### ISSUE TITLE
Incorrect PercentPipe formatting

### ISSUE THREAD

**Issue by pmatrosov** [angular/angular#20136]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
PercentPipe sometime incorrectly interprets digitInfo's minFractionDigits parameter. It outputs text like minFractionDigits=maxFractionDigits.
`{{ 0.12345674 | percent : '0.0-10' }}` outputs `12.3456740000 %` (this is error)
`{{ 0.12345678 | percent : '0.0-10' }}` outputs `12.345678 %` (this is ok)

## Expected behavior
`{{ 0.12345674 | percent : '0.0-10' }}` should output `12.345674 %`
`{{ 0.12345678 | percent : '0.0-10' }}` should output `12.345678 %`

DeprecatedPercentPipe works as expected.

## Minimal reproduction of the problem with instructions
Create empty component and add above code to it

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [X] Chrome (desktop) version 62.0.3202.75
- [X] Firefox version 56.0
- [X] IE version 11.0.9600.18816
 
</pre>

**Comment by ocombe** [comment]
Confirmed https://stackblitz.com/edit/angular-dfryge

**Comment by ocombe** [comment]
Ok so the problem comes from javascript, try to do `0.12345674*100` and you get `12.345673999999999` instead of `12.345674`, not sure if we can fix this

**Comment by trotyl** [comment]
Could it be fixed by using native `Number#toFixed()` method? Like:

![image](https://user-images.githubusercontent.com/6059170/32652110-2dec75fa-c63e-11e7-9325-abc85330fe2a.png)

**Comment by ocombe** [comment]
I've used something similar that seems to do the trick:

```ts
function multiFloats(a: number, b: number){
  const aPow = Math.pow(10,String(a).length - String(a).indexOf(DECIMAL_SEP) - 1);
  const bPow = Math.pow(10,String(b).length - String(b).indexOf(DECIMAL_SEP) - 1);
  return (a * aPow) * (b * bPow) / (aPow * bPow);
}
```

**Comment by trotyl** [comment]
That's awesome

**Comment by vicb** [comment]
What we discussed with @ocombe relative to 

> `{{ 0.12345674 | percent : '0.0-10' }}` should output 12.345674 %

in JS `console.log(0.12345674 * 100)` is `12.345673999999999`

So the pipe result should be either `12.3456739999` or `12.345674` (not sure what we are supposed to do with rounding) but `12.3456740000` is clearly wrong.

@ocombe will fix this but he will not fix floating point number in JS.
