### ISSUE TITLE
Convert properties in @Component/@Directive to Arrays

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2013]
Currently the `properties`, (and somewhat `events`) in `@Directive` take a `Map` rather then an `Array`.

The argument for an list rather then a map, is that most of the time we should not be renaming the properties, which creates a lists such as these:

```javascript
{
  'title': 'title',
  'name': 'name',
  'nickname': 'nick',
  'age': 'age'
}
```

These are necessarily wordy! In addition it is hard to spot the renames. Did you notice it? Instead we should have this syntax:

```javascript
['title', 'name', 'nickname <= nick', 'age']
```

This syntax is less wordy, and it makes the renames very explicit. It also encourages developers to keep the renames to a minimum. 

This should apply to both: `properties` and `events`

**Comment by gdi2290** [comment]
what about pipes?
```es6
@Component({
  selector: 'details',
  properties: [
    'model <= data | async'
  ]
})
class Details {}
```
What about with a pipe? What about something like this `model < data | async` using `<` rather than `<=` so the bash-like syntax is more consistent 


```es6
@Component({
  selector: 'details',
  properties: [
    'model < data | async',
    'name < ngName'
  ]
})
class Details {}
```

**Comment by tbosch** [comment]
Yeah!

**Comment by adamdbradley** [comment]
Good call. Every example we've had to update since this change was using the same key/value. :+1:

**Comment by shlomiassaf** [comment]
Not related, but I find this issue a wonderful example of open source sugar.
Simple technical issue, related to developers, easy to explain , easy to understand.
