### ISSUE TITLE
Angular cannot use relative path to find resources

### ISSUE THREAD

**Issue by HalfLegend** [angular/angular#20137]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

My app structure is like:  
    index.html
    main.ts
    app
     |--main.component.html
     |--main.component.ts
     |--app.module.ts
     |--note.png
    ... etc

  
I want to use the note.png in main.component.html which is under the same folder.
I tried `<img src="note.png"/>` and `<img src="./note.png"/>`, but the picture is not shown.
The browser goes to `/note.png` to search for the picture.

## Expected behavior

Because main.component.html is under /app/ , so if I write ./note.png, it should use /app/note.png instead of /note.png. 

I cannot use `<base href/>` because I will use the router feature, with the same parent page, who will have a `<base href/>` sharing with all its children pages.

 I don't want to create a asserts folder to store all the pictures of all the pages. In contrast,  I want to put my images in the same folder with ts and html who use the image.

Angular is different from the normal html structure.   
In normal html, if we visit main.component.html, the url will be like /app/main.component.html. So if we use relative path in the html, it will goes to /app/note.png.   
Whereas in Angular, the url is /index.html, but actually the page /app/main.component.html will be shown. So './note.png' is relative to the url /index.html

I also posted a question on StackOverflow, but no solution: https://stackoverflow.com/questions/47089303/how-to-find-resource-in-relative-path-in-angular

Further more, url in style should also work fine:  `style="background-image: url(note.png); "`

## Minimal reproduction of the problem with instructions

It's easy, just create a default project use `ng new test`
Then, just add  `<img src="note.png"/>` into the default app.component.html  and add a picture named "note.png" under the same folder.

## What is the motivation / use case for changing the behavior?

It has no problem with the traditional html structure but has problem in angular. This is the motivation

## Environment

<pre><code>
Angular version: all      my current version: 5.0.0

Browser:
    All 
 
</code></pre>
Others:
     Perhaps, Angular can provide a pipe, which may covert the relative path to the correct absolute path as per the path of the html file.
     For example:
    `<img src="'./note.png' | urlPipe"/>`  => /app/note.png

**Comment by Toxicable** [comment]
This isn't an issue with Angular.
You're having trouble with how your application is bundled.
Take a look at the CLI's documentation on the matter: https://github.com/angular/angular-cli/wiki/stories-asset-configuration
