### ISSUE TITLE
Ngfor is not working 

### ISSUE THREAD

**Issue by MahaSannasi** [angular/angular#20133]
**device-search.component.ts:**
export class DeviceSearchComponent {

 records:any;
  public setRecord(res:any){
    console.log('device sarch');
    console.log(res);
     this.records = res.entries;
    console.log(this.records); -- here its returing data
  }

**REST CALL :**
showDeviceSearch(){
    console.log(this.dbs.vendor);
    this.bs.basicSearch(this.dbs).subscribe( (res:any) => {
      console.log('res');
      console.log(res);
      this.deviceSearchComponent.setRecord(res);
    });

basicSearch(bs:DevicesBasicSearch): Observable<DevicesBasicSearch> {
	let headers = new Headers({ 'Content-Type': 'application/json' });
        let options = new RequestOptions(
          { headers: headers })
       return this.http.post('search/basicSearch', bs, headers).map((res: Response) => res.json());
      // console.log(res);  }
       
       
    }   
 

export class DevicesBasicSearch {
    public vendor: String;
    public socCode ?: String;
    public partNumber ?: string;
    public typeList: string[];
    public model ?: string;
    public sysObjectID ?: string;
    public family ?: string;
    public catalogIdHide ?: boolean;
    public lynxCertifiedOnly ?: boolean
    constructor(){}
}

ACCESSING the record in html (device-search.component.html):

<tr *ngFor="let item of records">
                       
                            <td height="30">{{item.deviceFamily}}</td>
                            <td height="30">{{item.catalogId}}</td>
                            <td height="30">{{item.manufacturerPartNumber}}</td>
                            <td height="30">{{item.vendor}}</td>
                            <td height="30">{{item.entityType}}</td>
                            <td height="30">{{item.model}}</td>
                            <td height="30">{{item.socCode}}</td>
                        </tr>

I am not getting anything in html.. 

Can anyone please help me what is missing

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
