### ISSUE TITLE
Adding Pug Support for angular templates

### ISSUE THREAD

**Issue by SalemCode8** [angular/angular#20147]
It's will be so beautiful if there is support for Pug Template Engine in Angular

**Comment by vicb** [comment]
Build process could certainly pre-process the template in some way - not sure what you mean by "Pug support" exactly.
Anyway as said might be something to consider as a build step but it will never be supported by the core itself.

**Comment by SalemCode8** [comment]
I Know, I mean to be able to use .pug file as template for angular component
