### ISSUE TITLE
Angular 5 should have typescript 2.6 support 

### ISSUE THREAD

**Issue by xnnkmd** [angular/angular#20146]
## I'm submitting a...

<pre><code>
[x ] Feature request
</code></pre>

## Current behavior
The new angular 5 unfortunately use an old version of 2.4.x version typescript which lacks many benefits that newer version of typescript has (better type checking, refactorings etc)

## Describe what the desired behavior would be.
It would be great if angular 5 could upgrading to typescript 2.6 (supporting strict mode). The additional strict function typing benefits would be very much aligned with angular 5 goal of improving static checking of templates etc.

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/19587#issuecomment-337713553

**Comment by vicb** [comment]
It will come at some point.

**Comment by mmc41** [comment]
@vicb I don't understand why you want to close issues before they are fixed? How else can we track things?

**Comment by trotyl** [comment]
I guess https://github.com/angular/angular/issues/19587 is tracking it for now.

**Comment by xnnkmd** [comment]
See also #20653
