### ISSUE TITLE
Cucumber on Angular

### ISSUE THREAD

**Issue by ja6a** [angular/angular#20145]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior

Unit testing is performed using Jasmine specifications.  

## Expected behavior

I want to use Cucumber feature files on my Angular project. I want to implement the feature scenarios at the unit testing level. I do not want to use Protractor or Selenium, i.e. this is not for integration or end-to-end (e2e) testing. I want to use the Angular testing tools that I normally use with Jasmine unit tests for mocking, e.g. TestBed.

## What is the motivation / use case for changing the behavior?

To support features expected by the enterprise: 
* The ability to use Cucumber feature files specified by the business.
* These feature files could be shared by the server side. 
* In a CI environment: to allow dashboards detailing the status of the *client-side* Cucumber feature development.

With Jasmine there is a tight coupling between the text used to describe the test and the implementation.
## Environment

<pre><code>
Angular version: 2+

**Comment by vicb** [comment]
Nothing is planned on our side. Could be a community effort.
