### ISSUE TITLE
Webpack guide need update to Angular 5.0.0

### ISSUE THREAD

**Issue by benbro** [angular/angular#20141]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

https://angular.io/guide/webpack

## Current behavior
The webpack introduction guide is using Angular 4.2.0.

## Expected behavior
The guide should use Angular 5.0.0

Shouldn't the docs be part of the release process?

**Comment by Alberto2686** [comment]
The guide should include AoT compilation + tree-shaking with AngularCompilerPlugin (@ngtools/webpack) and support chuncks for lazy-loaded modules.

**Comment by SebastianStehle** [comment]
Is the recommendation to use AOT compilation also for development?

**Comment by keyvhinng** [comment]
What's the entry point for the Webpack guide ? I can't find a link inside the docs portal to access webpack guide. I can only access through google.

**Comment by gkalpak** [comment]
See https://github.com/angular/angular/pull/20199#issuecomment-342078147.
