### ISSUE TITLE
Opening MatDialog from another MatDialog doesn't work in Safari

### ISSUE THREAD

**Issue by tpiros** [angular/angular#20155]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Opening a dialog from another dialog doesn't work in Safari

## Expected behavior

I'd expect the behaviour to be the same as in Chrome where a dialog can be opened from another dialog.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-1qxhep

If you check the two console.log() statements in safari the result looks different:

**Safari**

_First dialog info:_

`MatDialogRef {_overlayRef: OverlayRef, _containerInstance: MatDialogContainer, id: "dialog1", disableClose: false, _afterOpen: Subject, …}

_Second dialog info:_

`MatDialogRef {_overlayRef: OverlayRef, _containerInstance: MatDialogContainer, id: "dialog1", disableClose: false, _afterOpen: Subject, …}
`

**Chrome**

_First dialog info:_

`MatDialogRef {_overlayRef: OverlayRef, _containerInstance: MatDialogContainer, id: "dialog1", disableClose: false, _afterOpen: Subject, …}`

_Second dialog info:_

`MatDialogRef {_overlayRef: OverlayRef, _containerInstance: MatDialogContainer, id: "dialog2", disableClose: false, _afterOpen: Subject, …}`

Notice that for Chrome the 'id' parameter passed to the dialogs is properly picked up, for Safari I don't get the same behaviour and therefore Safari does not open the second dialog panel.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [X] Safari (desktop) version 11.0
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Hey @tpiros, are you sure this is a problem with angular itself and not with material2? You may want to report the issue over here https://github.com/angular/material2 👍
