### ISSUE TITLE
Merge injectables when creating ElementInjector

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#2015]
Currently we concatenate the `hostInjector` injectables before creating a ProtoElementInjector. This does not handle corner cases.

We need to handle the two scenarios.

## Scenario 1

We should throw when two directives instantiated on the same element declare the same injectable.

```
@Component({hostInjector: [bind(IService).toClass(ServiceA)]})
class ComponentA{}

@Component({hostInjector: [bind(IService).toClass(ServiceB)]})
class DirectiveB{}
```

## Scenario 2

We should take the hostInjector implementation if the same token is present in both the `hostInjector` and `viewInjector` configs. 

```
@Component({
  hostInjector: [bind(IService).toClass(ServiceA)],
  viewInjector: [bind(IService).toClass(ServiceB)]
})
class ComponentA{
  constructor(s:IService){}
}
```

**Comment by vicb** [comment]
closed via #2288
