### ISSUE TITLE
ng build --prod --aot --output-hashing none stuck at chunk asset optimization after Angular V 5 upgrade

### ISSUE THREAD

**Issue by rahulrsingh09** [angular/angular#20150]
After Upgrading to Angular Version 5 the aot compilation seems to be stuck at  92 % chunk Optimisation for ages.
 and Completes after a full 4 mins

```
Date: 2017-11-03T13:54:26.604Z
Hash: 35cf6c5f7a300435f807
Time: 222890ms
chunk {0} 0.chunk.js () 16.7 kB  [rendered]
chunk {1} main.bundle.js (main) 2.56 MB [initial] [rendered]
chunk {2} polyfills.bundle.js (polyfills) 63.8 kB [initial] [rendered]
chunk {3} styles.bundle.css (styles) 296 kB [initial] [rendered]
chunk {4} inline.bundle.js (inline) 1.36 kB [entry] [rendered]
```

Any reason for this slowness

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by gkalpak** [comment]
This sounds more like a cli issue (if at all). Could you repopen on https://github.com/angular/angular-cli/issues, providing the necessary details.
