### ISSUE TITLE
Angular 5.0.0 - *ngIf treats empty array as true

### ISSUE THREAD

**Issue by dc-m** [angular/angular#20161]
## I'm submitting a...
<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If you have an empty array  *ngIf treats as true.

## Expected behavior

Empty array returns false inside *ngIf 

## Minimal reproduction of the problem with instructions
Steps to reproduce:
create an array which is instantiated as an empty array.
create a div with an *ngIf of the array
http://plnkr.co/edit/4YM53mmnlpfyI3gouLc1?p=preview

## What is the motivation / use case for changing the behavior?
Previous version used same format

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.6.0
- Platform:  Windows

Others:
</code></pre>

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/19364, it's by design.

**Comment by dc-m** [comment]
Apologies hadn't seen this and wasnt in the documentation i read.

**Comment by trotyl** [comment]
Actually it's just keeping the same behavior as native JavaScript language, it should only be documented when not doing the same way. 😃

**Comment by dc-m** [comment]
Yeah I actually just read about the javascript version after you replied, was just use to the previous versions!  Will close this issue
