### ISSUE TITLE
No option to see the documentation for the version 4.x.x

### ISSUE THREAD

**Issue by aravindfz** [angular/angular#20166]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior 
No option for selecting 4.x.x version's documentation

![image](https://user-images.githubusercontent.com/22231525/32389936-70c8ec2e-c0f2-11e7-91d4-c5cd01acf1e0.png)

## Expected behavior 
Dropdown should have 4.x.x version as a option

## Minimal reproduction of the problem with instructions
Navigating to angular.io site 

## What is the motivation / use case for changing the behavior?
Have documentation for the previous versions.

**Comment by trotyl** [comment]
https://github.com/angular/angular/pull/20089 just merged 30mins ago, need time to build?

**Comment by tytskyi** [comment]
While it is true for main site, @aravindfz please use https://v4.angular.io/docs

**Comment by trotyl** [comment]
Since the PR already got merged, should it be closed? Even it was opened a little late than the PR.

**Comment by aravindfz** [comment]
@vicb the deployment is not yet done. Code changes are not reflected in the site

**Comment by trotyl** [comment]
All issues are closed on merge, not on release.
