### ISSUE TITLE
Not able to see styles in style.css

### ISSUE THREAD

**Issue by mastrauckas** [angular/angular#20163]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If I put a style in `style.css` it doesn't seem to show on the page.  For example if I put in
```
body {
  background-color: red;
}
```
However the background never goes to `red`.

The only workaround I have been able to find is to:

add `styles.css`  to the `styleUrls` and add `ViewEncapsulation.None`.

## Expected behavior
I should see my styles without adding  `styleUrls` and add `ViewEncapsulation.None` to my component.

## Minimal reproduction of the problem with instructions
* Add below line to `style.css` and the background will not `red`.
```
body {
  background-color: red;
}
```

## Environment
Angular 4.2.5

Browser:
All browsers I believe.
For Tooling issues:
- yarn version: 1.2.1
- Platform:  Windows

**Comment by vicb** [comment]
styles added to a component apply to that component only

**Comment by mastrauckas** [comment]
I never said the styles were added to the component.  `style.css` is the global style.

**Comment by mastrauckas** [comment]
Please reopen this because its an issue.

**Comment by trotyl** [comment]
Angular has nothing to do with `style.css`, if you think there's something wrong with Angular CLI, please open it there.

**Comment by mastrauckas** [comment]
I will try to explain this again.

When you a create project using the `angular cli`, it will create `styles.css` in the `src` directory.  

If I add any `style` to `styles.css` it will become global to all components.  So when I add
```
body {
  background-color: red;
}
```
Every component should have a `background` color of `red` without having to add `styles.css`  to every  `styleUrls` and adding `ViewEncapsulation.None`.  

However this is not happening.  They don't become global unless I add `styles.css` and `ViewEncapsulation.None`.

Even the text in the generated `styles.css` backs up what I am explaining:
```
/* You can add global styles to this file, and also import other style files */
```

**Comment by trotyl** [comment]
Please open a new issue if you have reproduction without using Angular CLI.

**Comment by mastrauckas** [comment]
@trotyl It is an issue with and without CLI.  Why should I recreate an issue that should never have been closed?
