### ISSUE TITLE
Angular 5.0.0 + AOT - ActivatedRoute.data does not include data from route config

### ISSUE THREAD

**Issue by jlowcs** [angular/angular#20160]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
With a route that contains a `data` properties, the content on that `data` is not present in the `ActivatedRoute.data` object with AOT, although it is present with JIT.

## Expected behavior
The behavior should be the same as with JIT.

## Minimal reproduction of the problem with instructions
Create a simple app with a simple path containing a `data` property.
```typescript
{
	path: 'mypath',
	component: MyComponent,
	data: { foo: 'bar' },
}
```

```
class MyComponent {
  constructor(route: ActivatedRoute) {
    route.data.subscribe((data) => console.log(data));
  }
}
```

When accessing `/mypath`, this code will output:
- { foo: 'bar' } with JIT
- {} with AOT

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [X] Chrome (desktop) version 61.0.3163.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.9.2
- Platform:  Windows 10

Others:
Using a custom toolstack, but the rest of the app works fine
</code></pre>

**Comment by jlowcs** [comment]
I just realized that I forgot to specify that we are bootstraping the app using `UpgradeModule` since part of our app is still in AngularJS.

**Comment by jlowcs** [comment]
I think I found the issue. It seems to be in our custom toolstack.

Our toolstack mostly uses `compiler-cli` to generate the `ngfactory` files.

It so happens that the `app-routing.ngfactory` file tries to import the `data` objects by importing them from the `app-routing` file. Since those objects are not exported, they are resolved as being undefined.

I assume that angular-cli also modifies the `app-routing` file?

**Comment by jlowcs** [comment]
I can confirm that `compiler-cli` does modify the `app-routing.module` file.

I was able to fix our tooling to use those modified files.

Therefore, this bug can be closed.

**Comment by MashB** [comment]
@jlowcs I'm still having similar issue with 5.1.0 , what is the workaround or fix for this issue ? , AOT returns data as {}

**Comment by jlowcs** [comment]
@MashB are you using angular-cli or a custom toolstack? Because there is no issue in the angular toolstack, therefore there won't be any fix.

**Comment by raizemm** [comment]
@jlowcs i'm having similar issue also with compiler-cli. Could you share how did you fix the issue?

**Comment by jlowcs** [comment]
@raizemm It all depends on how you're using compiler-cli. On my end, the only thing I had to change is to use all transformed files, instead of only the ngfactory files and the initial files. For instance app.module.ts is actually now transformed by compiler-cli (it wasn't in previous angular versions).
