### ISSUE TITLE
AOT compilation in Angular 5

### ISSUE THREAD

**Issue by vasyliv** [angular/angular#20174]
Hello all! Firstly thanks for your project. Have some problem with building a project, after transfer from angular 4.4.6 to Angular 5.0.0 the time of a building becomes too long, from 22 sec to 100 sec. How can I disable AOT compilation?

**Comment by SanderElias** [comment]
@vasyliv for the CLI's `ng serve` AOT is not yet enabled by default. I'm not 100% sure about `ng build` but if you want to turn it off you can use the `--no-aot` flag there.  

How many files does your project have?

**Comment by vasyliv** [comment]
I haven't got angular-cli, the problem was with typescript 2.6.1, after pin typescript to 2.5.3 the problem solved.
