### ISSUE TITLE
Update Tsickle to support 2.5 and 2.6 versions of TypeScript

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#20179]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior

Tsickle only works with 2.4 of TypeScript

## Expected behavior

Tsickle should work with 2.4, 2.5 and 2.6 of TypeScript.

**Comment by vicb** [comment]
@chuckjaz Does this belong here ? (thinking of https://github.com/angular/tsickle)

**Comment by e-cloud** [comment]
Track from tsickle, it can only support TS 2.5 for now. And hope Angular could support TS 2.6 soon.

**Comment by pkozlowski-opensource** [comment]
Angular supports TS 3.0.0 now.
