### ISSUE TITLE
{ updateOn: 'submit' } doesn't work when using with FormBuilder's group method

### ISSUE THREAD

**Issue by fiyazbinhasan** [angular/angular#20176]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

As the documentation states: when using the `{ updateOn: 'submit' }`, values of the `FormControl`s should only update when a submit event on the parent `FormGroup` is fired. This works well when you use a new instance of `FormGroup` . For example,

    form: FormGroup;

    constructor() {
        this.form = new FormGroup({
            email: new FormControl('', [Validators.required]),
            password: new FormControl('', [Validators.required])
        }, { updateOn: 'submit' })
    }

But the same example doesn't work, when using `FormBuilder`'s group method like the following:

    form: FormGroup;

    constructor(private fb: FormBuilder) {
        this.form = fb.group({
            email: new FormControl('', [Validators.required]),
            password: new FormControl('', [Validators.required])
        }, { updateOn: 'submit' })
    }

## Expected behavior

Since the `FormBuilder`'s `group` method is just a syntactic sugar that shortens `new FormGroup()`, in both cases it should give the exact behavior.

## Minimal reproduction of the problem with instructions

You can check the bug reproduction on this plunker:

http://plnkr.co/edit/mjtIHCy3fGOVauQFc7ed?p=preview.

## What is the motivation / use case for changing the behavior?

Most of the developers use the `FormBuilder` instead of newing up `FormGroup`. So, it would be nice to give them the exact behavior they want with `{ updateOn: 'submit' }` in both cases.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version 61.0.3163.100
- [x] Firefox version 56.0
- [x] Edge version 40.15063.674.0
 
For Tooling issues:
- Node version: 6.10.2 
- Platform:  Windows

**Comment by Toxicable** [comment]
duplicate #19163

**Comment by kara** [comment]
Yep, closing as dupe. We will add support for FB down the line.

**Comment by rdbhagat999** [comment]
Is this solved on v7?

**Comment by mehmettkocc** [comment]
@danzrou @rdbhagat999 
Here you can see this was fixed in #24599:
[https://github.com/angular/angular/blame/master/packages/forms/src/form_builder.ts](url)
