### ISSUE TITLE
Two set of docs for Angular 5

### ISSUE THREAD

**Issue by aravindfz** [angular/angular#20189]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Angular 5 documentation are seen in two url viz.,
           
1. [https://next.angular.io/docs](https://next.angular.io/docs)

2. [https://angular.io/docs](https://angular.io/docs)

## Expected behavior

One should be removed

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
https://next.angular.io/docs is sync to `@angular/*@next`, while the other is `@stable`.

**Comment by ocombe** [comment]
It's currently the same because we've just released v5. The branch 5.1.0 will be "next" soon.
