### ISSUE TITLE
"An asset cannot be written to a location outside of the output path" Error on upgrading to angular5

### ISSUE THREAD

**Issue by pankajsri03** [angular/angular#20183]
I have a perfectly working angular 4 app. Based on this doc https://angular-update-guide.firebaseapp.com/.
I updated my app. Now i am unable to start my app.
I get below mentioned error on serving the app.

An asset cannot be written to a location outside of the output path.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ccw-client-app@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ccw-client-app@0.0.0 start script

This is my package.json for reference:
"scripts": {
    "ng": "ng",
    "start-ng": "ng serve",
    "start": "node src/server/index.js",
    "build": "ng build",
    "build-dev": "ng build -dev",
    "build-local": "ng build -dev -e local",
    "build-test": "ng build -prod -e test",
    "build-prod": "ng build -prod -e prod",
    "serve": "ng serve -dev -e local -o",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "sme": "./node_modules/.bin/source-map-explorer"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/cdk": "2.0.0-beta.12",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/flex-layout": "^2.0.0-beta.9",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "2.0.0-beta.12",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@ngrx/store": "^4.0.3",
    "@ngrx/store-devtools": "^4.0.0",
    "angular2-jwt": "^0.2.3",
    "core-js": "^2.4.1",
    "devextreme": "^17.1.6",
    "devextreme-angular": "^17.1.6",
    "hammerjs": "^2.0.8",
    "jwt-decode": "^2.2.0",
    "msalx": "^0.1.1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.5.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.6.2",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~8.0.47",
    "codelyzer": "~4.0.0",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.2.0",
    "source-map-explorer": "^1.4.0",
    "ts-node": "~3.3.0",
    "tslint": "~5.8.0",
    "typescript": "~2.4.2"
  }

**Comment by ericmartinezr** [comment]
Please report cli's issues on its repo https://github.com/angular/angular-cli. Also make sure to respect the issue template :+1:

**Comment by palenicek** [comment]
@pankajsri03 The older cli version allowed to set 'outDir' property in '.angular-cli.json' file to point out of the project root. Reset this path to be within the project. Solved the issue for me.

**Comment by michael-lang** [comment]
In my case I want the build output outside of the CLI project.  I build it into an asp.net core website wwwroot folder so i can run live reload of the angular app served inside of the asp.net core website.  Why is this a new limitation that a CLI project cannot run outside of the CLI project folder?

**Comment by michael-lang** [comment]
n/m I see it will be fixed in the next release,

#8613

**Comment by sujoydc** [comment]
I am facing this issue even if I had downgraded the angular-cli to 4.3.4 and updated the outDir to some internal "../build" directory. Very strange. Does someone know how to fix this?

**Comment by michael-lang** [comment]
Check the version of the angular cli package.  The problem for me was with CLI version 1.5.4, not angular itself. See CLI issue 8613, angular/angular-cli#8613
