### ISSUE TITLE
Project with Angular 4, cli 1.4.9 built in jenkins earlier on, but now fails (code unchanged)

### ISSUE THREAD

**Issue by catull** [angular/angular#20180]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Code that has not changed was accepted 6 hours ago with our jenkins.
Now the nightly build failed, twice, see error log below.

## Expected behavior
Build must be successful.

## Minimal reproduction of the problem with instructions
Cannot disclose the source code, but will try to produce minimal repo.

## Environment

<pre><code>
Angular version: 4.4.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.0 LTS  
- Platform:  macOS 10.12.6 and Linux 2.6.x
- Angular 4 project is built in mvn, has successfully built since inception (almost 2 months into)

Others:

➜  ng git:(cd-dev npm install

> fsevents@1.1.2 install /Users/####/workspace/######/src/main/ng/node_modules/fsevents
> node install

[fsevents] Success: "/Users/#####/workspace/######src/main/ng/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@4.6.0 install /Users/######/workspace/######/src/main/ng/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/######/.npm/node-sass/4.6.0/darwin-x64-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/######/workspace/######/src/main/ng/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> node-sass@4.6.0 postinstall /Users/######/workspace/######/src/main/ng/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/######/workspace/######/src/main/ng/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine

> angular-ide@0.9.32 postinstall /Users/######/workspace/######src/main/ng/node_modules/angular-ide
> node ./scripts/post.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ngx-modal@0.0.29 requires a peer of @angular/core@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-modal@0.0.29 requires a peer of @angular/router@^3.0.0 but none is installed. You must install peer dependencies yourself.

added 1696 packages in 54.36s
parse_git_dirty:3: FLAGS: attempt to assign array value to non-array
➜  ng git:(cd-dev npm run build:prod

> integrator-ui@0.0.0 build:prod /Users/######/workspace/######src/main/ng
> npm run lint && ng build --environment prod

> integrator-ui@0.0.0 lint /Users/######/workspace/######src/main/ng
> tslint -p . -e 'node_modules/**'

Date: 2017-11-03T23:18:05.898Z
Hash: 53789ed37cc114f2ca6f
Time: 29625ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 379 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 217 kB [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 474 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 5.82 MB [initial] [rendered]

ERROR in Error: Metadata version mismatch for module /Users/######/workspace/######src/main/ng/node_modules/@swimlane/ngx-datatable/release/index.d.ts, found version 4, expected 3, resolving symbol AppModule in /Users/######/workspace/######src/main/ng/src/app/app.module.ts, resolving symbol AppModule in /Users/######/workspace/######src/main/ng/src/app/app.module.ts
    at syntaxError (/Users/######/workspace/######src/main/ng/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/Users/######/workspace/######src/main/ng/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/Users/######/workspace/######src/main/ng/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/Users/######/workspace/######src/main/ng/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/Users/######/workspace/######src/main/ng/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/Users/######/workspace/######src/main/ng/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/Users/######/workspace/######src/main/ng/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/######/workspace/######src/main/ng/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Users/######/workspace/######src/main/ng/node_modules/@ngtools/webpack/src/plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Users/######/workspace/######src/main/ng/node_modules/@ngtools/webpack/src/plugin.js:495:24)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integrator-ui@0.0.0 build:prod: `npm run lint && ng build --environment prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integrator-ui@0.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/######/.npm/_logs/2017-11-03T23_18_05_985Z-debug.log
parse_git_dirty:3: FLAGS: attempt to assign array value to non-array

**Comment by catull** [comment]
Just in case, here's package.json:

```json
{
    "name": "########",
    "version": "0.0.0",
    "license": "MIT",
    "scripts": {
        "start:dev": "npm run lint && ng serve --environment dev --deploy-url integrator-ui --proxy-config proxy.conf.json",
        "start:prod": "npm run lint && ng serve --environment prod --deploy-url integrator-ui --proxy-config proxy.conf.json",
        "build:dev": "npm run lint && ng build --environment dev",
        "build:prod": "npm run lint && ng build --environment prod",
        "test": "ng test",
        "lint": "tslint -p . -e 'node_modules/**'",
        "lint:old": "ng lint --type-check --force",
        "e2e": "ng e2e"
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "^4.4.6",
        "@angular/common": "^4.4.6",
        "@angular/compiler": "^4.4.6",
        "@angular/core": "^4.4.6",
        "@angular/forms": "^4.4.6",
        "@angular/http": "^4.4.6",
        "@angular/platform-browser": "^4.4.6",
        "@angular/platform-browser-dynamic": "^4.4.6",
        "@angular/platform-server": "^4.4.6",
        "@angular/router": "^4.4.6",
        "@swimlane/ngx-datatable": "^10.4.0",
        "@types/daterangepicker": "^2.1.16",
        "admin-lte": "2.3.11",
        "angular2-toaster": "^4.0.1",
        "auto-format": "^1.1.1",
        "core-js": "^2.5.1",
        "daterangepicker": "^2.1.25",
        "format-json-pretty": "^1.0.1",
        "moment": "^2.19.1",
        "ng2-codemirror": "^1.1.3",
        "ngx-admin-lte": "github:TwanoO67/ngx-admin-lte#1299604d4252902c99d626ec216c69db33a0995a",
        "ngx-modal": "0.0.29",
        "npm": "^5.5.1",
        "rxjs": "^5.5.0",
        "xml-beautifier": "^0.3.0",
        "zone.js": "^0.8.18"
    },
    "devDependencies": {
        "@angular/cli": "^1.4.9",
        "@angular/compiler-cli": "^4.4.6",
        "@angular/language-service": "^4.4.6",
        "@types/jasmine": "~2.6.0",
        "@types/jasminewd2": "~2.0.3",
        "@types/jquery": "^3.2.15",
        "@types/node": "8.0.47",
        "angular-ide": "^0.9.32",
        "codelyzer": "3.2.2",
        "jasmine-core": "~2.8.0",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "^1.7.1",
        "karma-chrome-launcher": "~2.2.0",
        "karma-cli": "~1.0.1",
        "karma-coverage-istanbul-reporter": "^1.3.0",
        "karma-jasmine": "~1.1.0",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.2.0",
        "ts-node": "~3.3.0",
        "tslint": "~5.8.0",
        "typescript": "2.6.1"
    }
}
```

Oh, and before you point out, TypeScript 2.6.1 is not officially supported, the project has used TypeScript 2.5 for quite a while, the code transpiled marvellously.

Just to humour you, changed typescript to "2.4.2", removed all of node_modules, `npm install`ed and tried to build it.  No luck, same error.

**Comment by clydin** [comment]
ngx-datatable was updated to support angular 5 hence the metadata version mismatch error.   Try pinning the version to 10.4

**Comment by catull** [comment]
Ey, @clydin long time not "read" ...

Indeed, setting "@swimlane/ngx-datatable": "10.4.0" does the trick.
