### ISSUE TITLE
bug(aio): incorrect recognization of normal words inside code block

### ISSUE THREAD

**Issue by trotyl** [angular/angular#20187]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The `json` in `package.json` would be recognized as `JsonPipe`.

![image](https://user-images.githubusercontent.com/6059170/32405345-8d46bd74-c131-11e7-9fac-8a2e5d283bc6.png)
![image](https://user-images.githubusercontent.com/6059170/32405349-99388720-c131-11e7-8589-443b7232a0e8.png)

Also same for `browser` (to api/animations/browser):

![image](https://user-images.githubusercontent.com/6059170/32405401-89c1a730-c132-11e7-9371-f9d3733725ce.png)

## Expected behavior

Leave it intact.

## Minimal reproduction of the problem with instructions

https://angular.io/guide/npm-packages

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by petebacondarwin** [comment]
Oh dear... sigh!

**Comment by gkalpak** [comment]
Please don't remove the auto-linkify-inside-code-blocks feature. It is lovely 🤗 
There shouldn't be many cases that are affected by this. I suggest we "blacklist" them (e.g. `!/\.json$/.test(code)`) if we can't come up with  better solution.

**Comment by petebacondarwin** [comment]
We can be marginally more effective for pipes and ensure that they are preceded by a `| ` pipe character.

**Comment by petebacondarwin** [comment]
I think it might also be worth insisting that there is real whitespace (not including `-`) around words that we match.

**Comment by gkalpak** [comment]
I think there are cases where there is no whitespace (thanks to `clang-format` :grin:); e.g. `FooThing|BarThing`.
👍 for being more strict for pipes.
