### ISSUE TITLE
https://next.angular.io/ always routing to docs

### ISSUE THREAD

**Issue by dnup1092** [angular/angular#20188]
## I'm submitting a...

<pre><code>
[ x] Documentation issue or request
</code></pre>

## Current behavior

Page is not allowing to navigate on any menu and always get routed to https://next.angular.io/docs

## Expected behavior

It should be routed to the correct navigation clicked/requested

## Minimal reproduction of the problem with instructions
1) Go to https://next.angular.io/
2) Try to navigate using the menus (even the default landing page for https://next.angular.io/ is docs)

## What is the motivation / use case for changing the behavior?

Not able to navigate on https://next.angular.io/ site

Browser:
- [ X] Chrome (desktop) version 48.0

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/19505

**Comment by dnup1092** [comment]
@ericmartinezr got that. So closing this.
