### ISSUE TITLE
ngc fails if using TS type alias

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#20185]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Running `ngc` on code that uses TS type alias (`export type SomeType = string | null | undefined`) generates js files that export the type as well.

## Expected behavior

It should not generate code that exports types (or interfaces).

## Minimal reproduction of the problem with instructions

You can clone [potion-node](https://github.com/biosustain/potion-node/tree/next) and just run `npm run build:standalone`. This will generate a `out-tsc/ng-es2015` folder with the results of the build.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.6  
- Platform:  Mac 

Others:

</code></pre>

**Comment by Toxicable** [comment]
Angular isn't tested with or compatible with TS versions greater than 2.4, while you don't get any exceptions you get other behaviour as you see. Drop it back down to the supported version and try again, let us know if the problem still occurs there

**Comment by rolandjitsu** [comment]
I can confirm that was the issue. Using `2.4.2` makes the issue go away, using anything above that will cause problems.

But it would be nice to see some updates on the TS version, there are 2 minor versions ahead and there are some useful features added.

**Comment by trotyl** [comment]
@rolandjitsu Explained in https://github.com/angular/angular/issues/19587#issuecomment-341849875

**Comment by vicb** [comment]
@rolandjitsu it will come at some point
