### ISSUE TITLE
我集成了zorro一个快速开发项目，目前升级到angular5.0，道友们拿去随便用

### ISSUE THREAD

**Issue by liepeng328** [angular/angular#20191]
I've integrated Zorro, a quick development project, which is now upgraded to angular5.0, and friends are using it freely

开源中国： https://gitee.com/lovepeng/angluar-base

github： https://github.com/liepeng328/angular-base

**Comment by trotyl** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by liepeng328** [comment]
谢谢，知道了
