### ISSUE TITLE
docs(aio) Tour Of Heros links to wrong setup

### ISSUE THREAD

**Issue by UnwarySage** [angular/angular#20192]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

https://angular.io/tutorial/toh-pt1
the Tour Of Hero tutorial links to the old quick-start guide, not the present angular CLI one.
setup link under first heading goes to https://angular.io/guide/setup

## Expected behavior

The link should go to https://angular.io/guide/quickstart

## Minimal reproduction of the problem with instructions
go to https://angular.io/tutorial/toh-pt1

## What is the motivation / use case for changing the behavior?

Pointing new users to a deprecated repository from the official tutorial is embarassing to the project at best, and confusing to the users.

## Environment
Any
<pre><code>
Angular version: 4+

It is in the docs, not dependent on version except for major changes,
Browser:
- [x ] Chrome (desktop) version XX
- [x ] Chrome (Android) version XX
- [ x] Chrome (iOS) version XX
- [x ] Firefox version XX
- [ x] Safari (desktop) version XX
- [x ] Safari (iOS) version XX
- [ x] IE version XX
- [ x] Edge version XX

**Comment by Foxandxss** [comment]
The new guide is still in a PR, will be merge soon. No worries

**Comment by Drag13** [comment]
Any news?

**Comment by Foxandxss** [comment]
Is there anything wrong?

**Comment by Drag13** [comment]
Just rechecked - all is great, sorry for the false alarm.
