### ISSUE TITLE
Why are the tutorials obsolete?

### ISSUE THREAD

**Issue by splincode** [angular/angular#20194]
AngularJS had a very good documentation and the tutorial was amazing. After “Phonecat App” tutorial you perfectly understood what exactly was AngularJS and how to use it. And it was clearer than any “Tour of Heroes”. 

https://angular.io/tutorial/toh-pt1

The examples refer to the second version and are morally obsolete, they are confusing (if I use angular-cli, the directories do not correspond to the current realities at all).

![screenshot_9](https://user-images.githubusercontent.com/12021443/32409076-bf448c00-c1b5-11e7-876e-87df93204fa0.png)

The tutorial needs to be rewritten with examples of use on Angular CLI.

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/20192#issuecomment-341916585

**Comment by ocombe** [comment]
Hello, the new docs are coming in the next days, some have already been merged but it's a lot of work because we rewrote all of the guides and there's a LOT of them.
