### ISSUE TITLE
Version 4 in the documentation dropdown available only in next.angular.io

### ISSUE THREAD

**Issue by aravindfz** [angular/angular#20190]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

 The option is seen in next.angular.io/docs 
![image](https://user-images.githubusercontent.com/22231525/32406128-b34b999c-c198-11e7-8ad3-8dccfc6e1134.png)

## Expected behavior

It should be seen in all urls
Not present in angular.io/docs
![image](https://user-images.githubusercontent.com/22231525/32406137-cfaeff02-c198-11e7-8de2-1c1d04236c09.png)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
The current angular.io is at 678d1cfae13ca643fbc5d1c7cc2fdcf5076d563a of [5.0.x](https://github.com/angular/angular/compare/5.0.x) branch, while 1bb0333c23985be8e5d2049c3bc2e3806286364b already merged to it successfully.

Seems everything is fine, except angular.io is not currently update to latest commit of stable yet.

**Comment by ocombe** [comment]
Yes, we need a successful build to generate the new aio website and we're having troubles with our CI right now. Should be fixed soon.

**Comment by Toxicable** [comment]
this is fixed now, can be closed
