### ISSUE TITLE
Angular 5 Serving Universal

### ISSUE THREAD

**Issue by lexcaraig** [angular/angular#20195]
By following the documentation from angular.io the building of the projects seems to be okay but when I am serving it with `npm run serve:universal` im getting the following error.

![image](https://user-images.githubusercontent.com/15936424/32411072-cc95bc20-c18e-11e7-871c-1d8c828ab038.png)

^Above image is from the angular documentation.

How can I fix this? Thanks a lot!

**Comment by Toxicable** [comment]
Upgrade `@nguniversal/express-engine` to version `5.0.0-beta.5`

**Comment by lexcaraig** [comment]
Here is my `package.json` file

`
{
  "name": "pwa-test",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "build:universal": "npm run build:client-and-server-bundles && npm run webpack:server",
    "serve:universal": "node dist/server.js",
    "build:client-and-server-bundles": "ng build --prod && ng build --prod --app 1 --output-hashing=false",
    "webpack:server": "webpack --config webpack.server.config.js --progress --colors"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/platform-server": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@nguniversal/express-engine": "5.0.0-beta.5",
    "@nguniversal/module-map-ngfactory-loader": "^1.0.0-beta.3",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.2",
    "ts-loader": "^3.1.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.5.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}
`

I deleted first the `node_modules` to reinstall everything.

running `npm run build:universal` and this give me the error
![image](https://user-images.githubusercontent.com/15936424/32411218-fdd9d10a-c192-11e7-8afe-dd7493e7571f.png)

Should I also upgrade the `"@nguniversal/module-map-ngfactory-loader": "^1.0.0-beta.3"` to `"@nguniversal/module-map-ngfactory-loader": "5.0.0-beta.5"`

^When I did the `npm run build:universal` works properly.

So I think, `@nguniversal` package version should be parallel with the other `angular` packages upon creation of the project with `ng new <app-name>`

Anyway, thanks a lot @Toxicable !

**Comment by Toxicable** [comment]
yes upgrade them both to `5.0.0-beta.5`

**Comment by lexcaraig** [comment]
I'm closing this issue. Thanks!
