### ISSUE TITLE
Require all injectable Types to have @Injectable annotation

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2020]
If a Type is referenced in the injector it needs tohave `@Injectable` or the DI system should throw (Both, Injector as well as ElementInjector). Should probably be done during the `ResolvedBinidng` creation.

**Comment by ewinslow** [comment]
As an outsider, it's not obvious to me why this should be the case.

**Comment by vicb** [comment]
@ewinslow this is only required when you need to x-compile to Dart: to keep the size of the generated JS reasonable, mirrors are disabled in Dart and we rely on transformers to generate the required metadata info at build time. Only class tagged with `@Injectable` will be grabbed by the transformers.

**Comment by ewinslow** [comment]
Thanks for the context!

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
