### ISSUE TITLE
Custom Validator example on angular.io directive selector issue.

### ISSUE THREAD

**Issue by MumblesNZ** [angular/angular#20206]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Custom validator in Template-Driven Form example doesn't work in https://angular.io/guide/form-validation & https://embed.plnkr.co/?show=preview. The directive selector needs to be updated to forbiddenName or the rest of the example needs updating to reflect the use of appForbiddenName selector.

## Expected behavior

"Name cannot be Bob." Error shown in plunker when template-driven form is filled in. 

## Minimal reproduction of the problem with instructions

To reproduce, go to  https://embed.plnkr.co/?show=preview and type in bob in the template driven form name example. 

## What is the motivation / use case for changing the behavior?

Less confusion for beginner coders.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
Good catch 👍

**Comment by LeiLiTroy** [comment]
Nice, found the same thing. Here is how I fix it. Add 'appForbiddenName' as alias name for input and on the view just use [appForbiddenName]="hero.name"
```
Inside direct file
@Directive({
  selector: '[appForbiddenName]',
  providers: [{provide: NG_VALIDATORS, useExisting: ForbiddenValidatorDirective, multi: true}]
})
export class ForbiddenValidatorDirective implements Validator {
  @Input('appForbiddenName') forbiddenName: string;

  validate(control: AbstractControl): {[key: string]: any} {
    return this.forbiddenName ? forbiddenNameValidator(new RegExp(this.forbiddenName, 'i'))(control)
                              : null;
  }
}

In the view file:
 <input id="name" name="name" class="form-control"
               required minlength="4" [appForbiddenName]="hero.name"
               [(ngModel)]="hero.name" #name="ngModel" >
```

**Comment by kapunahelewong** [comment]
This is also referenced in #20234. I invited that OP to submit a PR but either of you @MumblesNZ or @LeiLiTroy are welcome to, too. Please feel free to tag me in the PR if you do.

**Comment by MumblesNZ** [comment]
I think @LeiLiTroy solution is the way to go. @LeiLiTroy can you submit a PR? Otherwise I can do it but just might take me a while.

**Comment by MumblesNZ** [comment]
Hey @kapunahelewong I've made the changes locally and have been trying to create a Pull Request as per https://github.com/angular/angular/blob/master/CONTRIBUTING.md . I'm getting permission errors when I try to push the branch which I've made the changes on. This is the first time I've used the PR mechanism, any advice? 

![image](https://user-images.githubusercontent.com/5422194/32757354-fbf011d4-c943-11e7-8dfb-ab348b986ef7.png)

**Comment by kapunahelewong** [comment]
Hi @MumblesNZ, you'll need to fork Angular/angular so that you have a fork in your own GitHub account. Then, create a branch for your work and push up to your fork. You then create the PR from there. Does that help? If you're still stuck, let me know. I'm happy to help you through the process.

**Comment by MumblesNZ** [comment]
Thanks @kapunahelewong that should do it, thought a fork might be required but didn't see a mention in the contribution guide, must just be common knowledge for PR (that I don't have).

I'm just fixing up the e2e tests and will complete the PR shortly.

**Comment by egavard** [comment]
Hi,

Is there any way to add informations about Async Validators ? Such as provider to use is NG_ASYNC_VALIDATORS and not NG_VALIDATORS ?

Regards

**Comment by kapunahelewong** [comment]
@egavard Good idea. If you were so inspired you could add it to the API entry or in the Forms Validation doc in a PR. If you do, please tag me in it. That way I can help make sure the docs team is aware. What do you think?

**Comment by egavard** [comment]
@kapunahelewong No problem I'll prepare a PR on this subject.
Thank you for your concern

**Comment by kapunahelewong** [comment]
@egavard Great! I'll be on the lookout and make comments on it when you're ready to make sure it sticks to our docs guidelines (if needed). Thank _you_.
