### ISSUE TITLE
[Feature request] - Accept an object as parameter for i18n pipes

### ISSUE THREAD

**Issue by dev054** [angular/angular#20205]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I18n pipes in Angular 5 are supporting the locale and it's great, however it's always the **latest** parameter, even if all others arguments (params) are optional. 

Let's take [**DatePipe**](https://angular.io/api/common/DatePipe) as an example:

To pass a specific locale you have to pass all arguments to pass the _locale_, instead of only what you want (since all arguments are optional):

`dateVar | date: 'shortDate': null: 'fr'`

... but what if we could only pass only what we want? 

**Solution:**

I think the `DatePipe` (and others _pipes_ of course) could accept an `object`, like this:

`dateVar | date: { locale: 'fr' }`

## Expected behavior
I'd expect more flexibility in passing arguments to built-in pipes.

**Comment by vicb** [comment]
The `date` pipe is pure, meaning that it will only be re-evaluated if one of the argument changes.
If one of the arg is an array it might become confusing & bug prone.
