### ISSUE TITLE
Interpolation stop working when use {ngZone: 'noop'}

### ISSUE THREAD

**Issue by SteveZheng-BSFT** [angular/angular#20204]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

With the change {ngZone: 'noop'} on bootstrap (new 'Zone speed improvement'), both interpolation syntax and [innerHTML] stop working

## Expected behavior

Bypass zones entirely should not affect interpolation

## Minimal reproduction of the problem with instructions

interesting thing is, interpolation on app.component isn't affected at all. But all other module's component can't use {{}}, even directly use {{'test'}}

## What is the motivation / use case for changing the behavior?

bypass ngzones improving performance

## Environment
dev
<pre><code>
Angular version: 5.0.0

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ x ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ x ] Safari (desktop) version XX
- [ x ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.3  
- Platform:  mac 

Others:

</code></pre>

**Comment by Toxicable** [comment]
By turning off Zones you have to manually trigger Change Detection somehow.
Without Zones Angular has no idea when to run Change Detection.
This is not something I would recommend doing without specific knowledge no how Change Detection works and how Zones works

**Comment by SteveZheng-BSFT** [comment]
@Toxicable thanks!
