### ISSUE TITLE
failed to read json file angualr/common/locales/zh.metadata.json about angular language service

### ISSUE THREAD

**Issue by wzengguang** [angular/angular#20207]
hello:
      now , I use angular5. I use vsCode and angular language service. but this extension has a error output "failed to read json file angualr/common/locales/zh.metadata.json", and this extension is out of work.
     I find this file with a value of "[null]".
     when I  alter this value "[null]" to "[]",  this error is disappear.  and this extension  work well.

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
