### ISSUE TITLE
Changes to a `Map` are not detected unless `core-js/shim` is imported

### ISSUE THREAD

**Issue by cheapsteak** [angular/angular#20208]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Changes to a `Map` are not detected unless `core-js/shim` is imported

## Expected behavior

Changes to a `Map` should not require importing `core-js/shim` on browsers with existing support for `Map`s

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/LP7SEMJiIuK1JWzHHk8d?p=preview

Click on the "click me" button. Nothing happens. 

Add `<script src="https://unpkg.com/core-js/client/shim.min.js"></script>` to the head of index.html, and it will work

## What is the motivation / use case for changing the behavior?
Maps and WeakMaps are useful
Their changes may be easy to detect too? have to call `set` on them

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version  61.0.3163.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
This isn't an issue with Angular.
There is a difference between how a `Map` is implemented in Chrome and other browsers compared to the shim you're using.
Take this example in chrome:
```
var m = new Map()
m.set(1, 2)
JSON.stringify(m) //"{}"
```
yet with `core-js`'s one it a nested array

Now Chrome correctly implements `Map` as can be seen here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
So I'm inclined to think that their implementation here is correct

**Comment by tytskyi** [comment]
@Toxicable @vicb therefore it is better to avoid using `Map` for templates, right?

**Comment by Toxicable** [comment]
I personally wouldn't recommend it.
That JSON issue being one reason, but since you don't usually display JSON to users, less so.
The reason why I wouldn't just a Map in your template is becasue you cant use it with ngFor due t othe lack of order
