### ISSUE TITLE
Provide a way to identify item of FormArray other than index

### ISSUE THREAD

**Issue by adwd** [angular/angular#20210]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Index of array seems to be only way to identify item of `FormControl` in `FormArray`.
If a form has sort functionality, there is no way to identify sorted items.

```js
ngOnInit() {
  this.service.fetchTodos.subscribe(todos => {
    // todos: [ { id: 1, content: 'foo', sortNo: 0 }, { id: 2, content: 'bar', sortNo: 1 } ]
    this.form = this.fb.group({
      // user can edit content and sortNo by drag&drop
      todos: this.fb.array(todos.map(t => t.content)),
    });
  });
}

onSubmit() {
  const value = this.form.value;
  // { todos: [ 'foo yay', 'barrr' ] }
  // if todos are sortable, { id: 1, content: 'foo yay', sortNo: 0 } or { id: 2, content: 'foo yay', sortNo: 0 } is indeterminable
  ...
}
```

## Expected behavior

`FormControl` or `AbstractControl` has a way to identify themselves, ex: `FormControl#id` like

```js
ngOnInit() {
  this.service.fetchTodos.subscribe(todos => {
    // todos: [ { id: 1, content: 'foo', sortNo: 0 }, { id: 2, content: 'bar', sortNo: 1 } ]
    this.form = this.fb.group({
      todos: this.fb.array(todos.map(t => { value: t.content, id: t.id })),
    });
  });
}

onSubmit() {
  const value = this.form.value;
  // { todos: [ 'foo yay', 'barrr' ] }

  const controls = this.form.get('todos').controls.map((c, i) => { id: c.id, value: c.value, sortNo: i });
  // [ { id: 2, value: 'foo yay', sortNo: 0 }, { id: 1, value: 'barrr', sortNo: 1 } ]
}
```

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-zcvvg4

## What is the motivation / use case for changing the behavior?

I want to sort items of FormArray

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [x] Chrome (desktop) version 61
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.2.1  
- Platform:  Mac 

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@adwd ... how would you use such an `id` ... when `FormArray` is an array ... cycling around the array? From any point of view you need some transformation vector for it so you can use it right now ...

**Comment by KostyaTretyak** [comment]
I have a similar problem after applying pipe to `FormArray`.

How about adding property `index` to all items of [FormArray](https://angular.io/api/forms/FormArray)?

**Comment by adwd** [comment]
@mlc-mlapis I don't want to manage to arrays (original todos and form array). If FormControl has something to identify itself, I think it is possible. sorry if I misunderstood what you mean, I'm not English speaker 😇

**Comment by adwd** [comment]
@KostyaTretyak In addition to index, I start to think that something like `extra: any` field might be useful. If I want a form array of checkbox with label, I have to iterate both form array and todos array. If FormControl has `extra: any` field, I can add label text to it. example code is here -> https://stackblitz.com/edit/angular-ygbog3?file=app/todos-form/todos-form.component.ts

**Comment by mlc-mlapis** [comment]
@adwd ... hmm, you sure what exactly you want to do but still ... if you have an array then you have to lookup its elements somehow ... if you don't want to use just sequential order. How will you do that if elements are `FormGroups` and not primitive values?

So in any way you need a transformation vector that will map each array element (FormGroup) index = sequential order inside the array, to some of your unique value = part of each FormGroup that is important from the app point of view.

Then you have the original `FormArray` with original elements order and the vector that could re-ordered in any way but still keeping the relation to the original FormArray by the index.

So you can always lookup each element (FromGroup) from the original `FormArray` using the index.

**Comment by adwd** [comment]
I handled this by another way, so closing this issue.

**Comment by annuranjan** [comment]
@adwd Could you please tell me how did you do it? Thank you!

**Comment by annuranjan** [comment]
Never mind, I found the solution too.
I used "findIndex" method of the abstract control: 
index = (<FormArray>this.myForm.get('myFormArray')).controls.findIndex(x => x.value.id === myConditionId);

**Comment by pepemiso16** [comment]
@annuranjan , where did you get  x.value.id and myConditionId

**Comment by annuranjan** [comment]
@pepemiso16, here's the link for _findIndex()_ method: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex
As you know "controls" is an array of child controls. I have used findIndex() on _controls._ `x => x.value.id === myConditionId` is just my testing function. It simply means that findIndex() will return the index of the first _x_, whose x.value.id === anyIdIwantToTestAgainst.
