### ISSUE TITLE
*ngIf closes surrounding <p> 

### ISSUE THREAD

**Issue by amylinn** [angular/angular#20218]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Placing an `*ngIf` inside a `<p>` element in html throws an error: 
`Unexpected closing tag "p". It may happen when the tag has already been closed by another tag.`

## Expected behavior
I expect `*ngIf` not to close my `<p>`.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/wWaqrKFBWtpbeLvCbGPU
```
<p>
  <div *ngIf=""></div>
</p>
```

## What is the motivation / use case for changing the behavior?
I'd like to use `*ngIf` inside a `<p>`.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version  61.0.3163.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 54.0
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Windows

</code></pre>

**Comment by skreborn** [comment]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p), only phrasing content is allowed within a `<p>` element. Angular might be enforcing that rule more than your browser would otherwise, but it's a rule you should be playing by anyway.

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/6652, https://github.com/angular/angular/issues/13217, https://github.com/angular/angular/issues/5540, https://github.com/angular/angular/issues/6648

**Comment by amylinn** [comment]
I searched for an hour, but didn't find that issues. Need to improve my google-fu. 
Thanks @ericcarraway, @skreborn
