### ISSUE TITLE
Remove duplicate error messages from the build

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#2021]
currently there are several layers in our build system that log and rethrow exceptions, we need to unify these and suppress errors (or stack traces for errors) so that the output is easy to understand and doesn't contain duplicate messages or useless stack traces.

Sources of exceptions/exception logging:
- broccoli plugins
- angular_builder.ts
- gulp's runSequence
- gulp's tasks

common scenarios to tackle:

interactive/watch mode:
- [x] typescript compilation error
- [x] traceur compilation error
- [x] karma browser test failure/error (`gulp test.unit.js`)
- [x] jasmine test failure/error (`gulp test.unit.cjs`)
- [ ] ts2dart errors
- [x] dart unit tests failures/errors

ci mode:
- [x] typescript compilation error
- [x] traceur compilation error
- [x] karma browser test failure/error (`gulp test.unit.js`)
- [x] jasmine test failure/error (`gulp test.unit.cjs`)
- [x] ts2dart errors
- [x] dart unit tests failures/errors

WIP branch resolving some errors: https://github.com/angular/angular/compare/master...IgorMinar:tripple-errors?expand=1

**Comment by btford** [comment]
As far as I can tell, this eliminates the rest of the errors I was seeing. @IgorMinar – Is there somewhere else I should look?
