### ISSUE TITLE
Angular v5 ngc does not produce metadata in .js files

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#20217]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have Angular components and modules in separate "library". Library is compiled using `ngc` and output is used for both aot (production) and jit (development) compilation. In Angular v4 it worked because decorators transformed into metadata were present in output files, but `ngc` from Angular v5 these metadata are missing and are only available in metadata.json and ngsummary.json.

This should be documented as breaking change and should be optional, or configurable.

Before i had
```ts
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
import { Component, Optional, PLATFORM_ID, ChangeDetectorRef, Inject, ChangeDetectionStrategy } from '@angular/core';
import { slideInOutTrigger } from '@ng/animations';
import { NotificationsOptions } from './notifications.options';
import { GlobalNotificationsService } from './notifications.service';
import { Notifications } from './notifications.component';
/**
 * Notifications component for global messages
 */
var GlobalNotifications = (function (_super) {
    __extends(GlobalNotifications, _super);
    //######################### constructor #########################
    function GlobalNotifications(options, service, changeDetector, platformId) {
        var _this = _super.call(this, options, service, changeDetector, platformId) || this;
        _this.cssClass = "notifications global";
        return _this;
    }
    return GlobalNotifications;
}(Notifications));
export { GlobalNotifications };
GlobalNotifications.decorators = [
    { type: Component, args: [{
                selector: "global-notifications",
                styles: ["\n        .notifications.global\n        {\n            position: fixed;\n            right: 15px;\n            top: 20px;\n            z-index: 21312;\n        }\n\n        .notifications.global>notification\n        {\n            display: block;\n            overflow: hidden;\n        }\n    "],
                template: "<div [class]=\"cssClass\">\n        <notification *ngFor=\"let itm of notifications\"\n                      [@slideInOut]\n                      [item]=\"itm\"\n                      [clickToClose]=\"options.clickToClose\"\n                      (closed)=\"removeItem($event)\">\n        </notification>\n    </div>",
                animations: [slideInOutTrigger],
                changeDetection: ChangeDetectionStrategy.OnPush
            },] },
];
/** @nocollapse */
GlobalNotifications.ctorParameters = function () { return [
    { type: NotificationsOptions, decorators: [{ type: Optional },] },
    { type: GlobalNotificationsService, },
    { type: ChangeDetectorRef, },
    { type: Object, decorators: [{ type: Inject, args: [PLATFORM_ID,] },] },
]; };
```

now i have

```ts
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
import { Component, Optional, PLATFORM_ID, ChangeDetectorRef, Inject, ChangeDetectionStrategy } from '@angular/core';
import { slideInOutTrigger } from '@ng/animations';
import { NotificationsOptions } from './notifications.options';
import { GlobalNotificationsService } from './notifications.service';
import { Notifications } from './notifications.component';
/**
 * Notifications component for global messages
 */
var /**
 * Notifications component for global messages
 */
GlobalNotifications = /** @class */ (function (_super) {
    __extends(GlobalNotifications, _super);
    //######################### constructor #########################
    function GlobalNotifications(options, service, changeDetector, platformId) {
        var _this = _super.call(this, options, service, changeDetector, platformId) || this;
        _this.cssClass = "notifications global";
        return _this;
    }
    return GlobalNotifications;
}(Notifications));
/**
 * Notifications component for global messages
 */
export { GlobalNotifications };
```

## Expected behavior

Compilation of `ngc` should be also usable by JIT.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.1.2  
- Platform:  Windows

Others:

</code></pre>

**Comment by sarunint** [comment]
Please ensure that you are using TypeScript 2.4. Currently, Angular does not support TypeScript 2.5 and newer yet.

**Comment by kukjevov** [comment]
Ahhh this could be problem :). I have already upgraded to Typescript 2.6. And what is roadmap for supporting TS 2.6, dont you know? 

Thank you for response and help :)

**Comment by sarunint** [comment]
See https://github.com/angular/angular/issues/19287#issuecomment-342162264 and https://github.com/angular/angular/pull/20175

**Comment by shlomiassaf** [comment]
`ngc` does not strip decorators, not anymore I believe.

To remove the decorators the angular CLI is using this package:
https://github.com/angular/devkit/tree/master/packages/angular_devkit/build_optimizer

It's strange that you got this result from running `ngc`, I don't think the TS version has anything to do with it, it might but I don't think so.

As for JIT vs AOT, there is an option to instruct the AOT compiler to create `ngsummary` files suitable for JIT use.
```
  /**
   * Whether to generate .ngsummary.ts files that allow to use AOTed artifacts
   * in JIT mode. This is off by default.
   */
  enableSummariesForJit?: boolean;
```

I've never tried it, it does add a runtime file but I don't know if it works.

Currently, there's still a mix between v4 options and v5 options. 
Some values are shared, some only on 4 some only on 5.

It will get clear with time

**Comment by shlomiassaf** [comment]
update: using TS 2.5.3 will not emit decorators, silently :/

**Comment by vicb** [comment]
We will update in the coming months - sorry no exact timeline for now.

**Comment by ashishmulaye** [comment]
I have a library which is built with typescript and compiled with Angular 5 compiler. Now, there are few classes/interfaces which are defined inside a namespace.

export namespace A{
    export class C1 {
    }
    export interface I1{
    }
}
When I compile this code with angular 5 ngc compiler, it generates the filename.metadata.json file which contains [null] value.

And when I use this library in my Angular 5 application it gives error for this null .metadata.json file.

TypeError: Cannot read property 'version' of null
Note: This was working with Angular 4.3.3. Also when I use typescript compiler tsc then it does not even generate the .metadata.json file.

Typescript@2.4.2
angular@5.0.3
