### ISSUE TITLE
Angular 5.0 - NGC stopped creating *.ngfactory.ts files for AOT

### ISSUE THREAD

**Issue by scott-m-snyder** [angular/angular#20219]
## I'm submitting a...
[x ] Regression (a behavior that used to work and stopped working in a new release)

## Current behavior

Running ngc -p ./tsconfig-aot.json no longer creates ngfactory.ts files.

This works fine when reverting to 4.4.6 but 5.0 does not create any *.ngfactory.ts files in the aot directory that was previously working.  Oddly it does produce some *.ngfactory.js files in the same directory as the main component ts.

## Expected behavior

Should work like 4.4.6, or provide instructions to make it work

## Minimal reproduction of the problem with instructions

ngc -p ./tsconfig-aot.json

Using any project upgraded to Angullar 5.0 project does not work.  Reverting to 4.4.6. works fine.

## Environment

Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version XX
 
For Tooling issues:
- Node version: 7.6.0
- Platform:  Windows

**Comment by ericmartinezr** [comment]
Can you see if this is the same issue https://github.com/angular/angular/issues/20082 ?

**Comment by scott-m-snyder** [comment]
I guess it is, or similar.  I didn't see a resolvement for this?

**Comment by sarunint** [comment]
I believe this the intended behaviour. You no longer need to compile the `.ngfactory.ts` files via `tsc` anymore, it has been done by `ngc` already.

**Comment by scott-m-snyder** [comment]
I thought ngc was a wrapper for tsc?

**Comment by shlomiassaf** [comment]
the `compiler-cli` still emits **ngfactory** files but they are no longer `ts` but `js`.

If invoking from the command line, the `ts` files are complied using `tsickle`.

Most of the type information required by angular is saved in the **metadata.json** and **summary.json** files that are also emitted.

You can also include `d.ts` for the `ngfactory.js` files which makes them, type-wise, similar to a `ts` file. You can do this by setting `declaration: true` in the **tsconfig.json** file.

For a quick example, create a new project using the angular cli.
Edit the `tsconfig` file so it looks something like this:
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": true,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

in the command line, run:
```bash
./node_modules/.bin/ngc
```

Inspect `dist/out-tsc`

Should look similar to this:
![image](https://user-images.githubusercontent.com/5377501/32452881-75e024f6-c323-11e7-8a25-1d1ae3067cc2.png)

**Comment by shlomiassaf** [comment]
When used via `@ngtools/webpack` there is no output other then the bundled files webpack emits.

This is because `@ngtools/webpack` is managing a virtual file system internally which means no file is saved to disk (TS -> JS), they are all saved in memory and consumed by webpack to be included in the library.

`@ngtools/webpack` can do this because it defines the emitter to be used within the compiler-cli so actually all emits are virtual streams.

**Comment by scott-m-snyder** [comment]
Interest.  So in my main-aot.ts:

This is expecting an ngfactory.ts file, right?

import { AppModuleNgFactory } from "../aot/angularApp/app/app.module.ngfactory";
platformBrowser().bootstrapModuleFactory( AppModuleNgFactory);

**Comment by shlomiassaf** [comment]
It depends on the context...

If we are talking about library creation, there is no AppModule usage, the user of the library will do that.

When bundling an application, yes you need an ngfactory file, and there you have 2 steps
  1. compile with ngc
  2. bundle with webpack

The difference from 4 to 5 is that in 4 the compiler only generated the extra code, i.e. ngfactory, ngsummary, ngstyle etc... but did not compile the developer's code.
In 5, the compiler will output the **entire** code in JS.

So yes, when you bundle you instruct webpack to the ngfactory file of your app root module but from there all everything is JS code :)

In v4 it was a jumping game, part of the code was in the **genDir** and part in the **src** folder.

**Comment by scott-m-snyder** [comment]
Ok, so If I understand what you are saying - instead of:

ngc -p ./tsconfig-aot.json

I just run:

ngc

And then bundle with webpack.  But now I get an error:

ERROR in [at-loader] ./angularApp/main-aot.ts:10:36
    TS6143: Module '../angularApp/app/app.module.ngfactory' was resolved to 'C:/Dropbox/CODE/MyLifeForms/MyLifeFormsNG4/src/angularApp/app/app.module.ngfactory.js', but '--allowJs' is not set.

Maybe I missed something reading the release notes?

**Comment by shlomiassaf** [comment]
It's ok to run `ngc -p ./tsconfig-aot.json` or any other specific file your want to use for configuration.

The answer to your issue is right in the error message.

I wrote:
> The difference from 4 to 5 is that in 4 the compiler only generated the extra code, i.e. ngfactory, ngsummary, ngstyle etc... but did not compile the developer's code.
In 5, the compiler will output the entire code in JS.

And the error you have says just that...
simply allow js in the config and it should compile.

Although, it is not recommended... use `@ngtools/webpack` and remove the ts loader

**Comment by vicb** [comment]
We don't create typescript factories any more

**Comment by SnareChops** [comment]
@vicb Can this be updated in the README.md of the compiler-cli so that other users don't have this same issue? I stumbled around for quite awhile searching for answers since the readme still stated the same procedure. Found this and now I understand it's intentional, but is not documented anywhere.

**Comment by ConnorsFan** [comment]
@shlomiassaf I am not sure what you mean in your previous comment:

> simply allow js in the config and it should compile.
> Although, it is not recommended... use @ngtools/webpack and remove the ts loader
> 

What exactly is not recommended?
