### ISSUE TITLE
Provide better documentation for how to test AOT'ed components

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#20223]
## I'm submitting a...

<pre><code>
[x] Documentation issue or request
</code></pre>

## Current behavior

The current method for testing AOT'ed components is not fully documented.

## Expected behavior

The method for testing AOT'ed components should have a guide for how to accomplish it.

**Comment by jenniferfell** [comment]
for categorizing doc issues
filename=https://angular.io/guide/aot-compiler

**Comment by alxhub** [comment]
Just works with Ivy!
