### ISSUE TITLE
New updateOn behaviour

### ISSUE THREAD

**Issue by VadimPanov** [angular/angular#20226]
## I'm submitting a...

<pre><code>[x] Feature request</code></pre>

## Current behavior

According to documentation 'updateOn' returns update strategy of the AbstractControl (i.e. the event on which the control will update itself). Possible values: 'change' (default) | 'blur' | 'submit'

## What I suggest

I suggest to implement a new update behavior: update with delay after 'change'. The existing 'change' value 'change:XXXX' or new 'changeTimeout:XXXX' value may be used (where XXXX is timeout in milliseconds):
<pre><code>&lt;input type="text" [(ngModel)]="model" [ngModelOptions]="{updateOn: 'change:3000'}"/&gt;
&lt;input type="text" [(ngModel)]="model" [ngModelOptions]="{updateOn: 'changeTimeout:3000'}"/&gt;</code></pre>
Either implement new model option 'timeout' that may be used with any of the 'updateOn' values:
<pre><code>&lt;input type="text" [(ngModel)]="model" [ngModelOptions]="{updateOn: 'change', timeout: 3000}"/&gt;
&lt;input type="text" [(ngModel)]="model" [ngModelOptions]="{updateOn: 'blur', timeout: 3000}"/&gt;</code></pre>

Either allow to combine update strategies (whatever happens first) like this:
<pre><code>&lt;input type="text" [(ngModel)]="model" [ngModelOptions]="{updateOn: 'change:3000, blur'}"/&gt;
&lt;input type="text" [(ngModel)]="model" [ngModelOptions]="{updateOn: ['change:3000', 'blur']}"/&gt;
&lt;input type="text" [(ngModel)]="model" [ngModelOptions]="[{updateOn: 'change', timeout: 3000},{updateOn: 'blur'}]"/&gt;</code></pre>

Update on timeout must be cancelled if 'change' event happens again before timeout fires.

## What is the motivation / use case for changing the behavior?

There are cases when developer has to implement a very complicated component with a lot of inputs that can't be splitted on many components with 'OnPush' change detection strategy. When user is typing something in a input[type='text'] the change detection is firing on every 'change' event and this makes input either very slow or input even hungs for several seconds.

In case of implementing this feature this issue will be gone.

This also makes implementing 'search after pause' functionality very easy.

**Comment by kara** [comment]
We will be implementing something similar with "debounce". See issue here: https://github.com/angular/angular/issues/19705
