### ISSUE TITLE
Angular 5: onSameUrlNavigation

### ISSUE THREAD

**Issue by khoying** [angular/angular#20227]
I am trying to use the new onSameUrlNavigation that was added to Angular 5.  However, the compiler is throwing an error.

My Code:

```
import { NgModule }             from '@angular/core'; 
import { RouterModule, Routes } from '@angular/router';  
import Properties               from './../shared/properties';  

const routes: Routes = [     
           { path: '', redirectTo: '/' + Properties.ROUTES.catalog.home.route, pathMatch: 'prefix' } 
];  

@NgModule({
     imports: [ RouterModule.forRoot(routes, {onSameUrlNavigation: 'reload'}) ],
     exports: [ RouterModule ] 
})  

export class CoreRoutingModule {}
```

Error:

```
ERROR in [at-loader] ./app/core/core-routing.module.ts:13:45
    TS2345: Argument of type '{ onSameUrlNavigation: string; }' is not assignable to parameter of type 'ExtraOptions'.
  Object literal may only specify known properties, and 'onSameUrlNavigation' does not exist in type 'ExtraOptions'.
```

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by mlc-mlapis** [comment]
@khoying ... hmm, I tried to find `onSameUrlNavigation` implementation in Router module in final version 5.0.0 but without success ... it looks that it not there.

Btw, this is commit that implements it Angular repo: 
https://github.com/angular/angular/commit/d3211a2468c671e3e830009ade0454899518d544

**Comment by khoying** [comment]
Sorry.  This was listed as being available in a blog I had read here;  
http://blog.ninja-squad.com/2017/11/02/what-is-new-angular-5/

Guess it is not available yet.

Thanks!

**Comment by Tusharbalar** [comment]
Still not working. Is it working with lazy loaded module also?

```
@NgModule({
  imports: [RouterModule.forRoot(routes, {useHash: true, onSameUrlNavigation: 'reload'})],
  exports: [RouterModule]
})
```

All other routes is lazy in my application. please help.

**Comment by mlc-mlapis** [comment]
@Tusharbalar ... did you read https://github.com/angular/angular/issues/21115?
