### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by gieboyz** [angular/angular#20236]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

im using 
`this.param.filter()`
for filtering an array, before update this is working well. but after im update to 5.0.0
show error like this
![untitled](https://user-images.githubusercontent.com/9793593/32478580-1d1c4922-c3b8-11e7-83de-6e98433dba17.png)

## Expected behavior

can you give me solution for remove this error?? i already add 
`import { filter } from 'rxjs/operators';`
but still not working

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---


`this.param` is `undefined`

**Comment by gieboyz** [comment]
ok thank you for you response.
