### ISSUE TITLE
Bootstrapped component cannot be accessed in the ApplicationRef components collection until the second tick

### ISSUE THREAD

**Issue by ojji** [angular/angular#20238]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The bootstrapped component is added to the ApplicationRef components collection after the change detection mechanism is triggered. Because of that, the components collection is empty in the ApplicationRef until the second tick.

## Expected behavior

The ApplicationRef components collection should contain the bootstrapped component before the change detection mechanism is triggered.

## Minimal reproduction of the problem with instructions

1. Try to access the ApplicationRef components collection in a component's ngOnInit method.
2. Trigger the angular change detection mechanism (e.g. a button click on a component)
3. Check the components collection again as the root component is there now.
See:
http://plnkr.co/edit/5kqPIZiBiWIsHHZQtFgN?p=info

## What is the motivation / use case for changing the behavior?

I'm trying to create a component dynamically in a service for which I need a reference to the root component's hostView property. However the injected ApplicationRef's components collection is empty until there is something that triggers the change detection mechanism in Angular.
This behavior is causing `Cannot read property 'hostView' of undefined` error thrown in my service's initialization logic, where I am trying to read the injected `appRef.components[0].hostView`

## Environment

<pre><code>
Angular version: 5.0.0

</code></pre>

**Comment by alexzuza** [comment]
That's because `apllication.tick` is fired twice on first load. I would use `APP_BOOTSTRAP_LISTENER` to handle it

**Comment by jasonaden** [comment]
Closing based on @alexzuza's response.
