### ISSUE TITLE
Will an automatic update be added to the Angular CLI?

### ISSUE THREAD

**Issue by splincode** [angular/angular#20237]
Very much it would be desirable to be easily updated with use of a cli, in the event that versions Angular leave every 6 months, it is not so convenient independently to be updated.

Angular CLI should analyze the code of my application (if the project was created with the help of Angular CLI), and if there are no critical changes, then independently update the application, or give out warnings and reasons for which you need to manually update.

**Comment by Ploppy3** [comment]
In the meantime, Angular developed this tool to help you update from one version to another: https://angular-update-guide.firebaseapp.com/

**Comment by splincode** [comment]
Yes, I know this resource. But he does not analyze my project. If my project is too large, then automatic analysis would warn me against hasty actions, for example. Either directly in the console would give links to the documentation on how to update such a piece of code.

**Comment by trotyl** [comment]
It looks like a feature request for [Angular CLI](https://github.com/angular/angular-cli), please open it there. (by respecting issue template)

**Comment by splincode** [comment]
https://github.com/angular/angular-cli/issues/8390
