### ISSUE TITLE
ngClass should support mixed type in array `['yeah', {'wow': true}]`

### ISSUE THREAD

**Issue by tom10271** [angular/angular#20232]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`ERROR Error: NgClass can only toggle CSS classes expressed as strings, got [object Object]`
```html
<section
         [ngClass]="[
             'composite-'+'class', {
                'class-in-object-literal': true
             }
         ]">
</section>
```

## Expected behavior

```html
<section class="composite-class class-in-object-literal">This should be rendered</section>
```

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/KSTsdzmB4zvlc2AjYnu2?p=preview

## What is the motivation / use case for changing the behavior?

I know I can do it by separating them and put strings in array into class with template interpolation but I want to do it in a more simple way.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version 61.0.3163.100
</code></pre>

**Comment by pkozlowski-opensource** [comment]
To be honest I don't see added value of:
* additional syntax;
* performance hit (we would have diff each element in the array and it can get messy)

given that the example you are bringing up can be written in so many other, IMO simpler ways:
* `<section class="class-in-object-literal" [ngClass]="['composite-'+'class']">` (preferred)
* `<section [ngClass]="['class-in-object-literal', 'composite-'+'class']">`

I _suspect_ that your real use-case might be a bit more complex, ex.:
`<section [ngClass]="[exp1 ? 'class-in-object-literal' : null, 'composite-'+ exp2]">` and I agree that in cases like this the syntax you are proposing would be a bit nice from a template author point of view. Still, I don't think it justifies additional complexity and performance hit. If you really need to do complex processing on classes one suggestion would be to move this logic to a component.

I'm going to close it for now as the proposal _might_ be nicer in certain complex use-cases but it would needlessly complexity handling and make it slower for majority of cases.

**Comment by petermikitsh** [comment]
Thanks for the detailed reply, @pkozlowski-opensource. As someone new to Angular, I didn't know the preferred method was to use `class` and `[ngClass]` together. Coming from React (and in particular, as a user of the [classnames](https://github.com/JedWatson/classnames) module), the proposed syntax was how I assumed I should conditionally apply classnames, e.g., by using a mixed type array.
