### ISSUE TITLE
Dialog HTML template does not wait for init to complete

### ISSUE THREAD

**Issue by raydawg2000** [angular/angular#20231]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I load my dialog component I make an HTTP request to grab data from the server.  I am using a promise but before my promise completes the HTML template loads and I get JS errors about my template vars not being defined.  After the promise completes the data is successfully loaded into the template.  Due to all the JS errors though, dialog functionality ceases to work, I cannot close or use any of the mat buttons I defined.

## Expected behavior
The template should wait for my Init method to complete before evaluating the template and not throw JS errors preventing me from closing the dialog.

## Minimal reproduction of the problem with instructions

> export class EventInfoComponent implements OnInit {
>   event: Event;
> 
>   constructor(
>     @Inject(MAT_DIALOG_DATA) public data: any,
>     public dialogRef: MatDialogRef<EventInfoComponent>,
>     private http: Http
>   ) { }
> 
>   ngOnInit() {
>     this.http.get(`api/user/events/info/${this.data.eventID}`)
>       .toPromise()
>       .then(response => {
>         this.event = response.json().event as Event
>       });
>   }
> }

`<label>Event Name:</label> {{event.name}}`

ERROR TypeError: Cannot read property 'name' of undefined
    at Object.eval [as updateRenderer] (EventInfoComponent.html:10)
    at Object.debugUpdateRenderer [as updateRenderer] (core.js:14376)
    at checkAndUpdateView (core.js:13512)
    at callViewAction (core.js:13857)
    at execComponentViewsAction (core.js:13789)
    at checkAndUpdateView (core.js:13513)
    at callViewAction (core.js:13857)
    at execEmbeddedViewsAction (core.js:13815)
    at checkAndUpdateView (core.js:13508)
    at callViewAction (core.js:13857)

## Environment

<pre><code>
Angular version: 5.0

Browser:
All
 
</code></pre>

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

ngOnInit cannot and will not "wait" for async operations to complete.
You should hide your view with an ngIf and display a loader instead
or
use a resolver to resolve the data before entering that route

**Comment by pkozlowski-opensource** [comment]
Thnx @Toxicable
