### ISSUE TITLE
StaticInjectorError

### ISSUE THREAD

**Issue by vlimb** [angular/angular#20242]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

```
ERROR Error: Uncaught (in promise): Error: StaticInjectorError[undefined]: 
  StaticInjectorError[undefined]: 
    NullInjectorError: No provider for undefined!
```

## Expected behavior
No error

## Minimal reproduction of the problem with instructions
Complex app, unable to create a small reproducible plunker

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x ] Chrome (desktop) version XX

For Tooling issues:
- Node version: 8.9.0
- Platform: Mac

**Comment by lazarljubenovic** [comment]
How can this description help anyone tackle down the problem or even help you?

**Comment by vlimb** [comment]
@lazarljubenovic By reading the error message I got

**Comment by vlimb** [comment]
Fixed
