### ISSUE TITLE
Angular 5 Cli AOT Build Issue

### ISSUE THREAD

**Issue by arsyed04** [angular/angular#20240]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When doing AOT build getting following 'runtime' issue:
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'subscribe' of undefined
TypeError: Cannot read property 'subscribe' of undefined

Non AOT build works fine

## Environment

<pre><code>
Angular version: 5.0.0
Angular Cli: 1.5.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.0.0
- Platform:  

Others:

</code></pre>
Using Http and HttpModule, not HttpClient and HttpClientModule

**Comment by Toxicable** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by arsyed04** [comment]
Thanks @Toxicable I am following this issue here: https://github.com/swimlane/ngx-datatable/issues/1104
This seems to be a library issue instead of Angular. You can close this item.

**Comment by Toxicable** [comment]
@arsyed04 I cannot close this issue, you can though
