### ISSUE TITLE
Exception while using template-strings in a decorator

### ISSUE THREAD

**Issue by thomassittig** [angular/angular#20255]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Using template-strings to define a _templateUrl_ and _styleUrls_.

A valid example would be, to have an variable which contains a value that can be consumed as  part of the templateUrl and the styleUrls together.

By doing this, while running `ng serve` an exception occure that the requested resources can not be found. 
In the exception can also the RAW template-strings be found, and not the finally constructed.

## Expected behavior
All is fine and the constructed string-values are accepted and the resources can be found

## Minimal reproduction of the problem with instructions

* create a blank new out of the box angular 5 project
* go to the `app/app.component.ts`
* create a variable called `name` with the value `app`
* change the styleUrls to `[`./${name}.component.css`]`
* re-run the app with `ng serve`

Full Example:

```
import { Component } from '@angular/core';

const name = 'app';

@Component({
  selector: 'app-root',
  templateUrl: `./${name}.component.html`,
  styleUrls: [`./${name}.component.css`]
})
export class AppComponent {
  title = 'app';
}
```

## What is the motivation / use case for changing the behavior?

I see this as a major blocker in what should be a very basic behaviour.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.0  
- Platform:  Mac

Others:

</code></pre>

**Comment by vicb** [comment]
It should work, please add a reporo

**Comment by thomassittig** [comment]
Yes, it should.
An example repo is here: https://github.com/thomassittig/angular5-string-interpolation-error
And a similar running/failing app here: https://stackblitz.com/edit/angular-rs5loy

My local running `ng --version` says:

```
Angular CLI: 1.5.0
Node: 6.11.0
OS: darwin x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.6.1
webpack: 3.8.1
```

**Comment by jasonaden** [comment]
@thomassittig I looked at your repro and this appears to be a CLI bug as it's Webpack that's failing here. Can you please create an issue for it at https://github.com/angular/angular-cli/issues?
