### ISSUE TITLE
What is better StaticInjector than ReflectiveInjector?

### ISSUE THREAD

**Issue by splincode** [angular/angular#20252]
Angular 4

```js
platformBrowserDynamic([
  MyCustomProviderA,
  MyCustomProviderB // depends on MyCustomProviderA
]).bootstrapModule(AppModule);
```

Angular 5

```js
platformBrowserDynamic([
  { provide: MyCustomProviderA, deps: [] },
  { provide: MyCustomProviderB, deps: [MyCustomProviderA] }
]).bootstrapModule(AppModule);
```

In appearance, the same metadata, only separated from classes.
You need to write more code, specify the dependencies manually.
How to ensure the type of security, because the classes of arguments are passed separately to deps.

Or bootstrap-code now the compiler itself?

If it was only a matter of speed, then you could simply abandon the brake Reflect.defineMetadata and generate more optimal metadata.
Why make dependencies only explicit?

**Comment by Toxicable** [comment]
Only certain providers you must declare the deps explicitly, all normal ones that devs deal with out a day to day are unchanged.
One clear advantage is that we no longer rely on Reflect, therefore you can remove the polyfill(unless you're using it yourself).

**Comment by mlc-mlapis** [comment]
... the main reason is speed and elimination of the polyfill ... for more details you can read about here https://blog.angularindepth.com/angular-introduces-staticinjector-should-you-care-4e059eca030c
