### ISSUE TITLE
ng-class equivalent behaviour

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#2025]
[If this already exists, a pointer to the docs would be awesome.]

In AngularDart, I have an element:
`<div class="a" ng-class="someExpr"></div>` where `someExpr` evaluates to "b c".

The rendered output is `<div class="a b c"></div>`.

How do I use this pattern in Angular 2?

**Comment by pkozlowski-opensource** [comment]
This syntax is not currently supported with the existing `class` directive (it understand only object literals syntax right now). Last time I've discussed string-based with @IgorMinar it sounded like we might not want to support it in ng2 as it makes it easy to "hard-code" CSS classes in JS/Dart code.

We should probably re-discuss this and have definitive stance on this one.

**Comment by jbdeboer** [comment]
The current best option, AFAICT, is to re-write the above example as:
```<div [class-name]="'a ' + someExpr"></div>```

which is super-fugly.

**Comment by SekibOmazic** [comment]
@jbdeboer I had a similar problem and used following syntax:
```HTML
<div class="a" [class.b]="bExpr" [class.c]="cExpr"></div>
```
There is also the `CSSSelector` which works with object literals, but I found it inconvenient.

**Comment by jbdeboer** [comment]
@SekibOmazic Yes; but that approach would require us to rewrite our controller logic; which isn't something we are eager to do!

Thinking on the "best option" that I listed: it does not work well either, since in Angular1, we don't know if ```someExpr``` is a string, list or map without inspecting the controller. That transformation only works for strings.

**Comment by naomiblack** [comment]
Assigning to @mhevery and (also @IgorMinar) for discussion. Is this something that we can support in angular2, or else, what's our best recommendation for handling this pattern?

**Comment by yjbanov** [comment]
I think it's safe to support `<div class="a" [class]="expr"></div>` where `expr` evaluates to `List` or `Map` and `[class]` simply adds more classes to the already existing literal list.

**Comment by mhevery** [comment]
I agree with @yjbanov, I think we should support it.

**Comment by mhevery** [comment]
Also fix for ng-style

**Comment by naomiblack** [comment]
Assigning to @vsavkin to clarify what needs to be implemented.

**Comment by pkozlowski-opensource** [comment]
Had a productive chat with @vsavkin - I'm unblocked.
