### ISSUE TITLE
HttpClientTestingController ignores reportProgress: true

### ISSUE THREAD

**Issue by seedy** [angular/angular#20257]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

While **unit testing an interceptor**, I noticed the following behaviour :

- I am using **HttpClient** and **HttpClientTestingController** 
(respectively declared http and httpMock thereafter)

- I am mocking a http 'GET' request with HttpClient
`
http.get(url, {
  reportProgress: true,
  observe: 'events'
})
`
- I then build my mock expectation and response
`
cont req = httpMock.expectOne(...)
req.flush({somedata: ''});
`

- Subscribing to that request, I get 2 emitted objects : 
1) `{ type: HttpEventType.Sent }`
2) `jasmine.objectContaining({type: HttpEventType.Response})`

## Expected behavior

TestRequest#flush should follow the standard behaviour when reportProgress is true.

- Subscribing to that request, I should get 4 events in the following order : 
1) `{ type: HttpEventType.Sent }`
2) `{ type: HttpEventType.ResponseHeader }`
3) `{ type: HttpEventType.UploadProgress }`
4) `{ type: HttpEventType.Response }`

## What is the motivation / use case for changing the behavior?

This way unit testing interceptors or any progress event dependent feature would be much easier because the mock testing tool would behave just as the actual HttpClient service. 
Which is currently not the case.

By the way there is little to no documentation on the whole progress event handling behaviours implemented in Angular.

## Environment

<pre><code>
Angular version: 4.4.3

Browser:
- [X] Chrome (desktop) version 61.0.3163.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by nipuna777** [comment]
Is there a known workaround for this issue? 
If there is, should it be documented? I'll be happy to contribute in anyway possible.

**Comment by petebacondarwin** [comment]
The `TestRequest` class that is returned from `httpMock.expectOne()` contains a method called `event()` which can be used to deliver an arbitrary event (such as progress) to the `HttpClient` request handler.

Closing as this feature request did not receive enough votes and there appears to be a solution anyway.
