### ISSUE TITLE
Postinstall script causes error

### ISSUE THREAD

**Issue by am-a** [angular/angular#20254]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When installing the angular sources using the repository url directly, the install will fail because the `postInstall` script will fail to find `webdriver-manager`. Running with `--production=false` seems to work...

## Expected behavior

The postInstall script will only execute in non-production environments.

## Minimal reproduction of the problem with instructions

`yarn add 

## What is the motivation / use case for changing the behavior?

We would like to be able to use angular sources as a node_modules package

## Environment

<pre><code>
Angular version: 5.0.0

For Tooling issues:
- Node version: 6.9.5  
- Platform:  All 

Others:

</code></pre>

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
