### ISSUE TITLE
Error on using command "ng generate component"

### ISSUE THREAD

**Issue by CadnunsDimir** [angular/angular#20250]
When I use the command:
`ng generate component componentName`

the ViewEncapsulation component in the ts component file aren't imported properly. This issue block the angular Cli Build.

I have import this Class/Component manually, and work well.

I think that is only necessary correct the template generation putting this class in the import declaration line on top of the component ts file.

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular-cli/issues/8386 (where angular-cli's repo lives)

**Comment by pkozlowski-opensource** [comment]
Thnx @ericmartinezr !
