### ISSUE TITLE
registerOnValidatorChange is not called for ngModelGroup

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#20268]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Method `registerOnValidatorChange` is not called by form setup for ngModelGroup see setupControl in Forms.

## Expected behavior
Method should be called to inform the validator about changes of the input properties.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/eqo68nSQfk9nea70Ppur?p=preview

The log statement is not printed, because the method is never called.

## What is the motivation / use case for changing the behavior?
Group validators should be able to get informed about changes of input properties to trigger another validation cycle.

## Environment

<pre><code>
Angular version: 4.4.6 / 5.0.0

 
For Tooling issues:
- Node version: 6.5
- Platform:  Windows
</code></pre>

@ajafff

**Comment by dylhunn** [comment]
@CSchulz thank you for your bug report. This should be fixed in PR #41971.

**Comment by dylhunn** [comment]
Merged, expected to be released in v12.0.1.
