### ISSUE TITLE
title and meta services not working correctly

### ISSUE THREAD

**Issue by mohamedsherif91** [angular/angular#20264]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

i need service to can set title and meta tags, i'm using Title,Meta services but it's working only in browser but when i share it on facebook no title or meta tags appeard
`
import { Title } from '@angular/platform-browser';
import { Meta } from '@angular/platform-browser';
`

## Expected behavior

find service solving this issue instead of using angular universal 

## Environment
Angular 4
<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
Angular is where  those services run
Angular's only runs in the browser.
To run Angular on the server you need to use Universal, with universal you can either do pre-rendering or dynamic rendering with Express for example.
Some alternatives include prerender.io but that does exactly the same thing as pre-rendering with Universal

**Comment by netlander** [comment]
Even with Universal these tags do not update properly. The title for example updates in the browser tab but not in the source and not in a tool like browseo.net. Same with meta tags...
