### ISSUE TITLE
SVG not rendering with tag :inkscape:perspective

### ISSUE THREAD

**Issue by dgroh** [angular/angular#20261]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I'm trying to render a SVG in a HTML component, but I get the following error:

> ':inkscape:perspective' is not a known element:'

I created a stackblitz demonstrating this behavior: https://stackblitz.com/edit/angular-xc82la

It works in a plain HTML file and it also works in an AngularJs application tho.

## Expected behavior
I expect the SVG to be rendered.

## Environment

<pre><code>
Angular version: 5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vicb** [comment]
is `inkscape:perspective` a SVG element ?

**Comment by dgroh** [comment]
you ask for it and close the issue? so I assume **you don't know the answer**. 

yes, it can be part of a SVG. Check the plunker.
