### ISSUE TITLE
No router events for location.back() when using RouterTestingModule

### ISSUE THREAD

**Issue by rgal75** [angular/angular#20269]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I set up router based testing using ```RouterTestingModule```. I have a reference 
* to the Router via ```router = TestBed.get(Router)```
* to the browser location via ```location = TestBed.get(Location)```
If I call ```location.back()``` in a test then the router state (```router.routerState.snapshot.url```) is not updated and I receive no router events through ```router.events```.
Example test:
```
it('location.back()', fakeAsync(() => {
    router.navigate(['']);
    tick();
    expect(router.routerState.snapshot.url).toBe('/home');

    router.navigate(['/search']);
    tick();
    expect(router.routerState.snapshot.url).toBe('/search');

    console.log('BACK')
    location.back()
    tick();
    expect(location.path()).toBe('/home');
    expect(router.routerState.snapshot.url).toBe('/home');
  })); 
```
The last expectation fails.

## Expected behavior
```location.back()``` should cause router events (NavigationStart, e.t.c.) to fire and the last expectation above should succeed.

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/4qY4uM1TSuxkZCSY3GPu

## What is the motivation / use case for changing the behavior?
I would like to test forward and backward navigation using Router

## Environment

<pre><code>
Angular version: 4.4.6
</code></pre>

**Comment by Ruud-cb** [comment]
Uhh a 2 year old issue not addressed? Workaround known?

**Comment by atscott** [comment]
The router tests rely quite heavily on this working so I don't believe this is true anymore. Closing. Please do submit a new issue with reproduction using the latest version of Angular if an issue still exists.
