### ISSUE TITLE
Angular 4 Router doesn't handle two outlet changes at the same time

### ISSUE THREAD

**Issue by abhimanyu1717** [angular/angular#20270]
## I'm submitting a...
Issue related to angular 4 route.

## Current behavior
I have created configuration for routing.

const appRoutes: Routes = [
  { path: 'unAssigned',  component: CaoUnassigned, outlet:'view1' },
 { path: 'assigned',  component: CaoUnassigned, outlet:'view1' },
  { path: 'myPackage',  component: CaoPackage, outlet:'view2' },
  { path: 'pending',  component: CaoPending, outlet:'view2' }
];

When i am trying to route form component
      constructor(public router:Router) {
         router.navigate([{ outlets: { view1: ['unAssigned'] } }]);
      router.navigate([{ outlets: { view2: ['myPackage'] } }]);
 }

it's only showing page in view2. not in view1

## Expected behavior
Both unAssigned and myPackage view should rendered in view1 and view2 at same time.

**Comment by ericmartinezr** [comment]
You're doing two separate navigations there... https://stackblitz.com/edit/angular-ghqezt?file=app%2Fapp.component.ts
