### ISSUE TITLE
API docs are missing for HttpParamsOptions

### ISSUE THREAD

**Issue by dinvlad** [angular/angular#20276]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`HttpParams` is documented on Angular.io, however its constructor takes `HttpParamsOptions` that doesn't link to a doc.

## Expected behavior

We could infer the shape of `HttpParamsOptions` from the source code, but it would be nice to describe, link to and search for it on the API portal.

## Environment

Angular 5.0.0

Others:

https://angular.io/api/common/http/

**Comment by zippos** [comment]
I was looking for this yesterday :)

**Comment by eladcandroid** [comment]
Any news?

**Comment by gkalpak** [comment]
@alxhub, why label it as `comp: http` instead of `comp: common/http`?
See #20332.

**Comment by zippos** [comment]
Just note that HttpParams doesn't add up to the previous params just like HttpSearchParams used to do. 

`
let body = new HttpParams();
body.set('some_var', 'value');
body.set('another_var', 'value');

console.log(body.toString()); // will return null

body = body.set('some_var', 'value');
body = body.set('another_var', 'value');

console.log(body.toString()); //will return the params
`

**Comment by mhevery** [comment]
fixed by #20332

**Comment by gkalpak** [comment]
Fix reverted.

**Comment by shlomiassaf** [comment]
The topic is not entirely correct, it's not exported by the docs and also not exported by the public API, which is the real issue.

A public class with public constructor accepts a private interface, that's the problem.

The fix is super easy here...

**Comment by jenniferfell** [comment]
@alxhub Hi. On the surface, this is a "docs incomplete" issue, but then...see comment from 9 days ago. Are you the right person to ask...is there also a code/API issue which we need to resolve before we can determine the correct docs approach? Thanks for your input.

**Comment by gkalpak** [comment]
`HttpParamsOptions` should not be referenced by public API. 
#23015 is supposed to fix it. The fix was reverted before due to some google3 failures (see #20332 for more info).

**Comment by jenniferfell** [comment]
@gkalpak We'll hold on doc changes and just watch that PR. Thanks.

**Comment by jenniferfell** [comment]
@jbogarthyde To keep an eye on. :-)

**Comment by MattiJarvinen-BA** [comment]
How's this progressing?

**Comment by pickfire** [comment]
> HttpParamsOptions should not be referenced by public API.

@gkalpak I believe that `HttpParamsOptions` should be referenced by public API for others to be able to override the encoder as it does not encode some characters such as `+` and `=`, See https://github.com/angular/angular/issues/26979 and https://github.com/angular/angular/issues/18261.

**Comment by trotyl** [comment]
@pickfire It means `HttpParamsOptions` interface [is going to be inlined](https://github.com/angular/angular/pull/23015), so that `HttpParamsOptions` name doesn't exist anymore, which becoming part of the constructor type directly.

**Comment by pickfire** [comment]
@trotyl Nice, I see what that means now. It definitely will be better in this case.

**Comment by jeserkin** [comment]
How are things progressing on this issue?

I noticed it was created in 2017 and till now it still produces same result. By result I mean, that https://angular.io/api/common/http/HttpParams references HttpParamsOptions type, but this type has no reference and therefore doesn't tell developer/user, what it provides/consists of.

**Comment by rooby** [comment]
This documentation is made more important by the fact that the default encoder doesn't work and you need to know how to override with a custom one. See #11058
