### ISSUE TITLE
Dynamic component example in chrome

### ISSUE THREAD

**Issue by peterhorvathverba** [angular/angular#20275]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The example and live demo does not work about the dynamic component on the following page in chrome:
https://angular.io/guide/dynamic-component-loader

## Expected behavior

Working demo and plunkr example

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ X ] Chrome (desktop) version  62.0.3202.75 
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/18138, https://github.com/angular/angular/issues/17158, https://github.com/angular/angular/issues/19322
