### ISSUE TITLE
Uncaught TypeError: Cannot set property 'display' of undefined while using HTML <object> tag

### ISSUE THREAD

**Issue by Sibiraj-S** [angular/angular#20272]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behaviour

```
Uncaught TypeError: Cannot set property 'display' of undefined
```
Getting this error while using HTML's `<object>` tag

## Minimal reproduction of the problem with instructions

Demo here: http://plnkr.co/edit/lXm5VVssMt7GJOKcLY3c?p=preview

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x ] Chrome (desktop) version  62.0.3202.89
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9  
- Platform: Windows 10 x-64

**Comment by mlc-mlapis** [comment]
I can't see the code you are talking about in the demo. Also not the error.

**Comment by Sibiraj-S** [comment]
I didn't use any code. Just refer the template. Its HTML

```
@Component({
  selector: 'my-app',
  template: `
   <object data="./loader.svg" type="image/svg+xml">	</object> // this
  `,
})
```

Using `<object>` tag creates the error.

![error](https://user-images.githubusercontent.com/20282546/32552648-999b5c24-c4ba-11e7-94bc-4077572d4bf4.png)

**Comment by ericmartinezr** [comment]
Working perfectly fine for me in both FF and Chrome.

**Comment by ericmartinezr** [comment]
Yes, that error is plnkr itself. It has nothing to do with angular. You're not seeing anything related to angular.

**Comment by Sibiraj-S** [comment]
But the other error. `Cannot set property 'display' of undefined` I get while using in my projects too.

**Comment by mlc-mlapis** [comment]
@Sibiraj-S ... still can't see any problem:

![image](https://user-images.githubusercontent.com/5693835/32555368-d0e897aa-c49c-11e7-9480-5c9c078e589f.png)

**Comment by Sibiraj-S** [comment]
My bad. That was because of an extension. Sorry for the trouble. I realized after seeing the screenshot @mlc-mlapis
