### ISSUE TITLE
Events with same target are not detached if one is attached when "outside angular"

### ISSUE THREAD

**Issue by rkonstantinov** [angular/angular#20274]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If two DOM event handlers are attached to the same element via the renderer, where one is attached outside Angular and the other "inside" Angular, the later cannot be detached. 

This seems to be due to the fact that the decision about how the event should be detached is based on an expando [attached to the targeted DOM element](https://github.com/angular/angular/blob/200d92d0301ef4c584cb7d69366bde3395157e96/packages/platform-browser/src/dom/events/dom_events.ts#L191). 
Maybe this information can be passed directly via the closure or attached to the callback instead.

## Expected behavior
I would expect to be able to detach events.

## Minimal reproduction of the problem with instructions
The behavior is easily re-producible in the following plunker
http://plnkr.co/edit/RXhEXHwsXWr197WRctIw?p=preview

Just click on the document, you will noticed that two alerts are shown, instead of just one, as one of the click handlers is detached.

## Environment
Angular version: 5.0.0

**Comment by JiaLiPassion** [comment]
I have made a PR to fix this one, https://github.com/angular/angular/pull/20538

**Comment by IgorMinar** [comment]
This has been fixed by #20538

Confirmation: http://plnkr.co/edit/RXhEXHwsXWr197WRctIw?p=preview
