### ISSUE TITLE
Angular Animations Speed / Playback Rate

### ISSUE THREAD

**Issue by lornz** [angular/angular#20279]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Right now it's not possible to adjust the overall speed of all Angular Animations. (e.g. for debugging animations)

## Expected behavior
It would be great to be able to specify a global slow motion factor to adjust the playback speed of all animations.

## What is the motivation / use case for changing the behavior?
To look at animations in slow motion helps debugging and optimizing animations within the design process.

Angular version: 5

**Comment by Dok11** [comment]
Maybe it can help — use chrome dev tools animations for slowmo:
![image](https://user-images.githubusercontent.com/2697890/32652806-9f77e164-c616-11e7-976a-da7799cfcd5e.png)

This works, if you dont stop animations by setTimeout, or something else

**Comment by matsko** [comment]
Yes this is a great idea.

What I'm thinking of doing is something like this:

```html
<div [@.options]="{duration:'200%'}">
  ...
  <!-- this will now take double as long -->
  <div [@foo]="exp"></div>
  ...
</div>
```

**Comment by lornz** [comment]
@Dok11 That is not a solution for us, as we need to deliver this feature to our client. And we dont want our clients to access the chrome dev tools for that. Thanks for pointing it out though.

@matsko Thats exactly how I would expect it :)

**Comment by alxhub** [comment]
Closing as insufficient votes/interest, plus this is already served by DevTools support for animation slowing.
