### ISSUE TITLE
HttpReponse json value "false" is deserialized as null

### ISSUE THREAD

**Issue by Necroskillz** [angular/angular#20278]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Current implementation of `HttpResponse` coalesces the body like so: `this.body = init.body || null;`. This means when response body is `"false"` requested as JSON, the resulting body is `null` instead of `false`.

## Expected behavior
In case of `"false"` response content, `response.body` should be `false`.

## Minimal reproduction of the problem with instructions

```
let res = new HttpReponse(...);
res = res.clone({ body: false });
console.log(res.body); // -> null
```

## Environment

<pre><code>
Angular version: 5.0.0
</code></pre>

**Comment by trotyl** [comment]
Duplicate of #19825.

**Comment by Necroskillz** [comment]
Didn't see that one, closing this then.
