### ISSUE TITLE
Custom Validators example at form-validation docs is not working with strictNullChecks enabled

### ISSUE THREAD

**Issue by boban984** [angular/angular#20282]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The example for Custom Validators at "https://angular.io/guide/form-validation#custom-validators" is not working corectly with strict null checks.

Throws : 
TS2322: Type '{ 'forbiddenName': { value: any; }; } | null' is not assignable to type '{ [key: string]: any; }'.
Type 'null' is not assignable to type '{ [key: string]: any; }'.

## Expected behavior
Custom validation example should work with strict null checks

<pre><code>
Angular version: 4.4.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 7.7.4
- Platform:  Windows 10

Others:

</code></pre>

**Comment by yoyoyoshi** [comment]
I think
selector: '[appForbiddenName]' 
should be 
selector: '[forbiddenName]'
