### ISSUE TITLE
land basic http lib

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2028]
Scope: Should perform basic request/response, returning `EventEmitter` object, using XHR, with mock backend.

Example:

```js
http('https://google.com').subscribe((res) => console.log(res));
```

**Comment by ewinslow** [comment]
Why event emitter instead of promise? Any reason not to just use/polyfill the `window.fetch` API?

**Comment by gdi2290** [comment]
@ewinslow you can't cancel a promise

**Comment by ewinslow** [comment]
OK, that might be a good requirement/goal to mention explicitly...

Is the idea to abort the in-flight request, or simply unsubscribe a listener? Or both?

If only the former, then you can always return a custom CancelablePromise that extends Promise.

**Comment by jeffbcross** [comment]
Hey @ewinslow, good question. Sorry this issue is so vague, I opened it in a hurry so it could be tracked with the current milestone. I have more detail in [my prototype project](https://github.com/jeffbcross/http-design), though the readme is a little outdated. [This presentation](https://www.youtube.com/watch?v=Bm3eDgZZMFs) we gave a couple of weeks ago also includes a lot of examples of the new http API.

But regarding your question about fetch: yes! Please use fetch if that's what you like. There are other existing polyfills already. The native implementation and polyfills should just work with Angular out of the box; fetch in particular was recently patched with https://github.com/angular/zone.js/pull/119.

The short story of this observable-based http implementation ("EventEmitter" is the name of the internal Observable implementation for now) is to provide a more robust API for important HTTP operations like polling, retrying, cancellation, and observing upload/download progress. The library will also compose nicely with other parts of Angular that are observable-based, like component events. A lot of the constructs are based closely on the [fetch spec](https://fetch.spec.whatwg.org), such as the Request, Response, and Headers interfaces, with minor variation.

**Comment by gdi2290** [comment]
@ewinslow you can also do `http('https://google.com').toPromise().then(successFn)`

**Comment by ewinslow** [comment]
Thanks for the background! Very helpful.
