### ISSUE TITLE
Angular2 An unhandled win32 exception ocurred in iexplorer.exe [xxxxx]

### ISSUE THREAD

**Issue by MonicaMarques** [angular/angular#20284]
## Current behavior
I have an angular2 application that runs perfectly on google chrome, but for some reason it crashes on internet explorer 11.

When opening the console with F12 key, it opens the console, but immediately after it opens a window with the message "Internet Explorer has stopped working" and provides the option to close the window or to debug.

If I click debug it shows the message "An unhandled win32 exception ocurred in iexplorer.exe [xxxxx]".

I also tried to do the same without the IE add ons, but the errors continues.

## Expected behavior
I expect to be able to inspect my application code on internet explorer.

## What is the motivation / use case for changing the behavior?
Facilitate development of the angular2 application on internet explorer. E.g: Change CSS to look good on IE.

Browser:
-  Internet Explorer 11

For Tooling issues:
- Node version: 6.11.3
- npm :  3.10.10

**Comment by mlc-mlapis** [comment]
@MonicaMarques ... and does your app have the polyfill `<script src="https://unpkg.com/core-js@2.4.1/client/shim.min.js"></script>`? Or does it works any simple app from https://stackblitz.com/fork/angular-gitter with your IE?

**Comment by vicb** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists please open a new issue following [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue).
