### ISSUE TITLE
DatePipe: Missing locale data for the locale "de"

### ISSUE THREAD

**Issue by fortunella** [angular/angular#20286]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I use DatePipe in my component it throws an error:
Missing locale data for the locale "de"

new DatePipe('de').transform(...);  --> error
new DatePipe('en-DE').transform(...);  --> no error

This code worked fine in Angular 4.4.5.
The locale files for both are available in node_modules/@angular/common/locales

## Environment

<pre><code>
Angular version: 5.0.1

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v7.10.0  
- Platform:  Linux

</code></pre>

**Comment by vicb** [comment]
The solution is simple... read [the docs](https://angular.io/guide/i18n#i18n-pipes) :)

**Comment by alinkov** [comment]
# From docs

Angular pipes can help you with internationalization: the **DatePipe, CurrencyPipe, DecimalPipe and PercentPipe** use locale data to format data based on the **LOCALE_ID**.

By default, Angular only contains locale data for en-US. If you set the value of LOCALE_ID to another locale, you must import locale data for that new locale. The CLI imports the locale data for you when you use the parameter --locale with ng serve and ng build.

If you want to import locale data for other languages, you can do it manually:

```
src/app/app.module.ts
content_copy
import { registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/locales/fr';

registerLocaleData(localeFr);
```
The files in @angular/common/locales contain most of the locale data that you need, but some advanced formatting options might only be available in the extra dataset that you can import from @angular/common/locales/extra. An error message informs you when this is the case.

```
src/app/app.module.ts
content_copy
import { registerLocaleData } from '@angular/common';
import localeFrCa from '@angular/common/locales/fr-CA';
import localeFrCaExtra from '@angular/common/locales/extra/fr-CA';

registerLocaleData(localeFrCa, localeFrCaExtra);
```

**Comment by MiroKov** [comment]
This works for me when using ng-serve.
However, 
using `ng build --prod  --base-href /Plock/`
i get the following error:

> ERROR ErrorcolumnNumber: 538408fileName: "http://localhost/Plock/main.88db5360abacef277328.bundle.js"lineNumber: 1message: "Missing locale data for the locale \"de\"."stack: "O@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:538408\ni@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:536984\nA@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:544322\nhgH8/Xe</e.prototype.transform/<@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:577403\nhgH8/Xe</e.prototype.transform@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:577383\npTxz/</s</e.prototype.transform@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:593010\nVt/</<@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:119066\nVt/<@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:118142\nVt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:116340\nrn@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:125038\nr/<@http://localhost/Plock/1.a97e417274c50f3bc364.chunk.js:1:261426\nupdateRenderer@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:181205\nDt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:116114\nqt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:122591\nBt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:121991\nDt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:116137\nqt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:122591\nzt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:122254\nDt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:116016\nqt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:122591\nzt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:122254\nDt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:116016\nqt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:122591\nBt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:121991\nDt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:116137\nqt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:122591\nzt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:122254\nDt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:116016\nqt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:122591\nBt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:121991\nDt@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:116137\nLMZF/</Bo</e.prototype.detectChanges@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:169275\nLMZF/</zr</e.prototype.tick/<@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:145306\nLMZF/</zr</e.prototype.tick@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:145267\nnext/<@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:143644\neFQL/</</</l</t.prototype.invoke@http://localhost/Plock/polyfills.47cae882ab52bb503d6a.bundle.js:1:53252\nonInvoke@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:137286\neFQL/</</</l</t.prototype.invoke@http://localhost/Plock/polyfills.47cae882ab52bb503d6a.bundle.js:1:53179\neFQL/</</</c</r.prototype.run@http://localhost/Plock/polyfills.47cae882ab52bb503d6a.bundle.js:1:48406\nLMZF/</Nr</e.prototype.run@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:137998\nnext@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:143621\nLMZF/</Rr</t.prototype.subscribe/o<@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:135934\nE9/g/c</t.prototype.__tryOrUnsub@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:80661\nE9/g/c</t.prototype.next@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:79936\nE9/g/u</t.prototype._next@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:79005\nE9/g/u</t.prototype.next@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:78688\nTO51/f</t.prototype.next@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:361131\nLMZF/</Rr</t.prototype.emit@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:135693\nO@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:90744\nx@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:91018\nonInvokeTask@http://localhost/Plock/main.88db5360abacef277328.bundle.js:1:137230\neFQL/</</</l</t.prototype.invokeTask@http://localhost/Plock/polyfills.47cae882ab52bb503d6a.bundle.js:1:53840\neFQL/</</</c</r.prototype.runTask@http://localhost/Plock/polyfills.47cae882ab52bb503d6a.bundle.js:1:49097\neFQL/</</</p</e.invokeTask@http://localhost/Plock/polyfills.47cae882ab52bb503d6a.bundle.js:1:55041\nv@http://localhost/Plock/polyfills.47cae882ab52bb503d6a.bundle.js:1:43429\nd@http://localhost/Plock/polyfills.47cae882ab52bb503d6a.bundle.js:1:43664\n"__proto__: Object { … } main.88db5360abacef277328.bundle.js:1:132367
