### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by jasper-smit** [angular/angular#20280]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
At [https://angular.io/api/common/DatePipe](https://angular.io/api/common/DatePipe)
```
<!--output '2015-06-15 05:03 PM GMT+9'-->
    <p>The custom date is {{today | date:'yyyy-mm-dd HH:mm a z':'+0900'}}</p>
```

## Expected behavior
Should be 
```
<!--output '2015-06-15 05:03 PM GMT+9'-->
    <p>The custom date is {{today | date:'yyyy-MM-dd HH:mm a z':'+0900'}}</p>
```
(date is formatted with MM)

## What is the motivation / use case for changing the behavior?
Error in documentation

**Comment by ocombe** [comment]
Fixed with #20315
