### ISSUE TITLE
Can't resolve '../compiled/src/app/app.module.ngfactory' AOT

### ISSUE THREAD

**Issue by Ketec** [angular/angular#20281]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Upgraded from last angular version to 5 to test compatability. webpack-dev-derver works, JIT works.
But AOT fails.

`Module not found: Error: Can't resolve '../compiled/src/app/app.module.ngfactory' `

It is not a CLI project.
webpack conf has:
```
      entry: {
          'polyfills': './src/polyfills.browser.ts',
          'fa': 'font-awesome-sass-loader!./config/font-awesome.config.js',
          'main': AOT ? ('bootstrap-loader','./src/main.browser.aot.ts') : ('bootstrap-loader','./src/main.browser.ts')
      },
```

```
        new webpackTools.AngularCompilerPlugin({
            tsConfigPath: helpers.root('tsconfig.webpack.json'),
            skipCodeGeneration: !AOT
        }),
```
And tsconfig:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "noEmit": true,
    "noEmitHelpers": true,
    "strictNullChecks": false,
    "skipLibCheck": true,
    "lib": [
      "es2015",
      "dom"
    ],
    "typeRoots": [
      "node_modules/@types"
    ],
    "types": [
      "hammerjs",
      "jasmine",
      "node",
      "source-map",
      "uglify-js",
      "webpack",
      "jquery",
      "jasmine-expect",
      "d3"
    ],
    "outDir": "./compiled"
  },
  "exclude": [
    "node_modules",
    "build",
    "src/**/*.spec.ts",
    "src/**/*.e2e.ts"
  ],
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  },
  "angularCompilerOptions": {
    "genDir": "./compiled",
    "skipMetadataEmit": true
  },
  "compileOnSave": true,
  "buildOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}

```

The compiled folder is never created, therefor it cannot find the ngfactory file.

Any idea what changed in 5 to break AOT?

**Comment by alexzuza** [comment]
Use `compilerOptions.outDir` instead of `angularCompilerOptions.genDir` and seems you should also change path to your factory.

**Comment by Ketec** [comment]
This did nothing, i tried both ways. only in compileroptions, both at the same time - nothing changed.
I also tried the ./app/app.module.ngfactory" in the main entry - it couldn't find this one ether.

**Comment by brittanymoore** [comment]
Have you tried using entryModule in ngtools.AngularCompiler Plugin?

```
new ngtools.AngularCompilerPlugin({
    tsConfigPath: './tsconfig.aot.json',
    entryModule: './src/app/app.module#AppModule'
}),
```

When I upgraded, I also had to change the .ts loader pattern in my production configuration:

```
{ test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/, loader: '@ngtools/webpack', exclude: /node_modules/ },
```

tsconfig.aot.json:
```
{
    "compilerOptions": {
        "module": "es2015",
        "types": [ "node" ], 
        "noImplicitAny": true,
        "moduleResolution": "node",
        "target": "es5",
        "lib": ["es6", "dom"],  
        "typeRoots": ["node_modules/@types"],
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true
    }
}
```

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by AFigueroa** [comment]
I really still don't understand why this is, but in my case, I was able to solve this issue by adding a "include" property to my ts.config.json and adding both main.ts, and polyfills.ts to the "include" list.

`"include": [
        "./src/main.ts",
        "./src/polyfills.ts"
    ]`
