### ISSUE TITLE
An minor error with the tutorial

### ISSUE THREAD

**Issue by PoppinMic** [angular/angular#20294]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In this page of the tutorial,
https://angular.io/tutorial/toh-pt3#update-the-heroescomponent-template
after the description _"Bind the HeroesComponent.selectedHero to the element's hero property like this."_
The header colored blue is "hero_-detail_.component.html (HeroDetail binding)" which I think should be
"heroes.component.html"
![capture](https://user-images.githubusercontent.com/5344228/32598965-33db2d4e-c58f-11e7-8724-ec8256487924.PNG)

## Expected behavior

Change the minor error. It's kind of misleading.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jasonaden** [comment]
@PoppinMic Thanks for the issue and yes, I think you are correct. If you want, please submit a PR to fix this.

**Comment by kapunahelewong** [comment]
I was in there anyway so submitted the PR. Thanks for bringing this up @PoppinMic.

**Comment by jenniferfell** [comment]
Thanks for reporting this issue. It has been fixed in one of the recent releases. 

If we have not resolved your problem, please open a new issue. Thank you.
