### ISSUE TITLE
UrlResolver: Why does it require an anchor element to resolve a URL?

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2029]
This puts the requirement to run your test in a content shell/web driver in order to use the DOM. Is there a better way to do this, or at least an alternative implementation (even inefficient) that doesn't use the DOM for testing?

**Comment by rkirov** [comment]
dart can simply use https://api.dartlang.org/apidocs/channels/be/dartdoc-viewer/dart:core.Uri#id_parse as we did in angular.dart 1.x

**Comment by matanlurey** [comment]
:+1:

**Comment by vicb** [comment]
For reference, my [first implementation](https://github.com/vicb/angular/commit/9df8ba07899c9920dd7acfd1c7f0770b44911057#diff-6a3e64f22b71a1aab00d9415656eaa7bR1) was not using an anchor element. After discussing with @mhevery we decided that the browser was more capable or resolving urls.

I've kept the branch if at some later point we need to have an implementation that do not depend on the browser.

**Comment by ewinslow** [comment]
There is always https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

**Comment by mhevery** [comment]
Can this be pushed into the facade? That way we can solve this different on different platforms?

**Comment by vicb** [comment]
After having discussed with @tbosch I'll move away from the anchor element so that the `UrlResolver` can be used in any context (ie web workers, server side, ...)

**Comment by tbosch** [comment]
@mhevery: facades don't work if we need a different implementation for
client vs server
