### ISSUE TITLE
typo/error on tutorial page?

### ISSUE THREAD

**Issue by davlon** [angular/angular#20291]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

typo

## Expected behavior

replace with html

## What is the motivation / use case for changing the behavior?

clearer instruction

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ x
![angular typo](https://user-images.githubusercontent.com/14264456/32588621-e995f5e8-c507-11e7-862b-167b996747b5.png)
] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>
@

**Comment by jasonaden** [comment]
This issue isn't clearly explaining what you're trying to address. Please create a new issue with more detail if your issue persists.
