### ISSUE TITLE
AOT compile fails with Can't resolve '../compiled/src/app/app.module.ngfactory' 

### ISSUE THREAD

**Issue by Ketec** [angular/angular#20293]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I do not see the compiled folder being created at all.
I did try with:
```
        {
          test: /\.ts$/,
          use: [
			{
				loader: '@ngtools/webpack'
			},
          ],
          exclude: [/\.(spec|e2e)\.ts$/]
        },
```
for TS loader, it does build - but the main bundle is empty/1kb

## Minimal reproduction of the problem with instructions
Minimal project (removed all the custom components etc / logic).
https://gitlab.com/Tamm/Angluar5-starter
`npm run build:aot:prod` to run the aot build

I am unable to find problems in the setup/ missed configuration that would break it.

**Comment by alexzuza** [comment]
https://gitlab.com/Tamm/Angluar5-starter/blob/master/tsconfig.webpack.json#L10

**Comment by Ketec** [comment]
Worked before, is this some new change with 5?

**Comment by alexzuza** [comment]
As i said early you should also change path to factory like

`import { AppModuleNgFactory } from './app/app.module.ngfactory';`

**Comment by Ketec** [comment]
Confirmed. fixed the issue.
