### ISSUE TITLE
(router) Child routes handled by same component as parent route

### ISSUE THREAD

**Issue by rart** [angular/angular#20299]
## I'm submitting a...

```
[ x ] Bug report  <!-- Similar issue/PR: Not Found -->
```

## Current behavior
I have 2 child routes handled by the same parent route component as shown:
```
  {
    path: 'sites',
    component: SiteManagementComponent,
    children: [
      {
        path: 'create',
        component: SiteManagementComponent
      },
      {
        path: ':code',
        component: SiteManagementComponent
      }
    ]
  },
  /*
  {
    path: 'sites/create',
    component: SiteManagementComponent
  },
  {
    path: 'sites/:code',
    component: SiteManagementComponent
  },
  */
```

On the component, when visiting the child routes the URL told by the activeRoute is always that of the parent route (e.g. 'sites' in this case). I'm subscribed to `activatedRoute.params` and `activatedRoute.url`, and they both show the url/path to be `sites` even when navigating to `sites/create` & `sites/:code`. The subscription to params & url gets called in every case but the url is just not updated. 

The `router.url` is always updated correctly; if I observe the `router.url` value at any point in time (e.g. `activatedRoute.params`, `activatedRoute.url`, `ngOnInit`) it always shows `sites`, `sites/create`, `sites/:code` accordingly. The problem seems to be on the `activatedRoute`.

Notice on my setup above the commented top level routes also handled by the same component; when I take out the child routes and use them top level, the activatedRoute values seem to update correctly.

## Expected behavior

The activatedRoute reflects the correct *full* current URL at all points in time no matter of what component or route hierarchy.

## Minimal reproduction of the problem with instructions

[Here's a plunker with the issue reproduced](http://embed.plnkr.co/EQBtMA/): http://embed.plnkr.co/EQBtMA/

## What is the motivation / use case for changing the behavior?

Reliability & accuracy of the ActivatedRoute

## Environment

<pre><code>
$ ng --version
Angular CLI: 1.5.0
Node: 6.11.2
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.5.0
@angular/material: 2.0.0-beta.12
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1

Browser:
Chrome (desktop, mac OS) Version 61.0.3163.100 (Official Build) (64-bit)
(Didn't test other browsers)
 
For Tooling issues:
- Node version: 6.11.2
- Platform:  Mac

**Comment by jasonaden** [comment]
@rart You're getting this behavior because the `ActiveRoute` is a tree. If you do this:

`this.activeRoute.firstChild && this.activeRoute.firstChild.url._value.toString()`

You will get what you're looking for.

**Comment by rart** [comment]
Ah. I see. Thanks for your reply, @jasonaden :) 

I'm trying to make sense out of the decision that the position in the tree I'm getting here through `activatedRoute` is the root rather — than the leaf — which I'd argue is really the currently *activated* route; would you agree? I'm guessing the different components in the route hierarchy get a different position in the tree — at least when it's not the same component handling the entire route tree?

One component handling the entire route tree perhaps is not the most mainstream case, but at least in this case, feels like it makes it hard to subscribe to the params since, in the case of the navigation starting from `/parent` and going into `/parent/child`, can't subscribe to params/queryParams on `ngOnInit` (right?). Feels like now the component needs to be too aware of the route config rather than just knowing that it expects params X and Y. 

Can you advise what would be an architecturally-adequate strategy to get the leaf route params? This is what I came up with...
```
this.activeRoute.url
  .subscribe((urlSegment) => {
    if (this.activeRoute.firstChild) {
      this.activeRoute.firstChild
        .params
        .subscribe((params) => {
          // do stuff...
        });
    }
  });
```

Thanks indeed

**Comment by tony-gutierrez** [comment]
Same problem. If you have a child route using the same component as the parent, you do not get the childs params in a route.params.subscribe....
