### ISSUE TITLE
request routeChange  or  beforeRouteChange event

### ISSUE THREAD

**Issue by GoNode5** [angular/angular#20304]
## I'm submitting a...

<pre><code>
[X] Feature request
</code></pre>

## Current behavior
When a route Change the first event is this.routerSubscription = this.router.events.subscribe(event => {
console.log('first event:',event)
NavigationStart

## Expected behavior
an routeChangeEvent or beforeRouteChange
I need to know before a route actual change  the current route and state for various reasons (breadcrumb?) A navigator change also triggers components destroy etc. Sometimes I need to take action after the destroy

the routeChangeEvent should occur before Navigation Start

 https://ui-router.github.io/guide/transitions has
Create: The transition is being created
Before: The transition is about to start
Start: The transition has started

Angular only seems to have Start,  I need at least Before

**Comment by ghetolay** [comment]
I'm pretty what you need is already covered by one of the [router events](https://angular.io/api/router/Event).

But I must agree that for the most of us, when those event are exactly called is a bit fuzzy. We could improve the docs with some king of diagram for routing process showing all the steps and when those events are fired.

**Comment by GoNode5** [comment]
the source shows the sequence / lifecycle
https://github.com/angular/angular/blob/5.0.1/packages/router/src/events.ts#L322-L347

**Comment by GoNode5** [comment]
maybe NavigationStart can be extend with ActivatedRouteSnapshot, RouterStateSnapshot ?

**Comment by jasonaden** [comment]
@GoNode5 If you inject `ActivatedRoute` you should be able to get the snapshot from `ActivatedRoute.snapshot`. You can do the same with `RouterState` and `RouterState.snapshot`.

**Comment by GoNode5** [comment]
@jsayol ok moving to https://ui-router.github.io thnx

**Comment by GoNode5** [comment]
@jasonaden Inject where, don't understand what you mean. Asked on Gitter nobody knows or answer.
