### ISSUE TITLE
Can't register material icons anymore with version 5

### ISSUE THREAD

**Issue by Jonathan002** [angular/angular#20308]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I'm using an Angular 5 project and have installed material @angular/cdk@^5.0.0-rc0 + @angular/material@^5.0.0-rc0. When I try to register custom SVG Icons for Mat-Icon, I get the error: 
```
ERROR in Metadata version mismatch for module /Users/Me/dev/project/node_modules/@angular/material/core/typings/index.d.ts, found version 4, expected 3, resolving symbol AppSharedModule.
```

## Expected behavior

I would like to be able to register my svg Icons with IconRegistry of Material design without the version error.
```typescript
constructor(iconRegistry: MatIconRegistry, sanitizer: DomSanitizer) {
    iconRegistry
    .addSvgIcon('my-icon',
        sanitizer.bypassSecurityTrustResourceUrl('/assets/svg/my-icon.svg'));
}
```

## Minimal reproduction of the problem with instructions

Use Angular 5
```javascript
    "@angular/animations": "^5.0.0",
    "@angular/cdk": "^5.0.0-rc0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "^5.0.0-rc0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
```

Try to register icons e.g. AppModule/AppShared
```typescript
export class MyClass {
    constructor(iconRegistry: MatIconRegistry, sanitizer: DomSanitizer) {
        iconRegistry
         .addSvgIcon('my-icon',
            sanitizer.bypassSecurityTrustResourceUrl('/assets/svg/my-icon.svg'));
    }
}
```
Npm start
```
npm start
```

## What is the motivation / use case for changing the behavior?

Get the project to working

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jasonaden** [comment]
Please file this bug on the Material repo at https://github.com/angular/material2/issues.
