### ISSUE TITLE
Allow string to be passed as parameter in "headers" in HttpClient methods 

### ISSUE THREAD

**Issue by rafaelss95** [angular/angular#20319]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Basically the same of #20316.

Currently it's impossible to pass a simple string as `headers` [**HttpClient#get**](https://angular.io/api/common/http/HttpClient#get) method, for example. It only accepts `HttpHeaders | {[header: string]: string | string[]},`, so we can't pass a simple string, like this:

`this.httpClient.get(url, { headers: 'my-header:content' });`... 

Instead, we have to do this:

```
this.httpClient.get(url, new HttpHeaders('my-header:content'));
```

<hr>

... Also, I'm not too sure about the current signature (specifically `{[header: string]: string`). It means that if you want to pass an `object` **ALL** values **MUST** be a string. The following **valid** object, for example, will not compile and you'll have to "stringify" all values before call this method.

`this.httpClient.get(url, { headers: { content-x: true } });`

## Expected behavior
I'd expect more flexibility in passing parameters.

**Comment by petebacondarwin** [comment]
I'm afraid that this got no community support.
