### ISSUE TITLE
Allow string to be passed as parameter in "params" in HttpClient methods

### ISSUE THREAD

**Issue by rafaelss95** [angular/angular#20316]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently it isn't possible to pass a simple string as `params` in the [**HttpClient#get**](https://angular.io/api/common/http/HttpClient#get) method, for example, like below as the accepted types are `HttpParams|{[param: string]: string | string[]}`.

`this.httpClient.get(url, { params: 'angular=awesome&angular5=yes' });`... 

Instead, we have to do this:

```
this.httpClient.get(url, new HttpParams({
  fromString: 'angular=awesome&angular5=yes'
}));
```

<hr>

... Also, I'm not too sure about the current signature (specifically `{[param: string]: string`). It means that if you want to pass an `object`, **all** values **must** be _typeof_ string. The following **valid** object, for example, will not compile and you'll have to "stringify" all values before call this method.

`this.httpClient.get(url, { params: { angular: true, angular5: 1 } });`

## Expected behavior
I'd expect more flexibility in passing parameters.

**Comment by rafaelss95** [comment]
@jasonaden I think you've removed `comp: common/http` label wrongly. Can you please add it again? Thanks.

**Comment by trotyl** [comment]
Relates to #18403

**Comment by petebacondarwin** [comment]
Closing. See https://github.com/angular/angular/pull/20727#issuecomment-763947297
