### ISSUE TITLE
Fix a typo in angular tour of heroes tutorial

### ISSUE THREAD

**Issue by ddazal** [angular/angular#20322]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There is an error/typo in Angular Tour of Heroes tutorial, more specifically in this [section](https://angular.io/tutorial/toh-pt0#change-the-application-title) in the paragraph after the first panel. It is written: 
> Open the component template file (app.component.ts) and delete the default template generated by the Angular CLI. Replace it with the following line of HTML.

Where `app.component.ts` is not the correct file.
## Expected behavior

It should be:
> Open the component template file (app.component.html) and delete the default template generated by the Angular CLI. Replace it with the following line of HTML.

Where `app.component.html` is the correct file.
## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
Will be fixed by https://github.com/angular/angular/pull/20318

**Comment by ddazal** [comment]
Great! I didn't see that issue. Closing this
