### ISSUE TITLE
(docs) 404 error shown for a link in documenetation

### ISSUE THREAD

**Issue by aravindfz** [angular/angular#20338]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

404 error shown on clicking the `schema.ts` file in this [doc link ](https://angular.io/guide/aot-compiler#phase-1-analysis)

**Schema Link** : https://github.com/angular/angular/blob/master/packages/tsc-wrapped/src/schema.ts

## Expected behavior

Schema file should be seen in github

## What is the motivation / use case for changing the behavior?

 - Perfect documentation for reference

## Environment

<pre><code>
Angular version: 5.0.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
The new location is https://github.com/angular/angular/blob/master/packages/compiler-cli/src/metadata/schema.ts.
@aravindfz, would you like to submit a PR with the fix?

**Comment by aravindfz** [comment]
@gkalpak Raised a PR
