### ISSUE TITLE
Add .every() function to QueryList so I don't have to do ql.toArray().every()

### ISSUE THREAD

**Issue by Anticom** [angular/angular#20333]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I'm currently in the process of implementing a [`WizardComponent`](https://youtu.be/JhNo3Wvj6UQ?t=4260) and my steps are retreived via `@ContentChildren` which is giving me a `QueryList<Step>`.
Since every of my `Step`s has a `visited` property i'd like to be able to check if every step has been visited easily. In order to do that using `every()` function on array object I currently have to call `toArray()` on the QueryList (which is not prefered afaik).

```TypeScript
const allVistied = this.steps.toArray().every(step => step.visited);
```

## Expected behavior

```TypeScript
const allVistied = this.steps.every(step => step.visited);
```

## Minimal reproduction of the problem with instructions

Since I'm requesting to just provide a new API I don't think you need any working example. However if you actually **do**, just ping me and i'll provide one.

## What is the motivation / use case for changing the behavior?

Use case is described above. IMHO it would be great to have QueryLists's API closer to the one of Array.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [x] Chromium version 62.0.3202.75 (Offizieller Build) Built on Ubuntu , running on Ubuntu 16.04 (64-Bit)

**Comment by Toxicable** [comment]
I don't think that we should reimplment methods that already exist in js, even if we are just providing a proxy to the `Array#every` it will cause confusion on what a `QueryList` actually is.
Especially since you can easily convert it to an array anyway.

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

**Comment by Anticom** [comment]
Okay so just for my personal understanding, in such case is using `.toArray()` preferable?
