### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error: StaticInjectorError[e]:

### ISSUE THREAD

**Issue by mushinz** [angular/angular#20339]
https://image.prntscr.com/image/4Huq_HhQTHyIjYKH0ztgKw.png

`ERROR Error: Uncaught (in promise): Error: StaticInjectorError[e]: 
  StaticInjectorError[e]: 
    NullInjectorError: No provider for e!`

**Comment by mushinz** [comment]
Importing both HttpModule and HttpClientModule fixes the problem.


`import { HttpClientModule } from '@angular/common/http';
import { HttpModule } from '@angular/http';`

**Comment by vicb** [comment]
@ocombe is working on a fix (better error message)

**Comment by SK-Agrawal** [comment]
Add import { HttpModule } from '@angular/http'; in app.module.ts

**Comment by Heena-Vora** [comment]
still not working for me

**Comment by raghavjatin** [comment]
also not working for me , same error

**Comment by likeamugger** [comment]
Same issue here! Does not work after importing

**Comment by semtos** [comment]
Same problem for me. I really regret starting my projects with angular!

**Comment by Moshiour027** [comment]
same here

**Comment by Muhammad-Soban** [comment]
Not working for me

**Comment by crowster** [comment]
in app module
**Step 1 add import** 
import { HttpModule } from '@angular/http';
**Step 2 add HttModule in :**
  imports: [
    HttpModule       
  ],
.....

**Comment by 22ryann** [comment]
Have the same issue :(

**Comment by danielszuk** [comment]
same issue here

**Comment by jersonjohn** [comment]
Same error , Not working for me too

**Comment by mumairofficial** [comment]
Worked by importing `HttpClientModule` even I am not using this module in whole app.. that's wired.

**Comment by jersonjohn** [comment]
Have to add app.module.ts under provider section to make them available in providers


Problem fixed!! HUHU

**Comment by ilivestrong** [comment]
@jersonjohn - Which service to registere in Providers section. I am facing the same issue and after reading above suggestions,  I have already imported HttpClient and HttpClientModule in my app.module.ts (even though I am not using them)...

Please advise.

Thanks
Deepak

**Comment by ilivestrong** [comment]
<img width="607" alt="capture" src="https://user-images.githubusercontent.com/13273605/34328466-1b753bea-e912-11e7-99ee-49383facb6b7.PNG">

**Comment by jersonjohn** [comment]
providers: [
    AuthGuard,
    CookieService,
    CompanyService,
    PolicyService,
    CommunicationService,
    AuthenticationService
  ]

**Comment by jersonjohn** [comment]
@ilivestrong all services need to configure in the providers section of the app.module.ts

Something like this

providers: [
AuthGuard,
CookieService,
CompanyService,
PolicyService,
CommunicationService,
AuthenticationService
]

**Comment by ilivestrong** [comment]
@jersonjohn  - I already have all my custom services and angular services in providers array. Not sure why it's not working. I am just trying to build a login page using a reactive form (using FormBuilder).

Not sure what is breaking it...

**Comment by mumairofficial** [comment]
@ilivestrong have you included `ReactiveFromsModule` in *import array* of app.module.ts

**Comment by ilivestrong** [comment]
@mumairofficial - Yes I did. Strangely I created a new project and it went away, only until I wrote a new route guard and I get this StaticInjectionError for my route guard now.

This route guard is provided as well. :(

**Comment by HanVertegaal** [comment]
I had the same problem after creating a new service using ng-cli. This should automatically add the service to the providers array in app.module.ts

**Comment by VikashChoudahry** [comment]
I had same issue but after importing "**HttpModule**" in "app.module.ts" it worked fine for me.

1. import { HttpModule } from '@angular/http';
2. Add "HttpModule" in imports array list.

Thanks.
Keep Sharing.

**Comment by ShahidMirza2017** [comment]
Add import { HttpModule } from '@angular/http'; in app.module.ts for Http
Or 
Add import {HttpClientModule} from '@angular/common/http' in app.module.ts for httpclient

**Comment by amitkprajapati** [comment]
I imported both HttpModule and HttpClientModule but still getting the same error , Please any one help me out , i am trying to implement routing .

**Comment by nvigneux** [comment]
@amitkprajapati import HttpClientModule in `app.module.ts `

```
import { HttpClientModule } from '@angular/common/http'
///
@NgModule({
  imports: [ HttpClientModule ]
})
```

**Comment by HollyMarsia** [comment]
![default](https://user-images.githubusercontent.com/35092305/34552103-d8e24904-f162-11e7-9e03-8391ca95a480.PNG)

I had the same problem.
in my app this issue I did it like this.
step1. Check. app.Module.ts file inner import []

step2. Check the modules you created and see if any of the newly created files are unimported.

- In my case, I tried to register with the ' Effect ' without importing ' FreezerService ' from the 'core module' that manages the service module.

**Comment by mumairofficial** [comment]
add `FreezerService` into `providers` array of **app.module.ts**

**Comment by EmRa228** [comment]
Stop ionic and rerun "ionic serve" to show real error message to you.

**Comment by kverma17** [comment]
Not working with any of the solutions.

FILES -----
![error](https://user-images.githubusercontent.com/35423116/35138943-d7764132-fd16-11e7-8cc9-0edf8cbca953.png)
![system](https://user-images.githubusercontent.com/35423116/35138944-d7a919f4-fd16-11e7-8523-34b03a1be3a6.png)
![appmodulets](https://user-images.githubusercontent.com/35423116/35138873-84cabdd2-fd16-11e7-822e-d09c5de89869.png)
![homets](https://user-images.githubusercontent.com/35423116/35138874-85047f7c-fd16-11e7-865e-3de04029e4c2.png)
![packagejson](https://user-images.githubusercontent.com/35423116/35138875-85334938-fd16-11e7-9f42-0bf2dcaa519c.png)

**Comment by mumairofficial** [comment]
@kverma17 add `Camera ` to provider array in side of **app.module.ts** and donot forget to _import_ it :)

**Comment by jersonjohn** [comment]
Sorry I am not accessing computers as travelling now

**Comment by SK-Agrawal** [comment]
The above one is right .you should define the it in provider of app.module
file .

**Comment by devraj88** [comment]
You need provide your dataservices
import ...........
import { DataService } from '../dataservice';

@Component({
  selector: '.......
  templateUrl: ........
  styleUrls:......,
  providers: [DataService]
})

**Comment by miriiit** [comment]
these error occur when we use feature module just add 

RouterModule.forRoot({}) above the
 RouterModule.forFeature('Items',reducers)

**Comment by nagarajbyndoor** [comment]
Thanks @jersonjohn your suggestions helped :)

**Comment by csharpspecialist** [comment]
Make sure you are adding HttpModule and not just Http.  That was my problem.  Even adding Http would not fix my issue.  I had to add HttpModule as shown in the next paragraph.

Add import { HttpModule } from '@angular/http'; in app.module.ts , which of course means that I had to add it to the imports array below as well.

If you Add import { Http } from '@angular/http'; in app.module.ts by itself then it will still show you an error...even if you add a reference to it in the imports array/list below.  

The newest version of the CLI does not add this to your build when using npm if it is generating a new package for some reason.  It must have previously done this but not any longer.

If you are trying to build this youtube series project then you will need to import HttpModule into your app.module.ts file!!!
https://www.youtube.com/watch?v=pxv-0WeT44w

**Comment by mumairofficial** [comment]
_Just for information_ `HttpModule` is deprecated in favor of `HttpClientModule` from `@angular/common/http` package; use the latest one to make upgrade easy :+1:

**Comment by byassine52** [comment]
I had the same problem when I moved a property to a component inside `constructor()` parameters.
It was solved when I moved it out back.

**Comment by garycsebastian** [comment]
ionic serve ... again

**Comment by disujha** [comment]
Apart from above solutions... I think removing the NavCtrl from service also helps. Seems there is conflict between NavCtrl of Component and Service/Provider

**Comment by noameini** [comment]
![abc](https://user-images.githubusercontent.com/33673086/36179264-4e6a22ce-1124-11e8-9356-e044cbef8ef5.png)

I had the same problem.

**Comment by geyma1311** [comment]
my solution was to add my service in the providers in my component.ts

**Comment by chambahr** [comment]
import { HttpModule } from '@angular/http'; and then add HttpModule to imports

,imports: [
    HttpModule,
    BrowserModule,
    IonicModule.forRoot(MyApp),
  ],
This fixes the problem for me. 
you can also import 
 import { HttpClientModule } from '@angular/common/http'; for convenience sake

**Comment by fmorc** [comment]
You need to provide your service in the module where your component is being declared:

@NgModule({
  imports: [
    SharedModule,
    RouterModule.forChild([
      { path: 'login', component: LoginComponent }
    ])
  ],
  declarations: [
    **LoginComponent**
  ],
  providers: [
    **AuthService**
  ]

And then referencing it in your component and injecting in the constructor. Make sure your service has the Injectable decorator

**Comment by duggu123** [comment]
you need to import  AngularFireDatabaseModule                <---- for database 
                               AngularFireAuthModule                         <----for AngularAuth


`import { AngularFireModule } from 'angularfire2';
// for AngularFireDatabase
import { AngularFireDatabaseModule } from 'angularfire2/database';
import { AngularFireDatabase, FirebaseObjectObservable } from 'angularfire2/database';
// for AngularFireAuth
import { AngularFireAuthModule } from 'angularfire2/auth';
import { AngularFireAuth } from 'angularfire2/auth';

**@NgModule**({
  imports: [
    AngularFireModule.initializeApp({         <---- main module
      apiKey: ...,
      authDomain: '...',
      databaseURL: '...',
      storageBucket: '...',
      messagingSenderId: '...'
    }),                                       
    AngularFireDatabaseModule,                <---- for database 
    AngularFireAuthModule                     <---- for auth
  ]
})`

**Comment by T-candy** [comment]
i solved this problem.
at 'app.module.ts'
add " import {HttpClientModule} from '@angular/common/http' "
and , 
imports: [
    BrowserModule,
    HttpModule,
    HttpClientModule,
    IonicModule.forRoot(MyApp)
  ]

**Comment by qam12** [comment]
Thanks @mushinz

**Comment by ProgrammingFuad** [comment]
@jersonjohn thanks your guidance on adding services as a provider did the trick for me!

**Comment by BOUHAFSADMI** [comment]
I got this error in Angular 5.2.7 and importing HttpClientModule to the app.module.ts solved the the problem,
don't forget to add HttpClientModule to the imports: [] and don't forget the service provider too providers: []

**Comment by qinwanguk** [comment]
Thanks @T-candy, 
it worked for me. 

just import HttpClientModule instead of HttpModule 

ionic must changed handle name...


using ionic 3.x

**Comment by hiteshmandav** [comment]
iam using it to comnfigurre it with firebase.
after adding AngularFireDatabase to providders in app.module.ts the problem is solved.
:):)

**Comment by valentinoPereira** [comment]
All I did was add my service to providers array of app.module

**Comment by Heena-Vora** [comment]
I also got this working by importing **HttpModule** from **angular/http@5.2.9** in app.module.ts

```
import { HttpModule } from '@angular/http';
@NgModule({
    imports: [
       ...,
       HttpModule,
       ...
})
```

**Comment by priyankshukla** [comment]
That is because we have not injected our services in app module.

We have to pass our service at 2 places in app.module.ts
importing the service
added them in providers

import {ConfigService} from './providers/config.service';

....
providers: [ConfigService],
...

**Comment by vd853** [comment]
This error was caused by introducing angular2-cookie for me. It works during "ng serve", but not "ng build --prod". Solution was simply removing it from the project.  Didn't really use it anyways.

**Comment by xwa130** [comment]
I solve this by following two steps: 
> import { BrowserModule }  from '@angular/platform-browser';
...
  imports: [
    BrowserModule,
  ]

**Comment by Sharanagouda** [comment]
in app.module.ts I am using angular 5
import { HttpClientModule } from '@angular/common/http';
and add 
HttpClientModule inside import

**Comment by jitendriyag2** [comment]
Just verify Your Code with below one:

> import { BrowserModule } from '@angular/platform-browser';
> import { NgModule } from '@angular/core';
> import { HttpClientModule } from "@angular/common/http";
> 
> @NgModule({
> 
>   declarations: [
>       .....
>   ],
> imports: [
>       BrowserModule,
>       **`HttpClientModule`**
>   ],
>  providers: [
>        .....
>     ],
>   bootstrap: [AppComponent]
> })


the above Code resolve the issue

**Comment by bfaruqi** [comment]
in app module
import { FormsModule } from '@angular/forms';
import { Http, HttpModule } from '@angular/http';
import { HttpClientModule } from '@angular/common/http' 

in NgModules imports 
 HttpModule,
        HttpClientModule,
        FormsModule,

and it worked for me

**Comment by DebaratiMajumder** [comment]
Use HttpModule as the provider instead of Http.  It will register all its services.

**Comment by timzarema** [comment]
I spend a lot of time trying to figure out this error and tried all suggestions and non of them worked in my code. The solution for me was  adding the service to providers in app.module.ts
providers: [
    ClientService
   ],

**Comment by jigneshcitrusbug** [comment]
Fixed by Change in app.module.ts 

import { BrowserModule } from '@angular/platform-browser';
import { NgModule, ErrorHandler } from '@angular/core';
import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
import { HttpClientModule } from '@angular/common/http';

import { MyApp } from './app.component';

import { UsersPage } from '../pages/users/users';
import { ReposPage } from '../pages/repos/repos';
import { OrganisationsPage } from '../pages/organisations/organisations';

import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
import { GithubUsersProvider } from '../providers/github-users/github-users';
import { PeopleServiceProvider } from '../providers/people-service/people-service';

@NgModule({
  declarations: [
    MyApp,
    UsersPage,
    ReposPage,
    OrganisationsPage
  ],
  imports: [
    HttpClientModule,
    BrowserModule,
    IonicModule.forRoot(MyApp),
    
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    UsersPage,
    ReposPage,
    OrganisationsPage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler},
    GithubUsersProvider,
    PeopleServiceProvider
  ]
})
export class AppModule {}

**Comment by aj-nash** [comment]
Add HttpClientModule instead

**Comment by phil123456** [comment]
I got rid of "angular2-cookie/core" and wrote 2 functions to get and set cookies, problem solved

**Comment by webtechperfect** [comment]
If in authservice you used { Http } from '@angular/http',
then change it to { HttpClient } from '@angular/common/http'
and in constructor of authservice change parameter type from Http to HttpClient

**Comment by MehdiZohrevnd** [comment]
however someone answered correctly but i refer to correct solution too ....
1 - if you'r version is '6' in app.module use 'HttpClientModule' and 'HttpClient' from '@angular/common/http':

2 - otherwise use  'HttpModule' and 'Http' from '@angular/http':

**Comment by asrar7** [comment]
@MehdiZohrevnd  what should be version 6 ?

**Comment by bfheythem** [comment]
I am having the same issue , even when I do the HttpClientModule imports :/ plz help

**Comment by panchomr** [comment]
Hi , i solved this way , in angular 6 httpModule is deprecated and was removed from Angular.

this is my app.module.ts

`import { HttpClientModule } from '@angular/common/http';`

and then add into imports:

```
imports: [
    APP_ROUTING,
    BrowserModule,
    RouterModule,
    HttpClientModule
  ],
```
in my service 

`import { HttpClient, HttpHeaders, HttpClientModule } from '@angular/common/http';`

and this works for me

cheers!

**Comment by itamark** [comment]
As was mentioned above, this worked for me:
In `app.module.ts` import `HttpClientModule` and include it in your imports array.
In your service use HttpClient (`http: HttpClient` in constructor)

**Comment by omsaravanan** [comment]
Using Angular 6 and tried every suggestion... the problem continues... pls suggest

**Comment by adrobson** [comment]
In my case I had multiple resolvers and was using the wrong syntax by putting a [] around the resolvers eg [{name1:resolver1{,{name2:resolver2}] . Instead the syntax should be {name1:resolver1,name2:resolver2}

**Comment by SK-Agrawal** [comment]
Instead of  doing this  [{name1:resolver1*{*,{name2:resolver2}]
Please try this one      [{name1:resolver1*}*,{name2:resolver2}]

**Comment by jardelsimao** [comment]
this worked for me

@Injectable({
  providedIn: 'root',
})

**Comment by alundiak** [comment]
Just in case someone needs additional info, especially if it's about erros with `ng test`.
I had this error(s):

>Error: StaticInjectorError(DynamicTestModule)[HttpClient]: 
StaticInjectorError(Platform: core)[HttpClient]: 
NullInjectorError: No provider for HttpClient!

So this is what helped me:

I added to my xyz.component.`spec.ts` file

```
import { HttpClientModule } from '@angular/common/http';
import { ReactiveFormsModule } from '@angular/forms';
import { RouterTestingModule } from '@angular/router/testing';
```
and

```
TestBed.configureTestingModule({
      imports: [ HttpClientModule, ReactiveFormsModule, RouterTestingModule ], // new line
      declarations: [ BookCreateComponent ],
      schemas: [ CUSTOM_ELEMENTS_SCHEMA ]
})
```

In fact,
-  Injection of  `HttpClientModule` helps to get rid of `StaticInjectorError`
- Injection of `ReactiveFormsModule` and `RouterTestingModule` helps to get rid of `Can't bind to 'routerLink' since it isn't a known property of 'a'.`

Notes: Angular v6.1.1, Angular Material v 6.1.1, Angular CLI v6.1.2

**Comment by mhsworkonline** [comment]
One of the ways I was able to solve this issue is:

Add "HttpClientModule" existing in '@angular/common/http' in app.module.ts and add "HttpCleint" existing in '@angular/common/http' in the component/service wherein you are sending Http requests.

**Comment by Confiuzer** [comment]
In the auth.guard.ts 

```
@Injectable({
    providedIn: 'root',
})
```

**Comment by christiantigre** [comment]
I solved 
import { HttpClientModule } from '@angular/common/http'; 
import { HttpModule } from '@angular/http'; 

imports: [
    BrowserModule,
    HttpModule,
    HttpClientModule,
    IonicModule.forRoot(MyApp)
  ],

for mi

**Comment by noameini** [comment]
Problem fixed !
Thank you all !

**Comment by Jasa-Bcone** [comment]
> Importing both HttpModule and HttpClientModule fixes the problem.
> 
> `import { HttpClientModule } from '@angular/common/http'; import { HttpModule } from '@angular/http';`

if  we are using {Http ,Headers, or anything } from '@angular/http';  in app.compontent.ts file or app.service.ts file or any otherfile.ts then we have to  add HttpModule  in app.module.ts before using these in service.ts file or component.ts file

**Comment by macyun** [comment]
![image](https://user-images.githubusercontent.com/13185821/50752197-2eb55a00-1288-11e9-9084-8e9b1b9fb8fc.png)
![image](https://user-images.githubusercontent.com/13185821/50752374-feba8680-1288-11e9-9559-c6b31cfede59.png)
![image](https://user-images.githubusercontent.com/13185821/50752360-f2362e00-1288-11e9-92bd-7204f4b8160b.png)

not working for me..

**Comment by macyun** [comment]
angular-cli version is too high, Problem fixed

**Comment by macyun** [comment]
> > angular-cli version is too high, Problem fixed
> 
> how did you fix it

Reduce the @angular/cli version to 6.2.8

**Comment by MarcioBdeveloper** [comment]
the correct amount is { Http } from '@angular/http'; in Providers

**Comment by Elite40** [comment]
I'm using ionic version 3 and the following solution worked for me: 

Inside _app_module.ts_ add: `import { HttpClientModule } from '@angular/common/http';`

Then add that to your imports array, like so: 
` imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
    HttpClientModule
  ],`

**Comment by diegodelfin7** [comment]
Thanks . I had same issue but it got fixed

**Comment by ghulamakbar14** [comment]
I have same issue but it is not fixed.
My files are:

1. 

app.module.ts
import { HttpClientModule } from '@angular/common/http';
import { HttpModule } from '@angular/http';

imports: [
    ...
    HttpClientModule,
    HttpModule
  ]

1. 
package.json

 "devDependencies": {
    "@angular-devkit/architect": "~0.12.3",
    "@angular-devkit/build-angular": "~0.12.3",
    "@angular-devkit/core": "~7.2.3",
    "@angular-devkit/schematics": "~7.2.3",
    "@angular/cli": "7.2.4",
    "@angular/compiler": "~7.2.2",
    "@angular/compiler-cli": "^7.2.6",
    "@angular/language-service": "~7.2.2",
    "@ionic/angular-toolkit": "~1.4.0",
    "@ionic/lab": "1.0.21",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.12.0",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.0.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~8.0.0",
    "tslint": "~5.12.0",
    "typescript": "~3.1.6"
  },

**Comment by josemorenoaguilera** [comment]
This work for me:
at the app.module.ts
import { HttpModule } from '@angular/http';

in @NgModule import HttpModule and works!

**Comment by oscarhandsome** [comment]
For me helped: 
`import {HttpClientModule} from '@angular/common/http';`
to imports - `HttpClientModule`
in the app.module.ts

**Comment by johnedvard** [comment]
Remember that Pipes also needs to be in the providers' array. I got the error when I had my Pipes in a shared module, exporting them, but forgot to add them as providers.
`providers: [MyPipe]`

**Comment by vijayamurugan** [comment]
The solution is simple that you might be missing services under providers array. When you run in devlopment mode you will be able exactly identify the missing service under providers array. When you run in production mode the error log doesn't show the exact missing service/s under providers.
