### ISSUE TITLE
Custom NgModuleFactoryLoader receive null Compiler

### ISSUE THREAD

**Issue by luboid** [angular/angular#20336]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
No

## Expected behavior
New instance of NgModuleFactoryLoader to receive instance of Compiler.
Why I can't register custom NgModuleFactoryLoader with platformBrowserDynamic.bootstrapModule.

## Minimal reproduction of the problem with instructions
https://github.com/luboid/requirejs-angular-router

```cmd
npm i
```
```cmd
npm start
```
```html
Source code:
/src/loader/require-js-ng-module-loader.ts
Used in:
/src/app/app-routing.module.ts (32)
/src/app/app-routing.module.ts (43)
```

## What is the motivation / use case for changing the behavior?
Run Angular app with RequireJs

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [X ] Chrome (desktop) version 61.0.3163.100 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.3
- Platform:  Windows 

Others:

</code></pre>

**Comment by trotyl** [comment]
So the problem is only `Compiler` not available via DI? Seems nothing relates to `NgModuleFactoryLoader`.

**Comment by luboid** [comment]
Is DI not a part of Angular?

**Comment by trotyl** [comment]
```typescript
export const requireJsNgModuleFactoryLoaderProvider = {
  provide: NgModuleFactoryLoader,
  useClass: RequireJsNgModuleLoader,
  deps: <any>[]
};
```

You're manually [setting `deps` to empty array](https://github.com/luboid/requirejs-angular-router/blob/master/src/loader/require-js-ng-module-loader.ts#L127), what're you expecting then?

**Comment by mlc-mlapis** [comment]
@luboid ... but it is basic thing that Compiler is not available in AOT mode through DI. It is exactly how Angular Router also works ... and this point is exactly how it differentiate between JIT and AOT mode.

**Comment by trotyl** [comment]
@mlc-mlapis The repo is indeed JIT only...

**Comment by mlc-mlapis** [comment]
@trotyl ... ah, sorry then, I was too fast. 👍

**Comment by luboid** [comment]
Yes it  JIT only. I'am really sorry about this, but deps in StaticClassProvider is mandatory and it is remained from my try to register NgModuleFactoryLoader with platformBrowserDynamic.bootstrapModule

@angular\core\src\di\provider.d.ts (66-91)
```TypeScript
export interface StaticClassProvider {
    /**
     * An injection token. (Typically an instance of `Type` or `InjectionToken`, but can be `any`).
     */
    provide: any;
    /**
     * An optional class to instantiate for the `token`. (If not provided `provide` is assumed to be a
     * class to
     * instantiate)
     */
    useClass: Type<any>;
    /**
     * A list of `token`s which need to be resolved by the injector. The list of values is then
     * used as arguments to the `useClass` constructor.
     */
    deps: any[];
    /**
     * If true, then injector returns an array of instances. This is useful to allow multiple
     * providers spread across many files to provide configuration information to a common token.
     *
     * ### Example
     *
     * {@example core/di/ts/provider_spec.ts region='MultiProviderAspect'}
     */
    multi?: boolean;
}
```

**Comment by trotyl** [comment]
Since it's registered in [`NgModule`](https://github.com/angular/angular/blob/master/packages/core/src/metadata/ng_module.ts), the type used is `Provider` instead of `StaticProvider`:

```typescript
export interface NgModule {
  /**
   * Defines the set of injectable objects that are available in the injector
   * of this module.
   *
   * ## Simple Example
   *
   * Here is an example of a class that can be injected:
   *
   * ```
   * class Greeter {
   *    greet(name:string) {
   *      return 'Hello ' + name + '!';
   *    }
   * }
   *
   * @NgModule({
   *   providers: [
   *     Greeter
   *   ]
   * })
   * class HelloWorld {
   *   greeter:Greeter;
   *
   *   constructor(greeter:Greeter) {
   *     this.greeter = greeter;
   *   }
   * }
   * ```
   */
  providers?: Provider[];
 //...
}
```

Only platform providers (or other dynamic ones) are required to be `StaticClassProvider`.

**Comment by trotyl** [comment]
The type used in `NgModule` metadata is `Provider[]` instead of `StaticProvider[]`, which is:

```typescript
export type Provider =
    TypeProvider | ValueProvider | ClassProvider | ExistingProvider | FactoryProvider | any[];
```

`StaticProvider` are only required for platform providers (or other dynamic ones).

**Comment by luboid** [comment]
Ok don't argue with you, It was sequence of tries first platform, second AppModule and third AppRouteModule 
there is no help where to register that thing, and this not cross my mind, I was expecting consistency here

**Comment by trotyl** [comment]
So I guess it could be closed now?

**Comment by luboid** [comment]
Yes
