### ISSUE TITLE
trouble with hyperlink in documentation

### ISSUE THREAD

**Issue by pasha-bolokhov-cs** [angular/angular#20348]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

https://angular.io/guide/component-interaction#parent-interacts-with-child-via-local-variable
Under subsection "Test it" it shows a Markdown link in markdown, 
 \[the same countdown timer tests\](guide/component-interaction#countdown-tests)
but not as a link

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
Thanks for reporting this issue. It has been fixed in one of the recent releases. 

If we have not addressed your problem, please open a new issue. Thank you.
