### ISSUE TITLE
HttpClient.get<[type]> should return actual type

### ISSUE THREAD

**Issue by sylvaingirardbe** [angular/angular#20344]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When doing an http request like this
`this.http.get<InterventionType[]>('https://localhost:44384/api/interventiontypes')`
the return type is not an actual array of intervention types but an array of objects with the correct property names.

## Expected behavior

An array of objects of the actual type I specified.
The thing I need to ddo now to get the required behaviour is this:
<pre><code>this.http
            .get<InterventionType[]>('https://localhost:44384/api/interventiontypes')
            .switchMap(interventionTypes => 
                interventionTypes
                    .map(interventionType => InterventionType.createInterventionType(interventionType.id, interventionType.name)))
            .toArray();
</code></pre>
## What is the motivation / use case for changing the behavior?

I have a toString method on those types that are required by typeahead, for instance. 

## Environment

<pre><code>
Angular version: 4.4.6

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.4.0  
- Platform:  Windows

Others:

</code></pre>

**Comment by Toxicable** [comment]
Sorry but that isn't how TS works.
The types only exist at build time so if you provide a class we don't have a token to invoke it with at runtime.
I would suggest using a interface instead.

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
