### ISSUE TITLE
Issue with importing Observable from rxjs/Rx (import-blacklisted)

### ISSUE THREAD

**Issue by vajahath** [angular/angular#20349]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I was following [this part of our official guide](https://angular.io/tutorial/toh-pt4#observable-heroservice).
```ts
import { Observable } from 'rxjs/Rx'; // this line rises a tslint err
import { of } from 'rxjs/observable/of';
```
![import blacklisted](https://user-images.githubusercontent.com/12165822/32685701-74f236aa-c6bc-11e7-8246-8ab6063c9c7e.png)

```
ERR: [tslint] This import is blacklisted, import a submodule instead (import-blacklist)
```
Please shed some light on this issue.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.1  
- Platform:  Linux, Windows.

</code></pre>

## other info
Just in case if you are interested in my `tslint.json`. (same as generated by `ng new`)
```json
{
	"rulesDirectory": ["node_modules/codelyzer"],
	"rules": {
		"arrow-return-shorthand": true,
		"callable-types": true,
		"class-name": true,
		"comment-format": [true, "check-space"],
		"curly": true,
		"eofline": true,
		"forin": true,
		"import-blacklist": [true, "rxjs", "rxjs/Rx"], <<<<
		"import-spacing": true,
		"indent": [true, "tabs"],
		"interface-over-type-literal": true,
		"label-position": true,
		"max-line-length": [true, 140],
		"member-access": false,
		"member-ordering": [
			true,
			{
				"order": [
					"static-field",
					"instance-field",
					"static-method",
					"instance-method"
				]
			}
		],
		"no-arg": true,
		"no-bitwise": true,
		"no-console": [true, "debug", "info", "time", "timeEnd", "trace"],
		"no-construct": true,
		"no-debugger": true,
		"no-duplicate-super": true,
		"no-empty": false,
		"no-empty-interface": true,
		"no-eval": true,
		"no-inferrable-types": [true, "ignore-params"],
		"no-misused-new": true,
		"no-non-null-assertion": true,
		"no-shadowed-variable": true,
		"no-string-literal": false,
		"no-string-throw": true,
		"no-switch-case-fall-through": true,
		"no-trailing-whitespace": true,
		"no-unnecessary-initializer": true,
		"no-unused-expression": true,
		"no-use-before-declare": true,
		"no-var-keyword": true,
		"object-literal-sort-keys": false,
		"one-line": [
			true,
			"check-open-brace",
			"check-catch",
			"check-else",
			"check-whitespace"
		],
		"prefer-const": true,
		"quotemark": [true, "single"],
		"radix": true,
		"semicolon": [true, "always"],
		"triple-equals": [true, "allow-null-check"],
		"typedef-whitespace": [
			true,
			{
				"call-signature": "nospace",
				"index-signature": "nospace",
				"parameter": "nospace",
				"property-declaration": "nospace",
				"variable-declaration": "nospace"
			}
		],
		"typeof-compare": true,
		"unified-signatures": true,
		"variable-name": false,
		"whitespace": [
			true,
			"check-branch",
			"check-decl",
			"check-operator",
			"check-separator",
			"check-type"
		],
		"directive-selector": [true, "attribute", "app", "camelCase"],
		"component-selector": [true, "element", "app", "kebab-case"],
		"use-input-property-decorator": true,
		"use-output-property-decorator": true,
		"use-host-property-decorator": true,
		"no-input-rename": true,
		"no-output-rename": true,
		"use-life-cycle-interface": true,
		"use-pipe-transform-interface": true,
		"component-class-suffix": true,
		"directive-class-suffix": true,
		"invoke-injectable": true
	}
}
```
Related: https://github.com/angular/angular-cli/issues/7591

**Comment by Toxicable** [comment]
You shouldn't import from `'rxjs'` or `'rxjs/Rx'` since either import will import the whole of rxjs which will dramatically increase the size of your bundle.

This should be changed in the docs to `import { Observable } from 'rxjs/Observable ';`

**Comment by jasonaden** [comment]
Closing as you should use the above suggestion.

**Comment by mlc-mlapis** [comment]
@fetis ... yes ... because otherwise the complete RxJS will be added to a bundle.

**Comment by fetis** [comment]
@mlc-mlapis how big this overhead? I see that in RxJS6 they gonna change import format
```
// rxjs 6 alpha
import { Observable, Subject, ReplaySubject } from 'rxjs';
import { from, of, range } from 'rxjs/create';
import { map, filter, switchMap } from 'rxjs/operators';

// rxjs 5
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/of';
import 'rxjs/add/operator/map';
```

it looks like a problem for me if we import operator-by-operator

**Comment by trotyl** [comment]
Already tracked at #21572, RxJS v6 requires Webpack v4 support.

**Comment by fetis** [comment]
@trotyl  my question relates more to end applications, rather than angular code. Imagine you have an application with rxjs5 style imports, after new Angular version you'll have to do big refactoring and it's not just renaming. Are you going to provide some tool for this as part of ng-cli?

**Comment by trotyl** [comment]
@fetis That's not an Angular specific question. For RxJS support questions, it's better to be raised at their channels.

**Comment by fetis** [comment]
@trotyl  I think it's still Angular specific because that import style is dictated by ng-cli.

**Comment by trotyl** [comment]
@fetis Angular CLI doesn't forbid you changing `tslint.json`, actually everyone should change that first according to their needs before doing real works.

And there has always been updates on default `tslint.json`, the one in your project could already been outdated if created by old Angular CLI version.

**Comment by fetis** [comment]
@trotyl from Angular's team perspective, how you'd make this migration (rxjs5 -> rxjs6)? Manually? I assume you have individual imports for every operator.

**Comment by trotyl** [comment]
@fetis You'd ask Angular team then. From my knowledge, Angular v6 would still support RxJS v5.5, so there's no breaking change on Angular side, but if you'd like to upgrade RxJS version, just do it like any other RxJS project.

**Comment by sarahgreenwood** [comment]
I have included : import { Observable } from 'rxjs/Observable';
and import 'rxjs/add/operator/map';
but I still have the error for  .map((res : Response ) => res.json())
Am using Ionic --v 3

**Comment by AsiaMahmood** [comment]
@sarahgreenwood 
Me too :( 
Did you solve it?

**Comment by sarunint** [comment]
@DevJoseWeb please take a look at https://rxjs-dev.firebaseapp.com/guide/v6/migration

**Comment by jcroll** [comment]
@sarunint the `rxjs-5-to-6-migrate` command will change the rxjs imports in the linted ts files to import from the `rxjs` namespace like so:
```typescript
import { Observable, Subject, asapScheduler, pipe, of, from, interval, merge, fromEvent, SubscriptionLike, PartialObserver } from 'rxjs';
```

However this rule will fail the `operator-by-operator` test in tslint. This test is added to tslint in a new angular-cli project (I just tested creating a new project with angular-cli@6). Shouldn't the onus be on the angular cli team to create a tslint config that complies with the coding standards of RxJS 6?

**Comment by jcroll** [comment]
@sarunint my bad, it appears my angular-cli was outdated. This tslint being generated does appear to not contain the `import-blacklist` key

**Comment by leongaban** [comment]
Hi, I'm still having this problem

> Type 'Observable<{} | IProduct[]>' is not assignable to type 'Observable<IProduct[]>'

https://stackoverflow.com/questions/52156118/type-observable-iproduct-is-not-assignable-to-type-observableiproduc

And the `Rx.Observable.of` didn't work because of wasn't on `Observable`. I found the right syntax here to: http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html

**Comment by DevJoseWeb** [comment]
@sarunint tanks man !
