### ISSUE TITLE
No provider for HttpClient!

### ISSUE THREAD

**Issue by callawey** [angular/angular#20355]
After upgrading from angular 4.4 to 5.0 and after updating all HttpModule and Http to HttpClientModule i started to get this error. 

I also added HttpModule again to be sure its not due some dependency but it doesnt resolves the issue

in app.module, i have all correctly set
<pre><code>
import { HttpModule } from '@angular/http';
import { HttpClientModule, HttpClient } from '@angular/common/http';
.
.
.
@NgModule({
    imports: [
        BrowserModule,
        HttpClientModule,
        HttpModule,
        BrowserAnimationsModule,
        FormsModule,
        AppRoutingModule,
.
.
.
</code></pre>

I dont know from where this error is coming, or i have no clue how to get inner of it. I also have a warning (put it below too) maybe its related.

<pre><code>
Error: StaticInjectorError[HttpClient]: 
  StaticInjectorError[HttpClient]: 
    NullInjectorError: No provider for HttpClient!
    at _NullInjector.get (vendor.js?v=mekBM8IVBK72-MIZOVSTJizGi_TD_xK3uhPOCRlEHwg:5665)
    at resolveToken (vendor.js?v=mekBM8IVBK72-MIZOVSTJizGi_TD_xK3uhPOCRlEHwg:5953)
    at tryResolveToken (vendor.js?v=mekBM8IVBK72-MIZOVSTJizGi_TD_xK3uhPOCRlEHwg:5895)
    at StaticInjector.get (vendor.js?v=mekBM8IVBK72-MIZOVSTJizGi_TD_xK3uhPOCRlEHwg:5766)
    at resolveToken (vendor.js?v=mekBM8IVBK72-MIZOVSTJizGi_TD_xK3uhPOCRlEHwg:5953)
    at tryResolveToken (vendor.js?v=mekBM8IVBK72-MIZOVSTJizGi_TD_xK3uhPOCRlEHwg:5895)
    at StaticInjector.get (vendor.js?v=mekBM8IVBK72-MIZOVSTJizGi_TD_xK3uhPOCRlEHwg:5766)
    at resolveNgModuleDep (vendor.js?v=mekBM8IVBK72-MIZOVSTJizGi_TD_xK3uhPOCRlEHwg:15328)
    at _createClass (vendor.js?v=mekBM8IVBK72-MIZOVSTJizGi_TD_xK3uhPOCRlEHwg:15373)
    at _createProviderInstance$1 (vendor.js?v=mekBM8IVBK72-MIZOVSTJizGi_TD_xK3uhPOCRlEHwg:15339)
</code></pre>

Warning Message:
<pre><code>
./node_modules/@angular/Common/esm5/http.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* D:\XXX\node_modules\@angular\Common\esm5\http.js
    Used by 21 module(s), i. e.
    D:\XXX\node_modules\awesome-typescript-loader\dist\entry.js?silent=true!D:\XXX\node_modules\angular2-template-loader\index.js!D:\XXX\ClientApp\app\services\notification-endpoint.service.ts
* D:\XXX\node_modules\@angular\common\esm5\http.js
    Used by 1 module(s), i. e.
    D:\XXX\node_modules\awesome-typescript-loader\dist\entry.js?silent=true!D:\XXX\node_modules\angular2-template-loader\index.js!D:\XXX\ClientApp\app\app.module.ts
 @ ./node_modules/@angular/Common/esm5/http.js
 @ ./ClientApp/app/services/notification-endpoint.service.ts
 @ ./ClientApp/app/app.module.ts
 @ ./ClientApp/boot.browser.ts
 @ multi event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot.browser.ts
</code></pre>

## Current behavior
StaticInjectorError[HttpClient]: StaticInjectorError[HttpClient]: NullInjectorError: No provider for HttpClient!

## Environment

<pre><code>
Angular version: 5.0.0 and 5.0.1 (also 5.1 beta)

Browser:
- all

For Tooling issues:
- Node version: 8.5.0
- Platform:  windows
</code></pre>

**Comment by lazarljubenovic** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by RafiqueMohammed** [comment]
hey calleway! i am facing the same issue. I tried importing HttpClientModule but my app doesnt work saying "NullInjectorError: No provider for HttpClient!" Did you find any solution yet?

**Comment by callawey** [comment]
no, i didnt find any fix for it but what i did solved the problem.

I reverted back my project completely to angular4. Then i started to move to HttpClient from old Http one by one on my each module and service and be sure that after each move the project still works.

Doing so, i fully re-updated my project from ground after that, i removed old Http completely from the project and check to be sure the project still works. 

After everything succeded, i upgraded the project to angular5 along with other libraries to their betas or last versions and every thing worked like a charm.

**Comment by cdCarlos** [comment]
@callawey @RafiqueMohammed 
I think you should remove the old HttpModule import.

**Comment by mustaq7** [comment]
I've used HttpModule in app.module.ts after importing the httpmodule and it resolved my issue

**Comment by ChakrapaniKulkarni** [comment]
If you are using angular v5 version, import HttpClientModule in your app.module.ts after HttpModule.

`
import { HttpModule } from '@angular/http';
import { HttpClientModule } from '@angular/common/http';
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    MomentModule,
    HttpClientModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }`

**Comment by godenji** [comment]
> this fixed the issue for me

@ChakrapaniKulkarni  for now it does, but will be "unfixed" for you when deprecated *HttpModule* is removed.

Have no idea why *HttpClientModule* isn't sufficient, presumably if it replaces *HttpModule* is should be.

**Comment by mhbt** [comment]
@ChakrapaniKulkarni has the right solution while using `HttpClient` we have to import `HttpClientModule `from `@angular/common/http`

**Comment by sshreya0808** [comment]
import HttpClientModule in App Module and list that in imports.

**Comment by ahmadalfy** [comment]
@ChakrapaniKulkarni your solution works, it should be imported in the same order as you mentioned otherwise you will end up getting errors. That's really weird.

**Comment by basantkumarpogeyan** [comment]
Please add 
import {HttpClientModule} from '@angular/common/http'; to app.module.ts
imports: [
    BrowserModule,
    FormsModule,
    **HttpClientModule**,
  ],

**Comment by lazarljubenovic** [comment]
Alright guys, the solution was posted and is already highly voted. The issue is closed as it's a support request. This is a place for bug reports and issue requests. Hence no need to keep up this discussion.

**Comment by snow28** [comment]
I hade similar issue, it works for me.
1)In app.module.ts you have to import HttpClientModule:
`-import { HttpClientModule } from '@angular/common/http';`

2)and than add it to your @NgModule imports in the same file :

`imports: [
    HttpClientModule
  ]`

**Comment by worldsayshi** [comment]
@lazarljubenovic I'm not sure this is just about support. I have followed the support instructions here and I get different results depending on machine. It works fine on one machine when I installed everything on a new machine I get errors. It *seems* that there is something quirky going on with some version of Angular or some dependency. Also, there are several remarks that order makes a difference depending on the order.

**Comment by shreyacorm** [comment]
AppComponent.html:1 ERROR Error: StaticInjectorError(AppModule)[UserService -> Http]: 
  StaticInjectorError(Platform: core)[UserService -> Http]: 
    NullInjectorError: No provider for Http!
    at _NullInjector.get (core.js:1002)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.get (core.js:1110)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.get (core.js:1110)
    at resolveNgModuleDep (core.js:10854)
    at _createClass (core.js:10891)
    at _createProviderInstance$1 (core.js:10865)



How to resolve this ? Any suggestions Please

**Comment by DebaratiMajumder** [comment]
Hi Callawey,

Have you added the code snippet below in @NgModule imports section of app.module.ts?

HttpClientInMemoryWebApiModule.forRoot(
  InmemorydataserviceService, { dataEncapsulation: false }
)

**Comment by JoyPGit** [comment]
we need to add both the http module and the httpclient module.

**Comment by FanFanFantastic** [comment]
Why was there so many downvotes for the guy above me? Don't we need to add 2 modules now?

BTW I got so used to using just one module, you guys are changing 2 much , I come from Ionic background and now I have re-familiar myself with angular 6 with all those changes

**Comment by github-mayur** [comment]
When its not working on above mentioned way, use this way.

1) Just do the same thing in @ChakrapaniKulkarni answer.
2) Then find out in which service you are getting **HttpClient** error.
3) Add `import { HttpClientModule } from '@angular/common/http';` in that file.
4) Find in the same file, you will have
```
TestBed.configureTestingModule({
   providers: [ SomeService ]
});
```
code somewhere.
5) Now add `imports: [ HttpClientModule ],` option above providers.
6) This needs to be add only in that single file and it will not throw error for other components either.

It should work now!

**Comment by selvanchinnathambi** [comment]
Upgrading from angular 4 to 6.0 ,  after updating all HttpModule and Http to HttpClientModule i started to get this error: Can someone help me on this?

zone.js:388 Error: (SystemJS) Unexpected value 'undefined' imported by the module 'AppModule'
	Error: Unexpected value 'undefined' imported by the module 'AppModule'
	    at X (https://nikeelite-webapp-qa.nikecloud.net/libs/@angular/compiler/bundles/compiler.umd.min.js:20:1102)
	    at eval (https://nikeelite-webapp-qa.nikecloud.net/libs/@angular/compiler/bundles/compiler.umd.min.js:248:4599)
	    at Array.forEach (<anonymous>)
	    at t.getNgModuleMetadata (https://nikeelite-webapp-qa.nikecloud.net/libs/@angular/compiler/bundles/compiler.umd.min.js:248:4002)
	    at e._loadModules (https://nikeelite-webapp-qa.nikecloud.net/libs/@angular/compiler/bundles/compiler.umd.min.js:465:14712)
	    at e._compileModuleAndComponents (https://nikeelite-webapp-qa.nikecloud.net/libs/@angular/compiler/bundles/compiler.umd.min.js:465:14329)
	    at e.compileModuleAsync (https://nikeelite-webapp-qa.nikecloud.net/libs/@angular/compiler/bundles/compiler.umd.min.js:465:13256)
	    at e.compileModuleAsync (https://nikeelite-webapp-qa.nikecloud.net/libs/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.min.js:20:1944)
	    at e.bootstrapModule (https://nikeelite-webapp-qa.nikecloud.net/libs/@angular/core/bundles/core.umd.min.js:204:2079)
	    at execute (https://nikeelite-webapp-qa.nikecloud.net/app/application.js:32051:65)
	Error loading https://nikeelite-webapp-qa.nikecloud.net/bootstrap

**Comment by lazarljubenovic** [comment]
@selvanchinnathambi It's probably a circular dep. Please do not use random issues to file support requests. Use StackOverflow to ask questions.

**Comment by mlc-mlapis** [comment]
@selvanchinnatham ... you should be able to reproduce that case an online demo using Plunker if it is a real issue, but I think that it's not because we use `HttpClientModule` with SystemJS loade without any problem on Angular 6.

**Comment by wleite** [comment]
To fix this on .spec.ts file

`import { TestBed, inject } from '@angular/core/testing';

import { HttpClientModule }   from '@angular/common/http';

import { ApiService } from './api.service';

describe('ApiService', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [ApiService],
      imports: [ HttpClientModule ]
    });
  });

  it('should be created', inject([ApiService], (service: ApiService) => {
    expect(service).toBeTruthy();
  }));
});
`

**Comment by fdc80** [comment]
@wleite solved for me, thx

**Comment by CognitiveClouds-Prasad** [comment]
> If you are using angular v5 version, import HttpClientModule in your app.module.ts after HttpModule.
> 
> ```
> import { HttpModule } from '@angular/http';
> import { HttpClientModule } from '@angular/common/http';
> import { BrowserModule } from '@angular/platform-browser';
> import { NgModule } from '@angular/core';
> import { FormsModule } from '@angular/forms';
> import { AppComponent } from './app.component';
> 
> @NgModule({
>   declarations: [
>     AppComponent
>   ],
>   imports: [
>     BrowserModule,
>     FormsModule,
>     HttpModule,
>     MomentModule,
>     HttpClientModule
>   ],
>   providers: [],
>   bootstrap: [AppComponent]
> })
> export class AppModule { }
> ```
> This fixed the issue for me

This worked for me too!
