### ISSUE TITLE
problems with VSC v1.18's new autoimport feature

### ISSUE THREAD

**Issue by fxck** [angular/angular#20353]
https://code.visualstudio.com/updates/v1_18#_auto-import-for-javascript-and-typescript

I'm not sure whether to take this to their repo or this, but I think "fault" is perhaps on both sides.

So what happens when you try writing say `trigger` without having it imported previously.

![image](https://user-images.githubusercontent.com/1303561/32688002-b3e6d06c-c6c8-11e7-89ed-b8343e1c2f17.png)

VSC suggest 6 possible imports and doesn't really show from where they are from unless you click on the blue info icon. Now when you click the blue info icon, you can kind see where it would import from, it's one of these:

- `@angular/animations/src/animation_metadata`
- `@angular/core/src/animation/dsl`
- `@angular/core`
- `@angular/core/core`

..none of them is actually from `@angular/animations`.

So the question is, could you work along with vscode team to A) hide depracated exports and B) possibly completely disable, or least least prioritise suggestion of imports from places such as animation_metadata, src, etc?

Note that this doesn't happen exclusive to animations, when you start writing `@Component` the first suggestion imports it from `@angular/core/src/metadata/directives`.

**Comment by jasonaden** [comment]
@fxck Thanks for the issue. I suggest filing this on the VSCode repo. But I will also forward this to a member of our team who can re-open if this is something his team should handle.
