### ISSUE TITLE
5.0.1: ngc throws "Could not resolve type Document" when "strictMetadataEmit" = true

### ISSUE THREAD

**Issue by wilsoncook** [angular/angular#20351]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Ran `./node_modules/.bin/ngc -p tsconfig-aot.json` when `strictMetadataEmit: true` throws:
```shell
Error: /Users/wilson/Webroot/test/testangular5/src/app/app.component.ts:4:1: Error encountered in metadata generated for exported symbol 'AppComponent':
 /Users/wilson/Webroot/test/testangular5/src/app/app.component.ts:12:46: Metadata collected contains an error that will be reported at runtime: Could not resolve type Document.
  {"__symbolic":"error","message":"Could not resolve type","line":11,"character":45,"context":{"typeName":"Document"}}, resolving symbol AppModule in /Users/wilson/Webroot/test/testangular5/src/app/app.module.ts, resolving symbol AppModule in /Users/wilson/Webroot/test/testangular5/src/app/app.module.ts
```
Change `angularCompilerOptions.strictMetadataEmit` to `false` tobe OK

## Expected behavior

Succeed with `strictMetadataEmit` via `ngc`

## Minimal reproduction of the problem with instructions

It seems any ambient type would cause this error when i upgraded to angular 5. So i create a `@angular/cli` project as below, and use a custom `tsconfig-aot.json` file to run `ngc`.

My `tsconfig-aot.json`:
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": ["./node_modules/@types/"]
  },

  "files": ["src/app/app.module.ts", "src/main.ts"],

  "angularCompilerOptions": {
    "strictMetadataEmit": true
  }
}
``` 
Flashpoint codes:
```js
import { Component, Inject } from '@angular/core';
import { DOCUMENT } from '@angular/platform-browser';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';

  constructor(@Inject(DOCUMENT) private doc: Document) {} <------ HERE
}
```
Compiling command:
```shell
./node_modules/.bin/ngc -p tsconfig-aot.json
```

## Environment

<pre><code>
Angular: 5.0.1

For Tooling issues:
- Node version: 7.9.0  
- Platform: Mac 

Others:

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.4.2
webpack: 3.8.1
</code></pre>

**Comment by chuckjaz** [comment]
`"strictMetadataEmit"` is only intended to be used when publishing libraries, not for use in applications as it is overly pessimistic as you have demonstrated. It is intended to catch errors in metadata that normally would only be produced when building an application. If your are building an application you should never turn `"strictMetadataEmit"`.

**Comment by wilsoncook** [comment]
@chuckjaz Actually, we used `strictMetadataEmit ` when publishing our libraries and lead to the same error while compile with `ngc` (not only the `Document` but also other as typescript's generic type), so i did this demonstration.
Here `tsconfig-build.json` for our library:
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./publish/src",
    "baseUrl": "./",
    "declaration": true,
    "importHelpers": true,
    "module": "es2015",
    "sourceMap": false,
    "target": "es2015",
    "types": [
      "node"
    ]
  },
  "files": [
    "./src/__gen_components/ng-zorro-antd.module.ts"
  ],
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "strictMetadataEmit": true,
    "flatModuleOutFile": "index.js",
    "flatModuleId": "ng-zorro-antd",
    "skipTemplateCodegen": true
  }
}
```
The building script:
```shell
readonly currentDir=$(cd $(dirname $0); pwd)
cd ${currentDir}
rm -rf publish
cp -r src/components src/__gen_components
node ./less.convert.js

echo 'Generating entry file using Angular compiler'
$(npm bin)/ngc -p tsconfig-build.json #<--------------------------- ERROR HERE
rm -rf src/__gen_components

echo 'Bundling to es module'
export ROLLUP_FORMAT=es
$(npm bin)/rollup -c rollup.config.js
rm -rf publish/src/*.js
rm -rf publish/src/**/*.js
sed -e "s/from '.\//from '.\/src\//g" publish/src/index.d.ts > publish/index.d.ts
sed -e "s/\":\".\//\":\".\/src\//g" publish/src/index.metadata.json > publish/index.metadata.json
rm publish/src/index.d.ts publish/src/index.metadata.json

echo 'Transpiling es module to es5'
$(npm bin)/tsc --allowJs --importHelpers --target es5 --module es2015 --outDir publish/esm5 publish/esm15/index.js

echo 'Bundling to umd module'
export ROLLUP_FORMAT=umd
$(npm bin)/rollup -c rollup.config.js

echo 'Minifying umd module'
$(npm bin)/uglifyjs publish/bundles/ng-zorro-antd.umd.js --output publish/bundles/ng-zorro-antd.umd.min.js

echo 'Copying package.json'
cp package.json publish/package.json
```

**Comment by wilsoncook** [comment]
Change `@Inject(DOCUMENT) private doc: Document` to `@Inject(DOCUMENT) private doc: any` to resolve this error. BUT why shouldn't we use `Document` as a ambient type for DI, it should not be like this.

**Comment by chuckjaz** [comment]
`"strictMetadataEmit": true` test the compile to report whenever a `"__symbol": "error"` symbol is emitted  to `.metadata.json` in a position that is likely to be seen by the compiler. It doesn't do any semantic analysis to determine if there are other conditions that would cause it to be ignored. For example,  adding a comment such as,

```
/** @dynamic */
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';

  constructor(@Inject(DOCUMENT) private doc: Document) {} 
}
```

Is sufficient to suppress the error. This tells `"strictMetadataEmit"` to ignore this error as it is expected and will not cause a problem at compile time.

As for supporting ambient symbols for DI injection, please report that as a separate issue.

**Comment by wilsoncook** [comment]
Okay, willing to report as a separate issue

**Comment by johncrim** [comment]
Thanks for the info here. A related StackOverflow post: https://stackoverflow.com/questions/49513359/could-not-resolve-type-document-in-angular5/53715642#53715642

The workaround that I use is:

```
@Injectable({
  providedIn: 'root'
})
class MyService {

  constructor(@Inject(DOCUMENT) document?: any) {
    this._document = document as Document;
  }

  private _document?: Document;

...

```
This uses `any` for the injection signature (making angular happy), but gives you Typescript types within the class.
