### ISSUE TITLE
ServiceWorkerModule.register is not Universal friendly.

### ISSUE THREAD

**Issue by stanvanheumen** [angular/angular#20360]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When having setup the ServiceWorkerModule in your AppModule it crashes when the server is trying to render the application because of the `navigator` object not being defined in the server.

## Expected behavior

No crash.

## Minimal reproduction of the problem with instructions

`ReferenceError: navigator is not defined
    at Array.initializer (C:\Users\Stan\Documents\bravobit-web\functions\node_modules\@angular\service-worker\bundles\service-worker.umd.js:373:34)
    at ApplicationInitStatus.runInitializers (C:\Users\Stan\Documents\bravobit-web\functions\node_modules\@angular\core\bundles\core.umd.js:3490:67)
    at C:\Users\Stan\Documents\bravobit-web\functions\node_modules\@angular\core\bundles\core.umd.js:5418:28
    at _callAndReportToErrorHandler (C:\Users\Stan\Documents\bravobit-web\functions\node_modules\@angular\core\bundles\core.umd.js:5597:39)
    at C:\Users\Stan\Documents\bravobit-web\functions\node_modules\@angular\core\bundles\core.umd.js:5416:20
    at ZoneDelegate.invoke (C:\Users\Stan\Documents\bravobit-web\functions\node_modules\zone.js\dist\zone-node.js:392:26)
    at Object.onInvoke (C:\Users\Stan\Documents\bravobit-web\functions\node_modules\@angular\core\bundles\core.umd.js:4668:33)
    at ZoneDelegate.invoke (C:\Users\Stan\Documents\bravobit-web\functions\node_modules\zone.js\dist\zone-node.js:391:32)
    at Zone.run (C:\Users\Stan\Documents\bravobit-web\functions\node_modules\zone.js\dist\zone-node.js:142:43)
    at NgZone.run (C:\Users\Stan\Documents\bravobit-web\functions\node_modules\@angular\core\bundles\core.umd.js:4485:69)
`

## What is the motivation / use case for changing the behavior?

The server should not crash because of a undefined property.

## Environment

<pre><code>
Angular version: 5.0.1

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 8.8.1 
- Platform: Windows

Others:

</code></pre>

**Comment by CaerusKaru** [comment]
cc @alxhub 

A temporary workaround is to have a separate `AppBrowserModule` and `AppServerModule` with a common `AppModule`. Then you can load the `ServiceWorkerModule` into the `AppBrowserModule` and preserve your builds.

**Comment by Toxicable** [comment]
I don't think i'd call that a "work-around" since the service worker would be next to useless on the server anyway.

**Comment by CaerusKaru** [comment]
@Toxicable I think the point here is that we should be able to include `ServiceWorkerModule` in the regular `AppModule`, but since the `AppServerModule` loads that module, it throws an error on compilation.

**Comment by Toxicable** [comment]
Whops sorry, you're right I got it around the wrong way :P
Should just be a platform check here https://github.com/angular/angular/blob/17142a778a07fa26e16a274298b33a2a67ed2d31/packages/service-worker/src/module.ts#L26

**Comment by CaerusKaru** [comment]
Or just adding `if (!(navigator && ('serviceWorker' in navigator))) {`

**Comment by Toxicable** [comment]
Using a proper platform check such as `isPlatformBrowser` just incase some 3rd party decides it wants to implement the api itself, in such a situation we cannot predict the behavior

**Comment by maciejtreder** [comment]
As a workaround, you can also provide "`MockModule`" for the server build.

Check out my solution here:
https://github.com/maciejtreder/angular-universal-pwa

Here is module used for server-side rendering:
https://github.com/maciejtreder/angular-universal-pwa/pull/65/files#diff-6bfb9b4181ded81b72a3656654e0f183

And here faked module with services:
https://github.com/maciejtreder/angular-universal-pwa/pull/65/files#diff-9f8098d50dad87159602d9f8f1682d5d
https://github.com/maciejtreder/angular-universal-pwa/pull/65/files#diff-c6dbc4965270cce2acf71a57db7ee05d

**Comment by patrickmichalina** [comment]
@maciejtreder I cannot get `ServiceWorkerModule.register('./ngsw-worker.js')` to ever load the file... Not sure what I am missing. Driving me crazy

**Comment by maciejtreder** [comment]
@patrickmichalina You are using boilerplate created by me, or some other repository? Did you make sure that your `ngsw-worker.js` file is present in the output directory?

**Comment by CaerusKaru** [comment]
@cyrilletuzi @Toxicable had concerns about integration testing and passed the buck to @alxhub to implement. If you use either mine or @maciejtreder's workaround, you should be able to take advantage of the new AppShell feature without issue until this gets patched.

**Comment by maciejtreder** [comment]
@CaerusKaru Your solution have one big pitfall. If you are using any of services provided by the ServiceWorkerModule in your app (via `Dependency Injection`), the server-side rendering won't work. It will break, because of lack of provider for services (`SwPush` or `SwUpdate`).

**Comment by CaerusKaru** [comment]
@maciejtreder There is an easy, one-line solution for that. You can just add an Optional decorator to the injection and check if it's null before using.

**Comment by maciejtreder** [comment]
Still you need to check if service is initialized before you will use it ;). So your code looks like (for example):

```
public gimmePushes: Observable<any> {
    if (this.swPush) {
        return this.swPush.messages;
    } else {
        Observable.of(null);
    }
}
```

**Comment by CaerusKaru** [comment]
Yep, that's where I got the "and check if it's null before using". Thanks for providing the example for reference.

**Comment by maciejtreder** [comment]
@CaerusKaru I got workaround for this, too :)

https://github.com/maciejtreder/angular-universal-pwa/blob/master/src/app/services/notification.service.ts 

```
        try {
            this.swPush = injector.get(SwPush);
            this.swPush.messages.subscribe((message) => console.log(message));
        } catch (err) {
            // workaround for https://github.com/angular/angular/issues/20407
        }
```

and:
https://github.com/maciejtreder/angular-universal-pwa/blob/master/src/app/app.component.ts 



```
        try {
            this.swUpdate.activated.subscribe(() => {
            // some logic here
            });
        } catch (err) {
            // workaround for https://github.com/angular/angular/issues/20519
        }
```

Feel invited to use 👍

**Comment by maciejtreder** [comment]
Hmm.. Could you provide some example of method which won't work on server side?

In my boiler plate (mentioned above). I did not run into such issues. 

I had only problems with Safari. But for this I got workaround as well (you can read more here: https://github.com/angular/angular/issues/20407 and here: https://github.com/angular/angular/issues/20519 )

**Comment by CaerusKaru** [comment]
@maciejtreder try-catch blocks are typically [discouraged](https://github.com/angular/material2/blob/master/CODING_STANDARDS.md#try-catch) in Angular.

Also, if you try using ServiceWorker methods on the server, your server should output error logs when the methods are invoked. The errors would not show up in the browser because it's working as intended.

**Comment by patrickmichalina** [comment]
I learned last night that ServiceWorkerModule.register('./ngsw-worker.js') does not make an XHR for the file. In most examples I've seen online, loading the file is hidden by the CLI. The CLI injects it into index.html. @maciejtreder your starter has been a help, but I am not using the CLI so I have to load that file manually in my build tooling. Seems to work now!

**Comment by Gorniv** [comment]
I added service-worker to universal https://github.com/Angular-RU/angular-universal-starter/commit/a67bfe8dcf942daa07c385c8c359c110bc483c45  , but it broke the server side(only index app in the source code page)

**Comment by cyrilletuzi** [comment]
Too bad it didn't make into 5.0.5 with all the others SW fixes...

**Comment by ChristianWeyer** [comment]
AFAICT, it also fails here:
https://github.com/angular/angular/commit/80eeba272a4b81203b87091988c1a893fc6f0262#diff-d3f0f5f34efd2b679fc85854b84a281aR60

**Comment by alejonext** [comment]
Is exist a error in
https://github.com/angular/angular/blob/master/packages/service-worker/src/module.ts#L60

```
return new NgswCommChannel(
opts.enabled !== false && navigator && ( 'serviceWorker' in navigator ) ? navigator.serviceWorker : undefined, platformId);
```
