### ISSUE TITLE
[FormBuilder#control] - Change the signature method

### ISSUE THREAD

**Issue by rafaelss95** [angular/angular#20368]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently the signature of [**`FormBuilder#control`**](https://angular.io/api/forms/FormBuilder#control) is:

`control(formState: Object, validator?: ValidatorFn|ValidatorFn[]|null, asyncValidator?: AsyncValidatorFn|AsyncValidatorFn[]|null): FormControl`

So, if you have the following line:

~~this.formBuilder.control('angular');~~
```
this.formBuilder.control(null);
```

or

```
this.formBuilder.control(undefined);
```

... with `strict` option enabled in `tsconfig.json`, it doesn't compile. See the error:

> error TS2345: Argument of type  `null` | `undefined` is not assignable to parameter of type 'Object'.

In fact, I don't see a good reason to use `Object` instead of `any` as in [**`FormControl#constructor`**](https://angular.io/api/forms/FormControl#constructor).

Thinking more about it... it seems like a bug, since the `FormBuilder#control` acts like an wrapper for `FormControl#constructor`, so shouldn't it have exact the same signature of it?

## Expected behavior
I'd expect my app to compile well with `strict` option enabled.

## Environment
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.5.0
Node: 8.1.1
OS: linux x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.0
@angular/material-moment-adapter: 5.0.0-rc0
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.4.2
webpack: 3.8.1
```

**Comment by benbraou** [comment]
I do not reproduce the compilation error with/without strict option.
I think this is expected because:
1. formState is declared of type **O**bject. (so we can assing value to it, but invoke only the methods defined in the Object interface )
1. If it were declared of type **o**bject (the type used to describe non-primitive types), then passing a string(primitive value in TypeScript) would have resulted in the error mentioned above
@rafaelss95 am I missing something here ? A simple repo otherwise that I can clone to reproduce would be great.

Anyway, I agree that to be coherent with FormControl constructor, FormBuilder#control method should have the formState parameter of type any instead of Object.

I would like to provide a pull request for that

**Comment by rafaelss95** [comment]
@benbraou You're totally right. The error that I mentioned happens when you try to initialize a `control` with `null` or `undefined` (of course with `--strict` option enabled), e.g.:

this.formBuilder.control(null); // Argument of type 'null' is not assignable to parameter of type 'Object'.
this.formBuilder.control(undefined); // Argument of type 'null' is not assignable to parameter of type 'Object'.

**Comment by fredrik-lundin** [comment]
Hi, out of curiosity - how would one go about writing a test for such thing? I mean testing that something works specifically with the `--strict` option enabled

**Comment by benbraou** [comment]
@rafaelss95 thanks for the explanation. I have submitted a PR accordingly
@fredrik-lundin I see that Angular tsconfig file uses  strictNullChecks. The tests I have added won't work unless FormBuilder#control accepts a parameter of any type
