### ISSUE TITLE
Custom validator error with FromGroup

### ISSUE THREAD

**Issue by AhmedHadjTaieb** [angular/angular#20362]
## The problem when I used custom validator with second FormGroup 
I verified my familiar with FormBuilder, I used Custom validator to verify my confirm password, but when I would access to password value I have a problem with the FormGroup.
 Code of component:
<img width="999" alt="capture d ecran 2017-11-11 a 20 54 20" src="https://user-images.githubusercontent.com/22799068/32693105-21ecc6a0-c725-11e7-83b5-29c365b911a5.png">

Code of html:
<img width="701" alt="capture d ecran 2017-11-11 a 20 54 43" src="https://user-images.githubusercontent.com/22799068/32693106-2b1fd4c4-c725-11e7-9fb0-1939203c81b0.png">

Code of Custom Validator:
<img width="683" alt="capture d ecran 2017-11-11 a 20 54 55" src="https://user-images.githubusercontent.com/22799068/32693108-374d4ee8-c725-11e7-9299-4d1f2b0ebdd8.png">

The problem :
<img width="466" alt="capture d ecran 2017-11-11 a 20 55 11" src="https://user-images.githubusercontent.com/22799068/32693112-4b8cf1c4-c725-11e7-847d-3f54dc8fc3fa.png">

## Environment
Angular version: 4.4.6
Angular CLI: 1.5

Browser:
- [x] Chrome (desktop) Version 62.0.3202.89

For Tooling issues:
- Node version: v8.7.0
- Platform: MacOs Heigh Sierra

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by AhmedHadjTaieb** [comment]
The problem resolved, now you can close this issue my solution is:
Component :
`import {Component, OnInit} from '@angular/core';
import {FormBuilder, Validators, FormGroup, FormControl, AbstractControl} from '@angular/forms';
import {confirmPasswordValidator} from './strong-password.validator';


@Component({
  selector: 'connexion-app',
  templateUrl: './connexion.component.html'
})
export class ConnexionComponentComponent implements OnInit {
  form: FormGroup;
  
  
  constructor(protected fb: FormBuilder) {
    this.form = this.fb.group({
      name: this.fb.group({
        firstname: ['', Validators.compose([Validators.required, Validators.minLength(3), Validators.maxLength(25)])],
        lastname: ['', Validators.compose([Validators.required, Validators.minLength(3), Validators.maxLength(25)])]
      }),
      email: ['', Validators.pattern('^[a-z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$')],
      verification: this.fb.group({
        password: ['', Validators.compose([Validators.required, Validators.minLength(8)])],
        passwordConfirm: ['', Validators.compose([Validators.required, Validators.minLength(8)])]
      }, {validator: confirmPasswordValidator()}),
    });
  }

  ngOnInit(): void {
  }
  
  
  save(x: any) {
    console.log(x);
  }
  
}
`
Validator:
`import {AbstractControl, ValidatorFn} from '@angular/forms';

export function confirmPasswordValidator(): ValidatorFn {
  return (control: AbstractControl) => {
    return (control.get('password').value === control.get('passwordConfirm').value) ? null : {'strongPasswordError': true};
  };
}`

**Comment by Toxicable** [comment]
@AhmedHadjTaieb You can also close this issue
