### ISSUE TITLE
feat docs: replace old plnkr examples with aio examples 

### ISSUE THREAD

**Issue by Toxicable** [angular/angular#20366]
There are some very old (alpha) examples of some API's sitting around in the API Docs of some API's such as 
https://github.com/angular/angular/blob/master/packages/core/src/change_detection/change_detector_ref.ts#L18
doing a search for `### Example ([` shows most of them: about 29
It would be good to see these replaced with the aio @example ones

**Comment by jenniferfell** [comment]
@brandonroberts Hi. When you get a change, would you take a look? I know we've updated a lot of the examples, especially in the move to stackblitz. Please assist with triage on this. Close? If not, please add a note about the current state. Are examples broken? Outdated (use deprecated features or don't use current best practices)? Or just incomplete (we have stackblitz but need downloadable examples)? Thanks!

**Comment by brandonroberts** [comment]
This issue refers to the examples in the API documentation. Some of the examples are broken and some are outdated. I'm closing this one in favor of #21525.
