### ISSUE TITLE
 Compiler not allows to import packages, whose name contains dot (e.g. "angular.com")

### ISSUE THREAD

**Issue by mmlleevvyy** [angular/angular#20363]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In compiler_host.ts, there is a const NODE_MODULES_PACKAGE_NAME which is a regex, that should validate if a package is from node_modules... but this regex is invalid, as it do not match packages, whose name contains dot (".", eg. "angular.com"). Because of that, when one library requires other library (with name containing dot), compiler throws error "Trying to import a source file from a node_modules package".

Link to const:
https://github.com/angular/angular/blob/24cf8b326918e0694dfcdcf48635b5325060827a/packages/compiler-cli/src/transformers/compiler_host.ts#L20

## Expected behavior
Node package name may contain dots, so it should be allowed to import that kind of packages and angular compiler should not make any problems ;-).

## Environment

<pre><code>
Angular version: 5.0.1

 
For Tooling issues:
- Node version: 8.1.4 
- Platform: Mac

**Comment by mmlleevvyy** [comment]
Regex for matching package name:
```node_modules\/((\w|-|\.)+|(@(\w|-|\.)+\/(\w|-|\.)+))```

**Comment by mmlleevvyy** [comment]
@tbosch Can you look at it please?

**Comment by choucry13** [comment]
+1 please :-)

**Comment by pjetja** [comment]
Can I kindly ask for timeline for this to be fixed?

**Comment by mmlleevvyy** [comment]
Yuppiii!!! Thanks @mhevery !!!!
