### ISSUE TITLE
animation skips straight to final state on production build (when using booleans for state)

### ISSUE THREAD

**Issue by fxck** [angular/angular#20374]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

It works fine on stackblitz https://stackblitz.com/edit/burger?file=app%2Fburger%2Fburger.component.ts as well as with `ng serve --aot`, but doesn't work when built with `ng build --prod` http://burger.fxck.cz/

## Minimal reproduction of the problem with instructions

works (dev): https://stackblitz.com/edit/burger?file=app%2Fburger%2Fburger.component.ts
doesn't (prod): http://burger.fxck.cz

## Environment

<pre><code>
Angular version: 5.0.1

Browser:
All
 
For Tooling issues:
- Node version: all   
- Platform:   all

Others:

</code></pre>

cc @matsko

**Comment by fxck** [comment]
@matsko I managed to pin it down I think.

The problem is certainly not with me using a function to return the trigger, nor with params being passed down by the function. In fact this simple animation:

```
  animations: [
    trigger('line', [
      state('true', style({
        width: '40px'
      })),
      state('false', style({
        width: '20px'
      })),
      transition('true <=> false', [
        animate('500ms')
      ])
    ])
  ]
```

is not going to work either, but this will 

```
  animations: [
    trigger('line', [
      state('opened', style({
        width: '40px'
      })),
      state('closed', style({
        width: '20px'
      })),
      transition('opened <=> closed', [
        animate('500ms')
      ])
    ])
  ]
```

so the problem is obviously with using boolean, but curiously ONLY in production build, so something is perhaps being removed that shouldn't be.

**Comment by matsko** [comment]
Looking into it... Thank you @fxck.

**Comment by matsko** [comment]
@fxck just letting you know that the issue was detected and #20725 fixes it.

**Comment by matsko** [comment]
Thank you for making this issue easy to debug.
