### ISSUE TITLE
Testing Documentation and Tutorial Enhancements

### ISSUE THREAD

**Issue by Soobrakay** [angular/angular#20373]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The tutorial application does not have any working tests in the live demo, [downloadable source][2], or written guide. The [Fundamentals/Testing][1] section starts over from a new application built from the quickstart project instead of using the angular CLI. All of this increases friction when learning Angular 2 from scratch with testing in mind, and appears to be contrary to to the [Features][3] page that specifically calls out testing.

## Expected behavior

Minimum: downloadable versions of the tutorial include working tests so those who have completed the tutorial can more easily see how the application they just wrote would be tested.

Preferable: Include testing in the tutorial, or redo Fundamentals/Testing to use the tutorial application as the jumping point to backfill the tests not written during the tutorial.

## Minimal reproduction of the problem with instructions

* Code-along with the tutorial or download a source bundle. 
* Run `npm test` at any point after making the first edit to generated project source.

## What is the motivation / use case for changing the behavior?

Testing is important. It's listed as a feature of Angular. Developers new to Angular will hit the tutorial as a starting point. The friction between writing the initial app and switching to testing in Angular is high because of lack of a natural cutover. Either of the suggested expected behaviors will reduce friction when trying to learn Angular testing. It will also provide more cohesive documentation instead of introducing a new dummy app to learn to test in the Fundamentals/Testing section.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.4.0
- Platform:  Windows

Others:

</code></pre>

**EDIT**: included links to the pages and source download I referenced.

[1]: https://angular.io/guide/testing
[2]: https://angular.io/generated/zips/toh-pt6/toh-pt6.zip
[3]: https://angular.io/features

**Comment by gkalpak** [comment]
I am a little confused 😕

The tutorial _is_ based on CLI and while there is no dedicated section on testing, the downloadable bundle has both e2e tests and all the necessary scaffolding for unit tests.

And the `Testing` guide claims to be based on a project similar to the _Tour Of Heroes_ tutorial (although I am not if it is true - @Foxandxss would probably know more).

**Comment by Foxandxss** [comment]
The testing chapter is not updated yet. @wardbell will update it this week.

**Comment by Soobrakay** [comment]
@gkalpak Tutorial e2e tests fail, the unit tests are unmodified scaffolds with no useful content.

The package.json is also missing a dev-dependency in the source bundles for the istanbul coverage reporter.

* Download source bundle referenced above or from the tutorial download links
* `npm install`
* `npm test` - fails because of missing coverage reporter
* `npm install karma-coverage-istanbul-reporter --save-dev`
* `npm test` - runs but the e2e tests all fail with `NullInjector` or Template parse errors about `routerLink`.

As mentioned in the motivation section, I think this will reduce friction for those just learning Angular with a desire to produce tested code. The testing section works and teaches testing, but it does increase friction since it starts from a new app with a different install method than the tutorial.

**Comment by Foxandxss** [comment]
Don't worry. We are working on it and it will be CLI with the correct dependencies. (And all tests working of course)

**Comment by Vaelor** [comment]
To add to this, the 'All specs that test the sample application' 
(https://angular.io/generated/live-examples/testing/app-specs.eplnkr.html)
also needs to have a `tsconfig.spec.json` inside `src/`.
Running `npm test` results in:
`Error: ENOENT: no such file or directory, stat '/home/user/projects/app-specs.testing/src/tsconfig.spec.json'`
After fixing that, the root `tsconfig.json` is missing. Had to add that too.

Also, none of the example plunker tests seem to work (guess the same reason)

**Comment by jenniferfell** [comment]
docarea=testing
docarea=tutorial

**Comment by chembu** [comment]
Need engineering input.
