### ISSUE TITLE
Issue with rollup and NgProbeToken

### ISSUE THREAD

**Issue by iwhp** [angular/angular#20378]
## I'm submitting a...
<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
</code></pre>

## Current behavior
When I run rollup, i get the following message:
``
dist\aot\app\app.module.ngfactory.js (134:20) 'NgProbeToken' is not exported by 'node_modules\@angular\platform-browser\esm5\platform-browser.js'
``
## Expected behavior
Just compile without error

## Minimal reproduction of the problem with instructions
na

## What is the motivation / use case for changing the behavior?
Upgrade to angular 5

## Environment

<pre><code>
- angular version: 5.0.1
- node version: 8.6.0
- platform:  Windows
- rollup: 0.51.5
- rollup-plugin-commonjs: 8.2.6
- rollup-plugin-node-resolve: 3.0.0
- rollup-plugin-uglify: 2.0.1
</code></pre>

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/blob/master/CHANGELOG.md

>platform-browser: NgProbeToken has been removed from @angular/platform-browser as it was deprecated since v4. Import it from @angular/core instead. (#18760) (d7f42bf)

**Comment by iwhp** [comment]
thankx ericmartinezr!
I am not using NgProbeToken in my code, but I also cannot figure out, what external module is using it.
I just get it when running rollup, I am not getting it when I compile with tsc.

**Comment by ericmartinezr** [comment]
Can you provide a reproduction? I think in your case a a repo would be fine. This sounds like it's a 3rd party lib causing the issue, are you using any?

**Comment by iwhp** [comment]
This is quite a big and internal solution so it would take quite an effort to produce a repo. I have already started to analyze it, but I cannot figure out, when one would use NgProbeToken. Maybe you can point me at some documentation, to read more about it. Thankx for your interesst!

**Comment by jasonaden** [comment]
I'm going to close this issue as it was documented as removed. Feel free to continue the discussion.
