### ISSUE TITLE
Unexpected value 'Z' imported by the module 'DO'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by mbx2015** [angular/angular#20375]
After migrating from angular v4.4.6 to V5.0.0 I got the following error when I build and run the app : 
`Uncaught Error: Unexpected value 'Z' imported by the module 'DO'. Please add a @NgModule annotation.
    at d (main.a93e7d26837107e15544.bundle.js:1)
    at r.imports.At.forEach.t (main.a93e7d26837107e15544.bundle.js:1)
    at Array.forEach (<anonymous>)
    at gm.getNgModuleMetadata (main.a93e7d26837107e15544.bundle.js:1)
    at Ty._loadModules (main.a93e7d26837107e15544.bundle.js:1)
    at Ty._compileModuleAndComponents (main.a93e7d26837107e15544.bundle.js:1)
    at Ty.compileModuleAsync (main.a93e7d26837107e15544.bundle.js:1)
    at Yy.compileModuleAsync (main.a93e7d26837107e15544.bundle.js:1)
    at Ys.bootstrapModule (main.a93e7d26837107e15544.bundle.js:1)
    at Object.cDNt (main.a93e7d26837107e15544.bundle.js:1)`

My env:
-node v8.0.0
-npm v5.5.1
-angular cli v1.5.0

What seems to be the problem? I googled it but no way.

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).


-----


You can run your project with `ng serve --aot` so that you can debug

**Comment by billyjacobs2014** [comment]
I am getting the exact same behavior as described above after upgrading from angular 4.4 to 5.1. 

It occurs when I run ng serve on a project which in turn imports modules from a second external control project we created for common controls. This control project was also upgraded to 5.1 and built using the following command:
ngc -p src\tsconfig.json

If I run the primary application, which references modules from the 2nd control application, I get the following based on how I ng serve:
1. using just ng serve I get:
Unexpected value 'FileViewerIframeModule' imported by the module 'ViewPlanModule'. Please add a @NgModule annotation...... like above
2. using ng serve --aot 
No errors and the application works as expected. 

Any suggestions on why that is and what I should look for? I will also continue searching and post any resolution I find here. 

Thanks

**Comment by chris13524** [comment]
Same issue here. And if I build with `--aot`, I do not get the error.

**Comment by avergos29** [comment]
Same issue. 
Note that before v5.x.x a workaround was to use the --preserve-symlinks option.

**Comment by bergben** [comment]
Hey guys, 
make sure to set typescript to version `~2.4.2` in your package.json. See https://github.com/angular/angular-cli/issues/8486

**Comment by chris13524** [comment]
@bergben My typescript version is set to v2.4.2 exactly and I'm still getting the error.

**Comment by billyjacobs2014** [comment]
@chris13524, I just changed my typescript version to 2.4.2 (I previously had it at 2.6.1) in my child common component project, deleted node_modules, re-npm installed my modules and then built my child controls project. Then I went to my main project and deleted node_modules, changed to 2.4.2 (I previously had it at 2.6.1) re npm installed and the errors went away and everything works properly now.   
This was a prototype project that I was using as a reproduction project. Now I will see if it works on my other production projects. 

@bergben run ng --version to make sure it is using the correct version in the folder where you are serving. Also is it possible that you are referencing another control package that was not built with the correct version of typescript?

**Comment by mbx2015** [comment]
When I ignore the build-optimizer everything works properly, even if I'll not get the benefits of the build optimizer, but for me its the only solution (hack) for that issue right now !!,  I build using the next cmd: 
`ng build --no-build-optimizer --prod --aot false`

**Comment by mbx2015** [comment]
@billyjacobs2014 , I just applied you method and it worked! the problem was with typescript version >2.5.1, @angular/compiler requires typescript version >=2.4.2 & <2.5.
Now I can build with `ng build --build-optimizer --prod ` and everything work properly !
