### ISSUE TITLE
angular 2 http.get request is calling twice on page loading time

### ISSUE THREAD

**Issue by BattiniSantthosh** [angular/angular#20372]
## I'm using the angular 2 universal cli
If i send the http.get request through the service, it is requesting the api twice

## server.ts
<pre><code>
/**
 * the polyfills must be the first thing imported
 */
import './polyfills.ts';
import './__2.1.1.workaround.ts'; // temporary until 2.1.1 things are patched in Core
import * as path from 'path';
import * as express from 'express';
import * as compression from 'compression';
import { createEngine } from 'angular2-express-engine';
import { enableProdMode } from '@angular/core';
import { AppModule } from './app/app.node.module';
import { environment } from './environments/environment';
import { routes } from './server.routes';

// App

const app  = express();
const ROOT = path.join(path.resolve(__dirname, '..'));
const port = process.env.PORT || 4200;

/**
 * enable prod mode for production environments
 */
if (environment.production) {
  enableProdMode();
}

/**
 * Express View
 */
app.engine('.html', createEngine({}));
app.set('views', path.join(ROOT, 'client'));
app.set('view engine', 'html');

/**
 * Enable compression
 */
app.use(compression());

/**
 * serve static files
 */
app.use('/', express.static(path.join(ROOT, 'client'), {index: false}));

/**
 * place your api routes here
 */
// app.use('/api', api);

/**
 * bootstrap universal app
 * @param req
 * @param res
 */
function ngApp(req: any, res: any) {
  res.render('index', {
    req,
    res,
    ngModule: AppModule,
    preboot: false,
    baseUrl: '/',
    requestUrl: req.originalUrl,
    originUrl: req.hostname
  });
}

/**
 * use universal for specific routes
 */
app.get('/', ngApp);
app.use('/api', require('./routes/api'));
routes.forEach(route => {
  app.get(`/${route}`, ngApp);
  app.get(`/${route}/*`, ngApp);
});

/**
 * if you want to use universal for all routes, you can use the '*' wildcard
 */

app.get('*', function (req: any, res: any) {
  res.setHeader('Content-Type', 'application/json');
  const pojo = {status: 404, message: 'No Content'};
  const json = JSON.stringify(pojo, null, 2);
  res.status(404).send(json);
});

app.listen(port, () => {
  console.log(`Listening on port ${port}`);
});

</code></pre>
## api.ts
<pre><code>
let express = require('express');
let router = express.Router();

let siteInfo = { name: "ABC", msg: 'Get Info'};

router.get('/', function(req, res, next) {
	console.log("In API")
     res.send(siteInfo)
});

module.exports = router;
</code></pre>

## app.component.html
<pre><code>
<div>
			&lt;h1&gt;</div>
		<div>
			&nbsp; {{title}}</div>
		<div>
			&lt;/h1&gt;</div>
		<div>
			&lt;app-home&gt;&lt;/app-home&gt;</div>
</code></pre>

## home.component.ts
<pre><code>
import { Component, OnInit } from '@angular/core';
import { GetinfoService } from '../getinfo.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  providers: [GetinfoService]
})
export class HomeComponent implements OnInit {
  constructor(
  	private getInfo: GetinfoService
  	) { }
  ngOnInit() {
  	this.getInfo.getInformation()
    .subscribe(
      (info) => {
      	console.log(info)
      }, 
      (err) => { 
      	console.log(err)
      }
     );
  }
}

</code></pre>

## getinfo.service.ts
<pre><code>
import { Injectable } from '@angular/core';
import { Http, Headers } from '@angular/http';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/toPromise';
import { Observable } from "rxjs/Observable";

@Injectable()
export class GetinfoService {

  	apiUrl = 'http://localhost:4200/';
	headers: Headers = new Headers({'Content-Type': 'application/json'})
  	constructor(private http : Http) { }  	
	getInformation():Observable <any>{
	  let url = this.apiUrl +'api';
	  return this.http.get(url, {headers: this.headers}).map(res => res.json());
	}
}
</code></pre>

## in the console api is calling the twice why
<pre><code>
webpack: bundle is now VALID                                                    
Listening on port 4200
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
In API 
{ name: 'ABC', msg: 'Get Info' }
In API 
</code></pre>

Here why the API is called again once get the information for it?

Can you please guide me how to fix this issue. only one time API request to be made on the page loading time

##

**Comment by parys** [comment]
You should use TransferState https://github.com/angular/angular/pull/19134 
because for now first call is for rendering app on server side, after that client app (without transfer state) should bootstrap in the same state, so it makes its own call(second).

**Comment by BattiniSantthosh** [comment]
Can you please guide me how to use the transerState

**Comment by BattiniSantthosh** [comment]
Do I need to use the below for state transer

https://www.npmjs.com/package/@ngx-universal/state-transfer

Please provide the sample code for this, how to use the transerstate?

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).


---

As mentioned above you should use `TransferState` this is an API in `platform-browser` that was introduced in v5 https://angular.io/api/platform-browser/TransferState
here's a little gist showing how to use it https://gist.github.com/Toxicable/81619c10dc7f06417b4244cdadf71880

**Comment by EmaGht** [comment]
If my app doesn't use server-side rendering, why would i need to check this by default?
I think we should be able to decide when and where to use this "double request feature".

I've had many problems upgrading to Angular5 because of this and i solved everything by just not changing the deprecated Http module...

I don't feel like this is user-friendly at all... just my opinion
