### ISSUE TITLE
Warn when node_modules is stale during build

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#2038]
A common source of issues is stale version of installed dependencies.

Just like we warn about stale npm and node version, we should also complain about stale node_modules.

**Comment by caitp** [comment]
We used to have like a cached npm-shrinkwrap.json in node_modules, which would make it really easy to check if anything changed (assuming the cached version matches the one in the tree?). There doesn't seem to be a cached file anymore, does anyone know what happened to that?
