### ISSUE TITLE
large bundle size when i use Angular 5

### ISSUE THREAD

**Issue by teabagp** [angular/angular#20387]
[testapp3.zip](https://github.com/angular/angular/files/1465886/testapp3.zip)

## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When I build the project in Angular 5 the size of the bundle turns out to be very large

## Expected behavior

In Angular 4 the size of the bundle is smaller

## Minimal reproduction of the problem with instructions

You can reproduce the problems using my example. Use command ng build --prod

## Environment

<pre><code>
Angular version: 5.0.1

</code></pre>

**Comment by aravindfz** [comment]
can you share the code for v4

**Comment by teabagp** [comment]
For version 4 I use the same code. I change only the version of Angular in package.json

**Comment by jasonaden** [comment]
@teabagp Please create a repo with your reproduction example so it can be easily cloned from Github.

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
