### ISSUE TITLE
Unhandled Promise rejection: StaticInjectorError[Router]: after updating to Angualr 5.0.1

### ISSUE THREAD

**Issue by Romchik22** [angular/angular#20389]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I can't find the cause of error after upgrading Angular to version 5.0.1. Maybe someone has the same problem.
<pre> zone.js:690 Unhandled Promise rejection: StaticInjectorError[Router]: 
  StaticInjectorError[Router]: 
    NullInjectorError: No provider for Router! ; Zone: <root> ; Task: Promise.then ; Value: Error: StaticInjectorError[Router]: 
  StaticInjectorError[Router]: 
    NullInjectorError: No provider for Router!
    at _NullInjector.get (core.js:923)
    at resolveToken (core.js:1211)
    at tryResolveToken (core.js:1153)
    at StaticInjector.get (core.js:1024)
    at resolveToken (core.js:1211)
    at tryResolveToken (core.js:1153)
    at StaticInjector.get (core.js:1024)
    at resolveNgModuleDep (core.js:10585)
    at _createClass (core.js:10624)
    at _createProviderInstance$1 (core.js:10596) Error: StaticInjectorError[Router]: 
  StaticInjectorError[Router]: 
    NullInjectorError: No provider for Router!
    at _NullInjector.get (webpack-internal:///../../../core/esm5/core.js:1119:19)
    at resolveToken (webpack-internal:///../../../core/esm5/core.js:1407:24)
    at tryResolveToken (webpack-internal:///../../../core/esm5/core.js:1349:16)
    at StaticInjector.get (webpack-internal:///../../../core/esm5/core.js:1220:20)
    at resolveToken (webpack-internal:///../../../core/esm5/core.js:1407:24)
    at tryResolveToken (webpack-internal:///../../../core/esm5/core.js:1349:16)
    at StaticInjector.get (webpack-internal:///../../../core/esm5/core.js:1220:20)
    at resolveNgModuleDep (webpack-internal:///../../../core/esm5/core.js:10781:25)
    at _createClass (webpack-internal:///../../../core/esm5/core.js:10820:68)
    at _createProviderInstance$1 (webpack-internal:///../../../core/esm5/core.js:10792:26)
api.onUnhandledError @ zone.js:690 </pre>
## Environment
<pre> "dependencies": {
    "@angular/animations": "~5.0.1",
    "@angular/cdk": "^5.0.0-rc0",
    "@angular/cli": "^1.5.0",
    "@angular/common": "~5.0.1",
    "@angular/compiler": "~5.0.1",
    "@angular/core": "^5.0.1",
    "@angular/forms": "~5.0.1",
    "@angular/http": "~5.0.1",
    "@angular/material": "^5.0.0-rc0",
    "@angular/platform-browser": "~5.0.1",
    "@angular/platform-browser-dynamic": "~5.0.1",
    "@angular/router": "~5.0.1",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^4.0.5",
    "@ngrx/router-store": "^4.0.4",
    "@ngrx/store": "^4.0.3",
    "@ngrx/store-devtools": "^4.0.0",
    "zone.js": "~0.8.4"
     ....
  },
  "devDependencies": {
    "@angular/cli": "1.5.0",
    "@angular/compiler-cli": "~5.0.1",
    "@angular/language-service": "~5.0.1",
    "tslint": "~5.3.2",
    "typescript": "~2.4.2"
     ...
  }<code>
Angular version: 5.0.1

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.3 
- Platform:  Windows

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/search?q=StaticInjectorError&type=Issues&utf8=%E2%9C%93

**Comment by jasonaden** [comment]
A fix is ongoing for this issue. See #20339.

**Comment by jcjolley** [comment]
This and #20339 were closed, but I was unable to find a solution in either issue.  What is the fix?

**Comment by dlarr** [comment]
Also interested. After migration to Angular 5 i Had this problem : 

> Unhandled Promise rejection: StaticInjectorError[NgZone]: 
>   StaticInjectorError[NgZone]: 
>     NullInjectorError: No provider for NgZone!

There is also a SO post about this :  https://stackoverflow.com/questions/47859373/error-no-provider-for-ngzone


 still no answer :/

**Comment by Jiehong** [comment]
Updating from angular 5.0.x to 5.1.x solves this issue for me.

**Comment by ezekielloves** [comment]
I'm still facing this issue, even with the latest v5.2

**Comment by sebmade** [comment]
try to replace RouterModule.forChild() by RouterModule.forRoot()

**Comment by encounter12** [comment]
I also have this problem with latest Angular 5.2.0 and Angular CLI 1.6.4. In our environment we have an application with some modules and services inserted outside of the app folder using TypeScript Path mapping - see; [https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping](url)

The error I get in the browser console is:

`ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[RouterModule -> Router]: 
  StaticInjectorError(Platform: core)[RouterModule -> Router]: 
    NullInjectorError: No provider for Router!
Error: StaticInjectorError(AppModule)[RouterModule -> Router]: 
  StaticInjectorError(Platform: core)[RouterModule -> Router]: 
    NullInjectorError: No provider for Router!
    at _NullInjector.get (core.js:952)`

**Comment by AndyBrownlie** [comment]
any other resolutions to this?  I've imported HttpModule & HttpClientModule in app.module.ts and still getting same error

**Comment by agusdutra** [comment]
It only happened to me with RoutingModules that imported .forChild() routes only.

Importing RouterTestingModule on the imports declarations of configuringTestingModule fixed this issue, After that I import my RoutingModule for that Module

``` javascript
    beforeEach(async(() => {
        TestBed.configureTestingModule({
            imports: [
                RouterTestingModule,
                CarsRoutingModule,
            ],
            declarations: [ ... ],
            providers: [ ... ]
        })
            .compileComponents();
    }));
```

**Comment by victorotuk** [comment]
please has anyone found a clear solution for the error?

**Comment by systart** [comment]
@sebmade  thank you

**Comment by mdoumbouya117** [comment]
Thx @sebmade

**Comment by baraskarharshal** [comment]
I imported BrowserModule and it fixed the issue.

**Comment by zinara** [comment]
At the module where you implemented the empty path and the wildcard path. Change the forChild to forRoot and export RouterModule. Thats all.

**Comment by loicosquare** [comment]
> I imported BrowserModule and it fixed the issue.

this solved my problem thanks
