### ISSUE TITLE
Error while installing tsc-wrapped

### ISSUE THREAD

**Issue by afixibiranchi** [angular/angular#20388]
I tried the below command for install the tsc-wrapped,
npm i @angular/tsc-wrapped

I get the below error:
npm ERR! Cannot read property '0' of undefined

npm ERR! A complete log of this run can be found in:
/Users/<username>/.npm/_logs/2017-11-13T08_33_33_424Z-debug.log

My Node and NPM versions are as below:

node --version
v8.9.0

npm --version
5.5.1

**Comment by jasonaden** [comment]
I cannot reproduce this error. Also, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
