### ISSUE TITLE
Possible issue with Transfert State

### ISSUE THREAD

**Issue by manzonif** [angular/angular#20386]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently **[serializeTransferStateFactory](https://github.com/angular/angular/search?utf8=%E2%9C%93&q=serializeTransferStateFactory+&type=)** append a script with serialized content at the bottom of body, after vendor.bundle.
So, when vendor.bundle process the **initTransferState** function, the state script is not yet found in the document and **document.getElementById("some-app-key-state")** return null.

## Expected behavior
If I have the state script running before other scripts, the issue disappear, and transfer state work as expected-

```
function serializeTransferStateFactory(doc, appId, transferStore) {
    return function () {
        var /** @type {?} */ script = doc.createElement('script'),
        s = doc.getElementsByTagName("SCRIPT")[0];
        script.id = appId + '-state';
        script.setAttribute('type', 'application/json');
        script.textContent = _angular_platformBrowser.ɵescapeHtml(transferStore.toJson());
        s.parentNode.insertBefore(script, s);
        //doc.body.appendChild(script);
    };
}
```

## Minimal reproduction of the problem with instructions
Running this repo: [ng-demo-transfer-state](https://github.com/feloy/ng-demo-transfer-state)

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
You need to modify your main.ts
```
document.addEventListener('DOMContentLoaded', () => {
  platformBrowserDynamic().bootstrapModule(AppModule);
});
```

**Comment by trotyl** [comment]
Seems already discussed at https://github.com/angular/angular/pull/19134#issuecomment-337551723

**Comment by Expometals** [comment]
Hi @Toxicable, doing that in main.ts, Igetthis error:

```
ERROR in Error: Tried to find bootstrap code, but could not. Specify either statically analyzable bootstrap code or pass in an entryModule to the plugins options.
    at Object.resolveEntryModuleFromMain
```

**Comment by manzonif** [comment]
Would not it be more reasonable to make such a fix?
```
export function serializeTransferStateFactory(
    doc: Document, appId: string, transferStore: TransferState) {
  return () => {
    const script = doc.createElement('script');
    const firstScript = doc.getElementsByTagName("SCRIPT")[0];
    script.id = appId + '-state';
    script.setAttribute('type', 'application/json');
    script.textContent = escapeHtml(transferStore.toJson());
    firstScript.parentNode.insertBefore(script,firstScript);
  };
}
```

**Comment by Toxicable** [comment]
@manzonif no, it is very fragile relying on the ordering of the html elements to solve this issue. The snippet I posted is the correct work around

**Comment by vikerman** [comment]
Please follow #20484
