### ISSUE TITLE
Weird scroll behavior when pointer-events: none is applied

### ISSUE THREAD

**Issue by Ploppy3** [angular/angular#20381]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Scroll cancels when an overlay with `pointer-events: none` is in DOM.
![test2](https://user-images.githubusercontent.com/7990765/32703207-b83d1c5e-c7f2-11e7-845c-9d8c335ff4e2.gif)

## Expected behavior
Scroll should not cancel when an overlay with `pointer-events: none` is in DOM.

![test](https://user-images.githubusercontent.com/7990765/32703202-a790c996-c7f2-11e7-81f9-77213ae30f3f.gif)

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-mabkah

## What is the motivation / use case for changing the behavior?
Performance matters a lot on the web.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version 62
- [x] Chrome (Android) version 62
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.6.0 
- Platform: Windows 

Others:

</code></pre>

## NB
The problem only occurs on Chrome.

**Comment by jasonaden** [comment]
Not sure how to reproduce this issue. Is it Windows specific? What are the exact steps? I'm not seeing the issue in your repro on a mac.

Also, is this an Angular problem? Have you confirmed it works with vanilla HTML/CSS? I can't tell from your animated recordings what environment those were taken from.

**Comment by Ploppy3** [comment]
Broken on Chrome on Windows & Android at least. Confirmed by an Material2 dev. In order to reproduce, hold middle mouse button and move the up or down. 

I originally opened the issue on Material2 because they use an overlay causing this problem and I thought something was wrong on their side but it ended up being a problem with overlays with `pointer-events: none`. I don't have sufficient knowledge to investigate any deeper on either Chrome or Angular.

The Plunker has the component that creates the issue, only 36 lines of code, I can't reproduce out of this as it is a really specific use case, a virtual-scroll component.

**Comment by jasonaden** [comment]
@Ploppy3 Who were you talking to on Material2? Then I could ask them about it as well.

**Comment by Ploppy3** [comment]
Crisbeta at https://github.com/angular/material2/issues/6882

**Comment by jasonaden** [comment]
Per that other issue you were able to fix the problem. But it also sounds like it's something Material would handle rather than Angular. I think it's best to just have one copy of this issue and most of the info is on the version at the Material repo. I'll close this one and if there's something specific for the Angular repo, please create a new issue.

Thanks!

**Comment by Ploppy3** [comment]
> Per that other issue you were able to fix the problem.

No, we did not fix the problem, just reduced the overlay so that it's not an overlay anymore.

> But it also sounds like it's something Material would handle rather than Angular.

Material will handle it and I'm really glad about it but it doesn't fix the problem. They are just finding a way around it.

> I think it's best to just have one copy of this issue and most of the info is on the version at the Material repo.

The only copy of the issue is in a repo that doesn't have anything to do with the issue, all the necessary info are already here.

I said that the issue needs more investigation and my knowledge on Angular is not sufficiant, it's either my code (it's pretty basic so I doubt it but still, I can be wrong), Angular, Chrome, or combination of the last 2.

> I'll close this one and if there's something specific for the Angular repo, please create a new issue.

What make you think it's not related to Angular? Did you open the Stackblitz, it's a version of the issue without Material?

So please, reopen.

**Comment by Ploppy3** [comment]
@jasonaden can you please answer?
