### ISSUE TITLE
Importing external js files problem

### ISSUE THREAD

**Issue by DanijelJurjevic** [angular/angular#20393]
When importing js files (e.g. jquery) to angular 4  they don't get loaded in components **when route changes**. I tried following: 
- to put paths to these js files into angular-cli.json into scripts[ .. ]
"scripts": [
        "./assets/js/jquery-1.11.1.min.js"
]
- to put paths into index.html page
      <script src="../assets/js/jquery-1.11.1.min.js"></script>

The only thing that helps is this solution https://stackoverflow.com/a/44814222 which uses ngAfterViewInit. But, this solution is bad because when I load components html source get replicated <script> tags for each component:
<script src="../assets/js/jquery-1.11.1.min.js"></script>
<script src="../assets/js/jquery-1.11.1.min.js"></script>
<script src="../assets/js/jquery-1.11.1.min.js"></script>
<script src="../assets/js/jquery-1.11.1.min.js"></script>

And also, the solution is buggy, and has issues because of this loading of the js files after view inits. Is there solution for this?

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
