### ISSUE TITLE
Tour of Heroes, chapter 6 (services): should import Observable.of with new rxjs 5.5 style

### ISSUE THREAD

**Issue by williamBurgeson** [angular/angular#20397]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x] Documentation issue or request

Going through the tutorial with a learner, I noticed that the instructions for including Observable.of don't correspond to the new way of doing things.

The tutorial says use 
<code>
import { Observable } from 'rxjs/Rx';
import { of } from 'rxjs/observable/of';

...

getHeroes(): Observable<Hero[]> {
  return of(HEROES);
}
</code>

Whereas 
<code>
import { Observable } from 'rxjs';

...

getHeroes(): Observable<Hero[]> {
  return Observable.of(HEROES);
}
</code>

is more in line with the rxjs 5.5 way of doing things (we don't monkey-patch any more)

**Comment by gkalpak** [comment]
The `Observable` import has been changed to `import { Observable } from 'rxjs/Observable'`. The `of` import seems fine to me (note that it is not patching anything onto `Observable.prototype`).

I am going to close the issue, because everything works as expected afaict, but pelase free to continue the discussion below.

**Comment by gkalpak** [comment]
Actually, I meant the `Observable` import will be fixed with #20350 :grin:

**Comment by williamBurgeson** [comment]
It's not that it doesn't work, but that with rxjs 5.5 they are doing things differently - maybe "of(x)" on it's own is OK - but I thought the recommended style was now to have everything more "conventional", including avoiding deep linking into the rxjs file hierarchy, and just import from the top level.
Also from a readability point of view, with Observable.of(x) it's much more obvious what is going on: if I see just "of(x)" I'll keep thinking "of what???", especially for a slightly larger file.
I might be mistaken about that though.

**Comment by trotyl** [comment]
`rxjs` 5.5 only introduced new way of importing operators (`Observable.prototype` methods), not for observables (`Observable` static methods).

`of` is not an operator. I'm sorry but there is no `new rxjs 5.5 style` stuff for that.
