### ISSUE TITLE
Issue with Zone.js while upgrading angular 4 to v5

### ISSUE THREAD

**Issue by raghu22ram2** [angular/angular#20391]
I'm submitting an issue while upgrading my angular 4 application to angular 5.

Webpack is able to build the project and npm start is working fine, but in browser(chrome 60) I'm getting 2 errors in console and application is not loading.
error details:
1. uncaught Type Error: NativePromise.resolve is not function
2. uncaught Type Error: global[symbolPromise].resolve is not function

My application is working fine in Angular4.
We are using angular-clarity@ 0.10.13

**Comment by raghu22ram2** [comment]
I'm using angular@ 5.0.0

**Comment by JiaLiPassion** [comment]
@raghu22ram2 , this has been fixed in https://github.com/angular/zone.js/pull/916, please wait for a new version of `zone.js`.

**Comment by raghu22ram2** [comment]
Thanks for quick response, but even after adding core-js/es7/promise in pollyfills.ts is not resolving my issue

**Comment by JiaLiPassion** [comment]
@raghu22ram2 , this is a `zone.js` issue, you could try https://github.com/angular/zone.js/files/1459851/zone.zip (replace your `node_modules\zone.js\dist`).

**Comment by raghu22ram2** [comment]
Thank you very much..  You saved my day

**Comment by muralimnmcse** [comment]
@JiaLiPassion Hi thanks for the updated that solved my issue but i am facing the following issue,
webpack-internal:///../../../core/esm5/core.js:1546 ERROR TypeError: $(...).DataTable is not a function
    at eval (webpack-internal:///../../../../angular-datatables/src/angular-datatables.directive.js:45)
    at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:425)
    at Object.onInvokeTask (webpack-internal:///../../../core/esm5/core.js:4816)
    at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:424)
    at Zone.runTask (webpack-internal:///../../../../zone.js/dist/zone.js:192)
    at ZoneTask.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:499)
    at ZoneTask.invoke (webpack-internal:///../../../../zone.js/dist/zone.js:488)
    at timer (webpack-internal:///../../../../zone.js/dist/zone.js:2007)

What versions you are using?
angular/cli: 1.6.2
angular-devkit/build-optimizer: 0.0.36
angular-devkit/core: 0.0.22
angular-devkit/schematics: 0.0.42
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.9.2
schematics/angular: 0.1.11
schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0

**Comment by raghu22ram2** [comment]
I'm using Angular/Cli: 1.5.3

**Comment by JiaLiPassion** [comment]
@muralimnmcse , I think your new error is not a `zone.js` issue, you can post a reproduce repo or plunker here.

**Comment by brahimbouine** [comment]
@JiaLiPassion 
thankyou verymuch.....


> this is a zone.js issue, you could try https://github.com/angular/zone.js/files/1459851/zone.zip (replace your node_modules\zone.js\dist).

**Comment by prathyushp1** [comment]
@JiaLiPassion
thankyou verymuch.....

> this is a zone.js issue, you could try https://github.com/angular/zone.js/files/1459851/zone.zip (replace your node_modules\zone.js\dist).
