### ISSUE TITLE
Static value symbol resolution error prevents use of isDevMode() in NgModule annotation when compiled with AOT

### ISSUE THREAD

**Issue by lukeify** [angular/angular#20409]
# I'm submitting a...

[x] Bug report

# Current behavior

When compiling an Angular project in AOT mode, if `isDevMode` (from `@angular/core`) is present in the `@NgModule` annotation of a component, angular-cli will refuse to compile the project, emitting the following error:

```
Error encountered resolving symbol values statically. Calling function 'isDevMode', function calls are not supported. 
```

The specific code snippet which led to this error was:

```Typescript
import {NgModule, isDevMode} from "@angular/core";

// ...

@NgModule({
    imports: [
        RouterModule.forRoot([], { enableTracing: isDevMode() })
    ],
    exports: [
        RouterModule
    ]
})
export class RoutingModule {}
```

# Expected behavior

Angular project compiles with AOT successfully. 

# Steps to reproduce

1. Integrate snippet from above into angular-cli project.
2. Run `ng build --prod`. 
3. Observe error. 

# What is the motivation / use case for changing the behavior?

Increased AOT compilation success rate & maintaining functional similarities between what developers must write for JIT vs. AOT.

# Environment

- Angular version: 5.0.1
- angular-cli version: 1.5.0
- Node version: 8.6.0
- Platform: Tested against macOS & Windows

**Comment by sarunint** [comment]
I believe this is an intended behaviour. The solution is to move `isDevMode()` out of the annotation. (By defining to a variable)

**Comment by jasonaden** [comment]
Correct. You will need to set the return value to a variable, and use the variable rather than calling the function when wiring up the NgModule.

**Comment by lukeify** [comment]
@jasonaden Is there any chance then at least the error message could be improved so developers know you place functions in ngModule with AOT generally? It's a bit weird to mark something which produces an Error as not a bug, especially considering the unhelpfulness of the error emitted.

**Comment by mhussain001** [comment]
Thanks it worked for me with following code
```
let checkDevMode = false;
if (isDevMode()) {
  checkDevMode = true;
}
```
