### ISSUE TITLE
SwPush breaks Angular on Safari - undefined is not an object (evaluating 'source.lift')

### ISSUE THREAD

**Issue by maciejtreder** [angular/angular#20407]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When `SwPush` is injected in any service/component Safari complains with:
```
TypeError: undefined is not an object (evaluating 'source.lift') - map.js:46
```

## Expected behavior
SwPush should not break Safari build (ie code should be ignored when service worker is not available)

## Minimal reproduction of the problem with instructions

Inject `SwPush` into service/component.

Online example:
https://www.angular-universal-pwa.maciejtreder.com

github repo:
https://github.com/maciejtreder/angular-universal-pwa

## Environment

<pre><code>
Angular version: 5.0.0
rxjs: 5.5.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.5.0  
- Platform: Mac 

</code></pre>

**Comment by maciejtreder** [comment]
Warkaround can be found in my Angular PWA starter:
https://github.com/maciejtreder/angular-universal-pwa
https://github.com/maciejtreder/angular-universal-pwa/pull/68/files#diff-ce9cfd30bd8965cf7bf8754af08e4825R21-R27

```
    private swPush: SwPush;

    constructor(private injector: Injector) {
        try {
            this.swPush = this.injector.get(SwPush);
        } catch (error) {
            // workaround for https://github.com/angular/angular/issues/20407
        }
    }
```

**Comment by alxhub** [comment]
Fixed by https://github.com/angular/angular/commit/7cabaa0ae745dfbbad664b71da70eec89c17c744
