### ISSUE TITLE
bug(service-worker): Config urls don't respect deployUrl

### ISSUE THREAD

**Issue by Isigiel** [angular/angular#20405]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Setting a base href of `/app` generates `"index": "/app/index.html"` but also `"/app/0.5b9e33705dd6467bd973.chunk.js"` in the urls.

## Expected behavior

The deployUrl should be respected as well. MIne is `../public/` => the config urls should be `"/public/0.5b9e33705dd6467bd973.chunk.js"`. Right now my service worker just requests everything my app requests and does not cache any responses.

## Minimal reproduction of the problem with instructions

To reproduce, create an app with the static files deployed not where the index.html is and try to use the service worker.

## What is the motivation / use case for changing the behavior?

Allow using baseHref and deploy url while using the service worker

## Environment

<pre><code>
Angular version: 5.0.1

Browser:
- all

Others:

I feel like this concerns the cli as well, but from the code I saw it has to be fixed in here as well, because the cli is just forwarding the baseHref.
</code></pre>

**Comment by naveedahmed1** [comment]
Any update on this? I want the js bundles to be served from a CDN url which I specify through `--deploy-url` while building production build. May be a new option of `deployURL `could be added to the `AssetGroup`.

**Comment by gkalpak** [comment]
I think this is a cli issue. Closing as ducplicate of angular/angular-cli#9753.
