### ISSUE TITLE
Location.subscribe wrong typedefinition and documentation

### ISSUE THREAD

**Issue by Davilink** [angular/angular#20406]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

## Current behavior
The documentation and the definition file indicates that the **subscribe** method from the Location class, return an object: Object: https://angular.io/api/common/Location#subscribe

## Expected behavior
I would expected to receive an Subscription object.

## Minimal reproduction of the problem with instructions

```
export class Dummy {
private subscription: Subscription;
constructor(private platformLocation: Location) {
this.subscription = platformLocation.subscribe((e: PopStateEvent) => {
// ...
});
subscription.unsubscribe(); // Error unsubscribe doesn't exist
}
}```

## What is the motivation / use case for changing the behavior?
To be able to remove handleEventListener.

## Environment

<pre><code>
Angular version: 2.0.0 - 5.0
</code></pre>

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

NOTE: You have a local `subscription` variable only available in your constructor. This isn't an Angular issue, it's just the code is incorrect JavaScript.

**Comment by Davilink** [comment]
>Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request 
OK, it's not a bug report, but it still a documentation Issue.
[x] Documentation issue or request

> NOTE: You have a local subscription variable only available in your constructor. This isn't an Angular issue, it's just the code is incorrect JavaScript.
It's was only for showing what i use, but OBVIOUSLY i didn't use it like that...

Maybe more speaking : 
![image](https://user-images.githubusercontent.com/1498932/32788611-b10b06e0-c927-11e7-902a-2eea5a644f03.png)

But if i cast it before like this :
![image](https://user-images.githubusercontent.com/1498932/32788679-e2faf0e8-c927-11e7-9af3-5893500602b1.png)

 the removePopstate() method will work perfectly, it's will remove the popstate listener, but the documentation don't reflect that behavior.

the documentation tell us that the subscribe method of the Location class return an object from the Object Class (It's true because all object inherited that class), but when i inspect i found this : 
![image](https://user-images.githubusercontent.com/1498932/32789437-d6bd19a8-c929-11e7-9e00-11a6cb8c3082.png)

**Comment by jasonaden** [comment]
Ah! Now I understand.

Actually, I think you should file an actual bug (or maybe create a PR) to fix the type here:

https://github.com/angular/angular/blob/5.0.1/packages/common/src/location/location.ts#L132

The doc is taken from the type annotation there, so fixing the return to Subscription should do the trick.

**Comment by Davilink** [comment]
Will you update the online documentation too ?
https://angular.io/api/common/Location#subscribe

**Comment by jasonaden** [comment]
That should update automatically.

**Comment by Davilink** [comment]
I just saw that the angular website has been updated. Great job !
