### ISSUE TITLE
Can't resolve node_moduels in cli.json with Angular 5

### ISSUE THREAD

**Issue by Jonathan002** [angular/angular#20400]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I keep getting this error while trying to load a script in the angular-cli.json
```
Error: EISDIR: illegal operation on a directory, read
```

I'm trying to load jQuery for bootstrap alpha js to work:
angular-cli.json:
```javascript
"scripts": [
        "../node_modules/jquery"
      ],
```

## Expected behavior

It should compile and resolve without the error

## Minimal reproduction of the problem with instructions

Use Angular 5 - this is my package.json
```
{
  "name": "ng-project",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "bootstrap": "^4.0.0-beta.2",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jquery": "^3.2.1",
    "popper.js": "^1.12.3",
    "rxjs": "^5.5.2",
    "swiper": "^4.0.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@types/jquery": "^3.2.16",
    "@angular/cli": "1.5.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}

```

I've also tried switching the whole node_modules folders with an Angular 4 project's node_modules folder and the scripts in the angular-cli.json can compile properly with those node_modules.

## What is the motivation / use case for changing the behavior?

Get the project running.

## Environment

<pre><code>
Angular version: X.Y.Z
Angular CLI: 1.5.0
Node: 8.1.2
OS: darwin x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.4.2
webpack: 3.8.1

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
This is not an issue with Angular

With `"scripts":` you must provide a full path to a js file, so it has to look something like `"../node_modules/jquery/script.js"`

**Comment by Jonathan002** [comment]
I also have tested this with other scripts using a full path. This exact angular-cli.json works with the path specified on older node_modules if I use Angular 4.

Angular Cli works with these dependencies on my archive project before upgrading:
```
{
  "name": "ng-project",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.4.5",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/material": "^2.0.0-beta.12",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "bootstrap": "^4.0.0-beta.2",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jquery": "^3.2.1",
    "popper.js": "^1.12.3",
    "rxjs": "^5.4.2",
    "swiper": "^4.0.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.3.2",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "^3.2.16",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}

```

Also the jQuery folder's package.json points to it's dist for the script file so it can resolve properly.

**Comment by jasonaden** [comment]
@Jonathan002 If this `package.json` works pre-Angular v5, this could be a regression. Please create a repo that reproduces this issue so we can clone and test.

Also, sounds like this would be a CLI issue. Does this example work if you just downgrade Angular? Or do you need to downgrade both CLI and Angular to make it work?

**Comment by jasonaden** [comment]
I'll close this for now. You should file it against the [Angular CLI](https://github.com/angular/angular-cli) project.

**Comment by Jonathan002** [comment]
@jasonaden thanks for the reply about angular-cli,  I downgraded back to 1.3.2 for the cli with Angular 5 dependencies and I got the project compiling again. I'll bring up this issue with the cli team.
