### ISSUE TITLE
feat(service-worker): add staleWhileRevalidate strategy

### ISSUE THREAD

**Issue by Isigiel** [angular/angular#20402]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The service worker only supports networkFirst and cacheFirst caching for DataGroups.

## Expected behavior

Also support staleWhileRevalidate Strategy.
As shown here: https://developers.google.com/web/fundamentals/instant-and-offline/offline-cookbook/#stale-while-revalidate

## What is the motivation / use case for changing the behavior?

This would help with slow data requests, that can not be cached for a long time. They would be way faster while still being al most up to date.
I workaround for now would be to limit the cache time in order to catch repetitive requests, but staleWhileRevalidate is preferable in my opinion.

**Comment by MattiJarvinen-BA** [comment]
Had assumed that performance was actually stale while revalidate. It is not 
On line 355 it returns if cache entry was found.
https://github.com/angular/angular/blob/396c2417d95639e858f6e11970ded09817e9e01c/packages/service-worker/worker/src/data.ts#L339-L375

**Comment by Isigiel** [comment]
Stale while revalidate would require the service worker to fetch the resource even after it was found in the cache to update. I'm quite sure the current `performance` Strategy is like this @MattiJarvinen-BA 
https://developers.google.com/web/fundamentals/instant-and-offline/offline-cookbook/#cache-falling-back-to-network

**Comment by josephliccini** [comment]
Hi all,

Just brainstorming a little here.

One thing that I see being tricky about this would be: how are the consumers of the cached API calls notified that there is now a newer version available in the cache? In the current implementation, I don't see a particularly easy way to achieve this.  Would something like cache update notifications for an API resource even be desirable?

To get it to work with the current implementation, one would have to keep the current `'performance'` strategy, but right before returning the `res` from the cache, do an async revalidation network call to update the cache with the latest data. 

This way, each subsequent API call after successful 'revalidation' network call would get the newest data from cache, which (I think) would be good enough for our app's use-case.  I have to do a bit more thinking, but happy to contribute / discuss ideas.

**Comment by odahcam** [comment]
Guys, I think line https://github.com/angular/angular/issues/20402#L366 could be related to these https://github.com/angular/angular/issues/21636#issuecomment-361641561 errors. 

By default, shouldn't SW's cached content be fetched and work in offline mode?

I got my offline app working just one time when I messed up with some configurations and SW itself (I've deleted SW from production build). I'm unable to track the cause of my issue.

**Comment by josephliccini** [comment]
To get this functionality, our group created a separate NPM task for creating a `workbox-build` service worker.  It supports this `'staleWhileRevalidate'` strategy, as well as a bit more configuration, and also custom SW authoring.  

Though I really liked Angular's setup and how easy it was to get started, the Workbox one gave our group that extra configuration that we really needed.  Looking forward to seeing both libraries grow and learn from each other in the future.

**Comment by gkalpak** [comment]
You should basically be able to emulate the `staleWhileRevalidate` strategy with `strategy: 'freshness'` and `timeout: 0u`.
This will essentially do the following:
1. Try to fetch from network first.
2. If the network request does not complete after the 0ms timeout (:grin:), fallback to the cache (ignoring cache age).
3. Once the network request completes, update the cache.
4. If the resource does not exist in the cache, wait for the network request anyway.

##
Maybe we could document this.
Or add the `staleWhileRevalidate` option, which would essentially transform to `freshness + 0ms timeout` under the hood.

By show of hands, who would be interested in submitting a PR? :smiley:

**Comment by atmosuwiryo** [comment]
Sorry for commenting on closed issue, but I've tried solution wrote by @gkalpak 
Unfortunately, the updated response only update(saved at) the cache so the page will not updated until next refresh.

**Comment by gkalpak** [comment]
@atmosuwiryo, not sure what you mean. Do you mean that requesting the resource again (after it is saved in the cache) will not serve the latest (saved) response, untill you do a full-page reload? That sounds strange. If you can set up a minimal reproduction, I'd be happy to investigate.

(If you mean that the request is only made once (on page load), so with the `staleWhileRevalidate` strategy you don't get the latest content until a full-page reload, then that works as expected - this is what the `staleWhileRevalidate` strategy is for. If you want to always get the latest content, you can use the `freshness` strategy.)

**Comment by atmosuwiryo** [comment]
@gkalpak, **my mistake** then. It's for `staleWhileRevalidate` strategy so **it is works as expecte**d then.

What I'm trying to achive is that I've created offline-image cache directive with strategy:
1. fetch online
2. while wait for response, update image's src to locally saved image
3. When response received, update the image's src with the online response, also update the locally saved image.

Now i'm testing, can service-worker do it with same result.

Note: I'm using this for ionic project.

**Comment by gkalpak** [comment]
I see. No, this is not possible to do via a SW strategy (afaik). You need to implement some custom logic.

**Comment by vinay-akkipet** [comment]
@gkalpak Setting the timeout to 0 on a freshness strategy will be helpful, thanks.
In scenarios where we would like to update the page immediately whenever we know that the returned network request has a new payload this approach doesn't help and as you mention we would have to write some custom logic.
Have you considered exposing some hooks or generating events based on which we could execute our custom logic? NGSW is already super easy to use and this would make it highly configurable like a workbox or something.

**Comment by gkalpak** [comment]
@vinay-akkipet, we are considering ways to make `@angular/service-worker` more flexible/extensible in the future, but there are no immediate plans (or a timeline). Currently, the focus is on getting Ivy (the new renderer) out.

**Comment by odahcam** [comment]
Ivy is super important and should come first, but after Ivy hooks or events on the SW would be great, once without them we can't do much to interact with the user via UI, which would be great for some scenarios, e.g. when the app requires some update to be applied before the user continues to use the application.

**Comment by gkalpak** [comment]
(BTW, [SwUpdate][1] does provide some integration points regarding updates specifically.)

[1]: https://angular.io/api/service-worker/SwUpdate

**Comment by Modeso** [comment]
> @gkalpak, **my mistake** then. It's for `staleWhileRevalidate` strategy so **it is works as expecte**d then.
> 
> What I'm trying to achive is that I've created offline-image cache directive with strategy:
> 
> 1. fetch online
> 2. while wait for response, update image's src to locally saved image
> 3. When response received, update the image's src with the online response, also update the locally saved image.
> 
> Now i'm testing, can service-worker do it with same result.
> 
> Note: I'm using this for ionic project.

You solution is actually what we also need to achieve. For following reasons:
1. we want that the users sees a result a result fast.
2. But the data might be updated with the request and so we want to update the view which displayes this data immediatly when the cache was updated.

Basically what we want to achieve is that we subscribe to the cache directly instead of subscribing to the httpclient.
httpclient should update the cache any time when the data was requested.

<img width="816" alt="Service_workers_and_caching_strategies_explained_-_DEV_Community_👩💻👨💻" src="https://user-images.githubusercontent.com/11499388/68693013-2d774c80-057f-11ea-83df-1516d240201c.png">

This is defently not possible with the freshness strategy. So basically what we need to do is implement our own service worker for that?

**Comment by gkalpak** [comment]
Yes, see https://github.com/angular/angular/issues/20402#issuecomment-510667434.

**Comment by atmosuwiryo** [comment]
@Modeso I created custom directive to handle img tag since i only care for image cache. Like I've said here https://github.com/angular/angular/issues/20402#issuecomment-510664299
