### ISSUE TITLE
Add support for unary + in property bindings

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#20418]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I had tried to get that feature in #7964 back in the day, but got bitten by it again today.
A unary + in Javascript is used to convert anything to a number so that addition does the right thing. On the other hand, the template parser just ignores this token and does nothing.
Today, I wanted to bind input element values to a component's properties where the other component's template internally added two of those properties. This resulted in string concatenation instead of numeric addition.

As a workaround for my specific case, I have replaced `[prop]="+value"` with `[prop]="value*1"`

## Expected behavior

Unary + has a meaning in Javascript. Either make the template compiler honor that behavior or make it an error instead of silently dropping it.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
fixed by #22154 already.

**Comment by Tragetaschen** [comment]
Thanks
