### ISSUE TITLE
[compiler-cli] Some enums are missing from `ngc` transpiled code

### ISSUE THREAD

**Issue by BoykoAlex** [angular/angular#20412]
## I'm submitting a bug

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I'm compiling project https://github.com/spring-projects/spring-flo/commits/angular5 (__ensure `angular5` branch is selected__) with Angular 5.x Compiler CLI and `Flo.DnDEventType` and `Flo.Severity` enums are missing from the generated js code in `spring-flo/dist/spring-flo-es5.js` and `spring-flo/dist/spring-flo.js` (source `spring-flo/src/lib/src/shared/flo-common.ts`) while enum `Properties.InputType` (source `spring-flo/src/lib/src/shared/flo-properties.ts`) is present. Very confusing. All enums are being used throughout the code. The result is that when the lib is built `Flo.DnDEventType` is undefined for libs that are using it.

## Expected behavior
`compiler-cli` 4.1.3 used to generate the following (check master branch of the same repo):
```
var Flo;
(function (Flo) {
    Flo.joint = _joint;
    Flo.DnDEventType = {};
    Flo.DnDEventType.DRAG = 0;
    Flo.DnDEventType.DROP = 1;
    Flo.DnDEventType[Flo.DnDEventType.DRAG] = "DRAG";
    Flo.DnDEventType[Flo.DnDEventType.DROP] = "DROP";
    Flo.Severity = {};
    Flo.Severity.Error = 0;
    Flo.Severity.Warning = 1;
    Flo.Severity[Flo.Severity.Error] = "Error";
    Flo.Severity[Flo.Severity.Warning] = "Warning";
    /**
     * @param {?} view
     * @param {?} className
     * @return {?}
     */
    function findMagnetByClass(view, className) {
        if (className && className.startsWith('.')) {
            className = className.substr(1);
        }
        return view.$('[magnet]').toArray().find(function (magnet) { return magnet.getAttribute('class').split(/\s+/).indexOf(className) >= 0; });
    }
    Flo.findMagnetByClass = findMagnetByClass;
```
while with 5.0.1 it is:
```
var Flo;
(function (Flo) {
    Flo.joint = _joint;
    /** @enum {number} */
    function DnDEvent() { }
    Flo.DnDEvent = DnDEvent;
    function PropertyMetadata() { }
    Flo.PropertyMetadata = PropertyMetadata;
    function ExtraMetadata() { }
    Flo.ExtraMetadata = ExtraMetadata;
    function ElementMetadata() { }
    Flo.ElementMetadata = ElementMetadata;
    function ViewerDescriptor() { }
    Flo.ViewerDescriptor = ViewerDescriptor;
    function MetamodelListener() { }
    Flo.MetamodelListener = MetamodelListener;
    function Metamodel() { }
    Flo.Metamodel = Metamodel;
```

## Minimal reproduction of the problem with instructions
Clone https://github.com/spring-projects/spring-flo `angular5` branch
`rm -rf node_modules`
`npm install`
`npm run build`
Check contents of `spring-flo/dist/spring-flo-es5.js`. Look for `DnDEventType` - won't find enum declaration. Look for `InputType` there is enum declaration.

## What is the motivation / use case for changing the behavior?
Looks like regression

## Environment

<pre><code>
Angular version: 5.X.X

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mbaer3000** [comment]
This is a critical bug. We cannot use AOT compilation anymore with Angular 5.

**Comment by xealot** [comment]
I think I may have a related problem. When trying to use `ngc` to generate a library, some strange parts of the Typescript are omitted.

Original Snippet:
```ts
@Injectable()
export class AuthStatusService {
    private _status = new BehaviorSubject<PrincipalObj>(null);
    public status = this._status.asObservable();
    public snapshot: PrincipalObj;

    constructor() {
        getPrincipalData()
            .then(token => {
```

Output from `ngc` (in es2015 mode), note how there is no class-level variable initialization. Pretty weird.
```ts
export class AuthStatusService {
    constructor() {
        getPrincipalData()
            .then(token => {
```

Output from `tsc` (in es2015 mode), seems like things are working as expected.
```ts
let AuthStatusService = class AuthStatusService {
    constructor() {
        this._status = new BehaviorSubject(null);
        this.status = this._status.asObservable();
        getPrincipalData()
            .then(token => {
```

@angular/compiler@5.0.2

**Comment by sarunint** [comment]
@xealot Please ensure that you are using TypeScript 2.4.2. Support for compiling with TypeScript 2.5 is going to land in Angular v5.1.

**Comment by mhevery** [comment]
closing as obsolete
