### ISSUE TITLE
Argument of type '{ type: string; payload: IUiState; }' is not assignable to parameter of type 'Action'. ?

### ISSUE THREAD

**Issue by phpcodexpert** [angular/angular#20413]
Argument of type '{ type: string; payload: IUiState; }' is not assignable to parameter of type 'Action'.
  Object literal may only specify known properties, and 'payload' does not exist in type 'Action'.

ERROR in C:/Users/seefat/studio-lite-master/src/app/location/location-map.ts (316,57): Argument of type '{ type: string; payload: IUiState; }' is not assignable to parameter of type 'Action'.
  Object literal may only specify known properties, and 'payload' does not exist in type 'Action'.

**Comment by mlc-mlapis** [comment]
@phpcodexpert ... absolutely unclear what it is.

**Comment by jasonaden** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by phpcodexpert** [comment]
Thanks
