### ISSUE TITLE
aio has title on the homepage set to "Angular - link" instead of just "Angular"

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#20427]
if you navigate to [angular.io](https://angular.io), you'll see:

<img width="238" alt="screen shot 2017-11-14 at 5 15 11 pm" src="https://user-images.githubusercontent.com/216296/32790723-7f59f006-c95f-11e7-873e-4ffc6192daa5.png">

## Brief analysis of how this happens:

When we generate `marketing/index.json` for the first page we turn the original `marketing/index.md` code:

```
<article>
  <h1 class="no-toc" style="display: none"></h1>
  ...
</article>
```

into:

```
<article>
  <h1 class=\"no-toc\" style=\"display: none\" id=\"\"><a title=\"Link to this heading\" class=\"header-link\" aria-hidden=\"true\" href=\"index#\"><i class=\"material-icons\">link</i></a></h1>
  ...
</article>
```

which then gets picked up by doc-viewer which then finds the "link" text node and uses that to incorrectly set the title: https://github.com/angular/angular/blob/24cf8b326918e0694dfcdcf48635b5325060827a/aio/src/app/layout/doc-viewer/doc-viewer.component.ts#L99-L106

**Comment by gkalpak** [comment]
For future reference: The issue is that `innerText` does not work as expected on elements with `display: none`.
