### ISSUE TITLE
Ability to stop event propogation

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#2042]
In the GT codebase, we have a common pattern ```<ng-click-stop-propogation>```, which provides the same API as <ng-click>, but is implemented as:

```
(node as Element).onClick.listen((event) {
      scope.apply(expression);
      event.preventDefault();
      event.stopPropagation();
    });
```

We would like a similar pattern in Angular2.

**Comment by mhevery** [comment]
I think this is already support in three ways:

1. returning `false` causes `preventDefault()` to run. ie: `<div (click)="doSomething(); false">`
2. calling it manually: `<button (click)="doSomething(); $event.stopPropagation()">`
3. One can always implement the same directive in NG2 as:

```javascript
@Directive({
  selector: `click-stop-propagation`
  events: 'stopClick($event)'
})
class ClickStopPropagation {
  stopClick(event:Event) {
    event.preventDefault();
    event. stopPropagation();
  }
}
```

Then use as:

```html
<button (click)="doSomething()" click-stop-propagation>
```

## Request

Do you think the above is not sufficient? If so, how would you imagine the syntax to work?

**Comment by gdi2290** [comment]
this would work too correct? assuming the return type of `doSomething` is `void`
```html
<div (click)="!!doSomething()">
```

**Comment by jbdeboer** [comment]
#1 should work for us.

Interestingly, reactjs deprecated event handler return values in 0.12.  It
may be worth investigating to ensure you don't hit the same issues they
did.

Also, this pattern should be documented somewhere.
On May 27, 2015 5:37 AM, "PatrickJS" <notifications@github.com> wrote:

this would work too correct? assuming the return type of doSomething is void

<div (click)="!!doSomething()">

—
Reply to this email directly or view it on GitHub
<https://github.com/angular/angular/issues/2042#issuecomment-105689213>.

**Comment by tbosch** [comment]
[Here](https://facebook.github.io/react/blog/2014/10/16/react-v0.12-rc1.html#deprecated-returning-false-in-event-handlers) is the the comment from the React blog: 

> Deprecated: Returning false in Event Handlers
> It used to be possible to return false from event handlers to preventDefault. We did this because this works in most browsers. This is a confusing API and we might want to use the return value for something else. Therefore, this is deprecated. Use event.preventDefault() instead.

In Angular, the event handler that a user implements is actually not the event handler that the browser sees, but there is an indirection in between (e.g. needed for marshaling things over to webworkers). The argument for the return value would still count though... Thanks @jbdeboer for the hint to look there as well.

**Comment by jbdeboer** [comment]
Has this pattern been documented?

**Comment by HMhugomeireles** [comment]
I think is this.

<input (keydown)="onKeydown($event)">

onKeydown(event) {
event.preventDefault();
  if (event.key === "Enter") {
    console.log(event);
  }
}

**Comment by micsel** [comment]
HMhugomeireles


> 
> ```
> <input (keydown)="onKeydown($event)">
> 
> onKeydown(event) {
> event.preventDefault();
>   if (event.key === "Enter") {
>     console.log(event);
>   }
> }
> ```

Works but the user cannot type on the input anymore, a little edit made it work, with the below code.
> ```
> onKeydown(event) {
>   if (event.key === "Enter") {
>     event.preventDefault();
>     console.log(event);
>   }
> }
> ```

**Comment by DenisSemionov** [comment]
Now it of course works with event.preventDefault, but easier way to do this:

`<mat-checkbox (click)="doAction(); false"></mat-checkbox>`

Just add `false` after semicolon.
