### ISSUE TITLE
When replacing form control which has async validator the status from statusChange stays PENDING

### ISSUE THREAD

**Issue by dzonatan** [angular/angular#20424]
## I'm submitting a...
<pre><code>[X] Bug report</code></pre>

## Current behavior
When replacing form control with a new one which has asynchronous validator only `PENDING` status is broadcasted from `statusChanges` observable.

```ts
const myForm = new FormGroup({
  myControl: new FormControl('simple input');
});
    
myForm.statusChanges
  .subscribe(status => console.log(status));

myForm.setControl('myControl', new FormControl('another input', null, asyncValidator));
```
Console will only print `PENDING`. Nothing more.

## Expected behavior
Final `VALID` or `INVALID` status should be broadcasted after async validator finishes his job.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-qmdbkx

## Please tell us about your environment
<pre><code>Angular version: 7.0.1</code></pre>

**Comment by jsdevtom** [comment]
What happens when you listen to the control itself like so:

```
myForm.get('myControl').statusChanges
  .subscribe(status => console.log(status));

```
?

**Comment by rdnscr** [comment]
This issue still exists for me in ng v. 6.0.5. I registered myself to the statusChanges event and it is not fired for the result. I only get the notification for the transition to pending.

In essence this makes it currently quiet hard to use the async validator properly. Are there already some straight forward workarounds?

**Comment by oldbasilbear** [comment]
I am also experiencing this problem. 
Workarounds / fix due please?

**Comment by Endran** [comment]
I am using as a workaround:

`merge(of(formGroup.status), formGroup.statusChanges).pipe(
      filter(status => status !== 'PENDING'),
      take(1)
)`

Hope it helps

**Comment by Endran** [comment]
Are you sure your async validator is completing? I had similar behaviour in TestBed u till I added  `take(1)` to my `AsyncValidatorFn`.

**Comment by Endran** [comment]
Yeah, I was a bit to hasty. Nevermind.

**Comment by karptonite** [comment]
I'm Running into this issue as well, in Angular 7.1.

**Comment by suspectpart** [comment]
What about this issue? We still have trouble with this behavior. Is a fix anywhere near?

**Comment by dzonatan** [comment]
A fix is waiting to be reviewed/merged at #20806 for two years already.
Core team simply does not care about issues with forms.
Same goes with #18575

**Comment by suspectpart** [comment]
@kara @jasonaden Since you added labels to this issue: any prospect of having the pull request reviewed and merged eventually?

**Comment by artoodeeto** [comment]
I have the same problem but with `addControl` :disappointed:
