### ISSUE TITLE
Javascript files importing to angular 4 

### ISSUE THREAD

**Issue by DanijelJurjevic** [angular/angular#20425]
## I'm submitting a...

<pre><code>[x] Bug report  
</code></pre>

## Current behavior

When I try to import external javascript files into angular, files are loaded on index loading, but when route changes content doesn't get access to javascript files anymore. I have created small angular project with importing two js files in angular-cli.json file. One is jquery, the other uses jquery. I can't make it run (maybe it's not the closest explanation of my problem but that is the best that I could create). Repo url: https://github.com/DanijelJurjevic/angular-importing-js

## Expected behavior

Imported javascript files should be available through all routes since the main purpose of SPA is to load resources one time and use them, not to load them on every route change.

## Minimal reproduction of the problem with instructions

-first I tried to import javascript files in angular-cli.json file (not working): 
<pre><code>"scripts": [
        "./assets/js/jquery-1.11.1.min.js"
]</code></pre>
-then I tried to put urls directly into index.html (not working):
<pre><code><script src="../assets/js/jquery-1.11.1.min.js"></script></code></pre>

The solution was to use AfterViewInit, and there load javascript files (https://stackoverflow.com/a/44814222):
<pre><code>
export class OverviewComponent implements  AfterViewInit {
         async ngAfterViewInit() {
		await this.loadScript('../assets/js/jquery-1.11.1.min.js');
		await this.loadScript('../assets/js/jqueryUI.js');
		await this.loadScript('../assets/js/bootstrap.min.js');
		await this.loadScript('../assets/js/jquery.elevatezoom.js');
		await this.loadScript('../assets/js/owl.carousel.min.js');
		await this.loadScript('../assets/js/jquery.themepunch.revolution.min.js');
		await this.loadScript('../assets/js/jquery.themepunch.plugins.min.js');
		await this.loadScript('../assets/js/price-range.js');
		await this.loadScript('../assets/js/wow.min.js');
		await this.loadScript('../assets/js/store.js');
	}
   
	 private loadScript(scriptUrl: string) {
	   return new Promise((resolve, reject) => {
		 const scriptElement = document.createElement('script');
		 scriptElement.src = scriptUrl;
		 scriptElement.onload = resolve;
		 document.body.appendChild(scriptElement);
		})
	 }
}
</code></pre>
And I have this loading on every component, so at the end I get piled up script tags in index.html (shown below) which is bad but works somehow (so this solution works but it's not good enough). In example below I presented only jquery scripts but it happens for all jqueryUI, store.js wow.min.js etc

`<html><head></head>`
`<body>`
`<app-route></app-route>`
`<script src="../assets/js/jquery-1.11.1.min.js"></script>`
`<script src="../assets/js/jquery-1.11.1.min.js"></script>`
`<script src="../assets/js/jquery-1.11.1.min.js"></script>`
`<script src="../assets/js/jquery-1.11.1.min.js"></script>`
`<script src="../assets/js/jquery-1.11.1.min.js"></script>`
`</body>`
`</html>`

## Environment

<pre><code>
Angular version: 4
Packaging: Webpack

Browser:
- [x] Chrome (desktop) version 62.0.3202.75

**Comment by jasonaden** [comment]
I believe you're running into this issue, which is reported against the CLI. If this doesn't match the problem you're having, please file a new issue. But I think those CLI issues I referenced above will address the problem you're having.

Thanks for sending this with a repo to reproduce the issue!

**Comment by prasworld** [comment]
I am getting the following error in Angular 6

Refused to execute script from 'http://localhost:4200/node_modules/jquery/dist/jquery.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

How to resolve this one as in the previous Angular 4 it was working fine.

**Comment by flendsiva** [comment]
Thank aLot I'm very Hapyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy,I'm searched this issue past 6month,even i'm a tried many ways to tried........:)  
Again and Again Thank u :+1: :)
