### ISSUE TITLE
Make @angular/compiler-cli main function part of public api

### ISSUE THREAD

**Issue by dominique-mueller** [angular/angular#20422]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I am currently using the `@angular/compiler-cli` (version 5) package to build an Angular library which is compatible with Angular AoT compilation and bundlers such as Webpack.

In the command line, I can simply use the `ngc` command line tool to run the build. However, in order to use the Angular Compiler programmatically (meaning within a custom NodeJS script), I either
- have to run `ngc` by using `child_process.exec` or `child_process.spawn`
- have to make a "deep import" from `@angular/compiler-cli/src/main` to get access to the `main` function (which is still optimized for being used via command line).

Or am I missing something? The documentation on how to use the `@angular/compiler-cli` is not that detailed ...

## Expected behavior
I'd love to see the `main` function being part of the public API (exported in the `index.ts` file), or - perhaps even better - an equivalent function optimized for programmatic usage. This would heavily simplify the development of custom buid tools / build chains. I could also re-implement the stuff happening within the `main` function but then I wouldn't benefit from any updates regarding this.

## Environment

<pre><code>
Angular version: 5.0.1 (latest)
 
For Tooling issues:
- Node version: Tested with NodeJS 9 and NodeJS 8
- Platform: Tested on Windows 10 & Windows 7
</code></pre>

**Comment by sarunint** [comment]
It's quite complicate since this package isn't following semantic versioning. But I really like this idea.

So I'd like to propose this: make `@angular/compiler-cli` part of public API, but it can have breaking changes at anytime. So that developers can have references while using this package.

**Comment by dominique-mueller** [comment]
Does `@angular/compiler-cli` have any breaking changes except a different output (e.g. `metadata.json` version)?

**Comment by trotyl** [comment]
Of course, `angularCompilerOptions` changes quite often.

**Comment by Toxicable** [comment]
I disagree with this. 
In my opinion the compiler is a low level API that shouldn't be used directly by devs, it should be used indirectly through tools such as `ngc` or `AngularCompilerPlugin` for webpack, or even the upcoming Bazel integrations. 
It changes often and being restricted by making it public will slow down development on it.

**Comment by dominique-mueller** [comment]
@Toxicable I'm not sure I understand your point. `ngc` is available via command line, which also means it is part of the public API of `@angular/compiler-cli`. However, `ngc` does nothing more but calling the `main` function, passing in the arguments it received. Thus, if `ngc` is public API so should be the `main` function (in my opinion). A breaking change in the `main` function would also result in a breaking change in `ngc`. They're the same. So why not export the `main` function as well?

**Comment by xiaoxiangmoe** [comment]
I hope to write plugins for other packaging tools, such as using parcel or vite. 
At this time, I need to translate the ts code with decorator into js, and then compile parcel or vite.
If the compiler api can be opened and provide appropriate documentation, it will be convenient for us to use.

**Comment by alxhub** [comment]
In general, our choice not to have a public API for `@angular/compiler-cli` is deliberate, and we have no plans to offer one at this stage.
