### ISSUE TITLE
[Forms] sent object through FormControl with value property instead of value

### ISSUE THREAD

**Issue by masoud-moghini** [angular/angular#20426]
hey 
say that I have a form group like this 
```
this.form=fb.group({
      _id:new FormControl(),
      ...
      province:new FormControl({value:' ',disabled:true},[Validators.required]),
      city:new FormControl({value:' ',disabled:true},Validators.required),
      county:new FormControl({value:' ',disabled:true},Validators.required),
      installment_count:new FormControl({value:0}),
       ...
```

now I expect that if I don't modify the value of installment_count anywhere in the code ,empty string would be sent .while the result is as shown bellow:
![image](https://user-images.githubusercontent.com/17137345/32788239-ee668578-c96d-11e7-8a85-8ce0cd11f7af.png)
 as you see,an object sent with value property set to empty instead of just empty.

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
