### ISSUE TITLE
Issues with angular 5

### ISSUE THREAD

**Issue by lakinmohapatra** [angular/angular#20420]
Its showing "Cant find sock.js on safari" . Seems like a webpack issue .  Also its showing reference issue . ReferenceError: Can't find variable: overlayDiv  Please help

Quite dissapointed to see the result in safari.
Seems like not tested well .

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/8400

**Comment by lakinmohapatra** [comment]
When its going to be fixed . 
Is angular 4 pretty much stable ?

**Comment by trotyl** [comment]
It's nothing to do with Angular, it's an Angular CLI issue.

**Comment by jasonaden** [comment]
Closing as duplicate.
