### ISSUE TITLE
Update shrinkwrap readme

### ISSUE THREAD

**Issue by vicb** [angular/angular#2043]
```
- updating to master,
- rm node_modules/
- npm install,
- update the pkg.json for minichain as described in the readme (even though the tsd project is untouched),
- rm the 2 minichain folders (related to the previous step) - NOT mentioned in the readme
```

2 last steps are required even if not updating tsd

/cc @juliemr

**Comment by juliemr** [comment]
Also, the path is wrong. Right now it's
`node_modules/ts2dart/node_modules/tsd/node_modules/minitable/package.json`
should be
`node_modules/tsd/node_modules/minitable/package.json`

**Comment by vicb** [comment]
Also fs_events on Linux

**Comment by IgorMinar** [comment]
please take a look at #2092
