### ISSUE TITLE
[angular-cli]: flat module bundler should emit and not write

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#20434]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When opting in for **flatModuleOutFile** the `compiler-cli` will write the `metadata.json` bundle instead of passing it to the actual compiler host it for writing.

See [code](https://github.com/angular/angular/blob/master/packages/compiler-cli/src/metadata/bundle_index_host.ts#L53)

## Expected behavior

Bundled `metadata.json` should be passed for writing in the original compiler host.

## What is the motivation / use case for changing the behavior?

Host's might have logic or some other transformation done before writing the file.
This can be path renaming, etc..

`@ngtools/webpack` does not write to disk but in that case it will identify it and write.

## Environment

Angular version: 5.0.1

**Comment by JoostK** [comment]
Fixed in #23054.
