### ISSUE TITLE
Support `emitEvent` option in FormGroup and FormArray APIs

### ISSUE THREAD

**Issue by bitworking** [angular/angular#20439]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have a dynamic (reactive) form and use methods like setControl and addControl. If I use these methods everytime a form valueChanges event is triggered which in my situation is very bad because I cannot differentiate it from a "real" form value change. 

## Expected behavior
I need to set the option "emitEvent: false" in the method calls for addControl and setControl.

## What is the motivation / use case for changing the behavior?
I need to differentiate a value change from a form control change.

## Environment

<pre><code>
Angular version: 5.0.1

**Comment by Airblader** [comment]
I'm having the same issue in a form that is set up to auto-submit using `valueChanges.debounceTime`. It has a dynamic list of controls and using `setControl` to replace them triggers `valueChanges`, causing an infinite submission loop.

**Comment by Airblader** [comment]
By the way, my current workaround is to not subscribe to `form$.valueChanges`, but instead use my own Observable that I trigger from all the change handlers of the form controls. I only have (a list of) two dropdowns, so that's feasible. It'd still be better to tell `setControl` not to emit events.

**Comment by ottosson** [comment]
I'm listening to form changes and want to add a control when a specific condition in the form is met, which triggers a new change event in the form which is now an infinite recursion.

Should add/remove controls even trigger the changeEvent? Or should there be a different kind of event emitter for control value changes?

**Comment by Airblader** [comment]
I think the consistent behavior is what this issue is requesting, which is an option to suppress the events. That's how other parts of the API work as well.

**Comment by meriturva** [comment]
We are on same issue and `emitEvent` options is the only clean solution on our side!

**Comment by hatem20** [comment]
i have the same issue in angular 6 and can't find any workaround

**Comment by eramirezprotec** [comment]
Same issue here...

**Comment by vuquangtam** [comment]
> 
> 
> I cannot believe I banged my head against the wall for the last hour and didn't think about this from the start:
> 
> ```
>   this.frm.valueChanges
>     .pipe(
>       filter(_ => !this.pauseForm)
>     )
>     .subscribe(
>       (v) => {
>         // DO STUFF
>       }
>     );
> ```
> 
> Then, whenever I need to use setControl/addControl, I first do `this.pauseForm = true;` and after set/addControll I do `this.pauseForm = false;`
> This looks a bit ugly, I'm sure... but I'm no RxJs expert, maybe some other operators can be leveraged to a prettier solution?
> 
> Hopefully, this issue will get some attention... it's been over 1 year 😄

Also use this workaround :D. Make my code look ugly 👎 but this is only way

**Comment by sahrmann** [comment]
I really do not get why this function is not implemented yet. It would make working with dynamic forms much easier, i.e., changes of certain values trigger removal or addition of certain controls.

**Comment by MaxKless** [comment]
Still no updates on this front, this feature would save me from an ugly workaround.

**Comment by patrykp57** [comment]
Looking forward for this option. It might be helpful when we are adding multiple controls in same form group depending on emitted value.

**Comment by lsimonis** [comment]
Any chance this will be implemented soon?

**Comment by JACrosman** [comment]
This would be extremely useful.

**Comment by johnsonb2** [comment]
I just discovered this issue today. It's possible to stop the infinite recursion by either piping `valueChanges` into `distinctUntilChanged` or by testing if the value needs to be set, but in either case there is still an unnecessary 2nd event emission.

**Comment by Luperco** [comment]
I don't believe distinctUntilChanged  will help. I have to check but if you add a new control, the value will change (new field is added to the form value) unless the distinctUntilChanged is ignoring the null values.

**Comment by JbRezidu** [comment]
Hi, having the same issue here, option "emitEvent: false" on addControl would be really perfect :)

**Comment by AndrewKushnir** [comment]
Hi, quick update on this feature request: we plan to look into adding options to FormGroup and FormArray APIs that rely on `updateValueAndValidity` method. There is no ETA at this moment, but we'll keep this thread updated once ETA (or any other info) is available. Thank you.

**Comment by AndrewKushnir** [comment]
Closing this ticket since corresponding PR #31031 (that adds the `emitEvent` config option) is merged. The changes will be available in the next major release (v12) in a few weeks.

Thanks everyone for the discussion and feedback, and thanks @MikeJerred for implementing this feature 👍
