### ISSUE TITLE
Keyframes are removed after animation is complete.

### ISSUE THREAD

**Issue by lucifer-AM** [angular/angular#20445]
component.ts:-

`@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css'],
  animations: [

    trigger('completeProgressBar', [
      transition('void=>*', [

        //query('.progress .progress-right .progress-bar', style({ transform:'rotate(0deg)' }), { optional: true }),

        query('.progress .progress-right .progress-bar', stagger('300ms', [
          animate('1s ease-in', keyframes([
            style({ transform: 'rotate(0deg)' }),
            style({ transform: 'rotate(180deg)' })
          ]))]), { optional: true }),
        query('.progress.blue .progress-left .progress-bar', stagger('300ms', [
          animate('1s ease-in', keyframes([
            style({ transform: 'rotate(0deg)' }),
            style({ transform: 'rotate(60deg)' })
          ]))]), { optional: true })
      ])
    ]),
    trigger('inProgressProgressBar', [
      transition('* => *', [

        query('', style({ opacity: 0 }), { optional: true }),

        query(':enter', stagger('300ms', [
          animate('1s ease-in', keyframes([
            style({ opacity: 0, transform: 'translateY(-75%)', offset: 0 }),
            style({ opacity: .5, transform: 'translateY(35px)', offset: 0.3 }),
            style({ opacity: 1, transform: 'translateY(0)', offset: 1.0 }),
          ]))]), { optional: true })
      ])
    ]),
    trigger('pendingProgressBar', [
      transition('* => *', [

        query('', style({ opacity: 0 }), { optional: true }),

        query(':enter', stagger('300ms', [
          animate('1s ease-in', keyframes([
            style({ opacity: 0, transform: 'translateY(-75%)', offset: 0 }),
            style({ opacity: .5, transform: 'translateY(35px)', offset: 0.3 }),
            style({ opacity: 1, transform: 'translateY(0)', offset: 1.0 }),
          ]))]), { optional: true })
      ])
    ])

  ]
})`

component.html:-
`<div class="col-sm-4" style="padding-left:5%;" @completeProgressBar">
      <div class="progress blue">
          <span class="progress-left"><span class="progress-bar"></span></span>
          <span class="progress-right"><span class="progress-bar"></span></span>
          <div class="progress-value">60%</div>
      </div>
</div>`

component.css:-
`.progress {
    width: 150px;
    height: 150px;
    line-height: 150px;
    background: none;
    margin: 0 auto;
    box-shadow: none;
    position: relative;
}

.progress:after {
    content: "";
    width: 100%;
    height: 100%;
    border-radius: 50%;
    border: 4px solid #ddd;
    position: absolute;
    top: 0;
    left: 0;
}

.progress>span {
    width: 50%;
    height: 100%;
    overflow: hidden;
    position: absolute;
    top: 0;
    z-index: 1;
}

.progress .progress-left {
    left: 0;
}

.progress .progress-bar {
    width: 100%;
    height: 100%;
    background: none;
    border-width: 4px;
    border-style: solid;
    position: absolute;
    top: 0;
}

.progress .progress-left .progress-bar {
    left: 100%;
    border-top-right-radius: 80px;
    border-bottom-right-radius: 80px;
    border-left: 0;
    -webkit-transform-origin: center left;
    transform-origin: center left;
}

.progress .progress-right {
    right: 0;
}

.progress .progress-right .progress-bar {
    left: -100%;
    border-top-left-radius: 80px;
    border-bottom-left-radius: 80px;
    border-right: 0;
    -webkit-transform-origin: center right;
    transform-origin: center right;
    animation: loading-1 1.8s linear forwards;
}

.progress .progress-value {
    width: 90%;
    height: 90%;
    border-radius: 50%;
    font-size: 24px;
    color: rgba(124, 124, 124, 0.4);
    line-height: 135px;
    text-align: center;
    position: absolute;
    top: 5%;
    left: 5%;
}

.progress.blue .progress-bar {
    border-color: #049dff;
}

.progress.blue .progress-left .progress-bar {
    /* animation: loading-2 1.5s linear forwards 1.8s; */
}`

Currently I am able to see the animation. But after the animation time is over the keyframes are not visible in inspector.

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
