### ISSUE TITLE
ViewEncapsulation.Emulated/ViewEncapsulation.Native behave differently on child components

### ISSUE THREAD

**Issue by SteveVanOpstal** [angular/angular#20449]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In `ViewEncapsulation.Native` mode: parent `styles` are applied to the parent and child components.
In `ViewEncapsulation.Emulated` mode: parent `styles` are applied only to the parent component.

## Expected behavior

As `ViewEncapsulation.Emulated` is an emulated version of `ViewEncapsulation.Native`, I expect both modes to have the same behaviour.
So I expect in both modes that the `CSS` is applied to both parent and child components.

## Minimal reproduction of the problem with instructions
The example and code should be self explaining:
http://plnkr.co/edit/DoEdigJs54QRl7d2Qa9c

## Environment

<pre><code>
Angular version: 5.0.1

But I've seen the issue in earlier versions of Angular too.

Browser:
- [x] Chrome (desktop) version 62.0.3202.62 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by frederikprijck** [comment]
@SteveVanOpstal , Fwiw: According to this PR: https://github.com/angular/angular/pull/10997/commits/ae28e7a1be03aa7b8358e6702edf1a43c86d8b4c the result is expected and it doesn't look like a bug.

**Comment by frederikprijck** [comment]
Apparently the behavior is only different when u add a emulated directive inside a native one, which probably isn't a supported use case I guess?

**Comment by SteveVanOpstal** [comment]
I've created a plunker (http://plnkr.co/edit/6x4d8eAZMNo6nmgOzUuB?p=preview) which explicitely states that the child component is the same ViewEncapsulation as their parent. This results in the behaviour that is described in the docs (CSS is not applied to the child).
However, I expected the child to take on the ViewEncapsulation of the parent by default (which is not the case).

**Comment by vicb** [comment]
> The example and code should be self explaining:

We have 1800 bugs opened - it really helps to add explanation.

**Comment by SteveVanOpstal** [comment]
I made the assumption that a child component would use the same `ViewEncapsulation` of the parent.
So if you would set the parent to `Native` that automatically the child will also be `Native`.
The docs however https://angular.io/api/core/Component#encapsulation clearly states that `Emulated` is always the default

**Comment by SteveVanOpstal** [comment]
The actual issue is that when a parent component has `ViewEncapsulation.Native` and the child component has `ViewEncapsulation.Emulated`. The styles of the parent, in the case of the plunker `:host p { color: blue; }`, will make the child blue. In case both paren and child are `Emulated` the blue color will not be performed on the child

I changed the plunker to be a bit more readable: http://plnkr.co/edit/G4i6T3d03H12fs8d1FVJ?p=info

**Comment by AndrewKushnir** [comment]
Closing this ticket since ViewEncapsulation.Native is deprecated and will be removed in v11 (see [deprecations guide](https://angular.io/guide/deprecations)).
