### ISSUE TITLE
DatePipe: parsing MySQL datetime format for Safari

### ISSUE THREAD

**Issue by aristocr2t** [angular/angular#20443]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Safari browser can`t transform MySQL date through DatePipe. When I create new project I should insert this code to fix it (./node_modules/@angular/common/esm5/common.js:4392):
```typescript
<...>
else if ("string" === typeof value && /^(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})$/.test(value)) {
    /**
     * For MySQL datetime format
     */
    var _a = value.split(/[^0-9]/).map(function (val) { return parseInt(val, 10); }), y = _a[0], M = _a[1], d = _a[2], h = _a[3], m = _a[4], s = _a[5];
    date = new Date(y, M - 1, d, h, m, s);
}
<...>
```
## Expected behavior

I need to parse MySQL date for Safari.

## What is the motivation / use case for changing the behavior?

Safari browser doesn`t transform MySQL datetime format.

## Environment
<pre><code>Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [x] Safari (iOS) version 11
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:
- Node version: 6.11.3  
- Platform: Windows 
</code></pre>

**Comment by vicb** [comment]
@Aristocr2t I have marked as a feature request. You are trying to use the pipe in a way that is not intended.

If the date comes from server side you can probably transform it server side or create you own pipe client side.

**Comment by awais2080** [comment]
any body found solution for this

**Comment by ChaitanyaBabar** [comment]
Hi @vicb ,

CC: @aristocr2t 
Date string with time zone information breaks the date pipe.

For the date string as `'2020-04-22T04:41:56.650+530' ` i.e. date string with timezone is throwing the Error as **Error: InvalidPipeArgument: '2020-04-22T04:41:56.650+530' for pipe 'DatePipe'**.

But if we remove the time-zone information as pass date string as `'2020-04-22T04:41:56.650' `
the date pipe works fine.

Please find the stackblitiz example [here](https://stackblitz.com/edit/angular-date-pipe-with-timezone-string).

Is this same issue or different ?
