### ISSUE TITLE
How to don't call a pipe twice ?

### ISSUE THREAD

**Issue by amineparis** [angular/angular#20444]
I need to do the folowing : 
`<ng-container *ngIf="(project.actions | actionType : ActionType.Corrective).length">`

and just some lines after (**same component**) :
` <tr *ngFor="let action of project.actions | actionType : ActionType.Corrective">`

Is Angular optimised to call the pipe only once in this case ? If not, How to handle this to make pipe executed only once ?

**Comment by msarsha** [comment]
If the pipe is being used twice - it will get executed twice (even more in dev mode).

**Comment by amineparis** [comment]
What does angular suggest in this case to not be obliged to call it twice ?

**Comment by mlc-mlapis** [comment]
@amineparis ... there are basically two types of pipes ... `pupe` and `impure`. Impure pipes are called in every CD cycle ... `json` pipe is an example of it. Pure pipes are called only when `ngOnChanges` hook detects changes. That is all.

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
