### ISSUE TITLE
Typos in Documentation 

### ISSUE THREAD

**Issue by gatzsche** [angular/angular#20447]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

You are using prefix `my` in description and `app` in code samples, e.g. [here](https://angular.io/guide/structural-directives#templateref-and-viewcontainerref):

In the description you are using **myUnless**:
> The directive consumer expects to bind a true/false condition to `[myUnless]`.

In the code sample you are using **appUnless**:

> `@Input() set appUnless(condition: boolean) {`
>   `....`

## Expected behavior

Please go through the entire documentation, search for 'my([A-Z]+)' and replace it by 'app(\1)'

**Comment by trotyl** [comment]
Will be fixed by https://github.com/angular/angular/pull/19778

**Comment by gkalpak** [comment]
@trotyl, I don't think this particular error will. Did I miss something?

**Comment by trotyl** [comment]
@gkalpak You're right, indeed that one has not been included.

**Comment by hartraft** [comment]
This has been [committed](https://github.com/angular/angular/commit/77ef52799372805608be26c72cb60faba7f826b5) on the master, can it be closed now?
