### ISSUE TITLE
Semicolon should be escaped in Matrix Parameter

### ISSUE THREAD

**Issue by yozo1984** [angular/angular#20455]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When using matrix parameter in router.navigate(), ";" is not escaped. When trying to using the same link to go back to the page again, the browser (chrome) did not know it's part of the parameter and parsed as a separate one.

## Expected behavior

semicolon is correctly escaped.

## Minimal reproduction of the problem with instructions

1. `router.navigate(['./', {test: ';query'}]);  --> <current url>;test=;query`
1. Use the link to try to go back to the page
1. Browser cannot understand the ';' and incorrectly thinks there are two matrix parameters. Result parsed become: `{test: '', query: ''}`

## What is the motivation / use case for changing the behavior?

To allow using ';' in the matrix parameter without the need of manually encode each value.

## Environment

<pre><code>
Angular version: 5.0.1 HEAD

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by jahumes** [comment]
@jasonaden Any concerns with me making a pull request for this?

**Comment by trotyl** [comment]
@jahumes Should been covered by #22337.

**Comment by dariobraun** [comment]
@trotyl has this issue been fixed and can be closed?

**Comment by atscott** [comment]
This issue appears to be fixed. Special characters in matrix params are encoded correctly. https://stackblitz.com/edit/angular-ivy-4hl3sk?file=src%2Fapp%2Fhello.component.ts
