### ISSUE TITLE
Confused behavior with async pipe

### ISSUE THREAD

**Issue by djnaumov** [angular/angular#20453]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior

I will try use async pipe for show/hide some waiting message.

**app.component.html**
```
<ng-template #isWait>
	<h1>Please wait</h1>
</ng-template>

<div *ngIf="wait | async; else isWait">
	<hello name="{{ name }}"></hello>

	<p>
		Start editing to see some magic happen :)
	</p>

</div>

<button (click)="toggle()">Toggle</button>

<!-- Doesn't change -->
<div style="margin:1rem;">
	Doesn't change here
	<span style="color:red;">Value is {{wait | async}}</span>
  (AppComponent)
</div>
```
**app.component.ts**
```
@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  name: string = 'Angular 5';
  wait: Observable<boolean>;

  constructor(public waitService: WaitService) {
    this.wait = this.waitService.wait;
  }

  toggle() {
    this.waitService.toggle();
  }
}
```

**wait.service.ts**
```
export class WaitService {
  wait: Observable<boolean>;
  private _wait: boolean = false;
  private _onChange: EventEmitter<boolean> = new EventEmitter();

  constructor() {
    this.wait = Observable.create((obs: any) => {
      obs.next(this._wait);
      this._onChange.subscribe((w: boolean) => {
        if (this._wait !== w) {
          this._wait = w;
          obs.next(this._wait);
        }
      });
    });
  }

  toggle() {
    this._onChange.emit(!this._wait);
  }
}
```

I have WaitService, it includes wait property (Observable<boolean>) and method Toggle for switching wait.
When I try toggle **wait**, it works in one case, but doesn't work for each others as I expected.
So, It confused me and I will try figure out it.

Example: https://stackblitz.com/edit/angular-fwghfj

If you click on Toggle nothing happen with wait message, but subscription in Wait2Component will be emitted.

After commented this subscription in [Wait2Component](https://stackblitz.com/edit/angular-fwghfj?file=app%2Fwait2.component.ts) , show and hide wait message will be work, but in other places **wait** still have no change.
```
//this.wait.subscribe(() => console.log("Wait2Component | wait was changed"));
```

## Expected behavior

Will be work for all cases.

## Environment

<pre><code>
Angular version: 5.0.0
</code></pre>

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
