### ISSUE TITLE
Router link loads child view into current child view

### ISSUE THREAD

**Issue by Sevensnake** [angular/angular#20457]
I have a component for my left side navigation. when I click on a new route it loads the child page into the current child page.  Using Angularcli 5.0
Typescript version 2.4.2

for example.
`   <a [ngClass]="classTabA"  [routerLink]="['/Home/index/CA']">
                                <span class="glyphicon glyphicon-arrow-right" [hidden]="!selected"></span> Part A: </a>
                        </li>
                        <li>
                            <a [ngClass]="classTabB" [routerLink]="['/Home/index/CB']">
                                <span class="glyphicon glyphicon-arrow-right" [hidden]="selected"></span> Part B:</a>`

My ng main Module routing
`import {NgModule, ModuleWithProviders} from '@angular/core';
// Global Routing // 
//#############
import { Routes, RouterModule, CanActivate, Router } from '@angular/router';
import { mainComponent } from './dcomponent'
export const appRoutes: Routes = [
  { path: '', redirectTo: 'Home/index', pathMatch: 'full'},
  { path: 'Home/index', component: mainComponent },
  { path: 'Home/index/A', loadChildren: './a-table/atable.module#ATableModule'},
  { path: 'Home/index/B', loadChildren: './b-table/btable.module#BtableModule'},

];
NgModule({ 
    imports: [RouterModule.forRoot(appRoutes)],
    exports: [RouterModule]
})
export const routing: ModuleWithProviders =
    RouterModule.forRoot(appRoutes);    `

children for b
`import { NgModule }     from '@angular/core';
import { Routes,
         RouterModule } from '@angular/router';

 import { ColumnBTableComponent } from './column-b-table.component';
const routes: Routes = [
  { path: '',
    component: ColumnBTableComponent,
    children: [
      { path: '/Home/index/B',  component: ColumnBTableComponent }
    ]
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class BTableRoutingModule {}`
`import { ColumnATableComponent } from './column-b-table.component';
const routes: Routes = [
  { path: '',
    component: ColumnATableComponent,
    children: [
      { path: '/Home/index/S',  component: ColumnATableComponent }
    ]
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class AtableRoutingModule {}`

for example if I navigate from b to A. A shows up but B shows up at the bottom of the page. 
This just started to happen. any suggestions

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
