### ISSUE TITLE
Change Detection error (ExpressionChangedAfterItHasBeenCheckedError): Angular does not compare objects during checkNoChanges pass

### ISSUE THREAD

**Issue by gilbertogwa** [angular/angular#20450]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I had a problem with Change Detection when I set up an object in an @Input property of a directive. I have identified that Angular warns only when the value is a primitive type (number, string, etc), for objects the error is not reported. The CD became infinite after I applied a jquery transformation to the element where the directive was applied. The problem is that the loop has crashed the browser.

* Is it possible to put a lock in this situation (for example, ignore on 1000 errors)?
* Is it intentional not to report change detection error when value is object?

## Expected behavior

As expected behavior, I would like Angular to warn of CD errors for objects as well. Well, this is what I would like, but I do not know if there is any architectural or functional decision for this.
My problem was with jquery.select2, but there might be other types of libraries that would cause infinite error. So I wish there was a lock, at least from the CD when there was an X amount fired at a given time.

## Minimal reproduction of the problem with instructions

See following link to reproduce error: https://stackblitz.com/edit/angular-select2-infinite-cd

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [X] Chrome (desktop) version 62.0.3202.89
 
For Tooling issues:
- Node version: v7.8.0
- Platform:  Windows 10

**Comment by dylhunn** [comment]
Working as intended.
