### ISSUE TITLE
lazy loading routing child view loads with another child view

### ISSUE THREAD

**Issue by Sevensnake** [angular/angular#20451]
Having this problem now also.
Routing using lazy load modules. routeing the current view I left to enter a new view the old view loads at the bottom. This just starter happening with angular5. Not sure why. very hard to debug.

` <a   [routerLink]="['route/page']">`
this just start happening out of no where. not sure why.

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by Sevensnake** [comment]
`import {NgModule, ModuleWithProviders} from '@angular/core';
// Global Routing // 
//#############
import { Routes, RouterModule, CanActivate, Router } from '@angular/router';
import { DashboardComponent } from './dashboard/dashboard.component'
export const appRoutes: Routes = [
  { path: '', redirectTo: 'Home/index', pathMatch: 'full'},
  { path: 'Home/index', component: boardComponent },
  { path: 'Home/index/ColumnA', loadChildren: './table.module#ATableModule'},
  { path: 'Home/index/ColumnB', loadChildren: './btable.module#BtableModule'},
  { path: 'Home/index/ColumnC', loadChildren: './ctable.module#CtableModule'},
  { path: 'Home/index/ColumnD', loadChildren: './dtable.module#DtableModule'},
  { path: 'Home/index/ColumnE', loadChildren: './etable.module#EtableModule'}
];
NgModule({ 
    imports: [RouterModule.forRoot(appRoutes)],
    exports: [RouterModule]
})
export const routing: ModuleWithProviders =
    RouterModule.forRoot(appRoutes);    `

` <ul class="blocklist text-left">
                        <li>
                            <a [ngClass]="classTabA" [routerLink]="['/Home/index/ColumnA']">
                                <span class="glyphicon glyphicon-arrow-right" [hidden]="!selected"></span> Part A: General Information</a>
                        </li>
                        <li>
                            <a [ngClass]="classTabB" [routerLink]="['/Home/index/ColumnB']">
                                <span class="glyphicon glyphicon-arrow-right" [hidden]="selected"></span> Part B: Information About the Fund</a>
                        </li>
                        <li>
                            <a [ngClass]="classTabC" [routerLink]="['/Home/index/ColumnC']">
                                <span class="glyphicon glyphicon-arrow-right" [hidden]="!classTabC"></span> Part C: Schedule of Portfolio Investments</a>

                        </li>
                        <li>
                            <a [ngClass]="classTabD" [routerLink]="['/Home/index/ColumnD']">
                                <span class="glyphicon glyphicon-arrow-right" [hidden]="!classTabD"></span>Part D: Miscellaneous Securities</a>
                        </li>
                        <li>
                            <a [ngClass]="classTabE" [routerLink]="['/Home/index/ColumnE']">
                                <span class="glyphicon glyphicon-arrow-right" [hidden]="!classTabE"></span> Part E: Explanatory Notes (if any)</a>
                        </li>`
` "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "github:angular/material2-builds",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",`
dev `dependies"devDependencies": {
    "@angular/cli": "^1.5.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",`

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
