### ISSUE TITLE
Should angular-in-memory-web-api use the @angular/http package

### ISSUE THREAD

**Issue by GoshaFighten** [angular/angular#20465]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The `angular-in-memory-web-api` package uses the `@angular/http` module.

## Expected behavior
The `angular-in-memory-web-api` package depends on the `@angular/common/http` module.

## Minimal reproduction of the problem with instructions
Just add the `angular-in-memory-web-api` module to an Angular project.

## What is the motivation / use case for changing the behavior?
According to [Version 5.0.0 of Angular Now Available](https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced), I need to use the `@angular/common/http` module instead.

## Environment

<pre><code>
Angular version: 5.0.1
Angular CLI: 1.5.0
Node: 8.1.4
OS: win32 x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.3
typescript: 2.4.2
webpack: 3.8.1

</code></pre>

**Comment by trotyl** [comment]
Please have a look at the [CHANGELOG](https://github.com/angular/in-memory-web-api/blob/master/CHANGELOG.md), `@angular/common/http` support has been added long time ago.

**Comment by gkalpak** [comment]
Interestingly, it seems to [still peer-depend][1] on `@angular/http`. Maybe an ommission from when switching to `@angular/common/http`. If this is indeed still an issue in the latest version, please open a bug report on the [in-memory-web-api repo][2].

[1]: https://github.com/angular/in-memory-web-api/blob/7fc1ca042b49e59e1efccc43bb3e3c2f4550bd8e/package.json#L33
[2]: https://github.com/angular/in-memory-web-api
