### ISSUE TITLE
Angular universal with asp.net mvc 5.0

### ISSUE THREAD

**Issue by NagarajMani** [angular/angular#20476]
Anyone working with angular 5.0-universal with Asp.net MVC 5.0 combination ?
note: not asp.net core 2.0

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Please don't open issues for this kind of questions. Thank you.
