### ISSUE TITLE
Resolve won't be executed at a redirectTo Route configuration

### ISSUE THREAD

**Issue by Suizi11** [angular/angular#20475]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If I have a resolver in my route configuration, but no component or children, I need the "redirectTo" property as a minimum. With the redirect, which fits even my use case, the resolver won't be called.

## Expected behavior

Resolver gets called of the "old" route.

## Minimal reproduction of the problem with instructions

Configure a route like the following:
`{
    path: 'oldPath/:id',
    resolve: {
      redirectTo: 'newPath',
      resolvedData: ResolverService
    }
  }`

## What is the motivation / use case for changing the behavior?

In my old web-app, I've a path like "/oldPath/:id". Now i want switch to angular and use the router module. There the path is represented as another string, let's say "/newPath".
For the old path i need a resolver, for the new one not. I solved this with a redirect, from the oldPath to the newPath, the :id is only relevant for the old one. But than, the resolver won't be called (there I need the :id).

## Environment

<pre><code>
Angular version: 4.4.6

</code></pre>

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
