### ISSUE TITLE
Proposal: computed (aka memoized) properties

### ISSUE THREAD

**Issue by anjmao** [angular/angular#20472]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
There is no real computed properties. Getters are bad for performance. Example https://plnkr.co/edit/TQMQFb?p=preview

## Expected behavior
To be able to use computed properties as in vue or mobx

## What is the motivation / use case for changing the behavior?
My proposal is to make change detection smarter by adding computed properties like in mobx or vue.

```ts
import {Computed, Reactive} from '@angular/core';
...

class MyCmp {
  age = 69;

  @Reactive firstName = 'hello';
  @Reactive lastName = 'angular';
  @Computed get fullName() {
     console.log('recomputed');
     return `${this.firstName} ${this.lastName}`;
  }
}
```

This will allow to have computed get property and be able to cache it, so it is computed only when needed. Currently this is not possible and getter is recomputed a lot of times, especially if using default change detection.

**Comment by Toxicable** [comment]
In your example fullName is an impure function, therefore there is no way to track when the cached value needs to be invalidated.

**Comment by Toxicable** [comment]
Furthermore, if you were to replace your getter with a pure function then you'd be able to compare args to know when to refresh the cached value, so you'd have something that looks like:
```
  let valueCache = null;
  let argsCache = [];
  descriptor.value = function wrapper(...args) {
    if(arraysContainSameItems(args, argsCache)){
      return valueCache;
    }
    argsCache = args;   

    const result = fn.call(this, ...args);
    valueCache = result;
    return result;
  };
```
But there's a pretty big issue here, the `arraysContainSameItems` fn, running that is probably more expensive than just calling your function in the first place.
Since args are passed in as an array you cant do this by object ref here either

---
Conclusion:
Will this work with a Decorator? In my opinion: no.
Could you cache this value somewhere else? yes, ngrx would be a prefect fit here

**Comment by Toxicable** [comment]
One more small thing, small operations aren't as slow as you might think
https://jsperf.com/is-js-slow
on my machine I got ~1billion operations/s (~1ns per op) on both tests, therefore showing that a few hundred extra checks on your app really wont be slowing it down

**Comment by anjmao** [comment]
VueJs example

```html
<div id="example">
  <p>Original message: "{{ message }}"</p>
  <p>Computed reversed message: "{{ reversedMessage }}"</p>
</div>
```

```js
var vm = new Vue({
  el: '#example',
  data: {
    message: 'Hello'
  },
  computed: {
    // a computed getter
    reversedMessage: function () {
      // `this` points to the vm instance
      return this.message.split('').reverse().join('')
    }
  }
})
```

In vue computed property is cached based on its dependencies, so it messages value changes when reversedMessage is recalculated. In angular it can work the same way by building dependencies try for properties marked with `@Computed` decorator.

**Comment by anjmao** [comment]
@Toxicable In real word applications depending on data you can get big performance decrease for common array operations like these:

```js
@computed get total(): number {
   return this.reportData.reduce((memo, obj: any) => memo + obj.value, 0)
}
```

```js
@computed get pages() {
    const groups = _.groupBy(this.widgetGroups, 'PageNo');
    const pages = [];
    for (let key in groups) {
        pages.push({
            pageNumber: parseInt(key),
            widgetGroups: groups[key]
        });
    }
    return pages;
}
```

**Comment by Toxicable** [comment]
>In angular it can work the same way by building dependencies try for properties marked with @Computed decorator.

How?
As I stated above there is no way for Angular to "magically" track the fields that an arbitrary function depends on.

It sounds like you need to look at using Angular's current API's such as OnPush
I see no reason why these examples need getters specifically, all of them can be tracked by ref which is massively faster than other forms of tracking changes

**Comment by anjmao** [comment]
Right, now I see that in VueJs all properties in data object are reactive, this is how they know if reactive property is used :) So it will be possible by having reactive and computed decorators:

```js
import {Computed, Reactive} from '@angular/core';
...

class MyCmp {
  simpleProperty = 'hah';

  @Reactive firstName = 'hello';
  @Reactive lastName = 'angular';
  @Computed get fullName() {
     return `${this.firstName} ${this.lastName}`;
  }
}
```

BTW: using OnPush will not help here, you will still get a lot of recalculations on every event inside you component. i.e input change, click...

**Comment by Toxicable** [comment]
>`@Reactive firstName = 'hello';`

This is not what we want
`rxjs` already provide Observables which already handle reactivity for us.

>BTW: using OnPush will not help here, you will still get a lot of recalculations on every event inside you component. i.e input change, click...

You must misunderstand OnPush.
It's all based of @Input of components and object refs, therefore using Reactive immutable data yields very high perf, I would suggest doing some more reading on OnPush.

**Comment by anjmao** [comment]
Here is simple example https://plnkr.co/edit/X0koiv?p=preview using OnPush, open console to see what I was talking about. I know how on push and immutable data works. My point was what in mobx and vuejs computed getters are so easy and natural to use, because you can work with plain objects. probably you should try it to understand my feelings :D

**Comment by Toxicable** [comment]
@anjmao You're not actually taking advantage of OnPush here at all. this app would run exactly the same without it

**Comment by Toxicable** [comment]
Take a read through here https://github.com/mgechev/angular-performance-checklist

**Comment by alexzuza** [comment]
> BTW: using OnPush will not help here, you will still get a lot of recalculations on every event inside you component. i.e input change, click...

That's because angular calls markForCheck for such events. After that this component will be checked once

**Comment by anjmao** [comment]
@Toxicable I updated my example to better understand the idea https://plnkr.co/edit/X0koiv?p=preview how it looks if using with mobx. In this example totalSum is recalculated only if numbers array is changing. Do you know it if is possible to achieve this with angular only?

```js
class PageState {
  @observable numbers = [];
  
  @action addNumber(number) {
    this.numbers.push(number);
  }
  
  @computed get debug() {
    return this.numbers.join('+')
  }
  
  @computed get totalSum() {
    console.log('called totalSum');
    return this.numbers.reduce((c, n) => c + n, 0);
  }
}

@Component({
    selector: 'cities-page',
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: `
       <div *mobxAutorun>
        <input type="title" placeholder="Title" [(ngModel)]="title" /> <br />
        <input type="number" placeholder="Add number" [(ngModel)]="tmpNumber" />
        <button (click)="addNumber()">Add</button>
        <div>Total {{state.debug}} = {{state.totalSum}}</div>
       </div>
    `
})
export class CitiesPageComponent {
    state = new PageState();
    
    tmpNumber;
    title = 'title';
    
    addNumber() {
      if (!this.tmpNumber) return;
      this.state.addNumber(parseInt(this.tmpNumber));
      this.tmpNumber = null;
    }
}
```

**Comment by mlc-mlapis** [comment]
@anjmao ... to understand what you mean ... you click on the button `Add` and it runs the method `addNumber` ... which is directly related to `totalSum` that should be updated. ... all this means that you directly control the change.

Now you want that when you add a new number, something should recognize that this happened and as a reaction ... `totalSum` is updated also.

There was a try in history ... it was called `.observe()` and it was also implemented in browsers, but later ... in one year or so ... it was removed from the specs and removed also from browsers. Your example looks like that you want to do exactly the same as `.observe()`.

But the situation is more simpler ... because it is your code what makes the change ... you can also directly update `totalSum` in sync or you can use `observable/subscribe` pattern to do the same as async opperation or use `OnPush` ... but in each case it is probably a nonsense to use anything else then just simple property `totalSum` in the template and nothing else.

**Comment by ribizli** [comment]
I completely understand the issue what @anjmao has. But the responses I see doesn't solve or make invalid the problem.
Here is my similar issue:
I have a `boolean` array which is used as a model for a list of checkboxes. I'd like to disable some buttons if none of the checkboxes is checked. The convenient solution is to write a getter, which uses `.some` to determine if anything is selected. But this getter gets executed in every CD round for every binding (I can have several buttons). (In dev mode twice)

However vuejs cannot solve my problem either, since it doesn't watch array index access. I don't know if mobx does.

**Comment by anjmao** [comment]
Finally somebody understands this problem! thank you @ribizli  :)
@mlc-mlapis In my example with mobx totalSum getter is not recalculated if I change first input value `title`. The whole reason of having computed properties is to make state simpler by not syncing properties but instead allowing them to be calculated depending on you current state.

**Comment by mlc-mlapis** [comment]
@anjmao ... I understand what you mean ... but that `get` is just JS construct and will be called ... so how the code under `get` would look then.

**Comment by trotyl** [comment]
I guess it's something equivalent to [Aurelia's `computedFrom()`](http://aurelia.io/docs/binding/computed-properties#introduction) decorator.

**Comment by LinBoLen** [comment]
mobx seems have a ability to bind data between class. 
and mobx-angular can controll view render or destroy also detectchange.
https://github.com/mobxjs/mobx-angular/blob/master/lib/directives/mobx-autorun.directive.ts
mobx is so smart and, although I must write lots external code in template.

**Comment by anjmao** [comment]
@LinBoLen Yes, here is example https://plnkr.co/edit/EzumrI?p=preview how angular change detection becomes smarter and works completely without zone.js with support for computed properties.

Zone.js minified size 41kb.
Whole Mobx library minified size 56kb.

@mhevery Are there any estimates or priorities on implementing computed properties for angular? Maybe I can help with creating initial document for architectural design and comparison of other frameworks how they implement computed properties.

**Comment by ribizli** [comment]
Let me also share my quick idea how one could use MobX for computed properties:
https://stackblitz.com/edit/angular-dkuyjb
The basic idea is to install an `autorun` on the first getter call and cache the calculated value until `autorun` fires again. I'm curious what you guys think about this? It is just an additional decorator:
```typescript
function optimize(obj, key, desc) {
  const { get } = desc;
  let cached;
  let disposer;

  desc.get = function() {
    if (!disposer) {
      console.log('autorun init');
      disposer = autorun(() => {
        cached = get.call(this);
        console.log('cached: ' + cached);
      });
    }
    console.log('getter: ' + cached)
    return cached;
  };
}
```

**Comment by anjmao** [comment]
@ribizli In your example you added both computed and optimize decorators
```ts
  @optimize
  @observable
  get fullName() {
    console.log('compute')
    return [this.firstName, this.lastName].filter(Boolean).join(' ');
  }
```
In mobx you don't need any additional decorator, computed decorator is already doing all caching.

**Comment by ribizli** [comment]
@anjmao I need to kick-in observation with `autorun`, that's what my `@optimize` decorator is for. I don't use any `mobx-angular` directive in the template.

**Comment by BojanKogoj** [comment]
Any change? Mobx seems like a solution, but nothing about Angular 6 support, and it adds quite some size to bundle.

I would really like to see this in angular core.

**Comment by anjmao** [comment]
@BojanKogoj At least now you can use noop zone then you don't need to include zone.js and mobx bundle size is even smaller compared to zone.js, but keep in mind that some libraries my not work correctly if zone.js is disabled. 
```ts
platformBrowserDynamic()
    .bootstrapModule(AppModule, {
        ngZone: 'noop'
    });
```

**Comment by knaos** [comment]
What is the status of this? Is there a solution to this problem?

**Comment by marcelcremer** [comment]
I was switching between a ng and a vue project back and forth the last weeks and cannot believe, how natural the computed properties in vue work and that angular hasn't something similiar to offer.

In vue, you can easily do something like this(translated to ng terminology):

```javascript
@Input({
    default: ''
})
firstName: string;

@Input({
    default: '';
})
lastName: string;

get fullName() {
    return `${this.firstName} ${this.lastName}`;
}
```
which, despite the fact that we don't have default values in ng too, expresses exactly what we are doing.

However, in angular you have to do something like
```javascript
@Input()
set firstName(value: string)
{
    this._firstName = value || '';
    this.calculateFullName();
}
get firstName() {
    return this._firstName;
}
private _firstName: string;

@Input()
set lastName(value: string)
{
    this._lastName = value || '';
    this.calculateFullName();
}
get lastName() {
    return this._lastName;
}
private _lastName: string;

fullName: string = '';

calculateFullName() {
 this.fullName = `${this.firstName} ${this.lastName}`;
}
```

which is really ugly, error prone, bloated and no fun to use...

So +1 for computed Properties🎉

**Comment by fkleuver** [comment]
```ts
@Input({
    default: ''
})
firstName: string;

@Input({
    default: '';
})
lastName: string;

get fullName() {
    return `${this.firstName} ${this.lastName}`;
}
```

Still looks pretty verbose to me.

In aurelia 1 (5 years old by now):

```ts
@computedFrom(['firstName', 'lastName'])
get fullName() {
    return `${this.firstName} ${this.lastName}`;
}
```

In aurelia 2 (provided the browser supports proxies):

```ts
get fullName() {
    return `${this.firstName} ${this.lastName}`;
}
```

**Comment by motianjiao** [comment]
Please add computed properties to Angular core..

**Comment by williangd** [comment]
+1 for computed Properties

**Comment by maxime1992** [comment]
I might be missing something but "Computed properties" are really easy to achieve with observables, aren't they?

based on previous examples in this thread:

```ts
combineLatest(this.firstName$, this.lastName$).pipe(
  map(([firstName, lastName]) => `${firstName} ${lastName}`)
)
```

"But how would you do that for `Input`s?"

Just use [ngx-reactivetoolkit](https://www.npmjs.com/package/ngx-reactivetoolkit) which is a tiny wrapper. The ex above would turn into:

```ts
import { Changes } from 'ngx-reactivetoolkit';
import { combineLatest } from 'rxjs';
import { map } from 'rxjs/operators';

@Component({
  selector: 'my-component',
  template: `
    {{ fullName$ | async }}
  `,
})
export class HelloComponent implements OnChanges {
  @Input() public firstName: string;
  @Changes('firstName') public firstName$: Observable<string>;

  @Input() public lastName: string;
  @Changes('lastName') public lastName$: Observable<string>;

  public fullName$: Observable<string> = combineLatest(
    this.firstName$,
    this.lastName$
  ).pipe(map(([firstName, lastName]) => `${firstName} ${lastName}`));

  // needed for AoT
  ngOnChanges(): void {}
}
```

**Comment by marcelcremer** [comment]
If you have a hammer, everything looks like a nail...

While this might work, it has so much overhead that I don't even want to try it... IMHO it's a workaround for a missing feature in angular, which is the reason why some people think angular is overengineered.

Still props and <3 for posting your workaround attempt :)

**Comment by BojanKogoj** [comment]
I have a feeling they will never add this, because the _proper_ way is using onPush. If you use onPush computed properties aren't really that important.

**Comment by ribizli** [comment]
`OnPush` does indeed reduce the CD count of the component, but CD can still run even if `@Input` property hasn't changed: if a subsequent component needs CD for instance.

I also prefer the way to convert a property into a RxJS Subject (I use a utility function instead a decorator however). The only drawback is the bloated template due to `async`. (But this can be also simpler in Ivy, e.g.: https://www.youtube.com/watch?v=rz-rcaGXhGk)

**Comment by GlebkaF** [comment]
> I have a feeling they will never add this, because the proper way is using onPush. If you use onPush computed properties aren't really that important.

Do you mean that I could use plain get if I using onPush properly?
What do you mean "proper way"?

+1 for computed property btw, it feels so good in vue :heart:

**Comment by marcelcremer** [comment]
> > I have a feeling they will never add this, because the proper way is using onPush. If you use onPush computed properties aren't really that important.
> 
> Do you mean that I could use plain get if I using onPush properly?
> What do you mean "proper way"?
> 
> +1 for computed property btw, it feels so good in vue ❤️

I think what he means is, if you use "OnPush" Change Detection, the CD only runs when an Input property changes. Therefore, it doesn't matter if you call a function out of your template, because it'll be calculated only once anway and only recalculate, when an Input parameter changes.

However: As soon, as you have an impure Pipe (ngxTranslate for example, because Angular still has no option to do proper i18n without recompiling per language), the impure pipe also will not be recalculated as long as the input doesn't change (and therefore the term doesn't change, if the language configuration does).

There are other examples, but this might be a popular one.

Now some people might now say "Well, you need to use pre-calculated properties in your ngrx or ngxs state management", but this is really complex for simple applications and therefore also no viable option.

So I'm still voting for computed properties 👨‍🏫

**Comment by sarunint** [comment]
> the impure pipe also will not be recalculated as long as the input doesn't change

Impure pipes do recalculate on every CD cycle.

https://angular.io/guide/pipes#impure-pipes

**Comment by marcelcremer** [comment]
Yes, on every CD Cycle. So if you change the language in the translate service, no input parameter is altered and therefore no CD for the component is triggered. The Update will only happen, if the next "push" for the component was triggered :)

**Comment by ribizli** [comment]
with ivy our possibilities are limitless:
https://twitter.com/yurzui/status/1209948623028531203?s=20

**Comment by criskrzysiu** [comment]
@anjmao Please look at ngrx https://ngrx.io/guide/component-store. Combining it with @maxime1992 aproach would be perfect. 
Caching and ease of mainaining.  Bdw @maxime1992 thx for ngx-reactivetoolkit! I will actually ask to implement something like that into ngrx-component lib.

**Comment by maxime1992** [comment]
@criskrzysiu if you start using ngx-reactivetoolkit be aware of https://github.com/brechtbilliet/ngxReactiveToolkit/pull/28 which hasn't been merged and could introduce issues if you use it on more than 1 input in the same component

**Comment by mhevery** [comment]
What you are asking for can be implemented as follows.

```
class MyCmp {
  firstName = 'hello';
  lastName = 'angular';
  fullNameMemoizer = memoizer(() => firstName, () => lastName, (first, last) => `${this.firstName} ${this.lastName}`);
  @Computed get fullName() {
    return fullNameMemoizer();
  }
}

type GetterFns<A extends unknown[]> = {[K in keyof A]: () => A[K]};

function memoizer<ARGS extends unknown[], RET>(args: [...GetterFns<ARGS>, (...args: ARGS)=> RET]) {
    const fn = args.pop()! as (...args:ARGS)=>RET;
    let lastValue: RET;
    let values: ARGS;;
    return function(): RET {
        let inputChanged = false;
        if (!values) {
            values = args.slice() as any;
            inputChanged = true;
        }
        for(let i = 0; i<args.length; i++) {
            const getter = args[i] as () => unknown;
            let newValue = getter();
            if (values[i] !== newValue) {
                inputChanged = true;
                values[i] = newValue;
            }
        }
        return inputChanged ? lastValue = fn(...values) : lastValue;
    }
}
```

NOTE: For the example above I think the memorization would actually slow down the system performance.

The question is should the framework provide something like this out of the box. While I see the value of this I don't think that it is a high enough priority for us to be worked on any time soon. So I am going to leave the issue open, but don't expect a resolution any time soon.

**Comment by alyssamichelle** [comment]
+1 for computed properties 🔥

**Comment by theoklitosBam7** [comment]
+1 for computed properties

**Comment by jessicajaniuk** [comment]
Angular does not have a reactivity model that's fine-grained today, but it's something we're thinking about and interested in hearing about from the community.

**Comment by mickeyjohn** [comment]
another +1 for computed properties please.

**Comment by pkozlowski-opensource** [comment]
Since we are getting multiple issues / feature requests around computed properties, we've opened a canonical issue #47553 to track this use-case. Currently there is no exact solution / design, but we do acknowledge the use-cases and the need for such concept.
