### ISSUE TITLE
Feature: Adding Fastdom mechanism into Angular core and applicable libraries.

### ISSUE THREAD

**Issue by matthewharwood** [angular/angular#20471]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
**Problem:
["Escape hatch"](https://twitter.com/BenLesh/status/931280353783721984 ) components that allow raw DOM stuff have no batch/scheduling optimization for DOM Access.**

By batching DOM access we avoid unnecessary document reflows and speed up layout performance dramatically using mechanism like [FastDom](https://github.com/wilsonpage/fastdom). Libraries like `@angular/animations` or `@angular/cdk` and its directive's `cdkScrollable` and `cdkViewport` would get a significant perf boost by batching measures and mutations. I think the goal of this feature request is to integrate batching DOM access into cdk, animations, etc; libs in angular that require `zone.runOutsideAngular`.  Moreover, update core with fastdom like mechanic for devs to hook into.  There may be more implementations that I'm not thinking of.

## Expected behavior
Bit of background first:

```
fastdom.measure(() => {
  console.log('measure');
});

fastdom.mutate(() => {
  console.log('mutate');
});

fastdom.measure(() => {
  console.log('measure');
});

fastdom.mutate(() => {
  console.log('mutate');
});
```
Would output:

```
measure
measure
mutate
mutate
```

Example: Imagine you had an element on a page that would animate based on the current scroll position.

You could implement this in Angular w/cdkScrollable+animations with something like: (Pseudo code)
```
// index.html
<body [cdkScrollable]>
    <some-component></some-component>
</body>


// some-component.ts
@Component({
  selector: 'some-component'
})
export class SomeComponent implement OnInit, AfterViewInit {
   @ViewChild(CdkScrollable) child: cdkScrollable;
    private _el: any;
     constructor(private _elementRef: ElementRef, private _renderer: Renderer2){}

    ngOnInit() {
      this._el = this._renderer.selectRootElement(this._elementRef);
     }

     ngAfterViewInit() {
        this._makeAnimation()
     }

   private _makeAnimation() {
    // first build the animation
    const myAnimation = this._builder.build([
      style({ top: 0 }),
      animate(1000, style({ top: `${cdkScrollable. elementScrolled(). scrollTop + 100}px` }))
    ]);

    // then create a player from it
    const player = myAnimation.create(this._el.nativeElement);

    player.play();
  }
}
```

Using fastdom and Angular could look something like this:
_Note: this example should also `zone.runOutsideAngular` but I not to sure on how to add it i_n.
```

@Component({
  selector: 'some-other-component'
}) 
export class SomeOtherComponent {
  private _el: any;
  constructor(private _elementRef: ElementRef, private _renderer: Renderer2){}

  public ngOnInit() {
     this._el = this._renderer.selectRootElement(this._elementRef);
     this.renderLoop_(); // this should need to run outside of angular zone too.
  }

 private renderLoop_() {
    this.renderScrollBar_(); // this should need to run outside of angular zone too.
    fd.measure(() => this.renderLoop_());
  }

  private renderScrollBar() {
    fd.measure(() => {
      const scroll = window.scrollY + 100; 
      fd.mutate(() => {
         this._el.top = `${scroll}px`;
      });
    });
  }
}
```

**The answer isn't super straightforward; however, I believe, I'm looking to combine these two examples from above. An _Angular-Esq API_ like the first example but _scheduled DOM access APIS_ to tie Angular libraries and the developer libraries together.  Again, This Fastdom like mechanism would have to sit on top/inside core Angular libraries like `cdk` and `animations` for this system to all work and the developer would have to opt-in using them in their code as well.**

**UPDATE:** Started taking notes in a gist on how it could look 
https://gist.github.com/matthewharwood/23ea18c8509b8056813d3c3e7df0d1b2

[Example of Fastdom perf](http://wilsonpage.github.io/fastdom/examples/animation.html)
[This was also brought up in angular 1.x](https://github.com/angular/angular.js/issues/4296)
[Also wrote a stackoverflow question](https://stackoverflow.com/questions/47319803/does-angular-have-any-method-for-scheduling-measures-and-mutates-of-the-dom)

## What is the motivation / use case for changing the behavior?

Preventing the possible layout thrashing.

## Environment

<pre><code>
Angular version: 5.x

**Comment by gdi2290** [comment]
Angular has batching (via vm) for data-flow with zones but if you interact with the DOM directly you're on your own

also see `strictdom`
https://github.com/wilsonpage/strictdom

**Comment by pkozlowski-opensource** [comment]
There are many strategies for for improving UI performance and avoid layout trashing. FastDom might be one of them but also Angular tries to make sure that we do DOM manipulations in the most performant way possible.

We've just finished major framework rewrite and  not planning to do major changes to the rendering layer at the moment. Obviously we are always curious about use-cases where Angular doesn't perform well, so if you've got particular scenarios, please open more focused issues.

I'm going to close this one as we don't plan to bring FastDom right now so there is nothing actionable in the short term here. Again, happy to discuss more specific use-cases.
