### ISSUE TITLE
:leave animation does not work on Firefox and Edge

### ISSUE THREAD

**Issue by mohammedzamakhan** [angular/angular#20489]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

The enter animation is working fine on all the browsers, but the leave animation is not working on firefox and edge (works on chrome and safari)

## Expected behavior
Should work as it works in chrome and safari

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-xivr7n

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x] Firefox version 57
- [x] Edge version 41
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mham** [comment]
In your case Angular needs to calculate styles for `width` (explicitly set to `*`) and `margin` (not provided but used in animation, so implicitly `*`).

```Typescript
transition(':leave', [
  style({ transform: 'scale(1)', opacity: 1, width: '*' }),
  animate('1s cubic-bezier(.8,-0.6,0.2,1.5)', 
    style({ transform: 'scale(0.5)', opacity: 0, width: '0px', margin: '0px' }))
])
```

From documentation for [style](https://angular.io/api/animations/style#auto-styles-using-) function.

>  Auto-styles (using `*`)
>
> When an asterix (`*`) character is used as a value then it will be detected from the element being animated and applied as animation data when the animation starts.
>
> This feature proves useful for a state depending on layout and/or environment factors; in such cases the styles are calculated just before the animation starts.

Angular uses [`Window.getComputedStyle`](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) to calculate property value for auto-styles. `Window.getComputedStyle` returns *empty* string for `margin` property in Firefox. When property value is *empty* string, Angular [sets](https://github.com/angular/angular/blob/5.0.0/packages/animations/browser/src/render/transition_animation_engine.ts#L1489) `REMOVAL_FLAG` of element to `NULL_REMOVED_QUERIED_STATE` and [then](https://github.com/angular/angular/blob/5.0.0/packages/animations/browser/src/render/transition_animation_engine.ts#L1268) the [`NoopAnimationPlayer`](https://angular.io/api/animations/NoopAnimationPlayer) is used - animation does not play.

**When property is not longhand property, we should ignore its *empty* value.**

According to specification of [CSS Object Model](https://drafts.csswg.org/cssom/#dom-window-getcomputedstyle), `Window.getComputedStyle` returns all **longhand** properties. While iterate over numeric indexes of `Window.getComputedStyle`, there is no `margin` property in Chrome and Firefox. But when access `margin` property directly, there is *non-empty* value in Chrome and *empty* value in Firefox. We cannot rely on this across the browsers.

```javascript
var computed = window.getComputedStyle(document.body);
// no margin
for (var i = 0; i < computed.length; i++) {
  if (computed[i].startsWith('margin')) {
    console.info(computed[i]);
  }
}
// non-empty in Chrome, empty in Firefox
console.info(computed['margin']);
```

**Workaround is use of longhand properties.**

**Comment by mohammedzamakhan** [comment]
@mham I have changed to to explicit width now, but still it doesn't work!

**Comment by mham** [comment]
@mohammedzamakhan Property `width` is correct. Problem is with `margin` property. As workaround, expand `margin` to `margin-top`, `margin-right`, `margin-bottom` and `margin-left`.

@mhevery I think this is Angular bug. Can you reopen this issue?

**Comment by matsko** [comment]
There already exists an issue about the margin and padding shorthand properties not working in FF and IE: https://github.com/angular/angular/issues/16330

**Comment by matsko** [comment]
I will escalate it so it can get fixed by the next release.
