### ISSUE TITLE
Webpack failure on dot net core 2 gives wrong message.

### ISSUE THREAD

**Issue by tarekgh** [angular/angular#20485]
_From @prashantchoudhary on November 7, 2017 15:40_

DotNet Core 2.0 with Angular 5
If angular is updated to angular 5 and ngtools is not latest, then following error comes during runtime.
Error: Version of @angular/compiler-cli needs to be 2.3.1 or greater. 
Current version is "5.0.0".

Error message is clearly misleading.

_Copied from original issue: dotnet/corefx#25099_

**Comment by tarekgh** [comment]
_From @karelz on November 8, 2017 0:7_

@prashantchoudhary how is it related to .NET Core? Is it problem of managed code or JS?

**Comment by prashantchoudhary** [comment]
Its more of a webpack issue but the step is called by dotnet core in Startup Section. I posted in dotnet section as the template was dotnet core with angular and webpack. mostly it should be from webpack.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
