### ISSUE TITLE
autofocus not working

### ISSUE THREAD

**Issue by amineparis** [angular/angular#20480]
Native html autofocus attribute not working in Angular due to dynamic generation of DOM elements

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Please respect the issue template. Thank you.
