### ISSUE TITLE
Avoid having to put the client bootstrap in DOMContentLoaded for TransferState to work properly

### ISSUE THREAD

**Issue by vikerman** [angular/angular#20484]
Currently the client of a SSR Angular app needs to wait for DOMContentLoaded to complete before bootstrapping so that TransferState can reliably get the contents of the transferred state from the DOM.

Need to investigate whether we can handle this more transparently without the user needing to bootstrap in a specific way on the client side.

**Comment by jcao02** [comment]
@vikerman do you suggest to do something like this?
```
document.addEventListener('DOMContentLoaded', () => {
  platformBrowserDynamic().bootstrapModule(AppModule);
});
```

**Comment by nicolae536** [comment]
Thanks this made us to understand why a critical bug happens just some times. I agree this should be part of angular function but anyway is good that there is a easy fix for it.

**Comment by alan-agius4** [comment]
The script tag that loads the main.js file can be deferred using the [`defer`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer) attribute.
