### ISSUE TITLE
canDeactivate Router guard

### ISSUE THREAD

**Issue by angular2fan** [angular/angular#20483]
Hello,

Need advice on if am doing something not correct or is the feature not supported.

Background:
I implemented "canDeactivate" guard for one of my routes to alert the user if they really intended to navigate.

canDeactivate(): Observable<boolean> | boolean{
if(return value from Async call){
      if(returnValue){
         setTimeout(()=>{
        
        console.log('inside the settimeout function and can redirect');
        return true;
      }, 2000)
      } else{
       
        console.log('inside the settimeout function and canNOT redirect');
        return false;
      }
};

Issue:
canDeactivate method is not recognizing the return value from the setTimeout function. if i return true or false from outside of the async fn it works. 

Is this something buggy on my end or is this feature not supported. Please clarify.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).


Please read the docs:

https://angular.io/api/router/CanDeactivate
https://angular.io/guide/router#candeactivate-handling-unsaved-changes

**Comment by angular2fan** [comment]
okay. Thank you. I am closing this issue as this is not the correct venue.
