### ISSUE TITLE
feat: Allow Spliting the CSS bundle by Media Queries

### ISSUE THREAD

**Issue by montella1507** [angular/angular#20486]
## I'm submitting a...
[x ] Feature request

## Current behavior
All CSS are bundled in one CSS (with --extract-css tag).

## Expected behavior
Laverage a webpack module, to split CSS to multiple bundles like
core.css
[media-query].css

to generate multiple CSS bundles and load them with
`<link rel="[media-query].css" media="[media-query]">` 

to effective load only those CSS rules that are needed (based on the platform)

## What is the motivation / use case for changing the behavior?
Better code splitting - load performance, smaller "rendering gap".

**Comment by VagrantAI-c** [comment]
So, this is a pretty valuable feature, since google search now relies on site speed

**Comment by trotyl** [comment]
Please report to https://github.com/angular/angular-cli, Angular has nothing to do with CSS bundling.

**Comment by VagrantAI-c** [comment]
@trotyl I thought this is exact compiler task, since we specifying css in components metatag, e.g.:
```
@Component({
    template: ``,
    styleUrls: [
        './style.component.scss',
        { path: './style-mobile.component.scss', mediaQuery: '(max-width: 767px)' },
        { path: './style-tablet.component.scss', mediaQuery: '(max-width: 960px)' },
    ],
})
```

**Comment by VagrantAI-c** [comment]
I agree that this might be a CLI issue, but it will produce changes to [Component API](https://angular.io/api/core/Component), won't it? Since we would need to directly specify a media query for each optional style.

**Comment by VagrantAI-c** [comment]
@trotyl I think I'm getting what are you trying to imply. Do you propose that css chunk can be separated by media queries w/o developer participation? If so, then I'm gonna redirect it for CLI for sure.

**Comment by trotyl** [comment]
Component styles are not resulting in css file thus unrelated to this issue, this issue is only for the project styles used in Angular CLI.

**Comment by montella1507** [comment]
To be honest.. i haven't scoped this idea this to component styles...  But.. we have Webpack, we have build process... so "we" should be able to compute styles the same way a browser does and to be able to split all styles to groups by media queries...

Supersimple example:
// file xyz
a {}

// file zyx
@media(X) {
  a{}
}


@media(Y) {
  a{}
}


so why we shouldnt be able to teardown (compute) all queries, create bundles X and Y  with 
a{}  for small displays (X),  a{} form big display (Y) and so on? To link css by media query ? It is just an idea how it may work i am not skilled enough to make correct decisions regarding CSS bundling.
