### ISSUE TITLE
Consider DOMChangeList proposal for renderer(2?)

### ISSUE THREAD

**Issue by chicoxyzzy** [angular/angular#20499]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

There is [DOMChangeList proposal to DOM specification](https://github.com/whatwg/dom/issues/270) and it seems like there is an interest from implementors. As far as I can see, that proposal is quite similar to what renderer2 does. Glimmer already has a [polyfill](https://github.com/glimmerjs/glimmer-vm/tree/master/packages/%40glimmer/dom-change-list) for DOMChangeList (it's coupled to Glimmer internals though). Could that proposal be considered for future renderer implementations?

**Comment by Toxicable** [comment]
How would Angular benefit from having this?

**Comment by pkozlowski-opensource** [comment]
> Could that proposal be considered for future renderer implementations?

There are some aspects of the DOMChangeList proposal that would make implementing Angular internals easier (keeping track of nodes associated with a view and inserting / removing such group of nodes). Sadly, it doesn't seem like we are anywhere closer to have this spec finished / implemented. As such I'm going to close this issue for now (trying to cleanup a list of issues a bit). 

We will _always_ keep an eye on this (and similar) proposals but for now there is not much of action we can take.
