### ISSUE TITLE
angualr5，不兼容iPhone，微信浏览器，这是什么原因啊。

### ISSUE THREAD

**Issue by yushk** [angular/angular#20493]

**Comment by pkozlowski-opensource** [comment]
hanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
