### ISSUE TITLE
Can't change Angular4 validator default value

### ISSUE THREAD

**Issue by happierday** [angular/angular#20497]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Can't not set the default value for validator at the beginning

## What is the motivation / use case for changing the behavior?
When you first go to login page, I understand that the validator should be set to false because you do not give any value yet.

However, my question is when you already have a form that passed the validator and you want to edit it at some point. You need a new form to handle the edit event and you will get the value from the old form. But for this new form, the validator should be all true at the beginning because the old form already passed the validation.

Angular4 does not support this feature to set validator to true at initial step, or is there an another way to work around this?

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
