### ISSUE TITLE
FormControl.invalid stays true forever 

### ISSUE THREAD

**Issue by nhducseuit** [angular/angular#20492]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The `invalid` field of FormControl instance stays  `true` before and  after user have resolved the errors.

## Expected behavior

The FormControl instance inside a Component should update `invalid` field value

## Minimal reproduction of the problem with instructions

I thought that the plunker example on document site would help but it doesn't.
I will try to make one when I have time.
This only require a mat-select with a formcontrol injected and then check on browser debug console.

## What is the motivation / use case for changing the behavior?

I have an input form inside a dialog.
I would like to check the `invalid` attribute of FormControl instance sticking to input fields to decide whether the dialog should be closed on user clicks "Save" or stay there asking for correct inputs.

## Environment

<pre><code>
Angular version: 5.1.0-beta.0

Browser:
- [x ] Chrome (desktop) version 59
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version 56
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.10  
- Platform:   Ubuntu x64 16.04

Others:

</code></pre>

My workaround on this is to inspect the `ngControl` field of each input field directly. Like:
```
@ViewChild('reasonSelect') reasonSelect;
...
  public saveButtonClicked(event: any) {
    if (!this.reasonSelect.ngControl.invalid) {
      this.dialogRef.close(true);
    } else {
      console.log('Form error presents');
    }
  }
```

**Comment by mhevery** [comment]
Please provide plunker which reproduces the problem.

**Comment by kara** [comment]
@nhducseuit This is not actionable without some sort of code example, so I'm closing this for now. Please feel free to open a new issue once you have a plunker/stackblitz/equivalent for us to look at.
