### ISSUE TITLE
ng serve is  not working after fresh install

### ISSUE THREAD

**Issue by PrabakarKaruppasamy** [angular/angular#20506]
Versions of @angular/compiler-cli and typescript could not be determined.
The most common reason for this is a broken npm install.

Please make sure your package.json contains both @angular/compiler-cli and typescript in
devDependencies, then delete node_modules and package-lock.json (if you have one) and
run npm install again.

If we try ng -v getting like below

> E:\my-project>ng -v
> 
>     _                      _                 ___ _     __
>    / \   _ __   __ _ _   _| | _ _  _     / _| |   | _|
>   / △ \ | ' \ / ` | | | | |/ _` | '__|   | |   | |    | |
>  / __ \| | | | (_| | |_| | | (_| | |      | |___| |__ | |
> /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
>                |___/
> 
> Angular CLI: 1.5.2
> Node: 8.9.1
> OS: win32 x64
> Angular: 5.0.2
> ... animations, common, compiler, core, forms, http
> ... platform-browser, platform-browser-dynamic, router
> 
> @angular/cli: error
> @angular/compiler-cli: error
> @angular/language-service: error
> typescript: error
> webpack: error

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

Please open angular-cli related issue on its repo: https://github.com/angular/angular-cli

**Comment by PrabakarKaruppasamy** [comment]
Thanks for quick response. I have opened that issues in angular-cli.
