### ISSUE TITLE
Angular 4 App is not working in Safari 9.1.3 !!

### ISSUE THREAD

**Issue by vidhyasgr** [angular/angular#20505]
I got this two exceptions.

**Exceptions**
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
TypeError: null is not an object (evaluating 'element.addEventListener')

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
