### ISSUE TITLE
[i18n] Document how to set locale for pipes outside app module

### ISSUE THREAD

**Issue by philjones88** [angular/angular#20500]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Documentation at https://angular.io/guide/i18n#setting-up-the-locale-of-your-app currently describes 1 way to set the locale for pipes such as Date but according to @ocombe `It can be used anywhere, as long as it's before you use one of the pipes.`. See https://github.com/angular/angular/issues/20193#issuecomment-344989722

## Expected behavior
Documentation describes all methods of setting the locale 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ocombe** [comment]
Duplicate of #20487 I think :)

**Comment by philjones88** [comment]
Closed as duplicate :(
