### ISSUE TITLE
DiffingPluginWrapper should handle input trees with mutable input paths

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#2051]
Originally when DiffingPluginWrapper was written it appeared that the broccoli plugins don't change their outputPaths, but we came across several that do (for example mergeTrees, replace plugins).

These outputPaths become inputPaths for our `DiffingBroccoliPlugins`. The mutability of these inputPaths is causing us to throw `ENOENT` while dirty checking the filesystem because the `TreeDiffer` (used by `DiffingPluginWrapper` that wraps our `DiffingBroccoliPlugins`), expects that path to be immutable.

In order for us to be fully compatible with existing plugins we need to work around this issue by not tying a tree differ to a path, but instead provide the path to be dirty-checked when calling.

That means to move the path declaration from `TreeDiffer` constructor to `TreeDiffer#diffTree()`  method.

**Comment by joliss** [comment]
Having unstable input paths is one of the things I regret about the original (current) Broccoli API. I'm working on redoing the plugin API, and with the new API there will be stable input paths.

To use the new API, plugins will derive from the [broccoli-plugin](https://github.com/broccolijs/broccoli-plugin) base class (currently work-in-progress). Plugins using the broccoli-plugin will still run on old (current) Broccoli versions using [compatibility code](https://github.com/broccolijs/broccoli-plugin/blob/3cdf65fa86b0f578873456fd3c987722cc9c99cb/index.js#L110-L112). In fact, we're resorting to exactly the kind of symlinking as in [L41 of #2143](https://github.com/angular/angular/pull/2143/files#diff-5ec68c0c2d10286c46b7f9f84a0626b8R41) - see [index.js:172](https://github.com/broccolijs/broccoli-plugin/blob/3cdf65fa86b0f578873456fd3c987722cc9c99cb/index.js#L172). It's obviously a hack, and may be slow on Windows, but it's only a stop-gap until people use a newer Broccoli.

**Comment by joliss** [comment]
(Cc @caitp in case she isn't subscribed to this issue already.)

**Comment by joliss** [comment]
So to summarize: This issue will go away as soon as I finish broccoli-plugin, which is the thing that's at the top of my list right now. Then you can derive from broccoli-plugin and everything should work fine.

**Comment by IgorMinar** [comment]
@joliss thanks for the clarification. I took a quick look at the broccoli-plugin code, but unfortunately, I don't see it addressing some of the issue we came across. Especially, enabling incremental (at a file-level within a tree) compilation doesn't seem to be addressed. We worked around this limitation by creating a custom plugin interface that we wrap into a generic plugin before hooking it up with broccoli. You can see the interface [here](https://github.com/angular/angular/blob/2c25055828c2593958b3480e12a72ed50ed8499e/tools/broccoli/diffing-broccoli-plugin.ts#L29-L32) and an example plugin [here](https://github.com/angular/angular/blob/2c25055828c2593958b3480e12a72ed50ed8499e/tools/broccoli/broccoli-dest-copy.ts). Would you be open to discuss these changes? My plan was to finish rewriting plugins in our build tree to be only incremental and then present the result to you, but since you are already working on broccoli-plugin, it might be better to discuss this sooner.
