### ISSUE TITLE
Dynamic component generation and Dynamic routing configuration

### ISSUE THREAD

**Issue by AnilMule1008** [angular/angular#20514]
<pre><code>
Angular version:4.2.4
For Tooling issues:
- Node version: XX  
- Platform:  windows 7

public getCountries(){
    let _url: string = 'https://restcountries.eu/rest/v2/all';
    return this._http.get(_url);
  }

Suppose my service is returning 5 objects.
I wanted to know that is it possible to create components dynamically as per http response?
And Is it possible to configure routes dynamically as per http response?

</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by AnilMule1008** [comment]
Actually i have posted the same on StackOverflow last week. But i didnt get answer there.
here is the link:-
https://stackoverflow.com/questions/47278405/is-it-possible-to-create-components-dynamically-as-per-http-response-in-angular4

**Comment by mlc-mlapis** [comment]
@AnilMule1008 ... look around and google a bit, this theme is discussed hundreds times.

If you don't know where to start maybe this link helps you ... it is a simplified sample of the same solution as http://angular.io is using https://github.com/wardbell/ng-dynamic-app and it was presented during Angular Connect here https://www.youtube.com/watch?v=__H65AsA_bE&feature=youtu.be&t=2h14m13s.
