### ISSUE TITLE
common-http.umd : wrong rxjs_observable_of factory parameter

### ISSUE THREAD

**Issue by uparlange** [angular/angular#20516]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

ERROR TypeError: rxjs_observable_of.of is not a function
    at HttpClient.request (common-http.umd.min.js:sourcemap:39)
    at HttpClient.get (common-http.umd.min.js:sourcemap:39)
    at TranslateManager._loadProperties (TranslateManager.js:87)
    at TranslateManager.setLanguage (TranslateManager.js:27)
    at TranslateManager.init (TranslateManager.js:22)
    at Shell.init (Shell.js:26)
    at AppView.onInit (AppView.js:35)
    at AppView.ngOnInit (AbstractDirective.js:17)
    at AppView.ngOnInit (AbstractView.js:13)
    at checkAndUpdateDirectiveInline (core.umd.min.js:sourcemap:83)

## Current behavior

Error at runtime.
--> Meanwhile to fix add this before script : "Rx.Observable.prototype.of = Rx.Observable.of"

## Expected behavior

No error at runtime.
--> rxjs_observable_of parameter should be "Rx.Observable" and not "Rx.Observable.prototype"

## Environment

es5 integration
Angular 5+
Material 5.0.0-rc0
Rxjs 5.5.2
All browsers

**Comment by ericmartinezr** [comment]
I'm sorry but reported issues require a plunker reproducing the problem.

If this issue persists, please create a plunker using this template and describe the difference between the expected and current behavior and create a new issue: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by uparlange** [comment]
Problem is simple to correct (node_modules\@angular\common\bundles\common-http.umd.js)

(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('@angular/core'), require('rxjs/observable/of'), require('rxjs/operator/concatMap'), require('rxjs/operator/filter'), require('rxjs/operator/map'), require('tslib'), require('@angular/common'), require('rxjs/Observable')) :
	typeof define === 'function' && define.amd ? define('@angular/common/http', ['exports', '@angular/core', 'rxjs/observable/of', 'rxjs/operator/concatMap', 'rxjs/operator/filter', 'rxjs/operator/map', 'tslib', '@angular/common', 'rxjs/Observable'], factory) :
	(factory((global.ng = global.ng || {}, global.ng.common = global.ng.common || {}, global.ng.common.http = {}),
		global.ng.core,
		**global.Rx.Observable.prototype (change to global.Rx.Observable)**,
		global.Rx.Observable.prototype,
		global.Rx.Observable.prototype,
		global.Rx.Observable.prototype,
		global.tslib,
		global.ng.common,
		global.Rx));
}(this, (function (exports,
		_angular_core,
		**rxjs_observable_of**,
		rxjs_operator_concatMap,
		rxjs_operator_filter,
		rxjs_operator_map,
		tslib,
		_angular_common,
		rxjs_Observable) { 'use strict';

**Comment by uparlange** [comment]
https://plnkr.co/edit/2yTBI2cpMw6yXjAV8gLZ?p=preview

**Comment by sebastienminne** [comment]
Hi, is this going to be fixed in next release ? Any turn around waiting for this release ?

**Comment by dezsiszabi** [comment]
I encountered this very same error today. Had to apply the workaround provided by @uparlange.
Will this be fixed in the next release?
