### ISSUE TITLE
I Got error while implementing swipe tabs in ionic 3

### ISSUE THREAD

**Issue by hasnentai** [angular/angular#20517]
# So far i  have done 
**_npm install ionic2-super-tabs --save_**
## I have imported in app.module.ts file 
`import { SuperTabsModule } from 'ionic2-super-tabs';`

```
imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
    SuperTabsModule
  ],
```
## That is mine tabs.html

```
<super-tabs>
    <super-tab [root]="tab1Root" title="First page"></super-tab>
    <super-tab [root]="tab2Root" title="Second page"></super-tab>
    <super-tab [root]="tab3Root" title="Third page"></super-tab>
</super-tabs>
```
## The Error what i am getting is
<img width="760" alt="screen shot 2017-11-18 at 5 15 06 pm" src="https://user-images.githubusercontent.com/26821037/32979942-25d4ee14-cc84-11e7-978d-ddfd59c1248a.png">

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
