### ISSUE TITLE
Unresolved constructor types produce an internal error

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#20523]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

If a parameter type is not resolvable the compiler will produce an internal error instead of a reasonable error message.

## Expected behavior

A reasonable error message.

## Minimal reproduction of the problem with instructions

1. `ng new ` <someProgram>
2. `yarn add @angular/material # important, don't include the cdk and ignore the warning`
3. Add `MatPaginatorModule` to `app.module.ts`
4. `ng build --aot`

Received:  `Error: TypeError: Cannot read property 'isSkipSelf' of null`
Expected: `Could not resolve "@angular/cdk"` or something similar.

**Comment by Xavier-J-Ortiz** [comment]
Hello! I'd like to take a stab at this.

Full disclosure, I'm looking to do a first PR to this project and to an Open Source project. I chose this issue for no other reason in particular that it says the effort is _easy_, and the workaround is _obvious_.

I may need some help getting started, as I wouldn't know where to start chasing this.

If there's a better issue for a newbie like myself, please let me know and I'll free this up for someone who understands this better.

Thanks!

**Comment by Xavier-J-Ortiz** [comment]
@chuckjaz Any hints on where to get started on this please? :)

**Comment by picheli20** [comment]
I think this can be closed, I've tested and it's showing  the following validation:
```
ERROR in ../@angular/material/button/typings/index.ts(29,5): Error during template compile of 'MatButtonModule'
  Could not resolve @angular/cdk/a11y relative to /Users/fabiopicheli/projects/angular-error/node_modules/@angular/material/button/typings/index.d.ts..
```
It's enough?

**Comment by lazarljubenovic** [comment]
I'm still getting an useless error message when building a library with `ng`.

```text
BUILD ERROR
Cannot read property 'isSkipSelf' of null
TypeError: Cannot read property 'isSkipSelf' of null
    at ProviderElementContext._getDependency (/project/node_modules/@angular/compiler/bundles/compiler.umd.js:11483:22)
    at /project/node_modules/@angular/compiler/bundles/compiler.umd.js:11428:64
    at Array.map (<anonymous>)
    at /project/node_modules/@angular/compiler/bundles/compiler.umd.js:11428:30
    at Array.map (<anonymous>)
    at ProviderElementContext._getOrCreateLocalProvider (/project/node_modules/@angular/compiler/bundles/compiler.umd.js:11406:67)
    at /project/node_modules/@angular/compiler/bundles/compiler.umd.js:11304:27
    at Array.forEach (<anonymous>)
    at new ProviderElementContext (/project/node_modules/@angular/compiler/bundles/compiler.umd.js:11301:53)
    at TemplateParseVisitor.visitElement (/project/node_modules/@angular/compiler/bundles/compiler.umd.js:15072:35)
```

**Comment by darlanalves** [comment]
To add some extra information: I sometimes see the same error @lazarljubenovic is seeing.
That happens when I have an import that moves to a new location on disk and I don't change the code.
Instead of stating that an import is missing, the compiler just breaks with the `isSkipSelf` error.

As a sidenote: while developing with `ng serve`, a lot of random errors pop in my terminal with useless messages. Is only when I stop the server and start again that the real problem in my code is reported.

**Comment by lazarljubenovic** [comment]
I indeed had a random dependency here which couldn't exist. Solved it by exporting from the main file one symbol by one.

**Comment by xxxtonixxx** [comment]
I had a lot of problems with this error :cry: and ng-packagr. I couldn't build and I didn't know why. Finally, I found the problem, it was related with primitives values and DI. 

Here I give a test-comp of the error, it has been a headache:
```ts
import { Component, Optional } from '@angular/core';

export class DumbFail { }

// Hello incomprehensible isSkipSelf fail :')
export function createDumbFail(fail = true /* 'hello'/99/any primitive value */) {
  return new DumbFail();
}

@Component({
  selector: 'my-foo',
  template: '<h1>foo</h1>',
  styleUrls: ['./foo.component.scss'],
  providers: [
    {
      provide: DumbFail,
      useFactory: createDumbFail,
      deps: [[new Optional(), Boolean]] // It produces a failed build
      // deps: [[new Optional(), true/false]] // It produces a failed build
      // deps: [[Optional, Boolean]] // It builds (why? xD), but it produces an error in execution
    }
  ]
})
export class FooComponent {
  constructor(dumb: DumbFail) { }
}
```

**Comment by nickwinger** [comment]
it happened when building a library, then all the meaninful errors get swallowed and replaced by nonsense error message.
Luckily i had an other project where i used the library, there i just typed `ng build` and suddenly i saw all the errors (scss, etc.)
after fixing the building of the library also succeeded

**Comment by alehro** [comment]
I had the same problem with "npm run start" command. But "ng build" as Nick advised has shown true error. Thanks.

**Comment by kyliau** [comment]
Closing this manually since https://github.com/angular/angular/pull/30075 should have closed this.
