### ISSUE TITLE
[Router] - Type of event is not inferred correctly using filter operator

### ISSUE THREAD

**Issue by rafaelss95** [angular/angular#20525]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Consider this piece of code:

```
constructor(private router: Router) { }

ngOnInit() {
  this.router.events.pipe(
    filter(e => e instanceof NavigationEnd)
  ).subscribe(
    // e is inferred as RouterEvent | RouteConfigLoadStart | RouteConfigLoadEnd | ChildActivationStart | ChildActivationEnd | ActivationStart | ActivationEnd
    e => console.log(e)
  );
```

In code above, I'm using `filter` operator to "_listen_" only events referent to `NavigationEnd`, however the type isn't being inferred correctly. Instead of getting `e` as `NavigationEnd`, I'm getting `e` as `RouterEvent | RouteConfigLoadStart | RouteConfigLoadEnd | ChildActivationStart | ChildActivationEnd | ActivationStart | ActivationEnd`.

## Expected behavior
I'd expect `e` to be inferred as `NavigationEnd`.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gitter-pjkkjx

## Environment
Angular version: 5.0.2

Others:
Not sure if it's something related to the `filter` operator, but something has changed (here or in rxjs) that broke the old behavior.

Actually, to get the correct type inferred you have to put an `if` in your subscribe like that:

```
this.router.events.subscribe(
  e => {
    if (e instanceof NavigationEnd) {
     // e is inferred as NavigationEnd
     console.log(e);
    }
  }
);
```

**Comment by Toxicable** [comment]
I'm sorry but this issue is not caused by Angular. Please contact the author(s) of project `rxjs` or file issue on their issue tracker.

**Comment by rafaelss95** [comment]
@Toxicable are you sure about this? Could you expand a bit more?

What I'm seeing here is: `router.events` is an Observable of type `Event` which is: 

`(property) Router.events: Observable<RouterEvent | RouteConfigLoadStart | RouteConfigLoadEnd | ChildActivationStart | ChildActivationEnd | ActivationStart | ActivationEnd>`

... so theorically, there's no option to get the `NavigationEnd` since it's not part of [Event](https://github.com/angular/angular/blob/5.0.2/packages/router/src/events.ts#L346)

**Comment by Toxicable** [comment]
`Event` (@angular/router 's one) is this here https://angular.io/api/router/Event
specifically `NavigationEnd` is apart of https://angular.io/api/router/RouterEvent

but not that it matters since `pipe` and `filter` are rxjs's not Angular and it's those that are messing up the type not Angular

**Comment by rafaelss95** [comment]
Aha, I missed that `NavigationEnd` is part of `RouterEvent`. Thanks for that. I'll create an issue in `rxjs`.
