### ISSUE TITLE
Reactive Form with radios per row allow arrows to go to next row 

### ISSUE THREAD

**Issue by borriej** [angular/angular#20529]
issue:

- I have a large reactive form, that loops, using *ngFor
- there is a radio group with two option per row
- When you press tab on you keyboard, and have focus on the first radio, and then press 'arrow key right' twice... it will first focus on the last radio option (correct)... and then set focus on the next rows' radio (false !).. this happens , because Chrome thinks its the same radio group... Normally we would use attribute name="", but we cant because we're using formControlName.

`    <div class="btn-group btn-group-custom-toggle" >
        <input type="radio"
            id="rideType{{i}}RideTypeBusiness"
            autocomplete="off"
            formControlName="rideType"
            [value]="RideType.Business">
        <label class="btn" for="rideType{{i}}RideTypeBusiness">Z</label>
        <input type="radio"
            id="rideType{{i}}RideTypePrivate"
            autocomplete="off"
            formControlName="rideType"
            [value]="RideType.Private">
        <label class="btn"for="rideType{{i}}RideTypePrivate">P</label>
    </div>`

solution

- please also render native radio name attribute(?), so Chrome can devide 'row 1 radio group' versus 'row 2 radio group'.. then when keying with arrows it wont set focus on the radio in the row below the row it

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Please respect the issue template. Thank you.

**Comment by borriej** [comment]
Hi Eric,

Thanks for your review. I do not follow this, because adding attribute name (in combination with formControlName) has the side effect that the radios does not 'check' the radio with the value in the reactive form model anymore.. all radios are suddenly unchecked. 

It seems like name + formControlName are not supposed to be used together with radios?

**Comment by sarunint** [comment]
Hmm, this should be part of #9681, but it seems that it doesn't work as demonstrated here: https://stackblitz.com/edit/angular-8339wy

@kara, could you please look at this issue?
