### ISSUE TITLE
feat(platform-server): allow configuration for render timing

### ISSUE THREAD

**Issue by CaerusKaru** [angular/angular#20520]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`renderModuleFactory` will render the HTML string after the first VM tick returns as stable. This gives some undefined behavior for async operations that happen on the server, ie some may complete and some may not.

## Expected behavior

Allow for some method to override or force the render method to wait based on user configuration

## What is the motivation / use case for changing the behavior?

Some users may want async operations to complete before they render the HTML string without having to use a Route Resolve for every such operation.

**Comment by CaerusKaru** [comment]
cc @Toxicable @vikerman

**Comment by vikerman** [comment]
Hi - The current way to do this would be to make your task appear as a macrotask to Zone. This is the approach we took to wrap xhr2 for the HttpClient implementation on the server.

https://github.com/angular/angular/blob/14e8e880222431eeccdacac6540574b49903bd79/packages/platform-server/src/http.ts#L38

Is this a sufficient solution for your use case?

**Comment by CaerusKaru** [comment]
That's great! We should probably throw together a guide for this in the Universal repo with an example. If it's not too much trouble, could you throw together a short description of what your method/class is doing and how to use it (maybe in a Google Doc)? I can work on a practical example and post it as a guide in the repo/universal-starter.

**Comment by CaerusKaru** [comment]
@vikerman Also, does this mean that a possible solution to https://github.com/angular/universal/issues/842 is to wrap some Http/async calls as Zone.js microtasks?

**Comment by vikerman** [comment]
Will be able to throw together a doc next week. This should go into examples folder of angular/universal so that the starter remains simple.

 angular/universal#842 says the rendering is not waiting for AJAX data. Not sure what that means. If they use Httpclient everythign should just work. If they use any library of their own wrapping into a Zone macrotask is the way to go.

**Comment by CaerusKaru** [comment]
@vikerman Any updates on the doc?

**Comment by hiepsieuviet** [comment]
do you have any update on this ? I'm love to see it

**Comment by CaerusKaru** [comment]
If I don't get a response from @vikerman by the end of next week, I'll try taking a crack at writing the doc, but until then no.

**Comment by hiepxanh** [comment]
@vikerman, @CaerusKaru  can you make an instruction, sir? Just be simple, I will try my best to work with it. 
Please... , it's very important for me to make my firebase app to working in production.

**Comment by dcballs** [comment]
Hi @vikerman, do you plan any update on the examples in angular/universal? Is there a way for you  to provide a snippet to how to handle observables/promises with xhr requests not created by HttpClient!? Thanks in advance, kind regards

**Comment by dcballs** [comment]
Hey @CaerusKaru, any update on your solution?

**Comment by CaerusKaru** [comment]
@dcballs @hiepxanh I apologize, but I haven't been able to get in touch with @vikerman and I want to coordinate with him on the best design for the doc. I'll try for by the end of the month, but no promises.

**Comment by hiepxanh** [comment]
yes, thanks you alot, just give us a hope ✌️ , just relax, it is a opensource, you can do whenever you ready, just tell me if I can help you anything. I love to do that to support angular team

**Comment by dcballs** [comment]
thank you @CaerusKaru , if you need any assistance to provide an example of implementation in customized solution, don't hesitate to ask. Cheers 💯

**Comment by hiepxanh** [comment]
hello, any update on this? universal is very important feature and 3rth party like firebase can work if we can resolve this issue, which can allow configuration for render timing.

**Comment by CaerusKaru** [comment]
This is part of our documentation efforts over on `@angular/universal`. Once we have it ready, we’ll post an update here.

**Comment by hiepxanh** [comment]
yes sir! Thank you for your information

**Comment by thedewpoint** [comment]
@CaerusKaru can you link me to that?

**Comment by raza2022** [comment]
@CaerusKaru Please any update or code snippet how to use it I tried by didn't work as expected

**Comment by jenniferfell** [comment]
Universal doc has been rewritten for v7. Please let us know if you find errors or omissions in the new v7 doc. Thanks!
#25752
https://next.angular.io/guide/universal

**Comment by alvarotf** [comment]
Finally, I could make it work using ZoneMacroTaskWrapper as @vikerman suggested. Hope this helps someone.
[https://gist.github.com/alvarotf/95ba4ad6355be50d28b338d51dec1683](https://gist.github.com/alvarotf/95ba4ad6355be50d28b338d51dec1683)

**Comment by rangfu** [comment]
This works nicely for me thanks @alvarotf, to get Angular to wait for non-Angular asynchronous calls to finish before rendering (I'm making calls to AWS DynamoDB using their SDK). For anyone reading and not quite sure how to use that helper class, one of the comments in that Gist link has an example of how to inject and use it.

**Comment by jessicajaniuk** [comment]
It looks like this issue is resolved. Please create a new issue if the problem is still a need. Thanks.
