### ISSUE TITLE
Not able to create the interface in Type script

### ISSUE THREAD

**Issue by lavnaphade** [angular/angular#20533]
I have getting the below error. Kindly suggest the anything miss out.

TS Version : 2.6.1

interface ICar{  
    engine: string;
    color: string;
}

class Car implements ICar {  
    constructor (public engine: string, public color: string) {
    }
}
-------------------------

Error: 
C:\Users\nriportal\lav\src\app\test1.ts:1
(function (exports, require, module, __filename, __dirname) { interface ICar{
                                                                        ^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by tibinthomas** [comment]
Please define engine, color properties in the class without using TS shorthand syntax.

**Comment by lavnaphade** [comment]
Thanks for your response. 

I have tried simple interface. Still i have getting the same issue. Please suggest.

interface ICustomer
{
id: number;
name:string;
}

C:\Users\admin\TestProj1\main.ts:1
(function (exports, require, module, __filename, __dirname) { interface ICustome
r
                                                                        ^^^^^^^^
^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by lavnaphade** [comment]
Please can you help me..
