### ISSUE TITLE
Incomplete type list in commit guidelines: add "release" type

### ISSUE THREAD

**Issue by marionebl** [angular/angular#20537]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The list of allowed commit types at https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type currently list no type appropriate for project activities like releasing, for which previously the `chore` type was used. 

The Angular project itself uses a `release` type, e.g. here: https://github.com/angular/angular/commits/master/package.json

## Expected behavior
The commit conventions list all types in use. Add "release" to list of allowed types

## What is the motivation / use case for changing the behavior?
Create a reliable single source of truth for commit conventions external tools such as 

* https://github.com/marionebl/commitlint
* https://github.com/conventional-changelog/standard-version
* https://github.com/conventional-changelog/conventional-changelog/

**Comment by jenniferfell** [comment]
docsarea=contributing

**Comment by mgechev** [comment]
Since the release commit type is meant for only Angular caretakers, I'll close the issue as "wont fix" for now. If you disagree, please open a new issue and share details why you think it should be part of the docs.
