### ISSUE TITLE
Webpack example not working properly (npm test, npm start)

### ISSUE THREAD

**Issue by juandovo** [angular/angular#20530]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The testing setup in the current webpack example is not working properly. The download is in:
https://angular.io/guide/webpack (direct download URL: https://angular.io/generated/zips/webpack/webpack.zip). There are missing dependencies in package.json, as well as an error in which karma is not loading the specs.

## Expected behavior
The testing example should work without modifications when running npm install and npm test

## Minimal reproduction of the problem with instructions
1. Download the webpack example in https://angular.io/guide/webpack (notice that the files in this zip are different than what the actual webpage displays).
2. Unzip
3. Run npm install
4. Run npm test

Karma complains that webpack and sourcemap preprocessors need additional plugins.

5. Run `npm i karma-webpack -D` and `npm i karma-sourcemap-loader -D`
6. Run npm test

Karma will load properly, but the following message appears:
`Chrome 61.0.3163 (Windows 10 0.0.0): Executed 0 of 0 ERROR (0.013 secs / 0 secs)`

Which I'm guessing means that karma is not loading specs properly.

## What is the motivation / use case for changing the behavior?
The webpack example should have tests working properly to be consistent with what the documentation says.

The whole example should be checked thoroughly, since it seems `npm start` is also not working properly. The page only shows "Loading..." and it never gets to load Angular.

## Environment

<pre><code>
Angular version: 5.0.0 (according to package.json)

Browser:
- [X] Chrome (desktop) version 61.0.3163
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.1
- Platform:  Windows 10

Others:
Npm version: 5.5.1

**Comment by trotyl** [comment]
The webpack guide will be removed soon, please refer to https://github.com/angular/angular/pull/20213 for more information.
