### ISSUE TITLE
Check if `checkAndUpdateNodeInline` function can be removed

### ISSUE THREAD

**Issue by maximusk** [angular/angular#20534]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently there are two types of functions to run change detection:

- `checkAndUpdateNodeDynamic`
- `checkAndUpdateNodeInline`

## Expected behavior

- `checkAndUpdateNodeInline` can probably be removed

## What is the motivation / use case for changing the behavior?

`checkAndUpdateNodeInline` was implemented for performance boost. However, according to [this comment](https://twitter.com/maxim_koretskyi/status/850771011482132481) by [@bmeurer](https://twitter.com/bmeurer) the dynamic version should now be faster.

**Comment by vicb** [comment]
Closing this as not actionnable. Re-open if you have numbers.

Two things to consider here:
- bleeding edge chrome is not a pre-requisite to use Angular - it has to be fast in all (recent enough) supported browsers,
- calling the dynamic version also has a perf impact at the call site: we need to create an array -> time to create an array & memory pressure.
