### ISSUE TITLE
NgForm controls not updating on id/name change and view values are lost

### ISSUE THREAD

**Issue by mralien** [angular/angular#20546]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

NgForm.controles loses element it's id/name changed. View value of such element becomes empty

## Expected behavior

NgForm.controls should correctly updates & view values should be keeped

## Minimal reproduction of the problem with instructions

http://embed.plnkr.co/lZpkfSaR4ze3mf1pQ7i1/

1. Create template with form which contains inputs inside ngFor with id/name depending on index (for example "idx{{i}}")
2. Add 3 elements to array with some property
3. Remove second -> id/name of third element will change from "idx2" to "idx1". View value still correct
4. Add one more element -> view value of 2nd element will become empty. In ngForm.components we can see idx0 and idx2, but not idx1 which was removed and replaced in step 3

## Environment

<pre><code>
Angular version: 5.0.2

Browser:
- [x] Chrome (desktop) version 62.0.3202.94 x64
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.3
- NPM version: v5.5.1
- Platform:  Windows

Others:

</code></pre>

**Comment by tytskyi** [comment]
@mralien does this works as you expect? https://plnkr.co/edit/GR1N41whQ9Mj5mWLM8tR?p=preview

**Comment by mralien** [comment]
Yes, thanks, it works fine. Unexpected NgForm behavior.

**Comment by olezt** [comment]
@tytskyi Nice! Did the trick!
In case someone else is looking what is changed in the plunkr:  
Added in view `trackBy: trackByIndex;` and then at the component:
```
trackByIndex(index: number) {
    return index;
  }`

**Comment by kara** [comment]
We don't really support dynamically changing the names of ngModels yet, so marking this as a feature request

**Comment by olezt** [comment]
@kara If you check @tytskyi's plunkr you will see that it actually works using `trackBy`.

**Comment by kara** [comment]
Yep, it does fix the problem, but ngModel itself still does not support name changes. I'd consider that a separate feature.
