### ISSUE TITLE
Security in java backend for Angular App controlled by OAM

### ISSUE THREAD

**Issue by BhargaviChodisetti** [angular/angular#20545]
Hi All,

I have developed Angular(2) application , backend is developed in Java (JAX-RS). Both Angular and backend has same context.

Server side: Application is OAM controlled , when I open app page in browser i get OAM login page; once login, app home page opens.

Now i have requirement, put extra security in app, if OAM goes wrong/down app should work. To achieve this i used jspFilters and in web.xml added CLIENT_CERT, FORM. With these changes my app is showing extra login page after OAM login page.
But i am expecting; if OAM authenticates first then carry forward internal login and shouldn't ask login again. If OAM is not there then ask for login.

can anyone help me, how can I achieve this.

Thanks in advance
Ch

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
