### ISSUE TITLE
gulp test.unit.js - broken

### ISSUE THREAD

**Issue by vicb** [angular/angular#2054]
on master 863eb3c559e8c175885ceb0e2d5b4e5c535bf467

The first run is ok.

Then:
- No more progress traces are displayed after a file changes (the tests re-run but no progress / error reported), see traces below,
- Sometimes a second browser window gets opened ?

linked to the de-dedup of the logs & different processes ?

```
[11:01:39] Finished '!broccoli.js.dev' after 1.93 s
[11:01:39] Starting '!test.unit.js/karma-run'...
[11:01:40] Finished '!test.unit.js/karma-run' after 270 ms
[11:02:46] Starting '!broccoli.js.dev'...
Tree diff:          funnel-output_path-u7JTbQRS.tmp, duration:    51ms,     1 changes detected (files:   251, directories:  221) [
  * angular2/test/core/compiler/element_injector_spec.js
]
Tree diff:          funnel-output_path-u7JTbQRS.tmp, duration:    29ms,     0 changes detected (files:   128, directories:  221)
Tree diff:                   funnel-dest_9MaEXB.tmp, duration:    30ms,     1 changes detected (files:   379, directories:  123) [
  * angular2/test/core/compiler/element_injector_spec.es6
]
Tree diff:                   funnel-dest_rmC7Kc.tmp, duration:    74ms,     4 changes detected (files:  2009, directories:  252) [
  * es5/angular2/test/core/compiler/element_injector_spec.js
  * es5/angular2/test/core/compiler/element_injector_spec.js.map
  * es6/angular2/test/core/compiler/element_injector_spec.es6
  * es6/angular2/test/core/compiler/element_injector_spec.map
]

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
Funnel                                        | 637ms               
Funnel                                        | 467ms               
DiffingTraceurCompiler                        | 250ms               
DiffingTraceurCompiler                        | 207ms               
TreeMerger                                    | 180ms               
TreeMerger                                    | 165ms               
ReplaceFilter                                 | 135ms               

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
Funnel (74)                                   | 1337ms (18 ms)      
DiffingTraceurCompiler (2)                    | 457ms (228 ms)      
TreeMerger (7)                                | 405ms (57 ms)       
ReplaceFilter (3)                             | 238ms (79 ms)       

[11:02:49] Finished '!broccoli.js.dev' after 2.56 s
[11:02:49] Starting '!test.unit.js/karma-run'...
[11:02:49] Finished '!test.unit.js/karma-run' after 246 ms
<<< Where are my test progress ??? >>>
```

**Comment by vicb** [comment]
should we have a test suite for the test suite (that don't use the test suite) ?

**Comment by gdi2290** [comment]
![](http://i2.kym-cdn.com/photos/images/original/000/001/122/xzibit-happy.jpg)

**Comment by vicb** [comment]
Tried to revert all commits up to the different process -> no success
Tried to revert the protractor/jasmine update -> no success

The other thing I can think of is a fresh `npm i` I did yesterday. It was working before

**Comment by tbosch** [comment]
Please ping Igor, he was working on a fix

**Comment by vicb** [comment]
ping @IgorMinar

**Comment by IgorMinar** [comment]
I'm in meeting, I'll look into this in a few hours. is this reproducable by others?

**Comment by caitp** [comment]
Working for me on c5996529c3ed4be68565a02e1406ad8ccbe8c473 (https://gist.github.com/caitp/c8f7aa367acfcd20e735)

**Comment by mlaval** [comment]
Same issue on my Windows laptop.

In addition, `'!broccoli.js.dev'`task is run twice after launching `gulp test.unit.js`, and each run takes 40-50s ... For info, it is even slower on a MBP from 2011.
Is anyone experiencing such slowness ?

**Comment by IgorMinar** [comment]
@vicb I tried to repro this, but wasn't successful. are you still seeing this issue? can we pair tomorrow morning. I'm free between 9 and 10am PDT.

@mlaval can you create a separate issue about the slowness and post the output log into the issue?

**Comment by vicb** [comment]
So happy that I can close this issue this morning (it works for me now). THANKS !!!
