### ISSUE TITLE
HttpHeaders forEach is missing

### ISSUE THREAD

**Issue by dfenstermaker** [angular/angular#20548]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The HttpHeaders of common/http module do not show the forEach function or many of the functions it actually has at runtime. Despite the interface saying this is not available the headers at runtime appear to be Headers spec compliant. This makes it very difficult to work aruond and to get typescript to allow me to cast HttpHeaders to a Headers object.

## Expected behavior
I assume HttpHeaders is a minimal interface that at runtime is actually a Headers implementation. This should be reflected in the interface. 

## Minimal reproduction of the problem with instructions
plknr does not support the latest version of Angular but I don't believe that this issue would require a demo to test out. Its as simple as attempting to cast the import {HttpHeaders } from '@angular/common/http' to a Headers object.

## What is the motivation / use case for changing the behavior?
Make it easier to work with browser headers spec

## Environment

<pre><code>
Angular version: 4.4.5

Browser:
- [X] Chrome (desktop) Version 61.0.3163.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.4
- Platform:  Mac
- Typescript 2.5.3

Others:
vscode Version 1.18.0 (1.18.0)
</code></pre>

**Comment by trotyl** [comment]
The documentation is auto-generated, [`forEach()`](https://github.com/angular/angular/blob/5.0.2/packages/common/http/src/headers.ts#L206-L213) wan't listed due to it's a non-public API (only for Angular itself).

For introducing new public API, this one should be `Feature request`.
