### ISSUE TITLE
Handling browser tabs

### ISSUE THREAD

**Issue by sharathc10** [angular/angular#20544]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Our Angular application uses a router with a canActivate guard.  When the user creates a new tab on the browser and then tabs back, no lifecycle hooks run.  Furthermore, the router guard is not run at all.   To get around this problem, we are using the following in javascript in the index.html file which requires us to reload the page. 

    var hidden, visibilityChange;
    if (typeof document.hidden !== "undefined") { 
        hidden = "hidden";
        visibilityChange = "visibilitychange";
    }

    function handleVisibilityChange() {
        if (!document[hidden]) {
            var initialPage = window.location.pathname;
            window.location.replace(initialPage);
        }
    }

    document.addEventListener(visibilityChange, handleVisibilityChange, false);

Can you suggest a better way to implement the above?

## Expected behavior

When the browser tab is hit, ideally the router canActivate should run

## Minimal reproduction of the problem with instructions
 Code above

## What is the motivation / use case for changing the behavior?

Self Explanatory

## Environment

<pre><code>
Angular version: 4.0.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [x ] Chrome (iOS) version 62.0.3202.94
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by sharathc10** [comment]
@Toxicable - I posted this issue on StackOverflow - the only answer I have received is to use HostListener.  That is fine but I think using either browser tabs and back/forward buttons should run the canActivate guard.  The HostListener solution requires reloading the page every time.

**Comment by sharathc10** [comment]
@Toxicable  - FYI the stackoverflow post - https://stackoverflow.com/questions/47512979/why-dont-lifecycle-hooks-run-when-changing-tabs-in-my-app
