### ISSUE TITLE
regression(compiler): new transformer pipeline breaks .tsx support

### ISSUE THREAD

**Issue by trotyl** [angular/angular#20555]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

After introducing to new transformer pipeline based compiler (directly https://github.com/angular/angular/commit/506d2e98a475305a89cb8a4ab11d376582d64e60), the compatibility for `.tsx` files are completely broken.

Currently compiler will generate an `app.component.tsx` file with content of `app.component.metadata.json` due to the failure of file rename. (https://github.com/angular/angular/blob/5.1.0-beta.1/packages/compiler-cli/src/transformers/program.ts#L341)

Update: The root problem is compiler [reuse extension of source file for generated files](https://github.com/angular/angular/blob/5.1.0-beta.1/packages/compiler/src/aot/compiler.ts#L106), however, the generated files should always be `.ts` in AOT.

## Expected behavior

Angular compiler should support `.tsx` file as it used to be. (See https://github.com/angular/angular/issues/19691#issuecomment-336222081, easy to reproduce in 4.x)

## Minimal reproduction of the problem with instructions

1. Create a project: `ng new --minimal tsx-problem`;
2. Add `"jsx": "react"` to `tsconfig.json`;
3. Rename `app.component.ts` to `app.component.tsx`;
4. Run `ngc -p src/tsconfig.app.json`;

## What is the motivation / use case for changing the behavior?

Since Angular compiler is just an extension of TypeScript compiler, it should still support TypeScript functionalities. (And it was supported before using TypeScript transformer API)

And it's quite easy to fix (I will raise a PR to fix it).

## Environment

<pre><code>
Angular version: All 5.x versions

Browser: Not relevant
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
@josephliccini This one is about using `.tsx` for Angular resources, like `app.component.tsx` or `app.module.tsx`.

**Comment by josephliccini** [comment]
Ah I see that makes sense! I intentionally separated my tsx files but for those cases you've described, yes this makes sense

**Comment by sandangel** [comment]
@trotyl I have not see any resource, document on angular.io about using angular with tsx. Is this possible? I found myself often use inline template  but it cannot be formatted by prettier. Can't wait for this PR being merged.
