### ISSUE TITLE
feat(router): View Encapsulation to inherit outlet's attributes

### ISSUE THREAD

**Issue by Karasuni** [angular/angular#20560]
## I'm submitting a...
<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
`router-outlet`'s attributes are not passed on to the dynamically routed component. A page with the following definition:
```html
  <!-- src/app/app.component.html -->
  <app-header></app-header>
  <app-navbar></app-navbar>
  <router-outlet content></router-outlet>
  <app-footer></app-footer>
```
Results in this generated code:
```html
  <!-- dist/index.html -->
  <app-root _nghost-c0 ng-version="5.0.2">
    <app-header _ngcontent-c0 _nghost-c1>...</app-header>
    <app-navbar _ngcontent-c0 _nghost-c2>...</app-navbar>
    <router-outlet _ngcontent-c0 content></router-outlet>
    <app-home _nghost-c6>...</app-home>
    <app-footer _ngcontent-c0 _nghost-c3>...</app-footer>
  </app-root>
```
Where the routed component `app-home` is injected as a successive sibling of `router-outlet` but without the inheritance of it's attributes. A css selector relying on these attributes will not be able to select the routed component:
```css
  [content] {
    grid-area: content;
    background: greenyellow;
  }
```

(Even if the attribute would be inherited a current bug with the default `Emulated` view encapsulation https://github.com/angular/angular/issues/20558 would still prevent css selection)

## Expected behavior
Routed components should inherit `router-outlet`'s attributes for dynamically decorating a routed component.

## Minimal reproduction of the problem with instructions
A full example of the issue can be found in [this application](https://stackblitz.com/edit/angular-css-grid-holy-grail).

## What is the motivation / use case for changing the behavior?
The router outlet's dynamic behavior of injecting a component should behave similar to the static injection of a component (e.g. `<app-header header></app-header>` vs `<router-outlet content></router-outlet>`). As such decorators should be passed on from the `router-outlet` to the routed component.

## Environment
<pre><code>Angular version: 5.0.2</code></pre>

**Comment by mhevery** [comment]
I think what you are asking is that the `<app-home>` component should be a child of `<router-outlet>`. The current behavior is by design since the `<router-outlet>` acts like anchor rather than the container. 

Directives can't be dynamically added to the container.
