### ISSUE TITLE
Modal Popup Input Box creates cursor issue in IOS 11 version

### ISSUE THREAD

**Issue by dotnetexpert** [angular/angular#20563]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently, when a modal popup opens & when I type anything in Input Box, then the cursor will Blink outside the Input Box. 

The text is appearing in the input box, but the problem is that the cursor blinks outside the Input box.

This issue will arise in IOS 11 version.

## Expected behavior
It should be pointing within the Input Box. I think its not compatible with IOS 11.

## Environment

<pre><code>
 "dependencies": {
    "@angular/animations": "^4.1.3",
    "@angular/common": "^4.1.3",
    "@angular/compiler": "^4.1.3",
    "@angular/compiler-cli": "^4.1.3",
    "@angular/core": "^4.1.3",
    "@angular/forms": "^4.1.3",
    "@angular/http": "^4.1.3",
    "@angular/platform-browser": "^4.1.3",
    "@angular/platform-browser-dynamic": "^4.1.3",
    "@angular/platform-server": "^4.1.3",
    "@angular/router": "^4.1.3",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.26",
    "angular2-google-maps": "^0.17.0",
    "angular2-notifications": "^0.7.8",
    "bootstrap": "^4.0.0-alpha.6",
    "core-js": "^2.4.1",
    "moment": "^2.19.1",
    "ng2-google-place-autocomplete": "^1.4.2",
    "ngx-modialog": "^3.0.4",
    "ngx-pipes": "^2.0.5",
    "primeng": "^4.1.0",
    "rxjs": "^5.1.0",
    "typescript": "2.3.4",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.1.1",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "2.5.45",
    "@types/node": "~6.0.60",
    "angular2-perfect-scrollbar": "^2.0.6",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "2.3.4"
  }

Browser:
- [ ] Chrome (iOS) version XX
- [ ] Safari (iOS) version XX
 
</code></pre>

**Comment by mhevery** [comment]
This is not Angular related, it seems to be iOS issue therefore we are closing it.
