### ISSUE TITLE
Service workers error and multiply in dev mode

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#20567]
This might be a CLI issue, I'm not sure. The core problem is that it's very easy for a user to shoot themselves in the foot and get unpredictable behavior with dev mode service workers.

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Repro steps
`ng new too-many-sw -service-worker`
Edit `/src/app/app.module.ts` line from `environment.production ? ServiceWorkerModule.register('/ngsw-worker.js') : []` to `ServiceWorkerModule.register('/ngsw-worker.js')`
`ng serve` 

## Observed behavior
```ERROR Error: Uncaught (in promise): TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
    at resolvePromise (webpack-internal:///../../../../zone.js/dist/zone.js:824)
    at eval (webpack-internal:///../../../../zone.js/dist/zone.js:746)
    at eval (webpack-internal:///../../../../zone.js/dist/zone.js:762)
    at ZoneDelegate.invoke (webpack-internal:///../../../../zone.js/dist/zone.js:392)
    at Object.onInvoke (webpack-internal:///../../../core/esm5/core.js:4824)
    at ZoneDelegate.invoke (webpack-internal:///../../../../zone.js/dist/zone.js:391)
    at Zone.run (webpack-internal:///../../../../zone.js/dist/zone.js:142)
    at eval (webpack-internal:///../../../../zone.js/dist/zone.js:873)
    at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:425)
    at Object.onInvokeTask (webpack-internal:///../../../core/esm5/core.js:4815)
```
On every refresh of the browser, a new service worker is installed.
![image](https://user-images.githubusercontent.com/165056/33088866-c528a03e-cea3-11e7-8f8b-ff11da7e970e.png)

## Expected behavior
Developers adding service worker to their project in dev mode (which isn't recommended) should not see an error, and shouldn't get multiple service workers.

## What is the motivation / use case for changing the behavior?
Lots of developers will be adding service workers to their applications and it's very complex to manage dev-mode only or prod-mode only code (you can't use `constructor(swPush: SwPush)` for example because that will only work in prod mode.

## Environment

<pre><code>
Angular CLI: 1.6.0-beta.0
Node: 8.4.0
OS: linux x64
Angular: 5.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cli: 1.6.0-beta.0
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.36
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0-beta.0
@schematics/angular: 0.1.5
typescript: 2.4.2
webpack: 3.8.1

**Comment by alxhub** [comment]
You cannot use Service Workers in dev mode with the CLI, it's explicitly disabled. Even the build support will not work unless `--prod` is set.
