### ISSUE TITLE
Upgrade angular/angular to the latest version of yarn

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#20566]
We are currently on 1.0.2, which is super old. Work breakdown:

- [x] update env.sh
- [x] update circleci docker container (@alexeagle has info)
- [x] update the lock files in the `/`,`aio/` and anywhere else if there are more lock files
   (it's not clear how this should be done, I believe updating the yarn version and then doing `yarn install` should autoupdate the lock file without messing with the dependencies, but we need to verify that)
- [x] test everything on CI
- [x] add `yarn` to `engines` field in all package.json to enforce the version of yarn to be used (the check-env.js) script is often overlooked by people resulting in bad dependency installs and confusion
- [x] update any md docs under `docs/` if they reference yarn and its version number

**Comment by IgorMinar** [comment]
@ocombe could you take this one on please?

**Comment by alexeagle** [comment]
https://github.com/alexeagle/ngcontainer is the source for the docker image
we run on circleCI

**Comment by ocombe** [comment]
About the task "update the lock files", just installing with the new version of yarn will not change the lockfiles, and it will still install the same packages.
I can run `yarn upgrade` if we want to get the latest packages, this is the list of outdated packages for `/`:
![image](https://user-images.githubusercontent.com/265378/34714776-c6940050-f52a-11e7-83ac-3c0ecd0ce17e.png)

But if we don't want to change the versions right now, we can do nothing but update the yarn dependency and everything will work the same

**Comment by ocombe** [comment]
Apparently the circleCI image is already using yarn 1.3.2, can you confirm @alexeagle ?

**Comment by alexeagle** [comment]
Angular's .circleci/config.yml is currently at 0.0.8:

$ docker run --rm -it angular/ngcontainer:0.0.8
circleci@39e48d726025:/$ yarn --version
1.3.2
