### ISSUE TITLE
Decimal Pipe in component not wroking

### ISSUE THREAD

**Issue by jisheedpdm** [angular/angular#20577]
I'm using Decimal Pipe for formatting a number in my component.ts file as

DecimalPipe.prototype.transform(this.time.minutes, "2.0")

I have upgraded to Angular 5 and added the deprecated pipe in my module as

import { CommonModule, DeprecatedI18NPipesModule } from '@angular/common';

@NgModule({
  imports: [
    CommonModule,
    DeprecatedI18NPipesModule
],
})  (there are other imports too)

But I'm getting console error like

ERROR TypeError: Cannot read property 'toLowerCase' of undefined
    at findLocaleData (locale_data_api.js:514)
    at getLocaleNumberFormat (locale_data_api.js:369)
    at formatNumber$1 (format_number.js:41)
    at Object.DecimalPipe.transform (number_pipe.js:67)
    at SessionTimeOutComponent.ngDoCheck (session-timeout.component.ts:69)
    at checkAndUpdateDirectiveInline (provider.js:253)
    at checkAndUpdateNodeInline (view.js:472)
    at checkAndUpdateNode (view.js:415)
    at debugCheckAndUpdateNode (services.js:504)
    at debugCheckDirectivesFn (services.js:445)

## I'm submitting a...
Error 

## Current behavior
Getting error in console

## Expected behavior
Should work with Decimal Pipe

## Environment

Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version 62.0.3202.94
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.3
- Platform:  Windows 7
Typesript - 2.4.2

Others:

</code></pre>
@brad @evmar @jdalton @jesperronn @mprobst

**Comment by jotatoledo** [comment]
Add a plnkr or reproduction

**Comment by evmar** [comment]
Can we revoke bug tracker access for people who indiscriminately spam people with @-mentions in their bug reports?

**Comment by erichmuller** [comment]
@jisheedpdm check your code to see if you are forgetting to replace the imports. If you want to use the deprecated pipes you should import:

`import {DeprecatedDecimalPipe} from "@angular/common";`
instead of
`import {DecimalPipe} from "@angular/common";`

**Comment by pkozlowski-opensource** [comment]
Going to close for now as we don't have reproduce scenario. Please open a new issue following our GH issue template if the problem persists.
