### ISSUE TITLE
Service Worker doesn´t seem to cache index.html

### ISSUE THREAD

**Issue by wambowams** [angular/angular#20578]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
After installing the service worker with following ngsw-config.json some resources get cached others not.
<pre><code>
{
  "index": "/index.html",
  "appData": {
  },
  "assetGroups": [{
    "name": "shell",
    "installMode": "prefetch",
    "resources": {
      "files": [
        "/assets/**/*",
        "/favicon.ico",
        "/index.html"
      ],
      "versionedFiles": [
        "/*.bundle.js",
        "/*.bundle.css",
        "/*.svg",
        "/*.eot"
      ],
      "urls": [
        "https://fonts.googleapis.com/**",
        "https://fonts.gstatic.com/**"
      ]
    }
  }],
  "dataGroups": [{
    "name": "api",
    "urls": [
      "https://example.com/**"
    ],
    "cacheConfig": {
      "strategy": "freshness",
      "maxSize": 200,
      "maxAge": "1h",
      "timeout": "10s"
    }
  }]
}
</code></pre>

## Expected behavior
All resources from the json file should be cached

## Minimal reproduction of the problem with instructions
Adding the new service worker to the project and building the project with following commands:
    ng build --prod && node_modules\\.bin\\ngsw-config dist src\\ngsw-config.json && copy node_modules\\@angular\\service-worker\\ngsw-worker.js dist

## What is the motivation / use case for changing the behavior?
Service worker should work as expected and serve all files when offline.

## Environment

<pre><code>
Browser:
- [x] Chrome (desktop) version 62 and 64
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version 56
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
Angular CLI: 1.5.3
Node: 6.3.1
OS: win32 x64
Angular: 5.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.3
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.36
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.3
@schematics/angular: 0.1.5
typescript: 2.4.2
webpack: 3.8.1

</code></pre>

**Comment by alxhub** [comment]
Can you link an app that reproduces this problem, @wambowams?
