### ISSUE TITLE
Error: Uncaught (in promise): SecurityError: Failed to execute 'pushState' on 'History'

### ISSUE THREAD

**Issue by hussainwali74** [angular/angular#20574]
these are my routes:
```
const routes:Routes =[
  {path:'', component:WelcomeComponent},
  {path:'profile', component: ProfileComponent},
  {path:'addcourse', component: AddcourseComponent},
  {path:'course', component: CourseComponent},
  {path:'editCourse', component: EditCourseComponent},
  {path:'addLectures', component: AddLectureComponent},
  {path:'login', component:LoginComponent},
  {path:'register', component:RegisterComponent},
  // { path: 'newform', canActivate:[AuthGuard], component:NewFomComponent},
  { path: '**', redirectTo:'', pathMatch:'full'}

```
## Current behavior

my app starts with the welcome page, when I click on login it takes me to the courses page and upon clicking a course the app should take me to the course component but it redirects to welcome page and when i click on login it gives me this error: 

> ERROR Error: Uncaught (in promise): SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'http://%28login%29/' cannot be created in a document with origin 'http://localhost:4200' and URL 'http://localhost:4200/'.
> Error: Failed to execute 'pushState' on 'History': A history state object with URL 'http://%28login%29/' cannot be created in a document with origin 'http://localhost:4200' and URL 'http://localhost:4200/'.
> 

I have looked up similar issues and all of them suggest to check the base href, in my app it is set to / so no issues there. Can anybody please what am I doing wrong??

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by VladyslavKurmaz** [comment]
@hussainwali74 Have you had a luck to resolve this issue?
I faced with the same issue too.
