### ISSUE TITLE
Validators.minLength(1) doesn't work on FormArray

### ISSUE THREAD

**Issue by mohlendo** [angular/angular#20583]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Providing a validator for minLength = 1 marks an empty FormArray as valid.

## Expected behavior
Since the array of the FormArray has a length of 0 it should mark the FormArray as invalid.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/gjuPr6E9PMMSVL4gY9FD?p=preview

## Environment

<pre><code>
Angular version: 5.0.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.1
- Platform:  Mac

Others:

</code></pre>

**Comment by UserGalileo** [comment]
This was a (debatable) decision of the team: if the value is empty, we don't return errors, and this is the function responsible for checking the value (in https://github.com/angular/angular/blob/master/packages/forms/src/validators.ts):

```
function isEmptyInputValue(value: any): boolean {
  // we don't check for string here so it also works with arrays
  return value == null || value.length === 0;
}
```
As you can see, there's a comment saying that empty arrays are considered an empty value (and don't return an error).
However, I agree with you, an empty array shouldn't considered an empty value but simply an array with length 0; it should be easy to adjust this function by modifying the returned condition, this way:

`return value == null || (value.length === 0 && !Array.isArray(value))`

**Comment by mohlendo** [comment]
Another solution could be to special case for `minLenght(1)`. In that case I would not check for empty input value and just check the length. 
It does not make sense to have a control that is optional but must have `minLenght(1)` - `minLenght(1)` and `requried` are actually the same.

**Comment by kara** [comment]
To clarify, 0 length arrays are considered an empty value so we can properly support select multiple controls with the required validator (see https://github.com/angular/angular/issues/12274). That would break if we were to flip this. In addition, it would be a breaking change, and I'm not convinced that we would be making things less confusing.  While I agree that it is indeed odd that `minLength(1)` would also need `required` to work, it is this way to be consistent with how regular HTML5 forms work, and we try to keep things in sync where we can. For these reasons, it's not likely that we'll be changing over the logic.

**Comment by ruibasecone** [comment]
I bumped into this but with a FormControl with string value instead of a FormArray. I spent a couple of hours until figuring out this was the origin of the "problem". Maybe the `minLenght(1)` behaviour should be better documented?
