### ISSUE TITLE
model-bound <input> elements inside an *ngFor behave badly

### ISSUE THREAD

**Issue by tbertran** [angular/angular#20589]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When entering a character in an `<input>` field that was generated inside `*ngFor`, that character is magically populating the next `<input>` field on the screen. Also not that the model does *not* reflect that new "magic" value. 
[edited for clarification]

## Expected behavior
Values entered by the user inside a given `input` field should only populate that `input` field and not bleed into the next one.

## Minimal reproduction of the problem with instructions
https://jsfiddle.net/tbertran/b136qrwt/

## What is the motivation / use case for changing the behavior?
Using `*ngFor` to avoid unnecessarily repeating `input` fields in my HTML file.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ x] Chrome (desktop) Windows Version 62.0.3202.94 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox Windows version 56.0.2
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by pkozlowski-opensource** [comment]
You need to use `trackBy` for such cases: https://angular.io/api/common/NgForOf

**Comment by UserGalileo** [comment]
See [this](https://stackoverflow.com/questions/42322968/angular2-dynamic-input-field-lose-focus-when-input-changes) for details as you need to use trackBy inside your *ngFor. You're using an array of primitive types (strings) which, being compared by value, are removed from the DOM with every kaystroke (note that you also lose focus at every keystroke).

This is the working component:

```
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
        <input 
          *ngFor="let x of myArray; let idx = index; trackBy: trackArray" 
          type="text" [(ngModel)]="myArray[idx]"/>
        <br>{{myArray.toString()}}
  `
})
export class AppComponent  {
  myArray = ["","","",""];

  trackArray(index, item) {
    return index;
  }
}
```
