### ISSUE TITLE
Not possible to use Angular without Zone because of Router.setUpLocationChangeListener

### ISSUE THREAD

**Issue by ArekSliwa** [angular/angular#20582]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When using Angular Router it's not possible to use new Angular 5 feature ngZone: 'noop' .
In the console we can see: Zone is not defined error.
Router method setUpLocationChangeListener is using Zone.
screenshots:
[zone is not defined](https://ibb.co/cXPaYR)
[Router.setUpLocationChangeListener method implementation](https://ibb.co/dnzaYR)

## Expected behavior

Angular Router is able to work without Zone.

## Minimal reproduction of the problem with instructions

1. Just fire angular app with
platformBrowserDynamic()
    .bootstrapModule(AppModule, {
        ngZone: 'noop'
    });
2. comment import 'zone.js/dist/zone'; in polyfills
3. Try to use angular Router in some easy case.

## Environment

<pre><code>
Angular version: 5.0.1

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by JiaLiPassion** [comment]
@mhevery , should we provide a empty Zone implementation when use NgNoopZone? 

such as for  this issue,
```javascript
if (!global['Zone']) {
  function NoopZone() {
    wrap(func) {
      return func;
    }
    ...
  }
  
  global['Zone'] = NoopZone;
  NoopZone.current = new NoopZone();
}
```

or provide a `auto changeDetection` version?

```javascript
if (!global['Zone']) {
  function NoopZone() {
    wrap(func) {
      return function() {
        const result = func.apply(this, arguments);
        changeDetectRef.detectChange();
      } ;
    }
    ...
  }
  
  global['Zone'] = NoopZone;
  NoopZone.current = new NoopZone();
}
```

**Comment by mhevery** [comment]
@JiaLiPassion Instead of creating a noop mock, we should just remove that code from router. It seems like that https://github.com/angular/angular/commit/25e5b2fdf00175291d8719cc57f0bd4d130c2c4a#diff-7f0963cbc503a361ded7d2bfec5f01b9R386 is there because zone.js does not properly patch the `lociation.subscribe`???

**Comment by JiaLiPassion** [comment]
@mhevery , got it, I will look into it.

**Comment by ArekSliwa** [comment]
Thanks a lot for your attention to this issue! seems I can close it?

**Comment by JiaLiPassion** [comment]
@ArekSliwa, if my PR is correct, after merge , this issue will be closed automatically, thank you for posting the issue.

**Comment by me-12** [comment]
@JiaLiPassion Thank you for your PR. I am currently running into the same issue and was wondering if you could give an update on this issue. It looks like Travis is complaining about errors while testing.

**Comment by JiaLiPassion** [comment]
@me-12 , the travis is passed in the PR, do you mean some test failed in your travis build ?

**Comment by me-12** [comment]
@JiaLiPassion Sorry my bad. I was looking at your fork instead of the PR. https://github.com/angular/angular/pull/20640

So we are just waiting for @mhevery to review the PR again. Right?

**Comment by JiaLiPassion** [comment]
@me-12, yeah, I think so. please wait for a while.

**Comment by glebmachine** [comment]
Any news?

**Comment by glebmachine** [comment]
Wow, hope finally it works)
