### ISSUE TITLE
Styling issue in template-syntax guide

### ISSUE THREAD

**Issue by brunnerh** [angular/angular#20594]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The box here is black along with the text color:

![image](https://user-images.githubusercontent.com/834235/33149217-3cf4fbae-cfcf-11e7-8182-a992cdabe8ea.png)

**Comment by gkalpak** [comment]
Probably some temporary issue on your side (maybe network-related).
Normally, it looks pretty green to me :grin: ![binding-to-component](https://user-images.githubusercontent.com/8604205/33180494-913d2366-d075-11e7-940b-9cb34f6c747f.png)

**Comment by brunnerh** [comment]
Oh. Indeed, now it works, probably should have probed that with dev tools. (That was actually consistent yesterday, though. Wonder what caused it...)
