### ISSUE TITLE
'A spec to verify the test environment' test example does not work 

### ISSUE THREAD

**Issue by madcodemonkey** [angular/angular#20596]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If you follow the  'A spec to verify the test environment' [example](https://angular.io/generated/zips/testing/1st-specs.testing.zip,) from the [Angular testing page](https://angular.io/guide/testing), you will get the following error when you try to run it:
Error in config file!   Cannot find module 'karma-coverage-istanbul-reporter'

You probably want to check the rest of the examples too.  One of the guys I work with did mention that the examples were all jacked up.  I now know what they were talking about.

## Expected behavior
It should run the Karma test runner as shown on the testing page.

## Minimal reproduction of the problem with instructions
1. Download 'A spec to verify the test environment' from https://angular.io/generated/zips/testing/1st-specs.testing.zip
2. Unzip it to a folder
3. Open a command prompt
4.  run npm install
5.  run  npm test

## What is the motivation / use case for changing the behavior?
Your examples should work for novices like myself while we are trying to learn the product.

## Environment
<pre><code>
Angular version: 5.0.0

Browser:
- [X ] Chrome (desktop) version 62.0.3202.94
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 </code></pre>

**Comment by madcodemonkey** [comment]
Examples have errors.

**Comment by petebacondarwin** [comment]
This issue is out of date and no longer relevant. The examples in the testing guides are now working.
