### ISSUE TITLE
Library code cannot utilize critical services

### ISSUE THREAD

**Issue by bradley-dotnet** [angular/angular#20598]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If a packaged library is included in an Angular project, many framework provided services are not available to it, such as Router and ViewContainerRef. For example:

>StaticInjectorError[Router]: 
  StaticInjectorError[Router]: 
    NullInjectorError: No provider for Router!

Other services have errors, such as Http having CookieXSRFStrategy.configureRequest throw the following error:

> Cannot read property 'getCookie' of null

## Expected behavior
These services to be available to library code by default, or in the worst case there is a mechanism to provide them.

## Minimal reproduction of the problem with instructions
1. Start a package library from https://github.com/dherges/ng-packaged
2. In the default service of that seed, inject `Router` via the constructor
3. Build the package using `npm run buid:lib`
4. Create a basic angular application with routing using the CLI
5. npm link to the created package
6. Add a dependency to the package's service in app component
7. Serve the application and open the dev console to see the errors

## What is the motivation / use case for changing the behavior?
The current restrictions effectively make building a maintainable platform around Angular impossible as complex libraries simply fail.

Specifically, I am trying to make a library that contains modules preconfigured with routes, guards, and complex components. Some of these components rely on ng-bootstrap (which of course is listed as a dependency of the library). So far this has proved impossible using the Angular package format and webpack; which I would really like to use as it seems to be the "official" approach.

## Environment

<pre><code>
Angular version: 5.0.2

Browser:
- [ x] Chrome (desktop) version 62.0
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.1  
- Platform:  Windows

Others:
The site is being served through IIS express. 
</code></pre>

I have found a partial workaround as I can export an abstract class from the package that the application implements to provide the restricted functionality. Unfortunately this approach doesn't seem to apply to all the restricted providers.

**Comment by Toxicable** [comment]
You just need to provide the services you want to the NgModule just like any other module

**Comment by bradley-dotnet** [comment]
Ok, how do I do that for an Angular provided service. Can I just put `Router` in the `providers` list of app module?

**Comment by Toxicable** [comment]
No, you import the RouterModule like normal

**Comment by bradley-dotnet** [comment]
It is imported; routing works fine as long as `Router` isn't used by the library code.

**Comment by mhevery** [comment]
This is issue tracking for the Angular project. Please take support questions to one of our forums: 

- http://stackoverflow.com/questions/tagged/angular2
- https://gitter.im/angular/angular
- https://groups.google.com/forum/#!forum/angular

**Comment by bradley-dotnet** [comment]
@mhevery With all due respect it seems like this is a bug with Angular; the previous member that discussed it with me expected what I already had to work.

I have posted on gitter to no effect, and can try StackOverflow but in my opinion the fact that this doesn't work is a **major** bug in the angular framework.

**Comment by verbeeckjan** [comment]
I am having the same issue. For me ViewContainerRef is not found when I use a component which contains an *ngFor from and angular library.

@mhevery Are you absolutely sure this can't be a bug?

Error originating from the template of the component:
```
ERROR Error: StaticInjectorError[ViewContainerRef]: 
  StaticInjectorError[ViewContainerRef]: 
    NullInjectorError: No provider for ViewContainerRef!
    at _NullInjector.get (core.js:923)
    at resolveToken (core.js:1211)
    at tryResolveToken (core.js:1153)
    at StaticInjector.get (core.js:1024)
    at resolveToken (core.js:1211)
    at tryResolveToken (core.js:1153)
    at StaticInjector.get (core.js:1024)
    at resolveNgModuleDep (core.js:10585)
    at NgModuleRef_.get (core.js:11806)
    at resolveDep (core.js:12302)
```

**Comment by skol-pro** [comment]
In case someone is using npm link(s), the following does the job:

In .angular-cli.json add/replace:

```json
"defaults": {
    "styleExt": "css",
    "component": {},
    "build": {
        "preserveSymlinks": true
    }
}
```

**Comment by bradley-dotnet** [comment]
@skol-pro I'll try that and report on the results, but the compiler seems to traverse the symlink fine. Its just at runtime we have issues.

**Comment by skol-pro** [comment]
@bradley-dotnet It was always fine with the compile on my side too, I was only getting the error at runtime. However, it seems to be really related to npm link(s)... :-/

**Comment by bradley-dotnet** [comment]
@skol-pro That worked great; Hopefully whatever caused this issue in the first place can be resolved so we don't have to resort to that impossible to find hack....

**Comment by jcjolley** [comment]
I am running into this issue _without_ using npm link.  I think there may be a bug in Angular 5, as I started getting StaticInjectorError[Router] errors after upgraded to Angular 5.

**Comment by SublimeProphets** [comment]
@skol-pro your workaround with --preserve-symlinks as parameter or the defaults itself is working perfect and allows me to use *ngIf if a library (as own npm package). Without preserve-symlinks it will fail on ng serve but it still compile perfectly even with AOT. Looking forward to a solution. 

I am kind of sure that npm link causing several problems (at least running on win10). If i install the exact same library as a normal npm package through commandline it works like a charm, but i've i link it then it breaks for sure.
