### ISSUE TITLE
Unable to AOT compile when loading a component with Webpack's require.context()

### ISSUE THREAD

**Issue by mattdsteele** [angular/angular#20595]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Webpack's `require.context()` enables [build-time component loading](https://webpack.js.org/guides/dependency-management/#require-context). As an example:

```typescript
// dynamically-loaded.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-dynamically-loaded',
  template: `<p>This component was loaded dynamically!</p>`
})
export default class DynamicallyLoadedComponent {}

```

```typescript
// app.module.ts
declare var require: any;
const dynamicContext = require.context(
  '.',
  false,
  /dynamically-loaded.component.ts/
);
const dynamicComponents = dynamicContext
  .keys()
  .map(dynamicContext)
  .map(comp => comp.default);

@NgModule({
  declarations: [AppComponent, ...dynamicComponents],
```

When running this using the JIT compiler (aka `ng serve`), the app runs without issue.

Running with AOT (aka `ng serve --aot`),  I get this error:

```
ERROR in Error: Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'dynamicComponents'. Consider exporting the symbol (position 11:7 in the original .ts file), resolving symbol AppModule in C:/Users/IGEN261/code/test/dynamicloading/src/app/app.module.ts, resolving symbol AppModule in C:/Users/IGEN261/code/test/dynamicloading/src/app/app.module.ts, resolving symbol AppModule in C:/Users/IGEN261/code/test/dynamicloading/src/app/app.module.ts
```

## Expected behavior

I'd expect the AOT compiler to understand how to use this component.

## Minimal reproduction of the problem with instructions

**Reproduction repo**: https://github.com/mattdsteele/angular-webpack-dynamic-loading

Commit with breaking change: https://github.com/mattdsteele/angular-webpack-dynamic-loading/commit/6779ff4c96bb5943016891c851054e97bbadaff4

Run `ng serve --aot` to see error.

## What is the motivation / use case for changing the behavior?

I'm porting an "style guide" application, currently written in AngularJS and built with Webpack. Each example in the style guide is built as an AngularJS component each in their own file. We use Webpack to dynamically load these files into our application, so we don't have to maintain a bunch of `import` statements that might get out of sync.

This pattern works with Angular, but not when built with AOT. I would very much like to use AOT :)

## Environment

<pre><code>
Angular CLI: 1.5.3
Node: 6.12.0
OS: win32 x64
Angular: 5.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.3
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.36
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.3
@schematics/angular: 0.1.5
typescript: 2.4.2
webpack: 3.8.1

</code></pre>

**Comment by Toxicable** [comment]
use `System.import` to lazy load chunks

**Comment by mattdsteele** [comment]
@Toxicable I can't use a glob/regex with `System.import`, can I? My goal is to register an unknown set of components with Angular without having to keep a set of `import` statements in sync.

**Comment by Toxicable** [comment]
You can doing that with Angular and remain statically analyzable.
If Angular dosen't know about the template at compile time then it cannot find it and compile it

**Comment by mattdsteele** [comment]
My hope was that since `require.context()` is a compile-time step where the context is deterministic after it's been resolved, that it would play well with AOT. But I might be getting the ordering of Webpack and the AOT tooling wrong?

**Comment by Toxicable** [comment]
`System.import` isn't the ES `import something from 'somewhere'`
you can dynamically pass it a string, however it must be able to somewhat determine the location of the module you're trying to load at build time, this is so that Webpack is able to make a chunk out of the external module which it can then lazy loaded.
From my understanding it's handled at the same time, webpack will resolve the module then the compiler will compile as it passed through webpacks loaders

**Comment by mattdsteele** [comment]
Hmm, we might be talking about different "dynamic loader" mechanisms. I'm referring to `require.context()`, which is synchronous, doesn't create a new chunk in Webpack, and doesn't allow for anything that can't be determined at compile time. Documented at https://webpack.js.org/guides/dependency-management/#require-context

This is a separate mechanism from `System.import`, `import()`, `require.ensure()`, or the other async imports that perform code splitting, and allow for more dynamic module resolution at runtime. Documented at https://webpack.js.org/guides/code-splitting/#dynamic-imports

I'd expect AOT *not* to support `System.import`, but thought `require.context()` could be.

**Comment by JoostK** [comment]
When using AOT, the compiler needs to be able to statically understand the declarations list in an `NgModule`, as all components that is AOT compiles need to reference the declarables that have been used in its template. As a consequence, dynamic declarations as requested are not feasible in AOT mode.

If the dynamically loaded components don't have to use each other, then you may be able to create a dedicated NgModule for each individual component. This ensures that the compilation scope for a template is statically known such that the AOT template code can be generated. The act of actually loading that using some mechanism is then up to you. Please be aware that the usage of Webpack within the CLI is an implementation detail.
