### ISSUE TITLE
npm install hangs downloading chromedriver_mac32.zip

### ISSUE THREAD

**Issue by mprobst** [angular/angular#2060]
After deleting the entire `node_modules` folder and running `npm install`, lots of stuff flies by, but the build then hangs here:

```
> angular@2.0.0-alpha.24 postinstall /Users/martinprobst/src/angular
> node tools/chromedriverpatch.js && webdriver-manager update && bower install && gulp pubget.dart && tsd reinstall --config modules/angular2/tsd.json && tsd reinstall --config tools/tsd.json

Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.14/chromedriver_mac32.zip...
```

Interestingly `Ctrl-C` and then re-running install seems to succeed?

**Comment by tbosch** [comment]
I saw this one time before as well...

**Comment by vicb** [comment]
@tbosch stay positive please... I've seen it working once ;)

**Comment by IgorMinar** [comment]
@juliemr do you know what this is about?

server/network issue?

**Comment by juliemr** [comment]
Haven't seen this one before. Let me check networks...

**Comment by juliemr** [comment]
It's all working within ~5 seconds for me. Protractor just downloads using `request`. 

Is this only when completely re-running `npm install`?

**Comment by pkozlowski-opensource** [comment]
Hmm, I can see it quite often after wiping out node_modules. Didn't dig into it, though....

**Comment by IgorMinar** [comment]
that makes me think even more that it's a network issue rather

**Comment by mhevery** [comment]
Sounds like network issue. Can this be closed?

**Comment by juliemr** [comment]
Yes, let's close this and bother Protractor with https://github.com/angular/protractor/issues/1857
