### ISSUE TITLE
can i user interface as input?

### ISSUE THREAD

**Issue by linhuiw** [angular/angular#20602]
## can i user interface as input?

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Expected behavior

```javascript
interface TypesInterface {
  foo?: string;
  bar?: string
}

@Component({
  selector: 'Test',
  template: `<div></div>`,
})
class Point extends Chart {
  @Input(TypesInterface);
  ngAfterViewInit() {
     //*
     // I just want to get foo & bar as Input
     //*
     console.log(this.foo, this.bar);
  }
}
```

**Comment by mlc-mlapis** [comment]
@linhuiw ... interfaces are just typing things in TS ... they are clear away from run-time.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by linhuiw** [comment]
OK, Tks.
