### ISSUE TITLE
Locale files imports are not compatible with angular universal

### ISSUE THREAD

**Issue by yosigolan** [angular/angular#20605]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
when adding the locales imports for the new i18n framework like this (in the app.module):

import localeEn from '@angular/common/locales/en';     
registerLocaleData(localeEn);

and compiling with universal server side rendering, an error appears when starting the node server:

C:\GitRepos\WebApp\node_modules\@angular\common\locales\en.js:10
export default [
^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.oYeS (C:\GitRepos\WebApp\dist\en\server\main.bundle.js:1:1619104)

## Expected behavior
the locales imports should support angular universal and no errors should appear.

## Minimal reproduction of the problem with instructions
1. clone this project: https://github.com/yosigolan/ng5-locale-universal-bug
2. run "npm install"
3. run "npm run build-server"
4. run node server

## Environment

<pre><code>
Angular version: ^5.0.0
also reproduces with the latest version

For Tooling issues:
- Node version: 8.6.0
- Platform:   Windows

Others:
as a workaround i am adding the imports in the browser rendering module only.
</code></pre>

**Comment by vicb** [comment]
@ocombe I have assigned this issue to you as I think you have started looking at this.

**Comment by ocombe** [comment]
There's a PR for that already but @IgorMinar would like to wait for v6... https://github.com/angular/angular/pull/20624
maybe we'll have to generate both type of files (I'd rather not, but v6 is still very far away)

**Comment by hettiger** [comment]
Any updates @ocombe about your discussion with @IgorMinar ?

**Comment by ocombe** [comment]
We now ship files as UMD files in v6, it should work fine server side. I haven't tested it though, can you try with rc5?

**Comment by hettiger** [comment]
@ocombe Sorry I thought your discussion was about patching v5. My bad.

**Comment by yosigolan** [comment]
Hey.
this is fixed now in angular 6, you can close the issue.

**Comment by ocombe** [comment]
thanks!
