### ISSUE TITLE
Can deactivate not working with Outh0 logout.

### ISSUE THREAD

**Issue by rajesh-siliconharborlabs** [angular/angular#20613]
When I am clicked on logout and set false to confirm box and then after i click for any other tab and click ok on confirm box it is log out also.

Thanks

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
