### ISSUE TITLE
Unhandled Promise rejection: matchedQueriesDsl.forEach is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: matchedQueriesDsl.forEach is not a function

### ISSUE THREAD

**Issue by vinjog** [angular/angular#20614]
Hi,
It looks working fine before installing/uninstalling some of the packages from my project.
but now, getting above error after application run. The project get compiled successful, however after seen developer tool found this error.
Following is the environment -
depdencencies
@angular/animations 5.0.3
@angular/common 5.0.3
@angular/compiler 5.0.3
@angular/core 5.0.3
@angular/forms 5.0.3
@angular/http 5.0.3
@angular/platform-browser 5.0.3
@angular/platform-browser-dynamic 5.0.3
@angular/router 5.0.3
angular-mocks 1.6.6
core-js 2.5.1
ng2-toastr 4.1.2
rxjs 5.5.2
zone.js 0.8.18

devDependencies
@angular/cli 1.5.4
@angular/compiler-cli 5.0.3
@angular/language-service 5.0.3
2.8.2
2.0.3
8.0.53
codelyzer 4.0.1
jasmine-core 2.8.0
jasmine-spec-reporter 4.2.1
karma 1.7.1
karma-chrome-launcher 2.2.0
karma-cli 1.0.1
karma-coverage-istanbul-reporter 1.3.0
karma-jasmine 1.1.0
karma-jasmine-html-reporter 0.2.2
protractor 5.2.0
ts-node 3.3.0
tslint 5.8.0
typescript 2.6.1

![angularerror](https://user-images.githubusercontent.com/33949084/33199098-d5f431da-d114-11e7-992e-f64389960d39.JPG)

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by vinjog** [comment]
Pls. find attached demo code

**Comment by vinjog** [comment]
Pls. find attached demo code....






[src.zip](https://github.com/angular/angular/files/1501234/src.zip)

**Comment by mhevery** [comment]
Thank you for submitting the issue. All issues require a [plunker](https://plnkr.co/) which demonstrates the problem and how to reproduce it. Please re-open the issue or create a new issue once you have a reproducible use case.

We are sorry that we are so aggressive on closing the issues. We are overwhelmed with the number of issues we get, and so we only have time to look at the ones which are easy for us to reproduce.
