### ISSUE TITLE
Angular 4 with Flex application

### ISSUE THREAD

**Issue by aryanisml** [angular/angular#20612]
Is any library or plugin to communicate the angular 4 with flex application ? Need to share the data between flex and angular application

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
