### ISSUE TITLE
could not open https://angular.io/ in Ipad.

### ISSUE THREAD

**Issue by mystikraz** [angular/angular#20617]
I couldn't open your website in my Ipad. It looks like you have some rendering issue with IPad.

**Comment by gkalpak** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
