### ISSUE TITLE
Cannot use SystemJS in Angular5

### ISSUE THREAD

**Issue by tinganho** [angular/angular#20618]
Is there a reason I cannot setup Angular5 using SystemJS? I need to use SystemJS for a very specific reason and cannot use Webpack.

I've got the following error:

```ts
Error: No provider for PlatformRef!
```

When I inspect the code, from this function in `@angular/core/bundles/core.umd.js`:
```ts
/**
 * Creates a platform.
 * Platforms have to be eagerly created via this function.
 *
 * \@experimental APIs related to application bootstrap are currently under review.
 * @param {?} injector
 * @return {?}
 */
function createPlatform(injector) {
    // ... Some code 
    var /** @type {?} */ inits = injector.get(PLATFORM_INITIALIZER, null);
    // ... Som code 
```

After debugging, it seems like I need to inject some classes in order for everything to kick in. Could you provide an example of how to things up in SystemJS?

My `main.ts` file look like this:
```ts
// We must import reflect meta data on top, because of an angular bug
// @link https://github.com/angular/angular/issues/15890#issuecomment-322257479
import 'reflect-metadata';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module';

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.log(err));

```

**Comment by mlc-mlapis** [comment]
@tinganho ... you can use SystemJS without any problem. If you have a problem then demonstrate the simplest demo and then it is possible to help you. Plunker is using System JS so create the reproduction easily ...

**Comment by tinganho** [comment]
OK, I will try to provide a minimum verifiable repro.

**Comment by tinganho** [comment]
Turned out some of my dependencies was not up to date. But thanks!
