### ISSUE TITLE
ChangeDetectionStrategy.OnPush not running properly with @Input modified programmatically (outside of a template binding)  

### ISSUE THREAD

**Issue by UserGalileo** [angular/angular#20611]
## I'm submitting a...

<pre><code>
[X] Bug report  
</code></pre>

## Current behavior

I'm trying to set an Input property of a component which is projected into another one. I tried, for performance reasons, to use _ChangeDetectionStrategy.OnPush_ on the child component, but I've come across a strange bug.
With _ChangeDetectionStrategy.Default_ everything works fine, but using OnPush I get a strange behavior. It appears that the OnPush component doesn't receive the new input property. Please see my example which clarifies the problem.
~~I think the problem could be confined in ContentChildren, ViewChildren (same problem) or QueryList, and I believe it's the latter but I'm not sure about it.~~
It's been clarified that OnPush just looks at inputs which are set **in the template** and not via JavaScript. Although this kinda makes sense thinking about the current framework's logic, it doesn't in a sense that the child component using OnPush isn't "thinking with its own brain", but it's the parent who decides if re-rendering should occur for it, based only on its template bindings.

## Expected behavior

The component's Input property should be received and the component re-rendered even with ChangeDetectionStrategy.OnPush.

## Minimal reproduction of the problem with instructions
This is the demo I made, with a simple <accordion> component which is responsible for the state of all its <toggle> components which are being projected inside of it.

https://stackblitz.com/edit/angular-accordion

Please see the comment in _toggle.component.ts_ and try changing Default to **onPush**

## What is the motivation / use case for changing the behavior?

Compound components often **need** to be used with OnPush in order to optimize performance with large applications.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [X] Chrome (desktop) version 62

**Comment by alexzuza** [comment]
> It appears that the OnPush component doesn't receive the new input property

Indeed there are no input properties `active` here. Angular doesn't produce update logic for `@Input` in ngfactory if it doesn't appear in template. For example, compare it with

`<toggle title="Title 1" #t1 [active]="t1.active" ></toggle>`

https://stackblitz.com/edit/angular-hgndju?file=app/app.component.html

**Comment by UserGalileo** [comment]
Actually that "active" property does appear in the template, there's an ngIf based on it. :) I really can't see why I should use your technique, passing a property via ContentChildren is really what makes Compound Components a great design pattern and that should be the perfect usecase for OnPush. The component itself has no problem with OnPush, it DOES have problems with ContentChildren/ViewChildren or QueryList, I don't know why.

**Comment by mlc-mlapis** [comment]
@UserGalileo ... but you ignore how `OnPush` principally works ... it follows changes on `@Input()`s ... especially if a reference has changed on `@Input()` when you pass object or array ... and if there is no change on them then CD is not run. This is all.

**Comment by UserGalileo** [comment]
@mlc-mlapis I don't ignore how OnPush works, I use really often. I'm sorry, but did you see my example? The input property IS changing, but instead of using template binding, since I get the components with ContentChildren I change the property imperatively:
`this.toggle.active = false
`
The input is passed down again to the component but it doesn't re-run CD. Also there are strange behaviors when clicking on an item, clicking on another one and re-clicking on the previous one.

**Comment by sarunint** [comment]
@UserGalileo I'm not entirely accurate on this topic either, but I'll say that you are modifying the class member directly which Angular's change detection mechanism cannot detect that. It can detect only change  that occur to the binding.

Again, not entirely sure. I should summon @maximusk, the change detection god, for this topic.

**Comment by UserGalileo** [comment]
Thank you @sarunint I appreciate that :) However, if it's intended as a feature, I must say that this should be changed, modifying instance members shouldn't be a problem at all and shouldn't interfere with CDS.OnPush!
Waiting for the change detection god to clarify, thanks ;)

**Comment by mlc-mlapis** [comment]
@UserGalileo ... it is also not related to `ContentChildren` or `ViewChildren` at all ... if you add the following `ngOnInit` to `ToggleComponent` you can see that CD is also not invoked when `active` is asynchronously switch to `true` = equivalent of a click ...
```
export class ToggleComponent {
  @Input() active = false;
  @Input() title = "Default title";
  @Output() setActive = new EventEmitter();

  ngOnInit() {
    setTimeout(() => {
      console.log('Async call ...');
      this.active = true;
    }, 1000);
  }
}
```

**Comment by alexzuza** [comment]
As i wrote early angular won't check your `active` input because there is nothing to check.
![cd](https://user-images.githubusercontent.com/4223314/33220292-6fbf8c6a-d160-11e7-83f7-924a4d8f1430.png)

So it means that angular won't call [updateProp](https://github.com/angular/angular/blob/24cf8b326918e0694dfcdcf48635b5325060827a/packages/core/src/view/provider.ts#L423-L429) for your inputs and therefore your component will be hidden change detection.

We shouldn't change component property directly from any place if we want to abide by the unidirectional data flow

**Comment by alexzuza** [comment]
One more solution for you

```
  _active: boolean = false;

  @Input()
  set active(val) {
    this._active = val;
    this.cdRef.markForCheck();

  }

  get active() {
    return this._active;
  }

  constructor(private cdRef: ChangeDetectorRef) {}
```

https://stackblitz.com/edit/angular-m9gamy?file=app/toggle.component.ts

**Comment by UserGalileo** [comment]
@alexzuza I get how OnPush works, that's why I marked it as a bug, I don't feel it's right :) Even if I don't pass the prop from the template, it should be change detected. I get that Angular is template-focused, but this is kinda limiting. 
Also, this isn't breaking unidirectional data flow at all: the child emits an event which is subscribed to the parent, and the parent is passing down props again. This is an everyday-situation with other frameworks like React, and ContentChildren is the only way for handling the scenario and having the same result in clarity :) 
Thanks for the alternative solution with setter/getters, but I'm not actually developing anything with that component at the moment. I'm not trying to fix THAT component, I'm trying to say what I feel about this situation and what is wrong with Change Detection (obviously imho).
Since we don't have anything like shouldComponentUpdate in React, OnPush is the best thing we can do in order to have performant components: I'd like to work with it without any workaround ;) And if it's intended to work like this (like others said), maybe we can discuss that and make CD a little better!

**Comment by maximusk** [comment]
@UserGalileo 

> Even if I don't pass the prop from the template, it should be change detected

`OnPush` is tightly bound to the input bindings. What's important is that Angular checks the second part of the binding (`prop` in the example case), not the first:

`<child [i]="prop">`

And it does so when checking parent component. That's the mechanism of change detection. I don't see any way it could be changed. You can read more about operations in 
[Everything you need to know about change detection in Angular](https://blog.angularindepth.com/everything-you-need-to-know-about-change-detection-in-angular-8006c51d206f).

Also, here is the simple case that demonstrates the limitation. The AComponent **won't** render `updated` name in 2 seconds:

```
@Component({
    selector: 'my-app',
    template: `
        <h1>Hello {{name}}</h1>
        <a-comp></a-comp>
    `
})
export class AppComponent {
    @ViewChild(AComponent) a;

    constructor() {
        setTimeout(() => {
            this.a.name = 'updated';
        }, 2000);
    }
}


@Component({
    selector: 'a-comp',
    template: `
        <h2>I am A component, name is: {{name}}</h2>
    `,
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class AComponent {
    name = 'Jane';
}
```

**Comment by UserGalileo** [comment]
Hi @maximusk and thanks for your time, I also read your blog posts time ago and I found them very useful and well written. However, I just don't feel this as a reliable behavior at all...

> Inspecting @Input on child components isn't enough

That's exactly what happens in React! In React there are 2 features we can use to handle this scenario: PureComponents, which shallow check the properties, and the shouldComponentUpdate lifecycle hook for "hacking" into the rendering process. In Angular, since we have nothing that does the check for us inside the component and since we haven't got a hook for the rendering process, PureComponents are meant to be those ones with CDS.OnPush, why wouldn't it be the right thing to inspect inputs on child components? 

**Please, don't get me wrong.** I love both Angular and React, sorry for bringing other libraries to the table, but I feel this is kinda limiting. See the accordion example: the logic behind it should be completely hidden by the accordion itself, it shouldn't be exposed to the developer. The dev shouldn't care about that input property, it should be passed down from the accordion itself. And as I can see, the only ways to make it work flawlessly are: 
1) Stop using OnPush on components which may be projected (but who knows? At that point, I'd have to stop using OnPush everywhere since everything can be projected)
2) Do some ""hacking"" with the change detector, which doesn't feel right to me and shouldn't be abused (and in large applications, I just can't see how to not abuse of it)

**Comment by UserGalileo** [comment]
The third and most distant option I see is to have a third CDS which just removes CD and listens to the component's inputs and re-renders, nothing more. But I'm thinking out loud :)

**Comment by maximusk** [comment]
@UserGalileo 

> and the shouldComponentUpdate lifecycle hook for "hacking" into the rendering process. In Angular, since we have nothing that does the check for us inside the component

We have `ngDoCheck` on a component which is called even if change detection is not run. [You can utilize it in your case](https://stackblitz.com/edit/angular-zvrd6t?file=app/toggle.component.ts):

```
export class ToggleComponent {
  _active;
  @Input() active = false;
  @Input() title = "Default title";
  @Output() setActive = new EventEmitter();

  constructor(private cd: ChangeDetectorRef) {}

  ngOnInit() { this._active = this.active;  }

  ngDoCheck() {
    if (this._active !== this.active) {
        this._active = this.active;
        this.cd.markForCheck();
    }
  }
```

Read [If you think `ngDoCheck` means your component is being checked — read this article](https://blog.angularindepth.com/if-you-think-ngdocheck-means-your-component-is-being-checked-read-this-article-36ce63a3f3e5) for more information on this hook.

> See the accordion example: the logic behind it should be completely hidden by the accordion itself, it shouldn't be exposed to the developer

Did you check how ngx-bootstrap implements accordion with templates?

**Comment by UserGalileo** [comment]
@maximusk 
My accordion was just an example made for the purpose, it's not that there aren't other ways to do it! Compound components are a beautiful design pattern to me, which makes a lot of components reusable, not only the accordion :) At this point I'm asking myself if OnPush really makes sense at all, I just wouldn't rely on this behavior honestly... Properties shouldn't need to be bound to the parent's template in order to re-render the child, for me :) I absolutely understood that that's how CD works for now but maybe something else could be done in order to have **real pure angular components**. I'm absolutely no expert on CD's internals, so I'm just throwing a tought: wouldn't it make sense if components marked with OnPush (or with a third strategy, let's say, CDS.Pure) broke their bond with the parent's change detector and put listeners on their input properties? This way, unidirectional data flow would remain, access to the parent component via DI could be disallowed, and this components would have a separate change detecor which wouldn't start checking from the parent, but from the component's inputs. Would it make sense? Just thinking out loud again :)

**Comment by maximusk** [comment]
@sarunint 

> Again, not entirely sure. I should summon @maximusk, the change detection god, for this topic.

😄

**Comment by UserGalileo** [comment]
Maybe I put it down wrong, what I meant for "bond" is exactly what you stated :) it would be useful a third CDS which could detach the component (removing the need to do it manually) from the main change detection tree and have its own tree, and that automatically listens to the component's properties. Just an idea. Using OnPush kinda scares me, knowing that if someone tries to update my component from the outside will likely cause strange behaviors... Don't know :) Again thanks for the time and for your understanding!

**Comment by admosity** [comment]
@maximusk 

> There's no bond with parent change detector. It's just that when Angular checks parent component it decides whether to run change detection for the child component or not. 

I have a scenario where a parent component is set to `OnPush` and a child component without `OnPush` is performing some async operation (like `setTimeout`). Without `OnPush` on the parent, it works as expected, but with it; it doesn't update. Due to the modularity of Angular, it's possible to have very distributed teams with varying skillsets. The way change detection is currently, every dev would have to code as if their component can be used by an `OnPush` parent (which is not as easy as when just developing normally). (example: #21780)

I have some more examples in: #22461. I did not find this issue until after...

**Comment by maximusk** [comment]
@admosity 

> Without OnPush on the parent, it works as expected, but with it; it doesn't update.

Yeah, but that's the idea of `OnPush` - to disable checks for the entire tree of components. And it's the responsibility of the parent component. But I understand your concern. Someone developing a child component can't know if its component will be used inside the parent component with `OnPush` or without it. There are some changes in the change detection mechanism coming in v6, maybe there is a mechanism specific for these situations. In any case, it's always possible to inject the `ChangeDetectorRef` and call `markForCheck`.

**Comment by admosity** [comment]
Thanks @maximusk. We'll move forward with that assumption and make it a safety precaution to develop in this way for the future.

Is it the correct assumption that setting `OnPush` on the app component essentially sets all components to `OnPush` globally?

**Comment by maximusk** [comment]
@admosity 

> Is it the correct assumption that setting OnPush on the app component essentially sets all components to OnPush globally? Or is there more at play there?

I suggest your watch [this talk](https://www.youtube.com/watch?v=WizqXZjztss) and [read this article](https://blog.angularindepth.com/everything-you-need-to-know-about-change-detection-in-angular-8006c51d206f) on change detection. Setting `OnPush` on the app component simply prevents change detection mechanism from checking app component's children unless the input bindings specified for these child components have changed.

**Comment by admosity** [comment]
Thanks! I've personally shared out your article many times for being one of the best explanations of change detection around.

I think for me it feels like a break in encapsulation. I think zone.js patched events should check if the originator of the change detection request does not have `OnPush` set - it should `markForCheck` that component automatically.

**Comment by pburgmer** [comment]
I have the same problem @UserGalileo described. I use a component from a library , which has ChangeDetectionStrategy.OnPush (pagination of ng-zorro). But I have to set the input in my typescript code.
The pagination is a ViewChild and passed to a DataSource. Same kind of structure Angular Material uses for it's DataSource and the sort header directive. When the data source changes the total amount of items on the pagination component, nothing happens.

**Comment by atscott** [comment]
Closing as the original report is working as expected. 

* The `@Input` is not being used as an input. Removing `@Input` would have no affect on the program. 
* `OnPush` means that by default the component will not be checked during change detection. It is marked for check when the inputs change from the template bindings or you call `ChangeDetectorRef#markForCheck`. This would be the solution here: change `active` to a `getter`/`setter` and call `markForCheck` in the `set`: https://stackblitz.com/edit/angular-accordion-j3yzes?file=app%2Ftoggle.component.ts
