### ISSUE TITLE
Allowing insensitive case base href url when deploy in sub folder

### ISSUE THREAD

**Issue by guerson** [angular/angular#20629]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have an MVC/Angular application that is deployed in a sub folder in our web server. 
**RouteConfig.cs**

           routes.MapRoute(
                name: "AngularViews",
                url: "{*url}", 
                defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional }
            );

**With a component route defined in app-route.ts like this :**
<pre><code>
  { path: '',
    redirectTo: '/dashboard/home',
    pathMatch: 'full'
  },

{
    path: 'dashboard',
    component: DashboardComponent,
    children: [
      {
        path: 'home',
        component: HomeComponent,
        children: [
          ...
        ]
      }
    ]
}</code></pre>
When it is deploy. The base url is set to   base href="/BETA_dashboard/" into the index.html.
When I navigate to site.com/BETA_dashboard/... is all good.
When i try site.com/beta_dashboard/... without a exact base path, it is not working.

## Expected behavior

Case sensitive or not. this should work.

## Environment

<pre><code>
  "dependencies": {
    "@angular/animations": "4.0.3",
    "@angular/common": "4.0.3",
    "@angular/compiler": "4.0.3",
    "@angular/compiler-cli": "4.0.3",
    "@angular/core": "4.0.3",
    "@angular/forms": "4.0.3",
    "@angular/http": "4.0.3",
    "@angular/platform-browser": "4.0.3",
    "@angular/platform-browser-dynamic": "4.0.3",
    "@angular/platform-server": "4.0.3",
    "@angular/router": "4.0.3",
    "@angular/upgrade": "4.0.3",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-beta.5",
    "angular-in-memory-web-api": "0.3.0",
}

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mhevery** [comment]
This is issue tracking for the Angular project. Please take support questions to one of our forums: 

- http://stackoverflow.com/questions/tagged/angular2
- https://gitter.im/angular/angular
- https://groups.google.com/forum/#!forum/angular
