### ISSUE TITLE
Compiled angular files trigger an error at runtime "No value accessor for form control with name:"

### ISSUE THREAD

**Issue by Orodan** [angular/angular#20622]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Hi,

I'm trying to update a package [(ng-selector)](https://github.com/Orodan/ng-selector/tree/develop) from angular 4 to 5, and I can't get it to work correctly.

From what I understand, since Angular 5 is only compiling files from the application fodler, to use a package from the node_modules folder, my package needs to expose js files.

To expose js files in my packages (which only exposed ts files until now), I've tried both tsc ang ngc. Here is the problem : no matter what compiler I use, I don't get compilations error. But when I import my package from js files and try to use it, I always get an error on my console saying :

```
ERROR Error: No value accessor for form control with name: 'test1'
```

I know that in most cases, this error comes from one of the following ones mistake :
- I forgot to include the FormsModule
- I did not implement correctly ControlValueAccessor
- I did not use the provider NG_VALUE_ACCESSOR

I'm saving you the trouble to check, it is not the case here. My package was working fine with Angular 4.
It is a problem with the compilation of my typescript files, because if I put my package files directly into my appplication folder, change the import (instead of importing from node_modules folder, I import from the local package files), then everything works fine.

## Expected behavior

I would expect my package to work correctly, even when I'm exposing js files and not ts files directly anymore.

## Minimal reproduction of the problem with instructions

1. git clone git@github.com:Orodan/ng-selector.git
2. cd ng-selector
2. git checkout develop
3. npm install
4. npm run build-tsc or npm run build-ngc according to what compilation you want to test
5. cd ngSelectorDemo
6. npm install
7. npm start

## Environment

<pre><code>
Angular version: 5.0.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.1.3  
- Platform:  Mac/Linux

Thanks for the help

**Comment by mhevery** [comment]
Thank you for submitting the issue. All issues require a [plunker](https://plnkr.co/) which demonstrates the problem and how to reproduce it. Please re-open the issue or create a new issue once you have a reproducible use case.

We are sorry that we are so aggressive on closing the issues. We are overwhelmed with the number of issues we get, and so we only have time to look at the ones which are easy for us to reproduce.
