### ISSUE TITLE
Injecting HTML into an element via the innerHTML input binding ignores CSS styling.

### ISSUE THREAD

**Issue by geekmdio** [angular/angular#20625]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently, elements included in a component via performing an input binding on innerHTML will ignore CSS styling described in the components CSS file. 

## Expected behavior

HTML data provided to a component HTML via input binding of innerHTML will respect CSS styling rules for the component. 

## Minimal reproduction of the problem with instructions

component.ts
----------------
htmlData="&lt;span class='funky-text'&gt;Text goes here &lt;/span&gt;";

component.html
------------------
 &lt;div [innerHTML]="htmlData"&gt; &lt;/div&gt;

component.css
-----------------
.funky-text {
   color: red;
}

OUTPUT: Text goes here (in black)
DESIRED OUTPUT: <text style="color: red">Text goes here</text> (in red)

Of note, inspection of the elements on the page confirm that the innerHTML input binding was successful, including the class selectors.

## What is the motivation / use case for changing the behavior?

I would like to serve structured HTML data to an angular application. The application will have a component that binds this data. I would like to apply custom styling to key words and phrases in the served data.

## Environment

<pre><code>
Angular version: 4.4.6

Browser:
- [x ] Chrome (desktop) version  62.0.3202.94
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version 11.0.1
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.4  
- Platform:  Mac 

Others:
VS Code

</code></pre>

**Comment by mlc-mlapis** [comment]
@tnesbit450 ... it's related to difference between `ViewEncapsulation.None` an `ViewEncapsulation.Emulated ` ... read more about it.

**Comment by geekmdio** [comment]
@mlc-mlapis Thanks for the reply. At least conceptually, I was aware of the various DOM encapsulation techniques available in Angular. I have one point of confusion, however. My understanding of ViewEncapsulation.Emulated (default) is that the styling local to the components CSS should be applied. In fact, encapsulation of styling to the component level is the purpose and consistent with my desired behavior.

The component's styling, however, is not being applied within the scope of the component even though the elements are being rendered properly. Because this rendering is within the component's scope, I would expect that the default emulated view encapsulation would not (or should not) have this behavior.

Just in case it was missed, this behavior is only observed when using the [innerHTML] binding. The styling performs as expected otherwise.

My understanding of ViewEncapsulation.None would is that global styles will being applied to my components. That's not what I would prefer. 

If there is a connection that I'm missing, I would appreciate an explanation or link because I'm not quite seeing it. It's possible that it's just not possible for me to accomplish what I'm attempting, and if that's the case, that knowledge would be useful as well.

**Comment by mlc-mlapis** [comment]
@geekmdio ... if you inscept the source of your displayed page in a browser ... especially `<HEAD>` tag and also the concrete element you can see that your component CSS style is named using a name similar to the convention as ... `.funky-text[_ngcontent-c2] {...}`.

This is the reason why your `htmlData` (using just `class='funky-text'`) applied through `[innerHTML]` can't directly work with the component's styles ... just the scoping is not the same.

The explanation is that ViewEncapsulation.Emulated mode has to encapsulate the styles for just a component and you are mixing it with global styles ... or you are expecting that `[innerHTML]` is able to parse your HTML code and update all its classes and other things ... in relation to the actual component  but this is not true.

Read more for example ...
https://blog.thoughtram.io/angular/2015/06/25/styling-angular-2-components.html
https://blog.thoughtram.io/angular/2015/06/29/shadow-dom-strategies-in-angular2.html
https://toddmotto.com/emulated-native-shadow-dom-angular-2-view-encapsulation
https://medium.com/google-developer-experts/angular-advanced-styling-guide-v4-f0765616e635

**Comment by geekmdio** [comment]
@mlc-mlapis - Thank you again for your time! 

The links cover content I was familiar with. But, your last comment does provide me very useful information. You say "or you are expecting that [innerHTML] is able to parse your HTML code and update all its classes and other things ... in relation to the actual component but this is not true." and that is exactly what I was expecting. 

It appears that in order for this to work I would have to apply a global style as the component CSS will not be appended with the component-specific string which allows for emulation of view encapsulation. Native would be a decent option, but it's still only supported in select browsers.

I thank you for your time.
