### ISSUE TITLE
docs(aio) Example Usage for read metadata property in ContentChildren

### ISSUE THREAD

**Issue by aravindfz** [angular/angular#20627]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## What is the motivation / use case for changing the behavior?

Sample Usage of metadata properties.

## Environment

<pre><code>
Angular version: 5.0.1

**Comment by petebacondarwin** [comment]
This is a request for an author to write some samples of how to use the metadata for `ContentChildren`.

**Comment by jenniferfell** [comment]
API https://angular.io/api/core/ContentChildren

**Comment by ajitsinghkaler** [comment]
@kapunahelewong I think we can close this issue

**Comment by kapunahelewong** [comment]
Thank you, @ajitsinghkaler!
