### ISSUE TITLE
:host does not work when applied in scss? 

### ISSUE THREAD

**Issue by DewskiK** [angular/angular#20626]
I tried to apply style to host component but it just does not work.

:host {
 background-color: #000;
}

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
