### ISSUE TITLE
Can you provide convenience for developers?

### ISSUE THREAD

**Issue by jiangjianyu** [angular/angular#20631]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When I run ng serve, I want to use the cell phone to open it(My computer and phone in the same Wifi).
Like reactjs. When you run  'npm start' ,you can see like this:
![la7av87 jus74q56r tv zt](https://user-images.githubusercontent.com/31642247/33237460-8f144b82-d2af-11e7-903d-26426f01822e.png)
Angular is this:
![tnr w bke13 d4ue_juvkmc](https://user-images.githubusercontent.com/31642247/33237500-043e10a0-d2b0-11e7-9fdd-df0c7a906453.png)
Can you provide convenience for developers?

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [X] Chrome (Android) version XX
- [X ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [X] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sarunint** [comment]
This issue is for [angular/angular-cli](https://github.com/angular/angular-cli) repo. Please open a new issue there instead.
