### ISSUE TITLE
@ContentChildren(TypeComponent) returns undefined if "read" is TemplateRef

### ISSUE THREAD

**Issue by crisz** [angular/angular#20635]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In a component with a content, if I ask the `QueryList` of the content children without providing any option, it works properly. But if I want to read the TemplateRef  (So I set `read: TemplateRef` it returns an array of `undefined` (as many `undefined`s as the component is repeated)

## Expected behavior

The `QueryList` object should wrap an array of `TemplateRef`s or throw an error, instead it just wraps an array of `undefined`s.
According to [official documentation](https://angular.io/api/core/TemplateRef):

>  [...] you can query for the TemplateRef from a Component or a Directive via Query.

And `@ContentChildren()` is a [Query](https://angular.io/api/core/Query), so I expected a normal behavior.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-bmpzzk?file=app%2Fparent.component.ts

## What is the motivation / use case for changing the behavior?

I googled a lot before opening this issue and there is no documentation at all about the use of `read: TemplateRef` as option in `@ContentChildren()`, so I don't understand why it's not working and why it's returning an array of `undefined`s. 

I asked a [question on StackOverflow](https://stackoverflow.com/questions/47486933/contentchildren-returns-a-querylist-of-undefined-if-read-templateref) and I've been said that I need to wrap each `ChildComponent` in a `<ng-template>` tag and it actually works, but:
1) I don't understand the reason why I need to wrap each "content" component in a `<ng-template>`, is it a workaround? 
2) It prevents us to share components and provide a tidy public interface for other users. I need this behavior in a complex component and I don't want to introduce a breaking change asking other users to wrap each child component in a `<ng-template>`, it's just ugly and tedious.
3) If there's an actual reason why it returns an array of `undefined`s, I think it should throw an error instead. There's a lack of documentation and if a user as me finds `undefined` instead of the expected behavior, he or she doesn't know why and what's the meaning.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version 62.0.3202.94
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.2.1  
- Platform:  Windows 10

Others:

</code></pre>

**Comment by sandangel** [comment]
I think this is what you need.
```ts
@ContentChildren(ChildComponent, {read: ElementRef}) children: QueryList<ElementRef>;
```

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by pkozlowski-opensource** [comment]
@sandangel is correct here.

**Comment by bernatgy** [comment]
I'm leaving this here because of search results! If you think it should not be here, please remove or tell me. I searched for "_ContentChild is undefined_" for 2 days, and there were no helpful results "except this".

In my case, the problem was that I didn't export the directive I was looking for from it's module.
### Setup (_SharedModule_):
```typescript
// ****** THIS WAS NOT EXPORTED IN IT'S MODULE ******
@Directive({
  selector: '[admGridCellTemplate]'
})
export class GridCellTemplateDirective {
  constructor() { }
}

@Component({
  selector: 'adm-grid-column',
  template: ''
})
export class GridColumnComponent implements AfterContentInit {
  @ContentChild(GridCellTemplateDirective)
  template: GridCellTemplateDirective; 

  ngAfterContentInit(): void {
    // ****** THIS LOGGED undefined ******
    console.log('adm-grid-column template ', this.template);
  }
}
```

### Usage (_AppModule_):

```html
<adm-grid>
  <adm-grid-column>
    <ng-template admGridCellTemplate></ng-template>
  </adm-grid-column>
  <adm-grid-column></adm-grid-column>
  <adm-grid-column></adm-grid-column>
</adm-grid>
```

**Comment by bernatgy** [comment]
Oh my God..... I just ran into the same problem and found my own solution.... 🤣🤣

**Comment by pookdeveloper** [comment]
@bernatgy  please add the solution ! :)
