### ISSUE TITLE
Exception causing language service to crash

### ISSUE THREAD

**Issue by BorntraegerMarc** [angular/angular#20636]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Language service fails due to exception in VSCode. See also this issue: https://github.com/angular/vscode-ng-language-service/issues/197

I see the error in VSCode: "The Angular Language Service server crashed 5 times in the last 3 minutes. The server will not be restarted."

Error:
```
SyntaxError: Unexpected token ;
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\BorntraegerMarc\.vscode\extensions\Angular.ng-template-0.1.7\server\documents.js:3:10)
[Info  - 8:22:19 AM] Connection to server got closed. Server will restart.
C:\Users\BorntraegerMarc\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\typescript\lib\typescript.js:79436
}.call(this, exports, require, module, __filename, __dirname); });
```

## Expected behavior

Does not crash.

## Minimal reproduction of the problem with instructions

Install the plugin in VSCode.

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [X] VSCode
 
For Tooling issues:
- Node version: v8.9.1 
- Platform:  Windows 

Others:

</code></pre>

**Comment by RoyiNamir** [comment]
Confirm :  happens here also.

![image](https://user-images.githubusercontent.com/2842123/52666547-46cb6980-2f17-11e9-9f1a-2767b1bd28c2.png)


![image](https://user-images.githubusercontent.com/2842123/52666566-50ed6800-2f17-11e9-85d9-97415c217c78.png)


![image](https://user-images.githubusercontent.com/2842123/52666577-56e34900-2f17-11e9-8637-334b3394ab45.png)


![image](https://user-images.githubusercontent.com/2842123/52666606-6a8eaf80-2f17-11e9-9aae-f1ad108c6687.png)


![image](https://user-images.githubusercontent.com/2842123/52666611-6f536380-2f17-11e9-8c5a-b948d56c2518.png)

**Comment by JoostK** [comment]
Closing as obsolete as it's not clear what caused these crashes, and they have likely been resolved.
