### ISSUE TITLE
Server Side Rendering with TransferState Module doesn't seem to be working properly

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#20638]
## I'm submitting a...

<pre><code>[x ] Bug report</code></pre>

## Current behavior

I am using TransferState Module to cached http response on server side but it doesn't seem to work.

What I did was, added **ServerTransferStateModule** to **AppServerModule** and **BrowserTransferStateModule** to **AppModule** as suggested here https://next.angular.io/api/platform-browser/TransferState

Then I added below interceptor, which intercepts each http request and:

- when on server, executes request and stores response in cache.
- when on client, check the cache if cached response exists, it returns it otherwise executes request.

```
import { Injectable, Inject, PLATFORM_ID } from '@angular/core';
import { isPlatformServer } from '@angular/common';
import { TransferState, makeStateKey } from '@angular/platform-browser';
import { HttpEvent, HttpInterceptor, HttpHandler, HttpRequest, HttpResponse, HttpErrorResponse } from '@angular/common/http';

import { Observable } from 'rxjs/Observable';
import { of } from "rxjs/observable/of";
import { catchError, tap } from 'rxjs/operators';

const CACHE_KEY = makeStateKey('httpCacheKey');

@Injectable()
export class MyInterceptor implements HttpInterceptor {

  private isServer = isPlatformServer(this.platformId);

  constructor(
    @Inject(PLATFORM_ID) private platformId,
    private transferState: TransferState,
    @Inject('BASE_URL') private baseUrl: string) { }

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {

    let modifiedRequest: any;

    let isLocalRequest: boolean = !req.url.startsWith('http');

    if (isLocalRequest) {

      //skip cache check if the request method isn't GET.
      if (req.method == 'GET') {
        // check and serve cached response, if it exists
        const cachedResponse = this.transferState.get(CACHE_KEY, null as any);

        if (cachedResponse) {
          let modifiedResponse = new HttpResponse<any>({ headers: cachedResponse.headers, body: cachedResponse.body, status: cachedResponse.status, statusText: cachedResponse.statusText, url: cachedResponse.url });
          return of(modifiedResponse);
        }
      }

      // Clone the request to add the new header.
      modifiedRequest = req.clone({ headers: req.headers, url: this.baseUrl + req.url, body: req.body });
    }

    return next.handle(isLocalRequest ? modifiedRequest : req)
      .pipe(tap((event: HttpEvent<any>) => {
        if (event instanceof HttpResponse) {
          if (this.isServer && isLocalRequest) {
            this.transferState.set(CACHE_KEY, event as any);
          }
        }
      }));
  }
}
```

I do see the response being cached and transferred to client, I see below script tag in the markup returned from server:

```
<script id="ng-cli-universal-state" type="application/json">{&q;httpCacheKey&q;:{&q;headers&q;:{&q;normalizedNames&q;:{},&q;lazyUpdate&q;:null},&q;status&q;:200,&q;statusText&q;:&q;OK&q;,&q;url&q;:&q;http://localhost:49805/api/SampleData/WeatherForecasts&q;,&q;ok&q;:true,&q;type&q;:4,&q;body&q;:[{&q;dateFormatted&q;:&q;11/28/2017&q;,&q;temperatureC&q;:28,&q;summary&q;:&q;Mild&q;,&q;temperatureF&q;:82},{&q;dateFormatted&q;:&q;11/29/2017&q;,&q;temperatureC&q;:-15,&q;summary&q;:&q;Balmy&q;,&q;temperatureF&q;:6},{&q;dateFormatted&q;:&q;11/30/2017&q;,&q;temperatureC&q;:51,&q;summary&q;:&q;Freezing&q;,&q;temperatureF&q;:123},{&q;dateFormatted&q;:&q;12/1/2017&q;,&q;temperatureC&q;:45,&q;summary&q;:&q;Mild&q;,&q;temperatureF&q;:112},{&q;dateFormatted&q;:&q;12/2/2017&q;,&q;temperatureC&q;:1,&q;summary&q;:&q;Mild&q;,&q;temperatureF&q;:33}]}}</script>
```

But the http requests are executed twice, once on server and again in browser.

## Expected behavior
The http requests shouldn't execute again, when there is already a cached response.

## Minimal reproduction of the problem with instructions
Add the above http interceptor to your app and make http call from any component.

## Environment

<pre><code>
Angular version: 5.x

Browser:
- [x ] Chrome (desktop) version XX

For Tooling issues:
- Node version: 8.5
- Platform:  Windows

**Comment by Gorniv** [comment]
try look https://github.com/Angular-RU/angular-universal-starter/blob/master/src/app/transfer-back/transfer-back.component.ts (example request)
and https://github.com/Angular-RU/angular-universal-starter/blob/master/src/modules/transfer-http/transfer-http.ts (HTTP with transfer-state)

**Comment by mhevery** [comment]
This is issue tracking for the Angular project. Please take support questions to one of our forums: 

- http://stackoverflow.com/questions/tagged/angular2
- https://gitter.im/angular/angular
- https://groups.google.com/forum/#!forum/angular

**Comment by naveedahmed1** [comment]
@Gorniv I tried that but having same issue. The http request is being sent twice once on server and then again on client.

**Comment by Gorniv** [comment]
I check http://master-ssr.gorniv.com/back in the network - no get(or post) in the browser. I had twice requested when I had different ORIGIN_URL for server and browser.

**Comment by naveedahmed1** [comment]
@Gorniv it seems to be some issue with .Net Core Angular template. https://github.com/aspnet/JavaScriptServices/issues/1288#issuecomment-347592905

**Comment by Gorniv** [comment]
I get first version TransferHttp from https://github.com/MarkPieszak/aspnetcore-angular2-universal

**Comment by naveedahmed1** [comment]
I had an idea. TransferState in that repo works till Angular 4 but have issues with Angular 5 when SSR is enabled, that primarily because of issue aspnet universal engine.
