### ISSUE TITLE
List view in Angular 4 like skype chat history list view

### ISSUE THREAD

**Issue by AlaaFK** [angular/angular#20632]
## Im working with Angular 4, I have a button, when I click it and a small list of options opens. I want to do something like in the image below which is skype feature

![image](https://user-images.githubusercontent.com/32033098/33239248-e0730686-d2ae-11e7-8770-f8f3a8352cf2.png)

What type of control should I use to achieve similar to this feature? PS: Im using some controls from this lib syncfusion.com

Thanks

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
