### ISSUE TITLE
Release Schedule needs an update

### ISSUE THREAD

**Issue by sundarchi1** [angular/angular#20649]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

[Release Schedule](https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md) documentation is old and outdated with the v5 release now done.

## Expected behavior

It should be updated with the 5.1+ release schedule.

## Minimal reproduction of the problem with instructions

[Click here](https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md)

## What is the motivation / use case for changing the behavior?

So people know when to expect 5.1+.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sundarchi1** [comment]
Uh oh, looks like this missed the deadline (`5.1.2-Sprint 1 (Dec 11 - 19, 2017)`)! Everything ok?

**Comment by IgorMinar** [comment]
All good! :-) Thanks for asking.

Some issues just didn't make it into 5.1.2. We'll move them to the next
sprint after holidays.

>

**Comment by MarcusMorba** [comment]
Can some meanwhile post the most important planned release dates here in the comments? Thanks.

**Comment by sundarchi1** [comment]
It's fallen out of sync again guys, see new issue: https://github.com/angular/angular/issues/23754
