### ISSUE TITLE
Archive sites utilize suspicious amount of download bandwidth

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#20645]
<img width="589" alt="screen shot 2017-11-27 at 12 11 29 pm" src="https://user-images.githubusercontent.com/216296/33287124-84fdfa54-d36c-11e7-9572-db7339a8a2ce.png">

I've seen the same thing for v2.angular.io and even next.angular.io. This doesn't seem right. 10GB per month is a lot of data. I'm suspecting that the service worker might be pulling in way too much stuff or something like that, but first we should find out how much traffic those subdomains get - see #20644.

**Comment by gkalpak** [comment]
Are you saying that the `archive` and `next` sites utilize more bandwidth than `stable`? Or does `stable` have too much traffic anyway, so that it doesn't make sense to compare numbers?

**Comment by IgorMinar** [comment]
According to the firebase console the stable project used 2TB of download bandwidth over the last 30 days, and 78 GB in the last 24h alone.

These numbers seem way off...

**Comment by gkalpak** [comment]
2TB per month with ~1m unique visitors would be ~2MB per visitor per month. Doesn't that sound reasonable?

**Comment by gkalpak** [comment]
@IgorMinar, is this still an issue?

**Comment by IgorMinar** [comment]
sort of. I was able to confirm that we use that much data. only recently we
started collecting analytics for archive subdomains so we'll need to wait a
bit for the data to gather. then we can investigate more.

**Comment by petebacondarwin** [comment]
@IgorMinar do we now have enough data to tell if this is still a problem?

**Comment by jessicajaniuk** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
