### ISSUE TITLE
Enable strictNullChecks mode for aio codebase

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#20646]
aio [doesn't use](https://github.com/angular/angular/blob/master/aio/tsconfig.json)  the [`strictNullChecks` tsc mode](https://basarat.gitbooks.io/typescript/docs/options/strictNullChecks.html), primarily because the mode didn't exist when we started the project.

Having this mode on would help us catch more bugs using the typechecker and would also help us better understand the TS upgrade pain for users with this mode on (currently we have this mode on in g3 and angular framework code base, but we don't have any of our non-g3 apps using that mode).

**Comment by gkalpak** [comment]
Should we enable all `--strict` checks? Please? 😛
From the [TS handbook][1]:

> **--strict**
> Enable all strict type checking options. 
Enabling `--strict` enables `--noImplicitAny`, `--noImplicitThis`, `--alwaysStrict`, `--strictNullChecks` and `--strictFunctionTypes`.

[1]: https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by trotyl** [comment]
@gkalpak the `--strict` option will break Angular in TypeScript 2.7 due to [new `--strictPropertyInitialization` option](https://github.com/Microsoft/TypeScript/pull/20075). It was mentioned in https://github.com/Microsoft/TypeScript/issues/15360 and https://github.com/Microsoft/TypeScript/issues/20117.

**Comment by gkalpak** [comment]
Thx for the heads-up 👍

We can always explcitly opt-out of specific options. That's better than opt into imo.
Also, I am not sure why this is incompatible with Angular (why can't you initialize input properties anyway)?

Also, we just landed support for TS 2.5. Let's worry about 2.7 when we get there :smiley:

**Comment by trotyl** [comment]
In Angular we always initialize input properties **AFTER** `constructor` and before `ngOnInit`, so that's an error in TypeScript (if the properties are not nullable).

**Comment by gkalpak** [comment]
I mean there is nothing stopping you from initializing input properties in the component:

```ts
@Component({
  template: 'Hello, {{ name }}!',
})
class GreetingComponent {
  @Input() name = 'world';
}
```

**Comment by trotyl** [comment]
That's true, but I guess most input properties may not have a default value? 😄

**Comment by gkalpak** [comment]
You can always explicit `| null = null` :smiley:
Just to be clear, we are talking about just the `angular.io` app. But even if we end up turning `--strictPropertyInitialization` off, it is better to be "strict by default" :smiley:

**Comment by danwulff** [comment]
I feel like enabling the `--strict` flag, would provide for the safest / best use of typescript protection going forward. This would definitely be an undertaking for all of Angular but maybe shooting for this in release 6.0 could be a possibility? I hope @IgorMinar and the Angular team would at least take this into consideration.

From the typescript 2.3 release notes: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#new---strict-master-option

> New checks added to TypeScript are often off by default to avoid breaking existing projects. While avoiding breakage is a good thing, this strategy has the drawback of making it increasingly complex to choose the highest level of type safety, and doing so requires explicit opt-in action on every TypeScript release. With the --strict option it becomes possible to choose maximum type safety with the understanding that additional errors might be reported by newer versions of the compiler as improved type checking features are added.
