### ISSUE TITLE
security vulnerability 

### ISSUE THREAD

**Issue by rhernandez-itemsoft** [angular/angular#20654]
![image](https://user-images.githubusercontent.com/4327356/33297469-c53c4578-d3a6-11e7-82fe-8b9899afd37c.png)

**Comment by gkalpak** [comment]
It is not clear how this issue is related to Angular. Angular does not have a direct dependency on `handlebars` 😕

I am going to close this, but if you still think there some action we need to take, please open a new issue providing the necessary info.

**Comment by devoto13** [comment]
This was fixed in one of the last versions of Angular CLI.
