### ISSUE TITLE
Nested animations not working as of 5.0.3

### ISSUE THREAD

**Issue by Cyral** [angular/angular#20652]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The scaleAnimation in the inner container does not have any effect.

## Expected behavior
The scaleAnimation in the inner container (cyan colored) should run, but it does not when nested under the other outer animation. The scaleAnimation will work if applied to the outer container, but will not work if applied to the inner container.

## Minimal reproduction of the problem with instructions
Works on 5.0.2: https://plnkr.co/edit/1lu4iYaZJz9SiujfgR3v?p=preview
Doesn't work on 5.0.3: https://plnkr.co/edit/s8gnN1s21HPpfu7WHu1a?p=preview
(The animation runs when the page loads)

## What is the motivation / use case for changing the behavior?
Using this nested animation to fade in the background of a dialog and "slide down" the contents of it.

## Environment

<pre><code>
Angular version: 5.0.3+ (also tested with 5.1.0-beta.2)

Browser:
- [x] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v9.0.0
- Platform: Windows

Others:

</code></pre>

**Comment by matsko** [comment]
Yes this behaves as intended. The parent/child matching code wasn't working properly and with b2a586cee175a7a0204bc99f096d4dcf2d164fc7 it was patched. Because outer is the parent of inner, and because they execute at the same time, the child animation is blocked by the parent.

There are two ways to fix this. Either have `@fadeAnimation` query into `@childAnimation` and run animateChild():

```ts
// this needs to be here for each transition()...
query('@childAnimation', animateChild())
```

Or, set a component level animation trigger that handles the changes both scale and fade that then queries both `@fadeAnimation` and `@scaleAnimation` and allows them to run:

```ts
@Component({
  //...
  animations: [
    trigger('cmpAnimations', [
      transition('* => *', [
       query('@*', animateChild(), { optional: true })
     ])
     // ... @fadeAnimation and @scaleAnimation code ...
   ])
  ]
})
export class App {
  @HostBinding('@cmpAnimations')
  public animationState = 'show';
}
```

**Comment by matsko** [comment]
Sorry that it happened that your code was working unexpectedly with this. But this has been apart of the design since 4.x.

**Comment by codeepic** [comment]
@matsko, when I followed your code example and added `query()` and `animateChild() to parent animation`, the delay on child (nested) animation now delays the parent animations. Really weird behaviour. Child animation was supposed to start independently. 
It doesn't look like this issue is resolved.

**Comment by Ross-Rawlins** [comment]
I have tried this on ym page animations and its not doing anything new. What am I missing here?

```
export const animateRoute = trigger('animRoutes', [
    transition('* <=> *', [
        group([
            query(
                ':enter',
                [
                    style({opacity: 0, transform: 'translateX(-100%)'}),
                    animate('450ms ease-in-out',
                        style({opacity: 1, transform: 'translateX(0)'})),
                    
                ],
               
                {optional: true}
            ),
            query(
                ':leave',
                [
                    style({opacity: 1, transform: 'translateX(0)'}),
                    animate('450ms ease-in-out',
                        style({opacity: 0, transform: 'translateX(-100%)'})),
                    animateChild()],
                {optional: true}
            )
        ],query('@slideCardDown', animateChild()))
    ])
])
```

```
export const slideCardDown = trigger('slideCardDown', [
    transition(':enter', [
        style({opacity: 0}),
        animate('750ms 450ms ease-in-out', keyframes([
            style({opacity: 0, transform: 'translateY(-32px)', offset: 0}),
            style({opacity: 1, transform: 'translateY(0px)', offset: 1.0}),
        ]))
    ]),
]);
```
