### ISSUE TITLE
Cannot read property 'defaultDoc' of undefined

### ISSUE THREAD

**Issue by crissdev** [angular/angular#2065]
I've been trying to use angular2 with SystemJS but without any luck. It seems that Dynamically loading angular2 breaks somehow the library initialization. I've setup a repo to reproduce this issue.

The error I receive is `Cannot read property 'defaultDoc' of undefined`

More information here >> https://github.com/crissdev/angular2-es6-dynamic/issues/1

**Comment by gdi2290** [comment]
it's a problem with the DomAdaptor. one sec

**Comment by ericmdantas** [comment]
Same here.

**Comment by robwormald** [comment]
see https://github.com/angular/angular/issues/1652

solution is to use either the pre-built System.register bundle, or the ES6 source files. Importing from commonJS seems to cause an issue - this should be the default once https://github.com/jspm/registry/pull/385 lands

**Comment by ericmdantas** [comment]
@robwormald thanks!

**Comment by crissdev** [comment]
@robwormald @gdi2290 FYI, The sample is now working with latest versions of angular2 and systemjs. I've updated the repo. :tada:

**Comment by PascalPrecht** [comment]
@crissdev can you add a link to where the fix happened?

**Comment by crissdev** [comment]
@PascalPrecht It happened with latest version of [SystemJS](https://github.com/systemjs/systemjs/commits/master) and Angular2. I can't really tell which commits.

-
[Sample repo](https://github.com/crissdev/angular2-es6-dynamic) using SystemJS and Angular2

**Comment by PascalPrecht** [comment]
@crissdev alright, thanks dude

**Comment by crissdev** [comment]
no problemo :smile:
