### ISSUE TITLE
[i18n] select and plural does not work with negative numbers

### ISSUE THREAD

**Issue by tn0** [angular/angular#20650]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Angular break the rendering of template with an error message:
<code>
Uncaught Error: Template parse errors:
Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.) ("

       <pagination-controls (pageChange)="onPageChange($event)"></pagination-controls>

[ERROR ->]"): ng:///CompanyModule/CompanyComponent.html@31:0
Invalid ICU message. Missing '}'. ("col-xs-2" >{{company.adminEmail}}</td>
      				<td class="col-xs-1" i18n>{company.status, select, [ERROR ->]-1 {deleted} 0 {active} 1 {hidden} 2 {inactive} 3 {unapproved} }</td>
</code>

## Expected behavior
it should render an value of -1 as "deleted"

## Minimal reproduction of the problem with instructions
Create an Component with an template:

<code>
<div i18n>{status, select, 1 {ok} 0 {not} -1 {deleted} }</div>
</code>
Try to compile

http://plnkr.co/edit/UOJ0rAGwzaQFPLKFBFUl?p=preview

## What is the motivation / use case for changing the behavior?

We got an status as integer from database. We want to display the meaning of that status in the user language. So we want to use the build in i18n tools to translate that. 
One of our status value is -1

## Environment

<pre><code>
Angular version: 5.0.2

Browser:
- [ x] Chrome (desktop) version 62.0.3202.94 
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x] Firefox version 52.0 
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.8.1  
- Platform:   Mac 

Others:

</code></pre>

**Comment by vicb** [comment]
It seems like only positive number are supported in the spec: http://icu-project.org/apiref/icu4j/com/ibm/icu/text/MessageFormat.html#patterns

Adding support for negative numbers would be easy but it makes no sense to add support to Angular if the translation tools do not support it.

I guess it's easy enough to update your code to avoid negative numbers.

What we should do on the Angular side is to print a meaningful error message.

Does this make sense to you ?

**Comment by tn0** [comment]
Thanks for the fast reply. 
Yes it sounds OK for me.
