### ISSUE TITLE
docs(aio) performance boost for initial cold load of angular.io

### ISSUE THREAD

**Issue by samccone** [angular/angular#20666]
#### Question
angular.io loads in 3 seconds on a fast 3g connection with no throttling, can it be faster?

Upon introspection into the trace of angular.io we are presented with a somewhat interesting timeline, at initial blush it does seem *highly* optimized, with critical resources being fetched and less important ones deferred, however what is there a > 1 second delay between when we get our critical assets to when we draw the initial page?

![image00](https://user-images.githubusercontent.com/883126/33337813-0b527d0c-d429-11e7-9fa2-83ab696ac289.png)

Zooming into the inflection point when we go from nothing painted to something painted we are presented with the answer to the 1+ second question. The page is fetching a navigation.json and then index.json, which seem to be HTML fragments that are inserted into the DOM.

![image01](https://user-images.githubusercontent.com/883126/33337817-149a57f4-d429-11e7-83ed-017a14eed069.png)

![image02](https://user-images.githubusercontent.com/883126/33337825-194603fc-d429-11e7-9b9f-b5004778d781.png)

This delay of 650ms on a 3g connection accounts for a non-trivial slow down of time to first meaningful paint. By moving up this request for index.json and navigation.json to happen right off the bat should yield a non-trivial performance boost in the initial load time of the page.

**Comment by IgorMinar** [comment]
This looks promising. Thanks Sam!

**Comment by gkalpak** [comment]
Woohoo 🎉 

To add some context:
- The angular.io app is essentially a shell (a top navbar, a sienav and a footer), with a main-content area where we show different docs (loaded s `.json` files based on the URL).
- `index.json` is the file that needs to be displayed (and that contains the "meaningful content') for `/`. On a different URL we would load a different document.
- In order to determine what file needs to be downloaded, the app needs to be bootstrapped first (i.e. the main JS files need to be loaded and parsed).

As discussed in the past, prerendering (or server-side rendering) the pages (maybe even just the most common landing pages) would save this extra request for the first meaningful paint. Maybe it is time to give this another try now that the APIs are more mature.
Other ideas that could help:
- HTTP2-pushing the corresponding `.json` file.
- Having a simple JS snippet that loads `navigation.json` and requests the proper `.json` file without having to wait for `main.bundle.js` to be loaded and parsed.

**Comment by samccone** [comment]
@gkalpak if you look at a trace of the page you will see that between the angular bootstrap completing and the fetch of the .json there is a 600+ms delay. Identifying why that is happening and fixing it should yield significant wins.

**Comment by gkalpak** [comment]
I am confused now. I thought you said the 600+ms delay was fetching waiting for `index.json` to be fetched. Are you saying that there is a 600+ms delay between bootstrap finishing and requesting `index.json`?

**Comment by samccone** [comment]
Hey @gkalpak I went ahead and reprofiled on a clean install of chrome and it looks like I was missing  the fact that the network request for index.json and nav.json indeed is kicked off right after the bootstrap happens 😨 

![image](https://user-images.githubusercontent.com/883126/33353878-dd47658a-d464-11e7-871a-8f7669bb50eb.png)

This is good for us as the path to optimizing gets a lot easier. 🎉 

For this case I am going to recommend the following pattern.

Ship a tiny inline script that looks into a dict of routes to page.json list and does the following:
```ts
const link = document.createElement('link');
link.setAttr('rel', 'preload');
link.setAttr('href', {
  '/': 'index.json'
}[window.location.pathname];
document.body.appendChild(link);
```

This will enable y'all to kick off the critical asset request upfront and not be network bound after the JS framework bootstraps.

Let me know if I can be of any more help!

**Comment by gkalpak** [comment]
Phew! Glad that my initial understanding was correct 😥 
Thx, @samccone, for helping make sense out of this (you can tell profiling is not my strong suite 😛).

##
@others:
So, https://github.com/angular/angular/issues/20666#issuecomment-347646610 is still valid then :grin:
Based on @samccone's suggestion, the less involved "fix" (for browsers that support preloading) would be dropping this snippet into `index.html`:

```html
<!-- Preload initial content -->
<script>
  var relPath = location.pathname.slice(1) || 'index';
  var fileUrl = 'generated/docs/' + relPath + '.json';
  var link = document.createElement('link');
  link.setAttr('rel', 'preload');
  link.setAttr('href', fileUrl);
  document.body.appendChild(link);
</script>
```

**Comment by gkalpak** [comment]
I gave it a shot in #20688, but for some reason, it seems that the file is requested twice 😕
I played a bit with the `as` and `crossorigin` attributes (using `as="fetch"` and `crossorigin="anonymous"`), but no joy 😒

**Comment by gkalpak** [comment]
You can see it in action here: https://pr20688-72b6088.ngbuilds.io/
The file is loaded twice and Chrome warns that the preloaded file is not used 😞

**Comment by danwulff** [comment]
(looking at https://pr20688-72b6088.ngbuilds.io/)

The specific warning from chrome I see is:
`The resource https://pr20688-72b6088.ngbuilds.io/generated/docs/index.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.`

@gkalpak In Chrome, this seems directly related to this bug ticket: https://bugs.chromium.org/p/chromium/issues/detail?id=675280. It'd be nice to get some attention on this bug.

Additionally, it might be worth noting that Firefox (beta 58) does not seem to even attempt pre-fetching the file.

(The `crossorigin` param shouldn't be necessary.)

**Comment by gkalpak** [comment]
That bug seems indeed relevant. Thx for pointing it out @danwulff.
@samccone, have you seen preload work XHR before?

**Comment by samccone** [comment]
hey @gkalpak for this specific bug I workaround it by using XHR instead of fetch, then everything is happy :)

**Comment by gkalpak** [comment]
@samccone, we are using XHR already 😕 
For example, if you go to https://pr20688-72b6088.ngbuilds.io/, disable the ServiceWorker and then:

```
xhr = new XMLHttpRequest()
xhr.open('GET', 'https://pr20688-72b6088.ngbuilds.io/generated/docs/index.json')
xhr.send()
```

...you will see file being loaded (and taking 600ms on fast 3G) 😞 

Do you have an example of a page successfully preloading a JSON file, so I can take a look and try to spot the differences? :smiley:

**Comment by gkalpak** [comment]
@petebacondarwin just pointed out to me, that we are already preloading `index.json` in [firebase config][1], so something is clearly not working correctly 😄 

[1]: https://github.com/angular/angular/blob/d34f0bf573b40cc3960b86d3f29fa892c61e95b0/aio/firebase.json#L56-L57

**Comment by petebacondarwin** [comment]
@samccone and @gkalpak browsers do some crazy and weird stuff with regards to preloading. This is compounded by us implementing a caching strategy in a service worker. But you can see via https://www.webpagetest.org/result/171203_2X_aad4014655e363299d7d4f3c76d4b108/1/details/ that `index.json` and `navigation.json` are being preloaded via server push:

![screen shot 2017-12-03 at 20 12 51](https://user-images.githubusercontent.com/15655/33529265-6c0c77ec-d866-11e7-8b5e-cdc91a95f5bd.png)

I am not sure where you were generating those screenshots but I found that there are lots of reasons why the preload can "look" like it didn't actually happen.

**Comment by petebacondarwin** [comment]
Interesting when I run it locally, I see the preload AND an additional request, like Chrome is not matching the preloaded JSON to the actual request:

![screen shot 2017-12-03 at 20 17 23](https://user-images.githubusercontent.com/15655/33529305-3407f24e-d867-11e7-8b05-3c43b5f02368.png)

I suspect that this is actually just a demonstration of the [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=675280#c11) mentioned earlier.

**Comment by petebacondarwin** [comment]
Closing this as we are definitely configured to preload the `index.json` and `navigation.json` already. Please open a new issue if you find an additional place where we can optimise this.
Thanks @samccone
