### ISSUE TITLE
Unexpected value 'MyCustomModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by Jaldeep** [angular/angular#20664]
Unable to resolve the issues. Tried all steps mentioned in https://github.com/angular/angular/issues/11438

**Comment by mhevery** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
