### ISSUE TITLE
How do I use JitCompiler / JitCompilerFactory 

### ISSUE THREAD

**Issue by claygifford** [angular/angular#20671]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

controls-module.ts -----
import { JitCompiler } from "@angular/compiler";
import { JitCompilerFactory }  from '@angular/platform-browser-dynamic';

    providers: [
        { provide: JitCompiler, useClass: JitCompilerFactory },  
    ]

then using this code ----

    public static createComponent(compiler: JitCompiler, template: string, modules?: any[]): any {
        @Component({ template })
        class TemplateComponent { }

        @NgModule({ declarations: [TemplateComponent], imports: modules ? [RouterModule, ControlsModule].concat(modules) : [RouterModule, ControlsModule] })
        class TemplateModule { }

        const mod = compiler.compileModuleAndAllComponentsSync(TemplateModule);
        const factory = mod.componentFactories.find((comp: any) =>
            comp.componentType === TemplateComponent
        );

        return factory;
    }

Error that I get...
Can't resolve all parameters for JitCompilerFactory: (?).

Also tried using this
    providers: [
        {provide: COMPILER_OPTIONS, useValue: {}, multi: true},
        {provide: CompilerFactory, useClass: JitCompilerFactory, deps: [COMPILER_OPTIONS]},
        {provide: Compiler, useFactory: createCompiler, deps: [CompilerFactory]},
    ]

Error that I get...
core.js:1427 ERROR Error: StaticInjectorError[JitCompiler]: 
  StaticInjectorError[JitCompiler]: 
    NullInjectorError: No provider for JitCompiler!

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by claygifford** [comment]
Re-open as this is a bug.
