### ISSUE TITLE
Supporting animation directives

### ISSUE THREAD

**Issue by matsko** [angular/angular#20675]
Animations up to now only work in Component code (inside of the metadata and the AnimationBuilder). Directives are supported via AnimationBuidler code, but are difficult to manage due to the state machine being only present in the @ trigger handling layer of animations.

What needs to be developed is the ability to pass in the DSL code directly as a value into a @ trigger value.

```
@Directive({
  
})
class AnimDir {
  @HostBinding('@')
  public animValue;

  @Input('fade');
  set fadeStatus(value) {
    if (value == 'in') this.fadeIn();
    else if (value == 'out') this.fadeOut();
  }

  fadeIn() {
    this.animValue = [
      style({opacity: 0 }),
      animate('1s', style({opacity: 1 }))
    ];
  }

  fadeOut() {
    this.animValue = [
      animate('1s', style({opacity: 0 }))
    ];
  }
}
```

This issue will track where this feature goes.

**Comment by alxhub** [comment]
Unfortunately we're not currently planning to add any features to animations.
