### ISSUE TITLE
feat(router): specify fallback/wildcard route for auxiliary router-outlet

### ISSUE THREAD

**Issue by pmccloghrylaing** [angular/angular#20677]
## I'm submitting a...
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report
[X] Feature request
[ ] Documentation issue or request
```

## Current behavior
If you specify a wildcard route (`path: '**'`) for an auxiliary outlet it will only be applied if there are no route matches for the primary outlet.

## Expected behavior
You should be able to specify default content for an auxiliary outlet. If there is no matching route for an outlet and a wildcard route exists, the wildcard route should be used.

## Minimal reproduction of the problem with instructions
https://run.plnkr.co/plunks/mFNaxJ5kwdyRWYDTf2dG/

Steps to reproduce:
- Run the plunk
- Clicking "Members" will load the members menu into the "menu" router-outlet correctly

Expected result:
- When first loaded the "Menu Outlet" section should include the "Public Menu" which is a component specified with a wildcard path and an outlet of "menu".

Actual result:
- No menu is displayed by default

## What is the motivation / use case for changing the behavior?
Headers and footers are often the same for large sections of a website but can then change slightly for specific sections. Fixing this would make it easy to configure default navigation for a website while also providing the flexibility to override that in particular child routes, which could be lazy loaded.

An example of this could be a website that includes a shop. The lazy-loaded `ShopModule` could specify a different component for the `navigation` router-outlet. The `ShopNavigationComponent` could include things like a shopping cart and order totals, which would only be available within the `ShopModule`.

**Comment by dgroh** [comment]
brilliant. I hope angular fixes this...there should be a way to have a fallback for outlets.

**Comment by thorn0** [comment]
Links for reference:
* the original plunk from this issue: https://plnkr.co/edit/mFNaxJ5kwdyRWYDTf2dG?p=preview
* my relevant question on SO: https://stackoverflow.com/q/48744787/76173

**Comment by atscott** [comment]
I'm not sure if something changed since this was reported, but it _does_ seem to work now

https://stackblitz.com/edit/angular-ivy-router-base-e8nmwd?file=src%2Fapp%2Fapp.component.ts
