### ISSUE TITLE
AOT Compilation: JavaScript heap out of memory

### ISSUE THREAD

**Issue by nlgi** [angular/angular#20687]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Compilation with ng serve --aot
Error: 

> 13% building modules 29/57 modules 28 active ..._client\node_modules\events\events.js
> <--- Last few GCs --->
> 
>   199983 ms: Mark-sweep 1398.4 (1403.1) -> 1398.4 (1404.1) MB, 1028.2 / 0.0 ms [allocation failure] [GC in old space requested].
>   201009 ms: Mark-sweep 1398.4 (1404.1) -> 1398.4 (1404.1) MB, 1026.5 / 0.0 ms [allocation failure] [GC in old space requested].
>   202086 ms: Mark-sweep 1398.4 (1404.1) -> 1407.9 (1403.1) MB, 1076.1 / 0.0 ms [last resort gc].
>   203144 ms: Mark-sweep 1407.9 (1403.1) -> 1417.5 (1403.1) MB, 1057.4 / 0.0 ms [last resort gc].
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> Security context: 000000C3FEDCFB49 <JS Object>
>     2: write [\node_modules\typescript\lib\typescript.js:~9597] [pc=000003E66BDFD63F] (this=000003358B74AD71 <an Object with map 000000797CCD54C1>,s=000000C3FEDEBAA1 <String[1]: {>)
>     3: write(aka write) [\node_modules\typescript\lib\typescript.js:~70607] [pc=000003E66BEEEEE1] (this=000000C3FED04381 <undefined>,s=000000C3FEDEBAA1 <...
> 
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

## Environment

<pre><code>
Angular version: 5.0.3

For Tooling issues:
- Node version: 6.10.1
- Platform: Windows

Others:
- TypeScript : 2.6.2. Do you want I try another version?
</code></pre>

I saw there's a lot of causes to this problem and this error needs investigation. How can I help you?

Many thanks,

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular-cli/issues/5618

**Comment by nlgi** [comment]
Ahhhhh yes angular-cli github, I searched on angular.

Many thanks! Working perfectly with 
node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng serve --aot
Or for build
node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build -prod

PS.: First time I run a prod build, what performance on display! Great work.

**Comment by ArunPandianB** [comment]
After running node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng serve --aot , it didn't showed any aot errors.
