### ISSUE TITLE
How to call custom method after dynamic control added to the form in Angular 4?

### ISSUE THREAD

**Issue by spvjebaraj** [angular/angular#20684]
Hi,
I am working in Angular 4 with SharePoint. I would like to call one method after creating dynamic controls to the screen. Could you please provide the solution for the same? I used the below code to generate dynamic control while pressing the "+" icon in my form.

`<div *ngFor="let item of actionPlans; let i = index">`
`<div class="row">`
`<div class="form-group">`
`<label>Action Plan</label>`
`<input type="text" class="form-control" name="actionPlan-{{i}}"                                                         [(ngModel)]="item.actionPlan">`
`</div>`
`</div>`
`</div>`

Typescript code as follows:-
`private actionPlans: any = [];`
`private addActionPlan() {
        this.actionPlans.push({});        
    }`

I want to call the below method after the dynamic item is added to the screen. In the below method I want to access the control Id and some operations. Could you please any one help me on this?
`private getActionPlan() {
        // do some actvities
    }`

Regards,
Philip

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
