### ISSUE TITLE
Proposal: Precompiled templates for faster JIT bootstrap

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#20686]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
JIT is really slow. For bigger app it takes almost 10 seconds to load page in desktop browser, and up to 30 seconds in mobile browser. While AOT loads fast, the compilation is really slow. Even with angular 5's watch mode it take over 16 seconds to recompile after one file changes - this delay is unacceptable for development.

## Expected behavior
Angular JIT compiler should allow to use precompiled templates, which should increase bootstrap speed. `template` property of `@Component` could take precompiled template object as value, for example:
```ts
@Component({
   template: require('my.component.ngtemplate.js')
})
export class MyComponent {}
```

There should also exist a tool and webpack loader which convert `.html` template to `.ngtemplate.js` file.
Optionally, the tool could weave translations into templates at compile time.

## What is the motivation / use case for changing the behavior?
Faster bootstrap for JIT.

**Comment by trotyl** [comment]
How about allowing `NgModuleFactory`s in `NgModule.imports` array? Like:

```typescript
import { PrecompiledModuleNgFactory } from './precompiled.module.ngfactory'

@NgModule({
  imports: [
    PrecompiledModuleNgFactory
  ]
})
export class AppModuleForJIT { }
```

Currently `NgModule` is the actual basic compilation unit, you cannot compile a standalone component by its own.

**Comment by dawidgarus** [comment]
@trotyl That will probably be harder to do. I know that AOT needs whole metadata about module and it's component in order to compile templates and I want to avoid. I simply want to compile html to AST (or some other intermediary step) that doesn't depend on context. Templates could be precompiled without knowing anything about component and module. It could work like this:
```ts
if (typeof component.template === 'string') {
  return parseHtml(component.template);
} else {
  return component.template;
}
```

**Comment by Toxicable** [comment]
I think the time it would take to do this would be better spent on improving the AOT experience rather than patching up JIT.

**Comment by mhevery** [comment]
What you are asking for is AoT but faster. This is in the works. This issues is not actionable, closing

**Comment by dawidgarus** [comment]
No, I'm asking for faster JIT. AOT is not suitable for everyone.

**Comment by dawidgarus** [comment]
Also, at first glance at source code, changes I'm proposing seems really simple.
All we have to do is to check here:
https://github.com/angular/angular/blob/01f711281c297a024ed02f998672e81a0854d427/packages/compiler/src/directive_normalizer.ts#L116
Whether the `template` is already `ParseTreeResult`, then skip parsing.
`HtmlParser` is exposed as public API, so the community could do the rest a write a tool and webpack plugin that parses templates.

**Comment by no-more** [comment]
Sad it's closed, I'm currently looking for something like this.

AOT is not always a solution (in my case it's not working at all)

It would be great if AOT process could be split in multiple loaders/plugins that could be plugged in a normal webpack flow.
