### ISSUE TITLE
DatePipe formats incorrect time for a value of 0

### ISSUE THREAD

**Issue by douglasg14b** [angular/angular#20680]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
With `time` = `0`
`{{time | date : 'hh:mm:ss' : 'UTC'}}` displays `12:00:00`
`{{time | date : 'hh:mm:ss' : 'UTC+12'}}` displays `12:00:00`
`{{time | date : 'hh:mm:ss' : 'UTC+11'}}` displays `11:00:00`

## Expected behavior
With `time` = `0`
`{{time | date : 'hh:mm:ss' : 'UTC'}}` displays `00:00:00`
`{{time | date : 'hh:mm:ss' : 'UTC+12'}}` displays `12:00:00`
`{{time | date : 'hh:mm:ss' : 'UTC+11'}}` displays `11:00:00`

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/wz5JhWoC7Pkmho7H4btr?p=preview

## What is the motivation / use case for changing the behavior?
Formatting a time of `0` should be `00:00:00`

## Environment

<pre><code>
Angular version: 5.0.3

Browser:
- [x] Chrome (desktop) version  62.0.3202.94
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by lazarljubenovic** [comment]
You're using `hh` which is for 12-hour format, hence `00` is displayed as `12`. If you use `HH` instead, time of `0` is properly displayed as `00`. See more at [`DatePipe` docs](https://angular.io/api/common/DatePipe).

**Comment by douglasg14b** [comment]
@lazarljubenovic 

Oh wow. I feel like a pretty big dummy now, must have completely glossed over the `HH` vs `hh` part.

Thanks.
