### ISSUE TITLE
error when write children url manually in browse angular 4

### ISSUE THREAD

**Issue by RanaFouad** [angular/angular#20689]
When I try to write children URL in browser "/en/explore" after deploying my app to the HTTP server it return these errors:

gallery.js:1 Uncaught SyntaxError: Unexpected token <
sticky.js:1 Uncaught SyntaxError: Unexpected token <
inline.bundle.js:1 Uncaught SyntaxError: Unexpected token <
polyfills.bundle.js:1 Uncaught SyntaxError: Unexpected token <
scripts.bundle.js:1 Uncaught SyntaxError: Unexpected token <
styles.bundle.js:1 Uncaught SyntaxError: Unexpected token <
vendor.bundle.js:1 Uncaught SyntaxError: Unexpected token <
main.bundle.js:1 Uncaught SyntaxError: Unexpected token <

Although when I write the same URL manually on localhost no errors found, but when write "/en" on localhost or online manually page load without any errors.

My index.html file:
`<!doctype html>
<html lang="en">

<head>
  <base href="./">
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="./assets/css/images-grid.css">
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js">
  </script>
  <script src="./assets/js/gallery.js"></script>
</head>
<app-root>
  <img class="img-responsive text-center" style="margin:0px auto;" 
       src="http://www.scissorcomb.in/wp-
         content/themes/its/img/loading_circle%20.gif" />
</app-root>
<script src="./assets/js/sticky.js"></script>

</html>`

and my app route config:
`const appRoutes: Routes = [
  { path: '', component: EnHomeComponent },
  { path: 'en', component: EnHomeComponent },
  { path: 'en/explore', component: EnExploreComponent },
  { path: 'ar', component: ArHomeComponent },
  { path: 'ar/explore', component: ArExploreComponent },
];`

I tried to use children in my routes and the same problem and I don't want to use hash in my routes.

My htaccess file in the HTTP server is:
`RewriteEngine On  
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -f [OR]  
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -d  
RewriteRule ^ - [L]
RewriteRule ^ ./index.html  `

What can I do to write children URL manually on the online server and load my page correctly?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
