### ISSUE TITLE
bug(router): router.isActive does not respect matrix parameters

### ISSUE THREAD

**Issue by ppham27** [angular/angular#20698]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When using the [routerLinkActive] directive, matrix parameters are ignored. So if I have `[routerLink]="['issues', {id: 123}]"`, it will be considered active if the current route is just `/issues`. 

## Expected behavior

When `[routerLinkActiveOptions]="{exact: true}"`, the route should only be active if the current route is `/issues;id=123`. If `exact` is false, then the route should also be active for a current route like `/issues;other=foo;id=123`.

## Minimal reproduction of the problem with instructions

The following unit test fails.

    it('should return false when the container is missing matrixParams', () => {
      const t1 = serializer.parse('/one/two');
      const t2 = serializer.parse('/one/two;id=123');
      expect(containsTree(t1, t2, true)).toBe(false);
    });

## What is the motivation / use case for changing the behavior?

I would like the active router link to be correctly highlighted.

## Environment

<pre><code>
Angular version: 5.0.3

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 6.12.0  
- Platform:  Mac, Linux, Windows 

Others:

</code></pre>

**Comment by atscott** [comment]
confirmed in v9: https://stackblitz.com/edit/angular-ivy-router-base-nnsx9n?file=src%2Fapp%2Fapp.module.ts

**Comment by atscott** [comment]
Resolved in #40303
