### ISSUE TITLE
Testing - HttpTestingController throws errors for valid JSON

### ISSUE THREAD

**Issue by klinki** [angular/angular#20690]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`HttpTestingController` throws exception for valid JSON.
`Failed: Automatic conversion to JSON is not supported for response type.` error
(see https://github.com/angular/angular/blob/master/packages/common/http/testing/src/request.ts#L159)

But according to http://www.json.org/ valid JSON is:
- array
- object
- string
- number
- null
- true/false

## Expected behavior

It should not throw exception and use value as JSON response of http call.

## Minimal reproduction of the problem with instructions
```
const req = httpMock.expectOne('some-url');
req.flush(true);
```
## Environment

<pre><code>
Angular version: 5.0.2
</code></pre>

**Comment by jabby** [comment]
I'm encounter the same issue with angular in version 4.4.6. 

Is there a workaround?

**Comment by scote** [comment]
Any update on this issue? I have the same problem.

**Comment by scote** [comment]
I found a workaround. But i'm not sure if it is the best solution.

Here what I did until they fix it.
```
testService.isEnabled().subscribe((result: boolean) => {
  expect(result).toEqual(Observable.of(true));
});

const req = httpMock.expectOne('some-url');
req.flush(Obserbvable.of(true));
```

**Comment by jdell64** [comment]
Your workaround gave me this: 
```
error TS2345: Argument of type 'Observable<boolean>' is not assignable to parameter of type 'Expected<boolean>'.
  Type 'Observable<boolean>' is not assignable to type 'ObjectContaining<boolean>'.
```

**Comment by scote** [comment]
Can you add a snippet of your code?

**Comment by jdell64** [comment]
Sure... It is like this:

```
export const FLUSH_OK = {status: 200, statusText: 'Ok'};
// ... 
it('should work', async(() => {     
        service.myFunction().subscribe((data) => {
            expect(data).toEqual(Observable.of(true));
        });
       
    
     httpMock.expectOne((req) => {
            return req.url === MY_URL
        }).flush(Observable.of(true), FLUSH_OK);

}));
```

**Comment by jdell64** [comment]
submitted a PR, but i doubt i did it right... one of the travis builds doesnt like me

**Comment by jdell64** [comment]
submitted a PR, but i doubt i did it right... one of the travis builds doesnt like me

**Comment by balane** [comment]
this is super annoying. please get fix in soon

**Comment by sloosch** [comment]
work-a-round:
````typescript
const req = httpMock.expectOne('some-url');
req.event(new HttpResponse<boolean>({body: true}));
````

**Comment by adamlarner** [comment]
The above workaround simply masks the issue, since no response is actually resolved without calling 'flush' or 'error'. The reason it will appear to succeed is simply due to the specific nature of the testing scenario, for example:
```
it ("should verify that user is authenticated", () => {
    // calls underlying http post at 'api/account/isAuth'
    service.isAuth().then(response => {
      // does not execute, and so test defaults to success
      console.log("success!");
      expect(response).toBe(true);
    });

    const req = backend.expectOne("api/account/isAuth");
    req.event(new HttpResponse<boolean>({ body: true }));
  });
```
As stated in the docs, 'event' is used for sending HttpEvent responses for things like progress updates, and as such doesn't appear to have much use unless 'flush' or 'error' is used to call 'complete' or 'error' on the underlying observable.

The solution I used was simply to use a 'truthy' value in place of the boolean. Any underlying checks against a boolean value can usually be resolved within conditional statements this way, and so any logic checks in the underlying method code should be covered in this scenario:

```
it ("should verify that user is authenticated", () => {
    service.isAuth().then(response => {
      console.log("success!"); // underlying check successfully calls
      expect(response).toBe(true); // response is 'true', since underlying check against 1 is 'true'
    });

    const req = backend.expectOne("api/account/isAuth");
    // underlying post response body should be 'true', but 1 is truthy, and so will work in most scenarios
    req.flush(1); 
  });
```
Changing the one to zero in the above test causes the test to fail, and as such achieves the exact same behaviour as I would have expected from using a boolean value in the body of the response.

**Comment by Peter554** [comment]
Any updates on if this is getting fixed?

**Comment by C0ZEN** [comment]
I did not manage to find a solution with above comments.
2 years and no solution ?!

- Angular 7.2.3

**Comment by Bloodypie** [comment]
Maybe this will help someone:
`http.get<Object>(url, { responseType: 'blob' as 'json' })`

**Comment by dwilches** [comment]
I'm still seeing this issue. Any update?

**Comment by cjessing** [comment]
Angular 8... same issue :-(

**Comment by menelikw** [comment]
Should just be able to write: `req.flush({ body: true })`

**Comment by djmarquette** [comment]
yes, this still is a problem.  I could not get @adamlarner's solution to work ([above](https://github.com/angular/angular/issues/20690#issuecomment-403485479)) but was able to tweak with flushing a 0 or 1 and then having the test verify as:
      `expect(result).toBeTruthy();`
for 0 and:
      `expect(result).toBeFalsy();`
for the 1 test.

I am not sure this will pass muster, but would like to see the httpTestingController handle this more cleanly as well.

**Comment by tylerjamesmadsen** [comment]
I also couldn't get @adamlarner's solution to work, but a simple modification of his workaround is to use double-not `!!` to convert the flushed number to a boolean:
```
service.isAuth().then(response => {
  expect(!!response).toBe(true);
});
```

**Comment by alxhub** [comment]
Confirmed as reported, and this should be an easy fix. Definitely an opportunity for a community PR (I see there is one, but it's a few years old - hopefully @jdell64 is still around!)
