### ISSUE TITLE
(ControlValueAccessor) formGroup is an empty string until type something

### ISSUE THREAD

**Issue by danielelidio** [angular/angular#20709]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have a form `CreateEditPersonComponent` in which I've implemented the `ControlValueAccessor` interface. I use this one in another component `CreateEditStudentComponent` which the form group is named as `[formGroup]="studentData"`.
So briefly, my code looks like this:

```
// create-edit-student-component.ts
export class CreateEditStudentComponent implements OnInit {
	public studentData: FormGroup;
	@Input() model: Student;
         .................
         .................
         .................
         ngOnInit() {
		this.model = this.route.snapshot.data['student'] || new Student();

		this.studentData = this._fb.group({
			id: new FormControl(this.model.id),
			person: ''
		});

		this.studentData.valueChanges.subscribe((formModel) => {
			this.model = StudentAdapter.JSON2Student(formModel);
		});
	}
        .................
        .................
        .................
}
```

```
        // create-edit-student-component.html
	<div class="container" style="margin-top: 20px" [formGroup]="studentData">
		<input type="hidden" formControlName="id" />
		<app-create-person formControlName="person" [model]="model.person"></app-create-person>
		<button class="form-control btn btn-primary" [disabled]="!isPersonalDataValid" (click)="save()">Próximo</button>
	</div>
```

```
// create-edit-person-component.ts
export class CreateEditPersonComponent implements OnInit, ControlValueAccessor {
	public form: FormGroup;
        .................
        .................
        @Input() model;
	constructor(private _fb: FormBuilder) {
	}

	ngOnInit() {
		if (!this.model) this.model = new Person();

		this.form = this._fb.group({
			id: new FormControl(this.model.id),
			firstName: new FormControl(this.model.firstName, [Validators.required]),
			lastName: new FormControl(this.model.lastName, [Validators.required]),
			dateOfBirth: new FormControl(this.model.dateOfBirth, [Validators.required, birthDateValidator]),
			addresses: this._fb.array([
				new FormControl('')
			]),
			contact: this._fb.group({
				emails: this.buildEmailArray(),
				phoneNumbers: this.buildTelefoneArray(),
			})
		});

		this.form.valueChanges.subscribe((formModel) => {
			this.model = PersonAdapter.JSON2Person(formModel);
			this._onChange(formModel);
		});
	}

	_onChange: (value: any) => void;

	writeValue(obj: any): void {
		if (obj) this.model = PersonAdapter.JSON2Person(obj);
	}
	registerOnChange(fn: any): void {
		this._onChange = fn;
	}
	registerOnTouched(fn: any): void { }
```

```
// create-edit-person-component.html
<input type="hidden" formControlName="id" />
		<div class="row">
			<div class="col">
				<div class="form-group row">
					<label for="example-text-input" class="col-4 col-form-label">Primeiro Nome:</label>
					<div class="col-8">
						<input class="form-control" type="text" formControlName="firstName" placeholder="Primeiro Nome..." />
						<div class="invalid-feedback">
							Primeiro nome inválido!
						</div>
					</div>
				</div>
			</div>
			<div class="col">
				<div class="form-group row">
					<label for="example-search-input" class="col-3 col-form-label">Sobrenome:</label>
					<div class="col-9">
						<input class="form-control" type="search" formControlName="lastName" placeholder="Sobrenome..." />
						<div class="invalid-feedback">
							Sobrenome inválido!
						</div>
					</div>
				</div>
			</div>
		</div>
        .................
        .................
        .................
```

For debugging reasons, I've put this in my html code to see how does the `studentData` model looks like: `{{ studentData.value | json }}`.
The point is that I get the `studentData` correctly but the `person` attribute inside `studentData` gets as empty as a simple empty string like this:

```
{
   "id":null <----- THIS ID COMES FROM **STUDENT FORM**, IT'S ONLY ID FOR NOW, BUT IT WILL HAVE MORE ATTRIBUTTES FURTHERLY.
   "person":"" <----- THIS IS THE PERSONAL DATA FROM STUDENT FROM WHICH COMES FROM THE **CreateEditPersonComponent** DESCRIBED ABOVE.
}
```

When I type something in the `person` form, then it correctly becomes an non-empty plain object filled in with the data I've typed in the form:
```

{
   "id":null,
   "person":{
      "id":null,
      "firstName":"Test",
      "lastName":null,
      "dateOfBirth":null,
      "addresses":[
         ""
      ],
      "contact":{
         "emails":[
            {
               "email":""
            }
         ],
         "phoneNumbers":[
            {
               "phoneNumber":""
            }
         ]
      }
   }
}
```

**P.S.**
This problem also happens if I init one of the person's form controls, like:

```
this.form = this._fb.group({
    id: new FormControl(this.model.id),
    firstName: new FormControl('Testing first name', [Validators.required]),
    ...........
    ...........
});
```

## Expected behavior
The whole form model being fulfilled as a **empty plain object** when it initializes.

## Minimal reproduction of the problem with instructions
Code described above.

## What is the motivation / use case for changing the behavior?

As described above, the `person` attribute gets as empty as a simple string, but in fact, it's a whole form group with several form controls inside. So if we could get a **non-null plain object** with **empty attributes** it could avoid extra verification to check (if an field of an nested form group is empty or so).

## Environment

<pre><code>
"dependencies": {
		"@angular/animations": "^5.0.0",
		"@angular/common": "^5.0.0",
		"@angular/compiler": "^5.0.0",
		"@angular/core": "^5.0.0",
		"@angular/forms": "^5.0.0",
		"@angular/http": "^5.0.0",
		"@angular/platform-browser": "^5.0.0",
		"@angular/platform-browser-dynamic": "^5.0.0",
		"@angular/router": "^5.0.0",
		.............
		.............
}
"devDependencies": {
		"@angular/cli": "1.5.3",
		"@angular/compiler-cli": "^5.0.0",
		"@angular/language-service": "^5.0.0",
		.............
		.............
}

</code></pre>

<pre><code>
Browser:
- [ x ] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.9.5
- Platform:  Ubuntu 17.04

Others:
Nothing else.

</code></pre>

**Comment by kara** [comment]
The value of your student form is initially set when you create your `FormGroup`. When you do this in the `ngOnInit` hook of `CreateEditStudentComponent`, `person` to `''`.  As this is a CVA, the forms API will simply set the value without complaining because it's up to your CVA to determine whether or not it's a valid value. You can fix this by setting the value to `{}` when you create your form.

**Comment by danielelidio** [comment]
Thank you @kara !
Well, the explanation was clear but I'm still thinking in the following point:

As described above, there is a kind of inheritance between student form and person form, I mean, a student contains the person form into its form. In this sense (and reminding that my persons form is a CVA), let's suppose that I implement my persons form in such way that it initialize its data with a predetermined data such like:

```
id: new FormControl(1),
firstName: new FormControl('Daniel Elidio', [Validators.required]),
lastName: new FormControl('Mendes Junior', [Validators.required]),
....
```
and I make use of this form in my student form (which is the case), so my student form would look like this:

```
this.studentData = this._fb.group({
    id: new FormControl(this.model.id),
    person: ''
});
```

In the snippet `person: ''`, if I pass either `''` or `{}` it will override the data I've initialized in my persons form. I tested and I got
Initializing with `''`: `{ "id": null, "person": "" }`
Initializing with `{}`: `{ "id": null, "person": {} }`

So, there is a way to tell my persons form to let the students form to be initialized by it's own
