### ISSUE TITLE
fixture.debugElement.query(By.css('u1')).nativeElement is not working in angular 5 as well

### ISSUE THREAD

**Issue by kkajdd** [angular/angular#20704]
fixture.debugElement.query(By.css('u1')) always throws an null. I saw that https://github.com/angular/angular/issues/6599 it will be fixed but still i face the same issue now.

**Comment by vicb** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
