### ISSUE TITLE
Android Bottom version system how compatible ANGULAR4

### ISSUE THREAD

**Issue by zhongqiang1995** [angular/angular#20703]
The error is as follows

```
Uncaught SyntaxError .Use of const in strict mode
```

**Comment by mhevery** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
