### ISSUE TITLE
Angular Compiler  and parse errors 

### ISSUE THREAD

**Issue by figuerres** [angular/angular#20717]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

i have a wiki application that inserts markup for the pages at runtime.
the markup is passed thru the compiler so that items like a router link will do correct page navigation.
when the html is clean life is good.
when the html is not 100% valid the compiler throws an error and i am having difficulty with catching the error and displaying a message to the user.
if there was an optional compiler.validate() or compiler.parse()
function then i could use that to give feedback and not crash my app.
## Expected behavior

if there was an optional compiler.validate() or compiler.parse()
function then i could use that to give feedback and not crash my app.

## Minimal reproduction of the problem with instructions

this plunker shows the code for the directive
[sample directive](https://plnkr.co/edit/mcvILwmOLvrS2PxIrXX8?p=preview)
if the html is not valid then the directive fails to render any output.
that is ok. but i need to get a message to the user ...
## What is the motivation / use case for changing the behavior?

content management / markdown editors / dynamic html output.

## Environment

<pre><code>
Angular version: 5

Browser:
- [x] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6  
- Platform:   Windows 

Others:

</code></pre>

**Comment by alxhub** [comment]
This should actually be easier with the way Ivy JIT works, but I will point out that feeding uncontrolled user input into the template compiler is 100% a major security concern - it's akin to allowing users to execute arbitrary Javascript on a page. There are very, _very_ few applications where this is an acceptable pattern.

Within Google, the JIT compiler is disabled for all applications, specifically to prevent accidental occurrences of this pattern.
