### ISSUE TITLE
ts2dart should escape dgeni comment annotations in dart output

### ISSUE THREAD

**Issue by kwalrath** [angular/angular#2072]
If you go to http://www.dartdocs.org/, you can see that the last successful build of the angular2 docs was alpha.19. http://www.dartdocs.org/failed/index.html has links to the build failure messages.

**Comment by naomiblack** [comment]
@jakemac53 @kevmoo @kegluneq -- is this something you could help with? (if so please self-assign and add to M10)

**Comment by naomiblack** [comment]
Reopened until we push an update to pub and can verify that it's actually fixed.

**Comment by kwalrath** [comment]
Thanks, @jakemac53!

**Comment by naomiblack** [comment]
We're now generating dartdocs again, but everything is included (not just the public api) and our annotations show up in the doc. Needs more work. @jakemac53 could you investigate? http://www.dartdocs.org/documentation/angular2/2.0.0-alpha.26/index.html#angular2

**Comment by jakemac53** [comment]
pushed back again as I got sidetracked by more important transformer bugs

**Comment by jakemac53** [comment]
and again for same reason...

**Comment by kevmoo** [comment]
@naomiblack I'm not sure if this a ts2dart fix or something else, but we'll need to strip/replace the dgeni annotations when we generate Dart code.

**Comment by naomiblack** [comment]
I'd like to fix this but I'm going to punt it to backlog for now, unless it's a high priority for the Dart team.

**Comment by naomiblack** [comment]
Assigning to @alexeagle to do a first order pass of trying to filter and change the link format so dartdoc understands it.

**Comment by alexeagle** [comment]
I did that - assigning back to @naomiblack to dispatch to the next contributor

**Comment by naomiblack** [comment]
sending this to backlog -- I don't think we can get to this for another few weeks until some other issues with the API doc infrastructure and language single-sourcing are resolved

**Comment by naomiblack** [comment]
also see https://github.com/angular/ts2dart/issues/276 for a list of related issues.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
