### ISSUE TITLE
"Unexpected end of JSON input"

### ISSUE THREAD

**Issue by GreatHawkeye** [angular/angular#20729]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When sending a GET request to API, I'm always getting an error back, even though the request is correct. therefor it's falling into the catch of my try/catch.

I'm getting those error (with status 200)
message: "Unexpected end of JSON input"
message:"Http failure during parsing for http://API.com"

## Expected behavior

Whenenever the request is correct, it shouldn't throw an error.

## Environment

<pre><code>
Angular version: 5.0.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [x] Opera
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

As i'm using Angular 5, I took of the .map(res) function. 
checkUserExists() is the request and verifyEmail() is where I use this request. 

checkUserExists( platformId: string, email: string) {
      return this.http.get(checkUserExistsAPI + `/${platformId}/${email}`);
 }

// Verify if emails exists
    verifyEmail(email) {
        if (email) {
            this.authenticationService.checkUserExists( this.platformId, email )
                .subscribe(
                    (data: CheckEmailResponse) => {
                        console.log(data);
                    },
                    (error: CheckEmailResponse) => {
                        const { status } = error;
                        console.log(error);

                        status === 404 ? this.error['404'] = true : this.error['404'] = false;

                    }
                );
        }
    }

</code></pre>

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
