### ISSUE TITLE
async pipe doesn't resolve when an observable is assigned and a new value is pushed before exiting the function.

### ISSUE THREAD

**Issue by Goodwine** [angular/angular#20724]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When you have a template with `{{ myValue | async }}` and your component assigns an `Observable` instance to `myValue` and immediately pushes a value before exiting the function, then the async pipe doesn't resolve. i.e. an empty string is printed while the pipe "awaits" for the next value.
However, doing the same thing with a `Promise` and having `myValue = myObservable.first().toPromise()` works under the same conditions.

## Expected behavior

The async pipe should grab the latest value from the observable rather than waiting for the next one, this may break some assumptions so perhaps this is OK only if the observable is closed?
I would like the same behavior with either Promise or Observable.

My plunker makes the promise act weird, but I understand that this is happening because the promise is already resolved by the time the next value is pushed.

## Minimal reproduction of the problem with instructions

https://embed.plnkr.co/e3AvU9RaAaEH6l7XmK0D/
Some comments are written above the buttons, clicking the buttons will show what I'm trying to say.

## What is the motivation / use case for changing the behavior?

While in my production code I don't have this problem because my observable is not resolved immediately, testing becomes cumbersome because now I have to work around this limitation.

## Environment

<pre><code>
Angular version: 5.0.3

Browser:
- [x] Chrome (desktop) version 62

**Comment by trotyl** [comment]
It's technically not possible, how could Angular get the value while it isn't stored anywhere, if you want to store the last value, please use `BehaviorSubject` or `shareReplay` operator.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
