### ISSUE TITLE
typescript-angular5 build throws error Property does not exist on type 'void'

### ISSUE THREAD

**Issue by anukonatala** [angular/angular#20737]
The below code used to work in angular2 but i tried to upgrade to angular5 and angular-cli build throws error Property 'jsonro' and 'filedata' does not exist on type 'void'.

downloadFile(sid: number,userid: string) {
  let p = new Promise((resolve, reject) => {

    let cryptoService = this.cryptoService;
    let xhr: XMLHttpRequest = new XMLHttpRequest();
    let restURL = this.appURL + "/download";
    let body = new URLSearchParams();
    let input = { "sid": sid,"userid": userid};

    body.set('input', JSON.stringify(input));

    xhr.responseType = "arraybuffer";

    // listen for responses
    xhr.onreadystatechange = function() {
      if (xhr.readyState === 4) {
        let jsonro = JSON.parse(xhr.getResponseHeader("jsonro"));
        let jsonroResponse = JSON.parse(jsonro.Response);
        let hash = jsonroResponse.hash;

        let isValidFile = cryptoService.compareFileHash("SHA-256", xhr.response, hash);

        let blob = new Blob([xhr.response]);
        let responseArray = { "xhrheader": xhr.getResponseHeader("jsonro"), "blob": blob };
        if (isValidFile) resolve(responseArray);
        else reject("The file is not valid.");

      }
    }

    // set XHR settings and execute
    xhr.open('POST', restURL, true);
    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    xhr.setRequestHeader("Cache-Control", "no-cache");
    xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
    xhr.send(body);
  });

  // return the promise
  return p.then( resp => {

    let jsonro = resp["xhrheader"];
    if (JSON.parse(jsonro).Error == "true") {
      this.sharedService.setError(JSON.parse(jsonro).Message);
    }

    return { jsonro: resp["xhrheader"], fileData: resp["blob"]} ;
  }).catch(err => this.handleError(err));
}

## I'm submitting a...

<pre><code>
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by anukonatala** [comment]
Thank you. I will close the issue.
