### ISSUE TITLE
page not save its position

### ISSUE THREAD

**Issue by praveeno** [angular/angular#20733]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I am try to understand angular architecture, so when i click on a link in website, it redirect and when i come back using back button of browser, it again show top of page, not the location where i read recently, I'm not sure whether this is a issue or not, but it still annoying.
## Expected behavior

when i navigate through any link and come back, it should save its scroll position, so i not need to again scroll to go to appropriate content

## Minimal reproduction of the problem with instructions

https://angular.io/guide/form-validation
try click on a link , and  come back, it show top of the page, not the location where you read.

## What is the motivation / use case for changing the behavior?

It helps, as no need to again search the appropriate content again and again, no need to start from top.

## Environment

<pre><code>
Angular version: latest

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by lazarljubenovic** [comment]
There's a pending PR for this: https://github.com/angular/angular/pull/20030

**Comment by IgorMinar** [comment]
#20030 is the router feature needed, but that wouldn't be applicable to angular.io because aio doesn't use @angular/router 

However we do have a duplicate issue for the same thing filed against aio already: #17308 so I'm going to close this one.
