### ISSUE TITLE
Language service doesn't recognize custom structural directive

### ISSUE THREAD

**Issue by bradringel** [angular/angular#20739]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have a structural directive defined in a separate module. When I use the directive, the element is underlined in my editor with this message:
`Angular: Property binding appSecured not used by any directive on an embeded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations"`

## Expected behavior

Directive should be recognized

## Minimal reproduction of the problem with instructions

Define a directive in a module.
Import that module into a different module, and use the structural directive in a template

Currently this directive is defined in a module, which is listed in the `imports` and `exports` array of a shared module, which is then imported into the module I'm attempting to use the directive in

## Environment

<pre><code>
Angular version: 4.4.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.0.0  
- Platform: Windows   

Others:
WebStorm 2017.2.5
Build #WS-172.4343.25, built on October 20, 2017
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
</code></pre>

**Comment by chuckjaz** [comment]
@bradringel Can you create repository I can clone that will reproduce this?

**Comment by bradringel** [comment]
We've upgraded to angular 5.0 and Webstorm 2017.3 and this seems to be working now.
