### ISSUE TITLE
bug - move mouse roulette while loading

### ISSUE THREAD

**Issue by miguelmoya1** [angular/angular#20748]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior

If I move the mouse roulette while loading the page, it doesn't load
## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [X] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.2.0  
- Platform: Windows  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

??

**Comment by miguelmoya1** [comment]
I do not know how to explain myself well, but if the page is loading and you move the mouse roulette, it stays loaded while you are moving the roulette wheel.

**Comment by ericmartinezr** [comment]
Please the read links suggested above.
