### ISSUE TITLE
is not part of the compilation output, angular 5

### ISSUE THREAD

**Issue by vasuneet** [angular/angular#20741]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have included ng2-cache in package.json
 "ng2-cache": "^0.1.11",
using npm i installed this package.
imported cacheservice from this package using the following command
      import { CacheService } from 'ng2-cache/ng2-cache';
Giving the following issue

ERROR in ./node_modules/ng2-cache/ng2-cache.ts
Module build failed: Error: D:\va00120386\ATT\Projects\ms-angular\node_modules\ng2-cache\ng2-cache.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (D:\va00120386\ATT\Projects\ms-angular\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23)
    at plugin.done.then (D:\va00120386\ATT\Projects\ms-angular\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/app/cms-integration-module/cms.module.ts 12:18-48
 @ ./src/app/cms-integration-module/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

## Expected behavior

It should run fine.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/20091, also check on the lib's repo.

**Comment by IgorMinar** [comment]
I reopened #20091, so I'm going to close this one.
