### ISSUE TITLE
Bug with update controls in ngModelGroup or ngForm

### ISSUE THREAD

**Issue by Pontiley** [angular/angular#20742]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I use **Template Driven Forms** with ngModel, and I want to add new controls or delete old one from ngModelGroup within ngFor, where control names builds use index for making different names, for example, I add new conrols in ngModelGroup with names: **item_0, item_1, item_2**, after that I delete control with name **item_1** from ngModelGroup, it will contains controls: **item_0, item_2** and when I add new control with the same name which I deleted before, in my case it is **item_1** than it will not include to ngModelGroup, instead of this new control will be tied to control with name **item_2** and I will have two controls on the view but one FormControl in model form for both.

## Expected behavior
When I delete controls from ngModelGroup and after adding new controls with same names (the same names had controls which I deleted before) my new controls will include in the model form.

## Minimal reproduction of the problem with instructions
For reproducing bug you can go to my plunker with example https://plnkr.co/edit/dVChzfED2ba7aHJCrBZr?p=preview you need to add three input controls and to fill each with some information and after you will see value of the controls form ngModelGroup below "add" button.
After that delete the second control and look at changes in values from ngModelGroup (you will see two controls in ngModelGroup), then click by the "add" button and new control will add to the view, but values from ngModelGroup  will not update, and two last input controls will have the same value from ngModelGroup, it will **item_2** and change value in both last inputs will update value with name **item_2** from ngModelGroup.

## What is the motivation/use case for changing the behavior?
I want to use the list of controls with an opportunity add new controls or delete old and do validation for these controls (for that I need all controls in the form model)

## Environment
<pre><code>
Angular version: (5.0.2)

Browser:
- [x] Chrome (desktop) version latest
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version latest
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by Pontiley** [comment]
I found the solution for this problem, with use trackBy in ngFor https://angular.io/guide/template-syntax#template-input-variables

It's my example https://plnkr.co/edit/JKBkcXFtavGV4IYBAily?p=preview

**Comment by Fanchao92** [comment]
Had a similar issue when I tried to add and delete ngModelGroup within an ngForm. Trackby index works for me as well!
