### ISSUE TITLE
scss compiling bug for generated components

### ISSUE THREAD

**Issue by lumenier1** [angular/angular#20759]
Sass doesn't work correctly for generated components.
For e.g. this code is fine for `app.component.scss` if I have some repetitive selectors for some reason:
`.container {
   .header {
      margin-top: 20px;
   }
}
.container {
   .header {
      background-color: black;
   }
}`

But angular doesn't compile scss for imported components with the same style!
For e.g. this code will not work for `header.component.scss` if I have some repetitive selectors:
`.container {
   .header {
      margin-bottom: 20px;
   }
}`

Just don't tell me that I shouldn't write such scss code untill it would be recognized by Angular framework correclty. Or explain if I'am doing something wrong :)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
