### ISSUE TITLE
[ngc] Error compiling code with 5.0.5 - Static utility method with closure

### ISSUE THREAD

**Issue by jgodi** [angular/angular#20753]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Running `ngc -p tsconfig-aot.json` fails with:

```
Metadata collected contains an error that will be reported at runtime: Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function.
```

## Expected behavior

Compilation is successful

Here is the function in question that it fails

```
export class Helpers {
    static filterByField(field:string, reverse: boolean): Function {
        return (prev:any, curr:any) {
            // do filter code
        }
    }
}
```

Link to `tsconfig` that I am using: https://gist.github.com/jgodi/9a77c1329e38311d32e901272790d66f

This worked before, trying to upgrade my library now to 5.0+ (from 4.3) and getting these errors.

I also get 

```
Metadata collected contains an error that will be reported at runtime: Expression form not supported.
```

with this function

```
export class Helpers {
    static interpolate(str, props) {
        return str.replace(/\$([\w\.]+)/g, (original, key) => {
            let keys = key.split('.');
            let value = props[keys.shift()];
            while (keys.length && value !== undefined) {
                let k = keys.shift();
                value = k ? value[k] : `${value}.`;
            }
            return value !== undefined ? value : original;
        });
    }
}
```

Any ideas?

## Environment

<pre><code>
Angular version: 5.0.5

For Tooling issues:
- Node version: 6.12.0  
- Platform:  Mac

**Comment by jgodi** [comment]
I switched to use https://github.com/dherges/ng-packagr which is awesome and it all works now.

**Comment by manjot-cams** [comment]
@jgodi Hey, I'm getting a similar error to this using ng-packagr any help would be lovely.
