### ISSUE TITLE
Template driven forms have a pending but no status property

### ISSUE THREAD

**Issue by BioPhoton** [angular/angular#20762]
## I'm submitting a...
<pre><code>
[x] Bug report 
</code></pre>

## Current behaviour
Form controls have the pending and status property. The form it self don't.

## Expected behavior
I would expect the form to have the status property.

## Minimal reproduction of the problem with instructions
no

## What is the motivation / use case for changing the behaviour?
Consistency.

**Comment by kara** [comment]
@BioPhoton Forms should already have both the `pending` and `status` properties, in both TD and reactive forms. Without any code or a repro case, it's difficult to know why you're not seeing these. If you're still having trouble finding these values, please open a new issue with more information.
