### ISSUE TITLE
Property setter should not be called on a directive that does not use [] notation

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2076]
```js
@Component({
  selector: '[awesome]',
  properties: {
    'name': 'awesome'
  }
})
class AwesomeDirective {
  constructor(@Static('name') name:String) {
    console.log('attribute');
    console.log(name);
  }

  set name(name:String) {
    console.log('property')
    console.log(name);
  }
}
```

Expected:

```html
<div awesome="hello"></div>
```

Console output:
> attribute
> hello

Actual output:
> attribute
> hello
> property
> hello

```js
class ParentComponent {
  constructor() {
    this.name = 'world';
  }
}
```

Expected:

```html
<div [awesome]="name"></div>
```

Console output:
> attribute
> null
> property
> world

Actual output:
> attribute
> null
> property
> world

**Comment by matanlurey** [comment]
@yjbanov, @vsavkin from today.

**Comment by vicb** [comment]
Hum... isn't this actually a feature ? 
My understanding was that with `[]` the value is an expression vs a litteral without `[]`. But as you explicitly have a `properties` config, ng will honor this. 

Why would you need a `properties` config a all in your code snippet ?

**Comment by matanlurey** [comment]
Ideally I want to be able to set "name" in the awesome directive by using a statically defined value (attribute), or data-binding it (property).

**Comment by mhevery** [comment]
This works as intended. Let's chat in person about your use case.

**Comment by matanlurey** [comment]
This is working as intended. I'm OK with the resolution :)
