### ISSUE TITLE
aio home page banner logo should always be precached by service-worker

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#20763]
today we don't cache the banner logo and because of that we can get into a situation where the image is broken:

<img width="1066" alt="screen shot 2017-12-03 at 7 23 14 am" src="https://user-images.githubusercontent.com/216296/33526810-449683ee-d7fb-11e7-9049-f6e249645426.png">

This can happen in two ways:

1. index.json is fetched in the background but by the time when it's used the device is already offline, so the content displays with the exception of the logo

2. version skew and race condition cased by infrequent visits to angular.io (this one is harder to reproduce, but I'll try to describe the steps)
  
    - user navigates to angular.io and sw caches the current version (ver A)
    - a new version of angular.io is deployed (ver B), introducing a new logo for the frontpage
    - later the user navigates to angular.io but doesn't make any further navigation, the service worker downloads ver B but it doesn't get activated for the current user session because there was no navigation, this means that any lazily cached resources (like the frontpage logo) are not downloaded and cached
    - a new version of angular.io is deployed (ver C) which changes the frontpage logo again. This version no longer contains the logo for ver B because it was unnecessary and got removed
    - the user opens a new window, navigates to angular.io. This pulls ver B from the cache and displays it, but because the logo hasn't been precached, it tries to downloaded from the server. At this point however the server only has ver C available, which no longer contains the logo, so the server returns HTTP 404
        - while this is happening, the service worker finds ver C available on the server and downloads it, but doesn't activate it until the next navigation within the app or user doing full page refresh
    - if the user refreshes the page, ver C is now displayed and the site is unbroken again.

I'm thinking that the best solution would be to ensure (somehow) that all of the assets needed for rendering the shell and all the precached json files are also precached.

**Comment by gkalpak** [comment]
> I'm thinking that the best solution would be to ensure (somehow) that all of the assets needed for rendering the shell and all the precached json files are also precached.

Based on [our config][1], images for `index.json` (and most precached json files) should already be cached by the SW. Are you seeing something different?

[1]: https://github.com/angular/angular/blob/d34f0bf573b40cc3960b86d3f29fa892c61e95b0/aio/ngsw-manifest.json#L14

**Comment by gkalpak** [comment]
Closing since I believe we are pre-caching the image. Re-open if you are still seeing something different.
