### ISSUE TITLE
Observable.of does not work as expected in  HttpClient Interceptor 

### ISSUE THREAD

**Issue by m98** [angular/angular#20772]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior:
The `Observable.of` convert arguments to an observable sequence means it can be used as a mock response to another Observable which is subscribe.
But now, It seems `Observable.of` does not work when its called from an interceptor because methods which are subscribing to it does not execute

## Expected behavior:
When Observable.of is called with the given data, the `HttpClient` should return the data to the method which is already subscribing to it

## Minimal reproduction of the problem with instructions
**[Live Demo](https://stackblitz.com/edit/angular-8j63yr)**  (open DevTools console to read logs)

There is a service (`mock.service.ts`) which makes a mock HTTP get request using `HttpClient`, the request arrives at `mock.interceptor.ts` and it want's to answer with the mock data using `Observable.of` (means wants to not let the request to goes over the network), the `mock.service` has a subscriber in `app.component` which is waiting for the response of the `HttpClient`. No data arrives in subscriber, nor error.

**Comment by wKoza** [comment]
An interceptor should return a `Observable<HttpEvent<any>>` but, in your case, you return a `Observable<any>`.  See https://angular.io/guide/http#logging

**Comment by alxhub** [comment]
Hi @m98,

Interceptors are expected to return a stream of `HttpEvent`s, not an observable of the data directly. Look at the `HttpResponse` class, which is probably the one you want to use for your `Observable.of()` value.
