### ISSUE TITLE
test helper function whenStable didn't wait for Promise resolves

### ISSUE THREAD

**Issue by elliot-xu** [angular/angular#20774]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I'm using `SystemJsModuleLoader` to load modules, it works just fine.
But when I test my app, `whenStable` didn't works as it describes. 
It resolves so fast that `systemLoader.load()` hasn't resolved yet.
So I can't do test in `whenStable().then(my test here...)`.

## Expected behavior

`whenStable` should wait for Promise resolves.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/td8zKmBBqtAEL768kx4v?p=preview
## Environment

<pre><code>
Angular version: 5.0.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mhevery** [comment]
Your system JS must be loaded before Zone.js, which means it is running outside of the zone hence whenStable will not get triggered. This is intended behavior.

**Comment by elliot-xu** [comment]
Thank for your reply. As you said, Promise should registered as a microtask in the ngzone, so `whenStable` would know when the microtask is finished.
So if it is the ordering problem:

I create a new plunker with the example in https://angular.io/guide/testing#live-examples that put system.src.js before Zone.js although I did in my first example. But it is still failed.
https://plnkr.co/edit/E438ngPcFYkwh48CTUoe?p=preview

In the contrast, if system.src.js should loaded after Zone.js, so why the test `app/shared/twain.component.spec` in `All specs that test the sample application ` in https://angular.io/guide/testing#live-examples  works as expected? Since the system.src.js loaded before Zone.js.
