### ISSUE TITLE
2 router-outlet with *ngIf causes problems

### ISSUE THREAD

**Issue by borriej** [angular/angular#20778]
In my app.component i need two different mark-ups. One for logged in... Second for not-logged-in.

Once logged in, the new template is first loaded into the  router-outlet. But after routing to another state, you see the previous' state template displayed in the new state. This is due to two router-outlet's..

Which I was forces to use, because i really needed 'abstract states' on Angular Router, which do not exists yet :( ... because I need urls '/login', '/register', '/forgot' to load a parent component first (to share my 'auth layout'.. but I cant use router children: [] with path '', because this causes troubles when using router.navigate('')  in my app (it redirects back to the login, instead of a capture '' with a redirectTo from another state).

```
<div *ngIf="authService.isLoggedIn">
    ...
    <router-outlet></router-outlet>
    ...
</div>

<div *ngIf="!authService.isLoggedIn">
    ...
    <router-outlet></router-outlet>
    ...
</div>

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
