### ISSUE TITLE
Angular not binding a (click) into an element when two libraries are present

### ISSUE THREAD

**Issue by Zerokk** [angular/angular#20776]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I'm making a complex form in which I load some checkboxes dynamically. They have some complex behavior in which they can disable between themselves depending on certain conditions and so. 

This was working pretty well: I load all these inputs into a modal [(this one)](https://ng-bootstrap.github.io/#/components/modal/examples) and I could perfectly click them so this logic triggers and sets their status to selected. No problems so far; everything worked perfectly.

The problem came when I installed [this datepicker library](https://github.com/evansmwendwa/ng2-daterangepicker). It works well, for sure, but it makes my checkboxes suddenly stop to work. I click on them, and nothing happens. If I put a console.log() in the function my (event) click triggers, it just _won't trigger_. The message never appears in the console. **Somehow, Angular stops binding these (click) events into these dynamically loaded checkboxes.** Weeeeeird.

## Expected behavior
I should be able to use the datepicker and the modal's checkboxes at the same time. But either I disable the datepicker, commenting its whole template implementation, or these checkboxes just won't trigger the function they should.

## Minimal reproduction of the problem with instructions

You can see the template code in this other issue I opened in the datepicker library:
https://github.com/evansmwendwa/ng2-daterangepicker/issues/73

Too much code is required to do some reproduction of the problem...

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.1  
- Platform: Windows 10, 64 bits

</code></pre>

I know this is usually said, but I can't stress this enough: this is happening in a real app, with a deadline that is not that far. Both modal and datepicker are needed... so I'm quite anxious about fixing this problem, which root isn't very clear to be the datepicker, but maybe, Angular itself. I hope we can find what's going on, I would appreciate it a lot...

Thank you!

**Comment by Zerokk** [comment]
Ok, this definitely is an Angular problem and I will explain why. I hope the devs take this into account and fix it, because just for this problem, my whole company is doubting very seriously if upgrading to Angular. Probably we'll just forget about it. This framework **is not stable** and seems to have **some weird binding problem when working with big status objects**.

Ok, let's explain what's going on:
 
- This is a hard form. It has a lot of logic and one click triggers many functions:
```
openModal() {
    this.config.attributes.selected = this.clone(this.config.attributes.saved);
		var dimensions = this.ca_operations.exclude_dimensions(this.conversion_dimension_constants.dimensions, this.config.attributes.exclude);
		this.config.attributes.available = this.ca_operations.available_attributes(dimensions, this.config.attributes.selected, this.config.attributes.excluded);
    this.show();
}
```
So as you see, even when this modal is opened, some logic is triggered before showing it. 

- Afterwards, the modal loads the following information:

```
<!-- Modal -->
  <div #modal  class="modal fade" tabindex="-1" [ngClass]="{'show': visibleAnimate}"
  [ngStyle]="{'display': visible ? 'block' : 'none', 'opacity': visibleAnimate ? 1 : 0}">
  <div class="modal-dialog">
  <div class="modal-content">
   <div class="modal-header">
      <h4 class="modal-title">Dimensions</h4>
      <button type="button" class="close" aria-label="Close" (click)="hide()">
        <span aria-hidden="true">&times;</span>
      </button>
   </div>
   <div class="modal-body">
      <fieldset *ngFor="let attribute of listAttributes(config.attributes.available)" >
          <div *ngIf="!config.attributes.fixed[attribute.label]">
          <div class="form-group">
            <label class="control-label col-lg-4">
              {{attribute.label}}
            </label>
            <div class="col-lg-8 inputs">
              <label *ngFor="let value of attribute.values; let i = index" class="{{config.attributes.type[attribute.key]}}">
                <input
                  [type]="config.attributes.type[attribute.key]"
                  (click)="toggle_selected(attribute.key, attribute.values[i])"
                  [checked]="is_selected(attribute.key, attribute.values[i])"
                  *ngIf="is_defined(attribute.values[i])"
                >
                {{ value }}
              </label>
            </div>
          </div>
         </div>
      </fieldset>
    
        <div class="row-fluid clearfix col-md-12">
            Selected dimension filter(s):
        </div>
        <div id="selectedDimensions" class="row-fluid clearfix col-md-12">
         <span *ngFor="let attribute of listAttributes(config.attributes.selected)">
            <span *ngIf="attribute.values.length>0 && !config.attributes.hidden[attribute.key]">
             <span class="tag label label-info">
               {{attribute.label}}:
               {{attribute.values}}
             </span>
            </span>
         </span>
       </div>
   </div>
   <div class="modal-footer">  
        <button type="button" class="btn btn-default" (click)="hide()">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
   </div>
  </div>
  </div>
  </div>
```
- In the end, I can see the list of attributes, but **I can't click on them**. The thing is that **no function is triggered*; it's like if the framework just forgot about that complex input tag:

```
                <input
                  [type]="config.attributes.type[attribute.key]"
                  (click)="toggle_selected(attribute.key, attribute.values[i])"
                  [checked]="is_selected(attribute.key, attribute.values[i])"
                  *ngIf="is_defined(attribute.values[i])"
                >
```

- The only possible fix this far is to remove JQuery from the external components I use. I'm using the datepicker component I showed you before, and it imports JQuery like:

`var $ = require('jquery')`

If I comment this line... **suddenly the modal starts working and I can check the checkboxes!** But of course, the datepicker component stops working, since it relies on JQuery. 

**Conclussion: **
Something very weird happens to the binding capabilities of Angular when JQuery is present. Some things work, some things just don't. And this is a problem, because nowadays, so many dependencies rely on JQuery to work. 

Either this gets fixed, or we're done with this framework. I've already spent several hours split in two days of work for just realizing that Angular is not capable of making work one page that was working perfectly with AngularJS + JQuery. 

I hope some solution is quick delivered, or somebody has some clue on how to fix this, because this is a serious problem that costed already too much money.

**Comment by mhevery** [comment]
It seems like the datepicker library is registering the click handler and than canceling it, which means that Angular never gets it. So this is not an issue with angular, this is just how DOM works.

**Comment by Zerokk** [comment]
The thing is, why is JQuery behaving like this? Shouldn't Angular be prepared against this kind of stupid un-bindability thing?
