### ISSUE TITLE
Type narrowing for `NgSwitch` and `NgSwitchCase`

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#20780]
## Current behavior

No type narrowing is performed when using `NgSwitch` and `NgSwitchCase`.

## Expected behavior

Narrow the types used in the `NgSwitchCase` based on the selection criteria.

See https://github.com/angular/angular/issues/17953#issuecomment-348993040 and following for more details.

**Comment by dirkluijk** [comment]
Looking forward to see type guard support in language-service as well!

My simple use case:
```typescript
interface Animal {
  type: 'fish' | 'bird';
}

interface Fish extends Animal {
  type: 'fish';
  foo: string;
}

interface Bird extends Animal {
  type: 'fish';
  bar: string;
}

@Component({})
class MyComponent {
  animal: Animal;

  isFish(animal: Animal): animal is Fish {
    return animal.type === 'fish';
  }

  isBird(animal: Animal): animal is Bird {
    return animal.type === 'bird';
  }
}
```

Use case 1
```html
<app-fish *ngIf="isFish(animal)" [foo]="animal.foo"></app-fish>
<app-bird *ngIf="isBird(animal)" [bar]="animal.bar"></app-bird>
```

Use case 2
```html
<ng-container [ngSwitch]="true">
  <app-fish *ngSwitchCase="isFish(animal)"></app-fish>
  <app-bird *ngSwitchCase="isBird(animal)"></app-bird>
</ng-container>
```

Are both use cases covered?

**Comment by waterplea** [comment]
This would be a great addition, having an issue similar to case 2 that @dirkluijk posted.

**Comment by amitport** [comment]
@chuckjaz any updates? Anyone working on this? Thanks

**Comment by dirkluijk** [comment]
Will this be solved in Ivy?

**Comment by SchnWalter** [comment]
No, this isn't solved by Ivy, if anything, Ivy will cause more people to realize how badly they need `ngSwitch` to support type narrowing.

**Comment by klemenoslaj** [comment]
This would really clean up a lot of template code. How come this is such a low priority?

**Comment by Lonli-Lokli** [comment]
It has 63 upvotes so seems like pretty needed feature.

**Comment by ColinLaws** [comment]
I just enabled strict type checking on templates, and I find it to be highly beneficial feature; however, without type narrowing, you're really limited on the approach you can take when creating a component that accepts polymorphic data as an input, and conditionally render based on the type of data.

**Comment by amakhrov** [comment]
I ended up updating our existing templates that used `ngSwitch` to using `ngIf` - the latter properly supports type narrowing.

**Comment by simeyla** [comment]
It may never be possible for `ngSwitch` to have this kind of behavior.

The good news is you do not need to use a type guard function (`isFish()`, `isBird()`) to get type narrowing for *ngIf when using a [discriminated union](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes-func.html#discriminated-unions).

I've found this the most convenient way for displaying 'polymorphic' templates. No you won't get the nice 'switch' syntax or a `default` clause, but it sure is nice to finally see the correct type inferred inside a template.

```
  // Note: Animal is a type here not an interface
  type Animal = Fish | Bird;
  
  // Fish and Bird can be either interface or type
  // Note : Only Fish has 'fishThing' string
  interface Fish  {
    type: 'fish';
    fishThing: string;
  }
  
  interface Bird  {
    type: 'bird';
    birdThing: string;
  }
```

In the component:

    animal: Animal = { type: 'fish', fishThing: 'fish thing '};

Then in the template if I put `animal.type == 'fish'` it will automatically assert the type.

                         <div *ngIf="animal.type == 'fish'">{{ animal.fishThing }}</div>
                         <div *ngIf="animal.type == 'fish'">{{ animal.birdThing }}</div>    

This will result in an error for `animal.birdThing`:

![image](https://user-images.githubusercontent.com/3656278/122652885-1ce16d80-d0f6-11eb-911b-a02e93b95eed.png)

This won't work if `Animal` is an interface because it can't do the type narrowing without a [type guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html).

**Comment by maxime1992** [comment]
@alxhub closed the issue above :point_up: saying it was a duplicate but I'm not sure it is so I'll jsut reiterate quickly here:

I often end up using in a switch case the default to call a function which expects a parameter of type `never` and pass the argument of the switch to it. This way, if there's any case missing in the switch, typescript will throw an error as the remaining type is not of type never.

I think that if we could somehow replicate this behavior within the ngSwitch, that'd be a nice addition

**Comment by Kamshak** [comment]
The above would be fantastic, I also do this a lot to check for exhaustiveness. In a larger codebase it can be tricky to consider all places that e.g. an enum is used so when you extend logic it is super helpful to have the compiler tell you where you missed something (error at compile time). E.g.

```ts
class UnreachableCaseError extends Error {
	constructor(val: never) {
		super(`Unreachable case: ${val}`);
	}
}

function getColorName(c: Color): string {
    switch(c) {
        case Color.Red:
            return 'red';
        case Color.Green:
            return 'green';
        default:
            throw new UnreachableCaseError(c);
    }
}
```

It would be fantastic to have this in templates, too, so that we never end up with a piece of data that cannot be rendered

**Comment by Harpush** [comment]
Any news concerning this issue? Currently support for ngSwitch and else type narrow is the only thing that hold us back from enabling strict templates :(

**Comment by Lonli-Lokli** [comment]
Is there possibility with new typescript satisfied operator?
https://devblogs.microsoft.com/typescript/announcing-typescript-4-9-beta/#the-satisfies-operator

**Comment by scr2em** [comment]
Come on it's 2023

**Comment by MickL** [comment]
5 years later, still not implemented :(

**Comment by Lonli-Lokli** [comment]
I think this issue is not closed based on the ngswitch implementation, it just requires rewriting

**Comment by flevi29** [comment]
> 5 years later, still not implemented :(
> 
> Using functions as @dirkluijk commented is not an option for me as this functions will run each time the change detection runs and their pure purpose is to prevent type checking errors on build.

I've been wondering if this is true, `switch` would have to re-run each time too, it needs to check which template to render. So a nested ["if-else-if"](https://stackoverflow.com/questions/43812770/ngif-else-if-in-template) ugly depressing monstrosity should be just as good. Of course there's some added overhead but it should be absolutely minimal. The biggest headache is the resulting monster lasagna code. It's so much more verbose and hard to read than it has to be.

**Comment by Jrubzjeknf** [comment]
Check discussion https://github.com/angular/angular/discussions/50719, header `switch block `.

> #switch has several major benefits over NgSwitch:
>
>    It does not require a container element to hold the condition expression or each conditional template.
>    It can support template type-checking, including type narrowing within each branch.

**Comment by stealthAngel** [comment]
Although I like the answer of @dirkluijk There is a much simpler solution:

``` typescript
export type ShapeType = 'circle' | 'square' | 'rectangle';

export interface Shape {
  type: ShapeType;
}

export interface Circle extends Shape {
  radius: number;
}

export interface Square extends Shape {
  sideLength: number;
}

export interface Rectangle extends Shape {
  width: number;
  height: number;
}
```

```
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  json: string = `[{
    "type": "circle",
    "radius": 11
  },
  {
    "type": "square",
    "sideLength": 15
  },
  {
    "type": "rectangle",
    "height": 10,
    "width": 20
  }
  ]`;

  shapes: Shape[] = JSON.parse(json);
}
```

```
<ng-container *ngFor="let shape of shapes" [ngSwitch]="shape.type">
  <app-circle *ngSwitchCase="'circle'" [shape]="shape"></app-circle>
  <app-rectangle *ngSwitchCase="'rectangle'" [shape]="shape"></app-rectangle>
  <app-square *ngSwitchCase="'square'" [shape]="shape"></app-square>
  <div *ngSwitchDefault>Onbekend</div>
</ng-container>
```

```
@Component({
  selector: 'app-square',
  templateUrl: './square.component.html',
  styleUrls: ['./square.component.css']
})
export class SquareComponent {
  @Input()
  public shape: Shape | undefined;

  protected get square(): Square {
    return this.shape as Square;
  }

  constructor() { }
}
```

see my [git repository for an example](https://github.com/stealthAngel/easy-angular-polymorphism/tree/main):

**Comment by baratgabor** [comment]
One technique that can help:

```typescript
  // In component.ts
  // This type forces to create an object that always has exactly the same members & values as the original string union.
  animalType: { [K in Animal['type']]: K } = {
    bird: 'bird',
    fish: 'fish'
  }
```

```html
<ng-container [ngSwitch]="animal.type">
  <app-fish *ngSwitchCase="animalType.bird"></app-fish>
  <app-bird *ngSwitchCase="animalType.fish"></app-bird>
</ng-container>
```

**Comment by maxime1992** [comment]
@baratgabor this is about `NgSwitch` and `NgSwitchCase`. Nothing will be enforced on the template side as far as I know with your code above

**Comment by jpike88** [comment]
I've banned use of ngSwitch in our projects because not only does it not have type narrowing, there is zero type awareness in the case settings meaning any old thing can be used in the cases and we don't know about the problem until a bug happens.

**Comment by juane1000** [comment]
I think this may be locked going forward because the new template flow control syntax will enable type narrowing. NgSwitch and NgIf will be sunset according to previous angular team comments on their stream. Existing codebases will have to migrate if they want the type safety in the templates.

**Comment by jpike88** [comment]
Does anyone know how long roughly that RFC is going to take to be implemented? It still seems to be in early stages...

**Comment by JeanMeche** [comment]
The new control flow is pretty much implemented an available in the current RC. 
It will be available as a developer preview in v17 (release in early november).

**Comment by jpike88** [comment]
Thanks. I'll note that I'm just trying it out now on the current RC (I added the appropriate stuff to `angularCompilerOptions`), and neither vscode (typescript and angular extension on latest) or `ng build` is flagging any type related issues. In that screenshot, `isDebug` variable is a boolean... just an FYI

<img width="712" alt="Screenshot 2023-10-20 at 17 02 03" src="https://github.com/angular/angular/assets/9585787/ef300adc-74e4-49ef-8297-4058433b8da8">

**Comment by jpike88** [comment]
Sorry that wasn't very clear. What I meant is that I expected there to be some sort or type narrowing to be happening in those case statements as they don't match the type of the `isDebug` variable

**Comment by alxhub** [comment]
Closing as we have no plans to support coordinated type-checking of multiple structural directives, but `@switch` does support type-checking (it's about time!)
