### ISSUE TITLE
The meny Forms > W Wizard doesnt work

### ISSUE THREAD

**Issue by renatojava** [angular/angular#20789]
I am trying to select the menu tabs "Forms >  W Wizard" the error below is shown:
ERROR TypeError: $(...).validate is not a function

------
The CSS doesn't show.
I think this template need of revision, so many bugs.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by renatojava** [comment]
Hello,

But and about the layout ? the layouts breaks?
if I download the source and do not change anything the correct would work as the sold and presented on the site would not it? because I did not change anything
