### ISSUE TITLE
Change detector should be able to reference functions idempotentently

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2078]
I don't know if this happens in JS, but:

```dart
@Component(
  selector: 'x'
)
@View(
  directives: const [YComponent],
  template: r'''
    <y [callback]="onFoo"></y>
  '''
)
class XComponent {
  void onFoo() {
    print('foo!');
  }
}

@Component(
  selector: 'y',
  properties: const {
    'callback': 'callback'
  }
)
class YComponent {
  void set callback(Function callback) {
    callback();
  }
}
```

```html
<x></x>
```

Expected output: 

> foo!

Actual output:

Giant scary message.

Workaround:

```dart
class XComponent {
  Function onFoo;

  XComponent() {
    onFoo = _onFoo;
  }

  void _onFoo() {
    print('foo!');
  }
}
```

**Comment by matanlurey** [comment]
I know it's been a while since I filed this, but just wanted to bump. Is it possible that when Angular CD knows the value can't possibly change (e.g. it's a method definition on the class) that it parties on without using an identical() check? @yjbanov

**Comment by yjbanov** [comment]
I don't think we can make it a P1 just yet, given that the workaround isn't that bad. But we definitely need to fix this, as it is not straight-forward to debug.

**Comment by matanlurey** [comment]
Is it possible to verify how Angular 1.0 supported this? I took a quick look at the code and the only thing I can think of is it used equality, not identity.

**Comment by yjbanov** [comment]
IIRC this used to be a bug in ng1 as well and required an explicit fix, but wasn't the one fixing it, so not sure how it works there. @mhevery or @rkirov might know.

**Comment by mhevery** [comment]
The issue is that you cant tell the difference between a class with `foo` method or class with `foo` property which is a function. In ng1 we had some horrible hack for this, something like reading the property twice and checking for identity, if different we assumed method if same we assumed property.

@vsavkin could you add your thoughts?

**Comment by naomiblack** [comment]
Will not fix. Reasonable workaround exists.
