### ISSUE TITLE
HttpParams doesn't have appendAll method... 

### ISSUE THREAD

**Issue by eladcandroid** [angular/angular#20798]
Angular version: 5.0.3

**Comment by harunurhan** [comment]
@eladcandroid 
To be clear, are you suggesting to have an `appendAll` that works like constructor, implemented #18490 ?

**Comment by eladcandroid** [comment]
@harunurhan I suggested to add an "appendAll" method that works as the method in URLSearchParams class, very similar to that code:
https://github.com/angular/angular/blob/c2dbc55f115eb259a6d90e2b45ed61c329258c22/packages/http/src/url_search_params.ts#L144

**Comment by eladcandroid** [comment]
@harunurhan You're great! Thanks!

**Comment by eladcandroid** [comment]
@harunurhan One small thing - how can I pass a HttpParams object to this method? (like I did with URLSearchParams.appendAll)

**Comment by harunurhan** [comment]
@eladcandroid for this one, implementation should change. well actually if this is required. maybe it would be better to use existing constructor inside `appendAll` which will also give the ability to support appending all from string out of the box.

**Comment by eladcandroid** [comment]
@harunurhan In my opinion HttpParams should be equivalent to the one it replaces him, at least with the parameters in methods, so the appendAll method should get the object.. 
But the maintainers should take the decision as you said.
