### ISSUE TITLE
Observable timer not working after open window.print() method and not able to get the change detection of closing last tab of application in any browser

### ISSUE THREAD

**Issue by uyadav0001** [angular/angular#20790]
let timer = Observable.timer(200, 1000);
    timer.subscribe(t => {
      localStorage.setItem('lastActiveInBrowser', (new Date()).getTime().toString());
    });
  }

Above code is stops  when print window opens

Thanks

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jotatoledo** [comment]
Add a reproduction of the issue

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by IgorMinar** [comment]
window.print() block the UI thread of the application. The application freezes and can't do anything. This is how browsers work and Angular can't do anything about it. This is why I'm closing this issue.
