### ISSUE TITLE
Child route guards should be evaluated **after** parent resolves

### ISSUE THREAD

**Issue by xaralis** [angular/angular#20805]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently, child route guards have no access to parent route resolves, because resolves are being evaluated **after all guards have been dealt with no matter if these are in child or parent routes**.

## Expected behavior

Child route guards should be evaluated **after** the parent route resolves are finished.

## What is the motivation / use case for changing the behavior?

When dealing with more complicated nested route structure, current state of things results in writing unnecessary and increasingly more complicated code in deeper levels of routing.

Example:

- 3 kinds of entities: `Website`, `Organization`, and list of `News`
- `Website` can have related `Organization`
- News are only available, if `Website` has `Organization` set up, because these object are bound to both

Now consider having a page with `News` detail which sits on `/website/:websiteId/news/:newsId`. As mentioned before, this can only be shown when `Website` has an `Organization` link, this means we need to add guard `WebsiteHasOrganizationGuard` on the news route level. Something like this:

```
{
    path: '',
    resolve: {
        website: WebsiteResolver,
        organization: WebsiteOrganizationResolver,
    },
    component: WebsiteComponent,
    children: [
        {
            path: 'news-detail/:news',
            pathMatch: 'full',
            canActivate: [
                WebsiteHasOrganizationGuard,
            ],
            children: [
                {
                    path: '',
                    canActivate: [
                        NewsExists,
                    ],
                    resolve: {
                        news: NewsResolver,
                    },
                    component: NewsDetailComponent,
                },
            ]
        }
    ]
}
```

In order to show the news page, we need to evaluate both `WebsiteHasOrganizationGuard` and `NewsExists` guard. These are run according to proposed sequence: first parent, then child. Unfortunately, **none of these guards can take advantage of parent resolves of `website` and `organization`**. Since both `NewsExists` and `WebsiteHasOrganization` guards are triggered before the `WebsiteResolver` and `WebsiteOrganizationResolver`, we are forced to mimic logic of both of them in both guards in order to successfully evaluate them.

**This is against DRY and gets increasingly more complicated within deep trees of nested routes.** Quite commonly, one needs to write single-use guards/resolvers that span multiple objects that relate on each other.

If parent resolves we're evaluated **before child guards**, we can easily share the resolved `Website` and `Organization` objects in the child guards without any boilerplate code.

## Environment

<pre><code>
Angular version: 5.0.2

Browser:
- Not related to browser version

**Comment by jasonaden** [comment]
Thanks for the feature request. I think this could be debated and could be different depending on use case.

But right now the router is designed to do Guards first. This avoids making unnecessary requests to the server for resources that may not be needed anyway (since routing will fail if any Guards fail). In general, we shouldn't be kicking off these requests (Resolvers) unless we will actually need the data, and the only way to know is to have all Guards pass first.

Also, the router doesn't do incremental activation. It's an all-or-nothing approach. So Guards pass, then Resolvers collect data, and when everything is ready Activation is done synchronously.

Since this is as-designed, I'll close this issue. Maybe at some point there could be a way to adjust these sequences, but that would likely be a very different router designed with the ability to configure rules like this.

**Comment by chris13524** [comment]
I came across this use case today. We have a dashboard which can have different user roles. When the dashboard is loaded, an organization is determined (users can be part of multiple organizations or one is specified in the URL). We then have different sub-dashboard pages which have guards and those will be available or not depending on their user role in the organization.

**Comment by xaralis** [comment]
@chris13524 Since this is a wontfix, I suggest dropping the resolvers and replacing them by guards that also do the loading part and store it somewhere in the app state. Guards go from top to bottom unlike resolvers which go the other way around. And yes, I still think this is bad design decision even though I understand the reasoning behind it.

**Comment by chris13524** [comment]
@xaralis So something like a `getInstance()` method... good idea!

What do mean guards to from top to bottom? They check child roots or parent roots first?

**Comment by xaralis** [comment]
@chris13524 I don't have a definitive solution but guards can definitely be able to act as resolvers too in case you have some application state to store data to (and get from in the components). NgRx can be a solution, for example.

Guards are triggered from top to bottom, from parent to children. That's the way both resolvers and guards should work from my point of view. Resolvers should act the same, but Angular devs are not willing to change this behavior because the router is unable to act this way at the moment (see above). It might be supported in some _distant_ future.

For the time being, I suggest dropping resolvers and let guards in combination with some state management tool do their job.
