### ISSUE TITLE
Service Worker: package.json esm2015 points to wrong path

### ISSUE THREAD

**Issue by Doehl** [angular/angular#20801]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The Service Worker package points to a non-existing path for the esm2015 build.
Current value is "esm15"

This makes build with Google Closure Compiler impossible with following settings.
--package_json_entry_names es2015
--process_common_js_modules

`"es2015": "./esm15/service-worker.js",`

## Expected behavior

The esm2015 value should be "esm2015".
`"es2015": "./esm2015/service-worker.js",`

A PR fix has been submitted  #20800 

## Environment

<pre><code>
Angular version: 5.0.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.1  
- Platform: Windows  

Others:

</code></pre>

**Comment by alxhub** [comment]
Fixed by da3563ce.
