### ISSUE TITLE
Again error in Angular.io documentation

### ISSUE THREAD

**Issue by pasha-bolokhov** [angular/angular#20809]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Look at
https://angular.io/guide/structural-directives#write-a-structural-directive
and read:
"""
The directive attribute name should be spelled in lowerCamelCase and begin with a prefix. Don't use ng. That prefix belongs to Angular. Pick something short that fits you or your company. In this example, the prefix is my.
"""
No it's not "my"!!! In your example it's "app".

Another thing to note: 
"""
The directive class name ends in Directive per the style guide. Angular's own directives do not.
"""
Very smart and consistent, people! I'll look at your own surprise when you read this five years from now! Did it ever occur that the given Angular framework is WAY more complex than it should be? We're just wanting a Dynamic HTML, not a new OS! It's just incredible that in order to compose a pure-content page, you always have to include JS or TS — in the form of components defining classes that literally do nothing (if it's a pure content). Oh, guess what, componenting HTML and CSS is now the modern trend!! Very nice! Maybe you should think further ahead and make a simpler syntax for HTML. Our children will be grateful to you. As of right now, they will hate you (nothing personal)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
The docs issue has been fixed in #20658.

**Comment by aravindfz** [comment]
@gkalpak If the above issue is closed. Can we close this too.
