### ISSUE TITLE
Router.url always shows '/' onInit

### ISSUE THREAD

**Issue by jettcalleja** [angular/angular#20818]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

```typescript
// it shows the "previous" url when this.router is used in SideBarComponent
import { Router } from '@angular/core'
// ...
export class SidebarComponent implements OnInit {
  ngOnInit() {
    this.router.url; // shows '/'
  }
}
```

## Expected behavior

```typescript
import { Router } from '@angular/core'
// ...
export class SidebarComponent implements OnInit {
  ngOnInit() {
    this.router.url; // should be for example '/dashboard'
  }
}
```

## Environment

<pre><code>
Angular version: ^5.0.0

Browser:
- [x] Chrome (desktop) version 62.0.3202.94
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v.8.9.1
- Platform: Windows

**Comment by aravindfz** [comment]
can you add your code. I suppose that the `basehref` is set. Can you update the code

**Comment by jettcalleja** [comment]
@aravindfz yes, the `<base href="/">` is set, angular-cli does this by default.

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
