### ISSUE TITLE
Support callback functions for API functions

### ISSUE THREAD

**Issue by matsko** [angular/angular#20812]
In order to open up the animations API to support a better plugin architecture, the DSL functions need to support callback functions to be able to get dynamically generated values.

This issue will track the progress of these new features for 5.x:

### Phase 1: style()
Allowing `style()` to compute its own values dynamically would allow for custom plugins that can render values at runtime.

```ts
function customStyleFn(element: any, styles: {[prop: string]: string|number}, params: {[key: string]: any}) {
  return { prop: generateDynamicValue() };
}

style(customStyleFn)
```

### Phase 2: stagger()
`stagger()` can then animate and collect values dynamically.

```ts
  /*
    it stagger animates like this...
    0 1 2
    1 2 3
    2 3 4
  */
function topLeftToBottomRightStagger(duration: number) {
  return (entries: {element, styles}[], params: {[key: string]: any}): number[] => {
    const first = entries[0].element;
    const x0 = first.offsetLeft;
    const y0 = first.offsetTop;
    const w0 = first.offsetWidth;
    const h0 = first.offsetHeight;
    const unitX = x0 + w0;
    const unitY = y0 + h0;
  
    return entries.map(entry => {
      const {element} = entry;
      const y = element.offsetTop;
      const x = element.offsetLeft;
      const offsetX = x > 0 ? Math.floor(x / unitX) : 0;
      const offsetY = y > 0 ? Math.floor(y / unitY) : 0;
      return (offsetX + offsetY) * duration;
    });
  }
}

query(':enter', [
  stagger(topLeftToBottomRightStagger(1000), [ ... ])
])
```

### Phase 3: query()
This can be used to have plugins track elements that can later be referenced (like anchoring).

### Phase 4: remaining DSL functions?
If there is a need, then the remaining DSL functions could be dynamic as well.

**Comment by vitorrd** [comment]
Are there any updates on this? Is there anything I can do to help?

**Comment by jpzwarte** [comment]
Please add this :) Afaict we need this in order to do custom staggering as described here (https://uxdesign.cc/the-ultimate-guide-to-proper-use-of-animation-in-ux-10bd98614fa9).

**Comment by MightyRevenge** [comment]
Can't wait for this! What can I do to help?
