### ISSUE TITLE
Wrong date format in local 'de'

### ISSUE THREAD

**Issue by mtinner** [angular/angular#20816]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
6.12.2017

## Expected behavior
12. Dez. 2017

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/11Bd21?p=preview

## What is the motivation / use case for changing the behavior?
Wrong datePipe behavior on 'mediumDate' and default format

## Environment

<pre><code>
Angular version: since v 5.x.x

Browser:
- all Browsers

**Comment by ocombe** [comment]
The medium date format used by CLDR for german is `dd.mm.yy` https://github.com/unicode-cldr/cldr-dates-modern/blob/master/main/de/ca-gregorian.json#L319
Do you have any information that makes you think that it should be `dd. mmm. yy` instead ?

**Comment by mtinner** [comment]
according to the other languages (en and fr in my plnkr) its obviously an other format. so its not consistent.

**Comment by ocombe** [comment]
Locales are not consistent, that's why you rely on predefined formats, and that's why we use CLDR.
If you want the same format for all of your locales you can use a custom format like "dd mmm yy" instead.

**Comment by mtinner** [comment]
well okay, but make no sense for german

**Comment by ocombe** [comment]
I agree that it looks weird.
You might be interested by this feature request: https://github.com/angular/angular/issues/19823
It's a feature to achieve the same thing that was available in Angular v4 when we used the format "yMMMd".
You could say that you want numeric day/year, and medium month, but keep the order consistent with what the locale requires.
