### ISSUE TITLE
ERROR in Error: Could not resolve module @angular/core

### ISSUE THREAD

**Issue by papakai** [angular/angular#20820]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Minimal reproduction of the problem with instructions
As this is a internal tool I can't provide a test case.
```bash
ng build && ng serve --port 4200 --app full
ERROR in Error: Could not resolve module @angular/core
    at StaticSymbolResolver.getSymbolByModule (/home/kai/git/fmonitorcli/node_modules/@angular/compiler/bundles/compiler.umd.js:31884:30)
    at StaticReflector.findDeclaration (/home/kai/git/fmonitorcli/node_modules/@angular/compiler/bundles/compiler.umd.js:30371:63)
    at StaticReflector.initializeConversionMap (/home/kai/git/fmonitorcli/node_modules/@angular/compiler/bundles/compiler.umd.js:30636:36)
    at new StaticReflector (/home/kai/git/fmonitorcli/node_modules/@angular/compiler/bundles/compiler.umd.js:30317:14)
    at Object.createAotCompiler (/home/kai/git/fmonitorcli/node_modules/@angular/compiler/bundles/compiler.umd.js:32124:44)
    at AngularCompilerProgram._createCompiler (/home/kai/git/fmonitorcli/node_modules/@angular/compiler-cli/src/transformers/program.js:405:37)
    at AngularCompilerProgram.get [as compiler] (/home/kai/git/fmonitorcli/node_modules/@angular/compiler-cli/src/transformers/program.js:314:22)
    at AngularCompilerProgram.listLazyRoutes (/home/kai/git/fmonitorcli/node_modules/@angular/compiler-cli/src/transformers/program.js:157:20)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/kai/git/fmonitorcli/node_modules/@angular/compiler-cli/src/ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (/home/kai/git/fmonitorcli/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:247:66)
    at Promise.resolve.then.then (/home/kai/git/fmonitorcli/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:538:50)
```

ng build throws the above error

What I did: I have two apps configured, both as separate subfolders under /src e.g. /src/full and /src/tv. These folders are configured as root folder for these apps.
npm install got correctly processed and node_modules includes @angular/core module.

Looks like this is a path issue somewhere? Maybe the above description helps to figure a solution out.

## Environment
<pre><code>
Angular CLI: 1.5.4
Node: 6.12.0
OS: linux x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.4
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.4.2
webpack: 3.8.1

Browser:
- [x] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.12.0
- Platform:  
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
</code></pre>

**Comment by papakai** [comment]
Found the issue: tsconfig.app.json / tsconfig.spec.json included invalid paths after I moved them into these subfolders. No idea how this influences the build process, but correcting the paths fixed the above issue.
so fyi.

**Comment by ensonic** [comment]
Getting a decent error message would be gold though.

**Comment by shardulP** [comment]
@papakai could you please give me a sample path. I have done that but still issue persists.

**Comment by papakai** [comment]
@shardulP note that this might be project dependent, but anyways - here the content of my files as potential reference. I don't remember exactly which of the paths was wrong - I assume that the extends one was the reason.

tsconfig.app.json located in src folder
```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```
tsconfig.spec.json also located in src folder
```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "baseUrl": "./",
    "module": "commonjs",
    "target": "es5",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "test.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}
```

**Comment by shardulP** [comment]
@papakai Thanks for immediate reply but I am getting the same error I have checked paths inside tsconfig.app.json and tsconfig.spec.json is same. Still I am getting this error I will share my package.json.

**Comment by manzerProgen001** [comment]
Angular CLI: 1.6.3 (e)
Node: 9.5.0
OS: win32 x64
Angular: 4.4.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, tsc-wrapped

@angular/cdk: 5.1.1
@angular/cli: 1.6.3
@angular/material: 5.1.1
@angular/platform-webworker-dynamic: 6.0.9
@angular/platform-webworker: 6.0.9
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.6.8
@angular-devkit/schematics: 0.0.40
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.10
typescript: 2.6.2
webpack-dev-server: 2.9.7
webpack: 3.10.0



Packge.json
------------------------
{
  "name": "pi3",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "webpack-dev-server --port=4200",
    "build": "webpack",
    "test": "karma start ./karma.conf.js",
    "lint": "ng lint",
    "e2e": "protractor ./protractor.conf.js",
    "pree2e": "webdriver-manager update --standalone false --gecko false --quiet",
    "compile": "webpack --config webpack.config.js"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/core": "^0.6.8",
    "@angular-devkit/schematics": "0.0.40",
    "@angular/animations": "^4.2.4",
    "@angular/cdk": "^5.1.1",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/material": "^5.1.1",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/platform-webworker": "^6.0.9",
    "@angular/platform-webworker-dynamic": "^6.0.9",
    "@angular/router": "^4.2.4",
    "@auth0/angular-jwt": "^1.1.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.5",
    "@ngtools/webpack": "^1.5.1",
    "@types/d3": "^4.7.0",
    "@types/d3-sankey": "^0.7.2",
    "angular-2-dropdown-multiselect": "^1.6.0",
    "angular2-grid": "^2.0.7",
    "angular2-multiselect-dropdown": "^1.3.0",
    "angular2gridster": "^1.2.0",
    "c3": "^0.4.18",
    "core-js": "^2.4.1",
    "d3": "^4.10.2",
    "d3-sankey": "^0.7.1",
    "datamaps": "^0.5.8",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jwt-decode": "^2.2.0",
    "primeng": "^4.2.2",
    "rxjs": "^5.5.6",
    "topojson": "^3.0.2",
    "ts-helpers": "^1.1.1",
    "ts-topojson": "0.0.11",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.5.5",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "^2.0.4",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.3.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "^2.3.4",
    "webpack-dev-server": "~2.9.3",
    "webpack": "~3.10.0",
    "autoprefixer": "^6.5.3",
    "css-loader": "^0.28.1",
    "cssnano": "^3.10.0",
    "exports-loader": "^0.6.3",
    "file-loader": "^1.1.5",
    "html-webpack-plugin": "^2.29.0",
    "less-loader": "^4.0.5",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.1.2",
    "raw-loader": "^0.5.1",
    "sass-loader": "^6.0.3",
    "source-map-loader": "^0.2.0",
    "istanbul-instrumenter-loader": "^2.0.0",
    "style-loader": "^0.13.1",
    "stylus-loader": "^3.0.1",
    "url-loader": "^0.6.2",
    "circular-dependency-plugin": "^4.2.1",
    "copy-webpack-plugin": "^4.1.1",
    "uglifyjs-webpack-plugin": "^1.1.5"
  }
}
angular-cli.json
----------------------------
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "pi3",
    "ejected": true
  },
  "apps": [
    {
      "root": "src",
      "outDir": "pi3",
      "assets": [
        "assets",
        "favicon.ico",
        "assets/images/hp_logo2.png"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "assets/css/bootstrap-3.3.7.min.css",
        "../node_modules/font-awesome/css/font-awesome.min.css",
        "../node_modules/primeng/resources/primeng.min.css",
        "../node_modules/primeng/resources/themes/omega/theme.css",
        "../node_modules/c3/c3.min.css",
        "styles.css",
        "theme.css",
        "charts.css"
      ],
      "scripts": [
        "../node_modules/hammerjs/hammer.min.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {
    }
  }
}
tsconfig.json
--------------------------
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}

tsconfig.app.json
-----------------------
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}

tsconfig.spec.json
----------------------------
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "baseUrl": "./",
    "module": "commonjs",
    "target": "es5",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "test.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}


When running command 'npm start' getting error as  below:-

ERROR in Error: Could not resolve module @angular/core
    at StaticSymbolResolver.getSymbolByModule (D:\Users\ansarif\Documents\projects\git\gitpull Updated\git Pull and Merge\pi3_GIT_Pull_Merge-----\Git_Test_Working\Progen-pi-UI_20180718_2PM\node_modules\@angular\compiler\bundles\compiler.umd.js:25763:30)
    at StaticReflector.findDeclaration (D:\Users\ansarif\Documents\projects\git\gitpull Updated\git Pull and Merge\pi3_GIT_Pull_Merge-----\Git_Test_Working\Progen-pi-UI_20180718_2PM\node_modules\@angular\compiler\bundles\compiler.umd.js:24512:63)
    at StaticReflector.initializeConversionMap (D:\Users\ansarif\Documents\projects\git\gitpull Updated\git Pull and Merge\pi3_GIT_Pull_Merge-----\Git_Test_Working\Progen-pi-UI_20180718_2PM\node_modules\@angular\compiler\bundles\compiler.umd.js:24730:36)
    at new StaticReflector (D:\Users\ansarif\Documents\projects\git\gitpull Updated\git Pull and Merge\pi3_GIT_Pull_Merge-----\Git_Test_Working\Progen-pi-UI_20180718_2PM\node_modules\@angular\compiler\bundles\compiler.umd.js:24472:14)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (D:\Users\ansarif\Documents\projects\git\gitpull Updated\git Pull and Merge\pi3_GIT_Pull_Merge-----\Git_Test_Working\Progen-pi-UI_20180718_2PM\node_modules\@angular\compiler-cli\src\ngtools_api.js:90:31)
    at AotPlugin._getLazyRoutesFromNgtools (D:\Users\ansarif\Documents\projects\git\gitpull Updated\git Pull and Merge\pi3_GIT_Pull_Merge-----\Git_Test_Working\Progen-pi-UI_20180718_2PM\node_modules\@ngtools\webpack\src\plugin.js:240:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (D:\Users\ansarif\Documents\projects\git\gitpull Updated\git Pull and Merge\pi3_GIT_Pull_Merge-----\Git_Test_Working\Progen-pi-UI_20180718_2PM\node_modules\@ngtools\webpack\src\plugin.js:493:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
Child html-webpack-plugin for "index.html":
     1 asset
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 1.01 kB {0} [built]
webpack: Failed to compile.

**Comment by Omar-Qalei** [comment]
I solve this problem .
it's very easy first of all if you have another project open that and u can open tsconfig.json then copy all data and paste that in your project error . solved 
if you don't have another project create one then try to do above.
