### ISSUE TITLE
Please Help "Production build error" 

### ISSUE THREAD

**Issue by Yogeshjuya1993** [angular/angular#20826]
When we build app in production successfully on device after that it's showing below error -:

Uncaught Error: Cannot resolve all parameters for 't'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 't' is decorated with Injectable.

: ----------------------Please Help me---------------

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
