### ISSUE TITLE
Compiler-cli (ngc) strips out initialization values on class member variables

### ISSUE THREAD

**Issue by Bradleycorn** [angular/angular#20829]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When using the latest versions (5.0.4 or 5.0.5) of the @angular/compiler-cli, ngc() strips out class member variable initializations. Consider the following example typescript:

```
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { Subject } from 'rxjs/Subject';


@Injectable()
export class MyService {
    private observable: Observable<any>;
    private constructValue;

    // Some values that are initialized
    private subject: Subject<any> = new Subject<any>();
    private someValue = 1;
 
    constructor() {
        // we expect that this.subject exists, since it's already initialized.
        this.observable = this.subject.asObservable();

        // we expect that this.someValue is 1, since it's already initialized.
        if (this.someValue === 1) {
            this.constructValue = 5;
        }
    }

    // this should return true, but will always return false.
    public isWorking(): boolean {
        return (this.constructValue === 5);
    }
}
```

The above gets compiled to the following javascript when using ngc():

```
import { Injectable } from "@angular/core";
import { Subject } from "rxjs/Subject";
var MyService = /** @class */ (function () {
    function MyService() {
        this.observable = this.subject.asObservable();
        if (this.someValue === 1) {
            this.constructValue = 5;
        }
    }

    MyService.prototype.isWorking = 
    function () {
        return (this.constructValue === 5);
    };
    return MyService;
}());
```

This results in a runtime error when trying to use the MyService class, because in the constructor, `this.subject` is undefined and thus has no method, `asObservable()`. Further, if you got passed that, the isWorking method would never return true (even though the source is written in a manner where it should always return true) because `this.constructValue` didn't get properly set in the 
constructor, because the initialization of `this.someValue` was stripped out during compile.

See below for an example that shows what the typescript compiler outputs.

## Expected behavior
Initialization values should be output in a manner similar (identical?) to what the typescript compiler produces. Given the same source as above, `tsc` will output:

```
import { Injectable } from '@angular/core';
import { Subject } from 'rxjs/Subject';
var MyService = /** @class */ (function () {
    function MyService() {
        this.subject = new Subject();
        this.someValue = 1;
        this.observable = this.subject.asObservable();
        if (this.someValue === 1) {
            this.constructValue = 5;
        }
    }

    MyService.prototype.isWorking = function () {
        return (this.constructValue === 5);
    };
    MyService = __decorate([
        Injectable()
    ], MyService);
    return MyService;
}());
export { MyService };
```

Note that in the output, the constructor contains the initialization for `this.subject`, and `this.someValue`
```
function MyService() {
        this.subject = new Subject();
        this.someValue = 1;
```

## Minimal reproduction of the problem with instructions

This repo contains a demo of the problem:
https://github.com/Bradleycorn/ngc-demo

Clone the repo, and then `$ npm install && npm run build:ng` to compile it.
After compilation, look at the output `build/my.service.js` to see the problem.

Then, run `$ npm run build:ts` to compile with typescript and see the correct output.

## What is the motivation / use case for changing the behavior?

I want the ngc compiler to produce usable code that is compatible with code that the typesrcript compiler produces, is not broken, and works as intended from the source typescript.

## Environment

<pre><code>
Angular version: 5.0.5
typescript version: 2.5.3

Browser:
N/A
 
For Tooling issues:
- Node version: 8.4.0
- Platform:  Mac
</code></pre>

**Comment by sarunint** [comment]
Angular supports TypeScript 2.4.2. Support for TS2.5 is expected to land in Angular v5.1 and support for TS2.6 is later than that.

**Comment by Bradleycorn** [comment]
Confirmed, it works fine if use a supported version of typescript .... Move along, nothing to see here ...
