### ISSUE TITLE
angular.io is down!...

### ISSUE THREAD

**Issue by nakulnagariy** [angular/angular#20822]
the website is down.
![angulario](https://user-images.githubusercontent.com/26174424/33660991-fb0266fe-daab-11e7-92cf-8b4360bddc97.PNG)

**Comment by ericmartinezr** [comment]
Do you see something in the console? In the network tab? It's working fine for me.

**Comment by aravindfz** [comment]
It works fine now. @gkalpak can you close this :)

**Comment by gkalpak** [comment]
I am going to close this. Please, provide more info (such as the console output) if the problem persists.

**Comment by nakulnagariy** [comment]
here are some snaps, please take a look.

pfa

*Thanks & Regards*
Nakul Nagariya
Technical Evangelist
9035755294

**Comment by gkalpak** [comment]
I don't see any snaps 😕

**Comment by mkbhardwaj** [comment]
@gkalpak  even i am facing the same issue. Please find the below screenshot -
![image](https://user-images.githubusercontent.com/19253981/38502355-c7dc0360-3c2c-11e8-92ad-e45cc69e38e3.png)


I found following error in the console - : **Uncaught (in promise) TypeError: Cannot read property 'match' of undefined
    at worker-basic.min.js:1**

Feel free to ask for more details.

**Comment by mkbhardwaj** [comment]
@gkalpak @nakulnagariy  i just removed the cache and it's working fine for me now. 👍
