### ISSUE TITLE
angular2.x img tag src path load abnormal, how to display the default path 

### ISSUE THREAD

**Issue by htm9527** [angular/angular#20825]
@Component({
  selector: 'my-app',
  template: `
    <div>

      <img [src]="{{img_url || 'https://placehold.it/350x250&text=11'}}">

       <img [src]="{{img_url2 || 'https://placehold.it/350x250&text=11'}}">
    </div>
  `,
})
export class App {
  name:string;
  constructor() {
    this.img_url = "xxxxx.png";//The path exists, but this is a wrong path
    this.img_url2 = "";   
  }
}

**Comment by htm9527** [comment]
第一个img标签：默认路径图片不加载，加载img_url 图片失败
第二个img标签：默认路径图片加载成功
根据angular1.x语法<img ng-src="xxx ||  'https://placehold.it/350x250&text=11' ">不管xxx是空值还是错误路径都会加载指定的默认路径的。

**Comment by IgorMinar** [comment]
@htm9527 could you please try to describe the issue in English. Angular is being worked on contributors from all parts of world, and for practical purposes we settled on using English as the primary communication language.

I know that English as the primary language is not ideal for some folks in the community, but given the development tools we have available to us, cross-language communication during the development process is very difficult.

We try hard to respond and process issues that are not expressed in perfect English - as long as we can get the point being communicated. I'm myself not native English speaker, so I understand how not ideal this is.

**Comment by matthew-ch** [comment]
语法错误，怎么加载出来的。。。
https://angular.io/guide/template-syntax#interpolation----

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
