### ISSUE TITLE
Head over heals for ANGULAR5!!! SUPER GREAT JOB!!!

### ISSUE THREAD

**Issue by AckerApple** [angular/angular#20839]
(close this issue)

I simply cannot believe how incredibly advanced Angular5 is over 4

My app in Angular4, after AOT compiling and webpack minification, was 11mb and took about 3 minutes complete.

NOW, after Angular5 having AOT built-in and super advanced tree shaking, my app is 2.5mb and only takes 30 seconds to build.

CANNOT BELIEVE IT. Had to touch entire app for myself to believe it.

So so so so so so so so so so so so incredibly ecstatic for Angular5. Extra great job you guys!

_Acker Apple

**Comment by mlc-mlapis** [comment]
@AckerApple ... congratulations really much! ... but are you sure that there weren't any unused chunk's parts on 4.x (any unwanted vendor files) that you lately eliminated by any even small changes when updating to 5.x? It is simply unbelievable that the size was reduced about 400%.

**Comment by IgorMinar** [comment]
Thanks for the note. I'm sure that I speak for everyone that contributed to v5 that we appreciate it. 

I'm having a hard time deciding which of our "pre-canned" github replies to use to close your issue, I'll go with this one 😃 :

-----

> Thanks for reporting this issue. Luckily it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.
> 
> If after upgrade the problem still exists in your application please open a new issue and provide a plunker reproducing the problem and describing the difference between the expected and current behavior. You can use this plunker template: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by AckerApple** [comment]
I absolutely did NOT drop any dependencies

Updating from Angular4 to Angular5 at first was a can of worms...

I run two semi-popular npm packages (and several other less popular Angular packages):
- [angular-file](https://www.npmjs.com/package/angular-file)
- [ack-angular-webcam](https://www.npmjs.com/package/ack-angular-webcam)

Both packages were having issue reports about having Angular5 but my packages were built in Angular4. Then I built with 5 and had Angular4 issue reporters. I know I don't absolutely definitively know the exact science here and am sorta going by feel here. This issue, [linked here](https://github.com/angular/angular/issues/19607), led me to believe I was having conflicts with Angular4 and 5

EVENT during watching files, NOT minified and no webpack involved, **MY FILES ARE LESS THAN THE Angular4 PRODUCTION FILES** ... I feel the capitals and bold are necessary to illustrate my energized excitedness => The evidence is there Angular5 reduces and performs better.

I hate to try to stroke my ego amongst you fellas that wrote Angular but I know my shit enough to know just upgrading to Angular5 made a 400% difference

:)

**Comment by AckerApple** [comment]
Another fantastic Angular5 report! My favorite package of mine, [ack-angular](https://www.npmjs.com/package/ack-angular), went down from 2.5mb on Angular4 to 1.6mb on Angular5.

My biggest savings are coming from:
- Animation consolidation that occurred in Angular5. I use A LOT of animations
- Advanced tree shaking!!!!! So much unused code from my dependencies is now actually being removed in Angular5. SO HAPPY HERE!!!!!
- Built-in AOT compiling!!!!!! This is giving us HUGE savings now that we have completely removed a step in compiling.

I'm so happy with the release!!! So so so very happy

**Comment by IgorMinar** [comment]
:-)
