### ISSUE TITLE
ERROR DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.

### ISSUE THREAD

**Issue by oztek22** [angular/angular#20836]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When I am adding multiple classes dynamically like below I'm getting this error
`<div class="view"  [class.responsive-svg]="isCard" [class.bottom-left]="pos=='bl'" [class.top-right]="pos=='tr'" [class.top-left]="pos=='tl'"></div>`

> `ERROR DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.
    at EmulatedEncapsulationDomRenderer2.DefaultDomRenderer2.removeClass (webpack-internal:///../../../platform-browser/esm5/platform-browser.js:2941:40)
    at BaseAnimationRenderer.removeClass (webpack-internal:///../../../platform-browser/esm5/animations.js:592:41)
    at DebugRenderer2.removeClass (webpack-internal:///../../../core/esm5/core.js:15240:23)
    at setElementClass (webpack-internal:///../../../core/esm5/core.js:10639:18)
    at checkAndUpdateElementValue (webpack-internal:///../../../core/esm5/core.js:10590:13)
    at checkAndUpdateElementInline (webpack-internal:///../../../core/esm5/core.js:10538:24)
    at checkAndUpdateNodeInline (webpack-internal:///../../../core/esm5/core.js:13790:20)
    at checkAndUpdateNode (webpack-internal:///../../../core/esm5/core.js:13737:16)
    at debugCheckAndUpdateNode (webpack-internal:///../../../core/esm5/core.js:14609:76)
    at debugCheckRenderNodeFn (webpack-internal:///../../../core/esm5/core.js:14588:13)
View_AppComponent_0 @ AppComponent.html:169
proxyClass @ compiler.js:14525
DebugContext_.logError @ core.js:14681
ErrorHandler.handleError @ core.js:1411
(anonymous) @ core.js:5794
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
NgZone.runOutsideAngular @ core.js:4578
ApplicationRef.tick @ core.js:5794
ApplicationRef._loadComponent @ core.js:5853
ApplicationRef.bootstrap @ core.js:5741
(anonymous) @ core.js:5461
PlatformRef._moduleDoBootstrap @ core.js:5461
(anonymous) @ core.js:5382
ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.js:4630
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:142
(anonymous) @ zone.js:873
ZoneDelegate.invokeTask @ zone.js:425
onInvokeTask @ core.js:4621
ZoneDelegate.invokeTask @ zone.js:424
Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
Promise resolved (async)
scheduleMicroTask @ zone.js:585
ZoneDelegate.scheduleTask @ zone.js:414
Zone.scheduleTask @ zone.js:236
Zone.scheduleMicroTask @ zone.js:256
scheduleResolveOrReject @ zone.js:871
ZoneAwarePromise.then @ zone.js:981
PlatformRef.bootstrapModule @ core.js:5448
(anonymous) @ main.ts:11
../../../../../src/main.ts @ main.bundle.js:76
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:91
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1
`

## Minimal reproduction of the problem with instructions

Just add this lines with var in cli project and it'll show error
`<div class="view"  [class.responsive-svg]="isCard" [class.bottom-left]="pos=='bl'" [class.top-right]="pos=='tr'" [class.top-left]="pos=='tl'"></div>`

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ *] Chrome (desktop) version 62
 
For Tooling issues:
- Node version: 7.4.0  
- Platform:  Windows

**Comment by pkozlowski-opensource** [comment]
Could you please provide a minimal reproduce scenario in a plunker or similar? It is super-hard to debug / understand full, minified application.

**Comment by oztek22** [comment]
Found the issue.
I was having a syntax error on some other line. so the issue is that error is  showing on wrong line I guess.
I wrote [class..className] inplace of [class.className]

[plunker](http://plnkr.co/edit/TepaM4jA2AYNVLYNtM7S?p=preview)

expected behavior: It should show error on correct line.
thanks and sorry for the trouble.
