### ISSUE TITLE
'form' isn't a known attribute on 'button'

### ISSUE THREAD

**Issue by craigmichaelmartin** [angular/angular#20838]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Binding to the [`form` attribute of a button](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-form) element results in an error, `Can't bind to 'form' since it isn't a known property of 'button'.`
<details>
  <summary>See Full Error</summary>
  <img width="1385" alt="screen shot 2017-12-06 at 1 51 17 pm" src="https://user-images.githubusercontent.com/6545515/33679698-6bfc5b90-da8d-11e7-977e-30383ec2cd2e.png">
</details>

## Expected behavior
I would expect to be able to bind to a button's `form` attribute.

## Minimal reproduction of the problem with instructions
```
@Component({
  selector: 'my-app',
  template: `
    <div>
      <form [id]="formId">
      </form>
      <button type="submit" [form]="formId">Submit</button>
    </div>
  `,
})
export class App {
  formId:string;
  constructor() {
    this.formId = 'foo';
  }
}
```
Plunker: http://plnkr.co/edit/uqLGZrAvDCN20CgjJmbE
<details>
  <summary>See Plunker Screenshot of Error</summary>
  <img width="1384" alt="screen shot 2017-12-06 at 2 01 43 pm" src="https://user-images.githubusercontent.com/6545515/33680073-81ba4842-da8e-11e7-821c-950b806cb745.png">
</details>

## What is the motivation / use case for changing the behavior?
To allow binding to the the button's `form` attribute for cases when the submit button cannot be in the form element.

I would be happy to implement the fix, assuming the `form` attribute is not being intentionally omitted from the button's list of attributes: https://github.com/angular/angular/blob/master/packages/compiler/src/schema/dom_element_schema_registry.ts#L99

Thanks for you work!!

## Environment

<pre><code>
Angular version: 4.4.6

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.7.0
- Platform: Mac

</code></pre>

**Comment by ericmartinezr** [comment]
Did you try with `[attr.form]`?

**Comment by Charlinho** [comment]
Try to use [attr.form]

**Comment by pkozlowski-opensource** [comment]
Thnx @ericmartinezr and @Charlinho

**Comment by craigmichaelmartin** [comment]
`[attr.form]` indeed works! Thanks for the help! That said, this feels like more like a work-around than ideal behavior. This has been the first attribute of a native element that I haven't been able to bind to directly. Have I just getting on happy-paths, or is this exceptional?

**Comment by pkozlowski-opensource** [comment]
> This has been the first attribute of a native element that I haven't been able to bind to directly. Have I just getting on happy-paths, or is this exceptional?

It is not a work-around. By default Angular binds to _properties_ and most of the time a given attribute have a corresponding property. But it is not always the case, as in the `form` attribute. S

**Comment by sarunint** [comment]
On `input` elements, there is no form *property*, just form *attribute*. Property and Attribute are not the same.

**Comment by craigmichaelmartin** [comment]
Thanks for you responses! I appreciate it!

>It is not a work-around. By default Angular binds to properties and most of the time a given attribute have a corresponding property. But it is not always the case, as in the form attribute. 

I guess I'm wondering why that is (that the angular element doesn't have a property that is an attribute on the native element)? Is it because it is readonly on `HTMLButtonElement`s?

> there is no form property, just form attribute. Property and Attribute are not the same.

There *is* a `form` property for the attribute on `HTMLButtonElement`s ([web apis spec](https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#the-button-element)), as there is a `form` attribute on the html button element ([spec](https://html.spec.whatwg.org/#the-button-element)). Thus, I'm suggesting that there should be a form property on the angular element, or at least that its absence [here](https://github.com/angular/angular/blob/master/packages/compiler/src/schema/dom_element_schema_registry.ts#L99) seems exceptional.

**Comment by pkozlowski-opensource** [comment]
> There is a form property for the attribute on HTMLButtonElements (web apis spec),

Yes, but it is read-only property so you can't bind to it: https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement

> Thus, I'm suggesting that there should be a form property on the angular element

There is no such thing as "angular element", you are binding to native DOM elements directly.

**Comment by craigmichaelmartin** [comment]
Thanks so much! I apologize for using vague terminology. I'm not familiar with angular code under the hood, and assumed there was some javascript objects that modeled the dom nodes and served as a layer of abstraction.

Thanks for highlighting readonly as the significant factor!
