### ISSUE TITLE
[hidden]="true" not added to dom node when rendered on server

### ISSUE THREAD

**Issue by manda-linda** [angular/angular#20835]
## I'm submitting a...
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently when building an angular app on the server (using platform-server), the hidden attribute is not added to the pre-rendered dom node when bound as:

```
[hidden]="true"
```
It looks like this regression was introduced with the DefaultServerRenderer2 class. This bug was previously identified and fixed in the Universal node-renderer: https://github.com/angular/universal/issues/612 

## Expected behavior
The hidden attribute should be added to the dom node when bound to a true boolean.

## What is the motivation / use case for changing the behavior?
Server side rendering should support the same templating features as client side rendering.

## Environment

<pre><code>
Angular version: 5.0.5

</code></pre>

**Comment by vikerman** [comment]
This seems to be working as intended in 6.0
