### ISSUE TITLE
Safe-access syntax should does not type check correctly.

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#20841]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

The expression:

`(address | async)?.model?.street` generates a expression that does not doesn't erase the falsy side of the  address type nor the model type as the generated code contains multiple calls to the async pipe which are not treated as idempotent by TypeScript.

## Minimal reproduction of the problem with instructions

Pending.

## What is the motivation / use case for changing the behavior?

More ergonomic type checking.

This can be worked around by inserting odd looking '!' as in:

 `(address | async)!?.mode!l?.street`

which should be implied by using `?.`.

**Comment by JoostK** [comment]
This is working properly in Ivy's template type checker.
