### ISSUE TITLE
Ng2 component in hybrid app with downgradeModule does not work

### ISSUE THREAD

**Issue by JoeyLi-1** [angular/angular#20856]
## I'm submitting a...

[ X] Documentation issue or request

I was using UpgradeModule for the first project and it works. It is a small project. 
But I encountered $digest issue when upgrading second larger project. So I switch to use downgradeModule for better performance as described here: https://pr18487-aedf0aa.ngbuilds.io/guide/upgrade-performance

I did as the example said, add `
angular.module('mainAngularJsModule', [
  downgradedModule
]);
`
And did not change anything in ng1 app since the document said:

> It does not require you to change how you bootstrap your AngularJS app

The app works fine now, but the only issue is that I could not add ng2 componets!!!

I added a new ng2 component named testcomponent and add in my main.ts
`angular.module('mainAngularJsModule').directive(
     'test1',
     downgradeComponent({ component: TestComponent }) as angular.IDirectiveFactory
   );`
Add `<test1></test1> `in index.html.

But this directive is not working or even not registered in ng1. 
I had checked as:
`var has1 = $injector.has('test1Directive');
    var has2 = $injector.has('test1');`
Both returned false;

I had created a plunker to describe my issue https://plnkr.co/edit/ZaIp5i20fiqH1vfBnZ99?p=info

Could you please tell me how to register component? Or at least give me a hybrid demo with downgrademodule. 

## Environment

Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version latest

 
For Tooling issues:
- Node version: 8.5.0
- Platform:  Win10

Thanks,
Joey

**Comment by JoeyLi-1** [comment]
@tbosch @gkalpak Or anybody familiar with downgrademodule, please help me out! Thank you!

**Comment by JoeyLi-1** [comment]
**Update:**
I found the problem is where do you place this `angular.bootstrap(document.body, ['interestApp']);`
E.g. I have two files:
**app.js** for ng1

> angular.module('interestApp', []).config(...).directive(...).service(...);

**and main.ts for ng2**

> const bootstrapFn = (extraProviders: StaticProvider[]) => {
>   const platformRef = platformBrowserDynamic(extraProviders);
>   return platformRef.bootstrapModule(AppModule);
> };
> const downgradedModule = downgradeModule(bootstrapFn);
> 
> angular.module("interestApp", [downgradedModule]).directive("addPin", downgradeComponent({ component: AddPinComponent }));
> 

If I add `angular.bootstrap` in app.js then all controllers/routers works, but ng2 components not work;
If I add `angular.bootstrap` in main.ts then all the ng2 components works, but ng1 controllers not work;

If I want both of them work, should I merge main.ts and app.js together and add `angular.bootstrap` at the end of the file?

What should I do to achieve this:
> It does not require you to change how you bootstrap your AngularJS app. 

in https://pr18487-aedf0aa.ngbuilds.io/guide/upgrade-performance

**Comment by JoeyLi-1** [comment]
Finally, I know how to use downgrademodule.........
1 change code in app.js

> exports = angular.module('interestApp', []).config(...).directive(...).service(...);

2 change code in main.ts;

> import './relativepath/app.js';
angular.module("nginterestApp", ['interestApp', downgradedModule]).directive("addPin", downgradeComponent({ component: AddPinComponent }));
angular.bootstrap(document.body, ['interestApp']);

And then, all works!
I was just misleading by the 

> It does not require you to change how you bootstrap your AngularJS app.

in https://pr18487-aedf0aa.ngbuilds.io/guide/upgrade-performance

Close this issue. And it would be great if somebody could change a little bit of the description in official document above.

**Comment by gkalpak** [comment]
The docs are correct. The problem is caused by incorrect use of `angular.module()`. You are creating too modules, by using the `angular.module(moduleName: string, deps: any[])` signature. This is not specific to ngUpgrade or `downgradeModule`; your pure AngularJS should not work as expected either.

You should create the module once and only _retrieve_ the module if you want to define more stuff in a different file. You can retrieve an existing module by using the `angular.module(moduleName: stirng)` signature (without the `deps` param).

See [here][1] for more info.

[1]: https://docs.angularjs.org/api/ng/function/angular.module#angular.module-arguments

**Comment by JoeyLi-1** [comment]
@gkalpak Yes, in the past 40 hrs I was trying my best to do like you said

> You should create the module once and only retrieve the module if you want to define more stuff in a different file.

 But not working.
I don`t know how to do these two things in two separate files:
1 in app.js (this is my ng1 app)
angular.module('interestApp', ['ui-route', .....]);
2 in main.ts (this is my ng2 app)
angular.module('interestApp', [downgradedModule]);

And then I found this http://www.syntaxsuccess.com/viewarticle/angular-ngupgrade-with-downgrademodule

Just minutes ago, I finally understood what does the author mean by:

> import './angularjs-app/app';
> angular.module('ng-upgrade', [ 'old-angularjs-app', downgradedModule ]);
> angular.bootstrap(document, ['ng-upgrade']);

And It seems ng1 controller and ng2 component all work.
If 
> your pure AngularJS should not work as expected either

Could you please provide an example or a plunker to guide me the right way?

**Comment by JoeyLi-1** [comment]
@gkalpak  BTW, I upload my sample project here: https://github.com/JoeyXXX18/ng2_upgrade_downgrademodule 
Maybe you could tell me how to use downgradeModule in the right way based on this project.

It works now. Thanks!

**Comment by gkalpak** [comment]
Basically, you cannot add dependencies to an AngularJS module in two places. There can only be one call like `angular.module('interestApp', [ /* all dependencies here */ ])`.

You can either do that by importing `downgradedModule` in `app.js` and adding it to `interestApp`'s dependency array (along with `ui-router` and all the other) or you can create and bootstrap another module that dependes on `interestApp` (plus the downgraded module), as shown in:

```ts
import './angularjs-app/app';
angular.module('ng-upgrade', [ 'old-angularjs-app', downgradedModule ]);
angular.bootstrap(document, ['ng-upgrade']);
```

**Comment by JoeyLi-1** [comment]
That is what I did. 

> import './relativepath/app.js';
> angular.module("nginterestApp", ['interestApp', downgradedModule]).directive("addPin", downgradeComponent({ component: AddPinComponent }));
> angular.bootstrap(document.body, ['nginterestApp']);

There is a typo in my previous comment, I had fixed it.
