### ISSUE TITLE
FeatureModule with imported RouterModule fails only during an AOT build

### ISSUE THREAD

**Issue by pixelbits-mk** [angular/angular#20858]
#I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The code fails to compile during an AOT build, but the non-AOT build works as expected.

This issue seems to occur when the RouterModule is imported from a FeatureModule, and the `AppModule` tries to call the static `FeatureModule.forRoot` method.

The issue has also been posted on [StackOverflow](https://stackoverflow.com/questions/47686638/featuremodule-with-encapsulated-routermodule-causes-an-error-in-an-aot-build).  

## Expected behavior

The AOT build should compile successfully without errors (just as the non-AOT build does).

## Minimal reproduction of the problem with instructions

**Steps to Reproduce**
1. Create a FeatureModule that imports the RouterModule
2. Implement a static `forRoot` method on the FeatureModule that returns `ModuleWithProviders`:

```
import {RouterModule, provideRoutes, Routes} from '@angular/router';

@NgModule({
    imports: [ RouterModule ],
    exports: [],
    declarations: [],
    providers: [],
})
export class FeatureModule {
    static forRoot():ModuleWithProviders {  
        return {
            ngModule: FeatureModule, 
            providers: []
        }
    }
 }
```

3. In the main AppModule, import the FeatureModule by calling the static `forRoot` method:

```
@NgModule({
  imports:      [  FeatureModule.forRoot()],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ],
  exports: [AppComponent]
})
export class AppModule {
}

```

4.  Build the application with @angular/cli:

`ng build --prod`

Notice the error: 

```
ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'FeatureModule' was called.
```

## What is the motivation / use case for changing the behavior?

**Context**

I would like to create a Modal Dialog component that uses RouterModule behind the scenes.   Users of the component should be unware how the modal dialog is being triggered (i.e. through routes). 

**Details**

The AppModule imports the FeatureModule, and passes in configuration data to the FeatureModule using the FeatureModule.forRoot(data) method.

**src\app\app.module.ts**

```
@NgModule({
  imports:      [ BrowserModule, FeatureModule.forRoot([...])],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ],
  exports: [AppComponent]
})
export class AppModule {
}
```
**src\feature\feature.module.ts**

```
import {RouterModule, provideRoutes, Routes} from '@angular/router';

@NgModule({
    imports: [ RouterModule.forRoot() ],
    exports: [WidgetComponent],
    declarations: [WidgetComponent],
    providers: [],
})
export class FeatureModule {
    static forRoot(data: any[]):ModuleWithProviders {    
        var routes = ... //transform data to routes;
        return {
            ngModule: FeatureModule, 
            providers: [provideRoutes(routes)]
        }
    }
 }
```

Within the FeatureModule the configuration data would be converted to routes and passed to the `provideRoutes()` method.  This would allow the user to configure the components that would show within the Modal Dialog.

**Error Information**

The error when compiling for AOT using `@ngtools/webpack` and the `AngularCompilerPlugin`:
```
ERROR in Error during template compile of 'RouterModule'
  Function calls are not supported in decorators in 'NgModule'
    'NgModule' calls a function at @angular\core\core.ts(194,50).
```
The error when compiling for AOT using `ng build --prod`:
```
ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'FeatureModule' was called.
```

Unfortunately, the error only occurs on an AOT build, so I cannot reproduce it in Plnkr. It seems the static `forRoot` function call inside the AppModule decorator may be partly to blame since removing the static function call results in a successful compilation. 

## Additional Info

- A non-AOT build works perfectly.  This is true for @angular/cli 1.5 or 1.6, and also for my own custom build which uses `@ngtools/webpack`.  The issue only occurs during an AOT build.
- Interestingly, calling `provideRoutes` and removing the static `forRoot` call  in the metadata attributes for AppModule compiles fine so this is a potential work-around: 

```
import { provideRoutes } from '@angular/router';

@NgModule({
  imports:      [ 
    BrowserModule, 
    FeatureModule
  ],
  declarations: [ AppComponent],
  bootstrap:    [ AppComponent ],
  providers: [provideRoutes([...])],
  exports: [AppComponent]
})
export class AppModule {
}

```
But this is not ideal because then AppModule has knowledge of routes, which is what I am trying to avoid. 

## Environment

<pre><code>
Angular version: 5.1.0

Browser: N/A (this is an AOT build issue)
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.0 
- Platform: Windows  

Others:

</code></pre>

**Comment by jasonaden** [comment]
@pixelbits-mk If you create a reproduction on [StackBlitz](https://stackblitz.com), we can download a CLI project from it and run that locally to verify.

But it sounds to me like you might just be missing `RouterModule` in your `exports` from the `FeatureModule`. If that doesn't fix your problem, please create a reproduction as above and create a new issue.

**Comment by Gary-Pan** [comment]
I got the same issue, here is the repo. (https://github.com/Gary-Pan/my-app)

**Comment by stephengardner** [comment]
@pixelbits-mk wondering if you ever solved this :/
