### ISSUE TITLE
Font color wrong in terminal snippets in docs

### ISSUE THREAD

**Issue by zvory** [angular/angular#20867]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The text in those black rectangles is black on black, and thus unreadable
![screen shot 2017-12-07 at 9 15 16 am](https://user-images.githubusercontent.com/4392164/33719610-49e96ec4-db2f-11e7-81cd-7f146bdeb493.png)

## Expected behavior

The text should not be blac

## Minimal reproduction of the problem with instructions
https://angular.io/guide/forms

## What is the motivation / use case for changing the behavior?
Being able to read text

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [X] Chrome (desktop) version Probably whatever's latest
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
Agree. That looks frustrating and reading the markup isn't very usable. 
Unfortunately, I can't reproduce this. Works for me on Chrome, FF, and Safari, both Windows and Mac. 

![image](https://user-images.githubusercontent.com/31675481/33743724-443aa3c6-db6b-11e7-884e-bf599711b2cf.png)


Still broken for you?

**Comment by gkalpak** [comment]
That issue has come up before. It seems like some styling issue (but not sure what is causing it). Usually gets away after a reload.

If this still happens to you, it would be interesting to see what the HTML for the code example looks like for you. E.g. if you right-click and inspect the code block, it should look something like:

```html
<code-example language="sh" class="code-shell" ng-version="5.0.0-rc.9">
  <aio-code class="simple-code">
    <pre class="prettyprint lang-sh">
      ...
      <code class="animated fadeIn">
        <span class="pln">ng new angular</span>
        <span class="pun">-</span>
        <span class="pln">forms</span>
      </code>
    </pre>
  </aio-code>
</code-example>
```

Also, what `color` styles apply to the `.pln` spans?

**Comment by zvory** [comment]
Still happening, even after closing tab and reopening. 

![screen shot 2017-12-08 at 10 30 21 am](https://user-images.githubusercontent.com/4392164/33772528-e620f5c2-dc02-11e7-8323-5662f3597c9a.png)
```html
<code-example language="sh" class="code-shell" ng-version="5.0.0-rc.9"><!----><aio-code class="simple-code"><pre class="prettyprint  language-sh">      <!----><button class="material-icons copy-button" title="Copy code snippet" aria-label="">
        <span aria-hidden="true">content_copy</span>
      </button>
      <code class="animated fadeIn language-sh">ng new angular-forms</code>
    </pre></aio-code></code-example>
```

**Comment by gkalpak** [comment]
It looks like something related to our [prettifier][1] is not working correctly.
Are you getting any errors in the console?
How do the `.js` files requests look on the `Network` tab in DevTools? This is what I am getting for example:

![js-files](https://user-images.githubusercontent.com/8604205/33831221-ddb9d29e-de7f-11e7-927e-c4780018874d.png)


[1]: https://github.com/google/code-prettify

**Comment by zvory** [comment]
I can no longer reproduce
