### ISSUE TITLE
Indentation broken in docs code snippets

### ISSUE THREAD

**Issue by zvory** [angular/angular#20868]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Code in the snippets does not have indentation and is hard to read. Happens a few times on this page
![screen shot 2017-12-07 at 9 17 48 am](https://user-images.githubusercontent.com/4392164/33719688-9449504c-db2f-11e7-9bf7-a4c145eca87b.png)

## Expected behavior

It's indented normally

## Minimal reproduction of the problem with instructions
https://angular.io/guide/forms#revise-appmodulets

## What is the motivation / use case for changing the behavior?
Text should be readable

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [X] Chrome (desktop) version probably latest chrome
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
Thank you for including the URL and a screen shot. Unfortunately, I'm not seeing what you see. 

Chrome current version on Windows: 
![image](https://user-images.githubusercontent.com/31675481/33743371-cab27f16-db69-11e7-9ba6-bd0c6be29f55.png)

Are you still seeing the problem?

**Comment by jenniferfell** [comment]
Also works for me on Windows Firefox and Mac Safari and Chrome. 
@zvory If you still are having a problem, we'll probably need to dig into browser versions. Thanks.

**Comment by zvory** [comment]
Chrome Version 62.0.3202.94 (Official Build) (64-bit) macOS High Sierrra
Still happens after refresh or restarting chrome (using cmd+q)

**Comment by gkalpak** [comment]
Are you getting any errors in the console?
What does the HTML for the code snippets look like?
Does it happen on that one specific snippet only?

**Comment by zvory** [comment]
I can no longer reproduce. It happened in some, but not all snippets. Perhaps 30% of snippets. I did not check any other pages in angular docs.

**Comment by gkalpak** [comment]
Thx for getting back. We have recently made some changes in how our code-example components (among others) get loaded and instantiated (which might or might not have improved things), so I don't think there is any point in trying to investigate what could have caused this with the previous implementation.

I am going to close this now, but please do open a new issue if you run into the same problem again.
