### ISSUE TITLE
Angular.io error in Chromium Version 64.0.3269.0

### ISSUE THREAD

**Issue by olivierscheffler** [angular/angular#20863]
When I try to open angular.io, it doesn't work because of an error in main.bundle : Uncaught SyntaxError: Unexpected end of input.

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The web site is responding but display a white page.

## Minimal reproduction of the problem with instructions
Download version Version 64.0.3269.0 of Chromium and try to open angular.io web site

## Environment

Browser:
- [X ] Chromium (desktop) Version 64.0.3269.0
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by gkalpak** [comment]
FWIW, I tried with 63.0.3239.84 and 65.0.3287.0 and it seems to work fine.
@olivierscheffler, does it only happen on that specific version of Chromium?
Does next.angular.io work?

**Comment by olivierscheffler** [comment]
Hi !
It happens on some version of Chromium 63 and 64..
I will try to upgrade to 65 to see what's happening..
I will try tomorrow next.angular.io..

**Comment by olivierscheffler** [comment]
Ok I upgrade on Version 65.0.3285.0 (Build de développement) (64 bits) it wasn't working but then I try to open next.angular.io and it worked and angular.io too.
I don't what happen..
I think it can be close actually.
Thank you !

**Comment by Chris-V** [comment]
I had the same error on angular.io, but next.angular.io worked perfectly.

fwiw, I had to manually unregister the service worker for angular.io in my dev tools to get it back up.

**Comment by gkalpak** [comment]
It sounds like a ServiceWorker issue. Not sure if it is `@angular/service-worker` or a Chrome issue, but we are soon switching to the new `@angular/service-worker@5` (see #19795) which is completely different than the current implementation, so there is little value in investigating further.

Nonetheless, let us know if this happens again and if you are getting any errors in DevTools.
Closing for now...
