### ISSUE TITLE
angulat2.x img tag src path load abnormal, how to display the default path

### ISSUE THREAD

**Issue by htm9527** [angular/angular#20861]
<img [src]="{{img_url || 'https://placehold.it/350x250&text=11'}}">
    
 
this.img_url =“xxxxx.png”; //The path exists, but this is a wrong path
 //The path exists but this is a wrong path, img does not load the default path. The default path will be displayed only if the img_url value is empty. How to make the path is wrong when loading the default path

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
