### ISSUE TITLE
Service worker: Unauthorised (401) when requesting ngsw.json - basic auth is not provided

### ISSUE THREAD

**Issue by areijngoudt** [angular/angular#20865]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
My webapp is available after a nginx proxy which is configured with basic authentication. However, @angular/service-worker does not provide the basic auth header when requestion the ngsw.json file, so a 401 is returned. Initializing the ServiceWorker fails becaus of that.

## Expected behavior
Provide the basic auth header of use 'same origin' in the fetch as is described in [https://stackoverflow.com/questions/37934972/serviceworker-conflict-with-http-basic-auth]

## Environment

<pre><code>
Angular version: 5.1.0

Browser:
- [ x] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.1
- Platform:  Mac

Others:

</code></pre>

**Comment by alxhub** [comment]
Hi @areijngoudt,

Websites that sit behind HTTP authentication (which requires cookies or an Authentication header to access resources) are not supported by Service Worker, sorry.

**Comment by NCC1701M** [comment]
@alxhub What's the reason for not supporting the http authentication?

**Comment by gline9** [comment]
I am also interested in the reason for not supporting http authentication. I tried using the edit you provided and it worked for me on windows using an nginx server. If there is no response from @alxhub soon I may try creating a pull request for the feature.

**Comment by NCC1701M** [comment]
@gline9,
Because there was no response from @alxhub I filed a new issue. When you do a pull request you can refer to the Bug #23425
