### ISSUE TITLE
Angular compiler-cli does not support typescript 2.5.x as advertised

### ISSUE THREAD

**Issue by dflor003** [angular/angular#20872]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The [blog post on the release of Angular 5.1](https://blog.angular.io/angular-5-1-more-now-available-27d372f5eb4e#481c) claims that Angular 5.1 has support for TypeScript@~2.5.x. However, when upgrading to TypeScript ~2.5.x and attempting to run a build, you receive the following error:

```
@angular/compiler-cli@5.1.0 requires typescript@'>=2.4.2 <2.5.0' but 2.5.3 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.4.2 <2.5.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".
```

## Expected behavior

Once we've upgraded all `@angular` scoped packages to `5.1.0` and ran `yarn add -D typescript@~2.5.x`, we should be able to build successfully without any warnings about TypeScript version mismatch.

## Minimal reproduction of the problem with instructions

**Note:** Using `yarn` in example, but should be the same with `npm`

1. Install `@angular/cli@1.6.0` globally.
2. Create a project in a directory: `ng new angularts-test`
3. Change directory into the project: `cd angularts-test`
4. Everything should be on angular `5.0.0`, upgrade to `5.1.0` by running:
```
yarn add  @angular/{animations,common,compiler,core,forms,http,platform-browser,platform-browser-dynamic,router}@5.1.0
```
5. Upgrade TypeScript to 2.5.x: `yarn add -D typescript@~2.5.x`
6. Run a build: `yarn run build`

**Expected:**
Build succeeds with no warnings.

**Actual:**
Build gives the following warning:

```
@angular/compiler-cli@5.1.0 requires typescript@'>=2.4.2 <2.5.0' but 2.5.3 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.4.2 <2.5.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".
```

## What is the motivation / use case for changing the behavior?

The blogpost claims that `typescript@~2.5.x` is officially supported, so the CLI should not be issuing warnings when on `typescript@~2.5.x`.

## Environment

<pre><code>
Angular version: 5.1.0

For Tooling issues:
- Node version: 6.12.0
- Platform: Mac
</code></pre>

**Comment by jasonaden** [comment]
@dflor003 Sounds like you have an installation that's incorrect. The peer dependency on `5.1.0` is `"typescript": ">=2.4.2 <2.6"`. Please provide a reproduction of your issue as a fresh install doesn't create this problem.

**Comment by dflor003** [comment]
@jasonaden: Try the reproduction steps I've posted. It seems to be pretty consistent when using a fresh `ng new <app>`. Actually, after looking on the angular/cli repo, it seems like they have a known issue for this: https://github.com/angular/angular-cli/issues/8768.

Looks like there is a pending PR to fix this as well.

**Comment by mmc41** [comment]
I get the same warning after upgrading to angular 5.1 using a fresh install

**Comment by jasonaden** [comment]
Okay, closing this issue as it's a CLI bug as listed above.
