### ISSUE TITLE
Resurrect OnChange

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#2087]
It is required for Dart. It has to compile to:

```dart
abstract class OnChange {
  void onChange(changes);
}
```

**Comment by tbosch** [comment]
Please also add interfaces for the other lifecycle callbacks:

- `onDestroy` (https://github.com/angular/angular/blob/master/modules/angular2/src/core/annotations_impl/annotations.ts#L1071)
- `onChange` (https://github.com/angular/angular/blob/master/modules/angular2/src/core/annotations_impl/annotations.ts#L1109)
- `onAllChangesDone` (https://github.com/angular/angular/blob/master/modules/angular2/src/core/annotations_impl/annotations.ts#L1130)

**Comment by tbosch** [comment]
Right now this is actually not required by Angular, as we either call the method via reflection or from a generated change detector. Maybe we should change this to cast the directive instance to one of these interfaces and then call the method directly in any case.

**Comment by naomiblack** [comment]
I think this issue needs more discussion with the core team before we implement.

**Comment by yjbanov** [comment]
Before we discuss it let's first restore it. It was part of the public API and people already use it. I'm pretty certain we'll need it anyway. The current `lifecycle` annotation should be limited to JS (because it doesn't reify interfaces). In Dart, interfaces are reified and therefore:

* `lifecycle` annotation is not necessary
* interfaces give the compiler feedback to remove dynamic call sites

**Comment by naomiblack** [comment]
Please wait before merging this into master so we can chat with @mhevery next week. Unless this is P0, let's not rush into the change.

**Comment by yjbanov** [comment]
Can't wait. What's your worry?

**Comment by yjbanov** [comment]
Fixed by #2121
