### ISSUE TITLE
Service Worker should check for updates on every navigation

### ISSUE THREAD

**Issue by alxhub** [angular/angular#20877]
Currently the SW checks for updates on cold starts. Cold starts are unpredictable. This technique is generally fine in production but makes it hard for developers to verify the update process.

The SW should instead always fetch `ngsw.json` on navigation.

**Comment by gkalpak** [comment]
But you can manually check for updates with `SwUpdate`, right?
At least I would make it configurable (e.g. when importing the `ServiceWorkerModule`. Some strategies could be:

- Check on cold starts.
- Check on navigation.
- Check every X amount of time.

**Comment by webmaxru** [comment]
What I've found - it's enough to just subscribe to updates to trigger the update check w/o need for the SW cold start (as well as there is no need to use `checkForUpdate()` explicitly):

```
 this.swUpdate.available.subscribe(event => {
     //no-op
 });
```

**Comment by alxhub** [comment]
@webmaxru do you have a stable reproduction of that? Subscribing alone sends no messages to the SW and shouldn't affect behavior in any way...

**Comment by webmaxru** [comment]
@alxhub I can't reproduce it precisely anymore. Maybe it was a combo of normal VS incognito mode and existing VS new tabs. I'll continue exploring during this weekend
