### ISSUE TITLE
upgrade angular version from 2.1.0 to 5.0.0

### ISSUE THREAD

**Issue by rsavaniucla** [angular/angular#20873]
`I am trying to upgrade angular version from 2.1.0 to 5.0.0

I copied **package.json** from **angular.io**

    {
      "name": "angular-quickstart",
      "version": "1.0.0",
      "private": true,
      "description": "Example project from an angular.io guide.",
      "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "test": "ng test",
        "lint": "tslint ./src/**/*.ts -t verbose",
        "e2e": "ng e2e"
      },
      "keywords": [],
      "author": "",
      "license": "MIT",
      "dependencies": {
        "@angular/animations": "~5.0.0",
        "@angular/common": "~5.0.0",
        "@angular/compiler": "~5.0.0",
        "@angular/compiler-cli": "~5.0.0",
        "@angular/core": "~5.0.0",
        "@angular/forms": "~5.0.0",
        "@angular/http": "~5.0.0",
        "@angular/platform-browser": "~5.0.0",
        "@angular/platform-browser-dynamic": "~5.0.0",
        "@angular/platform-server": "~5.0.0",
        "@angular/router": "~5.0.0",
        "@angular/upgrade": "~5.0.0",
        "angular-in-memory-web-api": "~0.5.0",
        "devextreme": "^17.2.3",
        "devextreme-angular": "^17.2.3",
        "core-js": "^2.4.1",
        "rxjs": "^5.5.0",
        "web-animations-js": "^2.3.1",
        "zone.js": "^0.8.4"
      },
      "devDependencies": {
        "@angular/cli": "1.5.0",
        "@types/jasmine": "~2.5.53",
        "@types/jasminewd2": "^2.0.3",
        "@types/node": "^6.0.45",
        "jasmine": "~2.4.1",
        "jasmine-core": "~2.4.1",
        "karma": "^1.3.0",
        "karma-chrome-launcher": "^2.0.0",
        "karma-cli": "^1.0.1",
        "karma-jasmine": "^1.0.2",
        "karma-jasmine-html-reporter": "^0.2.2",
        "karma-phantomjs-launcher": "^1.0.2",
        "lodash": "^4.16.2",
        "phantomjs-prebuilt": "^2.1.7",
        "protractor": "~5.1.0",
        "ts-node": "^3.3.0",
        "tslint": "^3.15.1",
        "typescript": "~2.4.2"
      },
      "repository": {}
    }

But i am getting error in internal files of angular 5

> @angular\common\src\directives\ng_for_of.d.ts(18,14): error TS1005:
> Build:'=' expected.<br/>
> @angular\compiler\src\metadata_resolver.d.ts(80,5): error TS1128:
> Build:Declaration or statement expected.<br/>
> rxjs\operator\bufferTime.d.ts(3,74): error TS1005: Build:';'
> expected.<br/>`

I am getting error wherever readonly keyword in internal files.

I am getting error in all **.d.ts files. How to exclude from compile.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

I recommend you to use the CLI, it will save you all the pain.

**Comment by vicb** [comment]
Closing:
- The template is not filled out !
- Sounds like a support request (as stated by @ericmartinezr )
