### ISSUE TITLE
Get error "Expression has changed after it was checked"

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular#20886]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have a component with two options. For one I use ndModel directive and for the other option I, use binding with control pristine. When I change the value of an option with another element on the page, I get an error:
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.

## Expected behavior

Changing the value must be done without error

## Minimal reproduction of the problem with instructions

You can see my [example](https://github.com/dxvladislavvolkov/textbox_example)
Сhange the value in the second input and see the console.

## Environment

<pre><code>
Angular version: 5.1.0

**Comment by mlc-mlapis** [comment]
@dxvladislavvolkov ... did you read https://blog.angularindepth.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4 ?

And also, make a plunker or a Stackblitz simple demo, ... it is simply not realistic that anybody will take your repo locally, ... to try or show what is wrong, ...

**Comment by dxvladislavvolkov** [comment]
You can see an example in the [planker](http://plnkr.co/edit/YDoo8uKXSu6Rtx1BlCPJ?p=preview).
It seems that the problem is that the value of pristine is changing too late. Although the changes occur at the stage of writeValue

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mlc-mlapis** [comment]
@dxvladislavvolkov ... There are problems with `TextBoxModule` and `TextBoxComponent` in your plunker. You can't declare the same component in 2 modules.

From your code is also not clear what you are trying to do. For example why you don't use a validator and use `[isValid]="emailControl.pristine"` on input instead?

**Comment by dxvladislavvolkov** [comment]
@mlc-mlapis I use thу isValid for further processing in my component. In this example, I presented the simplest implementation.
