### ISSUE TITLE
FeatureModule with imported RouterModule fails only during an AOT build

### ISSUE THREAD

**Issue by pixelbits-mk** [angular/angular#20883]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I've created a FeatureModule that imports RouterModule and implements a static `forRoot` method.
If AppModule imports FeatureModule via the FeatureModule.forRoot() method, the code fails to compile during an AOT build.  It builds successfully for non-AOT builds.

    `ng build`  // SUCCESSFUL
    `ng build --prod` // ERROR

The error is:
```
ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'FeatureModule' was called.
src/app/app.module.ts(4,10): error TS2305: Module '"C:/projects/app5/src/feature/feature.module"' has no exported member 'FeatureModule'.
```

**feature.module.ts**

```
import { NgModule } from "@angular/core";
import { RouterModule } from '@angular/router';
import { BrowserModule } from "@angular/platform-browser";

@NgModule({
    declarations: [

    ],
    imports: [
        BrowserModule,
        RouterModule.forRoot([])    
    ],
    providers: []
  })
  export class AppModule { }
  
```

**app.module.ts**

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import { FeatureModule } from '../feature/feature.module';


@NgModule({
  declarations: [
    AppComponent,
    FeatureModule.forRoot()
  ],
  imports: [
    BrowserModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

## Expected behavior

The AOT build should succeed.

## Minimal reproduction of the problem with instructions

1.  git clone https://github.com/pixelbits-mk/aot-build-issue.git
2.  cd aot-build-issue
3.  npm install
4.  ng build --prod
5.  observe the compilation error: 
```
ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'FeatureModule' was called.
src/app/app.module.ts(4,10): error TS2305: Module '"C:/projects/app5/src/feature/feature.module"' has no exported member 'FeatureModule'.
```

## What is the motivation / use case for changing the behavior?

The code should compile.  For more context refer to #20858 .

## Environment

<pre><code>
Angular version: 5.1.0 (latest version)

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.0
- Platform:  Windows

Others:

</code></pre>

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by pixelbits-mk** [comment]
Why is this not a bug? I've provided an example to reproduce the issue.
