### ISSUE TITLE
Get Http Headers from base URL not from an http call

### ISSUE THREAD

**Issue by FARHANE** [angular/angular#20887]
## I'm submitting a...

<pre><code>
[ ] Regression
[ ] Bug report 
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior
I' am working with a Secure Access Manager, you must enter this tool and click the name of the application name and he will redirect you to your application and adding some informations (username) to your base url header.

## Expected behavior
How can I intercept this call and get the username from the base url (htt://example.com/myAngularApp);

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
