### ISSUE TITLE
InMemoryDbService can not add new item when collection is empty, 

### ISSUE THREAD

**Issue by sculxp** [angular/angular#20885]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

InMemoryDbService: can not add new item when collection is empty, Error ("id type is non-numeric or unknown. Can only generate numeric ids." ) is rasied.

## Expected behavior

can add new item when collection is empty! 

## What is the motivation / use case for changing the behavior?

If id type is numeric, then custom id generation strategy will be provided, if not,  you  can not add new item when collection is empty, Maybe it's better to assume id type is numeric when collection is empty.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
Can you please open an issue on https://github.com/angular/in-memory-web-api?
Once it is fixed there, we can update to the latest version.
<sub>Closing for now, since there is not much we can do atm.</sub>

**Comment by sculxp** [comment]
Sorry，I am new to Angular。
