### ISSUE TITLE
Make it easier to safely uninstall Service Worker

### ISSUE THREAD

**Issue by alxhub** [angular/angular#20899]
Removing a Service Worker can be a dangerous operation. Simply publishing a new version of the app where the SW script isn't registered and doesn't exist does not remove existing instances of the SW installed in users' browsers, and the nature of Service Workers is for them to continue serving a cached `index.html`, and never noticing that the registration code has been removed. In fact, they will not continue to update at all.

This also affects sites which want to rename their service worker script. Unless care is taken to update the cache of the _old_ service worker, clients which have it installed will stop receiving updates, and will never notice the new one or any new content for the site.

This is a very dangerous situation. It's mitigated somewhat by the design of `@angular/service-worker >5.0.0`, which will self-destruct if it ever receives an error from the server attempting to fetch `ngsw.json`.

`@angular/service-worker` should be checked to make sure it's safe with respect to this issue (deactivating SW in a build should result in the SW eventually unregistering itself).

Additionally, we should provide a script which can be provided when upgrading from the beta version of `@angular/service-worker`.

**Comment by mackelito** [comment]
@alxhub why was this closed? just being curious :)

**Comment by gkalpak** [comment]
I guess because it has been taken care of. See [ServiceWorker safety][1].

[1]: https://angular.io/guide/service-worker-devops#service-worker-safety

**Comment by mackelito** [comment]
Perhaps I misunderstood but I was expecting possibility to delete the service worker without having to  remove or rename the ngsw-config.json file...

As I understand it we could delete the service worker by doing something like:

```
if ('serviceWorker' in navigator) {
      navigator.serviceWorker.getRegistrations().then(function (registrations) {
        for (const registration of registrations) {
          // unregister service worker
          console.log('serviceWorker unregistered');
          registration.unregister();
        }
      });
    }
```

This will delete the service worker and then we could reinitiate it if needed.. or perhaps I'm totally wrong here? :D

**Comment by choopage** [comment]
@webmaxru How to use Angular's safety-worker.js to uninstall Service Worker? 
https://stackoverflow.com/q/57629541/3073280

**Comment by webmaxru** [comment]
@choopage You just have to rename `safety-worker.js` to `ngsw-worker.js` on the production and keep it there for a while (say, until the majority of the app users get this update)
