### ISSUE TITLE
Show clearer error message for "EmptyError: no elements in sequence"

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#20898]
Often this error message means the routerLink that was clicked is heading to an invalid route path. It would be great to show a clearer error message that lists the most likely possibilities.

```
ERROR Error: Uncaught (in promise): EmptyError: no elements in sequence
EmptyError: no elements in sequence
```

**Comment by jasonaden** [comment]
Sounds good @johnpapa. Could you make a simple repro on [StackBlitz](http://stackblitz.com)?

**Comment by johnpapa** [comment]
seems it is an rxjs thing https://stackoverflow.com/questions/41131476/emptyerror-no-elements-in-sequence

**Comment by jasonaden** [comment]
Thanks. Closing this issue based on that comment.
