### ISSUE TITLE
SVG/ngClass/mat-tab?/URL issue 

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angular#20907]
## I'm submitting a...
[ x] Bug report
I don't know on which level the bug is: mat-tab, angular, chrome...
Just tried it on FF and edge and there I don't have the issue...

## Current behavior
Using the fill: url(#start-end-selected-gradient); css as I've done here:
https://stackblitz.com/edit/angular-svg-url-issue?file=app%2Ftabs-template-label-example.css
gives an issue.
When going from tab to tab **sometimes** the drawn ellipse will 'disappear'. I have it a lot when going from tab 1 to tab 2. Sometimes when going to tab 4. It seems to occur more when you go from a previous to a next tab.

## Expected behavior
self-explanatory I suppose :-). It shouldn't disappear.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-svg-url-issue?file=app%2Ftabs-template-label-example.css

**Comment by jasonaden** [comment]
Added repro steps:

* Go from a tab with the circle to a later tab with the circle
* Wait for animation to finish
* Circle will disappear

Ex (broken): 
  Tab 1 -> Tab 2
  Tab 2 -> Tab 4

Ex (working):
  Tab 3 -> Tab 2
  Tab 3 -> Tab 4
  Tab 4 -> Tab 2

**Comment by pkozlowski-opensource** [comment]
I believe that it should be first investigate in https://github.com/angular/material2 - could you please re-open in-there?
