### ISSUE TITLE
[compiler-cli] export `createEmitCallback` thru public api

### ISSUE THREAD

**Issue by dherges** [angular/angular#20906]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`createEmitCallback(): api.TsEmitCallback` [is internal only](https://github.com/angular/angular/blob/24bf3e2a251634811096b939e61d63297934579e/packages/compiler-cli/src/main.ts#L36-L38).

## Expected behavior

Either:
- export `createEmitCallback()` in public api
- or: move initialization of tsickle's emit callback to `performCompilation()`

```ts
import * as ngc from '@angular/compiler-cli';

// A: make public API
const emitCallback = ngc.createEmitCallback(/*..*/);
ng.performCompilation({..., emitCallback });

// B: performing compilation with `annotateForClosureCompiler: true` should
// auto-create emit callback
ngc.performCompilation({..., options: { ..., annotateForClosureCompiler: true }});
```

## Minimal reproduction of the problem with instructions

Call `performCompilation()` with `annotateForClosureCompiler: true`. No source rewrite.

```ts
ngc.performCompilation({..., options: { ..., annotateForClosureCompiler: true }});
```

## What is the motivation / use case for changing the behavior?

programmatic usage of ngc, e.g. passing a custom compiler host to `performCompilation()`,
 see [example](https://github.com/dherges/ng-packagr/blob/master/src/lib/steps/ngc.ts#L219-L226)

## Environment

<pre><code>
Angular version: 5.1.x
</code></pre>

**Comment by alxhub** [comment]
The fact that Angular's compiler API is private is a deliberate decision - we have no plans to expose any part of it as public at this time.
