### ISSUE TITLE
Compilation problem with APP_INITIALIZER when <strictMetadataEmit=true> is used

### ISSUE THREAD

**Issue by mlc-mlapis** [angular/angular#20903]
<pre><code>[x] Documentation issue or request</code></pre>

## Current behavior
@chuckjaz There is a problem with `APP_INITIALIZER` and an exported function for a related provider where without `// @dynamic` on `@NgModule` it is not possible to compile (ngc) when `strictMetadataEmit=true`.

When `// @dynamic` not set ... the error message *Metadata collected contains an error that will be reported at runtime: Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function. {"__symbolic": "error","message": "Function call not supported", ...}* appears with setting `strictMetadataEmit=true`.

This is not document in any place. It should be documented somehow on http://angular.io I think.

The following code for APP_INITIALIZER is correct and the only way how to write the code (Angular 5.1.0).
```
export function appConfigServiceFactory (config: AppConfig): () => void {
	return () => config.load().then(...);
}
// @dynamic
@NgModule({
	...,
	providers: [
		AppConfig,
		{
			provide: APP_INITIALIZER,
			useFactory: appConfigServiceFactory,
			deps: [AppConfig],
			multi: true
		}
	],
	...
})
export class AppModule {...}
```

## Expected behavior
It should be documented at least. Also there is a question if it is the intended behavior that could not be improved.

## Environment
<pre><code>Angular version: 5.1.0
Browser: any
</code></pre>

**Comment by chuckjaz** [comment]
I agree we should document `@dynamic` and how it should be used. It is intended to mark functions or variables that are not intended to be used in decorators and for which an error is expected. Decorators are unaffected as you discovered.

We should also be more clear on when to use `strictMetadataEmit`. 

`strictMetadataEmit` should only be `true` when `skipTemplateCodegen` is `true`. It is intended to provide some validation of metadata when template code generation is disabled.

The fact that `strictMetadataEmit` reports the above is expected. `strictMetadataEmit` should never be used when compiling an application as it provides no value, is overly strict, and template compiler is already validating the metadata it uses.

**Comment by sarbull** [comment]
ffs. thank you.

**Comment by jenniferfell** [comment]
Closing as resolved. It looks like this was addressed when we documented the compiler options earlier this year: https://angular.io/guide/aot-compiler#strictmetadataemit

If this does not resolve the issue, please let us know by opening a new issue.

Thank you!
