### ISSUE TITLE
Class updates via hostProperties not synchronous

### ISSUE THREAD

**Issue by dylanb** [angular/angular#2090]
Take a look at this Plunker

http://plnkr.co/edit/x7kbzMSe6Mr0qEoLyHr8?p=preview

If you uncomment the `setTimeout` call, then the button will turn blue when the app initializes but when the focus call is done immediately after the class update (which makes the button visible and therefore focusable) the button cannot receive focus because its class has not yet been updated and the button therefore does not turn blue.

You could also add the following log immediately after the call to set `this.show = true;` and you will see that the class is still not set immediately `console.log(el.domElement.classList.contains('show'));` but making that same call inside the timeout callback will print `true`.

**Comment by mhevery** [comment]
it is impossible to detect class changes synchronously in JS. 
This is working as designed. 

I realize it is surprising behavior, but it is just not possible to do what you are asking.
