### ISSUE TITLE
AnimationBuilder: few animations in same component

### ISSUE THREAD

**Issue by nop1984** [angular/angular#20918]
Hi. 
For example i have a component those template include 2 divs.
And I want to animate each div seperatly with AnimationBuilder.

But if I animate next div, results of previous animation vanish. I tried to use 2 different instances of AnimationBuilder but result is same.

AngularJS 5.1, Chrome

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by nop1984** [comment]
@ericmartinezr thanks for paying attention to my question.
I have created empty new project to test, and I got wished result somehow ... must read out my project better tomorow.
Below is the code on clean special created for test component and animation of one div does not reset animated results of previously animated div

```
import { Component, OnInit, ViewChild} from '@angular/core';
import {AnimationBuilder, AnimationPlayer, AnimationFactory} from "@angular/animations";
import {ElementRef} from '@angular/core';
import {trigger, state, style, transition, animate} from '@angular/animations';

@Component({
  selector: 'app-testcomp',
  template: `<div #divone class='div1' (click)="div1click($event)">DIV 1</div>
  <div #divtwo class='div2' (click)="div2click($event)">DIV 2</div>
  `,
  styleUrls: ['./testcomp.component.scss'],
  styles: ['.div1 {background-color: yellow; width: 200px; height:200px};', '.div2 {background-color: blue; width: 200px; height:200px};']
})
export class TestcompComponent implements OnInit {
    
  @ViewChild('divone') div1:ElementRef;
  
  @ViewChild('divtwo') div2:ElementRef;
    
  //div1: HTMLDivElement;
  //div2: HTMLDivElement;

  constructor(private _builder: AnimationBuilder, private _builder2: AnimationBuilder) { }

  ngOnInit() {
  }
  
  ngAfterViewInit() {
      //this.div1 = this.domHandler.find(this.containerViewChild.nativeElement.parentElement, '.sidebar-ex-workarea-wrapper')[0];

  }
  
  
  div1click(event: Event) {
    const myAnimation = this._builder.build([ style({ transform: 'rotate(0deg)' }), animate(1000, style({ transform: 'rotate(30deg)' }))]);
 
    // then create a player from it
    const player = myAnimation.create(this.div1.nativeElement);
 
    player.play();
    
  }
  
  div2click(event: Event) {
    const myAnimation = this._builder.build([ style({ transform: 'rotate(0deg)' }), animate(1000, style({ transform: 'rotate(45deg)' }))]);
 
    // then create a player from it
    const player = myAnimation.create(this.div2.nativeElement);
 
    player.play();
  }

}

```

**Comment by nop1984** [comment]
@ericmartinezr false alarm, guys. sorry.
My problem was that I used one and same var-component member for player instance for both animations. So when this.player was reassigned it "killed" results of previous animation (in example above i used const insted of this.player var and all is okay now)

**Comment by jotatoledo** [comment]
Close the issue

**Comment by nop1984** [comment]
closing this
