### ISSUE TITLE
Animations: stagger

### ISSUE THREAD

**Issue by dblVs** [angular/angular#20911]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## What is the motivation / use case for changing the behavior?
Hey, As a user of the framework I would like to be able to use stagger within certain time rather than certain offset, because when animating large amount of data (10 items for example), it would take long for them to animate.
I think this would bring nice addition to the animations and would make animating letters, buttons for instance a breeze. Imagine if you have to animate 'Hong Kong Phooey' with current stagger with about 200 offset it would take 200ms * 16 + animation time, but then you animate 'matsko' it would take only 200ms * 6 + animation time. With this change i would be able to animate both things over let's say 1s where 'Hong Kong Phooey' would have 1000/16 ms offset on each letter and matsko would have  1000/6 ms offset on each letter.

P.s. keep up the work on the awesome framework you are creating.

@matsko

**Comment by matsko** [comment]
@dblVs this is just around the corner actually:

https://github.com/angular/angular/issues/20812

You would need to create the diminishing timing arc yourself, but it's doable via a custom stagger handler.

**Comment by dblVs** [comment]
@matsko great. would you like me to close the issue ? p.s All i'll have to use will be 
```
function overTime(duration: number) {
  return (entries: {element, styles}[], params: {[key: string]: any}): number[] => {
    let stagger = duration / entries.length; 
    return entries.map((entry, index) => {
      return stagger * index;
    });
  }
}

query(':enter', [
  stagger(overTime(1000), [ ... ])
])```
