### ISSUE TITLE
Proxy: Local virtual host names are all resolved to localhost.

### ISSUE THREAD

**Issue by PMacho** [angular/angular#20910]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

http.get() doesn't find the backend file.
 
## Expected behavior

Fetching data from backend. 

## Minimal reproduction of the problem with instructions

I created a local virtual host with xampp at http://mysite.local:8080. 
I have a  proxy.conf.json:
{
  "/api": {
    "target": "http://mysite.local:8080",
    "secure": false,
    "logLevel": "debug",
    "pathRewrite": {
      "^/api": ""
    }
  }
}

and changed the changed the start line in package.json to:
"start": "ng serve --proxy-config proxy.conf.json",

On `npm start` i get messages like:
[HPM] Rewriting path from "/api/src/main/package/Entries/testservice/testentry.php" to "/src/main/package/Entries/testservice/testentry.php"
[HPM] GET /api/src/main/package/Entries/testservice/testentry.php ~> http://mysite.local:8080

However, instead of mysite.local:8080 Angular attempts to fetch data from localhost:8080. 

I think the problem is related to webpack: https://webpack.github.io/docs/webpack-dev-server.html#proxying-local-virtual-hosts
I just don't know where to make the according changes in Angular.

## Environment

<pre><code>
Angular version: X.Y.Z

Angular CLI: 1.5.4
Node: 6.12.0
OS: darwin x64
Angular: 
...

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
node v6.12.0
npm  v5.5.1
- Platform:  
Mac OS 10.11.6

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
This issue belongs to https://github.com/angular/angular-cli, please re-open there.
