### ISSUE TITLE
router.navigate doesn't remove previous component

### ISSUE THREAD

**Issue by GenaANTG** [angular/angular#20915]
After programmatically invoke method router.navigate he doesn't remove previous component and at the same page stay two components after navigate.

Version of Angular: 5.1.0

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

**Comment by GenaANTG** [comment]
No problem, Thanks! I need to check again. We have many projects and only one project have this problem.

**Comment by MarkusLuttrell** [comment]
Gena, when will а new video?)

**Comment by GenaANTG** [comment]
@MarkusLuttrell Haha)) very soon) We need to end the project)

**Comment by calamarico** [comment]
@GenaANTG I have the same problem I think, when I have a route loaded that has a data param, for example:
```
const routes: Routes = [
  {
    path: '',
    component: ApisComponent,
    data: {
      breadcrumbs: 'APIs',
    },
    children: [
      {
        path: '',
        component: ApiListComponent,
      },
      {
        path: ':id',
        component: ApiDetailComponent,
        resolve: {
          api: ApiResolverService
        },
        data: {
          breadcrumbs: '{{ api.title }}',
        },
      },
    ],
  },
];
```
This route is loaded after navigation in /api. I have a handle error to navigates to a custom error page, when I'm in /api and exception is throwed, due to this code:

```
import { ErrorHandler, Injectable, Injector } from '@angular/core';
import { Router } from '@angular/router';

@Injectable()
export class AppErrorHandler implements ErrorHandler {

  constructor(private injector: Injector) { }

  handleError(error: any): void {
    const routerService = this.injector.get(Router);
    routerService.navigateByUrl('/error', { skipLocationChange: true } );
  }
}
```
Router navigates to another url (the skipLocationChange here is trivial, if it's false, the result is the same) and the thing is I can see my breadcrumb (loaded with data param in the previous router), and my generic error page. So I think I have the ActivatedRoute with old data.

**Comment by GenaANTG** [comment]
I think it's a bug. It's not problem with the data param. We are using same navigation method. But i don't use data param. Probably problem is with the method `scheduleNavigation` in router package: https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L452,
at this line method has timeout: https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L315
Maybe `scheduleNavigation` need a delay for components view state change or something like that.

**Comment by calamarico** [comment]
@GenaANTG Sounds logical, in your projects you haven't resolved yet the problem right? Or maybe you tried another way to do that?

**Comment by GenaANTG** [comment]
Not yet, but i need some time for testing. Then i'll posting here reproduction of the bug.

**Comment by calamarico** [comment]
Ok, I'm working on it too, also I have asked a question on stackoverflow: https://stackoverflow.com/questions/48325743/route-with-old-data-when-navigates-in-angular 

Hope we can share solutions soon!

**Comment by calamarico** [comment]
@GenaANTG in a very lucky moment I'm find the solution. The problem as you said it's not about data. The problem is that the router it's not firing correctly the next routing due to missunderstanding about 'parent' and 'children'.

As I showed I have a sub module to manage /apis routing, and of course I manage in app-routing.module the "forRoot" routings, and the solution is very very simple, I haven't imported in the apis-.module the BrowserModule, so...  when I did:

```
@NgModule({
  imports: [
    CommonModule,
    ApisRoutingModule,
    SharedModule,
    BrowserModule,
]
```
Problem solved for me! I hope it will help to you

**Comment by calamarico** [comment]
@GenaANTG forget about the import of BrowserModule, I was wrong, not resolve the problem...

**Comment by GenaANTG** [comment]
@calamarico Yep! I think it's a problem with delay.

**Comment by calamarico** [comment]
@GenaANTG Hi, I have tested with angular 5.2.9 and the problem still happens, do you have any advance in your side?

**Comment by calamarico** [comment]
@GenaANTG I have solved my problem, I added an answer on my stackoverflow question, hope it helps you: https://stackoverflow.com/questions/48325743/routing-child-to-parent-is-not-working-when-navigates-in-angular

**Comment by reza3zar** [comment]
@GenaANTG thanks a lot.
it works to me

**Comment by nethulap** [comment]
@GenaANTG  I have tested this in angular 5.2.9 and it the problem is still there. Thanks for your solution.
Hoping this would be properly fixed in next version of angular.

**Comment by hari1928** [comment]
this.router.navigate(['/login']);

  It will automatically remove previews component of url
