### ISSUE TITLE
$event is coming undefined in controller

### ISSUE THREAD

**Issue by nasif** [angular/angular#20923]
I have an input type with ng-change and ng-keyup events in my view, both events calling same callback

**view**
`
<input type="Number"  ng-keyup="calculateRent($event)" ng-change="calculateRent($event)">
`

**controller**

`
   $scope.calculateRent = function(event){

 }
`
when i am triggering ng-change "event" event argument in contoller is coming undefined but working fine in ng-keyup

**Comment by pkozlowski-opensource** [comment]
Wrong repo, I guess you've meant to open it in https://github.com/angular/angular.js
