### ISSUE TITLE
Unable to validate form on submit

### ISSUE THREAD

**Issue by kshkrao3** [angular/angular#20929]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The ```form``` will validate on ```submit``` if left blank, but even after filling the value when I check ```this.testform.valid``` it returns ```false```. But if I remove ```updateOn:'submit'``` on form then it validates on blur of input control and when value is entered it validates form return ```true```.

## Expected behavior

Form should revalidate on `submit` and check if controls are valid.

## Minimal reproduction of the problem with instructions

**component.html**
```
<form class="example-form" novalidate (ngSubmit)="onSubmit()" autocomplete="off" [formGroup]="testform">
     <input type="text" formControlName="name" class="form-control" placeholder="Enter name" required/>
     <app-show-errors [control]="claimform.controls.name"></app-show-errors>
     <button type="submit" (click)="onSubmit()">Next</button>
</form>
```

**component.ts**

```
ngOnInit() {
    this.testform= new FormGroup({
      name: new FormControl('', { validators: Validators.required})
    }, {updateOn: 'submit'});
}

onSubmit() {
    if (this.testform.valid) {
      alert('saving data');
    } else {
      this._validationService.validateAllFormFields(this.testform);
    }
}
```

**service.ts**

```
validateAllFormFields(formGroup: FormGroup) {
    Object.keys(formGroup.controls).forEach(field => {
      const control = formGroup.get(field);
      if (control instanceof FormControl) {
        control.markAsTouched({ onlySelf: true });
      } else if (control instanceof FormGroup) {
        this.validateAllFormFields(control);
      }
    });
}
```

## What is the motivation / use case for changing the behavior?
Client requirement

## Environment

<pre><code>
Angular version: 5
Angular CLI - 1.5.4

Browser:
All browsers
 
For Tooling issues:
- Node version: 8.9.1
- Platform:  Win32 x64

Others:

</code></pre>

**Comment by lazyspark** [comment]
I created a stackblitz. It should work fine - [Stackblitz](https://stackblitz.com/edit/angular-gk121z?file=app%2Fapp.component.ts)
Please modify the link to match your expectations. Seems more like stackoverflow question to me.

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

See the repro @lazyspark created and if you think there's still an actual bug, please create a similar repro showing the bug and submit a new issue.
