### ISSUE TITLE
n level search and filter in Angular 2 tree collection

### ISSUE THREAD

**Issue by girishmahida** [angular/angular#20926]
I am receiving data in below format tree collection. I want to filter this collection at all level and return the collection upto its main parent level.
<pre><code>
{
            "id": "1",
            "name": "Asia",
            "type": "Geography",
            "children":[
                {
                    "id":"C1",
                    "name":"China",,
                    "type":"Country"
                    "children":[
                        {
                            "id":"S1",
                            "name":"Sichuan",
                            "type":"States",
                            "children":[
                            {
                                "id":"C1",
                                "name":"Leshan",
                                "type":"City",
                                "children":[]
                            },
                            {
                                "id":"C2",
                                "name":"Deyang",
                                "type":"City",
                                "children":[]
                            },
                            {
                                "id":"C3",
                                "name":"Yibin",
                                "type":"City",
                                "children":[]
                            }
                            ]
                        },
                        {
                            "id":"S2",
                            "name":"Hainan",
                            "type":"States",
                            "children":[
                            {
                                "id":"C4",
                                "name":"Leshan",
                                "type":"City",
                                "children":[]
                            },
                            {
                                "id":"C5",
                                "name":"Deyang",
                                "type":"City",
                                "children":[]
                            }
                            ]
                        },
                        ],
                },
                ],    
                }
            ],

    },
    {
            "id": "2",
            "name": "Europe",
            "type": "Geography",
            "children":[
                {
                    "id":"E1",
                    "name":"Germany",,
                    "type":"Country"
                    "children":[
                        {
                            "id":"U1",
                            "name":"Berlin",
                            "type":"States",
                            "children":[
                            {
                                "id":"UC1",
                                "name":"Coburg",
                                "type":"City",
                                "children":[]
                            },
                            {
                                "id":"UC2",
                                "name":"Cologne",
                                "type":"City",
                                "children":[]
                            }
                            ]
                        },
                        {
                            "id":"U2",
                            "name":"Bavaria",
                            "type":"States",
                            "children":[
                            {
                                "id":"UC4",
                                "name":"Munich",
                                "type":"City",
                                "children":[]
                            }
                            ]
                        },
                        ],
                },
                {
                    "id":"E2",
                    "name":"France",,
                    "type":"Country"
                    "children":
                    [
                        {
                            "id":"F1",
                            "name":"Lyon",
                            "type":"States",
                            "children":[
                            {
                                "id":"UF1",
                                "name":"Rhone-Alpes",
                                "type":"City",
                                "children":[]
                            }
                            ]
                        },

                    ]
                }
                ],    
                }
            ],

    }
</code></pre>

In my angular code I want to set filter which return matching criteria from city to its respective Geography. I tried multiple solutions bot not getting required result.
Can any one please help me in this?
Thanks in advance

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by girishmahida** [comment]
I have posted the issue on StackOverflow, but didn't get any updates there.
Can you help me with any other forum where I can post my question.
