### ISSUE TITLE
Explain which tokens can be read from a query like ViewChild

### ISSUE THREAD

**Issue by brunnerh** [angular/angular#20927]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
[The documentation](https://angular.io/api/core/ViewChild) currently merely states for `read`:

> read a different token from the queried elements.

## Expected behavior
An explanation as to which tokens can be read or how to find out about what are valid tokens.

## What is the motivation / use case for changing the behavior?
Understanding how this works. I know that `ElementRef` is something that can be read, as it is used in some example somewhere else but not much more.

**Comment by phanikiranwtc** [comment]
Hi All, My question is something related to ViewChild, any help on this is highly appreciated.

I am facing issue with querying a directive of the child component in a parent component
Table component uses scrollableView directive. and table component is used in my Report summary component.
in reportSummary component am trying to find the instance of scrollbaleView directive using @ViewChild.
I was able to find the table component using @ViewChild(DataTable) table : DataTable;
similarly, i should be able to find @ViewChild(ScrollableView) scrollview : ScrollableView;
but it does not
ViewChild documentation says this
https://angular.io/api/core/ViewChild
You can use ViewChild to get the first element or the directive matching the selector from the view DOM. If the view DOM changes and a new child matches the selector, the property will be updated.
View queries are set before the ngAfterViewInit callback is called.

Interestingly table reference is not found in ngAfterViewInit function, i could get the value somewhere else.
But scrollableView is not found at any point in time.

**Comment by LeanHer94** [comment]
So, are we going to have an update on this? At least I'd like to know if I can read both: The Directive (to query for) and also the ViewContainerRef (to add components)
