### ISSUE TITLE
Angular 5 Injector Status 0 instead 401

### ISSUE THREAD

**Issue by launcelot66** [angular/angular#20936]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ * ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
error.status = 0
I'm never get status 401, always 0....

## Expected behavior
error.status = 401

## Minimal reproduction of the problem with instructions
**app.modules.ts**
<pre><code>
import {HttpClientModule, HTTP_INTERCEPTORS, HttpInterceptor, HttpRequest, HttpHandler, HttpEvent, HttpErrorResponse} from '@angular/common/http';
import {BrowserModule} from '@angular/platform-browser';
import {Injectable, NgModule} from '@angular/core';
import {AppComponent} from './app.component';
import {SvgIconComponent} from './svg-icon/svg-icon.component';
import {AuthModule} from './auth/auth.module';
import {NotFoundComponent } from './not-found/not-found.component';
import {Routing} from './app.routing';
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/operator/catch';
import {Router} from '@angular/router';

@Injectable()
class ErrorInterceptor implements HttpInterceptor {
  constructor (private router: Router) {}
  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return next.handle(req)
      .catch((err: any) => {
        console.log('Caught error', err);
        if (err instanceof HttpErrorResponse && err.status === 401) {
          this.router.navigateByUrl('/authorization/login');
        }
        return Observable.throw(err);
      });
  }
}

@NgModule({
  imports: [
    BrowserModule,
    HttpClientModule,
    Routing,
    AuthModule
  ],
  exports: [],
  declarations: [AppComponent, SvgIconComponent, NotFoundComponent],
  providers: [{
    provide: HTTP_INTERCEPTORS,
    useClass: ErrorInterceptor,
    multi: true,
  }],
  bootstrap: [AppComponent]
})
export class AppModule { }
</code></pre>
**General:**
<pre><code>
Request URL:http://127.0.0.1/auth/login
Request Method:GET
Status Code:401 
Remote Address: ***.***.***.***:80
Referrer Policy:no-referrer-when-downgrade
</code></pre>
**Response headers:**
<pre><code>
Cache-Control:no-cache, no-store, max-age=0, must-revalidate
Connection:keep-alive
Content-Length:0
Date:Mon, 11 Dec 2017 12:39:27 GMT
Expires:0
Pragma:no-cache
Server:nginx/1.12.2
X-Content-Type-Options:nosniff
X-Frame-Options:DENY
X-XSS-Protection:1; mode=block
</code></pre>
**Request Headers**
<pre><code>
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate
Accept-Language:ru,en-US;q=0.9,en;q=0.8,ru-RU;q=0.7
**Authorization:Basic **************
Cache-Control:no-cache
Connection:keep-alive
Cookie:JSESSIONID=4926C99AD8C78C281ECF1A86E9D3D78A
Host: 127.0.0.1
Origin:http://localhost
Pragma:no-cache
Referer:http://localhost/authorization/login
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
</code></pre>

## What is the motivation / use case for changing the behavior?
Not authorized users must go to authorization

## Environment

<pre><code>
Angular CLI: 1.5.0
Angular version: 5.0.0

Browser:
- [ * ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.5.0
- Platform:  Mac
- NPM version: 5.5.1

Others:
<code>ng new test</code> and after make any request to server with basic auth
![1](https://user-images.githubusercontent.com/17334308/33832978-d88d61d0-de9f-11e7-8db2-539f9dd522c5.jpeg)

**Comment by vicb** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a plunker reproducing the problem and describing the difference between the expected and current behavior. You can use this plunker template: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by sharpcoder28** [comment]
I have the same problem. Any HttpResponseError has a status of 0 instead of 401.

**Comment by freehuoshan** [comment]
i have the same proble, this problem still not have resolve from angular4-angular5

**Comment by launcelot66** [comment]
in my case the problem was either in the server or in the server settings.
Now for requests, the status comes 401 and in this case a notification with an authorization error is called and there is a redirect (without reloading) to the authorization page.

**Comment by launcelot66** [comment]
@freehuoshan @sharpcoder28 look your server side (or server setting, the problem is somewhere there)

**Comment by freehuoshan** [comment]
@launcelot66 Yes, I solved this problem, mainly because the authentication service was before CORS service, so when the authentication service go back directly, it didn't set the CORS header for it.
