### ISSUE TITLE
@angular/compiler-cli@5.1.0 requires typescript@'>=2.4.2 <2.5.0' but 2.5.3 was found

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#20939]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
A warning is show that I am using `typescript 2.5.3` with `@angular/compiler-cli 5.1.0`

Which is now supported;
https://github.com/angular/compiler-cli-builds/blob/master/package.json#L18

```bash
@angular/compiler-cli@5.1.0 requires typescript@'>=2.4.2 <2.5.0' but 2.5.3 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.4.2 <2.5.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".



````
## Expected behavior
no warning

## Environment

<pre><code>
Angular version: 5.1.0
TypeScript 2.5.3

</code></pre>

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular-cli/issues/8768
