### ISSUE TITLE
test.unit.dart runs build and tests twice for each file change

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#2093]
start: `gulp test.unit.dart`
then: `touch modules/angular2/src/facade/async.dart`

build and test will run twice for each touch

**Comment by IgorMinar** [comment]
@caitp can you please check if this is a watcher issue or if something is actually modifying the source directory during the build?

**Comment by caitp** [comment]
I can't seem to reproduce this locally :| I'll try in a linux container in a bit I guess

**Comment by caitp** [comment]
Actually, the change detection logger doesn't seem to be running for the first change (this is likely some issue with `ignoreInitial` being or not being needed). So it probably "looks" like it's running twice the first time, but not in subsequent changes (where the changes are logged correctly)

**Comment by caitp** [comment]
#2101 landed, so try to reproduce the issue on https://github.com/angular/angular/commit/be88cc7697878c907774848d23214866564b9c46 --- it may be that the issue was really just a symptom of the confusing logging. But that may not have been the case.

**Comment by IgorMinar** [comment]
works fine for me now. closing.
