### ISSUE TITLE
Compiler error messages have incorrect column and line numbers

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#20948]
## I'm submitting a...
<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

Given a template:
```
<table>
  <tr *ngFor="let issue of issues | async">
    <td>{{issue.priorityScore}}</td>
    <td>{{issue.number}}</td>
    <td>{{issue.title}}</td>
    <td>
      {{issue.labels.join(','}}
    </td>
  </tr>
</table>
```

I get error:

```
ERROR in : Parser Error: Missing expected ) at the end of the expression [
      {{issue.labels.join(','}}
    ] in /Users/iminar/Dev/ng-hq/client/src/app/app.component.html@5:8 ("
    <td>{{issue.number}}</td>
    <td>{{issue.title}}</td>
    <td>[ERROR ->]
      {{issue.labels.join(','}}
    </td>
  </tr>
")
```

Today there are at least these problems:
- the column and line numbers are 0-based, which is not how IDEs or even JS VMs typically work
- the column number seems to be off in a way that I can't pinpoint. In the best case, it points to the beginning of the binding and not place in the expression (in the case of expression errors).

## Expected behavior

I'd expect to get line and column numbers that I could use in my IDE to navigate to the problematic code position (via webstorm, vim, vs code, etc).

## Minimal reproduction of the problem with instructions

Create a template that looks like this:
```
{{issue.labels.join(','}}
```

And you get an error:

```
ERROR in : Parser Error: Missing expected ) at the end of the expression [{{issue.labels.join(','}}] in /Users/iminar/Dev/ng-hq/client/src/app/app.component.html@0:0 ("[ERROR ->]{{issue.labels.join(','}}")


webpack: Failed to compile.
```

I'd expect the coordinates to be: `1:3` or even better `1:21`.

## Environment

<pre><code>
framework: 5.1.0
cli: 1.6.0
</code></pre>

**Comment by alexzuza** [comment]
I would say it always refers to the start of the node(`textDef` in the exampe above) where error happens.

We can reproduce that case here

https://ng-run.firebaseapp.com/edit/7nuBw1gAVbW7m16GIzCh


The same behavior with errors like `ExpressionChangedAfterItHasBeenCheckedError`

https://ng-run.firebaseapp.com/edit/8HYOsFtgyUcw5wy7FvME

![1](https://user-images.githubusercontent.com/4223314/33885903-374f5b92-df5e-11e7-8132-f29392413b98.png)

As you can see error only points to the start of `div` element. Would be better if it pointed to a specific property(`myTitle`). I can do it but it requires some hacks

It worth noting that `ngParseError` gives us better understanding what's going on

https://ng-run.firebaseapp.com/edit/aGS4bOQtBb6vn59733sT

**Comment by pkozlowski-opensource** [comment]
Reproduce with Angular v9: https://ng-run.com/edit/z18NoEBjlvWjiInwOkhh
