### ISSUE TITLE
Featrue Request: BuiltIn way to unsubscribe from observables when the component destroyed

### ISSUE THREAD

**Issue by nasreddineskandrani** [angular/angular#20941]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

Basically this post show a way with takeUntil to don't unsubscribe all observeables in ngOnDestroy.
https://netbasal.com/automagically-unsubscribe-in-angular-4487e9853a88
Using this (it's one example of lib)
https://github.com/NetanelBasal/angular2-take-until-destroy

Why not making this or something similar directly part of angular framework?
(I can make a PR if you want to move forward with this)

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/10185

**Comment by kemsky** [comment]
Component inheritance works pretty well now, so it should be easy to create base class that provides automatic cleanup on destroy: unsubscribing, removing event listeners and disposing other things. Using decorator will lack compile time checks. Base class can also solve other problems: better handling for workarounds with `setTimeout`, provide state: initialized, destroyed, view initialized, provide support for automation and component-level logging, provide global template variables i.e. expose translation api, console object, enumerations and etc, provide lifecycle callbacks as base class methods without implementing interfaces every time.

**Comment by nasreddineskandrani** [comment]
@kemsky i don't ask to use decorator. It was just an example of a way that may solve it. I want angular team to add this (base class/decorator/...) to the framework to don't have to redo this each time  in each project or depend on a 3rd party library.

@ericmartinezr i ll close this issue => as duplicate of #10185

**Comment by ohjames** [comment]
@kemsky Problem with component inheritance is you can only extend a single class, if you want to provide different features they all need to be bundled into it. Not a viable long-term solution (although we're using it to work around the lack of lifecycle observables).

**Comment by kemsky** [comment]
@ohjames, you could try to use TypeScript mixins, but I'm not sure if it works with angular without workarounds.

**Comment by nasreddineskandrani** [comment]
in case: https://netbasal.com/automagically-unsubscribe-in-angular-4487e9853a88

**Comment by dinohorvat** [comment]
Custom decorator won't work well if you build the app with AOT. You still need to declare ngOnDestroy even if its empty.
