### ISSUE TITLE
Parallel animations not working

### ISSUE THREAD

**Issue by crisbeto** [angular/angular#20946]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When there are parallel animations running on an element, the first animation runs correctly, but all others are skipped.

## Expected behavior
All of the animations running at the same time.

## Minimal reproduction of the problem with instructions
1. Clone `https://github.com/angular/material2.git`.
2. `npm install`.
3. `npm run demo-app`.
4. Once in the demo app, navigate to `/expansion` and try expanding/collapsing some of the panels. Note how the height of the panels animates correctly, however the arrow rotation doesn't animate. The same can be observed on `/select` and `/menu` where panels expand correctly, however their content doesn't fade in.

## Environment

<pre><code>
Angular version: 5.1.0.

Browser:
- [x] Chrome (desktop) version 63.0
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
Others:
The issue wasn't there in 5.0.0. It seems to have been introduced around 5.0.5.
</code></pre>

**Comment by josephperrott** [comment]
I was able to narrow down the regression as starting with  `@angular/animations@5.0.3`.

Examples:
Arrow rotation in [5.0.2](https://stackblitz.com/edit/animation-repro-5-0-2?file=app/app.component.html)
No Arrow rotation in [5.0.3](https://stackblitz.com/edit/animation-repro-5-0-3?file=app/app.component.html)

**Comment by crisbeto** [comment]
Looks like this is [documented behavior in `animateChild`](https://angular.io/api/animations/animateChild):

> Each time an animation is triggered in angular, the parent animation will always get priority and any child animations will be blocked. In order for a child animation to run, the parent animation must query each of the elements containing child animations and then allow the animations to run using animateChild.

Example of how we resolved it in Material: https://github.com/angular/material2/pull/9134.
