### ISSUE TITLE
innerHTML in svg -> defs not working

### ISSUE THREAD

**Issue by JasonChenLogibec** [angular/angular#20949]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In Internet Explorer 11, attempting to inject values into a defs-tag via [innerHTML] does not work, while this injection works in Chrome.

## Expected behavior
An interface that is consistent across browsers. 

## Minimal reproduction of the problem with instructions
Using Internet Explorer 11 / Edge,
https://plnkr.co/edit/LJkssyfIFPHElec7eFxm
Clicking on "toggle background" should change the red rectangle into a blue-striped rectangle (to view expected behavior, please view the Plunker with Chrome). Instead, it becomes a black rectangle.

## What is the motivation / use case for changing the behavior?
We are porting a desktop application with user-defined sections. Thus, we want to generate patterns as specified by data; this would be the easiest way to approach the situation.

## Environment
Windows 10, 64-bit
(works with Chrome 63.0.3239.84)

<pre><code>
Angular version: 5.0.3, 5.1.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11.0.10240.17146
- [x] Edge version 20.10240.17146.0

</code></pre>

**Comment by vicb** [comment]
Could you please try to write direct JS code to update the element property (ie not using Angular but the JS/DOM api directly) attach the plukr and report if this work on IE11/Edge ?

Trying to figure out if the bug is in IE/Edge or angular.

Thanks

**Comment by JasonChenLogibec** [comment]
Thanks for the fast response!

Using .innerHTML does not work either:
https://plnkr.co/edit/Zg0MrX726ScfV1yGoYwZ?p=preview

**Comment by vicb** [comment]
So we can close this issue right ? (the pb does not come from Angular)

**Comment by JasonChenLogibec** [comment]
Yes. I'll submit a bug report with Microsoft and I'll add that here.
