### ISSUE TITLE
matInput type="time" binding to UI does not happen

### ISSUE THREAD

**Issue by Francis-Ide** [angular/angular#20951]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have this in the HTML 
<input matInput placeholder="select time"  type="time" [(ngModel)]=task.time>

When I select a time, the time gets pushed to the model. When I load the data in the model, the time doesn't show.

## Expected behavior

The Time should be displayed when model is loaded

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/KBMJ86a0x93fFiP3BRdX

## What is the motivation / use case for changing the behavior?

I guess this should be the intended behaviour

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [x ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
You forgot to save the plnkr. Also are you sure this should be reported here and not in [angular's material repo](https://github.com/angular/material2)?

**Comment by jasonaden** [comment]
Please file on the Angular Material repo linked above. Also include a reproduction. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).
