### ISSUE TITLE
Provide means to configure notificationclick in service-worker push

### ISSUE THREAD

**Issue by areijngoudt** [angular/angular#20956]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When a PushNotification is received by the ServiceWorker, I want to be able to handle the notificationclick event. For instance open the webapp and navigate based on the data that was passed in in the PushNotification

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by keatkeat87** [comment]
oh yup, we really need it ! 
any alternative for now ?
any way to make extending ?

**Comment by hazmah0** [comment]
I need this as well. Is there any recommended way or workaround at the moment?

**Comment by juanlu91** [comment]
any update on this?

**Comment by u-ryo** [comment]
There is a workaround.
Add the codes below to `ngsw-worker.js` around the line `this.scope.addEventListener('push', (event) => this.onPush(event));`(Line 1775).
```
      this.scope.addEventListener('notificationclick', (event) => {
        console.log('[Service Worker] Notification click Received.', event);
        event.notification.close();
        if (clients.openWindow && event.notification.data.url) {
          event.waitUntil(clients.openWindow(event.notification.data.url));
        }
      });
```
Then you can specify the URL in the "notification.data.url".
I created [a test application](https://github.com/u-ryo/angular-swpush).

**Comment by abhaygitty** [comment]
Thank you and it works like a magic :) But fails to work when deployment of application is done on the cloud. But locahost works smooth.!!

**Comment by GeorgeTailor** [comment]
I've played around a little with the service-worker code and came up with a solution of extending existing service worker with a notificationclick listener. Can anyone provide some other use-cases of this eventlistener except for redirecting the user to specific url ?

**Comment by sinasava** [comment]
@GeorgeTailor  would you please share the workaround with us?
Not being able to handle click events seems to render push notifications pointless or of not much use as it's not possible to open the pwa from notifications. Or am I missing something?

**Comment by GeorgeTailor** [comment]
@sinasava you can probably extend the generated ngsw.js with your code, which would receive a message from application with definition of the function that should handle the notification click, it is fairly easy to implement. The next step would be to tell angular to look for your extended ngsw instead of using the generated one.
As I mentioned before, not all browsers support that, for example firefox - https://bugzilla.mozilla.org/show_bug.cgi?id=1225110. I am not sure if Edge currently supports it, I wasn't able to find docs regarding that and + I had problems to run service worker within Edge, which was run within VirtualBox on my Mac.

**Comment by sinasava** [comment]
Thank you @GeorgeTailor . I'd have a look
