### ISSUE TITLE
Issue on component moduleUrl generation in IE11

### ISSUE THREAD

**Issue by jlowcs** [angular/angular#20959]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Du to the behavior of the core [stringify function](https://github.com/angular/angular/blob/b21a1d1961aa4039ee0d1479a0c6dc63c6ba8471/packages/core/src/util.ts#L63), if the typescript compiler `removeComments` is set to false, there can be issues with the JIT mode in IE11.

If a component's constructor's parameters include comments, the `stringify` function will call `token.toString()` in IE11 (as the name property of a function is undefined in IE11). The result of that call will include the comments, and will generate a moduleUrl containing `//`, which will result in an issue when generating the templateUrl used to fetch the template in `normalizeTemplateOnly` (in `@angular.compiler`).

```typescript
@Component({
  // ...
})
export class MyComponent {
  constructor(
    myService: MyService // my service
  ) { }
}

// moduleUrl will be "./MyComponent(myService // my service)"
```

## Expected behavior
The `moduleUrl` should only contain the name of the function.

## Environment

<pre><code>
Angular version: 4.4.3 (probably still exists in 5.x though)

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jlowcs** [comment]
I suggest updating `stringify` to:

```typescript
export function stringify(token: any): string {
    if (typeof token === 'string') {
    return token;
  }

  if (token instanceof Array) {
    return '[' + token.map(stringify).join(', ') + ']';
  }

  if (token == null) {
    return '' + token;
  }

  if (token.overriddenName) {
    return `${token.overriddenName}`;
  }

  if (token.name) {
    return `${token.name}`;
  }

  const res = token.toString();

  if (res == null) {
    return '' + res;
  }

  if (typeof token === 'function') {
    return res.replace('\n', ' ').replace(/^function (\w+).*$/i, '$1')
  }

  const newLineIndex = res.indexOf('\n');
  return newLineIndex === -1 ? res : res.substring(0, newLineIndex);
}
```

**Comment by trotyl** [comment]
> as the name property of a function is undefined in IE11

Any reason for not just having it polyfilled?

https://github.com/zloirock/core-js/#ecmascript-function

It's already a standardized API in ES2015 and Angular already depends on lots of ES2015 APIs, having special handling on any possible lacking of ES feature isn't a maintainable approach.

**Comment by AndrewKushnir** [comment]
Closing this ticket, since the reported problem was only present in IE11 and Angular no longer supports IE.
