### ISSUE TITLE
How to implement the route relative redirects with the query params and the fragment

### ISSUE THREAD

**Issue by igor-v-js** [angular/angular#20963]
Hello Everyone!
I have one problem in developing Angular project.

I tried to find the solution on how to implement the route relative redirects with 
When the URL redirects, in which origin redirect has its relative the query params and the `fragment.`

For example, in the guide of Angular.io.
```javascript
const heroesRoutes: Routes = [
  { path: 'heroes', redirectTo: '/superheroes' },
  { path: 'hero/:id', redirectTo: '/superhero/:id' },
  { path: 'superheroes',  component: HeroListComponent },
  { path: 'superhero/:id', component: HeroDetailComponent }
];
```
in hero-detail, `goback()` function to navigate back to the HeroListComponent.
I added `relativeTo: this.route`. But it is not working.
```
gotoHeroes(hero: Hero) {
  let heroId = hero ? hero.id : null;
  // Pass along the hero id if available
  // so that the HeroList component can select that hero.
  // Include a junk 'foo' property for fun.
  this.router.navigate(['/heroes', { id: heroId, foo: 'foo' }], {relativeTo: this.route});
}
```

When configuring to redirect to superheroes, I don't know how to implement this feature.

**Comment by igor-v-js** [comment]
This works fine.
It is my own issue.

**Comment by igor-v-js** [comment]
Even if I set relativeTo option to navigate method, it is not working.
`this.router.navigate(['/heroes', { id: heroId, foo: 'foo' }], {relativeTo: this.route});`
It is very strange.
In crisis section, it works when redirecting to parent route.
But in heroes section, it is now working.
Could you provide any suggestion to fix this problem, please?

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by igor-v-js** [comment]
Hi @jasonaden Thanks. I will try to create the issue on stackoverflow.
