### ISSUE TITLE
main website documentation for list of 'events'

### ISSUE THREAD

**Issue by icenold** [angular/angular#20969]
This main site needs to have a list of available events that we can use
This is very useful for < (events) > and @HostListener(events)
Most of the time people would just end up asking on stack reddit just to know what is the name of an event they trying to look for

**Comment by jenniferfell** [comment]
@jbogarthyde Perhaps something to consider in your API reference work. No need to respond now, but I wanted to make sure you see this. Thanks.

**Comment by ericmartinezr** [comment]
Isn't as simple as referencing [MDN Events](https://developer.mozilla.org/en-US/docs/Web/Events)? Since this is nothing but angular binding/listening to DOM Events.

**Comment by icenold** [comment]
> Isn't as simple as referencing MDN Events? Since this is nothing but angular binding/listening to DOM Events.

For instance like 'keyup.enter', anyone new in angular(even after taking lynda/udemy/pluralsight courses and reading the official documentation) would NEVER know that such binding exists.

yes, flat bindings like 'click', 'keyup' can be reference to MDN
but IMO, they should at least mention other binding posibilities.
after knowing that 'keyup.enter' exists, now I'm not even sure what other event binding possibilities are there. For all I know, there might even be keydown.3000 which could bind if the user holds the key down for at least 3 seconds. Or if they add that feature in the future, nobody would even know it.

**Comment by thw0rted** [comment]
I think `keyup.enter` is being called a "pseudo-event" in a number of places, and as far as I can tell they are not explicitly defined or explained in the docs. #18870 asks for docs, maybe upvote / watch that one?

**Comment by jenniferfell** [comment]
docsarea=events

**Comment by thw0rted** [comment]
Maintainers, could you please remove the "feature" label and associated vote-bot stuff?  Fully documenting the library is not a "feature".

**Comment by petebacondarwin** [comment]
There is currently a discussion being had about what constitutes a feature, when it comes to the docs.

Meanwhile, this issue is basically covered by #18870, which does have enough votes to be included. So I am going to close this one. If you feel that #18870 is missing something, please add an extra comment there.

**Comment by thw0rted** [comment]
Thanks Pete, I was already watching that one but had forgotten that it existed.

If the team is taking "community feedback" about what constitutes a feature, I would like to submit that having any documentation at all about a particular part of the framework -- that is, at least one paragraph saying what the thing is and how it's used -- should not rise to "feature" level.

The linked issue points out that pseudo-events are mentioned as an aside in a related section of the docs (handling user input) and never brought up again.  The term "pseudo-event" never appears anywhere else in the docs, and the current top Google hit for "angular pseudo-event" is a Medium post, followed by some StackOverflow questions.
