### ISSUE TITLE
I have two components rendering its html with MVC view.and the links are provided in left nav bar. when I click on first link it is working correct.when I click on another link it not rendering, in browser developer tools,it is showing the selector<firstcomponent-selector> did nto match any element error

### ISSUE THREAD

**Issue by challasreeja** [angular/angular#20979]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by challasreeja** [comment]
app.module.ts:
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { HttpModule } from '@angular/http';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Component } from '@angular/core';

//import { AppComponent, AppComponent1 } from './app.component';
import { UrlinfonewComponent } from './urlinfonew/urlinfonew.component';
import { NCOGDCMView } from './NCOGWebHCTool/backendAndKitInfo.component';

@NgModule({
    imports: [BrowserModule, HttpModule, FormsModule],
    declarations: [NCOGDCMView, UrlinfonewComponent],
    bootstrap: [NCOGDCMView, UrlinfonewComponent]
})
export class AppModule { }
first Component:
@Component({
    selector: 'my-backend',
    templateUrl: './backendAndkitInfo.html',
    providers: [NcogDcmService]
})
second Component:
@Component({

    selector: 'my-urlinfonew',
    templateUrl: './urlinfonew.component.html',
    providers: [UrlInfoNewService],
})

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
