### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error: Cannot reattach ActivatedRouteSnapshot created from a different route Error: Cannot reattach ActivatedRouteSnapshot created from a different route     at setFutureSnapshotsOfActivatedRoutes

### ISSUE THREAD

**Issue by lorryLUO** [angular/angular#20974]
## I'm submitting a...

import { RouteReuseStrategy, DefaultUrlSerializer, ActivatedRouteSnapshot, DetachedRouteHandle } from '@angular/router';

export class SimpleReuseStrategy implements RouteReuseStrategy {

    public static handlers: { [key: string]: DetachedRouteHandle } = {}

    public static waitDelete: string;

    /** 表示对所有路由允许复用 如果你有路由不想利用可以在这加一些业务逻辑判断 */
    public shouldDetach(route: ActivatedRouteSnapshot): boolean {
        if (route.routeConfig.loadChildren) return false;
        return true
    }

    /** 当路由离开时会触发。按path作为key存储路由快照&组件当前实例对象 */
    public store(route: ActivatedRouteSnapshot, handle: DetachedRouteHandle): void {
        if (route.routeConfig.loadChildren) return null;
        if(SimpleReuseStrategy.waitDelete && SimpleReuseStrategy.waitDelete==this.getRouteUrl(route)){
            //如果待删除是当前路由则不存储快照
            SimpleReuseStrategy.waitDelete=null
            return;
        }
        SimpleReuseStrategy.handlers[this.getRouteUrl(route)] = handle
    }

    /** 若 path 在缓存中有的都认为允许还原路由 */
    public shouldAttach(route: ActivatedRouteSnapshot): boolean {
        if (route.routeConfig.loadChildren) return null;
        return !!route.routeConfig && !!SimpleReuseStrategy.handlers[this.getRouteUrl(route)]
    }

    /** 从缓存中获取快照，若无则返回nul */
    public retrieve(route: ActivatedRouteSnapshot): DetachedRouteHandle {
        if (!route.routeConfig) return null;
        if (route.routeConfig.loadChildren) return null;

        return SimpleReuseStrategy.handlers[this.getRouteUrl(route)]
    }

    /** 进入路由触发，判断是否同一路由 */
    public shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {
    
        return future.routeConfig===curr.routeConfig && 
            JSON.stringify(future.params)==JSON.stringify(curr.params);
    }

    private getRouteUrl(route: ActivatedRouteSnapshot) {
        if (route.routeConfig.loadChildren) return null;
        return route['_routerState'].url.replace(/\//g, '_')
    }

}
///////////////////////////////////////
import { ExtraOptions, RouterModule, Routes } from '@angular/router';
import { NgModule } from '@angular/core';
import { IndexComponent } from "./index.component";
import { HomeComponent } from "app/pages/index/home/home.component";

const routes: Routes = [
    {
        path: '',
        component: IndexComponent,
        children:[{
            path: 'system',
            loadChildren: 'app/pages/system/system.module#SystemModule',
        },{
            path: 'warehouse',
            loadChildren: 'app/pages/warehouse/warehouse.module#WarehouseModule',
        },{
            path: 'supplier',
            loadChildren: 'app/pages/supplier/supplier.module#SupplierModule',
        },{
            path: 'ECommerceManage',
            loadChildren: 'app/pages/e-commerce-manage/e-commerce-manage.module#ECommerceManageModule',
        },{
            path: 'financialManage',  
            loadChildren: 'app/pages/financial-manage/financial-manage.module#FinancialManageModule',
        },{ 
            path: 'home',
            component: HomeComponent,
        },
        { path: '', redirectTo: 'home', pathMatch: 'full' }]
    }
];

@NgModule({
    imports: [RouterModule.forChild(routes)],
    exports: [RouterModule],
})
export class IndexRoutingModule {
}
/////////////////////////////////////////
import { ExtraOptions, RouterModule, Routes } from '@angular/router';
import { NgModule } from '@angular/core';

import { SystemComponent } from "app/pages/system/system.component";
import { UserComponent } from "app/pages/system/user/user.component";
import { UserUpdateComponent } from "app/pages/system/user/user-update/user-update.component";
import { UserCreateComponent } from "app/pages/system/user/user-create/user-create.component";
import { SessionComponent } from "app/pages/system/session/session.component";
import { MenuComponent } from "app/pages/system/menu/menu.component";
import { RoleComponent } from "app/pages/system/role/role.component";
import { DirComponent } from "app/pages/system/dir/dir.component";
import { ParamsComponent } from "app/pages/system/params/params.component";
import { MenuUpdateComponent } from "app/pages/system/menu/menu-update/menu-update.component";
import { MenuCreateComponent } from "app/pages/system/menu/menu-create/menu-create.component";

const routes: Routes = [
    {
        path: '',
        component: SystemComponent,
        children: [{
            path: 'user',
            component: UserComponent,
        },
        {
            path: 'userUpdate',
            component: UserUpdateComponent,
        },
        {
            path: 'userCreate',
            component: UserCreateComponent,
        }, {
            path: 'menu', 
            component: MenuComponent,
        },
        {
            path: 'menuUpdate',
            component: MenuUpdateComponent,
        },
        {
            path: 'menuCreate',
            component: MenuCreateComponent,
        },{
            path: 'role', 
            component: RoleComponent,
        }, {
            path: 'session', 
            component: SessionComponent,
        }, {
            path: 'dir', 
            component: DirComponent,
        }, {
            path: 'params', 
            component: ParamsComponent,
        },{
            path: '',
            redirectTo: 'user',
            pathMatch: 'full',
        },
    ]
    }
];

@NgModule({
    imports: [RouterModule.forChild(routes)],
    exports: [RouterModule],
})
export class SystemRoutingModule {
}

//////////////////////////////////////////////
 /* 
    关闭tab
    */
    closeTab(functionObj) {

        this.operationName = '_' + functionObj.action.replace(/\//g, '_');
        SimpleReuseStrategy.waitDelete = this.operationName;
        // console.log(SimpleReuseStrategy.handlers);
        // 删除快照
        delete SimpleReuseStrategy.handlers[this.operationName];

        const self = this;
        const index = _.findIndex(this.tabs, function (chr) {
            return chr.menuName == functionObj["menuName"];
        });

        if (this.tabs.length > 1) {
            this.tabs.splice(index, 1);
            if (this.historyStack[this.historyStack.length - 1].menuName === functionObj["menuName"]) {
                this.historyStack.pop();
                this.selectTab(this.historyStack[this.historyStack.length - 1]);
            }
        }else{
            this.router.navigate([functionObj['action']]);
            return;
        }
    };
///////////////////////////////////////////
##
## Current behavior

core.js:1427 ERROR Error: Uncaught (in promise): Error: Cannot reattach ActivatedRouteSnapshot created from a different route
Error: Cannot reattach ActivatedRouteSnapshot created from a different route
    at setFutureSnapshotsOfActivatedRoutes (router.js:3043)
    at createNode (router.js:3027)
    at eval (router.js:3032)
    at Array.map (<anonymous>)
    at createNode (router.js:3032)
    at eval (router.js:3067)
    at Array.map (<anonymous>)
    at createOrReuseChildren (router.js:3060)
    at createNode (router.js:3021)
    at eval (router.js:3064)
    at setFutureSnapshotsOfActivatedRoutes (router.js:3043)
    at createNode (router.js:3027)
    at eval (router.js:3032)
    at Array.map (<anonymous>)
    at createNode (router.js:3032)
    at eval (router.js:3067)
    at Array.map (<anonymous>)
    at createOrReuseChildren (router.js:3060)
    at createNode (router.js:3021)
    at eval (router.js:3064)
    at resolvePromise (zone.js:824)
    at resolvePromise (zone.js:795)
    at eval (zone.js:873)
    at ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4747)
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:192)
    at drainMicroTaskQueue (zone.js:602)
    at ZoneTask.invokeTask [as invoke] (zone.js:503)
    at invokeTask (zone.js:1540)

I click side item to create many new tab,when I close some tab ,sometime has error about  : Cannot reattach ActivatedRouteSnapshot created from a different route ;  If I add “if(route.routeConfig.loadChildren) return null;”  The probability of this error will be reduced；

## Expected behavior

I want resolve this error

## Environment

<pre><code>
Angular version: 5.0.0
"@angular/cli": "1.5.4"

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by luohong123** [comment]
![image](https://user-images.githubusercontent.com/20392340/60695733-62123200-9f15-11e9-858c-f7fd3132e75f.png)
hello,I have a same error.
