### ISSUE TITLE
Doc doesn't mention angular support for inheritance

### ISSUE THREAD

**Issue by chaouiy** [angular/angular#20981]
Many users are wondering about Angular support/maturity in terme of inheritance (between services, components, etc.) The offitial doc doesn't mention this

**Comment by jotatoledo** [comment]
what should be mentioned in your opinion? Inheritance is a common feature on languages that support classes.

**Comment by jenniferfell** [comment]
@jbogarthyde For your consideration. No need to respond here right now. Pls DM slack any thoughts. Thanks.

**Comment by amineparis** [comment]
@jotatoledo  For example, It would be a great addition in the doc coding style page if it identifies good practices of using inheritance.

**Comment by jenniferfell** [comment]
docsarea=styleguide
docsarea=architecture

**Comment by atscott** [comment]
Closing, as this isn't something we plan to create a stand-alone document for. General practices for inheritance isn't an Angular-specific thing. We should keep an eye on where and how specific Angular features interact with inheritance (such as the scope of styles, which is documented [here](https://angular.io/guide/component-styles#style-scope)). Thanks for the suggestion, however.
