### ISSUE TITLE
Angular does not (quite) compile with strictNullChecks (and other options)

### ISSUE THREAD

**Issue by mprobst** [angular/angular#20986]
In a recent change in Google internal code, I discovered that many Angular packages do compile with `strictNullChecks`, but not all. In particular compiler-cli and bazel packages do not support `strictNullChecks`, and all `benchmark*` packages have issues.

These packages also break with other strictness flags, like `noFallthroughCasesInSwitch` and `noImplicitAny`.

**Comment by Delagen** [comment]
No any factories from node_modules (source in TS) in output folder, only d.ts & json

**Comment by Delagen** [comment]
Reverted from 5.1.2 to 5.1.1, it works as expected

**Comment by alexeagle** [comment]
I plan to change Angular's build to have a single `tsconfig.json` for the whole repository, which will be the forcing function to make these strict settings consistent.

**Comment by jelbourn** [comment]
I believe this issue is obsolete.
