### ISSUE TITLE
DatePipe return for blank values

### ISSUE THREAD

**Issue by guilhermejcgois** [angular/angular#20989]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

DatePipe returns null for blank inputs

## Expected behavior

DatePipe accept a optional third parameter (default to null) to return in such case (blank inputs)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ocombe** [comment]
Hello, what do you mean by blank input? An empty string?

**Comment by guilhermejcgois** [comment]
Hum... I was refering the ng4 api for date pipe, my mistake to not take a look at ng5, maybe I need to update my feat req? 🤔 

BTW, @ocombe I was thinking in empty strings and null values... We have cases in our system in model with optional date properties, and for the case when the date property wasn't found, in the all entire UI we show a `-` ... I don't came back to think serious about how to do this stuff, a token like LOCALE_ID with the default set to null can do the job, but I don't sure if is the best way...

**Comment by ocombe** [comment]
yes update with Angular v5 and check if you still have the problem.
A reproducible example (plunkr or stackblitz) would be nice.

**Comment by guilhermejcgois** [comment]
Hey @ocombe sorry for the delay! I have make a little repro on [stackblitz](https://stackblitz.com/edit/angular-blank-dates). I'm using a string date, empty string date, null value, and an invalid js date object, hopes that help

**Comment by vicb** [comment]
Closing as this is something that could be solved on your side:
`(myDate | date) | default(' -- ')`.
