### ISSUE TITLE
After building the application I get No provider for e!

### ISSUE THREAD

**Issue by SlimenTN** [angular/angular#20985]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I get error in the console:
<code>
vendor.988e7eac784c28b96db8.bundle.js:1 ERROR Error: No provider for e!
    at _ (vendor.988e7eac784c28b96db8.bundle.js:1)
    at vendor.988e7eac784c28b96db8.bundle.js:1
    at t._throwOrNull (vendor.988e7eac784c28b96db8.bundle.js:1)
    at t._getByKeyDefault (vendor.988e7eac784c28b96db8.bundle.js:1)
    at t._getByKey (vendor.988e7eac784c28b96db8.bundle.js:1)
    at t.get (vendor.988e7eac784c28b96db8.bundle.js:1)
    at pe (vendor.988e7eac784c28b96db8.bundle.js:1)
    at t.get (vendor.988e7eac784c28b96db8.bundle.js:1)
    at De (vendor.988e7eac784c28b96db8.bundle.js:1)
    at Ve (vendor.988e7eac784c28b96db8.bundle.js:1)
</code>
Although the app works fine using ng serve

## Expected behavior

I expect the app to work fine since it's working good in development mode.

## What is the motivation / use case for changing the behavior?

I have no idea.

## Environment

<pre><code>
Angular version: 4.4.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.6.0  
- Platform:  Mac

Others:

This is my package.json file:
{
  "name": "my-app",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.0.0-beta.1",
    "@angular/animations": "^4.4.1",
    "@angular/common": "^4.4.1",
    "@angular/compiler": "^4.4.1",
    "@angular/core": "^4.4.1",
    "@angular/forms": "^4.4.1",
    "@angular/http": "^4.4.1",
    "@angular/platform-browser": "^4.4.1",
    "@angular/platform-browser-dynamic": "^4.4.1",
    "@angular/router": "^4.4.1",
    "core-js": "^2.5.1",
    "ngx-color-picker": "^4.5.0",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.17"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.0",
    "@angular/compiler-cli": "^4.4.1",
    "@angular/language-service": "^4.4.1",
    "@types/jasmine": "^2.6.0",
    "@types/jasminewd2": "^2.0.3",
    "@types/node": "^6.0.88",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "^2.6.2",
    "webpack": "^3.10.0"
  }
}

</code></pre>
The problem here is that I can't locate the source if this error !!

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by SlimenTN** [comment]
yes I have tried and this is the question:
https://stackoverflow.com/questions/47795507/angular4-unclear-exception-after-building-the-application
But no answer !!
