### ISSUE TITLE
Selected dropdown option is not displayed by the browser (Chrome, IE)

### ISSUE THREAD

**Issue by juristr** [angular/angular#2098]
Hi,

I have a strange issue in that the selected option doesn't get displayed in Chrome and IE (while it works in Firefox):

![image](https://cloud.githubusercontent.com/assets/542458/7770056/678efa16-008a-11e5-9169-21f27df8c574.png)

although in the HTML it is selected:

![image](https://cloud.githubusercontent.com/assets/542458/7770061/7bcbffba-008a-11e5-9db3-4b137adfb727.png)

Here's the plunker to reproduce the case:
http://plnkr.co/edit/zYY8wwyVYbNUE5pwyYan?p=preview

**Note,** it also only happens in the mentioned browsers when I set the data asynchronously, that is, in the Plunkr (for demoing) through a $timeout, while in my production code it is fetched through an $http call.

I'm not quite sure whether it is due to some strange binding in my code or an issue within Angular itself, and since also the guys on the IRC channel were not able to help me, I'm posting it here :smiley: .

**Does not work in**

- Chrome (latest stable)
- Chrome 45.0.2409.0 canary
- Internet Explorer 11.0.9600.17801 (Win7)

**Works in Firefox 37.0.2 and 38.0.1**.

**Comment by ericmdantas** [comment]
Hello!

This is a repository for angular2. 

I'd encourage you to open an issue in the [angular 1.x repo](https://github.com/angular/angular.js).

**Comment by juristr** [comment]
Oh, sorry, didn't get that.
I'll move it over once I'm on a computer again (in a couple of hours). It's kinda difficult from a mobile :wink:

**Comment by ericmdantas** [comment]
No problem =]

It's just that you might get more help there.

As for the problem you have, couldn't you move the inicialization of the select's ```ng-model``` in the async call?

[Like this](http://plnkr.co/edit/NUIfW7G0JlGHvEUTEyZt?p=preview).

**Comment by juristr** [comment]
@ericmdantas I'll verify that, thx. Anyway, I posted it on the Angular 1.x repo as this thing seems strange actually: https://github.com/angular/angular.js/issues/11929
