### ISSUE TITLE
v5.1.0 Import BrowserAnimationModule DOM doesn't get destroyed

### ISSUE THREAD

**Issue by DanielTupa** [angular/angular#20982]
## I'm submitting a...
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If an error is thrown and the Browser Animation Module is imported anywhere in the application the DOM does not get cleaned up and the entire application becomes unstable.

## Expected behavior
If an error is thrown the DOM should still be able to clean its self up on destroy

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/ur7bUE3zRZuaibLLgZCu?p=preview

## What is the motivation / use case for changing the behavior?
I can't use angular animations.

## Environment
Angular version: 5.1.0

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.1
- Platform:  Windows

**Comment by DanielTupa** [comment]
@jasonaden It looks like this has been resolved with angular 5.1.1

So glad this was fixed =) Thanks a bunch

**Comment by matsko** [comment]
Closing this for now.
