### ISSUE TITLE
Documentation for angular compiler options should be accessible on angular.io

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#20987]
## I'm submitting a...

<pre><code>
[x] Documentation issue or request
</code></pre>

## Current behavior

The documentation for the Angular compiler options is buried in the source code in https://github.com/angular/angular/blob/master/packages/compiler-cli/src/transformers/api.ts#L40-L164

## Expected behavior

This should be moved to and maintained in the content section of angular.io and a reference to that documentation placed in api.ts.

## Minimal reproduction of the problem with instructions

Search angular.io for `fullTemplateTypeCheck`.

**Comment by jenniferfell** [comment]
@chembu FYI. When we have a PR, we should remember to link it here.

**Comment by jenniferfell** [comment]
Addressed by [PR 21333](https://github.com/angular/angular/pull/21333) 

New doc published: [Angular Compiler Options](https://angular.io/guide/aot-compiler#angular-compiler-options)
