### ISSUE TITLE
Bindings are not updated properly when handling events from iframe

### ISSUE THREAD

**Issue by anton-gorbikov** [angular/angular#20980]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Consider a page with `async` binding. Stream receives values from page events and from <iframe> events inside the page. But currently page binding reflects only values received from the original page, when <iframe> is focused binding is not updated.

## Expected behavior
Binding should be updated in both cases.

## Minimal reproduction of the problem with instructions
Here is the [Plunker](https://plnkr.co/edit/4HvDi93O3Njd5p4C3We3?p=preview) link. To reproduce the bug press couple of keys on keyboard. You should see that 3 values are changed on the page: 2 via angular bindings and 1 using subscription to the stream and direct innerHTML modification. Then click mouse inside the iframe and press couple more keys. Only value set using innerHTML will change, which is incorrect.

## What is the motivation / use case for changing the behavior?
The use case is integration of third-party application into iframe of our product.

## Environment

<pre><code>
Angular version: 5.1.0

Browser:
- [x] Chrome (desktop) version 65 (canary)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 57
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

<hr>

Because an iFrame is it's own context, there isn't a way for Angular to have bindings work across an iFrame. You would need to load Angular in the iFrame itself and separately load the data as well. Please review [iFrame documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) for any questions.

**Comment by sergey-tihon** [comment]
Hi @anton-gorbikov, I am not Angular expert (not even close) but I see only one solution - trigger change detection manually - see sample here https://plnkr.co/edit/gRjeViQzlkjeaME0pcT7?p=preview

I have no idea why Angular does not react to changes propagate from the iframe.
