### ISSUE TITLE
ERROR TypeError: Cannot read property 'length' of null at HttpHeaders.applyUpdate

### ISSUE THREAD

**Issue by pranaykumar389** [angular/angular#20999]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

This error occurred when I'm making httpClient.get() call to a REST API.

## Expected behavior

If we a call http://localhost:3000/api/public it must return all the list of jobs but instead it throws an error in the front-end.

## Minimal reproduction of the problem with instructions

[http://plnkr.co/edit/DXI3tsRu17zUvMoDAov1?p=info] my plunker for reference.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.1.4  
- Platform:  Windows 

Others:

</code></pre>

**Comment by beeing** [comment]
We are facing same problem here. HttpClient.get will hit error if we pass in headers.

**Comment by paddyfink** [comment]
Hey, we facing the same issue, but only with a specific customer. For the others, it works fine. And that customer has that issue only in Chrome. It works on Edge.

**Comment by johnfrades** [comment]
currently experiencing this issue, i've never updated any packages. All of a sudden, i just got this error

**Comment by trotyl** [comment]
See https://github.com/angular/angular/issues/18743#issuecomment-323215006

**Comment by paddyfink** [comment]
I confirm, it was the case for me. I was passing a undefined value to HttpHeaders.set. It,s all good now

**Comment by BotanMan** [comment]
Got the same issue, the reason of that was setting `null`/`undefined` as header at interceptor 
```
req = req.clone({
        setHeaders: {
              'my-custom-header': key // which is basically not available null or undefined
        }
});
```

**Comment by rafame2** [comment]
HttpHeaders.applyUpdate should check for null before checking length of value...

**Comment by JoostK** [comment]
Closing as working as intended per https://github.com/angular/angular/issues/18743#issuecomment-323215006.

**Comment by khizaruddins** [comment]
same issue
