### ISSUE TITLE
Route component reuse options

### ISSUE THREAD

**Issue by arlowhite** [angular/angular#20993]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Sometimes components are complicated and have a lot of internal state. In these cases, it would be nice to have a simple way to configure the router to always create a new instance of the component.

Currently, one must setup a `RouteReuseStrategy`, which is not documented in much detail and may be daunting to newer programmers.

## Expected behavior

`Route` should support some simple reuse configuration.

This is just an example idea:

Disable component reuse completely:
```javascript
{ path: 'foo/:p1', reuse: false }
```

Disable component reuse for certain params.
In this case, if `p2` changes, the component is reused, but if `p1` changes, the component is recreated.
```javascript
{
  path: 'foo/:p1/:p2',
  reuse: {
    unlessChange: ['p1']
  }
}
```

## What is the motivation / use case for changing the behavior?

Implementing `RouteReuseStrategy` is complicated enough that I think default Route config options are justified.

## Environment

Angular version: `5.1.0`

## Example implementation

This implements the `unlessChange` logic. All other `RouteReuseStrategy` methods return false/null like the default.

```typescript
  shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {
    // default from DefaultRouteReuseStrategy
    const sameRouteConfig = future.routeConfig === curr.routeConfig;
    // future.routeConfig can be null
    if (sameRouteConfig && future.routeConfig) {
      const reuse: RouteReuseOptions = future.routeConfig.data.reuse;
      if (reuse) {
        for (const param of reuse.unlessChange) {
          const futureValue = future.paramMap.get(param);
          const currValue = curr.paramMap.get(param);
          if (futureValue !== currValue) {
            console.log(`Route param '${param}' is different, not reusing route`, future, curr);
            return false;
          }
        }
      }
    }
    return sameRouteConfig;
  }
```

If this feature were to actually be implemented, code like this could be put into the `DefaultRouteReuseStrategy`. However, it would need to be documented that the `Route.reuse` options will not work if you override the `RouteReuseStrategy`.

Also need to decide on the option to disable reuse. Should the reuse property always have an object value, or can it be `RouteReuseOptions | false` i.e.  `reuse: false` or `reuse: { never: true }`

**Comment by jasonaden** [comment]
Thanks for the suggestion. Can you think of other reuse strategies that might be useful?

I don't think we would implement as an option on the config. But maybe we could publish some helpers. Basically default RouteReuseStrategies that are configurable with options like you're saying above. That way applications only pay for the extra library bytes if they import and use one of these strategies.

**Comment by arlowhite** [comment]
There could be issues with params or query params that are initially undefined.
I could see developers wanting a different reuse policy for a `undefined --> VALUE` param change vs `VALUE1 --> VALUE2`
You probably would want to either always recreate, or reuse the component in the first case and recreate it in the second.

If your project routes many URLs to the same component you might want more reuse strategy features, but I don't have a good usecase.

**Comment by zoechi** [comment]
#35794 looks related
