### ISSUE TITLE
docs: async pipe needs better documentation on timing issues with Observables

### ISSUE THREAD

**Issue by jasonaden** [angular/angular#20998]
Consider the following code:

```
<div class="permissions">Permissions: {{ currentPermissions | async }}</div>
<div *ngFor="let user of users | async">... render users ...</div>
```

When this template is instantiated, it will subscribe to the `users` observable, capture the users as they are pushed through the Observable, and iterate over, displaying users. It will do the same with `currentPermissions`.

What if you were to wait for both these Observables to be ready and set a `loaded` property while waiting?

```
<div *ngIf="loaded | async">
  <div class="permissions">Permissions: {{ currentPermissions | async }}</div>
  <div *ngFor="let user of users | async">... render users ...</div>
</div>
```

Now the execution is much different. `permissions` and `users` may be loading in the background. When they both have values they get pushed to any listening Observer. However, because `loaded` isn't true yet, the `async` pipes haven't subscribed yet. Once `loaded` is true, the `async` pipes will subscribe, but they've already missed their values.

This can be mitigated by using `replay` or `shareReplay` to guarantee a value is delivered on new subscriptions. However, it's unclear this would be the fix.

This should be well documented so it's clear what the problem is, how to identify it, and how to fix it.

**Comment by jasonaden** [comment]
User generated example of this problem:

https://stackblitz.com/edit/angular-r1sqjy

**Comment by jenniferfell** [comment]
@jbogarthyde FYI...

**Comment by jenniferfell** [comment]
@jasonaden : Hi. Thanks for opening this issue. Where would you expect this to be documented? (just trying to categorize and group issues) Thanks!

**Comment by jenniferfell** [comment]
possibly affects ... 
filename=https://angular.io/api/common/AsyncPipe
filename=https://angular.io/guide/pipes#pure-and-impure-pipes
filename=https://angular.io/guide/observables-in-angular

**Comment by mgechev** [comment]
Since this is on the edge of rxjs and Angular, I'll suggest to keep it outside the Angular scope.
