### ISSUE TITLE
HttpErrorResponse status returns 0 instead of 401

### ISSUE THREAD

**Issue by sharpcoder28** [angular/angular#20991]
I'm trying to build an interceptor to handle 401 requests, but even in the subscribe error function handler the status is 0. I tried setting observe: response but that didn't help.

`this.http
    .get<ILead>(this.leadApiUrl)
     .subscribe( data => {
       console.log('data' +  data);
       this.company = data;
      },
    err => {
      console.log(err);
    })
`
![401](https://user-images.githubusercontent.com/5140239/33956071-8165df1e-e00b-11e7-88ab-0dc720fd703e.PNG)

**Comment by danwulff** [comment]
@sharpcoder28 Chrome (and possibly other browsers) return a status of `0` when incorrect CORS headers are used. This is likely some problem with the headers you are sending/receiving from your server and not Angular itself (I could be wrong but I myself have struggled with CORS and it has never been Angular's fault. Although I have had to set specific headers inside angular).

You can find more info about CORS here: https://cloud.google.com/storage/docs/cross-origin

**Comment by alxhub** [comment]
@danwulff is correct, this is a CORS issue, not an HTTP issue.

**Comment by aubrym** [comment]
Hi everyone,

I force my backend to add Access-Control-Allow-Origin header and verify the response.
After this the message No Access-Control-Allow-Origin is not longer displayed. But the HttpErrorResponse status always return 0 instead the correct status returned by the server.

**Comment by aholbreich** [comment]
@aubrym +1 Using  Angular 5.2.0 - 5.2.4 and probably before

**Comment by mlc-mlapis** [comment]
@aholbreich ... it is still CORS issue ... if you simulate the same case even with a tool totally outside Angular ... you can get also `status=0`.

**Comment by wangzhenhui1992** [comment]
I want to know why Chrome and FireFox can show 401 on console while Angular caught 0.
Are these browsers changed 401 to 0 before browser API passed the result to js .
@danwulff

**Comment by aec4444** [comment]
following

**Comment by mtpultz** [comment]
Don't know if this helps, but I had CORS on.  In my particular case I was getting `status=0` and noticed the token wasn't be attached to the header.  I incorrectly assumed that a whitelisted domain could include params like `http://localhost:8000/api/v1` so in `environment.ts`, which I used so I could keep my environment variables reasonably DRY by double it up with my API endpoint, but this didn't work till I removed both `http://` and `/api/v1` and set the whitelisted domain to `localhost:8000`

**Comment by rameezrami** [comment]
i am also getting same error.. and i think this is angular issue or the way i structured my code , because if you check the image, you can see server response code 401 and when we console error in interceptor it show status zero.

its not the issue with http request  if i check the error response without interceptor everything is fine. even in the current situation i can get currect error response in http service success but not in interceptor.

**Comment by rodrigoevildead** [comment]
@rameezrami solution works fine! Thank you!

**Comment by zhuhang-jasper** [comment]
@rameezrami how to do that in swagger node js back-end?

**Comment by dkusch** [comment]
I faced with the same issue - not getting correct HttpError object, Error status was always set to 0. And i think found a reason. So as my Application and API was on different domains - CORS mechanism is applied.
According to CORS for each API request browser sends two requests:
1. preflight OPTIONS request to understand if API allows Actual/Origin request.
2. when API allows (OPTIOS request respond with status 204 and correct Access-Control-Allow-Origin headers) - browser send next "Actual/Origin request".
In our Angular Application we are handling Error response for "Actual/Origin request", and if "preflight OPTIONS request" failed - browser doesn't give correct HttpError object for error handler. 
So to get correct status of http response - be sure to get success preflight OPTIONS request response.

**Comment by lehone-hp** [comment]
@rameezrami your solution was perfect :+1:
