### ISSUE TITLE
Error: Unexpected value 'SpinnerModule' imported by the module 'ProductFfmModule'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by gauravkadam** [angular/angular#21004]
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { SpinnerModule } from 'angular-spinners';

import { 
  //UserSessionService,
  SelectBoxComponent,
  SelectBoxOptionComponent,
  KeysPipe 
} from  'meteor/assist:commons';

import { ProductFfmComponent } from './product-ffm.component';
import { ProductFfmService } from './product-ffm.service';
import { ZipValidateDirective } from './zip-validate.directive';

import { ProductHelper } from './../utility/utility';
import { UserSessionService } from './../user-session.service';
import { PhonePipe } from './../utility/phone.pipe';

//FFMS:
import { FfmDeliveryComponent } from './ffm-delivery/ffm-delivery.component';
import { TakewithComponent } from './takewith/takewith.component';
import { FfmMpuComponent } from './ffm-mpu/ffm-mpu.component';
import { TransferSaleComponent } from  './transfer-sale/transfer-sale.component';
import { FlyBackDeliveryComponent } from './flyback-ffm/flyback-delivery.component';

@NgModule({
  imports: [
    CommonModule,
    FormsModule, 
    ReactiveFormsModule,
    HttpModule,
    SpinnerModule,
  ],
  
  declarations: [ 
  	ProductFfmComponent,
  	FfmDeliveryComponent,
    ZipValidateDirective,
    TakewithComponent,
    FfmMpuComponent,
    TransferSaleComponent,
    SelectBoxComponent,
    SelectBoxOptionComponent,
    FlyBackDeliveryComponent,
    KeysPipe,
    PhonePipe,
  ],
  providers:[
    ProductFfmService,
    ProductHelper,
    UserSessionService
  ],
  exports: [
    ProductFfmComponent,
    FfmDeliveryComponent,
    ZipValidateDirective,
    TakewithComponent,
    TransferSaleComponent,
    SelectBoxComponent,
    SelectBoxOptionComponent,
    FlyBackDeliveryComponent,
    PhonePipe,
  ]
})

export class ProductFfmModule { }

Am using augular 4
please help me on this

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

You can search that error message in the repo, there are a few issues about it.
