### ISSUE TITLE
window retain back-page postion when location.back

### ISSUE THREAD

**Issue by alanhg** [angular/angular#21000]
my code
```typescript
 constructor(private router: Router) {

    }

    ngOnInit() {
        this.router.events.subscribe((evt) => {
            if (!(evt instanceof NavigationEnd)) {
                return;
            }
            window.scrollTo(0, 0);
        });
```
****

jump to new page,scrollTop is ok,But when back history page,I want retain history page position.

I think it's a disadvantage about Angular.

**Comment by alanhg** [comment]
jump to new page,scrollTop is ok,but when back history page,I want retain history page position.

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/10929. Read through the issue, there's a PR for it.

**Comment by alxhub** [comment]
Closing as a duplicate.
