### ISSUE TITLE
Pipe Transform multiple values as array not working

### ISSUE THREAD

**Issue by lenoln** [angular/angular#21009]
## Hi, I'm trying to use PipeTransform with an Array, the code does not present exceptions, but does not recognize the changes in the filter list. can anybody help me?

AgePipe
<pre><code>
import { Pipe, PipeTransform } from 'angular2/core';
@Pipe({
  name: 'AgePipe'
})
export class AgePipe implements PipeTransform {
   transform(input, args?) {
    let tempList: any[] = input;
    args.forEach(age => {
      tempList = tempList.filter(item => {
        return item.age !== age;
      });
    });
    console.log('after: ', args);
    return tempList;
  }
}
</code></pre>
## Code

[Plunker](https://embed.plnkr.co/1sI1HQBLblK4TAq1eBRS/)

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by lenoln** [comment]
@ericmartinezr thanks for the feedback, I updated now. Would you help me?

**Comment by skreborn** [comment]
@lenoln Please use the provided template to file a proper issue. Said template is automatically provided when you [open a new issue](https://github.com/angular/angular/issues/new). What do you mean by _"does not recognize the changes"_? Does the `console.log('after: ', args);` print anything at all to the console?

**Comment by lenoln** [comment]
Thanks @skreborn,
but you would help me more if you tried to focus on the code problem.

**Comment by chuckjaz** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
