### ISSUE TITLE
"any" or object type literal parameter on an injectable is not skipped during dependency injection, despite being marked as optional.

### ISSUE THREAD

**Issue by mjamin** [angular/angular#21008]
## I'm submitting a...
<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[?] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

<pre><code>// works
@Injectable()
export class SomeInjectable {
    constructor(@Optional() foo: string = null) { }
}

// doesn't work: "Uncaught Error: Can't resolve all parameters for SomeInjectable: (?)."
@Injectable()
export class SomeInjectable {
    constructor(@Optional() foo: any = null) { }
}

// same error:
@Injectable()
export class SomeInjectable {
    constructor(@Optional() foo: {[key: string]: any} = {}) { }
}
</code></pre>

## Expected behavior
Skip the with @Optional() marked parameter during dependency injection, regardless of parameter type.

## Environment

<pre><code>Angular version: 5.1.0
</code></pre>

**Comment by alxhub** [comment]
Hi @mjamin,

I think you're misunderstanding the meaning of `@Optional()`. It tells the DI system that it's okay if it doesn't have a value provided for the token (whether that token is a class type or an `InjectionToken`). Even with `@Optional()`, the DI system still needs to know what type to look for, it's not okay to have a parameter without a type.

You could work around this by creating a NONE token:

```
const NONE = new InjectionToken<any>('NONE');

constructor(@Optional() @Inject(NONE) private foo: ...) {}
```

**Comment by mjamin** [comment]
Thanks.
