### ISSUE TITLE
Add errorCount to FormGroup

### ISSUE THREAD

**Issue by markgoho-EDT** [angular/angular#21011]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently if you want to display some messaging with your form to the effect of "You have 3 errors on your form." It's a significant amount of code to wire that up. You need to loop through all of your controls, and controls within any arrays, check for errors, and add each one to a running counter. Then you have to figure out where to in the process to run that method. I've chosen to run it on a `.valueChanges()` on the whole form so that whenever a user enters data, it'll calculate how many errors exist.

## Expected behavior

I'd love to see a `.errorCount` property or something similar that we could access that would do this logic in a more efficient way.

## What is the motivation / use case for changing the behavior?

Rather than simply telling the user there are errors on the form, give a specific number. This helps on larger forms where there may be many controls.

## Environment

<pre><code>
Angular version: 5.1.1

</code></pre>

**Comment by nephi5** [comment]
Great idea! That would be cool!

**Comment by Toxicable** [comment]
Off the top of my head, and very much untested you could do something like this
```
function getErrorCount(control: AbstractControl): number{
  let childCount = 0;
  if(control instanceof FormGroup){
    childCount =  Object.keys(control.controls)
      .reduce((count, keyb) => getErrorCount(control.controls[keyb]) + count, 0)
  } else if (control instanceof FormArray){
    childCount = control.controls.reduce((count, control) => getErrorCount(control) + count, 0);
  }
  return Object.keys(control).length + childCount;
}
```
I don't think this is unreasonable for us to do ourselves

**Comment by lazarljubenovic** [comment]
Interesting proposal, but needs to be outlined more clearly. If several errors exist on a single form control, how does that count? Do we count errors or do we count the controls which contain at least one error? Maybe this could be an additional parameter?
