### ISSUE TITLE
Rendering string as HTML element

### ISSUE THREAD

**Issue by jamilalisgandarov** [angular/angular#21010]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Not rendering variable value (string) as HTML Element using "{{}}"

## Expected behavior
Why there is not an option to render text as HTML element for example using "{{{ }}}" (3 brackets or something). Using [innerHTML] is not handy for every situation I think

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
This makes no sense.
Use `[innerHTML]` to render html

**Comment by pkozlowski-opensource** [comment]
> Using [innerHTML] is not handy for every situation I think

I don't think there is enough justification here to support new syntax so I'm going to close this one as won't fix.
