### ISSUE TITLE
Router `enableTracing` could support changing the value runtime

### ISSUE THREAD

**Issue by peterbakonyi05** [angular/angular#21015]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
`enableTracing` must be set during bootstrap and cannot be changed run-time.
```ts
RouterModule.forRoot(routes, { enableTracing: true })
```

## Expected behavior
```ts
RouterModule.forRoot(routes, { enableTracing: _isTracingEnabled })

export function _isTracingEnabled() {
    return someGlobalContext.isDebug;
}

// so type would be:
enableTracing?: boolean | (() => boolean);
```

## What is the motivation / use case for changing the behavior?
When having a router related defect on Prod environment (especially if it happens only on a specific browser) it helps a lot to see the router events. By default they should be turned off, but being able to enable logging with a global feature flag is quite handy. 

For now we implemented the same logging that angular router has, but it can be turned on/off like this. I think it is a valuable feature request to help debugging production issues.

## Environment

<pre><code>
Angular version: 5.1.0
</code></pre>

**Comment by Toxicable** [comment]
If an error occurs in production turning tracing on afterwards wont help since the error has already occured.

**Comment by jasonaden** [comment]
See the response from @Toxicable above. Also, it's preferable to be able to tree shake out debugging code for production so this is not a feature we would like to add in as it would cause prod apps to pay the cost for debugging whether they need/want it or not.
