### ISSUE TITLE
HttpClient API documentation states responseType is a unioned type, however, this is incorrect.

### ISSUE THREAD

**Issue by JarvisJ** [angular/angular#21017]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently, the documentation states that the responseType property in the options argument of HttpClient.post (and other HttpClient methods) is of type "'arraybuffer' | 'blob' | 'json' | 'text'". This is incorrect as the responseType cannot be assigned to a variable of type "'arraybuffer' | 'blob' | 'json' | 'text'". Additionally, the documentation states that the post method returns an Observable&lt;any&gt;, which is also inaccurate.

## Expected behavior

To avoid confusion, the API documentation should better match the typings file. 

## Minimal reproduction of the problem with instructions

Read the HttpClient API documentation, then read it's typings file. The documentation is misleading and incomplete.

## What is the motivation / use case for changing the behavior?

I ran into an error trying to assign a variable of type "'json'|'arraybuffer'" to responseType. When I looked at the API, I assumed that upgrading angular to the most recent beta would make the issue go away. Better, accurate, documentation would have allowed me to resolve this issue faster.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by alxhub** [comment]
Can you give a code example you think should work, but doesn't?

**Comment by JarvisJ** [comment]
`  return this.httpClient.post(url, body, {
            headers: this.authHeader(),
            withCredentials: true, 
            responseType: isJson? 'json': 'arraybuffer'
        });`

I get a compile error due to assigning a "'json' | 'arraybuffer'" to responseType. The API documentation makes it appear like this should work:

https://angular.io/api/common/http/HttpClient#post

However, the documentation is incorrect. I can only set it to 'json' (in which case it would return an Observable<T> or Observable<Object>, also not in the documentation), or 'arraybuffer', but not a ternary that could be either. Improved and accurate documentation would have led me to the correct solution faster, as well as a better understanding of the new http API.

**Comment by Bandito11** [comment]
I also had a related problem. When I try to add responseType to a options Object as so:
```
const httpOptions = {
headers: myHeaders,
responseType: 'json'
}
```

the error message in the console states that **responseType is not  a type of '"json"'**.

An example code would be something:

`this.http.put(url, body, httpOptions) //etc`

I had to go to the client.d.ts of the http in the **node_modules/@angular/yougetthepoint** folder and replace all of the variables types to string. 

When you write something like this:

```
options = {
responseType?:'json'
}
```
as a possible type (in the client.d.ts file) is expecting a **responseType** with a **_data type_** of **'json'** and not a possible value of **'json'**

**Comment by jbogarthyde** [comment]
@alxhub @igor 
Would it resolve this issue to add the following note to the Description of HttpClient?
https://angular.io/api/common/http/HttpClient#description

"This service is available as an injectable class, with methods to perform HTTP requests. Each request method has multiple signatures, and the return type varies based on the signature that is called (mainly the values of `observe` and `responseType`).
**Note that the value of `responseType` is a *String*, not a *union* (as the combined signature could imply). The value identifies the single data type of the response, and each data type is handled by a single overload version of the method.**

**Comment by jbogarthyde** [comment]
resolved by https://github.com/angular/angular/pull/32817
