### ISSUE TITLE
Angular.io documentation printer friendly or PDF.

### ISSUE THREAD

**Issue by nblavoie** [angular/angular#21012]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have difficulties reading on a computer screen. I would like to be able to print the Angular.io documentation as a PDF to take notes and highlight sentences to help me learn the framework.

## Expected behavior
It would be nice if, at least, the Angular.io documentation would be printer friendly or a link to download the must up to date PDF document.

## Minimal reproduction of the problem with instructions
Try to print a section of the documentation : it doesn't work. The menu is in the way, etc.

## What is the motivation / use case for changing the behavior?
Better learning tool.

## Environment
All.

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/19459

**Comment by nblavoie** [comment]
Ref. https://github.com/nblavoie/angular-documentation-pdf

**Comment by gkalpak** [comment]
FWIW, there is also a PR in progress to improve the print layout: #19651
