### ISSUE TITLE
How to know if the caps lock is on?

### ISSUE THREAD

**Issue by corali89** [angular/angular#21019]
## I'm submitting a...
[ X] Feature request

## Current behavior
I want to know is the caps lock is on or off

## Expected behavior
I want to know is the caps lock is on or off

## What is the motivation / use case for changing the behavior?
login pages, for type the password I want to let the user know that the caps lock is on

Angular version: 4

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
