### ISSUE TITLE
angular universal async platform hook

### ISSUE THREAD

**Issue by muradm** [angular/angular#21025]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
As explained in this [SO question](https://stackoverflow.com/questions/47820289/angular-universal-async-platform-hook) `BEFORE_APP_SERIALIZED` and `APP_INITIALIZER` hooks behave differently.
While former blocks on user provider, `BEFORE_APP_SERIALIZED` is not making it impossible to perform some something useful before server side rendering serialization.

## Expected behavior
Probably before rendering calls on `BEFORE_APP_SERIALIZED` providers should block. As it is seen from sources [packages/core/src/application_init.ts](https://github.com/angular/angular/blob/5.1.1/packages/core/src/application_init.ts) and [packages/platform-server/src/utils.ts](https://github.com/angular/angular/blob/5.1.1/packages/platform-server/src/utils.ts) they behave differently.

## Minimal reproduction of the problem with instructions
Example provided in mentioned SO question is simple enough to reproduce.

## What is the motivation / use case for changing the behavior?
Issue raised while trying to serialize application state on server and passing to browser via `TransferState`. I faced problem with Apollo client in general, but it is applicable for any asynchronous operation performed server side. Rendering process completes before any async operation initiated by application. 

## Environment
Angular version: 5.1.1 (latest at this moment)

For Tooling issues:
- Node version: v8.9.3
- Platform:  Linux

**Comment by Toxicable** [comment]
You're not meant to pass async functions to `BEFORE_APP_SERIALIZED` since it will not resolve or wait on them before serializing.
Why not just do your async operation at any point in your apps normal execution, for example in some constructor on ngOnInit ?
