### ISSUE TITLE
NgFactory and NgSummary import paths are incorrect

### ISSUE THREAD

**Issue by mrmeku** [angular/angular#21022]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

My example below is based off of the Angular Bazel Demo from Alex (https://github.com/alexeagle/angular-bazel-example) so keep that project in mind when interpreting the file paths below.

Take a look at the module load errors below. Despite these ngfactory files being generated within bazel-out/...

I have manually removed the bazel-out directory structure to reflect what the closure compiler considers to be the root directory of the application. There's two common themes in these import errors:
  1. The parent directory name angular_bazel_example is misinterpretted as being the root directory of the app. This directory is the parent of the WORSPACE file and should not have been included.
  2. All absolute import statements are missing the required leading '/' as required by the node module resolution algorithm. Without the prefix, the closure compiler tries to load a node_module with the path provided (which obviously doesn't exist).

/src/app.ngfactory.js:10: ERROR - Failed to load module "angular_bazel_example/src/hello-world/hello-world.module"
export { HelloWorldModule as HelloWorldModule_47 } from "angular_bazel_example/src/hello-world/hello-world.module";

/src/app.ngfactory.js:12: ERROR - Failed to load module "src/app"
import * as i1 from "src/app";

/src/app.ngfactory.js:15: ERROR - Failed to load module "angular_bazel_example/src/hello-world/hello-world.module"
import * as i4 from "angular_bazel_example/src/hello-world/hello-world.module";

/src/app.ngfactory.js:16: ERROR - Failed to load module "src/hello-world/hello-world.component.ngfactory"
import * as i5 from "src/hello-world/hello-world.component.ngfactory";

/src/app.ngfactory.js:17: ERROR - Failed to load module "angular_bazel_example/src/hello-world/hello-world.component"
import * as i6 from "angular_bazel_example/src/hello-world/hello-world.component";

/src/app.ngsummary.js:7: ERROR - Failed to load module "node_modules/@angular/common/common.ngsummary"
export { CommonModuleNgSummary as CommonModule_7NgSummary } from "node_modules/@angular/common/common.ngsummary";

/src/app.ngsummary.js:8: ERROR - Failed to load module "node_modules/@angular/core/core.ngsummary"
export { ApplicationModuleNgSummary as ApplicationModule_15NgSummary } from "node_modules/@angular/core/core.ngsummary";

/src/app.ngsummary.js:9: ERROR - Failed to load module "node_modules/@angular/platform-browser/platform-browser.ngsummary"
export { BrowserModuleNgSummary as BrowserModule_27NgSummary } from "node_modules/@angular/platform-browser/platform-browser.ngsummary";

/src/app.ngsummary.js:10: ERROR - Failed to load module "src/hello-world/hello-world.module.ngsummary"
export { HelloWorldModuleNgSummary as HelloWorldModule_47NgSummary } from "src/hello-world/hello-world.module.ngsummary";

/src/app.ngsummary.js:11: ERROR - Failed to load module "src/app"
import * as i0 from "src/app";

/src/app.ngsummary.js:12: ERROR - Failed to load module "src/app.ngfactory"
import * as i1 from "src/app.ngfactory";

/src/app.ngsummary.js:16: ERROR - Failed to load module "angular_bazel_example/src/hello-world/hello-world.module"
import * as i5 from "angular_bazel_example/src/hello-world/hello-world.module";

/src/app.ngsummary.js:17: ERROR - Failed to load module "node_modules/@angular/common/common.ngsummary"
import * as i6 from "node_modules/@angular/common/common.ngsummary";

/src/app.ngsummary.js:18: ERROR - Failed to load module "node_modules/@angular/core/core.ngsummary"
import * as i7 from "node_modules/@angular/core/core.ngsummary";

/src/app.ngsummary.js:19: ERROR - Failed to load module "node_modules/@angular/platform-browser/platform-browser.ngsummary"
import * as i8 from "node_modules/@angular/platform-browser/platform-browser.ngsummary";

/src/app.ngsummary.js:20: ERROR - Failed to load module "src/hello-world/hello-world.module.ngsummary"
import * as i9 from "src/hello-world/hello-world.module.ngsummary";

/src/hello-world/hello-world.component.ngfactory.js:7: ERROR - Failed to load module "src/hello-world/hello-world-styles.css.shim.ngstyle"
import * as i0 from "src/hello-world/hello-world-styles.css.shim.ngstyle";

/src/hello-world/hello-world.component.ngfactory.js:9: ERROR - Failed to load module "src/hello-world/hello-world.component"
import * as i2 from "src/hello-world/hello-world.component";

/src/hello-world/hello-world.component.ngsummary.js:7: ERROR - Failed to load module "src/hello-world/hello-world.component"
import * as i0 from "src/hello-world/hello-world.component";

/src/hello-world/hello-world.component.ngsummary.js:8: ERROR - Failed to load module "src/hello-world/hello-world.component.ngfactory"
import * as i1 from "src/hello-world/hello-world.component.ngfactory";

/src/hello-world/hello-world.module.ngfactory.js:8: ERROR - Failed to load module "src/hello-world/hello-world.module"
import * as i1 from "src/hello-world/hello-world.module";

/src/hello-world/hello-world.module.ngsummary.js:7: ERROR - Failed to load module "src/hello-world/hello-world.module"
import * as i0 from "src/hello-world/hello-world.module";

/src/hello-world/hello-world.module.ngsummary.js:8: ERROR - Failed to load module "src/hello-world/hello-world.component"
import * as i1 from "src/hello-world/hello-world.component";

/src/hello-world/hello-world.module.ngsummary.js:9: ERROR - Failed to load module "src/hello-world/hello-world.component.ngsummary"
import * as i2 from "src/hello-world/hello-world.component.ngsummary";

## Expected behavior

The ideal fix for this bug would be to use relative directory paths rather than absolute paths since then toolchains down the line (such as the closure compiler) don't have to be manually configured to use bazel-out/.../ as a root directory. 

Probably the easiest fix would be to put a leading '/' infront of the absolute file path to designate it as such while also investigating the bug which causes the parent directory name to be part of the import path.

## Minimal reproduction of the problem with instructions

Clone my version of Alex's repo
git clone git@github.com:mrmeku/angular-bazel-example.git
cd angular-bazel-example
bazel run @yarn//:yarn
bazel build //:bundle

## What is the motivation / use case for changing the behavior?

We want to realize ABC don't we? This bug is a blocker for that dream.

## Environment

<pre><code>
Angular version: 5.1.0

Others:
Bazel
</code></pre>

**Comment by alexeagle** [comment]
It seems like these sources are coming from devmode. In prodmode you'll get exactly the same import/export statements that appeared in the original TS sources.
(note that users could choose to `import {} from 'my_workspace/path/to/lib'` which might cause a problem here)

**Comment by mrmeku** [comment]
Alex and I talked offline and I convinced him that these are actually coming from the prodmode files. He thinks the correct way to solve this bug is to always prefix import paths with the workspace name and will attempt to fix the bug that way eventually

**Comment by alexeagle** [comment]
I do agree that a mix of import paths, some with workspace and some
without, is not desirable. Will have to find some time to repro and dig
into where we generate these imports.
