### ISSUE TITLE
./test.sh failing on clean ubuntu install

### ISSUE THREAD

**Issue by rfuhrer** [angular/angular#21020]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The test scripts fail on my fresh install of ubuntu.  Perhaps there's some steps missing from the DEVELOPER.MD?

## Expected behavior
Following the steps in DEVELOPER.MD should result in a completely working build environment

## Minimal reproduction of the problem with instructions
- Fresh install ubuntu on virtualBox VM
- install chrome
- install git
- install node (using 8.9.3)
- install yarn (1.3.2)
- using `/srv/git/` for the rest of the steps
- `git clone https://github.com/angular/angular.git angularMaster`
- `yarn install` - Works
- `./build.sh` - Works
- `./test.sh node` - Works but at the end it never kicks you back to the command prompt and just sits here forever until you hit ctrl+c
```
3721 specs, 0 failures, 2 pending specs
Finished in 185.126 seconds
EXIT: 0 <===== node dist/tools/cjs-jasmine -- @angular/**/*_spec.js @angular/compiler-cli/test/**/*_spec.js @angular/benchpress/test/**/*_spec.js
```
- `./test.sh browser` - Fires up a copy of chrome that says it's connected to karma but then sits there forever with this as the terminal output:
```
Compiling tools...
Watching: packages/tsconfig.json in /srv/git/angularMaster
=====> node_modules/.bin/tsc --emitDecoratorMetadata --project packages/tsconfig.json --watch
=====> node node_modules/karma/bin/karma start --no-auto-watch --port=9876 karma-js.conf.js
=====> node node_modules/karma/bin/karma start --no-auto-watch --port=9877 packages/router/karma.conf.js
EXIT: 1 <===== node node_modules/karma/bin/karma start --no-auto-watch --port=9876 karma-js.conf.js
1
(node:6060) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): 1
(node:6060) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
10:39:43 - Compilation complete. Watching for file changes.


------------------------------------------------------------------------------
=====> node node_modules/karma/bin/karma run karma-js.conf.js --port=9876
14 12 2017 10:39:44.117:ERROR [runner]: There is no server listening on port 9876
EXIT: 1 <===== node node_modules/karma/bin/karma run karma-js.conf.js --port=9876
1
```
- `./test.sh browserNoRouter` - pretty much the same as browser except it doesn't even launch chrome
```
Compiling tools...
Watching: packages/tsconfig.json in /srv/git/angularMaster
=====> node_modules/.bin/tsc --emitDecoratorMetadata --project packages/tsconfig.json --watch
=====> node node_modules/karma/bin/karma start --no-auto-watch --port=9876 karma-js.conf.js
EXIT: 1 <===== node node_modules/karma/bin/karma start --no-auto-watch --port=9876 karma-js.conf.js
1
(node:6524) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): 1
(node:6524) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
10:42:11 - Compilation complete. Watching for file changes.


------------------------------------------------------------------------------
=====> node node_modules/karma/bin/karma run karma-js.conf.js --port=9876
14 12 2017 10:42:12.253:ERROR [runner]: There is no server listening on port 9876
EXIT: 1 <===== node node_modules/karma/bin/karma run karma-js.conf.js --port=9876
1
```
- `./test.sh tools` - bails instantly:
```
Compiling tools...
/srv/git/angularMaster/dist/tools/tsc-watch/index.js:92
    throw new Error("unknown platform: " + platform);
    ^

Error: unknown platform: tools
    at Object.<anonymous> (/srv/git/angularMaster/dist/tools/tsc-watch/index.js:92:11)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
I tried resetting back to multiple releases (5.1.1, 5.0.5, 5.2.0-beta.0, etc.) and all give the exact same results

## Environment

<pre><code>
Angular version: 5.0+

Browser:
- [x] Chrome (desktop) version 63
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.3  
- Platform:  Ubuntu 17.10 

Others:

</code></pre>

**Comment by rfuhrer** [comment]
Just to add, I tried the Babel build even though build.sh was working for me (which installed the JDK as well) and still had the same results once I tried to run the tests.

**Comment by teh-skrud** [comment]
Experienced the same issue last week, while trying to publish a PR.

I was only able to fix `./test.sh browserNoRouter`, which I pinpointed to a "Error: EMFILE: too many open files, scandir" (probably after lauching it with --debug). Anyway, I simply followed the answer at https://askubuntu.com/questions/162229/how-do-i-increase-the-open-files-limit-for-a-non-root-user to augment the number of allowed opened files for my user.

**Comment by rfuhrer** [comment]
Thanks @teh-skrud , unfortunately that doesn't seem to be my problem.  I upped my open file limit and still had the same issue.  Running as `su` (which i believe should have an unlimited limit) didn't change anything.  Running with --debug didn't give any more information either.  My guess is there's something in the script that's not opening chrome properly for me. Maybe a new version of chrome broke this? no idea why 'tools' is broken though.  That kind of leads me to believe there's more wrong with the script than some chrome config.

**Comment by klauserber** [comment]
Hi, I have the same problem here:

- Fresh local install of ubuntu 17.10
- install chrome
- install git
- install node (using 8.9.4) via nvm
- install yarn (1.5.1)
- git clone git@github.com:klauserber/angular.git 5.2.x
- yarn install - Works
- ./build.sh - Works
- ./test.sh node - Works but at the end it never kicks you back to the command prompt and just sits here forever until you hit ctrl+c

./test.sh browser brings up a chrome browser:

![image](https://user-images.githubusercontent.com/9998995/37823670-781fb8f8-2e8a-11e8-9758-81683336d4d7.png)

... and the following output:

```
kerber@LT-57-EVO-LNX:~/git/angular$ ./test.sh browser
Compiling tools...
Watching: packages/tsconfig.json in /home/kerber/git/angular
=====> node_modules/.bin/tsc --emitDecoratorMetadata --project packages/tsconfig.json --watch
=====> node node_modules/karma/bin/karma start --no-auto-watch --port=9876 karma-js.conf.js
=====> node node_modules/karma/bin/karma start --no-auto-watch --port=9877 packages/router/karma.conf.js
EXIT: 1 <===== node node_modules/karma/bin/karma start --no-auto-watch --port=9876 karma-js.conf.js
1
(node:26835) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): 1
(node:26835) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
11:06:08 - Compilation complete. Watching for file changes.


------------------------------------------------------------------------------
=====> node node_modules/karma/bin/karma run karma-js.conf.js --port=9876
23 03 2018 11:06:08.962:ERROR [runner]: There is no server listening on port 9876
EXIT: 1 <===== node node_modules/karma/bin/karma run karma-js.conf.js --port=9876
1
```

Same as above with `./test.sh browserNoRouter` and `./test.sh tools`

**Comment by klauserber** [comment]
... in the karma debug tab it seems to be ok:

![bildschirmfoto vom 2018-03-23 11-28-37](https://user-images.githubusercontent.com/9998995/37824678-b2889a5c-2e8d-11e8-90e0-9dbf26fd01ed.png)

**Comment by gkalpak** [comment]
The part where the command does not exit is by design, since `./test.sh` will watch the files for changes and rerun the tests. The `UnhandledPromiseRejectionWarning` part is not expected and I can't reproduce it.

I just tried with latest master on Ubuntu 16.04, node: 8.10.0, yarn 1.5.1. Everything (`./test.sh browser/browserNoRouter/node/router`) works as expected (without warnings or errors) 😕 

`tools` is indeed not a valid platform any more. I submitted #22958 to update the error message and docs.

<sub>I feel like this should be closed, because (a) we are soon moving away from `test.sh` (afaict) and (b) I can't reproduce the issue :grin:</sub>

**Comment by rfuhrer** [comment]
If I have some time I'll try creating a new VM and running through the steps again and see what the result is now that 3 months have passed.

What might be nice though was if there was a "testForPullRequest" mode on the `test.sh` or whatever is taking its place.  This would just run all of the tests once and then spit out a "you're good to go!" or something at the end.  I was making a PR and the tests were working decently on Windows but I figured the couple weird things I was seeing would go away if I ran them in linux.  This lead me to creating this ticket when the linux experience was even worse than the windows one :)  All I wanted was an easy way to say "ok cool, I didn't break anything and can submit this PR" 

In other "making a PR isn't as fun as it should be" news ,it kind of sucks when your PR fixes a fundamental problem in Angular and then isn't looked at for 5 months :) (insert shameless plug for #20610)

Thanks for taking a look at this @gkalpak!

**Comment by klauserber** [comment]
ok, thank you for the quick reply.
it's working now for me, it was the open files limit like in @teh-skrud s post.

The trick was to add DefaultLimitNOFILE=xxx to /etc/systemd/user.conf & system.conf as described here:
https://superuser.com/questions/1200539/cannot-increase-open-file-limit-past-4096-ubuntu

And one more thing: a reboot is necessary

**Comment by smartsiva** [comment]
Any update on this of how to resolve.

**Comment by gkalpak** [comment]
https://github.com/angular/angular/issues/21020#issuecomment-375935567

**Comment by rfuhrer** [comment]
I finally had some spare time at work and tried this experiment again.  Using Ubuntu 18.04 in Virtual Box in Windows 10, and installed the latest everything.  After following what @klauserber posted it seems that my problem has gone away.

I'll close this issue now.  Thanks everyone!
