### ISSUE TITLE
FormGroup.patchValue should ignore null arrays

### ISSUE THREAD

**Issue by ShiftySituation** [angular/angular#21021]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Calling `formGroup.patchValue(someObject) ` when someObject has a null array value, patchValue is still trying to iterate the null value.

## Expected behavior

Should check for `null` before trying to run the iterative process.
The current implementation that allows null values in the array (ie; [null, 1234, null, 4433]) is not similar to this issue where the array value itself is null.
## Minimal reproduction of the problem with instructions

check the constructor of add.component.ts
[https://stackblitz.com/edit/angular-hewynt](https://stackblitz.com/edit/angular-hewynt)

## What is the motivation / use case for changing the behavior?

So the back-end response isn't forced to send an empty array.  

## Environment

<pre><code>
Angular CLI: 1.5.5
Node: 8.2.1
OS: win32 x64
Angular: 5.0.5

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by khylias** [comment]
Hi, I've got the same here. Have you a workaround for waiting a patch ?

**Comment by ShiftySituation** [comment]
I check the data for known arrays on the response.  If null, set it to [].  No real work-around.

**Comment by nirajkrz** [comment]
is there any update on this?

**Comment by Eivyses** [comment]
I'm waiting for update too

**Comment by hrschoch** [comment]
The same issue happens when patching a formGroup with a null value

**Comment by rodolfojnn** [comment]
While this is not solved, I am setting it as follows:

```
    this.frmMain.patchValue({
        ...res[0],
        someProperty: res[0].someProperty || {}
    });
```

**Comment by LittleFish19** [comment]
This issue was solved?

**Comment by wottpal** [comment]
This is such an obvious thing to fix. It's really annoying :(

**Comment by eduardosivd** [comment]
Is this on roadmap or what alternative route should we use?

**Comment by HitkoDev** [comment]
A "dirty fix" in case you really need this:

<details>
  <summary>⚠ This may break some stuff, use at own risk!</summary>

  ```ts
  import { NgModule } from '@angular/core'
  import { FormArray, FormGroup, FormsModule } from '@angular/forms'

  FormGroup.prototype.patchValue = function (value: { [key: string]: any }, options: { onlySelf?: boolean, emitEvent?: boolean } = {}): void {
      let keys: string[]
      try {
          keys = Object.keys(value)
      } catch (_e) {
          keys = []
      }
      keys.forEach(name => {
          if (this.controls[name]) {
              this.controls[name].patchValue(value[name], { onlySelf: true, emitEvent: options.emitEvent })
          }
      })
      this.updateValueAndValidity(options)
  }

  FormArray.prototype.patchValue = function (value: any[], options: { onlySelf?: boolean, emitEvent?: boolean } = {}): void {
      value?.forEach?.((newValue: any, index: number) => {
          if (typeof index === 'number' && this.at(index)) {
              this.at(index).patchValue(newValue, { onlySelf: true, emitEvent: options.emitEvent })
          }
      })
      this.updateValueAndValidity(options)
  }

  @NgModule({
      imports: [
          FormsModule
      ],
      exports: [
          FormsModule
      ]
  })
  export class FormsModuleFix { }
  ```
</details>

**Comment by SunilManthenaG01** [comment]
Do we have this on the roadmap yet?

**Comment by mistic100** [comment]
Here is a replacement to "patchValue" which call "reset" on groups and array when a null value is provided

```ts
safePatchValue(form: FormGroup | FormArray, value: any, options: any = {}) {
    Object.keys(value).forEach(name => {
        if (form.controls[name]) {
            if ((form.controls[name] instanceof FormGroup || form.controls[name] instanceof FormArray)) {
                if (isNil(value[name])) {
                    form.controls[name].reset();
                } else {
                    this.safePatchValue(form.controls[name], value[name], { onlySelf: true, emitEvent: options.emitEvent });
                }
            } else {
                form.controls[name].patchValue(value[name], { onlySelf: true, emitEvent: options.emitEvent });
            }
        }
    });
    form.updateValueAndValidity(options);
}
```

**Comment by AndrewKushnir** [comment]
Related PR: #21021.
