### ISSUE TITLE
TransferState before serialization hook

### ISSUE THREAD

**Issue by muradm** [angular/angular#21026]
## I'm submitting a...
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see 

## Current behavior
Currently, as per [packages/platform-server/src/transfer_state.ts](https://github.com/angular/angular/blob/5.1.1/packages/platform-server/src/transfer_state.ts) `ServerTransferStateModule` serializes state at very generic `BEFORE_APP_SERIALIZED` hook. There is no other which happens before `BEFORE_APP_SERIALIZED` so that user application would have chance to call `TransferState.set()` method to provide data for serialization.

Any attempts for user application to hook it self for the same `BEFORE_APP_SERIALIZED` event, ended up `serializeTransferStateFactory()` executed before user provided `BEFORE_APP_SERIALIZED`.

I.e. user application has no chance to serialize right before `serializeTransferStateFactory()`.

## Expected behavior
It would be good idea to provide specific hook like `BEFORE_APP_STATE_SERIALIZED`, so that user application will have chance to call `TransferState.set()` before state is actually serialized.

## What is the motivation / use case for changing the behavior?
While passing data from server side, especially asynchronously acquired, impossible to catch up with `ServerTransferStateModule`.

## Environment
Angular version: 5.1.1 (latest at this moment)

For Tooling issues:
- Node version: v8.9.3
- Platform: Linux

**Comment by Toxicable** [comment]
What's wrong with setting your state at any point in your apps normal execution, for example in some constructor on ngOnInit ?

**Comment by muradm** [comment]
@Toxicable, very simplified to:
```
// some where global not Angular, but same process
export function maybeServerSideOnlyTokenRefresh(): Promise<string> { /* do web-service / db / etc */ }

export const ACCESS_TOKEN_KEY = makeStateKey('ACCESS_TOKEN_KEY');

export function refreshAccessToken(req: Request, transferState: TransferState) {
  doServerSideOnlyTokenRefresh().then(token => {
    if (token != null) transferState.set(ACCESS_TOKEN_KEY, token);
  ]);
}

@NgModule({
  // ...
  providers: [
    {provide: BEFORE_APP_SERIALIZED, useFactory: refreshAccessToken, deps[REQUEST, TransferState], multi: true}
  ]
  // ...
})
export class ServerAppModule {}
```
Then browser checks if there is a refreshed access token in state from server like:
```
export const INIT_ACCESS_TOKEN = 'ACCESS_TOKEN_KEY';
export function initAccessToken(transferState: TransferState): string {
  let initAccessToken = transferState.get(ACCESS_TOKEN_KEY, null);
  if (initAccessToken == null) {
    initAccessToken = localStorage.get('ACCESS_TOKEN_KEY');
  }
  return initAccessToken;
}

@NgModule({
  // ...
  providers: [
    {provide: INIT_ACCESS_TOKEN, useFactory: initAccessToken, deps[TransferState]}
  ],
  // ...
})
export class BrowserAppModule {}
```

Whatever I do, my `BEFORE_APP_SERIALIZED` functions are executed after the `TransferState's`, so I don't get data in browser.

**Comment by Toxicable** [comment]
@muradm why do you need to use `BEFORE_APP_SERIALIZED` to do this?
Just do it at a normal point in your apps lifecycle.

**Comment by PaulKujawa** [comment]
We need to shift DOM elements from `head` to `body`. Using `BEFORE_APP_SERIALIZED` we have a document object instead of `renderModuleFactory`'s string return to do so. 

This works, until TransferState is used, as no function provided for that token seems to be called anymore.

**Comment by CaerusKaru** [comment]
I'm closing this since there is no real resolution. As @Toxicable mentioned, the correct procedure is to do any manipulation/setting during the normal app lifecycle.
