### ISSUE TITLE
ng build with prod flag take too much with AWS t2.micro 

### ISSUE THREAD

**Issue by Pankaj-Pippin** [angular/angular#21035]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When we build for --prod in AWS EC2 t2.micro 1 GB having 2 GB of SWAP
It took up to 7 hr to build the app , build time vary from 2hr to 7 hr, with same codebase

Flag we tried to build app
1. ng build   --prod -> take 2 hr to 7 hr build 
2. ng build  --target=production --environment=qa -> take 2 hr to 7 hr build 
3. ng build -e dev -> take 1 min to build 

It always stuck on 92% chunk asset optimization and 95% emitting

We tried with 
1. npm clear cache,
2. restarting the server
3. deleted the folder and deployed it again 

Still not able to understand why some time it take 7hr to build and some time it take 2 hr .

If we update it to t2.medium then it take 2 min to build, so it may related to memory issues but there should be some reason for 2hr to 7hr build

## Expected behavior

should take 20 min max build time and consistent time ranging 2 hr to 7hr is really not understanble

## Minimal reproduction of the problem with instructions

try to build with flag 

ng build   --prod in t2 micro instance 

## Environment

Your global Angular CLI version (1.4.2) is greater than your local
version (1.2.4). The local Angular CLI version is used.

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.10.3 
- Platform: Amazon Linux t2.micro

Others:

**Comment by kemsky** [comment]
Micro instance is virtual machine with CPU throttling, nodejs is single threaded and as a result it is very very slow in such case. I ran into the same issue on VMware, when host power policy was set to power saving effectively limiting clock speed. The partial way to optimize this is to use Closure Compiler (java version,  which can use multiple cores and threads) instead of uglify in anular cli, but it still will be slow.

**Comment by alxhub** [comment]
Please open this issue in the github.com/angular/angular-cli repo, thanks!

**Comment by gwasky** [comment]
Was having this issue on a t2.micro running ubuntu 16. using cli 7, resolved by enabling swap and set it to 3GB.
Build is not under a minute

**Comment by majidkhan138** [comment]
create swap

sudo /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
sudo /sbin/mkswap /var/swap.1
sudo chmod 600 /var/swap.1
sudo /sbin/swapon /var/swap.1

If you need more than 1024 then change that to something higher.

To enable it by default after reboot, add this line to /etc/fstab:

/var/swap.1   swap    swap    defaults        0   0

ng build --prod --build-optimizer=false

Help me solve the problem on t2.micro ,, max time 2 minutes

<img width="621" alt="Screen Shot 2019-07-26 at 4 27 53 PM" src="https://user-images.githubusercontent.com/34721169/61948841-5f5da680-afc2-11e9-803d-230f7cf2d72a.png">
