### ISSUE TITLE
Angular webpack tutorial error

### ISSUE THREAD

**Issue by javifm86** [angular/angular#21038]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Downloading [webpack zip](https://angular.io/generated/zips/webpack/webpack.zip) from [Webpack tutorial](https://angular.io/guide/webpack) section is not showing the message "Hello from Angular App with Webpack". Just loading.

## Expected behavior

See "Hello from Angular App with Webpack".

## Minimal reproduction of the problem with instructions

```
npm install
npm start
```

## What is the motivation / use case for changing the behavior?

Starting an Angular project from scratch with Webpack.

## Environment

Browser:
- [X] Chrome (desktop) Versión 63.0.3239.84 (Build oficial) (64 bits)
 
For Tooling issues:
- Node version: v8.9.0
- Platform:  Windows 10

</code></pre>

**Comment by gkalpak** [comment]
The webpack guide is obslolete and will be removed soon. See https://github.com/angular/angular/pull/20199#issuecomment-342078147.
