### ISSUE TITLE
Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by fashiontai** [angular/angular#21037]
The HTTP example is wrong；
The in-memory-data.service.ts have not .data
but hero.service.ts return response.json().data as Hero[];
lead to dashboard.component.ts Cannot read property 'slice' of undefined

**Comment by fashiontai** [comment]
resolve this problem 
remove response.json().data the .data
so The successful running

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/19659, 
 https://github.com/angular/angular/issues/19602
