### ISSUE TITLE
[aio] enforce API doc format in dgeni

### ISSUE THREAD

**Issue by vicb** [angular/angular#21034]
There should be a way to enforce basic API doc convention in dgeni.

For example:
- The first line should start with an uppercase letter and end with a ".",
- The first line should be a single sentence with a given max length,
- ... more convention to be defined with the doc team

This has been discussed with @IgorMinar 

Also it would be nice to integrate that with the GH bot from @ocombe so that we get can feedback on PRs.

**Comment by gkalpak** [comment]
:+1: for enforcing format.
(Not sure how bot integration is relevent though. It will be an error on CI, right?)

**Comment by ocombe** [comment]
It could be done by dgeni maybe? What do you think @petebacondarwin?

**Comment by petebacondarwin** [comment]
What would be the rules to enforce?

**Comment by petebacondarwin** [comment]
This could be done via dgeni in CI

**Comment by jenniferfell** [comment]
@petebacondarwin Does any of the recent API work address this? What remains?

**Comment by petebacondarwin** [comment]
The PR that is referenced put in place the ability to do this sort of thing. We need to decide on the exact rules and then implement them.

**Comment by petebacondarwin** [comment]
I think that we will never get round to implementing these rules, as it is clearly a very low priority, and we have coped for the last 7 years pretty well without.
