### ISSUE TITLE
Angular 4 throwing Cannot match any routes error with script tag in URL

### ISSUE THREAD

**Issue by CoryMortimer** [angular/angular#21032]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

With the route
<pre><code>
{ path: 'superhero/:id', component: HeroDetailComponent }
</code></pre>
navigating to this route with a script tag in the url such as
<pre><code>
superhero/<script>alert('test')</script>
</code></pre>
Will produce the below error
<pre><code>
Error: Cannot match any routes. URL Segment: ''test''
    at ApplyRedirects.noMatchError (router.js:1698)
    at CatchSubscriber.eval [as selector] (router.js:1663)
    at CatchSubscriber.error (catchError.js:105)
    at MapSubscriber.Subscriber._error (Subscriber.js:130)
    at MapSubscriber.Subscriber.error (Subscriber.js:104)
    at MapSubscriber.Subscriber._error (Subscriber.js:130)
    at MapSubscriber.Subscriber.error (Subscriber.js:104)
    at MapSubscriber.Subscriber._error (Subscriber.js:130)
    at MapSubscriber.Subscriber.error (Subscriber.js:104)
    at LastSubscriber.Subscriber._error (Subscriber.js:130)
    at ApplyRedirects.noMatchError (router.js:1698)
    at CatchSubscriber.eval [as selector] (router.js:1663)
    at CatchSubscriber.error (catchError.js:105)
    at MapSubscriber.Subscriber._error (Subscriber.js:130)
    at MapSubscriber.Subscriber.error (Subscriber.js:104)
    at MapSubscriber.Subscriber._error (Subscriber.js:130)
    at MapSubscriber.Subscriber.error (Subscriber.js:104)
    at MapSubscriber.Subscriber._error (Subscriber.js:130)
    at MapSubscriber.Subscriber.error (Subscriber.js:104)
    at LastSubscriber.Subscriber._error (Subscriber.js:130)
    at resolvePromise (zone.js:824)
    at resolvePromise (zone.js:795)
    at eval (zone.js:873)
    at ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4621)
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:192)
    at drainMicroTaskQueue (zone.js:602)
    at anonymous
</code></pre>

## Expected behavior

Navigating to
<pre><code>
superhero/<script>alert('test')</script>
</code></pre>
would successfully navigate to the page and not throw an error, as it does with any other invalid url.

## Minimal reproduction of the problem with instructions

On the [Routing & Navigation page](https://angular.io/guide/router), the [downloadable example](https://angular.io/generated/zips/router/router.zip) can reproduce this bug.

1. After downloading and extracting the zip, run npm install, then ng serve to boot up the example.
2. (Assuming the host is localhost:4200) In the address bar, type http://localhost:4200/superhero/11. This will show a page with superhero information
3. Type http://localhost:4200/superhero/nohero. This will still bring you to the superhero page (you can tell by the HEROES title) but will not display a hero
4. The issue is when you type http://localhost:4200/superhero/<script>alert('test')</script>. The stack trace will appear in the console and will not route to the superhero page

## What is the motivation / use case for changing the behavior?

The Angular web application should not throw errors when a user types a url it does not expect and instead allow the developer to decide what to do with the url.

## Environment

<pre><code>
Angular version: 5.0.5

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

I borrowed the name of this issue from the stackoverflow issue located here:
https://stackoverflow.com/q/45256834
</code></pre>

**Comment by vicb** [comment]
The / in /script would is interpreted as a url segment.

Closing as works as expected.

**Comment by CoryMortimer** [comment]
Thanks for the reply, @vicb.

From my understanding of your reply, the url 
<pre><code>
http://localhost:4200/superhero/<script>alert('test')</script>
</code></pre>
is being interpreted as 3 separate segments after the host: 
<pre><code>
superhero
<script>alert('test')<
script>
</code></pre>
That leads me to believe that another url such as
<pre><code>
http://localhost:4200/superhero/test/test2
</code></pre>
that is also interpreted as 3 segments:
<pre><code>
superhero
test
test2
</code></pre>
would produce the same results as the url with the script tag in it when they are both being navigated to.

In the example, the http://localhost:4200/superhero/test/test2 url navigates successfully to a page with the title "Page not found". The http://localhost:4200/superhero/<script>alert('test')</script> url does not navigate to a page and throws the above error in the console.

**Comment by trotyl** [comment]
@CoryMortimer Angular is using matrix URL and `(` ,`)` are separators for outlets, like:

```
/team/33;expand=true/(user/11//right:chat)
```

Just encode the parameter and make it valid URL would help.

**Comment by CoryMortimer** [comment]
Thanks for the help, @trotyl.
I guess I was not trying to get that specific url to work but more hoping that the Angular router would handle (such as going to the "Page not found" page in the example) whatever the user decided to type in the address bar, since the code
<pre><code>
{ path: '**', component: PageNotFoundComponent }
</code></pre>
is present in the app-routing.module in the example (which I am assuming would be sufficient to catch all routes that are not listed in the config, even if they are invalid).

**Comment by trotyl** [comment]
@CoryMortimer What if user types `superhero#foo?a=b#bar?baz=42`? Routing is not regex matching, it must be a valid URL first, then comes what does it mean.

**Comment by CoryMortimer** [comment]
@trotyl In the example, if the user type `http://localhost:4200/superhero#foo?a=b#bar?baz=42` it will redirect to the PageNotFoundComponent.

If I want to handle the case where the user can type anything into the address bar and successfully navigate to the Angular application and display a routed page, I need to account for this error being thrown (by implementing a custom ErrorHandler, or intercepting invalid urls before they get to the Angular application, or etc.). There is nothing in the Angular router that I can do to always route to a page. Are these statements correct?

**Comment by trotyl** [comment]
I mean there can be invalid syntax in URL, not talking about specific implementation, you can check [RFC](https://tools.ietf.org/html/rfc3986#section-2.2) for detail. If you want there to be a `URLParsingError` class for easier catching, then it would be a feature request instead.

**Comment by CoryMortimer** [comment]
Thanks @trotyl for your help and explanations. I will probably just cover the case during a NavigationError event.
