### ISSUE TITLE
routermodule in shared module

### ISSUE THREAD

**Issue by stepet80** [angular/angular#21045]
I have a SharedModule This shared module has a component with a template where I use [routerLink] attribute. The shared module doesn't define any route but needs to know about routing attributes/services so I can't use forRoot() or forChild().

I define the routes in the **AppModule** with the forRoot syntax.

`RouterModule.forRoot(appRoutes)`

If I import the RouterModule in the **SharedModule** I get an error:

TestComponent.html:1 ERROR Error: 
StaticInjectorError[Router]: 
  StaticInjectorError[Router]: 

`imports: [
        HttpClientModule, 
        CommonModule, 
        ButtonsModule,
        RouterModule]`

The question is how can i pass on the routes from the app module to the shared module. If I define a [routerlink] in a component of the shared module it needs to know about the routes of the appModule.

The shared module needs to know all the attributes/services of RouterModule and needs to know the routes of the app module.

If I just import RouterLink and add it to the shared module it doesn't seem to understand the routes of the app module.

Do I need to do something with a forRoot static method on the shared module?

Thanks

**Comment by alxhub** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
