### ISSUE TITLE
Service Worker start too late

### ISSUE THREAD

**Issue by fabienbranchel** [angular/angular#21043]
## I'm submitting a...
[ X ] Documentation issue or request
</code></pre>

## Current behavior
I use Angular with the internal Service Worker. This is my ngsw-config.json file : 

```json
{
  "appData": "Angular 5.1",
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "resources": {
        "files": ["/favicon.ico", "/index.html"],
        "versionedFiles": ["/*.bundle.css", "/*.bundle.js", "/*.chunk.js"]
      }
    },
    {
      "name": "assets",
      "installMode": "prefetch",
      "updateMode": "prefetch",
      "resources": {
        "files": ["/assets/**"]
      }
    }
  ],
  "dataGroups": [
    {
      "name": "tasks-users-api",
      "urls": ["/api"],
      "cacheConfig": {
        "strategy": "freshness",
        "maxSize": 20,
        "maxAge": "1h",
        "timeout": "5s"
      }
    }
  ]
}
```

In ngOnInit function of my homepage, I call the /api url listed in dataGroups. When I open my console, I can see this url is call (framed in red below) before the start of the service worker (I guess the start of the service worker matches with the element framed in blue below).

<img width="541" alt="capture d ecran 2017-12-13 a 18 30 46" src="https://user-images.githubusercontent.com/23743473/34044276-9e8dfaa0-e1a4-11e7-97fa-77a4fbd1c8c5.png">

So, if I switch off my internet connection, the /api call isn't handle by the service worker. If I navigate on another page and come back to the homepage before switch off my connection, the /api call is handle by service worker.

Is there a way to start the SW before the api call ?

## Expected behavior
Caching all the data.

## Minimal reproduction of the problem with instructions
1. Setup a SW
2. Call a webservice in the ngOnInit of the homepage component

## What is the motivation / use case for changing the behavior?
Caching the data of webservice called on the homepage, the first time.

## Environment
Output from: ng --version.
<pre><code>
Angular CLI: 1.6.0
Node: 6.11.3
OS: darwin x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cdk: 5.0.0
@angular/cli: 1.6.0
@angular/material: 5.0.0
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.10.0

Browser:
- [ X ] Chrome (desktop) version 63.0.3239.84
 
For Tooling issues:
- Node version: 6.11.3
- Platform:  Mac

</code></pre>

**Comment by alxhub** [comment]
Service Workers are persistent in your browser. We intentionally delay the installation of the SW until your application is started & stable, to avoid conflicting with the initial page load and slowing it down.

Once the SW is installed and running, it should cache any API requests normally. The next time you open the application, the SW will handle them.

**Comment by fabienbranchel** [comment]
Okay, I understand. 
Anyway, is there a way to observe the start of SW  ? I've got some services to call in my homepage, they are not absolutely necessary at the start - they could easily wait few seconds, and I would prefer to call them when they can be cache.
