### ISSUE TITLE
Service worker does not clear old cached values

### ISSUE THREAD

**Issue by AlexSte** [angular/angular#21044]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Service worker does not delete old cached values from cache after receiving new version.

## Expected behavior
Old cached values were cleared while update.

## Minimal reproduction of the problem with instructions
Deploy any application with service worker and open in browser.
Deploy second version of this application. Reopen application to receive new version.
Look at Cache Storage...

## What is the motivation / use case for changing the behavior?
After couple updates cache storage will use a big amount of space.

## Environment
<pre><code>
Angular version: 5.0.0

Browser:
- [x ] Chrome (desktop) version 63
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.1
- Platform: Windows 
</code></pre>

**Comment by alxhub** [comment]
The SW cleans its caches on SW restart (which won't happen if you have DevTools open). Go into the SW tab in DevTools, stop the worker, then start it, wait a few seconds, and check Cache Storage (be sure to right click and refresh it). The older caches should be gone.

**Comment by mackelito** [comment]
@alxhub sorry.. I know this is closed long ago and all but I'm trying to find out how I can stop/start the sw when our users logout but It' s nowhere to be found?.. any pointers?
