### ISSUE TITLE
navigate does not work after logged in

### ISSUE THREAD

**Issue by nimatullah** [angular/angular#21057]
my code:

`login.component.ts`

```
import { configuration } from './../../../../environments/.env';
import { Token } from './../../authentication/token.model';
import { AuthenticationService } from './../../authentication/authentication.service';
import { Component, OnInit } from "@angular/core";
import { SettingsService } from "../../../core/settings/settings.service";
import { FormGroup, FormBuilder, Validators } from "@angular/forms";
import { CustomValidators } from "ng2-validation";
import { Router, ActivatedRoute } from "@angular/router";
import { TokenService } from "../../authentication/token.service";
import { environment } from '../../../../environments/environment';

@Component({
  selector: "app-login",
  templateUrl: "./login.component.html",
  styleUrls: ["./login.component.scss"]
})
export class LoginComponent implements OnInit {
  valForm: FormGroup;
  returnUrl: string;
  loginFailed: boolean = false;
  failedMessage: string = 'Error: Username or password is incorrect';
  token: Token
  constructor(
    public settings: SettingsService,
    private fb: FormBuilder,
    private router: Router,
    private route: ActivatedRoute,
    private tokenService: TokenService,
    private authentication: AuthenticationService
  ) {
    this.token = this.tokenService.getToken();
  }

  /**
     * Login using email and password
     *
     * @param $ev
     * @param value
     */
  login($ev, value: any) {
    $ev.preventDefault();
    for (let c in this.valForm.controls) {
      this.valForm.controls[c].markAsTouched();
    }
    if (this.valForm.valid) {
      this.authentication.login(value.email, value.password).subscribe(response => {
         this.loginFailed = false;
          if (response && response.token) {
            if (response.user.userType !== 'admin') {
              this.failedMessage = 'You are not admin user';
              this.loginFailed = true;
            } else {
             localStorage.setItem('token', response.token);
             localStorage.setItem('refresh_token', response.refreshToken);
              setTimeout(() => {
                if (environment.production === true) {
                  // alert(this.returnUrl);
                  (window as any).location.href = configuration.SOCKET_URL +'/admin/#'+ this.returnUrl;
                } else {
                  // alert(this.returnUrl);
                  (window as any).location.href = `${this.returnUrl}`;
                }
              },500);
            }
          }
      },error => {
        this.failedMessage= JSON.parse(error._body);
        this.loginFailed = true;
      }
    );
    }
  }



  /**
   * Check if user is logged
   */
  isLoggedIn() {

    if (this.token && !this.token.isExpired() && this.token.getUserType() === 'admin') {
      this.router.navigate([this.returnUrl]);
    } 
    if (this.token && this.token.getUserType() !== 'admin') {
        this.tokenService.removeToken();
    }
  }

  ngOnInit() {
    this.returnUrl = this.route.snapshot.queryParams["returnUrl"] || "/user";
    this.isLoggedIn();
    this.valForm = this.fb.group({
      email: [
        null,
        Validators.compose([Validators.required, CustomValidators.email])
      ],
      password: [null, Validators.required],
      account_remember: [""]
    });
  }
}
```

`routes.ts`

```
export const routes = [
  {
    path: "",
    component: LayoutComponent,
    canActivate: [AuthenticationGuard],
    children: [
      { path: "", redirectTo: "user", pathMatch: "full" },
      {
        path: "user",
        data: { name: "Users" },
        loadChildren: "./user/user.module#UsersModule"
      },
      {
        path: "packages",
        data: { name: "Packages" },
        loadChildren: "./package/package.module#PackageModule"
      },
      {
        path: "subscriptions",
        data: { name: "Transactions" },
        loadChildren: "./subscription/subscription.module#SubscriptionModule"
      },
      {
        path: "jobs",
        data: { name: "Jobs" },
        loadChildren: "./jobs/jobs.module#JobsModule"
      },
      {
        path: "reportedResources",
        data: { name: "Reported Resources" },
        loadChildren:
          "./reported-resources/reported-resources.module#ReportedResourcesModule"
      },
      {
        path: "reporting",
        data: { name: "Reporting" },
        loadChildren: "./reporting/reporting.module#ReportingModule"
      },
      {
        path: "ads",
        data: { name: "Ads" },
        loadChildren: "./ads/ads.module#AdsModule"
      },
      {
        path: "session",
        data: { name: "Sessions" },
        loadChildren: "./session/session.module#SessionModule"
      },
      {
        path: "inbox",
        data: { name: "Inbox" },
        loadChildren: "./inbox/inbox.module#InboxModule"
      },
      {
        path: "masterData/unapproved",
        data: { name: "Unapproved" },
        loadChildren: "./master-data/unapproved/unapproved.module#UnapprovedModule"
      },
      {
        path: "masterData/approved",
        data: { name: "Approved" },
        loadChildren: "./master-data/approved/approved.module#ApprovedModule"
      },
      {
        path: "profile-verification-request",
        data: { name: "Profile Verification Request" },
        loadChildren:
          "./profile-verification-request/profile-verification-request.module#ProfileVerificationRequestModule"
      },
      {
        path: "settings",
        data: { name: "Settings" },
        loadChildren: "./settings/settings.module#SettingModule",
        component: SettingComponent
      },
      {
        path: "generalSearch",
        data: { name: "General Search" },
        loadChildren: "./general-search/general-search.module#GeneralSearchModule",
        component: GeneralSearchComponent
      },
      {
        path: "feedbacks",
        data: { name: "Feedbacks" },
        loadChildren: "./feedbacks/feedback.module#FeedbackModule"
      },
      {
        path: "bankAccounts",
        data: { name: "Bank Accounts" },
        loadChildren: "./bank-accounts/bank-account.module#BankAccountModule"
      },
      {
        path: "companyStatements",
        data: { name: "Company Statements" },
        loadChildren: "./company-statement/company-statement.module#CompanyStatementModule"
      },
      {
        path: 'exchangeRate',
        data: { name: "Exchange Rate" },
        loadChildren: "./exchange-rate/exchange-rate.module#ExchangeRateModule"
      },
      {
        path: "searchResult",
        component: ShowSearchResultComponent,
        data: { name: "Search Result View" }
      },
      {
        path: "companies",
        data: { name: "Active Company" },
        loadChildren: "./company/company.module#CompanyModule"
      },
      { path: "logout", component: LogoutComponent }
    ]
  },

  // Not lazy-loaded routes
  { path: "login", component: LoginComponent, resolve: [IsLoggedIn] },

  { path: "recover", component: RecoverComponent },
  { path: "lock", component: LockComponent },
  { path: "maintenance", component: MaintenanceComponent },
  { path: "500", component: Error500Component },
  // { path: "**", component: Error404Component },

  // Not found
  { path: "**", redirectTo: "user" }
];

```
## My issue

1. Local:  It works fine if url does not have query params, it redirec to `/user ` routes.
2. Local: It does not work if `url` has query params.
3. In production the navigate does not work in both the above cases.

## Environment

<pre><code>
Angular version: 4.4.4

For Tooling issues:
- Node version:  v9.2.0
- Platform:  Linux

`package.json`
{
  "dependencies": {
    "@angular/animations": "^4.4.4",
    "@angular/common": "^4.4.4",
    "@angular/compiler": "^4.4.4",
    "@angular/core": "^4.4.4",
    "@angular/forms": "^4.4.4",
    "@angular/http": "^4.4.4",
    "@angular/platform-browser": "^4.4.4",
    "@angular/platform-browser-dynamic": "^4.4.4",
    "@angular/platform-server": "^4.4.4",
    "@angular/router": "^4.4.4",
    "@angularclass/hmr": "~2.1.3",
    "@angularclass/hmr-loader": "~3.0.2",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.5",
    "@types/file-saver": "0.0.1",
    "@types/jquery": "^3.2.13",
    "@types/socket.io-client": "^1.4.31",
    "ag-grid": "^13.3.1",
    "ag-grid-angular": "^13.3.0",
    "angular2-infinite-scroll": "^0.3.43",
    "angular2-moment": "^1.7.0",
    "angular2-prettyjson": "^2.0.5",
    "angular2-text-mask": "^8.0.4",
    "angular2-toaster": "^4.0.1",
    "angular2-tree-component": "^3.1.0",
    "angular2-ui-switch": "^1.2.0",
    "angular2-wizard": "^0.4.0",
    "binary-pack": "^1.0.2",
    "bootstrap": "^3.3.6",
    "buffer": "^5.0.8",
    "chart.js": "^2.5.0",
    "codemirror": "^5.30.0",
    "core-js": "^2.4.1",
    "dotenv": "^4.0.0",
    "duplex": "^1.0.0",
    "easy-pie-chart": "^2.1.7",
    "file-saver": "^1.3.3",
    "flot": "^0.8.0-alpha",
    "font-awesome": "^4.7.0",
    "fullcalendar": "^3.2.0",
    "http-server": "^0.10.0",
    "ie-shim": "^0.1.0",
    "izitoast": "1.1.5",
    "jqcloud2": "^2.0.2",
    "jquery": "^3.2.1",
    "jquery-slimscroll": "^1.3.8",
    "jquery-sparkline": "^2.4.0",
    "jquery.browser": "^0.1.0",
    "jquery.flot.tooltip": "github:krzysu/flot.tooltip",
    "jsonpath-plus": "^0.16.0",
    "lodash": "^4.17.4",
    "modernizr": "^3.3.1",
    "moment": "^2.17.1",
    "monaco-editor": "^0.10.0",
    "ng-formly": "^1.0.0-rc.4",
    "ng-formly-tb": "github:eisa-netlinks/ng-formly",
    "ng2-accordion": "0.0.15",
    "ng2-bootstrap": "1.4.0",
    "ng2-bootstrap-modal": "^1.0.1",
    "ng2-charts": "^1.5.0",
    "ng2-dnd": "^4.2.0",
    "ng2-file-upload": "^1.2.0",
    "ng2-image-lazy-load": "^2.0.9",
    "ng2-imageupload": "^1.4.2",
    "ng2-img-cropper": "^0.9.0",
    "ng2-modal": "0.0.25",
    "ng2-pagination": "^2.0.1",
    "ng2-select": "^1.2.0",
    "ng2-simple-autocomplete": "^0.5.2",
    "ng2-tag-input": "^1.4.1",
    "ng2-translate": "^5.0.0",
    "ng2-validation": "^4.2.0",
    "ngx-bootstrap": "^1.9.3",
    "ngx-infinite-scroll": "^0.5.2",
    "ngx-uploader": "4.0.0",
    "node-sass": "^4.5.0",
    "primus": "^7.1.0",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.1.0",
    "screenfull": "^3.0.2",
    "simple-line-icons": "^2.4.1",
    "socket.io-client": "^2.0.4",
    "spinkit": "^1.2.5",
    "strong-pubsub": "^0.2.0",
    "strong-pubsub-bridge": "^0.2.1",
    "strong-pubsub-connection-mqtt": "^0.1.2",
    "strong-pubsub-mqtt": "^0.1.0",
    "summernote": "^0.8.2",
    "ts-helpers": "^1.1.2",
    "underscore": "^1.8.3",
    "weather-icons": "1.3.2",
    "whirl": "github:jh3y/whirl",
    "zone": "^0.3.4",
    "zone.js": "^0.8.18",
    "zxcvbn": "^4.4.2"
  },
  "devDependencies": {
    "@angular/cli": "1.4.7",
    "@angular/compiler-cli": "^4.4.4",
    "@swimlane/ngx-datatable": "^10.2.3",
    "@types/codemirror": "0.0.48",
    "@types/hammerjs": "^2.0.34",
    "@types/jasmine": "2.6.0",
    "@types/lodash": "^4.14.77",
    "@types/moment": "2.13.0",
    "@types/node": "^8.0.34",
    "@types/source-map": "^0.5.0",
    "@types/uglify-js": "^2.6.28",
    "@types/underscore": "^1.8.0",
    "@types/webpack": "^3.0.13",
    "add-asset-html-webpack-plugin": "^2.1.2",
    "angular2-template-loader": "^0.6.2",
    "assets-webpack-plugin": "^3.5.1",
    "awesome-typescript-loader": "~3.2.3",
    "base-href-webpack-plugin": "^1.0.2",
    "codelyzer": "~3.2.1",
    "copy-webpack-plugin": "^4.1.1",
    "cross-env": "^5.0.0",
    "css-loader": "^0.28.0",
    "exports-loader": "^0.6.4",
    "expose-loader": "^0.7.3",
    "extract-text-webpack-plugin": "~3.0.1",
    "file-loader": "^1.1.5",
    "find-root": "^1.0.0",
    "gh-pages": "^1.0.0",
    "html-webpack-plugin": "^2.28.0",
    "imports-loader": "^0.7.1",
    "inline-manifest-webpack-plugin": "^3.0.1",
    "istanbul-instrumenter-loader": "3.0.0",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "json-loader": "^0.5.4",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage": "^1.1.1",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-mocha-reporter": "^2.2.3",
    "karma-read-json": "^1.1.0",
    "karma-remap-coverage": "^0.1.4",
    "karma-remap-istanbul": "^0.6.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^2.0.5",
    "loaders.css": "^0.1.2",
    "napa": "^3.0.0",
    "ng-router-loader": "^2.1.0",
    "ngc-webpack": "~3.2.2",
    "node-sass": "^4.5.3",
    "npm-run-all": "^4.0.2",
    "optimize-js-plugin": "0.0.4",
    "parse5": "^3.0.2",
    "preload-webpack-plugin": "^2.0.0",
    "protractor": "~5.1.0",
    "raw-loader": "0.5.1",
    "rimraf": "~2.6.1",
    "sass-loader": "^6.0.3",
    "script-ext-html-webpack-plugin": "^1.7.1",
    "script-loader": "^0.7.2",
    "source-map-loader": "^0.2.2",
    "string-replace-loader": "~1.3.0",
    "style-loader": "^0.19.0",
    "to-string-loader": "^1.1.5",
    "ts-node": "~3.3.0",
    "tslib": "^1.6.1",
    "tslint": "~5.7.0",
    "tslint-loader": "^3.5.2",
    "typedoc": "^0.9.0",
    "typescript": "^2.5.3",
    "url-loader": "^0.6.2",
    "webdriver-manager": "12.0.6",
    "webpack": "^3.1.0",
    "webpack-dev-middleware": "^1.10.1",
    "webpack-dev-server": "^2.9.1",
    "webpack-dll-bundles-plugin": "^1.0.0-beta.5",
    "webpack-merge": "~4.1.0"
  }
}
</code></pre>

**Comment by jotatoledo** [comment]
DONT use the issue tracker for troubleshooting.

**Comment by alxhub** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
