### ISSUE TITLE
White-space should always be preserved in a <pre> tag

### ISSUE THREAD

**Issue by Malvolio** [angular/angular#21050]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If you have a `<pre>` tag in your template, your choices are

1. specify `preserveWhitespaces: true` in your @Component and preserve the whitespace in the _entire_ template, and that's if you remember, or 
2. forget and specify `preserveWhitespaces: false` in your @Component and have the `<pre>` tag basically not work.

## Expected behavior

Even if `preserveWhitespaces: false` in the @Component, whitespace in the `<pre>` tag should be preserved

## Minimal reproduction of the problem with instructions

N/A

## What is the motivation / use case for changing the behavior?

Outside of a `<pre>` tag, most of the time you do not want to preserve whitespaces
Inside of a `<pre>` tag, most of the time you do.  Adopting this change would allow the default behavior to be the correct behavior.

## Environment

<pre><code>
Angular version: 4.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
@Malvolio could you please provide a minimal reproduce scenario? We _Are_ preserving ws inside `<pre>` tags and got tests to prove it:  https://github.com/angular/angular/blob/0b2d636b75d69e17bff2eb875181a2a6242e1abb/packages/compiler/test/ml_parser/html_whitespaces_spec.ts#L100-L109

**Comment by Malvolio** [comment]
Cunningham's Law...
