### ISSUE TITLE
Angular NgFor elements not rendering in Safari (10.1.2) and iOS browsers

### ISSUE THREAD

**Issue by Hisairnessag3** [angular/angular#21067]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Elements in the ngFor bindings do not properly render on Safari for iOS and android.
## Expected behavior

Proper rendering of elements.
## Minimal reproduction of the problem with instructions

as you can see I have the required polyfills
live website: [trumpfreenews.co](url)

Code: 

home.component.ts
```
this.feedservice.getFeedContent2(this.feedUrl)
    .subscribe(
    feed =>{
  if (this.notrumpcookie == 'yes'){
  this.field = feed.items.filter(feed=> feed.content.indexOf(substring) !== -1) 
  this.trumpContent = feed.items.filter(item=> this.field.indexOf(item) < 0) 
  this.feeds = this.trumpContent;
  }else if(this.sometrumpcookie == 'yes'){
    this.small = feed.items.filter(feed=> feed.title.indexOf(substring) !== -1) 
  this.trumpTitle = feed.items.filter(item=> this.small.indexOf(item) < 0)
  this.feeds = this.trumpTitle;
}else{
  this.feeds = feed.items;
}

},
 error => console.log(error));
}
```

home.component.html

```
<app-feed-card2 *ngFor="let feed of feeds2 | slice:1:2" [feed]="feed" ></app-feed-card2>
<h1> TOP STORIES </h1>
<div class="jumbotron">
<app-feed-card *ngFor="let feed of feeds" [feed]="feed" ></app-feed-card>
</div>
<div id="fries"></div>
<trump-slider></trump-slider>

```

index.html

```
<!DOCTYPE html>
<html>

<head>
  <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en"></script>

```

polyfills.ts
```

import 'core-js/es7/reflect';

import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';
import 'intl';
import 'intl/locale-data/jsonp/en';

```

safari view:
 
![screen shot 2017-12-16 at 5 37 35 pm](https://user-images.githubusercontent.com/25183305/34075612-8ad568cc-e299-11e7-8d49-ffcafdc28059.png)

chrome view:

![screen shot 2017-12-16 at 5 38 09 pm](https://user-images.githubusercontent.com/25183305/34075617-932bdc4a-e299-11e7-9534-6b5bf4ac4929.png)

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [X] Safari (desktop) version XX
- [X] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Mac OS X: 10.12.6
node: 8.9.2

Others:

</code></pre>

**Comment by Hisairnessag3** [comment]
Still having issue with latest update to 5.1.1

**Comment by chuckjaz** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists please open a new issue following [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue).

**Comment by Hisairnessag3** [comment]
Um, I find it pretty hard to believe you tried to reproduce this but here is the new issue: https://github.com/angular/angular/issues/21099
