### ISSUE TITLE
Type 'RequestOptions' is not assignable to type 'Request'.     Property 'cache' is missing in type 'RequestOptions'.

### ISSUE THREAD

**Issue by RanaSinghRaj** [angular/angular#21069]
![posterror](https://user-images.githubusercontent.com/30930131/34077102-4289557e-e320-11e7-969b-c18e2612d970.PNG)

protected submitDepartment(data: any) {
  let _body = JSON.stringify(data);
  let headers = new Headers({ 'Content-Type': 'application/json;charset=utf-8' });

  let requestoptions: RequestOptions = new RequestOptions({
      method: RequestMethod.Post,
      url: this.baseurl + 'SaveMenuField',
      headers: headers,
      body: _body
  })

  return this.http.request(new Request(requestoptions))
      .map((res: Response) => { return res.json(); });
}

**Comment by jotatoledo** [comment]
DONT use the issue tracker for troubleshooting

**Comment by alxhub** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
