### ISSUE TITLE
Add multiple items with  type="number" in Lifecycle Hooks 

### ISSUE THREAD

**Issue by malikfaizanhaider** [angular/angular#21061]
[Add multiple items with input type="number" in Lifecycle Hooks! any documentation?  ] Documentation request

**Comment by alxhub** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a plunker reproducing the problem and describing the difference between the expected and current behavior. You can use this plunker template: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue
