### ISSUE TITLE
Application fails to load in IE 11 due to registry entry "NoNavButtons"

### ISSUE THREAD

**Issue by prasadmamidi7** [angular/angular#21062]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[  ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Angular 5 application does not load if it is configured with routes information in IE 11 when following registry entry is set to true

"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Internet Explorer\Restrictions\NoNavButtons". which was set to 1.

## Expected behavior
Application shall be launched regardless of whether the mentioned registry entry is set or not. Or sort of switch which will disable of pushing of url information state in window.history object.

## Minimal reproduction of the problem with instructions
Create a sample application with angular cli 1.6.0
Make sure your define some route configuration
Build with --prod switch
Try to launch the application in IE 11 on win 10

## What is the motivation / use case for changing the behavior?
This has become a major blocker for our application as most of our applications
-  Are targeted to the healthcare domain and it is a risk if we enable the navigation buttons.
- Are targeted for IE 11 on win 10
- All of them are not like usual website app for public , but they are specifically used inside the hospital environment
- Most of the times the applications are lunched on the machine whether it is deployed and mentioned registry entry is set to true.

## Environment

<pre><code>
Angular version: 5.1.0

Browser:
- [ x ] IE version 11
- [ x ] Edge version 11
 
For Tooling issues:
- Node version: 8.9.2
- Platform:  win32 x64

Others:

</code></pre>

**Comment by prasadmamidi7** [comment]
We are completely blocked due to this problem as we have no control on this registry entry. Can you please let me know is there any workaround 
- some sort of switch which will disable this functionality
- or any other solution.

**Comment by ximenchuigao** [comment]
We are also facing this problem :( 
Is there any workaround?
Or any timeline to get it fixed?

**Comment by AndrewKushnir** [comment]
Closing this ticket, since the reported problem was only present in IE11 and Angular no longer supports IE.
