### ISSUE TITLE
Reactive forms demo at : https://angular.io/generated/live-examples/reactive-forms/eplnkr.html is missing js files

### ISSUE THREAD

**Issue by elira** [angular/angular#21077]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Trying to view the demo for reactive forms.
The link to the plunker exists on the page: https://angular.io/guide/reactive-forms
The plunker is at: https://angular.io/generated/live-examples/reactive-forms/eplnkr.html
Some files are missing from the app. For example HeroDetailComponent.ts is completely missing ( among other files)

## Expected behavior

All referenced files in the demo should exist in plunker

## Minimal reproduction of the problem with instructions

Go to https://angular.io/generated/live-examples/reactive-forms/eplnkr.html

## What is the motivation / use case for changing the behavior?

I'm trying to understand reactive forms

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
This should be fixed by #21013.

**Comment by gkalpak** [comment]
Closing this. You can temporarily access the fixed version at https://pr21013-a92d75c.ngbuilds.io/guide/reactive-forms and follow #21013 for updates on when this is merged.

**Comment by elira** [comment]
@gkalpak - Thanks.
