### ISSUE TITLE
Doc about ngTemplateOutlet is outdated

### ISSUE THREAD

**Issue by stefdelec** [angular/angular#21073]
## Current behavior
When I go to `https://angular.io/api/common/NgTemplateOutlet`
I got the doc for the previous NgTemplateOutlet.
But If I build with angular 5=> 
`Uncaught Error: Template parse errors:
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'.
1. If 'ngOutletContext' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.`

## Expected behavior
I expect to have the right documentation.

Angular version: 5.0.1

**Comment by trotyl** [comment]
The [doc change](https://github.com/angular/angular/commit/c0178de0e2d2162023ef81d2dbc358644ae37da8#diff-78e5f4f910e4289ba4a6504c228e6448) has been made more than one year ago.

**Comment by stefdelec** [comment]
Yes you are right. Misunderstanding what has changed... Sorry. I close. Thanks for you time and your work!
