### ISSUE TITLE
[location] method naming inconsistency

### ISSUE THREAD

**Issue by mac2000** [angular/angular#21071]
## I'm submitting a feature request/documentation issue or request

[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[+] Feature request
[+] Documentation issue or request
[ ] Support request

## Current behavior
[Location.prepareExternalLocationUrl](https://angular.io/api/common/Location#prepareExternalUrl) is actually preparing absolute url

## Expected behavior
expecting that it should return full url instead and probably there should be something like `prepareAbsoluteLocationUrl` or something like this

## What is the motivation / use case for changing the behavior?
I'm playing around with Google OAuth2 and need to pass callback url to it, e.g. `http://localhost:42000/callback`. 

After looking around and asking on [SO](https://stackoverflow.com/questions/47616845/angular-get-full-url-for-a-route) did not found working out of the box solution and was curious why prepareExternalUrl did not do what it intents to

Here is a work around:

```
const urlTree = router.createUrlTree(['callback'], {
  queryParams: {foo: 'bar'},
  fragment: 'acme'
});
const path = location.prepareExternalUrl(urlTree.toString());
const url = window.location.origin + path;
console.log(url); // http://localhost:4200/callback?foo=bar#acme
```

I'm not sure should it at all be touched, because of possibility to brake everything, so no PRs, just want to share, and wish something like that working out of the box so no need to remember it

**Comment by sarunint** [comment]
Looks like you need to provide `APP_BASE_HREF` on the root module.

https://stackblitz.com/edit/angular-rvvuke

**Comment by mac2000** [comment]
From docs of [PathLocationStrategy](https://github.com/angular/angular/blob/5.1.1/packages/common/src/location/path_location_strategy.ts#L26-L28)

> If you're using `PathLocationStrategy`, you **must** provide a APP_BASE_HREF or add a base element to the document

So in your example you are missing base element at all and providing one by hands, I'm not saying that this is right or wrong what I'm trying to say it is still more like a hack, how will you build absolute urls for such setup?

**Comment by jasonaden** [comment]
Thank you and this would have been a good change, but at this point the API name is published and it's not a breaking change we will be able to prioritize in the near future. It could be considered if we ever create a new Location service API.

**Comment by mac2000** [comment]
Not sure if I understand your point, just to be clear (not for reopening or forcing changes): 

Why should location service be rewritten at all isn't it enough to rename `prepareExternalLocationUrl` method to `prepareAbsoluteLocationUrl`

Then create proxy `prepareExternalLocationUrl` method which will call `prepareAbsoluteLocationUrl` inside and mark it as an deprecated and leave it for a half of year

When deprecation will be removed you will be free to modify location service without breaking everything, and what is good absolute url is a subset of external one so nothing should break

Or it won't work that way?
