### ISSUE TITLE
angular.io site is not opening in Chrome(Ubuntu 64 bit)

### ISSUE THREAD

**Issue by dipankarX86** [angular/angular#21072]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The https://angular.io/ link does not open in my system (with google chrome Version 63.0.3239.108 (Official Build) (64-bit) in Ubuntu 16.04), this happens instead: <img src="http://siangexplorers.guruzone.in/images/gallery/5/image_26.png">

## Expected behavior

It is showing a blank page for the link https://angular.io/

## Environment
Google chrome Version 63.0.3239.108 (Official Build) (64-bit) in Ubuntu 16.04

<pre><code>
Angular version: X.Y.Z

Browser:
- [X ] Chrome (desktop) version XX
- [ X] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.0  
- Platform:  Linux(ubuntu 16.04)

Others:

</code></pre>

**Comment by gkalpak** [comment]
It seems that the polyfills bundle is corrupted. How do the `polyfills` requests look on the `Network` tab in DevTools? This is how mine look for reference:

![polyfills-requests](https://user-images.githubusercontent.com/8604205/34105029-897095a2-e3fb-11e7-9ab0-58dcb47d6155.png)

Can you also try to unregister the ServiceWorker in the `Application` tab in DevTools and reload.
I wonder if the file got corrupted on the CDN or in ServiceWorker's cache.

**Comment by alxhub** [comment]
Also try a hard refresh, as that avoids SW.

**Comment by aravindfz** [comment]
It is working fine now! I am not able to replicate this.
