### ISSUE TITLE
ngClass is not working inside ngFor for false condition

### ISSUE THREAD

**Issue by PrabakarKaruppasamy** [angular/angular#21076]
Hello All, 

I am trying to show the different icon inside for loop using [ngClass] with condition. Its perfectly working fine for true condition but its not working for false.

` <i class="text-warning" [ngClass]="{'fa fa-heart-o': z.isPinned == false, 'fa fa-heart':z.isPinned == true}" (click)=addFavorite(z,i);  aria-hidden="true"></i>

Environment:- 
@angular/cli": "1.5.0
@angular/common: ~5.0.0
`

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by PrabakarKaruppasamy** [comment]
Hello, 
are u saying that it's not a bug of angular. Its may be a syntax or logical error. Is it true?

**Comment by pkozlowski-opensource** [comment]
You can't have `'fa` to _both_ present and _not_ present - and this is what your code tries to do. I guess you've meant: `<i class="text-warning fa" [ngClass]="{'fa-heart-o': z.isPinned == false, 'fa-heart':z.isPinned == true}">`.

In any case, this is a support question as commented by @ericmartinezr so closing it here.

**Comment by PrabakarKaruppasamy** [comment]
Thanks for your response.  Now understand that it is support issue. Wrong window.
