### ISSUE TITLE
Router events lack information

### ISSUE THREAD

**Issue by izverev-aexsoft** [angular/angular#21088]
Briefly, in Angular 1.5 there were fromState and toState parameters:
$rootScope.$on("$stateChangeStart", function (e, toState, toParams, fromState, fromParams) {})

Currently, in NavigationStart there is resulting URL only.

I've used to extend router state objects with captions, role access. Is it possible to add these toState, toParams, fromState, fromParams properties to NavigationStart event? They look necessary for customizing the routing.

**Comment by jasonaden** [comment]
Thanks for the issue. I think you're talking about `ui-router` though, not Angular's router, as that's the one that fired the `$stateChangeStart` events.

Also, you should be able to get the current URL/params from `ActivatedRoute`.

**Comment by izverev-aexsoft** [comment]
@jasonaden right, using Angular Router, I'm missing expressiveness of `ui-router` events. Thanks for your tip, I've injected the `ActivatedRoute` object, but `activatedRoute.routeConfig` is null at NavigationStart event. I found this thread where lots of people also missing same feature: https://github.com/angular/angular/issues/11812 

I'm still sure that this functionality have to be implemented. It is simple and reasonable question, "which route configuration is activated on NavigationStart?" and it is hard to figure it out.

**Comment by izverev-aexsoft** [comment]
And also I have to add that canceling navigation is a big issue also. I have to reference `CanDeactivate` interface and do a lot of trickery instead of having something like `event.cancelNavigation()` right away in `NavigationStart`.

What I as Router consumer need is literally:

     router.events.subscribe((event: Event) => {
            if (event instanceof NavigationStart) {
                   if (event.state.data.myProperty === "mystring")
                       event.cancelNavigation();
            }
    }
