### ISSUE TITLE
Add beforeNavigate property on Route

### ISSUE THREAD

**Issue by Msender** [angular/angular#21081]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Expected behavior

When configuring routes, we should be able to specify an action to be executed beforNavigate, afterNavigate like so:

`const routes: Route[] = [
   { path: 'somePath', component: SomeComponent, beforeNavigate: someAction }
];` 
## What is the motivation / use case for changing the behavior?

It will be very helpful when using the redux pattern to dispatch an action (like load some data) to the store before navigating.
## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by steveadoo32** [comment]
If you need a workaround for now, you can just use a CanActivate class and always return true for `canActivate`.
