### ISSUE TITLE
Bundled metadata does not reflect metadata lowering.

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#21082]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

The metadata that is bundled with a FSEM is does not reflect rewritings performed by the compiler.

## Expected behavior

The rewritings are taken into account in the metadata.

## Minimal reproduction of the problem with instructions

From: https://github.com/dherges/ng-packagr/issues/382

```
git clone git@github.com:darkbasic/ngx-selectable-list.git
git checkout packagr
npm install
npm run packagr
```

Note that the `new` expression the the metadata for `SelectableListModule` which not present in `src/app/selectable-list/directive/selectable-list/selectable-list.directive.metadata.json` when compiled with `ngc -p ./src/tsconfig.app.json`.

## What is the motivation / use case for changing the behavior?

The bundled version should apply rewritings.

**Comment by dherges** [comment]
Here is another issue description:

> In the repro at https://github.com/georgiee/ng-packagr-foos, the bundled metadata json (`scoped-some-name.metadata.json`) has no metadata for `FooModule` and `FooComponent`. But, these two are exported by the FESM bundles (`(esm5|esm2015)/scoped-some-name.js`).

Is that the same issue?

**Comment by alxhub** [comment]
This is a longstanding and well known issue with View Engine's metadata bundler, and is systemic and non-trivial to fix. The good news is that Angular Ivy does not use the metadata system at all, and therefore this bug is rapidly becoming obsolete.

**Comment by JoostK** [comment]
With v12 now allowing libraries to be compiled with the Ivy compiler, this issue has been resolved.
