### ISSUE TITLE
Angular produces Error in IE9 that blocks page load

### ISSUE THREAD

**Issue by steveblue** [angular/angular#21083]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Angular app is not viewable in IE9. Issue prevents Routes from resolving correctly. 

## Expected behavior

Angular app can route in IE9.

## Minimal reproduction of the problem with instructions

Scaffold a simple app with two routes and observe the route cannot load in Windows 7 IE 9. 

`TypeError: Object doesn't support property or method 'apply'` displays in Developer Tools Console.

When {useHash: true} is omitted from RouteConfig, same issue but the address bar in IE9 is now flickering between `/#/` and `/#/#/`.

If I remove the RouteConfig from the app, IE will load the AppComponent fine. 

Follow instructions in this repo with steps to reproduce:
https://github.com/steveblue/angular5-ie9-issue

This issue is not only reproducible in app scaffolded with `angular-rollup`, but also `@angular/cli` according to the following issue.

https://github.com/angular/angular-cli/issues/6110

## What is the motivation / use case for changing the behavior?

Angular should work in IE9 as advertised. Enterprise users depend on IE9 compatibility.

## Environment

<pre><code>
Angular version: 5.1.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X ] IE version 9
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.9.0  
- Platform:  Built on Mac, viewing in Windows 

</code></pre>

**Comment by daehongKo** [comment]
Don't Angular 5 support IE9?

**Comment by steveblue** [comment]
Since Angular 2 there have been periods where IE9 worked, but it seems some tests are currently failing in IE9. @daehongKo

**Comment by steveblue** [comment]
I am able to still reproduce this and have narrowed down the behavior of the Router to some specific use cases.
 
If an app is bundled in a single bundle the flickering /#/ is not reproducible when the Router is configured with `{useHash: true}`. This issue may only happen when the Router is configured with routes that use `loadChildren` for lazyloading and `{useHash: true}`.

The repeating `#` happens  in IE9 when the RouterModule is configured with `{useHash: false}` in HTML5 mode. This may not be a huge issue, since app developers should be setting useHash to true for IE9 support. Ideally this error would be handled more gracefully.
<img width="613" alt="screen shot 2018-01-21 at 1 27 44 pm" src="https://user-images.githubusercontent.com/1171943/35199162-3fda3334-feaf-11e7-908a-354371a2dc33.png">

**Comment by steveblue** [comment]
This issue is shifting over time to different modules. Could it be rooted in how @angular packages are compiled? Before it happened whenever I would inject the Router into an application. Now in 5.2.3 I can replicate the issue `TypeError: Object doesn't support property or method 'apply' ` by injecting BrowserAnimationsModule and configuring a component with an animations Array. The Router however works again when configured with `{useHash: true}`

**Comment by steveblue** [comment]
Ok we have traced the issue in Angular 5.2.5 so far to `BrowserAnimationsModule` and `FormsModule`. If either of these are injected into our app it results in `TypeError: Object doesn't support property or method 'apply' ` in IE9 @alxhub @jasonaden IE9 has been broken throughout 5.x can we please get a fix before 6.0.0 is released? Im sure all your Enterprise users will be thankful.

**Comment by jasonaden** [comment]
Okay, thanks for the additional clarification.

Can you please specify which version it worked in? I'll also alert @matsko on this one with regards to animations.

**Comment by steveblue** [comment]
@jasonaden The version that worked is unclear, but I can devote some time today to figure it out. It may be as far back as 4.x.

**Comment by matsko** [comment]
Hello @steveblue if possible a stackblitz reproduction would help me find the exact reason why it's causing the error.

**Comment by steveblue** [comment]
@matsko for this use case that will not be possible, StackBlitz itself doesnt support IE9. 

<img width="1216" alt="screen shot 2018-02-22 at 1 21 49 pm" src="https://user-images.githubusercontent.com/1171943/36564828-74ad4528-17d3-11e8-9a2c-00c630e00a32.png">

All that is needed to reproduce is to scaffold an app with the `@angular/cli` and try viewing app in IE9. 

This app.module.ts works in IE9:
```
import { NgModule }      from '@angular/core';
import { CommonModule }  from '@angular/common';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent }  from './app.component';

@NgModule({
    imports: [ BrowserModule,
                     CommonModule],
    declarations: [ AppComponent ],
    bootstrap:    [ AppComponent ]
})

export class AppModule {}
```

That is all you can do with Angular. Only some Modules are effected. So far Ive traced the issue to RouterModule, BrowserAnimationsModule, and FormsModule. Try injecting any other Module into the AppModule in 5.2.6 like RouterModule and you will see the issue the moment you give an application a RouteConfig.

BrowserAnimationsModule can be injected into AppModule, but the moment any Component includes animations[] configuration, same issue appears in the IE9 Developer Tools console.

I tried shims_for_IE.js even though it wasn't recommended, the complete core-js library. I can't find a shim that works. 

I believe this is a problem either with certain coding practices in the `@angular` packages or with how the codebase is transpiled during the build process.

It may come down to how calls to super() are handled in the transpilation process, but that is my best guess. `_super.apply(this, arguments)`

Want to know the weird part? Look at what the Developer Tools console outputs when you type Object.apply.
```
TypeError: Object doesn't support property or method 'apply' 
>> Object.apply 
 function apply() {     [native code] }  
Add to watch
```

This issue in another repo may be a clue. I had to go back a few years in search results to find a similar issue.

https://github.com/getsentry/raven-js/issues/217

I think the last time IE9 worked was 2.x and only with Shims_for_IE.js and not necessarily with core-js. I can't verify this without a lot more investigation. By build doesn't reliably fallback to 2.x, only 4.x.

**Comment by jamiemac87** [comment]
I am having the same problem on IE9 using version `5.2.7`, I have tracked it down to the `HttpClient` in my build. When I call any method e.g `get` `post` etc I get `Object doesn't support property or method 'apply'` in the console

**Comment by jamiemac87** [comment]
please ignore my previous comment turns out i couldn't communicate with the server and thats why I was getting the error. 

@steveblue i hope you solve your issue. i now have my build working in ie9 with routing, reactive forms and http client (no animations module as its not supported in ie9). here is my polyfills file if it helps.

```
/**
 * This file includes polyfills needed by Angular and is loaded before the app.
 * You can add your own extra polyfills to this file.
 *
 * This file is divided into 2 sections:
 *   1. Browser polyfills. These are applied before loading ZoneJS and are sorted by browsers.
 *   2. Application imports. Files imported after ZoneJS that should be loaded before your main
 *      file.
 *
 * The current setup is for so-called "evergreen" browsers; the last versions of browsers that
 * automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),
 * Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.
 *
 * Learn more in https://angular.io/docs/ts/latest/guide/browser-support.html
 */

/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
// import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following for the Reflect API. */
import 'core-js/es6/reflect';


/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect';


/**
 * Required to support Web Animations `@angular/platform-browser/animations`.
 * Needed for: All but Chrome, Firefox and Opera. http://caniuse.com/#feat=web-animation
 **/
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.



/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.

/***************************************************************************************************
 * APPLICATION IMPORTS
 */

import 'ie9-oninput-polyfill';
import 'angular-polyfills/dist/blob';
import 'angular-polyfills/dist/classlist';
import 'angular-polyfills/dist/formdata';
import 'angular-polyfills/dist/intl';
import 'angular-polyfills/dist/shim';
import 'angular-polyfills/dist/typedarray';
import 'console-polyfill';
```

**Comment by steveblue** [comment]
oooo, let me try this. Do you know which of the polyfils actually fixed the apply() issue @jamiemac87 ?

**Comment by steveblue** [comment]
OK, I can verify with the above polyfills that most of Angular will load, but BrowserAnimationsModule is still failing in IE9. IMHO BrowserAnimationsModule should fail silently in IE9 and animations should degrade to just setting CSS properties without a tween @matsko. We probably have to strip out all animations unless there is some guidance for dealing with BrowserAnimationsModule in IE9. 

Here's what worked for me (for all the non Webpack folks)
```
  <!--[if gt IE 9 ]>
  <script src="/lib/web-animations-js/web-animations.min.js"></script>
  <![endif]-->
  <script src="/lib/core-js/client/shim.min.js"></script>
  <script src="/lib/zone.js/dist/zone.js"></script>
  <script src="/lib/ie9-oninput-polyfill/ie9-oninput-polyfill.js"></script>
  <script src="/lib/angular-polyfills/dist/blob.js"></script>
  <script src="/lib/angular-polyfills/dist/classList.js"></script>
  <script src="/lib/angular-polyfills/dist/formdata.js"></script>
  <script src="/lib/angular-polyfills/dist/intl.js"></script>
  <script src="/lib/angular-polyfills/dist/typedarray.js"></script>
  <script src="/lib/console-polyfill/index.js"></script>
```

When I inject BrowserAnimationsModule or NoopAnimationsModule and use animations in the `@Component` decorator in IE9. `TypeError: Object doesn't support property or method 'apply' `

**Comment by steveblue** [comment]
https://github.com/steveblue/angular5-ie9-animations-issue

^ @matsko github repo with reproduction of the issue with `NoopAnimationsModule` in IE9

**Comment by jamiemac87** [comment]
@steveblue the polyfills that fixed my initial errors which i have not documented above were: 
- `'angular-polyfills/dist/classlist';` which fixed issues i was having with class binding in templates i.e `[class.test-class]`. 
- `import 'ie9-oninput-polyfill'` fixed issues I was having with reactive forms on IE9. specifically deleting a text input was not correctly being reflected in the form value.
- `import 'console-polyfill';` fixed an issue i was having with the app not loading if the console was not open within IE9. 

I added the other polyfills just to be safe

**Comment by blackrek** [comment]
such changes helped me:

package.json:
```
add  "classlist.js": "^1.1.20150312", 
update zone.js to "zone.js": "0.8.4"
```

and my polyfills.ts:
```
import 'reflect-metadata'; 
import 'ie-shim';
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es7/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';
import 'core-js/es6/weak-set';
import 'core-js/es6/typed';

import 'rxjs/bundles/Rx';
import '@angular/common/bundles/common.umd';
import '@angular/compiler/bundles/compiler.umd';
import '@angular/platform-browser/bundles/platform-browser.umd';
import '@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd'

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
 import 'classlist.js';  // Run `npm install --save classlist.js`.
/** IE10 and IE11 requires the following for the Reflect API. */
 import 'core-js/es6/reflect';
/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect';
/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.
```

**Comment by steveblue** [comment]
6.0.0-rc seems to hose the Router in IE 9 again. The router is completely broken in our app but works with 5.2.9, same polyfills applied.

**Comment by steveblue** [comment]
Adding a polyfill for `Object.setPrototypeOf` will make the Angular 6.0.0 Router work in IE9 (with HashLocationStrategy). https://gist.github.com/edoardocavazza/47246856759f2273e48b

**Comment by VinayGade** [comment]
> @steveblue the polyfills that fixed my initial errors which i have not documented above were:
> 
> * `'angular-polyfills/dist/classlist';` which fixed issues i was having with class binding in templates i.e `[class.test-class]`.
> * `import 'ie9-oninput-polyfill'` fixed issues I was having with reactive forms on IE9. specifically deleting a text input was not correctly being reflected in the form value.
> * `import 'console-polyfill';` fixed an issue i was having with the app not loading if the console was not open within IE9.
> 
> I added the other polyfills just to be safe
Hi , 
with :  import 'console-polyfill'; I m able to fix issue. Angular is working fine with all versions of IE ( 6 .. 11) Thanks a lot
