### ISSUE TITLE
On the routing switch error, the old routing components are not destroyed

### ISSUE THREAD

**Issue by jiayisheji** [angular/angular#21087]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## What is the motivation / use case for changing the behavior?

![image](https://user-images.githubusercontent.com/6111778/34147912-54b0daae-e4da-11e7-81b4-e449df3da7fc.png)

An error occurred in my app-store component, I switched to the app-visual component, but the app-store component was not destroyed

## Environment

<pre><code>
Angular version: 4.4.5

Browser:
- [ ] Chrome (desktop) version  63.0.3239.108
 
For Tooling issues:
- Node version: v8.4.0
- Platform:  Windows

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
