### ISSUE TITLE
Support  @OutputWithReturnValue

### ISSUE THREAD

**Issue by Malvolio** [angular/angular#21098]
## I'm submitting a...

<pre><code>
[ ] Regression
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior

The existing @&#x200b;Output decorator creates an event emitter so that a child-component can send a event and optional value to its parent

## Expected behavior

I would like a decorator (named  @&#x200b;OutputWithReturnValue or something less goofy) that allows a child-component to send a event and optional value to its parent, *and get a value back*.

## What is the motivation / use case for changing the behavior?

In my case, I am trying to create a button that can tell its parent that it has been clicked and receive in reply an Observable; the button will put itself in some mode (perhaps with a busy animation) until that Observable completes.  There are many ways to accomplish this, of course, but all the ones I have found are awkward, unintuitive, and error-prone.

Other uses might be wherever the parent wished to supply some calculation to the child, where rerunning that calculation as part of change-detection is not practical.

## Environment

Angular version: 4.2

**Comment by trotyl** [comment]
This is impossible, an `Output` event could have as many receiver as possible like [here](https://stackblitz.com/edit/angular-kdxysw?file=app%2Fapp.component.html).

So should it get an `Array` of returned values? In what order?

**Comment by ericmartinezr** [comment]
Can't you simply pass the returned value through an `@Input()` to the child? Like

```
<child [returnedValue]="valueToTheChild " (myOutput)="doSomething()">...

// Parent cmp
doSomething() {
   this.valueToTheChild = ...
}
```

Just thinking out loud...

**Comment by pkozlowski-opensource** [comment]
Thnx for the suggestion but we will pass on this due to reasons pointed out by @trotyl
