### ISSUE TITLE
HttpClient response mapping

### ISSUE THREAD

**Issue by nazarkryp** [angular/angular#21107]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

I have an endpoint https://example.com/v1/media/1
that returns following JSON:

```
{
  "id": 1,
  "body": "some content",
  "created": "2017-12-20T10:23:20.71"
}

```

I have created a model:

```
export class Media {
    private _created: Date;

    public id: number;
    public body: string;

    public set created(created: Date) {
        this._created = created;
    }

    public get created() : Date {
        return this._created;
    }
}
```

I want to have response from HttpClient mapped to that property. To do achieve that I do the following:
(P.S: I use default HttpClient from import { HttpClient } from '@angular/common/http'; )

```
public foo() {
    this.httpClient.get<Media>('https://example.com/v1/media/1')
        .subscribe(media => {
            console.log(media);
        });
}
```

## Current behavior
GET and SET methods in Media class are NOT called

## Expected behavior
GET and SET methods are invoked

## Environment

<pre><code>
Angular version: 5.1.1

Browser:
- [X ] Chrome (desktop) version 63.0.3239.108
 
For Tooling issues:
- Node version: 6.11.0
- Platform:  Windows

Others:
</code></pre>

**Comment by jotatoledo** [comment]
This is the behavior by definition, as the HttpClient parse the body to plain objects, not class interfaces.

**Comment by alxhub** [comment]
@jotatoledo is correct - you will need to write an interceptor to do that transformation.

**Comment by grosch** [comment]
@alxhub Alex do you have an example you can point at on how to do that for those of us new to all this?  Thanks.
