### ISSUE TITLE
transition() accepts no function as stateChangeExpr as listed in the docs

### ISSUE THREAD

**Issue by da-mkay** [angular/angular#21104]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[#] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The [docs](https://angular.io/api/animations/transition) state that we can provide a function as the first argument (stateChangeExpr) for `transition()`. However, according to the function signature we can only pass a string as first parameter. Trying to pass a function anyway leads to a compile error.

This is the example from the docs:

    transition((fromState, toState) => {
        // when `true` then it will allow the animation below to be invoked
        return fromState == "off" && toState == "on";
    }, animate("1s 0s"))

## Expected behavior
Accept functions or correct docs ;)

## Minimal reproduction of the problem with instructions

Simply try the code from the docs linked above.

## Environment

<pre><code>
Angular version: 4.2.4 - 5.1.1

Browser:
- [#] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by matsko** [comment]
Fixed by https://github.com/angular/angular/commit/590d93b30dfb0fcc6baf380bc155dd07dd121f46 a few weeks ago.
