### ISSUE TITLE
DI: appInjector/hostInjector/viewInjector/ohMy!

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2110]
Alright, so I understand the need (today) for all three, but I think there should be some thought about how usable this is long term in a large application. Do we need all three?

**Comment by gdi2290** [comment]
would you prefer `@Host`

```es6
@Directive({
  selector: 'wat',
  appInjectors: [],
  properties: ['wat']
})
@Host({
  injectors: [],
  properties: ['ok']
})
class Cmp {}
```

**Comment by vicb** [comment]
@mhevery mentioned an issue where all host configs are gathered under a host key, do you have reference to an existing issue about that ?

**Comment by mhevery** [comment]
Our latest thinking is that we can get rid of app Injector and just have Element Injector.

**Comment by mhevery** [comment]
Closing in favor of https://github.com/angular/angular/issues/2379
