### ISSUE TITLE
test.sh fails in some timezones

### ISSUE THREAD

**Issue by sarunint** [angular/angular#21112]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I'm living in UTC+7, which makes this test fails:

https://github.com/angular/angular/blob/master/packages/common/test/pipes/date_pipe_spec.ts#L268..L269

Since the specified date in the test is 21st of Jaunary, 2017 in my timezone.

## Expected behavior

Some documentation stating that this test is expected to fail in some timezones. Or any other workarounds.

## Minimal reproduction of the problem with instructions

1. Set your timezone to UTC+7
2. Run `test.sh browser`

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
I (kind of) fixed a similar issue by changing time to 12.00 in [another PR][1]. There are still timezone where it will fail, but are very few. I think it is reasonable to do the same here.

I suspect that using jasmine's [mock clock][2] would be a better solution for such cases :smiley:

[1]: https://github.com/angular/angular/pull/19904/files#diff-664eb094568ce031b715e2b114d6166cR275
[2]: https://jasmine.github.io/api/2.8/Clock.html

**Comment by teh-skrud** [comment]
I don't think that Jasmine.clock() can be useful here as it only mocks calls to `new Date()` (i.e. it is used to mock "now"), but we are using `new Date(ISOString)`.

However, why not simply passing an ISOString including a timezone to it ? (i.e. '2017-05-07T22:14:39+0000') 
From my understanding, that would still be a valid test to prevent regression for the #9524 bug (@ocombe ?).

**Comment by teh-skrud** [comment]
I actually tried with a TZ but no luck. The actual test case referenced already had a TZ passed to it (but another one was failing on my TZ). 

This looks more like a bug than a poorly written test case. The timezone is lost, and I think the culprit is at https://github.com/angular/angular/blob/5a7bf367231e1250c19386b20151b2bbef91c4bd/packages/common/src/i18n/format_date.ts#L182 => the timezoneOffset is supposed to be the third parameter here, but not used.

**Comment by ocombe** [comment]
Thanks! Will look into it!
