### ISSUE TITLE
DI: Decorators can't publish to their host component in time

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2111]
In Angular 1.x Dart this was possible

```html
<some-component some-decorator></some-component>
```

If `some-decorator` published an interface, say, a `SelectionModel`, this was possible:

```dart
SomeComponent(SelectionModel selectionModelFromDecorator) {
  ...
}
```

Today, it cannot resolve (the component is created first, before the decorator maybe?)

Is that working as intended? @vsavkin

**Comment by mhevery** [comment]
I believe we have discussed this in person and it turned out to be a visibilit issue, and we were able to resolve it.

Working as intended.

**Comment by matanlurey** [comment]
Thanks!
