### ISSUE TITLE
onSameUrlNavigation doesn't re-load routed components

### ISSUE THREAD

**Issue by TylerDev6** [angular/angular#21115]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I'm trying to use the new onSameUrlNavigation flag in 5.1.1, and while it does repeat the RouterEvent cycle, it doesn't trigger any lifecycle events in the routed components

## Expected behavior

ideally if it's going to trigger a reload, it should re-initialize any routed components.

## Minimal reproduction of the problem with instructions
imports: [RouterModule.forRoot([
        { path: "", component: HomeComponent, pathMatch: "full" },
        { path: "login", component: LoginComponent },
    ], { onSameUrlNavigation: "reload" })]

This configuration will not trigger lifecycle events in LoginComponent if there's a link to LoginComponent somewhere on the page

## What is the motivation / use case for changing the behavior?

This flag was added to support refresh, but developers would still have to listen to the router event cycle to be able to refresh any components this way

## Environment

<pre><code>
Angular version: 5.1.1

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ x] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@TylerDev6 ... from where did you take that `onSameUrlNavigation` should introduce triggering of life-cycle hooks on components? As I know from source code it was introduce to re-invoke only guards & resolvers.

**Comment by TylerDev6** [comment]
@mlc-mlapis the angular router documentation itself mentions "refresh".... it's not a real refresh if the components don't reload....

https://angular.io/api/router/ExtraOptions

**Comment by mlc-mlapis** [comment]
@TylerDev6 ... you are right ... the formulation in the doc should be changed ...

`Define what the router should do if it receives a navigation request to the current URL. By default, the router will ignore this navigation. **However, this prevents features such as a "refresh" button.** Use this option to configure the behavior when navigating to the current URL. Default is 'ignore'.`

**Comment by rainstormza** [comment]
`import { NgModule } from '@angular/core';
import { Routes, RouterModule, ExtraOptions } from '@angular/router';
import { HomeComponent } from './home/home.component';
import { ProductComponent } from './product/product.component';
import { AppGuard } from './app.guard';

const routes: Routes = [
  { path: '', redirectTo: '/home', pathMatch: 'full' },
  { path: 'home', component: HomeComponent, canActivate: [AppGuard] },
  { path: 'product', component: ProductComponent, canActivate: [AppGuard] },
  { path: '**', redirectTo: '/home' },
];

@NgModule({
  imports: [RouterModule.forRoot(routes, {
    onSameUrlNavigation: 'reload'
  })],
  exports: [RouterModule]
})
export class AppRoutingModule { }
`

Angular CLI: 1.6.2
Node: 8.9.3
OS: darwin x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.2
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0

I tried to add onSameUrlNavigation to my routes but
both lifecycle and guard doesn't trigger

**Comment by mlc-mlapis** [comment]
@rainstormza ... simple http://Stackblitz.com reproduction?

**Comment by rainstormza** [comment]
@mlc-mlapis 
https://stackblitz.com/edit/angular-wa3au2

when I click button route on same url guard does not console anything. ( click product when route is /product)
I think guard should console.log 'guard' when I click same url.

**Comment by mlc-mlapis** [comment]
@rainstormza ... hmm, just I forgot to say that there is another property which affects the behavior of re-running guards and resolvers ... when `onSameUrlNavigation: true` ... and it is `runGuardsAndResolvers` ... so there has to be `runGuardsAndResolvers: 'always'` (... there are also `'paramsChange'` or `'paramsOrQueryParamsChange'`) set on each route definition which you want to affect.

You can see it in action on this Stackblitz demo: https://stackblitz.com/edit/onsameurlnavigation?file=app/app-routing.module.ts

**Comment by rainstormza** [comment]
@mlc-mlapis it works, thanks
but I think it should trigger ngOninit in component too.

if I want go to the same route and invoke ngOninit too, do you have any solution ?

**Comment by mlc-mlapis** [comment]
@rainstormza ... no, it shouldn't. Not by design. Triggering of `ngOninit` would mean creating a new instance of the same component ... and it's not true.

The question is why you need to run `ngOninit` at all. You have probably some logic in you code that should be improved to allow you to react to data changes without the necessity of running `ngOninit`  again. But I don't know your exact case so I can't be more explicit.

**Comment by rainstormza** [comment]
@mlc-mlapis  I got it.
I need to run ngOninit because when I click the same url 
I want my component ( or lazyload component) re-render again which mean I want my component trigger my service again or do some logic in ngOninit again.

Do you have any solution to do anything like this ? 
thanks.

**Comment by mlc-mlapis** [comment]
@rainstormza ... yes, you can run `ngOnInit` hook by yourself ... as you do it in unit tests. But I still think that you should improve the logic of your code ... so your component would be able to detect automatically that it is refreshed. One way could be via a resolver ... that can run some code and through a singleton service ... to which the component is subscribed ... emit something what the component understands and would be able to run what your need.

**Comment by rainstormza** [comment]
```
this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        // do some logic again when I click same url
      }
    });
```

I think router event should trigger event (something) when I click the same url.
In Angular 4 when I do that router event doesn't trigger any event but
In Angular 5 router event always trigger event when I click the same url.

Could you please show the way to emit some event when click the same url ?
thanks.

Anyway
```
// override the route reuse strategy
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
    this.router.events.subscribe((evt) => {
      if (evt instanceof NavigationEnd) {
        // trick the Router into believing it's last link wasn't previously loaded
        this.router.navigated = false;
        // if you need to scroll back to top, here is the right place
        window.scrollTo(0, 0);
      }
    });
```

I tried this way but I think it doesn't look like a good way.

**Comment by mlc-mlapis** [comment]
@rainstormza ... remember that `onSameUrlNavigation` is a new feature ... it doesn't exist on 4.x ... you can't count with this. And on 5.x without using `runGuardsAndResolvers` just only routers events are generated.

So I am not sure what you are trying to find ... probably migration to 5.x should be the best ... and as I believe without any problems ... but I thought that you are already on 5.x.

**Comment by bluefire2121** [comment]
Why does this exists only on forRoot? Why can't forChild accept the additional parameter as well?

**Comment by mlc-mlapis** [comment]
@bluefire2121 ... but it works. Do you have a case when not? Why should `forChild` accept it ... it is not necessary ... `forRoot` and `onSameUrlNavigation: 'reload'` means setting for the router as the singleton.

**Comment by mlc-mlapis** [comment]
@bluefire2121 ... and those levels are what? Are they lazy loaded modules? Router is a singleton principally - you have just one URL address bar in SPA app. So the switch `onSameUrlNavigation` works globally but without `runGuardsAndResolvers` param on each route only routers events are generated, nothing more. So it is a bit unclear what is the case where those events can't be processed ... when you know that those routes come from lazy loaded modules.

**Comment by chadbr** [comment]
Can't we just have a "reload()" method? This is like buying a dairy farm to get an ice cream cone.

**Comment by mlc-mlapis** [comment]
@chadbr ... still not clear why you should need to create a new component instance.

**Comment by chadbr** [comment]
@mlc-mlapis in this simple case, we have a "pop-in" component that allows users to change ~10 settings (colors, units of measure, internationalization, etc.etc.) -- 

When some of these settings are changed, we'd like to simply reload the control that happens to be in focus. Each of the controls have various services that "own" these settings and provide "the correct thing" to the components.  

We could add every setting change as some kind of event that every component in the system responds to -- but how about some separation of concerns? Does every component need to know about a possible data change in every service? Other component / service? It seems unreasonable to me... not to say it can't be done, but I don't think it *should* be done. A reload() makes all the code so much cleaner.

Thanks, Chad

**Comment by mlc-mlapis** [comment]
@chadbr ... I probably understand what you mean but still I am not sure that you see it right.

My reasons are:

* even when a new instance is created ... all those things have to happen so it is just a step further,
* and I always imagine that everything is async ... and it doesn't matter if the change is done directly by a user or it just comes through any other channel ... as a totally different user in any other place ... or as some automatic forced reaction from backend,
* in all those cases you should have to react correctly and not let the user think that there is no change.

**Comment by chadbr** [comment]
@mlc-mlapis I understand what you're saying... but:

- the one step further is again a separation of concerns... it's easy to say 'observe everything' until you have 50 things to observe and you can't reason on when / why things change anymore...
- not everyone uses observables (I assume you mean async / observables) -- it's a nice goal, but the complexity level there is high for many devs, so they do not.
- if you have a large application where someone assumed things could not change (i.e. it was hardcoded) -- and then someone comes along later and says 'we need to make this configurable' ... do you change 100 components to respond to live changes? ... you can, but the complexity vs. benefit is very low.

---

On the other side of the coin -- I don't see the harm in having a reload... it's a perfectly valid workflow. I'm just asking for the obtuse workflow outlined in various threads on this subject to be wrapped into a reload method.

**Comment by mlc-mlapis** [comment]
@chadbr ... yes, I mean `async / observables` logic. You are right that it is easier to suppose that there is only one source of any change ... and we also supposed that before Angular 2.x ... so no live changes. But with Angular we have changed our thinking.

It is also true that it could be relatively easy to add `reload()` method to Angular API and I am not sure what was the primary reason why Victor didn't do it. It is just my guess that the reason was his conceptual point of view. 😄

**Comment by chadbr** [comment]
@vicb -- any opinion on this?

**Comment by vincent-cm** [comment]
Comon, This feature is just to let you program more precisely to control over the events, not to delegate everything such as (your idea) to reload a page...
If so, you can suggest another directive property such as `onSameUrlNavigation: reloadAll`

**Comment by jibbers42** [comment]
I think a refresh is what most everyone expects, end users and developers alike. It would be nice to have a simple way to enable this wherever desired. My specific use case is for settings screens like the one in github.
![image](https://user-images.githubusercontent.com/797824/42309576-f8867c70-8006-11e8-9c23-4b9a562dfa46.png)

If you click Options on the left, pretty much everyone expects the form to reset (and usually with updated data if there are updates). The same with Settings up top (except it would also take you back to Options if you were on a different settings page). Ideally, there shouldn't be anything (or very little) a dev has to do to get this behavior.

**Comment by We-St** [comment]
Adding an option to `onSameUrlNavigation` seems like a small addition for a useful feature. We could probably design all our components to not require this, but why bother if for the few situations in which we need this, a component reload would do?

Can we get an estimate on when this feature might make it into Angular?

**Comment by mlc-mlapis** [comment]
@We-St ... `onSameUrlNavigation`  + `runGuardsAndResolvers` work together ... read https://medium.com/engineering-on-the-incline/reloading-current-route-on-click-angular-5-1a1bfc740ab2

And the general explanation is ... **why to destroy already existed component instance and create a new one for the same case** when it means performance degradation? It is the exactly the same behavior as using routes pattern `/product/:id` where the same component instance is also kept for `/product/5`, `/product/6`, ...

So you should re-init the component on the base of some emitted event (resolver / guard) and not on the base of `OnInit` hook because the same component instance.

**Comment by karthick678** [comment]
/product/:id/details

import { ActivatedRoute, Params, Router } from ‘@angular/router’;
export class ProductDetailsComponent implements OnInit {
             constructor(private route: ActivatedRoute, private router: Router) {
                      this.route.parent.params.subscribe(params => {
                                 this.paramsChange(params.id);
                    });
             }
            // Call this method on page change

            ngOnInit() {
            }
            // Call this method on change of the param

           paramsChange(id) {
           }
}

**Comment by mlc-mlapis** [comment]
@We-St ... then I missed the idea ... when nothing has been changed than what do you want to refresh?

**Comment by smithk58** [comment]
@mlc-mlapis - All of the data behind the scenes for that route? Just because the parameter in the route hasn't changed doesn't mean all of the data associated with visiting that route hasn't. In We-St's example another person could have modified that product. Is the user in that case expected to visit another route before coming back to the current one before they can see those changes, or are they expected to always refresh if they want another users changes? It's completely reasonable that they would expect to see those changes by clicking on that same route.

**Comment by mlc-mlapis** [comment]
@smithk58 ... so you are talking about the refresh of `resolvers` or `guards` ... or you mean that you read some static data in `ngOnInit` hook and later you don't know if this data has been changed?

**Comment by smithk58** [comment]
@mlc-mlapis  The later case. A user clicks on a navigation item and it loads the component for that route. Part of the ngOnInit of that component retrieves data for the component, and the data in that component could be updated at any time. If the user clicks that same navigation item they would expect all of the displayed data to be the most recent available data.

As far as I can tell the suggested work around for a situation like this is to prefetch all of your data before going to the route, then 'reload' would actually get the latest data if I tell resolvers to reload?

If that's true, I suppose it's not the worst, but it feels a lot more convoluted to me. It feels like I'm jumping through hoops to make the router not ignore my .navigate request.

**Comment by mlc-mlapis** [comment]
@smithk58 ... it is as you said ... using resolvers ... they are here exactly for that ...
> ... prefetch all of your data before going to the route with resolvers, then 'reload' would actually get the latest data.
The main goal is to eliminate the repeated instantiation of that component ... and behave reactively just on some events.

**Comment by We-St** [comment]
@mlc-mlapis Not sure why you argue so vehemently against this feature request, but many projects do not rely on resolvers. These are neither a mandatory part of Angular, nor do they lead to the UX behavior some projects want to incorporate into their product (in regards to showing loaders and error handling).

This FR is about an **opt-in** approach to create new component instances in rare occasions. I see why Angular is optimizing here, that's why it should be opt-in. The Angular team clearly thinks there's a use case for such a behavior, hence the option to re-run resolvers. There should also be an option when you do not use resolvers (or make them mandatory, but there's also a reason why that is not the case).

**Comment by jibbers42** [comment]
> The problem is that those cases represent small % of the whole issue

I'm not sure exactly what you mean here, but applying it to the performance implications that seem to be the main objection - I'm not sure the typical user, perhaps anyone, would even notice in the majority of cases. Or maybe the very savvy user would see a flicker and realize, but it would be so fast that even the savvy user wouldn't care.

The main argument seems to boil down to others dictating the performance characteristics of my app. Being opt-in, the documentation has the opportunity to clearly state that this may negatively impact performance. I'm perfectly fine with Angular choosing a default that is not in line with how the web has always worked, but I also think there should be an easy config to enable the requested behavior.

**Comment by ChristianRamseier** [comment]
My use case is chaning the user context globally for all components and here's my (ugly) workaround: In the template I added something like...
```
<router-outlet *ngIf="reload"></router-outlet>
<router-outlet *ngIf="!reload"></router-outlet>
```
... and then in the component instead of navigating I have ...
```
this. reload = !this.reload
```
Works but I'd prefer a way provided by the framework to do this.

**Comment by kdubious** [comment]
Maybe my example will help shed light on:
a. A better approach to avoid `.reload()`
b. The need for it

Imagine a parent `DashboardComponent`. One component on that page is a list of events to which you have been invited, and accepted. Another is a list of open invitations. Both are added to this `DashboardComponent` by means of `<app-events></app-events>` and `<app-open-invites></app-open-invites>`.

There's no need (at this point) for ViewChildren, a shared service, etc. Each child component is capable of loading it's own data.

Now, I'd like to be able to click an `accept` button on an item in the `OpenInvites` component, have that do some work in the back end, and ultimately (upon success) remove the open invite and show the new event.

Seems easiest to just re-navigate to `/dashboard` to do that.

If I leave `/dashboard` and return, it all re-loads.

How would we do that here without going away and coming back? `onSameUrlNavigation` is not enough. `runGuardsAndResolvers: 'always'` is not enough. `this.router.routeReuseStrategy.shouldReuseRoute` doesn't seem right.

**Comment by mlc-mlapis** [comment]
@kdubious ... why `runGuardsAndResolvers: 'always'` is not enough? It's all about resolvers.

**Comment by kdubious** [comment]
@mlc-mlapis I don't use resolvers at all... what am I missing? (off to read more documentation)

**Comment by mlc-mlapis** [comment]
@kdubious ... it's working as following:
* you are attaching a resolver to a route (it runs always because of `runGuardsAndResolvers: 'always'`)
* your `Dashboard` component can read that resolver data (this the smart component)
* those data can be passed to any other child component (those are dumb ones) either via `@Input`s
* or if more suitable via some other service injected into those children.
That's all.

**Comment by scottieslg** [comment]
In my situation, I have 3rd party components that won't refresh unless the page is refreshed.  Using a resolver won't work for me.  I need the entire route to re-load so that my 3rd party components will reload as well.  

I don't have any control over what @Inputs these components have or how they refresh.

**Comment by mlc-mlapis** [comment]
@scottieslg ... what are they? How the data is passed in then? Via observables?

**Comment by shootdaj** [comment]
So it's been over a year since this issue was opened. Is this on the roadmap at all? Or should we just implement one of the solutions (hacks) mentioned in this thread and elsewhere? I feel like this feature is super useful and (from my naive knowledge of Angular) wouldn't be that difficult to implement?

**Comment by sysmat** [comment]
When user change (by click on link, by click, manually) parameters in url regardless if it is the component, the component should start life cycle.

So basic example: You have organization component and in template routerLink to parent organization, but nothing happened because OnInit not  happened.

Some times I'm in doubt to using angular, basic staff not working.

**Comment by sechel** [comment]
👍

**Comment by ymongo** [comment]
> @We-St ... `onSameUrlNavigation` + `runGuardsAndResolvers` work together ... read https://medium.com/engineering-on-the-incline/reloading-current-route-on-click-angular-5-1a1bfc740ab2
> 
> And the general explanation is ... **why to destroy already existed component instance and create a new one for the same case** when it means performance degradation? It is the exactly the same behavior as using routes pattern `/product/:id` where the same component instance is also kept for `/product/5`, `/product/6`, ...
> 
> So you should re-init the component on the base of some emitted event (resolver/guard) and not on the base of `OnInit` hook because of the same component instance.

Your link is gold, it solved problem, and saved my night. Thank you!

**Comment by bunnyfly** [comment]
**Another vote for an easy router reload() method, please!**

I understand why the resolver or subscribe to an event methods are suggested. But for myself, reloading is only used for rare, secondary events. I (and my users) don't need anything fancy or have blazing fast performance expectations.

Resolvers feel nice at first but are difficult and unintuitive to maintain (my experience with two eng teams that both tried them) and make page display slower. And event-subscribing boilerplate is convoluted and irritating to add and maintain to every component in an app just to enable reloading.

Forcing people to use and maintain these patterns for "smart refreshing" feels pretty bad, when it could be as easy as router.reload(). I don't think anyone would say "hey! I thought reload() was going to be more performant than reloading!" but you **do** have a lot of people here saying "please allow this."

**Comment by webia1** [comment]
a quick and dirty solution, but it works:

```js
this.router.navigate(
          ['user', userId, { updated: true, at: new Date().getTime() }],
          {
            relativeTo: this.route.root
          }
        );
```
`new Date()' is the trick. And the route is (.routing.ts):

Excerpt:

```js
{
        path: ....
        component: .....,
        runGuardsAndResolvers: 'always'
}
```

**Comment by juancarrey** [comment]
If you navigate manually to the route, you can always navigate to an empty route first, then navigate to the route you want.

`this.router.navigate(['/reload']).then(() => { this.router.navigate([ ... ]); })`

**Comment by kernyden** [comment]
but what if i want to use  runGuardsAndResolvers on root(parent route) for specified childs and prevent for specified too? for instance, i want to prevent it for path: ':id'
children: [
        { path: 'create',  component: bla },
        { path: 'edit/:id',  component: bla },
        { path: ':id',  component: bla }
      ],
runGuardsAndResolvers: 'always',

**Comment by ayyash** [comment]
I think the confusion for me was that child components wrapped inside ng-containers that listen to param changes do NOT automatically reload themselves... when you would logically expect them to. I wonder how angular is made to ignore container changes like that

template
```
<ng-container *ngIf="(profile$ | async) as profile">
This updates itself on route change:
{{ profile.firstName }}

This does not:
<jr-share-button [share]="{profile: profile}"></jr-share-button>
</ng-container>
```

component
```

@Component({
    templateUrl: './profile.html',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class ProfileDetailsComponent implements OnInit {
profile$: Observable<IProfile>;
 constructor(private profileService: ProfileService,
        private route: ActivatedRoute) {
    }
 ngOnInit(): void {
      // the profile DOES reload on param changes,
     //  you would expect the container children would reload as well
      this.profile$ = this.route.paramMap.pipe(
            switchMap(params => this.profileService.GetProfile(params.get('id')))
        );
    }
}

```

Of course the solution is to force children to "listen" to property change by a setter, which makes its ngOnInit quite useless... but that is not what you'd expect.

**Comment by mlc-mlapis** [comment]
@ayyash The `ngOnInit` is run only when a component is instantiated.

**Comment by ayyash** [comment]
@mlc-mlapis thats where the confusion comes from, from my background in web, requesting a new url should reinitialize, right now, I must hide the component and show it again to force it, I wish there was a cleaner easier way (easier than making getters and setters and observables for child components), I thought 'onSameUrlNavigation' would fix it, apparently not.

**Comment by mlc-mlapis** [comment]
@ayyash Not sure about you concrete case conditions, but there are different settings for using `onSameUrlNavigation`, which allows you to re-run guards and resolvers to re-init the same component instance, instead of destroying and re-instantiating it. All are based on the subscriptions to the changes on URL. The real difference is mainly in our thinking. Angular generally prefers reactive ways, where it's possible.

**Comment by ayyash** [comment]
@mlc-mlapis im just saying why everyone expects something different, seeing you taking a lot of hits on this thread, this is what we understood, but that is what angular had in mind. Reload, really means reinitialize everything on page... hmmm, not so fast says angular.

**Comment by chadbr** [comment]
I think this thread should probably be closed... I don't see Angular supporting it.

fwiw -- this gets it done for us... ugly but effective.

```javascript
window.location.reload(true);
```

**Comment by bunnyfly** [comment]
@chadbr  `window.location.reload(true);` is not cross platform. It'll work for simple websites in a browser, but not necessarily for PWAs, Universal SSR, mobile-platform libraries that use Angular, etc.

**Comment by chadbr** [comment]
@bunnyfly completely agree...

**Comment by MonstraG** [comment]
I need this feature on user creation page. /user/new should redirect to /user/id, and /user/id should reload when I click "save". 

Having `onSameUrlNavigation` do that for me would be easy and simple.

`window.location.reload` reloads whole page instead of a component (I have a header with navigation as a separate component, I don't want it to be reloaded).

**Comment by bmoe24x** [comment]
Can we bring this back up? @chadbr hit it on the head. There is a (lot of) use case for it and we shouldn't have to do ugly hacks.

**Comment by helzgate** [comment]
It would be really useful to have a reload in the case of a Cordova app where literally everything dimension-wise needs to be re-evaluated after orientation change.  I set my initial values in the app.component.ts that all my routes use.  Sure I can set a orientation listener in my app.component.ts (and I am) and then kick off my ngOnDestroy and then my ngOnInit again but my <router-outlet> components don't know that that has occurred.  So Now I have to find a way to notify them, this is a big headache and all this work within a framework that is supposed to be helping me, not getting in my way.

**Comment by itayod** [comment]
any news?

**Comment by simeyla** [comment]
Ahh! I'm getting more and more tired of endless threads like this that go on for years. Especially when a simple API fix would wipe the slate clean.

My number one reason for wanting an component to recreate itself in full is **data integrity / safety** and for beginners **ease of use**.

Ease of use first (less important to me TBH) - when you start learning about `Resolve` you basically HAVE to use Observables - or you don't get new values when the route changes (if you try to use `snapshot.data`). For beginners it would be nice to just take `snapshot.data` in the `ngInit` and start with a clean page.

I'm developing a CRM admin console - so I have customers with orders, messages, membership settings etc. I have resolvers that load the most important data, but I rely on a 'ViewModel' class to manage loading dependencies and handling errors. 

I also use Observables extensively with a lot of async pipes, where often a value is derived from multiple inputs. Maybe there's a list of `orders$` and a list of `shippingAddresses$`. If you're not careful (assume these two Observables take varying time to initialize) you could end up merging a previous customer's orders with a newly selected customer's shipping addresses when changing route.

Easy to fix - probably - but then you have to make sure every observable is reset when a new route is set and it adds complexity. If you make a mistake somewhere and end up in this scenario the results could be a disaster. 

The point being sometimes it's far safer to just start from a blank page on a route change and just not have to worry about such things. And when switching to a new customer I'm already recreating all the child components anyway - so why this big fuss about performance on the parent I don't know.

**Comment by broweratcognitecdotcom** [comment]
I agree w/ @simeyla. The use cases are obvious. If I make an app that uses Resolve services to feed data to route components which in turn feed the data to smart components that they host then I want to be able to route to the same URL and for the route component to be destroyed and recreated.

**Comment by musaticsgilbert** [comment]
So we already seen lots of hacks even in this thread. Some of them look nice, some not so much. @mlc-mlapis pushed the `resolver` idea forward, not recognizing that Angular simply won't render a component until the resolver finished loading the data and this can pretty much halt the first render of the web app (for mlapis: https://stackoverflow.com/a/58936801/10780799). We really need the component reloading `onSameUrlNavigation` option so we can skip resolvers and show a loader while the data loads. If the Angular team can accept that this is a valid reason and make an official reloader, it can significantly reduce the number of dirty hacks we have to use now. Until then, @juancarrey's hack might be the safest hack to use.

**Comment by mlc-mlapis** [comment]
@musaticsgilbert I understand your point of you and the reasons behind it. I don't want to say that all 100 % of cases work the best with resolvers. But I also know very well that historical habit is very strong and there is a lot of developers who choose the trivial way, even it's far from optimal. That's why I was trying to explain (persuade) that the resolvers are the best way for most of the cases, but not the only ones.

Showing some spinner to express visually, that some data is loading, is not a principal problem in relation with resolvers. It depends on the logic and how you are technically controlling it to prevent just showing an empty screen or part of it.

**Comment by xsegrity** [comment]
Why not just add a 'forceReload' method to the router that re-initializes the entire route IN ADDITION to leaving the other mechanisms in place. There are legitimate scenarios for all cases. You can even name the method 'shameOnMeForForcingAReloadInThisFashion' if it makes some purist feel better. This is super aggravating to not have. This is forcing me to write a lot of extra code in areas that should not be concerned with this sort of thing or write some silly '/reload' page/route/bounce/back/again thing. Grr 😠

**Comment by kdubious** [comment]
Agree. It's frustrating to not have this. I find I'm getting frustrated with Angular 2+ in general... "compiling" TS (JS) into this framework is a risk we all take by using Angular 2+. Having little control over the roadmap makes that risk even riskier.

**Comment by ayyash** [comment]
`shameOnMeForForcingAReloadInThisFashion` lol... although i am on the suffering end of this ordeal, but I can see what Agnular people were thinking when they designed it that way, see "route" is just another observable in an SPA, like all observables you add to your component, imagine having a subject in your component, when you `next` it re-inializes another component? devistating... so I guess it just the way it is, if you have multiple components that feed from the route, make sure you tie them to the main route observable

**Comment by joaopaschoal** [comment]
Maybe angular team could add this reload component option, but I agree that by design it doesn't make much sense. In case it may be useful to anyone, I managed to react appropriately to onSameUrlNavigation event by intercepting the "NavigationStart" event and comparing router.url and event.url. If they are equal then you could do something like reloading your component. In my case I created a "navigatedSameRoute: EventEmitter<string>" which I fire when "NavigationEnd" takes place and my component subscribes to that EventEmitter and responds by reloading, like this:

// router-navigations-manager.component.ts (for example...)
  private currentNavUrl: string;
  private nextNavUrl: string;
  @Output() public navigatedSameUrl: EventEmitter<string> = new EventEmitter<string>();

  constructor(private router: Router) { }

  ngOnInit() {
    this.router.onSameUrlNavigation = 'reload';
    if (!this.eventsSubscription || this.eventsSubscription.closed) {
      this.router.events.subscribe(ev => {
        if (ev instanceof NavigationStart) {
          this.currentNavUrl = this.router.url;
          this.nextNavUrl = ev.url;
        } else if (ev instanceof NavigationEnd) {
          if (this.currentNavUrl && this.currentNavUrl === this.nextNavUrl) {
            this.navigatedSameUrl.emit(this.nextNavUrl);
          }
          this.currentNavUrl = undefined;
          this.nextNavUrl = undefined;
        }
      });
    }
  }

  ngOnDestroy() {
    if (this.eventsSubscription) {
      this.eventsSubscription.unsubscribe();
    }
  }

**Comment by kapunahelewong** [comment]
Status: docs team needs to clarify documentation on this point.

**Comment by atscott** [comment]
As noted by @kapunahelewong, we need to clarify the expectations in the docs. As for being able to actually reload the components, this seems to be possible by providing your own `RouteReuseStrategy` along with `{onSameUrlNavigation: 'reload'}` as in this example: https://stackblitz.com/edit/angular-ivy-router-base-2hgd2t. Please correct me if I'm wrong, but this appears to accomplish the described goal.

**Comment by EdwinBustamante** [comment]
@atscott 
  this is a great solution....

**Comment by AlexanderSesslerPorabo** [comment]
> As noted by @kapunahelewong, we need to clarify the expectations in the docs. As for being able to actually reload the components, this seems to be possible by providing your own `RouteReuseStrategy` along with `{onSameUrlNavigation: 'reload'}` as in this example: https://stackblitz.com/edit/angular-ivy-router-base-2hgd2t. Please correct me if I'm wrong, but this appears to accomplish the described goal.

Thanks for that solution, it kind of does what i would need in my case. Unfortunately i've noticed that when using nested routes, not only the child but also its parent component will be reloaded (though for some reason only the child resolver is triggered, not the parent resolver. What i need for my use-case (in my case a side by side master/detail view) is for only the child resolver and component to be reloaded, as i don't want my master list to be rebuilt every navigation.

Any chance you could help me extend your solution to accomplish this?
Thanks!

**Comment by atscott** [comment]
>What i need for my use-case (in my case a side by side master/detail view) is for only the child resolver and component to be reloaded, as i don't want my master list to be rebuilt every navigation.
> 
> Any chance you could help me extend your solution to accomplish this?
> Thanks!

@AlexanderSesslerPorabo I believe what you want is for your `shouldReuseRoute` to be `return future.children.length !== 0;` rather than `return false`. i.e. reuse the activated route if it has children.
https://stackblitz.com/edit/angular-ivy-router-base-fund7g?file=src%2Fapp%2Fapp.module.ts

**Comment by AlexanderSesslerPorabo** [comment]
Amazing, works as intended. Thank you!

**Comment by sanjuroo** [comment]
when i use shouldreuseroute false, it has a lot of side effects for me, like all links like <a routerLink="myLink">My link</a> will become default ones <a href="dashboard">My link</a>, in app.component.ts NavigationEnd event activatedroute.firstchild is undefined. Anyone knows why?

**Comment by MHillier98** [comment]
Maybe it's a bit hacky or something, but I found a guide that helped me work around this issue: https://medium.com/swlh/how-to-toggle-caching-for-routing-components-in-angular-5a327ea87310

Seems to fix the issue for me, assuming its the same issue?
