### ISSUE TITLE
Forms api should support model -> view updates

### ISSUE THREAD

**Issue by rkirov** [angular/angular#2112]
Calling `updateValue` on a control does not update the view.

**Comment by vsavkin** [comment]
`updateValue` is used to update the model form the view, so it should not be used in the other direction.

I think we should create the value setter that will be used to update the form:

```
  value(val: any): void {
    this._setValueErrorsStatus(val);
    this._updateView();
  }
```

And then in ControlDirective:

```
var c = this._control();
c.validator = Validators.compose([c.validator, this.validator]);
c._updateView = this._updateDomValue;
```

**Comment by naomiblack** [comment]
On hold while @vsavkin refactors forms. Let's revisit in M10.

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/commit/652ed0cf6df6bd96808bbd6042c2b23a64a9b693
