### ISSUE TITLE
error TS7016: Could not find a declaration file for module '@angular/common/locales/xx_XX" angular 5.1.2

### ISSUE THREAD

**Issue by cristhiank** [angular/angular#21120]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I updated my project to 5.1.2 and when I try to compile the project I'm getting an error message because the declarations files for the locales are missing and typescript won't compile.

![image](https://user-images.githubusercontent.com/1218220/34238779-8dbc54de-e5d1-11e7-81fc-9cbf04fd6cf2.png)

## Environment

<pre><code>
Angular version: X.Y.Z

Angular 5.1.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
See https://github.com/angular/angular/issues/20340#issuecomment-353081910

**Comment by davidcruy** [comment]
@trotyl that issue is about default file behavior.

This issue is happening because the ts-files are not inside the common/locales folder in v5.1.2

Is it normal that these files are missing?

**Comment by davidcruy** [comment]
@cristhiank, I've found a workaround. You can use the JS-file instead of searching for the ts-file.

Instead of this:
`import { registerLocaleData } from '@angular/common';
import localeNlBE from '@angular/common/locales/nl-BE';
registerLocaleData(localeNlBE);
`

Do this:
`import { registerLocaleData } from '@angular/common';
const localeNlBE: any = require('@angular/common/locales/nl-BE.js');
registerLocaleData(localeNlBE);
`

**Comment by trotyl** [comment]
@davidcruy You're right, `d.ts` files was removed by #20938.

**Comment by davidcruy** [comment]
The documentation over here:
https://angular.io/guide/i18n#i18n-pipes

Should be changed then :|

**Comment by trotyl** [comment]
Actually you do can import `.js` files in `.ts` by just turn on the `allowJs` flag, that was just fixed (see  #19757).

**Comment by ocombe** [comment]
@davidcruy the documentation should not be changed, it's a regression and we will revert this, thanks for reporting

**Comment by IgorMinar** [comment]
we will not cut an npm release until after holidays, so if you are affected by this regression you can in the meantime get a build from our CI using `yarn upgrade angular/common-builds#5.1.x` (works with npm as well) which will pull it from https://github.com/angular/common-builds/tree/5.1.x (the build will be there after https://travis-ci.org/angular/angular/builds/320557745 or later job completes)
