### ISSUE TITLE
Two impure pipes and a click event

### ISSUE THREAD

**Issue by kyles-repository** [angular/angular#21128]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

I currently work at Groventure PTE LTD, and this is an issue regarding a component I am working on. I have tested it, in the manner below, and the snippets were made, and used to reproduce it at its most minimal, and the issue still arose. Sorry, and thank you!

## Current behavior
Currently, the click event is not being handled. That is, in the test code ( That I have provided ), the function is not invoked. The invoked function should output to console. 

```
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
    name: 'pipe1',
    pure: false
})
export class Pipe1Pipe implements PipeTransform {
    transform(value: any, args?: any): any {
        return [
            { 'attribute1' : 1 , 'attribute2' : 2, 'attribute3' : 3 },
            { 'attribute1' : 2 , 'attribute2' : 3, 'attribute3' : 4 },
            { 'attribute1' : 5 , 'attribute2' : 6, 'attribute3' : 7 }
        ];
    }
}
```

```
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
    name: 'pipe2',
    pure: false
})
export class Pipe2Pipe implements PipeTransform {
    transform(value: any, args?: any): any {
        return [
            { 'name' : 'Fruit' , 'values' : [ 'Apple', 'Banana', 'Durian'] },
            { 'name' : 'Veg' , 'values' : [ 'Carrot', 'Pea'] },
            { 'name' : 'Desert' , 'values' : [ 'Cake', 'Brownies'] }
        ];
    }
}

```

```
var data : Array<number> = [231, 12312, 23123 ,23131];
```

```
<ng-container *ngFor="let attribute of data | pipe1 | pipe2">
    <h4>{{ attribute.name }}</h4>
    <a *ngFor="let value of attribute.values" (click)="log(attribute.name, value)">
        {{ value }}
    </a>
</ng-container>
```

This has been tested to reproduce the same error. Pipe1 is a dummy, with a value of ``` pure : false ```,  Pipe2 is the same ( neither pipes, use each others data in this reproduction, in the real application, pipe1 does pipe data to pipe 2, and both pipes are impure ). I have removed those pieces to find the most minimal code that reproduces the error, and that is what is here.

## Expected behavior
It should console.log on click

## Minimal reproduction of the problem with instructions
Sorry, no plunker.
1. Place, html code, in a test page ( to reproduce, it should not be immediately accessible from home page ).
2. Reload the home page.
3a. Click on the link to the test page ( Your html template should contain the snippet above, at this point ).
3b. Click on, sub-categories like 'Durian'. It will **not console.log**
4a. Reload the test page F5.
4b. Click on, sub-categories like 'Durian'. It **will console.log**

## What is the motivation / use case for changing the behavior?
I don't have any, but this was the immediate solution I was using to filter, data. 

## Environment

<pre><code>
Angular version: ^4.2.4

Browser:
- [ x ] Chrome (desktop) version Version 63.0.3239.108 (Official Build) (64-bit) ubuntu 17.10
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x ] Firefox version 45.3.0
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.3
- Npm version: 5.5.1
- Platform:  Linux, Windows

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@kyles-repository ... I tried described above in Stackblitz demo and it works ... so what is the problem?

https://stackblitz.com/edit/angular-hjzjyz?file=app%2Fapp.component.html

**Comment by kyles-repository** [comment]
Thanks, I forked your stackblitz at https://angular-gkzrkk.stackblitz.io/#/test  you are absolutely right, while the stackblitz was, version 5, I did a re test, using the exact same version on angular 4, nothing was wrong. Closing issue. Sorry for wasting your time and thanks!
