### ISSUE TITLE
Router strange behavior

### ISSUE THREAD

**Issue by montella1507** [angular/angular#21132]
## I'm submitting a...
[x ] Bug report

## Current behavior
I have 2 built packages built at the same time, only difference is in environment file (URLs to API). 
With 1. package on "Test" environment all works correctly, with 2. package on "Prod" environment -
 Routerlinks in Menu loads LazyLoaded module (checked in Network tab) but router doesn't change route on first click - it will only download chunk. Route is changed on second click.

I know it is very hard to answer on this issue, any tip what may be the issue from your side, will be very appreciated though. Is it possible the problem could be network issue? Different hosting settings ?

## Expected behavior
Router should change route on first click.

## Minimal reproduction of the problem with instructions
It is impossible to prepare repro, because it occurs on concrete hosting.

## Environment
@angular/cli: 1.4.2
node: 7.5.0
os: win32 x64
@angular/animations: 4.3.3
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/compiler-cli: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.4.2
@angular/language-service: 4.1.3
typescript: 2.3.4

Browser:
- [ x] Chrome (desktop) version XX

 
For Tooling issues:
- Platform:  Windows, IIS

Additional information:
This problem happens only when i want to navigate via menu to lazyLoaded modules, where is "default" route to component with next <router-outlet> like it is problem for angular router to change 2 contents of outlets at the same time.

**Comment by montella1507** [comment]
LazyLoaded module WITHOUT "outlet-component" as default works:
`const inspectionRouting: Routes = [
  {
    path: '',
    component: components.InspectionsComponent
  },
  {
    path: 'plan/:id',
    component: components.InspectionsPlanComponent,
    data: {
      isPlan: true
    },
    resolve: {
      inspection: InspectionsPlanResolver
    }
  },...`


LazyLoaded module with "outlet" component as entry point doesnt work:
`const measurementRouting: Routes = [
  {
    path: '',
    component: components.MeasurementsContainerComponent,
    children: [
      {
        path: '',
        component: components.MeasurementsComponent,
        data: {
          isNew: true
        }
      },`

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

**Comment by montella1507** [comment]
Well it doesn't work only on production environments so i am not able to reproduce this behavior on my local machine / test environment.
