### ISSUE TITLE
forms api custom validators do not run on initial value

### ISSUE THREAD

**Issue by rkirov** [angular/angular#2113]
A custom directive injects `ControlDirective` and adds a custom validator in its constructor. The validator is not called on the initial value of the model passed in the constructor as  `new Control("initial text")});`

**Comment by vsavkin** [comment]
You can override the validator setter to call this:

```
    this._errors = this.validator(this);
    this._status = isPresent(this._errors) ? INVALID : VALID;
    this._updateParent();
```

**Comment by naomiblack** [comment]
On hold until @vsavkin completes his forms work. Revisit in M10.

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/commit/559f54e92b6bec612c203809968ebb83f060314e
