### ISSUE TITLE
[Question] Lazy Module Path Recommendation in Multi-App environment

### ISSUE THREAD

**Issue by dereklin** [angular/angular#21138]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In https://angular.io/guide/ngmodule#lazy-loaded-modules, the example is using absolute path:
```
const routes: Routes = [
  { path: '', redirectTo: 'contact', pathMatch: 'full'},
  { path: 'crisis', loadChildren: 'app/crisis/crisis.module#CrisisModule' },
  { path: 'heroes', loadChildren: 'app/hero/hero.module#HeroModule' }
];
```
Is the Absolute path recommended by the Angular team or is it a convention?

In a multi-app setting.  With absolute path, it will be:

```
const routes: Routes = [
  { path: '', redirectTo: 'contact', pathMatch: 'full'},
  { path: 'crisis', loadChildren: 'apps/heroes/src/app/crisis/crisis.module#CrisisModule' },
  { path: 'heroes', loadChildren: 'apps/heroes/src/app/hero/hero.module#HeroModule' }
];
```

## Expected behavior

This will work for both single app set up and multi-app set up:
```
const routes: Routes = [
  { path: '', redirectTo: 'contact', pathMatch: 'full'},
  { path: 'crisis', loadChildren: './crisis/crisis.module#CrisisModule' },
  { path: 'heroes', loadChildren: './hero/hero.module#HeroModule' }
];
```

Is it really a bad idea to use relative path?

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

`loadChildren` will be relative to the `tsconfig.json` file that compiles the application. So if there were two apps, you wouldn't be able to route to modules & components across applications. You would just need to link to a URL handled by the other application.
