### ISSUE TITLE
Angular "approved" i18n editors

### ISSUE THREAD

**Issue by natcohen** [angular/angular#21133]
I have recently made my app i18n compatible with the official documentation procedure. I'm now running into the difficulty of finding a proper xlf editor that supports all the angular "tricks" such as the `id="INTERPOLATION"  equiv-text=...` or ICU plural and select.

The team should provide at least one name of editor that works with all angular features (ideally on Windows and OSX).

**Comment by ocombe** [comment]
Hello, it is difficult for us to list those editors as we have no way of knowing if they follow our changes, and we don't want to promote external services that require you to pay.
As of 2018 I'll be working on an editor for Angular i18n on my own time, but it is still months away.

That being said, I know that the people working on the following editors have reached out to us at some point to get some details, so they probably support Angular:
- Text United: https://www.textunited.com/
- PO Editor: https://poeditor.com/

Some other editors that might work as well:
- Crowdin; https://crowdin.com/
- Get Localization: https://www.getlocalization.com/
- One Sky: https://www.oneskyapp.com
- Web translate it: https://webtranslateit.com/en

**Comment by natcohen** [comment]
@ocombe Thanks for the list! I'm very surprised to see that almost none of the services support XLIFF 2.0

**Comment by ocombe** [comment]
Yes, it doesn't seem to be widely adopted unfortunately!
