### ISSUE TITLE
DI: @Parent, @Ancestor, @Unbounded should be usable in the annotation

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2114]
E.g.

```dart
class SomeComponent(@Unbounded() EventBus) { ... }
```

Should be the same as

```dart
@Component(
  hostInjector: const [
    const Binding(EventBus, toFactory: SomeComponent.createEventBus)
  ]
)
class SomeComponent(EventBus eventbus) {
  static EventBus createEventBus(@Unbounded() EventBus eventBus) {
    return new HierarchicalEventBus.fromParent(eventBus);
  }
}
```

**Comment by mhevery** [comment]
It is not possible to extract annotations from a function :-( in dart. So I don't think we can fix that. @kegluneq  can you comment?

**Comment by matanlurey** [comment]
I'm pretty sure it is... Here is an example:

https://gist.github.com/matanlurey/b82c4779ea2c8a4dfea2

```dart
library reflection_test;
 
import 'dart:mirrors';
 
List someFunction(String string, List list, Map map) {}
 
void main() {
  ClosureMirror mirror = reflect(someFunction);
 
  // Outputs: (String, List, Map)
  print(mirror.function.parameters.map((p) => p.type.reflectedType));
}
```

**Comment by kegluneq** [comment]
It is possible in the language, but within Angular 2 all reflection runs through [reflector](https://github.com/angular/angular/blob/master/modules/angular2/src/reflection/reflector.ts) to facilitate mirror removal. Accessing annotations without mirrors requires that we register that information via `registerType`, which, true to its naming, is presently set up to deal with `Type`s only.

Making the change there would not be difficult, but the transformer is not set up to process anything except constructors at the moment. I can't think of any technical reason we can't support this scenario, but it's not currently on the road map.

**Comment by matanlurey** [comment]
That's fine. I think I'd like to keep this filed for future sugar, but I understand that it may not happen in the near future. Maybe I'll help chip in when we get closer to launch :)

**Comment by mhevery** [comment]
Stale.
