### ISSUE TITLE
HAMMER_GESTURE_CONFIG API docs should contain info on how to setup hammer support

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21146]
api doc: https://angular.io/api/platform-browser/HAMMER_GESTURE_CONFIG

Material has a small high level note on hammer but otherwise we have no docs at all: https://github.com/angular/material2/blob/master/guides/getting-started.md#step-5-gesture-support

If there is another place to mention the gesture support we should do so.

Related issue: #5766

**Comment by jbogarthyde** [comment]
Moving to the API template testing branch.
