### ISSUE TITLE
How to fetch value from the nested json array in angular?

### ISSUE THREAD

**Issue by ShilpaVKulkarni** [angular/angular#21151]
Hello,

I want to fetch the value from the nested json array in angular2.
I want to fetch the **client_id** from the following json array:

{
  "resources" : [ {
    "scope" : [ "clients.read", "clients.write" ],
    **"client_id" : "tc53EZ",**
    "resource_ids" : [ "none" ],
    "authorized_grant_types" : [ "client_credentials" ],
    "redirect_uri" : [ "http://ant.path.wildcard/**/passback/*", "http://test1.com" ],
    "autoapprove" : [ "true" ],
    "authorities" : [ "clients.read", "clients.write" ],
    "token_salt" : "C7NBIz",
    "allowedproviders" : [ "uaa", "ldap", "my-saml-provider" ],
    "name" : "My Client Name",
    "lastModified" : 1512452520895
  } ],
  "startIndex" : 1,
  "itemsPerPage" : 1,
  "totalResults" : 1,
  "schemas" : [ "http://cloudfoundry.org/schema/scim/oauth-clients-1.0" ]
}

Can anyone help me out.

Thanks & Regards
Shilpa Kulkarni

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
