### ISSUE TITLE
How to integrate an Angular application into another one

### ISSUE THREAD

**Issue by abelardolg** [angular/angular#21159]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I don't see any doc related how to integrate an Angular application into another one

## Expected behavior

An article which describes how to integrate an Angular application into another one.

## What is the motivation / use case for changing the behavior?

Anybody needs to know how to integrate an Angular application and to be reusable for other ones.

## Environment
Angular 5
<pre><code>
Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [all]
 
For Tooling issues:
- Node version: the last version 
- Platform:  any 

Others:

</code></pre>

Best regards.

**Comment by mlc-mlapis** [comment]
@abelardolg ... probably no idea what do you mean with the term `integrate an Angular application into another one`.

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by abelardolg** [comment]
Hi @mlc-mlapis 

I referred how to use a custom Angular application/component inside another one.

For example: I want to create a reusable LoginComponent Angular application to be used by other Angular applications.

In which part of your documentation is explained this process? <- That is the reason so that I created my issue. 

Best regards.

**Comment by mlc-mlapis** [comment]
@abelardolg ... it is hard to explain anything when you have no idea what ... so ... the first fact is that Angular is a framework for creating SPA apps. Your exact case is a good example for a lib / package ... which can be used later in any Angular app ... `npm install yourlib`. Actually the best tool how you can create a reusable lib is `ng-packagr` ... look here: https://github.com/dherges/ng-packagr
