### ISSUE TITLE
Style Guide - "Core Module has already been loaded" when lazy-loading routes

### ISSUE THREAD

**Issue by stephengardner** [angular/angular#21158]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

I'm either missing something or the style guide is a bit misleading when discussing the purpose of a Core Module.

Specifically, here's the issue:  When lazy-loading a route (Module), that module does not inherit the directives, components, and services of the parent AppModule (ok, good, nothing wrong here).  However, we may often need something like a Service that someone following the Style Guide would have been put in the CoreModule.

>  Create a CoreModule with providers for the singleton services you load when the application starts.
-- Style Guide

Intuition would have you importing the CoreModule again in this lazy-loaded Module.  But in doing so, you have now violated the CoreModule principle of only ever importing it once, and you will receive an error.

So my issue is that this circumstance should be better explained in the docs.  When using lazy-loading, it seems like the CoreModule is going to remain very, very small.  Even my HTTP interceptors need to be loaded again in these lazy-loaded routes, so those don't make sense in the CoreModule either.  

Am I missing something here, or could this be better explained?

Thanks for _everything_!

**Comment by Toxicable** [comment]
Providers from the top module are copied into the lazy module.
There is no need to import the Core Module again

**Comment by stephengardner** [comment]
@Toxicable I ran into [this issue](https://github.com/auth0/angular2-jwt/issues/440) with auth0/angular-jwt and HTTP interceptor providers not working for lazy-loaded modules and neglected to test other services... I'm now realizing that yes, other services are being inherited.  I think I ran into a funky side-issue and generalized it.  You're correct.  Thanks.  Closing

**Comment by code-atom** [comment]
@Toxicable, Why Lazy Load Module Route does not include Core module component?
Please live example: https://stackblitz.com/edit/angular-2kwxtw

Lazy load module route not able to use core module components and directive why? I create a Shell Component which I use when creating child route of the lazy-loaded module. but when i navigate to lazy load module, they said there is no shell component exist in @Ngmodule.

please explain why this happened ? if try to import core module again in lazy load module then error shown is you can only import core module in App module

**Comment by sarunint** [comment]
If you are following the style guide, there will be `CoreModule` and `SharedModule` confusion.

`CoreModule` is for things that are "providable". (Mainly services) It should be imported only once at the root `AppModule`.

`SharedModule` are for things that are "declarable". (Components, pipes, directives) It can be import many times.
