### ISSUE TITLE
BUG: InjectionToken is not assignable to ViewChildren or ContentChildren

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#21152]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If i have `InjectionToken` i cant assign it to `ViewChildren` or `ContentChildren` as mentioned in https://github.com/angular/angular/issues/12758 Maybe due to changes of Typescript.

## Expected behavior
This code is working if you type it to `<any>` but without it cant be compiled using typescript.

## Minimal reproduction of the problem with instructions
This will not compile :).

``` typescript
export const SomeClassToken = new InjectionToken<SomeClass>('SomeClassToken');

export class TestClass
{
    @ViewChildren(SomeClassToken)
    public children: QueryList<SomeClass>;
}
```

## What is the motivation / use case for changing the behavior?
It should compile, because it works if typed to `<any>`.

## Environment

<pre><code>
Angular version: 5.1.2

Browser:
During compilation
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Typescript version: 2.5.3
- Node version: 8.1.2  
- Platform:  Windows 

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
> This will not compile :).

And IMO this is the intention as you can only query for:
* names (type: `string`)
* directive instance type (type: `Type`)

See: https://github.com/angular/angular/blob/master/packages/core/src/metadata/di.ts#L295

Not sure what you are trying to achieve, but the current typing is intentional.

**Comment by kukjevov** [comment]
Well if it is intentional, then see recomended solution for https://github.com/angular/angular/issues/12758 by @tbosch  and tell me how can you do it? 

What im trying to do is get all components that inherits from super class, it is exactly what that issue mentioned above is talking about. 

If you want to have dynamic content and you have base class and then 2 various components that inherits from that base class and you want to get via `ViewChildren` or `ContentChildren` all components that inherits from that base class that is only way to do it. 

Funny thing is if it is intentional, so why it is working? When you ignore types and use `any` it works.

**Comment by pkozlowski-opensource** [comment]
You can query for a type instead of `InjectionToken`: http://plnkr.co/edit/S5k0c28x0j5lmfEOoRGE?p=preview

In any case, I think that there is a discrepancy here between _intention_ and _implementation_ in place.

**Comment by ghetolay** [comment]
I'm also confused by that.
Why does view queries are restricted to type token ? 

Especially when it's working fine with `InjectionToken` as op said, I also experienced it.
Using an empty class as a token instead of an `InjectionToken` to get around this sounds like a silly workaround.

**Comment by kukjevov** [comment]
I have BaseClass, then i have MyComponentClass and MyComponentClass2.

Now i have this html template.

```html
<my-component1></my-component1>
<my-component2></my-component2>
```

How can i query them in `ViewChildren` in single property? I dont care about concrete implementation, because everything i need is defined in `BaseClass`.

If i use `ViewChildren(BaseClass)` it will not work, it returns empty `QueryList` so i cant use type. Only solution that works and i repeat this again is using `InjectionToken` (as recommended by @tbosch) where it is used as `ExistanceProvider` with multi value which is Provided by `MyComponentClass` and `MyComponentClass2` component providers.

So tell me how can i get all different implementations of `BaseClass` in single `QueryList` if it does not does not work while querying `BaseClass` and i should not use `InjectionToken` even if it is working?

Thank you :)

**Comment by kukjevov** [comment]
Ok sorry, i have open your plunker and i see what you mean. Ok it is possible to use type for this, but i still think it is misuse of "fictional" class created. I think `InjectionToken` was created exactly for this purpose, otherwise we could have always use some dummy class and use it instead of `InjectionToken`.

**Comment by arlowhite** [comment]
In a complex application, your component could already be extending a class but still want to _implement_ and _provide_ a small interface shared by many components. In this situation you would need this `@ViewChildren(MY_INJECTION_TOKEN)` feature. Without this feature, you'd have to do a painful refactor and make all the components extend the same class even if it doesn't make sense for your design.

**Current Solution Tip**
Since no one has mentioned it, when  `MyComponent extends BaseClass`, you also need to **provide** BaseClass:

In **my-component.ts**'s  `@Component({providers: ...})`
```typescript
    { provide: BaseClass, useExisting: forwardRef(() => MyComponent)},
```

- BaseClass can be abstract
- Not sure if provide line should have `multi: true`

**Comment by waterplea** [comment]
I was very surprised to find it doesn't work and what is even stranger is it does indeed work if you write it like that:
`@ContentChild(MY_TOKEN as any) something: SuperClass;`
Please fix this as it is scary to use like that.

**Comment by pkozlowski-opensource** [comment]
Agree that we should adjust types since it is an useful pattern which works in practice. At this point the only thing that is broken are types, really. Confirming as a bug.
