### ISSUE TITLE
5. Section - Final Code review missing hero-detail.component.css

### ISSUE THREAD

**Issue by bobbyangers** [angular/angular#21166]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

is showing the css for heoes.component.css

## Expected behavior

should show the css for hero-detail.component.css

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by bobbyangers** [comment]
Hi,
the title correspond to the section and paragraphe. Also Angular5.

--Robert Angers
m:514-557-8074

Sent from my iPhone

On Jan 12, 2018, at 13:44, Kapunahele Wong <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @bobbyangers<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbobbyangers&data=02%7C01%7C%7Cd6546a0b298c42b6592608d559ec8628%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636513794745240243&sdata=n8dlPU2K%2FbIdHwAPwW3kozWxLHUnQzbE%2BA%2FutngC2hY%3D&reserved=0> could you link me to the spot that needs attention? I'm not sure which page and section it's on. Thank you!

**Comment by kapunahelewong** [comment]
Ah, I see what you mean. The reason `hero-detail.component.css` is left out of the code tabs is because it doesn't contain any styles (though if you had a project like this you could certainly put styles in there for that component), and because it doesn't effect the action/functionality of the component. 

For the curious, here's the link: [https://angular.io/tutorial/toh-pt3#final-code-review](https://angular.io/tutorial/toh-pt3#final-code-review).

@bobbyangers I hope this helps. Thanks for keeping an eye out. I'll close this but if you have any outstanding questions, feel free to tag me.

**Comment by bobbyangers** [comment]
Hi,

I checked the final zip;
hero-detail.component.css. >> has some data
hero.compnent.css  >> empty;

The tab is showing the wrong one.

--Robert Angers
m:514-557-8074

Sent from my iPhone

On Jan 17, 2018, at 10:04, Kapunahele Wong <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, I see what you mean. The reason hero-detail.component.css is left out of the code tabs is because it doesn't contain any styles (though if you had a project like this you could certainly put styles in there for that component), and because it doesn't effect the action/functionality of the component.

For the curious, here's the link: https://angular.io/tutorial/toh-pt3#final-code-review<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fangular.io%2Ftutorial%2Ftoh-pt3%23final-code-review&data=02%7C01%7C%7C1c78507b2d8046be30f008d55dbb9749%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636517982627823616&sdata=m101fCt2J5g4GqlFVEyLUDdmSAOJI0g5OEzcgf2ErtM%3D&reserved=0>.

@bobbyangers<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbobbyangers&data=02%7C01%7C%7C1c78507b2d8046be30f008d55dbb9749%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636517982627823616&sdata=h6syBaz551JVj8GZ3JCupTmenNz636C7svMjpUL7eSk%3D&reserved=0> I hope this helps. Thanks for keeping an eye out. I'll close this but if you have any outstanding questions, feel free to tag me.

**Comment by kapunahelewong** [comment]
Thanks @bobbyangers, I'm reopening to make sure we address it. Maybe I was looking at the wrong file ([https://angular.io/tutorial/toh-pt3#final-code-review](https://angular.io/tutorial/toh-pt3#final-code-review)).

So I checked to see if you meant this one instead
[https://angular.io/tutorial/toh-pt1#final-code-review](https://angular.io/tutorial/toh-pt1#final-code-review), but this one doesn't include any css in the tabs either. Could you link me to the spot? Part of this might be the numbering issue in the tutorial - the files are named with different numbers than the actual parts of the tutorial. Thanks!

**Comment by jenniferfell** [comment]
@kapunahelewong : Hi. Thanks for your previous investigation on this. Do you have an update in the works from back then (or want to do one), or should I put this in @chembu queue? Thx.

**Comment by chembu** [comment]
Even I could not find the wrong CSS file in the final code review tab.

**Comment by kapunahelewong** [comment]
Closing this one as neither @chemu or I could find the issue. Part 5, Routing, which may be what the title of this issue is referring to, does have `hero-detail.component.css` in the Final Code Review tabs section, as it was edited in that part of the tutorial. It may have been added since this issue was submitted. As a side note, Part 6, HTTP, doesn't have that css file, but it isn't edited in that step of the tutorial as it was in Step 5, Routing.
