### ISSUE TITLE
** Wilcard URL matching is not working in 5.1.0

### ISSUE THREAD

**Issue by vijayamurugan** [angular/angular#21160]
## I'm submitting a...

<pre><code>
[ X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If URL does n't match it's not redirecting to the Error page as per the redirecTo value

## Expected behavior
It should redirecto the relevant page if unmatch URL been found

## Minimal reproduction of the problem with instructions
```
{ path: '**', pathMatch: 'full', redirectTo: 'error' },
      { path: 'error', component: ErrorpageComponent }
```

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue)  (**READ THIS LINK**) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by jasonaden** [comment]
As there's no update here, and no reproduction provided, I'm closing the issue. If this is still a problem, please open a new issue.
