### ISSUE TITLE
Get a exception unhandled error in a _for-of.js[dynamic] file

### ISSUE THREAD

**Issue by frostless** [angular/angular#21162]
I integrated Angular 5 with .net core 2.
In angular-cli.json file,I set the <code>app["outdir"]</code> to <code>/wwwroot</code> and use <code>ng build</code> to output the static asset file to the<code> wwwroot</code>.

Everything is working fine(chrome/Edge) except in IE that I will get this error:

<pre>
Unhandled exception at line 795, column 36 in http://localhost:59299/polyfills.bundle.js
0x800a139e - JavaScript runtime error: Exception thrown and not caught occurred
</pre>

It is from a dynamic .js file and even if I manually go to its directory<code> /node_modules\core-js\modules\_for-of.js</code>

and add the handler it is still not working.

<pre> try {
      if (typeof iterFn != 'function') throw TypeError(iterable + ' is not iterable!');
  }
    catch(e) {

  }
</pre>

Visual Studio will stop by this error, and even it I hit continue, IE will not render as expected. 
I was trying to iterate and IEnumerable list.

Local machine OS :windows 10
IDE:visual studio community 2017
IE version:11.125.16299.0

**Comment by Toxicable** [comment]
have you added the right polyfills? 
https://angular.io/guide/browser-support

**Comment by frostless** [comment]
solved

**Comment by travisudd** [comment]
tsconfig.json (change "target": "es5" to "es6"). polyfillls.ts uncomment import 'core-js/es6/... items under comment IE9, IE10 and IE11 requires all of the following polyfills. Then IE11 will work.

**Comment by enr1c091** [comment]
I am currently facing the same issue.. I already uncommented all IE11 polyfills and changed tsconfig.json to es6.

**Comment by nickbullock** [comment]
I am currently facing the same issue. ES6 polyfills doesn't help.

**Comment by Bhavin3184** [comment]
Same issue here....I tried all as mentioned above.
 nickbullock  : have you found anything ?

**Comment by nickbullock** [comment]
@Bhavin3184 my issue was related to https://github.com/storybooks/storybook/issues/3522
And solution for me is to include babel-polyfill, which includes much more polyfills than the polyfills.ts

**Comment by moequraishi** [comment]
I am still getting this error, I have tried everything, from uncommenting the imports polyfills.ts to adding `<meta http-equiv="X-UA-Compatible" content="IE=edge" />` and none of these did anything, same error over and over again.

Running out of options.

**Comment by PTC-JoshuaMatthews** [comment]
I am seeing this as well. Disappointing to see this has been open since February as I find out that our large production codebase that we finally got up and running on CLI is no longer compatible with IE.
