### ISSUE TITLE
Locale data for es-MX is not capitalized

### ISSUE THREAD

**Issue by clundberg1** [angular/angular#21169]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

After importing the locale data for es-MX setting the LOCALE_ID to use that value, the Date pipe returns "diciembre 31, 2017"

## Expected behavior
It should return the month capitalized: "Diciembre 31, 2017"

## Minimal reproduction of the problem with instructions
Go into the file @angular/common/locales/es-MX.js and you will notice none of the days or months are capitalized.

## Environment

Angular 5.0.0

**Comment by ocombe** [comment]
Hello, as of Angular 5 we use CLDR data for all i18n values, if you believe that the days/months should be capitalized, please open an issue on the CLDR repository: http://cldr.unicode.org/index/bug-reports

Thanks!
