### ISSUE TITLE
Make `AbstractControl#value` a union of `T` and `ValidationErrors`

### ISSUE THREAD

**Issue by yawaramin** [angular/angular#21168]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`AbstractControl#value` currently has type `any` (after #20040, it will have generic type `T`). `AbstractControl#errors` has type `ValidationErrors | null`. Currently we have to manually check for validation errors. It's easy to forget this check.

## Expected behavior

- Type `ValidationErrors` is redefined as `interface ValidationErrors<T> {currentValue: T, validators: Set<string>}`
- There is a type `ValueOrErrors<T>` defined as `T | ValidationErrors<T>`
- There is a corresponding namepace `ValueOrErrors` with predicate functions that test `ValueOrErrors<T>` values to determine their runtime subtype (`T` or `ValidationErrors<T>`)
- There is a property `AbstractControl#valueOrErrors` with type `ValueOrErrors<T>`
- `AbstractControl#value` is deprecated and later removed
- `AbstractControl#errors` is deprecated and later removed
- `AbstractControl#valid` is deprecated and later removed
- `AbstractControl#invalid` is deprecated and later removed

This forces the developer to check for errors in order to compile their code. It also decouples the concepts of a form control having a value/error from queries on the value/error type. E.g.:

```typescript
if (ValueOrErrors.isValue(inputName.valueOrErrors))
  PersonService.add(inputName.valueOrErrors);
else
  console.log(inputName.valueOrErrors.validators);
```

## Minimal reproduction of the problem with instructions

Example copied from https://angular.io/guide/form-validation :

```typescript
ngOnInit(): void {
  this.heroForm = new FormGroup({
    'name': new FormControl(this.hero.name, [
      Validators.required, Validators.minLength(4)])
  });
}

// ... type in 'Bob' in the 'name' field ...

// Returns 'Bob' which hasn't passed the minimum length validation:
get name() { return this.heroForm.get('name'); }
```

## What is the motivation / use case for changing the behavior?

Forms gather input from the untrusted outside world, hence it makes sense to make them as safe as possible. Recruiting the TypeScript compiler to help enforce safety checks is a big benefit.

## Environment

<pre><code>
Angular version: (all)

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

Depends on: #20040

**Comment by Toxicable** [comment]
How will you tell the difference between a value and an error?
An `AbstractControl#value` can be anything from a primitive `number | string | boolean` to a complex object in the case of a `FormGroup`, the same type as the error object.
Therefore there is no reasonable or easy way to tell the difference between an error and an actual value.

**Comment by yawaramin** [comment]
@Toxicable if we make `ValidationErrors<T>` a nominal type, in other words constructed using an ES6-style class i.e. using a function constructor--in this case, would we ever have an `AbstractControl<ValidationsErrors<T>>`? (Again, this is not a JS structural object.) Is that something that can happen?

My guess is no, that would not make any sense. We can test for nominal function-constructed types like this using `instanceof`, so it's possible to implement the type predicates.

**Comment by Toxicable** [comment]
A class instance here would work since you could do something like
```
submit(value: ValidationErrors | T){
  if(value instanceof ValidationErrors) {
     //handle errors
   } else {
    //submit
  }
}
```
However this brings more issues with it.
- it's the same amount of code we started with
- it's impossible to check for errors in templates since `{{value instanceof ValidationErrors}}` is invalid

Aside from those issues the larger issue here is the breaking change.
I don't see how we could make this an in place change, therefore we'd have to make a "ReactiveForms2" just for this change which I think is unacceptable

**Comment by yawaramin** [comment]
There isn't a managed process (i.e. deprecation warning, staged rollout) for breaking changes in Angular now?

**Comment by Toxicable** [comment]
The policy for breaking changes is that
- New API is introduced
- Old APi is marked as deprecated 
- Once old API has been deprecated for the length of one Major version it is removed

Think of `Renderer`, it went through this process with `Renderer2` being the new API.

The point here is that we cannot make a in place breaking change even on a major version bump, the API must go through the deprecation period

**Comment by yawaramin** [comment]
OK, by 'in-place' breaking change you are considering the entire `AbstractControl` class to be a single unit of change, I think? I was looking at it at the method level, hence deprecating some existing methods/getters and adding a new getter and a couple of new types seemed feasible.

Btw, I looked at templates and it seems it would be something like this:

```
<div *ngIf="ValueOrErrors.isErrors(name.valueOrErrors)">
  Errors!
</div>
```

It seems string interpolation is not used for checking validation at all?

**Comment by Toxicable** [comment]
Even on a method level, that has to be done via a depreciation period, we cannot break peoples code without it.

>ValueOrErrors.isErrors(name.valueOrErrors)

I have two issues with this
- it's a function call, which I very often discourage since it can easily lead to slow CD runs when there are side effects 
- what is `ValueOrErrors`? Is it another thing we have to define on our component classes? it's just making it more difficult and less intuitive to find if a control has errors

**Comment by yawaramin** [comment]
I totally agree that even on a method level there has to be a deprecation period. You mentioned a period of at least one major release before the deprecated items are removed, I fully agree with that. This is why I arranged the change as adding the new getter at the same time as deprecating the old ones.

Regarding your two points:

- Correct, this is a function call, but it's also a type predicate, which merely checks the runtime type of some value. The implementation I have [prototyped](https://www.typescriptlang.org/play/index.html#src=class%20ValidationErrors%3CT%3E%20%7B%0D%0A%20%20_currentValue%3A%20T%3B%0D%0A%20%20_validators%3A%20Set%3Cstring%3E%3B%0D%0A%0D%0A%20%20constructor(currentValue%3A%20T%2C%20validators%3A%20Set%3Cstring%3E)%20%7B%0D%0A%20%20%20%20this._currentValue%20%3D%20currentValue%3B%0D%0A%20%20%20%20this._validators%20%3D%20validators%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20get%20currentValue()%3A%20T%20%7B%20return%20this._currentValue%3B%20%7D%0D%0A%20%20get%20validators()%3A%20Set%3Cstring%3E%20%7B%20return%20this._validators%3B%20%7D%0D%0A%7D%0D%0A%0D%0Atype%20ValueOrErrors%3CT%3E%20%3D%20T%20%7C%20ValidationErrors%3CT%3E%3B%0D%0A%0D%0Anamespace%20ValueOrErrors%20%7B%0D%0A%20%20export%20function%20isValue%3CT%3E(v%3A%20ValueOrErrors%3CT%3E)%3A%20v%20is%20T%20%7B%0D%0A%20%20%20%20return%20!(v%20instanceof%20ValidationErrors)%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20export%20function%20isErrors%3CT%3E(v%3A%20ValueOrErrors%3CT%3E)%3A%20v%20is%20ValidationErrors%3CT%3E%20%7B%0D%0A%20%20%20%20return%20v%20instanceof%20ValidationErrors%3B%20%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20AbstractControl%3CT%3E%20%7B%0D%0A%20%20_t%3A%20ValueOrErrors%3CT%3E%3B%0D%0A%20%20constructor(t%3A%20T)%20%7B%20this._t%20%3D%20t%3B%20%7D%0D%0A%20%20get%20valueOrErrors()%3A%20ValueOrErrors%3CT%3E%20%7B%20return%20this._t%3B%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20inputName%20%3D%20new%20AbstractControl(%22Name%22)%3B%0D%0A%0D%0Aif%20(ValueOrErrors.isValue(inputName.valueOrErrors))%0D%0A%20%20console.log(inputName.valueOrErrors)%3B%0D%0Aelse%0D%0A%20%20console.log(inputName.valueOrErrors.validators)%3B%0D%0A) is totally side-effect free, and I wouldn't be surprised if most VMs just optimise away the function call altogether.
- `ValueOrErrors` is a type and its associated namespace which I am proposing to add to Angular to represent a control's current value or errors if the input fails validation. We wouldn't redefine it in component classes--we would use it everywhere and it would surface validation errors more effectively since you'd have to call `control.valueOrErrors` to get at the control's current value, and when you looked up the API docs you'd see it's giving you back a result of type `ValueOrErrors`, and when you look up that type in the docs you'll see the type predicate functions which help you test whether you have a value or validation errors. In short, you would be forced to check for validation errors before you could access the control's value.
