### ISSUE TITLE
Unexpected value 'PropDecoratorFactory' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by jaydeepkarena** [angular/angular#21161]
the app compiles successfully, but in browser i'm getting this error

ncaught Error: Unexpected value 'PropDecoratorFactory' imported by the module 'AppModule'. Please add a @NgModule annotation.     at syntaxError (compiler.js:485)     at eval (compiler.js:15204)     at Array.forEach (<anonymous>)     at CompileMetadataResolver.getNgModuleMetadata

main.ts

`import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.log(err));
`

app.module.ts
`
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, Input } from '@angular/core';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    Input
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { 
}

`

app.component.ts
`
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  @Input() articleText;
  title = 'Article Dictionary!';

  convertToDictionary(articleText: string): void {
    console.log(articleText);
  }
}

`

app.component.html
`
<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>
</div>
<div>
  <label for="article">paste your text here:</label>
  <input type="button" value="Convert to Dictionary" (click)="convertToDictionary()">
  <br>
  <br>
  <textarea name="article" id="article" cols="100" rows="30" [articleText]="name.value" #name>

  </textarea>

</div>

`

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) (**READ THIS LINK CAREFULLY**) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
