### ISSUE TITLE
implementing markdown editor

### ISSUE THREAD

**Issue by Stoffel-KT** [angular/angular#21177]
For the last 4 days I've been trying to implement a markdown editor with no succes unfortunately.
I've been trying to implement the ng2-simplemde package but I can't get it to show up/work.

I've been looking all over the internet for tips and have been hoping to get my eureka moment but this time it doesn't seem to be happening.

Could anybody please help me with some tips or advice, I'm completely stuck :(

**Comment by mlc-mlapis** [comment]
@Stoffel-KT ... I tried it and it works as expected ... just:

* installing as a new lib: `npm i ng2-simplemde`
* adding to the main module:
```
import { SimplemdeModule, SIMPLEMDE_CONFIG } from 'ng2-simplemde'
...
imports: [
	BrowserModule,
	SimplemdeModule.forRoot({
		provide: SIMPLEMDE_CONFIG,
		useValue: {placeholder: '111'}
	})
],
```
* adding the new tag to a template - even without any callback:
```
<simplemde></simplemde>
```

**Comment by robwormald** [comment]
@Stoffel-KT because of the volume of issues we get, we can't accept support requests on Github issues - you might join the gitter channel https://gitter.im/angular/angular and ask this question there.

Thanks!
