### ISSUE TITLE
AIO(docs) Routing & Navigation section missing CrisisCenterModule.ts

### ISSUE THREAD

**Issue by hartraft** [angular/angular#21174]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In the AIO docs for "Routing & Navigation" [Milestone 4: Crisis center feature](https://angular.io/guide/router#milestone-4-crisis-center-feature), [step 4](https://angular.io/guide/router#import-crisis-center-module-into-the-appmodule-routes) mentions to import the CrisisCenterModule but no reference has been mentioned in the previous steps. This may be confusing

## Expected behavior
Add a code snippet for the CrisisCenterModule

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?
Make it easier to follow the AIO docs

## Environment

<pre><code>
Angular version: 5.1.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by hartraft** [comment]
Thanks for taking a look at this. Just to add a bit more detail on the "Routing and Navigation" docs, I also saw that in **Milestone 1** and **Milestone 2**, all components have inline templates in the examples (for src/app/app.component.ts, src/app/hero-list.component.ts etc.). 

However by the time you get to **Milestone 3**, the plunker and zip mentioned have components using the templateUrl.

> This example recreates the heroes feature in the "Services" episode of the [Tour of Heroes tutorial](https://angular.io/tutorial/toh-pt4), and you'll be copying much of the code from the [Tour of Heroes: Services example code](https://angular.io/generated/live-examples/toh-pt4/eplnkr.html) / [download example](https://angular.io/generated/zips/toh-pt4/toh-pt4.zip).

and

> ### Add heroes functionality
>
> Follow these steps:
>
>    - Create the src/app/heroes folder; you'll be adding files implementing hero management there.
>
>    - Delete the placeholder hero-list.component.ts that's in the app folder.
>
>    - Create a new hero-list.component.ts under src/app/heroes.
>
>    - Copy into it the contents of the app.component.ts from the ["Services" tutorial](https://angular.io/generated/live-examples/toh-pt4/eplnkr.html) / [download example](https://angular.io/generated/zips/toh-pt4/toh-pt4.zip).
>
>    - Make a few minor but necessary changes:
>       - Delete the selector (routed components don't need them).
>       - Delete the `<h1>`.
>       - Relabel the `<h2>` to `<h2>HEROES</h2>`.
>       - Delete the `<hero-detail>` at the bottom of the template.
>       - Rename the AppComponent class to HeroListComponent.

This causes two issues. First the plunker and zip are inconsistent with the rest of the documentation in the "Routing & Navigation" section.

Secondly, the step "Make a few minor but necessary changes:" wouldn't make sense as there is no mention of `<h1>` and other elements (as the linked examples only include the templateUrl line). 

Sure we can do a translation in our heads but the documentation is incorrect as it stands. Perhaps it's a regression from changing the documentation examples. Do you want me to create a new issue for this instead?

**Comment by brandonroberts** [comment]
Fixed via https://github.com/angular/angular/pull/20023
