### ISSUE TITLE
Geometry Multipolygon

### ISSUE THREAD

**Issue by vinicius8488** [angular/angular#21175]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Expected behavior
 Need to work with geometry multipolygon, like tag: aol-geometry-multipolygon but in actual version this is not implemented

## What is the motivation / use case for changing the behavior?
It will be very helpful to work with vector feature selection in complex areas

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@vinicius8488 ... you can try to use `ng2-konva` ... library for drawing complex canvas graphics using Angular.

https://www.npmjs.com/package/ng2-konva

**Comment by lazarljubenovic** [comment]
This feature request is too scoped to a very specific use-case and thus does not belong to the Angular repo. You need to find or create a third party library to handle it.
