### ISSUE TITLE
using loadChildren for non lazily loaded modules not working on AOT build

### ISSUE THREAD

**Issue by dereklin** [angular/angular#21170]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When using loadChildren to load non-lazy modules. The page shows this error in console log:
```
Error: Runtime compiler is not loaded
```
Please see this issue for more info: https://github.com/angular/angular-cli/issues/5460

## Expected behavior

The modules should be loaded eagerly and correctly.

## Minimal reproduction of the problem with instructions

Please see this issue: https://github.com/angular/angular-cli/issues/5460
## What is the motivation / use case for changing the behavior?

bug fix
## Environment
AOT Prod build
<pre><code>
Angular version: X.Y.Z

5.1.0
Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
... why are you trying to use `loadChildren` for non lazily loaded modules at all?

**Comment by dereklin** [comment]
I watched https://www.youtube.com/watch?time_continue=1&v=66XR8EnFepA

Check out from 1:02:32 to 1:04:35

It seemed to suggest loadChildren can be used for non-lazy modules

Can someone confirm otherwise?

**Comment by trotyl** [comment]
You could, but on your own tooling rather than Angular CLI.

Angular has no idea how modules are organized, if you're using AOT, you'll need to provide the `NgFactory` of `NgModule` (or its path), rather than `NgModule` itself.

Anyway this is beyond the scope of this repo, it's tooling specific.

**Comment by mlc-mlapis** [comment]
@dereklin ... actually Angular router supposes default syntax (JIT x AOT) ... `loadChildren: '.../XXX.module#XXXModule'` ... and then for JIT mode (recognized by the compiler availability via DI) loads `XXX.module.js` ... and for AOT (recognized by the inaccessibility of the compiler via DI) loads `XXX.module.ngfactory.js`. **So as you can see the key is the syntax of `#XXXModule`.**

**Comment by dereklin** [comment]
OK. I have confirm this is not supported right now.  There are other github issues regarding this, like: https://github.com/angular/angular-cli/issues/4192

I am not sure if the core team is going to tackle this or not.

Feel free to close it if it's not a planned feature.

**Comment by jasonaden** [comment]
Thanks. This isn't something we are going to be tackling right now. We may take another look at lazy loading in the near future, but it would be a more wholistic approach, not specific to routing.

**Comment by aog1971** [comment]
the solution, 
Your problem is the following code:

new webpack.ContextReplacementPlugin(
    // The (\\|\/) piece accounts for path separators in *nix and Windows
    /angular(\\|\/)core(\\|\/)@angular/,
    helpers.root('./src'), // location of your src
    {} // a map of your routes
),
To understand why this plugin causes the issue when building aot you should know how @angular/cli produces lazy loading modules. It's very complicated process. But the key point here is that it relies on @angular/core/src/linker path.

Since you're replacing that path then map for lazy loading modules won't be generated (angular/cli uses ContextElementDependency for that).

So try disabling ContextReplacementPlugin for production build.

see:
https://stackoverflow.com/questions/47038516/aot-ngtools-webpack-lazy-loading-does-not-work-using-angular-4-webpack-3
