### ISSUE TITLE
[ts] Parameter declaration expected. (method) AddPhotosComponent.function($: any): void

### ISSUE THREAD

**Issue by PriyankaVansadia** [angular/angular#21178]
**AddPhotos.component.ts**

import { Component, ElementRef, EventEmitter, Input, Output, ViewChild, OnInit } from '@angular/core';
import './addphoto.js';
import { Router } from '@angular/router';
import { RouterModule, Routes } from '@angular/router';
import { BasicInfoService } from "../../basicInfo.service";
import * as firebase from 'firebase';
import { Header, ImageService } from '../sidebar/image.service';
import * as $ from "jquery";
import { Event } from '@angular/router/src/events';
@Component({
  selector: 'AddPhoto',
  templateUrl: './AddPhotos.html'
})
export class AddPhotosComponent implements OnInit {

    jQuery(function($)   { 
    var fileDiv = document.getElementById("upload");
    var fileInput = document.getElementById("upload-image");
    console.log(fileInput);
    fileInput.addEventListener("change", function (e) {
      var files = this.files;
      showThumbnail(files)
    }, false)

    fileDiv.addEventListener("click", function (e) {
      $(fileInput).show().focus().click().hide();
      e.preventDefault();
    }, false)

    fileDiv.addEventListener("dragenter", function (e) {
      e.stopPropagation();
      e.preventDefault();
    }, false);

    fileDiv.addEventListener("dragover", function (e) {
      e.stopPropagation();
      e.preventDefault();
    }, false);

    fileDiv.addEventListener("drop", function (e) {
      e.stopPropagation();
      e.preventDefault();

      var dt = e.dataTransfer;
      var files = dt.files;

      showThumbnail(files)
    }, false);

    function showThumbnail(files) {
      for (var i = 0; i < files.length; i++) {
        var file = files[i]
        var imageType = /image.*/
        if (!file.type.match(imageType)) {
          console.log("Not an Image");
          continue;
        }

        var image = document.createElement("img");
        // image.classList.add("")
        var thumbnail = document.getElementById("thumbnail");
        image.file = file;
        thumbnail.appendChild(image)

        var reader = new FileReader()
        reader.onload = (function (aImg) {
          return function (e) {
            aImg.src = e.target.result;
          };
        }(image))
        var ret = reader.readAsDataURL(file);
        var canvas = document.createElement("canvas");
        ctx = canvas.getContext("2d");
        image.onload = function () {
          ctx.drawImage(image, 100, 100)
        }
      }
    }
  });
}

i am getting error on this line 
 **jQuery(function($)   {** 

**error line**

[ts] Parameter declaration expected.
(method) AddPhotosComponent.function($: any): void

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by matthew-ch** [comment]
Your code doesn't make sense. You are invoking `jQuery` function inside class definition.
I suppose what you want might be:
```typescript
export class AddPhotosComponent implements OnInit {
  ngOnInit() {
    jQuery(/* ... */);
  }
}
```
Also, since you are using Angular now, you could ditch the `jQuery` way of doing things.
