### ISSUE TITLE
UNMET PEER DEPENDENCY ERROR issue with  "@angular/common": "~4.4.6",     "@angular/compiler": "^4.2.4",     "@angular/core": "~4.4.6",.

### ISSUE THREAD

**Issue by nani2nithin** [angular/angular#21179]
Here I gave the error message please give me the solution

admin@0.0.0 E:\tcare\admin
+-- UNMET PEER DEPENDENCY @angular/common@4.4.6
+-- UNMET PEER DEPENDENCY @angular/compiler@4.2.6
`-- UNMET PEER DEPENDENCY @angular/core@4.4.6

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/cdk@5.0.2 requires a peer of @angular/core@~5.1.0 but none was installed.
npm WARN @angular/cdk@5.0.2 requires a peer of @angular/common@~5.1.0 but none was installed.
npm WARN @angular/compiler@4.2.6 requires a peer of @angular/core@4.2.6 but none was installed.
npm WARN @angular/compiler-cli@4.4.6 requires a peer of @angular/compiler@4.4.6 but none was installed.
npm WARN @angular/material@5.0.2 requires a peer of @angular/core@~5.1.0 but none was installed.
npm WARN @angular/material@5.0.2 requires a peer of @angular/common@~5.1.0 but none was installed.
npm WARN @angular/platform-browser-dynamic@4.4.6 requires a peer of @angular/compiler@4.4.6 but none was installed.
npm ERR! code 1

**Comment by IgorMinar** [comment]
Please ensure that all of your @angular/* packages (except for cdk, material and cli) use the save version number

**Comment by srinivas444** [comment]
By Installing the failed UNMET dependencies globally one by one will help you, Because it's worked for me.

example :  npm install -g @angular/common@4.4.6
