### ISSUE TITLE
docs(ToH): use interface instead of class to define the Hero model

### ISSUE THREAD

**Issue by jotatoledo** [angular/angular#21186]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The ToH defines the Hero model using a **class**, but in the tutorial "instances" of this class arent created using the ctor of the class, promoting a bad practice. 

Furthermore the use of a class for this model is IMO inappropriate, as the class defines no behavior (methods). An interface would be better suited for this use case.

An example extracted from the tutorial:

```
class Hero {
  id: number,
  name: string,
}

const aHero: Hero = {
  id: 1,
  name: 'Superman'
}
````
Type checking will result in the following:

````
console.log(aHero instanceof Hero); //false
````

## Expected behavior
The Hero model should be defined using an **interface**.

## Minimal reproduction of the problem with instructions

Check the [ToH](https://angular.io/tutorial/toh-pt1#create-a-hero-class)

**Comment by kevincoscarelli** [comment]
Hi @jotatoledo , the real example code is [here](https://angular.io/tutorial/toh-pt1) , in the [stackoverflow question](https://stackoverflow.com/questions/47996399/typescript-using-classes-without-constructor) I modified it for the sake of brevity.

**Comment by trotyl** [comment]
Relates to or duplicate of #19632

**Comment by jenniferfell** [comment]
docsarea=tutorial

**Comment by chembu** [comment]
The style guide is updated. Keeping #21186 open to considering the implementation of the TOH tutorial.

**Comment by kapunahelewong** [comment]
Confirmed that this should be `interface`. Adding to Committed in Docs Project board so we can submit a PR.
