### ISSUE TITLE
[Feature Request] [Service Worker] DataGroups configurable with query parameters

### ISSUE THREAD

**Issue by josephliccini** [angular/angular#21189]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Right now, Service Worker will cache data in the cache using the entire URL as the key.  It would be nice to have data groups of the same base URL to have different expiration / performance policies for query parameters.

For example:
We have an API: `/documents`.  It provides a list of documents.  It also returns an ID called the `knowledge` parameter, which is a special ID that represents the current state of the user's document list.  I'd like to have this call use the `'performance'` strategy.

We can use the API `/documents?knowledge=KNOWLEDGE_ID` to fetch the delta of documents that have changed.  I'd like to have this call use the `'freshness'` strategy.

## Expected behavior

I am not sure if this is already supported, and in that case, it should be documented.

If it is not supported, I have been brainstorming of some ideas.

One is that the `dataGroups` entry in the `ngsw-config.json` could have a property: `queryParameters`, like this:

```json
"dataGroups": [{
    "name": "documents-fetch",
    "urls": [ "/documents" ],
    "strategy": "performance"
}, {
    "name": "documents-sync",
    "urls": [ "/documents" ],
    "queryParameters": [ "knowledge" ],
    "strategy": "freshness"
}]
```

Just brainstorming, but maybe the algorithm could select the _most specific_ query parameters for the same URLs if the URL matches in a group.

## Minimal reproduction of the problem with instructions

N/A

## What is the motivation / use case for changing the behavior?

To have configurable SW API caching based on query parameters as well as URL.

## Others:

This article isn't exactly the same thing, but there might be some prior work within Google and `sw-precache`: https://developers.google.com/web/showcase/2015/service-workers-iowa#watch_out_for_extra_query_parameters

**Comment by tfiwm** [comment]
Hello everybody :) This feature is already a long time in the backlog :( Any chance to push it? I think it is not so unusual to have api calls with query parameters. Would be nice if this feature could do it a bit faster 🥇

**Comment by gkalpak** [comment]
This is already possible (as long as you order the data-groups correctly - i.e. more specific ones first). I have submitted #38364 to make clearer in the docs.

In your case, the config should look something like:

```json
{
  ...
  "dataGroups": [
    {
      "name": "documents-fetch",
      "urls": [
        "/documents?knowledge="
      ],
      "cacheConfig": {
        ...
        "strategy": "freshness"
      }
    },
    {
      "name": "documents-fetch",
      "urls": [
        "/documents"
      ],
      "cacheConfig": {
        ...
        "strategy": "performance"
      }
    }
  ]
}
```
