### ISSUE TITLE
Delete confirm bouton doesn't work in IE and edge

### ISSUE THREAD

**Issue by AmenallahMeftehh** [angular/angular#21180]
When i select one or more files and i click on the remove button a modal bootstrap will pop up to confirm the deletion.
When i click ok in chrome and firefox everything works perfectly but in IE and edge nothing happens and the modal closes.
after when I click again on the delete button and then confirm the modal closes and the screen remains in loading.

package.json
![image](https://user-images.githubusercontent.com/18208672/34378947-cae7c59c-eaf8-11e7-8179-0376a7a0a543.png)

polyfills.ts
![image](https://user-images.githubusercontent.com/18208672/34378986-fd26664e-eaf8-11e7-9f87-9641e5576c93.png)

Frist chance:
before click yes
![image](https://user-images.githubusercontent.com/18208672/34379276-bd0a0f28-eafa-11e7-855a-f55612d16324.png)

after click yes
![image](https://user-images.githubusercontent.com/18208672/34379397-66fcf630-eafb-11e7-8b5f-22eaedfcfd7b.png)

Second chance:
after clicking delete and then confirm
![image](https://user-images.githubusercontent.com/18208672/34379300-dee3d9ee-eafa-11e7-97d9-123107ebd86e.png)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
