### ISSUE TITLE
Usage of Typescript Enum in route's data property

### ISSUE THREAD

**Issue by impankratov** [angular/angular#21195]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If you have a lazy loaded module and want to add `data` property to the route, i.e.:

```
  {
    path: 'test',
    loadChildren: './test/test.module#TestModule',
    data: {
      [TestEnum.testValue]: 'random' // <-- Using Enum as a key to increase typesafety here
    }
  }
```

Here's the string Enum (tried with `const enum`, doesn't make any difference):
```
enum TestEnum {
  testValue = 'hey'
}
```

`npm start` Results in following output:

```
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2017-12-28T09:07:56.124Z
Hash: c4f259d9e9195c2e92f7
Time: 14055ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 21.6 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 560 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 34 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 8.17 MB [initial] [rendered]
```
Trying to navigate the `/test` (that's the path for the lazy loaded module) in the app results in the following `console.err` output:
```
core.js:1427 ERROR Error: Uncaught (in promise): Error: Cannot find module './test/test.module'.
Error: Cannot find module './test/test.module'.
    at eval (eval at ../../../../../src/$$_lazy_route_resource lazy recursive (main.bundle.js:6), <anonymous>:5:9)
    at ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:4753)
    at ZoneDelegate.invoke (zone.js:387)
    at Zone.run (zone.js:138)
    at eval (zone.js:870)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4744)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at eval (eval at ../../../../../src/$$_lazy_route_resource lazy recursive (main.bundle.js:6), <anonymous>:5:9)
    at ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:4753)
    at ZoneDelegate.invoke (zone.js:387)
    at Zone.run (zone.js:138)
    at eval (zone.js:870)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4744)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at resolvePromise (zone.js:821)
    at resolvePromise (zone.js:785)
    at eval (zone.js:870)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4744)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:594)
    at ZoneTask.invokeTask [as invoke] (zone.js:499)
    at invokeTask (zone.js:1536)
```

And after any changes to the code we can see that lazy module actually appears in the output:
```
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry]
chunk {main} main.bundle.js (main) 21.8 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 560 kB [initial]
chunk {styles} styles.bundle.js (styles) 34 kB [initial]
chunk {test.module} test.module.chunk.js () 9.02 kB  [rendered]
chunk {vendor} vendor.bundle.js (vendor) 8.18 MB [initial] [rendered]
```

And everything starts work as expected.

## Expected behavior

Expected to not lose lazy loaded modules if Enum is used as key of route's `data` property.

## Minimal reproduction of the problem with instructions

Here's the repo with simple ng-cli setup. Just run `npm start`
https://github.com/impankratov/router-enums-data

## What is the motivation / use case for changing the behavior?

Just wanted to use Enum as key of route's `data` property to increase typesafety.

## Environment

<pre><code>
Angular version: 5.1

Browser:
- [x] Chrome (desktop) version 63
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v9.3.0 
- Platform:  Windows 10

Others:

</code></pre>

**Comment by impankratov** [comment]
Realized that it's probably wrong repo to post this issue to. Should I close this and open it in the angular-cli repo?

**Comment by jasonaden** [comment]
@impankratov This sounds like either a CLI issue or a compiler issue. I'll ask the compiler guys to take a look, and if it's a CLI issue they will likely close this and you can open it against the CLI project.

**Comment by impankratov** [comment]
@jasonaden thanks!

**Comment by JoostK** [comment]
Confirmed as completely broken in the View Engine compiler, although the error has changed a bit. It now fails with a compilation error `ERROR in Cannot read property 'loadChildren' of undefined`. Testing in Ivy however shows that this bug has been fixed!

**Comment by JoostK** [comment]
The Ivy compiler no longer has a metadata collector that was prone to unsupported syntax issues, so closing as resolved.
