### ISSUE TITLE
Problem with universal rendering of SVGs with XMLNS attribute

### ISSUE THREAD

**Issue by hitpopdimestop** [angular/angular#21196]
There's an issue that is described here:
https://github.com/angular/material2/issues/8241

But since it's not an angular/material issue it doesn't seem to be addressed. Just adding it here for the record and confirmation that it still exists on angular 5.1.0. Removing xmlns tag helps, but sometimes you really need it.

**Comment by Walking111** [comment]
Also have this problem.

**Comment by chuckjaz** [comment]
This appears to be an issue with domino and not Angular as the exception is coming domino not Angular.

Is there something I am missing?

**Comment by hitpopdimestop** [comment]
Sorry for late response @chuckjaz, we have endless winter holidays :) I'll try to dig deeper into this, thanks for paying attention to the problem.

**Comment by hitpopdimestop** [comment]
@chuckjaz you were right, the problem is with domino and it's been already fixed in this [commit](https://github.com/fgnass/domino/commit/b16cb1923f83db096b7cd0638734474e54b3308d). The problem will be solved with the next version of domino, just have to be sure angular/platform-server will update the dependency
