### ISSUE TITLE
Reactive forms. Add custom data to form control.

### ISSUE THREAD

**Issue by ctrl-brk** [angular/angular#21194]
## I'm submitting a...
<pre><code>[x] Feature request</code></pre>

## Current behavior
When creating a form group and adding form controls the only options available are form control name, value and validators.

## Expected behavior
Would be nice to be able to pass some custom data through form control so you can retrieve it using form.control.get....

## What is the motivation / use case for changing the behavior?
In my particular case I'm looking for a way to pass more detailed control description and get it when building validation messages. Ideally it would be nice to have access to concrete control instance from the form instance.

**Comment by jotatoledo** [comment]
Could you be more specific about your use case?

**Comment by ctrl-brk** [comment]
I'm trying to show consolidated validation message including results from all the controls in the form. Something like:
First Name: required
Date of birth: invalid date format
etc...
but all in one place, possibly as a submit button title. So I need to build a single piece of text somehow.
I can go over form's validation errors and collect form control names but they look like firstName, dateOfBirh etc... and I'd like to pass more human friendly descriptions as shown above.
I use my own custom controls which could have this information but I have no idea how to access concrete control instance from the form, it only gives me its own "control" collection.

**Comment by kara** [comment]
This looks like it's covered by https://github.com/angular/angular/issues/20477.
