### ISSUE TITLE
feat(service-worker): Support ignoring specific URLs (e.g. for AJAX progress listener, video streaming, range requests, Firebase uploads)

### ISSUE THREAD

**Issue by MrCroft** [angular/angular#21191]
## I'm submitting a...

```
[x] Feature request
```

## Current behavior
ServiceWorker breaks AJAX uploads progress reporting.

## Expected behavior
AJAX upload progress listener should work.

## What is the motivation / use case for changing the behavior?
Progress is needed when handling uploads.
There is an open issue [here](https://github.com/w3c/ServiceWorker/issues/1141) and it is on this w3c [roadmap](https://github.com/w3c/ServiceWorker/issues/1206)
Until then, as far as I could read, it would be possible to make this work by checking the `event.request.url` at the very top of the SW script and simply `return` if it matches certain urls that would be specified in `ngsw-config.json`

## Environment

```
Angular version: 5.1.2
```

**Comment by doronsever** [comment]
We have the same problem either.
For now, we added an ugly spinner instead of a progress bar but our clients aren't happy with it. 

It would be best if this topic can be priorities somehow

**Comment by MrCroft** [comment]
@doronsever 
In case this is critical for you, I've just tested with editing the resulted `ngsw-worker.js` file and it works:
I've installed `gulp` and `gulp-replace` 😬 and created a gulp task that replaces `onFetch(event) {` with:
```
onFetch(event) {
    if (event.request.url.indexOf('/upload') !== -1) { return; }
```
in the `dist/ngsw-worker.js` file and then my build script became `ng build [whatever options I have] && gulp swAjaxUploadFix` (or I could have used the default task and simply run `gulp`, but I like to name my tasks).
Of course, in my case we have the convention that all upload urls contain `/upload`.
And also I log a big, multiple line message in the console on build so I don't forget about removing this workaround as soon as this feature gets implemented by the Angular team.
But, meanwhile, reporting the progress on uploads works! 😁 
So, I just wanted to let you know it works. Because when I posted the issue, I had only read that this would fix progress reporting, and took what I read for granted, haven't tested myself. Now I have!

**Comment by doronsever** [comment]
@MrCroft Thank you very much!
At least it's working now :)

**Comment by ganeshkbhat** [comment]
Can this actually be put as a feature request from my end also? I think something having a key like `"exclude"` with interface like `interface Exclude { name: string; urls: string[]; version?: number; }`. There is one more open question like this in 'so. https://stackoverflow.com/questions/47693093/angular-5-and-service-worker-how-to-exclude-a-particular-path-from-ngsw-config

**Comment by gkalpak** [comment]
The only problem I see is that the check should happen asynchronously. Based on https://github.com/angular/angular/pull/23025#issuecomment-376662562 it shouldn't be possible to decide whether to handle the request or not asycnhronously. But I am wondering if calling `event.waitUntil()` allows us to defer the decision of whether to call `event.respondWith()` or not and still be able to choose not to handle the request.

I.e. something like:

```js
onFetch(evt) {
  evt.waitUntil(asynchronouslyDecideWhetherToHandle(evt).
    then(handleIt => handleIt && evt.respondWith(...));
}
```

**Comment by ganeshkbhat** [comment]
I see the point. If thats the case it definitely seems like its a tradeoff on performance and feature. May be someone is is more aware than me can point the way forward.

**Comment by GXGOW** [comment]
I'm having the same issue when watching server sent events through an EventStream. Bypassing the 'notifications' request with [aforementioned workaround](https://github.com/angular/angular/issues/21191#issuecomment-360051276) fixed it for now though.

**Comment by Delagen** [comment]
This issue is blocking rendering PDF in Chrome from 71 version

**Comment by aSegatto** [comment]
We are also having problems with PDF documents

**Comment by webmaxru** [comment]
Did you try specifying `navigationUrls`explicitly?
https://angular.io/guide/service-worker-config#navigationurls

**Comment by avilao** [comment]
Any roadmap on this issue?

**Comment by Iyashu5040** [comment]
Plus one for this. We're hitting issues with the service worker adding "Cache-Control" headers to external API calls which don't allow that header. As we're not in control of the API we can't modify the accept headers on it. Therefore we need some way to have the browser do these API calls normally.

**Comment by jraadt** [comment]
In `ngsw-config.json` there should be an `exclude` block to specify urls that you want to exclude from the service worker. Like @MrCroft 's solution, it would simply add another `if` condition to `onFetch(event)` function that would return if it matched a url in the new `exclude` block. Does this seem reasonable?

**Comment by gkalpak** [comment]
This has been discussed above (https://github.com/angular/angular/issues/21191#issuecomment-386799933), but it is not possible because of the reason explained in https://github.com/angular/angular/pull/23025#issuecomment-376662562.
Basically, the decision whether to handle the request or not should be made synchronously, but looking at the `exclude` property in `ngsw.json` would be an asynchronous operation.

**Comment by petersalomonsen** [comment]
I've managed to bypass the serviceworker for file attachment uploads in the Runbox 7 email app by checking request url before `event.respondWith` and just return from the onFetch handler if it's an URL that should not be handled by the serviceworker:

https://github.com/runbox/runbox7/blob/master/ngsw-worker-patched.js#L1940

Is there any reason that this is not supposed to work? (it works for me). Of course I would rather see a solution without having to patch the `ngsw-worker.js`, but this was just to test the concept of bypassing the serviceworker.

**Comment by gkalpak** [comment]
@petersalomonsen. no there's no reason why this shouldn't generally work (but it is possible that this breaks :grin:)

It is true that one way for the SW to be able to decide synchronously whether to handle a request or not is embedding the necessary info into the SW script itself (i.e. at build time). Unfortunately, this violates one of the core assumptions of our current SW implementation: The SW script is independent of the app version (i.e. all assets that make app a version of the app), which is entirely contained in the `ngsw.json` config. The SW relies on that assumption, so breaking it is not a straight forward change (and might require entirely changing the whole SW design).

##
In this particular case, what it means for you is that you may end up with a tab that runs an older version of your app, but being served by a newer version of the SW script. In that situation, it is possible that your app expects one set of URLs to bypass the SW and your SW script is configured to ignore a different set of URLs.

It is up to you to decide how much of an issue this is for your app, how often these URLs need to change and what would be the impact on your users if the app and the SW got out-of-sync (as described above).

**Comment by gkalpak** [comment]
@petersalomonsen. no there's no reason why this shouldn't generally work (but it is possible that this breaks :grin:)

It is true that one way for the SW to be able to decide synchronously whether to handle a request or not is embedding the necessary info into the SW script itself (i.e. at build time). Unfortunately, this violates one of the core assumptions of our current SW implementation: The SW script is independent of the app version (i.e. all assets that make app a version of the app), which is entirely contained in the `ngsw.json` config. The SW relies on that assumption, so breaking it is not a straight forward change (and might require entirely changing the whole SW design).

##
In this particular case, what it means for you is that you may end up with a tab that runs an older version of your app, but being served by a newer version of the SW script. In that situation, it is possible that your app expects one set of URLs to bypass the SW and your SW script is configured to ignore a different set of URLs.

It is up to you to decide how much of an issue this is for your app, how often these URLs need to change and what would be the impact on your users if the app and the SW got out-of-sync (as described above).

**Comment by gkalpak** [comment]
@petersalomonsen. no there's no reason why this shouldn't generally work (but it is possible that this breaks :grin:)

It is true that one way for the SW to be able to decide synchronously whether to handle a request or not is embedding the necessary info into the SW script itself (i.e. at build time). Unfortunately, this violates one of the core assumptions of our current SW implementation: The SW script is independent of the app version (i.e. all assets that make app a version of the app), which is entirely contained in the `ngsw.json` config. The SW relies on that assumption, so breaking it is not a straight forward change (and might require entirely changing the whole SW design).

##
In this particular case, what it means for you is that you may end up with a tab that runs an older version of your app, but being served by a newer version of the SW script. In that situation, it is possible that your app expects one set of URLs to bypass the SW and your SW script is configured to ignore a different set of URLs.

It is up to you to decide how much of an issue this is for your app, how often these URLs need to change and what would be the impact on your users if the app and the SW got out-of-sync (as described above).

**Comment by gkalpak** [comment]
@petersalomonsen. no there's no reason why this shouldn't generally work (but it is possible that this breaks :grin:)

It is true that one way for the SW to be able to decide synchronously whether to handle a request or not is embedding the necessary info into the SW script itself (i.e. at build time). Unfortunately, this violates one of the core assumptions of our current SW implementation: The SW script is independent of the app version (i.e. all assets that make app a version of the app), which is entirely contained in the `ngsw.json` config. The SW relies on that assumption, so breaking it is not a straight forward change (and might require entirely changing the whole SW design).

##
In this particular case, what it means for you is that you may end up with a tab that runs an older version of your app, but being served by a newer version of the SW script. In that situation, it is possible that your app expects one set of URLs to bypass the SW and your SW script is configured to ignore a different set of URLs.

It is up to you to decide how much of an issue this is for your app, how often these URLs need to change and what would be the impact on your users if the app and the SW got out-of-sync (as described above).

**Comment by petersalomonsen** [comment]
@gkalpak A suggestion for keeping the SW independent of the app version:

On my own I just tested fetching a SW-bypass (exclude) configuration from `ngsw.json`, and store it in a global variable in `ngsw-worker.js`. Once the configuration is loaded, that variable can be accessed synchronously by the `onFetch` handler. For the app (client) to be sure that the bypass/exclude configuration is loaded it should wait for a message from the serviceworker that it has loaded the configuration.

Would that be an acceptable way of implementing a fix for this?

**Comment by gkalpak** [comment]
> For the app (client) to be sure that the bypass/exclude configuration is loaded it should wait for a message from the serviceworker that it has loaded the configuration.

This is the tricky/undesirable part. For example, how lon will the app wait? What if there is no SW controlling the page?
It also means that making a request would be complicated and require special handling (which is tedious and error-prone).

You could probably still implement this yourself (by defining your own SW script, which importa `ngsw-worker.js`), but it will be far from straight forward.

##
Another option might be to use a special query param or hash fragment to signal to the SW that a request should be ignored.
Then you would have to change those URLs to include the special string. E.g. change `https://some.url/foo/bar?baz=qux` to `https://some.url/foo/bar?baz=qux&ngsw-ignore` or `https://some.url/foo/bar?baz=qux#ngsw-ignore`.

This way, the app is responsible for controlling which URLs should bypass the SW. (Still not ideal, but might be a good compromize.)

Although, I am sure there will be cases (even if only few), where this approach will be insufficient (e.g. unable to control a URL).

WDYT?

**Comment by petersalomonsen** [comment]
@gkalpak I think you're onto something here. If we evolve your idea to setting a request header instead of using query param / hash fragment it might be even "cleaner"? In most cases you should be able to set a request header either directly, or using an interceptor.

I just had to test it, so I modified the `onFetch` method in `ngsw-worker.js` to check for the presence of 'testheader`:

```
onFetch(event) {
            const req = event.request;
            console.log(req.headers.has('testheader'));
```

and when running this from the client:

`xhr = new XMLHttpRequest();xhr.open('GET','/test');xhr.setRequestHeader('testheader','test');xhr.send();`

The serviceworker console outputs `true`.

So this seems to work - and then we could just add some reserved header name to bypass the serviceworker. For example: `ngsw-bypass`, and then the serviceworker onFetch should just check for the presence of this header, and in that case just return.

Are we onto something?

**Comment by MrCroft** [comment]
@gkalpak I'm a bit confused :) maybe I don't know how the build process works, when it comes to generating the ngsw-worker.js file... I'm just assuming that the CLI generates that file. I'm not sure why it would have to be some tricky async thing? Or URL param... Why wouldn't it simply be like this: the CLI reads the ngsw-config.json (which it already does, doesn't it? Read the sw config json, in order to generate the sw js file, with all the necessary conditions like to know what to cache - assetGrouos, dataGroups and whatever other configurations there are), and from the sw config json it could also read some "bypassUrls: [ ]" key and simply generate the appropriate code in the ngsw-worker.js file, with a condition and a `return` statement in "onFetch()", if req.url matches any of the URLs in bypassUrls (can be regex or not).
At least that's the solution I thought/hoped it would be applied since the very beginning of this issue.

**Comment by petersalomonsen** [comment]
@MrCroft I think that is what @gkalpak said above that generating the `ngsw-worker.js` would violate the core assumption of the current serviceworker implementation: That the serviceworker script should be independent of the app version.

If you look at what the CLI does it just copy the file from `node_modules/@angular/service-worker/ngsw-worker.js`. So the serviceworker script will mostly be the same for any new version of the app.  You could get into trouble if an old version of the app is running with a newer version of serviceworker configuration, which often is the case since you'll have to reload to get the updated app version (after it's installed). It wouldn't be a good thing if the new serviceworker script also had to contain configuration of how to handle both the old (or even older) and new version of an app.

So that's why bypassing the serviceworker by setting a header in the request could be a good idea. If everyone agrees...

**Comment by MrCroft** [comment]
@petersalomonsen ohhh, ok... I feel so silly now :) so the contents of ngsw-config.json doesn't affect the contents of ngsw-worker.js file. And the sw config is actually read at runtime I guess.
Thank you for clearing that out! Everything makes sense now.
I guess using a header would be the safest/most usable option then. And there shouldn't be any 3rd party NG lib/package out there that wouldn't use Angular's built in HttpClient I guess, or allow us to set headers otherwise (ie ngx-uploader)

**Comment by petersalomonsen** [comment]
So I'd suggest adding a few more lines here https://github.com/angular/angular/blob/master/packages/service-worker/worker/src/driver.ts#L179

```
 private onFetch(event: FetchEvent): void {
    const req = event.request;
    if(req.headers.has('ngsw-bypass')) {
                return;
    }
    .....
```

**Comment by jraadt** [comment]
@petersalomonsen I like your idea of using a request header. That works in most cases, but I also have cases where I need to request a video in the HTML5 video player and I don't believe I can set headers since I'm just passing it a URL. In that case I'd like to use a special query parameter like @gkalpak suggested. Could it use request headers OR query parameter?

**Comment by petersalomonsen** [comment]
Very good point @jraadt 

Added checking the url for the presence of `ngsw-bypass=true`:

```
private onFetch(event: FetchEvent): void {
    const req = event.request;
    if(req.headers.has('ngsw-bypass') || req.url.indexOf('ngsw-bypass=true') > -1) {
          return;
    }

```

Tested locally and seems to work. Looks ok?

**Comment by jraadt** [comment]
@petersalomonsen - That looks really good and it works in my tests.

I don't know if this matters, but I had an `event.waitUntil()` in my `if` statement. I just copied it from another section in the `onFetch()` that seemed to be bypassing the SW. Someone who knows more about how the SW works should weigh in, but this is what I have:

```
private onFetch(event: FetchEvent): void {
    const req = event.request;
    if(req.headers.has('ngsw-bypass') || req.url.indexOf('ngsw-bypass=true') > -1) {
          event.waitUntil(this.idle.trigger());
          return;
    }

```

**Comment by petersalomonsen** [comment]
Yes @jraadt - that seems to be needed so that update checks can occur. @gkalpak should probably confirm.

**Comment by gkalpak** [comment]
Great discussion. I think we are definitely on to something :wink:
Supporting both a header and a query param SGTM (after having thought about it for 10 secs :grin:)

Calling `idle.trigger()` shouldn't be necessary in this case (similar to what we do in other cases where we ignore specific requests).
(Not that it would hurt, but I'd leave it out for consistentcy - and because it is unnecessary :grin:)

**Comment by Iyashu5040** [comment]
How would the header and query param solutions that have been proposed fix issues related to API calls made through SDKs where the developer is neither in control of the API or the SDK?

Case in point: The OneSignal Web Push SDK makes calls to the OneSignal API. The ngsw adds a Cache-Control header to the request, which the OneSignal API explicitly disallows. The developer cannot add special headers or query params to the request since it's being done through an SDK.

**Comment by gkalpak** [comment]
@lyashu5040, it won't be able to address those cases (but it will address cases all other cases).
It is not an ideal solution, but it is the best we've come up with so far :grin:

**Comment by gkalpak** [comment]
BTW, for anyone desperate for a work-around, I've seen people successfully wrapping `ngsw-worker.js` in their own script that catches `fetch` events early and stops their propagation to `ngsw-worker.js`. Off the top of my head, something like:

```js
// Catch `fetch` events and prevent specific ones from propagating to the "real" SW".
self.addEventListener('fetch', evt => {
  const req = evt.request;

  if (/* `req` matches some criteria */) {
    evt.stopImmediatePropagation();
  }
});

// Import the "real" SW to do the heavy-lifting.
self.importScripts('./ngsw-worker.js');
```

<sub>If you do that, you might want to set [updateViaCache: 'all'][1], when registering the SW.</sub>

I am not sure this will work (and it is definitely not an officially recommended approach 😇), but might be good enough as a work-around.

[1]: https://developers.google.com/web/updates/2018/06/fresher-sw

**Comment by petersalomonsen** [comment]
Started work on a pull request: https://github.com/angular/angular/pull/30010 @gkalpak

**Comment by frankadrian** [comment]
I found a fairly simple workaround if you want your SW to completely "ignore" a specific path (for example we had a few paths that get redirected to another domain, which we did not want to be handled by our SW) :
By adding paths, you want to ignore, with a cacheConfig.strategy of "freshness" as a dataGroup the service worker will automatically load the content from the server (given that the timeout is not reached.)

eg `ngsw-config.json`: 
    ...
    "dataGroups": [
    {
      "name": "cloudfront behaviours",
      "urls": [
        // for these paths the Service Worker is ignored
        "/terms",
        "/blog-posts"
      ],
      "cacheConfig": {
        "maxSize": 0,
        "maxAge": "0u",
        "strategy": "freshness"
      }
    },
    ...

**Comment by gkalpak** [comment]
@frankadrian, this is something different. In this case, the SW will still handle the request, but it will just choose to forward it to the server and forward the response back to the app. This is already possible without specifying a data-group (i.e. is the difault behavior).

This thread is about having the SW _not handle_ the request (and let the browser handle it instead). There is a subtle difference, but it can be important in certain cases (for reasons explained above).

**Comment by aSegatto** [comment]
Please don't close this. As was stressed before the current implementation doesn't fix all usecases,  eg. when using firebase SDK.

**Comment by petersalomonsen** [comment]
@aSegatto Have you tried using an HttpInterceptor: https://angular.io/api/common/http/HttpInterceptor

It could maybe capture the requests made by the firebase SDK?

**Comment by gkalpak** [comment]
@petersalomonsen, I don't think the Firebase SDK goes through the `HttpClient` (for all requests), but I might be wrong.

@aSegatto, fair enough. I suggest we open a new issue specifically for situations where using an HTTP header or query param is not possible (since that is slightly different than the original issue). Can you do that (and reference this issue for context)? (Also, I think it is worth mentioning this work-around for visibility: https://github.com/angular/angular/issues/21191#issuecomment-484586484)

**Comment by petersalomonsen** [comment]
@aSegatto @gkalpak I've had a quick look at AngularFire and seems like it's not using the HttpClient. But even when this is the case we can still intercept `XMLHttpRequest` for example like this:

```
const originalOpen = XMLHttpRequest.prototype.open;
XMLHttpRequest.prototype.open = function( method, url) { 
	originalOpen.apply(this,[method, url]);
	this.setRequestHeader('ngsw-bybass','true');
};
```

Then any library using `XMLHttpRequest` in your client will set the `ngsw-bypass` header. You can extend this to check for specific URLs / methods.

We could of course add another feature to the serviceworker by using the message port to send lists of URLs to be bypassed (and the serviceworker could store this in a map), but I think I would try out the client side interception strategy first.

**Comment by aSegatto** [comment]
@petersalomonsen Thanks for your suggestions. I don't know if modifying XMLHttpRequest would work , because i don't know how the requests are made from the firebase sdk (maybe they also use fetch API ? ), but this could be an approach... 
Message port IMHO is more clean as it doesn't couple to the sdk implementation.

@gkalpak Thanks, I open another issue

**Comment by briznad** [comment]
To expand upon @MrCroft 's workaround, in case anyone isn't using gulp/grunt or other build tool, you can modify the `ngsw-worker.js` file using `sed` and easily integrate the workaround into your `package.json` scripts. Here's the code I'm using:

in `package.json`
```
"scripts": {
    …
    "editngsw": "sed -i '' \"s/onFetch(event) {/onFetch(event) { if (event.request.url.indexOf('firebasestorage.googleapis.com') !== -1) { return; }/g\" www/ngsw-worker.js",
    "build": "ng build --prod=true && npm run editngsw"
  },
```
or for Ionic
```
"scripts": {
    …
    "editngsw": "sed -i '' \"s/onFetch(event) {/onFetch(event) { if (event.request.url.indexOf('firebasestorage.googleapis.com') !== -1) { return; }/g\" www/ngsw-worker.js",
    "build": "ionic build --prod && npm run editngsw"
  },
```
Please note: the above code assumes you're using `www` as your build output directory (vs `dist`, etc).

**Comment by BluebambooSRL** [comment]
@briznad  @MrCroft  many thanks for the solution! It also works for me :)
There is any way to write the code at the @angular/pwa library in order to avoid tho search for this bug? @gkalpak @AngularFirebase @fireship-ioThanks in advance!! Federico

**Comment by gkalpak** [comment]
@BluebambooSRL: Sorry, I disn't understand your question 😕 Can you clarify?
