### ISSUE TITLE
router fragment not trigger :target css selector

### ISSUE THREAD

**Issue by vthinkxie** [angular/angular#21193]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

routerLink with fragment option would not trigger `:target` css selector

## Expected behavior

should trigger `:target` css selector

## What is the motivation / use case for changing the behavior?

https://plnkr.co/edit/t9qwAHp4SNqC3Uw3lExz?p=preview

I just add some code to the demo of angular.io

1. add id="test" to `h3` in `app/crisis-center/crisis-detail.component.ts` and add some style `h3:target{color:blue}` to it.
2. add fragment="test" to `app/crisis-center/crisis-list.component.ts`
3. click `Crisis Center` then click `Dragon Burning Cities`
4. :target selector does not apply to element.

## Environment

<pre><code>
Angular version: latest

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
Out of scope: https://bugs.webkit.org/show_bug.cgi?id=83490

**Comment by jasonaden** [comment]
Closing as it's out of scope.
