### ISSUE TITLE
angular 5 service worker not work in some lazy load modules

### ISSUE THREAD

**Issue by icepoint0** [angular/angular#21198]
the example websitepage :[https://kl.atyun.net](https://kl.atyun.net)

if  u first load the websites it will redirect to module A ,and the route is '/sites', but the service worker not work in this route. and then u visit the page "/login" ,service worker works now ,why ?
"/login" and "/sites" not in same chunk.

and here is my code:

app.module:
<pre>
  imports: [
    ServiceWorkerModule.register('./ngsw-worker.js', {enabled: environment.production}),
    routing,
    HttpModule,
    BrowserAnimationsModule,
    CommonModule,
    FormsModule,

  ],
</pre>

routing config:
<pre>
  {path: 'sites', loadChildren: '../modules/site-render/site-render.module#SiteRenderModule'},
  {path: 'login', loadChildren: '../modules/login/login.module#LoginModule'},
</pre>

**Comment by alxhub** [comment]
Hello @icepoint0, 

I can see your site does produce this issue, but without source code it will be difficult to debug.

Can you upload a minimal CLI project which demonstrates this issue?

**Comment by icepoint0** [comment]
@alxhub I will take some time to upload a minimal project, plz don't close this issue; thank u.

**Comment by gkalpak** [comment]
Closing for now. Feel free to open a new issue once you have a repro (using the latest version of Angular :wink:).
