### ISSUE TITLE
route cant show URLSearchParams  in url when use "usehash: true"

### ISSUE THREAD

**Issue by mike8625** [angular/angular#21206]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>
I 

## Current behavior

`
//app.modules.ts
imports: [
  ...
  RouterModule.forRoot(appRoutes, { useHash: true })
  ...
]
`
input  "localhost:4200/?name=123/#/somePage" on locationbar
result:
locationbar:   localhost:4200/#/somePage,  string "?name=123/" is disappear.

## Expected behavior

input  "localhost:4200/?name=123/#/somePage" on locationbar
locationbar: "localhost:4200/?name=123/#/somePage" 
I expect locationbar's content is as same as I input

## Minimal reproduction of the problem with instructions
cant pass the URLSearchParams in url when use "usehash: true"

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

<hr>

You should put the URL variables after the hash in this case. Either the hash is part of the URL variable or the other way around. But if you're using a hash, URL vars should come after it.

**Comment by mike8625** [comment]
ok, tks
