### ISSUE TITLE
Interface-based lifecycle methods

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#2120]
We currently declare lifecycle callback methods in annotations:

```dart
@Component(
  lifecycle: const [onChange]
)
class MyComponent {
  void onChnage() { ... }
}
```

This is not idiomatic in Dart and error-prone in both Dart and TypeScript. Note that in the example above I misspelled the method. Also note that the signature of the method is wrong. There's no warning from the analyzer about these mistakes.

## Proposal

This is more idiomatic Dart:

```dart
@Component()
class MyComponent implements OnChange {
  @override
  void onChange(_) { ... }
}
```

With this you get much better feedback from tools.

Because `@Component` is shared between Dart and JS we will extract "lifecycle" property into its own annotation `@Lifecycle` for use with JS:

```typescript
@Component({...})
@Lifecycle({[onChange]})
class MyComponent {
  onChange():void { ... }
}
```

The reason we need to keep `@Lifecycle` is because TypeScript does not reify interfaces, so there is no way to reflectively tell if a class implements an interface.

Components intended to transpile to both languages (such as our own material components) would simply use both:

```typescript
@Component({...})
@Lifecycle({[onChange]})
class MyComponent implements OnChange {
  onChange(_):void { ... }
}
```

Dart would ignore `@Lifecycle` and JS would ignore `implements OnChange`.

Related issue: #1943

**Comment by yjbanov** [comment]
Assigning to @vsavkin to validate the idea. We can reassign to anyone willing to implement once we agree on it.

**Comment by vicb** [comment]
Is `OnChange` a good name ? (not very descriptive, easy to mix with `onChange`).

I am not really keen on 
```ts
@Component({...})
@Lifecycle({[onChange]})
class MyComponent implements OnChange {
  onChange(_):void { ... }
}
```

as an alternative, we could rename `onChange` to something more specific and use a structural type check for JS:
```ts
@Component({...})
class MyComponent implements OnChange {
  onBindingsChanged(_):void { ... }
}
```

the `implements OnChange` would be optional in JS but documented as a best-practice.

Also I think we do not inherit annotations for now ? If this is true, the interface based behavior would be different as of today.

**Comment by mdausmann** [comment]
what about 

    @Component()
    class MyComponent implements Changeable, Destroyable {
      @override
      void onChange(_) { ... }
    
    @override
      void onDestroy(_) { ... }
    }

**Comment by vicb** [comment]
`MyComponent` could change even if it does not implements `Changeable`.

**Comment by tbosch** [comment]
+1 for using structural type checks in JS land as well (e.g. via checking the prototype), so we keep the same syntax in both, Dart and JS (i.e. don't need `@Lifecycle` annotation at all)

**Comment by kegluneq** [comment]
I like this generally, but for the transformer this introduces some nasty edge cases.

To avoid the slowdown seen with the AngularDart (#1) transformer, we do not have a fully resolved AST or global information at transform time. With some exceptions, when operating on a file we only have the information available in that file. As an example, if we have:

a.dart:
```
class A implements OnChange {}
```

b.dart
```
class B extends A {}
```

We won't know that `B` implements `OnChange`.

@vsavkin and I talked about this and settled on requiring `OnChange` to be explicitly specified even if it is already inherited.

Any objections?

**Comment by vicb** [comment]
@kegluneq would you mind cross posting on #2220, this issue is closed.

I understand the why but I don't really like the solution. If you extend some Directives, you'll have to check its signature before doing so, far from ideal - not to mention issues when the base class signature changes.
