### ISSUE TITLE
[Feature request][Language Service] Warn user when Input/output does not exist in component and type checking

### ISSUE THREAD

**Issue by Tukks** [angular/angular#21204]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
given this component :
 ```
@Component({
  selector: 'example-component',
  templateUrl: 'example-component.component.html',
  styleUrls: ['example-component.component.scss']
})
export class ExampleComponent {
  @Input() label: string;
 @Output() event: string;
}
```
If I wrote this in another template like this :

```
<example-component [label]="1" [noExistingInput]="'label'" (event)="exampleMethod()">
<example-component>
```
I have no warning on the noExistingInput, and no warning on label input waiting for a string and receiving a number.

## Expected behavior
showing error saying no existing input/output and type mismatch in html template

## What is the motivation / use case for changing the behavior?
better linter integration, less AOT build error

**Comment by trotyl** [comment]
There's no type-checking for events, which is tracked by #17483.

Language service support would require compiler support comes first.

**Comment by Tukks** [comment]
Ok I understand, thank's for your response.
and for noExistingInput? and Input() typecheck? these are not event.

**Comment by CDDelta** [comment]
@Tukks I think you have the syntax wrong. `@Input` binding is done with [()] for two way or [] for one way binding. `@Output` binding is done with (). The language service already reports noExistingInput errors. As for type checking, that is not being done. You should have a look at #21143 and [@angular/cdk/coercion](https://github.com/angular/material2/tree/master/src/cdk/coercion).

**Comment by Tukks** [comment]
@CDDelta I edited my issue. Language service doesn't report the noExistingInput in vscode and in webstorm.
I can't do a plunker with this.

**Comment by CDDelta** [comment]
@Tukks the language service does report noExistingInput for me though and I am using vscode. It, however, does not report noExistingOutput when I tried it.

**Comment by Tukks** [comment]
@CDDelta I created a project with Angular Cli, and yes the service does report noExistingInput in Vscode, mabe the other project is to big to be handled by Language service.
I will drive more test to see what happen.
I close this issue until I have more info.
