### ISSUE TITLE
Improved Apache configuration steps

### ISSUE THREAD

**Issue by bibhas2** [angular/angular#21201]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The documentation under ``https://angular.io/guide/deployment`` suggests using Apache's ``mod_rewrite`` for fallback configuration. There is a much improved approach these days using the ``FallbackResource`` directive (available in Apache version 2.4.4 and later).

## Expected behavior

Suggested documentation (taken from my own SO answer https://stackoverflow.com/a/48012732/1036017).

Let us say that your Angular app's ``index.html`` is in ``my-app/index.html`` under the document root of your web server. And you wish to access the app using ``http://localhost/my-app``.

First of all make sure that your base href is ``"/my-app/"``. Next, in your ``httpd.conf`` file add:

```
<Location "/my-app">
    FallbackResource /my-app/index.html
</Location>
```

This will cause Apache to load ``index.html`` if any resource under ``/my-app/`` can not be found.

If you are making API calls under the same path, such as say ``/my-app/api`` then you should probably not apply the ``FallbackResource`` rule for these calls. So add:

```
<Location "/my-app/api">
    FallbackResource disabled
</Location>
```

## What is the motivation / use case for changing the behavior?

The ``FallbackResource`` is much easier to configure and understand.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
docsarea=deployment

**Comment by lukengda** [comment]
Is there any reason not to use this approach?

**Comment by yglodt** [comment]
@lukengda I have had an issue after upgrading the Angular resources while using `FallbackResource`:

In fact it seems that because the url of the JavaScript bundle changes, it might happen that the browser still requests the old bundle after an upgrade. Since the "old" bundle does not exist anymore, `FallbackResource `kicks in, and serves index.html instead. And this leads to the famous "unexpected token < at ..."

I have not made any research on this topic so far, but the solution would be to have `FallbackResource ` work only for .html files.

**Comment by josephperrott** [comment]
After investigating a bit, we have decided to continue to have the documentation as is.  While there are multiple ways to perform this configuration two reasons come to the front for us to continue as is:

- While newer version of Apache will support the newly proposed configuration, it will not work in older versions of apache.  We would need to add a disclaimer about this only complicating the understanding more.
- This method of configuration better expresses what is being done, serving files that are directly requested by path, and then falling back on all "misses" to use the default file. This explicit method of expressing this can aide in users learning how SPA applications are served.
