### ISSUE TITLE
Unable to ng new

### ISSUE THREAD

**Issue by naftulikay** [angular/angular#21205]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I am following [the Angular quickstart located here](https://angular.io/guide/quickstart).

Node/NPM versions:

```
[vagrant@devel vagrant]$ npm -v
3.10.10
[vagrant@devel vagrant]$ node -v
v6.11.2
```

Install `ng` CLI:

```
[vagrant@devel vagrant]$ export PATH="$PATH:$PWD/node_modules/.bin"
[vagrant@devel vagrant]$ npm install @angular/cli
vor@1.0.0 /vagrant
└── @angular/cli@1.6.3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

Create new project:

```
[vagrant@devel vagrant]$ ng new vor
# ... output omitted for brevity
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 3.10.0-514.26.2.el7.x86_64
npm ERR! argv "/home/vagrant/.nodenv/versions/6.11.2/bin/node" "/home/vagrant/.nodenv/versions/6.11.2/bin/npm" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! path /vagrant/vor/node_modules/ts-node/dist/bin.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/vor/node_modules/ts-node/dist/bin.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/vor/node_modules/ts-node/dist/bin.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/vor/npm-debug.log
```

## Expected behavior

I would expect to be able to proceed to the next step in the documentation.

## Minimal reproduction of the problem with instructions

Steps to reproduce are laid out above. I am using CentOS 7.4, node 6.11.2, npm 3.10.10, installed via nodenv.

## What is the motivation / use case for changing the behavior?

N/A

## Environment

<pre><code>
Angular version: latest

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.2
- Platform: CentOS 7.4, kernel 3.10.0

Others:
N/A
</code></pre>

**Comment by jotatoledo** [comment]
This is cli related. Please move the issue into that repository

**Comment by naftulikay** [comment]
@jotatoledo @trotyl I have migrated to the CLI issue tracker.
