### ISSUE TITLE
change detection onpush does not work inside ngFor when collection properties changed

### ISSUE THREAD

**Issue by ilovett** [angular/angular#21203]
## Current behavior

change a child property on a collection which takes an input with change detection on push

## Expected behavior

I would expect any type of change on the input (including child properties) to trigger the onpush change detection

https://stackblitz.com/edit/angular-gitter-fkcpab

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).


----

Sorry that's not how OnPush works.
To trigger OnPush one of the 3 actions must occur
- The ref of the bound input must change
- ChangeDetectorRef#markForCheck is called on the ChangeDetectorRef for the OnPush component
- a bound event is fired from inside the OnPush component
