### ISSUE TITLE
[Doc angular.io] Get Started button style

### ISSUE THREAD

**Issue by melkir** [angular/angular#21213]
The font-weight style seems to be a little too high

https://github.com/angular/angular/blob/27ae0f94753b6e3828f46a9a23b1cb8d5884de69/aio/src/styles/1-layouts/_marketing-layout.scss#L259

![capture du 2017-12-29 15-40-59](https://user-images.githubusercontent.com/3305685/34439506-bd3cf25c-ecae-11e7-9289-300f21983bc6.png)

**Comment by trotyl** [comment]
Will be fixed by #20382
