### ISSUE TITLE
 No matching version found

### ISSUE THREAD

**Issue by abedzaben28** [angular/angular#21217]
how can i install old version like 2.4.6, i have app with angular core version 2.4.10, so am i right in trying to install: @angular/animations@2.4.6 to be compatible? if yes i'm keep getting the following error:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular/animations@2.4.6
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! A complete log of this run can be found in:
...

is there any version of animation module to working with angular core 2.4.10?

**Comment by Toxicable** [comment]
`@angular/animations` didn't exist untill v4
I'd suggest upgrading if you want to use it

**Comment by pkozlowski-opensource** [comment]
Thnx @Toxicable
