### ISSUE TITLE
Rest syntax in MyModule.forWhatever doesn't work in AOT

### ISSUE THREAD

**Issue by bgotink** [angular/angular#21214]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have the following module:

```ts
export const TOKEN = new InjectionToken<string[]>('TOKEN');

@NgModule({})
export class OtherModule {
  static forStrings(...parts: string[]): ModuleWithProviders {
    return {
      ngModule: OtherModule,
      providers: [
        {provide: TOKEN, useValue: parts},
      ],
    };
  }
}
```

and in my `AppModule` I import `OtherModule.forStrings('first', 'second', 'third')`

When I inject the `TOKEN`, in JIT I get the array `['first', 'second', 'third']` but in AOT I get the string `'first'`.

## Expected behavior

I'd expect this to work in AOT just like in JIT, or I'd expect an error detailing that spread syntax isn't supported in these kinds of methods.

## Minimal reproduction of the problem with instructions

https://github.com/bgotink/angular-repro-21214

Run the application in JIT and AOT to spot the difference. The JIT build shows an array on the page, the AOT build shows a single string.

## Environment

<pre><code>
Angular version: 5.1.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
Not a big concern, but this is the `rest` operator, not `spread` operator, they're different (opposite) operators.

**Comment by bgotink** [comment]
You're absolutely right! I've updated the PR title to prevent further confusion.

**Comment by ibarsi** [comment]
Can confirm, this is also an issue when destructuring arguments.

**Comment by JoostK** [comment]
Rest paramaters are working in Ivy.
