### ISSUE TITLE
[4.0.3] UpgradeComponent  - Trying to get the AngularJS injector before it being set

### ISSUE THREAD

**Issue by eladh** [angular/angular#21225]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When i was trying to use angularJS component in angular 4 app we done the following
1.create UpgradeComponent Directive for the AngularJS component 
2. registered by using angular NgModule and adding exports and deceleration with the new angular directive.
while running we got the error :  'Trying to get the AngularJS injector before it being set.

when i changed  angular bootstrap to 

```
export class AppModule {
    constructor(upgrade: UpgradeModule) {
      upgrade.bootstrap(document.documentElement, [Ng1Module.name]);
    }
}

platformBrowserDynamic().bootstrapModule(AppModule).then(platformRef => {
  platformRef.injector.get(Router).initialNavigation();
});
```
the issue was that that angular UpgradeComponent started before AngularJS fully started

## Environment

<pre><code>
Angular version: 4.0.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  8.9.0
- Platform:  Windows

**Comment by shimond** [comment]
try to remove the code from to constructor to onInit function

**Comment by AminRahimi** [comment]
@Directive({
  selector: 'ng-cm'
})
export class ViraDirective extends UpgradeComponent {
  constructor(elementRef: ElementRef, injector: Injector) {
    super('ngCm', elementRef, injector);
  }

  
}


export class AppModule {
  constructor(private upgrade: UpgradeModule) {


  }


  ngDoBootstrap(app) {
    app.bootstrap(AppComponent)
    this.upgrade.bootstrap(document.body, ['angular-cm']);
  }
}


//appComponent.html

//<ng-cm></ng-cm>


ERROR Error: Trying to get the AngularJS injector before it being set.

**Comment by gkalpak** [comment]
@AminRahimi, as mentioned in the docs, AngularJS needs to own the root of the hybrib part of the app. This means that you can't have an upgraded component inside a regular Angular component (i.e. not inside an AngularJS component.

Follow the docs for an example of how to bootstrap the hybrid app or see this [simple example][1] for a runnable demo.

[1]: https://stackblitz.com/edit/ngupgradestatic-playground

**Comment by bharatn** [comment]
Try in 5.2.10 version. This issue was resolved after upgrading to this ver.
