### ISSUE TITLE
Generics do not correctly infer in template pipe usage

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#21224]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

Please take a look at the minimal example below:
```typescript
@Pipe({name: 'map'})
export class MapPipe implements PipeTransform {
  transform<T, R>(value: T[], func: (value: T) => R): R[] {
    return value ? value.map(func) : [];
  }
}

// the component
interface InData {
  foo: string;
}

interface OutData {
  bar: string;
}

@Component({
  selector: 'app-test',
  template: `
    <span *ngFor="let item of items | map: _mapper">
      {{item.bar}}
    </span>
  `,
})
export class TestComponent {
  @Input() items: InData[];

  _mapper(item: InData): OutData {
    return {
      bar: item.foo,
    };
  }
}
```

Angular language service (v5.0.2) gives me an error:
```Error:(7, 9) Angular: Identifier 'bar' is not defined. 'R' does not contain such a member```

## Expected behavior

Should infer the type as TypeScript would.

From https://github.com/angular/vscode-ng-language-service/issues/196

**Comment by lukengda** [comment]
is there something we could provide to aid development or is this a problem on the typescript side?

**Comment by icenold** [comment]
one this thats driving me crazy is why does it work for angular's native pipes?
https://github.com/angular/angular/blob/master/packages/common/src/pipes/async_pipe.ts

**Comment by matsaronsen** [comment]
@icenold possibly because this line has a return type of `any`
https://github.com/angular/angular/blob/master/packages/common/src/pipes/async_pipe.ts#L92

**Comment by icenold** [comment]
@matsaronsen I already tried creating an arrayFind pipe with this same structure but it still wouldn't infer the correct type

**Comment by icenold** [comment]
![image](https://user-images.githubusercontent.com/16298042/59809170-93a3c000-92bc-11e9-8040-6842c9cc92cf.png)

**Comment by icenold** [comment]
![image](https://user-images.githubusercontent.com/16298042/59809218-ccdc3000-92bc-11e9-8839-2deb0aa4792b.png)

**Comment by hassanasad** [comment]
I am having same issue with built-in `slice` pipe.

**Comment by kucerm2** [comment]
I am having same issue with Dictionary.

For instance:
```<tr *ngFor="let item of dict[key]">```
The type of item is ```any``` even if definition of dict is ```dict: Dictionary<MyType[]>;```.

**Comment by gearsandcode** [comment]
Any ideas on this? I'm running across this with the `slice` pipe as well.

**Comment by milky2028** [comment]
I'm also getting this with a homemade sort pipe.

**Comment by BlindDespair** [comment]
Same issue here when using slice pipe. 
Running `ng lint` does not have that error, but VS code is showing it and it's pretty bothersome, there is no way to mark false positives.

**Comment by edthenet** [comment]
It is almost 2 years after this bug is first added and still with Angular 8.2.7 this issue is not fixed. I do understand that TypeScript 3 may have an issue with this, but i also think that the Angular Pipe should have a solution for this. It is not always possible or wanted to do stuff like slining outsite of the template. otherwise i could do some like `this.trips = this.trips.slice(this.start,this.end);`

**Comment by kyliau** [comment]
This has been fixed in Angular extension v9. Please open a new issue if problem persists.
The latest version can be downloaded from https://marketplace.visualstudio.com/items?itemName=Angular.ng-template

**Comment by BenShelton** [comment]
I don't believe this is fully resolved. I have a generic sort pipe which starts with the following:
```js
transform<T>(arr: T[], prop: string, reverse: boolean = false): T[] {
```
However I still get the error `Identifier 'sort' is not defined. 'T' does not contain such a member` within my templates, this is an example implementation, the `image.sort` is showing the error:

```html
<li *ngFor="let image of imageList | sortBy : 'sort'">
    <div>{{image.sort}}</div>
</li>
```

This is the versioning output from the extension:
```
[Info  - 10:55:06] Using typescript v3.6.4 from c:\Users\bensh\.vscode\extensions\angular.ng-template-0.900.4\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 10:55:06] Using @angular/language-service v9.0.0-rc.8 from c:\Users\bensh\.vscode\extensions\angular.ng-template-0.900.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js
```

**Comment by dylansteen** [comment]
> I don't believe this is fully resolved. I have a generic sort pipe which starts with the following:
> 
> ```js
> transform<T>(arr: T[], prop: string, reverse: boolean = false): T[] {
> ```
> 
> However I still get the error `Identifier 'sort' is not defined. 'T' does not contain such a member` within my templates, this is an example implementation, the `image.sort` is showing the error:
> 
> ```
> <li *ngFor="let image of imageList | sortBy : 'sort'">
>     <div>{{image.sort}}</div>
> </li>
> ```
> 
> This is the versioning output from the extension:
> 
> ```
> [Info  - 10:55:06] Using typescript v3.6.4 from c:\Users\bensh\.vscode\extensions\angular.ng-template-0.900.4\node_modules\typescript\lib\tsserverlibrary.js
> [Info  - 10:55:06] Using @angular/language-service v9.0.0-rc.8 from c:\Users\bensh\.vscode\extensions\angular.ng-template-0.900.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js
> ```

Indeed. Upgraded to Angular9 this morning, and with the improved typechecking I attempted to upgrade an `orderByPipe` to be a generic. Unfortunately I still get that same error, looks like I'm going with `any` for now.

**Comment by dylansteen** [comment]
@kyliau I've since read read the docs and this is what I'm seeing:

From
https://angular.io/guide/template-typecheck


# Full mode
- If the fullTemplateTypeCheck flag is set to true, Angular is more aggressive in its type-checking within templates. In particular:

- Embedded views (such as those within an *ngIf or *ngFor) are checked.
- **Pipes have the correct return type.**
- Local references to directives and pipes have the correct type (except for any generic parameters, which will be any).

**Comment by kyliau** [comment]
Indeed, this is not fully resolved. The language service currently does not do a good job at inferring the proper type parameters of a generic function.

https://github.com/angular/angular/blob/81241af7ac1d320ad17feba1b69fd34f04ac278a/packages/language-service/src/typescript_symbols.ts#L221-L226

We'll look into the possibility of fixing with with a type check block scratchpad that @ayazhafiz is proposing.
If that is too much work, we'll have to wait until the integration of Ivy with the language service, which is already in progress.

**Comment by kyliau** [comment]
@dylansteen The language service currently does not look at angularCompilerOptions, so it'll not have any effect. We're already working on the language service for v10 which will support that fullTemplateTypeCheck flag.

**Comment by undejavue** [comment]
why can't we use something like this? 
<li *ngFor="let image of imageList | sortBy**<ImageModel>** : 'sort'">
    <div>{{image.sort}}</div>
</li>

**Comment by ayazhafiz** [comment]
> why can't we use something like this?
> *ngFor="let image of imageList | sortBy<OurType>"

Unfortunately, that is invalid Angular syntax today (expressions cannot have generics). The most viable use case would likely be just for this issue, so I do not think this syntax would be introduced.

**Comment by LakMoore** [comment]
Would love to see a fix or workaround for this.  Let us know if we can help.  I thought I had made a mistake fixing up my template variable types.  I didn't notice it was compiling despite the warnings in VS Code.

**Comment by Lonli-Lokli** [comment]
@kyliau Angular10 landed, is there update?

**Comment by alxhub** [comment]
The Ivy Language Service is currently under construction. I pasted this example into a running IDE with it.

We're able to infer the generic arguments to `MapPipe.transform`:

<img width="1529" alt="Screen Shot 2020-10-20 at 1 17 18 PM" src="https://user-images.githubusercontent.com/4175141/96655034-63759280-12f1-11eb-8542-705d78091fac.png">

which flows through to the type of `item` in the `*ngFor`: 

<img width="566" alt="Screen_Shot_2020-10-20_at_1 18 58_PM" src="https://user-images.githubusercontent.com/4175141/96655049-725c4500-12f1-11eb-8e1f-6dbb45e6a8a8.png">

**Comment by GeorgeKnap** [comment]
When I turn on experinmental Ivy feature in language service in vscode it doesn't  understand the key to be string in the object.
![image](https://user-images.githubusercontent.com/11920691/108235182-e1ce2e00-7145-11eb-9e20-c4061c14da84.png)

**Comment by JoostK** [comment]
@GeorgeKnap The messages in the screenshot are only reported by the pre-Ivy language service, so it looks like something is off there.

**Comment by samuelfernandez** [comment]
It now works for me!

**Comment by kyliau** [comment]
Closing this, since this has been fixed in the new Ivy-native language service. 
Please see [here](https://github.com/angular/vscode-ng-language-service/releases/tag/v11.1.0) for instructions on how to enable Ivy mode.
