### ISSUE TITLE
Form validation name.untouched does not work in IE11

### ISSUE THREAD

**Issue by StellaLim** [angular/angular#21223]
## I'm submitting a...

`<input formControlName="schduleName" 
        type="text"
        id="name"
        [style.width.%]="89.5"
         [class.ng-dirty]="!newSchdule.controls.schduleName.untouched || 
newSchdule.controls.schduleName.valid"/>`

## Current behavior

It is does not works in IE 11.

## Environment

<pre><code>
Angular CLI: 1.6.2
Node: 6.11.0
OS: win32 x64

Browser:
- [ ] IE 11

 
For Tooling issues:
- Node version: XX  
- Platform: Windows

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by StellaLim** [comment]
I find the problem that I tries to set .ng-dirty in my code. However , angular who can set .ng-dirty class by itself . The problem is that  I use reactive Form to do validation and I set per formControls default value is ' ', which is work for chrom but deson't works in IE 11.

**Comment by kara** [comment]
@StellaLim Can you please create a minimal repro on plunker or stackblitz? As is, this issue is not actionable.

**Comment by kara** [comment]
Closing, as we don't have sufficient information here.
