### ISSUE TITLE
ERROR in TypeError: compiler_1.isFormattedError is not a function 

### ISSUE THREAD

**Issue by AlhagebAlmansoor** [angular/angular#21229]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I am trying to deploy an asp.net core 2.0 angular template project. in the process when I try to execute the "webpack --env.prod" command I get the following error message :

ERROR in TypeError: compiler_1.isFormattedError is not a function
    at syntaxErrorToDiagnostics (C:\projects\Zowara\Code\Webportal\packages\compiler-cli\src\transformers\program.ts:871:14)
    at AngularCompilerProgram._addStructuralDiagnostics (C:\projects\Zowara\Code\Webportal\packages\compiler-cli\src\transformers\program.ts:530:27)
    at AngularCompilerProgram._createProgramOnError (C:\projects\Zowara\Code\Webportal\packages\compiler-cli\src\transformers\program.ts:521:12)
    at C:\projects\Zowara\Code\Webportal\packages\compiler-cli\src\transformers\program.ts:187:26
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

ERROR in main-client.js from UglifyJs
Unexpected token: name (Configuration) [main-client.js:25464,4]

## Expected behavior

To aot compile the application

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v9.1.0  
- Platform: Windows 

Others:

</code></pre>
Package.json:
{
  "name": "Webportal",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "test": "karma start ClientApp/test/karma.conf.js"
  },
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/cdk": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "~5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/platform-server": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@types/webpack-env": "1.13.2",
    "angular-font-awesome": "3.0.3",
    "angular2-jwt": "^0.2.3",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^3.0.1",
    "aspnet-webpack": "^2.0.1",
    "awesome-typescript-loader": "3.2.1",
    "bootstrap": "3.3.7",
    "css": "2.2.1",
    "css-loader": "0.28.4",
    "enhanced-resolve": "^3.3.0",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.9",
    "expose-loader": "0.7.3",
    "extract-text-webpack-plugin": "2.1.2",
    "file-loader": "0.11.2",
    "font-awesome": "4.7.0",
    "hammerjs": "^2.0.8",
    "html-loader": "0.4.5",
    "isomorphic-fetch": "2.2.1",
    "jquery": "3.2.1",
    "json-loader": "0.5.4",
    "jwthelper": "0.0.4",
    "ng2-image-gallery": "^0.3.18",
    "ngx-gallery": "^3.3.0",
    "ngx-logger": "^1.0.0",
    "preboot": "4.5.2",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "^5.5.0",
    "style-loader": "0.18.2",
    "to-string-loader": "1.1.5",
    "typescript": "2.4.1",
    "url-loader": "0.5.9",
    "web-animations-js": "^2.3.1",
    "webpack-hot-middleware": "2.20.0",
    "webpack-merge": "4.1.1",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.3",
    "@angular/compiler-cli": "^5.1.2",
    "@ngtools/webpack": "^1.9.3",
    "@types/chai": "4.0.1",
    "@types/jasmine": "2.5.53",
    "chai": "4.0.2",
    "jasmine-core": "2.6.4",
    "karma": "1.7.0",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.0",
    "karma-webpack": "2.0.3",
    "source-map-support": "^0.5.0",
    "typescript": "latest",
    "webpack": "^3.9.1"
  }
}

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by AlhagebAlmansoor** [comment]
Thanks ericmartinezr , I've already added the missing important information. my day is gone with this problem. I will appreciate any help with this problem.

**Comment by tomfloresa** [comment]
Hi @AlhagebAlmansoor . It seems to be this is a problem with your angular version (5.0.0 as I see). Try to upgrade to a different one (I recommend the latest) and give it a try again. I usually use [ncu](https://www.npmjs.com/package/npm-check-updates) to upgrade dependencies. Let me know if it this helped you!

**Comment by AlhagebAlmansoor** [comment]
@tomfloresa, Thanks a lot it worked! you saved my day.

**Comment by RedBeardDev** [comment]
**ERROR in TypeError: compiler_1.isFormattedError is not a function**
The problem was that a colleague had committed the .ts file and the .html file of the component.
There was code in the.ts but nothing in the.html
During the AOT build process, it will look in these files to optimize the output, and therefore it poses a problem.
Committing the .html file component fixes the problem.

**Comment by smilemuffie** [comment]
I had the same problem too. 
```
{
  "name": "my-app",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.conf.json",
    "build": "ng build --prod --aot --no-extract-license --build-optimizer && npm run gitversion",
    "fastBuild": "node --max_old_space_size=4048 ./node_modules/@angular/cli/bin/ng build --prod --aot --no-extract-license --build-optimizer && npm run gitversion",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "push": "node node_modules/grunt-cli/bin/grunt pubdnt",
    "gitversion": "echo 'gitversion from web' > dist/gitversion && git rev-parse HEAD >> dist/gitversion && date '+%Y-%m-%d %H:%M:%S' >> dist/gitversion"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "5.0.3",
    "@angular/common": "5.0.3",
    "@angular/compiler": "5.0.3",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.0.3",
    "@angular/http": "5.0.3",
    "@angular/platform-browser": "5.0.3",
    "@angular/platform-browser-dynamic": "5.0.3",
    "@angular/router": "5.0.3",
    "bootstrap": "3.3.7",
    "core-js": "2.5.1",
    "crypto-js": "^3.1.9-1",
    "echarts": "3.8.5",
    "file-saver": "^1.3.8",
    "grunt": "^0.4.5",
    "grunt-contrib-concat": "^1.0.1",
    "jquery": "3.2.1",
    "ng-http-interceptor": "4.0.0",
    "ng-zorro-antd": "^0.7.1",
    "ng2-charts": "1.6.0",
    "ng2-file-upload": "1.3.0",
    "ng2-slim-loading-bar": "4.0.0",
    "ngx-bootstrap": "2.0.0-beta.9",
    "ngx-uploader": "4.2.1",
    "perfect-scrollbar": "1.2.0",
    "primeng": "5.2.4",
    "rxjs": "5.5.2",
    "sweetalert2": "7.0.7",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@angular-devkit/core": "0.0.21",
    "@angular/cli": "1.5.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "^3.2.16",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "grunt": "^0.4.5",
    "grunt-cli": "^1.2.0",
    "grunt-contrib-concat": "^1.0.1",
    "grunt-pubdnt": "^0.2.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}
```

I install the @angular/compiler-cli@5.0.0 @angular/compiler@5.0.0 , to keep these 2 packages in same version and it worked;
