### ISSUE TITLE
@NgModule imports object destructuring fails in AOT but compilation succeeds

### ISSUE THREAD

**Issue by dereklin** [angular/angular#21227]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

@NgModule imports object destructuring fails in AOT but compilation succeeds

I have module that looks like this:

```
export class HttpServiceModule {
  public static register({httpServiceSettings}): ModuleWithProviders {
    return {
      ngModule: HttpServiceModule,
      providers: [
        { provide: HTTPSERVICESETTINGS, useValue: httpServiceSettings },
        { provide: HTTPSERVICE, useClass: SimpleHttpService },
        HttpClientService
      ]
    };
  }
}
```

Here is the usage:
```
@NgModule({
  imports: [
    CommonModule,
    CoreRoutingModule,
    TabNavModule,
    HttpServiceModule.register({httpServiceSettings: environment.httpServiceSettings})
  ],

```
I am pulling out the value for key httpServiceSettings

This works with ng serve

In ng serve --prod,

The value for httpServiceSettings is the original object.  The destructuring doesn't happen in AOT mode.
There is no error message.

## Expected behavior

I expect either the destructuring to happen or the compilation to throw an error.

## Minimal reproduction of the problem with instructions

Check out my project branch: https://github.com/dereklin/nx-demo-jest/tree/module-decorator-destructuring

To install:
npm i --no-optional

To run in dev mode:
npm run start:app1
Check the console to see the value is correct

To run in prod mode:
npm run start:app1 -- --prod
Check the console to see the object is just the original object

## What is the motivation / use case for changing the behavior?

This is a bug

## Environment

<pre><code>
Angular version: 5.1.2

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by bgotink** [comment]
Probably linked to #21214

**Comment by JoostK** [comment]
This works partially in Ivy.

The static interpreter itself does not handle the object destructuring in the parameter declaration, but in this particular scenario that isn't relevant as the value for `httpServiceSettings` isn't used at compile time.

**Comment by alxhub** [comment]
Indeed, neither static interpreter supports destructuring, but it's only a problem with VE.

**Comment by AndrewKushnir** [comment]
Closing this ticket since it was marked as ViewEngine-specific and ViewEngine is deprecated. Please reopen if the problem still exists in the latest version of Angular (powered by Ivy).
