### ISSUE TITLE
Proposal: Support passing a setter as a callback/event hook

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2122]
Suppose you have a custom even called `onItemSelected`. Instead of creating a function to handle that event, and assigning a variable as the result, you should be able to just assign the variable. Example:

```html
<material-picker (onItemSelected)="selectedItem="></material-picker>
```

Then, if you have a component:

```js
@View({
  template: '<material-picker (onItemSelected)="selectedItem="></material-picker>'
})
class ParentComponent {
  constructor() {
    this.selectedItem = '';
  }
}
```

When `onItemSelected` is fired, it calls `ParentComponent.selectedItem = $result` automatically.

**Comment by vicb** [comment]
@matanlurey it should be already supported: `(onItemSelected)="selectedItem=$event"`

**Comment by matanlurey** [comment]
Wasn't aware! Let me try :)

**Comment by vicb** [comment]
@matanlurey feel free to re-open if needed
