### ISSUE TITLE
Could not subscribe ActivedRoute url correctly outside router-outlet

### ISSUE THREAD

**Issue by JounQin** [angular/angular#21221]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

As title

## Expected behavior

Should it subscribe same route with same path?

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/9rthObWrtflMkj4n2BI9?p=preview

## What is the motivation / use case for changing the behavior?

I want to get current route path to judge whether render some nodes

## Environment

<pre><code>
Angular version: 5.1.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by Toxicable** [comment]
When you inject `ActivatedRoute` you get the `ActivatedRoute` at that level of the component tree where it's injected, meaning there is not one instance of it, there's many
Something like this might help https://stackblitz.com/edit/angular-param-service?file=app%2Fapp.component.ts

**Comment by JounQin** [comment]
That's cool, thx.
