### ISSUE TITLE
Using markup in translation units causes error: Unknown placeholder "START_TAG_xxx"

### ISSUE THREAD

**Issue by alirezamirian** [angular/angular#21239]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Here is a part of my template:
```html
<div i18n>this is a <span class="highlighted">translatable</span> text</div>
```
I expected this to work as [docs](https://angular.io/guide/i18n) says:

> You can use interpolations and html markup inside of your translations.

When I generate translation file (message.xlf) and run my app with angular-cli, I'm getting the following error:

> ERROR in Error: Unknown placeholder "START_TAG_SPAN" ("
          this is a  [ERROR ->]<x id="START_TAG_SPAN" ctype="x-span ...

I'm adding  `<target />`s for each source with the exact same value.

I didn't find an example of using markup in translations, and I'm not sure if I'm using it the right way.

## Expected behavior
Markup in translatable context should work without error according to docs.

## Environment

<pre><code>
Angular version: X.Y.Z
Angular CLI: 1.5.4
Node: 6.9.1
OS: win32 x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.0.1
@angular/cli: 1.5.4
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.0.1
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.4.2
webpack: 3.8.1

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  6.9.1
- Platform:  Windows
Others:

</code></pre>

**Comment by alirezamirian** [comment]
Interestingly, the problem occurs only with `<span/>`s!

**Comment by ocombe** [comment]
Can you give me the content of your translation file that fails please?

**Comment by alirezamirian** [comment]
I tried to reproduce the problem in a simple repo, but the error is not thrown there!
I'm now investigating more to find a clue about the root of the problem.

**Comment by ocombe** [comment]
My guess is that you used incorrect markup in your target for your translations

**Comment by alirezamirian** [comment]
It seems it was due to duplicate message id! I was mistakenly using same id for two `i18n` attributes, one of them containing a `<span>...</span>`, and another containing a `<b>...</b>`.
The reason I thought it only complains about `span` was that I happen to see and fix id issue at the same time I changed  `span` to something else :smile: 
Anyways, it seems it's not a real issue.

**Comment by istiti** [comment]
Donno if it's related, when i want build I get 
> ERROR in Unknown placeholder "INTERPOLATION" ("Max. [ERROR ->]<ph name="INTERPOLATION"><ex>INTERPOLATION</ex></ph>"): i18n@0:5

Due to 8 usages in code like:
` i18n-placeholder="@@4427020257742730161" placeholder="Max. {{fa?.invoice.amountLeft}}"`

cc @ocombe
