### ISSUE TITLE
Expression converter typo

### ISSUE THREAD

**Issue by bvdmitri** [angular/angular#21233]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
There is a typo in expression_converter.ts
[link](https://github.com/angular/angular/blob/bc7a6d7b0074b0c845035b99d05a831d286b60e4/packages/compiler/src/compiler_util/expression_converter.ts#L340)

```
    // For literal values of null, undefined, true, or false allow type inteference
    // to infer the type.
    const type =
        ast.value === null || ast.value === undefined || ast.value === true || ast.value === true ?
        o.INFERRED_TYPE :
        undefined;
```
```
ast.value === true || ast.value === true
```
## Expected behavior

```
ast.value === true || ast.value === false
```
## What is the motivation / use case for changing the behavior?

Just a typo

## Environment
Any
<pre><code>
Angular version: 5.1.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by bvdmitri** [comment]
As I can see the last commit was made by @chuckjaz. Can you review this line of code?

**Comment by sarunint** [comment]
I believe it is. It's part of #20972

**Comment by alxhub** [comment]
Confirmed as reported, and the error is still there today. This would be an easy one for someone to send a PR (with a test!).

This only affects the legacy View Engine compiler - Ivy doesn't use `expression_converter.ts`.

**Comment by jelbourn** [comment]
Conversation on #37361 indicates that this might be dead code anyway.
