### ISSUE TITLE
Firefox Quantum Form Validation Classes not update on blur/change value input

### ISSUE THREAD

**Issue by capripio** [angular/angular#21236]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I am using form validation, in Firefox Quantum its seems class remain unchanged when un-focus/blurred form field.

## Expected behavior
Working as an expected in Chrome and Edge. classes for form change update as soon as value changed or blurred.

## Minimal reproduction of the problem with instructions

I have created Plunker demo please open it in Firefox Quantum version is 58.0b13 (64-bit)
https://plnkr.co/edit/LsnWTd2aOtNw1V3Puupn?p=preview
Try to write anything in field you will notice name is valid false even if you write something in field. It seems not only classes but form validation doesn't update/change it self.

## What is the motivation / use case for changing the behavior?
Validating Form

## Environment

<pre><code>
Angular version: 5.1.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox Quantum version is 58.0b13 (64-bit)
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.3  
- Platform:  Windows

Others:
package.json dependencies.
"dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "rxjs": "^5.5.2",
    "slideout": "^1.0.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.6.3",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "autoprefixer": "^6.5.3",
    "circular-dependency-plugin": "^4.2.1",
    "codelyzer": "^4.0.1",
    "copy-webpack-plugin": "^4.1.1",
    "css-loader": "^0.28.1",
    "cssnano": "^3.10.0",
    "exports-loader": "^0.6.3",
    "file-loader": "^1.1.5",
    "html-webpack-plugin": "^2.29.0",
    "istanbul-instrumenter-loader": "^2.0.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "less-loader": "^4.0.5",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.1.2",
    "protractor": "~5.1.2",
    "raw-loader": "^0.5.1",
    "sass-loader": "^6.0.3",
    "source-map-loader": "^0.2.0",
    "style-loader": "^0.13.1",
    "stylus-loader": "^3.0.1",
    "tailwindcss": "^0.4.0",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2",
    "uglifyjs-webpack-plugin": "^1.1.5",
    "url-loader": "^0.6.2",
    "webpack": "~3.10.0",
    "webpack-dev-server": "~2.9.3"
  }

**Comment by matpag** [comment]
With the latest Quantum version 57.0.3 is working fine. 
You are testing with a beta release, have you tried filling a bug report in Firefox issues tracker?

**Comment by capripio** [comment]
just checked its seems some plugin causing issue its start working when I run firefox to safe mode

**Comment by capripio** [comment]
it turn out firefox plugin Vimium is causing issue with Angular
