### ISSUE TITLE
CurrencyPipe - currency code is being displayed instead of symbol 

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#21247]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
For certain currency symbols are not being displayed but rather the currency code is. Example, for Brazilian Real the `R$` symbol is being displayed however for Georgian Lari the `GEL` currency code is displayed instead.

```ts
Euro: {{ 1 | currency:'EUR' }} //€1.00
Brazilian Real: {{ 1 | currency:'BRL' }} //R$1.00
Turkish Lira: {{ 1 | currency:'TRY' }} //TRY1.00 this should be ₺1.00
Georgian Lari: {{ 1 | currency:'GEL' }}//GEL1.00 this should be ₾1.00
```

Apart from the above of course they are more currencies with the same issue.

## Expected behavior
Currency symbol is displayed.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-currency-pipe

## Environment

<pre><code>
Angular version: 5.1.2
</code></pre>

**Comment by alan-agius4** [comment]
I noticed that in order to get this working I should use `:symbol-narrow` example

```html
{{ 1 | currency:'GEL':symbol-narrow }}
```

**Comment by ocombe** [comment]
Yes symbol-narrow can be used for that. It depends on the data available in CLDR.
