### ISSUE TITLE
Angular 教程菜单中Http中案例错误

### ISSUE THREAD

**Issue by leixus** [angular/angular#21243]
![image](https://user-images.githubusercontent.com/24884532/34473667-8d298e90-efb0-11e7-814a-83e733523fec.png)

**Comment by leixus** [comment]
https://angular.cn/tutorial/toh-pt6#英雄与-http

**Comment by trotyl** [comment]
It's working properly in [angular.io](https://angular.io/tutorial/toh-pt6), please report the issue to [angular-cn](https://github.com/angular/angular-cn).
