### ISSUE TITLE
two template

### ISSUE THREAD

**Issue by daliri72** [angular/angular#21249]
How can i use two template in an angular project ?

**Comment by Pashozator** [comment]
@daliri72 What means to you using two templates?

**Comment by daliri72** [comment]
Site template (Admin template , Home template )
I have two site template, I want when the URL changes, the site template also changes.

**Comment by Pashozator** [comment]
Use `<router-outlet>` and two components `AdminComponent` and `HomeComponent`.

**Comment by daliri72** [comment]
Can use two <router-outlet> for each module?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by pkozlowski-opensource** [comment]
Thnx @ericmartinezr
