### ISSUE TITLE
angular 4 not send cookie to server and ignore withcredential

### ISSUE THREAD

**Issue by masoudline** [angular/angular#21248]
When I use withCredentials I can see that cookies are sent to the server. But are send anything to the server. I use laravel as backend and angular 4.0.0 as frontend. also, the cookie not shown on chrome developer tools and I can't access them using.

also, I used Cors middleware in laravel like:

```
<?php

namespace App\Http\Middleware;

use Closure;

class Cors
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
      $response = $next($request);
      $response->headers->set('Access-Control-Allow-Origin', 'http://localhost:4200');
      $response->headers->set('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');
      $response->headers->set('Access-Control-Allow-Headers', 'Content-Type, Accept, Authorization, X-Request-With');
      $response->headers->set('Access-Control-Expose-Headers', 'Content-Disposition, x-total-count, x-filename');
      $response->headers->set('Access-Control-Allow-Credentials', 'true');

      return $response;

    }
}
```

and when I request first time to the server for set cookie, these below response show:
```
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:Content-Type, Accept, Authorization, X-Request-With
Access-Control-Allow-Methods:GET, POST, OPTIONS, PUT, PATCH, DELETE
Access-Control-Allow-Origin:http://localhost:4200
Access-Control-Expose-Headers:Content-Disposition, x-total-count, x-filename
Cache-Control:no-cache, private
Connection:keep-alive
Content-Type:application/json
Date:Tue, 02 Jan 2018 09:04:32 GMT
Server:nginx/1.11.9
Set-Cookie:refreshToken=def502005a2ccf60eafdee2137df25a628d49f70c4571bedde628d50e45c0fe4b73f84f86bb469f0f77247dc2abc13c0c5c938027beb13fe534eb7bb41f4aed99faf49ebf2a238a007ce9514108951366db45a311d70d17d65dd48f5df6aa50f257c828cce16e589983c1e06c9e8d7d52806a1a9401569f87b3a394469e938c4ddbfcc7985e257d8f0d0df416e7b8a5bbd19e86050db3be5b90953c515934f529489f4e0ba62fb66ab883d1689349bbfb962332bceb322d978b7d20fa7e32bb94eb0050d8f94bfd3a780c4edfeea8eaa6954222b57c30229c2494fec38ee5292396400b25fadee04cad1729f9e9b9ccf12d21a6ed3f9663d41c5423536e64f83542df19fcede28247bfc12accf354e035182c3e019e4a2b55c807924cc50a12fa187b2f655fb19c1b42a1ae526763dd08dbd0d288b3a9c649216ab1abc60cd51bb97dfb0cb7b7b020ff270cf5c81bc94f2acd40f92edeefaf585d46d0750bf; expires=Sun, 25-Aug-2019 09:04:32 GMT; Max-Age=51840000; path=/; HttpOnly
Transfer-Encoding:chunked
X-RateLimit-Limit:60
X-RateLimit-Remaining:58
```

and when I request from frontend:
```
refreshToken(){

const headers = new Headers({ 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + this.getToken()})
let options = new RequestOptions({ headers: headers, withCredentials: true });
return this.http.post(API_DOMAIN + 'refresh', JSON.stringify({}), options)
  .map(
    (response) => {
      console.log(response);
      return response.json()
    },
  )
  .do(
    tokenData =>{
      localStorage.setItem('token', tokenData.access_token)
      localStorage.setItem('expires_in', tokenData.expires_in)
    }
  )
}
```
chrome developer tools request:
```
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.9,fa;q=0.8
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImNlOTdjNGEyNjBhMjkzMDRkN2VlODI3ZDUyOGQ3MGZlMmNjMTJkYTM2YmQ3NjU2NTcyMThiNzRjNWJhY2E1YjAzZmI0YjI1ZTU3MGRhYjgwIn0.eyJhdWQiOiIyIiwianRpIjoiY2U5N2M0YTI2MGEyOTMwNGQ3ZWU4MjdkNTI4ZDcwZmUyY2MxMmRhMzZiZDc2NTY1NzIxOGI3NGM1YmFjYTViMDNmYjRiMjVlNTcwZGFiODAiLCJpYXQiOjE1MTQ4ODQyMzMsIm5iZiI6MTUxNDg4NDIzMywiZXhwIjoxNTE0ODg0MjkzLCJzdWIiOiIzIiwic2NvcGVzIjpbXX0.QSDnqOlBrGSCqxenYyuWGZbttuV8-a8e6kA9Xwzh56ddOLAE-2-iuKyRh6AB9HaFi_UiRytqOV2UwzIElpMshBTw-OyugfNVSCWZFOxAsAV0zqk3Q6fYB0an0T-eIOpcsrpxwr6c2exXXkpOIS7CjmiTkzIvNILqEULu_mU4W5HbnDQx6rxTkLXZ4kR8vX_SdARsz2CC09jEjPBBA6triXxhIbmu8TxXb6FSQD3LGVZtR9Lsh-1BlxrL-QXLatsQLgnyrWBrsuOgGxPwrR42RoI0cHwam8jB_MSGu5lZtohYCNig2XJjfKIXImvvv4H0bXnaigW5v6uyPfTKPaslZQDMBtIfIPQ0BlJTGNDCPCV-olqwxJCayHNruT03U8St1uuqU-A_b_wvVpqTf4iziVVy739GtywZJTCUJqFwkWPyoXkCVgXcxYbKg0b3rrIOeKcY2dzoiqTzi_kS7jKmr5rMLo0ODP31750f62YOvaQEOXGkSncnwJrePLjxCSzVsnQK8DKuJegwXdcTorZfxhKJBwl7-SwpEKuTnK__YFErITfOlv2kY3fAoIvI-pqh8BvYTxsZC0sSRk4r25XJVGmIOPE3fb8S1moHgJOcW9fDxtm7P9OQv7zSNWPakUIcZEKJxFGzasgVa52shGJ1MyQasL9fljz8xyB0BPuQOJM
Connection:keep-alive
Content-Length:2
Content-Type:application/x-www-form-urlencoded
Host:roxo.test
Origin:http://localhost:4200
Referer:http://localhost:4200/
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
```

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by guguji5** [comment]
I meet the same problem. when I request a cross domain api, the authorization header is missing

**Comment by arlenniu** [comment]
Yes, I use the different ports of the port to test and make use of cookie, but upload to different hosts on the cloud and not carry cookie.
This.http.get (`${baseUrlrs}`, {withCredentials: true});
The server has been configured:
Request URL: https://testserverssssss.azurewebsites.net/api/CorsCookie
Request Method: GET
Status Code: 302 Found
Remote Address: 65.52.168.70:443
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://testclienttttttt.azurewebsites.net
Content-Length: 0
Date: Thu, 07 Jun 2018 10:09:25 GMT
Location: https://testserverssssss.azurewebsites.net/Account/Login?ReturnUrl=%2Fapi%2FCorsCookie
Server: Kestrel
Vary: Origin
X-Powered-By: ASP.NET
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Cookie: ARRAffinity=5e6dac78c4033789a5d2b8df3f1adce74c75f18333c8742ad6a77dc6072893a4
Host: testserverssssss.azurewebsites.net
Origin: https://testclienttttttt.azurewebsites.net
Pragma: no-cache
Referer: https://testclienttttttt.azurewebsites.net/about
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

and
In the case of no verification, it can be used:
This.http.get (`${baseUrlrs}`);
The server is configured to be Access-Control-Allow-Origin: *
CORS is successful.

Is the limitation of azure or NG4, or else, how do I debug it?
NG4 uses Cookie's CORS authentication, in the right way, thank you.
