### ISSUE TITLE
Component property bindings with same name as element bindings are not set.

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#2124]
I have a component where the ```onchange``` property binding is not being set.

e.g.

```
@Component(
    selector: 'my-comp',
    properties: const { 'onValueChange': 'onchange', })
class Comp {
  var onValueChange;
}
```

In a template, I use my-comp:
```
<my-comp [onchange]=someExpr></my-comp>
```

However, ```onValueChange``` is never set, even though ```someExpr``` has a value.

I suspect this behaviour is due to the presence of the ```onchange``` global event handler on ```Element```.

**Comment by mhevery** [comment]
I can't seem to reproduce the problem: http://plnkr.co/edit/4zmTnmslzEgvQgsNSIne?p=preview Can you have a look?

**Comment by jbdeboer** [comment]
This was in dart, not js.

The repo is g-date-picker in gt. Just change the on-value-change property
back to "on change".

On May 28, 2015 3:52 AM, "Miško Hevery" <notifications@github.com> wrote:
>
> I can't seem to reproduce the problem:
http://plnkr.co/edit/4zmTnmslzEgvQgsNSIne?p=preview Can you have a look?
