### ISSUE TITLE
Style bundle in not adding angular cli

### ISSUE THREAD

**Issue by chamikasandamal** [angular/angular#21258]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

"styles" array in `.angular-cli.json` not injecting to `index.html` with server side rendering. I'm using dotnet rendering engine(https://github.com/aspnet/JavaScriptServices/issues/1288)

## Expected behavior

style bundle should added to output like in browser rendering bundle.

## Minimal reproduction of the problem with instructions

add style to "styles" array in `.angular-cli.json` with SSR enabled. 
## What is the motivation / use case for changing the behavior?

client side rendering and SSR should identical

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.5.0  
- Platform:  Windows  

Others:

</code></pre>

**Comment by chuckjaz** [comment]
I'm sorry but this issue is not caused by Angular. Please contact the author(s) of project https://github.com/angular/angular-cli or file issue on their issue tracker.

**Comment by chamikasandamal** [comment]
ok. thanks for confirmation. i will raise an issue there
