### ISSUE TITLE
Import dragula in angular 5 JIT not working

### ISSUE THREAD

**Issue by natcohen** [angular/angular#21251]
I use [dragula](https://github.com/bevacqua/dragula) in my angular-cli project and need to import the dragula object. In my package.json, I added dragula as a dependency and in my component, I import dragula as follow:

    import dragula from 'dragula';

I then log the object to see if it exists `console.log(dragula)`. Surprisingly when I compile the app in AOT mode, the object exists while when I build it in JIT mode, it doesn't exist! Is it a bug from `angular` or am I missing something?

**Comment by ericmartinezr** [comment]
You already opened the issue on the lib's repo https://github.com/bevacqua/dragula/issues/545...

**Comment by pkozlowski-opensource** [comment]
> You already opened the issue on the lib's repo bevacqua/dragula#545...

Yeh, no need to duplicate it here till library author(s) actually confirm that this is a pb with Angular and not the lib.

**Comment by natcohen** [comment]
After further investigation, I discovered that the problem comes from angular-cli. It works with v1.5.5 but not with v1.6

@pkozlowski-opensource I'm not sure to understand why you closed this issue. You just said that the problem comes from Angular and not the lib?!? So the issue should remain open in angular not dragula... Anyway, I will re-open an issue in angular-cli and close the one in the lib

**Comment by pkozlowski-opensource** [comment]
>@pkozlowski-opensource I'm not sure to understand why you closed this issue. You just said that the problem comes from Angular and not the lib?!?

This is _not_ what I have said, please check my comment again...

**Comment by natcohen** [comment]
@pkozlowski-opensource Well, your comment is not clear at all!

> author(s) actually confirms that this is a pb with Angular and not the lib

For your record, here is the opened issue https://github.com/angular/angular-cli/issues/9059

**Comment by ericmartinezr** [comment]
>till library author(s) actually confirms that this is a pb with Angular and not the lib.

You forgot to read the "till" ;D

**Comment by natcohen** [comment]
@ericmartinezr My bad...

Please use emojis for constructive purpose, github is not facebook or twitter!
