### ISSUE TITLE
Error: Missing locale data for the locale "de".

### ISSUE THREAD

**Issue by MiroKov** [angular/angular#21255]
## I'm submitting a...
[x] Bug report  

## Current behavior
Problem arises when using a dynamic locale-changing pipe, but **only using ng build --prod**.
In browser, following error occurs:

> Error: Missing locale data for the locale "de".

Checked already on SO, posted a question but also found no answer.
Most confusing is the fact that it works using ng-serve.

## Expected behavior
Pipe changing the date according to language selected.

## Minimal reproduction of the problem with instructions

Pipe is recieving locale from a translating service:
```ts
@Pipe({
    name: 'localdate'
}) export class LocalizedDatePipe implements PipeTransform {
    constructor(
        // private _translateService: TranslateService
    ) {
 }
 public transform(value: any, pattern = 'dd.MM.yyyy EEEE HH:mm:ss', currentLocale: string): any {
        const ngPipe = new DatePipe(currentLocale);
        return ngPipe.transform(value, pattern);
    }
}
```

html:

` {{ASN.ClosedDateTime |jsonDate|localdate:'dd.MM.yyyy EEEE HH:mm:ss':currentLanguage}}`

in App.module:

```ts
import { registerLocaleData } from '@angular/common';
import localeDE from '@angular/common/locales/de';
registerLocaleData(localeDE);

...
 providers: [

   ...,
    {
      provide: LOCALE_ID,
      deps: [TranslateService],
      useFactory: (translateService) => translateService.currentLang
    }
  ],

```

## Environment

"@angular/core": "^5.1.2",
"@angular/cli": "1.6.2",

Browser:
All browsers.
 
For Tooling issues:
- Node version: 6.11.4
- Platform:  Windows

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/20286

**Comment by MiroKov** [comment]
Please read the question before writing automated answers. Thank you.

**Comment by ocombe** [comment]
You know that the data pipe can receive the locale as an extra parameter? You don't need to write your own pipe for that.
Your html would be:
```html
{{ ASN.ClosedDateTime | jsonDate | date:'dd.MM.yyyy EEEE HH:mm:ss':'':currentLanguage }}
```

Does it work if you do that?

**Comment by MiroKov** [comment]
Yes, 
I have used this before, however, with that I do not have dynamically changing locale of the date.
When the module is set as quoted above, with the code you wrote, date is always in german.
This works in ng build --prod as well.

**Comment by ocombe** [comment]
I don't understand why? You can change the value of "currentLanguage" in your template at any time and if would use another language.
Could you provide a minimal example that I could try? It would make things clearer to see what you're trying to do.

**Comment by MiroKov** [comment]
Found the error.
Was using
`{{ASN.ClosedDateTime |jsonDate|date:'dd.MM.yyyy EEEE HH:mm:ss':currentLanguage}}`
instead of
`{{ ASN.ClosedDateTime | jsonDate | date:'dd.MM.yyyy EEEE HH:mm:ss':'':currentLanguage }}`.

Sorry for taking your time, but thank you still because I do not think I would have found it otherwise.

**Comment by ocombe** [comment]
No problem!
