### ISSUE TITLE
Please make getLocaleDateFormat available outside the Angular framework

### ISSUE THREAD

**Issue by areijngoudt** [angular/angular#21253]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have imported the CommonModule, set the locale using angular-cli and now want to use the locale settings from the injected @angular/common/locales/ file. When I call getLocaleDateFormat() (from the local_data_api) the next error is thrown:

```
Module not found: Error: Can't resolve '@angular/common/src/i18n/locale_data_api' in ...
```

I suspect this is because the local_data_api is private. It there another way to use the locale settings?

## What is the motivation / use case for changing the behavior?
I would like to get access to the date format used with the set locale. I want to use it to parse / validate entered dates and to show the used format as a tooltip.

## Environment

<pre><code>
Angular version: 5.1.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ocombe** [comment]
`getLocaleDateFormat` is exported by the common module. Try to import it like that `import {getLocaleDateFormat} from "@angular/common"` and it should work. If not, please provide a reproducible example (stackblitz or plunkr) that demonstrates the issue.

**Comment by areijngoudt** [comment]
```
import { getLocaleDateFormat, FormatWidth } from '@angular/common';
```
works. Thanks!
