### ISSUE TITLE
EntryComponents Not Documented

### ISSUE THREAD

**Issue by spottedmahn** [angular/angular#21257]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
`entryComponents` are not documented on the [NgModules page](https://angular.io/guide/ngmodule).

## Expected behavior
`entryComponents` should be documented.

## What is the motivation / use case for changing the behavior?
What are they?  What is their purpose?

**Comment by Doehl** [comment]
This would be nice, since `entryComponents` are used by cdk overlay.

**Comment by spottedmahn** [comment]
I did find documentation about them [under the FAQs](https://angular.io/guide/ngmodule-faq#what-is-an-entry-component).

Also interesting, googling 'angular.io entrycomponents' doesn't seem to find anything on angular.io.

**Comment by kapunahelewong** [comment]
Thank you, @spottedmahn and @Doehl. Documentation on `entryComponents` is forthcoming in [20306](https://github.com/angular/angular/pull/20306). You can see the new file dedicated to `entryComponents` [here](https://github.com/ExpertSupport/angular/blob/a2b94b5fe3dc162ec2fcfbec74b749d03b8c44c9/aio/content/guide/entry-components.md). The PR has a few details that still need working out, but maybe this will help with any questions in the meantime.

Let me know if you have any questions.

**Comment by kapunahelewong** [comment]
Hi @spottedmahn and @Doehl there's a new page dedicated to entryComponents! [Entry Components](https://angular.io/guide/entry-components). I'll close this issue, but if you still have outstanding questions, please feel free to let me know. And if you see room for improvement in this new doc, I'm very interested in feedback.

**Comment by spottedmahn** [comment]
Awesome, thanks @kapunahelewong
