### ISSUE TITLE
Tab switching transition is visually too distracting

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21262]
## Current behavior

When switching between example tabs in aio, the transitions cause the old pane to abruptly disappear and the new content to fly in. This causes a lot of visual noise, as well as sudden resizing and relayout of the page.

## Expected behavior

A more subtle transition (like cross fade) would likely result in a better user experience.

## Minimal reproduction of the problem with instructions

Go to https://angular.io/tutorial/toh-pt0#final-code-review and switch between panes

![aio-tabs-animation](https://user-images.githubusercontent.com/216296/34499834-dbc63f74-efbc-11e7-982b-7b62926953d4.gif)

## What is the motivation / use case for changing the behavior?

Better UX

**Comment by petebacondarwin** [comment]
Still an issue. Although at least the scroll position doesn't change. Is that good enough?

**Comment by sjtrimble** [comment]
I think what we have now is much better than the example gif displayed in the issue.

@IgorMinar @petebacondarwin can we close this out, or do we need to discuss further?

**Comment by petebacondarwin** [comment]
With the scroll position not changing I am happier with this, but it was @IgorMinar who originally created this issue, so I leave the final call to him.

**Comment by sjtrimble** [comment]
I assigned to @IgorMinar for him to review/close out :)
