### ISSUE TITLE
FormGroupDirective.submitted is not propagated to inner FormGroupDirectives

### ISSUE THREAD

**Issue by ukrukarg** [angular/angular#21263]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

#### What is the expected behavior?
Error should be shown even if I have more then one [formGroup] on a page.

#### What is the current behavior?
Error not shown.

#### What are the steps to reproduce?
1. https://stackblitz.com/edit/angular-evuu4c
2. Click submit
3. Address 2 should have an error message, but it doesn't.

Important piece is in input-form-example.html:36. I use `[formGroup]="form.get('address')"` instead of `formGroupName="address"`and that is causing the bug. Material component depend on FormGroupDirective.submitted property to show errors on fields after submit. That is set only on FormGroupDirective added to `form` tag itself, but not other FormGroupDirectives.

#### What is the use-case or motivation for changing an existing behavior?
In my case I have parts of my form in subcomponents, pretty complicated ones, and I cannot use formGroupName. As a result validation errors don't show.

In some places I started doing this:

```
// Tell internal form that outer form was submitted.
// Needed to show validation error even for untouched inputs.
this.outerForm.ngSubmit.pipe(takeUntil(this.destroy))
    .subscribe((event: Event) => {
        this.innerFormGroupDirective.onSubmit(event);
    });
```
but I think FormGroupDirective should just do that (if host is no the `form`).

**Comment by kara** [comment]
@ukrukarg and I discussed a different solution offline, but for anyone finding this issue:

Generally speaking, `[formGroup]` is used as a top-level form directive only.  For nested FormGroups, you'd want to use `formGroupName` instead to ensure that the nested group value and validation status are properly synced to the parent group's value and validation status, among other things.

So if you *do* have a nested `[formGroup]`, it typically indicates that you have a nested form that is *not* related to the parent form. It's another top-level form that will not be connected to its parent's model.  This is a relatively common pattern because, for CSS / positioning reasons, you might have a sub-form that happens to be within the form tags of another form, but is unrelated (e.g.  a shopping checkout form with a "newsletter sign-up" sub form).

If we were to connect sub `[formGroup]` directives to their parents in this case, it would break any apps with this pattern. So instead, we will pursue adding the `submitted` property to the `FormGroup`.

**Comment by jpzwarte** [comment]
@kara I understand your reasoning, and its fine. However, i'm running into an issue (bug?) where i have a reactive form with a `FormArray` that uses a child component to render. It seems i **have** to use a `[formGroup]` directive inside the child component, otherwise i will receive errors like "formControlName must be used with a parent formGroup directive".

When i don't use a child component and just inline the HTML, it works fine. It is just with the child component that i run into issues.

I've tried to reproduce the issue here: https://angular-qvjckb.stackblitz.io

**Comment by jpzwarte** [comment]
So i've fixed this in my own component library by writing a directive with selector `[formGroup]` that connects the root form group with nested form groups.

```typescript
import { Directive, OnDestroy, Optional, Self, SkipSelf } from '@angular/core';
import { FormGroupDirective as AngularFormGroupDirective } from '@angular/forms';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

@Directive({
  selector: '[formGroup]'
})
export class FormGroupDirective implements OnDestroy {
  private destroyed = new Subject<void>();

  constructor(
    @Self() formGroupDirective: AngularFormGroupDirective,
    @Optional() @SkipSelf() parentFormGroupDirective: AngularFormGroupDirective
  ) {
    if (parentFormGroupDirective) {
      parentFormGroupDirective.ngSubmit.pipe(takeUntil(this.destroyed)).subscribe((event: any) => {
        formGroupDirective.onSubmit(event);
      });
    }
  }

  ngOnDestroy(): void {
    this.destroyed.next();
    this.destroyed.complete();
  }
}
```

**Comment by jonnyleeharris** [comment]
@jpzwarte I too have used this solution but am unsure how to mark the child forms as submitted when they are added to an already submitted parent form. Any ideas?

**Comment by jpzwarte** [comment]
@jonnyleeharris you could try adding the `startWith(parentFormGroupDirective.submitted)`

But my earlier comment is not really the way to go. It is better to add a child component containing the child form and then have that child component implement form `ControlValueAccessor` interface.

**Comment by jonnyleeharris** [comment]
@jpzwarte Thanks for replying :)

I've actually done this (implemented the `ControlValueAccessor`). The sub component has its own formGroup though, and therein seems to be the issue. It doesn't know when the parent form has been submitted. Do you propose a way around that?

```typescript
import { Component, forwardRef, OnInit } from '@angular/core';
import { AbstractControl, ControlValueAccessor, FormBuilder, NG_VALIDATORS, NG_VALUE_ACCESSOR, ValidationErrors, Validator, Validators } from '@angular/forms';

@Component({
  selector: 'app-address-input',
  templateUrl: './address-input.component.html',
  styleUrls: ['./address-input.component.scss'],
  providers: [        
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => AddressInputComponent),
      multi: true
    },
     {
      provide: NG_VALIDATORS,
      useExisting: forwardRef(() => AddressInputComponent),
      multi: true
    }
  ]
})
export class AddressInputComponent implements OnInit, ControlValueAccessor, Validator {

  readonly form = this.formBuilder.group({
    line1: ["", Validators.required],
    line2: [""],
    city: ["", Validators.required],
    zipCode: ["", Validators.required],
    country: ["", Validators.required]
  });

  public onTouched: () => void = () => {};

  validate(control: AbstractControl): ValidationErrors | null {    
    return this.form.valid ? null : { invalidForm: {valid: false, message: "Address fields are invalid"}};
  }
  
  writeValue(val: any): void {
    val && this.form.setValue(val, { emitEvent: false });
  }
  registerOnChange(fn: any): void {
    this.form.valueChanges.subscribe(fn);
  }
  registerOnTouched(fn: any): void {    
    this.onTouched = fn;
  }
  setDisabledState?(isDisabled: boolean): void {
    isDisabled ? this.form.disable() : this.form.enable();
  }

  constructor(private formBuilder:FormBuilder) { }  

  ngOnInit() {
  }

}
```


```html
<div fxLayout="column" [formGroup]="form">
    <div fxLayout="row" fxLayoutGap="20px">
        <mat-form-field fxFlex="1 1 auto">
            <input matInput placeholder="{{'address.line_1' | translate}}" formControlName="line1">
        </mat-form-field>    
        <mat-form-field fxFlex="1 1 auto">
            <input matInput placeholder="{{'address.line_2' | translate}}" formControlName="line2">
        </mat-form-field>
    </div>
    <div fxLayout="row" fxLayoutGap="20px">
        <mat-form-field fxFlex="1 1 auto">
            <input matInput placeholder="{{'address.city' | translate}}" formControlName="city">
        </mat-form-field>
        <mat-form-field fxFlex="1 1 auto">
            <input matInput placeholder="{{'address.zip' | translate}}" formControlName="zipCode">
        </mat-form-field>
        <mat-form-field fxFlex="1 1 auto">
            <input matInput placeholder="{{'address.country' | translate}}" formControlName="country">
        </mat-form-field>
    </div>
</div>
```

**Comment by jpzwarte** [comment]
@jonnyleeharris  Hmm, i don't think there's an easy answer. "submitted" is not something that is passed to `ControlValueAccessor`. Without looking into right now, i guess you still needs to use my `FormGroupDirective` workaround for now.

**Comment by benneq** [comment]
I've written an `AbstractFormGroupControlValueAccessor` class which pretty much solves all issues. Feel free to comment and provide improvements 😄 

Here we go: 
```ts
export abstract class AbstractFormGroupControlValueAccessor implements DoCheck, OnDestroy, ControlValueAccessor, Validator {
  abstract form: FormGroup;
  subscriptions = [] as Array<Subscription>;
  submitted = false;
  onTouched: any = () => { };

  constructor(
    protected fb: FormBuilder,
    protected cdr: ChangeDetectorRef,
    protected formGroupDirective: FormGroupDirective
  ) { }

  // This isn't super performant, but it's reliable
  ngDoCheck() {
    if (this.submitted !== this.formGroupDirective.submitted) {
      this.submitted = this.formGroupDirective.submitted;
      if (this.submitted) {
        this.form.markAllAsTouched();
      }
      this.cdr.markForCheck();
    }
  }

  ngOnDestroy() {
    this.subscriptions.forEach(subscription => subscription.unsubscribe());
  }

  writeValue(obj: any): void {
    // when you call `reset()` on your parent form, it will always set `null`
    // though I use this as an indicator to reset this FormGroup, too.
    if (obj === null) {
      this.form.reset();
    } else {
      this.form.setValue(obj, { emitEvent: false });
    }
  }

  registerOnChange(fn: any): void {
    this.subscriptions.push(this.form.valueChanges.subscribe(fn));
  }

  // unused for now
  registerOnTouched(fn: any): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    if (isDisabled) {
      this.form.disable();
    } else {
      this.form.enable();
    }
  }

  validate(control: AbstractControl): ValidationErrors | null {
    return this.form.valid ? null : getAllErrors(this.form);
  }
}
```

This helper function collects all the errors from the `FormGroup`:
```ts
export function getAllErrors(form: FormGroup | FormArray): { [key: string]: any; } | null {
  let hasError = false;
  const result = Object.keys(form.controls).reduce((acc, key) => {
    const control = form.get(key);
    if (control) {
      const errors = (control instanceof FormGroup || control instanceof FormArray)
        ? getAllErrors(control)
        : control.errors;
      if (errors) {
        acc[key] = errors;
        hasError = true;
      }
    }
    return acc;
  }, {} as { [key: string]: any; });
  return hasError ? result : null;
}
```

And then you can use this to implement your own FormGroupControlValueAccessor, like this:
```ts
@Component({
  selector: 'app-event-territorial-protection-form',
  templateUrl: './event-territorial-protection.form.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    ngValueAccessorProviderFactory(EventTerritorialProtectionForm),
    ngValidatorsProviderFactory(EventTerritorialProtectionForm)
  ]
})
export class UserForm extends AbstractFormGroupControlValueAccessor {
  form = this.fb.group({
    username: ['', [Validators.required]],
    password: ['', [Validators.required]]
  });

  get username(): FormControl {
    return this.form.get('username') as FormControl;
  }

  get password(): FormControl {
    return this.form.get('password') as FormControl;
  }
}
```

And last but not least the helper functions for the providers:
```ts
export function ngValueAccessorProviderFactory(val: any) {
  return {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => val),
    multi: true
  };
}

export function ngValidatorsProviderFactory(val: any) {
  return {
    provide: NG_VALIDATORS,
    useExisting: forwardRef(() => val),
    multi: true
  };
}
```
