### ISSUE TITLE
Transpiling breaks usage of this reference in simple use case.

### ISSUE THREAD

**Issue by adamspe** [angular/angular#21267]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Production build displays <code>runtime error "Cannot read property 'data' of undefined</code> while this error does not occur with a dev+aot build.

<pre><code>
E.g.
$ ng build --aot --dev
works
$ ng build --aot --prod
(obviously with or without --aot) fails.
</code></pre>

The "offending" client TypeScript code that results in this error is (obviously, within an instance function):
<pre><code>
        let previousValue = this.data.attributes[name];
... more code that makes up dates to this.data.attributes ...
        let changes:SimpleChanges = {};
        changes[name] = new SimpleChange(previousValue,this.data.attributes[name],false);
        this.wrapperChanges.next(changes);
</code></pre>

The resulting code transpiled from TypeScript to JavaScript is (pretty printed from Chrome Dev Tools):
<pre><code>
this.wrapperChanges.next(function() {
                    var e = {};
                    return e[t] = new za.I(n,this.data.attributes[t],!1),
                    e
                }())
</code></pre>

As you can see, the closure that is being created here invalidates the <code>this</code> reference resulting in the error.

This code exists in an abstract base class that isolates complex data models from the rest of the app using <code>@set/get</code> on sub-classes.  <code>@set/get</code> implementations use relatively simple helper functions on the base class to interact with the underlying data model.  Each instance has a <code>Subject</code> where updates can be subscribed to (though these details are almost certainly unnecessary).

The <code>wrapperChanges</code> instance variable is defined as: 

<code>wrapperChanges:Subject&lt;SimpleChanges&gt; = new Subject();</code>

Changing the last three lines of my client code above to:
<pre><code>
        let changes:SimpleChanges = {},
            currentValue = this.data.relationships[name];
        changes[name] = new SimpleChange(previousValue,currentValue,false);
        this.wrapperChanges.next(changes);
</code></pre>

Works around the problem with transpiling.

I'm not certain that this isn't a TypeScript issue rather than an Angular issue, it may very well be.  I tried upgrading to TypeScript 2.6.1 (and ignoring the warnings that result) but it had no effect.

## Expected behavior

Simple code like this that functions fine in a dev build should transpile to code that functions identically in production.

## Minimal reproduction of the problem with instructions

Hopefully, the code snippets above are sufficient since I'm not sure how to simulate dev/prod builds via something like plunkr.  If absolutely necessary I could try to put together a representative scaled-down project to try to recreate the problem (though it's very obscure, I have a workaround and have already spent too much time waiting for production builds to narrow down the error to work around it).

## Environment

<pre><code>
@angular/core v5.1.2
@angular/compiler-cli v5.1.2
typescript 2.4.2 

As mentioned I have tried a much later version of TypeScript and am already using the latest "stable" version of Angular.

Browser:
- [X] Chrome (desktop) version 63.0.3239.84 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 5.4.2  
- Platform:  Mac 

Others:

</code></pre>

**Comment by chuckjaz** [comment]
Please supply a link to a repository that reproduces this issue.

**Comment by adamspe** [comment]
While the problem still happens with my original project I have been unable to recreate a smaller simplified representative version where the same happens.

Regardless of what I do the JS that is generated does _not_ use a closure as shown in the original description of the problem (so there is no runtime error).  This seems logical since I see no reason a closure _should_ be generated for those few lines of code.

I have tried copying over the `package[-lock].json` from the original project to ensure that the exact same versions of everything are in place to no effect.  The simplified application, obviously, doesn't make use of all the same third-party code (google material, moment, google maps, etc.) even though some of it is imported via modules I assume the build process would exclude it (and, regardless, why its inclusion should affect TS->JS compilation makes no sense to me).

I'm inclined to say close this issue.  I cannot justify spending much more time trying to recreate it in a simplified project, and if you don't have a reproducible problem then there's nothing to do.

**Comment by pkozlowski-opensource** [comment]
Closing based on:

> I'm inclined to say close this issue. I cannot justify spending much more time trying to recreate it in a simplified project, and if you don't have a reproducible problem then there's nothing to do.
