### ISSUE TITLE
When does the build use esm2015 vs esm5?

### ISSUE THREAD

**Issue by CWSpear** [angular/angular#21260]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The build locally uses `node_modules/@angular/animations/esm2015/animations.js`, but in a different environment, using the same Node version and package versions, it uses `node_modules/@angular/animations/esm5/animations.js`.

## Expected behavior

The build uses `node_modules/@angular/animations/esm2015/animations.js` in both places.

We're using `@angular/cli` version `nrwl/fix-cli-build` using `ng build --aot --prod`.

## Minimal reproduction of the problem with instructions

Cannot reliably reproduce :(

## What is the motivation / use case for changing the behavior?

I marked this as a document issue, because I'm unsure why it decides to use the `esm5` version in one place and the `esm2015` in another. I noticed the `module` and `es2015` properties in the `package.json`, but I couldn't find documentation in `npm`'s docs about these, so I'm thinking they're nonstandard? 

If I could find out why it uses which, I may be able to better debug this, and find out what is different in my build environment that's causing this.

More specifically, the `esm5` in `@angular/animations` `5.0.0` does not uglify correctly. If I can figure out why it's using this version, I can better reproduce the issue I'm seeing and perhaps open a new issue (or maybe it's not relevant since it's gone in `5.1.2`, but the inconsistent builds is still an issue).

## Environment

<pre><code>
Angular version: 5.0.0 (and tried 5.1.2)

Browser:
- [x] Chrome (desktop) version 63.0.3239.108
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 57.0.3 
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.12.1 and tried 9.3.0  
- Platform:  Linux (doesn't work), Windows

Others:

</code></pre>

**Comment by devoto13** [comment]
These fields are used by Webpack. See [here](https://webpack.js.org/configuration/resolve/#resolve-mainfields). This is managed by Angular CLI. I would start by making sure that both environments use same Angular CLI version.

**Comment by CWSpear** [comment]
@devoto13 yeah... I just noticed we're using `nrwl/fix-cli-build` as the version for `@angular/cli`. It _should_ be the same version in both environments, tho. Tried fresh `npm install`s.

**Comment by CWSpear** [comment]
Updating the CLI to `1.6.3` seems to fix whatever issue(s) I was seeing.

I think there is definitely an issue in there somewhere, but I don't think it's something likely to come up and may have already been fixed in latest version, etc... unless it somehow pops back up, I think this is more or less a nonissue, and I'm closing.

Thanks @devoto13 for the info and pointing me in the right direction.
