### ISSUE TITLE
'Reference to a non-exported function' error with custom decorator.

### ISSUE THREAD

**Issue by kevinphelps** [angular/angular#21273]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

```typescript
interface NameViewModel {
  name: string;
  nameLength: number;
}

@Component({
  selector: 'app-test',
  templateUrl: './test.component.html',
  styleUrls: ['./test.component.css']
})
export class TestComponent {
  @Input() @Convert(convertName) name: NameViewModel;
}

/*export*/ function convertName(name: string) {
  const model: NameViewModel = {
    name,
    nameLength: name.length
  };

  return model;
}
```

AOT build error:
```
ERROR in src\app\test\test.component.ts(19,21): Error during template compile of 'TestComponent'
  Reference to a non-exported function.
```

## Expected behavior

I don't think the `convertName` function should have to be exported. The Angular compiler should not care because `@Convert(...)` is not an Angular decorator.

## Minimal reproduction of the problem with instructions

https://github.com/kevinphelps/angular-custom-decorator-no-export-issue

## What is the motivation / use case for changing the behavior?

I don't think the `convertName` function should have to be exported. The Angular compiler should not care because `@Convert(...)` is not an Angular decorator.

## Environment

<pre><code>
Angular version: 5.1.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.1
- Platform: Windows 10

Others:

Angular CLI: 1.6.0-beta.0
Node: 8.9.1
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.0-beta.0
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0-beta.0
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.8.1
</code></pre>

**Comment by alan-agius4** [comment]
Somewhat related to https://github.com/angular/angular/issues/21123

**Comment by chuckjaz** [comment]
@alan-agius4 #21123 is unrelated.
