### ISSUE TITLE
Suggest theme with Angular 4 or 5 for retail/ecommerce website 

### ISSUE THREAD

**Issue by mavajih** [angular/angular#21277]
I need to develop one retail website having functionality of catalog/products grid view with filters, store geo location with google map , search store/catalog/product, login/signup.

Please suggest theme with Angular 4 or 5 for functionality listed above.

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
