### ISSUE TITLE
aio(bug) - Reactive Forms plunker is crashing; looks like tooling problem

### ISSUE THREAD

**Issue by wardbell** [angular/angular#21289]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The plunker for the [Reactive Forms](https://angular.io/guide/reactive-forms) guide crashes (in Chrome):
https://angular.io/generated/live-examples/reactive-forms/final.eplnkr.html

The immediate problem is that the plunker generator "uploads" a file named `main-final.ts` which the `index.html` expects to be `main.ts`. Physically renaming the file in the Plunker makes it work.

The `plunker.json` appears to be correct, the relevant fragment being
```
    "main-final.ts",
    "index-final.html"
  ],
  "main": "index-final.html",
  "tags": ["reactive", "forms"]
```

I suspect that something is amiss in the plunker generator.

There is a good chance that there is a related error in the forthcoming `StackblitzBuilder`.

**Comment by IgorMinar** [comment]
This works fine in https://pr20165-325d58f.ngbuilds.io/guide/reactive-forms so I'm going to close this issue.

**Comment by petebacondarwin** [comment]
@IgorMinar do please remove such issues from the AIO project when you close them.
