### ISSUE TITLE
Unused import is created when compiling with NGC

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#21280]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Angular Compiler is not stripping out unused inputs for classes that are used solely for type definitions.

```ts
import { Component, Input } from "@angular/core";
import { FormControl } from "@angular/forms";

@Component({
   template: ``
})
export class MainComponent  {
  @Input() form: FormControl;
} 
```

In the output file generated by `NGC` there is an unused import that is used only for types within the component https://github.com/alan-agius4/angular-ngc-unused-imports/blob/master/ngc-out/main.component.js#L2
```js
import { Component, Input } from "@angular/core";
import { FormControl } from "@angular/forms"; // this is unused
export class MainComponent {
}
MainComponent.decorators = [
    { type: Component, args: [{
                template: ``
            },] },
];
/** @nocollapse */
MainComponent.ctorParameters = () => [];
MainComponent.propDecorators = {
    "form": [{ type: Input },],
};
```

When using `TSC` there is no unused import https://github.com/alan-agius4/angular-ngc-unused-imports/blob/master/tsc-out/main.component.js
```js
import * as tslib_1 from "tslib";
import { Component, Input } from "@angular/core";
let MainComponent = class MainComponent {
};
tslib_1.__decorate([
    Input()
], MainComponent.prototype, "form", void 0);
MainComponent = tslib_1.__decorate([
    Component({
        template: ``
    })
], MainComponent);
export { MainComponent };
```
## Expected behavior
The import statement is dropped.

## Minimal reproduction of the problem with instructions
https://github.com/alan-agius4/angular-ngc-unused-imports

## What is the motivation / use case for changing the behavior?
No unused import is created, As when I generate my library and using `rollup` to create `FESM`, this will create an import to the whole dependency example;
```js
import { FormControl } from "@angular/forms";
```
will be transformed to
```js
import "@angular/forms";
```

and like this there will be no treeshaking and the bundle size will eventually increase a lot

## Environment

<pre><code>
Angular version: 5.1.2
TypeScript version: 2.5.3
</code></pre>

  
Other details:
https://github.com/Microsoft/TypeScript/issues/17552

**Comment by sarunint** [comment]
Rollup should be smart enough to not include `@angular/forms`. Have you tried running rollup yet?

**Comment by alan-agius4** [comment]
Yes, can my comment above.

**Comment by hughanderson4** [comment]
It happens with `ElementRef` too.
Additional info [here](https://github.com/ng-packagr/ng-packagr/issues/710#issuecomment-451197666)

**Comment by trotyl** [comment]
This isn't about `ngc` or `tsc`, but whether `emitDecoratorMetadata` set to `true`. Currently `ngc` always switch on that option for lib build:

https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/compiler-cli/src/main.ts#L59-L64

TypeScript can either preserve all type annotation imports or drop them all, there's no smart detection in between, so `emitDecoratorMetadata` must be used otherwise `ctorParameters` would be broken. As long as `emitDecoratorMetadata` used, type annotation imports will all be preserved by TypeScript.

Given all angular packages [were marked `sideEffects: false`](https://github.com/angular/angular/pull/22785), it should have no size impact for final Webpack users. A better solution is https://github.com/rollup/rollup/issues/2593, which will handle `sideEffects` directly in library build.

**Comment by alan-agius4** [comment]
@trotyl, you are right it's due to `emitDecoratorMetadata`. 

Though for AOT it will result in an unused import since there won't be any decorator metadata, thus ideally the ngc compiler should elide the unused imports since tsc won't do see https://github.com/Microsoft/TypeScript/issues/17552

This is not just due to the bundle size, but also the build time, the more modules you include the slower the build is. Though `@ngtools/webpack` does have a workaround for these usecases https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/src/transformers/elide_imports.ts

**Comment by hpawe01** [comment]
@alan-agius4 thank you for pointing the workaround at `@ngtools/webpack`. But do you know how do I incorporate this transformer into the default Angular CLI config (without ejecting)?

**Comment by alan-agius4** [comment]
@hpawe01, you will need to integrate Jest to use Webpack first. However, I am not aware of any good open source solutions for that.

**Comment by alan-agius4** [comment]
@hpawe01, the CLI already handles this when building the application. 

How are you experiencing this issue?

**Comment by hpawe01** [comment]
@alan-agius4, I have an Angular library (with latest dependencies), that I build with ivy disabled (for npm publishing). The default `@angular-devkit/build-ng-packagr:build` builder is used.

And when ngc is bundling the project to `FESM2015` and `FESM5`, the warnings appear:
```
Bundling to FESM2015
WARNING: 'AfterViewInit', 'OnChanges', 'OnInit', 'SimpleChanges', 'HostListener', 'OnDestroy' and 'EmbeddedViewRef' are imported from external module '@angular/core' but never used
WARNING: 'SafeStyle', 'SafeResourceUrl' and 'SafeUrl' are imported from external module '@angular/platform-browser' but never used
...
```

**Comment by Vikki123** [comment]
Was there any fix or workaround for this ?

**Comment by guillaume-f** [comment]
Same issue...

`Compiling TypeScript sources through ngc
Bundling to FESM2015
WARNING: Non-existent export 'BlobFileData' is imported from dist\kernel\esm2015\lib\core\services\file-transfer.service.js
WARNING: 'InjectionToken', 'Type', 'OnInit', 'AfterContentInit', 'OnChanges', 'SimpleChanges', 'OnDestroy' and 'EmbeddedViewRef' are imported from external module '@angular/core' but never used
WARNING: 'Data', 'Event', 'UrlTree', 'ActivatedRouteSnapshot', 'CanActivate', 'CanActivateChild', 'CanLoad', 'Route', 'RouterStateSnapshot' and 'Routes' are imported from external module '@angular/router' but never used
WARNING: 'HttpEvent' is imported from external module '@angular/common/http' but never used
WARNING: 'Action' is imported from external module '@ngrx/store' but never used
WARNING: 'MenuItem' is imported from external module 'primeng/api' but never used
WARNING: 'ControlValueAccessor', 'ValidationErrors' and 'Validator' are imported from external module '@angular/forms' but never used
Bundling to FESM5
WARNING: Non-existent export 'BlobFileData' is imported from dist\kernel\esm5\lib\core\services\file-transfer.service.js
WARNING: 'InjectionToken', 'Type', 'OnInit', 'AfterContentInit', 'OnChanges', 'SimpleChanges', 'OnDestroy' and 'EmbeddedViewRef' are imported from external module '@angular/core' but never used
WARNING: 'Data', 'Event', 'UrlTree', 'ActivatedRouteSnapshot', 'CanActivate', 'CanActivateChild', 'CanLoad', 'Route', 'RouterStateSnapshot' and 'Routes' are imported from external module '@angular/router' but never used
WARNING: 'HttpEvent' is imported from external module '@angular/common/http' but never used
WARNING: 'Action' is imported from external module '@ngrx/store' but never used
WARNING: 'MenuItem' is imported from external module 'primeng/api' but never used
WARNING: 'ControlValueAccessor', 'ValidationErrors' and 'Validator' are imported from external module '@angular/forms' but never used`

**Comment by maxisam** [comment]
The workaround is simply put OnInit etc in a separate import statement.

https://github.com/ng-packagr/ng-packagr/issues/1543#issuecomment-593873874

**Comment by alxhub** [comment]
@alan-agius4 I don't think it's feasible for `ngc` to remove these imports, unfortunately. `ngc` has zero knowledge of whether imports are consumed or under what circumstances. That information is internal to TypeScript and not exposed to us. Adding the logic to extract it for ourselves would be expensive both in terms of complexity and performance.

The much more practical answer is to not rely on `emitDecoratorMetadata`, which Ivy in AOT mode does not.

**Comment by alan-agius4** [comment]
Agreed and in the CLI we also have a transformer to elide unused imports.

The original issue is caused because of a TS issue https://github.com/Microsoft/TypeScript/issues/17552
