### ISSUE TITLE
Changes made on component before navigating away from it aren't rendered when using animations

### ISSUE THREAD

**Issue by JohnKis** [angular/angular#21284]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Changes made on component before navigating away from it aren't rendered when using animations.  

## Expected behavior
All changes should be rendered before the component gets destroyed.

## Minimal reproduction of the problem with instructions
[http://plnkr.co/edit/WnM21eMRRpTczpYuGIDf?p=preview](http://plnkr.co/edit/WnM21eMRRpTczpYuGIDf?p=preview)

Notice that in HomeComponent the modalVisible property (that shows/hides the modal) is set to false before navigating away, however the modal remains visible during the leave animation of the component.

## What is the motivation / use case for changing the behavior?
Being able hide a popup/modal before navigation.

## Environment

<pre><code>
Angular version: 5.1.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.3.0
- Platform:  Mac

Others:

</code></pre>

**Comment by matsko** [comment]
So this behaves as expected.

Because a leave operation will not remove the children (only the container), the  child contents will hang around until the animation is done. But during the animation you can query for the items you wish to hide and style them as hidden:
http://plnkr.co/edit/TrCtL6TQEb51MIr3Bq0n?p=preview
