### ISSUE TITLE
Bug(input type=range) should be displayed correctly regardless of the attributes order

### ISSUE THREAD

**Issue by yuvalbl** [angular/angular#21283]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
input with type=range display wrong value when:
1. step is decimal
2. value attribute placed before step attribute 
3. value and step provided by variables

## Expected behavior
input with type=range  should be displayed correctly regardless of the attributes order

## Minimal reproduction of the problem with instructions
see image attachment and my plunk
http://embed.plnkr.co/nNHocaMT5HXdQ1DzuV4d/
![image](https://user-images.githubusercontent.com/11487010/34521378-237b0e56-f096-11e7-81e3-a73cda7f5b6f.png)

## Environment

<pre><code>
Angular version: 5.1.2, also in 5.2.0-beta.1

Browser:
- [x] Chrome (desktop) version 63.0.3239.84
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by pkozlowski-opensource** [comment]
Here is an updated and simplified reproduce scenario: https://stackblitz.com/edit/angular-wtewer

**Comment by pkozlowski-opensource** [comment]
I can reproduce the same issue in pure JS script, without any Angular: 
https://stackblitz.com/edit/js-3iajmk

The interesting bit is that all browsers I could test with (Chrome, FFox, Safari) exhibit the same behaviour so there must be something "interesting" going on here.

In any case this is not Angular specific so I'm going to close it here. If anyone has cycles to dig into those browsers quirk I would love to learn what is going on!
