### ISSUE TITLE
Resolver fails silently if a variable is used as the resolver property

### ISSUE THREAD

**Issue by JA-AmbosImmo** [angular/angular#21286]
### Versions
```

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.3
Node: 6.10.2
OS: darwin x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.2
@angular/cli: 1.6.3
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.0.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.6.2
webpack: 3.10.0
```

### Repro steps

* Use the following example app: https://github.com/darrenmothersele/angular5-resolve-data/releases/tag/v1.2
* In "contacts-routing.module.ts" use the following code: 

```
export enum UserListResolverProperties {
    Users = 'users'
}

const _userListResolver = {};
_userListResolver[UserListResolverProperties.Users] = UserListResolver;

export const routes: Routes = [
    {
        path: '',
        component: ContactListComponent,
        resolve: _userListResolver
    }
];
```
* Execute command ng server --prod
* Open http://localhost:4200

### Observed behavior
No contacts are shown.
In dev mode this works perfectly fine. Running the app in production mode (ng build --aot -prod) the resolver fails silently. No error is thrown and no request was being made.

### Desired behavior

I expected the resolver to work and make a request in prod mode.
I want to be able to use a variable as propertyname for the resolver.

### Mention any other details that might be useful (optional)
I tracked the error down after replacing 
```
resolve: _propertyObjectsResolver
```
with 
```
resolve: {
    propertyObjects: PropertyObjectsResolver
}
```
Then it works fine.

**Comment by chuckjaz** [comment]
The code 

```ts
export enum UserListResolverProperties {
    Users = 'users'
}

const _userListResolver = {};
_userListResolver[UserListResolverProperties.Users] = UserListResolver;

export const routes: Routes = [
    {
        path: '',
        component: ContactListComponent,
        resolve: _userListResolver
    }
];
```

is treated identically to:

```ts
export const routes: Routes = [
    {
        path: '',
        component: ContactListComponent,
        resolve: {}
    }
];
```

during AOT because the compiler tries to determine the value of `Routes` statically and disregards any code that might modify the values that are referenced such as `_userListResolver[UserListResolverProperties.Users] = UserListResolver;`.

There are several work-arounds for this some of which you have in the working version, that is use variable initializers instead of assignment statements.

The failure is silent because there is no error and the compiler doesn't recognize what is considered dynamic modification of the metadata.
