### ISSUE TITLE
date pipe - longDate not working in zh locales

### ISSUE THREAD

**Issue by tonny008** [angular/angular#21282]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

date = Wed Jan 03 2018 20:21:42 GMT+0800 (CST)
``` {{date | date: "longDate"}}```
outputs `longD下午te`
## Expected behavior

output `2018年1月3日` or 2018年01月03日` or `2018年一月3日` or `2018年一月03日` 

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-datepipe-zh

## Environment

<pre><code>
Angular version: >5.0.0

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
@ocombe It's a general bug for named format retrieval, in [data-extracting process](https://github.com/angular/angular/blob/0f5c70d563b6943623a5940036a52fe077ad3fac/tools/gulp-tasks/cldr/extract.js#L291-L296), there's a `removeDuplicates` function used to get rid of extra bytes, but **there're [no corresponding fallback logic](https://github.com/angular/angular/blob/2e7e935b028784efdced34104964dad74b455fbf/packages/common/src/i18n/format_date.ts#L83-L146) for reusing removed formats at runtime**.

In this case, `zh` locale [provide same formats](https://github.com/unicode-cldr/cldr-dates-full/blob/3eb9156b699ee903805411c37a63afc7f3594349/main/zh/ca-generic.json#L312-L313) for `mediumDate` & `longDate`, so the latter is stripped. And then no `longDate` named format found at runtime, making it being regarded as a normal format.

**Comment by ocombe** [comment]
Oh good catch @trotyl, we have fallback logic for all data except those formats. I'll fix it

**Comment by trotyl** [comment]
@ocombe I just raise a PR for it, it would be fine if you have better solution.
