### ISSUE TITLE
`fullTemplateTypeCheck` not honouring `skipLibCheck`

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#21287]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I am not sure that if this is by design, bug or missing feature.

But let me explain, I am building a library and turned on `fullTemplateTypeCheck`, have `strictNullChecks` and also `skipLibCheck`.

So my `tsconfig` looks something like if you remove the other properties;

```json
{
  "compilerOptions":{
    "strictNullChecks": true,
    "skipLibCheck": true
  },
  "angularCompilerOptions": {
    "strictMetadataEmit": true,
    "skipTemplateCodegen": true,
    "fullTemplateTypeCheck": true
  }
}
```

The problem I am encountering with `fullTemplateTypeCheck` is that when one of my external dependencies have issues with their template, this would cause compilation errors and unless I turn off `fullTemplateTypeCheck`, I am unable to compile my library.

## Expected behavior
`skipLibCheck` is honoured and only type checks on my library are performed, or a new flag is added like `skipLibTemplateTypeCheck` as `skipLibCheck` is used to skip type checking of declaration files.

## What is the motivation / use case for changing the behavior?
I think if I have `skipLibCheck` set to `true`, `fullTemplateTypeCheck` should only check the code within my library and other external dependencies. As like this, I will be unable to validate my templates until the other 3rd library solves the issue.

## Environment

<pre><code>
Angular version: 5.1.2
</code></pre>

**Comment by chuckjaz** [comment]
These options are unrelated.

**Comment by alan-agius4** [comment]
Maybe add another flag as I suggested above in that case, as mentioned indeed skipLibCheck is used to skip type checking?

> Or a new flag is added like skipLibTemplateTypeCheck as skipLibCheck is used to skip type checking of declaration files.

**Comment by chuckjaz** [comment]
Sure. Can you create another issue requesting that feature?
