### ISSUE TITLE
http post => Multiple post requests are used in the method

### ISSUE THREAD

**Issue by leixus** [angular/angular#21298]
![image](https://user-images.githubusercontent.com/24884532/34548217-c78a8fee-f13b-11e7-99e4-f15d24daf7fc.png)

This approach caused the data to chaos
这种情况应该怎么处理？
help me!

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by kara** [comment]
Yeah, this doesn't look like an issue or a feature request, so I'm going to close this.

**Comment by leixus** [comment]
Okay, you have the final say
