### ISSUE TITLE
[Service Worker] Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by LFeh** [angular/angular#21292]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When load `"@angular/service-worker": "^5.1.0"` on old Chrome version (in this case, 40.0.2214.91), happens an error.

## Expected behavior
Service Worker should work in this Chrome version.

## Minimal reproduction of the problem with instructions
![screen shot 2018-01-03 at 7 25 39 pm](https://user-images.githubusercontent.com/3603793/34540883-58c0aae0-f0bd-11e7-8c9b-02e22af9234b.png)

## What is the motivation / use case for changing the behavior?
I've been need use `bowser` to check what is Chrome version to prevent it. This a bad practice.

## Environment

<pre><code>
Angular version: 5.1.0

Browser:
- [x] Chrome (desktop) version 40.0.2214.91
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.10.2
- Platform: Mac, Linux, Windows
 
</code></pre>

**Comment by matpag** [comment]
Based on this link: https://jakearchibald.github.io/isserviceworkerready/ service worker on Chrome has been introduced in v40 but "fully" completed only in v49. Maybe the actual implementation is using something which was not available in v40 but introduced later (just thinking). Have you tried with v49 to see if the same error is provided?

**Comment by LFeh** [comment]
The question is not the `service worker`,  I don't need that `service worker` works on old Chrome.

My problem is because the app broken on this version if I use `@angular/service-worker` and some users of my app use the old Chrome.

If I remove the `@angular/service-worker` and add a manual implementation of service worker, the app works.

**Comment by gkalpak** [comment]
@LFeh, can you provide a non-minified stacktrace (and also try with the latest `@angular/service-worker` version).

**Comment by gkalpak** [comment]
Closing due to lack of response. Possibly duplicate of #20756 (based on https://github.com/angular/angular/issues/20756#issuecomment-358076579).
