### ISSUE TITLE
Angular ng build prerendered routes like angular universal for static serving #FeatureRequest

### ISSUE THREAD

**Issue by manuelfink** [angular/angular#21307]
## I'm submitting a Feature Request
Is it possible to build an angular app with several prerendered routes? I'm thinking of something similar to angular universal just during the build process for predefined routes but for static serving.

## Current behavior
seem not to be available as build option. At least I could not find it.

## Expected behavior

- add routes to prerender while building in .angular-cli.json
- on ng build create prerendered index.html files in dist folder for defined routes

For example:

```
./dist/index.html << this is default!
// Additional build prerendered index.html files for specified routes
./dist/routeA/index.html
./dist/routeB/index.html
./dist/routeC/customRouteParam/index.html
```

### Why static prerendering of Angular?
* Allow static serving avoiding extra complexity of server-side rendering
* Keep advantages of universal app and serverside rendering
* Improving load time
* Support for Open Graph Tags (OG Tags)
* ...

I posted the [same question on stackoverflow](https://stackoverflow.com/questions/48097079/angular-ng-build-prerendered-routes-like-angular-universal-for-static-serving-w), but looking through the build this seems not to be possible as of now. Anyone else thinks this is useful?

**Comment by kara** [comment]
This looks like it should be filed in the angular-cli repo, given that these would be added to ng build and CLI config.

**Comment by manuelfink** [comment]
If anyone wants to achieve the same, the [Angular Universal Starter Pack](https://github.com/angular/universal-starter) already implements an sample for prerendered routes. 

Take a look at:

- [prerender.js](https://github.com/angular/universal-starter/blob/master/prerender.ts) for rendering
- [static.paths.ts](https://github.com/angular/universal-starter/blob/master/static.paths.ts) containing the routes to render.
