### ISSUE TITLE
Documentation: Service Worker on the browsers that do not support it

### ISSUE THREAD

**Issue by smnbbrv** [angular/angular#21304]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Originated at https://stackoverflow.com/questions/48045748/angular-service-worker-on-the-browsers-that-do-not-support-it . The text is partly copied

Can I Use shows quite a poor support of the feature in relatively important browsers. I can survive the not working IE11, but Safari (especially mobile) is a thing I wouldn't like to keep unsupported.

So, my intention would be to know how the angular service worker module, services, events those services provide etc will behave on the browser that does not support service workers.

Will all those just silently fail? Will the events be triggered anyhow? Will the ngsw-worker.js be requested? Will something be cached in IndexedDB instead of service worker?

The solution looks cool, however I cannot answer the question should I use it? until I know the answers on the questions above.

## Expected behavior

The documentation should clearly define what is going on when the Service Worker is not supported by the browser.

## What is the motivation / use case for changing the behavior?

E.g. I want to implement the auto-refresh when the new app version is deployed => I need an answer to the question whether the service worker manifest will be downloaded on **all the browsers** and the updates will be pushed by `SwUpdate` or I need to implement it twice. This is actually pushing me in the direction of Service Worker in case it does and pushes away if it does not.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kapunahelewong** [comment]
@chembu and @jenniferfell fyi ^^

**Comment by alxhub** [comment]
The Angular SW only works in browsers which support service workers. This includes all of the application integration (e.g. the `SwUpdate` service).

If SWs are unsupported in the current browser.

* The SW script and `ngsw.json` will never be downloaded.
* Active attempts to interact with the SW, such as calling `SwUpdate.checkForUpdate()` will return rejected promises.
* Passive attempts to listen to SW `Observable`s such as `SwUpdate.available` will simply never trigger - the `Observable`s will never emit.

**Comment by smnbbrv** [comment]
Thanks for clarifying!

**Comment by sonnyk22** [comment]
Great input from alxhub.  The question still remains of how to can configure our PWA app to totally ignore the Service Worker caching on the older browsers such as IE11, but load SW on the newer ones?  The intent is for the PWA application to keep functioning as normal in IE.     Is there a way to do this in our code?

**Comment by gkalpak** [comment]
As @alxhub mentioned above, you shouldn't need to do anything special in your code.

**Comment by jenniferfell** [comment]
Reopening until the original request is resolved:
* Doc the behavior of browser that does not support sw has an open PR. 

Also, it sounds like we need to mention this: If the app is implemented to use service workers, but the user is accessing the app via a browser that does not support service workers, then the browser  simply ignores the service worker caching. Browsers that support service workers still load the service worker as expected.

**Comment by jenniferfell** [comment]
@gkalpak : See below. Is this a more complete summary?

@chembu : A sketch of a solution that combines the thread above and is more clear that this is about the different users' browsers. 

BEGIN SKETCH: 
To benefit from the Angular service worker, your app must be running in a web browser that supports service workers in general. Angular has been tested with the latest versions of Chrome and Firefox. To learn about other browsers that support service workers, see the Can I Use page.

If a user is accessing your app via a browser that does not support service workers, then the browser ignores the service worker caching. Browsers that support service workers still load the service worker as expected.

If the browser does not support service workers, then the Angular service worker is not created:
* The service worker script and `ngsw.json` are not downloaded.
* Active attempts to interact with the service worker, such as calling SwUpdate.checkForUpdate(), return rejected promises.
* The service worker observable properties such as SwUpdate.available are not triggered.

**Comment by smnbbrv** [comment]
Actually I am observing a slightly opposite thing in my sentry

![image](https://user-images.githubusercontent.com/13453858/48602148-739cce80-e972-11e8-9746-69cb0a092386.png)

The error is thrown.

I'm not sure how it affects the workflow, but seeing this error in error log is really annoying as long as I can't really fix it

**Comment by smnbbrv** [comment]
This happens in main.js, so I assume it happens when one subscribes to SwUpdate

**Comment by gkalpak** [comment]
This error means that the `checkForUpdate()` call returned a rejected promise. As @alxhub mentioned above, this is expected:

> Active attempts to interact with the SW, such as calling SwUpdate.checkForUpdate() will return rejected promises.

If you want to avoid that, you can also check whether SW is enabled, via `this.swupdate.isEnabled`.

**Comment by jbogarthyde** [comment]
Resolved by addition of section to SW intro: https://angular.io/guide/service-worker-intro#browser-support
