### ISSUE TITLE
Double comma in NgModule declarations

### ISSUE THREAD

**Issue by hawkwind2** [angular/angular#21302]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When double comma is introduced in NgModule declarations web browser gives an unclear error message: Error: Unexpected value 'undefined' declared by the module 'AppModule'' 

## Expected behavior

Consider giving a message with more specific details.

## Minimal reproduction of the problem with instructions

Add a comma in declaration for AppModule without e.g:
HomeComponent,
,OtherComponent

## What is the motivation / use case for changing the behavior?

Faster resolving of issue / errors

## Environment

<pre><code>
Angular version: 5.0.3

Browser:
- [x ] Chrome (desktop) version 63
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version 58
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@hawkwind2 ... do you use any linter? When using `tslint` (+ recommended `angular-tslint-rules`) then `no-sparse-arrays` rule will show a warning for you in that case.

**Comment by rjoydip** [comment]
@hawkwind2 declerations is a array of [`Type`](https://github.com/angular/angular/blob/master/packages/core/src/type.ts)  or array of `any` `declarations?: Array<Type<any> | any[]>;` and [`Type`](https://github.com/angular/angular/blob/master/packages/core/src/type.ts) is ***`Component` class, which in JavaScript is be represented by the `Component` constructor function.***

**Comment by frederikprijck** [comment]
> Consider giving a message with more specific details.

When you have an array like this:

```
[
SomeComponent,
,SomeOtherComponent
]
```

You are creating an array of 3 elements: SomeComponent, `undefined` and `SomeOtherComponent`.
I'm not sure there's more that can be done when it comes to logging an error, as the error message is perfectly valid (it's saying a value of undefined is `declared` in the module, which is what you're doing and it's invalid).

**Comment by pkozlowski-opensource** [comment]
> I'm not sure there's more that can be done when it comes to logging an error, as the error message is perfectly valid

I agree that the error message is spot on. As others mentioned linters might help catching this error even earlier.

Closing it here as I don't think we can do much better on the framework side.
