### ISSUE TITLE
UrlMatcher typescript strict mode wrong defined

### ISSUE THREAD

**Issue by Lexanius** [angular/angular#21301]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

currently `UrlMatcher` is defined:
`export declare type UrlMatcher = (segments: UrlSegment[], group: UrlSegmentGroup, route: Route) => UrlMatchResult;`
but for the typescript strict mode it must: 
`export declare type UrlMatcher = (segments: UrlSegment[], group: UrlSegmentGroup, route: Route) => UrlMatchResult | null;`

like the example show (not typed):
 ```
 * function htmlFiles(url: UrlSegment[]) {
 *  return url.length === 1 && url[0].path.endsWith('.html') ? ({consumed: url}) : null;
 * }
 *
 * const routes = [{ matcher: htmlFiles, component: HtmlCmp }];
 ```

## Expected behavior
`UrlMatcher` should define so:
`export declare type UrlMatcher = (segments: UrlSegment[], group: UrlSegmentGroup, route: Route) => UrlMatchResult | null | undefined;`

## Minimal reproduction of the problem with instructions
```
export function MyAwesomeMatcher ( url: UrlSegment[] ): UrlMatchResult | null {
  if (url.length === 0) {
    return null;
  }
  const reg = /^(awesome-path)$/;
  const param = url[ 0 ].toString();
   if (param.match( reg )) {
    // myValue: "awesome-path"
    return ({ consumed: url, posParams: { myValue: url[ 0 ] } });
  }
  return null;
}
// define application routes.
const routes: Routes = [
  { path: '', component: HomeComponent, pathMatch: 'full' },
  // { path: 'awesome-path', component: MyAwesomeComponent },
  { matcher: MyAwesomeMatcher, component: MyAwesomeComponent }
  ...
];
```

## Environment
Angular version: 5.1.1

For Tooling issues:
- Typescript 2.4.2

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
