### ISSUE TITLE
Travis builds failing because of: Cannot add PPA: 'ppa:ubuntu-toolchain-r/test'.

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21311]
```
Adding APT Sources (BETA)
$ export DEBIAN_FRONTEND=noninteractive
262.16s$ sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
Cannot add PPA: 'ppa:ubuntu-toolchain-r/test'.
Please check that the PPA name or format is correct.
The command "sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"" failed and exited with 1 during .
```

~Example job: https://travis-ci.org/angular/angular/jobs/325037420~ (logs lost after rerunning the job)

It looks like a travis-ci issue that we didn't cause because the problem occurs during the initialization of the container before any of our code runs.

http://status.travis-ci.com doesn't report any issues. I'll contact the Travis support.

**Comment by IgorMinar** [comment]
hmm.. the problem went away before I could even contact the support. The same job now passes (after I rerun it): https://travis-ci.org/angular/angular/jobs/325037420

**Comment by IgorMinar** [comment]
I just saw this issue twice in various jobs this evening. Reopening for further investigation.

**Comment by wardbell** [comment]
I got it here within the last day: https://travis-ci.org/angular/angular/jobs/326754035

**Comment by IgorMinar** [comment]
Travis has had a few bad days. I think the problem is resolved now, but let's keep monitoring this for a few more days.

**Comment by IgorMinar** [comment]
I believe this has been resolved.
