### ISSUE TITLE
google bot indexes 404 pages on angular.io

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21317]
https://www.google.com/search?q=PAGE+NOT+FOUND+site%3Aangular.io

<img width="852" alt="screen shot 2018-01-04 at 1 21 34 pm" src="https://user-images.githubusercontent.com/216296/34584866-4195351c-f152-11e7-8aa5-32017c4d0b0e.png">

Most of these pages should have a redirect setup to a correct page or should return HTTP 404 to signal that the page doesn't exist (dgeni knows about all the urls, so we can generate firebase config that will do this for us).

**Comment by devoto13** [comment]
Can you also look into how to fix search queries for particular Angular API? I.e. trying to search for `Renderer2` in Google returns bunch of invalid links with PAGE NOT FOUND titles. See https://www.google.se/search?q=Renderer2+site%3Aangular.io. And I don't see a correct link among results.

**Comment by IgorMinar** [comment]
@devoto13 that page renders correctly. I requested re-indexing of that page. Let's see if that helps...

<img width="1161" alt="screen shot 2018-01-08 at 8 07 27 pm" src="https://user-images.githubusercontent.com/216296/34704677-a41d1f78-f4af-11e7-8db3-3a488a053a17.png">

**Comment by IgorMinar** [comment]
I just realized why the 404 pages are such attractive content for the bot - thanks to displaying the search hints in order to find the content the reader was looking for, the 404 page is full of keywords and links that the crawlers then indexes and oddly finds very valuable.

**Comment by IgorMinar** [comment]
I'm not aware of a way to use JavaScript or DOM to signal to the bot that a 404 page is just that - a 404 page. But there might be a hackish solution that might work, then we could do a full page reload to a special URL that would then hit the http server which would serve the 404 page with the HTTP status of 404.

This is how it would work:

- user navigates to a page that should be 404
- the aio doc viewer realizes this and issues `window.location.reload()` command to cause a full page reload
- the request hits the service worker (if sw is supported and installed) and delegates the request to the (firebase hosting) server
- the server would then have to be configured to understand which paths are legal and issue an HTTP 404 for those that are not
- the page would come back to the browser with http 404, the browser would still bootstrap the page and render it, displaying the PAGE NOT FOUND content to the human, but crawler would honer the 404 http status and kick the page out of the index

This is quite nasty, but I'm not sure if there is a prettier way to do it.

It also makes me realize that we are lucky in that we know about all the legal URL paths ahead of time. If we had any dynamic url segments in our application (e.g. `/users/:username`), we'd be unable to use this trick without consulting the data store which would prevent us from using static http server.

**Comment by IgorMinar** [comment]
This is a relevant support page that uses term "Soft 404" for our kind of handling of the invalid urls: https://support.google.com/webmasters/answer/2409443?ctx=MCE&ctx=S4&hl=en but the document doesn't explain what client-side/single-page apps should do instead since they can't easily issue an HTTP 404 code (except for the hack described above).

**Comment by devoto13** [comment]
@IgorMinar Hopefully re-index will help. Similar issues are present for some other API doc pages as well. Couple of examples (but probably there are more):

- `NgForOf` - [results](https://www.dropbox.com/s/ms5m5tcelguk9kt/Screenshot%202018-01-09%2010.24.05.png?dl=0) (expected https://angular.io/api/common/NgForOf to show up)
- `ElementRef` - [results](https://www.dropbox.com/s/bv8jc68b2a513q0/Screenshot%202018-01-09%2010.33.29.png?dl=0) (expected https://angular.io/api/core/ElementRef to show up)
- `ViewChild` - [results](https://www.dropbox.com/s/wq7oia66pkec2gq/Screenshot%202018-01-09%2010.34.33.png?dl=0) (expected https://angular.io/api/core/ViewChild to show up)

However other queries work correctly, e.g:
- `RouterLink` - [results](https://www.dropbox.com/s/9d9hazho36s2ajy/Screenshot%202018-01-09%2010.31.22.png?dl=0)
- `CanActivate` - [results](https://www.dropbox.com/s/h9rb31bar65d3mr/Screenshot%202018-01-09%2010.32.06.png?dl=0)

**Comment by StephenFluin** [comment]
@IgorMinar It feels like we could simplify the above hack and when we hit a route without data, just forward to a known-URL 404 page (eg https://angular.io/404) and serve up the 404 status with a firebase function. I'm probably oversimplifying the problem.

**Comment by IgorMinar** [comment]
I was thinking about a single url on the server that always returns 404 but I'm not sure how will the crawler understand and respond to the sequence of:

1. nagivate to `/wrong/url`
2. get client side redirect to `/404?originalUrl=${encodeURIComponent(/wrong/url)}`
3. get a 404 status from the server

Will the 404 status be associated with the `/wrong/url` or with the `/404`? I don't know.

(we need to preserve the originalUrl so that we can render a useful 404 page for the non-bot users on the client side)

**Comment by IgorMinar** [comment]
@StephenFluin if you could confirm that the 404 status will get properly associated with the original url then that would definitely simplify the implementation and it would make supporting dynamic usecases much simpler as well.

**Comment by IgorMinar** [comment]
I was advised to use [`noindex` metatag](https://support.google.com/webmasters/answer/93710?hl=en) to indicate soft-404 status which will prevent crawlers from crawling the content of the page.

The tag must be in the `head` of the document, but (and I didn't know this) can be added to the document via JavaScript.

So let's try this solution first before we do crazy redirections.

We have two options:

1. The doc viewer adds the meta tag via [`Meta`](https://angular.io/api/platform-browser/Meta) service when rendering 404 and removes it on other pages
2. We put the noindex meta tag into the host `index.html` so that it's the default and doc viewer removes it for all documents except for 404 upon initial rendering. After that it behaves as 1. toggling the noindex metatag as needed.

The second option has an added benefit of also preventing urls that throw in the crawler from being indexed because the meta tag is set statically and removed dynamically, so it will be there until we successfully render the document.

I do realize that we currently don't need to care about toggling the meta tag after the initial navigation because the crawlers today always do full page reload for each url, but who knows how long it will stay this way, so a more futureproof solution would be to toggle the tag for each rendering of a document in the doc viewer.

**Comment by petebacondarwin** [comment]
I have created a PR using the strategy [suggested by Igor](https://github.com/angular/angular/issues/21317#issuecomment-357307182) above. See https://github.com/angular/angular/pull/21665

But, I have been unable to verify whether this approach works with the bot via a test project at https://ng-seo-tester.firebaseapp.com/ since it doesn't appear to be rendered correctly by the bot and doesn't seem to be indexed at all. The code for this test project is at https://github.com/petebacondarwin/ng-seo-tester

**Comment by IgorMinar** [comment]
This is in production now. Let's let the crawler do it's job over the weekend and then revisit the stats and search results...

**Comment by IgorMinar** [comment]
I'll keep the issue open until we confirm that the fix worked.

**Comment by IgorMinar** [comment]
I think that in order to expedite this, we should also implement a fix for #21377 and #21684.

**Comment by petebacondarwin** [comment]
@IgorMinar is there some way to clean the Google index cache for the site? Going to https://www.google.com/search?q=PAGE+NOT+FOUND+site%3Aangular.io is still showing lots of soft 404s but these are cached from before we fixed this - some from before Xmas!

**Comment by IgorMinar** [comment]
I'll check tonight.

**Comment by IgorMinar** [comment]
I looked into this and it seems that by setting up the redirects and submitting the sitemap, we should trigger enough crawler activity to get all the 404 links removed. The redirects will also fix the navigation from old content outside of angular.io that uses the old links + it will give us extra link "juice" so it's totally worth doing.

In the meantime I want ahead and used a feature within the search console to hide the old ts and dart urls:
![screen shot 2018-01-21 at 8 14 34 pm](https://user-images.githubusercontent.com/216296/35205153-04241844-fee8-11e7-93f5-5e3af0358df9.png)

**Comment by petebacondarwin** [comment]
@IgorMinar can we close this now that the firebase redirects PR has landed?

**Comment by IgorMinar** [comment]
The issue still exists. Let's wait until the pages disappear from the search results.

**Comment by IgorMinar** [comment]
The redirects seem to be working. We are down to ~500 "not found" results:

<img width="899" alt="screen shot 2018-02-08 at 9 12 54 am" src="https://user-images.githubusercontent.com/216296/35987369-539aeaee-0cb0-11e8-91ec-a75096a1cfab.png">

**Comment by petebacondarwin** [comment]
The redirects never landed on stable 😱 I am making up a PR now.

**Comment by IgorMinar** [comment]
all but 10 links are gone: https://www.google.com/search?q=%22PAGE+NOT+FOUND%22+site%3Aangular.io

<img width="784" alt="screen shot 2018-02-15 at 12 25 01 am" src="https://user-images.githubusercontent.com/216296/36246909-bd0cf1c6-11e6-11e8-88d1-66cb0efa15e3.png">

I'm going to close this. Thanks @petebacondarwin !!!
