### ISSUE TITLE
Router Malfunction

### ISSUE THREAD

**Issue by Smiller193** [angular/angular#21315]
So  I am having two problems specifically with routers. I have an appComponent.html like so

    <div id = "fullPage">
    <app-header></app-header>
    <app-login-form></app-login-form>
    <app-footer></app-footer>
    </div>

When I click the login button on the console I can see that the user is authenticated however it doesn't go to the dashboard.

My login component contains this function which handles the login of a user and at the end it should send a user to the dashboard

      loginUser(e){
        e.preventDefault();
      console.log(e.value);
      var email = e.target.elements[0].value;
      var password = e.target.elements[1].value;
      console.log(email,password);
      this.af.auth.signInWithEmailAndPassword(email,password)
      .then((success) => {
        console.log(success)
        this.authenticated = true;
        console.log("attempting to nav");
        this.router.navigate(['/dashboard']);
        console.log("nav worked");
      }).catch((err) => {
        this.error= err;
      })
      }//end of login user 

However, I click login it logs me in and just stays there and doesn't move.  My routes are properly defined 

    const appRoutes:Routes = [
      {
        path: 'login',
        component: LoginFormComponent
      },{
        path: 'dashboard',
        component: DashboardComponent
      },{
        path: 'events',
        component: EventsComponent
      },{
        path: 'add-event',
        component: AddEventComponent
      },{
        path: 'edit-event/:id',
        component: EditEventComponent
      },{
        path: 'delete-event/:id',
        component: DeleteEventComponent
      },{
        path: 'event-details',
        component: EventDetailsComponent
      }
    ] 

My loginComponent.html reacts properly to the click

    <div class="form">
    <span class="error" *ngIf="error">{{ error }}</span>
    <form  (submit) = "loginUser($event)">
    <input type="text" placeholder="Email Address"/>
    <input type="password" placeholder="Password"/>
    <button type = "submit">login</button>
    </form>
    </div>

However, nothing happens am I doing anything wrong?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Smiller193** [comment]
oh sorry I apologize

**Comment by kara** [comment]
Yeah, this looks like a support question, so it has to be closed. You might also try the Angular gitter as a resource to help track down the problem.
