### ISSUE TITLE
v2.angular.io is being indexed by google

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21312]
Example query: https://www.google.com/search?q=Angular+site%3Av2.angular.io

This is likely because the robots.txt file is missing on v2 site: https://v2.angular.io/robots.txt

note: this issue was discovered as part of investigation for #21272

**Comment by IgorMinar** [comment]
I'm not sure what's the best way to fix this. If we could, I'd prefer pulling down the currently deployed build of the v2 site and adding the robots file. I would like to avoid trying to create a new build with the old stack because the dependencies were not pinned at that time so rebuilding will be tough.

**Comment by petebacondarwin** [comment]
I think this is now resolved? @IgorMinar ?

**Comment by petebacondarwin** [comment]
This is still an issue (and for v4). It looks like the solution is https://github.com/angular/angular/issues/21313#issuecomment-357308410
