### ISSUE TITLE
next.angular.io is being indexed by google in spite of robots.txt disallowing it

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21313]
example query: https://www.google.com/search?q=language+service+site%3Aangular.io

current result:

<img width="841" alt="screen shot 2018-01-04 at 10 21 30 am" src="https://user-images.githubusercontent.com/216296/34578236-1176f2e4-f139-11e7-9660-e2c84f340049.png">

note: this issue was discovered as part of the investigation into #21272

**Comment by IgorMinar** [comment]
it seems that only the root url next.angular.io is being indexed. nothing else is: https://www.google.com/search?q=angular+site%3Anext.angular.io

Maybe this is the expected behavior?

**Comment by gkalpak** [comment]
You mean remove the `noindex` metatag on `angular.io`, but leave it on `next.angular.io`?

**Comment by IgorMinar** [comment]
@gkalpak yes

**Comment by petebacondarwin** [comment]
This does not yet appear resolved, although the search results for next.angular.io now has the Angular Elements page instead of the Language Service page.

**Comment by IgorMinar** [comment]
resolved - no longer a problem! closing!
