### ISSUE TITLE
several angular.io redirects not working

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21318]
we have redirect rules setup but some of them don't seem to be having any effect. broken link examples:

https://angular.io/guide/service-worker-getstart
https://angular.io/guide/service-worker-comm
https://angular.io/guide/service-worker-configref
https://angular.io/guide/metadata

The config for these is there and is present on the 5.1.x branch:
https://github.com/angular/angular/blob/b9d8ac5b2d3fbc38edeb901fc5f6d62cb734dee7/aio/firebase.json#L46-L48

**Comment by IgorMinar** [comment]
we should verify all the redirects we have setup and ensure that they still work

**Comment by IgorMinar** [comment]
// @StephenFluin

**Comment by gkalpak** [comment]
Could it be that the rules were not deployed? I see them working now 😕 
Are they still broken for you?

**Comment by IgorMinar** [comment]
@gkalpak I still see them broken:

<img width="1509" alt="screen shot 2018-01-08 at 9 04 31 am" src="https://user-images.githubusercontent.com/216296/34682187-ffc82b40-f452-11e7-9c0f-871713c9c851.png">

----

Could it be that the service worker is interfering with the redirects?!?!?

**Comment by gkalpak** [comment]
You are right, it's the ServiceWorker. We need to explicitly exclude them from SW-routing [here][1] 😞 

[1]: https://github.com/angular/angular/blob/fa03ae14b0be19c2cb9d653b2b1d3cfa0ae25117/aio/ngsw-manifest.json#L22

**Comment by IgorMinar** [comment]
Let's not do this in master. Let's instead fix this in the sw upgrade PR.

**Comment by gkalpak** [comment]
So, should I close #21416, or target it to the patch branch only?
