### ISSUE TITLE
I have defined a route 'index' as {path: 'index', redirectTo: 'summary'}, which is getting redirected to SummaryComponent's route 'summary'. On serving the locally gives no error, and I am able to redirect to both index and summary without any issue. However, when I create a build for this project and try serving the build index.html inside distribution folder, the route for index shows an error response"Error response Error code 404.  Message: File not found.  Error code explanation: 404 = Nothing matches the given URI.". Could not get any clue regarding this. I need to integrate this module with flask backend. Please provide your inputs to this.

### ISSUE THREAD

**Issue by sshreya08** [angular/angular#21321]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
