### ISSUE TITLE
ActivatedRoute.queryParams throws execption when using % in the URL

### ISSUE THREAD

**Issue by shmaram** [angular/angular#21328]
## I'm submitting..

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Using ActivatedRoute.queryParams with url the includes % it throws an exception that can't be catched anywhere. 

## Expected behavior
To be able to catch this kind of error 

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
go to : https://embed.plnkr.co/tUMGOtW39iMDYKHcv1hm/
then add layout=!@#$%^&*() so that the new URL will be 
https://embed.plnkr.co/tUMGOtW39iMDYKHcv1hm/?layout=!@#$%^&*()

Error found : 
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Ye (vendor.6b9be0480d04ab9c9c6c.js:6)
    at tn.$$parse (vendor.6b9be0480d04ab9c9c6c.js:6)
    at tn.$$parseLinkUrl (vendor.6b9be0480d04ab9c9c6c.js:6)
    at an.$get (vendor.6b9be0480d04ab9c9c6c.js:6)
    at Object.a [as invoke] (vendor.6b9be0480d04ab9c9c6c.js:6)
    at vendor.6b9be0480d04ab9c9c6c.js:6
    at r (vendor.6b9be0480d04ab9c9c6c.js:6)
    at i (vendor.6b9be0480d04ab9c9c6c.js:6)
    at Object.a [as invoke] (vendor.6b9be0480d04ab9c9c6c.js:6)

## What is the motivation / use case for changing the behavior?

By fixing this issue developers can use % in the URL

## Environment

<pre><code>
Angular version: 4.0.0

Browser:
- [X ] Chrome (desktop) version 63.0.3239.132
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

<hr>

Internally we are using the native `decodeURIComponent` function, and it's this function that's throwing the error. Percents are illegal in URLs unless you're providing a URL encoding (such as `%20` for space).
