### ISSUE TITLE
Failing to build Angular from source on Windows

### ISSUE THREAD

**Issue by valera-rozuvan** [angular/angular#21327]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When trying to build Angular from source, the `build.sh` script fails with the error message:

```
$ sh build.sh
====== BUILDING: Version 5.2.0-rc.0-b5934fc58

===> build.sh build tools ==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==
====== (tools)COMPILING: $(npm bin)/tsc -p ./tools/tsconfig.json =====
<=== build.sh build tools <==<==<==<==<==<==<==<==<==<==<==<==<==<==<==<==<==<==<==<==<==<==<==<=


===> build.sh clean dist ==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>
<=== build.sh clean dist <==<==<==<==<==<==<==<==<==<==<==<==<==<==<==<==<==<==<==<==<==<==<==<==


===> build.sh copy e2e files ==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==
====== Copying files needed for e2e tests =====
====== Copying files needed for benchmarks =====
ln: failed to create symbolic link './polymer': No such file or directory
```

## Expected behavior
The `build.sh` script should pass, and Angular should successfully build.

## Minimal reproduction of the problem with instructions

I followed all the steps in the guide https://github.com/angular/angular/blob/master/docs/DEVELOPER.md .

## Environment

<pre><code>
Angular version: 5.2.0

For Tooling issues:
- Node version: 8.9.3  
- Platform:  Windows 7 Enterprise, 64bit

**Comment by pkozlowski-opensource** [comment]
Yeh, we don't have a great story for Windows... This issue is already tracked in #17894

**Comment by valera-rozuvan** [comment]
@pkozlowski-opensource So the Angular dev team works on Linux/MacOS to develop Angular?

**Comment by sarunint** [comment]
If you are using Windows 10, I recommend installing Ubuntu from the Microsoft Store and build Angular there.

**Comment by sheikalthaf** [comment]
@sarunint Hi,

I have installed ubuntu and try to run the build cmd and got error like this.
<pre><code>
./build.sh: line 2: $'\r': command not found
: invalid option nameet: pipefail
</code></pre>

any idea to resolve
