### ISSUE TITLE
Issue in routes rendering on serving through dist folder index.html

### ISSUE THREAD

**Issue by sshreya0808** [angular/angular#21322]
## I'm submitting a...
{path: '', redirectTo: 'summary', pathMatch: 'full'},
    {path: 'index', component: SummaryComponent},
    {path: 'summary', component: SummaryComponent},
    {path: 'reports', component: ReportsComponent},
    {path: 'configure', component: ConfigureComponent},
</code></pre>

## Current behavior

I have defined a route 'index' as {path: 'index', redirectTo: 'summary'}, which is getting redirected to SummaryComponent's route 'summary'. On serving the locally gives no error, and I am able to redirect to both index and summary without any issue. However, when I create a build for this project and try serving the build index.html inside distribution folder, the route for index shows an error response"Error response Error code 404. Message: File not found. Error code explanation: 404 = Nothing matches the given URI.". Could not get any clue regarding this. Could not get any clue regarding this. I need to integrate this module with flask back end. Please anyone please provide an input to this. 

## Expected behavior

render all components routes through distribution, as it is getting served correctly on serving the project locally developed

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
