### ISSUE TITLE
ActivatedRoute parent subscription not removed on component destroy

### ISSUE THREAD

**Issue by Dt-Sodium** [angular/angular#21323]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I ran into an issue the past few dates where subscriptions to an activatedRoute params would stack up when switching between sub-components from a parent component.

After some trials and errors, i found out that this issue was caused by subscribing to a parent route parameters. If i do this.route.params.subscribe(), the subscription is correctly deleted when the component is destroyed. If i do this.route.parent.parent.subscribe(), it is not deleted on component destruction and those subscriptions start stacking up.

Manually unsubscribing on component destroy fixes this issue, but i was wondering if this is the expected behavior when working with activatedRoute.

**Comment by Pashozator** [comment]
@Dt-Sodium  I guess you always want to manually unsubscribe subscription.

**Comment by Dt-Sodium** [comment]
While searching for a solution for my problem, i've read numerous times that you're not supposed to manually unsubscribe from route parameters. I couldn't find anything about route parent parameters tough.

**Comment by mlc-mlapis** [comment]
@Dt-Sodium ... auto unsubscribe is always supposed on actual `ActivatedRoute` but you are using `this.route.parent.parent.subscribe()` which is not a recommended way at all.

You should then:
* manually unsubscribe or which is recommended ...
* change the logic how a component receives emits from upper component levels

**Comment by Dt-Sodium** [comment]
I'm not saying that my architecture is ideal.
I have a route with a product ids as parameters that only renders a component with a navigation to different product editing pages and a router outlet to render the chosen component.
In those components, i need to retrieve the edited product, so i subscribe to the product id in the parent route. If someone has a suggestion to do it better i'll be happy to hear it.

I don't mind unsubscribing manually, i actually like it better this way. I just think it's confusing that destroying the component auto-unsubscribes for the actived route but not when using the parent.
I may be wrong, but to me it seems to me that the parent property of the activated route still belongs to the activated route instance, which is a private property of my component.

**Comment by mlc-mlapis** [comment]
@Dt-Sodium ... so it is something like a route `product/:id` ... and then `product/:id/edit`?

**Comment by Dt-Sodium** [comment]
Yes, that's it.
product/:id redirects to product/:id/edit.

I could have loaded my product in the first component and loaded the sub-components while passing the product, but i wan't my user to be able to access most functionnalities by url directly.

Maybe there's a better way to do this but it isn't that easy to find angular best-practices as there always seems to exist at least ten methods to achieve something.

**Comment by mlc-mlapis** [comment]
@Dt-Sodium ... ok, and how `<router-outlet>` is placed because it affects the basic fact ... is the component re-used or a new instance is created when re-routing from `product/10/edit` to `product/20/edit`?

**Comment by Dt-Sodium** [comment]
I'm not sure how Angular's engine but the way i see it the product editing component reacts to the product id parameter change and loads the new product using a service, so i would say that a new instance is not created.

**Comment by mlc-mlapis** [comment]
@Dt-Sodium ... if you have only one `<router-outlet>` then `product` component is shared ... it means that a new instance is NOT created when routing from `/product/10/edit` to `/product/20/edit` is done. That's fine.

But then the subscription to `_route.params` should still be enough because for route definition:
`{path: 'product/:id/edit', component: ProductComponent}`
the subscribed `params` returns `id` value, ... so you know to which product you are routing.

constructor(private _route: ActivatedRoute) {
   console.log('... a new instance of PRODUCT component is created');
   _route.params.subscribe(
      params => console.log('... activated route params:', params)
   );
}

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

<hr>

The suggestions above are good. If you're manually subscribing to `.parent.parent`, you're going to have to unsubscribe.

However, there might be something useful coming in the release in about 5 minutes from now. [This feature](https://github.com/angular/angular/pull/20678) will allow you to basically merge all params, so children will always have access to parent params and you don't need to go `.parent` anymore. We intend to eventually make this the default behavior.

The documentation on it should end up [here](https://angular.io/api/router/ExtraOptions) once the release goes out.
