### ISSUE TITLE
@angular/compiler-cli 5.1.3 uses tsickle@0.25.6 which enforces typescript@≥2.4.2 <2.6

### ISSUE THREAD

**Issue by konradk-sparkbit** [angular/angular#21338]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

I”ve got following message after <code>npm prune & npm install</code>:
<pre><code>+-- @angular/compiler@5.1.3
`-- UNMET PEER DEPENDENCY typescript@2.6.2

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN @angular/compiler-cli@5.1.3 requires a peer of typescript@>=2.4.2 <2.6 but none was installed.
npm WARN tsickle@0.25.6 requires a peer of typescript@>=2.4.2 <2.6 but none was installed.
</code></pre>

## Expected behavior

Everything working fine

## Minimal reproduction of the problem with instructions
Try to install as dependencies <code>@angular</code> packages v5.1.3 along with dev dependencies <code>typescript</code> v2.6.2 and <code>@angular/compiler-cli</code> v5.1.3; installs packages fine without the latter one but refuses to run with <code>ng serve</code> with problem
<pre><code>The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
Error: The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
    at Object.CompilerCliIsSupported (‹PROJECT_PATH›\node_modules\@ngtools\webpack\src\ngtools_api.js:25:15)
    at new AotPlugin (‹PROJECT_PATH›\node_modules\@ngtools\webpack\src\plugin.js:29:23)
    at _createAotPlugin (‹PROJECT_PATH›\node_modules\@angular\cli\models\webpack-configs\typescript.js:92:16)

    at Object.getNonAotConfig (‹PROJECT_PATH›\node_modules\@angular\cli\models\webpack-configs\typescript.js:100:19)
    at NgCliWebpackConfig.buildConfig (‹PROJECT_PATH›\node_modules\@angular\cli\models\webpack-config.js:37:37)
    at Class.run (‹PROJECT_PATH›\node_modules\@angular\cli\tasks\serve.js:71:98)
    at check_port_1.checkPort.then.port (‹PROJECT_PATH›\node_modules\@angular\cli\commands\serve.js:123:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)</code></pre>

## What is the motivation / use case for changing the behavior?

Bug fix

## Environment

<pre><code>
Angular version: 5.1.3
Typescript version: 2.6.2

For Tooling issues:
- Node version: 6.7.0
- Platform:  Windows

Others:

</code></pre>

**Comment by sarunint** [comment]
Angular v5.1 currently supports upto TypeScript 2.5. You should use tilde (~) prefix in your package.json to prevent npm from installing TypeScript 2.6.

**Comment by konradk-sparkbit** [comment]
@sarunint: Not really interested in such solution; maybe <code>tsickle</code> could be updated in <code>@angular/compiler-cli</code> as it was in <code>@angular</code>?

**Comment by sarunint** [comment]
Well, the thing is TypeScript is not following semantic versioning. They are introducing breaking changes even in minor updates. The Angular team is basically need to update the code to support different versions of TypeScript. Support for TypeScript 2.6 is coming in Angular v5.2, though. (See #21144)

**Comment by konradk-sparkbit** [comment]
I see; feel free to close this issue then if this is a duplicate of aforementioned #21144.
