### ISSUE TITLE
Add option to render the component tag when using tests

### ISSUE THREAD

**Issue by da-mkay** [angular/angular#21330]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[#] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Let's say we have a component `<app-component>` with the template `<h1>hello</h1>`.
When testing the component, only its **content** (the `h1`) is added to a `div` (id=`root0`) in the  testing environment. However, the component tag itself (`<app-component>`) is not added.

## Expected behavior
I would expect that the component-tag is also added to the DOM, because that's the way how it's done when using the component in the real app (either using routing or adding it directly to DOM). Or at least that behavior should be configurable.

## What is the motivation / use case for changing the behavior?
When rendering a component without its enclosing tag as specified in the metadata (`selector`) it can cause problems when that component uses `ViewEncapsulation.None`. When using `ViewEncapsulation.None` it makes sense to use the component's tag-name (`app-component`) in CSS, for example to style the `h1` only in that component: `app-component > h1 { /* ... */ }`.
Sometimes it's useful to test for some of these CSS properties (opacity, positioning etc.). However, since the `app-component` tag is not used during the tests, the CSS will not be applied and cannot be tested.

Currently, a workaround is to add a `HostBinding` for a CSS-class (e.g. `.app-component`), and then use that class in the CSS instead of the component's tag name:
`@HostBinding('class.app-component') readonly componentStyle = true;`
`.app-component > h1 { /* ... */ }`

However, I would like to avoid additional code that is only needed to make the tests work. It would be better to render the components in the tests using their own tag or at least make that behavior optional :)

## Environment
<pre><code>
Angular version: 4.4.6
</code></pre>

**Comment by vikerman** [comment]
This seems to be happening only for the root component. Reducing the severity. 

Not sure whether the effort is worth the pay-off

**Comment by da-mkay** [comment]
It affects all components. AppComponent was just an example.
When using `TestBed.createComponent(SomeOtherComponent)`, not the `SomeOtherComponent` itself is added to the DOM of the testing environment, but instead only its child elements.
