### ISSUE TITLE
[compiler-cli] Should Metadata JSON be written via ts.WriteFileCallback ?

### ISSUE THREAD

**Issue by dherges** [angular/angular#21339]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The synthetic index file is written via plain `fs.writeFileSync`:

```ts
          // If we are writing the synthetic index, write the metadata along side.
          const metadataName = fileName.replace(DTS, '.metadata.json');
          fs.writeFileSync(metadataName, indexMetadata, {encoding: 'utf8'});
```

https://github.com/angular/angular/blob/master/packages/compiler-cli/src/metadata/bundle_index_host.ts#L52-L54

## Expected behavior

Is the above intended? Should (is it possible) to write the metadata json through `delegate.writeFile(..)`?

## Minimal reproduction of the problem with instructions

See above.

## What is the motivation / use case for changing the behavior?

Using compiler from programmatic node API

```ts
  const tsCompilerHost: ts.CompilerHost = /* ... */;  
  tsCompilerHost.writeFile = /* ... customizing the ts.WriteFileCallback */;

  ng.createCompilerHost({
    options: tsConfig.options,
    tsHost: tsCompilerHost
  })
```

## Environment

<pre><code>
Angular version: 5.1.x
</code></pre>

**Comment by JoostK** [comment]
Fixed in #23054.
