### ISSUE TITLE
Need a way to get ComponentRef from EmbeddedViewRef

### ISSUE THREAD

**Issue by mertdeg2** [angular/angular#21341]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Lets say i have this template defined somewhere:

```html
<ng-template><foo></foo></ng-template>
```

I want to instantiate this ng-template (possible using ViewContainerRef), and get a reference to foo component instance. I know for sure ng-template will only contain <foo> component.

## Expected behavior
Angular provides an API to achieve this.

## What is the motivation / use case for changing the behavior?
Without this, we needed to write code that can break with an update to Angular. One solution was to define Foo component like:
```ts
export class Foo {
  static mostRecentlyCreatedFoo;
  constructor() {
     Foo.mostRecentlyCreatedFoo = this;
   }
}
```

This workaround is present in couple of places including material2 code base: https://github.com/angular/material2/blob/693c8e843e38aba8b02c6f3c1085e37cb1c8a40b/src/cdk/table/table.ts#L454-L460

## Environment

<pre><code>
Angular version: 4

Browser:
All browsers

**Comment by mertdeg2** [comment]
@jelbourn

**Comment by kara** [comment]
@mertdeg2 Can you provide specific code samples for  1) the situation where you would need a reference to the component instance 2) sample code for how you'd expect to retrieve it?

**Comment by jelbourn** [comment]
@kara We do this in the cdk table and tree. It would be easier to go over it in person.
