### ISSUE TITLE
Refresh components as with iframes

### ISSUE THREAD

**Issue by albertodenatale** [angular/angular#21356]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently if I tweak a component in the code and I want to see it changed I have to reload the entire page.

## Expected behavior
It would be nice to be able to right click on the component and see the same options that I would see for a frame in Chrome:
- View Frame Source (it would become View Component Source)
- Reload Frame (it would become Reload Component)

![screen shot 2018-01-06 at 12 56 44](https://user-images.githubusercontent.com/11591862/34640085-10ec273e-f2e4-11e7-8d82-28e53a754914.jpg)

**Comment by Toxicable** [comment]
You're referring to HMR which is already possible.

**Comment by kara** [comment]
This doesn't look related to the Angular repo, so closing.
