### ISSUE TITLE
Skip `fullTemplateTypeCheck` for external libraries

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#21353]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The problem I am encountering with `fullTemplateTypeCheck` is that when one of my external dependencies have issues with their template, this would cause compilation errors and unless I turn off `fullTemplateTypeCheck`, I am unable to compile my library.

This is a feature request following: #21287
  
## Propose
I propose a new flag similar to `skipLibCheck` that skips declarations checking for libraries. But this flag will skip template check for libraries, something along `skipLibTemplateCheck`, `skipLibFullTemplateCheck` etc...

## What is the motivation / use case for changing the behavior?
That I can still use `fullTemplateTypeCheck` for my library even though one of my dependencies has a template issue.

## Environment

<pre><code>
Angular version: 5.1.2
</code></pre>

**Comment by elvirdolic** [comment]
@Angular team it would be great to get this fixed somehow, similar issue as this one: https://github.com/angular/angular/issues/21390. I don't know how big this fix is but it's really a pain to use this features.

**Comment by dornfeder** [comment]
Any progress on this issue? It's really annoying...

**Comment by jcimoch** [comment]
Still an issue :(

**Comment by stefnoten** [comment]
In my opinion, the extra compiler flag is not needed: `fullTemplateTypeCheck` should always ignore dependencies. The tsconfig file contains the TypeScript configuration for your *own* project. It makes sense for TypeScript in general to type check library declaration files because your own code may directly interact with it, but one never interacts with the internal templates of library components.

**Comment by antoinebrault** [comment]
Having the same problem with Amplify (https://github.com/aws-amplify/amplify-js/issues/3620).

**Comment by JoostK** [comment]
Hi folks,

with the Ivy compiler, libraries are compiled fully separate from the application and that results in the compiler _not_ typechecking external libraries.

There's no flag available to control this behavior, and there won't be a flag either.
