### ISSUE TITLE
titlecase pipe capitalises special characters in middle of word

### ISSUE THREAD

**Issue by aaroncolaco** [angular/angular#21368]
## I'm submitting a...
Bug report

## Current behavior
Using the `titlecase` pipe in my html causes 'special' alphabets like `ã`, and 1 characters after it, to be capitalised
eg: `{{ "margão" | titlecase }}` gives `MargÃO`
`{{ "margãoabc" | titlecase }}` gives `MargÃOabc`

## Expected behavior
`{{ "margão" | titlecase }}` should give `Margão`
`{{ "margãoabc" | titlecase }}` should give `Margão`

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version  63.0.3239.84 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.3
- Platform:  Mac

Others:
</code></pre>

**Comment by trotyl** [comment]
Relates to #20123

**Comment by aaroncolaco** [comment]
@trotyl oh yes! sorry. Closing this now.
