### ISSUE TITLE
The function "getLocaleCurrencyName" doesn't work with some locale code. For example: es-ES

### ISSUE THREAD

**Issue by rubensaraldao** [angular/angular#21363]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

console.log(getLocaleCurrencyName("es-ES"));  doesn't work and an error is displayed:
ComponentFatherComponent.html:1 ERROR Error: Missing locale data for the locale "es-ES".
    at findLocaleData (common.js:1496)
    at Object.getLocaleCurrencyName (common.js:1365)
    at ComponentSonComponent.ngOnInit (component-son.component.ts:24)
    at checkAndUpdateDirectiveInline (core.js:12400)
    at checkAndUpdateNodeInline (core.js:13927)
    at checkAndUpdateNode (core.js:13870)
    at debugCheckAndUpdateNode (core.js:14763)
    at debugCheckDirectivesFn (core.js:14704)
    at Object.eval [as updateDirectives] (ComponentFatherComponent.html:3)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:14689)

## Expected behavior

The name of the currency for "es-ES" should be returned.

## Minimal reproduction of the problem with instructions

in any component, import this:
   import { getLocaleCurrencyName } from '@angular/common';

and after, use the fuction with es-ES in the ngOnInit section:
   console.log(getLocaleCurrencyName("es-ES"));

## What is the motivation / use case for changing the behavior?

testing angular

## Environment

<pre><code>
Angular version: X.Y.Z

angular 5
{
  "name": "my-first-project",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.6.3",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  9.3.0
- Platform:  windows

Others:

</code></pre>

**Comment by ocombe** [comment]
You need to load the locale data for `es` first:
```ts
import { registerLocaleData } from '@angular/common';
import localeEs from '@angular/common/locales/es';

// the second parameter 'fr' is optional
registerLocaleData(localeEs, 'es-ES');
```
