### ISSUE TITLE
Component to component interaction Issue

### ISSUE THREAD

**Issue by amit0shakya** [angular/angular#21366]
I need to interact between components so I use Observables Subject method in Service but it dosen't work. I read docs and everything and I did the same thing but it doesn't work. I am creating an E-commerce shopping app. and I want when somebody clicks on product to buy then, this should add in shopping cart which is in nav.ts here is my code https://github.com/amit0shakya/ngEcommerce.

you can find angular code into client folder.

here is my app structure

Home.ts (homepage)
|->productpage.ts [Productpage shows all products in homepage]
|            |->product.ts [Product component to show individual product cost and other specification]
|->About
|->New Product [to add new product]
|->Register
|->nav.ts [Navigation component it contains navigation and shopping cart]
]->web.service.ts

Here I want to send data from product.ts to nav.ts using web.service.ts,

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mlc-mlapis** [comment]
@amit0shakya ... prepare the basic simple demo of using a singleton service and its one Observable stream used in components through DI on http://stackblitz.com and then discuss your problem on Angular Gitter channel.

Close this issues! It's not definitely an issue ... it's a misunderstanding of something on your side.
