### ISSUE TITLE
Un-mapped properties of Response Type are all undefined with HttpClient

### ISSUE THREAD

**Issue by bastienJS** [angular/angular#21369]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

this.http.get<UserResponse>('https://api.github.com/users/bastienJS')

UserResponse class has 4 properties:

```
interface UserResponse {
  login: string;
  bio: string;
  company: string;
  IsSelected: bool;
}
```

When request is I expect that user.IsSelected is 'false' but it is undefined

## Expected behavior

I would have expected the default value which is 'false' for a bool type in the interface.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/E3LR3JjJ8iPcmjzwi6lQ?p=preview

Why is the IsSelected property undefined? See console output.

## What is the motivation / use case for changing the behavior?

My bound html expects a false/true value not undefined properties.

## Environment

<pre><code>
Angular version: latest

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Your json returned doesn't have a `IsSelected` property.

**Comment by kara** [comment]
This doesn't look like an Angular issue, so closing.
