### ISSUE TITLE
ng-if unable to find provider for ProtoViewRef after angular 22 => 25 upgrade

### ISSUE THREAD

**Issue by samccone** [angular/angular#2137]
Here is the patch of the upgrade from 22 to 25
https://github.com/samccone/angular2-base/commit/79bcc7a3828c0f59ca2f920935d2b193d6050532

It looks like for some reason the `ng-if` directive is not being injected with the ProtoViewRef service.

-------

#### Steps to reproduce

* clone the repo https://github.com/samccone/angular2-base
* checkout the branch `sjs/if-bug`
* start a local server
* visit the page
* view the console

![screen shot 2015-05-23 at 1 09 34 pm](https://cloud.githubusercontent.com/assets/883126/7785056/fd85d0f4-014c-11e5-97ba-61ba93813ae7.png)

--------

#### What is expected

It to not error

**Comment by gdi2290** [comment]
`*ng-if="true"`

**Comment by samccone** [comment]
so I guess that makes 

https://github.com/angular/angular/blame/842459aa46c1387a6f599422321486a6abe0c7a7/modules/angular2/docs/core/01_templates.md#L385

wrong?

**Comment by samccone** [comment]
ah ok

refered to the source code
https://github.com/angular/angular/blob/aec51d616b079308bc4480924e81be4f22ae4215/modules/angular2/src/directives/ng_if.ts#L24-L26

Guess this is is the *new new* :sparkles: syntax
