### ISSUE TITLE
Load external js script dynamically in Angular 2

### ISSUE THREAD

**Issue by awsumnik** [angular/angular#21376]
I am building an application using angular 2, wherein I want some external javascript files to be loaded for some specific components and not globally.

I have looked around to get this implemented, but didn't find any example or way to achieve it from angular 2 documentation.

I want to know if there is any way to load js files in a components just like including css using styleUrls inside a angular component.

Found one solution on stackoverflow, which tells to export the js files using a ScriptStore service and then inject this service to the required component. Here is the link for the same - 
https://stackoverflow.com/questions/34489916/load-external-js-script-dynamically-in-angular-2?noredirect=1

Just want to know if this is the recommended way to do it or it is just a way around to achieve it ? Please let me know if there is another recommended way to achieve the same.

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).


---

You can lazily load modules with `System.import(pathToModule)`

**Comment by kara** [comment]
As @Toxicable mentioned, this isn't an issue or a feature, so we have to close this.
