### ISSUE TITLE
new project with cli does not work in ie11

### ISSUE THREAD

**Issue by arnjmllr** [angular/angular#21389]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I run ng new myProject  (from terminal in VS Code)
run ng serve

I will leave out the message about "Can't execute code from a freed script", since there is a known workaround for that.

The error I am getting is:

**Syntax error
vendor.bundle.js (446,1)**

I saw somewhere (maybe SO) to try this:
<meta http-equiv="X-UA-Compatible" content="IE=11" />
did not work.

the site does work in latest versions of chrome, firefox and Edge. 

## Expected behavior

I should be able to launch site with ie11 w/out getting script error. The tour of heros app should be displayed.

## Minimal reproduction of the problem with instructions
create a new project using the cli (1.6.4 with angular 5.0.0)
open ie and browse to site.

## What is the motivation / use case for changing the behavior?

angular 5.0.0 sites will be able to run in ie11

## Environment

<pre><code>
Angular version: 5.0.0 

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x ] IE version 11.192.16699.0
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.3 
- Platform: windows 10 (surface pro 64 bit) 

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/21385

**Comment by arnjmllr** [comment]
Duplicate of #21385 as mentioned by @ericmartinezr
