### ISSUE TITLE
Attention, maybe there is a typo here?

### ISSUE THREAD

**Issue by dementey** [angular/angular#21384]
Attention, maybe there is a typo here?
https://angular.io/tutorial/toh-pt3#update-the-heroescomponent-template  
**HeroComponent** - not true, **HeroesComponent** - right

_Not true_
> It's a one way data binding from the selectedHero property of the **HeroComponent** to the hero property of the target element, which maps to the hero property of the HeroDetailComponent.

_Right_
> It's a one way data binding from the selectedHero property of the **HeroesComponent** to the hero property of the target element, which maps to the hero property of the HeroDetailComponent.

**Comment by gkalpak** [comment]
You are right, @dementey 👍
Care to submit a PR with the fix? ☺️

**Comment by kapunahelewong** [comment]
Thank you @dementey the fix beat my PR to the finish line. I'll close this but if you have any outstanding questions, feel free to tag me.
