### ISSUE TITLE
New angular 5 app does not work in Internet Explorer 9 and 10

### ISSUE THREAD

**Issue by Rajnii** [angular/angular#21385]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
New angular 5 app generated using angular cli does not work in IE 9 and 10. We get the following error:
```DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: localhost:4200
HTML1300: Navigation occurred.
File: localhost:4200
SCRIPT1002: Syntax error
File: vendor.bundle.js, Line: 446, Column: 1
SCRIPT5011: Can't execute code from a freed script
File: zone.js, Line: 2783, Column: 17
```

## Expected behavior
New app should work fine on IE 9 and 10, as given in [documentation](https://angular.io/guide/browser-support) 

## Minimal reproduction of the problem with instructions
Create a new app using `ng start newapp`. `cd` into the directory. Run` npm install` and `ng serve`.

## Environment

<pre><code>
Angular version:  5.1.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 9 and 10
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  6.10.0  
- Platform:  Windows 8.1 

</code></pre>

**Comment by kara** [comment]
This looks like an angular-cli issue, and should be filed in that repo.
