### ISSUE TITLE
forbiddenName validator in template-driven form live example doesn't work

### ISSUE THREAD

**Issue by kamil-zielinski** [angular/angular#21380]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

forbiddenName validator doesn't work in the plunkr example of tempalte-drive form.

## Expected behavior

There should be validation error message visible: 'Name cannot be Bob.'

## Minimal reproduction of the problem with instructions

1. Go to [form validation live exmaple](https://angular.io/generated/live-examples/form-validation/eplnkr)
2. Type 'bob' in 'Name' input of Template-Driven Form

## Environment

<pre><code>
Angular version: 5.1.2

Browser:
- [x] Chrome (desktop) version 62.0.3202.62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by skreborn** [comment]
This seems to be because `ForbiddenValidatorDirective` has a selector of `appForbiddenName`, so it should either use that property, change its selector to `forbiddenName`, or the property `appForbiddenName` could be added to the template.

**Comment by kamil-zielinski** [comment]
@skreborn You are right. I've changed selector name and it works.

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/20206, https://github.com/angular/angular/issues/20234, https://github.com/angular/angular/issues/21242
