### ISSUE TITLE
i18n does not properly translate sometimes

### ISSUE THREAD

**Issue by erata** [angular/angular#21387]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

translates some words/sentences properly but does not translate others. I do not know why it occurs but I meet very rarely this bug. When use a different computer (OS: Windows 10) and test it i see no problem. 

my html includes:

```
<span i18n>Signature Area</span>
<span i18n><strong>Ia</strong> Add Text</span>
<label class="col-xs-6" i18n>Request Text Input</label>
```

the translation expressions exist in messages.tr.xlf file as below. 
```
<trans-unit id="7f2725f00ad01be97338a36c94611c867da1bca3" datatype="html">
        <source>Signature Area</source>
        <target>İmza Alanı</target>
 </trans-unit>
<trans-unit id="0316381b284d4d34a2efe24a848ae07d530c1c1c" datatype="html">
        <source><x id="START_TAG_STRONG" ctype="x-strong"/>Ia<x id="CLOSE_TAG_STRONG" ctype="x-strong"/> Add Text</source>
        <target><x id="START_TAG_STRONG" ctype="x-strong"/><x id="CLOSE_TAG_STRONG" ctype="x-strong"/> Metin Ekle</target>
 </trans-unit>
 <trans-unit id="1d3d925a3f2e3b3a83ba6848e2e38c567e69d309" datatype="html">
        <source>Request Text Input</source>
        <target>Metin Girişi İste</target>
</trans-unit>
```

i get below result (the top line is normal, belows are incorrect):

![translation issue](https://user-images.githubusercontent.com/3416873/34677126-294df3c6-f4a0-11e7-847a-25048621520f.PNG)

the top expression is translated properly but below ones not. this occurs some times.

## Expected behavior

translate properly

## Environment

<pre><code>
Angular version: 4.3.5

Browser:
- [x] Chrome (desktop) version 63
 
For Tooling issues:
- Node version: v6.9.1
- Platform:  Intel Mac OS X 10_11_6

Others:

</code></pre>

**Comment by ocombe** [comment]
Have you changed the DOM since you last exported the elements? The auto-generated IDs could have changed since then.
Try with custom IDs and see if it works.

**Comment by erata** [comment]
hi @ocombe. 

> Have you changed the DOM since you last exported the elements? The auto-generated IDs could have changed since then.

the text does not changed inside i18n area as <... i18n>...bla bla bla...</>. if it changes then the translation does not run both mac and windows machines. but it run on windows 10 machine now.

> Try with custom IDs and see if it works.

 this coluld be a solution and i will try it. but at this time it is a necessity adding custom IDs for every translation. because otherwise i don't know whether every i18n's generated IDs run different machines or not.

**Comment by vicb** [comment]
Closing as there is no repro available
