### ISSUE TITLE
Why can it work without specifying an operator (@) in services?

### ISSUE THREAD

**Issue by splincode** [angular/angular#21382]
## Adequate behavior

If I write this code, the compiler will swear

```typescript
Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
```

```text
Unexpected value 'AppComponent' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation
```

## Inadequate behavior

But if I write this code, the compiler will not swear

app.component.ts

```typescript
import { Component, Injectable } from '@angular/core';

Injectable() // thats without @
export class AuthService {
  constructor() {

  }
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';

  constructor(public auth: AuthService) {

  }

}
```

app.module.ts

```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent, AuthService } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [AuthService],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

![image](https://user-images.githubusercontent.com/12021443/34669590-753dc24c-f483-11e7-97f5-ecb84e4e00af.png)

That is, I am purely allowed from the beginning to write Injectable without an operator (@). So, it can lead me here:

## Uncertain behavior

app.component.ts

```typescript
import { Component, Injectable } from '@angular/core';
import { HttpClient } from 'selenium-webdriver/http';

Injectable()
export class AuthService {
  constructor(private http: HttpClient) {

  }
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';

  constructor(private auth: AuthService) {

  }

}
```

app.module.ts

```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { AppComponent, AuthService } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    HttpClientModule
  ],
  providers: [AuthService],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

![image](https://user-images.githubusercontent.com/12021443/34669593-7ac31e42-f483-11e7-9132-4f4fbeb6a767.png)

```text
Uncaught Error: Can't resolve all parameters for AuthService: (?).
```

But I would expect from the very beginning

```text
Unexpected value 'AuthService' declared by the module 'AppModule'. Please add a @Injectable annotation
```

## The worst after

The worst thing is that if I add an immediately missed statement (@), it means that ng serve does not work properly after that.

![image](https://user-images.githubusercontent.com/12021443/34669537-2e520a78-f483-11e7-8089-2faaa498a2d8.png)

![image](https://user-images.githubusercontent.com/12021443/34669572-65ce0b46-f483-11e7-8a0c-932a5f22819a.png)

## Environment

Angular version: 5.1.3
Browser: Chrome 63
Node version: 8.7.0
Windows 10

**Comment by skreborn** [comment]
This happens because `@` denotes a decorator. If you simply add `Injectable`, it does nothing. You might as well just write anything else there.

```typescript
Injectable()
export class AuthService { ... }

// same as

console.log('this does nothing')
export class AuthService { ... }
```

If you add `@Injectable` though, you make TypeScript keep the class' types around. This is a bit of a "hack" to make dependency injection work. Without this, your application would have no idea what `AuthService` meant in runtime.

Note that the `@Injectable` decorator - unlike `@Component`, for example - is special, because it has no content, and isn't technically required for a service to work, it just helps with dependency injection.

Alternatively, you can omit the `@Injectable` decorator on services, and use the `@Inject` decorator in your constructors, but there really isn't any upsides to this approach.

```typescript
export class AuthService { ... }

@Component({ ... })
export class AppComponent {
  constructor(@Inject(AuthService) private auth: AuthService) {}
}
```

**Comment by splincode** [comment]
But, unfortunately, this increases the learning curve...

**Comment by kemsky** [comment]
It seems that compiler check for `Injectable` is still missing, `Component` decorator is checked just because compiler need to use it to generate component. `Injectable()` is just a function call if used without `@`. 

Also, see #18604:
> @Injectable is still required for testing, hence it can't be removed.

It just doubles confusion about future and current state of `Injectable` .

**Comment by splincode** [comment]
```import { HttpClient } from 'selenium-webdriver/http';```

Even if I connect the wrong service, it will not work until I add the correct @ operator, which means that there is no special check

**Comment by splincode** [comment]
> It just doubles confusion about future and current state of Injectable
It's frustrating...

**Comment by trotyl** [comment]
> It seems that compiler check for Injectable is still missing

Strict type-checking for `@Injectable()` already came in `5.0` version, see #19412

> It just doubles confusion about future and current state of Injectable .

`@Injectable()` will accept parameters like `@Injectable(SomeModule, {deps: []})`, then it's not an useless (conventional) decorator any more, see #20850

**Comment by splincode** [comment]
Why would he do this? (Because, we are used to the old Injector)

**Comment by mhevery** [comment]
Sorry this works as intended, even if it is confusing per explanation above.
