### ISSUE TITLE
lots of weird characters in node_modules/@angular/core/src/application_tokens.d.ts

### ISSUE THREAD

**Issue by mmorandini** [angular/angular#21391]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

node_modules/@angular/core/src/application_tokens.d.ts gets created with a lot of strange characters at the top of the file.

## Expected behavior

node_modules/@angular/core/src/application_tokens.d.ts should not have thos characters in it.

## Minimal reproduction of the problem with instructions

When creating a new app with ng new, if i try to compile it I cannot, the reason being something is wrong with node_modules/@angular/core/src/application_tokens.d.ts, which is created with a lot of apparently random chracters at the top of it.

## Environment

<pre><code>
Angular version: 5.x

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.0
- Platform:  Mac

Others:

</code></pre>

**Comment by kara** [comment]
This looks like an angular-cli issue, but hard to tell without more information about the error or the characters you're seeing. I'd suggest opening this in the cli repo with more info.
