### ISSUE TITLE
FormBuilder Error: TypeError: Cannot read property 'Subject' of undefined

### ISSUE THREAD

**Issue by ericmdantas** [angular/angular#2139]
Hello!

I'm trying to use FormBuilder for a simple todoApp, but everytime I'd do:
```js
formBuilder.group({something: ["Something Here"]})
```

I'd get the error ```TypeError: Cannot read property 'Subject' of undefined```.

I was taking a look at the angular2.js file and it has:

```js
this._subject = new Rx.default.Rx.Subject();
```

and 
```js
this._immediateScheduler = Rx.default.Rx.Scheduler.immediate;
```

After checking that there's no ```Rx``` inside ```Rx.default```, I changed the code and it now looks like this:

```js
this._subject = new Rx.default.Subject();
```

and 
```js
this._immediateScheduler = Rx.default.Scheduler.immediate;
```

And it now works as expected.

Any clue on what's going on? [Here's my repo with the error](https://github.com/ericmdantas/ng2-play).

PS: I'm using version .25.

**Comment by ericmdantas** [comment]
Hmm, I see this was fixed in the [angular2.dev.js](https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js). Could someone confirm?

```js
if (Rx.hasOwnProperty('default')) {
            this._subject = new Rx.default.Rx.Subject();
            this._immediateScheduler = Rx.default.Rx.Scheduler.immediate;
          } else {
            this._subject = new Rx.Subject();
            this._immediateScheduler = Rx.Scheduler.immediate;
          }
        }
```

**Comment by cexbrayat** [comment]
I think you are running into #1797 : I had the same but it's not an issue in Angular 2 itself.

**Comment by ericmdantas** [comment]
Thanks, I'll give it a try later today.
