### ISSUE TITLE
Why is not there a good selection of resources for Angular like Vue (awesome-vue)?

### ISSUE THREAD

**Issue by splincode** [angular/angular#21393]
Already have a good selection of Vuejs
https://github.com/vuejs/awesome-vue

However, I would like to see the same in this community
https://github.com/angular/awesome-angular or https://github.com/angular/angular-labs

Because most exist for Angular2 (but this is not an official repository):
https://github.com/gdi2290/awesome-angular

The official repository would be a positive aspect for this...

**Comment by guilhermejcgois** [comment]
I think that is this [link](https://github.com/gdi2290/awesome-angular) that u r looking for

**Comment by sarunint** [comment]
Well, there is.

https://angular.io/resources

**Comment by splincode** [comment]
@guilhermejcgois most exist for Angular2

**Comment by splincode** [comment]
@sarunint there is very scarce

**Comment by kapunahelewong** [comment]
Hey @splincode, @sarunint seems to have answered your question, so I'll close this issue. If you still have outstanding questions, let me know and we'll make sure to address them.
