### ISSUE TITLE
Compile for production problem

### ISSUE THREAD

**Issue by martinaguilar** [angular/angular#21398]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

everything works ok like this: 
<pre><code>ng build --delete-output-path --output-path=~/test/ --base-href=./
</code></pre>

And don't work if I compile it like this:
<pre><code>ng build --prod --build-optimizer --delete-output-path --output-path=~/test/ --base-href=./
</code></pre>

Material select component, sidenav and other components don't close. They kept open. It's like nothing works. 

I didn't had this problem with version 5.0.5 and material release candidate

## Environment

<pre><code>
Angular CLI: 1.6.2
Node: 6.11.1
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.0.2
@angular/cli: 1.6.2
@angular/material: 5.0.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.2
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0

Browser:
- [x] Chrome (desktop) version 62
- [x] Chrome (Android) version 63
- [ ] Chrome (iOS) version XX
- [x] Firefox version 56 / 57
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Platform:  Linux, Windows, Android webview

Others:

I've test this with windows, ubuntu linux, chrome, firefox and webview. No changes between platforms or browsers. Everytime fails the same way.
</code></pre>

**Comment by kara** [comment]
This doesn't look like an Angular issue. If you're having issues with Material components, try filing in the material2 repo.

**Comment by martinaguilar** [comment]
This seems an angular issue to me and Material here is just a comment. 
I you see, when I buid my app with ng build, everythings works ok, but everything freeze when I add --prod or --build-optimizer.
How can Material affect in any way? Please @kara re-open this issue
