### ISSUE TITLE
Angular 5.1.3 Mistake in Tutorial -> Services

### ISSUE THREAD

**Issue by madhu131313** [angular/angular#21409]
At [Subscribe Section](https://angular.io/tutorial/toh-pt4#subscribe-in-heroescomponent) of Services in the Tutorial 

`heroes.component.ts` is mistakenly named as  `hero.component.ts` in 

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kapunahelewong** [comment]
Thank you for this @madhu131313!

**Comment by madhu131313** [comment]
My Pleasure to be a drop in the Angular Ocean

**Comment by kapunahelewong** [comment]
Annnnd fixed! :)
