### ISSUE TITLE
Documentation example missing JS reference

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#2140]
In [https://angular.io/docs/js/latest/guide/setup.html](https://angular.io/docs/js/latest/guide/setup.html)

```
<!DOCTYPE html>
<html>
  <head>
    <script src="https://jspm.io/system@0.16.js"></script>
    <script src="https://code.angularjs.org/2.0.0-alpha.22/angular2.dev.js"></script>
  </head>
  <body>
    <my-app></my-app>
    <script>
      System.import('main');
    </script>
  </body>
</html>
```

A reference to traceur runtime is missing.
`<script src="https://github.jspm.io/jmcriffey/bower-traceur-runtime@0.0.87/traceur-runtime.js"></script>`

**Comment by shlomiassaf** [comment]
Very confusing for first-timers who still dont know about the 3 different files (dev/sfx etc)

**Comment by gdi2290** [comment]
`traceur-runtime` wouldn't need to be required soon

**Comment by jomeier** [comment]
@gdi2290: Why not?

**Comment by vicb** [comment]
Angular2 will move to TypeScript (away from Traceur). The migration is on-going.
