### ISSUE TITLE
HttpClient Security recommandation

### ISSUE THREAD

**Issue by ohrrkan** [angular/angular#21419]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
You make possible and also recommend to Typechecking the response of the HttpClient and more precisely the HttpResponse<T>  :: 
https://angular.io/guide/http 

## Expected behavior
This usage can lead to multiple security issue. For me a http Response MUST be "ANY". This will Focus the attention of the user on creating a function immediately after to check received data and turn them into  a defined interface.
Also this usage will break some IDE, and TSLINT warning on unsafe use of any type.

## What is the motivation / use case for changing the behavior?
Security.
Rules :  Outside data are ANY Data until a function define them.

**Comment by alxhub** [comment]
Hi @ohrrkan, thanks for the feedback. I disagree that additional type safety creates a security risk. Using `any` is in fact worse, because it allows developers to access properties which should not be on the object.
