### ISSUE TITLE
DI: Resurrect @Injectables([])

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2141]
`@Inject` works fine when you have full control over your code base. However, if you're importing other libraries, you still want Angular to be able to reflect/generate factories for the constructor without an explicit `@Inject`, e.g.:

```dart
import 'package:angular2/di.dart';

@Injectables(const [
  ChartRenderer
])
import 'some_char_library.dart';
```

**Comment by gdi2290** [comment]
I think the idea is that you do the same thing as in angular1 where you have a top level file where you include your 3rd party injectables when you bootstrap

**Comment by matanlurey** [comment]
That means you have to manually create factories, though. At least in the Dart version (maybe JavaScript doesn't care because it is uses dynamic `eval` to generate factories).

**Comment by gdi2290** [comment]
here's my example 

`todoInjectables`
[TodoService.ts#L44](https://github.com/angular-class/angular2-webpack-starter/blob/955c7b1553d19e20eb1e81015feeb1758dc7cb3c/src/app/services/TodoService.ts#L44)

`appServicesInjectables `
[services.ts#L4](https://github.com/angular-class/angular2-webpack-starter/blob/955c7b1553d19e20eb1e81015feeb1758dc7cb3c/src/app/services/services.ts#L4)

`bootstrap`
[bootstrap.ts#L23](https://github.com/angular-class/angular2-webpack-starter/blob/955c7b1553d19e20eb1e81015feeb1758dc7cb3c/src/app/bootstrap.ts#L23)

**Comment by matanlurey** [comment]
You have no examples of using `toClass` though, which is what I think is not working.

**Comment by matanlurey** [comment]
@vsavkin, @kegluneq

**Comment by mhevery** [comment]
Reopen if this is still an issue.
