### ISSUE TITLE
FormGroup - allow to add validators without overwriting the existing one

### ISSUE THREAD

**Issue by Olgagr** [angular/angular#21410]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
This is very similar feature request to #10567 but for FormGroup. Right now this is not possible to add new validators to FormGroup without overwriting the existing one which leads to strange hacks to achieve it.

## Expected behavior
It would super nice to have a method like addValidators on AbstractControl or FormGroup.

## What is the motivation / use case for changing the behavior?
I have a component that gets as an input FormGroup. The component has to add a validator to this FormGroup. However, as this component is shared across application and can be used with different FormGroup instances. It is possible that one of them will have already some validators defined. I want to avoid situation that some validators are overwritten. It may lead to hard to find errors.

## Environment

<pre><code>
Angular version: 5.1.0
</code></pre>

**Comment by kara** [comment]
Given that`addValidators` would be added at the same time, I think it makes sense to track this as part of the existing issue, https://github.com/angular/angular/issues/10567
