### ISSUE TITLE
Error: NavParams is not an NgModule 

### ISSUE THREAD

**Issue by yuvanesh10** [angular/angular#21413]
I have implemented a barcode scanner function in my Ionic application.BUt I would like to implement the same function in my individual angular4/core UI application. I have been searching examples for angular2/4 but I couldn't find anything.

I tried to convert my ionic scanning function for angular.I have installed some ionic components into angular project.I am getting the following errors. Can someone help me out with this? Am I doing it in a right way ? Thank you guys

**buttons.component.ts**

import {ViewChild,Component } from '@angular/core';
import {BarcodeScanner} from  'ionic-native';
import {NavController}  from  'ionic-angular';
import {Platform}       from  'ionic-angular';
import {FormsComponent} from './forms.component';

@Component({
templateUrl: 'buttons.component.html'
})
export class ButtonsComponent {

@ViewChild(NavController) nav: NavController;

constructor() { }

click() {

BarcodeScanner.scan()
.then((result) => {
if (!result.cancelled) {
 const barcodeData = new BarcodeData(result.text);
 this.scanDetails(barcodeData);
 }
 })
  .catch((err) => {
   alert(err);
  })
 }

 scanDetails(details) {
 this.nav.push(FormsComponent, {details: details});
 }
 }

 export class BarcodeData {
 constructor(public text: String) {}
  }

**forms.component.ts**

import {ViewChild, Component } from '@angular/core';
import {BarcodeData} from './buttons.component';
import { NavController, NavParams } from 'ionic-angular';
import {Platform} from  'ionic-angular';

declare var cordova:any;

@Component({
templateUrl: 'forms.component.html'
})

export class FormsComponent {

@ViewChild(NavController) nav: NavController;

barcodeData: BarcodeData;
constructor(public navParams: NavParams, public platform:Platform) {
    this.barcodeData = navParams.get('details');
    this.platform = platform;
     }

launch(url) {
this.platform.ready().then(() => {
cordova.InAppBrowser.open(BarcodeData, "_system", "location=true");
});
}

back() {
    this.nav.pop();
      }
}

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by yuvanesh10** [comment]
@pkozlowski-opensource I have been trying in stackover flow as well..there are no response !!!  I am just trying to get the solution in any possible means !!!

**Comment by pkozlowski-opensource** [comment]
> I have been trying in stackover flow as well..there are no response !!! I am just trying to get the solution in any possible means !!!

You would have more success on SO (or any support forum) by:
* distilling the problem / question to the _simples possible_ form (minimal 3rd party dependencies, minimal amount of code);
* providing a minimal runnable example (plunker or similar).

I guess that you are not getting answers since people are having hard time to understand the problems you are having. In any case _no_ support questions are being answered here.
