### ISSUE TITLE
Problem on compile for produccion

### ISSUE THREAD

**Issue by martinaguilar** [angular/angular#21424]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

build with --prod  or --build-optimizer option generates a behavior than ng build does not.
Everything is overlapping, events are not working properly and in console I found errors as 404 to the routes I have define in my app.
But when I compile with ng build or runit with ng serve everything works fine. This is really awkward.
I didn't had this problem with version 5.0.5
This is not a material error. Compiler is producing a very different result for production and this translate to different behavior in this case.
![image](https://user-images.githubusercontent.com/377835/34740739-3a98be8a-f55f-11e7-97ef-79b7cb32f3c2.png)

![image](https://user-images.githubusercontent.com/377835/34740343-d593a7c6-f55d-11e7-9222-2be276f36ea1.png)

## Environment

<pre><code>
Angular CLI: 1.6.2
Node: 6.11.1
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.0.2
@angular/cli: 1.6.2
@angular/material: 5.0.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.2
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0

Browser:
- [x] Chrome (desktop) version 62
- [x] Chrome (Android) version 63
- [ ] Chrome (iOS) version XX
- [x] Firefox version 56 / 57
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Platform:  Linux, Windows, Android webview

Others:

I've test this with windows, ubuntu linux, chrome, firefox and webview. No changes between platforms or browsers. Everytime fails the same way.
</code></pre>

**Comment by kara** [comment]
I'm sorry, but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

**Comment by martinaguilar** [comment]
@kara 
I could finally found a solution to this problem.
When I update Angular and material, I did this way:
``
npm install --save  @angular/animations@'^5.0.5' @angular/common@'^5.0.5' @angular/compiler@'^5.0.5' @angular/compiler-cli@'^5.0.5' @angular/core@'^5.0.5' @angular/forms@'^5.0.5' @angular/http@'^5.0.5' @angular/platform-browser@'^5.0.5' @angular/platform-browser-dynamic@'^5.0.5' @angular/platform-server@'^5.0.5' @angular/router@'^5.0.5' @angular/compiler-cli@'^5.0.5' @angular/language-service@'^5.0.5'
``

and for material:
``
npm install --save @angular/material @angular/cdk
``

I create a new project to recreate the error. After several test I have found that the file package.json had different versions for some other libraries other than those mention before.

So I replace the package.json and node_modules folder and everything is working now. I think that the main problem is: I could not find a official way to update to new releases. 
The way I did, was found searching on the google.

This error took me a lot of time, and also I know that some other people is having the same problem.
Please... try to make docs a little bit clear

**Comment by mlc-mlapis** [comment]
@martinaguilar ... update of what ... NODE packages? You can just move your mouse pointer on any package name in `package.json` and info about the latest available version is showed. You can also use some tools like `npm-check-updates` NODE package installed globally to check on updates.

**Comment by martinaguilar** [comment]
@mlc-mlapis ...When a new version of angular is released, what I do is to update all @nagular/* npm dependencies. 
but what I did not update is:
<pre><code>
    "hammerjs": "^2.0.8",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
</pre></code>

All this dependencies remain the same and I have never had problems running ng serve, nor even have a warning. The only problem was that building for production mode, made the application work with a very strange behavior.
