### ISSUE TITLE
The adding the second `/` to import construction by `ng generate module`

### ISSUE THREAD

**Issue by Igor-Maf** [angular/angular#21439]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`ng generate module app-routing --flat --module=app` , as I understand, must add `import { AppRoutingModule } from './app-routing.module';` but it`s add the second `/` before `app-routing.module` in import construction 

## Expected behavior

 `ng generate module app-routing --flat --module=app` > `import { AppRoutingModule } from './app-routing.module';` in **app.module.ts**

## Minimal reproduction of the problem with instructions

[The screen of problem](http://joxi.ru/823xXGysJBOwBA)

## What is the motivation / use case for changing the behavior?

I use it because [the tutorial at angular.io](https://angular.io/tutorial/toh-pt5) describes this construction

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.1
- Platform:  Windows

Others:

</code></pre>

**Comment by alexeagle** [comment]
I think this issue should be filed on https://github.com/angular/angular-cli/issues, could you do that please?

**Comment by Igor-Maf** [comment]
@alexeagle 
I looked by search before I added this issue. I not saw the same issue there. It`s not a critical problem, I only thought that you need to know about it, that`s all

**Comment by Igor-Maf** [comment]
@alexeagle 
Yes, sure
