### ISSUE TITLE
ControlValueAccessor. WriteValue call after component destoyed

### ISSUE THREAD

**Issue by sergey-malykh** [angular/angular#21434]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

After I hide and show my input-control a few times, writeValue will call a few times too. Although component destoyed and reinit each time with ngIf

## Expected behavior

WriteValue call on the current control only

## Minimal reproduction of the problem with instructions

https://embed.plnkr.co/sCWAesnJtufDn1rBA208/

## Environment

<pre><code>
Angular version: 5.1.0

Browser:
- [ x ] Chrome (desktop) version 63
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kara** [comment]
@sergey-malykh In template-driven forms, the form is "driven" by the template. So if you remove a form directive from the template, its associated control is removed as well. In your plunker, you're using reactive forms, in which the direction is inverted. It's driven by your form control model, not what's present in the template. So it's expected that removing a form directive from the DOM does *not* destroy the associated control or its value updates.

**Comment by sergey-malykh** [comment]
@kara If it's not bug. Could you explain me how can I fix it?
And though I don't use [(ngModel)] at all, behavior repeat again
`<input [(ngModel)]=value (ngModelChange)="onChange($event)">`
change on
`<input>`
[https://embed.plnkr.co/ITd7ZZlTandD2NPJhkBb/](url)

> So it's expected that removing a form directive from the DOM does not destroy the associated control or its value updates.

How can I remove associated control?

Thank you so much in advance

**Comment by maxime1992** [comment]
There's definitely a bug. CF all the realted issue that I've [listed](https://github.com/angular/angular/issues/27803#issuecomment-451975496).
