### ISSUE TITLE
ERROR in b1ca7333.chunk.js from UglifyJs

### ISSUE THREAD

**Issue by Nikkypatel** [angular/angular#21441]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

my ng-lint run successfully but ng-build --prod give me error at build time, & serve working fine,
@build prod time it has give me error of uglify.js token(name) undefined else or not-found,
i used es7
## Expected behavior

need no error from unglify after a ng-lint successfully run.

## Environment
--prod --aot
<pre><code>
Angular version: 5.0.0

Browser:
- [ x ] Chrome (desktop) version 63.0.3239.84
- [  ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.2  
- Platform:Mac  

Others:

ERROR in 19.4fcd3e80c5dbb1ca7333.chunk.js from UglifyJs
Unexpected token: name (Dom7) [19.4fcd3e80c5dbb1ca7333.chunk.js:153,6]
</code></pre>

**Comment by alexeagle** [comment]
Please file this issue on https://github.com/angular/angular-cli/issues instead
