### ISSUE TITLE
Unit tests fail based on random things (order, directory, content of following tests)

### ISSUE THREAD

**Issue by SuperCorks** [angular/angular#21445]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I'm getting this extremely weird behavior when I run my unit tests. There's this test that fails, giving me the following error:
`Error: Can't resolve all parameters for RestFunctionFactory: (?, ?)`

At first, I thought I had some cyclical dependency somewhere but that's not it. I know that because the same test passes when it's not followed by tests from my other test files, or when I move tests files from one directory to another, or when I change the content of some other test files (bare in mind, the test that fails is not the one I'm moving or editing). Below you can find a video of the current behavior as I don't know how to explain it simply.

## Minimal reproduction of the problem with instructions
Run `ng test` in my project's root.

[Watch this video to understand.](https://drive.google.com/open?id=1vknZuUDKl8cT8v9hgyTodpTvdbV6XaKp)

[Here's a link to the project code to dowload](https://drive.google.com/file/d/1Ke0kOAbtJ_MutnrpYHamVH5kI3tKfojV/view?usp=sharing)

## What is the motivation / use case for changing the behavior?

I feel it might be a bug in the testing process.

## Environment

<pre><code>
Angular version: 5.1.3

Browser:
- [ x ] Chrome (desktop) version 63.0.3239.132
 
For Tooling issues:
- Platform:  Windows

Others:

Please help, I'd like to know if this bug is caused by my code or if it's just some random bug in the testing integration.
</code></pre>

**Comment by Toxicable** [comment]
It's likely your application code
Im not going to debug your entire application, if you have a specific which you want to report please make a minimal reproduction of that.

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
