### ISSUE TITLE
HttpClient Interceptor HttpErrorResponse object doesn't contain response from backend

### ISSUE THREAD

**Issue by CHAZTATS** [angular/angular#21442]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have a java backend which returns and error but I have no access to the response body in my HttpInterceptor.

The backend returns an object that looks like this:
![screen shot 2018-01-10 at 12 21 36](https://user-images.githubusercontent.com/18442675/34772697-e03bead2-f600-11e7-8c78-4331aa5c23a2.png)

With these errors in the console:

![screen shot 2018-01-10 at 12 21 46](https://user-images.githubusercontent.com/18442675/34772878-8cf3df28-f601-11e7-8b1e-418b7dbeeff3.png)

However in my HttpInterceptor:

<pre><code>
@Injectable()
export class ErrorHandlingInterceptor implements HttpInterceptor {
  intercept(req: HttpRequest&lt;any&gt;, next: HttpHandler): Observable&lt;HttpEvent&lt;any&gt;&gt; {
    return next.handle(req)
      .do(
      (event: HttpEvent&lt;any&gt;) => {
        console.log(event);
      }
      )
      .catch(err => {
        console.log('Caught error', err);
        return Observable.throw(err);
      });
  }
}
</code></pre>

The object I get doesn't contain any reference to this response.

![screen shot 2018-01-10 at 12 25 47](https://user-images.githubusercontent.com/18442675/34772850-702a7cda-f601-11e7-9966-f2ecae86985b.png)

## Expected behavior
The HttpErrorResponse object should contain the actual response returned from the request.

## Minimal reproduction of the problem with instructions
Make a failing request to a back end which returns a body with a HttpInterceptor.
Check contents of HttpErrorResponse in interceptor.

## What is the motivation / use case for changing the behavior?
To provide correct error handling.

## Environment

<pre><code>
Angular version: 5.1.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.3
- Platform:  Mac

Others:

</code></pre>

**Comment by laptransang** [comment]
I see it missing return event, you change change intercept method like this

  ```javascript
  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return next.handle(request)
      .map((event: HttpEvent<any>) => {
        if (event instanceof HttpResponse) {
          return event;
        }
      })
      .catch((error: any) => {
        if (error instanceof HttpErrorResponse) {

          this.handleError(error);

        } else {
          // return Observable.throw(error);
          return Observable.throw(error);
        }
      });
  }
  ```

**Comment by martinsik** [comment]
I think this doesn't look like a bug. It seems like the [response is blocked by the browser because of COSR](https://user-images.githubusercontent.com/18442675/34772878-8cf3df28-f601-11e7-8b1e-418b7dbeeff3.png) and that's why you see `HttpErrorResponse` with `status: 0`. If the backend fails with eg. `500` you'll have response body in the `error` property. Like here for example: https://stackblitz.com/edit/angular-lbwure?file=app%2Fapp.component.ts

When `status` is `0` it should mean there was a network layer error (that should I guess include CORS?) as described here in the code https://github.com/angular/angular/blob/master/packages/common/http/src/xhr.ts#L231-L241

**Comment by alxhub** [comment]
I agree with @martinsik' assessment - this looks like a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) issue, not an Angular one.
