### ISSUE TITLE
run aio e2e tests in --prod mode to catch optimization issues

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21446]
## Current behavior

We currently run aio e2e tests against dev builds of the app which means that if there is any issue introduced via build optimizations, we won't catch it via CI. This is a problem that could result in us shipping broken code to prod as almost happened in #21351.

## Expected behavior

We should be running all or at least a subset of e2e tests against the prod builds.

**Comment by IgorMinar** [comment]
We just experienced 17min outage in production because #21350 got merged (introducing a build optimizer related regression) before #21351 (which contained a fix for it).

We should prioritize fixing this over more feature work otherwise we risk more outages.

**Comment by gkalpak** [comment]
Is there any reason not to run all tests in prod mode?
Are there issues that might only appear in dev mode?
