### ISSUE TITLE
Why can't I add dependencies to the Injector through smart service? 

### ISSUE THREAD

**Issue by splincode** [angular/angular#21443]
Can not inject services ActivatedRoute, Route. 

## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
```
Maximum call stack size exceeded
```

If you specify all the dependencies declaratively in app.module.ts

```typescript
...
providers: [
    DataService,
    [
      {
        provide: ErrorHandler, 
        useClass: ExceptionService,
        deps: [ActivatedRoute, Router] 
      }
    ]
  ],
...
```

```
Cannot instantiate cyclic dependency! 
ApplicationRef ("[ERROR ->]"): 
in NgModule AppModule in ./AppModule@-1:-1
```

## Expected behavior
The ExceptionService class should work and display an error message

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-buw3dx?file=app%2Fexception.service.ts

## What is the motivation / use case for changing the behavior?
I want to use the parent class (smart service) to prescribe basic services in it

## Environment

<pre><code>Angular version: 5.1.3

**Comment by dawidgarus** [comment]
Router or one of its dependency depends on ErrorHandler, hence cyclic dependency.
When You trying to use injector you get infinite loop - ExceptionService is trying to create Router, which is trying to create ExceptionService.
If You really wan't to have Router in ExceptionService You can inject then both in modules and set it manually:
```ts
@NgModule(...)
export class AppModule {
  constructor(router: Router, handler: ErrorHandler) {
    if (handler instanceof ExceptionService) {
      handler.router = router;
    }
  }
}
```
Also, You can't have ActivatedRoute in singletons - it's only available for components.

**Comment by splincode** [comment]
But this works if you use a getter. This is bad? How can I even figure out where and when the code will regress, if in my case, now everything is working

```
import { Injector, Inject } from "@angular/core";
import { HttpClient } from "@angular/common/http";
import { DataService } from "./data.service";
import {ActivatedRoute, Router} from "@angular/router";

export abstract class BaseInjector {

    constructor(protected context: Injector) { 
      console.debug(context);
    }

    protected get router(): Router {
      return this.context.get(Router);
    }
    protected get route(): ActivatedRoute {
      return this.context.get(ActivatedRoute);
    }

}

export abstract class SmartService extends BaseInjector {
    
  protected data: DataService;

  constructor(context: Injector) {
    super(context);
    this.data = context.get(DataService);
  }

}
```

**Comment by dawidgarus** [comment]
@splincode 
- it's inefficient to use context.get every time
- it won't work if You try to use router/route in constructor - you will have infinite loop seemingly for no reason
- don't use Injector at all - it's dangerous and generally bad idea. And You can't use annotations like `@Host` or `@SkipSelf`
- You still can't use ActivatedRoute in singleton. It will throw when You try to get route.

**Comment by splincode** [comment]
> it's inefficient to use context.get every time

What do you mean?

**Comment by jasonaden** [comment]
@splincode You opened this issue yesterday and it was closed as a support request. You used the issue template this time, but again this is a support request. You need to bring these over to StackOverflow, not create Github issues.
