### ISSUE TITLE
Should be possible to select language/locale at runtime, affecting pipes, i18n codes etc

### ISSUE THREAD

**Issue by davidkarlsen** [angular/angular#21447]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Current situation is that you are restricted to statically building for one given target locale:
https://angular.io/guide/i18n - instead it should be possible to select (and change) the locale at runtime. Addons like: https://github.com/ngx-translate/core exist to circumvent this.

## Expected behavior
Be able to select locale at runtime, this should influence LOCALE_ID, so that pipes, i18n labels etc are affected.

## What is the motivation / use case for changing the behavior?
It is not unusual to have to provide the user with a chosen locale option. Usually default chosen by browser accept language: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html - but should be overridable. For my organization it is an UX requirement to provide the user with a set of languages to choose from, and it should take effect immediately.

## Environment

<pre><code>
Angular version: 5.1.3

Browser:
Should apply for any browser on any platform.

Others:

**Comment by vicb** [comment]
Closing because this is already mentioned in other i18n issues.

The next iteration of the i18n component should make this easier (/possible). It's clear if the core team will develop this functionality as this is not a requirement we have internally - if not it could be a community effort.

**Comment by davidkarlsen** [comment]
Is the next iteration 5.3 (or 6.x?) series?

**Comment by shobhit12345** [comment]
Hi 

How we can switch between language using Angular i18n feature ? I need to show one toggle button in my application for switching

**Comment by jlberrocal** [comment]
@shobhit12345 currently is not possible with i18n native implementation, you should try with a 3rd party library such us ngx-translate

**Comment by lizzymendivil** [comment]
What about using angular i18n with express server so that you can switch between languages? 
is it a good workaround?
