### ISSUE TITLE
docs(aio): NgClass setter misses part of signature containing "{"

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular#21451]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

https://angular.io/api/common/NgClass

Look at ngClass setter (I just assumed the problem is in the "{")

![image](https://user-images.githubusercontent.com/13039652/34790953-3ce7a296-f622-11e7-8129-8d57f4d87c48.png)

(This may happen in other signatures)

## Expected behavior

To look like it's in the source code ;D

https://github.com/angular/angular/blob/fc3e7e0381a44009492f60fa8bd77fd35e60ec2e/packages/common/src/directives/ng_class.ts#L59

## What is the motivation / use case for changing the behavior?

Improve documentation :D !!

(PS: I have the feeling this is a dup, but I'm not 100% sure. If it is feel free to close it)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by petebacondarwin** [comment]
Good spot @ericmartinezr - this is a problem with our doc-gen. I will look into it.

**Comment by petebacondarwin** [comment]
This is fixed by #21609. See https://pr21609-55da20e.ngbuilds.io/api/common/NgClass#ngClass

**Comment by IgorMinar** [comment]
fyi - the fix was moved to #21874 which hasn't landed yet.

**Comment by gkalpak** [comment]
Fixed.
