### ISSUE TITLE
resetForm issue when binding to an object

### ISSUE THREAD

**Issue by aec4444** [angular/angular#21452]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When you have a model as an object on your component, and you call resetForm(this.model), all of your fields are clear and won't take the values from your model.
In the example I give, there are 2 forms.  One has 2 single values bound to input controls.  The name of the variables MATCH the name of the input controls.  On the second form, this is not the case.  You'll see when you clear form 1, all works, but when you clear form 2, it expects a FLAT structure instead of a object.

Also, when resetting the form, ng-submitted is not cleared from the form, while the submitted flag on NgForm is cleared.

## Expected behavior

It's expected that values of the model will be used when resetting the form.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/46PwwYiyTg6hRbri3VqX

## What is the motivation / use case for changing the behavior?

Attempting to code an undo button on my app

## Environment

<pre><code>
Angular version: 5.1.3

Browser:
- [X ] Chrome (desktop) version 63
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kara** [comment]
This is working as expected. `reset` expects a value with a structure that matches the control structure of the form (e.g. whatever you put in the `name` attribute in your template). Otherwise, the forms API has no way of knowing which value should go to which control.

It's also worth noting that Angular 2+ does not set an "ng-submitted" class, so it's not expected that it would remove one.

**Comment by aec4444** [comment]
I have to look into how it’s being set then because it’s being set on submit. 

I think we are too quick to close this one.  If this is how it’s expected then it’s a bug in the design.   I have a work around but anyone with a complex object for a model can no longer use resetform without the work around I have that calls for setting the new model, callingnchange detedtion and then using this.form.value.
