### ISSUE TITLE
Angular 5x Animation Issue / Experts needed (Parent-Child Components)

### ISSUE THREAD

**Issue by olivermuc** [angular/angular#21464]
I'm counting on you experts, as I've spend roughly a full day trying to get a nested parent - child component setup working that uses ***ngIf** to show/hide child components. 
All in vain, and desperately seeking advice.

_(Note, all code snippets below is "simplified" code)_

Here is what I would like to do:
```
<parent (swipe)="swipeHandler()">
   <child *ngIf="isActive === child1">1</child>
   <child *ngIf="isActive === child2">2</child>
   <child *ngIf="isActive === child3">3</child>
</parent>
```
**The goal:** 
Depending on wipe left or right, the currently active child slides out to the left or right (counter direction). 
The newly made active child should slide in following the swipe direction.

**The challenge:**
Telling the child comp from which direction to slide in or out.

**The crux:**
The child animation is determined by the parent, henec the million dollar questions are, how do I either:
- tell the child's (@HostBinding) animation variable which value/state it should consider *in time* so once the *ngIf kicks in, the child animates correctly (_coding attempt below_)
- or setup a nested animation declaration in the parent that manages proper (parameterized) child animations 

I've tried various versions, none worked out really.
In some cases I ran again and again in funny errors `Error: Found the synthetic property @slide. Please include either "BrowserAnimationsModule"`. 
In other cases just nothing happened.

Below, simplified code, what am I missing?
Note: I have had no issues getting ***ngFor** (parent and child) elements animated in a parent hosted nested (using query()...) animation declaration block.

This however looks like a different beast to tame:

```
@Component({
  selector: 'child',
  template: `<ng-content></ng-content>`
  animations: [
    trigger('childAnim', [
      transition('void => toLeft', [style({ opacity: 0, transform: 'translate3d(100%,0,0)' }), animate("0.3s ease-in", style({ opacity: 1, transform: 'translate3d(0,0,0)' }))]),
      transition('void => toRight', [style({ opacity: 0, transform: 'translate3d(-100%,0,0)' }), animate("0.3s ease-in", style({ opacity: 1, transform: 'translate3d(0,0,0)' }))]),
      transition(':leave', [style({ opacity: 1 }), animate("1s ease-out", style({ opacity: 0 }))])
    ])
]
})
export class ChildComp {
  @HostBinding('@childAnim') public childAnim = 'toLeft'; // Default <=== but must be overwritten my parent component! How??
  constructor() { }
}

@Component({
  selector: 'parent',
  template: `<ng-content></ng-content>`
})
export class ParentComp {
  
  public animDirection; // How to 'pass' this on to the child comp??
  
  constructor() { }

  swipeHandler(event){
    if(left)
      this.animDirection = 'toLeft';
    else
      this.animDirection = 'toRight';
  }
}
```

Thank you so much!

**Comment by alexeagle** [comment]
Note, we don't generally accept support requests on this issue tracker, do you suspect something needs to change in Angular?

**Comment by olivermuc** [comment]
Point taken. 

I have spent roughly a day and a half now, and taken into consideration that I managed to get all of the setups working fine as laid out in the official angular documentation on animate (and anitmateChild), I suspect that my above mentioned approach either isn‘t supported, or there indeed is a bug.

In short: it‘s a combination of: 2 custom components, with the parent component determining 
- which child is visible (*ngIf)
- the animation direction (=state) of the child

Either I am getting the error as mentioned above, or just nothing happens.

**Comment by denisyilmaz** [comment]
maybe this helps: give your child components states (prev / next / active) then set these states in the parent. the state can be places as an input value for the child component (setter/getter function) for the animation state value. AND: everything must happen before the isActive value is set as your component is already deleted from DOM when the new value arrives.

As far as I know the animation module only allows animations `void <=> *` or `:enter`/`:leave` for *ngIf

**Comment by olivermuc** [comment]
I tried that in various ways.

The timing is, as you rightly mentioned, is critical here and makes passing variables non trivial. 
Also, how do specifically suggest passing on that variable to the getter function?
By INPUT value (using @Input() to retrieve) is too late/slow.

Also, feeding a parent variable directly to the child’s @childAnim variable by setting @childAnim in the html template (not using the @Hostbinding()) didn’t work, as this causes the dreaded 
`Error: Found the synthetic property @slide. Please include either "BrowserAnimationsModule"`

Thank you though, appreciate the thought.

**Comment by olivermuc** [comment]
Here is the solution:

```
<parent (swipe)="swipeHandler()" #parent>
	<child *ngIf="isActive === child1" [animDirection]="parent._animateDir">
			Some content.
	</child>
```

**#parent** needed to be set and referenced in its own child comp reference.
Make sure to use setTimeout on changing the `*ngIf="isActive` variable to allow for the child comp to update the input val.
