### ISSUE TITLE
Can't catch the exception from ActivatedRoute.queryParams when using % in the URL - causes app to crash

### ISSUE THREAD

**Issue by shmaram** [angular/angular#21468]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Using ActivatedRoute.queryParams with url the includes % it throws an exception that can't be catched anywhere and causing the app to crash.

## Expected behavior

To be able to catch this kind of error and to be able to keep working with the app

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
go to : https://embed.plnkr.co/tUMGOtW39iMDYKHcv1hm/
then add layout=!@#$%^&*() so that the new URL will be 
https://embed.plnkr.co/tUMGOtW39iMDYKHcv1hm/?layout=!@#$%^&*()

Error found : 
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Ye (vendor.6b9be0480d04ab9c9c6c.js:6)
    at tn.$$parse (vendor.6b9be0480d04ab9c9c6c.js:6)
    at tn.$$parseLinkUrl (vendor.6b9be0480d04ab9c9c6c.js:6)
    at an.$get (vendor.6b9be0480d04ab9c9c6c.js:6)
    at Object.a [as invoke] (vendor.6b9be0480d04ab9c9c6c.js:6)
    at vendor.6b9be0480d04ab9c9c6c.js:6
    at r (vendor.6b9be0480d04ab9c9c6c.js:6)
    at i (vendor.6b9be0480d04ab9c9c6c.js:6)
    at Object.a [as invoke] (vendor.6b9be0480d04ab9c9c6c.js:6)

## What is the motivation / use case for changing the behavior?

By fixing this issue adding % in the URL will not crush the application 

## Environment

<pre><code>
Angular version: 4.0.0

Browser:
- [ X ] Chrome (desktop) version 63.0.3239.132
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sod** [comment]
Still an issue / angular 5.2.3.

In angular.js [the router parses the uri component in a try/catch](https://github.com/angular/angular.js/blob/e3ece2fad9e1e6d47b5f06815ff186d7e6f44948/src/Angular.js#L1395-L1433), thus ignoring invalid parts of the URL.

[angular 5 doesn't try/catch](https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/router/src/url_tree.ts#L348-L350). If decodeURIComponent throws (just like `decodeURIComponent('%')` does), then the app stops functioning.

**Comment by muriloqr** [comment]
Still an issue for me, here is the workaround:

import { UrlTree ,DefaultUrlSerializer, UrlSerializer } from '@angular/router';

export class cleanUrlSerializer extends DefaultUrlSerializer {
public parse(url: string): UrlTree {
  function cleanUrl(url) {
      return unescape(url);
  }
 
  return super.parse(cleanUrl(url));
  }
}

Providers:

{
   provide: UrlSerializer,
   useClass: cleanUrlSerializer
},

**Comment by muriloqr** [comment]
Still an issue for me, here is the workaround:

```
import { UrlTree ,DefaultUrlSerializer, UrlSerializer } from '@angular/router';

export class cleanUrlSerializer extends DefaultUrlSerializer {
public parse(url: string): UrlTree {
  function cleanUrl(url) {
      return unescape(url);
  }
 
  return super.parse(cleanUrl(url));
  }
}
```

Add provider:

```
{
  provide: UrlSerializer,
  useClass: cleanUrlSerializer
}
```
