### ISSUE TITLE
compiler-cli 5.2 does not emit common/http.ngsummary.js

### ISSUE THREAD

**Issue by Quramy** [angular/angular#21466]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

compiler-cli with `enableSummariesForJit` don't emit `node_modules/@angular/common/http/http.ngsummary.js`

## Minimal reproduction of the problem with instructions

I created reproducing repo, see https://github.com/Quramy/repro-summary-missing

## Environment

<pre><code>
Angular version: 5.2.0

TypeScript: 2.6.0
 
For Tooling issues:
- Node version: v8.9.1  
- Platform:  macOS Sierra (10.12.6)

Others:

</code></pre>

**Comment by JoostK** [comment]
I am unable to reproduce in the original repro using Angular 5.2 (on macOS). Given that Ivy no longer works with summary nor factory files, this should no longer be an issue today.
