### ISSUE TITLE
$http.get are not sent in IE10

### ISSUE THREAD

**Issue by amirduran** [angular/angular#21467]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have developed an angular 2 application which perfectly works with Chrome, Firefox and IE 11. When I run my application in IE 10, application loads without any problems, dashboard page is displayed but data is never loaded from the server (for example, latest posts are not displayed on dashboard page). After some investigation I have realised that $http.get requests are never sent to the server and that is why my content is never filled. 

The same application is working correctly under IE 11 where $http.get requests are immediately sent and content is loaded.

## Expected behavior

$http.get requests should be sent on IE10 too when application starts.

## Minimal reproduction of the problem with instructions

Angular 2 application will not send automatically $http.get request in IE10 like in IE11, Chrome or Firefox.

## Environment

<pre><code>
Angular version: 4.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 10
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.5 
- Platform:  Mac
</pre></code>
Others:
```
"@angular/animations": "4.0.0",
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/router": "4.0.0",
    "@ngrx/core": "1.2.0",
    "@ngrx/effects": "2.0.4",
    "@ngrx/store": "2.2.3",
    "@ngrx/store-devtools": "3.2.4",
    "@ngtools/webpack": "1.7.2",
    "@ngui/datetime-picker": "0.16.2",
    "@ngx-translate/core": "6.0.1",
    "@swimlane/ngx-datatable": "9.3.1",
    "angular-pipes": "2.3.1",
    "angular2-autosize": "1.0.2",
    "angular2-moment": "1.7.0",
```

Here is my AppHttp class that extends Http class:

```
import { Observable, Subject } from 'rxjs';
import { Http, Request, RequestOptionsArgs, Response, RequestOptions, ConnectionBackend, Headers } from '@angular/http';
import 'rxjs/add/operator/filter';
import { Injectable } from '@angular/core';


@Injectable()
export class AppHttp extends Http {

    private _badResponseStream:Subject<any>;
    public badResponseStream:Observable<any>;

    constructor(
        backend: ConnectionBackend,
        defaultOptions: RequestOptions) {

        super(backend, defaultOptions);

        this._badResponseStream = new Subject<Response>();
        this.badResponseStream = new Observable<Response>( observer => this._badResponseStream.subscribe(observer));
    }

    intercept(observable: Observable<Response>): Observable<Response> {
        return observable.catch(err => {
            this._badResponseStream.next(err);
            return Observable.of(null);
        });
    }

    request(url: string | Request, options?: RequestOptionsArgs): Observable<Response> {
        return super.request(url, options);
    }

    get(url: string, options?: RequestOptionsArgs): Observable<Response> {
        return this.intercept(super.get(url,options));
    }

    post(url: string, body: string, options?: RequestOptionsArgs): Observable<Response> {
        return this.intercept(super.post(url, body, this.getRequestOptionArgs(options)));
    }

    put(url: string, body: string, options?: RequestOptionsArgs): Observable<Response> {
        return this.intercept(super.put(url, body, this.getRequestOptionArgs(options)));
    }

    delete(url: string, options?: RequestOptionsArgs): Observable<Response> {
        return this.intercept(super.delete(url, options));
    }

    getRequestOptionArgs(options?: RequestOptionsArgs) : RequestOptionsArgs {
        if (options == null) {
            options = new RequestOptions();
        }
        if (options.headers == null) {
            options.headers = new Headers();
        }
        options.headers.append('content-Type', 'application/x-www-form-urlencoded');
        return options;
    }
}
```

This class is then used in services to perform HTTP calls.

**Comment by alxhub** [comment]
Extending `Http` is not a supported use case, and the `Http` API itself is deprecated. Please switch to using `HttpClient` and `HttpInterceptor` instead.
