### ISSUE TITLE
Please add a @NgModule annotation error for an angular library when trying to build using aot.

### ISSUE THREAD

**Issue by keephacking** [angular/angular#21478]
you can find detailed information in
https://stackoverflow.com/questions/48207706/ionic-scrolling-header-package-issue-inbuilding-using-prod

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

...
