### ISSUE TITLE
Webpack Compilation issue with Angular 4.4.6

### ISSUE THREAD

**Issue by trextroy** [angular/angular#21482]
Hi, I am using below dependencies with webpack. 
"@angular/common": "4.4.6",
    "@angular/compiler": "4.4.6",
    "@angular/core": "4.4.6",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/platform-browser": "4.4.6",
    "@angular/platform-browser-dynamic": "4.4.6",
    "@angular/router": "4.4.6",
    "@angularclass/hmr": "1.2.2",

Along with node 8.9.4 and npm 5.6.0. 

I came accross below issue while compiling with webpack. 

WARNING in ./~/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression

WARNING in ./~/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 542 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 1.66 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 301 kB [entry] [rendered]

I tried to follow couple of similar post but nothing is helpful so far. Please help.

**Comment by alexeagle** [comment]
Sorry, we don't handle user support on the github issue tracker. You could try the angular channel on gitter or stackoverflow.
