### ISSUE TITLE
NgModel.viewToModelUpdate not works when define a Form Control on Input

### ISSUE THREAD

**Issue by kamuran21** [angular/angular#21483]
I want to change view and model data on an input with onBlur event by a directive but, when I want to define a form control on input, `this.ngModel.viewToModelUpdate` does not impact to the model. It seen ignore this function and set the model as string. How can I update model as number?

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`ngModel.viewToModelUpdate` does not update model.

## Expected behavior

`ngModel.viewToModelUpdate` updates model.

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/tG6IZls2prko9b89nLah?p=preview

## Environment

<pre><code>
Angular version: 4

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.3
 
- Platform: windows 10  

Others:

</code></pre>

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
