### ISSUE TITLE
merge status should be in the pending state when any of the other commit statuses are pending

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21497]
Currently it's the merge status supports only the "success" or "fail" status.

When CI tests are in progress, we should set the "merge status" to "pending".

**Comment by alexeagle** [comment]
should the merge status from the bot ever differ from the PR status from github plus the merge label?

**Comment by IgorMinar** [comment]
I don't think so

**Comment by IgorMinar** [comment]
Isn't that what I'm proposing?

**Comment by ocombe** [comment]
If any check is failing: status failing
If all checks are pending or successful + pending: status pending
If all checks are successful: status successful

**Comment by IgorMinar** [comment]
Correct + label requirements
