### ISSUE TITLE
Router doesn't insert component into a named router-outlet when a route has non-empty path

### ISSUE THREAD

**Issue by maxkorz** [angular/angular#21490]
## I'm submitting a...

<pre><code>[x] Bug report
</code></pre>

## Current behavior

Router doesn't insert component into a named `router-outlet` when a route has non-empty `path`.

## Expected behavior

Component should be loaded into a named `router-outlet` if `path` matches current URL.

## Minimal reproduction of the problem with instructions
Not working demo: http://plnkr.co/edit/JphG0Vj95BCy3c6xjcXr?p=preview

If I remove everything from "path" the named outlet works fine
Working demo: http://plnkr.co/edit/rFmP8MwIXuJ7VVaepjwY?p=preview

## What is the motivation / use case for changing the behavior?
It's not possible to access passed params in component loaded in named `outlet`.

## Environment
<pre><code>Angular CLI: 1.6.3
Node: 9.1.0
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.5.3
webpack: 3.10.0
</code></pre>

Maybe these issues are related:
https://github.com/angular/angular/issues/12265
https://github.com/angular/angular/issues/16406

**Comment by wangzhenhui1992** [comment]
I'm going with the some problem.
My code is like this
`<router-outlet style="width:100%"></router-outlet>`
and component's below:
`<div style="width:100%"><h1>Title</h1></div>`
but the html comes out like below:
`<router-outlet></outlet>
 <app-component>
    <div style="width:100%"><h1>Title</h1></div>
 </app-component>
`
So , the layout of the div is not go with the  width of 100% .
How can i solve it?

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

<hr>

I think what you want is a componentless route. This is the way of inheriting params from a parent component, and you can use pathless configurations in the children. Something like this:

http://plnkr.co/edit/XpwkNsodkwYamythkKrJ?p=preview

**Comment by diegocurbelo12** [comment]
Hi all, after a few hours trying to solve, this post solve my issue...
https://www.bennadel.com/blog/3346-named-outlets-require-non-empty-parent-route-segment-paths-in-angular-4-4-4.htm

Regards,
Diego

**Comment by willyboy** [comment]
I don't think this behavior should be expected. An empty route usually implies "index" so we can default to "index" without having anything in the route. Imagine you have a landing page with a modal that you use a router outlet to implement. You shouldn't have to redirect someone to /index just so you can show a modal.
