### ISSUE TITLE
merge status not updated after a flakey CI job restart

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21496]
I had a PR that was almost green, except for one failing travis job. I went ahead and restarted the job. It went green but the merge status didn't get updated:

<img width="899" alt="screen shot 2018-01-11 at 6 04 22 pm" src="https://user-images.githubusercontent.com/216296/34856464-12f0d718-f6fa-11e7-8bb9-6e8dc5de28cb.png">

**Comment by ocombe** [comment]
Yes I've noticed that as well, either forcepushing doesn't trigger a status check, or the merge status isn't updated properly. I'll investigate

**Comment by IgorMinar** [comment]
Another one https://github.com/angular/angular/pull/21474

**Comment by ocombe** [comment]
Ok I've found the bug, it was not matching correctly status updates to existing PRs from the database.
If one the PRs is in this case, the simplest way to fix it is to restart one of the travis build jobs (the bazel job that only takes 6mn and is a good candidate).
I'll go around and try to restart it on all PRs affected

**Comment by IgorMinar** [comment]
From your message it's not clear if you are just providing a workaround or if the issue is fixed for all new PRs. Can you please clarify?
