### ISSUE TITLE
DatePipe interprets ISO8601 in incorrect way on Safari/iOS

### ISSUE THREAD

**Issue by jirkafajfr** [angular/angular#21491]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I pass ISO8601 without timezone specification to _DatePipe_ it interprets it as local timezone in Edge/Explorer/Chrome and Firefox but Safari assumes UTC.

### Problem demonstrator
https://embed.plnkr.co/ylAn93B6FbCBsCYZGp9X/

#### Edge/Explorer/Chrome and Firefox Output - correct
```
(local) 2018-01-11T13:00:00 >> (local) 1:00 PM
(UTC) 2018-01-11T13:00:00Z >> (UTC) 7:00 AM
```

#### Safari/iOS - incorrect
```
(local) 2018-01-11T13:00:00 >> (local) 7:00 AM
(UTC) 2018-01-11T13:00:00Z >> (UTC) 7:00 AM
```

## Expected behavior
Safari/iOS should interpret _2018-01-11T13:00:00_ as _1:00 PM_ in CST timezone

## Minimal reproduction of the problem with instructions
https://embed.plnkr.co/ylAn93B6FbCBsCYZGp9X/

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [X] Safari (desktop) version 10.13
- [X] Safari (iOS) version 11.2.1
- [ ] IE version XX
- [ ] Edge version XX
 
Others:
My timezone is CST -6:00
Locale is set to en_US
</code></pre>

**Comment by vicb** [comment]
I confirm that this does not behave the same in Safari vs Chrome.
@ocombe please take a look at this.
