### ISSUE TITLE
Dynamic compilation of angular modules at run time from external UMD bundles

### ISSUE THREAD

**Issue by snarun** [angular/angular#21498]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Dynamic compilation of angular modules during application run time from UMD bundles or ES5 bundles is not possible, as the decorators are missing or is not arranged as per angular compiler expectations. This leads to errors such as **No NgModule metadata found for ABCModule** or **Please add a @Pipe/@Directive/@Component annotation**

## Expected behavior
To achieve the true pluggable scenarios, Angular modules should be dynamically build from UMD bundles or ES5 files using JITCompiler at run time. 

## Minimal reproduction of the problem with instructions
Build an angular app and generate the bundles as per angular package format. This will be the external bundle. Now load this bundle in another angular container app based on user action. Please note that the container app is running in Webpack production configuration and System.js is loaded on top of it for the dynamic support. The usage is shown below::
```javascript
SystemJS.import('http://localhost:3000/plugins/ABCplugin.umd.js').then((plugin: any) => {
     this.compiler.compileModuleAndAllComponentsAsync(plugin['ABCModule']).then((compiled: any) => 
      {   
        // component instantiation and rendering goes here...
      })
 }).catch(function (err: any) { console.error(err); });
```

## What is the motivation / use case for changing the behavior?
Most of the business scenarios, demands dynamic plugins. Also, It is not feasible always to do an upfront composition of the modules, at the cost of deployment efforts. We need some mechanism to support the decentralized application development

## Environment

<pre><code>
Angular version: 4.4.6

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 6.11.0
- Platform:  Windows

Others:

</code></pre>

**Comment by Toxicable** [comment]
I think what you're after is Angular Elements

**Comment by mlc-mlapis** [comment]
@snarun ... can you explain why you need that way of dynamic behavior at all when all of them are just static things and you can do that ahead of time?

**Comment by snarun** [comment]
Ahead of time might not work in building composite solutions, especially in the given context. Let me explain.

Look at the way of building a composite solution with different teams. A composite app in the current context has a container app and a set of functionalities in the form of bundles (as per angular package format).  Geographically separated teams are responsible for providing the functionalities in the form of  bundles and the Container app consumes it based on user actions.  Individual bundles adheres to OSGi module standards by associating the metadata of the bundle. (like, the module and component names)

In an ideal context, the container app should download and instantiate the bundles as per user request. All it needs is the OSGi specific metadata associated to the bundle, to know the module and component information.

As angular as a framework doesn't support this (whereas other JavaScript libraries supports. For e.g. React, Backbone etc.), its current context forces the container app to compose these bundles upfront using hard references, route configurations and web pack build process for bundle optimizations, followed by deployment. However, this is not feasible always especially, when it comes to the build and deployment efforts associated to the container app.  **Why the container app should be rebuild again and again even for a small change in the bundle?**

We need an option to create the true dynamic plugins, and there by achieving the objective of creating highly modular Angular systems, as it isolates developers from change, empowers team to be more agile, allows organizations to change the way that they develop software.

**Comment by mlc-mlapis** [comment]
@snarun ... thanks for your explanation. 👍 The interesting is that you see the problem by the same way as I and I also agree with. This the way where Angular 6 is going also ... but right now we can do it immediately and we don't need JIT run-time compilation at all.

The only limitation which we need to accept is:

* separate the base of Angular standard libs outside of the apps to avoid duplication
* separated base Angular libs then use as they are ... just UMD modules loaded on-demand and take even advantages of caching o proxy servers or directly browsers caches
* or optimize them to get only minimum functionality which is needed by our apps and use then this shared lib instead of standard Angular libs (the same as CLI's tree-shake source code optimization)
* because of that shared lib or base Angular libs it is logical that it is necessary to be on the same version

* those module plugins can be fully compiled for AOT mode and bundled to any combinations or just using a schema 1 module = 1 bundle, ...
* load those bundles fully programmatically when you want, so on-demand

* and keep the metadata in some form (metadata to know what is what and where) directly in apps' code or create a separate and remote abstraction and logic (probably as some registration records of those module) on a server/s where applications can read that
* having those metadata as a part of those bundles is probably inefficient because you have a problem to understand what is what and where before you load them.

**Comment by snarun** [comment]
@mlc-mlapis ... Thank you! :+1: 

> On separate the base of Angular standard libs outside of the apps to avoid duplication.

Even I also felt the same, that instance check of NgModule is failing due to duplication of Angular modules, as UMD bundles are self-contained and hence it fails at NgModule instance check.
```javascript
function _isNgModuleMetadata(obj) {
	return obj instanceof NgModule;	
}
```
> having those metadata as a part of those bundles is probably inefficient because you have a problem to understand what is what and where before you load them. 

Bundle owners register these information to a bundle registry and the container app consumes these info from the bundle registry through a CDN sort of delivery mechanism

I need to validate the rest of the steps you've mentioned. However, it is clear that available build techniques might not be a help , and it looks like its going to be a workaround.

Also, Can you confirm, whether Angular 6 is going in this direction?? or as @Toxicable  says... should we wait for Angular Elements??

**Comment by mlc-mlapis** [comment]
@snarun 

... ok, fine
> Bundle owners register these information to a bundle registry and the container app consumes these info from the bundle registry through a CDN sort of delivery mechanism.

... that seeing could depend probably on scope. For just fully Angular SPA application using Angular Elements doesn't have a lot of sense but for mixed environment yes.
> Also, Can you confirm, whether Angular 6 is going in this direction?? or as @Toxicable says... should we wait for Angular Elements?

... you many other options ... Closure Compiler & Bundler, Rollup, SystemJS Builder to mention only the most named ones.
> It is clear that available build techniques might not be a help , and it looks like its going to be a workaround.

**Comment by mlc-mlapis** [comment]
@snarun ... look also at:

export declare abstract class NgModuleFactoryLoader {
    abstract load(path: string): Promise<NgModuleFactory<any>>;
}
export declare function registerModuleFactory(id: string, factory: NgModuleFactory<any>): void;
export declare function clearModulesForTest(): void;
export declare function getModuleFactory(id: string): NgModuleFactory<any>;

**Comment by snarun** [comment]
Thank you!!.. I had taken another approach here, by writing a compiler, as webpack run time causes the issues by cleverly hiding the angular reference variables in its functional scopes.  In my scenario, it required modifications in webpack libraries as well... Angular Package format (APF) libraries remains intact.. but the compiler transforms the APF files to run time (webpack) recognizable form.

**Comment by IonIo** [comment]
Hi @snarun 

Could you post the solution on github? I mean the modifications that you made in webpack config. I did manage to succeed, but only with SystemJS and UMD format of the angular module. I give up tryning to make it work with Angular CLI

**Comment by Algatron** [comment]
I would also love to see this solution on github :D 
I also have this need, and I see many people posting about the same topic in various locations with no good answers. Sometimes angular elements, or dymanicly loaded components, or route-based components just doesn't work for plugin architectures

**Comment by Sushil1091Jes** [comment]
> Hi @snarun
> 
> Could you post the solution on GitHub? I mean the modifications that you made in webpack config. I did manage to succeed, but only with SystemJS and UMD format of the angular module. I give up trying to make it work with Angular CLI

HI@lonlo do u have solution of SystemJS with UMD format in github? I am stuck at build the library to UMD format.
