### ISSUE TITLE
How to use flexible views in 2.0

### ISSUE THREAD

**Issue by SanderElias** [angular/angular#215]
I have been reading a lot on 2.x. But I seem to miss something. At least, I don't see on how to do this in 2.x in its current state.
Lets say I have an feature in my application that is quite simple, but needs a couple of different views/templates to show the same data, just represented a bit different. In 1.x this is easy, just ngInclude a template, and you are done.
I created [a small demo](http://goo.gl/Ps4cpd) to show what I mean. The same data, just different views. With some pagination this kind of thing is a viable option. 
How would this look in 2.x? I mean, the best code, is the code you don't have to write. In 1.3 I need NO code to create this. For the 2.x version I don't see an option without writing a fair amount of code.

Or do I miss something obvious?
EDIT: updated the link to the right plunker.

**Comment by mhevery** [comment]
This will have to be done through Components in combination with switch. 

As there is no action item here, I am closing this.
