### ISSUE TITLE
Undesirable scroll bar appearing in the navbar when certain menu items are expanded

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21508]
repro: https://angular.io/guide/architecture

<img width="548" alt="screen shot 2018-01-12 at 8 18 56 am" src="https://user-images.githubusercontent.com/216296/34884361-57c4e452-f771-11e7-9bfa-7c7fef77e27a.png">

**Comment by gkalpak** [comment]
AFAICT, this is partly a duplicate of #17096. Last time I checked I couldn't find what is causing it (see https://github.com/angular/angular/issues/17096#issuecomment-306635627).
(Could it be a Chrome bug?)

**Comment by petebacondarwin** [comment]
I think it is worthwhile capturing this comment from the closed duplicate here: https://github.com/angular/angular/issues/23835#issuecomment-388286335

![image](https://user-images.githubusercontent.com/15655/39915823-d67f8e40-5500-11e8-9450-251c5d01d766.png)

**Comment by gkalpak** [comment]
FWIW, I don't see anything weird except for the fact that Chrome thinks the sidenav's content height is larger than it actually is. The rest of the behavior is normal/expected :grin:
(I still suspect it could be a Chrome bug - possibly related to FlexBox - but I could be wrong.)

**Comment by petebacondarwin** [comment]
Still a problem (on Chrome, Firefox and Safari) so perhaps it is not a browser bug?
In any case, can we live with this and close this issue @IgorMinar ?

**Comment by gkalpak** [comment]
I think I have found a fix: #26416 :tada:
