### ISSUE TITLE
fullTemplateTypeCheck error on property

### ISSUE THREAD

**Issue by schmitch** [angular/angular#21505]
Hello, currently I actually found the following error while activating the new angular compiler option:
```
ERROR in src/app/envisia/customer/box/customer-box.component.html(12,41): : Property 'id' does not exist on type 'Customer | { name: string; }'.
  Property 'id' does not exist on type '{ name: string; }'.
```

customer is of type `customer?: Customer | { name: string; }` .

While the code is:
```
  <div class="col-md-12 min" *ngIf="customer">
    <h4>
      <a *ngIf="customer.id"
         uiSref="a.crm.customer.detail" [uiParams]="{id: customer.id}"
         target="_blank"
         uib-tooltip="Kundenseite in neuem Fenster öffnen">
        {{ customer.name }}
      </a>
      <a *ngIf="!customer.id"
         uiSref="a.crm.redirect" [uiParams]="{name: escape(customer.name)}"
         target="_blank"
         uib-tooltip="Kundenseite in neuem Fenster öffnen">
        {{ customer.name }}
      </a>
    </h4>
```

currently `uiSref="a.crm.customer.detail" [uiParams]="{id: customer.id}"` is line 12.
I have other snippets where the same thing occurs. While on this snippet it might be the problem that the usage is on the same line as the *ngIf, I have a different snippet where it occurs differently:

```
    <address *ngIf="withAddress && customer?.invoice">
      {{ customer?.invoice.street }}<br>
      {{ customer?.invoice.zip}} {{ customer?.invoice.city }}<br>
    </address>
```

Raises:
```
src/app/envisia/customer/box/customer-box.component.html(25,55): : Property 'invoice' does not exist on type 'Customer | { name: string; }'.
  Property 'invoice' does not exist on type '{ name: string; }'.
src/app/envisia/customer/box/customer-box.component.html(26,41): : Property 'invoice' does not exist on type 'Customer | { name: string; }'.
  Property 'invoice' does not exist on type '{ name: string; }'.
src/app/envisia/customer/box/customer-box.component.html(26,41): : Property 'invoice' does not exist on type 'Customer | { name: string; }'.
  Property 'invoice' does not exist on type '{ name: string; }'.
```

actually`<address` ist line 25. using a `?` or not, has no further effect.

It's worse if I use a function as the *ngIf:
```
  isCustomerObj(obj?: Customer | { name: string } | null): boolean {
    return obj instanceof Customer;
  }
```

I didn't found a relevant Issue, but maybe I'm too dumb to found one :/ please close if appropriate and ask for more info if needed.

**Edit:** I think the issue are union types, because I have a different snippet where it works:
```
<div *ngIf="lastOffer">
      Aus Angebot:
      <ev-file-button [objId]="lastOffer.id" type="offer">
        {{ lastOffer.id }}
      </ev-file-button>
    </div>
```

Type is `lastOffer?: any;`

P.S.: This feature is amazing, if union types would work as well as the other stuff. I probably found at least 10 bugs already...

**Comment by vicb** [comment]
This should work (notice the `obj is Customer` return type):

```typescript
  isCustomerObj(obj?: Customer | { name: string } | null): obj is Customer {
    return obj instanceof Customer;
  }
```

Note that the typecheck feature is from TS, types are checked on the following code in your example (ngif gets transformed to if stamements):
```
// customer?: Customer | { name: string; }
if (customer) {
  if (customer.id) {
    // check the type of {id: customer.id}
  }
}
```

If TS is not able to resolve your types, the template type check will complain. In such case you can either refactor your code or last resort use `$any` (see https://github.com/angular/angular/pull/20968 for `$any`)
