### ISSUE TITLE
ngIf type narrowing feature does not work within "else" template

### ISSUE THREAD

**Issue by noemi-salaun** [angular/angular#21504]
Relative to #20967

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Compilation with option `fullTemplateTypeCheck` throw error `Object is possibly 'undefined'`

## Expected behavior
No error, because the `ngIf; else` can work as a guard

## Minimal reproduction of the problem with instructions

```ts
@Component({
  selector   : 'app-add-state',
  templateUrl: './add-state.component.html',
})
export class AddStateComponent {
  newState?: State
}
```

```html
<div *ngIf="!newState; else createdTemplate">
  <!-- Some code to create a new state... -->
</div>
<ng-template #createdTemplate>
  State {{ newState.name }} created
</ng-template>
```

**Comment by vicb** [comment]
A workaround until this is implemented is 

```
<ng-template #createdTemplate>
  State {{ $any(newState).name }} created
</ng-template>
```

**Comment by noemi-salaun** [comment]
I think the simplest workaround would be

```
{{ newState!.name }}
```

To tell TypeScript that it is not `null`.

But I wasn't looking for a workaround, I simply wanted to warn the Angular team about this issue.

**Comment by twittwer** [comment]
It seems to generally not working with ng-templates:
```ts
user?: { name: string }
```
```html
<ng-content *ngIf="user; then currentUser else loginButton"><ng-content>
<ng-template #currentUser>{{ user.name }}</ng-template> <!-- error -->
<ng-template #loginButton>...</ng-template>
```

**Comment by thw0rted** [comment]
@vicb I would argue that this is a bug, not a feature -- and now that label apparently matters because it triggered the vote-bot to show up.  (I think most users are going to wind up with strict templates by default sooner or later, so this is actually a pretty big deal.)

**Comment by Ulrikop** [comment]
hm, pretty old issue for such a bug. is there any news about this?

I would appreciate not having to use `$any` so that I can get good feedback about bugs as early as possible.

**Comment by JeanMeche** [comment]
This is now a solved issue with the new template synthax  : 
```
@if() {
 ...
} @else {
 ...
}

```
