### ISSUE TITLE
Pass custom animations to component instance

### ISSUE THREAD

**Issue by maximelafarie** [angular/angular#21507]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Let's say I have the following Angular 5+ component [from Angular docs](https://angular.io/guide/animations):
```
    @Component({
      selector: 'app-hero',
      template: `
        template code here...
      `,
      styleUrls: ['./hero-list.component.css'],
      animations: [
        trigger('heroState', [
          state('inactive', style({
            backgroundColor: '#eee',
            transform: 'scale(1)'
          })),
          state('active',   style({
            backgroundColor: '#cfd8dc',
            transform: 'scale(1.1)'
          })),
          transition('inactive => active', animate('100ms ease-in')),
          transition('active => inactive', animate('100ms ease-out'))
        ])
      ]
    })
    export class HeroListBasicComponent {
       @Input() heroes: Hero[];
    }
```
As the above example shows, `animations` are set inside the `@Component` decorator.

It could be useful to pass custom `animations` array to the element in order to make it use different animations depending on the one passed to the element instance (regardless of how to achieve that) for each or all component instance:

 - Custom service?
 - `@Input()`?
 - Global config script / variable / object?
 - localStorage variable

The last options seems to be working if doing this way:

Somewhere in the `AppModule`: 
```
localStorage.animations = [
   trigger('heroState', [
     state('inactive', style({
       backgroundColor: '#eee',
       transform: 'scale(1)'
     })),
     state('active',   style({
       backgroundColor: '#cfd8dc',
       transform: 'scale(1.1)'
     })),
     transition('inactive <=> active', animate('100ms ease-out'))
   ])
 ];
```

Then back in the component, use `localStorage.animations`:
```
    @Component({
      selector: 'app-hero',
      template: `
        template code here...
      `,
      styleUrls: ['./hero-list.component.css'],
      animations: localStorage.animations
    })
    export class HeroListBasicComponent {
       @Input() heroes: Hero[];
    }
```

## Expected behavior

Possibility to store the animations array somewhere in the app, and inject it / call it in the component.

E.g. (let's imagine the animations array is stored in a service or whatever, and the target component has an `@Input() animations;`): 
`<app-hero [animations]="myCustomAnimationArray"></app-hero>`

## Minimal reproduction of the problem with instructions
Can't reproduce it properly (only with `localStorage` as explained above).

## What is the motivation / use case for changing the behavior?
In my case, I have an [NPM library](https://github.com/biig-io/ngx-smart-modal) where [I'm using Angular animations in a component](https://github.com/biig-io/ngx-smart-modal/blob/master/src/ngx-smart-modal/src/components/ngx-smart-modal.component.ts). Users whom using it want to disable / customize this component animations by their own animations.

## Environment

<pre><code>
Angular version: 5.0.3

Browser:
- [X] All
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.10.0
- Platform:  Mac

Others:

</code></pre>

**Comment by Jasonkoolman** [comment]
Could this be addressed to the angular core team? Angular animations are very powerful in the hands of first-party users, but a pain to use for library developers. Implementing reusable UI components without having the option to configure animations is a bummer.

Abstraction should be key here. Angular animations provide a fluent API to create reusable animations of whatever complexity. Library developers shouldn't have to built custom implementations while we have this amazing tool sitting on the shelf. It's not an easy thing to do (right) and every library will have its own way of handling animations. I think the adoption rate of Angular animations will increase significantly if this feature gets implemented.

**Practical example**
I now use Angular animations by default - with the options to switch to CSS animations in case users want to use custom animations. The library offers multiple (reusable) for developers to use in their Angular application, but they **can't** pass them on to the components (think of a modal, tooltip or dropdown box). If this feature does not get through, I see no use in supporting Angular animations.

**Comment by Jasonkoolman** [comment]
@matsko @josephperrott Would you perhaps know of any workaround to pass animations to third-party libraries, or is this impossible during runtime?

Thanks in advance, keep up the great work.

**Comment by xiaojun1994** [comment]
> 可以解决这个问题吗？角度动画在第一方用户手中非常强大，但是对于库开发人员来说却是一个痛苦的过程。对于消费者来说，实现可重用的UI组件而不必选择配置动画是不行的。



> Could this be addressed to the angular core team? Angular animations are very powerful in the hands of first-party users, but a pain to use for library developers. Implementing reusable UI components without having the option to configure animations is a no-go for consumers.
> 
> Abstraction should be key here. Angular animations provide a fluent API to create reusable animations of whatever complexity. Library developers shouldn't have to built custom implementations while we have this amazing tool sitting on the shelf. It's **not an easy thing to do (right)** and each library will have its **own way of handling animations**. I think the adoption rate of Angular animations will increase significantly if this feature gets implemented.
> 
> **Practical example**
> I have a library that uses Angular animations by default - with the option to switch to CSS animations in case users want to use custom animations. The library offers multiple Angular animations for developers to use in their application, but they **can't** pass them on to the components (think of a modal, tooltip or dropdown box). If this feature does not get through, I (sadly) see no use in supporting Angular animations.

[Take a look at this](https://www.npmjs.com/package/@ciri/ngx-popup)

**Comment by xiaojun1994** [comment]
> Could this be addressed to the angular core team? Angular animations are very powerful in the hands of first-party users, but a pain to use for library developers. Implementing reusable UI components without having the option to configure animations is a no-go for consumers.
> 
> Abstraction should be key here. Angular animations provide a fluent API to create reusable animations of whatever complexity. Library developers shouldn't have to built custom implementations while we have this amazing tool sitting on the shelf. It's **not an easy thing to do (right)** and each library will have its **own way of handling animations**. I think the adoption rate of Angular animations will increase significantly if this feature gets implemented.
> 
> **Practical example**
> I have a library that uses Angular animations by default - with the option to switch to CSS animations in case users want to use custom animations. The library offers multiple Angular animations for developers to use in their application, but they **can't** pass them on to the components (think of a modal, tooltip or dropdown box). If this feature does not get through, I (sadly) see no use in supporting Angular animations.

you can use AnimationBuilder，[look this](https://github.com/xiaojun1994/ngx-popup)

**Comment by artemisclyde** [comment]
> **Practical example**
> I have a library that uses Angular animations by default - with the option to switch to CSS animations in case users want to use custom animations. The library offers multiple Angular animations for developers to use in their application, but they **can't** pass them on to the components (think of a modal, tooltip or dropdown box). If this feature does not get through, I (sadly) see no use in supporting Angular animations.

Is there any progress or plans for this feature request? I have to agree with @Jasonkoolman here - I've recently faced this issue frequently where I wanted to use a library Angular component but with the need of adjusting or at the very least disabling the animations for different reasons, one of which is performance. As mentioned before, for this I needed a complete custom version using the source code as there are currently no other means (known to me) of modifying a component's animations without touching the source code.

**Comment by petebacondarwin** [comment]
I'm afraid that we currently have no one focussing on animations issues and features. So it is not clear when this may be addressed.
