### ISSUE TITLE
[Docs] MarkForCheck needed if component is reused

### ISSUE THREAD

**Issue by montella1507** [angular/angular#21509]
[x] Documentation issue or request

## Current behavior
If a component is resued between navigation (/detail/5 -> /detail/8), router does'nt mark that component as markForCheck.  

So if you do something like
`
 this.activatedRoute.data.subscribe(x => this.handleRoute(x));

....
  handleRoute(data: Data) {
    let response = data['XYYZ'];
    this.data = response;
  }
`
That component will not be rerendered, until you click inside...

I think it is not so obvious. So maybe it is bug, or it should be documented in documentation somewhere.

## Expected behavior
This behavior will not happen so often if you follow "best practice" and map that data and use ASYNC pipe (it will call markForCheck in pipe). However, i think the Router should call markForCheck for components, which are being reused between navigation. Especially if the changed parametr is for concrete component:
 
path: edit/param
component: EditComponent

Becase it is obvious the component state is based on that parameter.

Angular CLI: 1.5.5
Node: 7.5.0
OS: win32 x64
Angular: 4.3.3
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, router
... tsc-wrapped

@angular/animations: 4.4.6
@angular/cdk: 2.0.0-beta.10
@angular/cli: 1.5.5
@angular/language-service: 4.1.3
@angular/material: 2.0.0-beta.10
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.5
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.3.4
webpack: 3.8.1

**Comment by atscott** [comment]
Closing since I believe this is a more general comment on component change detection (which is has been documented much better since 2018) and I don't think this is something that should be handled in the Router code.
