### ISSUE TITLE
feat: allow use of :host (or equivalent) with ViewEncapsulation.None

### ISSUE THREAD

**Issue by thefliik** [angular/angular#21511]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I understand that the shadow-piercing descendant combinator is deprecated, so I do not want to rely on `::ng-deep` in my code. Frequently however, I'll be in a situation when I'd _like_ to use `::ng-deep`. For example, when styling a component such as `@angular/material` `MatHorizontalStepper`. For this component, you put your html inside a `mat-step` directive but then the MatStepper component regurgitates that html and renders it through a `[ngTemplateOutlet]`, making `MatHorizontalStepper` the _technical_ "host" of the html content (though conceptually, it feels like the host should be the parent of `MatHorizontalStepper`). 

Using view encapsulation, I cannot style the html inside the `mat-step` without `::ng-deep`. My workaround is to use `ViewEncapsulation.None` and simply scope all the component's css using the component's element selector. This feels brittle and isn't DRY.

## Expected behavior

 I'm open to any solution to improve matters. My idea would be to allow use of the `:host` pseudo-selector (or an equivalent) when `ViewEncapsulation.None`, and simply have angular automatically replace `:host` with the component's element selector during compilation. Alternatively, make `::ng-deep` not deprecated :)

## What is the motivation / use case for changing the behavior?

Make it easier to style a component's descendants using CSS. Make my code more DRY.

## Environment

<pre><code>
Angular version: 5.1.2

**Comment by vicb** [comment]
Probably the best is to use encapsulation and `::ng-deep` for now. 

While it's deprecated, we will not remove it before we have an easy replacement.

**Comment by thefliik** [comment]
@vicb That's comforting to know, I'll use `::ng-deep` then. Thanks!

**Comment by goughjo02** [comment]
Is this still the answer?

**Comment by thefliik** [comment]
@goughjo02 Yes
