### ISSUE TITLE
Selecting headings text via double clicking sometimes select the anchor as well

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21515]
<img width="443" alt="screen shot 2018-01-12 at 8 51 18 pm" src="https://user-images.githubusercontent.com/216296/34902911-752791d4-f7da-11e7-97c0-97ddbea69dca.png">

The problem with this is that if you then copy the heading into the clipboard you will also copy the anchor title text. So when you paste the heading somewhere you get the text prefixed with "link".

Repro:

1. navigate to https://angular.io/guide/aot-compiler#flatmoduleoutfile
2. double-click on the heading "flatModuleOutFile" to select it
3. copy the selection into clipboard
4. paste the clipboard somewhere else

Expected: Pasted text is "flatModuleOutFile"
Actual: Pasted text is "linkflatModuleOutFile"

**Comment by maxkorz** [comment]
`user-select: none;` on the anchor fixes the problem

**Comment by gkalpak** [comment]
@maxkorz, would you be interested in submitting a PR with the fix. The `.header-link` styles are defined [here][1].
(I don't think we can test this (e.g. in e2e tests), but it would be cool it we could :grin:)

[1]: https://github.com/angular/angular/blob/54e02449549448ebab6f255f2da0b4396665c6f0/aio/src/styles/2-modules/_heading-anchors.scss#L21-L27
