### ISSUE TITLE
router option paramsInheritanceStrategy not merging params with child components

### ISSUE THREAD

**Issue by ravishivt** [angular/angular#21510]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Angular 5.2 introduces the new router `paramsInheritanceStrategy` option in #20678 by @voithos.  When this option is set to 'always', my understanding is that Angular should merge a child component's params with it's parent component params.  This does not appear to be the case.  In the child component, `this.route.snapshot.params` does not have any of the params that `this.route.parent.snapshot.params` do.

## Expected behavior

I expect the child components to have the parent components params merged with whatever params are in the child components.

## Minimal reproduction of the problem with instructions

Enable the `paramsInheritanceStrategy` option.

```typescript
    RouterModule.forRoot(routes, {
      paramsInheritanceStrategy: 'always',
    }),
```
Create a route with a child component.

```typescript
RouterModule.forChild([
  {
    path: 'accounts/:accountId',
    component: AccountDetailPageComponent,
    children: [
      {
        path: 'users',
        component: UserListPageComponent
      },
    ],
  },
])
```

You will not be able to access `this.route.snapshot.params.accountId` in the child component (UserListPageComponent) as expected.

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [x] Chrome (desktop) version 63.0.3239.132
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

<hr>

Thanks for the issue. We need to have a reproduction of your exact use-case though. Can you please create one?

**Comment by GrandSchtroumpf** [comment]
@ravishivt : it works for me with `this.route.snapshot.params['accountId '] ` on Chrome and Firefox.

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

<hr>

We did find a use case where the params may not be flattened inside resolvers, so will be working on a fix for that. If there's something else you've found, please reproduce and file a new issue.
