### ISSUE TITLE
Can't get the value of materialize select using ngModel

### ISSUE THREAD

**Issue by PrasathHari** [angular/angular#21529]
##Hi, I am trying to get the value of the selected option in a materialize select element. I am trying to display it in console during a change event. But it is not working.
## HTML
<code>

<form #srchForm="ngForm">

	<div class="col s12 m12 l12 xl12 ">
		<div class="card-panel ">
			<div class="row">
				<div class="input-field col s12 m6 l3 xl3">
					<input id="claims_user" name="claims_user" type="text" placeholder="Type your Id" class="validate" [(ngModel)]="searchCrit.username" >
					<label for="claims_user">Claims User (ID)</label>
				</div>
				<div class="input-field col s12 m6 l3 xl3">
					<select id="clm_ct" name="clm_ct" [(ngModel)]="searchCrit.category" (change)="onNameKeyUp($event)">
							<option [ngValue]="" disabled>Select</option>
						<option *ngFor="let options of mock" [value]="options.id">{{options.category}}</option>
					</select>
					<label for="clm_ct">Categorization</label>
				</div>
				<div class="input-field col s12 m6 l3 xl3">
					<select id="clm_rg" name="clm_rg" [(ngModel)]="searchCrit.region">
							<option [ngValue]="" disabled>Select</option>
						<option *ngFor="let options of mock" [value]="options.id">{{options.region}}</option>
					</select>
					<label for="clm_rg">Region</label>
				</div>

				<div class="col s12 m6 l3 xl3 marTop2 center">
					<a class="waves-effect waves-light btn btnSize" (click)="sendSearchData(srchForm)">Search</a>
					<a class="waves-effect waves-light btn btnSize" (click)="resetDetails()">Reset</a>
				</div>
			</div>

		</div>
	</div>
	</form>
{{srchForm.value | json}}
</code>

##TS
<code>
resetDetails () { 

    this.searchCrit = new SearchCriteria();
      setTimeout(() => {
        $('select').material_select();
        this.searchCrit = new SearchCriteria();
        }, 100);

  }

  onNameKeyUp(event) {

    this.claimUser = event.target.value;
    console.log(this.claimUser);
    
  }

  sendSearchData (form) {  

    this.initializeMatSelect();    
   console.log(form.value);
    console.log(this.searchCrit);
  }
  ngOnInit() {

    this.getUserData();
    this.searchCrit = new SearchCriteria();
    this.initializeMatSelect();     

    }
  initializeMatSelect () {

    setTimeout(() => {     
      $('select').material_select();
          }, 350);
  }

</code>

I am hitting my head for almost two days. Please anyone give a solution

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
