### ISSUE TITLE
ng build --prod, Angular and Bootstrap, got i.pause is not a function

### ISSUE THREAD

**Issue by woteska** [angular/angular#21527]
## I do not know whether it belongs to either Angular or Bootstrap folks.

https://github.com/twbs/bootstrap/issues/25297

## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

**a.)**
1. ng build --prod
2. built success
3. got the following error msg when I open the deployed source on the server:
"Uncaught TypeError: i.pause is polyfills.53de1bdf0af2f1f9ce6f.bundle.js:1 not a function 
    at HTMLDivElement.<anonymous> (scripts.aedec6ce60985a2f5804.bundle.js:1)
    at Function.each (scripts.aedec6ce60985a2f5804.bundle.js:1)
    at v.fn.init.each (scripts.aedec6ce60985a2f5804.bundle.js:1)
    at v.fn.init.e._jQueryInterface [as carousel] (scripts.aedec6ce60985a2f5804.bundle.js:1)
    at HTMLDivElement.<anonymous> (scripts.aedec6ce60985a2f5804.bundle.js:1)
    at Function.each (scripts.aedec6ce60985a2f5804.bundle.js:1)
    at v.fn.init.each (scripts.aedec6ce60985a2f5804.bundle.js:1)
    at scripts.aedec6ce60985a2f5804.bundle.js:1
    at dispatch (scripts.aedec6ce60985a2f5804.bundle.js:1)
    at m.handle (scripts.aedec6ce60985a2f5804.bundle.js:1)"

**Bootstrap v4.beta.2 carousel does not work, when I try to click on next slide, got the fallowing:**

Uncaught Error: No method named "next" polyfills.53de1bdf0af2f1f9ce6f.bundle.js:1 
    at HTMLDivElement.<anonymous> (scripts.aedec6ce60985a2f5804.bundle.js:1)
    at Function.each (scripts.aedec6ce60985a2f5804.bundle.js:1)
    at v.fn.init.each (scripts.aedec6ce60985a2f5804.bundle.js:1)
    at v.fn.init.e._jQueryInterface [as carousel] (scripts.aedec6ce60985a2f5804.bundle.js:1)
    at HTMLAnchorElement.e._dataApiClickHandler (scripts.aedec6ce60985a2f5804.bundle.js:1)
    at HTMLDocument.dispatch (scripts.aedec6ce60985a2f5804.bundle.js:1)
    at HTMLDocument.m.handle (scripts.aedec6ce60985a2f5804.bundle.js:1)
    at e.invokeTask (polyfills.53de1bdf0af2f1f9ce6f.bundle.js:1)
    at n.runTask (polyfills.53de1bdf0af2f1f9ce6f.bundle.js:1)
    at t.invokeTask [as invoke] (polyfills.53de1bdf0af2f1f9ce6f.bundle.js:1)

**b.)**
1. ng serve -> there is no any error msg, when I open localhost:4200

**c.)**
1. replace `../node_modules/bootstrap/dist/js/bootstrap.min.js` to `../node_modules/bootstrap/dist/js/bootstrap.bundle.min.js` in .angular-cli.json
2. ng build --prod -> everything works fine

## Expected behavior
Should not get any error msg.

## Minimal reproduction of the problem with instructions
I will not intend to create a Plunker, so much time! But I can give access to my private repository, if you need...

## Environment

<pre><code>

      "scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/popper.js/dist/umd/popper.min.js",
        "../node_modules/bootstrap/dist/js/bootstrap.min.js"
      ],

{
  "name": "...",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@ngx-translate/core": "^9.0.2",
    "@ngx-translate/http-loader": "^2.0.1",
    "@vimeo/player": "^2.2.1",
    "bootstrap": "4.0.0-beta.2",
    "core-js": "^2.5.3",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "ngx-facebook": "^2.4.0",
    "popper.js": "^1.12.9",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "1.6.4",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.4",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~9.3.0",
    "codelyzer": "^4.0.2",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.3",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.2.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "2.5.3"
  }
}
</code></pre>

**Browser:**
Chrome v63.0.3239.132 (official version) (64 bits)
 
**For Tooling issues:**
- Node version: v8.9.1
- Npm version: 5.5.1
- Platform:  Windows Pro 10 latest

**Others:**
- IDE: IntelliJ Idea Ultimate 2017.3.2

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by pkozlowski-opensource** [comment]
This is definitively _not_ an Angular bug - you are most likely missing one of the Bootstrap dependencies (jQuery and / or Bootstrap's JS). You might consider using one of the native integration of Bootstrap in Angular, ex.: https://ng-bootstrap.github.io

**Comment by woteska** [comment]
@pkozlowski-opensource , thank you for your reply!

Before it with one week, it perfectly works! And of course, I know that my choices are limited using simple bootstrap, not ng bootstrap... there are reasons for that...

What is important, before it 1-2 days, it worked. I was countinously updating the package.json with Angular and other dependencies, therefore I thought maybe the problem is coming from Angular.

@trotyl, @jotatoledo, @ericmartinezr, I do not know **why it is so important** to vote down my issue. Sorry for that not everybody is so clever, smart and profession like you... -.-

**Comment by jotatoledo** [comment]
Personally downvoted cause you didnt provided any sort of reproduction of your issue. Plus this isnt an angular related issue

**Comment by woteska** [comment]
@jotatoledo , I accept that there is no reproduction like on Plunker, but I offered that I could provide access to my repository. It should not be so much effort for anyone, it is just a clone and npm install, that's it!

Where do I have to know from which problem is Angular related one and which not? Sorry guys, I am also a developer and we also use Git, but if somebody ask me something I never downvote them for a question so I can't comprehend why someone should be an ass because of I got a problem... I suppose so you guys are all Angular folks, I think so it is not a good introduction for a user who uses your product.

Of course you have the right to vote down me personally, but there is no mean, there is not matter, the world is not a better place voting me down...

**Comment by mlc-mlapis** [comment]
@woteska ... that's simply not true ... if you don't prepare a simple form of reproduction (Stackblitz, Plunker, ...) it means that anybody has to spend many times more time even on understanding where exactly the problem is. If you times the number of people and the number of issues you can see why a simple reproduction is so important ...

Preparing a simple reproduction also means that in many cases the problem disappeared because its author finds out the problem or finds out that it is not related to Angular at all.

**Comment by trotyl** [comment]
> suppose so you guys are all Angular folks

No, I'm just a normal user. There're currently 2848 people watching this repo, and would be noticed by any kind of updates, downvote is just a signal for letting others know there's no need to waste time on checking this one.

> Where do I have to know from which problem is Angular related one and which not?

You can refer to several support channels, as described in [CONTRIBUTING](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question). As stated in issue template, the GitHub channel is not for support request.
