### ISSUE TITLE
Unable to AOT compile when loading a component with TypeScript 2.4 Dynamic Import Expressions

### ISSUE THREAD

**Issue by patrickmichalina** [angular/angular#21522]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
AOT compiler appears to ignore lazy routes when imported using Dynamic Import Expressions
```js
{ path: '', loadChildren: async () => (await import('./home/home.module')).HomeModule }
```

## Expected behavior
AOT could compile those local imported sources

## Minimal reproduction of the problem with instructions
https://github.com/patrickmichalina/fusebox-angular-universal-starter/blob/master/src/client/app/app-routing.module.ts
## What is the motivation / use case for changing the behavior?

I would like to be able to use AOT w/ Lazy Loading w/ latest typescript features.

For reference, I am using the [FuseBox](https://github.com/fuse-box/fuse-box) bundler (not webpack)

## Environment
Angular version: 5.2.0

**Comment by mlc-mlapis** [comment]
@patrickmichalina ... and why do you use such a syntax when finally it is a static path?

**Comment by patrickmichalina** [comment]
@mlc-mlapis please read https://github.com/tc39/proposal-dynamic-import

**Comment by mlc-mlapis** [comment]
@patrickmichalina ... yep, generally I know but it doesn't mean that it relates to the actual principles of static analyzable code for Angular AOT compilation.

**Comment by patrickmichalina** [comment]
"import() does not establish a dependency which can be statically analyzed. (**However, implementations may still be able to perform speculative fetching in simpler cases like import("./foo.js")**.)"

**Comment by patrickmichalina** [comment]
I believe angular lazy load case can be considered "simple", in terms of fetching locally defined modules to be analyzed by the AOT compiler.

**Comment by Delagen** [comment]
@patrickmichalina I implemented own webpack loader similar to angular-cli to replace paths and module names for AOT compilation with similar syntax.

**Comment by patrickmichalina** [comment]
@Delagen thanks will check it out. I need one for [FuseBox](https://github.com/fuse-box/fuse-box)

**Comment by trotyl** [comment]
You'll need two transformers to achieve that lazy-loading process:

1\. Wrap the arrow function to local exported function:

from:

```typescript
const routes = [
  { path: '', loadChildren: () => import('./lazy.module').then(m => m.LazyModule) }
]
```

to:

```typescript
export function loadChildren_1() {
  return import('./lazy.module').then(m => m.LazyModule)
}

export const routes = [
  { path: '', loadChildren: loadChildren_1 }
]
```

This is similar to the metadata lowering process.

2\. Mapping `NgModule` to corresponding `NgFactory`:

from:

```typescript
export function loadChildren_1() {
  return import('./lazy.module').then(m => m.LazyModule)
}

export const routes = [
  { path: '', loadChildren: loadChildren_1 }
]
```

to:

```typescript
export function loadChildren_1() {
  return import('./lazy.module.ngfactory').then(m => m.LazyModuleNgFactory)
}

export const routes = [
  { path: '', loadChildren: loadChildren_1 }
]
```

---

The first one is valid feature request for more general metadata lowering support, but the second one is tooling specific and does not belong to this repo. So you still need to write your own loader after arrow function being supported.

**Comment by Toxicable** [comment]
Just an extra note on `import()`, you have to set `"module": "esnext"` to be able to use it in TS which most tooling does not support at the moment, namely the CLI does not.
Instead use `System.import()` which is almost identical

**Comment by patrickmichalina** [comment]
Appreciate the feedback, thanks for the great tips! Just to be clear, @trotyl are you saying using this format will work with the current AOT compiler?

```js
export function loadChildren_1() {
  return import('./lazy.module.ngfactory').then(m => m.LazyModuleNgFactory)
}

export const routes = [
  { path: '', loadChildren: loadChildren_1 }
]
```

**Comment by Delagen** [comment]
@patrickmichalina yes. I use this format, and replace with loader at build time. All works.

**Comment by Delagen** [comment]
@patrickmichalina If interested in my loader there are snippet https://gist.github.com/Delagen/bcfe369b3f0bff20866840533d12ac8c
But it works only with dynamic imports (not implemented simple string paths)

**Comment by patrickmichalina** [comment]
Circling back on this issue, I was able to get it solved thanks to all the great feedback.

**My routes:**

```js
import { NgModule } from '@angular/core'
import { RouterModule, Routes } from '@angular/router'

export function homeModule() {
  return import('./home/home.module').then(m => m.HomeModule)
}

export function aboutModule() {
  return import('./about/about.module').then(m => m.AboutModule)
}

export function demosModule() {
  return import('./demos/demos.module').then(m => m.DemosModule)
}

export function callbackModule() {
  return import('./callback/callback.module').then(m => m.CallbackModule)
}

export function logoutModule() {
  return import('./logout/logout.module').then(m => m.LogoutModule)
}

export function accountModule() {
  return import('./account/account.module').then(m => m.AccountModule)
}

export const routes: Routes = [
  { path: '', loadChildren: homeModule },
  { path: 'about', loadChildren: aboutModule },
  { path: 'demos', loadChildren: demosModule },
  { path: 'callback', loadChildren: callbackModule },
  { path: 'logout', loadChildren: logoutModule },
  { path: 'account', loadChildren: accountModule }
]

@NgModule({
  imports: [RouterModule.forRoot(routes, { initialNavigation: 'enabled' })],
  exports: [RouterModule]
})
export class AppRoutingModule {}
```


A fuse-box plugin I wrote to tell where my AOT output files are (simple regex replace):

```js
import { File } from 'fuse-box/core/File'

const defaults = {}

export interface NgAotPluginOptions { }

export class NgAotPluginClass {
  public test: RegExp = /-routing.module.js/

  constructor(opts: NgAotPluginOptions = defaults) { }

  transform(file: File) {
    const regex1 = new RegExp(/.module'/, 'g')
    const regex2 = new RegExp(/Module\);/, 'g')
    file.contents = file.contents.replace(regex1, '.module.ngfactory\'')
    file.contents = file.contents.replace(regex2, 'ModuleNgFactory);')
  }
}

export const NgAotPlugin = (options?: NgAotPluginOptions) => new NgAotPluginClass(options);
```

Works great! Loving the performance gains on an SSR application :)

https://github.com/patrickmichalina/fusing-angular

**Comment by pkozlowski-opensource** [comment]
Closing as based on the reporter comment the original issue was resolved.
