### ISSUE TITLE
fullTemplateTypeCheck strange issue with safe navigation operator

### ISSUE THREAD

**Issue by Delagen** [angular/angular#21521]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
src\app.component.html(1,7): : Object is possibly 'undefined'.
with 
```
export interface ITest {
    test?: {
        [index: string]: any;
    }
}
export interface IParam {
    "test.test": ITest;

    [index: string]: ITest | undefined;
}

class AppComponent {
 test: IParam;
}
```
```
<span *ngIf="test['test.test'].test?.test as testValue">{{testValue}}</span>
```
This may be overwritten as
```
<ng-container *ngIf="test['test.test'].test as testParam">
    <span *ngIf="testParam as testValue">{{testValue}}</span>
</ng-container>
```
which does not generate this error, but why?

## Expected behavior
No errors.

## Minimal reproduction of the problem with instructions
https://github.com/Delagen/ng-typecheck-issue
npm i && npm run build

## Environment

Angular version: 5.2.0

For Tooling issues:
- Node version: 9.4.0

**Comment by ericmartinezr** [comment]
Related https://github.com/angular/angular/issues/21504

**Comment by Delagen** [comment]
@ericmartinezr Not sure. Cause if I reduce nesting for
```
export interface ITest {
    test?: {
        [index: string]: any;
    }
}

class AppComponent {
 test: ITest ;
}
```
```
<span *ngIf="test.test?.test as testValue">{{testValue}}</span>
```
It works without error as I know

**Comment by JoostK** [comment]
I just tested this and it works correctly with Ivy.
