### ISSUE TITLE
Can't resolve all parameters for

### ISSUE THREAD

**Issue by woteska** [angular/angular#21526]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

**a.)**
1. ng build --prod
2. buildt success, but got the following warning msg:
"Warning: Can't resolve all parameters for CustomTranslateHttpLoaderService in C:/Users/Richárd/IdeaProjects/thegiantsteps-app/src/app/services/custom-translate-http-loader.service.ts: ([object Object]
, ?, ?, [object Object]). This will become an error in Angular v6.x "

**b.)**
1. ng serve -> there is no any warning msg

## Expected behavior
Should not get any warning msg.

## Minimal reproduction of the problem with instructions
I will not intend to create a Plunker, so much time! But I can give access to my private repository, if you need...

## Environment

<pre><code>
{
  "name": "...",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@ngx-translate/core": "^9.0.2",
    "@ngx-translate/http-loader": "^2.0.1",
    "@vimeo/player": "^2.2.1",
    "bootstrap": "4.0.0-beta.2",
    "core-js": "^2.5.3",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "ngx-facebook": "^2.4.0",
    "popper.js": "^1.12.9",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "1.6.4",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.4",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~9.3.0",
    "codelyzer": "^4.0.2",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.3",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.2.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "2.5.3"
  }
}
</code></pre>

**Browser:**
I suppose, it does not depend on the browser (latest Chrome).
 
**For Tooling issues:**
- Node version: v8.9.1
- Npm version: 5.5.1
- Platform:  Windows Pro 10 latest

**Others:**
- IDE: IntelliJ Idea Ultimate 2017.3.2

**app/services/custom-translate-http-loader.service.ts**

```
import {Injectable} from '@angular/core';
import {HttpClient, HttpHeaders} from '@angular/common/http';
import {TranslateLoader} from '@ngx-translate/core';

@Injectable()
export class CustomTranslateHttpLoaderService implements TranslateLoader {

  constructor(private http: HttpClient,
              private prefix: string = '/assets/i18n/',
              private suffix: string = '.json',
              private headers?: HttpHeaders) {
  }

  public getTranslation(lang: string): any {
    if (this.headers) {
      return this.http.get(`${this.prefix}${lang}${this.suffix}`, {
        headers: this.headers
      });
    } else {
      return this.http.get(`${this.prefix}${lang}${this.suffix}`);
    }
  }
}
```

**app/app.module.ts:**

```
.
.
.
export class AppModule {
}

export function HttpLoaderFactory(http: HttpClient) {
  return new CustomTranslateHttpLoaderService(http, environment.i18nPath, '.json');
}
```

**environments/environment.prod.ts:**

```
const baseHref = 'https://www.....org/';

export const environment = {
  production: true,
  baseHref: baseHref,
  i18nPath: baseHref + 'assets/i18n/'
};
```

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

----
`@Injectable()` when you use `@Injectable()` angular will wire up this class for DI meaning it will try inject a token of `string` due to this here `private prefix: string = '/assets/i18n/',` which cannot be resolved.

More her https://angular.io/guide/dependency-injection-pattern

**Comment by woteska** [comment]
Ohhhh, jesus, it was a mistake. I just removed @Injectable() and everything is ok! Thank you!

**Comment by woteska** [comment]
@trotyl, @ericmartinezr, I do not know why it is so important to vote down my issue. Sorry for that not everybody is so clever, smart and profession like you... -.- Do not you have better things to do?!

**Comment by mlc-mlapis** [comment]
@woteska ... don't take it so personally ... it is just a quick way how to signal that it is not an issue but just some typo or misunderstanding. Because any response means a new message to all who are subscribed to this Angular repository.

**Comment by woteska** [comment]
@mlc-mlapis , I think so this is the worst message that a user can get. It has a message for the user: "If you ask anything, you are stupid and you will be downvoted, if you ask anything." No doubt.

**Comment by mlc-mlapis** [comment]
@woteska ... absolutely NO, it is a channel for issues and not for support ... remember that each message is sent to 2.849 people actually.

**Comment by woteska** [comment]
@mlc-mlapis , okay, yes, that's so many massages! But please, tell me, where can you know that as a user which one is NOT a bug?

**Comment by mlc-mlapis** [comment]
@woteska ... that's the point ... so the very first step ... creating a simple demo of the problem (Stackblitz, Plunker, ...) ... it all about it! Nothing more. This step examines the situation on the user side as well ... to avoid the case when ... something doesn't work ... bum, a new issue ... somebody will find my problem.

It doesn't mean that the problems and issues don't exist but it is about some level of balance.

**Comment by httpete** [comment]
This bit me - the cli generates @Injectable but you don't want it on the service class.

**Comment by giovannipds** [comment]
I have a similar thing - I will post here if somebody knows it:
A generic service, like so:
```typescript
@Injectable() // build error with or without Injectable
export class GenericProvider<IGeneric> {
  protected plural_endpoint: string
  constructor(
    protected http: HttpClient,
    protected api: ApiProvider,
    protected endpoint: string,
    protected className: string,
  ) { }
}
```
Then some other providers extending it:
```typescript
@Injectable()
export class PriceTableProvider extends GenericProvider<PriceTable> {
  constructor(
    http: HttpClient,
    api: ApiProvider,
  ) {
    super(http, api, 'price-table', 'PriceTableModel')
  }
}
```
Works everywhere, no errors at ide, but breaks when building with `--prod`, ex. `ionic cordova build browser --prod --release`.
Tips?

**Comment by Hobart2967** [comment]
Same here, Got a Service base taking a parameter being fed by child class, and cli complains about it... Feels kinda bad not to be able to realize patterns of OOP. Would be definitely a reason to switch the framework for me.
