### ISSUE TITLE
docs: Live demos in API documentation are outdated 

### ISSUE THREAD

**Issue by Toxicable** [angular/angular#21525]
## I'm submitting a...

<pre><code>[x] Documentation issue or request</code></pre>

If you do a search for `[live demo](` with your IDE there are many live demos linking to Plunker that are still using an alpha version of angular (v2), these are displayed on angular.io (see https://github.com/angular/angular/issues/21524)

These should all be removed or replaced in favor of `live example`s that the guides use

**Comment by DLDante** [comment]
Also live demos with ng v2 as target are trying to use code.angularjs.org as cdn, but there are no more any package of angular 2

**Comment by jenniferfell** [comment]
@brandonroberts Hi. When you get a moment, would you take a look at this. I know we've done a lot of examples work in the last few months, including moving from plunkr to stackblitz, so this issue might be resolved. Thanks!
