### ISSUE TITLE
ERROR in : Illegal state: Could not load the summary for directive ɵbf in node_modules/@angular/Forms/forms.d.ts.

### ISSUE THREAD

**Issue by s1728k** [angular/angular#21535]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When i run ng build --prod it get this error titled.

## Expected behavior

desired behaviour was to produce dist folder with build files

## Environment

<pre><code>
Angular version: 5

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by samialfattani** [comment]
Hi, I have encountered exactly same problem. here is the solution :-
you must import the component **_HeroDetailComponent_** in the right way. **Notice** that even case of letters is matter in paths. i.e ('@angular/forms' is correct, BUT'@angular/Forms' is not.
