### ISSUE TITLE
Disabled form controls are not included in the value of a form group

### ISSUE THREAD

**Issue by calebkiage** [angular/angular#21536]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When creating a form group using a form builder, one disable certain controls by passing `{value: '', disabled: true}` as the state. The problem is that when you have mixed disabled and enabled controls, then the disabled ones don't show up in the form group's value. When all controls are disabled, then the form value has all the controls' values.

## Expected behavior

A form group's value property should contain the values of all the form controls

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-uzle39

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [x] Chrome (desktop) version 63.0.3239.132
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kara** [comment]
This is expected behavior. Disabled control values are not included in aggregate form values to match native form behavior. See docs [here](https://angular.io/api/forms/AbstractControl#disabled)

**Comment by calebkiage** [comment]
Thank you for pointing that out @kara. One last question, when all the controls are disabled, their values are included in the parent's aggregate value. This is what was so confusing about this behavior and the documentation isn't clear about this. Is this the expected behavior?
