### ISSUE TITLE
[aio]: many mistakes in the NgModule guide

### ISSUE THREAD

**Issue by jnizet** [angular/angular#21531]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

I have just read (again) the guide about NgModule on angular.io, and spotted many mistakes or problems. 

 - https://angular.io/guide/ngmodules#the-basic-ngmodule: 
    - implies that the CLI generates a module which imports FormsModule and HttpModule, which isn't true.

 - https://angular.io/guide/ngmodule-vs-jsmodule: 
    - implies that the CLI generates a module which imports FormsModule and HttpModule, which isn't true.

 - https://angular.io/guide/frequent-ngmodules: 
    - suggests using the deprecated HttpModule to talk to a server, instead of using HttpClientModule

 - https://angular.io/guide/module-types: 
    - the section in the left menu is named *"Types of NgModules"*, whereas the page is titled *"Types of Feature Modules"*. 
    - It lists *"Feature Modules"* as a prerequisite, although the section about Feature modules comes after this page in the left menu hierarchy.
    - It tells *"Angular's HttpModule is a good example of a service module"*, although HttpModule is deprecated

 - https://angular.io/guide/entry-components:
    - still uses the deprecated HttpModule. Imports FormsModule, HttpModule and AppRoutingModule although they don't bring anything useful to the understanding of entry components.

 - https://angular.io/guide/feature-modules#rendering-a-feature-modules-component-template:
    - Says *"To see this HTML in the AppComponent, you first have to export the CustomerDashboardComponent in the CustomerDashboardModule. In customer-dashboard.module.ts, just beneath the declarations array, add an exports array containing CustomerDashboardModule:."* But the following example doesn't have any export.

 - https://angular.io/guide/providers:
    - Says *"This creates a service called UserService and returns a message telling you that you need to provide it."*. But no, the CLI doesn't return such a message anymore.
    - Says: *"Update app.module.ts by importing it with your other import statements at the top of the file and adding it to the providers array:"*. But the following example doesn't import the service, and doesn't have any provider.

 - https://angular.io/guide/singleton-services#providing-a-singleton-service:
    - Says: *"For example, a route will have an associated module. When the route is activated, an injector is created from that module as a child of the current injector. When you navigate away from the route, the injector is destroyed. This means that services declared in a route module will have a lifetime equal to that of the route."*. But what is a *route module*? The *"Types of NgModule"* page only describes what a *"Routed feature module"* and a *"Routing module"* are. But it doesn't tell what a *"route module"* is. A concrete example showing how to limit the scope of a service to a route would be nice. There is no such explanation in the https://angular.io/guide/providers#provider-scope section, although that's the one discussing how to limit the scope of a provider.

 - https://angular.io/guide/singleton-services#forroot:
    - Says *"It also must be imported by the individual route components"*. That's not really correct: the components don't import the RouterModule. Feature modules, containing components, are the ones that must also import the RouterModule.
    - Says *"If the RouterModule didn’t have forRoot() then each route component would instantiate a new Router instance"*. That is very unclear to me. Again: the guide shows how to limit the scope of a service to a component, by adding its provider to the component's metadata. But that is not the case here, and it's thus unclear why each route component would have its own Router instance.
    - Says *"whereas all route components import RouterModule which does not include the Router"*. But again, components don't import modules. Modules do import modules.

 - https://angular.io/guide/lazy-loading-ngmodules#routes-at-the-app-level:
    - The default route redirects to itself, which doesn't make much sense to me.

 - https://angular.io/guide/sharing-ngmodules:
    - The indentation in the imports of the example is messy

 - https://angular.io/guide/sharing-ngmodules#using-components-vs-services-from-other-modules: 
    - missing space in *sharedservices*

 - https://angular.io/guide/ngmodule-faq#how-do-i-restrict-service-scope-to-a-module
    - contains `{@ q-root-component-or-module}`

**Comment by trotyl** [comment]
The last two typos has been covered in #21517

**Comment by gkalpak** [comment]
Thx @jnizet :heart: I just noticed this issue (and #21517), after submitting a PR with several minor guide fixes (mostly for `NgModule` guides): #21589

@trotyl, have you incorporated @jnizet's issues into your PR, or should I go through them and see what I've missed?

**Comment by trotyl** [comment]
@gkalpak I think you can continue with #21589 first, I'll remove the conflict parts later. (AFAIK the official ones are always get merged quickly, so it would be better for users 😃 )

**Comment by gkalpak** [comment]
Thx @trotyl. I've merked #21589 for merge. It should be picked up by the caretaker soon.
Feel free to ping me for a review, once you update your PR.

**Comment by kapunahelewong** [comment]
Thank you so much for this @jnizet! This is a huge help. I will go through and check for any remaining things that need to be fixed.

**Comment by jenniferfell** [comment]
docsarea=ngmodule

**Comment by kapunahelewong** [comment]
Thanks for the organized list with links, @jnizet. This was super helpful. Iʻve gone through these one by one and it looks like most of them have been fixed. There are a few though that I can share some more info on:

For this one:

> Says: "For example, a route will have an associated module. When the route is activated, an injector is created from that module as a child of the current injector...

This^^ is covered more in the Dependency Injection PR #28700 because you limit the scope of a service via injector trees. In the meantime, however, this section of Singleton Services has been rewritten with more info on services and the Router.

****

For this one:

> Says "If the RouterModule didn’t have forRoot() then each route component would instantiate a new Router instance". That is very unclear to me....

See the Dependency Injection PR #28700 again. Itʻs a work in progress and thereʻs a lot more to come there. Why a new router instance is instantiated is robust topic. Once that PR is worked out Iʻll link to the right places from the Singleton Services page.

****

For this:
> The default route redirects to itself, which doesn't make much sense to me.

If you take that `redirect` out you get this error:
`zone-evergreen.js:651 Unhandled Promise rejection: Invalid configuration of route ''. One of the following must be provided: component, redirectTo, children or loadChildren ; Zone: <root> ; Task: Promise.then ; Value: Error: Invalid configuration of route ''. One of the following must be provided: component, redirectTo, children or loadChildren`

As far as I know, we donʻt want a component or children here, but if thereʻs a better way to do it, someone let me know and Iʻll submit a PR for it.

Thanks again, @jnizet 😊. You have a good eye! I just had a lot merge into Template Syntax if youʻre inspired to look at that....😅. Itʻs going to be broken into multiple documents like NgModules was. Iʻd love your feedback on that once I get the PRs up and going.

Iʻll leave this open until #28700 merges.

**Comment by rockument69** [comment]
The following issue will be fixed in PR [37948](https://github.com/angular/angular/pull/37948):

> https://angular.io/guide/feature-modules#rendering-a-feature-modules-component-template:
> 
> Says "To see this HTML in the AppComponent, you first have to export the CustomerDashboardComponent in the CustomerDashboardModule. In customer-dashboard.module.ts, just beneath the declarations array, add an exports array containing CustomerDashboardModule:." But the following example doesn't have any export.

**Comment by rockument69** [comment]
The following issue will be fixed in PR [38033](https://github.com/angular/angular/pull/38033):

> https://angular.io/guide/ngmodules#the-basic-ngmodule:
> 
> implies that the CLI generates a module which imports FormsModule and HttpModule, which isn't true.

**Comment by rockument69** [comment]
The following issue also surfaced in bootstrapping.md. PR [38090](https://github.com/angular/angular/pull/38090) fixes this.

>  implies that the CLI generates a module which imports FormsModule and HttpModule, which isn't true.

**Comment by rockument69** [comment]
The following issue will be fixed in PR [38148](https://github.com/angular/angular/pull/38148):

> https://angular.io/guide/ngmodule-vs-jsmodule:
> 
> implies that the CLI generates a module which imports FormsModule and HttpModule, which isn't true.

**Comment by rockument69** [comment]
The following issue will be fixed in PR [38167](https://github.com/angular/angular/pull/38167):

> https://angular.io/guide/frequent-ngmodules:
> 
> suggests using the deprecated HttpModule to talk to a server, instead of using HttpClientModule

**Comment by rockument69** [comment]
The following issue is now fixed by PR [38206](https://github.com/angular/angular/pull/38206):

> https://angular.io/guide/module-types:
> 
> the section in the left menu is named "Types of NgModules", whereas the page is titled "Types of Feature Modules".
> It lists "Feature Modules" as a prerequisite, although the section about Feature modules comes after this page in the left menu hierarchy.
> It tells "Angular's HttpModule is a good example of a service module", although HttpModule is deprecated

**Comment by rockument69** [comment]
> The following issue will be fixed in PR [38148](https://github.com/angular/angular/pull/38148):
> 
> > https://angular.io/guide/ngmodule-vs-jsmodule:
> > implies that the CLI generates a module which imports FormsModule and HttpModule, which isn't true.

This is now fixed (PR [38148](https://github.com/angular/angular/pull/38148)).

**Comment by aikidave** [comment]
I think this issue is now obsolete. Closing.
