### ISSUE TITLE
Angular 5 DatePipe returning wrong time

### ISSUE THREAD

**Issue by berre73** [angular/angular#21539]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have a datepipe service (see below) whic return a wrong time based on a unix epoch input.  The 2 logs shows:

1516001697
14:06 PM GMT+1

```ts
import { Pipe, PipeTransform } from '@angular/core';
import { DatePipe } from '@angular/common';
@Pipe({
    name: 'timeFormatPipe',
})
export class timeFormatPipe implements PipeTransform {
    transform(value: string) {
    	console.log(value);
       var datePipe = new DatePipe("en-BE");
        value = datePipe.transform(value, 'HH:mm a z');
       console.log(value);
       return value;
    }
}
```

## Expected behavior

I would expect the time returned to be:07:34:58

## Environment

<pre><code>
Angular version: 5

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  v9.3.0
- Platform:   Windows

Others:

</code></pre>

**Comment by jotatoledo** [comment]
Please add a repro of the issue

**Comment by ocombe** [comment]
Yes, add a reproduction on plunkr or stackblitz. Thanks

**Comment by vicb** [comment]
closing as no repro
