### ISSUE TITLE
using querySelector in angular

### ISSUE THREAD

**Issue by Obtin** [angular/angular#21530]
## I'm submitting a...

<code><pre>
[ ] Bug report  
</code></pre>

##issue
Cannot set property 'color' of undefined

## Current behavior
var pswdStrength = angular.element(document.querySelector("#pswd-strength-message")); not working
for style.color property, though var pswdStrength = document.getElementById("pswd-strength-message"); worked.

## Environment

<pre><code>
Angular version: 1.5.8

Browser:
- [ ] Chrome (Version 63.0.3239.108)
 
For Tooling issues:
- Node version: v6.2.2
- Platform:  Linux

</code></pre>

 The code is: 

  ```
          var password_strength = utilities.check(password) ;
            var pswdStrength = angular.element(document.querySelector("#pswd-strength-message"));
            // var pswdStrength = document.getElementById("pswd-strength-message");
            console.log(password_strength);
            pswdStrength.innerHTML = password_strength[0];
            pswdStrength.style.color = password_strength[1];
        };

```

**Comment by mlc-mlapis** [comment]
@Obtin ... I do not want to be rude, but read just some latest discussion about using this issue channel, please ... https://github.com/angular/angular/issues/21526, https://github.com/angular/angular/issues/21527

**Comment by Obtin** [comment]
@mlc-mlapis updated the issue. Thankyou.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

This is angular's repo, not angularjs's. You can try over there https://github.com/angular/angular.js
