### ISSUE TITLE
Documentation for interface router.Resolve should explain how Observable<T> is handled

### ISSUE THREAD

**Issue by codeape2** [angular/angular#21537]
## I'm submitting a...
<pre><code>
[x] Documentation issue or request
</code></pre>

## What is the motivation / use case for changing the behavior?

I believe the https://angular.io/api/router/Resolve documentation should explain how the various types of return values are handled by the router:

My main concern is that it is not obvious how Observable<T> is handled: 
- Does the router provide the first value from the Observable? 
- Or the last? 

In contrast, how the router handles T and Promise<T> is simpler to understand:
- If the resolver returns T: The router sets the value in route.data directly
- If the resolver returns Promise<T>: The router waits for the promise to resolve and then sets the value in route.data

I guess a lot of Angular apps that fetch backend data use (or would benefit from using) the router and route data resolvers, so IMO the docs should have a good discussion of the topic.

I'd be happy to submit a PR with some docs changes, but I would need some guidance to get the wording correct (both the router stuff and the RxJS stuff). For instance:

- route.data is an observable: What is the correct way to express that the router "sets a value in route.data"? Is it "the router pushes to route.data?"
- Is the correct term to "resolve an observable"? And if so, does that mean "get the last value of the observable"? From the guide/router docs, under "Milestone 5: Route guards": "The guard might return its boolean answer synchronously. But in many cases, the guard can't produce an answer synchronously. The guard could ask the user a question, save changes to the server, or fetch fresh data. These are all asynchronous operations. Accordingly, a routing guard can return an Observable<boolean> or a Promise<boolean> and the router will **wait for the observable to resolve to true or false**."

**Comment by jenniferfell** [comment]
docsarea=rxjs
docsarea=router

**Comment by atscott** [comment]
Closing as resolved by https://github.com/angular/angular/pull/44573
