### ISSUE TITLE
 NgFor does not support multiple nested levels

### ISSUE THREAD

**Issue by Leningsv** [angular/angular#21541]
PLEASE HELP US PROCESS GITHUB ISSUES FASTER BY PROVIDING THE FOLLOWING INFORMATION.

ISSUES MISSING IMPORTANT INFORMATION MAY BE CLOSED WITHOUT INVESTIGATION.
-->

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Problems Whit nested nfFor. Mi problem from the third nested cycle ngfor does not work. Assists in the first cycle the elements of the fourth cycle. it does not work associates the value a to all the first level cycles no different where it is.  Try several things from TrackByFn and others.

 

## Expected behavior

That the depth level for an ngfor should not have any limit. e worked with angular js and not e this problem

## Environment

<pre>

Angular CLI: 1.6.2
Node: 8.0.0
OS: win32 x64
Angular: 5.0.0
... common, compiler, core, forms, http, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/animations: 5.0.5
@angular/cdk: 5.0.0-rc.2
@angular/cli: 1.6.2
@angular/compiler-cli: 5.0.5
@angular/language-service: 4.4.6
@angular/material: 5.0.0-rc.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
<code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code>

<pre></pre>

	<table>
          <tbody>
            <tr *ngFor="let auxPlanRubro of listaPlanRubro1;">
              <td>
                <table>
                  
                  <tr *ngFor="let auxCanalVenta of auxPlanRubro.CanalesVenta;">
                    <td>
                      <table>
                        
                        <tr *ngFor="let item of auxCanalVenta.FormasPago; let indexFormaPago = index ;trackBy: trackByFn.bind(this, auxCanalVenta)">
                          <td>
                            <table>
                              
                              <tr>
                                <td>
                                  <input type="text" [(ngModel)]="auxPlanRubro.CanalesVenta[indexCanalVenta].FormasPago[indexFormaPago].Periodicidades" >
                                </td>
                              </tr>                             
                            </table>
                          </td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </tbody>
        </table>

**Comment by mlc-mlapis** [comment]
@Leningsv ... a simple reproduction on http://stackblitz.com is needed.

**Comment by Leningsv** [comment]
elaborate the example that you requested, in which there are n errors. The point is dependence when the objects are at 3 levels. It does not work When working with multiple select.
this is a url of test: https://stackblitz.com/edit/angular-nskhe4?file=app%2Fapp.component.ts
________________________________
De: Miloš Lapiš <notifications@github.com>
Enviado: lunes, 15 de enero de 2018 11:23
Para: angular/angular
Cc: Lenin; Mention
Asunto: Re: [angular/angular] NgFor does not support multiple nested levels (#21541)


@Leningsv<https://github.com/leningsv> ... a simple reproduction on http://stackblitz.com is needed.

**Comment by Leningsv** [comment]
[cid:f4c989ab-8935-4efe-9295-20911f3e56fb]

from my perspective when you create an object dynamically it has to be independent. I do not know why the error occurs.

Thank you very much I hope your help

________________________________
De: Lenin Samaniego Vizcaino <leningsv@hotmail.com>
Enviado: lunes, 15 de enero de 2018 14:34
Para: Miloš Lapiš; angular/angular; angular/angular
Cc: Mention
Asunto: RE: [angular/angular] NgFor does not support multiple nested levels (#21541)


elaborate the example that you requested, in which there are n errors. The point is dependence when the objects are at 3 levels. It does not work When working with multiple select.
this is a url of test: https://stackblitz.com/edit/angular-nskhe4?file=app%2Fapp.component.ts
________________________________
De: Miloš Lapiš <notifications@github.com>
Enviado: lunes, 15 de enero de 2018 11:23
Para: angular/angular
Cc: Lenin; Mention
Asunto: Re: [angular/angular] NgFor does not support multiple nested levels (#21541)


@Leningsv<https://github.com/leningsv> ... a simple reproduction on http://stackblitz.com is needed.

**Comment by mlc-mlapis** [comment]
@Leningsv ... hmm, the problem is not in Angular and nested `*ngFor` but in the basic fact that JS objects can share references of for their inner objects/arrays even the references on the first level are different.

The whole case is a bit unreadable because of you are using undefined arrays when initializing `[(ngModel)]` relations.

Finally that's the reason: `{{listaPadre[0].CanalesVenta === listaPadre[1].CanalesVenta}}` -> true ... the same reference.

**Comment by Leningsv** [comment]
Hi

And what can I do in that case? At the moment of using the communication between components and lists of independent resources to solve my problem. But I would like to know if there is another way. Something that has an angle to force you to send to the list that I send is unique. Thanks for all
________________________________
De: Miloš Lapiš <notifications@github.com>
Enviado: lunes, 15 de enero de 2018 17:35
Para: angular/angular
Cc: Lenin; Mention
Asunto: Re: [angular/angular] NgFor does not support multiple nested levels (#21541)


@Leningsv<https://github.com/leningsv> ... hmm, the problem is not in Angular and nested *ngFor but in the basic fact that JS objects can share references of for their inner objects/arrays even the references on the first level are different.

The whole case is a bit unreadable because of you are using undefined arrays when initializing [(ngModel)] relations.

Finally that's the reason: {{listaPadre[0].CanalesVenta === listaPadre[1].CanalesVenta}} -> true ... the same reference.

**Comment by mlc-mlapis** [comment]
@Leningsv ... I looked at it once more and the shared reference is `this.listaCanalVenta` on the line `<option *ngFor="let option of listaCanalVenta" [value]="option">`. And it is true ... in both cycles it is the same reference.

If you try to have separate ones ... like for example:

```
 this.listaCanalVenta = [
      [
        {Codigo: "AUTOBPAC", Descripcion: null, Id: "HANtbyi2VOJaWy7MX9jLmA%3d%3d", IdTabla: 4, Nombre: "CANAL AUTOMOTRIZ"},
        {Codigo: "GPS", Descripcion: null, Id: "1JdZb%2fIrx7SxqmwO%2fE2u1A%3d%3d", IdTabla: 1, Nombre: "GPS"},
        {Codigo: "PROM", Descripcion: null, Id: "wTuGncTUsONb%2fRGCoJ2a1w%3d%3d", IdTabla: 3, Nombre: "PROMOTORES"},
        {Codigo: "USSD", Descripcion: null, Id: "dKk4ykgGbl7eyM7XgfJa6A%3d%3d", IdTabla: 5, Nombre: "USSD"}
      ],
      [
        {Codigo: "AUTOBPAC", Descripcion: null, Id: "HANtbyi2VOJaWy7MX9jLmA%3d%3d", IdTabla: 4, Nombre: "CANAL AUTOMOTRIZ"},
        {Codigo: "GPS", Descripcion: null, Id: "1JdZb%2fIrx7SxqmwO%2fE2u1A%3d%3d", IdTabla: 1, Nombre: "GPS"},
        {Codigo: "PROM", Descripcion: null, Id: "wTuGncTUsONb%2fRGCoJ2a1w%3d%3d", IdTabla: 3, Nombre: "PROMOTORES"},
        {Codigo: "USSD", Descripcion: null, Id: "dKk4ykgGbl7eyM7XgfJa6A%3d%3d", IdTabla: 5, Nombre: "USSD"}
      ]
    ]
```

and then using ...
`<tr *ngFor="let padre of listaPadre; let i=index">`
...
`<option *ngFor="let option of listaCanalVenta[i]" [value]="option">`
the problem disappears.

**Comment by mlc-mlapis** [comment]
@Leningsv ... so the solution could be a pipe which makes the array immutable:

`<option *ngFor="let option of listaCanalVenta | getImmutable" [value]="option">`

**Comment by mlc-mlapis** [comment]
@Leningsv ... hmm, I am trying to make an immutable data of `listaCanalVenta` for each cycle but no luck (pipe, getter, ...) except a hard coded declaration:

```
his.listaCanalVenta = [
      [
        {Codigo: "AUTOBPAC", Descripcion: null, Id: "HANtbyi...", IdTabla: 4, Nombre: "CANAL AUTOMOTRIZ"},
        {Codigo: "GPS", Descripcion: null, Id: "1JdZb...", IdTabla: 1, Nombre: "GPS"},
        {Codigo: "PROM", Descripcion: null, Id: "wTu...", IdTabla: 3, Nombre: "PROMOTORES"},
        {Codigo: "USSD", Descripcion: null, Id: "dKk...", IdTabla: 5, Nombre: "USSD"}
      ],
      [
        {Codigo: "AUTOBPAC", Descripcion: null, Id: "HANtb...", IdTabla: 4, Nombre: "CANAL AUTOMOTRIZ"},
        {Codigo: "GPS", Descripcion: null, Id: "1JdZb...", IdTabla: 1, Nombre: "GPS"},
        {Codigo: "PROM", Descripcion: null, Id: "wTuG...", IdTabla: 3, Nombre: "PROMOTORES"},
        {Codigo: "USSD", Descripcion: null, Id: "dKk4y...", IdTabla: 5, Nombre: "USSD"}
      ]
    ]
```

**Comment by mlc-mlapis** [comment]
@Leningsv ... so after wider discussion it looks that there are only 2 solutions:
* switch the whole case completely to reactive forms principle
* create programmatically a shadow copy (the same principle as above the hard declaration) of array lists for `<option>` tag generated via `*ngFor` to have immutable list for each of them

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by ryanbuening** [comment]
Does anyone have a working example of the shadow copy solution to this problem?
