### ISSUE TITLE
Order of css changed depending on navigation order

### ISSUE THREAD

**Issue by rekna1** [angular/angular#21544]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I start my application with #dashboard it displays correct
When I start my application with another url and then navigate to #dashboard some elements are not correctly rendered.

When I inspect the css for #dashboard in both cases, I can see some css rules are in a different order which explains why in the first case some elements are rendered differently:

I've included two screenshots of css inspector, showing that in the first h4.title is rendered first and then later H1[_ngcontent-c9], H2[_ngcontent-c9], H3[_ngcontent-c9], H4[_ngcontent-c9], H5[_ngcontent-c9]

In the second example h4.title is rendered after H1[_ngcontent-c9], H2[_ngcontent-c9], H3[_ngcontent-c9], H4[_ngcontent-c9], H5[_ngcontent-c9] causing top and bottom margin not to be 0 but 1rem.

-------------
![first](https://user-images.githubusercontent.com/739942/34960682-28f3ccc4-fa3c-11e7-978b-5e1681bef9f8.png)
-------------
![second](https://user-images.githubusercontent.com/739942/34960690-2f8a9b08-fa3c-11e7-88a4-cb30345dccd0.png)
-------------

## Expected behavior
whatever route I start with, the css for any given component should be consistently rendered in the same order

## Minimal reproduction of the problem with instructions
currently unable to build repo, current application to complex to build simple repo

## Environment

<pre><code>
Angular CLI: 1.6.3
Node: 8.9.0
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0

Browser:
other browsers not tested but probably same behaviour
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x ] IE version XX
- [ ] Edge version XX

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

<hr>

Also, this would seem to be expected as the CSS would be attached to the components (if you AOT the code), so would load along with the component.

**Comment by rekna1** [comment]
Solved it by restructuring the css code.
