### ISSUE TITLE
Why are ChangeDetection cycles kicked off on input when {updateOn:'blur'} is set ?

### ISSUE THREAD

**Issue by gpeel** [angular/angular#21543]
I'm submitting a...
 
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
 

## Current behavior
 The docs state : Angular Forms adds updateOn Blur / Submit
You can now run validation and value updates on `blur` or on `submit`, instead of on every input event.

Whe using updateOn: 'blur' for example. the validator are only executed on 'blur' which is great
BUT you still got a full ChangeDection cycle on each 'input' event which is really unecessary.

example :
in a FormComponent :

    this.form = new FormGroup(
      {
        firstname: new FormControl('Thomas', {
          validators: [MyValidators.myRequired('Firstname')],
          updateOn: 'blur'
        })
      }
    );

If I trap ngDoCheck() on the app-component.ts, we see a ChangeDetection cycle for every input made.
  ngDoCheck(): void {
    console.log(`¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤--CD-${this.count++}---¤¤¤¤¤¤¤¤¤¤¤¤¤¤`);
  }

If I input Twice : ie  in my exmaple 'Thomas' becomes 'ThomasAA' inthe input =>
I see 2 refresh cycles

¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤--CD-3---¤¤¤¤¤¤¤¤¤¤¤¤¤¤ app.component.ts:36 
¤-¤-¤-¤-¤-¤-¤-¤-¤--dom-5--¤-¤-¤-¤-¤-¤-¤ refresh-count.component.ts:22 
¤¤-dom-refresh-for-FORM-COMPONENT:2 app.component.ts:36 
¤-¤-¤-¤-¤-¤-¤-¤-¤--dom-6--¤-¤-¤-¤-¤-¤-¤    app.component.ts:27 
¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤--CD-4---¤¤¤¤¤¤¤¤¤¤¤¤¤¤    app.component.ts:36 
¤-¤-¤-¤-¤-¤-¤-¤-¤--dom-7--¤-¤-¤-¤-¤-¤-¤ refresh-count.component.ts:22 
¤¤-dom-refresh-for-FORM-COMPONENT:3     app.component.ts:36
 ¤-¤-¤-¤-¤-¤-¤-¤-¤--dom-8--¤-¤-¤-¤-¤-¤-¤

NOTE :  dom refreshes are traced using the following method :
{{onRefreshCounter()}}
 onRefreshCounter() {
    console.log(`¤¤-dom-refresh-for-${this.name}:${this.counter++}`);
  }

And on blur we see the validators executing.

myRequired value/error ThomasAA / null   <<<<<<<< custom validator log
error-message.component.ts:79 <error-msg> compute errors => []  <<< error-component updating on valueChanges
¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤--CD-5---¤¤¤¤¤¤¤¤¤¤¤¤¤¤ app.component.ts:36 
¤-¤-¤-¤-¤-¤-¤-¤-¤--dom-9--¤-¤-¤-¤-¤-¤-¤   refresh-count.component.ts:22 
¤¤-dom-refresh-for-FORM-COMPONENT:4  refresh-count.component.ts:22 
¤¤-dom-refresh-for-ERRMSG-firstname:2   app.component.ts:36 
¤-¤-¤-¤-¤-¤-¤-¤-¤--dom-10--¤-¤-¤-¤-¤-¤-¤

Why are ChangeDetection cycles kicked off on input when {updateOn:'blur'} is set ?

## Expected behavior
only one ChangeDetecting cycle started on blur event

**Comment by fredrik-lundin** [comment]
The `updateOn` property controls when the `control` will update itself (valid state and value). It will _not_ affect change detection. The rest of your component might still want to react to your input changing, even though you don't want to update your `control`. 

> Returns the update strategy of the AbstractControl (i.e. the event on which the control will update itself). 

[https://angular.io/api/forms/AbstractControl#updateOn](https://angular.io/api/forms/AbstractControl#updateOn)

**Comment by gpeel** [comment]
I understand your comment, but logically if the input-component does not want to update itself and do not emit new value, why start change-detection on events that are not monitored/bound ?  it seems a waste of time.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
