### ISSUE TITLE
Why do I see component tags around component templates??

### ISSUE THREAD

**Issue by kolkov** [angular/angular#21549]
Hi! Why do I see component tags around component templates?? 
As result my sidebar dropdown does not work!
What cause this problem?
```
Angular CLI: 1.6.4
Node: 8.2.1
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.37
@angular-devkit/core: 0.0.24
@angular-devkit/schematics: 0.0.45
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.12
typescript: 2.4.2
webpack: 3.10.0
```
![image](https://user-images.githubusercontent.com/3740898/34984024-8267c0a6-fac0-11e7-9e8a-270614d6a8e1.png)

**Comment by mlc-mlapis** [comment]
@kolkov ... because they are custom components which have their own tags. If you use attribute components, directives or `<ng-container>` (`<ng-template>`) then they would not be there.

**Comment by kolkov** [comment]
@mlc-mlapis I try to use this solution in my project. https://github.com/mrholek/CoreUI-Angular/blob/master/Angular4_CLI_Starter/src/app/components/app-sidebar-nav/app-sidebar-nav.component.ts
If I build this example as is, I don't see this extra tags, but if I build in my own project I see this tags.
I don't undestand why?

**Comment by jotatoledo** [comment]
https://blog.angular-university.io/angular-ng-template-ng-container-ngtemplateoutlet/

**Comment by kolkov** [comment]
@jotatoledo Thanks! Very interesting and informative!
I read the manual, but still I do not understand where these extra tags come from, and how in my case it's to get rid of them so that the drop-down lists can work...(

**Comment by jotatoledo** [comment]
The article explains in a clear way how to archieve what you are looking for. Plus @mlc-mlapis already gave a hint.

Close this, as it now falls within the category of support.

**Comment by kolkov** [comment]
@jotatoledo Then I'll put the question differently, why do the same code compile differently? In my case, there are extra tags, and in the second, they do not appear. The only difference is that I use another router.

**Comment by mlc-mlapis** [comment]
@kolkov ... it is not related to `@angular/router` ... not sure why you are talking about `The only difference is that I use another router`. Where do you see the difference?

My recommendation is: `Start with simple separated examples of used techniques to understand how they works. Then you can combine them together`.  You jumped directly into the middle of some enhanced template and you missed some necessary information to understand it fully.

**Comment by kolkov** [comment]
I finally figured it out. Just did not pay attention to this directive. It is she who removes unnecessary tags. I understand that we can do that they did not arise at all?
https://github.com/mrholek/CoreUI-Angular/blob/master/Angular4_CLI_Starter/src/app/directives/replace/replace.directive.ts

**Comment by mlc-mlapis** [comment]
@kolkov ... yep, its effect is a direct manipulation with the hierarchy of some elements in DOM. It is used for some specific reasons ... but not too Angularic at all and also not a general recommendation.

**Comment by kolkov** [comment]
@mlc-mlapis Thank you so much! What more canonical way would you advise using? The one described above?

**Comment by jotatoledo** [comment]
Another thing is that routed components dont have selectors

**Comment by mlc-mlapis** [comment]
@kolkov ... yes, there are some specific cases where you need to avoid of adding custom component tags to DOM (as for example <TABLE><TR><TD> structures) ... then so called attribute components take their roles (... <tr myAttributeComponent>...</tr>). Also `<ng-container>` (`<ng-template>`) play important roles in many Angular abstraction constructs. You can also use fully programmatic way of creating components ... many times combined with dynamic loading of so called lazy loaded modules ...

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by kolkov** [comment]
When this question was relevant, he did not even look closely like the issue of support ...
