### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by rudra-maadhav** [angular/angular#21548]
key-up.component.ts

import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-key-up',
  templateUrl: './key-up.component.html',
  styleUrls: ['./key-up.component.css']
})
export class KeyUpComponent implements OnInit {
  values= '';
  value2= '';
  constructor() { }

  ngOnInit() {
  }

onKey(value: string) {
this.values += value + '|';
}

update(value: string) { this.value2 = value; }

}

//////////////////////////////////////////////////////////////////

@Component({
  selector: 'app-key-up4',
  template: `
    <input #box
      (keyup.enter)="update(box.value)"
      (blur)="update(box.value)">

    <p>{{value}}</p>
  `
})
export class KeyUpComponentComponent {
  value = '';
  update(value: string) { this.value = value; }
}
//////////////////////////////////
key-up.component.html
<p>
  key-up works with Enter key (keyup.enter)!
</p>

<input #box (keyup.enter)="onKey(box.value)">
<p>{{ values }}</p>

<p>On blur </p>

<app-key-up4></app-key-up4>
///////////////////////////////////////

compiler.js:26383 Uncaught Error: Cannot assign to a reference or variable!
    at _AstToIrVisitor.visitPropertyWrite (compiler.js:26383)
    at PropertyWrite.visit (compiler.js:4679)
    at _AstToIrVisitor._visit (compiler.js:26455)
    at eval (compiler.js:26426)
    at Array.map (<anonymous>)
    at _AstToIrVisitor.visitAll (compiler.js:26426)
    at _AstToIrVisitor.visitChain (compiler.js:26103)
    at Chain.visit (compiler.js:4605)
    at convertActionBinding (compiler.js:25807)
    at eval (compiler.js:28407)

Can any one help how to solve it or What went wrong!

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
