### ISSUE TITLE
[animations] @.done callback is called even after component was destroyed

### ISSUE THREAD

**Issue by alex-okrushko** [angular/angular#21546]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

@.done callback is called after component has been destroyed.

In my case this callback updates value in the shared service, which is used in the new component. Because this callback is called after the old component was destroyed and the new component has been rendered AND the shared data has been updated `ExpressionChangedAfterItHasBeenCheckedError` is thrown.

## Expected behavior

If viewRef (component) is destroyed do not call animation callback.

## Minimal reproduction of the problem with instructions

This app fully reproduces the behavior: https://stackblitz.com/edit/angular-animation-callback-issue?file=app/pulsing.component.ts

## Environment

<pre><code>
Angular version: X.Y.Z

5.2.0

</code></pre>

**Comment by alex-okrushko** [comment]
@matsko

**Comment by jrumandal** [comment]
`
@Component({
    selector: 'bugged-component',
    template: "<div [@animation]="isOpen" [@animation.done]="doneCallback()">"
})
export class BuggedComponent implements OnInit {
    @Input() isOpen = false;
    ...
    doneCallback() {
        console.log('this gets executed')
        setTimeout(() => console.log('if you call a changeDetection in here, you brake the app'), 5000);
    }
}

// used somewhere
<bugged-component *ngIf="isOpen" [isOpen]="isOpen" ></bugged-component>

// somewhere's implementation that somehow set the flag
...
ngOnInit () {
    this.isOpen = true;
    setTimeout(() => { this.isOpen = false; },1000);
}
...
`

I was able to replicate the problem, and the app broke when a detectChange is called inside a destroyed component

**Comment by atscott** [comment]
Closing as resolved by https://github.com/angular/angular/commit/432afd1ef41e0bfd905e71e8b15ec7c9ab337352. As long as the state update uses markForCheck where it’s read (which would be the case with your example) or you’re using a signal for state, you won’t get the ExpressionChanged error.
