### ISSUE TITLE
Nested ng-content with selector doesn't get content

### ISSUE THREAD

**Issue by bgotink** [angular/angular#21550]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have two components:

```ts
@Component({
  selector: 'my-inner',
  template: '<ng-content select="input"></ng-content>'
})
export class InnerComponent {}

@Component({
  selector: 'my-outer',
  template: `
    <my-inner>
      <ng-content select="input"></ng-content>
    </my-inner>
  `
})
export class OuterComponent {}
```

When the outer component is used with content, the content doesn't project, i.e. what I write is

```html
<my-outer>
  <input placeholder="foo">
</my-outer>
```

which results in the following DOM:

```html
<my-outer>
  <my-inner>
    <!-- no input here -->
  </my-inner>
</my-outer>
```

If we modify the `<ng-content select="input">` in the `InnerComponent` to `<ng-content select="input, ng-content">`, it does output the correct DOM:

```html
<my-outer>
  <my-inner>
    <input placeholder="foo">
  </my-inner>
</my-outer>
```

however we lose the fact that we only want `input` elements so this doesn't work when projecting multiple elements to different `ng-content`s.

## Expected behavior

It should result in the correct DOM without workaround.

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/GKaUMGTpI2K8BukQI6co?p=preview

## What is the motivation / use case for changing the behavior?

I'm building a library of complex input components (e.g. input masks &hellip;) and I want the consumer of the library to provide the actual `<input>` element so they can control the placeholder, tabindex and aria attributes. Right now run into this because the date input in my library uses the input mask internally:

```html
<!-- input mask template -->
<div class="placeholder">{{ placeholder }}</div>
<ng-content select="input"></ng-content>

<!-- date input template -->
<my-input-mask mask="../../....">
  <ng-content select="input"></ng-content>
</my-input-mask>
```

I can use the workaround for now, until I run into a component that needs multiple content projections.

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by alexzuza** [comment]
> It should result in the correct DOM without workaround.
Where did you find that it should work this way. For me it works as it was designed.
So at least it's a feature request

**Comment by vicb** [comment]
As @alexzuza mentioned above, it works as designed and you also get it right in your plunker: what you want to re-project is the `<ng-content>`.

That being said, your use case is legit and there is a little known Angular construct for that: the `ngProjectAs` attribute which defines how the `ng-content` would be selected:

```typescript
@Component({
  selector: 'my-wrapper-component',
  template: `
  <my-component>
    <ng-content select="input" ngProjectAs="input"></ng-content>
  </my-component>
  `
})
export class MyWrapperComponent {
}
```

**Comment by bgotink** [comment]
@alexzuza Based on how nested content projection works in ShadowDOM v0 ([plunker](https://plnkr.co/edit/L9cxfTzfKFCcLnus6k1X?p=preview), chrome only). ShadowDOM v0 is, afaik, what Angular's content projection and emulated style encapsulation are modeled to look like so this deviation from the ShadowDOM behaviour is unexpected.

@vicb Thanks for the info!
