### ISSUE TITLE
No NgModule metadata found for {module_name}

### ISSUE THREAD

**Issue by Zerokk** [angular/angular#21552]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I've got two modules: one main module which tries to set up some routing, and one mature, big module, that will be the first of many to be added to this application. 

## Expected behavior
The main module should lazy-load the entire secondary module with no problem. Needless to say, that module works perfectly when run standalone.

## Minimal reproduction of the problem with instructions

I've got one main module which only has it's default root component. Inside the src folder, I created a folder "modules" in which I relocated the old module. The main module looks like this:

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { routing } from './routing';


@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    routing
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

That "routing" import looks like the following:

```
import { ModuleWithProviders } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { AppComponent} from './app.component';

const routes: Routes = [
  { path: '', redirectTo: 'init', pathMatch: 'full' },
  { path: 'init', component: AppComponent },
  { path: 'achieved_combined', loadChildren: '../modules/MBO_plan_achieved/src/app/app.module#AchievedCombined_Module' }
];

export const routing: ModuleWithProviders = RouterModule.forRoot(routes);
```

If you wonder, I've got also the other module with this -apparently, needed- routing file:

```
import { ModuleWithProviders } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { AppComponent } from './app.component';

const routes: Routes = [
  { path: '', component: AppComponent }
];

export const routing: ModuleWithProviders = RouterModule.forChild(routes);
```

```
@NgModule({
  declarations: [
    AppComponent,
    SegmentsComponent,
    GranularityComponent,
    ChartPickerComponent,
    DatePickerWrapperComponent, 
    ChartWrapperComponent,
    DynamicTable,
    TableFormat,
    SelectedLevelsComponent
  ],
  imports: [
    BrowserModule,
    AngularFontAwesomeModule,
    FormsModule, 
    NgbModule.forRoot(),
    Ng4LoadingSpinnerModule.forRoot(),
    HttpModule,
    MyDateRangePickerModule,
    ChartModule,
    routing
  ],
  providers: [RefresherService, DataRequester],
  bootstrap: [AppComponent]
})
export class AchievedCombined_Module { }

```

## What is the motivation / use case for changing the behavior?
We're developing a big application in parts. The first part is ready and working! But now, I've got to make this main module in order to serve it, and add the future modules one by one to it. 

## Environment

<pre><code>
Angular CLI: 1.5.4
Node: 8.9.1
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.4
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.4.2
webpack: 3.8.1
</code></pre>

Any help regarding this? I really don't know what to do to fix this weird bug:

```
ERROR in Error: No NgModule metadata found for 'AchievedCombined_Module'.
    at NgModuleResolver.resolve (C:\Dev\Projects\AngularFrontend\MainModule\node_modules\@angular\compiler\bundles\compiler.umd.js:20277:23)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Dev\Projects\AngularFrontend\MainModule\node_modules\@angular\compiler\bundles\compiler.umd.js:15230:60)
    at visitLazyRoute (C:\Dev\Projects\AngularFrontend\MainModule\node_modules\@angular\compiler\bundles\compiler.umd.js:31167:104)
    at visitLazyRoute (C:\Dev\Projects\AngularFrontend\MainModule\node_modules\@angular\compiler\bundles\compiler.umd.js:31171:17)
    at AotCompiler.listLazyRoutes (C:\Dev\Projects\AngularFrontend\MainModule\node_modules\@angular\compiler\bundles\compiler.umd.js:31135:20)
    at AngularCompilerProgram.listLazyRoutes (C:\Dev\Projects\AngularFrontend\MainModule\node_modules\@angular\compiler-cli\src\transformers\program.js:156:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Dev\Projects\AngularFrontend\MainModule\node_modules\@angular\compiler-cli\src\ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (C:\Dev\Projects\AngularFrontend\MainModule\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:247:66)
    at Promise.resolve.then.then (C:\Dev\Projects\AngularFrontend\MainModule\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:538:50)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

webpack: Failed to compile.
```

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/search?q=No+NgModule+metadata+found+for&type=Issues&utf8=%E2%9C%93

**Comment by Zerokk** [comment]
Already looked for some info, but I don't find any solution for this particular problem...

**Comment by mlc-mlapis** [comment]
@Zerokk ... I can see a logical problem when `AchievedCombined_Module` should be a lazy loaded module and in the same time it should depend on `AppComponent` ... simply it has no sense.

**Comment by Zerokk** [comment]
@mlc-mlapis Yeah, I was just about to post some new info, and it has to do something with that. Let me explain.

I changed the main component of the AchievedCombined_Module, but just the name. Thing was, that both main components were called the same: "AppComponent". So I changed its selector and class name, and the app began compiling!

But now I've got another problem. I can see the MainModule's main component template, which was quite simple: it just has an <a href> that points to the other module. It triggers the route to the other module, but when I click it, I get the following error, before falling back again to the main page:

```
Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[ApplicationRef -> NgZone]: 
  StaticInjectorError(Platform: core)[ApplicationRef -> NgZone]: 
    NullInjectorError: No provider for NgZone!
_NullInjector.prototype.get@webpack-internal:///../../../core/esm5/core.js:1208:19
resolveToken@webpack-internal:///../../../core/esm5/core.js:1506:17
tryResolveToken@webpack-internal:///../../../core/esm5/core.js:1448:16
StaticInjector.prototype.get@webpack-internal:///../../../core/esm5/core.js:1316:20
resolveToken@webpack-internal:///../../../core/esm5/core.js:1506:17
tryResolveToken@webpack-internal:///../../../core/esm5/core.js:1448:16
StaticInjector.prototype.get@webpack-internal:///../../../core/esm5/core.js:1316:20
resolveNgModuleDep@webpack-internal:///../../../core/esm5/core.js:11050:12
NgModuleRef_.prototype.get@webpack-internal:///../../../core/esm5/core.js:12283:16
resolveNgModuleDep@webpack-internal:///../../../core/esm5/core.js:11050:12
_createClass@webpack-internal:///../../../core/esm5/core.js:11095:32
_createProviderInstance$1@webpack-internal:///../../../core/esm5/core.js:11061:26
initNgModule@webpack-internal:///../../../core/esm5/core.js:11014:28
NgModuleRef_@webpack-internal:///../../../core/esm5/core.js:12269:9
createNgModuleRef@webpack-internal:///../../../core/esm5/core.js:12258:12
debugCreateNgModuleRef@webpack-internal:///../../../core/esm5/core.js:14595:12
NgModuleFactory_.prototype.create@webpack-internal:///../../../core/esm5/core.js:15733:16
RouterConfigLoader.prototype.load/<@webpack-internal:///../../../router/esm5/router.js:4610:43
MapSubscriber.prototype._next@webpack-internal:///../../../../rxjs/_esm5/operators/map.js:82:22
Subscriber.prototype.next@webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:97:13
PromiseObservable.prototype._subscribe/<@webpack-internal:///../../../../rxjs/_esm5/observable/PromiseObservable.js:71:25
ZoneDelegate.prototype.invoke@webpack-internal:///../../../../zone.js/dist/zone.js:388:17
onInvoke@webpack-internal:///../../../core/esm5/core.js:4947:24
ZoneDelegate.prototype.invoke@webpack-internal:///../../../../zone.js/dist/zone.js:387:17
Zone.prototype.run@webpack-internal:///../../../../zone.js/dist/zone.js:138:24
scheduleResolveOrReject/<@webpack-internal:///../../../../zone.js/dist/zone.js:858:52
ZoneDelegate.prototype.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:421:17
onInvokeTask@webpack-internal:///../../../core/esm5/core.js:4938:24
ZoneDelegate.prototype.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:420:17
Zone.prototype.runTask@webpack-internal:///../../../../zone.js/dist/zone.js:188:28
drainMicroTaskQueue@webpack-internal:///../../../../zone.js/dist/zone.js:595:25
ZoneTask.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:500:21
invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:1517:9
globalZoneAwareCallback@webpack-internal:///../../../../zone.js/dist/zone.js:1543:17

Stack trace:
resolvePromise@webpack-internal:///../../../../zone.js/dist/zone.js:809:31
resolvePromise@webpack-internal:///../../../../zone.js/dist/zone.js:775:17
scheduleResolveOrReject/<@webpack-internal:///../../../../zone.js/dist/zone.js:858:17
ZoneDelegate.prototype.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:421:17
onInvokeTask@webpack-internal:///../../../core/esm5/core.js:4938:24
ZoneDelegate.prototype.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:420:17
Zone.prototype.runTask@webpack-internal:///../../../../zone.js/dist/zone.js:188:28
drainMicroTaskQueue@webpack-internal:///../../../../zone.js/dist/zone.js:595:25
ZoneTask.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:500:21
invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:1517:9
globalZoneAwareCallback@webpack-internal:///../../../../zone.js/dist/zone.js:1543:17
```

What can be causing this? These errors are definitely not very descriptive...

**Comment by Zerokk** [comment]
Definitely some bug is going on. While trying to fix the previous bug, I just reverted back the changes to check what I could do, and now I get the very same error again (and the working changes that I said in the last post, are still there):

`Error: No NgModule metadata found for 'AchievedCombined_Module'. at NgModuleResolver.resolve (C:\Dev\Projects\AngularFrontend\MainModule\node_modules\@angular\compiler\bundles\compiler.umd.js:20277:23) at CompileMetadataResolver.getNgModuleMetadata (C:\Dev\Projects\AngularFrontend\MainModule\node_modules\@angular\compiler\bundles\compiler.umd.js:15230:60) at visitLazyRoute (C:\Dev\Projects\AngularFrontend\MainModule\node_modules\@angular\compiler\bundles\compiler.umd.js:31167:104) at visitLazyRoute (C:\Dev\Projects\AngularFrontend\MainModule\node_modules\@angular\compiler\bundles\compiler.umd.js:31171:17) at AotCompiler.listLazyRoutes (C:\Dev\Projects\AngularFrontend\MainModule\node_modules\@angular\compiler\bundles\compiler.umd.js:31135:20) at AngularCompilerProgram.listLazyRoutes (C:\Dev\Projects\AngularFrontend\MainModule\node_modules\@angular\compiler-cli\src\transformers\program.js:156:30) at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Dev\Projects\AngularFrontend\MainModule\node_modules\@angular\compiler-cli\src\ngtools_api.js:44:36) at AngularCompilerPlugin._getLazyRoutesFromNgtools (C:\Dev\Projects\AngularFrontend\MainModule\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:247:66) at Promise.resolve.then.then (C:\Dev\Projects\AngularFrontend\MainModule\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:538:50) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)`

It makes no sense that this error happens so randomly, and giving such low information... where is the module metadata, and why is it missing? How can I add, or fix it?

**Comment by alexzuza** [comment]
@Zerokk Can you create github repo with minimal code to reproduce it?

**Comment by Zerokk** [comment]
@alexzuza No, sorry, but if you have any doubts on my project setup just ask me, anyways I think it's pretty well explained.

**Comment by mlc-mlapis** [comment]
@Zerokk ... sorry but this is the exact case when we usually say on Gitter channel ... `It's time for a Stackblitz` .., because it is not possible to just guess what you exactly have locally. And believe that it is very true ... there were hundreds cases where people were willing to bet that it is on 1000% sure that it is an bug or an issuse and finally it was not ... just they didn't see the mistake or misunderstanding or typo.

But there were big effects in fact ... but unfortunately negative ... many hours spent on something what could be explained in several minutes.

**Comment by Zerokk** [comment]
I was about to create it, but I managed to fix it up!

My problem was that I was literally putting one project inside another. Really silly thing. I just pulled out the modules file and my components, put them in another project (which was containing the actual main module from which to perform the routing), and then everything started to work.
