### ISSUE TITLE
httpClient get a text utf from server

### ISSUE THREAD

**Issue by mfusaro27** [angular/angular#21554]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
hi, by making a call to the server using httpClient in angular 4.5 and waiting for me to reply a text I get a conversion error because it tries to convert the result to json. 

## Expected behavior
a text rapresentation send from server

## Minimal reproduction of the problem with instructions
This is my call:
 return http.get (url, {params: httpParams}, options, {responseType: 'text'}). subscribe (data => {let blob = new Blob ([data], {type: "text / plain; charset = utf-8 "});
        let datetime = new Date ();
        let fileName = ''; })

Even specifying response type I get an error when I read the answer. I kindly ask for help.

## Environment

<pre><code>
Angular version: 4.5

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:

Others:

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
