### ISSUE TITLE
Same [routerLink] directive (using named outlet) leads to different URLs

### ISSUE THREAD

**Issue by Stephane-Peyroutet** [angular/angular#21553]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
When calling the same [routerLink] directive (from two different "locations") we obtain different URL results.

## Expected behavior
The same [routerLink] directive should lead to one unique URL.

## Minimal reproduction of the problem with instructions

My routerLink directive is using a named outlet but I'm not sure how relevant this point is :
<pre><code>[routerLink]="[{ outlets: { dialog: ['edit'] } }]"</code></pre>

Here is the demo : https://stackblitz.com/edit/angular-cojkgf

- the call made from inside the main router-outlet (test.component.ts) yields to the following Url (/test/(dialog:edit) and works fine
- the call made from outside the main router-outlet (app.component.ts) yields to the following Url (/test(dialog:edit) and does not work => **there is a "missing" slash after test**.

This problem might be related to trailing slash issues such as :
 - #16051 (this issue is classified as feature request)
 - #14905 (this issue has been closed)

One final note is that I'm not even sure which Url should be working and if this should not be the other way aroud according to the [Angular Router](https://angular.io/guide/router#displaying-multiple-routes-in-named-outlets) docs 

## What is the motivation / use case for changing the behavior?
To have a consistent behavior when using the Angular router and its directives.
Here is one common use case :

1. have a list of item displaying on the main router-outlet

1. put a link/button at the end of the list for calling some sort of "add wizard dialog"

1. put a link/button in the header/toolbar for direct access to this main action (add wizard dialog)

## Environment

<pre><code>
Angular version: 5.x.x
Tested with StackBlitz (5.0.0) and personal environment (5.1.2)

Browser:
- [x] Chrome (desktop) version 63.0.32329.132 (Latest)
- [x] Firefox version XX
 
Others:
The problem is not browser related.
</code></pre>

**Comment by jasonaden** [comment]
I believe this is working as expected, but would need to look into it more to know for sure.

`/test(dialog:edit)` means that `/test` and `/edit` are *siblings* of each other
`/test/(dialog:edit)` means that `/edit` is a *child* of `/test`

I don't know that it's very intuitive, but basically the first example above is the same as using `//` inside a parenthesis (the denotation for siblings), but the slash vs missing slash only works at the root (it's not recursive). In other words:

`/test/(panel0:view//panel1:edit)` is not the same as `/test/(panel0:view(panel1:edit))`, where as `/test(dialog:edit)` should be the same as `/test//dialog:edit`.

Let me know if that helps debug anything. If not, I'll mark as a bug and we will look into it.

**Comment by Stephane-Peyroutet** [comment]
@jasonaden Yes, that helps at least about understanding.
I was not sure that this should be considered a bug in the first place.
This is just how the current router implementation works regarding the routerLink directive and siblings/childs.
I'll close this one and I will file another issue if something more inconvenient pops up about this.

**Comment by sokolovstas** [comment]
I think this is error. And I have found this error only when we migrate to angular 6 from angular 4.

Angular 4:
`[routerLink]="[{ outlets: { user: [user.username, 'general', 'edit'] } }]"`

Angular 6:
`[routerLink]="['/', { outlets: { user: [user.username, 'general', 'edit'] } }]"`
