### ISSUE TITLE
Infinite two-way binding loop when changing input value very quickly

### ISSUE THREAD

**Issue by rbluethl** [angular/angular#21551]
## I'm submitting a...
<pre><code>
[x] Bug report
</code></pre>

## Current behavior
I'm experiencing very strange behavior with a simple input component that provides a two-way binding of its value. If I enter characters very fast, the binding results in an infinity loop, setting the previous and current values over and over again.

Since I'm using DevExtreme components, I first suspected DevExtreme to be responsible for this behavior, but the issue is fully reproducable using a plain HTML input element with two-way Angular binding.

Please have a look at this [sample](https://stackblitz.com/edit/angular-q2tnzc), you just need to hit a few keys on you keyboard, then the binding will infinitely update.

[Reference DevExtreme ticket](https://www.devexpress.com/Support/Center/Question/Details/T581095/dxautocomplete-has-strange-behavior-when-entering-characters-fast-in-angular)

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-q2tnzc

## Environment
<pre><code>
Angular version: 5.2.0

Browser:
- [x] Chrome (desktop) version 63.0.3239.132
 
For Tooling issues:
- Node version: 8.9.4
- Platform: Windows 10 64bit

**Comment by alexzuza** [comment]
i think that's the reason:

```
new EventEmitter<string>(true);
```
Async emitter overlaps with your typing and causes infinity loop.

**Comment by rbluethl** [comment]
That seems to solve the issue. Thanks!
