### ISSUE TITLE
GithubBot messages are truncated

### ISSUE THREAD

**Issue by mhevery** [angular/angular#21566]
GithubBot messages are truncated which makes it hard to know what he action is.
![screen shot 2018-01-16 at 11 41 15 am](https://user-images.githubusercontent.com/111951/35008742-5c69522e-fab2-11e7-915d-6e64b809b0ec.png)

**Comment by ocombe** [comment]
This is a limitation of the github API, the status API only accepts messages of 140 characters maximum. It is not documented, but you'll get the following error: 
```sh
<rejected> { [Error: {"message":"Validation Failed","errors":[{"resource":"Status","code":"custom","field":"description","message":"description is too long (maximum is 140 characters)"}],"documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}]
```

The solution is to have a link to a page to see the details. It's possible to do that with our bot, we just need to code it.

**Comment by gkalpak** [comment]
Would it be possible to have a `Details` link point to a super simple page listing the issues in more detail (e.g. without truncating :grin:)?

**Comment by ocombe** [comment]
Yes that's what I said: "It's possible to do that with our bot, we just need to code it."
There's a templating system in probot that should make this possible, no need to host it anywhere else or anything.
