### ISSUE TITLE
add approver + target info into merge scripts

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21568]
When we merge PRs, we already rewrite the commit message to add info about the original PR.

We should extend this to add info about:
- who approved the PR
- what was the PR target

**Comment by gkalpak** [comment]
OOC, why (since that info is already available on GitHub)?

**Comment by IgorMinar** [comment]
Because it will speed up release review (a meeting where we sit down and go over all the commits merged since the last release).

**Comment by jelbourn** [comment]
Closing since it seems like we would never actually get to a point of prioritizing something like this
