### ISSUE TITLE
Angular Package Format (APF) v6

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21570]
Angular Package Format needs a several changes and corrections:

- Support webpack's "side-effects: false" optimizations (this is similar to what we are doing in rxjs v6 https://github.com/ReactiveX/rxjs/issues/3212)
  - [ ] update package.json spec
  - [ ] provide unflattened output (watch out for dev time rebuild latency regressions)
- implement APF v6 across all of our packages
  - [ ] framework
  - [ ] cdk
  - [ ] material
- tooling support
  - [ ] Bazel (via ng_package rule)
  - [ ] CLI

**Comment by Karasuni** [comment]
[The document](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit) appears to have been removed.

**Comment by IgorMinar** [comment]
it's back. it was taken down by system error.

**Comment by IgorMinar** [comment]
all tasks but material/cdk implementations are done. material and cdk have partial apf v6 implementation  (the most important bits) and will switch over to ng_package bazel rule in 6.0.x or 6.1.0 release which will bring them up to full compliance.
