### ISSUE TITLE
Text not displaying after form fields

### ISSUE THREAD

**Issue by ThomHehl** [angular/angular#21577]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In the attached project, the login page contains some text in a span tag with a class of error. This uses {{errorMessage}} field defined in login.component.ts and assigned a value.

This field does not display as is. Comment out the two input fields ahead of it and it will suddenly show up.

## Expected behavior
The error message field should display always

## Minimal reproduction of the problem with instructions
I have attached a minimal demo

## What is the motivation / use case for changing the behavior?
It should work right.

## Environment
Ubuntu/Firefox

<pre><code>
Angular version: Latest

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X

] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

Note that I have deleted the e2e and node_modules directories to save space.
[login-test.zip](https://github.com/angular/angular/files/1637161/login-test.zip)

**Comment by mlc-mlapis** [comment]
@ThomHehl  ... a simple reproduction demo is necessary. Your attached project is simply not the right way how to demonstrate the potential problem. Don't suppose that anybody will install it locally.

**Comment by ThomHehl** [comment]
@mlc-mlapis How shall I create the demo?

**Comment by mlc-mlapis** [comment]
@ThomHehl ... use http://stackblitz.com ... super easy and fast to demonstrate the simple demo with the problem.

**Comment by ThomHehl** [comment]
@mlc-mlapis OK, I've created https://stackblitz.com/edit/angular-uyyv72?file=index.html and put my code there, but I can't figure out what to put into index.html to make the whole thing work. Can you lend a hand, please?

**Comment by mlc-mlapis** [comment]
@ThomHehl ... hmm, what are you trying to put on `index.html`? Just the selector of the main component should be enough: `<app-root></app-root>` when `AppComponent` is your main = bootstrapped component.

**Comment by ThomHehl** [comment]
@mlc-mlapis Yes, that did it thanks. Now this is re-creating my issue. Now if you comment out the two input boxes, the message shows up. If you uncomment them, the message disappears again. This appears to be a bug.

**Comment by skreborn** [comment]
@ThomHehl This seems to occur because you're using `[(ngModel)]` on the inputs, but the properties you are binding to don't exist.

**Comment by ThomHehl** [comment]
@skreborn credentials is defined in login.component.ts. Is this not correct?

**Comment by mlc-mlapis** [comment]
@ThomHehl ... yes, @skreborn is right ...
![image](https://user-images.githubusercontent.com/5693835/35105243-6ee9a9a2-fc6b-11e7-9f8a-191d325ca01f.png)

**Comment by ThomHehl** [comment]
@mlc-mlapis Maybe I need to initialize those values in the ngOnInit()?

**Comment by skreborn** [comment]
@ThomHehl See my [updated comment](https://github.com/angular/angular/issues/21577#issuecomment-358678379). You can initialize (define) it where its declaration already is.

**Comment by mlc-mlapis** [comment]
@ThomHehl ... you can't bind to undefined property ...
`<input [(ngModel)]="credentials.username" placeholder="username">`

**Comment by ThomHehl** [comment]
@skreborn @mlc-mlapis  I have initalized both values and it doesn't appear to have changed anything.

**Comment by skreborn** [comment]
You haven't declared `credentials` to be an object though, so it's `undefined` in `ngOnInit`.

---

Anyhow, this isn't Angular's fault, and so this is a support request instead of a bug report. If you're still having trouble figuring this out, please open an issue on StackOverflow.

**Comment by mlc-mlapis** [comment]
@ThomHehl ... this `credentials;` is not an initialized property ... and continue with `this.credentials.username = ""` doesn't have a sense.

**Comment by ThomHehl** [comment]
@mlc-mlapis @skreborn That seems to have done it. Thanks for your help.
