### ISSUE TITLE
misleading test description in the forms validators spec

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21575]
https://github.com/angular/angular/blob/54bf17988874e3149c926b97b0b6f0677d4e49b5/packages/forms/test/validators_spec.ts#L274-L275

where is the line boundary in the test string? I don't see it. I believe this test shows that we don't match when line boundary is missing - it's a good test but the description is wrong, please correct it.

Can you also add the missing test please?

note: [original comment](https://github.com/angular/angular/commit/54bf17988874e3149c926b97b0b6f0677d4e49b5#r26897827)

**Comment by kara** [comment]
Edit: @IgorMinar and I discussed offline. Test should read

1should work with pattern string containing boundary symbols` to clarify

**Comment by ghetolay** [comment]
What I'm calling line boundary is the 'line starts with' (`^`) and 'line ends with' (`$`) symbols.

I'll do the PR tomorrow but what is the missing test ?

**Comment by kara** [comment]
I don't think there's a missing test. The test description was just confusing because it sounded like it had to do with multiline/single-line regexes instead of "string starts with", etc.

**Comment by ghetolay** [comment]
Ok sorry for that missunderstanding, I'm a better coder than English speaker :D.

If we were to provide full coverage of the code we could add 2 tests :
 - Only using `^` like `^aaAA`
 - Only using `$` like `aaAA$`
