### ISSUE TITLE
[Question] material / e2e

### ISSUE THREAD

**Issue by vicb** [angular/angular#2157]
@jelbourn tests have

```ts
beforeEach(() => { browser.get(url); });
```

should it be

```ts
beforeEach((done) => { 
  browser.get(url).then(done); 
});
```

/cc @juliemr

**Comment by jelbourn** [comment]
I based on mine on the existing e2e tests which do the same thing. They all seem to work fine for now, but it's probably brittle WRT the run environment.

**Comment by vicb** [comment]
Not sure if @tbosch hadn't updated some time ago ?

**Comment by vicb** [comment]
That's actually [this commit](https://github.com/angular/angular/commit/8b28e99) from @juliemr

**Comment by mhevery** [comment]
Obsolete? reopen if still needed.
