### ISSUE TITLE
Tree-shakable providers

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21576]
Currently if an NgModule is imported into the app directly or transitively, all of the providers defined in these packages are retained. This change will make the unused providers eligible for removal.

- framework support
  - [x] runtime
  - [x] compiler
- [x] update cli schematics
- [x] update style guide
- use the new APIs in our packages to make our providers tree-shakable
  - [ ] framework
  - [x] material / cdk

**Comment by cyrilletuzi** [comment]
Is there a reason the last item, "use the new APIs in our packages to make our providers tree-shakable", has been dropped?

The documentation now advises to use `providedIn: 'root'` by default, which is also the new default behavior of the CLI when generating services. But I see Angular classes like `HttpClient` are still done the old way, needing the `HttpClientModule` to still be loaded, and it may confuse users: their own services won't need a module, but the Angular ones still do.

**Comment by trotyl** [comment]
It's still WIP at https://github.com/angular/angular/pull/23209 (and likely also others follow-ups)

**Comment by IgorMinar** [comment]
all tasks but refactoring certain service in the framework are done. the remaining services will be refactored in the upcoming 6.x.x releases without introducing a breaking change.

**Comment by IgorMinar** [comment]
@cyrilletuzi it's just a matter of available time. the refactoring is not a breaking change so it's been deferred until other more risky changes land for v6. if you'd like to help and send us a PR we'll appreciate it - small PRs that convert just a one or a few related services at a time are the best.

**Comment by sandangel** [comment]
@cyrilletuzi I heard that NgModule will be optional in v7, I guess may be user only need to inject Service directly with non config service, or use custom config by {provide: CONFIG, useValue: config}...

for example, I suppose that the API will look like this:
```typescript
export const CONFIG = new InjectionToken<any>('config', {providedIn: 'root'})

@Injectable({providedIn: 'root'})
export class FooService {
  constructor(@Inject(CONFIG) config: any) {}
}

// app.module.ts
export const customConfig = {/*...*/}

@NgModule({
  /*...*/
  providers: [{provide: CONFIG, useValue: customConfig}]
})
export class AppModule {}

// app.component.ts
import {FooService} from 'lib'

@Component({/*...*/})
export class AppComponent {
  constructor(foo: FooService) {}
}
```

**Comment by trotyl** [comment]
@cyrilletuzi You could use `{ providedIn: YourModule }` instead of `{ providedIn: 'root' }` to keep the consistency of `NgModule` requirement.

Also it's not about configuration, but your decision to use `NgModule` static methods for configuration. That way would certainly depends on `NgModule`.

**Comment by cyrilletuzi** [comment]
@sandangel Your example is already what is now possible in v6. 

@trotyl There is a serious limitation with `{ providedIn: SomeModule }`, and CLI team explicitly discourage to do that. See angular/angular-cli#10170.

And yes, the question in the current state is: do I keep a module with a static method for custom configuration, or do I let users provide tokens again in AppModule like in @sandangel example. Both have pros and cons:

- NgModule with static method for configuration:
  - simpler for the user
  - but inconsistent: there is a module if custom config, and no module if default config

- Let the user provide the tokens again:
  - harder for the user
  - but consistent as no NgModule is needed at all

**Comment by josephliccini** [comment]
This might be tangential (and maybe we should have a different issue for potential issues with Tree-Shakeable Providers), but let's consider this scenario:

I define an abstract class like this (in 5.x)
```ts
export abstract class ConfigReaderService {
    public abstract parseConfig(id: string);
}
```

In one build (for the Browser app) I implement this `abstract` service via:
```ts
@Injectable()
export class BrowserConfigReaderService {
    public parseConfig(id: string) {
        return JSON.parse(document.getElementById(id).innerHTML));
    }
}
```

And provide to app via: 
```ts
@NgModule({
    providers: [
        { provide: ConfigParserService, useClass: BrowserConfigParserService }
    ]
})
export class BrowserServicesModule { }
```

```ts
@Injectable()
export class ServerConfigParserService {
    constructor(
        @Inject(REQUEST) private readonly request: Request
    ) { }

    public parseConfig(id: string) {
        return JSON.parse(this.request.body)[id];
    }
}
```

and provide via: 
```ts
@NgModule({
    providers: [
        { provide: ConfigParserService, useClass: ServerConfigParserService }
    ]
})
export class ServerServicesModule { }
```
Then in the `AppServerModule`, import `ServerServicesModule`, and in the `AppBrowserModule` (app for browser), import `BrowserServicesModule`.

Reading through the Tree-shakeable provider docs, I did not see a straightforward way to do this.

I could see this being a problem for Universal (I think Universal does a similar thing for HTTP to use Node.js's HTTP? I might be wrong here, but I think there's some default provider overriding in Universal..)

Is this case possible (maybe I missed something in the docs), how would we achieve this with `providedIn:`?  If it's not possible maybe we can brainstorm?  I think tree-shakeable providers is a really exciting feature, excited to trim down our bundles! 😄 

Thanks!
Joe

**Comment by cyrilletuzi** [comment]
@josephliccini Everything is tree-shakable now (classes, abstract classes, tokens). Look at one [exemple here](https://github.com/cyrilletuzi/angular-async-local-storage/tree/next/src/lib/src/service/databases) (LocalDatabase is the abstract).

`{ provide }` in NgModule `providers` is now only necessary when wanting to override an existing service/token. Then we come to my question.

**Comment by josephliccini** [comment]
Ah I see.  So the solution there is to do `useFactory`? but then both bundles will have both implementations in my case? since it only determines at runtime which to use.  (Cool library by the way.. @cyrilletuzi 😄 )

**Comment by cyrilletuzi** [comment]
Not sure of what you mean by implemented in both bundles.

About my initial question, I've come up to a third way, half-way from both of the others: just do a classic function returning the providers, something like this:

```typescript
import { libConfig } from 'my-lib';

@NgModule({
  providers: [libConfig({ options: ... })]
})
export class AppModule {}
```

So no module inside the lib, but still easy for the users.

Would like to have an official direction about the good practice.

**Comment by josephliccini** [comment]
I mean both `ServiceConfigParser` and `BrowserConfigParser` will both be included in both the Universal bundle, and the Browser bundle).  That is because `useFactory` is resolved at runtime.

What I'd like to have happen is basically this:
"During the browser bundling process, inject for `abstract class` `ConfigParserService` the `BrowserConfigParserService`, and _do not include_ `ServerConfigParserService` in that bundle in any way"

"During the server bundling process, inject for `abstract class` `ConfigParserService` the `ServerConfigParserService`, and _do not include_ the `BrowserConfigParserService` in that bundle in any way."

`useFactory` won't be able to do this because that means it will include _both_ `ServerConfigParserService`, and `BrowserConfigParserService` in the bundle, and during application runtime, it will decide which to use.  Something like a compile-time `useFactory`.

Here's what it would look like:

```ts
function configParserFactory(platformId: string, request: Request) {
    if (isPlatformServer(platformId)) {
        return new ServerConfigParserService(request); // <-- will need this service included in the app-server-bundle.js and app-browser-bundle.js because this codepath isn't hit until runtime
    } else {
        return new BrowserConfigParserService(); // <-- will need this service included in the app-server-bundle.js and app-browser-bundle.js because this codepath isn't hit until runtime
    }
}

@Injectable({
    providedIn: 'root',
    useFactory: configParserFactory,
    deps: [ PLATFORM_ID, REQUEST ]
})
export abstract class ConfigParserService {
    public abstract parseConfig(id: string): object;
}
```

I can make a separate issue.. sorry for hijacking the thread here..
