### ISSUE TITLE
Peruvian currency symbol not showing, instead the currency code shows

### ISSUE THREAD

**Issue by Loutrinos** [angular/angular#21588]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

After registering the Peruvian locale (es-PE) and getting proper data for date and numbers, the currency symbol (S/) is not showing and instead the currency Code is present (PEN)

## Expected behavior

When using the Peruvian locale and the currency pipe I should see the peruvian currency symbol.

## Minimal reproduction of the problem with instructions

You can see a simple implementation of the CurrencyPipe using the PEN currency code:
https://stackblitz.com/edit/angular-xz9jsn?file=app%2Fapp.component.html

## What is the motivation / use case for changing the behavior?

It seems that the es-PE locale is loaded properly from cldr:
https://github.com/angular/angular/blob/5.1.x/packages/common/locales/es-PE.ts
but not the equivalent currency symbol:
https://github.com/angular/angular/blob/master/packages/common/src/i18n/currencies.ts
as a result the `getCurrencySymbol` run internally returns the code rather than the symbol.

There seems to be a problem fetching the currency symbol during the cldr.extract

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ocombe** [comment]
`PEN` is not listed in the currencies, because the symbol for `PEN` in english is the same as the currency code in the CLDR data: https://github.com/unicode-cldr/cldr-numbers-modern/blob/master/main/en/currencies.json#L1252-L1257

We are working on getting locale symbols for currencies, but there is already an issue for this, see #20385.
I'm closing this one since it's a duplicate.
