### ISSUE TITLE
Conversion of JSON date into Date

### ISSUE THREAD

**Issue by aneesazam** [angular/angular#21587]
I have used Angular2 - 4.x and did not get any issue of date conversion but as I updated to Angular 5.x. I am getting following logical error:-

If I enter date upto 31 Dec 2009, following javascript method which was working well, now convert it to one date back. i.e   If enter, 1 Aug 2008, it shows 31 Jul 2007.
If date is in year 2010 or later, it works fine.

**ToJavaScriptDate(value: any) {
        var pattern = /Date\(([^)]+)\)/;
        var results = pattern.exec(value);
        var dt = new Date(parseFloat(results[1]));

return (dt.getMonth() + 1) + "/" + dt.getDate() + "/" + dt.getFullYear();**
//or simple return 
      //  return dt;
    }****

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by aneesazam** [comment]
Eric Martinez,


Thank you so much for response and suggestion.


Regards

Anees Azam


________________________________
