### ISSUE TITLE
Value change in observable subscription not triggered in async pipe

### ISSUE THREAD

**Issue by sroeger** [angular/angular#21584]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
A change of a value (observable 'A') that is triggered by a subscribed observable (observable 'B') in a smart component does not reflect to the dumb component that is fed by an async pipe of observable 'A'.  We use a store to save all of our app's states (see plunkr).

## Expected behavior
The change can be seen in the dumb component as soon as one changes the value.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/l61VBFuybdCyyoNZIKro?p=preview

Enter some value (e.g. 'test') in the input field and click the button.
This publishes the value in the observable 'value'. 
In the app.ts one subscribes to that observable, so we get that value there. In the body of that subscribe the entered value is published in another observable 'name'.
The dumb component is fed by an async pipe which subscribes on the observable 'name'.
'test' can not be seen in the dumb component now.

If you hit the button a second time, you can see the value in the dumb component.
You can also delay the new value with a setTimeout to get it working.

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
You can see that your observable is emitting `undefined` value [if you add a `console.log`](http://plnkr.co/edit/mM07cRpIilWCRDX8GleP?p=preview), it's the problem of your own data source: 

```typescript
name$ = this.store.state$.pipe(
  tap(n => console.log(`tap1: ${JSON.stringify(n)}`)),
  map(s => s.name),
  tap(n => console.log(`tap2: ${n}`)),
  distinctUntilChanged(),
  tap(n => console.log(`tap3: ${n}`)),
);
```

**Comment by sroeger** [comment]
I can see that the observable is emitting two values where the first is the correct/expected one. The second emit is the previous value. I don't get why it emits two values.

```
setValue: {"name":"first value","value":"second value"}
value$: second value
setName: {"name":"second value","value":"second value"}
tap1: {"name":"second value","value":"second value"}
tap2: second value
tap3: second value
tap1: {"name":"first value","value":"second value"}
tap2: first value
tap3: first value
```

**Comment by trotyl** [comment]
You'll get the same behavior [without using `async` pipe](http://plnkr.co/edit/mM07cRpIilWCRDX8GleP?p=preview), since it's not an issue of Angular, you'd raise your to related project or other support channels.

You can find more information in [CONTRIBUTING guide](https://github.com/angular/angular/blob/master/CONTRIBUTING.md).

**Comment by sroeger** [comment]
Well, i can subscribe in the store directly. If i do so i get the expected emitted value.
http://plnkr.co/edit/QJjN5IluesJxO85SNUhS?p=preview

**Comment by trotyl** [comment]
GitHub issues are for bug report and feature request, not for RxJS tutorials. Please respect the  CONTRIBUTING guide.

**Comment by pschmoek** [comment]
I think, there is an issue with the async pipe. Subscribing to the Observable inside the component works just fine. Subscribing via async pipe does not.

inside component: http://plnkr.co/edit/bmnpcfra7uHnRROmyUjo
inside template via async pipe: http://plnkr.co/edit/QXHHGjoLUoToKDpK3pnX

**Comment by trotyl** [comment]
@pschmoek It won't work if you [subscribe `name$` after `value$`](http://plnkr.co/edit/9ygYXcvMBVlz5dm451n2?p=preview), as already said above.

**Comment by pschmoek** [comment]
@trotyl that's really interesting, but it shouldn't matter at all, since ngOnInit() runs through sychronously and both subscribe handlers are invoked in later micro tasks.

So the async pipe is not working because it is initialized after ngOnInit().

But this shouldn't be the case? correct me if i'm wrong

**Comment by trotyl** [comment]
@pschmoek It's the intrinsic evil of synchronous bi-directional event stream, not related to Angular part. I won't suggest depending on this kind of vulnerable code.

**Comment by aerojeyenth** [comment]
@Toxicable I am facing the same issue. If the parent container's ngIf value changes from false to true it do not trigger subscription in the childComponent's async pipe, but the same component trigger the subscription if comes from a different route. I sincerely feel its a bug with the async pip or ngIf.
