### ISSUE TITLE
Pushing FormControl to the disabled FormArray makes it enabled

### ISSUE THREAD

**Issue by prudnikov** [angular/angular#21581]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Here is sample code

    const form = new FormArray([]);
    form.disable();
    form.push(new FormControl('1'));
    console.log(form.disabled); // false
    console.log(form.controls[0].disabled);

There are two issues with this code: 
 * it marks form as enabled
 * it emits `valueChanges` event when calling `push()`, probably because form was marked as enabled during this call.

## Expected behavior

Form should still be disabled after adding a new control to it. Also newly added control should become disabled when added to the disabled FormArray.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/hZAuLIbNRFqFHe3CUqHL?p=preview

## What is the motivation / use case for changing the behavior?
Modifying form controls should not change disabled state of the form.

## Environment

<pre><code>
Angular version: 5.2

Browser:
- [ ] Chrome (desktop) version 63.0.3239.132 (Official Build) (64-bit)
- [ ] Safari (desktop) version 11.0.2 (13604.4.7.1.6)
 
For Tooling issues:
- Node version: 8.8.1  
- Platform:  Mac
</code></pre>

**Comment by kara** [comment]
This is expected behavior. Forms with at least one enabled control are no longer considered disabled.  So when you push an enabled control, this enables the form. You might try pushing a disabled control (`new FormControl({value: '1', disabled: true})`), if you'd like it to be disabled.
