### ISSUE TITLE
Confusing DI behavior between Router and ChangeDetectorRef

### ISSUE THREAD

**Issue by RamyHakam** [angular/angular#21582]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[1 ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

 If I tried to use Router and ChangeDetectorRef together Its gives me this error 
 Cannot read property 'router' of null
I want router to detect active url and  ChangeDetectorRef 
this is simple code 

<pre><code>
import { Component, ChangeDetectorRef ,ChangeDetectionStrategy } from '@angular/core';
import { user_local } from './Models/local_user';
import { Router , RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

constructor( private router:Router , private detect: ChangeDetectorRef){
if(localStorage.getItem('user_id')){  
this.detect.detectChanges();    
}
}
</code></pre>
If I delete one of them from the constractor  the other will work 

## Expected behavior

It must work togehter on the same time on the same component  

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/41KyIGsbIrneHIvZg5UN.

## Environment

<pre><code>
Angular version: 5.0.0

For Tooling issues:
- Node version: 9.4 
- Platform: Linux   

Others:

</code></pre>

**Comment by vicb** [comment]
The plunker does not seem to work, could you provide an app on StackBlitz ?

**Comment by Z-Team-Pro** [comment]
This is it 
https://stackblitz.com/edit/angular-i6s4db

**Comment by trotyl** [comment]
This is about triggering another change detection inside an existing change detection, possibly Angular should just throw an error like AngularJS?

> Error: [$rootScope:inprog] $apply already in progress 
> http://errors.angularjs.org/1.x.y/$rootScope/inprog?p0=%24apply

**Comment by atscott** [comment]
Per @trotyl's comment, this is now an error in Ivy: https://stackblitz.com/edit/angular-ivy-qrkd7d?file=src%2Fapp%2Fapp.component.ts
It's invalid to trigger change detection via `detectChanges` during the creation of a component.
