### ISSUE TITLE
loading angular modules as plugins 

### ISSUE THREAD

**Issue by sunilpes** [angular/angular#21583]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Loading angular modules as plugins during the run-time is not supported officially. We have a workaround to achieve it using '@angular/compiler' module. I am not happy to use low-level API of angular in my project. 

when I was working with angular.js version 1.x. we were using [ocLazyLoad](https://oclazyload.readme.io/) library to load and register the angular module during runtime.

## Expected behavior
Can we expect dynamic loading and registering the module as plugins with angular? This would really help a lot of use cases.

## What is the motivation / use case for changing the behavior?
We are trying to build a pluggable editor tool using angular. Plugins are angular modules. Host environment i.e editor app module has no prior knowledge about the plugins(modules with its own components, services) which is going to instantiate. All plugins are registered during the runtime. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@sunilpes ... this theme (dynamic loading of lazy loaded modules) is discussed in several issues, just go through ...

**Comment by jelbourn** [comment]
Tracking the main underlying concern here in #18093
