### ISSUE TITLE
document in https://angular.io/guide/dynamic-component-loader

### ISSUE THREAD

**Issue by SuperDoudou** [angular/angular#21593]
[x] Documentation issue or request

In the document https://angular.io/guide/dynamic-component-loader 

src/app/ad-banner.component.ts 
template: `
            <div class="ad-banner">
              <h3>Advertisements</h3>
              <ng-template ad-host></ng-template>
            </div>
          `

the class="ad-banner" will be hiden by Adblock, i use a lot of time to figure out the problem.
I wish the problem should no happen to other new angular developer

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/18138

**Comment by jenniferfell** [comment]
@SuperDoudou Thanks for reporting this.
@ericmartinezr Thanks for referencing the other issue. I'll close this one and keep that one open.
