### ISSUE TITLE
Embedded <style> for dynamic values

### ISSUE THREAD

**Issue by amolnw2778** [angular/angular#21597]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The embedded `<style>` is not rendering with the dynamic values. 
See https://stackblitz.com/edit/angular-y1jwgr?file=app%2Fapp.component.html

## Expected behavior

Embedded `<style>` should render with provided dynamic values for selector and its properties.

## Minimal reproduction of the problem with instructions

Check this StackBlitz example https://stackblitz.com/edit/angular-y1jwgr?file=app%2Fapp.component.html

## What is the motivation / use case for changing the behavior?

The embedded `<style>` was rendering properly with dynamic values in AngularJS 1.3x.
However it doesn't work as expected in Angular 5.x.
In given example, hover style can be applied through javascript, but that's not what I am looking for. The CSS should do its work instead writing javascript for simple and neat CSS.

This is a very simple example given here. I have a very big and complex SVG graph where it was smoothly styled using embedded `<style>` with lots of dynamic values. Almost each SVG item has its own styling based on its dynamic ID. Writing javascript over CSS is so silly, when CSS itself can do the magic. 

Angular should have this feature ASAP!

## Environment

<pre><code>
Angular version: 5.1.2
Angular CLI: 1.6.2

Browser: Issue is not browser specific
 
For Tooling issues:
- Node version: 8.9.1  
- Platform:  Windows 7 x64 

Others:

IDE: Visual Studio Code: 1.16.1 x64
</code></pre>

**Comment by vicb** [comment]
`<style>` are extracted before compilation and interpolation do not work there in Angular. So it works as expected.

You can probably use ngStyle or ngClass instead.

**Comment by amolnw2778** [comment]
@vicb `ngStyle` or `ngClass` or plain javascript is not what I am looking for.
I have case where style of all child elements changes based on dynamic id. For example:
```
.item-3:hover * { background-color: yellow; }
.item-3:hover > div { border-color: brown; }
.item-3 .place { color: lime; background-image: url(https://placekitten.com/200/300); }
.item-3:hover .place { color: yellow; background-image: url(https://placeimg.com/200/300/any); }
```
I have even more complex structure to style for our SVG graph. `ngStyle` , `ngClass` are not helpful in this case.
I don't know why Angular forces developers to make things complex, harder and unclean. Things which can easily be controlled through CSS only.

**Comment by mlc-mlapis** [comment]
@amolnw2778 ... use CSS variables ... they are ideal for that.
