### ISSUE TITLE
Component in another directory tree can't import from node_modules

### ISSUE THREAD

**Issue by ksamuel** [angular/angular#21596]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have a tsconfig file containing:

"rootDir": "/home/user/workspace/Company/Project/frontend/src",
"baseUrl": "/home/user/workspace/Company/Project/frontend/node_modules",
"paths": {
  "@Project_common/*" : ["/home/user/workspace/Company/Project/frontend/src/core/CommonStuff/*"],
  "@Project/*" : ["/home/user/workspace/Company/Project/frontend/src/*"],
  "@validation/*" : ["/home/user/workspace/Company/external_module/frontend/app/*"],

The goal is to include components from "/home/user/workspace/Company/external_module/frontend/app/" into our build despite the fact it's located completly outside of our project directory tree.

When we build this, it fails on:

ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /home/user/workspace/Company/external_module/frontend/app/node_modules/@angular/core/core.d.ts, resolving symbol GnValidationModule in /home/user/workspace/Company/external_module/frontend/app/gnValidation.module.ts, resolving symbol GnValidationModule in /home/user/workspace/Company/external_module/frontend/app/gnValidation.module.ts

## Expected behavior
It seems that for imports in "external_module", the compiler tries to lookup @angular in "/home/user/workspace/Company/external_module/frontend/app/node_modules" instead of "/home/user/workspace/Company/Project/frontend/node_modules".

Imports in any components from /home/user/workspace/Company/Project/frontend/src are not affected and look up correctly dependancies in "/home/user/workspace/Company/Project/frontend/node_modules".

## Minimal reproduction of the problem with instructions
 
- Use a brand new tsconfig file
- give an @alias to your components from the src directory so that a third party module can import it with @stuff
- give an @alias to your components to the src directory of a third party module no in the main directory tree
- import @angular/core in third party module

## What is the motivation / use case for changing the behavior?

There is only one node_modules that is already detected. It should be consistent.

## Environment

<pre><code>
Angular version: 4.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x] Firefox version 56
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by chuckjaz** [comment]
@ksamuel Can you supply a repository that can be cloned that reproduces this issue?

**Comment by ksamuel** [comment]
No. We found a workaround that worked specifically for us and we moved on. I apologize to not give more time on this. You can close it, until somebody stumble up on it again and reopen it with more details.

**Comment by mhevery** [comment]
closing as non-reproducible
