### ISSUE TITLE
@angular/language-service problems with VSCode and Language Service Extension

### ISSUE THREAD

**Issue by jtsom** [angular/angular#21591]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

While version 5.2 of Angular says it is compatible with TypeScript 2.6, using that combination with VS Code (latest Insiders version with the Angular Language Service extension) does not work properly. While editing html, there is no intellisense popups or hover-over information.

## Expected behavior

Hovering over an item in an html file should produce a popup showing the type of the variable:

![image](https://user-images.githubusercontent.com/13488/35045005-6d14663c-fb60-11e7-8bb7-4ace962eac53.png)

This popup does not appear if Typescript 2.6 is install in the project

## Minimal reproduction of the problem with instructions

In a new project, change the version of Typescript in the package.json file to be > 2.5 

"typescript": "2.6.2"

NPM Install to install the new version

Try to hover any variable in an html page, or try to get intellisense when typing something within {{ }} 's

## What is the motivation / use case for changing the behavior?

Correct functionality of the editor.

## Environment

<pre><code>
Angular version: 5.2.0

Browser: N/A
 
For Tooling issues:
- Node version: 9.4
- Platform:  Mac

Others:

</code></pre>

**Comment by cyrilletuzi** [comment]
@chuckjaz I confirm this issue.

**Comment by kyliau** [comment]
We are aware of this and we have filed a bug with Typescript here: https://github.com/Microsoft/TypeScript/issues/20321

**Comment by kyliau** [comment]
closing this since the latest version has been updated to support Typescript 3.1
