### ISSUE TITLE
How i format this @pipe currency with space ?

### ISSUE THREAD

**Issue by ingles200horas** [angular/angular#21598]
My pipe current print :
`{{ 200 | currency:'BRL':true }}` = R$200.00

I need include space between R$ in 200.00 
would stay correct 
`{{ 200 | currency:'BRL':true }}` = R$ 200.00`

somebody can help me?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by vicb** [comment]
The `R$200.00` is the format defined by the CLDR. You would have to create your own pipe to change the format.

**Comment by abhilashasokan** [comment]
**Create a new pipe that receive the currency as input.**

`import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'space'
})
export class SpacePipe implements PipeTransform {
  transform(value: any, args?: any): any {
    return 'R' + value.substring(0, 1) + ' ' + value.substring( 1);
  }
}`

After that you can call them like this

{{discount | currency: 'EUR' | space}}

Dont forget to include it in @NgModule -> declarations
