### ISSUE TITLE
Update Angular Authors Style Guide to recommend sentence caps

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#21605]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Author's Style Guide recommends Title Caps

## Expected behavior

Recommend Sentence caps to align with Google dev doc guidelines: https://developers.google.com/style/

## What is the motivation / use case for changing the behavior?

Align with Google guidelines

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
@IgorMinar Jules suggested we follow Google Dev Doc guidelines because those guidelines are more complete than Angular and had a very large investment of time/expertise. One thing that would mean is updating Angular guidelines to use "Sentence caps" in the page title for each doc page (not the nav titles). In my experience, "Sentence caps" have become an industry standard for in-page titles in tech doc. 

Do you agree with this style change?

**Comment by jenniferfell** [comment]
docsarea=standards

**Comment by jbogarthyde** [comment]
If we do this, we have to go change the headings in this style doc at least, and probably all of the rest of the guides as well. 
A lot of pages (including this one!) use title-style for the H1, and sentence-style for all other headings.

**Comment by jbogarthyde** [comment]
Fixed by PR
