### ISSUE TITLE
[Feature request] Check if a lazy loadable module has been loaded and explicitly load a lazy loadable module

### ISSUE THREAD

**Issue by MJomaa** [angular/angular#21603]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
I cannot check if a lazy loadable module has been loaded.
I cannot explicitly load a lazy loadable module.

## Expected behavior
API for checking if a lazy loadable module has been loaded.
API for explicitly loading a lazy loadable module.

## Minimal reproduction of the problem with instructions
None

## What is the motivation / use case for changing the behavior?
We are developing a visual builder that can use add-ins. To activate an add-in a user has to check the respected checkbox, thus explicitly loading the lazy loadable module if it is not already loaded.

**Comment by mlc-mlapis** [comment]
@MJomaa ... look at ... escpecially `getModuleFactory(id: string)`:
```
export declare abstract class NgModuleFactoryLoader {
    abstract load(path: string): Promise<NgModuleFactory<any>>;
}
export declare function registerModuleFactory(id: string, factory: NgModuleFactory<any>): void;
export declare function clearModulesForTest(): void;
export declare function getModuleFactory(id: string): NgModuleFactory<any>;
```

**Comment by kqadem** [comment]
@mlc-mlapis May you add some docs/guides about this, since SystemJsNgModuleLoader has been marked deprecated with 8.0.0?

**Comment by mlc-mlapis** [comment]
@kqadem … It is the dynamic import, like: `import('./modules/login/login.module').then(m => m.LoginModule)`.

**Comment by kqadem** [comment]
So it's enough to add the `id` property to an NgModule and then I can get the factory with `getModuleFactory`? 
Are there differences to `NgModuleFactoryLoader` except that I get a `Promise` instead of the actual value? Since it's abstract, how do I even get an instance of it? Usual DI?

**Comment by mlc-mlapis** [comment]
@kqadem … it depends also if the mode is JIT (where you load a class) or AOT (where you load a factory), so you have to do something similar as `router_config_loader.ts`. The rest is exactly the same as before, I think. 
```
private loadModuleFactory(loadChildren: LoadChildren): Observable<NgModuleFactory<any>> {
    if (typeof loadChildren === 'string') {
      return from(this.loader.load(loadChildren));
    } else {
      return wrapIntoObservable(loadChildren()).pipe(mergeMap((t: any) => {
        if (t instanceof NgModuleFactory) {
          return of (t);
        } else {
          return from(this.compiler.compileModuleAsync(t));
        }
      }));
    }
}
```
https://github.com/angular/angular/blob/master/packages/router/src/router_config_loader.ts

**Comment by jasedwards** [comment]
I am doing something similar but in AOT mode it is never type NgModuleFactory.  so the else executes and then I get an error that there is no run time compiler

**Comment by dylhunn** [comment]
This is now obsolete, this should be possible.
