### ISSUE TITLE
Service Worker doc page titles do not follow Google dev doc style guide

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#21604]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Doc page titles use title caps

## Expected behavior

Doc page titles should use sentence caps, per Google dev doc style guide 

## What is the motivation / use case for changing the behavior?

Directive early in this project to follow Google Dev Doc guidelines, and to begin aligning Angular doc guidelines with those. https://developers.google.com/style/

## Environment

<pre><code>
Angular version: stable

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>
One example page: https://angular.io/guide/service-worker-intro

**Comment by BrianDGLS** [comment]
This looks to be fixed see #21620

**Comment by chembu** [comment]
Yes, fixed it.

**Comment by jenniferfell** [comment]
Confirmed fixed.
