### ISSUE TITLE
Not able to install Angular on my machine. Tried different versions

### ISSUE THREAD

**Issue by manojgupta006** [angular/angular#21600]
## Current behavior
While installing angular using Node command prompt in Admin mode I am getting the below error:
npm ERR! code EINTEGRITY
npm ERR! sha1-PFtv1/beCRQmkCfwPAlGdY92c6Q= integrity checksum failed when using sha1: wanted sha1-PFtv1/beCRQmkCfwPAlGdY92c6Q= but got sha1-QOF5it9dFx2l83cPdPPY1SXo3ic=. (736870 bytes)

## Expected behavior
The installation should complete

## Minimal reproduction of the problem with instructions
I have attached the log file for details

## Environment

<pre><code>
Angular version: 5.5.1, 5.6.0

Browser:
Chrome
 
For Tooling issues:
- Node version: 8.9.1, 8.9.4, 9.3.0
Windows

[2018-01-17T16_17_12_074Z-debug.log](https://github.com/angular/angular/files/1640055/2018-01-17T16_17_12_074Z-debug.log)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Try angular-cli's repo https://github.com/angular/angular-cli
