### ISSUE TITLE
The live example in Angular doc is broken

### ISSUE THREAD

**Issue by 0229xiang** [angular/angular#21616]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Expected behavior

The [live example](https://embed.plnkr.co/?show=preview) in Angular doc is broken

## Minimal reproduction of the problem with instructions

open Angular doc,,[example](https://angular.io/guide/pipes), find the _live example_ link and click it, it was broken, only return `{"message":"An internal server error occurred","statusCode":500,"error":"Internal Server Error"}` 
## What is the motivation / use case for changing the behavior?

I can't overview the doc intuitively;

## Environment

<pre><code>
Angular version: latest

Browser:
- [ x ] Chrome (desktop) version 56.0.2924.87 (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  6.0
- Platform:  windows

Others:

</code></pre>

**Comment by gkalpak** [comment]
This is an error with plnkr (specifically with creating embedded plnkr programmatically).

##
As a temporary workaround, you can right-click on `live-example`, copy the URL, paste it into the address bar and replace `eplnkr.html` with `plnkr.html`.
For example, https://angular.io/generated/live-examples/animations/eplnkr.html would become https://angular.io/generated/live-examples/animations/plnkr.html.

**Comment by m0uj** [comment]
A duplicate of [19056](https://github.com/angular/angular/issues/19056)

**Comment by gkalpak** [comment]
It is the same issue, but this is a new occurrence 😒

**Comment by 0229xiang** [comment]
I have tried again , it is fixed now.
