### ISSUE TITLE
FormGroup with multiple FormGroupDirectives and submitted state

### ISSUE THREAD

**Issue by prasannapattam** [angular/angular#21617]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

This is some what related to #21263.
Angular creates FormGroupDirective every time a FormGroup is specified at a tag level

      <form [formGroup]="userForm" (ngSubmit)="submitForm()" novalidate>
          <div [formGroup]="userForm">
            First Name: <input formControlName="first">
          </div>
          <button type="submit">Submit Form</button>
      </form>

In the above code 2 FormGroupDirectives are created for the same FormGroup, userForm.

When the form is submitted, only the first FormGroupDirective is set to submitted.

## Expected behavior

Set all the FormGroupDirectives to submitted when the FormGroup is same. For sub/child/nested form groups we can leave the current functionality as it is (different FormGroups will have different FormGroupDirective.submitted tag). 

Alternatively add a submitted flag to the FormGroup itself.

## Minimal reproduction of the problem with instructions

Here is plunker with the above. When you click the submit only the first FormGroupDirective.submitted is set to true
http://embed.plnkr.co/MYFfG1mNRQoowMyuMOLV/

## What is the motivation / use case for changing the behavior?

As you know if we have to define part of a form in a component, we have to use <div [formGroup]="">. In my scenario, I am using Material Design and created a component which abstracts all the material code and also included error handling. 
https://github.com/Nootus/0xServices/blob/master/src/0xServices.Web/ClientApp/app/core/controls/NtInputComponent.html 
I am using this component instead of input tag. Inside this component I have to use div formGroup. So a new FormGroupDirective is created everytime my wrapper component is used. The FormGroup is same, this FormGroup now have several FormGroupDirectives.

In Material while displaying error I want to check whether the form is submitted or not. In my scenario every control has a FormGroupDirective and this directive will not have the submitted flag set to true.

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dominique-mueller** [comment]
I don't think it's possible to assign the same form group twice. Why not get rid of the deeper one?

**Comment by prasannapattam** [comment]
You can assign the same FormGroup multiple times. This is required when you put the textbox in a component, like this

  <form [formGroup]="userForm" (ngSubmit)="submitForm()" novalidate>
      <first-name></first-name>
      <button type="submit">Submit Form</button>
  </form>

First Name component will have this code:
      <div [formGroup]="userForm">
        First Name: <input formControlName="first">
      </div>

**Comment by kara** [comment]
See https://github.com/angular/angular/issues/21263#issuecomment-357074997. The problem would be better solved with a `submitted` flag on the model.

**Comment by prasannapattam** [comment]
I agree that adding submitted flag to FormGroup is a better option.

I already saw and mentioned #21263 while opening this issue. There is no open issue to track this feature change of adding submitted flag to FormGroup. Better leave this open till the functionality is implemented.

**Comment by kara** [comment]
@prasannapattam You're right that we need a dedicated issue, but I think the alternative solution / use case in this one might be confusing. I've opened a new one here, so anyone interested can track it: https://github.com/angular/angular/issues/21823
