### ISSUE TITLE
UrlMatcher: null should be declared as possible return-value

### ISSUE THREAD

**Issue by andresenmichael** [angular/angular#21624]
https://github.com/angular/angular/blob/af4eb00c9191f3eedfbb2b0bc6c471cd55f892a6/packages/router/src/config.ts#L268-L290

As shown in the documented example above `null` is a possible return-value.

If the property strictNullChecks is enabled in tsconfig.json, the error "ts2322" occurs.

**Comment by DustinJSilk** [comment]
Any update or any more information on this bug at all? The compiler breaks when returning null, undefined, or false. If i return `{consumed: []}` the compiler and linter are happy. And every page except for my home page works.

**Comment by bitjson** [comment]
Both #22898 and #24464 have been opened to fix this issue.

It looks like #22898 is ready to merge, and solves the issue completely. Can a maintainer take a look?

**Comment by sod** [comment]
This is stil super annoying. And before the stale-bot closes this, I add a comment.

**Comment by atscott** [comment]
Resolved by #36402
