### ISSUE TITLE
elementMatches error when given a text node

### ISSUE THREAD

**Issue by adamdbradley** [angular/angular#2162]
When creating a dynamic component through ViewContainerRef#create, it eventually calls `elementMatches()`, which in my app it is possible to pass a `text` node.

However, when running this code:

```
elementMatches(n, selector: string): boolean {
    return n instanceof HTMLElement && n.matches ? n.matches(selector) :
                                                   n.msMatchesSelector(selector);
  }
```

`msMatchesSelector` attempts to be executed on the text node, which doesn't exist.

https://github.com/angular/angular/blob/15f1eb28a2c7c3af40aa8882c89e28014f2fa582/modules/angular2/src/dom/browser_adapter.ts#L194

Also, I am able to prevent this error by providing a template without any text nodes, but in most cases there may be at least one text node in the array which `expandedDomNodes()` created.

Would it be possible to either have `expandedDomNodes` not collect text nodes, or update `elementMatches` to return false if the node is not an HTMLElement, or it doesn't have `.matches()` and doesn't have `.msMatchesSelector()`;

**Comment by mlynch** [comment]
Stack trace with more info:

![screenshot 2015-05-27 11 26 00](https://cloud.githubusercontent.com/assets/11214/7841580/34f2a3fa-0463-11e5-83ad-a48f074e16ee.png)

**Comment by mlynch** [comment]
More info: this seems to only happen when using `<content select>`. Still trying to find a meaningful test case.

**Comment by tbosch** [comment]
We are replacing our content projection with a new and faster mechanism (see #2529). In there, we don't call `elementMatches` only during compilation, so this should not be a problem any more.

**Comment by Y-Less** [comment]
I hit the same problem today and found the same issue.  The root cause is (I believe) operator precedence, thus the code becomes:

```js
  elementMatches(n, selector: string): boolean {
    return n instanceof HTMLElement && (n.matches ? n.matches(selector) :
                                                   n.msMatchesSelector(selector));
  }
```

I also thought the use of `msMatchesSelector` was wrong and should be a polyfilled `matchesSelector`, but I think the intent (made clearer just by adding the brackets) was to use that in the only case where `n.matches` doesn't exist - i.e. IE browsers.  If that's not the case, I guess that needs changing too.

**Comment by Y-Less** [comment]
An alternate solution if you don't want to modify the angular source and instead want an external patch to go in, say, your top-level HTML, is:

```js
window.Text.prototype.msMatchesSelector = function () { return false; }
```

**Comment by tbosch** [comment]
We now are using a new content projection that projects during compile time in master. I.e. we don't call `element.matchesSelector` when views are instantiated any more.
