### ISSUE TITLE
Series indexing issue after updating to Angular 5

### ISSUE THREAD

**Issue by mbn18** [angular/angular#21625]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Following an update to `Angular 5` in early December, we started experiencing a series indexing problem. Some **70%** of our root domain pages (`www.infogan.co.il`) were **de-indexed**. The subdomains (which are based on `Joomla`) doesn't seem to be effected.
We checked all the usual suspects (robots.txt, meta robots, rel=canonical, `WMT` Remove URL, Non-http/non-www all 301 redirects etc.), and are pretty sure it has nothing to do with an algorithm update or a penalty, and technically our traffic from `Google` is almost the same (other pages rank for queries were the de-indexed pages were supposed to be).
Early on, we found that rendered pages from the site look as blank pages (via `WMT` Fetch and Render), due to `Googlebot` using an old `Chrome` rendering engine. We fixed this on the December 15th but it didn’t change much.
We asked for help both in the [Webmaster Central Help Forum](https://goo.gl/LeAJ48) and the [Angular and AngularJS](https://goo.gl/48k5E6) discussion group. None of the answers we got seem applicable. Earlier this week we updated to `Angular 5.2`, which doesn’t seem to solve the problem either.

## Environment

<pre><code>
Angular version: 5.2.0

 
For Tooling issues:
- Node version: v8.9.1
- Platform:  Linux

Others:

</code></pre>
Platform is fast and clean. Rate A at [WebPagesTest](https://www.webpagetest.org/result/180116_4S_59e55a1dfdc65e148094fae374347a86/)

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by filipesilva** [comment]
Heya I don't know if this helps, but this issue reminds me of something that happened to Angular.io itself roughly in that timeframe: https://github.com/angular/angular/pull/21305, with the fix being https://github.com/angular/angular/pull/21305. It's application specific though, but it might be the same problem you're having.
