### ISSUE TITLE
Reflect.getMetadata("annotations") stopped working

### ISSUE THREAD

**Issue by Gebov** [angular/angular#21627]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Expected behavior

const annotations = Reflect.getMetadata("annotations", AppModule);
// should return the annotations

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/8lNXfsbWLA4BKb8Xky1q?p=preview

## Environment

<pre><code>
Angular version: 5.2.1

Browser:
- [x] Chrome (desktop) version  63.0.3239.132
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>
This was working fine in 4.2.6

**Comment by alexzuza** [comment]
Angular team has changed logic for metadata created by invoking the decorators.
It is no longer dependent on Reflect API.
You can try `AppModule['__annotations__']`

**Comment by Gebov** [comment]
@alexzuza that did it. Thanks !

**Comment by acostaf** [comment]
@alexzuza how do you get __annotations__ in AOT?
