### ISSUE TITLE
6.0.0-beta.0 throws compiler-cli version errror

### ISSUE THREAD

**Issue by gregbown** [angular/angular#21639]
## I'm submitting a...
[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  

## Current behavior
Error: Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "6.0.0-beta.0".

## Expected behavior
Able to build in Angular CLI and Webpack

## Minimal reproduction of the problem with instructions
Update Angular libs to 6.0.0-beta.0 and try to build in CLI or ejected Webpack build
Roll back to Angular 5.2.1 and build proceeds as it should

## Environment

<pre><code>
Angular version: 6.0.0-beta.0

Roll back to Angular 5.2.1 and build proceeds as it should
Browser:
- [X] Chrome (desktop) version Version 63.0.3239.108 (Official Build) (64-bit)

 
For Tooling issues:
- Node version: 8.9.0
- npm version: 5.6.0
- Platform:  Windows 10 professional 
- Angular CLI version 1.7.0-beta.0

**Comment by WhiteLeash** [comment]
Same here
Environment:
- Node: 6.11.0
- OS: Windows 10 Pro
- Angular: 6.0.0-beta.0

**Comment by WhiteLeash** [comment]
oh - thanks - but docs said it will works fine only after update :/

**Comment by gregbown** [comment]
Verified with local update to changes [here](https://github.com/angular/angular-cli/commit/65b97c08c7eabc6a3880e2b98d0b4c227b8655c0). Waiting on version update.
