### ISSUE TITLE
Build prod throw error on startup with Firefox ESR 45

### ISSUE THREAD

**Issue by Javarthur** [angular/angular#21631]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Angular 5 does not work on Firefox ESR version 45 (tested on 45.2.0 and 45.6.0) when the app is built in production mode (`ng build -prod`).
But the following commands does work :
 - `ng serve`
 - `ng serve --aot`
 - `ng build`
 - `ng build -prod --aot=false`

The app works correctly with chrome, IE Edge or a recent version of Firefox (52, 54).

## Expected behavior
Like with Angular 4, it should work when the app is built for production.

## Minimal reproduction of the problem with instructions

- Create a new app
- Build the app for the 'prod' environnement
- The app works with 

An easy way to reproduce the problem is to open https://angular.io/ with firefox ESR 45. The app does not start at all, and there is an error in the console:
Error:
`TypeError: this is undefined

t()
 main.9227b8376af048079879.bundle.js:1
t/<()
 main.9227b8376af048079879.bundle.js:1
t()
 main.9227b8376af048079879.bundle.js:1
.LMZF/q</t.prototype.get()
 main.9227b8376af048079879.bundle.js:1
Qt/</<()
 main.9227b8376af048079879.bundle.js:1
Qt/<()
 main.9227b8376af048079879.bundle.js:1
Qt/<()
 main.9227b8376af048079879.bundle.js:1
.cDNt()
 main.9227b8376af048079879.bundle.js:1
o()
 inline.421b80f0f331917cd5b3.bundle.js:1
[0]()
 main.9227b8376af048079879.bundle.js:1
o()
 inline.421b80f0f331917cd5b3.bundle.js:1
window.webpackJsonp()
 inline.421b80f0f331917cd5b3.bundle.js:1
<anonyme>
 main.9227b8376af048079879.bundle.js:1`

The app work when opening the previous version of angular.io (https://v4.angular.io/docs)

## What is the motivation / use case for changing the behavior?

Some of our customers still use older versions of Firefox (in our context, Firefox ESR 45)

## Environment

<pre><code>
Angular version: 5.2.0

Browser:

- [x] Firefox version 45 (Firefox ESR)

 
For Tooling issues:
- Node version: 8.9.4  
- Platform:  Linux, Windows

Others:

</code></pre>

**Comment by mhevery** [comment]
Please file the issue with https://github.com/angular/angular-cli

**Comment by Javarthur** [comment]
Hi @ahexdev1 !
I used a workaround explained in this issue https://github.com/angular/angular-cli/issues/9340

It just forces and old version of uglifyjs (1.1.5) where the error does not occur

`npm i uglifyjs-webpack-plugin@1.1.5 --save-exact
rm -rf package-lock.json node_modules
npm install`

**Comment by ahexdev1** [comment]
Hi Javarthur,
Thanks.

I have used --aot=false, and it solved my problem. But still i am worrying, is this going to cause any other issue. 

I want to know the good approach to solve this one. Is it the one you mentioned as solution would be best or my one.

Thanks and regards
