### ISSUE TITLE
github robot should rebase a PR when special label is added.

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21646]
When a repo collaborator applies a label "PR action: rebase" the robot should:
- rebase the PR on top of the HEAD of the *target* branch (the target might differ because of our patch branches)
- force push into the PR branch
- leave a comment on the PR that the PR was rebased as requested by @<username>
- remove the "PR action: rebase" label

**Comment by vicb** [comment]
:-1: having multiple actors rebasing the same PR is always a bad idea. Rebasing is in general bad as we loose track of the history - it's ok only when someone works in isolation on a PR but what we should do it rather to merge the master branch.

**Comment by IgorMinar** [comment]
@vicb I don't understand your last sentence. can you please clarify?

the use-case for this workflow is the following: I send a small change that fixes docs. the pr fails because of an infrastructure issue on travis. since I sent the PR, the infra issue was worked around on master. I don't want to go and rebase my PR manually. I just want the robot to do it. For now I don't want this to happen automatically, that's why I want a human to add a label to trigger the operator.

This workflow is especially useful for small PRs from outside contributors where it's hard to get them to rebase PRs.

As long as the PR rebases cleanly, I don't understand why would we lose history or have any other problems with this. If there is a merge conflict, the robot will detect it and comment on the issue. A human will then need to take over.

Can you clarify your concern please?

**Comment by ocombe** [comment]
I've checked briefly how to do that, and it would require checking out the branch and doing the rebase with git in cli (using forked processes), which seems like a complicated thing to do from firebase functions

**Comment by IgorMinar** [comment]
ok. in that case let's focus on other workflows first. can you please leave
any notes that will help us pick this issue up again in the future? thanks

**Comment by IgorMinar** [comment]
we now have a `PR action: rerun CI at HEAD` label that allows us to at least rerun the CI tests after a rebase to master (without actually pushing the rebase to the PR branch). That solves many use-cases the original request was seeking to fix/enable. I'm not sure if there is currently much added value in doing pursuing the rest.
