### ISSUE TITLE
Support observable on ActivatedRoute.snapshot

### ISSUE THREAD

**Issue by trshafer** [angular/angular#21640]
ActivatedRoute provides a observables for data, params, etc. It should provide an observable on snapshot.

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There is no way to directly subscribe to the snapshot.

## Expected behavior

There should be a way to directly subscribe to the activated snapshot. Many other components of the activated route provide observable properties, but acquiring the latest snapshot requires workarounds.

## What is the motivation / use case for changing the behavior?

The common format for subscribing to snapshot changes involves both the router and the activated route:

```TypeScript
constructor(router: Router, activatedRoute: ActivatedRoute) {
  router.events.subscribe(event => {
    if (event instanceof NavigationEnd) { 
      this.handleNewSnapshot(activatedRoute.snapshot)
    }
  });
}
```
or

```TypeScript
constructor(router: Router, activatedRoute: ActivatedRoute) {
  combineLatest(activatedRoute.params, activatedRoute.data, activatedRoute.queryParams).pipe(
    map(() => this.handleNewSnapshot(activatedRoute.snapshot))
  );
}
```

It would be helpful to support an activated route api of:

```TypeScript
activatedRoute.snapshot.subscribe(snapshot => this.handleNewSnapshot(snapshot))
```

## Environment
Browser.

<pre><code>
Angular version: 5.x
</code></pre>

Thanks.

**Comment by beaulac** [comment]
should the `activatedRoute.snapshot` now implement Observable? or should there instead be a new, different property (`activatedRoute.snapshotObs` or something) that provides this?
