### ISSUE TITLE
github bot: mark PRs with a google3 status

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#21642]
@ocombe here's how it should work:

whenever a PR has the merge label applied, or a new SHA is pushed to a PR with the merge label
1) get the head SHA
2) if that sha has no status with google3 context, then 
  a) if the PR affects any of these files
```
include = [
        "BUILD.bazel",
        "LICENSE",
        "WORKSPACE",
        "modules/**",
        "packages/**",
    ],
    exclude = [
        "packages/language-service/**",
        "**/.gitignore",
        "**/.gitkeep",
    ],
```
 then push a `'{"state":"pending", "context":"google3", "description": "Verifying this change in google3"}'` status to it
   b) otherwise push a `{"state":"success", "context":"google3", "description": "Does not affect google3"}` status to it

**Comment by ocombe** [comment]
@alexeagle should we do that even if the merge label is applied but some other tests are failing? (travis, pullapprove, labels, ...?)

**Comment by alexeagle** [comment]
That's a good question and merits some discussion - initially I only applied the google3 label to an otherwise green PR. I think it's probably better as described above because:
- it's sad to finally get your PR green on Travis only to see it go yellow again
- if the person is ready to merge, there is no harm testing internally
- many of the failures you'd see in travis are distinct from google3 - the tests we run are very disjoint between the two
- it makes the overall PR process faster if we run these two slow CI systems in parallel

the downsides:
- we might use more google3 testing resources (but you'd be impressed how much this is already abused)
- ?

**Comment by ocombe** [comment]
This has been fixed
