### ISSUE TITLE
Lazy loading is not working fine (inheritance)

### ISSUE THREAD

**Issue by vickydp** [angular/angular#21645]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior
I have a module that is loaded with lazy load whose son is also loaded with lazy load

//principal.routes.ts
export const PRINCIPAL_ROUTES: Routes = [
  {
    path: '',
    component: LayoutComponent,
    children: [
      {
        path: 'debtors',
        loadChildren: '../../Debtors/DebtorsModule/debtors.module#DebtorsModule',
        canActivate: [AuthGuard, AccessAuthGuard],
      }
    ]
  }

//debtors.routes.ts
export const DEBTORS_ROUTES: Routes = [
  {
    path: 'management',
    loadChildren: './Management/management.module#ManagementModule',
    canActivate: [AuthGuard],
  }
]

//management.routes.ts
export const DEBTORS_ROUTES: Routes = [
  {
    path: 'Client/:type/:id',
    component: ClientComponent,
  }
]

when I try to enter from the navigator bar to localhost:4200/debtors/management/Client/CL/1  , it redirects me to localhost:4200, and if first i enter to localhost:4200/debtors/management and then i enter to localhost:4200/debtors/management/Client/CL/1 works fine.

Inherit lazy loading is not working

## Expected behavior
 localhost:4200/debtors/management/Client/CL/1 it should work

## Environment

<pre><code>
    "@angular/cli": "1.6.2",
    "@angular/common": "5.1.1",
    "@angular/compiler": "5.1.1",
    "@angular/compiler-cli": "5.1.1",
    "@angular/core": "5.1.1",
</code></pre>

**Comment by mlc-mlapis** [comment]
@vickydp ... a simple reproduction demo is required ... use http://stackblitz.com

**Comment by spock123** [comment]
Works fine for my projects (Angular 5.2.1 and 6.0 beta).. I have several lazy loaded modules which in turn load other lazy loaded child modules.

**Comment by vicb** [comment]
Please open a new issue with a repro. Thanks.
