### ISSUE TITLE
Change the safe navigation operator to preserve undefined

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#21643]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior

Using the safe navigation operator results in `null` if the left-hand of the expression is `undefined` or `null`. However, it causes an issue if code is trying to avoid `null` it introduces `null` into code that otherwise doesn't use `null`.

## Requested behavior

If the left-hand side of the expression is `undefined` the result is `undefined`. If the result is `null` the result is `null`.

## Minimal reproduction of the problem with instructions

```
@Component({
  selector: 'u-cmp',
  template: 'N:{{optionalNumber}}'
})
export class UndefinedOnly {
  @Input() optionalNumber?: number;

  validate() {
    if (this.optionalNumber === null) throw Error("type violation");
  }
}

public interface Person {
  name: string;
  number?: number;
}

@Component({
  selector: 'my-app',
  template: `
    <div>
      <u-cmp [optionalNumber]='person?.number'></u-cmp>
    </div>
  `,
})
export class App {
  name:string;
  person?: Person;
  
  @ViewChild(UndefinedOnly) child: UndefinedOnly;
  
  constructor() {}
  
  ngAfterViewInit() {
    this.child.validate();
  }
}
```

https://plnkr.co/edit/A1kvP0snOazAHRsO7nlL

## What is the motivation / use case for changing the behavior?

Allows an application to avoid using `null`.

**Comment by trotyl** [comment]
In the current [optional chaining proposal](https://github.com/tc39/proposal-optional-chaining) the returned value would always be `undefined` regardless of the input expression being `null` or `undefined`, should Angular keep consistency with it?

**Comment by chuckjaz** [comment]
We are already significantly different than the proposal in that `a?.b.c` is `null` if `a` is `null` where it throws in the specification. This is non-sensical as `.c` would always be a throw if `a` is `undefined` so it should either be made statically illegal or made to mean `a == null ? undefined : b.c` instead of `(a == null ? undefined : b).c` which makes no sense as `.c` is never legal on `undefined`.

I believe the right meaning of `a?.b.c` is `a == null ? a : b.c` and we should recommend that to the standards committee.

**Comment by JoostK** [comment]
Closing this one to track in #34385.
