### ISSUE TITLE
https://angular.io/docs/latest/tutorial returns a 404

### ISSUE THREAD

**Issue by vicb** [angular/angular#21654]
The problem is that google search returns a link to this page (the menu points to the expected https://angular.io/tutorial)

internal issue b/62685042

**Comment by gkalpak** [comment]
Similar to #21377.
That said, I have no idea where the `/docs/latest/tutorial` URL may come from. The old (v2) site used `/docs/ts/latest/tutorial`, which is correctly redirected 😕

**Comment by IgorMinar** [comment]
I added this to the list of url in #21377. closing as dupe.
