### ISSUE TITLE
HttpModule Error !!

### ISSUE THREAD

**Issue by ashoksrinivas** [angular/angular#21658]
Hi,

I have imported HttpModule in app.module.ts and declared under imports. But still facing No provider for Http ! in Karma testing.. Help me out with this. Previously I faced the same for No provider for Service..I fixed this by importing the service in My component class and injected the provider inside @Component. 

`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { HttpModule } from '@angular/http';
import { LoadersCssModule } from 'angular2-loaders-css'

import { AppComponent } from './app.component';
import { HomeComponent } from './home/home.component';

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent
  ],
  imports: [
    BrowserModule,HttpModule,LoadersCssModule
  ],

  bootstrap: [HomeComponent]
})
export class AppModule { }`

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
