### ISSUE TITLE
UnitTesting of Date pipe in locale/timezone independent way

### ISSUE THREAD

**Issue by mhevery** [angular/angular#21655]
Expressions such as `{{value | date:'mediumDate'}}` will return different values depending on locale of the testing machine making hermetic tests difficult.  There should be a way to set locale / timezone in tests to produce consistent result.

**Comment by RakeshChouhan** [comment]
@mhevery Moment JS can be used in place if heavy date manupulations are required.

**Comment by pkozlowski-opensource** [comment]
This was already addressed by https://github.com/angular/angular/pull/43611
