### ISSUE TITLE
fullTemplateTypeCheck breaks union type with ngIf

### ISSUE THREAD

**Issue by elclanrs** [angular/angular#21668]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Given this union type and input:

```typescript
export type MyType = 'foo' | 'baz';
@Input() value: MyType = 'foo';
```

And this template:

```html
<div *ngIf="value !== 'baz'" [ngClass]="{ baz: value === 'baz' }">
```

With `fullTemplateTypeCheck` this throws an error:

```
Operator '===' cannot be applied to types '"foo"' and '"baz"'.
```

The problem as far as I understand is that `ngIf` narrows down the union type to `foo` so `baz` is not considered a valid type anymore when used in `ngClass`.

## Expected behavior

Should not throw a type error.

I can workaround it for now with `$any`:

```html
<div *ngIf="value !== 'baz'" [ngClass]="{ baz: $any(value) === 'baz' }">
```

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.1 
- Platform:  macOS 

Others:

</code></pre>

**Comment by elclanrs** [comment]
After opening this issue I realize that the error may actually be more helpful than not, since the case I explained above would be impossible, since the class cannot apply if the element is not there!

I'm not sure this is a bug anymore...

**Comment by noemi-salaun** [comment]
Personnaly I would want the compiler to tell me that this case is impossible with an error.

**Comment by chuckjaz** [comment]
As far as I can tell the compiler is doing the right thing.

This is equivilent to saying, in TypeScript,

```ts
if (value !== 'baz') { v = { baz: value === 'baz'}; }
```
[playground](http://www.typescriptlang.org/play/index.html#src=var%20value%3A%20'baz'%20%7C%20'bar'%3B%0D%0Avar%20v%3A%20any%3B%0D%0Aif%20(value%20!%3D%3D%20'baz')%20%7B%20v%20%3D%20%7B%20baz%3A%20value%20%3D%3D%3D%20'baz'%20%7D%3B%20%7D)

which produces exactly the same error.
