### ISSUE TITLE
*ngFor iterate function are called  many times

### ISSUE THREAD

**Issue by Leningsv** [angular/angular#21666]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

for example, if you have a function that debugs a list, it is called several times when, theoretically, it should only be called once.

## Expected behavior

https://stackblitz.com/edit/angular-ymxjt6?file=app%2Fapp.component.ts

Like a list should work in the service To only be called once to instantiate it.
## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-ymxjt6?file=app%2Fapp.component.ts

## Environment

<pre><code>
Angular version: X.Y.Z

Angular CLI: 1.6.1
Node: 8.0.0
OS: win32 x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.0.1
@angular/cli: 1.6.1
@angular/material: 5.0.1
@angular/service-worker: 5.1.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vicb** [comment]
This is expected when you run in dev mode, see https://angular.io/guide/deployment#enable-production-mode

rartionale: the CD is executed twice to make sure there is no loop.

**Comment by Leningsv** [comment]
But the function are execute 4 times.  I'm sorry I thought it was a mistake
________________________________
De: Victor Berchet <notifications@github.com>
Enviado: viernes, 19 de enero de 2018 12:17
Para: angular/angular
Cc: Lenin; Author
Asunto: Re: [angular/angular] *ngFor iterate function are called many times (#21666)


This is expected when you run in dev mode, see https://angular.io/guide/deployment#enable-production-mode

rartionale: the CD is executed twice to make sure there is no loop.

**Comment by changuelsami** [comment]
Hi,
I've ran ng server with  --environment=prod parameter. The method inside the ngFor is called twice, but when I change change a value and the loop is ran again, the function is called once. What's going on ? Why the metho is called twice the first time ?

**Comment by Phoenix404** [comment]
I have the same issue and recently discovered in the organization project.
I am using API to communicate with the server. And when I use `*ngFor` to fetch the images from the server by using API, the `*ngFor` continuously calling the API endpoint multiple time. Let me tell you that the object `imageURLObj `(`*ngFor="let img of imageURLObj"`) is not modified. It does not get any modification or any change.

I have created a minimalistic code on stackblitz. Please check it and don't forget to  check the console.
https://stackblitz.com/edit/angular-dwkegh

**Comment by mlc-mlapis** [comment]
@Phoenix404 Use `trackBy` and probably also `OnPush` strategy.

**Comment by Phoenix404** [comment]
This can be helpful: https://dzone.com/articles/developing-wordpress-sites-with-docker.
