### ISSUE TITLE
Edge browser bug with nativeElement.scrollTo method

### ISSUE THREAD

**Issue by ofirrifo** [angular/angular#21667]
## I'm submitting a...

<pre><code>
[X ] Bug report  
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have div container with Y scroll and I have a method that should set the scroll to the top.
### On edge browser
when I using elementRef with scrollTo(0,0) it not work 
### on other browsers
it works for me in all other browsers
### Demo
[I created demo](https://stackblitz.com/edit/angular-xxeguz?file=app%2Fapp.component.ts) 

## Expected behavior

it needs to work just like it work with other browsers

### Demo
[I created demo](https://stackblitz.com/edit/angular-xxeguz?file=app%2Fapp.component.ts) 

## Environment
Windows and mac 
<pre><code>
Angular version: ^5.0.0

Browser:
- [X ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by alexzuza** [comment]
How is it related to angular?

The same behavior i can observe here https://jsfiddle.net/mnr7h97h/
