### ISSUE TITLE
Angular starter with server rendering and mobile app support starter project

### ISSUE THREAD

**Issue by Aventrue** [angular/angular#21664]
I want to build an angular solution with server rendering and use the same codebase to create a mobile app with cordova. Is there somewhere a starter project to achive that? If not would it be possible that your team create such a starter?
I spoke with a lot of people and there is a big need out there for such a use case.
##
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
