### ISSUE TITLE
Add different css files conditionally

### ISSUE THREAD

**Issue by mousavidev** [angular/angular#21671]
My app uses different languages and some of them are right-to-left. I have two separate css files; one for LTR and the other for RTL.

how can i conditionally add a css file on component?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mousavidev** [comment]
@ericmartinezr Thanks for answer and reminder this issue.
I raising this issue on the stackoverflow.
