### ISSUE TITLE
Can you add a link to a new resource?

### ISSUE THREAD

**Issue by splincode** [angular/angular#21686]
In Russia, now the popularization of the framework is the Angular-RU and AngularMoscow community:
https://github.com/Angular-RU

![image](https://user-images.githubusercontent.com/12021443/35189106-01bb6140-fe55-11e7-8a2f-e008f54df424.png)

https://angular-ru.github.io/

I translate and our team spends different examples with Angular in Russian.

It would be great if you added a link (https://angular.io/resources) to our community. 

Thank you.

**Comment by gkalpak** [comment]
@splincode, feel free to submit a PR (see [here][1] for instructions).
Then someone like @StephenFluin would have to take a look (and approve it).

[1]: https://github.com/angular/angular/blob/master/aio/content/marketing/resources-contributing.md
