### ISSUE TITLE
Angular.io is down!

### ISSUE THREAD

**Issue by Sirrr** [angular/angular#21688]
Hi, Angular.io is down. Could anyone please help?
I can't reach https://angular.io/guide/quickstart for several hours

**Comment by vikram06** [comment]
Nope. It's working fine

**Comment by Sirrr** [comment]
I can't reach https://angular.io/guide/quickstart for several hours

**Comment by gkalpak** [comment]
I am going to close this, since the site seems to be working fine for other people.

**Comment by Sirrr** [comment]
Now it works. Thanks

**Comment by fanux365** [comment]
:( Again it's down!
