### ISSUE TITLE
docs(api/core/error-handler): CustomErrrorHandler should extend ErrorHandler

### ISSUE THREAD

**Issue by jotatoledo** [angular/angular#21697]
## I'm submitting a...
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
`ErrorHandler `is treated as an interface. Furthermore, the example is really simple and doesn't show how to inject elements into the handler.

UPDATE:

Just realized that Typescript allows the use of both implements and extends for classes. I guess that is a way to express that a class overrides the implementation of another? Kinda confusing.

## Expected behavior
The custom error handler should be decorated with @Injectable, showcase how to inject elements in the ctor and **extend**, not implement `ErrorHandler`

## Minimal reproduction of the problem with instructions

Check the [docs](https://angular.io/api/core/ErrorHandler)
****

**Comment by mhevery** [comment]
this is describe as expected.
