### ISSUE TITLE
How to send json data to services 

### ISSUE THREAD

**Issue by chaitanyash** [angular/angular#21696]
Hello Everyone,
I am building a web site in angular 4 I want help in how to connect with the api database and and validate the username and password and how to send json object to services ,I tried everything I know Please some one help me in this issue

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mlc-mlapis** [comment]
@chaitanyash ... just read the doc section https://angular.io/guide/http first. There is all you need.
