### ISSUE TITLE
Error "Please add a @NgModule annotation" in Angular 5

### ISSUE THREAD

**Issue by kandangit** [angular/angular#21699]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I am importing an Angular module (Shared2Module) which is generated from a separated library project (as an Angular package., as in the link https://www.usefuldev.com/blog/post/publishing-a-library-from-an-angular-cli-project)

Compiling with **yarn dev** returns error:

**ERROR in : Unexpected value 'Shared2Module 
imported by the module 'AppModule in ... 
Please add a @NgModule annotation.**

Both, the client project and the library project have the exactly the same dependency versions.
And, installing the dependency using npm install does NOT install any node_modules folder under my dependency (they are compatible). Yet, the compilation error happens.

(note: i have used Shared2Module as a temporary name and to avoid any issue with Prime SharedModule)

Below is the **package.json of the library project.** (The only difference with the client project package.json is that:
the client package.json of client project includes the library dependency
gulp dependencies (in the library project)
scripts/files/main/typings sections in the library package.json used to generate the compiled package using ngc

<pre><code>
{
  "name": "kandanviel-fbittest",
  "version": "1.0.20",
  "license": "MIT",
  "author": "kandanviel",
  "scripts": {
    "ng": "ng",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "inline-build-templates": "gulp inline-build-templates",
    "ngc-build": "ngc -p ./tsconfig.lib.json",
    "cleardown": "rimraf build lib",
    "prepare": "npm run cleardown && npm run inline-build-templates && npm run ngc-build"
  },
  "private": false,
  "dependencies": {
    "@angular/animations": "~5.1.2",
    "@angular/common": "~5.1.2",
    "@angular/compiler": "~5.1.2",
    "@angular/core": "~5.1.2",
    "@angular/forms": "~5.1.2",
    "@angular/http": "~5.1.2",
    "@angular/platform-browser": "~5.1.2",
    "@angular/platform-browser-dynamic": "~5.1.2",
    "@angular/router": "~5.1.2",
    "angular2-ie9-shims": "^0.0.2",
    "bootstrap": "3.3.7",
    "bootstrap-sass": "3.3.7",
    "core-js": "~2.5.1",
    "font-awesome": "4.7.0",
    "lodash": "4.17.4",
    "moment": "2.18.1",
    "primeng": "~5.0.2",
    "reflect-metadata": "0.1.10",
    "rxjs": "~5.5.5",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "~1.6.0",
    "@angular/compiler-cli": "~5.1.2",
    "@angular/language-service": "~5.1.2",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "http-server": "^0.10.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "2.4.2",
    "webpack-dev-server": "~2.9.3",
    "webpack": "~3.10.0",
    "autoprefixer": "^6.5.3",
    "css-loader": "^0.28.1",
    "cssnano": "^3.10.0",
    "exports-loader": "^0.6.3",
    "file-loader": "^1.1.5",
    "html-webpack-plugin": "^2.29.0",
    "less-loader": "^4.0.5",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.1.2",
    "raw-loader": "^0.5.1",
    "sass-loader": "^6.0.3",
    "source-map-loader": "^0.2.0",
    "istanbul-instrumenter-loader": "^2.0.0",
    "style-loader": "^0.13.1",
    "stylus-loader": "^3.0.1",
    "url-loader": "^0.6.2",
    "circular-dependency-plugin": "^4.2.1",
    "copy-webpack-plugin": "^4.1.1",
    "uglifyjs-webpack-plugin": "~1.1.2",
    "gulp": "^3.9.1",
    "gulp-inline-ng2-template": "^4.1.0"
    
  },
  "files": [
    "lib"
  ],
  "main": "./lib/shared/shared2.module.js",
  "typings": [
	"./lib/shared/shared2.module.d.ts",
	"./lib/shared/index.d.ts"
  ]
}

</code></pre>

## Expected behavior
No compilation error

## Minimal reproduction of the problem with instructions
Create a new angular-cli project 
In the app.module.ts
<pre><code>
import { Shared2Module } from 'kandanviel-fbittest';
@NgModule({
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    routing,
    Shared2Module
  ],
  declarations: [ AppComponent ],
  bootstrap: [ AppComponent ] //que componente arrancará al iniciar la app
})
export class AppModule { 
    constructor(){      
    }    
}
</code></pre>

## Environment
Angular 5.1.2, angular-cli 1.6.0
Yarn
<pre><code>

**Comment by kandangit** [comment]
Looks like was a problem with the **package.json**

> "typings": ["./shared/shared.module.d.ts", "./shared/shared.index.d.ts"]"

Creates the issue. Solve replacing by:

> typings": "./shared/shared.module.d.ts"

this means I created an index.ts that export all classes I need to import in the client project and import them direclty from the index.ts:

> import { Item }  from 'kandanviel-fbittest/**shared/index**';

I am not sure if is an issue  because package.json typings property does not allow an array (and fails later when compiling with the included dependencly) or an issue with angular-cli.. ; 

As commented by @IevhenIkonnykov in issue #15763 this "Please add a @NgModule annotation" error can be due to multiple reasons

**Comment by AhmedBHameed** [comment]
@kandangit You made my date with your solution. Thank you.
