### ISSUE TITLE
ng serve outputs  ERROR in TypeError: _this.host.getOutputName is not a function

### ISSUE THREAD

**Issue by savageqm** [angular/angular#21698]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

While running ng serve I get the ERROR in TypeError: _this.host.getOutputName is not a function   coming from the compiler.umd.js 
 I have remove the node_module folder and reinstall the angular cli -g

## Expected behavior

compile

## Minimal reproduction of the problem with instructions

ng serve

## Environment

<pre><code>
Angular version: 5.1.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.5  
- Platform:  Windows 10

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/21621
