### ISSUE TITLE
Build infrastructure improvements

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21707]
- Publish Angular using Bazel build artifacts (replace the existing build.sh script that creates build artifacts that we publish to npm with Bazel-based build configuration)
  - [x] implement ng_package rule
  - [x] configure ng_package rule throughout the repo
  - [x] update release scripts & instructions
  - [x] delete build.sh

**Comment by gkalpak** [comment]
- [ ] Update instructions in [docs/DEVELOPER.md][1].

[1]: https://github.com/angular/angular/blob/master/docs/DEVELOPER.md

**Comment by IgorMinar** [comment]
fixed by #27937
