### ISSUE TITLE
Documentation Lacking examples and descriptions

### ISSUE THREAD

**Issue by ZergRushJoe** [angular/angular#21705]
`https://angular.io/api/core/ComponentFactoryResolver`. Documents should have examples and descriptions of what they are doing. It not good enough to just give what the typescript tells me already. I need more then that to use this function properly. take this `https://nodejs.org/docs/latest-v7.x/api/crypto.html#crypto_new_crypto_certificate`. It tells me what it does and what it outputs and gives real code.

**Comment by MrJithil** [comment]
https://angular.io/guide/dynamic-component-loader seems to be reused on this page? Can I add it?

**Comment by petebacondarwin** [comment]
@MrJithil - are you saying that there is an example of using `ComponentFactoryResolver` on the https://angular.io/guide/dynamic-component-loader guide, and that you would like to reuse that example in this API doc?

**Comment by petebacondarwin** [comment]
I would recommend just linking to the guide from the API doc description. Thanks!

**Comment by MrJithil** [comment]
@petebacondarwin I have added the changes. https://github.com/angular/angular/pull/42496

Please check.
