### ISSUE TITLE
Update `ngc` to take advantage of the new watch API in TS 2.8

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#21703]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior

`ngc` needs uses the compiler host API to host the TypeScript compiler.

## Expected behavior

The watch mode of `ngc` should take advantage of the new watch API in TypeScript https://github.com/Microsoft/TypeScript/pull/20234

**Comment by alxhub** [comment]
I'm going to move this into our triage process for discussion. I'm leaning towards closing it as something we don't plan on implementing, as `ngc`'s watch mode is currently functional and not in significant use (in comparison to `ng serve` which uses an entirely different flow). But I think it's worth a discussion.

**Comment by alxhub** [comment]
Closing this as it's not feasible to implement - the compiler currently has an advanced incremental build system to support Angular semantics. Unfortunately, using TS semantics directly won't really work for `ngc` as Angular might require updates where TS would not.
