### ISSUE TITLE
Implement new angular.io API template for the "class" API type

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21715]
- [x] initial discussion, research, etc
- [x] @sjtrimble to create visual mocks by 2018-01-23
- [ ] @IgorMinar and @jbogarthyde to review and iterate on the mock with @sjtrimble, and approve by 2018-01-26
- [ ] @petebacondarwin to implement the template by 2018-01-31
- [ ] (stretch) @jbogarthyde to land the already drafted content changes for class API docs by 2018-02-02

**Comment by sjtrimble** [comment]
@IgorMinar My expectation was to deliver a visual mockup today (01-24) for us to review and discuss and move to HTML mockup once we have an agreed upon design. Does that match your expectation?

**Comment by IgorMinar** [comment]
@sjtrimble I see. So visual mock today (Jan 23), and only then html mock? I wonder if we could just skip html mock in that case. What do you think @petebacondarwin? Will html mocks add enough value or should we just skip that and ask @gkalpak for help if css gets too crazy?

**Comment by petebacondarwin** [comment]
The reason I pushed for HTML and CSS is that I don't think my time is well spent trying to convert a Photoshop into HTML and CSS. Given that is not where I am particularly strong, it would end up taking longer that way.

**Comment by IgorMinar** [comment]
Would mock html/css easily translate to angular.io setup? If it does then I
agree that html mocks would help. If it doesn't then George could do the
css while Pete does all the other eng bits.

**Comment by sjtrimble** [comment]
The way I have it currently designed, there is not too much custom CSS planned. I tried to work within the current classes/styles throughout the other pages as much as possible.

**Comment by jenniferfell** [comment]
@IgorMinar For @jbogarthyde "to land the already drafted content changes for class API docs ", will she be making changes herself directly to the source code, where the API ref content originates? Or will she be collaborating with engineers who own the source? Assume there's also an aspect of engineering review/input we'll want for technical accuracy and completeness of her proposed class rewrites. We might break it down by actual classes, some this sprint and some next.

**Comment by jbogarthyde** [comment]
I've done initial rewrites for 7 classes - ChangeDetectorRef, ViewRef, EmbeddedViewRef, ViewContainerRef, ComponentRef, AnimationBuilder, and AnimationFactory.  
No one has done any technical review of the content - if I put those into the new template, we can take the opportunity to develop a procedure for writer/engineer collaboration on API doc.

**Comment by IgorMinar** [comment]
@jenniferfell yeah. directly in the source code. all the content is in comments. we'll then need eng to review.

**Comment by sjtrimble** [comment]
Adding latest mockup here as well for reference.
[api-page-0124.pdf](https://github.com/angular/angular/files/1661285/api-page-0124.pdf)

**Comment by petebacondarwin** [comment]
We have now landed the class API type changes.
