### ISSUE TITLE
Internet Explorer shows white screen

### ISSUE THREAD

**Issue by danieldaeschle** [angular/angular#21719]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Internet Explorer doesn't load the site always. Sometimes it loads and sometimes not.
Sometimes an errors occures in the console:
```
SCRIPT5011: Unable to run shared script code
zone.js (2741,17)
```

## Expected behavior
It should show the page everytime

## Minimal reproduction of the problem with instructions
Angular 5 App with Angular CLI 1.6 generated. Polyfills for IE uncommented

## What is the motivation / use case for changing the behavior?
Internet Explorer Users should be able to get access to the site.

## Environment
<pre><code>
Angular version: 5.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X ] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.1
- Platform:  Windows 10 Pro

Others:
Also testet in prodcution with AOT compiler
</code></pre>

**Comment by JiaLiPassion** [comment]
@danieldaeschle , could you try to add this line in polyfill.ts

```javascript
(window as any).__Zone_enable_cross_context_check = true;
import 'zone.js/dist/zone';  // Included with Angular CLI.
```

**Comment by danieldaeschle** [comment]
@JiaLiPassion Error doesn't appear anymore.
I still have the white screen if i don't open the developer tools of internet explorer. if they're open i see the website.

**Comment by JiaLiPassion** [comment]
@danieldaeschle , I am not sure what is the reason, could you post a reproduce repo?

**Comment by danieldaeschle** [comment]
I forget to say that i'm using material-design-lite from getmdl.io
maybe that occures the issue?

**Comment by JiaLiPassion** [comment]
@danieldaeschle , I am not sure, but if you can provide a reproduce repo, I can help to debug.

**Comment by danieldaeschle** [comment]
https://github.com/danieldaeschle/ferienwohnung-sonnenuhr

**Comment by JiaLiPassion** [comment]
@danieldaeschle , I download your repo, and change `polyfill.ts` line 38 https://github.com/danieldaeschle/ferienwohnung-sonnenuhr/blob/master/src/polyfills.ts#L38
to

```javascript
import 'classlist';  // Run `npm install --save classlist.js`.
```

can't reproduce, everything work fine.

**Comment by danieldaeschle** [comment]
`classlist` is another module than `classlist.js`...
Chrome is working greate. IE still not working when developer console not opened.
But it is only when i'm using MDL.
maybe company environment is buggy. I will test it at home later.
Thanks for help

**Comment by trotyl** [comment]
Try add `<meta http-equiv="X-UA-Compatible" content="IE=edge" />` in the `<head>`, this will override the local network default one.

**Comment by gkalpak** [comment]
I can reproduce the issue (after fixing the app with `yarn add classlist.js`).

I tried whatever I could think of, but I can't debug this in IE11 😞 
IE11 does have different behavior with and without DevTools open. Most notoriously, [`console` is not defined][1] until you open the DevTools. But that isn't the issue in your case afaict.
The HTML seems to be rendered correctly, but some containers have 0 height. Sounds like an IE11 bug (possibly related to flexbox layout) and/or mdl issue.

[1]: https://stackoverflow.com/questions/7742781/why-does-javascript-only-work-after-opening-developer-tools-in-ie-once

**Comment by JiaLiPassion** [comment]
@danieldaeschle , ok , I will reinstall the `classlist.js`. I got an error when I install `classlist.js`...

**Comment by danieldaeschle** [comment]
@trotyl I tried this already. Doesn't help.
@gkalpak Yes i think that it is an MDL Bug or something too. Did you found a fix for it?

**Comment by danieldaeschle** [comment]
`<fs-root>` shows no height. And it is no MDL Component. maybe an Angular Bug? But when i create an new angular project everything is working.

**Comment by danieldaeschle** [comment]
![image](https://user-images.githubusercontent.com/30751516/35280490-c003157e-0050-11e8-9635-cfa3a46866e7.png)
It is an MDL bug. every MDL element is invisible.

**Comment by danieldaeschle** [comment]
https://github.com/google/material-design-lite/issues/5183

**Comment by csameer007** [comment]
I didn't have any MDL components but i still got this issue.

**Comment by naveenkumarv183** [comment]
I didn't have any Material design components, and strangely application is loading in IE-11 for dev environment but not in QA environment, can someone please help

**Comment by tamirgilany** [comment]
> Try add `<meta http-equiv="X-UA-Compatible" content="IE=edge" />` in the `<head>`, this will override the intranet default one.
> 
> More information could be found at https://stackoverflow.com/questions/3449286/force-ie-compatibility-mode-off-using-tags

Thanks, it worked for me!
