### ISSUE TITLE
Bot improvement - Slack integration + regression escalation

### ISSUE THREAD

**Issue by Brocco** [angular/angular#21711]
## Current behavior

N/A

## Expected behavior

When a new issue is submitted to this repo the bot will evaluate to determine if the regression checkbox is selected. And if that condition is met it will post a message to the caretaker channel within the Angular team slack for awareness.

The bot should keep on pinging the slack channel every 15 minutes unless the issue is triaged (via existing triaging rules) and assigned to someone (the assignee field is set).

## What is the motivation / use case for changing the behavior?

This feature would make it easier to sound alarms when regressions are reported.

This is issue is an action item from a post-mortem after a recent cli breakage, but is generally applicable to all of our repos/projects.

//CC @IgorMinar @ocombe

**Comment by IgorMinar** [comment]
thanks @Brocco. I added a few more details into the issue description.

**Comment by ocombe** [comment]
Don't you think that every 15mn is a bit harsh? What if the issue is opened in the week end, or in the night, you if it takes 8 hours before someone opens the slack channel you'll get 32 messages. People will just ignore the channel if there's too much noise!

Also if we want to do scheduled function activations in firebase functions, we'll need an external cron service that will ping our service to trigger it, see the demo app here: https://github.com/firebase/functions-samples/tree/master/delete-unused-accounts-cron

**Comment by IgorMinar** [comment]
The caretakers is expected to follow up on regressions even on weekends. The goal of this is to ensure that if something important happens (like a bad release, or site is down) we get notified and someone reviews the report and determines the appropriate path to resolution.

**Comment by IgorMinar** [comment]
yeah. scheduling jobs with Firebase is hard. we can either use an external service to ping the firebase end point ([post](https://medium.com/@ales.musto/firebase-cloud-functions-that-run-on-a-set-schedule-b5d62cbbc476), [video](https://www.youtube.com/watch?v=CbE2PzvAMxA)) or setup an app engine instance ([post](https://firebase.googleblog.com/2017/03/how-to-schedule-cron-jobs-with-cloud.html)). I'm not aware of other options.

**Comment by IgorMinar** [comment]
I'm inclined to go with the www.cron-job.org approach. It seems easier to setup.

**Comment by gkalpak** [comment]
You could also piggyback on the ngbuilds.io server (but it would couple unretated things).

**Comment by IgorMinar** [comment]
I'd rather not add this kind of cross-dependency on ngbuilds.io.

**Comment by ocombe** [comment]
Could we also monitor the number of comments since the issue was opened, and determine some kind of threshold, like x comments in x hours = hot topic and we should look into it?

**Comment by IgorMinar** [comment]
yeah. that's worth looking into as well
