### ISSUE TITLE
No fallback (thus no styling) for CSS Custom Properties in IE11

### ISSUE THREAD

**Issue by nicky-lenaers** [angular/angular#21721]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

CSS Custom Properties do not have a fallback in IE11. Therefor, no CSS is applied when using `var()` syntax. Even when I use the Browserslist in my `package.json` like so:
```json
"browserslist": [
    "> 1%",
    "last 5 versions",
    "ie >= 11"
  ],
```
... the CSS still has no fallback values.

## Expected behavior

Fallback values for `var()` syntax. Along the lines:
```css
// Source
:root {
  --my-color: #f00;
}

// Rendered:
color: var(--my-color);
color: #f00;
```

## What is the motivation / use case for changing the behavior?

Support styling using CSS Custom Properties in IE11

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4  
- Platform:  Windows

Others:

</code></pre>

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
