### ISSUE TITLE
FormControl to accept observable as a value

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/angular#21724]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently I'm pushing `ngrx/store` value into `FormControl` like this:
```
 this.store.select('storeProperty').takeUntil(this.ngUnsubscribe).subscribe(value => {
            this.form.get('field')!.setValue(value);
        });
```

## Expected behavior
It would be nice to reduce code into simpler statement if the `FormControl` would accept the `ngrx/store`'s observable.
like this perhaps:
```
this.form.get('field')!.setValue(this.store.select('storeProperty'));
```
It could also take away the need to unsubscribe the store's subscription via `.takeUntil(this.ngUnsubscribe)`.
ngUnsubscribe is a `Subject` which completes inside components `OnDestroy`.

## What is the motivation / use case for changing the behavior?
simpler code

**Comment by frederikprijck** [comment]
Fwiw you might want to have a look at https://netbasal.com/connect-angular-forms-to-ngrx-store-c495d17e129 , which basicly does the same but removes the need for the same code on every form.

**Comment by GeorgeKnap** [comment]
@frederikprijck 
I see, but he is still using subscription in his directive to update form value:
```
this.store.select(state => state.forms[this.path])
      .take(1)
      .subscribe(val => {
         this.formGroupDirective.form.patchValue(val);
    });
```

that's what I am trying to avoid in this feature request.

**Comment by BioPhoton** [comment]
I would avoid putting formdata to store or vice versa. 
The 2 biggest mistakes with redux patter , no matter what framework, is putting form data, errors, success messages into the store. 

With every app that I have to improve or analyse I do this first. Removing these things from redux.

Dont overload apps with unnecessary complexity.

Best 
Michael

**Comment by GeorgeKnap** [comment]
@BioPhoton 
Interesting. Why do you consider it being a mistake use of redux pattern? I don't pretend to know it perfectly, I've been using it for about a month now.

Let's consider following scenario:

> I have a tabs component. Regardless of possibility using the routed tabs I'm keeping the tab index in database to know which particular tab to show on app startup - that's what the user can set up.
> When the app starts, it loads the tab index into ngrx store. Multiple components subscribes to this store property to see the value. In one component I have an input form field for the tab index.  When the form value changes it dispatch a store update and also async call to update db.

Feels like pretty reasonable use of the store for me.

**Comment by BioPhoton** [comment]
why not update the store on forms save (click some button or so) instead of binding valueChanges to store? If you update the db on server you might have a separate action for this when the response arrives. 
I guess you want to avoid sending requests on every value change.

**Comment by GeorgeKnap** [comment]
Agreed. But that's not the point here.
The point here is to get the value from store and put it into form without the need of manually subscribing.

**Comment by rearl** [comment]
I would also like to see `setValue()` to accept `Observable`. +1
