### ISSUE TITLE
Back button should return to last component 'state' 

### ISSUE THREAD

**Issue by creativeprogramming** [angular/angular#21726]
E.g. I've a component that shows a list of real estate entries dynamically populated after some search criteria, then i've a routerLink to the single real estate detail component. Now if from the detail component i go back (hit browser back button) I lost the search results list cause the component is initialized from scratch and not restored from last state.

Please help me if there's a way to solve my issue without changing angular core.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
