### ISSUE TITLE
Documentation is missing for ngModel binding in the third property level gets undefined

### ISSUE THREAD

**Issue by riginoommen** [angular/angular#21720]
## I'm submitting a Documentation Request

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

```
<div class="form-group col-md-4">
            <label for="type">Type
            </label>
            <select class="form-control" id="type" [(ngModel)]="service.backup.type" required>
              <option value="Database">Database</option>
            </select>
          </div>
```

## Expected behavior
Data should be defined on passing to the back end. Currently we are getting error

> TypeError: _co.service.backup is undefined
> Stack trace:

> TypeError: _co.service.backup is undefined
> Stack trace:
> View_ManageServiceComponent_0/<@ng:///ServiceCatalogModule/ManageServiceComponent.ngfactory.js:1032:9
> debugUpdateDirectives@webpack-internal:///../../../core/esm5/core.js:14535:12
> checkAndUpdateView@webpack-internal:///../../../core/esm5/core.js:13704:5
> callViewAction@webpack-internal:///../../../core/esm5/core.js:14054:21
> execComponentViewsAction@webpack-internal:///../../../core/esm5/core.js:13986:13
> checkAndUpdateView@webpack-internal:///../../../core/esm5/core.js:13710:5
> callViewAction@webpack-internal:///../../../core/esm5/core.js:14054:21
> execEmbeddedViewsAction@webpack-internal:///../../../core/esm5/core.js:14012:17
> checkAndUpdateView@webpack-internal:///../../../core/esm5/core.js:13705:5
> callViewAction@webpack-internal:///../../../core/esm5/core.js:14054:21
> execComponentViewsAction@webpack-internal:///../../../core/esm5/core.js:13986:13
> checkAndUpdateView@webpack-internal:///../../../core/esm5/core.js:13710:5
> callWithDebugContext@webpack-internal:///../../../core/esm5/core.js:14936:39
> debugCheckAndUpdateView@webpack-internal:///../../../core/esm5/core.js:14473:12
> ViewRef_.prototype.detectChanges@webpack-internal:///../../../core/esm5/core.js:11496:9
> ApplicationRef.prototype.tick/<@webpack-internal:///../../../core/esm5/core.js:5982:58
> ApplicationRef.prototype.tick@webpack-internal:///../../../core/esm5/core.js:5982:13
> next/<@webpack-internal:///../../../core/esm5/core.js:5815:99
> ZoneDelegate.prototype.invoke@webpack-internal:///../../../../zone.js/dist/zone.js:392:17
> onInvoke@webpack-internal:///../../../core/esm5/core.js:4825:24
> ZoneDelegate.prototype.invoke@webpack-internal:///../../../../zone.js/dist/zone.js:391:17
> Zone.prototype.run@webpack-internal:///../../../../zone.js/dist/zone.js:142:24
> NgZone.prototype.run@webpack-internal:///../../../core/esm5/core.js:4642:54
> next@webpack-internal:///../../../core/esm5/core.js:5815:69
> EventEmitter.prototype.subscribe/schedulerFn<@webpack-internal:///../../../core/esm5/core.js:4419:36
> SafeSubscriber.prototype.__tryOrUnsub@webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:244:13
> SafeSubscriber.prototype.next@webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:191:17
> Subscriber.prototype._next@webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:132:9
> Subscriber.prototype.next@webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:96:13
> Subject.prototype.next@webpack-internal:///../../../../rxjs/_esm5/Subject.js:65:17
> EventEmitter.prototype.emit@webpack-internal:///../../../core/esm5/core.js:4399:24
> checkStable@webpack-internal:///../../../core/esm5/core.js:4790:13
> onHasTask@webpack-internal:///../../../core/esm5/core.js:4838:21
> ZoneDelegate.prototype.hasTask@webpack-internal:///../../../../zone.js/dist/zone.js:445:21
> ZoneDelegate.prototype._updateTaskCount@webpack-internal:///../../../../zone.js/dist/zone.js:465:17
> Zone.prototype._updateTaskCount@webpack-internal:///../../../../zone.js/dist/zone.js:289:17
> Zone.prototype.runTask@webpack-internal:///../../../../zone.js/dist/zone.js:209:25
> drainMicroTaskQueue@webpack-internal:///../../../../zone.js/dist/zone.js:602:25
> ZoneTask.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:503:21
> invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:1540:9
> globalZoneAwareCallback@webpack-internal:///../../../../zone.js/dist/zone.js:1566:17
> ManageServiceComponent.html:150:12

## What is the motivation / use case for changing the behavior?
Please update the documentation in the angular for managing the sub objects in the dom. also it will be good if you give a mention in the angularjs upgrade cheatsheet

## Environment

<pre><code>
Angular version: 5.0

Browser:

- [x] Firefox version 57
 
For Tooling issues:
- Node version: 8.9.1
- Platform:  Linux (Fedora)

**Comment by jenniferfell** [comment]
@riginoommen Hi. Thank you for submitting this issue. I apologize for taking so long to reply. Do you happen to remember which area of the docs you were using that you found incomplete or incorrect? 

Looks like it might be this:
https://angular.io/guide/forms#two-way-data-binding-with-ngmodel

Thank you

**Comment by riginoommen** [comment]
Hello @jenniferfell 

Thanks for considering the issue. We were on the same place but when it comes to multilevel data binding the things won't work as expected. 

something like

<input type="text" class="form-control" id="name"
       required
       [(ngModel)]="model.properties.name" name="name">
TODO: remove this: {{model.properties.name}}

**Comment by dylhunn** [comment]
Not enough information to reproduce -- please feel free to open a new issue with more specifics.
