### ISSUE TITLE
Type '(typeof HttpModule)[]' is not assignable to type 'CompilerOptions[]'.

### ISSUE THREAD

**Issue by ConorTighe1995** [angular/angular#21732]
## Problem with compiling HttpModule
I had a Angular project that worked fine but recently I've been getting Argument of type '(typeof HttpModule)[]' is not assignable to parameter of type 'CompilerOptions | CompilerOptions[]'. when I run npm start, here is the main.ts file that is the source of the error:

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module';
import { HttpModule } from '@angular/http';

const platform = platformBrowserDynamic();
platform.bootstrapModule(AppModule, [HttpModule]);

## Current behavior
Crashes when compiling, nothing in localhost

Angular version: 2.0.2

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by alxhub** [comment]
@ConorTighe1995,

`bootstrapModule()` has never worked this way - you need to import any modules you want to depend on from your `AppModule`, not pass them as an array parameter to `bootstrapModule()`. The Typescript error you are seeing here is valid.
