### ISSUE TITLE
Attributes are not preserved on `<style>` 

### ISSUE THREAD

**Issue by vicb** [angular/angular#21738]
Imported from b/26581405

I have the following in a component template:

    <style is='custom-style'>...</style>

which is transformed and inserted under the 'head' tag:

    <style>...</style>

losing the "is='custom-style'" during the process.

This marker is needed by polymer.

**Comment by trotyl** [comment]
Duplicate of #6513 (is it copy & pasted? 😃 )

**Comment by pkozlowski-opensource** [comment]
Duplicate of #6513
