### ISSUE TITLE
Better docs for ViewChild and ContentChild selectors

### ISSUE THREAD

**Issue by diminutivesloop** [angular/angular#21734]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The documentation for the ViewChild, and ContentChild decorators does not make clear what qualifies as a valid selector for specifying a target element or directive. Even if one can infer from the various code examples that Component classes, Directive classes, and standard CSS selectors are valid options I see no documentation that indicates template reference variables may be used as selectors. This has apparently already confused at least [one other person](https://github.com/angular/angular/issues/21542).

**Comment by takamori** [comment]
There's also https://github.com/angular/angular/issues/20927

**Comment by pkozlowski-opensource** [comment]
Agreed, we should document this better. For anyone looking for the info on the topic, we are currently supporting a sub-set of CSS selectors:

- element selectors
- attribute selectors (including values)
- `:not(...)` pseudo-selector
- combination of the above (including `,`)

**Comment by vincecampanale** [comment]
I'd be happy to address this is nobody else is working on it already.

**Comment by jenniferfell** [comment]
@vincecampanale That would be great!

**Comment by vincecampanale** [comment]
@jenniferfell I made the change -- how do I run the docs locally? I created a bullet-point list, identical to the one in @pkozlowski-opensource's answer and would like to verify that the markdown syntax for bullet points worked before I commit & push it to my branch.

**Comment by alexzuza** [comment]
@vincecampanale Please check this out
https://stackoverflow.com/questions/49162473/what-are-all-the-valid-selectors-for-viewchild-and-contentchild/49167289#49167289

**Comment by Richardinho** [comment]
In 2020, the docs for ContentChild https://angular.io/api/core/ContentChild still seem to be severely incomplete. In particular it's not explained what syntax and acceptable values for metadata is.
