### ISSUE TITLE
fullTemplateTypeCheck doesn't catch missing properties under *ngIf

### ISSUE THREAD

**Issue by buu700** [angular/angular#21733]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

```json
{
	"angularCompilerOptions": {
		"fullTemplateTypeCheck": true
	},
	...
}
```

```ts
// import {balls} from './misc-functions';

@Component({
	selector: 'my-foo',
	styleUrls: ['./foo.scss'],
	templateUrl: './foo.html'
})
export class FooComponent {
	// public readonly balls: typeof balls = balls;
}
```

```html
<div *ngIf='true'>{{balls()}}</div>
```

Build succeeds; run-time error `TypeError: _co.balls is not a function`.

## Expected behavior

The compiler should have caught that the commented out lines were missing from `FooComponent`.

## Minimal reproduction of the problem with instructions

1. Clone https://github.com/buu700/angular-21733-test

2. `ng build --prod`

3. Build (incorrectly) succeeds

## What is the motivation / use case for changing the behavior?

Catching bugs.

## Environment

<pre><code>
Angular version: 5.2.1

Browser: N/A
 
For Tooling issues:
- Node version: 8.9.4
- Platform: Linux (Debian 9.3 x86-64)

Others:

CLI version: 1.6.5
TypeScript version: 2.6.2
</code></pre>

**Comment by buu700** [comment]
Ah, perfect, thanks! That fixed the problem in the test project and caught a few errors in my real project. Is there already an issue tracking that?

**Comment by chuckjaz** [comment]
TypeScript does not merge angular compiler options like it does its own. Unfortunately, this means you cannot have a default set in the base tsconfig.json and update it in specific tsconfig.json files.
