### ISSUE TITLE
The problem with intercept when compiling ng build --prod --aot=true  --env=prod

### ISSUE THREAD

**Issue by Rambuto** [angular/angular#21742]
<pre><code>
[ ] Regression
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code>

<code>
Browser:
- [x] Chrome (desktop) version Version 63.0.3239.132 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code>
</pre>

Hello
After compiling the project in --prod mode, I get the following error:

<pre><code>
main.6514f8ee390d0c44c41c.bundle.js:1 ERROR TypeError: Assignment to constant variable.
    at i (main.6514f8ee390d0c44c41c.bundle.js:1)
    at XMLHttpRequest.a (main.6514f8ee390d0c44c41c.bundle.js:1)
    at t.invokeTask (polyfills.2379d8c18c8e6c25ec4e.bundle.js:1)
    at Object.onInvokeTask (main.6514f8ee390d0c44c41c.bundle.js:1)
    at t.invokeTask (polyfills.2379d8c18c8e6c25ec4e.bundle.js:1)
    at e.runTask (polyfills.2379d8c18c8e6c25ec4e.bundle.js:1)
    at e.invokeTask [as invoke] (polyfills.2379d8c18c8e6c25ec4e.bundle.js:1)
    at v (polyfills.2379d8c18c8e6c25ec4e.bundle.js:1)
    at XMLHttpRequest.g (polyfills.2379d8c18c8e6c25ec4e.bundle.js:1)
Ml @ main.6514f8ee390d0c44c41c.bundle.js:1
</code></pre>

This problem has only if I'm using interceptor. 

I took simple version in angular documentation.

This is part of code which I use:
<pre>
@Injectable()
export class NoopInterceptor implements HttpInterceptor {
  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return next.handle(req);
  }
}
</pre>

And in module this was included like this:
<pre>
{
    provide: HTTP_INTERCEPTORS,
    useClass: NoopInterceptor,
    multi: true,
},
</pre>

How I'm find, problem with this part of compiled code 
a = ("responseURL"in (e = e) && e.responseURL ? e.responseURL : /^X-Request-URL:/m.test(e.getAllResponseHeaders()) ? e.getResponseHeader("X-Request-URL") : null) || l.url;

**Comment by thillmann** [comment]
I'm having the same issue. If you target es5 instead of es2015 in your tsconfig.json this error won't appear, since const is a es2015 feature.

**Comment by trotyl** [comment]
Wrong repo: https://github.com/angular/angular-cli

**Comment by Rambuto** [comment]
Thank you, but I have a new problem.

After compilation, I have next error 

<pre><code>
Uncaught (in promise): TypeError: u.a.merge is not a function
TypeError: u.a.merge is not a function
</code></pre>

**Comment by umarov** [comment]
I am having this exact same version in two my angular applications.
Both of them are on 5.5.2. Happens when I do `--prod` build when targeting ES2017. Targeting ES5 fixed, but that's not a fix. 
In only one of my projects I am using interceptors for auth. The other one I am using lazy loaded modules.

**Comment by umarov** [comment]
I turned on source maps to find where the error is, and it's on this line https://github.com/angular/angular/blob/5.2.x/packages/common/http/src/xhr.ts#L147

**Comment by jasonaden** [comment]
Looks like there are two issues here. One for AngularCLI (please move to that repo) and another with HTTP, but no reproduction.

If you're still having an issue, please create a reproduction and file a new issue, filling out the new issue template. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).
