### ISSUE TITLE
Improve marketing, accessibility and communication

### ISSUE THREAD

**Issue by MickL** [angular/angular#21745]
## I'm submitting a...
<pre><code>
[ ] Regression
[ ] Bug report
[X] Feature request
[X] Documentation issue or request
[ ] Support request
</code></pre>

## Introduction
I think Angular is the most awesome thing that could have happened to web development until now. And for me, TypeScript is the best thing that happened to JavaScript. Also i think the Angular team is doing an incredible job making a Porsche to a Lamborghini to a Bugatti to a space rocket.

Anyway i feel like we are losing a race against Vue.js at the moment. And i bet you are now saying this is not a race or competition. I know it is not. Still i feel like the marketing, communication to the community, and the documentation could be improved ALOT. This framework is awesome, the technology is awesome, you are awesome - PLEASE show it to the world, explain it right and treat the community nicely.

As a part of the community i got three things to suggest:

## 1. Marketing
We can't compete with Vue.js since it uses JavaScript with no typings. Its accessibility is just super easy for everyone coming from JavaScript. Maybe it is even like jQuery: You don't have to have a lot of knowledge at all, still you can make things possible. For Angular on the other hand it is hard to learn OOP for a regular JS-developer, and even harder for a total beginner. But in my opinion it is more than worth it and that should be communicated.

Also i would aim for "real" developers that may not even got in touch with web development at all. Finally TypeScript makes it possible for a C#, Swift, C++, Python or Java developer to jump straight into web development. Thanks to TypeScript we can build real software with types, interfaces, classes, generics etc. etc. and on top of that Angular gives us the perfect framework for building complex web applications simple. And not even web applications, extend with Electron, NativeScript or Ionic and there are no more constraints! In my opinion this should be communicated more.

Angular is great for big ass applications i would focus marketing on this. Because of its technology and architecture It can be maintainable even after 50 people were working for 5 years. People should say "Use Vue.js for childish things. But when it comes to grown-up stuff use Angular"

Anyway i know Angular is reducing bundle size a lot(and there is angular libraries and elements on the way). So with each release so it gets more and more interesting for little projects, too. I would still aim for huge projects, but also have a little space to see whats coming up and where this is going. People may think: "They are going to Mars in the next year? Uh thats awesome, I wonder where its going in the next 5 years then!"

Easy to update(semantic versioning) should also be promoted. Very nice, updating from 2 to 4 to 5 felt like a minor update for me but no detailed informations about this on the website.

One more very important thing i would promote is the unbelievable progress Angular does. What about showing a graph of bundle size from Angular 2 to Angular 6? With the graph going a little bit in the future saying "Our aim" or something. This is just one example. What happened in this project since RC1 is impressive so please show it to the world!

## 2. Documentation / Accessibility
The documentation is great, don't get me wrong. But also it is frustrating sometimes and when it comes to Vue.js the most positive thing i hear is the documentation. 

My critic points about the documentation:
- It is really longsome
- It is written in tutorial style so when i just think of "How was this one router thing again?" i cant just look for it. I have to scroll through this big tutorial and search and search and search.
- It is missing stuff. I read the full documentation and was thinking i know everything. Still sometimes on the internet i come across stuff i never heard before. E.g. [ngClass] is documentated but not the short [class.classToAdd]
- We probably cant do something about it: Googling for something with the term "Angular" gives 90% AngularJS results. So i mostly search for "Angular 2" which is kind of outdated so i have to try "4" and "5" too with mostly no results.

Here are some suggestions from me:
- The "Tutorial" should be called something like "Quickstart" or "Get into Angular in 60 minutes"
- "Fundamentals" and "Techniques" should be reworked into something called Tutorial - It should not cover every little detail. Instead it give a quick overview of every feature(like add one simple animation) with links to the documentation to dive more deep into topics while working on a practically example project (like tour of heroes). 
- Add a new menu item "Documentation" which is the actual documentation giving us everything ON POINT. Click on routing and see everything related to the router and routing and navigation.
- Maybe add a section for best practices: Usage of service, dump/smart components, how to organize stuff, etc.
- Keep "API" as it is
- The actual documentation could be a wiki so everyone can suggest updates if something can be explained more simple or something is missing
- Take a look at Vue.js documentation how they did it

## 3. Communication to the community
I mentioned this in other issues already: There are some highly requested things like Elements, creating library easily, i18n runtime translations etc. and currently we have to ask for updates and we have to ask for it often and for a long time. If there is an answer it goes down within long issue comments.

I suggest that we need a place on Angular.io to see what is going on:  What is the team working on? Will there be new features? What has high priority? How much effort is put into XY? What are ideas for the future? Are there any estimations for XY?

This is important for 

1. The community: I am so impressed by Angular because i listen to every little detail so i know there is awesome stuff coming. But i bet 95% of the community does not know that. Also its frustrating to hear something awesome(like elements) and then hearing nothing for ages.
2. Decisions for new users which framework to use: A project may take a year and in this time huge stuff is happening within Angular. But who knows whats going on? They can only see the present right now and also a lot of negatives from the past that are no more present today. If bundle size is a concern right now it would be nice to know that it you are aiming to reduce it even further within the next year.

**Comment by MickL** [comment]
I add an answer from @ocombe to #3 (communication to the community) from another issue:

> I understand your concern, and I've asked the same question last week to the team. The reply was that when you make announcements, even if you're being cautious, people will take what you say for a fact. If it works out as you said, it's nice and everyone is happy, but that's rarely the case in development, things get postponed because other things take the priority, or things get canceled because it didn't work or issues arise that you didn't anticipate, etc...
> The point is that even if you say that it's an estimation, if it changes some people will get angry because they took what you said for granted and planed accordingly (for a project, for a business, etc...).
> Let's say that we announce "Angular Elements will be released in March", and you had convinced your boss to use this for the next project instead of Vue (like @alshdavid wants to do), and it turns out that in March it's not ready, it's buggy, or we had to postponed because we need to finish something else first. Then your boss comes to you and blames you, and in return you'll blame the Angular team.
> 
> At Angular Connect, I was so sure that we would get runtime i18n and code translations done for 5.3 that I said that during my talk. We were making good progress, we had design docs and we were working on it already so I had high hopes.
> It turns out that some core changes (new Renderer) will make our work much easier, but also obsolete if we had finished that part before. So we decided to wait a little and work on runtime i18n with the new renderer. It postponed that to v6 instead of 5.3, but it's for the best.
> Now apparently no one has blamed me for the delay this time, but it could have happened and I would have felt terrible (even if it was not really my fault and it was for the best).
> 
> That's why we cannot make announcements like that. From what I've heard, we will try our best in the future to share our roadmap and we work on, and probably that hiring a new devrel will also help for the communication (Rob & Stephen already have a lot of ground to cover).
> 
> I hope that you understand our position as well. As a developer I really really want to share some of the new and exciting stuff that we have planned, and to give you actual numbers for the new bundle size, but I cannot in good conscience do that for now.

I totally understand that and you don't have to make real estimations. On the other hand your text is a nearly perfect note for this announcements.

**Comment by roeba** [comment]
> Angular is great for big ass applications i would focus marketing on this. Because of its technology and architecture It can be maintainable even after 50 people were working for 5 years.

I have been following this project for an evaluation to use it in our company and frankly, I found the exact opposite. Every major version update from Angular 3 to 4 and to 5 had so many problems and breaking changes, that it is impossible to create a big project with the current state and hope to maintain it for more than one year.
Old versions don't get bugfixes, you need to stay up to date. But then you have breaking changes all over the place. I don't know how other libraries do it like React etc., but this makes Angular not usable for companies that need to their projects to be supported for a longer time.

**Comment by ocombe** [comment]
@roeba it pains me to hear that you feel it like this because we spend a lot of time to make sure that we don't break people too much.
We provide LTS versions (v4, and v6 are LTS) and we patch them for 1 year.
We only do breaking changes in each major versions (following semver), and we make sure to provide guidelines to update things. We usually deprecate old behaviors when possible to give people the time to update their code.
We've had good feedback that say that it was easy to upgrade when major versions come out.
Do you have concrete examples?

**Comment by trotyl** [comment]
> Every major version update from Angular 3 to 4 and to 5 had so many problems and breaking changes

@roeba Please do not fake facts even if you don't like it, there has never been a version 3.

**Comment by MickL** [comment]
To all: If you have more suggestions i will add them to the issue.

**Comment by trotyl** [comment]
@MickL I guess you mean **Vue.js** rather than **Vis.js**?

**Comment by MickL** [comment]
Lol sorry i worked too much with vis.js. I updated everything.

**Comment by mlc-mlapis** [comment]
@roeba ... it is just not true ... any upgrade from Angular 2 to 4 and then to 5 was completely done during several hours on our side with just one person. It is a B2B app which has about 50 modules and ~ 500 components, ... We had absolutely no problems.

Also ... your anonymous profile doesn't look very trustworthy from our point of view ... seriously ... who  are you and whom do you represent? Is it so difficult to show in just some trivial details or is it deliberately?

**Comment by StephenFluin** [comment]
@MickL Thanks for your kind comments about some of the things we are doing well, as well as for sharing your hopes for Angular. As this issue overall isn't actionable or resolvable as a single issue, I'm going to close it.

I'd love to continue the conversation, please drop an email to devrel@angular.io and we'd love to discuss some of your ideas, and look for ways that you can help us improve things or help activate the community.
