### ISSUE TITLE
How I load a script from assets to Angular project?

### ISSUE THREAD

**Issue by ljcucc** [angular/angular#21748]
I would like to import a script from `assets`. I do this at `index.html`
```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>...</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--npm package : image-compressor-->
  <script src="/assets/image-compressor/image-compressor.js"></script>
</head>
<body>
  <app-root>
    Loading...
  </app-root>
</body>
```
and in `app.component.ts`
```typescript
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = '...';
  ngOnInit(){
    var imageCompressor = new ImageCompressor(); //create a ImageCompressor from image-compreeor package
    console.log(imageCompressor)
    ...
  }
}
```

then I got a error which has been throw at running, although the error, the website still run and show the ImageCompressor which got on `app.component.ts`.
when I build project `ng build` will be got same error:
![image](https://user-images.githubusercontent.com/22980191/35336976-f657e3d4-0154-11e8-860b-c363172f21cf.png)

```
ERROR in src/app/app.component.ts(??,31): error TS2552: Cannot find name 'ImageCompressor'. Did you mean 'imageCompressor'?
```

How could I do?

Thanks!

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by ljcucc** [comment]
but I tried any script from assets with javascript are not work at all. such as Material Design Components web and firebase SDK and else...

**Comment by Ranboz** [comment]
**FIX**
- Move bootstrap and JQuery files to /assets/..
- Add references in index.html
- Remove references from .angular-cli.json

**new index.html**
=======
<head>
..
	<link rel="stylesheet" href="./assets/css/bootstrap.min.css">
..
</head>
<body>
..
	<script src="./assets/js/jquery.min.js"></script>
	<script src="./assets/js/bootstrap.min.js"></script>
..
</body>

Have a great day.
