### ISSUE TITLE
angular.io and material.angular.io are not reachable

### ISSUE THREAD

**Issue by jamilalisgandarov** [angular/angular#21746]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behaviour
I didn't know where to share this and thought this would be better to open issue here. Documentation website of angular.io and material.angular.io are not reachable
https://imgur.com/a/f2iTX 

## What is the motivation / use case for changing the behavior?
I did hard refresh

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [X] Chrome (desktop) version XX
- [X] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [X] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jamilalisgandarov** [comment]
@trotyl  ?

**Comment by Toxicable** [comment]
Looks fine now

**Comment by jamilalisgandarov** [comment]
@Toxicable Not solved yet, I don't know if it is related to country or not. I have tested it on my smartphone (mobile data) and on different laptops.
https://imgur.com/a/DHWNx

**Comment by jamilalisgandarov** [comment]
Tested with VPN, worked. What is the problem without VPN?

**Comment by gkalpak** [comment]
I don't think this is a problem on our end (not afaict) 😕

**Comment by jamilalisgandarov** [comment]
Just leaving the country name if it is going to happen anyone else: 
**Azerbaijan**
