### ISSUE TITLE
[AIO] Typo in the section ("Test a routed component with parameters")

### ISSUE THREAD

**Issue by last-indigo** [angular/angular#21755]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

https://angular.io/guide/testing#test-a-routed-component-with-parameters

The note under the example of subscribing to route parameters:
```  this.route.paramMap.subscribe(p => this.getHero(p.has('id') && p.get('id')));```
refers to 
> forEach operator to subscribe to id-changing events

while `forEach` was never used in code snippets.

Also, explanation does not completely match the code:
`route.params` vs `route.paramMap`

## Expected behavior

Documentation and code should be in sync.

**Comment by jenniferfell** [comment]
docsarea=testing
file=guide/testing.md

**Comment by brandonroberts** [comment]
Closing as resolved.
