### ISSUE TITLE
Why does the template code for the application angular highlight red each time in GitLab?

### ISSUE THREAD

**Issue by splincode** [angular/angular#21756]
For example, this is the valid syntax of an angular template:
https://gitlab.com/splincode/beria/blob/master/app.component.html

![image](https://user-images.githubusercontent.com/12021443/35347506-60e3eeaa-0146-11e8-9d58-b3ba76e7929c.png)

but for some reason attributes are highlighted

https://gitlab.com/gitlab-org/gitlab-ce/issues/42390

This is a problem in the HTML Editor: http://rouge.jneen.net/pastes/6ZRO

**Comment by splincode** [comment]
http://rouge.jneen.net/pastes/6ZRO

**Comment by jotatoledo** [comment]
The issue tracker is not the right place for general questions. Please read the issue template before creating an issue.

**Comment by splincode** [comment]
https://github.com/jneen/rouge/issues/865

**Comment by splincode** [comment]
But it's about how Angular applications integrate with other editors and in terms of PR it's important

**Comment by vicb** [comment]
NG templates are valid HTML - the issue must be in rouge.

**Comment by splincode** [comment]
The last question was asked on 18 Jul 2017 and no one solved the problem.
