### ISSUE TITLE
Material2 Menu fails on opening due to "partial keyframes"

### ISSUE THREAD

**Issue by rm-code** [angular/angular#21757]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Working menu component.

#### What is the current behavior?
Opening a menu once will cause it to open with all buttons being unclickable.
The console shows this:
```
Invalid keyframe value for property transform: matrix(0,01, 0, 0, 0,01, 0, 0)
```
```
polyfills.bundle.js:5856 ERROR DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at WebAnimationsPlayer.webpackJsonp../node_modules/@angular/animations/esm5/browser.js.WebAnimationsPlayer._triggerWebAnimation (file:///xxxx/dist/vendor.bundle.js:7480:52)
```

#### What are the steps to reproduce?
I just copied this example into my electron app:
https://material.angular.io/components/menu/examples

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/cdk": "^5.0.4",
    "@angular/material": "^5.0.4"
  },
  "devDependencies": {
    "@angular/common": "5.2.0",
    "@angular/compiler": "5.2.0",
    "@angular/core": "5.2.0",
    "@angular/forms": "5.2.0",
    "@angular/http": "5.2.0",
    "@angular/platform-browser": "5.2.0",
    "@angular/platform-browser-dynamic": "5.2.0",
    "@angular/router": "5.2.0",
```
I'm new to npm so maybe I misunderstand the output, but it seems weird to me that npm warns me about unmet dependencies:
```
npm WARN @angular/cdk@5.0.4 requires a peer of @angular/core@~5.1.1 but none was installed.
npm WARN @angular/cdk@5.0.4 requires a peer of @angular/common@~5.1.1 but none was installed.
npm WARN @angular/material@5.0.4 requires a peer of @angular/core@~5.1.1 but none was installed.
npm WARN @angular/material@5.0.4 requires a peer of @angular/common@~5.1.1 but none was installed.
```

I was told to re-post this issue here. (See https://github.com/angular/material2/issues/9348 for the original issue.)

**Comment by Rhmaric** [comment]
Even the example on [material.angular.io](https://material.angular.io/components/menu/overview) got the same issue. I'm using Google Chrome Version 64.0.3282.186

**Comment by JoostK** [comment]
I am going to close this as non-actionable as the Material site doesn't exhibit this issue anymore, so it's not reproducible anymore. Please open a new issue with repro if this is still a problem in latest Angular.
