### ISSUE TITLE
Broken "live example" link in Tour of Heroes tutorial

### ISSUE THREAD

**Issue by nickantzoulis** [angular/angular#21758]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The "live example" link in https://angular.io/tutorial/toh-pt0 results in a page not found.

## Expected behavior

It should display the live example.

## Minimal reproduction of the problem with instructions

Go to either https://angular.io/tutorial or https://angular.io/tutorial/toh-pt0, search for the "live example" link and click it.
It is a link to https://angular.io/generated/live-examples/toh-pt0/eplnkr which does not exist.

## What is the motivation / use case for changing the behavior?

Improved documentation.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sarunint** [comment]
Today, the live examples are converted to StackBlitz.

Refresh the page, the new link should be there.
