### ISSUE TITLE
Documentation/Setting Hashbang Prefix

### ISSUE THREAD

**Issue by schmitch** [angular/angular#21753]
Hello currently I wondered if there is still no way or the documentation is missing on how to set a hashbang prefix.

AngularJS URL uses a hash bang prefix (`#!/url`). Angular defaults to `#/url`.

It doesn't appear this is well documented. Adding `{provide: APP_BASE_HREF, useValue: '!'}` fixes the issue, but the documentation is either missing or unclear.

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by schmitch** [comment]
basically it's not a support issue. because I scanned the whole documentation and didn't found anything on how I accomplish it.
Basically it'works if I add: ` {provide: APP_BASE_HREF, useValue: '!'}`. But documentation isn't good for angular>1.6 anyways.

**Comment by jasonaden** [comment]
Understood.

Probably best to create a new issue and mark it as a documentation request. Agreed, this is a valid issue. Thanks!

**Comment by jasonaden** [comment]
^ Ignore that. I'll just re-open.

**Comment by jenniferfell** [comment]
@IgorMinar Is this a deliberate change from AngularJS? Should we also document #!

**Comment by schmitch** [comment]
`#!` will be used when doing `{provide: APP_BASE_HREF, useValue: '!'}`.

**Comment by trotyl** [comment]
@jenniferfell AngularJS 1.6 was released in 2016-12-08, while Angular in 2016-09-14; so that's not a change made from AngularJS to Angular, just in AngularJS itself.

**Comment by jenniferfell** [comment]
@brandonroberts : Hi. Can you help clarify and triage appropriately?  Thanks!

**Comment by FDIM** [comment]
Curious, can we count on `{provide: APP_BASE_HREF, useValue: '!'}` working in the future?

**Comment by atscott** [comment]
Closing as I don't believe this needs further documentation. `APP_BASE_HREF` documentation states "The base href is the URL prefix that should be preserved when generating and recognizing URLs." The docs do not need any/every specific possible value that can be used.

@FDIM - Yes, you can count on this always working.
