### ISSUE TITLE
Documentation for ngProjectAs

### ISSUE THREAD

**Issue by CWSpear** [angular/angular#21762]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question</code></pre>

`ngProjectAs` is a tool for getting styling to work in specific use-cases as described in https://medium.com/claritydesignsystem/ng-content-the-hidden-docs-96a29d70d11b

I don't see any documentation for this in the Angular docs. Is it safe to use? If so, I could maybe contribute some documentation (wherever it might go...?).

**Comment by trotyl** [comment]
Duplicate of #17983 (`ngProjectAs` is part of the content projection)

**Comment by CWSpear** [comment]
@trotyl oh ok, cool. I searched for `ngProjectAs` (since that's simply all I had to go on when I was introduced to it by another developer) and it doesn't appear in that thread, so it didn't come up.

Looks like it's being taken care of (or at least, enough that this additional issue doesn't add anything). Thanks! 👍

**Comment by blowsie** [comment]
Could someone please provide a link to the relevant section? After reading this, searching google, searching with the angular website, I am unable to find the documentation for `ngProjectAs`

**Comment by mlc-mlapis** [comment]
@blowsie ... yep, the descriptions is missing but in reality it's very trivial thing ... read this
https://medium.com/claritydesignsystem/ng-content-the-hidden-docs-96a29d70d11b
