### ISSUE TITLE
Html styles on Angular.io

### ISSUE THREAD

**Issue by Yerkon** [angular/angular#21769]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

https://angular.io/guide/ajs-quick-reference#style-sheets
Styles are not good decorated
![2018-01-25_15-11-13](https://user-images.githubusercontent.com/4002847/35380005-377ce0e8-01e2-11e8-87fb-54c72a8f5548.png)

## Expected behavior

Something like [this](https://user-images.githubusercontent.com/4002847/35380385-4b5443e4-01e3-11e8-9172-0d4b1ca04dd0.png) ?

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
It's an unclosed `<code-example>` tag [here](https://github.com/angular/angular/blame/master/aio/content/guide/ajs-quick-reference.md#L1257), would you like to submit a PR for it?

**Comment by Yerkon** [comment]
> It's an unclosed <code-example> tag here, would you like to submit a PR for it?

Ok

**Comment by Yerkon** [comment]
I have created pull request https://github.com/angular/angular/pull/21772
