### ISSUE TITLE
generate component directory structure

### ISSUE THREAD

**Issue by langwan** [angular/angular#21766]
my site url router like this

/site/login
/site/logout
/site/singup

/home/list
/home/settings

i need component like this

SiteLoginComponent
SiteLogoutComponent
SiteSingupComponent
HomeLayoutComponent 
HomeListComponent
HomeSettingsComponent

user login auto going the /home/list

HomeLayoutComponent is dashboard layout contains nav item [list, settings]

i holp component directory and name maps  like this

/app
/app/home
/app/home/layout => HomeLayoutComponent
/app/home/list => HomeListComponent
/app/home/settings => HomeSettingsComponent
/app/site/login => SiteLoginComponent
/app/site/logout => SiteLogoutComponent
/app/site/singup => SiteSingupComponent

how to use ng generate ?

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
