### ISSUE TITLE
View changes are not detected after triggering detectChanges and when ngIf is used

### ISSUE THREAD

**Issue by vinayk406** [angular/angular#21768]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

View changes to a component are not detected once changeDetectionRef.detectChanages is triggered manually.

## Expected behavior

Expect the view changes to be reflected

## Minimal reproduction of the problem with instructions

- main.ts
```ts
platformBrowserDynamic().bootstrapModule(AppModule, {ngZone: 'noop'})
```

- app.component.html
```html
{{flag}}
<button *ngIf="showBtn" (click)="flag = !flag">TogglgeFlag</button>
```

- app.component.ts
```ts
class AppComponent {
    showBtn;
    flag = false;
    constructor(private cdr: ChangeDetectorRef) {
        setTimeout(() => {
            this.showBtn = true;
            cdr.detectChanges();
        }, 3000)
    }
}
```

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [x] Chrome (desktop) version 66
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 

</code></pre>

**Comment by trotyl** [comment]
Working fine [here](https://stackblitz.com/edit/angular-cmajgf?file=app%2Fapp.component.ts).

**Comment by vinayk406** [comment]
Clicking on the button should toggle the flag. Which is not happening.

**Comment by trotyl** [comment]
Of course it won't, you didn't call `detectChanges` in event handler.

**Comment by vinayk406** [comment]
Check [this](https://stackblitz.com/edit/angular-ntp1cc).
App is bootstrapped **with ngZone.**. Button click is did not trigger the view changes.

**Comment by trotyl** [comment]
[As you can see](https://stackblitz.com/edit/angular-wnml6r?file=app/app.component.ts) the current zone is wrong after using the unpatched `setTimeout`, but I don't see how it relates to this issue?

**Comment by vinayk406** [comment]
In my application component state can be changed dynamically and externally(without @Inputs).

**Comment by vinayk406** [comment]
I don't think the problem is with zones. Take a look at [this](https://stackblitz.com/edit/angular-vaksgd). 
When I changed *ngIf to show/hide, it is working as expected.

**Comment by mhevery** [comment]
This is working as intended.
