### ISSUE TITLE
Dev build: ibazel watch stops working after 2 refreshes 

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#21770]
## I'm submitting a...

[x] Bug report  
## Current behavior

Try `$(npm bin)/ibazel test packages/core/test/render3` from your favourite shell. Edit a test file in the `packages/core/test/render3` 2 or 3 times and notice that `ibazel` stops picking up changes after 2 or 3 edits.

This was confirmed on multiple machines.

## Expected behavior

`ibazel` should re-build and re-run tests on each and every edit.

## Minimal reproduction of the problem with instructions

Clone this repository and try `$(npm bin)/ibazel test packages/core/test/render3` from your favourite shell. Edit a test file in the `packages/core/test/render3` 2 or 3 times and notice that `ibazel` stops picking up changes after 2 or 3 edits.

## What is the motivation / use case for changing the behavior?

Currently we need to restart `ibazel` process after 2-3 edits which makes working on the code in the TDD mode sub-optimal.  

## Environment

OSX, node v8.9.1

## Other

Discussed this with @IgorMinar and @alexeagle

**Comment by alexeagle** [comment]
Let's continue discussion on that bazel-watcher issue, I don't think it's Angular-specific (can probably repro with a bazel-hello-world app)

**Comment by pkozlowski-opensource** [comment]
@alexeagle do you have a reference to the bazel-watcher issue that we could track?

**Comment by alexeagle** [comment]
Was in the thread above:
https://github.com/bazelbuild/bazel-watcher/issues/117
