### ISSUE TITLE
bug(router): union type Event does not consist of all router event types

### ISSUE THREAD

**Issue by maxkorz** [angular/angular#21777]
## I'm submitting a...
<pre><code>[x] Bug report</code></pre>

## Current behavior
https://github.com/angular/angular/blob/5.2.2/packages/router/src/events.ts#L322-L347
```ts
/**
 * @whatItDoes Represents a router event, allowing you to track the lifecycle of the router.
 *
 * The sequence of router events is:
 *
 * - {@link NavigationStart},
 * - {@link RouteConfigLoadStart},
 * - {@link RouteConfigLoadEnd},
 * - {@link RoutesRecognized},
 * - {@link GuardsCheckStart},
 * - {@link ChildActivationStart},
 * - {@link ActivationStart},
 * - {@link GuardsCheckEnd},
 * - {@link ResolveStart},
 * - {@link ResolveEnd},
 * - {@link ActivationEnd}
 * - {@link ChildActivationEnd}
 * - {@link NavigationEnd},
 * - {@link NavigationCancel},
 * - {@link NavigationError}
 *
 * @stable
 */
export type Event = RouterEvent | RouteConfigLoadStart | RouteConfigLoadEnd | ChildActivationStart |
    ChildActivationEnd | ActivationStart | ActivationEnd;
```
The `Event` type is documented as an Union of all router events. But the declared variable does not consist of all events.

Which leads to the following Typescript error:
> error TS2339: Property 'urlAfterRedirects' does not exist on type 'Event'.
> Property 'urlAfterRedirects' does not exist on type 'RouterEvent'.

Also, IDE can't guess the type and code completion doesn't work:
![](https://i.imgur.com/Tx0L8fP.png)

## Expected behavior
I think the `Event` should be an Intersection type instead:
```ts
/**
 * @whatItDoes Represents a router event, allowing you to track the lifecycle of the router.
 *
 * The sequence of router events is:
 *
 * - {@link RouterEvent},
 * - {@link NavigationStart},
 * - {@link NavigationEnd},
 * - {@link NavigationCancel},
 * - {@link NavigationError}
 * - {@link RoutesRecognized},
 * - {@link GuardsCheckStart},
 * - {@link GuardsCheckEnd},
 * - {@link ResolveStart},
 * - {@link ResolveEnd},
 * - {@link RouteConfigLoadStart},
 * - {@link RouteConfigLoadEnd},
 * - {@link ChildActivationStart},
 * - {@link ChildActivationEnd}
 * - {@link ActivationStart},
 * - {@link ActivationEnd}
 *
 * @stable
 */
export declare type Event = RouterEvent &
                            NavigationStart & NavigationEnd & NavigationCancel & NavigationError & RoutesRecognized & GuardsCheckStart & GuardsCheckEnd & ResolveStart & ResolveEnd &
                            RouteConfigLoadStart & RouteConfigLoadEnd & ChildActivationStart & ChildActivationEnd & ActivationStart & ActivationEnd;
```

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?
With my solution there's no error and code completion in my IDE suggests some properties:
![](https://i.imgur.com/R2RnTRg.png)

## Environment

<pre><code>Angular CLI: 1.6.5
Node: 8.9.4
OS: win32 x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.6.2
webpack: 3.10.0
</code></pre>

**Comment by rafaelss95** [comment]
See #20525 and [ReactiveX/rxjs#3125](https://github.com/ReactiveX/rxjs/issues/3125).

**Comment by jasonaden** [comment]
Thanks. See the above comment about the root issue here.

Also, we can't use intersection types because then we can't, for instance, assign a `NavigationStart` to `Event` because the `route` property is missing in `NavigationStart` (in other words, these events are not ALL event types all the time, they are only ever ONE event type).
