### ISSUE TITLE
Error: Uncaught (in promise): TypeError: guard is not a function

### ISSUE THREAD

**Issue by ellaisys** [angular/angular#21781]
My code is as below 
## I'm submitting a...
import { ActivatedRouteSnapshot, CanActivate, Route, Router, RouterStateSnapshot } from '@angular/router';
import { Store } from '@ngrx/store';
import { Observable } from 'rxjs/Observable';
import { map, take } from 'rxjs/operators';
import { Observer } from 'rxjs';
import { Globals } from '../../app.global';
import { CRMStorageService } from '../services/storage.service';
import 'rxjs/add/operator/take';
//import { CoreState } from '../../core/core.reducer';

@Injectable()
export class AuthGuard implements CanActivate {
    constructor(
        private router: Router,
        private storageService: StorageService) { }

    canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> {
        return this.storageService.getItem(Globals._CURRENT_USER_KEY).take(1).map(token => {
            if (token) {
                return true;
            } else {
                this.router.navigate(['/login']);
            }
        });
    }
}

const appRoutes: Routes = [ 
  { path:'',redirectTo:'/login', pathMatch: 'full' }, 
  { path:'login', component: LoginComponent },
  { path:'reset/:token', component: ResetpasswordComponent },
  {
    path: '',
    canActivateChild: [AuthGuard],
    children: [
            { path:'dashboard', component: DashboardComponent },
            { path:'customerlist', component: CustomerlistComponent }
    ]
  },
  { path: '**', component: ErrorComponent }
];

@NgModule({
  imports: [   
    RouterModule.forRoot(
      appRoutes,
      {
        enableTracing: false // <-- debugging purposes only       
      }
    )
  ],
  declarations: [
    AppComponent,
    .
	.	
  ],  
  providers: [    
    AuthGuard
  ],
  exports: [
  ],
  bootstrap: [
    AppComponent
  ]
})
export class AppModule { }

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
