### ISSUE TITLE
Lazy-loaded module with no blank route should fall back to parent

### ISSUE THREAD

**Issue by mcalmus** [angular/angular#21785]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Use a lazy-loaded route where the sub-route doesn't have the empty route:

top module:
{ path: 'foo', loadChildren: 'foo.module#FooModule' },
{ path: '**', component: NotFoundComponent }

foo.module:
 { path: 'bar', component: 'BarComponent' },
 { path: 'baz', component: 'BazComponent' }

## Expected behavior

When you navigation to foo/bar or foo/baz it displays as expected. When you go to foo/d, it displays the NotFoundComponent. However, if you go to foo, it displays a blank page.

## What is the motivation / use case for changing the behavior?

It would be nice to have submodules that don't have a top-level URL without having to redirect or redundantly include a "not found" module.

## Environment

<pre><code>
Angular version: 5.2.0

**Comment by jasonaden** [comment]
Looks like you need a `component` for your `foo` route.

While this might be a good feature to implement, it should be a pretty rare use case and could be solved by validating your route configurations. I think the better solution would be to do that validation as adding this logic would make the router codebase larger for a very small use case.

If there's a larger use case involved, go ahead and create a new issue describing it.

Thanks!
