### ISSUE TITLE
Issue by using the ol tag by using the ngFor directive

### ISSUE THREAD

**Issue by romulus001** [angular/angular#21798]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Using the nfFor directive on an ol tag

## Expected behavior
The counter on each item stays at 1 and there is a space in between 2 consecutive items

## Minimal reproduction of the problem with instructions
See my code on [my plunker ](https://plnkr.co/edit/Gwf4k04xluh1g7n9tUs6?p=preview)

## Environment

<pre><code>
Angular version: 4.1.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by pkozlowski-opensource** [comment]
@romulus001 your plunker is non-trivial and has 3rd party CSS. On top of this it is not clear what you mean by "The counter on each item stays at 1 and there is a space in between 2 consecutive items" 

> Using the nfFor directive on an ol tag

I've spent a couple of minutes looking at your plunk but I couldn't find any `ol` tags...  I might have missed it, but once again, your plunker is not a small reproduction of a problem...

Given all this I'm going to close this issue as a support request: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem
