### ISSUE TITLE
ActivatedRoute.data type is wrong

### ISSUE THREAD

**Issue by jufarhi** [angular/angular#21805]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently the`ActivatedRoute` class has properties which return a 'BehaviorSubject' but the type in `router_state.d.ts` is `Observable`.

The property `value` is not known by those properties because it's there are `Observable` and not `BehaviorSubject`.

router_state.d.ts
```` 
export declare class ActivatedRoute {
    /** An observable of the URL segments matched by this route */
    url: Observable<UrlSegment[]>;
    /** An observable of the matrix parameters scoped to this route */
    params: Observable<Params>;
    /** An observable of the query parameters shared by all the routes */
    queryParams: Observable<Params>;
    /** An observable of the URL fragment shared by all the routes */
    fragment: Observable<string>;
    /** An observable of the static and resolved data of this route. */
    data: Observable<Data>;
    ...
}
````
router.js
````
function createActivatedRoute(c) {
    return new ActivatedRoute(new BehaviorSubject(c.url), new BehaviorSubject(c.params), new BehaviorSubject(c.queryParams), new BehaviorSubject(c.fragment), new BehaviorSubject(c.data), c.outlet, c.component, c);
}
````

## Expected behavior
Update the `ActivatedRoute`class.

````
export declare class ActivatedRoute {
    /** An observable of the URL segments matched by this route */
    url: BehaviorSubject<UrlSegment[]>;
    /** An observable of the matrix parameters scoped to this route */
    params: BehaviorSubject<Params>;
    /** An observable of the query parameters shared by all the routes */
    queryParams: BehaviorSubject<Params>;
    /** An observable of the URL fragment shared by all the routes */
    fragment: BehaviorSubject<string>;
    /** An observable of the static and resolved data of this route. */
    data: BehaviorSubject<Data>;
    ...
}
````
## Environment

<pre><code>
Angular version: ^5.0.0

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.4.0
- Platform:  Mac

Others:

</code></pre>

**Comment by zakhenry** [comment]
I wish the `ActivatedRoute` type would take a generic so we could type it more strictly - currently the `Data` type is little better than `any` - it is just a string-keyed dictionary of `any`.

The following would be preferred; and not be a breaking change:

```ts
export declare class ActivatedRoute<T extends Data = Data> {
    /** An observable of the URL segments matched by this route */
    url: BehaviorSubject<UrlSegment[]>;
    /** An observable of the matrix parameters scoped to this route */
    params: BehaviorSubject<Params>;
    /** An observable of the query parameters shared by all the routes */
    queryParams: BehaviorSubject<Params>;
    /** An observable of the URL fragment shared by all the routes */
    fragment: BehaviorSubject<string>;
    /** An observable of the static and resolved data of this route. */
    data: BehaviorSubject<T>;
    ...
}
```

**Comment by jasonaden** [comment]
Thanks, but it's intentional to return an Observable. The fact that internally it's a BehaviorSubject isn't supposed to be exposed on the public API, as we may later change to another implementation that keeps the Observable shape.
