### ISSUE TITLE
Virtual DOM & JSX for enhancing UI rendering speed? 

### ISSUE THREAD

**Issue by ghost** [angular/angular#21808]
## I'm submitting a...

[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

## Current behavior
UI rendering speed is not the fastest among the frameworks. It's rather slow when running on java webview, cordova, etc. 

> Lower render speed
> The limited usage of shadow DOM and lack of virtual DOM result in lower performance. The view render/re-render speed is slower compared to the performance shown by other JavaScript frameworks on our chart. 

## Expected behavior
Possibly angular uses something similar to virtual DOM and JSX to render UI faster on mobile devices. 

https://jsx.github.io
https://auth0.com/blog/more-benchmarks-virtual-dom-vs-angular-12-vs-mithril-js-vs-the-rest/

https://clockwise.software/blog/angular-vs-react-vs-vue/

> **faster**
> JSX performs optimization while compiling the source code to JavaScript. The generated code runs faster than an equivalent code written directly in JavaScript. The gain may vary, but even the optimized JavaScript libraries like Box2D becomes faster when ported to JSX (12% faster on iOS 5.1, 29% faster on Android 2.3).

## Minimal reproduction of the problem with instructions

Angular 5, when running on Cordova or any WebView, is somewhat slower than normal native app behavior. 

## What is the motivation / use case for changing the behavior?

Many companies, bloggers have pointed out slow UI rendering speed of Angular 5 as a downside of angular. 
I feel the same. I hope Angular 6 uses something similar to JSX and Virtual DOM like React and Vue do. 

https://auth0.com/blog/more-benchmarks-virtual-dom-vs-angular-12-vs-mithril-js-vs-the-rest/

## Environment

Angular version: 5

Browser:
- [ X] Chrome (desktop) version XX
- [ X] Chrome (Android) version XX
- [ X] Chrome (iOS) version XX
- [ X] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6
- Platform:  Windows, Mac, Java WebView

Others:
https://auth0.com/blog/more-benchmarks-virtual-dom-vs-angular-12-vs-mithril-js-vs-the-rest/

**Comment by ericmartinezr** [comment]
Those benchmarks are really old and using angular2. You probably want to see more up-to-date benchmarks http://www.stefankrause.net/wp/ ([benchmark](http://www.stefankrause.net/js-frameworks-benchmark7/table.html))

**Comment by mlc-mlapis** [comment]
... also here https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html and https://github.com/krausest/js-framework-benchmark

**Comment by jamesharvey2** [comment]
Yes, there are many different benchmarks and claims regarding speed but I'm coming from experience. Although the majority of behavior is in normal boundary but overall experience is that it's somewhat slower on webview application running on android or iOS smartphones. On desktop & laptops, angular is flawless.  If there's a way to increase angular's speed when running on mobile by using JSX or something similar, it would be great. 
This is an opinion based on anuglar's use on cordova which may not what angular is created for...

**Comment by mlc-mlapis** [comment]
@jamesharvey2 ... you didn't tell us what an app you are comparing? It is a big difference between JIT and AOT mode of the same Angular application for example. Probably the best step would be to have `the same simple application as possible` and compare Angular version with others to see ... app's initialization phase and app's repeated rendering phase.

**Comment by jamesharvey2** [comment]
Yes, I'm comparing simple apps. 

The angular-based cordova app I'm talking about is Ionic UI framework which is based on angular 5. 

www.ionicframework.com

You can create a demo app in a minute by using their CLI. 
Overall usage of angular on this example is rather slow than normal web apps, native apps built on java & objective-C. 

and the javascript-based html rendering app example is this app below: 

https://play.google.com/store/apps/details?id=com.tricedesigns.InstantHalloween

See how fast its navigation responds to your tap.  
or you can try React Native example app for a similar experience: 
https://play.google.com/store/apps/details?id=name.ratson.uiexplorer

Thanks,

**Comment by Toxicable** [comment]
`JSX` has nothing to do with runtime.
Angular cannot use a `VDOM` since it already has a alternate strategy called Change Detection
Here's a guide on improving the speed of you app https://github.com/mgechev/angular-performance-checklist
And here's a post on Change Detection https://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html

**Comment by trotyl** [comment]
JSX and Virtual DOM could **NOT** improve runtime performance, what your met is webview vs. native view performance issue. Ionic is using webview, making it slower than native views, you can try [NativeScript](https://www.nativescript.org/) for using native views.

**Comment by josephliccini** [comment]
I do see this question 'Why not a Virtual DOM' a lot in Angular?'.  Every few months or so it comes up.  Might be worth doing a Framework design and comparison in Angular.io so people know why VDOM doesn't make sense for Angular's implementation.

VueJS does a page in their docs: https://vuejs.org/v2/guide/comparison.html#ad

**Comment by arjunyel** [comment]
Template Literals such as lit-html are a better long term option than VDOM from a standards prospective https://github.com/Polymer/lit-html

**Comment by sgf** [comment]
Vurtual DOM and template is a proven technology that has been proven by react and Vue. I think angular should learn from each other, learning advanced technology or ideas to keep pace with the times.

**Comment by mlc-mlapis** [comment]
@sgf ... but the concept used by Angular is faster in many cases than Virtual DOM, so what is the problem?

**Comment by sgf** [comment]
@mlc-mlapis
But as far as I know, angular scores are not optimal in most performance tests.
In addition, in fact, only the large data volume of the situation to talk about performance is meaningful.

**Comment by trotyl** [comment]
@sgf Are you series? What performance tests are you referring to? Well-known examples:

+ https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html
+ https://medium.freecodecamp.org/a-real-world-comparison-of-front-end-frameworks-with-benchmarks-2018-update-e5760fb4a962

Virtual DOM is known bad for performance due to superfluous object creation and loops.

**Comment by sgf** [comment]
@trotyl 
https://www.stefankrause.net/js-frameworks-benchmark7/table.html

**Comment by mlc-mlapis** [comment]
@sgf ... and what exact numbers in that table you mean?

**Comment by trotyl** [comment]
@sgf As you can see Angular is already faster than React and Vue which are using virtual DOM, so what do you expect exactly? Faster than Inferno? Which doesn't seem to be possible regardless of using virtual DOM or not.

**Comment by sgf** [comment]
@trotyl @mlc-mlapis
Clear rows 
Startup time these the obviously lagging behind. Other comparisons have been won and lost, but the difference is minimal.

**Comment by trotyl** [comment]
@sgf That's true, but using virtual DOM in Angular will make "Clear rows" and "Startup time" becoming even worse.

**Comment by iwe7** [comment]
JSX is just a way to write HTML. There is no need to ban it.

**Comment by mhamri** [comment]
to be frank i fall in love with [stenciljs](https://stenciljs.com/). having react hooks and jsx and angular component is something I long for. the question is why angular can't be house of all the good things? if stensil can to do that then angular can do it better

**Comment by anjmao** [comment]
People seems to be confused about virtual dom. While performance is similar virtual dom gives you advanced rendering functionality which is not possible with templates.

Read this:

1. https://medium.com/js-dojo/whats-the-deal-with-vue-s-virtual-dom-3ed4fc0dbb20 https://vuejs.org/v2/guide/render-function.html

**Comment by alxhub** [comment]
Closing - this is based on several misunderstandings of how Angular works and the performance of various DOM synchronization patterns.
