### ISSUE TITLE
BUG: ViewChild property is set before OnInit

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#21800]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently when you have 
```ts
@Component(
{
    selector: 'home-view',
    templateUrl: 'home.component.html'
})
export class HomeComponent implements OnInit, AfterViewInit
{
    @ViewChild('treeview')
    public tree: FancyTreeComponent;

    public ngOnInit()
    {
        console.log(this.tree);//NOT NULL, SHOULD BE NULL
    }

    public ngAfterViewInit()
    {
        console.log(this.tree);//NOT NULL, OK
    }
}
```

before i dont know in which version was `this.tree` null before first call of `ngAfterViewInit`, now its not, which allows me to access `FancyTreeComponent` before it was properly initialized!

Before i was able to check for `null` and knew that component was not initialized. 

Even documentation says `View queries are set before the ngAfterViewInit callback is called.` which does not deny that it can be initialized before `ngOnInit` but in past it was exactly like that it was `null`.

Is it a not mentioned breaking change?

## Expected behavior
`ViewChild`, `ViewChildren`, `ContentChild`, `ContentChildren` should be initialized/set only after `ngAfterViewInit`, respectively `ngAfterContentInit` which are not.

## Minimal reproduction of the problem with instructions

Use code above.

## Environment

<pre><code>
Angular version: 5.1.2

Browser: All
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.4.0  
- Platform:  Windows 

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
If I'm not wrong that changed long ago over here https://github.com/angular/angular/pull/5993

>Component view is not yet created when component constructor is called.
-> use onInit lifecycle callback to access the view of a component

**Comment by kukjevov** [comment]
Hmmm, but there is one problem. This allows you to use component before its initialization. Especialy if you have some code in property setters which are `Input`, that means you have to create property `initialized` and set it in `ngOnInit` and check it in setters. Not very nice solution.

**Comment by pkozlowski-opensource** [comment]
I tend to agree with @kukjevov - the current behaviour seems to be side-effect of implementation choices, rather than designing API to user expectations.

**Comment by alexzuza** [comment]
**Static queries** (ViewChild and ContentChild that are not inside embedded view) are initialized during view creation https://github.com/angular/angular/blob/master/packages/core/src/view/view.ts#L333-L336. 

**Dynamic queries** (VIewChildren, ContentChildren and ViewChild/ContentChild that are located inside embedded view) are calculated during change detection cycle. https://github.com/angular/angular/blob/master/packages/core/src/view/view.ts#L361
https://github.com/angular/angular/blob/master/packages/core/src/view/view.ts#L371

As far as I know this behavior was added as part of new view engine here  https://github.com/angular/angular/commit/4e7752a12a47f537ea5b45b4ee419cda4e1008fd

**Comment by jotatoledo** [comment]
@kukjevov a minimal reproduction of what you explain can be found in the following blitz:

https://stackblitz.com/edit/dog-stuff

**Comment by pkozlowski-opensource** [comment]
We are going to make timing of `@ViewChild` and `@ViewChildren` assignment the same time with ivy view engine.  Assignment will be happening _after_ `ngOnInit` / `ngDoCheck` and _before_ `ngViewInit` / `ngViewChecked`.

**Comment by kukjevov** [comment]
Was this one solved by https://github.com/angular/angular/commit/19afb79 ? It looks like it could be it.

**Comment by kukjevov** [comment]
I am closing this as it has been at least partially solved by angular 8 and need of `static` flag for `ViewChildren`
