### ISSUE TITLE
[Meta] Please add tag to closed issues indicating what release they were/will be fixed in

### ISSUE THREAD

**Issue by zakhenry** [angular/angular#21819]
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behaviour
Currently when issues are encountered it is often the case that the developer just needs to update to the latest patch of angular. They are likely to come across the issue by searching the error message on google, but when the issue has been closed, it is often unclear as to when it will be in a release, or if it has already been released etc.

## Expected behaviour
When bugs are closed, a tag denoting the target release is added to the issue

## Minimal reproduction of the problem with instructions
n/a

## What is the motivation / use case for changing the behaviour?
Developer happiness 😁 

## Environment
n/a

**Comment by trotyl** [comment]
The version can be found if you open that linked commit:

![image](https://user-images.githubusercontent.com/6059170/35469072-145e01b4-0368-11e8-8a09-ae783e509681.png)
![image](https://user-images.githubusercontent.com/6059170/35469083-2d8bbc26-0368-11e8-895f-1db60d502eb3.png)

But there could be two different commit for master and patch, so likely it could still be improved.

**Comment by alexeagle** [comment]
I think the changelog is the way to go, every closed issue will appear there.
