### ISSUE TITLE
Docs(aio). The AOT compiler request

### ISSUE THREAD

**Issue by Yerkon** [angular/angular#21829]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## What is the motivation / use case for changing the behavior?

https://angular.io/guide/aot-compiler#angular-compiler-options
I think **Angular Compiler Options** topic will be better to allocate after the description topic. Cause compiler options is not matter for first reading. When someone opened this topic, will be better to read and understand about it, before configuring some options

**Comment by jenniferfell** [comment]
Thank you for the suggestion. I agree; reference information such as this is usually at the end of the topic. We'll check with engineering and see if there's a reason it's first. If so, we'll see if we can position it better. Thank you.

**Comment by jenniferfell** [comment]
@chuckjaz Any reason to keep these options at the top?

**Comment by chuckjaz** [comment]
@jenniferfell No. They can be moved.

**Comment by kapunahelewong** [comment]
Thank you, @Yerkon. This looks like it was resolved in #22353 so I'll close this issue, but if you have further questions on this topic, please feel free to reopen and tag me.
