### ISSUE TITLE
Silent failure from ng_module

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#21820]
Repro is in https://github.com/alexeagle/angular-bazel-example/pull/64
I repro'd locally too:

```
$ bazel build //src
INFO: Analysed target //src:src (0 packages loaded).
INFO: Found 1 target...
ERROR: /Users/alexeagle/Projects/angular-bazel-example/src/BUILD.bazel:5:1: Compiling Angular templates (ngc) //src:src failed (Exit 1)
src/main.ts(2,34): error TS2307: Cannot find module './app.ngfactory'.

Target //src:src failed to build
```
looks like a compilation error is being masked, this import is okay.

**Comment by alxhub** [comment]
Hey @alexeagle, is this still a bug in the modern Bazel/Angular integration? I don't know enough about Bazel and how things have changed to update the repro.

**Comment by alexeagle** [comment]
We are planning to drop our View Engine example in rules_nodejs, and I don't have time to track down a repro for this either. I guess close as can't repro?
