### ISSUE TITLE
Why do you use the old logo in npm?

### ISSUE THREAD

**Issue by splincode** [angular/angular#21827]
https://www.npmjs.com/~angular

![image](https://user-images.githubusercontent.com/12021443/35471303-9e80699e-0369-11e8-97a2-f07a38de198b.png)

And why is there a black band there?

**Comment by jasonaden** [comment]
Thanks for noticing. It's not really an Angular issue, so I'll close, but I asked for it to get corrected.

**Comment by IgorMinar** [comment]
This repo is actually the right place to track this. There is no better place. I'll leave this open until the issue is fixed.

**Comment by IgorMinar** [comment]
I fixed this. It should be good now.

**Comment by splincode** [comment]
@IgorMinar Thank you!
