### ISSUE TITLE
<!DOCTYPE html> <html> <head>     <title>Module 1 homework</title>     <link rel="Stylesheet" href="https://https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8"         crossorigin="anonymous"> </head> <body ng-app="app" ng-controller="fristController">     <div class="container">         <h1>Module 1 homework</h1>         <h2>The current date is: {{CerrentDate | date: 'dd/MM/YYYY'}}</h2>     </div>     <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js"></script>     <script type="text/javascript">          var app=angular.module( 'Datentime',[]);           //Datentime.controller( 'firstController',[         app.controller( 'firstController',function($scope){ $scope.CurrentDate= new Date();          }); </script>         </body> </html>

### ISSUE THREAD

**Issue by ArchanaGurav** [angular/angular#21832]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Yerkon** [comment]
This is not good decorated. Be more descriptive and follow convention

**Comment by kara** [comment]
Not enough info here to be actionable. Please feel free to re-open with the issue template filled out.
