### ISSUE TITLE
Angular for those who speak portuguese

### ISSUE THREAD

**Issue by helder-rangel** [angular/angular#21836]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I suggest that site https://angular.io/resources recommend the Angular course for those who speak Portuguese.
The online course is at https://loiane.training/course/angular-2/

Helder Rangel

## Expected behavior

None.
## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by helder-rangel** [comment]
Angular for portuguese language.

**Comment by jenniferfell** [comment]
Thank you for the suggestion and the link. 

@StephenFluin Please take a look. Do you think this is a good resource to add here https://angular.io/resources?

**Comment by StephenFluin** [comment]
Looks like a great course. The only thing we would ask is for @loiane to update the naming to not include the version number before we list it. It lists v2 and v4, but this is great content for versions 5 and 6 and beyond as well!

**Comment by loiane** [comment]
Done! It's been a while since I updated the description.
Removed the versions references and also updated the link to https://loiane.training/course/angular/.

Thanks for recommending the course @helder-rangel! :)

**Comment by helder-rangel** [comment]
@loiane also bought his book and recommended to teacher @lucachaves "[Data structure and algorithms in` JavaScript] (https://goo.gl/YHQTsV) "`.
I'm having a hard time learning, but with its Angular course it became clearer.

**Comment by StephenFluin** [comment]
@helder-rangel I highly recommend creating a PR to add this course if there isn't one. Can you do that?

**Comment by helder-rangel** [comment]
@StephenFluin Angular for those who speak portuguese #21836

**Comment by kara** [comment]
Closed by https://github.com/angular/angular/commit/ec6d6175d23d655a5d75874d5ca9424741b1dfcf
