### ISSUE TITLE
Router does not respect path of lazy-loaded module

### ISSUE THREAD

**Issue by pitops** [angular/angular#21838]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

**auth.routing**
```
const AUTH_ROUTES: Routes = [
  { path: 'signin', component: SignInComponent },
]
export const authRouting = RouterModule.forChild(AUTH_ROUTES)
```

**app.routing**
```
export const ROUTES: Routes = [
  { path: 'auth',loadChildren:'./auth/auth.module#AuthModule'}
]
```

User can access `localhost:4200/auth/signin` and `localhost:4200/signin`

## Expected behavior
Expected behavior would be to only allow for access to `localhost:4200/auth/signin` . This makes it hard for guards to trigger as well, as the guard only triggers on `auth/signin`

## Minimal reproduction of the problem with instructions
[stackblitz](https://stackblitz.com/edit/angular-bbfa8b)

try both `auth/signin` and `signin` paths

## What is the motivation / use case for changing the behavior?
The router should respect the namespace for the lazy loaded module - in this case `auth`

## Environment
<pre>Development environment<code>
Angular version: v5.2.2

</code></pre>

**Comment by Toxicable** [comment]
What do you mean by respect?
Your Stack Blitz is broken.
From your routing the only paths you've defined are ones with the prefix `/auth`, you have not defined a path `'/signin'`.

I don't see any but with Angular here

**Comment by pitops** [comment]
@Toxicable No stackblitz is not broken

Exactly my point! I haven't defind a path `/signin` yet i can access it even though its under `auth/signin`

**Comment by trotyl** [comment]
![image](https://user-images.githubusercontent.com/6059170/35481388-9d7b12ac-045d-11e8-8191-686066f1a864.png)

@pitops `AuthModule` is not a lazy-loaded module in your provided case.

**Comment by Toxicable** [comment]
@pitops , it wasn't working for me.
Either way, as pointed out, your reproduction differs from your explaination above, you're importing the lazy module, therefore making it not lazy and just a normal module

**Comment by pitops** [comment]
@trotyl @Toxicable I see what you are saying but if i want to access part of the auth module in other components/services you are saying i cannot do it using lazy module loading?

**Comment by mlc-mlapis** [comment]
@pitops ... if you want to a lazy loaded module works as a real lazy module = not loaded during initialization phase when a main app starts ... you can't have them directly related ... and you have to use just DI to inject other providers from the main app into a lazy loaded module.

**Comment by pitops** [comment]
@mlc-mlapis i get that but it seems to me since most modules can be tied up together using DI, that in a sense lazy loading is impossible.

**Comment by mlc-mlapis** [comment]
@pitops ... ooh, ... you are the author ... so please the issue.

**Comment by trotyl** [comment]
For reference: duplicate of #12648
