### ISSUE TITLE
BreakpointObserver returning incorrect result (when Element Inspector not open)

### ISSUE THREAD

**Issue by JoeKendall** [angular/angular#21839]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When detecting viewport size using `BreakpointObserver` and `Breakpoints` the returned boolean is consistent except from in between the pixel range of 600px and 650px only when Inspect Element is not open. Open Element Inspector, and the problem does not manifest. 

## Expected behavior

Attached Stackblitz should return 'handset or smaller' up to 960px, and 'bigger than handset' over that. [Angular Layout Breakpoints.](https://material.io/guidelines/layout/responsive-ui.html#responsive-ui-breakpoints)

## Minimal reproduction of the problem with instructions

*STEPS TO REPRODUCE*
```
      breakpointObserver.observe([
        Breakpoints.Handset
      ]).subscribe(result => {
        if (result.matches) {
          this.screen_size = 'handset or smaller';
        } else {
          this.screen_size = 'bigger than handset';
        }
      });
```
*MINIMAL DEMO*
* Go to: https://stackblitz.com/edit/angular-wfqrdz
* Slide the viewport size over/under 960px to see the desired result. 
* Then slide the viewport size in/around 550px to 700px to see the problem. 
* Finally, launch Inspect to see the issue stops.

## Environment
![environment](https://d2ffutrenqvap3.cloudfront.net/items/3v2I3b1V0a3G3k0r2x3v/Screen%20Shot%202018-01-28%20at%2013.40.44.jpg?v=522d2daf "Environment")

<pre><code>
Browsers tested on:
- [x] Chrome (desktop) Version 63.0.3239.132 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) Version 11.0.2 (13604.4.7.1.3)
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by ericmartinezr** [comment]
Hey @JoeKendall , would you mind opening the issue in angular material's repo? https://github.com/angular/material2

**Comment by JoeKendall** [comment]
Oops, sorry!
The new issue is here for reference: https://github.com/angular/material2/issues/9652
