### ISSUE TITLE
"Cheatsheet"'s Documentation of @Injectable has it backwards

### ISSUE THREAD

**Issue by eepstein** [angular/angular#21843]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

https://angular.io/guide/cheatsheet

Incorrectly reads:

<<
@Injectable()class MyService() {} | Declares that a class has dependencies that should be injected into the constructor when the dependency injector is creating an instance of this class.
-- | --
>>

## Expected behavior

Should be more along the lines of:

<<

@Injectable()class MyService() {} | Declares that a class can be injected as a dependency into other classes via the other class's constructor when the dependency injector is creating an instance of the other (dependent) class.
-- | --

>>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jotatoledo** [comment]
No, its ok like that. An `Injector `instance can inject class instances independent of the decorator. The difference is:

- If the class is decorated with `Injectable`, the dependencies wont be resolved (class members will be undefined/null/default)
- If the class is decorated `Injectable`, the `Injector `instance will attempt to resolve the dependencies, throwing an exception if it cant.

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

**Comment by eepstein** [comment]
I don't think the issue I was raising was understood.

The wording of the existing documentation appears to be about the "Injector", but it is documenting the "@Injectable" metadata annotation.

The comment from @jotatoledo is about how the parts function - and in that he is absolutely correct.  Unfortunately, that doesn't line up with the existing documentation.  

Simple put the existing documentation is flat out wrong.  It reads that adding an "@Injectable" "Declares that a class has dependencies that should be injected into the constructor when the dependency injector is creating an instance of this class."  That is false.  It is the other way around.  It declares that the class can be used by an Injector and be injected *into other classes* during those classes construction.
