### ISSUE TITLE
httpParams in 5.2.x has a bug that not encode URI

### ISSUE THREAD

**Issue by xp44mm** [angular/angular#21849]
## Current behavior

the httpParams class generate query string when contains `+` will be not encoded to `%2B`

```javascript
http.get('/api', {
            params: new HttpParams().set('test', ';/?:@&=+$,#')
        })

```
use chrome browser:
```
Request URL:http://localhost:53911/api?test=;/?:@%26=+$,%23
```
the encoded  is
```
test:;/?:@&= $,#
```

**Comment by tiep-phan** [comment]
Relates to https://github.com/angular/angular/issues/11058

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

<hr>

There's also another related issue here: https://github.com/angular/angular/issues/10280
