### ISSUE TITLE
Dead link in Angular.io documentation

### ISSUE THREAD

**Issue by samithaf** [angular/angular#21847]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Dead link in dynamic component sample app

## Expected behavior
There should be a sample app or remove the link

## Minimal reproduction of the problem with instructions
Access to [https://angular.io/guide/dynamic-component-loader](https://angular.io/guide/dynamic-component-loader) and click on live sample link at the bottom of the page

## What is the motivation / use case for changing the behavior?
N/A

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 63
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by samithaf** [comment]
@trotyl you were so quick to respond. I just realised too!. Probably SW cache comes to the picture? I am sure lot many people experiencing the same problem. Maybe need to add a notification in Angular.io saying flush the cache. :)

**Comment by samithaf** [comment]
Now I can see the new example but again it throws a run time error. Should I open a seperate issue for it?

```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'null: undefined'. Current value: 'null: Bombasto'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?
    at viewDebugError (VM1037 core.umd.js:9797)
    at expressionChangedAfterItHasBeenCheckedError (VM1037 core.umd.js:9775)
    at checkBindingNoChanges (VM1037 core.umd.js:9942)
    at checkNoChangesNodeInline (VM1037 core.umd.js:13990)
    at checkNoChangesNode (VM1037 core.umd.js:13964)
    at debugCheckNoChangesNode (VM1037 core.umd.js:14793)
    at debugCheckRenderNodeFn (VM1037 core.umd.js:14733)
    at Object.eval [as updateRenderer] (VM1087 HeroProfileComponent.ngfactory.js:21)
    at Object.debugUpdateRenderer [as updateRenderer] (VM1037 core.umd.js:14715)
    at checkNoChangesView (VM1037 core.umd.js:13804)
```

**Comment by trotyl** [comment]
That's already tracked on #19322, which doesn't affect functionality.
