### ISSUE TITLE
How do I make sense of Zone errors?

### ISSUE THREAD

**Issue by dylanbaxter** [angular/angular#21841]
Support request
Yeah, I'm not on StackOverflow, but I am on Github.

I'm trying to get the most basic functionality working on Angular, but zonejs is making it impossible to troubleshoot. It produces freaking incomprehensible errors which seem to have fsck-all to do with the actual problem.
Ridiculous error below:

{…}__zone_symbol__currentTask: Object { runCount: 0, _state: "notScheduled", type: "microTask", … }__zone_symbol__error: Error: NetworkError when attempting to fetch resource.
  Instantiating npm:@angular/material/bundles/material.umd.js
  Loading http://localhost:3000/build/app/app.module.js
  Loading main.js
Stack trace:
t@http://localhost:3000/node_modules/systemjs/dist/system.js:4:184 [<root>]
i.prototype.import/<@http://localhost:3000/node_modules/systemjs/dist/system.js:4:37168 [<root>]
Zone.prototype.run@http://localhost:3000/node_modules/zone.js/dist/zone.js:126:24 [<root> => <root>]
scheduleResolveOrReject/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:713:52 [<root>]
Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:166:28 [<root> => <root>]
drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:546:25 [<root>]
__zone_symbol__stack: "zoneify/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:834:33\nJ@http://localhost:3000/node_modules/systemjs/dist/system.js:4:10818\nWe/<@http://localhost:3000/node_modules/systemjs/dist/system.js:4:30081\nZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:334:17\nZone.prototype.run@http://localhost:3000/node_modules/zone.js/dist/zone.js:126:24\nscheduleResolveOrReject/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:713:52\nZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:367:17\nZone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:166:28\ndrainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:546:25\n"columnNumber: Getter & SetterfileName: Getter & SetterlineNumber: Getter & Settermessage: Getter & Settername: Getter & SetteroriginalErr: TypeError: NetworkError when attempting to fetch resource.
Stack trace:
zoneify/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:834:33
J@http://localhost:3000/node_modules/systemjs/dist/system.js:4:10818
We/<@http://localhost:3000/node_modules/systemjs/dist/system.js:4:30081
ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:334:17
Zone.prototype.run@http://localhost:3000/node_modules/zone.js/dist/zone.js:126:24
scheduleResolveOrReject/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:713:52
ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:367:17
Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:166:28
drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:546:25
originalStack: Getter & Setterstack: Getter & SettertoSource: function value()toString: function value()zoneAwareStack: Getter & Setter__proto__: Object { … } localhost:3000:12:49

By the way, the file on which it appears to be puking is present. There are no 404 errors during page load, nor during the subsequent 64 FILES LOADED successfully. 64?!?!? 2.86 MEGS for an EMPTY application. Holy crap, however did you people manage to make this thing so damn heavy and unapproachable? Have ALL the design patterns been shoe-horned into this framework, or is there any facility available for stupid developers like myself to actually create a working SPA? Please, for the sake of ever getting actual work done again, please put down the KoolAid!
...and please don't tell me to just use Angular CLI. I don't want any more single-use application bootstrap scripts on my box, and I don't need the kitchen sink installed on my project, unit tests, a handy server script, etc, and I'm so sick of starting over and over again to fix simple errors. Its just a damn SPA, how complicated does it have to be?

Many thanks to anyone who will help a crotchety old geezer like me to figure out any of this newfangled contrivance.

**Comment by JiaLiPassion** [comment]
@dylanbaxter , just to debug, you can add following file in `polyfill.ts`.

```javascript

import 'zone.js/dist/zone';  // Included with Angular CLI.
import `zone.js/dist/zone-error';
```

which will reduce the `zone` stack traces.

**Comment by dylanbaxter** [comment]
"Included with Angular CLI", lol. 
Well I put a copy of the file in my node_modules (rather than completely upend everything again and install CLI and create a new project from scratch) and reloaded. I guess that had some effect on the error:
{…}
__zone_symbol__currentTask: Object { runCount: 0, _state: "notScheduled", type: "microTask", … }
__zone_symbol__error: Error: NetworkError when attempting to fetch resource.
  Instantiating npm:@angular/material/bundles/material.umd.js
  Loading http://localhost:3000/build/app/app.module.js
  Loading main.js
Stack trace:
t@http://localhost:3000/node_modules/systemjs/dist/system.js:4:184 [<root>]
i.prototype.import/<@http://localhost:3000/node_modules/systemjs/dist/system.js:4:37168 [<root>]
Zone.prototype.run@http://localhost:3000/node_modules/zone.js/dist/zone.js:126:24 [<root> => <root>]
scheduleResolveOrReject/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:713:52 [<root>]
Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:166:28 [<root> => <root>]
drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:546:25 [<root>]
__zone_symbol__stack: "zoneify/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:834:33\nJ@http://localhost:3000/node_modules/systemjs/dist/system.js:4:10818\nWe/<@http://localhost:3000/node_modules/systemjs/dist/system.js:4:30081\nZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:334:17\nZone.prototype.run@http://localhost:3000/node_modules/zone.js/dist/zone.js:126:24\nscheduleResolveOrReject/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:713:52\nZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:367:17\nZone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:166:28\ndrainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:546:25\n"
columnNumber: Getter & Setter
fileName: Getter & Setter
lineNumber: Getter & Setter
message: Getter & Setter
name: Getter & Setter
originalErr: TypeError: NetworkError when attempting to fetch resource.
Stack trace:
zoneify/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:834:33
J@http://localhost:3000/node_modules/systemjs/dist/system.js:4:10818
We/<@http://localhost:3000/node_modules/systemjs/dist/system.js:4:30081
ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:334:17
Zone.prototype.run@http://localhost:3000/node_modules/zone.js/dist/zone.js:126:24
scheduleResolveOrReject/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:713:52
ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:367:17
Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:166:28
drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:546:25
originalStack: Getter & Setter
stack: Getter & Setter
toSource: function value()
toString: function value()
zoneAwareStack: Getter & Setter
__proto__: Object { … }
localhost:3000:12:49
<anonymous>
http://localhost:3000/:12:49
ZoneDelegate.prototype.invoke
http://localhost:3000/node_modules/zone.js/dist/zone.js:334:17
Zone.prototype.run
http://localhost:3000/node_modules/zone.js/dist/zone.js:126:24
scheduleResolveOrReject/<
http://localhost:3000/node_modules/zone.js/dist/zone.js:713:52
ZoneDelegate.prototype.invokeTask
http://localhost:3000/node_modules/zone.js/dist/zone.js:367:17
Zone.prototype.runTask
http://localhost:3000/node_modules/zone.js/dist/zone.js:166:28
drainMicroTaskQueue
http://localhost:3000/node_modules/zone.js/dist/zone.js:546:25

Still a whole lot of detail about nothing I care about.
Could this be trying to tell me that I have a bad mapping in my system.config.js? I checked and double-checked it already:

System.config({
  baseURL: './build/app',
  paths: {
    'npm': '/node_modules'
  },
  packages: {
    '.': {
      defaultExtension: 'js'
    }
  },
  map: {
    '@angular/core': 'npm/@angular/core/bundles/core.umd.js',
    '@angular/platform-browser-dynamic': 'npm/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
    '@angular/platform-browser': 'npm/@angular/platform-browser/bundles/platform-browser.umd.js',
    '@angular/compiler': 'npm/@angular/compiler/bundles/compiler.umd.js',
    '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
    '@angular/common': 'npm/@angular/common/bundles/common.umd.js',
    '@angular/cdk/platform': 'npm:@angular/cdk/bundles/cdk-platform.umd.js',
    '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
    '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
    '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',
    '@angular/material': 'npm:@angular/material/bundles/material.umd.js',
    'rxjs':'npm/rxjs',
    'jquery': 'npm/jquery/dist/jquery.js',
    'hammerjs': 'npm/hammerjs/hammer.min.js',
    'zone.js': 'npm/zone.js'
  }
});

Still going around in circles trying to get basic Ng stuff working, as usual.

**Comment by mlc-mlapis** [comment]
@dylanbaxter ... sure, it on you ... just use this config ...
```
platformBrowserDynamic()
    .bootstrapModule(AppModule, {
        ngZone: 'noop'
    });
```
... and also probably read this post https://blog.angularindepth.com/do-you-still-think-that-ngzone-zone-js-is-required-for-change-detection-in-angular-16f7a575afef

**Comment by dylanbaxter** [comment]
[head explodes]
'Looks like I've got angular/core 4.1.3, which doesn't have that property on CompilerOptions. What's more, from the article you linked I surmise that 1. should I disable zones in Angular then updates to data bindings won't occur automatically, which is freaking core to the mission here, and 2. zones are damned complicated and to use Angular effectively I had better go read 5 or 6 more articles full of information that might already be out of date.

Fsck it, I'm gonna go outside and build something out of wood instead. This kinda crap makes me hate computers.

**Comment by HilalHakla** [comment]
Zone errors are so frustrating, i've been looking to solve an error for hours and couldn't do it..

**Comment by hopsinat** [comment]
why are people downvoting dylan?, because he seems mad after hours of trying? Seriously downvotes don't help anyone.

**Comment by dylanbaxter** [comment]
To be fair, most people haven't the patience to help a complainer and I was venting pretty hard.
It turns out I was trying to use a space shuttle to haul groceries.  Angular is far too complicated for simpletons like me with small projects.
To those I have offended I apologize.

**Comment by Hamcker** [comment]
so what? it's solved by creating something out of wood? :/

**Comment by dylanbaxter** [comment]
Yep, I abstracted the problem so far out I ended up in the wood shop 🤣 
Oh and I switched from Angular to Vue.

**Comment by Hamcker** [comment]
But I didn't gave up and made a **monkey patch** right before **Angular** for my problem, how ever I'm thinking to wood shop also 💃

**Comment by JiaLiPassion** [comment]
Is there any issues to `import 'zone.js/dist/zone-error'`? It will bypass the most of `Zone related stacktraces`.

**Comment by abodn70** [comment]
> ```js
> import 'zone.js/dist/zone';  // Included with Angular CLI.
> import `zone.js/dist/zone-error';
> ```

man thank you very much after searching on the internet for like 2 hours you solved my problem thank you maaaaaaaan

**Comment by Prinsn** [comment]
@abodn70 
@JiaLiPassion 

that code block is misformatted, it's wrapping a string as open ` and close '
