### ISSUE TITLE
Angular 5.x two-way binding doesn't work on Firefox for Windows or OSX

### ISSUE THREAD

**Issue by kyle-hall** [angular/angular#21846]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When using the latest version of Firefox (58 at the time of issue submission) on either Windows or OSX, I can't get the model of my component to change on text input. I start with a clean project generated by the CLI, which I have the newest version of. I add an input to the generated app component, after including the FormsModule in my app.module.ts file, like so:

` <input [(ngModel)]="title" placeholder="app name">`

After starting the app with `ng serve`, I attempt to change the title of the app via the text box I created above. In Firefox on either Windows 10 or OSX Sierra (10.12.6), the title at the top of the page does not change in response to my input. But, if I switch to Chrome, the app works as expected, with the title matching the contents of that text input. I understand that, under the hood, this is no longer implemented as actual two-way data binding in Angular 2+. But it is my understanding that by using both `[]` and `()` around ngModel, I am declaring, in Angular 2+ language, what behaves/looks the same as two-way binding would have in AngularJS.

## Expected behavior

I expect that the framework would support all major browsers on all major OSes.

## Minimal reproduction of the problem with instructions

Steps to reproduce:
1. Open the plunk provided below in Firefox 58 on a machine running either Windows 10 or OSX.
2. Run the plunk and try to change the text in the input.
3. It should be observed that the input changes, but the title does not.

Minimal Demo: http://plnkr.co/edit/YdAFv08aNZzqpbiSuI6e

## What is the motivation / use case for changing the behavior?

I would like the browser I use to be supported by the framework so I don't have to have two browsers open while trying to learn to use said framework. I would also expect that some of the users of my apps would also being using Firefox, and I would like my apps to work for them, as well.

## Environment

<pre><code>
Angular version: X.Y.Z

Angular version: 5.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 58
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4 
- Platform:  Windows 10, Mac 

Others:

</code></pre>

Interestingly, Linux machines running Firefox do not seem to have this problem. I posted in the Angular gitter channel and other users reported that my code worked for them and that they were running Linux machines. These comments can be found here: https://gitter.im/angular/angular?at=5a6cfdedae53c159034279c5

**Comment by sarunint** [comment]
Hmm, I'm running Firefox 58 on Windows 10. It's working fine.

![angular](https://user-images.githubusercontent.com/3850197/35490938-aaa64ba4-04d5-11e8-895a-d4441228664d.gif)

**Comment by trotyl** [comment]
![image](https://user-images.githubusercontent.com/6059170/35490950-3271c290-04de-11e8-82a7-1e1539eab6cc.png)

Working fine in OSX...

**Comment by kyle-hall** [comment]
😕 I have tried this out many times with different code. I created a couple different projects locally, as well as the plunk I posted in the issue, and I saw the same thing each time (Firefox not working, Chrome working).

**Comment by sarunint** [comment]
@kyle-hall Can you try with a different computer?

**Comment by kyle-hall** [comment]
Yeah, I use a Mac for work. I tried it on that machine, and saw the same problem.

**Comment by sandangel** [comment]
Different issue but same feeling https://github.com/angular/angular/issues/19712
_Why only me can see this?_

**Comment by pkozlowski-opensource** [comment]
@kyle-hall I would suggest trying on different machines and / or using a browser in the incognito mode to exclude any potential interference from browser extensions.

In any case this sounds like sth specific to your environment, so closing till we've got a reliable way of reproducing this.

**Comment by kyle-hall** [comment]
I know this issue is closed, but I'll post my new findings anyway, in case anyone is interested.  Long story short, don't use the Vimium browser extension for Firefox. It was what caused my problems. I figured it out after downloading a clean version of Firefox that didn't have any extensions. When that worked, I started disabling add-on in Firefox until the app worked with Vimium disabled.

**Comment by hundredrab** [comment]
@kyle-hall thanks for reporting your findings. I finally found the answer to why my code never seemed to work all those months ago when I first started Angular xD
