### ISSUE TITLE
angular.io about page bug

### ISSUE THREAD

**Issue by Kirkhammetz** [angular/angular#2184]
Don't know if it's the right place to report it but if you open a bio on the about of angular.io then close it and reopen another one it fail to bind.

![immagine](https://cloud.githubusercontent.com/assets/5617452/7842625/b5a102b2-04a4-11e5-9cb8-761eebb4bd7e.jpg)

**Comment by gdi2290** [comment]
https://github.com/angular/angular.io

**Comment by Kirkhammetz** [comment]
Ok, thanks sorry for the wrong repo.

**Comment by pkozlowski-opensource** [comment]
Duplicate of https://github.com/angular/angular.io/issues/132
