### ISSUE TITLE
Attribute name not appear in DOM

### ISSUE THREAD

**Issue by kelvinsleonardo** [angular/angular#21845]
When the matInput is nested in a ngFor the attribute name don't appear in DOM.

![codigoname](https://user-images.githubusercontent.com/7854286/35440160-65eb5ad8-0285-11e8-8c3c-42205b7526a6.png)

Dev tools chrome
![field](https://user-images.githubusercontent.com/7854286/35440219-948d3a32-0285-11e8-8117-7d12bcfa7598.png)

Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.0.0
Material: 5.0.0-rc0
OS: Ubuntu 14.04
TypeScript: 2.5.3
Browsers: Chrome Versão 60.0.3112.90 (Versão oficial) 64 bits

Any thoughts?

**Comment by trotyl** [comment]
Duplicate of #19320

**Comment by pkozlowski-opensource** [comment]
This is a duplicate of  #19320 indeed, thnx @trotyl
