### ISSUE TITLE
How to prevent button click event

### ISSUE THREAD

**Issue by alanhg** [angular/angular#21853]
I create a is-login.directive

```html
<button type="button" appIsLogin (click)="sayHello()">
    down
</button>
```

```typescript
    sayHello() {
        console.log('clicked');
    }
```

```typescript
import {Directive, HostListener} from '@angular/core';

@Directive({
    selector: '[appIsLogin]'
})
export class IsLoginDirective {

    isLoginIn = false;

    constructor() {
    }

    @HostListener('mousedown', ['$event'])
    onClick(event: Event): boolean {
        if (!this.isLoginIn) {
            console.log('mousedown');
            event.preventDefault();
            event.stopPropagation();
            return false;
        }
        return true;
    }
}
```

## Current behavior
When I clicked the button, both events happened.
![image](https://user-images.githubusercontent.com/9245110/35511194-fdc287ca-0535-11e8-8e5d-9b8fbd8c501e.png)

## Expected behavior
I hope click event does not happen.

## Environment
```
"@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
```

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
