### ISSUE TITLE
You cannot load the specified default module dynamically depending on the variable.

### ISSUE THREAD

**Issue by 973257307** [angular/angular#21850]
![n icfieawn f oief3o 6](https://user-images.githubusercontent.com/20786616/35505239-73be4420-0520-11e8-8fe6-32139ba29752.png)
You cannot load the specified default module dynamically depending on the variable.

**Comment by mlc-mlapis** [comment]
@973257307 ... you missed some basic points how it works ... read the doc first ... this is `issues` channel -> for existed bugs and new features ... not answering your questions.

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
