### ISSUE TITLE
Error: Invalid configuration of route '': Array cannot be specified

### ISSUE THREAD

**Issue by muhammadumerfarooq** [angular/angular#21858]
i came through this error while running angular, can any one help me to figure this out..
my **app.module.ts** file is  
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { HeaderComponent } from './header.component';
import { RecipesComponent } from './recipes/recipes.component';
import { RecipesListComponent } from './recipes/recipes-list/recipes-list.component';
import { RecipesItemComponent } from './recipes/recipes-list/recipes-item.component';
import { RecipesDetailComponent } from './recipes/recipes-detail/recipes-detail.component';
import { UserdropdownDirectiveDirective } from './userdropdown-directive.directive';
import { ShoppingListComponent } from './shopping-list/shopping-list.component';
import { RecipeServiceService } from './recipes/recipe-service.service'
import { ShoppingServiceService } from './shopping-list/shopping-service.service';
import {CommonModule} from '@angular/common';
import { routing } from './app.routes';
@NgModule({
  declarations: [
    AppComponent,
    HeaderComponent,
    RecipesComponent,
    RecipesListComponent,
    RecipesItemComponent,
    RecipesDetailComponent,
    UserdropdownDirectiveDirective,
    ShoppingListComponent
  ],
  imports: [
    BrowserModule,
    CommonModule,
    routing
    
  ],
  providers: [RecipeServiceService, ShoppingServiceService],
  bootstrap: [AppComponent]
})
export class AppModule { }

**app.router.ts** file is 
import { RouterModule } from "@angular/router"
import { Routes } from "@angular/router";
import { provideRoutes } from "@angular/router";
import { RecipesComponent } from "./recipes/recipes.component";
import { ShoppingListComponent } from "./shopping-list/shopping-list.component";

export const APP_ROUTES: Routes = [

    //provideRoutes([
        {path: '', redirectTo: '/recipes', pathMatch: 'full' },
        { path: 'recipes', component:RecipesComponent },
        { path: 'shopping-list', component: ShoppingListComponent }

    //])

];
export const APP_ROUTES_PROVIDERS=[
    provideRoutes(APP_ROUTES)
];

export const routing = RouterModule.forRoot(APP_ROUTES_PROVIDERS);

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
