### ISSUE TITLE
add i18n-id & keep i18n attributs on development mode

### ISSUE THREAD

**Issue by elvisbegovic** [angular/angular#21852]
## I'm submitting a...
<pre><code>[ x ] Feature request</code></pre>

## Current 
`i18n `attributs are always removed from templates and we have path in xmb file to retrace where i18n attribut is used but we have not id  in DOM when visiting app 

## Expected 
Keep `i18n  `attributs when app is not on `production `mode + add `i18n-id="897897789678"`.
![image](https://user-images.githubusercontent.com/2789203/35506928-56762a20-04eb-11e8-95b7-8a06f4c4bbde.png)

## What is the motivation / use case for changing the behavior?
I think on developement mode we can kepp i18n on our html template because: 
1. we can select i18n attribut with CSS to let traductors know what is translatable/missing
2. If we have an more attribut added like `i18n-id="897897789678"` we could listen onclick on each these attributs and open modal to translate text directly/instantly while visiting webapp. We already have meaning&description but that's not enough (we have problems to translate our app french-german)  this will avoid us maintain our "xmb->excel file" tool and avoid share xls file to traductor while he can just visit webapp and translate in place, and with id it is easy to find traduction in compiler output file messages.xmb
3. Angular create so many insignifiants attributs on production so why not theses for useful usecase only on developement mode. 😀

## Environment
all

## Others
see https://github.com/angular/angular/issues/11042
see https://github.com/angular/angular/issues/20055

**Comment by ocombe** [comment]
I agree that it would be useful to keep this in development.
The reason why it is not kept right now is that we don't want anyone to be able to read the content of meaning & description which may contain private data

**Comment by istiti** [comment]
In addition of keeping i18n tags : 
Actually `messages.xmb` give us info to retrieve component in `<source>` tag but we can't  do the opposite : from html DOM retrieve `<msg id="8909043068192495111">`

If we have this info in DOM in dev mode as said like `<span _i18n="8909043068192495111">Montants</span>` , we could have many opportunities/ideas for i18n especially for translators even let us know it is translated or not.

If we can't have both and need choose:  I prefer i18n tag with id as value this will gaurantee hide private data. 

What you think @ocombe

**Comment by ocombe** [comment]
Good idea, I'll see what is possible but it shouldn't be hard to add the generated ID here
Keep in mind that this is a low priority though

**Comment by kasperstorgaard** [comment]
Any developments on this one? I have almost exact use case, and am wondering if I will have to fork the compiler to make something like this work for us.

**Comment by petebacondarwin** [comment]
Your feature request seems reasonable... although it would not be enough IMO since this would require the translator to step through every part of the app in order to see all the potential translations.
Be aware also that after v9 developers will also be able to create messages in code too using `$localize` tags. So these will not be available to the translated via browsing the pages of the app.

**Comment by elvisbegovic** [comment]
thank you @petebacondarwin 
I think your comment is justified mainly wiht ivys' `$localize` functionality.
