### ISSUE TITLE
Binding Problem in Select box 

### ISSUE THREAD

**Issue by akshacker** [angular/angular#21855]
```
import { IPost } from './../help';
import { map } from 'rxjs/operator/map';
import { Component, OnInit, OnChanges, SimpleChanges } from '@angular/core';
import { IHelp, Base, ICity } from '../help';
import { DataService } from '../data.service';
import {Http, Response} from '@angular/http';
import {Observable} from 'rxjs/Observable';
import { bindCallback } from 'rxjs/observable/bindCallback';
import { resolve } from 'url';


@Component({
  selector: 'app-table',
  templateUrl: './Table.component.html',
  styleUrls: ['./Table.component.css'],
  providers: [DataService],
})
export class TableComponent implements OnInit {
  public Country= [];
  public City= [];
  public Cities= [];
  public State= [];
  public Langauge= [];
  public PostType= [];
  public Source= [];
  public Category= [];
  public Posts= [];
  _Post: any;
  CountryName: string;
  CityName: string;
  StateName: string;
  LanguageName: string;
  PostTypeName: string;
  SourceName: string;
  CategoryName: string;
  StartDate: Date;
  EndDate: Date;
  store = new Map<string, string>();
  url: any;
  ngOnInit() {
  }

  onChangeState(value) {
  if (this.store.has('Country'))
  {
    this.store.delete('Country');
  }
  if (this.store.has('State'))
  {
    this.store.delete('State');
  }
  this.store.set('State', value);
  this.StateName = value;
   console.log('hiii');
  }
 onChangecity(value) {
  if (this.store.has('State'))
  {
    this.store.delete('State');
  }
  if (this.store.has('City'))
  {
    this.store.delete('City');
  }
  this.store.set('City', value);
  this.CityName = value;
 }
 onChangeCountry(value) {
  if (this.store.has('Country'))
  {
    this.store.delete('Country');
  }
  this.store.set('Country', value);
  this.CountryName = value;
 }
 onChangeCategory(value) {
  if (this.store.has('Category'))
  {
    this.store.delete('Category');
  }
  this.store.set('Category', value);
  this.CategoryName = value;
 }
 onChangeLanguage(value) {
  if (this.store.has('Language'))
  {
    this.store.delete('Language');
  }
  this.store.set('Language', value);
  this.LanguageName = value;
 }
 onChangePostType(value) {
  if (this.store.has('PostType'))
  {
    this.store.delete('PostType');
  }
  this.store.set('PostType', value);
  this.PostTypeName = value;
 }
 onChangeSource(value) {
  if (this.store.has('Source'))
  {
    this.store.delete('Source');
  }
  this.store.set('Source', value);
  this.SourceName = value;
 }
 onChangeStartDate(value) {
  if (this.store.has('StartDate'))
  {
    this.store.delete('StartDate');
  }
  this.store.set('StartDate', value);
  this.StartDate = value;
 }

 onChangeEndDate(value) {
  if (this.store.has('EndDate'))
  {
    this.store.delete('EndDate');
  }
  this.store.set('EndDate', value);
  this.EndDate = value;
 }

  constructor(private http: Http) {
  this.http.get('http://localhost:8082/lang').subscribe(data => { this._Post = data.json();
  for (let entry of this._Post['Post']) {
   // tslint:disable-next-line:prefer-const
   // tslint:disable-next-line:max-line-length
   let obj = new Base(entry._fields[1], entry._fields[0] , entry._fields[2] , entry._fields[4], entry._fields[5], entry._fields[6], entry._fields[7], entry._fields[8]);
   this.Posts.push(obj);
  }
  for (let entry of this._Post['Country']) {
    let obj = new Base(entry._fields[0] , entry._fields[1]);
    this.Country.push(obj);
}
console.log('Loading State');
for (let entry of this._Post['state']) {
    let obj = new Base(entry._fields[0] , entry._fields[1]);
    this.State.push(obj);
}
//    console.log('Loading City');
//    for (let entry of this._Data['city']) {
//         let obj = new Base(entry._fields[0] , entry._fields[1]);
//         this.City.push(obj);
//    }
console.log('Loading Category');
for (let entry of this._Post['Category']) {
    let obj = new Base(entry._fields[0] , entry._fields[1]);
    this.Category.push(obj);
}
console.log('Loading Language');
for (let entry of this._Post['Language']) {
    let obj = new Base(entry._fields[0]);
    this.Langauge.push(obj);
}
console.log('Loading Post Type');
for (let entry of this._Post['PostType']) {
    let obj = new Base(entry._fields[0][0]);
    this.PostType.push(obj);
}
console.log('Loading Source');
for (let entry of this._Post['source']) {
    let obj = new Base(entry._fields[0]);
    this.Source.push(obj);
}

 });
}



  onclick()
  {
    this.url =  this.getData();
    this.http.get(this.url).subscribe( data => { this._Post = data.json();
    console.log('before length' + this.Posts.length);
    this.Posts.length = 0;
    console.log('after length' + this.Posts.length);
     for (let entry of this._Post['data']) {
       // tslint:disable-next-line:prefer-const
       // tslint:disable-next-line:max-line-length

       console.log('url' +  entry);
       // tslint:disable-next-line:max-line-length
       let obj = new Base(entry._fields[1], entry._fields[0] , entry._fields[2] , entry._fields[4], entry._fields[5], entry._fields[6], entry._fields[7], entry._fields[8]);
       this.Posts.push(obj);
      }
      console.log('i m there');
 }).unsubscribe();
  }
     getData() {
        let url = 'http://localhost:8082/v1.0/post?';
        if ( this.store.has('State'))
        {
           url = url + 'State=' + this.store.get('State') + '&';
           console.log(url);
        }
        if ( this.store.has('Country'))
        {
           url = url + 'Country=' + this.store.get('Country') + '&';
           console.log(url);
        }
        if ( this.store.has('City'))
        {
           url = url + 'City=' + this.store.get('City') + '&';
           console.log(url);
        }
        if ( this.store.has('Language'))
        {
           url = url + 'language=' + this.store.get('Language') + '&';
           console.log(url);
        }
       if ( this.store.has('PostType'))
        {
           url = url + 'type=' + this.store.get('PostType') + '&';
           console.log(url);
        }
        if ( this.store.has('Category'))
        {
           url = url + 'category=' + this.store.get('Category') + '&'; 
           console.log(url);
        }
        if ( this.store.has('Source'))
        {
           url = url + 'source=' + this.store.get('Source') + '&';
           console.log(url);
        }
        if ( this.store.has('StartDate'))
        {
           url = url + 'date1=' + this.store.get('StartDate') + '&';
           console.log(url);
        }
        if ( this.store.has('EndDate'))
        {
           url = url + 'date2=' + this.store.get('EndDate') + '&';
           console.log(url);
        }
    return url;
    }

}

```            
   <table width="200" border="3" class="table">
    <tbody>
        <tr style="height: 70px;">
            <th scope="col" style="width: 80px;font-size: larger;font-family: inherit;">SL.No</th>
            <th scope="col" style="width: 65%;size: 100px;font-size: larger;font-family: inherit;">TITLE

                <div class="btn-group" role="group">

                    <input type="date" name="dateofbirth" id="StartDate" #StartDate (blur)="onChangeStartDate(StartDate.value)">
                    <br>

                    <input type="date" name="dateofbirth" id="EndDate" #EndDate (blur)="onChangeEndDate(EndDate.value)">
                </div>
                <div class="btn-group" role="group">

                    <select style="background-color: #ff7919;width:100px;height:80px" [(ngModel)]="Source" #source (change)="onChangeSource(source.value)">
                        <option value="" hidden>SOURCE</option>
                        <option *ngFor="let Sources of Source" [value]="Sources.name">
                            {{Sources.name}}
                        </option>
                    </select>
                </div>

                <div class="btn-group-vertical" role="group" aria-label="Vertical button group">
                    <div class="btn-group" role="group">
                        <select style="background-color: #ff7919;border-radius: 24px;height: 36px;width: 130px;" [(ngModel)]="Langauge[0]" #Lang (change)="onChangeLanguage(Lang.value)">
                            <option value="" hidden selected>LANGUAGE</option>
                            <option *ngFor="let arr of Langauge" [value]="arr.name">
                                {{arr.name}}
                            </option>

                        </select>
                    </div>
                    <div class="btn-group" role="group">
                        <select style="background-color: #ff7919;border-radius: 24px;height: 36px;width: 130px;" [(ngModel)]="Country" #country (change)="onChangeCountry(country.value)">
                            <option value="" hidden>COUNTRY</option>
                            <option *ngFor="let arr of Country" [value]="arr.name">
                                {{arr.name}}
                            </option>
                        </select>
                    </div>
                </div>

                <div class="btn-group-vertical" role="group" aria-label="Vertical button group">
                    <div class="btn-group" role="group">
                        <select style="background-color: #ff7919;border-radius: 24px;height: 36px;width: 130px;" [(ngModel)]="State" #Statevalue (change)="onChangeState(Statevalue.value)">
                            <option value="" hidden>STATE</option>
                            <option *ngFor="let arr of State" [value]="arr.name">
                                {{arr.name}}
                            </option>
                        </select>
                    </div>
                    <div class="btn-group" role="group">

                        <select style="background-color: #ff7919;border-radius: 24px;height: 36px;width: 130px;" [(ngModel)]="Cities" #city (change)="onChangeCity(city.value)">
                            <option value="" hidden>City</option>
                            <option *ngFor="let arr of Cities" [value]="arr.name">
                                {{arr.name}}
                            </option>
                        </select>

                    </div>
                </div>

                <div class="btn-group-vertical" role="group" aria-label="Vertical button group">
                    <div class="btn-group" role="group">
                        <button id="btnDropOne1" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color:#ff7919;border-radius: 24px;">NOTIFICATION</button>

                    </div>
                    <div class="btn-group" role="group">
                        <button id="btnDropOne1" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color:#ff7919;border-radius: 24px;">UNPUBLISHED</button>

                    </div>
                </div>
                <div class="btn-group-vertical" role="group" aria-label="Vertical button group">
                    <div class="btn-group" role="group">
                        <select style="background-color: #ff7919;border-radius: 24px;height: 36px;width: 130px;" [(ngModel)]="PostType" #Post (change)="onChangePostType(Post.value)">
                            <option value="" hidden>POST TYPE</option>
                            <option *ngFor="let arr of PostType" [value]="arr.name">
                                {{arr.name}}
                            </option>
                        </select>
                    </div>
                    

                    <div class="btn-group" role="group">
                        <select style="background-color: #ff7919;border-radius: 24px;height: 36px;width: 130px;" [(ngModel)]="Category" #Cat (change)="onChangeCategory(Cat.value)">

                            <option [value]="undefined" disabled selected="selected"> Category</option>
                            <option *ngFor="let arr of Category" [value]="arr.name">
                                {{arr.name}}
                            </option>
                        </select>
                    </div>

                </div>

                <div class="btn-group-vertical" role="group" aria-label="Vertical button group">
                    <button id="btnDropOne1" type="button" class="btn btn-default" style="background-color: #ff7919;border-radius: 24px;height: 36px;width: -webkit-fill-available;" (click)="onclick()">GO</button>

                    <button id="btnDropOne1" type="button" class="btn btn-default" style="background-color: #ff7919;border-radius: 24px;height: 36px;width: -webkit-fill-available;" (click)="onReset()">RESET</button>

                </div>
            </th>
            <th scope="col" style="width: 200px;font-size: larger;font-family: inherit;">THUMBNAIL</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </tbody>

    <tr *ngFor="let arr of Posts;index as i">
        <td>
            <div style="margin-top: 60px;"> {{i}}</div>
        </td>
        <td>
            <small>@ {{arr.publishtime | date:'shortTime'}} from {{arr.source_type}} {{arr.source_name}} {{arr.language}} published in {{arr.category}}</small>
            <div style="margin-top: 40px;"> {{arr.name}} </div>
            <div class="btn-group-vertical" role="group" aria-label="Vertical button group" style=" width: 18%; text-align: -webkit-center;margin-left: 80%;">
                
                <mat-checkbox checked="true">{{arr.category}}</mat-checkbox>
      
                
                
            </div>
            
        </td>
        <td>
            <div class="col-sm-6 col-md-3">
                <a href="#">
      
                    <img src="{{arr.image}}" style="width: 200px;">
                </a>
            </div>
        </td>
        <td> </td>
        <td>&nbsp;</td>
      </tr>

</table>

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
