### ISSUE TITLE
iterator of an element in an array executes 4 times when *ngFor based on that array 

### ISSUE THREAD

**Issue by krave1986** [angular/angular#21864]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

It's a simple case with only one app.component .
In the template, I am trying to repeat div based on
`<div *ngFor="let row of dataSet"></div>`

While in app.component.ts, I have an array - dataSet which includes one object element.
I have implemented @@iterator of that object.

As far as I know, `let row of dataSet` sholudn't have invoked iterator of the nested object in an array.

## Expected behavior

The iterator not being invoked.

## Minimal reproduction of the problem with instructions

Here is my demo. I installed latest angular version on my machine.
https://stackblitz.com/edit/angular-ft7xwn
Please bring on the console to see 'hit' logged four times.

## What is the motivation / use case for changing the behavior?

I implement the object's @@iterator because I'd like to use nested *ngFor to run some logic.

## Environment

<pre><code>
Angular version: 5.2.2

Browser:
- [x] Chrome (desktop) version 63
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v7.2.0  
- Platform:  Mac

Others:

</code></pre>

**Comment by vicb** [comment]
you can add a `debugger;` statement in place of the `console.log()` and inspect the call stack when the debugger breaks.

The reason is that [`areIterablesEqual()`](https://github.com/angular/angular/blob/dd48df105b69f1bb4814ec7065f2b85e234ad50f/packages/core/src/change_detection/change_detection_util.ts#L85) gets called because your are in debug mode.

**Comment by krave1986** [comment]
Thank you.  `ng serve --open --environment=prod` solve the problem.
