### ISSUE TITLE
paramsInheritanceStrategy = 'always' doesn't flatted data params in resolvers

### ISSUE THREAD

**Issue by jasonaden** [angular/angular#21878]
Essentially, if we have 2 route resolvers in a parent/child relationship, we'd expect to be able to see the parent resolver's output in the child resolver's route data. Unfortunately, the parameter inheritance code (this bit: https://github.com/angular/angular/blob/master/packages/router/src/router_state.ts#L193) actually ends up executing *after* the resolvers already run.

Reproduction needed. Reported internally.

**Comment by KatzeKahn** [comment]
I agree, the parent resolver data is not yet available in a depending child resolver. The `route.data` is null on execution. :(

**Comment by ukrukarg** [comment]
Might be related to https://github.com/angular/angular/issues/25140?

**Comment by atscott** [comment]
I think the code pointer is outdated and it should point to https://github.com/angular/angular/blob/6eb868b63a5b0ae877346b48ac659f35e6e7af8b/packages/router/src/operators/resolve_data.ts#L47-L52 (notice that `resolveNode` happens before `inheritedParamsDataResolve` are copied to `futureARS`)

**Comment by petebacondarwin** [comment]
Closing due to lack of reproduction.
