### ISSUE TITLE
Ignore whitespace in test comparisons

### ISSUE THREAD

**Issue by kegluneq** [angular/angular#2187]
In particular, IntelliJ wants to add newlines to some of the expected JSON output which is causing some tests to fail when running locally.

cc @vicb

**Comment by vicb** [comment]
thanks

**Comment by mhevery** [comment]
@kegluneq / @vicb Who is this issue against? https://github.com/vsavkin/guinness? or Angular.

**Comment by vicb** [comment]
Probably angular.
As this is related to JSON comparison, could we compare the objects rather than the serialized output ? @kegluneq

**Comment by kegluneq** [comment]
Right, there are some tests in test/transform that are too strict about whitespace comparison. I wouldn't prioritize these too highly -- this should only affect the small number of people who are modifying transformer tests.

**Comment by kegluneq** [comment]
This is now handled by using `package:dart_style` to format code before comparisons.
