### ISSUE TITLE
Automate PR workflow via github robot

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21884]
The robot could help us manage the PR workflow by watching activity on PRs and moving PRs into various milestones depending on the activity observed on the PR. The proposed milestones are captured on the following diagram as nodes (ovals) and actions that cause transitions are the annotated edges in the graph.

I used color coding to capture who's responsible for the next state transition.

![angular pr lifecycle 1](https://user-images.githubusercontent.com/216296/35609419-14001fc0-0612-11e8-8d31-675d331f8ffc.png)

There might be some exceptional state transitions are missing in this diagram, we should try to capture and document as many as we can.

@ocombe can you take a stab at this? thanks!

**Comment by ocombe** [comment]
Do you have a higher resolution for the image? I cannot read the small text

**Comment by IgorMinar** [comment]
oops.. sorry. I'll upload a better quality picture this evening.

**Comment by IgorMinar** [comment]
updated. @ocombe please let me know if you have questions.

@vicb suggested that we actually use some open source state machine library to implement this. he said that he would reach out to you to discuss this in detail.

One more thing: several of us discussed today that using "PR assignee" could be used to indicate who should take the next action. So for example any time we are in the "green" state, the issue is assigned to the original reviewer, but if we are in the blue state, the PR is assigned to the PR author. This would allow the team members to just watch the issues and PR assigned to them and follow up on those, simplifying the whole process of figuring out what issues to follow up on.

**Comment by StephenFluin** [comment]
Can we change "Dead" to "Pending Close"?

**Comment by manughub** [comment]
Can we add a timeout between "work in progress" ands "inactive" states ?

**Comment by ocombe** [comment]
New graph: https://docs.google.com/drawings/d/1PStuvppgz5ksyEtPtxjMzKe6uirQUImmqbLEbX9kWr8/edit?ts=5bbf14f6

**Comment by manekinekko** [comment]
@ocombe the doc seems to be private. is that intentional?

**Comment by ocombe** [comment]
Not really, I've changed the access rights, but I'm just adding the link here so that we don't loose it, I don't think it has much value to anyone else :)

**Comment by davegaeddert** [comment]
I would actually be interested in taking a look at the doc if nobody is opposed? I run [pullapprove](https://www.pullapprove.com/), and am always curious to see what more complex projects are thinking around PR workflows. I can request access through Drive, just thought I would check here first.

**Comment by ocombe** [comment]
@manughub can you make the doc public please?

**Comment by davegaeddert** [comment]
Any word on this? Still looks to be private.

**Comment by manughub** [comment]
@davegaeddert here you go. I had to move the doc to a different domain to share it.
http://bit.ly/AngularPRProcess

**Comment by davegaeddert** [comment]
Awesome, thanks @manughub!

**Comment by AndrewKushnir** [comment]
This feature will be taken care of in the dev-infra repository (there is a proposed project), so I'm closing this ticket.
