### ISSUE TITLE
Not able to see the unit testing page in angular.io website

### ISSUE THREAD

**Issue by abhishekstl** [angular/angular#21887]
The url https://angular.io/guide/testing is not accessible. Is it down for maintainance?

**Comment by trotyl** [comment]
It's under rewrite at #20697

**Comment by gkalpak** [comment]
The old page should still be visible (although @trotyl is right that a re-write is about to be merged).
Sounds like this issue is a duplicate of #21889.

**Comment by trotyl** [comment]
Ah, just found I misunderstood the question...
