### ISSUE TITLE
ngFor and reactive forms in firefox not working es expected

### ISSUE THREAD

**Issue by MasseElch** [angular/angular#21885]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When using a custom made component for a radio-group in an *ngFor loop in firefox the radio button do not work.

## Expected behavior
Clicking the radio-button will mark them as selected.

## Minimal reproduction of the problem with instructions
See the following plunker.
http://plnkr.co/edit/JiIAQvXMH3D3xpYm759W

Does work in Chromium but not in Firefox (all Versions)

## Environment

<pre><code>
Angular version: 5.2.2 (tested on several other versions, same problem)

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox all versions
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.0
- Platform:  Mac

Others:
 none
</code></pre>

**Comment by trotyl** [comment]
![image](https://user-images.githubusercontent.com/6059170/35556615-a3d73104-05dd-11e8-9531-99b9aaa7c181.png)

It's by design, you're creating a new array with completely different elements each time, so all DOM nodes would be destroyed and recreated. Seems to be a bug (or special feature) of Chrome to keep status even after DOM not being the same.

**Comment by MasseElch** [comment]
@trotyl Thank you for the hint. 

In my real example i am creating the materials-array with the reduce()-function.

````
this.configurationService.data.materials.reduce((radios, material) => {
            return radios.concat({
                label: this.productVariantTranslatorService.translate(material),
                value: material.id
            });
        }, []);
```

Since reduce takes an new empty array as starting value, it is the same problem, am i right?

**Comment by trotyl** [comment]
If you're creating new object with same content, [`trackBy`](https://angular.io/api/common/NgForOf#ngForTrackBy) is designed for that case.

**Comment by MasseElch** [comment]
@trotyl I learned a lot. Thank you very very much. Closing the issue.
