### ISSUE TITLE
Tour of Heroes - Step 6 page won't load

### ISSUE THREAD

**Issue by cemer1215** [angular/angular#21899]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When attempting to complete step 6. Services for Tour of Heroes, the page advises the request failed. 

'REQUEST FOR DOCUMENT FAILED.'

## Expected behavior

Cannot see steps to complete this portion of the tutorial 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/21889
