### ISSUE TITLE
Possible bug with ng-template clicks not firing

### ISSUE THREAD

**Issue by merrickfox** [angular/angular#21893]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

This is difficult to explain in words so there is a Plunkr below... Bear with me.
I'm experiencing from very odd behaviour with a highly reusable component architecture I've been experimenting with. The idea is having standardised components with slots for different functionality depending on context, so I've been using `ng-template` and `ngTemplateOutlet` etc. When pressing buttons that are in the `ng-template` "slots", which are wrapped in `*ngFor` and the functionality inside the slots communicates with it's host component via eventEmitter sometimes the `(click)` handler is not firing and it's seemingly random, but it seems isolated to when there is an `[ngclass]` in the mix.

## Expected behavior

The buttons should fire every time and trigger whatever functionality is connected to the button

## Minimal reproduction of the problem with instructions

I've created the simplest version of this I can, each button should toggle the class of the element in it's host component, click on the buttons in a random order (eg try clicking 1, 2, 1 and then finally 2, for me 2 no longer works at this point) you will see that sometimes the click fires and sometimes it does not depending on the current state of all expanded elements. **However** if on line 39 you replace the `[ngclass]` with an `ngIf` like so `<div *ngIf="open">` the functionality works perfectly albeit without the classes to style it.
https://plnkr.co/edit/BUPALYkBN5Zot2RWx4rW?p=preview

## What is the motivation / use case for changing the behavior?

in my full version I wanted an animation like an accordian type functionality

## Environment

<pre><code>
Angular version: 5.2.2

Browser:
- [63.0.3239.132] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by skreborn** [comment]
This isn't an Angular bug. Your open class is simply wrong. It hides the element using `opacity: 0` and `height: 0`, but the content overflows and won't let you click through. Either [use `display: none`](https://plnkr.co/edit/xeuKdlgEkUuN3LuyTyBU?p=preview) or [add `overflow: hidden` to the `opacity`/`height` combination](https://plnkr.co/edit/4xQiIL8ZHVcPHbzkEKcy?p=preview).

---

In any case, this isn't a bug report, but a support request, and should therefore be closed.
