### ISSUE TITLE
Broken demo on Dynamic Component Loader documentation article

### ISSUE THREAD

**Issue by dankellett** [angular/angular#21903]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The "live demo" and downloadable demo linked on the documentation page titled "[Dynamic Component Loader](https://angular.io/guide/dynamic-component-loader)" does not function, nor does the downloadable demo.

## Expected behavior

The demo works

## Minimal reproduction of the problem with instructions

Follow the "live example" link that shows at the top or bottom of the article [here](https://angular.io/guide/dynamic-component-loader) or go straight to live example link [here](https://angular.io/generated/live-examples/dynamic-component-loader/stackblitz.html)

## What is the motivation / use case for changing the behavior?

Demo is broken

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
What do you mean by "broken"? See https://github.com/angular/angular/issues/17158

**Comment by dankellett** [comment]
Different symptom - Logs are showing "ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked." However, it does seem to be adblocker related. This is an issue since Angular is used to build many enterprise applications and many end users will have adblockers installed as a company infosec policy.

Should I just close this issue out since it seems related to the issue you linked?

**Comment by mlc-mlapis** [comment]
@dankellett ... it is not related to any adblocker.

**Comment by dankellett** [comment]
I see what you mean. The app runs with Adblocker disabled but it is still producing the console error with adblockers disabled. This suggests that these are likely two different issues.

So the symptom is solely that this functionality in the demo doesn't work when adblocker is running, which seems to be tracked in #17158.

**Comment by mlc-mlapis** [comment]
@dankellett ... this is the only change that is enough to solve the problem in thit case ... `ngOnInit()` instead of `ngAfterViewInit()` is the most simple solution ... but be careful - not in every similar case ...
```
export class AdBannerComponent implements OnDestroy, OnInit {
   ...
   constructor(private componentFactoryResolver: ComponentFactoryResolver) { }

   ngOnInit() {
      this.loadComponent();
      this.getAds();
  }
  ...
}
```

**Comment by richadr** [comment]
For people coming from Google, https://blog.angularindepth.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4 helped me understand what's going on.  `ngOnInit` fixed it.

P.S.: while you're at it... `currentAddIndex` should become `currentAdIndex` (not just in the example code, also referenced in docs), `app-add-banner` should be `appAdBanner` and there appears to be an unused `subscription` field in `AdBannerComponent` that can be removed.

**Comment by Yerkon** [comment]
Can you try this solution: #22020?

**Comment by kapunahelewong** [comment]
Hey, thanks for finding this @dankellett. I learned something new! 👍
