### ISSUE TITLE
Styles CSS / Libraries JS of backend and frontend

### ISSUE THREAD

**Issue by kamalkech** [angular/angular#21901]
Angular CLI: 1.6.5
Node: 8.9.1
OS: darwin x64
Angular : 5

Hello every 

I try to develop an application with two modules importants, backend and frontend.
For each module i have list of files css and js libraries, and i won't to load all in one time so ".angular-cli.json" is not a good way, for each list files css i put theme in each file css of component module like : 

- Load files css of frontend in : frontend.component.css
- Load files css of backend in : backend.component.css

but not working good when try to navigate between routes of modules, angular still load the list files css of module first visited and it crashed, i try with `encapsulation: ViewEncapsulation.None` but not working.

any idea plz ?

captures : 
 
![1](https://user-images.githubusercontent.com/1313428/35578933-500361ec-05dd-11e8-98f6-5407c4d644af.png)
![2](https://user-images.githubusercontent.com/1313428/35578934-502d626c-05dd-11e8-911d-9231d4d7da07.png)
![3](https://user-images.githubusercontent.com/1313428/35578935-5052fb4e-05dd-11e8-8a8a-5392a47cebd8.png)

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
