### ISSUE TITLE
Service Worker Extendablility

### ISSUE THREAD

**Issue by adamzr** [angular/angular#21918]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

Currently, Angular's Service Worker support generates a service worker as part of the build process to cache the application for offline use. I'd like to use the service worker to do additional work, like receive push notifications. The generated service worker should be extendable. I should be able to specify scripts that the service worker should import in the config file. Or, I should be able to declare functions to handle service worker events, like notification events, in my code that will get included in the generated service worker script.

**Comment by alxhub** [comment]
Hello, @adamzr,

`@angular/service-worker` has native support for push notifications (via the `SwPush` service, which clearly needs documentation). However, the inclusion of user-provided code in the SW itself is something which is explicitly not supported (for now), but we may consider such a feature in the future.

**Comment by adamzr** [comment]
Thanks! Documentation on SwPush would be great!
