### ISSUE TITLE
Github robot should not allow PRs with pending reviews to be merged

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21919]
In the past we accidentally merged a few PRs with pending reviews. This can lead to changes that haven't been sufficiently reviewed to be merged.

I filed an issue with pullapprove to handle this: https://github.com/pullapprove/support/issues/117

If that doesn't get much traction, we should consider implementing this in our github robot.

**Comment by ocombe** [comment]
Done! Requested reviews are now required
