### ISSUE TITLE
angular is too slow Violation

### ISSUE THREAD

**Issue by neutron92** [angular/angular#21910]
```
zone.js:1547 [Violation] 'mousedown' handler took 778ms
zone.js:1547 [Violation] 'click' handler took 247ms
zone.js:1547 [Violation] 'mousedown' handler took 738ms
home:1 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
zone.js:1547 [Violation] 'click' handler took 234ms
zone.js:1547 [Violation] 'mousedown' handler took 714ms
home:1 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
zone.js:1547 [Violation] 'click' handler took 223ms
```

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[  x ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

Browser:
- [ x ] Chrome (desktop) version XX
- [ x ] Chrome (Android) version XX
- [ x ] Chrome (iOS) version XX
- [ x ] Firefox version XX
- [ x ] Safari (desktop) version XX
- [ x ] Safari (iOS) version XX
- [ x ] IE version XX
- [ x ] Edge version XX

**Comment by mlc-mlapis** [comment]
@neutron92 ... what is the sense of it? Without code it is about nothing.

**Comment by neutron92** [comment]
@mlc-mlapis it is in bootsrap modal all inputs are slow and i have these errors

**Comment by neutron92** [comment]
1-
![screenshot at 2018-01-30 20-00-38](https://user-images.githubusercontent.com/6135555/35585590-a754c47a-05f8-11e8-9853-3ebba0b44049.png)
2- 

![screenshot at 2018-01-30 20-02-21](https://user-images.githubusercontent.com/6135555/35585602-ac96cf0a-05f8-11e8-819f-3cda516d3d1a.png)

**Comment by mlc-mlapis** [comment]
@neutron92 ... ok, probably yes, you have a problem somewhere but still as you certainly know very well the first and just the principal step is to be able to reproduce the problem. Do you think that your images above can help anybody? If you mean it seriously ... prepare a simple Stackblitz demo of the problem ... http://stackblitz.com

**Comment by mhevery** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by dpac4u** [comment]
I am also facing the same issue? Did you find any solution for this. We are using web components.

**Comment by Nagaraj104065** [comment]
me too.

**Comment by michaelbats** [comment]
Getting a ton of these as well

**Comment by ags504** [comment]
DOM is getting stuck and mouse events also not working on lazy load of data. 
But the DOM is not getting stuck on firefox, wherein Chrome UI is not responding.
