### ISSUE TITLE
Cheatsheet documentation documents the wrong end of the stick

### ISSUE THREAD

**Issue by eepstein** [angular/angular#21913]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

See #21843 

I don't think the issue I was raising was understood.

The wording of the existing documentation appears to be about the "Injector", but it is documenting the "@Injectable" metadata annotation.

The comment from @jotatoledo is about how the parts function - and in that he is absolutely correct. Unfortunately, that doesn't line up with the existing documentation.

Simple put the existing documentation is flat out wrong. It reads that adding an "@Injectable" "Declares that a class has dependencies that should be injected into the constructor when the dependency injector is creating an instance of this class." That is false. It is the other way around. It declares that the class can be used by an Injector and be injected into other classes during those classes construction.

**Comment by trotyl** [comment]
The current description is indeed correct, a class with `@Injectable()` only indicate that it could have dependency, not relates to how it would be used in other parts. So, if a service does not have any dependency, `@Injectable()` can be removed without causing any issue:

```
// No need to add @Injectable()
class MyServiceWithoutDep {
  method() { }
}

// Must add @Injectable()
@Injectable()
class MyServiceWithDep {
  constructor(private dep: Dep) {}
  method() { }
}

@NgModule({
  providers: [MyServiceWithoutDep, MyServiceWithDep]
})
class MyModule { }
```

But always having a `@Injectable()` is recommended for consistency.

**Comment by kapunahelewong** [comment]
@jasonaden would you take a look at this when you get a chance to confirm accuracy? I'm happy to submit the PR if we should make these changes.

**Comment by jotatoledo** [comment]
IMO is fine

**Comment by jenniferfell** [comment]
@jbogarthyde : Hi. When you get a chance, would you look into this issue and the related (closed) issue #22803, especially in the context of recent glossary and DI updates. Please re-triage as appropriate. Thanks!

**Comment by jenniferfell** [comment]
docsarea=cheatsheet
docsarea=dependencyinjection

**Comment by trotyl** [comment]
https://github.com/angular/angular/pull/27480 should have made this clear.

**Comment by jbogarthyde** [comment]
Resolved by doc changes to cheat-sheet and `@Injectable` API page
