### ISSUE TITLE
Helpful patterns for creating successful forms

### ISSUE THREAD

**Issue by iankpconcentricsky** [angular/angular#21920]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Developer experience lacks documentation for approaching design of handling form controls across reusable sub-components.  It could be done with injectable <pre><code>private container: ControlContainer</code></pre> and later <pre><code>@Input() name;
this.control = this.container.control.get(name) as FormControl;</code></pre> although this is ENTIRELY undocumented and ControlContainer's extremely limited explanation states<pre>Only used by the forms module.</pre>  This could imply it isn't designed or intended to inherit from.  There are other methodologies dispersed/employed, such as Kara Erickson's talk at AngularConnect 2017.  

## Expected behavior

This common use-case should be documented, discoverable, and canonical.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-toxicable-template-control-container-bx3iye?file=app%2Fapp.component.ts

## What is the motivation / use case for changing the behavior?

Improve developer experience.

## Environment

<pre><code>
Angular version: Documentation as of 5.2.2

**Comment by iankpconcentricsky** [comment]
@robwormald How are we supposed to handle situations such as these? I'm at a bit of a loss and I wish it was covered?  https://stackblitz.com/edit/angular-toxicable-template-control-container-b7cwsz?file=app/app.component.ts

Rather than have one giant monolithic template, some (entirely standard) form controls may be within smaller, re-usable sub-components. How do I bind the reactive form controls through without necessitating a template-monolith. 

Worth noting, I'm not crafting new input components like material design might. I'm simply trying to organize reusable components.  A "submission page" might be a giant form composed of multiple reusable "sections", for example.

**Comment by kapunahelewong** [comment]
After quick conversation with @Kara, I'm adding that this one needs engineering input as there is some discussion that needs to take place that will determine how and where we document this and what needs to go along with it.

**Comment by jenniferfell** [comment]
@brandonroberts FYI in context of reactive forms rewrite you're doing and backlog. Thanks.

**Comment by dylhunn** [comment]
The docs have changed a lot since this issue was filed, and we're unlikely to overhaul them soon.
