### ISSUE TITLE
add or hide some field with conditions within a template

### ISSUE THREAD

**Issue by soowonshin** [angular/angular#21928]
I have an issue.
Any information or any clue will be great help.

We use a template.
But we need to change column according to search condition.
Such as department.
The result should be different with search condition.
And as I said we use a template to show result.

Do you think it is possible to add or hide some field with conditions.
We need any help badly.

Please help me out.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
