### ISSUE TITLE
There is NumberSymbol.TimeSeparator but lack of NumberSymbol.DateSeparator

### ISSUE THREAD

**Issue by luboid** [angular/angular#21929]
## I'm submitting a... #21851

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

there is not current behavior

## Expected behavior

DateSeparator new property of NumberSymbol

## Minimal reproduction of the problem with instructions

**@angular\common\src\i18n\locale_data_api.d.ts**
<pre><code>
/**
 * Number symbol that can be used to replace placeholders in number patterns.
 * The placeholders are based on english values:
 *
 * | Name                   | Example for en-US | Meaning                                     |
 * |------------------------|-------------------|---------------------------------------------|
 * | decimal                | 2,345`.`67        | decimal separator                           |
 * | group                  | 2`,`345.67        | grouping separator, typically for thousands |
 * | plusSign               | `+`23             | the plus sign used with numbers             |
 * | minusSign              | `-`23             | the minus sign used with numbers            |
 * | percentSign            | 23.4`%`           | the percent sign (out of 100)               |
 * | perMille               | 234`‰`            | the permille sign (out of 1000)             |
 * | exponential            | 1.2`E`3           | used in computers for 1.2×10³.              |
 * | superscriptingExponent | 1.2`×`103         | human-readable format of exponential        |
 * | infinity               | `∞`               | used in +∞ and -∞.                          |
 * | nan                    | `NaN`             | "not a number".                             |
 * | timeSeparator          | 10`:`52           | symbol used between time units              |
 * | currencyDecimal        | $2,345`.`67       | decimal separator, fallback to "decimal"    |
 * | currencyGroup          | $2`,`345.67       | grouping separator, fallback to "group"     |
 *
 */
export declare enum NumberSymbol {
    Decimal = 0,
    Group = 1,
    List = 2,
    PercentSign = 3,
    PlusSign = 4,
    MinusSign = 5,
    Exponential = 6,
    SuperscriptingExponent = 7,
    PerMille = 8,
    Infinity = 9,
    NaN = 10,
    TimeSeparator = 11,
    CurrencyDecimal = 12,
    CurrencyGroup = 13,
}
</code></pre>

## What is the motivation / use case for changing the behavior?

When build components you need to know environment 

## Environment

<pre><code>
Angular version: 5.2.2, 6.0.0-beta.1

Browser: 
- [X] Chrome (desktop) version - any
- [X] Chrome (Android) version - any
- [X] Chrome (iOS) version - any
- [X] Firefox version - any
- [X] Safari (desktop) version - any
- [X] Safari (iOS) version - any
- [X] IE version - any
- [X] Edge version - any
 
For Tooling issues:
- Node version: any  
- Platform:  any

Others:

This is not a runtime problem
</code></pre>

**Comment by ocombe** [comment]
Hello,

sorry but I don't understand what you're looking for? What is this date separator? I don't see anything like that in CLDR data.

**Comment by luboid** [comment]
Hello,
Date separator is alike Time separator it  divides parts of date if you have next:

12/11/2018 12:45

/ is Date separator
:  is Time separator 

I don't understand how can exists TimeSeparator (:) in CLDR, but there will not be  Date separator. In German this is dot while in America this is / and if I create input component for dates I need to allow some characters and to disallow others

**Comment by ocombe** [comment]
Ok I understand better what you're looking for. I'm afraid that there is nothing like this in CLDR right now.
The closest thing that you can use are date formats, for example in german: https://github.com/angular/angular/blob/master/packages/common/locales/de.ts#L60
the 4 formats are will be represented as `['dd.MM.yy', 'dd.MM.y', 'd. MMMM y', 'EEEE, d. MMMM y']`

You can use the function `getLocaleDateFormats` for that: https://angular.io/api/common/getLocaleDateFormat

Chose the `FormatWidth` that you want, for example `FormatWidth.Medium`, and you'll get the medium format for the locale. If you want to use the current locale of the application, you can use the token `LOCALE_ID`: https://angular.io/api/core/LOCALE_ID

Then it's just a matter of replacing the `dd`, `MM` and `y` with the values that you want.

**Comment by luboid** [comment]
:)
