### ISSUE TITLE
Eagerly loaded routed feature module introduces undesired routes

### ISSUE THREAD

**Issue by RGTGT** [angular/angular#21934]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Eagerly loaded routed-feature module adds its routes to the root application.

## Expected behavior

Routes of routed-feature module should not be added to root routes either loaded lazyly or eagerly.

## Minimal reproduction of the problem with instructions
see sample at: [https://github.com/RGTGT/samble-routes-with-feature-modules](https://github.com/RGTGT/samble-routes-with-feature-modules)
checkout
ng serve
goto http://localhost:4200/
observe the links at the top of the page are all available although the last one shouldn't exist.

## What is the motivation / use case for changing the behavior?
Began to do a feature routed lazily loaded module. Then I needed one of its component at the application level.
So I imported it on the AppModule to eagerly load it, consciously loosing the lazy loading advantage. Although, as a side effect, routes of the feature module were loaded directly at the application level.

I consider that loading eagerly or lazilly a routed feature module shouldn't imply functionnal change on the application.

## Environment

<pre>ng version<code>

Angular CLI: 1.6.6
Node: 8.9.4
OS: win32 x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.6
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.6
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.10.0

**Comment by Yerkon** [comment]
https://github.com/RGTGT/samble-routes-with-feature-modules/blob/master/src/app/app.module.ts#L22
Hi, @RGTGT. App-routing.module should be imported last. Order is matter.

**Comment by RGTGT** [comment]
@Yerkon 
Importing the AppRoutingModule last makes feature routing takes precedence.

When importing AppRoutingModule last, navigating to / directly redirects toward the undesirable /list route. The issue remains the same.

**Comment by Yerkon** [comment]
> Eagerly loaded routed-feature module adds its routes to the root application.


I think, it's not a bug, it's correct behavior. You have two routes with the same `path: ''` which imports in root module.

**Comment by RGTGT** [comment]
I get what's happening. Although if we refer to the [module types guide](https://angular.io/guide/module-types). Eagerly loaded routed feature modules are mentionned:

>  An eager loaded routed feature module must be imported by another module so that the compiler learns about its components.

If not a bug I think this part of documentation is a bit blur / misleading.

**Comment by Yerkon** [comment]
An eager loaded routed feature module **must be imported by another module** so that the compiler learns about its components.

If it's not imported then, component/pipes/directive .... not found error will thow, because they are not lazy-loaded 😄

**Comment by RGTGT** [comment]
You are totally right, I get this part. 

The thing that bothers me is that transforming a lazy loaded routed feature to a eagerly loaded one (by importing it in another module just like the doc says and like the sample application is doing) 
is not trivial and can cause undesired effects (import of the module routes on the root app context) that are difficult to detect.

I can agree on the fact that it may not be a bug. If so the documentation should maybe caution about the specifics on an eagerly loaded routed feature module IMO.

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Just taking a quick look at it, would this change if you made the eagerly loaded module a dependency of your app routing module instead of the app module directly? I don't know if it would help, but in a way you've got the `RouterModule.forRoot` and `RouterModule.forChild` both being imported at the `AppModule` level. When really one should be a child of the other.
