### ISSUE TITLE
Script blocking app for some seconds ?

### ISSUE THREAD

**Issue by bhawin-bigstep** [angular/angular#21931]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have an angular which i am loading via an iframe . The angular app is hanging the whole web browser for about 3 seconds while loading .

I am loading this iframe on window.onload
I am only getting this issue in chrome.

What have i debugged:

1. I have seen the sources tab in devtools which show that there is one file which has no domain is causing problem which loading .
2. I opened this file and the code seems like this 
```
(function(define, require, requireNative, requireAsync, exports, console, privates, apiBridge, bindingUtil, getInternalApi,$Array, $Function, $JSON, $Object, $RegExp, $String, $Error) {'use strict';// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Custom binding for the app API.

var appNatives = requireNative('app');
var process = requireNative('process');
var extensionId = process.GetExtensionId();
var logActivity = requireNative('activityLogger');

function wrapForLogging(fun) {
  if (!extensionId)
    return fun;  // nothing interesting to log without an extension

  return function() {
    // TODO(ataly): We need to make sure we use the right prototype for
    // fun.apply. Array slice can either be rewritten or similarly defined.
    logActivity.LogAPICall(extensionId, "app." + fun.name,
        $Array.slice(arguments));
    return $Function.apply(fun, this, arguments);
  };
}

// This becomes chrome.app
var app = {
  getIsInstalled: wrapForLogging(appNatives.GetIsInstalled),
  getDetails: wrapForLogging(appNatives.GetDetails),
  runningState: wrapForLogging(appNatives.GetRunningState)
};

// Tricky; "getIsInstalled" is actually exposed as the getter "isInstalled",
// but we don't have a way to express this in the schema JSON (nor is it
// worth it for this one special case).
//
// So, define it manually, and let the getIsInstalled function act as its
// documentation.
var isInstalled = wrapForLogging(appNatives.GetIsInstalled);
$Object.defineProperty(
    app, 'isInstalled',
    {
      __proto__: null,
      configurable: true,
      enumerable: true,
      get: function() { return isInstalled(); },
    });

// Called by app_bindings.cc.
function onInstallStateResponse(state, callbackId) {
  var callback = callbacks[callbackId];
  delete callbacks[callbackId];
  if (typeof callback == 'function') {
    try {
      callback(state);
    } catch (e) {
      console.error('Exception in chrome.app.installState response handler: ' +
                    e.stack);
    }
  }
}

// TODO(kalman): move this stuff to its own custom bindings.
var callbacks = { __proto__: null };
var nextCallbackId = 1;

function getInstallState(callback) {
  var callbackId = nextCallbackId++;
  callbacks[callbackId] = callback;
  appNatives.GetInstallState(callbackId);
}

$Object.defineProperty(
    app, 'installState',
    {
      __proto__: null,
      configurable: true,
      enumerable: true,
      value: wrapForLogging(getInstallState),
      writable: true,
    });

exports.$set('binding', app);
exports.$set('onInstallStateResponse', onInstallStateResponse);

})
```

## Environment

<pre><code>
Angular version: 
ng -v
Angular CLI: 1.6.6
Node: 9.4.0
OS: linux x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router
... tsc-wrapped

@angular/cdk: 2.0.0-beta.8
@angular/cli: 1.6.6
@angular/material: 2.0.0-beta.8
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.6
@schematics/angular: 0.1.17
typescript: 2.2.2
webpack: 3.10.0

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  
node -v = v9.4.0
npm -v = 5.6.0

Others:

</code></pre>

**Comment by bhawin-bigstep** [comment]
Why @trotyl  , you can check this at devaddons1.socialengineaddons.com/mobiledemodevelopment/

The page hangs when iframe loads and you can check that its not hanging in firefox.

**Comment by trotyl** [comment]
You're responsible for providing the **minimal** reproduction in bug report, rather than asking other to debug your app.

**Comment by bhawin-bigstep** [comment]
@trotyl   I have updated the bug report , can you please check now whether the issue is valid

**Comment by trotyl** [comment]
@bhawin-bigstep To create a minimal repro, either [Plunker](http://plnkr.co/), [StackBlitz](https://stackblitz.com/) or GitHub repo newly created [Angular CLI](https://stackblitz.com/) project would be fine.

We have no idea what your environment looks like or what you did in your project, the description here is not helpful for anyone trying to help.

**Comment by bhawin-bigstep** [comment]
Hi @trotyl  , I have added the problem reproduction steps as well.
Can you please see now .

**Comment by trotyl** [comment]
That's obviously not a **minimal** repro.

**Comment by bhawin-bigstep** [comment]
Hi @trotyl  , I have created a Stackblitz for this issue.
https://stackblitz.com/edit/angular-o7npf7?file=app%2Fapp.module.ts
Try to scroll the editor while the app is loading . you will see the scroll not working for 3-4 seconds when the view renders.

**Comment by trotyl** [comment]
The online demo will compile TypeScript code and Angular templates on the fly, it's not for production or performance test.

In real application, AOT compilation will be used and production mode will be turn on. More information can be found at https://angular.io/guide/deployment and https://angular.io/guide/aot-compiler .

I thought you were going to report some mysterious network request?

**Comment by bhawin-bigstep** [comment]
`ng build --env=prod `  compile with aot by default.

I am still getting the same blockage on my server.

@trotyl  , Can you tell me what can be the reasons please .
Or the path where should i do the research to get it rectifed

**Comment by trotyl** [comment]
![snip20180131_10](https://user-images.githubusercontent.com/6059170/35624208-469e96fc-06c9-11e8-84bd-eb20cb416a3b.png)

Are you sure it's an Angular app?

**Comment by bhawin-bigstep** [comment]
![data](https://user-images.githubusercontent.com/18306587/35624580-6b1cc102-06b5-11e8-8b31-0e5a39f6f93b.png)

The Blue Chat APP at the right corner is the angular app.
I am loading it via iframe
@trotyl

**Comment by trotyl** [comment]
![image](https://user-images.githubusercontent.com/6059170/35625040-d65c8d6a-06cb-11e8-81c1-1462b3dd7440.png)
![image](https://user-images.githubusercontent.com/6059170/35625066-ebce7974-06cb-11e8-889b-3c4cbd6c2fc6.png)

The app is running in JIT mode.

**Comment by trotyl** [comment]
> ng build --env=prod compile with aot by default.

It's not, `--target=production` will turn on AOT, `--env` is just setting which `environment.ts` to use.

**Comment by bhawin-bigstep** [comment]
@trotyl  , It been an amazing conversation with you. 
All my queries have been resolved.
Thanks a lot .
