### ISSUE TITLE
module import with custom providers only select the last one

### ISSUE THREAD

**Issue by valentinoNguyen** [angular/angular#21930]
## Module import with custom providers only run the last one

I got a problem when trying to register the implementation of a service via ModuleWithProviders, it means there are 2 modules with its own implementation, register on another module for a certain interface service. Please check the blow sample for more information

### Module 1
<pre>
<code>
@NgModule({
   ...
   imports: [
       MyShareModule
   ]
})
export class Module1{
    public static forRoot(): ModuleWithProviders {        
        return {
            ngModule: Module1,
            providers: [
                {
                    provide: ISearchService,
                    useFactory: () => { 
                        return new SearchService1()
                    }
                }
            ],
        }
    }
}
</code>
</pre>

### Module 2
<pre>
<code>
@NgModule({
   ...
   imports: [
       MyShareModule
   ]
})
export class Module2{
    public static forRoot(): ModuleWithProviders {        
        return {
            ngModule: Module2,
            providers: [
                {
                    provide: ISearchService,
                    useFactory: () => { 
                        return new SearchService2()
                    }
                }
            ],
        }
    }
}
</code>
</pre>

### AppModule
<pre>
<code>
@NgModule({
   ...
   imports: [
       MyShareModule,
       Module1.forRoot(),
       Module2.forRoot()
   ]
})
</code>
</pre>

MyShareModule has all functionality use in both Module1 and Module2, it is only different on the service API end-point. That's why I create an interface ISearchService, and the implementation is provided by the Module1 and Module2. So everywhere inside MyShareModule, if it inject the ISearchService, it should get the implementation base on it is inside Module1 or Module2.

Module1 and Module2 is lazy load module via Route.

## Current behavior
It's using the implementation from Module2 because Module2 is put below Module1 in the imports from AppModule even I'm on the Module1 route. And if I move Module2 to above, it will use the implement of Module1.

So it only registers the last module from imports. 

## Expected behavior
It should use the correct implementation of the correct module.

## Environment

<pre><code>
    "@angular/animations": "5.0.3",
    "@angular/common": "5.0.3",
    "@angular/compiler": "5.0.3",
    "@angular/core": "5.0.3",
    "@angular/forms": "5.0.3",
    "@angular/http": "5.0.3",
    "@angular/platform-browser": "5.0.3",
    "@angular/platform-browser-dynamic": "5.0.3",
    "@angular/router": "5.0.3",
</code></pre>

**Comment by tiep-phan** [comment]
This is expected behaviour, and because you're using lazy loading, you can create `correct implementation of the correct module` by puting provider to NgModule level, not root level (it'll create new injector tree for each lazy module)

https://stackblitz.com/edit/angular-cvps48

**Comment by valentinoNguyen** [comment]
@tiep-phan : Thank for your response. Although I got it works by using providers inside component. But your idea gives me idea helps me alot !
