### ISSUE TITLE
ngClass remove the class only if the object's value is null

### ISSUE THREAD

**Issue by tahuba** [angular/angular#21932]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have an icon component:
<pre><code>@Component({
  selector: 'icon',
  styleUrls: ['./icon.component.css'],
  template: `
    < span 
      [ngClass]="{'large': large, 'small': small}"
      class="mdi {{'mdi-'+name}}"
    >< /span>
  `
})
export class IconComponent  {
  @Input() name: string;
  @Input() large: boolean = false;
  @Input() small: boolean = false;
}
</code></pre>

And the usage of it:

<pre><code>< icon [name]="show ? 'eye' : 'eye-off'"
       [small]="true"
       [large]="false">< /icon>
</code></pre>

After the initial render the icon component's < span> element will have only one class, the 'small'. It's okay. But after it I modify the `name` input's value, the < span> element will have the class 'large' and 'small' both. 

## Expected behavior
After the modification of the `name` input's value, the < span> element will have only the class 'small'.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-vsffrd?file=app%2Fapp.component.html

Just click to the 'switch the icon' button. After it, the icon (< span> element) will be large, not small.

## What is the motivation / use case for changing the behavior?
The documentation says, that the ngClass directive works with 'false' object value, but I experienced, it works only with value 'null'. If I modify the large input's value to 'null', it will work fine, but with 'false', it does not work.

This works only:
<pre><code>< icon [name]="show ? 'eye' : 'eye-off'"
       [small]="true"
       [large]="null">< /icon>
</code></pre>

## Environment

<pre><code>
Angular version: >= 4.0.0-beta.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v9.4.0
- Platform:  Linux

Others:
-
</code></pre>

**Comment by tahuba** [comment]
I think, this modification breaks the default behaviour:
https://github.com/angular/angular/commit/2e3ac70e0af46640c2606c5e49bf695745db2278#diff-e1329c3d217826f2cddc8d77b4374ad8L132

**Comment by ericmartinezr** [comment]
I think you have a misunderstanding about how ngClass works. Here's an explanation (quite old though) https://github.com/angular/angular/issues/5763#issuecomment-166114033. Basically you're saying: "I want this class to be added when it's false", and in your case it's always false, therefore it will always be there.

See this [example](https://stackblitz.com/edit/angular-9a4jrd?file=icon/icon.component.ts) where I simply pass a toggling variable for the "large" property (the same thing you're doing with the "show" property).

**Comment by trotyl** [comment]
Could be a valid bug, simpler repro: https://stackblitz.com/edit/angular-xybndc?file=app/app.component.html

**Comment by pkozlowski-opensource** [comment]
See #15396.

**Comment by Yerkon** [comment]
thanks, @pkozlowski-opensource. But we are not first and not last who will face with this problem. It's look like a bug, if not browser console should show descriptive error maybe? Because it's not obvious

**Comment by pkozlowski-opensource** [comment]
> But we are not first and not last who will face with this problem. It's look like a bug, if not browser console should show descriptive error maybe? Because it's not obvious

Totally. We should look into this one to see if we can handle this case correctly and add an error message if not.

**Comment by pkozlowski-opensource** [comment]
#21937 should take care of this specific case.

**Comment by trotyl** [comment]
@pkozlowski-opensource Thanks for the link, but given that (static) interpolation in `class` is already covered is [test case](https://github.com/angular/angular/blob/407b5cf4082b5c5be2b2e4a81127ef83e2bbc75e/packages/common/test/directives/ng_class_spec.ts#L280), it may not be a good design to allow interpolation but provide no support for changing value, so I thought it to be a bug.

**Comment by Yerkon** [comment]
> Thanks for the link, but given that (static) interpolation in class is already covered is test case

@trotyl, right. but in @pkozlowski-opensource case interpolation in class dynamic. this case not covered before

**Comment by lf-novelt** [comment]
Hello, it seems like it happens again in angular 9.0.0 using `[class]="null"`
