### ISSUE TITLE
Relative Urls for templates not working correctly

### ISSUE THREAD

**Issue by choeller** [angular/angular#2194]
Assuming we have a project structure as below:

```
project
│   app.js
└───components
    ├───my-component
    │   │   my-component.js
    │   │   my-component.html
...
```

When referencing my-component.html from my-component.js we currently have to pass the complete path from `project` folder to `templateUrl`:

```javascript
@Component({
    selector: 'my-component'
})
@View({
    templateUrl: 'components/my-component/my-component.html'
})
export class MyComponent { }
```
This is not ideal for writing reusable components. 

As far as I understand <a href="https://github.com/angular/angular/blob/2.0.0-alpha.25/modules/angular2/src/core/compiler/component_url_mapper.ts#L11">ComponentUrlMapper#L11</a> always returns `./` no matter what folder the component is located in. This path gets  then appended to `_appUrl` in <a href="https://github.com/angular/angular/blob/2.0.0-alpha.25/modules/angular2/src/core/compiler/compiler.ts#L210-L214">Compiler#L210-L214</a> so the information about the actual location of the component gets lost. 

I think this issue is also related to https://github.com/angular/angular/issues/2175

**Comment by tbosch** [comment]
One idea would be the following:

`@View` does not only take a `templateUrl`, but also a `moduleId`. Many module systems provide these via a special import:

- node.js and requirejs jave the special import `module` which has a `id` property (see [here](https://nodejs.org/api/modules.html#modules_the_module_object) and [here](https://github.com/jrburke/requirejs/wiki/Differences-between-the-simplified-CommonJS-wrapper-and-standard-AMD-define#module))
- traceur has an open issue for supporting something similar ([here](https://github.com/google/traceur-compiler/issues/1328))
- I remember there was a similar thing for systemjs, but could not find it any more. But it should be easy to add it.

For Dart, we could add a method to the `reflector` that would get the fully qualified class name either via mirrors or from the transformer.

**Comment by choeller** [comment]
Oh, I didn't write that in the issues, but I was expecting, that it should be possible to work with relative URLs. For example for the above folder Structure something like this:

```javascript
@Component({
    selector: 'my-component'
})
@View({
    templateUrl: './my-component.html'
})
export class MyComponent { }
```
This would make it easy to write reusable components and does not add any more boilerplate. Or is there anything I didn't consider with this?

**Comment by mhevery** [comment]
Superseded by: #2382, #2384, #2383
