### ISSUE TITLE
Angular Router Prematurely Constructs the DOM during a cancelled refresh

### ISSUE THREAD

**Issue by matsko** [angular/angular#21947]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In #19712 an animation bug surfaces when a route is refreshed and cancelled (by hitting the back button). The animation bug itself is caused due to a race condition which involves having the DOM be constructed with this rapid change.

## Expected behavior
The premature DOM construction shouldn't be kicked off during this refresh/back-button event.

## Minimal reproduction of the problem with instructions
1. `git clone https://github.com/sandangel/angular-bug.git`
2. `yarn`
3. `yarn start`
4. go to the "graph" page and let it load fully
5. hit refresh (browser refresh) and immediately trigger the back button page change
6. inspect the console

## What is the motivation / use case for changing the behavior?
To fully figure out why animations are being buggy with this scenario.

## Environment
Chrome 64 on Mac OSX 10.13.

<pre><code>
Angular version: master

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by atscott** [comment]
I updated the reproduction to v10 and was not able to see any animation bugs. Closing.
https://github.com/atscott/angular21947

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template that include info on how to create a reproduction using our template.
