### ISSUE TITLE
aio: send crash reports to Google Analytics

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#21943]

**Comment by petebacondarwin** [comment]
We can start with a straightforward `window.onerror` handler, which sends (max 150 bytes) to Google Analytics. The stack trace for these error is not available in the handler for some browsers ([as of 2016](https://blog.sentry.io/2016/01/04/client-javascript-reporting-window-onerror#browser-compatibility)).

Going forward we could try hooking into the Angular [`ErrorHandler`](https://angular.io/api/core/ErrorHandler) functionality, which is driven by zone.js and should capture more information.

Looking even further ahead, Google Analytics only allows us to send 150 bytes per message to the server. This is very limiting for useful information, such as stack traces. We could consider an off-the-shelf service (e.g. https://www.bugsnag.com/open-source/) or roll our own (perhaps a FirebaseDB)...

**Comment by IgorMinar** [comment]
I don't think that this is working. I tried to manually cause errors and I don't see any pings to analytics.

I tried using the following:

```
window.eval("(function() { throw new Error('test error'); })()");
```


I also tried to call:

```
window.onerror("test error")
```

this results in analytics ping in the network tab, but I don't see the event in the analytics UI under events.

**Comment by petebacondarwin** [comment]
Are we using the correct GA identifier?

**Comment by petebacondarwin** [comment]
It turns out that Exceptions are not displayed in any of the standard reports and that you have to create a custom report to view them! I nice guy called Ron Whitman created such a report and uploaded it to the GA gallery: https://analytics.google.com/analytics/gallery/#posts/search/%3F_.viewId%3DZ7mmQrXHRMG-Adw4TqA2xQ/

I have now installed this and you can see the exceptions coming in via https://analytics.google.com/analytics/web/?authuser=0#my-reports/7KWdS7sUROuutLPIQDUotw/a8594346w94746691p98770826/%3F_r.tabId%3D3330/

**Comment by petebacondarwin** [comment]
@IgorMinar PTAL

**Comment by petebacondarwin** [comment]
20% of errors are:

```
Error fetching document [object Object] undefined:?:?
```

It seems that exceptions have been increasing towards the end of last month:

<img width="1493" alt="screen shot 2018-03-04 at 09 02 33" src="https://user-images.githubusercontent.com/15655/36943981-de660b26-1f8a-11e8-803b-e3d58eeb327a.png">

**Comment by gkalpak** [comment]
The increased error rate could be me trying out #22483 :grin:
There are a lot of 404s when testing redirections.

But we should fix our [error logging for 404s][1], since we are now [concatenating errors][2] instead of `console.log/error()` them.

[1]: https://github.com/angular/angular/blob/4f609687044a5b7cd15f796bce948e9385b70f7a/aio/src/app/documents/document.service.ts#L93
[2]: https://github.com/angular/angular/blob/4f609687044a5b7cd15f796bce948e9385b70f7a/aio/src/app/shared/logger.service.ts#L17

**Comment by petebacondarwin** [comment]
I have attempted to improve our error handling to improve the reported data: #22713
