### ISSUE TITLE
router typings might be behind in definition

### ISSUE THREAD

**Issue by ORESoftware** [angular/angular#21945]
I see this:

![screenshot 2018-01-31 12 46 20](https://user-images.githubusercontent.com/11139560/35646698-de745830-0684-11e8-98a3-71eaf61660e0.png)

I am pretty certain the url property is already present on `val`, might be a typings issue? dunno

**Comment by adrienboulle** [comment]
https://github.com/angular/angular/blob/master/packages/router/src/events.ts

URL is not present on every event, you have to filter

**Comment by ORESoftware** [comment]
but router.events should be RouterEvent not Event, right?

**Comment by trotyl** [comment]
[`Event`](https://github.com/angular/angular/blob/61abba4bed7f45e6821aeaa7ddb9a05d4b59177a/packages/router/src/events.ts#L393) is the union type for `Router#events`, it's not the ambient DOM one (with the same name), this is correct.

Not every event type being extends the `RouterEvent` which has `url` property, like [`RouteConfigLoadStart `](https://github.com/angular/angular/blob/61abba4bed7f45e6821aeaa7ddb9a05d4b59177a/packages/router/src/events.ts#L287-L292), the error message is clear.

**Comment by ORESoftware** [comment]
alrighty then
