### ISSUE TITLE
Http: should return correct status code / text when errors occur

### ISSUE THREAD

**Issue by cesareian** [angular/angular#21953]
## I'm submitting a...
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see 

## Current behavior
When we do a request to our API and the response is a 404, the statusText is being returned as "OK"

## Expected behavior
When we do a request to our API and the response is a 404, the statusText should be "Bad Request" or something like that

## What is the motivation / use case for changing the behavior?
All responses which are of type "404" are being returned incorrectly and therefore their statusText are not actually reflecting the actual response

## Environment

Angular version: 5.2.2

Browser:
- [ x ] Chrome (desktop) version 63
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by cesareian** [comment]
This issue was already Opened but somehow it was closed without a fix as can be seen in this issue https://github.com/angular/angular/issues/6138

**Comment by alxhub** [comment]
@cesareian please include a reproduction that illustrates the issue.

**Comment by cesareian** [comment]
@alxhub In the link issue, there is one

**Comment by mlc-mlapis** [comment]
@cesareian ... but the problem with 404 is probably related to the fact that `HTML5 Push State` is enabled ... it means `useHash: false` setting ... because as you know, a server returns always `index.html` for any request that doesn't exist on that server ... so in that case it is always ... `status: 200, statusText: "OK", ...`?
```

```
