### ISSUE TITLE
<select> ngModel binding breaks when no <option> with model value

### ISSUE THREAD

**Issue by aidalgol** [angular/angular#21952]
## I'm submitting a...

<pre>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</pre>

## Current behavior

I have a component containing a `<select>` element with `ngModel` bound and the child `<option>` elements passed in via `<ng-content>`.  This component is used in another component with the `<option>` elements generated from an array that is initially empty, and populated after a short delay.  When the list is populated, one of the generated `<option>` elements has the same value as `ngModel`, but the dropdown list selects the first item.  (It does not seem to make a difference whether the array is empty, as long as it does not contain a value matching that of the `ngModel`.)

## Expected behavior

The dropdown selection switches to the item with the value that matches `ngModel`.

## Minimal reproduction of the problem with instructions

This Plunk starts with the model initialised to `"baz"` and the array from which the `<options>` are generated is empty.  The constructor sets timers that make the following changes in sequence.

1. Set the array to a value that contains the item `"baz"`.
2. Set the model to the value `"quux"`.
3. Set the array to a value that does _not_ contain the item `"quux"`.
3. Set the array to a value that contains the item `"quux"`.

https://plnkr.co/edit/aBhtWh?p=preview

## What is the motivation / use case for changing the behavior?

I have a form where the list of choices for a dropdown menu is fetched from a server.

## Environment
<pre>
Angular version: 5.2.0

Browser:
- [X] Chrome (desktop) version 63
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 52
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: N/A 
- Platform: Windows

**Comment by kara** [comment]
This looks like it has the same root problem as https://github.com/angular/angular/issues/13761. The options aren't being registered properly with the select because the select is not the parent element.
