### ISSUE TITLE
@angular/language-service: support for strictNullChecks and ngIf

### ISSUE THREAD

**Issue by dirkluijk** [angular/angular#21954]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When Typescript compiler option `strictNullChecks` is enabled, the @angular/language-service throws errors.

Example: 

![image](https://user-images.githubusercontent.com/2102973/35669869-d1a9169c-0736-11e8-9e3c-fa49452c1836.png)

```typescript
interface Foo {
  bar: string;
}

@Component({
  selector: 'app-foo',
  templateUrl: './foo.component.html'
})
export class FooComponent {
  foo?: Foo;
}
```
Example 1:
```html
<app-foo *ngIf="foo" [bar]="foo.bar"></app-foo>
```
Example 2:
```html
<div *ngIf="foo">{{ foo.bar }}</div>
```

```
Error: ng: The expression might be null
```

## Expected behavior
I expect `*ngIf` to assert the object not to be null, so I can safely use it without any errors.

## Environment
<pre><code>
Angular version: 5.2.2
- Node version: 8.9.1
- Platform:  MacOS
- Typescript 2.6.2
</code></pre>

**Comment by sir-boformer** [comment]
I would consider this as a bug, not a feature request.

The language service is unusable with strictNullChecks enabled.

**Comment by klemenoslaj** [comment]
It's close to be one year already...Is there any update on this bug?
Language service is just useless at the moment with strictNullChecks.

**Comment by thw0rted** [comment]
This hasn't been updated in 3 years.  The language service now complains when I *don't* have strictTemplates turned on, every time I launch VSCode.  I can't possibly be the only person developing Angular in VSCode, who makes use of `ngIf`, right?

**Comment by JoostK** [comment]
With the Ivy language service this issue has been resolved; compiler options such as `strictNullChecks` now work correctly together with `ngIf` narrowing.

@thw0rted if you continue to experience issues with the Ivy language service, could you please open a new issue? I can't deduce from your comment what the problem could be, so diagnosing that requires some more information about your case. Thanks.
