### ISSUE TITLE
Architecture guide references 'app-hero-detail' tag as 'hero-detail'

### ISSUE THREAD

**Issue by wimgoeman** [angular/angular#21955]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The text of the component section of the architecture page refers to the `<hero-detail>` tag whereas it is `<app-hero-detail>` in the example code snippet. 

## Expected behavior

Use `<app-hero-detail>` in the text.

## Minimal reproduction of the problem with instructions
Not applicable

## What is the motivation / use case for changing the behavior?
This is confusing. Not very confusing, but should be fixed nonetheless in my opinion.

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [ x] Chrome (desktop) version XX
- [ x] Chrome (Android) version XX
- [ x] Chrome (iOS) version XX
- [ x] Firefox version XX
- [ x] Safari (desktop) version XX
- [ x] Safari (iOS) version XX
- [ x] IE version XX
- [ x] Edge version XX
 
For Tooling issues:
- Node version: N/A
- Platform:  N/A

Others:
N/A
</code></pre>

**Comment by jenniferfell** [comment]
Closed by https://github.com/angular/angular/pull/21569
