### ISSUE TITLE
ReactiveForms form.value is not behaving consitent

### ISSUE THREAD

**Issue by borriej** [angular/angular#21959]
[x] Bug

Hi,

I think i've found a bug, or a design flaw in my opinion.

When you disable a form i expect the form value to be available, or not available. I dont mind the form value not being availabe, as long as it's consistent through the framework. But at the moment form values are available on disabled Reactive Form's with simple FormControls.. but disabled Reactive Forms with FormArray's turn out to have empty form values. 

I believe this is incorrect because it is behaving inconsistent.

Two examples:

Simple Reactive Form based on a a simple class
```
// class
export class Profile {
  company_address?: string;
  company_city?: string;
  company_country?: string;
  company_name?: string;
  company_postcode?: string;
}
...

  submit(form: FormGroup){

    if(!form.valid){
      return;
    }

    form.disable();

    // the form values are (weirdly) available after disabling the form

    let value = <Profile>form.value;
    console.log(value);

  }
```

Form Array Reactive Form
```
// class
export class Patterns {
  patterns: any[];
}
...
  submit(form: FormGroup): void{
       
    if(!form.valid){
      return;
    }
    form.disable();

    // this returns { patterns: [] } ... which i didn't expect
    // because on the simple reactive forms values were available after disabling
    // so angular should pick one behavior and stick to it
    console.log(form.value)

    // while this returns { patterns: [{foo: bar}, {foo: bar}]
   let value = <Patterns>form.getRawValue();

  }
```

Conclusion: 

> form.value should behave the same over all reactive forms. Or it should always return empty form values, or it should always behave like get raw value.

**Comment by borriej** [comment]
update: I had some subscription still being active on FormGroup's like:

```
  // each pattern has subscriptions
  subscribeChanges(pattern: FormGroup){

    pattern['subFrequency'] = pattern.get('frequency').valueChanges.subscribe(val => {
      this.frequencyChange(val, pattern);
    });
    pattern['subFrequencyType'] = pattern.get('frequencyType').valueChanges.subscribe(val => {
      // revalidate frequency, because of max validation based on Week/Quarter 
      pattern.get('frequency').updateValueAndValidity();
    });
    pattern['subOnDays'] = pattern.get('onDays').valueChanges.subscribe(val => {
      this.onDaysChange(val, pattern);
    });
  }
```

which i needed to unsbuscribe first if the form was valid. Now form.value and form.getRawValue() are both returning the values.

**Comment by kara** [comment]
Sounds like you resolved your issue?  To confirm, when an entire form is disabled the form.value and form.getRawValue() should match.  If you're still seeing weirdness, please feel free to re-open with a minimal repro case on stackblitz (as I'm not able to reproduce using only the snippets provided).
