### ISSUE TITLE
Fields with dot in name cannot be retrieved using form.get()

### ISSUE THREAD

**Issue by timruhle** [angular/angular#21950]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When creating a form field with a . (dot) in the id, it cannot be retrieved.

## Expected behavior
It should allow a field id with any characters in the string

## Minimal reproduction of the problem with instructions
Click the button and look at the console logs. The field without a dot works but the field with a dot doesn't work
https://angular-reactive-forms-issue-aw1vh8.stackblitz.io/

## What is the motivation / use case for changing the behavior?
To stop errors from occuring

## Environment

<pre><code>
Angular version: 5.2.3

Browser:
- [x] Chrome (desktop) version 64
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by mlc-mlapis** [comment]
@timruhle ... but dot is not as any other character ... it has a reserved meaning.

**Comment by timruhle** [comment]
I think that it should be usable and all that should have to change is adding another condition inside of [this if](https://github.com/angular/angular/blob/b4cd27979b1fa12bbd681cafe47d40aa384bf9f0/packages/forms/src/model.ts#L40-L42) to check if that string with the dot exists before making it into an array.


If you want to keep it as a reserved character then some better documentation may be needed for it. All that I can find is [one small sentence](https://angular.io/guide/reactive-forms#inspect-formcontrol-properties) in a 6,500 word page, that doesn't explicitly say it, but it has to be inferred.

**Comment by kara** [comment]
@timruhle  As @mlc-mlapis mentioned, dots are reserved characters in the shorthand syntax. If you want to use dots in your form control names, this is already possible using the array syntax with `get`:

```ts
this.form.get(['myGroup', '2.3']);
```

**Comment by arkauss83** [comment]
Use `this.form.controls['field.name.with.dots']` instead.
