### ISSUE TITLE
Why is my project path being hardcoded in the generated webpack?

### ISSUE THREAD

**Issue by sarbull** [angular/angular#21967]
## I'm submitting a...
<pre><code>
[ ] Regression
[X] Bug report
[ ] Feature request
[X] Documentation issue or request
[X] Support request
</code></pre>

## Current behavior
After i run `ng eject` my current full folder path is being hardcoded in the webpack build
```js
...
    new CircularDependencyPlugin({
      "exclude": /(\\|\/)node_modules(\\|\/)/,
      "failOnError": false,
      "onDetected": false,
      "cwd": "D:\\Users\\sarbull\\projects\\angularApp"
    }),
...
```

## Expected behavior
Should have been a relative path?

## Minimal reproduction of the problem with instructions
Run `ng eject` check the `webpack.config.js` on line 406 in the CircularDependencyPlugin.

## What is the motivation / use case for changing the behavior?
If i move the application in another folder will result in different folder paths.

**Comment by ericmartinezr** [comment]
Hey @sarbull would you mind opening this issue in angular-cli's repo? https://github.com/angular/angular-cli.

This one is for the framework itself 👍

**Comment by sarbull** [comment]
Ok, thanks.
