### ISSUE TITLE
CurrencyPipe adds character 160 after Euro sign instead of a normal space ?

### ISSUE THREAD

**Issue by StefH** [angular/angular#21963]
## I'm submitting a...
<pre><code>
[x] Bug report
</code></pre>

## Current behavior
``` js
const currencyPipe = new CurrencyPipe( 'nl-NL');
const x = this.currencyPipe.transform(43005.60, 'EUR', 'symbol', '1.2-2');
console.log(x);
console.log(`x[0] = ${x[0]} + 0 = ${x.charCodeAt(0)}`);
console.log(`x[1] = ${x[1]} + 1 = ${x.charCodeAt(1)}`);
```
Logging shows
```
€ 43.005,60
x[0] = € + 0 = 8364
x[1] =   + 1 = 160
```

## Expected behavior
Instead of character code 160, I would expect code 32 (normal space), so like this:
```
€ 43.005,60
x[0] = € + 0 = 8364
x[1] =   + 1 = 32
```

## Environment

<pre><code>
Angular version: 5.2.2

Browser:
- [x] Chrome (desktop) version latests
- [x] IE version 11
 
For Tooling issues:
- Node version: v7.10.1
- Platform:  Windows 7

**Comment by skreborn** [comment]
Actually, I think character 160 is a perfect fit here. It's the Unicode no-break space, and should prevent your currency from being broken when there isn't enough space to display it on a single line.

**Comment by ocombe** [comment]
Yes, it's what the CLDR format uses, non breaking space makes sense.

**Comment by vicb** [comment]
Work as intended
