### ISSUE TITLE
Angular 5 prod build not loading defaullt route automatically when open in server ?

### ISSUE THREAD

**Issue by manojcena** [angular/angular#21960]
I developed application using Angular 5 with lazy loading and routing and when i created development build every thing working fine.
Current behavior

but when i generated production build using ng build –prod and placed the dist folder in local host and run it is not loading the default route as i specified in routing. when i type manually a particular route it is loading that route. some times not pointing to the
Expected behavior

when i generated production build and placed in local host and run it should load the default routed in routing.

Environment
Windows 10

Angular version: 5

Browser:
- [ ] Chrome (desktop) Version 63.0.3239.132 (Official Build) (64-bit)

 
For Tooling issues:
- Node version: v8.9.1
- Platform:   Windows 
"dependencies": {
    "@angular/animations": "^5.1.2",
    "@angular/cdk": "^5.0.2",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "^5.0.2",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@types/moment": "^2.13.0",
    "angular-io-datepicker": "^1.3.1",
    "angular-io-overlay": "^1.2.7",
    "angular2-toaster": "^4.0.1",
    "angular5-toaster": "^1.0.2",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "moment": "^2.20.1",
    "ng2-datepicker": "^2.1.6",
    "ng2-toastr": "^4.1.2",
    "ng4-loading-spinner": "^1.1.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.5.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
