### ISSUE TITLE
TitleCasePipe is under-documented

### ISSUE THREAD

**Issue by JocelynDelalande** [angular/angular#21976]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`TitleCasePipe` is not listed in [built-in pipes](https://angular.io/guide/pipes#built-in-pipes) doc section nor provided with code examples as other built-in pipes do.

## Expected behavior

- `TitleCasePipe` listed in pipes page within built-in pipes section
- code examples provided on [TitleCasePipe](https://angular.io/api/common/TitleCasePipe) page

## Environment

<pre><code>
Angular version: 5.2.3
</pre></code>

**Comment by Yerkon** [comment]
[DecimalPipe](https://angular.io/api/common/DecimalPipe) also isn't listed in [built-in-pipes](https://angular.io/guide/pipes#built-in-pipes) doc

**Comment by vicb** [comment]
Feel free to submit a PR if you like !

**Comment by jenniferfell** [comment]
docarea=pipes

**Comment by josephperrott** [comment]
After investigating it further, we will not be adding the `TitleCasePipe` to the listing of the most commonly used pipes.  As mentioned above, the documentation just below this list links to the complete list of built in pipes.  For the list of commonly used pipes to provide value, it cannot grow too large as then the amount of information required to look through detracts from its purpose.
