### ISSUE TITLE
Compilation fails when I try to include external javascript files for angular 5.2.0

### ISSUE THREAD

**Issue by ujjainimukherjee** [angular/angular#21971]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If I try to include an external javascript file inside an angular 5.2.0 project(created using angular cli) and allowJS is set to true, compilation fails

## Expected behavior

If I try to include an external javascript file inside an angular 5.2.0 project(created using angular cli) and allowJS is set to true, it should compile successfully

## Minimal reproduction of the problem with instructions
I have created an angular 5.2.0 project with angular cli and trying to include a 'widget.js' file. The reference to the file has been added to angular-cli.json inside 'scripts' array.
To reproduce - 

1. git clone https://github.com/ujjainimukherjee/ujjainiIncludeJavascript.git
2. cd ujjainiIncludeJavascript
3. npm install
4. ng serve
5. Error appears 
ERROR in error TS5055: Cannot write file '/Users/umukherjee/workspace/_angular_wrapper/ujjainiIncludeJavascript/src/app/widget.js' because it would overwrite input file.
  Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScriptfiles. Learn more at https://aka.ms/tsconfig.

## What is the motivation / use case for changing the behavior?
We are trying to create angular wrappers for existing javascript components written ion vanilla javascript.  We need this for multiple components and this issue is holding us up.

## Environment

<pre><code>
Angular version: 5.2.0
This is still and issue with the latest Angular version

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.4.0
- Platform:  Mac

</code></pre>

**Comment by ericmartinezr** [comment]
Related/dup https://github.com/angular/angular/issues/21080 ?

**Comment by mhevery** [comment]
https://github.com/hansl/angular-cli/commit/a61f5a6041a8499161094a7680fbdb8ec43b17d7
