### ISSUE TITLE
Support emitting all factories to one file instead of separate files

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#21975]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior

The compiler generates a factory file for each module that contains a module or component.

This is problematic for the `ng_module` rule of bazel because bazel requires that the output files be determinable from name of the input file (e.g. `foo.c` -> `foo.o`). Since a `.ts` file might or might not generated `.ngfactory.js`, `'.ngsummary.json` and `.ngsummary.js` files, the `ng_module` rule just assumes that every `.ts` file will produce these files and will generate empty files if the module doesn't end up containing a component or module.

When an application gets large this multiplier of the number of emitted files could cause problems with build systems that have reasonable limits on the number of files they can handle (such as 100k files per action).  The causes the limit to be hit unnecessarily soon.

For bazel it would be better to generate a fixed module that contains all the factories for an `ng_module` rule instead. This would mean that every `ng_module` would imply one three extra files instead of 3 times the number of files.

## Desired behavior

An option that allows `ngc` to emit a single module containing all the factories instead of companion modules.

**Comment by JoostK** [comment]
Closing as obsolete, given that factory files are being phased out altogether.
