### ISSUE TITLE
An AOT Error when use loadchildren with RouterModule

### ISSUE THREAD

**Issue by AaronJin2013** [angular/angular#21981]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I use loadchildren by lazyload or Lambda，JIT is ok，when I try change to AOT，lazyload still works，but Lambda failed.
```
RouterModule.forRoot(
      [
        {
          path: '',
          loadChildren: (): Type<WorkspaceModule> => WorkspaceModule
          // loadChildren: '@ebiz-ng/workspace#WorkspaceModule'
        }
      ],
      { initialNavigation: 'enabled' }
    ),
```
It's Error Info.
```
ERROR in Error during template compile of 'AppModule'
  Function expressions are not supported in decorators in 'ɵ1'
    'ɵ1' contains the error at apps/ebiz-workspace/src/app/app.module.ts(51,25)
      Consider changing the function expression into an exported function.
```

## What is the motivation / use case for changing the behavior?
I want to use ModuleWithProviders and take parameters for it,like this.
```
const params={};
...
RouterModule.forRoot(
      [
        {
          path: '',
          loadChildren: (): Type<WorkspaceModule> => WorkspaceModule.forRoot(params)
        }
      ],
      { initialNavigation: 'enabled' }
    ),
```
And some times ,I want to use a factory function to create a Module import some feature module with Router.

## Environment

<pre><code>
Angular version: 5.1.0

Browser:
- [x] Chrome (desktop) version XX
 
For Tooling issues:
- Node version: 7.8.0
- Platform:  Mac

Others:
-  "@nrwl/nx": "^0.6.19"
</code></pre>

**Comment by trotyl** [comment]
Duplicate of #16923

**Comment by AaronJin2013** [comment]
@trotyl 
thx
