### ISSUE TITLE
Element duping via :enter and :leave animation with *ngIf

### ISSUE THREAD

**Issue by VagrantAI-c** [angular/angular#21987]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When animating an element via :enter and :leave, which has *ngIf in it, angular can dupe it multiple times

## Expected behavior
Maybe drop :leave animation if :enter is triggered?

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/kD4c0oE8ui7xiZ8kR6Q7?p=preview
Moving mouse quickly in and out of gray rectangle causes text label to appear multiple times

## Environment

<pre><code>
Angular version: 5.2.3

Browser:
- Any browser except Safari and Edge
 
For Tooling issues:
- Node version: 8.1.2  
- Platform:  Windows

</code></pre>

**Comment by Saxtonn** [comment]
I have noticed same bug when I was making a button with fa icons. Each click generates new icon.

Simplified (but still giving duplications) html:
```
    <button (click)="changeArrowState()" type="button">
      <i class="fas fa-chevron-down" *ngIf="!arrowUp"></i>
      <i class="fas fa-chevron-up" *ngIf="arrowUp"></i>
    </button>
```

With this code in .ts:
```
  arrowUp: boolean;
  changeArrowState() { this.arrowUp = !this.arrowUp; }
```

I've forked VagrantAI-c's plunker example to show it in action: [http://plnkr.co/edit/HjuFmXcolT2lWkr7gNg0?p=preview](url)

**Comment by VagrantAI-c** [comment]
Can verify that this issue is still reproducable on Angular v.6 https://stackblitz.com/edit/angular-gitter-kyndua

**Comment by nicky-lenaers** [comment]
Can verify that this also happens in Edge (`Microsoft Edge 42.17134.1.0` and `Microsoft EdgeHTML 17.17134`).

**Comment by jelbourn** [comment]
This seems to be fixed in the latest version of Angular:
https://stackblitz.com/edit/angular-ivy-n1hjwl
