### ISSUE TITLE
Docs(aio/generated code examples). Angular Universal: server-side rendering(guide is outdated), broken code examples

### ISSUE THREAD

**Issue by Yerkon** [angular/angular#21983]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

https://angular.io/guide/universal#absolute-http-urls
In this guide: 
1. **Tour of Heroes** project uses new [HttpClientModule](https://angular.io/api/common/http/HttpClientModule), but guide references to deprecated [Http](https://angular.io/api/http/Http) module. 
2. used link [Http](https://angular.io/api/http/Http), which in some case is unnecessary
3. https://angular.io/guide/universal#universal-typescript-configuration

> The module property must be commonjs which can be **require()'d** into our server application.
 Typo mistake? 

4. ~~Guide is outdated or written incorrectly~~. Exceptions happens when running scripts from npm 
I have downloaded final code example of **Universal**. It doesn't work. Script error. 
    *   Mising `main.server.ts` in src folder:
`export { AppServerModule } from './app/app.server.module';`

## Downloaded code example:
![Missing main.server.ts](https://user-images.githubusercontent.com/4002847/36027941-6f6d4d6c-0dc7-11e8-8c14-90b154d0369a.png)
Aio folder => problem with generating zips:  
`"generate-zips": "node ./tools/example-zipper/generateZips"` 
Need to fix code where called: https://github.com/angular/angular/blob/0b1f5d21270063b2019b11a9494397916d3977d6/aio/tools/example-zipper/exampleZipper.js#L58-L61

Regex matches these and returned `main.ts` which breaks code examples by replacing them to `main.ts`: 
```
src/main-specs.ts
src/main-specs.ts
src/main.1b.ts
src/main.2.ts
src/main.0.ts
src/main.3.ts
src/main-final.ts
src/main-final.ts
src/main-specs.ts
src/main.server.ts
```
When code examples zipped. Code examples with more than one `main.ts` overrides each other when extracted to folder. And in final code there are only one `main.ts`. In universal guide should be `main.ts` and `main.server.ts
`  
 *  Need to reinstall @nguniversal dependencies maybe to last version
       *   Local dependencies with local Angular-CLI doesn't properly installs. 
Throws error:
`Error: Cannot find module '@angular-devkit/core'`
Working version **package.json**:
```
{
  "name": "angular.io-example",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server",
    "serve:ssr": "node dist/server.js",
    "build:client-and-server-bundles": "ng build --prod && ng build --prod --app 1 --output-hashing=false",
    "webpack:server": "webpack --config webpack.server.config.js --progress --colors"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~5.0.0",
    "@angular/common": "~5.0.0",
    "@angular/compiler": "~5.0.0",
    "@angular/compiler-cli": "~5.0.0",
    "@angular/core": "~5.0.0",
    "@angular/forms": "~5.0.0",
    "@angular/http": "~5.0.0",
    "@angular/platform-browser": "~5.0.0",
    "@angular/platform-browser-dynamic": "~5.0.0",
    "@angular/platform-server": "^5.2.4",
    "@angular/router": "~5.0.0",
    "@angular/upgrade": "~5.0.0",
    "@nguniversal/express-engine": "^5.0.0-beta.5",
    "@nguniversal/module-map-ngfactory-loader": "^5.0.0-beta.5",
    "angular-in-memory-web-api": "~0.5.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.0",
    "ts-loader": "^3.5.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.6.5",
    "@types/jasmine": "~2.8.0",
    "@types/jasminewd2": "^2.0.3",
    "@types/node": "^6.0.45",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.3",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.2",
    "lodash": "^4.16.2",
    "phantomjs-prebuilt": "^2.1.7",
    "protractor": "~5.1.0",
    "ts-node": "^3.3.0",
    "tslint": "^3.15.1",
    "typescript": "2.4.2"
  }
}

```

## Expected behavior

In this guide need to update reference from [Http](https://angular.io/api/http/Http) module to [HttpClientModule](https://angular.io/api/common/http/HttpClientModule) and remove unnecessary link.
Update this guide to actual. Sample code and guide is differ.

**Comment by Yerkon** [comment]
@Foxandxss, @alxhub can you checkout exampleZipper.js => `_renameFile()` method?

**Comment by Yerkon** [comment]
@gkalpak, I updated issue description, can you please look at 4 position (bug in exampleZipper.js)?

**Comment by gkalpak** [comment]
I think most issues have been addressed. One thing that seems to still be a problem is that the npm scripts are invalid (e.g. refer to inexistent `build/`serve` configurations :confused:):

```json
"start:fr": "ng serve --configuration=fr",
"build:fr": "ng build --configuration=production-fr",
```

cc @brandonroberts

**Comment by brandonroberts** [comment]
@gkalpak this I don't see how those configurations pertain to this issue since its about server-side rendering and not i18n

**Comment by gkalpak** [comment]
@brandonroberts, I haven't looked into what is going on under the hood, but the `package.json` in the [universal guide zip][1] (which contains the full example), contains the following scripts:

```json
"scripts": {
  ...
  "start:fr": "ng serve --configuration=fr",
  "build:fr": "ng build --configuration=production-fr",
  "extract": "ng xi18n --output-path=locale",
  "build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server",
  "serve:ssr": "node dist/server.js",
  "build:client-and-server-bundles": "ng build --prod && ng run angular.io-example:server",
  "webpack:server": "webpack --config webpack.server.config.js --progress --colors"
},
```

Are you saying that some these scripts are not relevant to the guide and should be ignored?
(If that is the case, why include them in `scripts` in the first place?)

[1]: https://next.angular.io/generated/zips/universal/universal.zip

**Comment by brandonroberts** [comment]
Correct, those `scripts` shouldn't be there in the first place since. They aren't included in the example zipper configuration for universal, so it looks like theirs an issue there.

**Comment by jenniferfell** [comment]
@brandonroberts @gkalpak Hi. Thanks for exploring this. So is the summary that we need to rezip the universal example? That's it?

**Comment by brandonroberts** [comment]
@jfell we need to fix an issue with scripts being put in the `package.json` file that don't belong with this example.

**Comment by brandonroberts** [comment]
@Yerkon the issue with the missing files in the example and zip file has already been fixed

**Comment by brandonroberts** [comment]
Closing as issues have been resolved.
