### ISSUE TITLE
QueryList initialized properties regression

### ISSUE THREAD

**Issue by emilio-martinez** [angular/angular#21980]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I believe I've found a regression issue with `QueryList`, possibly caused by this commit: https://github.com/angular/angular/commit/e54474215629aa6a0e0497fe61bfc896cea532c9#diff-a85dbe0991a7577ea24b49374e9ae90b.

I stumbled upon this in an isolated test, i.e., I'm just testing the class logic, not rendering the component. The component has a property decorated with `@ViewChildren` and has other logic that depends of the `QueryList` length. So for testing purposes, I "manually" instantiate a `QueryList` because, of course, it would be automatically populated when outside of Angular's purview. This is where the issue comes in:

Previously (Angular 5.1.3, in my case), `queryListInstance.length` used to have an initial value of `0` because it was a getter for the `_result` array length. Upon upgrading to Angular 5.2.3, it's now `undefined`. Now to actually have it populated, the use `reset()` is required:

```ts
const ql = new QueryList();
console.log(ql.length); // => undefined
ql.reset([]);
console.log(ql.length); // => 0
```
I've only been impacted by this in isolated tests. `ViewChildren`'s logic, however, through it's use of `QueryList`'s `reset()` makes the change imperceptible when the component is rendered.

## Expected behavior
```ts
const ql = new QueryList();
console.log(ql.length); // => 0, without the need to call reset()
```

## Minimal reproduction of the problem with instructions
The below examples show how `QueryList` behavior changed when using `new QueryList()`. Also showcased, `QueryLists` via `@ViewChildren` haven't changed *in practice*; however, in Angular 5.2.3, the length must be getting initialized via calling `reset()` behind the scenes.

With Angular 5.1.3: https://stackblitz.com/edit/angular-akgclx
With Angular 5.2.3: https://stackblitz.com/edit/angular-tcnwtn

## What is the motivation / use case for changing the behavior?
Regression

## Environment

<pre><code>
Angular version: 5.2.3

</code></pre>

**Comment by emilio-martinez** [comment]
Added PR.

**Comment by mhevery** [comment]
https://github.com/angular/angular/pull/21982
