### ISSUE TITLE
Add location sync code for hash-based navigation from AngularJS

### ISSUE THREAD

**Issue by jasonaden** [angular/angular#21995]
AnguarJS applications using hash-based URL navigation can encounter a problem after #21728 which added a value to `history.state`. In fact, AngularJS applications using hash-based URL navigation will encounter this problem any time something exists in `history.state`.

It turns out the browser publishes a `popstate` event when the hash on the URL changes. So that's how the Angular router was getting notified of URL changes caused by the AngularJS router when using hash-based URL navigation. Apps didn't need the "upgrade" code because of this.

The change applied in #21728 gives the option to pass a "state" to the history API calls for Angular's Location service. This is something AngularJS had, but was never implemented in Angular.

The router used these new APIs to store it's `navigationId` in the history API which allows us to sync the two routers much better. However, there was a side effect in AngularJS which is if it sees the history API had been used, it assumes you want to update location through the history API rather than location.hash or location.url (both of which will trigger the `popstate` event Angular's router hooks into). If you use the history API directly, a `popstate` isn't published and therefore we needed to add the sync code to keep the two routers in sync (this is similar code anyone using HTML5 URLs would already have done). That code looks slightly different to manage hash-based URLs, and we will need to add this solution to the `@angular/router/upgrade` package for other projects to take advantage of.

**Comment by jpzwarte** [comment]
@jasonaden is this related perhaps to #23573?

**Comment by vincentjames501** [comment]
+1. This would be great to add to the `@angular/router/upgrade` package. Right now if I try that using hash based routing in my AngularJS/Angular hybrid application it blows up. I just ran into this issue today while upgrading to Angular 6.

**Comment by jasonaden** [comment]
Fixed with #28609.
