### ISSUE TITLE
compiler-cli 5.2.3 - wrong unmet peer dependency for typescript 

### ISSUE THREAD

**Issue by cvgaviao** [angular/angular#21997]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I've updated to angular 5.2.3 also updated typescript to 2.6.2 and I'm getting warning related to unmet peer dependency 

> warning " > @angular/compiler-cli@5.2.3" has unmet peer dependency "typescript@>=2.4.2 <2.7".
> warning "@angular/compiler-cli > tsickle@0.26.0" has unmet peer dependency "typescript@>=2.4.2 <2.7".
> warning " > tslint@5.9.1" has unmet peer dependency "typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev".
> warning "tslint > tsutils@2.20.0" has unmet peer dependency "typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev".

## Expected behavior
since I've installed typescript 2.6.2, I should not receive this warnings

## Minimal reproduction of the problem with instructions

Install angular 2.5.3 and then typescript 2.6.2

## Environment

<pre><code>
Angular version: 5.2.3
</code></pre>

**Comment by Doehl** [comment]
I don't have this issue. Sure you are not using a caret (^) version of typescript in your package.json file?

**Comment by csentis** [comment]
If existing, you might want to delete your `package-lock.json`, delete your `node_modules` folder and then `npm I` again.

**Comment by IgorMinar** [comment]
yeah. sorry. I'm pretty sure that you either haven't installed the typescript package correctly, or your lock file is outdated.

**Comment by IgorMinar** [comment]
we have tests that verify that our package.json is correct.

**Comment by cvgaviao** [comment]
I've removed yarn.lock and also node_modules from my project and did a yarn install...
But I'm getting the same error.
could someone point me what is wrong in my package.json, please:

`"dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/cdk": "^5.0.1",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/flex-layout": "^2.0.0-beta.12",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "^5.0.1",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/platform-server": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@angular/service-worker": "^5.0.0",
    "@ngrx/effects": "^5.0.0",
    "@ngrx/entity": "^5.0.0",
    "@ngrx/router-store": "^5.0.0",
    "@ngrx/store": "^5.0.0",
    "@ngrx/store-devtools": "^5.0.0",
    "core-js": "^2.4.1",
    "global": "^4.3.2",
    "hammerjs": "^2.0.8",
    "material-design-icons": "3.0.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "http-server": "^0.11.1",
    "@angular/cli": "~1.6.7",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@ngrx/schematics": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "env2json": "^1.1.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ngrx-store-freeze": "^0.2.0",
    "protractor": "~5.1.2",
    "ts-action": "^6.0.1",
    "ts-action-operators": "^6.0.0",
    "ts-node": "~3.2.0",
    "tslint": "~5.9.0",
    "typescript": "~2.6.2"
  },`

**Comment by csentis** [comment]
Just guessing whether you have an old global TS Installation left?

**Comment by cvgaviao** [comment]
@csentis , thank for your reply. 
But TS wouldn't be in node-modules folder? If I remove that folder wouldn't the problem have gone ?

**Comment by csentis** [comment]
For a global installation of TS, the answer is: no, not in your project‘s `node_modules` folder. You can try to find this out with `npm list -g --depth=0`. To rule out another scenario, an outdated TS version installed not standalone, but as a dependency by a (globally installed) angular-cli, just use `npm list -g` and look for typescript.

**Comment by kuncevic** [comment]
That is really weird but I have that issue, tested on both Linux and Windows 10.
No have any version of Typescript installed.

`ng -v:`

```Angular CLI: 1.6.8
Node: 8.9.4
OS: win32 x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.8
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.6.2
webpack-bundle-analyzer: 2.10.0
webpack: 3.10.0
```
to replicate just do
1) `ng g new myapp --routing=true --style=scss`
2) alter the `package.json` by changing the typescript version to `~2.6.2`
3) run yarn

//cc @IgorMinar

**Comment by Baklap4** [comment]
Getting the same output here with `yarn`. With npm it seems to work correctly.

```
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @angular/compiler-cli@5.2.5" has unmet peer dependency "typescript@>=2.4.2 <2.7".
warning "@angular/compiler-cli > tsickle@0.26.0" has unmet peer dependency "typescript@>=2.4.2 <2.7".
warning " > tslint@5.9.1" has unmet peer dependency "typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev".
warning "tslint > tsutils@2.21.1" has unmet peer dependency "typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev".
[4/4] Building fresh packages...
Done in 64.16s.
```

This is my environment:
```

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.8
Node: 9.4.0
OS: linux x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.8
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.6.2
webpack: 3.10.0
```

**Comment by cebor** [comment]
Also getting this warning.

```json
"dependencies": {
    "@angular/animations": "^5.2.4",
    "@angular/cdk": "^5.2.1",
    "@angular/common": "^5.2.4",
    "@angular/compiler": "^5.2.4",
    "@angular/core": "^5.2.4",
    "@angular/forms": "^5.2.4",
    "@angular/http": "^5.2.4",
    "@angular/material": "^5.2.1",
    "@angular/platform-browser": "^5.2.4",
    "@angular/platform-browser-dynamic": "^5.2.4",
    "@angular/router": "^5.2.4",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "fg-cookie": "^1.0.0",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "ngx-facebook": "^2.4.0",
    "ngx-filter-pipe": "^1.0.2",
    "ngx-infinite-scroll": "^0.8.2",
    "rxjs": "^5.5.2",
    "socket.io-client": "^2.0.4",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "1.6.8",
    "@angular/compiler-cli": "^5.2.4",
    "@angular/language-service": "^5.2.4",
    "@types/hammerjs": "^2.0.35",
    "@types/jasmine": "~2.8.4",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~9.4.5",
    "@types/socket.io-client": "^1.4.32",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "npm-run-all": "^4.1.2",
    "protractor": "~5.3.0",
    "rimraf": "^2.6.2",
    "ts-node": "~4.1.0",
    "tslib": "^1.9.0",
    "tslint": "~5.9.1",
    "typescript": "~2.6.2",
    "yarpm": "^0.2.1"
  }
```

**Comment by IgorMinar** [comment]
Some thing not right here after all - it's possible that it's a yarn bug. I can repro this problem using yarn 1.3.2 (npm 5.6.0 works fine). Steps to repro:

```
mkdir test
cd test
yarn init -y

# manual step:
#
#   update package.json using definition from https://github.com/angular/angular/issues/21997#issuecomment-365646797 
#

yarn install
```

the result is:

```
yarn install v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning karma > log4js > nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
warning karma > log4js > loggly > request > node-uuid@1.4.8: Use uuid module instead
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @angular/compiler-cli@5.2.5" has unmet peer dependency "typescript@>=2.4.2 <2.7".
warning "@angular/compiler-cli > tsickle@0.26.0" has unmet peer dependency "typescript@>=2.4.2 <2.7".
warning " > tslint@5.9.1" has unmet peer dependency "typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev".
warning "tslint > tsutils@2.21.1" has unmet peer dependency "typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 329.02s.
```

**Comment by IgorMinar** [comment]
Can someone from the community help to investigate this and see if we can create minimal reproduction for yarn? Maybe there is an existing bug open on yarns issue tracker?

**Comment by kuncevic** [comment]
@IgorMinar
There is two related issues https://github.com/yarnpkg/yarn/issues/5007 https://github.com/yarnpkg/yarn/issues/4743 bot closed

**Comment by IgorMinar** [comment]
Awesome! Thanks. Let's keep this open until yarn 1.4 is tagged as latest.

**Comment by kuncevic** [comment]
@IgorMinar no probs!

**Comment by vicb** [comment]
Closing as this is not an Angular issue.

**Comment by Baklap4** [comment]
member overules owner. How i love hierarchy :joy:
