### ISSUE TITLE
Large difference between `ng serve` and `ng build` numbers

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#22006]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

In the `integration/hello_world__render3__cli` test I get the following numbers when I `ng build --prod --build-optimizer`

```
$ ng build --prod --build-optimizer
chunk {0} polyfills.2fdd242284bad920a44f.bundle.js (polyfills) 61.1 kB [initial] [rendered]
chunk {1} main.fee73a2ac2bb0f30ec71.bundle.js (main) 40.9 kB [initial] [rendered]
chunk {2} styles.ac89bfdd6de82636b768.bundle.css (styles) 0 bytes [initial] [rendered]
chunk {3} inline.4e7c97ed0f02a2c2a5cd.bundle.js (inline) 1.45 kB [entry] [rendered]
```

However, when I use `serve` the main bundle is significantly larger:

```
$ ng serve  --prod --build-optimizer
chunk {0} polyfills.2fdd242284bad920a44f.bundle.js (polyfills) 61.1 kB [initial] [rendered]
chunk {1} main.2ca3076617f5cb1c4581.bundle.js (main) 182 kB [initial] [rendered]
chunk {2} styles.ac89bfdd6de82636b768.bundle.css (styles) 0 bytes [initial] [rendered]
chunk {3} inline.90ec2dd10567f834052e.bundle.js (inline) 1.45 kB [entry] [rendered]
```

## Expected behavior

Bundle sizes would be identical or, at least, similar.

## Minimal reproduction of the problem with instructions

From an Angular repository workspace:
```
./build.sh
cd integration/hello_world__render3__cli
yarn
ng build --prod --build-optimizer
ng serve --prod --build-optimizer
```

**Comment by filipesilva** [comment]
The extra size in `ng serve --prod` is the result of live reload scripts injected into the main bundle. You can opt out of them by using `ng serve --prod --live-reload=false` and obtain the same `ng build` sizes.

Note: `--prod` already sets `--build-optimizer`.

**Comment by IgorMinar** [comment]
I think this has been resolved via `--live-reload=false`. @chuckjaz can you confirm?

**Comment by chuckjaz** [comment]
Confirmed
