### ISSUE TITLE
HttpClient using JSON when it shouldn't

### ISSUE THREAD

**Issue by grosch** [angular/angular#22008]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When making a `get` call where I specify an `Accept: audio/mpeg` header and the response header specifies the `Content-Type: audio/mpeg` and `Content-Transfer-Encoding: binary` the HttpClient is trying to parse JSON and throwing this error:

SyntaxError: Unexpected token I in JSON at position 0 at JSON.parse (<anonymous>) at XMLHttpRequest.onLoad (webpack-internal:///../../../common/esm5/http.js:2290:51) at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:421:31) at Object.onInvokeTask (webpack-internal:///../../../core/esm5/core.js:4939:33) at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:420:36) at Zone.runTask (webpack-internal:///../../../../zone.js/dist/zone.js:188:47) at ZoneTask.invokeTask [as invoke] (webpack-internal:///../../../../zone.js/dist/zone.js:496:34) at invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:1517:14) at XMLHttpRequest.globalZoneAwareCallback (webpack-internal:///../../../../zone.js/dist/zone.js:1543:17)

## Expected behavior
There should be no JSON involved in this transaction.

## Minimal Reproduction

        this.httpClient.get(url, {
            headers: {
                'Accept': 'audio/mpeg'
            }
        })
            .subscribe(
                data => console.log('I got stuff back'),
                error => console.log('Error', error)
            );

## Environment

<pre><code>
Angular version: 5.2.2

Browser:
- [X] Chrome (desktop) Version 64.0.3282.140 (Official Build) (64-bit)

 
For Tooling issues:
- Node version: v9.4.0
- Platform:  Mac High Sierra

Others:

</code></pre>

**Comment by Toxicable** [comment]
https://angular.io/guide/http#requesting-non-json-data

**Comment by alxhub** [comment]
@Toxicable's response is spot on.

**Comment by ansonfoong** [comment]
I'm getting the same issue, but it's with a post request.

`SyntaxError: Unexpected token h in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.onLoad (http://localhost:4200/vendor.js:35370:51)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:3240:31)
    at Object.onInvokeTask (http://localhost:4200/vendor.js:93878:33)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:3239:60)
    at Zone.runTask (http://localhost:4200/polyfills.js:3017:47)
    at ZoneTask.invokeTask [as invoke] (http://localhost:4200/polyfills.js:3314:34)
    at invokeTask (http://localhost:4200/polyfills.js:4452:14)
    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:4200/polyfills.js:4489:21)`
