### ISSUE TITLE
Remove private urls from the sitemap

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#22017]
the following private / internal / test urls are being published into the sitemap confusing the crawlers

- /test
- /file-not-found
- /overview-dump - what is this? it gives 404 but it is in the sitemap

I think that's all, but please check the sitemap one more time in case I missed anything else.

**Comment by petebacondarwin** [comment]
I found a few others:

* /contributors
* /navigation

**Comment by gkalpak** [comment]
I wonder if `/resources-contributing` should also be removed.

**Comment by petebacondarwin** [comment]
I did wonder about that but it is a real page - https://angular.io/resources-contributing - even if it is not referenced in the rest of the site. If it is rubbish then I would rather it was removed from the site altogether rather than blacklisting it from the search index.
