### ISSUE TITLE
Need a way to override CLA failure and make a PR green

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#22014]
Currently, if a PR contains commits from multiple authors, the CLA check will fail, causing the whole PR to be green.

This is not good because the CLA check is very simplistic and doesn't allow commits from multiple authors in a single PR. This is a problem, because we often augment PRs or pull commits from one PR into another one.

A solution this might be a new "cla: override" label that the github robot would recognize and somehow suppress the status from the cla bot.

It would be even better if this was a feature supported by the sign-cla bot. I can ask about that internally.

**Comment by gkalpak** [comment]
The CLA bot now asks for the extra commit authors to add a `@googlebot I consent` comment to give their consent for including their commits in the PR.

Can we close this or do we still want the `cla: override` label?

**Comment by jelbourn** [comment]
Closing since googlebot now supports this
