### ISSUE TITLE
Cannot insert multiple Dynamic Components in one ViewContainerRef

### ISSUE THREAD

**Issue by mboughaba** [angular/angular#22010]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When calling ViewContainerRef.insert(viewRef: ViewRef) multiple times to add multiple dynamic components only the last dynamic component will be attached to the dom.

## Expected behavior

Multiple dynamic components are attached to the dom.

## Minimal reproduction of the problem with instructions

```typescript
export class DynamicComponent {
  currentComponent;

  @ViewChild('dynamicComponentContainer', {
    read: ViewContainerRef
  }) dynamicComponentContainer: ViewContainerRef;

  @Input() set componentData(data: {
    component: any,
    inputs: any
  }) {
    if (!data) {
      return;
    }
    let inputProviders = Object.keys(data.inputs).map((inputName) => {
      return {
        provide: inputName,
        useValue: data.inputs[inputName]
      };
    });
    let resolvedInputs = ReflectiveInjector.resolve(inputProviders);
    let injector = ReflectiveInjector.fromResolvedProviders(resolvedInputs, this.dynamicComponentContainer.parentInjector);
    let factory = this.resolver.resolveComponentFactory(data.component);
    let component = factory.create(injector);

    // Insert the component into the dom container
    this.dynamicComponentContainer.insert(component.hostView);
    this.currentComponent = component;
  }

  constructor(private resolver: ComponentFactoryResolver) { }
}
```
When called from AppComponent
```typescript
  createComponent<T>(component: T) {
      this.componentData = {
        component: component,
        inputs: {
          input: 1
        }
      }
  }

  createComponents() {
    this.createComponent(OneComponent);
    this.createComponent(TwoComponent);
    // There are more components to add
  }

  ngAfterViewInit() {
      this.createComponents();
  }
```

## Workaround
Set immediate timeout solves the issue, but it is very dirty
```typescript
  createComponent<T>(component: T) {
    setTimeout(() => {
      this.componentData = {
        component: component,
        inputs: {
          input: 1
        }
      }
    }, 0);

```
I didn't understand yet why the workaround is even working, maybe has something to do with change detection.

Please let me know if this is easily reproducible otherwise I can add a stackblitz.

## What is the motivation / use case for changing the behavior?

With the current behavior it is impossible to attach multiple dynamic components to the dom and the workaround is dirty.

## Environment

<pre><code>
Angular version: 5.0.0, 5.2.0 and 5.2.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.4.0 
- Platform:  Windows

Others:

</code></pre>

Cheers,
Mo

**Comment by Yerkon** [comment]
Hi2 @mboughaba,  [look at this](https://angular.io/guide/reactive-forms#async-vs-sync)

> For example, if you inject the form control with a @ViewChild(NgForm) query and examine it in the ngAfterViewInit lifecycle hook, you'll discover that it has no children. You must wait a tick, using setTimeout, before you can extract a value from a control, test its validity, or set it to a new value.

**Comment by jburtondev** [comment]
@mboughaba Great solution. It works.

**Comment by mboughaba** [comment]
@jburtondev glad it helped,
Another solution would be to call `detectChanges` on `changeDetectorRef`

```
  public createComponent<T extends LeafComponent, A extends ComponentAttributes>(component: T, attribute: A, payload: A) {
    this.dynamicContent = {
      component,
      attribute,
      payload
    };

    // NOTE: This is required because dynamicContent will be changed after ViewInit of parent.
    this.cdr.detectChanges();
  }

  constructor(protected cdr: ChangeDetectorRef) {
    super();
  }
```

**Comment by vlaco** [comment]
Can anyone tell me how refactor the same code for Angular 5? I am using this same example but with updating to Angular v5 ReflectiveInjector is depricated and Injector doesnt have methods resolve and fromResolvedProviders. Any ideas?

**Comment by mboughaba** [comment]
@vlaco 
I suggest that you post this question on stackoverflow with a small plunkr and cross link here to avoid confusion in this thread.

here is a plunkr to start with: https://embed.plnkr.co/p7VHB4/

for your injector, yes `ReflectionInjector` is deprecated so you need something like below
```typescript
    const injector = Injector.create({
      providers: [
        {
          provide: yourClass,
          useValue: yourValue
        }
      ],
      parent: this.dynamicComponentContainer.parentInjector
    });
    const factory = this.resolver.resolveComponentFactory(dc.component);
    const component = factory.create(injector);
    this.dynamicComponentContainer.insert(component.hostView);
```
In your dynamic component you need
```typecript
  constructor(@Inject(WhatNeedsToBeInjected) public ca: WhatWillBeInjected) {
    super();
  }
```
Make sure you avoid injecting string and inject classes instead.

cheers

**Comment by vlaco** [comment]
@mboughaba Thanks a lot! :)

**Comment by cls-yzhang** [comment]
I know this is an old issue.

Now it shows an warning "parentInjector is deprecated: No replacement" in the tslint.  Is there any fix for that?

When will parentInjector be removed?

**Comment by mboughaba** [comment]
Hey @cls-yzhang 

Just remove the parent key from the object you are passing to `Injector.create`.

Cheers

**Comment by cls-yzhang** [comment]
> Hey @cls-yzhang
> 
> Just remove the parent key from the object you are passing to `Injector.create`.
> 
> Cheers

Thanks @mboughaba !

This works for me.  The `parent` is indeed not used in my case.
