### ISSUE TITLE
Promise not awaited by flushMicrotasks in test

### ISSUE THREAD

**Issue by fredgate** [angular/angular#22012]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior
I am using agm-core (angular component for google maps) and I test a component that uses MapsApiLoader that is class that asynchronously loads google maps library : the `load` method returns a Promise that resolves when libraries is loaded. Source code here : https://github.com/SebastianM/angular-google-maps/blob/658de77b1ec67ca80d4bc46c3f958af47572735a/packages/core/services/maps-api-loader/lazy-maps-api-loader.ts#L95
In my test I need to do some works when library is loaded, that is when promise resolves. For that I run my test in the fakeAsync zone, and use the flushMicrotasks method. But promise is not termianted when this methods returns, and my next code is then executed.

## Expected behavior
That all promises be terminated when `flushMicroTasks` returns.

## Minimal reproduction of the problem with instructions
Here is a very simple test that shows problem with this promise but not for another and for timer :
```
it('should load maps api', fakeAsync(() => {
	TestBed.configureTestingModule({
		imports: [ AgmCoreModule.forRoot({ apiKey: 'XXXXX' }) ]
	});
	const loader = TestBed.get(MapsAPILoader);

	window.setTimeout(() => console.log('timer'), 0);
	loader.load().then(() => console.log('loader promise'));
	Promise.resolve().then(() => console.log('test promise'));

	console.log('flush');
	flushMicrotasks();
	console.log('flush done');
	tick();
	console.log('tick done');

	console.log('expect');
}));
```

Last instruction of my test is executed before api is loaded.
Current output is :
```
LOG: 'flush'
LOG: 'test promise'
LOG: 'flush done'
LOG: 'timer'
LOG: 'tick done'
LOG: 'expect'
LOG: 'loader promise'
```

## What is the motivation / use case for changing the behavior?
Execute code after all promises resolved.
Expected output is :
```
LOG: 'flush'
LOG: 'test promise'
LOG: 'loader promise'
LOG: 'flush done'
LOG: 'timer'
LOG: 'tick done'
LOG: 'expect'
```

## Environment

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 58.0.1
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4
- Npm : 5.6.0
- Platform:  Windows 10

Libraries:
- angular : 5.2.1
- angular cli : 1.6.5
- zone : 0.8.20
- agm/core : 1.0.0-beta.2

**Comment by JiaLiPassion** [comment]
@fredgate , I just see the code you posted of `google map`, it is a `jsonp` call to get data, currently `jsonp` is not treated as `zone aware` async operations, so the `loader promise` is not controlled by `fakeAsync`.

there are two possible solutions here.

1. I have made a PR to help to patch `jsonp` , https://github.com/angular/zone.js/pull/997
if this PR is merged, I can provide some help method to patch `google map lazy load`. so your test would be fine.

2. for the case 

```javascript
loader().then(...);
```

which `loader()` return a promise but `loader` itself is not a `zone aware` operation, maybe `fakeAsync` should also handle this case by default, I will consider about it, if I found a solution, I will make a PR in `zone.js`.

**Comment by fredgate** [comment]
Yes loading of google maps use jsonp, but the loader returns a promise that is resolve when callback is called by jsonp. I thought that flushMicrotasks was able to wait for any promise no matter how it is resolved.

I can not execute my test in the resolve of the promise, because the example that I wroted in the issue was a simple case to show the problem. In fact, the loader is called by the component that I test, so my test is not aware of this promise. So option 2 is not possible for me.

So @JiaLiPassion  my hope lies in your pull request ;-)

**Comment by JiaLiPassion** [comment]
@fredgate , 

>  I thought that flushMicrotasks was able to wait for any promise no matter how it is resolved. I do not understand why it is not the case.

in fact, although the `loader` return a `promise`, but the `loader itself` is not a `zone aware` async task, so `promise` itself is not a `zone aware` async operation. angular `async` or `fakeAsync` will only wait for the `async` operations `zone aware`, such as `promise.then` but not `promise` itself.

**Comment by mhevery** [comment]
Wont fix since JSONP can't be patched.
