### ISSUE TITLE
Rename Angular 2 to Angular in stackshare.io

### ISSUE THREAD

**Issue by splincode** [angular/angular#22021]
Could Google somehow agree that they made redirects to a normal page, where Angular is simply mentioned?

https://stackshare.io/angular instead https://stackshare.io/angular-2

Official repo: https://github.com/leanstack
Email: team@stackshare.io

**Comment by jotatoledo** [comment]
There has been enough discussion about this topic in the past. Sadly, as the framework came out, ppl adopted "angular 2" as the "official" name for it. Afterwards developers realized that such a name made no sense.

If we start opening issues for every site, blog, etc that has a wrong name on it, we would never end. The best thing that we can do at the moment IMO, is inform newcomers about this and minimize the amount of new resources created with a wrong naming.

**Comment by splincode** [comment]
However, major publications, blogs, etc., it would be useful to inform that they misinform the community

**Comment by Wykks** [comment]
It's clear enough: https://angular.io/presskit#brand-names

**Comment by jotatoledo** [comment]
Yeah, but its not something that I would personally ask the angular team to prioritize or do, they most definitely have more relevant things to do.

Feel free to contact as many bloggers, devs, etc that used a wrong name to advice em to change it though.

**Comment by IgorMinar** [comment]
@splincode have you tried emailing them?

You are a member of our community just like anyone else who cares about Angular. Angular community is all about people that help each other and help Angular be better.

You obviously care enough to file an issue with us, so I encourage you to email stackshare and ask them to rename the entry. Feel free to reference our [branding guidelines](https://angular.io/presskit#brand-names) and even this issue. Let us know how it went.

Thanks for helping Angular.

**Comment by splincode** [comment]
@IgorMinar Yes, I tried to write to them, I'm waiting for an answer

**Comment by IgorMinar** [comment]
Thank you!

**Comment by StephenFluin** [comment]
We reached out to StackShare about this. It's in their court now.
