### ISSUE TITLE
remove ng-atl banner from the homepage

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#22029]
let's remove the banner from https://angular.io/ homepage - the conf is over.

unless it breaks the design we should not replace it with anything new for now.

**Comment by petebacondarwin** [comment]
I have a work on progress for this

**Comment by IgorMinar** [comment]
@petebacondarwin can you please fix this first and then work on #22031?

**Comment by StephenFluin** [comment]
@petebacondarwin Please replace it with ng-conf.

https://www.ng-conf.org/
April 18–20th 2018 Salt Lake City, UT

![](https://www.ng-conf.org/wp-content/uploads/2016/09/logo.png)

**Comment by petebacondarwin** [comment]
@StephenFluin I'm afraid that logo image is not going to work in the banner. I tried adding the dark background to make it similar to how it is in their website but it is just too fiddle and looks weird.

![screen shot 2018-02-07 at 09 59 06](https://user-images.githubusercontent.com/15655/35910163-a258d9f2-0bed-11e8-9430-fb3a1828dacb.png)

**Comment by petebacondarwin** [comment]
@IgorMinar I have removed the banner in #22060 - but my #22043 PR for #22031 is now ready to review and also removes the banner. So we can land either.

**Comment by IgorMinar** [comment]
@StephenFluin this issue will get closed soon because #22060 is landing soon. Can you please open a new issue and provide the correct assets? thanks

**Comment by aaronfrost** [comment]
@petebacondarwin what size do you need from me? I can get you something bigger, but I need to know what you need.

**Comment by IgorMinar** [comment]
@StephenFluin I created a new issue: https://github.com/angular/angular/issues/22122 can you please do this yourself next time? thanks!
