### ISSUE TITLE
message : "Http failure response for (unknown url): 0 Unknown Error"

### ISSUE THREAD

**Issue by ygr15893000** [angular/angular#22022]
`
user.ts:46 ERROR 
HttpErrorResponse {headers: HttpHeaders, status: 0, statusText: "Unknown Error", url: null, ok: false, …}
error
:
ProgressEvent {isTrusted: true, lengthComputable: false, loaded: 0, total: 0, type: "error", …}
headers
:
HttpHeaders {normalizedNames: Map(0), lazyUpdate: null, headers: Map(0)}
message
:
"Http failure response for (unknown url): 0 Unknown Error"
name
:
"HttpErrorResponse"
ok
:
false
status
:
0
statusText
:
"Unknown Error"
url
:
null
__proto__
:
HttpResponseBase`

**Comment by ygr15893000** [comment]
polyfills.js:3 OPTIONS https://example.com/api/v1/login net::ERR_CONNECTION_REFUSED
s @ polyfills.js:3
t.scheduleTask @ polyfills.js:3
onScheduleTask @ polyfills.js:3
t.scheduleTask @ polyfills.js:3
r.scheduleTask @ polyfills.js:3
r.scheduleMacroTask @ polyfills.js:3
(anonymous) @ polyfills.js:3
o.(anonymous function) @ polyfills.js:2
(anonymous) @ http.js:2347
Observable._trySubscribe @ Observable.js:172
Observable.subscribe @ Observable.js:160
subscribeToResult @ subscribeToResult.js:23
MergeMapSubscriber._innerSub @ mergeMap.js:132
MergeMapSubscriber._tryNext @ mergeMap.js:129
MergeMapSubscriber._next @ mergeMap.js:112
Subscriber.next @ Subscriber.js:89
ScalarObservable._subscribe @ ScalarObservable.js:49
Observable._trySubscribe @ Observable.js:172
Observable.subscribe @ Observable.js:160
MergeMapOperator.call @ mergeMap.js:87
Observable.subscribe @ Observable.js:157
FilterOperator.call @ filter.js:60
Observable.subscribe @ Observable.js:157
MapOperator.call @ map.js:56
Observable.subscribe @ Observable.js:157
ConnectableObservable.connect @ ConnectableObservable.js:40
RefCountOperator.call @ refCount.js:24
Observable.subscribe @ Observable.js:157
webpackJsonp.310.User.login @ user.ts:39
webpackJsonp.348.LoginPage.doLogin @ login.ts:37
(anonymous) @ LoginPage.html:11
handleEvent @ core.js:13255
callWithDebugContext @ core.js:14740
debugHandleEvent @ core.js:14327
dispatchEvent @ core.js:9704
(anonymous) @ core.js:10318
(anonymous) @ platform-browser.js:2614
t.invokeTask @ polyfills.js:3
onInvokeTask @ core.js:4620
t.invokeTask @ polyfills.js:3
r.runTask @ polyfills.js:3
e.invokeTask @ polyfills.js:3
p @ polyfills.js:2
v @ polyfills.js:2
user.ts:46 ERROR HttpErrorResponse {headers: HttpHeaders, status: 0, statusText: "Unknown Error", url: null, ok: false, …}error: ProgressEvent {isTrusted: true, lengthComputable: false, loaded: 0, total: 0, type: "error", …}headers: HttpHeaders {normalizedNames: Map(0), lazyUpdate: null, headers: Map(0)}message: "Http failure response for (unknown url): 0 Unknown Error"name: "HttpErrorResponse"ok: falsestatus: 0statusText: "Unknown Error"url: null__proto__: HttpResponseBase
(anonymous) @ user.ts:46
SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
SafeSubscriber.error @ Subscriber.js:197
Subscriber._error @ Subscriber.js:128
Subscriber.error @ Subscriber.js:102
Subscriber._error @ Subscriber.js:128
Subscriber.error @ Subscriber.js:102
Subject.error @ Subject.js:70
Subscriber._error @ Subscriber.js:128
ConnectableSubscriber._error @ ConnectableObservable.js:77
Subscriber.error @ Subscriber.js:102
Subscriber._error @ Subscriber.js:128
Subscriber.error @ Subscriber.js:102
Subscriber._error @ Subscriber.js:128
Subscriber.error @ Subscriber.js:102
OuterSubscriber.notifyError @ OuterSubscriber.js:22
InnerSubscriber._error @ InnerSubscriber.js:26
Subscriber.error @ Subscriber.js:102
onError @ http.js:2283
t.invokeTask @ polyfills.js:3
onInvokeTask @ core.js:4620
t.invokeTask @ polyfills.js:3
r.runTask @ polyfills.js:3
e.invokeTask @ polyfills.js:3
p @ polyfills.js:2
v @ polyfills.js:2
XMLHttpRequest.send (async)
s @ polyfills.js:3
t.scheduleTask @ polyfills.js:3
onScheduleTask @ polyfills.js:3
t.scheduleTask @ polyfills.js:3
r.scheduleTask @ polyfills.js:3
r.scheduleMacroTask @ polyfills.js:3
(anonymous) @ polyfills.js:3
o.(anonymous function) @ polyfills.js:2
(anonymous) @ http.js:2347
Observable._trySubscribe @ Observable.js:172
Observable.subscribe @ Observable.js:160
subscribeToResult @ subscribeToResult.js:23
MergeMapSubscriber._innerSub @ mergeMap.js:132
MergeMapSubscriber._tryNext @ mergeMap.js:129
MergeMapSubscriber._next @ mergeMap.js:112
Subscriber.next @ Subscriber.js:89
ScalarObservable._subscribe @ ScalarObservable.js:49
Observable._trySubscribe @ Observable.js:172
Observable.subscribe @ Observable.js:160
MergeMapOperator.call @ mergeMap.js:87
Observable.subscribe @ Observable.js:157
FilterOperator.call @ filter.js:60
Observable.subscribe @ Observable.js:157
MapOperator.call @ map.js:56
Observable.subscribe @ Observable.js:157
ConnectableObservable.connect @ ConnectableObservable.js:40
RefCountOperator.call @ refCount.js:24
Observable.subscribe @ Observable.js:157
webpackJsonp.310.User.login @ user.ts:39
webpackJsonp.348.LoginPage.doLogin @ login.ts:37
(anonymous) @ LoginPage.html:11
handleEvent @ core.js:13255
callWithDebugContext @ core.js:14740
debugHandleEvent @ core.js:14327
dispatchEvent @ core.js:9704
(anonymous) @ core.js:10318
(anonymous) @ platform-browser.js:2614
t.invokeTask @ polyfills.js:3
onInvokeTask @ core.js:4620
t.invokeTask @ polyfills.js:3
r.runTask @ polyfills.js:3
e.invokeTask @ polyfills.js:3
p @ polyfills.js:2
v @ polyfills.js:2
polyfills.js:3 XHR failed loading: OPTIONS "https://example.com/api/v1/login".

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by alxhub** [comment]
Status code 0 indicates a CORS failure.

**Comment by sgiradoa-psl** [comment]
@alxhub We have a very long process on backend that makes the API unavailable until it finishes. During this process the OPTIONS response returns an status code`503` and we have an interceptor that redirects the app to a "In maintenance" page. It worked on Angular 1 $http, now the status is 0 with the same issue: `Http failure response for (unknown url): 0 Unknown Error` and I am not able to know if the status is `503`.
Not sure if I should use this `status===0`like`OPTIONS` was `503`.

**Comment by trotyl** [comment]
`OPTIONS` response is not exposed in both XHR and Fetch, no client-side logic can help with that.

**Comment by ChristianLutz** [comment]
Maybe some others have the same problem I had. https://stackoverflow.com/questions/48557390/angular-4-http-failure-response-for-unknown-url-0-unknown-error

**Comment by zeptoMawais** [comment]
fadfa

**Comment by ManishJainGitHubUser** [comment]
I was getting this error even when CORS was enabled. I have posted my solution to above SO link.

**Comment by NomanBashir133** [comment]
Error with
 **status: 0
 statusText: "Unknown Error"
 url: null**
 also occurs when browser doesn't have internet connection. 

**No CORS** error object should be differentiable from error of **No Internet connection**.
