### ISSUE TITLE
Export `DomRendererFactory2` publicly from `@angular/platform-browser`

### ISSUE THREAD

**Issue by maxkoretskyi** [angular/angular#22024]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

To implement custom renderer and extend the default renderer, I need to specify `DomRendererFactory2` as a dependency:

```
    providers: [
        {
            provide: RendererFactory2,
            useFactory(rendererFactory) {
                return new CustomRendererFactory2(rendererFactory);
            },
            deps: [DomRendererFactory2]
        }
    ],
```

Currently, `DomRendererFactory2` is exported privately, so I'm importing it by pre-pending with Greek Theta symbol:

```
import { ɵDomRendererFactory2 as DomRendererFactory2 } from '@angular/platform-browser';`
```

## Expected behavior

I want to be able to import it directly from '@angular/platform-browser';` without pre-pending it with Greek Theta symbol:

```
import { DomRendererFactory2 as DomRendererFactory2 } from '@angular/platform-browser';`
```

**Comment by trotyl** [comment]
I think it's better to re-introduce something similar to [AngularJS's decorator pattern](https://docs.angularjs.org/guide/decorators) in Angular *(but likely in a different name)*, should be able to provide a more general solution.

<sub>Since the term `decorator` changed from **decorator design patten** to **attribute directive** to **ES decorator proposal**, I don't know if there's an existing issue due to the search difficulty.</sub>

**Comment by maximusk** [comment]
@trotyl , yes, as general mechanism this would be an ideal solution. But the quick fix would be to simply export `DomRendererFactory2` publicly.  I'm extending the default renderer in the same way as Angular does with `DebugRenderer2`.

**Comment by pkozlowski-opensource** [comment]
I'm going to close this one as we don't have to export `DomRendererFactory2` publicly and maintain it as the public API. We've got the future request already to have component-specific renderers, we are tracking it in #12688
