### ISSUE TITLE
Optimize whitespace in template by default (preserveWhitespace to false by default)

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#22027]
In https://github.com/angular/angular/pull/18401 we implemented `preserveWhitespace` compiler flag to fix https://github.com/angular/angular/issues/11679.

Initially we made this an opt-in because of a possibility of subtle breaking changes related to applying styles to DOM with whitespace suddenly stripped from most nodes.

Now that we verified that the negative impact of this change at Google has been minimal, we should go ahead and make **`https://github.com/angular/angular/issues/11679` option set to false by default**.

**Comment by StefanKern** [comment]
Hey, Issue #21049 list a number of complains where this is change.

**Comment by listepo-alterpost** [comment]
Hello, @IgorMinar why it doesn't work for `TestBed` by default?
