### ISSUE TITLE
Css changes shouldn't refresh the browser tab

### ISSUE THREAD

**Issue by shyamal890** [angular/angular#22037]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently when css code in the application is modified a full reload/refresh of browser tab takes place. 

## Expected behavior
Instead on the the `css` code must be modifed without reloading/refreshing the browser tab. This is something that https://github.com/ionic-team/ionic handles very well.

**Comment by mlc-mlapis** [comment]
@shyamal890 ... what exactly do you mean? ... something as global CSS styles?

**Comment by shyamal890** [comment]
`scss` files that are either imported in `styles.scss` or in the component.

**Comment by Yerkon** [comment]
@shyamal890, you can use **hot module reload** command:
`ng serve --hmr`. After that, changing component css/ts file will trigger partial reload.

**Comment by alxhub** [comment]
Actually, this is a CLI issue, and @Yerkon is correct.
