### ISSUE TITLE
 'onSameUrlNavigation' reload feature does not reload the routed components

### ISSUE THREAD

**Issue by dhanarajp** [angular/angular#22038]
Reloading the components when the same navigation url is triggered:
If the same url is calling more than once, using the onSameUrlNavigation:reload feature we can subscribe the router events in the corresponding component, but the component is reloading again over there. In my case the component should be reloaded.

**Comment by mlc-mlapis** [comment]
@dhanarajp ... `onSameUrlNavigation` feature is not designed to create a new instance of the component ... because there is no reason to do that. It is designed to invoke router events / run attached guards / run attached resolvers.

Also read this: https://github.com/angular/angular/issues/21647

**Comment by dhanarajp** [comment]
Thanks @mlc-mlapis  , then how can i reload the component when navigate the same url?, any thing way to achieve this scenario.

**Comment by mlc-mlapis** [comment]
@dhanarajp ... but this exactly what you should not do! I suppose that you have some code that runs only when the component is instantiated ... probably in its constructor. But you should design your code that it is ready to re-run when receiving some emits ... and there could be emits from router.events, ActivatedRoute observables, ... So you should change your code to be able to use those information to re-run some code / hooks / method ... on your component to react properly when a route is reloaded.

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

You can also ask for support on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

**Comment by jberall** [comment]
Here is a great article to explain.
https://medium.com/engineering-on-the-incline/reloading-current-route-on-click-angular-5-1a1bfc740ab2

Also not if you redirectTo you need the redirected route.
