### ISSUE TITLE
RouteReuseStrategy delete handles anew Route ERROR

### ISSUE THREAD

**Issue by CoSaoyears** [angular/angular#22036]
ERROR Error: Uncaught (in promise): Error: Cannot insert a destroyed View in a ViewContainer!
Error: Cannot insert a destroyed View in a ViewContainer!

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
