### ISSUE TITLE
Dart transformers should record interfaces

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#2204]
If I have the following class in my app

```
class MyClass implements MyInterface1, MyInterface2 {}
```

Dart transformers should record this information in the reflector object, so that I can do the following:

```
reflector.interfaces(MyClass) //should return [MyInterface1, MyInterface2]
```

**Comment by kegluneq** [comment]
What is this being used for? Is there a design document I can read?

**Comment by naomiblack** [comment]
This is the Dart part of completing the work that @yjbanov requested in https://github.com/angular/angular/issues/2120

**Comment by kegluneq** [comment]
Additional context: https://github.com/angular/angular/issues/2220

**Comment by kegluneq** [comment]
For which classes does this need to occur?
1. Every class?
2. Only `@Injectable`?
3. Only `@Directive`?
4. Only `@Component`?

(1) is possible but will likely defeat tree-shaking, resulting in code bloat. For that reason I'd prefer one of the other options if possible.

**Comment by kegluneq** [comment]
Also, is this something that could be done with `is` checks, which `dart2js` supports?

If this information is used in the generation of change detectors (which I imagine it is) the answer is likely "no" since change detectors are created before we ever have an instance of a Type.
