### ISSUE TITLE
Bot should consider "type: refactor" issues as "triaged" and move into backlog

### ISSUE THREAD

**Issue by kara** [angular/angular#22053]
If you look at: 
https://github.com/angular/angular/issues?q=is%3Aopen+is%3Aissue+label%3A%22comp%3A+forms%22+no%3Amilestone

The second one down is triaged, but still showing up in the "no milestone" list because its type is "refactor".

cc @IgorMinar  @ocombe

**Comment by IgorMinar** [comment]
Also "type: RFC / Discussion / question"

**Comment by ocombe** [comment]
@IgorMinar actually the bot only triages issues right now, not PRs, that's why #20848 wasn't triaged automatically.
Do you want me to change the bot so that it triages PRs as well? I think that we said that it shouldn't do that, right?

**Comment by IgorMinar** [comment]
PRs should be triaged via the PR workflow automation proposal (I don't have
the issue # handy)
