### ISSUE TITLE
require("environment") const variable not loading before AngularFireModule.initializeApp(environment) in production build but working with deveopment build ?

### ISSUE THREAD

**Issue by bhawin-bigstep** [angular/angular#22059]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I am using angular2
In my app.module.ts file 
I have this code:
var environment = require("data.json");

@NgModule({
    imports: [
        AngularFireModule.initializeApp(environment),
    ],
})

## Expected behavior

The code is working perfect when i do "ng build"
The doesn't work when i do "ng build --target=production"

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by bhawin-bigstep** [comment]
@trotyl  , I am using angularfire2 module which i am initializing via 
`AngularFireModule.initializeApp(environment),` in my imports section of my ngmodule
Now ,  i am importing the environment variable from 
var environment = require("../firebase/web-google-services.json");


The environment variable is passing into AngularFireModule.initializeApp(environment) well in ng build but not good in "ng build --target=production"

I think because in production mode node_modules code is compiled first with (environment = undefined). After that we are getting correct environment variable values.

I have done console.log on node_modules/angularfire2/angularfire2.js
`AngularFireModule.initializeApp = function (config, appName) {
        console.log(config);
        return {
            ngModule: AngularFireModule,
            providers: [
                { provide: FirebaseAppConfigToken, useValue: config },
                { provide: FirebaseAppName, useValue: appName }
            ]
        };
    };`

**Comment by bhawin-bigstep** [comment]
@trotyl , anything man, I am stuck here . I ma sure it is some angular issue

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

It sounds like you're using importing environment incorrectly
Check the docs on it here https://github.com/angular/angular-cli/wiki/stories-application-environments
