### ISSUE TITLE
Set CSP header value before Bootstrap- Angular2

### ISSUE THREAD

**Issue by jilna** [angular/angular#22057]
I am trying to CSP response header to my angular 2 application on bootstrap. This is a dynamic value and hence I cannot set it on the web.config or add the meta tag. 

Is there a way this can be achieved in Angular 2 application.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
