### ISSUE TITLE
Issue in Angular Tutorial, Chapter "Services"

### ISSUE THREAD

**Issue by bogvak** [angular/angular#22051]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Angular Tutorial, Chapter 6.
https://angular.io/tutorial/toh-pt4
Title: Provide the HeroService
Sample piece of code mentions
`providers: [ HeroService, MessageService ],`

And after that further in text mentioned ('**See it run**') that whole app should work.
Unfortunately it's not true as at this stage it still hasn't been declared `MessageService` provider.

## Expected behavior
It's better to fix this line this way:
`providers: [ HeroService ],`

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/20398

**Comment by trotyl** [comment]
Should be closed as deployment already done.
