### ISSUE TITLE
Percolate down @Input() and bubble up @Output() from deep grandchild to parent and skip intermediary children?

### ISSUE THREAD

**Issue by momoadeli** [angular/angular#22052]
## I'm submitting a FEATURE REQUEST

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In scenarios with parent components that have many deeply nested children and grandchildren (say 0 to 'n' levels deep where parent is level 0), if grandchild ('gc') at level k needs data that only parent has access to, each intermediary child must have an `@Input()` ...with that data merely passed down. Conversely, in order for gc(k) to emit its requests, each intermediary child must intercept `@Output()/emit()s` and merely pass them up. The parent/child relationship is depicted below:
```
<parent0>
    <gc1 [data]="data">
         <gc2 [data] = "data">
              <gc3 [data] = "data">
                   ...etc, etc, down to gc(k)
              </gc3>
         </gc2>
    </gc1>
</parent0>
```

## DESIRED behavior

Components that **DO NOT** have `@Input()s or @Output()s` will automatically pass @Input()/@Output()s down/up  the chain by default. OR add settings:
Activate passthrough by, perhaps omitting `@Input()s/@Output()s` or a decorator like '@`AutoPassthrough`' on a component or an attribute on the `@Component` decorator:

`@Component: {
...
      passThrough: passThroughStrategy.onInput,
      passThrough: PassThroughStrategy.onOutput
..
}`

## What is the motivation / use case for changing the behavior?

Hectic and laborious passing through `@Input()s/@Output()s `

## Environment

<pre><code>
Angular version: 5.2

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues: n/a

Others: n/a

**Comment by alxhub** [comment]
This is an excellent use case for shared services, a store, or some other state management system.
