### ISSUE TITLE
Abstract superclasses and Injector gives Argument of type 'typeof AMyService' is not assignable to parameter of type 'Type<AMyService>

### ISSUE THREAD

**Issue by asgerjensen** [angular/angular#22063]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Using `fixture.debugElement.injector.get` reports as deprecated (from 4.0.0 use Type<T>|InjectionToken<T>), but its not possible to use the alternate version with an abstract type.

```ts
import { Injectable } from '@angular/core';

@Injectable()
export abstract class AMyService {
    abstract hello(): string;
}

@Injectable()
export class MyService extends AMyService {
    public hello() {
        return 'world';
    }
}
```

then in spec
```
       fixture.debugElement.injector.get<AMyService>(AMyService);
```
Will give compile error (Typescript 2.6.2):
```
error TS2345: Argument of type 'typeof AMyService' is not assignable to parameter of type 'Type<AMyService> | InjectionToken<AMyService>'.
  Type 'typeof AMyService' is not assignable to type 'InjectionToken<AMyService>'.
    Property '_desc' is missing in type 'typeof AMyService'
```

If I change to 
```
 fixture.debugElement.injector.get<MyService>(MyService);
```
it compiles, but then I lose ability to have the abstract superclass as interface, which (used to?) be required if you wanted to use it as provider token (as opposed to just having an interface).

## Expected behavior

To be able to use the injector without getting deprecation or compile errors, with abstract classes.

## Minimal reproduction of the problem with instructions
1. `ng new demosite`
2. Add service as above
3. add `fixture` line to the `app.component.spec.ts` file generated

## What is the motivation / use case for changing the behavior?

Avoid getting hit by deprecation issues in tests.

## Environment

<pre><code>
Angular version: 5.2.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by paddyfink** [comment]
@asgerjensen  please let me know if you find a solution. I have the same problem
