### ISSUE TITLE
reloadOnSearch should not cause reload on hash change

### ISSUE THREAD

**Issue by kshay** [angular/angular#2206]
Background: We have pages that dynamically update the URL #hash. Not realizing that setting a route's reloadOnSearch: true would also mean it reloads when the hash changes, we recently did that and those pages broke rather thoroughly.

Yes, our fault for not checking the docs, since this is clearly documented, but... the name is misleading, and I'm also hard pressed to think of a use case for wanting to reload a route on hash change (in the context of html5Mode, of course). In any event, it feels like a better interface would be simply to support two separate options, reloadOnSearch and reloadOnHash. Or if you didn't want to make a breaking change, perhaps the reloadOnSearch behavior could remain but with a noReloadOnHash to override it?

I'm happy to work on a PR for one of those or another option, but wanted to open this first to get people's thoughts.

**Comment by mhevery** [comment]
Please file here: https://github.com/angular/angular.js/issues/new this is Angular 2 repo not Angular.js
