### ISSUE TITLE
currencyPipe | can number_expression input be undefined/null ?

### ISSUE THREAD

**Issue by casvil** [angular/angular#22062]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I am trying to use the currencyPipe by itself without providing input `number_expression` like:
`{{ | currency[:currencyCode] }}`
`{{ null | currency[:currencyCode] }}`
`{{ undefined | currency[:currencyCode] }}`

And got either error or empty response

## Expected behavior

Only display the currency symbol like:
just `$` or `€`

**Comment by casvil** [comment]
@ericmartinezr any problem?

**Comment by vicb** [comment]
We have a plan to provide and API to get access to the locale data.
Using a pipe is not the right solution.

**Comment by casvil** [comment]
`input.forEach(element => {
  let found = element.match(/\d+/);
  
  return element.substring(0, found.index);
});`
