### ISSUE TITLE
[HTTPClient] Incorrect URI encoding for params

### ISSUE THREAD

**Issue by andyrichardson** [angular/angular#22068]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Context
HTTPClient

## Current behavior
When adding a param to a HTTP GET request, a colon `:` is not encoded to its UTF-8 value `%3A`.

## Expected behavior
When adding a param to a HTTP GET request, a colon `:` is encoded to it's UTF-8 value `%3A`.

## Minimal reproduction of the problem with instructions

    import { Injectable } from '@angular/core';
    import { HttpClient } from '@angular/common/http';
    import { url } from 'config/main';

    @Injectable()
    export class ExampleService {
      constructor(private http: HttpClient) { }

      makeRequest(): void {
        return this.http.get('http://url.com', {
          params: {
            param: '$:test',
          },
        });
      }
    }

Expected request
    
    http://url.com?param=%24%3atest

Actual request
   
    http://url.com?param=%24:atest

## What is the motivation / use case for changing the behavior?
It seems as though the [encodeURI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) function is being used on parameters in order to translate them to UTF-8 strings as opposed to the more appropriate [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) function

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 64.0.3282.119
 
Others:

</code></pre>

**Comment by trotyl** [comment]
Duplicate of #18884

**Comment by andyrichardson** [comment]
Thanks @trotyl

**Comment by lucipacurar** [comment]
I'm still experiencing this bug on Angular 6.0.3. Isn't it fixed already?

In my case I'm sending a date string to the server: `2018-06-14T10:20:42+03:00` as a URL param and it doesn't get encoded at all.

**Comment by henlz** [comment]
I'm having problems with the `+` character.

**Comment by philipphutterer** [comment]
> I'm having problems with the `+` character.

As @trotyl mentioned already, this solution worked for me also for the '+' character:
https://github.com/angular/angular/issues/18884#issuecomment-488360438
