### ISSUE TITLE
ngOnChanges() doesn't get called when an @Input() property is changed

### ISSUE THREAD

**Issue by sivakumar414ram** [angular/angular#22066]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

i have 5 @input() properties , Generally ngOnChanges() change will get call if any one input changed out of five inputs. But in my case out of 5, for only one @input ngOnChanges() is not getting called .

I'm trying to change a child's @input() property using an @ViewChild instance in the parent,
and the method ngOnChanges() doesn't get called.

Changing "processPage" in the parent will trigger an ngOnChanges() on the child.

Also, if I update "this.ParentComponent.pageSize" from the parent, the change will appear in DOM,
but ngOnChanges() won't get called.

## Expected behavior

The method ngOnChanges() should be called every time when a property is changed, and I should be able to get the changes.
If this shouldn't be possible then angular should throw an error, because silent fail isn't an accepted behaviour.

## Minimal reproduction of the problem with instructions

@component({
selector: 'my-app',
template: <div class="wrapper"> <my-compoennt [page]="processPage"></my-compoennt></div>,
providers: [AppService]
})

export class AppComponent {

@ViewChild(PaginationComponent) processListPagination: PaginationComponent;
 
processPage = 0;
public currentVal : string;

    onNextPage(pagination: Pagination): void {
        this.processPage = this.processListPagination.current - 1;
    }

}

@component({
selector: 'my-component',
template: <div class="sidebar"> Current child's value: {{testVal}} </div>,
})

export class MyComponent implements OnInit, OnChanges, DoCheck {

@Input() id : number;
@Input() size : number;
@Input() page : number;

public ngOnChanges(): void{
    console.log(this.page);
}
}

## Environment

<pre><code>
Angular version: X.Y.Z
 5.0.1

Browser:
- [x ] Chrome (desktop) version XX
- [] Chrome (Android) version XX
- [] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX   8.9.1
- Platform:   Linux

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@sivakumar414ram ... it is expected that you provide a simple reproduction demo of the problem using http://stackblitz.com.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
