### ISSUE TITLE
Patching Element.prototype.addEventListener breaks Angular 2 apps

### ISSUE THREAD

**Issue by skjindal93** [angular/angular#22073]
I have an Angular 2 app https://github.com/DanWahlin/Angular-JumpStart. I tried to patch Element.prototype.addEventListener for some of my use case.

Here is the patch:

```
var origLis = Element.prototype.addEventListener;
Element.prototype.addEventListener = function(type, handler, useCapture) {
    console.log("Added");
    return origLis.apply(this, arguments);
}
```

If I patch **Element.prototype.addEventListener**, it breaks the Angular 2 app. No resources/XHRs are being sent in the app. I tried this on many Angular 2 apps. But, same result. There are no errors in the console.

I can't patch **EventTarget.prototype.addEventListener**, because that does not work on IE10 and IE11, as EventTarget is not defined there

**Comment by robwormald** [comment]
This is generally a bad idea - patching built-ins will almost always lead to strange behavior, and in this case you're likely breaking ZoneJS. See https://www.nczonline.net/blog/2010/03/02/maintainable-javascript-dont-modify-objects-you-down-own/ for some more details on why this is not something we're going to support.

**Comment by skjindal93** [comment]
But, what if I want to track user clicks, and things like that? I will have to monkey patch these methods, right?
