### ISSUE TITLE
unify $DARTIUM and $DARTIUM_BIN

### ISSUE THREAD

**Issue by goderbauer** [angular/angular#2207]
In addition to defining $DARTIUM_BIN as described in DEVELOPER.md I also had to execute "export DARTIUM=$DARTIUM_BIN" to execute the tests. Might be worth to unify the usage of those two environment variables in the test setup of angular.

**Comment by naomiblack** [comment]
A PR would be welcome if anyone has time to contribute it...

**Comment by pkozlowski-opensource** [comment]
@goderbauer Hmm, I must say that I didn't experience this issue on any of the environments I'm using (Linux, OSX, Win from time to time). Could you share more details on your environment and setup?

What is the exact task that needs the described setting? What is the error message that you were getting?

**Comment by mlaval** [comment]
With https://github.com/angular/angular/commit/65769699b0ce98677af3a75e015319a8a73cc82d, `DARTIUM_BIN` should be enough, isn't it?

**Comment by pkozlowski-opensource** [comment]
@mlaval I think so. @goderbauer I'm going to close this one, happy to re-open if you've got still issues and could provide more details.
