### ISSUE TITLE
Remove or document core/src/animation/dsl.ts symlink

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#22079]
In 3e51a1998304ab6a15e5bea6bc66e7a8c636a8ad we introduced https://github.com/angular/angular/blob/master/packages/core/src/animation/dsl.ts as a symlink.

I don't recall the reason for this, but I think it had to do something with code reuse or backwards compatibility.

This symlink is causing issues for the bazel build and is generally very confusing. Could we remove it?

If we can't, can we document what needs to be done for this symlink to be removed in this issue?

**Comment by matsko** [comment]
Fixed with https://github.com/angular/angular/commit/f5a98f41fe2cc1d2fd93818cbff165498bbd8c9d
