### ISSUE TITLE
docs: explain what information is required by a breaking changes commit 

### ISSUE THREAD

**Issue by Toxicable** [angular/angular#22076]
## I'm submitting a...

<pre><code>[x] Documentation issue or request</code></pre>

As per comment here we should have some Developer docs on how breaking changes commit messages should be formatted
https://github.com/angular/angular/pull/20212#pullrequestreview-94873214

**Comment by gkalpak** [comment]
[This document][1] (which is linked to from `CONTRIBUTING.md`) has info and examples.
Do you think we should enhance it or do a better job surfacing it.

[1]: https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#heading=h.gbbngquhe0qa

**Comment by Toxicable** [comment]
@gkalpak Ah! I missed that doc, thanks for that
Maybe moving some of whats in there into `CONTRIBUTING.md` would be great

**Comment by jenniferfell** [comment]
docsarea=contributing

**Comment by aikidave** [comment]
Closing as this section in CONTRIBUTING.md seems to cover this! https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-footer
