### ISSUE TITLE
A fix for angular/angular#21080 is not available in the angular cli github code yet

### ISSUE THREAD

**Issue by ujjainimukherjee** [angular/angular#22071]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
There is a current fix in angular cli which is the following
fix(@ngtools/webpack): suppress warnings for overwriting files in tsc
(https://github.com/hansl/angular-cli/commit/a61f5a6041a8499161094a7680fbdb8ec43b17d7)
This works if I manually change code on my local code base. But if I download the latest version of angular cli, this change is not there

## Expected behavior
There is a current fix in angular cli which is the following
fix(@ngtools/webpack): suppress warnings for overwriting files in tsc
(https://github.com/hansl/angular-cli/commit/a61f5a6041a8499161094a7680fbdb8ec43b17d7)
This change should be in the official angular-cli version. Instead it is only in the https://github.com/hansl/angular-cli fork

## Minimal reproduction of the problem with instructions
- Plz install the latest angular-cli
- If we go to this file - node_modules/@ngtools/webpack/src/angular_compiler_plugin.js
- After this line - this._compilerOptions.outDir = '';
- As per the above fix  - We should expect this line -this._compilerOptions.suppressOutputPathCheck = true;
- But this line is absent

## What is the motivation / use case for changing the behavior?
In our current project - we have to include external javascript files (with .js extension)

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.4.0
- Platform:  Mac

**Comment by vicb** [comment]
@ujjainimukherjee as you can the commit you linked to has been merged. You can track the CLI changelog to know when it will be released. If you need more information please re-open the issue on https://github.com/angular/angular-cli/issues

Thanks.
