### ISSUE TITLE
aio: redirect https://angular.io/styleguide -> guide/styleguide

### ISSUE THREAD

**Issue by wardbell** [angular/angular#22078]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

This old v1, once valid styleguide URL, [https://angular.io/styleguide](https://angular.io/styleguide), now is a 404.

Minko Gechev tells me

>This breaks a lot of releases of codelyzer + the printed content of my book.

It used to redirect to its current location, [https://angular.io/guide/styleguide](https://angular.io/guide/styleguide).

Redirects were recently updated. Maybe there is a much bigger regression here?

## Expected behavior

* Should redirect.
* Should confirm that our old v1 to v2 redirects are still working.

## Minimal reproduction of the problem with instructions

Go to [https://angular.io/styleguide](https://angular.io/styleguide)

**Comment by IgorMinar** [comment]
// @mgechev

**Comment by petebacondarwin** [comment]
I'll fix this today
