### ISSUE TITLE
Configure service worker not to present stale content for frequently visited landing pages

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#22080]
Repro:

- as a user I navigate to https://angular.io and stick around enough for sw to catch everything
- Angular developers push an update to the angular.io homepage (e.g. new release announcement)
- as a user I go to https://blog.angular.io and find a release announcement, I click on a link to https://angular.io/events that is mentioned in the blog post because of new events coming up

Expected result:
- I see the updated version of https://angular.io/events

Current result:
- I see an outdated version of https://angular.io/events
- If I wait long enough for sw to update and reload https://angular.io/events I see the new content

The tricky thing about this is that we shouldn't do it in a way where it's going to affect our TTI.

The new sw has a feature where we can optimize for freshness, but that affects TTI.

Maybe we should consider a full page reload if we detect that the currently displayed content is stale? I'm not sure...

// @alxhub @StephenFluin

**Comment by gkalpak** [comment]
Right now we check for available updates every 6 hours I think. Once an update has been downloaded, the new content should be displayed on new navigations. So, theoretically, the content (after a navigation - either in-app or new page) should not be staler than that.

I can't think of another way to ensure freshness without affecting the TTI.

Wait! What if we show a snackbar when an update is available prompting the user to reload the page :grin:
<sub>(déjà vu)</sub>

**Comment by rjsteinert** [comment]
> What if we show a snackbar when an update is available prompting the user to reload the page 

That's precisely what I'm looking to do in my app. Is there docs on how to do this? An event we can listen for perhaps? Bonus points for an event for when an update is installing so the user doesn't navigate away and brick their application.

**Comment by gkalpak** [comment]
This is what angular.io used to do, but people where finding it annoying 🤷‍♂️ 

I could link you to the code, but it used an old version of `@angular/service-worker`, so that wouldn't be very useful to you.

With the latest `@angular/service-worker`, you should use the [SwUpdate][1] service (see also [here][2] for more info).

[1]: https://angular.io/api/service-worker/SwUpdate
[2]: https://angular.io/guide/service-worker-communications#swupdate-service

**Comment by Ploppy3** [comment]
It's actually quite simple: 
```
constructor(
  update: SwUpdate,
) {
  update.available.subscribe(event => {
    // show your snackbar
  })
}
```

**Comment by jessicajaniuk** [comment]
@gkalpak Is this still an issue?
