### ISSUE TITLE
Expose HttpInterceptorHandler as public API

### ISSUE THREAD

**Issue by sinedied** [angular/angular#22083]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
`HttpInterceptorHandler` from `@angular/common/http/src/interceptor` is not exposed as a public API.

## Expected behavior
Expose `HttpInterceptorHandler` in `@angular/common/http` exported APIs.

## What is the motivation / use case for changing the behavior?
Currently because https://github.com/angular/angular/issues/18155 is not implemented, the only way to have per-request configuration (ie configurable or dynamic interceptors) is to extend `HttpClient`. To dynamically chain new interceptors for specific requests, we have to use an `HttpInterceptorHandler` class like how it's done for static interceptors added with `HTTP_INTERCEPTORS` token.

As I do not want to use a private API, I have to duplicate the `HttpInterceptorHandler` code which is silly as it's already there, just not exposed. As long a you want to tinker with interceptors yourself, this class is needed so it would makes sense to expose it publicly.

## Environment

<pre><code>
Angular version: 5.2.2

</code>
</pre>

**Comment by AhnpGit** [comment]
hi @sinedied I just ran into http interceptor codes from my colleague and I think this would be nice to allow Angular support dynamic interceptors.

**Comment by alxhub** [comment]
Unfortunately, we don't intend to support `HttpInterceptorHandler` as public API for the time being. Nor is extending `HttpClient` supported or recommended - it could break at any time (for example code doing this was probably broken by https://github.com/angular/angular/commit/120bdeecdc9ecb3f760ed38547991e0b87bbaba4 already).

**Comment by sinedied** [comment]
@alxhub I understand your position, though due to https://github.com/angular/angular/issues/18155 we have no other way around than extending `HttpClient`, which we also would like to avoid.

In the lack of https://github.com/angular/angular/issues/18155, do you have any recommendation on how we can apply per-request configuration without extending `HttpClient` then?

It was really easy to do with the deprecated `Http` API, but now it's really problematic. My best shot at it was https://gist.github.com/sinedied/46f9b3cf5cbd04fa452d1446edc6006d to keep standard `HttpInterceptor` and dynamically use them using an extended `HttpClient` class injected in place of the default one, but it still feel hacking around the issue.
