### ISSUE TITLE
docs: Style Guide's "Directive selectors" doesn't mention prefixing selectors

### ISSUE THREAD

**Issue by shaungrady** [angular/angular#22081]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In the [Directive selectors](https://angular.io/guide/styleguide#directive-selectors) section of the **Style Guide**, nothing is mentioned about prefixing selectors for name spacing.

_However_, in the **Guide** for [Write a structural directive](https://angular.io/guide/structural-directives#write-a-structural-directive), in the second to last paragraph, you can find the following:

> The directive _attribute name_ should be spelled in _lowerCamelCase_ and begin with a prefix. Don't use `ng`. That prefix belongs to Angular. Pick something short that fits you or your company. In this example, the prefix is `app`.

This is not mentioned in the style guide. Worse, Angular's directives seem to _only be prefixed_ with `ng` when it's a "single word" directive—`ngForm`—but they are not prefixed with they are multiple words—`formControlName`.

## Expected behavior

The Style Guide should make a recommendation about prefixing or not prefixing directive attribute names. I would be more than happy to submit a PR to clarify the issue in the Style Guide once I receive direction. 👍

**Comment by kapunahelewong** [comment]
@shaungrady thanks for this (and your awesome tweet!). Let me know when you're ready and I'll help you through the contributing process if needed. So excited!

**Comment by shaungrady** [comment]
I'm ready! So, the first question is, what's the recommendation the style guide should make? Should all directives be prefixed the same way that components are?

**Comment by Yerkon** [comment]
`Should all directives be prefixed the same way that components are?`

Right, components/directives should be prefixed

**Comment by Yerkon** [comment]
> In the Directive selectors section of the Style Guide, nothing is mentioned about prefixing selectors for name spacing.

https://angular.io/guide/styleguide#custom-prefix-for-components
https://angular.io/guide/styleguide#custom-prefix-for-directives

**Comment by shaungrady** [comment]
@Yerkon Ohhhh, I see. It's confusing that the bit about custom prefixes for directives doesn't appear immediately after the **Directive selectors** section, but is instead bisected by the **Custom prefix for components**. I was also expecting that **Directive selectors** should cover prefixes, since prefixes are part of the selector.

Maybe **Custom prefix for directives** could be moved to the **Directive selectors** section, and **Custom prefix for components** could be renamed to **Component selectors**? Would be a bit more consistent that way.

**Comment by kapunahelewong** [comment]
Thanks @Yerkon 👍 

@shaungrady good catch on the order. I've read that style guide several times and never caught that! The section on **Custom prefix for components** looks like it should be down in the **Components** section. What do you think about moving it down there after **Component Selector names**? That would put the directives related sections together, and the current naming would make more sense. What do you think?

**Comment by Yerkon** [comment]
@kapunahelewong, @shaungrady, [Directives](https://angular.io/guide/styleguide#directives) section doesn't have `Directive selector names` section. 
If you look, [Directive selectors](https://angular.io/guide/styleguide#directive-selectors) allocated in [Naming](https://angular.io/guide/styleguide#naming) section, thats why  [Component selector names](https://angular.io/guide/styleguide#component-selector-names) can be moved to [Naming](https://angular.io/guide/styleguide#naming) section(all about naming here)

**Comment by kapunahelewong** [comment]
Good point @Yerkon. The Naming section makes more sense. @shaungrady you could even reference it if made sense from the components section.

**Comment by shaungrady** [comment]
So if I'm understanding correctly, this is how it should be reorganized:

> #### Naming
> - ...
> - Component selectors
> - Component custom prefix
> - Directive selectors
> - Directive custom prefix
> - ...

> ...

> #### Components
> - ~Component selector names~
> - ...

In **Naming**, I think it makes sense for the Component section to appear before the Directive section as components are more common. Also, renaming **Custom prefix for components** to **Component custom prefix** keeps it visually connected to the preceding **Component selectors**.

If that sounds good I'll submit a PR with those changes. 😄

**Comment by kapunahelewong** [comment]
Hey @shaungrady yes! I agree completely on both points. If you have any questions about editing the files, just let me know.

@jenniferfell fyi^^ @shaungrady would like to contribute to the docs :)

@shaungrady, @jenniferfell is our project manager for the docs and can help you navigate the process of approving and landing your PR.

**Comment by shaungrady** [comment]
I do have one question: I noticed the style numbers increment nicely—`Style 02-06` to `Style 02-07`—how do I handle that while reorganizing sections? I'm sure changing them has broader impact. Do I keep their original numbers, and just use the next available number for the new section (Component custom prefix)?

**Comment by kapunahelewong** [comment]
That's a good question, @shaungrady. 

Hey, @petebacondarwin, could you advise us as to the numbering in the styleguide? Now that @shaungrady brings it up, I think those links and numbers are distinct for a reason, but my memory is hazy on it.

**Comment by petebacondarwin** [comment]
I have to admit I am not sure. I would imagine that a number people (and maybe tools) link through to these styles, so perhaps the numbering should stay stable.

**Comment by shaungrady** [comment]
Yeah, can confirm that `Codelyzer` does link to styles by their number.

**Comment by petebacondarwin** [comment]
Also @johnpapa and @wardbell have had a lot to do with this historically and might have a view.

**Comment by shaungrady** [comment]
Should I just open the PR with all the style numbers left as they were?

**Comment by petebacondarwin** [comment]
@shaungrady - I think that is the safest approach.
