### ISSUE TITLE
String couldn't be converted to number by prefix + in the interpolation expression

### ISSUE THREAD

**Issue by deart1mer** [angular/angular#22089]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In template, {{ +'1' +  2 }} will get 12.

## Expected behavior

+'1' +  2 should get 3 same as JavaScript expression.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-e3oqrr?file=app%2Fapp.component.html
## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
https://github.com/angular/angular/blob/3f5a3d6ea1d20d8d6d662d0912a875b68db5c3b1/packages/compiler/src/expression_parser/parser.ts#L478-L480

This should be blamed for, the parser just skips `+` prefix.

**Comment by deart1mer** [comment]
@trotyl Thanks for taking your time to view the source code. 
Why skip the `+` prefix? This is very convenient for data that can not be determined as string or number. Especially get data from asynchronous request.

**Comment by trotyl** [comment]
@deart1mer I'm not saying it's by design, the logic was implemented in [very early stage](https://github.com/angular/angular/commit/965fa1a9859a69bcfb7c796e34231348043a3ed7) (3 years ago), should be a legacy mistake.

By convention the founder should be given the opportunity for raising a fix (PR) if he/she wants and issue not being critical/urgent. So that's the tip for making changes.

And it would be totally OK for just waiting for a fix. 😃

**Comment by trotyl** [comment]
PR raised since no reply from OP, suggested tags: `type: bug/fix`, `comp: core & compiler`, `effort1: easy (hours)`, `freq1: low`, `severity2: inconvenient`, `workaround1: obvious`.
