### ISSUE TITLE
Using extJs inside angular4. Geting context releated issue

### ISSUE THREAD

**Issue by abhimanyu1717** [angular/angular#22092]
import { Component } from '@angular/core';
        @Component({
          selector: 'faxEmail',
          templateUrl:'./fax.email.comp.html',
           providers: [HomeService,CommonService],
        })
        export class FaxEmail {
        
        
         ngOnInit(){
            /* this is simple JavaScript function */
        		  var sayHello=function(){
        			 alert('sayHello');
        			 this.hello=function(){/*this function i am trying to call*/
        				 alert('hello');
        			 }
        			 this.hello();
    /*Here i am geting issue because this is using the angular context.*/
        		  }
        		  sayHello();
         }
        
        }

/*same scenario i am geting when using ext inside angular how to solve this .?*/

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
