### ISSUE TITLE
Unnecessary route change everytime that a runtime error occurs.

### ISSUE THREAD

**Issue by iget-master** [angular/angular#22098]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Using `ng serve`, when using a Lazy Loaded component with router, everytime that an error occurs, angular redirects to the root directory making difficult to development since during the development cycle this occurs many times (when you type to inject a service that isn't declared yet for example).

## Expected behavior

It should just show the runtime error without redirecting, allowing that when the error is fixed, the page is reloaded and just run fine!

## What is the motivation / use case for changing the behavior?
The motivation is to speed up the development process since this unnecessary redirection consumes 20~30 seconds every time that it occurs.

## Environment

<pre><code>
Angular version: 5.2.4

Browser:
- [x] Chrome (desktop) version `Versão 62.0.3202.62 (Versão oficial) beta 64 bits`
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.4
- Platform:  Ubuntu 17.10

Others:

</code></pre>

**Comment by mhevery** [comment]
Thank you for submitting the issue. All issues require a [plunker](https://plnkr.co/) which demonstrates the problem and how to reproduce it. Please re-open the issue or create a new issue once you have a reproducible use case.

We are sorry that we are so aggressive on closing the issues. We are overwhelmed with the number of issues we get, and so we only have time to look at the ones which are easy for us to reproduce.

**Comment by iget-master** [comment]
I'll provide a example as soon as possible.
