### ISSUE TITLE
Bootstrap Framework Not Adding to App

### ISSUE THREAD

**Issue by treasure1210** [angular/angular#22101]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
After installing bootstrap via npm, the styles are not loading into the angular app. Bootstrap 4.0.0 is installed and listed as a dependency (also tried with 3.3.7), but I cannot use the Bootstrap classes to style the app.

## Expected behavior
Bootstrap classes and styles should work when installed via npm. This works fine for CLI 1.6.7 and Angular 5.2.3, but not CLI 1.6.7 and Angular 5.2.4.

## Minimal reproduction of the problem with instructions
<pre><code>
ng new project
cd project
npm install bootstrap
</code></pre>

## Environment
<pre><code>
Angular version: 5.2.4

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by ericmartinezr** [comment]
Would you mind reporting this issue in angular-cli's repo? https://github.com/angular/angular-cli 👍
