### ISSUE TITLE
core.js:1440 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by yaelya** [angular/angular#22102]
### I got this error:

core.js:1440 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'style' of null
TypeError: Cannot read property 'style' of null
    at LoginComponent.eval (login.component.ts:39)
    at step (login.component.ts:41)
    at Object.eval [as next] (login.component.ts:22)
    at eval (login.component.ts:16)
    at new ZoneAwarePromise (zone.js:887)
    at __awaiter (login.component.ts:12)
    at LoginComponent.loginWithGoogle (login.component.ts:26)
    at Object.eval [as handleEvent] (LoginComponent.html:21)
    at handleEvent (core.js:13532)
    at callWithDebugContext (core.js:15041)
    at LoginComponent.eval (login.component.ts:39)
    at step (login.component.ts:41)
    at Object.eval [as next] (login.component.ts:22)
    at eval (login.component.ts:16)
    at new ZoneAwarePromise (zone.js:887)
    at __awaiter (login.component.ts:12)
    at LoginComponent.loginWithGoogle (login.component.ts:26)
    at Object.eval [as handleEvent] (LoginComponent.html:21)
    at handleEvent (core.js:13532)
    at callWithDebugContext (core.js:15041)
    at resolvePromise (zone.js:821)
    at new ZoneAwarePromise (zone.js:890)
    at __awaiter (login.component.ts:12)
    at LoginComponent.loginWithGoogle (login.component.ts:26)
    at Object.eval [as handleEvent] (LoginComponent.html:21)
    at handleEvent (core.js:13532)
    at callWithDebugContext (core.js:15041)
    at Object.debugHandleEvent [as handleEvent] (core.js:14628)
    at dispatchEvent (core.js:9944)
    at eval (core.js:10569)
## in the html code:
<div id="recaptcha-container">
	
</div>
<div class="container">
		<div class="login-box animated fadeInUp">

			<div class="box-header">
				<h2>Welcome {{authService.nameAndFname}}</h2>
			</div>
			<form class="form" action="/action_page">
	
			<input type="text" [(ngModel)]="UserName" onsubmit="myFunction()" name="UserName"  pattern="[A-Za-z]{}" placeholder="UserName"  >
          <div id="city" style="color:red; display:none">
			  The user name is required.
			</div>
		  
			<input type="text" [(ngModel)]="phone" name="phone" placeholder="Phone number">
          <div id="city" style="color:red; display:none">
				The phone is required.
			  </div>
			<button (click)=loginWithGoogle() type="Submit"  class="Submit" id="login-button">Login</button>
	
		</form>
		</div>
	  <img class="footer" src="https://firebasestorage.googleapis.com/v0/b/imagetalk-76424.appspot.com/o/%D7%9C%D7%95%D7%92%D7%95.png?alt=media&token=549b55ef-4d5b-4221-903d-2e4ed642ffde">
	</div>
## in my ts code:
  async loginWithGoogle() {
    if(this.UserName != "" && this.phone != "")
    {
      this.firebaseService.updateUser({username: this.UserName, phone :this.phone})
      await this.authService.keepUser({username: this.UserName, phone :this.phone})
    }
    else{
   if(this.UserName==""||this.phone=="")
      {
       document.getElementById("UserName")
       document.getElementById("phone")
       if(this.UserName=="")
        {
           document.getElementById(this.UserName).style.display='block';
        }
       else{
           document.getElementById(this.UserName).style.display='none';
          }

       if(this.phone=="")
        {
          document.getElementById("phone").style.display='block';
        }
         else{
           document.getElementById("UserName").style.display='none';

          }
       }
      }
    this.router.navigate(["home"])
  }

## this is my package.json:
{
  "name": "imagetalke",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.1.2",
    "@angular/cdk": "^5.0.0-rc0",
    "@angular/cli": "^1.5.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@angular/material": "^5.0.0-rc0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "angular-calendar": "^0.23.2",
    "angular-material": "^1.1.5",
    "angularfire2": "^5.0.0-rc.5",
    "error-context": "^1.0.1",
    "firebase": "4.8.0",
    "groc": "^0.8.0",
    "then-request": "^4.1.0"
  },
  "devDependencies": {
    "@angular/cli": "1.3.1",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "rm-npm": "0.0.9",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "^2.0.2"
  }
}

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
