### ISSUE TITLE
The type definition of AsyncPipe.transform is overly strict

### ISSUE THREAD

**Issue by levilindsey** [angular/angular#22100]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When using type checking in our templates, the `async` pipe will not accept values of type `Observable<boolean> | undefined`. Instead, it has overloads defined to accept `undefined` or `Observable<T>`, but not `Observable<T> | undefined`.

Note that when declaring a method overload, the implementation signature is ignored for typing calls. It just needs to be wider than the overload declarations.
https://github.com/angular/angular/blob/5.2.4/packages/common/src/pipes/async_pipe.ts#L90

Here is the reported error:
"TS100: Argument of type 'Observable<boolean> | undefined' is not assignable to parameter of type 'Promise<{}>'"

## Expected behavior

We should be able to pass nullable values to the `async` pipe without generating type errors.

## Minimal reproduction of the problem with instructions

- Enable template type checking.
- Define a field of type `Observable|undefined`.
- Pass that field to the `async` pipe in a template.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by buu700** [comment]
Tagging onto this, I was surprised to discover a day or two ago that passing a non-promise/observable value into the async pipe like `'a string' | async` causes a run-time error. I would expect it to behave more like the `await` keyword and accept any value.

**Comment by trotyl** [comment]
Fixed by #22169 already, missing `fixes/closes` statement.

**Comment by pkozlowski-opensource** [comment]
Should be fixed by #22169
