### ISSUE TITLE
Docs: outdated developer.md

### ISSUE THREAD

**Issue by Yerkon** [angular/angular#22109]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

https://github.com/angular/angular/blob/master/docs/DEVELOPER.md
This developer guide is outdated. When building angular with `./build.sh`
* bower package manager is missing. 
* rsync command not found... I installed rsync, added to environment path. But after that, another error throws... I couldn't solved it. 

## Expected behavior

Update document to actual:
* Inlcude `bower` to Prerequisite
* Correct **rsync** 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4
- Platform: Windows 10 x64  

Others:

</code></pre>

**Comment by Splaktar** [comment]
@gkalpak @jenniferfell This appears to have been resolved sometime in the last year.

**Comment by aikidave** [comment]
Closing as @Splaktar indicates it was resolved in 2019.
