### ISSUE TITLE
The Angular router erases OAuth authentication results

### ISSUE THREAD

**Issue by kputh** [angular/angular#22119]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When I use the address of my SPA as redirect URL for OAuth 2.0, Angular using _HashLocationStrategy_ will erase the authentication information in the hash from the URI before any part of the Angular app can process it.

## Expected behavior

There should be a way to configure the Router or individual Routes to not rewrite URIs, or a routing event that fires before the URI is rewritten.

## Minimal reproduction of the problem with instructions

1. Go to https://run.plnkr.co/plunks/x6NH4i6SWqPLA2A6jhY4/#access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik5HVEZ2ZEstZnl0aEV1Q&token_type=Bearer&expires_in=3599&scope="90c0fe63-bcf2-44d5-8fb7-b8bbc0b29dc6 offline_access"&id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik5HVEZ2ZEstZnl0aEV1Q&state=arbitrary_data_you_sent_earlier
2. Compare the URI in the link with the URI in your browser. Examine the JavaScript log for routing events.

## What is the motivation / use case for changing the behavior?

OAuth 2.0 is a widely-used protocol for authorization. SPAs use implicit grants, and the default for these is to append authentification results to the URI as a fragment. (See link above.) Angular must offer an Angular app a way to evaluate the original URI fragment in order for OAuth to work.

## Environment

<pre><code>
Angular version: 5.2.4

Browser:
- [x] Chrome (desktop) version 64
- [?] Chrome (Android)
- [?] Chrome (iOS)
- [x] Firefox version 58
- [?] Safari (desktop)
- [?] Safari (iOS)
- [?] IE
- [?] Edge
 </code></pre>

**Comment by trotyl** [comment]
The URL you posted is invalid, so got 404 and then being redirected, try:

```
https://run.plnkr.co/plunks/x6NH4i6SWqPLA2A6jhY4/#/superheroes?access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik5HVEZ2ZEstZnl0aEV1Q&token_type=Bearer&expires_in=3599&scope=%2290c0fe63-bcf2-44d5-8fb7-b8bbc0b29dc6%20offline_access%22&id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik5HVEZ2ZEstZnl0aEV1Q&state=arbitrary_data_you_sent_earlier
```

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

<hr>

It looks like the only difference here is the `"` and ` ` have been percent encoded. This is as-expected, and can be "fixed" by using `decodeURI(url)`.

**Comment by kputh** [comment]
I have the feeling that you are observing a different behavior than me. When I use the original URL, it is shortened to `https://run.plnkr.co/plunks/x6NH4i6SWqPLA2A6jhY4/#/access_token`. I see this behavior across different browsers and operation systems.

The URL from @trotyl works, because the authentication result is encoded differently. This different encoding is supported by OAuth, but it is a different variant of the standard which is not meant for web applications, and may not be supported by JavaScript authentication libraries.

**Comment by trotyl** [comment]
> because the authentication result is encoded differently.

The encoding has been leaved intact, only different in path, please try have an inline diff. But please note that browser itself would perform escaping before the navigation happens.

**Comment by kputh** [comment]
Sorry, I should not have used the word encoding. I'm not talking about character encoding. I meant that you moved the authentication result from the fragment to the query.

**Comment by trotyl** [comment]
OAuth parameters themselves are just normal query parameters.
