### ISSUE TITLE
Uncaught TypeError: StaticInjectorError(Platform: core)[t]:    Cannot set property '_injector' of undefined

### ISSUE THREAD

**Issue by kasimkha** [angular/angular#22118]
## I'm submitting a...
The source contains a rest api call as well as global variable reference also I have used only bootstrap css and not saved jquery since i m not using bootstrap.js
i am getting prod build files after executing(ng build -prod) and everying is working fine on my local server. However when the same i am merging into jsp code on some other server,I am getting error "Uncaught TypeError: StaticInjectorError(Platform: core)[t]: 
  Cannot set property '_injector' of undefined"

## Expected behavior
There should be no error

## Minimal reproduction of the problem with instructions
create ng build -prod and merge the code in another jsp

## Environment
"dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "bootstrap": "^3.3.7",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.2",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.8",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }

Angular version: 5

Browser:
NA
 
For Tooling issues:
- Node version: v9.3.0
- Platform:  Windows

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by kasimkha** [comment]
Done
