### ISSUE TITLE
Animation events in HostListeners aren't supported in Angular Elements (yet?)

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#22117]
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Support request 

Could be considered a bug, but also a feature. You decide 😄 

## Current behavior

Angular component with built-in animations using Angular animation events in components host listeners aren't supported. For example Assuming a component with animation events like this:

```
host: {
 '(@transform)': 'doSomethign',
 '(@transform.start)': 'doSomethignElse'
}
```
Won't be triggered by the resulting Angular Element of this component. While native host listener will work. E.g.

```
host: {
  '(keyup)': 'doSomethignElse'
}
```
The reason why this isn't working yet, is because there's no Custom Element equivalent of Angular's `@foo` events.

## Expected behavior

Not sure whether I'd expect this to be magically handled by Angular Elements, nor am I sure this is supposed to be supported eventually, but it definitely makes some components not work the way as expected when running them as Custom Elements. That's why I'm bringing this up here.

## What is the motivation / use case for changing the behavior?

We might want Angular Elements to support Angular Animations as well. This affects many of Angular Material's components.

**Comment by robwormald** [comment]
this is resolved in the latest builds, see https://github.com/andrewseguin/elements-example/blob/master/src/app/popup.component.ts

**Comment by PascalPrecht** [comment]
@robwormald that's cool!

Do you have a commit that solves this that we can reference here? I can then close this issue.

**Comment by robwormald** [comment]
See https://github.com/angular/angular/pull/22413

**Comment by PascalPrecht** [comment]
I'm gonna close this one as fixed.

**Comment by talamaska** [comment]
@robwormald Actually when i try to bind via the @HostListener like so
```
  @HostBinding('@buttonAnimation') get buttonAnimation() {
    return this.buttonState;
  }
  @HostListener('@buttonAnimation.done') buttonAnimationDone($event) {
    console.log($event);
  }
```
the done event is not triggered at all

**Comment by andrewtw** [comment]
@talamaska 
The `HostListener` should be given the `args` to output the data, eg. 
```
	@HostListener('@animate.done', ['$event'])
	animationDone(event: AnimationEvent) {
		// Do something
    }
```
This should work.

**Comment by talamaska** [comment]
@andrewtw thanks, will try.
