### ISSUE TITLE
ngModelChange called when the input lose focus (type number 

### ISSUE THREAD

**Issue by houssemFat-DDF** [angular/angular#22115]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When using the `ngModel` and `ngModelChange` in an input with type `number`, the function `ngModelChange` called when value changes and when the input loses the focus.

## Expected behavior
Using the `ngModel` and `ngModelChange` in an input with type `number` behave like a string input type.

## Minimal reproduction of the problem with instructions
When using the `ngModelChange` with input (default string type ), the `ngModelChange`  function called one time. But when we change the type to `number`, the function called when the input loses the focus also.

__Component__
```
 /**
 *  ngModelChange callback 
 */
  test_event(value) {
    console.log(value);
  }
```
__html__
* Event called one time, even if the input lose the focus
```
 <input [(ngModel)]="test_counter"  (ngModelChange)="test_event($event)">
```
* event called when input lose the focus
```
 <input [(ngModel)]="test_counter" type="number"  (ngModelChange)="test_event($event)">
```

## Environment

<pre><code>
Angular version: 4.4.6

Browser:
- [x] Chrome (desktop) version 64.0.3282.140
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.5
- Platform:  Windows  

Others:

</code></pre>

**Comment by trotyl** [comment]
![image](https://user-images.githubusercontent.com/6059170/36025688-e225c274-0dce-11e8-9ed8-a4dffa25f85a.png)

[Cannot reproduce](https://stackblitz.com/edit/angular-aupjkt?file=app%2Fapp.component.html), please provide a repro (just based on that).

**Comment by trotyl** [comment]
![snip20180209_7](https://user-images.githubusercontent.com/6059170/36025818-71c3fa7c-0dcf-11e8-9b3a-d5a0302b2a98.png)

[Cannot reproduce](https://stackblitz.com/edit/angular-aupjkt?file=app%2Fapp.component.html), please provide a valid repro.

**Comment by houssemFat-DDF** [comment]
@trotyl Thank you .
I Tried to edit and click out the input of type `number`, the lose of focus still fire the `ngModelChange`
__chrome__  
![image](https://user-images.githubusercontent.com/34309592/36034455-6be93a74-0db4-11e8-9c13-1b8174cfa397.png)

__firefox__

![image](https://user-images.githubusercontent.com/34309592/36034593-d689c27c-0db4-11e8-8b36-ee266a840557.png)

**Comment by trotyl** [comment]
In current implementation, `input[type=text]` will only listen for `input` event, while `input[type=number]` will listen to both `input` and `change` event.

**Comment by houssemFat-DDF** [comment]
Ok thank you, it seems that this is the standard way of listen to change/input event  https://developer.mozilla.org/en-US/docs/Web/Events/change .  So, am i asking for a feature or just the normal behaviour ? because if we have a ws call for ngChangeModel in input number it will be called the WS twice.

**Comment by trotyl** [comment]
I personally agree this should be improved, please waiting for Angular team to determine.

**Comment by kara** [comment]
Agree that this should be improved, but already tracking core problem here https://github.com/angular/angular/issues/12540
