### ISSUE TITLE
aio + docs/api: enforce use of required jsdoc tags

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#22138]
In https://github.com/angular/angular/pull/21874#issuecomment-363543097 @gkalpak suggested:

> I think might be a good idea to enforce all docs to have @whatItDoes and @description sections. I think it will encourage good practices. Right now, depending on whether there is @whatItDoes and/or @description section, some docs have something that looks like a description above the overview and no "Description" section, others have a "Description" section under "Overview" but nothing above, and others have both (I guess).
> 
> I think that by enforcing @whatItDoes and @description tags, we ensure that all docs look more consistent and API docs authors are forc...ehm...encouraged to provide both a short, high-level (possibly one-line) description as well as a longer, more thorough description.

**Comment by IgorMinar** [comment]
we should also enforce things like sentences should start with capital letter unless it's a keyword (monospaced) and end with dots.

also we should enforce that all free form text is formatted in a way where each sentence is located on a new line - this makes reviewing diffs so much easier and also doesn't force us to reformat big chunks of text to fit within a line length used for code.

**Comment by petebacondarwin** [comment]
We are already parsing the HTML into a [UNIST](https://github.com/syntax-tree/unist) tree via [rehype](https://github.com/rehypejs/rehype) in our post-processing phase of Dgeni. So we could use [retext](https://github.com/retextjs/retext) to parse the natural language itself into a [NLCST](https://github.com/syntax-tree/nlcst)

**Comment by petebacondarwin** [comment]
We now have basic rules in place.
