### ISSUE TITLE
aio + api/docs: doc-type badge placement

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#22130]
@gkalpak raised concerns about the placement of these badges in https://github.com/angular/angular/pull/21874#issuecomment-363543097:

![image](https://user-images.githubusercontent.com/15655/36047679-11808dca-0ddd-11e8-80bc-f109866c1148.png)

Having the [badges before the name](https://pr21874-14230fd.ngbuilds.io/api/forms/AbstractControl#abstractcontrol) is not ideal imo, because imo the main piece of information on that line is the name of the thing and it helps to have it at a predictable location. As it is now, depending on the number and texts of badges, the name may be end up further to the right.
I would put the badges either on the right or below the name (and make the smaller).

**Comment by sjtrimble** [comment]
Option 1: Moving them to the right of the class name as we had originally (I would recommend this)
![labels-alternative1](https://user-images.githubusercontent.com/2958442/36609778-e7ce8e40-1882-11e8-96a2-0a2f4609a014.png)

Option 2: Moving them underneath the header element
![labels-alternative2](https://user-images.githubusercontent.com/2958442/36609773-e3b9592a-1882-11e8-86f4-40bb4d38685a.png)


As always, we can explore additional options.

@IgorMinar

**Comment by jenniferfell** [comment]
The most important thing on the page is the title, and it's shouldn't move around. Left align. Don't move it. Larger slightly than the icons. 

I like both of Stefanie's options for icons. My preference is #1, because #2 pushes the "real" content of the API ref too low on the page, but I'm more flexible on this. 

Class Name [class] [experimental]

**Comment by sjtrimble** [comment]
@IgorMinar Can you confirm that you're good with option 1?
