### ISSUE TITLE
add special case for href to allow optionally not including the attribute

### ISSUE THREAD

**Issue by rkirov** [angular/angular#2213]
It appears that in browsers setting the href property to any value (even null) on an anchor element will stringify it (and sync with the attribute). Ex ``` a = document.createElement('a'); a.href = null; -> <a href="null">```

This means that ```<a [href]="null">``` will be decorated as a link for 'null'. For users that want to optionally decorate their links depending on presence of some data, the only option left is using `ng-if`.

Adding simple sugar to generate the following setter 
```
(el, val) => {
   if (val !== null) el.href = val;
   else el.removeAttribute('href');
}
```
will make href binding a lot more useful. The downside is having custom logic in the compiler. Thoughts?

**Comment by mhevery** [comment]
+1 for custom logic

**Comment by pkozlowski-opensource** [comment]
There is quite similar pb with null -> string conversion for `src` attributes being discussed here: https://github.com/angular/angular/issues/3765

While the pb is not _exactly_ the same, it also calls for a "special" setter mechanism for a given property

**Comment by zoechi** [comment]
https://github.com/angular/angular/issues/4150#issuecomment-163147652 seems related to convert `false` to `null` to get boolean attributes.

**Comment by naomiblack** [comment]
Will not fix.
