### ISSUE TITLE
aio + api/docs: header "link" icons overwrite other visual elements

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#22131]
In https://github.com/angular/angular/pull/21874#issuecomment-363543097 @gkalpak noted:

The .header-link that appears when hovering over the main doc heading is overlaid onto the badge.

![image](https://user-images.githubusercontent.com/15655/36047861-9f453ffc-0ddd-11e8-9f7d-299d799a85c5.png)

**Comment by petebacondarwin** [comment]
The .header-link that appears when hovering over the heading does not blend well with the card border.

![image](https://user-images.githubusercontent.com/15655/36047986-040ac740-0dde-11e8-8955-512bd5538c70.png)

**Comment by petebacondarwin** [comment]
![image](https://user-images.githubusercontent.com/15655/36048183-a341ef50-0dde-11e8-8095-4d34e10c542c.png)

**Comment by sjtrimble** [comment]
@IgorMinar thoughts?

**Page Title (API Name)**
Option 1: Remove anchor link
Option 2: Move labels to the right of title text
* I think option 2 will work best as the number of labels varies per API and will fix the anchor link and header `after` issues.

**Headings in Tables Formatting**
Option 1: Remove anchor link for API pages
Option 2: Shift text over for anchor to fit upon hover (see GIF below)
![anchorlink-shift](https://user-images.githubusercontent.com/2958442/36052640-66988996-0da3-11e8-9ceb-0d6ed36de660.gif)

We can consider other options if these don't work.

**Comment by gkalpak** [comment]
I generally find the ability to link to specific methods useful (I've used them extensively when answering AngularJS questions on StackOverflow, Gitter, etc :grin:).
I can live with having the name jump around as you hover over it, but that is not ideal.

How about we place the link icon on the right for headings inside tables? (This is the same we do for all headings on narrow screens btw.)

**Comment by sjtrimble** [comment]
Option 1: Moving them to the right of the class name as we had originally (I would recommend this)
![labels-alternative2](https://user-images.githubusercontent.com/2958442/36567494-73880f9a-17db-11e8-8b41-41757bf2670b.png)

Option 2: Moving them underneath the header element
![labels-alternative1](https://user-images.githubusercontent.com/2958442/36567495-73a1b49a-17db-11e8-9376-7c8b13c475d6.png)

As always, we can explore additional options.

**Comment by petebacondarwin** [comment]
Moving the badges only solves the problem for this instance. There are other situations where the heading is within a container and the link partially "falls outside" the container. E.g. https://github.com/angular/angular/issues/22131#issuecomment-364551433

**Comment by petebacondarwin** [comment]
@sjtrimble I think you meant your comment to go on #22130 ??

**Comment by sjtrimble** [comment]
@petebacondarwin I sure did. Should I delete and add over there? :/

**Comment by sjtrimble** [comment]
On this thread ... are we okay just removing the link visual for these API pages?

**Comment by petebacondarwin** [comment]
I am not OK with removing the link visual. Sorry :-)
I think we should simply move the anchor to "after" the heading (i.e. the RHS for L to R text).

**Comment by sjtrimble** [comment]
@petebacondarwin Fair enough, just want to make sure I understand the limitations :)
