### ISSUE TITLE
collect google analytics for subdomains (v4.angular.io, next.angular.io)

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#22142]
I believe that we currently collect analytics only for angular.io (the stable version), this means that we are missing out on seeing the traffic that goes to the next version and archive versions.

We should reconfigure analytics so that all of these domains are included in the reports:

- [x] next.angular.io
- [x] v2.angular.io
- [x] v4.angular.io
- [ ] v5.angular.io (will exist once v6 is out)

Also consider:
- [x] cli.angular.io
- [x] universal.angular.io
- [ ] material.angular.io

anything else?

Additional items:

- [ ] we'll also need to reconfigure analytics reports and views to display the domain name

Some helpful links:
- http://www.ericmobley.net/guide-to-tracking-multiple-subdomains-in-google-analytics/
- https://www.lunametrics.com/blog/2016/08/11/subdomain-tracking-google-analytics/
- ??? https://developers.google.com/analytics/devguides/collection/analyticsjs/cross-domain

**Comment by IgorMinar** [comment]
I started off by implementing the following GA filter:

<img width="695" alt="screen shot 2018-02-09 at 5 30 19 pm" src="https://user-images.githubusercontent.com/216296/36057086-f354bcf4-0dbe-11e8-83ec-d2331cd9ca76.png">
([source](http://www.ericmobley.net/guide-to-tracking-multiple-subdomains-in-google-analytics/))

so now we see domains in all reports:

<img width="658" alt="screen shot 2018-02-09 at 5 31 21 pm" src="https://user-images.githubusercontent.com/216296/36057097-11ba6f90-0dbf-11e8-938a-4aa531791ad8.png">

now we need to verify that we are collecting data from all the domains we care about. I can't seem to prove that we collect info from v*.angular.io and next.angular.io.

**Comment by gkalpak** [comment]
AFAICT, we should be tracking `next.angular.io` and `v*.angular.io` in the exact same way as `angular.io`. When I visit them, I see the same requests to `google-analytics` being sent out.
(Maybe nobody is visiting them :grin:)

**Comment by IgorMinar** [comment]
I tried to visit them when testing this and I didn't see any traffic from
those domains.

**Comment by IgorMinar** [comment]
alright.. I just checked on the traffic since Friday and we do see hits on various subdomains now that the filter is in place:

![screenshot 2018-02-11 at 11 56 20 pm](https://user-images.githubusercontent.com/216296/36087464-60bba554-0f87-11e8-9e9b-5f9e33d429a5.png)

it looks like we are now missing just the material subdomain..

**Comment by petebacondarwin** [comment]
I created https://github.com/angular/material2/issues/10022 to track this last site.

**Comment by josephperrott** [comment]
With the merge  of https://github.com/angular/material.angular.io/pull/401, [material.angular.io](https://material.angular.io/) will begin collecting analytics data with our next release.
