### ISSUE TITLE
Required edits of the layout of the official site

### ISSUE THREAD

**Issue by splincode** [angular/angular#22149]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

1. Apparently somewhere overdetermined styles?

![image](https://user-images.githubusercontent.com/12021443/36061976-30f3bc94-0e74-11e8-83c2-e6d4798db495.png)

2. Animation hangs very badly on weak computers
Examples: https://angular.io/guide/dependency-injection

Small screen (stable 59fps, execute 500ms) 

![](https://habrastorage.org/webt/gc/vs/od/gcvsoddtpyx-shygapjuvmit41k.gif)

Default screen (width 1280px, 29fps - 36fps - 46fps, execute 500ms)

![](https://habrastorage.org/webt/2j/r0/zu/2jr0zuxn383xolzdkask2nkgttk.gif)

3.  Why can not the scrolls be displayed when hovering? Why should I and the community focus on black bands?

Why not do so?

```css
mat-sidenav.mat-sidenav.sidenav {
    overflow: hidden;
}

mat-sidenav.mat-sidenav.sidenav:hover {
    overflow: auto;
}

// etc
```

![](https://habrastorage.org/webt/ff/wh/qp/ffwhqpkzkaxzmjxjcbpmrikfrpg.gif)

5. Broken layouts in home page

![](https://habrastorage.org/webt/kp/4c/cu/kp4ccuhzyojzxpp-9f13fow7nq8.gif)

Browser:
- [ ] Chrome (desktop) version 64
 
For Tooling issues:
- Platform:  Windows 10

**Comment by IgorMinar** [comment]
oops.. @splincode thanks for pointing these out.

would you like to send us a PR with the proposed fixes?

**Comment by splincode** [comment]
@IgorMinar About animation hangs very badly on weak computers
But my computer has very high performance (Intel core i7, Cores 8, 32Gb RAM)

But on the monitor's performance panel, the main thread loads the processor core at 80-100% (because there is a lot of redrawing)

We will exclude 85% of the load, if remove current code:

```
.mat-drawer-transition .mat-drawer-content {
    transition-duration: .4s;
    transition-timing-function: cubic-bezier(.25,.8,.25,1);
    transition-property: transform,margin-left,margin-right;
}
```

![copy](https://user-images.githubusercontent.com/12021443/37047738-f063329c-217c-11e8-88c5-d7342295dd24.gif)

**Comment by petebacondarwin** [comment]
@splincode are these issues now resolved?

**Comment by splincode** [comment]
@petebacondarwin Only problems with animation
