### ISSUE TITLE
Simple visual bug on main angular page

### ISSUE THREAD

**Issue by tayurus** [angular/angular#22159]
![image](https://user-images.githubusercontent.com/15295424/36085957-7cb48f16-0fda-11e8-8436-875e6d82d6c0.png)
Just look at the "next step" label
![image](https://user-images.githubusercontent.com/15295424/36085978-9bbb69ac-0fda-11e8-8c9f-8fef511849ba.png)

**Comment by shrivatsahosabettu** [comment]
Can you please specify the resolution and other details, because I don't see this visual error in the main document at any zoom point of the browser

![image](https://user-images.githubusercontent.com/12061573/36086148-947334d4-0ff0-11e8-8104-59e64ada08a8.png)

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/22149
