### ISSUE TITLE
Testing: Mocha done() stops subsequent tests

### ISSUE THREAD

**Issue by NiKlimenko** [angular/angular#22150]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
At use the standard case with the Mocha done() function, subsequent tests are not run.
```
it('should work', (done) => {
     done();
});

it('should work too', () => {
     // will not be executed
});
```

## Expected behavior
The subsequent tests should continue to run.

## What is the motivation / use case for changing the behavior?
Ability to write tests using Mocha

## Environment

<pre><code>
Angular version: 5.2.3

Browser:
- [x] Chrome (desktop) version 64.0.3282.140
 
For Tooling issues:
- Node version: 8.9.4  
- Platform:  Windows 10

Others:
Angular CLI used as a test starter.

**Comment by mhevery** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by NiKlimenko** [comment]
@mhevery thank you for your comment, can I provide a repository with the reproduction of the problem in this issue?

**Comment by JiaLiPassion** [comment]
@NiKlimenko , sure, please provide a reproduce repo. And some `README` to describe your issue.

**Comment by NiKlimenko** [comment]
@mhevery @JiaLiPassion here is a repository with a reproduction of the issue. If you have any questions let me know, thank you!
https://github.com/NiKlimenko/angular-mocha-done

**Comment by JiaLiPassion** [comment]
@NiKlimenko , thank you for posting the issue, it is a bug of `zone.js` not compatible with new version of `mocha`, I will fix it in `zone.js`.

**Comment by JiaLiPassion** [comment]
@NiKlimenko , for now, you can update your `package.json` and use my temp branch to test.

```
"zone.js": "https://github.com/JiaLiPassion/zone.js#mocha-dist"
```
