### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event.

### ISSUE THREAD

**Issue by jameskentTX** [angular/angular#22152]
[ x ] Bug report 

chrome, https://embed.plnkr.co/5w3EY55f0KMASipp8QhZ/

just open developer console and then run my plunker, click Alabama and you get error message

this problem was reported already by neutron92: https://github.com/angular/angular/issues/21910

**Comment by ericmartinezr** [comment]
For those who see nothing in the console, you have to select "Verbose" right next to the "Filter" input box.

That being said, this doesn't seem to be a problem with angular. You can reproduce this with a simple jsfiddle https://jsfiddle.net/zauc6ebc/.

If you look at [NgFor](https://github.com/angular/angular/blob/master/packages/common/src/directives/ng_for_of.ts) directive's source code you'll see no event handling (unless some of the functions called inside do actually handle scroll events).

Now, angular itself doesn't support passing properties to HostListener (nor through Renderer2/3 afaik) which is being tracked here https://github.com/angular/angular/issues/8866.

**Comment by Toxicable** [comment]
The above is what i'd recommend for now.
Use https://github.com/angular/angular/issues/8866 for tracking the status of passive events

**Comment by jameskentTX** [comment]
@Toxicable @ericmartinezr :

ok guys, I will observe #8866 feat, thanks
