### ISSUE TITLE
Documentation error which says NgModule instead of BrowserModule

### ISSUE THREAD

**Issue by shrivatsahosabettu** [angular/angular#22158]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In Architecture Overview --> Angular Libraries 
as in the below screen print it says "You also import NgModules from Angular libraries using JavaScript import statements:" which is in contradiction with the example shown in the code
![image](https://user-images.githubusercontent.com/12061573/36085164-ab82b746-0fe9-11e8-87aa-41e7eee4e42a.png)

## Expected behavior

The description should have been "You also import BroserModul from Angular libraries using JavaScript import statements:" to inline with the code example given

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
Please note the `s`(plural), `BrowserModule` is only an example used, your app may import several different others NgModules as well, nothing wrong with that.

Would you suggest something like:

> You also import NgModules (eg. `BrowserModule`) from Angular libraries using JavaScript import statements?

**Comment by shrivatsahosabettu** [comment]
Yes, that would be lot better.. Thanks for the your comments.

**Comment by jenniferfell** [comment]
Thank you for your feedback. We've done some work on the Architecture doc. We've expanded the information about NgModules in https://github.com/angular/angular/pull/21569. Does this sufficiently address this potential point of confusion?

**Comment by jenniferfell** [comment]
Rechecked against v6. Keeping open. 

@trotyl recommendation would be a useful clarification to help differentiate between "You import NgModule" (a proper noun) and "you import any ngModule" (kind of thing, which is the intent here).

Recommendation copied here for convenience: "You also import NgModules (eg. BrowserModule) from Angular libraries using JavaScript import statements."

**Comment by jbogarthyde** [comment]
Suggested wording change - with that change, #24475 is good to go.
