### ISSUE TITLE
docs(aio): Circular dependency in guides

### ISSUE THREAD

**Issue by imgx64** [angular/angular#22157]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

[Bootstrapping](https://angular.io/guide/bootstrapping) page starts with the following:

> #### Prerequisites
> 
> A basic understanding of the following:
> * JavaScript Modules vs. NgModules.

And [JavaScript Modules vs. NgModules](https://angular.io/guide/ngmodule-vs-jsmodule) page starts with the following:

> #### Prerequisites
> A basic understanding of Bootstrapping.

## Expected behavior

A reader should be able to read the prerequisites of a page before the page itself.

## Minimal reproduction of the problem with instructions

N/A

## What is the motivation / use case for changing the behavior?

A reader new to Angular is unable to know if he/she should read the `Bootstrapping` page first or the `JavaScript Modules vs. NgModules` page first.

## Environment
N/A

**Comment by kapunahelewong** [comment]
Hi @imgx64, thanks for catching this. Would you be willing to submit a PR? If so, I'd be happy to review it.

**Comment by jotatoledo** [comment]
Damn, my head almost overflowed after trying to read that

**Comment by imgx64** [comment]
@kapunahelewong I could, but I don't know which one is supposed to be read first.

**Comment by trotyl** [comment]
> **More on NgModules**
> For more information on NgModules, see:
> 
> + Bootstrapping.
> + Frequently used modules.
> + Providers.

@imgx64 Since **Bootstrapping** is already marked a further reading in **JavaScript Modules vs. NgModules**, could just remove that from Prerequisites. Namely **JavaScript Modules vs. NgModules** is a prerequisite of **Bootstrapping**, but not the opposite.

**Comment by kapunahelewong** [comment]
That's a good idea, @trotyl. @imgx64 you could remove it like @trotyl suggests but since that'd leave nothing there and we'd like to give people some sort of context, how about altering it something like: 

> A basic understanding of the following:
> * JavaScript

Without linking it. We have some pages with prerequisites like that since we do presume some basic knowledge in the docs. What do you two think?

**Comment by kapunahelewong** [comment]
Hey @imgx64 I've got it - no worries. :) Thank you
