### ISSUE TITLE
Integrate refresh mechanism to $resource

### ISSUE THREAD

**Issue by Izhaki** [angular/angular#2216]
This is a feature request to support what I believe will become an increasingly popular scenario.

(This applies to Angular 2, although would be great if we can see something like this in Angular 1.X; I will be using Angular 1 syntax, but the concept is the same nevertheless).

# Background

The applications to which this applies involve:

- A single page application.
- Possibly a (socket.io or similar) notification from the server to all clients, so clients can see updates in real time.

# Intro

In the most simple form controllers (or router.resolve) call $resource to facilitate CRUD operations:

> $resource < Controller

It is common to introduce a 'middleware' between the two, say in a system that shows reports:

> $resource < Reports < ReportsController

The benefits of which are many, including the ability to move business logic from the controller to the middleware.

In the code examples below, I will use `Reports` rather than $resource.

# A simple use case

Consider I have an app that lists all reports. For sake of clarity, instead of using the router `resolve`, the controller code will look something like this:

    // listAll() calls get/READ on $resource
    $scope.reports = Reports.listAll();

Now say the user clicks 'Add report', a model dialog shows, details are filled and the controller callback executes something like this:

    Reports.add( newReport, function( aRespose ) {
        newReport.id = aResponse.id;
    }

Now I want my reports list to update. There are two possible ways to do this:

## Solution 1

One way of doing this is to push to `$scope.reports` the new report. But doing so rely on very specific conditions:

- That the records returned by READ are identical to those returned by CREATE, which might not be the case since:
    - READ calls often do not return the full record data but only the properties required for presentation (eg, in a table).
    - CREATE calls may not return the full data, e.g. they may omit `creation_date`.

Now while this way of updating the list may well work in many cases, there are also many cases where it won't.

## Solution 2

The second, 'more correct' way of updating the list is simply running the READ query again.

It is worth noting that ideally, we don't just replace the reports array with the newly return results (as this will cause `ng-repeat` to flicker), but instead compare the old and new list and simply apply the changes.

# A less simple use case

Now consider that the reports list is:

- Paginated
- Filtered
- Sorted

All of these where provided as parameters to `$resource.get()`.

When the user adds a new report, there is virtually no sense in solution 1 above - you must call the READ query again.

# Real-time updates

Now if Client A adds a report, and the server notifies Client B, the latter must call the READ query again to ensure its local list is up to date.

Note that it's not only lists that need updating, it is also individual records - If Client A updates report 3, we want this report to be updated for Client B.

# The application or framework responsibility

All of this behaviour can be realised by application specific code, but perhas that it is really the framework responsibility to deal with such scenarios, since:

- $resource is the one that holds the `value` variable to which controllers have reference to, so it is the one which actually holds the data that needs updating.
- $resource can 'cache' the query that resulted in the data of its variable, so it shouldn't have a problem refreshing it.

# Requirements

So essentially, as a developer after calling

    var Report = $resource('/report/:reportId');

I'd like to be able to call something like:

    Report.refresh();

Which will update all the variables that are currently in use by calling the very same query that originally populated their data.

There are some optimisation requirements, like the ability to provide conditionals to check whether a refresh is needed (so if I got an report with `id:1` I don't need to refresh it if what has changes is a report with `id:2`), and also in case of lists not replacing the list by just applying changes.

But I wonder if the general concept is clear and if Angular can in any way support this?

**Comment by SekibOmazic** [comment]
@Izhaki This is Angular2 repo. You should file your issue here: https://github.com/angular/angular.js

**Comment by Izhaki** [comment]
I'm well aware this is an Angular2 repo, and this is request is for Angular 2 (and 1 if possible).

Sorry if using Angular 1 syntax is confusing. I'll edit my post.

**Comment by Izhaki** [comment]
@mhevery 

If I'm honest, we've been given much greater thought to this and I'm unsure it is Angular's responsibility to implement this - sure, it will be nice to have a refresh feature on a resource, but if all use cases are taken into account, this will hardly be of aid.

A proper solution is far more involved than a simple resource refresh (there is, for instance, a need for a two side - response/existing - comparison of the records). I hope to write some more on this soon and share.

You may be interested to have a quick look at [Loopback's Live Set example](https://github.com/strongloop/angular-live-set-example/blob/master/client/modules/circle/circle.controller.js), to see a possible option to solve part of the problem.

In the meantime, I suggest this issue is closed.

**Comment by mhevery** [comment]
Angular 2 will not include `$resource` like API. We think this is where the community can step in. 

Closing because this is outside the scope.
