### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by RbkGh** [angular/angular#22161]
## I'm submitting a...

[X] Feature request

## Current behavior
Seems there is no hook for page reload or refresh.
A hook like onPageRefresh() will be helpful for page refreshes.

## Expected behavior
When a refresh page is initiated by user in the browser,the parent app component is reloaded.
When the parent component is reloaded,there could be manual redirections on the parent component which loses the current page that the user was on.
For instance,let's say in my home component,I check to see the presence of an unexpired jwt key and redirect a user to a "home" route.
Now when a user is on a "purchase" route and refreshes the page,the app home component is recreated and it redirects to the home route upon seeing the presence of an unexpired jwt key instead of reloading the "purchase" route or component.

## Minimal reproduction of the problem with instructions
<pre>
<code>
import {BrowserModule} from '@angular/platform-browser';
import {Component, NgModule} from '@angular/core';

import {Router, RouterModule} from '@angular/router';

@Component({
  selector: 'app-root',
  template: `
    <router-outlet></router-outlet>
  `,
  styleUrls: ['./app.component.css']
})
export class MainComponent {
  constructor(private router: Router) {
    this.router.navigate([('home')]);
  }
}

@Component({
  selector: 'app-root-home',
  template: `
    <div>home works</div>
    <a [routerLink]="['/..', 'random']">Go to random</a>
  `
})
export class HomeComponent {

}

@Component({
  selector: 'app-root-random',
  template: `
    <div>random route works</div>
  `
})
export class RandomComponent {
  // when random component is loaded and we refresh the page,
  // it riderects back to home component(ie '/home' route) instead of the same '/random' route.
}

@NgModule({
  declarations: [
    MainComponent,
    HomeComponent,
    RandomComponent
  ],
  imports: [
    BrowserModule,
    RouterModule.forRoot([
      {
        path: '',
        component: MainComponent,
        children: [
          {
            path: 'home',
            component: HomeComponent
          },
          {
            path: 'random',
            component: RandomComponent
          }
        ]
      }
    ])
  ],
  providers: [],
  bootstrap: [MainComponent]
})
export class AppModule {
}
</code>
</pre>
## What is the motivation / use case for changing the behavior?
refresh an angular page and still stay on the same page after refresh

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
How would you like to implement that? By comparing current time and last close time? By session expiry cookie? How do you make sure there is no false positive?

**Comment by mlc-mlapis** [comment]
@RbkGh ... what do you mean by the terms `reload` or `refresh`? Is it the same as pressing the key F5?

**Comment by RbkGh** [comment]
yeah the same as F5 @mlc-mlapis

**Comment by mlc-mlapis** [comment]
@RbkGh ... ok, and what is your concrete case when a user need to do that ... it means when the user should press F5?

**Comment by jasonaden** [comment]
@RbkGh Thanks for the issue. But I think I need some more details in order to understand this. Maybe creating a StackBlitz example showing the problem would help to understand the feature request.

**Comment by RbkGh** [comment]
@jasonaden kindly find attached the stackblitz example .
I hope this helps 

[Angular-reload-enhancement](https://angular-reload-enhancement.stackblitz.io)

**Comment by mlc-mlapis** [comment]
@RbkGh ... it is not a problem with reload / F5 ... the same behavior when manually entering  URL ...
 /hi and ENTER.

The problem is that you have `<router-outlet></router-outlet>` only in your `AppComponent` + ` ngOnInit() {this.router.navigate(['/hello']);}` in it. But you routing definition is following ... where do you think that the second component `HelloComponent` or `HiComponent` should be placed?

```
{
   path: '', component: AppComponent,
   children: [
       { path: 'hello', component: HelloComponent },
       { path: 'hi', component: HiComponent }
    ]
}
```

**Comment by RbkGh** [comment]
@mlc-mlapis yes,HelloComponent will render in the same location as where the HiComponent will be loaded . But when refresh button is pressed when HiComponent is loaded,this new feature will just reload the HiComponent instead of redirecting to the 'hello' component from the AppComponent.

**Comment by trotyl** [comment]
@RbkGh Try open https://angular-reload-enhancement.stackblitz.io/hi directly, you'll be redirected as well, refresh didn't make a difference.

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
