### ISSUE TITLE
Improvement to Tour of Heroes Tutorial (Routing)

### ISSUE THREAD

**Issue by damodaranr** [angular/angular#22174]
In **Section 5 Master/Detail components**, we were introduced to property binding. Since **HeroesComponent** was directly binding to the **hero** property of HeroDetailComponent, it was necessary to import Input and declare the hero property using **@_Input_ hero:Hero**.

This technique was used <app-hero-detail [**hero**]="**selectedHero**"></app-hero-detail>

However after improvements made in the **Section 7 Routing**, the hero details were being retrieved through a route **hero**/**_id_**. As a result the code in hero-detail.component.ts can be further simplified as 
1.	import { Component, OnInit } from '@angular/core';  **instead of** import { Component, OnInit, **Input** } from '@angular/core';
2.    hero: Hero; **instead of**  **@_Input_ hero:Hero**.

**Comment by jenniferfell** [comment]
Thank you for the clear explanation and recommenation. We'll take a look at adding a section in which we have the reader rewrite that section of code to be simpler, after the improvements in Section 7.

**Comment by jenniferfell** [comment]
@damodaranr Or...if you'd like to contribute a fix directly, we're happy to help you through the process.  https://github.com/angular/angular/blob/master/CONTRIBUTING.md

**Comment by damodaranr** [comment]
@jenniferfell  Sure, I can contribute. I had noticed some other minor improvements that are possible in the documentation. I can create issues for those and work on them as well. I have not contributed before and hence I might be a little slower to begin. Is signing the CLA enough to get me started?

**Comment by jenniferfell** [comment]
@damodaranr : That's fantastic! Welcome aboard. My recommendation:
1. Read https://github.com/angular/angular/blob/master/CONTRIBUTING.md
2. Sign the CLA (linked from CONTRIBUTING.md)
3. Review https://github.com/angular/angular/blob/master/docs/DEVELOPER.md
4. For docs only contributions (not examples or code), in DEVELOPER.md, do everything up to "Building." 
You can skip the JDK. 
At this point, you'll have the tools and your fork. CONTRIBUTING has info about commit message format and submitting PRs. If you're not familiar with git, github, markdown, let me know, and I'll send some more links. 

Thanks again!

**Comment by damodaranr** [comment]
Thanks @jenniferfell I am not familiar with the github stuff. You can send me those links as well. I will get started on this soon.

**Comment by jenniferfell** [comment]
@damodaranr Can you access this wiki? https://github.com/ExpertSupport/doc-workflow/wiki
It was written by-and-for my team, and it's still under construction, but much of it applies to any doc contributor. Getting Started has setup information.

**Comment by damodaranr** [comment]
@jenniferfell  Yes. I am able to access it. Thanks!

**Comment by jenniferfell** [comment]
@damodaranr Hi. I'm catching up on issues. I just wanted to check in with you. How are you doing on this? If the github side of this is an inhibitor, perhaps I can connect you with someone on my team to co-author an improvement? If you've moved on to other things, I also understand. I just wanted to check in. Thanks.

**Comment by dariobraun** [comment]
@jenniferfell Saw this issue and that the OP didn't report back so I thought I'd just open a pr for the changes he suggested.

**Comment by chembu** [comment]
Fixed in PR #25215
