### ISSUE TITLE
Platform-browser transferState does not support false/0/null/enum values

### ISSUE THREAD

**Issue by manda-linda** [angular/angular#22178]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

```
this.transferState.set(KEY, 0);
this.transferState.set(KEY2, false);
this.transferState.set(KEY3, null);
this.transferState.set(KEY3, TestEnum.first);

console.log(this.transferState.get(KEY, 'DEFAULT');
console.log(this.transferState.get(KEY2,  'DEFAULT');
console.log(this.transferState.get(KEY3,  'DEFAULT');
console.log(this.transferState.get(KEY3,  'DEFAULT');
```
output:

```
 DEFAULT
 DEFAULT
 DEFAULT
 DEFAULT
```

## Expected behavior

```
0
false
null
0
```

## Minimal reproduction of the problem with instructions

Set the transfer state for a given key to a value that javascript conditionally evaluates as 'false'. Access that value using 'get' method. Observe that the default value is returned.

## What is the motivation / use case for changing the behavior?

Transfer state should support primitive types. 

## Environment

<pre><code>
Angular version: 5.2.4

**Comment by trotyl** [comment]
Closed by #22179 already (missing `fix` statement).
