### ISSUE TITLE
Angular 6 should support custom view engines (in addition to Render2 & Render3/Ivy)

### ISSUE THREAD

**Issue by eamon-otuathail** [angular/angular#22183]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Angular 6 currently supports the Render2 and Render3 (Ivy) view engines. Alternatives are not supported. 

## Expected behavior
If Angular 6 supported alternative view engines (and alternative view compilers), then a range of other implementation approaches for view processing could be experimented with. One idea is WebAssembly - rather than _emitRender3 within Compiler-CLI producing TypeScript code, we could have emit-Wasm, which would create .wasm code. Another idea for a custom view engine would be a multi-threaded Render3 - with different parts of the page managed by different web workers, connected to the main UI thread (for actual DOM edits) via a shared array buffer. Angular application developers will continue to write the same Angular Template Syntax (unchanged) and alternative view engines can process it in different ways.  

## Minimal reproduction of the problem with instructions
A more detailed explanation of the idea is here:
[http://www.clipcode.net/content/modular-view-engine-architecture-for-angular.pdf](http://www.clipcode.net/content/modular-view-engine-architecture-for-angular.pdf)

## What is the motivation / use case for changing the behavior?
Find the absolute fastest way of view processing for large applications. When WebAssembly supports direct DOM access, then for larger Angular apps such an approach could be faster than a TypeScript approach. 

## Environment
<pre><code>
Angular version: 6
</code></pre>

**Comment by arjunyel** [comment]
Using lit-html in Angular would be incredible :)

**Comment by tme321** [comment]
For what it's worth I think this is a very interesting proposal and I'd love to hear some feedback from the angular team.

**Comment by trotyl** [comment]
@arjunyel This proposal is **NOT** going to change any template syntax, but only the compilation result. What's the benefit for compile current template to lit-html internally?

**Comment by NiNJAD3vel0per** [comment]
This is really good article 
I totally agree about this.
Angular need support another renderer because Angular is platform-agnostic framework.

**Comment by IgorMinar** [comment]
The problem with this is that it opens up Angular's API surface to complexity that we are currently not in a position to support. Just look at @angular/platform-webworker as an example of similar feature that failed - it was a great idea at the time, but it added a ton of complexity, and over time we realized that it won't work well for all the main use-cases we need to support, didn't have cycles to make it work well for the use-cases where it could work well.

I think we can keep on discussing this request, but realistically we can't do anything like this until after Ivy is rolled out as the default (target is version 9), and even then unless we can figure out how to sustain API surface that is this huge, you will face a lot of resistance to proposals like this from the team that will be on the hook to support it.

Don't let this discourage you from proposing crazy ideas. I just want to set the realistic expectations here.

**Comment by michaeljota** [comment]
I just was looking for something like this. I understand this can be complicated and complex, but also I wouldn't expect so much of real scenarios with this. The applications of a custom view engine are very limited, but extremely powerful.

I would like to experiment and create a view engine that support rendering [libui](https://github.com/andlabs/libui) components. This could allow to an Angular developer to create a desktop native application, using the same API that we are used to. 

Beyond that, I would expected an improve support from NativeScript. 

Maybe you could open up progressively, and reducing the scope of the supported implementations to some scope you are confortable of.

**Comment by leonelvsc** [comment]
I've heard of other frameworks like https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor that implement wasm compilation. It would be amazing if Angular has the hability of compile to wasm code

**Comment by mlc-mlapis** [comment]
@leonelvsc Principally possible, but it's really a lot of work to prepare, develop and maintain all those parts to have something meaningful.
