### ISSUE TITLE
ng build not to remove .git info at dist dir

### ISSUE THREAD

**Issue by calidion** [angular/angular#22180]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
.git dir removed

## Expected behavior
.git kept back

## Minimal reproduction of the problem with instructions
``` ng build --prod```

## What is the motivation / use case for changing the behavior?

easier for deployment by git push

**Comment by ericmartinezr** [comment]
Please report angular-cli issues in its repo https://github.com/angular/angular-cli. This one is for the framework itself 👍
