### ISSUE TITLE
class.name for template function does not work in production

### ISSUE THREAD

**Issue by anvaya** [angular/angular#22187]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
The class.name property works in dev build, however fails in production build. class.name gives undefined. Not browser related as dev build works fine in the same browser.

## Expected behavior
Should not get class.name = undefined in production build, should get the actual class name. Something that compiles and works in dev build must work in production build.

## Minimal reproduction of the problem with instructions
If below code is used in dev build, works fine. Fail and gives "undefined" in production build.

```
export class Employee{  public id:string; public className="Employee"; 
   
   constructor(values: Object = {}) {          
        Object.assign(this, values);          
    }
}

export class Api
{
    public List<T>(c: new(values: Object)=>T)
    {
         var classname = c.name; //Returns  "Employee" in dev build, "undefined" in Production build.
    }

    public getEmployeeList()
    {
         return this.List(Employee);
    }
}
```
## What is the motivation / use case for changing the behavior?
Template functions won't help much if we can not get the class name in production. 

## Environment
<pre><code>
Angular version: 5.0.1

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.4.0
- Platform:  Windows

Others:
Tested on Windows 7 and Windows 2008 based servers with Apache 2.4 web server. 
</code></pre>

**Comment by chaosmonster** [comment]
class.name, even if it is tempting for Java developers, shouldn't be used. Because in prod mode your code will also be minified and uglified and that means your class may get a completely different name as you expect. 
E.g. `Router.name === t` in some of my builds in others it has another minified version.

**Comment by IgorMinar** [comment]
that's right. In JavaScript you can't rely on the class name being the same in prod mode. This is not an Angular thing. It's just how JavaScript and minification/prod optimizations work and have been working for years.

**Comment by anvaya** [comment]
Agreed, but then why should it come as "undefined"? I can understand getting a different name due to optimization.
