### ISSUE TITLE
ErrorHandler not working with lazyloaded child modules

### ISSUE THREAD

**Issue by karsunke** [angular/angular#22197]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When declaring ErrorHandlers in child modules, while also declaring an ErrorHandler in the root module, the root error handler is always called in case of an error. The child module ErrorHandlers are ignored.
<pre><code>
AppmoduleModule
|--> provides RootErrorHandler
|    
|--> ChildModule1
|    |--> provides Child1ErrorHandler
|
|--> ChildModule2
     |--> provides RootErrorHandler
</code></pre>
I made a sample repo for this behaviour: https://github.com/karsunke/angular-error-handler. If you click on 'child1' an error of childmodule1 is thrown, and the same for 'child2'.

I also made a branch where the RootErrorHandler is removed. Then there is no error handling at all: https://github.com/karsunke/angular-error-handler/tree/angular_issue

## Expected behavior
I expect the error handling to be module specific or at least work, if it is declared only in one child module.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/github/karsunke/angular-error-handler/
Click either on 'child1' or 'child2' and see that the error is always handled by the root error handler.

https://stackblitz.com/github/karsunke/angular-error-handler/tree/angular_issue
Click either on 'child1' or 'child2' and see that the errors aren't handled at all.

## What is the motivation / use case for changing the behavior?
I want module specific error handling.

## Environment
Angular version: 5.2.4

Browser:
- [ x ] Chrome (desktop) version 64.0.3282.140 
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

I also added a bounty to my question on SO a week ago, but there was no real answer: https://stackoverflow.com/questions/48564471/module-specific-error-handling-in-angular#

**Comment by jasonaden** [comment]
It looks to me like you're expecting the error handler to change based on where the error occurs. That's not going to work if you never inject the error handler you need.

In your example, it looks like you're creating the `AppComponent` and injecting the `ErrorHandler` (which at the `AppComponent` is going to be `RootErrorHandler`). The `AppComponent` is never re-instantiated, so when would it ever be the `ChildErrorHandler`? Also, even if it were re-instantiated it will pull the `ErrorHandler` for the injector the `AppComponent` is attached to. In this case, that's the one configured in `app.module.ts`, so for the `AppComponent` it will *always* be the `RootErrorHandler`.

**Comment by karsunke** [comment]
Well thats not quite true. I only inject the error handler to show the output in Appcomponent. The error handling itself works if you do not inject the error handler at all. The problem is, that it does not work if you provide it in a child module.
