### ISSUE TITLE
facing issue when Referring a typescript file outside of project directory is not working

### ISSUE THREAD

**Issue by karanhinduja** [angular/angular#22192]
<b>Following is my directory structure:</b>

├── MainProject
│ ├── package.json
│ ├── systemjs.config.js
│ ├── tsconfig.json
│ ├── app (folder)
├── Shared
│ ├── package.json
│ ├── tsconfig.json
│ ├── app (folder)
│ │ ├── Service
│ │  |  ├── Service.ts

In my main project I try to add service.ts file but get 404 error. Need assistance how can I achieve adding ts file outside the project directory

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by IgorMinar** [comment]
You can't share code like this without having a proper build setup. If you are using @angular/cli then such directory layout is definitely not supported. If you are using bazel, then this directory layout can be supported but requires you know how to manually setup the build pipeline.
