### ISSUE TITLE
Form Validator Directives not working

### ISSUE THREAD

**Issue by Karasuni** [angular/angular#22198]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
[`Form Validators`](https://angular.io/api/forms/Validators) directives don't seem to work for implicit [`FormGroup`](https://angular.io/api/forms/NgForm) instances. I've observed this recently with the `min` and `pattern` validators.

## Expected behavior
For a field with directive `min="0"` the value `-1` should result in an `error` and set `valid` to `false`.

## Minimal reproduction of the problem with instructions
[Example Stackblitz](https://stackblitz.com/edit/angular-5e2c7o?file=app%2Fapp.component.html)

1. Create an implicit form using `<form #myForm="ngForm">`
2. Create an implicit control using `<input [(ngModel)]="theNumber" #myNumber="ngModel" />`
3. Set a validator on the control e.g. `min=0`
4. Enter the value `-1`

Observe how there are no errors and valid is still `true`. Also observe how `e` is an accepted value (this looks like default but counter-intuitive behavior)

## Environment
<pre><code>Angular version: 5.2.4
</code></pre>

**Comment by trotyl** [comment]
See #17491, there's no validator for `min`/`max` attributes due to compatibility issue.

**Comment by Karasuni** [comment]
That issue appears to be closed even though it's marked as `severy5:regression`. Is there no fix or alternative planned then?

**Comment by trotyl** [comment]
Supporting `min`/`max` is a `severy5:regression` bug, and removing them is the fix. Please read it carefully.

**Comment by kara** [comment]
As @trotyl notes, this was intentional because the change was breaking. Existing issue https://github.com/angular/angular/issues/16352 tracks re-adding it down the line.
