### ISSUE TITLE
angular5 build failed in production mode

### ISSUE THREAD

**Issue by santhoshrajuvysyaraju** [angular/angular#22191]
Hi I have an error while building my application in production mode.

Here is The Following Error While building my angular application in production mode.

Here is The Error I Am Getting.

> ERROR in scripts.3c73d2a250157e743883.bundle.js from UglifyJs
Unexpected character '@' [scripts.3c73d2a250157e743883.bundle.js:7,0]

I Used Command  ng build --prod

but it is working fine when i use with out production mode.

Please Help Me To Solve The Issue.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by ttma1046** [comment]
you sure 'ng build' without '--prod' works fine.

**Comment by santhoshrajuvysyaraju** [comment]
yes thats working fine in my system

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
