### ISSUE TITLE
production build failed with error in angular form

### ISSUE THREAD

**Issue by sufiiiyan** [angular/angular#22190]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

ng build --prod is giving error in reactive form

error as below
chunk {0} styles.9c0ad738f18adc3d19ed.bundle.css (styles) 79 bytes [initial] [rendered]
chunk {1} polyfills.3bc34265385d52184eab.bundle.js (polyfills) 86 bytes [initial] [rendered]
chunk {2} main.e402deade8b026b7d50e.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.22b7623ed7c5ac6f9a35.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in src\app\components\login\login.component.html(7,30): : Argument of type 'FormGroup' is not assignable to parameter of type 'NgForm'.
  Property 'submitted' is missing in type 'FormGroup'.

## Minimal reproduction of the problem with instructions
component.ts file
<code>
 this.myForm = new FormGroup({
      'name': new FormControl('', Validators.required, CustomValidators.uniqueName),
      'birthYear': new FormControl('', [Validators.required, CustomValidators.birthYear]),
      'location': new FormGroup({
        'country': new FormControl('', [Validators.required]),
        'city': new FormControl('', [Validators.required])
      }, CustomValidators.countryCity),
      'phoneNumbers': new FormArray([this.buildPhoneNumberComponent()], CustomValidators.telephoneNumbers)
    });
</code>

component.html file 
<code>

```
<form [formGroup]="myForm" (ngSubmit)="register(myForm)">
    <div>
      <label>Name</label>
      <input type="text" name="name" formControlName="name">
      <show-errors [control]="myForm.controls.name"></show-errors>
    </div>

    <div>
      <label>Birth Year</label>
      <input type="text" name="birthYear" formControlName="birthYear">
      <show-errors [control]="myForm.controls.birthYear"></show-errors>
    </div>

    <div formGroupName="location">
      <h3>Location</h3>
      <div>
        <label>Country</label>
        <input type="text" name="country" formControlName="country">
        <show-errors [control]="myForm['controls'].location['controls'].country"></show-errors>
      </div>
      <div>
        <label>City</label>
        <input type="text" name="city" formControlName="city">
        <show-errors [control]="myForm['controls'].location['controls'].city"></show-errors>
      </div>
    </div>

    <div formArrayName="phoneNumbers">
      <h3>Phone numbers</h3>
      <div *ngFor="let phoneNumberControl of myForm['controls'].phoneNumbers['controls']; let i=index;">
        <label>Phone number {{i + 1}}</label>
        <input type="text" name="phoneNumber[{{phoneId}}]" [formControlName]="i">
        <button type="button" (click)="remove(i); myForm.controls.phoneNumbers.markAsTouched()">remove</button>
        <show-errors [control]="phoneNumberControl"></show-errors>
      </div>
      <button type="button" (click)="add(); myForm.controls.phoneNumbers.markAsTouched()">Add phone number</button>

      <show-errors [control]="myForm['controls'].phoneNumbers"></show-errors>
    </div>

    <pre>{{myForm.value | json}}</pre>
    <button type="submit">Register</button>
    <button type="button" (click)="printMyForm()">Print to console</button>
  </form>

```

## Environment

<pre><code>
Angular version: 5.2.2
Angular CLI: 1.6.4
Node: 8.9.4
OS: win32 x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

Browser:
- [ x] Chrome (desktop) version 64.0.3282.140 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.4
- Platform:  Windows 

</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
