### ISSUE TITLE
Interface based lifecycle methods

### ISSUE THREAD

**Issue by vicb** [angular/angular#2220]
As proposed in #2120, the current situation is:

```ts
@Component({
  lifecycle: [onChange],
  ...
})
class MyComponent implements OnChange {
  onChange(_):void { ... }
}
```

- `lifecycle: [onChange]` is ignored in Dart
- `implements OnChange` is ignored in JS (there is no such things as interfaces in JS)

I can see two problems with this:
- It's harder to write directives that would work for both Dart & JS,
- Currently the behavior is different because interfaces are inherited but annotations are not (yet) - this is probably going to change and will not be further described here.

What about completely dropping the `lifecycle: [onChange]` part using the following code for both JS & Dart:

```ts
@Component({
  ...
})
class MyComponent implements OnChange {
  onChange(_):void { ... }
}
```

Note that JS would use structural type check (which is currently the case when the `lifecycle` key is not present in the component configuration) and then the `implements OnChange` would be optional. To "workaround" this, we could document implementing the lc interfaces as a best practice and apply it to our code examples.

Some potential issue: `OnChange` define an `onChange` method. The name might bee to generic and the structural type check might return false positive when some user implement their own `onChange` method, ie in response to an event. However we could come with more specific name to circumvent this (`onDirectiveChange`, `onBindingsChange`, ...) - anyway having both `OnChange` & `onChange` is probably confusing.

Thoughts ?

/cc @vsavkin @yjbanov @tbosch @mhevery

**Comment by kegluneq** [comment]
(cross-posted from #2120)

I like this generally, but for the transformer this introduces some nasty edge cases.

To avoid the slowdown seen with the AngularDart (#1) transformer, we do not have a fully resolved AST or global information at transform time. With some exceptions, when operating on a file we only have the information available in that file. As an example, if we have:

a.dart:
```
class A implements OnChange {}
```

b.dart
```
class B extends A {}
```

We won't know that `B` implements `OnChange`.

@vsavkin and I talked about this and ~~settled on~~ proposed requiring `OnChange` to be explicitly specified even if it is already inherited.

Any objections?

**Comment by vicb** [comment]
(cross posted from #2120)

I understand the why but I don't really like the solution. If you extend some Directives, you'll have to check its signature before doing so, far from ideal - not to mention issues when the base class signature changes.

Also if we later need to merge annotations from the base classes, we'll have to walk them anyway (not clear to me if this will be implemented ?)

**Comment by kegluneq** [comment]
Another option is that we search the type graph at runtime to determine what a `Type` `extends` & `implements`. Something like:

```
Set<Type> visited = new Set<Type>();
Queue<Type> searchQueue = new Queue<Type>();

searchQueue.enqueue(MyComponent);
while (searchQueue.isNotEmpty) {
  var curr = searchQueue.dequeue();
  if (visited.contains(curr)) continue;
  visited.add(curr);
  if (curr == OnChange) {
    isOnChange = true;
  } else if (curr == OnDestroy) {
    isOnDestroy = true;
  } // ... etc
  searchQueue.enqueueAll(reflector.interfaces(curr));
}
```

We could cache answers for the future so we don't have to pay for this multiple times, but I wouldn't think it'd be too expensive.

**Comment by vicb** [comment]
> Another option is that we search the type graph at runtime [...]

What exactly would be the issue with pushing the work to the transformers ? could we make that configurable via a cli option (ie runtime checks during dev, static for prod) ?

**Comment by kegluneq** [comment]
There is no technical reason we can't do it, but it will make the transformation very, very slow.

Those queries require non-local information. Let's say we want to determine whether `A implements C`. If `A extends B` and `B implements C`, then we need to return `true`, but to figure that out we need to find the file where `B` is defined. For that reason making a change to any file in an Angular app "invalidates our cache" and we have to do a bunch of additional work to rebuild our view of the world.

The original AngularDart transformer used this technique which is why it was smarter but much slower. One of the transformer's main design goals is to avoid requiring this kind of global information.

One option we've discussed is having a "slow version" that does this kind of analysis and a "fast version" that doesn't. The slow version could then give you hints about how to make the fast version work.

**Comment by jakemac53** [comment]
I think I need a bit more info for this one. I see that we are already recording the interfaces, but where should these methods actually be invoked from? Also, what is the complete list of lifecyle methods?

**Comment by mhevery** [comment]
@jakemac53 What needs to be done from the Dart transformer is that it needs to generate the `lifecycle` event for the corresponding interface.

Example:

```
@Component(...)
@View(...)
class MyClass implements OnChange {
  onChange() {...}
}
```

Then the transformer needs to generate:

```
reflector.registerType(MyClass, {
  "interfaces": [OnChange],
  "annotations": ...
});
```

**Comment by jakemac53** [comment]
@mhevery so did https://github.com/angular/angular/pull/2328 close this out then?

**Comment by naomiblack** [comment]
@yjbanov can you have a look at this to see if it's actually closed by #2328?

**Comment by yjbanov** [comment]
@naomiblack No, it does not close this issue. Also, I do not fully understand why we needed #2328. In Dart you can already `is` to check interface compliance. OTOH, #2328 will increase code size and also it does not walk type hierarchy, so it is less accurate than an `is` check. I'll talk to @vsavkin and @kegluneq.

**Comment by yjbanov** [comment]
Update: @vsavkin explained that we only needed while we're still using transformers with dynamic change detectors. When generated change detectors are feature-complete, we will no longer need #2328 because we won't be checking interfaces reflectively. I will log an issue to remove interfaces from the reflector as a follow-up task after change detectors are done.

**Comment by naomiblack** [comment]
@yjbanov to provide some guidance to @jakemac53 on what's needed next.

**Comment by leafpetersen** [comment]
@jakemac53 asked me to take a look at this.  @yjbanov , any update on what needs to be done on our end to close this out?

**Comment by leafpetersen** [comment]
Per offline discussion with @yjbanov, it sounds like #2328 should have fixed the immediate issue, but the longer term goal is to eliminate the need for this information entirely.

**Comment by yjbanov** [comment]
Sadly, we're using recorded interfaces in more places now: https://github.com/angular/angular/commit/a9a552c112da1397a0122acdbecbd52bc88e1906

**Comment by jakemac53** [comment]
Fwiw, I did just do a quick test of `OnInit` and it seems to be working post-transform, but I added an issue to create an e2e test for this so we can make sure things don't break later on.

**Comment by yjbanov** [comment]
Let's close it then.
