### ISSUE TITLE
FormArrays with shared FormControls

### ISSUE THREAD

**Issue by luisfelipediaz** [angular/angular#22200]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have one FormGroup, and two FormArrays.

The first formArray has formControls "A", "B" and "C".
The second formArray has formControls "A" and "B".

I subscribed both formArrays to ValueChange Observable. But when "A" or "B" changes, the first formArray don't executes the ValueChange. Only the second formArray changes have been executed.

Only if "C" changes, the first formArray executes ValueChange.

https://plnkr.co/edit/upPg9d

## Expected behavior

I expected that changes in "A" and "B" executes ValueChange from both FormArrays.

https://plnkr.co/edit/GRdem2

## Environment

<pre><code>
Angular version: 5.2.3
</code></pre>

**Comment by chaosmonster** [comment]
That is not like FormArray is intended I feel like what you want is done with RxJs.

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
