### ISSUE TITLE
Router should not mutate Route config objects because it causes issue with platform-server

### ISSUE THREAD

**Issue by vikerman** [angular/angular#22203]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Router mutates Route[] object created by the user and configure in NgModule by writing extra _loadedConfig field.

This is ok for platform-browser by not for platform-server where parallel requests are sharing the same Route[] object.

## Expected behavior
Router should create a copy of the Route config per application before mutating it.

## What is the motivation / use case for changing the behavior?
This is to make sure Router works properly on the server environment

## Environment

<pre><code>
Angular version: latest

For Tooling issues:
any

Others:
-
</code></pre>

**Comment by Longfld** [comment]
Hi,
that change breaks my current application,.
Could you please give a sample, how we should use it after your changes?
