### ISSUE TITLE
docs(forms): expand documentation for Validator interface

### ISSUE THREAD

**Issue by jotatoledo** [angular/angular#22217]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The description for the Validator interface is poor IMO.
Furthermore, there is currently no documentation for the `registerOnValidatorChange` method.

## Expected behavior

Function signatures should be commented

## Minimal reproduction of the problem with instructions
Check the [src](https://github.com/angular/angular/blob/master/packages/forms/src/directives/validators.ts#L40)

**Comment by jenniferfell** [comment]
Thanks. I agree the API reference for Validator interface could be more complete. We've put it on our list. In the meantime, the guide may provide some of what you need: https://angular.io/guide/form-validation#template-driven-validation

If there are other use cases or scenarios that would be useful in the guide section, we're interested in that as well. Thanks!

**Comment by jotatoledo** [comment]
Hey @jenniferfell thanks for the rep. I was just looking at https://angular.io/guide/form-validation#adding-to-template-driven-forms and IMO some use cases are missing:

- how to update validity of the control when the input property of the validator directive is changed?

- How can a validator function of a reaxtive form control be binded to a component input property? So that in the case that the input property is changed, the validator will consider its current value when the validity is checked.

Ill update my comment with some examples during the weekend, Im currently afk

**Comment by seedy** [comment]
`registerOnValidatorChange` seems to follow the same logic as `ControlValueAccessor`'s methods 
`registerOnChange` and `registerOnTouched`.

Therefore I'd tell : 
```
/**
     * Registers a callback function that should be called when the validator's value
     * changes.
     *
     * This is called by the forms API on initialization so it can update the form
     * state when values propagate from the view (view -> model).
     *
     * If you are implementing `registerOnValidatorChange` in your own validator, you
     * will typically want to save the given function so your class can call it
     * at the appropriate time.
     *
     * ```ts
     * registerOnValidatorChange(fn: () => void): void {
     *   this._onChange = fn;
     * }
     * ```
     *
     * When the value changes, your class should call the registered
     * function to allow the forms API to update itself.
     *
     *
     */
```

**Comment by jotatoledo** [comment]
@jenniferfell this is tagged with "has pr".
