### ISSUE TITLE
Add a milestone:needsTriage to issues that don't have label:"comp:"

### ISSUE THREAD

**Issue by manughub** [angular/angular#22212]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Github does not have a way to do -label:"comp:*" wildcard searches to find untriaged issues

## Expected behavior
This is a new feature request for the bot.
For issues in Angular/Angular that dont have a label:"comp:" assignment, I would like to have the bot assign a milestone:needsTriage

## Minimal reproduction of the problem with instructions
Not Applicable

## What is the motivation / use case for changing the behavior?

Efficiency improvement for triaging

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ocombe** [comment]
What about searching for issues with no milestone instead?

**Comment by manughub** [comment]
I'm trying to determine that issues that have not been triaged. Just no:Milestone would bring up semi-triaged issues 
https://github.com/angular/angular/issues?utf8=%E2%9C%93&q=repo%3Aangular%2Fangular+type%3Aissue+state%3Aopen+no%3Amilestone+
These already have a component designation (and missing some fields that I expect the L2 comp triagers to assign)

**Comment by manughub** [comment]
Any update on this ?

**Comment by ocombe** [comment]
I can work on it tomorrow if you want

>
