### ISSUE TITLE
IE11 Error in Polyfills.bundle.js Running Angular 4 project

### ISSUE THREAD

**Issue by Bushan11** [angular/angular#22215]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I am running a Angular 4 project. It is working perfect in Chrome but when we run it on IE11 sometimes it throws error at below line of code in Pollyfills.bundle.js

try {
                if (task.type == macroTask && task.data && !task.data.isPeriodic) {
                    task.cancelFn = null;
                }
                try {
                    return this._zoneDelegate.invokeTask(this, task, applyThis, applyArgs);
                }
                catch (error) {
                    if (this._zoneDelegate.handleError(this, error)) { 
                        throw error; //ERROR THROWS AT THIS LINE
                    }
                }
            }
Please see attached screenshots for your reference
![image](https://user-images.githubusercontent.com/31878643/36188871-1d3ccf8e-1175-11e8-896f-8d294fc42d16.png)

## Expected behavior

It is happening very frequently but not always

## Environment

<pre><code>
@angular/cli: 1.4.2
node: 6.11.3
os: win32 x64
@angular/animations: 4.4.4
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.4.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x ] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:   Windows

Others:

</code></pre>

**Comment by JiaLiPassion** [comment]
@Bushan11 ,please provide a reproduce repo or `stackblitz`.

**Comment by Bushan11** [comment]
It is not able to reproduce .. Sorry
But it is happening intermittently .. not sure what causing this

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
