### ISSUE TITLE
Serviceworker: Cannot read property 'next' of undefined

### ISSUE THREAD

**Issue by myxor** [angular/angular#22218]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

After updating some files on the server where the serviceworker is active it sometimes fails with
> Serviceworker: Cannot read property 'next' of undefined

in line 913 of **ngsw-worker.js** which is:

>  // The node is not the head, so it has a previous. It may or may not be the tail.
        // If it is not, then it has a next. First, grab the previous node.
        const previous = this.state.map[node.previous];
        // Fix the forward pointer to skip over node and go directly to node.next.
        previous.next = node.next; **// <-- THIS ASSERTION FAILS**
        // node.next may or may not be set. If it is, fix the back pointer to skip over node.
        // If it's not set, then this node happened to be the tail, and the tail needs to be
        // updated to point to the previous node (removing the tail).

It seems that `previous` is not set because there was no node in the `this.state.map` array.

## Expected behavior

Serviceworker should not crash if `previous` is not set. 
There should be a check if the object is set before setting its property `next`.

## Minimal reproduction of the problem with instructions

Sorry i can't provide an example because this happens not every time and depends on changes of other files which are cached by the serviceworker.

## What is the motivation / use case for changing the behavior?

Preventing the crash

## Environment

<pre><code>
Angular version: 5.2.4
Angular CLI: 1.6.8

Browser:
- [x] Chrome (desktop) version 63.0.3239.132 64-bit
- [x] Firefox version 58.0.2 64-bit
propably on others too
 
For Tooling issues:
- Node version: v9.3.0  
- Platform:  Linux, Windows, propably on others too

Others:
We are using Apache as the webserver

</code></pre>

**Comment by Romanchuk** [comment]
Struggling with this error.
When fetching network first html file:
> TypeError: previous is undefined
We need null check
