### ISSUE TITLE
`routerLinkActive` and `router.isActive` do not work with arrays in queryParams.

### ISSUE THREAD

**Issue by gregoirechauvet** [angular/angular#22223]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`routerLinkActive` and `router.isActive` do not work with arrays in queryParams.

## Expected behavior

`routerLinkActive` and `router.isActive` should match correctly an URL which has arrays in queryParams.

## Minimal reproduction of the problem with instructions

Here is a plunker that show what the issue is: http://plnkr.co/edit/CgMuRGMvsu2KAOm0aYOQ
If you click on _Link with an array_ in the plunker, the navigation is achieved, but the class `active` is not added, and the link is not red. Because there is a queryParams with an array.

However, if you click on _Link with an integer_, it works fine, and the link is highlighted in red.

## Identification of the issue
I have looked for the issue in angular code, and I think the issue is caused by this method which compare queryParams:
In file [packages/router/src/url_tree.ts](https://github.com/angular/angular/blob/master/packages/router/src/url_tree.ts):
```typescript
function containsQueryParams(
    container: {[k: string]: string}, containee: {[k: string]: string}): boolean {
  return Object.keys(containee).length <= Object.keys(container).length &&
      Object.keys(containee).every(key => containee[key] === container[key]);
}
```
The issue is that `containee[key] === container[key]` cannot work with arrays.
`[1] === [1]` is `false`.

Maybe I can do a pull request to fix this.

## What is the motivation / use case for changing the behavior?

I am using arrays in queryParams, to store some state in the URL, in order to be able to save the link and use it later.
I could probably use a workaround ; sort and stringify my array before using it, but I prefer not to.

## Environment
<pre><code>
Angular version: 5.2.5

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by jasonaden** [comment]
@Prince-Leto Thanks for the issue. Yes, a PR would definitely be helpful.

**Comment by Prince-Leto** [comment]
Ok, I will try to make a pull request in 3 three weeks. I will have some time.

**Comment by Zaid-Al-Omari** [comment]
I have fixed the issue with the PR #22666.
kindly review @jasonaden

**Comment by IliaVolk** [comment]
Any updates?

**Comment by stocksr** [comment]
I would like this fix included please - can I help get the pull request merged?
