### ISSUE TITLE
Header issue

### ISSUE THREAD

**Issue by javid-abd** [angular/angular#22227]
[ ] Documentation issue or request
this is very insignificant bug in documentation. just move the header a little bit to the right  :)
https://angular.io/guide/quickstart#next-step
![im](https://user-images.githubusercontent.com/32272345/36223432-d42336bc-11dd-11e8-9cb8-6e14fbcbfea9.jpg)

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/22149

**Comment by javid-abd** [comment]
didn't see that, going to close

**Comment by javid-abd** [comment]
dup of #22149

**Comment by javid-abd** [comment]
dup of #22149
