### ISSUE TITLE
Mistake at CSS file in Tour of Heroes tutorial

### ISSUE THREAD

**Issue by op-fasc** [angular/angular#22222]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Buttons aren't styled correctly.

## Expected behavior
Buttons should be styled

## Minimal reproduction of the problem with instructions
https://angular.io/tutorial/toh-pt6#final-code-review

heroes/heroes.component.css
Line 53: change class selector ".button" to element selector "button"

Buttons are styled correctly.

## What is the motivation / use case for changing the behavior?
Having a nice output ;)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 64.0.3282.140
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.4.0
- Platform:  Mac

Others:

</code></pre>

**Comment by sarunint** [comment]
Off-topic: congrats on getting the issue number 22222!
