### ISSUE TITLE
aio + docs/api: New icons for types

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#22224]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently, each type in the API reference has an icon. The icons are all rectangular boxes with ALL CAPS text. Color differentiates types.

## Expected behavior

I find myself asking if these are for decoration, or if we expect users to build up a memory and association for these icons to their types. For example, do users begin to learn that class has a blue box in the API ref index and on the pages?

I wonder if we can come up with a set of icons that have more "pop." ALL CAPS in a box isn't as easy to scan as Sentence or CamelCaps and shape variation. Also, some of the colors are very close and don't distinguish well when scanning. 

Perhaps we can come up with icons and colors that scan easily. Perhaps color families could be used for similar types, such as blue and green for class and interface? 

If we get icons we like, we might be able to reuse them in diagrams elsewhere to help reinforce the association.

They aren't bad. Just wondering if there's an opportunity here. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
All types are shown here with their small icons. Large icons on the associated pages: https://angular.io/api

**Comment by petebacondarwin** [comment]
Can we close this then?
