### ISSUE TITLE
Angular2 component not loading in jqxLayout

### ISSUE THREAD

**Issue by hanusaikrishna** [angular/angular#22220]
I am using jqxWidgets in angular2. I Designed one jqxLayout with tabbed Group and document group. I am trying to load the angular component inside jqxLayout.It is not Loading.
Kindly share the code to load component in jqxLayout.

Here is my code,

export class AppComponent{
layout: any[] =
[{
type: ‘layoutGroup’,
orientation: ‘horizontal’,
items: [{
type: ‘layoutGroup’,
orientation: ‘vertical’,
width: 800,
items: [{
type: ‘documentGroup’,
items: [{
type: ‘documentPanel’,
title: ‘ToolItems’,
contentContainer: ‘ToolbarPanel’
}]
}]
}, {
type: ‘layoutGroup’,
class: ‘Color’,
orientation: ‘horizontal’,
width: 800,
height: 600,
items: [{
type: ‘tabbedGroup’,
width: 400,
height: 600,
items: [{
type: ‘layoutPanel’,
title: ‘Color Group’,
contentContainer: ‘ColorGroupPanel’
}]
}, {
type: ‘tabbedGroup’,
width: 400,
height: ‘100%’,
items: [{
type: ‘layoutPanel’,
title: ‘Error List’,
contentContainer: ‘ColorListPanel’
}]
}]
}, {
type: ‘tabbedGroup’,
width: 268,
items: [{
type: ‘layoutPanel’,
title: ‘Properties’,
contentContainer: ‘PropertiesPanel’
}]
}]
}];
}
HTML code,
<jqxLayout [width]=” ‘100%’ ” [height]=” ‘100%’ ” [layout]=”layout” [theme]=”‘efi'”>
<!–The panel content divs can have a flat structure–>
<!–documentGroup–>
<div class=”toolBarComponent” data-container=”ToolbarPanel”>
<app-toolbar *ngIf=”productValue == ‘efi’ && licensed”></app-toolbar>
</div>
<!–bottom tabbedGroup–>
<div class=”colorGroupComponent” data-container=”ColorGroupPanel”>
<app-colorgroup [colorGroupWidth]=”colorGroupWidth” [ngStyle]=”{‘color’: ‘inherit’, ‘width’:colorGroupWidth}”>
</app-colorgroup>
</div>
<div class=”colorListComponent” data-container=”ColorListPanel”>
<app-colorlist style=”display: flex; flex: 1;” [colorGroupWidth]=”colorGroupWidth” [colorListWidth]=”colorListWidth” (currentColorListWidth)=”currentColorListWidth($event)”>
</app-colorlist>
</div>
<!–right tabbedGroup–>
<div data-container=”PropertiesPanel”>
List of properties
</div>
</jqxLayout>

My requirement is to load a component in jqxLayout.
I kept All controls in a child component. I need to instantiate the component not controls.
How I can refer a child component in Layout??
I don’t find any reference regarding this requirement. Please provide some example,it will be useful.

Thanks,
Hanusaikrishna

**Comment by mlc-mlapis** [comment]
@hanusaikrishna ... you are a bit lost ... you have detailed demos for many jQWidgets components on their pages ... and especially for jqxLayout here ... https://www.jqwidgets.com/angular/angular-layout/angular-layout-defaultfunctionality.htm

**Comment by jotatoledo** [comment]
Please dont use the issue tracker for general support questions

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
