### ISSUE TITLE
Restore `install-chromium.sh` version checking once `https://omahaproxy.appspot.com/all` is back

### ISSUE THREAD

**Issue by matsko** [angular/angular#22231]
When travis runs this error pops up:

```
   creating: /home/travis/.chrome/chromium/chrome-linux/resources/inspector/security_test_runner/
  inflating: /home/travis/.chrome/chromium/chrome-linux/resources/inspector/security_test_runner/security_test_runner_module.js  
/home/travis/build/angular/angular/scripts/ci/install-chromium.sh: line 82: LATEST_CHROMIUM_VERSION: unbound variable
```

And it's due to [https://omahaproxy.appspot.com/all](https://omahaproxy.appspot.com/all) being unresponsive.

Once that page is working again. We can uncomment and close this issue.

**Comment by IgorMinar** [comment]
can you capture why it's failing now? the next caretaker will not know when it's safe to restore.
