### ISSUE TITLE
Tutorial: Tour of Heroes - added hero's value shows nothing

### ISSUE THREAD

**Issue by javid-abd** [angular/angular#22237]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

in Tutorial: Tour of Heroes, after removing all hero names, the value of added hero shows null.

## Expected behavior

https://stackblitz.com/angular/oarvopmjgjv
![angular-bug](https://user-images.githubusercontent.com/32272345/36243560-79c24aec-123b-11e8-88c3-c2d7cff2c42e.gif)

**Comment by trotyl** [comment]
Duplicate of #22120

**Comment by javid-abd** [comment]
duplicated issue
