### ISSUE TITLE
Document not found for service workers

### ISSUE THREAD

**Issue by mkarthik90** [angular/angular#22242]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
Service workers section is not getting loaded in angular.io
<img width="1680" alt="screen shot 2018-02-15 at 10 11 05 am" src="https://user-images.githubusercontent.com/9751475/36273194-9518c2ba-1238-11e8-8f5b-b976160c3923.png">

## Expected behavior
When clicked on service workers link, the service workers documentation should show up.

**Comment by gkalpak** [comment]
@mkarthik90, can you provide some more info?
E.g. what is the URL in the address bar? Do you see any messages/errors in the console? What version is shown at the very bottom of the page (inside the blue footer)?

**Comment by mkarthik90** [comment]
@gkalpak Please find the details:

###### URL:
```
https://angular.io/guide/service-worker-intro
```

###### Console logs:
```
The resource https://angular.io/generated/docs/index.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
service-worker-intro:1 The resource https://angular.io/generated/navigation.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
```

###### Version:
```
5.2.6-build.40114+sha.0c88d5d
```

###### Network calls:
```
Request URL:https://www.google-analytics.com/collect?v=1&_v=j66&a=1915444958&t=pageview&_s=5&dl=https%3A%2F%2Fangular.io%2Fguide%2Fservice-worker-intro&dp=%2Fguide%2Fservice-worker-intro&ul=en-us&de=UTF-8&dt=Angular%20-%20QuickStart&sd=24-bit&sr=1680x1050&vp=1680x226&je=0&_u=SACAAEABE~&jid=&gjid=&cid=1517559940.1501132690&tid=UA-8594346-15&_gid=407540729.1518571224&z=929094430
Request Method:GET
Status Code:200 
Remote Address:172.20.5.75:8080
Referrer Policy:no-referrer-when-downgrade

Request URL:https://www.google-analytics.com/collect?v=1&_v=j66&a=1915444958&t=pageview&_s=5&dl=https%3A%2F%2Fangular.io%2Fguide%2Fservice-worker-intro&dp=%2Fguide%2Fservice-worker-intro&ul=en-us&de=UTF-8&dt=Angular%20-%20QuickStart&sd=24-bit&sr=1680x1050&vp=1680x226&je=0&_u=SACAAEABE~&jid=&gjid=&cid=1517559940.1501132690&tid=UA-8594346-15&_gid=407540729.1518571224&z=929094430
Request Method:GET
Status Code:200  (from ServiceWorker)
Remote Address:10.48.127.169:8080
Referrer Policy:no-referrer-when-downgrade
```

Let me know if you need any other details.

**Comment by gkalpak** [comment]
Thx for the info. Can you please also post the content of https://angular.io/ngsw.log and also all XHR requests (as shown in DevTools `Network` tab) while loading the page?

After you have done that, you can try to unregister the ServiceWorker (`DevTools` > `Application` > `Service Workers` > `Unregister`) and reload the page. Sounds like something has gone wrong with the SW.

**Comment by mkarthik90** [comment]
@gkalpak Please find the details

###### ngsw.log
```
{
  "state": "READY",
  "lifecycleLog": [
    "manifest 8f7e427a93381490fcaa834e92c76235e5f670c0 activated",
    "transition from STARTUP to READY"
  ]
}
```

###### XHR Requests:
```
Request URL:https://www.google-analytics.com/analytics.js
Request Method:GET
Status Code:304 
Remote Address:10.48.127.169:8080
Referrer Policy:no-referrer-when-downgrade

Request URL:https://angular.io/generated/navigation.json
Request Method:GET
Status Code:200  (from ServiceWorker)
Remote Address:10.48.127.169:8080
Referrer Policy:no-referrer-when-downgrade

Request URL:https://angular.io/ngsw-manifest.json?ngsw-cache-bust=0.3507996039483592
Referrer Policy:no-referrer-when-downgrade

Request URL:https://angular.io/generated/docs/guide/service-worker-intro.json
Request Method:GET
Status Code:503 OK (from ServiceWorker)
Remote Address:10.48.127.169:8080
Referrer Policy:no-referrer-when-downgrade

Request URL:https://angular.io/generated/docs/guide/service-worker-intro.json
Referrer Policy:no-referrer-when-downgrade

Request URL:chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/ng-validate.js
Request Method:GET
Status Code:200 OK (from disk cache)
Referrer Policy:no-referrer-when-downgrade

Request URL:https://angular.io/generated/docs/app/search-data.json
Request Method:GET
Status Code:503 OK (from ServiceWorker)
Remote Address:10.48.127.169:8080
Referrer Policy:no-referrer-when-downgrade

Request URL:https://angular.io/generated/docs/app/search-data.json
Referrer Policy:no-referrer-when-downgrade

Request URL:https://fonts.gstatic.com/s/materialicons/v36/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2
Request Method:GET
Status Code:200  (from disk cache)
Remote Address:10.48.127.168:8080
Referrer Policy:no-referrer-when-downgrade
```

I unregistered the service workers from Applications and the page still doesn't load. Let me know if you need any other detail.

**Comment by gkalpak** [comment]
Hm...these `Status Code: 503 OK (from ServiceWorker)` responses look suspicious :grin:
Especially since these files are not cached by the SW :confused: @alxhub, any idea what might be going on?
(Related issue: https://github.com/angular/mobile-toolkit/issues/168)

Such issues should go away once we upgrade to the new ServiceWorker implementation though (see #19795).

##
@mkarthik90, have you tried disabling the browser cache. (It could be that the browser (not the SW) has cached a bad response; possibly from a few days ago when we had some issues with the firebase hosting.)
Could you also try from a different browser?

Thx again for the patience and providing all the info. It really helps us make sure everything works more smoothly in the future ❤️

**Comment by mkarthik90** [comment]
@gkalpak It works fine with other browsers(Safari). I disabled cache and tried to load service workers but it doesn't work. Thx

**Comment by gkalpak** [comment]
That is very strange 😕 I am running out of ideas 😅
What do you get if you request https://angular.io/generated/docs/guide/service-worker-intro.json directly?

**Comment by mkarthik90** [comment]
@gkalpak I am sorry the issue was with my proxy. I am able to load all the angular pages. Sorry for the trouble. Closing this issue.
