### ISSUE TITLE
Router does not support NgRoutingUsePushState 

### ISSUE THREAD

**Issue by irfantusneem** [angular/angular#2224]
Router does not support NgRoutingUsePushState.  See Angular 1.0 dart.

**Comment by btford** [comment]
@irfantusneem – what functionality is missing? You can change between pushstate and hashchange strategies like this: https://github.com/angular/angular/blob/master/modules/angular2/router.ts#L40

**Comment by btford** [comment]
I'm going to close this since I think it's been resolved. If I'm incorrect, let me know @irfantusneem and I'll reopen this.
