### ISSUE TITLE
Create semi-complex form example

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#2225]
checkout form that contains several fields:

- first name: required, some max length, type=text
- middle name: optional
- lastname
- credit card: custom validator, required
- amount: number, required
- email: native type, required
- comment: text area, optional

capabilities:
- show validation error messages
- disable submit button when invalid

styles:
- template driven style
- imperative style

**Comment by mhevery** [comment]
@IgorMinar are you aware of this demo: https://github.com/angular/angular/blob/master/modules/examples/src/forms/index.ts Is this not sufficient?
