### ISSUE TITLE
Drop event is not firing when attached inside ngFor

### ISSUE THREAD

**Issue by richenyadav001** [angular/angular#22250]
Hi Team,

I am attaching html 5 drop event on an element inside ngFor enabled element

NOT WORKING CODE
              `<div *ngFor="let item of Table; let i=index;">
                  <div class="drag-list">
                      <div class="drag-list-block">{{item['id']}}</div>
                  </div>
                  <div class="drag-place">
                      <div class="center-text" id="drop_{{i+1}}" (drop)="drop($event)" (dragover)="dropover($event)"></div>
                  </div>
                </div>`

WORKING CODE
              `<div class="dragdrop-section">
                  <div class="drag-list">
                      <div class="drag-list-block">Lorem ipsum dolor sectum</div>
                  </div>
                  <div class="drag-place" id="div1" (drop)="drop($event)" (dragover)="dropover($event)">
                  </div>
                  <div class="drag-list">
                      <div class="drag-list-block">Laborum et dolorum iste</div>
                  </div>
                  <div class="drag-place" id="div2" (drop)="drop($event)" (dragover)="dropover($event)">
                  </div>
                  <div class="drag-place" id="div3" (drop)="drop($event)" (dragover)="dropover($event)">
                  </div>
              </div>`

## While drag event is firing on both working and non working code
                `<div *ngFor="let item1 of x; let i=index;" class="drag-drop" id="drag_{{i+1}}" draggable="true" (dragstart)="drag($event)">
                    <div class="drag-list-block">{{Table[x[i]].id}}</div>
                    <a href="javascript:void(0);" class="drag-icon"></a>
                  </div>`

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Environment

<pre><code>
Angular CLI: 1.5.3
Node: 6.9.5
OS: win32 x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.8.1

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
Please make a living demo on https://stackblitz.com/

**Comment by richenyadav001** [comment]
https://stackblitz.com/edit/angular-k411hs

**Comment by PodaruDragos** [comment]
use'@HostListener' to bind to drop event. that should work just fine.

**Comment by richenyadav001** [comment]
I also tried 
changeDetection: ChangeDetectionStrategy.OnPush
then listen for changes
then detach()
but it doesnt work

**Comment by richenyadav001** [comment]
Hey guys thanks for support 
I found the problem
Its in div which binds drop event as that div doesnt occupy any space when rendered

SO you can close this issue
Thanks

**Comment by vicb** [comment]
@richenyadav001 you can closeyour own issues too. Thanks.

**Comment by mxchange** [comment]
@richenyadav001 if it was the `div`, was it not collapsed without the ngIf?

Because I'm dealing with a similar issue where `(drop)` is never fired while `(dragover)` is. Even with `.stopPropagation()` the dropped file will be loaded in the tab, instead of staying on the page.
