### ISSUE TITLE
Reactive forms async validation: internal control validator is able to raise the state of a formGroup from PENDING up to the VALID

### ISSUE THREAD

**Issue by timkachko** [angular/angular#22253]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

### Reactive forms with async validation

If I have async validators both on the form and child control, and form's validator is still in process (form state is PENDING), the child control is able to set the form state to the VALID.

## Expected behavior

Regarding to the fact that we don't have the result from the outer validator, the form should stay in the PENDING state. The state of the form should not be VALID, if the validation result is unknown yet. 

## Minimal reproduction of the problem with instructions

Please refer to the https://stackblitz.com/edit/angular-5qdtpv?file=src%2Fapp%2Fapp.component.ts

Easy to see that the form should not be VALID ever, as soon as its async validator returns error after the timeout.

## What is the motivation / use case for changing the behavior?

The form should not allow to submit incorrect data in any case/time.
The AbstractControl internal state propagation should follow the hierarchy based on the statement above.

And the FormGroup API doesn't allow to change the internal state of the FormGroup, so no easy workarounds here. 

## Environment

<pre><code>
Angular version: ^4.0.0, ^5.00

Browser:
- [x] Chrome (desktop) version 64.0.3282.167

**Comment by kara** [comment]
Yeah, this is broken. We already have an existing issue here, though, so closing as a dupe.

https://github.com/angular/angular/issues/10064.
