### ISSUE TITLE
Symlink node module not detecting changes past folder depth of 4

### ISSUE THREAD

**Issue by JanaMOH** [angular/angular#22262]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I currently have a module that i share across multiple angular applications. I am using symlink as a way to have the module be shared across the multiple applications. Changes made for files trigger angular's watcher and recompiles the code up until a folder depth of 4. Anything past that will not trigger it. I have noticed it does work on windows, using the same Angular Version, but not on Linux.

## Expected behavior
Changes made in shared folder should trigger auto compiler and refresh the page.

## Minimal reproduction of the problem with instructions
package.json has one shared module dependency listed as

`"shared_module": "file:../shared_module", `

## What is the motivation / use case for changing the behavior?
Decrease development time. 

## Environment

<pre><code>
Angular version: 1.1.3

Browser:
N/A
 
For Tooling issues:
- Node version: 9.2.0
- Platform: Linux x64

**Comment by vicb** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a plunker reproducing the problem and describing the difference between the expected and current behavior. You can use this plunker template: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue
