### ISSUE TITLE
Implement Google Analytics tracking via gtag.js instead of analytics.js

### ISSUE THREAD

**Issue by markgoho-EDT** [angular/angular#22260]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## What is the motivation / use case for changing the behavior?

Users implementing GA tracking after February 1, 2018 are prompted to use the gtag implementation of tracking from the GA admin dashboard.

It would be great to see AIO implement this strategy so others looking for best practice could have something to go on.

Migration guide: https://developers.google.com/analytics/devguides/collection/gtagjs/migration

**Comment by gkalpak** [comment]
cc @IgorMinar

**Comment by petebacondarwin** [comment]
Still unresolved.

**Comment by wKoza** [comment]
Do we need to change it ? I can take it !

cc @IgorMinar @petebacondarwin

**Comment by petebacondarwin** [comment]
@wKoza - We don't "need" to change it but it is now best practice. Feel free to take this on if you have time. Thanks!
