### ISSUE TITLE
Components on a route are instantiated before calls of ngOnDestroy of the previous route's components

### ISSUE THREAD

**Issue by BBaysinger** [angular/angular#22267]
I've just noticed that components on a route are getting instantiated before `ngOnDestroy` is being called on the components of the previous route.

For me it's causing problems in the order that things need to happen. The components of the previous route need to unsubscribe from a few things before the new route makes changes in state that will emit some observables/events and whatnot.

This may or may not be a big issue, as I may have to add code for many of my components to listen for a route change rather that rely on `ngOnDestroy`.

Mostly, I'm just perplexed. Am I missing something? Was this a change in Angular 4 or 5? I'm not sure how it actually makes sense.

I guess my main question would be, is this a bug, or is there a reason for it?
 
https://stackoverflow.com/questions/48836759/angular-5-components-on-route-instantiated-before-ngondestroy-of-the-previous-r

## I'm submitting a...

<pre><code>
[ x] Bug report
</code></pre>

## Current behavior

Components on a route are instantiated before calls of ngOnDestroy of the previous route's components

## Expected behavior

Components on a previous route should be destroyed before the new components on the successive route.

## Minimal reproduction of the problem with instructions

Make an Angular app with two routes.
`console.log()` from onOnDestory in a component on the first route.
`console.log()` from the constructor of a component on the second route.
See that the constructor on the second route gets called before ngOnDestory on the first route.

## What is the motivation / use case for changing the behavior?

1. I'm listening for route changes, and updating certain variables from that.
2. This triggers a few events and observables to dispatch/emit.
3. Those events are triggering processes in the components on the previous route, right before they are destroyed.
4. With the overall state changes that occur on route change, the previous route's component are not operating on the correct state they are expecting, causing errors.

I'm sure this isn't the only use case, but it's really screwing things up for me. I may have to detect route changes, and manually destroy my components. Hopefully not a bunch of them!

## Environment

<pre><code>
Angular version: 5.2.5

Browser:
- [x ] Chrome (desktop) version XX
- [x ] Chrome (Android) version XX
- [ x] Chrome (iOS) version XX
- [ x] Firefox version XX
- [x ] Safari (desktop) version XX
- [ x] Safari (iOS) version XX
- [ x] IE version XX
- [ x] Edge version XX

**Comment by jotatoledo** [comment]
Please add a living demo of the issue

**Comment by vicb** [comment]
Please add a repro otherwise we can not help

**Comment by BBaysinger** [comment]
Yes, I will. I’m under a mad deadline right now. Might have it to you Thursday.

**Comment by BBaysinger** [comment]
My plunkr example is not reproducing the issue I observe in my app. I will need to investigate further.

https://plnkr.co/edit/KWV0KBHOKRWEa041J8Lr?p=preview

**Comment by BBaysinger** [comment]
Closing since I couldn't reproduce it. Will come back to this if I run into it again.
