### ISSUE TITLE
Could not resolve module @angular/core with Sails.js

### ISSUE THREAD

**Issue by AtifJaved1** [angular/angular#22266]
Due to the integration with the sails.js application. the path changes due to which its throwing that error. I am attaching the tsconfig.app.json file. Please let me what should I update in this file according to my directories structure. 

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "baseUrl": "./",
    "types": [],
     "paths": {
      "@angular/*": [
        "./node_modules/@angular/*"
      ],
      "@nebular/*": [
        "./node_modules/@nebular/*"
      ]
    }
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}

```

<img width="264" alt="screen shot 2018-02-17 at 4 56 37 am" src="https://user-images.githubusercontent.com/26598012/36335036-f8aa2488-139e-11e8-8c37-d208b51f97c9.png">

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
