### ISSUE TITLE
May be a little typo at Docs -> Tutorial -> Routing Page.

### ISSUE THREAD

**Issue by theSumit67** [angular/angular#22278]
## I'm submitting a...

<pre><code>
[x ] Documentation issue or request
</code></pre>

At Docs -> Tutorial -> Routing Page -> Section [ DashboardComponent hero links ](https://angular.io/tutorial/toh-pt5#dashboardcomponent-hero-links)

## Current behavior
You're using Angular interpolation binding within the *ngFor repeater to insert the current interation's hero.id into each routerLink.

## Expected behavior
You're using Angular interpolation binding within the *ngFor repeater to insert the current iteration's hero.id into each routerLink.

**Comment by jenniferfell** [comment]
Looks like this was fixed, but not by the referenced PR. Closing as fixed. Thanks for catching this!
