### ISSUE TITLE
Can be code of SharePoint hosted app which is written in Angular 2.0, move to SharePoint 2010?

### ISSUE THREAD

**Issue by guptarajesh001** [angular/angular#22281]
I have created SharePoint hosted app which is written in Angular 2.0 in the SharePoint 2013, now I want to use this app's code to SharePoint 2010. Can it be possible? If please tell its step..

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem)
