### ISSUE TITLE
files not emitted by ngc compiler

### ISSUE THREAD

**Issue by Bengreen** [angular/angular#22296]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I run the my build process for library code inside the postinstall hook of my modules (as we are doing a lot of development and do not want to commit compiled js into version control).
I am doing this for libraries for my angular projects.
When the ngc function is run it does not follow the imports for the imported components, etc to generate them in the library.
it seems to (my guess) believe that since this library is within the node_modules path of the parent project then it is an external therefore shoudl not be compiled.
As a result I only get the files compiled that are specifically listed in my includes or files configurations. As a sort fo fix I can extend the scope fo include to specifically identify all files explicitly, but this goes against the flatModuleOutFile option which requires a single entry to the module and results in all files being compiled not just those that are required and traced from the entry point of the library.

As an alternative test I installed the library (standalone) rather than as a dependancy from a parent module and in this case the post install works perfectly (the only difference I can see is that this case the src files are not inside a node_modules path and therefore do not get picked up as external and ignored.

## Expected behavior
Should compile the files the same whether in standalone project or as dependancy inside a node_modules path.

## Minimal reproduction of the problem with instructions
run ngc to compile a library whilst within a node_modules tree and it will not follow and compile dependancies. BUT when run outside fo the node_modules tree it will compile correctly.

## What is the motivation / use case for changing the behavior?
Allow typescript to be compiled for a module at point of install.

## Environment
Typescript 2.6.2
compiler-cli 5.2.5
<pre><code>
Angular version: 5.2.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  8.9.1
- Platform:  Mac

Others:
</code></pre>

**Comment by vicb** [comment]
Please add a repro
