### ISSUE TITLE
Issue with File uploading in Angular

### ISSUE THREAD

**Issue by KSANTHOSHKUMA** [angular/angular#22299]
**Files uploading issue with Angular 4,**

I am struggling with this issue since 4 days if possible provide serve rside code also

Please see the below link for the issue
(https://stackoverflow.com/questions/48839828/unable-to-upload-all-types-of-files-to-server)

Current behavior
I have implemented code that is working fine only for  text files like  .ts, .json, .html, .txt,  but when it comes to .pdf, .xls, .png, .jpg ..............not working properly,    data which is sent over the request that is not saving on to file at server side.

Expected behavior
I want send & store all types of files to server

 Environment
@angular/cli  1.4.7
node  8.9.4
Angular version  4.0.0
npm version : 5.6.0

**Comment by KSANTHOSHKUMA** [comment]
@ericmartinezr  Thanks, i have tagged issue with Angular , if any thing else required please let me know, 

hoping we will close this issue soon.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
