### ISSUE TITLE
How to call or interact a method from child/parent/sibling component in angular 5.

### ISSUE THREAD

**Issue by Mrkd007** [angular/angular#22300]
So, the problem is I have to call a method from the child component and another one from child to the siblings and parent as well which will be based on some conditions. So I need a proper solution for this I am struggling a lot with this.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
