### ISSUE TITLE
View Encapsulation on feature module level

### ISSUE THREAD

**Issue by adamlubek** [angular/angular#22302]
## I'm submitting a...
<pre><code>
[x] Feature request
</code></pre>

## Current behavior
When feature module is loaded (lazy/eager) and has view encapsulation set to none, it's css bleeds to other parts of the app.

## Expected behavior
When feature module is loaded (lazy/eager), it's view encapsulation settings should only apply to this module i.e. not bleed/affect other parts of the app

## What is the motivation / use case for changing the behavior?
When developing feature module, I might need to set view encapsulation to none for my feature module but that setting shouldn't affect styling of other feature modules once my module is loaded into app

</code></pre>

**Comment by alxhub** [comment]
View Encapsulation doesn't work this way - setting `ViewEncapsulation.None` on a component is an explicit statement that its CSS should be in the global namespace. This is how CSS works in browsers.
