### ISSUE TITLE
Make it possible to make multiple roots, so we can do <custom-component> inside <body>

### ISSUE THREAD

**Issue by mortenmoulder** [angular/angular#22303]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Feature description
I've recently looked into [Stencil](https://stenciljs.com/) which I'm a fan of (as well as Ionic). The way Stencil makes components is really easy. I can create a new component and implement it on any page I want in a few minutes, without worrying about routing or anything like that.

I would love, if I could make a component in Angular, which completely ignores the `<app-root>` component, like I can with Stencil. 

This is how easy it is to implement n amount of components using Stencil:

    <script src="~/stencil/www/build/app.js"></script>
    <custom-component name="Morten"></custom-component>
    <second-custom-component></second-custom-component>

I would like to do something that simple in Angular, since it seems like a pretty easy thing to implement (bootstrapping multiple root components).

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by mortenmoulder** [comment]
@vicb It's really more of a feature, as it's not supported in Angular as of now. I can't get support or help, as it's not a feature in Angular as of now.

**Comment by mlc-mlapis** [comment]
@mortenmoulder ... https://github.com/angular/angular/pull/15668 + wait for Angular Elements.
