### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked

### ISSUE THREAD

**Issue by splincode** [angular/angular#22304]
I need to change the value in the life cycle of the component, but when I do this error falls, what should I do?

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

app.component.ts

```ts
import { Component, AfterViewInit } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent implements AfterViewInit {

  public value: boolean = true;
  public testValue = { value: true };

  public ngAfterViewInit() {
    this.value = false;
    this.testValue.value = false;
  }

}

```

app.component.html

```html
value = {{value}} <br>
testValue.value = {{testValue.value}}
```

```
AppComponent.html:1 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.
    at viewDebugError (errors.js:52)
    at expressionChangedAfterItHasBeenCheckedError (errors.js:28)
    at checkBindingNoChanges (util.js:127)
    at checkNoChangesNodeInline (view.js:547)
    at checkNoChangesNode (view.js:520)
    at debugCheckNoChangesNode (services.js:542)
    at debugCheckRenderNodeFn (services.js:486)
    at Object.eval [as updateRenderer] (VM303 AppComponent.ngfactory.js:12)
    at Object.debugUpdateRenderer [as updateRenderer] (services.js:463)
    at checkNoChangesView (view.js:363)
```

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-frgqqb?file=app%2Fapp.component.ts

## Environment

<pre><code>Angular version: 5+

**Comment by trotyl** [comment]
> `<!-- Please search GitHub for a similar issue or PR before submitting -->`

**Comment by mlc-mlapis** [comment]
@splincode ... lol, simply you have to change your logic. You can't do it in `ngAfterViewInit` because it is a moment when Angular is preparing to update the View based on the latest data changes and during that process `ngAfterViewInit` and you can't change conditions in this moment = it is too late, you break unidirectional principle from top to bottom.

**Comment by splincode** [comment]
https://angular.io/guide/lifecycle-hooks#lifecycle-sequence

Why is the documentation not mentioned about this? What can not we do?

**Comment by splincode** [comment]
Examples in documentation:

```ts
export class AfterViewComponent implements  AfterViewChecked, AfterViewInit {
  private prevHero = '';

  // Query for a VIEW child of type `ChildViewComponent`
  @ViewChild(ChildViewComponent) viewChild: ChildViewComponent;

  ngAfterViewInit() {
    // viewChild is set after the view has been initialized
    this.logIt('AfterViewInit');
    this.doSomething();
  }

  ngAfterViewChecked() {
    // viewChild is updated after the view has been checked
    if (this.prevHero === this.viewChild.hero) {
      this.logIt('AfterViewChecked (no change)');
    } else {
      this.prevHero = this.viewChild.hero;
      this.logIt('AfterViewChecked');
      this.doSomething();
    }
  }
  // ...
}
```

```ts
private doSomething() {
  let c = this.viewChild.hero.length > 10 ? `That's a long name` : '';
  if (c !== this.comment) {
    // Wait a tick because the component's view has already been checked
    this.logger.tick_then(() => this.comment = c);
  }
}
```

Angular throws an error if the hook updates the component's data-bound comment property immediately (try it!). The LoggerService.tick_then() postpones the log update for one turn of the browser's JavaScript cycle and that's just long enough.

Why do not you immediately write a warning in the hooks about what you can not do? Why do I need to understand this.logger.tick_then and where is its description (is it the Promise or setTimeout)?

**Comment by NoMercy235** [comment]
'ExpressionChangedAfterItHasBeenCheckedError` is thrown when you try to modify a component's state after the change detection algorithm ended.

Your issue is that `ngAfterViewInit` happens, as the name suggests after the change detection algorithm ended. At that point, Angular expects nothing else to change in the component's state until the next tick. However, it does, because you set the value of the properties to false. You can't something that would trigger a new change detection after a change detection has ended. 

You can do those assignments in `ngOnInit` and Angular won't complain.

**Comment by splincode** [comment]
There are not many short descriptions in the documentation that can not be done, but what can be done. Only a bunch of examples, beginners can not always do so much effort to study them

**Comment by ericmartinezr** [comment]
There are issues about this you can read just like trotyl mentioned. There's no need to open a new one.

**Comment by TheSkyNet** [comment]
@trotyl meby it's not him and its a shit error? you can't say RTFM if its pile of garbage
