### ISSUE TITLE
ts2dart should rename types/methods for simple facades

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2231]
* [ ] rename `Array`, `Map`, `String` and all of their methods
* [ ] throw when object has `.push()` but is of type `any`.

**Comment by vicb** [comment]
@mprobst I love this! Are `Map` handled yet ?

**Comment by mprobst** [comment]
@vicb (and others):

You can find the supported façade methods [in facade_converter.ts](https://github.com/angular/ts2dart/blob/master/lib/facade_converter.ts#L88) in ts2dart.

Supported as of this writing:
* [x] `Array.push`
* [x] `Array.map`
* [x] `Array.concat`
* [x] `Array.isArray`
* [x] `Map.get`
* [x] `Map.set`
* `CONST_EXPR`, `forwardRef`

Meaning you should be able to just write:

```ts
var xs: string[] = [];
xs.push('12');
var sum = 0;
xs.map((x) => parseInt(x)).forEach((x) => sum += x);
```

And for Maps:

```ts
var m = new Map<string, number>();
m.set('answer', 42);
console.log(m.get('answer'));
```
