### ISSUE TITLE
[BUG ?] InvalidPipeArgument for pipe DatePipe

### ISSUE THREAD

**Issue by kevincaradant** [angular/angular#22312]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Under IE11 only.       FF && Chrome work
![image](https://user-images.githubusercontent.com/6093175/36380090-54dfdcbe-1581-11e8-8f82-01e7fe647382.png)

`return new DatePipe(local).transform("2018-02-16 06:41:00", 'd MMM y HH:mm');`

## Expected behavior

No error with the DatePipe

## What is the motivation / use case for changing the behavior?

Use the pipe for a date without error

## Environment

<pre><code>
Angular version: 5.2.5

Browser:
- [x] Chrome (desktop) version 64
- [x] IE version 11
 
For Tooling issues:
- Node version: 8.9.0
- Platform:  Windows 7 64 bits

**Comment by trotyl** [comment]
Duplicate of #20443, see https://github.com/angular/angular/issues/21716#issuecomment-360084199

**Comment by kevincaradant** [comment]
Yes I understood it more later after to create this issue. Sorry ;)
