### ISSUE TITLE
Each standard Validator could have an optional string param to override the validators name/errorKey

### ISSUE THREAD

**Issue by bastienJS** [angular/angular#22319]
## I'm submitting a...
 
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Imagine I have a class with 100 key/value pairs defined. Each key is the name of a validator like min for Validators.min(number). The value for the key would be the error message.

Now I have 10 min and max validators for multiple fields. When I try to get the specific error message for a specific min, max, required validator I get multiple error messages because multiple same keys exist...

My goal is really to have all error keys and error custom messages defined in ONE class:

That would work:

```
getValidatorErrorMessage(validatorName: string, validatorValue?: any) {
    let config = {
      'required': 'Required',
      'worstScoresSmallerThanBestScores': 'Punkte müssen kleiner sein als Punkte für beste Note.',
      'worstScoresOneSmallerThanBestScores': 'Es wird ein freier Punkt benötigt für Punkte bei Knick',
      'worstMistakesSmallerThanBestScores': 'Fehler müssen größer sein als Fehler für beste Note.',
      'min': 'Minimum ist ein Punkt.',
      'max': `Maximum ${validatorValue} sind erlaubt`
    };

    return config[validatorName];
  } 
```

but that not:

```
static getValidatorErrorMessage(validatorName: string, validatorValue?: any) {
    let config = {    
      'minWorstScore': 'Minimum worst score is: ${validatorValue} ',
      'minBestScore': `Minimum best score is: ${validatorValue}`
    };
    return config[validatorName];
  }
```
Custom validator names for standard validators are not possible :-/

## Expected behavior

I would like to do: Validators.min(1, "minBestScore") or Validators.min(99, "minWorstScore");

## Minimal reproduction of the problem with instructions

Really there is nothing to reproduce, its easy to understand by looking above

## What is the motivation / use case for changing the behavior?

I want to keep validation error messages in one class having a getErrorMessage method like above. But that will only work with unique error key names.

At the moment all error messages are spread in the whole application inside terrible to read .html templates.

## Environment

 
Angular version: 6.0.0 beta 4

**Comment by mlc-mlapis** [comment]
@bastienJS ... maybe I don't understand it correctly but you probably need your own sets of validators (including wrappers of standard validators) and each validator can return either `null` or any object you want as ...
```
return { 
   anyValidator: {
      errorCode: 'S02702',
      errorMessage: anyExpressionOrConstant
   }
}
```

**Comment by bastienJS** [comment]
@mlc-mlapis  I think you get my point, but I do not want to create a bag of wrappers around my min/max/required wrappers. That should be handled by the framework as its a common requirement.

**Comment by mlc-mlapis** [comment]
@bastienJS ... I think that you should ... because:

* it is the reason why Angular has only a few standard validators
* wrapping them is just several lines of code
* data type of a returned value is therefore designed for that purpose
* Angular can't cover all the needs of real-world applications
* so it is supposed that you will customize them by your specific way.
