### ISSUE TITLE
Navigating to a parent route with an auxiliary route breaks the navigation flow

### ISSUE THREAD

**Issue by blackholegalaxy** [angular/angular#22310]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Navigating through `router.navigate()` to a both parent route and with an auxiliary route keeps the current route in the url.

## Expected behavior
It should remove current url segment if navigating to absolute parent route.

### First case: working properly

Let's say we are on route `/manage/my-super-id`.

From a service, calling the following method:
```
this.router.navigate(['/manage', 'my-super-id', { outlets: { auxOutlet: ['comments', 'new'] } }]);
```

works properly. We are redirected to url: `/manage/my-super-id/(auxOutlet:comments/new)`

### Second breaking case

Let's say we are on route `/manage/my-super-id/edit`.

From the service, calling the following method:
```
this.router.navigate(['/manage', 'my-super-id', { outlets: { auxOutlet: ['comments', 'new'] } }]);
```

works properly. We are redirected to url: `/manage/my-super-id/(edit//auxOutlet:comments/new)`

It keeps my `edit` route part in the loop, even if my `navigate()` intended to navigate to an absolute path.

Please note: the addition of the edit route, within parenthesis, will eventually break subsequent router flow. For example, if I close the auxOutlet. By navigating to `{outlets: { auxOutlet: null}}`, the URL now becomes /manage/my-super-id/(edit) which breaks for example regex route matchers and so on which can rely on URL parts strings.

## Environment

<pre><code>
Angular version: 4.3.2
Still occurs in 5.2.5

Browser: Chrome (iOS) version 63.x and 64.x
</code></pre>

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
