### ISSUE TITLE
[HttpClient POST] `Invalid calling object` in IE11 and Edge

### ISSUE THREAD

**Issue by dalidovski** [angular/angular#22329]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior;
I'm using HttpClient to post a request, It's working as expected on Chrome, Mozzila and Safari. However, I'm facing an issue with IE11 and Edge with the following errror : 

**Error occured while authenticating
ERROR TypeError: Invalid calling object.**

Below the source code:

> import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
> ...
> 
>    let params = new HttpParams();
>     params = params.append('username', user_id);
>     params = params.append('password', password);
>     this.http.post(API_URLS.loginURL, params).subscribe(
>       res => {
>         console.log('success');
>         },
>       err => {
>        console.log('Error occured while authenticating');
>         console.log('err');
>       });

## Expected behavior
The expected behavior is that the browser (IE 11/Edge) send the http request and return success.

## Environment

Angular CLI: 1.6.0
Node: 8.9.2
OS: win32 x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

<pre><code>
Angular version: 5.2.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [x] Edge

**Comment by vicb** [comment]
Please provide a repro

**Comment by dalidovski** [comment]
Pace js is overriding XHR requests w they have a bug with IE11. It's not related to Angular/http.
Sorry for the inconvenience.
