### ISSUE TITLE
Custom two-way binding with @Input and @Output properties

### ISSUE THREAD

**Issue by Yerkon** [angular/angular#22326]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

https://angular.io/guide/template-syntax#two-way-binding---

`<app-sizer [(size)]="fontSizePx"></app-sizer>` This code syntax sugar of this: 
`<app-sizer [size]="fontSizePx" (sizeChange)="fontSizePx=$event"></app-sizer>`

Before solving my problem, I spend enough time to find what's wrong. 
### I have component with custom two-way binding with @Input and @Output properties:
```
<tmk-factory-department-list (factoryChanged)="onFactoryChange($event)"
                                 [(factory)]="position.factory">
</tmk-factory-department-list>
```

### factory-department-list.component.ts:
```
...
  /**Two way binding
   * 
   * @required
   */
  @Input() public factory: Common.Item;

  /**Two way binding
   * 
   * @optional
   */
  @Input() public department: Common.Item;

  /**
   * при выборе цеха
   * 
   * @optional
   */
  @Output() factoryChanged = new EventEmitter<any>();
...
 selectFactory(factory: Common.Item) {
    _.assign(this.factory, factory);
   ...
   this.factoryChanged.emit(); // 
  }
...
```
So when emitting different values like number, boolean it updates property `@Input() factory ` to emitted value. The problem is `ngModel `collisions with property `@Output factoryChange`. So in this case how I undersand: 
   When using custom two-way binding with ~~@Input and~~ @Output properties we should care about naming these @Output properties. Because if we use `someVariable ` as `ngModel ` we can **broke** app behaviour if we use `@Output someVariableChange` in that component. 

So, updating @Output property to another solves problem(**factoryChange** to **factoryChanged**) : 
```
<tmk-factory-department-list (factoryChanged)="onFactoryChange($event)"
                                                [(factory)]="position.factory">
</tmk-factory-department-list>
```

## Expected behavior

Give opportunities to name `@Output properties` as you wish in case with `ngModel`. 
OR show in console about collision with naming something like: "`ngModel`  `variableChange` event binding is overriden by some component"

In AngularJS, how I remember, there is no problem like this.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by alxhub** [comment]
The problem here is the multiple bindings to the output `factoryChange`, not the naming of the output itself. I suspect this works in Ivy, though - we do (I think?) support multiple event listeners on the same event.
