### ISSUE TITLE
HttpClient doesn't throw on observable if Chrome cancels a request

### ISSUE THREAD

**Issue by PascalHonegger** [angular/angular#22324]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

If Google Chrome cancels a request the HttpClient.get() observable never finishes. This happens for example when you put your computer to sleep (or in our concrete use-case close a laptop).

## Expected behavior

The observable should throw just like any other network related request error would.

## Minimal reproduction of the problem with instructions
To cancel a request in chrome you have to put your windows into sleep mode (E.g. close laptop). I don't know enough about the pipeline to simulate a request cancelation by hand, so I created a stackblitz where you can simulate a request which takes at least 5s so you have time to put your computer to sleep. You can also provoke a cancelation by simply pressing ctrl+s.
https://stackblitz.com/edit/angular-request-cancelation?file=app/app.component.ts

## What is the motivation / use case for changing the behavior?

We have a request which rerstarts itself once it finishes. As a user might close his laptop (put it to sleep) and keep the site open, this request is never restarted. The only feasible workaround for this would be to either detect a browser sleep (unrealiable) or add a timeout to the request (delayed reaction).

## Miscellaneous
* The same sleep-problem doesn't seem to exist in other browsers (tested IE11 & FF58) as they don't cancel the request like Chrome does.
* I couldn't find an existing issue talking about this concrete problem, but it might also be related to:
  * The sleep of windows (7)
  * Google Chrome handling of cancelation
  * RxJS
* I also tried these steps to fix this issue, sadly without any success:
  * Use new RxJS <code>pipe()</code> instead of the "old-school" methods (E.g. <code>finally()</code> => <code>finalize()</code>)
  * Specify observe: 'response'
* Using my provided stackblitz I got the following warning from Chrome itself: <code>The FetchEvent for "..." resulted in a network error response: an object that was not a Response was passed to respondWith().</code> Maybe it's a Chrome issue?

## Environment

<pre><code>
Angular version: 4.4.6 & 5.2.5 & 6.0.2 tested

Browser:
- [x] Chrome (desktop) version 66
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version 58
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4
- Platform:  Windows

Others:

Windows 7
</code></pre>

**Comment by PascalHonegger** [comment]
I noticed an additional (and devastating) behavior in the latest chrome: You can cancel a request using the ctrl+s shortcut (which opens a save dialog). This makes it stupidly easy to break an angular website which relies on the completion of an observable to show / hide loading messages. This can for example also break the angular.io website by simply hitting ctrl+s while switching to a new page (simulating a slow network makes the timing easier). I know that most users don't spam ctrl+s, but I still think this issue should be investigated / prioritized.

**Comment by grosch** [comment]
Any progress on this?

**Comment by curdwithraisins** [comment]
Seems like we figured out where is the problem. 

We fallowed the same steps @PascalHonegger provided: make a pending request and put laptop into sleep mode. 

We tested it by creating two requests: one through simple **XMLHttpRequest** and another one through Angular **HttpClint**. We subscribed on HttpClint and all XMLHttpRequest events. As was discovered cancelation of request triggers abort event on XMLHttpRequest. We dived deeper and found that HttpClient listens to only three events: _progress_, _load_ and _error_. 

That is why Observable never ends. XMLHttpClient returns an abort but Angular doesn't react on it.

We made a small fix on our side just adding an **HTTP_INTERCEPTOR** which cancels a request if it doesn't respond after 1 min. But we also made a PR to Angular to support this event (#28338).

**Comment by andreyjamer** [comment]
We also suffer a lot because of this issue. If user has unstable network and application send a series of requests, then it is impossible to know if request was canceled or server is polling requests.
Handling of _about_ event is very required in HttpClient

**Comment by Sanguium** [comment]
Any update on this issue?

**Comment by vladjerca** [comment]
I understand your specific use-case, but I don't think a cancelled HTTP request should throw an `error`. 

Remember that HTTP in-flight requests are cancelled automatically if a new one is launcher or if you manually unsubscribe from the stream, which in essence is the desired behavior.

I think we're better of if a new `HttpEvent` is implemented, which can be later accessed via the `observe` option.

``` ts
this._http.get(endpoint, {
  params,
  observe: 'events',
})
  .pipe(
    tap(ev => {
      if (ev.type === HttpEventType.Cancel) {
        // do something
      }
    })
  );
```

Regarding the `abort` event, I agree that the observer should be completed if the browser cancels the event.

``` ts
xhr.addEventListener('abort', () => observer.complete());
```

This check can also be easily added within a `HttpInterceptor` allowing configuration at an application wide level.

**Comment by grosch** [comment]
@vladjerca That makes sense to me.  No reason for it to be an error, we just need *some* way to tell that it happened.

**Comment by andreyjamer** [comment]
@vladjerca Yes, probably, it should not be an error. But anyway some notification should appear in such case. Now we have the total silence from the HttpClient and also there is no information about such behavior in documentation. So many developers can get unexpected bug when they will deal with unstable network connections.

**Comment by lostdev** [comment]
This is a huge problem, I am surprised it hasn't been fixed yet.

**Comment by luisfpg** [comment]
I don't think this should be labeled as `freq1:low`.
It happens every time in my case if I quickly click login / action / action... / logout in my app.
I'm a developer of https://github.com/cyclosproject/cyclos4-ui.
The app has a global HTTP interceptor, which knowns when there are pending requests (https://github.com/cyclosproject/cyclos4-ui/blob/master/src/app/core/api.interceptor.ts). As a fallback, after 15 seconds the request is removed from the pending queue.
In the following video you can see that after logging-in, clicking a bunch of actions and logging out, the login button is disabled, and gets re-enabled after a few seconds. That means that the notification for request completion was never generated for some requests...
![Angular - canceled http requests](https://user-images.githubusercontent.com/1183737/59764452-3125d200-9272-11e9-837f-b4a6ec79ea11.gif)

**Comment by maximedupre** [comment]
So is there a workaround or not right now?

**Comment by eXXeption** [comment]
Same usecase, same error nearly two years later.

As requests are cancelled by chrome, my loading spinner won't disappear.

**Comment by vladjerca** [comment]
@maximedupre No, I was just describing an underlying proposal for how I think this should be handled within the engine.

**Comment by vladjerca** [comment]
For people that are still struggling with this, until this is officially solved I bet you can get away with simply providing your own `XhrFactory` and hooking the `onabort` to call the `onerror` before returning the `XMLHttpRequest`.

``` ts
// define your abort handler
@Injectable()
export class BrowserXhrWithAbortError implements XhrFactory {
    constructor() { }

    build(): any {
        const request = <any>(new XMLHttpRequest());

        request.onabort = (ev) => request.onerror && request.onerror(ev);

        return request;
    }
}

// then simply provide the new factory in the root module
@NgModule({
  declarations: [...],
  imports: [...],
  providers: [{
        provide: XhrFactory,
        useClass: BrowserXhrWithAbortError,
  }],
  bootstrap: [...]
})
export class AppModule {}
```

**Comment by dcalvoj** [comment]
is there any news on this? 
My spinner doesn't disappear when a request is cancelled in a text search box, because swichmap cancels the requests and my http interceptor doesn't capture it.
I also haven't known how to apply the solution proposed by @vladjerca.

**Comment by ruimarques** [comment]
I suspect i bumped into another use case where this issue is relevant.

I created a custom Async Validator (FormControl), these have an issue, or call it a gotcha, that if the observable (say a request you make to do the validation) does not complete, the control status stays stuck with 'PENDING' instead of moving to 'VALID' / 'INVALID'.

So basically seems if validation runs often enough that it cancels previous requests (quite easy to achieve if no debounce is done), validation status will be stuck in 'PENDING'.

**Comment by luisfpg** [comment]
The (workaround)[https://github.com/angular/angular/issues/22324#issuecomment-562401163] proposed by @vladjerca doesn't work in Angular 9.

It is not possible to apply any workaround because Angular's implementation removes the listeners before calling the abort method:
https://github.com/angular/angular/blob/698b0288bee60b8c5926148b79b5b93f454098db/packages/common/http/src/xhr.ts#L332
I'm pretty sure that just adding a `observer.complete()` just after https://github.com/angular/angular/blob/540c29cd6bfc4124a30f5f8e7b599d326baf6af4/packages/common/http/src/xhr.ts#L342 would fix it.

I couldn't find any workaround that could fix this.

**Comment by jankowskip** [comment]
Really hoping for this to be fixed, been looking for solution as a workaround i do: 

```
  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return handleApiRequest(this.store)(next.handle(req));
  }
}

function handleApiRequest<T>(store: Store<State>) {
  return (obs: Observable<T>) => {
    return new Observable(subscriber => {
      const sub = obs.subscribe(
        value => {
          if (!(value instanceof HttpResponse)) {
            console.log("request started");
          }
          return subscriber.next(value);
        },
        err => subscriber.error(err),
        () => subscriber.complete()
      );
      return () => {
        console.log("request finished");
        sub.unsubscribe();
      };
    });
  };
}
```
Found this approach on alxhub answer https://github.com/angular/angular/issues/32909#issuecomment-542427879

**Comment by alxhub** [comment]
Wow, this is super interesting.

I generally agree with a new `HttpEventType` that tracks the `abort` event, and lets you know that forces beyond your control have decided your request is no longer going to continue.

**Comment by bernard-ng** [comment]
Any progress on this?

**Comment by ItNoN** [comment]
Hello there, 

I've made a PR based on @curdwithraisins solution to fix this error. I would be pleased if you supported it [#40767](https://github.com/angular/angular/pull/40767).

Thanks!
