### ISSUE TITLE
feature(compiler): able to get reference of direct context in template

### ISSUE THREAD

**Issue by trotyl** [angular/angular#22323]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In template, `this` keyword will always refer to the component context even if inside `<ng-template>`:

```html
<p>In component: {{ this.process(this) }}</p>
<!-- comp.process(comp) -->
<ng-template ref-temp>
  <p>In template: {{ this.process(this) }}</p>
  <!-- comp.process(comp) -->
</ng-template>
<ng-container *ngTemplateOutlet="temp; context: foo"></ng-container>
```

It will be quite troublesome to retrieve the entire template context (rather than specific property).

## Expected behavior

There should be another keyword which always refer to real context:

```html
<p>In component: {{ $context.process($context) }}</p>
<!-- comp.process(comp) -->
<ng-template ref-temp>
  <p>In template: {{ $context.process($context) }}</p>
  <!-- foo.process(foo) -->
</ng-template>
<ng-container *ngTemplateOutlet="temp; context: foo"></ng-container>
```

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-ngjupk?file=app%2Fapp.component.html

## What is the motivation / use case for changing the behavior?

The shape of context may be unknown or has dynamic keys so spreading is required.

## Environment

<pre><code>
Angular version: *

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

Relates to #10406, which is infeasible as there indeed need to be two contexts.
Relates to #22208 for the extra compiler work.

There can be a workaround by [intercepting the `TemplateRef`](https://github.com/trotyl/ng-vdom/blob/418b82e4dd08940aaa5c45fa275304ca5a28551e/src/lib/providers/vdom-util.ts#L10-L15), even it's still technically public API usage, but looks hacky and require deep knowledge.

**Comment by jessicajaniuk** [comment]
Closing this as it's unclear what the use case for it would be. If you see this as a need, please open a new feature request and outline the use case for us so we can understand the reasoning for adding a feature like this.
