### ISSUE TITLE
Cannot use `typeof` with AoT - Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by brunolm** [angular/angular#22320]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Compile error

```
typescript error
Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing
the function or lambda with a reference to an exported function (position 26:40 in the original .ts file),
resolving symbol MobileAwareHostListener in
.../event-listener.decorator.ts, resolving symbol HomePage in
.../home.ts

Error: The Angular AoT build failed. See the issues above
```

## Expected behavior
Compile without errors

## Minimal reproduction of the problem with instructions
- make a file exporting a function
- inside this function return a value using a ternary operator or if/else
- if condition should be `typeof document.ontouchstart === 'undefined'`
- call this function in any component
- build project --prod and aot

Full example: https://stackoverflow.com/q/48873883/340760
Notes: In the example changing `const` to `function` solves part of the issue, I can't use `typeof` that is still an issue.

## What is the motivation / use case for changing the behavior?
Why can't I use `typeof`? That is one of the most used features, is that no supported on AoT? Or is it because something specific I'm doing?

## Environment

<pre><code>Angular version: 5.0.3

Browser: N/A
 
For Tooling issues:
- Node version: 9.5.0 
- Platform:  Windows / Mac

Others: N/A
</code></pre>

**Comment by vicb** [comment]
You don't include a complete repro here but it seems like you have dynamic code in your annotations. This is what is wrong as they need to be resolved at compile time.

**Comment by vahidvdn** [comment]
I have the same issue. Any workaround?
