### ISSUE TITLE
Commenting inner html attributes 

### ISSUE THREAD

**Issue by d-damien** [angular/angular#22328]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
It is not possible to comment html attributes natively, but it is possible in several template languages, see [examples](https://stackoverflow.com/questions/14020482/how-to-comment-within-an-html-attribute/14020499#14020499).

## Expected behavior
Some commenting syntax, ideally with both begin+end or single line, but one of them would be enough I guess.

## What is the motivation / use case for changing the behavior?
Considering templates and template binding are some core concepts in Angular, and that you may find yourself dealing with big sets of attributes, a way to comment them without commenting the whole component would be a nice add.

**Comment by trotyl** [comment]
Angular templates need to be valid HTML (in syntax), so the begin + end style may not feasible, but the idea itself may be valid.

What's your concrete cases for this feature that cannot be done by binding to a default value of the attribute or corresponding property?

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by d-damien** [comment]
When you have several components having lots of simple interactions through variable changes within the template (= not using typescript for this, hence no ts comments), and you want to change or tweak them in some way, temporary mute (aka comment) them is useful.

When you have some variable binding problems (inducing some infinite loop or deadlock, generally with `ngModel`), so you need to test with/without combinations.

When you want some todo-like reminder for later.

Otherwise, you have to either comment the component entirely (making twice the code lines) or get the commented line out of the component, which messes it up.

Had all of those on an date or integer interval kind of component (example code) :

``` html
<input
  #leftInput
  matInput
  [min]="min"
  [max]="right"
  [(ngModel)]="left"
  (keydown)="onkey(false, $event)"
/>
<button
  (click)="left = left*2 > right ? right : left*2">
  x2 button
</button>

<!-- need to comment ngModel here -->
<!--  [(ngModel)]="right" -->
<input
  #rightInput
  matInput
  [min]="left"
  [max]="max"
 
  (keydown)="onkey(true, $event)"
/>
