### ISSUE TITLE
Templates - GUID template parse failure

### ISSUE THREAD

**Issue by Wayne-Mather** [angular/angular#22341]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I am unable to use GUID identifiers as input parameters to a child component.

```
compiler.js:485 Uncaught Error: Template parse errors:
Parser Error: Unexpected token Lexer Error: Invalid exponent at column 1 in expression [0efde954-e523-4f88-ad25-4efbda9b5a1e] at column 2 in [0efde954-e523-4f88-ad25-4efbda9b5a1e] in ng:///AppModule/AppComponent.html@0:51 ("<app-history [records]="30" [shellDimValId]="5205" [ERROR ->][shellDimLocId]="0efde954-e523-4f88-ad25-4efbda9b5a1e">

</app-history>"): ng:///AppModule/AppComponent.html@0:51
Parser Error: Lexer Error: Invalid exponent at column 1 in expression [0efde954-e523-4f88-ad25-4efbda9b5a1e] at column 2 in [0efde954-e523-4f88-ad25-4efbda9b5a1e] in ng:///AppModule/AppComponent.html@0:51 ("<app-history [records]="30" [shellDimValId]="5205" [ERROR ->][shellDimLocId]="0efde954-e523-4f88-ad25-4efbda9b5a1e">

</app-history>"): ng:///AppModule/AppComponent.html@0:51
Parser Error: Lexer Error: Invalid exponent at column 25 in expression [0efde954-e523-4f88-ad25-4efbda9b5a1e] at column 26 in [0efde954-e523-4f88-ad25-4efbda9b5a1e] in ng:///AppModule/AppComponent.html@0:51 ("<app-history [records]="30" [shellDimValId]="5205" [ERROR ->][shellDimLocId]="0efde954-e523-4f88-ad25-4efbda9b5a1e">

</app-history>"): ng:///AppModule/AppComponent.html@0:51
    at syntaxError (compiler.js:485)
    at TemplateParser.parse (compiler.js:24668)
    at JitCompiler._parseTemplate (compiler.js:34621)
    at JitCompiler._compileTemplate (compiler.js:34596)
    at eval (compiler.js:34497)
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.js:34497)
    at eval (compiler.js:34367)
    at Object.then (compiler.js:474)
    at JitCompiler._compileModuleAndComponents (compiler.js:34366)
syntaxError @ compiler.js:485
TemplateParser.parse @ compiler.js:24668
JitCompiler._parseTemplate @ compiler.js:34621
JitCompiler._compileTemplate @ compiler.js:34596
(anonymous) @ compiler.js:34497
JitCompiler._compileComponents @ compiler.js:34497
(anonymous) @ compiler.js:34367
then @ compiler.js:474
JitCompiler._compileModuleAndComponents @ compiler.js:34366
JitCompiler.compileModuleAsync @ compiler.js:34260
CompilerImpl.compileModuleAsync @ platform-browser-dynamic.js:239
PlatformRef.bootstrapModule @ core.js:5563
(anonymous) @ main.ts:12
../../../../../apps/shellhistory/src/main.ts @ main.bundle.js:96
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:119
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1

```

## Expected behavior

I should be able to use this string as an input

## Minimal reproduction of the problem with instructions
Create a standard NG Cli app and build your component so it supports the following:

`<app-child  [input_as_string]="0efde954-e523-4f88-ad25-4efbda9b5a1e"></app-child>`

## What is the motivation / use case for changing the behavior?

We heavily use GUID's inside our system so being able to inject these are the parent level is a must. 

## Environment

<pre><code>
Angular version: 5.2.0

For Tooling issues:
- Node version: v9.5.0 
- Platform:  Windows 

Others:

</code></pre>

**Comment by Toxicable** [comment]
A GUID is not a type in JS.
Use it as a string.

**Comment by jotatoledo** [comment]
By doing

`<app-child [input_as_string]="0efde954-e523-4f88-ad25-4efbda9b5a1e"></app-child>`

You are binding the input_as_string property to a [template expression ](https://angular.io/guide/template-syntax#template-expressions), which angular will try to evaluate into a value.

In this case, you should avoid the brackets as explained in [the docs](https://angular.io/guide/template-syntax#one-time-string-initialization)

**Comment by Wayne-Mather** [comment]
@jotatoledo - Ok, got it. Just all examples I saw for input used []. Will test when back at work but will consider this closed and my problem not the frameworks.
