### ISSUE TITLE
Animation and css style not working properly if keep mouseenter and mouseleave

### ISSUE THREAD

**Issue by minhui27** [angular/angular#22342]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I keep mouseenter and mouseleave on a div (fast moving), the animation and the css style of the div is not working properly.
The image below is the one of styling error when mouseenter the div:
![error](https://user-images.githubusercontent.com/18694106/36470413-afb781be-1725-11e8-812f-608d337efcb5.JPG)

## Expected behavior
All the animation and css style should work as stated in the animation styling.
- mouseleave: all the words become transparent or the opacity change to 0
- mousenter: all the words remain in white color or the opacity is 1

Therefore, when mousenter the div, it should be like this:
![expected](https://user-images.githubusercontent.com/18694106/36470343-7a4df4fe-1725-11e8-9f34-152a25c3a83e.JPG)

## Environment

<pre><code>
Angular version: 5.2.5

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.9.4
- Platform:  Windows
</code></pre>

**Comment by vicb** [comment]
Please attach a **minimal** repro otherwise there is no way we can help.

**Comment by minhui27** [comment]
@vicb  The demo link is [https://github.com/minhui27/angular-5-animation-test](https://github.com/minhui27/angular-5-animation-test).

**Comment by matsko** [comment]
@minhui27 any chance you could make a stackblitz demo and reduce the example to a smaller size? It's hard figuring out exactly what's breaking.

**Comment by vicb** [comment]
Closing as the minimal provided was not provided
