### ISSUE TITLE
Back button weird delay when used inside WebView (Cordova)

### ISSUE THREAD

**Issue by creativeprogramming** [angular/angular#22348]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Back button pressed while running an angular app inside a cordova webview presents a strange random delay between router state changes, occasionally with glitches

## Expected behavior
Back button working fine

## Minimal reproduction of the problem with instructions
Cannot provide a demo link, issue is in angular app deployed to cordova app (android webview)

**Comment by jotatoledo** [comment]
Without reproduction this issue isn't actionable.

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
