### ISSUE TITLE
Missing documentation on cli config for universal app

### ISSUE THREAD

**Issue by jcampbell05** [angular/angular#22349]
In the example code at https://angular.io/guide/universal#universal-in-action there is an entry for the server app which is lacking in the tutorial itself.

It also misses an example  for the `main.server.ts` both in the tutorial and the file itself.

Without this, the code doesn't work.

**Comment by Yerkon** [comment]
@jcampbell05,
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #21983. Please subscribe to that issue for future updates.

**Comment by petebacondarwin** [comment]
Thanks for spotting the duplicate @Yerkon
