### ISSUE TITLE
 WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by jsmozila1988** [angular/angular#22343]
Browser : Chrome Version 64.0.3282.167 (Official Build) (64-bit)
Angular CLI: 1.7.0
Node: 8.9.4
OS: win32 x64

As application start to loads in the chrome browser it's showing below given error in the console : 
**websocket.js:6 WebSocket connection to 'ws://localhost:4200/sockjs-node/938/zyveyd3w/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400**
After this all the apis requests failed.
**OPTIONS http://user-service:3010/login net::ERR_EMPTY_RESPONSE**

Please share any solution for this.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by robwormald** [comment]
this is not an Angular issue.
