### ISSUE TITLE
Documentation Request: How to have multiple build outcomes for the dgeni angular documentation project

### ISSUE THREAD

**Issue by DinoSourcesRex** [angular/angular#22347]
## I'm submitting a...
[X] Documentation issue or request

## Current behavior
I have a single documentation project which has documentation for all of my products.
-Project A
-Project B
-Shared Documents

I need to be able to create 2 documentation builds, 1 for Project A and another for Project B.

There are two issues; first the navigational sidepanel (which I have resolved with some custom code + an environment file to pick the correct navigation.json) and the second is selecting which folders / files should be copied to the project dist.

Currently I have created another content-package, is this the original intention?

## Expected behavior
To have documentation on how to handle multiple build outcomes from a single source

## What is the motivation / use case for changing the behavior?
As a user I must be able to generate different distributables from a single source based on which project I am building.

## Environment
Angular version: 5.0.0 beta
 
For Tooling issues:
- Node version: v8.9.4
- Platform:  windows

**Comment by trotyl** [comment]
Should be open in [angular/dgeni](https://github.com/angular/dgeni)?

**Comment by DinoSourcesRex** [comment]
@trotyl My reason for opening it here was because we originally cloned this repo as a base. I suppose the documentation can go anywhere.

I would say that if the documentation does go there that there should be at least a link to the [angular/dgeni](https://github.com/angular/dgeni) from [/aio/README.md](https://github.com/angular/angular/tree/master/aio) for visibility, as I, for one,  didn't even know about that repo let alone think to look there.

**Comment by petebacondarwin** [comment]
@DinoSourcesRex - I'm sorry that you were confused. The documentation for angular.io is generated by the tool called Dgeni. There is actually a link to it in the readme that you mentioned, although I accept it is not that prominent. See https://github.com/angular/angular/tree/master/aio#guide-to-authoring. The configuration for generating the Angular docs (i.e. what is held in this repo) is not supposed to provide a starting point for generating your own app's documentation. It is tuned specifically to our requirements, for generating the docs for the Angular library.

If you want to generate docs for your own app then you must configure Dgeni yourself. I would take a look at the [Dgeni](https://github.com/angular/dgeni) repo and also the [Dgeni Packages](https://github.com/angular/dgeni-packages) repo. This is where a lot of the processors are held that do the documentation generation work. You can also look at how other projects have configured Dgeni to create docs. For instance https://github.com/angular/material2/tree/master/tools/dgeni.

**Comment by DinoSourcesRex** [comment]
Thanks @petebacondarwin . I can't actually believe I missed the link twice, though I do see it now that you've pointed it out.

I've gotten something working for this, in any case, I just don't think it's done in the way the dgeni folks intended it. I'll continue my search over there.

Thank you both!

**Comment by petebacondarwin** [comment]
@DinoSourcesRex - feel free to email me directly with questions as I wrote most of the dgeni code.

**Comment by DinoSourcesRex** [comment]
I thought your name seemed familiar, must have seen it through gitlens. I may take you up on that! Thanks!
