### ISSUE TITLE
Method parameters are unclear on Renderer2 from @angular/core 

### ISSUE THREAD

**Issue by peter-gergely-horvath** [angular/angular#22344]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
`Renderer2` from `@angular/core` has a number of methods to perform changes in the DOM that are barely documented and the parameters are of type `any`, which makes it hard to figure out what is actually expected there. See the [API docs](https://angular.io/api/core/Renderer2)

E.g. `setStyle(el: any, style: string, value: any, flags?: RendererStyleFlags2): void` or 
`appendChild(parent: any, newChild: any)`: how am I supposed to know what is to be passed to the method? Is it a native `Element`, an Angular `ElementRef`,  a selector or something else? 

The beauty of type checked TypeScript APIs would be that they are more or less self-documenting what is expected as parameters and more importantly, fail-fast when with compilation error if you use something incorrectly.
Specifying `any` destroys the whole concept and causes a lot of pain on the Angular developers' side.

## Expected behavior

   * The API should be properly documented. Explaining what the methods do and what the expected parameters are.
  * Specify the acceptable parameter type / types: avoid using `any` where there is a specific type expected. 

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?

N/A

## Environment
N/A
<pre><code>
Angular version: CURRENT

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by JoostK** [comment]
The `Renderer2` class has been extended with docs in f1ab3942187b52effeb74aac9c5f242e94f812ca.
