### ISSUE TITLE
optimizationterminate called after throwing an instance of 'std::bad_alloc' while running ng build --aot -prod

### ISSUE THREAD

**Issue by techyaura** [angular/angular#22354]
![gcp_angular](https://user-images.githubusercontent.com/5227618/36504610-1c835772-1777-11e8-8f83-7641ee5ac9d5.png)

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
