### ISSUE TITLE
Tour Of Heroes, Chapter 7 (Routing): src/app/hero.service.ts is missing from Final code review

### ISSUE THREAD

**Issue by Mavbraz** [angular/angular#22359]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Final code review doesn't have the file src/app/hero.service.ts

## Expected behavior

Final code review has the file src/app/hero.service.ts

## Minimal reproduction of the problem with instructions

1. Open https://angular.io/tutorial/toh-pt5
2. Find the "Add HeroService.getHero()" step (step to change src/app/hero.service.ts)
3. Now, make sure the "Final code review" has the HeroService

## What is the motivation / use case for changing the behavior?

Improve the quality of documentation

**Comment by kapunahelewong** [comment]
Thank you for spotting this, @Mavbraz. PR submitted! :)

**Comment by jenniferfell** [comment]
Fixed per PR #22373
