### ISSUE TITLE
ng test produces => Can't bind to 'ngModel' since it isn't a known property of 'input'

### ISSUE THREAD

**Issue by omurbekjk** [angular/angular#22361]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`ng serve` compiles and gives no error.
While running `ng test` produces `Can't bind to 'ngModel' since it isn't a known property of 'input'`.
I imported `FormsModule` already.
## Expected behavior

It should not give any errors

## What is the motivation / use case for changing the behavior?

Clone the repo `https://github.com/jacho-academy/learn-angular5.git`,
Run `npm install`, then `ng test`

## Environment

<pre><code>
Angular CLI: 1.7.1
Node: 8.9.4
OS: linux x64
Angular: 5.2.6

Browser:
- [x] Chrome (desktop) version 64, ubuntu
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:

Others:

</code></pre>

**Comment by omurbekjk** [comment]
Fixed, by importing `FormsModule` in the imports property of the `Testbed` configuration object.

**Comment by jimshowalter** [comment]
Ran into the same problem. It would be nifty if the testbed could figure out what it needs by looking at the working code that it is testing.
