### ISSUE TITLE
Cannot resolve router after update to 5.2.6

### ISSUE THREAD

**Issue by vincent-cm** [angular/angular#22366]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

ERROR in ./src/app/xxxxxxx.ts
Module not found: Error: Can't resolve 'xxxxxx/src/node_modules/@angular/router' in 'xxxxxx/src/app/xxxxxxx'
 @ ./xxxxxxx.ts 7:15-41
 @ ./xxxxxxx.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/main.browser.ts

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vincent-cm** [comment]
https://www.npmjs.com/package/@ngtools/webpack 1.10.1 bug

**Comment by almothafar** [comment]
Wasted 4 hours trying to figure out what the issue, finally got the solution, thanks a lot
