### ISSUE TITLE
Assets Folder issue..in Angular 4

### ISSUE THREAD

**Issue by KSANTHOSHKUMA** [angular/angular#22367]
Hi All,

I am creating roles in my Angular 4 Application, after creating a role successfully one JSON file is generated from back end ( JSON file contains List of Menu Items which user can access)
I am storing these JSON files in Assets folder. and i am using these files to build side menu.

but the issue is when i am trying to log in with new role(immediately after creating new role), side menu is not building even though the corresponding role's JSON file is exist in Assets folder. When i restart the lite server with ng serve and login with new role then side menu is showing. i.e., changes/ new updates in assets folder are not reflecting if we don't rerun the ng server in @angular/cli

but refreshing / restarting the lite server is not a good practice.

how to resolve it with out restarting the lite server.

Thanks in advance.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
