### ISSUE TITLE
Want to know the behavior of encodeURI(tree.fragment !)

### ISSUE THREAD

**Issue by xeodou** [angular/angular#22365]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Get a bit confusing read the source code at https://github.com/angular/angular/blob/5.2.6/packages/router/src/url_tree.ts#L283 
```
 serialize(tree: UrlTree): string {
    const segment = `/${serializeSegment(tree.root, true)}`;
    const query = serializeQueryParams(tree.queryParams);
    const fragment = typeof tree.fragment === `string` ? `#${encodeURI(tree.fragment !)}` : '';

    return `${segment}${query}${fragment}`;
  }
```
, it uses a function `encodeURI` but the parameter with a `!` at the end.  I haven't see the usage at MDN https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI or Typescript document. I would know what is the behavior of the `!`. Thanks a lot.

## Environment

<pre><code>

Angular version: 5.2.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator

**Comment by xeodou** [comment]
Thanks @trotyl
