### ISSUE TITLE
Failed to load resource: the server responded with a status of 504 (Gateway Timeout)

### ISSUE THREAD

**Issue by chamikasandamal** [angular/angular#22362]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Angular service worker application throws following error

> Failed to load resource: the server responded with a status of 504 (Gateway Timeout)
`ng new my-project --service-worker`

## Expected behavior

It should not throw any exceptions

## Minimal reproduction of the problem with instructions
`ng new my-project --service-worker`
`ng build --prod`
`cd dist
http-server -p 8080`
Even with IIS host i can see the same issue.

## Environment

<pre><code>
Angular version: 5.2.6

Browser:
- [x] Chrome (desktop) version 64.0.3282.167
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v9.5.0  
- Platform:  Windows 

Others:

</code></pre>

**Comment by EreckGordon** [comment]
It seems to trigger for me on any url, only the first time opening dev tools while viewing the site. If you close the tab, then reopen the site and reopen dev tools the error appears again.

I don't use hash routing. Here's a site demonstrating the issue:

https://universal-demo.ereckgordon.com/

**Comment by gkalpak** [comment]
@akilmakda, this sounds like a different issue. If you think it is related to `@angular/service-worker`, please open a new issue and provide all relevant details (including a minimal reproduction).

**Comment by akilmakda** [comment]
@gkalpak  

![504 timeout](https://user-images.githubusercontent.com/24309502/37905955-364d1448-311e-11e8-8ccb-8b4f0eb4073d.png)

**Comment by gkalpak** [comment]
@akilmakda, the error message (which comes from the browser, not `@angular/service-worker`) explains why it is failing. I don't think this is related to Angular's ServiceWorker.

(In any case, this issue is not the place to discuss unrelated problems. If you still think there is an issue with `@angular/service-worker` please open a new isue.)

**Comment by akilmakda** [comment]
Create new issue #23012
