### ISSUE TITLE
Problem in demo: dynamic-component-loader

### ISSUE THREAD

**Issue by stason4ik** [angular/angular#22371]
https://angular.io/docs/ts/latest/cookbook/dynamic-component-loader.html

Error:
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'Bombasto'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?

**Comment by Yerkon** [comment]
Hi @stason4ik,
Please look at this issue #22020

**Comment by jenniferfell** [comment]
Fixed by https://github.com/angular/angular/pull/22181. See comments on https://github.com/angular/angular/issues/21903 for more info about the fix.
