### ISSUE TITLE
angular 4: get data from http response

### ISSUE THREAD

**Issue by ahmedhassanahmedwasfy** [angular/angular#22377]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

 i cannot access inner array of the response data sometimes ,I use promise to get the response of service  

this._page_Service.GETsync(`/Groups/Get?ID=${this.ID}`)     
       .then((res: Response) => {    
      console.log('res json',res.json() as GenericResponse); 
         this._result=null;   this._result=  res.json() as GenericResponse  ;          console.log('this._result',this._result  ); }

 but the result as following:{Success: true, Message : "success" Success : true data : CreateDate : "2018-02-22T02:54:02.37" CreateUserID : 10 ID : 1150 ModifyDate : "2018-02-22T02:54:02.37" ModifyUserID : 10 NameAr : "wdqewdwdqewd" NameEn : "wdqewdwdqewd" **Privilliges {NameEn: "SecurityModel", NameAr: "SecurityModel", Groups: Array(0), Users: Array(0), CreateUserID: 1, …}**
please note that **Privillige** array has one record but the second log has no record

Message : "success" Success : true data : CreateDate : "2018-02-22T02:54:02.37" CreateUserID : 10 ID : 1150 ModifyDate : "2018-02-22T02:54:02.37" ModifyUserID : 10 NameAr : "wdqewdwdqewd" NameEn : "wdqewdwdqewd" **Privilliges : Array(0)**
finally please note that it sometimes works good and sometimes not working and i got crazy about that so i appreciate your help

## Expected behavior

I was expecting Privillige array to be the same at both cases

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@ahmedhassanahmedwasfy ... the formatting of your response data looks really strange ... you are talking about arrays but do you see those arrays? I would expect an array syntax as ... `anArray: [{...},{...},...]` but there is nothing like that. You description is totally confusing.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
