### ISSUE TITLE
aio + api/docs - github link text is too big

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#22379]
<img width="197" alt="screen shot 2018-02-22 at 20 44 46" src="https://user-images.githubusercontent.com/15655/36563225-5be2d6e6-1811-11e8-9f02-df84b59b50ff.png">

The text on these buttons seems disproportionately big compared to the rest of the page; and the "Suggest Edits" link doesn't fit a single line.

**Comment by sjtrimble** [comment]
Original design for reference:

![aio-interactive-buttons](https://user-images.githubusercontent.com/2958442/36680554-edffe72e-1aca-11e8-90dc-8a033e34f778.PNG)

1. Font size should be 12 px, which will make it fit a bit better, along with a minimum width
2. Min width can be adjusted
3. Content should be left aligned (with possible space on the right side after text if text is longer on one item than another

Idea --- we could change it to either A) shorten the text to say 'Edit' and 'Source' only, or B) icons only with tooltips on hover (I like this but less straight forward for the user). What do you think? Is Option B obvious enough?
![interactive-buttons1](https://user-images.githubusercontent.com/2958442/36680891-e3b7d65e-1acb-11e8-911e-8f3d0d11223b.png)
![interactive-buttons2](https://user-images.githubusercontent.com/2958442/36680892-e594eba6-1acb-11e8-94bc-de11b5172bf4.png)

Option B would be nice for mobile regardless!

**Comment by sjtrimble** [comment]
The more I think about it the more I like the very last option :) with either format of the action buttons, but I do like the clean icon-only option, followed by full text as we had.

**Comment by petebacondarwin** [comment]
I like the icon only option. Putting these links above the ToC would be technically challenging since that is outside the doc-viewer's area of control.

**Comment by kapunahelewong** [comment]
oooh I like the icon-only version. It's clean and intuitive, and it's just like GitHub's.

**Comment by petebacondarwin** [comment]
I'll knock up an icons only PR

**Comment by Narretz** [comment]
I think icons only doesn't draw enough attention to the buttons, therefore it's less likely they will be used. 

Another thing with the text button is however that  on small screens they overlap with the description.

**Comment by splincode** [comment]
Are there any suggestions for translations?

How is this done on such a known resource?
https://developer.mozilla.org/ru-RU/

You can usage medium.io editor (which works great with markdown for md files):

![image](https://user-images.githubusercontent.com/12021443/36847687-275f843c-1d70-11e8-89bb-c8259904bf5f.png)

**Comment by petebacondarwin** [comment]
@splincode - please could you open a new issue for the question of translation.

**Comment by petebacondarwin** [comment]
Having spoken with @jbogarthyde and @jenniferfell I am going to implement the icon only button right aligned on the same row as the breadcrumbs.

**Comment by splincode** [comment]
@petebacondarwin pin https://github.com/angular/angular/issues/20542#issuecomment-369596554

**Comment by splincode** [comment]
@petebacondarwin I meant, will you be offered a convenient editor for editing the documentation?

**Comment by petebacondarwin** [comment]
@splincode - please create new issues for new topics. It is distracting and confusing to ask off-topic questions as comments on issues that are about other things.

**Comment by splincode** [comment]
@petebacondarwin Sorry, but my topics are closed by making links to these 2 topics:
https://github.com/angular/angular/issues/20542
https://github.com/angular/angular/issues/22379
