### ISSUE TITLE
[ivy] DirectiveDef properties may need better names

### ISSUE THREAD

**Issue by marclaval** [angular/angular#22383]
PR #22352 triggered a naming discussion on the properties of `DirectiveDef` interface:
https://github.com/marclaval/angular/blob/8850381cb228dbad21d9fd70177cfc842672a8ac/packages/core/src/render3/interfaces/definition.ts#L39-L59

@vicb proposed the following terminology for the 3 information we need for inputs:
- alias = the name given in the decorator,
- property name = source code,
- minified name

Let's discuss if and how we should rename 'inputs', 'inputsPropertyName' and 'outputs'.

**Comment by mhevery** [comment]
obsolete since we now only have `inputs` and `outputs`.
