### ISSUE TITLE
Directive example has errors

### ISSUE THREAD

**Issue by mcalmus** [angular/angular#22382]
## I'm submitting a...

<pre><code>
[X] Documentation issue or request
</code></pre>

## Current behavior

The Directive documentation (https://angular.io/api/core/Directive) has an example in the inputs section that uses "bankName" as the class variable, but the usage example in the same code uses "bank-name". In addition, the "live demo" link (http://plnkr.co/edit/ivhfXY?p=preview) is incredibly out of date (trying to use 2.0.0-alpha.37) and no longer works.

## Expected behavior

Syntactically correct example code and working live demo.

## What is the motivation / use case for changing the behavior?

Accurate documentation

**Comment by petebacondarwin** [comment]
@vicb this is not an AIO issue as it is purely related to the docs and not to the AIO application or doc generation infrastructure.

**Comment by dariobraun** [comment]
Variable names are fixed. Not sure if the live demo link is still relevant. Maybe this issue can be closed?

**Comment by pkozlowski-opensource** [comment]
It is `bankName` only now at https://angular.io/api/core/Directive
