### ISSUE TITLE
Need to be able to run test on SauceLabs

### ISSUE THREAD

**Issue by vicb** [angular/angular#2239]
It would be nice to be able to `gulp test.* --sauce` and even nicer `gulp test.* --sauce --browser=ie9,chrome` when we need to test across browsers, ie #2238 

We should also use it for the CI on the current working set of browsers (and capture other browsers as they start to work)

/cc @mlaval

**Comment by juliemr** [comment]
Note that this won't work for dart tests since Dartium isn't available on Sauce Labs.

**Comment by gdi2290** [comment]
this is a dup of https://github.com/angular/angular/issues/2239

**Comment by vicb** [comment]
@gdi2290 recursive comment ?

**Comment by gdi2290** [comment]
@vicb oops I meant to make that comment here https://github.com/angular/angular/issues/35

**Comment by vicb** [comment]
Not a exactly a dup, the primary intent of this one is to be able to test locally which is helpful during dev. 35 is more about adding all supported browsers to the CI.

**Comment by pkozlowski-opensource** [comment]
Initial support for running tests on Sauce landed through eebd736cfe557c0d83b59652134d9aaa46476344. If more needs to be done we should open separate, more focused issues.
