### ISSUE TITLE
response from service is UNDEFINED when assigned to local variable?!

### ISSUE THREAD

**Issue by nkengasongatem** [angular/angular#22393]
Okay i'm confused and need your help guys, below is the cause:

 getStudent(): void { // get student id from url
    this.student_id = +this.route.snapshot.paramMap.get('id');
    this.portalService.getStudent(this.student_id)
        .subscribe(res => (this.student = res));
  }

So, i am correctly getting the student data from my backend. Proof is that i see it when i alert it. The problem comes when i assign the res as so:   this.student = res
when i echo this in my ngOnInit method it is UNDEFINED. Please can  you help me???

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
