### ISSUE TITLE
Unable to dynamically add change event to an external mat-select component in angular 4

### ISSUE THREAD

**Issue by rpusarla** [angular/angular#22391]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Unable to dynamically add change event to an external mat-select dropdownlist component in angular 4

## Expected behavior
There should be a provision to dynamically add events to angular 4 material components.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gitter-6o37hi?file=app%2Fapp.component.ts

## What is the motivation / use case for changing the behavior?

Would like to reuse the mat-select dropdown list in many other components and also would be able to add events dynamically.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version 63.0.3239.132
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:   Windows

Others:

</code></pre>

**Comment by alexeagle** [comment]
I think this issue belongs on http://github.com/angular/material2/issues ?
