### ISSUE TITLE
click vs mousedown event (reproduced with a github page)

### ISSUE THREAD

**Issue by Jun711** [angular/angular#22390]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When clicking an absolute positioned and higher z-index element, click event is not fired but mousedown event is fired. 
When I tap on a dropdown list(second list) item, I can select the item.
When I click with a mouse or click on my touchpad, I can't select the item.  
It could be my CSS problem?

## Question
From definitions of click and mousedown that I found on MDN. It seems that the difference is mousedown is fired when a press is released. 
I wonder how Angular treats click and mousedown. 

The [click](https://developer.mozilla.org/en-US/docs/Web/Events/click) event is fired when a pointing device button (usually a mouse's primary button) is pressed and released on a single element.

The [mousedown](https://developer.mozilla.org/en-US/docs/Web/Events/mousedown) event is fired when a pointing device button is pressed on an element.

## Expected behavior

Expected it to work with click event but it only works with mousedown event as I noticed.

## Minimal reproduction of the problem with instructions

Page: https://jun711.github.io/popcorn/

https://github.com/Jun711/popcorn/blob/06b3f0bf20268ae914fc82f8ccb69f622b880e10/src/app/components/drop-down-list/drop-down-list.component.html#L8
```
<li
    role='Listitem'
    (click)='selectItem(item)'
    *ngFor='let item of listItems; let i = index'
    [class.selected]='i === activeIndex'
    [selected]='i === activeIndex'>{{i + 1}}: {{item.data}}
</li>
```
https://github.com/Jun711/popcorn

## What is the motivation / use case for changing the behavior?

click on a dropdown list item to select the item

## Environment
<pre><code>
macOS Sierra Version 10.12.6
Chrome Version 64.0.3282

ng -v result: 
Angular CLI: 1.7.0
Node: 9.2.0
OS: darwin x64
Angular: undefined
... 
typescript: error
webpack-dev-server: 2.11.1
webpack: 3.11.0

Angular version: 5.2.0

Browser:
- [X] Chrome (desktop) version 64.0.3282
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
Node: 9.2.0
- Platform:  
macOS Sierra Version 10.12.6

Others:

</code></pre>

**Comment by vicb** [comment]
Have you tried to reproduce this in plain html/JS ?
I don't see how Angular would change the behavior here.
Please test and attach a working repro if you have.
Thanks

**Comment by Jun711** [comment]
I attached a repo, I guess you overlooked.
https://github.com/Jun711/popcorn and github page: https://jun711.github.io/popcorn/

Please have a look. thanks

**Comment by IgorKurkov** [comment]
Some similar behavior - when use (click) on mat-input with mat-autocomplete which already contains some data for autocomplete, but data might be already changed - data updates ONLY when I leave mouse button. With mousedown data updates immediately
