### ISSUE TITLE
downgraded components within upgraded are not destroyed

### ISSUE THREAD

**Issue by jbedard** [angular/angular#22392]
## I'm submitting a...
<pre><code>[x] Bug report </code></pre>

## Current behavior
`ngOnDestroy` is not called in some ng-upgrade cases. Also causes the entire DOM of the route to leak, at least in the example outlined.

## Expected behavior
All on-destroy methods should be invoked in both Angular and AngularJS when using ng-upgrade.

## Minimal reproduction of the problem with instructions
watch the console for all component create/destroy events
https://nested-upgrade.stackblitz.io (using router)
https://nested-upgrade2.stackblitz.io (simpler just using `ngIf`)

Essentially...
```
<downgraded-root>
   <router-outlet></router-outlet>
   <upgraded-component>         <--- used-as or nested-within the route component
       <downgraded-component>   <--- ngOnDestroy is not called
   </upgraded-component>
</downgraded-root>
```

The `downgraded-component` [$destroy](https://github.com/angular/angular/blob/5.2.6/packages/upgrade/src/common/downgrade_component_adapter.ts#L213) seems to never be called. Note that the `upgraded-component` [ngOnDestroy](https://github.com/angular/angular/blob/5.2.6/packages/upgrade/src/static/upgrade_component.ts#L218) is called though, so it seems like something is lost between those two?

Note that this has nothing to do with the router, that was just my original use case. Anything that adds/removes a component works.

**Comment by gkalpak** [comment]
Good catch, @jbedard!
(Fix: #22400)
