### ISSUE TITLE
documentation about libraries creation

### ISSUE THREAD

**Issue by jojoblaze** [angular/angular#22396]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
It seems there is a lot of confusion about how to create a library with Angular.
I crawled the web for days, reading tons of articles, but no one seems to work fine.
I think that users really like an "official" article about it.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by robwormald** [comment]
We definitely realize this is somewhat frustrating at the moment, and we want to make it as straightforward as possible. We're currently working on support for this in the 6.0 release, aiming to have the CLI make this automatic. 

More details here : https://github.com/angular/angular-cli/issues/6510

In the interim, there's a good video from Jason here: https://www.youtube.com/watch?v=unICbsPGFIA

The package guidelines are here : https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview

See also ng-packagr - https://www.npmjs.com/package/ng-packagr - we're working with the author of this to roll it into the CLI, so its a good thing to use until we add official support.

Going to close this as we're tracking it in the CLI issue above - this should get better soon!
