### ISSUE TITLE
Docs - h3 heading misaligned inside div

### ISSUE THREAD

**Issue by SeanPrashad** [angular/angular#22407]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The `h3` heading for "[TypeScript interfaces aren't valid tokens](https://angular.io/guide/dependency-injection#typescript-interfaces-arent-valid-tokens)" is misaligned within its `div`.

## Expected behavior
The `h3` heading should be visually left aligned within it's `div` to maintain consistency with other sections.

## Minimal reproduction of the problem with instructions
Open Angular's documentation for  "[TypeScript interfaces aren't valid tokens](https://angular.io/guide/dependency-injection#typescript-interfaces-arent-valid-tokens)"

## What is the motivation / use case for changing the behavior?
To maintain consistency with other sections in the Angular documentation.

## Environment

Angular version: 1.6.9

Browser:
- [x] Chrome (desktop) version 64.0.3282.167 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox 58.0.2 (64-bit)
- [x] Safari (desktop) Version 11.0.3 (13604.5.6)
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
## GIF of Bug

![angularheadingbug](https://user-images.githubusercontent.com/13009507/36607521-ddb6b7b8-1894-11e8-80a5-7b2ae6715179.gif)

Upon closer inspection inside Chrome's dev tools, it looks like the heading isn't being properly aligned for a CSS reason:

<img width="1203" alt="screen shot 2018-02-23 at 12 34 03 pm" src="https://user-images.githubusercontent.com/13009507/36607834-e6b0ce7a-1895-11e8-8477-02c134630751.png">

## Potential Fix
A potential fix might be adding `padding-left: 34px;` to `.l-sub-section h3` found in `_subsection.scss:13`. This would result in the following:

<img width="1083" alt="screen shot 2018-02-23 at 12 37 53 pm" src="https://user-images.githubusercontent.com/13009507/36608055-9f8b04c4-1896-11e8-925d-e085e57539de.png">

**Comment by petebacondarwin** [comment]
+1 Do you want to provide a PR?
cc @sjtrimble

**Comment by sjtrimble** [comment]
`padding-left` as @SeanPrashad recommends would work as intended 👍 

Side note, should we actually have h3s inside of a subsection though? Seems a bit odd from a content hierarchy perspective.

**Comment by SeanPrashad** [comment]
I would love to actually help walk a new OSS contributor, [@haoRchen](https://github.com/haoRchen), through building Angular and submitting his PR in the next few days if that's ok!

**Comment by haoRchen** [comment]
After looking into this issue, and applying @SeanPrashad 's fix, I noticed that the header is not being aligned properly in mobile/responsive view. See below:

<img width="438" alt="mobile view error" src="https://user-images.githubusercontent.com/19397242/36632213-bcee11b2-1951-11e8-8fbc-c1b1fc9d0987.png">

Should I proceed with his solution?

**Comment by petebacondarwin** [comment]
Actually, looking again at this, I don't think it is the fault of the `h3` element, instead it is related to the anchor that appears when you hover. This is doing some sneaky position, which affects where the h3 text begins.

**Comment by haoRchen** [comment]
![bug issue](https://user-images.githubusercontent.com/19397242/36633226-9948b150-195f-11e8-8543-8e1c5e6b9ad7.gif)

After removing the `l-sub-section` class from the surrounding div, I noticed that the formatting is fine. I think we should modify the `l-sub-section` css class to better handle h3 elements. Does anyone have any suggestions?
