### ISSUE TITLE
Form validation message templating

### ISSUE THREAD

**Issue by plalx** [angular/angular#2240]
I've looked at the new proposed forms specification and I believe there would be an alternative way of integrating error messages in custom form templates.

The following is way to heavy in my opinion:

`<div *if="form.hasError('city', 'required')">Required</div>`

It's great to have the flexibility to do the above, but in most cases I believe that something like the following could be appropriate:

`<control-errors control="city" show="1"></control-errors>`

However, that also means we need more control over the error messages generation. Simply adding details about the rules definitions as well as what went wrong for every broken rule would allow to build generic solutions that are quite flexible.

For instance, if we have a `maxLength=10` rule that failed because the string was `15`chars long, then the broken rule representation could be something like `{ type: 'maxLength', maxLength: 10, actualLength: 15 }`.

Then we could configure messages using a provider such as:

`$validationMessageProvider.registerMessageFor('maxLength', "too long by {actualLength - maxLength} character(s)")`

Obviously, we would have to think more about what would be an appropriate standardized broken rule schema, especially if we wish to support combined rules as well (assuming the rest of the framework supports them). For example, a `complexPassword` rule composed of a `specialChars` rule and a `minLength` rule.

**Comment by plalx** [comment]
@mhevery Was there any thoughts on how this will get implemented? Also, what would be the idiomatic approach for rules spanning more than a single control?

**Comment by plalx** [comment]
@mhevery Could you please answer the above questions? Thanks!

**Comment by mhevery** [comment]
Sorry this is a P3 for us, and as such we will not have a design for you until later.

**Comment by changLiuUNSW** [comment]
I have created angular 2 version of ng -message.
https://github.com/changLiuUNSW/ng-messages2
The syntax is quite similar to ng-message:
```
<form [formGroup]="formGroup">
    <label for="phoneNumber">Phone Number</label>
        <input type="text" id="phoneNumber" name="phoneNumber" formControlName="phoneNumber" required>
        <cl-ng-messages [control]="formGroup.get('phoneNumber')">
          <template clNgMessage="required">
             This is required
          </template>
          <template clNgMessage="pattern">
            the format of phone number is not correct
          </template>
        </cl-ng-messages>
</form>
```

**Comment by splincode** [comment]
@plalx  Is the issue relevant? Maybe close the task...

**Comment by AndrewKushnir** [comment]
Hi, thanks for creating this ticket and sharing the proposal. We do not plan to extend API surface to support this at the moment, so I'm going to close this ticket for now. We might get back to that when we decide to revisit error management in Forms package. Thank you.
