### ISSUE TITLE
Lazy loading & routing issue

### ISSUE THREAD

**Issue by upondeep** [angular/angular#22418]
This is main routing:
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule,Routes } from '@angular/router';
// import { AdminModule } from '../admin/admin.module';


import { PageNotFoundComponent } from '../shared/components/page-not-found/page-not-found.component';

const routes:Routes = [
  { path: 'pagenotfound', component: PageNotFoundComponent, pathMatch: 'full' },
  { path: 'admin', loadChildren: '../admin/admin.module#AdminModule' },
  { path: '', redirectTo:'/pagenotfound', pathMatch: 'full' },
  { path: '**', component: PageNotFoundComponent, pathMatch: 'full' },
];
@NgModule({
  imports: [
    CommonModule,
    // AdminModule,
    RouterModule.forRoot(routes),
  ],
  declarations: [],
  exports: [RouterModule]
})
export class RoutingModule { }
```
This is adminRoutingModule:
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Routes } from '@angular/router';
import { AdminHomeComponent } from '../admin/components/admin-home.component';

const adminRoutes:Routes = [
  { path:'', component: AdminHomeComponent},
];
@NgModule({
  imports: [
    CommonModule,
    RouterModule.forChild(adminRoutes),
  ],
  declarations: [],
  exports:[RouterModule]
})
export class AdminRoutingModule { }
```

This is AppModule:
```
@NgModule({
  declarations: [
    AppComponent,
    PageNotFoundComponent,
  ],
  imports: [
    BrowserModule,
    //AdminModule,
    RoutingModule,
    
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Now problem comes: When I serve the app, it directly show `AdminHomeComponent` not `PageNotFoundComponent`. Anyone knows why? looks like child routes is overwriting parent routes "" path. Thanks

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
