### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError on ng-untouched flag when disabling a form during submission with ENTER key

### ISSUE THREAD

**Issue by Vicente69** [angular/angular#22426]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
A form contains a single input. Right after loading, the focus is set in the input. On submit with the ENTER key, the form is disabled (thanks to the use of a `<fieldset>` container). The error `ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ng-untouched: true'. Current value: 'ng-untouched: false'.` shows in the Chrome console.

I suppose this behavior occurs:
- The ENTER key is pressed.
- The ng-untouched flag is checked by Angular under-the-hood and is `true`.
- The `onSubmit` callback is triggered.
- The form is disabled => the input lost focus => the ng-untouched flag is set to `false`.
- Angular complains about this undesired change.

## Expected behavior
No error.

## Minimal reproduction of the problem with instructions
- Extract the content of the ZIP archive enclosed in this issue in the `webapps` directory of a Tomcat servlet container (or I guess any simple HTTP server).
- Open the URL `http://localhost:8080/app/` under Chrome.
- After the page is loaded, set the focus in the input field.
- Press ENTER
- See the error in Chrome console.

## Environment
- Tomcat 9.0.5
- JDK 8 update 112
- Google Chrome 64.0.3282.186

<pre><code>
Angular version: 5.2.6

Browser:
- [x] Chrome (desktop) version 64.0.3282.186
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Platform:  Windows 10 Family

Others:
</code></pre>

May I have done something wrong?
Thanks in advance for your help!
[app.zip](https://github.com/angular/angular/files/1754244/app.zip)

BR,
Vincent

**Comment by mlc-mlapis** [comment]
@Vicente69 ... prepare a simple online demo reproduction using https://stackblitz.com (it is just a standard how to do it) ... don't suppose that anybody would download something to run it locally.

**Comment by Vicente69** [comment]
Hi @mlc-mlapis,

Unfortunately, I cannot reproduce exactly this issue with online tools like Plunkr or Stackblitz. With Stackblitz, I can get the error `ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.`. which is not exactly the one I mentioned above, and that is related to a `ng-untouched` property.

**Comment by mlc-mlapis** [comment]
@Vicente69 ... hmm, OK ... but still ... even `Previous value: 'true'. Current value: 'false'.` is a problem ... so let's try to solve it first ... and we will see.

**Comment by Vicente69** [comment]
Ok, here's a link to a Stackblitz app: https://stackblitz.com/edit/angular-9jjxcd

**Comment by mlc-mlapis** [comment]
@Vicente69 ... the only possible solution for this template based form case is to use `this.cdr.detectChanges();` immediately after `this.formDisabled = true;` because in other case there is the update of `ng-untouched` property of  `<input name="myName" ...>` in `THE SAME` CD cycle as disabling of all controls via binding `<fieldset [disabled]="formDisabled">`. So you have to run additional CD between them.

You can see it: https://stackblitz.com/edit/mlc-submit-form-disable-inputs?file=app/app.component.ts

**Comment by Vicente69** [comment]
Yes I understand, thank you very much for these clarifications on CD and your help @mlc-mlapis!
Before closing the issue, how shall I interpret the fact that the issue occurs only with Chrome?

**Comment by mlc-mlapis** [comment]
@Vicente69 ... yep, it is true ... the problem appears just only with Chrome and not with Edge, IE 11, FF or FF DEV. It is a bit mystery but it has to be related to the fact that different browsers call event handlers in different orders ... so it is about some internal implementation of events processing ... especially Chrome and `onblur` ... you can find other discussions about the problem even not related to Angular at all if you try to google the term like `Different behavior of blur event in different browsers`.

**Comment by Vicente69** [comment]
Great explanations, thank you!

**Comment by mrcleanandfresh** [comment]
I had an issue with this where I was programmatically focusing an input on `ngInit`. The suggestion to force a change detection after "the problem area" worked for me, and the error went away. Still, I don't understand these mysteries of the Angular Universe, but I still feel new to Angular too.
