### ISSUE TITLE
Router with Nested Outlets

### ISSUE THREAD

**Issue by jpsfs** [angular/angular#2242]
Hi!

I'm trying to create nested router outlets to achieve something similar to:
```
----------------------------------------------------------------------------|
|     App                                                                   |
|     -------------------------------------------------------|              |
|     |  Parent                                              |              |
|     |                                                      |              |
|     |       -----------------------------------|           |              |
|     |       | Child                            |           |              |
|     |       |                                  |           |              |
-----------------------------------------------------------------------------
```
Live example: http://plnkr.co/edit/qPhMWjw6V8tf2FucyKYb?p=preview

When the page loads I'm getting:

![image](https://cloud.githubusercontent.com/assets/1041209/7897073/67b476e6-06c6-11e5-92bb-59188d075660.png)

Router documentation is still in it's early stages and I've not managed to find any working example of this, so I cannot tell if there is a bug or it's just not well done on my end.

Can someone take a look?

Cheers!

**Comment by ibhi** [comment]
Hi,
 Same issue with me also. https://github.com/ibhi/angular-2-router-with-child

**Comment by ludohenin** [comment]
Same issue here, trying to achive almost the same as @ibhi.
[https://github.com/ludohenin/angular2-demo-app](https://github.com/ludohenin/angular2-demo-app)

**Comment by piraveen** [comment]
Does anyone have any examples for 'How to use child router in Angular2' ? I am following @ibhi method.

**Comment by btford** [comment]
See https://github.com/angular/angular/blob/master/modules/angular2/test/router/outlet_spec.ts#L100-L109

**Comment by PardeepJain** [comment]
@btford  your suggested link is expired not working.
