### ISSUE TITLE
Default select option in angular5 is not working even coded as in HTML syntax selected or selected="selected"

### ISSUE THREAD

**Issue by rawatfeb** [angular/angular#22436]
Please look into the issue.
 
As expected below code should default select "Select City" in drop down but it does not work.
 
<select class="form-control"  [(ngModel)]="selectedCity">
              <option value="0" selected="selected">Select City</option>
              <option *ngFor="let ct of cities" value={{ct.id}}>{{ct.name}}</option>
   </select>

Let me know for anything else.

Thanks,
Gaurav Rawat

**Comment by micronyks** [comment]
May I know what exactly are you passing to or setting to "selectedCity" variable?
You have to make sure that, according to your written code, "selectedCity" must have an id to match with available (id)values of cities.

eg. Demo :  https://plnkr.co/edit/FgwGmvXycIj96D48IoUD?p=preview

```
<select class="form-control" [(ngModel)]="selectedCity">
      <option *ngFor="let ct of cities" [value]="ct.id">{{ct.name}}   // changed [value]="ct.id"
</select>
```
```
export class App {
  name:string;
  constructor() {
    this.name = `Angular! v${VERSION.full}`
    this.cities=[{id:1,name:"xyz"}, {id:2,name:"abc"}, {id:3, name:"etc"}]
    
    //here you can apply your own logic to pre-select the country
    this.selectedCity=1;
  }
}
```

If it resolves your problem, **kindly close the question**.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
