### ISSUE TITLE
Unexpected directive value 'undefined' on the View of component

### ISSUE THREAD

**Issue by VirtualOverride** [angular/angular#2244]
I used the latest alpha version. when i i try to add angular.For in directives i encounter error
Unexpected directive value 'undefined' on the View of component.

I use this https://code.angularjs.org/2.0.0-alpha.25/angular2.sfx.dev.js

**Comment by mhevery** [comment]
This needs a full repro case. Please use http://plnkr.co/edit/tpl:BrUl7z1vvZBGWBfSGS8D to create it. Once you have it reopen the issue.

**Comment by VirtualOverride** [comment]
Hi @mhevery, i create a plnkr,
http://plnkr.co/edit/eJqmvaiDyypPOexr0IgF?p=info

**Comment by gdi2290** [comment]
@VirtualOverride the problem was that the docs on angular.io are still outdated. Here's your example working with alpha.25 http://plnkr.co/edit/ks0Sbv?p=preview refactored it a bit and made a helper annotations in Utils. I also added the original one as `_old_` if you prefer that

this closes #2248

**Comment by VirtualOverride** [comment]
yay... many thanks i saw it in the plnkr many thanks it helps a lot. you may close this issue.
