### ISSUE TITLE
UI Misalignment in sub section Title

### ISSUE THREAD

**Issue by mishra-ankit** [angular/angular#22441]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Title of section "Why not "highlight"?" is too much to the left.

![mis](https://user-images.githubusercontent.com/1507256/36642724-059c6b82-1a44-11e8-8d5b-67ae53ff5a79.PNG)

## Expected behavior

![fix](https://user-images.githubusercontent.com/1507256/36642725-07fc3344-1a44-11e8-80f0-a6580aa0f5da.PNG)
Note - Link to section seems unnecessary here. That could be removed.

## Minimal reproduction of the problem with instructions

Visit - https://angular.io/guide/attribute-directives#why-not-highlight

## What is the motivation / use case for changing the behavior?

Make the UI look broken and inconsistent.

## Environment

<pre><code>
Angular version: 5.2.x

Browser:
- [x ] Chrome (desktop) version XX
- [ x] Chrome (Android) version XX
- [ x] Chrome (iOS) version XX
- [ x] Firefox version XX
- [ x] Safari (desktop) version XX
- [ x] Safari (iOS) version XX
- [ x] IE version XX
- [ x] Edge version XX

**Comment by Doehl** [comment]
Dublicate of #22407
