### ISSUE TITLE
Error with new Webpack 4.0.0

### ISSUE THREAD

**Issue by mhosman** [angular/angular#22442]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Today has been released Webpack 4.0.0.
If I try to run Angular with this new Webpack version I get: 

Cannot read property 'thisCompilation' of undefined
at NodeTemplatePlugin.apply (.........\node_modules\webpack\lib\node\NodeTemplatePlugin.js:19:18)

If I go back to 3.11.0 works OK.

## Environment
<pre><code>
Angular version: 5.2.6

 
For Tooling issues:
- Node version: 6.11.3  
- Platform: Windows

**Comment by jotatoledo** [comment]
Please fill the issue template.

**Comment by splincode** [comment]
Problem for old dependencies, you need remove package-lock.json

```
$ rm -rf node_modules
$ rm package-lock.json
$ npm i
```

**Comment by BBaysinger** [comment]
@splincode, this did not fix the problem for me. Reverting to Webpack 3.11.0.

**Comment by pyritewolf** [comment]
I've got the same issue. I removed node_modules and package-lock.json, and made sure to have the latest version of all angular related packages.

I've reverted to an older webpack version too, but it'd be nice for this to work since the new version is supposed to reduce build time considerably.

**Comment by alexeagle** [comment]
Could you file this issue at https://github.com/angular/angular-cli/issues please?

**Comment by r2c0der** [comment]
ditto! reverting to 3.11.0
