### ISSUE TITLE
Router Guard doesn't trigger when using navigateByUrl from Router class

### ISSUE THREAD

**Issue by AhnpGit** [angular/angular#22447]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When navigating using `RouterLink` directive, it works well with Router Guard. However, if navigating using `navigateByUrl` from `Router` class, Router Guard does not trigger.

## Expected behavior

When navigating using `navigateByUrl` from `Router` class, Router Guard should be triggered similar to using `RouterLink` directive

## Minimal reproduction of the problem with instructions
**STEP TO REPRODUCE**
Example app: https://angular-szgjlg.stackblitz.io
- Open example app with Chrome, open Chrome Developer Tool and switch to Console tab.
- Click on the link `Click me to go to test page` and check console log. There is a console log printed out
- Click on the link `Click me to go to home page` and check console log. There is no console log printed out

## What is the motivation / use case for changing the behavior?

Can use Router Guard regardless which way of routing, either using `RouterLink` directive or using navigateByUrl from `Router` class

## Environment

<pre><code>
Angular version: 5.2.6

Browser:
- [x] Chrome (desktop) version 64.0.3282.167
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4
- Platform:  Mac

Others:
N.A.
</code></pre>

**Comment by mlc-mlapis** [comment]
@AhnpGit  ... but you have defined the guard only on `test` route and not on `home` route so you can't expect the guard to run also on `home` route.

```
{
    path: 'test',
    component: TestComponent,
    canActivate: [ TestGuard ],
}
```

**Comment by AhnpGit** [comment]
oops sorry I put the wrong code. I will close this for now and I will reopen when I get back my codes from my work project.
