### ISSUE TITLE
Deep copy still reflect new changes on parent 

### ISSUE THREAD

**Issue by Austyns** [angular/angular#22455]
## I'm submitting a bug report

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If a nested array object is copied, changes on the new new object still reflects on the old 

## Expected behavior

The expected behaviour is that the copy and the parent should be independent of each other as in angular1's angular.copy() method.

## Minimal reproduction of the problem with instructions

``` 
var arr = [{"name": "ab"},{ "name":"bc"},{'name': 'ca', options:[{"size":3}]}];
var newField = Object.assign({}, arr[2]);
newField.options.push({"size": 4});

console.log('New Array',newField); // output {name: "ca", options:[ {"size":3}, {"size":4 }  ]}
console.log('Old',arr[2])  // output {name: "ca", options:[ {"size":3}, {"size":4 }  ]}

```

## Environment

<pre><code>
@angular/cli: 1.4.5
node: 8.9.4
os: linux x64
@angular/animations: 4.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.5
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.3.4

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jotatoledo** [comment]
Why do you think that `Object.assign` makes a deep copy?

**Comment by mlc-mlapis** [comment]
@Austyns ... each nested object has its own reference.

**Comment by alexeagle** [comment]
Seems like this is not a problem with Angular, but with how you construct the copy?
Please re-open if that's not the case.
