### ISSUE TITLE
Valid code interpreted as dead code due to custom annotation

### ISSUE THREAD

**Issue by cosminadrianpopescu** [angular/angular#22452]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When compiling for prod (using aot and `UglifyJS`), dead code is removed without the possibility for the developer to fine tune the behavior of the `UglifyJS`. This poses problems in certain use cases. Example:

`app.component.js`:

```
import { OnInit, Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'app';
  aClass: any;

  ngOnInit(){
    console.log('checking out the component');
    this.aClass ? this.aClass.sMethod() : console.log('aClass is null');
  }
}

export function CustomAnnotation(obj) {
    console.log('hello', obj);
    AppComponent.prototype['aClass'] = obj;
    console.log('AppComponent is', AppComponent);
}
```

Then, in some file we could have:

```
@CustomAnnotation
export class AnnotatedClass{
    public static sMethod(){
        console.log('hello, I am a static method');
    }
}
```

As seen in the example, the `AnnotatedClass` class is going to be added to the properties of `AppComponent` using a custom annotation. I would expect when launching the application, to see in the console the message `hello, I am a static method`. This happens when compiled with aot for dev, but not when compiled for prod (which includes minification).

The problem is that the minifier is going to remove this class because is considered as dead code. Obviously, this is not dead code. 

The full project can be found here: http://popestii.eu/cloud/index.php/s/EliezZgizc7zHhA/download

Project compiled with `ng build --aot -sm false --environment prod --extract-css true --build-optimizer true --named-chunks false --output-hashing all --output-path dist-dev --base-href="/bug-report/dist-dev" --deploy-url="/bug-report/dist-dev"` can be tested here: 

http://popestii.eu/bug-report/dist-dev/index.html

Project compiled with `ng build --output-path dist-default --base-href="/bug-report/dist-default/" --deploy-path="/bug-report/dist-default/"` can be found here: 

http://popestii.eu/bug-report/dist-default/index.html

Project compiled with `ng build --prod --output-path dist-prod --base-href="/bug-report/dist-prod/" --deploy-url="/bug-report/dist-prod/"` can be found here:

http://popestii.eu/bug-report/dist-prod/index.html

## Expected behavior

I would expect to see the message `hello, I am a static method` in the developper tool's console (the static method should be executed by `ngOnInit` from the component). 

## Minimal reproduction of the problem with instructions

* download the project from here: http://popestii.eu/cloud/index.php/s/EliezZgizc7zHhA/download
* do `ng serve --prod`
* check the developer tools => The static method from the class `AnnotatedClass` is not called. 

If you try and serve it like this: `--aot -sm false --environment prod --extract-css true --build-optimizer true --named-chunks false --output-hashing all` (which basically should simulate the prod environment without minification), then everything is fine. 

## What is the motivation / use case for changing the behavior?

The developer should be allowed to fine tune the behavior of `UglifyJS` so in certain cases he could set the `dead_code` to false, so dead code would not be removed, if this poses problems. 

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: v8.9.4 
- Platform:  Windows 7

Others:

</code></pre>

**Comment by alexeagle** [comment]
@filipesilva I think this belongs on the angular/cli issue tracker? Also, do we handle Angular decorators differently from user-defined ones?

**Comment by alexeagle** [comment]
moving to https://github.com/angular/angular-cli/issues/9800
