### ISSUE TITLE
Component with transclusion instantiates transcluded component always

### ISSUE THREAD

**Issue by Gebov** [angular/angular#22457]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I have a component that has in its template transclusion with the tag ng-content and I have further decorated the container with the structural directive ngIf, the framework instantiates the component and does not render it.

## Expected behavior
I expect the component inside the <ng-content> not to be instantiated and rendered unless the directive is true

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gitter-kmwpjq
**Check the console.** The I have logged a message when the component's ngOnInit event is fired.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [X] Chrome (desktop) version 64
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dawidgarus** [comment]
That's by design. Here's explanation of this behavior: https://medium.com/@MichalCafe/angulars-content-projection-trap-and-why-you-should-consider-using-template-outlet-instead-cc3c4cad87c9
