### ISSUE TITLE
link target for [href] not applied when Directive exists

### ISSUE THREAD

**Issue by mcalmus** [angular/angular#22462]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If a Directive is created with a selector containing [href], things work fine for links created in-line in HTML. The directive is done and the link is followed. If the link is returned through code, though (using [href] in html), the anchor is no longer styled as a link and clicking the text only does the directive and doesn't follow the link.

## Expected behavior

Both directive run and link followed.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/5Mp2aJm5I9PMrEKq71gM?p=preview

## What is the motivation / use case for changing the behavior?

Want to run some code when links are clicked throughout app

## Environment

<pre><code>
Angular version: 5.2.6

Browser:
- [X] Chrome (desktop) version 64
- [X] Firefox version 58
- [X] IE version 11

**Comment by trotyl** [comment]
You'll need to re-bind it to property or attribute manually ([plunker](https://plnkr.co/edit/0IsOESdAZWDMVA0pKWEz?p=preview)).

The ability to intercept is by design, otherwise directives like `NgClass` won't be able to work:

```html
<element class="foo bar" [ngClass]="{baz: true}"></element>
```

I guess no one would expect `class="foo bar"` in the final DOM.

**Comment by alexeagle** [comment]
@mcalmus please re-open if that doesn't resolve the issue.
