### ISSUE TITLE
Parent component change detection strategy being inherited by descendants

### ISSUE THREAD

**Issue by admosity** [angular/angular#22461]
## I'm submitting a...
```
[x] Feature request
```
## Current behavior

Setting the change detection strategy of a parent component to `OnPush` "sets" the change detection strategy of all descendants in the same tree to `OnPush` or so it seems. I understand that change detection is skipped if a parent hasn't changed, but if a child performs a change worthy event (such as calling `setTimeout`) and doesn't itself have its change detection set to `OnPush`, shouldn't it still trigger change detection for itself?

## Expected behavior

Switching the change detection strategy in a parent component should not set the change detection strategy for all the components in the same tree.

## Minimal reproduction of the problem with instructions
Here's a set of examples on angular 4 and 5 with an example of a 2 layer deep parent:
https://stackblitz.com/edit/angular4-parent-child-change-detection?file=app%2Fapp.component.html
https://stackblitz.com/edit/angular5-parent-child-change-detection1?file=app/app.component.html

## What is the motivation / use case for changing the behavior?

We are migrating some codebases to a smart/presentational component architecture and it seems that it's not quite possible to do it piecemeal with container components affecting descendants.

We have a large distributed team that used `setTimeout` quite often to trigger change detection or perform operations on the next tick. API calls that used to work are not triggering changes either. It also seems to be a break in encapsulation that the parent component's change detection strategy affects a child's. This also affects projected content.

## Environment

<pre><code>
Angular version: ^4.0.0 and ^5.0.0

Browser:
- [ ] Chrome (desktop) version 64.0.3282.167

 
For Tooling issues:
- Node version: v8.7.0
- Platform:  Mac
</code></pre>

**Comment by mhevery** [comment]
This is by design.

**Comment by xsurge83** [comment]
@mhevery is there a workaround for this ? Should we trigger change detection at child level, even though the child doesn't have `OnPush` change detection strategy?

**Comment by mlc-mlapis** [comment]
@xsurge83 ... the CD goes through the tree of components always from top to bottom and if it is stopped at some point by `OnPush` logic it's on you to invoke the CD somehow behind the point.

**Comment by vivainio** [comment]
@xsurge83 trigger changeDetectorRef.detectChanges
