### ISSUE TITLE
Angular2 download excel file from Web API, file is corrupt

### ISSUE THREAD

**Issue by muhil85** [angular/angular#22464]
I was trying to download the file from controller api in Angular 4 component, file getting downloaded but it showing as corrupted. could you please any one one help on this issue,

My Controller Code:
----------------------------------
        [HttpGet("[action]")]
        public HttpResponseMessage DownloadFile()
        {
            using (MemoryStream ms = new MemoryStream())
            {
                string fileName = "Test.xlsx";

                using (FileStream file = new FileStream(@"E:\" + fileName, FileMode.Open, FileAccess.Read))
                {
                    byte[] bytes = new byte[file.Length];
                    file.Read(bytes, 0, (int)file.Length);
                    ms.Write(bytes, 0, (int)file.Length);
                    
                    HttpResponseMessage httpResponseMessage = new HttpResponseMessage();
                    httpResponseMessage.Content = new ByteArrayContent(ms.GetBuffer());
                    httpResponseMessage.Content.Headers.Add("x-filename", fileName);
                    httpResponseMessage.Content.Headers.ContentType = new MediaTypeHeaderValue("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
                    httpResponseMessage.Content.Headers.ContentDisposition = new ContentDispositionHeaderValue("attachment");
                    httpResponseMessage.Content.Headers.ContentDisposition.FileName = fileName;
                    httpResponseMessage.Content.Headers.ContentLength = file.Length;
                    httpResponseMessage.StatusCode = HttpStatusCode.OK;
                    return httpResponseMessage;
                }
            }

        }

Service Code:
------------------------------
    export(baseUrl: string, requestId: number): Observable<Object[]> {
        return Observable.create((observer:any) => {
            let xhr = new XMLHttpRequest();
            xhr.open('GET', baseUrl + 'api/RequestInformation/DownloadFile', true);
            xhr.setRequestHeader('Content-type', 'application/json');
            xhr.responseType = 'blob';

            xhr.onreadystatechange = function () {
                if (xhr.readyState === 4) {
                    if (xhr.status === 200) {

                        var contentType = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
                        var blob = new Blob([xhr.response], { type: contentType });
                        observer.next(blob);
                        observer.complete();
                    } else {
                        observer.error(xhr.response);
                    }
                }
            }
            xhr.send();

        });
    } 
Component Code:
-------------------------------
    DownloadRequest(requestId: number, fileName: string): void {

        this.requestService.export(this.appBaseUrl, requestId)
            .subscribe(downloadData => this.onSuccessDownloadRequest(downloadData, fileName), downloadData => this.onErrorDownloadRequest(downloadData));

    }

    onSuccessDownloadRequest(response: Object[], fileName: string): void {

        console.log(response);

        var link = document.createElement('a');
        link.href = window.URL.createObjectURL(response);
        link.download = "Report.xlsx";
        link.click();
}

i was spending almost a day on this issue, but there is no luck. please provice me the solution. different approach also good for me.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by muhil85** [comment]
Do u have any sample for downloading file in angular 4 using web api.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on StackOverflow using tag angular.

If you are wondering why we don't resolve support issues via the issue tracker, please check out this explanation.
