### ISSUE TITLE
Move the Compiler's ROUTES token to Core

### ISSUE THREAD

**Issue by hansl** [angular/angular#22463]
Right now libraries and toolings using the Angular compiler to list routes require a peer dependency to `@angular/router`. This is awkward if they don't deal with normal routes or have their own routing tokens.

Having the token in core would remove the dependency.

**Comment by jasonaden** [comment]
Can you give me an example of what you need?

**Comment by hansl** [comment]
Essentially UI-Router, Angular CLI and any routing static analysis tool or library need to depend directly (not a dev dependency) on `@angular/router`. This is highly inconvenient.

I would argue that this is `freq high` as it would affect every installation of UI Router or the CLI. Also, this has minimal dev time as it's simply moving the token to core, which should have been there in the first place (the route injection token is a feature of angular itself, not a feature of the router). Let's chat offline.

**Comment by JoostK** [comment]
The `ROUTES` token is specific to the `@angular/router`, as the `InjectionToken` is typed to resolve to `Route`, which is specific to `@angular/router`. Static analysis tooling should be able to identify `ROUTES` usages without a dependency on `@angular/routes` themselves. More importantly, lazy loading/code splitting  is nowadays possible using native dynamic imports so the preferred way that Misko mentioned is now actually available.
