### ISSUE TITLE
Angular2 with C#?

### ISSUE THREAD

**Issue by Thaina** [angular/angular#22470]
Is it possible to have angular engine work on C# in place of typescript?

I really love angularjs and always use it in my web project. I am also fond of C# much, I work with C# on unity and server. And so I wish I could write angular template syntax in html and write C# to run page instead of javascript

I was look at the Blazor project and see the compilation process is similar to angular2 that compile typescript. So what if we switch from typescript in angular into C#? Could we bridge the underlying angular engine to mono-wasm?

**Comment by admosity** [comment]
Same as #22398?

**Comment by Thaina** [comment]
@admosity Well I think in similar but opposite way that, we don't even need IDL if we just use angular template syntax to access method/property from webassembly that compiled from C#. And then just hook C# compiler in place of typescript compiler under the toolchain

This could be replace with any language aside from C#. Just that angular have some way to make custom binding on template syntax. I can think only with C# because in C# we have dynamic object that could imitate javascript object easily

**Comment by robwormald** [comment]
This isn't something we're going to do, though it would certainly be interesting for the community to look into. Closing as its not really actionable for us.
