### ISSUE TITLE
RouteReuseStrategy.retrieve() gets called twice in a row

### ISSUE THREAD

**Issue by StevenLiekens** [angular/angular#22474]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The `routeReuseStrategy.retrieve(curr.value)` is called twice in a row when creating the router state.

https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/router/src/create_router_state.ts#L32-L44

## Expected behavior

Call `retrieve` once and reuse the return value.

```ts
} else {
    // retrieve an activated route that is used to be displayed, but is not currently displayed
    const detachedHandle: DetachedRouteHandleInternal = routeReuseStrategy.retrieve(curr.value);
    if (detachedHandle) {
        const tree: TreeNode<ActivatedRoute> = detachedHandle.route;
        setFutureSnapshotsOfActivatedRoutes(curr, tree);
        return tree;

    } else {
        const value = createActivatedRoute(curr.value);
        const children = curr.children.map(c => createNode(routeReuseStrategy, c));
        return new TreeNode<ActivatedRoute>(value, children);
    }
}
```

## What is the motivation / use case for changing the behavior?

The current behavior confuses me as an implementer of the `RouteReuseStrategy` interface.

## Environment

<pre><code>
Angular version: 2.3+

</code></pre>

**Comment by jasonaden** [comment]
Thanks for the issue (and the PR). I will review in the near future so we can get this merged.
