### ISSUE TITLE
Re-open issue Unexpected directive value 'undefined' on the View of component

### ISSUE THREAD

**Issue by VirtualOverride** [angular/angular#2248]
Re-open issue Unexpected directive value 'undefined' on the View of component #2244
angular 2.0 with es5 code.

Hi @mhevery, i create a plnkr,
http://plnkr.co/edit/eJqmvaiDyypPOexr0IgF?p=info

**Comment by gdi2290** [comment]
please see https://github.com/angular/angular/issues/2244#issuecomment-107249552 with updated plnkr http://plnkr.co/edit/ks0Sbv?p=preview

**Comment by gdi2290** [comment]
@VirtualOverride can manually close it
