### ISSUE TITLE
defaultUrlMatcher() in router.js prints error if the router config do not have a path property

### ISSUE THREAD

**Issue by rdkmaster** [angular/angular#22487]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Config the routers with the following code:
```
@NgModule({
  declarations: [ SomeComponent ], 
  imports: [RouterModule.forChild([
      <any>{
          url: '/table/calendar', desc: 'calendar'
      },
      {
        path: 'abc', component: SomeComponent
      },

  ])]
})
export class SomeModule {
}
```

RouterModule prints error when encoutering the first mistake router config which does not have a path property, and the second valid router config is parsed because of the unhandled error.

## Expected behavior

The router module of angular should ignore the invalid router config:
```
{
    url: '/table/calendar', desc: 'calendar'
}
```
and continue to parse the other valid router config items

## Minimal reproduction of the problem with instructions

this online app explains everything

https://stackblitz.com/edit/angular-gitter-kfdyyj?file=app%2Fapp.module.ts

## What is the motivation / use case for changing the behavior?

In my case, I use the router config array for not just `RouterModule.forChild()`, so I need to add some invalid router config item in the array.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 60
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

<br>

If you want to pass arbitrary data, you should use the `data` property of a route config. But we can't remove the runtime validation to make it easier to use this API incorrectly.
