### ISSUE TITLE
OTS parsing error: invalid version tag

### ISSUE THREAD

**Issue by jferrer21** [angular/angular#22484]
Upgraded to Angular 5.26, and now I can't get get the glyphicons icons to download.  I also deleted the node_modules and package-lock.json and re-install.  Same issue.

Browser: Chrome Version 64.0.3282.186 (Official Build) (64-bit)

Thanks for any help.

Failed to decode downloaded font: http://localhost:4200/glyphicons-halflings-regular.f4769f9bdb7466be6508.eot?#iefix)%20format(%27embedded-opentype%27),url(../fonts/glyphicons-halflings-regular.woff2)%20format(%27woff2%27),url(../fonts/glyphicons-halflings-regular.woff)%20format(%27woff%27),url(../fonts/glyphicons-halflings-regular.ttf)%20format(%27truetype%27),url(../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular)%20format(%27svg%27
main:1 

OTS parsing error: invalid version tag

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
