### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by dariolongo** [angular/angular#22493]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Empty content.

`ERROR [DocViewer] Error preparing document 'tutorial/toh-pt3': Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
`
## Expected behavior

Show Master/Detail Components Chapter

## Minimal reproduction of the problem with instructions

Browse to [https://next.angular.io/tutorial/toh-pt3](https://next.angular.io/tutorial/toh-pt3)

**Comment by dariolongo** [comment]
PS: here [https://angular.io/tutorial/toh-pt3](https://angular.io/tutorial/toh-pt3) works

**Comment by petebacondarwin** [comment]
We have been making doc-gen infrastructure changes on master, which is deployed to `next.angular.io`. So this is a real bug. Thanks for the catch @dariolongo

**Comment by petebacondarwin** [comment]
Well this doesn't make sense to me...

<img width="1332" alt="screen shot 2018-02-28 at 22 26 42" src="https://user-images.githubusercontent.com/15655/36816712-8a075a5a-1cd6-11e8-938c-e2d801f132b2.png">

**Comment by petebacondarwin** [comment]
The `anchorLink` has just been selected from the `a` and now we are trying to remove it. How can it not be a child?

Unless... it is a descendant but not a child.

**Comment by petebacondarwin** [comment]
Ahah! This is because the `querySelector` is finding a `code-anchor` `a` tag before it finds the `header-link` `a` tag.
We need to change the selector to be more specific.

**Comment by petebacondarwin** [comment]
Fix is in the pipeline :-)
