### ISSUE TITLE
Unable to lazy load modules and their dependencies when using barrel(s)

### ISSUE THREAD

**Issue by Lydon** [angular/angular#22490]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

We're trying to lazy-load by cherry picking specific modules related to a particular route.

Example: Npm package: `ui.common` with `LoginModule`, `RegisterModule` and `AdminModule` in a flat esm5 index.js.

We want to lazy-load:
`/admin` -> only ```AdminModule``` and its dependencies should be loaded
`/login` -> only ```LoginModule``` and its dependencies should be loaded.
`/register` -> only ```RegisterModule``` and its dependencies should be loaded.

The JS chunks are being generated as in the attached image below. (Refer to [dist/](https://github.com/Lydon/lazy-loading/tree/master/dist))

![capture](https://user-images.githubusercontent.com/7816662/36783308-ea6a77de-1c7b-11e8-8791-c34bc52ab52b.PNG)

What we've also noticed is when loading the last registered route, in this case `register`, it loads the required JS chunk. However when navigating to `admin` or `login` it loads the incorrect chunk with the following error **Error: Cannot find 'LoginModule' in './common/index'** (please refer to the image below).

![capture4](https://user-images.githubusercontent.com/7816662/36783353-09b41ca8-1c7c-11e8-8656-f662f23493c0.PNG)

## Expected behavior

I expect that the necessary modules are lazy loaded for a specific route.

## Minimal reproduction of the problem with instructions

GitHub Repo: https://github.com/Lydon/lazy-loading
Navigate to `admin` or `login`, otherwise refer to the attached images.
## Environment

<pre><code>
Angular version: 5.2.X

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [x] All
 
For Tooling issues:
- Angular CLI 1.7.1
- Node version:  8.4.0
- Platform:  Windows

**Comment by alexeagle** [comment]
I think maybe this issue belongs on angular/angular-cli - what do you think @filipesilva  ?

**Comment by peterbakonyi05** [comment]
@alexeagle It happens using `@ngtools/webpack` with a custom Webpack configuration. So if it is CLI related, it is probably `@ngtools/webpack`

**Comment by alexeagle** [comment]
I am not sure where such issues belong, will just tag this for triage...

**Comment by alan-agius4** [comment]
The problem here seem to be the barrel file here.

If you change the routes in  https://github.com/Lydon/lazy-loading/blob/master/src/app/app-routing.module.ts#L4 to;

```ts
const routes: Routes = [
  {
    path: 'admin',
    loadChildren: './common/admin/admin.module#AdminModule'
  },
  {
    path: 'login',
    loadChildren: './common/login/login.module#LoginModule'
  },
  {
    path: 'register',
    loadChildren: './common/register/register.module#RegisterModule'
  }
];
```

**Comment by filipesilva** [comment]
Heya, sorry for taking a while to answer. Yes this sounds like a bug in ngtools/webpack, as reported in https://github.com/angular/angular-cli/issues/9862. I think we've actually fixed it in master for 6.x, but will comment there.

**Comment by mhevery** [comment]
Closing in favor of angular/angular-cli#9862
