### ISSUE TITLE
Angular guide not working. Getting error -   "REQUEST FOR DOCUMENT FAILED.

### ISSUE THREAD

**Issue by jjayaraman** [angular/angular#22491]
I am getting this error when tried to navigate around angular guide.
https://angular.io/guide/component-styles

"REQUEST FOR DOCUMENT FAILED.
We are unable to retrieve the "guide/component-styles" page at this time. Please check your connection and try again later."

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/21889

Try cleaning your browser's cache

**Comment by jjayaraman** [comment]
Thanks it works now :-)

**Comment by gkalpak** [comment]
Thx, @ericmartinezr! Closing as it works now.
(Not worth investigating further, since we are soon switching to a new ServiceWorker implementation - see #19795)
