### ISSUE TITLE
Testing example on https://angular.io/guide/testing does not work without manual corrections

### ISSUE THREAD

**Issue by op-jusi** [angular/angular#22497]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The testing example https://angular.io/generated/zips/testing/specs.testing.zip does not work locally when you use the guide https://angular.io/guide/testing.
When you issue 
`ng-test`
you get several errors.
`Can't resolve '...\src\test.ts`
`Cannot find module 'jasmine-marbles'`
And the warning that the local angular cli is older than the global one.

## Expected behavior

`ng-test` works in the example above immediately without warnings. Please provide _src\test.ts_ and put jasmine-marbles and the latest angular-cli to _package.json_ in the example package mentioned above.

## Minimal reproduction of the problem with instructions

$ ng test
## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by arielkuzminski** [comment]
Same problem here on Ubuntu machine, when using Angular CLI version (1.7.3).

**Comment by MarvinToll** [comment]
PS C:\project\ng6\tester> ng -v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.1
Node: 9.11.1
OS: win32 x64
Angular: 6.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.1
@angular-devkit/build-angular     0.6.1
@angular-devkit/build-optimizer   0.6.1
@angular-devkit/core              0.6.1
@angular-devkit/schematics        0.6.1
@angular/platform-server          <error>
@angular/upgrade                  <error>
@ngtools/webpack                  6.0.1
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

------ RESULT

PS C:\project\ng6\tester> ng test
 10% building modules 1/1 modules 0 active(node:356) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
11 05 2018 21:30:29.892:WARN [karma]: No captured browser, open http://localhost:9876/
11 05 2018 21:30:29.899:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
11 05 2018 21:30:29.899:INFO [launcher]: Launching browser Chrome with unlimited concurrency
11 05 2018 21:30:29.904:INFO [launcher]: Starting browser Chrome             × ｢wdm｣: Hash: 2de58b98a0d04967086dVersion: webpack 4.6.0
Time: 2832ms
Built at: 2018-05-11 21:30:30
       Asset      Size     Chunks  Chunk Names
     main.js  6.21 KiB       main  main
polyfills.js  6.52 KiB  polyfills  polyfills
Entrypoint main = main.js
Entrypoint polyfills = polyfills.js
[./src/polyfills.ts] 0 bytes {polyfills} [built]
[0] multi ./src/polyfills.ts 28 bytes {polyfills} [built]
[./src/test.ts] 0 bytes {main} [built]

ERROR in error TS2688: Cannot find type definition file for 'node'.
src/app/twain/twain.component.marbles.spec.ts(3,40): error TS2307: Cannot find module 'jasmine-marbles'.

**Comment by brandonroberts** [comment]
This issue has been resolved. If this is still relevant, please open a new issue.
