### ISSUE TITLE
Unable to get response objects

### ISSUE THREAD

**Issue by vikram06** [angular/angular#22507]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see 
</code></pre>

## Current behavior
I have response data, but it has encoded by BASE64. When try to call that value i can't get that value.

CODE:
```
return next.handle(req).map((event: HttpEvent<any>) => {
        alert("main"+JSON.stringify(event));
        if (event instanceof HttpResponse) {
          alert("if");    
        } 
        return event;
      });
```
Even i can't to get `main ` alert also

## Expected behavior

 What are objects Angular will be to return as object. 

## Environment

<pre><code>
Angular version: 5.2.5

Browser:
- [X ] Chrome (desktop) version 64.0.3282.186
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.3.0
- Platform:  Windows 7

</code></pre>

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
