### ISSUE TITLE
aio + docs/api: render @param descriptions in functions, interfaces, enums

### ISSUE THREAD

**Issue by jbogarthyde** [angular/angular#22501]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Captures the params and types in a table, but ignores the description in the @param tag

## Expected behavior

Capture param description in param table

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jbogarthyde** [comment]
Also for Type/TypeAlias

**Comment by petebacondarwin** [comment]
The `@param` tag works on interface methods.

**Comment by petebacondarwin** [comment]
`enum`s do not have parameters.

**Comment by petebacondarwin** [comment]
I'm working on rendering params for exported functions

**Comment by petebacondarwin** [comment]
I don't see how exported Type aliases can have params either.
