### ISSUE TITLE
aio + docs/api: consider the layout of method description etc

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#22500]
Continuing the discussion from https://github.com/angular/angular/issues/22133#issuecomment-369353668.

**Comment by jbogarthyde** [comment]
OK, looking at George's example (in 22133), I can live with a one-liner after the signature - especially since the parameter table has a "Parameters" heading.  
Let's just try to make sure that we keep it to one line.

**Comment by petebacondarwin** [comment]
I'll implement that then.
