### ISSUE TITLE
i cant bind data when i want edit product in my project in select box(multi select)

### ISSUE THREAD

**Issue by Moji0098** [angular/angular#22514]
ERROR Error: Uncaught (in promise): Error: Binding object with bindValue is not allowed.
Error: Binding object with bindValue is not allowed.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
