### ISSUE TITLE
Saml authentication with angular2

### ISSUE THREAD

**Issue by danishwebindia** [angular/angular#22512]
can we achieve SAML authentication IPD session maintaining part with angular 2/4. In my project i have to achieve SAML authentication from client side. But I can not get anything throw angular.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
