### ISSUE TITLE
HttpClient pushes undefined down the observable stream on error

### ISSUE THREAD

**Issue by abdullahsari** [angular/angular#22516]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[] Feature request
[] Documentation issue or request
[] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

An error instance does not exist when the backend responds with an error (can be a general issue, I only experienced it with the post and put method so far)
<pre><code>
TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at subscribeToResult (subscribeToResult.js:74)
    at CatchSubscriber.error (catchError.js:112)
    at XMLHttpRequest.onLoad (http.js:2283)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4740)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at ZoneTask.invokeTask [as invoke] (zone.js:496)
    at invokeTask (zone.js:1517)
    at XMLHttpRequest.globalZoneAwareCallback (zone.js:1543)
</code></pre>

## Expected behavior

HttpClient should give the error instance instead of undefined

## Minimal reproduction of the problem with instructions

- Call a backend API with HttpClient.post/HttpClient.put and make sure the call will result in an error
- Use either the catchError operator or catch the error in the observer
- Try logging the error instance to the console
- You will probably get a similar stracktrace from above

## What is the motivation / use case for changing the behavior?

Well, it's quite obvious no need to mention anything.
## Environment

<pre><code>
Angular version: 5.2.7

Browser:
- [X] Chrome (desktop) version 64.0.3282.186 (Official build) (64-bits) (cohort: Stable)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.1  
- Platform: Windows 

Others:
RxJS version 5.5.6

</code></pre>

**Comment by abdullahsari** [comment]
Was a problem related to HTTP_INTERCEPTOR.

**Comment by steeefyyy** [comment]
hello, how do you fix it ? got the same, probably my http_interceptor as well :/

**Comment by juristr** [comment]
@mburger81 

> Our question is how can we not THROW an error but also not throw a SUCCESS for http calls if we intercept for example a 401 or 403 in interceptor?

You should return an empty observable s.t. it completes. Something like

```
import { empty } from 'rxjs/observable/empty';
...
catchError(errorResponse => {
  if (errorResponse instanceof HttpErrorResponse) {
    if (errorResponse.status === ...) {
      // do your logic handling
      return empty();
    }
  }

  return _throw(errorResponse);
})
```
