### ISSUE TITLE
DOCS-i18n: Select among alternative text translations

### ISSUE THREAD

**Issue by narthur157** [angular/angular#22522]
## I'm submitting a...
[x ] Documentation issue or request
</code></pre>

## Current behavior
The text in the docs does not match the example code given

## Expected behavior
They should match

## Minimal reproduction of the problem with instructions
![image](https://user-images.githubusercontent.com/2042752/36845439-0b237b70-1d57-11e8-80a9-de100226f7e7.png)
The following format message in the component template binds to the component's gender property, which outputs one of the following string values: "m", "f" or "o". The message maps those values to the appropriate translations:

Referring to the example:
<pre><code><span i18n>The author is {gender, select, male {male} female {female} other {other}}</span></pre></code>

## What is the motivation / use case for changing the behavior?
Unless I am quite confused, it seems like the component should be said to be outputting "male", "female" or "other". If I am confused, then perhaps the docs should be clearer here..

Suggested new docs text:
The following format message in the component template binds to the component's gender property, which outputs one of the following string values: "male", "female" or "other". The message maps those values to the appropriate translations:

**Comment by rockument69** [comment]
This issue will be fixed by PR [36924](https://github.com/angular/angular/pull/36924).

**Comment by rockument69** [comment]
PR [36924](https://github.com/angular/angular/pull/36924) (docs: Refactor-i18n-DOCS-758) closes this issue.
