### ISSUE TITLE
radio not checked while it should be

### ISSUE THREAD

**Issue by ddwolf** [angular/angular#22525]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

* HERE IS THE CODE
    <input (click)="chooseEnv(0)" [(ngModel)]="task.env" type="radio" name="taskType"
           value="0" id="envDebug" checked>{{task.env}}

the task.env is 0 and it's displayed on the page CORRECTLY.

CHROME console showed this error message, which I dont' know its effect:

WebSocket connection to 'ws://localhost:4200/sockjs-node/557/ogcxfg3k/websocket' failed: Error during WebSocket handshake: Unexpected response code: 500

## Expected behavior

I expect that the radio input should be checked, but it's not, what may be the reason?

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [x] Chrome (desktop) 
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by alexeagle** [comment]
Sorry, that's not a sufficient reproduction for us to be able to observe the problem, can you please create a stackblitz that demonstrates the bug?

**Comment by ddwolf** [comment]
@alexeagle Thks for you reply, here is my demo:)
https://stackblitz.com/edit/angular-98tzhd

**Comment by alexeagle** [comment]
The radio button does appear checked for me when I click it, Chrome 64.0.3282.167 on Linux

**Comment by ddwolf** [comment]
@alexeagle yeah，but the click should not be necessory，the radio should be checked automatically，b/c the ngmodel has the value equal to the radio‘s value

**Comment by admosity** [comment]
https://stackblitz.com/edit/angular-2mb3sd?file=app%2Fapp.component.ts

ngModel and radio work on strict equality. Note how I changed `0` to `'0'` because the value is a string. Might be a separate conversation if there are coercion rules not being followed.

**Comment by ddwolf** [comment]
You are amazing, Thks so much,  yes, it worked in the stackblitz, I 'll test in my work place as soon as possible

**Comment by ddwolf** [comment]
YEAH GREAT, After I have modified my variable type to string, the problem fixed:)

BUT I am still thinking, can I give a number value to the radio input, which I tried, but failed...

**Comment by trotyl** [comment]
@ddwolf The `value` property will always be string, that's defined by HTML/DOM, not Angular. You can use `ngValue` for non-string types.
