### ISSUE TITLE
ng serve --prod issue [Uncaught (in promise): undefined]

### ISSUE THREAD

**Issue by genyklemberg** [angular/angular#22520]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I try `ng serve --prod` you can see in console 5 times triggering such an error:
```
Error: Uncaught (in promise): undefined
    at x (polyfills.724bd30c299df28c4429.bundle.js:1)
    at r.reject (polyfills.724bd30c299df28c4429.bundle.js:1)
    at widgets.js:8
    at Array.forEach (<anonymous>)
    at n (widgets.js:8)
    at e.invoke (polyfills.724bd30c299df28c4429.bundle.js:1)
    at t.run (polyfills.724bd30c299df28c4429.bundle.js:1)
    at polyfills.724bd30c299df28c4429.bundle.js:1
    at e.invokeTask (polyfills.724bd30c299df28c4429.bundle.js:1)
    at t.runTask (polyfills.724bd30c299df28c4429.bundle.js:1)
r.onUnhandledError @ polyfills.724bd30c299df28c4429.bundle.js:1
```

## Expected behavior
twitter timeline should be rendered as it does with regular `ng serve`

## Minimal reproduction of the problem with instructions
Can be found here (as you see it is working) https://stackblitz.com/edit/angular-d3nkls

## Environment
```
"@angular/animations": "^5.0.0",
    "@angular/cdk": "^5.0.0-rc0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "^5.0.0-rc0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/platform-server": "^5.0.0",
    "@angular/router": "^5.0.0",
```

Browser:
- [x] Chrome (desktop)
 
For Tooling issues:
- Node version: 8.9.1
- Platform:  Windows

**Comment by alexeagle** [comment]
A stackblitz that's working doesn't help us repro the problem.
Also I think this issue is for angular CLI? please re-open at github.com/angular/angular-cli/issues if needed
