### ISSUE TITLE
Elements doesn't work when using webpack to bundle shims (custom-elements-es5-adapter.js)

### ISSUE THREAD

**Issue by liquidboy** [angular/angular#22531]
I was playing around with the very very early beta bits of @angular/elements  in @andrewseguin    branch  https://github.com/andrewseguin/angular/tree/aio-elements-slimmed-ng-element

Just like to share that I finally got an element built and working BUT I spent a crazy amount of time troubleshooting 1 particular bug, which was nothing to do with the angular bits BUT may bite others..

The issue was with using the polyfill from webcomponentsjs, "custom-elements-es5-adapter.js"

I tried "bundling" the polyfill "custom-elements-es5-adapter.js" using webpack, and it wasn't obvious that webcomponentjs recommends to use it via <script /> tag and NOT bundling..  https://github.com/webcomponents/webcomponentsjs/issues/891

The error I was getting when I was trying to use the webpack bundled version was  -

`ng-element-constructor.js:29 Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at NgElementImpl.NgElement [as constructor] (ng-element-constructor.js:29)
    at new NgElementImpl (ng-element-constructor.js:54)
    at new AppModule (app.module.ts:91)
    at _createClass (core.js:11171)
    at _createProviderInstance$1 (core.js:11145)
    at initNgModule (core.js:11061)
    at new NgModuleRef_ (core.js:12353)
    at createNgModuleRef (core.js:12342)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:14690)
    at NgModuleFactory_.create (core.js:15828)`

So make sure to NOT USE WEBPACK for your webcomponentjs polyfills …  

Hopefully this tip saves someone some time with wasted troubleshooting

**Comment by andrewseguin** [comment]
Thanks for the heads up. I pushed out a different strategy using @webcomponents/custom-element instead of @webcomponents/webcomponentsjs because of this reason. Seemed way too complicated to set up otherwise, and it also included too many polyfills.

Can you try this out instead? https://github.com/angular/angular/pull/22413/commits/2ec69519548c37b8f208695d1d602646b0c59a14

```ts
// polyfills.ts
...

/** Add support for window.customElements */
import '@webcomponents/custom-elements/custom-elements.min';

/** Required for custom elements for apps building to es5. */
import '@webcomponents/custom-elements/src/native-shim';

...
```

**Comment by liquidboy** [comment]
thanks @andrewseguin    that approach is much better. using a polyfills.ts which imports the custom-elements bits and then webpacking that ts..    

Works great and feel much better than hard <script /> referencing webcomponentsjs polyfill files …
