### ISSUE TITLE
Key events: e2e test failing on my (AZERTY) computer

### ISSUE THREAD

**Issue by vicb** [angular/angular#2253]
`./scripts/ci/build_and_test.sh js` generates the following error

```
Failures:
1) key_events should display correct key names
  Message:
    Expected 'q' to be 'a'.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/home/victor/dart/angular/dist/js/cjs/examples/e2e_test/key_events/key_events_spec.js:21:33)

```

**Comment by vicb** [comment]
@divdavem can you take a look ?

**Comment by divdavem** [comment]
@vicb Is it the first time you are running this test on your AZERTY computer, or did it work before?
Do you see the same issue when trying to execute the test manually (without protractor) by typing "a" on your keyboard in the sample page?

**Comment by vicb** [comment]
It has been a long since I last run the e2e tests (I usually only execute the one which is broken) so I can not really tell about about that first part of the question.

If I `gulp serve.js.prod`& `http://localhost:8001/examples/src/key_events/` everything is fine, it might relates to protractor then /cc @juliemr

**Comment by juliemr** [comment]
Chromedriver issue: https://code.google.com/p/chromedriver/issues/detail?id=553

**Comment by vicb** [comment]
@juliemr: thanks for the link, I'll update the test to avoid this & add a link to the issue.
