### ISSUE TITLE
Different behaviour between `--prod` and unoptimized builds

### ISSUE THREAD

**Issue by cpenner-va** [angular/angular#22530]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The two following route configs result in different behaviours when --prod is enabled. Both work as expected when aot compiling is turned off. The differing behaviour is that the resolvers do not run when using `routesModified`.

```typescript
const routesLiteral: Routes = [
  { path: `user/:userID/settings`, component: UserSettingsComponent, resolve: {userID: SelectedUserResolver} },
  // ...
];

@NgModule({
  imports: [RouterModule.forRoot(routesLiteral)],
  providers: [
    SelectedUserResolver,
  ],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```

Using Map to modify routes:
```typescript
let routesModified: Routes = [
  { path: `user/:userID/settings`, component: UserSettingsComponent},
];

routesModified = routesModified.map((routeConfig: Route) => {
  return {
    ...routeConfig,
    resolve: {
      userID: SelectedUserResolver,
    }
  };
});

@NgModule({
  imports: [RouterModule.forRoot(routesModified)],
  providers: [
    SelectedUserResolver,
  ],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```

## Expected behavior
I expect behavior to be consistent between normal builds and `--prod` builds. If I am doing something that the aot compiler cannot understand I expect an error to occur rather than altered behavior.

## Minimal reproduction of the problem with instructions
Use the provided router configs with a dummy app implementation and note that the resolvers do not run with `--prod`

## What is the motivation / use case for changing the behavior?
It causes my production build to fail when my testing builds work.

## Environment

<pre><code>
Angular version: 5.2.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by robwormald** [comment]
Please open build related issues in the Angular CLI repo - https://github.com/angular/angular-cli - thanks!
