### ISSUE TITLE
Injectable Service Worker context + cache services

### ISSUE THREAD

**Issue by duckwaffle** [angular/angular#22543]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I'm not sure if this is a feature request, or a documentation request (because the docs are pretty crap if you want to do anything remotely advanced), but it seems that there is no way to interact with the Service Worker for any purpose other than to listen for SW updates (kind of useless if your app runs on dynamic resources and you want to implement some kind of pre-fetch/update cycle) and receive push notifications (entirely useless because there is no way to interact with push notifications).

Without the a service worker context/scope its very difficult to hook into the [onfetch event](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/onfetch), and while it is possible to interact with service worker caches using the [global caches](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage) object, its impossible (or just not documented) to know which cache does what and why, and how to use them to your advantage.

## Expected behavior

There are a number of injectables in the service worker component that are not marked for export. Exporting them would at least give people who are willing to dig through the source some ability to do things such as pre-fetching assets and all sorts of other good stuff that can be found [here](https://serviceworke.rs).

## Environment

<pre><code>
Angular version: 5.2.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by alxhub** [comment]
Correct - for know, this is a design decision for `@angular/service-worker`. In the future we may expand support for interacting with the SW, but for now it is designed as a caching solution.

**Comment by gkalpak** [comment]
Based on the explanation in https://github.com/angular/angular/issues/22543#issuecomment-384103692 and the low demand for this feature, I am going to close this for now. Note that adding support for interacting with the caches (in a limited way) is being discussed/tracked in #22543 (initially potentially only for clearing specific caches).
