### ISSUE TITLE
ViewChild decorator stores element reference in local variable instead of instance member.

### ISSUE THREAD

**Issue by brianz3** [angular/angular#22545]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
ViewChild finds the element using its 'id', but it stores the reference in a local variable instead of an instance member. For example, in `tab2` instead of in `this.tab2`. See the example below for details.

## Expected behavior
The element reference that ViewChild finds should be stored as an instance member.

## Minimal reproduction of the problem with instructions
* Step 1 - Create new project and new component. Do not add any packages.
```
ng new test-view-child
ng g component test-vc
```
* Step 2 - Add reference to test component at the end of app.component.html.
```
<div>
  <p>here is the test</p>
  <app-test-vc></app-test-vc>
</div>
```
* Step 3 - Run server (before changing test-vc.component.ts to delay compiler error) and open in Chrome browser.
```
ng serve --port 4201
```
* Step 4 - Replace test-vc.component.ts with this:
```
import { Component, OnInit, AfterViewInit, ViewChild, ElementRef } from '@angular/core';

@Component({
  selector: 'app-test-vc',
//  templateUrl: './test-vc.component.html',
  template: '<div id="tab2"></div>',
  styleUrls: ['./test-vc.component.css']
})
export class TestVcComponent implements OnInit, AfterViewInit {
  @ViewChild('tab2') tab2: ElementRef;

  tab2a: ElementRef;

  constructor() { }

  ngOnInit() {
  }

  ngAfterViewInit() {
//    // very strange: 'this.tab2' is undefined, but 'tab2' contains the element
    this.tab2a = this.tab2;
    console.log('avi 1 tab2', tab2)  // compiler says: Cannot find name 'tab2'. Did you mean the instance member 'this.tab2'?
    console.log('avi 2 this.tab2', this.tab2)
    console.log('avi 3 this.tab2a', this.tab2a)
  }
}
```
* Step 5 - Examine results in Chrome console.
### Observed behavior
Chrome console shows that ViewChild did find the element, but it didn't store the reference in a legally accessible location.
```
avi 1 tab2 <div _ngcontent-c1 id=​"tab2">​</div>​
avi 2 this.tab2 undefined
avi 3 this.tab2a undefined
```
The development server shows this error message:
`ERROR in src/app/test-vc/test-vc.component.ts(22,31): error TS2663: Cannot find name 'tab2'. Did you mean the instance member 'this.tab2'?`

Also the build prod command will fail because of the same message.

## What is the motivation / use case for changing the behavior?
I am trying to use the ViewChild decorator to find an element reference so that I can send it a click. Unfortunately, while ViewChild does find the element using its 'id', it stores the reference in a local variable instead of an instance member. (Which I only discovered by accident.)

## Environment

<pre>$ ng --version
Angular CLI: 1.7.2
Node: 6.11.3
OS: darwin x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.2
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
</pre>
<code>
Angular version: 5.2.7

Browser:
- [X] Chrome (desktop) version 64.0.3282.186
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.3
- Platform:  Mac
</code>

Others:
I've seen several examples showing that this has worked for other people. I'm at a loss why it isn't working here. Perhaps I haven't followed the examples correctly?

**Comment by brianz3** [comment]
Thank you for filling in those two important gaps in my knowledge. That makes all of the difference. I appreciate it.

**Comment by pkozlowski-opensource** [comment]
Closing as a support request. Thnx for helping out @alexzuza
