### ISSUE TITLE
[aio] Routes and Navigation guide still use observable patched operators

### ISSUE THREAD

**Issue by michaeljota** [angular/angular#22542]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In the section of [Activated route in action](https://angular.io/guide/router#activated-route-in-action) of the Routes and Navigation guide, the code samples still use patched operators for observables

## Expected behavior
It should use piped operators.

## What is the motivation / use case for changing the behavior?
Patched operators are deprecated, and piped should be prefer. Also in ToH tutorial, piped operators are being used.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by brandonroberts** [comment]
The example has been updated to use pipeable operators
