### ISSUE TITLE
Optional route parameter cannot be retrieved with paramMap.switchMap

### ISSUE THREAD

**Issue by dm-CaT** [angular/angular#22549]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Optional parameter cannot be retrieved with paramMap.switchMap. It is not working even in official example (see StR).

## Expected behavior

Optional parameter could be retrieved from route as described in documentation.

## Minimal reproduction of the problem with instructions

1. Open official [documentation](https://angular.io/guide/router#route-parameters-in-the-activatedroute-service)
2. Click 'live example' [link](https://angular.io/generated/live-examples/router/stackblitz.html)
3. Select any hero from the list
4. Click 'Back' button
Expected: the hero visited is highlighted (has class selected).
Current: no hero highlighted.

## What is the motivation / use case for changing the behavior?

There is no possibility to use optional parameters in the way the official docs describe.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version 63.0.3239.132 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Windows 

Others:

</code></pre>

**Comment by dm-CaT** [comment]
I found why the example from official documentation does not work.
It's because after navigation back to the list of heroes with parameters redirect occurs and all query parameters are lost.
In hero details component navigation looks like that:
```
  gotoHeroes(hero: Hero) {
    let heroId = hero ? hero.id : null;
    // Pass along the hero id if available
    // so that the HeroList component can select that hero.
    // Include a junk 'foo' property for fun.
    this.router.navigate(['/heroes', { id: heroId, foo: 'foo' }]);
  }
```
then according to routes defined redirect occurs
```
const heroesRoutes: Routes = [
  { path: 'heroes', redirectTo: '/superheroes' }, // this redirect loose query parameters
  { path: 'hero/:id', redirectTo: '/superhero/:id' },
  { path: 'superheroes',  component: HeroListComponent },
  { path: 'superhero/:id', component: HeroDetailComponent }
];
```
I didn't find the way to preserve query parameters during redirect. Any suggestions?

**Comment by jasonaden** [comment]
I believe you want the `NavigationExtras` and `queryParamHandling` strategy:

https://angular.io/api/router/NavigationExtras#queryParamsHandling
