### ISSUE TITLE
Minor tweak to make docs match code

### ISSUE THREAD

**Issue by samdutton** [angular/angular#22550]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

https://angular.io/guide/quickstart

src/app/app.component.ts example:

> change the title property from _Welcome to app!!_

## Expected behavior

>  change the title property from _app_ ...'

(to match downloaded code)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
Thanks! It looks like this issue has been resolved. Current doc: 
Step 4: Edit your first Angular component 
Open the component file and change the title property from 'app' to 'My First Angular App!'

Thanks, again!
