### ISSUE TITLE
Building angular requires the code to be placed in a git repository

### ISSUE THREAD

**Issue by i3anaan** [angular/angular#22551]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
`./build.sh`
`fatal: Not a git repository (or any of the parent directories): .git`

## Expected behavior
A warning would be shown that says the current version cannot be determined and a placeholder (invalid) version would be used, but the build finishes.

## Minimal reproduction of the problem with instructions
- Use a fresh git clone from the angular repository
- `yarn install` (from https://github.com/angular/angular/blob/master/docs/DEVELOPER.md)
-  `rm -rf .git`
- `./build.sh`

## What is the motivation / use case for changing the behavior?
An application should not fail to build because the versioning software is removed/changed (ie. just the code should be sufficient)

## Environment

<pre><code>
Angular version: commit 0451fd93df954e9a6ecedb15997bfab9e74b2b22
</code></pre>

Environment (Dockerfile):
```
FROM node:8.9.4

RUN apt-get update && apt-get install -y rsync
```

Others:
Ran into this while trying to get angular to build in a docker container, but accidentally did not copy the .git folder (as it was used as a submodule)

**Comment by i3anaan** [comment]
I submitted a PR with a fix for this problem:

https://github.com/angular/angular/pull/22552

**Comment by jelbourn** [comment]
I believe this is obsolete since we've switched to bazel.
