### ISSUE TITLE
Live example for Dynamic Component Loader is showing Page Not Found in firefox

### ISSUE THREAD

**Issue by GowthamS05** [angular/angular#22554]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

in the documentation page for [Dynamic Component Loader](https://angular.io/guide/dynamic-component-loader)  there is a link for [live example](https://angular.io/generated/live-examples/dynamic-component-loader/eplnkr.html) the link is not working 
on click it says page not found
Firefox only ---works fine in chrome
## Expected behavior

the live example should load.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x] Firefox version 58 
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
Firefox blocks the redirection and I have to allow it, but other than that it works fine for me :confused:

**Comment by ericmartinezr** [comment]
Your link points to `https://angular.io/generated/live-examples/dynamic-component-loader/eplnkr.html` but I see the link in the doc points to `https://angular.io/generated/live-examples/dynamic-component-loader/stackblitz.html`, could it be a cache issue? (Works fine for me in both browsers)

**Comment by jenniferfell** [comment]
Thank you. This appears to have been resolved when we moved the examples from plnkr to stackblitz. The link for the live example now works correctly for me. If you're still experiencing problems, please let us know. Thanks.

**Comment by MarienBourguignon** [comment]
uBlock origin adds "display: none;" to the declaration block of ad-banner because the class attribute is listed in the EasyList filter list (https://easylist.to/easylist/easylist.txt). One simple way to solve the issue would be to rename ad-banner into something that isn't listed.
