### ISSUE TITLE
Two way binding doesn't work for programmitically changed input values

### ISSUE THREAD

**Issue by kyleThayerXpanxion** [angular/angular#22561]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If I change an input's value programmically, the model that is bound to said value does **not** update.

## Expected behavior

I expect two way binding to cover both user input changes and programmic changes to the input.

## Minimal reproduction of the problem with instructions
Simply use two way binding on an input, then change value programmically:
 <input (input)="onChange($event, 5, 2, true)" [(ngModel)]="funcType.hours">
onChange(event) {
event.currentTarget.value = "TEST!!!"
}

## What is the motivation / use case for changing the behavior?
Being able to dynmically validate and change/format user's data easily

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ x] Chrome (desktop) version 64.0
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by bcandullo** [comment]
`Being able to dynmically validate and change/format user's data easily`
Reactive forms has a much better api for this.

**Comment by kyleThayerXpanxion** [comment]
Reactive forms is great; however, it doesn't provide the granular validation + improved user experience that we are shooting for the project.

**Comment by maximedupre** [comment]
I think this is a bug, not a feature. Please see referenced ticket.

**Comment by alxhub** [comment]
Closing as I don't believe we will address this. This is just not how forms fundamentally understands the view - it monitors _events_ on the inputs, it doesn't perform comparisons against the view values. That is, `ngModelChange` only emits when a true user input action occurs, not when the DOM control's value is manipulated outside of the forms system.
