### ISSUE TITLE
Project keeps re-initializing, chrome tab keeps spinning

### ISSUE THREAD

**Issue by joshterrill** [angular/angular#22562]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
When I start my app up, it looks like angular keeps re-initializing over and over. I am just using `ng serve` and the loading spinner in the chrome window keeps spinning. When I look in the console, I see

`Angular is running in the development mode. Call enableProdMode() to enable the production mode.`

Show up, and then it just keeps repeating itself over and over every few seconds. 

## Expected behavior
This seems like it just started happening for some reason, no code in my app initialization has changed.

### Angular CLI Version
<pre><code>
joshterrill$ ng --version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.7.2
Node: 6.11.0
OS: darwin x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.7.2
@angular/flex-layout: 2.0.0-rc.1
@angular/http: 4.3.0
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0

</code></pre>

### Package JSON
<code><pre>

"dependencies": {
    "@angular/animations": "^5.2.5",
    "@angular/common": "^5.2.5",
    "@angular/compiler": "^5.2.5",
    "@angular/core": "^5.2.5",
    "@angular/flex-layout": "^2.0.0-rc.1",
    "@angular/forms": "^5.2.5",
    "@angular/http": "4.3.0",
    "@angular/platform-browser": "^5.2.5",
    "@angular/platform-browser-dynamic": "^5.2.5",
    "@angular/router": "^5.2.5",
    "@dharapvj/ngx-signalr": "^3.0.0",
    "@types/core-js": "^0.9.46",
    "@types/node": "9.4.0",
    "angular-2-dropdown-multiselect": "1.5.4",
    "angular-auth-oidc-client": "1.3.15",
    "angular-autofocus-fix": "0.1.0",
    "angular-calendar": "^0.23.6",
    "angular-star-rating": "3.0.8",
    "angular2-infinite-scroll": "^0.3.5",
    "angular2-moment": "1.6.0",
    "angulartics2": "4.6.3",
    "bootstrap": "4.0.0",
    "core-js": "2.5.1",
    "cws-angular2-image-gallery": "^1.2.7",
    "date-fns": "^1.29.0",
    "hammerjs": "2.0.8",
    "jquery": "3.2.1",
    "moment": "2.19.3",
    "mydatepicker": "2.6.1",
    "ng2-date-picker": "2.6.2",
    "ng2-file-upload": "1.2.1",
    "ng2-popover": "0.0.14",
    "ng2-search-filter": "0.4.1",
    "ng2-signalr": "2.1.0",
    "ng2-toastr": "4.1.2",
    "ngx-bootstrap": "2.0.2",
    "ngx-chips": "^1.6.4",
    "ngx-facebook": "2.4.0",
    "ngx-uploader": "4.2.2",
    "rxjs": "5.5.6",
    "signalr": "2.2.2",
    "videogular2": "^6.0.6",
    "web-animations-js": "2.3.1",
    "zone.js": "0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.7.0",
    "@angular/compiler-cli": "^5.2.5",
    "@angular/language-service": "^5.2.5",
    "@ngtools/webpack": "^1.10.0",
    "@types/jasmine": "2.5.45",
    "@types/node": "9.4.0",
    "angular2-perfect-scrollbar": "2.0.6",
    "codelyzer": "3.0.1",
    "jasmine-core": "2.6.4",
    "jasmine-spec-reporter": "4.1.1",
    "karma": "2.0.0",
    "karma-chrome-launcher": "^2.1.1",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "^1.4.1",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "ngx-perfect-scrollbar": "5.0.0-9",
    "protractor": "5.1.2",
    "ts-node": "^4.1.0",
    "tslint": "^5.9.1",
    "typescript": "~2.6.2"
  }

</code></pre>

Browser:
- [ x ] Chrome (desktop) version 64.0.3282.186 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.0
- Platform:  Mac

**Comment by alexeagle** [comment]
Sorry, there's nothing we can do to investigate with no steps to reproduce.
