### ISSUE TITLE
ChangeDetectorRef.markAsUntouched()

### ISSUE THREAD

**Issue by ghost** [angular/angular#22566]
## I'm submitting a...
<pre><code>[x] Feature request
</code></pre>

## Current behavior
Methods that don't change anything still trigger change detection. Currently the only way to fix this is to use OnPush or detach(), both of which require modifying the entire component subtree to support OnPush change detection.
E.g. A HostListener('scroll') will cause change detection on each scroll, which is expensive.

## Expected behavior
Methods should be able to call a method `changeDetector.markAsUntouched()` to indicate that the current method has not changed any state. Then, Angular can skip the onLeave change detection if only that method ran.

## Minimal reproduction of the problem with instructions
1. Create a class like
<pre><code>export class SomeComponent {
  aVeryLargeMutableObject = new VeryLargeMutableObject();

  @HostListener('window:scroll', [])
  onWindowScroll() {
    // Do nothing
  }
}</code></pre>

2. Now, scrolling is very slow because change detection occurs every time.

## What is the motivation / use case for changing the behavior?
Allow methods that don't change anything to run efficiently, without having to modify the whole component tree to use OnPush.

## Environment
Angular version: latest
Browser:
  All browsers

**Comment by Yerkon** [comment]
@sweiss-google,  [Code example](https://stackblitz.com/edit/angular-p4dv5k?file=app%2Fapp.component.ts)

**Comment by devoto13** [comment]
https://github.com/angular/angular/pull/21681 provides a way to make event listeners not trigger change detection. You also can use a custom `EventManager` to solve it for now. See complete code example in [this gist]( https://gist.github.com/devoto13/a1663506728212481cdb4f301002b1d4).

**Comment by admosity** [comment]
You can also disable parts of zone's patching globally if performance against these events are an issue:

```typescript
/**
 * By default, zone.js will patch all possible macroTask and DomEvents
 * user can disable parts of macroTask/DomEvents patch by setting following flags
 */

 (window as any).__Zone_disable_requestAnimationFrame = true; // disable patch requestAnimationFrame
 (window as any).__Zone_disable_on_property = true; // disable patch onProperty such as onclick
 (window as any).__zone_symbol__BLACK_LISTED_EVENTS = ['scroll', 'mousemove']; // disable patch specified eventNames
```

This is actually provided in newer versions of angular-cli:
https://github.com/angular/devkit/blob/1f1c2750a81a9b1397327cc2a3c3cb91d18c340c/packages/schematics/angular/application/files/__sourcedir__/polyfills.ts#L55-L62
