### ISSUE TITLE
Feature: add method to change inputs in ComponentRef

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#22567]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
To change inputs of component creates via ComponentFactory we need to access component instance directly, like that:
```typescript
componentRef.instance.myInput = 'new value';
```

## Expected behavior
There should exist a method on ComponentFactory that changes inputs, for example:
```typescript
componentRef.changeInputs({ myInput: 'new value' });
```

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?
Changing properties on component instance won't call ngOnChanges. You have to do it manually, and that's really annoying because You really can't assume that it's not necessary for component to work correctly.
Calling changeInputs should also call ngOnChanges on component instance. It's also might be a good idea to delay it until change detection is triggered or trigger change detection automatically when changeInputs is called, so ngOnChanges would be called only once before ngDoCheck. Again, some components may rely on ngOnChanges being followed by ngDoCheck.

**Comment by devoto13** [comment]
This a very cool idea. It should also allow to to test OnPush components without adding a wrapper component, so should at least partially resolve https://github.com/angular/angular/issues/12313.

**Comment by vzakharov-rxnt** [comment]
Is it still being considered? I think it would be a very useful feature.
