### ISSUE TITLE
[Router] Redirect chain does not work

### ISSUE THREAD

**Issue by JounQin** [angular/angular#22577]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

## Current behavior

When I set root Route redirectTo `console`, and `console` redirectTo `console/dashboard`, and visit root route, it only redirects to `console`, and refresh the page, it will redirect to `console/dashboard` correctly.

## Expected behavior

It should redirect from root route to `console/dashboard` directly.

## Minimal reproduction of the problem with instructions

https://github.com/JounQin/ng-rubick/blob/master/src/views/app.routing.module.ts#L18-L20
https://github.com/JounQin/ng-rubick/blob/master/src/views/console/console.routing.module.ts#L14-L16

## Environment

Angular version: 6.0.0-beta.6

Browser:
- [x] Chrome (desktop) version 64.0.3282.186
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by Toxicable** [comment]
That is intended, I don't have any docs to link on it sorry but there is a specific test to make sure there isn't more than one redirect

**Comment by JounQin** [comment]
@Toxicable But why? Or how to make it working *correctly*?

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

<hr>

I would take a look at this article, which covers some of the rules in the section "One Redirect at a Time".
