### ISSUE TITLE
[AOT] warning wrong type error message when using pug on webpack watch rebuilding

### ISSUE THREAD

**Issue by JounQin** [angular/angular#22578]
## I'm submitting a...

[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

## Current behavior

```
ERROR in src/views/console/console.component.pug(1,1): : Property 'breadCrumb' is private and only accessible within class 'ConsoleComponent'.
src/views/console/console.component.pug(1,1): : Property 'label' does not exist on type 'BreadCrumbService'.
src/views/console/console.component.pug(1,1): : Property 'breadCrumb' is private and only accessible within class 'ConsoleComponent'.
src/views/console/console.component.pug(1,1): : Property 'label' does not exist on type 'BreadCrumbService'.
```

## Expected behavior

No error message

## Minimal reproduction of the problem with instructions

Branch: `pug_issue`

https://github.com/JounQin/ng-rubick/blob/pug_issue/src/views/console/console.component.pug

run `yarn dev` first, there is no error message, but whenever you change anything to trigger webpack rebuild, there will be an error message on console.

If I use html template, there will not be an error message. And I've checked the pug file output content, it is correct, and if I copy it and set it to be `template` content, there will not be an error message neither.

## Environment

Angular version: 6.0.0-beta.6

Browser:
- [x] Chrome (desktop) version 64.0.3282.186
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.7.1  
- Platform:  Mac 

Others:

`Webpack`: 4.0.1
`@ngtools/webpack`: 6.0.0-beta.4

**Comment by Toxicable** [comment]
Sorry I don't think this is an issue with Angular

**Comment by JounQin** [comment]
@Toxicable Or maybe related to `@ngtools/webpack`

**Comment by alexeagle** [comment]
Please reopen if you think this is a bug in Angular.
