### ISSUE TITLE
[AOT] webpack DefinePlugin not working with @ngtools/webpack

### ISSUE THREAD

**Issue by JounQin** [angular/angular#22574]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

## Current behavior

When I define a global variable `HASH_MODE=true` via webpack.DefinePlugin and set it to `RouterModule useHash`, it not works,

## Expected behavior

When `HASH_MODE=true` is set, Router should be in hash mode.

## Minimal reproduction of the problem with instructions

// route module
https://github.com/JounQin/ng-rubick/blob/master/src/views/app.routing.module.ts#L24
// webpack config
https://github.com/JounQin/ng-rubick/blob/master/build/config.ts#L14
// Travis env config
https://github.com/JounQin/ng-rubick/blob/master/.travis.yml#L7

## Environment

Angular version: 6.0.0-beta.6

Browser:
- [x] Chrome (desktop) version  64.0.3282.186
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.7.1  
- Platform:  Mac 

Others:

- `@ngtools/webpack` version: 6.0.0-beta.4

**Comment by alexeagle** [comment]
This looks like a support request, which we don't handle on the issue tracker. Is there a bug somewhere?
Also, if this issue can't be reproduced without Angular CLI, then it should be filed on angular/angular-cli - thanks!
