### ISSUE TITLE
Offline documentation

### ISSUE THREAD

**Issue by imatmati** [angular/angular#22580]
Hi,

Could you please make an offline documentation in a format like PDF or HTML ?
I don't undestand why everyone out there seems to consider normal to make a documentation site with JS that you can't download to read offline. Do I really need a net connection just to read the doc or did I miss something ? 
Have a nice day.

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/19459

**Comment by imatmati** [comment]
Hi, 
Thanks for your reference. Unfortunately,I noticed it was closed. 
Too bad, because it would be really a plus. For instance, how am I supposed to read the docs on my android tablet in my train. Developers are more or less nomads but a web connection is not always possible. The pity is that I was able to mirror the VueJS site but not Angular's one.

**Comment by sarunint** [comment]
Thanks to Service Worker, [Angular's website](https://angular.io) works offline!

**Comment by imatmati** [comment]
Offline but with the need of a service worker. You still need a connection and a platform running a server ... So I would not say offline, because you still need a line even local.
Is it really the new norm to access documentation throw a server ?

**Comment by gkalpak** [comment]
> The pity is that I was able to mirror the VueJS site but not Angular's one.

Why is that? What problems did you run into, @imatmati?

> You still need a connection and a platform running a server

Not sure what you mean about needing a server. ServiceWorkers run in the browser and are able to handle requests, thus enabling an app to work as if online even when there is no network conectivity (assuming that the ServiceWorker has previously cached the necessary data - in our case docs content).

##
At the moment we are not caching the content of all docs (guides, API docs, etc), but only the top-level ones. We will soon switch to the latest `@angular/service-worker` (you can follow progress in #19795), which offers better/more flexible caching capabilities, including dynamic caching.

Once it's done, we could consider adding a way to cache all documents offline, but it is not in our top priorities. (We would happily accept contributions, I guess, if anyone is interested in investigating that.)

**Comment by sarunint** [comment]
You'll need to be online for the first time only. After that, you can access it offline.

Moreover, if there is a documentation update, it'll update automatically.

**Comment by imatmati** [comment]
Hi,

Thanks for your replies. AFAIK, I can't rely totally on the cache of my browser. I don't remember where, but I read something about that in an attempt to read the docs offline.
Concerning the service worker, correct me if I'm wrong, but I need to install js, yarn and dependencies. How to do it if I want to read the docs on my android browser ?

**Comment by gkalpak** [comment]
@imatmati, I am not talking about the browser cache, but the ServiceWorker cache. And no, a ServiceWorker does not require you to do anything. (In fact, you are already using a ServiceWorker in the current angular.io docs without having noticed.)

You might want to take a look at some generic resources on ServiceWorkers (like [this][1] and [that][2]) and then [our guide][3] to see how you could add ServiceWorker capabilities to your own Angular apps.

[1]: https://developers.google.com/web/fundamentals/primers/service-workers/
[2]: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API
[3]: https://angular.io/guide/service-worker-intro

**Comment by imatmati** [comment]
Thanks, I'll have a look and maybe my solution :-)

**Comment by gkalpak** [comment]
👍
Just tobe clear: It will not allow you to solve the problem with viewing angular.io offline (currently), but will possibly allow _us_ to solve this problem for you in the near future.

**Comment by ohboyotero** [comment]
Huge +1 for anybody that travels and wants to work with docs with either no connection or a spotty one.

**Comment by gkalpak** [comment]
I am closing this issue, because we don't plan to ship a different downloadable/printable format, such as PDF, (see #19459) and the offline availability for docs is tracked in #27492.

In the meantime, with this one weird trick, you can make all the docs available for offline access: [one weird trick][1]
<sub>(It is an unofficial hack, but it works for me and might work for you too :grin:)</sub>

[1]: https://twitter.com/gkalpakas/status/1065929759593562113
