### ISSUE TITLE
Feature: A way to skip queryParams changes when I'm subscribed to it

### ISSUE THREAD

**Issue by raeef-refai** [angular/angular#22582]
## I'm submitting a...
<pre><code>
[x] Feature request
</code></pre>

## Current behavior
There is no way to skip `queryParams` changes when I'm subscribed to it

## Expected behavior
A way to skip `queryParams` changes when I'm subscribed to it, For example:
<pre><code>
this.router.navigate(['/my-route'], { queryParamsEmitEvent: false });

// this won't be triggered when `queryParamsEmitEvent` is false
this.activatedRoute.queryParams.subscribe(params => console.log(params));
</code></pre>

**Comment by benneq** [comment]
I have a similar requirement: The same should be possible when using matrix params.

I want to change matrix params without triggering the router events:
```
activeRoute = /my-route
router.navigate([{foo: 'bar'}], {replaceUrl: true, SKIP_ROUTER_EVENTS: true})
=> activeRoute = /my-route;foo=bar
```

At the moment I use the Location service to achieve this:
```
constructor(router: Router, route: ActivatedRoute, location: Location) {
    // I want this only to get triggered when:
    // either the component is loading,
    // or the user manually edits the URL.
    // But this should NOT get triggered when I programmatically change the params
    route.params.subscribe(val => console.log(val));

    let url = router
        .createUrlTree([{foo: 'bar'}], {relativeTo: route})
        .toString();
    location.replaceState(url);
}
```

This looks quite unclean to me. Using the Router to create a string, which then is getting passed to the Location Service. I'm not sure yet if this approach will be problematic when using multiple Router Outlets. (anyone got experience with this?)

I would feel more comfortable if the Router could handle this. Though there should be an option within NavigationExtras like `skipRouterEvents`.

There are a few things to consider:
1. Should it skip all Router Events? Or make it configurable?
2. Use one option for everything (matrix params, query params, fragment) or make it configurable?
