### ISSUE TITLE
[bazel] ng_package cannot correctly resolve rxjs operators

### ISSUE THREAD

**Issue by Toxicable** [angular/angular#22596]
## I'm submitting a...
<pre><code>[x] Bug report </code></pre>

## Current behavior
When importing an rxjs operator and bundling it with ng_package you will receive:
>[!] Error: 'filter' is not exported by ../../../../../../../../../Users/fabianwiles/Downloads/ngx-tabs-libdemo-bazel/node_modules/rxjs/operators/index.js

## Expected behavior
Compile correctly

## Minimal reproduction of the problem with instructions
Clone https://github.com/Toxicable/ngx-tabs-libdemo/tree/bazel
run `yarn`
run `bazel build //...`

note the only change is in ngx-tabs-lib.module.ts
```
import { Observable } from 'rxjs/Observable';
import {filter} from 'rxjs/operators';

const t = new Observable();
t.pipe(filter(a => true))
```

## Environment
Angular version: 6.0.0-beta.6
```
Build label: 0.10.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jan 10 02:02:06 +50057 (1517480013726)
Build timestamp: 1517480013726
Build timestamp as int: 1517480013726
```

**Comment by alexeagle** [comment]
Two options:

1. `ng_package` accepts a `globals` attribute so you could do
```
globals = {
  "rxjs/operator/filter": "Rx.Observable.prototype"
}
```

2. pick up latest snapshot from github.com/angular/bazel-builds which includes a bunch more rxjs symbols in the default globals
