### ISSUE TITLE
ngAria module applies aria-disabled attribute to element when non-explicit false value is present

### ISSUE THREAD

**Issue by redconfetti** [angular/angular#2259]
I was recently coding a button to be disabled when a function indicating that the forms requirements have NOT been met ($scope.notReadyForProcessing) returns true, or when a scope variable indicating that the request is being processed ($scope.requestProcessing) is true.

I did not declare this requestProcessing variable as true in my controller, so it was left as an undefined in the controllers $scope. I applied the ngDisabled directive to my element like so:

```html
<button data-ng-disabled="notReadyForPreparation() || requestProcessing">Continue</button>
```

I found that while ngDisabled properly applies or unapplies the `disabled="disabled"` attribute to the button when this expression did not return an explicit TRUE value, ngAria did not unapply the aria-disabled attribute when the expression did not return an explicit TRUE value (returning undefined).

```javascript
> var scope = {};
> scope.a = false;
> scope.a || scope.b;
< undefined
```

Here is a [jsFiddle example](http://jsfiddle.net/redconfetti/0L3eL3ap/).

It seems that in my "Undefined Example" you can see that 'undefined' perhaps gets converted to TRUE when assigned to the scope via ngModel. I'm not completely sure what is causing that, as the Simple Example you see it's applying `aria-disabled="undefined"`.

**Comment by gdi2290** [comment]
@redconfetti yo, you're looking for the angular 1.x repo here https://github.com/angular/angular.js

**Comment by redconfetti** [comment]
@gdi2290 aah, sorry about that. Thanks
