### ISSUE TITLE
Refactor DirectiveDef to remove inputsPropertyName

### ISSUE THREAD

**Issue by kara** [angular/angular#22591]
Currently we have a property on the DirectiveDef called `inputsPropertyName`. This is only needed for properly implementing `NgOnChanges`, so instead of saving it on the def (where it won't be needed later), we should pass it into the feature directly.

cc @mhevery

**Comment by trotyl** [comment]
How about (allowing) minifying `SimpleChanges` keys as well? 

The inconsistency between `this['someProp']` and `changes['someProp']` may causing problems, eg:

```typescript
class MyComp implements OnChanges {
  someProp: string // becoming `a` at runtime

  ngOnChanges(changes: SimpleChanges) {
    for (let prop in changes) {
      // `prop` still being `someProp` here
      if (!this[prop]) {
        throw new Error(`Null value is not allowed`);
      }
    }
  }
}
```

Or:

```typescript
class MyComp implements OnChanges {
  someProp: string // becoming `a` at runtime

  ngOnChanges(changes: SimpleChanges) {
    // Got `{ someProp: ... }`
    if (changes.someProp) { // Becoming `if (changes.a)` at runtime
      console.log('Property changed');
    }
  }
}
```

Once https://github.com/angular/angular/pull/22103 arrived, `changes.someProp` will become much more popular than `changes['someProp']` for type-checking purpose, and could got broken when using advanced optimizers (maybe just closure compiler actually).
