### ISSUE TITLE
Authentication guard cannot mutate route (e.g. remove URL fragment)

### ISSUE THREAD

**Issue by m-chandler** [angular/angular#22598]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I'm using a router guard to trigger authentication via OIDC (Keycloak). The authentication guard triggers the authentication flow, including a redirect to the authentication server, and a redirect *back* to the angular app with the token as part of the URL fragment (i.e. "/admin/rental-codes#state=uvnlwejr5098...").

When the Angular app evaluates the authentication guard with the token, the Keycloak javascript client fetches the token from the url fragment, and then *removes* the fragment. Unfortunately when the Angular router finishes evaluating the authentication guard, it places the original path including the url fragment into the browser location. I must remove this url fragment, as it presents a number of issues if it remains in the browser location.

I was doing this within my authentication guard to clear the state, but I'm now finding that this doesn't work when the guard is on a parent route (i.e. "/admin") protecting child routes (i.e. "/admin/rental-codes")... as it essentially redirects to the route it's protecting ("/admin"), not the child route.
`
if (route.fragment === undefined) {
	return true;
} else {
	// Clear Keycloak state from URL fragment.
	this.router.navigate(['']);
	return false;
}
`

## Expected behavior

Authentication guards should not reset the browser location after they finish evaluating.

## Minimal reproduction of the problem with instructions

https://github.com/m-chandler/routing-example

## What is the motivation / use case for changing the behavior?

Clear authentication state from window location within route guard.

## Environment

<pre><code>
Angular version: 5.2.0

Browser N/A
 
For Tooling issues N/A

Others:

</code></pre>

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

<hr>

As currently implemented, the router doesn't allow mutations of the destination URL as part of the Guards phase. In order to get the behavior you want, it would be a new navigation.

Basically after the router finishes redirects, the destination should be considered immutable, and if you need to route to a different destination, issue a new navigation.
