### ISSUE TITLE
Dynamical adding new component to application that hosted with out building the whole application or using ng-build :angular 4/5

### ISSUE THREAD

**Issue by ajeeshc** [angular/angular#22592]
Am run into a situation where i really want to use Angular 5 because of one requirement question which am not able to find an answer I am forced to go with angular 1. Please help me to get an answer in how can i achieve the below scenario.

I have an application which is created and hosted in a server using angular 5. Its just a designer web site where user can use the template which is listed in the tool bar. A authorized third party can create a new template (following the guideline provided ) and there will be and option to upload the template as a Zip ( ideally it will be a component with on js,html and Css ) once its successfully uploaded and registering a the module to the list templates. the new template should be listed in toolbar so that the end user can use it.

In angular 5 when a new component created it should be refereed in app.module to make it available for the application. this is where am stuck because the third part not allowed to make changes in app.module. How to tackle this situation. Any help or guidance will be really helpful. Thanks in advance

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
