### ISSUE TITLE
Change Detection is not working properly when chrome.storage.sync uses

### ISSUE THREAD

**Issue by junimohano** [angular/angular#22607]
I am trying to create web extension using Angular 5.

I made array values and bind to it when getting the result from chrome.storage.sync on web extension.

after that, Change Detection is not properly working.

Do you have any solutions?

```
const test = [];

chrome.storage.sync.get('data', (items) => {
   this.test = items.data;
});
```

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by alexeagle** [comment]
@junimohano can you make a minimal repro for this? do you think the storage API does something differently from other event sources?

**Comment by junimohano** [comment]
@alexeagle 

I created it and can reproduce as it is simple.

Once I use storage API then, Angular doesn't work properly after that.

[https://github.com/junimohano/angular-chrome-storage-problem](url)

**Comment by trotyl** [comment]
This is expected, you'll need use [`ngZone.run()`](https://angular.io/api/core/NgZone#run) when working with Zone-unawared task schedulers. Or you can make a request to zone.js about [adding spec](https://github.com/angular/zone.js/blob/master/NON-STANDARD-APIS.md) for chrome.storage APIs.

Either way this is not an Angular issue.

**Comment by junimohano** [comment]
@trotyl  I already tried ngZone.run() which still doesn't work.

**Comment by trotyl** [comment]
@junimohano Please provide code of using `ngZone.run()` (your way) then.
