### ISSUE TITLE
Retrieve data from incoming HTTP request - Angular 4

### ISSUE THREAD

**Issue by arj060892** [angular/angular#22603]
I want to retrieve header values from the incoming HTTP Requests, which is coming to my Web App[angular application] and use the retrieved values in the application for other outgoing requests. My angular application is hosted via IIS. I tried using HttpHeaders but its only configurable for outgoing requests.

Please let me know whether its possible or not , if not then what are the work around :)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
