### ISSUE TITLE
Reactive form setControl sets disabled form to enabled.

### ISSUE THREAD

**Issue by jraadt** [angular/angular#22608]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If you have a disabled form and then add a control to it using setControl, the form becomes enabled.

## Expected behavior

The form should stay disabled.

## Minimal reproduction of the problem with instructions

```
this.form = this.formBuilder.group({ users: this.formBuilder.array([])});
this.form.disable();
// The form is now disabled.
this.form.setControl('users', this.formBuilder.array(users));
// The form is now enabled, which it shouldn't be.
```

## What is the motivation / use case for changing the behavior?

A form that has been set to disabled shouldn't become enabled without the developer explicitly enabling it.

## Environment

<pre><code>
Angular version: 5.1.2

Browser:
- [X] Chrome (desktop) version Latest
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by tashoecraft** [comment]
Can reproduce: https://stackblitz.com/edit/angular-kqlra5

**Comment by kara** [comment]
@jraadt A form is only disabled if all of its controls are disabled. When you add an enabled control to a disabled form, it's expected that the form would be enabled. You can fix the code by setting the control to an array with disabled controls.
