### ISSUE TITLE
Strange UI binding behavior for Date data type

### ISSUE THREAD

**Issue by vsmahesh** [angular/angular#22604]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
One-way binding using date is not working as expected

## Expected behavior
One-way binding with date datatype should work as with the String and number data types

## Minimal reproduction of the problem with instructions
Issue is explained in the following stackoverflow question https://stackoverflow.com/questions/49125356/angular-strange-ui-binding-bahavior-for-date

## What is the motivation / use case for changing the behavior?
It is a basic expectation to work in the suggested way

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
Expected behavior. You're binding `currentDate` to view and `currentDate` wasn't changed at all.
There won't be a recursive deep compare for object values.

Simpler repro: https://stackblitz.com/edit/angular-yxpjwb-6btsrx?file=src/app/heroes/heroes.component.ts

**Comment by vsmahesh** [comment]
Agree! The work around I've found is to re-initialize the date. 

However, note that it works fine when you remove the <br /> after it! So it seems something needs to be improved here.

**Comment by vsmahesh** [comment]
Agree! The work around I've found is to re-initialize the date. 

However, note that it works fine when you remove the 'br' after it! So it seems something needs to be improved here.

**Comment by trotyl** [comment]
The refreshing unit is [`Node`](https://developer.mozilla.org/en-US/docs/Web/API/Node), you cannot update partial bindings , with `<br>` in between they're two individual [`Text`](https://developer.mozilla.org/en-US/docs/Web/API/Text)s, so unrelated.
