### ISSUE TITLE
Commit message wrongly formatted

### ISSUE THREAD

**Issue by sarunint** [angular/angular#22618]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When I submit a PR, the ci/circleci: lint check always fail due to commit https://github.com/angular/angular/commit/d8abf70f1f420d9227d4fc700c79dac3c71d9a99

## Expected behavior

Commit Message lint passes

## Minimal reproduction of the problem with instructions

N/A

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
that commit has nothing to do with commit linting

**Comment by sarunint** [comment]
Oh I mean the commit message of commit https://github.com/angular/angular/commit/d8abf70f1f420d9227d4fc700c79dac3c71d9a99 is wrongly formatted.

CircleCI complains this:

![image](https://user-images.githubusercontent.com/3850197/37083048-e4009fea-2220-11e8-96e5-98203de10622.png)

**Comment by alexeagle** [comment]
We should move the commit message formatting check to a husky pre-commit hook
