### ISSUE TITLE
Bazel: Cannot import a re-exported class annotated with @NgModule

### ISSUE THREAD

**Issue by mrmeku** [angular/angular#22612]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently, when building with bazel, you cannot import a re-exported a class annotated with @NgModule. 

Here is a minimal reproduction: https://github.com/mrmeku/angular-bazel-example/commit/977f82f4ffbe771f8d7b63bda40d08706ef59c38

## Expected behavior
`bazel run //src:devserver` should not error out. 

## Minimal reproduction of the problem with instructions
`git clone git@github.com:mrmeku/angular-bazel-example.git`
`git checkout re_export_ng_module`
`bazel run //src:devserver`

## What is the motivation / use case for changing the behavior?
Feature parity with Angular CLI

**Comment by alexeagle** [comment]
A component must be compiled together in the same `ng_module` rule with the NgModule that declares it. I think by moving the files around this way, you also need to change the compilation unit boundaries?

**Comment by mrmeku** [comment]
The component is still compiled with the same ng_module which declares it. That compilation unit is then re-exported by a parent compilation unit (as far as my understanding goes)

**Comment by gregmagolan** [comment]
Note: the min reproduction example builds and runs if the nested dependency is explicitly specified in the `//src:src` ng_module target like so: ```ng_module(
    name = "src",
    srcs = glob(["*.ts"]),
    tsconfig = ":tsconfig.json",
    deps = ["//src/public-api", "//src/public-api/hello-world"],
)```

**Comment by gregmagolan** [comment]
Tracked down the issue to the nested dep `.d.ts` files not being included in the allowedStrictDeps of generated `tsconfig.json` file for the `//src:src` compilation unit.

Without the explicit dep:

```
      "allowedStrictDeps":[  
         "bazel-out/darwin-fastbuild/bin/src/public-api/index.d.ts",
         "src/app.component.ts",
         "src/app.module.ts",
         "src/main.ts"
      ],
```

With the explicit dep:

```
      "allowedStrictDeps":[  
         "bazel-out/darwin-fastbuild/bin/src/public-api/index.d.ts",
         "bazel-out/darwin-fastbuild/bin/src/public-api/hello-world/hello-world.component.ngfactory.d.ts",
         "bazel-out/darwin-fastbuild/bin/src/public-api/hello-world/hello-world.component.ngsummary.d.ts",
         "bazel-out/darwin-fastbuild/bin/src/public-api/hello-world/hello-world.component.d.ts",
         "bazel-out/darwin-fastbuild/bin/src/public-api/hello-world/hello-world.module.ngfactory.d.ts",
         "bazel-out/darwin-fastbuild/bin/src/public-api/hello-world/hello-world.module.ngsummary.d.ts",
         "bazel-out/darwin-fastbuild/bin/src/public-api/hello-world/hello-world.module.d.ts",
         "bazel-out/darwin-fastbuild/bin/src/public-api/hello-world/hello-world-styles.css.shim.ngstyle.d.ts",
         "bazel-out/darwin-fastbuild/bin/src/public-api/hello-world/hello-world-styles.css.ngstyle.d.ts",
         "src/app.component.ts",
         "src/app.module.ts",
         "src/main.ts"
      ],
```

The rest of the two tsconfig files is the same.

**Comment by gregmagolan** [comment]
It wasn't the strict deps. The issue was that the ngsummary JSON files were not being exposed for nested deps. #22761 fixes this.
