### ISSUE TITLE
Bazel: Cannot import an ng_module from an external workspace

### ISSUE THREAD

**Issue by mrmeku** [angular/angular#22613]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Consider how rxjs allows you to build form source:
They have a workspace file in the `src` directory: https://github.com/ReactiveX/rxjs/blob/master/src/WORKSPACE

And a BUILD.bazel file in their `src` directory: 
https://github.com/ReactiveX/rxjs/blob/master/src/BUILD.bazel

Their BUILD.bazel file uses a ts_library build rule and works great. If, however, they needed to use an ng_module build rule it wouldn't for two reasons

1. `ng_module` uses short path to calculate where ngfactory and ngsummary files should live. `short_parth`s for external repositories have a ../ prefix. The fix is to replace `short_path` with `path`. The bug is demonstrated here: https://github.com/mrmeku/angular-bazel-example/commit/a4346cd87d6acf295950da3bffe1a82aa11478c5
2. `module_name` works differently between `ts_library` and `ng_module` as demonstrated here: https://github.com/mrmeku/angular-bazel-example/commit/081cd718b9b0700d588b19e89141c7046a24d2ae

## Expected behavior
External workspaces should be able to have ng_module targets others can depend upon.

## Minimal reproduction of the problem with instructions
Contact me for one. I have one in a private repo.

Alternatively:
`git clone https://github.com/alexeagle/angular-bazel-example`
`bazel run @yarn//:yarn`
Manually go into `//node_modules/rxjs/src/BUILD.bazel` and change the ts_library to an ng_module
`bazel build //src`

**Comment by alexeagle** [comment]
`ng_module` does accept `module_name` - that's how we build angular itself:
https://github.com/angular/angular/blob/master/packages/core/BUILD.bazel#L13

I don't understand what's wrong with the computed path for the ngfactory file, can you explain?

**Comment by mrmeku** [comment]
Here's an example of the bug using the angular bazel example: https://github.com/mrmeku/angular-bazel-example/commit/a4346cd87d6acf295950da3bffe1a82aa11478c5

**Comment by mrmeku** [comment]
I updated the bug description with a minimal reproduction of the `module_name` bug I was alluding too: https://github.com/mrmeku/angular-bazel-example/commit/081cd718b9b0700d588b19e89141c7046a24d2ae . The bug isn't that module_name isn't accepted by ng_module, but rather that if functions differently for ng_module than it does for ts_library

**Comment by divdavem** [comment]
I am also facing this issue while trying to use bazel to build [ng_bootstrap](https://github.com/ng-bootstrap/ng-bootstrap) (cf the [bazel branch of my fork of ng-bootstrap](https://github.com/divdavem/ng-bootstrap/tree/bazel)).
Especially, using `ts_devserver` does not work when using `module_name` in `ng_module`.

You can reproduce this issue with [my sample repository](https://github.com/divdavem/angular_bazel_bug_module_name) in the following way:
```
git clone https://github.com/divdavem/angular_bazel_bug_module_name.git
cd angular_bazel_bug_module_name
bazel run @yarn//:yarn
bazel run //src/myapp:devserver
```
Then go to http://localhost:5432. You can see the following errors on the console:

![image](https://user-images.githubusercontent.com/1152706/37590567-fcda8bba-2b68-11e8-8804-9cde92ba2392.png)

When stopping on the error in the debugger:

![image](https://user-images.githubusercontent.com/1152706/37591031-73d1de66-2b6a-11e8-9561-a9b1242b0c7c.png)

You can see on the screenshot above that `i1` is undefined (it was initialized with `var i1 = require("angular_bazel_bug/src/mylib/mycomponent.ngfactory")` which does not use the `module_name`) while `i2` is correctly defined (it was initialized with `var i2 = require("@mylib/mylib/mycomponent");` which uses the `module_name`).

Note that:
- if you revert the [last commit](https://github.com/divdavem/angular_bazel_bug_module_name/commit/56f162df29a74adf94aeff86071ba5f0c9bb8393) (which adds the `module_name` parameter), the dev server works fine (`git checkout master~1 && bazel run //src/myapp:devserver`).
- bundling with rollup works fine (`git checkout master && bazel run //src/myapp:prodserver`)

**Comment by stoltene2** [comment]
I'm also experiencing a similar issue where I want to import an ng_module existing in an external repository. The motivation is to incrementally upgrade a large repository while living alongside the existing build infrastructure.

I simulated the problem by creating two project directories each with a WORKSPACE file. Project1 depends on the hello-world module produced in project2.

https://github.com/graybeards/angular-bazel-example/tree/51b4e90d93efa02244011c96ed6eed656dd3843e

In the reproducible example repository I see the following error when attempting to build inside of project1:
```
$ bazel build //src 
INFO: Analysed target //src:src (1 packages loaded).
INFO: Found 1 target...
ERROR: /home/eric/workspace/angular-bazel-example-bug-in-multi-repo/project1/src/BUILD.bazel:5:1: Compiling Angular templates (ngc) //src:src failed (Exit 1)
src/app.module.ts(6,32): error TS2307: Cannot find module './hello-world/hello-world.module'.

Target //src:src failed to build
```

In my project, I see the error that #22755 resolves. I'm unsure if  #22755 fixes the above error, though.
