### ISSUE TITLE
Router should use strongly typed (and error-checked) classes, not maps

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2261]
Before

```dart
@RouteConfig(const [
  const {
    'path': '/pipeline',
    'component': GtPipelineComponent,
    'as' : 'pipeline'
  },
  const {
    'path': '/cleanup',
    'component': GtCleanupComponent,
    'as' : 'cleanup'
  }
])
```

After

```dart
@RouteConfig(const [
  const Route(
    path: '/pipeline',
    component: GtPipelineComponent,
    as : 'pipeline'
  ),
  ...
])
```

e.g.

```dart
class Route {
  const Route({String path, Type component, String as, String redirectTo})
}
```

Additionally, this could use errors/assertions to catch invalid configuration, e.g. having component AND redirectTo should throw

**Comment by btford** [comment]
:+1: 

We'll still want to accept Maps for JS devs, but I'm happy to add this if it's more idiomatic for Dart.

**Comment by naomiblack** [comment]
this is internal issue b/21563833

**Comment by matanlurey** [comment]
It's not possible to get refactoring or type checking without maps, e.g., if you were to change the API it could fail silently.

**Comment by alexeagle** [comment]
`@RouteConfig` is just different from other annotations at present, right? Others like `@View` have a typed interface for their argument, which is called using object literal syntax from JS but produce a typed Dart API, so IIUC this issue is just to follow the same pattern in Router?
I'm asking to understand whether we need something improved in the expressibility of our type system or ts2dart.

**Comment by btford** [comment]
@alexeagle – This wouldn't involve any changes to our type system.

In TS/JS, I think it's still going to be more idiomatic to use maps.

**Comment by matanlurey** [comment]
Just curious, isn't the goal in typescript to have typed classes? Why would you prefer a map where a user can't easily tool/ide-refactor any of the properties and has no idea if the value they assign is valid without re-running the app (e.g. no static analysis)?

**Comment by btford** [comment]
>  Why would you prefer a map where a user can't easily tool/ide-refactor any of the properties and has no idea if the value they assign is valid without re-running the app (e.g. no static analysis)?

TS has interfaces that can hint what should be in the map. And just knowing the type (`path` is a string) isn't enough to know if the route is configured correctly anyways.

Aesthetically, I expect that this:

```
@RouteConfig([
  { path: '/foo', component: FooCmp }
])
```

Is going to be preferred over this:

```
@RouteConfig([
  new Route({ path: '/foo', component: FooCmp })
])
```

Of course I'll leave the second option open for TS folks.

**Comment by alexeagle** [comment]
Your first option can still be structurally typed with an interface and not
use a map. As long as we agree on what expressions are valid router
configurations, we can make TS typings that properly restrict to those, and
give the right completion and error-checking.

**Comment by btford** [comment]
> Your first option can still be structurally typed with an interface and not use a map

+1; this is exactly what I was thinking.

>  As long as we agree on what expressions are valid router configurations, we can make TS typings that properly restrict to those, and give the right completion and error-checking.

I was more talking about something like `'/#)?#(foo'` being an invalid value for path, or having a parent without a trailing "continuation" segment having children, which AFAIK can't be expressed in TS's type system.
