### ISSUE TITLE
Angular Animations: query(':enter') and query(':leave') return zero elements in a Hybrid Angular Application that tries to animate Route Changes

### ISSUE THREAD

**Issue by kvnnap** [angular/angular#22625]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Adding two or more downgraded Angular components in the root AngularJS Application's HTML makes query(':enter, :leave') function return zero elements. This only happens when the second downgraded component is encountered. If the component that requires animation is moved up in the DOM, it works. If both components require animation, only the first component will have its animation working.

## Expected behavior

query(':enter') and query(':leave') should return the leaving and entering elements when the route changes independent of the surrounding components within the application.

## Minimal reproduction of the problem with instructions

I have reproduced this issue with the latest stable releases of both Angular (5.2.7) and AngularJS (1.6.9). A StackBlitz demonstration of this issue can be found [here](https://stackblitz.com/edit/angular-animation-bug). I have left the code in the broken state, to see the animations working again, it is necessary to comment `<hello name="Angular Team"></hello>` from _line 7_ in _index.html_. It can be noted that uncommenting _line 15_, while _line 7_ is commented, reintroduces the same component but this time after the app component, and leaves the application in a working state. Hence, this issue depends on the order of how the components are layed out, as explained earlier.

## What is the motivation / use case for changing the behavior?

My aim is to be able to animate components within route transitions in a hybrid Angular application using Angular 5 animations.

## Environment

<pre><code>
Angular    version: 5.2.7,
AngularJS version: 1.6.9

Browser:
- [x] Chrome (desktop) version 64
- [x] Chrome (Android)

Haven't tested any other browsers

**Comment by dylhunn** [comment]
AngularJS is now EOL.
