### ISSUE TITLE
[BUG] Lifecycle : Throwing error in @Input setter creates infinite change detection loop

### ISSUE THREAD

**Issue by seedy** [angular/angular#22620]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have an Input setter method which throws an error.
Input setter is expected to be called each time the value actually changes.
Error output happens twice, while input value doesn't change.

## Expected behavior

 Single error output.

## Minimal reproduction of the problem with instructions

See
https://stackblitz.com/edit/angular-gitter-a835wt
## Environment
See stackblitz.
<pre><code>
Angular version: X.Y.Z

Browser:
- [X] Chrome (desktop) version 64.0.3282.167
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@seedy ... you run it dev mode and not in production mode?

**Comment by seedy** [comment]
@mlc-mlapis,  yes sir!
The provided stackblitz example runs in dev mode.
I tried in prod mode and saw it fired only once.

Still I don't understand this behaviour in dev mode.

**Comment by mlc-mlapis** [comment]
@seedy ... yes, it's expected because of checking on the beginning CD and re-checking after CD cycle where the re-checking is not done in production mode.

**Comment by seedy** [comment]
Didn't know that, sorry then.
