### ISSUE TITLE
i want to get data from the material design data table. 

### ISSUE THREAD

**Issue by lintojohny** [angular/angular#22621]
## I'm submitting a...

<pre><code>
<div class="example-container mat-elevation-z8">

      <div class="example-header">
        <mat-form-field>
          <input matInput (keyup)="applyFilter($event.target.value)" placeholder="Filter">
        </mat-form-field>
      </div>

      <mat-table #table [dataSource]="dataSource" [trackBy]="myTrackById">

        

        
        
        <ng-container matColumnDef="name">
          <mat-header-cell *matHeaderCellDef>Options Value Name: </mat-header-cell>
          <mat-cell *matCellDef="let element;let i=index ">
            <input type="hidden" name="{{'option_value[' + i + '][option_value_id]'}}" [value]="element['option_value_id']" />

            <input name="{{'option_value[' + i + '][option_value_description][1][name]'}}" [value]="element['option_value_description'][1]['name']"
            />
          </mat-cell>
        </ng-container>

        <ng-container matColumnDef="shortcode">
          <mat-header-cell *matHeaderCellDef> Option Value Shortcode </mat-header-cell>
          <mat-cell *matCellDef="let element">
            

            <input name="{{'option_value[' + i + '][option_value_description][1][shortcode]'}}" [value]="element['option_value_description'][1]['shortcode']"
            />
          </mat-cell>
        </ng-container>

        <ng-container matColumnDef="image">
          <mat-header-cell *matHeaderCellDef> Image: </mat-header-cell>
          <mat-cell *matCellDef="let element">
            <img src="no_image-100x100.jpg" alt="">
            <br>
            <div class="z_img">
              <a href="">browse files</a> |
              <a href="">clear files</a>
            </div>
          </mat-cell>
        </ng-container>
        <ng-container matColumnDef="pos_image">
          <mat-header-cell *matHeaderCellDef> Pos Image </mat-header-cell>
          <mat-cell *matCellDef="let element">
            <img src="no_image-100x100.jpg" alt="">
            <br>
            <div class="z_img">
              <a href="">browse files</a> |
              <a href="">clear files</a>
            </div>
          </mat-cell>
        </ng-container>
        <ng-container matColumnDef="sort_order">
          <mat-header-cell *matHeaderCellDef> sort_order </mat-header-cell>
          <mat-cell *matCellDef="let element"> {{element.sort_orde}} </mat-cell>
        </ng-container>

        
        <ng-container matColumnDef="remove">
          <mat-header-cell *matHeaderCellDef> Remove
          </mat-header-cell>
          <mat-cell *matCellDef="let element" (click)="onRemoveOption(element.option_value_id)">
            <pre> {{element.option_value_id }} </pre> </mat-cell>
        </ng-container>
        

        <mat-header-row *matHeaderRowDef="displayedColumns"></mat-header-row>
        <mat-row *matRowDef="let row; columns: displayedColumns;" (click)="selection.toggle(row)">
        </mat-row>

      </mat-table>
    </div>
</code></pre>

########ts file
<pre><code>
// tslint:disable-next-line:max-line-length
  constructor(private WebService: WebService[],public toastr: ToastsManager, vcr: ViewContainerRef, private userService: WebService, private route: ActivatedRoute, private fb: FormBuilder, private webserve: WebService, private router: Router) {
    this.toastr.setRootViewContainerRef(vcr);
    this.token = localStorage.getItem('token');
    console.log('token value', this.token);
    this.route.params.subscribe(params => {
      this.option_id = params['id']
      this.webserve.editOptions(this.option_id).subscribe(data => {
        console.log('category_id', this.option_id);
        console.log('this is response', data);
        console.log('this is table', data);
        this.option = data;
        this.displayedColumns = ['name','shortcode','image','pos_image', 'sort_order', 'remove'];
        this.dataSource = new MatTableDataSource(data['option_values']);
        this.selection = new SelectionModel<Element>(true, []);
      });

    }); 

  }
</code></pre>
## Current behavior

not able to get the data from the table. i were edited the table data using input html tag and bind the data to name.

## Expected behavior

expecting to get the full data from the data table

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by lintojohny** [comment]
ok thank you
