### ISSUE TITLE
Document SwPush

### ISSUE THREAD

**Issue by adamzr** [angular/angular#22627]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

Please document the SwPush service that @angular/service-worker has to support push notifications.

**Comment by gkalpak** [comment]
FWIW: there are some API docs here: https://angular.io/api/service-worker/SwPush

**Comment by adamzr** [comment]
@gkalpak that's good to know, thanks! But, what I really want is a full guide on how to do push notifications with Angular.

**Comment by vleput** [comment]
A short documentation on Push Notifications with Angular would definitely help

For those interested I found that [this article](https://blog.angular-university.io/angular-push-notifications/) was a good first dive into the topic.

Still had to dive into the `ngsw-worker.js` code to figure out subtilities (like the fact that the notification payload needs to be wrapped in a `notification` object)

**Comment by FoseFx** [comment]
For those who are not willing to take a deep dive into their ngsw-worker.js file here's a bit of research I did regarding SwPush:

SwPush is an Angular API to subscribe and unsubscribe to the ngsw's PushManager for the purpose of creating a Push Notification.

More information regarding this topic: 

- https://developers.google.com/web/fundamentals/codelabs/push-notifications/

- https://developer.mozilla.org/en-US/docs/Web/API/Push_API





1. You can Inject `SwPush` into any component or service.

```
import {SwPush} from '@angular/service-worker';
...
constructor(private swPush: SwPush) {}
...
```

2. To subscribe call `requestSubscription` which will ask the user for permission.

`requestSubscription` returns a Promise holding your PushSubscription.

[The API docs are quite useful.](https://angular.io/api/service-worker/SwPush#requestsubscription)

When it rejects these are possible reasons:

- User denied permissions

- [Browser blocks or does not support the Push API](https://developer.mozilla.org/en-US/docs/Web/API/Push_API#PushMessageData)

- [Browser blocks does not support ServiceWorkers](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker#Browser_compatibility)



```
async subscribeToPush() {
    try {
      const sub = await this.swPush.requestSubscription({
        serverPublicKey: PUBLIC_VAPID_KEY_OF_SERVER
      });
      // todo send to server
    } catch (e) {
      console.error('Could not subscribe', e);
    }
  }
```



3. You can invoke Push Notifications by pushing a message with the following payload:

```

{
	"notification": {
		"actions": NotificationAction[],
		"badge": USVString
		"body": DOMString,
		"data": any,
		"dir": "auto"|"ltr"|"rtl",
		"icon": USVString,
		"image": USVString,
		"lang": DOMString,
		"renotify": boolean,
		"requireInteraction": boolean,
		"silent": boolean,
		"tag": DOMString, 
		"timestamp": DOMTimeStamp, 
		"title": DOMString, 
		"vibrate": number[]
	}
}

```
Only the `title` is required.

https://developer.mozilla.org/en-US/docs/Web/API/Notification#Instance_properties



NgSw will listen to the PushEvent and create the Notification.



4. You can unsubscribe using `swPush.unsubscribe()`. Again the API is a good place to start.

**Comment by jbogarthyde** [comment]
Resolved by https://github.com/angular/angular/pull/32139
