### ISSUE TITLE
Adding a route item in the routes array after it's init

### ISSUE THREAD

**Issue by astalegale** [angular/angular#22624]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Adding a new route to the route-array using push or unshift doesn't work.
When i write the route in the browser, the application redirect to me to 404.

## Expected behavior

That the new route is added

## Minimal reproduction of the problem with instructions

in app.routing.ts: 
```

const appRoutes: Routes = [

    { path: `download`, component: DownloadComponent, pathMatch: 'full' }
    , { path: '404', component: PageNotFoundComponent, pathMatch: 'full' }
    , { path: '**', redirectTo: '404' }
];


const appRoutes2: Routes = [
    { path: '', component: HomeComponent, pathMatch: 'full' }
];

if (!environment.production) {
    appRoutes.unshift(...appRoutes2);
//     appRoutes.unshift(appRoutes2[0]); // not working too
}

```
## What is the motivation / use case for changing the behavior?

I need to add a route based on an environment variable

## Environment

<pre><code>
Angular version: 5.2.7

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by TooHTooH** [comment]
Can you have a full example ?
Looks like it's working here: 
https://stackblitz.com/edit/angular-bfnkgx?file=src/app/app-routing.module.ts

You sure that you have the url without the `/` to be able to be redirected to `HomeComponent` ?

**Comment by astalegale** [comment]
@TooHTooH Thanks for help!
I've modified your example to recreate the issue, take a look:

[(https://stackblitz.com/edit/angular-bfnkgx-bvt3ue?file=src/app/app-routing.module.ts)]

Thanks!
Alex

**Comment by jasonaden** [comment]
I believe this is just an error in the JavaScript. You're unshifting an array into the Routes array, rather than unshifting a route config into the routes array. I believe this change fixes your issue:

```
if (!environment.production) {  
  routes.unshift(environment.others1[0]);
}
```
