### ISSUE TITLE
Not able to use Keyup events in virtual Keyboad

### ISSUE THREAD

**Issue by mitalthakkar31** [angular/angular#22649]
## I'm using Virtual Keyboard for my one of Angular Project where i want to use keyUp event for input validation but not able to use keyup/keydown/keypress any events for virtual keyboard .Events are working fine for hardware Keyboard so there is no syntax error.

#my code is as below
  <input class="search" 
                  type="text" 
                  matInput 
                  [matKeyboard]="'Azərbaycanca'"
                  placeholder="Search for a song"
                  (keyup.enter)="search_result();"   
                   (enterClick)="closeCurrentKeyboard();"
                   (keyup)="function();"
              >    
              
#Virtual keyboard i am using is refrenced from this link-->
 https://github.com/ngx-material-keyboard/core

I had tried a lot of substitute but not able to get perfect solution.Please help me with Solution.

**Comment by alexeagle** [comment]
Maybe file it on ngx-material-keyboard/core ?

**Comment by mitalthakkar31** [comment]
ok i will file.thanks
