### ISSUE TITLE
Suggestion: notify when a reusable route is attached or detached

### ISSUE THREAD

**Issue by StevenLiekens** [angular/angular#22647]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When using a custom RouteReuseStrategy to store router states (instead of destroying them), there is no easy way to get notified when a component is detached from its outlet or reattached to its outlet.

## Expected behavior

I think that there should be lifecycle hooks and events for reusable routes, similar to the ones we already have for non-reusable routes (`ngOnInit` / `ngOnDestroy` / `activateEvents` / `deactivateEvents`).

When `RouteReuseStrategy.shouldDetach` evaluates to `true`
- `ngOnDetach` is invoked on the component
- `RouterOutlet.detachEvents` is emitted

When `RouteReuseStrategy.shouldAttach` evaluates to `true`
- `ngOnAttach` is invoked
- `RouterOutlet.attachEvents` is emitted

## What is the motivation / use case for changing the behavior?

I need to clean up stuff when a route is detached and I need to reinitialize stuff when a route is reattached.

The problem that I face is that long-lived observable subscriptions are not unsubscribed when a route is detached. My subscriptions are created in `ngOnInit` and unsubscribed in `ngOnDestroy`. Neither of those hooks are called when a router state is detached.

This turns into a real problem when subscriptions cause code to run inside components that are detached.

## Environment

<pre><code>
Angular version: 2.3+

</code></pre>

**Comment by StevenLiekens** [comment]
I improved my motivation for notifying components when they are attached or detached.

**Comment by ToxSickCoder** [comment]
I ran into this issue today as well. I have a component that needs to redraw because it renders wrong while the route is detached. However, there is no way of knowing when the component attaches, and thus no way of knowing when to redraw.

**Comment by gnovotny** [comment]
You can create trigger custom lifecycle events using a custom RouteReuseStrategy. See https://gist.github.com/gnovotny/ef110975dab290a365814a62158ce876

**Comment by thorn0** [comment]
Duplicate of #25521. This issue was submitted first, but #25521 contains a more specific proposal.

**Comment by StevenLiekens** [comment]
@thorn "duplicated by" is a non-misleading way to put it. ;)

**Comment by StevenLiekens** [comment]
@alexeagle @jasonaden closing this because #25521 contains the same suggestion but much more detailed.
