### ISSUE TITLE
In AIO docs, indicate that`ReactiveFormsModule.withConfig` method is deprecated

### ISSUE THREAD

**Issue by kara** [angular/angular#22640]
Example: 

```ts
export class ReactiveFormsModule {
  static withConfig(opts: {
    /** @deprecated from v6 */ warnOnNgModelWithFormControl: 'never' | 'once' | 'always'
  }): ModuleWithProviders {
    return {
      ngModule: ReactiveFormsModule,
      providers: [{
        provide: NG_MODEL_WITH_FORM_CONTROL_WARNING,
        useValue: opts.warnOnNgModelWithFormControl
      }]
    };
  }
}
```

**Comment by petebacondarwin** [comment]
Can we clarify what should happen if this occurs?

Right now, "literal types" like this are not currently documented in any real sense except by a description on the parameter itself. Moreover, as it stands right now, they are not parsed as "dgeni documents" in themselves so we don't read any jsdoc tags on such a comment. The TypeScript parser is able to read the comment and attach it appropriately in its AST so it would be possible to do something with it.

That being said, I would like to propose that if one wants to mark up literal types like this, then it is an indicator that perhaps it is time to convert the literal type into an interface instead. This can then be fully documented and each of its members can be tagged individually.

**Comment by petebacondarwin** [comment]
@IgorMinar - the last paragraph of my previous comment is perhaps a more general comment about the Angular code base. I think we use too many literal types, especially large ones, which might look neat at the time and work well with intellisense but are a pain to document (as @jbogarthyde has found).  My understanding from @alxhub is that too many interfaces are frowned upon as it dilutes the API surface, but I would argue it just moves the API surface complexity elsewhere. From a documentation point of view, we could tag some API elements as "primary" and make them more visually prominent in the docs. Perhaps we could filter out the auxiliary API elements from the main views and only show them if requested?

**Comment by petebacondarwin** [comment]
I think that this is not feasible as it stands. If a type is complex enough that it needs individual members deprecating then it should be converted to an interface IMO.

**Comment by JoostK** [comment]
@petebacondarwin downside is that it would require exporting that type as part of the public API, which is not currently necessary.

**Comment by petebacondarwin** [comment]
Yes, but it's kind of a chicken and egg thing. If it is complex enough to warrant documenting then I would argue it *should* be part of the public API.

**Comment by jenniferfell** [comment]
Decision: Deprecate the method or describe the deprecation in text descriptions.

**Comment by jenniferfell** [comment]
Change this issue to one to fix the reactiveformsmodule doc specifically

**Comment by jenniferfell** [comment]
Related: https://github.com/angular/angular/issues/30098

**Comment by mgechev** [comment]
Seems like the issue is no longer relevant. Please open a new issue if I'm mistaken.
