### ISSUE TITLE
downgradeComponent: digest is not triggered after two-way binding is updated

### ISSUE THREAD

**Issue by FDIM** [angular/angular#22648]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently when two-way bindings (or outputs) are setup in a downgraded component no digest is triggered. Actual expression is evaluated and the value on scope is updated, but no watchers are invoked until next digest.

## Expected behavior

2 potential solutions:
- a digest should be invoked when expression is executed, so somewhere here: https://github.com/angular/angular/blob/master/packages/upgrade/src/common/downgrade_component_adapter.ts#L197
- ability to detect inside the component if it runs in 'angularjs component' without changing the api. How about a public field `$downgraded`=`true` that would be set here: https://github.com/angular/angular/blob/master/packages/upgrade/src/common/downgrade_component.ts#L116 so that a digest could be triggered manually only when needed.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/ngupgradestatic-playground-sw7maz

When you open the link above and the app hopefully compiles and runs you will be presented with a simple counter example. It has a label rendered by angularjs, 2 buttons: `increment` and `increment (with digest)` and another label rendered by angular 5.

Clicking either of the buttons will increment the count property and emit change event, which in turn should update both labels. Currently only the second button will update first label.

## What is the motivation / use case for changing the behavior?
To be able to use downgraded component with two way bindings transparently inside angularjs component and in angular 5 component

## Environment

<pre><code>
Angular version: 5.2.x

Browser: any

</code></pre>

**Comment by gkalpak** [comment]
This works as intended afaict. This is exactly the type of case where you have to "pay the price" for the performance benefits that `downgrdeModule()` offers, by having to manually trigger a `$digest`.

I don't think that a `$digest` should be triggered by default when an output emits a new value (since that is likely to unnecessarily hurt performance in many cases), but we have discussed it in the past (and agree) that making it (and other similar behaviors) configurable would be nice.

This isn't high in our priorities (since there are ways to work around it), but if anyone wants to work a PR, I would be happy to offer help/guidance.

##
BTW, I do not understand your second suggestion: 

> ability to detect inside the component if it runs in 'angularjs component' without changing the api. How about a public field $downgraded=true that would be set [here](https://github.com/angular/angular/blob/master/packages/upgrade/src/common/downgrade_component.ts#L116) so that a digest could be triggered manually only when needed.

**Comment by FDIM** [comment]
I agree with you, that triggering a digest on each emit would be a bit too much. On the flip side, handling it manually in each binding in the components that use downgraded version is also quite inconvenient, especially when some of them are 2 way and you actually rely on digests to keep view up-to-date.

After looking more deeply into the source code, it seems to be possible to detect when a component is used in angularjs template and when in angular 5 component. I really want to keep the API of the component the same for normal use and in downgraded version and therefore going with my second suggestion.

I'll be injecting `@Inject('$scope') @Optional() $scope` into downgraded components and checking if scope is available, if it is - I'll subscribe to relevant component outputs (either in ngOnInit, or ngAfterViewInit) and cause a digest on `$rootScope` if one is not in progress.

Could this be mentioned in https://angular.io/guide/upgrade#using-angular-components-from-angularjs-code ? I mean that it's up to the developer to handle digests for downgraded components and a possible solution / workaround.

Anyway, thanks for getting back and sorry for being the guy that follows not so popular path.

**Comment by gkalpak** [comment]
Yeah, documenting it would be nice. Unfortunately, the docs of `ngUpgradeLite` (which is the version of `ngUpgrade` that is affected by this) are still in a PR #18487 due to some AngularJS typings issues (which I haven't found time to fix yet; but it's on my list :grin:)

**Comment by gkalpak** [comment]
At this point, it is probably not worth implementing the configurability (as mentioned in https://github.com/angular/angular/issues/22648#issuecomment-372327673) due to low demand, but leaving this open as a low-priority request to improve the docs.

**Comment by FDIM** [comment]
@gkalpak I'm pretty sure you can close this request and focus on some other more important tasks. We have completed the upgrade like a 2 years ago 😁 Thanks for all the efforts on this upgrade path!
