### ISSUE TITLE
pass formGroup in child component

### ISSUE THREAD

**Issue by regedit15** [angular/angular#22653]
I want to make a child component that takes the formGroup and adds validations but I receive an error because the child component does not perceive that it is inside the parent's "form"

How could I solve this problem?

https://plnkr.co/edit/iyvemjyYAq6hY4jzHihu?p=preview

**Comment by alexeagle** [comment]
Do you think there's a bug in Angular, or is this a support request? We don't handle the latter on our issue tracker.

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
