### ISSUE TITLE
AsyncPipe doesn't resolve value when a BehaviourSubject is completed

### ISSUE THREAD

**Issue by NoNameProvided** [angular/angular#22650]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
When a subject is completed before the first render of the AsyncPipe it will never resolve anything. However if a regular observable is completed before the first render of the AsyncPipe it will be still rendered.

## Expected behavior
The AsyncPipe retain the last value of both regular observables and subjects when they are completed.

## Minimal reproduction of the problem with instructions
[https://stackblitz.com/edit/angular-asyncpipe-completed-issue](https://stackblitz.com/edit/angular-asyncpipe-completed-issue?file=app/app.component.ts)

## What is the motivation / use case for changing the behavior?

We compose some execution logic with `forkJoin` so we have to complete observables at the end, but we also want to use the `BehaviourSubject` in the template to show partial content when things are ready (`*ngIf="someService.ready | async"`)

## Environment

<pre><code>
Angular version: 5.2.8

Browser:
- [x] Chrome (desktop) version latest
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version latest
- [x] Safari (desktop) version latest
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v9.7.1
- Platform:  Mac

**Comment by sod** [comment]
If you complete a Subject/BehaviorSubject, it's set to `isClosed = true`

https://github.com/ReactiveX/rxjs/blob/master/src/internal/Subject.ts#L86

And if you done that, a subscription will never receive a value every again

https://github.com/ReactiveX/rxjs/blob/master/src/internal/Subject.ts#L116-L118

**Comment by NoNameProvided** [comment]
Thanks for the information, I didn't know Subjects behaves differently from Observables in this aspect.

For future users, an example:

```ts
const obs Observable<string[]> = new Observable(x => {
    x.next(['obs']);
    x.complete();
  })

const subj: BehaviorSubject<string[]> = new BehaviorSubject(['subj']);

subj.complete();

obs.subscribe(console.log, console.error, () => console.warn('Completed'));
subj.subscribe(console.log, console.error, () => console.warn('Completed'));

//  For the observable, it emits the last value (logs ["obs"]) and then logs "Complete"
// For the subject, it just completes, without emitting the last value.
```
