### ISSUE TITLE
IE11 Issue - Atleast take 10-20 seconds to type a single letter

### ISSUE THREAD

**Issue by shameej** [angular/angular#22651]
Hi All,

My application is working on Angula5 and when I type in a simple textbox in IE11 browser it is taking 10-20 seconds to appear even a single letter. Whereas if I try the same thing in chrome its working fine. Can you tell me what's going wrong in IE11.

Thanks,
Shameej

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by alexeagle** [comment]
Please include a repro and/or do some initial debugging in F12 tools to see if Angular is actually the slow thing.
