### ISSUE TITLE
Custom Date pipe does not work with getFullYear(), d.getMonth(), d.getDate() etc...

### ISSUE THREAD

**Issue by jacksylvane** [angular/angular#22664]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I am trying to make a custom date pipe in order to get a number of current week. I searched SO and found a good solution. Hovewer, that solution does not offer ISO week standard.  When searching further I found original answer suggesting using UTC date. You can find questions here:

[Angular solution - simple week](https://stackoverflow.com/questions/35474506/angular-2-date-pipe-weeknumber)

[Original vannila JS solution - ISO week](https://stackoverflow.com/questions/6117814/get-week-of-year-in-javascript-like-in-php)

Angular does not consider getFullYear(), d.getMonth(), d.getDate() as a functions and throws error.

## Expected behavior

d = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate())); should execute without error

## Minimal reproduction of the problem with instructions
 [DEMO on Stackblitz](https://stackblitz.com/edit/angular-yjejyq?file=app%2Fweek.pipe.ts)

## Environment

<pre><code>
Angular version:  5.2.7

Browser:
- [ XX ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ XX ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.5.0
- Platform:  Windows

</code></pre>

**Comment by trotyl** [comment]
`Date.now()` is not a date, but a number.
