### ISSUE TITLE
AIO + API: consider layout of enum pages

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#22678]
At the moment, the `enum` API pages are rendered using the same logic as the `class` API pages. 

<img width="1176" alt="screen shot 2018-03-09 at 13 23 56" src="https://user-images.githubusercontent.com/15655/37209473-5ffbeb2c-239d-11e8-8315-28b62ad5e6fc.png">

There may be room for improvement.  For instance

* Merge the overview with the properties table. They are mostly showing the same information in different ways.
* Rename the properties table to members, which is more in keeping with the terminology of enums

**Comment by petebacondarwin** [comment]
@jbogarthyde can you add your comments here.

**Comment by jbogarthyde** [comment]
Leave the overview - it's an index to the descriptions. Yes, rename the prop table to Members - and the column heading. The descriptions should be the `@description`  for each member.

**Comment by jbogarthyde** [comment]
I would keep the overview, and drop the "Type" column from the table. It's not the type, it's the enum value, and the point of naming the members is that people don't need to use the values (which could change).

Yes, they are members, not properties.

**Comment by petebacondarwin** [comment]
@jbogarthyde this was closed by another PR a couple of weeks ago: https://github.com/angular/angular/pull/23872.
You can see what it looks like now on the live site. E.g. https://angular.io/api/animations/AnimationMetadataType

I changed Properties to Members and Type to Value. I kept the value column but only if at least one value is specified. This is because, if a value has been specified in the code then it is possible that this actually has a some meaning outside the enum.
