### ISSUE TITLE
On the problem of modularized development of angular

### ISSUE THREAD

**Issue by einstein888** [angular/angular#22673]
You can look generous with your criticism if I had a A project, there are two functional modules of task management and system management of the project two. This module has its own service/model/component/module/routing. I want to publish to the NPM system management module, warehouse management module, then install the system I posted in the project B.Is the above approach feasible? How can I configure my routing information in AppModule if it is feasible?
This is my AppMoudle
![qq 20180309145026](https://user-images.githubusercontent.com/28614443/37194418-18966d5a-23a9-11e8-8447-49592b7da93a.png)
This is my tsconfig.json
![qq 20180309145057](https://user-images.githubusercontent.com/28614443/37194419-18caaf3e-23a9-11e8-953c-23e90ab7a3bf.png)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
