### ISSUE TITLE
Feature request: redirectTo should be as flexible as routerLink and Router#navigate

### ISSUE THREAD

**Issue by thorn0** [angular/angular#22679]
## I'm submitting a...

<pre><code>[x] Feature request</code></pre>

## Current behavior

The constraining inflexibility of `redirectTo` manifests itself especially distinctly when working with multiple outlets. E.g., using `redirectTo`, we can't
- redirect to `..` or to `../something` (without affecting other outlets),
- reload only the current outlet,
- reload only some other outlet(s).

All these use cases are perfectly possible with `routerLink` and `Router#navigate` though.

The workaround is ugly: using a guard just to call `navigate`. At that, it's not allowed to have a routing config entry with `path` and a guard only, so we also have to add a never used component there.

## Expected behavior & motivation

Consistency. Least astonishment. Compatibility. Related features of the framework should, expectedly, have similar API and abilities. `redirectTo` is essentially the same thing as the `routerLink` directive, the only difference is that the link is triggered by a different event (a URL change, not a click.)
</code></pre>

**Comment by jasonaden** [comment]
Thanks for the issue. I added as a feature request.

**Comment by dc-p8** [comment]
Very usefull feature request !

In addition, it would be nice if we could pass data when redirecting.
something like this :

```
path: 'parent',
children:[
	{
		path:'',
		component: ParentComponent
	},
	{
		path:':id',
		redirectTo:'/parent;id=:id',
		// or
		redirectTo:"['parent', {id:id}]",
		pathMatch:'full',

	}
]
```
I know this case is not very usefull because we can directly use ParentComponent, but we can imagine cases where it would be useful.

**Comment by atscott** [comment]
Closing due to lack of traction. In a perfect world with unlimited resources to implement everything that makes sense, I do agree that this is kind of inconvenient. That said, it is possible to do with a guard as you mentioned. For what it's worth, you can use an empty `children: []` array instead of an unused component to pass the validation.
