### ISSUE TITLE
CSS served as text/html

### ISSUE THREAD

**Issue by kvea2git** [angular/angular#22686]
#

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Running the app with ng serve and then opening the page in  localhost;4200 produces

<code>
Refused to apply style from 'http://localhost:4200/css/test.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
</code>

## Expected behavior
style sheet should load as text/css

## Minimal reproduction of the problem with instructions

 create a new default Angular app with "ng new"  and add a simple style sheet to it, or add a package that adds a style sheet, such as font-awesome, to the app in package-json and npm install.
Reference the style sheet in the default index.html. Attached zip  is the trivial app from ng new, less the node_modules directory

## What is the motivation / use case for changing the behavior?

This is trivial correct behavior that should work out  of the box.  The failure is trivially reproducible. The attached zip archive is the trivial test app, less the node_modules directory resulting from npm install.

## Environment
Angular 
<pre><code>
C:\A_VangNG2\testnew>ng --version
Angular CLI: 1.6.8
Node: 8.9.4
OS: win32 x64
Angular: 5.2.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router
[testcss.zip](https://github.com/angular/angular/files/1798101/testcss.zip)

@angular/cli: 1.6.8
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

C:\A_VangNG2\testnew>npm --version
5.6.0
</code>

Browser:
- [x] Chrome (desktop) Version 64.0.3282.186 (Official Build) (64-bit)

- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  
Windows 10 Pro

Others:

</code></pre>

**Comment by kvea2git** [comment]
The section on "reproducing the problem" did not come thru. The problem is trivially reproducible and the attached zip is the trivial app created with Angular CLI, less the node_modules directory. Create a new project with "ng new", and add a trivial style sheet, and/or add a package that adds a style sheet, such as font-awesome. Reference the css from the index.html. This produces the  above error. Thanks

**Comment by kvea2git** [comment]
[testcss.zip](https://github.com/angular/angular/files/1798160/testcss.zip)

**Comment by jotatoledo** [comment]
This is cli related, and it fairly well documented how you should add styles through the cli config

**Comment by kara** [comment]
Yeah, this looks like something that should be filed in https://github.com/angular/angular-cli.

**Comment by kvea2git** [comment]
What is documented? Including styles.css in .angular-cli.json and in referencing the styles in styles.css? They don't load when reffed in styles. I finally applied the  styles, by giving the absolute path in .angular-cli.json. This is from the real app I was working on

<code>
"styles": [
        "/a_vangng2/vanguardng/node_modules/font-awesome/css/font-awesome.min.css",  
        "/a_vangng2/vanguardng/node_modules/primeng/resources/primeng.min.css",
        "/a_vangng2/vanguardng/node_modules/primeng/resources/themes/omega/theme.css",
        "styles.css"
      ]
</code>

**Comment by jotatoledo** [comment]
https://github.com/angular/angular-cli/wiki/stories-global-styles

https://github.com/angular/angular-cli/wiki/stories include font awesome

**Comment by kvea2git** [comment]
I looked on the angular-cli wiki

https://github.com/angular/angular-cli/wiki/angular-cli

but missed the "stories". Such info should be more prominently documented.
