### ISSUE TITLE
ɵisPromise, ɵisObservable ???

### ISSUE THREAD

**Issue by Davilink** [angular/angular#22685]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

I was trying to use isPromise, isObservable, but each time the compiler was throwing exception, because i tried to use it from the @angular/core package (the auto-import of VSCode) : 
![image](https://user-images.githubusercontent.com/1498932/37222170-2c0034c0-239a-11e8-868d-f6e592e770ce.png)

if i remove the auto import and try to import manually (with the auto-discovery option of vscode), i get :

![image](https://user-images.githubusercontent.com/1498932/37222257-67925356-239a-11e8-8cbd-aea7d72ab8b5.png)

But when i use it, i get many error from the compiler : 
![image](https://user-images.githubusercontent.com/1498932/37222306-920988de-239a-11e8-8697-043041649b4c.png)

After looking around i found that the real import is : 

![image](https://user-images.githubusercontent.com/1498932/37222337-aa116618-239a-11e8-9aec-8b2a88b30064.png)

Is it normal ? Could it be a bad unicode that has been convert to the caracter « ɵ » ?

**Comment by kara** [comment]
Functions prefixed with ɵ are intended to be private/internal to the framework. This is intentional to help signal to users that these functions should not be called externally.
