### ISSUE TITLE
We want to post the UTC date time in API and display in local date time. 

### ISSUE THREAD

**Issue by kudeepak** [angular/angular#22695]
## We want to post the UTC date time in API and display in local date time.

<pre><code>
[ 1 ] Feature request
</code></pre>

## Environment

<pre><code>
Angular version: 4/5/6

Browser:
All Browser

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
