### ISSUE TITLE
no tests for disableTypeScriptVersionCheck angularCompilerOptions flag

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#22699]
This code path has no tests:

https://github.com/angular/angular/blob/fa451bcd19bcebfc3dca60265fea4f08beee1cde/packages/compiler-cli/src/transformers/program.ts#L76-L79

We should add them.

This would be a great issue for a community contribution.

**Comment by benbraou** [comment]
@IgorMinar I believe this issue can be closed now.
PR #22705 is merged in master now. It has added several tests, and among them tests for `disableTypeScriptVersionCheck` 

https://github.com/angular/angular/blob/a5f0939eae754adaa64cc613cac44dd528395529/packages/compiler-cli/test/transformers/program_spec.ts#L1052-L1080

**Comment by pkozlowski-opensource** [comment]
Sounds like it was fixed: https://github.com/angular/angular/issues/22699#issuecomment-377576834
