### ISSUE TITLE
Allow disabling a routerLink

### ISSUE THREAD

**Issue by Airblader** [angular/angular#22698]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently, there is no good way to disable a `routerLink` conditionally. This causes [clunky solutions](https://stackoverflow.com/questions/36985112/angular2-what-is-the-correct-way-to-disable-an-anchor-element) in the community.

## Expected behavior
There should be something like `routerLinkDisabled` which can be used to easily disable a router link from working, e.g.:

```
<button *ngFor="let item of items" 
        [routerLink]="['items', item.id]" 
        [routerLinkDisabled]="!item.enabled">
  {{ item.name }}
</button>
```

I would expect this to take care of removing the `href` altogether since only then it'll work properly for mouse and keyboard navigation; it will also be better for accessibility.

## What is the motivation / use case for changing the behavior?
There are several motivating usecases. For example, rendering a list of links (which may also be buttons etc.), but disabling their link based on permissions, validation state and such.

It should also be noted that [anchors without href are perfectly valid markup](https://stackoverflow.com/questions/5292343/is-an-anchor-tag-without-the-href-attribute-safe).

**Comment by lucasctd** [comment]
Have you found a solution for this?
If any of my routerLink has a null value, it will show the current page url in the href (which is a valid uri). I don't wanna this. I want to be able to set something like `href="javascript:"`.
I tried to use only href, but if I do it I will be able to use routerLinkActive feature ?:v

**Comment by pauldraper** [comment]
@Airblader why was this closed?
