### ISSUE TITLE
Daxie & Angular : Wait until populating DB

### ISSUE THREAD

**Issue by CMFPRO** [angular/angular#22708]
i have a service PhoneService calling (in the constructor) a remote API to get data and populate DB, the AppComponent use the PhoneService (ngOnInit) to get data from the table.
in the first page load i have no data (it's normal because AppComponent call function to get data before the PhoneService populate DB)

my question is : how can i tell my PhoneService to wait unit pupulation ending and then fetch the table to get data ?

thank you

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
