### ISSUE TITLE
use Angular 5.2.8 How to get the downloaded file name, which is not the same as Angular 4

### ISSUE THREAD

**Issue by chenwuwen** [angular/angular#22703]
I use the angular version is 5.28, now the situation is that I want to download the file server request, I set up the ResponseType Blob before Angular 4, the server returns a Response object which contains a lot of information, I can get the Blob object and the name of the file from which now use Angular5, the Blob object is directly received that can't get file name, how can I do, in order to obtain the file name, thank you

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mikeandersun** [comment]
@chenwuwen  Please chek in with 5.2.7 , I think there is a problem in 5.2.8 and 6.0.0-beta.7  .
https://github.com/IdentityModel/oidc-client-js/issues/520 maybe related to this.

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Comment by cecotw** [comment]
I am getting this same issue. I went from 5.0.2 to 5.2.8 and our oidc-client started to fail to grab the state from the redirect response. Downgrading to 5.2.7 fixed the issue.

**Comment by stefandroog** [comment]
Maybe you van use:
`this.http.get('…', { observe: 'response' });`

This will return the response (with the Blob and Content-Disposition header) and not only the body.

**Comment by lfdajr** [comment]
See https://angular.io/guide/http#reading-the-full-response
