### ISSUE TITLE
client certificate authentication not working on iOS when using angular http service

### ISSUE THREAD

**Issue by shahul-basha** [angular/angular#22707]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
My server mandates client certificate authentication for any communication with the server. Hence angular http is used to perform the post. 
Am using the Cordova Client Certificate Plugin (https://github.com/agenceaddictic/cordova-plugin-client-certificate-addictic.git) for registering the client certificates.

While the certificates are actually passed when using android, the same behavior is not seen on iOS.

From the backend, it is observed, that though the certificates are registered, it is presenting a certificate that the server is not able to accept. In case of android, the server is getting the correct certificate.

**Expected / new behavior:**
Client cert authentication should happen when the connection is made from the iOS device to the back end server.

**Minimal reproduction of the problem with instructions:**

The certificate is registered as below:

    var success = function (message) {
      console.log("success in client cert registration: " + message);
    }

    var failure = function (error) {
      console.log("error in client cert registration " + error);
    }

    clientCertificate.register("www/sample.p12", "s3cr3t123", success, failure);

Then the http post is performed as below:

           http.post(url, message, options).subscribe((data: any) => {
              console.log("data : " + JSON.stringify(data));

              )
              console.log(data.status);
              console.log(data.data); // data received by server
              console.log(data.headers);

            }, error => {

              console.log("error : " + JSON.stringify(error));

              console.log(JSON.stringify(error));
              console.log(error._body); // error message as string
              console.log(error.headers);
            }); //end of POST promise

When tried to debug in xcode, it is observed that the customHTTPProtocol that is registered as a delegate for the URL connections is not getting used at all when the http post is fired.

Following is the logs at xcode when the post is made:

error : Response with status: 0  for URL: null, string : {"_body":{"isTrusted":true},"status":0,"ok":false,"statusText":"","headers":{},"type":3,"url":null}

Versions used:
"ionic-angular": "3.9.2"
"@angular/common": "5.0.3",
    "@angular/compiler": "5.0.3",
    "@angular/compiler-cli": "5.0.3",
    "@angular/core": "5.0.3",
    "@angular/forms": "5.0.3",
    "@angular/http": "5.0.3",

**Comment by shahul-basha** [comment]
Appreciate any updates on the issue reported?

**Comment by alxhub** [comment]
Hi @shahul-basha,

Please provide a full reproduction (cloneable repository with a certificate setup, etc) in which the problem is visible. It's very likely that the bug here is in Cordova and not Angular, and without a proper setup it's impossible to test this scenario.

**Comment by pkozlowski-opensource** [comment]
We've deprecated and removed `http` so this issue is no longer relevant.
