### ISSUE TITLE
How to Record an angular 2 application

### ISSUE THREAD

**Issue by vibingopal** [angular/angular#22706]
[ x] Feature request
[ ] Documentation issue or request
[x ] Support request => Please do not submit support request here, instead see 
## Current behavior
Hello Team,

I have a requirement where i can record the angular 2 application from browser . I saw examples on recordRtc but it won't supports recording the application in the browser. Are there any dependencies available in the market to implement this feature? 

## Expected behavior

Need to record the application when the user clicks on particular action item(for example button).So that user can record the tasks by running the applicaion in the browser and can save the recorded video.(For saving- we can implement using backend.But now recording through front end have no implementations) later reportees can view the recorded angular application and can take necessary action .

## Environment

<pre><code>
Angular version: 5.0.1

Browser:
- [x ] Chrome (desktop) version XX
- [x ] Chrome (Android) version XX
- [ x] Chrome (iOS) version XX
- [x ] Firefox version XX
- [x ] Safari (desktop) version XX
- [x ] Safari (iOS) version XX
- [ x] IE version XX
- [ x] Edge version XX
 
For Tooling issues:
- Node version: 6.10.1
- Platform:  Windows

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
