### ISSUE TITLE
Exception in BrowserPlatformLocation on IE in mobile window

### ISSUE THREAD

**Issue by AKlaus** [angular/angular#22709]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When an Angular app is open in a modal IE window, it throws the following exception:
> EXCEPTION: Uncaught (in promise): Error: Unspecified error.
> Error: Unspecified error.
> at BrowserPlatformLocation.prototype.replaceState (./vendor.bundle.js)
> at PathLocationStrategy.prototype.replaceState (./vendor.bundle.js)
> at Location.prototype.replaceState (./vendor.bundle.js)
> at Router.prototype.resetUrlToCurrentUrlTree (./vendor.bundle.js)
> at Router.prototype.resetStateAndUrl (./vendor.bundle.js)
> at Anonymous function (./vendor.bundle.js)
> at ZoneDelegate.prototype.invoke (./polyfills.bundle.js)
> at onInvoke (./vendor.bundle.js)
> at ZoneDelegate.prototype.invoke (./polyfills.bundle.js)
> at ZoneDelegate.prototype.run (./polyfills.bundle.js)

After looking in the code, I found that all the exceptions are caused by manipulations with the History object (e.g. `history.replaceState`).

The modal Internet Explorer window can be open in one of the following ways:
- JavaScript method: `window.showModalDialog()`
- In a traditional windows app (e.g. WinForms) create a mobile dialogue window with an instance of  the WebBrowser ActiveX control, which runs IE under the hood.
- MS Office open the authentication page in a modal window for files opened via [WebDAV protocol](https://en.wikipedia.org/wiki/WebDAV).

## Expected behavior

No exception should be thrown.

## Minimal reproduction of the problem with instructions

Please check out [this demo on stackblitz](https://stackblitz.com/edit/angular-qurvft).

## What is the motivation / use case for changing the behavior?

When MS Office products open a file for editing from a website, which require authentication, they show the login page in a modal window. So if the login page is done in Angular, the user is experiencing the issue described above.

## Additional information
While I was fiddling with the problem I create a simple example with vanilla JavaScript, which behaves in a similar way. Check out [this plunkr](http://plnkr.co/edit/ys1EoFQEWAYSAcLUa8UL?p=preview).

## Workaround
Adding the following line in the `index.html` of the Angular app helps to avoid throwing the exception.
`window.history.replaceState = function (){ console.log('Empty stub for history.replaceState()') };`

## Environment

<pre><code>
Angular version: 5.2.

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE any version
- [ ] Edge version XX

**Comment by robwormald** [comment]
As far as I'm aware, this feature is deprecated on the Web Platform (per https://developer.microsoft.com/en-us/microsoft-edge/platform/status/showmodaldialog/?q=modaldialog) - so I doubt we'd treat this as a bug, per se. See Chromium's rationale here: https://developer.microsoft.com/en-us/microsoft-edge/platform/status/showmodaldialog/?q=modaldialog

I suspect (?) that the history API just isn't available here, hence it exploding. Angular, by default, uses the `PathLocationStrategy` (which relies on the history API). You could use the `HashLocationStrategy`, which does not rely on the history API, or if this is *only* for a login page, implement something like the `MockLocationStrategy` we use in tests. See https://angular.io/guide/router#appendix-locationstrategy-and-browser-url-styles for some more details.

**Comment by AKlaus** [comment]
@robwormald, I used the ` showModalDialog()` method just as a simple example of having an instance of IE in a modal dialogue window. As I said the problem can be easily reproduced on Windows by running an instance of the _WebBrowser ActiveX control_ (which runs IE under the hood) in a modal dialogue window (I mean the window created in a windows app, I can provide an example in WinForms).

## The MS Office problem
My actual problem was with opening a _.doc_ file in _MS Office_ from a website, which requires authentication and where the login page is an Angular app. In this case:

1. The user opens the website in ANY browser.
1. The user clicks on a Word file link (which has the [Office URI Schema](https://msdn.microsoft.com/en-us/library/office/dn906146.aspx)).
1. If a MS Word is installed on the computer, it will process the link and will attempt to open the file.
1. If the website requires authentication (implements [MS OFBA](https://msdn.microsoft.com/en-us/library/cc313069.aspx)), then MS Word will show a **modal dialogue window** with the login page from the specified authentication website.
1. As our login page is an Angular app and MS Office shows the page in a **modal dialogue window** we see the bug described above.

## Suggested solution
Thank you, @robwormald, for suggesting `HashLocationStrategy` and `MockLocationStrategy`, I'll give it a try. But would it be possible for the Angular team to consider using a polyfill in cases when the history object is not available?

**Comment by robwormald** [comment]
> But would it be possible for the Angular team to consider using a polyfill in cases when the history object is not available?

That's what HashLocationStrategy is :) More accurately, you should use the HashLocationStrategy when the history API is unacceptable for whatever reason.

We don't bake in polyfills (because the vast majority of the world doesn't have this problem) - that would add unnecessary page weight to consumers who do not need the polyfills. See https://github.com/browserstate/history.js/ for a polyfill for the history API (again, we do not own/support this polyfill) that you can try.

**Comment by sylvainpolletvillard** [comment]
A client has the same issue when opening our Angular app from a MS Excel macro, but we already use the HashLocationStrategy:
![image](https://user-images.githubusercontent.com/566536/37513805-65820720-2906-11e8-8c28-f27c4afb6841.png)

The error only happens when opening the app from MS Office. It works fine if I use a simple HTML form that redirects to the app.

**Comment by AKlaus** [comment]
@sylvainpolletvillard, was the workaround (in my post above) with stubbing `history.replaceState` or `history.pushState` of any help?

**Comment by sylvainpolletvillard** [comment]
@AKlaus yes, it solved this particular issue but this is not a satisfying solution as we are relying on HTML5 history for other purposes. We finally decided to not support loading the app from a MS Office document link. 

I implemented your workaround this way :
```
var isIE = /*@cc_on!@*/false || !!document.documentMode; // Internet Explorer 6-11
if(isIE){
	// force Angular BrowserPlatformLocation supportsState() to return false
	// see https://github.com/angular/angular/issues/22709
	window.history.pushState = undefined;
}
```

**Comment by prad9** [comment]
@sylvainpolletvillard  Thanks for the workaround. It works for me too.
