### ISSUE TITLE
Ability to ask angular for a copy of the 'current' app environment for consumption in non-injectable places

### ISSUE THREAD

**Issue by un33k** [angular/angular#22718]
```
[ x] Feature request
```
## Current behavior

1. A module that is internal to the app's project directory. works as expected.

```typescript
import { environment } from './environment/environment'
```

2. A module that is NOT internal to the app's project directory. works as expected.

```typescript
// app.module.ts
import { environment } from './environment/environment'

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    XyzModule.forRoot(environment)
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}
```
```typescript
 // xyz.module.ts (external module)
 static forRoot(config?: AppEnv): ModuleWithProviders {
    return {
      ngModule: CfgModule,
      providers: [{ provide: AppEnv, useValue: config }, XyzService]
    };
  }
```
```typescript
// xyz.serivce.ts
@Injectable()
export class XyzService {
  constructor(@Optional() private options: AppEnv) {}
}
```

## Expected behavior
3. An external module that provides services to three apps that require different localStorage engines.

- Web (Browser - localStorage)
- Mobile(NativeScript - customStorage)
- Desktop(Browser - localStorage)

```
// Layout
targets/web/app/environment/environment.ts ({storageEngine: window.localStorage})
targets/mobile/app/environment/environment.ts ({storageEngine: customStorage})
targets/deskto/app/environment/environment.ts ({storageEngine: window.localStorage})

libs/xyz/src/xyz.reducer.ts
```

```typescript
// xyz.ngrx.reducer.ts
import {envLoader} from '@angular/common'; // if possible
const appEnv = envLoader();

export function rehydrateMetaReducer(reducer: (state: State, action: Actions) => any) {
  return function(state, action) {
      const persistedState = appEnv.storageEngine.getItem('xyz');
      return persistedState? JSON.parse(persistedState): reducer(state, action);
  };
}
```
```typescript
import {rehydrateMetaReducer} from './xyz.ngrx.reducer.ts';
@NgModule({
  imports: [
    StoreModule.forFeature('xyz', reducer, { metaReducers: [rehydrateMetaReducer] }),
  ],
  ...
}
```

## Minimal reproduction of the problem with instructions
Unable to get to the app `environment` in an external module

## What is the motivation/use case for changing the behavior?
Any file within angular's scope should be able to consume the `environment`.  This may be the chicken & the egg problem for any app and any external modules.  Both the app and the module have angular in common. So, it would be great to ask angular for a copy of the environment. At any stage of the bootstrap and execution.

## Environment

<pre><code>
Angular CLI: 6.0.0-beta.4
Node: 9.6.1
OS: darwin x64
Angular: 6.0.0-beta.7
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

@angular/animation: 4.0.0-beta.8
@angular/animations: 5.2.8
@angular/cdk: 6.0.0-beta.4
@angular/cli: 6.0.0-beta.4
@angular/flex-layout: 5.0.0-beta.13
@angular/material: 6.0.0-beta.4
@angular-devkit/build-optimizer: 0.4.3
@angular-devkit/core: 0.4.3
@angular-devkit/schematics: 0.4.3
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 6.0.0-beta.4
@schematics/angular: 0.4.3
@schematics/package-update: 0.4.3
typescript: 2.6.2
webpack: 4.0.1

Browser:
- [x ] Chrome (desktop)

For Tooling issues:
- Node version: 9.6.1
- Platform:  Mac

Others:
Wonder  if angular cli can help with this.
</code></pre>

**Comment by trotyl** [comment]
There's nothing like `environment` in Angular, it's only an [Angular CLI](https://github.com/angular/angular-cli) conversion file.

**Comment by un33k** [comment]
Dear @angular-robot - three years waiting is a long time ...... so, I am closing it.
