### ISSUE TITLE
service worker not working

### ISSUE THREAD

**Issue by ylandau** [angular/angular#22725]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
</code></pre>

## Current behavior
see url: https://dist-damzzkdcrp.now.sh/
service worker is registered,
but when putting browser offline in dev tools it doesn't reload,

## Minimal reproduction of the problem with instructions
ng new test-service-worker --service-worker
cd test-service-worker
ng build --prod
cd dist
upload to any cloud provider

## Environment

<pre><code>
Angular version: 5.2.8

Browser:
- [x] Chrome (desktop) version 65
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kara** [comment]
This looks like it should be filed in the CLI repo.
