### ISSUE TITLE
CORS issue in Angular 2 by using Node

### ISSUE THREAD

**Issue by subodh6580** [angular/angular#22729]
import { Injectable } from '@angular/core';
import { Http , Response,RequestOptions } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/do';

import { Headers } from '@angular/http';

@Injectable()
export class ProductService {

    constructor (private _http:Http ) {}

    getCurrentTime(){
            let headers = new Headers();
        headers.append('Client-Service','Reculta-client');
        headers.append('Auth-key','X9##reculta');
    
    let options = new RequestOptions({ headers: headers });
    
        return this._http.get('http://13.126.187.50/reculta2/index.php/api/get_company_post?company_id=4&user_id=433',options)
        .map(res => res.json());
    }
    postJSON(){
        var json = JSON.stringify({ username: '1234567893', password: 1234 });
        var params = 'json=' + json;
        var headers = new Headers();

         headers.append('Client-Service','Reculta-client');
         headers.append('Auth-key','X9##reculta');
           
        return this._http.post('http://13.126.187.50/reculta2/api/login', params,{
            headers: headers
        }) 
        .map(res => res.json());
    }
}

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by subodh6580** [comment]
thank you..!
