### ISSUE TITLE
HttpClient POST using request() method error on Firefox: event is not defined

### ISSUE THREAD

**Issue by funkizer** [angular/angular#22730]
## I'm submitting a...

<pre><code>
[ x ] Bug report 
</code></pre>

## Current behavior
In Firefox, trying to upload FormData using HttpClient.request() instead of .post() causes `event is not defined`. I just moved to using .request() because I want to track the upload progress, and everything was working previously.

The error occurs before request is sent, ie. nothing in the network tab.

## Expected behavior
Should work as it does in Chrome, Edge and IE11.

## Minimal reproduction of the problem with instructions
Open [this StackBlitz](https://stackblitz.com/edit/angular-7bagc2?file=app/app.component.ts) in Firefox, select a file with the input, see error in console. 

On Chrome, you should see 403 as expected. On FF, you should see `event is undefined` and a stack trace pointing to a weird line number in `common/esm5/http.js`.

Hacked a bit into http.js and added logging to both places where I could find the name `event`, which is in `onUpProgress()` and `onDownProgress()` and neither one of these gets ever called on FF, so I can't figure out where this `event` even is.

## Environment

<pre><code>
Angular version: 5.2.8

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x ] Firefox version 58.0.2
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
- Platform:  Windows
</code></pre>

## Other
[StackOverflow question](https://stackoverflow.com/questions/49253383/httpclient-post-using-request-method-error-on-firefox-event-is-not-defined)

**Comment by funkizer** [comment]
Made a simplified blitz to rule out as much as possible, sending File instead of FormData like in the [guides example](https://angular.io/guide/http#listening-to-progress-events). Result was the same:
https://stackblitz.com/edit/angular-7bagc2?file=app/app.component.ts

**Comment by funkizer** [comment]
Ehh hmm.. the problem was I `return event` in the map call, instead of `e`. There is no `event`. Weird that the compiler and other browsers let that slip! Sorry about this! Closing. Working blitz: https://stackblitz.com/edit/angular-rptitf?file=app/app.component.ts

**Comment by trotyl** [comment]
For tracking: https://github.com/Microsoft/TypeScript/issues/18433

**Comment by funkizer** [comment]
Oh, `event` is declared in lib.dom.d.ts. Very enlightening read, thanks @trotyl !
