### ISSUE TITLE
downgraded component: not possible to have two-way binding and change event on the same output / emitter

### ISSUE THREAD

**Issue by FDIM** [angular/angular#22734]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

It seems that it is not possible to have 2-way-binding and listen to the same change event when angular 5 component is downgraded.

## Expected behavior

Two way binding should work and the provided expression (if any) should be evaluated.

## Minimal reproduction of the problem with instructions

- open https://stackblitz.com/edit/ngupgradestatic-playground-o2xraa?file=index.html
-  click the first increment button and observe that only the value from event changes even though there is two-way binding to value property
- clicking second increment button only updates counter as there is no additional binding to countChange output (all good)
- after clicking 3rd button you can see that both values update (all good)

## What is the motivation / use case for changing the behavior?

To keep downgraded component behavior similar to normal usage in other angular 5 component

## Environment

<pre><code>
Angular version: 5.2.x

Browser: any

</code></pre>

**Comment by gkalpak** [comment]
This is a valid issue. It happens, because of the `if else`s we have [here][1], which only allow one form of the output binding and ignore the rest. Instead, we should collect all output bindings.

@FDIM, would you be interested in working on this?

[1]: https://github.com/angular/angular/blob/bd9d4df7354591eb039249f14ab180f6b60ddf70/packages/upgrade/src/common/downgrade_component_adapter.ts#L178-L188

**Comment by FDIM** [comment]
@gkalpak I am :) I'll try come up with a fix in our local copy of the library (due to another issue) and I'll prepare a PR after that. So hopefully some time this week.

**Comment by gkalpak** [comment]
From a quick look, the fix looks good 👍 (Make sure to include some tests on the PR :wink:)
Feel free to ping me if you get stack.

**Comment by FDIM** [comment]
After fiddling with some white space (linter is very picky!) - I think the PR is ready.

I also updated existing test case and seen it break without my changes and pass with the fix.

**Comment by gkalpak** [comment]
Thx! I'll take a look shortly.
(Pro tip: `gulp format` fixes linting issues :wink:)
