### ISSUE TITLE
Feature: asterisk syntax sugar without structural directive to define template

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#22743]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
To define template one must use `<ng-template>` element:
```html
<ng-template #hello>
  <div>Hello world!</div>
<ng-template>
```

## Expected behavior
A syntax sugar for simple template with one inner element that works in similar fashion to * with structural directives:
```html
<div *#hello>Hello world!</div>
```
This syntax is just a proposition. Other suggestion:
```html
<div *ngTemplate="hello">Hello world!</div>
```

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?
It would work fine with ngIf's else. Let's consider this example:
```html
<div class="row">
	<span>First</span>
</div>
<div class="row" *ngIf="condition; else elseRef">
	<span>Something</span>
</div>
<ng-template #elseRef>
	<div class="row">
		<span>Something else</span>
	</div>
</ng-template>
<div class="row">
	<span>Last</span>
</div>
```
Corresponding elements in different rows have different indentation. It looks weird and mismatched. At first glance one could think there's mistake somewhere. Also, if you add extra indentation to existing code VCS will report changes in every line.
Of course you can use ngIf on  `<ng-contarner>`, but other elements still have different indentation and it requires extra boilerplate code:
```html
<div class="row">
	<span>First</span>
</div>
<ng-container *ngIf="condition; else elseRef">
	<div class="row">
		<span>Something</span>
	</div>
</ng-container>
<ng-template #elseRef>
	<div class="row">
		<span>Something else</span>
	</div>
</ng-template>
<div class="row">
	<span>Last</span>
</div>
```
With new syntax it could look like this:
```html
<div class="row">
	<span>First</span>
</div>
<div class="row" *ngIf="condition; else elseRef">
	<span>Something</span>
</div>
<div class="row" *#elseRef>
	<span>Something else</span>
</div>
<div class="row">
	<span>Last</span>
</div>
```

**Comment by pkozlowski-opensource** [comment]
I think that it becomes less confusing if you use the full `<ng-template>` syntax:

```html
<div class="row">
	<span>First</span>
</div>
<ng-template [ngIf]="condition" [ngIfElse]="elseRef">
    <div class="row">
	  <span>Something</span>
    </div>
</ng-template>
<ng-template #elseRef>
	<div class="row">
		<span>Something else</span>
	</div>
</ng-template>
<div class="row">
	<span>Last</span>
</div>
```

Not saying it is straightforward / pretty but at this point I'm not sure if drawbacks justify new syntax (IMO people are having enough of the hard time already when it comes to `*`).

**Comment by dawidgarus** [comment]
There are other potential uses of new syntax:
```html
<div *myDirective *#ref="myDirective"></div>
```
desugar:
```html
<ng-template myDirective #ref="myDirective">
  <div></div>
</ng-template>
```
It would add this requested feature: https://github.com/angular/angular/issues/11189

**Comment by pkozlowski-opensource** [comment]
> There are other potential uses of new syntax:
>`<div *myDirective *#ref="myDirective"></div>`

@dawidgarus when I'm reading this and seeing `*` 2 times it is not clear if `<ng-template>` would be created once or 2 times. 

> It would add this requested feature: #11189

Hmm, the way I'm reading  #11189 it was rather misunderstanding than a feature request...

Again, I'm totally with you and I totally acknowledge that syntax to express conditional if / else _can_ get painful. I just don't believe that the proposal put forward makes it any better - I don't think we want to add more `*` related sugar at this point - what we've got can be confusing already.

I'm going to close this for now based on the above, happy to continue the discussion though.
