### ISSUE TITLE
Improve "barrel" error to include more information

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#22749]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior

The current error emitted for a barrel error message does not include the `debugInfo` provided in the parameter to `_getProviderMetadata` that could be extremely helpful to debugging the issue as the current text does not provide a clue as to what provider is causing the problem.

https://github.com/angular/angular/blob/bd9d4df7354591eb039249f14ab180f6b60ddf70/packages/compiler/src/metadata_resolver.ts#L975,

## Expected behavior

The error message to include more contextual information.

**Comment by JoostK** [comment]
Closing as the metadata system is no longer used in Ivy.
