### ISSUE TITLE
Static reflector: Calling static method breaks AOT build

### ISSUE THREAD

**Issue by halilibrahim** [angular/angular#22757]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If I've understood correctly, according to [this closed issue](https://github.com/angular/angular/issues/10266) and [this merged pr](https://github.com/angular/angular/pull/10289) we should be able to call static methods in imports section of NgModule.
Calling static method as below breaks AOT build with "Function calls are not supported in decorators" message.
```ts
@NgModule({
  imports: [
    AppGenericModule.forChild({
      moduleTitle: 'Sample 1',
      config: {
        sampleParameter: 'sample parameter'
      }
    })
  ]
})
export class AppSample1Module {}
```

## Expected behavior

Successful build with AOT.

## Minimal reproduction of the problem with instructions

[Minimal demo repo](https://github.com/halilibrahim/ng-static-reflector-issue)

## What is the motivation / use case for changing the behavior?

I'm developing an application with many similar (data listing and manipulation) modules. I want to set a configuration object (which contains module specific information such as module title, menu item for app navigation, database entity metadata, i18n strings, etc...) to custom AppGenericModule and let it handle NgModule configuration.

In my scenario a generic module should prepare a data listing component (which has a paging grid list and add/edit/delete buttons), a data editing form component (which renders it's fields according to given form configuration), load i18n strings and add new module to app navigation.

I also have tried to solve with below methods:

```ts
// Not working because static reflector ignores custom decorators
@AppGenericModule(moduleConfig)
class SampleModule{}
```
> Is it possible to register custom decorators to reflector from app?
> https://github.com/angular/angular/blob/2a236b40666c1714cee35efc42bb059761a24a40/packages/compiler/src/aot/static_reflector.ts#L372-L373

```ts
// Also not working because compiler reflector ignores custom decorators 
// (even if they set proper NgModule annotations metadata to SampleModule class)
@NgModule({})
@AppGenericModule(moduleConfig) 
class SampleModule{}
```

```ts
// Can't do this because "function calls in decorators are not allowed" error
@NgModule( AppGenericModule(moduleConfig) )
class SampleModule{}
```

Finally I've found [this closed issue](https://github.com/angular/angular/issues/10266) but couldn't make a successful AOT build.

## Environment

<pre><code>
Angular version: 5.2.8

 
For Tooling issues:
- Node version: v7.10.1
- Platform:  Ubuntu 16.04
</code></pre>

**Comment by kemsky** [comment]
From my experience "Function calls are not supported in decorators"  message is quite misleading,  angular supports small subset of functions (functions that it can analyze statically). See https://angular.io/guide/aot-compiler#metadata-restrictions.

**Comment by robwormald** [comment]
Calling static methods is allowed, but what you're doing in https://github.com/halilibrahim/ng-static-reflector-issue/blob/master/src/app/generic/generic.module.ts is absolutely not going to work. We're looking to enable this kind of functionality in future versions, but attempting to declare modules / components / etc this way is not supported.
