### ISSUE TITLE
Error compil

### ISSUE THREAD

**Issue by Bary92** [angular/angular#22753]
**Hi** ,

I have a problem with angular5 . I have a services file that is used to retrieve data via an API. here is the code.
_data.services.ts_
```
import { Injectable } from '@angular/core';
import { HttpClient , HttpHeaders, HttpRequest } from '@angular/common/http';

@Injectable()
export class DataService {

	baseURL: 'path_to_api';

  constructor(private http: HttpClient) { 
  	let header: HttpHeaders();
  	header.set('Content-Type', 'application/json')
  		  .set('authorization', 'Bearer ' + 'token');
  }
  get_all(){
  	return this.http.get(
  		this.baseURL+'/ressource'
  	).subscribe(data => {
      console.log(data);
    });
  }
}
```
and here is the error:
****ERROR in src/app/services/data.service.ts(10,27): error TS1005: '=' expected.
src/app/services/data.service.ts(10,28): error TS1109: Expression expected.**

can you help me? 
thank you

**Comment by jotatoledo** [comment]
If you read the error maybe you could get an idea of what is going on.

**Comment by Bary92** [comment]
It's OK
