### ISSUE TITLE
Error on run-time when modul's component is referenced in route-config through a canActive-provider (that it should be added to the entry-components)

### ISSUE THREAD

**Issue by maks187** [angular/angular#22758]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Component of module referenced in routing definition in routing-module of the module itself is not found when it should be re-routed from a canActivate provider, who should replace the routing-config of the module. The module itself is lazy-loaded.

## Expected behavior

The module does declare the component already. And when the same routing is done without the canActivate provider, it works as expected.

## Minimal reproduction of the problem with instructions

Route-config's 'login'-route should be added dynamically though the canActivate RouteLoader:

```
export const routes: Routes = [
  { path: 'login', component: FrameComponent, 
    children: [
      { path: '', loadChildren: 'path_to_module/login.module#LoginModule' },
    ]
  },
  { path: '',  redirectTo: 'login', pathMatch: 'full' },
];
```
So putting the 'login'-route to an own route-struct:

```
export const DynamicRoutes = [
  { path: 'login', component: FrameComponent, 
    children: [
      { path: '', loadChildren: 'path_to_module/login.module#LoginModule' },
    ]
  },
];
```
And define the canActivate RouteLoader which should re-configurate the routing-config:
```
@Injectable()
export class RouteLoader implements CanActivate {
  constructor(public router: Router) {}
  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): boolean {
    const routerConfig: Routes = this.router.config;
    routerConfig.splice(routerConfig.length - 1, 0, ...DynamicRoutes);
    this.router.resetConfig(routerConfig);
    this.router.navigateByUrl('/login');
    return true;
  }
}
```
Then remove the now dynamically added route from the entry route config and adding the canActivate to the entry route, so it looks like this:
```
export const routes: Routes = [
  { path: '', canActivate: [ RouteLoader ], component: FrameComponent },
];
```
But then I get the following error:
```
zone.js:672 Unhandled Promise rejection: No component factory found for FrameComponent. Did you add it to @NgModule.entryComponents? ; Zone: angular ; Task: Promise.then ; Value: Error: No component factory found for FrameComponent. Did you add it to @NgModule.entryComponents?
```
If I put a log into the canActive provider to log the router-config, then I can see that the route was also been added to the routing-config:
```
{path: "", resolve: {…}, loadChildren: "path-to-module/container.module#ContainerModule", _loadedConfig: LoadedRouterConfig}
1:{path: "login", component: ƒ}
2:{path: "**", redirectTo: "failAndError"}
```

## What is the motivation / use case for changing the behavior?

Route-config's single-route should be added dynamically though an canActivate provider.
Route-config is part of a lazy-loaded module. Should be able to load other modules lazy through a modifyable route-config which can be set in an service, which is provided from the app-root.

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

<hr>

We would need a much cleaner reproduction on this one. It sounds like something that should be posted to StackOverflow, but tough to tell without a running example of the problem. You can use [StackBlitz](https://stackblitz.com) to create the reproduction.
