### ISSUE TITLE
component loaded by ngComponentOutlet not attached to DOM in ngOnInit

### ISSUE THREAD

**Issue by timbell** [angular/angular#22767]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
A component loaded by ngComponentOutlet is not attached to the DOM in ngOnInit if the surrounding component has a structural directive.

## Expected behavior
A component loaded by ngComponentOutlet should reliably be attached to the DOM in ngOnInit.

## Minimal reproduction of the problem with instructions

See this [stackblitz](https://stackblitz.com/edit/angular-dhg9eo?file=app%2Fcontent.component.ts). Click on the "Toggle components" button to show the test component in a variety of contexts. It is not attached to the DOM in the last case where it is loaded via ngComponentOutlet and the surrounding component has a structural directive.

## What is the motivation / use case for changing the behavior?

I came across the issue trying to integrate a charting module in to my application. I am loading the charts dynamically and they were not rendering correctly as the charting module uses getBoundingClientRect to get the view dimensions and in this case the chart was not yet attached to the DOM so the dimensions were 0. The stackblitz example is a reduction of this situation.

## Environment

<pre><code>
Angular version: 5.0.0-5.2.8

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dylhunn** [comment]
Likely different in Ivy. Please re-open with a repro if this is still an issue in 14.
