### ISSUE TITLE
Language service reports errors at the wrong position when using CRLF

### ISSUE THREAD

**Issue by Goobles** [angular/angular#22764]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Language service reports errors at the wrong positions when using CRLF file line endings in inline templates.

![image](https://user-images.githubusercontent.com/8776771/37404481-46a564c0-2792-11e8-860a-4603fdb99a96.png)

## Expected behavior

The correct positions should be used

## Minimal reproduction of the problem with instructions

Use the vscode extension Angular Language Service on Windows and open any project file.
Change the End of Line Sequence to CRLF.

## Environment

<pre><code>
VSCode version: 1.21.0
Angular language service plugin version: 0.1.9

Angular CLI: 1.6.8
Node: 8.9.1
OS: win32 x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.6.8
@angular/language-service: 5.2.8
@angular-devkit/core: 0.4.2
@angular-devkit/schematics: 0.4.2
@ngtools/json-schema: 1.1.0
@schematics/angular: 0.4.2
typescript: 2.6.2
webpack: 3.10.0
</code></pre>

**Comment by kyliau** [comment]
This was already fixed in https://github.com/angular/angular/pull/34737
