### ISSUE TITLE
Changes to properties expression does not trigger OnChange/set method on property change

### ISSUE THREAD

**Issue by ibhi** [angular/angular#2277]
I have a Directive called `validation` with a property also named `validation`.  I am assigning the property `validation` an expression(`[validation]="input.value"`) which evaluates to the value of the input I am typing.
I also attached a set method and an onChange lifecycle method to the `validation` property in the Directives controller class. So my expectation is that as I type in the input box, both set method and onChange method will get triggered, but it isnt(refer plnkr line number#49). However if I attach an `(keyup)` event to the directive, everything works. (refer plnkr line number#50 - uncomment this line and comment line#49). 
```javascript
@Directive({
selector: '[validation]',
lifecycle: [onChange],
properties: {'value':'validation'}
})
class Validator {
  
  constructor(elementRef: ElementRef) {
    this.el = elementRef.domElement;
  }
  
  set value(newvalue){
    console.log(newvalue);
  }

  onChange(p) {
    console.log(p)
    if (this.value === 'x') {
      
      this.el.className = "has-error"
    } else {
       this.el.className = ""
    }
  }
 
}

@Component({
    selector: 'app'
})
@View({
  template: `
     <style>
         .has-error {
             background-color: red
           
         }
      </style>
      <input type=text #input [validation]="input.value" >
      <!--<input type=text #input (keyup)[validation]="input.value" >-->
      Type 'x'!
  `,
  directives: [Validator]
})
class MyAppComponent{

}
```
Here is the full example in plnkr http://plnkr.co/edit/wDyiNyOJSoCMRqVlwHoU?p=preview

Is it a bug or Do we need to attach an event to the Directive to trigger the change detection?

I also attached below the explanation from angular.io docs page, where it says **Whenever the someExpression expression changes, the properties declaration instructs Angular to update the Tooltip's text property.**

The below code sample is from angular.io docs page.
```javascript
@Directive({
  selector: '[tooltip]',
  properties: {
    'text': 'tooltip'
  }
})
class Tooltip {
  set text(text) {
    // This will get called every time the 'tooltip' binding changes with the new value.
  }
}
```

**We can then bind to the tooltip property as either an expression (someExpression) or as a string literal, as shown in the HTML template below:**

```html
<div [tooltip]="someExpression">...</div>
<div tooltip="Some Text">...</div>
```
**Whenever the someExpression expression changes, the properties declaration instructs Angular to update the Tooltip's text property.**

**Comment by choeller** [comment]
To be a bit more specific, I would say, that as far as I understand change detection is not working for local variables referring to a DOM Element:

```html
<input type=text #input (keyup)[validation]="input.value" >
```
...
```javascript
@Directive({
selector: '[validation]',
lifecycle: [onChange],
properties: {'value':'validation'}
})
class Validator {
...
```

So in the example we try to bind ìnput.value`to `[validation]`which obviously is not covered by change-detection. Adding the `(keyup)`event as a trigger somehow feels like a hack. So the question is, why do we need to trigger change detection, when we bind the local variable to a property.

**Comment by vicb** [comment]
Works as expected (you need to trigger an event), see https://angular.io/docs/js/latest/guide/user-input.html

Also note that you might want to use the form API

**Comment by choeller** [comment]
Hi Victor, 

we saw that in the documentation, and we realised, that we currently need it, but I think the source above is a different case, as we really bind a property to the the local variable. 

So basically the question is: What is the difference between

```html
<div [tooltip]="someExpression">...</div>
```
and
```html
<input type=text #input [validation]="input.value" >
```

Furthermore I can currently trigger any event and magically my changes are recognized. So this code also works perfectly fine:

```html
     <input #myname>
     <p>The value is {{myname.value}}</p>
     <button (click)>Click me to trigger change detection</button>
```


From a developer point of view this all feels pretty hacky and inconsistent and IMO leads to a lot of confusion. Can you explain the differences of the cases above?

Thanks in advance
Christoph

**Comment by vicb** [comment]
Not much difference.

Both `somExpression` and `input.value` are evaluated during the Change Detection. The change detection runs after any async "event" (a future that completes, a DOM events, ...).

Changing the value of an input field does not trigger the change detection. If you listen to the `keyup` event, the CD will run after any of those are triggered.

I understand that this does not feel intuitive at first but the form API will probably help here.

Do it makes sense ?

**Comment by choeller** [comment]
Hi Victor, 

thanks for your explanations! That all makes sense, somehow ;) I guess not triggering Change Detection on input value changes has performance reasons, right?

In our case form API would of course be an option, but in other cases like just passing the input.value to another component, like this:

```html
     <input #myname>
     <crazy [crazyprop]="myname.value"></crazy>
```

it would still be nice, if things were simpler, but I guess, there will be helpers for such cases in the future. 

Thanks again
Christoph

**Comment by ibhi** [comment]
Ranks @vicb for clarification and also thanks to my friend @choeller .
