### ISSUE TITLE
Literals in css with escapes are not emitted correctly

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#22774]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
</code></pre>

REF: [b/74538140](http://b/74538140)

## Current behavior

A style that contains an a value with a string escape such as `'\0025BC'` is emitted as `"\\x0025BC"` instead of the expected "\0025BC".

This is true when using 2.6 or 2.7 of TypeScript but does not reproduce with 2.5.

This is related to https://github.com/Microsoft/TypeScript/issues/20192. TypeScript, beginning with 2.6, calls `escapeString` for the value of synthetic literals.

https://github.com/Microsoft/TypeScript/blob/1736741e546bb6d436acd4c0632e3b23c7033b29/src/compiler/utilities.ts#L352

This produces the incorrect escaping identically had this been an interpolation.

## Expected behavior

The escaped string in css should be emitted correctly.

## Minimal reproduction of the problem with instructions

1. `ng new repro`
2. modify app.component.css to be

```css
span {
  content: '\0025BC';
}
```

`./node_modules/.bin/ngc -p src/tsconfig.app.json`

Inspect `out-tsc/app/src/app/app.component.css.shim.ngstyle.js`

**EXPECTED**

```
["span[_ngcontent-%COMP%] {\n  content: '\\0025BC';\n}"]
```

**RECEIVED**

```
["span[_ngcontent-%COMP%] {\n  content: '\\x00025BC';\n}"]
```

**Comment by CWSpear** [comment]
Nice... I noticed this, too. I'm on the latest of every `@angular/*` package and TypeScript `2.6.2`, so has this just not been released, or is the issue still there? If it's the latter, I can provide more details, but looks like it's the former.
