### ISSUE TITLE
ngZone.onError.subscribe not working and errorHandler err response missing details!

### ISSUE THREAD

**Issue by karlmnz** [angular/angular#22780]
## I'm submitting a...
<pre><code>
[x] Bug report  
[x] Documentation issue or request
</code></pre>

## Current behavior
[https://angular.io/api/core/NgZone](https://angular.io/api/core/NgZone) indicates can use NgZone.onError to get errors from zone.js, but subscribing to this never catches zone.js errors.  And that ErrorHandle either on individual subscribes e.g. http.get(<url>).subscribe(..., err => {...}) or in a globalErrorHandler does not provide the actual error response. (as per expected behaviour close comment on https://github.com/angular/angular/issues/17012)

## Expected behavior
Errors in zone.js will be emitted to NgZone.onError so custom angular code can interrogate the actual error response and provide meaningful end user error info.

OR ErrorHandler err will give the actual status and statusText or message from the zone.js errors.  Zone.js seems to be able to console.error the right message so need to passed back to angular.

I expect to get a 404 error.status ... in the example case.

## Minimal reproduction of the problem with instructions
Open the following plunker, and then view both the result and console.  Not zone.onError.subscribe is never triggered and the http error info is always 'unknown error'.

[https://plnkr.co/edit/0HjQ98VEEaOHL80XFVG4](https://plnkr.co/edit/0HjQ98VEEaOHL80XFVG4)

The example is a bogus url but same happens for any other errors using HttpClient request e.g. if disconnected network, 401, ...

## What is the motivation / use case for changing the behavior?
Need to get the real error status and statusText from the zone.js errors so can conditionally manage the different error types and handle UX flow.  e.g. when make a call to an API with Auth token but is expired, then want to tell the user why, then send to auth login ...  (plus so much more e.g. disconnected network).

## Environment

<pre><code>
Angular version: 5.2.8  (this was latest at time)

Browser:
- [x] Chrome (desktop) version  64.0.3282.186
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 59.0
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11.0.51
- [x] Edge version (latest)
 
For Tooling issues:
- Node version: v8.9.4
- Platform:  assume all (Mac, Linux, **Windows**)
- Plunker v1.6.2

Others:

</code></pre>

**Comment by karlmnz** [comment]
Thanks Kara.

Additional Note: In my application with the auth token example, it is not always possible to check if valid before making the call as the check valid api call itself could happen when the network is disconnected and so zone.js would error on that ...

**Comment by karlmnz** [comment]
In plunker example, if I remove the err => {..} form the http.get(...).subscribe then the NgZone,onError code is used but the problem is still that the ErrorResponse has status 0 rather than 404.

**Comment by JiaLiPassion** [comment]
@karlmnz , your plunker seems not working any longer, could you create a demo on stackblitz?

**Comment by praveen62** [comment]
any solution or work around for this?. I dont want zone.js to log any errors. 
For example: http.get() request with catch statement is catching the error and in addition to that zonejs is also logging the error first. I dont want zone js to log error for me. 

Anyway to control this behaviour?

**Comment by boknoypatotoy** [comment]
how can i pass zone.js errors to my custom error handler? Errors like net::ERR_* do not make it to catchError ... it only shows generic statuscode 0, unknown, which i think useless to show to client. or is it a bug?

ex. net::ERR_NAME_NOT_RESOLVED 502 (Bad Gateway)

**Comment by boknoypatotoy** [comment]
> In plunker example, if I remove the err => {..} form the http.get(...).subscribe then the NgZone,onError code is used but the problem is still that the ErrorResponse has status 0 rather than 404.
> 
> And in my app I have a globalErrorHandler and also have http...subscribes that have () => {...} so the NgZone.onError doesn't get executed in these cases.

I have the same problem ... anything helpful ...

**Comment by JiaLiPassion** [comment]
@boknoypatotoy , could you provide a reproduce repo to describe this issue? Thanks!

**Comment by pkozlowski-opensource** [comment]
Seems like the original reproduce scenario no longer works and we didn't get a new one. Given this I've got no choice but to close this issue for now. If anyone hits this / similar issue, please open a new ticket with a minimal reproduce scenario.
