### ISSUE TITLE
Unable to use ngAfterViewInit for Modal clicking outside trigger

### ISSUE THREAD

**Issue by nir-sk** [angular/angular#22786]
Modal gets closed when clicked on the close modal button as well as when mouse clicked outside the modal I want to call the same function that I call when I click on the close modal button also when I click outside the modal. I am not sure how to do this in Angular 2. I am using jQuery to display the modal. I tried using ngAfterViewInit() but it did not help me.
Also I tried using (clickOutside)="CloseModal()"; in html but this is running whenever I click anywhere on the component other than the modal area.
I am not sure where I am going wrong I am new to Angular 2 and TypeScripting.
Could you please share your ideas on this. Below is my code
Thanks

        import { Component, OnInit, AfterViewInit, NgModule, Input, Output, EventEmitter, ViewChild, ElementRef } from '@angular/core';
        import * as jQuery from 'jquery';

    export class Component implements OnInit {

      @ViewChild('newModal') newModal: ElementRef; 

    public OpenModal(){
    jQuery(this.newModal.nativeElement).modal('show');
    }

    public CloseModal(){
    Includes actions taken when close modal button is clicked - I want the same function to be called with I click outside the model. So I called this function in ngAfterViewInit....
    } 

    ngAfterViewInit() {
      this.newModal.onDismiss.subscribe(() => {
    CloseModal();
      });
    }     
    }

**Comment by matsko** [comment]
Hello @nir-sk it's difficult to figure out what exactly is going on here without all the info about Angular, the version and a reproduction of the issue. Please open a new issue and follow the template in the new issue and fill in each question and produce a link to stackblitz.com which has a working demo of the issue.

**Comment by nir-sk** [comment]
Thx Matsko!!!!
