### ISSUE TITLE
json pipe does not update on object change

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#2278]
Maybe it is by design, but when I use the `json` pipe on an object inside a `ng-for`, whenever I change the object from a directive, these changes are not reflected.

I have a [repo](https://github.com/rolandjitsu/ng2-play) where I actually use this and you can see it [here](https://github.com/rolandjitsu/ng2-play/blob/db65c8a7001083aba0dc0555a9374f9b5f614a14/src/components/tasks/tasks.html#L14).

**Comment by vicb** [comment]
The problem might be that `test` is checked by ref and if the ref does not change, `json` is no re-evaluated as transformers are pure fonctions.
/cc @vsavkin

**Comment by rolandjitsu** [comment]
@vicb `test` is actually an array of objects (I said `object` in the first post - my bad). Detection works when I change the length of the array, but it does not work when I change any of the object values inside the array.

In Angular 1.x there is a `$watchCollection` for instance which solves that issue when you need to watch for changes inside the array, because a simple `$watch` did not work (unless you specify the deep comparison option `$watch(something, callback, true)`).

I'm not quite sure how things work in Angular 2 though.

**Comment by vsavkin** [comment]
You should be able to do the following: `{{ col | iterableDiff | json }}`. iterableDiff transforms a reference check into a collection check.

**Comment by vsavkin** [comment]
We could also change json not to cache the value.

**Comment by rolandjitsu** [comment]
@vsavkin maybe json should not cache the values, but that would have an impact on performance I suppose.

**Comment by rolandjitsu** [comment]
@vsavkin using `iterableDiff` throws: `Cannot find 'iterableDiff' pipe supporting object '[object Object]' in [{{ test | iterableDiff | json }} in null]`.

**Comment by gdi2290** [comment]
darn :/ cache was a perf feature. Yeah I can update it. If we want to cache the ref we should just add a `CachePipe` or `LRUPipe` 

`{{ test | cache | json }}`
`{{ test | lru(5) | json }}`

**Comment by gdi2290** [comment]
I'm also running into this problem so I can't test locally. Although, the changes is just removing code and adding more tests
https://github.com/angular/angular/issues/2281

**Comment by rolandjitsu** [comment]
@gdi2290 I think that a cache pipe would be nice for those who do not want any changes reflected after the collection has been set.

**Comment by gdi2290** [comment]
this issue can be closed here since it was fixed via https://github.com/angular/angular/pull/2308 and merged at https://github.com/angular/angular/commit/e77710a3727e40778a247e96f0507c212091668a

**Comment by gdi2290** [comment]
this can be closed
