### ISSUE TITLE
Angular i18n and Server Side Rendering LOCALE_DATA is not populated

### ISSUE THREAD

**Issue by martinmcwhorter** [angular/angular#22793]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Following the Universal SSR recipes at 
* https://angular.io/guide/universal
* https://github.com/angular/angular-cli/wiki/stories-universal-rendering

In the app template is the following

```
    Date Example:
    <div>
      {{ '2018-03-17' | date }}
    </div>

    <br>
    Number Example:
    <div>
      {{ 123456789 | number }}
    </div>

    <br>
    Currency Example:
    <div>
      {{ 987654.33 | currency : 'EUR' }}
    </div>
```

Build using an explicit locale: 

    ng build --prod --locale=fr-FR && ng build --prod --locale=fr-FR --app 1 --output-hashing=false

The Node/Express server reports the following error:

```
Node server listening on http://localhost:4000
ERROR Error: Missing locale data for the locale "fr-FR".
    at findLocaleData (D:\projects\ssr-i18n-missing-locales\dist\server.js:29460:11)
    at getLocaleId (D:\projects\ssr-i18n-missing-locales\dist\server.js:29069:12)
    at getNamedFormat (D:\projects\ssr-i18n-missing-locales\dist\server.js:31664:37)
    at formatDate (D:\projects\ssr-i18n-missing-locales\dist\server.js:31625:40)
    at DatePipe.transform (D:\projects\ssr-i18n-missing-locales\dist\server.js:32415:16)
    at checkAndUpdatePureExpressionInline (D:\projects\ssr-i18n-missing-locales\dist\server.js:14760:38)
    at checkAndUpdateNodeInline (D:\projects\ssr-i18n-missing-locales\dist\server.js:15476:20)
    at checkAndUpdateNode (D:\projects\ssr-i18n-missing-locales\dist\server.js:15415:16)
    at prodCheckAndUpdateNode (D:\projects\ssr-i18n-missing-locales\dist\server.js:16139:5)
    at Object.updateRenderer (D:\projects\ssr-i18n-missing-locales\dist\server.js:134994:7131)
```
If I do view source on the page, the locale pipes have not rendered the values:

```
   Date Example:
   <div>
   </div>
    
   <br>
   Number Example:
   <div>
   </div>
    
   <br>
   Currency Example:
   <div>
   </div>
```

## Expected behavior

When I rerun the above for English, I get no error for the server missing locale data, and the i18n pipes render the data, number and currency expressions. 

I would expect this to work for any valid supported locale. 

## Minimal reproduction of the problem with instructions

```
git clone https://github.com/martinmcwhorter/ssr-i18n-missing-locales.git
cd ssr-i18n-missing-locales
npm install
npm run build:ssr
npm run serve:ssr
```

Open `http://localhost:4000`
CTRL+U to view page as source

```
npm run buld:ssr:en
npm run serve:ssr
```

Open `http://localhost:4000`
CTRL+U to view page as source

## What is the motivation / use case for changing the behavior?

Would like to use SSR for multiple locales. 

## Environment

<pre><code>
Angular CLI: 1.7.3
Node: 8.9.4
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

Browser:
- [x] Chrome (desktop) version 64
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4
- Platform:  windows 10

Others:

</code></pre>

**Comment by martinmcwhorter** [comment]
@ocombe

**Comment by ocombe** [comment]
You should import the locale data for french as explained in the i18n guide: https://angular.io/guide/i18n#i18n-pipes

**Comment by martinmcwhorter** [comment]
This i18n guild says:

    "The CLI imports the locale data for you when you use the parameter --locale with ng serve and ng build."

Is this incorrect?

**Comment by ocombe** [comment]
It should, but apparently not for the server side module. Could you open an issue on the cli repository instead?

**Comment by ocombe** [comment]
thanks
