### ISSUE TITLE
Textarea not correctly behaviour with reset button

### ISSUE THREAD

**Issue by tofesath** [angular/angular#22791]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

After reset action of a form, an included textarea contains whitespaces.

## Expected behavior

After reset action of a form, an included textarea should be empty.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/xiczCv2Uv80bh0Lb4pwx?p=preview

Click on the reset button and you check the content of the textarea. You will see that there are several spaces inside.

## What is the motivation / use case for changing the behavior?

It is confusing for the user when all input fields are empty after reset but textarea is not.

## Environment

<pre><code>
Angular version: 5.2.3

Browser:
- [x] Chrome (desktop) version 65.0.3325.162
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 5.6.0  
- Platform: Windows 

Others:

</code></pre>

**Comment by bradtaniguchi** [comment]
This seems to be an html thing, not an angular bug. The spaces when you define for the text area are set as the "default values", so when you use the html's reset, the text area is filled with these values. (as they are set normally by html by default)  
So this html code will replicate your issue, except initially the textarea is filled with the extra spaces.
```html
<form>
  <textarea>       </textarea>
  <button type="reset">
    reset
  </button>
</form>
```
You can prevent this by doing:
```html
<textarea formControlName="multiline"></textarea>
```
OR
You can capture the reset event with
```html
<form (onReset)="reset()">
...
</form>
```
and in your component
```typescript
reset() {
  this.formGroup.reset();
}
```

**Comment by tofesath** [comment]
You are right, thank you for your prompt response. 

My problem was fixed by removing extra spaces in inner textarea.
