### ISSUE TITLE
using `set` on component class to detect property changes throws exception

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#2279]
If I want to detect when a property binding changes using `set` as illustrated in the docs on a [Component](https://angular.io/docs/js/latest/api/annotations/Component-class.html) that has a template which uses that binding, it throws an exception:

```js
import { ComponentAnnotation as Component, ViewAnnotation as View } from 'angular2/angular2';

@Component({
	selector: 'task',
	properties: {
		'chore': 'model'
	}
})

@View({
	templateUrl: 'components/task/task.html',
	directives: []
})

export class Task {
	constructor() {}
	set chore(value) { // if I use this it causes an exception to be thrown
		console.log(value);
	}
}
```
```html
<ul>
	<li>{{chore.desc}}</li>
</ul>
```

![screenshot 2015-06-02 10 45 39](https://cloud.githubusercontent.com/assets/1479737/7931887/8d6553ce-0914-11e5-9670-d13e98930b1c.png)

**Comment by vicb** [comment]
As indicated by the error message, you need to add  a getter too (used by change detection)

**Comment by choeller** [comment]
You need to define a getter for `chore`. With your code `{{chore.desc}}` cannot be resolved.

**Comment by rolandjitsu** [comment]
@vicb great, thanks :) Maybe that should be specified in the docs since I, for instance, expected that specifying the property would be enough.
