### ISSUE TITLE
aio + docs/api: directive docs ideas

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#22790]
1) [x] do not show constructor (it is not relevant to the user of the directive) (see https://github.com/angular/angular/commit/cf0968f98e844043a0f6c2548201f3c0dfd329a7)
2) [x] put the inputs and outputs into a table
3) [x] combine the inputs and outputs information with their associated properties
4) [ ] convert the selectors information into example usages, similar to what we have done in Pipe overviews.

**Comment by IgorMinar** [comment]
sounds good except for 4 - some selectors especially in forms are quite complex and might be hard to convey clearly without actually showing the raw selector.

If we can work around this then we don't need to show them, otherwise we should show the selector.

**Comment by jbogarthyde** [comment]
See how this works out in some mockups: 
https://docs.google.com/document/d/1sYEdRp48kXCofHvisKA9-UOLBRu7mzg8vxG0drY2vg8/edit#heading=h.fltci8lkrw5

**Comment by petebacondarwin** [comment]
BTW I believe we can compute whether a directive is structural or not by looking for  `ViewContainerRef` and `TemplateRef<...>` classes injected into the constructor.

**Comment by trotyl** [comment]
Possible issues:

+ [`NgComponentOutlet`](https://github.com/angular/angular/blob/5.2.9/packages/common/src/directives/ng_component_outlet.ts#L10-L112) and [`NgTemplateOutlet`](https://github.com/angular/angular/blob/5.2.9/packages/common/src/directives/ng_template_outlet.ts#L10-L100) doesn't have `TemplateRef` but known as Structural Directive;
+ [`NgSwitch`](https://github.com/angular/angular/blob/5.2.9/packages/common/src/directives/ng_switch.ts#L35-L127) and [`NgPlural`](https://github.com/angular/angular/blob/5.2.9/packages/common/src/directives/ng_plural.ts#L14-L81) has no `TemplateRef` nor `ViewContainerRef`, only their content children companions do;
+ [`RouterOutlet `](https://github.com/angular/angular/blob/5.2.9/packages/router/src/directives/router_outlet.ts#L14-L142) is technically more Structural Directive (providing `ViewContainerRef` like `NgComponentOutlet`) than Attribute Directive (doesn't perform side-effects at all), but using element selector making that weird.

**Comment by petebacondarwin** [comment]
So we could relax the test to whether it injects a `ViewContainerRef` which would pick up `NgComponentOutlet`, `NgTemplateOutlet` and `RouterOutlet`. But I agree that it is not possible to automatically identify `NgSwitch` and `NgPlural` via this approach.

**Comment by petebacondarwin** [comment]
Actually thinking about this some more, I am not sure there is much benefiting in actually labelling a directive as structural. It is something that should be explained in the docs but having a tag (or being able to filter by "structural" type) doesn't seem of much use IMO.

**Comment by jenniferfell** [comment]
Related example docs in progress: https://github.com/angular/angular/pull/24135

Related issue re directive templates: https://github.com/angular/angular/issues/25530
