### ISSUE TITLE
Exclude EventHandler Functionality from Zone.js

### ISSUE THREAD

**Issue by dolebrant** [angular/angular#22798]
## I'm submitting a...
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request 

## Current behavior
I want to insure that the 'keydown' event is excluded from zone.js when it loads within an Angular application.  

Right now I believe there is some need for clarity in documentation as some suggestions are towards using the "removeEventListener" which does not seem to function properly.  Is there a method or future plans to allow configuration methods which would suppress specific EventHandlers ?

## What is the motivation / use case for changing the behavior?
Because zone.js and other applications may fulfill the same functionality, I believe this knowledge / implementation is very critical.

## Environment
Angular 4

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by JiaLiPassion** [comment]
@dolebrant , you can found it in latest version of `angular/cli`.
add this line before loading zone.js in `polyfill.ts`

```javascript
// (window as any).__zone_symbol__BLACK_LISTED_EVENTS = ['keydown']; // disable patch specified eventNames
import 'zone.js/dist/zone';  // Included with Angular CLI.
```

**Comment by dolebrant** [comment]
I am currently running 
@angular/cli: 1.2.5
@angular/compiler-cli: 4.3.3

So I don't think that this fix would apply in my current situation (I think this was implemented after).  Not really willing to upgrade, so I will just put in a custom fix / hack for now.  

But Thanks.

**Comment by jenniferfell** [comment]
docsarea=eventhandler
