### ISSUE TITLE
Horrible hack breaks whenever selenium-webdriver Command changes.

### ISSUE THREAD

**Issue by johnjbarton** [angular/angular#22804]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
" * Copy of the `Command` class of webdriver"
angular/packages/benchpress/src/webdriver/selenium_webdriver_adapter.ts

## Expected behavior

Proper use of upstream code.

## Minimal reproduction of the problem with instructions

Change selenium-webdriver Command in any way.
Attempt to run angular benchmark
Confusion when Command fails.
## What is the motivation / use case for changing the behavior?

Come on this is dumb code.

## Environment

<pre><code>
Angular version: X.Y.Z

Source code error.
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dylhunn** [comment]
`benchpress` was never public API; not in scope for this sort of issue.
