### ISSUE TITLE
ngIf not working properly when array is empty

### ISSUE THREAD

**Issue by Zerokk** [angular/angular#22801]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I've got an object with various properties, each of which, is an array. These arrays fill in and down depending on some user interaction. This list should be hidden when the array gets emptied, but... it just doesn't:

1. If I click on an item, the ngIf (list.length > 1) executes and shows the list, and therefore, that key and that item. Nice.
2. If I click on more items, they get added to the list. If I unselect them, they get removed. Nice!
3. If I unselect the first item that I added to the array, that key should be removed from the list. But it stays there. And even more strangely, if I click again in the item to select it, the key gets repeated in the list. 

## Expected behavior
When deselecting all the items for a given key, that key should be removed from the list. The code is pretty self-explanatory:

```
<div *ngFor="let attr of config?.attribute_list">
  <div class="row " *ngIf="attr.selected.length > 0">
    <div class="col no-padding">
      <span>{{ attr?.label }}</span>
    </div>
    <div class="col no-padding">
      <p>{{ attr?.selected ? attr?.selected.join(", ") : ""}}</p>
    </div>
  </div>
</div>
```

When a given attribute has 0 selected items, it should not appear... right? Well, if you select an item and deselect it, it will just stay where it is! And if you select it back again... it creates that key again! It's a fucking mess, and sorry for the bad words, but this makes absolutely no sense.

I've been checking the object on each value change, to see if there was being some strange behavior, but the object just responds as expected. 

## What is the motivation / use case for changing the behavior?
It's plain simple: the ngIf should react on the array length change, and when it's emptied, just remove that key from the list. 

## Environment
Angular CLI: 1.5.4
Node: 8.9.1
OS: win32 x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.4
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.4.2
webpack: 3.8.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ X ] Firefox version Quantum
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

 
I'm really concerned about this, because it's affecting to a serious project, and after hours trying to look for the problem, I just can't find anything. It's a complex page, there's just too much info to make a Plunkr or something, and there are many uses of RxJs and other business logic things that may difficult a lot explaining this further.

But the part that is affected itself... it's plain easy. There should be no problems with this, it's a very simple thing that I think has something to do with Angular itself. The array just behaves as expected: it gets the value added when selected, and erased when deselected. Easy peazy. But why the hell does this super strange behavior happen at the ngIf not hiding up the array with length lower than 1? Why the NgFor shows another copy of that key afterwards? This makes no sense.

**Comment by jotatoledo** [comment]
If the part that is affected is plain easy peazy as you mention, it should be as easy to reproduce in a minimal environment. Please do the effort and provide a living reproduction.

**Comment by flakolefluk** [comment]
I think the bug is related to adding or removing attributes. Not to the *ngIf displaying the list. We don't have access to that part of the code and that makes it harder to help. You might have shared the part that is working as expected.
To help you debugging, you can try to display the length of the array(I added a span below)

`
<div *ngFor="let attr of config?.attribute_list">
<span>Check length: {{attr.selected.length}} </span> 
  <div class="row " *ngIf="attr.selected.length > 0">
    <div class="col no-padding">
      <span>{{ attr?.label }}</span>
    </div>
    <div class="col no-padding">
      <p>{{ attr?.selected ? attr?.selected.join(", ") : ""}}</p>
    </div>
  </div>
</div>
`

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
