### ISSUE TITLE
Reactive forms validation documentation - possible issue

### ISSUE THREAD

**Issue by Bartosz-D3V** [angular/angular#22809]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Angular documentation (https://angular.io/guide/form-validation) states that it is fine to access formControl invalid property like this:
```js
<input id="name" class="form-control"
       formControlName="name" required >

<div *ngIf="name.invalid && (name.dirty || name.touched)"
     class="alert alert-danger">

  <div *ngIf="name.errors.required">
    Name is required.
  </div>
```
So far I could not replicate this behavior correctly - not in local development environment, nor in StackBlitz.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-2qgdtx
After loading the app, please open the console and you can see the error:

```
ERROR TypeError: Cannot read property 'invalid' of undefined
```
Which is basically the core problem of this issue.

Others:
This is likely to be a duplicated of closed & unresolved issue- #19846

**Comment by jotatoledo** [comment]
You are clearly not using the same code as in the docs. Please revisit the site and read the sections more carefully.

**Comment by Bartosz-D3V** [comment]
I need to admit that I hoped for some shortcut access to AbstractControl within HTML template as creating number of getters in component might be problematic for bigger forms. Nevertheless, the documentation is correct, therefore I am closing the issue.

Thank you so much for your help.
