### ISSUE TITLE
Router. URL. Add "isLocalUrl" function

### ISSUE THREAD

**Issue by a13531a** [angular/angular#22811]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[O] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There is no "isLocalUrl" function that would return a boolean value indicating whether the URL is local.

## Expected behavior

There is such a function in Angular.

## Minimal reproduction of the problem with instructions

No matter how much time you will be searching, reading, and looking for this function, you won't find it.

## What is the motivation / use case for changing the behavior?

[Description](https://www.trustwave.com/Resources/SpiderLabs-Blog/Understanding-and-Discovering-Open-Redirect-Vulnerabilities/)
Functionality that would be available out of the box and used in conjunction with "returnUrl" parameter in the query string. A redirect to the page would only be performed if the "returnUrl" points to the same domain. Such a check is a must in order to be protected against the Open Redirect attack http://whatis.techtarget.com/definition/open-redirect

**PLUS** it would be cool to have something like this in [NavigationExtras](https://angular.io/api/router/NavigationExtras) (note that I might not be the best at giving names to params):

`this.router.navigate([this.returnUrl], { sameDomainOnly: true, sameDomainFallbackUrl: '/home' })`

The **sameDomainFallbackUrl** URL would be used by the router in case when the specified URL (the 1st param) doesn't belong to the same domain.

## Environment

<pre><code>
Angular version: 5.2.9

**Comment by jasonaden** [comment]
Thanks for the request!
