### ISSUE TITLE
E2E tests timeout using greensock lib in lazy loaded module when using ngZone.runOutsideAngular

### ISSUE THREAD

**Issue by edoparearyee** [angular/angular#22827]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I'm trying to use the Greensock [`TimelineMax`](https://greensock.com/docs/TimelineMax) library in my cli project which has some async code `setInterval`/`setTimeout` etc..., inside a component in a lazy loaded module. My protractor tests fail even when my `TimelineMax` code is wrapped inside a `ngZone.runOutsideAngular` code block which is what is recommended according to the documentation for protractor: https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular

If I move the component around in my project so it's not lazy loaded then e2e tests run successfully.

## Expected behavior
E2E tests should not timeout when running async code inside `ngZone.runOutsideAngular` inside a component inside a lazy loaded module.

## Minimal reproduction of the problem with instructions
https://github.com/edoparearyee/angular-greensock-example

simply run `npm run e2e` and the e2e tests will timeout.

To get the tests to run uncomment the lines here: https://github.com/edoparearyee/angular-greensock-example/blob/master/src/app/app.module.ts#L7-L16 and here: https://github.com/edoparearyee/angular-greensock-example/blob/master/src/app/app-routing.module.ts#L5 and run `npm run e2e` again

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [x] Chrome (desktop) version 65

 
For Tooling issues:
- Node version: 8.9.4
- Platform:  Mac

</code></pre>

**Comment by atscott** [comment]
Closing as obsolete (protractor is deprecated)
