### ISSUE TITLE
Upgrade component: $attrs and $transclude locals are not provided

### ISSUE THREAD

**Issue by FDIM** [angular/angular#22824]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When upgrading angularjs component, `$attrs` and `$transclude` dependencies are not provided as they are passed as locals. 
Workaround is not really possible either as you can't get a reference to these locals from `$injector` and do something different for upgraded component without changing previous behavior.

## Expected behavior

 `$attrs` and `$transclude` dependencies should be provided, at least mocks so that something special could be done if needed. Now it just fails at runtime when you attempt to upgrade such component.

## Minimal reproduction of the problem with instructions

- open https://stackblitz.com/edit/ngupgradestatic-playground-9uqkzi?file=ng1%2Fng1-demo.component.ts
- you will see `Error: [$injector:unpr] Unknown provider: $attrsProvider <- $attrs` (or $transclude) in console

It is also visible in the source code directly in [upgrade helper](https://github.com/angular/angular/blob/master/packages/upgrade/src/common/upgrade_helper.ts#L106) on line 106 and in [angularjs in compile.js](https://github.com/angular/angular.js/blob/c0adcc3a4b561260d0f1ff6b834ca940bf1971a9/src/ng/compile.js#L2944-L2949) on line 2944

## What is the motivation / use case for changing the behavior?

Upgrade component would be compatible with more angularjs components and in turn would simplify upgrade process. 

I am prepared to make a PR if you agree that this should be fixed :)

EDIT: I've looked into the issue a bit and I get why $attrs are not provided, mapping values would not be easy. On the other hand almost everything is in place for $transclude - it just has to be exposed (polyfilled?) in a compatible way.

So how about providing `undefined` as `$attrs` and try to expose `$transclude` ? If it proves to be difficult provide it as `undefined` as well?

EDIT2: PR ready

## Environment

<pre><code>
Angular version: 5.2.7

Browser: any

</code></pre>

**Comment by gkalpak** [comment]
They are deliberately not passed, since these features are not supported by `ngUpgrade` (see also [here][1]). `ngUpgrade` does not support all AngularJS features, because some are impossible to support (needing access to AngularJS internals) and others are not worth the complexity.

In general, if we decide to support a specific feature, we aim to make it work exactly the same as it would in a plain AngularJS app. The reasoning is that it is better to fail when something is not properly supported (and force people find other way around it), then pretend we support it and have the apps fail in unexpected, hard-to-detect/debug ways.

[1]: https://github.com/angular/angular/blob/0bede54b2de0f3014a16fd59803858a3ac38b2f6/packages/upgrade/src/static/upgrade_component.ts#L173-L183

**Comment by FDIM** [comment]
I understand, but the issue that still remains is that if these values are not provided, you simply can't upgrade a component that for example needs `$transclude` or `$attrs` for some of it's optional functionality

In my case, we have a custom autocomplete and select components that use a shared service to open a menu which shows a list of items (could be filtered, highlight some text and are also accessible with keyboard) - both of them support optional custom template that you can pass as content which would be used to render a single item in the menu. Now the problem is that, since it is optional I could tell the teams that custom item template is not supported in upgraded component and if it's required we must prioritize and refactor it to angular 5. 
As it is now, we would have to drop the feature (and possibly refactor existing code) or provide `$attrs` and `$transclude` as global dependency (which would be a hack) instead of tweaking the component a bit to not break if `$tranclude` or `$attrs` are injected as `undefined` when used inside angular 5 component. (Currently I patched @angular/upgrade/static.js and provided `null` value for both) 

Implementing transclude is a bit tricky and would not work in all the scenarios, more specifically the implementation that I have in the PR would not work in our case (not 100% sure) as we wouldn't be able to clone the template, change the context (e.g. value of x in the new unit test) and render it. On the other hand it would work for some other simpler use case where you only transclude the content.

Aside of that, when it comes to `$attrs`, we only need that for a workaround to make sure that model on parent scope is updated before on-change expression is evaluated. I believe that this is non-issue for upgraded component as we can do two-way bind and subscribe to model change event when my other PR is merged :)

My simplest goal would be to have these values as `undefined` or `null` and documented in upgrade guide. We are not depended on actual `$transclude` value - I only tried to polyfill it as challenge for myself 😃
