### ISSUE TITLE
Logic inside environments.ts fails in decorator with --prod

### ISSUE THREAD

**Issue by samuelt1** [angular/angular#22829]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Placing logic of any kind within the `environments.prod.ts` will not be used within a @NgModule. *This only happens when running with --prod*
 For example:
```
@NgModule({
  imports: [
    myModule.forRoot({
      myAtt: environment.envAtt,
    })
  ]
})
export class AppModule { }
```

Inside the environment file it looks like this:
```
const env : any = {
  production : true
};
env.envAtt = 'value';
export const environment  = env;
```

`myModule` will not get undefined for myAtt inside the forRoot function

## Expected behavior

I would expect the `myModule.forRoot` function to get 'value' from the variable envAtt

## Minimal reproduction of the problem with instructions

See this repo: https://github.com/samuelt1/angular-problem

It is very easy to reproduce. Use the example above, and replace the myModule with your favorite module, and then replace myAtt with a variable that gets used within that module, the run it with `ng s --prod` It will also break while doing a `ng build --prod`, but that is more work.

## What is the motivation / use case for changing the behavior?

I am using nested environment files. So I import a base environment, to my main environment file, and cannot do so. I have about 20 environment files that I manage in one project, and having a base environment file makes things significantly easier. 

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
I didn't bother to check more it.
 
For Tooling issues:
- Node version: v8.9.1  
- Platform: Linux server, Mac 

Others:

</code></pre>
I have not tried getting rid of the decorator, but I could not find the documentation on that.

**Comment by johngrogg** [comment]
This actually seems to extend beyond the environment files themselves to all pre-compiled code. Extending the example provided above:

environment.ts:
```
export const environment = {
  production : true,
  envAtt: 'value',
  envNum: 5
};
```

app.module.ts
```
@NgModule({
  imports: [
    myModule.forRoot({
      myAtt: environment.envAtt,
      myNumAsString: environment.envNum.toString()
    })
  ]
})
export class AppModule { }
```

When this gets built using `ng build --prod`, the pre-compiled app.module code loses the entire `myAtt: environment.envAtt.toString()` value, resulting in `myModule.forRoot` being passed the following object:
```
{
  myAtt: 'value'
}
```
instead of the desired:
```
{
  myAtt: 'value',
  myNumAsString: '5'
}
```

This does not effect non-prod builds, I assume, because it does not pre-compile the app.module.

**Comment by swayam18** [comment]
Are there any updates on this? This is a very surprising issue.

**Comment by JoostK** [comment]
Many parts of AOT compilation still depend on statically evaluating code to know certain values without a runtime. This has some limitations [as outlined here](https://angular.io/guide/aot-compiler#expression-syntax-limitations).

The good news however is that this will work correctly with the Ivy compiler.
