### ISSUE TITLE
About translate

### ISSUE THREAD

**Issue by babyblue94520** [angular/angular#22823]
I hope to establish multilingual support for the project in a simple, fast, and low-coupling way. I have tried many tools, but none of them are ideal, so I developed a tool [translate-go](https://github.com/babyblue94520/translate-go).
But translate-go cannot do SEO. 
So whether the great angular can develop similar tools and translate at the time of compilation.
This is a simple example for the official website.
1. Open [Angular](https://angular.io/), and open chrome development tools.
2. Run the javascript.
```javascript
var source2 = document.createElement('script');
source2.src = 'https://babyblue94520.github.io/translate-go/demo/AngularTranslateGoSource.js?v=2';
source2.onload = function(){
    var source = document.createElement('script');
    source.src = 'https://babyblue94520.github.io/translate-go/lib/translate-go.min.js';
    source.onload = function(){
      // 用英文語系最明顯，true:產生右下角的toolbar
      window.translateGO = new TranslateModule.TranslateGO('zh_TW',true);
      window.translateGO.loadLanguageData(AngularTranslateGoSourceByLang);
      // 開始監聽
      window.translateGO.watch();
    }
document.head.appendChild(source);
}
document.head.appendChild(source2);
```

**Comment by matsko** [comment]
Thank you @babyblue94520 for putting something together that uses Angular. 

I will be closing this issue because this isn't an issue.
