### ISSUE TITLE
$resource doesn't correctly resolve dot notation in URI parameters

### ISSUE THREAD

**Issue by jardilio** [angular/angular#2284]
If a URI parameter contains dot notation to express a path to retrieve the value on the given object, then the $resource will correctly collect the key/value pairs via "lookupDottedPath" during "extractParameters", however it doesn't get applied correctly during "Route.setUrlParams". The issue is that spliting the url value on /\W/ results in breaking up the dot notation parameter into 2 separate parameters.

Example:

A path of "'/parent/:parent.parentId/child/:childId'" is resolved to "/parent/.parentId/child/2?parent.parentId=1" when given {parent: {parentId: 1}, childId: 2} when "/parent/1/child/2" is expected.

http://plnkr.co/edit/cV5hvlgp8i1cNoJBmgGl?p=preview

The correct value returned from "lookupDottedPath" and passed into the "params" argument of "Route.setUrlParams" is: {"childId":2,"parent.parentId":1}

**Comment by jelbourn** [comment]
This repository is for Angular 2; you are looking for https://github.com/angular/angular.js
