### ISSUE TITLE
`RouteConfigLoadEnd` event emitted multiple times

### ISSUE THREAD

**Issue by peterbakonyi05** [angular/angular#22842]
## I'm submitting a...
<pre><code>
[X] Bug report
</code></pre>

## Current behavior
When lazy-loaded modules are being preloaded (using `PreloadAllModules` strategy or a custom strategy) and a navigation starts to a module that is currently being preloaded, `RouteConfigLoadEnd` event is emitted twice because `RouterConfigLoader.load` is called twice and it calls `onLoadEndListener` twice ([code here](https://github.com/angular/angular/blob/5.2.8/packages/router/src/router_config_loader.ts#L38)).

## Expected behavior
`Router` emits `RouteConfigLoadEnd` event only once for a lazy-loaded route.

## Minimal reproduction of the problem with instructions
Use `PreloadAllModules` strategy and after `RouteConfigLoadStart` even is emitted, but before `RotueConfigLoadEnd` happens, call `router.navigate` or `router.navigateByUrl` to the currently pre-loaded module. If you enable tracing, you will see two `RouteConfigLoadEnd` event is being logged in the console.

## What is the motivation / use case for changing the behavior?
When listening to `Router` events, it is not expected that this event is emitted multiple times for the same route. In our case, we need to create a lookup for route config and without having an extra safe-check in our code-base, items will be added multiple times.

## Environment

<pre><code>
Angular version: 5.2.8
Chrome (desktop) version 65
</code></pre>

**Comment by danielcrisp** [comment]
I'm experiencing this too.

I'm finding that child modules of lazy-loaded modules are instantiated multiple times (once for each `RouteConfigLoadEnd` event) as a result, and this is leading to odd behaviour.

**Comment by atscott** [comment]
Confirmed with repro here: https://angular-preload-all-qmhasc.stackblitz.io/A
https://stackblitz.com/edit/angular-preload-all-qmhasc?file=app%2Fapp.component.ts

1. Navigate to /A route (preloading for lazy loaded module starts and is returned in a 5 second timeout)
2. Navigate to /B before the 5 second timeout
-=> see that `RouteConfigLoadEnd` is fired twice.

**Comment by atscott** [comment]
Fixed by https://github.com/angular/angular/commit/4906bf6a50f307fb69080d276c3b91a60ba7fbae
