### ISSUE TITLE
RouterLink not show real path on DevTooLs and cut it.

### ISSUE THREAD

**Issue by akalightowl** [angular/angular#22845]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

RouterLink like this

`<button routerLink="/account/order/{{this.orderService.order._id}}/messages">Messages</button>`

gives me in DevTools truncated real URL

`<button _ngcontent-c4="" class="btn" tabindex="0" ng-reflect-router-link="/account/order/5aaaa0c6fd20460">Messages</button>`

## Expected behavior

But my real URL is `/account/order/5aaaa0c6fd204609b3bd2577/messages` and I think I should get something like this

`<button _ngcontent-c4="" class="btn" tabindex="0" ng-reflect-router-link="/account/order/5aaaa0c6fd204609b3bd2577/messages">Messages</button>`

## Minimal reproduction of the problem with instructions

I want to know is this bug or specification that i can't find. In Angular 5, when I use routerLink like this in my `*.component.html`

`<button routerLink="/account/order/{{this.orderService.order._id}}/messages">Messages</button>`

I get working button on url `/account/order/5aaaa0c6fd204609b3bd2577/messages`, but when I try view it in DevTools I saw something like this:
`<button _ngcontent-c4="" class="btn" tabindex="0" ng-reflect-router-link="/account/order/5aaaa0c6fd20460">Messages</button>` 
instead
 `<button _ngcontent-c4="" class="btn" tabindex="0" ng-reflect-router-link="/account/order/5aaaa0c6fd204609b3bd2577/messages">Messages</button>` with full URL path.

I tried to use different assigns methods for `routerLink`, but for all of that I got truncated real URL (I put creating URL string in `component.ts` and put only string variable in `routerLink` and other methods like `[routerLink]` creation). For first time it looks like `ng-reflect-router-link` have not enough length. But I try use simple string in href and in DevTools I see normal link like this:

` <button class="btn" routerLink="/123456789123456789123456789123456789123456789123456789123456789">Messages </button>`

I get full URL with real length of routerlink and truncated `ng-reflect-router-link`.

`<button _ngcontent-c4="" class="btn" routerlink="/123456789123456789123456789123456789123456789123456789123456789" tabindex="0" ng-reflect-router-link="/12345678912345678912345678912">Messages</button>`

When I use RouterLink with parameters or variables from component I get only `ng-reflect-router-link` and can't see real link.

## What is the motivation / use case for changing the behavior?

Under development in some situation getting truncated link prevent understand what real adress you get in view, especially if you use adress with hash or ObjectId parameters.
I think for all links we should see full path or maybe routerlink parameters as for simple string link.

And second, if user have problem with navigate with button (they can't see URL adress on left bottom corner (that not displayed for button)) and if i ask they send me link from devtools - i will get wrong address and can't detect problem.

## Environment

<pre><code>
Angular version: 5.2.8

Browser:
- [*] Chrome (desktop) version 65
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [*] Firefox version 59
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.10.0  
- Platform: Linux (Debian 9.4) 

Others:

</code></pre>

**Comment by robwormald** [comment]
Using `<button>` for navigation is generally a bad idea, due to accessibility issues. See https://marcysutton.com/links-vs-buttons-in-modern-web-applications/

If `[routerLink]` is applied to an anchor `<a>` tag, then the `href` *is* appropriately set, as far as I can tell - the `href` is the thing a user sees when they hover over a link. Buttons don't have an `href` (or shouldn't), and so you're not seeing the property reflected into the DOM.

`ng-reflect----` properties are for debugging / devtime only, and they're truncated so they don't dump huge amounts of data into the DOM.

**Comment by akalightowl** [comment]
Thank you for your explanation.
