### ISSUE TITLE
Docuementation Error in Routing & Navigation

### ISSUE THREAD

**Issue by pakmingw** [angular/angular#22849]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In Milestone 4, there is a reference to CrisisCenterModule, but I think it should be CrisisCenterRoutingModule. I'm not sure that if you follow the tutorial code it will work.

It is in section: "Import crisis center module into the AppModule routes"

https://angular.io/guide/router#import-crisis-center-module-into-the-appmodule-routes

## Expected behavior
As described in current behavior.

## What is the motivation / use case for changing the behavior?
Correct documentation

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [X] Chrome (desktop) version XX
- [X] Chrome (Android) version XX
- [X] Chrome (iOS) version XX
- [X] Firefox version XX
- [X] Safari (desktop) version XX
- [X] Safari (iOS) version XX
- [X] IE version XX
- [X] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jasonaden** [comment]
I think this doc is actually correct. While there is a `CrisisCenterRoutingModule`, that should be imported into the `CrisisCenterModule`. You wouldn't want your application to have to know the inner workings of the `CrisisCenterModule`, and by directly requiring the `CrisisCenterRoutingModule` you are in a way knowing too much about that dependency.

Think about it from the perspective of two separate large teams. Your team works on the `AppModule` which glues many pieces together. Another team works on the `CrisisCenterModule` that loads in a section of the app. You wouldn't want to have to know whether that dependency uses routing or not. You just want to depend on the top-level module.

**Comment by pakmingw** [comment]
Thanks for the explanation -- that makes a lot of sense and appreciate your feedback.
