### ISSUE TITLE
The same formControlName in one form - not in sync

### ISSUE THREAD

**Issue by piernik** [angular/angular#22846]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have in my form two fields with the same `formControlName`. They are not in sync.

## Expected behavior
I think they should be in sync always.
Is it a bug or a feature?

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-y2sj5g

## What is the motivation / use case for changing the behavior?
I have search form that has one custom "phrase" field that is always visible. 
Beside it there is also an field filter that You can filter all available fields for searching. If You select "phrase" field it displays in selected fields.

![angular fieldcontrolname](https://user-images.githubusercontent.com/420691/37558002-7bf2db1c-2a0d-11e8-951e-73fc471bd860.png)

Sure - I can always sync them manually, but maybe it is a bug:)

**Comment by trotyl** [comment]
Duplicate of #10036

**Comment by piernik** [comment]
Oh... so this i feature :/
