### ISSUE TITLE
Angular 5 Getting data from basic Auth .net api

### ISSUE THREAD

**Issue by Shahf172** [angular/angular#22858]
let headers = new Headers({ 'Content-Type': 'application/json' }); // ... Set content type to JSON
headers.append('Accept', 'application/json');
headers.append('Access-Control-Allow-Methods', 'POST, GET, OPTIONS, DELETE, PUT');
headers.append('Access-Control-Allow-Origin', 'http://localhost:50555/api/adminSystems');
headers.append('Access-Control-Allow-Headers', "X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding");
headers.append('Authorization','Basic' + btoa('faizan'+":"+'pass'));

let opt: RequestOptions = new RequestOptions();
opt.headers = headers;

return this.http.get('http://localhost:50555/api/adminSystems', opt)
.subscribe((data:any)=>{
  console.log(data);
});              

the error is coming when i am hitting the get request is given below:
ERROR 
Object { _body: "", status: 401, ok: false, statusText: "Unauthorized", headers: {…}, type: 2, url: "http://localhost:50555/api/adminSystems" }
core.js:1350
XML Parsing Error: no root element found
Location: http://localhost:50555/api/adminSystems
Line Number 1, Column 1:

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
