### ISSUE TITLE
Animation query(): Sibling Selector

### ISSUE THREAD

**Issue by sqwk** [angular/angular#22853]
## I'm submitting a...
<pre><code>
[ ] Regression
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
Animation's `query()` "is used to find one or more inner elements within the current element that is being animated" according to the docs.

## Feature Request
Allow selecting sibling or parent elements using the query selector. The former could be implemented using CSS' sibling selectors `~` or `+`:

<pre><code>
transition('void => someState', sequence([
    query(':self ~ @siblingElement',
        animate('300ms ease-in-out', style({
            opacity: '0'
        })), { optional: true }),
    ...
    query(':self', stagger('100ms', animate('200ms ease-in-out'))),
    query(':self ~ @siblingElement',
        animate('300ms 3s ease-in-out', style('*')), { optional: true }),
]))
</code></pre>

**Comment by matsko** [comment]
Thank you @sqwk for proposing this. Sibling selectors do work, but the problematic thing here is `:self` (since there's nothing supported like that in CSS). You could try just having a different (by placing something on a parent element), but `query()` is only designed to find inner items within the container.

**Comment by thw0rted** [comment]
I'm trying to select direct children of an element with query, and `query(":self > *")` throws.  `query(":scope > *")` works but of course it's limited to those browsers that support `:scope`.  Would that fall under this issue, or should I file a new ticket?
