### ISSUE TITLE
This is the worst framework i have ever seen.

### ISSUE THREAD

**Issue by gubenkovalik** [angular/angular#22859]
This is the worst framework i have ever seen.

**Comment by gubenkovalik** [comment]
I have real project with Angular, and the only thing i get while developing - is the hurting. Tons of hurt i get.
You need to be a creator of Angular to make a real project with Angular,

**Comment by gubenkovalik** [comment]
Yes, Angular is very good if you developing something not complicated more than "Hello World" application. But when you deal with real big scale project - the hurt is the only thing you get.

**Comment by zoechi** [comment]
Your issue doesn't contain a single bit of useful information anybody could act on.
At best the problem is that your expectations are wrong and you blame Angular instead of adjusting yourself,
and the worse case is that you are just spreading spam.
Angular works great for most. If it doesn't for you it's highly likely the problem us on your end.

**Comment by gubenkovalik** [comment]
@zoechi , your comment doesn't contain any information, that can help the situation, and from one side, i can understand you, but no one wants to get deep into it. just try to develop big project with angular and without. How many time would take both? Angular with consume at least 5x time more than if without Angular.

**Comment by gubenkovalik** [comment]
Angular - is the most perplexing.

**Comment by zoechi** [comment]
There is no situation that needs help. 
You need to stop acting like 3-year old.
Grow up, get your sh*t together and stop spamming.

**Comment by gubenkovalik** [comment]
@zoechi, don't cry, contributor, you are not blame that you are into that sh*t

**Comment by mlc-mlapis** [comment]
@gubenkovalik ... the reality is just opposite, it is the very suitable framework especially for real big projects. Just to guess, you problem is probably that you see it / try to use it by the same way as from jQuery point of view which is totally wrong way.

> But when you deal with real big scale project - the hurt is the only thing you get.

**Comment by ocombe** [comment]
Hello, this is not the place to post this kind of message @gubenkovalik, I'm closing the topic. Please follow the [contributing](https://github.com/angular/angular/blob/master/CONTRIBUTING.md) guidelines if you want to post anything constructive.

**Comment by gubenkovalik** [comment]
Okay, close it, but still Angular remains to be better. Best wishes, contributors, im outtie...
