### ISSUE TITLE
angularjs.org code examples: Removing text-shadow on the AngularJS bits will improve readability

### ISSUE THREAD

**Issue by manjitkarve** [angular/angular#22855]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
On https:/angularjs.org, the styling on the AngularJS bits (tags, attributes, placeholders) in the code examples include a white colored text-shadow on a light blue background. This makes text difficult to read from 2-3ft (for example, a desktop monitor). 

## Expected behavior

The text doesn't need the white text-shadow. The light blue background is enough to identify it as AngularJS related.

## Minimal reproduction of the problem with instructions

1. Visit https://angularjs.org
2. Scroll down to one of the code examples
![Screenshot](https://user-images.githubusercontent.com/5223355/37575256-2ba8f0fc-2b4c-11e8-816f-88e1c0b78f70.gif)

## What is the motivation / use case for changing the behavior?

Changing will improve usability and possibly accessibility.

## Environment
Chrome 65, Firefox 59, Ubuntu 16.04
<pre><code>
Angular version: NA

Browser:
- [x ] Chrome (desktop) version 65
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version 59
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: NA  
- Platform:  Linux

Others:

</code></pre>

**Comment by robwormald** [comment]
moved to https://github.com/angular/angular.js/issues/16495
