### ISSUE TITLE
Package.json defect in @angular/animations/browser/testing

### ISSUE THREAD

**Issue by kylecordes** [angular/angular#22852]
## I'm submitting a...

<pre><code>
[x ] Bug report  
</code></pre>

## Current behavior

The `package.json` file for `@angular/animations/browser/testing` is defective.

https://github.com/angular/animations-builds/blob/master/browser/testing/package.json

```
{
  "name": "@angular/animations/browser/testing",
  "typings": "./testing.d.ts",
  "main": "../../bundles/platform-browser-animations-testing.umd.js",
  "module": "../../esm5/animations/testing.js",
  "es2015": "../../esm2015/animations/testing.js"
}
```

The `main` field points to a file which does not exist.

## Expected behavior

I believe the value of this field should actually be `animations-browser-testing.umd.js`, as that is the relevant named file which does exist in the directory in which the bundles are located:

https://github.com/angular/animations-builds/tree/master/bundles

More broadly, ideally he file naming should be generated algorithmically, and that the algorithms to verify that the file exists as part of the packaging process.  I suspect there is some legacy left in the Angular build process, creating this defect.

## Minimal reproduction of the problem with instructions

It is visible at the links above. To see the problem in action, simply consume the code via a path that uses the package file. I don't have an example of that handy - but it should be irrelevant, the package files should be valid and correct.

## What is the motivation / use case for changing the behavior?

In my particular use case I am walking through the package files, grabbing the UMDs.

## Environment

No environment necessary, defect is visible at the links above.

**Comment by kylecordes** [comment]
Incidentally, the code I use walks all the package files for all of the Angular packages, and only hits the error here. Here is a charming little bit of workaround code:

```
  // Defect in the Angular packages!
  // https://github.com/angular/angular/issues/22852
  if (main == '../../bundles/platform-browser-animations-testing.umd.js') {
    main = '../../bundles/animations-browser-testing.umd.js';
  }
```

**Comment by matsko** [comment]
Hello @kylecordes. It seems like your proposed fix has already been implemented: https://github.com/angular/animations-builds/commit/fe33d109fc8c7b6078e27096d39d4e62c399596d

6.0.0-RC0 should have this apart of it already (that came out two days ago).

**Comment by kylecordes** [comment]
Excellent. I actually noticed that commit go by, but forgot to come back and find my issue and close it myself.
