### ISSUE TITLE
How use different jquery  versions in one angular project

### ISSUE THREAD

**Issue by edeye** [angular/angular#22851]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I want use two different jquery versions in one angular project,
there are 2 different jquery version: 1.11.2 and 3.3.1,and because some reasons,I can't update 1.11.2 to 3.3.1

## Expected behavior

please tell me How use different jquery  versions in one angular project

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by robwormald** [comment]
This is unrelated to Angular. Please do not use GitHub for how-to questions.
