### ISSUE TITLE
Communication between iframe to current component

### ISSUE THREAD

**Issue by nkarthikeyan90** [angular/angular#22863]
Hi,
I have used angular 5 version ,i need to send some data to Iframe and get back from componenet.ts file.
how do that
thank you

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by matsko** [comment]
Thank you @nkarthikeyan90 and @ericmartinezr. Closing.
