### ISSUE TITLE
Angular 6 - LTS

### ISSUE THREAD

**Issue by nirvan002** [angular/angular#22862]
Hi,
Angular 6 is released on 04/04/2018 while its support start date starts on 10/2018. Can you explain this deceleration? 
Will Angular 6 be supported between 04/04/2018 and 10/2018?

Best regards.

**Comment by ocombe** [comment]
Hello, where did you see this date? It's most likely a mistake. v6 will be supported for 2 major versions (until v8) since it's an LTS

**Comment by ocombe** [comment]
Actually I think that it just means that it will "still" be supported after 10/2018 (when v7 comes out)

**Comment by nirvan002** [comment]
Hello,
https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md

**Long-Term Supported (LTS) Versions**
Version -  LTS Start Date - LTS End Date
^4.0.0 October 2017 October 2018 
^6.0.0 October 2018 October 2019

**Comment by nirvan002** [comment]
Did you mean that Angular v6 will be supported from 04/04/2018 ?

**Comment by nirvan002** [comment]
`Actually I think that it just means that it will "still" be supported after 10/2018 (when v7 comes out)`

**Comment by mgol** [comment]
Angular 6 will be a regular release first and then, after approximately half a year it will become an LTS; that's what those tables mean.

This follows a similar pattern to what NodeJS does: https://github.com/nodejs/Release

**Comment by nirvan002** [comment]
Thank you.

**Comment by mgol** [comment]
If everything's clear could you close the issue?
