### ISSUE TITLE
bazel ts_devserver rule with dependency on HttpClientModule: `Uncaught ReferenceError: ɵi is not defined`

### ISSUE THREAD

**Issue by divdavem** [angular/angular#22866]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
While trying to use bazel to build [ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap) (cf my bazel branch of ng-bootstrap [here](https://github.com/divdavem/ng-bootstrap/tree/bazel)), I came across an issue that I reproduced in the following minimal repository: https://github.com/divdavem/angular_bazel_bug_httpclientmodule.

If a module depends on `HttpClientModule`, it will fail to load in the browser with `Uncaught ReferenceError: ɵi is not defined` when using `ts_devserver`.

## Expected behavior
There should be no error when a module depends on `HttpClientModule`, even when using `ts_devserver`.

## Minimal reproduction of the problem with instructions

```
git clone https://github.com/divdavem/angular_bazel_bug_httpclientmodule.git
cd angular_bazel_bug_httpclientmodule
bazel run @yarn//:yarn
bazel run //src:devserver
```

Then go to http://localhost:5432. You can see the following error on the console:

![image](https://user-images.githubusercontent.com/1152706/37603164-487e5d2e-2b8e-11e8-8617-daf51541d238.png)

When stopping on the error in the debugger:

![image](https://user-images.githubusercontent.com/1152706/37603240-74d6421a-2b8e-11e8-858e-65471935d20a.png)

Note that:
- if you revert the last commit (which adds the dependency on `HttpClientModule`), the dev server works fine (`git checkout master~1 && bazel run //src:devserver`).
- bundling with rollup works fine (`git checkout master && bazel run //src/myapp:prodserver`)

## Environment

<pre><code>
- Angular version: 5.2.9
- Bazel version: 0.11.1
- Node version: 8.9.4
- Platform: Linux (Ubuntu 16.04.4 LTS)
</code></pre>

**Comment by alxhub** [comment]
Closing as obsolete - the Bazel builder and associated CLI functionality are deprecated and no longer supported.
