### ISSUE TITLE
CanActivate Guards: unable to navigate to another route during canActivate evaluation

### ISSUE THREAD

**Issue by omermizr** [angular/angular#22865]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There is no way (or at least I haven't found one) to unsubscribe a guard's canActivate subscription, meaning you can't navigate to different routes while a canActivate is being evaluated.

## Expected behavior

There should be some way to cancel a guard's evaluation subscription. For example, Angular can implicitly unsubscribe and allow navigation, or router.events could still emit during canActivate evaluation and allow the app to handle events.

## Minimal reproduction of the problem with instructions

<pre><code>
export class TestGuardService implements CanActivate {
    constructor(private router: Router){}

    canActivate(route, state){
        // this won't complete until 30s have passed, even if the user tries to go to another route
        return race(this.router.events, timer(30000))
    }
}
</code></pre>

## What is the motivation / use case for changing the behavior?

Consider the following: 
You have a guard that needs to evaluate some expensive ajax request. During evaluation the user decides it wants to navigate to another page. There is no way to cancel the evaluation. 
A possible solution (in the app) would be to capture router events in order to cancel the canActivate subscription, but they aren't fired during evaluation.

## Environment

<pre><code>
Angular version: 5.1.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.2 
- Platform: Windows 10  

Others:

</code></pre>

**Comment by jasonaden** [comment]
Thanks. This is similar to #22865 as a feature request. I'll close this issue as it's on the plan to address as a new feature.
