### ISSUE TITLE
clang-format should not break link tags in comments

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#2287]
The line wrap reformat introduced by clang-format has made the doc comments break oddly. This is mostly an aesthetic annoyance when browsing the code, but in some cases, where the formatter breaks a link tag such as `{@link annotations/onChange}` across lines, our dgeni doc formatter can't resolve the link.

Can we make clang-format smarter about how it breaks lines? Or, make dgeni more tolerant of linebreaks in link statements?

**Comment by naomiblack** [comment]
@petebacondarwin @IgorMinar would be interested in what the best way to solve this is.

**Comment by petebacondarwin** [comment]
I think we might be able to make dgeni more tolerant but the output from clang is particularly ugly in this regard and I think it should be fixed too

**Comment by IgorMinar** [comment]
@mprobst what's the effort for teaching clang-format not to break lines within `{@...}` in comment blocks? it's kind of domain specific to javascript and jsdoc, but it would be nice if we didn't break it.

@petebacondarwin regardless of the formatting, dgeni should be able to deal with the linebreaks. can you estimate the effort please?

**Comment by mprobst** [comment]
Shouldn't be too hard, it has the same functionality for comments in Java already, iirc. I'll file a bug.

**Comment by IgorMinar** [comment]
```
/**
 * *Component Injectors*: Each component instance has its own {@link something really long here baba baba booo Injector}, and they follow
*/
```

should break into:

```
/**
 * *Component Injectors*: Each component instance has its own
 * {@link something really long here baba baba booo Injector}, and they follow
 */

and not:

```
/**
 * *Component Injectors*: Each component instance has its own {@link something really long here
 * baba baba booo Injector}, and they follow
 */
```

**Comment by mprobst** [comment]
@IgorMinar what if the text within {@link} is longer than one line?

**Comment by petebacondarwin** [comment]
I thought that dgeni was resilient to these line breaks now anyway. Can you provide a reproduction where it breaks?

**Comment by mhevery** [comment]
@naomiblack looks like `dgeni` is resilient. I am going to close. Please provide a specific use case if you reopen.
