### ISSUE TITLE
google3 CI check seems to consider only the last commit and not the PR diff

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#22871]
While working on the rxjs v6 update PR #22573 I noticed that the g3 CI check suddenly claimed that the PR had no impact on g3 (it had). This check was working just fine until I pushed a last commit to the branch that had no impact on g3 - that makes me suspect that the check operates only on the last commit and not the diff between master and the PR HEAD.

Screenshot:

![screen shot 2018-03-19 at 9 09 05 pm](https://user-images.githubusercontent.com/216296/37635614-da3c4ac0-2bb9-11e8-9a18-ac35453633f4.png)

**Comment by jelbourn** [comment]
Closing since this seems to be obsolete (Andrew Scott says it definitely checks the whole PR)
