### ISSUE TITLE
Documentation for custom async validators

### ISSUE THREAD

**Issue by coffeymatt** [angular/angular#22881]
## I'm submitting a...
<pre><code>
[x] Documentation issue or request
</code></pre>

I can't see any documentation on async custom validators (there is section on custom validators, but not async). An example with the common scenario of using http in a validator would be very useful as I'm struggling to figure out how to make it work/fire.

**Comment by jotatoledo** [comment]
Related to #22217

**Comment by zetsnotdead** [comment]
I would be willing to contribute a PR for this, but I would hate to duplicate effort. @brandonroberts can I take

**Comment by brandonroberts** [comment]
@zetsnotdead of course!

**Comment by zetsnotdead** [comment]
Awesome, I'll have something ready by Monday :+1:

**Comment by mellogarrett** [comment]
I followed this documentation and the async validation is working except for the fact my input element that is being validated always says `.ng-pending`
