### ISSUE TITLE
Documentation required: Routing with replaceUrl does not remove queryparams

### ISSUE THREAD

**Issue by echo-sean** [angular/angular#22885]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When using `replaceUrl: true` in NavigationExtras the queryParams are not removed.

## Expected behavior
Setting `replaceUrl: true` in NavigationExtras should navigate while replacing the current state in history.

## Minimal reproduction of the problem with instructions
```
this.router.navigate(['/test']);
this.router.navigate(['/test'], { queryParams: { id: '123' } });
this.router.navigate(['/other'], { replaceUrl: true });
```

## Environment
Angular 5.2.8

Browser:
- [x] Chrome (desktop) version 65.0.3325.162 Mac

**Comment by KorbinianKuhn** [comment]
If ```replaceUrl``` would clear queryParams it can interfere with parallel ```queryParams``` and ```queryParamsHandling``` settings.

Setting empty ```queryParams``` is more explizit:

    this.router.navigate(['/test']);
    this.router.navigate(['/test'], { queryParams: { id: '123' } });
    this.router.navigate(['/other'], { replaceUrl: true, queryParams: {} });

So I'm not sure whether this is really a bug or just intended.

**Comment by echo-sean** [comment]
Ah right, that makes sense.
Perhaps the documentation should include this?

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

<hr>

`replaceUrl` is actually tied to the browser history. See note [here](https://angular.io/api/router/NavigationExtras#replaceUrl).
