### ISSUE TITLE
Verify docs match examples updates for rxjs@6.0.0-alpha.4

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#22890]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Doc text matches old examples

## Expected behavior

Ensure doc text matches updated examples in PR https://github.com/angular/angular/pull/22573

## What is the motivation / use case for changing the behavior?

Ensure doc text matches what is shown in the codesnippets pulled from the examples

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
@jbogarthyde Opening an issue so we can easily link this doc update request (and doc update PR) to the original examples update PR.

**Comment by IgorMinar** [comment]
I believe that this is done and can be closed. if not please reopen.
