### ISSUE TITLE
Bundle SystemJS help

### ISSUE THREAD

**Issue by vmagalhaes** [angular/angular#22895]
## I'm submitting a...
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ x ] Support request

## Current behavior

Hi, I need a help to bundle my project the right way. The load page of my project is a little slow and a need a solution to this, so if you know something that can help me I will appreciate that.

My files > 
systemjs.config.js

> (function(global) {
>   // map tells the System loader where to look for things
>   var map = {
>     '@angular':   'node_modules/@angular',
>     'moment':     'node_modules/moment',
>     'rxjs':       'node_modules/rxjs',
>     'devextreme': 'node_modules/devextreme',
> 
>     'cldr': 'node_modules/cldrjs/dist/cldr',
>     'cldr-data': 'node_modules/cldr-data',
>     'json': 'node_modules/systemjs-plugin-json/json.js',
>     'jszip': 'node_modules/jszip/dist/jszip.min.js',
>     'globalize': 'node_modules/globalize/dist/globalize',
>   };
> 
>   // packages tells the System loader how to load when no filename and/or no extension
>   var packages = {
>     'moment':     { main: 'min/moment.min.js',    defaultExtension: 'js' },
>     'cldr':       { main: '../cldr.js',           defaultExtension: 'js' },
>     'globalize':  { main: '../globalize.js',      defaultExtension: 'js' }
>   };
> 
>   var ngPackageNames = [
>     'common',
>     'compiler',
>     'core',
>     'forms',
>     'http',
>     'platform-browser',
>     'platform-browser-dynamic',
>     'router',
>     'router-deprecated',
>     'testing',
>     'upgrade'
>   ];
> 
>   // Individual files (~300 requests):
>   function packIndex(pkgName) {
>     packages['@angular/'+pkgName] = { main: 'index.js', defaultExtension: 'js', minify: true };
>   }
> 
>   // Bundled (~40 requests):
>   function packUmd(pkgName) {
>     packages['@angular/'+pkgName] = { main: 'bundles/' + pkgName + '.umd.js', defaultExtension: 'js', minify: true };
>   }
> 
>   // Most environments should use UMD; some (Karma) need the individual index files
>   var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;
> 
>   // Add package entries for angular packages
>   ngPackageNames.forEach(setPackageConfig);
> 
>   var config = {
>     defaultJSExtensions: true,
>     map: map,
>     packages: packages,
>     bundles: {
>       "node_modules/rxjs/bundles/Rx.min.js": [
>         "rxjs/*",
>         "rxjs/operator/*",
>         "rxjs/observable/*",
>         "rxjs/add/operator/*",
>         "rxjs/add/observable/*",
>         "rxjs/util/*"
>       ]
>     }
>   }
> 
>   // filterSystemConfig - index.html's chance to modify config before we register it.
>   if (global.filterSystemConfig) { global.filterSystemConfig(config); }
> 
>   System.config(config);
> 
> })(this);
> 

gulpfile.ts

> import * as gulp from 'gulp';
> import * as util from 'gulp-util';
> import * as runSequence from 'run-sequence';
> var Builder = require("systemjs-builder");
> import {loadTasks} from './tools/utils';
> import {TASKS_DIR} from './tools/config';
> 
> loadTasks(TASKS_DIR);
> 
> // --------------
> // Build dev full (with legacy).
> gulp.task('build.dev.full', (done: any) => {
>   runSequence(
>     'clean',
>     'build.assets',
>     'build.fonts',
>     'build.templates',
>     'build.css',
>     'build.js',
>     'build.config',
>     'copy.dependencies',
>     'copy.systemjs.config',
>     'build.index',
>     done
>   );
> });
> 
> gulp.task("rxjs", () => {
>   var builder = new Builder('./');
>   builder.config({
>     paths: {"rxjs/*": "node_modules/rxjs/**/*.js"},
>     map: {"rxjs": "node_modules/rxjs"},
>     packages: { "rxjs": {main: 'Rx.js', defaultExtension: "js"} }
>   });
>   builder.bundle('rxjs', 'public/lib/rxjs/Rx.min.js', {
>     sourceMaps: true,
>     minify: true,
>     mangle: true
>   });
> });
> 
> // --------------
> // Build prod.
> gulp.task('build.prod', (done: any) => {
>   runSequence(
>     'clean',
>     'build.assets',
>     'build.templates',
>     'build.css',
>     'build.fonts',
>     'copy.ts',
>     'build.js',
>     'build.config',
>     'copy.dependencies',
>     'copy.systemjs.config',
>     'build.index',
>     done)
> });
> 
> // --------------
> // Serve prod.
> gulp.task('server', (done: any) => {
>   runSequence(
>     'server.start',
>     done
>   )
> });
> 

About the tasks, if you need see it, just ask

Thanks!

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Use the cli.
