### ISSUE TITLE
Spelling error in Guide -> Testing -> FAQ

### ISSUE THREAD

**Issue by drademacher** [angular/angular#22904]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
"The component DOM tests _describe_ in this guide often require extensive setup and advanced techniques where as the class-only test were comparatively simple."

## Expected behavior
"The component DOM tests _described_ in this guide often require extensive setup and advanced techniques where as the class-only test were comparatively simple."

## Minimal reproduction of the problem with instructions
Visit: https://angular.io/guide/testing#frequently-asked-questions

## What is the motivation / use case for changing the behavior?
Improve reading by correct grammar.

Others:

</code></pre>

**Comment by brandonroberts** [comment]
Closed via https://github.com/angular/angular/pull/22360
