### ISSUE TITLE
Docs: versioning and LTS should be explained in docs

### ISSUE THREAD

**Issue by Toxicable** [angular/angular#22915]
Most people will look on Angular.io for docs about versioning.
THerefore we should have a section explaining the general outline of time between releases and how LTS works in Angular.
Also maybe even a part about what a breaking change means and the deprication policy.

I know all of this is documented on here but that's not easy for everyone to find.

**Comment by matsko** [comment]
cc @IgorMinar @StephenFluin

**Comment by jenniferfell** [comment]
In progress

**Comment by jenniferfell** [comment]
Closed by PR https://github.com/angular/angular/pull/23551. 

Doc is here: https://angular.io/guide/releases
