### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError if focusout event is provoked by effects of click event

### ISSUE THREAD

**Issue by akloeber** [angular/angular#22910]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If the user clicks the button in the simplified component below it becomes disabled and an additional `blur`-event is provoked which itself changes the `isFocused` field. As a consequnce the bindings of `class.has-focus` should be updated but an `ExpressionChangedAfterItHasBeenCheckedError` is thrown instead.

```TypeScript
import {Component, HostBinding} from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <button
      (focus)="focused = true"
      (blur)="focused = false"
      [class.has-focus]="focused"
      [attr.disabled]="disabled ? 'disabled' : null"
      (click)="disabled = true"
    >action
    </button>
  `,
  styles: [`
    button.has-focus {
      outline: 2px solid blue;
    }

    button.has-focus {
      outline: 2px solid red;
    }
  `]
})
export class AppComponent {

  @HostBinding('class.has-focus') focused = false;
  disabled = false;
  
}
```
(http://plnkr.co/edit/pj5vRtGsWpwkMkSgSGmE?p=preview)

In Chrome this causes the following error:
```
AppComponent_Host.ngfactory.js? [sm]:1 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'has-focus: true'. Current value: 'has-focus: false'.
    at viewDebugError (core.js:9775)
    at expressionChangedAfterItHasBeenCheckedError (core.js:9753)
    at checkBindingNoChanges (core.js:9920)
    at checkNoChangesNodeInline (core.js:13968)
    at checkNoChangesNode (core.js:13942)
    at debugCheckNoChangesNode (core.js:14771)
    at debugCheckRenderNodeFn (core.js:14711)
    at Object.eval [as updateRenderer] (AppComponent_Host.ngfactory.js? [sm]:1)
    at Object.debugUpdateRenderer [as updateRenderer] (core.js:14693)
    at checkNoChangesView (core.js:13782)
```

I'm not able to reproduce this with Firefox or Safari. The reason is that those browsers do not focus a button on click.

The only workaround I found was running `ChangeDetectorRef#detectChanges()` in the `(click)`-handler (it does not work in the `(blur)`-handler) which looks suboptimal as in our real use case this handler is provided from the outside by the parent component (a more complete example can be found at http://plnkr.co/edit/q3lLmKQl2hqSVb5dPhqt?p=preview). We could still manage to invoke `ChangeDetectorRef#detectChanges()` after the `EventEmitter#emit()` on the `Output` but that doesn't feel right and it would always cause a second change detection on every button click (even it is not necessary).
Another way to fix this is using `setTimeout(() => this.focused = false, 0);` for applying the changes on `blur` but that looks even more _dirty_.

## Expected behavior
There should not be a `ExpressionChangedAfterItHasBeenCheckedError`

## Minimal reproduction of the problem with instructions

- Open Plnkr in Chrome
- Click on button

## What is the motivation / use case for changing the behavior?
Implementation of this simple component behavior should be straight-forward. Processing of multiple events (blur and click in this example) should work with change detection out-of-the-box.

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [x] Chrome (desktop) version 65.0.3325.181
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- Platform: Mac OS 10.12.6

Others:

</code></pre>

**Comment by akloeber** [comment]
I found a better workaround by adding
```typescript
  ngOnChanges(changeRecord: SimpleChanges) {
    if (changeRecord.disabled) {
      if (changeRecord.disabled.currentValue) {
        this.focused = false;
      }
    }
  }
```

But I still think that synchronization of those events should be handled by Angular.

**Comment by divdavem** [comment]
We have a similar issue with the keyboard navigation on the datepicker in ng-bootstrap when changing month: the focused element is a day in the month, and when pressing a key leads to a month navigation, the focused DOM element is destroyed, and, in Chrome, the call to `removeNode` (which is done as part of the change detection) triggers a synchronous `focusout` event, and the `focusout` event handler changes the data model (which should be allowed), but as this is still during the change detection of the key event, the `ExpressionChangedAfterItHasBeenCheckedError` exception is thrown.

The simplified issue can be reproduced here:
https://stackblitz.com/edit/angular-bcqst5?file=src%2Fapp%2Fapp.component.html

**Comment by atscott** [comment]
Closing as resolved by using a signal for the focused state.
