### ISSUE TITLE
Change file event not fired if we select same file ?

### ISSUE THREAD

**Issue by amineparis** [angular/angular#22911]
When we select same file twice `(change)` event is not fired.

It would be nice if we have an event that is fired when file is` (selected )`

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by matsko** [comment]
It might be firing because of the dev mode running change detection twice.

However as Eric said, please have a look on stackoverflow.
