### ISSUE TITLE
how to use both less and scss  in one angular project

### ISSUE THREAD

**Issue by yytian1017** [angular/angular#22925]
In my project, I want to use both less and scss. In angular-cli.json, I can config just less or scss

    "defaults": {
        "styleExt": "scss",
        "component": {}
    }

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
