### ISSUE TITLE
How to include CLDR data for RTL languages?

### ISSUE THREAD

**Issue by shahramSo** [angular/angular#22926]
As many changes in Angular 5 to use Date, number and currency pipes for the RTL languages such as Arabic and Persian, how to include the CLDR data to show dates and numbers correctly?
Currently, all numbers display as Latin in date and currency pipes.
any Idea?
Thanks.

**Comment by matsko** [comment]
Sorry this channel is for reporting issues. Please try hopping into Angular Gitter channel or using stackoverflow to ask and someone can help answer this in detail.
