### ISSUE TITLE
6.0.0-rc.0 RxJS upgrade issues

### ISSUE THREAD

**Issue by slubowsky** [angular/angular#22937]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
As per the documentation referred to by the change log [https://github.com/angular/angular/blob/master/CHANGELOG.md](https://github.com/angular/angular/blob/master/CHANGELOG.md) at [https://goo.gl/osWFzo](https://goo.gl/osWFzo) Updating RxJS for 6.0.0-rc.0 can be done in stages. Milestone 1 is supposed to consist of simply updating your RxJs dependency. That does not work for me.

I updated my RxJS dependency to ^5.6.0-forward-compat.0 I also obviously updated my Angular dependencies to 6.0.0-rc.0
ng serve fails and my app doesn't run

```
PS D:\dev\my-app> ng serve
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-03-22T18:56:55.617Z
Hash: be6ac1d204adf2320468
Time: 11036ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 2.91 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 577 bytes [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 1.65 MB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 852 kB [initial] [rendered]

ERROR in node_modules/@angular/common/http/src/backend.d.ts(8,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/common/http/src/client.d.ts(1,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/common/http/src/interceptor.d.ts(9,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/common/http/src/jsonp.d.ts(1,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/common/http/src/module.d.ts(9,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/common/http/src/xhr.d.ts(1,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/common/http/src/xsrf.d.ts(2,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/common/src/location/location.d.ts(1,34): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/common/src/pipes/async_pipe.d.ts(9,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/core/src/application_ref.d.ts(8,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/core/src/event_emitter.d.ts(8,25): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/core/src/linker/query_list.d.ts(8,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/core/src/util/lang.d.ts(8,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/forms/src/directives/abstract_control_directive.d.ts(8,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/forms/src/directives/validators.d.ts(9,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/forms/src/model.d.ts(1,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/forms/src/validators.d.ts(9,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/router/src/config.d.ts(9,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/router/src/interfaces.d.ts(8,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/router/src/router.d.ts(10,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/router/src/router_config_loader.d.ts(9,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/router/src/router_preloader.d.ts(9,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/router/src/router_state.d.ts(9,28): error TS2307: Cannot find module 'rxjs'.
node_modules/@angular/router/src/utils/collection.d.ts(9,28): error TS2307: Cannot find module 'rxjs'.
src/app/my/my-reports/shared/my-reports.service.ts(91,45): error TS2339: Property 'headers' does not exist on type '{}'.
src/app/my/my-reports/shared/my-reports.service.ts(94,56): error TS2339: Property 'body' does not exist on type '{}'.
src/app/my/my-reports/shared/my-reports.service.ts(102,39): error TS2339: Property 'body' does not exist on type '{}'.
src/app/my/my-reports/shared/my-reports.service.ts(102,82): error TS2339: Property 'body' does not exist on type '{}'.
src/app/my/shared/thing1-info/thing1-rules/thing1-rules.service.ts(139,99): error TS2345: Argument of type '{}' is not assignable to parameter of type 'PayorRule'.
  Property 'set' is missing in type '{}'.
src/app/my/shared/thing1-rate-code/thing1-rate-code.service.ts(32,24): error TS2339: Property 'map' does not exist on type '{}'.
src/app/my/shared/thing2-search/thing2-search.service.ts(105,51): error TS2339: Property 'headers' does not exist on type '{}'.
src/app/my/shared/thing2-search/thing2-search.service.ts(106,42): error TS2339: Property 'body' does not exist on type '{}'.
src/app/my/shared/thing2-thing3/thing2-thing3.service.ts(135,29): error TS2339: Property 'status' does not exist on type '{}'.
src/app/my/shared/thing2-thing3/thing2-thing3.service.ts(136,53): error TS2339: Property 'body' does not exist on type '{}'.
src/app/my/shared/thing2-thing3/thing2-thing3.service.ts(138,32): error TS2339: Property 'ok' does not exist on type '{}'.
src/app/my/shared/thing2-thing3/thing2-thing3.service.ts(154,37): error TS2345: Argument of type '(item: Thing5Thing6) => {}' is not assignable to parameter of type '(value: Thing5Thing6) => Thing5Thing6'.
  Type '{}' is not assignable to type 'Thing5Thing6'.
    Property 'set' is missing in type '{}'.
src/app/dialog/dialog.component.ts(52,28): error TS2339: Property 'pipe' does not exist on type 'EventEmitter<string>'.
src/app/shared/caching-services/active-data.service.ts(87,37): error TS2345: Argument of type '{}' is not assignable to parameter of type 'T'.
src/app/shared/caching-services/active-list.service.ts(82,28): error TS2339: Property 'length' does not exist on type '{}'.
src/app/shared/caching-services/active-list.service.ts(84,32): error TS2339: Property 'map' does not exist on type '{}'.
src/app/shared/caching-services/caching.service.ts(41,28): error TS2339: Property 'map' does not exist on type '{}'.
src/app/shared/company-rules/company-rules.service.ts(66,44): error TS2345: Argument of type '{}' is not assignable to parameter of type 'ICompanyRules'.
  Property 'admitDiagnosis' is missing in type '{}'.
src/app/shared/company/company-detail.service.ts(86,93): error TS2339: Property 'id' does not exist on type '{}'.
src/app/shared/company/company-detail.service.ts(87,107): error TS2345: Argument of type '{}' is not assignable to parameter of type 'ICompany'.
  Property 'id' is missing in type '{}'.
src/app/shared/company/company-detail.service.ts(95,107): error TS2345: Argument of type '{}' is not assignable to parameter of type 'ICompany'.
src/app/shared/dated-resource/dated-resource.service.ts(27,37): error TS2345: Argument of type '{}' is not assignable to parameter of type 'T'.
src/app/shared/dated-resource/dated-resource.service.ts(56,32): error TS2339: Property 'map' does not exist on type '{}'.
src/app/shared/thing4/thing4.service.ts(38,32): error TS2339: Property 'map' does not exist on type '{}'.
src/app/shared/thing7/thing7-info.service.ts(73,52): error TS2345: Argument of type '{}' is not assignable to parameter of type 'IThing7'.
  Property 'id' is missing in type '{}'.
src/app/shared/location/location.service.ts(33,32): error TS2339: Property 'map' does not exist on type '{}'.
src/app/shared/thing1/thing1-info.service.ts(73,51): error TS2345: Argument of type '{}' is not assignable to parameter of type 'IThing1'.
  Property 'id' is missing in type '{}'.


webpack: Failed to compile.
```

## Expected behavior

App should run

## Environment

<pre><code>
Angular CLI: 1.7.3
Node: 9.7.1
OS: win32 x64
Angular: 6.0.0-rc.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.7.2
webpack: 3.11.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
v9.7.1

- Platform:  
Windows 10

Others:

</code></pre>

**Comment by benneq** [comment]
I used `rxjs 6 beta` and `rxjs-compat 6 beta` instead of `rxjs 5.6.0-forward-compat`. Had to fix 10 lines in my code and it worked. Maybe that works for you, too?

**Comment by slubowsky** [comment]
@benneq It actually does. All the errors shown above go away.
Unfortunately I instead had to make many changes due to the RxJS API changes to get the code to run and things aren't really working. The app starts and my initial data loads, but then as I begin clicking things and routing around, things just seem to hang (no errors in console). No way to know whats due to my quick probably in many cases incorrect changes due to RxJS API changes, whats due to possible beta version RxJS bugs, and whats due to rc.0 version Angular 6.0.0 bugs.

I'll have to debug and see whats going on. Too many changes at once, way too painful. Would be way better to be able to introduce change in a managed fashion (and yes if I had more complete tests Id probably have a better idea of where the issues were).

**Comment by benneq** [comment]
Yeah.. Angular Beta and RC releases are (often) russian roulette 😄 

At the moment it's really damn hard. Angular Beta / RC, Angular CLI Beta, Angular Material Beta, Angular Flex Beta, RxJs Beta, etc. 
I'm still stuck at beta.7, because I have not yet resolved issues with angular-cli. I just tried rc.0 with some mini project and there I had no issues with rxjs.
Maybe we have to wait another week for a "stable" combination of all those RC release dependencies.

Btw: Did you try rxjs 6 beta 0 and beta 1? Maybe the one you didn't use works.

**Comment by slubowsky** [comment]
Turns out I broke the code that fetches my authorization token when updating to new RxJS API. Fixed that, now pretty much everything seems to be working.
I am seeing a few httpClient subscriptions fail with what appear to be erroneous "Error: no elements in sequence" errors but I have seen similar behavior before after upgrading to other versions of RxJS and they turned out to be RxJS bugs that were fixed pretty quickly so I think I'll wait for another version or two before spending time trying to make things perfect.

**Comment by patrickmichalina** [comment]
@slubowsky same here. Think its still a ways off. Huge change.

**Comment by xmlking** [comment]
I upgraded angular to `^6.0.0-rc.0` and  rxjs `6.0.0-beta.1` and  rxjs-compat `6.0.0-beta.1`
I am using a lib that has following [code](https://github.com/ngxs/store/blob/master/src/of-action.ts). 
```ts
import { OperatorFunction } from 'rxjs/interfaces';
```
when I start `ng serve` I am getting following error
```
webpack: Compiled with warnings.
ERROR in node_modules/@ngxs/store/of-action.d.ts(1,34): error TS2307: Cannot find module 'rxjs/interfaces'.
```

I was expecting `rxjs-compat` could have helped in this situation

**Comment by patrickmichalina** [comment]
@xmlking same issue here... I made a script that during AOT build time, replaces `rxjs/interfaces ` with `rxjs` and everything works :) 

https://github.com/patrickmichalina/fusing-angular/blob/master/tools/tasks/seed/tmp-ng6-upgrade.ts

**Comment by IgorMinar** [comment]
This was a bug in rxjs@5.6.0-forward.compat.0 that has been fixed in -forward.compat.1. Please update rxjs
