### ISSUE TITLE
Angular Tutorial of Heroes not Loading in Firefox 60.0b5.

### ISSUE THREAD

**Issue by RobRoseKnows** [angular/angular#22938]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Tried to load the [tutorial example](https://nlvrooxxdvy.angular.stackblitz.io/) in Firefox 60.0b5 and nothing rendered. Thought it might by uBlock Origin, but after disabling and Ctrl+F5ing it still does not load.

Only error in console is:
```
Unhandled promise rejection TypeError: r.scriptLanguage is undefined
Stack trace:
generateConfig@https://c.staticblitz.com/assets/engineblock-146c780d9ccd7eca58c9775fadffeb836d7f8b198b9ddefc26cfde20a0cc7c00.js:3:12779
start@https://c.staticblitz.com/assets/engineblock-146c780d9ccd7eca58c9775fadffeb836d7f8b198b9ddefc26cfde20a0cc7c00.js:3:21846
r/<@https://c.staticblitz.com/assets/packs/preview-ebf0053a47a45e97ef59.js:1:126383
T/</<@https://c.staticblitz.com/assets/packs/common-0cb775d8f7d5cff94de1.js:1:41338
T/<@https://c.staticblitz.com/assets/packs/common-0cb775d8f7d5cff94de1.js:1:41208
a@https://c.staticblitz.com/assets/packs/common-0cb775d8f7d5cff94de1.js:1:31436
 common-0cb775d8f7d5cff94de1.js:1:41681
```

## Expected behavior

I would expect it to load the tutorial example that loads in Chrome. I asked on the Gitter and other people said it loads fine on earlier versions of Firefox, so this could be a beta bug with Firefox.

## Minimal reproduction of the problem with instructions

Use Firefox 60.0b5 64-bit version (current up-to-date beta version) and try to load the example from StackBlitz.

## What is the motivation / use case for changing the behavior?

Trying to do the tutorial.

## Environment

Angular version: 5.2.9 I believe is [what is says in StackBlitz](https://stackblitz.com/angular/nlvrooxxdvy?file=src%2Findex.html).

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 60.0b5
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: Can't find it on StackBlitz.
- Platform:  Windows 64-bit.

Others:

Windows Insider Build 17127

**Comment by gkalpak** [comment]
Does https://stackblitz.com/angular/nlvrooxxdvy work?

**Comment by RobRoseKnows** [comment]
@gkalpak The StackBlitz interface loads but the preview on the right doesn't show anything, just a white screen.

Console shows these errors (not including tracking protection blocks):

```
SecurityError: The operation is insecure.
_relay_:10
<anonymous>
https://nlvrooxxdvy.angular.stackblitz.io/_relay_:10:7
<anonymous>
https://nlvrooxxdvy.angular.stackblitz.io/_relay_:9:6
SecurityError: The operation is insecure.
preview-ebf0053a47a45e97ef59.js:1
[306]
https://c.staticblitz.com/assets/packs/preview-ebf0053a47a45e97ef59.js:1:42089
e
https://c.staticblitz.com/assets/packs/preview-ebf0053a47a45e97ef59.js:1:96
[1217]
https://c.staticblitz.com/assets/packs/preview-ebf0053a47a45e97ef59.js:1:13326
e
https://c.staticblitz.com/assets/packs/preview-ebf0053a47a45e97ef59.js:1:96
[305]
https://c.staticblitz.com/assets/packs/preview-ebf0053a47a45e97ef59.js:1:41094
e
https://c.staticblitz.com/assets/packs/preview-ebf0053a47a45e97ef59.js:1:96
[548]
https://c.staticblitz.com/assets/packs/preview-ebf0053a47a45e97ef59.js:1:126648
e
https://c.staticblitz.com/assets/packs/preview-ebf0053a47a45e97ef59.js:1:96
[557]
https://c.staticblitz.com/assets/packs/preview-ebf0053a47a45e97ef59.js:1:127188
e
https://c.staticblitz.com/assets/packs/preview-ebf0053a47a45e97ef59.js:1:96
<anonymous>
https://c.staticblitz.com/assets/packs/preview-ebf0053a47a45e97ef59.js:1:516
<anonymous>
https://c.staticblitz.com/assets/packs/preview-ebf0053a47a45e97ef59.js:1:2
ReferenceError: _preboot is not defined[Learn More]
nlvrooxxdvy.angular.stackblitz.io:11:13
<anonymous>
https://nlvrooxxdvy.angular.stackblitz.io/:11:13
<anonymous>
https://nlvrooxxdvy.angular.stackblitz.io/:11:2
```

Sorry it's kind of poorly formatted, it didn't copy-paste well.

**Comment by gkalpak** [comment]
I just tried with Firefox 60.0b6 (on Windows 10) and https://stackblitz.com/angular/nlvrooxxdvy works fine. It sounds like something is messing things up on your end (some blocker or something).
I am going to close this, since everything works as expected afaict (but feel free to continue the discussion below).

**Comment by RobRoseKnows** [comment]
Figured out what it is, setting `network.cookieBehavior` to 1 will break it somehow. That [prevents cookies coming from a different server](http://kb.mozillazine.org/Network.cookie.cookieBehavior#0).

**Comment by gkalpak** [comment]
Not sure if it is something that is "work-around-able" in StackBlitz.
cc @EricSimons

**Comment by apai4** [comment]
@RobRoseKnows Chrome has this issue if third party cookies are blocked, the solution for Chrome (without allowing 3rd party cookies globally) is making an exception for cookies from our preview domains: https://github.com/stackblitz/core/issues/162#issuecomment-357656965

I just verified this in Firefox as well, if you have third party cookies blocked you'll need to add an exception for cookies from `https://stackblitz.io` in order for the previews to work properly
