### ISSUE TITLE
Upgrade Guide Typo

### ISSUE THREAD

**Issue by GRRedWings** [angular/angular#22930]
I'm struggling to find out who manages the Angular 4 to Angular 5 upgrade guide, but there is a small typo in it.  

https://angular-update-guide.firebaseapp.com/

If I go there and select "Medium" complex, the second bullet point under "Before Updating" says
"Replace OpaqueTokens with InjectionTokens."

InjectTokens is wrong, it should be InjectToken (singular)

**Comment by gkalpak** [comment]
cc @StephenFluin

**Comment by matsko** [comment]
@GRRedWings can you put together a PR real quick?

**Comment by GRRedWings** [comment]
PR?

**Comment by matsko** [comment]
Sorry. My mistake. I assumed that this was public inside of `angular/angular`.

@StephenFluin can you fix this?

**Comment by trotyl** [comment]
https://github.com/StephenFluin/angular-update-guide/blob/99459576a7844f1dc203224e2b31ffc2d03ca697/src/app/recommendations.ts#L24

> ```Replace `OpaqueToken`s with `InjectionToken`s```

![image](https://user-images.githubusercontent.com/6059170/37815337-6e67f04a-2ea9-11e8-9d57-abecfc8480dd.png)

The content is correct, `s` is never a part of the code, maybe use a different font for `<code>` element.

**Comment by StephenFluin** [comment]
Rewritten for less ambiguity and pushed to production. 

`Replace any OpaqueToken with InjectionToken.`
