### ISSUE TITLE
Use two observables or more with *ngIf

### ISSUE THREAD

**Issue by Nexeuz** [angular/angular#22944]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Error when I try put 2 observables and and create template variable with as.

```
  <ng-container *ngIf="peliculaspopulares ? ( peliculaspopulares | async ) as peliculas   : ( peliculaskids | async ) as peliculas ">

...
</ng-container>
```

compiler.js:485 Uncaught Error: Template parse errors:
Parser Error: Conditional expression peliculaspopulares ? ( peliculaspopulares | async )  requires all 3 expressions at column 53 in [peliculaspopulares ? ( peliculaspopulares | async ) as peliculas   : ( peliculaskids | async ) as peliculas ] in ng:///AppModule/HomeComponent.html@16:16 ("

## Expected behavior

that there are no mistakes when I try to make this.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-gitter-tmmpz2

## What is the motivation / use case for changing the behavior?

For save code and does not  repeat code for other condition.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
Expected behavior, `as` is never something stands for alias, it's not an operator, but template variable assignment.

For example, `*ngIf="value$ | async as value"` means `*ngIf="value$ | async; ngFor as value"`. To be clear, there's no relationship between the variable `value` and expression `value$ | async`.

Besides, your repro link is broken.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

All what trotyl said plus handle that in the comoponent.
