### ISSUE TITLE
Angular tutorial, InMemoryWebApiModule doesn't work with angular-in-memory-web-api 0.6.0

### ISSUE THREAD

**Issue by socurites** [angular/angular#22955]
## I'm submitting a...

<pre><code>
[X] Documentation issue or request
</code></pre>

## Current behavior

Getting a error following:
RROR {body: {…}, url: "api/heroes", headers: HttpHeaders, status: 500, statusText: "Internal Server Error"}

## Expected behavior

With angular-in-memory-web-api version: 0.5.0, It works well.
But with 0.6.0, It doesn't.

## Environment

<pre><code>
Angular version: 5.2.0
angular-in-memory-web-api version: 0.6.0

**Comment by gkalpak** [comment]
`angular-in-memory-web-api@0.6.0` has a peer dependency on RxJS@^6.0.0-beta.1 (and the examples need to be updated to be compatible with that.

This will be fixed in #22872 (which will only be merged into master). You can see the example working in this preview: https://pr22872-0c678fd.ngbuilds.io/tutorial.

**Comment by gkalpak** [comment]
@genyklemberg, what do you mean? The examples have already been updated (but only in master).
`angular.io` corresponds to the stable branch (currently 5.2.x).
`next.angular.io` corresponds to the maste branch (currently containing what will shortly become 6.x).

**Comment by sebastian-marinescu** [comment]
@gkalpak he means, that it should be fixed in the official documentation: 
https://angular.io/tutorial/toh-pt6#simulate-a-data-server
or at least be mentioned there to install 
`npm i --save angular-in-memory-web-api@0.5.0`

**Comment by gkalpak** [comment]
Fait enough. Changing `npm install angular-in-memory-web-api --save` to `npm install angular-in-memory-web-api@0.5 --save` sounds reasonable.

Would any of you be up to submitting a PR with the fix?

**Comment by sebastian-marinescu** [comment]
Is there an official repo for the tour-of-heroes tutorial? I haven't found it..
