### ISSUE TITLE
StaticInjectionError - NG TEST

### ISSUE THREAD

**Issue by MichaelLazarevic** [angular/angular#22953]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Error: StaticInjectorError(DynamicTestModule)[PoolAPIService -> AuthHttp]: 
  StaticInjectorError(Platform: core)[PoolAPIService -> AuthHttp]: 
    NullInjectorError: No provider for AuthHttp!

## Expected behavior
` 
import { async, ComponentFixture, TestBed } from '@angular/core/testing';
import { ShareModule } from '../../../../share/share.module';
import { RootTableModule } from '../../../../share/table/root-table.module';
import { VehicleListComponent } from './vehicle-list.component';
import { VehicleDetailComponent } from '../vehicle-detail/vehicle-detail.component';
import { VehicleService } from '../vehicle-main.service';
import { VehicleAPIService } from '../../vehicle.api.service';
import { LocationAPIService } from '../../../location/location.api.service';
import { PoolAPIService } from '../../../pool/pool.api.service';
import { VehicleModelService } from '../../vehicle-model/vehicle-model.service';

describe('Component : VehicleList', () => {
  let component: VehicleListComponent;
  let fixture: ComponentFixture<VehicleListComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports : [
        ShareModule,
        RootTableModule
      ],
      declarations: [
        VehicleListComponent,
        VehicleDetailComponent
      ],
      providers: [
        VehicleService,
        VehicleAPIService,
        LocationAPIService,
        PoolAPIService,
        VehicleModelService
      ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(VehicleListComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should be created', (async(() => {
    expect(component).not.toBeNull();
  })));
});
`

I'm running ng test, as I'm trying to create a test framework for the project but this bug isn't one I understand, and I'm finding it hard to find similar issues online. The only time I found one, nobody replied to try and solve it, hence why I've come here.

## Environment

<pre><code>
Angular version: 5.6.0

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4
- Platform:  Windows

Others:
</code></pre>

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
