### ISSUE TITLE
HttpClient  setHeaders  Authorization .net core 2.0 + error

### ISSUE THREAD

**Issue by SkillUsing** [angular/angular#22951]
1. HttpClient  setHeaders Authorization 
2. .net core no value
3.  postman is  true
Why is that?
Please answer thank you

```
    intercept(req: HttpRequest<any>, next: HttpHandler):
        Observable<HttpSentEvent | HttpHeaderResponse | HttpProgressEvent | HttpResponse<any> | HttpUserEvent<any>> {
        console.log("拦截Api");
        console.log(`ToKen:${BaseService.token}`);
        // 统一加上服务端前缀
        let url = req.url;
        if (!url.startsWith('https://') && !url.startsWith('http://')) {
            url = "http://localhost:9492/" + url;
        }
        const newReq = req.clone({
            url: url,
            setHeaders: { Authorization: 'Bearer 1323211111111111111111111111' }
        });
        console.log(newReq);
        console.log(next);
        return next.handle(newReq).pipe(
            mergeMap((event: any) => {
                // 允许统一对请求错误处理，这是因为一个请求若是业务上错误的情况下其HTTP请求的状态是200的情况下需要
                if (event instanceof HttpResponse && event.status === 200)
                    return this.handleData(event);
                // 若一切都正常，则后续操作
                return of(event);
            }),
            catchError((err: HttpErrorResponse) => this.handleData(err))
        );
    }
```

![image](https://user-images.githubusercontent.com/19234575/37822763-5e7280ec-2ec2-11e8-8d9e-0d7184163e61.png)

![image](https://user-images.githubusercontent.com/19234575/37822840-a4dfee16-2ec2-11e8-8693-575888f5c2bf.png)

![image](https://user-images.githubusercontent.com/19234575/37822846-adbc2ec8-2ec2-11e8-8f44-4823ee0a825a.png)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by SkillUsing** [comment]
@ericmartinezr thank
