### ISSUE TITLE
Error in component styles doc regarding relative URLs

### ISSUE THREAD

**Issue by greatkeke** [angular/angular#22956]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
[Here](https://angular.io/guide/component-styles#template-link-tags) is the doc for *template link tags* , but `The link tag's href URL must be relative to the application root, not relative to the component file.` was wrong absolutely. 

## Expected behavior
In fact, the link tag's href URL must be relative to the component file instead of the application root.

## Environment

<pre><code>
Angular version: 5.2.9

**Comment by jenniferfell** [comment]
Link to PR https://github.com/angular/angular/pull/22360 is incorrect. That's unrelated.

**Comment by petebacondarwin** [comment]
This was actually fixed in https://github.com/angular/angular/commit/f8fa20d71a72d52d48454835c192daa88557ef61
