### ISSUE TITLE
App module documentation example missing app component import

### ISSUE THREAD

**Issue by kctiley** [angular/angular#22968]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The documentation at https://angular.io/guide/architecture-modules#ngmodule-metadata shows an example of an app module. There is no import for app component.

## Expected behavior

I think import app component needs to be added near top of app module if I understand correctly.

## What is the motivation / use case for changing the behavior?

n/a

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
The example is supposed to show an excerpt from the `app.module.file` showing the `NgModule` definition. Where `AppComponent` or `Logger` come from is not improtant (e.g. they could be defined below in the same file or imported from elsewhere).

But I agree that making it clear that there two some from somewhere (or that the code snippet is only an excerpt) would be better (i.e. less confusing for beginners).

PRs welcome :smiley:

**Comment by kctiley** [comment]
George, Thank you for the clarification. I appreciate your response and will try a PR next time. 
Thanks!



Klint Tiley
303.330.9577
kctiley@gmail.com

**Comment by jainanuj0812** [comment]
@gkalpak, @kctiley  Can you please help or share some docs, how we can create PRs for the docs related issues, I am not able to find it over here.

**Comment by gkalpak** [comment]
@jainanuj0812, the [general guidelines][2] on how to submit PRs still hold, of course.
For more info on how to prepare PRs for docs (and how the docs build system works) see [here][2] and [there][3].

Essentially, the content for the `Architecture > Intro to modules` guide is [here][4] and the code where the relevant code-snippet is extracted from is [there][5].

[1]: https://github.com/angular/angular/blob/910a16a1ff70682cb1c7546cfb4c527865f2e1ce/CONTRIBUTING.md#-submitting-a-pull-request-pr
[2]: https://github.com/angular/angular/blob/master/aio/README.md
[3]: https://github.com/angular/angular/blob/910a16a1ff70682cb1c7546cfb4c527865f2e1ce/aio/content/guide/docs-style-guide.md
[4]: https://github.com/angular/angular/blob/910a16a1ff70682cb1c7546cfb4c527865f2e1ce/aio/content/guide/architecture-modules.md
[5]: https://github.com/angular/angular/blob/910a16a1ff70682cb1c7546cfb4c527865f2e1ce/aio/content/examples/architecture/src/app/mini-app.ts

**Comment by jainanuj0812** [comment]
@gkalpak Thanks!

It helps :)

**Comment by kapunahelewong** [comment]
@jainanuj0812 You might also find my NgAtlanta talk helpful. It's about how to contribute to the docs and gives a general overview. Feel free to reach out with questions. :)

[My Talk](https://www.youtube.com/watch?v=OBDmJlnEWis)
[Slides](https://speakerdeck.com/kapunahelewong/contributing-to-the-angular-docs)

**Comment by jainanuj0812** [comment]
@kapunahelewong, Same story here what you have told in the starting of your talk :P. Nice talk, it really helped. Thanks for sharing.

**Comment by kapunahelewong** [comment]
Thanks @jainanuj0812. How kind of you! :D

**Comment by jenniferfell** [comment]
@jainanuj0812 Hi. How are you? Now that v6 is out, we're getting caught up on issues and PRs. Are you still interested in working on a PR for this? (no pressure) If so, how can we help? Thanks!

**Comment by dariobraun** [comment]
Hey @jainanuj0812 , I'd like to create a PR for this. Could you let me know which one of these two options you think makes more sense?

1) Add import statements for `Logger ` and `AppComponent`
2) Add another disclaimer saying something along the lines of "Note that this is only a code snippet and therefore the imports/declarations of AppComponent and Logger are not shown, even though they are necessary (for the Module to compile)"

**Comment by jainanuj0812** [comment]
@dariobraun, IMO, as this is a demo code snippet 2nd option makes more sense, and can be added as a note.

**Comment by jainanuj0812** [comment]
@Jenniferfell, count me in

**Comment by jenniferfell** [comment]
@dariobraun Option 2 sounds great!

**Comment by jbogarthyde** [comment]
I don't even think the full disclaimer is necessary, if you introduce the snippet with something like "The following code snippet illustrates the syntax of xx."
