### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by cvk435** [angular/angular#22978]
I am betting the below error while executing npm run build:universal && cd dist && node server

command. Could you please me how to resolve it.

Date: 2018-03-25T05:32:10.906Z
Hash: 93b122bd24a7d1810fea
Time: 18719ms
chunk {0} main.bundle.js (main) 773 kB [entry] [rendered]
chunk {1} styles.bundle.css (styles) 0 bytes [entry] [rendered]
C:\Angular\ditchit-website_ditchit_appscrip-c383421aa57f\node_modules\ng2-cloudinary\dist\esm\src\cloudinary-image.service.js:1
(function (exports, require, module, __filename, __dirname) { import { Injectable } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.flAF (C:\Angular\ditchit-website_ditchit_appscrip-c383421aa57f\dist\dist-server\main.bundle.js:1:393730)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
