### ISSUE TITLE
toh-pt6 does not compile

### ISSUE THREAD

**Issue by phpwalter** [angular/angular#22977]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I went through the tutorial up to HTTP "Get heroes with HttpClient" section
The code stops compiling at this point.

I completed the tutorial and it still fails to compile.

After downloading the examples and getting the latest from GITHUB, I discovered that the latest versions of dependents is the issue.

I replaced my "package.json" with the one from the tutorial DL and now the code works.

## Expected behavior

Working example

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

This is my package file that fails

{
  "name": "angular-tour-of-heroes",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "angular-in-memory-web-api": "^0.6.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.3",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}

</code></pre>

**Comment by zyzof** [comment]
This is due to breaking changes in the latest (0.6.0) version of in-memory-web-api.

A workaround is to install with `npm install in-memory-web-api@5.4.0 --save`.

Probably the [tutorial documentation](https://github.com/angular/angular/blob/master/aio/content/tutorial/toh-pt6.md) should be updated to mention which version to install based on the version of Angular being used.

Related: https://github.com/angular/in-memory-web-api/issues/189

**Comment by bogdanmanate** [comment]
@zyzof  do you mean npm install angular-in-memory-web-api@0.5.4 --save ?

**Comment by zyzof** [comment]
@bogdanmanate yup, thanks. I typed the wrong version number. Have updated my comment.

**Comment by IgorMinar** [comment]
this has been fixed already by #23242
