### ISSUE TITLE
Undefined Variable When Properly Defined

### ISSUE THREAD

**Issue by xerofoify** [angular/angular#22970]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I am new to Angular and have to do so work for a school assignment. I have  a few components that all use a Employees class and only one complains when I deference it with a value being undefined. 

## Expected behavior

Have factory creation work in all methods.

## Minimal reproduction of the problem with instructions
 I will be glad to zip my code and send it. It's hard to reproduce outside of the app.
Afterwards you go employeescreate in the main menu and go to web console. The e variable will be undefined but the other components have no issues with variablename: Employee.  For example one
component has this line:
private e: Employee;
and the other non create component:
private selectedEmployee: Employee;

## What is the motivation / use case for changing the behavior?

To fix the issues with angular rendering in current versions of Firefox on Linux and
factory creation issues.

## Environment
<pre><code>
Angular version: X.Y.Z

 5.2.9 
Seems the most current version at least to my knowledge. 
Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version  64.0.3282.167  64 bit
- [X ] Firefox version 59.0.1 64 bit
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
v6.11.4
- Platform:  
Linux 
Ubuntu 17.10 Up to Date. 
Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by xerofoify** [comment]
I am not asking for support. It's a bug. Clearly how does:
private e: Employee;
cause issues when I importing the files correctly and it works in all other components.

**Comment by pkozlowski-opensource** [comment]
@xerofoify if you believe that there is a bug in the framework, please open a new issue following our issue template (most importantly - providing a minimal reproduce scenario). We can't confirm / fix bugs that we can't reproduce...

**Comment by mlc-mlapis** [comment]
@xerofoify ... there were already hundreds cases when others reported some hypothetical issues but after creating a reproduction demo of the problem they found out that the problem was not related to Angular at all.
