### ISSUE TITLE
All locales from @angular/common/locales contain extra comma after ['AM', 'PM'] array

### ISSUE THREAD

**Issue by marzecm** [angular/angular#22988]
Hi,

I'm  importing many locales from @angular/common/locales (en, fr, fr-CA, ...) and I'm getting 
Uncaught TypeError: Cannot read property 'visitExpression' of undefined raised by zone.js at runtime. 

## Current behavior
At runtime zone.js raises an error
Uncaught TypeError: Cannot read property 'visitExpression' of undefined

## Expected behavior
Can use locales without errors at runtime. 

## Personnal investigation
It seems that the reason is that default object being exported from locale file contains 2 extra commas at default[2] which is right after  ['AM', 'PM'],,
This extra comma is present in ALL files from @angular/common/locales.

example: https://github.com/angular/angular/blob/master/packages/common/locales/fr.ts at line 21-22 commas should be removed

in english version https://github.com/angular/angular/blob/master/packages/common/locales/en.ts
the extra comma is also present at default[1] at line 22

Can you please clean those files from this extra comma?

**Comment by trotyl** [comment]
It's by design, `[42, ]` is equivalent to `[42, undefined]` but saved many space.

**Comment by trotyl** [comment]
Please provide reproduction for any of your problem.

**Comment by vicb** [comment]
The issue is not with the interpreter: `[42, ]` and `[42, undefined]` will work equally well. Without a repro we can not know what is wrong.
_However our plan is to change the sparse array and have explicit `undefined` because it already caused troubles with some webpack plugins_`
