### ISSUE TITLE
Uncaught Error: Template parse errors: No provider for NgSwitch

### ISSUE THREAD

**Issue by Vicky443** [angular/angular#22984]
quite strange if NgSwitch is in build directive of angular so why am I getting this error, 
even I try to include NgSwitch directive manually but the is same.

here are my project dependencies

"dependencies": {
    "@angular/animations": "^5.2.9",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@ionic/storage": "^2.1.3",
    "bootstrap": "^4.0.0",
    "codelyzer": "^4.1.0",
    "core-js": "^2.4.1",
    "ngx-bootstrap": "^2.0.3",
    "ngx-loading": "^1.0.14",
    "ngx-toastr": "^8.3.0",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by keyfu** [comment]
en mi caso me pasó que la directiva *ngSwitchDefault no estaba dentro de la etiqueta div que contenía la directiva [ngSwitch]. Debes fijarte que dentro de [ngSwitch] encierre a *ngSwitchCase y *ngSwitchDefault. For example: 

`<div [ngSwitch]="type">
  <div *ngSwitchCase="'details_customer'">
    <div *ngFor="let o of items; let i= index" [ngClass]="class_item">
      <span [ngClass]=" i === 1 ? 'uk-text-bold uk-text-uppercase' : '' ">{{ o }}</span>
    </div>
  </div>
  <div *ngSwitchDefault>
    <span *ngFor="let o of items" [ngClass]="class_item">
      {{ o }}
    </span>
  </div>
</div>`

**Comment by leandrw** [comment]
In my case, I was trying use `[ngSwitch]` as a attribute of `<ng-template>`
