### ISSUE TITLE
Bazel build too slow on Mac Mini

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#22985]
My home computer is a mid-range Mac - 2 GHz Intel Core i7 w/ 16G RAM

A clean `bazel build //...` takes
`INFO: Elapsed time: 1884.566s, Critical Path: 310.00s`
which is not acceptable.

Likely culprits:
- Mac sandboxing still?
- ESM5 actions don't use worker
- Three TS emit flavors don't share any work - is it possible to just emit one ts.Program three times?
- Too many input files to actions? Maybe the size of node_modules filegroup again. Push more on Bazel team to get a filegroup made of a TreeArtifact?
- Profiling and tuning of the critical path, once I figure out how to display it

**Comment by jakeleventhal** [comment]
https://github.com/bazelbuild/bazel/issues/8230

**Comment by alexeagle** [comment]
That's funny timing, I just switched back to that same machine today. Likely fix is in rules_nodejs where we'll provide one input per node module (a TreeArtifact, or directory) rather than individual files. Closing here as I don't think this is an Angular issue.
