### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked

### ISSUE THREAD

**Issue by ezra2310** [angular/angular#22987]
Hi All,

I have issue with "ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked".
Im using the same component dynamically with the different layout render. 
For example, If single layout  the my component object hold array[0] value. if double layout  then my my component object hold array[0] & array[1] value, if triple layout  then my my component object hold array[0] & array[1] & array[1] value. and so on.

**var comp = this._cfr.resolveComponentFactory(DynamicComponent);
var expComponent = this.addPageControlContainer.createComponent(comp);**

The above code are using for render the component in UI.

In page loaded the Single layout component with the value of array[0] and render successfully, then i tried to load the same component into bootstrap popup with double section component with the value of array[0] &   array[1] then it throw the ExpressionChangedAfterItHasBeenCheckedError.

Note : The single and double layout will have the different values.

Please help us by anyone ;-(

**Comment by LinBoLen** [comment]
manual call changeDetectChangeRef.detectChange(). 

btw. really fell annoyed when there have ExpressionChangedAfterItHasBeenCheckedError. angular should't exist this error. it agains with common sense in programming.

**Comment by diicar** [comment]
https://blog.angularindepth.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4

**Comment by ezra2310** [comment]
Hi,
I tried with call changeDetectChangeRef.detectChange() manual.
Here what the problem main problem is In DOM page with array[0].flag = true and then i will call the same  competent in popup means the  array[0].flag come as 'undefined' value and  array[0] &  array[1] will hold some other values.
In same DOM object can't able to use multiple component?

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
