### ISSUE TITLE
"Samsung Internet" browser on tablet Title.setTitle() delay

### ISSUE THREAD

**Issue by esolCrusador** [angular/angular#22992]
## I'm submitting an issue with "Samsung Internet" browser on tablet. 

When I am using Title.ts (https://github.com/angular/angular/blob/master/packages/platform-browser/src/browser/title.ts). 
And call titleService.setTitle("Some Title 1"), when I check titleService.getTitle() I get "Some title 1". But actually title in browser is not changed. But when I navigate to another route, "Some title 1" is set as title in browser. On next page I set "Some title 2" and when I navigate to 3-rd page, "Some title 2" is being set as title of the page.

<pre><code>
[x ] Bug report 
</code></pre>

## Current behavior
Title in "Samsung Internet" browser  is delayed on one navigation. It means when I go to "page 1" nothing is set, when I go to "page 2" - than title is set to "page 1", when I go to "page 3" then "page 2" title is set.

## Expected behavior
Title is being set for current page.

## Minimal reproduction of the problem with instructions
0. Use "Samsung Internet" browser.
1. Resolve title service in root component. 
2. Use titleService.setTitle("") method.

## Environment

<pre><code>
Angular version: 5.2.3

Browser:
- [x ] Samsung Internet (Android) version 6.4.10.5
 
</code></pre>

**Comment by vicb** [comment]
Closing as no repro provided.
