### ISSUE TITLE
Compatible issue with Angular 4 and Bootstrap 4

### ISSUE THREAD

**Issue by KSANTHOSHKUMA** [angular/angular#22990]
HI all
I am Working with Angular 4 , I am trying to use Bootstrap 4 in my application.
but getting the following error in command prompt.

**Versions of @angular/compiler-cli and typescript could not be determined.
The most common reason for this is a broken npm install.

Please make sure your package.json contains both @angular/compiler-cli and typescript in
devDependencies, then delete node_modules and package-lock.json (if you have one) and
run npm install again.**

Package.json file is as below

```
{
  "name": "cli-test4",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "@types/jquery": "^2.0.47",
    "bootstrap": "^4.0.0",
    "bootstrap-grid": "^3.0.1",
    "bootstrap-reboot": "^0.1.1",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "jquery": "^3.3.1",
    "lodash": "^4.17.4",
    "moment": "^2.21.0",
    "ng2-tooltip": "0.0.7",
    "ngx-quill": "^1.6.0",
    "popper.js": "^1.12.9",
    "raw-loader": "^0.5.1",
    "rxjs": "^5.1.0",
    "web-animations-js": "^2.2.5",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.3",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "2.5.38",
    "@types/lodash": "^4.14.65",
    "@types/node": "~6.0.60",
    "angular-2-dropdown-multiselect": "^1.2.0",
    "codelyzer": "~2.0.0",
    "css-loader": "^0.28.1",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "raw-loader": "^0.5.1",
    "script-loader": "^0.7.0",
    "source-map-loader": "^0.2.1",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}
```

**Comment by KSANTHOSHKUMA** [comment]
@trotyl , do you know any solution for this.......

**Comment by benneq** [comment]
Update your project, or downgrade angular-cli.

angular-cli 1.7.x was built for angular 5.x

Additionally you have compiler-cli 5.x, which is part of angular 5.x. But the rest of your angular deps is 4.x

**Comment by KSANTHOSHKUMA** [comment]
thanks @benneq , will try and update you shortly

**Comment by benneq** [comment]
And you should use Typescript 2.6 for angular 5.2, or Typescript 2.3 for angular 4.2

**Comment by KSANTHOSHKUMA** [comment]
@benneq, working on your two comments, will update you shortly

**Comment by KSANTHOSHKUMA** [comment]
@benneq, worked on your comments and run **ng serve** but get the following error                                      **You seem to not be depending on "@angular/core". This is an error.**

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by KSANTHOSHKUMA** [comment]
@ericmartinezr , we have working on it from 2 days but there is no solution for it... please let me know what to do,,,,,,,, find the stackoverflow link below which i was posted                                [](https://stackoverflow.com/questions/49489545/angular-4-compatibility-issue-with-bootstrap-4/49490070#49490070)

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
