### ISSUE TITLE
TSification: mark fields as private/protected

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#2300]
We have a convention from AtScript of prefixing privates with underscore. This is also needed so the ts2dart emit produces "private" fields/methods in Dart.

We should mark these actually private, so TypeScript can enforce it.

Notes:
- could use ts2dart as a linter to warn if a field in `.ts` has underscore prefix but isn't private
- sometimes we access these variables from outside the class, pretending that the semantics of underscore-prefix is that it's "module-private"

**Comment by vicb** [comment]
Note that some fields are `_prefixed` but not private according to the TS definition: they are accessed by classes/functions in the same file. 

I have used this convention at a few places (and I think other have too) having in mind the Dart definition of private, ie private member are library private in Dart (they can be accessed from within the same library which is essentially the same file in Angular as we use a 1-1 mapping)

**Comment by willbuck** [comment]
I wouldn't mind taking a crack at this, I'll get started and check back here if I have questions :)

**Comment by alexeagle** [comment]
See https://github.com/angular/ts2dart/issues/278
We have an option you could enable:
https://github.com/angular/angular/compare/master...alexeagle:underscore?expand=1#diff-cb068e9a6a1837586e67d28648bf2067R18

But this enforces too much. We don't have a good answer for marking fields/methods in TS as 'may be accessed anywhere in this file', we cannot currently make them private.

In the meantime, a good next step would be a tslint check in the angular repo that any private method starts with underscore. It's better to enforce this way since TS-only contributors will still have the enforcement.

**Comment by gilamran** [comment]
@alexeagle I've created a PR on the lint thing: https://github.com/angular/angular/pull/5043

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
