### ISSUE TITLE
preserveWhitespaces doesn't update the template nor metadata file

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#23013]
## I'm submitting a...

<pre><code>
[] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Setting `preserveWhitespaces: false` seems to have no effect on templates tag and metadata file. This is a bit of a problem when wanting to ship a library.

```ts
@Component({
	template: "foo   bar"
})
export class MainComponent {}
```

tsconfig.json
```json
"angularCompilerOptions": {
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "preserveWhitespaces": false,
}
```

Compiling directly using the Angular Compiler CLI
```sh
$ node_modules/.bin/ngc -p tsconfig.json
```
Will output the below:
```js
import { Component } from "@angular/core";
var MainComponent = /** @class */ (function () {
    function MainComponent() {
    }
    MainComponent.decorators = [
        { type: Component, args: [{
                    template: "foo   bar"
                },] },
    ];
    /** @nocollapse */
    MainComponent.ctorParameters = function () { return []; };
    return MainComponent;
}());
export { MainComponent };
```

```metadata file
"arguments": [
	{
		"template": "foo   b2ar"
	}
]
```

## Expected behavior
Whitespaces to be removed.

## Environment
```
Angular version: 5.2.9
Typescript: 2.6.2 
Node version: v8.9.1
Platform:  Windows
```

**Comment by trotyl** [comment]
`preserveWhitespaces` is only for leading or trailing spaces, not for inner space of your content.

**Comment by alan-agius4** [comment]
@trotyl not according to the documentation https://angular.io/api/core/Component#preserveWhitespaces

**Comment by trotyl** [comment]
I got your point, you mean that the two spaces should be transformed into one space, right?
But the `preserveWhitespaces` is an compiler stuff and only meant for compiling (generating `ngfactory`, the metadata re-writing is the job of `tsickle`, and there is not even a template parsing phase for that.

**Comment by alan-agius4** [comment]
Yes, that's my point. So with that in mind, that's why Angular Material have `preserveWhitespaces: false` for each component other than tsconfig.
