### ISSUE TITLE
Validators for Input type File 

### ISSUE THREAD

**Issue by aakashbanerjee** [angular/angular#23011]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Angular does not provide basic validators for input type = file as of current version. 
1. Validator to make a file input field required
2. Validator to restrict file type
3. Validator to restrict file size

## Expected behavior

When a input type = file is used either in reactive or template driven forms it would be great if Angular supports or provides out of the box directives/validators to make a intput type = file field Required.
Also to restrict certain file types and file sizes. Currently these basic client side validations for input type = file are not supported officially.

## Environment

<pre><code>
Angular version: 5.1.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.3.0  
- Platform:  Mac, Linux, Windows

Others:

</code></pre>

**Comment by trotyl** [comment]
This is infeasible until https://github.com/angular/angular/issues/7341 lands first.

**Comment by kara** [comment]
Let's bundle this with #7341 since they are related.
