### ISSUE TITLE
Add PR check by tslint rules for CI

### ISSUE THREAD

**Issue by splincode** [angular/angular#23019]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I began to notice a lot of typos in the code and inconsistencies in the commits. Especially in the documentation. Also, when people send their PRs, they do not check the tslint rules (and somewhere they do not put spaces, but somewhere they put it).

![2ae33a1f-f523-44e7-8d4b-2a01af5a4e7a](https://user-images.githubusercontent.com/12021443/37967465-1d7df6c4-31d4-11e8-803a-5f4509ca4253.jpg)

**Comment by aravindfz** [comment]
@gkalpak can I fix this typos?

**Comment by gkalpak** [comment]
```
+------------------------------------------------+
| Permission granted to @aravindfz to fix typos. |
\___  ___________________________________________/
    |/
  🤖
```

**Comment by petebacondarwin** [comment]
So I think when we move all the example code to `<code-example path="..." region="...">` then this will go away because the examples themselves are linted.
I don't think the effort to parse the content for code blocks and then to identify if they are typescript and finally to run them through tslint is worth it.

**Comment by petebacondarwin** [comment]
Most code snippets now come from external `<code-example>` which provides lint checking.
