### ISSUE TITLE
Need API to get an array with all available locales 

### ISSUE THREAD

**Issue by angelasrc** [angular/angular#23022]
In my app I need to list in a dropdown all available locales in @angular/common/locales

**Comment by dawidgarus** [comment]
If you use webpack You can do something like this:
```js
var req = require.context('null-loader!@angular/common/locales', false, /\.js$/);
var locales = req.keys(); // array of locales in form: './xx-XX.js'
```
`null-loader` is here so the locales won't be added to the bundle.
Unless You actually want to include and register all locale data, then:
```js
var req = require.context('@angular/common/locales', false, /\.js$/);
req.keys().forEach(locale => registerLocaleData(req(locale)['default']));
```

**Comment by vicb** [comment]
@angelasrc usually people have a list of locale they want to support and start from that.

In your case, it seems like you want to support all locales. Those locales are defined by the CLDR and may change in future releases. Anyway you can check the packages installed via the `cldr:...` in the gulp task to have more information.

Anyway this is a support and github is not the place for support request.

--

Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
