### ISSUE TITLE
Run DDC analysis as part of CI build

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#2303]
DDC is the new compiler for Dart that's more strict than dart2js. It can catch more type errors than we are currently catching with `dartanalyzer`.

## Proposal

Introduce an experimental new build job in addition to the existing `stable` and `dev` jobs.

**Comment by yjbanov** [comment]
pushing to alpha-29

**Comment by naomiblack** [comment]
lower priority. Yegor has a PR in progress but moving back to backlog for now.
