### ISSUE TITLE
Pipeable operator for unsubscribing from observables in the components

### ISSUE THREAD

**Issue by smnbbrv** [angular/angular#23038]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

For every observable I consume in the components I need to manually unsubscribe from it on component destruction.

What does it mean:
1. For every subscription I need to create a property on a component (or an array of those subscriptions)
2. In `ngOnDestroy` I need to unsubscribe from all subscriptions above

Normally this is a little bit painful. That's why I have a [helper library](https://github.com/smnbbrv/ngx-rx-collector) that creates a pipeable operator that tracks the component destruction and kinda extends standard `takeUntil` pipeable:

```ts
export function untilDestroyed<T>(componentInstance: any, destructorName = 'ngOnDestroy'): MonoTypeOperatorFunction<T> {
  if (!componentInstance[metaProperty]) {
    const originalDestructor = componentInstance[destructorName];

    if (!originalDestructor && aot) {
      console.warn('untilDestroyed limitation: ngOnDestroy is not present on the component which is a problem for AoT. See https://github.com/angular/angular/issues/16023 for more details');
    }

    componentInstance[metaProperty] = new Subject();

    componentInstance[destructorName] = function() {
      if (originalDestructor) {
        originalDestructor.call(componentInstance);
      }

      componentInstance[metaProperty].next();
      componentInstance[metaProperty].complete();
    };
  }

  return takeUntil(componentInstance[metaProperty]);
}
```

Everything is cool, it is really comfortable to use as

```ts
interval(1000).pipe(untilDestroyed(this)).subscribe(console.log.bind(console));
```

where `this` is a component instance.

But here comes AoT and forces to create an empty `ngOnDestroy` according to this issue https://github.com/angular/angular/issues/16023.

## Expected behavior

1. As long as now RxJS is very flexible with those pipeables, can we have a similar **standard** pipeable shipped by angular?
2. Can we embed this pipeable under the hood to bind to the component destructor that one is not forced to write `ngOnDestroy`?

## What is the motivation / use case for changing the behavior?

I need to manually unsubscribe from every observable in `ngOnDestroy`.  Even using the custom pipeable I still need to create an empty `ngOnDestroy`. This could be done in a way better manner

## Environment

<pre><code>
Angular version: >=5.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by bcandullo** [comment]
I dig that helper you've created. Have you tried creating a base component to handle this which would automatically invoke the `ngOnDestroy` for sub components? Pseudo example:

```
export abstract class DestroyableComponent {
  protected subscriptions: Subscription[] = [];
  protected subscribe(sub: Subscription[]) {
    this.subscriptions.push(sub);
  }
  protected ngOnDestroy() {
    this.subscriptions.forEach(s => s.unsubscribe());
  }
}

class MyComponent extends DestroyableComponent {
  constructor() {
    super();
    this.subscribe(service.getObservable());
  }
  // ngOnDestroy .. who needs it?
}
```

**Comment by bcandullo** [comment]
I agree, especially about #3. It seems the operator is elegant and most effective when presented with the alternatives, I’d love to see it implemented.

**Comment by wulfsberg** [comment]
I was half on my way to propose a standard Observable which fires when the component is destroyed, so we could .takeUntil that, but creating it as a pipe would be more elegant. Now, if we could then also get `@Input` as observables using this pipe... :-)
We definitely need a more elegant way to handle Observables on destroy, and this sounds like a good idea for it.

**Comment by ericmartinezr** [comment]
Haven you seen this PR https://github.com/angular/angular/pull/20682 (See the issue referenced for more discussion on this matter)? Is it what you're asking for?

**Comment by smnbbrv** [comment]
@ericmartinezr yes, it is a good solution. I would be happy if this pull request gets merged / released. Both solutions could co-exist together, still

**Comment by cedvdb** [comment]
I personally use this 

```
// utility class to unsub from observable
export abstract class AutoUnsub implements OnDestroy {

	_destroy$ = new Subject<void>();

	constructor() { }

	ngOnDestroy() {
		this._destroy$.next();
		this._destroy$.complete();
	}
}
```

then in my component extending the class
` takeUntil(this._destroy)`

Ultimately I think we should have a `@Observable` that'd do everything it the background.

**Comment by amcdnl** [comment]
This would be awesome to have implemented but I think in a more generic way the ability to listen in on lifecycle events in things like decorators would be a even better improvement. For example:

```
export function MyDecorator() {
   return function(target: any, name: string, descriptor: TypedPropertyDescriptor<any>) {
      target.events.pipe(filter(event => event instanceof OnDestroy)).subscribe(() => {});
   }
}
```

Similar syntax to what the router uses with `events` and filtering techniques this would allow developers to listen for events in the component lifecycle and thus making decorators like mentioned here possible.

A nice to have would be the ability to get the `injector` off the target too.

**Comment by NetanelBasal** [comment]
+1

**Comment by Bjeaurn** [comment]
Is there any status updates on this issue/proposal? Currently seeing the referenced issues being closed, but this one is still open? Is there any progress on Lifecycle Hooks as Observables, or able to extend lifecycle hooks in PipeOperators?

**Comment by MickL** [comment]
I would rather like to see this happen instead: https://github.com/angular/angular/issues/10185

**Comment by Franki1986** [comment]
Back in 2020, is there still no way to auto unsubscribe if a component is destroyed?

**Comment by Bjeaurn** [comment]
Yes there is, if you use `AsyncPipe`. It's been there "since 2018."

**Comment by smnbbrv** [comment]
How does async pipe help the discussion?

**Comment by Franki1986** [comment]
I was also thinking what AsyncPipe has to do with this?

**Comment by Bjeaurn** [comment]
> auto unsubscribe if a component is destroyed?

AsyncPipe does this for you. But unfortunately, still no lifecycle hooks provided by the framework we can hook into no.

**Comment by fabioemoutinho** [comment]
@pkozlowski-opensource is it possible we introduce something like a `@AutoUnsubscribe() myObs$ = ...` that includes the observable into the logic view, and then when ngOnDestroy is called, it looks at the subscriptions added in logic view and unsubscribes them? I was thinking of something similar that was done for `@Output()`

**Comment by JeanMeche** [comment]
[This PR](https://github.com/angular/angular/pull/49154/files#diff-508a78c7ae7456260190375c3b624cdd2fd5219aee48375c9d848ea2f3f95395) will land a `takeUntilDestroyed` operator !

**Comment by JeanMeche** [comment]
The `takeUntilDestroyed` operator is available since v16.
