### ISSUE TITLE
Are there Fetch Api's provided by Angular ?

### ISSUE THREAD

**Issue by rahulrsingh09** [angular/angular#23033]
My app uses integrated auth using negotiate authorization scheme (WWW-Authenticate: Negotiate). Both the app UX and API require integrated authorization. 
In the latest build of Edge this dosent work and they need to send those requests via fetch API. 

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11018116/

Is there any possibility of Fetch in Angular

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by gkalpak** [comment]
So, currently there is no built-in way to use `fetch` in `HttpClient`.

Although I haven't tried it, you could probably provide your own [HttpBackend][1] for `HttpClient` to use, which could use `fetch()` under the hood. For reference, here is the current implementation for the [HttpXhrBackend][1] that is used by `HttpClient`. 

[1]: https://github.com/angular/angular/blob/5.2.9/packages/common/http/src/backend.ts#L29-L41
[2]: https://github.com/angular/angular/blob/5.2.9/packages/common/http/src/xhr.ts#L61-L339
