### ISSUE TITLE
Lazy loading is used for each page, resulting in too slow compilation speed when ng serve is developed.

### ISSUE THREAD

**Issue by llkui** [angular/angular#23039]
![1522231064 1](https://user-images.githubusercontent.com/22491062/38022249-968c6324-32b1-11e8-8b4c-8499b4c16c0a.jpg)

How do I optimize the project？

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
