### ISSUE TITLE
get error "JSON is not defined "

### ISSUE THREAD

**Issue by hungvu2803** [angular/angular#23035]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I use angular-cli to develop my project.
my project works well but after I use "AfterViewChecked" , sometimes  I get a error
```
ERROR ReferenceError: JSON is not defined
    at debugCheckAndUpdateNode (core.es5.js:13158)
```

![error](https://user-images.githubusercontent.com/4714057/38015764-0462fae0-3297-11e8-8a58-8d847fa75d4a.png)

## Environment

<pre><code>

@angular/cli: 1.3.2
node: 6.11.2
os: win32 x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.3.2
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6

Browser:
- [x ] Chrome (desktop) version 65.0.3325.181
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.2  
- Platform:  Windows 

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
