### ISSUE TITLE
keep changes for next animation (angular animation)

### ISSUE THREAD

**Issue by labyed** [angular/angular#23043]
when i execute another animation, it don't work, the element get back to his previous position
```
animations: [
    trigger('robotsMove', [
      state('down', style({
        bottom: '7%'
      })),
      state('left', style({
        bottom: '7%', // i have to precise it so like that the animation work 
        //left: '{{currentPosition1}}',// not working
        transform: 'translateX(-1vw)'// the problem is i wiil trigger this animation multiple time
      })),
      state('right', style({
        bottom: '7%',
        //left: '{{currentPosition2}}',
        transform: 'translateX(1vw)'
      })),
      transition('* => down', animate('4000ms ease-in')),
      transition('* => right', animate('500ms ease-in')),
      transition('* => left', animate('500ms ease-in'))

    ])
  ]
```
https://stackoverflow.com/questions/38003068/angular-2-animation-translate3d-from-the-current-position

**Comment by matsko** [comment]
@labyed please add a stackblitz demo so we can investigate.

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
