### ISSUE TITLE
compiler.umd.min.js causes exception when loaded in browser

### ISSUE THREAD

**Issue by elijulian** [angular/angular#23046]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When the code from compiler.umd.min.js is loaded in the browser the following exception is thrown:
```
Uncaught SyntaxError: Invalid regular expression: /[^ 

	áš€á Žâ€€-â€Š  â€¯âŸã€€﻿]/: Range out of order in character class
    at new RegExp (<anonymous>)
    at compiler.umd.min.js:110
    at compiler.umd.min.js:6
    at compiler.umd.min.js:6
```

## Expected behavior

The script should successfully load in the browser

## Minimal reproduction of the problem with instructions

create a minimal npm project with all the basic angular dependencies, and place the following in the index.html in the app root:
```<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Test App</title>
    <script src="../node_modules/@angular/compiler/bundles/compiler.umd.min.js"></script>

</head>

<body id="body">
test test
</body>

</html>
```

## Environment

<pre><code>
Angular version: 4.4.5 and on

Browser:
- [x] Chrome (desktop) version 65.0.3325.181
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 59.0.2
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
Can't reproduce: http://plnkr.co/edit/YRxJ4kSey17qs1Te0TJX?p=preview

Search for the existing issues - in cases I'm aware of the issue was that the build toolchain was modifying the original files

**Comment by elijulian** [comment]
Thanks @pkozlowski-opensource - I also had trouble reproducing it in Plunker but the problem persists when building a project locally. In the case I am discussing, I am using the compiler.umd.min.js, do no build toolchain is modifying the files - this is the file that is provided by angular

**Comment by pkozlowski-opensource** [comment]
> I also had trouble reproducing it in Plunker but the problem persists when building a project locally. In the case I am discussing, I am using the compiler.umd.min.js, do no build toolchain is modifying the files - this is the file that is provided by angular

I think that you should double-check this assumption. I _think_ that part of your toolchain _is_ modyfing_ the file in question. Maybe try to compute its hash directly from node_modules and then another hash / checksum of what is served in a browser.

Again, we had several similar reports and in all cases it _was_ a build modyfing a file. In any case we will need a minimal reproduce if you still believe that our distribution is broken.

**Comment by elijulian** [comment]
package json:
```{
  "name": "test",
  "version": "1.0.0",
  "description": "a test to play with",
  "main": "index.js",
  "scripts": {
    "test": "test"
  },
  "author": "Eli Julian",
  "license": "ISC",
  "dependencies": {
    "@angular/compiler": "^5.2.9",
    "@angular/core": "^5.2.9",
    "typescript": "^2.7.2"
  }
}
```

index.html:
```<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Test App</title>
    <script src="node_modules/@angular/compiler/bundles/compiler.umd.min.js"></script>

</head>

<body id="body">
test test
</body>

</html>
```

run npm install, open index.html in browser.

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/20109

**Comment by IgorMinar** [comment]
I tried to repro with https://stackblitz.com/edit/angular-mk6xbz but I can't reproduce this either.

**Comment by IgorMinar** [comment]
I tried to repro this locally following [instructions above](https://github.com/angular/angular/issues/23046#issuecomment-377022006) with Chrome 65 and Safari 11.0.3 (13604.5.6) and can't repro it.

If you can still repro this problem please open a new issue and provide more detailed repro instructions.
