### ISSUE TITLE
Adding test documentation and example for component injectors

### ISSUE THREAD

**Issue by karllhughes** [angular/angular#23042]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
There are examples for how to implement [component injectors](https://angular.io/guide/hierarchical-dependency-injection#component-injectors) in the section of the docs on Hierarchical Dependency Injection, but they do not cover examples or guidance for testing services injected in this manner.

## Expected behavior
I expected to be able to provide the service that I wanted to inject into the `configureTestingModule` method of the `TestBed`, but that didn't work. Upon further experimentation, I realized that it could be done with the `overrideComponent` method as so:

```
TestBed.overrideComponent(
  MyComponentUnderTest,
  {set: {providers: [
    {provide: MyRealService, useClass: MyMockService}
  ]}}
);
```

## Minimal reproduction of the problem with instructions
Go to the docs available here: https://angular.io/guide/hierarchical-dependency-injection#component-injectors

Or the live example: https://angular.io/generated/live-examples/hierarchical-dependency-injection/stackblitz.html

There are clearly no tests or docs on how to implement tests for component injectors.

## What is the motivation / use case for changing the behavior?
Because component injectors aren't mocked/tested the same way as module injectors, I think a little extra documentation is warranted.

I'm happy to make a PR, but I'm not sure where the docs code is kept. It doesn't appear to be in this repo.

## Environment

<pre><code>
Angular version: 6.0.0-rc0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by kapunahelewong** [comment]
@karllhughes This would be a great addition to the docs and PRs are always welcome if you're still up for it. It might be easier once #28700 has landed, however. We're still going to be adding the visibility decorators (like `@Host()`, etc.), but that rewrite will really dive into `ElementInjector` trees. The examples for it might also provide a jumping off point for testing. I'd love to hear your thoughts. 🌈😊

**Comment by mgechev** [comment]
Thank you for the proposal for improving Angular.

I'd suggest to keep this as community documentation given the insufficient votes label.
