### ISSUE TITLE
Date Pipe should support OS date format settings to match native HTML date inputs

### ISSUE THREAD

**Issue by ghost** [angular/angular#23056]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Angular Date Pipe currently uses a language string to set the date format. 

## Expected behavior

Angular Date Pipe should be able to use OS date format to set the date format.

## Minimal reproduction of the problem with instructions

When a date is piped inside a template: ```<p>{{someDate | date}}</p>``` in our current implementation we use the OS language (navigator.language) to provide the language string to Angular date pipe but when we compare the output with an ```<input type="date">``` in the same template, the results produce different formats if the OS language and OS date formats do not reflect one another.

## What is the motivation / use case for changing the behavior?

Enterprise business users who travel and wish to keep their OS in their native language but wish to set the date format to match the place they currently reside. Support for native HTML date inputs is key for the web and having this disparity causes confusion for end-users of the application.

## Environment

<pre><code>
Angular version: 2.4.0

Yes

Browser:
- [x] Chrome (desktop) version 65
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@JonathanRowley ... Angular moved recently from internationalization support from JavaScript to its own solution because of very inconsistency across different browsers and platforms ... so it is probably not possible to expect that it will be reverted in near future.

**Comment by petebacondarwin** [comment]
Closing due to a lack of support for this feature.
