### ISSUE TITLE
rename template-loading lib's xhr service to disambiguate from forthcoming http lib

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2305]
@vicb I'm adding some files and tests for the http library, and it could be confusing to contributors seeing many implementations of xhr in shared directories, like services and mock. I'd like to rename files for better clarity of purpose.

What do you think of prefixing all existing xhr implementation filenames with `template_` like so?

```
/angular
|--modules
|----angular2
|------src
|--------mock
|----------xhr_mock.ts -> template_xhr_mock.ts
|--------services
|----------xhr.ts -> template_xhr.ts
|----------xhr_impl.dart -> template_xhr_impl.dart
|----------xhr_impl.ts -> template_xhr_impl.ts
|------test
|--------mock
|----------xhr_mock_spec.ts -> template_xhr_mock_spec.ts
|--------services
|----------xhr_impl_spec.ts -> template_xhr_impl_spec.ts
```

**Comment by vicb** [comment]
What about moving xhr* out of services ?

**Comment by jeffbcross** [comment]
Would you move it into core? And would you keep the mock implementation in the mock directory?

**Comment by tbosch** [comment]
I actually should go into `src/render`, as it is only used there.

**Comment by jeffbcross** [comment]
@tbosch sounds good, will just move it there
