### ISSUE TITLE
@Injectable providedIn should be able to create a new service instance per component

### ISSUE THREAD

**Issue by benneq** [angular/angular#23057]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently it's not possible to use `@Injectable` `providedIn` to get a new service instance every time it is injected. Only singleton is possible using `providedIn: 'root'`.

The desired behavior can currently be achieved using `@Component({ providers: [MyService] })`

## Expected behavior

I'd like to specify at the service level that there should be no shared instanced. Though I'd like to have something like `providedIn: '*'`. Or maybe another additional parameter.

In Spring Framework they distinguish these behaviors using the words `singleton` and `prototype`.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-gitter-ibtjjh?file=app%2Fapp.component.ts

## What is the motivation / use case for changing the behavior?

At the moment we either must either use `@Component` `providers`, or
inject all needed services into the component itself and then pass it to some non-injectable utility service.

## Environment

<pre><code>
Angular version: 6.0.0-rc.0

Browser:
- [x] Chrome (desktop) version 65
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.9.0  
- Platform:  macOS 10.13.3 

Others:

</code></pre>

**Comment by trotyl** [comment]
Duplicate of #22756, if it's considered, should apply to both default and normal providers.

**Comment by benneq** [comment]
Sorry, didn't find it in the issues
