### ISSUE TITLE
Lazy modules providers setup is duplicated when trying to access the instance of NgModuleRef

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#23058]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

This is hard for me to explain so i'll do my best, most of it is in the demo.

## Current behavior
Lazy modules **providers** setup is duplicated when trying to access the **instance** of `NgModuleRef`.

## Expected behavior
When accessing the **instance** of the `NgModuleRef` it should use the injector created by the `NgModuleRef` and not create a new layer.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-dhdadp

Especially see https://stackblitz.com/edit/angular-dhdadp?file=app%2Fmy-service.service.ts

The demo is simple, 2 modules: root and feature where feature is lazy loaded.
Each module has 1 page.
There is one service called `MyServiceService` which is set in the **providers** of every module.
The service has a unique id for every instance.

In theory we should have only 2 instances of `MyServiceService` but in practice everytime we will access `NgModuleRef.instance` of the lazy module a new `MyServiceService` is created.

> Note that `MyServiceService` is eagerly init by setting it in the ctor of each module.

It is clear that the instance of `NgModuleRef` has a lazy init, so it will not init until we access it but angular also inspects the ctor of the module and see's that it has `MyServiceService` as an injection so it creates the instance of `MyServiceService **before creating the module instance**

Once we call `instance` angular creates the instance of the module but not with the existing injector, it creates a new injector based on the **providers** of the module... this is a duplicate.

## Environment

<pre><code>
Angular version: 5.2.8

**Comment by shlomiassaf** [comment]
It seems that the DI layer for a module is split into 2:

  - The metadata level, i.e. the **ModuleRef** level
  - The instance level

The latter is lazy, only if the developer want to access the module instance... lazy makes sense because instances of modules are rarely used.

It looks like there is no way to access the first layer (metadata) it doesn't exist, at least not as part of the tree... It exists within angular internals... maybe it's transient maybe not but its is not part of the user accessible tree.

While this design might be the right one, the final output is confusing...

**Comment by shlomiassaf** [comment]
@alexzuza DI issues are complex, I'm always carful before making a statement, twice when it's a complex DI scenario.

I agree that you have a valid point here, that is:

The **constructor** of a **module** request a service with a constructor that request the module instance.

That's true actually but it is so hidden, and so hard to see... it's a bad dev experience.

This happens because i'm not actually asking the DI for the module's instance, i'm asking it for **ModuleRef** instance, within it I access the instance....

@mhevery i'm not 100% sure it's a bug, but more of a peculiar  situation where the situation is obscured or hidden from plain sight, for me at least...

**Comment by alxhub** [comment]
This was resolved a while ago with Ivy - `NgModuleRef.instance` is no longer a getter.
