### ISSUE TITLE
aio: verify no 404 is served for sitemap URLs

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#23063]
As part of aio monitoring, verify that the sitemap URLs (in addition to not being redirected) do not result in a 404 page. 
See https://github.com/angular/angular/pull/22483#discussion_r177950039.

**Comment by gkalpak** [comment]
Adding proper checks for all sitemap URLs would increase the job time significantly (5x).
We have added some "smoke" tests in #23390, which cover basic areas.

@IgorMinar, do you think they are sufficient, or should I look into adding tests for all URLs?

**Comment by gkalpak** [comment]
Closing. @IgorMinar, feel free to reopen if you think we need more tests (and don't mind the time increase).

(For reference, the current job duration is ~25mins in total, ~15mins of which are spent on the sitemap URLs tests - this is the part that would increase 5x.)

**Comment by IgorMinar** [comment]
smoke tests should be sufficient. thanks!
