### ISSUE TITLE
Should nested i18n elements be supported?

### ISSUE THREAD

**Issue by roydor** [angular/angular#23068]
## Current behavior
Currently an element with an i18n attribute having a child element with an i18n attribute succeeds, but this shouldn't work, because i18n translations should be restricted to a single element.

## Expected behavior
Clear build warning/error if detected.

## What is the motivation / use case for changing the behavior?
Early detection of i18n structural issues.

**Comment by vicb** [comment]
Something might be broken but we have [a test](https://github.com/angular/angular/blob/0d9140cdce547de76539e6a9ddaa77939a7d0851/packages/compiler/test/i18n/extractor_merger_spec.ts#L313) showing that this situation produces an error.

There is nothing more I can do without more explanation or a reproduction - which is the reason why we ask for it in the issue template.
