### ISSUE TITLE
Proposed Optional Chaining operator (?.) for JavaScript, and the Angular safe navigation operator

### ISSUE THREAD

**Issue by jaufgang** [angular/angular#23065]
There is a Level 1 [TC39 proposal  to add an optional chaining (`?.`) operator to ECMAScript](https://github.com/tc39/proposal-optional-chaining).  

This operator is similar to the Angular template safe navigation operator.  The TC39 proposal document listed prior art of similar operators in other languages, but did not list the Angular template operator.  I [ created an issue](https://github.com/tc39/proposal-optional-chaining/issues/58) suggesting that the Angular template operator be listed as prior art, and a question was posed about the semantics of the Angular operator with respect to short circuiting.

I think there would be value in ensuring that the semantics of the Angular template operator be harmonized with anything that is going to be added to ECMAScript through TC39.  I would like to suggest that the appropriate core Angular devs be made aware of this proposal and contribute as appropriate.  In particular if anyone could engage in the discussion at
https://github.com/tc39/proposal-optional-chaining/issues/58, and answer the question about short-circuiting, that would be great!

**Comment by mhevery** [comment]
I have updated that issue. Closing this one.
