### ISSUE TITLE
docs(testing): not works download example.

### ISSUE THREAD

**Issue by KostyaTretyak** [angular/angular#23060]
## I'm submitting a...

<pre><code>[ x ] Bug report 
</code></pre>

## Current behavior
After downloads [Tests](https://angular.io/generated/zips/testing/specs.testing.zip) from [docs](https://angular.io/guide/testing), `npm i` and `npm test`, angular CLI report about error:

> ERROR in Entry module not found: Error: Can't resolve '/var/repos/angular-sample-tests/src/test.ts' in '/var/repos/angular-sample-tests/node_modules/@angular/cli/models/webpack-configs'
>
> ERROR in error TS6053: File '/var/repos/angular-sample-tests/src/test.ts' not found.
src/app/twain/twain.component.marbles.spec.ts(3,40): error TS2307: Cannot find module 'jasmine-marbles'.

And even after `npm i jasmine-marbles rxjs` throw error:

> ERROR in Entry module not found: Error: Can't resolve '/var/repos/angular-sample-tests/src/test.ts' in '/var/repos/angular-sample-tests/node_modules/@angular/cli/models/webpack-configs'
>
> ERROR in error TS6053: File '/var/repos/angular-sample-tests/src/test.ts' not found.
node_modules/jasmine-marbles/src/scheduler.d.ts(1,31): error TS2307: Cannot find module 'rxjs/testing'.
node_modules/jasmine-marbles/src/test-observables.d.ts(2,33): error TS2307: Cannot find module 'rxjs/internal/testing/SubscriptionLog'.

## Expected behavior
Test example should works.

## Environment

<pre><code>
Angular CLI: 1.6.5
Node: 8.10.0
OS: linux x64
Angular: 5.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, upgrade

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.10.0
</code></pre>

**Comment by jainanuj0812** [comment]
I have tried it on local, I have found following things
1) The jasmine-marble entry is missing from package.json.
2) test.ts file is missing from src/ folder, maybe it is a typo as I can see tests.sb.ts in src which can be the actual file.
3) This will anyway not work with the latest jasmine-marble package, see this
https://stackoverflow.com/questions/49530947/cannot-find-module-rxjs-testing-from-jasmine-marbles-umd-js
