### ISSUE TITLE
Data that starts with 0.

### ISSUE THREAD

**Issue by DaLiangLee** [angular/angular#23079]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`<div class="form-group">
                    <label>Delivery</label>
                    <select class="form-control" (change)="saveSelectedFilter(list,'deliveryOrderId',deliveryOrderId)" [(ngModel)]="deliveryOrderId" name="deliveryOrderId">
                        <option *ngFor="let item of deliveryOrderIDs" value ="{{item.value}}">
                            {{item.text|removeLeadingZeros}}
                        </option>
                    </select>
                </div>`

0 has been removed

`getPOs = (request: DeliveryOrderListRequest): Observable<any> => {
    console.log(request);
    console.log(request.deliveryOrderId);
    console.log(typeof(request.deliveryOrderId));
    this.selectionArea.selectionService.deselectAll(false);
    this.loadFilters(request);
    return this.service.deliveryOrders(request)
    .do((res: any) => {
      this.onDataLoaded.emit(res.page.totalElements !== 0);
      if (this.progressCode === 'WAITING') {
          this.noRecord = res.page.totalElements === 0;
      }
      this.getStorageFilter(res.page.totalElements);
    })
    .map(resp => resp.data);
  };`

`import { PagedListRequest } from 'right-angled';

export interface DeliveryOrderListRequest extends PagedListRequest {
  deliveryOrderId: string;
}`
## What is the motivation / use case for changing the behavior?

The data starting with 0 can be displayed normally on the page, but it is removed when it is passed back to the background.

## Environment

<pre><code>
Angular version: 4.3.1

Browser: All
- [ ] Chrome (desktop) version  65.0.3325.181
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.0  
- Platform: Windows

Others:

</code></pre>

![qq 20180330090005](https://user-images.githubusercontent.com/21189061/38120927-a8115c6e-33fe-11e8-9114-6df2aa6217d1.png)
![qq 20180330090015](https://user-images.githubusercontent.com/21189061/38120928-a8699c80-33fe-11e8-8427-dd3a3f10d471.png)
![qq 20180330090024](https://user-images.githubusercontent.com/21189061/38120929-a8b48fa6-33fe-11e8-891d-55a828c43e88.png)
![qq 20180330090030](https://user-images.githubusercontent.com/21189061/38120930-a8fea4c4-33fe-11e8-9d58-66984871bd18.png)
![qq 20180330090047](https://user-images.githubusercontent.com/21189061/38120931-a9e0046e-33fe-11e8-94f6-be7635873e2e.png)

**Comment by DaLiangLee** [comment]
Starting with 0 (088888), the page is normal, but it will get rid of 0 in the background.

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
