### ISSUE TITLE
Dependency injection for `useFactory` should not require explicitly listing `deps`

### ISSUE THREAD

**Issue by voithos** [angular/angular#23071]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently, specifying `useFactory` with injected parameters doesn't compile properly without also specifying the injectables in `deps`.

## Expected behavior
I'd expect the AoT compiler to be able to understand the dependency injection without having to explicitly specify it under `deps` (just like it works with components, other providers, etc).

This might be made slightly more difficult because (last I heard) parameter decorators are currently not allowed for function declarations (but only on methods, etc). See https://github.com/Microsoft/TypeScript/issues/3661. But this would only make usage of `@Inject()` difficult, whereas normal dependency injection should still work.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-kukwtv?file=app%2Fapp.module.ts

## What is the motivation / use case for changing the behavior?
More consistency with how dependency injection works elsewhere, and more convenience.

## Environment

<pre><code>
Angular version: head

Others:

</code></pre>

**Comment by mhevery** [comment]
AoT would be able to understand it, but JIT would not. We don't want to have a situation where valid AoT code would break in JIT. 

WONT_FIX; WORKING_AS_INTENDED

**Comment by voithos** [comment]
Ah, I see - JIT relies on the `@decorator` semantics? That's unfortunate.
