### ISSUE TITLE
ngBot milestone update

### ISSUE THREAD

**Issue by manughub** [angular/angular#23072]
Olivier, I missed a scenario when we made the change to the bot to add milestone: needsTriage

Here's what is required:

- If an issue does not have a label: comp, do not assign a milestone. This means it needs to go through caretaker triage.
- If an issue has a label: comp but does not have "severity*:" or "freq*:" then it needs to have a milestone: needsTriage . This signals the issue needs to go through L2 triage

**Comment by manughub** [comment]
Seems to be working fine, however the updates prior to this PR have left some of the issues in an inconsistent state. Looks like the bot is not crawling the full set of issues to do a clean up based on changes we made.

**Comment by manughub** [comment]
Also type: RFC is not handled correctly. A type: RFC does not need any other fields to get to milestone:backlog.

**Comment by ocombe** [comment]
@manughub do you have some examples of issues that are in an inconsistent state?
