### ISSUE TITLE
Class 'MatTableDataSource<T>' incorrectly extends base class 'DataSource<T>'.

### ISSUE THREAD

**Issue by paiamsahari** [angular/angular#23095]
Buge: i think after installed multi select in error
HElp me HElP me
ERROR in node_modules/@angular/material/table/typings/table-data-source.d.ts(21,22): error TS2415: Class 'MatTableDataSource<T>' incorrectly extends base class 'DataSource<T>'.
  Types of property 'connect' are incompatible.
    Type '() => BehaviorSubject<T[]>' is not assignable to type '(collectionViewer: CollectionViewer) => Observable<T[]>'.
      Type 'BehaviorSubject<T[]>' is not assignable to type 'Observable<T[]>'.
        Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
node_modules/@angular/material/tree/typings/data-source/flat-data-source.d.ts(72,22): error TS2415: Class 'MatTreeFlatDataSource<T, F>' incorrectly extends base class 'DataSource<F>'.
  Types of property 'connect' are incompatible.
    Type '(collectionViewer: CollectionViewer) => Observable<F[]>' is not assignable to type '(collectionViewer: CollectionViewer) => Observable<F[]>'. Two different types with this name exist, but they are unrelated.
      Type 'Observable<F[]>' is not assignable to type 'Observable<F[]>'. Two different types with this name exist, but they are unrelated.
        Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
node_modules/@angular/material/tree/typings/data-source/nested-data-source.d.ts(17,22): error TS2415: Class 'MatTreeNestedDataSource<T>' incorrectly extends base class 'DataSource<T>'.
  Types of property 'connect' are incompatible.
    Type '(collectionViewer: CollectionViewer) => Observable<T[]>' is not assignable to type '(collectionViewer: CollectionViewer) => Observable<T[]>'. Two different types with this name exist, but they are unrelated.
      Type 'Observable<T[]>' is not assignable to type 'Observable<T[]>'. Two different types with this name exist, but they are unrelated.
        Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

This is not an angular's bug. If it is a bug at all it should be reported in the lib's repo https://github.com/angular/material2

**Comment by kara** [comment]
Yeah, this look Material-related, so it should be filed in that repo.

**Comment by barryallen7** [comment]
same issue here. Someone found any solution?

**Comment by lsnellenburg** [comment]
Same error over here... Trying to create a simple mat-table. I've been googling for days but can't find the solution
