### ISSUE TITLE
Use Angular Components without a root app component.

### ISSUE THREAD

**Issue by mikeandersun** [angular/angular#23099]
I have a CMS web site with many static pages that made with angular1.6.x. 
I don't need a SPA feature , but I need some angular components(e.g: like component ,rate component,...) that placed in some points of my html pages.
It is possible?

**Comment by mlc-mlapis** [comment]
@mikeandersun ... any Angular component which is created programmatically can be attached to any node in DOM.

**Comment by mikeandersun** [comment]
@mlc-mlapis ... Can you give me some sample address?Please.

**Comment by mlc-mlapis** [comment]
@mikeandersun ... it's all about using `create` method from `ComponentFactory` class because you can pass `rootSelectorOrNode` as the third parameter ... in this case `node`. https://angular.io/api/core/ComponentFactory#create

```
class ComponentFactory<C> {
  get selector: string
  get componentType: Type<any>
  get ngContentSelectors: string[]
  get inputs: {...}
  get outputs: {...}
  create(injector: Injector, projectableNodes?: any[][], rootSelectorOrNode?: string | any, ngModule?: NgModuleRef<any>): ComponentRef<C>
}
```

**Comment by gkalpak** [comment]
@mikeandersun, you might also want to look into `@angular/elements` (which is still experimental but getting close to stable): #20891

**Comment by alexeagle** [comment]
I don't think there's any action needed from Angular team or an issue to resolve? Please comment if we should re-open this.
