### ISSUE TITLE
Support for Typescript 2.8

### ISSUE THREAD

**Issue by pulsejet** [angular/angular#23092]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior

Throws an error for TS 2.8+ which can optionally be overridden.

## Expected behavior

2.7 is now supported (8449eb8d62220565237360b12b25273818d1d9da), but since 2.8.1 is already here, would be nice to have support for it officially.

**Comment by alexeagle** [comment]
I think we want to do this for rc.2, right @IgorMinar ?

**Comment by sandangel** [comment]
Please do. I really really want conditional type.

**Comment by IgorMinar** [comment]
@alexeagle I don't think so. it's a high risk change. This will have to wait until 6.1 due in May.

**Comment by pburgmer** [comment]
Would be great to see this in CLI 6.1

**Comment by IgorMinar** [comment]
Closing in favor of #23779. Please follow that issue for updates.
