### ISSUE TITLE
e2e tests: clicks are not working when using `mobileOptions` capabilities

### ISSUE THREAD

**Issue by tbosch** [angular/angular#2309]
Calls to `browser.click()` are doing nothing when I run benchmarks / e2e tests using protractor and have the capabilities below. There are no errors in the browser log, clicking on the buttons manually works, and removing the `mobileEmulation` entry from the capabilities also makes the tests work again.

This is probably a bug in chromedriver, but needs more investigation and a simple reproduction case to file an issue there.

```
{
  browserName: 'chrome',
  chromeOptions: {
    'mobileEmulation':   {
      'deviceMetrics': {
        'width': 600,
        'height': 960,
        'pixelRatio': 2
      }
    }
  }
}

```

**Comment by juliemr** [comment]
Note that this works for chrome 43 and 45 (canary).

**Comment by tbosch** [comment]
I am using the following command: 
```
./node_modules/.bin/protractor protractor-js.conf.js --benchmark --specs=dist/js/cjs/benchmarks/e2e_test/tree_perf.js
```

Note that the benchmarks don't throw, but just don't click on the button, i.e. the tree does not show and hide while the benchmark is running.

**Comment by juliemr** [comment]
Reproduced with plain old selenium-webdriver using selenium-webdriver node module 2.45, selenium 2.45, and chromedriver 2.14, and Chrome > 43. See https://github.com/juliemr/webdriver-bugs/blob/master/mobileclick.js

New versions of selenium and chromedriver are out today. I'm going to try updating and see if that fixes.

**Comment by juliemr** [comment]
See https://github.com/angular/protractor/issues/2245

**Comment by juliemr** [comment]
With updated selenium and chromedriver, this passes on Chrome 44 beta but fails on Chrome 45 canary because the click goes to the wrong element.

Issue submitted to ChromeDriver: https://code.google.com/p/chromedriver/issues/detail?id=1127

**Comment by juliemr** [comment]
Closing since the issue is now filed with chromedriver.

**Comment by nexstreamray** [comment]
Hey @juliemr, the clicks are still not working on current chrome driver.
Any news for this?
