### ISSUE TITLE
[Doc] inconsistent code style of interpolation binding syntax

### ISSUE THREAD

**Issue by kmsheng** [angular/angular#23105]
https://angular.io/tutorial/toh-pt1

<img width="842" alt="screen shot 2018-03-31 at 8 26 57 am" src="https://user-images.githubusercontent.com/880569/38157841-6b734690-34bd-11e8-9d95-d0ff1a8013fb.png">

**Comment by IgorMinar** [comment]
Can you please explain what's inconsistent about this? I'm not sure I understand this issue.

**Comment by kmsheng** [comment]
@IgorMinar Sure, by saying `inconsistent` I mean either to choose a style with spaces inside the interpolation binding syntax or without spaces. 
For example, `{{ hero.name }}` and `{{hero.name}}`

**Comment by jenniferfell** [comment]
@IgorMinar Is there a preferred style? (https://angular.io/guide/styleguide does not use spaces in the examples it shows, but it doesn't specify explicitly.) I can make a note in our docs on creating examples, at least for internal consistency as we make other changes to examples. Thanks.
