### ISSUE TITLE
Setting i18nLocale in configuration with optimizations on breaks application

### ISSUE THREAD

**Issue by msc117** [angular/angular#23107]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

```js
  function y(t, e, n) {
    'string' != typeof e && (n = e, e = t[0]),
    e = e.toLowerCase().replace(/_/g, '-'),
    d[e] = t,
    n && (d[e][19] = n)
  }
```
`TypeError: e is undefined[Learn More]
main.8d50cd235bdedd34ad5a.js:formatted:7106`

## Expected behavior

Compiling application in production mode with `i18nLocale` set runs built app successfully with selected locale.

## Minimal reproduction of the problem with instructions
```bash
$ ng new test-app
```
In `package.json` set angular dependencies to `6.0.0-rc.0` and rxjs to `6.0.0-beta.4` and typescript to `2.7.2`
```bash
$ npm i
```
In `angular.json`, modify production configuration to have `i18nLocale: 'ja'`, or any other locale besides en.

```bash
$ ng serve --configuration=production
```

Open to `locahost:4200` and see broken application with the error `TypeError: e is undefined[Learn More]
main.8d50cd235bdedd34ad5a.js:formatted:7106`

## What is the motivation / use case for changing the behavior?
Angular 6 works built with a different locale

## Environment

<pre><code>
Angular version: >=6.0.0-rc.0 (possibly the beta releases, I haven't tried them)

Browser:
all browsers
 
Others:
Application works correctly in dev mode, but breaks with optimizations on.

This is the source file it is coming from: https://github.com/angular/angular/blob/master/packages/common/src/i18n/locale_data.ts#L27
</code></pre>

**Comment by IgorMinar** [comment]
This could be the same issue as #23103

**Comment by vicb** [comment]
Closing as duplicate. `t[0]` should be the locale name but is undefined because `t` (localeData) is not passed.

**Comment by msc117** [comment]
I'm not sure it is, since this isn't a rc.1 issue. I'm using rc.0 to recreate this consistently. I've seen rc.2 issue and don't think it's related.
