### ISSUE TITLE
On @angular/platform-webworker reactive form with select input not work bind value or change event

### ISSUE THREAD

**Issue by Insidexa** [angular/angular#23109]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In webworker platform reactive form with select input does not react on `this.form.valueChanges.subscribe(v => console.log(v))`
not react on `(change)`
not bind new selected value to `[(ngModel)]`

## Expected behavior

fix this problem

## Minimal reproduction of the problem with instructions
html
```
<form [formGroup]="form" (ngSubmit)="submit()">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="input-group">
                                    <input formControlName="path" required class="form-control">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="input-group">
                                    <select formControlName="type" class="form-control">
                                        <option value="">select type</option>
                                        <option *ngFor="let t of types" [value]="t">{{ t.text }}</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <button [disabled]="form.invalid" class="btn btn-block btn-primary btn-sm" type="submit">Save</button>
                            </div>
                        </div>
                    </form>
```

component (  )
```
public types: Array<any> = [
    { text: 'Number', value: '[object Number]' },
    { text: 'String', value: '[object String]' },
    { text: 'Array', value: '[object Object]' },
  ];
  public form: FormGroup;

  constructor(private fb: FormBuilder) { }

  public ngOnInit() {
    this.form = this.fb.group({
      path: [this.key.path, Validators.required],
      // init value worked
      type: [this.types[1], Validators.required],
    });
    this.form.valueChanges.subscribe(v => {
      // on select this does not react
      // on change path its work
      console.log(v)
    });
  }
```

## Environment

<pre><code>
Angular version: ^5.2.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by splincode** [comment]
@Insidexa Please, a create on stackblitz your example

**Comment by jotatoledo** [comment]
Please add a living reproduction of your issue, for example in stackblitz.

**Comment by Insidexa** [comment]
If you use webworker platform, you should understand that stackblitz does not allow configure webpack for create bundle with webworker.bundle
For webworker necessary ng eject
But i created github repository

**Comment by AndrewKushnir** [comment]
Hi @Insidexa,

As of Angular version 8, all `platform-webworker` APIs are deprecated (see more info about this in [deprecation doc](https://angular.io/guide/deprecations#running-angular-applications-in-platform-webworker)), so I'm closing this ticket.

Thank you.
