### ISSUE TITLE
Large JSON file (size around 45MB) , takes time while searching .

### ISSUE THREAD

**Issue by goel-sunny** [angular/angular#23122]
I have a large JSON file in my angular 5 project like 45 MB or may be bigger , when i am loading this file from my local assets folder it takes around 5-10 sec but while i am doing searching in it , it would takes alot of time and memory and sometimes my browser window become unresponsive and crashed , for representing the data at front end side i am using `ng-treetable` module . can anyone suggest me how to increase the searching performance .

is i have to use database here for searching and displaying ?

or do searching in JSON file instead of object ?

**Comment by frederik** [comment]
Hi there,

I don't think this is an issue with Angular (e.g. a bug) but rather a general constraint on in memory processing you can (or should) do in the browser. Please see the [contribution guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question) on asking questions in this repository.

In the spirit of being helpful even though this repository is reserved for issues with Angular itself, you could look into:

- reducing the overall file size (maybe not all data is needed)
- storing the file in the browser (e.g. through IndexedDB) and then paginating
- storing the data in a service like firebase and then using angular-fire to access it (paginated)
- using a server side solution (e.g. an node.js express) app to split the JSON and only serve the data the app needs (again, paginated).

Which option you pick largely depends on your exact use case. There are a lot of resources on Google/StackOverflow,.. (e.g. if you search for "AngularFire2 pagination").

Regards
Frederik

**Comment by gkalpak** [comment]
In addition to what @frederik said above, the issue might be with `ng-treetable`, in which case you can try opening an issue on their repo.

**Comment by Githamza** [comment]
Also using a dataframe could increase performances , check [dataframe-js](https://www.npmjs.com/package/dataframe-js)
