### ISSUE TITLE
Remove ad-banner class from ad-banner.component.ts in Dynamic Component Loader stackblitz example.

### ISSUE THREAD

**Issue by iamkdev** [angular/angular#23125]
The example(https://stackblitz.com/angular/xkpnjgvlqym) for Dynamic Component Loader doesn't display.
If we remove the class **ad-banner** from ad-banner.component.ts in the template it will display the ad.

**Comment by gkalpak** [comment]
This probably caused by an ad blocker you have installed. Feel free to submit a pull request for removing the class if it helps people not have the example incorrectly blocked by ad blockers.

**Comment by iamkdev** [comment]
@gkalpak you are correct it because of ad-blocker. I would suggest to change the class name so that people with ad-blocker don't get confuse.
