### ISSUE TITLE
How to host angular 5 universal project IIS web server

### ISSUE THREAD

**Issue by chozharajan** [angular/angular#23120]
i build a site with universal support it's working good in local and i referred this [URL](https://github.com/angular/universal-starter). for normal angular project we move all files from `dist` folder to server (MySiteFolder/All files). but in universal they have two folders in `dist` (browser and server). so we moved all files from both server and browser  to server (MySiteFolder/All files). my site is working  but universal not working (view source). i used `npm run build:ssr` for build.
please let me know how to host angular universal to IIS web serever for dynamic sites. Thank you

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
