### ISSUE TITLE
Explicitly support dynamic application loading/unloading/multi-loading

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#2312]
We've been sort of moving in the right direction with @tbosch's recent refactoring of dynamic component loading and bootstrap, but we need a formal support and documentation for how to dynamically unload a ng2 application and load a new one, as well as bootstrap multiple apps simultaneously.

**Comment by mhevery** [comment]
Should be covered by #1594

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

Supported by `@AppModule`
