### ISSUE TITLE
Angular service worker stop working after going offline

### ISSUE THREAD

**Issue by klauserber** [angular/angular#23135]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

After we where offline new lazy assets and datagroup calls are not cached when we come back online.

## Expected behavior

New lazy assets and datagroup calls will be cached when we come back online.

## Minimal reproduction of the problem with instructions

https://stackblitz.com is not suitetable for a reproduction, cause we need a angular production build.

1. Create a new angular project with service worker:

$ ng new ngsw-test --service-worker

2. Add an asset to the project:

$ cd ngsw-test/
$ echo "Just an asset" > src/assets/test.txt

3. Build for production

$ ng build --prod

4. Serve the production build:

$ http-server dist/

5. Visit the Application with chrome:

http://localhost:8080

6. Request the test asset:

http://localhost:8080/assets/test.txt

Check if the asset was cached:

![image](https://user-images.githubusercontent.com/9998995/38234879-8262bfd4-371f-11e8-8e7c-242b1d987700.png)

Fine! That work's!

7. Now Clear all site data:

![image](https://user-images.githubusercontent.com/9998995/38234932-ad28a756-371f-11e8-8a1c-7ef06e36ed4c.png)

…and visit the applictaion again in a new tab/window.

Then go to

http://localhost:8080/ngsw/state

```
NGSW Debug Info:

Driver state: NORMAL ((nominal))
Latest manifest hash: 93c83124ea864957be27f463285f323a5ba37e0c
Last update check: 6m12s56u

=== Version 93c83124ea864957be27f463285f323a5ba37e0c ===

Clients: 6c425f61-4e54-46da-a94c-e7e459569501

=== Idle Task Queue ===
Last update tick: 6m10s928u
Last update run: never
Task queue:


Debug log:

[6m10s927u] TypeError(Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode, TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at Driver.safeFetch (http://localhost:8080/ngsw-worker.js:2464:37)
    at Driver.handleFetch (http://localhost:8080/ngsw-worker.js:1975:25)) Driver.fetch(http://localhost:8080/)

```

The driver state is normal and we have a TypeError in the log.

8. Go offline and visit the application

![image](https://user-images.githubusercontent.com/9998995/38235095-3d38cd8a-3720-11e8-8f12-26f7ffaaa5e3.png)

```
NGSW Debug Info:

Driver state: EXISTING_CLIENTS_ONLY (Degraded due to failed initialization: Manifest fetch failed!
Error: Manifest fetch failed!
    at Driver.fetchLatestManifest (http://localhost:8080/ngsw-worker.js:2187:19))
Latest manifest hash: 93c83124ea864957be27f463285f323a5ba37e0c
Last update check: 18m6s7u

=== Version 93c83124ea864957be27f463285f323a5ba37e0c ===

Clients: 6c425f61-4e54-46da-a94c-e7e459569501, efd7e4ed-d75f-40b3-9065-c390a0ae3c22

=== Idle Task Queue ===
Last update tick: 9m54s265u
Last update run: 9m49s264u
Task queue:


Debug log:

[18m4s878u] TypeError(Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode, TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at Driver.safeFetch (http://localhost:8080/ngsw-worker.js:2464:37)
    at Driver.handleFetch (http://localhost:8080/ngsw-worker.js:1975:25)) Driver.fetch(http://localhost:8080/)
[9m49s262u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(http://localhost:8080/ngsw.json?ngsw-cache-bust=0.8606498338103712)
[9m49s262u] Error(Manifest fetch failed!, Error: Manifest fetch failed!
    at Driver.fetchLatestManifest (http://localhost:8080/ngsw-worker.js:2187:19)) Error occurred while updating to manifest (unknown

```

The request for the manifest was failed, because we are offline. This leads to a degraded state 'EXISTING_CLIENTS_ONLY'.

9. Go online and visit the application.

![image](https://user-images.githubusercontent.com/9998995/38235203-8d54a0e6-3720-11e8-8a3e-653a413177c8.png)

The manifest request was now successful.

But the driver state is still degraded:

```
NGSW Debug Info:

Driver state: EXISTING_CLIENTS_ONLY (Degraded due to failed initialization: Manifest fetch failed!
Error: Manifest fetch failed!
    at Driver.fetchLatestManifest (http://localhost:8080/ngsw-worker.js:2187:19))
Latest manifest hash: 93c83124ea864957be27f463285f323a5ba37e0c
Last update check: 2m50s917u
…

```

10. Request the test asset.

The asset was not cached:

![image](https://user-images.githubusercontent.com/9998995/38235254-be944012-3720-11e8-9890-fd135797b4e0.png)

A few thoughts on that:

After some debugging I found the method checkForUpdate() in the file driver.ts:

```typescript
async checkForUpdate(): Promise<boolean> {
	let hash: string = '(unknown)';
	try {
		const manifest = await this.fetchLatestManifest();
		hash = hashManifest(manifest);
		// Check whether this is really an update.
		if (this.versions.has(hash)) {
			return false;
		}
		await this.setupUpdate(manifest, hash);
		return true;
	} catch (err) {
		this.debugger.log(err, `Error occurred while updating to manifest ${hash}`);
		this.state = DriverReadyState.EXISTING_CLIENTS_ONLY;
		this.stateMessage = `Degraded due to failed initialization: ${errorToString(err)}`;
		return false;
	}
}

```

The call fetchLatestManifest() throws an error in the offline case. Then we came into the catch block, which sets the degraded state. After this we never come back to the normal state. Is this the correct behaviour? Do we really want to switch the state in this way, when we are offline? If the answer is yes, how do we come back to normal state, so that the cache begin to work again.

## What is the motivation / use case for changing the behavior?

The environment of our application has no stable network. Changes between online and offline state are normal. Nevertheless, we need a consistent application.

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [x] Chrome (desktop) version 65.0.3325.181
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.1  
- Platform:  Windows 

Others:

</code></pre>

**Comment by gkalpak** [comment]
Thx for the detailed report.
This has been fixed in #22883. The fix has been merged into 5.2.x (ae9c25ff3) and should be included in 5.2.10.

**Comment by junraemon** [comment]
I have this issue on my angular 6 project, has this already been resolved?

**Comment by gkalpak** [comment]
Yes, it has been fixed (see https://github.com/angular/angular/pull/22883#issuecomment-386798035).
