### ISSUE TITLE
Angular router problem?

### ISSUE THREAD

**Issue by VCodepp** [angular/angular#23143]
There are two buttons. and one of the buttons has a drop-down menu. it works fine when the buttons are clicked. pages are being created, url is changing.
but I can not say the same for the drop-down menu. This does not react when I click on the popup menu button (but the url is changing). I could not figure out why the drop-down buttons do not work.

My page schema 
![announcement](https://user-images.githubusercontent.com/18616263/38254787-c924e1d4-3762-11e8-9cf0-3ae696645865.png)

app-routing.ts 

![component](https://user-images.githubusercontent.com/18616263/38254857-fba8f690-3762-11e8-8c3a-eadae7b5cec8.png)

child component.ts
![componenst](https://user-images.githubusercontent.com/18616263/38254960-3c7b21e8-3763-11e8-83d8-6427a1084869.png)

I did not understand what was wrong

**Comment by VCodepp** [comment]
eric Stackoverflow is not good platform. because ;
they behave badly because my english is not in perfect level. they are very arrogant instead of answering. so I'm trying to find alternative places

**Comment by mlc-mlapis** [comment]
@VCodepp ... but Angular Issue Channel is not the right place really. I recommend following:

* Prepare **the most simplest** demonstration version of your problem on https://stackblitz.com which is run-able for anyone.
* Then ask on https://gitter.im/angular/angular channel.

**Comment by VCodepp** [comment]
ericmartinezr You don't like commentary, but it does not change the truth.

mlc-mlapis thx dude. I'm try
