### ISSUE TITLE
@angular/common/locals are not being shipped in Angular 6.0.0-RC1

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#23140]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Since Angular 6 RC 1 `locales`  under `@angular/common/locales` are not being shipped 

See
https://unpkg.com/@angular/common@6.0.0-rc.1/

## Expected behavior
Locales to be shipped.

## Environment

<pre><code>
Angular version: 6.0.0-rc.1

**Comment by jotatoledo** [comment]
Dup https://github.com/angular/angular/issues/23103

**Comment by pkozlowski-opensource** [comment]
Yep it was previously reported in #23103, closing as a duplicate
