### ISSUE TITLE
Improve injectable app configuration (angular-cli-compatible)

### ISSUE THREAD

**Issue by gagle** [angular/angular#23158]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
With Angular CLI we are able to define preconfigured per-environment configuration that is included in the build artifact, which is great when we want to hardcode some settings like API endpoints.

To consume these settings we just need to import the environment.ts file and use it in any class:

```typescript
import { environment } from '.../environments/environment';
```

There is a typical architecture setup for UI automation acceptance tests where you run the website with all service calls stubbed with fake data for performance issues and because you don't want to call the real services, you're just testing the UI frontend as a unit.

This is implemented by injecting per-environment services. You have the real and the stubbed one, both extending an abstract class acting as the provider interface:

```typescript
abstract class UserService {}
class UserApiService extends UserService {}
class UserStubService extends UserService {}
```

Then in the environment file you declare the type that is injected, like so:

```typescript
// dev
export const environment = {  userServiceType: UserApiService  };

// test
export const environment = {  userServiceType: UserStubService };
```

And then in the app module we select the user service type:

```typescript
@NgModule({
  providers: [
    {
      provide: UserService,
      useClass: environment.userServiceType
    }
  ]
})
class AppModule {}
```

So far, so good.

Now let's introduce a dependency cycle. Say you want to read a configuration property from the environment file:

```typescript
import { environment } from '.../environments/environment';

class UserApiService extends UserService {
    private endpoint: string;
    constructor() {
        this.endpoint= environment.userServiceEndpoint;
    }
}
```

With this simple scenario we've introduced a dependency cycle:

UserApiService -> environment -> UserApiService

For this use case, this can be solved by wrapping the environment and injecting this wrapper in the consumer class. For example, let's put this peace of code in the app module:

```typescript
class EnvironmentContainer {
  public environment: object;
}

@NgModule({
  providers: [
    {
      provide: EnvironmentContainer,
      useValue: {
        environment
      } as EnvironmentContainer
    },
    {
      provide: UserService,
      useClass: environment.userServiceType
    }
  ]
})
class AppModule {}
```
Now the user service can be rewritten as:

```typescript
class UserApiService extends UserService {
    private endpoint: string;
    constructor({ environment }: EnvironmentContainer) {
        this.endpoint= environment.userServiceEndpoint;
    }
}
```

The dependency cycle has been removed AND we've also removed the hardcoded dependency (the import), now the unit tests are far more easier, we just need to stub the injectable configuration.

## Expected behavior
It could really improve the angular app configuration experience by creating a set of classes above the environment file to decouple us from reading the low-level config file by manually importing it and wrapping it into an injectable.

Java Spring Configuration solved this some years ago by creating an Environment class which gets injected into configuration classes to get the properties from the config. Currently I implemented this into my project and works really well.

For instance, this is a configuration class that I'm using to hold all the Google Analytics settings:

```typescript
export const environment = {
  googleAnalytics: {
    userId: 'foo'
  }
}
```

```typescript
@Injectable()
export class GoogleAnalyticsConfiguration {
  // Properties just wraps the access to the object with an immutable in order to make the config
  // immutable and to be able to use the getIn function, so unknown property acces will never
  // throw an error and will return null. It is basically a layer to control the access.
  private properties: Properties;

  public constructor(environment: EnvironmentService) {
    this.properties = environment.getProperty('googleAnalytics');
  }

  public get userId(): string {
    return this.properties.get('userId');
  }
}
```

And the consumer class:

```typescript
@Injectable()
export class GoogleAnalyticsVendorService extends GoogleAnalyticsService {
  public constructor(
    private configuration: GoogleAnalyticsConfiguration
  ) {
    super();
    console.log(configuration.userId) // foo
  }
}
```

It would be excellent to mimic the Java Spring Configuration module and also add some decorators to reduce boilerplate:

```typescript
@Configuration() // Automatically calls Injectable() decorator
export class GoogleAnalyticsConfiguration {
  @Value('googleAnalytics.userId')
  public userId: string;
}
```

**Comment by trotyl** [comment]
What's the semantics of `@Configuration()` and `@Value()` given that there's no Angular CLI involved?

**Comment by gagle** [comment]
No-op with a warning message maybe?

**Comment by gagle** [comment]
This feature can be further improved by adding support to any property source, not only the environment file, we could go with something like this:

```typescript
// HTTP file is in json format but may be in any other format.
// The PropertySource class would need to handle that
// {
//   "services": {
//     "user": {
//       "api": {
//         "baseUrl": "http://foo.bar",
//         "port": 8888,
//         "security": { ... }
//       },
//       "websocket": { ... }
//     }
//   }
// }

@Configuration({
  // The source of the properties may be specified, otherwise properties are
  // loaded from environment file
  source: HttpFileSource,
  properties: {
    safeNotFound: true // nulled not found properties
  },
  // when true, call PropertySource#load on boot with APP_INITIALIZER
  init: true
})
class UserServiceConfiguration {
  // This will call HttpFileSource#getProperties in a safe way,
  // if the 'services' field is not found, it will return null due to the
  // 'safeNotFound' option
  // It will also instantiate the UserApiConfiguration class and fill all the
  // properties of the class based on the property name and the class type
  @Value('services.user')
  api: UserApiConfiguration;
}

// Mark the class as Configuration to make it injectable and to be able to add
// any Configuration related property decorators
@Configuration()
class UserApiConfiguration {
  baseUrl: string;
  port: number;
}

// Alternatively, you specify the 'prefix' to get rid of the @Value
@Configuration({
  source: HttpFileSource,
  properties: {
    safeNotFound: true // nulled not found properties
  },
  init: true,
  prefix: 'services.user'
})
class UserServiceWithPrefixConfiguration {
  api: UserApiConfiguration;
  security: UserSecurityConfiguration;
}

interface PropertySource {
  load: Promise<void>;
  getProperties(): Properties;
}

class HttpFileSource implements PropertySource {
  private properties = new Properties({
    options: /* read Configuration 'properties' metadata */
  });

  load(): Promise<void> {
    // Http GET request
    // This is also the point to validate the schema with any schema-validator
    // like hapi joi
    this.properties = this.properties.merge(await this.fetchFile());
  }

  getProperties(): Properties {
    return this.properties;
  }
}
```

The only remaining things are initialization order, think about a tree of `PropertySource`s and maybe variable expansion.

[Spring configuration docs](http://www.baeldung.com/configuration-properties-in-spring-boot)
