### ISSUE TITLE
How to use @Input example

### ISSUE THREAD

**Issue by arangates** [angular/angular#23159]
Is it possible to use @Input variable in anothe @Input variable ? 

`
 @Input() field: Field;

  @Input() form: FormGroup = new FormGroup({
    amount: new FormControl({ value: null, disabled: this.disabled }, [Validators.required]),
    currency: new FormControl({ value: this.field.currencies[0].value , disabled: this.disabled }, [Validators.required])
  });
`
Angular version: 5.1.o

**Comment by thw0rted** [comment]
This doesn't make sense -- you're assigning a value to `form` in your class definition code.  Don't do that!  The value of `@input` members should be set by assigning to them in a template declaration.

Generally, if you have a question about Angular usage, you should ask on StackOverflow (or similar).  This issue tracker is for bugs or feature requests.

**Comment by mlc-mlapis** [comment]
@arangates ... it doesn't have any logic to use `@Input()` in that situation ...

**Don't use Angular Issues Channel for support questions.** Use Gitter or so for that ...
