### ISSUE TITLE
ParamMap returns a number if number used in navigate

### ISSUE THREAD

**Issue by narthur157** [angular/angular#23165]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Optional route params that are given as numbers in navigate remain as numbers until page is refreshed. 

## Expected behavior

Would expect this to always be a string, as paramMap.get() claims

## Minimal reproduction of the problem with instructions
https://angular-gitter-gd3f8s.stackblitz.io/notTheRoot;numVal=9;strVal=14
https://stackblitz.com/edit/angular-gitter-gd3f8s

The values change every 3 seconds. On page load, numVal will be a string, but then after updating will be a number. strVal is the same, except toString is called.

## What is the motivation / use case for changing the behavior?

Actual types matching types declared by api

## Environment
See StackBlitz
<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version 65
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kambleaa007** [comment]
At the start they both are of type Object (Output shows)
As you declared them as Any (Line no. 13,14)
There is nothing like String as per your question
Its fine I checked with output not test cases :-


  ngOnInit() {
    setInterval(() => {
      this.router.navigate([{
      numVal: Math.floor(Math.random()*20).toString(), 
      strVal: Math.floor(Math.random()*20).toString()}
      ], {relativeTo: this.route});
    }, 3000);

    this.route.paramMap.subscribe((paramMap: ParamMap) => {
      this.numVal = paramMap.get('numVal');
      this.strVal = paramMap.get('strVal');

      this.numValType = typeof this.numVal;
      this.strValType = typeof this.strVal;
    });
  }

output:-
numVal: 11 string strVal: 16 string
numVal: 16 string strVal: 11 string

**Comment by narthur157** [comment]
I can't tell what you're trying to say

**Comment by benneq** [comment]
I just experienced this issue, too.

And it's getting even worse with objects:
```
router.navigate([{ foo: { bar: true } }])
// now activatedRoute.snapshot.paramMap.get('foo') === { bar: true }

// reload the page
// now activatedRoute.snapshot.paramMap.get('foo') === "[object Object]"
```

**Comment by r4vn** [comment]
It seems it is not only limited to `paramMap`. Just encountered the very same problem with accessing `queryParams` after using `navigate` with a number. 

I would definitely prefer #25095 since this solves the root issue with `createUrlTree`. The first pull request #23641 would only solve it for `paramMap` in my opinion.
