### ISSUE TITLE
Can't get custom error message from server when response status is 404 

### ISSUE THREAD

**Issue by owlstack** [angular/angular#23166]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently, if I have a service call that returns 404 status I can't get the custom error message from my json reponse to display in my UI. The only message I can display is the fault error message. 

Here's an SO post with exact problem: https://stackoverflow.com/questions/49646657/how-do-i-get-the-post-json-when-there-is-a-404-error

## Expected behavior
Ideally, when I have an error, I should be able to get my custom error message from my json response to display to my UI. Currently, there is no way for me to do so. I'm not sure if this is a bug with Angular or a feature request that needs to occur or both. 

## Minimal reproduction of the problem with instructions

Here's an SO post with code and steps: https://stackoverflow.com/questions/49646657/how-do-i-get-the-post-json-when-there-is-a-404-error

## What is the motivation / use case for changing the behavior?

The reason I want custom error messages is because a 404 status from the server can be for different reasons and we want to identify to the user is the error from the server is being they could not locate the transaction or because it's a permission issue and they need to ask admin for permission. So we show different custom messages. 

## Environment

Angular CLI: 1.7.3
Node: 8.11.1
OS: win32 x64
Angular: 5.2.5

Browser:
- [X ] Chrome (desktop) version Version 65.0.3325.181 
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by digitalplayer-steemit** [comment]
Why is it reported as a bug?

**Comment by owlstack** [comment]
Not sure if bug or feature request but this needs to be fixed or added. Currently, there is no way to get the custom error message from the server. 

Unless you know a way @digitalplayer-steemit ?

**Comment by alxhub** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
