### ISSUE TITLE
Lazy-loading not working in Angular 5.2.8 on StackBlitz

### ISSUE THREAD

**Issue by splincode** [angular/angular#23163]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
![image](https://user-images.githubusercontent.com/12021443/38312605-d9d591d6-382a-11e8-83cb-6513d810f769.png)

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-uotzgd?file=app/app.module.ts

<pre><code>
Angular version: 5.2.8

**Comment by trotyl** [comment]
![image](https://user-images.githubusercontent.com/6059170/38314154-2ff70cb6-3858-11e8-94fc-d425783cad3e.png)

You can try request StackBlitz to provide a tslint integration.

**Comment by splincode** [comment]
I think need online tslint on stackblitz, thank you)))

**Comment by splincode** [comment]
For an hour I could not understand what was going on
