### ISSUE TITLE
Locale inconsistency: Upper/Lower case

### ISSUE THREAD

**Issue by iget-master** [angular/angular#23171]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently, when using dates on `en` locale, months and weekdays starts with an Uppercase character.
On the `pt` locale starts with a Lowercase characters.

## Expected behavior
IMO, both must have the same character case, avoid differences between languages.

## Minimal reproduction of the problem with instructions
Not necessary, just see:
https://github.com/angular/angular/blob/master/packages/common/locales/en.ts
and
https://github.com/angular/angular/blob/master/packages/common/locales/pt.ts

## What is the motivation / use case for changing the behavior?
Do not apply

## Environment

**Do not apply, unnecessary**

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vicb** [comment]
The data comes from the CLDR.

If the CLDR is wrong we could certainly patch them but you need to explain why the CLDR is wrong.

**Comment by IgorMinar** [comment]
If we agree that this is a problem we should actually try to raise this issue with CLDR first before working around it.

**Comment by iget-master** [comment]
IMO, the first step is to check whats the default: all lower, or camel case.

I think that it should be normalized, but I really don't understand about CLDR.

**Comment by ocombe** [comment]
Angular uses [CLDR](http://cldr.unicode.org/) data for all i18n values, if you believe that there is a mistake in those data, then you should open an issue on the CLDR repository: http://cldr.unicode.org/index/bug-reports

**Comment by vicb** [comment]
Closing this as the format comes from the CLDR.
If the CLDR are wrong please file a defect there and we can normalize while the bug is being fixed.
