### ISSUE TITLE
Validation issue on Reactive Form(input type file) on Angular 5 on Google Chrome browser

### ISSUE THREAD

**Issue by pradiptagure** [angular/angular#23172]
## I'm submitting a...
[ X ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X ] Feature request
[ X ] Documentation issue or request
[ X ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Reactive Form - For input type 'file', if a file is added, input should be a valid one. On Firefox,IE this is working fine. But on Chrome browser, even if the file is added, input is still invalid.

## Expected behavior
On google chrome browser input file status should be a 'valid' one, when file is already added.

## Minimal reproduction of the problem with instructions
This is my stackblitz implementation -
https://stackblitz.com/edit/angular-5vcajr

1. Open developer tools while opening on Mozilla Firefox. 
2. Focus on 'Browse' through inspector.
3. On input class, these many values could be seen - ng-untouched ng-pristine ng-invalid
4. Add any file(image, pdf etc) through browse option. Focus on 'Browse' through inspector.
5. On input class, these many values could be seen - ng-dirty ng-valid ng-touched
6. Which means after adding file, input status is 'valid' now.

Same process is done on google chrome browser. On step 5, I could see input class is still 'ng-invalid'.

This means, if I apply Validators, it won't work correctly. If I keep a 'submit' button, and it expects input file, to be valid, submit button will never be enabled. It will always be in disabled condition if the formcontrol is set as Validators.required.

## What is the motivation / use case for changing the behavior?
Validation works perfectly for input type 'text' etc. But it doesn't work for input 'file' type, only in chrome browser. If it works fine in chrome too, then it would be good for developers.

**Below is stackblitz link for expected behavior. If it is opened in Firefox, then after adding file, submit button is enabled. But on chrome, submit button is not enabled even if file is added.**

https://stackblitz.com/edit/angular-oyrydn

## Environment
Angular version: 5.2.8(Detailed version could be seen on stackblitz demo I provided)

Browser:
- [ ] Chrome (desktop) Version 65.0.3325.181 (Official Build) (64-bit)
- [ ] Firefox version 59.0.2(64 bit)
- [ ] IE version 11
 
For Tooling issues:
- Node version: v9.10.1
- Platform:  Windows

Others:
NA

**Comment by jotatoledo** [comment]
Dup of https://github.com/angular/angular/issues/23011?

**Comment by kara** [comment]
File inputs aren't actively supported yet; track #23011 for progress on this.
