### ISSUE TITLE
Provide Symbol as value

### ISSUE THREAD

**Issue by william-lohan** [angular/angular#23170]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
With InjectionToken

    export const MY_SYMBOL = new InjectionToken<Symbol>('mySymbol');

providing Symbol as value

    {
      provide: MY_SYMBOL,
      useValue: Symbol('mySymbol')
    }

throws error

chrome
> Cannot create property '__anonymousType' on symbol 'Symbol(mySymbol)'

edge
> Assignment to read-only properties is not allowed in strict mode

## Expected behavior
Provides symbol by token.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-xi8mdw

## What is the motivation / use case for changing the behavior?
Providing unique symbol

## Environment

<pre><code>
Angular version: 5.2.8

Browser:
- [x] Chrome (desktop) version 65
- [ ] IE version 11 (works surprisingly)
- [x] Edge version 41
 
For Tooling issues:
- Node version: 9.8.0  
- Platform:  Windows 
</code></pre>

Same error as https://github.com/angular/angular/issues/13314 but this is providing a symbol with an InjectionToken not using symbol as a token.

**Comment by alxhub** [comment]
Obsolete; this is a bug that was fixed in Ivy.
