### ISSUE TITLE
is tsd updated with the latest version?

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#2318]
I'm just wondering if the tsd typings are up to date with the latest alpha version, because it seems like the typings are at version `22` and the alpha version available for dev preview on npm is at `25`.

If so, how else could we have the typings in sync with the current alpha version on npm? Or can we build angular from the `atscript` directory that comes with the dist from npm?

**Comment by gdi2290** [comment]
I have a PR open for about 12+ days now https://github.com/borisyankov/DefinitelyTyped/pull/4432 which only only meant to serve as a quick fix until the offical one is pushed out. I think it's nearly done so they might be an official update soon. Feel free to use the one in the PR

**Comment by rolandjitsu** [comment]
@gdi2290 I am not very familiar with tsd and typescript, first time trying it, so may I ask how do I tell tsd to take your patch instead of the official one?

**Comment by rkirov** [comment]
Will be fixed as part of https://github.com/angular/angular/issues/1803

**Comment by rolandjitsu** [comment]
@rkirov do you have an aprox. timespan for when the next release with this fix will be done?

**Comment by rolandjitsu** [comment]
@gdi2290 so how do I grab a the current angular typings?

*Note that I use `npm install` to get Angular 2, and then I just build into a single file using almost the same process as the `es5build.js` that comes with the rest of the files in `es6/prod` folder (but I also build Rx using systemjs-builder and I add the router too). Furthermore, I include `Reflect.js`, `zone.js` and `long-stack-trace-zone.js` along since Angular has a dependency on those as well (or so it seems to have).*

But everything kind of throws errors in the terminal right now since I am missing the right typings. I have tried though to use the `angular2.d.ts` that is present is the same folder `es6/prod`, but that one throws even more errors (`StringMap`, `Map`, etc. - are all missing and so on ...).

Some help would be appreciated, because I have a hard time figuring out how to make it all fit together when using Typescript :)

**Comment by gdi2290** [comment]
@rolandjitsu post your repo here

**Comment by rolandjitsu** [comment]
@gdi2290 [https://github.com/rolandjitsu/ng2-play](here) it is. The `master` branch has is written with js and transpiled with Traceur, but the `ts` branch is where I tried switching to TS, but failed. In `gulpfile.js` there is a `test-ts` task which compiles the TS files.

**Comment by gdi2290** [comment]
@rolandjitsu there is a new update for Angular 2 typings. could you update yours? Although it's limited only to types in `angular2/angular2`

**Comment by rolandjitsu** [comment]
@gdi2290 I'll give it a try, to bad the `angular2/router` typings are not updated.

**Comment by rolandjitsu** [comment]
@gdi2290 does it mean that the typings will always be kept the same from now on? All under `angular2/angular2`? Or will we have typings mapped the same as the folder structure you have?

Also, what's the plan for `angular2/router` typings?
