### ISSUE TITLE
[Doc] Validating form control based on the value of another form control should be explained in the docs

### ISSUE THREAD

**Issue by zetsnotdead** [angular/angular#23182]
I've been answering a lot of Angular questions on stackoverflow lately, and one question that comes up again and again is: 

> how to validate one form control based on the value of another form control?

I think it would be nice if there was an example in the official docs of this kind of validator. Maybe it could be another item under the `CustomValidators` section in the `Form Validation` chapter?

If this receives positive feedback, I'd love for this to be my first contribution to the Angular docs.

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently the docs do not have an example of validating one form control based on the value of another form control.

## Expected behavior
The docs should have an example of validating one form control based on the value of another form control.

## What is the motivation / use case for changing the behavior?
A lot of users ask for this kind of validator on stackoverflow, and it would be nice if I could point them to the official documentation.

**Comment by kapunahelewong** [comment]
Cross validation in the demo is a great idea. I've had to use this _a lot_ in my front end dev jobs. And that position in the docs makes sense to me. @jenniferfell @chembu or @brandonroberts could one of you take a look at @zetsnotdead's idea?

**Comment by jenniferfell** [comment]
@zetsnotdead Hi. I apologize for letting this sit. (We were finishing v6.) If you'd like to contribute this to the  docs, that would be great! For general contributor info, see here: https://github.com/angular/angular/blob/master/CONTRIBUTING.md

My team's also shared our wiki (in progress), if you need more github or doc-specific info: https://github.com/ExpertSupport/doc-workflow/wiki

And we're here to help!

**Comment by zetsnotdead** [comment]
Thank you for your reply. I would still like to contribute this to the docs. I'll start working on this tomorrow :fire: Should be done in a couple of days.

**Comment by jenniferfell** [comment]
Fantastic! Thank you so much. No rush. Enjoy your weekend.

**Comment by zetsnotdead** [comment]
Got it done during the weekend. The PR has the documentation change with appropriate e2e test. I'd appreciate any feedback.

**Comment by jenniferfell** [comment]
@zetsnotdead Wow, you're quick! Thanks! I tagged a couple reviewers from the team, and I'll give it a look wrto to editorial style.

**Comment by zetsnotdead** [comment]
Is there anything I can do on my part to speed up the review process?

**Comment by brandonroberts** [comment]
Fixed via https://github.com/angular/angular/pull/23743
