### ISSUE TITLE
enable asp.net web api session when working with angular5 on localhost

### ISSUE THREAD

**Issue by noah2233** [angular/angular#23180]
In production mode I have the angular 5 client and the web api on the same site so I have no problem with the session but in development mode my angular 5 is hosted on localhost:4200 which reset the session on each call to a service.

I can host the angular 5 and the web api on the same host on development mode but it means I have to do ng build all the time(which will have a big overhead).

Any ideas? Should I use the session? or there is a better way?

**Comment by noah2233** [comment]
What do you mean by proxy?
My angular 5 run on localhost in dev mode and does call the startup.cs file so I am not sure it helps me.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
