### ISSUE TITLE
Upgraded components with angular-dynamic-loader

### ISSUE THREAD

**Issue by nickbullock** [angular/angular#23183]
Hello. I don't know this issue fall into the bug report or feature request, so i just describe it.
## I'm submitting a...

<pre><code>
[x ] Bug report 
[x ] Feature request
</code></pre>

## Current behavior
I have a hybrid ng1-ng5 application. I use UpgradeComponent to updrade some ng1 components to ng5 <code>@Directive</code> as described here https://angular.io/api/upgrade/static/UpgradeComponent 
Then i want to render it dynamically with https://github.com/gund/ng-dynamic-component it based on https://angular.io/guide/dynamic-component-loader.
When i trying to use it i've got: 
<pre>Error: No component factory found for Component. Did you add it to @NgModule.entryComponents?</pre>
OK, but when i added my component to entryComponents i've got:
<pre>Component cannot be used as an entry component.</pre> - because it is <code>@Directive</code>

So how can i use upgrade components with dynamic loader? It works with ng5 components perfectly.

## Expected behavior
I can use upgraded components with ng5 dynamic loader.

## What is the motivation / use case for changing the behavior?
I need to render both type of components dynamically: upgraded ng1 and n5

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [x ] Chrome (desktop) version 65.0.3325.181 (Official Build) (64-bit) (cohort: Stable)

 
For Tooling issues:
- Node version: 8.10.0
- Platform:  Windows 10

</code></pre>

**Comment by nickbullock** [comment]
I think i solved it with some hack - just use <code>@Component</code> instead of <code>@Directive</code> with empty template(and don't forget to add your component to entry components), like this: 
<pre><code>
@Component({
  selector: 'my-component',
  template: ''
})
export class MyComponent extends UpgradeComponent {
constructor(elementRef: ElementRef, injector: Injector) {
    super('my-component', elementRef, injector);
  }
}
</code></pre>
But i want to see angular's team answer.

**Comment by nickbullock** [comment]
I've fixed the problem with following code:
<pre>
@Component({
  selector: 'my-component,
  template: ''
})
export class MyComponent extends UpgradeComponent {
  constructor(elementRef: ElementRef, injector: Injector) {
    super('Component', elementRef, injector);
  }
}
</pre>

1) Changed `@Directive` to `@Component`
2) Added empty template
3) Added MyComponent to entryComponents

Is this expected and known behavior?

**Comment by gkalpak** [comment]
Upgraded components are indeed not designed to be used as `entryComponents` or be dynamically loaded. It should be easier to dynamically load the AngularJS components directly.

If the empty-template component trick works for you, feel free to use it.

##
<sub>Closing this, since this is not a usecase we intend to support.</sub>
