### ISSUE TITLE
Support IDE autocomplete for ngPreserveWhitespaces 

### ISSUE THREAD

**Issue by tytskyi** [angular/angular#23198]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

IDE will not autocomplete or suggest attribute `ngPreserveWhitespaces` when typing in template.

## Expected behavior

IDE suggests or completes `ngPreserveWhitespaces` when typing in angular template, after triggering particular IDE's helper command.

This can be achieved by adding `ngPreserveWhitespaces` directive (it is empty, does nothing) to the `CommonModule`.

## Minimal reproduction of the problem with instructions

Demo, plunkr N/A.

In WebStorm go to angular template. On any tag type `ngPre`. CTRL SPACE. Autocomplete does not come up.

## What is the motivation / use case for changing the behavior?

Faster placing `ngPreserveWhitespaces` without copy-pasting or creating a snippet, or custom directive.

## Environment

<pre><code>
Angular version: 5.2.9

Browser: N/A
 
For Tooling issues: N/A

Others: WebStorm 2018.1
</code></pre>

**Comment by IgorMinar** [comment]
I updated the subject to reflect the problem and not the solution.

**Comment by MattiJarvinen-BA** [comment]
It also seems like ngPreserveWhitespaces is not documented at all.

**Comment by pkozlowski-opensource** [comment]
> It also seems like ngPreserveWhitespaces is not documented at all.

@MattiJarvinen-BA you can find the documentation here: https://angular.io/api/core/Component#preserveWhitespaces

**Comment by MattiJarvinen-BA** [comment]
@pkozlowski-opensource  ah, but not in https://angular.io/guide/aot-compiler#preservewhitespaces

**Comment by dylhunn** [comment]
This would have to be a language service feature -- adding the directive to common has a runtime impact.

**Comment by dylhunn** [comment]
This is rare enough that we probably don't want to special case it in the language service, actually.
