### ISSUE TITLE
Shared modules to share components through lazy-loaded modules, is failing with strange errors

### ISSUE THREAD

**Issue by Zerokk** [angular/angular#23192]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Our application has a parent module with a menu, and two child modules (but there are more to come) that share some components. If I use the menu to switch between these modules, they break because of the annoying bug that happens when you declare components in two different modules.

## Expected behavior
After moving all the components declaration to a shared module, and removing them from both child lazy-loaded modules, I expected the app to work, as many guides and posts in StackOverflow and this page suggest. **But the app will just crash with random errors, just like this**:

![](https://i.stack.imgur.com/bVCgu.png)

You can find my stackoverflow question here: 
https://stackoverflow.com/questions/49671270/angular-lazy-load-modules-duplicated-components?noredirect=1#comment86354032_49671270

## Minimal reproduction of the problem with instructions
Here you have a pastebin with the current status of all our NgModules:

https://pastebin.com/seuc6ZB9

The routes work perfectly and each component does too, so it's some error in these modules declaration, that I can't spot.

## What is the motivation / use case for changing the behavior?
This is a business app. It should work. I hereby admit my knowledge of how NgModules work is not extensive, but I find that normal since the design followed is very, very poor and buggy, as far as I experienced. 

The fact of having to use a shared module is a bad design decission. In the end, it is incredibly hard to escalate, since components will have to be either in separate modules, or be all of them imported in the modules that require them, even if there are components in that module that aren't needed by the importer.

But what really annoys here, is that not even this approach seems to work. **Probably, I'm skipping something important** and somebody will point to an _obvious_ error and fix it, but I'm not capable of seeing it this far. 

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ X ] Firefox Quantum
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.0
- Platform:  Windows 10

-----

Any help will be highly appreciated!

**Comment by Zerokk** [comment]
Honestly, I don't get these downvotes mixed with lack of help. As far as I've seen, I'm not the only one who is concerned about the design of Angular lazy-loading modules, and in this case I followed the info I could find in the web about this topic. That's why I've posted this as a bug report, tho it can be (and probably is) some trouble in my code.

Still looking for some help.

**Comment by Zerokk** [comment]
Good news here: could finally fix the issue and get this working. The problem was with the component-specific imports, which needed to be in the shared module too.

But honestly, I'm still not happy with this design. It's a bit weird and I think the Angular team should think in reworking it... but at least, it works now!

**Comment by IgorMinar** [comment]
@Zerokk thanks for posting about the resolution. I agree with you that our lazy-loading story while working is too error prone and awkward in certain situations. Ivy is going to simplify this whole thing significantly. Stay tuned for Angular v7!!! I can't wait.
