### ISSUE TITLE
Duplicate license headers are present in `umd.min.js` and fesm files

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#23190]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Following a conversation with @filipesilva about license headers in packages, I noticed that at the moment license headers are not being removed in `umd.min.js` This will cause bundles to be bigger.

## Expected behavior
License headers are not avilable in the minified umd bundle. 

## Minimal reproduction of the problem with instructions
https://unpkg.com/@angular/common@6.0.0-rc.1/bundles/common.umd.min.js
https://unpkg.com/@angular/common@6.0.0-rc.1/fesm2015/common.js

<pre><code>
Angular version: 6.0.0-rc.1

**Comment by IgorMinar** [comment]
The issue is that there are duplicate license headers in the bundle. It's expected that each bundle will contain one license header.

This should not cause any size regressions for Angular CLI users though because CLI dedupes the license headers.

**Comment by alxhub** [comment]
As far as I can tell, this isn't a regression - there don't seem to be more license headers in v6 vs v5. In v4 there are far fewer headers but they don't seem to be sanely placed, so my guess is the v4 tooling was simply not including headers that it should have.

**Comment by IgorMinar** [comment]
this is still an issue as in 10.0.0-rc.0

https://unpkg.com/@angular/common@10.0.0-rc.0/fesm2015/common.js
https://unpkg.com/@angular/common@10.0.0-rc.0/bundles/common.umd.min.js

**Comment by JeanMeche** [comment]
This is no longer the case : https://unpkg.com/@angular/common@16.0.0/fesm2022/common.mjs
