### ISSUE TITLE
service-worker missing "badge" in "NOTIFICATION_OPTION_NAMES"

### ISSUE THREAD

**Issue by HiveSolution** [angular/angular#23196]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When displaying notification on mobile using the service-worker, the ```badge``` in the payload seems to be ignored and only the default notification bell icon is displayed.

## Expected behavior

Display the notification badge as sent by the the payload and not use any default icons.

## Minimal reproduction of the problem with instructions

Default service-worker setup and send any notification payload containing a ```badge``` url.
The badge will not be displayed. The default notification bell icon will be used instead.

When looking at the generated ```ngsw-worker.js``` I noticed the ```const NOTIFICATION_OPTION_NAMES```. It appears to be listing the option that are used by the service worker to display notifications.
When adding ```badge``` to the array, it will display as expected. The badge option is simply missing from the notification options.

## Environment

<pre><code>
Angular version: 5.2.5
    "@angular/animations": "^5.2.5",
    "@angular/cdk": "^5.2.1",
    "@angular/common": "^5.2.5",
    "@angular/compiler": "^5.2.5",
    "@angular/core": "^5.2.5",
    "@angular/forms": "^5.2.5",
    "@angular/http": "^5.2.5",
    "@angular/platform-browser": "^5.2.5",
    "@angular/platform-browser-dynamic": "^5.2.5",
    "@angular/router": "^5.2.5",
    "@angular/service-worker": "^5.2.5",

Browser:
- [ ] Chrome (desktop) version XX
- [  X ] Chrome (Android) version 65.0.3325.109
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by HiveSolution** [comment]
I've noticed that I wasn't running the newest Version of Angular and the service-worker. So I did a quick update and the problem still exists.

On a bit of a closer look at the source it seems to be a problem with the ```servie-worker/worker/src/driver.ts```

It's, like i was guessing earlier, missing the ```badge``` option.

https://github.com/angular/angular/blob/1fac5f4eb16204d677bba4206a643239274523c6/packages/service-worker/worker/src/driver.ts#L33

Adding Badge and compiling again seems to make it work just fine.

**Comment by gkalpak** [comment]
Sounds reasonable :smiley: Thx for investigating, @HiveSolution 👍
Would you be up to submitting a PR with the fix?

##
I was going through the [ServiceWorkerRegistration#showNotification()][1] docs on MDN and we also seem to be ignoring the `image` property.

Since this is experimental technology, I expect the options properties will likely change in the future. Why not just pass through the [data.notification][2] object as is, @alxhub?

[1]: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification
[2]: https://github.com/angular/angular/blob/1fac5f4eb16204d677bba4206a643239274523c6/packages/service-worker/worker/src/driver.ts#L278

**Comment by gkalpak** [comment]
Thx, @HiveSolution!

I know it can be overwhelming the first couple of times :grin:
(Wait until you have to also run the tests. With bazel. On Windows :grin:)
We are working on smoothing things out 😳

In the meantime you did great. Thx for the investigation and fix. I left a couple of minor comments on the PR.
❤️
