### ISSUE TITLE
issue in compiling

### ISSUE THREAD

**Issue by mayur055** [angular/angular#23191]
hi 
i am new to angular need help with a small concern when ever i am running my angular project and want to perform another task like create component or anything else i use to press Ctrl+c to exit the execution it ask for "^**CTerminate batch job (Y/N)?**" when ever the task performed by me accidentally and i type N or n it is still terminating is it the issue with my angular setup or every one is facing and can anyone please help me to fix it .
thanks in advance

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
