### ISSUE TITLE
ngc --watch doesn't work with extends and relative paths in tsconfig

### ISSUE THREAD

**Issue by steveblue** [angular/angular#23208]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When a tsconfig extends another, ngc will compile but the watcher does not listen for changes.

``` bash
$ node_modules/.bin/ngc -p config/tsconfig.dev.json --watch
: Compilation complete. Watching for file changes.
```

When a file is changed ngc does not react to the change. Here is a quick example of the tsconfig:

tsconfig.dev.json (in root/config directory)

``` javascript
{
  "extends": "../tsconfig.json",
    "compilerOptions": {
        "outDir": "../build",
        "target": "es5",
        "module": "commonjs",
        "noImplicitAny": false
    },
    "angularCompilerOptions": {
        "skipMetadataEmit": true
    },
    "include": [
        "../src/**/*"
    ]
}
```

tsconfig.json (in root directory)

``` javascript
{
    "compilerOptions": {
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "moduleResolution": "node",
        "declaration": false,
        "sourceMap": true,
        "typeRoots": [
            "node_modules/@types"
        ],
        "types": [
            "node",
            "jasmine",
            "karma"
        ],
        "lib": [
            "es2017",
            "dom"
        ]
    }
}
```

When tsconfig.dev.json is in the root directory and doesn't contain relative paths, it works with the watcher.

## Expected behavior

The watcher listens for changes in files when relative paths are used in config.
 
## Minimal reproduction of the problem with instructions

This repo will reproduce this issue. Steps to reproduce are in the README.
https://github.com/steveblue/ngc-watcher-error

## What is the motivation / use case for changing the behavior?

ngc should allow engineers to organize config as desired and still use the watcher.

## Environment

<pre><code>
Angular version: 6.0.0-rc.1 and 5.2.9

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4  
- Platform:  Mac OS 10.13.3 
- TypeScript: 2.7.2

Others:
</code></pre>

**Comment by alxhub** [comment]
Unfortunately the repro posted doesn't work any longer, but I believe this bug is fixed as the CLI uses a split tsconfig with relative paths now, as do our internal compiler tests for incremental builds.

I'm going to close this as a resolved bug, but feel free to open a new one if it's still an issue in Angular 9+.
