### ISSUE TITLE
Get error Module not found: Error: Can't resolve

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular#23203]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I use a custom type in ts files. After compiling components I get js files with require this d.ts file. If I try to run the application, then I get an error ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve './some' in '/src/app'

This happened when I started using angular 5

## Expected behavior

Compiled js files without require d.ts file

## Minimal reproduction of the problem with instructions

1. Clone this repo https://github.com/dxvladislavvolkov/exampleWithdts
2. Run npm i
3. gulp build.ngc
4. Check app.component.js file. You can see a line var some_1 = require("./some");

With angular 4 everything works correctly

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by alxhub** [comment]
(the reproduction uses Angular 4.4.7, so it doesn't exhibit the problem)

This is a Typescript change - Typescript now writes the `require` statement as (my guess is) it cannot guarantee that the import doesn't have side effects.

Really, you shouldn't use a `.d.ts` file to declare types in your own program anywhere. Use a `.ts` file for this purpose.
