### ISSUE TITLE
Regression: locales seem to be incorrect in 6.0.0-rc.2: ng serve fails to compile

### ISSUE THREAD

**Issue by jnizet** [angular/angular#23217]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Adding these 3 lines in app.module.ts:

```
import { registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/locales/fr';

registerLocaleData(localeFr);
```

, in a brand new project using Angular 6.0.0-rc.2 and Angular CLI 1.7.4 makes the build fail with the following error:

```
WARNING in ./node_modules/@angular/common/locales/fr.js
10:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

Note: although it just looks like a warning, any attempt at using a locale-related pipe, like date for example, leads to a runtime error:

```
Uncaught Error: Cannot find module "."
    at webpackMissingModule (fr.js:10)
    at eval (fr.js:10)
    at eval (fr.js:16)
    at Object../node_modules/@angular/common/locales/fr.js (vendor.bundle.js:14)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (app.module.ts:5)
    at Object../src/app/app.module.ts (main.bundle.js:50)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (main.ts:4)
    at Object../src/main.ts (main.bundle.js:66)
webpackMissingModule @ fr.js:10
(anonymous) @ fr.js:10
(anonymous) @ fr.js:16
./node_modules/@angular/common/locales/fr.js @ vendor.bundle.js:14
__webpack_require__ @ inline.bundle.js:55
(anonymous) @ app.module.ts:5
./src/app/app.module.ts @ main.bundle.js:50
__webpack_require__ @ inline.bundle.js:55
(anonymous) @ main.ts:4
./src/main.ts @ main.bundle.js:66
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:74
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1
client:147 [WDS] Warnings while compiling.
warnings @ client:147
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
wrapFn @ zone.js:1188
ZoneDelegate.invokeTask @ zone.js:421
Zone.runTask @ zone.js:188
ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
client:153 ./node_modules/@angular/common/locales/fr.js
10:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@angular/common/locales/fr.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

## Expected behavior

It should compile and run fine

## Minimal reproduction of the problem with instructions

 - `ng new localebug`
 - edit the package.json file to use angular 6.0.0-rc.2, zone.js 0.8.25, rxjs 6.0.0-rc.0
 - `yarn`
 - edit app.module.ts to add the three lines above
 - edit app.component.html to add `{{ '2018-04-06T08:56:00.000Z' | date:'longDate' }}`
 - `ng serve`

Or even simpler:

 - `ng new localebug`
 - edit the package.json file to use angular 6.0.0-rc.2, zone.js 0.8.25, rxjs 6.0.0-rc.0
 - `yarn`
 - edit app.component.html to add `{{ '2018-04-06T08:56:00.000Z' | date:'longDate' }}`
 - `ng serve --locale=fr`

## Environment

<pre><code>
Angular version: 6.0.0-rc.2

Browser:
- [x] Chrome (desktop) version 65.0.3325.181
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 59.0.1 
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.11.1  
- Platform: Mac 

Others:

</code></pre>

**Comment by ztan** [comment]
I am having the same issue.

**Comment by ocombe** [comment]
Apparently the correct esm5 files are available in `@angular/common/esm5/`, so if you change your code to:

```ts
import { registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/esm5/fr';

registerLocaleData(localeFr);
```

it should work without any error, until we fix the build, or the documentation & the cli

**Comment by jamajamik** [comment]
It does not seem that  locales are present  under esm5 or esm2015 directories for  "@angular/common": "^6.0.0-rc.3"  (tested on windows platform) ....

**Comment by cexbrayat** [comment]
Looks like this is still failing in rc.4...
