### ISSUE TITLE
Falsy routes are considered active

### ISSUE THREAD

**Issue by trichetriche** [angular/angular#23224]
## I'm submitting a...
<pre><code>[ X ] Bug report 
[ X ] Feature request
</code></pre>

## Current behavior

When a route is not defined, it is considered active by the `routerLinkActive` : 

````typescript
routeTwo: string[];
````

````html
<div class="proof routeOne" [routerLink]="['routeOne']" routerLinkActive="active">Route one is active</div>
<div class="proof routeTwo" [routerLink]="routeTwo" routerLinkActive="active">Route two is active</div>
````

## Expected behavior

When a route is undefined, it should not be marked as active, because it isn't. 

## Minimal reproduction of the problem with instructions
[Here is a stackblitz](https://stackblitz.com/edit/angular-vgim23?file=app%2Fapp.component.html), and here is the minimal code to try if you don't have access to stackblitz

**Module**
````typescript
const routes = [
  { path: 'routeOne', component: HelloComponent },
  { path: 'routeTwo', component: HelloComponent },
  { path: '', redirectTo: 'routeOne', pathMatch: 'full' },
];

@NgModule({
  imports:      [ BrowserModule, FormsModule, RouterModule.forRoot(routes) ],
  declarations: [ AppComponent, HelloComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }
````
**Component** : juste declare an empty variable `routeTwo` in the typescript. For the HTML : 
````html
<div class="proof routeOne" [routerLink]="['routeOne']" routerLinkActive="active">Route one is active</div>
<div class="proof routeTwo" [routerLink]="routeTwo" routerLinkActive="active">Route two is active</div>

<router-outlet></router-outlet>
````

**CSS**
````css
.proof {
  display: inline-block;
  margin: 12px;
  padding: 12px;
  background: teal;
  color: white;
  border-radius: 5px;
}

.active {
  border: 1px solid red;
}
````
## What is the motivation / use case for changing the behavior?

As a developer, when I want to make conditional routing, I would like to define empty routes (for disabled routing) that aren't considered as active to avoid UI confusion. 

## Environment

<pre><code>
Angular versions:

    "@angular/animations": "5.2.6",
    "@angular/cdk": "5.2.3",
    "@angular/common": "5.2.6",
    "@angular/compiler": "5.2.6",
    "@angular/core": "5.2.6",
    "@angular/flex-layout": "2.0.0-beta.10-4905443",
    "@angular/forms": "5.2.6",
    "@angular/http": "5.2.6",
    "@angular/material": "5.2.3",
    "@angular/platform-browser": "5.2.6",
    "@angular/platform-browser-dynamic": "5.2.6",
    "@angular/router": "5.2.6",
    "@angular/cli": "1.7.1",
    "@angular/compiler-cli": "5.2.6",
    "@angular/language-service": "5.2.6",

Browser:
- [ ] Chrome (desktop) version 65.0.3325.181
- [ ] Firefox version XX version 56.0.2
 
For Tooling issues:
- Node version: v8.11.1
- Platform:  Windows 10 Profesionnal Edition (64 bits)

</code></pre>

**Comment by jasonaden** [comment]
Closing as duplicate.
