### ISSUE TITLE
Multi slot content projection with child component

### ISSUE THREAD

**Issue by will-l-h** [angular/angular#23233]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[X] Feature request
</code></pre>

## Current behavior
I'd like to be able to use multi-slot content projection on content from a child component. Currently, only ng-content without a select pulls in the content as a catch all.

## Expected behavior
In the attached stackblitz, the bottom "nested" example would look the same as the top "direct" example 

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gitter-jbrwyi

## What is the motivation / use case for changing the behavior?
I'm developing a library component that will wrap various other custom components as cards which can be collapsed, maximized, have custom controls in each title bar, etc. For that reason, it doesn't work to only project the content in from the parent template.

## Environment

<pre><code>
Angular version: 5.2.9, 6.0.0 rc1

Browser:
- [X] Chrome (desktop) version XX

**Comment by vicb** [comment]
This is not how content projection works.
You can only project direct child of the the content (your nested tile has no content).

**Comment by will-l-h** [comment]
Thanks, @vicb, but I don't quite follow; could you elaborate a little? In my stackblitz, the tile-nested has 

```
<div class="header">nested foo</div>
<div class='body'>nested bar</div>
```

and that is projecting into the ng-content in the tile (showing up in the red border). I just cannot get it to project into the multi slot with the select filter.

**Comment by mlc-mlapis** [comment]
@will-l-h ... here `tile` is **directly** process **select** only on `<tile-nested></tile-nested>` content (and not the template of `TileNested` component as you probably would like) so ...
```
<tile>
   <tile-nested></tile-nested>
</tile>
```
... neither `<ng-content select=".header"></ng-content>` nor `<ng-content select=".body"></ng-content>` hasn't any effect and `<ng-content></ng-content>` is applied which leads to project the content `<tile-nested></tile-nested>` which is finally rendered as the template of `TileNested` component when this component is instantiated.
```
<div style="border: 5px solid green;">
   content should be in this div<br/>
   <ng-content select=".header"></ng-content>
   <ng-content select=".body"></ng-content>
</div>
<div style="border: 5px solid red;">
   <ng-content></ng-content>
</div>
```

**Comment by will-l-h** [comment]
@mlc-mlapis, @vicb I get that it's not working the way I want, but why isn't this a valid use case (...a feature request)? 

A developer that wants to use my Tile library component has some custom component with certain features. In some areas, he wants to use his component directly and in others he wants to project his component into the tile.  This could work if I could apply the ng-content selectors but instead I can only use the single-slot ng-content.

**Comment by mlc-mlapis** [comment]
@will-l-h ... I would like notice that Angular compiler creates the code / JS functions ahead of time. It is not a run-time thing. So imagine how it would work if any nested level would be combined with any other ... how many combination it would be ... and cross the whole just the principle of no duplicity.

As I know there are plans how to extend the possibility and other scenarios above current status but all of them are scheduled / planned after Ivy new view engine because many things should be more easy to do / implement.

**Comment by will-l-h** [comment]
But that doesn't really address why single slot works in the scenario I'm after but multi-slot does not.

**Comment by mlc-mlapis** [comment]
@will-l-h ... lol, so can you describe by the most simple case once more what you would like to work with multi-slot? Just to understand 100% ...
