### ISSUE TITLE
Problem in bundles since Angular 6.0.0-rc.1

### ISSUE THREAD

**Issue by uparlange** [angular/angular#23238]
## I'm submitting a...

<pre><code>
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Unable to load my application, "ng packages" are no more created (ng.core, ng.common, ....) 

## Expected behavior

Bundles should export right packages
PS : I'm still having problem with tslib that is not correctly exported in bundles (#22971)

## Minimal reproduction of the problem with instructions

Angular 6.0.0-rc.0 --> OK
https://unpkg.com/@angular/core@6.0.0-rc.0/bundles/core.umd.js
(factory(**(global.ng = global.ng || {}, global.ng.core = {})**,global.rxjs,global.rxjs.operators));

Angular 6.0.0-rc.1 --> KO
https://unpkg.com/@angular/core@6.0.0-rc.1/bundles/core.umd.js
(factory(**(global.npm_package = {})**,global.tslib,global.rxjs,global.rxjs.operators));

--> And there is the same problems with all bundles !

## What is the motivation / use case for changing the behavior?

Bundles should export right packages

## Environment

<pre><code>
Angular version: 6.0.0-rc.1

Browser: ALL

</code></pre>

**Comment by anokori** [comment]
coz of these?
[https://github.com/angular/angular/blob/master/packages/core/rollup.config.js#L13-L14](url)

is it correct?
`'rxjs': 'rxjs'` should be `'rxjs': 'Rx'`
`'rxjs': 'rxjs.operators'` should be `'rxjs': 'Rx.operators'`

exist on the other packages too

**Comment by trotyl** [comment]
@anokori That's correct, the RxJS v6 has changed the UMD global name to `rxjs`.

The error 
 is caused by: 
 https://github.com/angular/angular/blob/1fac5f4eb16204d677bba4206a643239274523c6/packages/core/BUILD.bazel#L21

**Comment by ocombe** [comment]
Do you still have the error with rc3 that was just released? It was an emergency release to fix the ng packages, maybe it fixed your issue?

**Comment by CaerusKaru** [comment]
@ocombe Definitely still a problem, see the latest bundle [here](https://unpkg.com/@angular/core@6.0.0-rc.3/bundles/core.umd.js)

**Comment by alexeagle** [comment]
FYI https://github.com/angular/angular/blob/master/packages/core/rollup.config.js#L13-L14 is no longer used, it's part of the legacy build which will be removed after 6.0 final. Sorry this is confusing during the transition.

**Comment by alexeagle** [comment]
thanks for reporting this @uparlange !
