### ISSUE TITLE
Generation of guides during project development by Angular-CLI

### ISSUE THREAD

**Issue by splincode** [angular/angular#23246]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
As a matter of fact, now only commands are generated, what and how to launch.

## Expected behavior
[React CLI](https://github.com/facebook/create-react-app) generates the whole documentation, which is extremely convenient because there even have videos and animations of what and how to do. Although React is not a framework, it's just a library, the guys tried to make it easier to run projects.

```
$ ng new my-project # also generate with README.md + GUIDE.md
$ ng new my-project --skip-guide # generate with README.md
```

Because the project is huge and it is not always possible to understand what and to what this structure is generated. How to write tests immediately and for what they are, what are the pitfalls and how to develop the project and what should be avoided.

At least a minimal development guide would be a smart update.

**Comment by trotyl** [comment]
Should have nothing to do with this repo, but only [Angular CLI](https://github.com/angular/angular-cli).

**Comment by splincode** [comment]
@trotyl Ok, I closed this
