### ISSUE TITLE
Angular animation ngFor 

### ISSUE THREAD

**Issue by Ascolon** [angular/angular#23245]
Hi. There is a list that is displayed with the help of nFor. An animation is added to the list item. How to start the animation when the list item is added to the markup.
I want to animate the appearance of a list item.

**Comment by Ploppy3** [comment]
https://angular.io/guide/animations#example-entering-and-leaving

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
