### ISSUE TITLE
[ServiceWorker] localhost took too long to respond. HTTP ERROR 504

### ISSUE THREAD

**Issue by MrCroft** [angular/angular#23240]
## I'm submitting a...
```
[x] Regression (a behavior that used to work and stopped working in a new release)
```
Not sure if it's a regression, I just assume since #21636 was closed and I was advised to open a new issue.

## Current behavior
Offline mode doesn't work when using the ServiceWorker.

## Expected behavior
Offline mode should work when using the ServiceWorker.

## Minimal reproduction of the problem with instructions

1. Clone: https://github.com/MrCroft/ng6-sw
2. `npm i`
3. `ng build --prod`
4. `http-server dist/ng6/`
5. Access the app at the `url:port` mentioned in the terminal.
6. Stop http-server
7. Refresh the page:

![image](https://user-images.githubusercontent.com/2809154/38459836-bc6741dc-3ab7-11e8-82b7-53a43498e1a6.png)
Steps 1-2 from above can simply be replaced with:
```
> ng new ng6 --skip-install
> cd ng6
  - Replace "6.0.0-rc.1" Angular version in package.json with "6.0.0-rc.2")
  - Add "@angular/service-worker": "6.0.0-rc.2" to package.json
> npm i
> ng g serviceWorker --project ng6
```
while having an Angular CLI version >=6.0.0-rc.1 installed globally.

## Environment
```
Angular: 6.0.0-rc.2
Angular CLI: 6.0.0-rc.2
```
Browser:
- [x] Chrome (desktop) latest `65.0.3325.181 (Official Build) (64-bit)`
Haven't tested on other browsers.
 
For Tooling issues:
- Node version: 8.11.1
- Platform:  Mac x64 & Win x64

**Comment by gkalpak** [comment]
This is actually an issue with generating `ngsw.json`. The files are not properly picked up, resulting in empty asset-/data-groups. Let's track it in angular/angular-cli#10297.

**Comment by alejonext** [comment]
Is the same error in version `6.1.4`

**Comment by zain-b** [comment]
Having the same issue, Angular 8
