### ISSUE TITLE
Some examples are really outdated

### ISSUE THREAD

**Issue by rafaelss95** [angular/angular#23254]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
A lot of demo/examples in code are really outdated. Just search by `plnkr`.

Ex (`2.0.0-alpha.37`):

https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/common/src/directives/ng_for_of.ts#L91-L98

## Expected behavior
The demos/examples should be up to date.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
duplicate of https://github.com/angular/angular/issues/21525

**Comment by rafaelss95** [comment]
Oops, thanks. I've searched by "plnkr" and didn't find any issue. It was did if I searched by `Plunker` :)
