### ISSUE TITLE
viewContainerRef.clear() should give destroyed components :leave animation time

### ISSUE THREAD

**Issue by AndrinGautschi** [angular/angular#23256]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When destroying a dynamically created component with :enter and :leave animations, the :leave has no time to be executed. 

## Expected behavior

The viewContainerRef.clear() should give back an Observable which completes when everything has run correctly. 

## Environment

<pre><code>
Angular CLI: 1.7.3
Node: 9.7.0
OS: darwin x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, route

Browser:
- [x] Chrome (desktop) version 65.0.3325.181 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.7.0
- Platform:  Mac

Others:

</code></pre>

**Comment by xingguangsixian** [comment]
I feel that I have the same issue。
If I import BrowserAnimationsModule into AppModule, the componet will be deffered destory。
The old component will be destoryed after that  the new component be loaded.
In this case,the data in the old component will be repeated loading.
I feel like the issue .#22509

**Comment by dicbrus** [comment]
I tried to reproduce this bug, but seems everything is working as a charm

here is the repo
[https://stackblitz.com/edit/angular-hgzffe](url) at stackblitz

:leave animation starts and finishes.

**Comment by pkozlowski-opensource** [comment]
Going to close this one for now as we haven't heard back with the reproduce scenario and got a report of things working properly. If anyone is still facing this / similar issue please open a new bug report with a reproduce scenario.
