### ISSUE TITLE
Router: Has no mocks or testing utilities for location - makes testing extremely difficult.

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2325]
Ideally, I'd like to do something like

```dart
void test() {
  expect(mockRouter.lastNavigatedto, 'oldUrl');
  clickOnSomethingThatCausesNavigation();
  expect(mockRouter.lastNavigatedTo, 'newUrl');
}
```

**Comment by matanlurey** [comment]
Hi Naomi, can we up the priority on this? Any page that uses navigation (e.g., a lot) will require a mock or fake router to not effect other tests and allow developers to expect certain states (e.g. navigation, navigation failed).

**Comment by naomiblack** [comment]
yes, thanks for also filing internal issue b/21620768 with prioritization. Raised to P1 (P3 is my default "absent other info, filed with a `cust:` label" prioritization)

**Comment by btford** [comment]
We have this, but it's not exported in builds: https://github.com/angular/angular/blob/master/modules/angular2/src/mock/location_mock.ts

@tbosch @mhevery – How do we handle this for other parts of Angular?

**Comment by btford** [comment]
@tbosch – we chatted about how best to handle the class hierarchy on Friday, and I've since implemented these changes. Can you please review? I really want to get this in today.
