### ISSUE TITLE
Add the ability to use templates in the routing

### ISSUE THREAD

**Issue by splincode** [angular/angular#23269]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

Now, if I want to do something simple, I have to do wrappers. If the decorator properties @Сomponent could be directly used in options, it would be great.

## Current behavior
```ts

@Component({
  select: 'root-child'
  template: `<router-outlet></router-outlet>`
})
export class RootChildComponent {
}

// ..

export const routes: Routes = [
{ path: '', component: AppComponent },
{ path: '/children', component: RootChildComponent, chidlren: [
    { path: 'abc', component: AbcComponent },
    { path: 'def', component: DefComponent },
    ...
  ]  
 }
];
```

## Expected behavior
Example 1:

```ts
export const routes: Routes = [
{ path: '', component: AppComponent },
{ path: '/children', 
  componentProps: {
     template: '<router-outlet></router-outlet>' // fast proxy writing
  },
  children: [
    { path: 'abc', component: AbcComponent },
    { path: 'def', component: DefComponent },
    ...
  ]  
 }
];
```

Example 2:
```ts
export const routes: Routes = [
{ path: '', component: AppComponent },
{ path: '/not-found', 
  componentProps: {
     template: '<div class="global-style"> 404 </div>'
  }
 },
{ path: '**', redirectTo: '/not-found' }
];
```

**Comment by jotatoledo** [comment]
When you start with that, what will stop devs from putting even larger chunks of html templates in the routes definition? Styles? Providers? Etc. This potentially adds unnecessary complexity to the routing

**Comment by RedmatchAngular1** [comment]
If we have opportunities to declare components with a simple function in future. I guess something similar could get a go.
