### ISSUE TITLE
TitleCasePipe not working with latin characters

### ISSUE THREAD

**Issue by odahcam** [angular/angular#23267]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Words like `FOGÃO` are turned into `FogÃO`.

## Expected behavior
Words like `FOGÃO` are turned into `Fogão`.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-titlecase-latin-bug?file=app/app.component.html

## What is the motivation / use case for changing the behavior?
Because that's not title case in my language.

## Environment

<pre><code>
Provided by the StackBlitz demo.

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11 
- Platform:  Windows 10 Pro 

Others:

</code></pre>

**Comment by trotyl** [comment]
Should have been fixed by https://github.com/angular/angular/pull/22600, which landed in `6.0.0-rc.1`.

**Comment by odahcam** [comment]
Confirmed, works.

Angular 5 will not receive any patchs after v6 release?

**Comment by trotyl** [comment]
This is technically a breaking change, even with more people in favor of the new behavior, there might be some user depends on the existing behavior, so I guess it shouldn't be merge into v5.

**Comment by odahcam** [comment]
Sad to hear that. :(
