### ISSUE TITLE
Proposal: User-defined DefFeatures to extend component's capability

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#23264]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Goal

Allow users to *install* capabilities into components or directives by using ngIvy's `DefFeature` system. Mainly, it will become APIs for third-party library authors.

## Motivation

For example, if I want to implement observable lifecycle like `onDestroy$` in my Component, User-defined DefFeature can solve it.

Currently, it needs to hand-written code.

```ts
@Component({})
class SomeComponent implements OnDestroy {
  onDestroy$ = new EventEmitter();

  ngOnDestroy() {
    this.onDestroy$.emit();
  }
}
```

With the proposal, it can be able to write as like  below:

```ts
// user-defined feature
// emit an event on destroy automatically
const OnDestroy$Feature = (def: DirectiveDef) => {
  const proto = (def.type.prototype as any) as OnDestroy$;

  const emitter = proto.onDestroy$;
  if (emitter == null) {
    return;
  }
  const existingHook = def.onDestroy;
  if (existingHook) {
    def.onDestroy = () => {
      emitter.next();
      existingHook();
    }
  } else {
    def.onDestroy = () => {
      emitter.next();
    }
  }
}

interface OnDestroy$ {
  onDestroy$: Subject<any>;
}

@NgModule({
  // install the feature to the compiler
  features: [OnDestroy$Feature],
  declarations: [SomeComponent],
})
class AppModule { }

@Component({})
class SomeComponent implements OnDestroy$ {
  // detected by the feature.
  onDestroy$ = new EventEmitter();
}
```

With Hand-written definition:

```ts

class SomeComponent {
  onDestroy$ = new EventEmitter();

  static ngComponentDef = defineComponent({
    type: SomeComponent,
    factory: function SomeComponent_Factory() {
      return new SomeComponent();
    },
    features: [OnDestroy$Feature],
  });
}
```

## Outline

* Expose `ComponentDefFeature` type as a public API.
* Allow `@NgModule` to take `ComponentDefFeature[]`

**Comment by trotyl** [comment]
> Allow @NgModule to take ComponentDefFeature[]

Technically `ComponentDefFeature` is only a component-level stuff. Imaging `OnChangesFeature`, some component want to implement `ngOnChanges` wouldn't mean the same of rest of its module; also `HostFeature`, not every components in a module needs to be `entryComponent` and got special treatment.

**Comment by lacolaco** [comment]
I think the important thing is that users can install third-party DefFeature via the librarie's NgModule. 
For simplicity, component-level feature definition is good, but still we have to edit all components which use onDestroy$.
As well as built-in lifecycle hooks, it may be better to allow user-defined features to be installed at ngModule (or compiler)-level.

**Comment by trotyl** [comment]
My thought is that one of Ivy's goal is make everything tree-shakable. But as pure side-effect, `DefFeature` won't be optimized even if it's declared by accident (or forget to remove). 

Also `DefFeature`s could produce bad performance impact on start-up time and memory if auto-installed on a bunch of components.
