### ISSUE TITLE
@angular/common/locales/es not well formatted

### ISSUE THREAD

**Issue by Nerioth11** [angular/angular#23262]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Even the translations are correct, the months and days are missing a capital letter at the beginning. It's very annoying. 

## Expected behavior
The correct format should be like this one attached here.
[es.zip](https://github.com/angular/common-builds/files/1883502/es.zip)
Would be awesome to have this fixed in the main angular version ^^ Thanks!

## What is the motivation / use case for changing the behavior?
Weird capitalization of the months and days in my language.

## Environment
Angular version: Latest version available.

Browser:
All browsers.

**Comment by ocombe** [comment]
Hello, Angular uses [CLDR](http://cldr.unicode.org/) data for all i18n values, if you believe that there is a mistake in those data, please open an issue on the CLDR repository: http://cldr.unicode.org/index/bug-reports
Thanks!
