### ISSUE TITLE
HttpClient post type inference error

### ISSUE THREAD

**Issue by timn** [angular/angular#23266]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Issuing a HttpClient.post request with observe='response' and responseType='text' is resolved to a return type of ```Observable<Object>```, rather than the expected ```Observable<HttpResponse<string>>```.

## Expected behavior

Correct return type inference.

## Minimal reproduction of the problem with instructions

Create a new Angular app with:
- ng new angular-type-inference-error
- Then copy https://gist.github.com/timn/fce04f84e8391d12f1d013ad1c4168ef to src/app/app.component.ts.
- build the code ```ng build```
The error is:
```
ERROR in app/app.component.ts(24,5): error TS2322: Type 'Observable<Object>' is not assignable to type Observable<HttpResponse<string>>.
  Type 'Object' is not assignable to type 'HttpResponse<string>'.
    The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
      Property 'body' is missing in type 'Object'.
```
Just changing the "post" into a "get" leads to proper type inference and the code compiles without error. The function prototypes look similar. I couldn't make out the error within the time I had available.

## Environment
```
# ng --version
Angular CLI: 1.7.4
Node: 8.11.0
OS: linux x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

**Comment by alxhub** [comment]
The second argument to `HttpClient.post` is a body value, not the options object. So what you're actually doing is making a POST request with a JSON body containing `{ headers: headers, params: params, observe: 'response', responseType: 'text' }`, and not configuring the request.

Closing as a support request / not an issue in Angular.
