### ISSUE TITLE
add language service for vim

### ISSUE THREAD

**Issue by towc** [angular/angular#23261]
## disclaimer
I opened an issue here because I couldn't find anywhere else to do it. If someone can point me there, that would be most appreciated

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I open vim, and I can't do all the awesome things that the language service provides! So I lay down and cry in panic

## Expected behavior

I google "vim angular language service", install it with my favorite bundler (Vundle), use it, and live happily

## Minimal reproduction of the problem with instructions

google "vim angular language service" and stare at the lack of useful responses

## What is the motivation / use case for changing the behavior?

I really want to use vim with angular :,(

## Environment
vim.

<pre><code>
Angular version: ANY

definitely

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Linux 

Others:

</code></pre>

**Comment by trotyl** [comment]
[Language service](https://langserver.org/) are all implemented on the virtual interface and by design editor-agnostic, I guess you're requesting answer for "how to make a vim plugin based on language service".

**Comment by towc** [comment]
@trotyl I thought angular might want its official plugin for that, like it does for vscode, for example. Is this correct?

**Comment by towc** [comment]
there's a company behind it that is trying to sell a product. Vim users
rely on the open source community for pretty much everything. I won't have
time to write my own implementation any time soon :/ But I guess this isn't
the place to request it either. If someone on the team is interested, maybe
they can pick it up, although I guess it's not too urgent?

**Comment by IgorMinar** [comment]
we'd love for the Angular community to create and maintain an integration like this.

from the Angular team only @matsko uses vim for building Angular apps, so we are really the wrong people to do this since we won't be using it ourselves. We do understand that there are community members that use vim and we ask that the once that are enthusiastic about having angular language service support in vim build it and share it with the rest of the community.

**Comment by AmebaBrain** [comment]
For vim users there are available a few plugins with TypeScript support. While it's not 100% substitute for native Angular language service, but from TypeScript perspective they cover pretty much everything.

I use [tscompletejob](https://github.com/runoshun/tscompletejob) plugin, which uses new vim async api.   Another popular plugin is [tsuquyomi](https://github.com/Quramy/tsuquyomi). But it uses sync api and freezes on larger projects.
