### ISSUE TITLE
Unable to get  upcoming absolute url from RouterStateSnapshot/ActivatedRouteSnapshot.

### ISSUE THREAD

**Issue by nehaagrawal** [angular/angular#23277]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Unable to get  upcoming absolute url from RouterStateSnapshot/ActivatedRouteSnapshot.

Is there a way to achieve this in angular router?

## Expected behavior

 It's gives only relative url. Currently I am only getting the relative url like /product not http://localhost:4200/product.

## What is the motivation / use case for changing the behavior?

 I can't use this.router.navigateByUrl('/product'); because I need to send the absolute path to non-angular code.If I have to map it to angularjs ui-router, we had something like this.

var absoluteUrl = $state.href(toState, toParams, { absolute: true })

## Environment

<pre><code>
Angular version: 4.3.0

Browser:
- [x ] Chrome (desktop) version 65.0.3325.181 
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4
- Platform:  Windows

Others:

</code></pre>

**Comment by sandangel** [comment]
FYI https://stackblitz.com/edit/angular-4mhif3?file=app%2Fapp.component.ts

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Also, if this is a bug report, it needs a StackBlitz to repro the issue.
