### ISSUE TITLE
Angular.io routerLink with dynamic parameters

### ISSUE THREAD

**Issue by vijender1256** [angular/angular#23273]
I am trying to build navigation links dynamically which also has optional paramteers 

  

  ```
  <mat-list-item *ngFor="let link of itemSummarylinks" class="app-sidenav-content">
                <a mat-list-item [routerLink]="[link.routerLink,itemCode,'edit']">
                    {{link.name}}
                </a>
    </mat-list-item>
```

Below is the route:

   ```
  { path: 'general-product-attributes/:id', component: eneralProductAttributesDetailComponent },
     { path: 'general-product-attributes/:id/:edit', component: GeneralProductAttributesEditComponent }
```

if the path is :

   ```
 [general-product-attributes/35/Edit] --> it should edit componenet
    [general-product-attributes/35]--> it should flow to detail componement
```

so how to build router dynamically:

  ```
  [routerLink]="[link.routerLink,itemCode,'edit']"
    [routerLink]="[link.routerLink,itemCode,'']"
```

if i pass empty in the place of edit it should navigate to detail componenet but it give errors , can we achieve with angular router ?

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
