### ISSUE TITLE
rxjs里面没有throwError模块

### ISSUE THREAD

**Issue by zhangtingwz** [angular/angular#23278]
man i am a newbee,
I have a problem :
import { Observable, throwError } from 'rxjs'; 
in this word ,rxjs not have export any throwError ,
please answer for me 
我是一个新手，我有一个问题
import { Observable, throwError } from 'rxjs'; 
rxjs 里面没有任何的export throwError
模块“"c:/Users/huajie/Desktop/新建文件夹/my-app/node_modules/rxjs/Rx"”没有导出的成员“throwError”。

**Comment by dereklin** [comment]
import { _throw } from 'rxjs/observable/throw';

**Comment by zhangtingwz** [comment]
very thank your help @dereklin 
so in the https://angular.cn/guide/http
```
private handleError(error: HttpErrorResponse) {
  if (error.error instanceof ErrorEvent) {
    // A client-side or network error occurred. Handle it accordingly.
    console.error('An error occurred:', error.error.message);
  } else {
    // The backend returned an unsuccessful response code.
    // The response body may contain clues as to what went wrong,
    console.error(
      `Backend returned code ${error.status}, ` +
      `body was: ${error.error}`);
  }
  // return an observable with a user-facing error message
  return throwError(
    'Something bad happened; please try again later.');
};
```
that throwError should be change to _throw . is it?
非常感谢你的帮助，所以官方文档上面的throwError需要改成为_throw,对吗

**Comment by trotyl** [comment]
`import { Observable, throwError } from 'rxjs';` is correct, but only for RxJS v6+.

So you shouldn't wrting that you're using RxJS v5.

For any problem of `angular.cn`, please report it to https://github.com/angular/angular-cn as it's not maintained by this repo.

**Comment by zhangtingwz** [comment]
Thank you very much @trotyl ,
forgive me please，i thing maybe it`s my code has worry or my node-module version has diffrent from the newest one. And i follow angluar`s blow to the github,that i ask my question in it ,sorry

**Comment by trotyl** [comment]
Even it's not a problem with the code, but the default version used is indeed confusing:

![image](https://user-images.githubusercontent.com/6059170/38543296-c992c5d6-3cd6-11e8-9f04-94bd5868f888.png)

Since it's not a consistent behavior to `angular.io`, you do can report it as a BUG (but in the right repo).

**Comment by zhangtingwz** [comment]
thank you ， i learn it  from u teach ，not have the second

**Comment by jasonaden** [comment]
Closing as resolved.
