### ISSUE TITLE
Angular.io is not working

### ISSUE THREAD

**Issue by michaeljota** [angular/angular#23286]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

angular.io is not working. 

Error in console:
```Uncaught SyntaxError: Unexpected end of input```

## Expected behavior

No errors

## Minimal reproduction of the problem with instructions

[angular.io](https://angular.io/)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by IgorMinar** [comment]
I can't reproduce this. If the problem still persists, can you please file a new issue and provide more details about the problem including:
- what file fails to parse
- are the any errors in the network tab of devtools
- what browser/version do you use
- what's your geographical location (we've seen problems like this related to regional edge cache corruption in the past)

thanks

**Comment by michaeljota** [comment]
I was failing. The error was the one I posted. I was in my job. 

I just tested in Edge, and Chrome (Android) and worked. Weir. Thanks you.
