### ISSUE TITLE
ERROR Error: Uncaught (in promise): NoMatch: {}

### ISSUE THREAD

**Issue by splincode** [angular/angular#23282]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
app.routing.ts

```ts
export const routes: Routes = [
  {
    path: '',
    canActivateChild: [AuthGuardService],
    children: [
      {
        path: '',
        loadChildren: 'app/view/dashboard/dashboard.module#DashboardModule'
      }
    ],
    pathMatch: 'full'
  },
  {
    path: 'login',
    component: LoginComponent
  },
  {
    path: '**',
    redirectTo: '/'
  }
];

```

dashboard.routing.ts

```ts
const CommonRoutes: Routes = [
  {
    path: '',
    component: ProcessQueueComponent
  },
  {
    path: 'process/:processId',
    component: ProcessComponent
  }
];

export const routes: Routes = [
  {
    path: '',
    component: DashboardComponent,
    children: [
      {
        path: '',
        redirectTo: 'task-queue'
      },
      {
        path: 'task-queue',
        children: CommonRoutes
      },
      {
        path: 'report-queue',
        children: [
          ...CommonRoutes
          {
            path: 'process-start',
            component: ProcessStartComponent
          }
        ]
      }
    ]
  }
];
```

Repro: https://stackblitz.com/edit/angular-gizvaj?file=app%2Fdashboard.module.ts

```
ERROR
Error: Uncaught (in promise): NoMatch: {}
```

**Comment by IgorMinar** [comment]
@splincode can you provide a stackblitz repro please?

**Comment by splincode** [comment]
@IgorMinar Yes, sorry, for some reason I forgot to attach a link.

Repro: https://stackblitz.com/edit/angular-gizvaj?file=app%2Fdashboard.module.ts

**Comment by jasonaden** [comment]
It appears your redirect is not being parsed correctly. See this:

https://stackblitz.com/edit/angular-7xmnh4?file=app%2Fdashboard.routing.ts

where the redirect was changed to add `./` at the beginning.

This is still an issue as the error message should probably be more clear.

**Comment by martinsik** [comment]
I think this should show the same problem but it's stripped off all unnecessary things:

https://stackblitz.com/edit/angular-a7sxdf?file=app%2Fapp.routing.ts

**Comment by splincode** [comment]
@jasonaden any update?
