### ISSUE TITLE
Dynamically associate component with route based on route parameter

### ISSUE THREAD

**Issue by bin-cc-aryd-cc-igits** [angular/angular#23294]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Hi everyone!!!
At present, there is no way to dynamically associate a component with a route using router parameter(s).

# I would like to write my route definition as follows:
`const routes: Routes = [
  {
    path: 'form/:country/',
    component: someComponentLoaderMechanism(:country)
  }
]
// where someComponentLoaderMechanism() is a method or factory that can supply a particular component at run time based on the route parameter
`

# Instead of writing route definition for each route and associated component

`const routes: Routes = [
  {
    path: 'form/US/',
    component: UsaFormComponent
  },
  {
    path: 'form/CA/',
    component: CanadaFormComponent
  }
]
`

## Environment

<pre><code>
Angular version: 4.4.6+

Browser:
- [x ] Chrome (desktop) version XX
- [x ] Chrome (Android) version XX
- [x ] Chrome (iOS) version XX
- [x ] Firefox version XX
- [x ] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x ] Edge version XX
 
For Tooling issues:
- Node version: v9.8.0
- Platform:  any

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@binarydigits ... you can do it right now. Just have a master component that will subscribe to `params` and then dynamically creates another component which is required / logic dictates.

**Comment by jotatoledo** [comment]
@mlc-mlapis yeah but its kinda weird to define a component only to encapsulate the factory logic. IMO a service would be better suited for this, that implements an interface similar to `RoutedComponentResolver {resolve(router: RouterSnapshot, next: ActivatedRouteSnapshot): Type<any>;}`

**Comment by mlc-mlapis** [comment]
@jotatoledo ... yep, I agree. 👍 My comment was primarily focused just on the fact that the requested feature is available today. 😄 It wasn't meant as the best way how to do it.
