### ISSUE TITLE
anchor href attribute throws: TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by shroffshyam** [angular/angular#23295]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

i m creating an anchor tag to download from a http link, which is a variable. But i get  weird error on the first click on this anchor tag, it works fine but i m not sure why does it through error in console.
Please see the image for the error stack.

## Expected behavior

It should not throw any error on click

## Environment

<pre><code>
   <a download class="btn btn-small btn-primary" *ngIf="row.isExportable" [href]="row.exportLink"> Export button </a>

Angular version: 5.2.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>
![screen shot 2018-04-10 at 4 04 56 pm](https://user-images.githubusercontent.com/2181543/38580808-f3c9afd4-3cd8-11e8-95f4-a81249249327.png)

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

**Comment by IgorMinar** [comment]
@ericmartinezr +1
