### ISSUE TITLE
Router features

### ISSUE THREAD

**Issue by btford** [angular/angular#2329]
/cc @matsko @IgorMinar – These are the outstanding items based on our discussions the past few days:

- [ ] "//" (double-slash) syntax for overlays (plus good name – maybe reclaim "sibling" here somehow)

---

Behavior of rerouting during a navigation:
- [ ] before any components are committed, cancel and start over (recognition, canActivate, or loadResources/resolve) phases
- [ ] if any components are committed (any phases after load/resolve), then finish current nav before beginning the next

---

Databinding from parent component's outlet to child component

---

Allow user metadata in route configs

---

Examples (e2e tests)

**Comment by nikaspran** [comment]
Would it be possible to request a bit more transparency on the direction of the router?

The current notion of sibling components was removed with only mentions of another solution down the road, but AFAIK there is no public information on what that might look like. All the documentation is outdated and less than helpful.

**Comment by naomiblack** [comment]
@matsko @btford it looks like this is slipping another week. Can you provide a status update, and whether it should go in alpha-29 or alpha-30? Is @matsko still the right owner?

**Comment by havenchyk** [comment]
@btford is there any progress here? Could you please explain the current state?

**Comment by btford** [comment]
I've split this into #2774, #2775, #2776, and #2777.

@havenchyk – check the weekly meeting notes, or GH issues with the relevant tag – https://github.com/angular/angular/issues?utf8=%E2%9C%93&q=label%3A%22comp%3A+router%22+
