### ISSUE TITLE
Compiler should not take templateRoot

### ISSUE THREAD

**Issue by mhevery** [angular/angular#233]
https://github.com/angular/angular/blob/master/modules/core/src/compiler/compiler.js#L41

The compile method should be give the Component only. It should not take the templateRootElement. I believe this is left over when we were thinking that the template will come from the inline case. 

This needs to be fixed to pave the way for WebWorkers.

**Comment by naomiblack** [comment]
@rkirov @tbosch is there still work to be done on this?
