### ISSUE TITLE
polyfills.bundle.js  6152 line, error：RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by lovepanda603** [angular/angular#23305]
![image](https://user-images.githubusercontent.com/12789995/38600801-02dd653c-3d98-11e8-90b1-27f52d33f6c5.png)
![image](https://user-images.githubusercontent.com/12789995/38600819-1e991f8c-3d98-11e8-9179-b0369e180848.png)
What can cause this problem?
My browser  is:
![image](https://user-images.githubusercontent.com/12789995/38600975-a21cd59c-3d98-11e8-99bd-27299a732552.png)
Only a small number of mobile phones will appear.

**Comment by splincode** [comment]
Please add repro (repository or stackblitz)

**Comment by vicb** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
