### ISSUE TITLE
Remove DynamicChangeDetector.hydrated method

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#2330]
It is not used (except in tests) and removing it will allow us to add concrete type on the `context` field in the generated change detectors.

/cc @vsavkin

**Comment by vsavkin** [comment]
I don't mind removing `hydrated`. But I don't understand how  `hydrated(): boolean { return this.values[0] !== uninitialized; }` in DynamicChangeDetector affects the generated change detectors. Could you expand on that?

**Comment by kegluneq** [comment]
Removing `hydrated` is not necessary to provide types for `context`, but if it's not being used there's no reason to keep it around.

https://github.com/angular/angular/issues/2070 tracks providing a type for `context`

**Comment by kegluneq** [comment]
Since this is not required for `context` typing, lowering its priority. @vsavkin wants to keep `hydrated` (or also remove `View#hydrated` to remain consistent), and I don't have the cycles to do that atm. @yjbanov , assigning to you to either make the case for removing `hydrated` or close.

**Comment by mhevery** [comment]
If this is not an issue for typing, we are just closing.
