### ISSUE TITLE
FR: Get ComponentRef using component instance

### ISSUE THREAD

**Issue by avber** [angular/angular#23301]
## I'm submitting a...
<pre><code>
[x ] Feature request
</code></pre>

## Expected behavior

var ref = SomeAngularBuiltinService.getComponentRef(componentInstance);

//some code to use Angular services
ref.injector.get(...)

This should also work with lazy loaded modules.

## What is the motivation / use case for changing the behavior?

It will be possible to write specialized decorators that require access to Angular built in services.

Here is an example:

export class TasksComponent implements OnInit {

  @fromRoute('id', (o: TasksComponent) => {
      o.loadTasks();
  })
  projectId: string;

//skipped
}
-----------------
It's more concise than

export class TasksComponent implements OnInit {
  projectId = '';

  constructor(private route: ActivatedRoute) {
  }

  ngOnInit() {

    this.projectId$ = this.route.paramMap
      .switchMap((params: ParamMap) =>
        params.get('id'));

      this.projectId$.subscribe(val => {
           this.projectId  = val;
          this.loadTasks();
      });
  }
--------
Currently I have to patch component factories and router config loader in order to achieve it.

**Comment by avber** [comment]
Ideally there should be a similar feature for services:

var injector = SomeAngularBuiltinService.getServiceInjector(serviceInstance);

**Comment by pkozlowski-opensource** [comment]
@avber would you mind elaborating more on the exact, real-life use-case? Forgive me, but I'm really confused here since this:

```javascript
var ref = SomeAngularBuiltinService.getComponentRef(componentInstance);
//some code to use Angular services
ref.injector.get(...)
```

Sounds like a way of accessing an injector associated with a given component (in other words, getting access to all the tokens available for a given component). 

To be honest it sounds like it would break encapsulation of component providers as those should be specifically available to component only. 

What are you trying to achieve here, in practical / functional terms?

**Comment by avber** [comment]
>What are you trying to achieve here, in practical / functional terms?

At the time of opening the issue I was trying to write class and method decorators that needed access to services configured in DI container.

In the example above the @fromRoute decorator needs access to ActivatedRoute.

class Component1 {
@fromRoute(...)
projectId: string;
}

class Component1 {
@fromRoute(...)
taskId: string;
}

As you can see the decorator knows nothing about Component1 and Component2.
It just assigns values to components' properties from routes.

Similar decorators can be used for cross cutting concerns like caching, logging, loading indicators, etc.

**Comment by vinayluzrao** [comment]
+ 1 for this. Besides the injector, ComponentRef has other properties that are highly useful to have inside the component instance, and, to my knowledge, can't be obtained any other way:
```TypeScript
abstract hostView: ViewRef
abstract changeDetectorRef: ChangeDetectorRef
abstract componentType: Type<any>
```
PS: I believe the `ViewRef` and `ChangeDetectorRef` that can be injected through the component instance's constructor are different from the ones available in `ComponentRef`, but I might be wrong on this (if I am, please let me know).

**Comment by perjerz** [comment]
How to get RootViewRef via dependency injection?
