### ISSUE TITLE
Get error "Expression has changed after it was checked" when I use pristine flag

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular#23314]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have a component with two options. For one I use ngModel directive and for the other option I, use binding with control pristine. When I change the value of an option I get error "ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'someInput: true'."

A value I expose asynchronously.
Perhaps this is due to the implementation of the ControlValueAccessor  interface

## Expected behavior

Changing the value must be done without error

## Minimal reproduction of the problem with instructions

You can see [an example](https://stackblitz.com/edit/angular-b9hhcn). (open console)

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
An `@Input` is not allowed to trigger an `@Output`, that's violating the one-way data flow.

**Comment by dxvladislavvolkov** [comment]
@trotyl Not quite understood, can you explain the problem?

**Comment by trotyl** [comment]
Your `@Input() value` will trigger an `@Output() valueChange` in the example.

**Comment by dxvladislavvolkov** [comment]
@trotyl can you help me? how can I solve this problem?

**Comment by mlc-mlapis** [comment]
@dxvladislavvolkov ... first of all don't mix template based form with reactive based one.

Recommendation: If you use just reactive based ... you avoid a lot of problems with violating the one-way data flow.

**Comment by dxvladislavvolkov** [comment]
@mlc-mlapis Does this mean that I should not use form flags (eg dirty, pristine and etc ) with custom components?

**Comment by mlc-mlapis** [comment]
@dxvladislavvolkov ... you can ... they are also on reactive based forms.

**Comment by dxvladislavvolkov** [comment]
@mlc-mlapis what is wrong in my example?

**Comment by mlc-mlapis** [comment]
@dxvladislavvolkov ... I already said ... you are mixing template based form with reactive based one.

```
<form [formGroup]="form" novalidate>
        <label for="email">Email</label>
        <text-box
            formControlName="emailControl"
            [(ngModel)]="formData.email"
            [someInput]="emailControl.pristine">
        </text-box>
    </form>
```
... with reactive forms ...
* it is not relevant to use `<form>` tag
* not use `ngModel` directive

**Comment by dxvladislavvolkov** [comment]
@mlc-mlapis okay. I understood. Thank you!
But this does not solve the problem with the error

**Comment by mlc-mlapis** [comment]
@dxvladislavvolkov ... hmm, so start again and now with just a correct code ... the best with reactive principle. You will see that this way solve a lot of problems with violating the one-way data flow.

**Notice:**
If you have an unclear case when you need to find out what is exactly the place with stands behind `ExpressionChangedAfterItHasBeenCheckedError` message ... use https://ng-run.com
https://medium.com/@a.yurich.zuev/catch-angular-template-errors-like-a-pro-or-how-i-create-angular-demo-e98694977911

And read carefully these posts:
* https://blog.angularindepth.com/everything-you-need-to-know-about-change-detection-in-angular-8006c51d206f

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
