### ISSUE TITLE
[IVY][Fix] Remove work-around for local refs on <ng-template>

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#23316]
Let's consider the following (contrived) example:

```html
<ng-template #tpl></ng-template>
{{ tpl.createEmbeddedView != null }} <!-- just to make sure that we are getting TemplateRef instance -->
```

In the above example the `tpl` variable should be of type `TemplateRef`. 

This case is not yet supported in the ngIvy compiler / runtime and this issue is opened to discuss possible solutions.

## Current work-arround

In the existing tests we are using the following work-around:

```typescript
if (cm) {
  container(0, tplContentFn, undefined, undefined, ['tpl', '']);
  text(2);
}
const tpl = getOrCreateTemplateRef(getOrCreateNodeInjectorForNode(load(0)));
text(2, tpl.createEmbeddedView != null);
```

This is obviously _not_ what we want to use long-term so what follows is a set of 3 proposals with the indication of my favourite one.

### A dedicated load instruction

The simples / most naive approach is to create a dedicated `loadTemplateRef` instruction, ex.:

```typescript
if (cm) {
  container(0, tplContentFn, undefined, undefined, ['tpl', '']);
  text(2);
}
const tpl = loadTemplateRef(0);
text(2, tpl.createEmbeddedView != null);
```

Pros:
* trivial to implement

Cons:
* compiler needs to work harder to figure out that `#tpl` is pointing to a `TemplateRef`
* not consistent with the existing local ref resolution / load code

### A dedicated local ref resolution strategy

We can't simply add another if / else to the existing local ref resolution strategy - it would be well too easy to add a piece of logic for a `TemplateRef` [here](https://github.com/angular/angular/blob/b3a10e0a42cca072ab5bc9245f7e312d5cee3e5d/packages/core/src/render3/instructions.ts#L697) but this would kill tree-shaking (we would have to bring `TemplateRef` and related code for every element / container instruction). 

Instead we could introduce a strategy for a default (without a value) local ref resolution, ex.: 

```typescript
if (cm) {
  container(0, tplContentFn, undefined, undefined, ['tpl', ''], tplRefByDefaultStrategy);
  text(2);
}
const tpl = load(0);
text(2, tpl.createEmbeddedView != null);
```

Pros:
* `TemplateRef` is only pulled for the `container` instruction
* consistent usage of the `load(idx)` instruction

Cons:
* new argument in the generated code
* `TemplateRef`- related code is pulled for JS-based blocks, even if not needed

### A dedicated instruction for `<ng-template>`

Instead of introducing a new argument to the existing instruction we could create 2 separate functions creating `LContainerNode`:
* `container` for JS blocks
* `template` for `<ng-template>`

```typescript
if (cm) {
  template(0, undefined, undefined, ['tpl', '']);
  text(2);
}
const tpl = load(0);
text(2, tpl.createEmbeddedView != null);
```

Pros:
* smallest and clearest generated code (clear separation of containers created for JS blocks vs. <ng-template>
* best tree-shaking (TemplateRef` is only pulled when `<ng-template>` is used but not for JS blocks)
* consistent usage of the `load(idx)` instruction   

Cons:
* biggest impact on the existing code (test and compiler)

## Recommendation

My proposal would be to go with the 3-rd option (A dedicated instruction for `<ng-template>`) - although it is most "laborious" one, it is also one with best properties.

**Comment by mhevery** [comment]
discussed in person and decided to go with `A dedicated instruction for <ng-template>` approach
