### ISSUE TITLE
Custom implements NgModel does not work with custom angular components

### ISSUE THREAD

**Issue by splincode** [angular/angular#23311]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

https://github.com/angular/angular/issues/3076#issuecomment-168998072

 In fact you can leverage bidirectional binding on custom components but you don't need to use ngModel. For this, just define input and output parameters for your field:

```ts
@Component({
  selector: 'my-component'
})
export class MyComponent {
  @Input() inputText : string;
  @Output() inputTextChange = new  EventEmitter();
}
```

With this, you will be able to use the syntax [(inputText)] when using your component:

```html
<my-component [(inputText)]="something"></my-component>
```

But current behavior not working 

## Expected behavior
When the model changes, the values of the root component must also change

## Minimal reproduction of the problem with instructions
Repro: https://stackblitz.com/edit/angular-cuvlxp?file=app%2Fapp.component.html

**Comment by ericmartinezr** [comment]
I don't understand what you're trying to do, or what do you expect. Do you think the parent component will know anything about the child or viceversa and that they will share their properties? The `name` binding in your child won't change the property in your parent, you have to communicate them somehow. You can read to learn a few tricks https://angular.io/guide/component-interaction. I think you misunderstood the comment you referenced.

Here's a [simple example](https://stackblitz.com/edit/angular-ruoi4a?file=app/hello.component.ts)

**Comment by robwormald** [comment]
> In fact you can leverage bidirectional binding on custom components but you don't need to use ngModel. For this, just define input and output parameters for your field

You can certainly allow two-way binding this way, but its just shorthand for `[inputText] (inputTextChange)`. 

If you want to allow ngModel usage, you need to define and implement the `ControlValueAccessor`API, which allows any component to work with NgModel, Template Forms as well as Reactive Forms. See : https://angular.io/api/forms/ControlValueAccessor

This is works as intended, as far as I can tell.

**Comment by splincode** [comment]
@robwormald It's very hard usage, I think need simple API

**Comment by splincode** [comment]
@robwormald To create your custom ngModel, you need to re-create a bunch of code, a whole class with ControlValueAccesor and a bunch of methods. But even if you use your own banana-box attribute on the component. If you forgot to make emit from the component of the event, you will not even be warned about it. It's hard!!!
