### ISSUE TITLE
Add a function to get the locale currency code

### ISSUE THREAD

**Issue by ocombe** [angular/angular#23317]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior
There is no function to get the currency code for a locale, but there are functions to get the currency symbol and name

## Expected behavior
There should be a function to get the currency code for a locale as well. See issue https://github.com/angular/angular/issues/16374#issuecomment-380480263

**Comment by petebacondarwin** [comment]
This has been implemented: https://angular.io/api/common/getLocaleCurrencyCode
