### ISSUE TITLE
ng documentation is missing command option descriptions

### ISSUE THREAD

**Issue by SetTrend** [angular/angular#23326]
Throughout the documentation of `ng` commands, their options are missing a description of the arguments they understand.

For example:

[`ng generate service`](https://github.com/angular/angular-cli/wiki/generate-service)

```
module

--module (aliases: -m)

Specifies where the service should be provided.
```

- Not a word about a module name that can be added to this option.
- Not an example whatsoever.

I believe this information should be added.

**Comment by jainanuj0812** [comment]
Can you please close this one and create an issue here https://github.com/angular/angular-cli/issues

Thanks!

**Comment by SetTrend** [comment]
Absolutely. Sorry for posting to the wrong group.
