### ISSUE TITLE
sanitizing unsafe URL value

### ISSUE THREAD

**Issue by siplavinash** [angular/angular#23335]
Hello, I have a table with imageurl column which stores path of that images and i'm trying to display on the screen by get method from specific path using web api is successfully retriving the all data but while displaying image on screen it encountered an error and WARNING: sanitizing unsafe URL value D:\StudentMangementApp\VSAPI\VSAPI\mail-baja-1024x744.jpg (see http://g.co/ng/security#xss)

unsafe:D:\StudentMangementApp\StudentMangement\StudentMangement\src\mail-baja-1024x744.jpg:1 GET unsafe:D:\StudentMangementApp\StudentMangement\StudentMangement\src\mail-baja-1024x744.jpg net::ERR_UNKNOWN_URL_SCHEME

**Comment by ericmartinezr** [comment]
>**(see http://g.co/ng/security#xss)**

Try to read the warning message.

<hr>

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
