### ISSUE TITLE
Problem in bundles with Angular 6.0.0-rc.4

### ISSUE THREAD

**Issue by uparlange** [angular/angular#23343]
## I'm submitting a...

<pre><code>
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Unable to load my application 
- I'm still having problem with compiler bundle (#23238)
- I'm still having problem with tslib that is not correctly exported in bundles (#22971)

## Expected behavior

Bundles should work as expected

## Minimal reproduction of the problem with instructions

Angular 6.0.0-rc.0 --> OK
https://unpkg.com/@angular/compiler@6.0.0-rc.0/bundles/compiler.umd.js
(factory(**(global.ng = global.ng || {}, global.ng.compiler = {})**));

Angular 6.0.0-rc.4 --> KO
https://unpkg.com/@angular/compiler@6.0.0-rc.4/bundles/compiler.umd.js
(factory(**(global.npm_package = {})**,global.tslib,global.rxjs,global.rxjs.operators));

## What is the motivation / use case for changing the behavior?

Bundles should work as expected

## Environment

<pre><code>
Angular version: 6.0.0-rc.4

Browser: ALL

</code></pre>

**Comment by uparlange** [comment]
I had this problem many times in older release. Isn't possible to have a simple web page loading all bundles and make sure everything is ok before release a version ?

**Comment by alexeagle** [comment]
@uparlange yes, our integration tests haven't been ported to run against the bazel-produced packages so we are clearly pushing releases without proper testing. Working to fix that now, thanks for being our human quality control in the gap...
