### ISSUE TITLE
Ivy: Support injection flags (Optional, Self, etc)

### ISSUE THREAD

**Issue by kara** [angular/angular#23342]
We need to support injection flags:

- [x] Optional
- [x] Self
- [x] SkipSelf
- [x] Host

e.g.

```ts
constructor(@Optional() someParentDir: ParentDir) {}
```

**Comment by LinBoLen** [comment]
I have a question. formerly such as `Host` decorated constructor parameter be solved in `template defined` injector(the parent inject is always same). does ivy will solve injector to rendered parent inject(only dir rendered, the parent inject will be assigned)

**Comment by pkozlowski-opensource** [comment]
I believe that this is implemented now.
