### ISSUE TITLE
GST-14 ⁃ onSameUrlNavigation config value not set by RouterTestingModule

### ISSUE THREAD

**Issue by lelanophilus** [angular/angular#23347]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Setting onSameUrlNavigation to 'reload' in the config for RouterTestingModule in a unit test does not update the config value in the router.

## Expected behavior
It should update the value.

## What is the motivation / use case for changing the behavior?
Unit test

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

┆Issue Number: GST-14

**Comment by jasonaden** [comment]
The issue here is the `ExtraOptions` are not all passed through with the `RouterTestingModule`. Should be a quick/easy fix to get this in.

**Comment by tjulinfan** [comment]
Hi there, is there any update on this? We have some tests are blocked by this.

**Comment by gmcgilvray** [comment]
+1 on this issue

**Comment by atscott** [comment]
As far as I can tell, as mentioned previously, this should be an easy fix: The method for setting up the testing router does not assign several of the options from the config: https://github.com/angular/angular/blob/a5ffca0576bc67df8e4076741963a6e61eeefb2a/packages/router/testing/src/router_testing_module.ts#L121-L136
Adding the community help label, as this seems like a good candidate for a contributor to fix.
