### ISSUE TITLE
Allow optionally giving an example to interpolation with i18n

### ISSUE THREAD

**Issue by Goodwine** [angular/angular#23355]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

It is not possible to specify an example for interpolation text.

## Expected behavior

We should be able to specify an example sometimes.
Renaming the variable to make more sense is fine too, or adding more context in 

## Minimal reproduction of the problem with instructions

```html
<span i18n="saying hi">
  Hello, {{ name // i18n(ph="name", ex="John") }}
</span>
```

## What is the motivation / use case for changing the behavior?

Our translators sometimes raise questions (these cause translations to be delayed) which could have been avoided if we had an example in the placeholder.

**Comment by Goodwine** [comment]
I'm talking about the undocumented placeholder expressions for interpolation placeholder renaming.

https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/compiler/src/i18n/i18n_parser.ts#L165

Normally interpolations become "INTERPOLATION", but you can change the name with `// i18n(ph="new_name")`

**Comment by vicb** [comment]
@ocombe Could you please take a look at this one.
We also need to make sure to add some documentation.

**Comment by ocombe** [comment]
It was so well undocumented that I wasn't even aware that it was possible to do that 😄 
@vicb we will need to make sure that this feature is ported to ivy as well.

**Comment by JarekToro** [comment]
How does this work while translating an attribute? Is 

Example:
```
 <span *ngIf='element.latestRecord && element.isCheckedOut()'
 matTooltip='Currently Checked Out To {{element.latestRecord?.publisherName}}'
i18n-matTooltip="@@CurrentlyCheckedOutToTooltipPopover" matTooltipPosition='right'>
```

I have been unsuccessful in making a translation file that can handle the interpolation inside of an attribute.

**Comment by petebacondarwin** [comment]
Closing as there does not appear to be much interest in this feature request.
As a workaround, I would recommend that any additional examples should be added to the description of the overall message.
