### ISSUE TITLE
Angular 6 Compilation fails when trying to lazy load a module from a package in node_modules

### ISSUE THREAD

**Issue by SoundarDinesh** [angular/angular#23358]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have a a package in my node_modules folder which was created using Ng-Packagr. This is a custom package called 'my-component-library' and we try to lazy load a module from this package like so:

const routes: Routes = [
  {
    path: 'sayheader',
    loadChildren: 'my-component-library#AppModule'
  } 
];

However when we do ng-serve --prod I get the following compiler errors:

ERROR in ./src/$$_lazy_route_resource lazy namespace object
Module not found: Error: Can't resolve 'D:/experiments/LazyLoadingTest/node_modules/my-component-library/my-component-library.ngfactory.js' in 'D:\experiments\LazyLoadingTest\src\$$_lazy_route_resource'

ng-serve(JIT) also fails with the following error:
Module build failed: Error: D:\experiments\LazyLoadingTest\node_modules\my-component-library\my-component-library.d.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

However if I change the routing config like so:
const routes: Routes = [
  {
    path: 'sayheader',
   loadChildren: () => new Promise(resolve => {
    (require as any).ensure([], require => {
          resolve(require('my-component-library').AppModule);
      })
   })
  } 
];

and use JIT it works and the module is lazy loaded.

Note: In Angular 5 the compilation and the lazy loading used to work (JIT and AOT)

## Expected behavior
Such a configuration needs to work:

const routes: Routes = [
  {
    path: 'sayheader',
    loadChildren: 'my-component-library#AppModule'
  } 
];

with ng-serve --prod. We need this working with a AOT deployment.

## Minimal reproduction of the problem with instructions
See above.

## What is the motivation / use case for changing the behavior?
See above.

## Environment

<pre><code>
Angular version:^6.0.0-rc.1

Browser:
- [x ] Chrome (desktop) version XX

 
For Tooling issues:
- Node version: 8.9.1
- Platform: Windows

Others:

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

**Comment by jasonaden** [comment]
While this looks like an interesting issue, this is a very common use case for Angular. I would suggest sending the question over to StackOverflow as it's probably just some support help.

If that's not the case, please do create an actual reproduction of the problem and create a new issue.

**Comment by trotyl** [comment]
@jasonaden No, it's never supported in Angular CLI, requested at https://github.com/angular/angular-cli/issues/6373 and not caused by Angular.

**Comment by thruba** [comment]
I'm facing the same issue, any idea?

**Comment by israphim** [comment]
Create a wrapper module inside your app that eagerly imports the library module. Then lazy load the wrapper module

**Comment by aburht** [comment]
@israphim   Appreciate your idea,  You are saying to lazy load the library modules into wrapper module this would lazy-loaded into the main module
