### ISSUE TITLE
Inconsistent behavior when @Output name matches dom event

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#23361]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Run plunker and click test.
On chrome `onActivate` is called only once (custom `EventEmitter`)
On IE 11 `onActivate` is called twice. First time with `UIEvent`, second time from custom `EventEmitter`

## Expected behavior
Dom events should overwritten by custom outputs and not emitted.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/JpxJiUS1qRFnzJw9uC9a

## What is the motivation / use case for changing the behavior?
Consistent behavior across browsers

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [ ] Edge version XX
</code></pre>

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/4059

**Comment by jasonaden** [comment]
I'm going to close this as a duplicate, and have raised the question about the original issue internally to see if we can get some eyes on it. Subscribe to that issue for updates.
