### ISSUE TITLE
Angular 5 relative navigation from a default route does not work

### ISSUE THREAD

**Issue by quasiunafantasia** [angular/angular#23364]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Precondition: there is a following set of nested routes with a redirection to a default child (Child 1)
  - `Child 1` (default) -> `Child 1 nested` route with route param
  - `Child 2` 

Relative navigation from `Child 1` to a sibling route `Child 2` does not work. Instead the navigation is made to `Child 1 nested` route with a parameter value equal to Child 2 path
The behavior is the same for `routerLink` navigation and navigation using `Router` api.

## Expected behavior

Navigation is made to `Child 2`

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-gitter-ki2ebs?file=app%2Fapp.routes.ts
## What is the motivation / use case for changing the behavior?

Navigation in this case requires workarounds with replacing the url, which is not the desired way of using Angular API

## Environment

<pre><code>
Angular version: 5.x.x (reproduces both for 5.0.0 and 5.0.1)

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX   8.9.1
- Platform:   Mac
Others:

</code></pre>

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

<hr>

If you look at your router config, you'll see that `../` isn't what you want. As your config is written, you would need `../../` in order to get to the siblings of `child-1`. So you could either change the router link as such, or change your config so you don't have the default for `child-1` as an empty-path default but instead just put the component on `child-1`:

```
{
    path: 'some-nested-path',
    children: [
      {
        path: '',
        redirectTo: 'child-1',
        pathMatch: 'full'
      },
      {
        path: 'child-1',
        component: Child1Component,
        children: [
          {
            path: ':someParam',
            component: Child1NestedComponent
          }
        ]
      },
      {
        path: 'child-2',
        component: Child2Component
      }
    ]
  }
```
