### ISSUE TITLE
Angular 6 RC4 / AOT Compilation failed with multiple lazy routing

### ISSUE THREAD

**Issue by DenisLaboureyras** [angular/angular#23360]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I tried to migrate my project to Angular 6, I have a strange error with the AOT compiler "TypeError: Converting circular structure to JSON".
I'm using webpack and ngtools to compile.
The bug isn't occurring when : 
- I'm compiling my project with the JIT compiler
- I'm compiling one lazy module with the AOT compiler
When I add a second or third lazy module, the AOT compiler isn't working anymore. Even if I tried to add a very simple module with 1 component and no dependencies

## Expected behavior

No bug, or at least an error message showing how to fix this

## Minimal reproduction of the problem with instructions

Here is the main router code
`export const routes: Routes = [
{path: 'app/:language', component: MainPage, children : [
    { path: 'app', loadChildren: '../app-module/app.module#AppModule' },
    { path: 'lp', loadChildren: '../landing-page-module/landing-page.module#LandingPageModule' },
    { path: '**', component: NotFoundPage }
]},
{ path: 'notfound', component: NotFoundPage },
{ path: '',   redirectTo: '/app/fr/home', pathMatch: 'full' },
{ path: '**', component: NotFoundPage }
]
export const routing: ModuleWithProviders = RouterModule.forRoot(routes, { initialNavigation: 'enabled' });`

## What is the motivation / use case for changing the behavior?

I want to be able to compile my application with angular 6 in AOT mode

## Environment

<pre><code>
Angular version: 6.0.0-RC.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4
- Platform:  Ubuntu 16.04
- Webpack : 4.5.0
- Typescript : 7.2.1

Others:

</code></pre>

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

**Comment by jasonaden** [comment]
Also, if you create a new issue with a repro, please let include if this is an issue specific to Angular 6. You would know if it works fine with 5x but breaks with v6.

**Comment by jkrth617** [comment]
has then been any updates with this issue? Is there a separate posting with a repo?

**Comment by DenisLaboureyras** [comment]
I has time this week to investigate a bit further (and thanks to an update of a plugin which leads me to the solution).
For a reason I don't fully understand, but with a mix of lazy modules, webpack 4 and angular 6, the chunks of the AOT builds create a circular dependency in the html-webpack-plugin.
This issue is described here : https://github.com/jantimon/html-webpack-plugin/issues/870
The solution was to change the chunksSortMode function by this one:

`var chunksSortMode = function sort(left, right) {
  let leftIndex = entryPoints.indexOf(left.names[0]);
  let rightIndex = entryPoints.indexOf(right.names[0]);
  if (leftIndex > rightIndex) {
      return 1;
  }
  else if (leftIndex < rightIndex) {
      return -1;
  }
  else {
      return 0;
  }
}`

**Comment by hesampour** [comment]
same problem. with angular 5 everything was Ok. but now I cant build with aot. the problem is that it does not find lazy router madules and errors:

Cannot determine the module for class 'some class' in  .... Add PaymentListComponent to the NgModule to fix it.
