### ISSUE TITLE
Animation not working

### ISSUE THREAD

**Issue by luuk777w** [angular/angular#23362]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
The animation is not working.
The components do wait the delay given but there is no animation.
Also see this [stackoverflow](https://stackoverflow.com/questions/49816178/angular-5-animation-not-working) question.

## Expected behavior
Well, that it animates.

## Minimal reproduction of the problem with instructions
I have made this [stackblitz](https://stackblitz.com/edit/angular-enethh).

## What is the motivation / use case for changing the behavior?
Well....
I want to animate the switch between components.

## Environment

<pre><code>
Angular version: 5.1.3

Browser:
- [x] Chrome (desktop) version 65.0.3325.181
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.8.0  
- Platform:  Windows

Others:

</code></pre>

**Comment by luuk777w** [comment]
See https://stackoverflow.com/questions/49816178/angular-5-animation-not-working

**Comment by Erogunz** [comment]
I have the exact same problem. Is there a solution for that so far?
