### ISSUE TITLE
Explain the newEvent helper function used in the live example of Testing docs

### ISSUE THREAD

**Issue by keilla** [angular/angular#23370]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

In [Testing Section](angular.io/guide/testing#component-dom-testing), there is a typo. 
The example in _Change an input value with dispatchEvent()_ section, in the test is showing 

 _nameInput.dispatchEvent(newEvent('input'));_

## Expected behavior

 nameInput.dispatchEvent(new Event('input'));

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by marzann** [comment]
Is this issue open for contribution?

**Comment by jenniferfell** [comment]
docsarea=testing
filename=guide/testing.md
URL=https://angular.io/guide/testing

@brandonroberts When you get a chance, would you look into this. The question is about the example code. Thanks!

**Comment by brandonroberts** [comment]
Hi @keilla! The code used there is not a typo. There is a `newEvent` helper function that's in the live example, but not explained in the documentation. I think it would be valuable to show it though to avoid confusion.

**Comment by brandonroberts** [comment]
@marzann this issue is open for contribution. Would you like to submit a PR?

**Comment by 1083** [comment]
So far haven't been able to find any information on this random, basically un-duck-duck-go-able `newEvent` function that's mentioned, but never imported or explained, in the docs.

**Comment by 1083** [comment]
@brandonroberts Definitely looks to be a typo: shouldn't `newEvent(...)` just be `new Event(...)`?

**Comment by brandonroberts** [comment]
@1083 its not a typo, its not just exposed in the guide. The source for the example is here https://github.com/angular/angular/blob/master/aio/content/examples/testing/src/testing/index.ts#L23

**Comment by krzysztof-grzybek** [comment]
@brandonroberts As we can in [comment](https://github.com/angular/angular/blob/master/aio/content/examples/testing/src/testing/index.ts#L21) above this method, it's created only for better compatibility between browsers:
`
Although officially deprecated, some browsers (phantom) don't accept the preferred "new Event(eventName)"
`

Since angular tests are run on Chrome by default, maybe we don't need it any more? I think it might be confusing, especially if not documented.

**Comment by jakpaw** [comment]
Hey, I would like to submit my first PR for this issue

**Comment by andrewasche** [comment]
sorry, I think i misunderstood. I don't know if any work is needed here

**Comment by kapunahelewong** [comment]
@andrewasche, you could re-open your PR and instead of changing the code, you could explain the `newEvent()` function per this comment https://github.com/angular/angular/issues/23370#issuecomment-383586018, if you would like.

**Comment by andrewasche** [comment]
Thanks for the encouragement. I tried again to explain that newEvent is not a typo, I reopened my PR and got it right this time.

**Comment by andrewasche** [comment]
next Try. . . 

I created a branch and tried to do it properly

Here is my PR:
[https://github.com/angular/angular/pull/37386](https://github.com/angular/angular/pull/37386
)
