### ISSUE TITLE
Link with wrong URL on Angular CLI page

### ISSUE THREAD

**Issue by casperschou** [angular/angular#23381]
On the https://cli.angular.io/ site, the bottom "Learn Angular"-link is linking to https://wwww.angular.io (one too many W's)

**Comment by dreamid27** [comment]
so details haha , nice one !

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/microsites/issues/15

<sub>(And actually wrong repo)</sub>

**Comment by IgorMinar** [comment]
oops. we should fix this.

**Comment by jainanuj0812** [comment]
https://github.com/angular/design-love/pull/12

Pull request is not merged yet. :)

**Comment by jenniferfell** [comment]
@IgorMinar Can you confirm that design-love is where this should be fixed and if so, please help with the PR mentioned above. Thanks!

**Comment by jenniferfell** [comment]
Notes to myself (trying out some potential labels or search keywords)
docarea=other
prexists=true

**Comment by dariobraun** [comment]
The link seems to be fixed so this issue can be closed.
