### ISSUE TITLE
[Feature request] Compile time expressions in template

### ISSUE THREAD

**Issue by bvdmitri** [angular/angular#23382]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

As i can see angular template syntax is not providing a way to declare a constant compile time expressions in template. Any `{{ expression }}`  should be invoked in runtime in order to be tracked for changing. But it might be useful to declare an expression which won't be changed, but still referenc it from component's class. 

## What is the motivation / use case for changing the behavior?

Let me show you example of use case.

```
export { globalConstMessages } from './utils/messages'

@Component({
    selector: 'app',
    template: '<p>{{ text }}</p>' // or may be some other syntax something like <p>@text</p>
})
export class MyComponent {
    public readonly text: string = globalConstMessages.someText; // <-- 'Hello world' for example
}
```

There is no way to transform this template at **compile-time** into
```
@Component({
    selector: 'app',
    template: '<p>Hello world</p>'
})
export class MyComponent {
    // empty here, no variable at all
}
```
In this case we will be able to avoid unnessesary change detections in run-time. It will be usefull in cases where we need to reuse some text messages across application, and it will be much easier to maintain this messages in one file and then only reference them as constant compile-time expression in other templates.

Also it will be a nice feature if we will be able to declare an @Input's variable of other component's as a constant compile-time expressions, but i think it will be much harder to implement.

For example
```
@Component({
    selector: 'tooltip',
    template: '<p>{{ text}}</p>'
})
export class TooltipComponent {
    @Input('text')
    public text: string;
}
```

```
@Component({
    selector: 'app',
    template: '<tooltip [text]="constantText"></tooltip>'
})
export class MyComponent {
    public readonly constantText: string = 'Hello world!';
}
```

and it should be transformed at **compile-time** into 

```
@Component({
    selector: 'app',
    template: '<p>Hello world</p>'
})
export class MyComponent {}
```

**Comment by ghetolay** [comment]
You can use template literal : 

````
export { globalConstMessages } from './utils/messages'

@Component({
    selector: 'app',
    template: `<p>${ globalConstMessages.someText }</p>`
})
export class MyComponent { }
````

But be aware that this won't use the string reference but put the content of it directly on the template. For large string this may be undesirable.

**Comment by bvdmitri** [comment]
@ghetolay Will it work with templateUrl? If not then this feature is kinda useless. 
Btw thank you for @Attribute decorator, how it might be possible that I have never heard about it😧

**Comment by dawidgarus** [comment]
This looks two separate features:
1. Inlining components. The usage is really limited to components without any dependencies and lifecycle hooks which makes it rarely useful.
2. One-time bindings

**Comment by dawidgarus** [comment]
@bvdmitri One-time bindings would much easier to implement and performance overhead would be really minimal.
Not to mention that You cannot just remove public field from component class. That's really bad idea. You need to analyze entire project in case this field is used somewhere else and it can still produce errors  that would be hard to track.

**Comment by bvdmitri** [comment]
@dawidgarus there is no need to analyze entire project in case some special syntax in template or maybe some kind of decorator which will tell that this field should be invoked in compile time and can be removed. If it used somewhere else it is not an angular problem.

**Comment by ghetolay** [comment]
@bvdmitri I wasn't sure anymore but `@Attribute` as its name indicates is about html attributes. So anything set with it will stick on the final DOM element as an attribute.

**Comment by dawidgarus** [comment]
@bvdmitri Yes there is the need. This field can be referenced in many ways. For example:
```html
<app #app></app>
{{app.constantText}}
```
or
```typescript
@ViewChild(MyComponent)
private app: MyComponent;
// app.contentText
```
or
```typescript
@Component({
    selector: 'better-app',
    template: '<tooltip [text]="constantText | uppercase"></tooltip>'
})
export class BetterComponent extends MyComponent {}
```
There are literally thousands of way it could go wrong.

**Comment by bvdmitri** [comment]
@dawidgarus Of course it is. But as I mentioned it can be marked using some special decorator. See example.
```
@Component({
    selector: 'some-component',
    template: '<p>{{ someText }}</p>'
})
export class SomeComponent {
    @ConstExpression() // or @CompileTimeExpression() not so important
    public someText: string = 'Hello world'
}

So if you will reference this variable somewhere else you are doing wrong because you marked it as a compile-time expression and of course if you reference it elsewhere outside template it won't compile at all. So i think in case some special decorator there is no need to analyze entire project.

**Comment by dawidgarus** [comment]
@bvdmitri But You still need to scan entire project for usage of that field, whether it's marked or not. It just doesn't seem like it's worth the effort.

**Comment by bvdmitri** [comment]
@dawidgarus You don't need to scan project. For example you can't access private properties of component somewhere and there is no need to scan anything. You just can't do it and that's all. 

So and here you will not be able to reference `@CompileTimeExpression()` property elsewhere outside template. It just won't compile.

**Comment by dawidgarus** [comment]
@bvdmitri Private properties don't disappear from the code. They still exist and You can access them. If You remove property from a class, You are asking for trouble. And properties that are used in template MUST be public in order for AOT to work.

**Comment by bvdmitri** [comment]
@dawidgarus Do you know what **compile-time** means? Compile-time **should not** exist in runtime.

 If you marked property as private then it should not be referenced elsewhere outside class. If you marked property as compile time, that means you know that it should not be referenced elsewhere outside template (and should be read only).

 After template compilation we can safely remove `@CompileTimeExpression` property. Or it can be `@RemoveMeAfterCompilationAndDoNotUseElsewhere`. If you don’t understand that is 100% safe removal I wont’t argue anymore.

**Comment by trotyl** [comment]
@bvdmitri Simple question: without AOT compiler, how would you like to implement that?

**Comment by bvdmitri** [comment]
@trotyl It think it can be only aot feature. In JIT there is no pre-compilation stage. Angular team said that AOT is preferable way to build angular applications. If you need JIT for some specific task this feature will be unavailable.

**Comment by bvdmitri** [comment]
@trotyl sorry, but I don't understand why it should break something. It is just additional decorator which will tell that this expression should be invoked in compile-time and then can be removed. It is not even breaking change because property should be marked explicitly.

**Comment by trotyl** [comment]
@bvdmitri AOT compilation can only change the execution timing, not the execution result. If you're suggesting something cannot be done without AOT, then that's a new programming language feature.

**Comment by bvdmitri** [comment]
@trotyl Thank you for the answer! Does it mean that compile-time expression should be a TypeScript feature (like constexpr in C++) in order to be able to implement this in Angular template engine? .

**Comment by trotyl** [comment]
@bvdmitri TypeScript does not really have something like "feature", it only provides type-checking for JavaScript:

> Goal.9 Use a consistent, **fully erasable**, structural type system.

> Non-goal.2 Aggressively **optimize the runtime performance** of programs.

> Non-goal.5 Add or rely on run-time type information in programs, or **emit different code based on the results of the type system**.

https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

**Comment by trotyl** [comment]
But this feature should still be fully feasible in JIT, without needing AOT compiler.

**Comment by trotyl** [comment]
@bvdmitri That’s not true for scripting language. 
And If you're using minifier, then the constants will be extracted to variable again, just end up burning the CPU.

**Comment by bvdmitri** [comment]
@trotyl We are talking about angular template engine, it is not a scripting language. In the example above template can be transformed
```
<p>{{ foo }}, {{ foo + 1 }}</p>
->
<p>16, 17</p>
```
during compilation stage. There is no need to extract foo variable every time if we have some mechanism (decorator or something else) with will tell angular that this expression can be evaluated and inlined in template at compilation stage.

**Comment by trotyl** [comment]
@bvdmitri Angular template compiler does not provide constant folding.

**Comment by bvdmitri** [comment]
@trotyl Yea, and that's it my feature request was about. Let angular template compiler be more intelligent, provide constant folding, let it to optimize constant expression and inline them (of course with some help from user, such as decorators etc).

**Comment by trotyl** [comment]
@bvdmitri In development, doing constant folding will be much slower than passing to JavaScript VM.
In production, a minifier should already have the same feature.

It’s meaningless for doing that.

**Comment by sod** [comment]
I guess you mean the same as [one-time-binding aka "::" in angularjs](https://docs.angularjs.org/guide/expression#one-time-binding)?

Angular1 got this feature, because dirty checking became a problem in big apps. As most apps were one big blob, everything could write in all directions, and one change detection cycle always ran at least twice to check if a change caused another change.

In Angular2+ on the other hand, detection is insanely fast. Thanks to the compiler generated methods, the browsers JIT can optimize the sh*t out of it. Sure it sounds wasteful to still check variables that might never change, but I bet it's even hart to see the performance impact in the profiler, as other tasks usually out weight the dirty checking.

And keep in mind, one-time-binding can cause bugs if used in wrong places. So your app becomes harder to understand by the developer.

Did you profile your app and found a bottleneck that a one-time-binding would fix?

**Comment by ghetolay** [comment]
Besides runtime optimization, I sometimes do not react to some inputs changes because I assume them being just one-time binding.

So for the moment it can only be a convention between component author and user. The only things you can do would be to throw an error if the input were to change.

With the framework handling one time binding we could get that error thrown from it or maybe even some linting to expose inputs not supposed to change over time.

**Comment by bvdmitri** [comment]
@sod, @trotyl  No, angular performance is great. But this feature request was not about one-time binding, it was about compile-time binding (or inlining if you prefer). The main idea of this feature comes from my practice. Imagine you have content-maker guy in your team. He is responsible for almost every text content on your site such as tooltips, popups, button names, error/success notifications text and so on. So it can be difficult to explain him where he should to edit some popup (or something else) text in hundreds of templates (especially if the same content can be used in different templates). If we had one file with all content (xml, json whatever) we could just reference this content and inline it during compilation stage.

I know this can be achieved with custom webpack loaders, but angular-cli does not provide us a possibility to change default loaders. BTW it can be usefull in other cases and thats why i proposed this feature in main issue-tracker of angular.

**Comment by trotyl** [comment]
@bvdmitri As I have mentioned above, there's no constant folding in template compiler and the macro will become deoptimization.

Since one-time binding has better performance, there's no reason to use the macro.

**Comment by trotyl** [comment]
Also, the usage (not the idea) your proposed is not feasible even in AOT.

For the code:

```typescript
export { globalConstMessages } from './utils/messages'

@Component({
    selector: 'app',
    template: '<p>{{ text }}</p>'
})
export class MyComponent {
    public readonly text: string = globalConstMessages.someText;
}
```

This could be powered by:

```typescript
declare module './utils/messages' {
  export const globalConstMessages: { someText: string };
}
```

The TypeScript code does not require to be actual raw source code. And there's no way to resolve the actual value.

**Comment by robwormald** [comment]
The AOT compiler can do a limited amount of folding - see https://angular.io/guide/aot-compiler#folding - doing much beyond this is extremely difficult. In general, we're trying to remove complexity and special-casing from the compiler, so we're unlikely to do anything here other than the limited subset we're already doing, at least in the near future.

**Comment by trotyl** [comment]
@robwormald The constant folding in AOT only happens in the **Metadata Collector**, not the **Template Compiler**, they are different cases.
