### ISSUE TITLE
Async value not resolved into ngIf/else

### ISSUE THREAD

**Issue by 39ro** [angular/angular#23387]
## I'm submitting a...
<pre><code>
[X] Bug report
</code></pre>

## Current behavior
Async value is not resolved into a ngIf/else condition.

## Expected behavior
The second value shall be populated.

## Minimal reproduction of the problem with instructions

```
   <h1>Date published: {{ (property | async)?.date_listed}}</h1>     <!-- Value is resolved, it WORKS!-->

    <div *ngIf="(property| async)?.date_listed === null; else is_published"
            (click)="publish()">Publish
    </div>

    <ng-template #is_published>

      <h1>Date published: {{ (property | async)?.date_listed}}</h1>      <!-- Value is empty, NOT WORKING -->

      <button class="button button-blue"
              (click)="unpublish()">UnPublish
      </button>
    </ng-template>
```

## Environment

<pre><code>
"@angular/core": "^5.2.0",
"angularfire2": "^5.0.0-rc.6",
</code></pre>

![ngifelse](https://user-images.githubusercontent.com/16247935/38782722-8c8ae5d4-40ef-11e8-878d-d27537fc6981.png)

**Comment by jotatoledo** [comment]
Please add a living reproduction of the issue
