### ISSUE TITLE
ServiceWorker: TypeError: Cannot set property 'next' of undefined at LruList.remove

### ISSUE THREAD

**Issue by domdeger** [angular/angular#23388]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I am building a PWA with @angular/service-worker. The app is backed up by a REST-API. So there is a resource /api/state which can be called via GET and PUT verb and shall be cached by the sw. 
Indeed I would only need the GET-Requests to be cached, if I could specifiy this. 

If i start by a freshly cleared cache following behaviour can be observed:
1. First GET request is cached and does not throw an error. 
2. PUT Requests throw following error: 
Uncaught (in promise) TypeError: Cannot set property 'next' of undefined
    at LruList.remove (ngsw-worker.js:913)
    at DataGroup.handleFetch (ngsw-worker.js:1045)

3. Next GET-Request throws:
Uncaught (in promise) TypeError: Cannot set property 'next' of undefined
    at LruList.remove (ngsw-worker.js:913)
    at LruList.accessed (ngsw-worker.js:947)
    at DataGroup.cacheResponse (ngsw-worker.js:1214)
    at DataGroup.handleFetchWithFreshness (ngsw-worker.js:1106)

## Expected behavior
There should be no errors thrown. 

## Minimal reproduction of the problem with instructions
Cannot provide this.

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  v8.9.4
- Platform:  Windows 10

Others:

</code></pre>

**Comment by gkalpak** [comment]
This has been fixed in #22769 and the fix is included in the latext 6.x releases and should be included in the next patch release (5.2.10).
