### ISSUE TITLE
has no exported member "of"

### ISSUE THREAD

**Issue by webxinyu** [angular/angular#23392]
In the Hero tutorial, an error occurred in the hero.service.ts file and there was no "of" method in the "rxjs" file.

**Comment by splincode** [comment]
Please follow the rules of writing issue template

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
