### ISSUE TITLE
`DynamicComponentLoader.loadIntoExistingLocation` should create a host element

### ISSUE THREAD

**Issue by tbosch** [angular/angular#2339]
Right now, Angular has 2 ways of loading dynamic components:

1. Using a `@Component` that does not have a view and dynamically loads another component onto the same element including the view of that component
2. Using a regular `@Directive` that creates a host view via a `ViewContainer` (i.e. a View that contains the host element of the component)

Option 1) has the following downsides:

- it allows having 2 component instances on the same element, including possible 2 app injectors on it, which can have unexpected corner cases. It can also lead to a component without a view at all.
- it does not handle animations, as we can't animate adding a shadow root. I.e. if a user wants to use option 1) + animations, he needs to use a `ViewContainer` any ways
- the only customer (GT) for which we designed it actually needs the host element

We should change option 1) into also creating a host view but inserting it as a child of a given `ElementRef`.

Note that this would also allow to remove 1 method from the `Compiler`, leaving only one public method.

**Comment by tbosch** [comment]
Code wise, this would mean for our public API:

- removing `loadIntoExistingLocation` from [DynamicComponentLoader](https://github.com/angular/angular/blob/master/modules/angular2/src/core/compiler/dynamic_component_loader.ts), leaving only `loadIntoNewLocation`, `loadNextToExistingLocation` and `loadAsRoot` which all take host ProtoViews.
- removing `compile` from [Compiler](https://github.com/angular/angular/blob/master/modules/angular2/src/core/compiler/compiler.ts), leaving only `compileInHost` as public method.
- enforcing an `@View` annotation on all classes that have a `@Component`

**Comment by matanlurey** [comment]
Let me double check.

**Comment by tbosch** [comment]
@mhevery what do you think?

**Comment by tbosch** [comment]
Talked with @mhevery in person, no red flags from there. Lowered priority to P2 as @mhevery said that removal of app injector needs to go first.

**Comment by tbosch** [comment]
Talked to Ferhat@ and he also does not need it. However, he needs the following use case:

```
<dynamic-cell>
  <text-field>...</text-field>
</dynamic-cell>
```

I.e. he wants to load a `text-field` component into a `dynamic-cell` component, and Angular should also create the `text-field` element (and not just add the component view of it).

**Comment by tbosch** [comment]
Regarding the API of `DynamicComponentLoader`: We should remove `loadNextToExistingLocation` and change `loadIntoExistingLocation` to also create the host element, but add the it as a child of the existing location.
