### ISSUE TITLE
Search Engine visibility

### ISSUE THREAD

**Issue by dalu** [angular/angular#23394]
Yes yes, keep your close trigger finger calm for a moment.

I was thinking. And I was playing around with fusebox thanks to Uri Shaked's video about fusebox and SSR and his personal page (https://www.youtube.com/watch?v=vE516nAUwFI), and the dilemma about SSR and search engine visibility in general.

Angular pages are able to be indexed, but only partially (see webmaster tools and try for yourself). Anything that needs a http request done in order to receive data isn't considered by at least Google, the dominant western search engine.

Pre-rendering everything and/or serving it via low performance nodejs/.net can't be the solution.
So the problem isn't rendering the html, the problem is just data not being indexed.
How can we counter that?

a) have Go serving the static files as an alternative to node/.net
~ meh, better than nothing. we would've accomplished just relaying the problem, we still need to do all the jumping through hoops

b) render a snapshot every interval minutes (esp useful with service worker)
So you don't take just the dist dir and copy it to prod.
You have a copy of the whole thing there and some cronjob or whatever condition triggers a prod build.

All that needs to be done is import the json from all web service endpoints via `import`.
And webpack will do the rest (or fusebox if you ask me, because it's so nice and fast)

So you have something like..

import {CustomerData} from './services/customer';
because if I can include css via import, why wouldn't I be able to include json?

or, this is the new idea that dawned just now
c) have HttpClient's promise fulfilled on rendering a prod build
or its observable actually grabbing data initially

Which ever the case, you're the experts of your framework,
web service data needs to be indexed by search engines.
This is essential. I know there are scenarios where search engine visibility isn't an issue.
I mean how come that vue and even angularjs is able to be indexed but angular isn't?
Marketing is everything and search engine visibility is free marketing.

d) you actually start bugging your own search engine team to include angular remote data in the index and tell them how

## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[x] Other... Please describe:
</code></pre>

**Comment by IgorMinar** [comment]
Hi there, good timing. I'm actually giving a talk on Angular and SEO at ng-conf in two days.

There shouldn't be any problem with fetching remote data, angular.io is an Angular app that fetches all the content as JSON files and it is fully index by google (and I've seen evidence that even some other crawlers can get to the content, but the coverage is not as great).

There are many reasons why your app could fail to render and be indexed by google. I recommend that you [check for any errors throw when the crawler is rendering your app ](https://developers.google.com/search/docs/guides/debug-rendering) and ensure that your robots.txt are not blocking any scripts needed by the app as well as any of the urls from which you fetch data.

You can watch the rest of my recommendations on Wednesday at 10:30 am – 10:50 am MDT via https://www.ng-conf.org/livestream.
