### ISSUE TITLE
Animations freeze in safari when using `ng serve --prod`

### ISSUE THREAD

**Issue by andrewseguin** [angular/angular#23401]
## I'm submitting a...
<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Safari freezes when performing an animation in an app built with `ng build --prod`

## Expected behavior

Shouldn't freeze

## Minimal reproduction of the problem with instructions

https://github.com/andrewseguin/broken-animations
Here's a repo that can be run with `ng serve --prod`. When the red div is clicked, an animation plays to change it to green. In Safari, this freezes the browser.

## Environment

<pre><code>
Angular version: 6.0.0-rc.5
CLI: 6.0.0-rc.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by nielsheeren** [comment]
I have the same issue with ng build --prod in combination with IE11 and Edge. A development build doesn't freeze those browsers.
