### ISSUE TITLE
Having a problem when transpiling with RouterModule imported in NgModule decorator

### ISSUE THREAD

**Issue by SoundarDinesh** [angular/angular#23408]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I'm unable to transpile a project, There is a build error i get when I run the ngc command. This only happens when I import the RouterModule inside the imports section of the @NgModule decorator and also set the skiptemplatecodegen. Like so:

```typescript
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    CommonModule,
    RouterModule.forChild(routes)
  ],
  // providers: [
  //   {
  //     provide: ROUTES,
  //     useValue: routes,
  //     multi: true
  //   },
  //   {
  //     provide: ANALYZE_FOR_ENTRY_COMPONENTS,
  //     useValue: routes, // provide them here too
  //     multi: true
  //   }
  // ],
})
export class AppModule { }

.....tsconfig.json
"angularCompilerOptions": {
      "strictMetadataEmit": true,
      "skipTemplateCodegen": true
    }
```

The error i get is:
Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'RouterModule' was called.

However, if i add it to through the providers section(commented out), then there is no error and the package is successfully created.

## Expected behavior
It should  transpile when adding RouterModule.forChild in the imports section and skipTemplateCodegen:true

## Minimal reproduction of the problem with instructions
I've created a repository containing the full app. Just download, npm install and then run npm run packagr, in order to reproduce the issue. The link to the repo : https://github.com/SoundarDinesh/AngularCompilerIssue.git

## Environment

<pre><code>
Angular version: 6.0.0-rc.5

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.11.1
- Platform:  Windows

Others:

</code></pre>

**Comment by FayezSalimSiemens** [comment]
I face the same issue when I use ng-packgr v3.0.0-rc.0  and angular 6.0.0-rc.5

**Comment by alxhub** [comment]
Fyi, this error typically occurs when you have multiple versions of Angular in your dependencies.

**Comment by alan-agius4** [comment]
@alxhub, this error is occurring when angular version are the same.

Also there seems to be some awkward behaviour with `fullTemplateTypeCheck` I have created a new issue with more details together with a reproduction.

https://github.com/alan-agius4/angular-issue-23609

**Comment by alan-agius4** [comment]
@alxhub any update re this issue? It's blocking a lot of people that are building a library
