### ISSUE TITLE
Typo errors in DOCS (https://angular.io/guide/comparing-observables)

### ISSUE THREAD

**Issue by chiaerichung** [angular/angular#23405]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

In the section "Observables compared to arrays" of  "Observables compared to other techniques" 
(https://angular.io/guide/comparing-observables), there are some errors in the table.
(1) the content of the cell of row "find()" and column "Array":
arr.find((v) => v>10)
5
(2) the content of the cell of the row "forEach()" and column "Observable":
obs.forEach((v) => {
  console.log(v);
})
1
2
3
4
5
(3) the content of the cell of the row "forEach()" and column "Array":
arr.forEach((v) => {
  console.log(v);
})
1
2
3
4
5
## Expected behavior

(1) the content of the cell of row "find()" and column "Array":
arr.find((v) => v>3)
5
(2) the content of the cell of the row "forEach()" and column "Observable":
obs.forEach((v) => {
  console.log(v);
})
1
2
3
5
7
(3) the content of the cell of the row "forEach()" and column "Array":
arr.forEach((v) => {
  console.log(v);
})
1
2
3
5
7

## Minimal reproduction of the problem with instructions

https://angular.io/guide/comparing-observables
## What is the motivation / use case for changing the behavior?

To correct the typo errors in the documentation.

## Environment

<pre><code>
Angular version: 5.2.10

Browser:
- [x] Chrome (desktop) version 65.0.3325.181
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
Fixed by PR https://github.com/angular/angular/pull/23407
