### ISSUE TITLE
Add AbstractControl.setEnabled(enabled: boolean)

### ISSUE THREAD

**Issue by shalomdotnet** [angular/angular#23414]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently `AbstractControl` have two methods to enable/disable: `enable()` and `disable()`.
So If I want to enable/disable according to another field I need to write:
```typescript
this.petForm.get('hasDog')!.valueChanges.subscribe((newVal: boolean) => {
    if (newVal) {
        this.petForm.get('dogName')!.enable();
    } else {
        this.petForm.get('dogName')!.disable();
    }
});
```

## Expected behavior
Add `AbstractControl.setEnabled(enabled: boolean)`, so I can write:
```typescript
this.petForm.get('petType')!.valueChanges.subscribe((newVal: string) => {
    this.petForm.get('dogName')!.setEnabled(newVal === 'Dog');
    this.petForm.get('catName')!.setEnabled(newVal === 'Cat');
});
```

## Environment

<pre><code>
Angular version: any

Browser: any

</code></pre>

**Comment by MiguelLattuada** [comment]
As an implementation alternative, it's possible to use `enable()` or `disable()` behind the scene for `setEnable(enabled: boolean)`, this will keep backwards support.
