### ISSUE TITLE
Package `@angular/http` still existing in v6?

### ISSUE THREAD

**Issue by dherges** [angular/angular#23418]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

`@angular/http@6.0.0-rc.5`

## Expected behavior

Is it intended that the "old" http package is still present in v6?

It [became deprecated in v5](https://angular.io/api/http/HttpModule)

## Environment

<pre><code>
Angular version: 6.0.0
</code></pre>

**Comment by trotyl** [comment]
> We’ll continue to support existing usage of a stable API (i.e. your code will keep working) during the deprecation period, and you’ll always have **more than 6 months (two major releases)** to update.

It’s promised to be preserved for at least two major version.

https://blog.angularjs.org/2016/10/versioning-and-releasing-angular.html?m=1

**Comment by dherges** [comment]
@trotyl Thanks for your explanation!
