### ISSUE TITLE
Angular5.x RouterLink can't url encode

### ISSUE THREAD

**Issue by j87b0003** [angular/angular#23413]
Use routerLink, URL include "&" can't encode to "%26".

**Comment by splincode** [comment]
Sorry, but follow the rules of writing issue

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
