### ISSUE TITLE
Populate multiple router outlets for a single route

### ISSUE THREAD

**Issue by pcroc** [angular/angular#23416]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
A route is configured to load a single component, in a single router outlet. To load a component in an auxiliary outlet, it needs to go into the URL separately.

## Expected behavior
A single route is able to populate multiple router outlets:

```
<div class="sidebar">
  <router-outlet name="sidebar">
  </router-outlet>
</div>
<div class="main">
  <router-outlet>
  </router-outlet>
</div>
```

```
export const routes: Routes = [
  {
    path: 'dashboard',
    components: [
      DashboardPageComponent, // Just component specified, shown in default router outlet
      { component: DashboardSidebarComponent, outlet: 'sidebar' } // Component in specific outlet
    ]
  }
];
```

## What is the motivation / use case for changing the behavior?
The above code demonstrates the use case. If I navigate to `/dashboard` I want to load a component in the main content area, and a companion component in the sidebar area, without needing to have a weird URL such as `/dashboard(sidebar:something)`.

## Environment

```
Angular CLI: 1.7.3
Node: 8.11.1
OS: linux x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

**Comment by johngrimsey** [comment]
Is there a solution/workaround to achieving this?

**Comment by thoweber** [comment]
+1

**Comment by jbirdman72** [comment]
+1

**Comment by atscott** [comment]
Closing since this is possible with empty path routes: https://stackblitz.com/edit/angular-rxye61?file=src%2Fmain.ts
