### ISSUE TITLE
currency pipe should use getLocaleCurrencySymbol() instead of getCurrencySymbol

### ISSUE THREAD

**Issue by moshmage** [angular/angular#23419]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

the interpolation of 
```
{{10 | currency:'PEN':'symbol':'1.0-3':'es-PE'}}
```
returns `PEN10`

## Expected behavior
Should return `S/.10` 
Why? Well. For one, there's no reference of `PEN` in the provided locale (/@angular/common/locales/es-PE.js) and the 15th index (aka the currency symbol index, from my counting of the source) is displayed as `S/.`

Secondly, if you force out the value of `getLocaleCurrencySymbol('es-PE')` it returns the correct symbol, whereas the `getCurrencySymbol` from `i18n/locale_data_api` does not (it's returning PEN, probably because its non-existant in /i18n/currencies.ts).

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gitter-77rbpc

I made two p's: one cheating the currency pipe using the _symbol_ as the currency code and another using the currencyPipe as supposed to.

## What is the motivation / use case for changing the behavior?
1) We could all adhere to the Locale form, instead of having to depend on ./currencies.ts
2) No more currencyPipes that extend the currencyPipe that are then provided as currencyPip

## Environment

<pre><code>
Angular version: 5.0.0 ~ 5.2.10

Browser:
- [x] Chrome (desktop)
- [x] Firefox (Desktop)
</code></pre>

**Comment by ocombe** [comment]
Hello, this has already been fixed in Angular 6, see this example with the latest version of Angular: https://stackblitz.com/edit/angular-gitter-zbrjkl?file=app/app.component.html

**Comment by ocombe** [comment]
No worries. I'm wondering why this wasn't also ported to v5 actually, I guess it was considered a breaking change.

**Comment by wilker7ribeiro** [comment]
These two shouldn't have the same value?
https://stackblitz.com/edit/angular-gitter-nffzye

If I have a multiple language app how do I make CurrencyFilter get LOCALE_ID as default?

**Comment by ocombe** [comment]
No, the currency pipe doesn't take the value of LOCALE_ID by default because we don't want currencies to change the symbol when you change the language of your app. A value in a currency doesn't have the same value in another currency ($1 !== €1). You have to manually set the code of the currency that you want to use.

**Comment by wilker7ribeiro** [comment]
Makes sense, thank you!
