### ISSUE TITLE
ValueProvider wrong behavior with AOT

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#23429]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

`ValueProvider` if created as following
``` ts
    <ValueProvider>
    {
      provide: TEST_PROVIDER,
      useValue: {}
    }
```

for component which is added to parent component html multiple times, this provider `TEST_PROVIDER` is instantiated multiple times if used without AOT which i think is correct, but if use it with AOT you will get only one shared instance among all instances of component which i dont think is correct. If i change `ValueProvider` for `FactoryProvider` it behaves correctly with and without AOT.

## Expected behavior

It should behave exactly as application running without AOT. 

## Minimal reproduction of the problem with instructions
Here you can see sample which works https://stackblitz.com/edit/angular-wsjkd3?file=app%2Fhello.component.ts i cant perform AOT compilation here using @ngtools/webpack

But when i do this this locally and compile it JIT i can see in logs correct output in console
```
undefined
ano0.9378965020726581
undefined
ano0.4123230410763685
```

but if i do it locally using AOT i get following console output
```
undefined
ano0.9378965020726581
ano0.9378965020726581
ano0.4123230410763685
```

where you can see previous value in constructor.

Thank you

## What is the motivation / use case for changing the behavior?

Consistent correct behavior for AOT and JIT compilation.

## Environment

<pre><code>
Angular version: 5.2.10
@ngtools/webpack version: 1.9.8
Webpack version: 3.10.0

Browser: probably all
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 59 (test in)
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.4.0  
- NPM version: 5.6.0  
- Platform: Windows 

Others:

</code></pre>

**Comment by trotyl** [comment]
It's a wrong behavior in JIT, tracked at https://github.com/angular/angular/issues/10788.

**Comment by kukjevov** [comment]
Well I am not completely sure why it is wrong behavior in JIT? 

Why value provider should work different as other providers types? Every component have own `Injector`, if you use this `Injector` and try to obtain `TEST_PROVIDER` you should get 1 instance AKA as singleton. But if you have multiple instances of one component each will have own `Injector` so every one of them should create own instance of `TEST_PROVIDER`. This is exactly how it works with `ValueProvider` and JIT, also this is how it works for each and every other `Provider`. But if you use `ValueProvider` with AOT you will get one instance of `TEST_PROVIDER` for multiple different sibling `Injector`s which is weird.

Why is this correct behavior, it is in conflict with what is written here https://angular.io/guide/hierarchical-dependency-injection why should be `ValueProvider` treated differently?

**Comment by trotyl** [comment]
This is just the JavaScript semantics.

```typescript
fn({
   provide: TEST_PROVIDER,
   useValue: {}
})
```

equals to:

```typescript
var someVar = {};

fn({
   provide: TEST_PROVIDER,
   useValue: someVar
})
```

**Comment by kukjevov** [comment]
Ah sorry, now i see its single value, so it is really singleton :). 

Ok thx for explaination.
