### ISSUE TITLE
NoopZone throws errors when Zone.js is not included

### ISSUE THREAD

**Issue by robwormald** [angular/angular#23428]
## I'm submitting a...

<pre>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
NgZone throws a `ReferenceError: Zone is not defined` error when `{ ngZone: 'noop' }` is used to bootstrap a module.

## Expected behavior
Using the `noop` ngZone should not require Zone.js to be loaded.

I believe the regression was introduced here : https://github.com/angular/angular/pull/16863

We should probably have some kind of integration test for this.

**Comment by robwormald** [comment]
@JiaLiPassion see https://stackblitz.com/edit/angular-branw3?file=app%2Fapp.component.ts - I think this will only surface on v6+?

**Comment by JiaLiPassion** [comment]
@robwormald , yes, you are right, thank you for the reproduce link.

**Comment by oliverdavidt** [comment]
@JiaLiPassion Is there any workaround for this error while we wait for your PR to merged?

**Comment by JiaLiPassion** [comment]
@oliverdavidt , I believe you can define this line in `polifills.ts` to avoid the error for now.

```
(window as any)['Zone'] = {
  current: {
    get: function() {}
  }
};
```

**Comment by oliverdavidt** [comment]
@JiaLiPassion That worked. Thank you.

**Comment by alexzuza** [comment]
Another workaround could be:

```
providers: [{ provide: Testability, useValue: null }]
```

**Comment by maylortaylor** [comment]
> (window as any)['Zone'] = { current: { get: function() {} } };

does it matter where this goes on the `polyfill.ts` file? Is it best on top or bottom of the file?

**Comment by JiaLiPassion** [comment]
@maylortaylor, you can put this code anywhere in `polyfill.ts`.

**Comment by alxhub** [comment]
Fixed by @kara in https://github.com/angular/angular/commit/ee12e725.
