### ISSUE TITLE
Service Worker forces 401 status when using HTTP-Authentication

### ISSUE THREAD

**Issue by NCC1701M** [angular/angular#23425]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When using the service worker with web apps which are using HTTP authentication (in this case Windows authentication) the ngsw.json?ngsw-cache-bust= runs into a 401 status.

## Expected behavior
The 401 status should not be happen.

## Minimal reproduction of the problem with instructions
Create a angular service worker project like described here [https://angular.io/guide/service-worker-getting-started](https://angular.io/guide/service-worker-getting-started) enable some kind of Authentication e.g. Windows authentication

## What is the motivation / use case for changing the behavior?
The motivation is that service workers should work with authentication.

## Possible solution
In the ngsw-worker.js file change the implementation of the newRequest method of the Adapter class to the following
````ts
newRequest(input, init) {
  init = init || {};
  if (!init.credentials) {
    init.credentials = 'same-origin';
  }
  return new Request(input, init);
}
````

## Environment

<pre><code>
Angular version: 5.2.10

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4
- Platform:  Windows

**Comment by dirkluijk** [comment]
We had the same issue. I thought it was a browser limitation, but if this can be fixed... yes please!

**Comment by alxhub** [comment]
Service workers have a lot of issues with HTTP authentication, it's not well supported in general, and not at all in NGSW.

**Comment by NCC1701M** [comment]
@alxhub So then you simply decide to close this bug instead of testing the solution I provide in the issue? You don't even think about an option to give developers the chance to decide for themselve by implementing a setting to switch on/off this feature?

That's poor!

**Comment by arangates** [comment]
@alxhub 
here is the case , where the problem is kinda resolved
 https://thatemil.com/blog/2018/02/21/pwa-basic-auth/
