### ISSUE TITLE
Angular 5 interceptor using cached in catch

### ISSUE THREAD

**Issue by Scipionh** [angular/angular#23421]
I have an implementation of the HTTP_INTERCEPTOR in the latest angular5 version. 

```
return next
      .handle(req)
      .do(evt => {
        ...
      })
      .catch((e: any) => {
        if(cachedResult) {
          return Observable.of(cachedResult)
        } else
        return Observable.throw(e)
      })
```

However, it doesn't seem to work when I have an error and the cachedResult does exist, as if Observable.of(cachedResult) returns an Observable of nothing. This leads to all my subscribe having nothing from their subscription.

I wonder if I am doing the right thing by using Observable.of inside my catch ?

**Comment by splincode** [comment]
You have incorrectly described the task:

Where is the online example?
Why do not you keep the issue template?

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
