### ISSUE TITLE
Query parameters removed upon application load

### ISSUE THREAD

**Issue by chrsmith** [angular/angular#23423]
[x] Bug report (?)
[x] Feature request (?)
[x] Documentation issue or request

## Current behavior

When opening a page the URL's query parameters are being automatically removed. So when opening http://localhost:3000/route?param=alpha, the URL changes to http://localhost:3000/route as part of Angular's initialization.

I'm aware you can _read_ the URL's query parameters from the `ActivatedRoute` ([docs](https://angular.io/guide/router#query-parameters)). And you can _preserve_ URL query parameters when routing to a different component within the same app ([docs](https://angular.io/api/router/NavigationExtras)).

But what isn't clear is how to have the Angular router "keep the URL query parameter around" when linked to the Angular application from an external site. Since the initial link isn't within the same Angular application, I cannot specify the `NavigationExtras` to preserve the URL query parameters.

Since the URL query parameters appear to be removed before the routed component's `ngOnInit` method is called, there's no way to find out what the incoming URL parameters were. (Or if they were even passed at all.)

## Expected behavior

This seems like a reasonable scenario, so I would expect this to "just work". But I assume there is something I'm missing. I haven't been able to find any documentation calling out if this is specifically supposed to work or not.

Is there some way to configure `interface Route` so that it doesn't strip off the URL query parameters by default? e.g.` { path: "orders/:id", component: OrdersComponent, dontRemoveQuryParameters: true }`

Ultimately I'd like links like `https://ng-app.com/orders/42?debug=true` to work, and have the `OrdersComponent` be able to get the `debug` URL query parameter. But instead, by the time the component loads the URL has been changed to https://ng-app.com/orders/42.

**Comment by fergusg** [comment]
I had a similar problem, but it turned out to be a coding error. More specifically a race condition between async authentication and an "authentication" guard in the router.  The guard was redirecting the route before authentication was complete.  Try setting route tracing on: 

```
RouterModule.forRoot(ROUTES, {
    enableTracing: false
})
```

to see if something similar is happening for you.  My solution was to ensure the initial auth was complete before getting close to any protected routes.

**Comment by chrsmith** [comment]
@fergusg thanks for the suggestion, but I see this behavior on both guarded and unguarded routes. Setting the `enableTracing` flag, when loading `/welcome?foo=bar` the query parameter is dropped before the very first routing event:

```
Router Event: NavigationStart
    NavigationStart(id: 1, url: '/welcome')
    NavigationStart {id: 1, url: "/welcome"}
Router Event: RoutesRecognized
    RoutesRecognized(id: 1, url: '/welcome', urlAfterRedirects: '/welcome', state: Route(url:'', path:'') { Route(url:'welcome', path:'welcome') } )
    RoutesRecognized {id: 1, url: "/welcome", urlAfterRedirects: "/welcome", state: RouterStateSnapshot}
Router Event: GuardsCheckStart
    GuardsCheckStart(id: 1, url: '/welcome', urlAfterRedirects: '/welcome', state: Route(url:'', path:'') { Route(url:'welcome', path:'welcome') } )
    GuardsCheckStart {id: 1, url: "/welcome", urlAfterRedirects: UrlTree, state: RouterStateSnapshot}
Router Event: ChildActivationStart
    ChildActivationStart(path: '')
    ChildActivationStart {snapshot: ActivatedRouteSnapshot}
```

I'll look at the docs/code at `NavigationStart` and see if that turns up something.

**Comment by fergusg** [comment]
@chrsmith I see very different behaviour:  

```
Router Event: NavigationStart
    NavigationStart(id: 1, url: '/resetpassword?request=true')
[... lots]
Router Event: NavigationEnd
    NavigationEnd(id: 1, url: '/resetpassword?request=true', urlAfterRedirects: '/resetpassword?request=true')
```

My config is completely vanilla except for a crazy depth of child-routes.  I'm not using lazy-loading.

One thing, though, is that I'm not using `ng serve` at all, even  in dev, but `ng build --watch` and running through a real webserver (Apache).  It should be easy enough to eliminate (or confirm!) the devserver as the culprit.

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by elvomka** [comment]
@chrsmith The preservation of query strings seems to be broken when using hash-based routing.

**Comment by cecchisandrone** [comment]
Anyone found a way to resolve this issue?

**Comment by manklu** [comment]
If you follow https://github.com/angular/angular/issues/23423#issuecomment-382949597 you may get an answer.

**Comment by elvomka** [comment]
I had to disable the router's `initialNavigation` and create my own `initialNavigation` in my toplevel AppComponent. There you can access queryParameters and pass it to the router's `navigate()` method. Be aware however, that this way Angular will append the QueryParameter to the fragment-identifier of your URL.

**Comment by shayaneumar** [comment]
I am also facing the similar problem in my application which is on Angular6. I am using hashed url, I am not sure if this is framework problem or some issue in the code.

@elvomka Can you share the code for the solution you have mentioned?
I have tried the issue reported here in Angular 7, query params work with both hash and without hash url.

**Comment by wollerman** [comment]
So I made a stackblitz to try and reproduce the issue: https://stackblitz.com/edit/angular-hoknk5 and it seems to work fine in the stackblitz. You can test it out by adding a `code` query param to the test url like https://angular-hoknk5.stackblitz.io/?code=123 This seems to work fine and the page refresh also works fine.

Looking at the console the `Router Event` stack ends with: 
![image](https://user-images.githubusercontent.com/1610241/54938160-177b2580-4ee3-11e9-9bd3-db3721503dd8.png)

Whereas in my version that causes the query params to drop on refresh, the stack shows a `NavigationEnd`, `Scroll`, and then starts again with `NavigationStart`. Screenshot from my app:

![image](https://user-images.githubusercontent.com/1610241/54938306-5610e000-4ee3-11e9-91ba-86c46d894045.png)


I'm not sure what would cause this difference in reloading the app twice? Locally I'm using `ng serve` and I also deployed to an S3 bucket. I see the same functionality either way. Perhaps it's related to a RouteGuard? I'll make another stackblitz to test that.

**Comment by wollerman** [comment]
This also seems to work with a route guard: https://stackblitz.com/edit/angular-ab8kvt and test url: https://angular-ab8kvt.stackblitz.io/?code=123
