### ISSUE TITLE
HttpHeaders class set/append/delete returns HttpHeaders

### ISSUE THREAD

**Issue by htzhang2** [angular/angular#23438]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

class HttpHeaders {
...
  append(name: string, value: string | string[]): HttpHeaders
  set(name: string, value: string | string[]): HttpHeaders
  delete(name: string, value?: string | string[]): HttpHeaders

Why set, append, delete methods returns a new instance of HttpHeaders?

## Expected behavior

These 3 methods should returns nothing, just update current HttpHeaders instance. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by CDDelta** [comment]
`HttpHeaders` is immutable meaning that any updates to it return a new object. You should be something like this if you want to use `HttpHeaders`.
`let headers = new HttpHeaders().append('X-Header', 'val').append('X-Header-2', 'val);`
It is working as expected.

**Comment by robwormald** [comment]
As @CDDelta states, this is working as intended.
