### ISSUE TITLE
Buffered Render Option (ngFor)

### ISSUE THREAD

**Issue by toxik** [angular/angular#23433]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently `ngFor` directives perform unbuffered dom insertions into the page.
Is there any way to batch some of the operations in order to improve render times by inserting a full batch of elements instead of the "one-by-one" behavior?

## Expected behavior

I'd like to be able to control when the dom nodes are inserted into the page and perform the rendering "off-page"

## Minimal reproduction of the problem with instructions

I've created a [stackblitz demo](https://stackblitz.com/edit/angular-czjt4b) for easy comparison that creates two 200 columns x 20 rows tables.
The first button will spawn a table normally, while the second one uses a directive which detaches the `tbody` from the rendered DOM at init and then re-inserts it back after an observable emits.

## What is the motivation / use case for changing the behavior?

Improving the render performance (helping IE 11 especially)

## Environment

<pre><code>
Angular version: 5.2.10

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX

**Comment by trotyl** [comment]
Added a timer to your example: https://stackblitz.com/edit/angular-czjt4b-cg8fri?file=app%2Fdefer-dom-insert.directive.ts

![image](https://user-images.githubusercontent.com/6059170/38974876-4267c7fa-43de-11e8-978b-ef2f3e256f16.png)

Didn't get any real difference. (Also due to the poor-designed demo, whatever triggered latter will be faster).

Also, this is not about operation buffer, but operation redesign, which cannot be applied to insert, append, move, swap, or whatever partial update scenario. (Don't see anyone wants to detach the table first when just adding a new row)

**Comment by vladjerca** [comment]
@trotyl This demo is a simple example, true. But in real world scenarios, where the DOM elements are nested

- eg: each cell contains an ```mat-icon```, ```mat-menu``` etc. 

The DOM tree gets really large, I've tried to test the demo @toxik posted in one of our production tables and it reduced rendering time from `1600ms` to `780ms` in a table with 50 rows in Internet Explorer.

I know speed differences are minor in other browsers like Chrome, the fact of the matter is that the speed increase affects all browsers, and from an engineering standpoint, generating the elements in memory before attaching them to the DOM, is more efficient.

The sad truth is that most applications, like it or not, have Internet Explorer users (and many of them at that).

**Comment by robwormald** [comment]
I think in the interest of keeping keeping it relatively compact and simple, we won't add this option to `ngFor` - the CDK team is working on a virtualized repeater at the moment, and you can track the progress of that [here](https://github.com/angular/material2/projects/20)
