### ISSUE TITLE
Safari (on production) doesn't print results from HTTP get via *ngFor

### ISSUE THREAD

**Issue by Juliusdz** [angular/angular#23434]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Safari (on production) doesn't print results from HTTP get via *ngFor.

On development all is fine with all browsers, but on production, Safari doesnt print results via *ngFor from my http.get calls. In one .html I display results in two places:

1. Works:

```
  <div *ngIf="weatherObj" class="wrapper">
    Current Weather: {{weatherObj.weatherNow}}
  </div> 
```
2. Doesn't work:

```
<div *ngIf="weatherObj">
  <span class="wrapper">
    <div *ngFor="let futureW of weatherObj.futureWeather">
      {{futureW.hour}}.00 - {{futureW.weather}} <br>
    </div>
  </span>
</div>
```

weatherObj is received after I subscribe in constructor a Subject which receives next(weatherObj) in a service's subscribe function that makes http.get():

```
constructior(){
  this.weatherSubscription = this.wService.weatherObs$.subscribe(_ => this.showIcon(_)); 
}

showIcon(weather) {
  this.drawCanvas().then(() => {
    this.weatherObj = weather;
    ...
  })
}  

drawCanvas() {
  return new Promise((resolve) => {
    if (this.canvas) {
      this.rd.removeChild(this.iconCanvas.nativeElement, this.canvas);
    }     
    this.canvas = this.rd.createElement('canvas');
    this.rd.setStyle(this.canvas, 'width', '128');
    this.rd.setStyle(this.canvas, 'height', '128');
    this.ctx = this.canvas.getContext('2d');
    this.ctx.textBaseline = 'top';       
    resolve();
  });
}
```

Safari shows no errors in console...

[project in gitHub](https://github.com/Juliusdz/WeatherApp)

## Environment

- "@angular/core": "^5.2.0",
- Safari (desktop) version 11.1
- Node version: v9.11.1

**Comment by vicb** [comment]
Please attach a simple repro that reproduces the problem.

**Comment by Juliusdz** [comment]
Oh, issue was about how Safari uses Date format... In service I had things like:

`new Date("2018-04-20 18:00:00").getDate()` 

Now replaced with `new Date("2018-04-20 18:00:00".replace(/-/g, "/")).getDate()` 

And all seems to be fine...
