### ISSUE TITLE
Expose observable as @Output() parameter in future safe way

### ISSUE THREAD

**Issue by bygrace1986** [angular/angular#23435]
## I'm submitting a...

<pre><code>
[X] Feature request
</code></pre>

## Current behavior
The docs say:
> An Output property is an observable property annotated with an @Output decorator. The property **almost always** returns an Angular EventEmitter.

It doesn't mention what a valid exception is. By viewing the source code I can see that the EventEmitter extends Subject and through experience I know that I can use an Observable instead. But using an Observable instead of an EventEmitter seems fragile for the future as the Angular team could change the underlying function of the EventEmitter.

So if I have an existing observable stream that I want to expose as an output property I have to subscribe to that observable and forward its emissions to an EventEmitter.

```
import { Component, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs/Subscription';

@Component({
    selector: 'test-component',
    template: ''
})
export class TestComponent implements OnInit, OnDestroy {
  private subscription: Subscription;

  @Output()
  public readonly isProcessing = new EventEmitter<boolean>();

  constructor(
      public testService: TestService
  ) {
    this.subscription = this.testService.isProcessing.subscribe((x) => {
      this.isProcessing.emit(x);
    });
  }

  ngOnInit(): void {
    this.testService.doWork();
  }

  ngOnDestroy(): void {
    if (this.subscription) {
      this.subscription.unsubscribe();
    }
  }
}
```

## Expected behavior
Ability to reuse an existing observable as an output property in a future safe way. I understand why the Angular team would want to wrap the observable. So maybe a function can be exposed that wraps an observable returning it as something that implements the EventEmitter interface but doesn't make it hot.

```
import { Component, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs/Subscription';

@Component({
    selector: 'test-component',
    template: ''
})
export class TestComponent implements OnInit {
  private subscription: Subscription;

  @Output()
  public readonly isProcessing: EventEmitter<boolean>;

  constructor(
      public testService: TestService
  ) {
    this.isProcessing = createEventEmitter(this.testService.isProcessing);
  }

  ngOnInit(): void {
    this.testService.doWork();
  }
}
```

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?
Subscribing to an existing observable in order to forward its emissions to an EventEmitter has some undesirable side-effects:

1. I have to manage the subscription to the observable by unsubscribing it in `onDestroy`.
2. I have to make the stream hot by subscribing to it even though another component may not be subscribed to the output property.

## Environment

<pre><code>
Angular version: 2.x+
Browser: N/A
</code></pre>

**Comment by splincode** [comment]
Where is it imported createEventEmitter ?

**Comment by bygrace1986** [comment]
@splincode `createEventEmitter` is what I was proposing would be created by the Angular team. Something like it at least that would wrap an observable in whatever magic Angular requires now or in the future for outputs.

**Comment by dawidgarus** [comment]
Why not:
```typescript
this.isProcessing = this.testService.isProcessing.publish();;
```
?

**Comment by bygrace1986** [comment]
@dawidgarus what is your goal with putting the publish operator on the end?

**Comment by dawidgarus** [comment]
@bygrace1986 I forgot about `refCount()`. It should be `publish().refCount()`. This way You can subscribe to output multiple times (example: `[(myOutput)]="value" (myOutputChange)="onChange()"` or directly `component.myOutputChange.subscribe()`), but the original observable will be subscribed only once.

**Comment by bygrace1986** [comment]
@dawidgarus thanks, I'm doing similar inside my services. This feature request is about future proofing. From what I can tell from the docs and random comments/blogs online is that we are expected to use EventEmitter for output properties and that though the EventEmitter is an RxJs Observable by nature of it being a Subject, it is not guaranteed to always be such. EventEmitter isn't much more than a Subject today but if that changes then it would be a significant refactor in larger apps that made assumptions that they could use Observables in place of them. So though I know that I can expose observables as Output properties today I would like a way to future proof that method.

**Comment by pauldraper** [comment]
What reason is there for Angular *not* wanting `@Ouput()` to Observable?

My understanding is that Angular uses rxjs heavily, and this is *exactly* what an Observable is made to do.

**Comment by chikakow** [comment]
actually this will help with ngrx store selector.  I'm looking for something to convert observable that is from selector to output.  So createEventEmitter will help.  My reusable component is accessing ngrx store but I don't want consumers have to access to ngrx store everytime but rather just use the component event if they don't have to know whole alot of things.
As you could see, it is not so elegant right now.
`    this.subscription.add(
      this.store
        .pipe(
          select(MenuFilterSelectors.selectDateRangeValues, {
            preferenceName: this.menuPreferenceName
          })
        )
        .subscribe((dateRange: DateRange) =>
          this.dateRangeChange.emit(dateRange)
        )
    );`

**Comment by kdshop** [comment]
Yes please 👏

**Comment by syndicatedshannon** [comment]
My current use-case for something like this is to allow Angular to manage my subscription lifetime.

Given the following template throughout for clarity:

    <select (change)="selected.next($event.target.value)" />

Only in the simplest of use-cases do I get the benefit of the observable pattern:

    export class MyComponent {
        @Output() selected: EventEmitter<string> = new EventEmitter<string>();
    }

However, as soon as I want to filter it (e.g. mouse events), or combine it with another observable (e.g. data source or correlated component), etc., I lose the benefit of the observable pattern, where the external subscribers manage the lifetime. Now I have to create an intermediate Subjects and force a lifetime independent of consumers:

    export class MyComponent {
        @Output() selected: EventEmitter<string> = new EventEmitter<string>();

        ngOnInit() {
            this.subscriptions.add(this.filteredUpdates().subscribe(m => this.selected.next(m)));
        }
        
        ngOnDestroy() {
            this.subscriptions.unsubscribe();
        }

        filteredUpdates() {
            return updates.pipe(filter(u => u !== null));
        }

        updates: Subject<string> = new Subject<string>();
    }

To address most of my need here, it would probably work if I could initialize an EventEmitter with another observable. Maybe an extra line of code here or there, but at least I wouldn't be managing more component-related lifetimes.

    export class MyComponent {
        @Output() selected: EventEmitter<string>;

        constructor() {
            this.selected = new EventEmitter<string>(filteredUpdates());
        }

        filteredUpdates() {
            return updates.pipe(filter(u => u !== null));
        }

        updates: Subject<string> = new Subject<string>();
    }

**Comment by darkbasic** [comment]
Everyone interested in seeing this feature, please answer the angular survey 2020 and where it says `"How else should we improve Angular for you?"` make it explicitly known that you care alot about seeing "Issue #23435 implemented and resolved."

Here is the direct link to the survey:
https://goo.gle/angular-survey-2020

**Comment by JeanMeche** [comment]
17.3 landed the new `output()` function and alongside of it `outputFromObservable` to expose `Observable` as output.
