### ISSUE TITLE
App Component SVG object html element rendering issue on edge

### ISSUE THREAD

**Issue by zane007bloom** [angular/angular#23430]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Loading SVG's using the object html element fails to render on edge V41.16299.371.0 on the main app component. The SVG does render on components that are inside the router outlet though.

## Expected behavior

Correct SVG rendering on the App Component using the object html element.  

## Minimal reproduction of the problem with instructions

Here is an example of the issue: https://embed.plnkr.co/XwYcGDHfMcMZ7fTW0vkf/ 

## What is the motivation / use case for changing the behavior?

I want SVG's to render correctly and consistently in any html template.

## Environment

<pre><code>
Angular version: 5.2.10

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 41.16299.371.0
 
For Tooling issues:
- Node version: 8.11.1
- Platform:  Linux

Others:

The SVG renders correctly in chrome and firefox
</code></pre>

**Comment by vicb** [comment]
> fails to render on edge V41.16299.371.0

Could you please try to create an SVG element programmatically and see if it works in Edge ?
It might be the problem (please attach repro code here) 

> The SVG does render on components that are inside the router outlet though.

Is probably a different issue, please create an other one.

**Comment by vicb** [comment]
Closing as obsolete and no follow up answer was given.
