### ISSUE TITLE
angular2_1.Component is not a function

### ISSUE THREAD

**Issue by svrcekmichal** [angular/angular#2343]
After update to angular2@2.0.0-alpha26 I'm getting error `Uncaught TypeError: angular2_1.Component is not a function`. Any possible solution or hint? 

in builded JS file `var angular2_1 = require("angular2/angular2");` return empty object `{}`. In version 25 everything works fine.

**Comment by jomeier** [comment]
Me too.

**Comment by mhevery** [comment]
Need more steps to reproduce. How are you getting this error? what command you are running etc.

**Comment by ericmdantas** [comment]
I'm having a similar issue, but not with the component (maybe the exception is thrown before hitting that), I'm having the error with Directives:

```Uncaught TypeError: angular2_1.Directive is not a function```

If I try to import directive as ```DirectiveAnnotion```, I get the error: 

``` Uncaught TypeError: angular2_1.DirectiveAnnotation is not a function```

**Comment by toedter** [comment]
Same here.

@mhevery , you can try it out cloning my git repo https://github.com/toedter/angular2-typescript-demo. Currently it is running fine using alpha 22. When you change line 7 in src/main/html/index.html using angular2-a26 you would get the error: Uncaught TypeError: angular2_1.Component is not a function

**Comment by mhevery** [comment]
We were able to repro this and @rkirov is looking into it.

**Comment by rkirov** [comment]
Confirmed, the bundle is broken when consumed through commonjs. I am looking into what caused that regression.

**Comment by svrcekmichal** [comment]
@mhevery @rkirov thanks guys, I really appreciate that. Thanks for all the work you are doing with whole team behind angular :)

**Comment by mgechev** [comment]
Today me and @ludohenin updated the Angular version at the [angular2-seed](https://github.com/mgechev/angular2-seed/) and had the same issue. After digging a while in System.js I found that the issue comes from `angular2/src/core/compiler/interfaces`, after being transpiled to ES5 it gets turned into an empty file. During the dependency resolution phase `angular2/core` is getting messed.

[Here is a very dirty](https://github.com/mgechev/angular2-seed/blob/alpha26/app/init.ts#L3-L9) workaround I did.

**Comment by rkirov** [comment]
Thanks for the leads, a slightly less dirty fix is pending. Does anyone know of a relevant system.js issue?

**Comment by robwormald** [comment]
there were a bunch of changes to jspm/systemJS today: https://github.com/systemjs/systemjs/releases/tag/0.17.0, so there may be a conflict if you're trying to use a bundle built with an earlier version of the builder?

**Comment by mgechev** [comment]
@rkirov I had a quick chat with Guy Bedford from system.js. [Here is an issue](https://github.com/systemjs/systemjs/issues/487) in their repo, which is related with this one.

**Comment by jomeier** [comment]
Do you have any recommendations what we can do to get Alpha 26 working? Will "it" be fixed in Alpha 27 ?

**Comment by glfafn** [comment]
@jomeier The 26 version was updated soon after with a patch that fixes the issue temporarily.

**Comment by rkirov** [comment]
Temporary fix landed, thanks for the reference @mgechev.

As mentioned already, the 26 bundle has been back-patched.

**Comment by guybedford** [comment]
There's a fix in SystemJS for this at https://github.com/systemjs/systemjs/issues/487. If anyone is able to test master against this case again, that would be a great help to know if it's been caught.

**Comment by guybedford** [comment]
(Note the above is in relation to @mgechev's comment at https://github.com/angular/angular/issues/2343#issuecomment-109259669)
