### ISSUE TITLE
migrating .angular.cli.json file to angular.json in angular v6-rc.3 - old format not parsed

### ISSUE THREAD

**Issue by st-clair-clarke** [angular/angular#23443]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[x] Other... Please describe:
</code></pre>

## Current behavior

I have the following styles and scripts in angular5 .angular-cli.json file

      "styles": [
        "../node_modules/primeng/resources/primeng.min.css",
        "../scss/bootstrap/bootstrap.scss",
        "../src/assets/styles/icon8.css",
        "styles.scss",
        "styles-props.css"
      ],
      "scripts": [
        "../node_modules/web-animations-js/web-animations.min.js",
        "../node_modules/jquery/dist/jquery.js",
      ],

## Expected behavior

The styles and scripts should be parsed with ng-serve in my angular 6 angular.json file

## Minimal reproduction of the problem with instructions

When ng serve is excecuted, I get the following:
J:\workspace\ts\ng6\pim>ng serve
** Angular Live Development Server is listening on localhost: 4200, open your browser on http://localhost:4200/ **
 91% additional asset processing scripts-webpack-plugin× ｢wdm｣: Error: ENOENT: no such file or directory, open 'J:\workspace\ts\ng6\node_modules\web-animations-js\web-animations.min.js'
i ｢wdm｣: wait until bundle finished: /
i ｢wdm｣: wait until bundle finished: /

## What is the motivation / use case for changing the behavior?
It appears that the format of the script is not able to be read

## Environment

<pre><code>
Angular CLI: 6.0.0-rc.4
Node: 8.9.1
OS: win32 x64
Angular: 6.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.6
@angular-devkit/build-angular     0.5.7
@angular-devkit/build-optimizer   0.5.7
@angular-devkit/core              0.5.7
@angular-devkit/schematics        0.5.7
@angular/flex-layout              5.0.0-beta.14
@angular/material                 6.0.0-rc.11
@ngtools/json-schema              1.1.0
@schematics/angular               0.5.6
@schematics/update                0.5.6
rxjs                              6.0.0-uncanny-rc.7
typescript                        2.7.2
webpack                           4.6.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by splincode** [comment]
The reason for the question is not quite clear

**Comment by st-clair-clarke** [comment]
Angular v5.x has a file .angular-cli.json. The file has been renamed in angular v6 to angular.json. 

The question is 'How do you convert the attributes of an angular version 5.x .angular-cli.json file "script:" and "style:" values to the angular version 6.x angular.json configuration. I hope this is clearer.

**Comment by trotyl** [comment]
@st-clair-clarke It's not about Angular version nor this repo.

+ [Angular CLI](https://github.com/angular/angular-cli) v1.x uses the `.angular-cli.json` or `angular-cli.json` file;
+ [Angular CLI](https://github.com/angular/angular-cli) v6.x uses the `.angular.json` or `angular.json` file.

The project structure will be automatically updated when you run `ng update` command. Please see [Angular CLI release log](https://github.com/angular/angular-cli/releases/tag/v6.0.0-rc.2) for more information.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
