### ISSUE TITLE
Angular 5.2.10,  typescript 2.6.2  Run time issues with barrels

### ISSUE THREAD

**Issue by rodhoward** [angular/angular#23444]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Everything is compiling nicely both in dev mode and in production (using angular/cli 1.7.4).  However when I run the code I'm getting issues with classes in barrels. for example:
```
import { Operations, Pagination, Campaign } from '../core/model';
..
// fromJson is a static function.
this.campaigns = response.result.map((c) => Campaign.fromJson(c));
..
```
is giving me:
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'fromJson' of undefined
TypeError: Cannot read property 'fromJson' of undefined
```
 Taking Campaign out of the barrel and importing it independently fixes the issue. This has been working just fine with angular v5 typescript v2.4.2.  What is interesting is that reverting to typescript 2.4.2 I still get the issue so its probably something with the angular compiler or webpack stripping stuff out...

## Expected behavior
No errors.

## Minimal reproduction of the problem with instructions
use barrels with classes with static functions..  

## Environment

<pre><code>
Angular version: 5.2.10

Browser:
- [X] Chrome (desktop) version XX
 
For Tooling issues:
- Node version: v8.9.2
- Platform:  Linux

**Comment by Toxicable** [comment]
This isn't an issue with Angular.
You likely have a cyclic dependency between `Campaign` and another class exported from your barrel, therefore resulting in an undefined import

**Comment by rodhoward** [comment]
Yeah thanks. That's what I've found too I was going to post again but still haven't quite resolved it.

I guess the only gotcha is why is it biting us now and not on the previous versions...

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
