### ISSUE TITLE
v6 rc.5 fails with memory issues on chrome/safari

### ISSUE THREAD

**Issue by mlakmal** [angular/angular#23445]
## I'm submitting a...

<pre><code>
[ x] Bug report
</code></pre>

## Current behavior
when running existing hybrid app with v6 rc.5 version fails on chrome browser with Aw Snap error. rolling back version to rc.3 works fine. firefox seems to work with gracefully handling memory issue.

<pre><code>
Angular version: 6.0.0-rc.5

**Comment by splincode** [comment]
Please attach a demo repository for the launch

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
