### ISSUE TITLE
Accelerate deployment `ng new project`

### ISSUE THREAD

**Issue by splincode** [angular/angular#23449]
## I'm submitting a...
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[x] Other... Please describe: Build improvements
</code></pre>

## Current behavior
In total, to run the first application, and the usual demo, I need to spend 6 minutes until it installs all the packages.  This is sometimes very annoying.

```
$ ng new demo
349.36 sec ~ 6 min
Project 'demo' successfully created
```

-------

If we use Vue then we can simply add a script

```
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Vue CDN</title>
</head>
<body>
    ...
    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.13/dist/vue.js"></script>
</body>
</html>
```

And all, you can write to start the application or if you usage vue init it's best start config cli

## Expected behavior

```
$ ng new project
? default install all dependencies (Y/n) n
# ========================
? Install @angular/router? (Y/n) n
? Use TSLint to lint your code? (Y/n) n
? Set up unit tests Karma (Y/n) n
? Setup e2e tests with Protractor? (Y/n) n
# Project initialization finished!
# ========================
To get started:

  ng serve

Documentation can be found at https://angular.io/guide/quickstart

```

If you make a customizable way to install the application, you could create simple applications faster.

**Comment by Toxicable** [comment]
https://github.com/angular/angular-cli
Already does this.

**Comment by splincode** [comment]
@Toxicable why am I not aware of this? and where examples in the official quickstart documentation

**Comment by trotyl** [comment]
You can already use whatever schematics in `ng new` command.

**Comment by splincode** [comment]
@trotyl Where are the documentation and examples?)

ng-cli@1.7 ? or ng-cli@6 ?

**Comment by Toxicable** [comment]
https://github.com/angular/angular-cli/wiki/new

**Comment by trotyl** [comment]
Seems the doc is indeed outdated, PR found in https://github.com/angular/angular-cli/pull/9170

**Comment by splincode** [comment]
This is not exactly what I would like to have by default
You are talking about schemes

**Comment by trotyl** [comment]
The default schematics used will obviously follow the best practices, which is the current behavior.

**Comment by vicb** [comment]
This is handled by the CLI.
