### ISSUE TITLE
Routing issue with queryparams

### ISSUE THREAD

**Issue by pramodrwt** [angular/angular#23448]
**Route:**  http://localhost:4200/#/users/:id

**Url:** http://localhost:4200/#/users/123?tab=profile

For getting param value:  **this.route.snapshot.params['id'];**

So it is giving me:  **"123?tab=profile"**

Then i have to do:
**this.route.snapshot.params['id'].split('?')[0];** 

is this problem with Angular 4.0 ?

**Comment by splincode** [comment]
Please create an examples on stackblitz and edit the correct issue template

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by pramodrwt** [comment]
@vicb This is not support request i just notify bug

Angular having routing problem with queryparams

**Comment by splincode** [comment]
@pramodrwt Please create new issue with an examples on stackblitz and edit the correct issue template
