### ISSUE TITLE
ngc watch flag doesn't produce metadata.json

### ISSUE THREAD

**Issue by mike-suggitt** [angular/angular#23457]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

If i do an `ngc -p ./src/tsconfig.lib.json` then the compiler produces a metadata.json as expected. If I use the new watch flag (-w)
`ngc -w -p ./src/tsconfig.lib.json` then there is no metadata.json produced.

## Expected behavior

For the watch flag to make no difference to build output

## Minimal reproduction of the problem with instructions

Example tsconfig
```
{
    "compilerOptions": {
        "target": "es5",
        "module": "es2015",
        "moduleResolution": "node",
        "sourceMap": true,
        "outDir": "../dist/",
        "rootDir": "",
        "declaration": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "lib": [
            "es2016",
            "dom"
        ],
        "outDir": "../dist"
    },
    "exclude": [
        "**/*.spec.ts",
        "test.ts"
    ],
    "files": [
        "./export.ts"
    ],
    "angularCompilerOptions": {
        "skipMetadataEmit": false,
        "genDir": "../dist",
        "debug": false,
        "enableResourceInlining": true,
        "strictMetadataEmit": false
    }
}
```

## Environment
Using the following compiler package versions:
```
@angular/compiler": "^6.0.0-rc.3",
        "@angular/compiler-cli": "6.0.0-rc.3",
```
<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by JoostK** [comment]
Closing as obsolete, as the Ivy compiler does not generate metadata.json files at all.
