### ISSUE TITLE
docs(aio): Wrong documentation in guide/http

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#23453]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

https://angular.io/guide/http#testing-for-errors

The documentation text says `Call request.error()` but its example code calls `req.flush`

![image](https://user-images.githubusercontent.com/1529180/38997128-afb9420e-4427-11e8-9c96-e616b8a7b081.png)

## Expected behavior

2 error kinds should be documented. one is error response (like 404), and another is like networking error. 
404 response testing will use `req.flush()`, and networking error testing will use `req.error()`.

## Environment

Version 5.2.11-build.43496+sha.402f452.

**Comment by jenniferfell** [comment]
docarea=httpclient
filename=guide/http.md

**Comment by brandonroberts** [comment]
Fixed via #23567
