### ISSUE TITLE
Semantics of Arguments Passed to Constructor of Component

### ISSUE THREAD

**Issue by sayasree** [angular/angular#23463]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
In the URL: https://angular.io/guide/architecture-components
at the place where the "class HeroListComponent"  is defined, the explanation for the semantics of passing the argument "private service: HeroService" to the constructor method is missing.
Someone coming from the OOP background, they think that it is just a formal parameter and expects it to be initialized with the instance of the object created with new operator. 

## Expected behavior
Looks like, in Angular, by virtue of specifying it as a formal parameter to constructor method it automatically does the following:
private service: HeroService;
constructor() {
   service = new HeroService();
}
If this is the case, in case some parameters to be passed while constructing as HeroService(p1,p2,p3), how it is done when it can be done in the constructor() syntax.

## Minimal reproduction of the problem with instructions
None

## What is the motivation / use case for changing the behavior?
Not Applicable

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:  Not Applicable
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:  Not Applicable
- Node version: XX  
- Platform:  

Others:  Not Applicable

**Comment by trotyl** [comment]
This is normal TypeScript semantics, Angular was not involved at all.

**Comment by jotatoledo** [comment]
> Someone coming from the OOP background, they think that it is just a formal parameter and expects it to be initialized with the instance of the object created with new operator.

Im pretty sure that most devs will recognize that the component is using constructor injection.

> Looks like, in Angular, by virtue of specifying it as a formal parameter to constructor method it automatically does the following:
> private service: HeroService;
> constructor() {
> service = new HeroService();
> }

Not sure where did you got this idea from, but its incorrect. @trotyl already pointed out how parameter properties work.

**Comment by sayasree** [comment]
Hi Trotyl/Jose,

Thanks for your clarifications.

I am still learning TypeScript. Now, I realize that I need to catch up with
TypeScript even deeper.

Regards,
  --Sreenivasulu Saya

**Comment by jenniferfell** [comment]
Thank you for the original comment and clarifications re typescript experience. Given that this architecture doc is part of the introductory material, we'll look at making it more clear for those who are learning typescript and angular together.

**Comment by jenniferfell** [comment]
docarea=architecture
filename=guide/architecture-components

**Comment by sayasree** [comment]
Hi Jennifer,

Thanks for accepting my feedback. Including in the introductory material
would be a good idea.

Definitely, documenting the missing pieces in the documentation will hep to
understand Angular better and hence it will be embraced with more comfort
by the development community.

Regards,
  --Sreeni Saya


Regards,
  --Sreenivasulu Saya
