### ISSUE TITLE
Support Elvis operator with brackets notation

### ISSUE THREAD

**Issue by AbakumovAlexandr** [angular/angular#23469]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior

Currently, template parser doesn't support Elvis operator with bracket notation:
```
    <input
        type="text"
        [value]="entity?[field]">
```
## Expected behavior

Elvis operator is supported with bracket notation in the same way as with dot notation.

## What is the motivation / use case for changing the behavior?

Supporting Elvis with bracket notation would prevent us from expanding expressions manually in cases when we can't use dot notation with Elvis:
```
    <input
        type="text"
        [value]="entity ? entity[field] : undefined">
```
## Environment

<pre><code>
Angular version: 5.2.10.

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/17181

**Comment by vicb** [comment]
Closing as duplicate
