### ISSUE TITLE
Error: could not handle the request Angualr universal using firebase functions

### ISSUE THREAD

**Issue by coderrepo** [angular/angular#23461]
I have Angualr universal apps that serve request using Firebase function.

Website URl : https://ngcoderfirst-23e41.firebaseapp.com

When I test apps using Firebase command firebase serve --only functions, hosting it works fine.

After deploying apps I get a strange error message in an Angular application and I can´t figure out what's happening.

Browser says Error: could not handle the request

Firebase Log

TypeError: factory is not a function at _callFactory (/user_code/node_modules/@angular/core/bundles/core.umd.js:10996:20) at _createProviderInstance$1 (/user_code/node_modules/@angular/core/bundles/core.umd.js:10948:26) at resolveNgModuleDep (/user_code/node_modules/@angular/core/bundles/core.umd.js:10930:17) at NgModuleRef_.get (/user_code/node_modules/@angular/core/bundles/core.umd.js:12167:16) at resolveDep (/user_code/node_modules/@angular/core/bundles/core.umd.js:12657:45) at createClass (/user_code/node_modules/@angular/core/bundles/core.umd.js:12527:32) at createDirectiveInstance (/user_code/node_modules/@angular/core/bundles/core.umd.js:12364:37) at createViewNodes (/user_code/node_modules/@angular/core/bundles/core.umd.js:13822:53) at callViewAction (/user_code/node_modules/@angular/core/bundles/core.umd.js:14256:13) at execComponentViewsAction (/user_code/node_modules/@angular/core/bundles/core.umd.js:14165:13)

**Comment by ampgular** [comment]
Hi, have you checked whether the function is firing correctly in your fire console?
After having serve locally, have you properly changed the functions url in your code base?
Sorry for being so simple...but I went through this errors myself!

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by vinodmurali** [comment]
I am facing the same issue as above. Any solutions?
