### ISSUE TITLE
AngularJS Application running issues in IE11

### ISSUE THREAD

**Issue by LessFilling1** [angular/angular#23467]
I am using AngularJS.  Project runs perfectly in Chrome(desktop) version 66.0.3359.117 but when I tried to use IE11 version 11.371.16299.0 - nothings shows up.
Console shows me the following Error:

![Error][1]

![ErrorDetails][2]
(Platform: Windows 10; Node version: 8.9.4)

Anyone knows how to solve this problem?

  [1]: https://i.stack.imgur.com/Sz4QK.png
  [2]: https://i.stack.imgur.com/A0sXX.png

**Comment by vicb** [comment]
Your question sounds like a support request. 

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
