### ISSUE TITLE
Misleading typo in Benchpress ReadMe

### ISSUE THREAD

**Issue by PaulTFreedman** [angular/angular#23471]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Under [Measuring in the browser](https://github.com/angular/angular/tree/master/packages/benchpress#measuring-in-the-browser) the names used indicate that the loop iterates 10,000 times but it actually iterates 100,000 times. It's a minor issue but for the sake of clarity it's worth correcting.

## Expected behavior

Iterate 10,000 times.

## What is the motivation / use case for changing the behavior?

To increase clarity of example.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vicb** [comment]
@PaulTFreedman would you like to send a PR ?
