### ISSUE TITLE
Add option to change the default "" view -> model value when an input is empty

### ISSUE THREAD

**Issue by AbakumovAlexandr** [angular/angular#23474]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior

When an input becomes empty, `DefaultValueAccessor` writes empty string ('') into a (for instance, `ngmodel`) bound property.

## Expected behavior

We should have the ability to change the default empty string behavior however we want, for example, to `undefined`, `null`, `'<empty>'`, etc.

## What is the motivation / use case for changing the behavior?

The solution provided by @pkozlowski-opensource in #9146 [(solution)](https://github.com/angular/angular/issues/9146#issuecomment-241191899), i.e. using custom value accessor based on a selector with some non-standard `<input type="uppercase">` is not really good option. When you have a bunch of other directives (for instance, from Angular Material or any other 3rd party library beyond your control), you need to keep your `input`s with the proper `type="text"` which you can't do - see [Stackblitz](https://stackblitz.com/edit/angular-default-value-accessor-issue). `MyDefaultValueAccessor` breaks view -> model value propagation when the same selector expression as in standard `DefaultValueAccessor` is used. You have to switch it to a different `selector: "fakeType"` in order to maintain the value propagation, but this means `MyDefaultValueAccessor` would not work with inputs with standard HTML types.

## Environment

<pre><code>
Angular version: 5.2.10

**Comment by AbakumovAlexandr** [comment]
Ok, got it working at least (see [Stackblitz](https://stackblitz.com/edit/angular-default-value-accessor-issue)). But if I understand correctly, when two or more `ControlValueAccessor` directives have absolutely the same selectors, they all get instantiated and applied, right? This does not seem good.

Also, what I don't understand is how they all working simultaneously. Which one does 'win'? Do they all affect the input value one-by-one or only the winner one?

Comments on this are highly appreciated.

**Comment by xaviergxf** [comment]
@AbakumovAlexandr shouldn't DI be used to replace behavior? When will this be implemented?

**Comment by xaviergxf** [comment]
My problem is: I have a formgroup with a formcontrol binded to a null value, when user updates the textarea associated to it, value changes to empty string. Empty string is different than null then pristine is set to false. I tried using @AbakumovAlexandr StackBlitz but pristine is still false even when FormControl value is now setted to null (not different from when the form was binded). How can i get the desired behavior: When value is binded to null, undefined or empty string pristine should be false (those values are the same for my application).
