### ISSUE TITLE
Guidance request regarding enabling Angular as a JupyterLab extension

### ISSUE THREAD

**Issue by SimonBiggs** [angular/angular#23478]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[x] Other... Please describe:

I wish to make a pull request and I am seeking initial guidance.

</code></pre>

## Current behavior

`angular-language-service` doesn't pick up the custom import method required when creating a [JupyterLab extension](https://github.com/jupyterlab/jupyterlab) with Angular.

### Further details

When making a JupyterLab extension it is not possible to customise `webpack.conf.js`. To make Angular and its templates be able to be used within a JupyterLab extension the loader is inlined within the import as so:

```typescript
import * as htmlTemplate from 'html-loader!./variable-table.component.html';
```

(see https://github.com/SimonBiggs/scriptedforms/blob/master/scriptedforms/src/app/variables-module/variable-table.component.ts#L46)

This is possible as long as the following type definition is created:

```typescript
declare module "html-loader!*.component.html" {
  const content: string;
  export = content;
}
```

(see https://github.com/SimonBiggs/scriptedforms/blob/master/scriptedforms/src/component-html.d.ts)

This however, understandably, breaks the logic of the `angular-language-service`. I desire to be able to create a pull request to make this use case be able to be detected by the `angular-language-service`, I just need a pointer in the right direction.

## Expected behavior

Be able to have angular-language-service pick up imports in the form shown at https://github.com/SimonBiggs/scriptedforms/blob/ba9ef5c281be54fa080a89b5de11ccb28e500e30/scriptedforms/src/app/variables-module/variable-table.component.ts#L46

## What is the motivation / use case for changing the behavior?

To be able to create JupyterLab extensions with Angular and Angular templates and still be able to properly use the angular-language-service

## Environment

<pre><code>
Angular version: 5.2.5
"@angular/language-service": "5.2.9"
</code>
</pre>

**Comment by kyliau** [comment]
As we focus on the next iteration of language service based on Ivy, we currently do not have capacity to support third party extensions. If this use case is still relevant, please let us know what the goals are for the integration, and how language service could support those use cases. I'll close this issue for now, please reopen if further discussion is necessary.
