### ISSUE TITLE
AOT: Not possible to import library directive without declaring module

### ISSUE THREAD

**Issue by anjmao** [angular/angular#23475]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When I importing directive from library validators library and building with aot I'm getting error
```
Cannot determine the module for class Base64Validator in /source/ng-validators/integration/node_modules/@ng-validators/ng-validators/ng-validators.d.ts! Add Base64Validator to the NgModule to fix it.
```
This is how my main library index.ts file looks https://github.com/anjmao/ng-validators/blob/master/src/index.ts. I'm exporting only validatorFn(for reactive forms) and validator directive which is a wrapper to use in template driven forms.

And this is how client's who is consuming library import looks like This is how client who is using library looks https://github.com/anjmao/ng-validators/blob/master/integration/src/app/app.module.ts#L5.

## Expected behavior
It should be possible to import component from npm library without the need to create module for it.

## Minimal reproduction of the problem with instructions

1. Clone https://github.com/anjmao/ng-validators
2. yarn install, yarn build, yarn link
3. cd integration, yarn install, yarn link @ng-validators/ng-validators
4. in integration folder build app `ng build --aot`

## What is the motivation / use case for changing the behavior?
I'm creating validators library for both reactive and template driven forms. I don't want to force user to import whole module so I decided that it is best if user can import only that he needs and create his own validators module.

**Comment by dawidgarus** [comment]
When You build app with aor, not used directives will not be included, thanks to tree shaking. There no need to cherry pick directives manually.

**Comment by anjmao** [comment]
That is not true. If I create module with all validators then all of them will be included in the final bundle even if no one is used. There is no way to tree shake it because you are referencing class in NgModule declarations array.

**Comment by vicb** [comment]
We have introduced tree shakeable providers a few weeks ago - that might help.
That will be an important focus for the next iteration of Angular which we are actively working on.

**Comment by anjmao** [comment]
@vicb Hi, is this issue is closed because you also working on allowing to to create library without NgModule? I don't see how would you tree shake unused directives.

**Comment by trotyl** [comment]
@anjmao Directives are already tree-shakeable now when importing NgModule, for support question please made it in StackOverflow.
