### ISSUE TITLE
Allow CSS `var(--xxx)` function in style sanitizer?

### ISSUE THREAD

**Issue by iceberg-young** [angular/angular#23485]
**I'm submitting a** ... (check one with "x")
```
[x] bug report
[ ] feature request
```

**Current behavior**
A style binding with a [CSS variable](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) will get stripped out by the style sanitizer.

For example, when I try to use [Bootstrap provided variables](https://getbootstrap.com/docs/4.1/getting-started/theming/#available-variables)
```html
<span style="color: var(--primary)">Primary</span>
and
<span [style.color]="'var(--secondary)'">Secondary</span>
and
<span style="color: var({{colorVar}})">Dynamic</span>
```
The render result in browser will be
```html
<span style="color: var(--primary)">Primary</span>
and
<span>Secondary</span> <!-- <<< Note this one -->
and
<span style="">Dynamic</span> <!-- <<< and this one -->
```

**Expected behavior**
Since I'm very likely to use CSS variables in dynamic way, I think they should not be stripped out.

---
P.S.
https://github.com/angular/angular/blob/6761a6452283ef47ad603987518521e2cdb4b723/packages/core/src/sanitization/style_sanitizer.ts#L31
Is it the correct place to modify?
```patch
- const CSS3_FNS = '(?:calc|attr)';
+ const CSS3_FNS = '(?:calc|attr|var)';
``` 
Could (_or will_) `var` belongs to CSS3 from a [Candidate Recommendation](https://www.w3.org/TR/css-variables/)?

**Comment by ericmartinezr** [comment]
related https://github.com/angular/angular/issues/9343

**Comment by sandangel** [comment]
I face this issue when using css repeat() function in inline style.

**Comment by benlesh** [comment]
Related google issue: http://b/115506288
