### ISSUE TITLE
fileUpload in primeng upload files can post without HttpInterceptor

### ISSUE THREAD

**Issue by wszgrcy** [angular/angular#23493]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
 I use fileupload in primeng  when I click upload button,I find httpinterceptor isn't work,but nodejs(my serve) can receive the data.
The httpinterceptor has worked with other states.

## Expected behavior
Because the http request doesn't cross the httpinterceptor,the token in httpinterceptor can't be add.

## Minimal reproduction of the problem with instructions
choose any file,and upload,then nodejs(my serve) will receive data without httpinterceptor
## Environment
https://www.primefaces.org/primeng/#/fileupload
<p-sidebar [(visible)]="display">
    Content
</p-sidebar>
Angular version: 5.2.9

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@wszgrcy ... PrimeNG is a third party lib ... you have to report any issues on their repository not on Angular.

... btw: They use the native XHR interface to do some things so ... no `HttpClient` involved in those cases.

**Comment by robwormald** [comment]
Please file issues with PrimeNg in *their* repo!
