### ISSUE TITLE
HttpClientModule - XSFR Token Support for GET Requests

### ISSUE THREAD

**Issue by justin-ruffin** [angular/angular#23491]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently the HttpClient does not support XSFR Tokens on Get Requests.

## Expected behavior
HttpClient should support XSFR Tokens on Get Requests.

## What is the motivation / use case for changing the behavior?
Security Issue

Some Enterprise API Frameworks secure all Http requests irrespective of the Method (e.g Get vs Post).
This is done for security reasons (e.g An inexperienced developer creates a back-end "GET" request which  mutates data).

The fact that the HttpClient doesn't support this option out of the box, makes communication with server APIs more insecure than the previous version (HttpModule), because the Server API's will have to remove the XSRF token verification on all Get Requests, now opening a possible vulnerability on the server side.

The previous HttpModule supported GET Requests.

## Environment

<pre><code>
Angular version: 5.2.9

**Comment by robwormald** [comment]
The default configuration is set up per OWASP best practices, namely that GET requests should *never* mutate server data. While I appreciate that some frameworks may do this, we can't cover all use cases by default. As such, you can provide your own implementation of an Http Interceptor that adds XSRF tokens to get requests. 

See https://angular.io/guide/http#intercepting-requests-and-responses for how to use interceptors, and https://github.com/angular/angular/blob/master/packages/common/http/src/xsrf.ts#L70 for the default interceptor you can use as a base for your own.
