### ISSUE TITLE
Documentation not clear on dynamic component loading

### ISSUE THREAD

**Issue by SetTrend** [angular/angular#23498]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
The current documentation on [Dynamic Component Loading](https://angular.io/guide/dynamic-component-loader) is partially quite ambiguous and, thus, hard to get.

1. At the beginning it doesn't clearly differentiate between custom and library directives.
1. The "ad" example description doesn't match the actual example.
1. It doesn't get clear on whether "dynamic component loading" means
   1. "loading components dynamically from a fixed, precompiled set of components" or
   1. "loading components dynamically from a web service, which are unknown at compile time".

## Expected behavior

I tried to amend the documentation in regard to (1) and (2).

But I don't have a clue on (3). The requirement of adding components which are supposed to be loaded dynamically to the `entryComponents` configuration member of an NgModule makes me believe it's rather (3.i) than (3.ii):

## What is the motivation / use case for changing the behavior?

To clearly understand the topic right from the beginning, without additionally consulting search engines.

**Comment by jenniferfell** [comment]
filename=https://angular.io/guide/dynamic-component-loader

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.

Feel free to drop any suggestions for the new doc site, thank you.
