### ISSUE TITLE
Angular and Golang

### ISSUE THREAD

**Issue by khwerhahn** [angular/angular#23497]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Hi it would be great if the Angular and Golang team could join forces and create a nice development experiences using both Google in-house developed languages/frameworks.

**Comment by robwormald** [comment]
Angular and Golang work great together, but our teams have no plans to create anything like this. Maybe you could create such a thing and open-source it? In any case, this isn't an actionable issue so I'm closing it. Thanks!
