### ISSUE TITLE
Issue with Observables guide - examples do not work

### ISSUE THREAD

**Issue by avrim** [angular/angular#23490]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

HI,
In the documents for Observables, there is an issue with the examples:
url :    https://angular.io/guide/observables
if you will take a look at the examples and try to run them as they are, they won't run
Please fix them
## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@avrim ... can you be more concrete? Now it is so vague that maybe totally unusable. Always an online simple demo reproduction is requested ... the best on http://stackblitz.com.

**Comment by robwormald** [comment]
Please provide a reproduction.
