### ISSUE TITLE
function trows property not defined

### ISSUE THREAD

**Issue by lloydst** [angular/angular#23506]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
```
checkTime() {
    console.log(this.hour)
    if(this.hour > 17) { // 16h = 4pm
      console.log('no 1 should be working')
      return this.time = 'past 6'
    } else if(this.hour > 15) {
      console.log('display travel info')
      return this.time = true ;
    } else if(this.hour <= 15) { 
      
      setTimeout(() => {
        this.openWindow()
      }, 500);
      return this.time = false;
    } 
  }
  
  openWindow() {
    var x = 0;
    //console.log(this.data)
    var arrayOfUrls =[]
    var url = document.querySelectorAll('span#urls')
    for (let i = 0; i < url.length; i++) {
      arrayOfUrls.push(url[i].innerHTML) 
    }
    // test array of urls
     arrayOfUrls = ['https://facebook.com','https://google.com','https://youtube.com']
      function go() {
        var myWindow = window.open(arrayOfUrls[x])
        if(x === arrayOfUrls.length) {
          console.log('should be called last')
          myWindow.close()
          this.checkTime()
        } else if (x++ < arrayOfUrls.length) {
          setTimeout(() => {
            myWindow.close()
            console.log(x)
            go()
          // change this number to change the time it switches between websites
          }, 1000); // 1 min for each website this means it checks time every 17 min
        }
      }

      go()
      
  } 
```
this.checkTime() trows err: core.js:1448 ERROR TypeError: Cannot read property 'checkTime' of undefined
## Expected behavior
checkTime gets called

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-xjpqf8

## Environment
dev and prod
<pre><code>
Angular version: 5.2.0

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.10.0  
- Platform:   Windows

**Comment by lloydst** [comment]
calling checkTime in on init works as expected btw

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
