### ISSUE TITLE
small typo in ‘src/app/highlight.directive.ts’ embedded code snippet

### ISSUE THREAD

**Issue by arunkarthicksr** [angular/angular#23503]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

There is a small typo in ‘src/app/highlight.directive.ts’ embedded code snippet on 'https://angular.io/guide/attribute-directives#respond-to-user-initiated-events'

## Expected behavior

'}' expected at the last line in ‘src/app/highlight.directive.ts’ embedded code snippet on 'https://angular.io/guide/attribute-directives#respond-to-user-initiated-events'

## Minimal reproduction of the problem with instructions

Navigate to ‘src/app/highlight.directive.ts’ embedded code snippet on 'https://angular.io/guide/attribute-directives#respond-to-user-initiated-events'.

## What is the motivation / use case for changing the behavior?

Fix could improve the readability of the code.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
Confirmed. Missing final } in the code snippet shown after this intro text: "Here's the updated directive in full:"
https://angular.io/guide/attribute-directives#respond-to-user-initiated-events

**Comment by brandonroberts** [comment]
@arunkarthicksr would you like to submit a PR for this? I can provide assistance if needed.

**Comment by arunkarthicksr** [comment]
Sure Brandon. Please share me the details on the branch.
Cheers,
Arun

Sent from Mail for Windows 10

**Comment by brandonroberts** [comment]
Here is a link to the file that needs editing: https://github.com/angular/angular/blob/master/aio/content/examples/attribute-directives/src/app/highlight.directive.2.ts

You should be able to edit directly from GitHub by clicking the pencil on the toolbar.
You add a docregion for `mouse-methods, ` before and after the `}` on the last line of the file. The file has examples of using `#docregion` and `#enddocregion`. 
After you edit, you can create a branch with a commit message and submit the PR directly from there.
