### ISSUE TITLE
Assets folder not serving

### ISSUE THREAD

**Issue by PeterDavidCarter** [angular/angular#23501]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Attempting to reference an image (logo.svg) from within the assets folder using the src assets/images/logo.svg results in the following error 

`logo.svg:1 GET http://localhost:4200/assets/images/logo.svg 404 (Not Found)`

## Expected behavior

I expected the logo to serve from the assets directory

## Minimal reproduction of the problem with instructions

n/a
## What is the motivation / use case for changing the behavior?

So images are not broken on webpages

## Environment
Windows 10, Linux subsystem with Ubuntu installed

<pre><code>
Angular version: 5.2.0

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by PeterDavidCarter** [comment]
Appears to be a problem with file paths. Dropping back to the Windows root from the Windows Linux subsystem Ubuntu installation I was working on solved the problem. Obviously this is an issue with Angular and needs to be fixed.

**Comment by robwormald** [comment]
Please see the assets config here - https://github.com/angular/angular-cli/wiki/stories-asset-configuration and validate you're setting it up correctly (note that you likely don't need the `src/` path, if that's what you're doing.

If this is an actual issue, please re-open it on the https://github.com/angular/angular-cli repo and provide a reproduction per the instructions.

**Comment by PeterDavidCarter** [comment]
That's not what I was doing. The setup was correct and was only fixed by moving the file containing folder up the directory tree into Windows root. As stated this is an issue with Angular but if you particularly want this issue there it can be moved. Either way this is a problem with Angular not my setup skills.

**Comment by wartab** [comment]
> Exactly what additional reproduction steps would you need as everything plausible to include is here and I have even helped you out by including my hypothesis on the source of the issue. 

Maybe a reproduction is missing? Show an example of an app that doesn't work.

**Comment by sarunint** [comment]
Please provide an example of an app that didn't work. You could create a repository and put a link here. Without examples, we can't be exactly sure where is the problem.

**Comment by PeterDavidCarter** [comment]
A repo won't help. The problem was solved by moving the exact same repo up the directory tree.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
