### ISSUE TITLE
Angular Doesn't work with urls with search and hashes

### ISSUE THREAD

**Issue by JohnGalt1717** [angular/angular#23508]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
If you pass a url in this form: https://someurl/someroute?id=xxxx#blah=1234 angular loads the site but doesn't route anywhere.

## Expected behavior
Should route to "someroute", and handle the search and hash parts of the Url properly.

## Minimal reproduction of the problem with instructions
See above. Removing the #blah=1234 part makes the URL route properly.

## Environment

<pre><code>
Angular version: 5.2.10

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [X] Edge version XX

**Comment by jainanuj0812** [comment]
Not able to reproduce, can you please share your code over GitHub or on plunk?

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
