### ISSUE TITLE
Update of RELEASE_SCHEDULE.md for Angular 6.0.0

### ISSUE THREAD

**Issue by MarcusMorba** [angular/angular#23505]
It would be great for plannings to get latest information about the progress of the 6.0.0 Major Release.
Please update the "https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md".

Thanks.

**Comment by RainingNight** [comment]
Angular 6.0.0 postponed indefinitely??

**Comment by mlc-mlapis** [comment]
... be patient a bit. It isn't so crucial thing to press anybody because of a week or two ... especially in combination with **ng-conf**. When there will be more concrete information ... they certainly publish the final version of Angular 6 or the exact day.

**Comment by vicb** [comment]
We will update the schedule shortly.

**Comment by larssn** [comment]
You can keep track of what needs to be done for 6.0:
https://github.com/angular/angular/milestones/v6.0

**Comment by RainingNight** [comment]
Any news?
