### ISSUE TITLE
application with large html components on v6.0.0-rc.4 crashes on chrome 

### ISSUE THREAD

**Issue by mlakmal** [angular/angular#23513]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Following github repo is setup with latest 6.0.0-rc.5 version and it is not loading the application on chrome. chrome crashes with aw snap error.
https://github.com/mlakmal/uxd-v6-test

## Expected behavior
should load the application without crashing the browser.

## Minimal reproduction of the problem with instructions
use the below github repo to run this application. and goto url - http://localhost:9000/#/style-guide in browser.
https://github.com/mlakmal/uxd-v6-test

## What is the motivation / use case for changing the behavior?
migrating applicaiton from v5 to v6

## Environment

<pre><code>
Angular version: 6.0.0-rc.5

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1
- Platform:  MacOS

Others:

</code></pre>

**Comment by wojo1206** [comment]
I can't reproduce, compilation errors :(

**Comment by mlakmal** [comment]
Can you post the error ?

**Comment by mlakmal** [comment]
@wojo1206 can u pull latest and try again ? i fixed the build errors, looks like some incorrect local changes got moved with initial commit.

npm install
npm run serve2

**Comment by wojo1206** [comment]
@mlakmal Build succeeded

**Comment by wojo1206** [comment]
@mlakmal I don't see a 'large number of components' in your code. Your code structure isn't well organized. You have general JS errors. 
```js
columnNumber: 54
fileName: "http://localhost:9000/vendor.js line 28632 > Function"
lineNumber: 1361
message: "_co.toggleButtonForm is undefined"
```

**Comment by mlakmal** [comment]
@wojo1206 seems like another issue in my template (i removed my original template component references as i cant share that source-code). just loading this dummy html from route component crashes chrome ...

i fixed the html bindings, can you pull latest and try again ?

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by mlakmal** [comment]
@vicb i did provide full repo that can be used to reproduce this problem in chrome. can you let me know what else is required ?
