### ISSUE TITLE
Feature: Intentionally Don't Encapsulate Specified Style

### ISSUE THREAD

**Issue by Vandivier** [angular/angular#23525]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Styles are encapsulated when we use `@Component({ ..styleUrls... })`

## Expected behavior

Specified styles will be intentionally not encapsulated, so that a component can intentionally affect the style of other components when loaded.

1. This allows better re-use of generic components, because those generic components can be overridden by their children, siblings, and wrappers, without modifying a global style, and without the need to modify the original component.
1. This allows developers to keep style which is logically attributable to a single component (the child) in a style file specifically associated with that component, rather than adding it to a global style file.
1. This reduces code needed because a developer doesn't need to use :not() conditions and other such statements which may be relevant to a style rule in a global file, but they are extraneous when a certain component is utilized.
1. This uses CSS correctly instead of causing JS workarounds like importing DOCUMENT into a child in order to manipulate other contexts.

Propose implementation (2 options):
1) the :global pseudoclass. Just like we have :host
2) styleUrls takes an object, the object can have a property like global: true, or even closest: 'css-selector', which would find the nearest element matching the css selector and treat the matched element as :host for each contained style rule, inspired by [jQuery](https://api.jquery.com/closest/).

## Minimal reproduction of the problem with instructions

Code is proprietary, but pseudo-code included in the use case below

## What is the motivation / use case for changing the behavior?

1. Create an OverlayComponent with a closed button in the top-right
1. OverlayComponent's template includes `<ng-container *ngComponentOutlet="overlayContent"></ng-container>`, so you can pass arbitrary components to display within the component.
1. Now, a certain child component has a logical condition which should hide the closed button in the top-right.

## Environment

<pre><code>
Angular version: All versions, all browsers (afaik)

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by robwormald** [comment]
Is this different than using `ViewEncapsulation.None`?

**Comment by Vandivier** [comment]
I think so, but we can close if you can show how I've mistaken ViewEncapsulation.None.

I think ViewEncapsulation.None applies to all your style, whether added in styleUrl or not. By contrast, :global would allow rule-by-rule specification. styleUrl option objects would allow script-by-script config.

Also, the jQuery-inspired 'nearest' encapsulation is different from just turning encapsulation off.

**Comment by vicb** [comment]
You should be able to use [`polyfill-unscoped-rule`](https://github.com/angular/angular/blob/43a49d3f645408646d741aa800b21803a4310235/packages/compiler/test/shadow_css_spec.ts#L211)

If that works for you we should probably add this to the docs.

**Comment by Vandivier** [comment]
@vicb I've confirmed that with default ViewEncapsulation, the following rule resolved my use case:

    polyfill-unscoped-rule {
        content: '.icon-button.top-right';
        display: none;
    }

Feel free to close, but I'll leave open in case you want to track the docs change with this issue.

**Comment by Vandivier** [comment]
@vicb I have to withdrawal my statement that polyfill-unscoped-rule fixes all scenarios. It does fix several, but here's one problem left open:

    // ref: https://github.com/angular/angular/issues/23525#issuecomment-384094001
    .overlay-child {
        polyfill-unscoped-rule {
            content: '.icon-button.top-right'; // .icon-button exists outside .overlay-child, in .overlay-parent
            background: url('./close-icon');
        }
    }

    .overlay-child.changed-child-state {
        polyfill-unscoped-rule {
            content: '.icon-button.top-right';
            background: url('./submit-icon');
        }
    }

As a developer, I still have to bring in DOCUMENT and change classes on the parent in this scenario.

**Comment by dawidgarus** [comment]
Why not just import css in component?
```typescript
import 'my.component.global.css';

@Component({
  styleUrls: ['my.component.css']
})
export class MyComponent {}
```

**Comment by Vandivier** [comment]
With `polyfill-unscoped-rule` and the workaround I described above, I notice the following issue:

1. OverlayChild1 successfully hides parent close icon using `polyfill-unscoped-rule` and implements child-close-icon as described.
1. OverlayChild2 doesn't implement child-close-icon. The parent icon is still hidden.

Notice that these components are not open simultaneously. When I close OverlayChild1 the `polyfill-unscoped-rule` persists, so that when I open OverlayChild2 later it creates an issue. Do I need to specially handle OverlayChild1's closing? I have *ngIf on a wrapper, so it is removed from the DOM.

Remember that I'm using `<ng-container *ngComponentOutlet="overlayContent"></ng-container>`, so this may be related to [PR #15362](https://github.com/angular/angular/pull/15362/files).

`:encapsulateNearest()` would solve all known scenarios, so that remains my favorite.

**Comment by kondasMajid** [comment]
Regardly some of my Css  files weren't working as expected locally till i  used _ViewEncapsulation.None?_ and it work locally on the selected component perfectly, i think in  way encapsulation works locally in some way..

**Comment by woble** [comment]
@Vandivier 
FWIW, project I am working with being able to import multiple styles and flag which ones should become global could prove extremely useful. Currently we resort to declare `import 'foo.css'` inside `ts` files, but that method is not very flexible in our setup, in the sense that depending on the build configuration and the inheritance nature of the solution we might not want these styles at all or want to replace these styles with something else completely without having to override individual properties. `:global` could work as well if it was an option.

Using `polyfill-unscoped-rule` is an option, but it doesn't look very convenient to work with.

So far as I am concerned, adding option 1 or 2, or both would be a great addition.

**Comment by kondasMajid** [comment]
@woble  sorry to chip in.
With multiple Css maybe with the same  file name or not or same css classes names.
You can preferably call the Css you wanna use along the projects at for speficied compoent,, it mostly run first so if you want to control a specific css to run on a component then call all of in the component and en-capsule to none.

**Comment by thefliik** [comment]
@Vandivier when using `ViewEncapsulation.Emulated` (the default) you can use the [`::ng-deep` pseudo selector](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep) to specify specific styles which are not scoped/encapsulated to the component.

Example with SCSS
```
.car {
  color: blue;
}

::ng-deep {
  .boat {
    color: green;
  }
}
```

Note, the docs say that the `::ng-deep` selector:

> forces a style down through the child component tree into all the child component views.

However in reality it simply removes any scoping from the specified styles, which I believe is exactly what you are asking for?

This does not work with `ViewEncapsulation.ShadowDom` or `ViewEncapsulation.Native`. I think the shadow DOM specification *requires* that css be scoped to children of the component, so what you ask will probably not ever be possible when using those encapsulation methods.

**Comment by Vandivier** [comment]
@thefliik I'm not really involved in this conversation anymore, but to anyone who is considering using ::ng-deep, just keep in mind [the docs](https://angular.io/guide/component-styles):

"Use /deep/, >>> and ::ng-deep only with emulated view encapsulation. Emulated is the default and most commonly used view encapsulation. For more information, see the Controlling view encapsulation section.

The shadow-piercing descendant combinator is deprecated and support is being removed from major browsers and tools. As such we plan to drop support in Angular (for all 3 of /deep/, >>> and ::ng-deep). Until then ::ng-deep should be preferred for a broader compatibility with the tools."

**Comment by petebacondarwin** [comment]
Since the idea of breaking out of the scope of an encapsulated component is not something that would ever be supported natively (via ShadowDOM) I don't believe we should offer it as an aspect of our component system.

I think the best solution is to define a service that acts as a global styling provider, then inject that service into any components that want to specify global styling... See here for an example: https://stackblitz.com/edit/angular-ivy-cs6sog?file=src%2Fapp%2Fapp.component.html
