### ISSUE TITLE
Add support for global helper functions within the template

### ISSUE THREAD

**Issue by matsko** [angular/angular#2352]
It would be great for the router if we had a global helper function that we can call within any portion of the template as well as in our JavaScript component code.

```html
<a (click)="routeUrl('homePage')">
   Click me
</a>
```

Currently Angular2's expression code is only local (relative to the parent component within the template) so having a global helper function that can be called anywhere isn't possible.

Let's make this happen.

**Comment by gdi2290** [comment]
Rather than just global I rather allow people to scope it to be similar to adding bindings. Bindings allows per component or global app which means small apps use global while large apps scope it out

```es6
@View({
  expressions: []
  templateUrl: 'wat.HTML'
})

**Comment by mhevery** [comment]
We have discussed this, and we think that the best way to do this is to have the component inject and then export this function.

```javascript
@Component(...)
@View({
  tempalate: `<a href="{{route.mainView()}}">main view</a>`
})
class MyComponent {
  route: Route;

  constructor(route:Route) {
     this.route = route;
  }
}
```
