### ISSUE TITLE
BehaviorSubject produces ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by macifell** [angular/angular#23522]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The following error is produced when modifying the value of a BehaviorSubject as a side effect in an Observable pipe().
```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngIf: [object Object]'. Current value: 'ngIf: false'.
```

Also, If I use ChangeDetectionStrategy.OnPush, the update to the behavior subject in the pipe() is never detected.

## Expected behavior

I would not like to see any javascript errors and would like the change detection to figure out that the behavior subject's value has changed when using `ChangeDetectionStrategy.OnPush`.

## Minimal reproduction of the problem with instructions

The code:
```
import {ChangeDetectionStrategy, Component, OnInit} from '@angular/core';
import {tap} from 'rxjs/operators';
import {BehaviorSubject, Observable, of} from 'rxjs/index';

@Component({
  selector: 'something-or-other',
  template: '<div *ngIf="loading$ | async">Loading...</div><div>{{ response$ | async }}</div>'
  // , changeDetection: ChangeDetectionStrategy.OnPush
})
export class SomethingOrOtherComponent implements OnInit {

  response$: Observable<string>;
  loading$: BehaviorSubject<boolean>;

  ngOnInit() {
    this.loading$ = new BehaviorSubject(true);

    this.response$ = of('response').pipe(
      tap(() => this.loading$.next(false))
    );
  }

}
```

I also get the same behavior without using `ngOnInit()`:
```
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {tap} from 'rxjs/operators';
import {BehaviorSubject, of} from 'rxjs/index';

@Component({
  selector: 'something-or-other',
  template: '<div *ngIf="loading$ | async">Loading...</div><div>{{ response$ | async }}</div>'
  // , changeDetection: ChangeDetectionStrategy.OnPush
})
export class SomethingOrOtherComponent {

  loading$ = new BehaviorSubject(true);
  response$ = of('response').pipe(
    tap(() => this.loading$.next(false))
  );
}
```
## What is the motivation / use case for changing the behavior?

The scenario is intended to be a simplified version of displaying a loading message while retrieving data from a server.

## Environment

<pre><code>
Angular version: 5.2.10

Browser:
- [x] Chrome (desktop) version 65.0.3325.181 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vicb** [comment]
Please include a simple repro with stackblitz.

**Comment by macifell** [comment]
https://angular-gitter-lx641u.stackblitz.io

**Comment by macifell** [comment]
Cool, thanks for both of your detailed explanations @JoostK
