### ISSUE TITLE
node_modules/@angular/common/http/src/params"' has no exported member 'HttpParamsOptions'.

### ISSUE THREAD

**Issue by roscoedeemarutam** [angular/angular#23523]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[Xnpm ] Other... Please describe: node_modules/@angular/common/http/src/params"' has no exported member 'HttpParamsOptions'.
</code></pre>

## Current behavior
the build error is the title (I'm working with angular 5.2 and npm 6. When I double check the online params.ts and the one in the node modules they are different??????? Could someone help me out here because I find it a little strange that the version I install is different then they official github version

## Expected behavior
same version on my machine and in github

## What is the motivation / use case for changing the behavior?
I need to make a querystring out of my request object and this seems to be the way to do it?!

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.11.0  
- Platform:   Windows 

Others:

</code></pre>

**Comment by wojo1206** [comment]
Steps to reproduce please

**Comment by Toxicable** [comment]
you cant import from that path.
use `@angular/common/http` instead

**Comment by alxhub** [comment]
@Toxicable's answer is correct.

**Comment by roscoedeemarutam** [comment]
Why is this closed??????? I have not commented or received a solution, because NO that answer (for me is not correct
![noexportedmember](https://user-images.githubusercontent.com/35805262/39245837-1fd428e4-4895-11e8-96c2-2a09dd7e8cc6.PNG)

**Comment by roscoedeemarutam** [comment]
and step to reproduce ... npm install with this package
![packagejson](https://user-images.githubusercontent.com/35805262/39245986-93ea4786-4895-11e8-95ad-6fe65836437f.PNG)

**Comment by roscoedeemarutam** [comment]
wow... a thumbs down but no comment or solution? so much for that then.... thx a lot for nothing
