### ISSUE TITLE
can't add a Header on GET API calls on iOS (desktop works)

### ISSUE THREAD

**Issue by borriej** [angular/angular#23532]
[x] Bug

Hi,

I think i found a bug, or im doing something stupid.

*Steps*
* When I log-in, my POST returns a user object... with a token
* I add that token to my session service
* I have a token intercepter that adds the Authorization header on each request

*Problem*
All API calls authenticate fine on desktop... 
but on iOS chrome / safari... and on Android Chrome... the application headers are not being sent :(

*How to reproduce?*
* Create this simple service API call that adds a custom header... and call it from a component.

```
export class RidesService {

    constructor(
        private http: HttpClient
    ) {
    }

    public getList(): Observable<Ride[]> {
       
        let url = `/api/rides`;
        let headers = new HttpHeaders('Authorization: testtoken');
        
        return this.http.get<Ride[]>(url, { headers: headers })
            .do(res => {
            })
            .catch(err => {
                return Observable.of(null);
            });
    }
}
```
* On your local develop computer... run your app and check your network request.. the Authorzation header has been added to your GET... 
* Now... Connect your iPhone to Mac over USB
* Go to Safari, enable debugging, open the console to monitor network request
* On your iPhone, go to local server (which I set to 0.0.0.0.:4200).... so you can access your local server via Wifi (eg. on 192.168.1.2:4200) on your iPhone
* When i log the network request... the API header 'Authorization' is not added :'( 

```
GET /api/rides/ HTTP/1.1
Host: 192.168.1.2:4200
Accept: application/json, text/plain, */*
Connection: keep-alive
Accept-Language: nl-nl
Accept-Encoding: gzip, deflate
Cookie: .......
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
Referer: http://192.168.1.2:4200/app/rides/117/2018/1
```

*version*
angular version 5.2.7

**Comment by vicb** [comment]
Please add a repro using StackBlitz

**Comment by alxhub** [comment]
Just FYI, this seems like it could be an issue with CORS. Double-check that your server is setting the right CORS headers.

**Comment by borriej** [comment]
**I've created a stackblitz...**
https://stackblitz.com/edit/angular-rvk8d1

which uses the API from 
```
https://jsonplaceholder.typicode.com/posts
```

**I've also created a minimal repo on my local machine..**
which uses api:
```
http://127.0.0.1:8000/api/rides
```
(and my local frontend runs on 0.0.0.0:4200)

**what i've found so far:**
* the Stackblitz can add headers on Desktop: Chrome & Safari 
* the Stackblitz can add headers on Mobile: Safari
```
Authorization: testtoken
If-None-Match: W/"6b80-Ybsq/K6GwwqrYkAsFxqDXGC7DoM"
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
Referer: https://angular-rvk8d1.stackblitz.io/
```
* My local repo can add headers on Desktop: Chrome
* My local repo can NOT add headers on Desktop: Safari
* My local repo can NOT add headers on Mobile: Safari

**Comment by borriej** [comment]
SOLVED
------------------------
What was the issue? ... 
Safari needs an ending slash on the API's for the Authorization Header to be appended... Where chrome doesn't need the ending slash and can always add API Headers. I've appended the slash and it's also working on mobile devices now!

**wrong**
```
        let url = `/api/rides?vehicle_id=${params.vehicleId}&year=${params.year}`;
```
**correct**
```
        let url = `/api/rides/?vehicle_id=${params.vehicleId}&year=${params.year}`;
```
