### ISSUE TITLE
Angular 5 animations do not work (Material/Bootstrap buttons)

### ISSUE THREAD

**Issue by gan-mel** [angular/angular#23542]
Hey, I have tried to apply the normal button of angular material but the ripple affect will not work at all, I have also tried to use bootstrap's animations and it's like they reach to their end state immediately or something.. there is no fade for the bootstrap 4 button.

Is it possible it relates somehow to: 20725?

but it says it's closed.

Iv'e got:

```ts
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
import 'zone.js/dist/zone';
import 'hammerjs';
import 'web-animations-js';
import { MatCheckboxModule } from '@angular/material';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import {MatButtonModule} from '@angular/material/button';

imports: [
    MatButtonModule,
    MatCheckboxModule,
    BrowserAnimationsModule
  ],
  providers: [WeatherService],
  bootstrap: [AppComponent, WeatherComponentComponent]
})
```

In the global styles.css file i have: @import

'~@angular/material/prebuilt-themes/deeppurple-amber.css';
dependancies:
"dependencies": {
    "@angular/animations": "^5.2.10",
    "@angular/cdk": "^5.2.5",
    "@angular/common": "^5.2.10",
    "@angular/compiler": "^5.2.10",
    "@angular/core": "^5.2.10",
    "@angular/forms": "^5.2.10",
    "@angular/http": "^5.2.10",
    "@angular/material": "^5.2.5",
    "@angular/platform-browser": "^5.2.10",
    "@angular/platform-browser-dynamic": "^5.2.10",
    "@angular/router": "^5.2.10",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.26"

  "devDependencies": {
    "@angular/cli": "^1.7.4",
    "@angular/compiler-cli": "^5.2.10",
    "@types/jasmine": "^2.8.6",
    "@types/node": "^9.6.6",
    "codelyzer": "^4.3.0",
    "jasmine-core": "^3.1.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^2.0.2",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.6.0",
    "protractor": "^5.3.1",
    "ts-node": "^6.0.0",
    "tslint": "^5.9.1",
    "typescript": "^2.7.0"
  }
HTML:

<button mat-raised-button color="primary">Button</button>
I have also tried to link the stylesheet in the global HTML - but doesn't work still.
-->

<pre><code>
[X] Bug report  
</code></pre>

## Current behavior
Animation doesn't play 

## Expected behavior
Animation plays on over and on click

## Minimal reproduction of the problem with instructions

Load the above versions and implement a button with material.

## Environment

<pre><code>
Angular version: 5

Browser:
- [X ] Chrome (desktop) version 65

 
For Tooling issues:
- Node version: XX  
- Platform:

**Comment by gan-mel** [comment]
Actually after some work I was able to find the superficial cause and it seems to be due to the HTML I have used:

**Comment by gan-mel** [comment]
I was able to find that the this happens due to my HTML:

```
<div>
  <label>name:</label>
    <input placeholder="name" [(ngModel)]="cityName">
    <button  mat-raised-button color="primary" (click) ="submitData(cityName); submitDataBox(cityName)" type="submit">Find Weather</button> 
        
    <form #myForm='ngForm'>      
        <input type="checkbox" class="form-control" 
             #checkBox="ngModel" 
          [(ngModel)]="shown" name="checkBox">
</form>
        <div *ngIf="shown;else other_content"> 
           {{forecasts.list[0].dt}}
        </div>
        <ng-template #other_content>
        
                **<span>Temperature (celsius): {{ weathers.main.temp }} </span>**

              
        </ng-template>

    </div>
```

specifically  {{ weathers.main.temp }}  within the #other_content or for that matter any variable within other content seems to cause all animations to stop functioning correctly.

**Comment by AndrewKushnir** [comment]
Hi, it looks like the error might be related to #18751 (the error message would be improved in #41356). I'm going to close this ticket for now since there is no repro available. If the problem still exists, could you please create a new ticket and include a repro (using [Stackblitz](https://stackblitz.com/)), so we can investigate the issue?
