### ISSUE TITLE
Export a list of "human readable" HTTP status codes

### ISSUE THREAD

**Issue by QuentinFchx** [angular/angular#23543]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Expected behavior

The `@angular/common/http` module should export a list of http status codes.

## What is the motivation / use case for changing the behavior?

Exposing status code would help readability in HTTP responses handling.

```typescript
import { HttpClient, NOT_FOUND } from "@angular/common/http"

@Injectable(){
  constructor(private hc: HttpClient){}

  fetch(){
    return this.hc.get<any>('http://...')
      .catch(err => {
        if(err.status === NOT_FOUND) console.error('Oops...');
      })
  }
}
```

This would be similar to what the Ruby on Rails framework provides (through [Rack](https://github.com/rack/rack/blob/f9393b9b0852fc064eb21ac4df71e07290980d9d/lib/rack/utils.rb#L494)).
A similar initiative exists in the `@angular/cdk` library around [key codes](https://github.com/angular/material2/blob/master/src/cdk/keycodes/keycodes.ts).

I've already started to [implement it](https://github.com/angular/angular/compare/master...QuentinFchx:http-status-codes). I'll go further if the feature is in the scope of what we want to provide with the `common/http` package.

**Comment by zh99998** [comment]
https://www.npmjs.com/package/http-status-codes

**Comment by mlc-mlapis** [comment]
@QuentinFchx ... but it means also increasing the size of `HttpClient` module ... and the question is if it is worth for everybody = you have to load it probably almost in each app.

**Comment by QuentinFchx** [comment]
@zh99998 https://github.com/kabirbaidhya/keycode-js exists, still they added it in the `@angular/cdk` package. I'd say the reasoning behind this is to ease application development by providing basic blocks out of the box without having to rely on hundreds of dependencies.

@mlc-mlapis tree shaking.

**Comment by mlc-mlapis** [comment]
@QuentinFchx ... it depends on what `NOT_FOUND` and others would be in fact.

> tree shaking.

**Comment by QuentinFchx** [comment]
```typescript
export const OK = 200;
export const NOT_FOUND = 404;
```

@mlc-mlapis I understand your initial concerns.
But honestly if you took the time to check the links I added in the issue description you would've seen it's not an issue.
<sub>We have the technology.</sub>

**Comment by zh99998** [comment]
`const enum` will compile to value directly and means totally no size and runtime cost.

**Comment by robwormald** [comment]
This is an interesting idea - with `const enum` it would be zero-cost, as @zh99998 suggests.

@QuentinFchx I reckon we'd probably accept the PR (just spoke with @alxhub about it) - with a couple of changes:
- should be a const enum, vs floating variables - see [example](http://www.typescriptlang.org/play/index.html#src=const%20enum%20HttpStatusCode%20%7B%0D%0A%20%20%20%20Success%20%3D%20200%2C%0D%0A%20%20%20%20MovedPermanently%20%3D%20301%2C%0D%0A%20%20%20%20BadRequest%20%3D%20400%0D%0A%7D%0D%0A%0D%0Aconst%20code%20%3D%20301%3B%0D%0A%0D%0Aif%20(code%20%3D%3D%3D%20HttpStatusCode.Success)%20%7B%0D%0A%20%20%20%20console.log('success!')%0D%0A%7D%0D%0Aelse%20%7B%0D%0A%20%20%20%20console.log('fail')%0D%0A%7D%0D%0A) - this makes it much cleaner to manage, as well as being removed in the runtime code.
- should be consistent with other enum uses in Angular (Pascal case) - `SomeEnum.SomeValue`

**Comment by vamsivarikuti** [comment]
NestJs [HttpStatus](https://github.com/nestjs/nest/blob/master/packages/common/enums/http-status.enum.ts) has similar implementation.

**Comment by vmasek** [comment]
We are using [node-http-status](https://github.com/prettymuchbryce/node-http-status) in our projects. It is a simple implementation exporting constants (enum is a better idea) 
What is good about this that it covers also the text representation of the code and has nice comment + RFC link for each of the codes.
see the [index.d.ts](https://github.com/prettymuchbryce/node-http-status/blob/master/index.d.ts)
