### ISSUE TITLE
npm error notarget for the Angular 6.0.2

### ISSUE THREAD

**Issue by aelkoussy** [angular/angular#23540]
## I'm submitting a...

[x] Bug report 

## Current behavior
As per the release schedule , angular 6.0.2 is released as stable version, however, on using 
`npm i @angular/core@6`

I get this error:
`npm ERR! notarget No matching version found for @angular/core@6`

## Expected behavior
The package (latest of version 6) should be installed on running the cmd:
`npm i @angular/core@6`

## Minimal reproduction of the problem with instructions
run `npm i @angular/core@6
`
## What is the motivation / use case for changing the behavior?
To upgrade the angular version from 5 to 6 (which is released and stable)

## Environment
Angular version: 5.2.10 upgrade to 6.0.2

Browser:
- [x] Chrome (desktop) version 66.0
 
For Tooling issues:
- Node version: 7.9.0
- Platform:  Windows

**Comment by ppjjzz** [comment]
hi bro, angular still not release 6.0 stable version.

**Comment by quantumdream** [comment]
Angular 6 is not a stable release yet, you can check which version is the most recent released on npm by checking https://www.npmjs.com/package/@angular/core under the version tab.

**Comment by aelkoussy** [comment]
so how to find the date of the stable release for angular 6 , if the release schedule is not very accurate?
and generally is it safe to use the beta version now ?
Thank you

**Comment by RainingNight** [comment]
dystocia....

**Comment by astec** [comment]
@aelkoussy check [`package.json`](https://github.com/angular/angular/blob/master/package.json#L3) for current dev version or https://www.npmjs.com/package/@angular/core for latest published release.

P.S. You probably should close this issue to minimize noise.

**Comment by aelkoussy** [comment]
Alright , closing the issue with the recommendation to update the released schedule page.
Thanks guys

**Comment by danwulff** [comment]
@aelkoussy The release schedule docs are estimated release dates, so they won't always be up to date.

There's two ways that I'd recommend for checking the latest releases:

- npm: https://www.npmjs.com/package/@angular/core
- the repo changelog: https://github.com/angular/angular/blob/master/CHANGELOG.md

I personally prefer the latter since you can see a list of the actual changes.

**Comment by aelkoussy** [comment]
@danwulff Thanks a lot for your advice bro :)
