### ISSUE TITLE
setValue function in reactive forms not working when i'm trying to setValue of select element ( with multiple mode )

### ISSUE THREAD

**Issue by HDaghash** [angular/angular#23541]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

setValue function in reactive forms not working when i'm trying to setValue of select element ( with multiple mode )

this.zoneForm.controls.controlName.setValue(['valueAsArry']);

## Expected behavior

should update the checked menu in the select dropdown list 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jainanuj0812** [comment]
Not able to regenerate, maybe this will help you

https://github.com/angular/angular/issues/12059

**Comment by HDaghash** [comment]
it's still not working on i set the value like so

this.myForm.controls.businessType.setValue(['b2cEnabled'])

**Comment by HDaghash** [comment]
it's no binding the selected value guys 
anyone have any clue ?

**Comment by HDaghash** [comment]
if i pull the value 

this. myForm.controls.businessType.value 

it will be update to ['b2cEnabled']

but this is not showing on the UI

**Comment by HDaghash** [comment]
@DzmitryShylovich please advice

**Comment by kara** [comment]
Closing this issue, as there isn't enough actionable info. Please file a new issue that follows the template (most importantly, the minimal repro section), which gives the team the information needed to investigate.
