### ISSUE TITLE
Language Service: using require() to load templates displays component must have a template or templateUrl

### ISSUE THREAD

**Issue by jimmymain** [angular/angular#23553]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## I have a simple component that uses webpack to load templates.
``` javascript
@Component({
  selector: "app-sidebar-header",
  template: require("./app-sidebar-header.component.html")
})
export class AppSidebarHeaderComponent { }
```

## Current behavior

the error is displayed
**Component 'AppSidebarHeaderComponent' must have a template or templateUrl**

## Expected behavior
I do not expect to see the error message 
The template actually exists, it's just being loaded by webpack. This method resolves a lot of issues with loading templates in unit tests, and is essential for my workflow.

Angular version: `5.2.10`

**Comment by rmckeel** [comment]
For what it's worth, I see the same error presenting itself in Angular 6.1.0 with a very similar use case:

**Current Behavior**
`Component "UsersViewComponent" must have a template or templateUrl` 

**Expected Behavior**
No error

```
@Component({
    template: require('./users-view.pug')
})
export class UsersViewComponent { }
```

**Comment by masonmark** [comment]
I have basically the same issue in a hybrid AngularJS/Angular app that is built with webpack. We aren't using the `require()` syntax, though; we use `import * as template from './foo.html';` but we get the exact same error. 

Here is a workaround:

```typescript
import * as template from './new-long-term-discount.component.html';

@Component({
  selector: 'app-new-long-term-discount',
  template: '' + template, // dumb lol but otherwise Angular Language Service flags as error
  styles: []
})
export class NewLongTermDiscountComponent extends AbstractController implements OnInit  {
    //...
}
```

Perhaps the kludge of prepending an empty string to the real template value could work with `require()` as well?

**Comment by rmckeel** [comment]
I am on 7.1.4 currently (including @angular/language-service), and this issue has been resolved for me.  Not sure exactly what point it was resolved.

**Comment by tschaffter** [comment]
Hi, I'm using Angular 8.2.2 and I also have the issue in VS Code v.1.37.1: Component 'PostListComponent' must have a template or templateUrl

```
@Component({
    selector: 'post-list',
    template: require('./post-list.html'),
    styles: [require('./post-list.scss')],
})
```
