### ISSUE TITLE
StaticInjectorError arises when using translate pipe in component

### ISSUE THREAD

**Issue by tryCatchPizza** [angular/angular#23556]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

If you use shared components from seed project which contains translation pipe in html part of the component, and we use that same component in the main project, we get the following error:
`ERROR Error: StaticInjectorError(AppModule)[TranslateService -> TranslateStore]: 
  StaticInjectorError(Platform: core)[TranslateService -> TranslateStore]: 
    NullInjectorError: No provider for TranslateStore!
    at NullInjector.get (core.js:994)
    at resolveToken (core.js:1292)
    at tryResolveToken (core.js:1234)
    at StaticInjector.get (core.js:1102)
    at resolveToken (core.js:1292)
    at tryResolveToken (core.js:1234)
    at StaticInjector.get (core.js:1102)
    at resolveNgModuleDep (core.js:10837)
    at createClass (core.js:10882)
    at _createProviderInstance$1 (core.js:10848)`
This is issue when using `ng serve` and `ng serve --aot` or after deployment of application after `ng build --prod`
## Expected behavior

Expected behavior is that pipe in the component should without error translate given caption.
## Minimal reproduction of the problem with instructions

Clone this repo (https://github.com/tryCatchPizza/reproRepo.git). And after download in seed project execute `npm install` and then `npm link`, after that `npm install` in app folder and then execute again `npm link test-seed`. After the projects are linked run `ng serve` or  `ng serve --aot` and navigate to the page and you should then see the error.
## What is the motivation / use case for changing the behavior?

To be able to use translate pipe in both seed and app projects.

## Environment

<pre><code>
Angular CLI: 1.7.4
Node: 8.11.1
OS: win32 x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

Browser:
- [ X ] Chrome (desktop) version 66.0.3359.117
- [ X ] Firefox version 59.0.2
 
For Tooling issues:
- Node version: 8.11.1
- Platform:  Windows 10

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
@tryCatchPizza I had a brief look at your repo but there is _lots_ of code in there so it is super-hard to understand what is going on. The error message is rather clear: `SaticInjectorError(AppModule)[TranslateService -> TranslateStore]` - it seems like `TranslateStore` is not being added to providers. It is hard for me to say more since the setup in your reproduction is very complex (2 different applications, 3rd party library, ...).

If you still believe that there is a bug in Angular somewhere you will have to come up with a much more reduced reproduce scenario (no 3rd party libraries, a single project, ideally in a stackblitz). Please re-open this issue when you've got a _minmal_ reproduce scenario.
