### ISSUE TITLE
ng server  angular template picture issue

### ISSUE THREAD

**Issue by FlyFire-Young** [angular/angular#23552]
angular template example：
@Component({
  templateUrl: '<img src="./test.png">',
  styleUrls: ['../styles/index.css'],
})
The picture can't be found

**Comment by jainanuj0812** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out our [submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

For this type of issues, please go once stackoverflow as this is not seems like core issue and may be a logical one.
