### ISSUE TITLE
[IVY] Support events on `<ng-template>`

### ISSUE THREAD

**Issue by vicb** [angular/angular#23561]
Render2 supports events on `<ng-template>`:

```html
<ng-template (directiveOutput)="...">
   <!-- ... -->
</ng-template>
```

See the [template parser spec](https://github.com/angular/angular/blob/1a44a0b4a87767236f6eea07deca5e4d8789572f/packages/compiler/test/template_parser/template_parser_spec.ts#L879) for more details

Updates are required for:
- [x] the runtime
- [x] the compiler

**Comment by pkozlowski-opensource** [comment]
Runtime part PR: #25698

**Comment by pkozlowski-opensource** [comment]
Compiler part PR: #25717
