### ISSUE TITLE
Bad exports naming for Directive/Component

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#2356]
the top-level 'angular2/angular2' module re-exports Component as ComponentAnnotation. The actual Component class extends Directive. However, we re-export class Directive as DirectiveAnnotation, and the re-exported Directive is just a var declaration. This breaks the angular2.d.ts since it ends up with a Component extends Directive type, where Directive is not a class.

Current workaround is to export the Directive *annotation* into the .d.ts, but this breaks the application because only decorators should be exposed to JS application.

**Comment by naomiblack** [comment]
@alexeagle we need to discuss how to prioritize this relative to other customer-facing issues -- might need to slip to alpha-30.

**Comment by rkirov** [comment]
The workaround is in `angular2.api.ts`, when this bug is fixed that file should be removed.
