### ISSUE TITLE
Dynamic styling on i tag

### ISSUE THREAD

**Issue by akash-potdar7** [angular/angular#23574]
Hey guys,

So here's my problem, 
I'm getting bunch of font-awesome icon class names from an api, and i loop these in the html and trying to apply this.

`<div>`
`     <i (click)="goTo(item.data1)" class="item.style"></i>`
`</div>`
Can somebody help me out?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by akash-potdar7** [comment]
thanks man!
