### ISSUE TITLE
Change detection is propagated in one direction only

### ISSUE THREAD

**Issue by waterplea** [angular/angular#23578]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently, if you use change detection strategy OnPush — change detection is triggered by user action. Say you have a component with template, and inside that template you use some value. User action can trigger change detection and then the value would be updated. If you use that template as TemplateRef and put it into <ng-contaner> somewhere — it keeps track of its original context and change detection in original component will also update the value in the template. However this only propagates into one direction, if you do the same action INSIDE that template — the value gets updated but change detection is only triggered down the line, not up (which is, if it is used in a nested component it works, but if it is thrown up and used there — change detection does not work for the original template location). It makes change detection difficult for popup/alert type of functionality.

## Expected behavior

Change detection should work in both directions, templateref should keep track not of only the context, but also of changedetector and trigger check if user action triggered changes happen.

It should be fairly easy to understand from the stackblitz below, much easier than from my words!

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-euxblv

## What is the motivation / use case for changing the behavior?

Developing popup/alert/hint/dropdown in a portal functionality, where template is defined in one place and then used in some portal host up the tree requires us to be able to tell if any change has happened in the template and original location of the template should know about that.

## Environment

<pre><code>
Angular version: 5.2.8

Browser:
- ALL
</code></pre>

**Comment by mlc-mlapis** [comment]
@waterplea ... but because `HelloComponent` has no `@Input()` then using `OnPush` on it means that there is nothing what could invoke CD ... but if `ngDoCheck()` with console printing hook is added to `HelloComponent` then it is seen that it is running.

**Comment by IgorMinar** [comment]
@mlc-mlapis's response is correct. thanks @mlc-mlapis!

**Comment by waterplea** [comment]
I see now, I though change detection OnPush does not travel up through OnPush components when action is performed in a nested one, that's why I thought it was something special with the template usage. That means with templateRef only keeping reference it its original nativeElement location, it is very difficult to use templateRef in any place other than a nested component then, for there is no way to tell where you should run change detection on any template action. Or I might be missing something, need to read up on OnPush more.

**Comment by mlc-mlapis** [comment]
@waterplea ... I think that the basic idea still origins at the fact that CD runs from the top to the bottom. 

Then any extra combinations have to be controlled by your code ... probably using `ngDoCheck()` hook + some shared state.

**Comment by waterplea** [comment]
@mlc-mlapis Well, since template keeps track of the context, it would also be nice if it keept track of that context's change detector also, otherwise that context can realistically be only used for viewing...

**Comment by waterplea** [comment]
Just in case, what I ended up doing was create a directive:

    <ng-template myDirective>
      Content
    </ng-template>

And in that directive I inject `TemplateRef` and `ChangeDetectorRef`. This way instead of giving `TemplateRef` to where I needed that template, I give `ViewChild(MyDirective)` and use `myDirective.template` as template and call `markForCheck()` on that change detector on `ngAfterViewChecked()` of that component.
