### ISSUE TITLE
Safari 9.0 | 404 errors on all files in rxjs folder

### ISSUE THREAD

**Issue by TimHawkHodg** [angular/angular#23572]
## I'm submitting a...<pre><code>[x] Bug report</code></pre>

Note: I originally posted this [question on rxjs github](https://github.com/ReactiveX/rxjs/issues/3541) but they instructed me to come here.

**Code to reproduce:**
Open Apple simulator using iOS 9 or simply open safari browser version 9.0

ng new PROJECT-NAME
cd PROJECT-NAME
ng serve

app.component.ts

```
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/timer';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app works!';

  constructor() {
    Observable.timer(100).subscribe(x => {
      console.log('This will never log');
    });
  }
}
```

https://user-images.githubusercontent.com/32336115/38568140-e69edcbc-3cb5-11e8-8494-98d788daf7ae.png

**Expected behavior:**
Statement to be logged

**Actual behavior:**
Statement never logged. 404 errors on rxjs observables

**Additional information:**
For the current project I am working on I am getting 404 errors on nearly all the files in node_modules > rxjs folder. This only occurs in safari version 9. Adding an import statement to the path of the missing files, as suggested in the README, does not seem to help. Also there are over 80+ 404 errors so it would not be ideal to add an import statement for each missing file in every component.

Any idea on how I can resolve this?

## What is the motivation / use case for changing the behavior?
To be able to use our application in Safari 9.0

## Environment

<pre><code>
Angular version: 5.2.9
RxJS version: 5.5.8

Browser:
- [x] Safari (desktop) version 9.0

**Comment by IgorMinar** [comment]
the 404 errors seem to be for the source maps only. is that right? that would explain why it's coming from one browser only. what's odd is that the browser seems to be pulling in individual source maps files, even though you seem to be using cli which bundles everything.

can you provide us with a better reproduction of the problem? do you see this problem with a freshly created cli project?

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
