### ISSUE TITLE
Angular doesn't work on IE 11.0.9 but works on IE 11.2

### ISSUE THREAD

**Issue by owlstack** [angular/angular#23587]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Client is reporting that Angular web application does not work/does not load on IE 11.0.9600.18697 

## Expected behavior
Angular web application should work on IE 11.0.9600.18697 

## Minimal reproduction of the problem with instructions
Deploy Angular app and use IE 11.0.9600.18697 to see the issue. 

## What is the motivation / use case for changing the behavior?
Client is using IE 11.0.9600.18697 and we can't ask them to upgrade all their machines to latest IE11 version to use the app. Currently, we tested ourselve and it works on IE 11.2

## Environment

<pre><code>
Angular CLI: 1.7.3
Node: 8.9.4
Angular: 5.2.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X ] IE version 11.0.9
- [ ] Edge version XX
 
</code></pre>

Possibly relevant: 
Polyfills.ts file: 
```

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
 import 'core-js/es6/object';
 import 'core-js/es6/function';
 import 'core-js/es6/parse-int';
 import 'core-js/es6/parse-float';
 import 'core-js/es6/number';
 import 'core-js/es6/math';
 import 'core-js/es6/string';
 import 'core-js/es6/date';
 import 'core-js/es6/array';
 import 'core-js/es6/regexp';
 import 'core-js/es6/map';
 import 'core-js/es6/weak-map';
 import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
 import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following for the Reflect API. */
 import 'core-js/es6/reflect';


/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect';


/**
 * Required to support Web Animations `@angular/platform-browser/animations`.
 * Needed for: All but Chrome, Firefox and Opera. http://caniuse.com/#feat=web-animation
 **/
 import 'web-animations-js';  // Run `npm install --save web-animations-js`.

/**
 * By default, zone.js will patch all possible macroTask and DomEvents
 * user can disable parts of macroTask/DomEvents patch by setting following flags
 */

  (window as any).__Zone_disable_requestAnimationFrame = true; // disable patch requestAnimationFrame
  (window as any).__Zone_disable_on_property = true; // disable patch onProperty such as onclick
  (window as any).__zone_symbol__BLACK_LISTED_EVENTS = ['scroll', 'mousemove']; // disable patch specified eventNames

 /*
 * in IE/Edge developer tools, the addEventListener will also be wrapped by zone.js
 * with the following flag, it will bypass `zone.js` patch for IE/Edge
 */
 (window as any).__Zone_enable_cross_context_check = true;

/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.



/***************************************************************************************************
 * APPLICATION IMPORTS
 */

```

**Comment by mlc-mlapis** [comment]
@owlstack ... lol, it is about several hours of work as minimum and the result still very problematic. It is really necessary to add some concrete debug information for the simplest case as possible.

> Deploy Angular app and use IE 11.0.9600.18697 to see the issue.

**Comment by owlstack** [comment]
I can't share current client project but I'm asking if you can test with hello world angular app on that version. Also, could you find that version to install or is it hard to come by? Unfortunately, I only have access to 11.2 but remote client has 11.0.96. I can provide you with hello world angular app if you don't have one already and set the polyfills? I mean idk if that helps or should I assume you already have access to basic hello world angular app?

**Comment by ocombe** [comment]
The error message for what's causing the failure would help a lot.

**Comment by owlstack** [comment]
Sorry for the trouble but it seems the issue is related to compatibility mode in IE 11. If that option is checked, then the angular app doesn't work. If it's unchecked, it works. Not sure if we should close this bug or should it be open in the sense that angular web app should still work in compatibility mode?

**Comment by spock123** [comment]
@owlstack  from Wikipedia:

> .... "Compatibility View" is a compatibility mode feature of the web browser Internet Explorer in version 8 and later. When active, Compatibility View forces IE to display the webpage in Quirks mode as if the page were being viewed in IE7

Angular is not compatible with Explorer 7, which is why it fails in compatibility mode.

**Comment by owlstack** [comment]
Thanks for the explanation @spock123 and @mlc-mlapis! I will close this ticket now. Thanks :)
