### ISSUE TITLE
Angular Universal - Switches to client side rendered page before its full rendered, when using webpack import

### ISSUE THREAD

**Issue by mkhurramali** [angular/angular#23588]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using webpack dynamic imports, the client side page is rendered before the code that depends on the import is executed. This causes the page to flicker and gives a bad user experience.

## Expected behavior

I would like to be able to tell Angular that I am not done with rendering the page yet.

## Minimal reproduction of the problem with instructions

Sample code that produces the issue. This code is placed in ``ngOnInit``:

```
import( /* webpackChunkName: "dynamic-imported-module" */ 'MyDataClass' )
.then( function ( MyDataClass ) {
  // Any code here will execute after client side page is rendered and visible.
});
```

This solution did not work for me:

```
const t = Zone.current.scheduleMacroTask ( 'reference', () => {}, {}, () => {}, () => {} );

import( /* webpackChunkName: "dynamic-imported-module" */ 'MyDataClass' )
.then( function ( MyDataClass ) {
  // Any code here will execute after client side page is rendered and visible.

  // I am now done with rendering of page.
  t.invoke();
});
```

## What is the motivation / use case for changing the behavior?

Using dynamic imports to reduce overall code that is downloaded.

## Environment

<pre><code>
Angular version: 5.2.10

Browser:
- [ X ] Chrome (desktop) version 66
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.10.3  
- Platform: Windows 10 

Others:

</code></pre>

**Comment by vikerman** [comment]
Hi - You can provide a custom APP_INITIALIZER that doesn't resolve till the dynamic imports are loaded (It would be up to you to set this up). Angular on the client side will wait for the promise returned by APP_INITIALIZER to resolve before swapping in the client rendered view over the server rendered view - Thereby avoiding the flicker. https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/core/test/application_init_spec.ts#L43 for example of using async app initializers.
