### ISSUE TITLE
Material Menu Accessibility -- Narrator should list menu position

### ISSUE THREAD

**Issue by djpmsft** [angular/angular#23583]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using a mat-menu, the narrator does not list a mat-menu-item's position within the menu (ie menu item 2 of 4).

## Expected behavior

The narrator should list the menu item

## What is the motivation / use case for changing the behavior?

This greatly helps a visually impaired user's experience navigating throughout a product. 

## Environment

<pre><code>
Angular version: 5.1.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 6.11.2 
- Platform:  

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
Should be opened in https://github.com/angular/material2 following this repository issue submission guidelines.
