### ISSUE TITLE
request for yarn docs-watch to see changes to navigation.json

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#23582]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[X ] Other... Please describe: Feature request for build tools, not for Angular or AIO site themselves
</code></pre>

## Current behavior

When I make a change to navigation.json locally, I have to stop and start yarn docs-watch and refresh my browser (localhost:4200) before I can see the change. 

## Expected behavior

It would be nice yarn docs-watch could see changes to navigation.json and reload navigation on-the-fly the way it handles changes to .md files. 

## Minimal reproduction of the problem with instructions

1. yarn start
2. yarn docs-watch
3. look at docs in browser localhost:4200
4. change navigation.json
5. look at docs in browser localhost:4200. navigation has not changed

## What is the motivation / use case for changing the behavior?

Improve work efficiency and reduce wait time when making navigation changes. Make on-the-fly collaboration and testing more efficient. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
@jbogarthyde @chembu @brandonroberts @dennispbrown FYI.

**Comment by petebacondarwin** [comment]
@jenniferfell I have a fix for this here: https://github.com/angular/angular/pull/23698
