### ISSUE TITLE
Treeshakable provider - missing docs on how to create factories that inject other dependencies

### ISSUE THREAD

**Issue by manfredsteyer** [angular/angular#23592]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Treeshakable providers using ``useClass`` don't work without a ``deps``-array.

Example:

```typescript
@Injectable({
  providedIn: 'root',
  useClass: DefaultHeroService,
  deps: [HttpClient, MessageService ]
})
export abstract class HeroService { }
```

## Expected behavior
A treeshakable provider using ``useClass`` should work without a ``deps``-array.

## Minimal reproduction of the problem with instructions
1. Open https://stackblitz.com/edit/angular-yxr5ny?file=src%2Fapp%2Fhero.service.ts
2. See that it works
3. Open the file hero.service.ts and comment out the deps-array
4. You'll see that it doesn't work anymore

## What is the motivation / use case for changing the behavior?

Meeting the expected behavior

## Environment

<pre><code>
Angular version: 6.0.0-rc.6

Browser:
- [ x ] Chrome (desktop) version Version 66.0.3359.139 (64-Bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: Stackblitz online and Node 9.11.1 on premise
- Platform:  Stackblitz online and Windows 10 on premise

</code></pre>

**Comment by IgorMinar** [comment]
This feature is intentionally missing because it would break tree-shaking. Instead you should use the `inject` function to retrieve the dependencies and inject them into constructors.

**Comment by IgorMinar** [comment]
Here is an example: https://github.com/angular/angular/blob/b64a276d4b34c23a8d882e7bca5f306d2b6775c1/packages/core/test/render3/compiler_canonical/injection_spec.ts#L176

I believe that this info is missing from our DI docs. Would you mind sending us a PR that adds this info to https://next.angular.io/guide/dependency-injection (https://github.com/angular/angular/blob/master/aio/content/guide/dependency-injection.md).

cc: @jenniferfell

**Comment by manfredsteyer** [comment]
@IgorMinar do we really speak about the same?

I think you meant sth like this (taken from the docs):

```typescript
const TOKEN = 
  new InjectionToken('tree-shakeable token', 
    { providedIn: 'root', factory: () => 
        new AppConfig(inject(Parameter1), inject(Paremeter2)), });
```

As you say, using useClass here would prevent tree shaking, hence it was removed some weeks ago as I saw in the checkins.

What I'm talking about is this case: 

```typescript
@Injectable({
  providedIn: 'root',
  useClass: DefaultHeroService,
  deps: [HttpClient, MessageService ]
})
export abstract class HeroService { }
```

Do we have the same situation (preventing tree shaking) here?

**Comment by trotyl** [comment]
If you want to have `useClass` without deps, like:

```typescript 
@Injectable({
  providedIn: 'root',
  useClass: DefaultHeroService,
})
export abstract class HeroService { }
```

Then you **MUST** also add `Injectable()` decorator on `DefaultHeroService` like:

```typescript
@Injectable()
export class DefaultHeroService {
  constructor(http: HttpCIient, message: MessageService) {}
}
```

Then it comes the old API again.

**Comment by manfredsteyer** [comment]
@trotyl Thanks for this hint. I've tried it out but this issue still occours with Injectable. To reproduce it, you can follow those steps:

1. Open https://stackblitz.com/edit/angular-yxr5ny?file=src%2Fapp%2Fdefault-hero.service.ts
2. App is executed correctly
3. Remove deps-Array
4. App crashes and the console shows that the dependencies are not injects (but undefined instead)

**Comment by trotyl** [comment]
Then why not just use the class itself as default implementation?

**Comment by jenniferfell** [comment]
@chembu There might be an opportunity to improve the docs. Please keep this on your radar as we look at tree-shaking docs backlog. Thanks!

**Comment by JoostK** [comment]
This is working correctly in Ivy.
