### ISSUE TITLE
Error due to reference to inexistant sourcemap in ngsw-worker.js

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular#23596]
### Versions
```
cli v6.0.0-rc
angular v6.0.0-rc.5
```

### Repro steps
* `npm install @angular/cli@next -g`
* `ng new helloworld`
* `cd helloworld`
* `ng g service-worker --project helloworld`
* `ng build --prod`

### Observed behavior
`ngsw-worker.js` contains a reference to a sourcemap:
`//# sourceMappingURL=ngsw_worker.es6.js.map`
but the sourcemap file doesn't not exist in distribution files (and should not, as this file is for prod), and as the CLI just copy `ngsw-worker.js` as is, then it produces a message in browser console.

### Desired behavior
No reference to sourcemap in `ngsw-worker.js`.

**Comment by cyrilletuzi** [comment]
Due to the [bazel build](https://github.com/angular/angular/blob/master/packages/service-worker/BUILD.bazel#L29) just copying a dev generated file as is.

**Comment by IgorMinar** [comment]
good catch. thanks.

**Comment by varshag91** [comment]
What should i do to avoid this error

**Comment by lehno** [comment]
Any news on that? same error here

**Comment by vytautas-pranskunas-** [comment]
Any news?

**Comment by ErmakovSY** [comment]
To avoid this errors I had generared sourcemap of ngsw_worke.js manually (with Gulp), named it "ngsw_worker.es6.js.map" and placed to dist/browser directory. Of course, this is temporary issue, but I haven't another one.

**Comment by peterpeterparker** [comment]
I like the fact that even the Angular Material website itself face that small bug ;)

For example opening the debugger console of https://material.angular.io/components/menu/overview will display the same warning
