### ISSUE TITLE
Feature Request: export NoopNgZone as @angular/core at top level

### ISSUE THREAD

**Issue by sandangel** [angular/angular#23594]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior

I need to create some tests for [PushPipe](https://stackblitz.com/edit/angular-no-zones?file=main.ts) to run in `ngZone: 'noop'` environment. So I want to disable zone for a particular test suite. 

I have found there is a NoopNgZone class in `@angular/core/src/zone/ng_zone` but it was not exported at top level. 

When I try to import NoopNgZone from there, the test fail with error: 

`Error: Cannot find module '@angular/core/src/zone/ng_zone'`

## Expected behavior

NoopNgZone should be provided at top level import like this: 

`import {NoopNgZone} from '@angular/core'`

## What is the motivation / use case for changing the behavior?

Can disable zone for particular test suite is really helpful because user don't have to opt-out zone in global test environment.

## Environment

<pre><code>
Angular version: 6.0.0-rc.6

 
For Tooling issues:
- Node version: 8.11.1  
- Platform:  All

Others:

</code></pre>

**Comment by lacolaco** [comment]
Did you try to use `ComponentFixtureNoNgZone`? It may be what you want.

```
TestBed.configureCompiler({
      providers: [
        {provide: ComponentFixtureNoNgZone, useValue: true},
      ]
    });
```

**Comment by sandangel** [comment]
@lacolaco wow, that's really help. Are you in Japan? I really want to join your team. Awesome. Thank you so much.

**Comment by sandangel** [comment]
hi @lacolaco , I have found this [test](https://github.com/angular/angular/blob/master/packages/core/test/application_ref_spec.ts#L369-L374) in the angular source code. They config ComponentFixtureNoNgZone in configureTestingModule, not configureCompiler. Can you review that?

**Comment by lacolaco** [comment]
@sandangel Both can add providers to TestBed injector.  configureTestingModule does all config. configureCompiler does only about compiler (=injector).

**Comment by sandangel** [comment]
@lacolaco thanks for clarifying, I really appreciate it. Looking forward to hearing your speech at ng-japan ^^

**Comment by sandangel** [comment]
reopen because I found this still useful when user want to disable zone in particular Components or Modules which have heavy computation logics.
