### ISSUE TITLE
How to upload a file from local System, without using form

### ISSUE THREAD

**Issue by swapnil14** [angular/angular#23604]
I am developing my app in angular 4.
I want to upload a file having path C:\Users\user\Download\untitled.indd to server without using form.
When i will click on given button, I have  to upload this file to server.

**Comment by AdnanSalah84** [comment]
@swapnil14  
None of us understand!

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
