### ISSUE TITLE
include cldr time units data into locales

### ISSUE THREAD

**Issue by elvisbegovic** [angular/angular#23607]
## I'm submitting a...
[x] Feature request

## Current behavior
Nowadays app largely uses : 

> "a minute ago" 

> "a few seconds"

A developer can easily create a directive or a pipe to cover this instead of using 3rd party lib like [momentjs](https://momentjs.com/docs/#/durations/) or [date-fns](https://date-fns.org/docs/distanceInWords). But problem resides with locales, he would need to handle them himself.

Indeed as we can see  [here](https://github.com/angular/angular/blob/6.0.0-rc.6/packages/common/locales/extra/en.ts) Angular is not extracting durations units from cldr so we can't use them.
The extraction tool is already downloading [those data](https://github.com/angular/angular/blob/master/tools/gulp-tasks/cldr/cldr-urls.json) (last url) but discard them. So it shouldn't be hard to make them part of the locales.

## Expected behavior
Add [duration units](https://github.com/unicode-cldr/cldr-units-full/blob/master/main/en/units.json#L191-L252) to the locale extra data.

## What is the motivation?
We currently have to depend/use 3rd party libs (non friendly tree-shakable) to cover a common used feature.

## Others:
Is a PR welcome ?

**Comment by petebacondarwin** [comment]
Closing as this feature request does not appear to have much interest. The feature would result in further bloating of the locale files, and can be achieved, somewhat, via 3rd party code.
