### ISSUE TITLE
Changelog v6.0.0-rc.6 missing

### ISSUE THREAD

**Issue by kvanzuijlen** [angular/angular#23602]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The changelog wasn't updated for the 6th release candidate.

## Expected behavior
Documented changes of Angular 6.0.0-rc.6

## Environment

<pre><code>
Angular version: 6.0.0-rc.6

</code></pre>

**Comment by spock123** [comment]
Weee, didn't realize there was a new version out - thanks :)

**Comment by jcompagner** [comment]
https://github.com/angular/angular/blob/6.0.x/CHANGELOG.md

**Comment by larssn** [comment]
Think you can close this

**Comment by sarunint** [comment]
But shouldn't commit https://github.com/angular/angular/commit/4008e36e806f31f7c0e39810aa35242739b5a502 be cherry-picked into the master branch?

**Comment by ocombe** [comment]
Thanks for reporting this, it's fixed
