### ISSUE TITLE
HttpClient#put with `observe: events` and generic as return type doesn't take in `reportProgress: true`

### ISSUE THREAD

**Issue by diagramatics** [angular/angular#23600]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Consider this:
```ts
this.http.put<{}>('endpoint', {}, {
  reportProgress: true,
  observe: 'events',
});

this.http.put<{}>('endpoint', {}, {
  reportProgress: true,
});
```

Basically, the top `HttpClient#put` call doesn't compile in TS from a non-matching override function definition. Bottom does.

According to: https://github.com/angular/angular/blob/master/tools/public_api_guard/common/http.d.ts#L1163-L1170

There's no way to specify `reportProgress: true` when you're using a generic type to specify the return type for `HttpClient#put` and the configuration `observe: 'events'` to exist. Compare this to:

https://github.com/angular/angular/blob/master/tools/public_api_guard/common/http.d.ts#L1183-L1194

Where there is the definition for it if you're not returning a generic type as a part of `HttpEvent`.

## Expected behavior

Supposedly you add `reportProgress?: boolean` into the override definition? Can definitely make a quick PR if this is the case.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-gitter-nsqoef?file=app%2Fapp.component.ts shows the TS compile error.

## What is the motivation / use case for changing the behavior?

Well, type correctness? I don't think that type of PUT request wasn't supported. I assume like every other methods, they are small wrappers to create an `HttpRequest` for `HttpClient#request`, which handles `reportProgress` and `observe: events` the same for any types of requests.

## Environment

Considering the code is still in `master`, I'm assuming all versions of Angular to this date and all versions of TypeScript.

**Comment by mistic100** [comment]
This is a blocker.

**Comment by alxhub** [comment]
Yep, this looks like an oversight - `reportProgress` is missing from this signature: https://github.com/angular/angular/blob/bd7393fc6810f3cd2e7e347ba9183ab3dde746a8/packages/common/http/src/client.ts#L2449-L2453

Seems like a great opportunity for a community fix!
