### ISSUE TITLE
ES6 and FormsModule cause EDGE browser to error with "This page is having a problem loading", or crash. 

### ISSUE THREAD

**Issue by chrisbu** [angular/angular#23610]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

ES6 and FormsModule cause EDGE browser to display message:

> This page is having a problem loading
> We tried to load this page for you a few times, but there is still a problem with this site. We know you have better things to do than to watch this page reload over and over again so try coming back to this page later.

F12 devtools also close without revealing any useful message as the page is reloaded several times.

Occasionally it will also cause Edge to actually crash, leaving an error in the windows event log, eg:
> Faulting application name: MicrosoftEdgeCP.exe, version: 11.0.16299.371, time stamp: 0x5abdadc7
> Faulting module name: KERNELBASE.dll, version: 10.0.16299.371, time stamp: 0x6369e29f

## Expected behavior
To work.  This works in Chrome, Opera etc...

## Minimal reproduction of the problem with instructions

1. Create new angular app `ng new edgetest`
1.1 `ng serve` and browse with Edge to confirm it works ok
2. edit **tsconfig.ts**, change `"target":"es5"` to `"target": "es6"`
3. edit **app.module.ts** to include FormsModule import, adding the following lines:
`import { FormsModule } from '@angular/forms';`
`// snip...`
`imports: [BrowserModule, FormsModule]`
`// snip rest of file...`
4. `ng serve`  and browse with Edge - the page does not load, instead, showing the message noted above.

## What is the motivation / use case for changing the behavior?
Wanted to target ES6

## Environment
Windows 10

<pre><code>
Angular version: 5.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [X ] Edge version 41.16299.371.0
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by splincode** [comment]
EDGE does not fully support ES6.

**Comment by IgorMinar** [comment]
Please ensure that you transpile all the code to es5. Angular CLI does that by default.
