### ISSUE TITLE
Angular Compiler don't return type error

### ISSUE THREAD

**Issue by Shockolino** [angular/angular#23612]
## I'm submitting a...

<pre>

Accessing an undeclared member don't return type error, the angular doc is wrong (section Template Syntax --> The $any type cast function)
<div>
  The hero's marker is {{$any(hero).marker}}
</div>

<code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [X] Chrome (desktop) version lastest
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by robwormald** [comment]
The point of `$any` is to ignore undeclared members. This is works as intended.

**Comment by Shockolino** [comment]
Yes but without $any work fine, the doc say that without $any there is a error, but don't error will be showInviato dal mio dispositivo Huawei-------- Messaggio originale --------Oggetto: Re: [angular/angular] Angular Compiler don't return type error (#23612)Da: Rob Wormald A: angular/angular CC: Shockolino <87shock@libero.it>,Author The point of $any is to ignore undeclared members. This is works as intended.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/angular/angular","title":"angular/angular","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/angular/angular"}},"updates":{"snippets":[{"icon":"PERSON","message":"@robwormald in #23612: The point of `$any` is to ignore undeclared members. This is works as intended."}],"action":{"name":"View Issue","url":"https://github.com/angular/angular/issues/23612#issuecomment-385490857"}}}
