### ISSUE TITLE
Tree Shakable Providers and InjectionToken: inject() does not work with abstract classes

### ISSUE THREAD

**Issue by manfredsteyer** [angular/angular#23611]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

You cannot use the new inject with abstract classes, as it expects an InjectionToken or a Type which is defined as "new-able":

```typescript
export const DEMMO_SERVICE = new InjectionToken<DemoService>('DEMO_SERVICE', {
  providedIn: 'root',
  // this doesn't work as HeroService is abstract
  factory: () => new DemoService(inject(HeroService))
})
```

## Expected behavior

It should be possible to use inject with abstract classes.

Sidenote: inject from @angular/core/testing uses any instead and this includes abstract classes too.

## Minimal reproduction of the problem with instructions

Please see comments in 
https://stackblitz.com/edit/angular-yxr5ny-foth3r?file=src%2Fapp%2Fapp.tokens.ts

## What is the motivation / use case for changing the behavior?

- API symmetrie
- going with the principle of the least surprise
- the current behavior could be a show stopper in some situations

## Environment

<pre><code>
Angular version: 6.0.0-rc.6
Tested with Stackblitz (see above)
</code></pre>

**Comment by trotyl** [comment]
Relates to https://github.com/Microsoft/TypeScript/issues/17572, there's no way to type-check an abstract class.

**Comment by manfredsteyer** [comment]
Yes, but we could go with any. I know, this is not a pretty solution but it fits to Angular b/c a token can technically be of any type (also see https://angular.io/api/core/Inject).

**Comment by manfredsteyer** [comment]
I see. That means, we have two options.
1. Beeing too restrictive which means we cannot use abstract classes
2. Beeing too tolerant which means the type system allows abstract classes but also other things we are not happy with

None of them is perfect. But when we consider that it is very common to use abstract classes as tokens, I think option 2 is the better one. Also, there are many cases where Angular follows this pattern and it was possible in the past, which means that option 1 would break things we are used to.

**Comment by trotyl** [comment]
> it was possible in the past

Not since v4, it already won't work in current `Injector` API if you don't ignore the deprecated warning.

https://github.com/angular/angular/blob/8062f7de9eb671b527b5eceba5a8a63be8054a44/packages/core/src/di/injector.ts#L74-L79

Whatever deprecated in v4 should be removed in v6.

So this request is **NOT** about the new `inject()` method introduced.

**Comment by manfredsteyer** [comment]
I see. Thanks for pointing this out. Frankly, this is not ideal, since using abstract base types for such things is in general considert good design.

**Comment by rgant** [comment]
Trying to resolve my [difficulties with OnPush](angular/angular/issues/12313) change detection in unit tests and I needed to get the ChangeDetectorRef of my Component to trigger change detection. But that caused these warnings because ChangeDetectorRef is an abstract class.

**Comment by trotyl** [comment]
> Trying to resolve my difficulties with OnPush change detection in unit tests and I needed to get the ChangeDetectorRef of my Component to trigger change detection.

@rgant That's https://github.com/angular/angular/issues/29905, you don't use this `inject()` API in testing.

**Comment by Springrbua** [comment]
We just enabled the "deprecation"-rule of tslint and I noticed a few of them in our app.
I "fixed" them using a cast to `Type`:
`this.injector.get(<Type<HeroService>>HeroService)`

**Comment by JoostK** [comment]
Support for abstract classes as tokens was added in #37958, so closing this as resolved.
