### ISSUE TITLE
Angular 5 not responsive

### ISSUE THREAD

**Issue by juragandotid** [angular/angular#23614]
Angular 5 not responsive please check this video https://drive.google.com/file/d/1W1EDZ0OXsDt8vFd80WZa1-Ry_4IPhflp/view?usp=drivesdk

**Comment by robwormald** [comment]
Closing as you've ignored the issue template, not attached a reproduction, and this is likely unrelated to Angular Core. See https://material.angular.io/components/sidenav/overview#creating-a-responsive-layout-for-mobile-amp-desktop
