### ISSUE TITLE
Stray change log file in aio guide directory but not in navigation

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#23615]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The following change log is part of the stable (v5.x) release of docs, but it isn't in the navigation/TOC, and we don't seem to link to it. https://angular.io/guide/change-log

It's the 3rd hit on Google search for "Angular change log."

It's also pretty  out-of-date, with the most recent entry being March 2017.

Looks like the intent was for this to be a docs-specific change log. 

## Expected behavior

Either of these:

* Delete it. Remove this file from guides. Consider replacing with a redirect to https://github.com/angular/angular/blob/master/CHANGELOG.md so anyone who bookmarked this old change log is appropriated directed to the new change log. Include both code and doc changes in that single change log. 

* Make it current and useful. Keep this file, make it current, include a link to the code change log, and put it in master/CHANGELOG-DOCS.md or add it to the navigation under Keeping Up-to-Date as "Recent documentation changes". If we do that, we might also consider putting the code change log in the navigation at that location. 

## Minimal reproduction of the problem with instructions

3 ways to find this file:
* Google for "Angular change log" and see 3rd entry.
* Within aio, search for "change log" "update" or "current".
* Go directly to https://angular.io/guide/change-log

## What is the motivation / use case for changing the behavior?

Knowing what's new and changed in the docs is useful. Something like this could be good. 

This file is out-of-date, it's only about doc changes, and it's showing up prominently in search which is making it harder for users to find the right docs about Angular updates and changes. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
@IgorMinar @StephenFluin Love to talk to you both about this one. I think either we should fold doc changes into changelog.md, or we should do something more parallel across the two (either both as must .md or both in guides and available from the nav under Keeping Up-to-Date.

**Comment by petebacondarwin** [comment]
IMO the `guide/changel-log` is obsolete and confusing. We should delete it.

**Comment by jenniferfell** [comment]
PR with starter updates: https://github.com/angular/angular/pull/26102

**Comment by JoostK** [comment]
Since the stray changelog has since been deleted in #26102 the remaining proposal to provide insight into docs changes duplicates #17409, so I'm closing this one.
