### ISSUE TITLE
Angular rc versions

### ISSUE THREAD

**Issue by BzenkoSergey** [angular/angular#23619]
Milestone "v6-candidates" is not completed. 
Will we have a new angular 6.0.0-rc.6 version?

https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md
Release Schedule table is not informative for now.

Can you provide any information about the updates?

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/23602 and https://github.com/angular/angular/issues/23505

**Comment by robwormald** [comment]
We'll ship V6 when we're happy that users will have a great experience. Won't be long now.
