### ISSUE TITLE
Add information for when not to use tree-shakable injector format

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#23621]
## I'm submitting a...

[X] Documentation issue or request

## Current behavior
https://next.angular.io/guide/dependency-injection#create-an-injectable-heroservice

## Expected behavior
We need to find a way to help people know that they can't use this new format if they are overriding a token. They must use the `provides: []` syntax (which is not tree shakable) to do this.

**Comment by jenniferfell** [comment]
See https://github.com/angular/angular/pull/23634

**Comment by kapunahelewong** [comment]
Closing as this was fixed in https://github.com/angular/angular/pull/23634. @StephenFluin please feel free to reopen and tag me if there are further items to include.
