### ISSUE TITLE
Author's Style Guide needs clean-up and better navigation

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#23626]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The Authors Style Guide is here https://angular.io/guide/docs-style-guide

1. It's not easy to find. It's not in the navigation for aio docs (despite being in Guide), nor is is located near other contributor information (despite being for contributors). You can find it via Google search or aio search. 

2. We might want to rename it and/or rename the Angular coding style guide, so it's easier to distinguish them in search results. Perhaps "Angular Documentation Style Guide" to be more in alignment with title of master Google Dev Doc Style Guide. 

3. It opens to an image of a 404 error, which is confusing. Without any #anchor modifier, the page opens to the end of the Live example section, which displays an image of a 404 error. 

4. In some places, it conflicts with the Google Developer Documentation Style Guide https://developers.google.com/style/. We've been told to follow Google style when they conflict, but we should reconfirm the differences and update this doc as appropriate. 

## Expected behavior

My votes:
1. Should be with other contributor information. To keep it simple, remove this from guide and put in https://github.com/angular/angular/tree/master/docs as DOCUMENTATION.md or DOCUMENTATION-STYLE.md. Reference from https://github.com/angular/angular/tree/master/CONTRIBUTING.md. Think of it as the doc contributor parallel to DEVELOP.md for code contributors. 

Alternative: If we want to move all contributor info into Guide in a new navigation section, that would work, but it might not be where github contributors expect to find it. It's also a bit work. 

2. Angular Documentation Style Guide is my preference. Rename the other to Angular Coding Style Guide or something like that for page title, keeping Style Guide as nav title as shorthand. 

3. Fix to open to top of page. This happens automatically when it is removed from aio guides and put in docs. 

4. Update to match and refer to GDDSG. 

## What is the motivation / use case for changing the behavior?

Make it easier to find for those who need it. 
Make it accurate for those who use it. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
docarea=contributorsupport

**Comment by gkalpak** [comment]
The automatic scrolling and 404 are indeed unexpected. I will look into that.

##
Regarding making it more visible and "discoverable" by contributors, I just wanted to point out that this was (I guess) primarily intended for members of the docs authoring team and might seem intimidating/discouraging for the occasional contributor that just wants to fix a typo.

The barrier of entry is already a little too high for docs contributions - even for very simple fixes. If anything, we should avoid changes that would raise the barrier or potentially discourage people.

m2c

**Comment by jenniferfell** [comment]
Thanks for looking into the scrolling.

Re making it more visible: I agree wrto the primary audience, but I see no harm in making it available in an obvious location to contributors. Then they won't be as surprised if someone asks them to follow a certain convention for filename, page title, image format, or inclusion of example code...or at least we'll have a place to refer them for more info if we ask them for a change to meet our style.

**Comment by gkalpak** [comment]
BTW, here is the fix for scrolling/404: #23637

**Comment by aikidave** [comment]
The documentation style guide is now part of our Content Contributors Guide. It's now much easier to find. While we could probably refresh the topic, I think the current state is sufficient for the time being. Closing this issue.
