### ISSUE TITLE
Elements guide is missing an intro paragraph clarifying the relationship to custom elements

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#23627]
https://next.angular.io/guide/elements

The page title is "Angular Elements Overview" but nowhere at the beginning we have a section that clarifies the relationship between Angular Elements and custom elements.

Maybe we should start with something like "Angular Elements are Angular components packaged as custom elements, a web standard for defining new html elements in a framework-agnostic way..."

**Comment by manughub** [comment]
Associated PR #23638  closed. Closing the issue.
