### ISSUE TITLE
Stackblitz issue with absolute paths

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#23620]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

There is an issue with the StackBlitz integration with our V6 examples on angular.io. With the V5 examples, we can use absolute paths, specifically for lazy loading modules with the router, but in V6 examples are broken because an error occurs where we use those absolute paths that begin with "app". 

Here are examples from the router guide: 

V5 - https://stackblitz.com/angular/omplpnlkrdx
V6 - https://stackblitz.com/angular/aeqnjjrarod

See email from @brandonroberts . Also adding as issue here, so it will appear in searches for potential outstanding v6 work.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
@StephenFluin FYI...for tracking. Thanks for looking into this.

**Comment by EricSimons** [comment]
Looks like this was a compat issue on our end with the new angular.json- just deployed fix to prod. Lmk if all looks well on your end!

**Comment by StephenFluin** [comment]
@jenniferfell I don't see any paths beginning with `app`, can you verify this is fixed?

**Comment by EricSimons** [comment]
@StephenFluin it looks like they're in this file, starting line 11: https://stackblitz.com/angular/aeqnjjrarod?file=src%2Fapp%2Fapp-routing.module.ts

**Comment by brandonroberts** [comment]
@StephenFluin @jenniferfell I verified that the examples are working correctly now. Thanks @EricSimons for the help!
