### ISSUE TITLE
Services folders

### ISSUE THREAD

**Issue by RodRitter** [angular/angular#23622]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Expected behavior

I hope the format of my feature request is correct. I'm really new to Angular so I apologize if this is obviously not useful. 

I would like to know if it's possible to seperate Services into their own folder, separate from the app component bits and pieces. Something like this:
```
[src]
- [app]
--- [services]
----- [cool-service]
------- cool.service.ts
------- cool.service.spec.ts
--- app.component.css
--- app.component.ts
--- app.mopdule.ts
...
```

## What is the motivation / use case for changing the behavior?

The problem is with a lot of services, it becomes difficult to find what you want immediately.

## Environment

<pre><code>
Angular version: 5.2.10
</code></pre>

**Comment by jotatoledo** [comment]
The first question is, what makes you think that doing so is *not* possible atm?

**Comment by jnizet** [comment]
if the question is how to generate the files with the CLI, just use

    ng generate service services/cool-service/cool

**Comment by wojo1206** [comment]
Yes, that is possible :)

**Comment by RodRitter** [comment]
Oh man, thats so blind. I didn't know you could do that.
