### ISSUE TITLE
Add support for Shadow DOM V1

### ISSUE THREAD

**Issue by robwormald** [angular/angular#23636]
Centralizing discussion on Shadow DOM V1 changeover.

Good explainer documentation on what's changed between v0 -> v1: https://hayato.io/2016/shadowdomv1/

#### `element.createShadowRoot()` => `.attachShadow({ mode: 'open' | 'closed' }) `

This is the big change, currently breaking people using Edge (unexpectedly), as it supports the new Shadow DOM API but not the old. 

#### Proposed Fix:
- Add two new `ViewEncapsulation` enum options: `ShadowDom` and `ClosedShadowDom` (name to be bikeshedded) - doing this rather than changing the behavior of `ViewEncapsulation.Native` means we can do this as a feature release rather than a breaking change. `ViewEncapsulation.Native` should be deprecated.

#### `Shadow DOM emulation / ViewEncapsulation.Emulated`: 

Currently the Emulated view encapsulation is based on the V0 semantics.

#### Proposed Fix:
We should update the emulation of Shadow DOM via Shadow CSS to match the V1 semantics - we currently use an (old) version of the ShadowCSS polyfill from @webcomponents - https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/compiler/src/shadow_css.ts.

Additionally, we should consider allowing developers to *polyfill* Shadow DOM at runtime via the Shadow DOM polyfill at https://www.webcomponents.org/polyfills. This would allow developers to author with the expectation of Shadow DOM being available, and fall back via the polyfill, rather than having to author two components etc to support modern and legacy browsers. This polyfill has a non-trivial runtime overhead, but as all major browsers (except Edge ) support it, this may be desirable for some developers.

#### `::content selector` => `::slotted (compound-selector)` 

V1 introduces a new psuedo-selector for styling slotted nodes. This is of course supported natively, but we should work out the correct way to (maybe) emulate this in encapsulated mode, what to do about `ng-deep`, etc.

### Content Projection Changes

`<content>` elements are deprecated, in favor of the new `<slot>` API. `<slot>` has already been added to the schema, so developers are able to use native slot functionality (this is generally only useful in Angular Elements, for now).

#### Proposed Fix:
@pkozlowski-opensource has proposed a new `<ng-slot>` API that would supersede `<ng-content>` - this means aligning with the distribution semantics of the V1 API. This may mean introducing something like `@SlotChild()/@SlotChildren()` decorators and deprecating `@ContentChild()/@ContentChildren()`.

Additionally, we should align the semantics of how our emulated distribution of nodes works against the V1 spec, including default content: https://github.com/angular/angular/issues/12530

Longer term, we should consider if the [part/theme proposal](https://meowni.ca/posts/part-theme-explainer/) covers our developers' use cases, and potentially emulate it at build time for theming? See https://github.com/angular/angular/issues/22515

Related Issues:
https://github.com/angular/angular/issues/11595
https://github.com/angular/angular/issues/2567
https://github.com/angular/angular/issues/7856
https://github.com/angular/angular/pull/19059
https://github.com/angular/angular/issues/3882
https://github.com/angular/angular/issues/12530

**Comment by robwormald** [comment]
The Shadow DOM fix is the most time-critical, as it's confusing for developers - many browsers never supported the V0 API, but now support the V1, which Angular doesn't support.

Chrome has also deprecated v0 - https://www.chromestatus.com/feature/4507242028072960

**Comment by cyrilletuzi** [comment]
Does this mean even Angular Elements still use the ShadowDOM v0? If so, it's a serious issue: as one the goal of Elements is to produce standard web components, it needs to have proper ShadowDOM support.

**Comment by sarunint** [comment]
Is this issue going to be pre-v6 or post-v6 thing?

**Comment by sandangel** [comment]
@robwormald Hi, I have 2 questions:
1/ does this means we should not use Angular Element in production yet until Angular team release a version that compatible with Shadow DOM v1?
2/ The proposed fix with Content Projection seems like a big breaking change, is it possible to update with only 1 command `ng update`?

**Comment by sandangel** [comment]
@trotyl hi, thanks for your answer.
I think different: angular element use Emulated by default, but since we can put it anywhere, is that safer to use ViewEncapsulation.Native instead? In that situation does moving to Shadow V1 introduce some breaking change? (like we have to change to ViewEncapsulation.ShadowDom / ClosedShadowDom).

**Comment by trotyl** [comment]
@sandangel I won't suggest `ViewEncapsulation.Native` for now, given:

+ The emulation process in Angular is mainly compiler-based rather than using runtime polyfills, which has little effect on final size;
+ There're still many browsers supports none of Shadow DOM V0 or V1, eg. IE and Edge;
+ Mixing `Emulated` and `Native` components may sometimes break encapsulation like https://github.com/angular/angular/issues/20449, and 3rd-party libs are not likely to use `Native`.

I'm not sure about the migration path, but all breaking changes for valid API usage should follow the [Angular Deprecation Policy](https://blog.angularjs.org/2016/10/versioning-and-releasing-angular.html#Deprecation_policy_31), providing at least two-major-version deprecation stage.

**Comment by robwormald** [comment]
@trotyl thanks, updated

**Comment by benoitjchevalier** [comment]
Can we hope this makes it into Angular 7? We're building a library of Web Components using Angular Elements and possibly including other Web Components built with other libraries (Polymer), which will be using Shadow Dom. Having v1 Shadow Dom support [and polyfilling Shadow Dom (v1), but that can be done on our side] will probably be a need for us as we won't be able to mix V0 component with V1 components.

Aligning content projection to use slots would also help standardizing the use of our components. I'm also hoping it will make it easier grabbing a ref to another web component that has been projected into an angular element (I'm having a hard time finding a clean way of doing it with @ContentChild right now)

**Comment by njl07** [comment]
Hope we can have a solution soon because `ViewEncapsulation.Native` is broken on `Safari` and my `customElement` doesn’t work on it.

Thanks for your collaboration and your time on this problem.

**Comment by Thilo84** [comment]
I'm also waiting for a working solution for the `ViewEncapsulation.Native`. There is currently no working polyfill for IE.
I would be very happy if this pull request could be merged soon.
Thank you very much for your effort.

**Comment by robwormald** [comment]
Update on this - https://github.com/angular/angular/pull/24718 should fix the root issue (the renderer using the old Shadow DOM API) - it's an opt-in as `ViewEncapsulation.ShadowDom` - note that using the new Shadow DOM API will likely impact styles if you are relying on the old API (that's why it's a new option).

Note that this API (like the existing `Native` option) *requires* Shadow DOM to be available in the browser, and provides no polyfills or benefits for browsers that do not support Shadow DOM (At this writing, Chrome and Safari support v1, Firefox support is [imminent](https://bugzilla.mozilla.org/show_bug.cgi?id=1471947) and Edge's status is [unknown](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6263785-shadow-dom-unprefixed). IE will never support Shadow DOM.

**Comment by schnrap** [comment]
Does this new `ViewEncapsulation.ShadowDom` offer a way to access the host children other than @ContentChildren? Or do we need to wait for a new option like a @SlotChildren for this (like suggested above)?

**Comment by schnrap** [comment]
I got it working this way, perfect!
Thank you very much for your time and help.

**Comment by robwormald** [comment]
implemented in https://github.com/angular/angular/commit/c9844a2f0132c757711a1a1004120ddf058e47f6

**Comment by benoitjchevalier** [comment]
@robwormald with this closed is there any plan to support shadow dom polyfills and in particular css variables in Angular Elements?

**Comment by evanjmg** [comment]
Any update on shadow DOM polyfills?
