### ISSUE TITLE
Add support for min/max number validation in template driven forms.

### ISSUE THREAD

**Issue by westonpace** [angular/angular#23635]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
There is no mechanism for basic number validation (min/max) in template driven forms.

## Expected behavior
`<input type="number" [(ngModel)]="value" [minValue]="minimum" [maxValue]="maximum"/>
`
## What is the motivation / use case for changing the behavior?

Certainly the scope of validation should be pretty limited for Angular.  However, the fact that https://github.com/angular/angular/pull/13688 was implemented seems to suggest that min/max are in this limited scope.  This also would allow Angular to supply validators that at least match the HTML5 spec (sharing motivation with https://github.com/angular/angular/issues/16352 although this need not address that particular issue).  Furthermore, there is some public demand as seen on [StackOverflow](https://stackoverflow.com/questions/39847862/min-max-validator-in-angular-2-final) and this has even been attempted and approved before but the mechanism used was a breaking change that had to be [rolled back](https://github.com/angular/angular/commit/3e685f98c666fcb9f0556ccb65d4b40716ac2985#diff-d60c63de232466b99bc9f5ab2bb39430).

In order to avoid a breaking change it would seem that either custom attributes are used (easy but does not satisfy https://github.com/angular/angular/issues/16352) or the user has to add a particular module (or some other boolean flag) to enable the feature (adds complexity).

## Environment

<pre><code>
Angular version: X.Y.Z
5.2.10

Browser:
- [X] Chrome (desktop) version XX
- [X] Chrome (Android) version XX
- [X] Chrome (iOS) version XX
- [X] Firefox version XX
- [X] Safari (desktop) version XX
- [X] Safari (iOS) version XX
- [X] IE version XX
- [X] Edge version XX
 
For Tooling issues:
- Node version: N/A  
- Platform:  N/A 

Others:

</code></pre>

**Comment by kara** [comment]
The existing issue, #16352, encompasses this min/max validation case, so closing this as a dupe.
