### ISSUE TITLE
Incorrect http Accept header on router preloading of feature areas

### ISSUE THREAD

**Issue by santam85** [angular/angular#23632]
#I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I implemented an application with multiple routes using background preloading of 1st level routes following instructions at https://angular.io/guide/router#preloading-background-loading-of-feature-areas
When requesting the route definitions, the SystemJS module loader does not specifies correct Accept headers:

<pre><code>
Accept: */*
</code></pre>

 On complex configurations, for instance when using Spring MVC 5+, due to a change to a default spring parameter value and the naming pattern of the chunk files (IE name.module.chunk.js), this can lead to html served instead of static resources.

## Expected behavior

I would argue that a more correct Accept header would be:
<pre><code>
Accept: application/javascript, */*
</code></pre>

## Minimal reproduction of the problem with instructions
Create an empty Spring Boot 2 app and have a MVC RequestMapping matching the start of a chunk name that renders a page.

## What is the motivation / use case for changing the behavior?
Allow for complex configurations and avoiding name clashes

## Environment

Angular version: 5.2.7

Others:
Tested on latest Spring Boot (2.0.1-RELEASE)

**Comment by trotyl** [comment]
Not controlled by Angular but your JavaScript bundler, eg. Webpack if you’re using Angular CLI.

**Comment by santam85** [comment]
@trotyl are you sure that is accurate? I am using the angular CLI indeed, but the documentation states:

> Angular provides a built-in module loader that supports SystemJS to load modules asynchronously. If you were using another bundling tool, such as Webpack, you would use the Webpack mechanism for asynchronously loading modules.

If I had to customize this through webpack config, can you give me an indication of how I could override the default Accept header? I couldn't find any reference for this...
