### ISSUE TITLE
Broken layouts (link to this heading) in AIO

### ISSUE THREAD

**Issue by splincode** [angular/angular#23630]
## I'm submitting a...

<pre><code>
[x] Documentation issue or request
</code></pre>

## Current behavior

https://next.angular.io/guide/elements#angular-elements-overview

![image](https://user-images.githubusercontent.com/12021443/39471598-a4897e48-4d4c-11e8-860f-22a44ca61a9e.png)

**Comment by jotatoledo** [comment]
Steps to reproduce? environment? Im not able to see this issue on chrome.

**Comment by splincode** [comment]
Strange, now I can not reproduce either

**Comment by splincode** [comment]
I noticed a mistake if I go directly. And the menu is closed while the error remains
