### ISSUE TITLE
Reusable `Injectable` annotations

### ISSUE THREAD

**Issue by rkirov** [angular/angular#2363]
Already existing angular.dart 1 applications have a number of services that should be reusable in angular2 apps (to aid migration). To achieve that one needs to denote them as Injectable in both

```
@ng1.Injectable()
@ng2.Injectable()
class MyService
```

This has a significant issue that now the service code needs to import both angular1 and angular2 and potentially run both transformers.

Ideally, the annotations should live in a third package - angular_annotations. Since they rarely change, it would not add much maintenance cost and allow services to only depend on that one package and neither angular1 (di.dart) or angular2.

**Comment by mhevery** [comment]
cc: @irfantusneem

**Comment by kegluneq** [comment]
This would work fine in the transformer as long as you update [AnnotationMatcher](https://github.com/angular/angular/blob/master/modules/angular2/src/transform/common/annotation_matcher.dart) to know about them

**Comment by rkirov** [comment]
After a chat with @tsander I am deprioritizing this as it would not prevent angular2 transformers running on angular1 apps, because angular2 transformers are declared per package not globally.

**Comment by mhevery** [comment]
@rkirov is this still a thing? 

I am closing as I think the current workaround is sufficient. Re-open if you feel otherwise.
