### ISSUE TITLE
Google Chrome refresh favicons every route change Angular 6

### ISSUE THREAD

**Issue by kolkov** [angular/angular#23643]
Hi! 
When I click to any router link I see new request for favicons...
Is this a bug?
```
<link rel="shortcut icon" href="./assets/icons/favicon.ico">
  <link rel="apple-touch-icon" sizes="180x180" href="./assets/icons/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="./assets/icons/favicon-32x32.png?v=Jy7JjExQOk">
  <link rel="icon" type="image/png" sizes="16x16" href="./assets/icons/favicon-16x16.png?v=Jy7JjExQOk">
  <link rel="icon" type="image/png" sizes="96x96" href="./assets/icons/favicon-96x96.png?v=Jy7JjExQOk">
  <link rel="icon" type="image/png" sizes="192x192" href="./assets/icons/android-icon-192x192.png?v=Jy7JjExQOk">
```
![image](https://user-images.githubusercontent.com/3740898/39505614-3425d288-4ddc-11e8-9d5e-8ed1a90fda67.png)

Angular CLI: 6.0.0-rc.7
Node: 9.11.1
OS: win32 x64
Angular: 6.0.0-rc.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.8
@angular-devkit/build-angular     0.5.8
@angular-devkit/build-optimizer   0.5.8
@angular-devkit/core              0.5.8
@angular-devkit/schematics        0.5.10
@angular/cli                      6.0.0-rc.7
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.0-rc.6
@schematics/angular               0.5.10
@schematics/update                0.5.10
rxjs                              6.0.0
typescript                        2.7.2
webpack                           4.6.0

**Comment by gkalpak** [comment]
Apparently, this is something that Chrome does whenever `history.pushState()` is called. It is neither related nor specific to Angular.

**Comment by philip-firstorder** [comment]
Changing the order of the icons doesn't fix it.
Putting favicon.ico at the top after the meta tag also didn't fix it.
Adding Cache-Control: max-age=604800 also didn't fix.

I guess we have to wait for Chrome to fix the bug.

**Comment by DeviousM** [comment]
So, way we fixed that stupid issue (in React though, but that doesn't matter) in our company is just by putting the favicon files in the root instead of putting it in the subcatalogue. Try, it really should work.

**Comment by gkalpak** [comment]
BTW, this Chromium bug is related: https://bugs.chromium.org/p/chromium/issues/detail?id=895175

**Comment by DeviousM** [comment]
@gkalpak - I know, I've stumbled upon it, but they still didn't release the fix. 
And not all users always download the latest version immediately, so moving the files to root is kind of a quick fix that does it's job for now.
