### ISSUE TITLE
AIO: IE polyfills not loaded always in blocking way

### ISSUE THREAD

**Issue by rokerkony** [angular/angular#23647]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[x] Other... Please describe:
</code></pre>

## Current behavior
On NgConf @IgorMinar had a great talk about SEO. One of the tips was to load polyfills only when necessary and he was pointing to a solution on AIO.

After taking creadits from AIO and implementing it in our app I started to see few cases when polyfills are not loaded and I was curious why. Unfortunatelly I found same problem as we have on AIO when using IE11.

Problem is that this can be still async https://github.com/angular/angular/blob/master/aio/src/index.html#L90

Screenshots where polyfills are loaded later than main chunks:
![screen shot 2018-05-02 at 13 48 23](https://user-images.githubusercontent.com/156132/39522368-435dee94-4e12-11e8-9195-1cdea8a2f6c5.png)

![screen shot 2018-05-02 at 13 49 47](https://user-images.githubusercontent.com/156132/39522348-3785a922-4e12-11e8-9931-dd6a6ae59226.png)

After reading more about the issue I found:
`script-inserted scripts execute asynchronously in IE and WebKit, but synchronously in Opera and pre-4 Firefox.` taken from: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

## Expected behavior
Polyfills should be loaded synchronously (in a blocking way).

## Minimal reproduction of the problem with instructions
I reproduced it e.g. when I went to `angular.io` and clicked on `Docs`

**Comment by gkalpak** [comment]
Good catch! I remember having a discussion about this with @petebacondarwin some time ago, but I can't find it now 😞

If I understand this [depressing blog post][1] (:grin:) correctly, adding `.async = false` to the script should at least fix the issue for IE10-11 (which might be good enough).

@rokerkony, could you verify that it solves the issue?

[1]: https://www.html5rocks.com/en/tutorials/speed/script-loading/

**Comment by petebacondarwin** [comment]
Does this mean this is a "won't fix"?

**Comment by rokerkony** [comment]
As I wrote we put it on prod and I just looked into logs and `.async = false` unfortunately doesn't help - it behaves same as before.

**Comment by mgol** [comment]
A suggestion: instead of dynamically adding the polyfills script for IE AIO could use:
```html
<script nomodule src="generated/ie-polyfills.min.js">
```
This will load IE polyfills not just in IE but in all browsers not supporting modules but that shouldn't be a problem - with the exception of Firefox which added `nomodule` support in version 60, a month ago, all other browsers support it (i.e. skip such scripts) since September-October 2017. And it's not that loading those polyfills would break those older browsers, they will just load & execute a file they don't need.

What do you think? Should I submit a PR?

**Comment by petebacondarwin** [comment]
I like it!

**Comment by gkalpak** [comment]
:+1:
(One thing to consider: Would googlebot be affected in a way we care?)

**Comment by mgol** [comment]
@gkalpak Googlebot uses Chrome 41 under the hood so it'd load the unneeded IE polyfills. I don't know whether that is a problem for us or not. It's quite clear, though, the current way doesn't work well in IE.

**Comment by petebacondarwin** [comment]
I don't think it will "break" the indexing by Googlebot - but it might slow it does a bit and affect our Google page rank?

**Comment by mgol** [comment]
Currently Chrome 41 loads 24 KB minified (7.8 KB gzipped) polyfills from polyfills.io. If it was instead changed to load IE polyfills via `<script nomodule>`, that'd increase to 96.4 KB (31.4 KB gzipped) of polyfills loaded from angular.io.

That said, it looks like most of the IE polyfills should be needed for Chrome 41 so I'm not sure if we're loading everything that's needed right now.

I'll submit a PR in a moment (I'm running the tests locally right now).
