### ISSUE TITLE
Routing is broken in IE9 and Angular 6.0.0-rc

### ISSUE THREAD

**Issue by steveblue** [angular/angular#23642]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Scaffold a simple app with two Routes and view in IE9. Try to navigate anywhere except base route and the browser will throw an error `SCRIPT438: Object doesn't support property or method 'apply'`. The Router is calling Zone with `null` instead of an Object and breaking IE9. 

## Expected behavior

An application can Route in IE9. It works in 5.x but upgrading to 6.0.0-rc breaks any Angular app we tested in IE9.

## Minimal reproduction of the problem with instructions

https://github.com/steveblue/ie9-angular-router-issue

## What is the motivation / use case for changing the behavior?

Enterprise users require IE9 support and this is such a major issue that is blocks apps from being deployed. If this issue persists I will not be able to upgrade to 6.0.0.

## Environment

<pre><code>
"@angular/core": "6.0.0-rc.6",
 "zone.js": "^0.8.19"

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X ] IE version 9
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4
- Platform:  Windows

</code></pre>

**Comment by trotyl** [comment]
Relates to https://github.com/angular/angular/issues/21083

**Comment by steveblue** [comment]
@trotyl that issue evolved into a discussion about how Animations blocks page load. This is a different issue entirely that only effects 6.0.0-rc while #21083 effects 5.x as well.

**Comment by steveblue** [comment]
OK, I was able to get IE9 to reveal the problem. TraceKit is a wonderful tool BTW, it prints stacktraces in IE9! For the Router in @angular 6.0.0 this polyfill is required. 

https://gist.github.com/edoardocavazza/47246856759f2273e48b
