### ISSUE TITLE
ValueProvide only supports already defined values

### ISSUE THREAD

**Issue by NoNameProvided** [angular/angular#23648]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When value provider is used in AOT mode, only variables can be assigned to the `useValue` property.

```ts
  // in a forRoot function
  providers: [
    {
       provide: NetworkConfig,
       useValue: config, // works
       // useValue: { ...new NetworkConfig(), ...config }, // doesn't work
     },
  ]
```

> Note: the title of the issue is not the best, but I don't know the proper name for this. Feel free to rename the issue. :) 

## Expected behavior

The `{ ...new NetworkConfig(), ...config }` syntax is supported to easily merge the recieved config with a default one.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-gitter-wxcyw

The demo has the code what can show the problem, but since Stackblitz uses the JIT compiler it will work as expected. So the demo must be downloaded and compiled with the `ng build --aot` command.

## What is the motivation / use case for changing the behavior?

When I inject the config it will be in the requested format everywhere, so I don't have to introduce a new service to hydrate all the injected option objects.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 65
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v9.9.9
- Platform:  Windows

Others:

Angular CLI: 1.7.3
Node: 9.9.0
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cdk: 5.2.4
@angular/cli: 1.7.3
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

</code>
</pre>

**Comment by mhevery** [comment]
the values have to be statically analyzable hence they value needs to be known at compile time. This is by design.

**Comment by abalad** [comment]
@NoNameProvided how did you get around this problem? I want to do the same thing with the config of my application:

```typescript
export class CoreModule {

    constructor (@Optional() @SkipSelf() parentModule: CoreModule) {
        if (parentModule) {
            throw new Error( 'CoreModule is already loaded. Import it in the AppModule only !!!!!!!!');
        }
    }
        
    
    static forRoot( lazyApplicationLoaderConfig: LazyApplicationLoaderConfig ): ModuleWithProviders {
      return {
        ngModule: CoreModule,
        providers: [
          {
            provide: APPLICATION_CONFIGURATION,
            useValue: Object.assign( new LazyApplicationLoaderConfig(), lazyApplicationLoaderConfig  )
          }
        ]
      };
    }
}
````
