### ISSUE TITLE
Wide currency values missing

### ISSUE THREAD

**Issue by KrekkieD** [angular/angular#23645]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

It is not possible to get the wide symbol format for the US Dollar (amongst others) in all locales:
```
import { getCurrencySymbol } from '@angular/common';
getCurrencySymbol('USD', 'wide'); // '$'
```
```
import { CurrencyPipe } from '@angular/common';
this.currencyPipe = new CurrencyPipe('en-CA');
this.currencyPipe.transform(10000, 'USD', 'symbol'); // $10,000.00
```

## Expected behavior

No matter the configured locale it should be possible to retrieve the wide format of any currency:
```
import { getCurrencySymbol } from '@angular/common';
getCurrencySymbol('USD', 'wide'); // 'US$'
```
```
// with registered localeData for en-CA
import { CurrencyPipe } from '@angular/common';
this.currencyPipe = new CurrencyPipe('en-CA');
this.currencyPipe.transform(10000, 'USD', 'symbol'); // US$10,000.00
```

## What is the motivation / use case for changing the behavior?

For currencies that have shared currency symbols (f.e. USD/CAD/AUD but also GBP/Falkland Islands Pound, etc) it should always be possible to get the wide format. It is currently not possible to show the `US$` notation for people with f.e. a Canada-based locale, where the short symbol `$` would imply the Canadian dollar and the wide syntax `US$` is required to distinguish the type of dollar.

## Environment

<pre><code>
Angular version: 5.2.10

</code></pre>

**Comment by ocombe** [comment]
Hello, good news for you, locale currency names & symbols have been added in v6: https://stackblitz.com/edit/angular-mncy8j

**Comment by maapteh** [comment]
Can't this be solved for the ones where upgrading to 6 is no option? Can we add a pull request for it?

**Comment by ocombe** [comment]
It's changing the behavior of the currency pipe, and could be considered a breaking change if people expected to see $ and suddenly see US$ instead. It could also be considered as a fix... @vicb what do you think? Can we backport the PR https://github.com/angular/angular/pull/21783 to 5.x ?

**Comment by maapteh** [comment]
Thanks for consideration. People may expect $, but their business will be very happy if it is showing the right locale (saves lot of money if Canadian dollar or American Dollar) :) Greetings from Toulouse!

**Comment by RomeshPanditha** [comment]
Did this fix only apply to en-CA?
Have tried to replicate with en-AU and am getting 'USD1000' rather than 'US$1000'
Same for all other currencies. When the locale is set to 'en-AU' currencies like JPY for example show 'JPY1000' instead of their native symbol.

**Comment by ocombe** [comment]
It depends what the CLDR locale data contain. For en-CA the narrow symbol for then yen is `¥` while for en-AU it's `JPY`.
Angular uses [CLDR](http://cldr.unicode.org/) data for all i18n values, if you believe that there is a mistake in those data, please open an issue on the CLDR repository: http://cldr.unicode.org/index/bug-reports
Thanks!
