### ISSUE TITLE
Support binding to the class/style in `host`

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2364]
```
@Component(
  hostProperties: {
    'class': 'classes'
  }
)
class MyWidget{
   classes = {'my-red-class', true};
}
```

**Comment by naomiblack** [comment]
This is internal b/21635551

**Comment by pkozlowski-opensource** [comment]
@mhevery I'm starting to look into this one but would like to confirm, that we want to accept any expression here, as in the NgClass directive - that is, an expression that could to evaluate to one of: string, array, object. Or maybe just accept an object?

In any case, if we are going to support '[class]: exp' here I would strongly suggest changing a selector for the [existing directive](https://github.com/angular/angular/blob/3e6503789ff445b765996bcb530e4ad88ace19e0/modules/angular2/src/directives/class.ts#L11) - otherwise it "looks" like we can call a directive from host properties...

BTW, today people can do: 

```java
@Component(
  hostProperties: {
    '[class.my-red-class]: 'showRed'
  }
)
class MyWidget{
   showRed = true
}
```

which is not as nice as a proposed syntax, but at least doesn't raise questions about directive.

I guess the bottom line is this: should binding to `classList` be so special that it has completely separate rules in the compiler?

**Comment by mhevery** [comment]
I think this issues was before we had `host` properties. So your Alderney syntax is correct. As far as accepting full expressions, I think we would like to limit the expressions here as much as possible do to test ability concerns. Let's do it without and revisit if it is not possible.

**Comment by naomiblack** [comment]
@pkozlowski-opensource can you update with status please?

**Comment by pkozlowski-opensource** [comment]
@naomiblack I'm afraid I didn't do much progress on this one... Impl should be easy but there is still one more thing I would like to discuss with @mhevery before moving forward.

**Comment by naomiblack** [comment]
moving to alpha-32 unless you happen to catch @mhevery earlier.

**Comment by pkozlowski-opensource** [comment]
Didn't progress on this one during .33, moving to .34

**Comment by pkozlowski-opensource** [comment]
Based on the in-person discussion with @vsavkin and @mhevery, we are not going to support binding to `[class]=exp` in host properties as it would either require activating directives in host properties or doing complex special-casing in the compiler. If people need to add / remove classes dynamically in their directives, it should be done by injecting renderer / element ref and doing it imperatively. 

Based on the above, here is the task breakdown:
* [ ] - rename class directive selector from `[class]` to `[ng-class]` - see PR #3498 
* [ ] - check how easy / hard is to do imperative / dynamic class manipulation from a directive. Make sure that it works correctly with hydrating / dehydrating
* [ ] - add convenience APIs if doing it "by hand" with the current APIs is too cumbersome.

**Comment by pkozlowski-opensource** [comment]
@vsavkin based on our discussion yesterday, here is a proposal for the helper API (assuming that I got your intentions right):

```java
@Directive({
    selector: '[my-directive]',
    lifecycle: [LifecycleEvent.onDestroy],
})
export class MyDirective {
    constructor(private _cssClass: CssClass) {
        this._cssClass.toggle('foo', true);
    }

    doSomething() {
        this._cssClass.toggle('foo', false);
        this._cssClass.toggle('bar', true);
    }

    onDestroy(): void { this._cssClass.cleanup(); }
}
```

So the interface of this utility (name to be decided) would be:

```java
interface CssClass {
    toggle(className: string, add: boolean);
    cleanup();
}
```

and an implementation would be stateful and would track which classes were added / removed for a given element. Then it would be capable of cleaning up after itself.

Is this sth you guys had on your mind?

**Comment by mhevery** [comment]
SGTM

**Comment by jelbourn** [comment]
@pkozlowski-opensource I would also have `add` and `remove` methods in addition to toggle, but I do like the idea. 

What does `cleanup` do? I wonder if we can make `cleanup` something that the user doesn't have to call manually.

**Comment by jpsfs** [comment]
Hi,

If you allow me to step in, what do you think about a ```has(string): boolean``` method? I kinda see a use for it too.

Cheers,

**Comment by pkozlowski-opensource** [comment]
@jelbourn we can definitively add `remove` and `add` for the convenience. 

> What does cleanup do? I wonder if we can make cleanup something that the user doesn't have to call manually.

The whole idea behind this helper class is that it "remembers" which classes (we will need to have similar mechanism for styles) were added / removed from a given element so when the view get de-hydrated we can restore the initial state of the element.

I would love to do it in the way that we don't need users to explicitly call `cleanup` but I don't know how to do atm :-(

**Comment by jelbourn** [comment]
@vsavkin is there any way of making changes to the injection to support something like this automatically being disposed upon component destruction?

**Comment by pkozlowski-opensource** [comment]
PR for this ready for review: https://github.com/angular/angular/pull/3557
