### ISSUE TITLE
aio search doesn't match on phrases with punctuation in search keyword

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#23652]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[X ] Other... Please describe: Doc usability and access issue
</code></pre>

## Current behavior

When I search for Node.js, the search drops everything after the . and searches for node, which provides a lot of false positive results. It's time-consuming to go to each result, do an in-page search, and then find out that 75% of the results did not contain "node.js" anywhere on the page. 

Similarly, when I search for "app-hero-detail", I get false positives. 

If I put quotation marks around the string, I got zero results, which is also not correct. False negative.

## Expected behavior

If a search keyword contains punctuation, include the punctuation as part of the search string. Do a Google search on node.js or app-hero-detail to see expected results. 

## Minimal reproduction of the problem with instructions

1. Go to https://angular.io

2. In the on-site search box, enter "node.js" without the quotes.
3. See all of the search results. Only the following results are correct:
https://angular.io/guide/setup
https://angular.io/guide/visual-studio-2015
https://angular.io/guide/npm-packages
https://angular.io/guide/quickstart
All other results are false positive, hitting on "node".
4. In the on-site search box, enter "node.js" with the quotes. No results found. This is incorrect.

5. In the on-site search box, enter "app-hero-detail" without the quotes.
6. See all of the search results. No way to know which are actual matches.
7. In the search results, select "Forms".
8. Now do an in-page search for "app-hero-detail". The only match is the angular.io site search box. This page is a false positive in the search results. 
9. In the on-site search box, enter "app-hero-detail" with the quotes. No results found. This is incorrect. At least one page does contain this string: https://angular.io/tutorial/toh-pt5

## What is the motivation / use case for changing the behavior?

Search is a primary on-site navigation aid. Punctuation in strings is a reasonable thing to expect, especially given how often they are found in code constructs. False positives waste time. False negatives create the impression the content doesn't exist. Both degrade the user's trust in search, to the point that users will go out to google to search, instead of using onsite search.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
A couple other examples: 
tree-shaking
tree-shakeable
ng-content (https://github.com/angular/angular/issues/17983)

**Comment by trotyl** [comment]
Another question, is it **Tree-Shakable** or **Tree-Shakeable**?
Both word have occurrence in doc, codebase and issues:

+ https://github.com/angular/angular/search?utf8=%E2%9C%93&q=tree-shakable&type=
+ https://github.com/angular/angular/search?utf8=%E2%9C%93&q=tree-shakeable&type=

As a non-English speaker I'm not sure which one is better, but strongly believe only one should be used.

**Comment by jenniferfell** [comment]
another phrase that's really important and can't be matched with aio site search: ng-template

I've actually given up on aio search. I go out to google search, find the right aio page from google results, and then I do in-page browser search within that aio page.
