### ISSUE TITLE
Incorrect release version

### ISSUE THREAD

**Issue by detroitpistons16** [angular/angular#23654]
Latest release version is ngcontainer_0.3.0 instead of an actual version?

Link to see the issue: https://github.com/angular/angular/releases

![image](https://user-images.githubusercontent.com/35926265/39549557-f26e8368-4e66-11e8-8642-f0945acc7389.png)

**Comment by pkozlowski-opensource** [comment]
Looks fine to me: https://github.com/angular/angular/releases

**Comment by gkalpak** [comment]
There was indeed an issue yesterday. (I've seen related errors [on CircleCI][1].)
It seems to be fixed now.

[1]: https://circleci.com/gh/angular/angular/41221

**Comment by detroitpistons16** [comment]
@pkozlowski-opensource somebody must have fixed it in the meantime and didn't say anything.

@trotyl thanks for the downvote.
