### ISSUE TITLE
loading jquery before angular.js

### ISSUE THREAD

**Issue by parliament718** [angular/angular#2365]
I'm experiencing an issue with ngDraggable library that is immediately solved by loading jquery.js AFTER angular.js. This issue: https://github.com/fatlinesofcode/ngDraggable/issues/119#issuecomment-109147536

Although doing so fixes all the issues with that library, is then breaks my entire code base (tons of console errors including a [Error: jqLite:nosel]). 

Does the angular community have any insight into why this may be happening? Could it be that angular.js is overwriting or hidding funtionality in jquery, such that loading it after jquery causes ngDraggable to break?

**Comment by gdi2290** [comment]
@parliament718 parliament718  this is the Angular 2.x repo so you're looking for the Angular 1.x repo https://github.com/angular/angular.js

**Comment by parliament718** [comment]
woops, sorry. https://github.com/angular/angular.js/issues/12033
