### ISSUE TITLE
Light font in footer difficult to read

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular#23651]
## I'm submitting a...

<pre><code>- [ x ] Documentation issue or request
</code></pre>

## Current behavior
Both the `angular.io` and the `next.angular.io` footers are using a light white font that is difficult to see. 
![image](https://user-images.githubusercontent.com/2133184/39542786-722c84ce-4e17-11e8-9c15-3c58b8584718.png)
![image](https://user-images.githubusercontent.com/2133184/39542794-7a7a7cf8-4e17-11e8-9c39-f99f6497482d.png)

## Expected behavior

It would be ideal if this text was a thicker font so it is easier to read. 

## What is the motivation / use case for changing the behavior?

Accessibility

## Environment

<pre><code>
Browser:
- [ x ] Chrome (desktop) version 66.0.3359.117

**Comment by zackarychapple** [comment]
@ericmartinezr if I disable `-webkit-font-smoothing: antialiased;` then I get the font to appear as you have it. 
![image](https://user-images.githubusercontent.com/2133184/39543995-bb2c00ca-4e1a-11e8-89e3-ec852506b752.png)

Unchecking the `-webkit-font-smoothing: antialiased;` box makes the font readable. 
![image](https://user-images.githubusercontent.com/2133184/39544003-c178d8fe-4e1a-11e8-9760-5c20546c6fa9.png)

**Comment by lazarljubenovic** [comment]
It's _a bit_ better here on Ubuntu/Chrome, but still not ideal to read at night.

![image](https://user-images.githubusercontent.com/7661457/39545084-5baa3618-4e50-11e8-90dc-eb942c48370b.png)

Regardless, it's an issue. It fails the WCAG contrast thingy.

![image](https://user-images.githubusercontent.com/7661457/39545058-4315fb28-4e50-11e8-9803-911f85dea78b.png)

(From [WebAIM: Color Contrast Checker](https://webaim.org/resources/contrastchecker/).)

**Comment by gkalpak** [comment]
I am also on Windows and it looks fine (aaccessibility aside).
Does setting the color to `#ffffff` (instead of `#fafafa`) help with antialiasing?

**Comment by zackarychapple** [comment]
@gkalpak it does not.

**Comment by ajitsinghkaler** [comment]
@gkalpak font-weight has been increased to 400 I think we can close this issue.

**Comment by gkalpak** [comment]
Thx, @ajitsinghkaler. While it is not perfect, it is looking much better now: https://webaim.org/resources/contrastchecker/?fcolor=1976D2&bcolor=FFFFFF
