### ISSUE TITLE
Angular elements guide should have a simple code snippet or example

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#23650]
## I'm submitting a...

<pre><code>
[X] Documentation issue or request
</code></pre>

## Current behavior
The Angular Elements guide has a fully fledged example of an Angular component rendered as a custom element, but doesn't break down the specific tasks I need to do to take advantage of this strategy.

https://next.angular.io/guide/elements

## Expected behavior
Simplify or add a simple example that focuses on the 2-3 steps developers need to do to take advantage of this: https://stackblitz.com/edit/angular-f3nrpv?file=app%2Fapp.module.ts

**Comment by wizardnet972** [comment]
[Elements - Check my repo](https://github.com/wizardnet972/angular-elements-talk)

**Comment by METACEO** [comment]
@wizardnet972 (no to hijack, a side question relating to my bug #23732) have you tried building both of your components  ('hello-world' and 'password-strength') independently and consuming them in one application?

**Comment by METACEO** [comment]
@wizardnet972 - following and I will keep an eye out for your video demo, thank you! [I updated my bug and included some screenshots of the workflow, I'd certainly be interested to know if you hit the same, or similar, errors.](https://github.com/angular/angular/issues/23732#issuecomment-387915011)

**Comment by mgechev** [comment]
Closing for now since it's not part of our immediate priority queue.
