### ISSUE TITLE
Routing not working in production build

### ISSUE THREAD

**Issue by Hari-25** [angular/angular#23669]
1. OS: Ubuntu
2. server: Apache (localhost)
3. Angular Version: 4
4. Node Version: 8.x
5. Chrome Version: 63.0.3239.108
- Info

I have facing a problem of routing in production build.
my project is routing properly if i try to click on the menu list. but if i try to refresh the page then show the 
the 404 error message. 
Not Found

The requested URL /webapp/Gallery was not found on this server.
Apache/2.4.27 (Ubuntu) Server at localhost Port 80
![screenshot from 2018-05-03 14-53-02](https://user-images.githubusercontent.com/38939826/39569675-8c2a18a6-4ee3-11e8-93f5-9430e1740570.png)

![screenshot from 2018-05-03 15-10-43](https://user-images.githubusercontent.com/38939826/39569965-6b9d025a-4ee4-11e8-9f24-4d65dfd59074.png)

**Comment by mlc-mlapis** [comment]
@Hari-25 ... you don't have a correct config on your server side ... related to HTML5 Push State config.

**Comment by Hari-25** [comment]
Please, can you provide a demo.

**Comment by jainanuj0812** [comment]
It's not an issue, please redirect all your UI server requests to default page (index.html). 

Please check this for more details - https://stackoverflow.com/questions/35284988/angular-2-404-error-occur-when-i-refresh-through-the-browser

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by AutumnsFall** [comment]
mine worked with this. https://stackoverflow.com/questions/26349497/node-express-with-static-html-how-to-route-all-requests-to-index-html
