### ISSUE TITLE
compiler-cli `ngfactories` are generated when setting fullTemplateTypeCheck and skipTemplateCodegen to true

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#23662]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When using the API and set the `CompilerOptions` inside code rather than reading from `tsconfig` and `emitFlags` is omitted from the `performCompilation` call. `ngfactories` are generated when setting `fullTemplateTypeCheck` and `skipTemplateCodegen` both to `true`.

## Expected behavior
No `ngfactories` are generated.

## Minimal reproduction of the problem with instructions
https://github.com/alan-agius4/angular-emitflags-issue-23662/blob/master/build.ts#L24

https://github.com/alan-agius4/angular-emitflags-issue-23662

## What is the motivation / use case for changing the behavior?
Should have the same behavior as when doing a compilation via the CLI command.

## Environment

<pre><code>
Angular version: 6.0.0-rc.6
TypeScript 2.7.2
</pre></code>

Others:

</code></pre>

**Comment by JoostK** [comment]
This is probably rooted in the following logic, which [has caused me headaches before](https://github.com/ng-packagr/ng-packagr/pull/860).

https://github.com/angular/angular/blob/6d11a8199479481f6ba68b6df5801b2257a5aad3/packages/compiler-cli/src/transformers/compiler_host.ts#L522

However, as factories and the old compiler are EOL, I am closing this as obsolete.
