### ISSUE TITLE
bug(form): NgForm should not use camelCase in element selector

### ISSUE THREAD

**Issue by trotyl** [angular/angular#23678]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

```html
<ngForm>
  <p>Some Input:</p>
  <input name="myModel" [(ngModel)]="myModel">
</ngForm>
```

## Expected behavior

```html
<ng-form>
  <p>Some Input:</p>
  <input name="myModel" [(ngModel)]="myModel">
</ng-form>
```

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-ejraew?file=app%2Fapp.component.html

More directly:

https://github.com/angular/angular/blob/cccc328a52c72919c388e583d3974f47c96827d2/packages/forms/src/directives/ng_form.ts#L67

## What is the motivation / use case for changing the behavior?

It completely break the design consistency.
Also using (non-native) element selector is useful for nested forms as in AngularJS, should not be removed.

Actually just a mistake in https://github.com/angular/angular/pull/5765

## Environment

<pre><code>
Angular version: 2.0.0-alpha.52 ~ 6.0.0-rc.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by IgorMinar** [comment]
ouch. I'm surprised we haven't noticed this before. you are right, we should fix this by deprecating the old selector and introducing the correct one + figuring out the migration path.
