### ISSUE TITLE
Disable form on init

### ISSUE THREAD

**Issue by eyalerez1** [angular/angular#23677]
I'm submitting a...
[x ] Bug report

## Current behavior
I create a form (with mat-form-fields) which I want to initialize as disable but it doesn't work.
It works only if I add setTimeout() of at least ~1000+.
I've tried to disable using:

ngOnInit(): void {
    this.form.disable();
  }

and also:

ngAfterViewInit(): void {
    this.form.disable();
  }

this issue is similar to #22556 but different.

## Expected behavior
The form should be disable.

## Environment
Angular version: 5.2.7
Browser:
- [ x] Chrome (desktop) version XX

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

<hr>

This also sounds as a 3rd party lib issue...
