### ISSUE TITLE
Allow components to provide values from within the component

### ISSUE THREAD

**Issue by dereklin** [angular/angular#23689]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have a component.  In my component, I provide a service.  This service is coupled with the component.  I am doing this so that I can split up my component code and move some specific logic into the service.

My service depends on some settings.  The settings are a @Input() in the component.

Now, I want to provide the settings in my component so that I can inject the settings inside the service in the service's constructor.

I tried this in component:
```
providers: [{ provide: SETTINGS, useValue: this.settings }]
```
even though ng serve doesn't complain, at run time, "this" is undefined.

## Expected behavior

It would be nice to be able to provide values within the component in its own providers list.

## What is the motivation / use case for changing the behavior?

To workaround this.  I need to create an init method in the service.  and initialize the settings in the component's onInit method.

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dawidgarus** [comment]
This should work:
```
providers: [{
  provide: SETTINGS,
  useFactory: comp => comp.settings,
  deps: [forwardRef(() => MyComponent)]
}]
```

**Comment by dereklin** [comment]
@dawidgarus 
That's some interesting idea.

Is it function allowed with useFactory now in a decorator?

For me, I had to export a function to use it, like:

```
export function _el(comp) {
  return comp.el.nativeElement;
}

export function _config(comp) {
  return comp.config;
}

@Directive({
  selector: '[MyDirective]',
  providers: [
    {
      provide: MY_ELEMENT,
      useFactory: _el,
      deps: [forwardRef(() => MyDirective)]
    },
    {
      provide: MY_CONFIG,
      useFactory: _config,
      deps: [forwardRef(() => MyDirective)]
    },
    MyService
  ]
})
export class MyDirective {
  ...

  constructor(private myService: MyService, public el: ElementRef) {}

  ...
```

Now the problem is that my directive is dependent on the service, and my service is dependent on my directive.  Here is MyService:

```
@Injectable()
export class MyService {
  ...

  constructor(
    @Inject(MY_ELEMENT) private el: any,
    @Inject(MY_CONFIG) private config: MyConfig
  ) {}
  ...
```
So I get the error:
```
Cannot instantiate cyclic dependency!
```

For my specific case.  MyService and MyDirective are tightly coupled, so I changed the injectable service into a normal class and just initiate the class manually.

Not sure if there will be a case someone wants to provide and inject an outside service into a directive/component and that service needs some properties from the component.  I am guessing there are not many such use cases.

**Comment by dawidgarus** [comment]
I'm assuming You need to have MyService in providers so it could be injected to other directives/components. Maybe this will help:
```typescript
@Directive({
  selector: '[MyDirective]',
  providers: [
    {
      provide: MyService,
      useFactory: dir => dir.myService,
      deps: [forwardRef(() => MyDirective)]
    },
  ]
})
export class MyDirective {
  constructor(el: ElementRef) {
    this.myService = new MyService(el, this.config);
  }
}
```
Or You can just extend MyService by MyDirective.

**Comment by dereklin** [comment]
Since MyService is provided in MyDirective, it's only local to MyService, and won't be available for injection for any other directives or components, right?

In that case, I don't need to provide it at all.  I have ended up is just:
```
constructor(el: ElementRef) {
    this.myService = new MyService(el, this.config);
  }
```

And since I am manually initiating, I don't need MyService to be @Injectable

I suppose if MyService were provided at the root like app.module.ts, I could still just use new MyService(el, this.config);

Maybe there is no need to provide properties inside of a component/directive...

**Comment by mhevery** [comment]
Closing, since services and component inputs have different lifetimes and therefore there is no consistent way to inject one into other. When services are created their behavior should be defined by the injection tree. The request is to have the injection based on run-time values, which is explicitly out of scope for injection. 

will not implement.
