### ISSUE TITLE
gulp serve.js.prod is not more building when a src file is updated

### ISSUE THREAD

**Issue by vicb** [angular/angular#2369]
seen with this file: angular/modules/benchmarks/src/naive_infinite_scroll/app.ts

linked to the migration to ts ?

**Comment by IgorMinar** [comment]
serve.js.prod was never setup to incrementally build. can you use serve.js.dev instead?

**Comment by vicb** [comment]
The prod version is required when running the benchmarks.

If there is not plan on implementing this, feel free to close.

**Comment by IgorMinar** [comment]
it's easy to implement but on our CI we also use serve.js.prod for benchmarks and end-to-end tests in which case we would rebuild the whole thing twice on CI. So it's a bigger change in the gulp setup

**Comment by IgorMinar** [comment]
@matsko could you create a target `serve.e2e.prod` just like you did for dev in #2473. thanks!

**Comment by matsko** [comment]
Here's the PR for that: https://github.com/angular/angular/pull/2516

**Comment by naomiblack** [comment]
@IgorMinar need a review from you on #2516 if we're going to close for Monday's alpha-27
