### ISSUE TITLE
App won't build with service worker after updating to v6

### ISSUE THREAD

**Issue by Ploppy3** [angular/angular#23692]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

App does not build with a service worker

> Error: Expected to find an ngsw-config.json configuration file in the [root/project/path] folder. Either provide one or disable Service Worker in your angular.json configuration file.
Error: Error: Expected to find an ngsw-config.json configuration file in the [root/project/path] folder. Either provide one or disable Service Worker in your angular.json configuration file.

## Expected behavior

App should build with service worker enabled after updading to v6.

## Minimal reproduction of the problem with instructions

Update an ng5 app with a service worker to ng6 using https://update.angular.io/

Build the app:
`ng build --prod`

NB: I even tried to set up the service worker again with the new `@angular/pwa` package as described here: https://angular.io/guide/service-worker-getting-started#adding-a-service-worker-to-your-project

NB: The docs says that the `ngsw-config.json` is located in the `src` folder (https://angular.io/guide/service-worker-config#service-worker-configuration)
While the error says it should be located at the root of the project. The `@angular/pwa` create the file at the root ; moving the `ngsw-config.json` file to the `src` folder does not fix the issue.

## Environment
<pre><code>
Angular CLI: 6.0.0                                            
Node: 8.9.4                                                   
OS: win32 x64                                                 
Angular: 6.0.0                                                
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser 
... platform-browser-dynamic, platform-server, router         
... service-worker                                            
                                                              
Package                           Version                     
-----------------------------------------------------------   
@angular-devkit/architect         0.6.0                       
@angular-devkit/build-angular     0.6.0                       
@angular-devkit/build-optimizer   0.6.0                       
@angular-devkit/core              0.6.0                       
@angular-devkit/schematics        0.6.0                       
@angular/pwa                      0.6.0                       
@ngtools/webpack                  6.0.0                       
@schematics/angular               0.6.0                       
@schematics/update                0.6.0                       
rxjs                              6.1.0                       
typescript                        2.7.2                       
webpack                           4.6.0                       
</code></pre>

**Comment by boradakash** [comment]
I have also experienced the same error after upgrading to v6,
and that issue looks related to path of angular service worker config file(ngsw-config.json)
When I updated v6 using **ng update**  it has created following path in angular.json file
"ngswConfigPath": "/src/ngsw-config.json",
then I changed to this
"ngswConfigPath": "src/ngsw-config.json",
and then I am able to build it successfully :)

**Comment by Ploppy3** [comment]
@boradakash Yeah, you're right the `ngsw-config.json` has to be in the root folder and your config fix did the trick for me. I'm successfully able to build again.

**Comment by manughub** [comment]
We're on it.

**Comment by skonx** [comment]
thx @boradakash

**Comment by ranbuch** [comment]
I was having the same problem when my config file configure like this:
`"ngswConfigPath": "src/ngsw-config.json"`
I was trying to build `ng b --prod` from `src/app/shared` instead of building from the root folder.
Building from the root folder fix the issue for me.

**Comment by alxhub** [comment]
I'm closing this as I believe the issue to be fixed. As I've tested with Angular 7, `ng add @angular/pwa` seems to do the right thing and put the `ngsw-config.json` in root.
