### ISSUE TITLE
Mention hex capitalization in author style guide

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#23691]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Neither Angular Author's Style Guide
https://angular.io/guide/docs-style-guide
nor Google Dev Doc Style Guide
https://developers.google.com/style/
are clear wrto capitalization of hex codes for colors

## Expected behavior

update https://angular.io/guide/docs-style-guide

## What is the motivation / use case for changing the behavior?

More complete guidelines for authors

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
docsarea=authorstyle

**Comment by jenniferfell** [comment]
correct case is lowercase

**Comment by sjtrimble** [comment]
@jenniferfell 
Did we decide that lowercase is the format we want to follow? (I prefer uppercase because I find it easier to read and my research yielded no solid result as to which one is 'correct', but I don't feel too strongly about it).

Regardless, do we still need to update the author's style guide to state this, or does prettier handle this for us somehow?
