### ISSUE TITLE
Need help to open any component in a different router and that router is in modal popup widnow. It is in Angular 5.

### ISSUE THREAD

**Issue by VishalRaghavIT** [angular/angular#23696]
## **I am working on Angular 5 application.**
Application list and detail screen Structure:

1. Open List screen.
2. Open detail screen by clicking on Edit icon from the last column in the grid.
3. Detail screen has multiple tabs.
4. On second tab, it display the list of child records and this list has actions button to Edit and Delete.

## **What I need :**
 
**I want to open that child record in a modal pop window.**

Please help me , how we can open that child record in modal popup window.
Do we need to use different router for that? and what code we need to implement to complete that task ?

Please provide any sample/code which work in my scenerio.

Thank you,
Vishal Raghav

**Comment by ocombe** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
