### ISSUE TITLE
After Upgrade to V6, getting 'postCSS' and 'sassLoader' undefined error.

### ISSUE THREAD

**Issue by sureshdotariya** [angular/angular#23694]
Tried Upgrading our application from Angular V5.2.10 to V6. Followed the steps mentioned in upgrade.angular.io

1) **npm install @angular/cli** - Success
2) **ng update @angular/cli** - Success
3) **ng update @angular/core** - returned below warning 
<pre><code>
Package "@ionic-native/core" has an incompatible peer dependency to "rxjs" (requires "^5.0.1", would install "6.1.0").
                  Package "codelyzer" has an incompatible peer dependency to "@angular/compiler" (requires ">=5.0.0-rc.0 <6.0.0||>=2.3.1 <3.0.0||>=4.0.0-beta <5.0.0", would install "6.0.0").
                  Package "ng2-translate" has an incompatible peer dependency to "@angular/core" (requires ">=3.0.0-rc.0 <4.0.0||>=2.0.0 <3.0.0", would install "6.0.0").
                  Package "ng2-translate" has an incompatible peer dependency to "@angular/http" (requires ">=3.0.0-rc.0 <4.0.0||>=2.0.0 <3.0.0", would install "6.0.0").
Incompatible peer dependencies found. See above
</code></pre>

4) So tried this command **ng update @angular/core --force**

5) **ng serve -o** command returns below error
<pre><code>
Could not find module "@angular-devkit/build-angular" 
</code></pre>

6) did npm install <code>@angular-devkit/build-angular</code> --save-dev

7) did **ng serve -o** again, getting the below error 

<pre><code>
Module build failed: TypeError: Cannot read property 'postcss' of undefined
    at Object.module.exports (/XXX/node_modules/postcss-loader/index.js:40:32)
ERROR in ./src/app/lib/bootstrap-4.0.0-beta/css/bootstrap.min.css (./node_modules/raw-loader!./node_modules/postcss-loader??embedded!./src/app/lib/bootstrap-4.0.0-beta/css/bootstrap.min.css)
Module build failed: TypeError: Cannot read property 'sassLoader' of undefined
    at getLoaderConfig (/xxx/node_modules/sass-loader/index.js:389:39)
    at Object.module.exports (/xxx/node_modules/sass-loader/index.js:42:23)
ERROR in ./xxx/inputControls.component.scss
</code</pre>

8) Also tried "npm install sass-loader node-sass --save-dev",  but same error.

Also this error is returning for all component scss files.

## Environment
<pre><code>
Angular version: 6.0
ng-bootstrap: 1.1.2

Browser:
- Chrome (desktop) version
For Tooling issues:
- Node version: 8.9.1
- npm: 5.0.3 
- Platform:  Mac
</code></pre>
## I'm submitting a...

<pre><code>
[ ] Bug report

**Comment by trotyl** [comment]
It's clearly to be Angular CLI issue: https://github.com/angular/angular-cli

**Comment by matsko** [comment]
Moved to https://github.com/angular/angular-cli/issues/10816
