### ISSUE TITLE
wildcard in angular.json

### ISSUE THREAD

**Issue by shahraship** [angular/angular#23695]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
In angular5, in .angular-cli.json, under assets wildcard entries used to work. for example:
"assets": [ "*.png" ]

In angular6, after the upgrade in angular.json file it changed to following:
"assets": ["src/*.png"]
however the build throws an error:
Error: ENOENT: no such file or directory

## Expected behavior
Expect it to evaluate the wildcard entries just like it used to before.

## What is the motivation / use case for changing the behavior?
To support backwards compatibility and also it's a nice to have.

## Environment

<pre><code>
Angular version: 6.0.0

**Comment by alan-agius4** [comment]
This is a CLi issue and should be created here instead https://github.com/angular/angular-cli

**Comment by shahraship** [comment]
Opened in angular/cli with issue number: 10645. Hence closing here.
