### ISSUE TITLE
Error: 'of' is not exported by node_modules/rxjs/Rx.js

### ISSUE THREAD

**Issue by RamonSchmitt** [angular/angular#23702]
## I'm submitting a...
[x] Bug report 

## Current behavior
[!] Error: 'of' is not exported by node_modules/rxjs/Rx.js

node_modules/@angular/common/fesm5/http.js (8:21)
 6:
 7: import { Inject, Injectable, InjectionToken, Injector, NgModule, PLATFORM_ID } from '@angular/core';
 8: import { Observable, of } from 'rxjs';
                                          ^
 9: import { concatMap, filter, map } from 'rxjs/operators';
10: import { __extends, __read, __spread } from 'tslib';

## Expected behavior
It should import the of observable from rxjs.

## Environment
rxjs version: 5.5.10
Angular version: 6.0.0
 
For Tooling issues:
- Node version: 6.10.1

Others:
This will work:
import { of } from 'rxjs/observable/of';
import { Observable } from 'rxjs';

**Comment by wartab** [comment]
Angular 6 requires RXJS 6, you should upgrade RXJS as well, not only Angular.

**Comment by trotyl** [comment]
Or use the rxjs [`5.6.0-forward-compat.xxx` versions](https://www.npmjs.com/package/rxjs/v/5.6.0-forward-compat.4).

**Comment by Ploppy3** [comment]
I will add this in case you don't know about it already https://update.angular.io/

**Comment by RamonSchmitt** [comment]
I noticed, https://update.angular.io/ wasn't updated yet this morning thnx.

**Comment by Ploppy3** [comment]
@RamonSchmitt they changed the domain of the update app, the one in your favs is probably the old one ;)
