### ISSUE TITLE
[IVY][Fix] Directives matching logic results in unnecessary attributes and bindings

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#23706]
### Problem description

The directives matching logic implemented today relies on attributes array passed to the `elementStart` instruction. This logic needs to be adjusted for cases where a directive needs to match a _binding_ instead of a static attribute.

Consider a simple example of the `<span [dir]="false">` template with the following directive:

```
@Directive({
  selector: '[dir]'
})
class Directive {
  @Input() dir;
}
```

Given this example the current compiler / runtime expect `elementStart(0, 'span', ['dir', 'false']);` but this is not correct: `dir` is not a real attribute and thus:
* should not be reflected in the DOM
* we should not use "false" in [binding inputs from attributes]()

Here is a simple (failing) test case that exposes both issues:  https://github.com/pkozlowski-opensource/angular/commit/06e93c697e00e4d1f4bd5462e8b4fb6d054e42fc

### Solution proposal

We should separate collection of "real" attributes and ones derived from bindings (and used only for directives matching). We could do so be introducing a new argument to the `elementStart` / `container` instructions: given the `<span class="nice" [dir]="exp" #local>` we should have: 
`elementStart(0, 'span', ['class', 'nice'], ['dir'], ['local', ''])`

### Other cases to consider

Seems like Renderer2 will still reflect attributes where there is no binding: `<span dir="literal">` - in this case an attribute is reflected in the DOM _and_ bound to the directive's input: https://stackblitz.com/edit/angular-nhcmpx?file=src%2Fapp%2Fapp.component.ts

cc @kara @mhevery

**Comment by kara** [comment]
My original thinking on this was that we could report property bindings in the attributes array with a special value like `null`, so we know not to actually set the attribute. But given that we have to support outputs in the same way, separating it out may be better / clearer

**Comment by mhevery** [comment]
We already need to support namespaces like so:
```
  elementStart(1, 'svg', [
      'id', 'display',
      'width', '400',
      'height', '300',
      NS.FULL, 'http://www.example.com/2014/test', 'title', 'abc'
    ])
```

Could we extend this mechanism to something like this:
```
  elementStart(1, 'svg', [
      'id', 'display',
      'width', '400',
      'height', '300',
      NS.FULL, 'http://www.example.com/2014/test', 'title', 'abc'
      NS.BIND_ONLY, 'dir'
    ])
```

This way no new array is created but we have the same information. In runtime we would know that once we hit `BIND_ONLY` we should stop creating attributes, but we should use the information after `BIND_ONLY` for selector matching.
