### ISSUE TITLE
build(compiler) `ng build` fails after upgrade to 6.0.0, `ng build --prod` works!

### ISSUE THREAD

**Issue by catull** [angular/angular#23709]
## I'm submitting a...

<pre><code>
[x] Regression (a behaviour that used to work and stopped working in a new release)
[X] Bug report  
</code></pre>

## Current behaviour

I am forced to use Bootstrap 3, NG CDK 5.2, NG flex-layout 2.0.0-beta.12 and NG Material 5.2.
This is due to limitations with the package `angular2-json-schema-form`.

The project has compiled, built and served with NG CLI versions 1.5 all the way to 1.7.4

When upgrading the project to NG 6.0.0, adding `rxjs-compat` as new dependency, `ng build` or `ng serve` fail with a "Module parse" error:

### `"Module parse" failed`
```log
ERROR in ./node_modules/angular2-json-schema-form/angular2-json-schema-form.js
Module parse failed: Identifier 'Ajv' has already been declared (6:12)
You may need an appropriate loader to handle this file type.
| import { cloneDeep, filter, isEqual, map, uniqueId } from 'lodash';
| import { FormArray, FormControl, FormGroup, FormsModule, NG_VALUE_ACCESSOR, ReactiveFormsModule } from '@angular/forms';
| import * as Ajv from 'ajv';
| import { DomSanitizer } from '@angular/platform-browser';
| import { CommonModule } from '@angular/common';
```
`ng build --prod` builds nicely, though!

## Expected behaviour

`ng build` should work as before.

## Minimal reproduction of the problem with instructions

I prepared a repo:  [catull/angular-issue23709.git](https://github.com/catull/angular-issue23709.git).

### Branch [works-with-ng-1.7.4](https://github.com/catull/angular-issue23709/tree/works-with-ng-1.7.4)

This branch actually can be built with both NG CLI version 1.7.4 and 6.0.0!
It was created with NG CLI 1.7.4.

With both NG CLI version 1.7.4 AND 6.0.0, we have:
- :sparkles: `ng build --prod` :sparkles:
- :sparkles: `ng build` :sparkles:
- :sparkles: `ng serve` :sparkles:

### Branch [upgraded-to-angular-6](https://github.com/catull/angular-issue23709/tree/upgraded-to-angular-6)

This branch does not build with NG CLI 6.0.0.
It is basically the branch `works-with-ng-1.7.4` upgraded to  NG 6, with `rxjs-compat` included as new dependency, no other changes other than the upgraded \@angular packages.

We have:
- :sparkles: `ng build --prod` :sparkles:
- :boom: `ng build` => "Module parse" failed :boom:
- :boom: `ng serve` => "Module parse" failed :boom:

### Branch [created-with-ng-cli-6](https://github.com/catull/angular-issue23709/tree/created-with-ng-cli-6)

This branch is generated with NG CLI 6.0.0.

We have:
- :sparkles: `ng build --prod` :sparkles:
- :boom: `ng build` => "Module parse" failed :boom:
- :boom: `ng serve` => "Module parse" failed :boom:

## Conclusion

The upgraded project does not "dev" build anymore.

I can launch the app with `lite-server`, not nearly as convenient as `ng serve`.
But I cannot have `ng build --watch` along with it, so this sucks.

## Environment

<pre><code>
Angular version: 6.0.0
Node: 10.0.0
OS: macOS 10.12.6
</code></pre>

**Comment by matsko** [comment]
Moved to https://github.com/angular/angular-cli/issues/10817
