### ISSUE TITLE
$event.target undefined in platform-webworker

### ISSUE THREAD

**Issue by rolaveric** [angular/angular#23703]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When a browser event is passed to the Worker, it loses the `target` property.

## Expected behavior
`$event.target` should resolve to a Render Store Object on the Worker, which can then be used with `Renderer2` methods or passed back to the UI via Service/ClientMessageBroker.

## Minimal reproduction of the problem with instructions
Plunker using Angular v6.0.0: https://plnkr.co/edit/ZeADic?p=preview
I also have a github repo that can reproduce the issue:
https://github.com/rolaveric/angular-webworker-playground
1. Clone repo
2. `yarn` or `npm install`
3. `yarn run start-webworker`
4. Load `http://localhost:4200/`
5. Click anywhere on the page (`@HostListener('document:click')`)
6. Console log with `$event.target` value

## What is the motivation / use case for changing the behavior?
Key use case is for detecting when a `click` has occurred outside a certain element, such as a dropdown menu.

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [x] Chrome (desktop) version 66
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 59
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.0.0
- Platform:  Mac

Others:
</code></pre>

**Comment by rolaveric** [comment]
I think the best solution would be to always return `target` as a Render Store Object [on the UI](https://github.com/angular/angular/blob/master/packages/platform-webworker/src/web_workers/ui/event_dispatcher.ts#L110) and stitch it back onto `$event` [on the Worker side](https://github.com/angular/angular/blob/master/packages/platform-webworker/src/web_workers/worker/renderer.ts#L109), and have some other mechanism to query the element itself - whether
The only trouble is this would break the existing behaviour provided by the [`addTarget()`](https://github.com/angular/angular/blob/master/packages/platform-webworker/src/web_workers/ui/event_serializer.ts#L52) function, which extracts the `value` and `files` properties - if present.  
You could chalk this up to experimental APIs changing, or you could only apply this behaviour to mouse events and wait till v7 to apply a breaking change.

**Comment by jelbourn** [comment]
Closing all issues related to web-workers since Angular's experimental web-worker renderer has been deprecated and it now being removed completely in Angular v11.
