### ISSUE TITLE
[IVY][Fix] Queries refreshed before directive lifecycle hooks

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#23707]
### Problem description

As of today a simple view query in a component will result in a generated code along those lines:

```typescript
if (rf & RenderFlags.Create) {
  query(0, 'foo', true, QUERY_READ_ELEMENT_REF);
  elementStart(1, 'div', null, ['foo', '']);
  elementEnd();
}
if (rf & RenderFlags.Update) {
  queryRefresh(tmp = load<QueryList<any>>(0)) && (ctx.query = tmp as QueryList<any>);
}
``` 

Notice that the the `queryRefresh` instruction is _part of a template function_. Now consider that an element **has a directive on it** and this directive will **insert an embedded view in the ngOnChanges lifecycle hook**). This is not a rare case - for example [ngTemplateOutlet does it](https://github.com/angular/angular/blob/490e39a23fc9d95b0ab59ffd85923e4209f93801/packages/common/src/directives/ng_template_outlet.ts#L45-L62).

If I understand correctly the `ngOnChanges` hook of a directive will be executed _after_ a template function was run. But since a query is refreshed _inside_ a template function the net effect is that **queries are refreshed before ngOnChanges lifecycle hook of directives**. This in turn means that queries won't pick-up results from embedded views created in the mentioned lifecycle hook!

### Solution options

We need to do one of:
* move lifecycle hooks execution to a template function instruction
* move query refresh logic out of template function (to do it in a tree-shakable way we need to have it as a feature, probably).

This needs proper design, cc @mhevery @kara

**Comment by kara** [comment]
+1 on #2 solution

**Comment by mhevery** [comment]
+1 for #2, here is how it could work.

```
  query(0, 'foo', true, QUERY_READ_ELEMENT_REF);
``` 
Would insert `queryRefresh` into the `View` hooks array. This way it would be able to invoke the `queryRefresh` at correct time.

Because the `queryRefresh` is also used as a guard to assignment `&& (ctx.query = tmp as QueryList<any>);` We would have to leave a flag someplace to know that we need to do the assignment.

**Comment by pkozlowski-opensource** [comment]
Note to self when considering changes to the query refresh mechanism: as of today `@ViewChild` assignment happens _much_ earlier as compared to `@ViewChildren`  assignment:
https://stackblitz.com/edit/angular-lub689?file=src%2Fapp%2Fapp.component.ts

More importantly, the `@ViewChild` assignment happens _before_ `ngOnInit` hooks which seems to be controversial / confusing, see: #21800

Current thinking: make `@ViewChild` / `@ViewChildren` assignment happening at the _same_ time (and after `ngOnInit`), effectively "solving" #21800
