### ISSUE TITLE
Better visual feedback for loads during router navigation

### ISSUE THREAD

**Issue by jonrimmer** [angular/angular#23701]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The resolve capability of the router is currently almost useless, due to the lack of support for providing targeted and specific visual feedback to the user about what is loading, and where. If a dev naïvely adds a resolve that includes a slow network request, there will be no obvious feedback when a user clicks on a link that anything is occurring at all.

Surprisingly, the Angular router documentation does not even mention this anti-pattern, either as something to be concerned about, or to suggest a mitigation. Perhaps because there *is* no good mitigation. The only recommendation I have found (via StackOverflow) is to listen for the global navigation start and end events, and show a blanket, app-wide spinner, like a bad AJAX app from 2005. This might be just about OK on mobile, but is absolutely _horrible_ on desktop, where it has long been standard practice in web apps to constrain indicators to just those sections of the UI that are loading new data.

## Expected behavior

It should be possible to:

- Target those parts of the UI which will be affected by in-progress navigation.
- Display custom UI in those locations for the duration of the load.

My suggestion:

 1. When a route navigation starts, check if whether there are any resolves that need to be processed. If there are, identify all `router-outlet` components that will activate if it is successful. Find those that are topmost in the component hierarchy. I.e. those that are not nested within another `router-outlet` that will also be affected by the navigation. These are the pre-active roots.
 2. For each pre-active root, set them into a `preActive` state. This should be reflected by a `preActive` boolean property on the `router-outlet` component controller, and by them firing a `preActivated` event.
 3. Add an optional `preActiveComponent` property to the router config. If set, during a navigation with resolves, this component will be rendered by each pre-active root _alongside_ the currently activated component (if any).
 4. Add an optional `preActiveDelay` property to the router config. If set, there will be a grace period of this many milliseconds before firing the `preActive` event.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-gitter-nmrets

1. Click on the "Go somewhere (with a slow resolve)." link.
2. See that the user experience is horrible.

## Environment

<pre><code>
Angular version: 6
</code></pre>

**Comment by atscott** [comment]
Tracking in #42489
