### ISSUE TITLE
Scrolling is slow in a big table benchmark

### ISSUE THREAD

**Issue by bradlygreen** [angular/angular#2371]
I'm seeing 14-20 FPS for the Angular 2 version of this benchmark https://rawgit.com/alincc/angular-test-table/master/angular2/dist/index.html (code https://github.com/alincc/angular-test-table/tree/master/angular2).

@tbosch thought this was related to the test's use of rAF interacting poorly with our Zones.

**Comment by vicb** [comment]
The `ng-for` should be on `<tr>` https://github.com/alincc/angular-test-table/blob/master/angular2/src/templates/test-table.html#L20

**Comment by tbosch** [comment]
@vicb yes, you are right. Just double checked it and by changing this we get the same FPS as the other examples. See https://github.com/alincc/angular-test-table/issues/4.

Closing this.
