### ISSUE TITLE
TypeError: Cannot read property 'xxxx' of undefined

### ISSUE THREAD

**Issue by JohnGalt1717** [angular/angular#23712]
## I'm submitting a...
[x] Bug report  

## Current behavior
In previous versions with the cli (6.0.0-rc.10 with 6.0.0-rc.6 of the compiler) everything was fine. IN the new version we're getting a ton of TypeError: Cannot read property 'xxx' of undefined.

ngx-quill causes this as does the following:
`
export namespace Enums {
	export enum AccountTypes {
		Checking = 1,
		Savings = 2,
		SharedDraft = 3,
	}

	export const AccountTypesTranslation: Structures.KeyValuePair[] = [
		{ value: AccountTypes.Checking, text: 'Checking' },
		{ value: AccountTypes.Savings, text: 'Savings' },
		{ value: AccountTypes.SharedDraft, text: 'Shared Draft' },
	]
}
`

and this in app.module.ts:
`
import { Enums } from './api/xxx.Interfaces';
`

It appears that all of the Enums items are all factored out and cause undefined.

## Expected behavior
Should work like 6.0.0-rc.6 (and cli rc.10) and not factor out this code causing errors.

## Environment
Angular CLI: 6.0.0
Node: 8.10.0
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

Browser:
- [X ] Chrome (desktop) version Latest
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version Latest
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X] IE version 11
- [X] Edge version 17
 
For Tooling issues:
- Node version: 8.10.0
- Platform:  Windows

##Steps to Reproduce

ng new projectname

Add a new ts file with the above snippet of typescript
Import it into app.module.
In app.component.ts import it again and attempt to use it there. Or do the same in the app.module in n APP_INITIALIZER. In both cases you'll get the above error.

**Comment by fergalmoran** [comment]
@trotyl  @ericmartinezr Why the thumbs down? This is definitely an issue.

**Comment by trotyl** [comment]
No reproduction, wrong repo.

**Comment by JohnGalt1717** [comment]
There's a reproduction. It's clearly outlined.

What wrong repo? This is angular.

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/10655, not an Angular issue.

**Comment by JohnGalt1717** [comment]
Ok... well as long as someone knows...
