### ISSUE TITLE
Support for query parameters without values

### ISSUE THREAD

**Issue by pedroclayman** [angular/angular#23714]
## I'm submitting a...

<pre><code>
[ x] Feature request
</code></pre>

## Current behavior

Currently, when you use RouterLinkDirective and specify [queryParams] there is not a way how to specify a parameter without a value producing a URL in a form like the following: *http://foo.bar?abc*. The closest you can get to this is http://foo.bar?abc= (AFAIK).

## Expected behavior

There should be a way to specify a query parameter without a value.

## Environment

<pre><code>
Angular version: 5.0.5
</code></pre>

**Comment by jelbourn** [comment]
Revisiting older issues and PRs. Going to close this since we don't have a strong enough signal for this feature.
