### ISSUE TITLE
Services step in Tour of Heroes tutorial doesn't follow RWE

### ISSUE THREAD

**Issue by HillChris1234** [angular/angular#23717]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
in the Tour of Heroes, on Step 6 of the tutorial (services), after you generate the hero service, the tutorial says that Injectable should come with {providedIn: 'root',} as an argument. This does not happen for me, and when I add it manually, the CLI doesn't compile citing "Expected 0 arguments, but got 1."

## Expected behavior
The tutorial should reflect what actually happens.

## Minimal reproduction of the problem with instructions
Follow the tutorial to Step 6. The service is not created as the tutorial describes

## What is the motivation / use case for changing the behavior?
People learning Angular should be able to follow the tutorial

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by emilio-martinez** [comment]
@HillChris1234 docs now reflect angular v6, so you'll need to upgrade to that to follow the guide as shown

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
