### ISSUE TITLE
The angular1 router as angular nested child route cannot take effect when the page is refreshed

### ISSUE THREAD

**Issue by billyma128** [angular/angular#23719]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Use ngRoute(ng1) as root sibling router, it works fine:
https://stackblitz.com/edit/angular-q1gj9s

Use ngRoute as child route of root router, it works fine when navigate from ng6 to ng1, broken when refresh ng1 route page:
https://stackblitz.com/edit/angular-cegnxc

## Expected behavior

Refresh the page of ng1 route in the case 2, ngView takes effect.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-cegnxc

## What is the motivation / use case for changing the behavior?

Upgrade from ng1.

## Environment
<pre><code>
Angular version: 6.0.0
AngularJS version: 1.6.10
Angular-Route version: 1.6.10

Browser:
- [x] Chrome (desktop) version 66.0.3359.139
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.0  
- Platform:  Mac

Others:

</code></pre>

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
