### ISSUE TITLE
Web Worker compiled with main Angular app

### ISSUE THREAD

**Issue by SamProf** [angular/angular#23730]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Now if we need create web worker for our application we can 
- develop and compile it outside angular project.
- make <code>ng eject</code> and then make some modification in webpack config file

## Expected behavior

Posibility to add in angular.cli.json or angular.json file list of workers files and then they can be compiled (with all imports) as external files, that later we can use.

## What is the motivation / use case for changing the behavior?

JS world is one-thread and sometimes we need more "threads" for our applications. It can make easely to create few different threads and run sum tasks outside main js loop.

## Environment
<pre><code>
Angular version: ^6.0.0

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX

**Comment by jbogarthyde** [comment]
See also #17779

**Comment by jelbourn** [comment]
Closing all issues related to web-workers since Angular's experimental web-worker renderer has been deprecated and it now being removed completely in Angular v11.
