### ISSUE TITLE
Renamed imports break the angular2.d.ts

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#2373]
A common pattern in Angular code is
import * as viewModule from './view';

the name 'viewModule' should only be known within this file - other modules may import from 'view' but choose their own renames.

Currently our dgeni-based .d.ts generator naively looks at the text of declared symbols, so 'viewModule' leaks out into the .d.ts.

My current workaround is to define a nested module 'viewModule' under 'angular2/angular2' which declares empty interfaces for each type exported from 'view' but this is bad, it breaks completion and type-checking.

**Comment by mhevery** [comment]
No longer the case. Closing.
