### ISSUE TITLE
I upgraded my project to angular6 but there is a problem here

### ISSUE THREAD

**Issue by MrZwqShuai** [angular/angular#23738]
I have upgraded my project which structure by angular5.2 to angular 6，I follow the angular website setps to upgrade my application，like this

but when I run my application I get this problem that say ‘ERROR Error: Uncaught (in promise): Error: Cannot find module "app/xxx/xxx.module".’ and I get a warning say ‘System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/’ 

this module is a lazy module for route， use like  loadChildren: 'app/xxx/xxxmodule#FirstScreenModule'

what happend here ? who can help me

**Comment by hitandyrun** [comment]
Try using loadChildren like this: loadChildren: './xxx/xxxmodule#FirstScreenModule'.

see this commit: https://github.com/angular/angular/commit/f44a2c730a84cd86695d1851395ad28423704bd0

**Comment by leeseean** [comment]
help

2018-05-07 18:24 GMT+08:00 Eric Martinez <notifications@github.com>:

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
