### ISSUE TITLE
Angular CLI 6: Unhandled Schematics Error when using invalid project names

### ISSUE THREAD

**Issue by georgiee** [angular/angular#23744]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I'm in the process of upgrading to Angular and I want to create a plain project with the CLI first. I accidentally used a name that is not valid 'test-6v' and I got the following response:
```
Schematic input does not validate against the Schema: {"name":"test-6v","version":"6.0.0","newProjectRoot":"projects","skipInstall":false,"linkCli":false,"skipGit":false,"commit":null}
Errors:
Data path ".name" should match format "html-selector".
```

## Expected behavior
I expect to see a human readable error that is not that cryptic so people are not confused. It looks more like an unhandled error from the schematics itself. In previous version you got a proper error telling you "Project name <NAME> is not valid". 

## Minimal reproduction of the problem with instructions
This fails:
```
ng new test-6v
```

This works:
```
ng new test6v
```

## Environment
```
Angular CLI: 6.0.0
Node: 8.9.4
OS: darwin x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.0
@angular-devkit/core         0.6.0
@angular-devkit/schematics   0.6.0
@schematics/angular          0.6.0
@schematics/update           0.6.0
rxjs                         6.1.0
typescript                   2.7.2
```

**Comment by ericmartinezr** [comment]
Please report angular-cli issues in its repo https://github.com/angular/angular-cli 👍

**Comment by georgiee** [comment]
Oh no,
I feared to make a mistake with my first Angular issue and got it wrong in the beginning 😬

Will move.

**Comment by onurinci** [comment]
Do not include project name special characters. for example this is wrong: www_testProject.

This is correct: wwwTestProject

**Comment by Maxyee** [comment]
Thanks for you support @onurinci . it really helps

**Comment by dhanarajknp** [comment]
npm install rxjs@6 rxjs-compat@6 --save use this command to solve compactablity version issue

**Comment by satishpatro44** [comment]
I tried with normal name, still it doesn't work
`D:\Angular Projects>ng new DemApFiv;
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
Schematic input does not validate against the Schema: {"name":"DemApFiv;","version":"7.0.3","routing":true,"style":"css"}
Errors:

  Data path ".name" should match format "html-selector".`

I checked >>npm install for an old project

`D:\Angular Projects\DemoApp01>npm install;

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    completion, config, create, ddp, dedupe, deprecate,
    dist-tag, docs, doctor, edit, explore, get, help,
    help-search, hook, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, profile, prune, publish, rb, rebuild, repo, restart,
    root, run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    C:\Users\xyz\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.4.1 C:\Users\xyz\AppData\Roaming\npm\node_modules\npm

Did you mean one of these?
    install
    uninstall
    unstar`

Can anyone help me what to do?

**Comment by breakdeath** [comment]
Funciono, gracias! 
![inicio](https://user-images.githubusercontent.com/13208422/48970972-b275f880-eff2-11e8-86cf-7cb5b7c78209.JPG)

**Comment by seranet** [comment]
try to delete the _ in the name of project 

ex: **sera-project**  not sera_project

**Comment by KarthikDev81** [comment]
> Funciono, gracias!
> ![inicio](https://user-images.githubusercontent.com/13208422/48970972-b275f880-eff2-11e8-86cf-7cb5b7c78209.JPG)

Thanks Man... Worked

**Comment by maqk** [comment]
I resolved my issue but not giving the underscore in the project name :-D

**Comment by amwayDarshana** [comment]
But for me still have the issue.  
![image](https://user-images.githubusercontent.com/42367701/53789242-f74cec00-3f5e-11e9-9443-5a26c66bbb11.png)
