### ISSUE TITLE
angular.io/docs - v5 is missing from version dropdown

### ISSUE THREAD

**Issue by fpeterdev** [angular/angular#23746]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

On https://angular.io/docs there's no option int the dropdown for v5. I can get there by explicitly using https://v5.angular.io/docs so it's not an urgent one.

## Expected behavior
There should be a v5 option in the dropdown.

**Comment by mhevery** [comment]
closing as dup of https://github.com/angular/angular/issues/23746

**Comment by trotyl** [comment]
Correct the link: https://github.com/angular/angular/issues/23781
