### ISSUE TITLE
Docs Tutorial Part 8, missing part of final code review

### ISSUE THREAD

**Issue by Braindea7** [angular/angular#23747]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Missing the dashboard code changes in the tutorial part 8 at final code review.
Without the dashboard changes, the search doesn't appear on the dashboard.

## Expected behavior

The changes of the dashboard files should appear in the final code review. 

## What is the motivation / use case for changing the behavior?

People could get confused without these code parts in the final code review.

## Environment

<pre><code>
Angular version: X.Y.Z

6.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
filename=https://angular.io/tutorial/toh-pt6#final-code-review
docsarea=tutorial

Minimally missing dashboard.component.html from the final review.
4 other files are shown in code examples in this doc, but are not in the final review, so those might also need to be added.

**Comment by chembu** [comment]
Fixed in PR #24445
