### ISSUE TITLE
Radio buttons are not checked in an ngFor with async pipe

### ISSUE THREAD

**Issue by Elecash** [angular/angular#23748]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Radio buttons are not checked in an `ngFor` with `async` pipe bound to function that returns an inlined Observable.

## Expected behavior
The radio button are checked.

## Minimal reproduction of the problem with instructions

Check the radio buttons and see how they're not checked.
https://stackblitz.com/edit/angular-urfeyj?file=src%2Fapp%2Fapp.component.ts

## Environment

Angular version: 5.2.0 & 6.0.0

Browser:
- [x] Chrome (desktop) version 66
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 59
- [x] Safari (desktop) version 11.1
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: with Angular 5.2.0 and Node 8.6 | with Angular 6.0.0 and StackBlitz Node version
- Platform:  Mac

**Comment by ericmartinezr** [comment]
I don't think this is related to async pipe. The problem is that you're returning a new array each time, therefore you're recreating the list each time you click on any item. You can reproduce the same behavior without the async pipe and returning an array (check the dom inspector in your browser, and click in any radio, in any group).

```
<div *ngFor="let option of getListDoesNotWork()"> 


  getListDoesNotWork() {
    return [
    {id: '0', name: 'David'},
    {id: '1', name: 'John'}, 
    {id: '2', name: 'David2'},
    {id: '3', name: 'John3'}
  ];
  }
```
imho this is an expected behavior.

**Comment by Elecash** [comment]
Obviously! Thanks for pointing me to the right direction 👍
