### ISSUE TITLE
'Uncaught SyntaxError: Unexpected token %' issue when using jsonp with angular5

### ISSUE THREAD

**Issue by pranabunni** [angular/angular#23752]
I am new to angular5 and I trying to call a api using 'jsonp' property.
```
this.http.jsonp('http://localhost/angular5/lesson2.pdf?callback=JSONP_CALLBACK').subscribe(res=>{
     console.log(res);
   })
```
in the above code I am using 'HttpClinetJsonpModule' for calling the api.But it returns following error.
![screenshot from 2018-05-07 19-06-35](https://user-images.githubusercontent.com/22249146/39711346-1dc38c28-523d-11e8-95bb-79467bd3a7e2.png)
can anyone please help me to solve this issue.I already spend a few hous in it.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
