### ISSUE TITLE
when having a component rendered in `ng-content`, by `ng-if`, this component life cycles hooks are called, even if it isn't  rendered because ng-if.

### ISSUE THREAD

**Issue by brachi-wernick** [angular/angular#23756]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
when having a component rendered in `ng-content`, by `ng-if`, this component life cycles hooks are called, even if it isn't  rendered because ng-if.
this can cause issues when I have for example `ngDoCheck`

## Expected behavior
life cycles hooks should be called *just* if this component is rendered

## Minimal reproduction of the problem with instructions
open and run this:
https://stackblitz.com/edit/angular-xstszl

here I have `AppComponent` render  `myAppComponent`.
`MyAppComponent` knows to get `ng-content` and display it , currently it always not shown.
here I send `HelloComponent` as content, in `HelloComponent` I have 2 life cycles hooks for `ngOnInit` and for `ngDoCheck`.
I print to console when I get to this 2 hooks.

run application and click button. any time it's clicked you get to console a notification on `ngDoCheck` even this component is OFF, and NOT IN DOM!!!
 

## What is the motivation / use case for changing the behavior
can cause low performance for components that are not displayed, but get hooks.

please suggest fix or workaround, seems to me as very big issue

**Comment by mlc-mlapis** [comment]
@brachi-wernick ... you missed some information about the design how `<ng-content>` works. It is not a bug, it runs as designed.

Please, look at the presentation from **ng-conf** on that theme:
https://nitayneeman.com/posts/all-talks-from-ng-conf-2018/#deep-dive-into-content-projection

**Comment by brachi-wernick** [comment]
@mlc-mlapis I see the presentation, the point was to use `ng-template`, still same issue:
```html
<ng-template #try>
  <ng-content></ng-content>   
</ng-template>

<ng-container *ngIf="false" [ngComponentOutlet]="try">

</ng-container>
```
I think it's an issue, how can I overcome it?

**Comment by mlc-mlapis** [comment]
@brachi-wernick ... hmm, try to look at it once more. It is not about when the `<ng-content>` is instantiated but where and how it is possible to affect the `<ng-content>` placed. That is the reason why `<ng-content>` can affect performance in some cases so it is necessary to understand how it works and be careful.

But the principle of `<ng-content>` is that it is instantiated when the host component is instantiated and it also means that Angular compiler creates the rule and related JS code when compiling the code. No run-time affects the behavior later.

**Comment by sandangel** [comment]
this is by design. You can not change it. The ng-content just change the **PLACE** the component is rendered in DOM tree, it does not change **WHEN** the component is created.

**Comment by brachi-wernick** [comment]
OK.  Understood.  Any suggestion how to avoid uneccesary `ngDoCheck` when it is hidden because `ng-if`

**Comment by sandangel** [comment]
@brachi-wernick can you fix the reproduction link? It just linked to a new angular project

**Comment by brachi-wernick** [comment]
@sandangel here is the real link https://stackblitz.com/edit/angular-xstszl

**Comment by brachi-wernick** [comment]
@sandangel here is the real link https://stackblitz.com/edit/angular-xstszl

**Comment by brachi-wernick** [comment]
@sandangel sorry for that here is the real link. I updated also the description. 
https://stackblitz.com/edit/angular-xstszl

**Comment by mlc-mlapis** [comment]
@brachi-wernick ... also remember that `ngDoCheck()` hook is called by the parent component and not by the child component itself.

**Comment by brachi-wernick** [comment]
works if I use `ng-template` and not ng content:
https://stackblitz.com/edit/angular-pcwfnm

**Comment by mlc-mlapis** [comment]
@brachi-wernick ... yep, it is only about `<ng-template>` functionality then. What we discussed before was mainly about `<ng-content>`. They have different sense, sometimes it is just suitable to combine them.

**Comment by mhevery** [comment]
Works as intended.
