### ISSUE TITLE
Error: Runtime compiler is not loaded - SharePoint app part using Angular 5.

### ISSUE THREAD

**Issue by KinsonDigital** [angular/angular#23757]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[X] Other... Please describe:
</code></pre>

## Current behavior

What kind of app this is: [SharePoint Web Part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part) that uses Angular 5.  Project is a standard SharePoint framework web part with that uses Angular 5 for the UI of the part.  This project was started and inspired from the project [here](https://winsmarts.com/use-spfx-with-angular-cli-3747c306244b?__s=ujmzcbbccb59epy74bpm).

Inspired From Project:
For instructions on project that inspired this one, click [here](https://winsmarts.com/use-spfx-with-angular-cli-3747c306244b?__s=ujmzcbbccb59epy74bpm).
Original Inspired GitHub Project [Here](https://github.com/maliksahil/SPFxAngularCLI)

## Expected behavior
Show new dynamic component with the updated HTML in the web part successfully without any errors.

Minimal reproduction of the problem with instructions
1. Download project from [here](https://github.com/KinsonDigital/WebPartCompileIssue).
2. run <code>npm install</code> to install all components.
3. run command <code>gulp serve</code> to spin up SharePoint web part server locally on a workbench page.  
NOTE: Changing code live while server is running can be done to update the page.
4.  To add part, follow steps below.
* Hover mouse over center of workbench page to show pic below.
![image](https://user-images.githubusercontent.com/4921022/39725461-e6610cba-5219-11e8-821d-8dee0062c31c.png)
* Click the + sign and choose the web part at the bottom of the list
![image](https://user-images.githubusercontent.com/4921022/39725504-09c52c72-521a-11e8-8aa0-de0331b8e889.png)
* The error in the developer tools console window will show 
![image](https://user-images.githubusercontent.com/4921022/39725607-66e716c2-521a-11e8-9b4f-f84fb208aec5.png)
---
FULL ERROR TEXT BELOW

Error: Runtime compiler is not loaded
Stack trace:
_throwError@https://localhost:4321/dist/hello-world-web-part.js:4028:11
Compiler</Compiler.prototype.compileModuleAndAllComponentsSync@https://localhost:4321/dist/hello-world-web-part.js:4094:15
RuntimeContentComponent</RuntimeContentComponent.prototype.createComponentFactorySync@https://localhost:4321/dist/hello-world-web-part.js:36511:22
RuntimeContentComponent</RuntimeContentComponent.prototype.compileTemplate@https://localhost:4321/dist/hello-world-web-part.js:36489:23
RuntimeContentComponent</RuntimeContentComponent.prototype.ngOnInit@https://localhost:4321/dist/hello-world-web-part.js:36482:9
checkAndUpdateDirectiveInline@https://localhost:4321/dist/hello-world-web-part.js:12660:9
checkAndUpdateNodeInline@https://localhost:4321/dist/hello-world-web-part.js:14184:20
checkAndUpdateNode@https://localhost:4321/dist/hello-world-web-part.js:14127:16
debugCheckAndUpdateNode@https://localhost:4321/dist/hello-world-web-part.js:15020:55
debugCheckDirectivesFn@https://localhost:4321/dist/hello-world-web-part.js:14961:13
View_AppComponent_0/<@https://localhost:4321/dist/hello-world-web-part.js:75753:611
debugUpdateDirectives@https://localhost:4321/dist/hello-world-web-part.js:14946:12
checkAndUpdateView@https://localhost:4321/dist/hello-world-web-part.js:14093:5
callViewAction@https://localhost:4321/dist/hello-world-web-part.js:14444:21
execComponentViewsAction@https://localhost:4321/dist/hello-world-web-part.js:14376:13
checkAndUpdateView@https://localhost:4321/dist/hello-world-web-part.js:14099:5
callWithDebugContext@https://localhost:4321/dist/hello-world-web-part.js:15347:39
debugCheckAndUpdateView@https://localhost:4321/dist/hello-world-web-part.js:14884:12
ViewRef_</ViewRef_.prototype.detectChanges@https://localhost:4321/dist/hello-world-web-part.js:11868:13
ApplicationRef</ApplicationRef.prototype.tick/<@https://localhost:4321/dist/hello-world-web-part.js:6198:58
ApplicationRef</ApplicationRef.prototype.tick@https://localhost:4321/dist/hello-world-web-part.js:6198:13
ApplicationRef</ApplicationRef.prototype._loadComponent@https://localhost:4321/dist/hello-world-web-part.js:6264:9
ApplicationRef</ApplicationRef.prototype.bootstrap@https://localhost:4321/dist/hello-world-web-part.js:6152:9
AppModule</AppModule.prototype.ngDoBootstrap@https://localhost:4321/dist/hello-world-web-part.js:75230:13
PlatformRef</PlatformRef.prototype._moduleDoBootstrap@https://localhost:4321/dist/hello-world-web-part.js:5875:13
PlatformRef</PlatformRef.prototype.bootstrapModuleFactory/</</<@https://localhost:4321/dist/hello-world-web-part.js:5793:21

---

## What is the motivation / use case behavior?
I have a piece of HTML from a server that I need to render.  This HTML can be changed on the server side essentially letting the person change the looks of the web part as well as the data that gets pulled in.  This HTML is used to dynamically create a component during run time and then showing this component in the web part.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [X] Chrome (desktop) version 66.0.3359.139 64-bit
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 59.0.3 64-bit
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X] IE version 11.371.16299.0 
- [X] Edge version 41.16299.3710.0
 
For Tooling issues:
- Node version: 8.11.1
- Platform:  Windows 10 Pro (10.0, Build 16299) - 64-bit

Others:

IDE: Visual Studio Code v1.23.0
OS: Windows 10 Pro (10.0, Build 16299) - 64-bit
HTTP Server: Built in gulp server that comes with SharePoint web part.
</code></pre>

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Maybe someone familiar with the Sharepoint setup like @wardbell or @johnpapa could help answering the question on StackOverflow. thanks!
