### ISSUE TITLE
Server tags being escaped and moved, worked in Angular 5

### ISSUE THREAD

**Issue by NebulaFox** [angular/angular#23751]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

In my index.html I had server preprocessing tags for Rails in the `head`. When I do `ng build --prod` my server tags are being escaped (<> -> \&lt;\&gt;) and moved to the `body` tag.

## Expected behavior

In Angular 5 this did not happen.

## Minimal reproduction of the problem with instructions

1. ng new <project>
2. open index.html
3. add `<%= csrf_meta_tags %>` to `head` tag
4. run `ng build --prod`
5. open index.html in `dist/`

## What is the motivation / use case for changing the behavior?

If this was intentional is there away to tell Angular not to escape these server tags in index.html?

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10  
- Platform: Mac 

Others:

</code></pre>

**Comment by matsko** [comment]
Moved to https://github.com/angular/angular-cli/issues/10819
