### ISSUE TITLE
Can't resolve '@angular/router/src/utils/collection'

### ISSUE THREAD

**Issue by bryanzavala** [angular/angular#23758]
Estoy intentando hacer un foreach y tengo este error.

![image](https://user-images.githubusercontent.com/33789256/39730722-e66b3758-5228-11e8-941c-a1037d5aa12a.png)
![image](https://user-images.githubusercontent.com/33789256/39730733-f51fdef2-5228-11e8-91a1-b9faa7fc5f4a.png)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

You're not suposed to import anything under `src/*`. That's private api.
