### ISSUE TITLE
CLI Build Optimization removes enum export from third party library

### ISSUE THREAD

**Issue by christopherthielen** [angular/angular#23759]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

A library in node_modules defines a typescript enum and exports it. 

```ts
export enum TransitionHookScope {
  TRANSITION,
  STATE,
}
```

The commonjs output is as follows:

```js
var TransitionHookScope;
(function (TransitionHookScope) {
    TransitionHookScope[TransitionHookScope["TRANSITION"] = 0] = "TRANSITION";
    TransitionHookScope[TransitionHookScope["STATE"] = 1] = "STATE";
})(TransitionHookScope = exports.TransitionHookScope || (exports.TransitionHookScope = {}));
```

In production mode, the build optimizer rewrites the enum to:

```
var TransitionHookScope = /*@__PURE__*/ (function (TransitionHookScope) {
    TransitionHookScope[TransitionHookScope["TRANSITION"] = 0] = "TRANSITION";
    TransitionHookScope[TransitionHookScope["STATE"] = 1] = "STATE";
    return TransitionHookScope;
})({});
```

*The enum is no longer exported because of the rewrite.*

## Expected behavior

An exported enum should be remain exported.

## Minimal reproduction of the problem with instructions

```
git clone https://github.com/christopherthielen/angular-enum-transform-problem.git
cd angular-enum-transform-problem
yarn
npx ng serve --prod
```

This repo is an angular-cli 6.0.0 app which imports `@uirouter/core` and references an enum in the app component:
```
import { TransitionHookScope } from '@uirouter/core';
...
export class AppComponent {
  title = TransitionHookScope.STATE;
}
```

Browse to the app and open the JS console.  Note the error:

```
main.ae05991ef8dcd02afa03.js:1 ERROR TypeError: Cannot read property 'STATE' of undefined
    at new <anonymous> (main.ae05991ef8dcd02afa03.js:1)
    at Ao (main.ae05991ef8dcd02afa03.js:1)
    at ko (main.ae05991ef8dcd02afa03.js:1)
    at ei (main.ae05991ef8dcd02afa03.js:1)
    at Jo (main.ae05991ef8dcd02afa03.js:1)
    at Object.vi [as createRootView] (main.ae05991ef8dcd02afa03.js:1)
    at t.create (main.ae05991ef8dcd02afa03.js:1)
    at t.create (main.ae05991ef8dcd02afa03.js:1)
    at e.bootstrap (main.ae05991ef8dcd02afa03.js:1)
    at main.ae05991ef8dcd02afa03.js:1
```

Now run `npx ng serve` (not production mode).  The app runs and prints the message `Welcome to 1!` (where `1` is a reference to the enum value).

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.0  
- Platform: Mac  

Others:

</code></pre>

Related to: 
https://github.com/angular/angular/issues/23400
https://github.com/angular/angular/issues/23739

**Comment by Iverson** [comment]
+1, have the same issue after migration to Angular 6.0.0 & CLI 6.0.0

**Comment by matsko** [comment]
Moved to https://github.com/angular/angular-cli/issues/10815
