### ISSUE TITLE
Release Schedule needs an update (again!)

### ISSUE THREAD

**Issue by sundarchi1** [angular/angular#23754]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
[Release Schedule](https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md) documentation is old and outdated with the v6 release now done.

## Expected behavior
It should be updated with the 6.1+ release schedule.

## Minimal reproduction of the problem with instructions
[Click here](https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md)

## What is the motivation / use case for changing the behavior?
So people know when to expect 6.1+.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
It should soon be removed [as per discussion](https://github.com/angular/angular/pull/23551#discussion_r185665072).

**Comment by BzenkoSergey** [comment]
I think it should be removed or updated.

It's not okay to see this.

![image](https://user-images.githubusercontent.com/5772034/39753407-5830e4e8-52c7-11e8-8c1c-6ca15a4f52c5.png)

**Comment by jenniferfell** [comment]
docsarea=releaseinfo

**Comment by jenniferfell** [comment]
Closed by PR https://github.com/angular/angular/pull/23808.

Angular team has decided to maintain public schedule of major releases in the Angular docs (under [Keeping Up-to-Date](https://angular.io/guide/releases)). That location is now current. Thanks!
