### ISSUE TITLE
add a new progressive view encapsulation 

### ISSUE THREAD

**Issue by zh99998** [angular/angular#23761]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

many of old (before angular was invented) components require a empty div, then script will append elements into it.
```html
<div id="candy"></div>
```
such components are hard to use in angular currently.

for `ViewEncapsulation.None` or import style globally in `style.css`/`angular.json`, component styles will leak out and cause global pollution.
for `ViewEncapsulation.Emulated`, the generated element does not have such ng scope attribute and can't apply styles.
for `ViewEncapsulation.Native`, styles are works well but script using `document.getElementByXXX` / `document.querySelector` can't find element.

## Expected behavior

here request for a new view encapsulation strategy.
add `_nghost-c*` to component host, but no `_ngcontent`.

```html
<component _nghost-c0></component>
```
then compile css styles as descendant selector

```css
_nghost-c0 a {
	color: #333;
	text-decoration: none;
}
```

most of old components could work under such encapsulation. and no style pollution.

**Comment by trotyl** [comment]
Technically `ViewEncapsulation.Emulated` is designed to be an exact emulation of `ViewEncapsulation.Native` for browsers which doesn't support Shadow DOM yet.

What you proposed can **ONLY** affects `ViewEncapsulation.Emulated`, but **NOT** `ViewEncapsulation.Native`, isn't it? I suspect that would be a big inconsistency issue as `ViewEncapsulation.Native` will got more preferred in the future.

**Comment by zh99998** [comment]
i'm proposed to add a NEW ViewEncapsulation strategy, not make change to ViewEncapsulation.Emulated.

**Comment by trotyl** [comment]
I meant that what you proposed has only interop with `ViewEncapsulation.Emulated`, but not `ViewEncapsulation.Native`. So it will become useless in the future as `ViewEncapsulation.Native` going to be the main option.

**Comment by trotyl** [comment]
@zh99998 `ViewEncapsulation` is **NEVER** designed to provide different behaviors, but to apply same behavior to different environments. And `ViewEncapsulation.Emulated` is a built-in polyfill for `ViewEncapsulation.Native`. And `_nghost`/`_ngcontent` is how this polyfill works.

The problem of your scenario is that the elements were not created by `Renderer2.createElement`, so the styling doesn't applies.

**Comment by zh99998** [comment]
`ViewEncapsulation is NEVER designed to provide different behaviors`

so why there is a `ViewEncapsulation.None`.
it a different behavior, for convenience, aha?

**Comment by mlc-mlapis** [comment]
@zh99998 ... because it means: **Don't use encapsulation at all?**

**Comment by trotyl** [comment]
https://github.com/angular/angular/blob/77ff72f93b86e57ba3fdc67a60a5b00c69c9a824/packages/compiler/src/directive_normalizer.ts#L186-L189

> so why there is a ViewEncapsulation.None.

It mean: "I want to speed up the framework as knowing that it will be same with or without encapsulation". I know it's already got abused now.

**Comment by pcroc** [comment]
I think the desired effect can be achieved by using `ViewEncapsulation.Emulated` and placing all of your style rules within :host ::ng-deep like this:

```
:host ::ng-deep {
  a {
    color: #333;
    text-decoration: none;
  }
}
```

Result:
```
[_nghost-c25] a {
  color: #333;
  text-decoration: none; }
```
