### ISSUE TITLE
AngularJS expression is visible on https://angular.io/about/

### ISSUE THREAD

**Issue by ronilichtman** [angular/angular#2376]
When clicking on a contributor image the first time you are provided by a description like so:
![working](https://cloud.githubusercontent.com/assets/12766460/8012323/465061ce-0bc9-11e5-9ef9-257d8b96fea3.PNG)

When you click on the image a second (or more) time, you are provided with the following:
![not-working](https://cloud.githubusercontent.com/assets/12766460/8012329/58affd02-0bc9-11e5-8aa6-18497bc4bbd2.PNG)

**Comment by splintercode** [comment]
This issue can be closed see related issue on https://github.com/angular/angular.io/issues/132 
and commit https://github.com/jackmu95/angular.io/commit/1315b757876e0cabb233e31c4d210391e148d1fd

**Comment by pkozlowski-opensource** [comment]
Thnx @splintercode !
