### ISSUE TITLE
Package "@angular/flex-layout" has an incompatible peer dependency to "rxjs" (requires "^5.5.0", would install "6.1.0").

### ISSUE THREAD

**Issue by ishankhare07** [angular/angular#23765]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

```
$  ng -v
Angular CLI: 6.0.0
Node: 8.11.1
OS: linux x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@angular/cdk                      5.2.5
@angular/cli                      6.0.0
@angular/flex-layout              5.0.0-beta.14
@angular/material                 5.2.5
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              5.5.10
typescript                        2.5.3
webpack                           4.6.0

$ ng update @angular/core
Package "@angular/flex-layout" has an incompatible peer dependency to "rxjs" (requires "^5.5.0", would install "6.1.0").
Incompatible peer dependencies found. See above.

```

## Expected behavior

Following instructions from `update.angular.io` . Should work fine without this error.

## Minimal reproduction of the problem with instructions

I think this might be because angular/flex-layout 6.0.0 is still in beta - [see here](https://github.com/angular/flex-layout/releases). If so, does it makes sense to install flex-layout's nightly builds by `npm install angular/flex-layout-builds --save`, as the [installation docs](https://github.com/angular/flex-layout/wiki/Using-Angular-CLI#install-flex-layout) says:
> This installs a nightly build which incorporates the latest updates not yet published to NPM

## What is the motivation / use case for changing the behavior?

Upgrading from v5.2 to v6.0 by following instructions from update.angular.io

## Environment

<pre><code>
Angular version: 5.2.10

Browser:
- [x] Chrome (desktop) version 66.0.3359.139 
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 59.0.2
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1  
- Platform: Linux(ubuntu 16.04) 

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
There's no need to open this issue here since it's a problem with flex-layout package. Track the issue in flex-layout's repo 👍 .

**Comment by Mani-RRI** [comment]
working packages versions of **@angular/flex-layout@^2.0.0-beta.9** :

npm install --save @angular/animations@^4.4.5 @angular/cdk@^2.0.0-beta.12 @angular/common@^4.4.5 @angular/compiler@^4.4.5 @angular/core@^4.4.5 @angular/flex-layout@^2.0.0-beta.9 @angular/forms@^4.4.5 @angular/http@^4.4.5 @angular/material@^2.0.0-beta.12 @angular/platform-browser@^4.4.5 @angular/platform-browser-dynamic@^4.4.5 @angular/router@^4.4.5 core-js@^2.5.1 hammerjs@^2.0.8 ngx-restangular@^1.0.11 rxjs@^5.4.3 zone.js@^0.8.18

working packages versions of **@angular/flex-layout@^6.0.0-beta.15 ** :

"@angular/animations": "^6.0.1", "@angular/cdk": "^6.0.0", "@angular/common": "^6.0.0", "@angular/compiler": "^6.0.0", "@angular/core": "^6.0.0", "@angular/flex-layout": "^6.0.0-beta.15", "@angular/forms": "^6.0.0", "@angular/http": "^6.0.0", "@angular/material": "^6.0.1", "@angular/platform-browser": "^6.0.0", "@angular/platform-browser-dynamic": "^6.0.0", "@angular/router": "^6.0.0", "core-js": "^2.5.4", "hammerjs": "^2.0.8", "rxjs": "^6.0.0", "zone.js": "^0.8.26" }, "devDependencies": { "@angular/compiler-cli": "^6.0.0", "": "~0.6.1", "typescript": "~2.7.2", "@angular/cli": "~6.0.1", "@angular/language-service": "^6.0.0", "": "~2.8.6", "": "~2.0.3", "": "~8.9.4", "codelyzer": "~4.2.1", "jasmine-core": "~2.99.1", "jasmine-spec-reporter": "~4.2.1", "karma": "~1.7.1", "karma-chrome-launcher": "~2.2.0", "karma-coverage-istanbul-reporter": "~1.4.2", "karma-jasmine": "~1.1.1", "karma-jasmine-html-reporter": "^0.2.2", "protractor": "~5.3.0", "ts-node": "~5.0.1", "tslint": "~5.9.1"

good luck!
