### ISSUE TITLE
angular 6 cli error

### ISSUE THREAD

**Issue by gyansoft786** [angular/angular#23768]
![angular 6 cli error](https://user-images.githubusercontent.com/7090767/39756234-60755156-52e6-11e8-883f-da3287ff2e6a.PNG)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Please report this in angular-cli's repo, and also respect the issue template. Thanks 👍
