### ISSUE TITLE
Angular 6 layout changes: all 4px gaps removed between inline or inline-block elements

### ISSUE THREAD

**Issue by jostschmithals** [angular/angular#23764]
## Description of the problem:

Angular 6 removes all 4px gaps which the browser puts by default between inline or inline-block elements when there are line breaks in the code.

Since this changed behavior seems not to be documented, I wonder whether it is intended?

This might well be considered a desired feature, but in general I would expect that I can rely on the fact that my layouts won't change unspokenly when I update a project to Angular 6.

## Minimal reproduction of the problem:

This code snippet in a fresh project `(ng new ...`) - it doesn't matter where it is placed - ...

```
span {
  background: limegreen;
  padding: 5px;
}
```

```
<span>Test</span>
<span>Test</span>
<span>Test</span>
<span>Test</span>
<span>Test</span>
```
... produces these outputs ...

1. with Angular 5 (like in normal HTML):

![ng5](https://user-images.githubusercontent.com/5700294/39745067-86c89aba-52a6-11e8-8914-107872128789.JPG)

2. with Angular 6:

![ng6](https://user-images.githubusercontent.com/5700294/39745078-8c1ad92e-52a6-11e8-99b8-e97334493426.JPG)

**Comment by trotyl** [comment]
Expected behavior: https://github.com/angular/angular/issues/22027

**Comment by jostschmithals** [comment]
Thanks for the quick response! - I found this now in the changelog under "small features/preserveWhitespaces". So my only suggestion would be to point it out more clearly, since in unlucky circumstances it could break layouts.

**Comment by gravityctrl** [comment]
I tried adding `"angularCompilerOptions": { "preserveWhitespaces": true }` to `tsconfig.json` and `tsconfig.app.json`. It won't work for me.

**Comment by topce** [comment]
@gravityctrl  for me as well setting it on global level in tsconfig it does not work
@IgorMinar maybe this is new bug for angular cli team , not sure did not check if it is already reported
@gravityctrl if you set it up on Component level it should work OK ie preserve white spaces

**Comment by mischah** [comment]
Whoa. That’s a hell of a breaking change. I don’t get why they choose to default it to be that aggressive in removing whitespace. The default should be the other way round.

Anyways. Here is the how to fix that …

## Solution

According to [stackoverflow](https://stackoverflow.com/a/46619232/702783).

### For JIT Compiling

Add `{ preserveWhitespaces: false }` as an option to the `bootstrapModule()` method in **main.ts**:

```javascript
platformBrowserDynamic().bootstrapModule(AppModule, { preserveWhitespaces: false });
```

### For AOT Compiling

Add `"angularCompilerOptions": { "preserveWhitespaces": false }` to **tsconfig.app.json**:

```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts"
  ],
  "angularCompilerOptions": {
    "preserveWhitespaces": false
  }
}
```

**Comment by skjelbek** [comment]
@mischah Thanks! Even though I'm sure you mean `{ preserveWhitespaces: true }`.

**Comment by simeyla** [comment]
One of the beauties of Angular templates is that whitespace gets stripped out, so you can format your code on multiple lines with humanly readable indentation. 

So globally setting whitespace settings could lead to much less efficient code elsewhere. 

If you don't have an massive existing codebase, you can add a space within the span:

```
<div *ngIf="address.countryCode == 'US'">
    <span>{{ address.city }} </span>
    <span>{{ address.stateCd }} </span>
    <span>{{ address.zipOrPostal }} </span>
</div>
```

Interestingly this collapses completely as if the `<span> </span>` wasn't even there!

```
<div *ngIf="address.countryCode == 'US'">
    <span>{{ address.city }}</span>
    <span> </span>
    <span>{{ address.stateCd }}</span>
    <span> </span>
    <span>{{ address.zipOrPostal }}</span>
</div>
```

**Comment by ricardosaracino** [comment]
this really screws with i18n
