### ISSUE TITLE
Angular 6 production output code generate ReferenceError

### ISSUE THREAD

**Issue by kennyrulez** [angular/angular#23766]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When building a project in angular 6, using ng-buld --prod, the output generate an error. The offending error is: 
`ReferenceError: must call super constructor before using |this| in Ti class constructor`.
The generated, offending code is
```
class Ei {
    constructor(l, n=Ei.now) {
    this.SchedulerAction = l,
    this.now = n
            }
            schedule(l, n=0, e) {
                return new this.SchedulerAction(this,l).schedule(e, n)
            }
        }
        Ei.now = Date.now ? Date.now : ()=>+new Date;
        class Ti extends Ei {
            constructor(l, n=Ei.now) {
                this.actions = [],
                this.active = !1,
                this.scheduled = void 0
            }
            schedule(l, n=0, e) {
                return Ti.delegate && Ti.delegate !== this ? Ti.delegate.schedule(l, n, e) : super.schedule(l, n, e)
            }
            flush(l) {
                const {actions: n} = this;
                if (this.active)
                    return;
                let e;
                this.active = !0;
                do {
                    if (e = l.execute(l.state, l.delay))
                        break
                } while (l = n.shift());if (this.active = !1,
                e) {
                    for (; l = n.shift(); )
                        ;
                    throw e
                }
            }
        }
```
precisely:
``` 
  constructor(l, n=Ei.now) {
        this.actions = [], <----
       .....
```

if I issue the output with
`ng build --prod --build-optimizer=false`
no error and application works, but obviously the size of the bundle is higher.

NOTE: this issue is related to Angular 6. Angular 5.2.10 compile and run without errors or warnings.

## Minimal reproduction of the problem with instructions
It seems to be related to how code is uglyfied, not my code itself.

## Environment
<pre><code>
Angular CLI: 6.0.0
Node: 10.0.0
OS: linux x64
Angular: 6.0.0
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
</code></pre>

**Comment by skreborn** [comment]
@kennyrulez See https://github.com/angular/angular-cli/issues/7799#issuecomment-386582136.

**Comment by kennyrulez** [comment]
@skreborn ok thanks for pointing me out. Closing issue!
