### ISSUE TITLE
Serviceworker Fail Safe Removal does NOT work

### ISSUE THREAD

**Issue by aavelyn** [angular/angular#23767]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Following the description on removing (fail safe) serviceworkers by renaming or removing the ngsw-config file causes the building process to "fail". 

>  Expected to find an ngsw-config.json configuration file in the /Users/hanche/Desktop/Development/playground/toggl2 folder. Either provide one or disable Service Worker in your angular.json configuration file.

A Dist folder is still being emitted, but obviously without a ngsw-worker.js causing the client to throw a 404 on ngsw-worker.js instead of the ngsw.json.

## Expected behavior

Building process without error emiting a dist folder which includes a ngsw-worker.js which deregisters any previously installed service workers.

## Minimal reproduction of the problem with instructions

create new app with angular cli, 
add service worker, 
rename/remove ngsw-config.json, 
ng build --prod

## Environment

<pre><code>
Angular version: 5.2.10 and 6.0.0

Browser:
- [x] Chrome (desktop) version 66
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.0.0
- Platform: Mac

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by aavelyn** [comment]
@mhevery, I do not fully understand your reasoning for closing this issue.

If I have already deployed apps with angular service workers and they behave faulty on for example updates ([Stackoverflow](https://stackoverflow.com/questions/50161482/angular-cli-update-service-worker-id-of-undefined-error?noredirect=1#comment87480246_50161482) or #23742)
then I need a safe way to remove service workers with the next update.

Under the Serviceworker Section (https://angular.io/guide/service-worker-devops#service-worker-safety) you have listed methods on how to remove the serviceworkers, of which one does not work.

**Comment by gkalpak** [comment]
@aavelyn, this is a typo in the documentation. You should remove `ngsw.json` (from `dist/`), not `ngsw-config.json`. Would you be up to submitting a pull request to fix the docs? (This is the file that needs editing: https://github.com/angular/angular/blob/master/aio/content/guide/service-worker-devops.md)
