### ISSUE TITLE
 Problem loading the main.js file

### ISSUE THREAD

**Issue by Espi13** [angular/angular#23769]
I changed the configuration of system-config.js as they put in another issue but it did not work. Also, check that the name of the tsconfig.json file was fine.

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

![04576c7a77c8ad69e2731e824a070f49](https://user-images.githubusercontent.com/25864885/39757314-c2567f4a-52cc-11e8-8159-10d9515d8c6a.png)

## Environment

<pre><code>
Angular version: 5.2.3

Browser:
- [ x] Chrome (desktop) version 66.0.3359.139
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10 
- Platform:  Windows

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
