### ISSUE TITLE
Deep link of dynamic routes not available until next visit

### ISSUE THREAD

**Issue by DevCeN** [angular/angular#23760]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

With dynamic children routes in a lazy loaded module, visiting a direct deep link to one of these children routes (either via the browser URL input or via routerLink) will throw NoMatch exception the first visit, but normal on second visit. Comparing to a lazy loaded module with static children routes, there is no such issue on first and subsequent visits.

## Expected behavior

Lazy loaded module with dynamic children routes should perform the same as lazy loaded module with static children routes, where visiting a direct deep link to one of the children routes should allow loading of the module and allow setting up the dynamic children routes then check from there before deciding if it is a NoMatch.

## Minimal reproduction of the problem with instructions

Example: https://stackblitz.com/edit/angular-xvmi8t
Steps to reproduce:
Scenario 1
1. Click on the [Go to lazy-normal child page(Good)] link, expect the route reaches [PASS]
2. Click on the [Go to lazy-dynamic child page(Fail)] link, expect the route reaches [FAIL]
3. Click on the [Go to lazy-dynamic child page(Fail)] link again, expect the route reaches [PASS]

Scenario 2
1. Click on the [Go to lazy-dynamic page(Good)] link, expect the route reaches [PASS]
2. Click on the [Go to lazy-dynamic child page(Fail)] link, expect the route reaches [PASS]

## What is the motivation / use case for changing the behavior?

Able to dynamically setup children routes for lazy loaded module

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by zolekm** [comment]
It looks similar to this issue which i report: https://github.com/angular/angular/issues/23740

**Comment by atscott** [comment]
Hi, after a bit more investigation, this seems to be working as expected. As the router is processing the route which is `loadChildren` you change it in your module to be `children` instead. It's kind of like deleting the items in an array while you're doing a `forEach` -- this can't be expected to work.

What you can do instead is provide your dynamic routes using the `ROUTES` multi provider (this is what the `RouterModule.forChild` is doing anyways)

```

@NgModule({
  imports: [RouterModule.forChild([]), CommonModule],
  providers: [
     [{provide: ROUTES, multi: true, useFactory: getDynamicRoutes, deps: [SomeService]}]
  ],
  declarations: [LazyComponent, TestComponent, DefaultComponent],
  entryComponents: [LazyComponent, TestComponent, DefaultComponent]
})
export class LazyDynamicModule {
}
```

See this example: https://stackblitz.com/edit/angular-hidmsp?file=src%2Flazy-dynamic%2Flazy-dynamic.module.ts
