### ISSUE TITLE
Property 'map' does not exist on type 'Observable<Response>'.  Angular 6

### ISSUE THREAD

**Issue by mattbuzz94** [angular/angular#23778]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
## Current behavior
After update my angular cli global and create a new project I'm getting a erro in my services:
Property 'map' does not exist on type 'Observable<Response>'.

Folllow my code:
`import { Injectable } from '@angular/core';
import { environment } from '../../environments/environment';

import { Http, Response } from '@angular/http';
import { Chamado } from './chamado';
import { Observable } from 'rxjs';
import 'rxjs/add/operator/map';
import { map } from 'rxjs/operators';
import 'rxjs/add/operator/map';

const API_URL = environment.apiUrl;

@Injectable()
export class ChamadoService {

    constructor(
        private http: Http
    ) {
    }
    private chamados: Chamado[]; // Lista de usuários

    // API: GET /Chamados
    public getAllChamados(): Observable<Chamado[]> {
        return this.http
            .get(API_URL + 'chamados/555699/')
            .map(response => {
                const chamados = response.json();
                // return chamados.map((chamado) => new Chamado(chamado));

            })
            .catch(this.handleError);
    }

    public getChamados(textoBusca: string, projeto: string): Observable<Chamado[]> {
        return this.http
            .get(API_URL + 'chamados/busca/?' + textoBusca + '?' + projeto)
            .map(response => {
                const chamados = response.json();
                return chamados.map((chamado) => new Chamado(chamado));
            })
            .catch(this.handleError);
    }
    private handleError(error: Response | any) {
        console.error('ApiService::handleError', error);
        return Observable.throw(error);
    }
}
`
## Expected behavior
I've already imported these packages, but doesn't work anyway
import { Observable } from 'rxjs';
import 'rxjs/add/operator/map';

Follow my package.json:
`{
  "name": "project-support",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "bootstrap": "^4.1.1",
    "core-js": "^2.5.4",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.0",
    "@angular/cli": "^6.0.0",
    "@angular/compiler-cli": "^6.0.0",
    "@angular/language-service": "^6.0.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }
}
`
Angular version: 6.0.0
 
For Tooling issues:
- Node version: v8.11.1
- Platform:  Windows 7

Tks for any help.

**Comment by Toxicable** [comment]
This isn't an issue with Angular.
Check the rxjs migration guide https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md

-----
It should be:
```
return this.http
  .get(API_URL + 'chamados/busca/?' + textoBusca + '?' + projeto).pipe(
    map(response => {
      const chamados = response.json();
      return chamados.map((chamado) => new Chamado(chamado));
    })
    catchError(this.handleError);
```

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mattbuzz94** [comment]
@Toxicable tks for your help !

**Comment by Rename94** [comment]
npm install --save rxjs-compat@6 SOLVED

**Comment by BKYoseph** [comment]
Thank you for a wonderful solution

**Comment by crazy3553** [comment]
Good Solution @Rename94

**Comment by b4youleap** [comment]
Migration guide moved to https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md
