### ISSUE TITLE
Angular 6.0.0 --base-href, --deploy-url no longer works as expected.

### ISSUE THREAD

**Issue by truginis** [angular/angular#23773]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

After upgrading to Angular 6 the --base-href and --deploy-url no longer work as expected.

I am running ```ng build --base-href /virtualDir --deploy-url /virtualDir --prod``` command to build the app which used to work in angular 5.2 without a problem. Now it tries to grab runtime.js, styles.js, main.js and polyfill.js without adding **/** after the base-href so it just ends up getting a 404 error.

Used to be: *https://mydomain.com/virtualDir/styles.08dcsetc.css*
Now it is: *https://mydomain.com/virtualDirstyles.08dcsetc.css*

Notice the missing **/** between virtualDir and styles.08dcsetc.css

If i add the **/** to the end of base-href and deploy-url, the main files get loaded but then every call to an API fails because and extra **/** gets added to every request.

The api calls look like this: 
https://mydomain.com/virtualDir//api//someEndpoint

## Expected behavior

Should load all required files from https://mydomain.com/virtualDir/

## Minimal reproduction of the problem with instructions

Not sure how to reproduce this on stackblitz.com.

But this is the simples one i can come up with. 

* Create virtual directory on your server
* Have a node instance running in that directory with following setup
```
const express = require('express');
const api = require('./api');
const path = require('path');

const app = express();
const port = process.env.PORT || 3000;
const virtualDirPath = process.env.virtualDirPath || '';

// static files (all angular stuff)
app.use(virtualDirPath, express.static(path.join(__dirname, 'dist')));
// Handles all api routes
app.use(`${virtualDirPath}/api`, api);

app.listen(port, () => {
  console.log(`listening on ${port}`);
});
```
* Build and deploy angular app to said virtual directory with --base-href and --deploy-url set to your virtual dir
* Try to run it.

## What is the motivation / use case for changing the behavior?

Would like to be able to run multiple apps on same domain within virtual directories. 

## Environment

<pre><code>
Angular version: 6.0.0
Node: 8.11.1

Browser:
- [X] Chrome (desktop) version XX
- [X] Chrome (Android) version XX
- [X] Chrome (iOS) version XX
- [X] Firefox version XX
- [X] Safari (desktop) version XX
- [X] Safari (iOS) version XX
- [X] IE version XX
- [X] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1  
- Platform:  Mac 

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Please report cli's issues in its repo https://github.com/angular/angular-cli 👍

**Comment by truginis** [comment]
Thanks, my bad somehow my brain skipped the part where cli would be responsible.
