### ISSUE TITLE
Add support for TypeScript 2.8

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#23779]
Typescript 2.8 info:
- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html
- https://blogs.msdn.microsoft.com/typescript/2018/03/27/announcing-typescript-2-8/

Typically a TypeScript update means the following things:

- [x] ensure that tsickle is compatible with the new version of typescript
- [x] ensure that rxjs is compatbile
- [x] update our main [package.json](https://github.com/angular/angular/blob/77ff72f93b86e57ba3fdc67a60a5b00c69c9a824/package.json#L117) and yarn.lock to reflect the typescript 2.8 dependency
- [x] add a new test for ts28 similar to https://github.com/angular/angular/tree/77ff72f93b86e57ba3fdc67a60a5b00c69c9a824/integration/typings_test_ts27
- [x] ensure that our codebase can compile with typescript 2.8. Usually the tighter compiler checks surface preexisting errors that we need to fix in a way that
  - doesn't change our public api
  - doesn't make our published d.ts files incompatible with typescript 2.7
- [x] ensure that our code that users TS AST and compiler apis are compatible (primarily compiler-cli and language-service) - if we need to make any updates we need to make sure that we remain both 2.7 and 2.8 compatible.
- [ ] point out anything Angular-specific and noteworthy that we need to let Angular developers know when they update to 2.8 (new flags, etc)

Previous PR with 2.7 update just for reference: https://github.com/angular/angular/pull/22669

**Comment by IgorMinar** [comment]
@LucasSloan has offered to take this one on, @alxhub can you please help with code reviews? thanks!

**Comment by LucasSloan** [comment]
There was a previous issue #23092, could you merge or link or whatever?

**Comment by IgorMinar** [comment]
Bah! I knew there was an issue for this already but search couldn't find
it. I deduped the issues. Thanks

**Comment by sundarchi1** [comment]
[2.9 out now](https://blogs.msdn.microsoft.com/typescript/2018/05/31/announcing-typescript-2-9/) FYI

**Comment by MrWolfZ** [comment]
Is someone still working on this? Or are you looking for contributors?

**Comment by sarunint** [comment]
@MrWolfZ It has been done in #23782 and is scheduled for v6.1.

**Comment by alan-agius4** [comment]
This is already been done in master branch ie for v6.1.X

https://github.com/angular/angular/pull/23782

**Comment by MrWolfZ** [comment]
Great news, thanks for the info. Could this issue then be closed to avoid confusion? It is still popping up as the second result on Google for me when searching for "Angular TypeScript 2.8".

**Comment by trotyl** [comment]
But this is a checklist, one can found which parts have already been done.

**Comment by gkalpak** [comment]
Is there anything left to do here, @IgorMinar?
The only remaining item is:

> point out anything Angular-specific and noteworthy that we need to let Angular developers know when they update to 2.8 (new flags, etc)

**Comment by ericmartinezr** [comment]
Should this one be superseded by https://github.com/angular/angular/pull/24652 ?

**Comment by sundarchi1** [comment]
+1 for #24652 replacing this.
Please don't release 6.1 with TS 2.8 only!

**Comment by ohjames** [comment]
When installing the 6.1.0-beta.2:

```
warning "@angular-devkit/build-angular > @ngtools/webpack@6.1.0-rc.0" has incorrect peer dependency "typescript@~2.4.0 || ~2.5.0 || ~2.6.0 || ~2.7.0".
```

Can I ignore this warning or is typescript 2.8 not available in the released version? If not, do you know which version of angular ts 2.8 will be supported from?

**Comment by vladimiry** [comment]
@ohjames try to put `disableTypeScriptVersionCheck` option into your `tsconfig.json`
```json
  "angularCompilerOptions": {
    "disableTypeScriptVersionCheck": true
  }
```

**Comment by ohjames** [comment]
@vladimiry I don't think that's even needed, it's just a warning from yarn/npm about peer dependency being violated. I can ignore it but I'm not sure if ts 2.8 is supported by the current 6.1 beta (mostly due to this peer dependency).

**Comment by vladimiry** [comment]
> but I'm not sure if ts 2.8 is supported by the current 6.1 beta

IMHO, you can't know that for sure until it's officially stated by Angular team.

Btw I go with latest TS and Angular versions and usually it works well, like now using TS 2.9.2 and Angular 6.0.6, have not tried beta though.

**Comment by zuozhiw** [comment]
@vladimiry I'm struggling to combine the latest version of typescript (TS 2.9.2 currently) and the latest Angular version (it needs TS 2.7.2). I did what you said: `disableTypeScriptVersionCheck` in `tsconfig.json`, and I also disabled the `typescriptMismatch` warning in Angular CLI. 

However, when I do `ng serve`, I get this error `ERROR in The Angular Compiler requires TypeScript >=2.7.2 and <2.8.0 but 2.9.2 was found instead.`It seems like I need to install the peer dependency for Angular compiler on my own. Could you please guide me on how to do this, or point me to some online resources? Thanks

**Comment by vladimiry** [comment]
@zuozhiw I don't use CLI, but use compiler [directly](https://github.com/vladimiry/protonmail-desktop-app/blob/master/src/webpack/web.ts) in Webpack config. Based on the information you provided it looks like `angularCompilerOptions.disableTypeScriptVersionCheck` option didn't take an affect. I'd suggest to double check that you changed a right `tsconfig.json` file. You can also debug it (at least using `console.log` approach), see related code line in my previous comment.

**Comment by gkalpak** [comment]
I am closing this, since it seems to be complete. (@IgorMinar, reopen if not.)
There is a separate issue for tracking problems with TS 2.9: #25141
