### ISSUE TITLE
Search in Angular 2 Archive Site Broken

### ISSUE THREAD

**Issue by firstdivision** [angular/angular#23780]
## I'm submitting a Documentation Error / Bug in the Angular 2 Documentation Archive
<pre><code>[X ] Documentation issue or request
</code></pre>

## Current behavior
- Go to https://v2.angular.io/docs/ts/latest/
- Type "ngfor" into search box
- Hit enter
- Nothing happens

## Expected behavior
A result for "ngfor" should appear

## Minimal reproduction of the problem with instructions
See "Current Behavior" above

## What is the motivation / use case for changing the behavior?
Some of us still have to maintain Angular 2 applications

## Environment
Angular version: 2

Browser:
- [X ] Chrome (desktop) version XX
- [X ] IE version 11

**Comment by petebacondarwin** [comment]
Closing as we are very unlikely to change this. OK @StephenFluin ?

**Comment by firstdivision** [comment]
lol closed as "We don't feel like fixing it, sucks for you that you actually have to maintain a giant app in our  mistake called Angular 2"

**Comment by firstdivision** [comment]
Yes, I know how to use Google, I'd much rather use your actual documentation.  I'f you're not going to fix it then remove the search tool instead of leaving it broken.  And I'm sorry for the snarky response.  But I'm very frustrated that my job is more and more becoming "fixing things that the framework designers change" instead of actually writing new features.  

Kind of like how I always add "-angularjs" and select the "in the past year" option  to all my searches because if you search for "angular" you get old information.  All we do now is fix things that have been "upgraded".

**Comment by firstdivision** [comment]
I apologize again.  I'm just exhausted from being assigned to too many projects, all using different technologies, and not being able to find the answers to my questions.   It's not your fault, I'm sure you guys are in the same position of being pulled in too many directions.

**Comment by petebacondarwin** [comment]
@firstdivision I appreciate your honesty and openness and I am sorry that you are stressed and frustrated. Hopefully the workaround will provide you with an option to keep you moving at least.
