### ISSUE TITLE
Passing observable through 2 methods does not work

### ISSUE THREAD

**Issue by BorntraegerMarc** [angular/angular#23787]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I'm getting the following exception when I pass up an observable over 2 methods:
```
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at HttpRequest.serializeBody (http.js:916)
    at Observable._subscribe (http.js:2196)
    at Observable._trySubscribe (Observable.js:172)
    at Observable.subscribe (Observable.js:160)
    at Object.subscribeToResult (subscribeToResult.js:23)
    at MergeMapSubscriber._innerSub (mergeMap.js:132)
    at MergeMapSubscriber._tryNext (mergeMap.js:129)
    at MergeMapSubscriber._next (mergeMap.js:112)
    at MergeMapSubscriber.Subscriber.next (Subscriber.js:90)
```

If I call the method `post2` (see below) directly in the `login` function then everything works and I see the success message.

## Expected behavior

No exception should occur.

## Minimal reproduction of the problem with instructions

I have the following template & method:
```
<button (click)="login()">Click me</button>
```
inside the login method:
```
public login(): void {
  this.webService
    .post('auth/login', { username: this.username, password: this.password })
    .subscribe((data: any) => {
       console.log('sucess');
     }, (err: any) => {
        console.log('errror');
  });
}
```

And then in the web service:
```
public post(url: string, body: any): Observable<any> {
  return this.post2(url, body);
}
```

and the 2nd method:
```
public post2(url: string, body: any): Observable<any> {
  return this.http.post('/auth/login', body);
}
```

If I call the method `post2` directly in the `login` function then everything works and I see the success message.

## Environment

<pre><code>
Angular version: 5.2.7

Browser:
- [X] Chrome (desktop) version 66
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8  
- Platform: Mac 

Others:

</code></pre>

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by BorntraegerMarc** [comment]
ok, sorry for bothering
