### ISSUE TITLE
this.httpClient.get('....').let ????

### ISSUE THREAD

**Issue by RayLuxembourg** [angular/angular#23788]
why i can't do that? i want to create reusable pipe and give it to all my httpClient calls ...

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
