### ISSUE TITLE
Loading chunk failed when scripts are included through another http server

### ISSUE THREAD

**Issue by rishabh-94** [angular/angular#23793]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[X ] Other... Please describe:
</code></pre>

## Current behavior

I am running the angular app with ng serve on port 4200 and another http server on port 8080.
Using lazy loading, the chunk tries to load through port localhost:8080

## Expected behavior

The chunk should be loaded correctly through port localhost:4200 (the port that the angular-app is being served on)

## Minimal reproduction of the problem with instructions

Run ng serve in angular app which has lazy loaded modules. Include 
```
        <script type="text/javascript" src="http://localhost:4200/inline.bundle.js"></script>
        <script type="text/javascript" src="http://localhost:4200/polyfills.bundle.js"></script>
        <script type="text/javascript" src="http://localhost:4200/styles.bundle.js"></script>
        <script type="text/javascript" src="http://localhost:4200/vendor.bundle.js"></script>
        <script type="text/javascript" src="http://localhost:4200/main.bundle.js"></script>
```
on the html page of another http server. Navigate to the lazy loaded module and see that loading of common.chunk.js and lazy-loaded.module.js has failed
## What is the motivation / use case for changing the behavior?

It should load through the correct port depending on what port the angular app is being served from

## Environment

<pre><code>
Angular version: 5.2.10

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.4  
- Platform:   Windows

Others:

</code></pre>

**Comment by matsko** [comment]
Moved to https://github.com/angular/angular-cli/issues/10814
