### ISSUE TITLE
Shortdate wrong format in fr locale

### ISSUE THREAD

**Issue by Hanfrey** [angular/angular#23790]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The date pipe returns `09/05/2018` for shortdate
Like declared [here](https://github.com/angular/angular/blob/b0eca85e5187fbfe2f2edd02327ce2fc6f0e196b/packages/common/locales/fr.ts#L40)

## Expected behavior

'shortDate': equivalent to 'M/d/yy' (e.g. 6/15/15). 

## Minimal reproduction of the problem with instructions
{{today | date:'shortDate'}}

## What is the motivation / use case for changing the behavior?

Align with other languages

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 

Others:

</code></pre>

**Comment by trotyl** [comment]
It's defined by CLDR:

https://github.com/unicode-cldr/cldr-dates-full/blob/f58498912ff14da83ebed3309c3c2085b89fa4da/main/fr/ca-gregorian.json#L366

**Comment by vicb** [comment]
This is how we write dates in French.
