### ISSUE TITLE
Docs: Practical observable usage: Type ahead suggestions has incorrect import

### ISSUE THREAD

**Issue by jfrei** [angular/angular#23803]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

In the Angular Guide section Observables & RxJS, in the Practical observable usage page: https://angular.io/guide/practical-observable-usage#type-ahead-suggestions

Line 1 of the TypeAhead code example is:

`import { fromEvent } from 'rxjs';`

Which is not a correct import if you've followed the guide for creating a new Angular project. It currently throws an error which states that **Module 'myApp/node_modules/rxjs/Rx' has no exported member 'fromEvent'**

## Expected behavior

Line 1 of the TypeAhead code example should import from observable:

`import { fromEvent } from 'rxjs/observable/fromEvent';`

## What is the motivation / use case for changing the behavior?

After scouring Google and StackOverflow for a correct resolution to the problem, I did not find an ample solution. Hoping to save people lots of time digging through if your Google-foo is not quite perfect (As in my case)

## Environment

<pre><code>
Angular version: 5.0.5

Browser:
- [X] Chrome (desktop) version 66
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.10.0  
- Platform: Windows 

Others:

</code></pre>

**Comment by sarunint** [comment]
The documentation website of in https://angular.io is now based on Angular v6, which is depend on RxJS v6.

RxJS v6 deprecates many import paths from v5. Please make sure you visit the v5 version of the documentation, or upgrade to Angular v6 to take advantages of the new features.

**Comment by jfrei** [comment]
Doh! Thanks for the enlightenment :)
