### ISSUE TITLE
Path to ngsw-config.json

### ISSUE THREAD

**Issue by zygimantas** [angular/angular#23816]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
</code></pre>

## Current behavior

ngsw-config.json must be in src/ directory

## Expected behavior

angular.json may configure multiple apps, so the path ngsw-config.json should be configurable

## What is the motivation / use case for changing the behavior?

ngsw-config.json should not be shared across different apps;
file name should be configurable;

## Environment

<pre><code>
Angular version: 6.0.0

</code></pre>

**Comment by pkozlowski-opensource** [comment]
This belongs to https://github.com/angular/angular-cli, please open there

**Comment by splincode** [comment]
https://github.com/angular/angular-cli/issues/9949

**Comment by splincode** [comment]
@zygimantas You can usage ngw (webpack configuration modifier for @angluar/cli):
https://github.com/Angular-RU/angular-cli-webpack
