### ISSUE TITLE
Angular 5 update to 6

### ISSUE THREAD

**Issue by pacozevallos** [angular/angular#23823]
In the process of updating my version of Angular from 5 to 6 something I did wrong and ended up getting the following errors:

npm WARN checkPermissions Missing write access to / usr / local / lib / node_modules / @ angular / cli
npm WARN checkPermissions Missing write access to / usr / local / lib / node_modules / @ angular
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-pre-gyp@^0.9.0 (node_modules / @ angular / cli / node_modules / fsevents / node_modules / node-pre-gyp):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ELOOP: too many symbolic links found, open '/usr/local/lib/node_modules/@angular/cli/node_modules/fsevents/node_modules/node-pre-gyp/npm-shrinkwrap.json'

npm ERR! path / usr / local / lib / node_modules / @ angular / cli
npm ERR! code ELOOP
npm ERR! errno -62
npm ERR! syscall access
npm ERR! ELOOP: too many symbolic links encountered, access '/ usr / local / lib / node_modules / @ angular / cli'

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/pacozevallos/.npm/_logs/2018-05-10T16_23_40_078Z-debug.log

In any case how can I delete it and reinstall it?

I have Node 8.11.1 and my system is MacOS High Sierra 10.13.4

Any idea how I can solve it?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
