### ISSUE TITLE
Angular 5 ng build --prod error

### ISSUE THREAD

**Issue by shariqshahzad** [angular/angular#23821]
**Current behavior**
ERROR in : Can't resolve all parameters for TouchSystemsService in E:/TSProjects/TouchSystemsRetail/Code/TS.Web.UI/client-src/app/shared/services/touch-systems.service.ts: ([object Object], ?, [object Object]).

**Expected behavior**
It should build without any errors
it used to show this as a warning like "WARN : Can't resolve all parameters for TouchSystemsService in E:/TSProjects/TouchSystemsRetail/Code/TS.Web.UI/client-src/app/shared/services/touch-systems.service.ts: ([object Object], ?, [object Object]) this will be an error in angular 5"

I cant find any solution to this neither on github nor on stackoverflow

Windows 10 , Visual Studio 2017 , npm , server on .net core 

this is my service:

`export class TouchSystemsService extends BehaviorSubject<any>{
    baseUrl: string ;

    constructor(public http: HttpClient, private apiEndPoint: string, private configService: ConfigService) {
        super(null);
        this.baseUrl = '/api';

    }
    public fetchById(id: number, state?: State): Observable<any>
    {
        if (!state) {
            let options = this.CreateHeaders();
            return this.http.get<any>(`${this.baseUrl}/${this.apiEndPoint}/${id}`, options);
        }
        const queryStr = `${toDataSourceRequestString(state)}`;
        const hasGroups = state.group && state.group.length;
        let options = this.CreateHeaders();

        let result = this.http.get<any>(`${this.baseUrl}/${this.apiEndPoint}/${id}?${queryStr}`, options);
        return result;
    }`

it is not an injectable service it is a base service inherited by other service like this 

`export class SizeService extends TouchSystemsService {

    dataResult: GridDataResult;

    constructor(http: HttpClient, configService: ConfigService) {
        super(http, 'size', configService);
    }

    public read(id:number): Observable<GridDataResult> {
        return this.fetchById(id);
    }`

Angular: 5.2.10

Browser:
- [ ] Chrome (desktop) version  66.0.3359.139
 
For Tooling issues:
- Node version: v8.11.1
- Platform:  Windows

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
