### ISSUE TITLE
Implicit global variables not accepted after angular 6 upgrade

### ISSUE THREAD

**Issue by maximedupre** [angular/angular#23824]
## I'm submitting a...
<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Errors at compilation every where a global variable is used, e.g.

    ERROR in src/app/components/base.ts(35,13): error TS2304: Cannot find name '$'.

To avoid this error, the global variable needs to be imported somewhere, such as in the module (`app.module.ts`), e.g.

    import * as $ from 'jquery';

## Expected behavior
Implicit global variables should not give an error when used, just like with previous angular versions. In other words, global variables that are declared in scripts that are loaded by angular `angular.json -> projects[0].architect.build.scripts` should be useable right away.

The required type definitions are installed (e.g. `@types/jquery"`)

If helpful:

Here is my `/tsconfig.json`

    {
        "compileOnSave": false,
        "compilerOptions": {
            "baseUrl": "./",
            "outDir": "./dist/out-tsc",
            "sourceMap": true,
            "declaration": false,
            "moduleResolution": "node",
            "emitDecoratorMetadata": true,
            "experimentalDecorators": true,
            "target": "es5",
            "typeRoots": [
                "node_modules/@types"
            ],
            "lib": [
                "es2017",
                "dom"
            ]
        }
    }

Here is my `/src/tsconfig.app.json`

    {
      "extends": "../tsconfig.json",
      "compilerOptions": {
        "outDir": "../out-tsc/app",
        "module": "es2015",
        "types": []
      },
      "exclude": [
        "src/test.ts",
        "**/*.spec.ts"
      ]
    }

## Environment
<pre><code>
Angular version: 6.0.0

Browser:
- [X] Chrome (desktop)

**Comment by IgorMinar** [comment]
This might be a change introduced by Typescript 2.8.

However this is the expected behavior because you are depending on an ambient type that should be introduced via "types" property in tsconfig - I see that you don't have it. If you update your tsconfig the issue should go away without the extra imports in your app code.

**Comment by maximedupre** [comment]
Isn't it sufficient to specify

        "typeRoots": [
            "node_modules/@types"
        ]

as I did in my `/tsconfig.json`?
