### ISSUE TITLE
remove background from app icon 144x144

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#23827]
## I'm submitting a...
[X] Bug report  

## Current behavior
When a device (such as a pixelbook or ChromeOS device) installs the angular.io PWA, the icon shows up with a white border.

The icon being used is here: https://angular.io/assets/images/favicons/apple-touch-icon-144x144.png

## Expected behavior
The icon should have a transparent background.

## Minimal reproduction of the problem with instructions
Visit angular.io on a chromebook. Install the PWA:
![image](https://user-images.githubusercontent.com/165056/39889371-858332da-544c-11e8-9de7-e5b875b28d50.png)

**Comment by gkalpak** [comment]
For reference:
The [194x194 icon][1] _does_ have a transparent background. The [144x144 "apple-touch" icon][2] (added in 53f57d74b) does _not_.

[1]: https://github.com/angular/angular/blob/4ecae6449e459e638215a193b6c20aa37587eeec/aio/src/assets/images/favicons/favicon-194x194.png
[2]: https://github.com/angular/angular/blob/4ecae6449e459e638215a193b6c20aa37587eeec/aio/src/assets/images/favicons/apple-touch-icon-144x144.png
