### ISSUE TITLE
ERROR TypeError: Cannot read property 'cin' of undefined     at Object.eval [as updateDirective

### ISSUE THREAD

**Issue by jozifen** [angular/angular#23830]
<hey there ,
I'm working on angular project , so I wanna update a user by transformings his data to a form BUT I keep getting this error all the time:

```
ERROR TypeError: Cannot read property 'cin' of undefined
    at Object.eval [as updateDirective
```
cin is the id of the user
can anybody help me???

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
