### ISSUE TITLE
Output property name in Component Interaction guide doesn't match styleguide

### ISSUE THREAD

**Issue by collink** [angular/angular#23831]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently the [Component Interaction](https://angular.io/guide/component-interaction#parent-listens-for-child-event) contains an output property whose name does not match [convention established in the styleguide](https://angular.io/guide/styleguide#dont-prefix-output-properties).

## Expected behavior
The output property in the example is currently defined as follows:

```
@Output() onVoted = new EventEmitter<boolean>();
...
<app-voter *ngFor="let voter of voters"
      [name]="voter"
      (onVoted)="onVoted($event)">
```

According to the styleguide, it should instead be:

```
@Output() voted = new EventEmitter<boolean>();
...
<app-voter *ngFor="let voter of voters"
      [name]="voter"
      (voted)="onVoted($event)">
```

## What is the motivation / use case for changing the behavior?

The verbiage on [this subject in the styleguide](https://angular.io/guide/styleguide#dont-prefix-output-properties) is concrete:

> Do name events without the prefix on.

> Do name event handler methods with the prefix on followed by the event name.

**Comment by jenniferfell** [comment]
filename=https://angular.io/guide/component-interaction

**Comment by brandonroberts** [comment]
Fixed via https://github.com/angular/angular/commit/88ab1d0e553238f45e16fabd208134f836564a63
