### ISSUE TITLE
Base URL support in templates and stylesheets

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2384]
# GOAL

Add support to the template/stylesheets for base URL so that components can refer to resources in relative paths.

## Problem

```
-- components
  +-- zippy.ts
  +-- zippy.html
  +-- zippy.css
  +-- zippy.gif
```

where:

`zippy.ts` 
```typescript
@Component()
@View({
  moduleId: module.id, // see #2383
  templateUrl: 'zippy.html',
  styleUrls: ['zippy.css']
})
class Zippy {}
```

`zippy.html`
```html
...
<!-- THIS WILL NOT WORK -->
<img src="zippy.gif">

<!-- WE NEED TO SUPPORT THIS -->
<img src="$baseUrl/zippy.gif">
...
```

```stylesheet
selector {
  backround-url: 'zippy.gif', # DOES NOT WORK
  backround-url: '$baseUrl/zippy.gif', # WORKS
}
```

## Why prefix `$baseUrl` and not do it automatically?
We need to mark attributes that take relative urls in html files explicitly, as we don't know which attributes are urls and which ones are not. 
Also, in html files we could have something like `<img src="$baseUrl/{{img}}.gif">`

## Solution

* Compute the `baseUrl` from the module, see #2383 
* search `template` and `stylsheets` for `$baseUrl` and replace with URL form the module

**Comment by rolandjitsu** [comment]
Will this solve the issue of resolving the path for a template relative to the component instead of writing the full path?
E.g.:
```js
@Component({
	selector: 'app'
})
@View({
	templateUrl: 'components/app/app.html',
	directives: []
})
class App {}
```
vs.
```js
@Component({
	selector: 'app'
})

@View({
	templateUrl: './app.html',
	directives: []
})
class App {}
```

**Comment by mhevery** [comment]
@rolandjitsu you are looking for #2383

**Comment by mhevery** [comment]
FYI @vicb updated the description

**Comment by rolandjitsu** [comment]
@mhevery thanks, both this one and the other you pasted are great ideas :)

**Comment by rolandjitsu** [comment]
@mhevery I just had a thought while playing with components. Whenever I load a stylesheet within a template using `<style>@import "app.css";</style>`, I experience some flickering. I suppose that is due to the delay of the stylings being loaded and then applied to the DOM.

If so, the current proposal, will it fix this issue? Otherwise may I suggest delaying DOM injection until the styles have been loaded to avoid this flickering (there is a very obvious delay, e.g. the text is black for a few milliseconds and then suddenly it changes to the color the styling says it should be)?

**Comment by mhevery** [comment]
@rolandjitsu see #1694

**Comment by vicb** [comment]
@rolandjitsu 
> I experience some flickering

This will be fixed with by #2563 fixing #1694

**Comment by vicb** [comment]
@mhevery do we actually need this for css ? we already resolve `url(...)` and `url('./path')` is much nicer than `$baseUrl/path' IMO.

**Comment by vicb** [comment]
As indicated in my comment above, I'm not sure if this issue makes sense for styles. Html should be enough.

**Comment by naomiblack** [comment]
@tbosch can you pick this one up from @vicb or reassign?

**Comment by alxhub** [comment]
I've determined how I'm going to do this - `$basePath` will be string-replaced into the HTML string during ViewLoader._loadHtml with the relative base path of the template file (if loaded from a template URI) or the component (if the template is inlined).

**Comment by adamduren** [comment]
Does this feature still exist? I tried it in a component I am building and get a 404 with the `$baseUrl` not substituted.

![image](https://cloud.githubusercontent.com/assets/581097/17553825/db2a2d1a-5ed5-11e6-8e02-d7f82e9dfd91.png)

**Comment by adamduren** [comment]
@alxhub
