### ISSUE TITLE
[Docs] Optional dependencies with @Inject decorator

### ISSUE THREAD

**Issue by IlCallo** [angular/angular#23849]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior
`@Inject(Token, null)` fires a TypeScript error `expected 1 arguments, but got 2` at build time

## Expected behavior
The token should be optional, as stated in the [docs](https://angular.io/guide/dependency-injection#optional-dependencies)

## Minimal reproduction of the problem with instructions
Create an Angular project
Create an InjectionToken
Inject the token into a component constructor using `@Inject(Token, null)`
Try to build

## What is the motivation / use case for changing the behavior?
I'm trying to create a library which takes a provider (with `multi` option) defined in other libraries/modules used in the same project to build up automatically the web-app structure.
This provider can also be null, if there are no modules defining it inside the project.

## Environment

<pre><code>
Angular version: 6.0.0

 
For Tooling issues:
- Node version: 9.3.0
- Platform:  Windows

Others:

Visual Studio Code
TypeScript 2.8.3
</code></pre>

**Comment by trotyl** [comment]
Doc change made by https://github.com/angular/angular/pull/23027, don't think this usage ever being supported.

**Comment by jenniferfell** [comment]
docsarea=di
filename=https://angular.io/guide/dependency-injection#optional-dependencies
Confirmed this change was introduced in v6 tree-shakable provider doc update.

**Comment by yogeshgadge** [comment]
`@Optional()` does not work with `@Inject(MY_TOKEN)` / compile

neither `@Inject(Token,null)` version `6.0.5`

**Comment by alxhub** [comment]
@jenniferfell correct, this is a docs issue. To my knowledge `@Inject` has never taken a second argument.

The correct code here is:
```
@Optional() @Inject(MY_TOKEN) token: IToken
```

Note the syntax listed is wrong in more ways than one. In the docs currently there isn't even a parameter name.

**Comment by jenniferfell** [comment]
@jbogarthyde Please make sure this is addressed in your DI rewrite. Thanks! https://github.com/angular/angular/pull/21915

**Comment by jbogarthyde** [comment]
In the current rewrite of the DI Guide, the @Inject example does not have the spurious 2nd arg

The API doc seems to define it correctly. However, I have started a rewrite of all the DI-decorator API doc --  https://github.com/angular/angular/pull/24744

**Comment by csbenjamin** [comment]
I don't know if here is the right place to post this. 
If I do
```typescript
export class MyService {
    constructor(@Optional() @Inject('MY_STRING_TOKEN') private myOptionalService) {}
}
```
and I don't provide 'MY_STRING_TOKEN', the app works as expected and I have `this.myOptionalService === null'. But if I do the following 

```typescript
export const MY_NON_STRING_TOKEN = new InjectionToken<string>('MY_NON_STRING_TOKEN');
export class MyService {
    constructor(@Optional() @Inject(MY_NON_STRING_TOKEN') private myOptionalService) {}
}
```
even if I do provide something with thisi token, angular throw a error: Can't resolve all parameters for MyService: (?). What am'I missing? I am using Angular 6.0.9

**Comment by jbogarthyde** [comment]
@alxhub Can you help with this question?

**Comment by jbogarthyde** [comment]
You have an unmatched single quote on `MY_NON_STRING_TOKEN'`

**Comment by csbenjamin** [comment]
@jbogarthyde This was just a typo while submitting here in github. In my actually implementation there isn't the typo.

**Comment by kapunahelewong** [comment]
I can't find `@Inject()` with two arguments in the docs. @IlCallo it seems like this was resolved, unless I'm missing something. I'm interested on anyone's thoughts here. If it's resolved (which I suspect), I'd like to close this, but if not, I'd be happy to submit a PR.

**Comment by IlCallo** [comment]
Yes, it has been removed with https://github.com/angular/angular/commit/2379ad1a4bc527be4b45bf6a697d9de1be481685

**Comment by ggradnig** [comment]
@csbenjamin It seems to be related to the target of the TS build. When changing it from `es5` to `es6`, it works, because constants are supported there.
