### ISSUE TITLE
url encode let router not found

### ISSUE THREAD

**Issue by ICTlight** [angular/angular#23848]
I am using NG4 cli to manage project. But i found a matter.When i make a url with 
params like this :

`http://localhost:8080/dap#/console/report?repId=95b7c142-ef1f-4ea9-b908-5dcb3c88422b&ha=no`;

          the bower will encode it to:

 `http://localhost:8080/dap#/console/report%3Frepld%3D95b7c142-ef1f-4ea9-b908-5dcb3c88422b%26ha%3Dno`

this make the router cannot found the component

What's wrong? How to fixed it ??   TKS

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by matsko** [comment]
As @ericmartinezr pointed out, the issue doesn't follow the template. Closing.
