### ISSUE TITLE
Error: No provider for e! with prod flag(working fine in local server)

### ISSUE THREAD

**Issue by Jackeysharath** [angular/angular#23846]
Can someone tell me the solutions here is my code?
working fine with local server,
when I move to hosting server the following error arises.
Error: No provider for e!
at _e (vendor.c6cd506179cfc8072419.bundle.js:1)
at vendor.c6cd506179cfc8072419.bundle.js:1
at e._throwOrNull (vendor.c6cd506179cfc8072419.bundle.js:1)
at e._getByKeyDefault (vendor.c6cd506179cfc8072419.bundle.js:1)
at e._getByKey (vendor.c6cd506179cfc8072419.bundle.js:1)
at e.get (vendor.c6cd506179cfc8072419.bundle.js:1)
at wo (vendor.c6cd506179cfc8072419.bundle.js:1)
at vendor.c6cd506179cfc8072419.bundle.js:1
at Mo (vendor.c6cd506179cfc8072419.bundle.js:1)
at wo (vendor.c6cd506179cfc8072419.bundle.js:1)

**## versions**
Angular CLI: 1.7.4
Node: 6.10.1
OS: win32 x64
Angular: 4.4.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, tsc-wrapped

@angular/cdk: 5.2.5
@angular/cli: 1.7.4
@angular/material: 5.2.5
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.3.4
webpack: 3.11.0

## package.json

{
  "name": "cemsdemo",
  "version": "0.0.1",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --port 7777 --host 192.168.0.169 --open",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.4.7",
    "@angular/cdk": "^5.2.5",
    "@angular/common": "^4.4.7",
    "@angular/compiler": "^4.4.7",
    "@angular/core": "^4.4.7",
    "@angular/forms": "^4.4.7",
    "@angular/http": "^4.4.7",
    "@angular/material": "^5.2.5",
    "@angular/platform-browser": "^4.4.7",
    "@angular/platform-browser-dynamic": "^4.4.7",
    "@angular/router": "^4.4.7",
    "@ng-idle/core": "^2.0.0-beta.15",
    "@ng-idle/keepalive": "^2.0.0-beta.15",
    "@nicky-lenaers/ngx-scroll-to": "^0.6.1",
    "@types/jquery": "^3.3.1",
    "angular2-cookie": "^1.2.6",
    "angular2-moment": "^1.9.0",
    "angular4-datepicker": "^1.0.1",
    "angular4-slimscroll": "^1.0.5",
    "angularfire2": "^4.0.0-rc0",
    "core-js": "^2.5.6",
    "firebase": "^4.13.1",
    "font-awesome": "^4.7.0",
    "intl": "^1.2.5",
    "ng2-owl-carousel": "^0.1.15",
    "ngx-loading": "^1.0.14",
    "ngx-mydatepicker": "^2.4.5",
    "ngx-pagination": "^3.1.1",
    "rxjs": "^5.5.10",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "^1.7.4",
    "@angular/compiler-cli": "^4.4.7",
    "@angular/language-service": "^4.4.7",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^6.0.109",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.4.2",
    "karma-jasmine": "^1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.3.3"
  }
}

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by matsko** [comment]
Please produce a reproduction with a specific issue. Closing.
