### ISSUE TITLE
Cannot read property 'map' of undefined in service-worker-config.umd.js

### ISSUE THREAD

**Issue by andredlam** [angular/angular#23857]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

After upgraded from version 5 to latest version 6.0.0 (then tried 6.0.1)

When run "ng build --prod", it gives the following error:

```
Cannot read property 'map' of undefined
TypeError: Cannot read property 'map' of undefined
    at ../node_modules/@angular/service-worker/bundles/service-worker-config.umd.js:292:38
    at Array.map (<anonymous>)
    at Generator.processDataGroups (../node_modules/@angular/service-worker/bundles/service-worker-config.umd.js:289:42)
    at Generator.<anonymous> (../node_modules/@angular/service-worker/bundles/service-worker-config.umd.js:227:50)
    at step (../node_modules/@angular/service-worker/bundles/service-worker-config.umd.js:72:23)
    at Object.next (../node_modules/@angular/service-worker/bundles/service-worker-config.umd.js:53:53)
    at fulfilled (../node_modules/@angular/service-worker/bundles/service-worker-config.umd.js:43:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)

Here is my package.json:

"dependencies": {
    "@angular-devkit/core": "^0.6.0",
    "@angular-devkit/schematics": "^0.6.0",
    "@angular/cdk": "^6.0.1",
    "@angular/common": "^6.0.1",
    "@angular/core": "^6.0.1",
    "@angular/flex-layout": "^6.0.0-beta.15",
    "@angular/forms": "^6.0.1",
    "@angular/http": "^6.0.1",
    "@angular/language-service": "^6.0.1",
    "@angular/material": "^6.0.1",
    "@angular/platform-browser": "^6.0.1",
    "@angular/platform-browser-dynamic": "^6.0.1",
    "@angular/router": "^6.0.1",
    "@angular/service-worker": "^6.0.1",
    "@ng-bootstrap/ng-bootstrap": "^2.0.0",
    "@schematics/angular": "^0.6.0",
    "@schematics/package-update": "^0.6.0",
    "@schematics/schematics": "^0.6.0",
    "@swimlane/ngx-datatable": "^12.0.0",
    "ajv": "^6.5.0",
    "autoprefixer": "^8.4.1",
    "bootstrap": "^4.1.1",
    "core-js": "^2.5.6",
    "hammerjs": "^2.0.8",
    "jquery": "^3.3.1",
    "ngx-cookie-service": "^1.0.10",
    "perfect-scrollbar": "^1.3.0",
    "popper.js": "^1.14.3",
    "rxjs": "^6.1.0",
    "rxjs-compat": "^6.1.0",
    "screenfull": "^3.3.2",
    "tether": "^1.4.4",
    "yarn": "^1.6.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.6.0",
    "@angular/animations": "^6.0.1",
    "@angular/cli": "^6.0.1",
    "@angular/compiler": "^6.0.1",
    "@angular/compiler-cli": "^6.0.1",
    "@types/jasmine": "^2.8.7",
    "@types/jasminewd2": "^2.0.3",
    "@types/node": "^10.0.6",
    "codelyzer": "^4.3.0",
    "jasmine-core": "^3.1.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^2.0.2",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^1.0.1",
    "karma-coverage-istanbul-reporter": "^1.4.2",
    "karma-jasmine": "^1.1.2",
    "karma-jasmine-html-reporter": "^1.1.0",
    "protractor": "^5.3.2",
    "ts-node": "^6.0.3",
    "tslint": "^5.10.0",
    "typescript": "^2.7.2"
  }
```
## Environment

<pre><code>
Angular version: 6.0.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ x] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  9.8.0  
- Platform:  Mac 

Others:

</code></pre>

**Comment by gkalpak** [comment]
The error occurs on [this line][1]. (This hasn't changed from 5.x, but maybe the CLI code that generates the `Config` - i.e. converts `ngsw-config.json` to a JS object - is less forgiving now.)

In any case, it sounds like you using a `data-group` without specifying a `urls` array, which is not correct (since `urls` is a required property). See the [guide][3] for more info.

[1]: https://github.com/angular/angular/blob/cfde36da84b5de5248e1cdea932fc75c57ee078c/packages/service-worker/config/src/generator.ts#L80
[2]: https://github.com/angular/angular/blob/5c89d6bffab52176e4afdfff1b71645cbba9bd47/packages/service-worker/config/src/generator.ts#L79-L80 
[3]: https://angular.io/guide/service-worker-config#datagroups
