### ISSUE TITLE
Missmatch v6 aot documentation and update.angular.io 5.2 to 6.0

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#23854]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

In documentation for AOT options for `preserveWhitespaces` is stated **As of v6, this option is false by default, which results in smaller emitted template factory**, but in angular update guide on http://update.angular.io is stated **Choose a value of off preserveWhitespaces in your tsconfig.json to gain the benefits of this setting while the default is still to preserve whitespace.**

Which one is true?

## Expected behavior

It should be same.

## Environment

<pre><code>
Angular version: 6.0.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
It's a problem of [Angular update guide](https://github.com/StephenFluin/angular-update-guide) application, the recommendations are just summary from the start version to end version, there's no smart filter to ignore some of them.

The [specific rule](https://github.com/StephenFluin/angular-update-guide/blob/17362367d231ea2a2be31868ed5cad2582432869/src/app/recommendations.ts#L41) is not actually for v6.

**Comment by jenniferfell** [comment]
docsarea=updating

**Comment by jenniferfell** [comment]
Confirmed that the default was changed to false for v6: https://github.com/angular/angular/pull/22046

https://github.com/angular/angular/blob/master/packages/compiler/src/config.ts
export function preserveWhitespacesDefault(
    preserveWhitespacesOption: boolean | null, defaultSetting = false): boolean {
  return preserveWhitespacesOption === null ? defaultSetting : preserveWhitespacesOption;
}

**Comment by StephenFluin** [comment]
Clarified in https://github.com/StephenFluin/angular-update-guide/commit/8e6eda5387766db0ff812b895d57c601585cc771
