### ISSUE TITLE
Using a selector of "listing" causes all block level elements to render their white space.

### ISSUE THREAD

**Issue by sstriano** [angular/angular#23862]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When adding a selector to a component, setting the name of the selector to "listing" causes all the block level elements on the page to render their white space.

If you name it something else like "l0sting", the white space disappears and is no longer rendered.

When you add spaces in the markup, line breaks, etc, the white space increases accordingly.

Are there a set of reserved words in selector names you shouldn't use?

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [x ] Chrome (desktop) version 66.0.3359.139
 
For Tooling issues:
- Platform:  Windows

Others:

</code></pre>

**Comment by matsko** [comment]
@sstriano no there shouldn't be any reserved component keywords. Could you add a stackblitz.com link?

**Comment by vicb** [comment]
This is not specific to Angular.

`<listing>` is an actual HTML element, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/listing

You should prefix your component with `somePrefix-` if you want to make sure there is no collision.
