### ISSUE TITLE
feature: ability to resize the left navigation pane

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#23860]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[X ] Other... Please describe: AIO feature request
</code></pre>

## Current behavior

The width of the left navigation pane is fixed on desktop viewing in web browsers. One user ended up in a situation where the nav titles wrapped, even though we try to keep the titles short and on one-line in most browsers

## Expected behavior

It would be nice if users could drag to make the left navigation pane a bit narrower or wider, to fix wrap-around issues with long titles. We could set a min and max to avoid serious problems, but give the user some control. 

## What is the motivation / use case for changing the behavior?

See above. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser: 
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sjtrimble** [comment]
@jenniferfell I find this to not be very standard and also not quite usable on any mobile devices (tablets and phones).

I tried to reproduce and wasn't able to. Are you able to reproduce any sidenav text wrapping? I think this is fairly standard (example: https://firebase.google.com/docs/cloud-messaging/js/send-multiple -> see highlighted active sidenav menu item).
