### ISSUE TITLE
Angular fails silently when paragraph tags contain unordered list

### ISSUE THREAD

**Issue by Legion6789** [angular/angular#23864]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

If a component template has an unordered list inside paragraph tags, Angular fails silently. To be clear an error is displayed in the browser console, but the Angular CLI displays "Compiled successfully."

## Expected behavior

If strict adherence to HTML spec is desired an error should be emitted instead of just receiving a blank page with nothing on the CLI. If strict adherence is not a priority it should render as expected, which is how Chrome, Firefox and Edge handle it.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-gitter-9btizb?file=app%2Fapp.component.html

## Environment

<pre><code>
Angular version: 6.0.1

Browser:
- [x] Chrome (desktop) version 66.0.3359.139
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by matsko** [comment]
Hello @Legion6789.

Angular's HTML parser strictly follows how the HTML5 validator works and, as it turns out, including block-level HTML tags (like `ul`, `div`, `p`) inside of a `p` tag isn't valid. This is why Angular doesn't allow it.

You can try pasting the following HTML code into the validator (https://validator.w3.org/nu/#textarea)
```html
<!DOCTYPE html>
<html lang="en-US">
<head>
<title>foo</title>
</head>
<body>
<p>
  <ul>
    <li>foo</li>
  </ul>
</p>
</body>
</html>
```
