### ISSUE TITLE
[Angular doc] "import { Observable, of } from 'rxjs';" is not the correct from. 

### ISSUE THREAD

**Issue by wangju1111** [angular/angular#23867]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
In Doc link: https://angular.io/tutorial/toh-pt4#observable-data
import { Observable, of } from 'rxjs';

## Expected behavior
import { Observable } from 'rxjs/Observable';

import { of } from 'rxjs/observable/of';

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
The guide is currently using Angular 6 which depends on RxJS 6. You can see the migration guide from rxjs5 to 6 here https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md ([this will be useful too](https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md))

**Comment by jenniferfell** [comment]
@wangju1111 Thank you for your feedback. 
@ericcarraway Thank you for helping us out with the v5 - v6 note. 
I confirmed with @jasonaden , and this is correct for v6, so I'm closing. Thanks again, all!

**Comment by jlopezfdez** [comment]
Hi, 
I had some issues with "import { Observable, of } from 'rxjs';" as well, but for me the solution was easy:

1) From  'Angular Tour of Heroes'  tutorial, in section "2. The application Shell',

   right after doing 'cd angular-tour-of-heroes', 

   ---> install 'rxjs' library by running:

           npm install rxjs

  that will install 'node_modules/rxjs' folder (at least) and then "import { Observable, of } from 'rxjs';" will work and won't show any error in your favourite code editor (VS Code in my case).
