### ISSUE TITLE
Angular Route fails if added parameter with hyphen

### ISSUE THREAD

**Issue by infomahendra2009** [angular/angular#23870]
Hi Angular,

I Want to this website convert  in angular 5 or 6 any version but  i  am facing url problems

old url like this
https://www.distancesfrom.in/rajasthan/distance-from-tamtiya-to-banswara-h-o/27872.html
https://www.distancesfrom.in/rajasthan/distance-from-chordi-to-bhoyar/15072.html

here static contnet https://www.distancesfrom.in/rajasthan/distance-from-(*)-to-(*)/(*).html 

Client says url parameters can not change because all page links already index in google so,
Can u snuggest me how can convert url like this in angular.

Thanks 
Mahendra

**Comment by dawidgarus** [comment]
You can try custom `UrlMatcher`: https://angular.io/api/router/UrlMatcher
If that won't work, maybe You can change URL and send http 301 response with redirection for old URLs. Your page should not be penalized by google for that.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
