### ISSUE TITLE
Request: I18n for update.angular.io with open-sourcing

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#23873]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe: 
</code></pre>

## Current behavior

https://update.angular.io is very useful and important resource for all Angular developers. But it's not open source, so it's difficult to localize for non-English.

## Expected behavior

The best is open source repository and use Angular i18n API. then I will be able to contribute to improving localization of my locale.

Or, if it will be public repo, I can fork it for my locale. it's enough better than now.

## What is the motivation / use case for changing the behavior?

I'm organizing https://angular.io localization in Japanese, https://angular.jp. 
And now, for our community and Angular ecosystem, I think I should create `update.angular.jp` , too.

cc/ @StephenFluin

**Comment by ericmartinezr** [comment]
https://github.com/StephenFluin/angular-update-guide

**Comment by lacolaco** [comment]
Oh, I was looking for that in `angular/**` repo. Thank you @ericmartinezr !

**Comment by lacolaco** [comment]
So I wonder why is it in Stephen's repo still. It has official `angular.io` domain today.  why not `angular/angular-update-guide` ?

**Comment by jenniferfell** [comment]
docsarea=update
docsarea=translation

**Comment by StephenFluin** [comment]
@lacolaco The plan is to move it to the angular/angular repo in the future, this just hasn't happened yet.

Internationalization should actually be very easy if we focus on the steps themselves. I've created https://github.com/StephenFluin/angular-update-guide/issues/17 to follow up.
