### ISSUE TITLE
Angular 5/6 - DecimalDelimiter from Locale

### ISSUE THREAD

**Issue by Luke-1988** [angular/angular#23874]
Hi guys,

I do use Date or Number pipe which does job very well, but when I need convert these dates or numbers from strings (ie. from inputs) back to date or number, I need support for locale specific conversion. Either any Angular built-in function which supports converts (parsers) based on Locale or I am going to build own and therefore I need Locale specific configuration like Decimal Delimiter, Date format etc. 

1) does Angular have such built-in functions (convert / parse)?
2) if no, how can I get locale specific configuration (decimal delimiter, date format)

Thanks!

**Comment by lazarljubenovic** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by vicb** [comment]
The exposed information are available via https://github.com/angular/angular/blob/master/packages/common/src/i18n/locale_data_api.ts (also check the different filers in this folder).
