### ISSUE TITLE
Compile exception

### ISSUE THREAD

**Issue by xtqjh** [angular/angular#23879]
Compile to 92% exceptions

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'builda' ]
2 info using npm@5.6.0
3 info using node@v8.2.1
4 verbose run-script [ 'prebuilda', 'builda', 'postbuilda' ]
5 info lifecycle new-admin@0.0.0~prebuilda: new-admin@0.0.0
6 info lifecycle new-admin@0.0.0~builda: new-admin@0.0.0
7 verbose lifecycle new-admin@0.0.0~builda: unsafe-perm in lifecycle true
8 verbose lifecycle new-admin@0.0.0~builda: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/xtqjh/Sites/sdzh/new-admin/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle new-admin@0.0.0~builda: CWD: /Users/xtqjh/Sites/sdzh/new-admin
10 silly lifecycle new-admin@0.0.0~builda: Args: [ '-c',
10 silly lifecycle   'node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --prod --build-optimizer' ]
11 silly lifecycle new-admin@0.0.0~builda: Returned: code: 1  signal: null
12 info lifecycle new-admin@0.0.0~builda: Failed to exec builda script
13 verbose stack Error: new-admin@0.0.0 builda: `node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --prod --build-optimizer`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:921:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid new-admin@0.0.0
15 verbose cwd /Users/xtqjh/Sites/sdzh/new-admin
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "builda"
18 verbose node v8.2.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error new-admin@0.0.0 builda: `node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --prod --build-optimizer`
22 error Exit status 1
23 error Failed at the new-admin@0.0.0 builda script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
