### ISSUE TITLE
Angular 5: Route transition to ' ' takes long time

### ISSUE THREAD

**Issue by LeoIV** [angular/angular#23888]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
To perform the routing, I have a link that is defined as follows:

`<a [routerLink]="['/']"><i class="fa fa-angle-left mb-3" aria-hidden="true"></i> back</a>`

My router config looks as follows:

```
const routes: Routes = [
  {path: '', component: SearchComponent, data: {state: 'overview'}},
  {path: 'detailpage/:id', component: DetailComponent, data: {state: 'detail'}},
];
```

In my index.html, I have my base url defined as `<base href="./">.`

Do you have an idea, why this globalZoneAwareCallback function takes such a long time (it might seem tolerable, but it is really slow on less powerful computers - about 2 seconds)? 

<pre><code>
Angular version: 5.2.10

Browser: Browser independent
![grafik](https://user-images.githubusercontent.com/13868691/39984734-6739c5c4-575c-11e8-85e0-0cb4c230a967.png)

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
