### ISSUE TITLE
how external JS file transfer data with component in angular4 program？

### ISSUE THREAD

**Issue by NobodyXiao** [angular/angular#23880]
1.First of all, the business is like this. We now need to write some js libraries for others to use, and the back end can give this written script string to us through HTTP requests, and we parse the scripts and execute the related logic.

second, the script that others call contains some code that controls the logic of the user, and of course they use our library, but the scripts they write can operate display, so we should transfer data of component to external js and we need also transfer data of external js to inner component.

so what we are going to do now is to know what the correct way to make the data in the angular component available for the global JS call, and the data after the global processing, and to update the information in the component to affect the page

4., the third point is the key. If there is a clear God, let's go to the Ming Road. Thank you!

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
