### ISSUE TITLE
Benchpress Documentation / Getting Started guide

### ISSUE THREAD

**Issue by felippenardi** [angular/angular#2388]
I can't find a documentation or a getting started guide for Benchpress. Where can I start learning about how to use it?

**Comment by tbosch** [comment]
Hi,
here is a simple example that uses benchpress in a standlone project: https://github.com/jeffbcross/benchpress-tree

And here are some docs: https://github.com/angular/angular/blob/master/modules/benchpress/docs/index.md

Sorry, right now we don't have more docs...

**Comment by felippenardi** [comment]
That helps a lot, thanks @tbosch !
