### ISSUE TITLE
Angular CLI 6.0.1 doesn't generate baseUrl in tsconfig.app.json

### ISSUE THREAD

**Issue by GolubevS** [angular/angular#23890]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

1. ng new SomeProject --routing
2. setup routing with lazy loading modules
3. ng serve

Result: Failed to compile (ERROR in Could not resolve module app/users/users.module relative to ..../src/app/app-routing.module.ts) 

Workaround: set "baseUrl" param to "./" in tsconfig.app.json

## Expected behavior

Angular CLI generates tsconfig.app.json with "baseUrl" value.

## Environment

<pre><code>
Angular version: 6.0.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Marabyte** [comment]
You may want to open a ticket in the [Angular CLI repo](https://github.com/angular/angular-cli/issues) instead.

**Comment by GolubevS** [comment]
Yes. Thanks.
