### ISSUE TITLE
CLI Build removes exported enum definition

### ISSUE THREAD

**Issue by moescs** [angular/angular#23896]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
If I define an enum as follows:

export namespace SomeEnums {
  export enum Enum {
    Zero,
    One,
  }
}

 and then reference it as follows:

export class AppComponent {
  public someEnum = SomeEnums.Enum.One;
}

someEnum is undefined. This happens for a brand new project, but only under after "ng build --prod". "ng serve" works fine.

## Expected behavior
I would expect someEnum to be 1;

## What is the motivation / use case for changing the behavior?
The use case is that I want to use enums, but they appear to get wiped out.

## Environment
Angular version: 6.0.1

Browser:
- [x ] Chrome (desktop) version 66.0.3359.139
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v9.4.0
- Platform:  Windows

Others:
Only happens under "ng build --prod". "ng serve" works as expected.

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/23739

**Comment by robwormald** [comment]
We would *strongly* suggest not using namespaces, at all. They are a holdover from the days where scripts were simply concatted together (and thus ordering was defined), whereas modern web applications typically use ES Modules, which are *not* concatted in order. 

See https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html, specifically that `Namespaces are simply named JavaScript objects in the global namespace. `

Using `const enums` directly has the added benefit of being able to remove everything but the value itself, which leads to smaller builds and no dependence on script ordering.

**Comment by jimmykane** [comment]
@robwormald  have you considered that the namespaces come from outside packages? 

Recomendation on other's code are not welcome.

**Comment by IgorMinar** [comment]
If the namespaces comes from a third-party package imported from node_modules then it won't be processed by Build Optimizer, if the namespaces are in your application, then you either have to turn off the optimizations in the CLI (which I don't recommend) or refactor your application to not use namespaces.

I'm not sure what you mean by "Recomendation on other's code are not welcome.". If we misunderstood what you are doing, can you please open a new issue and describe your scenario more clearly? thank you.

**Comment by AdJesumPerMariam** [comment]
This caused a lot of headache for me to figure out. This functionality works just fine in development mode, but silently fails in production. I think there should at least be some sort of warning with the compiler/linter if this is not going to be fixed.
