### ISSUE TITLE
Currency/Decimal Pipe weird rounding of big numbers

### ISSUE THREAD

**Issue by robounohito** [angular/angular#23893]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

In our business application we're working with numbers (currencies) in format 14digits.4fraction.
An attempt to format big number according to current locale sometimes ends up in unwanted rounding:

`this.currencyPipe.transform('99999999999999.9999', 'USD', undefined, '1.4-4')`
results in `$100,000,000,000,000.0000`

## Expected behavior

`this.currencyPipe.transform('99999999999999.9999', 'USD', undefined,  '1.4-4')`
should result in `$99,999,999,999,999.9999`

## Minimal reproduction of the problem with instructions

`this.currencyPipe.transform('99999999999999.9999', 'USD', undefined, '1.4-4')`
--> `$100,000,000,000,000.0000` (??)
or
`this.decimalPipe.transform('99999999999999.9999', '1.4-4')`
--> `100,000,000,000,000.0000` (??)

## What is the motivation / use case for changing the behavior?

In AngularJS Currency filter worked as expected. Maybe it just did formatting, and was not dependent on any decimal operations. 

Can we make Currency pipe independent of Decimal pipe, so there would not be any currencies rounding?

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [x] Chrome (desktop) version 66
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
![image](https://user-images.githubusercontent.com/6059170/39992870-b5dbf4aa-57a6-11e8-97ba-1b2335a7f442.png)

Not related to Angular.

**Comment by robounohito** [comment]
I'm aware of JS float numbers rounding, but why is it applied to currencies? Make Currency pipe independent of Decimal pipe, like it was in AngularJS

**Comment by trotyl** [comment]
> Make Currency pipe independent of Decimal pipe

`CurrencyPipe` doesn't depends on `DecimalPipe` at all.

**Comment by robounohito** [comment]
from docs:
> https://angular.io/api/common/CurrencyPipe
> digitsInfo - see DecimalPipe for more details
but anyway, does not matter what it uses under the hood, it should not make decimal operations, just string formatting
(because that rounding freaks out the business big time)

**Comment by trotyl** [comment]
> it should not make decimal operations, just string formatting

You should create your own pipe to do that for special business logics.

**Comment by robounohito** [comment]
Yeah, I was afraid you will say so. But the thing it's not that special, just usual expectations when working with money. 
Besides, as I said, we were uniformly using Currency filter in our old AngularJS app, it worked great, and the idea was to continue use it in Angular too.

**Comment by dawidgarus** [comment]
> You should create your own pipe to do that for special business logics.
Then angular should expose API to get locale data on how numbers should be formatted, like decimal separators or groups separators.  Otherwise programmer must duplicate that.
Number formatting is not special business logic. It's literally called currency pipe and it's common knowledge that You should not use floating point numbers for money.

**Comment by skreborn** [comment]
The funny thing is that `CurrencyPipe` actually works with the string representation and the problem is ultimately that it first [converts the string to number](https://github.com/angular/angular/blob/master/packages/common/src/pipes/number_pipe.ts#L157), and [then back to string again](https://github.com/angular/angular/blob/master/packages/common/src/i18n/format_number.ts#L33) - as far as I can see at least.

**Comment by trotyl** [comment]
> Number formatting is not special business logic. 

That's true, but the problem is OP wants string rounding rather than number formatting.

How would someone perform rounding mechanism on string directly?

**Comment by trotyl** [comment]
> Then angular should expose API to get locale data on how numbers should be formatted

All of locale APIs should already be exposed in V6, but not much logic can be reused between string-based operation and numeric ones.

**Comment by robounohito** [comment]
> OP wants string rounding rather than number formatting.
> How would someone perform rounding mechanism on string directly?
no no, you misunderstood, I don't want ANY rounding for currencies, just string formatted according to current locale

**Comment by trotyl** [comment]
Would you expect 9.99 to be `$9` or `$10`?

**Comment by robounohito** [comment]
> The funny thing is that CurrencyPipe actually works with the string representation and the problem is ultimately that it first converts the string to number, and then back to string again - as far as I can see at least.

It's probably done that way to make sure the pipe's dealing with an actual number, but maybe it's better to use regexp for that or something

**Comment by robounohito** [comment]
> Would you expect 9.99 to be $9 or $10?
if I explicitly tell it I want 2 digits
`currencyPipe.transform('9.99', 'USD', undefined, '1.2-2')
i expect `$9.99`

**Comment by trotyl** [comment]
> if I explicitly tell it I want 2 fraction digits

So what happened when you explicitly tell you want 0 fractions? Or should CurrencyPipe only be able to deal with 2 fractions?

**Comment by robounohito** [comment]
sorry, I was late with editing:

`If the need for rounding will arise, then it probably should work as it is now.`

but when there is no need, like when I explicitly want 2 fractions and string contains number with 2 fractions, then there should be no rounding

**Comment by dawidgarus** [comment]
@trotyl I believe he wants `this.currencyPipe.transform('99999999999999.9999', 'USD', undefined, '1.4-4')` to be `$99,999,999,999,999.9999`
And `this.currencyPipe.transform('99999999999999.9999', 'USD', undefined, '1.3-3')` to be `$100,000,000,000,000.000`

> How would someone perform rounding mechanism on string directly?

Libraries like Big.js do this and it works fine:
```
> new Big('99999999999999.9999').round(4).toFixed(4)
< 99999999999999.9999
> new Big('99999999999999.9999').round(3).toFixed(3)
< 100000000000000.000
```

**Comment by trotyl** [comment]
@dawidgarus I know what the request is for, but it would definitely:

+ break the consistency for different inputs; or
+ introduce lots of runtime burden.

**Comment by dawidgarus** [comment]
> That way you'll expecting completely different behavior between
I don't think that's different behavior. `transform(123.45)` and `transform('123.45')` should give the same result always. Reason why `transform(99999999999999.9999)` and `transform('99999999999999.9999')` may seem to be different, it's because 99999999999999.9999 does not represent number 99999999999999.9999. It not a number 99999999999999.9999 rounded to 100000000000000. It's just a different representation of number 100000000000000 in floating point numbers, same as 0.(9) is different representation of 1 in base 10.

**Comment by robounohito** [comment]
Then Currency Pipe is useless for us. 

(And it worked so nice in AngularJS...) 

I could've written something for formatting string according to current locale myself, I can getLocaleNumberSymbol (Group/Decimal separators), but I can't figure out how to get Currency Symbol Position. 

(And there probably much more stuff we will need, locale contains too much info).

**Comment by vicb** [comment]
As @trotyl mentioned, the currency pipe uses JS numbers and have the limitation that come with them.

The only way around would be to include code to support arbitrary precision arithmetic but it would be slower and the payload higher. I am not sure that is something most users want.

We will update the documentation to reflect this.

**Comment by mkoziel2000** [comment]
I'm with robounohito on this one.  It is absolutely odd behavior when working with an input field  that has the currency pipe applied to it.  It makes the control unusable.  I need the currency pipe so that trailing zeros can be shown correctly.

<input formControlName="somePriceField" [value]="form.get('somePriceField').value | currency:'USD','','1.2-2'"/>
