### ISSUE TITLE
Test that the dynamic component loader propagates errors when a dynamic component fails to load.

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#2389]
I do not see any error case tests in dynamic_component_loader_spec.dart and I suspect that there is a bug eating exceptions coming from dynamic components.

**Comment by mhevery** [comment]
Could you provide a repro case.

**Comment by jbdeboer** [comment]
Same as #2391

IIUC, the dynamic component loader is passing the component's exception through a Future to the Router in #2391. The Router is not doing anything with that error and then something (the zone maybe?) is eating the exception.

I wasn't able to verify that the dynamic component loader was doing the correct thing -- and am still not convinced: why should the user of the dynamic component loader need to handle all error cases?

In any case, I would have loved to look at the spec file to understand how the dynamic component loader intended to deal with these errors.

**Comment by naomiblack** [comment]
Closing this as a dup of #2391. (Resolving that issue will include meaningful tests.)
