### ISSUE TITLE
docs: Router - tell us to remove `pathMatch: 'full'` from lazy-routing modules

### ISSUE THREAD

**Issue by wardbell** [angular/angular#23900]
I stumbled badly in child route configuration because the **Router guide** didn’t tell me to remove `pathMatch: 'full'` _from lazy loaded routes!_

See what I mean in  “CrisisCenter” route configuration:

1. https://angular.io/guide/router#candeactivate-handling-unsaved-changes

2. Then search for `pathMatch` and you will end up here:

```
const crisisCenterRoutes: Routes = [
  {
    path: '',
    redirectTo: '/crisis-center',
    pathMatch: 'full'
  },
  {
    path: 'crisis-center',
    component: CrisisCenterComponent,
    children: [
      {
        path: '',
        component: CrisisListComponent,
        children: [
          // ... more
        ]
      }
    ]
  }
];
```
I followed that pattern in my app. But because my module lazy loads, only the empty child path matched. The `:id` route did not match and was reported as an error. The router event trace tells me it isn’t matching but not why.

Later in the Router Guide, we talk a bit about configuration but we don’t talk about `pathMatch`. It just  *silently disappears* from the [lazy load configuration](
https://angular.io/guide/router#lazy-load-the-crisis-center).

We should call out how important it is to remove `pathMatch` from lazy-configured routes!

**Comment by brandonroberts** [comment]
Fixed via https://github.com/angular/angular/pull/20023
