### ISSUE TITLE
NPM Audit Security Warnings

### ISSUE THREAD

**Issue by Linicks** [angular/angular#23913]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ x] Other... Please describe: Security  Warnings.
</code></pre>

## Current behavior

When performing an npm audit in the root of a new Angular 6 + material project the following is reported: 16 vulnerabilities found - Packages audited: 21363 (21337 dev, 1437 optional) Severity: 11 Low | 5 High

## Expected behavior

No security warnings.

## Minimal reproduction of the problem with instructions

Execute the npm audit command in the root of the project. Of course your npm cache should be up to date.

## What is the motivation / use case for changing the behavior?

It's important to address security issues proactively. 

## Environment

<pre><code>
Angular version: 6.0.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.1.0  
- Platform:  Linux 

Others:

Output from ng version:

Angular CLI: 6.0.1
Node: 10.1.0
OS: linux x64
Angular: 6.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.1
@angular/cdk                      6.0.2
@angular/material                 6.0.2
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

npm version is 6.0.1
</code></pre>

**Comment by IgorMinar** [comment]
closing in favor of https://github.com/angular/angular-cli/issues/10963 - please follow that issue for further updates.
