### ISSUE TITLE
Components exported from library module are not available in app code

### ISSUE THREAD

**Issue by MonocleKelso** [angular/angular#23912]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Components exported from a library module are available in templates but cannot be imported into app code.

## Expected behavior

Components should be available everywhere.

## Minimal reproduction of the problem with instructions

Via the CLI create a new "demo" app and a new library (test-library) in the same workspace. Add a component (TestComponent) to the library and include it in the export config of the library module. Build the library and use the component in a template in the demo app. Everything works. Now attempt to import TestComponent into a component in the demo app via _import {TestComponent} from 'test-library'_ and notice that the app fails to build stating that TestComponent is not an exported member of test-library. Adding _export * from './test.component'_ to public_api.d.ts solves the issue but now you have to declare the component for export in two places.

## What is the motivation / use case for changing the behavior?

Having to declare components for export in two places is redundant and not intuitive.

## Environment

<pre><code>
Angular version: 6.0.1

Browser:
- [x] Chrome (desktop) version 66
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by phl3x0r** [comment]
You need to export it. I don't think this should be considered a bug as it's working as intended.
Putting the component in the exports section of NgModule decorator is not a substitute.

**Comment by IgorMinar** [comment]
NgModule export compliments the ES Module export, in order for the component to be accessible in your app, you need to export the it in both places. We are working on making the NgModules step optional but that is not ready yet.
