### ISSUE TITLE
IE11 Syntaxerror when building under es6

### ISSUE THREAD

**Issue by ninjaonsafari** [angular/angular#23927]
## I'm submitting a...

<pre><code>
[X] Bug report  
</code></pre>

## Current behavior
I get two syntax errors in ie11 when running my angular6 app with es6.

In the main.js the error is that there is still a `class` inside it:
`let AppComponent = class AppComponent {`

and also for the vendor.js
`class PlatformLocation {`

I also get an error in the polyfill.js on this line:
`var testString = delegate.toString();`

## Minimal reproduction of the problem with instructions
I created a project to reproduce it ([repo](https://github.com/ninjaonsafari/ng6test)).
or
1. ng new test-app
2. change to es6
3. add polyfills
4. run ng serve
5. open ie11

## What is the motivation / use case for changing the behavior?
It's broken in ie.

## Environment

Angular CLI: 6.0.1
Node: 9.4.0
OS: win32 x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package
```
@angular-devkit/architect         0.6.1
@angular-devkit/build-angular     0.6.1
@angular-devkit/build-optimizer   0.6.1
@angular-devkit/core              0.6.1
@angular-devkit/schematics        0.6.1
@angular/cli                      6.0.1
@ngtools/webpack                  6.0.1
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
Not relates to Angular. Ref: 

+ https://angular.io/guide/typescript-configuration#target
+ https://github.com/angular/angular/issues/21202

**Comment by ninjaonsafari** [comment]
so your saying we can't build under es6 for ie11?
Aren't the polyfills responsible to transpile the code to es5?

**Comment by trotyl** [comment]
+ https://stackoverflow.com/questions/31205640/what-is-the-difference-between-polyfill-and-transpiler
+ https://stackoverflow.com/questions/45874815/can-a-transpiler-replace-polyfills
+ https://stackoverflow.com/questions/40524010/why-does-a-browser-need-a-polyfills-file-while-i-compile-es6-to-es5-with-babel

**Comment by ninjaonsafari** [comment]
so I have to use babel or so to transpile to es5?

**Comment by trotyl** [comment]
True if you're using IE11. But Angular prefers TypeScript.

**Comment by ninjaonsafari** [comment]
For me the problem is, I want to write es6 in my .ts files.
But when I change `"target": "es6"` to `"target": "es5"` i get compiling errors like:
`error TS2339: Property 'find' does not exist on type 'Route[]`

So I would run bable over the compile files or what are you suggesting?

**Comment by trotyl** [comment]
http://www.typescriptlang.org/docs/handbook/compiler-options.html

`Array.prototype.find` is an ES2015 API, `--lib es2015` required.

**Comment by ninjaonsafari** [comment]
Okay, I understand the problem now. Thanks for clarification.
