### ISSUE TITLE
Webpack guide should be deprecated/removed

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#23937]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

The Webpack guide is outdated, but still available through direct links and search results. Since we're promoting use of the CLI, we should add a deprecation warning to the top of the guide or remove it.

**Comment by dschnelldavis** [comment]
*Please* do not remove this page.

Instead, please add a warning to the top that setting up Webpack manually is not normally recommended, though it is possible. Then, to support those of us who need to do it anyway, update the page to explain how to manually set up Webpack with Angular 6.

I am one of many developers working on projects that are incompatible with the current version of the Angular CLI. (My latest problem is the CLI is now incompatible with multiple NPM packages—but that's just the most recent in a series of problems I've had using the CLI.) For us, updating this Webpack guide will solve two problems:

In the short run, it will enable us to use Angular 6 right away—without having to first wait for the CLI to fix its incompatibilities.

In the long run, it will increase our confidence that we will be able to use Angular long term (and therefore increase our willingness to both use Angular in new projects and recommend it to others), by providing some insurance protection in case future incompatibilities arise with the CLI.

One of the things I love about Angular is the way it balances being highly opinionated, while stopping short of being dictatorial. For example, Angular strongly recommends using TypeScript. However, if a specific developer wants to ignore that and write plain JavaScript—that isn't recommended, but it *is* allowed. Updating this page would continue that excellent tradition by recommending the CLI, but also allow using plain Webback if needed. (The Angular CLI itself has never struck this balance well, and has acted dictatorially multiple times, especially by [repeatedly](https://github.com/angular/angular-cli/issues/10618#issuecomment-391049171) [blocking users from configuring Webpack themselves](https://github.com/angular/angular-cli/issues/1656#issuecomment-249921747)—a problem this guide would provide a permanent alternate solution for.)

**Comment by sarunint** [comment]
I kinda disagree with @dschnelldavis for a reason.

Angular CLI v6 introduces a concept of builders, which will allow developers to plug their own build system. This way, developers can change Webpack config that they need.

The thing is this API isn't stable yet, but it's coming!

**Comment by lazarljubenovic** [comment]
I agree that the CLI should be promoted as the best-practice way to build an app, but I don't see a reason why an example of a good webpack config cannot be moved under some "advanced" section. Until `ng` (the CLI) and `ngc` (the Angular compiler) are merged into a single binary which cannot be separated, `ng` will remain an additional helper utility for working on an Angular application.

**Comment by jenniferfell** [comment]
Note to doc-selves: If the doc remains, we should add it back to the nav. It's a big no-no in content UX to have files that come up in search but aren't in the navigation. :-)

**Comment by CarissaThomas** [comment]
Is there a way to manually edit a webpack.config file in Angular 6?  If ng eject no longer works, how can I access the Webpack.config file?  I'm currently having issues with URLs and dots on the Webpack dev server and I need to access the webpack.config so that I can properly implement the disableDotRule.  Honestly, if Angular 6 was released without these kinds of issues in consideration, I question the decision making on this one.

**Comment by sarunint** [comment]
@CarissaThomas Unfortunately, at this stage it is impossible. But it will be possible soon, since version 6 of the CLI supports custom builders. But its API is not stable for custom implementation yet. So, soon...

**Comment by lazarljubenovic** [comment]
> Is there a way to manually edit a webpack.config file in Angular 6?

Yes, but not with Angular CLI.

**Comment by jenniferfell** [comment]
Adding "needs eng input" label. 

Options:
- Keep = add webpack doc to nav, update example to work, and possibly add "deprecated" notice to top of page
- Remove = remove webpack doc and example entirely

The current state is confusing. The doc and example show up in search and source, but the example doesn't work and the doc is considered unsupported/unmaintained.
