### ISSUE TITLE
How to deploy Angular 6 Universal (server-side-rendering) Web app?

### ISSUE THREAD

**Issue by jitendrapal00** [angular/angular#23934]
Hi, 

I have built the Angular 6 Universal Web it is working fine on the localhost: port(ex- 4000).

And now I want to deploy the app on firebase but I don't know and not found any solution for deploying it on the firebase.

So please let me know how we can deploy it to the firebase.

**Comment by robwormald** [comment]
See https://github.com/davideast/angular-universal-express-firebase

In the future, please take how-to questions to Gitter.
