### ISSUE TITLE
undefined is not a function in _onFinish callback for animation player

### ISSUE THREAD

**Issue by gmfun** [angular/angular#23930]
## I'm submitting a...

<pre><code>
[X ] Bug report  
</code></pre>

## Current behavior

Getting the following error 
<pre><code>
undefined is not a function
</code></pre>

![screen shot 2018-05-16 at 2 03 24 pm](https://user-images.githubusercontent.com/6323787/40106196-bb7c3d30-5912-11e8-8a0a-130b002b7084.png)

Probably originating from 
https://github.com/angular/angular/blob/b7c417f618f1aa27fe1613129711d1380ce71dce/packages/animations/src/players/animation_player.ts#L56

## Environment
<pre><code>
Angular version: 6.0.1

Browser:
- [X ] Chrome (Android)

Others:
This error is happening in mobiles from Chinese vendors like Vivo etc.
</code></pre>

**Comment by dario-piotrowicz** [comment]
I agree with @martinsik I imagine this is the expected behaviour and just a user error (not having a minimal reproduction also doesn't help)
