### ISSUE TITLE
Please make Angular support HammerJs's doubletap.

### ISSUE THREAD

**Issue by shen-bing** [angular/angular#23954]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Angular doesn't support HammerJs's doubletap.

## Expected behavior

Angular should support HammerJs's doubletap. Just add an item "'doubletap': true," to the object EVENT_NAMES in the "platform-browser/src/dom/events/hammer_gestures.ts" file should be ok.

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [x] Safari (iOS) version 10
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by vicb** [comment]
@shen-bing would you like to try and make a PR for this ?
