### ISSUE TITLE
upgrade jasmine to 2.9 and its typings to definitely typed head version

### ISSUE THREAD

**Issue by rkirov** [angular/angular#23952]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## What is the motivation / use case for changing the behavior?

Google internally uses jasmine 2.9 (with typings from 2.4 sadness). We are trying to upgrade the typings to their current head on DefinitelyTyped which claims support for 2.8, but likely works with 2.9 too.

Previous attempts at upgrading jasmine have failed:

https://github.com/angular/angular/pull/23230
https://github.com/angular/angular/pull/19904

cc @vikerman

**Comment by thorn0** [comment]
Why 2.9? What's wrong with Jasmine 3.x?

**Comment by mhevery** [comment]
Closed by https://github.com/angular/angular/pull/19904
