### ISSUE TITLE
dont find reference if use this.setTest( ) and this.innerTestFn()

### ISSUE THREAD

**Issue by swapnilpatil1990** [angular/angular#23955]
## I'm submitting a...

<pre><code>

 Demo(): boolean {
        const self = this;
        if (this.itemsFn(listToCheck)) {
            arr.forEach(function (itemToCheck, itemToCheckIndex) {
                if (self.innerTestFn()) {
                    self.setTest( );                   
                }
            });
        }
        return true;
    }

</code></pre>

## Current behavior

For 'this' object related issue. i have written a function with one if and forEach. 
1) I have put a forEach loop inside the If condition and when i try to access a function using  'this' object,it's not persisting the reference of that function. So i have explicitly save the 'this' and use it.
Eg.
 Demo(): boolean {
        const self = this;
        if (this.itemsFn(listToCheck)) {
            arr.forEach(function (itemToCheck, itemToCheckIndex) {
                if (self.innerTestFn()) {
                    self.setTest( );                   
                }
            });
        }
        return true;
    }

2) In above example self.innerTestFn() and self.setTest( ) dont find reference if use this.setTest( ) and this.innerTestFn()

## Expected behavior

using this.setTest( ) and this.innerTestFn() should be accessible all functions

## Environment

<pre><code>
Angular version: 5

Browser:
- [ ] Chrome (desktop) Version 65.0.3325.181  (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6
- Platform:  Windows  

Others:

</code></pre>

**Comment by swapnilpatil1990** [comment]
This issue is in Angular 5

**Comment by jotatoledo** [comment]
`const self = this;` thats so jquery-ish

For support requests you should use other channels, like stackoverflow or gitter.
Please dont use the issue tracker for this kind of issues.

**Comment by swapnilpatil1990** [comment]
@jotatoledo:I know what you said  Actually i am using Angular 5 with typescript with performance improved prosime given by angular 5 still i need to handle global boject reference.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
