### ISSUE TITLE
Tutorial Hero Editor section needs a blank space

### ISSUE THREAD

**Issue by kyle116** [angular/angular#23951]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

There needs to be a space between `@NgModule` and `decorator` on the documentation page here:
https://angular.io/tutorial/toh-pt1
"The most important @NgModuledecorator annotates the top-level AppModule class."

## Expected behavior

"The most important @NgModule decorator annotates the top-level AppModule class."

## What is the motivation / use case for changing the behavior?

Better readability

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by brandonroberts** [comment]
@kyle116 would you like to submit a PR to fix the spacing issue?

**Comment by jainanuj0812** [comment]
@kyle116, I can help you out if you need any help to file the PR

**Comment by kyle116** [comment]
@jainanuj0812 uh sure lol. i didnt know the angular.io docs were on this repo.

**Comment by jenniferfell** [comment]
@kyle116 : I saw that you abandoned your PR. We all did that a lot in the beginning. I still do. If you're still interested in working on this, we're happy to support you each step of the way. 

My team put together a wiki that might help you: https://github.com/ExpertSupport/doc-workflow/wiki

@jainanuj0812 Thanks for your offer to help, too.
