### ISSUE TITLE
internationnalisation with angular 6:

### ISSUE THREAD

**Issue by mdghaies** [angular/angular#23957]
when in run this command with angular cli 6.0 
ng serve --aot --i18nFile=src/locale/messages.fr.xlf --i18nFormat=xlf --locale=fr
I have this error : 
unknown option:   '--i18nFile'

**Comment by jotatoledo** [comment]
Please revisit the [options section](https://github.com/angular/angular-cli/wiki/serve#options) for `ng serve`

**Comment by brandonroberts** [comment]
The i18n guide shows you how to add configuration to your Angular CLI for internationalization and usage with Angular CLI 6.0. https://angular.io/guide/i18n#merge-the-completed-translation-file-into-the-app
