### ISSUE TITLE
Delete me

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#23969]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[] Documentation
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by danwulff** [comment]
@jenniferfell sadly github doesn't allow issue deletion (right now), but the creator can close the issue their self I believe.

**Comment by jenniferfell** [comment]
I was just playing with something, and I couldn't get the issue to reset to the default template of prompts, nor could I cancel creation of the issue, so I gave it an obvious subject so I could come back and just get rid of this.
