### ISSUE TITLE
feat(platform-server): add missing globals

### ISSUE THREAD

**Issue by CaerusKaru** [angular/angular#23967]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Globals like `Node` and `HTMLElement` are provided by Domino and are safe to add to the global namespace, but are not included

## Expected behavior

Before/during app initialization, these safe globals should be added to prevent render errors (note: this does not include unsafe globals like `window` and `document`)

## What is the motivation / use case for changing the behavior?

Reduce render errors

## Environment

<pre><code>
Angular version: 6.0.2

**Comment by mhevery** [comment]
This is something which the user should do when configuring the `tsconfig` for the project. Angular should only declare what it depends on.

Won't fix.
