### ISSUE TITLE
Angular 6 server-side prerendering error NodeInvocationException: Prerendering failed because of error: ReferenceError: Document is not defined at ...\ClientApp\dist\main-server.js:20175:42

### ISSUE THREAD

**Issue by LucianoDiPierno** [angular/angular#23961]
## I'm submitting a...
<pre><code>
[x] Bug report 
</code></pre>

## Current behavior
After migrate from Angular 5 to 6 and webpack v3 to v4, an error occurs when the application is started:
NodeInvocationException: Prerendering failed because of error: ReferenceError: Document is not defined
at J:\Progetti\Platform\Software\CTAgenda\ClientApp\dist\main-server.js:20175:42

In main-server.js the error is in a NgbFocusTrapFactory Function where is used Document. In app.module.shared.ts i have a component that reference to @ng-bootstrap/ng-bootstrap (NgbActiveModal). Moreover in app.module.server.ts i have the import of app.module.shared.ts.

I've tried to move the component from app.module.shared.ts to app.module.browser.ts but another error appear (component not found)

Given that I have not changed anything in the application after the upgrade, i can not figure out how to solve the problem. Thanks for the help.

## Expected behavior
The normal functioning of prerendering as has been with Angular v5

## Minimal reproduction of the problem with instructions
i've tried to reproduce the error on stackblitz.com without success (project greater of 5mb due to main-server.js and vendor.css/js)

## What is the motivation / use case for changing the behavior?
Migrate from Angular 5 to 6 and webpack v3 to v4

## Environment
<pre><code>
Angular version: 6.0.2
npm 6.0.0
webpack 4.8.3
@angular/cli 6.0.1
aspnet-prerendering 3.0.1
aspnet-webpack 2.0.3
.NET Core 2 with WebpackDevMiddleware and HotModuleReplacement on

Browser:
- [x] Chrome (desktop) version 66.0.3359.170
 
For Tooling issues:
- Node version: v10.0.0
- Platform:  Windows

Others:
</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Please report the issue in the repo of the library you're using.

**Comment by pkozlowski-opensource** [comment]
This should be opened in https://github.com/ng-bootstrap/ng-bootstrap

**Comment by LucianoDiPierno** [comment]
@pkozlowski-opensource  Ok, thanks for the suggestion
