### ISSUE TITLE
StackBlitz exports invalid Angular project structure

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#23962]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Exporting the live example to a zip file from StackBlitz produces an incorrect project file structure when the files are extracted from the zip.

## Expected behavior

Project exported generally matches live example on StackBlitz and CLI structure

## Minimal reproduction of the problem with instructions

1. Visit https://stackblitz.com/edit/angular-7dbrdq
2. Click on the `Export` button and download the zip
3. Extract the zip to a folder
4. Compare the example file structure to the extracted folder structure. 

The `src` folder is nested in another `src` folder. 
The `.angular-cli.json` file is present in the V6 zip file 
The `angular.json` is not at the root of the folder
The `package.json` is out of date with older version of Angular and the CLI

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

cc: @EricSimons

**Comment by mwo44** [comment]
Hi, Is there any workaround to fix it and compile exported package?

**Comment by brandonroberts** [comment]
@mwo44 you can download the zip file that's in the guide. It has everything in it to run the example locally.

**Comment by mwo44** [comment]
Thanks @brandonroberts for your response, but which guide exactly? Thanks in advance

**Comment by brandonroberts** [comment]
@mwo44 it depends on which example you want as a zip file. There should be one available for most if not all the examples.

**Comment by EricSimons** [comment]
Hey all! Some legacy projects on stackblitz have been hitting problems w/ exporting, but we're rolling out our new v2 release next week that solves this (+ a whole bunch of other awesome features). Would love to have y'all beta test it :)

**Comment by ElmarN** [comment]
Problem still exists for me. Project structure is off and angular-cli is an older version...

**Comment by EricSimons** [comment]
StackBlitz prod is currently A/B testing v2 rn but all traffic should be on v2 by tmrw. This is a monster upgrade on our end, so we've had to test the heck of it before fully pulling the switch (and I'm sure there's more stuff we'll find after we do :)

**Comment by petebacondarwin** [comment]
@EricSimons - how did the A/B testing go. Is this issue now resolved?

**Comment by EricSimons** [comment]
Woah, just seeing this now- yup everything is resolved with our v2 stuff! Feel free to close 👍

**Comment by petebacondarwin** [comment]
Thanks
