### ISSUE TITLE
Fix tables in markdown to be HTML per Angular doc style

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#23978]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The following files contain tables in plain markdown: 

https://angular.io/guide/i18n#setting-up-the-locale-of-your-app
https://angular.io/guide/aot-compiler#folding

There may also be others. 

## Expected behavior

Per Angular docs style, tables should be marked up in HTML:

https://angular.io/guide/docs-style-guide#tables

Other correct examples: 
https://angular.io/guide/docs-style-guide#tables
https://angular.io/guide/module-types
https://angular.io/guide/ngmodule-api#ngmodule-metadata
https://angular.io/guide/ajs-quick-reference
https://angular.io/guide/router#router-events
https://angular.io/guide/template-syntax#binding-targets

## Minimal reproduction of the problem with instructions

See links above

## What is the motivation / use case for changing the behavior?

Consistent style
Ability to control style in same css 
Adhere to Angular Authors Guide

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kapilepatel** [comment]
@jenniferfell I am new here, please check if my PR is useful.
