### ISSUE TITLE
Module not found when generating build after upgrading to Angular 6

### ISSUE THREAD

**Issue by dalloglio** [angular/angular#23975]
## I'm submitting a...
<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

After updating Angular from version 5 to version 6 is generating error when executing the build "ng build"

## Expected behavior
Generate the build without errors.

## Minimal reproduction of the problem with instructions
When generating the build the following error occurs.

<pre>
<code>
WARNING in ./node_modules/asn1.js/lib/asn1/api.js
Module not found: Error: Can't resolve 'vm' in './node_modules/asn1.js/lib/asn1'

ERROR in ./node_modules/browserify-sign/browser/index.js
Module not found: Error: Can't resolve 'stream' in './node_modules/browserify-sign/browser'
ERROR in ./node_modules/cipher-base/index.js
Module not found: Error: Can't resolve 'stream' in './node_modules/cipher-base'
ERROR in ./node_modules/hash-base/index.js
Module not found: Error: Can't resolve 'stream' in './node_modules/hash-base'
</code>
</pre>

## Environment
 - Development

<pre>
<code>
Angular CLI: 6.0.3
Node: 9.8.0
OS: linux x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                                             Version
-----------------------------------------------------------
@angular-devkit/architect                      0.6.3
@angular-devkit/build-angular               0.6.3
@angular-devkit/build-optimizer            0.6.3
@angular-devkit/core                            0.6.3
@angular-devkit/schematics                 0.6.3
@angular/cli                                          6.0.3
@ngtools/webpack                                6.0.3
@schematics/angular                            0.6.3
@schematics/update                            0.6.3  
rxjs                                                        6.1.0
typescript                                              2.7.2
webpack                           4.8.3
</code>
</pre>

**Comment by splincode** [comment]
Please, add repository and add infromation your repro steps

**Comment by dalloglio** [comment]
Sorry, I'm a beginner and I still do not know how to post a question here. The update steps I followed are the same as described in this link: [Want to upgrade project from Angular v5 to Angular v6
](https://stackoverflow.com/questions/48970553/want-to-upgrade-project-from-angular-v5-to-angular-v6?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa).

My package.json file looks like this after the update:

{
  ...
  ...
  ...
  "dependencies": {
    "@angular/animations": "6.0.2",
    "@angular/common": "6.0.2",
    "@angular/compiler": "6.0.2",
    "@angular/core": "6.0.2",
    "@angular/forms": "6.0.2",
    "@angular/http": "6.0.2",
    "@angular/platform-browser": "6.0.2",
    "@angular/platform-browser-dynamic": "6.0.2",
    "@angular/platform-server": "6.0.2",
    "@angular/router": "6.0.2",
    "@ng-bootstrap/ng-bootstrap": "^2.0.0",
    "bootstrap": "^4.1.1",
    "core-js": "^2.5.1",
    "font-awesome": "^4.7.0",
    "highcharts": "^6.1.0",
    "rxjs": "^6.1.0",
    "rxjs-compat": "^6.1.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "6.0.3",
    "@angular/compiler-cli": "6.0.2",
    "@angular/language-service": "6.0.2",
    "@types/jasmine": "2.5.45",
    "@types/node": "^6.0.89",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "^2.0.2",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "moment": "^2.21.0",
    "protractor": "^5.3.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "2.7.2",
    "@angular-devkit/build-angular": "~0.6.3"
  }
}

**Comment by matsko** [comment]
@dalloglio could you make a github repo of your failing project so we can investigate?

**Comment by dalloglio** [comment]
@matsko I can not. The project I'm working on is private. Is there another way to solve this problem?

**Comment by dalloglio** [comment]
Problem solved. I applied as an alternative what is described in: [https://gist.github.com/niespodd/1fa82da6f8c901d1c33d2fcbb762947d](https://gist.github.com/niespodd/1fa82da6f8c901d1c33d2fcbb762947d)

**Comment by kgathuru** [comment]
Any chance we can re-open and fix this, the fix from https://gist.github.com/niespodd/1fa82da6f8c901d1c33d2fcbb762947d is temporary:

From comments:
'This is a monkey-patching type of fix and you should use it only temporarily. Also make sure to fix Angular version, because any new version may break it again.'

**Comment by coranos** [comment]
Is this problem fixed at all?

We get it in nanovault/bananovault and have to use the monkey patch, still, months later.

**Comment by 11lein** [comment]
I've added 

`    "browser": {
        "crypto": false,
        "vm": false
    }, `

in the root of the package json to fix this

**Comment by prahaladbelavadi** [comment]
I'm facing a similar issue, and I've bundled mine up into a github repo [here](https://github.com/prahaladbelavadi/ionic-crypto-key-creator) 

The error I get is 
`[ng] ERROR in ./node_modules/cipher-base/index.js
[ng] Module not found: Error: Can't resolve 'stream' in 'C:\Users\gescoe\Documents\projects\ionic-crypto-key-creator\myApp\node_modules\cipher-base'
[ng] ERROR in ./node_modules/hash-base/index.js
[ng] Module not found: Error: Can't resolve 'stream' in 'C:\Users\gescoe\Documents\projects\ionic-crypto-key-creator\myApp\node_modules\hash-base'`

I have added types and saved it into the package.json file albeit I still get this error;

I tried adding "browser": { "crypto": false } and reinstalling the npm packages but the error still throws.
