### ISSUE TITLE
Style scope in Angular2 Component not aligned to native Web Component Shadow DOM 

### ISSUE THREAD

**Issue by anandgupta08** [angular/angular#2397]
My understanding is that the Angular 2 Components are built on top of Web Component standards.
As per the Web component standards, the scope of the style inside the shadow DOM is scoped. In other words, the style in the "light DOM" (non-shadow DOM) should not have any impact on the elements inside the shadow DOM. However, this does not seem to be the case (my apologies if I am missing something here). 
[Refer : https://www.airpair.com/javascript/posts/creating-container-components-part-1-shadow-dom]

I tried to write a native Web Component as well as an Angular 2 Component and used them on the same page with the page having a stylesheet that styles the button. This style is present in the "light DOM". Both the native Web Component and the Angular 2 Component have similar HTML markup that includes a button. 
As expected, the styling of the button inside the native Web Component is not affected by the style in the "light DOM"; however the button inside the Angular 2 Component was styled based on the button style defined in the "light DOM". This means the render behavior the native Web Component and the Angular2 Component are different (i.e the style is not scoped in Angular 2 component).
Is this expected?

Additionally, I do not see #shadow-root in the rendered page for the Angular 2 Component whereas it appears (as expected) for native Web Component. My understanding is Angular 2 will implement the native shadow DOM implementation where possible, and will emulate shadow DOM in browsers that do not support it.

I am using Chrome Version "43.0.2357.81 m" which i believe supports native shadow DOM. 
I am using Angular 2.0.0-alpha.25 with TypeScript 1.5.0-beta

The code can be found at : https://github.com/anandgupta08/hello-angular2-typescript

Screenshot below shows the difference in the styling of the button in native Web Component vs Angular 2 Component on Chrome 43 browser. 
The Chrome Dev Tools show #shadow-root is missing for Angular2 Component (named <hello>) , but is present for native Web Component (named <native-hello>).

![image](https://cloud.githubusercontent.com/assets/12773087/8019142/a200d47e-0c71-11e5-92d9-73aadb83de85.png)

**Comment by mhevery** [comment]
We are still debating how best to handle the CSS encapsulation of components. This is on our road-map.

**Comment by vicb** [comment]
To add some details here: there are 3 strategies for rendering component: native WC, emulated WC, emulated WC unscoped.

The default strategy is the last one which explains what you see. See application.js for more info.

As the emulated behavior is not strictly the same as the native one, the strategy is not automatically switched based on the availability of WC.

**Comment by anandgupta08** [comment]
Thanks Misko and Victor for your response.

How can i switch between WC strategies ? I do see some posts that say we can do it while calling bootstrap() as below:

![image](https://cloud.githubusercontent.com/assets/12773087/8022963/0ad4d5e0-0d26-11e5-946c-ac3dbfc8802f.png)


However, this does not seem to help as i get an error (if i still go ahead and run the compiled JavaScript code assuming its just that typedefiniton / editor tooling  issue):

![image](https://cloud.githubusercontent.com/assets/12773087/8022969/629927f4-0d26-11e5-8a39-c4183b70a8c5.png)

I am using Typescript 1.5.0-beta and Angular 2.0.0-alpha.25

Some guidance around this would be highly appreciated.

**Comment by gdi2290** [comment]
>@anandgupta08


for alpha.25 do this
```typescript
import {ShadowDomStrategy, NativeShadowDomStrategy} from 'angular2/core';
import {StyleUrlResolver} from 'angular2/src/render/dom/shadow_dom/style_url_resolver';
import {bind} from 'angular2/di';
import {bootstrap} from 'angular2/angular2';
import {Hello} from 'hello';

bootstrap(Hello, [

  bind(ShadowDomStrategy).toFactory(
    styleUrlResolver => new NativeShadowDomStrategy(styleUrlResolver),
    [StyleUrlResolver]
  )

])
```
---

for alpha.26 do this
```typescript
import {ShadowDomStrategy, NativeShadowDomStrategy} from 'angular2/render';
import {bind} from 'angular2/di';
import {bootstrap} from 'angular2/angular2';
import {Hello} from 'hello';

bootstrap(Hello, [

  bind(ShadowDomStrategy).toClass(NativeShadowDomStrategy)

])
```

**Comment by mcpDESIGNS** [comment]
@gdi2290 Hey Patrick, does Angular2 by default scope CSS? Trying to find out how to do this, can't find any documentation on how to actually implement it!
