### ISSUE TITLE
Question: |pipe:arg1:arg2 or |pipe(arg1, arg2)

### ISSUE THREAD

**Issue by vicb** [angular/angular#2398]
We had the debate back to ng.dart 1 and decided to keep the colon format.

I'd like to revive the debate are pipes will probably be used more in n2.

There's a gotcha with the colon format:

`subject | p1:arg | p2` is currently parsed as `subject | p1:(arg | p2)` - while you might want `(subject | p1:arg) | p2`

Switching to `()` can make resolving the ambiguity easier:

`subject | p1(arg) | p2` and `subject | p1(arg | p2)`

**Comment by gdi2290** [comment]
you can do `subject | pipe(arg1, arg2)` already with the existing version (and I prefer switching to `()`) [rxPipes.ts#L38](https://github.com/angular-class/angular2-reactive-starter/blob/2f29104a32df4bbbaff82fd28b65316cd92907f8/src/common/rxPipes.ts#L38) but it doesn't allow for when you don't want arguments.

I made an issue here https://github.com/angular/angular/issues/1625 where @mhevery said "I think we would like to keep the same syntax unless there is a technical reason not to." so we probably found our technical reason to do so `subject | p1(arg | p2) | p3`

**Comment by vicb** [comment]
> you can do `subject | pipe(arg1, arg2)` already with the existing version

This is currently parsed as `(subject | pipe)(arg1, arg2)`. `subject | pipe(arg1, arg2)` would have to be rewritten as `subject | pipe()(arg1, arg2)` or `(subject | pipe)(arg1, arg2)` if we use '()' to delimit parameters.

**Comment by vicb** [comment]
We will stick with ":" as argument separator.
