### ISSUE TITLE
When SSR with Angular Universal, handling large arrays with ngFor blocks server processes.

### ISSUE THREAD

**Issue by cse-t-kutsuna** [angular/angular#23986]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Handling large arrays with ngFor blocks server processes.
This makes it impossible to receive requests for api and static files.

## Expected behavior

ngFor does not block when running on server.

## Minimal reproduction of the problem with instructions

https://github.com/cse-t-kutsuna/ng-toh-ssr

```
npm i
npm run build:server
npm run start:server
ab -n 2000 -c 20 http://localhost:4000/heroes
```
access http://localhost:4000 on browser

## Environment

<pre><code>
Angular version: 5.2.10

 
Others:

- Node version: 8.6.0  
</code></pre>

**Comment by vikerman** [comment]
Not sure what is being expected here. Don't have large ngFor?

**Comment by cse-t-kutsuna** [comment]
Yes, my app has a big ngFor.
I expect that even if I handle large ngFor, I will not block other processing.

One temporary solution is to put setImmediate in the loop as follows.
https://github.com/cse-t-kutsuna/ng-toh-ssr/blob/master/server/angular/src/directives/ng_for_of.ts#L156
