### ISSUE TITLE
add more hover action to tabbed titles in code snippet collections

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#23985]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ X] Other... Please describe: AIO css
</code></pre>

## Current behavior

See here: https://angular.io/tutorial/toh-pt3#final-code-review
It's not obvious at first that the filenames at the top are a set of tabs that will switch the code displayed below. Hover over a title and the cursor changes to a hand (or other selection cursor). Nothing else changes

## Expected behavior

It might be nice to also show a response to hover by the title being hovered. This site adds a selection box to the JavaScript or TypeScript title when you hover over it, to provide more visual cue about the tab action available. 
https://docs.split.io/docs/javascript-sdk-overview#section-using-the-sdk

## Minimal reproduction of the problem with instructions

See above.

## What is the motivation / use case for changing the behavior?

Ease of use

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by petebacondarwin** [comment]
Styling the tab with a different background colour when hovered makes sense.
Also I think the lack of tabbiness of these code examples is that the tabs don't feel like they connect to the content. So I would consider putting code examples into a card with the tabs filling across the top of the tab. This would make them feel more connected and tab-like.

**Comment by petebacondarwin** [comment]
Also the Material Design guidelines discourage long tab names, so we should consider not including the "path" of the example file in its tab.
