### ISSUE TITLE
Add "suggest edits" feature to all docs

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#23981]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[X ] Other... Please describe: AIO 
</code></pre>

## Current behavior

Starting with v6, the API reference pages now have two icons on the top right of each page: 

- Suggest edits (pencil icon): Opens the page in editing mode, so you can make small changes and with one button create a branch and submit a PR. 

- Show source (< > icon): Opens the source code file to the location of this doc markup. 

## Expected behavior

It would be nice to add Suggest edits to all pages in http://angular.io/docs. This would make it easier for our team and community contributors to submit simple changes, without the overhead of fork maintenance and the pull-push cycle. 

- Suggest edits (pencil icon): Opens the page in editing mode, so you can make small changes and with one button create a branch and submit a PR. 

## Minimal reproduction of the problem with instructions

1. Go here: https://angular.io/api/animations/animate
2. Click the pencil icon in the upper right

## What is the motivation / use case for changing the behavior?

Encourage contribution
Expedite simply changes

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by petebacondarwin** [comment]
Closed by #24378
