### ISSUE TITLE
Make title area of code snippet collections more similar to single code snippet titles

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#23984]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ X] Other... Please describe: AIO css
</code></pre>

## Current behavior

A collection of code snippets has a tabbed widget above the code area. That widget contains the titles of the code files, each one clickable to change what's displayed in the code area. The text is medium gray with the standard page background. The current file is underlined in blue. 

https://angular.io/tutorial/toh-pt3#final-code-review

A single code snippet has a single title above the code area. The title is white text on a blue box. 

https://angular.io/tutorial/toh-pt3#add-the-input-hero-property

## Expected behavior

It would be nice if these were similar in color, font, and border treatment.

## What is the motivation / use case for changing the behavior?

Consistency: Training the eye to recognize all code by the same visual cue

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by petebacondarwin** [comment]
So do we want to make the tabs more "blue" like the headed code blocks or make the headed code blocks more similar to the tabs?

I might be tempted by the former but it would require some designing to accommodate the various states that tab labels can take (e.g. active, inactive, hovered, disabled, etc).

**Comment by petebacondarwin** [comment]
Note that in #24027 I have styled the tabs inside a Material Design "card". Perhaps this is the direction we should be taking for all code blocks, if we are buying into the MD approach?

**Comment by jenniferfell** [comment]
Probably does make sense to move toward MD approach. 

I think it makes sense to design the tabbed one first, because of the variants you mention. Then we can make the single file one look like the selected tab.

FWIW...I like where this is headed: 

![image](https://user-images.githubusercontent.com/31675481/40390064-3c8f75d2-5dd1-11e8-8c0a-97f62e0f004d.png)

**Comment by gkalpak** [comment]
BTW, the "blue background, black text" style is our current style for focused tab labels.

**Comment by petebacondarwin** [comment]
Related to https://github.com/angular/angular/issues/23982 @sjtrimble

**Comment by dylhunn** [comment]
The tabbed code snippet widget looks different because it's a `mat-tab`. However, both widgets work well, and we're probably not going to make changes here.
