### ISSUE TITLE
Consider white background for docs

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#23983]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ X] Other... Please describe: AIO css
</code></pre>

## Current behavior

Background of all pages is a light (20%) gray.

These light grays have been used extensively on the web because they soften the harsh black-and-white look. They also reduce contrast, which with some background-text combinations (such as 80% gray text on 20% gray background) makes the doc harder to use for some users. 

Light gray background also means that all graphics need to either be transparent or have borders so the white background of the graphics looks normal. 

## Expected behavior

It would be interesting to see if a white background improves readability/look overall, esp with the blue font areas, in tables, and near graphics. 

## Minimal reproduction of the problem with instructions

See https://angular.io/guide/architecture#whats-next

## What is the motivation / use case for changing the behavior?

Accessibility
Ease of creating graphics that look well-integrated with the site

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by petebacondarwin** [comment]
Note that Angular Material itself is defining this grey background colour. It is set deep inside the theming part of the SASS code in their library: https://github.com/angular/material2/blob/abc3d38c57146443c848d5ba26fd2fab8ca185d6/src/lib/core/theming/_palette.scss#L677

We should talk to someone... @jelbourn(?) ... about the choice of this colour and how best to override it?

**Comment by gkalpak** [comment]
Also, according to the spec ([Color theme creation][1] > `Surface, background, and error colors`):

> The background color appears behind scrollable content. The baseline background and surface color is #FFFFFF.

[1]: https://material.io/design/color/the-color-system.html#color-theme-creation

**Comment by jelbourn** [comment]
As @gkalpak said, the color is defined by the Material Design specification. 

Is there text somewhere on the site that's not meeting W3C guidelines? The tool http://contrast-ratio.com can tell you pretty easily.

**Comment by jelbourn** [comment]
I checked: http://contrast-ratio.com/#rbga%280%2C0%2C0%2C.87%29-on-%23fafafa

The current colors meet W3C AAA for any size text.

**Comment by petebacondarwin** [comment]
Um, @jelbourn: I think @gkalpak was saying that background and surface baseline colours are white?

<img width="699" alt="screen shot 2018-05-21 at 16 32 18" src="https://user-images.githubusercontent.com/15655/40315948-b65c2152-5d14-11e8-8848-503c9487e506.png">


I note that mat-card backgrounds, are in fact white.

**Comment by jelbourn** [comment]
Ah, it looks like that's been changed in the 2018 update. The pre-I/O version was `#fafafa` for app background with the pure white reserved for "sheets of material" like cards and dialogs.

**Comment by jenniferfell** [comment]
I'm not surprised that technically it meets accessibility standards. Every site I've worked on with this gray did, and it didn't stop readers from complaining that text blurs into background a little so they wanted a higher contrast option.

So...if I understand your point @jelbourn, the light gray background makes sense when you have cards and other elements that you want to offset...is that the idea? I can see how it pops nicely there. 

The tricky part of a text-rich site is that we want the main body to as readable as possible. Same reason the cards have white background. 

As @gkalpak pointed out in another thread, with a white background for the whole page, we do lose the ability to offset code regions or images with white card-like boxes. I'm not sure, however, that those elements are so much more important than the main text that they deserve special offset the way navigation cards are offset. But I definitely wouldn't want to offset code or images by giving them a darker background than the main page, because that definitely moves us into readability challenges. 

Hmmm....

**Comment by sjtrimble** [comment]
@jenniferfell / @petebacondarwin can we close this? It was addressed and implemented in the associated PR above.

**Comment by ajitsinghkaler** [comment]
@gkalpak I think we can close this

**Comment by gkalpak** [comment]
Thx, @ajitsinghkaler! Fixed by #28396.
