### ISSUE TITLE
Soften header for code sections

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#23982]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[X ] Other... Please describe: AIO
</code></pre>

## Current behavior

Code snippets are displayed in a special box with a title area that is the same blue as the site masthead. 

https://angular.io/guide/quickstart

![issue-code-title](https://user-images.githubusercontent.com/31675481/40210862-a5c4da2c-5a04-11e8-9203-8bdc552542f7.png)

## Expected behavior

The code snippet titles are visually stronger than section headings. This makes it harder for users to remain oriented in the overall doc, especially longer docs. It also makes it harder to scan section headings when scrolling.

It would be nice to soften the visual impact. Perhaps gray background or a less saturated blue. Or reverse the white-text-on-blue to blue-text-on-white? Experimentation by a designer required. 

Bonus: A color change would allow selection highlighting to show up on the title text. 

## What is the motivation / use case for changing the behavior?

https://angular.io/guide/quickstart
Go to the code snippet for src/app/app.component.ts

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by petebacondarwin** [comment]
@sjtrimble can you take a look at this?
