### ISSUE TITLE
Q: router(router-outlet): how to pass properties/events to components

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#2399]
yo @btford ,

How do I pass properties/events to components that are loaded in by the `<router-outlet>`. The initial assumption is `<router-outlet [model]="someInitialData"></router-outlet>` but that doesn't work. Using `@RouteConfig` doesn't make sense (although allowing me to include hostInjectors/viewInjectors might be interesting)

thanks

**Comment by rolandjitsu** [comment]
On the note of `events`. In version 1.x of Angular, the new router calls some methods on the controllers (`canActivate`, `activate`, etc.), but it seems like for version 2, these methods, if they exist on the constructors, they are not called.

Is that on purpose? If so, how else can we tap into those events?

**Comment by mhevery** [comment]
host/view injector is the way to go here. We don't have plans for other modes yet.

**Comment by TiagoBraga39** [comment]
@mhevery @rolandjitsu Can you give any more details?
I used canActivate to filter whether it is possible to activate:
```javascript
onActivate() {
    return false;
}
```
Shouldn't it never load the component or the HTML?
The HTML is always rendered.
What am I doing wrong?

Best regards,
Tiago Braga

**Comment by mhevery** [comment]
@btford is a better person to answer this.

**Comment by TiagoBraga39** [comment]
@mhevery I tried using the host Injector. It is plausible and it works, but still doesn't work because the property on the host property is instanciated via http request (async).
How can I manage to accomplish this? Is changeDetection the way, by waiting for the property to be instanciated?

Best regards,
Tiago Braga

**Comment by rolandjitsu** [comment]
@TiagoBraga39 if what you are explaining is how to load an async dependency and get it already instantiated without you having to explicitly call a `.then()` or `.subscribe()` on it and then wait for the response, I am afraid there is not, as far I know there hasn't been a mechanism implemented that can do what you want, so the only way I think you can is the one illustrated bellow (probably there may be other ways, but this is what I used):
```js
import {
	ViewEncapsulation,
	Component,
	View,
} from 'angular2/angular2';
import { ObservableWrapper } from 'angular2/src/facade/async';
class AsyncDep {
    constructor() {} // some logic here that returns a promise or an observable with a factory that you actually want
}

@Component({
    selector: 'my-component',
    viewBindings: [
        AsyncDep
    ]
})
@View({
    encapsulation: ViewEncapsulation.NATIVE, // https://angular.io/docs/js/latest/api/annotations/ViewEncapsulation-enum.html#NONE
    template: 'Hello {{name}}!',
    directives: []
})
class MyComponent {
    name: string;
    res: myAsyncDep;
    constructor(myAsyncDep: AsyncDep) {
        myAsyncDep.then(res => this.res = res;) // `myAsyncDep` is not ready for use yet so you need to wait here until it's resolved if it's a promise
        // or if an observable
        // ObserverWrapper.subscribe(myAsyncDep, (res) => this.res = res);
    }
}
```

**Comment by TiagoBraga39** [comment]
I managed to solve with ng-if ready, but
