### ISSUE TITLE
MDC Web is not transpiled to ES5

### ISSUE THREAD

**Issue by danieldaeschle** [angular/angular#23994]
I have an Angular app which should be IE11 compatible.
I added MDC Web code like:
```
import { MDCTopAppBar } from '@material/top-app-bar/index';

ngAfterViewInit() {
    const topAppBar = new MDCTopAppBar(this.topAppBarElement.nativeElement);
}
```

But on IE11 i get a syntaxerror
![image](https://user-images.githubusercontent.com/30751516/40234196-2c9ba048-5aa6-11e8-9fa7-21e1eb75dcd1.png)
![image](https://user-images.githubusercontent.com/30751516/40234203-34e50ba4-5aa6-11e8-8dea-58c42e7a21e8.png)

In `vendor.js` stands ES2017 code from the MDC Library. It isn't transpiled to ES5... why?

What can i do to achive my goal?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
