### ISSUE TITLE
feature request (router): Use resolvers and guards as components

### ISSUE THREAD

**Issue by chris13524** [angular/angular#23996]
## I'm submitting a...
<pre><code>[X] Feature request</code></pre>

## Current behavior

Take the example of a `RequireUserGuard`. If a protected (user required) route is picked, `canActivate()` will be invoked. If no user exists, the guard stores the current URL in a shared service and routes to a login page. Once the user logs in, there is a check against the shared service and routes back to the previous page (in which case the guard gets invoked again).

Guards and resolvers also have the issue of while the guard is being checked or while the resolve is happening (which can take a bit), the page is blank. This offers no feedback to the user, a progress bar or some visual indicator should be put here. This issue relates to #19187.

## Expected behavior

Guards and resolvers should be able to be used as components. If the guard/resolver returns a promise, the guard/resolver's component should be displayed in place of the target route. Let me give an example:
```
const routes: Routes = [
    {path: "dashboard", component: ..., canActivate: [RequireUserGuard]}
];

@Injectable()
@Component({
    template: "...progress bar..."
})
export class RequireUserGuard implements CanActivate {
    constructor(private userService: UserService) { }
    canActivate(route: ActivatedRouteSnapshot, routerState: RouterStateSnapshot): boolean {
        // do your checks, updating the template if you want
    }
}
```

## What is the motivation / use case for changing the behavior?

Developers could put their login pages directly inside the route itself. This would remove the need to redirect elsewhere and back again. Status messages and visual feedback could also be displayed during this intermittent state.

For resolvers, error messages could be displayed in the resolver itself instead of resolving a `Data | "notFound"` type and then having the target component deal with it. Errors should be dealt with in the resolver itself. Status messages and visual feedback could also be displayed during this intermittent state.

I'm sure there are many other uses for this behavior. But in general, it would make things a lot cleaner for developers as well as make the interface look a lot more consistent.

**Comment by trotyl** [comment]
But the problem is, an method can only be used when class being instantiated, but `canActivate` must be determined before that, as it's design for deciding whether that component can be instantiated.

**Comment by djleonskennedy** [comment]
@chris13524 are you serious ? :)

**Comment by chris13524** [comment]
@djleonskennedy Yes... is there something off about my request?

**Comment by jotatoledo** [comment]
Is not a bad idea, I think there was a similar proposal somewhere around the issue tracker. Did you found anything related?

**Comment by chris13524** [comment]
@jotatoledo I did see #19187, but I feel my approach is "better" and allows more options to the developer.

**Comment by jasonaden** [comment]
Thanks for the request. I've thought about this as well. If the API were done right, this could be quite useful.

**Comment by Toub** [comment]
I don't see a real benefit here.

Why don't you just redirect to the right route in your guard (and return false to stop current navigation)?
