### ISSUE TITLE
Angular Language Service: No syntax checking in [ngClass] declaration

### ISSUE THREAD

**Issue by TheNavigateur** [angular/angular#24005]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

No syntax checking in `[ngClass]="{ myClass: something }"` declaration

## Expected behavior

Syntax checking in the described declaration.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-gitter-ekepka

The HTML should show an error because "something" is not an available value;

## What is the motivation / use case for changing the behavior?

Not catching bad references in [ngClass] declarations allowing bugs to remain until run time.

## Environment

<pre><code>
Angular Language Service Version 0.1.9
Angular Version: 6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform: Windows 

Others:

</code></pre>

**Comment by splincode** [comment]
Stackblitz uses JIT-compiler in runtime.  Therefore, there is no rigid type checking...

1) If you usage IDEA

![image](https://user-images.githubusercontent.com/12021443/40303795-fa765bc2-5cfc-11e8-8bed-2f29851b7a03.png)

2) If you run building with AOT-compiler

![image](https://user-images.githubusercontent.com/12021443/40303854-2d5b554c-5cfd-11e8-9407-38c263be0abd.png)

3) JIT-compiler with valid boolean
[ngClass]="{ myClass: true }"

![image](https://user-images.githubusercontent.com/12021443/40303935-728527a6-5cfd-11e8-8041-42cdb3b4e7c0.png)

**Comment by TheNavigateur** [comment]
@splincode Why the downvote? Am I wrong to expect syntax checking with code highlighting e.g. in Visual Studio Code (not using IDEA)?

None of your workarounds show this working, as far as I can tell.

Do you believe what I'm asking to be technically impossible?

If not, is there a reason why it can't be fixed soon? It is definitely important, as I use ngClass a lot, and it's not currently syntax highlighting bad references...

Could you be more clear, step-by-step, as I'm not familiar with the different compilers, etc.

**Comment by alexzuza** [comment]
@splincode 

> Stackblitz uses JIT-compiler in runtime.

Stackblitz has integrated angular language service

https://twitter.com/ericsimons40/status/976154412690345984

**Comment by JoostK** [comment]
Type checking of `ngClass` and `ngStyle` is working correctly for me now, so closing as resolved at some point.
