### ISSUE TITLE
包含子表单组件的表单，无法实时验证valid永远是false

### ISSUE THREAD

**Issue by lijiadashaoye** [angular/angular#24007]
父表单
<form [formGroup]="froms" (ngSubmit)="isSubmit(froms,$event)">
  <input type="text" placeholder="第一个" formControlName="one1">
  <input type="text" placeholder="第二个" formControlName="two1">
  <app-one-child3-child formControlName="three" (isvalid)="childValid($event)"></app-one-child3-child>
  <br>
  <button type="submit">提交</button>{{froms.value|json}}
  <br>froms.valid : {{froms.valid | json}}
</form>

@Component({
  selector: 'app-one-child3',
  templateUrl: './one-child3.component.html',
  styleUrls: ['./one-child3.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class OneChild3Component implements OnInit {
  froms: FormGroup;
  constructor(private fb: FormBuilder) { }

  ngOnInit() {
    this.froms = this.fb.group({
      one1: ['', Validators.compose([Validators.required, this.oneValid])],
      two1: ['', Validators.compose([Validators.required, this.oneValid])],
      three: [{ child1: 'lichild1', child2: 'lichild2' },Validators.required]
    })
  }
  isSubmit(froms, ev: Event) {
    ev.preventDefault()
    console.log(froms.value)
    console.log(froms)
  }
  // 表单内单独添加验证函数
  oneValid(c: FormControl): { [key: string]: any } {  // 验证器只有出错时才返回值,
    if (!c.value) {
      return null
    }
    let data = /^li/;
    if (data.test(c.value)) {
      return null
    }
    return {
      validData: '验证不通过'
    }
  }
  childValid(e) {
    console.log(e)
  }

}
表单组件：app-one-child3-child

<form [formGroup]="froms">
  <input type="text" placeholder="child-1" formControlName="child1">
  <input type="text" placeholder="child-2" formControlName="child2">

  <br>child.valid:{{froms.controls['child1'].valid|json}}
  <br>child.errors:{{froms.controls['child1'].errors|json}}
</form>

@Component({
  selector: 'app-one-child3-child',
  templateUrl: './one-child3-child.component.html',
  styleUrls: ['./one-child3-child.component.css'],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => OneChild3ChildComponent),
      multi: true
    },
    {
      provide: NG_VALIDATORS,  //  下边需要写以 validate 为名字的验证函数
      useExisting: forwardRef(() => OneChild3ChildComponent),
      multi: true
    }
  ]
})
export class OneChild3ChildComponent implements OnInit, ControlValueAccessor {
  @Output() isvalid=new EventEmitter<boolean>();
  froms: FormGroup;
  registerOnChanged;  // 用来承接向上传递数据的函数
  makeChild;
  constructor(private fb: FormBuilder) { }

  ngOnInit() {
    this.froms = this.fb.group({
      child1: ['', Validators.compose([Validators.required, this.validate])],
      child2: ['', Validators.required]
    })
  }
  isSubmit(froms, ev: Event) {
    ev.preventDefault();
    this.registerOnChanged(this.froms.value);
  }
  makeChild2() {
    this.makeChild='两个input框实现change联动'
    this.isvalid.emit(true);
  }

  validate(c: FormControl): { [key: string]: any } {  // 验证器只有出错时才返回值
    if (!c.value) {
      return null
    }
    let data = /^li/;
    if (data.test(c.value)) {
      return null
    }
    return {
      'child1-valid': '第二个表单验证不通过'
    }

  }
  //ControlValueAccessor 必须有的三个函数
  writeValue(obj: any): void {   // obj根据传进来的数据而定类型string?object?array?
    this.froms.get('child1').patchValue(obj.child1);  // 初始化值
    this.froms.get('child2').patchValue(obj.child2);
  }
  registerOnChange(fn: any): void {
    this.registerOnChanged = fn
  }
  registerOnTouched(fn: any): void { }
}

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by IgorMinar** [comment]
I'm sorry but we don't understand the subject and content of this issue.

Angular is being worked on by a diverse team of people and in order for us to be able to collaborate we use a common communication language. English is the communication language that many of us have adopted for this purpose.

Can you please translate your issue to English or work with an English speaking community member to create an issue in English? Thank you for understanding.
