### ISSUE TITLE
Unable to count the amount of filtered data  from [(ngModel)]  in angular4

### ISSUE THREAD

**Issue by suchetaswabhav** [angular/angular#24009]
I want to change the count of the filterdata [i.e. [(ngModel)]="filterdata"] after the data has arrived in the tables. For Example:

![image](https://user-images.githubusercontent.com/37062796/40268298-7e67e3e0-5b88-11e8-9281-974cfc13c589.png)

Initially in the text-box, i entered "experia" so all the data from the database that has experia appeared in the table. And the number of data is displayed on the right-hand of the table as you can see in the picture => "Number of searched data = 6". However, the issue is, if i enter text again in the search-text box and the data filters, but this filtered data number is not displayed, like "Number of searched data =4", of course this number will be less than the maximum number i.e.=6.It remains the same as >> "Number of searched data = 6" even though the total data displayed number is 4.

I have used an (ngModelChange) because i thought it might work, but it doesn't.

code:

transaction.component.html

<input class="form-control" id="input1-group1" style="margin-
top:20px" type="text" name="search" placeholder="Enter Search Text"
[(ngModel)]="filterdata" (ngModelChange)=
"countFilter(filterdata)"(keyup.enter)="searchByText(filterdata)">

//code

Transaction
Number of searched data : {{arrayCount}}
transaction.component.ts

countFilter(filtData){

console.log("inside countFilter = "+ filtData)
this.countFilterData = filtData.length;

if(this.arrayCount>=0){

  if(this.countFilterData<this.arrayCount){
     
  // console.log("inside if -arrayCount = "+ this.arrayCount)
  //   this.arrayCount=this.countFilterData;

  var result = [];
  var url = config.url;
  var port = config.port;

  this.http.post("http://" + url + ":" + port + "/transaction/masterSearchTransactionForm/", this.filterObj
  , { headers: new Headers({ 'Authorization': 'Bearer ' + localStorage.getItem('Token') }) })
  .map(result => this.result = result.json())
  .subscribe((res: Response) => {
    console.log("# DATE FILTER RESULT TRANSACTION  XXXXXXXXXXXX", res);
     this.records = res;

     this.toShowCount =true;
    console.log ("the result of SearchByText is =  ", this.result)
     this.arrayCount = this.result.length;
     console.log("ArrayCount = " , this.arrayCount)
     console.log("search-by-text  records = ",res)

    console.log("Search by Text result is : " + result)
    if (this.result.length > 0) {

      this.notify.Success("Data Displayed Successfully");
      this.loading = false;

    }
    else {
      this.notify.Error("No Matching Data Available")
      // this.dateTransactionForm.reset();
      this.loading = false;

    }
  });

  }
}

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mlc-mlapis** [comment]
@suchetaswabhav ... why do you show such a big description from a real app when it is not easy to understand on the first look instead of a really trivial online sample of the principle instead (using http://stackblitz.com)?

Don't you think that it is a difference to spend 20 mins on it or just look and answer during 1 min?
