### ISSUE TITLE
AOT fails with latest upgrded version of compiler-cli

### ISSUE THREAD

**Issue by arooran** [angular/angular#24004]
Created new angular project with latest version 6. But when I compile with AOT using tsconfig-aot.json. getting error in the compiler-cli.

used latest typescript version 2.8.3 then downgraded to 2.7.2 but no luck.

![image](https://user-images.githubusercontent.com/4504096/40262632-b97bf4a4-5b00-11e8-93e1-4b195937f087.png)

![image](https://user-images.githubusercontent.com/4504096/40262619-9bfc212e-5b00-11e8-9932-2e8eed27e498.png)

**Comment by splincode** [comment]
Ask this question on stackoverflow

**Comment by jotatoledo** [comment]
Please fill the issue template, otherwise is hard to tell if this is an issue related to your local configuration or a possible bug.

**Comment by arooran** [comment]
I will move this question to stackoverflow
