### ISSUE TITLE
IE11 does not support attribute binding for HTML5 progress value attribute

### ISSUE THREAD

**Issue by lizschwab** [angular/angular#24001]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

In IE11 (possibly other versions) the HTML5 progress tag's value attribute does not work when using attribute binding. Rather than binding the value supplied, it defaults to 1. It works when the value is static, and the max attribute works. Here's an example of the issue. https://stackblitz.com/edit/angular-hp8nc4

I see that this was an issue in angular.js as well and was resolved using the ng-attr-value directive.
https://docs.angularjs.org/guide/ie
https://github.com/angular/angular.js/issues/7218

## Expected behavior
Progress tag should show the appropriate value binded using [attr.value] binding.

## Minimal reproduction of the problem with instructions

1. Add a <progress></progress> tag to an Angular app.
2. Bind the value attribute to a variable inside the component using [attr.value]="variableName".
3. Set the value to a number other than one and set a desired max.

https://stackblitz.com/edit/angular-hp8nc4

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x ] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

Windows 10
</code></pre>

**Comment by vicb** [comment]
I suspect the bug is with IE11 itself as `[attr.value]` will result in calling [`element.setAttribute()`](https://github.com/angular/angular/blob/23a98b9e5134df3b96dd932173ce86384d72ada0/packages/platform-browser/src/dom/dom_renderer.ts#L158).

If you manage to set the `value` attribute successfully in IE please re-open the issue with that code and we will look at it (for this test, use the DOM APIs outside of Angular)
