### ISSUE TITLE
New logo for ANGULAR

### ISSUE THREAD

**Issue by k-syusteem** [angular/angular#24018]
<b>Hello!</b> I have designed a logo for "Angular", I hope you are interested. Give your assessment so I can solve a problem related to the logo you want for "Angular".

![web](https://user-images.githubusercontent.com/38687140/40281502-0387c9b4-5c8d-11e8-961f-f15ddf820d32.png)

![01](https://user-images.githubusercontent.com/38687140/40281504-0d60c6ca-5c8d-11e8-8b08-daa0aa5c3ab5.png)

![02](https://user-images.githubusercontent.com/38687140/40281505-1928a68a-5c8d-11e8-9d68-9273d6821d35.png)

![03](https://user-images.githubusercontent.com/38687140/40281508-24886bfa-5c8d-11e8-9737-0587bdc1b46a.png)

<i>@k-syusteem</i>

**Comment by sandangel** [comment]
I think you should try changing only the shape inside 6 sided polygon, not the whole logo.

**Comment by Insidexa** [comment]
sorry, but the concept of the "corner" logo is lost

**Comment by k-syusteem** [comment]
@Insidexa I agree with, maybe I should correctly understand the concept of ”corner”

**Comment by robwormald** [comment]
Thanks for the idea, but we are happy with our existing logo, and lots of communities around angular use it so we have no desire to change it at this time!
