### ISSUE TITLE
`moduleNameToFileName` is being invoked for modules that are not imported and not invoked for those which are

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#24010]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I noticed that the compiler host method `moduleNameToFileName` is being invoked for modules which are not being imported or exported, and is not invoked with modules that are being imported.

## Expected behavior
To be invoked with modules that are imported and exported.

## Minimal reproduction of the problem with instructions
For instance in the below it's being invoked with `@angular/core` which I am never importing and it's never being invoked with `shared` which I am importing.

public_api.ts
```ts
import * as shared from 'shared';

export {
    shared
}
```
shared.ts
```ts
export const title = 'hello world';
```

tsconfig
```js
paths: {
    'shared': [
	'./src/shared/shared.ts'
     ]
}
```

build.ts
```ts
const host = {
	...ng.createCompilerHost({ options }),
	moduleNameToFileName: (moduleName: string, containingFile: string) => {
		const { resolvedModule } = ts.resolveModuleName(
			moduleName,
			ensureUnixPath(containingFile),
			options,
			host
		);

		if (containingFile.indexOf('node_modules') <= 0) {
			console.log({ moduleName, containingFile });
		}

		return resolvedModule && resolvedModule.resolvedFileName;
	}
};

const program = ng.createProgram({
	rootNames: [path.resolve('./src/public_api.ts')],
	options,
	host
});

program.getNgStructuralDiagnostics()
```
output
```shell
{ moduleName: '@angular/core',
  containingFile: '/Users/alan/git/src/public_api.ts' }
{ moduleName: '@angular/core',
  containingFile: '/Users/alan/git/src/public_api.ts' }
{ moduleName: '@angular/core',
  containingFile: '/Users/alan/git/src/public_api.ts' }
{ moduleName: '@angular/router',
  containingFile: '/Users/alan/git/src/public_api.ts' }
...
```

Reproduction repo 
https://github.com/alan-agius4/angular-issue-host-24010/blob/master/build.ts#L36

## Environment

<pre><code>
Angular version: 6.0.2

</code></pre>

**Comment by JoostK** [comment]
During initialization of the static reflector, the ViewEngine compiler creates a lookup structure for common Angular symbols:

https://github.com/angular/angular/blob/86e1e6c0823a6a8cf4314a655eaa6aef14a474b8/packages/compiler/src/aot/static_reflector.ts#L381-L430

In Ivy, the `ng.CompilerHost.moduleNameToFileName` method is no longer considered, only the standard `ts.CompilerHost.resolveModuleNames` is used.
