### ISSUE TITLE
ProvidedIn Annotation Not Compatible With Deriving Classes

### ISSUE THREAD

**Issue by Jackthomsonn** [angular/angular#24011]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using the `providedIn` annotation on a derived class, the derived class does not internally get a factory created. This is down to the `ngInjectableDef` property that is already set and when the providedIn is invoked, it can see that `ngInjectableDef` is already set on it's parent so it does not get set again. To get around this issue, in any deriving classes we have to set `ngInjectableDef` to undefined. This in turn, invokes the providedIn logic to create a factory for us

## Expected behavior

We should be able to use the `providedIn` annotation as normal on any deriving classes without the need of setting the `ngInjectableDef` property back to undefined.

## Minimal reproduction of the problem with instructions

```
@Injectable({
  providedIn: 'root'
})

export class BaseService {
  public name: string = 'Test'

  public get() {
    return this.name;
  }
}

@Injectable({
  providedIn: 'root'
})

export class TestService extends BaseService {
  // This service is not available in our application
  // [Fix]: static ngInjectableDef = undefined or we import this service in our app.module in the 
  // 'imports' section
}
```

## What is the motivation / use case for changing the behavior?

We should have the same behaviour in deriving classes as we do in our base classes

## Environment

<pre><code>
Angular version: X.Y.Z

6.0.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by TomDemulierChevret** [comment]
Any update on this ?
