### ISSUE TITLE
Missing word in documentation

### ISSUE THREAD

**Issue by TristanMarion** [angular/angular#24017]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In the [Frequently Used Modules](https://angular.io/guide/frequent-ngmodules) page, a word is missing in the array of modules.
The `HttpClientModule` description is `When you to talk to a server`.

## Expected behavior

It should be `When you want/need to talk to a server`

**Comment by jotatoledo** [comment]
Hey @TristanMarion, why dont you submit a pr for this? :)

**Comment by gkalpak** [comment]
All the descriptions are a bit inconsistent (e.g. `when you want to...` vs `when you build...` vs `when building...` vs `for routing...`). If anyone feels like cleaning them up, they are more than welcome to submit a PR :grin:

cc @jenniferfell

**Comment by TristanMarion** [comment]
Hey @jotatoledo, 
I could have done a PR that's right 😅

Thanks @alan-agius4 !
