### ISSUE TITLE
error TS2322: Type 'number' is not assignable to type 'String'.

### ISSUE THREAD

**Issue by jbiddulph** [angular/angular#24015]
**ERROR in src/app/components/add-item/add-item.component.ts(28,7): error TS2322: Type 'number' is not assignable to type 'String'.
src/app/components/items/items.component.ts(29,5): error TS2322: Type 'true' is not assignable to type 'false'.**

<code>
export class AddItemComponent implements OnInit {
  date: Number;
  item: Item = {
    title: '',
    description: '',
    date: ''
  };

  constructor(private itemService: ItemService) { }

  ngOnInit() {
  }

  onSubmit() {
    if (this.item.title !== '' && this.item.description !== '') {
      this.itemService.addItem(this.item);
      this.item.title = '';
      this.item.description = '';
      this.item.date = new Date().getTime();
    }
  }

}
</code>

**Comment by splincode** [comment]
Ask this question on stackoverflow
