### ISSUE TITLE
The component of a route should be destroyed if route is refreshed and guard returns false

### ISSUE THREAD

**Issue by maximedupre** [angular/angular#24012]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Expected
When navigating on the same url, if the guard blocks the navigation by returning `false`, the component of that route should be destroyed.

## Current
Instead, the guard is called again on "reload" and it returns false, but the component is still displayed. 

If the guard blocks the current route, why is the component spawned by the `router-outlet` for this route still displayed? The component was initially displayed when the guard indeed returned true, but since it is not the case anymore on refresh, it should be destroyed.

## Minimal reproduction of the problem with instructions

    const appRoutes: Routes = [
        { path: '', component: AreasComponent, canActivate: [AuthGuardService], runGuardsAndResolvers: 'always' },
        { path: 'confirmation', component: ConfirmationComponent }
    ];

    @NgModule({
        declarations: [AppComponent, ConfirmationComponent, AreasComponent],
	    imports: [BrowserModule, HttpClientModule, FormsModule, RouterModule.forRoot(appRoutes, { onSameUrlNavigation: 'reload' })],
	    providers: [UsersService, TokensService, AuthGuardService, { provide: HTTP_INTERCEPTORS, useClass: InterceptorService, multi: true }],
	    bootstrap: [AppComponent]
    })    
    export class AppModule { }

Then, in `AppComponent`, where my `router-outlet` is, if I navigate to the current route (`this.router.navigate(['']);`),  assuming `AuthGuardService.canActivate` returns false, `AreasComponent` is still displayed.

## What is the motivation / use case for changing the behavior?

My AuthGuardService verifies if the user is logged in or out. On logout is when it navigates to the current route. The AuthGuard returns false, because the user is not allowed to view the site's content anymore.

## Environment

<pre><code>
Angular version: 6.0.2"

Browser:
- [x] Chrome (desktop) version 66

**Comment by mlc-mlapis** [comment]
@maximedupre ... hm, on the beginning a component instance is not created at all when the guard returns `false` but here it would mean that something is replaced by nothing. It is certainly logical to imagine such a functionality but I think it is also a matter of prioritization.

Actually you can do the similar effect by using separate route for a login and navigating to another route directly in the guard when a user shouldn't have access already.

**Comment by maximedupre** [comment]
@splincode This ticket does not describe a memory leak.

@mlc-mlapis Thank you for proposing an alternative, but there would be no where else to navigate in the guard. All of my routes should display something only if the user is logged in (if the guard returns true)

**Comment by jasonaden** [comment]
I think I'm understanding this request correctly. But I also think this use case is not supported nor is it intended to be supported currently. The guards are basically there to tell whether or not a route should be activated. If a guard returns false, it's going to not activate anything, leave the previously activated route there, and give you a `NavigationCancel` event.

In the future we should have an API by which you can use a live Observable to have much more fine-grained control over how guards and resolvers behave in relation to components.
