### ISSUE TITLE
Angular 6.0 changing Locale to NL, DE or FR doesn't work! [Solved]

### ISSUE THREAD

**Issue by TolgaBA** [angular/angular#24028]
I am new to Angular, but I am a professional programmer and I am trying to change decimal symbol from '.' to ',' by changing the Locale configuration to 'nl'. So I have been trying my best to search how to do this and came to the following documentation link: https://angular.io/guide/i18n#i18n-pipes. I tried to apply the code as what they recommended me to do by adding the following to the app.module.ts file:

```
import { NgModule, LOCALE_ID } from '@angular/core';

@NgModule({
..
providers: [ { provide: LOCALE_ID, useValue: 'fr' } ]
..
})
```

And I got the following error message on my Chrome browser console:

`ERROR Error: InvalidPipeArgument: 'Missing locale data for the locale "fr".' for pipe 'DecimalPipe'.`

I get the following message when I use this code:

`ng serve --configuration=fr`

result:
```
Configuration 'fr' could not be found in project 'ng6'.
Error: Configuration 'fr' could not be found in project 'ng6'.
    at Architect.getBuilderConfiguration (/Users/noble/Development/bitarea/node_modules/@angular-devkit/architect/src/architect.js:106:23)
    at MergeMapSubscriber._loadWorkspaceAndArchitect.pipe.operators_1.concatMap [as project] (/Users/noble/Development/bitarea/node_modules/@angular/cli/models/architect-command.js:64:55)
    at MergeMapSubscriber._tryNext (/Users/noble/Development/bitarea/node_modules/rxjs/internal/operators/mergeMap.js:122:27)
    at MergeMapSubscriber._next (/Users/noble/Development/bitarea/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/Users/noble/Development/bitarea/node_modules/rxjs/internal/Subscriber.js:103:18)
    at TapSubscriber._next (/Users/noble/Development/bitarea/node_modules/rxjs/internal/operators/tap.js:109:26)
    at TapSubscriber.Subscriber.next (/Users/noble/Development/bitarea/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (/Users/noble/Development/bitarea/node_modules/rxjs/internal/operators/mergeMap.js:141:26)
    at InnerSubscriber._next (/Users/noble/Development/bitarea/node_modules/rxjs/internal/InnerSubscriber.js:30:21)
    at InnerSubscriber.Subscriber.next (/Users/noble/Development/bitarea/node_modules/rxjs/internal/Subscriber.js:103:18)
```

## I'm submitting a...

<pre><code>
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: 6.0.1
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.1
@angular-devkit/build-angular     0.6.1
@angular-devkit/build-optimizer   0.6.1
@angular-devkit/core              0.6.1
@angular-devkit/schematics        0.6.1
@ngtools/webpack                  6.0.1
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

Browser:
- [ ] Chrome (desktop) version 66.0.3359.139 (Official Build) (64-bit)
 
For Tooling issues:
- Node version: v9.7.1
- Platform: Mac
</code></pre>

## Solved!
So by adding the following code to the app.module.ts file did solve the issue:

```
import { registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/locales/fr';

registerLocaleData(localeFr, 'fr');
```

**Comment by Lakston** [comment]
You should close your issue if you found the problem :)

**Comment by serhioV** [comment]
when doing `ng serve --configuration=fr -o` I also had 

> Configuration 'fr' could not be found in project 'ClientApp'.

but putting 

```
import { registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/locales/fr';

registerLocaleData(localeFr, 'fr');
```
in the app.module.ts didn't solve the problem. I have dates displayed in English using `| date: "medium"` filter...

**Comment by izerozlu** [comment]
> when doing `ng serve --configuration=fr -o` I also had
> 
> > Configuration 'fr' could not be found in project 'ClientApp'.
> 
> but putting
> 
> ```
> import { registerLocaleData } from '@angular/common';
> import localeFr from '@angular/common/locales/fr';
> 
> registerLocaleData(localeFr, 'fr');
> ```
> 
> in the app.module.ts didn't solve the problem. I have dates displayed in English using `| date: "medium"` filter...

After import you should set your locale via

```
@NgModule({
  providers: [
    { provide: LOCALE_ID, useValue: "en-US" }, //replace "en-US" with your locale
    //otherProviders...
  ]
})
```

answer found from: https://stackoverflow.com/a/39344889/5182352

**Comment by serhioV** [comment]
> > when doing `ng serve --configuration=fr -o` I also had
> > > Configuration 'fr' could not be found in project 'ClientApp'.
> > 
> > 
> > but putting
> > ```
> > import { registerLocaleData } from '@angular/common';
> > import localeFr from '@angular/common/locales/fr';
> > 
> > registerLocaleData(localeFr, 'fr');
> > ```
> > 
> > 
> > in the app.module.ts didn't solve the problem. I have dates displayed in English using `| date: "medium"` filter...
> 
> I know this comment is old and this issue is already closed. But i'm leaving message below for the future answer seekers.
> 
> After import you should set your locale via
> 
> ```
> @NgModule({
>   providers: [
>     { provide: LOCALE_ID, useValue: "en-US" }, //replace "en-US" with your locale
>     //otherProviders...
>   ]
> })
> ```
> 
> answer found from: https://stackoverflow.com/a/39344889/5182352

Fixed by the team in the docs, see https://github.com/brandonroberts/angular/commit/bd0c2b41ffc212b667583648525f5519854a237e
