### ISSUE TITLE
pre-select radio button from list by index based condition in  radio [checked] = "i===0" angular 5.2.9

### ISSUE THREAD

**Issue by gowthamzinc** [angular/angular#24023]
cant able to pre-select radio button from list by index based condition  [checked] = "i===0"

`<div class="left-menu" *ngFor="let position of allStyles">
        <div class="checkbox" *ngFor="let subpostion of position.sub_position.items; index as i" >`
          `  <label>`
                ` <input type="radio" [id]="position.position_name+i" [name]="'group'+position.position_name" [value]="subpostion.id" [(ngModel)]="custom[position.position_name]"  [checked]="i === 0" >
                      {{subpostion.subposition_name}}`
          `  </label>`
        ` </div>`
`</div>`

angular 5.2.9

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
