### ISSUE TITLE
i18n Angular 5.x to Angular 6.0

### ISSUE THREAD

**Issue by DavideCarvalho** [angular/angular#24021]
## I'm submitting a...

<pre><code>
[ x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I've updated my Angular application from 5 to 6. It uses i18n to portuguese language, so all the currency is shown as R$, but when i updated to 6, The currency started showing US$ instead of R$

## Expected behavior

Currency pipe should've stayed the same, showing R$ instead of US$

## Environment

<pre><code>
Angular version: 6.0.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.11.1
- Platform:  Mac

Others:

</code></pre>

**Comment by splincode** [comment]
You can ask a question on stackoverflow

**Comment by TolgaBA** [comment]
It seems that we can't change currency because the following doesn't work:
`providers: [ { provide: LOCALE_ID, useValue: 'fr' } ],`

The same applies for nl, de, etc...!!

**Comment by vicb** [comment]
Please provide a repro.
We have customer using i18n w/o pbs on 6, I suspect something wrong with your code.

**Comment by vicb** [comment]
Closing as no repro provided.

Please open a new issue if the issue persists
