### ISSUE TITLE
Initial animation state on server side rendering ignored

### ISSUE THREAD

**Issue by visurel** [angular/angular#24033]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When relying on @angular/animation to show or hide a dropdown, since the animation are done on browser side, server side rendering shows elements that should be hidden.
Using BrowserAnimationsModule, or NoopBrowserAnimationsModule in server.modules doesn't do the trick (neither triggers any errors)

## Expected behavior

The rendered HTML from server should include the initial state of the animations (hidden, if something is hidden in the initial state, collapsed if something is collapsed, a fixed height if there's a fixed height set, ...)

## What is the motivation / use case for changing the behavior?
A smoother transition from the server rendered application to the actual app. (Without showing content that should be hidden or even a simple expanded/collapsed animation that should be collapsed by default)

## Environment
<pre><code>
Angular version: 6.0.0

Browser:
- [all] Browsers

Others:

</code></pre>

**Comment by visurel** [comment]
Related to https://github.com/angular/universal/issues/716

**Comment by vikerman** [comment]
Server includes NoopAnimationsModule by default but there should be no events on the server that actually trigger the animation. Can you describe your setup more?
