### ISSUE TITLE
[IVY] Bug in the binding mechanism ?

### ISSUE THREAD

**Issue by vicb** [angular/angular#24036]
Given the `bind` implementation:

```typescript
export function bind<T>(value: T | NO_CHANGE): T|NO_CHANGE {
  if (currentView.bindingStartIndex < 0) {
    initBindings();
    return data[currentView.bindingIndex++] = value;
  }

  const changed: boolean =
      value !== NO_CHANGE && isDifferent(data[currentView.bindingIndex], value);
  if (changed) {
    throwErrorIfNoChangesMode(
        creationMode, checkNoChangesMode, data[currentView.bindingIndex], value);
    data[currentView.bindingIndex] = value;
  }
  currentView.bindingIndex++;
  return changed ? value : NO_CHANGE;
}
```

I think that there might be a bug with the following code in a template fn:
```typescript
function template(flags, ctx) {
  // ...
  if (flag & UPDATE) {
    bind(ctx.value0);
    bind(ctx.value1);
  }
```

`bind(ctx.value0);` will trigger the first `if` and initialize the binding system.

`bind(ctx.value1);` will not trigger the first `if` and skip to `isDifferent(data[currentView.bindingIndex], value)`. If value1 is `undefined` (the value of `data[currentView.bindingIndex]`) `bind` will return `NO_CHANGE`.

However `NO_CHANGE` should never ever be returned on the first check.

Possible solutions:
- Pre-allocate the binding "slots" with and init them to a unique value (could be `NO_CHANGE` or any other unique/non-exposed value). Tracking the number of binding slots would be more work for the compiler but would have 0 impact at runtime,
- Update the runtime to not return `NO_CHANGE` on the first `template()` pass for a view. This would not require changes on the compiler side but there would be a test added to every single execution each binding. Note that short circuiting should not be a problem as they are store in a different location and the issue has been taken into account during the design (PR to come).

Note: `bind` and `interpolationX()` are affected. `pureFunctionX()` will not when the short-circuiting PR lands.

**Comment by pkozlowski-opensource** [comment]
The `bind` implementation changed completely so I don't think this issue is relevant any more. Closing.
