### ISSUE TITLE
Angular5 program production mode (ng build - prod) cannot run under low version (47.0.1) of firefox

### ISSUE THREAD

**Issue by jerrypotti** [angular/angular#24030]
Angular5 program production mode (ng build --prod) cannot run under low version (47.0.1) of firefox, but development environment model (ng build), can I put the polyfills.ts of compatible file is opened, or no, consult the solution, thanks.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
