### ISSUE TITLE
"Tagged template expressions are not supported in metadata." during AOT build with Angular 6, built successfully with Angular 5

### ISSUE THREAD

**Issue by joeattardi** [angular/angular#24031]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I am consuming a library built with Angular CLI 6/ng-packagr in my application. In this library is defined a decorator, `RestRequest` that takes a tagged template literal as its argument. For example:

```
@RestRequest(RestUrl`POST /ab_test_search`)
 search(@RestBodyParam() config: {}): Observable<ABTestSearchResult> {
    return RestResponse;
 }
```

When I try to do an AOT build of the applcation, I get the error:

```
src/app/resources/bootstrap/bootstrap.resource.ts:34:16: Metadata collected contains an error that will be reported at runtime: Tagged template expressions are not supported in metadata.
```

Before updating to Angular 6, the AOT build was successful for this project.

## Expected behavior
The AOT build is successful.

## Minimal reproduction of the problem with instructions
Use a tagged template literal as the argument to a method decorator as shown above.

## Environment

<pre><code>
Angular CLI: 6.0.1
Node: 9.11.1
OS: darwin x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.1
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.1
@angular-devkit/schematics        0.6.1
@angular/cdk                      5.2.5
@angular/cli                      6.0.1
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3

For Tooling issues:
- Node version: 9.11.1
- Platform:  Mac

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/23997

**Comment by vicb** [comment]
Not related to Angular but ng-packagr (see #23997)
