### ISSUE TITLE
lifecycle method onChange called before onInit and onCheck

### ISSUE THREAD

**Issue by ibhi** [angular/angular#2404]
I have attached `onInit, onCheck, onChange`, and `onAllChangesDone` lifecycle methods attached to a component(to reason about the sequence in which these methods get called). When the component is instantiated, its `onChange` method is called first, then `onInit`, `onCheck` and `onAllChangesDone` methods are called in sequence. 
The docs says `onChange` 
> Notify a directive when any of its bindings have changed.
> This method is called right after the directive's bindings have been checked, and before any of its children's bindings have been checked.
> It is invoked only if at least one of the directive's bindings has changed.

1. Why `onChange` is called initially when the component is instantiating?
2. And whenever I change the value of a property on the component, `onChange` is fired first before `onCheck`. Is this intended behavior?

Here is a simple plunker for the above question -> http://plnkr.co/edit/sk6Xi7L6a7ob9xiRJaSJ?p=preview. View the console for the sequence.

**Comment by vicb** [comment]
1. It is called *after* the component have been instantiated (vs being instantiated in your comment) to render the initial state.
2. We do not currently document any specific call order when multiple events are called. The actual order is [change, init and check](https://github.com/angular/angular/blob/d1b35f9174dbef808fdff655f9c4b42b1c125242/modules/angular2/src/core/compiler/proto_view_factory.ts#L99). @ibhi do you have an use case where the order matters ? @vsavkin should we document this ?

**Comment by ibhi** [comment]
@vicb , Thanks for your quick response.
I do not have any use case for the order now, but If I come across, I will share it here.

**Comment by vsavkin** [comment]
We sort of document it in this test `directive_lifecycle_integration_spec.ts`.

**Comment by vicb** [comment]
@vsavkin it could be valuable to have this in the docs, I'll send a PR tomorrow.

**Comment by poshest** [comment]
+1 for `$onInit` being called before `$onChanges`. I think that's the way most people would expect it. I also have many use cases for an init function which `$onChanges` depends on already having been called. I don't have a single use case for the other way around.
