### ISSUE TITLE
ServiceWorker will not get installed if there is Landing page Redirection

### ISSUE THREAD

**Issue by arangates** [angular/angular#24043]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
`Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`
`SecurityError: Failed to register a ServiceWorker: The script resource is behind a redirect, which is disallowed`

## Expected behavior
ServiceWorkers should be installed after redirection is complete. 

## Minimal reproduction of the problem with instructions
1. Build application with some --base-href
2. Serve the application 
3. Open console to see the Security Error.
![screenshot from 2018-05-22 10-09-38](https://user-images.githubusercontent.com/7692801/40349916-5ce7c0f6-5da8-11e8-9de4-3d322d299a39.png)

## use case ?
There are many applications which does landing page redirection. if the user tries to go to **example.com** it will be redirected to **example.com/en/** in such cases it is not possible to serviceworker as of now.

## Environment

```
Angular CLI: 6.0.0
Node: 9.6.1
OS: linux x64
Angular: 6.0.0
... cli, common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.0.28
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack     4.6.0

```

**Comment by gkalpak** [comment]
Can you please post a minimal reproduction (e.g. exact steps to follow or a minimal repo we can check out and inspect)?

(This is likely related to  angular/angular-cli#8515.)

**Comment by arangates** [comment]
Related to  angular/angular-cli#8515
