### ISSUE TITLE
Cannot use string enum values into animation functions with prod flag enabled

### ISSUE THREAD

**Issue by IlCallo** [angular/angular#24047]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I've created an animation with multiple states.
States have been saved into a string enum object.

If I use the enum into the `animations` decorator property functions (`state` and `transition` in this case) without `--prod` flag everything works fine.

When I try to compile it for production environment, the app breaks and this error is fired.
```
TypeError: Cannot read property 'toString' of null
    at main.548e98b8c7d2ad1cacd5.js:1
    at Array.forEach (<anonymous>)
    at t.visitTrigger (main.548e98b8c7d2ad1cacd5.js:1)
    at Mp (main.548e98b8c7d2ad1cacd5.js:1)
    at t.build (main.548e98b8c7d2ad1cacd5.js:1)
    at Up (main.548e98b8c7d2ad1cacd5.js:1)
    at e.t.registerTrigger (main.548e98b8c7d2ad1cacd5.js:1)
    at main.548e98b8c7d2ad1cacd5.js:1
    at Array.forEach (<anonymous>)
    at t.createRenderer (main.548e98b8c7d2ad1cacd5.js:1)
```

If I change the enum values with their corresponding literal values everything works as expected.
If I use `const enum`, which should substitute every occurrence of the enum values at compile time as stated in TypeScript docs, the error persists.

## Expected behavior
That everything works fine using enums, even using AOT compilation.

## Minimal reproduction of the problem with instructions
State enum example
```
enum States {
  StateOne = 'STATE_ONE',
  StateTwo = 'STATE_TWO',
}
```

Example of usage (here I use template strings but the problem is present even with the more basic `States.StateOne + ' => ' + States.StateTwo`)
```
@Component({
  selector: 'app-component',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.scss' ],
  animations: [
    trigger('prettyFade', [
      state(States.StateOne, style({ opacity: 0 })),
      state(States.StateTwo, style({ opacity: 1 })),
      transition(`${States.StateOne} => ${States.StateTwo}`, animate('12s')),
      transition(`${States.StateTwo} => ${States.StateOne}`, animate('1.3s')),
    ])
  ],
})
```

## Environment

<pre><code>
Angular version: 6.0.2
Typescript version: 2.8.3 (but the error persists also using 2.7.2)
</code></pre>

**Comment by ericmartinezr** [comment]
Possibly related/dup https://github.com/angular/angular-cli/issues/10655 (can you verify?)

**Comment by IlCallo** [comment]
Tryed to set `"buildOptimizer": false` and launch again `ng serve -o --prod`: nothing changed, the error is still the same

**Comment by matsko** [comment]
This should've been cleaned up with this commit: https://github.com/angular/angular/commit/7be7abdebd6b8582642bf16e5102a32b30750e99

Any chance you could put together a project with @angular/cli and I can boot it up?

**Comment by matsko** [comment]
@IlCallo if you could make a stackblitz example then that would work as well.

**Comment by IlCallo** [comment]
With enum: https://stackblitz.com/edit/angular-qxbls6
Without enum: https://stackblitz.com/edit/angular-nk6dfm

They both work now but I guess it's because they go with the JIT compiler, I don't know how to set AOT compiler on stackblitz (first time I use it)

**Comment by matsko** [comment]
@IlCallo that's fine. I'll recreate this locally. Thank you.

**Comment by levgaas** [comment]
@IlCallo 

If you add `export` to the `enum`
Like this

```
export enum AnimationState {}
```
It'll work like a charm.

cc. @matsko

**Comment by IlCallo** [comment]
Can you please explain the underlying motivations?

**Comment by massimilianorango** [comment]
I just wasted 1 hour of debugging to find this. What's the reason behind the `export` keyword?

**Comment by ericzhangjx** [comment]
Same problem here, using `ng build` with `optimization: false` in angular.json.
Env: 
`Node v10.15.2`
`@angular/* v7.2.13`
`@angular/cli v7.3.8`

Use case:
```
  animations: [
    trigger('carousel', [
      state(CarouselState.Stay, style({ transform: `translateX(-100%)` })),
      state(CarouselState.MoveLeft, style({})),
      state(CarouselState.MoveRight, style({})),
    ]),
  ],
```

Both `enum` and `const enum` without `export` aren't gonna work:
```
const enum CarouselState {
  Stay = 'stay',
  MoveLeft = 'moveLeft',
  MoveRight = 'moveRight',
}
```
while adding `export` or using variable instead `const CarouselState = {}` can bypass this issue;



Here is the output (partial) of the broken case:
```
data: {
  'animation': [{
    type: 7,
    name: 'carousel',
    definitions: [{
      type: 0,
      name: null,
      styles: { type: 6, styles: { transform: 'translateX(-100%)' }, offset: null },
      options: undefined,
    }, {
      type: 0,
      name: null,
      styles: { type: 6, styles: {}, offset: null },
      options: undefined,
    }, {
      type: 0,
      name: null,
      styles: { type: 6, styles: {}, offset: null },
      options: undefined,
    }],
    options: {},
  }],
},
```

**Comment by JoostK** [comment]
This is no longer an issue in Ivy!
