### ISSUE TITLE
Can not pass value from parent component to a child via property in alfa-26

### ISSUE THREAD

**Issue by peter-svintsitskyi** [angular/angular#2405]
See the following plunk http://plnkr.co/edit/YwVBlAVLIzA4Dx0sAWIE
I have two components defined in parent-component.es6.js and I'm trying to pass data from ParentComponent to a ChildComponent using the "foo" property of the child component.

It works when I switch to previous version alfa-25.

**Comment by ibhi** [comment]
@peter-svintsitskyi - In alpha.26 the syntax for properties changed from object (key: value) to string array (List), So if you change the `properties: {'childFoo': 'foo'}` to `properties`: ['childFoo: foo']`. This will work.
http://plnkr.co/edit/1H4xpmCX9LFxngMyLZeW?p=preview

The change in syntax will enable us to not repeat, the directiveProperty name and bindingProperty names if they are same, for ex now we can write
`properties: ['foo']` -> this would mean `properties: ['foo: foo']`

**Comment by vicb** [comment]
When things are not working for a new release, you should first check [the changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md). We do out best to list beaking changes there.

**Comment by peter-svintsitskyi** [comment]
Thank you for your help. I did not notice it in the chagnelog.
