### ISSUE TITLE
Option to make xi18n extract every string into a separate unit

### ISSUE THREAD

**Issue by jaska45** [angular/angular#24052]
xi18n when extracting strings looks them by string values. If two or more location on templates or source code use the same string only one unit element will be created into XLIFF/XMB. It would be good to have an option that would make one unit element created for each string. So no unit element would be shared with multiple string instances.

This is because sometimes there is a need to translate the string in a different way depending on the context. For example we might have two templates both having word `hard`. In one template the meaning is _solid_ and on other the meaning is _difficult_. We also might have a word `access` that would be noun on one location but _verb_ on _another_.

Right now we have a workaround if we add meaning into i18n attribute. For example i18n="difficult|" and i18n="solid|". This will make two unit element to appear in XLIFF file. However this requires additional template editing (i.e. adding attribute value). Developers might not even notice the need to have a meaning until translator/tester will point it out. That time it might be too late. It would be good that there is an option to add a separate unit element for each string instance.

Extractor seems to use only string value and optional meaning value when calculating the hash code to be the id. To implement the above something else (unique to each string instance) should be added into id calculation equation. Right now I cannot figure out anything that wouldn't make the id too volatile in the case of template/code refactoring :-(  

Hope you have some ideas.

## I'm submitting a...
<pre><code>
[x] Feature request
</code></pre>

## Current behavior
If the same string appears more than once in templates or source code only only unit element is extracted to XLIFF/XMB

## Expected behavior
Optionally extract each string into a separate unit element.

## Minimal reproduction of the problem with instructions
Use the same string in two locations in the same template or different templates.

## What is the motivation / use case for changing the behavior?
Make localization quality better and the process easier.

## Environment
Angular version: all

**Comment by vicb** [comment]
What you are describing seems to be the exact reason why we have an optional "meaning".

I fail to see how extracting different message for "hard" would help if you do not have a meaning to disambiguate ? 

Maybe I miss something ? Adding a concrete example of what you would like to see might help. (Think that extracting is one thing but then we need to replace with the translations and they might be out of order)

**Comment by jaska45** [comment]
My point is that developers do not know if two same strings need to be translated in a different way. We will only see on translation or testing phase if this is the case. Then if we have all those strings mapped into single unit there is nothing we can do (except ask developers to add meaning, extract strings again). To avoid this the only solution is to ask them to add meaning to all i18n attributes. This will cause lots of string.

If each strings instance would be extracted in their own unit translator can translate them in a different way if needed. No need to go back to modify source code and to re-extract strings. Our localization tool can easily handle strings that have same value so you basically only translate once and that populates to other. Then if some instance need to be translate in a different way it can easily be done. Unfortunately as I just explaned not in the case when Angular is used.

For example desktop application that use UI resource might have the same string on multiple dialogs. However they do not share the resource string but each instance of the string generates its own resource item. This is pretty much one of the golden rule of localization that you do not use the same resource item on multiple context.

**Comment by jaska45** [comment]
Here is one example if noticed yesterday

On one template we have "_Search criteria_". That is a label to show possible search criteria. On another template the is a button that has label "_Search criteria_". Here them meaning is search by criteria. Both strings are the same so they map into once but meaning is very different and need to localized in a different way.

We already use meaning in the cases like this but if all strings already have a unique meaning (very difficult to generate) we need to modify the source and re-extract.

**Comment by jaska45** [comment]
Little bit more information. Because the id is calculated solely based string value and meaning value we going to get collisions from multiple string instances no matter where they are located. The only way to avoid this is to make that meaning value is unique among all strings in the project. This is difficult. If we have hundreds of template files and several developers working on the same project. Making sure that meaning value is unique gets hard.

My recommendation is to add a third parameter to the id calculation equation. In addition of string value and meaning value add the location value. This way collisions from same string will dramatically decrease and if you still use two or more same strings in the same file but with different meaning it is easier to add meaning because they need to be unique only among that file.

**Comment by vicb** [comment]
> My recommendation is to add a third parameter to the id calculation equation. In addition of string value and meaning value add the location value.

That could be a solution.

However in your exemple:

> On one template we have "Search criteria". That is a label to show possible search criteria. On another template the is a button that has label "Search criteria". Here them meaning is search by criteria. Both strings are the same so they map into once but meaning is very different and need to localized in a different way.

Let's say you now have two "Search criteria" strings because they are in location1 and location2.

How does the translator knows that "Search criteria" meaning in location2 is "search by criteria" ? i.e. I don't see location as an improvement in this particular case. To me this is a great exemple of how meaning help disambiguate.

I am probably missing something ?

**Comment by vicb** [comment]
Ok got it for the screenshot. Thanks for clarification.

To be honest most other customers with talk to use a different approach:
- Whoever write the template adds a meaning when applicable,
- Very few use screenshots.

Which is why I have marked this issue as low priority.

**Comment by spock123** [comment]
@jaska45 maybe I've misunderstood what you're after, but wouldn't this be solved using unique IDs in the translations?

Example:

`<h1 i18n="site header|An introduction header for this sample@@introductionHeader">Hello i18n!</h1>`

Assigning unique custom IDs to translations generate separate translation tokens afaik.

**Comment by jaska45** [comment]
Spock123. It is very hard for developers to figure out unique ids. In addition if you by mistake use the same id twice only first string will be extracted. I have tried to convince about 15 Angular to start using meaning and id but they don't want to do that. I don't blame them. Adding i18n, unique meaning and/or id is causing lots of extra work. 

My main work is not to write Angular application but localization and testing tools for Angular. All Angular app I have written are single dev apps having few templates. In case like that you can do all these meaning id stuff but when you write big apps with large teams markup changes should be minimal. This means to add i18n and a comment when needed.

**Comment by spock123** [comment]
@jaska45  I get what you're saying. We're only 2 developers on my biggest projects and we try to prefix the custom IDs with the module name. At least then you'll have much fewer clashes.
