### ISSUE TITLE
Angular.io front page "GET STARTED" text overflows its element on Chrome Linux

### ISSUE THREAD

**Issue by anttirastas** [angular/angular#24053]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The "GET STARTED" link in the middle of the Angular.io front page is overflowing from its container/element on Arch Linux , Gnome 3, Google Chrome Version 66.0.3359.139 (Official Build) (64-bit).

The "GET" is halfway outside the top border and the "STARTED" is halfway outside the bottom border of the white background button-like element (<a class="button hero-cta" href="guide/quickstart">Get Started</a>). It seems that if the padding property value of this element were e.g. "0 22px" instead of the current "0 24px" the issue would be fixed.

## Expected behavior

Expected behavior would be that the text "GET STARTED" stays within the white box. 

## Minimal reproduction of the problem with instructions

Navigate to angular.io front page using Google Chrome Version 66.0.3359.139 (Official Build) (64-bit), Arch Linux with Linux kernel 4.16.6-1-ARCH and Gnome Desktop Environment version 3.28.2

## What is the motivation / use case for changing the behavior?

It does not give a very professional image of the framework if the front page is shown in a professional context with professional equipment (e.g. Linux-based OS like mentioned above) and there's an extremely visible issue on the front page.

## Environment

<pre><code>
Angular version: X.Y.Z

Not related to the framework itself but the angular.io website.

Browser:
- [X] Chrome (desktop) version 66.0.3359.139 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

Operating system version: Linux 4.16.6-1-ARCH

![angular_get_started_text_off](https://user-images.githubusercontent.com/12835103/40379358-89a766fe-5dfe-11e8-81d1-2d007b4693cd.png)

</code></pre>

**Comment by gkalpak** [comment]
Apparently this only affects some Linux distros (e.g. Gentoo too). #20382 was supposed to fix it, but the author abandonded it. If you would like to submit a PR (following [these suggestions][1]), that would be great!

[1]: https://github.com/angular/angular/pull/20382#discussion_r150874144

**Comment by berdal84** [comment]
Same problem under Firefox Quantum 68.0.1 x64 & Win7 x64
![image](https://user-images.githubusercontent.com/942052/62214326-1d0edd80-b3a5-11e9-86ec-2781c0b90d4f.png)

**Comment by ericmartinezr** [comment]
This should have been fixed by https://github.com/angular/angular/commit/66d6b53fb10bf671599b15d9aadd531a1c9ef0eb

@gkalpak

**Comment by gkalpak** [comment]
@ericmartinezr is right. This should have been fixed by 66d6b53 (PR #31470).
I am going to close this, but if you still see the same problem, @berdal84, (and you are on the latest version), please open a new issue (and mention the version shown in the footer of the page). Thank you!

**Comment by berdal84** [comment]
@gkalpak ok, I'll take a look. But I'm working on a small project only this week ^^
