### ISSUE TITLE
using ng-form-model directive throws exception

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#2406]
After I updated to version `26`, the forms I had no longer work. After I looked through the source code I found some examples of how to use forms now:

```html
<article>
	<h1>Tasks</h1>
	<form [ng-form-model]="todo" (submit)="add($event, desc.value)">
		<input name="desc" type="text" ng-form-control="desc" [value]="desc.value" placeholder="Description" required>
		<button>Add</button>
	</form>
	<ul>
		<li *ng-for="#task of tasks">
			<task [model]="task"></task>
		</li>
	</ul>
</article>
```
```js
@Component({
	selector: 'todos',
	appInjector: [
		Tasks
	]
})

@View({
	templateUrl: 'app/components/todos/todos.html',
	directives: [
		NgFor,
		formDirectives,
		Task
	]
})

export class Todos {
	constructor(@Inject(FormBuilder) builder, @Inject(Tasks) tasks) {
		this._tasks = tasks;
		this.tasks = tasks.entries;
		this.todo = builder.group({
			'desc': ['', Validators.required]
		});
		this.desc = this.todo.controls.desc;
	}
	add(event, value) {
		event.preventDefault();
		if (!value || !value.length) return;
		this._tasks.add(value);
		this.desc.updateValue('');
	}
}
```
But I keep getting an exception:

![screenshot 2015-06-08 16 12 21](https://cloud.githubusercontent.com/assets/1479737/8036606/32093380-0df9-11e5-840b-d4468e85617c.png)

I've tried all combinations I could think of (of directives), but I cannot seem to be able to figure out why I keep getting that exception.
Any pointers on why is that happening?

**Comment by mhevery** [comment]
It seems like your binding `[value]="desc.value"` is throwing an error because `desc` is null.

**Comment by rolandjitsu** [comment]
@mhevery I've tried removing that actually, and it still tells me the same thing. You can also see that I am assigning `this.desc = this.todo.controls.desc;`.

**Comment by rolandjitsu** [comment]
@mhevery it seems I managed to make it work now, I removed the `[value]="desc.value"` as you instructed and I had `ng-form-control="desc"` written as `[ng-form-control]="desc"`.

**Comment by vsavkin** [comment]
You can find examples of using forms here:
https://github.com/angular/angular/commit/4cd29f791fddde8136dec92cc9ae70669f84fdc9
https://github.com/angular/angular/commit/3eff7be9a652e65f4cc464c6ff4f481948f8fca4

**Comment by rolandjitsu** [comment]
@vsavkin thanks. That looks great, especially the template driven form example.

On a side note, how do I setup TS with Angular? I've got a [branch](https://github.com/rolandjitsu/ng2-play/tree/ts) where I'm trying to, but it just doesn't work.

**Comment by rolandjitsu** [comment]
@vsavkin Nevermind the TS setup, I managed to do it :)

**Comment by rolandjitsu** [comment]
@vsavkin when I try to use the template driven form example, I get the following exception:

![screenshot 2015-06-10 12 58 36](https://cloud.githubusercontent.com/assets/1479737/8080874/6db5126e-0f70-11e5-8392-1f57d6869247.png)

Do you know what is that about?
