### ISSUE TITLE
5.2.11  changelog is missing

### ISSUE THREAD

**Issue by astalegale** [angular/angular#24062]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Hi guys,

i've noted changelog  of angular 5.2.11 version is missing. Is it possible to have it?

thanks!

## Minimal reproduction of the problem with instructions

Open changelog.md

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Charius** [comment]
https://github.com/angular/angular/blob/5.2.x/CHANGELOG.md

**Comment by astalegale** [comment]
Thanks!
