### ISSUE TITLE
angular 6 library - error: XYZ is not a constructor

### ISSUE THREAD

**Issue by burner-account** [angular/angular#24064]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Hi!
If i call a constructor of a namespaced class residing in an angular 6 library, i get the following error in production mode. The angular-cli project was built for production mode with aot enabled:
<pre><code>
ERROR Error: Uncaught (in promise): TypeError: IA.Resource is not a constructor
TypeError: IA.Resource is not a constructor
    at new <anonymous> (main.3f05eb227c975433eb3f.js:1)
    at wi (main.3f05eb227c975433eb3f.js:1)
    at vi (main.3f05eb227c975433eb3f.js:1)
    at Qi (main.3f05eb227c975433eb3f.js:1)
    at sr (main.3f05eb227c975433eb3f.js:1)
    at or (main.3f05eb227c975433eb3f.js:1)
    at Qi (main.3f05eb227c975433eb3f.js:1)
    at Hi (main.3f05eb227c975433eb3f.js:1)
    at Object.hr [as createRootView] (main.3f05eb227c975433eb3f.js:1)
    at e.create (main.3f05eb227c975433eb3f.js:1)
    at new <anonymous> (main.3f05eb227c975433eb3f.js:1)
    at wi (main.3f05eb227c975433eb3f.js:1)
    at vi (main.3f05eb227c975433eb3f.js:1)
    at Qi (main.3f05eb227c975433eb3f.js:1)
    at sr (main.3f05eb227c975433eb3f.js:1)
    at or (main.3f05eb227c975433eb3f.js:1)
    at Qi (main.3f05eb227c975433eb3f.js:1)
    at Hi (main.3f05eb227c975433eb3f.js:1)
    at Object.hr [as createRootView] (main.3f05eb227c975433eb3f.js:1)
    at e.create (main.3f05eb227c975433eb3f.js:1)
    at j (polyfills.cf535d2993b5def59ab4.js:1)
    at j (polyfills.cf535d2993b5def59ab4.js:1)
    at polyfills.cf535d2993b5def59ab4.js:1
    at e.invokeTask (polyfills.cf535d2993b5def59ab4.js:1)
    at Object.onInvokeTask (main.3f05eb227c975433eb3f.js:1)
    at e.invokeTask (polyfills.cf535d2993b5def59ab4.js:1)
    at t.runTask (polyfills.cf535d2993b5def59ab4.js:1)
    at d (polyfills.cf535d2993b5def59ab4.js:1)
    at t.invokeTask [as invoke] (polyfills.cf535d2993b5def59ab4.js:1)
    at _ (polyfills.cf535d2993b5def59ab4.js:1)
ot @ main.3f05eb227c975433eb3f.js:1
t.handleError @ main.3f05eb227c975433eb3f.js:1
next @ main.3f05eb227c975433eb3f.js:1
e.object.r @ main.3f05eb227c975433eb3f.js:1
e.__tryOrUnsub @ main.3f05eb227c975433eb3f.js:1
e.next @ main.3f05eb227c975433eb3f.js:1
e._next @ main.3f05eb227c975433eb3f.js:1
e.next @ main.3f05eb227c975433eb3f.js:1
e.next @ main.3f05eb227c975433eb3f.js:1
e.emit @ main.3f05eb227c975433eb3f.js:1
(anonymous) @ main.3f05eb227c975433eb3f.js:1
e.invoke @ polyfills.cf535d2993b5def59ab4.js:1
t.run @ polyfills.cf535d2993b5def59ab4.js:1
t.runOutsideAngular @ main.3f05eb227c975433eb3f.js:1
onHandleError @ main.3f05eb227c975433eb3f.js:1
e.handleError @ polyfills.cf535d2993b5def59ab4.js:1
t.runGuarded @ polyfills.cf535d2993b5def59ab4.js:1
e @ polyfills.cf535d2993b5def59ab4.js:1
n.microtaskDrainDone @ polyfills.cf535d2993b5def59ab4.js:1
d @ polyfills.cf535d2993b5def59ab4.js:1
t.invokeTask @ polyfills.cf535d2993b5def59ab4.js:1
_ @ polyfills.cf535d2993b5def59ab4.js:1
m @ polyfills.cf535d2993b5def59ab4.js:1
</code></pre>

## Expected behavior

I expected no error to occur.

## Minimal reproduction of the problem with instructions

- create a library and remove boilerplate
- add single file to lib, e.g. ./lib/interfaces/file.ts
- add a namespaced interface and class
- update public api
- build&run prod etc
- implement call to constructor of namespaced class outside library

file.ts
<pre><code>
export namespace SomeNamespace {

    export interface ISomething {
        num: number;
    }

    export class Something implements ISomething {
        public num: number;

        deserialize(obj: ISomething): Something {
            this.num = obj.num;
            return this;
        }
    }

}
</code></pre>

outside:
<pre><code>
    // this one triggers the error
    let sth = new SomeNamespace.Something().deserialize({num: 5});
</code></pre>

## What is the motivation / use case for changing the behavior?

This seems very basic. It should work.

## Environment

<pre><code>
Angular CLI: 6.0.3
Node: 9.6.1
OS: linux x64
Angular: 6.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.1
@angular-devkit/build-angular      0.6.1
@angular-devkit/build-ng-packagr   0.6.1
@angular-devkit/build-optimizer    0.6.1
@angular-devkit/core               0.6.1
@angular-devkit/schematics         0.6.3
@angular/cdk                       6.1.0
@angular/material                  6.1.0
@angular/pwa                       0.6.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.1
@schematics/angular                0.6.3
@schematics/update                 0.6.3
ng-packagr                         3.0.0-rc.5
rxjs                               6.2.0
typescript                         2.7.2
webpack                            4.6.0

Browser:
- [ x] Chrome (desktop) version 66.0.3359.181 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: Node: 9.6.1
- Platform:  linux x64

Others:

</code></pre>

**Comment by IgorMinar** [comment]
Please don't use typescript namespaces. They are not necessary since we are using ES modules and if you do use them, your code will not be optimizable because namespaces are not compatible with tree-shaking and dead code elimination in webpack and uglify.

**Comment by Leanvitale** [comment]
Try for this..
> ng build --prod --optimization=false

**Comment by burner-account** [comment]
Thank you very much for your advice.
Sadly i will not be able to verify the effect of your suggestion (in the near future) as i already have changed all of my repos after reading the comment of IgorMinar. I cannot promise that i will find some free time to setup a non-working example and try to fix it with your approach.

But many thanks for picking up this topic again.
