### ISSUE TITLE
Feature request. Make possible disable check `SafeValue must use [property]=binding`

### ISSUE THREAD

**Issue by Dok11** [angular/angular#24065]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Using SafeValue in `{{ }}` make an error `SafeValue must use [property]=binding`

## Expected behavior
Value in html code what I setted.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-g2qzjw?file=src%2Fapp%2Fapp.component.ts
![image](https://user-images.githubusercontent.com/2697890/40418050-fdd9a5a6-5e89-11e8-81bc-33c886840738.png)

## What is the motivation / use case for changing the behavior?
Using safe html value without extra tags.
Sometimes extra tags broken html layout and css rules.

**Comment by petebacondarwin** [comment]
This is still how it works in Ivy (the original example using Angular v6 and ViewEngine).
The code that is being run is:

```ts
abstract class SafeValueImpl implements SafeValue {
  constructor(public changingThisBreaksApplicationSecurity: string) {}

  abstract getTypeName(): string;

  toString() {
    return `SafeValue must use [property]=binding: ${this.changingThisBreaksApplicationSecurity}` +
        ` (see http://g.co/ng/security#xss)`;
  }
}
```

I would imagine it would be better to throw in ngDevMode??  For example:

```ts
  toString() {
    const message = `SafeValue must use [property]=binding: ${this.changingThisBreaksApplicationSecurity}` +
        ` (see http://g.co/ng/security#xss)`;
    if (ngDevMode) {
      throw new Error(message);
    } else {
      return message;
    }
  }
```
