### ISSUE TITLE
Service worker will not work in sites having Landing page redirect or HTTP Basic Authentication 

### ISSUE THREAD

**Issue by arangates** [angular/angular#24060]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior 
i added service worker and Web App Manifest to the application using `ng add @angular/pwa` .
I ran into some issues which was harder to find due to lack of documentation.

# 1. **Problem caused by landing page redirect.**

As we all know ,working with multiple languages in angular is very complicated.we build separate bundles for each languages and serve in **example.com/en** , **exaple.com/pl** ...etc.
so it makes sense to landing page redirect (i.e user enters **example.com** and the user is redirected to  **example.com/en** automatically) . Service worker will not work in such cases.

# 2. **Problem caused by HTTP Basic Authentication.**

it is not uncommon for any startups to have the flow of testing out stuffs in staging and then merging things to production site.most of the time the new features needs to be hidden. so they use **HTTP Basic Authentication** to prevent their site from being available to public. 

Service worker wont register in such sites and will throw.
```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
SecurityError: Failed to register a ServiceWorker: The script resource is behind a redirect, which is disallowed
```

## Expected behavior

These two things are very common and can be included in documentation . so that people can decide earlier.

## Environment

<pre><code>
Angular version: X.Y.Z

Angular CLI: 6.0.0
Node: 9.6.1
OS: linux x64
Angular: 6.0.0
... cli, common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.0.28
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack     4.6.0

**Comment by gkalpak** [comment]
The first problem is related to angular/angular-cli#8515 (afaict).
The second problem is tracked in #23605.
