### ISSUE TITLE
My angular root folder comes .cmd files after run ng serve command?

### ISSUE THREAD

**Issue by surya5353** [angular/angular#24068]
After run ng serve below happening and error comes in command prompt

click here to show my root folder
https://i.stack.imgur.com/uXexR.png

Click here command prompt error show
https://i.stack.imgur.com/Wymmq.png

I also uninstall global cli and reinstall with latest version, but issue not resolved (Angular 6.0 as well as Angular 5).

my package.json
https://i.stack.imgur.com/16Gul.png

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
