### ISSUE TITLE
Assets don't working

### ISSUE THREAD

**Issue by simbargit** [angular/angular#24078]
When I add the images in the assets folder Angular says "Not found" and I've the same problem after build.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Please open cli's issues in its repo.

**Comment by simbargit** [comment]
I'm sorry, maybe is my mistake but I think this is a bug because I follwe the official instructions and I see other people with the same problem but I use Stackoverflow.

**Comment by gkalpak** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If you still think there is a bug, please file a new issue on the [angular/angular-cli][1] project and ensure you provide all of the required information when filling out the issue template.

[1]: https://github.com/angular/angular-cli
