### ISSUE TITLE
Angular 6 and Bootstrap

### ISSUE THREAD

**Issue by NikolayYeryomenko** [angular/angular#24070]
I developed ASP.NET MVC 5 single page application using Angular 5 and Bootstrap. 
Recently I updated app to use Angular 6. Now html layout does not have spaces between Bootstrap controls.

For example this html:

`<form class="form-inline">`
`  <div class="form-group">`
`    <label for="exampleInputName2">Name</label>`
`    <input type="text" class="form-control" id="exampleInputName2" placeholder="Jane Doe">`
`  </div>`
`  <div class="form-group">`
`    <label for="exampleInputEmail2">Email</label>`
`    <input type="email" class="form-control" id="exampleInputEmail2" placeholder="jane.doe@example.com">`
`  </div>`
`  <button type="submit" class="btn btn-default">Send invitation</button>`
`</form>`

Firefox dev tools edit html option displays as:

`<form class="form-inline"><div class="form-group"><label for="exampleInputName2">Name</label>` `<input type="text" class="form-control" id="exampleInputName2" placeholder="Jane Doe">`
`</div><div class="form-group"><label for="exampleInputEmail2">Email</label><input type="email" ` `class="form-control" id="exampleInputEmail2" placeholder="jane.doe@example.com">`
`</div><button type="submit" class="btn btn-default">Send invitation</button></form>`.

When I edit html and add whitespace or line break like in the first example then browser displays spaces between controls as has to be.

Is Angular 6 compacts html of component templates? How to make app (that uses Bootstrap) look like expected?

Angular 5 and Bootstrap
![angular 5 screenshot-2018-5-23 create department](https://user-images.githubusercontent.com/5666818/40412074-f5a8a26a-5e7a-11e8-9692-a82806535b5b.png)

Angular 6 and Bootstrap
![angular 6 screenshot-2018-5-23 create department](https://user-images.githubusercontent.com/5666818/40412088-ffddf7b2-5e7a-11e8-81e7-d51e87b41d9e.png)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

https://angular.io/guide/aot-compiler#preservewhitespaces
