### ISSUE TITLE
Revert test change for core_package

### ISSUE THREAD

**Issue by jasonaden** [angular/angular#24076]
Part of landing Ivy platform bootstrap required adjusting a Bazel test for license info. From #23811 in https://github.com/angular/angular/blob/master/packages/bazel/test/ng_package/core_package.spec.ts#L108

**Comment by alexeagle** [comment]
I don't understand - do you still have an issue? I don't see a change to that test which should be reverted.

**Comment by alexeagle** [comment]
Jason said on chat that it's obsolete
