### ISSUE TITLE
Fix some sync bindings that have async dependencies

### ISSUE THREAD

**Issue by vicb** [angular/angular#2408]
This is an error case as described in #1111. 

#2407 make sure that the errors get detected.

Bindings to fix:
- [ ] [`appComponentType`](https://github.com/angular/angular/blob/79f3f3b456c8e73054d9f0c3e62aaa830cff64b6/modules/angular2/src/core/application.ts#L90) depends on async `appComponentRefToken`
- [ ] [`WebDriverExtension`](https://github.com/angular/angular/blob/79f3f3b456c8e73054d9f0c3e62aaa830cff64b6/modules/benchpress/src/web_driver_extension.ts#L22) depends on async `_CHILDREN`
- [ ] [`MultiMetric`](https://github.com/angular/angular/blob/79f3f3b456c8e73054d9f0c3e62aaa830cff64b6/modules/benchpress/src/metric/multi_metric.ts#L14) depends on async `_CHILDREN`

**Comment by mhevery** [comment]
@vicb is this still relevant? I think it is stale. Please reopen if you think otherwise.
