### ISSUE TITLE
providedIn annotation breaking library build with rollup

### ISSUE THREAD

**Issue by mlakmal** [angular/angular#24088]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
rollup breaks with multiple imports for same provider when using Injectable with providedIn.

service1.ts
```
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class Service1 {}
```

service2.ts
```
import { Injectable } from '@angular/core';
import {Service1} from './service1';

@Injectable({
  providedIn: 'root'
})
export class Service2 {
constructor(private _serv1: Service1){}
}
```

with above 2 ts files, when we run ngc it emits below for service2.js

```
import { Inject, Injectable } from '@angular/core';
import { Service1 } from './service1';
import * as i0 from "@angular/core";
import * as i1 from "/Users/xxx/stash/features/xxx-ui/.libs/service1";
export class Service2 {
}
Service2.decorators = [
    { type: Injectable, args: [{
                providedIn: 'root'
            },] },
];
/** @nocollapse */
Service2.ctorParameters = () => [
    { type: Service1, }
];
/** @nocollapse */ Service2.ngInjectableDef = i0.defineInjectable({ factory: function Service2_Factory() { return new Service2(i0.inject(i1.Service1)); }, token: Service2, providedIn: "root" });
function Service2_tsickle_Closure_declarations() {
    /** @type {!Array<{type: !Function, args: (undefined|!Array<?>)}>} */
    Service2.decorators;
    /**
     * @nocollapse
     * @type {function(): !Array<(null|{type: ?, decorators: (undefined|!Array<{type: !Function, args: (undefined|!Array<?>)}>)})>}
     */
    Service2.ctorParameters;
    /** @type {?} */
    Service2.prototype._serv1;
}
```

## Expected behavior
ngc should not include multiple imports as rollup is breaking when trying to find imports for bundling libraries.

## Minimal reproduction of the problem with instructions
create library project with above 2 service files and run ng build against library project. it will throw error like below.
Could not resolve '../../../service1' from .libs/core/.ng_pkg_build/core/stage/esm2015/core.js

## What is the motivation / use case for changing the behavior?
Support bundling shareable libraries.

## Environment

<pre><code>
Angular version: 6.0.3

 
For Tooling issues:
- Node version: 8.9
- Platform:  Mac

**Comment by IgorMinar** [comment]
I'm sorry, but this seems like a rollup bug. Can you please file an issue against the rollup project? thanks
