### ISSUE TITLE
V6 button boxes has no nature margin

### ISSUE THREAD

**Issue by haolong7** [angular/angular#24081]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

buttons at v6 are stick together(margin 0). Check example at https://stackblitz.com/edit/angular-yxhxxu

## Expected behavior

They should have nature space between each other as before. Check example at https://stackblitz.com/edit/angular-forms-v5-m2scak

## Minimal reproduction of the problem with instructions

At stackblitz, add  `<button>123</button>
<button>321</button>
<button>4321</button>` to template.

## What is the motivation / use case for changing the behavior?

This may leads to app side style refactor for component library which has button.

## Environment

<pre><code>
Angular version: ^6.0.0

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by biiiipy** [comment]
That's probably because in angular 6 preserveWhitespaces is set to false by default - https://github.com/angular/angular/pull/22046 - So this is by design

**Comment by ericmartinezr** [comment]
@biiipy is right

https://angular.io/guide/aot-compiler#preservewhitespaces

**Comment by ericmartinezr** [comment]
I have read in other issues that it's not working through the .json config file (can't tell for sure it's a bug or not), you can try this though
```
platformBrowserDynamic().bootstrapModule(AppModule, {preserveWhitespaces:false})
```

**Comment by haolong7** [comment]
Thank you. add
`{preserveWhitespaces: true}` option at main.ts would work.
