### ISSUE TITLE
After ng production build getting miss match objects in componentFactoryResolver

### ISSUE THREAD

**Issue by vikram06** [angular/angular#24089]
I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
`function t(t){this.cran=t,this.componentlist=[],this.model={}}`

## Expected behavior
`function CranchecklisttemplateComponent(cran) {this.cran = cran;this.componentlist = [];this.model = {}; }`

## Minimal reproduction of the problem with instructions
   I am trying to create a dynamically creating a component based on a template in my project.
   More information [Stackoverflow](https://stackoverflow.com/questions/40528592/ng2-dynamically-creating-a-component-based-on-a-template/40662376#40662376 )
   In my code
         `     let factories = Array.from(this.componentFactoryResolver['_factories'].keys()); `

 In development environment `factories `  values are 

      function CranchecklisttemplateComponent(cran) {
        this.cran = cran;
        this.componentlist = [];
        this.model = {};
        }

after build i am getting

   `   function t(t){this.cran=t,this.componentlist=[],this.model={}}`

## Environment

<pre><code>
Angular version: 4.2.4

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.0.0
- Platform: Windows

</code></pre>

**Comment by alexzuza** [comment]
It has nothing to do with angular. If you want your components keep their original full names then don't use compressor/minifier.

Anyway, the link you provided suggests you to define dictionary so you won't relay on component name.

**Comment by vikram06** [comment]
Agreed @alexzuza.This issue is related to the Angular compiler. My suggestion is one thing work in development environment that also except to work in production environment

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
