### ISSUE TITLE
UrlMatcher unable to route on URL query parameters

### ISSUE THREAD

**Issue by mozrat** [angular/angular#24093]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
My requirement is to route to Components based on values in the URL query parameters

```/?id=form``` routes to the FormComponent

```/?id=list``` routes to the ListComponent, etc

I have written Routes with a UrlMatcher to achieve this

```
const routes: Routes = [
  { matcher: (url: UrlSegment[]) => {
      console.log(url);
      return url.length === 1 && url[0].path.indexOf('id=form') > -1 ? ({consumed: url}) : null;
    },
    component: FormComponent },
  { matcher: (url: UrlSegment[]) => {
      console.log(url);
      return url.length === 1 && url[0].path.indexOf('id=list') > -1 ? ({consumed: url}) : null;
    },
    component: ListComponent },
  { path: '**',  component: PageComponent }
];
```

Whilst logging to the console the UrlSegment has not captured the query parameters

<img width="901" alt="screen shot 2018-05-24 at 09 30 07" src="https://user-images.githubusercontent.com/2851393/40473860-4af0e06a-5f35-11e8-973f-04f83ea1770f.png">

And therefore I cannot route based on the URL query parameters

## Expected behavior

I expected the ```parameters``` object in the UrlSegment to contain my URL query parameters

## Minimal reproduction of the problem with instructions

I have tried to reproduce here: https://stackblitz.com/edit/angular-qsxuye

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1  
- Platform:  Docker on Mac 

Others:

</code></pre>

**Comment by jasonaden** [comment]
The problem here is `UrlMatcher` gets the `UrlSegment`. The `params` property here is the matrix params, not the query params.

Optional params for a given route should be read from matrix params. However, you can't have a URL with an empty path and use matrix params, so you can't just make the URL something like `/;id=form`.

I would suggest doing a redirect on your root path. Perhaps have a guard that would handle such cases and execute a `navigateByUrl` to the correct URL (`/form` or `/list`) in the appropriate situations.

**Comment by mcalmus** [comment]
I know this has been closed for a year, but it seems like "we didn't plan for a scenario like this" isn't a valid reason to close an issue.
