### ISSUE TITLE
Using [style.transform] with scale is considered unsafe

### ISSUE THREAD

**Issue by Dok11** [angular/angular#24097]
## I'm submitting a...
<pre><code>
[x] Bug report  
</code></pre>

## Current behavior
`<h1 [style.transform]="'translate(' + transform  + 'px, 0px) scale(1)'">Text 2</h1>`
replace to  
`<h1>Text 2</h1>`  
and throwed error to console  
`WARNING: sanitizing unsafe style value translate(20px, 0px) scale(1) (see http://g.co/ng/security#xss).`

## Expected behavior
`<h1 style="transform: 'translate(10px, 0px) scale(1)">Text 2</h1>`

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-style-transform-bug?file=src/app/app.component.ts
![image](https://user-images.githubusercontent.com/2697890/40481793-27677fde-5f5b-11e8-8e93-3d93b473a9bc.png)

## Environment
Angular 5.2.0 (in my project) and 6.0.0 (in stackblitz).

P.S. Maybe this bug is duplicate of https://github.com/angular/angular/issues/21723

**Comment by ericmartinezr** [comment]
It is indeed a dup https://github.com/angular/angular/issues/21723#issuecomment-360141852

**Comment by IgorMinar** [comment]
this should indeed work. I suspect there is a bug in the regexp whitelist matching of https://github.com/angular/angular/blob/13cb75da8b02ed7aa60508dbb5ecd9065809fd12/packages/core/src/sanitization/style_sanitizer.ts#L28

**Comment by mhevery** [comment]
This works as intended. The reason why this is considered unsafe is that one could for example leave a comment in the blog, which would have a div with click handler. One could than use the transform to move the div over a button such as like. A visitor coming to a sit would try to like a post, but would instead be redirected to a malicious website. So any styles which can translate position are considered unsafe.

**Comment by Dok11** [comment]
@mhevery and how I can set such style? Usage native `domElement.style.transform = ''`?
This restriction must be configurable at least because in current behaviuor this bind hands for creation animations and some effects.

**Comment by Dok11** [comment]
@mhevery and this does not explain whats wrong with svg example https://github.com/angular/angular/issues/24097#issuecomment-393176546

**Comment by Dok11** [comment]
@mhevery 
`WARNING: sanitizing unsafe style value linear-gradient(to right, rgba(192, 199, 81, 1) 25%, rgba(255,255,255,0))`

Why? What exactly here is unsafe?

**Comment by mhevery** [comment]
- See https://angular.io/api/platform-browser/DomSanitizer#bypassSecurityTrustStyle for how to take an unsafe string and set style on it.
- The reason this is unsafe is that `<h1 [style.transform]="'translate(' + transform + 'px, 0px) scale(1)'">Text 2</h1>` concatenates strings and `transform` could come from the user input, hence it is not trusted.
- The sanitizer is not smart enough to decide if a particular style is safe or unsafe. Doing so would be very expensive both computational as well as complexity wise. As you would have to answer if the transform move a potentially dangerous div over existing button which would trick the user. For this reason we simply say that any string concatenation which ends up in style is potentially unsafe.

**Comment by schippie** [comment]
@mhevery While i fully understand the reasoning why it's unsafe doing it the proper way but marking it as safe:

```typescript
@HostBinding("style.transform") get hostElementTransform(): SafeStyle {
	return this.sanitizer.bypassSecurityTrustStyle(`translateX("${this.offset.toString(10)}px")`);
}
```

Also doesn't work https://stackblitz.com/edit/style-hostbinding-demo (when running 5.2.8)
