### ISSUE TITLE
Form validators don't take the locale into account

### ISSUE THREAD

**Issue by GoGoris** [angular/angular#24099]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other...
</code></pre>

## Current behavior

Number validators like Validators.min() and Validators.max() don't work with other decimal separators than '.' .

## Expected behavior

The validator takes the decimal separator from a locale that can be set as a provider in the app module.

## Steps to reproduce
The validator should fail in the example below but ignores everything after the comma.
The example works as intended if the comma is replaced with a dot.
https://stackblitz.com/edit/angular-minmax-validators-locale

## What is the motivation / use case for changing the behavior?

These validators are not usefull in the currect state for countries/languages that use a different decimal separator. The validator is the right place for this logic because it gets the values straight from the form. 

## Environment

Angular version: 6.0.1

**Comment by IgorMinar** [comment]
Can you please create a reproduction?

I just want to make sure that you are not expecting the constraints to be specified in the locale specific format, the localization should be supported for the input, but not for the constraint, which should be in a locale-agnostic format.

**Comment by GoGoris** [comment]
Hi IgorMina, yes I am talking about the input.

The min and max validators use parseFloat() to convert the control value to a number, which does not support localization.

```typescript
  /**
   * Validator that requires controls to have a value greater than a number.
   *`min()` exists only as a function, not as a directive. For example,
   * `control = new FormControl('', Validators.min(3));`.
   */
  static min(min: number): ValidatorFn {
    return (control: AbstractControl): ValidationErrors | null => {
      if (isEmptyInputValue(control.value) || isEmptyInputValue(min)) {
        return null;  // don't validate empty values to allow optional controls
      }
      const value = parseFloat(control.value);
      // Controls with NaN values after parsing should be treated as not having a
      // minimum, per the HTML forms spec: https://www.w3.org/TR/html5/forms.html#attr-input-min
      return !isNaN(value) && value < min ? {'min': {'min': min, 'actual': control.value}} : null;
    };
  }
```

I will add an example to the issue

**Comment by danielelidio** [comment]
Hey, quick question @GoGoris @IgorMinar . There is already a solution proposal for this one?
I've implemented a simple solution which seems to be working locally, if you guys are interested I can finish testing the missing cases, documenting the code and submit a pull request.

**Comment by chrisbertrandsagecom** [comment]
Was this ever acheived? @danielelidio what was your simple solution for this?

**Comment by rajibhasan11** [comment]
It seems angular FormControl itself should take 'locale' into account.

**Comment by GoGoris** [comment]
Personally I created my own validator where I first convert the string to the right format by replacing all comma's with points. I couldn't find a better way. You could try to find the decimal separator based on the locale but this seems very hacky: https://stackoverflow.com/questions/1074660/with-a-browser-how-do-i-know-which-decimal-separator-does-the-operating-system

**Comment by trotyl** [comment]
Could you provide a minimal reproduction of how could it work in native browser?
From [HTML spec](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#valid-floating-point-number) this is not a locale-defined feature and anything other than `.` is invalid.

**Comment by GoGoris** [comment]
When using input type="number", the browser shows "1,0" but the form value will be float 1.0, this is correct. Unfortunately there are many bugs and inconsistencies with various browsers and input type="number" and other decimal separators, so most applications use input type="text". This works fine if the the number can be parsed with parseFloat() but will fail if the format is different.

Actually @rajibhasan11 is correct. The ideal solution would be that Angular Forms parses the string to a floating point number using the right locale. So the input is of type text and the form value is float. But I do not know how this would work because currently there is no way to specify that a formcontrol is numeric. 

That's why I suggested that the form value stays the same but that the number validators parse the string to a float using the locale. Now they just call parseFloat() which is very confusing and prone to error because it works with a string but the locale is completely ignored.

**Comment by GoGoris** [comment]
Example: http://jsfiddle.net/qwdtkpg5/

Firefox 68b01
![afbeelding](https://user-images.githubusercontent.com/2930063/59602977-73330480-9108-11e9-868b-9faeaea1f331.png)

Chrome 75
![afbeelding](https://user-images.githubusercontent.com/2930063/59602996-83e37a80-9108-11e9-964b-514f7287f640.png)

Edge 41 (EdgeHTML 16)
![afbeelding](https://user-images.githubusercontent.com/2930063/59603003-8a71f200-9108-11e9-966f-14eae73d74f8.png)

**Comment by trotyl** [comment]
> Unfortunately there are many bugs and inconsistencies with various browsers and input type="number" and other decimal separators, so most applications use input type="text".

The validation is applied to model value, not the view value, you can always keep the model value being the real value to use. In this case you should have your own ControlValueAccessor mapping them, rather than have a magical model value.

> Actually `@rajibhasan11` is correct. The ideal solution would be that Angular Forms parses the string to a floating point number using the right locale.

It's not about forms, locale-specific parsing never exist at all. Not even in Angular, and any library/API such as Moment.js or Intl. Locale is only meant for formatting, not parsing, that's the universal rule of programming. Any attempt to implement a general locale-specific parsing will make you understand why this isn't feasible.

**Comment by GoGoris** [comment]
Thank you for the explanation, it makes sense so I will close this issue. I didn't think of using a ControlValueAccessor but it sounds like a solution.

**Comment by GoGoris** [comment]
Thank you for the explanation, it makes sense so I will close this issue. I didn't think of using a ControlValueAccessor but it sounds like a solution.
