### ISSUE TITLE
'Cannot read property 'prototype' of undefined' after upgrade to Angular 6 from 5 Ask Question

### ISSUE THREAD

**Issue by Pilukina** [angular/angular#24100]
## I'm submitting a...

<pre><code>
[X ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

After update to @angular/cli:6.0.3 and @angular:6.0.3

My app is not rendered on browser (Chrome v  66.0.3359.181 and Firefox 60.0) due:

Uncaught TypeError: Cannot read property 'prototype' of undefined
    at inherits (inherits_browser.js:5)
    at Object../node_modules/hash-base/index.js (index.js:23)
    at __webpack_require__ (bootstrap:76)

## Expected behavior

The application rendered on browsers. 

## Minimal reproduction of the problem with instructions

ng serve the app and browse on Chrome

## What is the motivation / use case for changing the behavior?

Update to latest releases

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [X ] Chrome (desktop) version 66
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X ] Firefox version 60
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
Angular CLI: 6.0.3
Node: 8.11.2
OS: win32 x64
Angular: 6.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cdk                      6.1.0
@angular/material                 6.1.0
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.2.0
typescript         
              
- Platform:  

Others:

</code></pre>

**Comment by krazygit** [comment]
I got the same error after upgrade and I am investigating

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by Pilukina** [comment]
@krazygit In my case the problem is related with:
core.js:1598 ERROR TypeError: this._subscribe is not a function
    at PromiseObservable.Observable.subscribe (Observable.js:161)
    at eval (subscribeTo.js:21)

In order to compile: angular 6.0.3 version I needed to upgrade rxjs (to v6.0) and install rxjs-compat (to 6.2.0). 
The error rise on this part of the code:

this.http.get(wsdlSchema)
              .flatMap(responseXML => new PromiseObservable(xml2js(responseXML.text())))
              .subscribe
                response => {
Still I have no idea about the solution, maybe the info could help you.
