### ISSUE TITLE
Update the lazy loading information to CLI and v6

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#24109]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Current documentation shows non-relative paths being used for `loadChildren`
```
  {
    path: 'customers',
    loadChildren: 'app/customers/customers.module#CustomersModule'
  },
```

While this can work, it depends on the tsconfig `baseUrl` configuration. 

In Angular CLI 1.x we had a baseUrl of `src/`, which made sense for single apps. Angular CLI 6.x adds multi project and library support, and as part of that we changed the `baseUrl` to be `./`.

This was done because having a `baseUrl` pointing to a specific project affects path resolution in all projects. Having multiple `baseUrl` is also problematic because your app interprets paths in tsconfig in one way, and your lib in another way. And your editor in yet another way because `tsconfig.app.json` is not recognized by the editor.

For a non-relative path to a lazy route to work, now it would have to include `src/`: `loadChildren: 'src/app/orders/orders.module#OrdersModule'`.

To avoid confusion on the CLI we always used relative paths, since we didn't know what baseUrl users had in their configs.

## Expected behavior
I suggest examples use relative paths, thus not depending on any `baseUrl` configuration on user projects:
```
  {
    path: 'customers',
    loadChildren: './customers/customers.module#CustomersModule'
  },
```

It would also be beneficial to add a note about how using non-relative paths works but they are based off `baseUrl`.

## What is the motivation / use case for changing the behavior?
Show instructions for lazy modules that work in a newly generated CLI 6.x project.

Related to https://github.com/angular/angular-cli/issues/10673#issuecomment-391801112

cc @brandonroberts

**Comment by jenniferfell** [comment]
filename=https://angular.io/guide/lazy-loading-ngmodules

@brandonroberts : If I understand, there are two issues here: 
1. Update lazy loading doc to talk about absolute v relative paths
2. Update all doc examples to use relative paths

The style guide seems correct: Style 05-04

Is that correct?

**Comment by brandonroberts** [comment]
Yes, that's correct

**Comment by montella1507** [comment]
@filipesilva  i think angular 6 has again problems with lazy loaded modules if there are 2+ unlisting  in path..
if path in loadChildren contains 2+ times "../" it is error in first build (how ever it works in rebuild on watch)

//PROJECT STRUCTURE:   portal/routing/portal.routing.ts,   help/help.module.ts - you have to go 2 directories "up" to reach help.module.ts

     loadChildren: '../../help/help.module#HelpModule'
 = DOESNT WORK

//PROJECT STRUCTURE:   x/x.routing.ts,  help/help.module.ts -  you have to go only one directory "up" to reach help.module.ts
     loadChildren: '../help/help.module#HelpModule'
 = DOES WORK


I am pretty sure you have solved this issue year ago and it is back.

**Comment by filipesilva** [comment]
@montella1507 can you make a simple repro and open an issue with it in https://github.com/angular/angular-cli please? Then we can investigate it.

**Comment by montella1507** [comment]
@filipesilva  https://github.com/angular/angular-cli/issues/12236 

i have tried to simulate it on stackblitz, without success, but i have added zip file and explained the problem as much as possible. Thank you.

**Comment by filipesilva** [comment]
Thanks for the repro @montella1507, it really helps a lot. I triaged it and we should get to it as time allows.

**Comment by montella1507** [comment]
@filipesilva thank you for your time i think you have already faced this issue in the past. Maybe it is only lack in documentation and relative path is between module importing routes and another module and not "routing file". I am pretty sure you will figure it out. Thank you again.

**Comment by brandonroberts** [comment]
Fixed via https://github.com/angular/angular/pull/20023
