### ISSUE TITLE
i18n CDATA in xlf is rendered as plaintext

### ISSUE THREAD

**Issue by philippschladitz** [angular/angular#24101]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
After upgrading my application from Angular 5.2 to Angular 6 all translations, where CDATA is used, are incorrectly rendered. 
As an example, a translation like this will result in plaintext:
```
<trans-unit id="example" datatype="html">
    <source>example</source>
    <target>Example with <![CDATA[<a [href]="/example" target="_blank">Example Link</a>]]></target>
</trans-unit>
```

## Expected behavior
The example above should get rendered as text with a real HTML5 link.

## Environment
Angular version: 6.0.3

**Comment by vicb** [comment]
> The example above should get rendered as text with a real HTML5 link.

Why do you think so ?
It would allow injecting arbitrary html in your app which we probably do not want (And for sure this will not be possible with the next gen ivy architecture)

**Comment by philippschladitz** [comment]
This can be closed. As you correctly stated CDATA is not the correct feature to use. We use x-Tags now, for future reference, see section 2.4 in http://docs.oasis-open.org/xliff/v1.2/cs02/xliff-core.html

**Comment by MickL** [comment]
@philippschladitz How is this working? When i try to insert a <br> into the target i get:

`ERROR in Unknown placeholder "x1" ("Bitte nutzen Sie zur Identifikation den bereitgestellten Link.[ERROR ->]<x id="x1" ctype="x-html-br" equiv-text=" "/>`

I used exactly the code from the XLIFF specification:
`<x id="x1" ctype="x-html-br" equiv-text=" "/>`

**Comment by philippschladitz** [comment]
@MickL The specification is a bit confusing in this context. Can you show me a full-length example of what you tried?

**Comment by philippschladitz** [comment]
Here is an example of what I use: 
`<trans-unit id="exampleID" datatype="html">
        <source>
          <x id="START_BOLD_TEXT" ctype="x-b"/>
          <x id="CLOSE_BOLD_TEXT" ctype="x-b"/>
        </source>
        <target>
          This is a simple text with a <x id="START_BOLD_TEXT" ctype="x-b"/>bold style inbetween<x id="CLOSE_BOLD_TEXT" ctype="x-b"/>.
        </target>
      </trans-unit>`

**Comment by MickL** [comment]
Same as you, trying to add html (a, br) into translation:

```
<trans-unit id="example" datatype="html">
    <source>example</source>
    <target>Example with <![CDATA[<a [href]="/example" target="_blank">Example Link</a>]]></target>
</trans-unit>
```

**Comment by MickL** [comment]
So you add the tags before? How if messages are generated automatically and i dont want that link in source language...

**Comment by philippschladitz** [comment]
You don't need to add the link in the source language. The source language only provides the available x-Tags.

**Comment by philippschladitz** [comment]
@MickL 
Here is an example with a link instead of bold text. The address is added inside of the angular html or ts file.

Translation:
`<trans-unit id="exampleID" datatype="html">
        <source>
          <x id="START_LINK" ctype="x-a"/>
          <x id="CLOSE_LINK" ctype="x-a"/>
        </source>
        <target>
          This is a <x id="START_LINK" ctype="x-a"/>link<x id="CLOSE_LINK" ctype="x-a"/>.
        </target>
      </trans-unit>`

Component.html:
<p i18n="@@exampleID"><a href="/example"></a></p>

**Comment by MickL** [comment]
But in source (componet.html) i don't want the link :/

**Comment by philippschladitz** [comment]
You can provide the link as a data-binding.

**Comment by spock123** [comment]
@philippschladitz 2019 here - you just saved my say with that example - thanks :)
