### ISSUE TITLE
Cannot find module '@angular/cli/plugins/webpack'

### ISSUE THREAD

**Issue by RockGuitarist1** [angular/angular#24104]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

### Versions
```
Angular CLI: 6.0.3
Node: 8.9.4
OS: win32 x64
Angular: 6.0.3

@angular-devkit/architect    0.6.3
@angular-devkit/core         0.6.3
@angular-devkit/schematics   0.6.3
@schematics/angular          0.6.3
@schematics/update           0.6.3
rxjs                         6.2.0
typescript                   2.7.2
webpack                      3.10.0
```

I have an Electron app using Angular 6 (just upgraded) and upon trying to run the app, I got this error: 'Cannot find module '@angular/cli/plugins/webpack''. I looked in the node_modules folder and found where the webpack file used to exist, but now it is gone. What is the solution to this?

NOTE: The angular app was ejected, hence why I am using Webpack.

I still need reference to these 2 imports in webpack: NamedLazyChunksWebpackPlugin,
  BaseHrefWebpackPlugin

UPDATE: Also ngtools/webpack is missing too. I see there is a npm library for it, but not sure if it will work since webpack has been removed from the cli folder.

**Comment by IgorMinar** [comment]
The packages are still there but they might have been moved to a different location under node_modules because of npm's hoisting. If your electron app depends directly on these packages, then you will need to specify the dependency on them in your package.json and not rely on the packages being installed as transitive dependencies of the @angular/cli.
