### ISSUE TITLE
Builder TemplateDefinitionBuilder doesn't support animations yet

### ISSUE THREAD

**Issue by guysenpai** [angular/angular#24112]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have this error when I serve my angular app: 

```
Error: Builder TemplateDefinitionBuilder doesn't support animations yet
    at TemplateDefinitionBuilder.unsupported
```

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.11.1  
- Platform:  Mac

Others:

</code></pre>

**Comment by IgorMinar** [comment]
Ivy is not feature complete yet. Please don't open issues for it until we have a version that we encourage people to use, otherwise you are just increasing noise on the issue tracker that could result in important issues being missed. Thank you for understanding.

**Comment by bostondevin** [comment]
Can I somehow get rid of the error? I commented out all instances of animation / browser animation and still getting it
