### ISSUE TITLE
Angular.io service worker documentation - wrong outputPath

### ISSUE THREAD

**Issue by jakehockey10** [angular/angular#24115]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The documentation for Service Workers [here](https://angular.io/guide/service-worker-getting-started) suggests to use the `http-server` node package to run a production build of an angular application that just received a new service worker.  The documentation suggests changing directories to `dist/`, but in the latest version of Angular 6, `angular.json` configures the `projects.<app-name>.architect.build.outputPath` to put the result of `ng build --prod` into `dist/<app-name>`.

## Expected behavior

The documentation needs an update as long as the defaults for `angular.json` differs from the assumptions in this documentation page.  Otherwise, maybe a note about this in the documentation page would suffice: "change your directory to the value that appears in `projects.<app-name>.architect.build.outputPath` of `angular.json`."

## Minimal reproduction of the problem with instructions

Follow the steps outlined in the documentation.
## What is the motivation / use case for changing the behavior?

To save people's time that are trying to learn angular and service workers specifically.

## Environment

<pre><code>
$ ng -v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.0.1
Node: 8.11.1
OS: win32 x64
Angular: 6.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.1
@angular-devkit/build-angular     0.6.1
@angular-devkit/build-optimizer   0.6.1
@angular-devkit/core              0.6.1
@angular-devkit/schematics        0.6.1
@angular/cli                      6.0.1
@angular/pwa                      0.6.3
@ngtools/webpack                  6.0.1
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

</code></pre>

**Comment by gkalpak** [comment]
Sounds reasonable. If you feel like taking a stub at fixing this, you need to update [this file][1] :wink:

[1]: https://github.com/angular/angular/blob/master/aio/content/guide/service-worker-getting-started.md

**Comment by gkalpak** [comment]
Fixed in #24439.
