### ISSUE TITLE
Tutorial --> 8. HTTP not working. error 'api/heroes' not found status 404

### ISSUE THREAD

**Issue by soumenbarua** [angular/angular#24110]
Tutorial --> 8. HTTP not working. error 'api/heroes' not found status 404

**Comment by jenniferfell** [comment]
filename=https://angular.io/tutorial/toh-pt6

**Comment by jenniferfell** [comment]
@soumenbarua : Thank you for submitting this. We recently checked the tutorial with v6, and we didn't encounter this problem. It's possible, however, that we overlooked something or weren't clear enough in the instructions. 

Were you successful with these steps: https://angular.io/tutorial/toh-pt6#simulate-a-data-server

Can you be more specific about the step that resulted in the 404 error? 

Thanks for any additional info.

**Comment by soumenbarua** [comment]
Hi Jennifer,
I was able to run it with 'api/heroes' but the same code does not work with an external api, for example, 'http://localhost:port/api'. Is there any tutorial or example to consume an external api?
Thanks,
Soumen

**Comment by chembu** [comment]
We don't have an example that shows how to consume an external api. Hope you updated the base URL parameter in your code to point to the external api.

**Comment by shwetaahuja123** [comment]
Hi soumenbarua,

I am facing same issue that you have mentioned initially here. Can you guide me about the fix.

Thanks,
shweta

**Comment by israelpg** [comment]
> Resolved.

Resolved, however you did not mention how you solved the issue, which is pointless.
