### ISSUE TITLE
How can i pass router from parent to child with input binding?

### ISSUE THREAD

**Issue by YuJieLian** [angular/angular#24117]
## Current behavior

I define a template inside the sub component, which adds several routes, rendering it to the parent component, and the routing inside the template does not work.

## Expected behavior

By calling the subcomponents through the selector, it is hoped that the routes defined in the sub component template can work normally.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
