### ISSUE TITLE
Angular CLI generates library with a file path reference in tsconfig.json different from where the build system outputs it to

### ISSUE THREAD

**Issue by bh3605** [angular/angular#24129]
## I'm submitting a...
<pre><code>
[ x ] Bug report 
</code></pre>

## Current behavior

After building a library using the Angular CLI, app cannot find a reference to library when importing in app.module.ts

## Expected behavior
It finds a proper reference to MyTestLibrary.

## Minimal reproduction of the problem with instructions
Create a library containing capital letters like MyTestLibrary with the command
<code>ng g library MyTestLibrary</code>
tsconfig.json file now contains reference to library MyTestLibrary
<code>
"paths": {
      "MyTestLibrary": [
        "dist/MyTestLibrary"
      ]
    }
</code>

Build MyTestLibrary with command <code>ng build MyTestLibrary</code>
Import library in app.module.ts with <code>import { MyTestLibraryComponent } from 'MyTestLibrary';</code>
*see error: can not find module MyTestLibrary*
Look at the folder containing the build output and notice it built the library under dist/my-test-library which differs from the file path in tsconfig.json
## What is the motivation / use case for changing the behavior?
The Angular CLI is not providing a proper reference to where the build system outputs the library without having to manually edit the generated filepath in tsconfig.json

When generating a library it should either 
A. Specify the filepath that the build system would output the AOT compiled library to
B. Fix the build system to it takes into account capital letters and doesn't insert hyphens and lower cases everything.

I suggest A, since your build system has been around a lot longer than ng generate library command has.

You could also look at it the other way, I notice when I build my app it outputs it into a folder that matches the name of my app, but when I build the library, it uses the library's hyphenated form.

## Environment
Any

<pre><code>
Angular version: 6.0.0

**Comment by bh3605** [comment]
I found the dest path of the library is where it's using the hyphenated form when the build system builds and outputs. You can find the destination path under ng-package.json. This is probably the culprit

**Comment by ericmartinezr** [comment]
Please report angular-cli issues in its repohttps://github.com/angular/angular-cli :+1:

**Comment by bh3605** [comment]
Oh, well that explains the downvotes.
