### ISSUE TITLE
Upgrade to Angular 6 from angular 5, PromiseObservable.subscribe error

### ISSUE THREAD

**Issue by Pilukina** [angular/angular#24128]
## I'm submitting a...

<pre><code>
[ X] Regression (a behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

After loading, my web app send a http request, once received my app uses PromiseObservable to get the result of an xml2js parsing:

this.http.get(url)
              .flatMap(responseXML => new PromiseObservable(xml2js(responseXML.text())))
              .subscribe
                response => {

When the response of the http request arrives then the browser throws the follow error:
` TypeError: this._subscribe is not a function
    at PromiseObservable.Observable.subscribe (Observable.js:161)
    at eval (subscribeTo.js:21)
    at subscribeToResult (subscribeToResult.js:6)
    at MergeMapSubscriber._innerSub (mergeMap.js:127)
    at MergeMapSubscriber._tryNext (mergeMap.js:124)
    at MergeMapSubscriber._next (mergeMap.js:107)
    at MergeMapSubscriber.Subscriber.next (Subscriber.js:93)
    at XMLHttpRequest.onLoad (http.js:1336)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4053)`

## Expected behavior
The application methods should be able to subscribe to a PromiseObservable

## Minimal reproduction of the problem with instructions
*STEPS TO REPRODUCE*
1.- create a new project with the follow libraries:
```
Angular CLI: 1.7.4
Node: 8.11.2
OS: win32 x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 6.1.0
@angular/cli: 1.7.4
@angular/material: 6.1.0
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.7.2
webpack: 3.11.0
```
2.- Create a service with a method that loads an url (for example a simple SOAP WSDL) and after that uses PromiseObservable and xml2js to parse the xml code into JSO.
import { Injectable } from '@angular/core';
import { Http } from '@angular/http';

import * as xml2js  from 'xml2js-es6-promise';

import 'rxjs/add/operator/mergeMap';
import { PromiseObservable } from 'rxjs/observable/PromiseObservable';
import { Observable } from 'rxjs/Observable';
import { BehaviorSubject }  from 'rxjs/BehaviorSubject';
import { Subject }    from 'rxjs/Subject';
import 'rxjs/add/observable/of';

     this.http.get(wsdlSchema)
              .flatMap(responseXML => new PromiseObservable(xml2js(responseXML.text())))
              .subscribe(
                response => {
-->

## What is the motivation / use case for changing the behavior?

Upgrade from angular v5.2.0 to angular v6.0.2

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x ] Chrome (desktop) version 66
- [x ] Firefox version 60
 
For Tooling issues:
- Node version: 8.11.2 
- Platform: Windows

Others:
IDE: Visual Studio Code
</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by sandangel** [comment]
Hi @Pilukina, angular 6 now using rxjs 6 which has some breaking changes. I suggest you should read this (migration guide)[https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md]. in short, you now can only import from 'rxjs' and 'rxjs/operators'. you need to change the above code to:

```typescript
import { Injectable } from '@angular/core';
// import { Http } from '@angular/http';
// use new HttpClient API
import { HttpClient } from '@angular/common/http';

import * as xml2js from 'xml2js-es6-promise';

// import 'rxjs/add/operator/mergeMap';
import { mergeMap } from 'rxjs/operators';
import { of, from, Observable, BehaviorSubject, Subject } from 'rxjs';
// import { PromiseObservable } from 'rxjs/observable/PromiseObservable';
// import { Observable } from 'rxjs/Observable';
// import { BehaviorSubject } from 'rxjs/BehaviorSubject';
// import { Subject } from 'rxjs/Subject';
// import 'rxjs/add/observable/of';

 this.httpClient.get(wsdlSchema).pipe(
          mergeMap(responseXML => from(xml2js(responseXML.text())))
          .subscribe(
            response => {
```

There is a 'rxjs-tslint' package which could help you automatically update your import from rxjs. I think you should read about that in the migration docs above.

For the place to ask more questions, I think you should use angular gitter channel [here](https://gitter.im/angular/angular), or try contact http://ng-girls.org/, I heard that they provide support for women who work in tech. Hope this could help.

**Comment by destus90** [comment]
@Pilukina you can use rxjs-compat that is a bridge from v5 to v6 https://github.com/ReactiveX/rxjs/tree/master/compat

**Comment by Pilukina** [comment]
@destus90, I forgot to add on the post that I also migrated from:
    "**rxjs": "^5.2.0", -> "rxjs": "^6.0" and "rxjs-compat": "^6.2.0",**
**PromiseObservable seems not to be supported.**

@sandangel,
After install (**npm i -g rxjs-tslint**) and run (**rxjs-5-to-6-migrate -p path-to-tsconfig.tsxjs-5-to-6-migrate -p path-to-tsconfig.ts**) all paths have been updated but still same error on browser.

This page could be also useful to **migrate from Angular 5 to Angular 6: https://update.angular.io/**
Many thanks for the information about ng-girl. It is good to know about them.

@ericmartinezr, I'll create a task with this question on StackOverflow.

Many thanks for your help to you all.

**Comment by Pilukina** [comment]
As @sandangel propertly said (again many thanks) the code must be updated in order to work with rxjs6.
Here is the reason why PromiseObservable fails:

> All observable classes (https://github.com/ReactiveX/rxjs/tree/5.5.8/src/observable) have been removed from v6, in favor of existing or new operators that perform the same operations as the class methods. 

> For example, ArrayObservable.create(myArray) can be replaced by from(myArray), or the new operator fromArray().

In our case:
**new PromiseObservable(xml2js(responseXML.text()) must be replaced by from(xml2js(responseXML.text());**

-> flatMap(...) is replaced by:  
**.pipe(
          mergeMap(...)**

Another example  that I could find on my code is:

**Observable.of() by of()**

For further information, please, check the follow doc:
https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md#import-paths
