### ISSUE TITLE
Not Able to fetch the local data stored in json using the HttpClients using latest angular cli

### ISSUE THREAD

**Issue by vinay277** [angular/angular#24136]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

when trying to access the data stored locally in any folder it is not being fetched

## Expected behavior

should be able to fetch the data successfully using the httpclient method

## What is the motivation / use case for changing the behavior?

Difficulty to fetch any data stored locally

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:
The error shown on the console is Http failure during parsing for https://angular-izzybu.stackblitz.io/src/app/api/employee.json"
</code></pre>

**Comment by ericmartinezr** [comment]
HttpClient uses XmlHttpRequest internally. You can't access your own filesystem with it.

**Comment by vinay277** [comment]
Can you please let me know what alternative can be used to do that.
In angular 2 I used http it worked very well.

**Comment by ericmartinezr** [comment]
Can you ask your question in [gitter's chatroom](https://gitter.im/angular/angular)? A repro (a gist, stackblitz, plnkr, etc) of what used to work would be awesome, because from your description this shouldn't be possible in any version of angular.

**Comment by vinay277** [comment]
U can find the repo in the link "https://github.com/DeborahK/Angular-GettingStarted/tree/master/APM-Final". when i do the same with the angular CLI this seems to throw an error http.get

Will add this question in gitter chat room too

**Comment by mlc-mlapis** [comment]
@vinay277 ... any HTTP calls from a client needs a HTTP server (local or remote). This the principle.

Probably nobody understand what is your main goal. Try to formulate your idea by another words. Do you need to save some data to a local disk of a client? ... then read about `localStorage`, `sessionStorage` or do you need to save something to a local database like `IndexedDB`, `Web SQL`, ...

**Comment by vinay277** [comment]
I have a stored json data in my local machine and usig http.get i want to fetch it as a response which is happening in some cases and which is not happening in some other cases

this is one of the stackoverflow follow up which gives the idea what issue i am facing
https://stackoverflow.com/questions/50577059/not-able-to-access-the-local-json-data-in-angular-5-using-httpclient/50579726#50579726
