### ISSUE TITLE
@angular/elements when removeChild from dom error happen!!

### ISSUE THREAD

**Issue by iwe7** [angular/angular#24145]
## ERROR TypeError: Cannot read property 'nativeNode' of null

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

code like this!
```ts
createToast(cfg: AmToastInterface): Observable<AmToastService> {
    const toast = document.createElement("am-toast");
    for (const key in cfg) {
      toast[key] = cfg[key];
    }
    document.body.appendChild(toast);
    return fromEvent(toast, "hide").pipe(
      switchMap((res: any) => {
        return of(this).pipe(
          tap(res => {
            document.body.removeChild(toast);
          })
        );
      })
    );
  }
```

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

<img width="873" alt="bug" src="https://user-images.githubusercontent.com/37964954/40574654-5bd7c1da-6108-11e8-8e98-0571ef44b817.png">

**Comment by splincode** [comment]
Add repo for example

**Comment by iwe7** [comment]
i have fixed this problem! thanks!

**Comment by geocine** [comment]
@iwe7 can you share how you fixed this issue?

**Comment by kevin192291** [comment]
Please tell us how you fixed it.
