### ISSUE TITLE
Cannot run tests for compiler-cli locally

### ISSUE THREAD

**Issue by alippai** [angular/angular#24149]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
It's not updated to Angular 6 & Angular CDK 6.0.0 (at least there is old reference in the `offline_compiler_test.sh`)

## Expected behavior
This workflow should be updated

## Minimal reproduction of the problem with instructions
Follow the instructions in the `packages/compiler-cli/README.md`

## What is the motivation / use case for changing the behavior?
I'd like to improve the compiler-cli, add tests.

## Environment

<pre><code>
Angular version: master#729c7978904

For Tooling issues:
- Node version: 10.1.0

Others:
Couldn't install npm packages (with yarn) on NodeJS 10.1, had to change the engines: {} check.
</code></pre>

**Comment by alippai** [comment]
After some local patching, managed to get this result:
![image](https://user-images.githubusercontent.com/240729/40578987-7efd6b0e-611e-11e8-9ff7-64ba66ebe679.png)

I'm not sure these errors shouldn't result in test failures instead of _success_

**Comment by mhevery** [comment]
I think that file is out of date. I think you should just have to use the `bazel` to run all of the compiler tests.

**Comment by jelbourn** [comment]
Closing since I believe this is obsolete (the given test does not exist any more)
