### ISSUE TITLE
i18n, ng6, remove the &amp; from the xlf file for &amp;#39; - was not the case in ng 5

### ISSUE THREAD

**Issue by anymos** [angular/angular#24147]
## I'm submitting a...

<pre><code>
[ X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

using a xlf with 

<target state="translated">Qu\&amp;#39;est-ce que ?</target></trans-unit>
the template display : 

Qu#39;est-ce que ? 

## Expected behavior

it should display : 

Qu'est-ce que ? 

which show the quote correctly

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [ x] Chrome (desktop) version XX
- [ x] Chrome (Android) version XX
- [ x] Chrome (iOS) version XX
- [ x] Firefox version XX
- [ x] Safari (desktop) version XX
- [ x] Safari (iOS) version XX
- [ x] IE version XX
- [ x] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by splincode** [comment]
Add repo for example and add about info for repro steps

**Comment by vicb** [comment]
Closing as no repro has been provided
