### ISSUE TITLE
In the form, use the form components, but the parent form validation for the wrong forever?

### ISSUE THREAD

**Issue by lijiadashaoye** [angular/angular#24146]
This is a form components，Please have a look at“one-child3.component.html”
I found that no matter what is the verification results of the subform, parent form validation for the wrong forever, what's the real-time modification parent forms authentication method?

[child3.zip](https://github.com/angular/angular/files/2041465/child3.zip)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem)
