### ISSUE TITLE
Dependency Injection from inherited classes not working properly

### ISSUE THREAD

**Issue by thekhoi** [angular/angular#2414]
I am having a couple of issues w/ DI.  Firstly, the I'm unable to DI the NgZone when using the appInjector syntax. The work around was to use the constructor parameter syntax.

```sh
Error during instantiation of Token(ComponentRef)!. ORIGINAL ERROR: Cannot resolve all parameters for NgZone. Make sure they all have valid type or annotations.
```

The second issue I've observed is that the NgZone is getting injected twice, 1st and 3rd parameters, in the below example. 

```sh
class BaseComponent {
  constructor(@Inject(NgZone) zone:NgZone) {  }
}

@Component({
	selector:"todo-app",
	appInjector:[Store, TodoFactory]
})
class SubClassComponent extends BaseComponent {
  constructor(todoStore:Store, factory: TodoFactory, @Inject(NgZone) zone:NgZone) {
     console.log(todoStore); // result Object: NgZone
     super(zone);
  }
}
```

I'm currently using version .25

**Comment by mhevery** [comment]
Assuming you are using typescript, there is no need for the `@Inject(NgZone)` annotation. can you remove it.

**Comment by thekhoi** [comment]
I am using typescript.
```sh
tsc  --module amd --emitDecoratorMetadata
```
As you can see i'm injecting the Store and TodoFactory in the above example.  However adding NgZone to the appInjector caused it to error out. (See above)

Looking a the source code for the bootstrap method, it appears that angular is binding to the value instead of a factory for NgZone.  I had a hunch that has something to do w/it but didn't dig any deeper after I found the work around.

Things of note, I'm using Requirejs along side Systemjs. I wrote a require plugin to load the angular modules from SystemJs.

I doubt that is causing the issue.

**Comment by thekhoi** [comment]
@mhevery Just as you said, I removed the @Inject(NgZone) and it is working.  I thought I needed to include it in the appInjector property.
