### ISSUE TITLE
Message for error could be clearer

### ISSUE THREAD

**Issue by parloti** [angular/angular#24148]
https://github.com/angular/angular/blob/6ef9f2278f64697920df8ecaf79293a7eef7e0ab/packages/compiler/src/metadata_resolver.ts#L996

The message for this error could be clearer.
The `debugInfo` and `providerIdx` variables are available in context and would help in finding the error quickly if they were part of the message.

**Comment by splincode** [comment]
Describe the issue according to the rules

**Comment by alexeagle** [comment]
Seems clear enough to me - the error is missing context that is trivial to provide

**Comment by parloti** [comment]
@alexeagle @splincode 
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => 
[x] Other...: The error message does not represent and does
 not help to resolve one of the possibles errors.
</code></pre>

## Current behavior
[In this line...](https://github.com/angular/angular/blob/6ef9f2278f64697920df8ecaf79293a7eef7e0ab/packages/compiler/src/metadata_resolver.ts#L996)

When I have an invalid provider, for typos or renaming for example, the message does not tell either the index of the provider or which module the problem occurs.


## Expected behavior
The message for this error could be clearer.
The `debugInfo` and `providerIdx` variables are available in **context** and would help in finding the error quickly if they were part of the message.


## Minimal reproduction of the problem with instructions
Just import a invalid provider.

[ stackblitz ](https://stackblitz.com/edit/undefined-provider?file=src%2Fapp%2Fapp.module.ts)
Hier `debugInfo` is `"provider for the NgModule 'AppModule'"`
And `providerIdx` is `1`.


## What is the motivation / use case for changing the behavior?
If I knew immediately through the message in console, which module and the index of the array of providers, it would be very easy to identify the problem.


## Environment

<pre><code>
 Angular CLI: 6.0.7
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4
- Platform:  win32 x64

</code></pre>

**Comment by trotyl** [comment]
> When I have an invalid provider, for typos or renaming for example

How could you make TypeScript happy with doing that?

**Comment by parloti** [comment]
> How could you make TypeScript happy with doing that?

It was just a mistake I made, and I just realized after spending some time debugging in the browser.

It was only a problem that I had, and I am sharing a possible solution with the community, in order that other beginners like me suffer less when they made the same mistake that I did.

**Comment by lazarljubenovic** [comment]
I'm also interested how did this get through TypeScript. If it was a typo, TypeScript should have complained that it doesn't know what an identifier is.

**Comment by parloti** [comment]
I did several simulations locally to get the same error again.
I describe below the two that I think are most important.

**1st Situation:**
1. The application works normally.
2. I make a typo.
3. I call "ng serve" and I get the following errors:
_**TS2305**: Module has no exported member (if the typing error is in the import declaration)._
OR
_**TS2304**: Can not find name (if the typing error is in the NgModule Decorator, in this case array of providers)._
AND
**'Failed to compile'.**


**2nd Situation:**
1. The application works normally.
2. I call "ng serve" and I get 'Compiled successfully'.
3. I make a typo, that is, I keep the server running and rename the service in the import declaration AND in the array of providers.
4. "ng" recompiles automatically and I get 'Compiled with warnings'.
4. Other system features that do not depend on this service continue to work normally.

**Comment by opetriienko** [comment]
I also faced a problem when the message wasn't clear when prod build couln't be built. I had to debug `ng build --prod` command to find out what the issue was there. The problem was with a library which worked ok without `--prod` flag. But during the optimization process it merely became broken.
I believe this enhancement could be useful for such cases as well just to save a couple of hours at least.

**Comment by alxhub** [comment]
The error message is indeed quite unhelpful. The good news is that in Ivy in Angular 9+, DI is entirely a runtime concept, and it should be trivial to break on the equivalent error in a debugger and see exactly where the undefined provider is coming from.

**Comment by JoostK** [comment]
The Ivy compiler no longer has a metadata collector that was prone to unsupported syntax issues, so closing as resolved.
