### ISSUE TITLE
feat(http): EventEmitter and Dart support

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2415]
The initial implementation of http (PR #2360) is only tested in JS, and is limited to JavaScript because it's using RxJS directly. The library should be changed to use the EventEmitter abstraction, which uses RxJS for  JavaScript, and streams for dart. This will require extending `EventEmitter` to support creation of cold observable, and to support the map operator.

**Comment by gdi2290** [comment]
it sounds like we need an `EventEmitterWrapper`

**Comment by jeffbcross** [comment]
@gdi2290 our thinking is that we'll use the `ObservableWrapper` for creation and combinators (in addition to subscription, which it already does).
