### ISSUE TITLE
Drop the "Coding conventions" section from the style guide

### ISSUE THREAD

**Issue by mgechev** [angular/angular#24153]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The style guide provides TypeScript coding conventions.

## Expected behavior

Do not couple the document with TypeScript syntax conventions.

## What is the motivation/use case for changing the behavior?

Following a coding style guide improves the consistency and the communication in our projects. Nevertheless, this section is not coherent with the purpose of the style guide because of the following reasons:

* The style guide aims to provide a generic set of practices which apply to different organizations. Coding practices are often organization-wide.
* Although there are exceptions, the rest of the style guide focuses on semantics rather than syntax. 
* The "Coding conventions" section contradicts the original purpose of the style guide - to keep it Angular-specific by providing a generic set of best practices which will assist developers to ship successful projects 🚢.
* Some conventions are controversial with the semantics of Angular concepts (naming member variables without `_` prefix and intercepting inputs could be viewed as an inconsistency).

// cc @wardbell @bradlygreen @johnpapa @IgorMinar

**Comment by jenniferfell** [comment]
docsarea=styleguide

**Comment by fmalcher** [comment]
Sorry for coming up with this so late, I just saw the change by accident.
Section 3 also had the note about using interfaces ("Consider using interfaces for data models").
While the interfaces vs. classes debate might be dependent of the project, I liked to have it as a rule in the style guide. When working with immutable (or pseudo-immutable) data structures, classes are not easy to reason about, although this is not clear at first sight.
Do you see a way of getting this rule back, maybe even with some more explanation?

**Comment by trotyl** [comment]
@fmalcher Isn't that documentation belong to specific 3rd-party library? Like [class-support in akita](https://netbasal.gitbook.io/akita/general/class-support).

**Comment by fmalcher** [comment]
@trotyl Thanks for your reply!
IMO, immutable data is not specific for a library, but the principles can (and should) also be applied to a simple Angular application. In order to leverage the `OnPush` strategy in child components we should at least treat objects as immutable using the spread operator – and this is quite a struggle with class instances.
Of course not every simple app need immutability, but in order to prepare people for it, I find a best practice towards classes/interfaces for data models very useful.

**Comment by JohannesHoppe** [comment]
Okay, the style guide wasn't the right place. How about an extra dedicated guide on coding conventions instead? I see several good reasons that speak for interfaces instead of classes, too.  I think we should talk about this somehow.

**Comment by bampakoa** [comment]
Is it supposed to come up again in the style guide? I can see them in the 7.2.12 release 🤔
