### ISSUE TITLE
ngForOf behaves strangely when using data from other elements in the exported NgIterable

### ISSUE THREAD

**Issue by specialkk** [angular/angular#24155]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When a template inside an `*ngFor` directive uses data from another element by accessing it via an index to the alias of the exported `NgIterable<T>` variable, the template is not re-rendered when the data from that element is changed. 

## Expected behavior

It would be nice if this behavior were documented somewhere, or ideally fixed so that the first two columns of the StackBlitz editor below behave the same way.

## Minimal reproduction of the problem with instructions

This is behaves fine:
```html
<div *ngFor="let ele of arr; let i = index">{{arr[i + 1]?.value}}</div>
```
This does not:
```html
<div *ngFor="let ele of arr as arr; let i = index">{{arr[i + 1]?.value}}</div>
```

https://stackblitz.com/edit/angular-ngfor-changedetection

In this example adding a new message will render a block that displays what the `id`s of the previous and next messages are at the time of rendering. The only thing that can cause it to update is when `ngForOf` is able to tell that the individual item has changed (e.g. via a deep copy).

The only solutions that come to mind is to provide a `trackBy` function that incorporates data from the indices that the template needs to render itself (in this example the `id`s of the elements before and after), or to rework the data structure so that the elements in `ngForOf` already have all the data they need to render themselves individually

## What is the motivation / use case for changing the behavior?

The reason for this behavior wasn't immediately obvious and I was pretty confused until I was able to isolate it in a simple example. I'd consider the fact that using an aliased local variable of the exported `NgIterable` variable causes things to behave different a bug.

## Environment

<pre><code>Angular version: 6.0.3</code></pre>

**Comment by mhevery** [comment]
@trotyl Would you be up for creating a fix and a PR?

**Comment by trotyl** [comment]
@mhevery Created https://github.com/angular/angular/pull/24684.
