### ISSUE TITLE
ng new looks for local cli version instead of taking global cli version

### ISSUE THREAD

**Issue by ismailsaleekh** [angular/angular#24159]
## Current behavior
cli version is taken from my old projects, that are placed in the same Disk, in which i m trying to use ng new command

## Expected behavior
my global cli version should be used

## What is the motivation / use case for changing the behavior?
this happens when i try to create new project (ng new) in thi my HDD, which already contains some angular projects in it

## Environment
Windows 8.1, node: 8.11.1, npm: 5.10.0, angular cli: 6.0.5

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Please open angular-cli issues in its repo. Thanks.

**Comment by pkozlowski-opensource** [comment]
This belongs to https://github.com/angular/angular-cli
