### ISSUE TITLE
Error when I run commond "sudo npm install -g @angular/cli "

### ISSUE THREAD

**Issue by solarisy** [angular/angular#24160]
pengdeMacBook-Pro:angular_demos pengwang$ node -v
v8.11.2
pengdeMacBook-Pro:angular_demos pengwang$ npm -v
6.1.0
pengdeMacBook-Pro:angular_demos pengwang$ sudo npm install -g @angular/cli
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/@angular/cli/node_modules/_bonjour@3.5.0@bonjour/node_modules/deep-equal
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/@angular/cli/node_modules/_bonjour@3.5.0@bonjour/node_modules/multicast-dns-service-types
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/@angular/cli/node_modules/_browserslist@1.7.7@browserslist/node_modules/caniuse-db
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/@angular/cli/node_modules/_browserslist@1.7.7@browserslist/node_modules/electron-to-chromium
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/@angular/cli/node_modules/_buffer@4.9.1@buffer/node_modules/base64-js
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/@angular/cli/node_modules/_buffer@4.9.1@buffer/node_modules/ieee754
.
.
.
....

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
