### ISSUE TITLE
Bug: VS Code Autocomplete Stopped Working

### ISSUE THREAD

**Issue by ewaschenko** [angular/angular#24169]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The autocomplete in templates for variables does not work when using VS Code and the extension Angular Language Service for Angular 6.

## Expected behavior

Autocomplete in templates should work for all variables defined in the associated `.ts` file.  This began around the time when Angular 6 was released.

## Minimal reproduction of the problem with instructions

[https://stackblitz.com/edit/angular-e8riby?file=app/button-overview-example.html](https://stackblitz.com/edit/angular-e8riby?file=app/button-overview-example.html)

With the Stackblitz, `myObject` has been defined, but auto-complete does not find it when you try to reference it in the component with `{{ myObject }}` (this uses a pre-made example from angular material)

If you go to the Stackblitz home page and launch the Angular option, the auto-complete works perfectly fine.  

## Environment

<pre><code>
Angular version: 6.0.3

Browser: - N/A
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/vscode-ng-language-service/issues/256. Not a bug in angular's framework.

**Comment by ewaschenko** [comment]
@ericmartinezr Would you know of any idea of why this would be happening?
