### ISSUE TITLE
NgForOf example in the reference documentation still uses a pre-2.0 release of angular

### ISSUE THREAD

**Issue by jnizet** [angular/angular#24163]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Clicking the "live demo" link in the [NgForOf reference documentation](https://angular.io/api/common/NgForOf) leads to http://plnkr.co/edit/KVuXxDp0qinGDyo307QW?p=preview, which still uses pre-Angular2 release code (imports from angular2, for example).

## Expected behavior

It should link to an up-to-date example.

**Comment by ericmartinezr** [comment]
Tracked here https://github.com/angular/angular/issues/21525, will be fixed  by https://github.com/angular/angular/pull/23966
