### ISSUE TITLE
[NgUpgrade] Disable interpolation for `[attr]` attributes of downgraded components

### ISSUE THREAD

**Issue by th0r** [angular/angular#24161]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[?] Bug report  
[ ] Performance issue
[?] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently AngularJS interpolates values for `[attr]` attributes of downgraded components. Because of this template compiler throws a parse errors in such cases:
```html
<downgraded-comp
  [obj]="{key: '{{ !!! just a string that should not be interpolated !!! }}'}">
</downgraded-comp>
```

## Expected behavior

Angular shouldn't interpolate values of `[attr]` or `[(attr)]` attributes.

## What is the motivation / use case for changing the behavior?

In a few places in our project we generate dynamic JSON objects and inject them as component attributes. If some of those objects contain `{{` characters Angular tries to interpolate them and throws compilation error.  

## Environment
<pre><code>
Angular version: 1.5.8 / 6.0.3
Browser: any
</code></pre>

**Comment by gkalpak** [comment]
Sorry, but this works as intented. The "contract" is that everything inside an AngularJS template belongs to AngularJS (and follows its rules). Changing this for `[prop]` bindings would not only be inconsistent but also a breaking change (e.g. there can be valid usecases where one wants the values to be interpolated).

So, as is the case for pure AngularJS apps, if you want an attribute value to contain interpolation markers without been interpolated, you need to [escape the markers][1]:

```html
<downgraded-comp
  [obj]="{key: '\{\{ !!! just a string that should not be interpolated !!! }}'}">
</downgraded-comp>
```

[1]: https://docs.angularjs.org/api/ng/service/$interpolate#escaped-interpolation
