### ISSUE TITLE
This property fromEvent does not exist on type 'typeof Observable'

### ISSUE THREAD

**Issue by josuevalrob** [angular/angular#24167]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am following the Ng-book version 6. 
I am stuck in an example that makes a search YouTube video as you type. When the search returns we’ll show a list of video thumbnail results, along with a description and link to each video.

So for this, we use an observable.fromEvent: https://github.com/NiLinli/ng-book2-angular-6-r68-code-samples/blob/master/http/src/app/you-tube-search/search-box.component.ts

But i am getting this error: 

> ERROR in src/app/search-box/search-box.component.ts(42,13): error TS2339: Property 'fromEvent' does not exist on type 'typeof Observable'.

## Expected behavior
I expect an observable from the event.

## Minimal reproduction of the problem with instructions
This is my code: 
```
import {
  Component,  OnInit,  Output,  EventEmitter,  ElementRef} from '@angular/core';
// By importing just the rxjs operators we need, We're theoretically able to reduce our build size vs. importing all of them.

import { Observable } from 'rxjs';
import 'rxjs/add/observable/fromEvent';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/filter';
import 'rxjs/add/operator/debounceTime';
import 'rxjs/add/operator/do';
import 'rxjs/add/operator/switch';

import {YoutubeSearchService} from '../services/youtube-search.service';
import {SearchResult} from '../search-result.model';

@Component({
  selector: 'search-box',
  template: `
  <div class="ui raised very padded text container segment">
  	<div class="ui input">
  		<input type="text" class="form-control" placeholder="Search" autofocus>
  	</div>
  </div>
  `,
  styles: []
})
export class SearchBoxComponent implements OnInit {

	@Output() loading: EventEmitter <boolean> = new EventEmitter<boolean>();
	@Output() results: EventEmitter <SearchResult[]> = new EventEmitter<SearchResult[]>();
// .el is an object of type ElmentRef, which is an Angular wrapper around a native element
  constructor(private youtube: YoutubeSearchService, private el: ElementRef) { }

  ngOnInit(): void {
  	// Convert the `keyup`event into an observable
	Observable.fromEvent(this.el.nativeElement, 'keyup')
		.map((e:any) => e.target.value) // extract the value of the input
		.filter((text:string) => text.length > 1) //filter out if empty
		.debounceTime(250) //only search after 250 ms
		.do(() => this.loading.emit(true)) // Enable loading
		// search, call the search service
		.map((query:string) => this.youtube.search(query)) 
		// discard old events if new input comes in
		.switch()
		// act on the return of the search
		.subscribe(
			(results: SearchResult[]) => { //on success
				this.loading.emit(false);
				this.results.emit(results);
			},
			(err: any) => { //on error
				console.log(err);
				this.loading.emit(false);
			},
			()=> { // on complete
				this.loading.emit(false)
			}
		);
  }

}

```

## What is the motivation/use case for changing the behavior?
I want a fromEvent working on Angular 6

## Environment

<pre><code>
Angular 6 last release
 
For Tooling issues:
- Node version: v10.0.0  
- Platform:  Mac High Sierra
</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by josuevalrob** [comment]
thanks.

**Comment by josuevalrob** [comment]
I like breaking bad too...

**Comment by tobiz-pb** [comment]
Solution: https://stackoverflow.com/questions/52137092/angular-6-throttletime-doesnt-exist-in-rx-js/52137107
