### ISSUE TITLE
feat(http): implement support for headers and url params objects in http

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2417]
The constructors for `Headers` and `UrlSearchParams` have already been implemented to near-spec ([Headers](https://fetch.spec.whatwg.org/#terminology-headers), [UrlSearchParams](https://url.spec.whatwg.org/#urlsearchparams)) in PR #2360, but have not been incorporated into the request process. These should be incorporated in such a way that a dictionary or fully-constructed object of each type can be attached to request options passed to `http`, and will properly be attached to the outgoing request (headers), or serialized into the url string (params).

**Comment by caitp** [comment]
I'd like to take this one on as well, but if someone wants this they can take it

**Comment by jeffbcross** [comment]
@caitp FYI basic headers setting has been implemented in xhr_backend with #2828, but there's still work to be done in the `RequestOptions` merging process.
