### ISSUE TITLE
Feature: Child Form Groups

### ISSUE THREAD

**Issue by kevupton** [angular/angular#24172]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

At the moment I am looking for functionality to create child `FromGroup` from parent `FormGroup` so that data can be synced, but separated across multiple forms. At the moment I only have the following code:

## Current behavior

```ts
    this.detailsFormGroup = builder.group({
      displayName: [contentStandard.displayName, Validators.required],
      websiteAddress: [contentStandard.websiteAddress, Validators.required],
      retailerTeamId: [contentStandard.retailerTeamId, Validators.required],
      namespace: [contentStandard.namespace, Validators.required],
      altTextStatus: [contentStandard.altTextStatus, Validators.required],
      altTextLengthLimit: [contentStandard.namespace, this.validateAltTextLength],
    });

    this.displayLogoGroup = builder.group({
      displayLogo: [contentStandard.displayLogo, Validators.required]
    });

    this.pdfUploadGroup = builder.group({
      pdfFileUrl: [contentStandard.pdfFileUrl, Validators.required]
    });

    this.slotGroupArray = builder.array(
      contentStandard.slots.map(slot => this.newSlotFormGroup(slot))
    );
```

Where this form is a vertical stepper and steps through each of the form groups. 

Getting the whole object:
```js
{
      ...this.detailsFormGroup.value,
      ...this.pdfUploadGroup.value,
      ...this.displayLogoGroup.value,
      slots: this.slotGroupArray.value,
    }
```

## Expected behavior

It would save a lot of work being able to combine them all into one form group and then separate them in the html or code. So that validation can be applied to only a subset group:
```js
this.formGroup = builder.group({
  displayName: [contentStandard.displayName, Validators.required],
  websiteAddress: [contentStandard.websiteAddress, Validators.required],
  retailerTeamId: [contentStandard.retailerTeamId, Validators.required],
  namespace: [contentStandard.namespace, Validators.required],
  altTextStatus: [contentStandard.altTextStatus, Validators.required],
  altTextLengthLimit: [contentStandard.namespace, this.validateAltTextLength],
  displayLogo: [contentStandard.displayLogo, Validators.required],
  pdfFileUrl: [contentStandard.pdfFileUrl, Validators.required],
  slots: builder.array(
    contentStandard.slots.map(slot => this.newSlotFormGroup(slot))
  )
});
```
```html
<div [formGroup]="formGroup.child(['displayName', 'websiteAddress', 'retailerTeamId'])"></div>
<div [formGroup]="formGroup.child(['displayLogo'])"></div>
<div [formGroup]="formGroup.child(['pdfFileUrl'])"></div>
```
Geting the whole object:
```js
this.formGroup.value
```

## What is the motivation / use case for changing the behavior?

This would make the logic of having a complete form object separated into multiple pages using a stepper much simpler.
In this scenario the form maps directly to a type of object which would make sense to keep it in a whole object.
## Environment

<pre><code>
Angular version: 5.2.4

**Comment by kara** [comment]
It's already possible to create nested `FormGroups` as children of existing `FormGroups`. See [the guide here](https://angular.io/guide/reactive-forms#nested-formgroups).
