### ISSUE TITLE
Update guide lacks clarity 

### ISSUE THREAD

**Issue by tatsujb** [angular/angular#24174]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

the update doc : https://update.angular.io/ to me is unclear. 

I figured out by myself that "I use ngUpgrade" means "I'm upgrading from AngularJS to whatever" , it should have this or similar info tacked on to help out the user. otherwise the user has no idea whether to tick or not. the name could easily be confused for something more global.

but that's a minor issue.

the real issue is at : 

> If you import any animations services or tools from @angular/core, you should import them from @angular/animations

Ok so I glean from that, that it'll be something to do with animations.... wait exclusively? it does say " or tools" it doesn't say "or animation tools", that's too generic it could mean anything. 

plus how does this concern a angular 5.2 user? won't he already have been using @angular/animations instead? 

then why is it saying I should look for that? what am I looking for? an example would go such a long way.

**Comment by ericmartinezr** [comment]
https://github.com/StephenFluin/angular-update-guide/issues
