### ISSUE TITLE
@angular/elements component events are called from an inconsistent zone

### ISSUE THREAD

**Issue by divdavem** [angular/angular#24181]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Event handlers in an angular element (registered as a custom element with `@angular/elements`), are called either from the angular zone or from the root zone depending on how the element is instantiated, leading to different behaviors:
- if the element is in the initial markup of the page (before the custom element is registered), then event handlers are called from the angular zone (as expected), and the change detection and refresh of the template are done correctly
- if the element is created from the angular zone (after the custom element is registered), then event handlers are called either from the angular zone (in Chrome, leading to a correct behavior) or from the root zone (in other browsers, leading to an incorrect behavior: the change detection is not done and the template is not refreshed)
- if the element is created from the root zone (after the custom element is registered), then event handlers are called from the root zone (both in Chrome and other browsers), leading to an incorrect behavior: the change detection is not done and the template is not refreshed.

## Expected behavior

The angular element should behave correctly no matter how it is instantiated.
In the minimal reproduction sample, clicking on "Toggle display" should work no matter the line.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-dxu5td?file=src%2Fapp%2Fhello.component.ts
Depending on the line and the browser, clicking on the "Toggle display" works or has no effect.
In Chrome, only the first two lines work correctly. In other browsers, only the first line works correctly.

## What is the motivation / use case for changing the behavior?

The current behavior is inconsistent. Event handlers should be called from the angular zone no matter how the component is instantiated, which would allow those components to be created from any other framework even if that framework does not run in the angular zone.

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x] Chrome (desktop) version 66.0.3359.181
- [x] Firefox version 60.0.1
- [x] IE version XX
- [x] Edge version XX

</code></pre>

**Comment by divdavem** [comment]
@remackgeek Thank you for your quick response with a PR!

**Comment by robwormald** [comment]
In general, I'm not super excited about adding a bunch of affordances for Zones + Elements - the future of Elements is almost certainly Zoneless, so I'm concerned about adding a bunch of Zone specific APIs we have to support forever. 

@remackgeek your PR seems fine, though it might be better implemented as an additional ElementStrategy/Factory (or potentially a subclass of the ComponentFactoryStrategy - which developers who wanted to use Zones could pass into the `createCustomElement` call. The explicit pass in (vs detecting internally) means that if a developer doesn't pass the zone strategy in, it could be treeshaken away.

**Comment by JiaLiPassion** [comment]
@robwormald , I agree an additional ElementStrategy/Factory is better, by checking current NgZone is using `zone.js` or `noopzone`, we can use different Strategy.

And do you have chance to take a look at my proposal? https://github.com/JiaLiPassion/angular-elements-with-zone
I believe we can make `zone.js only active` inside `Angular Elements` without impact outside world, so user can have another option to develop `Angular Elements`.
The benefits of this idea are : 
1. user can develop `Angular Elements` just like developing `normal Angular Components`.
2. user can easily migrate existing `Angular Components` to `Angular Elements`.

Please check it when you have time.    Thank you!

**Comment by remackgeek** [comment]
@robwormald, At my company there is a big opportunity for using elements in older applications -- and the developers are used to change detection that Just Works(tm), so I think the zone use case brings a lot of value.

So you are thinking something like this to enable zones:

`
    const strategyFactory = new ComponentNgElementZoneStrategyFactory(HelloComponent, injector);
    const customElement = createCustomElement(HelloComponent, { injector, strategyFactory });`

and then a strategy with methods something like this?

` connect(element: HTMLElement) {   this.insureAngularZone( () => { super.connect(element);});}
  private insureAngularZone(fn: () => any) {    
NgZone.isInAngularZone() ? fn() : this.ngZone.run(fn); 
 }`

I'll update the PR

**Comment by remackgeek** [comment]
...or, add a new optional field to the configuration:
`const insureAngularZone = true;`
`const customElement = createCustomElement(HelloComponent, { injector, insureAngularZone })`

and change the factory constructor to add the boolean (defaulting to false). Then you wouldn't need to have a new factory and add it to the public API

Let me know which way you prefer.

**Comment by robwormald** [comment]
@remackgeek more like the first one - it doesn't require changing the API surface of `createCustomElement`

**Comment by otodockal** [comment]
I don't know guys, I've seen Angular elements as a great opportunity to promote more OnPush, fewer dependencies (Zone.js)...and locality ;-)

**Comment by remackgeek** [comment]
@robwormald, I've updated the PR per your comments. Please take a look.

**Comment by LinBoLen** [comment]
same issue occurred to me

**Comment by krawetko** [comment]
What is the plan on this? Having an opportunity to export existing AngularComponents and use them in non Angular or legacy AngularJS application with Zone/Change Detection working out of the box would be a huge use case for my company (and for many others with legacy / non angular systems i believe)

**Comment by krishna217** [comment]
In which version will the issue be fixed. Any expected timeline ?

**Comment by remackgeek** [comment]
@krishna217, It will be fixed in  the next release of zone.js, by this PR: [angular/zone.js#1133](https://github.com/angular/zone.js/pull/1133).

Per this issue [#1149](https://github.com/angular/zone.js/issues/1149), they haven't said when that release is planned.

**Comment by shai93** [comment]
ERROR Error: Uncaught (in promise): TypeError: n.e is not a function
TypeError: n.e is not a function
    at i (main.73bb8af0aafb54188d28.js:1)
    at e.loadFactory (main.73bb8af0aafb54188d28.js:1)
    at e.load (main.73bb8af0aafb54188d28.js:1)
    at e.loadModuleFactory (main.73bb8af0aafb54188d28.js:1)
    at e.load (main.73bb8af0aafb54188d28.js:1)
    at t.project (main.73bb8af0aafb54188d28.js:1)
    at t._tryNext (main.73bb8af0aafb54188d28.js:1)
    at t._next (main.73bb8af0aafb54188d28.js:1)
    at t.next (main.73bb8af0aafb54188d28.js:1)
    at e._subscribe (main.73bb8af0aafb54188d28.js:1)
    at resolvePromise (zone.js:852)
    at resolvePromise (zone.js:809)
    at zone.js:913
    at ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (main.73bb8af0aafb54188d28.js:1)
    at ZoneDelegate.invokeTask (zone.js:422)
    at Object.onInvokeTask (main.73bb8af0aafb54188d28.js:1)
    at ZoneDelegate.invokeTask (zone.js:422)
    at Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)

ERROR Error: Expected to not be in Angular Zone, but it is!
    at Function.e.assertNotInAngularZone (main.73bb8af0aafb54188d28.js:1)
    at Object.next (main.73bb8af0aafb54188d28.js:1)
    at t.object.o [as _next] (main.73bb8af0aafb54188d28.js:1)
    at t.__tryOrUnsub (main.73bb8af0aafb54188d28.js:1)
    at t.next (main.73bb8af0aafb54188d28.js:1)
    at t._next (main.73bb8af0aafb54188d28.js:1)
    at t.next (main.73bb8af0aafb54188d28.js:1)
    at t.next (main.73bb8af0aafb54188d28.js:1)
    at t.emit (main.73bb8af0aafb54188d28.js:1)
    at main.73bb8af0aafb54188d28.js:1

I'm getting this erro when use angular element in other angular project and ng build --prod

**Comment by Ashwin2488** [comment]
Still the change detection in angular elements does not work in legacy edge with latest zone.js. Only way to get it work was through @remackgeek solution https://github.com/remackgeek/elements-zone-strategy. It works fine in chrome without adding the zone strategy.

**Comment by gkalpak** [comment]
FWIW, this has been fixed by Zone.js v0.8.27 for browsers that natively support Custom Elements (e.g. Chrome, Firefox, Chromium-based Edge, etc.). For browsers that require a polyfill, the fix from Zone.js v0.8.27 does not fix all the cases (depending on the polyfill, because each one exercises the native APIs in unconventional ways).

Indeed the only way to fix this reliably would be to ensure that Angular Elements related operations happen inside the Angular Zone (with something like #23885 or #24185, either by updating `@angular/elements` or documenting the use of an external library (such as [remackgeek/elements-zone-strategy][1]).

https://github.com/angular/angular/issues/24181#issuecomment-393331388 is still relevant, so I am not sure what the correct resolution would be.

[1]: https://github.com/remackgeek/elements-zone-strategy

**Comment by remackgeek** [comment]
@gkalpak , if you are going to leave this for external library support, could you please take [PR 26216](https://github.com/angular/angular/pull/26216), to avoid having to use knowledge of internal data structures?

**Comment by gkalpak** [comment]
Sounds reasonable. It seems that `ComponentNgElementStrategy` was [meant to be public API][1] all along.

Unfortunately, it seems that #26216 has slipped through the cracks and is quite old now (not to mention failing CI). Would someone be interested in submitting a new PR with this change. (It would be rad if someone wanted to add some API docs for [NgElementStrategy][3] too 🤩)

##
BTW, just to be clear, I did not suggest we should leave this for external library support (that is just one of the options and we might indeed end up deciding to go that way).

[1]: https://github.com/angular/angular/blob/1b55da10b1f4443f4e30807568832086f5127c80/packages/elements/src/component-factory-strategy.ts#L43
[2]: https://github.com/angular/angular/blob/1b55da10b1f4443f4e30807568832086f5127c80/packages/elements/src/element-strategy.ts#L28-L33
