### ISSUE TITLE
rest parameter signature is not available for console.log

### ISSUE THREAD

**Issue by ketanyekale** [angular/angular#24193]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The code I'm trying to use:
```
log(...input) {
	if (this.getCookie('dev') == 'dev') {
		console.log(...input);
	}
}
```

Error:
```
[12:01:39]  ngc started ...
[12:01:52]  typescript: c:/xampp/htdocs/app/client/app/src/providers/commondata.ts, line: 400
            Supplied parameters do not match any signature of call target.

     L399:  if (this.getCookie('dev') == 'dev') {
     L400:      console.log(...input);

Error: Failed to transpile TypeScript
    at errorCheckProgram (c:\xampp\htdocs\app\client\app\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:119:39)
    at Object.<anonymous> (c:\xampp\htdocs\app\client\app\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:89:21)
    at step (c:\xampp\htdocs\app\client\app\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:32:23)
    at Object.next (c:\xampp\htdocs\app\client\app\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:13:53)
    at fulfilled (c:\xampp\htdocs\app\client\app\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:4:58)
    at <anonymous>
[12:01:52]  copy finished in 13.96 s
``` 

## Expected behavior

console.log should work for rest parameter just like it works in browser console.
Check the code below in the browser console:
```
function log(...input){
     console.log(...input);
}
log(1,2);
console.log(1,2);
```

## Minimal reproduction of the problem with instructions
To reproduce the issue define a function `log` in you class as:
```
log(...input) {
	console.log(...input);
}
```
and instead of calling console.log call:
```
this.log(param1,param2,param2);
```

## What is the motivation / use case for changing the behavior?

The actual definition for the log function is:
```
log(...input) {
	if (this.getCookie('dev') == 'dev') {
		console.log(...input);
	}
}
```
With this simply by setting a cookie on live environment, I'll be able to check the logs. 

## Environment

<pre><code>
Angular version: 4.1.3

Browser:
- [x] Not related to Browser(The issue is with ngc)
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:- 
Node version: The issue is independent of node version. I'm using v- 8.11.1
Platform:  The issue is independent of platform. I've tried on Windows

Others:
None.

</code></pre>

**Comment by splincode** [comment]
https://github.com/Microsoft/TypeScript/issues/4130

**Comment by vicb** [comment]
Closing as this does not seem related to Angular as indicated in the messages above
