### ISSUE TITLE
Angular 6 CLI does not copy library's assets folder into dist folder.

### ISSUE THREAD

**Issue by 7bamboo** [angular/angular#24190]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Upon building & packaging an Angular 6 library e.g. `@acme/lib1` using `ng build @acme/lib1`, the Angular CLI does not copy the library's assets into the `dist/acme/lib1/assets` folder. This happens also when using the `--prod` flag.

The CLI seems to only support copying the root app's assets but not library specific assets.
When trying to add `"assets": ["src/assets"]` to project `@acme/lib1` within `angular.json`, the following error appears in the command line:

> Schema validation failed with the following errors: Data path "" should NOT have additional properties(assets).

When creating the following custom rule to copy the files on `ng build`:
```
 "assets": [
    "src/favicon.ico",
    "src/assets",
     { "glob": "**/*", "input": "src/assets", "output": "../acme/lib1/assets/" }
],
```
I get the following error:

> An asset cannot be written to a location outside of the output path.

A workaround is to copy the files using the command line (Mac/Linux)

> cp -R projects/acme/lib1/assets/ dist/acme/lib1/assets/

Or another workaround is to use a node script or 3rd party package to manage copying of files.

However, it seems that the CLI already supports assets copying for root assets and, therefore, it will be more consistent to support it for libraries as well.

## Expected behavior
Add ability to define a library specific `assets` property within `angular.json`.
Example - 
```
"@acme/lib1": {
      "root": "projects/acme/lib1",
      "sourceRoot": "projects/acme/lib1/src",
      "projectType": "library",
      "prefix": "lib",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "projects/acme/lib1/tsconfig.lib.json",
            "project": "projects/acme/lib1r/ng-package.json",
            "assets": [ // <--------- this is currently not supported
              "src/assets"
            ]
          },
  ...}
```

## Minimal reproduction of the problem with instructions
(1) Create a library @acme/lib1 using `ng generate library @acme/lib1`
(2) Add a `"projects" -> "@acme/lib1" -> "architect" -> "build" -> "options" -> "assets"` key to the library's config within `angular.json` file.

## What is the motivation / use case for changing the behavior?
Very often libraries include image files, icons, css files and other static files which are needed to be distrubted with the package.

## Environment

<pre><code>
Angular version: 6.0.x

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: v9.3.0
- Platform:  Mac

</code></pre>

**Comment by gkalpak** [comment]
This is a issue with `@angular/cli`. Please re-open on https://github.com/angular/angular-cli.

**Comment by 7bamboo** [comment]
Ok thanks, opened it as [#11071](https://github.com/angular/angular-cli/issues/11071)

**Comment by Tefofo** [comment]
@7bamboo after manually copying the assets folder to the dist folder where do you reference your assets in your library project?
