### ISSUE TITLE
Router/PreActivation: Multiple Resolvers resolving to empty observables cause uncaught EmptyError

### ISSUE THREAD

**Issue by richard-voss** [angular/angular#24195]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When there is a route with more than one resolver, empty observables (no next, only complete, as in EmptyObservable) are treated differently than with a single resolver:
- if for example 1 of 2 resolvers resolves to an empty observable, the navigation is not canceled, but the corresponding route-data-field is undefined as result
- if all resolvers resolve to empty observables, navigation is canceled, but due to an uncaught EmptyError, because the combined resolvers are piped through a last() operator

## Expected behavior

- if any resolver resolves to empty, navigation must be canceled, as it is the behaviour for a single resolver
- even if all resolvers resolve to empty, the router should not emit any uncaught errors

## Minimal reproduction of the problem with instructions

1. open: https://angular-gitter-enmoca.stackblitz.io
2. click the link and observe an uncaught EmptyError in the browser console

the interesting code is in app.module.ts, it configures a route with two resolves that resolve to EMPTY

## What is the motivation / use case for changing the behavior?

In our case, we have implemented an error consuming procedure that takes care of any failures during resolver actions (like http errors), thus in case of an error it is important to be able to indicate route cancellation without forwarding an error to the router.

(a) Because if a resolver cannot obtain what it is supposed to obtain, we do not want to navigate, because the destination page would be empty/broken.
(b) we treat uncaught errors as potential bugs (and have set up an error handler accordingly). An error from a resolver ends up as uncaught error, which would be wrong in the case of a handled http failure.
(c) This resolving to "nothing" with am empty observable is just the right way to indicate navigation shall be cancelled but no error should end up in the console. As it is already the case with single resolvers.

## Environment

<pre><code>
Angular version: 5.2.9
Also in Angular 6, see the angular-gitter link.

Browser: (i believe irrelevant)
- [x] Chrome (desktop) version 66
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 60
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.5 (i believe irrelevant)
- Platform:  Mac (i believe irrelevant)

Others:
I belive the problem is the implementation of resolveNode in PreActivation. It should rather combine multiple resolvers using the semantics of Observable.combineLatest(...) and the takeLast(1) operator, because last() causes the EmptyError... but i have no further knowledge of the angular codebase, so that is just my 2 cents.
</code></pre>

**Comment by demsey2** [comment]
hey I have the same problem and I hope this will be fixed, a simple example
```
const appRoutes: Routes = [
...
  {
    path: 'tasks',
    loadChildren: () =>
      import('./pages/tasks/tasks.module').then(m => m.TasksPageModule),
  },
];
```
```
@NgModule({
  imports: [
    CommonModule,
    RouterModule.forChild([
      {
        path: '',
        component: TasksPage,
        resolve: {
          tasks: TasksResolver,
        },
        runGuardsAndResolvers: 'always',
        canActivate: [AuthGuardService],
      },
      {
        path: ':id',
        component: TaskPage,
        resolve: {
          tasks: TaskResolver,
        },
        runGuardsAndResolvers: 'always',
        canActivate: [AuthGuardService],
      },
    ]),
  ],
  declarations: [TasksPage],
  providers: [TasksResolver],
})
export class TasksPageModule {}
```
when I navigate to /tasks and TasksResolver will fail and return empty() the navigation is not cancelled

the only ways to get that working is:
```
// move that
  {
        path: 'tasks',
        component: TasksPage,
        resolve: {
          tasks: TasksResolver,
        },
// to the app routes, but then lazy loading will load the whole module and it's not that lazy anymore
const appRoutes: Routes = [
...
  {
        path: 'tasks',
        component: TasksPage,
        resolve: {
          tasks: TasksResolver,
        },
        runGuardsAndResolvers: 'always',
        canActivate: [AuthGuardService],
        loadChildren: () =>
          import('./pages/tasks/tasks.module').then(m => m.TasksPageModule),
      },
];
```
or manually navigate to previous route in your resolver 
```
this.router.navigate(['/']);
```

**Comment by pkarny** [comment]
Issue is still there in Angular 8.2.7. I have tested a simple `resolve()` method with `return EMPTY` and the component was still loaded. Navigating away helps, but either code should be fixed or docs should clearly state that `this.router.navigate` prevents the execution not the `return EMPTY`

**Comment by Wisdomb33r** [comment]
Same here with Angular 8.2.8. One of the main point of using resolvers is to load the minimum information required to navigate to a routed component (which can then load a lot of asynchronous information if needed). The typical case is a general resolver for the whole application, high in the route tree, loading configuration from backend. And more specific per-route (lazy loaded children route in my case) resolvers to load the main business object needed toi avoid a blank page (a person, a contract, ...). 

If any of the routers cannot provide data, the navigation should be prevented, otherwise the routed component needs to handle null provided data, which completely nullify the interest of resolvers (to my opinion at least). Thumbs up for the issue, but it does not looks very popular...

**Comment by rastafan** [comment]
I had a similar issue with resolvers today. 
I tried to stop navigation by returning EMPTY in resolver, though a catchError in the observable. 

```
 return this.webservice.getThings().pipe(
            catchError((err, caught) => {
                console.log('ERROR');
                console.log(err);
                this.started = false;
                if (this.spinner) {
                    this.loadingController.dismiss();
                }
                return EMPTY;
            }),
            tap({
                next: () => { this.started = false; if (this.spinner) { this.spinner.dismiss(); } },
                error: () => { this.started = false; if (this.spinner) { this.spinner.dismiss(); } },
            })
        );
```

Returning EMPTY stops navigation, but triggers an "EmptyError: no elements in sequence" error. 
May be related to #24621.
