### ISSUE TITLE
Provide primitives to iterate ES6 Maps with ngFor

### ISSUE THREAD

**Issue by mprobst** [angular/angular#24200]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Iterating an ES6 map in Angular is surprisingly hard.

The code below does not work, map is not iterable:

```ts
@Component({template: `<p ngFor="let something of myMap"></p>`})
class MyComponent {
  myMap = new Map([['a', 1], ['b', 2]]);
}
```

The code below doesn't work either, because `Map.prototype.keys` returns a new array on each call, so the expression is not stable:

```ts
@Component({template: `<p ngFor="let key of myMap.keys()"></p>`})
class MyComponent { /* as above */ }
```

Similarly for `.entries`.

## Expected behavior

This is hard to solve automatically for Angular. Watching the map just by identity might be wrong, if user code mutates the map. Watching the map's entries instead of the map itself can cause performance issues, as it is slow for large maps. So some programmer intervention is required. However currently Angular doesn't provide any way to fix this problem at all.

Angular should provide two pipes out of the box to deal with mutable and (effectively) constant maps:

```html
<p ngFor="let key of myMap | mutableMap"></p>
<p ngFor="let key of myMap | immutableMap"></p> <!-- or constMap ? -->
```

`mutableMap` would watch the map's entries. `immutableMap` would watch just the map by identity. I'm not sure if these should give `entries` or `keys`.

@mhevery promised to add a pipe back in https://github.com/angular/angular/issues/2246, but that never happened.

**Comment by mhevery** [comment]
# Design

```
<p ngFor="let key of myMap | toList"></p>
```

## Const

There is a suggestion to do const list.
```
<p ngFor="let key of myMap | mutableToList"></p>
```

However this is an ad-hoc solution. I would prefer to a solution which would work across many bindings in a consistent way. Let's hold of on implementing that.

**Comment by mprobst** [comment]
I don't understand this bit:

> it should be a non-pure map so that the pipe can keep an internal state of the `Array<KeyValue<K, V>>` and return the same instance if the input of the pipe has not changed.

Do you mean this handles the case where the `Map`, `Object`, or `WeakMap` is mutable, and we have to check the actual array?

I don't understand the `mutableToList` case - `let key of myMap` currently AFAIU doesn't work, and I don't understand the name `mutableToList` - what would that do?

**Comment by mhevery** [comment]
@marclaval `non-pure` just means that the `toKeyValue` can have internal state which can propagate between invocations. The internal state is needed so that the `toKeyValue` returns the same result instance if the input does not change.

I am only saying that you are suggesting to do `immutableMap` (which I renamed to `mutableToKeyValue`). I am saying that we should not implement it, since it is not a holistic solution, rather than one-off.

**Comment by mprobst** [comment]
@mhevery SGTM.

**Comment by trotyl** [comment]
FYI: `WeakMap` cannot be iterated.

**Comment by Toxicable** [comment]
There's this PR here https://github.com/angular/angular/pull/11319
and I came up with this implementation here https://stackblitz.com/edit/entries-pipe?file=app%2Fentries.pipe.ts
Which satisfies a couple of your design points @mhevery

**Comment by mhevery** [comment]
> There's this PR here #11319

Excellent! see: https://github.com/angular/angular/pull/11319#pullrequestreview-125340944

**Comment by mhevery** [comment]
Resolved by https://github.com/angular/angular/pull/24319

**Comment by mprobst** [comment]
Nice, thanks!
