### ISSUE TITLE
HttpInterceptor not returning any response back with forkJoin and token as Observable

### ISSUE THREAD

**Issue by Ahmad-Magdy** [angular/angular#24215]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have a Service to get the token from type Observable and HttpInterceptor to use it to inject the token in every http request. The thing is it works fine with a single request but if i used forkJoin i will not get any response back. also it will work  with forkJoin if the token was normal string not Observable or if i used take(1) but this isn't what i want because if the token changed the request should get the new token.

## Expected behavior

It should work even  with forkJoin to handle muliple requests

## Minimal reproduction of the problem with instructions

Example for the error: 
https://stackblitz.com/edit/angular-kpxvej

and here is my interceptor 
```typescript
import { HttpErrorResponse, HttpEvent, HttpHandler, HttpInterceptor, HttpRequest } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, } from 'rxjs';
import { catchError, map, switchMap } from 'rxjs/operators';
import { AppService } from './app.service';
@Injectable()
export class AuthInterceptor implements HttpInterceptor {
  constructor(
    private service: AppService
  ) { }

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return this.service.token$.pipe(
      map((token: string) => {
        if (token) {
          const headers = req.headers.set('Authorization', `Bearer ${token}`);
          console.log(`Request for url ${req.url}`);
          req = req.clone({
            headers: headers
          });
        }
        return req;
      }
      ),
      switchMap(newReq => next.handle(newReq))
    )
  }
}

```

the interceptor will work with frokJoin in case the token was a string
 ```typescript
 intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    const token = this.service.getToken();
    const headers = req.headers.set('Authorization', `Bearer ${token}`);
    console.log(`Request for url ${req.url}`);
    req = req.clone({
      headers: headers
    });
    return next.handle(req);
  }
```
and code example 
```typescript
// Service
export class AppService {
  token$ = new BehaviorSubject<string>(null);
  constructor(private http: HttpClient) {
    this.token$.next('MYTOKEN');
  }

  getUsers() {
    return this.http.get<any[]>(`https://jsonplaceholder.typicode.com/users`);
  }

  getPosts() {
    return this.http.get<any[]>(`https://jsonplaceholder.typicode.com/posts`);
  }


// Single One will work
 this.appService.getPosts().subscribe(res => console.warn(res));

// Will not work
    forkJoin([this.appService.getPosts(), this.appService.getUsers()])
      .subscribe(([posts, users]) => {
        console.log(posts, users);
      });

```

## What is the motivation / use case for changing the behavior?

the token may change during  using the app so the request should get the latest token not the older version of it.

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v9.10.0  
- Platform: Windows 

Others:

</code></pre>

**Comment by Airblader** [comment]
forkJoin doesn't emit until all inputs have completed. Your token observable doesn't complete, thus the observable returned by the interceptor doesn't complete and thus your forkJoin never emits You're just using rxjs wrong, there's no bug here.

**Comment by Airblader** [comment]
(On a side note, when making requests without forkJoin, you get values, but since they don't complete you're just creating memory leaks. Interceptors are not the tool to keep observables alive over time. You should do this in your services)

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by dielangsea** [comment]
i add next.complete() and it work.
