### ISSUE TITLE
Faild using 'ng build --prod ' build project with angular6 

### ISSUE THREAD

**Issue by StellaLim** [angular/angular#24216]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I'm so sad with buiding project using 'ng build --prod ' falid. I have been spend over three day update angular 5 to 6 and want build --pord. Using ng build --prod when building I wait long time about 15min. Maybe because my project is big... However, after servaral time terminal shows error like this:
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/fv1FB.png

## Expected behavior
Using ng build --pord succesful.

## Environment

<pre><code>
 {
    "name": "zhgyl",
    "version": "0.0.0",
    "license": "MIT",
    "scripts": {
    "ng": "ng",
    "start": "ng serve --env=prod --proxy-config proxy.conf.json",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
    },
    "private": true,
    "dependencies": {
      "@angular-devkit/core": "^0.3.2",
      "@angular/animations": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "angular-tag-cloud-module": "^3.0.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "ngx-echarts": "^3.0.0",
    "echarts": "^3.8.5",
    "font-awesome": "^4.7.0",
    "fullcalendar": "^3.7.0",
    "jquery": "^3.2.1",
    "moment": "^2.18.1",
    "ng2-file-upload": "^1.2.1",
    "node-sass": "^4.9.0",
    "primeng": "^5.2.4",
    "rxjs": "^6.2.0",
    "rxjs-compat": "^6.0.0-rc.0",
    "zone.js": "^0.8.26"
    },
    "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.6",
    "@angular/cli": "^6.0.7",
    "@angular/compiler-cli": "^6.0.3",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.3.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "^2.0.2",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.3.2",
    "ts-node": "~3.2.0",
    "tslint": "^5.0.0",
    "typescript": "~2.7.2",
    "wangeditor": "3.1.0"
    }
    }

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

This belongs here https://github.com/angular/angular-cli. Also look at the issues that report the same https://github.com/angular/angular-cli/search?q=heap+out+of+memory&unscoped_q=heap+out+of+memory&type=Issues
