### ISSUE TITLE
Long requests are re-sent to server every two minutes

### ISSUE THREAD

**Issue by Biquette** [angular/angular#24219]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When a request is long using HttpClient, on get, the request is sent again every two minutes, up to 10 times.

## Expected behavior
I would expect the request to wait for the response without re-sending the request to my server.

## Minimal reproduction of the problem with instructions
Easy : A simple request, server side, doing a wait for more than two minutes and a little snippet calling it, on client side.

## What is the motivation / use case for changing the behavior?
We can not change this behaviour on dev side.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 60.0.1
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1
- Platform:  Windows 7 Enterprise

Others:

</code></pre>

**Comment by Airblader** [comment]
This is almost certainly an issue on your end. Please provide a Stackblitz reproducing the issue.

**Comment by vicb** [comment]
Closing as no repro.
