### ISSUE TITLE
Invalid `metadata.json` when multiple barrel exports from packages

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#24225]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When having multiple barrel exports from external packages incorrect metadata file is being generated, as some exports are missing.

## Expected behavior
The metadata file contains all exports.

## Minimal reproduction of the problem with instructions
Create a `.ts` file, containing 2 barrel exports example;
**tsconfig** 
```json
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "flatModuleId": "index",
    "flatModuleOutFile": "index.js"
  },
```

**public-api.ts** 
```ts
export * from '@angular/common';
export * from '@angular/common/testing';
```

 **.metadata.json**
```json
{
    "__symbolic": "module",
    "version": 4,
    "exports": [
        {
            "from": "@angular/common/testing"
        }
    ],
    "metadata": {},
    "origins": {},
    "importAs": "AUTOGENERATED"
}
```

## What is the motivation / use case for changing the behavior?
Consumer will have an error

## Environment

<pre><code>
Angular version: 6.0.2
TypeScript: 2.7.2
Tsickle: 0.27.5

</code></pre>

**Comment by alxhub** [comment]
This is fixed in Angular Ivy in v9, as the Ivy compiler completely ignores `metadata.json` files. Eventually they will cease to exist  🎉
