### ISSUE TITLE
CUSTOM_ELEMENTS_SCHEMA breaks validation for known components

### ISSUE THREAD

**Issue by cronon** [angular/angular#24223]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I use angular alongside with custom elements, however if I use CUSTOM_ELEMENTS_SCHEMA it stops validating not only custom elements, but angular components as well

## Expected behavior
I'd like validation continue to work for angular components

## Minimal reproduction of the problem with instructions
1. Go to https://stackblitz.com/edit/angular-lmwemp?file=src/app/app.module.ts
2. See the error `Can't bind to 'foo' since it isn't a known property of 'app-heroes'`
3. Uncomment line 17 in `app.module.ts`
4. No more error

## Environment

<pre><code>
Angular version: 6.0.3
</code></pre>

**Comment by mhevery** [comment]
Yes, that is the correct behavior. We don't know what elements are custom-elements and so we have to disable the validation everywhere. There really is no good way to know which element is custom element and which is not.

**Comment by cronon** [comment]
Indeed, when we face some tag we cannot say if it is custom element or just a misspelled tag. But at least we could check if this tag is an angular component and make validation for it :)

**Comment by pkozlowski-opensource** [comment]
This is still reproducible with the lates Angular v9 running ivy: https://stackblitz.com/edit/angular-ivy-nyg1z7?file=src%2Fapp%2Fapp.component.ts

While it is true that during AoT compilation `CUSTOM_ELEMENTS_SCHEMA` disables all validation for custom elements not specified in the schema (as we can't known if it is valid or not), we could improve situation a bit in JIT, as checks are done during runtime in ivy. Relevant code: https://github.com/angular/angular/blob/ed1b4a8f198eff41559c7c3fc4b1bceab96e8395/packages/core/src/render3/instructions/shared.ts#L1091-L1105

**Comment by pkozlowski-opensource** [comment]
Also relevant: #12045

**Comment by atscott** [comment]
Closing in favor of #12045
