### ISSUE TITLE
Update to ng 6 breaks font awesome icons

### ISSUE THREAD

**Issue by loutocky** [angular/angular#24220]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
After update to ng 6 from ng 4, icons from font awesome package lost padding. I have seen, there is new class at every font awesome icon with name ng-star-inserted caused by BrowserAnimationsModule, but I am not able to find any settings of padding via developer tools in Chrome. It is a global issue of whole frontend. See image below.

<img width="357" alt="current" src="https://user-images.githubusercontent.com/17061923/40786393-3ad3d000-64eb-11e8-9f42-caa4b9f1cf09.png">

## Expected behavior
Every font awesome icon or badge will have the same padding like before. See attached image.

<img width="375" alt="expected" src="https://user-images.githubusercontent.com/17061923/40786394-3b23ea68-64eb-11e8-98c2-6d64fd535d10.png">

## What is the motivation / use case for changing the behavior?
It breaks frontend of our app.

## Environment

<pre><code>
Angular version: 6.0.7
ng-bootstrap version: 4.7.0
font-awesome version: 3.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.2  
- Platform:  Mac

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
The ng-star things is explained in the changelog: https://github.com/angular/angular/blob/master/CHANGELOG.md#520-2018-01-10

The padding "problem" sounds to be caused by  https://angular.io/guide/aot-compiler#preservewhitespaces (see more issues related https://github.com/angular/angular/search?q=preservewhitespaces&type=Issues)

**Comment by loutocky** [comment]
Thank you Eric, preserveWhitespaces: true solved my issue.
