### ISSUE TITLE
Style compiler: remove double spaces and indention symbols from css

### ISSUE THREAD

**Issue by Dok11** [angular/angular#24247]
## I'm submitting a...

<pre><code>
[x] Performance issue
[x] Feature request
</code></pre>

## Current behavior
New lines in scss files and idention symbols saved in bunle file:
![image](https://user-images.githubusercontent.com/2697890/40833988-213996e0-6598-11e8-8ca3-04b96dae1c27.png)

## Expected behavior
Remove double spaces and `\n` from css in main.bundle.js

## Minimal reproduction of the problem with instructions
Set css compiler as scss and use in component style something like this:
```scss
@import "vars.scss";

:host {
	display: block;
}

.menu {


	a {
		font-weight: 500;

		
	}

}

```

vars.scss
```scss

$blue:         #007bff !default;


$blue-light:   #5d7f92 !default;


$blue-lighten: #94aebd !default;

```

## Environment

<pre><code>
Angular CLI: 1.6.7
Node: 8.9.4
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.7
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

Valuable part of package.json:
	"dependencies": {
		"@angular/animations": "^5.2.9",
		"@angular/common": "^5.2.9",
		"@angular/compiler": "^5.2.9",
		"@angular/core": "^5.2.9",
		"@angular/forms": "^5.2.9",
		"@angular/http": "^5.2.9",
		"@angular/platform-browser": "^5.2.9",
		"@angular/platform-browser-dynamic": "^5.2.9",
		"@angular/router": "^5.2.9",
		"core-js": "^2.5.4",
		"rxjs": "^5.5.8",
		"zone.js": "^0.8.19"
	},
	"devDependencies": {
		"@angular/cli": "1.6.7",
		"@angular/compiler-cli": "^5.2.9",
		"@angular/language-service": "^5.2.9",
		"@types/node": "^6.0.103",
		"codelyzer": "^4.2.1",
		"protractor": "~5.1.2",
		"ts-node": "~4.1.0",
		"tslint": "^5.9.1",
		"typescript": "^2.5.3"
	}
</code></pre>

**Comment by AndrewKushnir** [comment]
Just checked with 13.3.0 version: this problem is resolved, so I'm closing this ticket.
