### ISSUE TITLE
Angular 6 Library module with forRoot DI not working when imported into lazy loaded module

### ISSUE THREAD

**Issue by marcusingogo** [angular/angular#24242]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Angular 6 Library module with forRoot when imported in lazy loaded module of another app gives a "no provider for ..." error when the lazy module is loaded. However when used imported into app.module no error.

## Expected behavior

Be able to import Angular 6 Library module with forRoot in Lazy loaded module and not have to import to app.module

## Minimal reproduction of the problem with instructions
Angular 6 Library Module
```
export class BookingLibModule { 
  public static forRoot(environment: any): ModuleWithProviders {

    return {
        ngModule: BookingLibModule,
        providers: [
            {
                provide: 'env', // you can also use InjectionToken
                useValue: environment
            }
        ]
    };
  }
}
```

Imported into Lazy loaded module of another app gives error:
Uncaught (in promise): Error: StaticInjectorError(AppModule)[env]: 
  StaticInjectorError(Platform: core)[env]: 
    NullInjectorError: No provider for env!

Below is lazy loaded module 
```
import {environment} from './../../environments/environment';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    BookingLibModule.forRoot(environment),

```

But when imported into app.module it works  and there is no error

## What is the motivation / use case for changing the behavior?

Dont wont to import library module in app.module, want to it only to be loaded in lazy loaded module

## Environment

<pre><code>
Angular CLI: 6.0.7
Node: 10.2.1
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.7
@angular-devkit/build-angular      0.6.7
@angular-devkit/build-ng-packagr   0.6.7
@angular-devkit/build-optimizer    0.6.7
@angular-devkit/core               0.6.7
@angular-devkit/schematics         0.6.7
@angular/cli                       6.0.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.7
@schematics/angular                0.6.7
@schematics/update                 0.6.7
ng-packagr                         3.0.0
rxjs                               6.2.0
typescript                         2.7.2
webpack                            4.8.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
