### ISSUE TITLE
event not fired

### ISSUE THREAD

**Issue by jayeshsheta** [angular/angular#24244]
how to achive document.ready()  kind of logic in angular 5 

ngAfterViewInit() not worked for me

 public ngOnInit() {
   
  this.route.queryParams.subscribe(p=>{
    this.AC=p["AC"]||'';
    this.UID=p["UID"]||'';
  });
  
    this.getTiles();
  }

  ngAfterViewInit(){
    //  $(document).ready(function(){
  alert('ok');
    //  });
}

in above code alert fire before my contents load i want to fire it after gettiles() function called

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
