### ISSUE TITLE
Angular6 issue on load of remote web components dynamically

### ISSUE THREAD

**Issue by andreap2018** [angular/angular#24253]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior
We tried to load remote web components dynamically using Angular 6, using the following example application:

https://angular-webcomponents-usage-sample.now.sh/
https://medium.com/@ezekizibzibadze/angular-and-web-components-a-k-a-angular-elements-e009b057cd75

It works with Angular 5.1 but not with Angular 6.0.3

In Angular 6.0.3 the compiler does not generate the following files:
inline.bundle.js
vendor.bundle.js
main.bundle.js 

It generates instead:
vendor.js
main.js 

And if we load the 2 files with:
    await this.loadScript(`${rootUrl}/vendor.js`);
    await this.loadScript(`${rootUrl}/main.js`);

the page does not show the module component, also no errors appears on the browser console.
Do we need to include other files ?

## Expected behavior

Browser should load and display the remote web component.

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x] Chrome (desktop) version 65.0.3325.181
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 60.0
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.1.0
- Platform:  Ubuntu 16.04 LTS

Others:

</code></pre>

**Comment by vicb** [comment]
Could you please provided a minimal reproduction that demonstrates the issue ?

**Comment by andreap2018** [comment]
It requires 2 separate applications running to reproduce it, here are the 2 sample applications:

https://github.com/playerx/angular-webcomponents-usage-sample
https://github.com/playerx/angular-elements-sample

It works with Angular 5.1 but when I upgrade Angular (cli, core ...) to version 6 it doesn't work, 
the page does not show the module component, also no errors appears on the browser console.

This is the application that works with 5.1, module is loaded by clicking on the button 'Load Module'
https://angular-webcomponents-usage-sample.now.sh/

**Comment by 100cm** [comment]
Any update on this?

**Comment by alxhub** [comment]
Closing as obsolete - please reopen if this is an issue with the current Angular.
