### ISSUE TITLE
Angular2 动态生成的html中 (click)事件无效怎么解决？

### ISSUE THREAD

**Issue by Zhongxiangyun** [angular/angular#24250]
```
<div id="imgBox_${id}" class="imgBox" >
                        ${imgName}
                        <img src="/assets/img/poster/del.png" class="remove" (click)="removeBox('1')">
                        <img src="/assets/img/poster/edit.png" style="position: absolute;top: 0;right: 16px;width: 15px;height: 15px;cursor: pointer;" (click)="addImgBox('2')">
                        <input type="hidden" value="${imgName}">
                    </div>
```

由于一些业务需要，需要动态构建dom，然后在它上面绑定一些事件，eg：编辑和删除事件，但是目前是不支持这样的操作模式的，请问有什么办法可以解决？谢谢！

**Comment by jainanuj0812** [comment]
The information provided by you is not sufficient. And please try to explain things in globally accepted language(English).

**Comment by dereklin** [comment]
I think the OP is asking about dynamically constructing the dom.  The dynamically parts might have edit or delete actions.

I think you might need to use native Javascript, eg: document.createElement, element.addEventListener for things like that, depending on how dynamic things are.

Maybe you can point out which part of your code is dynamically generated.

**Comment by Zhongxiangyun** [comment]
I'm sorry, I don't know how to describe this problem in English. I hope a friend can help translate it. Thank you very much!

**Comment by destus90** [comment]
@dereklin she can use [Renderer ](https://angular.io/api/core/Renderer2) class instead of direct access to DOM.

**Comment by dereklin** [comment]
@destus90 Thanks.  I found this which could help OP: https://www.concretepage.com/angular-2/angular-4-renderer2-example

**Comment by sandangel** [comment]
wow, I think she is trying to do something like this:
```typescript
// get id,imgName dynamically
let id, imgName;

@Component({
	template: `
		<div id="imgBox_${id}" class="imgBox">${imgName}
			<img src="/assets/img/poster/del.png" 
				class="remove" (click)="removeBox('1')">
			<img src="/assets/img/poster/edit.png" 
				style="position: absolute;top: 0;right: 16px;width: 15px;height: 15px;cursor: pointer;" 
				(click)="addImgBox('2')">
			<input type="hidden" value="${imgName}">
		</div>
	`
	// ...
})
export class SomeComponent {}
```

**Comment by StephenFluin** [comment]
It looks like @sandangel  or @dereklin may have provided the help needed. As there isn't any description of the problem that the team can act on, I'm closing this issue.
