### ISSUE TITLE
Can't get all releases/latest release via GitHub API

### ISSUE THREAD

**Issue by var-bin** [angular/angular#24268]
Hi there,

Currently, I'm working on [Telegram Bot](https://github.com/var-bin/ReleaseButler) which can help you stay up to date with the new versions of used libraries/frameworks.
The question is: Do you happen to know why GitHub API [https://api.github.com/repos/angular/angular/releases](https://api.github.com/repos/angular/angular/releases) returns an empty array for Angular repo? In another hand, this API has returned all releases for React: [https://api.github.com/repos/facebook/react/releases](https://api.github.com/repos/facebook/react/releases). Does GitHub have an option for blocking releases requests for a particular repo?

Best regards,
Vitalii

**Comment by vicb** [comment]
@ocombe do you have any idea ?

**Comment by ocombe** [comment]
Let me ask my contacts at Github, I'll let you know

**Comment by dawidgarus** [comment]
Maybe use npm registry instead: https://registry.npmjs.org/@angular/core

**Comment by var-bin** [comment]
Hi @dawidgarus,

Thank you for your suggestion. Yes, it's possible but not consistent. I want one source of truth :-)

**Comment by var-bin** [comment]
Hi @ocombe,

Yesterday, I sent the same request to GitHub support for clarifying this issue. Bellow you can find the answer:

> Hi Vitalii,
>
> Thanks for reaching out. The reason why it returns an empty array is that the repository in question doesn't have any Releases -- it only has Tags. The UI lists both releases and tags under the same page, but the API has separate endpoints for listing tags and releases.
>
> Give this a try:
>
> https://api.github.com/repos/angular/angular/tags
>
> Hope this helps.
 
What do you think in this case?

Thanks,
Vitalii

**Comment by ocombe** [comment]
Ok it makes sense, it's true that we don't "draft releases" on the repository (on github), we only tag them in git. I guess that your tool will have to take that into account.

**Comment by var-bin** [comment]
OK, thank you.
