### ISSUE TITLE
Property 'map' does not exist on type 'Observable<Response>

### ISSUE THREAD

**Issue by bishoe** [angular/angular#24265]
[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
## Current behavior
After update my angular cli and create a new project I'm getting a erro in my services:
Property 'map' does not exist on type 'Observable'.

  my code:
import { Injectable } from '@angular/core';
import {Http , Response , Headers , RequestOptions ,RequestMethod } from '@angular/http';

 
import {Employee} from './employee.model';
  
import { Observable, Subject, asapScheduler, pipe, of, from, interval, merge, fromEvent } from 'rxjs';

 
import { map, filter, scan } from 'rxjs/operators';

 
import { webSocket } from 'rxjs/webSocket';

 
import { ajax } from 'rxjs/ajax';

 
import { TestScheduler } from 'rxjs/testing';

 
@Injectable({
  providedIn: 'root'
})
export class EmployeeService {
  selectedEmployee : Employee;

  constructor(private http :Http) { }
    postEmployee(emp : Employee){
      var body = JSON.stringify(emp);
      var headerOptions = new Headers({'Content-Type': 'application/json'});

      var requsetOptions = new RequestOptions({method : RequestMethod.Post,headers :headerOptions});
      return this.http.post('url',body,requsetOptions).map(x => x.json());
    }
  
}

## Expected behavior
I've already imported these packages, but doesn't work anyway
import { Observable, Subject, asapScheduler, pipe, of, from, interval, merge, fromEvent } from 'rxjs';

 
import { map, filter, scan } from 'rxjs/operators';

 
import { webSocket } from 'rxjs/webSocket';

 
import { ajax } from 'rxjs/ajax';

 
import { TestScheduler } from 'rxjs/testing';

package.json

{
  "name": "angular-curd",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "core-js": "^2.5.4",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^6.0.3",
    "@angular-devkit/build-angular": "~0.6.5",
    "typescript": "~2.7.2",
    "@angular/cli": "~6.0.5",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1"
  }
}

Angular CLI: 6.0.5
Node: 8.11.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.5
@angular-devkit/core         0.6.5
@angular-devkit/schematics   0.6.5
@schematics/angular          0.6.5
@schematics/update           0.6.5
rxjs                         6.2.0
typescript                   2.7.2

 
- Node version: v8.11.1
- Platform:  Windows 7 sp1

 thanks

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Rename94** [comment]
npm install --save rxjs-compat@6
SOLVED
