### ISSUE TITLE
Forms restore option not available

### ISSUE THREAD

**Issue by laluali** [angular/angular#24267]
## I'm submitting a...

[x] Feature request
[x] Documentation issue or request

## Current behavior
Form Control allows to pre-populate values, this helps in rendering form in valid state

## Expected behavior
Working as expected.

## Minimal reproduction of the problem with instructions
Create a Reactive form with pre feed values.

## What is the motivation / use case for changing the behavior?
There should be a collection mechanism(watcher) that collects all form Inputs & validates them against initializing values of form, this feature will help in form submit validation and save a large amount of code for small implementation. Right now we dont have any flag that gives us this information.

Example:
Reactive Form loads with name: "XYZ">> right now state is PRISTINE-UNTOUCHED, I click it, so state becomes TOUCHED, I change value becomes DIRTY. I bring the value back to "XYZ", I dont have any flag to tell me that actually there is no change in form values.

## Environment
Angular version: 4^

**Comment by lazarljubenovic** [comment]
You can easily store the original value and do a comparison to see if it's different than original. I don't see a reason for Angular handling this internally.

**Comment by laluali** [comment]
In case of template driven forms its easy(but tedious), in case of reactive forms that needs good amount of code(when i have many fields) for such a small thing.

**Comment by lazarljubenovic** [comment]
If you don't want to manually compare, you can always throw a loop or use a library such as `lodash`. It has the utilities you need.

**Comment by dawidgarus** [comment]
It can be done with simple validator:
```typescript
if (control.pristine) {
  this.value = control.value;
} else if (this.value !== control.value) {
  return { notDefault: true };
}
```

**Comment by kara** [comment]
We aren't very likely to add something like this because it's possible to do manually and doing so inside Angular would create some unnecessary complexity, especially with deeply nested objects. But we do have an open discussion [here](https://github.com/angular/angular/issues/19747), if you want to track it.
