### ISSUE TITLE
bug(forms): AbstractControl.hasError() should check existing key instead of true value

### ISSUE THREAD

**Issue by RKaczmarek** [angular/angular#24276]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Imagine using a validator that checks, if a list contains a minimum of something. This could be described or typed by an enum. So the errors contains a key e.g. "missing" with the enum value.

Checking for an existing error on a control, which has a false value like "0" results in false.

## Expected behavior

The control should check if the key exists instead of checking for a true value.

```ts
  /**
   * Returns error data if the control with the given path has the error specified. Otherwise
   * returns null or undefined.
   *
   * If no path is given, it checks for the error on the present control.
   */
  getError(errorCode: string, path?: string[]): any {
    const control = this._resolvePath(path);
    return control && control.errors ? control.errors[errorCode] : null;
  }

  /**
   * Returns true if the control with the given path has the error specified. Otherwise
   * returns false.
   *
   * If no path is given, it checks for the error on the present control.
   */
  hasError(errorCode: string, path?: string[]): boolean {
    const control = this._resolvePath(path);
    return control && control.errors ? (control.errors as Object).hasOwnProperty(errorCode) : false;
  }

  /**
   * Returns the control for the given path.
   *
   * If no path is given, it returns the present control.
   *
   * @internal
   */
  _resolvePath(path?: string[]): AbstractControl | null {return path ? this.get(path) : this}
```

## Minimal reproduction of the problem with instructions

```ts
  enum Test {ZERO, ONE}
  const control = new FormControl();
  control.setErrors({
    missing: Test.ZERO
  });
  console.log(control.hasError('missing')); // false
```

## What is the motivation / use case for changing the behavior?

Using enum values in errors to describe the exact error.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 8.x 
- Platform: Windows 

Others:

</code></pre>

**Comment by jessicajaniuk** [comment]
Closing based on [this comment](https://github.com/angular/angular/pull/24344#issuecomment-792420090) from @AndrewKushnir on the closed pull request.
