### ISSUE TITLE
Lint - Unable to specify a tslint configuration file per tsconfig project

### ISSUE THREAD

**Issue by felpel** [angular/angular#24275]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

We are not able to assign a specific tslint configuration for a given tsconfig project. 
It results in multiple linting errors/warnings that shouldn't appear based on the tslint configuration for our spec files.

## Expected behavior

With the previous format of `.angular-cli.json`, we were able to assign a tslint config/tsconfig project:
```json
    "lint": [
                {
                         "project": "src/tsconfig.app.json",
			"tslintConfig": "tslint.json",
		},
		{
			"project": "src/tsconfig.spec.json",
			"tslintConfig": "tslint.test.json", // Specific configuration file
		}
      ]
```

## Minimal reproduction of the problem with instructions
- Create new project for Angular 6;
- Create two separate `tslint` configurations for production/test code;
- Extend `tslint.json` in `tslint.test.json` and overwrite some rules as `no-unsafe-any : false`;
- Run `ng lint`;
- Check if any warnings appears.

## What is the motivation / use case for changing the behavior?

We were able to configure explicitely linting rules for production/test code.

## Environment
- Angular version: 6.0.3
- Node version: 8.11.1
- Platform:  Windows

**Comment by ericmartinezr** [comment]
Please open angular-cli's issues in its repo https://github.com/angular/angular-cli/issues 👍
