### ISSUE TITLE
Not able to iterate through response in ngFor in angular 5 from API

### ISSUE THREAD

**Issue by abhiindia** [angular/angular#24271]
Decalared as "terms: any;"

this.auth.getRequest('/terms/terms-list/'+this.auth.email, null ).subscribe(res => {
      this.terms =  res.data;
      console.log(this.terms)
    });

and in html file

<tr *ngFor='let term of terms; index as i'></tr>

But it is giving me error however returning object is valid array.

NavbarComponent.html:80 ERROR Error: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.
    at NgForOf.ngOnChanges (common.js:2579)
    at checkAndUpdateDirectiveInline (core.js:12407)
    at checkAndUpdateNodeInline (core.js:13935)
    at checkAndUpdateNode (core.js:13878)

**Comment by destus90** [comment]
@abhiindia try to declare it this way
```terms: any = [];```

**Comment by lazarljubenovic** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
