### ISSUE TITLE
Uncaught TypeError: Cannot read property 'injector' of null        

### ISSUE THREAD

**Issue by koppulapramod** [angular/angular#24281]
@Injectable()
export class EmployeeService {
      constructor(private _http: Http) {  }
  
  getEmployee(): Observable<IEmployee[]> {
       return this._http.get('http://10.48.11.44:8080/AngularBackendService/rest/employee/findAll')
     .map((response: Response) => <IEmployee[]>Array.of(response.json()))
      .catch(this.handleError);
     }
      handleError(error: Response) {
          console.error(error);
        return Observable.throw(error);
      }

---> I am getting below errors while loading the application. 
![image](https://user-images.githubusercontent.com/39898855/40902697-8860a4ba-67f2-11e8-8ab3-3fde49be9d96.png)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
