### ISSUE TITLE
Error when compiling with ivy `ERROR in ./src/main.ts`

### ISSUE THREAD

**Issue by sushinpv** [angular/angular#24284]
I just created an `Hello world` Angular CLI project to check the working of ivy.

>app.component.html
`<h1>Hello world</h1>`

>tsconfig.app.json
  `"angularCompilerOptions": {`
    `"enableIvy": true`
 ` },`

When i compile with ivy i'm getting error as 
`ERROR in ./src/main.ts
Module not found: Error: Can't resolve './app/app.module.ngfactory' in '/Users/sushinpv/Projects/Angular/Ivy/src'`

But without ivy there is no issue its building without any problem,

**Version details** 

```
Angular CLI: 6.0.7
Node: 10.1.0
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.7
@angular-devkit/build-angular     0.6.7
@angular-devkit/build-optimizer   0.6.7
@angular-devkit/core              0.6.7
@angular-devkit/schematics        0.6.7
@angular/cli                      6.0.7
@ngtools/webpack                  6.0.7
@schematics/angular               0.6.7
@schematics/update                0.6.7
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
```

**Comment by vicb** [comment]
IVY is currently a work in progress and not supported.

**Comment by davidshen84** [comment]
I have an old project that I enabled by following [this guide][1], but I still get this error. Interestingly, if I build my project with `enableIvy = false` first, then I turn on the option, the build with Ivy will pass.

[1]: https://angular.io/guide/ivy
