### ISSUE TITLE
JS Distribution Strategy 

### ISSUE THREAD

**Issue by robwormald** [angular/angular#2428]
Happy to tackle some of these, wanted to list them in case they're already on the roadmap.
- we should stop using the *.es6 extension - it makes it quite difficult to work with the ES6 source.
- ES6 consumers are likely going to want to bundle themselves, vs using a pre-built bundle.
- ES6 consumers are likely going to want to consume ES6 (or TS) source, vs commonJS (which has already caused a few issues)
- There are a bunch of extraneous dependencies listed in the package.json currently (vs being in devDependencies) so installing via jspm adds a huge amount of unnecessary stuff. 

JSPM / SystemJS now support Typescript (including in-browser transpilation), so it might be a good time to look at getting set up in the registry properly. Doing `jspm install npm:angular2` again requires you to manually override to be able to access the ES6 source. We can easily add angular2 to the registry, and add the ovveride there (to point to es6/dev or es6/prod), but it would be nice if it was set up correctly in the repo (and had .js file extensions)

Also note that the Loader spec is changing, and the latest version of SystemJS (0.17+) has a number of breaking changes that may bite us if they're not accounted for: https://github.com/whatwg/loader/issues/52

**Comment by robwormald** [comment]
I'm tracking the registry stuff over here, https://github.com/jspm/registry/pull/385, mostly blocked until we have .js extensions. Note that consuming commonJS works, but when there's a problem with the build (like there is now), we're sort of stuck until the next bump.

**Comment by robwormald** [comment]
example of the kind of overrides needed to use it - not a big issue, but just one more bit of friction to get up and running. https://github.com/robwormald/ng2-jspm-seed/blob/master/jspm.conf.js#L34-L41

**Comment by rkirov** [comment]
@robwormald renaming es6 to js and cleaning up our package.json should happen and are non-controversial (or least this is the place for someone to make them controversial). I will open separate issues for those.

We agree that the bundle is not the way to go for es6 or ts consumers, thats why we publish es6, and ts sources to npm on top of the es5 (commonjs). I am ok with adding jspm info to our package.json as long as it has no maintenance cost. Npm would still be the preferred method for delivering and consuming Angular2.

**Comment by rkirov** [comment]
Superceded by #2447 and #2448
