### ISSUE TITLE
BrowserAnimationModule Bug - router-outlet

### ISSUE THREAD

**Issue by uloga** [angular/angular#24297]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

There seem to be a bug when using BrowserAnimationModule that causes router-outlet to append components instead of replacing them. See the video below:

https://www.youtube.com/watch?v=dAZV_H4d8_k

## Environment

<pre><code>
Angular version: 6.03

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/20290

**Comment by vicb** [comment]
Closing as duplicate
