### ISSUE TITLE
HTTP_INTERCEPTORS can't use providedIn injectable/service

### ISSUE THREAD

**Issue by epelc** [angular/angular#24306]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

You get a missing dependency error if you inject a service which has `providedIn: 'root'` and isn't explicitly provided in a module if you try to use it in an http interceptor.

## Expected behavior

HTTP_INTERCEPTORS should load the `providedIn` injectable correctly just like components, services, etc.

## Minimal reproduction of the problem with instructions

* Inject a provider which is using `providedIn` into an http interceptor. It will be undefined unless you use the old non tree shakable style of importing a module that explicitly provides that injectable/service.

## What is the motivation / use case for changing the behavior?

Simplify http interceptors with new tree shakable injectables.

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
Not related to `HTTP_INTERCEPTORS`, just that `providedIn` cannot be combined with `multi: true`. (Should still be valid feature request)

**Comment by trotyl** [comment]
`providedIn`s are only used for default implementation, namely what the designer want  `HTTP_INTERCEPTORS` to be by default (no custom implementation).

But clearly you're not the designer of `HTTP_INTERCEPTORS`, also it won't have any default implementation.

The request itself doesn't make sense.

**Comment by epelc** [comment]
@trotyl I'm asking for an interceptor to be able to use an injectable's default implementation(some injectable which I am the designer).

ie `MyAuthInterceptor` requires `SomeAuthService` which has `providedIn: 'root'` doesn't work with interceptors

**Comment by trotyl** [comment]
Please make a reproduction via https://stackblitz.com/

**Comment by epelc** [comment]
Hmm reproduction isn't showing the issue for some reason. 

https://stackblitz.com/edit/angular-pehule

**Comment by futurizing** [comment]
Not sure if it's the same problem, but I recently encountered this. Here's the reproduction edited from @epelc 's: https://stackblitz.com/edit/angular-cyj13k

In my case, that the constructor of `AuthManagerService` tries to create a HTTP request using `HttpClient`, which then instantiates `AuthHttpInterceptor` with `AuthManagerService` its dependency, causing the silent cyclic dependency problem, injecting `undefined` value to the interceptor instead.

I think there should be at least an error message. Not sure why it does not throw any error, similar to the normal dependency injection system.

**Comment by JGH153** [comment]
The behavior changes if I switch back to the old way of providing the services (in the module, as opposed to providedIn: 'root'). The old way causes an infinite loop where a new instance of the service is created each time the interceptor intercepts a new request, and each new instance of the service fires a new http request. It never stabilises before exceeding max call stack size. 

Stackblitz example: https://stackblitz.com/edit/angular-s99pyd

**Comment by justin1291** [comment]
I was having the same issue.

- I removed providedIn from my service
- Added "undefined" service in providers of AppModule **before** providing HttpInterceptor

```
providers: [
   PreviouslyUndefinedService,
    {provide: HTTP_INTERCEPTORS, useClass: HttpInterceptorService, multi: true}
  ]
```
