### ISSUE TITLE
'Access-Control-Allow-Origin' header issue in Angular 4 for cross domain accessing

### ISSUE THREAD

**Issue by AkhilNaidu09** [angular/angular#24305]
Failed to load http://abcdefg/token?grant_type=password&username=abc&password=abc: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.

![image](https://user-images.githubusercontent.com/13352708/40979193-b3dfaa54-68f2-11e8-9391-aeb006ee690b.png)

```
 request(url: string | Request, options?: RequestOptionsArgs): Observable<Response> {
        return super.request(url);
    }

    get(url: string, options?: RequestOptionsArgs): Observable<Response> {
        this.beforeRequest();
        return super.get(url, this.getRequestOptionArgs(options)).map((response) => {
            this.afterRequest();
            return response;
        }).finally(() => {
            this.afterRequest();
        });
    }

    post(url: string, body: string, options?: RequestOptionsArgs): Observable<Response> {
        this.beforeRequest();
        return super.post(url, body, this.getRequestOptionArgs(options)).map((response) => {
            this.afterRequest();
            return response;
        })
            .finally(() => {
                this.afterRequest();
            });

    }

    put(url: string, body: string, options?: RequestOptionsArgs): Observable<Response> {
        return super.put(url, body, this.getRequestOptionArgs(options)).map((response) => {
            this.afterRequest();
            return response;
        }).finally(() => {
            this.afterRequest();
        });
    }

    delete(url: string, options?: RequestOptionsArgs): Observable<Response> {
        return super.delete(url, this.getRequestOptionArgs(options)).map((response) => {
            this.afterRequest();
            return response;
        }).finally(() => {
            this.afterRequest();
            alert('Something went wrong please contact your system administrator !!')
        });
    }

    private beforeRequest(): void {
        $('#loadingScreen').addClass('d-block');
    }

    private afterRequest(): void {
        $('#loadingScreen').removeClass('d-block');
    }

    private getRequestOptionArgs(options?: RequestOptionsArgs): RequestOptionsArgs {
        if (options == null) {
            options = new RequestOptions();
        }
        if (options.headers == null) {
            options.headers = new Headers();
        }
        return options;
    }
```

I tried all the ways by adding Custom Headers but its not working can you please post a solution for **Angular 4**

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mlc-mlapis** [comment]
@AkhilNaidu09 ... it's the CORS problem ... it is related to your server side configuration. It's not related to Angular at all.

**Comment by jithureddy** [comment]
@mlc-mlapis as explained, @AkhilNaidu09 Add accept allow origin headers as * in your server code. 

**For example:** 
We have a REST API endpoints running in nodejs express server. Since both the frontend server and services server running on different ports, we need to make sure, let each of these applications know each other to make a secured connection.

However you have an option to not to allow any unknown client, but you can mention the domain names of different clients so that your server aware of who is being access the resources.

**Code:** 

const app = express();

app.use(function (req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    next();
});

This is not related to UI framework as such.

**Comment by AkhilNaidu09** [comment]
Thanks @jithureddy . I will look into it.

**Comment by vicb** [comment]
Does not seem related to angular
