### ISSUE TITLE
Issue : Angular 4/IOS Devices/Safari: - Auto detecting Mobile Number not working as expected in iOS Safari 

### ISSUE THREAD

**Issue by ravitejadeevi** [angular/angular#24304]
## I'm submitting  below iOS Feature which is not working as expected in Angular 2/4/6 

iOS Feature : "By default, Safari on iOS detects any string formatted like a phone number and makes it a link that calls the number."

## Current behavior
In Angular2/4 -  Safari on iOS does not  detect any string formatted like a phone number and it does not  make it a link(iOS Devices).

## Expected behavior
By default, Safari on iOS detects any string formatted like a phone number and makes it a link that calls the number.  

**Note: Working as expected in environments  : Plain HTML and Angular 1.x.**

## Minimal reproduction of the problem with instructions
Please go with the below JS Fiddle URL:

https://jsfiddle.net/1hk7knwq/3752/

## Environment

<pre><code>
Angular version: X.Y.Z

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
In Angular2/4 -  Safari on iOS does not  detect any string formatted like a phone number and it does not  make it a link(iOS Devices).

## Expected behavior
By default, Safari on iOS detects any string formatted like a phone number and makes it a link that calls the number.  

## Minimal reproduction of the problem with instructions
Please go with the below JS Fiddle URL:

https://jsfiddle.net/1hk7knwq/3752/

## Environment

<pre><code>
Angular version: 2/4/6
Angular version: 2/4/6

Browser:

- [ ] Safari (iOS) version XX

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

**Comment by mlc-mlapis** [comment]
@ravitejadeevi ... and what are the rules on which iOS is doing so?

**Comment by ravitejadeevi** [comment]
@mlc-mlapis  It is default behavior of iOS Devices.   It detects the phone numbers automatically when we do a long press on the number it shows  bottom sheet which has options to make a call.

This Feature is present only in iOS - Safari

**Comment by mlc-mlapis** [comment]
@ravitejadeevi ... lol, I know it ... but I don't know exactly what rules have to satisfied from HTML / DOM side of view to allow Safari to react by that way.

**Comment by mlc-mlapis** [comment]
@ravitejadeevi ... did you read https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html#//apple_ref/doc/uid/TP40008193-SW1

**Comment by ravitejadeevi** [comment]
We don't have any special rules for this . just you can give any valid mobile number in plain HTML and check in device how it behaves and same way in Angular 2 observe the difference(below URL)

https://jsfiddle.net/1hk7knwq/3752/

**Comment by ravitejadeevi** [comment]
<meta name="format-detection" content="telephone=no"> 
By using this meta tag we can hide this feature. But our requirement is we have to show this feature.

**Comment by vicb** [comment]
Have you tried https://stackoverflow.com/questions/13662175/how-to-create-hyperlink-to-call-phone-number-on-mobile-devices ?

**Comment by ravitejadeevi** [comment]
@vicb  Yes we are aware of it. But that is not our requirement. We don't want to wrap the number in an anchor tag. iOS Safari makes any 10 digit number a hyperlink which when long pressed slides up a bottom sheet and provides options to make a call.

**Comment by vicb** [comment]
My guess reading the [Apple docs](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/PhoneLinks/PhoneLinks.html) is that Safari as to parse the html to detect phone numbers. 

Angular creates element programmatically and this is not something that is possible to change.

So I am going to close this issue. Alternatively you might want to create an issue on the Safari bug tracker to ask if they could unify programatic text nodes creation with html parsing.

_Note for people looking at this last comment only: you can use `<a href="tel:+15555551212">555-555-1212</a>` that works across browser. It's only the auto-detection that is not working on Safari_
