### ISSUE TITLE
Angular Router does not update optional parameters

### ISSUE THREAD

**Issue by nickwinger** [angular/angular#24316]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

For deeplinking i'm changing only the optional parameters in the current route like this:
this.router.navigate(['.', params], { relativeTo: this.route });

This works 2 times, the 3rd time it does not update the url anymore.
I debugged the source code and it seems like somehow it says that the currentUrlTree is the same
as the new url, but the currentUrlTree is wrong, because it is not the currentUrl that i see in the browser...
The router thinks that the url has not changed, because the currentUrlTree is wrong.

## Expected behavior

It should update the url with the new optional parameters

## Minimal reproduction of the problem with instructions

Just change optional parameters in the current route multiple times

## What is the motivation / use case for changing the behavior?

Sync the url for deeplinking

## Environment
Windows 10, newest node, newest npm, newest angular

<pre><code>
Angular version: 6.0.1

Browser:
- [x ] Chrome (desktop) version 66
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1
- Platform:   Windows

Others:
Somehow the sync works with the queryParameters, so i made a hacky workaround that works:
this.router.navigate(['.', params], {relativeTo: this.route, queryParams: {ts: Date.now()} });

I just use a timestamp inside the queryParameters, with the queryParameters the change detection works.
With only the optional parameters -> NOT

**Comment by splincode** [comment]
Please, add repo or example on stackblitz for reproduce

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
