### ISSUE TITLE
docs ( Attribute Directives ) example

### ISSUE THREAD

**Issue by chdnitinsharma** [angular/angular#24314]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Source: https://angular.io/guide/attribute-directives

## Small change will be 
"You use the **ElementRefin** the directive's constructor to inject a reference to the host DOM element, the element to which you applied appHighlight."
must be a 
"You use the **ElementRef in** the directive's constructor to inject a reference to the host DOM element, the element to which you applied appHighlight."

Below this sentence "Here's the updated directive in full:"
## src/app/highlight.directive.ts
<pre><code>
import { Directive, ElementRef, HostListener } from '@angular/core';

@Directive({
  selector: '[appHighlight]'
})
export class HighlightDirective {
  constructor(private el: ElementRef) { }

  @HostListener('mouseenter') onMouseEnter() {
    this.highlight('yellow');
  }

  @HostListener('mouseleave') onMouseLeave() {
    this.highlight(null);
  }

  private highlight(color: string) {
    this.el.nativeElement.style.backgroundColor = color;
  }
</code></pre>

## Expected behavior

<pre><code>
import { Directive, ElementRef, HostListener } from '@angular/core';
 
@Directive({
  selector: '[appHighlight]'
})
export class HighlightDirective {
  constructor(private el: ElementRef) { }
 
  @HostListener('mouseenter') onMouseEnter() {
    this.highlight('yellow');
  }
 
  @HostListener('mouseleave') onMouseLeave() {
    this.highlight(null);
  }
 
  private highlight(color: string) {
    this.el.nativeElement.style.backgroundColor = color;
  }
**}** // Missing
</code></pre>

## What is the motivation?

To make documentation clear. So that user can use it without any hassle.

**Comment by jenniferfell** [comment]
Thanks! Double thanks for linking to a fix. This was also reported and a fix might be in progress here: https://github.com/angular/angular/issues/23503

**Comment by jenniferfell** [comment]
I'm going to mark this closed as a duplicate, because it looks like there's a PR already attached to issue #23503 (PR #23972 ).

**Comment by chdnitinsharma** [comment]
Okay. Thanks you.
