### ISSUE TITLE
`valueChanges` fires before control values are updated (template forms) in Angular 6

### ISSUE THREAD

**Issue by CWSpear** [angular/angular#24312]
## I'm submitting a...

<pre><code>[x] Regression (a behavior that used to work and stopped working in a new release)</code></pre>

## Current behavior

When you subscribe to `this.ngForm.valueChanges`, the values you pass into `ngModel` (i.e. `[(ngModel)]="user.firstName"`) are no longer up to date in the `subscribe` callback. (i.e. `user.firstName` would still hold the old value).

## Expected behavior

The values you pass into `ngModel` to have the latest value. (i.e. `user.firstName` would have the new value). This is how it worked in Angular 5, and it no longer works in Angular 6.

## Minimal reproduction of the problem with instructions
Here's a quick and easy demo that shows the expected behavior in Angular 5.2.9 and rxjs 5.5.7: [demo on Angular 5.2.9](https://stackblitz.com/edit/angular-5-value-changes-v2?file=src%2Fapp%2Fapp.component.ts)

Here's _the exact same app code_, but using Angular 6.0.3 and rxjs 6.2.0: [demo on Angular 6.0.3](https://stackblitz.com/edit/angular-6-value-changes-v2?file=src%2Fapp%2Fapp.component.ts)

You should notice that the snapshot displayed is stale... it doesn't update when the value changes like it used to.

## What is the motivation / use case for changing the behavior?
I mean, the main motivation is that we don't want to rewrite all of the code that depends on this behavior. 😄 

I noticed some changes were made to `ngModelChange`, but the way they were described, makes me believe the above was not an intentional change. I would expect that in `valueChanges`, my controls have the latest value, which is consistent with Angular 5. I can't think of a reason to change it to the way it is, which makes me believe it's a regression. Or at least I hope.

## Environment

<pre><code>Angular version: 5.2.9
Angular version: 6.0.3

Browser:
- [x] Firefox version 60.0.1

 
For Tooling issues:
- Node version: v10.3.0
- Platform:  Mac</pre></code>

**Comment by mlc-mlapis** [comment]
@CWSpear ... isn't related to the Possible Breaking Changes in 6.0?

> **forms:** `ngModelChange` is now emitted after the value/validity is updated on its control.

https://github.com/angular/angular/blob/master/CHANGELOG.md#possible-breaking-changes

**Comment by CWSpear** [comment]
Except `valueChanges` is being emitted _before_ the value is updated on the control.

**Comment by CWSpear** [comment]
So let's say it is related (it makes sense that `ngModelChange` triggers `valueChanges`). We have no way to get a snapshot of our model in its current state in the `subscribe` callback. It leaves us with no way to do something with our model while reacting to changes to the model as a whole (since our model doesn't necessarily follow the same structure as the form).

**Comment by kara** [comment]
@CWSpear This is expected behavior that follows the breaking change @mlc-mlapis mentioned. It looks like your code relied on the `ngModelChange` event always firing before `valueChanges`, which is not desirable because it creates confusing behavior for more typical template-driven patterns (it looks like the code mixes the two strategies, which we don't recommend).  

If you want the latest value, the value that comes through the `valueChanges` stream will always be the latest. Or you can switch to `ngModelChange`.

**Comment by CWSpear** [comment]
It's obviously confusing both ways. :-(

I can't switch to `ngModelChange`, as that doesn't work on an `ngForm` directive.

**Comment by mlc-mlapis** [comment]
@CWSpear ... if you use reactive driven pattern somehow ... it's logical that you get the latest values through the `.valueChanges` stream. Is it a problem for your case?

**Comment by CWSpear** [comment]
@mlc-mlapis Yes, the values returned in `.valueChanges` are based on the `ngForm` structure, which creates the keys via the `name` attributes on the components with `ngModel`, which won't match the actual model structure in most cases.

We use this pattern for simple composite sub-forms. The main reason we went with a primarily template-driven solution for these is because:

* it allows us to use strong types for our models, something we don't have in reactive forms.
* it's easier to do a partial update (you can send a full model and just update a subset of properties).
* it's more of a pain to do dynamic forms (of which we have a lot) with reactive forms.
* directive validation jives better with template forms and is easier to work with, especially with conditional validation.

We just want to update the model (i.e. propagate the change up via CVA) any time anything in the sub-form changed based on our template driven model. Which worked great before this change, unfortunately.

I understand your reasoning, and it makes sense. We just obviously thought our approach made a lot of sense, too, which is why we did it. :)

Maybe if there was a `(ngFormChange)` event on `ngForm` that would be fired _after_ the template model was updated, then we'd be in business. :)
