### ISSUE TITLE
how can i set timeout?

### ISSUE THREAD

**Issue by Webjiacheng** [angular/angular#24313]
my project need to set timeout options,anyone konw how to set?thanks!

**Comment by jainanuj0812** [comment]
It's a support request (not an issue/feature/improvement), can you please try to ask this type of over stackoverflow.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
