### ISSUE TITLE
Can't access Route metadata within a Service from RouterStateSnapshot

### ISSUE THREAD

**Issue by denver-HJS** [angular/angular#24328]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
The `data` object associated with the active route snapshot is empty.

## Expected behavior
The `data` object contains the static metadata associated with the active route.

## Minimal reproduction of the problem with instructions
The stackblitz repro will log the route metadata to the console.

https://stackblitz.com/edit/angular-xhjg5i

## What is the motivation / use case for changing the behavior?
I would like to use the route metadata from within a service in order to prevent requiring awareness of this process by *every* UI component.

## Environment

<pre><code>
Angular version: X.Y.Z
Angular CLI: 6.0.7
Node: 9.11.1
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.7
@angular-devkit/build-angular     0.6.7
@angular-devkit/build-optimizer   0.6.7
@angular-devkit/core              0.6.7
@angular-devkit/schematics        0.6.7
@angular/cdk                      6.2.1
@angular/cli                      6.0.7
@angular/flex-layout              6.0.0-beta.15
@angular/material                 6.2.1
@ngtools/webpack                  6.0.7
@schematics/angular               0.6.7
@schematics/update                0.6.7
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
</code></pre>

**Comment by jasonaden** [comment]
You should instead access `this.route.data` and subscribe to this Observable (or import `take` from `rxjs/operators` and use `take(1)`):

`this.route.data.subscribe(d => console.log(d));`

This will log the values you're looking for. `this.route.snapshot` is mutated over time and is not guaranteed to be the correct value at the time of `ngOnInit`.

**Comment by denver-HJS** [comment]
I'm not looking to use the snapshot at the time of `ngOnInit`, I'm trying to access the active route's metadata from a service (it says this in the title of the issue). 

@jasonaden  I'm not sure why this issue has been closed.

**Comment by denver-HJS** [comment]
@jasonaden @vicb -- the active route's metadata being inaccessible from a service seems like a significant limitation to me.  Is there something that I'm missing?
