### ISSUE TITLE
docs: API list filtered with status=stable shows nothing

### ISSUE THREAD

**Issue by lukepierotti** [angular/angular#24329]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Nothing comes up when filtering the API list with status set to stable
https://angular.io/api?status=stable
## Expected behavior

List of Angular APIs with stable tag should appear when filtering the API List by status=stable

## Minimal reproduction of the problem with instructions

https://angular.io/api?status=stable

## What is the motivation / use case for changing the behavior?

Allow users of documentation to find all stable Angular APIs easily

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jainanuj0812** [comment]
HI

**Comment by jenniferfell** [comment]
For validation, here's one API ref page that should appear when "stable" is chosen: 
https://angular.io/api/common/http/HttpClient

**Comment by petebacondarwin** [comment]
I have a fix here https://github.com/angular/angular/pull/24356
