### ISSUE TITLE
Inconsistent form group creation

### ISSUE THREAD

**Issue by tom-sinclair** [angular/angular#24326]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[x] Other... Please describe: It's a code change (bug fix?) and a documentation change
</code></pre>

## Current behavior

Creating a `FormGroup` by instantiation and creating it with the `FormBuilder` has the tiniest of differences, the key for adding the validators to the `FormGroup` by instantiation is `validators`, however following the same pattern with the `FormBuilder` the key is `validator`, the same is true for `asyncValidators` in the `FormGroup` and `asyncValidator` with the `FormBuilder`.

## Expected behavior

Allow validators and async validators to be added to `FormGroup`s when created with the `FormBuilder` using the same keys as used during the `FormGroup` instantiation.

An extension of this would be to allow the validators and async validators to be passed in as the second and third parameters.

## Minimal reproduction of the problem with instructions
```
createForm( ) {
  this.form = this.formBuilder.group( {
      first_name: [ '', Validators.required ],
      last_name: [ '', Validators.required ],
      email: [ '', [ Validators.required, Validators.email ] ],
      passwords: this.formBuilder.group( {
        password: [ '', [ Validators.required, Validators.minLength( 8 ) ] ],
        password_confirmation: [ '', [ Validators.required, Validators.minLength( 8 ) ] ]
      }, { validators: this.passwordsMatch } ),
      marketing_consent: [ false ],
      recaptcha: [ '', Validators.required ],
      correspondence_address_id: [ '', Validators.required ]
  } );
}

passwordsMatch( group: FormGroup ): ValidationErrors | null {
    return group.get( 'password' ).value === group.get( 'password_confirmation' ).value ? null : { password_mismatch: true };
  }
```

## What is the motivation / use case for changing the behavior?
Seems a quick win for you to update the keys, and provides consistency.

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by AndrewKushnir** [comment]
The mentioned APIs seem to be in sync right now, so I'm closing this ticket. Please reopen if the problem still exists. Thank you.
