### ISSUE TITLE
consider removing tsd es6-promise and other related es6 definitions

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#2433]
Might be a good idea to remove those tsd deps and use the typescript `lib.es6.d.ts`. It provides at least the `Promise` and `Map` definitions. But that's just an idea (more because if I want to use the typescript es6 def. I get conflicts with `es6-promise`).

**Comment by mhevery** [comment]
we have a tasks to completly rebuild the way we generate `angular.d.ts` file and it should be resolved there. Closing for now.
