### ISSUE TITLE
Sass file import not found causing test runner to error/fail

### ISSUE THREAD

**Issue by ashnewport** [angular/angular#24337]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Running `ng test` on a project that uses Sass with `@import` statements in component `scss` files causes the test runner to error resulting in no tests being executed. Even setting `stylePreprocessorOptions.includePaths` in `angular.json` doesn't seem to fix the issue.

Using component `scss` files or third party (Bootstrap, Material) also have the same issue as above and may be another, but similar problem, with tilde imports, e.g. `@import "~@angular/material/theming";`.

A current workaround seems to be using relative paths to import, e.g. `@import "../../sass/theme";`.

I have tried setting `karma.conf.js` to include Sass but I still get the same error, see [How to configure Karma to include global scss files for an angular-cli project?
](https://stackoverflow.com/questions/44460733/how-to-configure-karma-to-include-global-scss-files-for-an-angular-cli-project/)

```bash
...
ERROR in ./src/app/app.component.scss
Module build failed:
@import "theme";
^
      File to import not found or unreadable: theme.
      in C:\Users\me\angular-sass-test\src\app\app.component.scss (line 1, column 1)
 @ ./src/app/app.component.ts 18:21-52
 @ ./src/app/app.component.spec.ts
 @ ./src sync \.spec\.ts$
 @ ./src/test.ts
```

## Expected behavior

`ng test` should execute unit tests and resolve `@import` statements as per `ng serve` or `ng build`. If the `includePaths` are defined then there shouldn't be a need to import with relative paths, e.g. `@import "../../sass/theme.scss";`.

I think when a project is created with the `--style=scss` flag or configured as such then `ng test` should run without error. So if this is a Karma config issue/error, then it should be configured correctly at creation, e.g. `ng new ...`.

## Minimal reproduction of the problem with instructions

```bash
ng new angular-sass-test --style=scss
cd angular-sass-test
ng test
# tests build successfully
```

Create `src/sass` directory and new `theme.scss` for Sass variables.
```bash
mkdir src/sass
touch src/sass/theme.scss
```
Edit `theme.scss`:
```scss
$bg-color: bisque;
$h1-color: cornflowerblue;
```

Edit `src/styles.scss`:
```scss
@import "theme";
body {
  background-color: $bg-color;
}
```

Edit `angular.json`:
```json
// projects.PROJECT-NAME.architect.build.options
...
"stylePreprocessorOptions": {
  "includePaths": [
    "src/sass"
  ]
}
...
```
At this point `ng test` will execute correctly.

Edit `src/app/app.component.scss`:
```scss
@import "theme";
h1 {
  color: $h1-color;
}
```

Execute `ng test` in terminal and the result is:
```bash
...
ERROR in ./src/app/app.component.scss
Module build failed:
@import "theme";
^
      File to import not found or unreadable: theme.
      in C:\Users\me\angular-sass-test\src\app\app.component.scss (line 1, column 1)
 @ ./src/app/app.component.ts 18:21-52
 @ ./src/app/app.component.spec.ts
 @ ./src sync \.spec\.ts$
 @ ./src/test.ts
```

_I'm not sure how to set up [StackBlitz](https://stackblitz.com/) and execute `ng test` otherwise I'd link to one with the above configured._

## What is the motivation / use case for changing the behavior?

I am trying to reuse my Sass variables, mixins, and functions from a `theme.scss` file in my Angular component Sass files, `*.component.scss`. Currently this works when running a build or serve on the application however unit testing cannot run without a workaround (see above) which doesn't seem like the correct way to be coding a project.

## Environment

<pre><code>
Angular version: 6.0.1

For Tooling issues:
- Node version: 9.11.1
- Platform:  Windows
</code></pre>

**Comment by splincode** [comment]
Please add minimum repo for reproduce

**Comment by jotatoledo** [comment]
Shouldnt it be:

````sass
// src/style.scss
@import "./sass/theme";
body {
  background-color: $bg-color;
}
````

considering that the theme file is under `src/sass/`?

**Comment by jotatoledo** [comment]
This should be reported in the cli repo.

**Comment by ashnewport** [comment]
Reported the issue in `angular-cli` repo as per recommendation by @jotatoledo. See https://github.com/angular/angular-cli/issues/11212

Closing this one.
