### ISSUE TITLE
Element is not defined in Universal 6.0.4

### ISSUE THREAD

**Issue by dottodot** [angular/angular#24345]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

After updating to 6.0.4 from 6.0.3 my universal app now throws an error of 

```
ReferenceError: Element is not defined
```
which I assume is something to do with this

https://github.com/angular/angular/pull/24188

## Environment

<pre><code>
Angular CLI: 6.0.7
Node: 8.11.2
OS: darwin x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.7
@angular-devkit/build-angular      0.6.7
@angular-devkit/build-optimizer    0.6.7
@angular-devkit/core               0.6.7
@angular-devkit/schematics         0.6.7
@angular/cdk                       6.2.0
@angular/cli                       6.0.7
@angular/material                  6.2.0
@angular/material-moment-adapter   6.2.0
@ngtools/webpack                   6.0.7
@schematics/angular                0.6.7
@schematics/update                 0.6.7
rxjs                               6.2.0
typescript                         2.7.2
webpack                            4.8.3
</code></pre>

**Comment by hiepxanh** [comment]
wew, can you create a minimum repository ?

**Comment by dottodot** [comment]
I've been unable to create a minimum repository that has the same issue and as I don't know whats causing it, it's going to be hard to replicate. All I know is I have no issues with 6.0.3

**Comment by bflopez** [comment]
@dottodot Supposedly this was fixed in 6.0.4 but I am also getting a similar error I believe. Check out https://github.com/angular/angular/issues/23280

**Comment by hiepxanh** [comment]
@dottodot dott
is that problem still there?

**Comment by dottodot** [comment]
Only if I add `Object.assign(global, domino.impl);` to my server.ts

**Comment by gkalpak** [comment]
Shouldn't this have been fixed by #24116?

**Comment by vikerman** [comment]
Hi - Can someone either share the full error stack or better share a repro repository?
