### ISSUE TITLE
Refresh issue with Child route

### ISSUE THREAD

**Issue by shaheer-scania** [angular/angular#24341]
I am using child route in my application. When I do direct refresh on child path, the style.css is getting loaded on parent path instead of root. This is causing the page to loose global styling as style.css is not found on root. Its working perfectly when navigating with angular routing, but issue happens only I do browser refresh on child route. 

The above issue is not reproducible in local, but happening only when I deploy angular application in AWS cloud-front. I have tried all possible fixes like setting base href, etc.. but no luck

Please help to fix this issue

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
