### ISSUE TITLE
(click) inside *ngIf is not working for some time as soon as DOM is created

### ISSUE THREAD

**Issue by sushree-moharana** [angular/angular#24342]
@All,
I have created a simple dropdown:
1. Header - 
![header](https://user-images.githubusercontent.com/19340495/41095584-72126a16-6a6f-11e8-940d-c074ccb47ddf.jpg)
2. Inner items - 
![inner-dropdown](https://user-images.githubusercontent.com/19340495/41095566-645d55ac-6a6f-11e8-93af-75b1f11e8896.jpg)

Markup URL:
[https://gist.github.com/sushree-moharana/08738b2505a74c249f1e78290fa799e4](url)

Scenario:
On clicking outer row i.e., Header : We will be able to see the inner items(this is done using *ngIf) and clicking the header again or any inner item will close the inner items. And if any item is clicked, it gets selected and the name gets updated in the header.

Issue:
Whenever I click on header, I am seeing the inner items, but not able to select any items instantly. If I open the dropdown and wait for 2-3 seconds, then I am able to select the item in one click. Else its not happening.

Framework used: Ionic
Platform: iOS 11.2.2
Angular version : 5.0.0
 
Ionic has 
(tap): Using this I am not able to scroll the inner items.
tappable: This makes the scrolling too much sensitive , which is very annoying.

From Angular side I tried:
ViewChild: Made a reference to the element and attached click event. Still not working.
Added a directive with @HostListener, still not working.

Still inner item is not getting selected with one click.

Thanks in advance..

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
