### ISSUE TITLE
API template design for method overloads

### ISSUE THREAD

**Issue by jbogarthyde** [angular/angular#24349]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Overload descriptions are hard to identify and navigate through if there are more than two or three.

## Expected behavior
Suggested solution is to increase the weight of the line between overloads, and move the short-description of each method before the code signature. 
I would also  like some kind of marker or icon to distinguish the description of each new overload from the Params/Returns headers of the previous one.

## Minimal reproduction of the problem with instructions
See HttpClient doc, where many methods have 15+ overloads.
Some test doc for the file is in PR 
https://github.com/angular/angular/pull/23839

## What is the motivation / use case for changing the behavior?
It should be easier to find the overload that does what you want. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by petebacondarwin** [comment]
See https://github.com/angular/angular/issues/24331

**Comment by sjtrimble** [comment]
Design we discussed today (PDF included for higher res):
![api-page-overloads](https://user-images.githubusercontent.com/2958442/42059768-5ffb07dc-7ad9-11e8-9def-530c7b9afdf3.png)

[api-page-overloads.pdf](https://github.com/angular/angular/files/2146904/api-page-overloads.pdf)

**Comment by petebacondarwin** [comment]
I think we can close this now that https://github.com/angular/angular/pull/24976 has landed.
