### ISSUE TITLE
DatePipe function parameter documentation shows 'mediumDate' as param type

### ISSUE THREAD

**Issue by andrewseguin** [angular/angular#24355]
The `DatePipe` documentation on angular.io says that the `format` parameter is of type `mediumDate`, which is the default value.

Also, it would help to have table headers to indicate what each column represents, I had to assume that the column meant type

![piqde10qx2e](https://user-images.githubusercontent.com/22898577/41126485-856f65d6-6a5c-11e8-9021-75e6838b9a9f.png)

**Comment by petebacondarwin** [comment]
So this is because that parameter doesn't have an explicit type. It is implied by the default string value:

```ts
transform(value: any, format = 'mediumDate', timezone?: string, locale?: string): string|null {
```

I will try to make the parser more intelligent to get around this.

I can add column headers too.

**Comment by petebacondarwin** [comment]
I have a fix in dgeni-packages for this https://github.com/angular/dgeni-packages/pull/278.
Once it is landed we can update our dependencies.
