### ISSUE TITLE
ngPrint alternative for Angular

### ISSUE THREAD

**Issue by Vishesh-Gupta** [angular/angular#24350]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

There is no new alternative package for ngPrint in the new Angular versions. 

## Expected behavior

The new package should allow developers to print certain sections of their code. The format should also include all the styling done externally or inline using CSS

## What is the motivation / use case for changing the behavior?

The use case for this feature request is for printing something directly from a template becomes easier for people who use external css styling. There are other ways of including the inline css but no way of keeping the external css style.

Developers using Angular have been working by making different templates and then applying other Style Sheets on them externally, either by NPM or using <link> in their html. These style sheets are disabled on the print and we only get to see white and black boxes and improper orientation

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by robwormald** [comment]
ngPrint is a third-party library, not supported by the Angular or AngularJS teams. It was created by someone and open sourced - looking at the implementation, it's not all that complicated, so why not port it to Angular and release it? 

Closing this issue as its not actionable by the Angular team.

**Comment by robwormald** [comment]
@Vishesh-Gupta great! - remember that the CLI can now generate libraries for you, so its a great starting point. See https://github.com/angular/angular-cli/wiki/stories-create-library

**Comment by tayambamwanza** [comment]
@Vishesh-Gupta Have you done any work on this?
