### ISSUE TITLE
Document how to test hybrid apps that include angular.js components

### ISSUE THREAD

**Issue by jpzwarte** [angular/angular#24369]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

After upgrading an angular.js component and then making it available using ```downgradeComponent``` from ```@angular/upgrade/static```, my angular.js karma test fails with:

```
Error: [$injector:unpr] Unknown provider: $$angularLazyModuleRefProvider <- $$angularLazyModuleRef
```

I'm not using a custom karma config. I'm just using the one generated by the angular-cli.

The upgrade guide at https://angular.io/guide/upgrade does not go into what you need to do to get tests running again when you have a hybrid application. It only covers upgrading the tests to angular. SO and Google are no help in this case.

## Expected behavior

It should not fail and the docs should cover this scenario.

## Minimal reproduction of the problem with instructions

This is my compatibility module for angular.js which is a dependency for the module i'm loading in my jasmine test (ng.mock.module):

```
export const compatModule = ng
  .module('compat', [])
  .directive('voPageFooter', downgradeComponent({ component: PageFooterComponent }) as ng.IDirectiveFactory)
  .directive('voPageHeader', downgradeComponent({ component: PageHeaderComponent }) as ng.IDirectiveFactory)
  .factory('ngZone', downgradeInjectable(NgZone));
```

## Environment

<pre><code>
Angular version: 6.0.2
Angular.js version: 1.6.9

**Comment by gkalpak** [comment]
Unfortunately, testing with interdependencies is generally a complex thing in `ngUpgrade`. You should either completely mock out the parts that come from the other framework (e.g. upgraded/downgraded components) or create "mini-apps" that contain all dependencies from both frameworks.

By "mini apps" I mean creating a two modules (one for AngularJS and one for Angular) that contain all the necessary components for the test and then bootstrap that module (as you would bootstrap an actual app).

Most of our own `ngUpgrade` tests use this approach. See for example [this test][1] (but really most `ngUpgrade` tests use the same approach - feel free to look around).

We are also working on some test helpers for `ngUpgrade` (e.g. #16848), which should make such things easier in the future.

##
:+1: on documenting this better. I think the main reason we haven't done so already is that we are not happy with the current state either (but some docs are better than no docs :grin:).

[1]: https://github.com/angular/angular/blob/95fbb7d675d43e6d9954a3f8efb051fcf2f1f58a/packages/upgrade/test/static/integration/upgrade_component_spec.ts#L26-L64

**Comment by jpzwarte** [comment]
@gkalpak Thanks for the explanation.

**Comment by AlexSwensen** [comment]
@gkalpak This explanation is exactly what I have been searching for for a while. Thanks for taking the time to write this out.

I would agree with your statement that this should be documented in some form, even though testing in a hybrid app is not in an ideal state, there are many teams (including my own) that are having to follow the migration path instead of just rewriting from the ground up. 
My own experience has been a process of discovery/the-blind-leading-the-blind. I would have loved some documentation for testing. :-)

As-is, i'll be using your text examples going forward.

---

This is the issue that i ended up on most of the time with my errors. Would be great to have a reference to this issue.
https://github.com/angular/angular-cli/issues/5432

**Comment by edarioq** [comment]
We have a Hybrid app but without AngularCLI. What do you recommend for implementing testing? I can't find anything in the docs for this.

**Comment by aryaroudi** [comment]
The problem I have is, it just doesn't render the angular 2 components while running the AngularJS unit test. There is no error. Do we have any resolution on this? is it bad news or good news that there is no error?

**Comment by gkalpak** [comment]
@aryaroudi, hard to tell with so little info. Make sure you have checked out https://github.com/angular/angular/issues/24369#issuecomment-395843749 (and the links provided there) 😉

**Comment by aryaroudi** [comment]
> @aryaroudi, hard to tell with so little info. Make sure you have checked out [#24369 (comment)](https://github.com/angular/angular/issues/24369#issuecomment-395843749) (and the links provided there) 😉

isn't that comment referred to an angular2 unit test that loads the angular 1 component? In other words, is it possible to do the same in a [ajs-component].spec.js?

**Comment by AlexSwensen** [comment]
@aryaroudi @gkalpak This is something that desperately needs to be documented. Thankfully it is a problem that we have solved. If the angular component is not being rendered, you probably are not bootstrapping the angular portion of your app correctly, or you aren't downgrading the component/service you are testing. Given components are simply custom HTML elements, you probably will not get an error. 

My team is successfully testing and *slowly* migrating an AngularJS application into Angular, and the hybrid is stable in production. I plan to write some posts on my personal blog soon detailing how to migrate from AngularJS to Angular.

Also, I figure I should ask if you are using ui-router or the stock AngularJS router for your app, as that is an important distinction.

**Comment by AlexSwensen** [comment]
@aryaroudi It's also worth pointing out that when I bootstrapped our tests in karma, I found we would hit a race-condition while angular was bootstrapping.

Here is a snippet from our `test.ts` file.

```ts
// test/test.ts
import * as jquery from 'jquery';
declare const window: any;
window.$ = jquery;
window.jQuery = jquery;

import 'zone.js'
import 'zone.js/dist/zone-testing';
import 'zone.js/dist/long-stack-trace-zone'
// import 'zone.js/dist/proxy.js'
import 'zone.js/dist/sync-test'
// import 'zone.js/dist/jasmine-patch'
// import 'zone.js/dist/async-test'
// import 'zone.js/dist/fake-async-test'

declare const __karma__: any;
declare const require: any;

__karma__.loaded = function () {};

import '../src/app/main';

// give the app a second to start...
// This timeout is needed because the process of bootstrapping Angular and AngularJS together
// is asynchronous, so the simplest way to solve the problem is with a short delay.
setTimeout(() => {

  // Then we find all the tests in the test/js directory.
  const context = require.context('./js', true, /_?\.?(s|S)pec$/);
  // and all the tests in the app directory
  const appContext = require.context('./../src', true, /_?\.?(s|S)pec$/)

  // load the modules.
  context.keys().map(context);
  appContext.keys().map(appContext);

  // and run the tests.
  __karma__.start();
}, 1000);
```

Since the bootstrap is asynchronous, we threw in a 1-second timeout before the tests start to be sure it is finished. Ever since then we did not encounter that race condition.

**Comment by aryaroudi** [comment]
> @aryaroudi @gkalpak This is something that desperately needs to be documented. Thankfully it is a problem that we have solved. If the angular component is not being rendered, you probably are not bootstrapping the angular portion of your app correctly, or you aren't downgrading the component/service you are testing. Given components are simply declared with custom HTML tags, you probably will not get an error.
> 
> My team is successfully testing and _slowly_ migrating an AngularJS application into Angular, and the hybrid is stable in production. I plan to write some posts on my personal blog soon detailing how to migrate from AngularJS to Angular.
> 
> Also, I figure I should ask if you are using ui-router or the stock AngularJS router for your app, as that is an important distinction.

Awesome @AlexSwensen, Thanks for the info. My question is the bootstrapping of the application is happening in the `bundle`that is generating by Webpack and before the test gets start, Karma compiles the project and makes a `bundle` by webpackMiddleware and the downgrade, upgrade, etc already have been provided inside the bundle. From this point, is it necessary again you have it done separately in your tests? if yes then I guess we need to change the test unit files to TypeScript in order to be able to use angular decorators, etc for the test and do the operations there. make sense?

**Comment by AlexSwensen** [comment]
@aryaroudi You shouldn't need to bootstrap the application twice. Once is enough.

We had an issue where we didn't want to re-create all of our tests. Turns out we didn't have to due to how you test AngularJS and Angular are different enough and (for the most part) do not interfere with each other.

> As I am seeing also in your `test.sh` it seems that you are running the test on Angular karma, not the Angularjs Karma

I'm a little confused by what you mean here... Karma is a test runner and Jasmine is the default testing framework used by AngularJS and Angular. We are using Karma webpack to bundle our app for running tests, but eventually, we will be running all our tests through the Angular CLI (once we prioritize that part of the process)

**Comment by aryaroudi** [comment]
> @aryaroudi You shouldn't need to bootstrap the application twice. Once is enough.
> 
> We had an issue where we didn't want to re-create all of our tests. Turns out we didn't have to due to how you test AngularJS and Angular are different enough and (for the most part) do not interfere with each other.
> 
> > if yes then I guess we need to change the test unit files to TypeScript in order to be able to use angular decorators, etc for the test and do the operations there. make sense?
> 
> Any tests that touch Angular components/services will need to be in TypeScript, but that is fairly easy to do.
> 
> > As I am seeing also in your `test.sh` it seems that you are running the test on Angular karma, not the Angularjs Karma
> 
> I'm a little confused by what you mean here... Karma is a test runner and Jasmine is the default testing framework used by AngularJS and Angular. We are using Karma webpack to bundle our app for running tests, but eventually, we will be running all our tests through the Angular CLI (once we prioritize that part of the process)

Hey @AlexSwensen you mentioned some valuable points and I appreciate you. When I get this to work will share my resolution compeletly. Is it possible that you share your `Karma.config` file? I got to the point that the karma is complaining about the `test.sh` and says that couldn't find the `test.sh` inside the `files` property of the `tsconfig` which is not correct and it has been added. however, the webpack has the appropriate loader and the build is going fine. Going to share some config with you:

*Webpack.config.js*
```
entry: {
            'bundle.js': './app/main.ts',
             ......
        },
        output: {
            filename: '[name]',
            path: path.resolve(__dirname, 'dist'),
            chunkFilename: 'bundle-[name]-[chunkhash].js'
        },
        module: {
            rules: [
                {
                    test: /\.ts$/,
                    parser: { system: true },
                    exclude: path.resolve(__dirname, "node_modules"),
                    use: [{ loader: '@ngtools/webpack' },
                            { loader: 'tslint-loader',
                               options: {
                                   failOnHint: true
                               }
                            }]
                },
               ....
plugins: [
            new AngularCompilerPlugin({
                mainPath: path.resolve('./app/main.ts'),
                tsConfigPath: 'src/tsconfig.app.json',
                entryModule: 'src/app/app.module#AppModule',
                sourceMap: true,
                nameLazyFiles: true,
                hostReplacementPaths: ifProd({
                    [path.resolve('src/environments/environment.ts')]: path.resolve('src/environments/environment.prod.ts')})
            }),
]
```

*test.sh*
```
import "angular";
import "angular-mocks";

import "./app/main";

const testsContext = require.context("./app", true, /\.spec\.js$/);

testsContext.keys().forEach(testsContext);
```

*karma.config.js*
```
  frameworks: ['mocha', 'chai', 'sinon'],

        'plugins' : [
            require('karma-mocha'),
            require('karma-webpack'),
            require('karma-chai'),
            require('karma-sinon'),
            require('karma-junit-reporter'),
            require('karma-chrome-launcher')
        ],

        // list of files / patterns to load in the browser
        files: [
            './src/test.sh',
        ],

        // list of files to exclude
        exclude: [],

        // preprocess matching files before serving them to the browser
        // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
        preprocessors: {
            './src/test.sh': ['webpack']
        },
```

**Comment by aryaroudi** [comment]
> @aryaroudi You shouldn't need to bootstrap the application twice. Once is enough.
> 
> We had an issue where we didn't want to re-create all of our tests. Turns out we didn't have to due to how you test AngularJS and Angular are different enough and (for the most part) do not interfere with each other.
> 
> > if yes then I guess we need to change the test unit files to TypeScript in order to be able to use angular decorators, etc for the test and do the operations there. make sense?
> 
> Any tests that touch Angular components/services will need to be in TypeScript, but that is fairly easy to do.
> 
> > As I am seeing also in your `test.sh` it seems that you are running the test on Angular karma, not the Angularjs Karma
> 
> I'm a little confused by what you mean here... Karma is a test runner and Jasmine is the default testing framework used by AngularJS and Angular. We are using Karma webpack to bundle our app for running tests, but eventually, we will be running all our tests through the Angular CLI (once we prioritize that part of the process)

Thank you so much Alex! I got it more or less to work just fixing some errors. I have two questions what is this for?

`import '../src/app/main';`

are you importing your `main.ts` of your app which has the bootstrapping function inside it? That would be great if you share an example of a test unit so everyone who is struggling with this problem can have a good picture of it.

**Comment by AlexSwensen** [comment]
@aryaroudi `main.ts` is the main entry point for most stock angular applications. Yes, it also has a fair amount of bootstrapping code. If you are using UIRouter I suggest you look at the docs for [ui-router/angular-hybrid](https://github.com/ui-router/angular-hybrid)

If you are using the stock router I'm really not sure what is involved there beyond what the official docs recommend. Sorry!

My unit tests import the real component code. Sadly I am not in a position where I can share an example for my main application. If I find some time I can try and create a stand-alone example. That might take some time as I have a lot going on at work and in my personal life for the next few weeks.

**Comment by fzxt** [comment]
@gkalpak, correct me if I am wrong but those test helpers introduced in #16848 seem to be targetted towards services (not components). Any thoughts on introducing some helpers for bootstrapping "mini hybrid apps"?

**Comment by gkalpak** [comment]
Right, @fzxt. There are no immediate plans, but #16848 are paving the way :smiley: Hopefully, in the future we could have helpers for components as well (and ideally not even need the mini-apps (wishful thinking ❓)).

**Comment by kriscoleman** [comment]
> @aryaroudi It's also worth pointing out that when I bootstrapped our tests in karma, I found we would hit a race-condition while angular was bootstrapping.
> 
> Here is a snippet from our `test.ts` file.
> 
> ```ts
> // test/test.ts
> import * as jquery from 'jquery';
> declare const window: any;
> window.$ = jquery;
> window.jQuery = jquery;
> 
> import 'zone.js'
> import 'zone.js/dist/zone-testing';
> import 'zone.js/dist/long-stack-trace-zone'
> // import 'zone.js/dist/proxy.js'
> import 'zone.js/dist/sync-test'
> // import 'zone.js/dist/jasmine-patch'
> // import 'zone.js/dist/async-test'
> // import 'zone.js/dist/fake-async-test'
> 
> declare const __karma__: any;
> declare const require: any;
> 
> __karma__.loaded = function () {};
> 
> import '../src/app/main';
> 
> // give the app a second to start...
> // This timeout is needed because the process of bootstrapping Angular and AngularJS together
> // is asynchronous, so the simplest way to solve the problem is with a short delay.
> setTimeout(() => {
> 
>   // Then we find all the tests in the test/js directory.
>   const context = require.context('./js', true, /_?\.?(s|S)pec$/);
>   // and all the tests in the app directory
>   const appContext = require.context('./../src', true, /_?\.?(s|S)pec$/)
> 
>   // load the modules.
>   context.keys().map(context);
>   appContext.keys().map(appContext);
> 
>   // and run the tests.
>   __karma__.start();
> }, 1000);
> ```
> 
> Since the bootstrap is asynchronous, we threw in a 1-second timeout before the tests start to be sure it is finished. Ever since then we did not encounter that race condition.

I'm not here to contribute to the conversation, but I just wanted to thank @AlexSwensen for this. I've been working on upgrading a angular 1.6 app to a hybrid w/ angular 8, and I've had a hell of a time bootstrapping the angularjs tests back in. After a day or two of searching around and playing with things, Alex's suggestion here finally got me somewhere. Thanks so much for sharing!!

Also ++ to suggesting this gets documented in the Upgrade documentation. That documentation is done well, but this is a gap that would certainly be helpful.

**Comment by aryaroudi** [comment]
> > @aryaroudi It's also worth pointing out that when I bootstrapped our tests in karma, I found we would hit a race-condition while angular was bootstrapping.
> > Here is a snippet from our `test.ts` file.
> > ```ts
> > // test/test.ts
> > import * as jquery from 'jquery';
> > declare const window: any;
> > window.$ = jquery;
> > window.jQuery = jquery;
> > 
> > import 'zone.js'
> > import 'zone.js/dist/zone-testing';
> > import 'zone.js/dist/long-stack-trace-zone'
> > // import 'zone.js/dist/proxy.js'
> > import 'zone.js/dist/sync-test'
> > // import 'zone.js/dist/jasmine-patch'
> > // import 'zone.js/dist/async-test'
> > // import 'zone.js/dist/fake-async-test'
> > 
> > declare const __karma__: any;
> > declare const require: any;
> > 
> > __karma__.loaded = function () {};
> > 
> > import '../src/app/main';
> > 
> > // give the app a second to start...
> > // This timeout is needed because the process of bootstrapping Angular and AngularJS together
> > // is asynchronous, so the simplest way to solve the problem is with a short delay.
> > setTimeout(() => {
> > 
> >   // Then we find all the tests in the test/js directory.
> >   const context = require.context('./js', true, /_?\.?(s|S)pec$/);
> >   // and all the tests in the app directory
> >   const appContext = require.context('./../src', true, /_?\.?(s|S)pec$/)
> > 
> >   // load the modules.
> >   context.keys().map(context);
> >   appContext.keys().map(appContext);
> > 
> >   // and run the tests.
> >   __karma__.start();
> > }, 1000);
> > ```
> > 
> > 
> > Since the bootstrap is asynchronous, we threw in a 1-second timeout before the tests start to be sure it is finished. Ever since then we did not encounter that race condition.
> 
> I'm not here to contribute to the conversation, but I just wanted to thank @AlexSwensen for this. I've been working on upgrading a angular 1.6 app to a hybrid w/ angular 8, and I've had a hell of a time bootstrapping the angularjs tests back in. After a day or two of searching around and playing with things, Alex's suggestion here finally got me somewhere. Thanks so much for sharing!!
> 
> Also ++ to suggesting this gets documented in the Upgrade documentation. That documentation is done well, but this is a gap that would certainly be helpful.

Well, What @AlexSwensen mentioned was very helpful for me and I could test it with success BUT remember that there is one issue. You have to modify all your tests after the migration again and if you have like 400-500 tests it's a hell of the work!

**Comment by AlexSwensen** [comment]
@aryaroudi In our current use case, we are in the middle of a large rebrand & rebuild of many features in our application, so for us it makes sense to leave legacy code as-is and rebuild as much as we can in Angular, this includes new tests as well. At that point, it becomes more of a product and process issue than a technical one. The best way to get the work done is to make it a priority for the product/management team. :-)

**Comment by aryaroudi** [comment]
> @aryaroudi In our current use case, we are in the middle of a large rebrand & rebuild of many features in our application, so for us it makes sense to leave legacy code as-is and rebuild as much as we can in Angular, this includes new tests as well. At that point, it becomes more of a product and process issue than a technical one. The best way to get the work done is to make it a priority for the product/management team. :-)
> 
> EDIT: I also should point out that we finally upgraded to Angular 8 and implemented the CLI in our hybrid application. I would suggest teams take the time needed to do this, as in the end, it reduces complexity a lot.

Very valuable point. I realized that we should do the same and move to CLI. Any important point to highlight while migrating from webpack to CLI? If you could share a demo of your config it would be very helpful. Thanks

**Comment by AlexSwensen** [comment]
@aryaroudi I'll put together a demo hopefully soon.
There are a few important points, one is to use strictDi for AngularJS dependencies.
The other is for AngularJS templates you need to use raw-loader as part of the `[require` statement](https://github.com/webpack/docs/wiki/loaders#introduction) if you are trying to load a .html in AngularJS. In Angular the templateUrl property works perfectly fine as-is.

Those two things required me to modify every single AngularJS component we had, along with several state definitions, but once i had that fixed things went very well.

**Comment by ghous92** [comment]
@AlexSwensen  _ Thanks for your input, I was able to bootstrap the Hybrid App. To Add on I have changed my .js spec files into .ts in order to utilize ES6

**Comment by Camo30** [comment]
> I'll put together a demo hopefully soon.

@AlexSwensen Any news about this? I am very interested in a runnable demo as I'm stuck with it

**Comment by AlexSwensen** [comment]
@Camo30 Very sorry I haven't checked back in. My project ran into some difficulty and (to put a long story short) my team and I are all looking for new work. 😅
If I ever get back into this space I am happy to build up a demo. In the meantime, I took most of my tips from this repo. https://github.com/ui-router/sample-app-angular-hybrid

In addition, if anyone wants some assistance I also take offers for consulting. 😉

**Comment by JeanMeche** [comment]
We'll let the community provide info around this topic since angular.dev doesn't cover angularjs anymore.
