### ISSUE TITLE
In test.unit.dart has high latency because Karma takes long time to serve context.html

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#2437]
We are spending about 21s (on my MBP) somewhere between kicking off the test run and tests actually running.

I tried to debug this a bit and here is what I found:
- dartium's timeline confirms the time is spent in fetching context.html
- deducing from Karma's log, it looks like the time is spent in watcher or rather karma-dart's adapter that generates the list of files to serve.

To repro:
- run `gulp test.unit.dart`
- in separate terminal run `touch modules/angular2/src/di/injector.ts`

cc: @pkozlowski-opensource @tbosch

**Comment by IgorMinar** [comment]
@zzo / @juliemr could you take a look at this one please?

**Comment by zzo** [comment]
sure looking...

**Comment by zzo** [comment]
This issue is this:
https://github.com/isaacs/node-glob/issues/78
karma is using an old version of glob whose async performance is bad.  Just using glob.sync instead increases performance 2x with the same version of glob.  
Using the latest version of glob performance is order of magnitude improved.
Hope to have a fix one way or another soon.

**Comment by caitp** [comment]
A quick grep:

```shell
$ grep "glob(" -r node_modules/ --exclude-dir=glob | grep broc | grep '\.js'
node_modules//broccoli/node_modules/rimraf/rimraf.js:    glob(p, globOpts, afterGlob)
node_modules//broccoli-funnel/node_modules/broccoli-read-compat/node_modules/rimraf/rimraf.js:    glob(p, globOpts, afterGlob)
node_modules//broccoli-stew/node_modules/broccoli-funnel/node_modules/rimraf/rimraf.js:    glob(p, globOpts, afterGlob)
node_modules//broccoli-stew/node_modules/fs-extra/node_modules/rimraf/rimraf.js:    glob(p, globOpts, afterGlob)
```

It doesn't look like any of the angular build tools are using async glob directly

**Comment by IgorMinar** [comment]
@caitp, it's used by karma's dart plugin.

**Comment by zzo** [comment]
it's coming from karma which uses (an older version) of glob.  This is about karma taking a long time to run/re-run tests - glob is globbing over 4k files and it's taking a long time.

**Comment by zzo** [comment]
fwiw it's karma itself that's doing the globbing and taking a long time not the dart plugin - since we're using Dartium no dart2js is happening so the dart plugin isn't doing anything expensive in this case.

**Comment by IgorMinar** [comment]
really? then I would expect the issue to affect the js tests as well. There
is a small delay, in js, but it's nowhere as significant as the dart. Is it
because the dart dist tree contains many more files?

**Comment by pkozlowski-opensource** [comment]
Hmm, looking at the analysis pointing to node-glob as a culprit, I wonder why we start to see this issue only now, after migration to Brocolli. It used to be very fast with the Gulp-based build.

**Comment by zzo** [comment]
Back in the old pre-broccoli days karma watched the filesystem itself so it did not have do run full globs.  Now with broccoli watching the fs - karma gets kicked off fresh for every file change so it must glob over the entire fs each time looking for files (and there are a lot of them).

**Comment by pkozlowski-opensource** [comment]
Oh, I didn't realise that now we've got broccoli _and_ Karma doing the watching... I guess it was done like this to have only one thing in charge of the build, right? Instead of having a separate broccoli and Karma adapter? Hm, but then again, why don't we see the same pb in JS?

**Comment by zzo** [comment]
karma is no longer doing any watching - only broccoli.  When broccoli detects a change it kicks off a single run from karma.
Haven't looked at the JS stuff yet so don't know about that - will take a look

**Comment by IgorMinar** [comment]
This started happening only recently. I wonder if it's because of the
generated files that we now have in dart. Maybe part of the solution would
be to make the file patterns more restrictive so that karma doesn't need to
do so much work?

Also, the build could generate a list of changed files so that karma can
use those to figure out which paths to invalidate. But as far as I know,
when we run in dartium the http caching is disabled because the file urls
can't be amended with versioning info.

**Comment by zzo** [comment]
Ok some bad news - the newer globs don't automatically follow symlinks so they were running much faster :)
So using the latest 'glob' and using sync vs. async glob'ing the we get from ~30 seconds currently to ~20 seconds - faster but not instantaneous.
The heavy hitter is this pattern in karma-dart conf: 'dist/dart/**' which matches ~82k files and takes about 8 seconds just for the glob. 
So yes any way we can make that list of files smaller will help.

**Comment by zzo** [comment]
ok got it down to 20 sec (from 30) with the latest karma - now we need some surgery on the dart karma config to not glob 80k+ files.  Once my karma changes get to npm (as a canary release) - I'll send a PR.
The JS unit tests take about 6 seconds and 'only' glob about 2000 files.

**Comment by pkozlowski-opensource** [comment]
80k files for Dart sounds like a lot... Are we ending up with such huge no of files because of transformers? Or is it about globbing all pub dependencies? 

In any case the current unit-testing workflow for Dart is pretty much broken :-(

**Comment by zzo** [comment]
INFO [watcher]: Pattern "/Users/trostler/angular/dist/dart/**" matches 82403.

So the bulk of them by far are here:

trostler-macbookair2:test trostler$ find -L /Users/trostler/angular/dist/dart/angular2/test  | wc -l
   80903

With the 'transform' directory being the big winner:

trostler-macbookair2:test trostler$ find -L /Users/trostler/angular/dist/dart/angular2/test/transform/  | wc -l
   53390

**Comment by naomiblack** [comment]
Checking in on this one... @caitp is out this week. Is anyone working on it in alpha-29, or should it slip to alpha-30? @IgorMinar can you clarify whether this is still P1?

**Comment by zzo** [comment]
Another option while we're still readying the karma 1.0 release - the latest dart sdk has a test runner built in - have you given that a shot?

**Comment by IgorMinar** [comment]
just running `find dist/dart/angular2/test/ -name packages | xargs rm -r` reduces the latency from 26 seconds down to 6 seconds.

Some of these files are needed for the transformer to work, but once the transformers run, we don't need them. Also what I see is that every subdirectory under `dist/dart/angular2/` contains `packages` directory that that links to main `packages` directory in the root. This seems pretty excessive. These links are generated by `pub get`. Anyone knows why? @yjbanov?

**Comment by pkozlowski-opensource** [comment]
Thnx so much @IgorMinar and @zzo !!! Just tested this locally and it cuts down re-run delay from ~30 secs to ~2 secs! Awesome, thank you!

**Comment by IgorMinar** [comment]
there was an issue with this change. I'm working on an alternative solution.

**Comment by zzo** [comment]
Sweet
