### ISSUE TITLE
angular6 about <img> Not Found

### ISSUE THREAD

**Issue by z3214965** [angular/angular#24389]
![default](https://user-images.githubusercontent.com/18589356/41188776-5aed9900-6bf5-11e8-997c-b4e811022e8e.PNG)
![1](https://user-images.githubusercontent.com/18589356/41188771-471c0268-6bf5-11e8-92ee-b2af5e10ae07.PNG)
![2](https://user-images.githubusercontent.com/18589356/41188775-51225988-6bf5-11e8-8ddf-d8333371ac17.PNG)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by z3214965** [comment]
I have a new project, still have this problem，In addition to the above, other settings are not required？

**Comment by trotyl** [comment]
@z3214965 It's not related to this repo, please report [Angular CLI](https://github.com/angular/angular-cli) issue to its own repo, and also **follow the contribution guide there**.

**Comment by z3214965** [comment]
I know，thank you
