### ISSUE TITLE
Angular 6 HttpClient OPTIONS request "pending" when response code is not 204. 

### ISSUE THREAD

**Issue by nealhamilton** [angular/angular#24383]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[] Other... Please describe: 
</code></pre>

## Current behavior

After upgrading a large application to angular 6.0.3, our application started failing to make HTTP requests from our services.  We have a JWT Interceptor that modifies headers and places the "Authorization Bearer {token}" header on our requests.  If the OPTIONS request doesn't respond with a 204, and rather response with a 200, we are seeing all requests in a state of "pending" for eternity.  There is no failure of the request, it is simply pending.

## Expected behavior
Some sort of error message, or failure of that request to surface after a timeout period.  

## Minimal reproduction of the problem with instructions
HttpClient requests an endpoint with OPTIONS that does NOT return a 204, and instead returns a 200.
Check network tab of Google Chrome, and wait.. and wait.. and wait.  
No errors or timeouts will surface. 

## What is the motivation / use case for changing the behavior?
More description allowing developers to track down an issue, considering this seems to have been introduced in either angular 4.4, 5, or 6. Although that is hard to tell where it was introduced. 

## Environment
macOS High Sierra 10.13.5

Angular version: 6.0.3

Browser:
- [ X] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [ X] Firefox version XX
- [ X] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [X ] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:
While this was obviously a blunder on our part, and now we are making the changes in the api to fix this, this was clearly something that changed in the HttpClient after 4.3 without any obvious communication of said change that I could see. We have a version of our code running in our UAT environment on 4.3.X and in our Local/Development environment it's running 6.0.3, with nothing else changed it works on 4.3.x but not 6.0.3 which leads me to believe this should be documented or give more description of this case.  

Thanks for all your hard work on angular.

**Comment by splincode** [comment]
It is normal that the server gives you the status of 200

![image](https://user-images.githubusercontent.com/12021443/41188404-25cc03ae-6bc5-11e8-8f1a-974b91627d36.png)

**Comment by trotyl** [comment]
What you reported is **NOT** possible as OPTIONS request/response never exposed via XHR API, it's totally transparent to any JavaScript code.

If anything works wrong with OPTIONS, you should report that to browser (but make sure you read the spec first).

**Comment by alxhub** [comment]
@trotyl and @splincode are correct - this is an issue with your CORS setup and not with Angular. `OPTIONS` and CORS in general are transparent to `HttpClient`, we're unaware of its operation.
