### ISSUE TITLE
provide more cues for deprecated APIs 

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#24380]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ X] Other... Please describe:  info arch (content access) and AIO infra
</code></pre>

## Current behavior

1. Search results: If I search for "http", the search results include (and sometimes favor) the deprecated APIs. This is good, because search should provide complete results. This is not so good, because it can result in 4 steps instead of 2 steps to find the current API:

- Search for http
- Pick "http" from search results
- Discover that it's deprecated, so it's probably not what I want
- Click link to replacement API

![deprecated-http-search](https://user-images.githubusercontent.com/31675481/41174499-93c06c46-6b17-11e8-9b0e-de2f99ded632.png)

2. API landing page: If I am on the API landing page, all APIs are shown without a status indicator. I can filter for only stable, only experimental, or only deprecated, but without filtering I can't tell which ones are deprecated. Sometimes the deprecated API is higher in the index or a better match for my keyword, which means I'm likely to have extra clicks:

- Go to API index
- Type "http" into search field. 
- Choose "http"
- Find out that it's' deprecated. Follow link to replacement API

![deprecated-http-api-index](https://user-images.githubusercontent.com/31675481/41174687-131cff04-6b18-11e8-988f-4291ca9680e2.png)

3. Module page: No indicator if module is deprecated
https://angular.io/api/http
![deprecated-http-module](https://user-images.githubusercontent.com/31675481/41174700-1f473f10-6b18-11e8-9f77-a848d01cf5cd.png)

## Expected behavior

1. It might be useful to append status to APIs in the search results for APIs that are not stable, like this: 

http (deprecated)
animations (experimental)
http client

Or shorthand that users can learn easily

http (dep)(old?)
animations (exp)
http client

And/or filter search results automatically to put stable APIs at the top of the results. 

2. Similar to #1, append status to API names in the list, and/or offer a filter that excludes deprecated (so I can see stable + experimental together, which is everything I should consider for possible future direction). 

3. Add "deprecated" badge to deprecated packages, as mocked up in image above. 

## Minimal reproduction of the problem with instructions

See above. 

## What is the motivation / use case for changing the behavior?

Reduce navigation "noise" and extra steps for developers. Make non-deprecated APIs more prominent in navigation paths. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
@jbogarthyde @petebacondarwin @brandonroberts FYI

**Comment by jenniferfell** [comment]
Related issue regarding package overview pages showing what's deprecated: https://github.com/angular/angular/issues/25721

**Comment by jenniferfell** [comment]
Re deprecated badge, we'd like to switch to red/orange colors for deprecated, security risk badges (and not use those colors for types ideally) so they show up similar to a warning or caution

**Comment by petebacondarwin** [comment]
I have added some commits to https://github.com/angular/angular/pull/25750 to help with this.
