### ISSUE TITLE
DatePipe does not Round 99.5 to 99.9 Milliseconds correctly

### ISSUE THREAD

**Issue by jmgrill** [angular/angular#24384]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The angular date pipe rounds the milisecond portion of the format without allowing a round upward from 99 to 100 to increase the the value in the second's position, producing both the wrong value and the wrong number of digits in the formatted output.

{{3999 | date:'m:ss.SS'}}   ---->  0:03.100

reproduced here:
https://stackblitz.com/edit/angular-nc4d3n?file=src%2Fapp%2Fapp.component.html

## Expected behavior

{{3999 | date:'m:ss'}} ----> 0:03
{{3999 | date:'m:ss.S'}} ----> 0:03.9
{{3999 | date:'m:ss.SS'}} ----> 0:03.99
{{3999 | date:'m:ss.SSS'}} ----> 0:03.999
_(edit by vicb)_

## Minimal reproduction of the problem with instructions
{{3999 | date:'m:ss.SS'}}   ---->  0:03.100

reproduced here:
https://stackblitz.com/edit/angular-nc4d3n?file=src%2Fapp%2Fapp.component.html

## What is the motivation / use case for changing the behavior?
The date pipe does not format timestamps correctly, which is something that I'd imagine plenty of people want to use it for.

**Comment by dawidgarus** [comment]
Although 0:03.100 is wrong, `DatePipe` should be used to display date, not time intervals and in my opinion it should not be rounded. For example, `2018-06-08T23:59:59.999` should not be rounded to `2018-06-09T00:00:00.00` in any circumstance.

**Comment by dominikg** [comment]
imho the expected behavior should be

{{3999 | date:'m:ss'}} ----> 0:03
{{3999 | date:'m:ss.S'}} ----> 0:03.9
{{3999 | date:'m:ss.SS'}} ----> 0:03.99
{{3999 | date:'m:ss.SSS'}} ----> 0:03.999

**Comment by jmgrill** [comment]
I agree with both comments above.
