### ISSUE TITLE
ActivatedRoute does not update on navigation.

### ISSUE THREAD

**Issue by pathurs** [angular/angular#24399]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The `ActivatedRoute`'s snapshot is always the root snapshot.

## Expected behavior

The `ActivatedRoute`'s snapshot should be the current route's snapshot.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-rakecj

Click the buttons 'A', 'B', 'C', 'D', or 'E' to change to a different route.

Information shown below buttons.

## What is the motivation / use case for changing the behavior?

-

## Environment

<pre><code>
Angular version: 6.0.5

Browser:
- [ X] Chrome (desktop) version 61
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.3.0  
- Platform:  Windows 
</code></pre>

Similar to #19420

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/11812

It's not about updating, but scoping. Angular router is hierarchical, a component can only get route information belongs to its subtree.

As `data: { name:'aa' }` is defined in `AComponent`'s route, only `AComponent` and its descendant have access to it.

**Comment by pathurs** [comment]
@trotyl is this explained in the docs? I've not read this.

**Comment by trotyl** [comment]
@pathurs Yes, it's explained in [the properties table](https://angular.io/api/router/ActivatedRoute#properties) whether some property is shared (`all routes`) or scoped (`this route`).

**Comment by pathurs** [comment]
Looks like the ActivatedRoute provider needs more documentation, but I can see your answer working.

Thank you @trotyl
