### ISSUE TITLE
Nested Angular elements with ViewEncapsulation.Native don't work as expected

### ISSUE THREAD

**Issue by JenPeleva** [angular/angular#24397]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently, if you have nested angular elements with ViewEncapsulation.Native, you get the following error: 
`ERROR DOMException: Failed to execute 'createShadowRoot' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree.`

## Expected behavior
To work without an error.

## Minimal reproduction of the problem with instructions

Reproducible here: https://stackblitz.com/edit/angular-944bgm
I have two custom elements - <custom-button> and <custom-container>. <custom-button> is used in the template of the container, which leads to the error.

I tried using ViewEncapsulation.Emulated as a workaround, which led to another unpredictable result: https://stackblitz.com/edit/angular-qvf79y  
The button from the template of the <custom-button> gets duplicated.

## What is the motivation / use case for changing the behavior?
It's a pretty common scenario.

## Environment

<pre><code>
Angular version: 6.0.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [x] Chrome (iOS) version 66.0.3359.181
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

Thanks!

**Comment by robwormald** [comment]
Hi @JenPeleva - thanks for the 👍 issue report.

The main issue with your demo is that because you have all the components in the same NgModule, Angular has those components registered - so when Angular stamps out the `<custom-button>` element, you end up with two instances of the component - one created by the AppComponent, and one created by the Custom Element - so there's a conflict as they both try to add a shadow root. 

Two ways around this - you can either put each element in its own NgModule, and bootstrap them separately, or just remove the `selector` entirely from the @Component definition - which will prevent Angular from double bootstrapping. You'll also need to add the `CUSTOM_ELEMENTS_SCHEMA` to the `schemas: []` array on any NgModule where you want to use any custom element from an Angular template.

Here's a working version: https://stackblitz.com/edit/angular-e4zxmm?file=src%2Fapp%2Fapp.component.html

The other thing (which isn't directly related to your issue, but as I was fixing your demo i fixed it too) is related to content projection: you can use `ng-content`, but its limited in Custom Elements - for real flexibility you'll want to use Shadow DOM and Slots - see https://developers.google.com/web/fundamentals/web-components/shadowdom - unfortunately the current `ViewEncapsulation.Native` uses the older version of Shadow DOM (which uses `<content>` elements to do the same thing) - that demo also adds a hack to enable Shadow DOM V1 if you want to experiment with slots.

**Comment by njl07** [comment]
using shadow dom v1 works for me on Safari now

**Comment by njl07** [comment]
I've published the [renderer](https://www.npmjs.com/package/@hapiness/ng-shadow-dom-renderer) to have it for all people until it's fix in the core

**Comment by njl07** [comment]
@robwormald when using your renderer with shadom dom v1:

```typescript
import { Renderer2, RendererFactory2, RendererStyleFlags2, RendererType2, ViewEncapsulation } from '@angular/core';
import {
    EventManager,
    ɵDomRendererFactory2 as DomRendererFactory2,
    ɵDomSharedStylesHost as DomSharedStylesHost,
    ɵflattenStyles as flattenStyles,
    ɵNAMESPACE_URIS as NAMESPACE_URIS
} from '@angular/platform-browser';

// HACK: this uses the shadow DOM V1 spec until we fix it in core
// https://github.com/angular/angular/issues/24397

export class ShadowDomV1Renderer implements Renderer2 {
    shadowRoot: ShadowRoot | undefined;
    data: { [ key: string ]: any } = Object.create(null);
    destroyNode: null;
    readonly abstract;

    constructor(
        private eventManager: EventManager, private sharedStylesHost: DomSharedStylesHost,
        private hostEl: any, private component: RendererType2) {

        this.shadowRoot = (hostEl as HTMLElement).attachShadow({ mode: 'open' });
        this.sharedStylesHost.addHost(this.shadowRoot);
        const styles = flattenStyles(component.id, component.styles, []);
        for (let i = 0; i < styles.length; i++) {
            const styleEl = document.createElement('style');
            styleEl.textContent = styles[ i ];
            this.shadowRoot.appendChild(styleEl);
        }
    }

    destroy() {
        this.sharedStylesHost.removeHost(this.shadowRoot);
    }

    private nodeOrShadowRoot(node: any): any {
        return node === this.hostEl ? this.shadowRoot : node;
    }

    createElement(name: string, namespace?: string): any {
        if (namespace) {
            return document.createElementNS(NAMESPACE_URIS[ namespace ], name);
        }

        return document.createElement(name);
    }

    createComment(value: string): any {
        return document.createComment(value);
    }

    createText(value: string): any {
        return document.createTextNode(value);
    }

    appendChild(parent: any, newChild: any): void {
        this.nodeOrShadowRoot(parent).appendChild(newChild);
    }

    insertBefore(parent: any, newChild: any, refChild: any): void {
        if (parent) {
            this.nodeOrShadowRoot(parent).insertBefore(newChild, refChild);
        }
    }

    removeChild(parent: any, oldChild: any): void {
        if (parent) {
            this.nodeOrShadowRoot(parent).removeChild(oldChild);
        }
    }

    selectRootElement(selectorOrNode: string | any): any {
        const el: any = typeof selectorOrNode === 'string' ?
            document.querySelector(selectorOrNode) :
            selectorOrNode;
        if (!el) {
            throw new Error(`The selector "${selectorOrNode}" did not match any elements`);
        }
        return el;
    }

    parentNode(node: any): any {
        return this.nodeOrShadowRoot(node.parentNode);
    }

    nextSibling(node: any): any {
        return node.nextSibling;
    }

    setAttribute(el: any, name: string, value: string, namespace?: string): void {
        if (namespace) {
            name = `${namespace}:${name}`;
            const namespaceUri = NAMESPACE_URIS[ namespace ];
            if (namespaceUri) {
                el.setAttributeNS(namespaceUri, name, value);
            } else {
                el.setAttribute(name, value);
            }
        } else {
            el.setAttribute(name, value);
        }
    }

    removeAttribute(el: any, name: string, namespace?: string): void {
        if (namespace) {
            const namespaceUri = NAMESPACE_URIS[ namespace ];
            if (namespaceUri) {
                el.removeAttributeNS(namespaceUri, name);
            } else {
                el.removeAttribute(`${namespace}:${name}`);
            }
        } else {
            el.removeAttribute(name);
        }
    }

    addClass(el: any, name: string): void {
        el.classList.add(name);
    }

    removeClass(el: any, name: string): void {
        el.classList.remove(name);
    }

    setStyle(el: any, style: string, value: any, flags: RendererStyleFlags2): void {
        if (flags & RendererStyleFlags2.DashCase) {
            el.style.setProperty(
                style, value, !!(flags & RendererStyleFlags2.Important) ? 'important' : '');
        } else {
            el.style[ style ] = value;
        }
    }

    removeStyle(el: any, style: string, flags: RendererStyleFlags2): void {
        if (flags & RendererStyleFlags2.DashCase) {
            el.style.removeProperty(style);
        } else {
            // IE requires '' instead of null
            // see https://github.com/angular/angular/issues/7916
            el.style[ style ] = '';
        }
    }

    setProperty(el: any, name: string, value: any): void {
        checkNoSyntheticProp(name, 'property');
        el[ name ] = value;
    }

    setValue(node: any, value: string): void {
        node.nodeValue = value;
    }

    listen(target: 'window' | 'document' | 'body' | any, event: string, callback: (event: any) => boolean):
        () => void {
        checkNoSyntheticProp(event, 'listener');
        if (typeof target === 'string') {
            return <() => void>this.eventManager.addGlobalEventListener(
                target, event, decoratePreventDefault(callback));
        }
        return <() => void>this.eventManager.addEventListener(
            target, event, decoratePreventDefault(callback)) as() => void;
    }
}

function decoratePreventDefault(eventHandler: Function): Function {
    return (event: any) => {
        const allowDefaultBehavior = eventHandler(event);
        if (allowDefaultBehavior === false) {
            event.preventDefault();
            event.returnValue = false;
        }
    };
}

function checkNoSyntheticProp(name: string, nameKind: string) {
    if (name.charCodeAt(0) === '@'.charCodeAt(0)) {
        throw new Error(
`Found the synthetic ${nameKind} ${name}. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.`
        );
    }
}

export function overrideRenderFactory() {
    return [ {
        provide: RendererFactory2, useFactory(renderFactory: RendererFactory2, sharedStylesHost, eventManager) {
            return {
                createRenderer(host, renderType: RendererType2) {

                    if (renderType && renderType.encapsulation === ViewEncapsulation.Native) {
                        return new ShadowDomV1Renderer(eventManager, sharedStylesHost, host, renderType);
                    }
                    return renderFactory.createRenderer(host, renderType);
                }
            };
        }, deps: [ DomRendererFactory2, DomSharedStylesHost, EventManager ]
    } ];
}
```

 it works fine with only one component but when my component has another component inside, `this.shadowRoot = (hostEl as HTMLElement).attachShadow({ mode: 'open' });` failed in `DebugRendererFactory2.push`.

More, in SSR with `universal` this factory failed when back in browser with error in this execution `renderFactory.createRenderer(host, renderType)`. `DomRendererFactory2` is not provided.

How to solve all or when shadom v1 will be released inside `core`?

Thanks for all.

**Comment by maxtacco** [comment]
This example helped me to bootstrap nested Angular elements: https://stackblitz.com/edit/nesting-angular-elements-example

**Comment by raulrios** [comment]
I faced similar problem and the only thnig that worked for me was changing encapsulation from Native to Emulated.
