### ISSUE TITLE
Background image url containing spaces doesn't work with [ngStyle]

### ISSUE THREAD

**Issue by LoveenDyall** [angular/angular#24395]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

&lt;div [ngStyle]="{'background-image': 'url(' + '/assets/posters/5b1be6729d9ef62eb658489d Sat Jun 09 2018.jpeg' + ')'}"&gt;
When file name contains spaces, the background image doesn't display. Removal of spaces in url provided and image filename works successfully.

## Expected behavior

Background image should show

## Environment

<pre><code>
"@angular/animations": "^6.0.4",
"@angular/common": "^6.0.4",
"@angular/compiler": "^6.0.4",
"@angular/core": "^6.0.4",
"@angular/forms": "^6.0.4",
"@angular/http": "^6.0.4",
"@angular/platform-browser": "^6.0.4",
"@angular/platform-browser-dynamic": "^6.0.4",
"@angular/router": "^6.0.4",

Angular CLI version: ^6.0.7

Browser:
- [x] Chrome (desktop) version 66
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version 11.1
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

MAMP 4.3
</code></pre>

**Comment by trotyl** [comment]
Space is [not allowed](https://tools.ietf.org/html/rfc3986#section-2.3) in URL.

You can get the valid URL by running:

```javascript
encodeURI('/assets/posters/5b1be6729d9ef62eb658489d Sat Jun 09 2018.jpeg')
```

**Comment by ericmartinezr** [comment]
Aditional to @trotyl's answer: https://stackoverflow.com/a/2405359/4933038

<hr>

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by bithinbrainium** [comment]
Try this one. 
=================
<div class="img-cntrl"  [ngStyle]="{'background-image': 'url(&quot;' +  baseUrl+ project?.bannerImg?.url + '&quot;)'}"></div>
=================
This one works fine for me

**Comment by bithinbrainium** [comment]
Try this one. 
=================
`<div class="img-cntrl"  [ngStyle]="{'background-image': 'url(&quot;' +  baseUrl+ project?.bannerImg?.url + '&quot;)'}"></div>`
=================
This one works fine for me

**Comment by SoftronetBithin** [comment]
Try this
`<div class="img-cntrl"  [ngStyle]="{'background-image': 'url(&quot;' +  baseUrl+ project?.bannerImg?.url + '&quot;)'}"></div>`

This one works for me
