### ISSUE TITLE
Proposal: Accessing named elements from a template

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2439]
If I create the following directive:

```dart
@Directive(
  properties: const ['source']
)
class PopupDirective {
  void set source(ElementRef elementRef) {
    // Do something, like using the ruler to meaure
  }
}
```

I might want to refer to other elements in my template:

```html
<div>
  <button #save>Save</button>
  <popup [source]="save"></popup>
</div>
```

Right now this is not possible. @tbosch mentioned that a workaround for now would be creating a directive, e.g., export-element, that would [work like this](https://github.com/angular/angular/blob/master/modules/angular2/test/core/compiler/integration_spec.ts#L442).

**Comment by mhevery** [comment]
per discussion with @matanlurey  works as intended. No action.
