### ISSUE TITLE
ngtools_api2 `program.emit` still emits files when having `noEmitOnError`

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#24398]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When using `program.emit()` in `ngtools api2` togather with `noEmitOnError` and having a clear typescript error, files are still emitted.

## Expected behavior
That files are not emitted when using `noEmitOnError`.

## Minimal reproduction of the problem with instructions
https://github.com/alan-agius4/angular-issue-24398-no-emit
## What is the motivation / use case for changing the behavior?
noEmitOnErrors should be honoured 

## Environment

<pre><code>
Angular version: 6.0.4
</code></pre>

**Comment by filipesilva** [comment]
As a minor clarification, `noEmitOnError` is a TypeScript compiler option that says:
> Do not emit outputs if any errors were reported.

It can be found listed in https://www.typescriptlang.org/docs/handbook/compiler-options.html

I believe what @alan-agius4 means is that the option should be honored by `ngc` when present in the provided `tsconfig.json` file.

**Comment by alan-agius4** [comment]
That’s correct @filipesilva. That’s what I meant.

**Comment by JoostK** [comment]
This is still an issue in ngtsc. The reason is that ngtsc emits files individually, so the `noEmitOnError` flag is also considered per individual file instead of the full compilation.

**Comment by alxhub** [comment]
Closing as no longer relevant - the CLI no longer uses `noEmitOnError`
