### ISSUE TITLE
TypeError stopImmediatePropagation platform-browser

### ISSUE THREAD

**Issue by LucianoDiPierno** [angular/angular#24407]
## I'm submitting a...
<pre><code>
[x] Bug report 
</code></pre>

## Current behavior
After upgrading @angular/platform-browser (and others @angular/xxx) to versione 6.0.4, i've this error at startup and after page reload:

NodeInvocationException: Cannot assign to read only property 'stopImmediatePropagation' of object '[object Object]'
TypeError: Cannot assign to read only property 'stopImmediatePropagation' of object '[object Object]'
at DomEventsPlugin.module.exports../node_modules/@angular/platform-browser/bundles/platform-browser.umd.js.DomEventsPlugin.patchEvent (I:\Progetti\Platform\Software\CTAgenda\ClientApp\dist\vendor.js:60044:50)
at new DomEventsPlugin (I:\Progetti\Platform\Software\CTAgenda\ClientApp\dist\vendor.js:60031:15)
at eval (ng:///AppModule/module.ngfactory.js:51:25)
at _callFactory (I:\Progetti\Platform\Software\CTAgenda\ClientApp\dist\vendor.js:40373:28)
at _createProviderInstance$1 (I:\Progetti\Platform\Software\CTAgenda\ClientApp\dist\vendor.js:40319:26)
at resolveNgModuleDep (I:\Progetti\Platform\Software\CTAgenda\ClientApp\dist\vendor.js:40282:21)
at _createClass (I:\Progetti\Platform\Software\CTAgenda\ClientApp\dist\vendor.js:40346:29)
at _createProviderInstance$1 (I:\Progetti\Platform\Software\CTAgenda\ClientApp\dist\vendor.js:40316:26)
at resolveNgModuleDep (I:\Progetti\Platform\Software\CTAgenda\ClientApp\dist\vendor.js:40282:21)
at _createClass (I:\Progetti\Platform\Software\CTAgenda\ClientApp\dist\vendor.js:40352:32)

## Expected behavior
No error at startup

## Environment
<pre><code>
Angular version: 6.0.4
@angular/cli: 6.0.8
aspnet-prerendering: 3.0.1
aspnet-webpack: 3.0.0
Webpack: 4.12.0

Browser:
- [x] Chrome (desktop) version XX
</code></pre>

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by SaidMarar** [comment]
i have the error at first load but after reload it disapears !!!

**Comment by LucianoDiPierno** [comment]
@mhevery  Ok thanks, here is the link to stackoverflow: [https://stackoverflow.com/questions/50813457/cannot-assign-to-read-only-property-stopimmediatepropagation-of-object](url)

However, please note that the problem occurred after updating to the latest version of Angular (previously i already had version 6 installed).

Thanks again

**Comment by SaidMarar** [comment]
@LucianoDiPierno did you resolve the problem ? if not please tell me the version that does not has this issue i am going to downgrade

**Comment by SaidMarar** [comment]
10 days ago and none provide support ! thats why having less stars !!!

**Comment by ilDon** [comment]
This should be reopened as it is a bug that could be easily fixed. In `packages/platform-browser/src/dom/events/dom_events.ts` change:

    Event.prototype.stopImmediatePropagation = function() {

to

    Event.prototype[stopMethodSymbol] = function () {

**Comment by JiaLiPassion** [comment]
@LucianoDiPierno, @SaidMarar, @ilDon, could you provide a reproduce repo? And which version of `chrome` for testing?

**Comment by ilDon** [comment]
Actually I've updated all my packages to the latest versions and now the error does not appear anymore. My package.json is:

    "@angular/animations": "^6.0.7",
    "@angular/common": "^6.0.7",
    "@angular/compiler": "^6.0.7",
    "@angular/core": "^6.0.7",
    "@angular/forms": "^6.0.7",
    "@angular/http": "^6.0.7",
    "@angular/platform-browser": "^6.0.7",
    "@angular/platform-browser-dynamic": "^6.0.7",
    "@angular/platform-server": "^6.0.7",
    "@angular/router": "^6.0.7",
    "@nguniversal/express-engine": "^6.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^6.0.0",
    "bootstrap": "^4.1.1",
    "core-js": "^2.5.4",
    "fs-extra": "^6.0.1",
    "rxjs": "^6.2.1",
    "rxjs-compat": "^6.2.0",
    "spider-detector": "^1.0.18",
    "ts-loader": "^4.4.2",
    "zone.js": "^0.8.26"

**Comment by LucianoDiPierno** [comment]
@JiaLiPassion I spent a lot of time trying to figure out precisely at what point the problem occurs. I started from a working version, updating one component at a time, and regenerating the files every time through the webpack, but i could not define the precise moment in which the problem started to occur. However the chrome version is 67.0.3396.99

**Comment by JiaLiPassion** [comment]
@LucianoDiPierno, @ilDon, @LucianoDiPierno, thank you for the information, if there is a reproduce repo, I can help to find the reason.

**Comment by vikicoder007** [comment]
![image](https://user-images.githubusercontent.com/29039389/44622701-73dd7e80-a8db-11e8-9734-92622e9ee007.png)

i am having the same issue how to solve this please help 

before update all was rendering from server but after i update there is console error 

also setMeta is working from client side not from server side

**Comment by JiaLiPassion** [comment]
@vikicoder007, could you provide a reproduce repo? thanks.
