### ISSUE TITLE
port 4200 is already in use. use '--port' to specify a different port.

### ISSUE THREAD

**Issue by webengers** [angular/angular#24408]
port 4200 is already in use. use '--port' to specify a different port.

here i will change the  --port number following command

$ ng serve --port 123
** Angular Live Development Server is listening on localhost:123, open your browser on http://localhost:123/ **

here i will click this link  the site This site can’t be reached error msg will be display
what are the problem is 

$ ng serve --open --port=123
** Angular Live Development Server is listening on localhost:123, open your browser on http://localhost:123/ **
this type also running not working 
 and close all the active connections and restart the connection also 

plz help me 
![1](https://user-images.githubusercontent.com/28916605/41221150-f2414090-6d80-11e8-8a59-17da46800e86.png)
![2](https://user-images.githubusercontent.com/28916605/41221151-f26ea40e-6d80-11e8-9a52-3f70a0d20fbc.png)
![3](https://user-images.githubusercontent.com/28916605/41221152-f29b6b10-6d80-11e8-9b13-12cfaf21dab0.png)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
