### ISSUE TITLE
RouterLinkActive scroll to visible

### ISSUE THREAD

**Issue by YZahringer** [angular/angular#24404]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
RouterLinkActive not visible on long List without scroll.

## Expected behavior
Make a RouterLinkActive visible, scroll if needed on long List for example.

## What is the motivation / use case for changing the behavior?
RouterLinkActive not visible on long List or Table until you scroll on element.

## Environment
Angular version: 6.0.4

## Others:
Current temp workaround:
```ts
import { Directive, AfterContentInit, OnDestroy, ElementRef, ContentChild } from '@angular/core';
import { Router, RouterLinkActive, NavigationEnd } from '@angular/router';
import { Subscription } from 'rxjs';
import { filter } from 'rxjs/operators';

@Directive({
  selector: '[routerLinkActiveVisible]'
})
export class RouterLinkActiveVisibleDirective implements AfterContentInit, OnDestroy {
  private readonly subscription: Subscription;

  @ContentChild(RouterLinkActive) private link: RouterLinkActive;
  
  constructor(
    private readonly elementRef: ElementRef,
    private readonly router: Router) {
    this.subscription = this.router.events.pipe(
        filter(e => e instanceof NavigationEnd))
      .subscribe(
        () => {
          this.updateScroll();
        });
  }

  ngAfterContentInit(): void {
    this.updateScroll();
  }

  ngOnDestroy() {
    this.subscription.unsubscribe();
  }

  private updateScroll() {
    if (!this.link || !this.link.links || !this.link.linksWithHrefs || !this.router.navigated)
      return;

    const isActive = (this.link as any).hasActiveLinks(); // TODO Fix this HACK
    if (isActive) {
      this.elementRef.nativeElement["scrollIntoViewIfNeeded"]();
    }
  }
}
```

**Comment by jasonaden** [comment]
Scrolling is coming in `6.1.0`. Here's the PR implementing it. If this doesn't exactly suit the need, you should create a custom `RouterScroller`, as covered [here](https://github.com/angular/angular/pull/20030#issuecomment-360204934) and [here](https://github.com/angular/angular/pull/20030#discussion_r177884426).
