### ISSUE TITLE
Module export and import

### ISSUE THREAD

**Issue by exotfboy** [angular/angular#24400]
Sounds like there are two kinds of `import/export` when using angular through [this post](https://stackoverflow.com/a/41927063/306719).

> In ES6/TypeScript:
> - A module is any code file in your project.
> - An import is a line starting with the import keyword.
> - An export is a line starting with the export keyword.
> 
> In Angular:
> - A module is a class decorated with @NgModule. It serves as a registry (aka container) for all the components, pipes, directives and providers in your application.
> - An import is what you put in the imports property of the @NgModule decorator. It enables an Angular module to use functionality that was defined in another Angular module.
> - An export what you put is the exports property of the @NgModule decorator. It enables an Angular module to expose some of its components/directives/pipes to the other modules in the applications. Without it, the components/directives/pipes defined in a module could only be used in that module.

So when we saying `export/import` things between modules(for example when you want to use components created in another module, you have to import it first) we are meaning the angular way.

But in the offical routing example:

```
import { AppRoutingModule }     from './app-routing.module';
import ...
@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    AppRoutingModule
  ],
  declarations: [
    AppComponent,...
  ],
  bootstrap: [ AppComponent ]
})
export class AppModule { }
```

```
import { NgModule }             from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { DashboardComponent }   from './dashboard/dashboard.component';
...
const routes: Routes = [
  { path: '', redirectTo: '/dashboard', pathMatch: 'full' },
...
];

@NgModule({
  imports: [ RouterModule.forRoot(routes) ],
  exports: [ RouterModule ]
})
export class AppRoutingModule {}
```

`AppModule` depends on `AppRoutingModule`, so it have to import it.

For  `AppRoutingModule`, it have to use the components for handling the routes, but the components are created in `Appmodule`, so in my opinion `AppRoutingModule` depedens on `AppModule` now.

Now there are something consused me:

- The componets are not exported from `AppModule` at all by the angular `import/export`. 
- `AppRoutingModule` does not import `AppModule`
- `AppRoutingModule` import components directly using the `TypeScript` way.

What happened?

**Comment by trotyl** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

https://angular.io/guide/entry-components#a-routed-entry-component

It's well-explained in documentation.
