### ISSUE TITLE
Fail safely for Service workers enabled ng app in HTTP protocol in browser

### ISSUE THREAD

**Issue by ganeshkbhat** [angular/angular#24401]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Performance issue
[ X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Does not fail safely for Service workers enabled ng app in HTTP protocol in browser. When trying to open an angular app with service workers enabled will render an blank screen due to an error. Works okay as expected in HTTPS protocol.

```
vendor.11fb683a276fe085bb0a.js:1 ERROR Error: Uncaught (in promise): SecurityError: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
    at j (polyfills.5a0a464f4a0c614c3e4d.js:1)
    at polyfills.5a0a464f4a0c614c3e4d.js:1
    at polyfills.5a0a464f4a0c614c3e4d.js:1
    at e.invoke (polyfills.5a0a464f4a0c614c3e4d.js:1)
    at Object.onInvoke (vendor.11fb683a276fe085bb0a.js:1)
    at e.invoke (polyfills.5a0a464f4a0c614c3e4d.js:1)
    at t.run (polyfills.5a0a464f4a0c614c3e4d.js:1)
    at polyfills.5a0a464f4a0c614c3e4d.js:1
    at e.invokeTask (polyfills.5a0a464f4a0c614c3e4d.js:1)
    at Object.onInvokeTask (vendor.11fb683a276fe085bb0a.js:1)
```

## Expected behavior
Fail safely when opening an angular app in http protocol with service workers enabled

## Minimal reproduction of the problem with instructions
 * Enable service workers in angular app
 * Create a build
 * Open the app in http protocol instead of https

## What is the motivation / use case for changing the behavior?
Fails with an error not rendering the whole app and renders a blank screen

## Environment
Angular CLI: 6.0.1
Node: 9.11.1
OS: linux x64 (Ubuntu 17.x)
Angular: 6.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@ angular-devkit/architect         0.6.1
@ angular-devkit/build-angular     0.6.1
@ angular-devkit/build-optimizer   0.6.1
@ angular-devkit/core              0.6.1
@ angular-devkit/schematics        0.6.1
@ angular/pwa                      0.6.1
@ ngtools/webpack                  6.0.1
@ schematics/angular               0.6.1
@ schematics/update                0.6.1
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

Browser:
Following were tested. Others left blank not yet tested

- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version XX Mobile latest version
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 

Others:
NA

**Comment by gkalpak** [comment]
Since ServiceWorkers are not supported in non-secure pages, there is nothing we can do other than avoiding to register the ServiceWorker.

This would be trivial to do in your app, e.g.:

```diff
+ const isSecure = location.protocol === 'https:' || ['localhost', '127.0.0.1'].includes(location.hostname);

-ServiceWorkerModule.register('/ngsw-worker.js', { enabled: environment.production })
+ServiceWorkerModule.register('/ngsw-worker.js', { enabled: environment.production && isSecure })
```

If anyone wants to submit a PR baking that into `ServiceWorkerModule`, I think that would be OK.
Although, I wonder if it would be a breaking change (i.e. if it possible to specify other domain names that browsers treat as secure and allow SW) :confused:

**Comment by ganeshkbhat** [comment]
Thats the feature request. Please request you to fail HTTP protocol safely. Its just a 'if' statement; will not impact the code a lot. I have a requirement in a project and its a reality in the market; considering chrome is making HTTP as unsafe.

**Comment by ganeshkbhat** [comment]
@gkalpak On a second thought, I think you can close this. The provided solution should be fine; unless getting this into the framework code is going to be a task. Please make a choice based on your experience; you might be in a better position to take this up.

**Comment by gkalpak** [comment]
Yes, I think you are right. Since this is trivial to fix on the app side (and since everything it moving to HTTPS :wink:), let's close this (we don't want to encourage people serving stuff on HTTP 😛).
