### ISSUE TITLE
Angular 6 E2E tests don't work on Alpine Linux

### ISSUE THREAD

**Issue by hamilton-lima** [angular/angular#24402]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When running e2e test the following error happens:

<pre><code>
[14:10:55] E/launcher - Error: spawn /testAlpine/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.40 ENOENT
</code></pre>

[See stackoverflow question](https://stackoverflow.com/questions/50763289/how-to-run-angular6-e2e-tests-on-alpine-linux)

## Expected behavior

Run the e2e test with no errors.

## Minimal reproduction of the problem with instructions

<pre><code>
docker run -it --name my-alpine --rm alpine:latest /bin/ash
apk add --update nodejs nodejs-npm chromium \
    && export CHROME_BIN=/usr/bin/chromium-browser

npm install -g @angular/cli
ng new testAlpine
cd testAlpine
ng e2e
</code></pre>

## What is the motivation / use case for changing the behavior?

Use the provided e2e test

## Environment

<pre><code>
Angular version: 6.0.4

Angular CLI: 6.0.8
Node: 8.9.3
OS: linux x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.3
- Platform:  Alpine Linux v3.7

Others:
</code></pre>

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by hamilton-lima** [comment]
So this would be considered a protractor bug?
