### ISSUE TITLE
feature(core): order-independent mode for IterableDiffer

### ISSUE THREAD

**Issue by trotyl** [angular/angular#24406]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

[`NgClass`](https://angular.io/api/common/NgClass) uses [`IterableDiffer`](https://angular.io/api/core/IterableDiffer) for `string` or `string[]` input values:

https://github.com/angular/angular/blob/29eb24b142b29a84491f92fe1a4c48290a207db8/packages/common/src/directives/ng_class.ts#L78-L82

`IterableDiffer` would try to find out the order change, which is the most costly action in diffing, but makes no sense for `className`, as it only cares about existence or not:

https://github.com/angular/angular/blob/29eb24b142b29a84491f92fe1a4c48290a207db8/packages/common/src/directives/ng_class.ts#L102-L111

## Expected behavior

Provide an order-independent mode for `IterableDiffer` (or a new kind of differ) to skip the order-change detection, which could benefit cases like `NgClass`.

## Minimal reproduction of the problem with instructions

N/A.

## What is the motivation / use case for changing the behavior?

Performance.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
Note that this is less relevant post-ivy since with ivy changes `NgClass` / `NgStyle` won't use differs any more. As such the only real users of differ will be `NgFor` and as such I don't think we want to continue investing into making `IterableDiffer` a general-purpose utility.

**Comment by trotyl** [comment]
@pkozlowski-opensource Agreed, since there's no more use case within the framework, it doesn't necessarily be provided in built-in differs.
