### ISSUE TITLE
Routing animations don't work on dynamic routes

### ISSUE THREAD

**Issue by whizkidwwe1217** [angular/angular#24403]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Animations only work on the first time the route is activated. Then navigating to the same route with a different parameter, the animation don't work.

/tenant/view/1      -> Animation works once the route is activated for the first time
/tenant/view/2      -> Navigate to another route, animations don't work
/tenant/view/1      -> Again, animations is forever not working unless I navigate to a different route
/settings                -> then back to
/tenant/view/1      -> ANimations work, but again don't work when navigating to succeeding related routes

![image](https://user-images.githubusercontent.com/1977391/41203498-6b8c2eb4-6d0a-11e8-8161-d76179a8179d.png)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
I'm sorry but reported issues require a StackBlitz reproducing the problem.

If this issue persists, please create a StackBlitz using this template and describe the difference between the expected and current behavior and create a new issue: https://stackblitz.com/fork/angular-gitter

**Comment by whizkidwwe1217** [comment]
@ericmartinezr Here's the [https://stackblitz.com/edit/routing-animations](https://stackblitz.com/edit/routing-animations)
![image](https://user-images.githubusercontent.com/1977391/41209704-c229e6bc-6d5f-11e8-85fb-f0ff1fa7afe3.png)

**Comment by whizkidwwe1217** [comment]
I should say, inner router outlets only animate on first navigation

**Comment by levgaas** [comment]
@whizkidwwe1217 

The issue lies in how you handle animation state
`[@fadeAnimation]="outlet.isActivated ? outlet.activatedRoute : ''">`

The thing is that your **"Employees, Home, ..."** have separate routes. And once you navigate between them outlet first gets `isActivated === false` and then to `true`. So your animation state `* <=> *` is changed.

But you handle employees differently. It's `:id`. So if you navigate between children `activatedOutlet` is never changed. I mean the reference to the object.
Hence animation state is never changed.

**Comment by whizkidwwe1217** [comment]
@levgaas I see. Is there a proper way to make it work? I tried looking at the Angular docs and even tried HostBinding but it didn't worked for routes with /:id.
What do you mean by 'To have it worked each route should have unique identifier to properly differ routes'? The id that is being passed into the :id query parameter is unique

**Comment by levgaas** [comment]
@whizkidwwe1217 

There are tons of approaches.
Basically what you need to do is to whenever route is changed the animation state should change as well.

One of them would be:
You get that `:id` from router and paste it as animation state.

Or you can couple it with `router.url` itself.

Or you subscribe to router events and change state variable manually

**Comment by whizkidwwe1217** [comment]
@levgaas Got it! Thanks man. It's really great help for me. I appreciate it.
