### ISSUE TITLE
best practices of i18n for some cases

### ISSUE THREAD

**Issue by mouradghafiri** [angular/angular#24409]
Hello;

I found some difficulties to translate some cases.

A phrase with parameters that should change its order when translated to another language.
Word1 P1 Word2 P2 Word3 P3
should (after translation) be : Word3 P3 Word2 P2 Word1 P1

And a phrase that is distructed in HTML and that also change its order.

```
<div>
<span> Word1 P1</span>
</div>
<div>
<span> Word2 P2</span>
<span> Word3 P3</span>
</div>
```

should (after translation) be : 

```
<div>
<span> Word3 P3</span>
</div>
<div>
<span> Word2 P2</span>
<span> Word1 P1</span>
</div>
```

Thank you in advance

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
