### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by SamuelMarks** [angular/angular#24405]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Works fine on `ng serve`, but on `ng build --prod` nothing loads.

Console shows:
```
main.cce5d9c91eee4e38853c.js:1 Uncaught ReferenceError: process is not defined
    at Object.OekB (main.cce5d9c91eee4e38853c.js:1)
    at c (runtime.e5571f5c8402d28c7710.js:1)
    at Object.SwIR (main.cce5d9c91eee4e38853c.js:1)
    at c (runtime.e5571f5c8402d28c7710.js:1)
    at Object.zUnb (main.cce5d9c91eee4e38853c.js:1)
    at c (runtime.e5571f5c8402d28c7710.js:1)
    at Object.6 (main.cce5d9c91eee4e38853c.js:1)
    at c (runtime.e5571f5c8402d28c7710.js:1)
    at t (runtime.e5571f5c8402d28c7710.js:1)
    at Array.r [as push] (runtime.e5571f5c8402d28c7710.js:1)
OekB @ main.cce5d9c91eee4e38853c.js:1
c @ runtime.e5571f5c8402d28c7710.js:1
SwIR @ main.cce5d9c91eee4e38853c.js:1
c @ runtime.e5571f5c8402d28c7710.js:1
zUnb @ main.cce5d9c91eee4e38853c.js:1
c @ runtime.e5571f5c8402d28c7710.js:1
6 @ main.cce5d9c91eee4e38853c.js:1
c @ runtime.e5571f5c8402d28c7710.js:1
t @ runtime.e5571f5c8402d28c7710.js:1
r @ runtime.e5571f5c8402d28c7710.js:1
(anonymous) @ main.cce5d9c91eee4e38853c.js:1
```

## Expected behavior
Expected to load fine on `ng build --prod` also.

## Minimal reproduction of the problem with instructions
https://github.com/glaucoma-australia/glaucoma-risk-calculator-web-frontend
My package.json has this section also:
```json
"browser": {
  "fs": false,
  "path": false,
  "os": false
},
```

Also tried setting:
```
"process": true
```
as per https://github.com/gdi2290/angular-starter/blob/master/config/webpack.prod.js#L319

Also tried `npm i -S process`, and adding this to my `polyfills.ts`:
```
import * as process from 'process';
window['process'] = process;
```

Now refreshing the page gives me:
```
main.cce5d9c91eee4e38853c.js:1 Uncaught TypeError: e is not a constructor
    at main.cce5d9c91eee4e38853c.js:1
    at Ao (main.cce5d9c91eee4e38853c.js:1)
    at main.cce5d9c91eee4e38853c.js:1
    at new t (main.cce5d9c91eee4e38853c.js:1)
    at Object.Qo [as createNgModuleRef] (main.cce5d9c91eee4e38853c.js:1)
    at e.create (main.cce5d9c91eee4e38853c.js:1)
    at main.cce5d9c91eee4e38853c.js:1
    at e.invoke (polyfills.6a51f2ae3d3c5687da3a.js:1)
    at Object.onInvoke (main.cce5d9c91eee4e38853c.js:1)
    at e.invoke (polyfills.6a51f2ae3d3c5687da3a.js:1)
(anonymous) @ main.cce5d9c91eee4e38853c.js:1
Ao @ main.cce5d9c91eee4e38853c.js:1
(anonymous) @ main.cce5d9c91eee4e38853c.js:1
t @ main.cce5d9c91eee4e38853c.js:1
Qo @ main.cce5d9c91eee4e38853c.js:1
e.create @ main.cce5d9c91eee4e38853c.js:1
(anonymous) @ main.cce5d9c91eee4e38853c.js:1
e.invoke @ polyfills.6a51f2ae3d3c5687da3a.js:1
onInvoke @ main.cce5d9c91eee4e38853c.js:1
e.invoke @ polyfills.6a51f2ae3d3c5687da3a.js:1
t.run @ polyfills.6a51f2ae3d3c5687da3a.js:1
t.run @ main.cce5d9c91eee4e38853c.js:1
t.bootstrapModuleFactory @ main.cce5d9c91eee4e38853c.js:1
zUnb @ main.cce5d9c91eee4e38853c.js:1
c @ runtime.e5571f5c8402d28c7710.js:1
6 @ main.cce5d9c91eee4e38853c.js:1
c @ runtime.e5571f5c8402d28c7710.js:1
t @ runtime.e5571f5c8402d28c7710.js:1
r @ runtime.e5571f5c8402d28c7710.js:1
(anonymous) @ main.cce5d9c91eee4e38853c.js:1
```

## Environment

<pre><code>
Angular version: 6.0.3 with CLI v6.0.8

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.2
- Platform:  

Others:
Confirmed with nginx and SimpleHTTPServer; it's not a server issue.
</code></pre>

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by SamuelMarks** [comment]
@mhevery Is there some debug mode I can enable that will give me an actual error message?

All these tracebacks are horribly uninformative, to the point where one would close an issue or stackoverflow question due to lack of concise test-case.

`ng build` works; `ng build --prod` works, but when running nothing loads and it gives that error in console.

😞
