### ISSUE TITLE
Angular 5 app performance issue

### ISSUE THREAD

**Issue by kunaldel** [angular/angular#24416]
hii all,

I have created angular 5 app. (http://13.232.46.113/).
please suggest ways to resolve performance issue.
On SCROLL,  I concat element in view.
Switching between different view becomes sticky when more and more element get appended in view.
View is made of UL..LI of Cards through ng-repeat.

Please Suggest why its getting slow asap. on card I have not used ngModel.

**Comment by jotatoledo** [comment]
There are good articles about this topic out in the net. Try by searching for "angular improve performance", do some research by yourself.

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
