### ISSUE TITLE
More configuration options for Injectables

### ISSUE THREAD

**Issue by csutorasr** [angular/angular#24413]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

According to the Angular 6 docs, the CoreModule can be injected only once in the AppModule. I placed my interceptors in the CoreModule as injecting the tokens to the HTTP requests is a core function. Before Angular 6 I provided the interceptors and in every module that needed the token I added CoreModule as a dependency. I works well now, however I inject the CoreModule more than once this way.

## Expected behavior

A way to inject my interceptors with `provideIn: 'root'`.

This way the interceptors would be existing in any module, and the CoreModule could be injected only once.

This would be nice for every `multi` or `useValue` etc. injectables, the interceptors are just an example.

## Other:

[Stackoverflow link](https://stackoverflow.com/questions/50211120/angular-6-provide-http-interceptors-for-root) on the problem.

**Comment by trotyl** [comment]
The DI usage hasn't been changed in v6, there's only a new concept called **default implementation**, which allow the owner of some token to provide a **fallback provider** of some token.

This would not help with non-default (customize) usage, which is **neither tree-shakable nor reachable**.

And clearly you're not the owner of `HTTP_INTERCEPTERS`.
