### ISSUE TITLE
Service worker not caching the local files

### ISSUE THREAD

**Issue by harshjulka** [angular/angular#24411]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am adding a error.html in resources. However,  its not cacching the file in ngsw.json file
ngsw-config.json
<pre>
{
  "index": "/index.html",
  "assetGroups": [{
    "name": "app",
    "installMode": "prefetch",
    "resources": {
      "files": [
        "/favicon.ico",
        "/index.html",
        "/error.html",
        "/*.css",
        "/*.js"
      ],
      "urls": [
        "https://fonts.googleapis.com/css?family=Material+Icons",
        "https://fonts.gstatic.com/s/materialicons/v29/2fcrYFNaTjcS6g4U3t-Y5UEw0lE80llgEseQY3FEmqw.woff2",
        "https://fonts.googleapis.com/css?family=Roboto:300,400,500" 
      ]
    }
  }, {
    "name": "assets",
    "installMode": "lazy",
    "updateMode": "prefetch",
    "resources": {
      "files": [
        "/assets/**"      ]
    }
  }]
}
</pre>

## Generated ngsw.json
<pre>
{
  "configVersion": 1,
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "updateMode": "prefetch",
      "urls": [
        "/favicon.ico",
        "/index.html",
        "/main.af9b91fe168b3978a68b.js",
        "/polyfills.2f4a59095805af02bd79.js",
        "/runtime.a66f828dca56eeb90e02.js",
        "/styles.34c57ab7888ec1573f9c.css"
      ],
      "patterns": [
        "https:\\/\\/fonts\\.googleapis\\.com\\/css\\?family=Material\\+Icons",
        "https:\\/\\/fonts\\.gstatic\\.com\\/s\\/materialicons\\/v29\\/2fcrYFNaTjcS6g4U3t-Y5UEw0lE80llgEseQY3FEmqw\\.woff2",
        "https:\\/\\/fonts\\.googleapis\\.com\\/css\\?family=Roboto:300,400,500"
      ]
    },
    {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "urls": [
        "/assets/icons/icon-128x128.png",
        "/assets/icons/icon-144x144.png",
        "/assets/icons/icon-152x152.png",
        "/assets/icons/icon-192x192.png",
        "/assets/icons/icon-384x384.png",
        "/assets/icons/icon-512x512.png",
        "/assets/icons/icon-72x72.png",
        "/assets/icons/icon-96x96.png"
      ],
      "patterns": []
    }
  ],
  "dataGroups": [],
  "hashTable": {
    "/assets/icons/icon-128x128.png": "dae3b6ed49bdaf4327b92531d4b5b4a5d30c7532",
    "/assets/icons/icon-144x144.png": "b0bd89982e08f9bd2b642928f5391915b74799a7",
    "/assets/icons/icon-152x152.png": "7479a9477815dfd9668d60f8b3b2fba709b91310",
    "/assets/icons/icon-192x192.png": "1abd80d431a237a853ce38147d8c63752f10933b",
    "/assets/icons/icon-384x384.png": "329749cd6393768d3131ed6304c136b1ca05f2fd",
    "/assets/icons/icon-512x512.png": "559d9c4318b45a1f2b10596bbb4c960fe521dbcc",
    "/assets/icons/icon-72x72.png": "c457e56089a36952cd67156f9996bc4ce54a5ed9",
    "/assets/icons/icon-96x96.png": "3914125a4b445bf111c5627875fc190f560daa41",
    "/favicon.ico": "84161b857f5c547e3699ddfbffc6d8d737542e01",
    "/index.html": "c10782863caaf82fcc5fd74feab02edcc5ada1db",
    "/main.af9b91fe168b3978a68b.js": "6e018d5019f4bfb6983e86453a6153285674ce72",
    "/polyfills.2f4a59095805af02bd79.js": "8949bb1b1e302dda246f6ed9c2da703270360b1f",
    "/runtime.a66f828dca56eeb90e02.js": "078e320cc6fdaf355836c3b1c52b059cdd33fc7e",
    "/styles.34c57ab7888ec1573f9c.css": "da39a3ee5e6b4b0d3255bfef95601890afd80709"
  },
  "navigationUrls": [
    {
      "positive": true,
      "regex": "^\\/.*$"
    },
    {
      "positive": false,
      "regex": "^\\/(?:.+\\/)?[^\\/]*\\.[^\\/]*$"
    },
    {
      "positive": false,
      "regex": "^\\/(?:.+\\/)?[^\\/]*__[^\\/]*$"
    },
    {
      "positive": false,
      "regex": "^\\/(?:.+\\/)?[^\\/]*__[^\\/]*\\/.*$"
    }
  ]
}
</pre>

## Expected behavior

It should add the error.html same like index.html file

## What is the motivation / use case for changing the behavior?

It will help the developer because we don't have to cache files by modifying the ngsw-worker.js

## Environment

<pre><code>
Angular version: X.Y.Z

<pre>
Angular CLI: 6.0.7
Node: 8.11.2
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.7
@angular-devkit/build-angular     0.6.7
@angular-devkit/build-optimizer   0.6.7
@angular-devkit/core              0.6.7
@angular-devkit/schematics        0.6.7
@angular/cli                      6.0.7
@angular/pwa                      0.6.8
@ngtools/webpack                  6.0.7
@schematics/angular               0.6.7
@schematics/update                0.6.7
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
    </pre>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
This happens because `error.html` does not exist in your dist directory (i.e. it is not copied over by the cli). In order to get cli to copy it over, you need to specify it as an asset in your `angular.json` config file:

```diff
 "assets": [
   "src/favicon.ico",
+  "src/error.html",
   "src/assets"
 ],
```

Once you do that, the file will be copied over to the dist directory and will be included in `ngsw.json` as expected.
