### ISSUE TITLE
Allow animation-fill-mode as a property of animate.

### ISSUE THREAD

**Issue by bklik** [angular/angular#24428]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The following throws an error
```javascript
animate('400ms ease forwards', style({...}))
```

## Expected behavior

Animate should except [animation-fill-mode](https://www.w3schools.com/cssref/css3_pr_animation-fill-mode.asp) and behave accordingly.

## What is the motivation / use case for changing the behavior?

Animation-fill-mode is a common CSS animation property that has been around for years, and is fully supported on all browsers. Not providing it requires a tremendous amount of boilerplate to recreate.

**Comment by haoliangwu** [comment]
if it can support `forwards` to stop at final animation frame style, that sounds great. But I found the workaround here is just providing final style with `[ngStyle]`. Hope for help.
