### ISSUE TITLE
AOT compiler mix up useClass provider with the module class itself

### ISSUE THREAD

**Issue by tchandelle** [angular/angular#24421]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When providing an anonymous class in a the provider of a module, AOT compiler use the Module itself.

## Expected behavior

It should use the provided class

## Minimal reproduction of the problem with instructions

When the `DateAdapter` is required by `mat-datepicker`, it will provide the `FooModule` instead (only in AOT)

```ts
import { NgModule } from '@angular/core';
import { MatMomentDateModule, MomentDateAdapter } from '@angular/material-moment-adapter'
import { DateAdapter, MAT_DATE_LOCALE } from '@angular/material/core'
import { Moment } from 'moment'

@NgModule({
  providers: [
    {
      provide: DateAdapter,
      useClass: class extends MomentDateAdapter {
        compareDate(first: Moment, second: Moment): number {
          return first.valueOf() - second.valueOf()
        }
      },
      deps: [ MAT_DATE_LOCALE ],
    },
  ]
})
export class FooModule {
  constructor() {
    console.log(arguments)
    // ⤷ on 2nd call, will be injected parameter for MomentDateAdapter
    // (ie. dateLocale: string)
  }
}

```

## Environment

<pre><code>
Angular CLI: 6.0.8
Node: 8.11.2
OS: darwin x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.6.8
@angular/cdk                       6.2.1
@angular/cli                       6.0.8
@angular/material                  6.2.1
@angular/material-moment-adapter   6.2.1
@ngtools/webpack                   6.0.8
@schematics/angular                0.6.8
@schematics/update                 0.6.8
rxjs                               6.2.0
typescript                         2.7.2
webpack                            4.8.3

Browser:
- [x] Chrome (desktop) version 66.0.3359.181
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX   v8.11.2
- Platform:   Mac

Others:

</code></pre>

**Comment by tchandelle** [comment]
It works if I provide an exported named class.

I guess that it isn't supposed to work and that an error message is missing (like when we provide non exported classes)

**Comment by JoostK** [comment]
This is no longer an issue in Ivy, as it's caused by a bug in the metadata system that's no longer used in Ivy.
