### ISSUE TITLE
Some location change events are no longer after router upgrade

### ISSUE THREAD

**Issue by vincentjames501** [angular/angular#24429]
## I'm submitting a...
<pre><code>
[ x ] Regression (a behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior
We are running a hybrid application and we have some AngularJS code that calls `$location.path(...)` to change routes. This commit https://github.com/angular/angular/commit/c40ae7f7cfb7f498bc142ae267911e07d73baf31 introduced an issue where when our AngularJS code changes its location to an Angular route, Angular never gets notified of this change (`enableTracing: true` shows this as well). If I simply change line 738 in the aforementioned commit (between router version 6.0.0.beta1 and 6.0.0.beta2) to what it was previously:
```typescript
if (this.location.isCurrentPathEqualTo(path) || replaceUrl) {
  this.location.replaceState(path);
} else {
  this.location.go(path);
}
```
Angular still gets notified correctly of these route changes.

## Expected behavior
I expect that when `$location.path(...)` is invoked outside of Angular, that Angular still picks up on the location change so the correct components can be loaded.

## Environment

<pre><code>
Angular version: 6.0.4

Browser:
- [ x ] Chrome (desktop) version 67
 
For Tooling issues:
- Node version: 9.11.1
- Platform:  Mac

</code></pre>

**Comment by vincentjames501** [comment]
Looks like this is related to #21995 #21728

**Comment by TheeRFG** [comment]
I've recently attempted to upgrade from Angular5 to Angular7 and I've noticed this issue as well. Routing is so intermittently inconsistent I would honestly deem this as unusable. We've actually had to revert our entire upgrade and stay on version 5 because of this.
