### ISSUE TITLE
Non functionality of Interceptor - When used Ng6 new feature 

### ISSUE THREAD

**Issue by BharathKumarKompelli** [angular/angular#24425]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Until Angular 5, Interceptor having request headers used by importing in module - applied for all services commonly which are imported in that particular module.

## Expected behavior
After Angular 6, When following snippet is used instead of importing services in module (new feature as told)

@Injectable({
  providedIn: 'root'
})

Interceptor is not working - meant request headers are not getting applied for the service requests.

## What is the motivation / use case for changing the behavior?
When removed service imports in module and used the above snippet (update bought in Angular 6) - still interceptor should apply all request headers when interceptor is imported in module.

##Observed
Angular version: 6.0.4

Browser:
- [x] Chrome (desktop) version 66

For Tooling issues:
- Node version: 9.5.0  
- Platform: Mac OS High Sierra v10.13.4

**Comment by mhevery** [comment]
What you are asking for is not technically possible because it goes against tree shaking. 

Won't fix.
