### ISSUE TITLE
UpgradeModule throws error: Unknown provider: $injector from $$UpgradeModule.init

### ISSUE THREAD

**Issue by Kayes-Islam** [angular/angular#24431]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am roughly following this guide to integrate Angular 6 in our existing app: https://angular.io/guide/upgrade
I am getting the exception: "Unknown provider: $injector from $$UpgradeModule.init".

## Expected behavior

No exception thrown and both angularjs and angular components works.

## Minimal reproduction of the problem with instructions

I have an old AngularJS 1.0.5 app and we need to be able to integrate some of the components from the new Angular6 app into the AngularJS app.

I am trying achieve this by following the upgrade guide (https://angular.io/guide/upgrade). However some of the things are a bit different for my implementation:
I do not have AngularJS and Angular in the same project, my requirement is that I need to build then deploy the Angular6 into AngularJS project. I am doing that by `ng build --output-path ../OldAngularJSApp/NewAppOutput`. I then make sure the scripts in NewAppOutput are included in the index.html file of the old angularjs app. Other than that I've followed everything from the guide.

I have managed to reproduce this behaviour on a test project which is can be downloaded here:
https://drive.google.com/open?id=1B_GIly9CNcsYQ1o0kvOu811kqUoscj7G

Steps to run to see the problem:

1. Download the reproducible code and unzip
2. CD to NewAngular6App and run `npm install & npm run build` which will generate output to 
../OldAngularJSApp/NewAppOutput.
3. CD to OldAngularJSApp and run `npm install & npm run start`
4. Open browser to localhost:5050 and dev mode to see the exception

As an overview here's what my bootstrapping looks like in angular6's module.ts file:
```
  ngDoBootstrap() {
    angular.module('myApp')
      .directive('appTest', downgradeComponent({component: TestComponent}));
    
    angular.element(this.document).ready(() =>{
      this.upgrade.bootstrap(this.document.documentElement, ['myApp']);
    });
  }
```
And here's my AngularJS module and controller  in app.js file:
```
var app = angular.module('myApp', []);
app.controller('MainCtrl', ['$scope', '$http', function ($scope, $http) {
  $scope.text = "Text in angularjs controller"
}]);
```
Here's the view in index.html file:
```
<body ng-controller="MainCtrl">
  <app-test></app-test>
  <div> {{text}}</div>

</body>
```

## Environment

<pre><code>
Angular version: 6

AngularJS Version: 1.0.5

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
This is because `ngUpgrade` relies on an AngularJS feature that is not available in v1.0.5: exposing the provider injector.

Even if you found a way to work around that (which might not be possible at all), I am pretty sure `ngUpgrade` is not compatible with v1.0.5 anyway. 1.0.5 is a very old, unsupported version. `ngUpgrade` assumes an AngularJS version >= 1.5.x.

It is recommended that you first upgrade your AngularJS app to a more recent AngularJS version and only then use `ngUpgrade`. (But with such an old codebase it might make more sense for you to do a "big bang" re-write to Angular directly.)

**Comment by Kayes-Islam** [comment]
Thank you @gkalpak  

That is actually the first thing I looked for in the guide (https://angular.io/guide/upgrade) but it's not mentioned there. The minimum version requirement should be added to the guide and the documentation.

**Comment by gkalpak** [comment]
Good point @Kayes-Islam. Could you open an issue about that (or even submit a PR :wink:)?

**Comment by Kayes-Islam** [comment]
I have upgraded my test project to 1.2.0 and downgrading angular6 components and services worked.
