### ISSUE TITLE
Error: Cannot find a differ supporting object '' of type 'object'. NgFor only supports binding to Iterables such as Arrays in Chrome 41. 

### ISSUE THREAD

**Issue by sunnykreative** [angular/angular#24434]
Error: Cannot find a differ supporting object '' of type 'object'. NgFor only supports binding to Iterables such as Arrays in Chrome 41. I need to get this working on chrome 41 only please help.

In Ts following is written:

courses = [
{ id: 1 , name: "course 1"},
{ id: 2 , name: "course 2"},
{ id: 3 , name: "course 3"},

];

In html:

<ul>
<li *ngFor="let course of courses">
{‌{ course.name }}
</li>
</ul>

**Comment by splincode** [comment]
Please add repo for reproduce or example on stackblitz

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
