### ISSUE TITLE
my npm package as loadChildren config,but error in ng6

### ISSUE THREAD

**Issue by jiangmingwen** [angular/angular#24435]
## my npm package  top/login  has been install 
<pre><code>
const routes: Routes = [
  {
    path: '',
    redirectTo: 'login',
    pathMatch: 'full',
  },
  {
    path: 'login',
    loadChildren: 'node_modules/top/login/dist/lib/login.module#LoginModule',
  }
]
</code></pre>

## Current behavior

ERROR in ./node_modules/top/login/dist/lib/login.module.ts
Module build failed: Error: H:\topweb\branch\ppp\node_modules\top\login\dist\lib\login.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).

## Expected behavior
but ng4 and ng5 it's right, how to resolve? 

## Environment
<pre><code>
Angular CLI: 6.0.8
Node: 8.11.2
OS: win32 x64
Angular: 6.0.3
Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.6.8
@angular-devkit/build-angular       0.6.8
@angular-devkit/build-optimizer     0.6.8
@angular-devkit/core                0.6.8
@angular-devkit/schematics          0.6.8
@angular/animations                 6.0.4
@angular/cli                        6.0.8
@angular/common                     6.0.4
@angular/compiler                   6.0.4
@angular/compiler-cli               6.0.4
@angular/forms                      6.0.4
@angular/http                       6.0.4
@angular/language-service           6.0.4
@angular/platform-browser           6.0.4
@angular/platform-browser-dynamic   6.0.4
@angular/router                     6.0.4
@ngtools/webpack                    6.0.8
@schematics/angular                 0.6.8
@schematics/update                  0.6.8
rxjs                                6.0.0
typescript                          2.7.2
webpack                             4.8.3
</code></pre>

**Comment by splincode** [comment]
need more information
add repo with step for reproduce

**Comment by alexeagle** [comment]
Also you don't say what produced this error. Were you running `ng build`? is this a runtime error in the browser?
There's not enough info here for us to understand the issue, but it seems you're saying this is a breaking change from Angular 5 to 6?

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
