### ISSUE TITLE
about angular6 picture assets path

### ISSUE THREAD

**Issue by z3214965** [angular/angular#24436]
customize two modules, module a refers to module b, module b refers to a picture, this picture resource should be placed in module a, or module b?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
