### ISSUE TITLE
Need a simple way to pause/start/stop animations

### ISSUE THREAD

**Issue by m98** [angular/angular#24433]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

After some hours of working with Animations in Angular (which I should say it's not easy), I could make something that works, but I still have problems. One of the problems I'm already facing is that there is not anyway (or at least no way in docs) to pause stagger animation, and I need to pause the animation while it's running on a bunch of phone numbers and show one phone number as the winner... I could not do it!

## Expected behavior

An easy way to pause stagger!

It's also kind of wired that stagger animation takes something like the length of the array you're going to animate, but it's not limited to that... It's like it does not use that number at all. 
```
// from: https://angular.io/api/animations/stagger#usage
<div [@listAnimation]="items.length">
  <div *ngFor="let item of items">
    {{ item }}
  </div>
</div>
```
but when you set `item.length` to a static number, or a way larger one, nothing changes. It could be nice if it could be used to pause at that index!

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 66
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9
- Platform:  Fedora
- Angular: 6

Others:

</code></pre>

**Comment by levgaas** [comment]
@m98 

Currently you can achieve this by using `AnimationBuilder`
https://angular.io/api/animations/AnimationBuilder

Which returns `AnimationPlayer`. 
https://angular.io/api/animations/AnimationPlayer

Having `animationPlayer` in play you could have more granular control over animations.

**_That's suggested / proper way to tackle it._**



> If it's not suitable for you, you can have your hands dirty:

1. Inject `private animationBuilder: AnimationBuilder` into constructor of your component

2. bind output listener to `(@animation.start)="onAnimationStart($event)"` event

3. 
```
  onAnimationStart(event): void {
    const animationRenderer: AnimationRenderer = this.animationBuilder._renderer;
    const animationPlayers = animationRenderer.engine.players;
    // find trigger you want to have control over
    const player = animationPlayers.find((p) => p.triggerName === event.triggerName);

    player.pause();

   // here you can control your animation
  }
```

**Keep in mind that it's experimental and not documented. And accessing private API could lead to unexpected behavior**
