### ISSUE TITLE
Provide an easy persistent way to navigate from Angular blog to main Angular site

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#24449]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[X ] Other... Please describe: Blog site 
</code></pre>

## Current behavior

The Angular blog is a self-contained site. Within articles there are often links to related resources on the Angular site, but there doesn't seem to be an obvious persistent link. 

In reverse, the Angular site has "BLOG" as a primary subarea offered in the main masthead. 

## Expected behavior

BLOG uses the same masthead as the main Angular site, so it feels like a true subarea.

![blog-to-angular-option3](https://user-images.githubusercontent.com/31675481/41307589-dd1e18ee-6e36-11e8-825b-6a9eb25fe1f2.png)

or....
BLOG has an icon/link in its masthead area that provides a single link to the main Angular site. 

![blog-to-angular-option2](https://user-images.githubusercontent.com/31675481/41307599-e33372ce-6e36-11e8-9f02-2d2aeb81ad6b.png)

or...
BLOG looks as it does today but Angular icon is a link to the main Angular site

![blog-to-angular-option1](https://user-images.githubusercontent.com/31675481/41307621-f02f665e-6e36-11e8-8bf7-e31c193526c7.png)

## Minimal reproduction of the problem with instructions

1. Go to https://blog.angular.io/
2. Try to go to the main Angular site (https://angular.io) from the home page of the blog. 

## What is the motivation / use case for changing the behavior?

Create a more unified content experience. Encourage co-use of Angular site and the blog. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by StephenFluin** [comment]
We have chosen Medium as our platform for hosting our blog, and I don't believe it supports this sort of customization. Part of the value of Medium is it's intense focus on the simplicity of the reading experience, so I don't believe we will be able to fix this.

Hopefully the links we put into the blog content serve as natural starting points to relevant and appropriate places within angular.io.
