### ISSUE TITLE
Ng switch using same component instance for same case type

### ISSUE THREAD

**Issue by rakshans1** [angular/angular#24440]
## I'm submitting a... 
Bug

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

**when same switch case is called with different data** 

using ngswitch when the data is changed new instance of the component is not created and internal data created at time of ngOnInit remains same.

## Expected behavior

new component instance should have been created when switching data.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-llprbc

when same type is used with different data the component instance is same therefore ngOnInit is not called twice

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [x] Chrome (desktop) version 65.0.3325.181
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
> using ngswitch when the data is changed

What being passed to `ngSwitch` is `currentQuestion.type`, which is not changed and always being `'hello'`. Try change the data and then it would be recreated:

https://stackblitz.com/edit/angular-llprbc?file=src%2Fapp%2Fapp.component.ts

**Comment by trotyl** [comment]
What you have changed has nothing to do with `NgSwitch`, the only value it got is result of `currentQuestion.type` which being a `string`.

Try:

```javascript
let oldValue = null
function check(value) {
  // How do you want to tell if `foo` is different than `foo` here?

  // End
  oldValue = value
}

const oldObj = { data: 'foo', other: 1 }
const newObj = { data: 'foo', other: 2 }

check(oldObj.data)
check(newObj.data)
```

And `NgSwitch` is never designed to recreate a component, nothing is. If you want to reset the component state, achieve it via component communication.

**Comment by alexeagle** [comment]
thanks @trotyl 
Seems like that should resolve the question, so closing.
