### ISSUE TITLE
Bad number formatting locale for "sk" - Slovak Republic

### ISSUE THREAD

**Issue by Orvisky** [angular/angular#24467]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
<pre>
{{1589.35 | number:'.2':'sk'}}
</pre>
* outputs - 1,589.35

## Expected behavior
<pre>
{{1589.35 | number:'.2':'sk'}}
</pre>
* outputs - 1 589,35

## Minimal reproduction of the problem with instructions
When using DecimalPipe and locale "sk", i found that there is bad number format in "sk" locale https://github.com/angular/angular/blob/master/packages/common/locales/sk.ts#L50. 
<pre>
['#,##0.###', '#,##0 %', '#,##0.00 ¤', '#E0'], '€', 'euro', {
</pre>
It should be
<pre>
['# ##0,###', '# ##0 %', '# ##0,00 ¤', '#E0'], '€', 'euro', {
</pre>
In Slovak Republic, we dont write number like this: 1,458,558.05, but like this, 1 458 558,05.
So we use space " " as separator and comma "," as decimal point.

## What is the motivation / use case for changing the behavior?
Correct number formatting for locale Slovak Republic.

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [x] Chrome (desktop) version 67.0.3396.79 (Official Build) (64-bit)
 
For Tooling issues:
- Node version: 8.9.4
- Platform:  Windows 10

</code></pre>

**Comment by vicb** [comment]
The formats (`['#,##0.###', '#,##0 %', '#,##0.00 ¤', '#E0'], '€', 'euro', {`) are extracted from the CLDR database.
There might be:
- a bug in our extraction script, in which case we can fix it,
- a bug in the CLDR and which case you would need to report a bug there. We can make a local override when the bug has been accepted by CLDR.

@ocombe please have a look

**Comment by Orvisky** [comment]
It seems that there is some strange thing i found in that database - http://demo.icu-project.org/icu-bin/locexp?d_=en&_=sk_SK.

![image](https://user-images.githubusercontent.com/1727586/41370017-c10c5312-6f46-11e8-9066-d8e6631116b5.png)

For example:

Decimal Pattern | #,##0.### | 1 234,56
-- | -- | --

They mention format "#,##0.###", which i think is not equal to their output "1 234,56".
Correct me if i am wrong, but i think you consider "," as exact "," character. 
So i think they have bad interpretation.

**Comment by ocombe** [comment]
"," is not necessarily the "," character, it is the "group separator" for numbers (see https://angular.io/api/common/NumberSymbol for the list of symbols).
The group symbol is the second symbol in the list (see api doc above), which means that it's the second symbol in this array: `[',', ' ', ';', '%', '+', '-', 'e', '×', '‰', '∞', 'NaN', ':']` (see https://github.com/angular/angular/blob/master/packages/common/locales/sk.ts#L49).
In our case it's ` ` which is a non-breaking space symbol, encoded as `&nbsp;` in html or `U+00A0` in unicode.

So you are correct about your expected output, it should be `- 1 589,35`.
And it is in fact the case **in v6**, as long as you don't forget to load the sk locale data. See https://stackblitz.com/edit/angular-gitter-rgjfny?file=app%2Fapp.module.ts

This is why we ask for a reproduction of the bug. In this case there is no bug it works as expected (at least in v6, I haven't tested v5).
