### ISSUE TITLE
Testing documentation is linking to older Jasmine than the Angular Cli is using

### ISSUE THREAD

**Issue by samal84** [angular/angular#24462]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The current testing documentation is linking to the version 2.4 Jasmine documentation: https://github.com/angular/angular/blob/9add50129d14d21d940ab830699f9598f490d006/aio/content/guide/testing.md

## Expected behavior
The Angular Cli is linking to version ^2.6.0 of jasmine currently, so I would expect the documentation to do the same: https://github.com/angular/angular-cli/blob/182c890979fdefc5c73b5184c75c0c51d68c0760/package.json

**Comment by brandonroberts** [comment]
@samal84 would you like to submit a PR for this change? I can provide assistance if needed.

**Comment by brandonroberts** [comment]
Fixed via https://github.com/angular/angular/pull/25175
