### ISSUE TITLE
Directive stops working when dependent on formControlName and parent control is rebuilt

### ISSUE THREAD

**Issue by kirilmitev** [angular/angular#24472]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
A directive, that works on a FormControl would either use @Input() formControl, or @Input() formControlName. If the directive gets a formControlName, it would have to use the parent FormGroup to get the desired FormControl-instance. Then the directive can subscribe to value-, or statusChanges of this FormControl and react to these changes. A problem arises when the reference to the parent FormGroup is changed, for example because the FormGroup is part of a FormArray and this array is being rebuild with data coming from the Backend. The directive has no way to react to this change of the reference to the parent FormGroup! 
In the template we can either use the *ngFor structural directive to loop over controls, or access them directly ( i.e. myArray.controls[ 0 ].get( 'title' ) ). If the controls are accessed directly and we rebuild the FormArray, then our custom directive will simply stop getting value-, or statusChanges, in other words it will stop working. If the controls are accessed through a loop and we rebuild the FormArray, then new directives will be created, which could lead to memory leaks, as the old directives are still subscribed and listening for changes.   

## Expected behavior
We would like some way to react to changes regarding FormGroup references. The desired behavior could be achieved with:
<pre><code>
const formGroupDirective: FormGroupDirective = this.controlContainer.formDirective as FormGroupDirective;
const temp = formGroupDirective.ngOnChanges;
formGroupDirective.ngOnChanges = (changes: SimpleChanges) => {

    // Here we can react to changes of the FormGroup reference

    temp.call(this, changes);
}
</code></pre>
But this of course is a "hack". A solution could be something like:
<pre><code>
formGroupDirective.controlChanges.subscribe( () => // Here we can react to changes of the FormGroup reference )
</code></pre>
or maybe:
<pre><code>
this.controlContainer.controlChanges.subscribe( () => // Here we can react to changes of the FormGroup reference )
</code></pre>

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-nrcfml
You see a form on the page. The FormControls have the required validator set and the ErrorHandlerDirective applied. If the FormControl is invalid, the ErrorHandlerDirective colors the border of the FormControl's DOM element in red. Otherwise, the border is in the default grey color.
Clicking on "Load data from Backend" will rebuild the FormArray. The new FormControls also have the required validator set and the ErrorHandlerDirective applied, but the ErrorHandlerDirective does not style the controls anymore. 

## What is the motivation / use case for changing the behavior?
REST and reactive forms are a must for web developers. There are many use cases for adding/removing/changing FormControls/FormArrays/FormGroups based on REST communication. Every directive that operates on a FormControl should know, when it's FormControl dissapears, or it's reference changes.

## Environment
<pre><code>
Angular version: 6.0.4
</code></pre>

**Comment by javix** [comment]
+

**Comment by 5te1n** [comment]
Vote +1

**Comment by bibidon** [comment]
Are the any changes? Still have.
Angular version: 11.1.2

**Comment by dylhunn** [comment]
This is more a limitation of the DI system than Forms -- if the parent of the form directive changes inside the template, the new parent isn't injected again later.

**Comment by dylhunn** [comment]
I'm sorry to say this is just not a use case Forms (or the DI system integration) can realistically support without a redesign.
