### ISSUE TITLE
Cannot read property 'module' of undefined when using barrel and flatModuleOutFile

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#24476]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When using `flatModuleOutFile` and a barrel file to register a symbol to an `NgModule` an error is  emitted `TypeError: Cannot read property 'module' of undefined`.

tsconfig
```json
  "angularCompilerOptions": {
    "flatModuleId": "index.js",
    "flatModuleOutFile": "index.js"
  }
```

Module file
```ts
import { NgModule } from '@angular/core';
import { LibComponent } from './lib/index';

@NgModule({
  declarations: [LibComponent]
})
export class LibModule { }

```

## Expected behavior
Build works without any error.

## Minimal reproduction of the problem with instructions
https://github.com/alan-agius4/angular-issue-24476

## Environment

<pre><code>
Angular version: 6.0.4
Typescript: 2.7.2
</pre></code>

### Related issues: 
https://github.com/angular/angular/issues/23713

https://github.com/dherges/ng-packagr/issues/917
https://github.com/dherges/ng-packagr/issues/943

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/20931?

**Comment by alan-agius4** [comment]
yes, thanks
