### ISSUE TITLE
Absence of `Object.setPrototypeOf` on IE10 since rxjs@6

### ISSUE THREAD

**Issue by everedifice** [angular/angular#24488]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Since rxjs@6.0.0 IE10 need polyfill of `Object.setPrototypeOf`. [breaking changes of rxjs6](https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#breaking-changes-7)

Angular depends on core-js polyfill. but core-js's `Object.setPrototypeOf` polyfill needs IE11+ [you can check here.](https://github.com/zloirock/core-js#ecmascript-object)

So if Angular want to support IE10. need other polyfill like [set-prototype-of](https://www.npmjs.com/package/setprototypeof) or else.

Or just add commented module import syntax like `classlist.js`.

Or don't support IE10... 😢 

## Minimal reproduction of the problem with instructions

After uncomment some lines in `polyfill.ts` for supporting IE10 but. If browser ran rxjs's EmptyError.js or ArgumentOutOfRangeError.js. throw is not function error.

You can see the source codes

https://github.com/ReactiveX/rxjs/blob/d0ea152f3c5575455a73cc43b8fad6a750d24208/src/internal/util/ArgumentOutOfRangeError.ts#L17

https://github.com/ReactiveX/rxjs/blob/d0ea152f3c5575455a73cc43b8fad6a750d24208/src/internal/util/EmptyError.ts#L17

## Environment

<pre><code>
Angular version: 6.0.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 10 (modern.ie)
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.3  
- Platform: Windows  

Others:

</code></pre>

<img width="706" alt="2018-06-14 5 08 15" src="https://user-images.githubusercontent.com/1061205/41375429-0ba4a826-6f91-11e8-886f-dd1a42842d71.png">

**Comment by hLittle** [comment]
I was able to get it working in IE10 by adding 
```
(function() {
  Object.setPrototypeOf = Object.setPrototypeOf || ({__proto__: []} instanceof Array ? setProtoOf : mixinProperties);

  function setProtoOf(obj, proto) {
    obj.__proto__ = proto;
    return obj;
  }

  function mixinProperties(obj, proto) {
    for (const prop in proto) {
      if (!obj.hasOwnProperty(prop)) {
        obj[prop] = proto[prop];
      }
    }
    return obj;
  }
})();
```
To polyfills.ts (before core-js/es6) imports

**Comment by everedifice** [comment]
@hLittle Yes i know. but currently Angular didn't notice this problem to developer.

**Comment by FernandoIbaePLiborio** [comment]
@hLittle, thanks for the comment. Sorry for my ignorance, but this function only solved for angle 6 applications or earlier versions as well?

**Comment by lasimonne** [comment]
@everedifice Thanks 🔥🔥

**Comment by mhevery** [comment]
This is an RXjs issue not angular. @benlesh could you move this issue to your repo. Also we should not be using setPrototypeOf due to performance.

**Comment by jenniferfell** [comment]
Per note from @mhevery , assigned this to @benlesh 
Marked as "state: needs eng input" to indicate that it's on hold wrto Angular docs work, pending additional information or instructions from @benlesh

**Comment by mhevery** [comment]
Closing in favor of https://github.com/ReactiveX/rxjs/issues/3966

**Comment by prad9** [comment]
I have the same issue with ie11 aswell. Have used above code from @hLittle and added to polyfills.ts. It worked like a charm.
