### ISSUE TITLE
Audit dependencies for angular2 in package.json

### ISSUE THREAD

**Issue by rkirov** [angular/angular#2448]
Currently we are listing obvious dev dependencies like `gulp-insert` as runtime dependencies.

/cc @robwormald @pkozlowski-opensource

**Comment by pkozlowski-opensource** [comment]
So, I totally agree that we should be more strict about what we put in the https://github.com/angular/angular/blob/master/package.json file, but my understanding is that the package.json that gets pushed to npm is generated from https://github.com/angular/angular/blob/master/modules/angular2/package.json

**Comment by tbosch** [comment]
Yes, this is correct

**Comment by rkirov** [comment]
@pkozlowski-opensource Right, so technically the top level `package.json` can never be used as a dependency to other projectes since it is never published to npm.

The only other case where it matters would be if someone uses `jspm github:angular/angular`.

**Comment by jgw96** [comment]
Hey everyone, i would not mind taking care of this minor issue, we just need to move certain dependencies like gulp-insert from runtime dependencies to to dev dependencies in the https://github.com/angular/angular/blob/master/package.json file correct?

**Comment by jgw96** [comment]
I have never contributed to Angular before so this looks like a nice, super easy issue to start with. Ive used angularJS 1.3 and now 1.4 for about a year at work, so i have experience using AngularJS and i have messed around and done some little personal projects using Angular and am loving it even more than i love AngularJS.

**Comment by rkirov** [comment]
Go for it, make sure to read https://github.com/angular/angular/blob/master/npm-shrinkwrap.readme.md
