### ISSUE TITLE
API ref page for router function locationSyncBootstrapListener doesn't show in API index

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#24493]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ X] Other... Please describe: doc or AIO infra?
</code></pre>

## Current behavior

API index under router/upgrade lists two APIs:
- RouterUpgradeInitializer 
- setUpLocationSync

https://next.angular.io/api/router/upgrade
lists one additional API page:
https://next.angular.io/api/router/upgrade/locationSyncBootstrapListener

## Expected behavior

API index and https://next.angular.io/api/router/upgrade match in the APIs they list

## Minimal reproduction of the problem with instructions

See links above 

## What is the motivation / use case for changing the behavior?

Consistency, completeness of index

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
@petebacondarwin Do you know why this isn't showing up in the API index page? Thanks! (triaging as docs-infra or just docs)

**Comment by petebacondarwin** [comment]
No idea! I will look into it.

**Comment by petebacondarwin** [comment]
It doesn't appear in the API overview page because it is marked as `@internal`: https://github.com/angular/angular/blob/6.1.0-beta.1/packages/router/upgrade/src/upgrade.ts#L46

The fact it appears in the package (aka module) page is a bug in the template.

**Comment by jenniferfell** [comment]
@petebacondarwin Is this resolved now?

**Comment by petebacondarwin** [comment]
It is now...
