### ISSUE TITLE
Staggered Animations with Multiple Timings Using 'group' do not work in Safari

### ISSUE THREAD

**Issue by ewohlken2** [angular/angular#24490]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Child animations do not fire correctly in safari when using stagger on the parent animation, and have multiple animations on the child running using the `group` function

## Expected behavior
Animations should function correctly in all browsers (as they did in angular 5)

## Minimal reproduction of the problem with instructions
Here is a git repo that has demo's the issue, only occurs in safari: https://github.com/ewohlken2/angular-animations-safari-bug-demo

Download the repo, run ng serve, open safari and navigate to localhost:4200

While setting up the demo repo I learned that this problem does not occur using Angular 5

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by opetriienko** [comment]
Angular docs says: ```Angular animations are built on top of the standard Web Animations API and run natively on browsers that support it.```
Is there any way to turn off Web Animations API programmatically? In our application animation in iOS Safari causes unexpected behavior(starting from Angular 6).

**Comment by dylhunn** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

(The animations package has moved from CSS animations to browser animation API)
