### ISSUE TITLE
feat(change-detection): add bind-once support in templates

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2449]
@gdi2290 and I were just troubleshooting an issue related to an observable pipe always emitting a null value because the observable reference being passed into the pipe never matched the already set observable instance. This was because the template was calling a method to return an observable, causing a new observable to be created on each lifecycle tick.

```
{{ someService.getObservable() | async }}
```

It would be nice to have the same [one-time binding](https://docs.angularjs.org/guide/expression#one-time-binding) capability as AngularJS 1.x where bindings could be expressed as "bind once" inside of templates.

One option is to create a pipe to support this, where as soon as a non-undefined value is returned from the left-side, the `once` pipe would cache and keep the reference:

```
{{ someService.getObservable() | once | async }}
```

Or we could add template sugar for this.

```
{{ ::someService.getObservable() | async}}
```

**Comment by gdi2290** [comment]
I prefer using pipes over new syntax with `| once` and `| keyValueDiff` for deep check. This plays well with the idea that pipes affecting bindings and angular2 being more explicit compared to angular1 (rather than more syntax which was the workaround for angular1). Also see [json cache error](https://github.com/angular/angular/issues/2278#issuecomment-108087305) where I removed the ref cache

I also rather keep the `::` syntax for [Function bind es7 syntax](https://github.com/angular/angular/issues/1625#user-content-FunctionBind)

**Comment by eshcharc** [comment]
One feature of binding once I'm missing (and still haven't noticed in Angular 1.x) is the ability to switch the binding on and off, based on another property.
One example of usage I can think of is static labels, that should change on language switch.

**Comment by mhevery** [comment]
@vicb what do you think about this? I am thinking that we won't support this and we should close this.

**Comment by vsavkin** [comment]
Currently, we have only one use case: we create a new observable on every tick. If we store a reference to this observable in the template, the problem won't be present anymore.

It is tempting to solve all our problems by extending the template syntax, but the user already has a way to deal with it by doing `this.observable = getObservable()` in the component itself. This does not seem unreasonable. That is why, even though this is not very hard to implement, I recommend against doing this. It requires new syntax, and makes the execution model more complicated.

@jeffbcross Is there another good use case for the bind once functionality?

**Comment by ewinslow** [comment]
It's a bummer for use cases like falcor where then your model is tied to your controller again.

I suppose an alternative solution is to patch falcor to return the same promise on repeated requests to `model.getValue(path).toPromise()` for identical values of `path`, as long as the value underneath hasn't changed.

Seems like it would just be nice for users if angular handled this transparently, though.

**Comment by mhevery** [comment]
@ewinslow we are planning on having tight integration with falcor, but this is not the best way to get there.

**Comment by ewinslow** [comment]
OK well that's good to know I guess.

**Comment by shlomiassaf** [comment]
Retry...

This is a nice to have feature and one that will help a lot of people to fine tune performance without doing workarounds.

In my use case I want the user of the component to supply a function that will return a value and supply it in a declarative way (HTML).
The function needs to run in the context of the class it is written in so the most simple approach would be to supply an `@Input` property in the component and the user will bound to it.

This approach results in endless invocations of the supplied function by the change detector.
I can't prevent that. I can save a reference to the returned value inside `ngOnInit` thus making sure I have 1 value for the whole component life cycle but this does not solve the problem:  

  - The invocation will continue still.
  -  I create boilerplate by adding a private member that hold a reference to the "1st" returned value.

As I see it, One time binding is a performance tune, it should be in the hand of the component builder to decide if it is needed or not. The user of the component should decide that as it might effect other things inside the component thus it shouldn't be a syntax thing.

Trying to avoid adding new template syntax, there are several options:  

__* Setting up one time binding from metadata:__
```
@Input(true) private prop: string;
```
This create some API changes, tough not necessarily breaking but it does.
So we can:
```
@OneTime() @Input() private prop: string;
```

__* Provide binding based change detection API: __
`ChangeDetectorRef` can provide an API to `freeze` change detection for a BindingTarget.
This is a more complex scenario that allows granularity.

**Comment by no-more** [comment]
Hi,

I really miss this feature in angular2, I'm still very new in angular2 but this really trouble me and I can't see any easy way to be able to do bindonce. I have lots of use case for this, like said for translation, of in order to display lots of value in a page where no edit can be done or only some of the values.

I hope this will be implemented, or maybe I still don't understand how to handle this with change detection.

Thanks.

**Comment by metamaker** [comment]
Is it implemented?
