### ISSUE TITLE
when possible open the same page when user switches to different version

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#24495]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[X ] Other... Please describe: AIO infra
</code></pre>

## Current behavior

If I'm on a doc page, and I switch the version, the angular.io site resets to the home page for the site. It appears to happen only when I switch to a newer version, such as switch from v5->stable or stable->next. 

When I'm switching to an older version, the site resets to angular.io/docs.

## Expected behavior

If I'm on a doc page, and I switch the version from stable to next, I'd like to remain on the equivalent page in the newly-chosen version, when possible. 
Example:
start page: https://angular.io/tutorial/toh-pt1
switch to next version
new page: https://next.angular.io/tutorial/toh-pt1

When not possible, I'd like to go up to "last known good point" in the structure if possible. For example

for any guide, open angular.io/docs
for any API ref, open angular.io/api
for any tutorial page, open angular.io/tutorial
or even just always go to angular.io/docs from any guide, tutorial, or API ref page

## Minimal reproduction of the problem with instructions

Scenario 1: Moving to newer release, page exists
1. Start at stable version of a tutorial page: https://angular.io/tutorial/toh-pt1
2. From the bottom of the left nav, switch to next
Notice that you are moved to here: https://next.angular.io/
To get where I wanted to be (same content, different version), I do these things:
3. Select DOCS
4. Select Tutorial
5. Select The Hero Editor
Now I'm where I'd want to be: https://next.angular.io/tutorial/toh-pt1
6. Repeat going from v5 ( https://v5.angular.io/tutorial/toh-pt1) to stable. Same behavior. 
I'd like to end up on https://next.angular.io/tutorial/toh-pt1 or at least https://next.angular.io/docs when I switch versions. 

Scenario 2: Moving to older release, page exists
1. Start at stable version of a tutorial page: https://angular.io/tutorial/toh-pt1
2. From the bottom of the left nav, switch to v5
Notice that you are moved to here: https://v5.angular.io/docs
This is closer than scenario 1, but to get where I wanted to be (same content, different version), I still need two more steps:
4. Select Tutorial
5. Select The Hero Editor
Now I'm where I'd want to be: https://v5.angular.io/tutorial/toh-pt1. Ending up on https://next.angular.io/docs isn't too bad, but it could be better by putting me on the equivalent v5 page. 

Scenario 3: Moving to an older release, page doesn't exist
1. Start at stable version of elements page: https://angular.io/guide/elements
2. From the bottom of the left nav, switch to v5 (where elements doesn't exist)
Notice that you are moved to here: https://v5.angular.io/docs
That's fine. Because elements doesn't exist in v5, that's as close as we can get. 

## What is the motivation / use case for changing the behavior?

Faster navigation to the right place when reader switches versions.
Easier to compare "it was this way in v5, how does it work in v6?"

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sonukapoor** [comment]
@petebacondarwin I can help with this. Can you please assign it to me? Thanks
]
