### ISSUE TITLE
Compile error using TypeScript "ReturnType"

### ISSUE THREAD

**Issue by jmagaram** [angular/angular#24499]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Create a brand new Angular app. Open in VS Code. Compiles and works fine. Add the following legal TypeScript to a new .ts file in the app folder.

    const f = () => 'abc';
    type T = ReturnType<typeof f>;

Run `npm build`. Error I receive is `error TS2304: Cannot find name 'ReturnType'. Works fine in an old create-react-app project. The VS Code editor is happy with the code (no red squigglies) but the build process isn't. The status bar shows using TypeScript 2.91.

## Expected behavior

No build error.

## Minimal reproduction of the problem with instructions

ng new ang-app
cd ang-app
ng serve --open

VS Code 1.24
Open folder ang-app
Run build task - no problems

In the app folder, add a file rt.ts with code as shown above
npm build
Error as described above

## What is the motivation / use case for changing the behavior?

ReturnType is useful for generating strongly-typed actions (like Redux) with less boilerplate.

## Environment

<pre><code>
Angular version: 6.03 

Browser:
n/a
 
For Tooling issues:
- Node version: 5.60
- Platform:  Windows 10
- VS Code 1.24

Others:

</code></pre>

**Comment by jmagaram** [comment]
Did `npm install -g typescript` and then `tsc --version` and it shows `2.9.2`. Restarted VS Code. Same problem.

**Comment by jmagaram** [comment]
I think the features I want are part of TypeScript 2.8. I have installed the latest TypeScript as described above. Within VS Code when I'm editing a TypeScript file I see in the status bar below 2.9.2. If I click on it I get a choice of whether to use VS Code's version 2.9.2 or the workspace version 2.7.2, which is in the node/modules folder. I've chosen the more recent version.

**Comment by jmagaram** [comment]
Just found this StackOverflow [comment](https://stackoverflow.com/questions/50707956/how-to-build-with-angular-cli-6-using-typescript-2-8-x)

If you want to use TS 2.8 you need to use cli version 6.1.0-beta.0

**Comment by jmagaram** [comment]
Duplicate of #23779

**Comment by sandeep2** [comment]
What fixed this issue for you ?
