### ISSUE TITLE
docs: API list filtered with status=stable shows nothing for decorators 

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#24496]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ X] Other... Please describe: AIO infra
</code></pre>

## Current behavior

Follow on to issue #24329. Problem appears fixed for all types except decorator. If I set the filters to type: @decorator and status: stable, I get no results. 

## Expected behavior

See @decorators like other types. 

## Minimal reproduction of the problem with instructions

https://angular.io/api?status=stable&type=decorator

## What is the motivation / use case for changing the behavior?

To not hide the things

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
I can see all decorators :/

**Comment by jenniferfell** [comment]
@gkalpak Agree. Looks like the issue has been resolved. I can see clearly now.
The following filter setting correctly lists all decorators: 
https://angular.io/api?status=stable&type=decorator
