### ISSUE TITLE
How to add a Sandbox attribute to angular in iframe

### ISSUE THREAD

**Issue by rahulrsingh09** [angular/angular#24504]
Is there a snadbox attribute that we can add to iframes in Angular as it seems to not work when using it like this .

```
<iframe #iframe sandbox=""></iframe>


  ngOnInit(){
    let content = '<script>console.log(window.document);</script>'; // still able to access this which should not be the case
    let doc =  this.iframe.nativeElement.contentDocument || this.iframe.nativeElement.contentWindow;
    doc.open();
    doc.write(content);
    doc.close();
  }

```

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by rahulrsingh09** [comment]
@ericmartinezr Can you please give some hints on this as SO also has no clue and they downvote , it would be great if you could

**Comment by trotyl** [comment]
See https://github.com/angular/angular/issues/18909#issuecomment-325766459

Angular will mount the element first before adding attributes (in current implementation). If you want to assign attributes before mounting the element, better to use imperative codes.

**Comment by rahulrsingh09** [comment]
@trotyl can you give a small example it would be great on how to have it in this context

**Comment by alexeagle** [comment]
Closing the issue as we don't handle support requests here, sorry.
