### ISSUE TITLE
{{3.1*9}} shows 27.900000000000002

### ISSUE THREAD

**Issue by Neaco** [angular/angular#24502]
## I'm submitting a...

<pre><code>
[X] Bug report  
</code></pre>

## Current behavior

{{3.1 * 9 }} shows 27.900000000000002 for some reason.

The multiplication of doubles sometimes has weird values.

I am using kendo-ui but I could reproduce it on plnkr without it.

## Minimal reproduction of the problem with instructions

https://next.plnkr.co/edit/MPrObSRarEeEAqwJ

**Comment by pkozlowski-opensource** [comment]
Try `3.1 * 9` in your favourite browser console...

In short:
* this is how numbers are represented in JS....
* has nothing to do with Angular (or any other framework)

**Comment by Neaco** [comment]
I see, sorry for not testing that in vanilla JS. I was in a hurry and didn't proof check. 
I didn't know about the number thing on JS.
Thanks for the answer.
