### ISSUE TITLE
Providing of Title service not necessary

### ISSUE THREAD

**Issue by mofogasy** [angular/angular#24501]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
The guide describing the Title service states that the service has to be injected in the AppModule (see https://angular.io/guide/set-document-title). This is wrong, since the Title service is already provided in the BrowserModule (see https://angular.io/api/platform-browser/BrowserModule)

## Expected behavior
Update the code in section "Use the Title service" and remove the section "Why provide the Title service in bootstrap" altogether.

**Comment by jenniferfell** [comment]
Thanks for submitting this issue. I notice that https://angular.io/guide/set-document-title isn't in the doc navigation, so I wonder if someone intended to remove it entirely. I'll investigate.

**Comment by atscott** [comment]
Closing as obsolete.  The guide does not mention injecting into AppModule
