### ISSUE TITLE
The filter/pipe doesn't work after the content it applied to changed

### ISSUE THREAD

**Issue by ddwolf** [angular/angular#24505]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am applying a filter to an array, which was displayed on the page by ngFor iteratation, it works fine, until I dynamically added another item to that array, the new iterm was not displayed, and I think(and I confirmed) that the filter was not triggered at all.

## Expected behavior

The filter should work again after the content it applied to changed.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-qlbgvm

<pre><code>
Angular version: 5 and 6

Browser:
- [x] Chrome (desktop) version 66
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 </code></pre>

**Comment by jnizet** [comment]
You can also check why there is no filter pipe in the framework, and why it's a bad idea to use one: https://angular.io/guide/pipes#appendix-no-filterpipe-or-orderbypipe

**Comment by ddwolf** [comment]
Thks all you guys, I 'll choose the impure one, because My app is simple and , that way is much simple:)
