### ISSUE TITLE
@angular/elements: add support for programmatic access to content projection

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#24509]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I would like to have some way how to do *"templating"* in custom elements and processing html content or elements defined as `ContentChild` or `ContentChildren` for `Component` defined as *custom element*. For example i have grid component that gathers metadata from its content. I would like to convert it to *custom elements*.  Another possibility is i would like to have "custom template" for my component.

## Expected behavior

I dont know how is this done in *custom elements* but i think it is possible somehow. I would like to have possibility to work with *templates* and `ContentChild`, `ContentChildren` same way as it is used in Angular.

## Environment

<pre><code>
Angular version: 6.0.3

Browser: All
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.4.0
- Platform:  Windows

Others:

</code></pre>

**Comment by fr0** [comment]
Is there any chance of this happening before Ivy? This is a critical feature for those of us who are wanting to expose complex custom components written in Angular via WebComponents (on the order of the Angular Material tab control).

**Comment by antch** [comment]
This is a huge blocker for many usages of elements as ShadomDom just isn't well-supported enough, besides the fact that the complete encapsulation of the `slot` makes it not suitable for all scenarios.

Is there any sort of workaround possible, even if it requires plugging in custom code?

**Comment by antch** [comment]
Also, it appears that if you include HTML inside of your custom element tag, it gets output as a part of the element's output, but not in a way where you can see the nodes after `ngOnInit`, `ngAfterViewInit`, or `ngAfterContentInit` so quite inconsistent and confusing...

**Comment by kukjevov** [comment]
Any news here @alexeagle @andrewseguin ?

It would be nice, to be able create or represent `TemplateRef` as function which takes context and returns *HTML*, because otherwise I don`t know how to create template in plain javascript without this. This would allow us to use plain javascript, or handlebars or whatever to create dynamic template outside of angular. But currently it is not possible to create `TemplateRef` without angular since it cant be constructed from function or something similar.

Thanks

**Comment by gkalpak** [comment]
Thank you for submitting this feature request. We reviewed it and decided not to move forward with it at this time.

Content queries will not work for content outside the Angular app with our current implementation of content projection.
We intend to revisit the content projection implementation as a whole at some point and potentially more closely align it with "native" content projection (via `<slot>` elements), which will also allow content projection to work more seamlessly for Angular Elements.

**Comment by darkguy2008** [comment]
> Thank you for submitting this feature request. We reviewed it and decided not to move forward with it at this time.
> 
> Content queries will not work for content outside the Angular app with our current implementation of content projection.
> We intend to revisit the content projection implementation as a whole at some point and potentially more closely align it with "native" content projection (via `<slot>` elements), which will also allow content projection to work more seamlessly for Angular Elements.

When are you guys moving on with this request then? I've been struggling a lot trying to retrieve the elements within my web component's <ng-content> without avail. Angular is good as long as you make your entire app/framework around it, but when you want to extend it to play nice with other use-cases all we get is a brick wall, painted with "let's vote" and then "nope, not enough votes, won't do".

**Comment by gkalpak** [comment]
There is no specific timeframe atm. As much as we'd like to be able to address all issues, we have limited resources and a lot of things in the pipeline already 😞
So, we have to prioritize our work. We capture the main areas/efforts we are currently focusing on in [our roadmap][1] if you want to know more.

[1]: https://angular.io/guide/roadmap
