### ISSUE TITLE
falsy maxLength on input makes input uneditable

### ISSUE THREAD

**Issue by JounQin** [angular/angular#24503]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
- [ ] Other... Please describe:

## Current behavior

As title

## Expected behavior

`null/undefined/false` for `maxLength` should be ignored rather than converting it to be `0`

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-bxsghq?file=src%2Fapp%2Fapp.component.ts

## What is the motivation / use case for changing the behavior?

`maxLength` should be ignorable

## Environment

Angular version: 6.0.0

Browser:
- [x] Chrome (desktop) version 67.0.3396.87
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

**Comment by trotyl** [comment]
> `null/undefined/false` for `maxLength` should be ignored rather than converting it to be `0`

It has nothing to do with Angular, just how DOM works: http://jsbin.com/xefelew/edit?html,js,output

**Comment by alexeagle** [comment]
Thanks @trotyl sounds like working as intended to me.
