### ISSUE TITLE
"Buffer is not defined" Error When Porting To Angular 6

### ISSUE THREAD

**Issue by pointtoken** [angular/angular#24517]
## I'm submitting a...
X Regression (a behavior that used to work and stopped working in a new release)

## Current behavior
When attempting to use a package that expects Buffer to be globally available, the call fails.

## Expected behavior
Dependent packages should be able to access the global Buffer object

## Minimal reproduction of the problem with instructions
1.  Create a barebones Angular 6 project. Attempt to access the Buffer object.
## Environment

Angular version: 6.0.5

Browser:
 Chrome (desktop) version XX

Others:
There is some discussion of this issue here: https://stackoverflow.com/questions/50371593/angular-6-uncaught-referenceerror-buffer-is-not-defined/50377270#50377270 but the workaround of adding 

<pre><code>
global.Buffer = global.Buffer || require('buffer').Buffer;
</code></pre>to polyfills.ts causes intermittent compiler errors.

**Comment by alexeagle** [comment]
what's the compiler error from the workaround? that's surprising that it only fails to compile intermittently.

**Comment by alexeagle** [comment]
Also, I suspect this issue is outside of Angular, it's not our job to provide general node polyfills. Are you saying this worked with an earlier version of Angular (which one?) and not with 6.0.5?

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/1548. Not an Angular issue.

**Comment by pointtoken** [comment]
@trotyl  thanks for the lead on this. Ultimately, I had to use the patch as described here: https://gist.github.com/niespodd/1fa82da6f8c901d1c33d2fcbb762947d

**Comment by raxim1** [comment]
suck my dick on all the negative comments - my project is gone, thanks Angular team.
