### ISSUE TITLE
HttpClient retry not working.

### ISSUE THREAD

**Issue by workfel** [angular/angular#24516]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Hello, i want to implement retry request on my application but when it try it, i have a infinite loop of my request.[http://www.syntaxsuccess.com/viewarticle/retrying-http-requests-with-rxjs](http://www.syntaxsuccess.com/viewarticle/retrying-http-requests-with-rxjs)
```js
return this.http
                .get(this.url)
                .retry(5);
```

Or 
```js
this.http
    .get(this.url)
    .retryWhen(error => {
               return error
                  .flatMap((error: any) => {
                     if(error.status  === 503) {
                       return Observable.of(error.status).delay(1000)
                     }
                     return Observable.throw({error: 'No retry'});
                  })
                  .take(5)
                  .concat(Observable.throw({error: 'Sorry, there was an error (after 5 retries)'}));
               });
```

When i tried this 2 options, i have always a infinite loop when an errors happen.

## Environment

<pre><code>
Angular version: 5.2.11
Rxjs : 5.5.11

Browser:
- [x] Chrome (desktop) version XX
 
For Tooling issues:
- Node version: 8.9.4
- Platform: Mac

Thx

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
