### ISSUE TITLE
Lazy loading a library fails for non-aot builds

### ISSUE THREAD

**Issue by totkeks** [angular/angular#24519]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Error returned on `ng build`
`ERROR in ./dist/my-lib/my-lib.d.ts
Module build failed: Error: C:\Git\playground\ng6-lib-import\dist\my-lib\my-lib.d.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Git\playground\ng6-lib-import\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:709:23)
    at plugin.done.then (C:\Git\playground\ng6-lib-import\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

## Expected behavior
No error on `ng build` like with `ng build --aot`

## Minimal reproduction of the problem with instructions
Use my repository https://github.com/totkeks/ng6-lib-import/tree/bug/lazy-load-lib which contains a basic angular6 app and a basic library (my-lib) on the master branch and this bug on the bug/lazy-load-lib branch.

Run the following commands
- `npm install`
- `ng build my-lib`
- `ng build`

The additional routing steps can be seen in the last commits on this branch. Basically the my-lib module got a simple route to the my-lib component and the main app is now lazily loading the my-lib module. 

## What is the motivation / use case for changing the behavior?
We want to use both the new library project feature from angular 6 and lazy loading routes in our application. The former to split our development into multiple domain libraries and the latter to reduce page loading times and performance.

## Environment
<pre><code>
Angular CLI: 6.0.8
Node: 8.11.2
OS: win32 x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-ng-packagr   0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.6.8
@angular/cli                       6.0.8
@angular/router                    6.0.5
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.8
@schematics/angular                0.6.8
@schematics/update                 0.6.8
ng-packagr                         3.0.1
rxjs                               6.2.0
typescript                         2.7.2
webpack                            4.8.3
</code></pre>

**Comment by jasonaden** [comment]
Please provide an actual reproduction for this issue. It sounds like there's some configuration problem here which might be obvious to fix with a repro provided.

**Comment by totkeks** [comment]
@jasonaden I'm not entirely sure, what you mean by actual reproduction, because that's the reason I created this new repository linked in the issue, which only does the simplest steps needed to reproduce the error using the angular cli. But let me try to put the steps into words:

1. create new angular app with `ng new` which includes a routing module
2. create new library project with `ng generate library <my-library>` (https://github.com/angular/angular-cli/wiki/stories-create-library)
3. add child routing to the library with `RoutingModule.forChild(<simple route to component here>)`
4. switch main app routing to lazy loading and reference the main module from the library project
5. build library with `ng build <my-library>`
6. build or serve main app with `ng serve` or `ng build`, but do **not** set `--aot`
7. error occurs
8. build or serve main app with `--aot`
9. error does not occur

Hope this helps. Also see the issue referenced above which describes the same problem.

**Comment by jasonaden** [comment]
@totkeks My apologies. I saw that link and thought it was a library you are developing, not a repo to clone. Thanks for the repro and steps!

**Comment by mhevery** [comment]
I am unable to reproduce the issue. If it is still an issue, can you update the repro steps to the latest version and re-open.
