### ISSUE TITLE
ngTemplateOutlet modifies its initial context when getting a new context whose shape is the same

### ISSUE THREAD

**Issue by divdavem** [angular/angular#24515]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
ngTemplateOutlet modifies the previous context when getting a new context whose shape is the same.

## Expected behavior
ngTemplateOutlet should not change its context parameters in any case.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-ymixqh?file=src%2Fapp%2Fapp.component.ts

Click on "Swap". The contexts of the ngTemplateOutlets directives are swapped.
We should see "name = context 2" on the first line and "name = context 1" on the second line, but both lines show "name = context 2". The first ngTemplateOutlet has changed the `name` property of the first context when receiving the second context.

Note that the problem does not happen if the contexts do not have exactly the same set of properties (for example, when adding "foo: true" in the first context but not in the second, the behavior of ngTemplateOutlet is correct).

## What is the motivation / use case for changing the behavior?
It is clearly a bug. It is confusing.

## Environment

<pre><code>
Angular version: 6.0.0

Browser: all

</code></pre>

**Comment by mhevery** [comment]
I suspect this code is wrong: https://github.com/angular/angular/blob/master/packages/common/src/directives/ng_template_outlet.ts#L74-L93

**Comment by waterplea** [comment]
I got my static constants with some never changing content mutated by this and whole app got messed up by just using ngTemplateOutlet, built in trusted directive. Cannot believe this got no traction for a year, please do something about it. I understand the idea of optimizing it so it doesn't recreate the view, but this is just shocking to find.
