### ISSUE TITLE
angularCompilerOptions `genDir` is breaking

### ISSUE THREAD

**Issue by dinony** [angular/angular#24535]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The [`genDir`](https://github.com/angular/angular/blob/master/packages/compiler-cli/src/transformers/api.ts#L51) option is marked as deprecated but is also breaking. It has no effect anymore (?), as denoted in the comment.

## Expected behavior

When something is deprecated, I would assume that it is deprecated, but still working.

## Minimal reproduction of the problem with instructions

Just try to compile with the following tsconfig using v4 and v5+ compiler.

```json
{
  "compilerOptions": "{{your compiler options}}",
  "include": ["{{your files}}"],
  "angularCompilerOptions": {
    "genDir": "aot",
    "skipMetadataEmit" : true
  }
}
```

## What is the motivation / use case for changing the behavior?

Everybody would know that `genDir`is deprecated, but still working - so they know in advance and adapt accordingly.

**Comment by mhevery** [comment]
There is a technical reason why we could not make it work, but now I can't remember.  @alxhub  Do you remember?

**Comment by dinony** [comment]
:D
