### ISSUE TITLE
Error: ENOENT: no such file or directory, open ...

### ISSUE THREAD

**Issue by witosmartyn** [angular/angular#24532]
[X] Bug report  

## Current behavior
when i create new project with CLI 
**`ng new myApp`**
and install js librarry  with command :
**`npm install jquery  -p`** 
 npm install it succsessfully(exist in /node_modules)
I add  this section to angular.json in project folder
**`
"scripts": [
  "../node_modules/jquery/dist/jquery.js"
],
`** 
and  then I start the project with command **ng serve  i**
i have this error:
 **`## 91% additional asset processing scripts-webpack-plugin✖ ｢wdm｣: Error: ENOENT: no such file or directory, open '/Volumes/HSSD/projects/JS/Angular/ng5/node_modules/jquery/dist/jquery.js`**
## Expected behavior
The server should start and the js library should be connected to the main page

## Minimal reproduction of the problem with instructions
ng new myApp 
cd myApp
npm install jquery -p
add this section to angular.json
"scripts": [ "../node_modules/jquery/dist/jquery.js", ],
ng serve

## Environment
CLI 6.0.8
Angular version: 6.0.5

Browser:
- [X] Chrome (desktop) version XX
For Tooling issues:
- Node version: 8.11.2
- Platform:  MAC

**Comment by splincode** [comment]
add the demo repository right away

**Comment by splincode** [comment]
https://github.com/angular/angular-cli/issues/9438

**Comment by witosmartyn** [comment]
And this is established.Considering that `angular.json` is at a level higher than `'src' `and `node_modules` then `../` is redundant, I have everything compiled without `../`
Even CLI generated a project with a connected `src/styles.css`
Why, then, is everyone advised to add `../` ?
Some confusion

**Comment by pkozlowski-opensource** [comment]
This issue belongs to https://github.com/angular/angular-cli

**Comment by pfiterman** [comment]
@witosmartyn thanks! solve my problem!

**Comment by Sakthivel26** [comment]
@witosmartyn thanks ! this solve my problem also... once again thanks.

**Comment by marquinmpfs** [comment]
@witosmartyn  Tks, you solve my problem.

**Comment by frenchy321** [comment]
Sorted, thank you !
