### ISSUE TITLE
route problem

### ISSUE THREAD

**Issue by joebnb** [angular/angular#2453]
```
http://localhost/projectocean/src/web/#/open#id=414124211
```
if i use 
$rootScope.$on('$routeChangeStart',function(evt,next,current){
    next.originalpath == condition
}
to check permission and jump url it,the angular js will prevent this,because the id is random,i think angular shoud let the route just match the first #

**Comment by gdi2290** [comment]
this is the angular2 repo. angular1 is here https://github.com/angular/angular.js
could you close this
