### ISSUE TITLE
What is the minimum version of firefox browser that supports angular2, angular3, angular4, angular5 and angular6. Is the minimum browser support information provided by Google any where?

### ISSUE THREAD

**Issue by gkswargam** [angular/angular#24531]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jotatoledo** [comment]
The issue tracker is not the right place for general questions.

**Comment by splincode** [comment]
@gkswargam https://angular.io/guide/browser-support

**Comment by pkozlowski-opensource** [comment]
@splincode is right (thnx!), it is documented at  https://angular.io/guide/browser-support

**Comment by ThomasSchellenbergNextCentury** [comment]
This is actually not documented in the link above right now.  Did the documentation on the minimum supported browser versions move?

**Comment by thomasbee** [comment]
The answer given by @pkozlowski-opensource is incorrect. The mentioned link only documents that the latest version of Firefox is supported. That is not helpful. Please reopen the ticket to provide an answer to the question asked.
