### ISSUE TITLE
Non exported parent class will not compile properly with AOT

### ISSUE THREAD

**Issue by jsgoupil** [angular/angular#24543]
## I'm submitting a...

<pre><code>[X] Bug report 
</code></pre>

## Current behavior
    function View_DynamicComponent_0(_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵvid"](2, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵand"](0, [["container", 2]], null, 0, null, View_DynamicComponent_1))], null, null); }

## Expected behavior
    function View_DynamicComponent_0(_l) { return _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵvid"](2, [_angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵqud"](402653184, 1, { container: 0 }), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵand"](16777216, [[1, 3], ["container", 2]], null, 0, null, View_DynamicComponent_1))], null, null); }

## Minimal reproduction of the problem with instructions
    /*export*/ class DynamicComponentBase {
      @ViewChild('container', { read: ViewContainerRef })
      container: ViewContainerRef;
    }

    @Component({
      selector: 'tn-dynamic',
      template: `<ng-template #container></ng-template>`,
      changeDetection: ChangeDetectionStrategy.OnPush
    })
    export class DynamicComponent extends DynamicComponentBase {
    }

By not including the `export` keyword, the AOT compiler will output something different than if it were created with the `export`. This error took me about 8h to figure out since there are no warning, no errors, AOT only.

The compiler should either output an error/warning, or work properly.

## Environment

<pre><code>
Angular version: 6.0.4
 
For Tooling issues:
- Node version:  8.11.2 
- Angular tooling: 6.0.8
- Platform: Windows 

</code></pre>

**Comment by mhevery** [comment]
Actually this is working as intended. If it is not exported it is impossible for the generated code to imported hence it does not work.

**Comment by jsgoupil** [comment]
@mhevery @jasoneden
What about a compilation error... this is failing at runtime. It is so complicated to catch such error... I had to debug a compiler output to actually understand what was going on. The vast majority of people will NOT do that and will wonder what is happenong.

**Comment by mhevery** [comment]
The whole thing will become non-issue with Ivy, so we will not be investing any time into fixing it, rather focus on delivering ivy faster.
