### ISSUE TITLE
bug(animation): Animating calc() fails in IE11 / Edge

### ISSUE THREAD

**Issue by macjohnny** [angular/angular#24545]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Here is an example using Angular animations to animate the transition from `min-width: 100%` to `min-width: calc(100% + 32px)`: [https://stackblitz.com/edit/angular-gitter-v3xmvv](https://stackblitz.com/edit/angular-gitter-v3xmvv?file=app%2Fapp.component.ts)
It works correctly in Chrome, but it does not work in IE.
This also happens when starting with an initial state of `min-width: calc(100%)`.

Animating from e.g. `min-width: 100%` to `min-width: 110%` works in both, Chrome and IE.
Nevertheless, animating from `min-width: 100%` to `min-width: calc(110%)` fails in IE.

It seems that this is rather a bug in the angular animations itself, since e.g. `web-animations-js` can handle the transition from `min-width: 100%` to `min-width: calc(100% + 32px)` correctly, see this [codepen example](https://codepen.io/macjohnny-zh/pen/gKGEWb), which works correctly in IE11.

This happens for both, with and without `import 'web-animations-js';`

This causes the following issue: https://github.com/angular/material2/issues/11642

See also the discussion in https://github.com/angular/material2/pull/11801 

## Expected behavior
It should animate the transitions correctly

## Minimal reproduction of the problem with instructions
[https://stackblitz.com/edit/angular-gitter-v3xmvv](https://stackblitz.com/edit/angular-gitter-v3xmvv?file=app%2Fapp.component.ts)

## Environment

<pre><code>
Angular version: 6.0.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [x] Edge version latest

**Comment by macjohnny** [comment]
maybe this is related to the fact that css-based animation of `min-width` in IE does not work either (it works in chrome, however):
[https://codepen.io/macjohnny-zh/pen/RJLOWG](https://codepen.io/macjohnny-zh/pen/RJLOWG)

**Comment by macjohnny** [comment]
@matsko this also happens in edge and also affects the material select, see #14444

**Comment by AdemHodzic** [comment]
This also happens when you using transfroms. E.g. 
```transfrom: translateX(calc(50% - 100px)); ``` will not work in ie11 (not sure about Edge). Luckily, there is workaround:
Instead of ```transfrom: translateX(calc(50% - 100px));```
You need to write ```transfrom: translateX(50%) tanslateX(-100px);```

**Comment by jessicajaniuk** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
