### ISSUE TITLE
Reactive forms : Conditional Required field how can i manage

### ISSUE THREAD

**Issue by ravindralande** [angular/angular#24544]
I am set ***ngIf="false"** on element as like - 

<pre>
               <textarea *ngIf="false" id="description" 
                            autocomplete="description" 
                            class="form-control" 
                            formControlName="description">
                     </textarea>
                 <div class="lw-error"  *ngIf="productForm.get('description').hasError('required')">
                                Required
                  </div>
</pre>

It's required field , but i am hide it conditionally from dom..??

Defined validation in related component... which is
<pre>
            description: ['',
                [
                    Validators.required,
                    Validators.minLength(10)
                ]
            ]
</pre>

now this form STATUS always invalid why.....????

**Comment by MikeSaprykin** [comment]
Hey, @ravindralande!
The control is always there in the component and it's value is empty - so it is invalid. 
Reactive form controls don't depend on DOM elements existence. 
To make it work like you want you need to set this control disabled. This will remove this control from the form group and it will be valid. Once you need to bring it back - set this control enabled.

Hope this will help ;-)

**Comment by BenevidesLecontes** [comment]
Or you can always remove the validator and set again with `setValidators` and `clearValidators`.

**Comment by dominique-mueller** [comment]
Instead of directly manipulating the DOM, start with the reactive form: Disable the control using the `.disable()` function, thus disabling the validation and removing the form control value from the form value. Now you can bind the `*ngIf` or `[hidden]` to the form control disabled state, e.g. by writing `*ngIf="this.form.get( ... ).enabled"`. This way, you can change the reactive form state and the UI state will always follow.

Nevertheless, this is probably a good question for StackOverflow ...

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
