### ISSUE TITLE
Layout bug in angular documentation on snack bar

### ISSUE THREAD

**Issue by angelitasasmita** [angular/angular#24550]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

at https://material.angular.io/components/snack-bar/examples
when using pink-dark theme, if i'm moving from TS to CSS page, theme changes to the default blue theme

## Expected behavior

theme should stay as the pink-dark theme

## Minimal reproduction of the problem with instructions
+ go to https://material.angular.io/components/snack-bar/examples using pink-dark theme
+ from TS tab go to CSS tab

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by gkalpak** [comment]
This is an issue for the Angular Material repo.
Please open on https://github.com/angular/material2.

**Comment by gkalpak** [comment]
I know :wink:
Angular Material docs issues are also tracked on the Angular Material repo (the content and tools live on there).
