### ISSUE TITLE
[Bug] angular/elements: Failed to construct 'HTMLElement': Please use the 'new' operator

### ISSUE THREAD

**Issue by rinukkusu** [angular/angular#24556]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
We're using `@angular/elements` to create a custom element, which we want to embed elsewhere in our non-angular projects. Since the **Chrome Version 67.0.3396.87**, we get an error in the console 

```
Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at NgElementImpl.NgElement [as constructor] (elements.js:391)
    at new NgElementImpl (elements.js:427)
    at new AppModule (app.module.ts:28)
    at _createClass (core.js:8116)
    at _createProviderInstance$1 (core.js:8088)
    at initNgModule (core.js:8024)
    at new NgModuleRef_ (core.js:8747)
    at createNgModuleRef (core.js:8736)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:10561)
    at NgModuleFactory_.push../node_modules/@angular/core/fesm5/core.js.NgModuleFactory_.create (core.js:11263)
```

![image](https://user-images.githubusercontent.com/804848/41526139-86a387cc-72e3-11e8-8107-82e420945fb2.png)

## Expected behavior
Our compilation target was and is **ES5**, which did work in **Chrome Version 66.x** and also does work in all other major browsers.

## Minimal reproduction of the problem with instructions

Use an Angular Elements project in the newest Chrome browser.

## Environment

<pre><code>
Angular version: 6.0.5

  "dependencies": {
    "@angular/animations": "^6.0.5",
    "@angular/common": "^6.0.5",
    "@angular/compiler": "^6.0.5",
    "@angular/core": "^6.0.5",
    "@angular/elements": "^6.0.5",
    "@angular/forms": "^6.0.5",
    "@angular/http": "^6.0.5",
    "@angular/platform-browser": "^6.0.5",
    "@angular/platform-browser-dynamic": "^6.0.5",
    "@angular/router": "^6.0.5",
    "@webcomponents/custom-elements": "^1.1.1",
    "@webcomponents/webcomponentsjs": "^2.0.0",
    "bootstrap": "^4.1.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.4",
    "document-register-element": "^1.7.2",
    "moment": "^2.22.2",
    "ngx-bootstrap": "^3.0.0",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  },

Browser:
- [x] Chrome (desktop) version 67

</code></pre>

**Comment by rinukkusu** [comment]
@ericmartinezr Pinning `document-register-element` to `1.8.1` indeed solved the problem here. Thanks for the heads up!

**Comment by jessndaa** [comment]
Hi, I have solved this issue by changing the "target":"es5" in the tsconfig.json to "target":"es2015"
these is my tsconfig.json file
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}```

**Comment by rinukkusu** [comment]
Yes, that's what we saw as well, but we need it to work in IE, which doesn't support es5, sadly :(

**Comment by playground** [comment]
For a single component, it works fine for me.  But getting the same errors when there are nested child components.

**Comment by richnologies** [comment]
We solve this issue by adding the package before any other script: 

<script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.0.3/custom-elements-es5-adapter.js"></script>

No need to change the target to es2015.

**Comment by CaiqueCardoso19** [comment]
Hello guys,

I have same problem.

@jessndaa solution works if you don't need run yout application in IE11.

The solution that works for me was:

- upgrade `document-register-element` to `1.8.1` 

- set my target to es5 like this:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
``` 

- remove `encapsulation: ViewEncapsulation.Native` from component notation (this does not works in IE11 without ShadowDOM polyfill).

It works and compile a simple component with @input and @output notations in Chrome 47+ and IE11. 
I hope to help them.

**Comment by railsstudent** [comment]
@CaiqueCardoso19  What is the shadowDOM polyfill you use? I cannot get angular element working in browser that is not Chrome. Thanks.

**Comment by CaiqueCardoso19** [comment]
@railsstudent I've used @webcomponentsjs following Angular's docs: https://www.webcomponents.org/polyfills

But, it not working in IE11. Only works if i remove `encapsulation: ViewEncapsulation`.

**Comment by railsstudent** [comment]
@CaiqueCardoso19  Do I npm install webcomponents/webcomponentsjs first? Then add "node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js" in scripts array in angular.json file?  Thanks.

I have a presentation on angular element in meetup this Friday evening and would like to solve the shadow polyfill issue.  Thanks.

**Comment by tbhatti** [comment]
@rinukkusu In tsconfig.json file, update "target": "es2015", previously it's "target": "es5"

**Comment by TriBasilOdrs** [comment]
working solution in index.html:
<body>
  <app-root></app-root>
  <script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.1.3/custom-elements-es5-adapter.js"></script>
</body>

**Comment by ChrisTheButcher** [comment]
Add this to your `polyfills.ts` on the bottom of your file
```
/***************************************************************************************************
 * APPLICATION IMPORTS
 */
import '@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js'; 
```

make sure to have the module installed with `npm install @webcomponents/webcomponentsjs --save-dev`

**Comment by SetTrend** [comment]
@ChrisTheButcher: Shouldn't the NPM option rather be `--save`? Or isn't this file required when the solution gets distributed?

**Comment by davidenke** [comment]
@SetTrend you're right, it is needed at runtime, so it shoud be in `dependencies` rather than `devDependencies`.

**Comment by RobinDeBock** [comment]
> Add this to your `polyfills.ts` on the bottom of your file
> 
> ```
> /***************************************************************************************************
>  * APPLICATION IMPORTS
>  */
> import '@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js'; 
> ```
> make sure to have the module installed with `npm install @webcomponents/webcomponentsjs --save-dev`

This works, thanks a lot!

**Comment by aashkashah** [comment]
@ChrisTheButcher Great clean solution. Thanks a lot for sharing

**Comment by webmozart** [comment]
I used @ChrisTheButcher's solution, but now my tests on PhantomJS report:

```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Unexpected token 'const'
  at http://localhost:9876/_karma_webpack_/polyfills.js:131:0

PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Unexpected token 'const'
  at http://localhost:9876/_karma_webpack_/polyfills.js:131:0
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  ReferenceError: Can't find variable: Promise
  at http://localhost:9876/_karma_webpack_/vendor.js:41470:22

PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  ReferenceError: Can't find variable: Promise
  at http://localhost:9876/_karma_webpack_/vendor.js:41470:22
```

Anyone had/fixed this problem?

**Comment by javaland235** [comment]
the following solved my issue:
first do the following
npm install @webcomponents/custom-elements --save

after that in the polyfills.ts add the following imports
import '@webcomponents/custom-elements/src/native-shim';
import '@webcomponents/custom-elements/custom-elements.min';

**Comment by AndrWeisR** [comment]
> 
> 
> @ChrisTheButcher: Shouldn't the NPM option rather be `--save`? Or isn't this file required when the solution gets distributed?

It worked OK at runtime for me with --save-dev, which makes sense if the module is only used to generate a polyfill at build time.

**Comment by rudolfolah** [comment]
For Angular 8, it looks like es2015 is the default and it seems to work? it was only when I used es5 as a target for the TypeScript compiler configuration that I would see this error.

**Comment by rudolfolah** [comment]
The solution that some are using here is to simply use another library that isn't document-register-element. However the official angular/elements package continues to use document-register-element so it isn't a very good solution.

I have tracked down the issue to a particular version of document-register-element, the last working version was 1.8.1, the package version suggests using 1.7.2 and above. A proper fix will probably be made in document-register-element though for the time being I would suggest angular/element's schematics change the required version from `^1.7.2` to `>=1.7.2 <=1.8.1` until the issue in the upstream library is fixed.
