### ISSUE TITLE
Dynamic calling Injector.create is not injecting deps dependencies.

### ISSUE THREAD

**Issue by sunnyyadav100** [angular/angular#24553]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Gives error:
Error: StaticInjectorError[DynamicCreatedComponent -> InjectionToken A_SERVICE -> HttpClient]: 
  NullInjectorError: No provider for HttpClient!

Or any other injected service from deps property.

## Expected behavior

Deps dependencies should get injected.

## Minimal reproduction of the problem with instructions

*MINIMAL DEMO*
https://stackblitz.com/edit/angular-fzajt8?file=src%2Fapp%2Fdynamic-service.ts

## Environment

<pre><code>
Angular version: X.Y.Z

Angular v6.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sunnyyadav100** [comment]
After debugging here it is depRecord.token is undefined
<img width="1355" alt="screen shot 2018-06-17 at 9 40 49 pm" src="https://user-images.githubusercontent.com/9139037/41509864-524ab6c8-7278-11e8-888b-2b66260d3dfc.png">

**Comment by Toxicable** [comment]
Why are you creating a new Injector? just use the parent

**Comment by sunnyyadav100** [comment]
@Toxicable Thanks!. Yes after passing parent injector in Injector.create, deps array dependency are resolved.

As per your suggestion, how do I inject token based service using parent injector?

**Comment by sunnyyadav100** [comment]
This is not a bug, as by passing parent injector dependencies are resolved. Hence closing.

**Comment by pandradesa** [comment]
Could you show how you passed parent injector?
