### ISSUE TITLE
NotYetImplemented error with angular universal 

### ISSUE THREAD

**Issue by samialmorshedi** [angular/angular#24552]
I'm using angular universal V6 and express server. When I run webpack as compiler of **server.ts** to **server.js**, it shows me these errors that I have no idea what to do with!!
Can you please help me to fix it!! Ignoring **nyi** function for these kind of error or something better.

`ERROR Error: NotYetImplemented at Document.exports.nyi (webpack-internal:///./node_modules/domino/lib/utils.js:41:9) at CookieService.check (webpack-internal:///./node_modules/ngx-cookie-service/cookie-service/cookie.service.js:31:48) at CookieService.get (webpack-internal:///./node_modules/ngx-cookie-service/cookie-service/cookie.service.js:36:47) at ChatySystemComponent../src/app/chaty-system/chaty-system.component.ts.ChatySystemComponent.ngOnInit (webpack-internal:///./dist/server/main.js:1371:40) at checkAndUpdateDirectiveInline (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:9217:19) at checkAndUpdateNodeInline (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:10481:20) at checkAndUpdateNode (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:10443:16) at prodCheckAndUpdateNode (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:10983:5) at Object.eval [as updateDirectives] (webpack-internal:///./dist/server/main.js:341:1857) at Object.updateDirectives (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:10772:72) at checkAndUpdateView (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:10425:14) at callViewAction (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:10666:21) at execComponentViewsAction (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:10608:13) at Object.checkAndUpdateView (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:10431:5) at ViewRef_.detectChanges (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:8812:22) at eval (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:4701:63) at Array.forEach (<anonymous>) at ApplicationRef.tick (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:4701:25) at ApplicationRef._loadComponent (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:4735:14) at ApplicationRef.bootstrap (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:4677:14) at eval (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:4477:81) at Array.forEach (<anonymous>) ERROR { Error: Uncaught (in promise): Error: NotYetImplemented Error: NotYetImplemented at Document.exports.nyi (webpack-internal:///./node_modules/domino/lib/utils.js:41:9) at CookieService.check (webpack-internal:///./node_modules/ngx-cookie-service/cookie-service/cookie.service.js:31:48) at CookieService.get (webpack-internal:///./node_modules/ngx-cookie-service/cookie-service/cookie.service.js:36:47) at new DateFormatterByTimezonePipe (webpack-internal:///./dist/server/main.js:9099:53) at createClass (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:9268:20) at createPipeInstance (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:9147:12) at createViewNodes (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:10366:32) at callViewAction (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:10689:13) at execComponentViewsAction (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:10608:13) at createViewNodes (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:10401:5) at createRootView (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:10287:5) at Object.createProdRootView [as createRootView] (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:10799:12) at ComponentFactory_.create (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:8633:29) at ComponentFactoryBoundToModule.create (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:3452:29) at ViewContainerRef_.createComponent (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:8743:45) at RouterOutlet.activateWith (webpack-internal:///./node_modules/@angular/router/fesm5/router.js:4658:40) at ActivateRoutes.activateRoutes (webpack-internal:///./node_modules/@angular/router/fesm5/router.js:4003:40) at eval (webpack-internal:///./node_modules/@angular/router/fesm5/router.js:3955:19)`

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
