### ISSUE TITLE
Add ability to download cheat sheet from Angular IO documentation site in PDF Or any other doc format

### ISSUE THREAD

**Issue by jonbonraki** [angular/angular#24555]
## I'm submitting a...

<pre><code>
[ ] Feature request
</code></pre>

## What is the motivation / use case for changing the behavior?
As a Developer I like to Have Cheat Sheet in My Machine( Preferably in PDF Document), Instead of Going to Angular docs and looking at cheat sheet . Through this Button or some kind element on Documentation Site, User will be able to download cheat sheet in pdf. https://angular.io/guide/cheatsheet

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
In chrome: Hitting print (ctrl + p) -> Save as PDF somewhat works, it could use a bit of specific styles but it's there.

**Comment by destus90** [comment]
When you go on official site, you'll get actual information. 
If you have a PDF-like document, you can have a bit outdated data.

**Comment by kambleaa007** [comment]
Go Visit 
https://dncmagazine.blob.core.windows.net/downloads/AngularCheatSheet-DNCMagazine.pdf

**Comment by jenniferfell** [comment]
Thanks for submitting this request. Also thanks to everyone who has commented.

May I ask for some clarification about your use case: Are you looking for a format to use offline on an electronic device? If so, what is your preferred device? Or are you looking for something to print as hardcopy?

I'm curious about your thoughts on these options for offline electronic use:
A: This site does take advantage of service workers to provide some offline capability.

B: I used my browser (Chrome on Mac) to do "Save as HTML" and got everything I need for offline use in my browser (including the nice formatting you see when connected to the live site). It's readable and searchable. 

C: I used my browser to save as PDF. The results are attached. Does this look like what you get? It could use some layout improvement, but all the content is there. I can search, select and copy sections, and add my own comments (with the right PDF viewer). 

[Angular - Cheat Sheet.pdf](https://github.com/angular/angular/files/2138428/Angular.-.Cheat.Sheet.pdf)


Similar to issue https://github.com/angular/angular/issues/24589, which focuses on shortening to 1-2 pages and offering a format for printed hardcopy use.

**Comment by jenniferfell** [comment]
Closed related issue as a duplicate, but that issue does have good comments to read/keep/consider in this context. https://github.com/angular/angular/issues/24589

**Comment by gnowland** [comment]
Hey ya'll (and everyone listening over on #24589) I also wanted a print version of the cheat sheet but the print styles are awful so I painstakingly made a PDF version of the current docs with an improved print layout - check it out:

[Angular v8 Cheat Sheet.pdf](https://github.com/angular/angular/files/3349538/Angular.v8.Cheat.Sheet.pdf)

It's not 2 pages but it covers everything on the site in a readable format.

**Comment by aikidave** [comment]
Creating a PDF is a non-trivial task, unfortunately. I think we'd need to get more information about how many people in the community need this feature for us to move forward on it. As this issue has been open without activity for almost 2 years, I'm closing it.
