### ISSUE TITLE
Register pure/simple functions as Pipes

### ISSUE THREAD

**Issue by luchsamapparat** [angular/angular#24559]
## I'm submitting a...

<pre><code>
[X] Feature request
</code></pre>

## Current behavior
I have various simple/pure functions (e.g. predicates, selectors, etc.) which are used throughout my application. When I want to use these functions in my components, I have to either (a) create a component method or (b) create a pipe which delegates to my function. This creates unnecessary boilerplate code.

I tried to create a factory method for creating pipes from functions, however that does not work with AOT.

```ts
export const ShoppingCartIsEmptyPipe = createPipe(shoppingCartIsEmpty);
```

https://gist.github.com/luchsamapparat/d535749f37def17ffdd312665a475cce#file-pipe-factory-ts

## Expected behavior
I want to register a method as pipe without the need to define a separate class.

```ts
@Pipe({ name: shoppingCartIsEmpty })
export function shoppingCartIsEmpty(shoppingCart: ShoppingCart) {
    if (isNull(shoppingCart)) {
        return true;
    }

    return isEmpty(shoppingCart.items);
}

@NgModule({
    declarations: [
        shoppingCartIsEmpty
    ]
}
export class ShoppingCartModule {}
``` 

## Minimal reproduction of the problem with instructions
Function:
https://github.com/luchsamapparat/cfha-client/blob/f0405838a32318d2b975019b1d63ae64419d2380/libs/shopping-cart-common/src/lib/shopping-cart.util.ts

Boilerplate Pipe to use Function in Template:
https://github.com/luchsamapparat/cfha-client/blob/f0405838a32318d2b975019b1d63ae64419d2380/libs/shopping-cart/src/lib/shopping-cart/shopping-cart-is-empty.pipe.ts

## What is the motivation / use case for changing the behavior?
Easily define re-usable business behavior in simple/pure functions without any dependencies to angular. When there's the need to use that function, I can just register it as pipe.

**Comment by babeal** [comment]
or maybe a way to indicate in the component class that the function is pure.
```
@Pure()
public computeSum(a, b) {... }
```

**Comment by trotyl** [comment]
Also please note that there's no such function decorator syntax.

**Comment by trotyl** [comment]
@sandangel There can only be decorator for **Function Expression**, but not possible for **Function Declaration**, which has already been discussed many time:

+ https://github.com/tc39/proposal-decorators-previous/issues/35
+ https://github.com/tc39/proposal-decorators/issues/40

**Comment by trotyl** [comment]
Seems related to https://github.com/angular/angular/issues/9761

**Comment by babeal** [comment]
I should have made mine more clear.  I assumed the context the component class (a method of) which decorators can live not a random exported function.  It reduces the utility but might still be nice.  @trotyl

**Comment by alxhub** [comment]
Closing as this is not really possible at this time, because of the lack of top-level function declaration decorators. With Angular's upcoming "standalone" feature, standalone pipes imported into standalone components will significantly reduce the boilerplate required, and come pretty close to a lightweight pipe API.
