### ISSUE TITLE
DoBootstrap interface does not exist

### ISSUE THREAD

**Issue by RoopeHakulinen** [angular/angular#24557]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
There is no `DoBootstrap` interface for modules like there is for all of the lifecycle hooks of components.
![capture](https://user-images.githubusercontent.com/2197974/41527335-b5efc3a6-72de-11e8-8482-9d68be1bbd24.PNG)

## Expected behavior
There should be an interface so that this would work:
![capture2](https://user-images.githubusercontent.com/2197974/41527338-b95b1392-72de-11e8-8e2b-3bf46fd0896d.PNG)

## What is the motivation / use case for changing the behavior?
There is an interface available for each lifecycle hook but `ngDoBootstrap` is missing the corresponding interface. This can be problematic for people with OCD over things like shown in the images above.

While adding the interface and getting rid of the linter warning improves quality of my life substantially already, there is also another point: documentation. Currently there is not much documentation covering the `ngDoBootstrap` so adding the interface also provides an entry for it in the angular.io documentation with example on how it should be utilized.

**Comment by RoopeHakulinen** [comment]
I'll submit a PR soon for this.

**Comment by mhevery** [comment]
+1 for PR

**Comment by RoopeHakulinen** [comment]
The PR #24558 should is ready for review @mhevery :)
