### ISSUE TITLE
Error importing more than 4 Modules in Angular 6

### ISSUE THREAD

**Issue by AndreVizosodaCruz** [angular/angular#24566]
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';

import { TextBoxModule, CheckBoxModule, ComboBoxModule, PasswordModule, RadioButtonModule, TextAreaModule, TextAreaComponent, CheckboxComponent, TextBoxComponent, PasswordComponent, ComboBoxComponent, RadioButtonComponent } from 'ux-framework'

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    TextBoxModule,
    CheckBoxModule,
    ComboBoxModule,
    PasswordModule,
    // RadioButtonModule,
    // TextAreaModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Hello i'm doing a simple framework, like bootstrap, and i'm importing that like a library in other project fut if i import more than 4 my app stop working(doesn't show anything in the app.component.html), any idea?

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
