### ISSUE TITLE
Standalone pipe function documentation issue

### ISSUE THREAD

**Issue by hiteshjoshi1** [angular/angular#24560]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

On the page
https://angular.io/guide/rx-library
Where Standalone pipe function is defined, the use of filter is wrong. This will not compile. filter should return a boolean. Also the overall function does not work even after fixing the filter with
filter(n => n % 2 !== 0)

See exercept below
```
import { filter, map } from 'rxjs/operators';
 const nums = of(1, 2, 3, 4, 5);
 // Create a function that accepts an Observable.
const squareOddVals = pipe(
  filter(n => n % 2),
  map(n => n * n)
);
 
```
## Expected behavior

The filter function and the overall example should either be fixed or removed completely, the chained pipe example that follows should be sufficient enough.

## What is the motivation / use case for changing the behavior?

Clean up documentation

## Environment

<pre><code>
Angular version: 6

Yes
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
@jasonaden Hi. Thoughts on this? Should we fix or remove? Thanks. (I'm surprised that it won't compile, because the example seems to come from a live example. Hmmm.) 

https://angular.io/guide/rx-library#operators

**Comment by jenniferfell** [comment]
@jbogarthyde FYI.

**Comment by brandonroberts** [comment]
@hiteshjoshi1 the example mentioned works with a small tweak.

```ts
const squareOddVals = pipe(
  filter((n: number) => n % 2 !== 0),
  map(n => n * n)
);
```
Stackblitz example: https://stackblitz.com/edit/angular-ghqab2?file=src%2Fapp%2Fapp.component.ts

I think the overall example is worth keeping because it shows how to create a custom pipeable operator. Would you like to submit a PR with a fix?


---
@jenniferfell The rx-library examples aren't part of a live example. They are just standalone files. He is correct that this wouldn't compile

**Comment by hiteshjoshi1** [comment]
Thanks @brandonroberts , I should have provided a working example.

Here, we need to note that in order to fix the filter function, we need to specify the type of n
(n: number) and provide the condition !== 0

Also, the  line in the docs
`// Create an Observable that will run the filter and map functions
const squareOdd = squareOddVals(nums);`
is wrong and has to be removed.

The nums observable should be piped  properly as @brandonroberts  pointed
`nums.pipe(squareOddVals).subscribe(console.log);`

I vote for a fix, Thanks!

**Comment by brandonroberts** [comment]
Closed via https://github.com/angular/angular/pull/24947
