### ISSUE TITLE
Problem with routing and iframe in page

### ISSUE THREAD

**Issue by Parro** [angular/angular#24561]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have a page in a route `college-page-name/18` with an iframe containing a Vimeo video with url `https://player.vimeo.com/video/456`. If you arrive in the page from `college-page-name/19`, where there's a video with url `https://player.vimeo.com/video/123` and you click back in the browser you do not return to `college-page-name/19`, instead you see in the iframe the video `https://player.vimeo.com/video/123`, and only if you press back a second time you are redirected to page `college-page-name/19`. If I enable enableTracing in routing, on the first click on back I don't see any message, I see only on the second click. It seems like the iframe is intercepting the back button. 

I think the problem is in `sanitizer.bypassSecurityTrustResourceUrl()`. If I try to use  with `www.google.com/123` and `www.google.com/456` as the iframe source, using `bypassSecurityTrustResourceUrl`, I get the same behavior. But if I use `www.google.com` and `www.apple.com` without `bypassSecurityTrustResourceUrl` the back button is working as expected.

## Expected behavior
Hitting the back button should redirect to the previous page

## Environment

<pre><code>
Angular version: 5.29

Browser:
- [x] Chrome (desktop) version 67.0.3396.87
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 60.0.2
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version 11.1.1
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Platform:  Mac OS X 10.13.4
</code></pre>

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

<hr>

Sounds like you found an edge case here, but without a reproduction it's hard to do anything about it. Please go ahead and create one, filing a new issue.
