### ISSUE TITLE
Make Service Workers configurable at runtime

### ISSUE THREAD

**Issue by jfrohn** [angular/angular#24575]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Is there a way to (re-)configure a Service Worker at runtime? We need an API which enables us to change the Service Worker configuration (see dataGroups entries ngsw-config.json) at runtime. Are there any strong reasons against doing it?

## Expected behavior

The Service Worker configuration can be changed at runtime.

## What is the motivation / use case for changing the behavior?

We would like to add (maybe also remove) Service Workers for specfic URLs at runtime. This should be extended to other configuration entries as well.

## Environment

<pre><code>
Angular version: all

Browser:
- all
 
For Tooling issues:
- Node version: all
- Platform:  all

Others:

</code></pre>

**Comment by gkalpak** [comment]
> Are there any strong reasons against doing it?

Are there any strong reasons for doing it? :grin:

> We would like to add (maybe also remove) Service Workers for specfic URLs at runtime.

You probably meant to say something else. Did you mean add/remove data-groups? If so why?

**Comment by jfrohn** [comment]
Yes, thanks! I meant to add/remove data-groups.

In our App we only need to cache certain resource specific calls, e.g. "../users/**1**/details" but not 
"../users/**2**/details". The IDs are decided at runtime. If we cache everything under "../users" we would store a lot of unnecessary data.

Is there maybe another way to achieve this?

**Comment by gkalpak** [comment]
So, you are making requests for `.../users/1/details`, `.../users/2/details`, but you only need to cache responses for _one_ specific user ID (probably the logged-in user)?

It sounds doable, but complicated (and it is still possible that it breaks some of the guarrantees we rely (without me realizing atm)).

This would also not work well if it were possible to have two different tabs on the same browser caching different IDs, but I guess that usecase (even if possible) is quite rare.

Overall, I don't think it is worth the extra complication.

##
Possible workarounds:
- Use a different URL for requesting active user data (may or may not be straight forward based on the app).
- Use an appropriate [cache configuration][1] to ensure avoid storing too much data. 

[1]: https://angular.io/guide/service-worker-config#cacheconfig

**Comment by jfrohn** [comment]
Thank you for your help @gkalpak!

I think in this case the maxSize configuration must be enought then. I will the close the ticket now.
