### ISSUE TITLE
directive usage before app is bootstrapped

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#2457]
I suppose that if I were to use a directive before the app is bootstrapped it wouldn't work (already tried it anyway). For instance the following case:
```html
<app>
	<loader></loader>
</app>
```
The `loader` directive/component would not work (not even after it has been transcluded in the `<content></content>` tag I have in the app template).

Is there any way to have this scenario work?

**Comment by gdi2290** [comment]
angular2 currently ignores the lightDom only for the top level component (usually called `App` class as `<app>`). it doesn't make sense to bootstrap angular to load a loader for bootstrapping angular

**Comment by rolandjitsu** [comment]
@gdi2290 the idea was to have a nice spinner (`<loader>`). And if I want a reusable component I would have used a directive. So I suppose this will never be supported?

**Comment by gdi2290** [comment]
I'm saying the loader wouldn't even work here so your loader should have basic features such as default display loading then when angular bootstraps you can add the correct behavior. what you want is supported but it's more of using css then converting the selector to a component

**Comment by rolandjitsu** [comment]
@gdi2290 right now I am using just an SVG with animations, so that is just fine. But the part about converting it to a component is what I am not sure how to do it. Could you elaborate with a very simple example or explain how I would approach it?

**Comment by thekhoi** [comment]
@gdi2290 are there a reason why angular2 is ignoring the light DOM on a root component?  I also seems like it doesn't interpolate literal values for component properties for root components either.  This would be helpful if you have have server generated code markup and don't want to go through too much ceremony to wire it all up in angular.

**Comment by mhevery** [comment]
For security reasons we will not process any directives in the index.html (with the exception of the bootstrap component)
