### ISSUE TITLE
Webpack Guid Not Found on angular.io

### ISSUE THREAD

**Issue by asif4ever4u** [angular/angular#24574]
> https://angular.io/guide/webpack

above is showing Page Not Found.

**Comment by trotyl** [comment]
See https://github.com/angular/angular/issues/23937

**Comment by gkalpak** [comment]
See also https://github.com/angular/angular/pull/20199#issuecomment-342078147 for reasoning.
BTW, you can find the guide in the (archived) v5 docs: https://v5.angular.io/guide/webpack

**Comment by udayRedI** [comment]
@gkalpak , The repo we download doesn't work. Do we move to ng-cli or make our own repo to support webpack?

**Comment by gkalpak** [comment]
What repo are you referring to, @udayRedI?

**Comment by udayRedI** [comment]
https://v5.angular.io/guide/webpack
