### ISSUE TITLE
How building process takes place in angular 6?

### ISSUE THREAD

**Issue by BUHARIMOHAMEDISMAIL** [angular/angular#24576]
I'm newone to angular 6.

I know how to build the application but i don't the inner process happened while taking build.

May i know which bundling system you are using and Is there necessary to use external bundling system like rollup, browsify, ...

Further i need to add the tree shaking feature in my application. 

please assist me

Thanks,
Buhari Mohamed Ismail

**Comment by sarunint** [comment]
Use Angular CLI. It handles the bundling, treeshaking and others for you.

By the way, this issue tracker is not the appropriate place to ask questions. Please ask questions on [StackOverflow](http://stackoverflow.com/) using tag `angular` or on [Gitter](https://gitter.im/angular/angular).
