### ISSUE TITLE
Angular/Elements: DOM not updated when using a *ngIf and async pipe 

### ISSUE THREAD

**Issue by Werner-Swart-83** [angular/angular#24577]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have created a custom component using angular/elements. I am calling the next method on a subject to update an observer that is bound on the html template with an *ngIf (i.e. *ngIf="(value$ | async ) as value") When the subject.next is called the DOM isn't updated. 

## Expected behavior
Expect the DOM to be updated when the subject.next is called in my MyElementComponent.

## Minimal reproduction of the problem with instructions
Here is a link to my Github repository where I created a sample project where the issue occurs: https://github.com/Werner-Swart-83/elements-test/tree/master/src/app

The index.html page and the elements-test.js file is in the same directory. I used a http-server to serve it on my local. The custom component does load but the *ngIf isn't evaluated after the subject.next is called.

## What is the motivation / use case for changing the behavior?
This works in a normal angular application, so expected it to work the same in the custom-component. Could be wrong, that also why I am here :)

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x] Chrome (desktop) version 67.0.3396.87
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.11.1
- Platform:  Windows 10

Others:
Used http-server, also tried hosting it in an aspcore project, got the same result. 
</code></pre>

**Comment by ericmartinezr** [comment]
Does it work if you `next` in `ngAfterViewInit()` instead of `ngOnInit()`? If that works I would say it's a timing thing (you're nexting before it is actually subscribed). Here's an [example](https://stackblitz.com/edit/angular-lnk7jo?file=src%2Fapp%2Fapp.component.ts) (not using elements though). If the problem persist, ignore this comment *cough*

**Comment by Werner-Swart-83** [comment]
Thanks for the reply, I implemented the recommendations but it didn't work.

**Comment by remackgeek** [comment]
@Werner-Swart-83  the underlying cause looks to be the same as #24181 and #23841. 
There's a PR for it here: #24185

I've made a variation of this as an npm package:  [elements-zone-strategy](https://www.npmjs.com/package/elements-zone-strategy)

change app.module.ts:
`import { ElementZoneStrategyFactory } from 'elements-zone-strategy';`

`const strategyFactory = new ElementZoneStrategyFactory(MyElementComponent, injector);`
`const element = createCustomElement(MyElementComponent, { injector, strategyFactory });`

and it should work for you.

**Comment by remackgeek** [comment]
Hmm...I'm not sure what I'm doing differently. I pulled your latest and built it and it worked (I got the potato). I reverted to the previous commit and it didn't work (no potato).

**Comment by Werner-Swart-83** [comment]
@remackgeek so the output of my package script was targeting the root folder instead of my dist folder. Yesterday morning when I tested it I did the build and thought that the element-test.js was being outputted to my dist folder (like my other project). Now that I have fixed my package output, I have tested it again it works. Thank you :) and also my bad.
