### ISSUE TITLE
Directive naming ambiguity ?

### ISSUE THREAD

**Issue by biancashouse** [angular/angular#24573]
How come a module has directive @NgModule, while a component doesn't have directive @NgComponent.

Perhaps its just how my brain works, but I find the inconsistency slightly disturbing ;-)
IMHO every angular directive should be prefixed by ng.

[NOTE to Github - I definitely type a cap C in @NgComponent, but on saving the comment it gets lowercased. huh?]

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/10729, https://github.com/angular/angular/issues/19178

**Comment by magnattic** [comment]
> [NOTE to Github - I definitely type a cap C in @ngcomponent, but on saving the comment it gets lowercased. huh?]

When you use `@` Github thinks you are referencing a Github user or team. Those are usually lowercase. Try escaping it with code blocks: `@NgComponent`.

**Comment by biancashouse** [comment]
ok, thanks for that info.
so how to escape an at sign, backslash? \\

**Comment by trotyl** [comment]
@biancashouse Or surround it with backticks (\`), then the content would be rendered as `<code>` like: `@Component()`, `@NgModule()`.

**Comment by biancashouse** [comment]
useful feedback. many thanks.

**Comment by jasonaden** [comment]
Closing as this appears resolved.
