### ISSUE TITLE
Don't use Dart identical(x, y) for strings

### ISSUE THREAD

**Issue by kevmoo** [angular/angular#2458]
The same strings values are not guaranteed to be identical in Dart.

The code `KeyEventsPlugin.getEventFullKey(event) === fullKey` returns `false` even if the Strings are equal causing the ToDo sample to not work in Dartium.

This is because `x === y` is converted to `identical(x, y)` by ts2dart.

```ts
// key_events.ts
  static eventCallback(element, shouldSupportBubble, fullKey, handler, zone) {
    return (event) => {
      var correctElement = shouldSupportBubble || event.target === element;
      if (correctElement && KeyEventsPlugin.getEventFullKey(event) === fullKey) {
        zone.run(() => handler(event));
      }
    };
  }
```

For instance, this Dart code

```dart
  var a = ['f', 'o', 'o'].join();
  var b = 'foo';
  print(a == b);
  print(identical(a, b));
```

prints
```
true
false
```

**Comment by vicb** [comment]
Could you please submit a PR ?

**Comment by kevmoo** [comment]
@vicb We'd need to patch up `ts2dart` to support `==`, which it doesn't. I wanted to capture the issue here first before opening a bug there.

**Comment by vicb** [comment]
ah yep, however ts2dart will only be able to generate a `==` when at least one of the operand is known to be a string.
/cc @mprobst

**Comment by mprobst** [comment]
This would depend on precise type information being available to ts2dart. This might turn out to be a bit of a problem, as far as I can tell from taking a rough look, large parts of the Angular code base do not have type information around, so people would have to write lots of type assertions for these (`<string>bar === something`, but also for any other `==` statement).

**Comment by kevmoo** [comment]
@mprobst I'm not arguing for "smarts" based on types. I'm arguing that

1. ts2dart support `==`
2. angular2 use `==` in some contexts. For instance, comparing strings where we aren't worried about squishy equality

**Comment by mprobst** [comment]
I see. So you're saying we should just translate '==' to '==' in Dart?
That'd be a workable solution, but the quite dangerous - using '==' for
non-string arguments leads to all the beloved oddities of JavaScript '=='
comparison on the JS side; using '===' leads to silent errors for strings
on the Dart side.

We could replace "identical(a, b)" with "a instanceof String || b
instanceof String ? a == b : identical(a, b)", but that might be a
performance issue.

>

**Comment by kevmoo** [comment]
@mprobst Gah! Not to mention - we'd need to know that a and b are String. Or at least what type they are.

Couldn't we allow `==` and just make sure it's treated optional?

Or (@vicb) we could create another facade for String equality.

**Comment by vicb** [comment]
@kevmoo someone smart has already created `StringWrapper.equals`

**Comment by kevmoo** [comment]
Ha! Okay. That's our fix here.

@mprobst : never mind – for now. Thanks for discussing...
@vicb: pull request inbound shortly
