### ISSUE TITLE
Unable to install Angular 6.0.8

### ISSUE THREAD

**Issue by suhas-hebbar** [angular/angular#24581]
Angular installation failing with the below error and angular is not installed.

Attached Error log
[2018-06-19T08_39_53_490Z-debug.log](https://github.com/angular/angular/files/2118666/2018-06-19T08_39_53_490Z-debug.log)

D:\software\node-v8.11.2-win-x64>npm install -g @angular/cli
D:\software\node-v8.11.2-win-x64\ng -> D:\eclipse\software\node-v8.11.2-win-x64\node_modules\@angular\cli\bin\ng

> @angular/cli@6.0.8 postinstall D:\eclipse\software\node-v8.11.2-win-x64\node_modules\@angular\cli
> node ./bin/ng-update-message.js

'node' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\@angular\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @angular/cli@6.0.8 postinstall: `node ./bin/ng-update-message.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @angular/cli@6.0.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\N96304.LAUNCHER\AppData\Roaming\npm-cache\_logs\2018-06-19T08_39_53_490Z-debug.lo

**Comment by mvgadagi** [comment]
First, check whether node is installed in your machine by `node -v`

**Comment by suhas-hebbar** [comment]
Thanks. Issue is am using zip version of node.js and the PATH variable is not set.

**Comment by UrsBeeli** [comment]
Making sure that node.exe is on the path solved the issue for me!
