### ISSUE TITLE
@angular/http deprecation notes need more info about replacement

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#24597]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

https://angular.io/api/http/RequestOptions
https://angular.io/api/http/Response

API is deprecated. Deprecation note directs users to the HttpClient guide: https://angular.io/guide/http. That guide contains no mention of RequestOptions or Response APIs explicitly.

## Expected behavior

API deprecation note should clearly explain what APIs should be used to replace this class. There should be a link to replacement APIs, not just to the related guide. If there isn't a 1:1 replacement, then more needs to be written here (or in a migration guide or blog post and linked from here) about switching from old http to new common/http APIs. 

## Minimal reproduction of the problem with instructions

See links above

## What is the motivation / use case for changing the behavior?

Help developers move off this deprecated API to the new solution. Even though this is a feature request, I'm marking this as high frequency because this API was included in a recent list of most popular APIs. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by cgideon** [comment]
Please address this, it's very unclear how to upgrade the applications that use Response and RequestOptions from Angular 4 to 6.

**Comment by fidel-ruiz** [comment]
@cgideon Did you find any doc related on what to accomplish this upgrade?
Thanks in advance

**Comment by jenniferfell** [comment]
Updated issue title, because this applies to *all* of the @angular/http package APIs. The API reference pages need to be updated to have cross references to the replacement APIs, not just to the HTTP guide.

**Comment by mayank-aggarwal28** [comment]
> 
> 
> I figured it out via experimentation with the new HttpClient in Angular6

Can you post how you did it? I am trying to migrate from Angular 2.4.10 to Angular 7 and I am just not able to figure out about Headers and RequestOptions.

**Comment by gkalpak** [comment]
I don't think it is a good idea to redirect those to their "replacements" (see https://github.com/angular/angular/pull/29907#pullrequestreview-226773904 and https://github.com/angular/angular/pull/29907#issuecomment-523566631).

We should redirect to the deprecation guide, which (among other info) also contains a mapping from old APIs to their new couterpart (if any).

**Comment by jbogarthyde** [comment]
The current behavior is preferred - redirecting all old http urls to deprecations page. Closing both this issue and the proposed PR.
