### ISSUE TITLE
Generic type support for pipes transform

### ISSUE THREAD

**Issue by JDeblaton** [angular/angular#24590]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have a few classes that implement an abstract class like the following : 

```
export abstract class EncompassedPeriod {
  start: Date;
  end: Date;
}

export class A implements EncompassedPeriod {
  start: Date;
  end: Date;
  x: any;
}

export class B implements EncompassedPeriod {
  start: Date;
  end: Date;
  y: any;
}
```

I'd like to be able to do the following thing : 

```
(someArrayOfA | getEncompassedPeriod)?.x
```
but I get the following error : 

> ng: Identifier 'type' is not defined. 'T' does not contain such a member

## Expected behavior

I'd like to be able to create a generic pipe :

```
  transform<T extends EncompassedPeriod>( value: T[]): T {
     return value[0]; // simplified
  }
```

## What is the motivation / use case for changing the behavior?

I know I could simply return "any" but I lose the ability to have typed support into my template

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/21224

**Comment by JDeblaton** [comment]
Thanks ericmartinezr, I promise I did a research before. This issue can be closed I think
