### ISSUE TITLE
setTimeout() in ngZone.runOutsideAngular() blocks async() test

### ISSUE THREAD

**Issue by atheros** [angular/angular#24603]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
If I call setTimeout() outside zone, unit test wrapped in async() function timeouts.

## Expected behavior
In Angular 5.2.0 this works as expected: test completes immediately.

## Minimal reproduction of the problem with instructions
Bellow is a simple test, I've tested it in app.component.spec.ts in default angular project created from cli.
<pre><code>
    it('should not timeout', async(() => {
        const zone = TestBed.get(NgZone);

        zone.runOutsideAngular(() => {
            setTimeout(() => {
                console.log('timeout!');
            }, 6000);
        });

        console.log('completed');
    }));
</code></pre>

## What is the motivation / use case for changing the behavior?
I think this is a bug. It used to work correctly in Angular 4 and 5.
Same issue is with timer observable outside zone.

## Environment

<pre><code>
Angular version: 6.0.5
zone.js: 0.8.26

Browser:
- [x] Chrome (desktop) version 67.0.3396 (headless)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3
- Platform:  Mac

Others:
</code></pre>

**Comment by JiaLiPassion** [comment]
@atheros, this is a zone.js issue, and I believe the current behavior is correct.

```ts
 it('should not timeout', async(() => {
        const zone = TestBed.get(NgZone);

        // because zone.runOutsideAngular will run in rootZone, and 
       // will not managed by asyncTestZone
        zone.runOutsideAngular(() => {
            setTimeout(() => {
                console.log('timeout!');
            }, 6000);
        });

        console.log('completed');
    }));
```

`zone.runOutsideAngular` will run in `root zone`, and it will not be detected by `async Test Zone`.
So before `setTimeout callback` triggered, the test case will be `completed`. This is by design.
Before the current version `zone.js`, the behavior is not correct.

So the `async` will only handle `setTimeout/promise` which happens inside it's zone.
And in your case, I don't udnerstand why you need to call `zone.runOutsideAngular` because in test case, the current zone is not `ngZone`. Could you provide your use case or reproduce repo?

**Comment by atheros** [comment]
I use setTimeout and timer observable from my components to schedule some asynchronous actions not directly tied the UI. The issue is that during unit tests, if I test a component that schedules such action, the unit test wrapped in async() will timeout waiting for completion of that timeout. My solution before Angular 6.0 was to do the scheduling outside ngZone. 
With Angular 6.0 it doesn't work anymore.

An example with component:
```typescript
import { TestBed, async } from '@angular/core/testing';
import { Component, NgZone, OnDestroy } from '@angular/core';


@Component({
    template: `Hi`
})
class TestComponent implements OnDestroy {
    private timeout: any;

    constructor(private ngZone: NgZone) {
    }

    ngOnDestroy(): void {
        if (this.timeout) {
            clearTimeout(this.timeout);
        }
    }

    someAction() {
        this.ngZone.runOutsideAngular(() => {
            this.timeout = setTimeout(() => {
                console.log('timeout!');
                this.timeout = null;
            }, 6000);
        });
    }
}

fdescribe('TestComponent', () => {
    beforeEach(async(() => {
        TestBed.configureTestingModule({
            declarations: [
                TestComponent
            ],
        }).compileComponents();
    }));

    it('should create component', async(() => {
        const fixture = TestBed.createComponent(TestComponent);
        const app = fixture.debugElement.componentInstance;
        expect(app).toBeTruthy();
    }));

    it('should not timeout with async()', async(() => {
        const fixture = TestBed.createComponent(TestComponent);
        const app = fixture.debugElement.componentInstance as TestComponent;

        app.someAction();
    }));

    it('should not timeout with whenStable()', async () => {
        const fixture = TestBed.createComponent(TestComponent);
        const app = fixture.debugElement.componentInstance as TestComponent;

        app.someAction();

        await fixture.whenStable();
    });
});
```
In this example "should not timeout with async()" timeouts in Angular 6.
Interesting point is that fixture.whenStable() works as expected.
All tests work in Angular 5.

**Comment by sactyagi** [comment]
Hi,
I have around 200 angular test cases, every time when I am running all  in bulk, the run hung up on the specific test case. Its hung on that method where ngZone is used. My test case is async.  Please advise how I can resolve my issue, please advise. 
I am using the following versions:
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.3.1
@angular/cli                      6.0.8
@angular/flex-layout              6.0.0-beta.15
@angular/material                 6.3.1
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3

**Comment by JiaLiPassion** [comment]
@atheros, my previous explanation is not correct.
The current behavior is correct.

This case will timeout

```
  it('should not timeout with async()', async(() => {
        const fixture = TestBed.createComponent(TestComponent);
        const app = fixture.debugElement.componentInstance as TestComponent;

        app.someAction();
    }));
```

because `app.someAction()` will `call setTimeout`, even `outside ngZone`, it will be `caught by `async zone`. So `async zone` will wait for `setTimeout` until `timeout`. This is the correct behavior.

------------

This case will not timeout,

```
it('should not timeout with whenStable()', async () => {
        const fixture = TestBed.createComponent(TestComponent);
        const app = fixture.debugElement.componentInstance as TestComponent;

        app.someAction();

        await fixture.whenStable();
    });
```

because `async` here is not `angular async`, it is the javascript keyword of `async/await`. 
In fact, in this case, the test will not timeout because  `app.someAction is not awaited`, it is just a `sync call`.

**Comment by benlesh** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
