### ISSUE TITLE
Provide a way to unhook a particular page from ng serve's autoreload mechanism

### ISSUE THREAD

**Issue by earshinov** [angular/angular#24606]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Motivation

Sometimes it is useful to keep a page as a reference, for example during layout adjustments. However, if a page is served by `ng serve`, it will automatically reload as soon as any change is made. I would like to have a way of preventing a particular page from reloading, basically unhook it from the angular's autoreload mechanism. A command to be executed in browser developer tools (like `ng.probe`) would be very welcome.

**Comment by pkozlowski-opensource** [comment]
This belongs to https://github.com/angular/angular-cli

**Comment by earshinov** [comment]
Filed https://github.com/angular/angular-cli/issues/11332
