### ISSUE TITLE
Perhaps incorrect formatting when using currency pipe with locale de-AT

### ISSUE THREAD

**Issue by cat-mandres** [angular/angular#24609]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
The currency pipe uses the wrong decimal symbol when called with the locale 'de-AT'.
This does not occur with the decimal pipe, it uses the correct decimal symbol.

Input: 123456789

Current output from currency pipe with locale 'de-AT': € 123 456 789.00
Expected output from currency pipe with locale 'de-AT': € 123 456 789,00

[Image of the problem](https://imgur.com/Swz0w83)

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gitter-bmc7aa

## Environment

<pre><code>
Angular version: 6.0.5

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
This is expected.

The numeric decimal separator is `,` as per https://github.com/unicode-cldr/cldr-numbers-full/blob/68f9da8c4a2bd918ae4081b53418eb9585484ccf/main/de-AT/numbers.json#L19

But currency decimal separator is `.` as per https://github.com/unicode-cldr/cldr-numbers-full/blob/68f9da8c4a2bd918ae4081b53418eb9585484ccf/main/de-AT/numbers.json#L111

Angular uses [CLDR](http://cldr.unicode.org/) data for all i18n values, if you believe that there is a mistake in those data, then you should open an issue on the CLDR repository: http://cldr.unicode.org/index/bug-reports

**Comment by cat-mandres** [comment]
Can this somehow be read from the locale files in the angular repo, e.g. here?

https://github.com/angular/angular/blob/master/packages/common/locales/de-AT.ts
https://github.com/angular/angular/blob/master/packages/common/locales/de.ts

I cant really find the difference in here where the other symbol is defined.

**Comment by trotyl** [comment]
https://github.com/angular/angular/blob/637805a0c90b201f3e258eaeff967d5992d71faf/packages/common/locales/de.ts#L53

This line is the symbol for numbers while:

https://github.com/angular/angular/blob/637805a0c90b201f3e258eaeff967d5992d71faf/packages/common/locales/de.ts#L54

This line is the symbol for currencies.

**Comment by cat-mandres** [comment]
Yes I know that - and if you now take the lines from the de-AT.ts file

https://github.com/angular/angular/blob/637805a0c90b201f3e258eaeff967d5992d71faf/packages/common/locales/de-AT.ts#L54

and

https://github.com/angular/angular/blob/637805a0c90b201f3e258eaeff967d5992d71faf/packages/common/locales/de-AT.ts#L55

You get the following format for currencies get formatted:

`¤ #,##0.00`

According to this method which is getting used by the currency pipe to get the number:

https://github.com/angular/angular/blob/637805a0c90b201f3e258eaeff967d5992d71faf/packages/common/src/i18n/locale_data_api.ts#L365

the dot should get replaced by the character used for decimal point.

https://github.com/angular/angular/blob/637805a0c90b201f3e258eaeff967d5992d71faf/packages/common/src/i18n/locale_data_api.ts#L351

now the character used for decimal point is only defined once, the first symbol in the numbers line above, which is a `,`.
Am I wrong about something here?

**Comment by trotyl** [comment]
Agreed, sounds like a legit bug.

**Comment by trotyl** [comment]
The bug is caused by these code:

https://github.com/angular/angular/blob/ce40e85cbbf100df3e5507d26e961582ffdd1a17/tools/gulp-tasks/cldr/extract.js#L447-L453

There should be an else clause for `currencyDecimal` to push an `undefined` value to keep this position, like:

```typescript
if (symbols.currencyDecimal) {
  symbolValues.push(symbols.currencyDecimal);
} else {
  symbolValues.push(undefined);
}
```

CC: @ocombe

**Comment by ocombe** [comment]
Hmm that sounds about right, good find both of you, thanks!

**Comment by ocombe** [comment]
Actually the correct format will be `€ 123.456.789,00` with the fix

**Comment by cat-mandres** [comment]
How so? Isnt that another bug then? 
In locale de-AT there is a blank defined as digit grouping symbol?

**Comment by ocombe** [comment]
It was previously using the currency group symbol instead of the currency decimal symbol. With the fix, it'll use the currency group symbol for group, and the regular number decimal symbol for decimals.

**Comment by cat-mandres** [comment]
I see.
So am I correct that the last symbol of the following line:

https://github.com/angular/angular/blob/637805a0c90b201f3e258eaeff967d5992d71faf/packages/common/locales/de-AT.ts#L54

is the digit grouping symbol used for currencies if it is defined? 
And if undefined it will fallback to the 2nd symbol of this line, the digit grouping symbol for decimals.

E.g. in the locales/de.ts file this last symbol is undefined, which means same symbol for decimals as for currencies?

**Comment by ocombe** [comment]
Yes that is how the formatting rules are defined by CLDR, use the currency specific symbols if they are defined, or use the regular symbols otherwise.
