### ISSUE TITLE
How can i retrieve a eventStream data with httpClient?

### ISSUE THREAD

**Issue by Root-Control** [angular/angular#24600]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I can't retrieve data from a event stream

## Expected behavior

I want to retrieve the data from the server in an observable

## What is the motivation / use case for changing the behavior?

I need to retrieve this data to create a excel file

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [x ] Chrome (desktop) version 67.0.3396.87
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4 
- Platform: Windows 10

Others:

</code></pre>

I can't retrieve this data in a http request, the data is text, i tried { responseType: 'text'} but doesn't work, this is the eventStream:
http://35.182.172.115:3000/api/devices/logreport/TEL999?startDate=20180601&endDate=20180603&interval=1

also i tried with oboejs but still not working, please elp me.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
