### ISSUE TITLE
feature(router): Provide an API to update the URL without causing a NavigationStart

### ISSUE THREAD

**Issue by jasonaden** [angular/angular#24617]
In some situations when a page is rendered, data will be fetched from the server that should end up in the URL. For example, a page containing a sortable table where the sort/filter info comes from the server after the route has already been activated.

In a situation like this, we might want to update the URL with the sort values, but don't want to re-run the full navigation flow. There should be an API allowing certain updates to the URL (probably just the query parameters, but if there's use cases for it maybe the matrix parameters as well) to happen without running the navigation flow.

**Comment by dawidgarus** [comment]
I think it's related to https://github.com/angular/angular/issues/14283
