### ISSUE TITLE
Feature: API or tool to get info on number, location and reason for DOM changes in CD cycle

### ISSUE THREAD

**Issue by liorcaspi9** [angular/angular#24612]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
There is no API or tool to get how many DOM changes were made and where in every CD cycle by angular.

## Expected behavior
It would be great if there was an API or a tool that exposes the number of, location and reason for changes in the DOM on every CD cycle or tick.

## What is the motivation / use case for changing the behavior?
It would Help profiling angular in run-time and checking that *all but only* desired changes occur.

@robwormald

**Comment by trotyl** [comment]
This has already been implemented in Ivy: https://github.com/angular/angular/pull/23385.

The API locates at: https://github.com/angular/angular/blob/637805a0c90b201f3e258eaeff967d5992d71faf/packages/core/src/render3/ng_dev_mode.ts#L12-L32

Possibly add a `fixed by Ivy` label first but keep this open for now.

**Comment by liorcaspi9** [comment]
@trotyl  the API in ivy has counters but not the nodes and no way of knowing why they changed... right?

**Comment by mhevery** [comment]
> @trotyl the API in ivy has counters but not the nodes and no way of knowing why they changed... right?

What you are asking for is way to memory intensive and as such it will unlikely to be implemented. Closing as won't fix.
