### ISSUE TITLE
feature(ivy): bring back type-checking for inputs

### ISSUE THREAD

**Issue by trotyl** [angular/angular#24625]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The View Engine in v4 causes a regression for input type-checking, and haven't been fixed yet. But that's still a real regression: https://github.com/angular/angular/issues/20600.

It's understandable that current View Engine won't be honored with further big fixes.

### Code generation

The code-generation in Ivy would be much easier to allow input type-checking. For example, currently Ivy generates:

```typescript
class SubComponent {
  items: string[];
  static ngComponentDef = defineComponent({ /* ... */ });
}

function template(rf: RenderFlags, ctx: {items: string[]}) {
  if (rf & RenderFlags.Update) {
    elementProperty(0, 'items', bind(ctx.items));
  }
}
```

It could be expanded to:

```typescript
class SubComponent {
  items: string[];
  static ngComponentDef = defineComponent({ /* ... */ });
}

function template(rf: RenderFlags, ctx: {realItems: string[]}) {
  if (rf & RenderFlags.Update) {
    const exp_0: SubComponent['items'] = ctx.realItems;
    elementProperty(0, 'items', bind(exp_0));
  }
}
```

That way if `realItems` in context doesn't match `SubComponent.items`, a type error would be produced by TypeScript.

For shared inputs, an intersection type could be used:

```typescript
class SubComponent {
  items: string[];
  static ngComponentDef = defineComponent({ /* ... */ });
}

class AnotherDirective {
  items: string[];
  static ngDirectiveDef = defineDirective({ /* ... */ });
}

function template(rf: RenderFlags, ctx: {realItems: string[]}) {
  if (rf & RenderFlags.Update) {
    const exp_0: SubComponent['items'] & AnotherDirective['items'] = ctx.realItems;
    elementProperty(0, 'items', bind(exp_0));
  }
}
```

If `realItems` is not compatible to either signature, there would always be error.

### Locality

This approach doesn't require full global information, but still requires the transitive scope of its NgModule, so would certainly break single-file locality, should only be enabled in non-watch mode, and **especially in Language Service**. 

### Performance

Should be inlined by a minifier, thus results in no difference in prod build. (Should have little impact even without minifier)

## Minimal reproduction of the problem with instructions

N/A.

## What is the motivation / use case for changing the behavior?

Type-checking is helpful in development.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by JoostK** [comment]
@trotyl Do you agree this can be closed now that ngtsc has a dedicated typecheck phase, independent from the generated runtime code?

**Comment by trotyl** [comment]
Close as explanation above.
