### ISSUE TITLE
Required ViewChild/ContentChild proposal

### ISSUE THREAD

**Issue by rkirov** [angular/angular#24620]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Using Angular with TS 2.7+ --strict, means that property initialization is checked by the TypeScript compiler. For `ViewChild` this is good because it forces developers to recognize that the framework does not guarantee that `ViewChild` property is always set. For example, `@ViewChild(Foo) foo: Foo`, the prop could be `undefined` if in the template we have `<Foo *ngIf="...">`.

However, I think that in the majority of cases the desired child is unconditionally present in the template. Our recommendation for these cases is to use `@ViewChild(Foo) foo!: Foo` but to pair with an runtime assertion in `afterViewConentInit`. Without a runtime assertion the component is brittle, because an `*ngIf` could be added later and the static checks are now wrong.

So I am proposing a `required` attribute to the decorator, such that the framework throws if the component is ever present through out the lifecycle of the component. Then we can syntactically allow '!' only if the `required` flag is present, so

```
@ViewChild(Foo, {required: True}) foo!: Foo;  // ok
@ViewChild(Foo) foo!: Foo;  // bad
```
This can be enforced easily with a lint check like codalyzer.

`ContentChild` can be handled similarly. I chose `ViewChild` for this proposal because it is more widely used and more tempting to just add `!` everywhere.

**Comment by alxhub** [comment]
In general I like the idea of statically validating `ViewChild` queries, but I think this is likely to be done through template type-checking and not a `required` attribute to the decorator.
