### ISSUE TITLE
feature(core&compiler): special binding value to remove attribute/style

### ISSUE THREAD

**Issue by trotyl** [angular/angular#24622]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Sometimes the absence of certain attribute is always different than having any value, for example: https://github.com/angular/angular/pull/22276#discussion_r168923928.

When trying to remove an attribute, no binding can be used but only imperative logics.

## Expected behavior

There could be special binding value indicates removing it (if previously exists).

In template:

```html
<input [attr.name]="name != null ? name : $empty">
```

In logic:

```typescript
import { EMPTY_BINDING, HostBinding } from '@angular/core'

class MyComp {
  @HostBinding('attr.name')
  get attributeName() {
    return this.name != null ? this.name : EMPTY_BINDING
  }
}
```

Should invoke [removeAttribute](https://angular.io/api/core/Renderer2#removeAttribute) (or [removeStyle](https://angular.io/api/core/Renderer2#removestyle) for style binding). But throw for property binding (property cannot be removed).

## Minimal reproduction of the problem with instructions

N/A.

## What is the motivation / use case for changing the behavior?

Above.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by alxhub** [comment]
Does `null` not work in this case? I believe that clears the attribute...

**Comment by alxhub** [comment]
https://stackblitz.com/edit/ng-toggle-attr?file=src%2Fapp%2Fapp.component.ts

**Comment by trotyl** [comment]
@alxhub Sounds right, possibly something with my original case, close for now.
