### ISSUE TITLE
Form Controls are not available until after a next tick

### ISSUE THREAD

**Issue by maxkorz** [angular/angular#24639]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
`NgForm.controls` object is empty until after a next tick.

## Expected behavior
`NgForm.controls` must be available earlier in the lifecycle.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-ddwp4h?file=src%2Fapp%2Fapp.component.ts
Open the console to see the output

## Environment

<pre><code>Angular version: 6.0.6

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by manjot-cams** [comment]
Just a suggestion, why don't you use [reactive forms](https://angular.io/guide/reactive-forms)? this way you have access to the controls in the `ngOnInit` lifecycle

**Comment by maxkorz** [comment]
I think the Reactive forms make the code more complicated than necessary. There are dozens of inputs in my forms. I don't want to describe all the inputs in both Controller and Template. For me, template-driven forms are easier to work with.

**Comment by dawidgarus** [comment]
@maxkorz why not set initial values bindings to ngModel:
```typescript
this.model = {
  firstName: 'John',
  lastName: 'Doe',
};
```
and:
```html
<input name="firstName" [(ngModel)]="model.firstName">
<input name="lastName" [(ngModel)]="model.lastName">
```

**Comment by maxkorz** [comment]
@dawidgarus because of side effects. 
When I pass some data into a component and bind it with `[(ngModel)]`, data in outer component changes along with my changes in the form inputs. It doesn't happen when I don't use `[(ngModel)]` binding.

Take a look at this demo https://stackblitz.com/edit/angular-zpgxmz to see what I mean

**Comment by dawidgarus** [comment]
@maxkorz change `[(ngModel)]` to `[ngModel]` and you're good

**Comment by kara** [comment]
This is working as intended. Template-driven forms must be registered asynchronously to avoid ExpressionChangedAfterChecked errors.
