### ISSUE TITLE
aio(routing) live example is not working as expected

### ISSUE THREAD

**Issue by jainanuj0812** [angular/angular#24638]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Live example for the route and navigations is not working as expected [live example](https://angular.io/generated/live-examples/router/stackblitz.html)

as per the documentation: 'You'd like to send the id of the current hero with the navigation request so that the HeroListComponent can highlight that hero in its list.'

sending the id as an optional parameter to the herosList component that will be used to highlight the selected hero is not working as expected (the selected hero is not getting highlighted). 

**It may be due to redirectTo, it breaks the optional parameter** sent to the heroes component and we are not getting hero id in the herolist component. 

## Expected behavior
the selected hero should get highlighted (we should get the selected heroId as a part of params in the heroList component).

## Minimal reproduction of the problem with instructions
1) Open the link - [https://angular.io/generated/live-examples/router/stackblitz.html](https://angular.io/generated/live-examples/router/stackblitz.html)

2) Click on Heroes

3) Goto any of the heroes from the list. lets say - 12 Narco

4) Click Back from the hero details.

5) Narco should be highlighted (the optional parameter which we are passing from the hero detail component should be available in the params in the hero list component). which is not.

**Comment by brandonroberts** [comment]
This issue is covered in my router guide updates PR. You can view the live example preview https://pr20023-a1643e3.ngbuilds.io/

**Comment by brandonroberts** [comment]
Fixed via https://github.com/angular/angular/pull/20023
