### ISSUE TITLE
Testability initialization triggers a digest cycle when one might already be in progress

### ISSUE THREAD

**Issue by kiramclean** [angular/angular#24630]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
As of angular 6, the constructor for `Testability` runs things in a zone, and when that zone is empty it triggers a digest cycle. In some tests for an angular 1/angular 6 hybrid app, sometimes `Testability` is not constructed until an angular 1 digest is already in progress, causing the `digest already in progress` error. This was not an issue in angular 5.

## Expected behavior
Tests that work for a hybrid app on angular 5 continue to work with angular 6. 

## Minimal reproduction of the problem with instructions
To reproduce the problem:
- Write a test for an angular 1/angular 6 hybrid app that results in `Testability` being constructed mid-way through the test
  - We saw this happen in our app in a test for an angular 1 component that included some other downgraded components.

## What is the motivation / use case for changing the behavior?
Upgrading a hybrid app to angular 6 shouldn't break tests.

## Environment
<pre><code>
Angular version: 6.0.6
AngularJS version: 1.6.7

**Comment by JiaLiPassion** [comment]
@kiramclean , could you provide a reproduce repo?

**Comment by kiramclean** [comment]
Unfortunately not.. I tried a (very) little bit, but it's quite a combination of things to get running just to write a failing test. The problem is that the constructor for `Testability` triggers an ng1 digest but there may already be one in progress.

**Comment by alxhub** [comment]
@kiramclean unfortunately without a reproduction, we won't be able to fix this issue. I'm tagging this as "needs repro" for now.

**Comment by alxhub** [comment]
Closing as no reproduction is available. Please feel free to re-open the issue with a working reproduction.
