### ISSUE TITLE
Routes with annotations

### ISSUE THREAD

**Issue by chiqui3d** [angular/angular#24648]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have started to read the Angular documentation and I see that you use annotations for the components and also for the services, and why not for the routes?

## Expected behavior
```
import { Component, OnInit } from '@angular/core';
 
import { Hero } from '../hero';
import { HeroService } from '../hero.service';
 

@Component({
  selector: 'app-heroes',
  templateUrl: './heroes.component.html',
  styleUrls: ['./heroes.component.css']
})
@Router({
  path: 'new/path',
  name: 'my_new_path'
})
export class HeroesComponent implements OnInit {
 
  selectedHero: Hero;
 
  heroes: Hero[];
 
  constructor(private heroService: HeroService) { }
 
  ngOnInit() {
    this.getHeroes();
  }
 
  onSelect(hero: Hero): void {
    this.selectedHero = hero;
  }
 
  getHeroes(): void {
    this.heroService.getHeroes()
        .subscribe(heroes => this.heroes = heroes);
  }

}

```

And then in HTML

`<a routerName="my_new_path">Heroes</a>
`

One more thing I don't understand about the services.

```
export class HeroService {
 
  constructor(private messageService: MessageService) { }
 
  getHeroes(): Observable<Hero[]> {
    // TODO: send the message _after_ fetching the heroes
    this.messageService.add('HeroService: fetched heroes');
    return of(HEROES);
  }
}
```

Why complicate programming so much?

It's no easier to get it this way.

```

  getHeroes(): Observable Hero {
 {
    // TODO: send the message _after_ fetching the heroes
    this.messageService.add('HeroService: fetched heroes');
    return of(HEROES);
  }
}
```
OR
```
  getHeroes(Observable Hero) {
 {
    // TODO: send the message _after_ fetching the heroes
    this.messageService.add('HeroService: fetched heroes');
    return of(HEROES);
  }
}
```

Excuse me if I say anything silly.

**Comment by ericmartinezr** [comment]
>and why not for the routes?

That used to be like that, in a very very very very old version of angular (~RC1 and lower). After modules were introduced a lot of things were simplified.

>One more thing I don't understand about the services.

https://www.typescriptlang.org/docs/handbook/functions.html

**Comment by jasonaden** [comment]
Thanks for the feature request. We're looking at possibly introducing some new APIs that would allow routing to be configured declaratively. Since this is already on the radar, I'll go ahead and close this issue.

As far as the type info on the methods, this is simply type declarations. You could always turn them off if you want. In fact, in the example you gave TypeScript will imply the types successfully, so you don't actually even need the return type info:

```
getHeroes() {
    // TODO: send the message _after_ fetching the heroes
    this.messageService.add('HeroService: fetched heroes');
    return of(HEROES);
}
```

**Comment by chiqui3d** [comment]
Awesome. Thank you very much.
