### ISSUE TITLE
Can't simulate keypress on input controls

### ISSUE THREAD

**Issue by mrjohnr** [angular/angular#24640]
## I'm submitting a...

<pre><code>
[X] Other... Please describe: QUESTION
</code></pre>

## Current behavior

Can't simulate tab key press when enter is pressed on input control,in order to focus next control.For that I use a directive:

```
 private el: ElementRef;
    @Input() onEnter: string;
    constructor(private _el: ElementRef, public renderer: Renderer) {
        this.el = this._el;
    }
    @HostListener('keydown', ['$event']) onKeyDown(e: any) {
        if ((e.which === 13 || e.keyCode === 13)) {
            e.preventDefault();


    const event = new KeyboardEvent("keypress", {
            "key": "Tab"
          });
          this.el.nativeElement.dispatchEvent(event);

```............
code for enter key fires but no tab is sent



## Environment

<pre><code>
Angular version: 6.0.5

Browser:
- [X ] Opera (desktop) version 53
For Tooling issues:
- Node version: 9.11.1 
- Platform: Windows

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mrjohnr** [comment]
hi.already posted to stackoverflow: [https://stackoverflow.com/questions/50932956/angular-5-simulate-keypress-on-input-controls/50933576#comment89011545_50933576](url)
