### ISSUE TITLE
Angular testing examples missing for services using http calls.

### ISSUE THREAD

**Issue by raj2033** [angular/angular#24643]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am learning uint testing for services that uses HTTP calls. 
A service is generally used for following task. 

- getData (example for unit testing is available)
- updateData (example for unit testing is available)
- deleteData
- SearchData
- addData
But for last three functionalities, the examples are not given/explained.

The comment present there is: `// TODO: test other HeroService methods`. I guess the work is pending.
Here is the tutorial link

- [tutorial](https://angular.io/guide/http#testing-http-requests)
- [stackblitz code](https://stackblitz.com/angular/bnyjaobgxmp?file=src%2Fapp%2Fheroes%2Fheroes.service.spec.ts)

## Expected behavior

Proper/ complete examples with explanation for beginners.

## Minimal reproduction of the problem with instructions

Everything is working fine according to tutorials. Just need remaining functionalities test cases. 

## What is the motivation / use case for changing the behavior?

Easy for beginners or developers to understand how to write jasmine test cases for angular.

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3  
- Platform: Linux 

Others:
NA

</code></pre>

**Comment by textbook** [comment]
Given that the examples show you how to check the URL, the method and the content, what else would you need to know to cover those additional operations?

**Comment by chembu** [comment]
The example folders are now updated with test samples of the common HTTP calls.

**Comment by chembu** [comment]
Under common/http/test

**Comment by kapunahelewong** [comment]
@raj2033, did @chembu's updates help clarify these points for you?

**Comment by juanri0s** [comment]
@kapunahelewong I know it's been about a good amount of time but is there an update on this task?

I can take on any additional work that it needs, although based on the last update, it seems it's all good to go.
