### ISSUE TITLE
Send method POST but show method OPTIONS

### ISSUE THREAD

**Issue by viniciogomez89** [angular/angular#24647]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I'm using Angular 6, send method POST but show method OPTIONS:

Google Chrome console:
![image](https://user-images.githubusercontent.com/16264396/41820949-31751a02-779f-11e8-866c-b6bebdba5c7e.png)

Slim 3 Framework:
`use App\Sgadm\Model\turnoModel;

$app->group('/sgadm/turno/', function () {

    $this->post('prueba', function ($req, $res, $args) {
        $um = new turnoModel();
        $data = json_encode($req->getParsedBody());
        return
            $res->withHeader("Content-Type", "application/json")
                ->withHeader('Access-Control-Allow-Origin', '*')
                ->withHeader('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type, Accept, Origin, Authorization')
            ->write($data);
    });
`

## Environment
`
import {Component, OnInit} from '@angular/core';
import {HttpClient, HttpHeaders} from '@angular/common/http';
import {Observable} from 'rxjs';

const httpOptions = {
    headers: new HttpHeaders({
        'Content-Type': 'application/json'
    })
};

@Component({
    selector: 'app-turno',
    templateUrl: './turno.component.html',
    styleUrls: ['./turno.component.css']
})
export class TurnoComponent implements OnInit {
    public turnos;

    constructor(private http: HttpClient) {
    }

    ngOnInit() {
        this.getTurnos('gomez');
        // this.getTurnos();
    }

    getTurnos(busqueda: string): void {
             this.http.post('http://localhost:8080/sgh_ws/public/sgadm/turno/prueba', {search: busqueda}).subscribe(
         
            result => {

                console.log('result');
                console.log(result);
            },
            error => {
                console.error(<any>error);
            }
        );
    }

}

`

Postman result body it works:

![image](https://user-images.githubusercontent.com/16264396/41821058-b03da31c-77a0-11e8-8915-e29f8bbf9e33.png)

Postman result header it work include header:
![image](https://user-images.githubusercontent.com/16264396/41821064-bdeda1ec-77a0-11e8-903c-2ef1db5b354a.png)

Angular version: 6.3.0

Browser:
- [x ] Chrome (desktop) version 67
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version 60
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1 
- Platform:  Windows 10.0.17134.112

Others:

Postman v6.1.3
Slim Framework 3

</code></pre>

**Comment by pkozlowski-opensource** [comment]
Nothing to do with Angular, this is CORS (implemented by each browser, not Angular) in action. More info at: https://www.html5rocks.com/en/tutorials/cors/
