### ISSUE TITLE
source map error when using stylus for css styles

### ISSUE THREAD

**Issue by rajinder-yadav** [angular/angular#24641]
## I'm submitting a...

<pre><code>
[X] Bug report  
</code></pre>

## Current behavior

Create a new project using CLI

```sh
ng new app --styles styl
```

```sh
npm i -S bootstrap jquery-slim pooper.js
```

Update file __angular.json__:

```json
            "styles": [
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "src/styles.styl"
            ],
            "scripts": [
              "node_modules/jquery-slim/dist/jquery.slim.min.js",
              "node_modules/popper.js/dist/umd/popper.min.js",
              "node_modules/bootstrap/dist/js/bootstrap.min.js"
            ]
```

Getting a source map error in the debugger console.
```
Source map error: request failed with status 404
Resource URL: http://localhost:4200/
Source Map URL: src/app/app.component.css.map
```

I am able to fix this by renaming, `app.component.style` to `app.component.css` and likewise updating the component code to look for this file for style.

## Expected behavior
No error in debug console.

## Environment

<pre><code>
Angular version: 6.0.2

Browser:
- [X] Firefox version 60.0.2 (64-bit)
 
For Tooling issues:
- Node version: v10.1.0
- Platform:  

Others:

</code></pre>

**Comment by rajinder-yadav** [comment]
Closing, generate a fresh project and the problem is no longer there.

**Comment by rajinder-yadav** [comment]
Unfortunately this is still an issue. Seems like if you include ".css" file in `angular.json` under the `styles` array this source map error shows up.

**Comment by jasonaden** [comment]
Thanks for the issue. Please head over to the [Angular CLI](https://github.com/angular/angular-cli) project and file it there as this appears to only be related to the CLI. You can link back to this issue for context.
