### ISSUE TITLE
access DOM element from super-class component

### ISSUE THREAD

**Issue by chaendler** [angular/angular#24655]
Hello All,

i'm working on a project, where child-class components are dummy and all methods are implemented in super-class components. I tried to manipulate DOM elements of child-class component from super-class components. This scenario can be represented as follows.

SuperClassComponent.ts
```
import {ViewChild, ElementRef} from '@angular/core'

export class SuperClasssComponent{
    @ViewChild("input") input: ElementRef
}

ngAfterViewInit(): void {
        console.log(this.input);
    }

```

ChildClassComponent.ts
```
export ChildClassComponent extends SuperClassComponent{
    
}
```

ChildClassCompoent.html
```
<input #input>
``` 

package.json
```
  "dependencies": {
    "@angular/common": "~2.2.1",
    "@angular/compiler": "~2.2.1",
    "@angular/compiler-cli": "~2.2.1",
    "@angular/core": "~2.2.1",
    "@angular/forms": "~2.2.1",
    "@angular/http": "~2.2.1",
    "@angular/platform-browser": "~2.2.1",
    "@angular/platform-browser-dynamic": "~2.2.1",
    "@angular/platform-server": "~2.2.1",
    "@angular/router": "~3.2.1",
    "@angular/upgrade": "~2.2.1",
    "angular2-in-memory-web-api": "0.0.21",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "ie-shim": "^0.1.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "~0.6.26"
  }
```
The output is "undefined".  Does anyone know the reason why?

Thanks.

**Comment by alxhub** [comment]
Please add a full, working reproduction (e.g. in stackblitz). You're missing the `@Component` decorator on your classes, for example, so it's hard to know what the problem is reading this issue.

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back with the reproduce scenario.
