### ISSUE TITLE
Named Router Outlet not rendering module's components

### ISSUE THREAD

**Issue by mohaqqani** [angular/angular#24651]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am trying to lazyLoad reporting module on successfull adminLogin. I have successfully displayed side-nav using default router-outlet. But issue is when I'm using named router outlet, it is not rendering.

I have used material schematics to generate side-nav and dashboard.

## Expected behavior

I am expecting `<router-outlet name="reporting"></router-outlet>` to render reporting/dashboard in given area. but no error is shown on console(neither on terminal nor on browser)

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-1dthmu 
after login visit click dashboard link in sidenav
https://stackblitz.com/edit/angular-1dthmu

## Environment

<pre><code>
Angular version: 6.0.5

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.11.2  
- Platform:  Angular CLI: 6.0.8
Node: 8.11.2
OS: win32 x64
Angular: 6.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Others:

</code></pre>

**Comment by mohaqqani** [comment]
here is my StackBlitz repo

https://stackblitz.com/edit/angular-1dthmu

**Comment by jasonaden** [comment]
Sorry, the StackBlitz attached doesn't seem to have anything other than the default new content. Also, this sounds more like a support request, which should be filed over on StackOverflow.

If you think there's a specific bug here, please update the StackBlitz so it shows what's happening and file a new bug.

I removed all the code from the comment because it was tough to read. You don't need to list all the code there, just the StackBlitz and the exact steps to reproduce.
