### ISSUE TITLE
bug(http): values from HttpInterceptor are silently ignored when not HttpEvent

### ISSUE THREAD

**Issue by martinsik** [angular/angular#24669]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I have `HttpInterceptor` that doesn't return object that's one of [`HttpEvent` possible types](https://github.com/angular/angular/blob/master/packages/common/http/src/response.ts#L135-L136)  eg. `HttpResponse` it seems like the emission is silently ignored:

```
@Injectable()
export class Interceptor implements HttpInterceptor {
  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return next.handle(request)
      .pipe(catchError(err => {
        return of('Hello' as any);
        // return of(new HttpResponse({ body: 'Hello' }));
      }));
  }
}
```

This will never reach subscribers even though I have a failing HTTP request and the callback for `catchError` is invoked.

When I uncomment `of(new HttpResponse({ body: 'Hello' }))` you can see `"Next:
Hello"` printed in console.

## Expected behavior

When I try to emit anything other than `HttpEvent` (basically anything that can't be propagated further) it should throw an error.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-qtmdxp?file=src%2Fapp%2Finterceptor.ts

## What is the motivation / use case for changing the behavior?

It's very easy to do this by mistake and then it's very confusing why it doesn't work.

## Environment

This is most likely not browser dependent behavior.

<pre><code>
Angular version: 6.0.6

Browser:
- [X] Chrome (desktop) version 67
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by trotyl** [comment]
The typings make it clear that only `HttpEvent`s are allowed:

https://github.com/angular/angular/blob/166d90d2a98908898fe9cf482f7b91208b03e685/packages/common/http/src/interceptor.ts#L44

I don't think check against the violating static types usage is worthy, but just increasing bundle size and impact performance.

The problem in your demo is due to `any` type being skipped in type-checking, likely would be solved by https://github.com/Microsoft/TypeScript/pull/24423.

**Comment by alxhub** [comment]
@trotyl is correct.
