### ISSUE TITLE
add npm package ts-loader to Angular Universal sample code

### ISSUE THREAD

**Issue by carstenbaumhoegger** [angular/angular#24671]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Following error appears when running `npm run build:ssr`: 
```
ERROR in Entry module not found: Error: Can't resolve 'ts-loader' in '/x/y/z/server-side-rendering'
```

## Expected behavior

`ts-loader` is part of the `package.json` and does not need to be installed manually.

## Minimal reproduction of the problem with instructions
1. Download the finished sample code from [here](https://angular.io/guide/universal)
2. open the unzipped folder and run `npm install`
3. run `npm run build:ssr`

## What is the motivation / use case for changing the behavior?

The module `ts-loader` should be added to the `package.json`, so that new users don't need to install it manually for running the sample code.

## Environment

<pre><code>
Angular version: 6.0.6

 
For Tooling issues:
- Node version: 10.5.0
- Platform:  Mac
</code></pre>

**Comment by jenniferfell** [comment]
Thanks for your suggestion. 

Current state: The section "Install the tools" in "Preparation" includes ts-loader in the list of packages that users must install before using this example. The npm install command shown in the docs includes ts-loader.

I'm marking this issue to consider as a feature request. If we can reduce the number of setup steps before using this example--such as by including ts-loader--then I agree that's a good idea.

**Comment by carstenbaumhoegger** [comment]
thanks for your comment @jenniferfell !
I didn't do the "Preparation" steps, because I was just interested in SSR.
That's because I just clicked on the link, downloaded the sample and tried to play with it.

I personally like examples that work out of the box but if all examples require the preparation and I'm the only one "complaining" about that, then I should work through the preparation part of the docs next time 😄

**Comment by Lostlover** [comment]
I have the same trouble as you ！   @carstenbaumhoegger

**Comment by brandonroberts** [comment]
This was a regression from https://github.com/angular/angular/pull/24478. I'll have a fix in shortly
