### ISSUE TITLE
why such tight coupling between components in descendent trees? 

### ISSUE THREAD

**Issue by laurencefass** [angular/angular#24676]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[x ] Other... Please describe: router design issue.
</code></pre>

## Current behavior

there is a tight coupling between descendents of 3 or more generations of components.

consider the following router configuration for a ParentComponent
{
    path: 'child',
    component: ChildComponent,
    children: [
      {path: 'grandchild', component: GrandChildComponent},
    ]
}

Why is there a tight coupling between the Parent and the Grandchild?

## Expected behavior

Would it be better design to define the Grandchild route within the ChildComponent and load the route only when the Child is loaded? This would certainly make 2nd generation component routes more portable with less coupling between 3rd generation routing relationships.

## What is the motivation / use case for changing the behavior?

Use case = pretty much any routing configuration involving 3 generations of components.

## Environment
<pre><code>
Angular version: angular 6+

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by spock123** [comment]
Without being an export, I assume this is because Angular has to know where to insert the components.

It uses the <router-outlet></router-outlet> of the parent component to insert child components. Without a parent component, how should the router know where to inject the child component?

**Comment by robwormald** [comment]
If you want more flexible routing configurations, you can use lazy-loading / loadChildren to configure routing (which is what you asked for - the child *module* would define the child routing. See https://angular.io/guide/lazy-loading-ngmodules

**Comment by laurencefass** [comment]
i found the ngmodules shortly after submitted which works fine but question remains about the design of the non-lazy component tree.

how would we define an n-tiered component tree using this format? i.e. children of children etc?

thanks
