### ISSUE TITLE
Injector injects undefined value for aliased export of service (in AoT, prod build)

### ISSUE THREAD

**Issue by dherges** [angular/angular#24675]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Here is a copy of my source code. If request, I'll try to put a minimal repro on agithub repo.

```ts
@Injectable()
export class ContentApiService {
  constructor(private http: HttpClient) {}

  foobar(): Observable<any> {
    // -> in AoT prod build: this.http is undefined
    // -> in JiT, dev build: it works
    return this.http.get<any>(`blabla.json`);
  }
}

export { ContentApiService as DocumentsApiService };
```

```ts
import { DocumentsApiService } from '../../content/api/documents-api.service';

@Injectable()
export class DocumentsEffects {

  constructor(
    /* When injected with the aliased export, the error occurs (`httpClient` injected in the service is undefined).
     * When injected with the original export (ContentApiService), the injected `HttpClient` is defined.
     */
    private documentsApi: DocumentsApiService 
  ) {}

  doThings() {
    this.documentsApi.foobar();
  }
}
```

```ts
import { NgModule, ModuleWithProviders } from '@angular/core';
import { ContentApiService } from './api/documents-api.service';

const providers = [ContentApiService];

@NgModule({})
export class ContentModule {
  public static forRoot(): ModuleWithProviders {
    return { ngModule: ContentModule, providers };
  }
}
```

```ts
@NgModule({
  imports: [
    HttpClientModule,
    ContentModule.forRoot()
  ]
})
export class AppModule {}
```

## Expected behavior

Consistent behaviour in JiT and AoT.

I have not tried out whether adding both `DocumentsApiService` (the alised export) and `ContentApiService` (the original export) to the `providers: []` would solve the error. If request, I take a look.

## Minimal reproduction of the problem with instructions

See above.

## What is the motivation / use case for changing the behavior?

See above.

## Environment

<pre><code>
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.0.8
Node: 8.9.1
OS: win32 x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      5.2.5
@angular/cli                      6.0.8
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.1
@schematics/update                0.6.8
ng-packagr                        3.0.3
rxjs                              6.2.1
typescript                        2.6.2
webpack                           4.8.3
</code></pre>

Note: need to check whether this was solved in v6.

**Comment by alxhub** [comment]
Thank you for the awesome bug report!

**Comment by dherges** [comment]
Here is the repro: https://github.com/dherges/ng-issue24675

**Comment by loicsalou** [comment]
looks like I have same issue when using imports like "import * as firebase from 'firebase'". Getting ugly message "Uncaught Error: Cannot find module "."" only when aot build, working fine in JIT.

**Comment by loicsalou** [comment]
to anyone this might help: my issue looked similar but actually was not. I had a problem coming from usage of typescript 2.9.2 with @angular/...@6.1.0-rc.3. 
The fact that @types/bluebird recently required typescript > 2.8.0 sort of pushed me towards such recent libs combination but everything is not mature enough yet.

**Comment by JoostK** [comment]
I just tested this in Angular 9.0 and the issue has indeed been resolved when using Ivy :-)
