### ISSUE TITLE
Quickstart doesn't seem to work with polymer components

### ISSUE THREAD

**Issue by RobertGardner** [angular/angular#2467]
If you add the following to the Quickstart's index.html the chart does not draw:
```html
<link rel="import" href="bower_components/google-chart/google-chart.html">
<google-chart
  type='geo'
  data='[["Country", "Popularity"],
       ["Germany", 200],
       ["United States", 300],
       ["Brazil", 400],
       ["Canada", 500],
       ["France", 600],
       ["RU", 700]]'>
</google-chart>
```

It seems to be because of a zones.js conflict. At least, that's where the exception is thrown.

(Of course, if you comment out all the angular2 script imports then the chart does draw.)

**Comment by mhevery** [comment]
Closing as obsolete. Please reopen if still an issue.
