### ISSUE TITLE
i18n Resources escape HTML tags in v6

### ISSUE THREAD

**Issue by IgorWolbers** [angular/angular#24679]
## I'm submitting a...
<pre><code>[X] Bug report</code></pre>

## Current behavior
In version 6 of angular translations/texts that contain HTML markup are displayed as verbatim strings.

## Expected behavior
Translations/texts that contain HTML markup should render the HTML markup **or** the changelog should identify that this is a breaking change and mention how to work around this after upgrading.

## Minimal reproduction of the problem with instructions

*html code for any component*

    <span i18n="@@ImportIntro">Import the Excel file.&lt;br&gt;The Excel file must contain the following:&lt;br&gt;More information</span>
	
The resources can be extracted using the cli although I found this is not necessary to reproduce the issue.

    ng xi18n --i18n-locale en --i18nFormat xlf2 --outFile ../Resources/translations.xliff2.xlf
	
Run the application using the angular-cli, it does not matter if it is a production build or just using `ng serve`. The build can be executed with or without pointing to an i18n file, the result will be the same.

The output as it appears in the browser:

    Import the Excel file.<br>The Excel file must contain the following:<br>More information
	
In previous versions including 5 and 4 the included `<br>` tags were rendered as html so the browser would display this

    Import the Excel file.
    The Excel file must contain the following:
    More information

## What is the motivation / use case for changing the behavior?
This is a breaking change from version 5 and I could not find anything in the change log or existing issues about this.

## Environment

	Angular CLI: 6.0.8
	Node: 10.4.1
	OS: win32 x64
	Angular: 6.0.6
	... animations, common, compiler, compiler-cli, core, forms
	... http, language-service, platform-browser
	... platform-browser-dynamic, router

	Package                           Version
	-----------------------------------------------------------
	@angular-devkit/architect         0.6.8
	@angular-devkit/build-angular     0.6.8
	@angular-devkit/build-optimizer   0.6.8
	@angular-devkit/core              0.6.8
	@angular-devkit/schematics        0.6.8
	@angular/cdk                      6.3.0
	@angular/cli                      6.0.8
	@angular/material                 6.3.0
	@ngtools/webpack                  6.0.8
	@schematics/angular               0.6.8
	@schematics/update                0.6.8
	rxjs                              6.2.1
	typescript                        2.7.2
	webpack                           4.8.3

----
*personal side note: I really love this framework, thank you everyone involved for making angular so awesome!*

**Comment by IgorWolbers** [comment]
I guess I should have persisted in my attempts to fix the issue just a little longer. The fix is to remove the escaped html syntax from the template and use unescaped html syntax directly.

    <span i18n="@@ImportIntro">Import the Excel file.&lt;br&gt;The Excel file must contain the following:&lt;br&gt;More information</span>

should be

    <span i18n="@@ImportIntro">Import the Excel file.<br/>The Excel file must contain the following:<br/>More information</span>

Which then gets pushed to the resource  file as

    <source>Import the Excel file.<ph id="0" equiv="LINE_BREAK" type="fmt" disp="&lt;br/&gt;"/>The Excel file must contain the following:<ph id="0" equiv="LINE_BREAK" type="fmt" disp="&lt;br/&gt;"/>More information</source>

The output in the browser now renders the `br` tags correctly. I am not sure if this is a bug or not as there was nothing in the documentation about this being fixed or a change in behavior. I will close the issue but not delete it in case someone else comes across this.

**Comment by colorpump** [comment]
See #25242 i18n: Adding HTML tags in target translation doesn't work anymore in v6:

I have a similar issue, but I (my translation tool) used escaped HTML Tags to insert HTML in translation **not in original HTML content but in target translation**. This is not working anymore - but was helpful to add line breaks, bold text, etc. only in certain languages.

So above solution doesn't help in this case.
