### ISSUE TITLE
Dynamically created objects for configuration for Modules fail when build for production

### ISSUE THREAD

**Issue by bobslaede** [angular/angular#24672]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Creating a configuration object in an AppModule, and giving it to a different module in a forRoot method will break the object when in a production build.
If the object is made from variables, or from things that have been toString()'ed it will break.

## Expected behavior
Providing configuration in a forRoot method on a module should work as expected.  
It should not matter if it is a dev build or production.

## Minimal reproduction of the problem with instructions
Steps to reproduce:  
* Create AppModule
* Create ConfigModule with static forRoot method for providing configuration
* Create configuration obj in AppModule, combining it with properties from for example window.location, or foo.bar
* Observe that when used in ConfigModule.ConfigService the ConfigConfiguration is broken  

https://stackblitz.com/edit/angular-gitter-2he4x6?file=app%2Fapp.module.ts  
Stackblitz is running in dev mode  
https://angular-bug.firebaseapp.com/  
Code hosted on firebase is running in production mode  

## What is the motivation / use case for changing the behavior?
It should be possible to create a configuration object dynamically, without it breaking in production builds

## Environment

<pre><code>
Angular CLI: 6.0.8
Node: 10.3.0
OS: win32 x64
Angular: 6.0.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3

Browser:
- [x] Chrome (desktop) version 67.0.3396.87
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 60.0.2 
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [x] Edge version  41.16299.492.0
 
For Tooling issues:
- Angular Cli  6.0.8
- Node version: v10.3.0
- Platform:  Windows 10 64bit

Others:

</code></pre>

**Comment by alxhub** [comment]
This is WAI for Angular 6.x. `ngc` attempts to statically resolve the call to `forRoot` at compile time, and evaluating the template strings in the config object returns the results you see.

Fortunately, DI is entirely a runtime concept in Ivy, and so this example should work in that case.

**Comment by bobslaede** [comment]
Thanks for the clarification. I will just use an injection token to inject configuration instead of a forRoot method.  
Could you maybe explain why the line evaluated from `location.origin.toString()` totally goes missing?

**Comment by pkozlowski-opensource** [comment]
This continues to be an issue in Angular v9 with ivy: https://ng-run.com/edit/iv2arHfCpzQbPkcnuXzS

**Comment by JoostK** [comment]
This limitation has been lifted in Angular Ivy: [see Stackblitz](https://stackblitz.com/edit/angular-ivy-ux6iwt?file=src%2Fapp%2Fapp.module.ts).
