### ISSUE TITLE
Document service workers don't support upload progress for httpClient `reportProgress`

### ISSUE THREAD

**Issue by epelc** [angular/angular#24683]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I believe service workers do not support reporting upload progress(download progress should work) since it basically acts as a proxy and converts all `XMLHttpRequest`s to the fetch api. This should be documented to avoid confusion. I just spent several hours trying to figure out why upload progress doesn't work when you use service workers.

Some more info on why:
- Service workers act as a proxy for all requests
- Requests come in as XmlHttpRequest or fetch and are always sent out to your server as a fetch request.
- This can't be changed since service workers [only support using the newer fetch api](https://www.fxsitecompat.com/en-CA/docs/2015/xmlhttprequest-is-no-longer-available-in-service-workers/)

- Fetch doesn't support upload progress(it's not in the spec yet)
>“it [fetch] is currently lacking when it comes to request progression (not response progression).” https://fetch.spec.whatwg.org/#fetch-api

![image](https://user-images.githubusercontent.com/5204642/41949194-53d2c0c2-798e-11e8-9fed-67f2fb5395cf.png)
the first uses xhr(XMLHttpRequest) but goes out of the service worker as a fetch request which is why you can’t get upload progress info

## Expected behavior

Basically the docs should state that `reportProgress` doesn't work when using a service worker due to fetch api limitations.

## What is the motivation / use case for changing the behavior?

Documenting this would make using service workers less confusing. Without these docs you have to dig deep and understand/know about more internals for XmlHttpRequest, fetch, how service workers actually work, etc.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) Version 67.0.3396.87 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by epelc** [comment]
Here is the relevant feature spec that will add support fetch upload progress. It seems a ways off so docs would be good until then.

It's called `FetchObserver`
https://github.com/whatwg/fetch/issues/607

**Comment by jenniferfell** [comment]
@epelc Thanks for this research and clarification. I'm checking with engineering to ensure that they agree this is a useful/correct doc addition.

**Comment by alxhub** [comment]
@jenniferfell this is a useful addition, albeit an esoteric one.

**Comment by tzahari** [comment]
It would be great if there is a possibility to configure the http request or the service worker not to intercept specific requests. Then the progress listener would work again.

**Comment by oliverjanik** [comment]
Since when are file uploads esoteric? Browser and library authors need to treat file uploads as a first class citizen. Literally every line of business app has some form of attachment upload.

**Comment by Jun711** [comment]
@tzahari 
For a temporary workaround, you can modify your ngsw-worker.js. Look for onFetch function, you should modify the function so that it stops executing when detecting your upload endpoint.

```javascript
onFetch(event) {
  if (event.request.url.indexOf('up2?apikey') !== -1) {
    return;
  }
  ...
}
```

You can check out this [article](https://jun711.github.io/web/how-to-listen-for-upload-progress-in-service-worker-and-progressive-web-app/) for more information.

**Comment by Jun711** [comment]
@tzahari 
For a temporary workaround, you can modify your ngsw-worker.js. Look for onFetch function, modify the function so that it stops executing when detecting your upload endpoint.

```javascript
onFetch(event) {
  if (event.request.url.indexOf('upload') !== -1) {
    return;
  }
  ...
}
```

You can check out this [article](https://jun711.github.io/web/how-to-listen-for-upload-progress-in-service-worker-and-progressive-web-app/) for more information.

**Comment by sachq** [comment]
Is there any workaround other than modifying `ngsw-worker.js`? 

Thanks.

**Comment by FreakTheMighty** [comment]
Should this be closed? It seems like https://github.com/angular/angular/issues/21191 resolves this issue.

@sachq

**Comment by epelc** [comment]
@FreakTheMighty thanks for the link. To be clear see the pr for that issue https://github.com/angular/angular/commit/6200732e2360690532686c131add006cd29f3b61 There are now docs about setting a special header or other flags to bypass the service worker entirely for specific requests.
