### ISSUE TITLE
JSON.parse doesn't Date as string

### ISSUE THREAD

**Issue by xanscale** [angular/angular#24687]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
https://weblog.west-wind.com/posts/2014/Jan/06/JavaScript-JSON-Date-Parsing-and-real-Dates

## Expected behavior
if in model var is a Date, i expect that will be a date. something like "a = new Date(a)"

## What is the motivation / use case for changing the behavior?
each time rest return a date in iso8601 require something like "a = new Date(a)" or an interceptor like
https://gist.github.com/martinobordin/39bb1fe3400a29c1078dec00ff76bba9

## Environment
<pre><code>Angular version: 6.0.6
Browser: indipendent
For Tooling issues:
- Node version: indipendent
- Platform:  indipendent</code></pre>

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/20770, https://github.com/angular/angular/issues/21107, https://github.com/angular/angular/issues/24456

**Comment by xanscale** [comment]
sorry
