### ISSUE TITLE
feature: ability to highlight section within (or to expand context for) a docregion

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#24681]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ X] Other... Please describe: AIO infrastructure
</code></pre>

## Current behavior

docregion marks code in an example app that can be included and shown in the docs. The entire docregion is shown in the doc, with pretty-printing applied to show structure of code. There is no way to highlight the area on which you want the user to focus. Or alternatively, there is no way to include additional context around the area you want to show. All content is shown the same way.

## Expected behavior

In PR https://github.com/angular/angular/pull/19715 @gkalpak suggested: "I think it might be useful to introduce a new feature for context in docregions that show adding to or modifying an existing file. I.e. 1-2 lines above and below the affected lines would appear grayed-out (to show what was there before the change), while the affected lines would be highlighted in color as usual."

I think that would be ideal! Configurable on a per-case basis would be super cool, but even just always grabbing 2 lines above/below and including them with a lighter font or gray background would be good. Or we could have a button and let user control "show me context" to pop open the window to show 5 lines above and below. Another option would be to let us make some code bold within a docregion (so an additional tag such as docfocus) so that it stands out within a docregion.

## What is the motivation / use case for changing the behavior?

Provide more context around a code snippet.
Highlight the area of focus within a code snippet.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
To be clear, I don't think it is possible to expand the docregion "on-demand", because docregions often come from different parts of the file and the lines that are around them do not necessarily make sense for the specific thing that the docregion is showcasing.

What I was refering to, was the ability to specify that within a docregion, particular lines are of interest (and should be highlighted, while others are just for context (and should be grayed out or something).

Off the top of my head, here is the proposed API:

```ts
...
// #docregion heroes-property
export class HeroesComponent implements OnInit {
  // #docregion-highlight heroes-property
  heroes = HEROES;
  // #docregion-endhighlight heroes-property
  // #enddocregion heroes-property
  selectedHero: Hero;

  constructor() { ... }

  ngOnInit() { ... }
// #docregion heroes-property
}
// #enddocregion heroes-property
```

This would show docregion `heroes-property` as usual:

```ts
export class HeroesComponent implements OnInit {
  heroes = HEROES;
  /* . . . */
}
```

...except that the `heroes = HEROES` line would be "highlighted" (whatever we decide this means :grin:).

**Comment by jenniferfell** [comment]
@StephenFluin @brandonroberts FYI...this is the open issue I mentioned re being able to highlight within a code example

**Comment by petebacondarwin** [comment]
Closing as this issue has limited benefit for a fair amount of work and has not seen any follow up requests from the current docs team. Also the current docs workflow puts a lot of onus on the engineering team to create and mark up examples, so adding further features to doc-region support without clear need will not help with engineering capacity.
