### ISSUE TITLE
Angular based Electron app does not trigger click events with touch screen on macOS

### ISSUE THREAD

**Issue by BenBergman** [angular/angular#24694]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Tapping a button on a touch screen in an Angular app wrapped in Electron triggers `mousedown` events but not click events. The same Angular app packaged using Cordova and targeting platform `osx` works just fine for triggering click events. I also have another Electron app that does not use Angular that works just fine with click events on the same hardware and the same version of Electron.

## Expected behavior
Angular apps built with Electron should trigger click events when tapped using a touch screen.

## Minimal reproduction of the problem with instructions
I have built a minimal Angular+Electron project based on this tutorial that reproduces the bug: https://github.com/BenBergman/angular-electron-tap-bug-test

``` sh
$ git clone https://github.com/BenBergman/angular-electron-tap-bug-test.git
$ cd angular-electron-tap-bug-test
$ npm install
$ npm run electron-build
```

## Environment

<pre><code>
Angular version: 6.0.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [X] Electron version v2.0.3
 
For Tooling issues:
- Node version: v10.4.1
- Platform:  macOS High Sierra - 10.13.5 (17F77)

Others:

</code></pre>

I have also filed [a bug with Electron](https://github.com/electron/electron/issues/13474) as I'm not sure where the issue lies.

**Comment by robwormald** [comment]
It would be surprising if the click etc events aren't triggered at all. Can you narrow this down a bit? Is it that the event isn't firing at all(?), or is it that change detection isn't being run after the event?

Easy check:
```ts
@Component({ template: `Count: {{count}} <button (eventname)="increment()">` })
class TestComponent {
  count = 0;
  increment(){
   console.log('event fired');
   this.count++;
 }
}
```
- if the log works but the UI doesn't update, that would indicate a Zone issue
- it the log doesnt work at all, something else is going on

**Comment by BenBergman** [comment]
Thanks for the suggestion. I added your code to my test app. Clicking the button with the mouse fires updates the counter and the log. Tapping the button with the touch screen does not affect either (but the button does become "active" so something is happening at least at the CSS level).

**Comment by robwormald** [comment]
That would indicate an issue with Zones. be sure you have the electron zone extra pulled in - https://github.com/angular/zone.js/tree/master/lib/extra - and if that doesn't work, open an issue in the angular/zone.js issue. Thanks!

**Comment by BenBergman** [comment]
@robwormald Thanks for the tip. How exactly should I that be "pulled in"? I did an `npm install zone.js` and added `import 'zone.js/dist/zone-patch-electron` to `src/polyfills.ts` under the zone import already created by Angular CLI. This alone didn't fix anything so I'm not sure if I'm missing something else to activate the patch or if this is a bug that needs reporting.

**Comment by JiaLiPassion** [comment]
@BenBergman, please post this issue to zone.js repository and I am not sure how to test it, do I need a touchable device?

**Comment by BenBergman** [comment]
@JiaLiPassion I have been testing this using a touch screen connected to a Mac Mini. I'm not sure if there is a way to test it without using a touch screen. I have opened an issue with zone.js so we can continue discussing there.
