### ISSUE TITLE
Animations not mantaining width after it ends

### ISSUE THREAD

**Issue by Hbck** [angular/angular#24698]
[ x] Bug report  

## Current behavior
When the animation completes, its width reverts to the original value defined in css/html. The width values from the states are completely ignored.

## Expected behavior
The width after the animation completes should be the same as the corresponding state.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/ZtbBlsVC4IwvR9u58acF?p=preview

## What is the motivation / use case for changing the behavior?
Proper animation and styling.

## Environment
Windows 10,  Angular version: 6.0.2, npm, angular cli

Browser:
- [ x] Chrome (desktop) version 67.0 

## Other
A somewhate related issue: https://github.com/angular/angular/issues/16919

**Comment by dario-piotrowicz** [comment]
The issue still exists in angular 12, I've re-created the example in stackblitz: https://stackblitz.com/edit/angular-animation-end-width-bug

and opened a PR with the fix :slightly_smiling_face:
