### ISSUE TITLE
some angular.io stackblitz live examples not working in firefox 61

### ISSUE THREAD

**Issue by laurencefass** [angular/angular#24696]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
This live example not working in firefox 61. i noticed couple of others too. most work. https://angular.io/guide/dynamic-component-loader

## Expected behavior
works in latest chrome.

## What is the motivation / use case for changing the behavior?

n/a

## Environment
firefox 61

<pre><code>
Angular version: 6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x] Firefox version 61
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Stackblitz

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Dup of 99% of these https://github.com/angular/angular/search?q=adblock&type=Issues
