### ISSUE TITLE
Select input is very slow show and bank delay

### ISSUE THREAD

**Issue by phamxuancan** [angular/angular#24706]
Hi,
I have a problem with angular 4 on chome when rendering big view about 500 row data, and in a row has select input, this happen when i click select. It show options of select is very slow. Please support my case!
image error : 
![image](https://user-images.githubusercontent.com/5526128/42069590-df7912a8-7b7c-11e8-852a-a6492782a873.png)
after 10s data done to load : 
![image](https://user-images.githubusercontent.com/5526128/42069718-6fcc4dde-7b7d-11e8-8de0-44878ad94dda.png)

Please check , thank you!

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
