### ISSUE TITLE
Angular AIO General Setup for Authoring - Yarn fails

### ISSUE THREAD

**Issue by FrederikSchlemmer** [angular/angular#24709]
## I'm submitting a...

<pre><code>
[ ? ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ x ] Other... Please describe:
The instructions in the README.md under "angular/aio" to get a general setup doesn't work anymore. After executing "yarn setup" an error occurs (see screenshot).
</code></pre>

## Current behavior
After executing the "yarn setup" an error occurs and general setup can't be completed. That's why it's impossible to generate documentation or local builds.
The errors seems to be related to the generation process of the documentation files. 

Also tested:
- yarn cache clean - No Improvement
- Executing "yarn" before "yarn setup" - No Improvement
- Cloning the repository again - No Improvement

![error](https://user-images.githubusercontent.com/35023083/42078087-79f8bdee-7b7b-11e8-99e8-2ebbd0d3c751.PNG)

## Expected behavior
General setup should run through without any errors.

## Minimal reproduction of the problem with instructions
Steps to reproduce:
- Install the latest Yarn version
- Fork and clone the Angular Repo
- Open a terminal (administration rights required) and navigate into the folder "angular/aio"
- Execute "yarn setup"

## What is the motivation / use case for changing the behavior?
Generating docs is essential for contributing to angular.

## Environment

<pre><code>
Angular version: Latest Repo version

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.11.2  
- Yarn version: v1.7.0
- Platform:  Windows 10 

Others:

</code></pre>

**Comment by s-gbz** [comment]
I have the same problem on Windows 10 Enterprise Version 1709 (Build 16299.431).

**Comment by gkalpak** [comment]
It works for me 😕

**Comment by gkalpak** [comment]
Oh, it's because `packages/upgrade/static/src` is a linux-style symlink to `packages/upgrade/src`. Windows doesn't recognize it and can't find `downgrade_module.ts`.

There are some scripts in `scripts/windows/` which you can use to update/restore those symlinks (require admin rights, if you haven't enabled Windows dev mode).

**Comment by gkalpak** [comment]
We should probably document that, though (or somehow automate it).

**Comment by gkalpak** [comment]
Would one of you be interested in adding a note in `aio/README.md`? 🙏

**Comment by FrederikSchlemmer** [comment]
@gkalpak Thanks for the reply! I executed the "remove-symlinks.sh"  first and then "create-symlinks.sh" in angular/scripts/windows as a Admin and now I can execute "yarn setup" without any problems.

I will create a PR with a note in aio/README.md!

**Comment by FrederikSchlemmer** [comment]
@gkalpak I just created the Pull Request #24714. Maybe you got time to do a review?
