### ISSUE TITLE
ERROR TypeError: Cannot read property 'Stream' of undefined

### ISSUE THREAD

**Issue by Antonyselt** [angular/angular#24702]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I tried to upload a file with aws-sdk to a s3 bucket, here is my code

`
this.selectedFile = event.target.files;
		const AWSService = AWS;
		const region = 'us-east-1';
		const bucketName = 'my-bucket-name';
		const IdentityPoolId = 'my-identity-pool-id';
		const file = this.selectedFile.item(0);
		AWSService.config.update({
			region: region,
			credentials: new AWSService.CognitoIdentityCredentials({
				IdentityPoolId: IdentityPoolId
			})
		});
		const s3 = new AWSService.S3({
			apiVersion: '2006-03-01',
			params: { Bucket: bucketName}
		});
		this.image = file.name;
		s3.upload({
			Key: file.name,
			Bucket: bucketName,
			Body: file,
			ACL: 'public-read'
		}, function (err, data) {
			if (err) {
				console.log(err, 'there was an error uploading your file');
			} else {
				console.log(data);
			}
		});
`

## Expected behavior
It should upload the file but is not uploading and I got the following error:

`ERROR TypeError: Cannot read property 'Stream' of undefined`

And it works fine in Angular 5

## Minimal reproduction of the problem with instructions

Creat an new angular 6 app and configure a new bucket in amazon s3

and if it helps I add you a link for to ways of doing that

[one in angular 4](http://javasampleapproach.com/frontend/angular/angular-4-amazon-s3-example-how-to-upload-file-to-s3-bucket)
[Other with angular 5](https://medium.com/@bevin.hernandez/angular-5-file-uploads-to-s3-with-relative-ease-ea19b7fd120e)
<pre><code>
Angular version: 6.0.6

Browser:
- [x] Chrome (desktop) Versión 67.0.3396.99 (Build oficial) (64 bits)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.3.0 
- Platform: Windows 10

Others:

Visual studio code
npm

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
