### ISSUE TITLE
POST method calling from service Angular 6 to the REST using web api in asp.net mvc

### ISSUE THREAD

**Issue by kambleaa007** [angular/angular#24708]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

OPTIONS http://localhost:51156/api/values 400 (Bad Request)

Failed to load http://localhost:51156/api/values: Response for preflight has invalid HTTP status code 400.

in service

postTest(student: Student) {

    console.log("In service " + student);
    return this._httpService.post('http://localhost:51156/api/students', student);

}
in component.ts calling from front end

 postTest(){
    console.log("see now ..."+this.student);
    this.uservice.postTest(this.student).subscribe();
  }
front end : HTML data

 <button type="submit" class="btn btn-primary" (click)="postTest()">TEST</button>
errors at console debugging:- google chrome

Angular is running in the development mode. Call enableProdMode() to enable 
the production mode.
user.component.ts:47 see now ...[object Object]
user-service.service.ts:100 In service [object Object]
2zone.js:2969 OPTIONS http://localhost:51156/api/students 400 (Bad Request)
scheduleTask @ zone.js:2969
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ 
zone.js:407
GET works fine for me but POST bad request (POST also works well with the POSTMAN tool so no problem in asp.net web api code) searched lots of websites but doesnt rings bells With postman i tested json data it works fine with postman I making mistake while calling http.post() method forgetting something SYNTAX might wrong in 'angular 6' How you people calls post method from angular I tested postman works fine What syntax in angular 6

OPTIONS http://localhost:51156/api/students 400 (Bad Request)
Failed to load http://localhost:51156/api/students: Response for preflight 
has invalid HTTP status code 400.
Response {_body: ProgressEvent, status: 0, ok: false, statusText: "", 
headers: Headers, …}
Modified to

postTest(){ console.log("see now ..."+this.student); 
console.log(this.student) this.uservice.postTest(this.student).subscribe( 
success => { console.log("success"+success) }, error => { console.log("errrr 
"+error) } ); } 
and OUTPUT is

 errrr Response with status: 0 for URL: null 
"Help me to solve quick wasted whole two days in this .........."

Hitting

     http://localhost:51156/api/students from POSTMAN
Passing

Body{"Sid":1,"fname":"Sss","lname":"XYZ","rollno":666,"address":null,"marks":0," grade":null,"discount":0.0}

raw JSON (application/json)

then after send clicked status 200 OK

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
