### ISSUE TITLE
set max line length for content area of documentation

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#24707]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ X] Other... Please describe: AIO styles
</code></pre>

## Current behavior

Currently, if I'm viewing the Angular docs (angular.io/docs) from a wide device, each line of text in the main center frame will be as long as absolutely possible. 

## Expected behavior

Do not allow text in the main center frame to go beyond 75 characters. If the screen is wider, then add white space left rather than continuing to expand text area. 

## Minimal reproduction of the problem with instructions

See above.

## What is the motivation / use case for changing the behavior?

Reason: Optimal line length for reading is in the 60-75 character range, depending on which research you use. All research agrees that lines over 75 characters are hard to read. The eye simply cannot effectively scan and read longer lines, so long lines limit comprehension.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
I agree on having a max width, but 75 chars is way to few imo. Unless we have a two-column layout, which fills a little weird for the docs :/

**Comment by Splaktar** [comment]
Added screenshots that demonstrate this issue to https://github.com/angular/angular/issues/22246#issuecomment-575447837.

**Comment by jessicajaniuk** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
