### ISSUE TITLE
BrowserAnimationsModule should guard against being lazy loaded

### ISSUE THREAD

**Issue by jasonaden** [angular/angular#24717]
When `BrowserAnimationsModule` gets lazy loaded, it will create two renderers. Among possible other issues, this causes a situation where when removing elements, the removals get enqueued in one renderer and dequeued from another, meaning nothing gets removed.

We should throw an error when `BrowserAnimationsModule` is lazy loaded.

Internal repro b/199209336

**Comment by JeanMeche** [comment]
Isn't that (at least partially) fixed by #45826 ? 

Angular throws now an error when  `BrowserModule` providers are loaded twice. That's exactly what a lazy import of `BrowserAnimationsModule` does.

**Comment by AndrewKushnir** [comment]
@JeanMeche yes, I think we can close this ticket. Thanks for the comment.
