### ISSUE TITLE
CanLoad when navigate to "/" and return false. The route "/" not triggered on redirect to him

### ISSUE THREAD

**Issue by yuriystovbur** [angular/angular#24715]
## I'm submitting a...

<pre><code>[x] Bug report. CanLoad Guard with Route.navigate(['/'])</code></pre>
Previous issue: https://github.com/angular/angular/issues/16197

## Current behavior
routes:
<pre><code>[
    {
        path: '',
        loadChildren: 'app/dashboard/dashboard.module#DashboardModule'
    },
    {
        path: 'test',
        loadChildren: 'app/test/test.module#TestModule',
        canLoad: [RedirectGuard]
    },
    {
        path: '**',
        redirectTo: '/'
    }
];
</code></pre>
canLoad:
<pre><code>export class RedirectGuard implements CanLoad {
    constructor(private _router: Router) {}
    canLoad() {
      this._router.navigate(['/']);
      return false;
    }
}
</code></pre>

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-4kt7bp
If I open https://angular-4kt7bp.stackblitz.io/test the route "/" not triggered on redirect to him

## Environment

<pre><code>Angular version: 5.2.11

Browser:
- [x] Any browser
</code></pre>

**Comment by Sidd27** [comment]
Is Angular Team Fixing this bug?

**Comment by atscott** [comment]
This issue appears to be resolved in v10: https://stackblitz.com/edit/angular-nhesda
