### ISSUE TITLE
design problem with non-lazy n-tiered routing?

### ISSUE THREAD

**Issue by laurencefass** [angular/angular#24710]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[x ] Other... Please describe: router design issue.
</code></pre>

## Current behavior

there is a tight coupling between descendents of 3 or more generations of components. i submitted an issue but it was closed down immediately without discussion after being told to lazy load modules. i think a problem issue still exists with the standard design, needing to define trees up in top level parents.

How do I add additional tiers of components into this configuration?

consider the following router configuration for a ParentComponent
{
    path: 'child',
    component: ChildComponent,
    children: [
      {path: 'grandchild', component: GrandChildComponent},
    ]
}

## Expected behavior

Would it be better design to define the Grandchild route within the ChildComponent and load the route only when the Child is loaded? This would certainly make 2nd generation component routes more portable with less coupling between 3rd generation routing relationships.

## What is the motivation / use case for changing the behavior?

Use case = pretty much any routing configuration involving 3 generations of components.

## Environment
<pre><code>
Angular version: angular 6+

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by robwormald** [comment]
Maybe i'm misunderstanding the question, but this *is* what lazy loading accomplishes (the point isn't lazy-loading itself, but that a route can either point to a component, *or* a module - in the latter case, that module controls routing for that level of the routing tree):

```ts
//app.module.ts
{ 
  path: 'child',
  loadChildren: './path/to/child.module#ChildModule' `
```
```ts
//child.module.ts
{ 
  path: '',
  component: ChildComponent,
  children: [
    { 
       path: 'grandchild',
       loadChildren: './path/to/grand/grandchild.module#GrandChildModule'
    }
  ] 
}
```
```ts
//grand.child.ts
{ 
  path: '',
  component: GrandChildComponent,
}
```
etc? 

I'm curious if your concern about tight coupling is academic, or if there's a use case you have that this doesn't solve. For highly dynamic stuff, the fact that `loadChildren` uses a string means you can (with a bit of effort) write your own resolver system, that is able to accept an arbitrary string and resolve to whatever, letting you have an extremely dynamic routing system.

**Comment by laurencefass** [comment]
thanks my question was about scalability of the default design and potential code bloat. i suppose the default (non lazy) is simple enough for small component systems, if not scalable, and I assume there must performance reasons for including it. thanks for the feedback.

**Comment by robwormald** [comment]
The early designs of Angular's router actually had configuration done at the Component level, which was extremely tightly coupled - in the end, we decided a *Component* should know almost nothing about it's routing configuration, which makes them far less coupled. *Modules* configure the router, and Components can be composed into any variety of Modules. 

Consider a case where you have a "layout" component that has a Router outlet:

```ts
@Component({
  selector: 'my-layout',
  template: `
    <mat-sidenav>
      <mat-sidebar></mat-sidebar>
     <mat-sidenav-content>
      <router-outlet></router-outlet>
    </mat-sidenav-content>
  </mat-sidenav>`
})
export class MyLayout {}
```
This component does not care where or how its used, what's above it in the routing tree, or what's below it. 

It's then used in a routing tree, which is configured at the NgModule level, meaning its completely decoupled from the Component itself... 

In your first post you say  "consider the following router configuration for a ParentComponent" - it's important to understand you are not configuring the Router for a *component* - you are configuring it for an *NgModule* (or more accurately, an injector)

You could absolutely re-use `ParentComponent` in any other location, and put any other set of routes below or above it, which seems pretty decoupled to me.

Closing this, but happy to discuss further.
