### ISSUE TITLE
 NgFor only supports binding to Iterables such as Arrays.

### ISSUE THREAD

**Issue by bbmattieu9** [angular/angular#24719]
i am trying to create a front end app with Angular6 for a currency converter API.

in my Service file i have:

`getCurrencies()
  {
      return this.http.get('https://free.currencyconverterapi.com/api/v5/currencies')
  }`

And in my converter.component.ts file i did this:

`currencies$: Object;

  constructor(private data: DataService) { }

  ngOnInit() {
    this.data.getCurrencies().subscribe(
      data => this.currencies$ = data
    )
  }`

`<mat-form-field>
          <mat-select placeholder="Currency">
            <mat-option *ngFor="let currency of currencies$" [value]="currency.id">
              {{currency.id}}
            </mat-option>
          </mat-select>
        </mat-form-field>`

Everything seem to compile fine but in my browser console, I get the error 

`ERROR Error: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.`

Please anyone with helpful hint as to what I did wrong and how to fix it so that my drop down can show the list of abbreviations from the endpoint

**Comment by dooks** [comment]
The error is self-explanatory. `*ngFor*` will only work if `currencies$` is an array, not an object. 

(Also more of a stylistic nit, but you should only suffix variables with `$` if it's an `Observable<T>` type, not the result an observable.)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by robwormald** [comment]
This is works as intended. Please take how-to questions to our Gitter Channel - https://gitter.im/angular/angular
