### ISSUE TITLE
Clearing ngModel bound field stops clearing input after first change

### ISSUE THREAD

**Issue by WiseBird** [angular/angular#24711]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have an input with ngModel:
```
<input type="text" name="text"
        [(ngModel)]="text"
        (ngModelChange)="onTextChange()"
/>
```

when value changes I clear it:
```
  onTextChange() {
    if (!this.text) {
        return;
    }

    this.items.push(this.text);
    this.text = '';
  }
```
It clears the input on first change but then stops:
![peek 2018-06-29 12-34](https://user-images.githubusercontent.com/1745378/42085306-bb62d680-7b98-11e8-8a3f-f5e2dba665e2.gif)

## Expected behavior

Input should be cleared after each change event

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-stops-clear-input-after-second-change

## What is the motivation / use case for changing the behavior?

Looks like a bug

## Environment

<pre><code>
Angular version: 6.0.7

Browser:
- [x] Chrome (desktop) version 67.0.3396.62

**Comment by kara** [comment]
@WiseBird This has to do with how change detection works in Angular. When you change the value the second time (let's say you type `'k'`), the previous value of `this.text` was `''` and the new value is `'k'`. But when you overwrite that value to `''` immediately, the framework is checking the previous value `''` against the new value `''` and it sees no change to propagate. So the `ngOnChanges` hook in `ngModel` never fires. In this case, you'll want to force your clearing logic to run next tick (e.g. wrap in `setTimeout`).
