### ISSUE TITLE
RouterOutlet name input missing from documentation

### ISSUE THREAD

**Issue by dooks** [angular/angular#24720]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Documentation for the [RouterOutlet](https://angular.io/api/router/RouterOutlet) directive has no mention of `name` attribute except for the provided example.

Others:

</code></pre>
Documentation in question: https://angular.io/api/router/RouterOutlet

**Comment by m-henderson** [comment]
@brandonroberts can I tackle this one?

**Comment by brandonroberts** [comment]
@m-henderson Sure

**Comment by m-henderson** [comment]
@brandonroberts I cant fix this until I fix this issue https://github.com/angular/angular/issues/30033

**Comment by m-henderson** [comment]
@dooks  were you expecting to see the `name` property under the properties section on that page?

**Comment by m-henderson** [comment]
@brandonroberts do you have an idea of what he is talking about? I think the bug should have contained more details. 😄

**Comment by shonderdos** [comment]
Hey, as it is labeled as 'good first issue' I also took a look at it.

The `router-outlet` directive uses `@Attributes()` to get the name attribute from its host. This is probably why name is not on the properties list.

The use of the name attribute is documented [here](https://angular.io/guide/router#displaying-multiple-routes-in-named-outlets)

**Comment by m-henderson** [comment]
@shonderdos the name is not on the properties list because it is a private property

**Comment by m-henderson** [comment]
@shonderdos lets work together on this one. I looked into this issue and if you make the name property public instead of private in the docs then it does show in the properties list.

**Comment by YuliaTsareva** [comment]
I’ve been looking for some issue with "good first issue" label and I’ve found this one. After a small research, I think this issue probably is not as easy as it might look like.

I discovered that `name` is not under the properties section because it is not an instance member, it is only a constructor param marked with `@Attribute` decorator. So it seems quite logical not to show it under the properties section.

But also there is a private property with the same name. As @m-henderson noticed, if we make it public, then it appears in the properties section. But I suppose it is not a solution, because in fact the parameter `@Attribute('name') name` is something that should be documented.

@kapunahelewong What do you think about the correct way to fix it?

**Comment by m-henderson** [comment]
@YuliaTsareva exactly 😄

**Comment by kapunahelewong** [comment]
Thank you, @YuliaTsareva. This is very helpful. Let me ask around and see if I can find some engineering guidance here.

**Comment by trotyl** [comment]
Relates to https://github.com/angular/angular/issues/12522

**Comment by Splaktar** [comment]
It might be worth submitting a PR that just removes the `private` from the field. Is that sufficient to get it in the docs? 

Or is `public` required? Hopefully not.

**Comment by Splaktar** [comment]
Based on some additional discussion, I believe that the `good first issue` label should be removed from this issue.

After some discussion, we've decided to 
- keep the field `private`
- update the description to clearly call out that this is set via a static `@Attribute` and not a dynamic `@Input()` (as https://github.com/angular/angular/issues/12522 is not supported).

**Comment by jbogarthyde** [comment]
Resolved by https://github.com/angular/angular/pull/32973
