### ISSUE TITLE
feature(router): warn if navigation triggered outside Angular zone

### ISSUE THREAD

**Issue by trotyl** [angular/angular#24728]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When some user performs navigation outside the Angular zone, the change detection will not be invoked. 

Even **it's certainly users' fault**, they may still going to be confused by what the problem is:

+ https://github.com/angular/angular/issues/15770
+ https://github.com/angular/angular/issues/15946
+ https://github.com/angular/angular/issues/18254
+ https://github.com/angular/angular/issues/19731
+ https://github.com/angular/angular/issues/20112
+ https://github.com/angular/angular/issues/22472
+ https://github.com/angular/angular/issues/23697
+ https://github.com/angular/angular/issues/24727
+ ...

## Expected behavior

As the navigation should always happen in Angular zone, so router itself could guard against that thus produce a warning when not valid.

## Minimal reproduction of the problem with instructions

N/A.

## What is the motivation / use case for changing the behavior?

Reduce the invalid issue amounts.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by JiaLiPassion** [comment]
If there is no use case that user want to run `navigation` outside of `ngZone`, I vote for `force inside ngZone` solution.

**Comment by trotyl** [comment]
@JiaLiPassion But for `ErrorHandler`-like usages, it's switched to root zone deliberately to avoid possible infinite loops, once comes implicit switching to Angular zone in navigation, the risk of infinite loops could be back again.

**Comment by jasonaden** [comment]
@trotyl Is this something you want to implement?

Also, we would like to reduce the reliance on Zones to make Zones optional in the future. So whatever the warning is, it needs to be there only when Zones is being used for CD.

**Comment by trotyl** [comment]
@jasonaden Added a PR for warning purpose, should be OK for noop zone environments.

**Comment by george43g** [comment]
Has this been merged in yet? This issue is painful af, especially for newbies!
