### ISSUE TITLE
Bug: Child component receives null in `writeValue` when using a component implementing ControlValueAccessor inside another component implementing ControlValueAccessor

### ISSUE THREAD

**Issue by ayush987goyal** [angular/angular#24725]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Child component receives null in `writeValue` when using a component extending ControlValueAccessor inside another component extending ControlValueAccessor.
This might be related to #14988 

## Expected behavior
The child component should not receive null.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-vpfh8e

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.3  
- Platform:  Windows

Others:

</code></pre>

**Comment by kara** [comment]
Looks related enough to combine with #14988. Thanks for the additional example.
