### ISSUE TITLE
Custom Error Handler : reactive form problem !

### ISSUE THREAD

**Issue by vedrax-admin** [angular/angular#24729]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I've a global error handling. When an Http error occurred in a component (Component A) with **reactive form** (e.g. no such URL resource on the server). The router cannot destroy correctly the component A. When the error handler redirect me to the error page (component B), the component B is displayed along with the component A. **If I throw the same error without a reactive form all work as expected**.

## Expected behavior
When error occurred, the custom error handler should redirect the user to the error page. The component where the error occurred should be destroyed.

## Minimal reproduction of the problem with instructions
https://angular-error-handler.stackblitz.io/

## What is the motivation / use case for changing the behavior?
When an error occurred, I want the user to be redirected to the error page via custom error handler by using simply `router.navigate(['/error'], {queryParams: {msg: error}});`. The router should destroy the component where the error occurred.

## Environment

<pre><code>
Angular version: 6.0.7

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [x] Chrome (iOS) version 67.0.3396.99
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3
- Platform:  Mac

Others:

</code></pre>

**Comment by dawidgarus** [comment]
After You handle error, You throw it again - that's why You get unhandled error.

**Comment by vedrax-admin** [comment]
Yes, you are right. but when I remove in my error handler the `throw error;`  the problem is still the same. The deal for me was to use a global error handler, not using an http interceptor. In my demo the error component is not displaying at all.

**Comment by trotyl** [comment]
@vedrax-admin Without even a `<router-outlet>` in your template, where should it be displayed?

**Comment by vedrax-admin** [comment]
Hi, I've made change to my demo in order to reproduce the problem I have. As you can see when I submit the form with an error the component is not destroyed. The error page is correctly displayed but the previous component is still present. Without having a reactive form, the global error handler works as expected (the component is destroyed). As soon as there is a reactive form in the component something goes wrong.

Tell me if there is a bug or

**Comment by trotyl** [comment]
@vedrax-admin Router navigation should only be triggered inside Angular zone: https://stackblitz.com/edit/angular-error-handler-7kyftn?file=app/core/handlers/errors.handler.ts

**Comment by vedrax-admin** [comment]
Thanks so much. Do you have any other advice for my global error handling implementation.

Thanks

**Comment by trotyl** [comment]
I'd suggest catch the error as early as possible.

**Comment by kara** [comment]
Looks like this is resolved.
