### ISSUE TITLE
Wrong router behavior when injected in custom error handler

### ISSUE THREAD

**Issue by Corsseir** [angular/angular#24727]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Navigate with router in custom global error handler is impossible. I can inject Router service and execute for example navigateByUrl method but component which is loaded with router is not complete. The icons from awesome icons are missing and navbar ngIf statements are not refreshing.

## Expected behavior

Router works as it should.

## Minimal reproduction of the problem with instructions

```
import { ErrorHandler, Injectable, Injector } from '@angular/core';
import { BadTokenError } from '../errors/bad-token.error';
import { Router } from '@angular/router';

@Injectable()
export class CustomErrorHandler extends ErrorHandler {

    constructor(
        private _injector: Injector
    ) {
        super();
    }

    handleError(err: Error) {
        if (err instanceof BadTokenError) {
            const router: Router = this._injector.get(Router);

            window.localStorage.removeItem('vlAuth');
            router.navigateByUrl('/auth/sign-in');
            // window.location.href = '/auth/sign-in';
        }

        console.log(err);
    }

}
```

## What is the motivation / use case for changing the behavior?

Handle 401 status when auth token is obsolet.

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x] Chrome (desktop) version 67
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 60.0.2
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.0  
- Platform:  Linux 

Others:

</code></pre>

**Comment by trotyl** [comment]
Expected behavior, `ErrorHandler` is executed outside the Angular Zone. See https://github.com/angular/angular/issues/7774.

**Comment by Corsseir** [comment]
Ok, so what is the best way to handle this kind of errors? HttpInterceptor?

**Comment by Corsseir** [comment]
Ok, thanks.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
