### ISSUE TITLE
Ng-Reflect attributes not seen in DOM

### ISSUE THREAD

**Issue by laluali** [angular/angular#24730]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ x ] Other... Please describe:
</code></pre>

## Current behavior
"@angular/core": "^5.2.8",
JBOSS-EAP-7.0
We are running local env on CLI(@1.7.3) and PROD env on JBOSS EAP 7.0. It is observed that all ng-reflect attributes are removed from DOM when application is runnig on JBOSS, local running on CLI runs fine.
## Expected behavior
ng-reflect attributes should be as is.

## Minimal reproduction of the problem with instructions
Build any angular application on CLI and deploy it on JBOSS EAP 7.0 with ng-build --prod command

## What is the motivation / use case for changing the behavior?
DOM structure changes which is not the expected behaviour

## Environment
DEV-CLI & NodeJS
Stagging - mvn-clean-install which is configured to run ng build --prod and then deployed in a war on JBOSS 7.0.
<pre><code>
Angular version: 5.2.8

Browser:
- [ x ] Chrome (desktop) version 67.0.3396.99 (Official Build) (32-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ x ] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3
- Platform:  LINUX

Others:

</code></pre>

**Comment by trotyl** [comment]
`ng-reflect-` attributes are all debug helpers to let devtools know what bindings are, which never exist in non-debug (production) mode.

**Comment by laluali** [comment]
Thanks @trotyl for your quick response, but i was unable to find any documentation relating to ng-reflect usage. It would be great if you can share any link.

**Comment by trotyl** [comment]
@laluali I don't think so since it's not even a public feature. But has been asked several times:

+ https://stackoverflow.com/questions/43397839/what-does-the-ng-reflect-attribute-do-in-angular2-4
+ https://stackoverflow.com/questions/40907192/what-are-ng-reflect-attributes-added-by-angular2-to-dom?noredirect=1&lq=1

**Comment by pkozlowski-opensource** [comment]
Thnx for helping out with the issues @trotyl - much appreciated.

**Comment by laluali** [comment]
Thank you for your help @Trotyl it has helped me solve my issue.

**Comment by sallyzhangrong** [comment]
if I know this earlier,I would not make detours, I used so many ng-reflect attribute in our automation scripts to locate the element.so I need overwrite them .
