### ISSUE TITLE
Circular dependency detected:

### ISSUE THREAD

**Issue by maifs** [angular/angular#24736]
## I'm submitting a...
[x ] Bug report 
[ ] Feature request

## Current behavior
ng build

Date: 2018-07-01T17:34:59.296Z
Hash: cec4cd2f4bc6d8d1c5cf
Time: 23786ms
chunk {main} main.js, main.js.map (main) 597 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 275 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 371 kB [rendered]
chunk {styles} styles.js, styles.js.map (styles) 344 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 7.22 MB [initial] [rendered]

WARNING in Circular dependency detected:
src\app\services\auth.service.ts -> src\app\services\endpoint-factory.service.ts -> src\app\services\auth.service.ts

WARNING in Circular dependency detected:
src\app\services\endpoint-factory.service.ts -> src\app\services\auth.service.ts -> src\app\services\endpoint-factory.service.ts

--- console exception

Uncaught Error: Can't resolve all parameters for AppComponent: ([object Object], [object Object], ?, [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object]).
at syntaxError (compiler.js:178)
at CompileMetadataResolver._getDependenciesMetadata (compiler.js:10134)
at CompileMetadataResolver._getTypeMetadata (compiler.js:10030)
at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (compiler.js:9659)
at CompileMetadataResolver._getEntryComponentMetadata (compiler.js:10229)
at entryComponents.push.bootstrapComponents.map.type (compiler.js:9897)
at Array.map ()
at CompileMetadataResolver.getNgModuleMetadata (compiler.js:9897)
at JitCompiler._loadModules (compiler.js:21156)
at JitCompiler._compileModuleAndComponents (compiler.js:21139)

## Expected behavior
I want to see the same functionality like in angular 5. In angular cli 1.7, there was no issue but when i upgraded my source code to angular cli 6 then i am getting the above exception.

## Minimal reproduction of the problem with instructions
Create two services using typescript in angular cli 6.
1). endpoint-factory.service.ts
2). auth.service.ts
Now develop some functions in both files.
Use first file functions in second file and than use second file functions in first file.
You will get the exact exception.

## What is the motivation / use case for changing the behavior?
https://github.com/emonney/QuickApp

I upgraded this repository to angular cli 6.

## Environment
Angular version: 6

Browser:
- [ XX] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ XX] Edge version XX
 
For Tooling issues:
- Node version: v10.4.0
- Platform:  Windows10
- NPM version : 6.1.0

**Comment by jotatoledo** [comment]
Ever heard about the chicken or the egg dilemma?

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by maifs** [comment]
Thank yoy pkozlowski. 

jotatoledo, boy i have read and understood the issue, i think you need ponder on your reply before giving an comment (Your comment is a bit childish).  Didn't you see the clear error mentioning the both typescript files calling each others?

I am wondering two files are dependent on each other and this should not be an issue at this minor level.    Circular dependency is not be in angular 5 but placed this in angular 6. I was asking because i was thinking may be i could have some tweak  for re-writing the logic. i was using a third party framework and that had this issue.

**Comment by maifs** [comment]
Thank yoy pkozlowski. 

jotatoledo, boy i have read and understood the issue, i think you need ponder on your reply before giving an comment (Your comment is a bit childish).  Didn't you see the clear error mentioning the both typescript files calling each others?

I am wondering two files are dependent on each other and this should not be an issue at this minor level.    Circular dependency is not be in angular 5 but placed this in angular 6. I was asking because i was thinking may be i could have some tweak  for re-writing the logic. i was using a third party framework and that had this issue.
