### ISSUE TITLE
Why would you use a resolver with Angular?

### ISSUE THREAD

**Issue by maxime1992** [angular/angular#24735]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I like the idea of `resolver`s.

You can say that:  
- for a given route you expect some data to be loaded first  
- you can just have a really simple component with no observable (as retrieving data from `this.route.snapshot.data`)  

So resolvers makes a lot of sense.

**BUT:**  
 - You're not changing the URL and displaying your requested component until you receive the actual response. So you can't (simply) show the user that something is happening by rendering your component and showing as much as you can (just like it's advised to, for the shell app with PWA). Which means that when having a bad connection, your user may have to just wait without visual indication of what's happening for a long time  
 - If you are using a resolver on a route with param, let's take as example `users/1`, it'll work fine the first time. But if you go to `users/2`, well nothing will happen unless you start using another observable: `this.route.data.subscribe()`

So it feels like resolvers might be helpful retrieving some data BUT in practice I wouldn't use them in case there's a slow network and especially for routes with params.

Am I missing something here? Is there a way to use them with those real constraints?

It would be nice to have more information about that in the doc I think.

I've opened a question on StackOverflow 4 months ago and I haven't had a proper answer ever since:
https://stackoverflow.com/q/49054232/2398593

**Comment by jnizet** [comment]
This is not the right place to post a question, but let me answer anyway:

> So you can't (simply) show the user that something is happening 

yes, you can. Typically by subscribing to router events and showing some spinner or progress when navigation starts, and hiding it when navigation ends. Github does this for example by displaying a thin blue progress bar at the top of the page when navigating. This kind of global behavior is actually simpler to implement when resolve guards are used than when they're not.

> nothing will happen unless you start using another observable

so what? Do just that. It's still way simpler than listening to parameter changes, switchmapping to load the results, not forgetting to handle potential errors, etc. Most components don't link to their own routes, so this is not really an issue most of the time.

Resolvers do make code simpler and cleaner in my opinion, but yes, they have some drawbacks, too (perceived speed being the main one). You're not forced to use them, and they might not be the best choice in some situations, but they're still a useful tool in many, many situations. Especially for behind-the-firewall applications, where the network is supposed to be fast.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
