### ISSUE TITLE
HttpClientTestingBackend is getting strange export name

### ISSUE THREAD

**Issue by hhorton2** [angular/angular#24746]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Importing the HttpClientTestingBackend can only be done by importing "ɵangular_packages_common_http_testing_testing_a" as HttpClientTestingBackend.
![image](https://user-images.githubusercontent.com/9061986/42234590-a7f506d4-7eba-11e8-81d0-a9b874f0a841.png)

This is a screenshot of the testing/testing.d.ts file showing where it is being exported.
![image](https://user-images.githubusercontent.com/9061986/42234657-dac8d630-7eba-11e8-88bd-ceb8517f46d2.png)

## Expected behavior

Not have HttpClientTestingBackend be exported with a weird alias.

## Minimal reproduction of the problem with instructions

Just navigate to "@angular\common\http\testing\testing.d.ts" inside the distro bundle and see the wrong export.

## Environment

<pre><code>
Angular version: 6.0.7

Browser:
- [ X] Chrome (desktop) version XX
- [ X] Chrome (Android) version XX
- [ X] Chrome (iOS) version XX
- [ X] Firefox version XX
- [ X] Safari (desktop) version XX
- [ X] Safari (iOS) version XX
- [ X] IE version XX
- [ X] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1
- Platform: Windows

Others:

</code></pre>

**Comment by sarunint** [comment]
If you are importing `HttpClientTestingBackend`, you are likely doing something wrong. On 'HttpClientTestingModule', `HttpClientTestingBackend` is provided as `HttpBackend`.

https://github.com/angular/angular/blob/09222280249c6d76658c911740d8397a01029dba/packages/common/http/testing/src/module.ts#L23-L34

**Comment by hhorton2** [comment]
In my unit test I am configuring the testing module like this:
![image](https://user-images.githubusercontent.com/9061986/42236020-3213dbd4-7ebf-11e8-99a4-dadcf6b8e97e.png)

And then injecting it into my tests like this:
![image](https://user-images.githubusercontent.com/9061986/42236052-52111b04-7ebf-11e8-8977-ce9851ad5e74.png)

Is there a better way to do this?

**Comment by sarunint** [comment]
```
TestBed.configureTestingModule({
  imports: [
    HttpTestingModule
  ]
})
```
and inject it like this:
```
it('should work', inject([HttpBackend], (backend: HttpBackend) => { ... });
```

**Comment by hhorton2** [comment]
right, but that doesn't expose the verify or expect methods. Which is why I need access to the HttpClientTestingBackend, so that I can assert my service is making the correct calls.

**Comment by sarunint** [comment]
Then do this:
```
it('should work', inject([HttpBackend, HttpTestingController], (backend: HttpBackend, controller: HttpTestingController) => {
  controller.extectOne(...);
  controller.verify(...);
});

**Comment by hhorton2** [comment]
That's not going to be feasible. I'm not looking for workarounds, as I can already keep my tests passing with the aliasing I mentioned in the bug report. I am extending the httpclient to handle some auth stuff automatically, and part of construction for the httpclient is to provide a backend. This makes injecting a controller into my tests a heavy lift which would include a lot of fundamental refactoring of how I have built my auth client. The HttpClientTestingBackend is the easiest solution to my problem, I just wanted to make the team aware of their strange alias.

**Comment by sarunint** [comment]
No, that is the expected way to do that.

As seen in this code:
https://github.com/angular/angular/blob/09222280249c6d76658c911740d8397a01029dba/packages/common/http/testing/src/module.ts#L23-L34

`HttpClientTestingBackend` is provided as both `HttpBackend` and `HttpTestingController` token. The `expect...` and `verify` methods are parts of `HttpTestingController` class so injecting `HttpTestingController` class is the correct way to call them.

**Comment by sarunint** [comment]
Moreover, `HttpClientTestingBackend` is not in Angular's public API. It wouldn't be covered in deprecation policy and can break at anytime.

**Comment by hhorton2** [comment]
I see that you are right now. so how would I extend the HttpClient? It needs a HttpHandler in the constructor bu the controller does not implement that. So I can provide the injected backend, but I can not assert on those requests because it is just an HttpBackend, not a controller.

**Comment by sarunint** [comment]
If you are doing the auth stuff, I recommend using [`HttpInterceptor`](https://angular.io/api/common/http/HttpInterceptor) instead of extending `HttpClient`.

https://angular.io/guide/http#intercepting-requests-and-responses

*Disclaimer: I've not used the interceptor myself, but I think it's the way to do it!*

**Comment by kara** [comment]
This export name is deliberate because it's not part of the public API.
