### ISSUE TITLE
HttpClient DELETE request is making OPTIONS request

### ISSUE THREAD

**Issue by jlafuenteribera** [angular/angular#24742]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Im trying to make DELETE requests with @Angular/common/http/HttpClient but angular in creating OPTIONS requests

## Expected behavior
Its expected to make DELETE Requests.

## Environment
Angular version: 6.0.5

![1](https://user-images.githubusercontent.com/23057516/42220097-51e727c2-7ece-11e8-8021-ad2c9693787c.png)
![2](https://user-images.githubusercontent.com/23057516/42220098-52036bf8-7ece-11e8-89f2-eeb1b7afce86.png)

**Comment by pkozlowski-opensource** [comment]
This has nothing to do with Angular, it is browser's CORS in action. More info at https://www.html5rocks.com/en/tutorials/cors/
