### ISSUE TITLE
what is event name for check box by using click?

### ISSUE THREAD

**Issue by sokhomhuy** [angular/angular#24740]
i have know in angular we can use (change) & (ngModelChange) for event checkbox but in this problem i don't know how to use without these 2 event i just want by onclick so that is trigger. sometime i just from controller component set true false to my ngModel check all but it is trigger my event in that (change) or (ngModelChange). 

please Help.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
