### ISSUE TITLE
Set blank value to the field when it is touched or dirty

### ISSUE THREAD

**Issue by RakheeMenon** [angular/angular#24741]
I want to set blank value to one of the float field and send the blank value as null to the backend

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
