### ISSUE TITLE
Angular 6 error when creating new app.

### ISSUE THREAD

**Issue by thirtyfoursoft** [angular/angular#24758]
I have installed the node and angular but when I try to create new app, it shows me the below errors.
please help.
<pre><code>
D:\app-new>ng new app-test
CREATE app-test/angular.json (3557 bytes)
CREATE app-test/package.json (1311 bytes)
CREATE app-test/README.md (1024 bytes)
CREATE app-test/tsconfig.json (384 bytes)
CREATE app-test/tslint.json (2805 bytes)
CREATE app-test/.editorconfig (245 bytes)
CREATE app-test/.gitignore (503 bytes)
CREATE app-test/src/environments/environment.prod.ts (51 bytes)
CREATE app-test/src/environments/environment.ts (631 bytes)
CREATE app-test/src/favicon.ico (5430 bytes)
CREATE app-test/src/index.html (294 bytes)
CREATE app-test/src/main.ts (370 bytes)
CREATE app-test/src/polyfills.ts (3194 bytes)
CREATE app-test/src/test.ts (642 bytes)
CREATE app-test/src/assets/.gitkeep (0 bytes)
CREATE app-test/src/styles.css (80 bytes)
CREATE app-test/src/browserslist (375 bytes)
CREATE app-test/src/karma.conf.js (964 bytes)
CREATE app-test/src/tsconfig.app.json (194 bytes)
CREATE app-test/src/tsconfig.spec.json (282 bytes)
CREATE app-test/src/tslint.json (314 bytes)
CREATE app-test/src/app/app.module.ts (314 bytes)
CREATE app-test/src/app/app.component.html (1141 bytes)
CREATE app-test/src/app/app.component.spec.ts (990 bytes)
CREATE app-test/src/app/app.component.ts (207 bytes)
CREATE app-test/src/app/app.component.css (0 bytes)
CREATE app-test/e2e/protractor.conf.js (752 bytes)
CREATE app-test/e2e/src/app.e2e-spec.ts (303 bytes)
CREATE app-test/e2e/src/app.po.ts (208 bytes)
CREATE app-test/e2e/tsconfig.e2e.json (213 bytes)
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'find-npm-prefix'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\love34\AppData\Roaming\npm\node_modules\npm\
lib\config\load-prefix.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
Package install failed, see above.
</code></pre>

Package                      Version
------------------------------------------------------
Angular CLI: 6.0.8
Node: 10.5.0
OS: win32 x64
Angular:
...

@angular-devkit/architect    0.6.8
@angular-devkit/core         0.6.8
@angular-devkit/schematics   0.6.8
@schematics/angular          0.6.8
@schematics/update           0.6.8
rxjs                         6.2.1
typescript                   2.7.2

**Comment by jotatoledo** [comment]
This is related to the angular-cli project, please open an issue in that repository.

**Comment by thirtyfoursoft** [comment]
Wrong thread adding the same issue on Angular CLI : https://github.com/angular/angular-cli/issues/11455
