### ISSUE TITLE
ngModel for custom checkbox doesn't work correctly and returns true as string and doesn't update the  status 

### ISSUE THREAD

**Issue by bobKasbi** [angular/angular#24757]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I customize a checkbox and use it a separated component (child component) and add into parent component, the `ngModel`, for two way binding and passing the $event isn't working expected. It passes a string `"true"` instead of a boolean `true`. And also when I uncheck the checkbox, the status doesn't change to `false`. neither as `string` or `boolean`. It keeps displaying `"true"`. 

## Expected behavior

The checked/unchecked `checkbox` should pass the correct $event/status to the model.
so, checked --> true. unchecked --> false. and the `ngModel` should be updated with boolean based on the status.

## Minimal reproduction of the problem with instructions
The description of the issue and code are in [SO](https://stackoverflow.com/questions/51161220/custom-checkbox-why-ngmodule-cant-get-update-the-boolean-checkbox-status)

## What is the motivation / use case for changing the behavior?

I would like to add differen Checkboxex to parent app and change names, label text, values, error message etc. based on the requirements.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [x ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
Angular CLI: 1.7.4
Node: 8.11.1
OS: darwin x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.5
@angular/cli: 1.7.4
@angular/material: 5.2.5
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.4.2
webpack: 3.11.0

Others:

Visual studio code
OS: darwin x64

**Comment by robwormald** [comment]
`NgModel` (and all the form APIs) use a set of underlying APIs including `ControlValueAccessor` - this is the API you'd want to implement if you want an Angular Component to act like a vanilla `<input>` element inside an Angular form.

The API is here https://angular.io/api/forms/ControlValueAccessor, and here's a couple of great blog posts that dive a bit deeper: 

https://blog.angularindepth.com/never-again-be-confused-when-implementing-controlvalueaccessor-in-angular-forms-93b9eee9ee83

https://blog.thoughtram.io/angular/2016/07/27/custom-form-controls-in-angular-2.html

**Comment by bobKasbi** [comment]
Understand. But why should it be sooo complicated to custom form fields. Would it not be more productive not to be forced to rewrite nearly the whole app concept just to move to reactive forms?

And also with each upgrade it's almost a huge time investment to make everything works again as expected. So, what has been implemented should be rewritten again.

**Comment by mlc-mlapis** [comment]
@bobKasbi ... ??? ... `ControlValueAccessor` API is here from the beginning of version 2 so what you need to rewrite again?
