### ISSUE TITLE
Programatically change focus using Renderer2 disables ngFor

### ISSUE THREAD

**Issue by sreerajkarippala** [angular/angular#24760]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

i am trying to programatically focus a select html element which options are reported by a ngFor. unfortunately ngFor not working when element is focused using code
<code>
this.render.selectRootElement('#select').focus();
</code>

## Minimal reproduction of the problem with instructions

just goto https://codesandbox.io/s/5m3mzvq0qk, you can see the select without any option. 

comment code <i>this.render.selectRootElement('#select').focus(); </i> in src/app/app.component.ts then the select will ngFor options.
## What is the motivation / use case for changing the behavior?

Autofocus or set focus of html elements by programatically.

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.0.0  
- Platform:  Mac 

Others:

</code></pre>

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/19554, expected behavior.

**Comment by sreerajkarippala** [comment]
thank you for your response.
