### ISSUE TITLE
Create multiple components using Command Line.

### ISSUE THREAD

**Issue by MrPardeep** [angular/angular#24761]
PS: May be a feature request -

Is the any command to generate multiple angular components using angular-cli command like 
`ng g c comp1, comp2, comp3.`

**Comment by Airblader** [comment]
This can be done trivially in any shell. There's no need for Angular to support this.

**Comment by MrPardeep** [comment]
Can you show the example command about which you are talking about?

**Comment by Airblader** [comment]
That depends on your environment. In a bash shell, for example, you can do

    for i in comp1 comp2; do ng g c "${i}"; done

**Comment by Airblader** [comment]
Also this issue should be closed for completely ignoring the issue template...

**Comment by trotyl** [comment]
Also wrong repo. https://github.com/angular/angular-cli

**Comment by MrPardeep** [comment]
@Airblader  Thank you so much :)
@trotyl Yup , my bad :(

**Comment by pkozlowski-opensource** [comment]
This belongs to https://github.com/angular/angular-cli
