### ISSUE TITLE
Naming of modules after migration to v6

### ISSUE THREAD

**Issue by arangates** [angular/angular#24765]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The name of the modules is longer and has duplicates .... For eg: if there is a module named `manage-users` ...the cli says its `manage-users-manage-users-module` 
```
chunk {manage-users-manage-users-module} manage-users-manage-users-module.js, manage-users-manage-users-module.js.map (manage-users-manage-users-module) 97.9 kB  [rendered]
```

## Expected behavior

Name must not contain duplicates
```
chunk {manage-users-module} manage-users-module.js, manage-users-module.js.map (manage-users-module) 97.9 kB  [rendered]
```

<pre><code>
Angular version: 6.0.0

**Comment by intellix** [comment]
wrong repository :) https://github.com/angular/angular-cli

**Comment by kara** [comment]
Yep, please file in the CLI repo
