### ISSUE TITLE
Allow tests of HTTP services to explicitly ignore query parameters in request matching

### ISSUE THREAD

**Issue by textbook** [angular/angular#24763]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Per #19974 there is an issue with the matching of URL in the current testing controller. It matches against `HttpRequest.urlWithParams`, not just `HttpRequest.url`, which means you have to either build the right URL again in your tests or work around it, e.g. using the request matching function or just matching the method. This also causes surprise because what is logged out by `HttpClientTestingBackend.verify` explicitly strips out any query parameters (see also #22112).

## Expected behavior

Given that changing the default behaviour would potentially break many existing test suites and there's no obvious way to configure the testing controller as a whole, I propose adding a new property to `RequestMatch`: `ignoreParams` (or `excludeParams`, perhaps). This would default to `false`-y if not set explicitly, retaining the current behaviour, but if explicitly set to `true` would switch the behaviour of `HttpClientTestingBackend._match` from using `urlWithParams` to `url`.

**Note** that this would still cause issues where the query parameters are hardcoded into the URL parameter, rather than passed in the `HttpParams` object. This may only be solvable if `HttpRequest.url` was changed to explicitly strip out any hardcoded params into the `HttpParams` object, which seems like a substantial change and a lot of extra complexity.

## Minimal reproduction of the problem with instructions

N/A

## What is the motivation / use case for changing the behavior?

To quote [my comment](https://github.com/angular/angular/issues/19974#issuecomment-342827258) on the other issue:

> I'd rather write:
> 
> ```
> const req = httpMock.expectOne({ method: 'GET', url: 'http://example.org' });
> expect(req.request.params.get('foo')).toEqual('bar');
> ```
> 
> than:
> 
> ```
> httpMock.expectOne({ method: 'GET', url: 'http://example.org?foo=bar' });
> ```
> 
> not least because it avoids any ordering issues when you have more than one parameter.

There is an open pull request, #20916, that proposes a different fix for the same problem, but per my comment there that implementation has the potential to break some existing test suites.

## Environment

<pre><code>
Angular version: 6.0.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by csnate** [comment]
Why not use the [matchFn overload of expectOne](https://angular.io/api/common/http/testing/HttpTestingController#expectone)?

```
const req = httpMock.expectOne(r => r.url === 'http://example.org');
expect(req.request.method).toEqual('GET');
expect(req.request.params.get('foo')).toEqual('bar');
```
