### ISSUE TITLE
Error: Angular Compiler requires TypeScript >=2.7.2 and <2.8.0 but 2.9.2 was found instead.

### ISSUE THREAD

**Issue by DmitriyIvanko** [angular/angular#24764]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[+] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Expected behavior
Please support the latest version of typescript.

**Comment by sarunint** [comment]
Resolved by https://github.com/angular/angular/commit/e3064d5432d5332f54592f405e7e589a3feea18d, to be released with v6.1.
