### ISSUE TITLE
Documentation lacks info about EventEmitter 

### ISSUE THREAD

**Issue by andremarcondesteixeira** [angular/angular#24774]
Angular version: 6.0.7

There is an undocumented convention in the framework.

When you name an EventEmitter instance with a "Change" suffix, the framework will look for an input property without the "Change" suffix, like so:

``` Typescript
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
    selector: 'app-error-modal',
    templateUrl: './error-modal.component.html',
    styleUrls: ['./error-modal.component.css']
})
export class ErrorModalComponent {
    @Input() isVisible = false;
    @Output() isVisibleChange = new EventEmitter<boolean>();
    @Input() message: string;

    closeDialog() {
        this.isVisible = false;
        this.isVisibleChange.emit(this.isVisible);
    }
}
```

In the example, the `isVisibleChange` together with the 'isVisible' properties will allow the use of the "banana in a box" syntax in the view:

``` html
<app-error-modal [(isVisible)]="isDialogVisible"></app-error-modal>
```

But if I rename the `isVisibleChange` property to anything else, I will be forced to do a separate input and output binding in my html:

``` html
<app-error-modal [isVisible]="isDialogVisible" (another-name)="my-method($event)"></app-error-modal>
```

This is true even if I rename the output property using;

``` typescript
@Output('isVisible') another-name = new EventEmitter<boolean>();
```

**Comment by trotyl** [comment]
> The `[(x)]` syntax is easy to demonstrate when the element has a settable property called `x` and a corresponding event named `xChange`.

https://angular.io/guide/template-syntax#two-way-binding---

It has nothing to do with `EventEmitter`, just normal event binding, even DOM event named `xChange` would also work.

**Comment by andremarcondesteixeira** [comment]
wow. Thanks for the response @trotyl
I was looking that in the api documentation. I didn't know it was in the tutorial

**Comment by andremarcondesteixeira** [comment]
Is this an Angular specific pattern?

**Comment by trotyl** [comment]
Definitely, all built-in DOM events are lowercase (but still case-sensitive), there's no camelCase convention in event names (but still valid). Also the idea of two-way binding is framework-specific, not language-provided.

**Comment by andremarcondesteixeira** [comment]
What is the Angular service/component/module responsible for this behavior?

**Comment by trotyl** [comment]
@andremarcondesteixeira No, it's just first-class pre-compilation (macro-like syntax sugar) step in template compiler.

**Comment by jenniferfell** [comment]
@andremarcondesteixeira : Thanks for sharing this tip and highlighting that it wasn't where you expected.

@trotyl : Thanks for the clear and helpful explanations.

Question: Do you have a recommended action for us on the docs team? Some options seem to be:

1. Do nothing. This syntax is documented in Template Binding guide. 

2. Add a note in the TOH Tutorial about this syntax option, so others learn about it sooner:
https://angular.io/tutorial/toh-pt1#two-way-binding

The specific code example here doesn't seem to lend itself easily to mapping to using *Change. 

3. Add a see also link in the EventEmitter API reference page: https://angular.io/api/core/EventEmitter

The code example here doesn't have @input, but this it might be something we can add to the final set of links.

?

**Comment by andremarcondesteixeira** [comment]
@jenniferfell the example you posted does not illustrate the situation I have exposed.
The place I believe this behavior should be documented for quick reference is in the quick reference API documentation, not the in the heavy reading tutorial

**Comment by andremarcondesteixeira** [comment]
I personally think that you guys could do a lot of improvements in the quick referecence api documentation

**Comment by andremarcondesteixeira** [comment]
one SHOULD NOT treat a tutorial as official documentation

**Comment by andremarcondesteixeira** [comment]
Maybe you have not considered that many people will not have an intro to Angular through your tutorials, but through online courses, articles, youtube, etc

**Comment by andremarcondesteixeira** [comment]
So, improving the current tutorial will have little effect in terms of having a better documentation, because a tutorial is not a documentation

**Comment by andremarcondesteixeira** [comment]
You could always put the docs in an open source repo as well

**Comment by jenniferfell** [comment]
@trotyl is correct. He kindly tried to explain that the syntax that confuses you is not part of EventEmitter or any other specific API. It is part of the html template syntax.

The documentation that you needed is here in the official Angular guides: 

https://angular.io/guide/template-syntax#two-way-binding---

As @trotyl wrote: It has nothing to do with EventEmitter, just normal event binding, even DOM event named xChange would also work.

**Comment by andremarcondesteixeira** [comment]
@jenniferfell Yeah, but this compilation is an Angular specific behavior. It does not occur outside of Angular applications, so you could not expect that a developer reading the quick reference would magically know about it. I learned Angular through online courses, so I didn't spend time re-reading yet another tutorial.

**Comment by jenniferfell** [comment]
I think we have some terminology differences, so please offer me a moment to explain. 

Angular provides more than one kind of information in their official documentation at https://angular.io/docs. 

It includes the API reference (such as https://angular.io/api/core/EventEmitter) which explains the public Angular API. It explains each aspect of the API as individual pieces. This documentation is extracted from specially-marked comments in the API source files, which are stored in the angular/angular repo. Both source and the embedded comments are open source. 

The official documentation also includes a tutorial and guides, which explain how to put the pieces together to create Angular applications. Understanding template syntax is essential, but it is not handled by the Angular APIs, so the description is in the guides not the API reference. The tutorials and guides are also open source, in the same angular/angular repo as markdown files. 

Yes, I am aware that this documentation set is part of a larger learning ecosystem, and I encourage everyone to find the best learning method for you. If you prefer in-person or online classes, many are available. The Angular documentation set is here as self-help for those who want to try starting on their own or as a resource during and after training. 

If you want to learn on your own, I recommend the Angular tutorial in our doc set here: https://angular.io/tutorial

All of that said, what I am hearing is that you would like the reference for template syntax to be easier to find in the navigation and search. The document exists (https://angular.io/guide/template-syntax), but you weren't able to easily find it. I appreciate that, and we are working on navigation changes to the entire docs site. 

Thanks for your feedback and follow-on comments.

**Comment by jenniferfell** [comment]
Our comments posted at the same time. I see that you've taken training, so I agree that doing the tutorial is unnecessary.

Also, regarding my options from yesterday, I agree that 2 and 3 don't show exactly what you wanted. I was just offering some options of locations that discuss similar topics to see if maybe we should put a link from those locations to the template syntax doc that you couldn't find.

**Comment by jenniferfell** [comment]
It's Angular-specific, so it is documented in the official Angular doc set. It's not part of the Angular API. It's part of the template syntax defined by Angular. Angular components and the templates work together (+ css) to create the user's experience.

**Comment by jenniferfell** [comment]
I'm sorry you had trouble finding it.

**Comment by jenniferfell** [comment]
Idea: I think it would help to put a note here about *Change and link to the two-way binding document : 
https://angular.io/guide/cheatsheet

**Comment by andremarcondesteixeira** [comment]
Yes. Putting a note about it in the two way binding guide would be great :D

Em sex, 13 de jul de 2018 16:09, Jennifer Fell <notifications@github.com>
escreveu:

**Comment by jenniferfell** [comment]
possible places to update:
filename: https://angular.io/guide/cheatsheet
filename: https://angular.io/api/core/EventEmitter
filename: https://angular.io/guide/template-syntax#two-way-binding---

**Comment by atscott** [comment]
Closing - two way binding is mentioned in the cheat sheet as well as what the long-hand equivalent. The two way binding guide explains this concept in more depth.
