### ISSUE TITLE
Angular4 - How to load list of components in given order

### ISSUE THREAD

**Issue by Panthaka** [angular/angular#24776]
I m bit new to angular(angular4) and I need to clarify how to load list of components in given order in home page.This list can be vari.
I m developing a user design dashboard and in there, user able to drag and drop component according the requirement and then view dashboard that designed order .
Expecting your help to resolve this..

**Comment by mlc-mlapis** [comment]
@Panthaka ... it's not really an issue for this channel. Don't use it for that. Use Gitter or SO instead, ...

... btw, you can see it as a case where the components are async things and you can use RxJS to coordinate them ... on the base of your rules.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
