### ISSUE TITLE
Work with AngularJS and Angular at same time is possible?

### ISSUE THREAD

**Issue by YilverMolina** [angular/angular#24772]
Good day, recently I am working in a project with `Angular 1.5.9`, and now I want to add modules with `Angular 6.0.8.` I have been searching about it, but is complicated for the big differences. My question is, exists some way to use AngularJS and Angular modules in the same project? How do would work with `node_modules` for different versions?

Thank you so much for the support.

**Comment by ericmartinezr** [comment]
https://angular.io/guide/upgrade

**Comment by YilverMolina** [comment]
Thanks @ericmartinezr
