### ISSUE TITLE
Feature request - Add name to router

### ISSUE THREAD

**Issue by guyaloni** [angular/angular#24775]
## Current behavior
When using router, one needs to explicitly write the url which is specified in `Routes` array in order to navigate to this url:

Routing module:
<pre>
const routes: Routes = [
  {path: 'item/:id', component: ItemPageComponent},
</pre>

Module using the router:
<pre>
this.router.navigate(['item', itemId]);
</pre>

## Motivation
In some situations there might be a need to change the url.  
In this case, you need to review the entire project, modifying all places this url is used.

## Suggested solution
In many other frameworks ([ruby-on-rails](http://guides.rubyonrails.org/routing.html#naming-routes), [Laravel](https://laravel.com/docs/5.6/routing#named-routes), etc.) you can add a *name* to the route.

Then, instead of using the explicit url, you simply use the route name with its parameters.
If you need to change the url, you need to modify *only* the routing file.

### For example:
Declaring route:
<pre>
const routes: Routes = [
  {path: 'item/:id', component: ItemPageComponent, name: 'itemPage'},
</pre>

Using it:
<pre>
this.router.navigateByName('itemPage', [itemId]);
</pre>

**Comment by Nexeuz** [comment]
for now I use a service save router names in a service, with statics methods 

```

public static get INICIO_ROUTING(): any {
    return {
      inicio: {
        path: 'inicio',
        data: {
          title: 'Inicio'
        },
        childs: {
          cuenca: {
            path: 'cuenca',
            data: {
              title: 'Que me cuencas'
            },
            childs: {
              path: 'caracterizacion-del-sitio',
              data: {
                title: 'Caracterización del área',
                lazy: true
              }
            }
          }
        }
      }
    };
  }

```

and use in router like this: 

```
const routes: Routes = [
  { path: RoutingConstansService.INICIO_ROUTING.inicio.path,
    canActivate: [TokenGuard],
    component: ChangePasswordByEmailComponent },
];
```

**Comment by jasonaden** [comment]
Thanks for the request.

**Comment by alxhub** [comment]
This isn't feasible within the design of Angular's current routing system and the way our lazy loading works.
