### ISSUE TITLE
[ngModel$]

### ISSUE THREAD

**Issue by BagumEpmak** [angular/angular#24778]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Template driven forms are easy to implement but difficult to use with rxjs.
You can use rxjs library if you create component property as BehavoirObject. 
Then you can use this property in template using ngModel and ngModelChange and you also can use rxjs library functions in component code

<pre><code>
import { Component } from '@angular/core';
import { BehaviorSubject, Observable, combineLatest } from 'rxjs';
import { map } from 'rxjs/operators';
@Component({
  selector: 'my-app',
  template: `
    Name
    &lt;input [ngModel]="name$.value" (ngModelChange)="name$.next($event)">
    Surname
    &lt;input [ngModel]="surname$.value" (ngModelChange)="surname$.next($event)">
    Hello {{ nameAndSurname$|async }}!!!
    Your name is {{ name$|async }} and surname is {{ surname$.value }}
  `
})
export class AppComponent {
  name$ = new BehaviorSubject('John');
  surname$ = new BehaviorSubject('Doe');

  nameAndSurname$ = combineLatest(this.name$, this.surname$)
    .pipe(map(([name, surname]) => name + ' ' + surname))
}
</code></pre>
## Expected behavior
New directive [ngModel$]. Value for this directive must be BehaviorSubject. This directive must reuse [ngModel] and (ngModelChange) functionality.

Using new directive you could write
<pre><code>&lt;input [ngModel$]="name$"></code></pre>
instead of
<pre><code>&lt;input [ngModel]="name$.value" (ngModelChange)="name$.next($event)"></code></pre>

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gitter-hrdmuc

## What is the motivation / use case for changing the behavior?
This directive will greatly simplify usage of rxjs functions in template driven forms

**Comment by dawidgarus** [comment]
You can extend `BehaviorSubject`:
```typescript
class NgModelSubject<T> extends BehaviorSubject<T> {
	set value(value: T) {
		this.next(value);
	}
}
```
and use it like this:
```html
<input [(ngModel)]="name$.value">
```

**Comment by BagumEpmak** [comment]
@jotatoledo ,
it is reactive approach with less boilerplate. FormBuilder and &LT;form> are not required.

@dawidgarus ,
that is great idea!
One correction: you forgot to reimplement getter.
Final solution for me is:
<pre><code>import { BehaviorSubject } from 'rxjs';

export class NgModelSubject<T> extends BehaviorSubject<T> {
  constructor(_value?: T) {
    super(_value);
  }

  get value() {
    return this.getValue();
  }

  set value(value: T) {
    this.next(value);
  }
}
</code></pre>

I think it is good to have such class in Angular library out of the box
