### ISSUE TITLE
could we change convert.ts to convert.dart ?

### ISSUE THREAD

**Issue by vicb** [angular/angular#2477]
It seems like convert.ts is used from Dart only to (un)serialize DirectiveMetadata annotation.

Moving it from .ts to .dart would allow using enum for the `type` (JS and Dart do handle differently).

@kegluneq what do you think ?

**Comment by kegluneq** [comment]
It's my understanding that we'll need to serialize `DirectiveMetadata` from Js when we have application / render separation, but I'm not certain that's the case. If you think it's worth making the change to simplify things I have no problem with it.

**Comment by mhevery** [comment]
@vsavkin and @tbosch can you comment?

If we have plans to use it in JS, than it should probably stay as `.ts`

**Comment by mhevery** [comment]
Let's just do it.

**Comment by vicb** [comment]
The idea when we do this is to convert type to an enum

**Comment by tbosch** [comment]
Could we wait a little bit more until we our intern that works on WebWorkers is a little farther? So we know what we actually need there?

**Comment by vicb** [comment]
Closing, will open a new more generic issue
