### ISSUE TITLE
Feature Request: addGroup and removeGroup methods to FormGroup

### ISSUE THREAD

**Issue by novaterata** [angular/angular#24786]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Imagine an arbitrary tree structure where each node is an optional component with a FormGroup
Imagine each node can be enabled/disabled or add/delete in the case of arrays with relative buttons.
Some of the nodes are arrays, some are not.

Apparently the only way to achieve this now if by wrapping every node into a FormArray even if there is a single component allowed.
Then I will need to use an adapter to replace singletons with single properties.

## Expected behavior
If I have a FormGroup that has an optional child FormGroup, I should be able to call addGroup / removeGroup just like I can call addControl / removeControl so that I don't have to wrap everything in a FormArray

## What is the motivation / use case for changing the behavior?
This form is used to render JSON based on the present components

## Environment

<pre><code>
Angular version: 6

**Comment by Toxicable** [comment]
FormGroup already has `AddControl` and `RemoveControl` https://angular.io/api/forms/FormGroup#addcontrol
Which you can use to add and remove FormGroups

**Comment by novaterata** [comment]
Oh good! I had been told on an SO question that it wasn't possible except using FormArray and I couldn't find an example that didn't use it with plain controls. I noticed that FormGroup extends AbstractControl. I thought controls had to be simpler things.
