### ISSUE TITLE
StyleUrlResolver: Does not support 'package:'-style Dart URIs

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2478]
E.g.

```html
<style>@import "package:material_dialog/material_dialog.scss.css";</style>
```

**Comment by vicb** [comment]
This issue comes from the `UrlResolver` which does not support `package:`

**Comment by matanlurey** [comment]
Our UrlResolver is hotfixed to support it, but I think the RegEx check on StyleUrlResolver fails

**Comment by vicb** [comment]
> Our UrlResolver is hotfixed to support it, but I think the RegEx check on StyleUrlResolver fails

Are you sure of that, it should not

**Comment by mhevery** [comment]
dup of  #2502
