### ISSUE TITLE
Add `router.buildRouteUrl()` helper method, for opening new browser windows to a given route

### ISSUE THREAD

**Issue by brian428** [angular/angular#24782]
## I'm submitting a...
<pre><code>
[X] Feature request
</code></pre>

## Current behavior
Given a route like:
`{ path: 'game/:width/:height', component: GameComponent }`

There is no way (that I can find) to convert that route into a URL that could be used to open a new browser window.

## Expected behavior
`Router` (or some other class) could expose a method that translates a given route into a full, valid URL. 

Something like:
`let url = this.router.buildRouteUrl( [ 'game', { queryParams: { width: width, height: height } } ] );`

## What is the motivation / use case for changing the behavior?
We have a data visualization app that uses multiple browser tabs to let users view different sets of charts at once. We use websockets to communicate across tabs.

Currently, building a URL to use to launch the new windows is more difficult and error-prone than it should be. `Location.prepareExternalUrl()` gets us part of the way there, but has no support for building up the URL to enforce the required params, order, etc. One just has to "know" what params are required, what order they need to be in, and the proper Matrix URL syntax to employ for the given params.

I assume this would be fairly easy to add? Add if there's already a way to do this that I'm just not aware of, feel free to let me know.

## Environment
<pre><code>
Angular version: 6.0.7
</code></pre>

**Comment by dominikg** [comment]
what about `location.prepareExternalUrl(router.serializeUrl(router.createUrlTree([...])))`

**Comment by jasonaden** [comment]
Closing this based on the suggestion from @dominikg.
