### ISSUE TITLE
error while compling 

### ISSUE THREAD

**Issue by jaswanth1998** [angular/angular#24796]
`ERROR in src/app/first-look/home/home.component.ts(14,26): error TS1149: File name '/Users/apple/Downloads/FML_firebase_work-master/node_modules/rxjs/observable.d.ts' differs from already included file name '/Users/apple/Downloads/FML_firebase_work-master/node_modules/rxjs/Observable.d.ts' only in casing.
`

in friends laptop it is working fine but on my laptop it showing error

**Comment by ponkys** [comment]
check:
https://github.com/Microsoft/TypeScript/issues/5371

https://www.google.de/search?q=file+name+differs+from+already+included+file+name+only+in+casing&rlz=1C5CHFA_enDE775DE775&oq=File+name+differs+from+already+included+file+name&aqs=chrome.1.69i57j0.3265j0j7&sourceid=chrome&ie=UTF-8

**Comment by robwormald** [comment]
You're probably importing from `rxjs/Observable`, which isnt' a thing post v6. Use `import {Observable} from 'rxjs'`
