### ISSUE TITLE
minifed code requires null check; @angular-devkit/build-angular requires process

### ISSUE THREAD

**Issue by SamuelMarks** [angular/angular#24795]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
My project compiles without error, using `ng build --prod`. However nothing loads. Checking the console, I get:
```
Uncaught ReferenceError: process is not defined
```
tracing the minified code down, I came to this section:

```
    OekB: function(t, e, n) {
        "use strict";
        t.exports = "win32" === process.platform || !!process.env.COLORTERM || /^screen|^xterm|^vt100|color|ansi|cygwin|linux/i.test(process.env.TERM)
    },
```

Tracing that down in my directory tree, and I found:
```
node_modules/@angular-devkit/build-optimizer/src/.cache/47e1a4b7ca8adc1aecb35ea3b98de6ab.json:{"remainingRequest":"node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js??ref--8-1!node_modules/gauge/has-color.js","dependencies":[{"path":"node_modules/gauge/has-color.js","mtime":1466042398000},{"path":"node_modules/cache-loader/dist/cjs.js","mtime":1531103950607},{"path":"node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js","mtime":1528256844000}],"contextDependencies":[],"result":["'use strict'\n\nmodule.exports = isWin32() || isColorTerm()\n\nfunction isWin32 () {\n  return process.platform === 'win32'\n}\n\nfunction isColorTerm () {\n  var termHasColor = /^screen|^xterm|^vt100|color|ansi|cygwin|linux/i\n  return !!process.env.COLORTERM || termHasColor.test(process.env.TERM)\n}\n",null]}
```
Tracing `gauge` to my `package-lock.json`, and only version 2.7.4 is used, running `grep` on that package shows that `has-color.js` is the culprit. Note that `gauge` is a dependency of `npmlog`, only 4.1.2 of `npmlog` is a dependency; and `node-pre-gyp`, `node-gyp`, `node-sass`, `npm-registry-client` and packages depend on `npmlog`. Some of these are dependencies of `@angular-devkit/build-angular`, so it's clearly an issue.

Anyway, polyfilling `process`, or adding this to my `package.json`:
```
"browser": {
    "fs": false,
    "path": false,
    "os": false
  },
```

Gives this error:
```
Uncaught TypeError: e is not a constructor
````

The prettified code is:
```
function Ao(t, e) {
            var n;
            switch (201347067 & e.flags) {
            case 512:
                n = function(t, e, n) {
                    var i = n.length;
                    switch (i) {
                    case 0:
                        return new e;
```

Printing `e` to console, and I get:
```
main.685197d80b1a59a47a62.js:1 e: ƒ t(){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ t(){this.contexts=new Map} ;
main.685197d80b1a59a47a62.js:1 e: ƒ t(){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ (){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ t(){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ (){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ (){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ (){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ t(){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ t(){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ (){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ (){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ (){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ t(){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ t(){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ t(){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ (){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ t(){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ (){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ t(){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ t(){} ;
main.685197d80b1a59a47a62.js:1 e: ƒ t(){} ;
main.685197d80b1a59a47a62.js:1 e: undefined ;
main.685197d80b1a59a47a62.js:1 Uncaught TypeError: e is not a constructor
    at main.685197d80b1a59a47a62.js:1
    at Ao (main.685197d80b1a59a47a62.js:1)
    at main.685197d80b1a59a47a62.js:1
    at new t (main.685197d80b1a59a47a62.js:1)
    at Object.Qo [as createNgModuleRef] (main.685197d80b1a59a47a62.js:1)
    at e.create (main.685197d80b1a59a47a62.js:1)
    at main.685197d80b1a59a47a62.js:1
    at e.invoke (polyfills.6a51f2ae3d3c5687da3a.js:1)
    at Object.onInvoke (main.685197d80b1a59a47a62.js:1)
    at e.invoke (polyfills.6a51f2ae3d3c5687da3a.js:1)
(anonymous) @ main.685197d80b1a59a47a62.js:1
Ao @ main.685197d80b1a59a47a62.js:1
(anonymous) @ main.685197d80b1a59a47a62.js:1
t @ main.685197d80b1a59a47a62.js:1
Qo @ main.685197d80b1a59a47a62.js:1
e.create @ main.685197d80b1a59a47a62.js:1
(anonymous) @ main.685197d80b1a59a47a62.js:1
e.invoke @ polyfills.6a51f2ae3d3c5687da3a.js:1
onInvoke @ main.685197d80b1a59a47a62.js:1
e.invoke @ polyfills.6a51f2ae3d3c5687da3a.js:1
t.run @ polyfills.6a51f2ae3d3c5687da3a.js:1
t.run @ main.685197d80b1a59a47a62.js:1
t.bootstrapModuleFactory @ main.685197d80b1a59a47a62.js:1
zUnb @ main.685197d80b1a59a47a62.js:1
i @ runtime.4510d1eaa4782899e567.js:1
6 @ main.685197d80b1a59a47a62.js:1
i @ runtime.4510d1eaa4782899e567.js:1
t @ runtime.4510d1eaa4782899e567.js:1
r @ runtime.4510d1eaa4782899e567.js:1
(anonymous) @ main.685197d80b1a59a47a62.js:1
```

It compiles and runs when I change the line to:
```
case 0:
    return e == null? e : new e;
```

However, clicking a few things in my application, and I get this error:
```
ERROR TypeError: i is not a constructor
```

Which resolves to a different `return new i;`; which could probably be resolved with the same mechanism of null checking, but really I shouldn't have to patch the minified output.

## Expected behavior
It should compile and serve without error.

## Minimal reproduction of the problem with instructions
```
git clone https://github.com/glaucoma-australia/glaucoma-risk-calculator-web-frontend
cd glaucoma-risk-calculator-web-frontend
npm i -g @angular/cli typescript tslint typings
typings i
npm i
ng build --prod
cd dist/glaucoma-risk-calculator-web-frontend
caddy # <or any other http server>
# view in browser
```

## Environment

<pre><code>
Angular version: 6.0.7

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3
- Platform:  Mac

Others:

</code></pre>

**Comment by robwormald** [comment]
As far as I'm aware, there's nothing in Angular framework code that uses or depends on the `process` module, anywhere (this would be a Bad Idea, as its a node-only API....). Build Optimizer may use it, but that's a purely build-time process and doesn't insert `process` into your code.

It's more likely that this is a third party dependency that uses process (or incorrectly includes it in a runtime bundle)

We'd need a reproduction of this to investigate further.

**Comment by gkalpak** [comment]
AFAICT, `lru-cache` is supposed to be used in Node.js; it is not browser-compatible.

**Comment by vajahath** [comment]
@gkalpac I think that needs a correction.
This module just stores values in memory.
I don't see any node specific things in this module. Please see [this](https://github.com/isaacs/node-lru-cache/issues/106#issuecomment-306611583) comment.

**Comment by gkalpak** [comment]
`process.env` (which is transitively required via `pseudomap`) is node specific afaict.

Of course you can polyfill node specific things and use node-'oriented modules in the browser. And in case of `lru-cache` it is pretty trivial if `process.env` is the only node specific API used.

But then it's expected that you have to provide `process` yourself and that failing to do so will result in an error (which has nothing to do with Angular).

**Comment by vajahath** [comment]
Well, that makes sense 🎈

**Comment by SamuelMarks** [comment]
Got it working, Previously, I was uploading my `repo-name/dist` in my `org/repo-name` repository. Library was called `lib0`.

In `org/repo-name2` angular project, I included in my `package.json`: `{"repo-name": "org/repo-name"}`. Compiled fine on `ng build`; `ng build --prod` proved the problem.

Pushing the `dist` directory to its own repository `org/lib0`; removing the previous from my `package.json`; then adding: `{"lib0": "org/lib0"}`; proved to be the solution.

Now `ng build --prod` works; and the rendered static files give no unexpected errors.
