### ISSUE TITLE
Issues with ServiceWorker in Angular 6

### ISSUE THREAD

**Issue by hassanasad** [angular/angular#24790]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When new build is pushed to S3 (along with service worker files [ngsw-worker.js and ngsw.json]) we run cache invalidation from CloudFront. The browser using ServiceWorker even picks up the new change and downloads the files. However it doesn't trigger the `swUpdate.available()` method and it downloads the same files on every request that goes out to check `ngsw.json` file even though there is no new change in them. We are checking for new version every 30 seconds.
![screenshot 2018-07-07 13 50 50](https://user-images.githubusercontent.com/7580112/42409001-0a87b4ec-81ed-11e8-8de0-89cd8265ac8a.png)

## Expected behavior

The ServiceWorker should just fetch the file once and trigger `swUpdate.available()` method. If there is some issue - it should throw an exception or console message if there is some error.

## Minimal reproduction of the problem with instructions

Service Worker setup code in `app.component.ts`:
```
	private setupServiceWorker(): void {
		if ( this.swUpdate.isEnabled && environment.allowServiceWorker ) {
			// Service worker is enabled
			// Check for update
			this.appUpdateIntervalSub = interval( 1000 * 60 * 0.5 ).subscribe( () => {
				this.swUpdate.checkForUpdate();
			} );

			// New app version is available
			this.appUpdateAvailableSub = this.swUpdate.available.subscribe( () => {
				console.log('SW Available');
				// New version of app is available - notify user to refresh browser
				this.showAppUpdateMessage = true;
			});
		}
	}
```

**P.S:** It works okay on local webserver:
```
ng build --configuration=alpha && cd dist && http-server -p 8080
```
alpha config in **angular.json**:
```
            "alpha": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": true,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false,
              "serviceWorker": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.alpha.ts"
                }
              ]
            },
```

## Environment

<pre><code>
```
Angular CLI: 6.0.8
Node: 10.1.0
OS: darwin x64
Angular: 6.0.7
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3
```

Browser:
Chrome 67.0.3396.99
 
For Tooling issues:
- Node version: v10.1.0
- Platform:  Mac OS High Sierra 10.13.5

Others:

</code></pre>

**Comment by hassanasad** [comment]
There isn't much regarding repro steps in terms of code i am assuming. Regarding access to it i can give it to you in a PM if you like. Its behind a VPN.

**Comment by hassanasad** [comment]
@gkalpak Also i believe the `comp` should be "Service Worker" and NOT "language service" no?

**Comment by hassanasad** [comment]
I will close this issue as we have found one of our build processes to be the culprit. 

We use Octopus to write some version values in our main.*.js bundle and thats breaking the file integrity.

**Comment by gkalpak** [comment]
I am happy to investigate if I can get my hands on a reproduction. 
BTW, can you navigate to `/ngsw/state` and post the output here?

**Comment by hassanasad** [comment]
Sorry i dont understand `/ngsw/state` thingy you mentioned. I tried it in
navigation and i get 404 because its not part of my routes.

**Comment by gkalpak** [comment]
Nevermind. I write that before I saw you found the culprit.

(In case you're curious, `/ngsw/state` is a route that the SW serves (even if it is not is your routes) and shows info about the SW's current state, which is useful for debugging. If you are getting 404, then the SW is probably not activated.)

**Comment by hassanasad** [comment]
Oh yeah it works now without last slash (/ngsw/state).

I am facing another issue if you can give me some direction how to resolve
it. We are injecting APP_VERSION after build for debugging purposes. This
however breaks the SW detection. Is there any way round this?

I am assuming its because it considers hash difference between ngsw.json
file and the one its calculating.

**Comment by gkalpak** [comment]
I think you are right. I don't think there is a (straight forward) way around this atm, but it is a valid usecase.
Can you open an issue on the [cli repo](https://github.com/angular/angular-cli/issues) (and tag me)?

**Comment by gkalpak** [comment]
As a workaround, you can re-generate `ngsw.json` after you have changed the content files with `./node_modules/.bin/ngsw-config dist/<app-name> ngsw-config.json`.
