### ISSUE TITLE
QueryList empty when ng-template is defined outside host

### ISSUE THREAD

**Issue by dirkluijk** [angular/angular#24806]
## I'm submitting a...

<pre><code>[X] Bug report</code></pre>

## Current behavior
Given an Angular template:
```html
<ng-template let-item #tpl>
  <li appChild>{{ item }}</li>
</ng-template>

<ul appParent>
  <ng-container *ngFor="let item of list; template: tpl"></ng-container>
</ul>
```
where:
```typescript
@Directive({
  selector: '[appChild]'
})
export class ChildDirective {}

@Directive({
  selector: '[appParent]'
})
export class ParentDirective {
  @ContentChildren(ChildDirective) childDirectives;

  ngAfterContentInit(): void {
    console.log(`Got ${this.childDirectives.length} child directives`);
  }
}
```
The QueryList with child directives is not populated.

However, when the `ng-template` is moved next to the `ng-container`, it is populated:
```html
<ul appParent>
  <ng-template let-item #tpl>
    <li appChild>{{ item }}</li>
  </ng-template>
  <ng-container *ngFor="let item of list; template: tpl"></ng-container>
</ul>
```

## Expected behavior
I expect all embedded views to match the query based on the location of the _view container_, not the location of its _template_.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-addawb

## What is the motivation / use case for changing the behavior?
I want to render two lists using the same `ng-template`, but still profit from `@ContentChildren`, `@ViewChildren`, etc.

## Environment

<pre><code>Angular version: 6.0.0</code></pre>

**Comment by mhevery** [comment]
This is working as expected/by design. queries are executed in the location of declaration not location of insertion.
