### ISSUE TITLE
 TypeError: Object(...) is not a function (Upgrading to Angular 6)

### ISSUE THREAD

**Issue by kaushik1094** [angular/angular#24804]
Angular upgarde 6: I am upgrading to angular 6 and Getting the following error: 
![angular6error]
![angular6error](https://user-images.githubusercontent.com/23369030/42465165-050ad1e2-8360-11e8-996a-2bbe1519aad2.PNG)
Error is thrown at main.browser.ts , 

It's working fine for previous versions.
depen
 "@angular/animations": "^6.0.5",
    "@angular/cdk": "^6.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^6.0.2",
    "@angular/forms": "^6.0.6",
    "@angular/http": "^6.0.6",
    "@angular/material": "^6.2.0",
    "@angular/platform-browser": "^6.0.7",
    "@angular/platform-browser-dynamic": "^6.0.7",
    "@angular/platform-server": "^6.0.7",
    "@angular/router": "^6.0.7",
    "@angularclass/conventions-loader": "^1.0.2",
    "@angularclass/hmr": "~1.2.2",
    "@angularclass/hmr-loader": "~3.0.2",
    "@ngx-translate/core": "^9.1.1",
    "@turf/bbox": "5.1.5",
    "@turf/distance": "5.1.5",
    "@turf/helpers": "5.1.5",
    "@turf/nearest-point": "5.1.5",
    "@types/elasticsearch": "^5.0.19",
    "@types/geojson": "1.0.1",
    "@types/mapbox-gl": "^0.40.1",
    "adal-angular-resources": "^1.0.17-resource-v3",
    "adal-angular4-resources-fork": "^1.1.11-resource-v3",
    "angular-font-awesome": "3.1.2",
    "angular-webpack-config": "^6.0.1",
    "copyfiles": "^2.0.0",
    "core-js": "^2.5.7",
    "elastic-builder": "^1.1.4",
    "elasticsearch": "^13.3.1",
    "file-saver": "^1.3.8",
    "flexboxgrid": "^6.3.1",
    "font-awesome": "^4.7.0",
    "get-json": "^1.0.0",
    "hammerjs": "^2.0.8",
    "http-server": "^0.9.0",
    "ie-shim": "^0.1.0",
    "jasmine-core": "^2.5.2",
    "latlon-geohash": "^1.1.0",
    "mapbox-gl": "^0.41.0",
    "moment": "^2.22.2",
    "ng2-datepicker": "2.2.5",
    "openlayers": "3.20.0",
    "pixi.js": "^4.6.2",
    "reflect-metadata": "^0.1.9",
    "rxjs": "^5.5.2",
    "rxjs-compat": "^6.0.0-rc.0",
    "turf": "^3.0.14",
    "wellknown": "^0.5.0",
    "zone.js": "^0.8.4"
},
I am unable to extract or debug much from it.  is anyone having the same issue. ?

It's working forprevious versions.

**Comment by robwormald** [comment]
This is likely an issue with one of your dependencies, which you should generally update alongside updating the framework. For example: https://github.com/ngx-translate/core/issues/824

We'd need a reproduction to be able to investigate this, but i suspect its a dependency.

Closing, but feel free to request a re-open if it ends up not being one of your deps.

**Comment by kaushik1094** [comment]
Solved this Issue, I needed a dependency Domino 2.0.0 for @angular/platform-server. Issue has been resolved. 

Thank you :)
