### ISSUE TITLE
@Inject does not have second argument for default value and/or null for optional

### ISSUE THREAD

**Issue by Znert** [angular/angular#24801]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Using @Inject only allows the token, but not the default value as described in the tutorial:

https://angular.io/guide/dependency-injection#optional-dependencies

## Expected behavior
@Inject should allow a default value as fall-back.

## Minimal reproduction of the problem with instructions
Try to use @Inject as described in the tutorial, e.g.:

```
export class HeroListComponent {
 
  constructor(@Inject(HeroService, null) heroService: HeroService) {
  }

}
```

## What is the motivation / use case for changing the behavior?
Sometimes you need to provide a default behaviour, but want it be overridden via the dependency injector.

## Environment

<pre><code>
Angular version: 6.0.7
 
For Tooling issues:
- Node version: v8.11.2
- Platform:  Linux
</code></pre>

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/23849

**Comment by Znert** [comment]
Sorry for the duplicate, I did not find it myself. Thanks for your quick answer :slightly_smiling_face:

**Comment by trotyl** [comment]
Sometimes it's hard to find the proper keywords, it's not a big problem. 😃 
<sub>Actually I found it via list of my commented issues (as knowing it is), it's sort of cheating.</sub>
