### ISSUE TITLE
[Elements] ng-add schematic only adds polyfill to first project in angular.json

### ISSUE THREAD

**Issue by garydex** [angular/angular#24813]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using `ng add @angular/elements --project=<project-name>` the document-register-element polyfill script is added to the first project in angular.json regardless of the name passed in the project flag.

## Expected behavior

In a workspace with multiple projects, you should be able to specify the project name and the polyfill should be added to the scripts array of the given project. The schematic already supports the project flag, but it seems to ignore it.

## Minimal reproduction of the problem with instructions

1. Create a new CLI project `ng new foo`
2. Generate a new app `ng generate application bar`
3. Add @angular/elements to the new app `ng add @angular/elements --project=bar`
  - document-register-element.js is added to the architect.build.options.scripts array for the 'foo' project
  - Each subsequent call to `ng add @angular/elements` will add the script to the first project's scripts array again

## What is the motivation / use case for changing the behavior?

- Calling `ng add @angular/elements` with a `--project` flag should honour the given value
- Polyfills script should only be added to the script array once per app

## Environment

<pre><code>
Angular CLI version: 6.0.8
Angular Elements version: 6.0.5 (but the schematic code hasn't changed since)

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.10.0  
- Platform:  Mac 

Others:

</code></pre>

**Comment by santoshyadav198613** [comment]
Hi Team,

Any update on the issue, on any workaround, I need to add everything manually in case I have multiple apps.

**Comment by gkalpak** [comment]
I tried with CLI v9.1.7 and `@angular/elements` v9.1.9 and it seems to work as expected. The `angular.json` is no longer updated by `ng add @angular/elements --project=...`, but the `document-register-element` polyfill is added to the `polyfills.ts` file of the target project.
