### ISSUE TITLE
Auxiliary routes with Clean URL

### ISSUE THREAD

**Issue by vnykSJ** [angular/angular#24819]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
While using aux routing url will be something like http://localhost:4200/nlp/home/(secondaryOutlet:applications)

which is kind of ugly.

## Expected behavior
is it possible for cleaning it to something like http://localhost:4200/nlp/home/applications

## Minimal reproduction of the problem with instructions
We have raised Question on this in [stackOverflow](https://stackoverflow.com/q/50834187/7739150) But still no luck

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3
- Platform:  Windows

Others:
Need help

**Comment by jasonaden** [comment]
Thanks for the issue. If you would like to adjust the parsing and serializing, you can do so by overriding the [`UrlSerializer`](https://angular.io/api/router/UrlSerializer) for your application.
