### ISSUE TITLE
compiler.js :22402 Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by lincolnthree** [angular/angular#24823]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Getting an error when running webpack-dev-server:

```
compiler.js:22402 Uncaught TypeError: Cannot read property 'apply' of undefined
    at evalExpression (VM52234 compiler.js:22631)
    at jitStatements (VM52234 compiler.js:22642)
    at JitCompiler._interpretOrJit (VM52234 compiler.js:22957)
    at JitCompiler._compileTemplate (VM52234 compiler.js:22927)
    at eval (VM52234 compiler.js:22868)
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (VM52234 compiler.js:22868)
    at eval (VM52234 compiler.js:22778)
    at Object.then (VM52234 compiler.js:435)
    at JitCompiler._compileModuleAndComponents (VM52234 compiler.js:22777)
    at JitCompiler.compileModuleAsync (VM52234 compiler.js:22737)
    at CompilerImpl.compileModuleAsync (VM52233 platform-browser-dynamic.js:158)
    at PlatformRef.bootstrapModule (VM52030 core.js:4557)
    at main (main.ts:9)
    at eval (main.ts:22)
    at Object../src/main.ts (main.bundle.js:12706)
    at __webpack_require__ (main.bundle.js:21)
    at Object.5 (main.bundle.js:12718)
    at __webpack_require__ (main.bundle.js:21)
    at main.bundle.js:85
    at main.bundle.js:88
```
Seems to be failing because "Function.bind" is undefined in compiler.js, when paused in the debugger.

```
    if (createSourceMap) {
        // using `new Function(...)` generates a header, 1 line of no arguments, 2 lines otherwise
        // E.g. ```
        // function anonymous(a,b,c
        // /**/) { ... }```
        // We don't want to hard code this fact, so we auto detect it via an empty function first.
        var emptyFn = new (Function.bind.apply(Function, Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__spread"])([void 0], fnArgNames.concat('return null;'))))().toString();
        var headerLines = emptyFn.slice(0, emptyFn.indexOf('return null;')).split('\n').length - 1;
        fnBody += "\n" + ctx.toSourceMapGenerator(sourceUrl, headerLines).toJsComment();
    }
```

## Expected behavior

To not get the error and run in dev mode successfully.

## Minimal reproduction of the problem with instructions
I wish I could make it minimal, but here it is. Please forgive/Ignore the mess of scripts in package.json and run "npm install && npm run start:dev", then open a browser to http://localhost:8088 to see the error in action. Trying to delete things and get to a cause, but not having much luck.

https://github.com/snowdrop/snowdrop-site-angular/tree/angular-6

## What is the motivation / use case for changing the behavior?

It needs to work :)

## Environment

<pre><code>
Angular version: 6.0.6 / 6.0.7

Browser:
- [x ] Chrome (desktop) version Version 66.0.3359.139 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11  
- Platform:  Linux, Fedora

Others:

</code></pre>

**Comment by lincolnthree** [comment]
@trotyl @splincode Out of curiosity, what could I have done differently/better? Did I miss something obvious? Thanks :) I'm not super experienced with Angular/Node/Webpack yet at this point.

**Comment by splincode** [comment]
1. Invented an unsuccessful task name
2. This problem is solely related to webpack

**Comment by lincolnthree** [comment]
@splincode Hmm... Could you explain what you mean by "unsuccessful task name"?

I'm not sure how this is solely related to webpack. The issue is occurring at runtime, and the error occurs in Angular. I have some updates as well. See below...

**Comment by trotyl** [comment]
For any bug report please make a minimal reproduction **without any 3rd-party library** usage, otherwise it's only a support question and should not be made on the issue channel.

**Comment by lincolnthree** [comment]
Update. The issue appears to be sporadic / race condition. Sometimes I'll get a successful compile/build, but other times I'll get this error. I have been systematically deleting code from our app, and it appears that this occurs when one of the dependencies "asciidoctor.js" is loaded into the browser before Angular finishes its module/component compilation. 

So, this is most likely a conflict with Opal.js (which asciidoctor embeds). After removing this library, everything is working fine. This issue can be closed. Thank you.

**Comment by lincolnthree** [comment]
@trotyl Understood. Thanks.
