### ISSUE TITLE
Extending Query to Support Querying By #name

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#2482]
Currently, we can only query by a directive type, which is not flexible enough. We need to extend the query mechanism to support querying by #.
 
## Querying directive children

```
@View({
  directives: [Header, Footer],
  template: `
    <header #header></header>
    <footer #footer></footer>  
  `
})
class HeaderFooter {
  constructor(Query("#header") header, Query("#header") footer, Query("#header,#footer") headerAndFooter) {}
  
  // all the queries should return directives: Header and Footer.
}
```

## Querying DOM

```
@View({
  template: `
    <input #first>
    <input #last>
  `
})
class HeaderFooter {
  constructor(Query("#first") first, Query("#last") last, Query("#first,#last") firstAndLast) {}
  // all the queries should return dom elements  
}
```

The result of the query depends on what the provided name is bound in the view to.

`Query("#some-ref")` should return a DOM element when some-ref points to a DOM element.
`Query("#some-ref")` should return a directive when some-ref points to a directive.

The mental model is: whatever I can access in the view I can also be access via Query.

/cc @rkirov @mhevery

**Comment by matanlurey** [comment]
:+1:

**Comment by mhevery** [comment]
:+1:

**Comment by naomiblack** [comment]
@vsavkin this seems like something we should address in alpha-28. assigning to you, please reassign (or unassign) if you're the wrong owner.

**Comment by vsavkin** [comment]
Talked to Rado. I will be working on it.

**Comment by vsavkin** [comment]
Merged via https://github.com/angular/angular/commit/b0e2ebda708cf25287a211a30ef63d84cdb92a7f

**Comment by aboeglin** [comment]
I have a little issue on this feature. 

Say my template is made like this : <my-directive #directive></my-directive>

If I use the form @ViewQuery("#directive") I get no reference at all. If I use @ViewQuery("directive"), and I log the result in the console I get an empty _results array, but if I expend it to see the content, I see this : 
![viewquery](https://cloud.githubusercontent.com/assets/8297302/9167879/1b27fa32-3f56-11e5-9942-f64f54e41cc4.jpg)
But I am still not able to access it. Is this feature tested and supposed to work ? I also tried on previous alpha versions and none seems to make it work ( alpha 30 -> 34 ).

**Comment by cristinecula** [comment]
@aboeglin have a look at #2916
