### ISSUE TITLE
why is X-XSRF-TOKEN added to header of request if I can just read XSRF-TOKEN from cookie

### ISSUE THREAD

**Issue by wobeng** [angular/angular#24821]
From my understanding angular looks for  XSRF-TOKEN on the current domain, 

If that  XSRF-TOKEN cookie is found, it reads the value and adds it to the request as the X-XSRF-TOKEN header.

Why is adding X-XSRF-TOKEN to header needed? why can't I just read XSRF-TOKEN from cookie when the subsequent requests are made

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
