### ISSUE TITLE
Currency pipe for DKK is not correct

### ISSUE THREAD

**Issue by ngThrall** [angular/angular#24839]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currency pipe for DKK currently is 'kr' (use parameter symbol-narrow)

## Expected behavior

It should be 'kr.'

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-khus7e

## Environment
<pre><code>
Angular version: 5

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x ] IE version XX
- [x] Edge version XX
 
</code></pre>

**Comment by vicb** [comment]
We use the code from the CLDR data:

```
          "DKK": {
            "displayName": "Danish Krone",
            "displayName-count-one": "Danish krone",
            "displayName-count-other": "Danish kroner",
            "symbol": "DKK",
            "symbol-alt-narrow": "kr"
          },
```

If there is an issue it should be reported to  the CLDR.

We might provide a patch if you send a link to a spec showing how the currency should be displayed in the meantime and a bug report to the CLDR.

Please also the locale in which this is applicable ?

A workaround could be: `{{ 10.23 | currency: 'DKK':'kr.':'1.0-2'}}`

**Comment by ngThrall** [comment]
thanks for responding, I wrote a custom pipe to resolve it.
