### ISSUE TITLE
Want to start early with Angular 2

### ISSUE THREAD

**Issue by vaibhav-kaushal** [angular/angular#2483]
Hello folks, 

This is **not an issue**. But just wanted to say that I'm developing an app in angular and recently saw a slide about upcoming Angular 2 which got me excited. I want to start off with Angular 2 early on. How do I start with it? 

Any pointers would be helpful (if they did not come from XKCD :smile_cat: ).

**Comment by matanlurey** [comment]
https://angular.io/docs/js/latest/quickstart.html ?

**Comment by gdi2290** [comment]
https://github.com/angular-class/angular2-webpack-starter

**Comment by vaibhav-kaushal** [comment]
Thanks to both of you for replying. Will go through them.
