### ISSUE TITLE
Silent error when inheriting from service class without providing subclass

### ISSUE THREAD

**Issue by inspirassion** [angular/angular#24834]
When service` ChildService` inherit from `ParentService` and change attribute or methode implementation without providing `ChildService` the substitution is ignored and the implementation executed is the implementation of the parent class. This is a silent error that must throw an exception.

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
