### ISSUE TITLE
@angular/core.Component: documentaion: inputs -> @Input()

### ISSUE THREAD

**Issue by lebnic** [angular/angular#24843]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

[Documentation](https://angular.io/api/core/Component#setting-component-inputs) for `@Component` uses the `inputs` property:
```
@Component({
  selector: 'app-bank-account',
  inputs: ['bankName', 'id: account-id'],
  template: `
    Bank Name: {{ bankName }}
    Account Id: {{ id }}
  `
})
```

## Expected behavior

Use `@Input()` in documentation, as it is stated in Angular's official [style guide](https://angular.io/guide/styleguide#style-05-12):

> Do use the `@Input()` [class decorator] instead of the inputs [property of the] `@Component` metadata

## What is the motivation / use case for changing the behavior?

Improve documentations's consistency

**Comment by robwormald** [comment]
The linked documentation is specific to the `@Component()` *decorator* - which is why it's using the `inputs:[]` property of said decorator. In general, the documentation uses the `@Input()` decorator when discussing Components in general, eg https://angular.io/guide/component-interaction
