### ISSUE TITLE
Internationalization (i18n) DOCS (& bugs)?

### ISSUE THREAD

**Issue by mrfx** [angular/angular#24849]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Internationalization (i18n)  docs are unclear and have to be read from the end.
ng serve --configuration not working

## Expected behavior

Examples in docs should work.
ng serve --configuration should work.

## Minimal reproduction of the problem with instructions

I followed docs and on the top there is <code>ng serve --configuration=fr</code> but CLI will show error, because yet there is no such configuration. So let's skip that and go on. After replace <code> providers: [ ], </code> with <code> providers: [ { provide: LOCALE_ID, useValue: 'fr' } ], </code> in the app.module.ts web browser console will show error "[object Object]" and the app will not work. Confusing... but let's try more... maybe there is needed "translation source file'? Since we've got errors at start, it is unclear if we need to create xlf file to use @angular/common/locales/... only? So, let's create that file with <code>ng xi18n</code>. Oh, still this: <code> providers: [ { provide: LOCALE_ID, useValue: 'fr' } ], </code> cause an error. Tired already? No! Let's read all the docs first. So at the end there is heading: "Merge the completed translation file into the app" and there is "configurations". I think it must have something in common with <code>ng serve --configuration=fr</code> at "Setting up the locale of your app" heading on the top of the document. Let's add it and try again <code>ng serve --configuration=fr</code>. Ooops, I've got that: 

` 'fr' could not be found in project 'website'.
Error: Configuration 'fr' could not be found in project 'website'.
    at Architect.getBuilderConfiguration (path\website\node_modules\@angular-devkit\architect\src\architect
.js:106:23)
    at MergeMapSubscriber._loadWorkspaceAndArchitect.pipe.operators_1.concatMap [as project] (path\website\
node_modules\@angular\cli\models\architect-command.js:64:55) [...]`

Too bad. :( Let's remove i18n lines from configuration and try again. The same error. :(  Let's check <code>ng build --configuration=fr'</code>. It works. When used with xlf file in my configuration it shows some errors due to 3rd party modules (missing translations in xlf file, but it works. So it is possible to ng build different configurations but cannot ng serve them .

## What is the motivation / use case for changing the behavior?

I need to use internalization but now it not works for me.

## Environment

<pre><code>
Angular version: X.Y.Z

Angular CLI: 6.0.8
Node: 9.5.0
OS: win32 x64
Angular: 6.0.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3

Browser:
For Tooling issues:
- Node version: 9.5.0
- Platform:  Windows

Others:

</code></pre>

**Comment by mrfx** [comment]
Thanks to @tatsujb  #24474 my locale works now. There was needed:

<code>"pl": {
              "browserTarget": "website:build:pl"
            }</code>

at serve section of angular.json and even <code>providers: [ { provide: LOCALE_ID, useValue: 'fr' } ]</code> in app.module.ts not causing error, but my locale works with 3rd party modules like ng-bootstrap when providers are empty too. Why?

**Comment by tmtron** [comment]
I agree that a good example application in the docs is really required. The current info in the docs (and everywhere on the Internet) seems outdate and is very confusing.

The [example code](https://angular.io/generated/zips/i18n/i18n.zip) is way too basic and should be hosted on GitHub.

[Angular docs - i18n pipes](https://angular.io/guide/i18n#i18n-pipes)
> The CLI imports the locale data for you when you use the parameter --configuration with ng serve and ng build.

What exactly does this mean? Does it refer to the `i18nLocale` parameter of the [build](https://angular.io/cli/build) command?
If so does this mean that we need not call `registerLocaleData()` at all when we use `i18nLocale`? 
And  will it then also handle the `extra Dataset` that his mentioned [here](https://angular.io/guide/i18n#i18n-pipes)?


[Merge with the JIT-compiler](https://angular.io/guide/i18n#merge-with-the-jit-compiler)
> `@NgModule({ { provide: LOCALE_ID, useValue: 'de' } })`

How does this relate to the aot build?
i.e. I guess that when we aot-compile, the "i18nLocale" parameter will be used to set the LOCALE_ID.
Will this override the `@NgModule` setting of the LOCALE_ID, or must we take care to provide the LOCALE_ID only when the JIT compiler is used? If so, how do we know that?

What about loading the messages file?
```const translations = require(`raw-loader!./locale/messages.fr.xlf`);```
This is done unconditionally - but for the AOT build this is not needed, right? So how can we avoid this?

**Comment by gdm85** [comment]
> I guess that when we aot-compile, the "i18nLocale" parameter will be used to set the LOCALE_ID.
> Will this override the `@NgModule` setting of the LOCALE_ID, or must we take care to provide the LOCALE_ID only when the JIT compiler is used? If so, how do we know that?

I confirm this behaviour. When serving with AOT enabled the `LOCALE_ID` will be correctly populated with the `i18nLocale` parameter (either from CLI or from configuration), while serving without AOT will completely ignore that parameter.

I think this is not correct behaviour for **any** CLI: if a parameter is ignored it should be an error because otherwise user's request is being (silently) ignored.

**Comment by rockument69** [comment]
PR [24849](https://github.com/angular/angular/issues/24849) should fix this issue.

**Comment by rockument69** [comment]
PR [36924](https://github.com/angular/angular/pull/36924) (docs: Refactor-i18n-DOCS-758) closes this issue.
