### ISSUE TITLE
Dart: Using '$' as an identifier in a string literal is not ideal

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2484]
In Dart, $ is used for String templating.

So when using the `$event` in the host is done as such:

```dart
hostListeners: const {
  'mouseenter': 'onMouseEnter($event)'
}
``` 

It requires the $ to be escaped. Can there be an alternative identifier for Dart?

**Comment by vicb** [comment]
`r'onMouseEnter($event)'` ? (still needs one more char)

**Comment by matanlurey** [comment]
Yeah, but to put that in every component? Meh.

**Comment by mhevery** [comment]
Currently the `$` is reserved for all identifiers which are special in the sense that they are not declared in the template. 

Since the only identifiers we are discussing are: `event`, and possibly `self`, and `this` I could be convinced to just make those reserved. 

Thoughts: @vsavkin, @tbosch

**Comment by vicb** [comment]
Don't we also have target ?

-1 for removing the prefix, IMO it would make things confusing.

**Comment by vicb** [comment]
Maybe `ng-event`, `ng-target`, 'this, `self` ?

**Comment by jelbourn** [comment]
Agreed that removing the prefix entirely would be confusing and that `ng` would be an adequate replacement (though not as nice as `$` in JS).

**Comment by mhevery** [comment]
:-1: for `ng` as a prefix. `ng` prefix is currently reserved for bundled directives, but the core is prefixless. it is `<div bind-title>` not `<div ng-bind-title>`.

Sounds like we should just keep it the way it easy. (I am going to close this issue, comment if you dissagree)
