### ISSUE TITLE
Runtime Configuration Loading

### ISSUE THREAD

**Issue by bailejl** [angular/angular#24848]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Today, Angular 6 and AngularFire use environment configuration within the `@NgModule` decorator.  When I try to bypass the Angular compile-time environment configuration system and load a configuration at runtime, it is hard to do.  The `@NgModule` decorator in the AppModule is executed when the `main.ts` file is loaded.  Loading a runtime environment configuration file prior to the `@NgModule` decorator is unlikely. 

## Expected behavior

To the best of my knowledge, is not possible to load a runtime config in Angular when environment configuration is used in the `@NgModule` decorator.  I want to load a configuration at runtime and have my app use it.  All, I am asking for is either a documented process to do runtime configuration or changes to support runtime configuration. 

## What is the motivation / use case for changing the behavior?

I need to support the creation of one binary from a build process and have it used in N environments without knowing the environment and its config at build time.  This would greatly support continuous delivery, the dynamic creation of environments and environment configuration changes. 

### Continuous Delivery Use Case

I want my continuous integration process to store one Angular artifact in my repository.  Then deploy the Angular artifact to each in environment within my continuous delivery pipeline.  As it is deployed to an environment, the latest version of the environment's configuration is deployed alongside the Angular artifact.

### Dynamic Environment Creation Use Case

With modern tools, it is easy to make environment cookie cutter style.  There are a number of reasons to create environment dynamically.  In the process of development, developers may want to create their own dev environment.  Or a developer may need to duplicate an environment to troubleshoot an issue.  Having to build a new Angular artifact for each environment is fraught with danger and a runtime configuration solution is preferred.

### Environment Configuration Changes Use Case

The systems an Angular application will depend will most likely change.  If the configuration is baked in at compile time, this requires a new build and deployment.  Whereas, having a runtime configuration option make environments less painful.

## Environment

<pre><code>
Angular version: 6.0.2

Browser:
- [X] Chrome (desktop) version XX
- [X] Chrome (Android) version XX
- [X] Chrome (iOS) version XX
- [X] Firefox version XX
- [X] Safari (desktop) version XX
- [X] Safari (iOS) version XX
- [X] IE version XX
- [X] Edge version XX
 
For Tooling issues:
- Node version: 10.1.0  
- Platform:  Mac 

Others:

</code></pre>

**Comment by trotyl** [comment]
> AngularFire use environment configuration within the `@NgModule` decorator.

This is incorrect, any [`ModuleWithProviders`](https://angular.io/api/core/ModuleWithProviders) is just a shortcut of [`NgModule`](https://angular.io/api/core/NgModule) and [`ValueProvider`](https://angular.io/api/core/ValueProvider)s, there's no special logic for that.

No library can require using `NgModule` for configuration (but possibly recommends).

For `AngularFireModule.initializeApp(options, nameOrConfig)`, the two parameters are respectively `FirebaseOptionsToken` and `FirebaseNameOrConfigToken`, if you want to provide them dynamically, then `useFactory` should be used.

**Comment by robwormald** [comment]
As @trotyl says, factories are the right way to do this - the static `forRoot` / `initializeApp` etc methods are usually just sugar for configuring providers. Here's an example for firebase - https://stackblitz.com/edit/angular-qiy6t7?file=src%2Fapp%2Fapp.module.ts

We're looking at making this more flexible in the future, but for now this is the best way.

**Comment by bailejl** [comment]
@trotyl  and @robwormald   I appreciate the info and help with my problem. 

Thanks,
Joe
