### ISSUE TITLE
Renderer should not clear host contents when using Shadow DOM

### ISSUE THREAD

**Issue by robwormald** [angular/angular#24859]
When using Angular Elements with the new `ViewEncapsulation.ShadowDom` option, the renderer clears the pre-existing textContent of the selected root node: https://github.com/angular/angular/blob/master/packages/platform-browser/src/dom/dom_renderer.ts#L144

This prevents developers from using `<slot>` elements to do runtime content projection, eg
```ts
@Component({
  template: '<slot></slot>',
  encapsulation: ViewEncapsulation.Native,
  styles: [ `:host { color: red } `]
})
class MyComponent {}
```
```html
<my-component>ProjectedText</my-component>
```

This is the desired behavior when using Angular in "SPA" mode, where the app will own the whole DOM, but prevents runtime composition with Elements.

Normally, this could be handled in the Shadow DOM renderer, but because this selectRootElement() call happens from inside the view services,: https://github.com/angular/angular/blob/master/packages/core/src/view/services.ts#L756
the *default* renderer is used here, before the component is booted (?), there's no way to know if this is a ShadowDOM component or not, and the default implementation is used.

**Comment by benoitjchevalier** [comment]
Was tinkering with this and about to open an issue but feels like this might be the same issue. Just want to confirm that this issue covers what I found when using `ViewEncapsulation.ShadowDom`:
 - <slot> doesn't work  for angular *component* (not element)
- <slot> works for angular *element* within an angular app
- <slot> doesn't work  for angular *element* outside of an angular app (out of scope for now?)

three cases demoed here: https://stackblitz.com/edit/angular-slot-sd1

**Comment by robwormald** [comment]
@benoitjchevalier yes, this should fix the issue for (i believe) all three of those cases.
