### ISSUE TITLE
Angular Roadmap and browser support

### ISSUE THREAD

**Issue by camueller** [angular/angular#24855]
I'm working on project of major company considering Angular for development. The company has many corporate customers pinned to IE10 and IE11 which will stick to these versions for some time (years!)
The page https://angular.io/guide/browser-support outlines the current browser support.
However I did not find any statements until which time these browsers are supported.

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
