### ISSUE TITLE
Upgrade Error : 5.2.0 -> 6.0.9

### ISSUE THREAD

**Issue by abhishekgoenka** [angular/angular#24851]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am getting below error when migrating my application from Angular 5.2.10 to 6.0.9
![image](https://user-images.githubusercontent.com/14522198/42624057-131e23b8-85e2-11e8-9de1-b9f5082203b2.png)

## Expected behavior

Application should be successfully migrated.

## Minimal reproduction of the problem with instructions

I used the migration steps described [https://update.angular.io/](https://update.angular.io/)

## Environment
Development

<pre><code>
Angular version: 6.0.9

Browser:
- [X] Chrome (desktop) version  67.0.3396.99
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4  
- Platform:  Windows 

Others:

</code></pre>

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by abhishekgoenka** [comment]
The issue got resolved by created a new Angular6 application and moving existing application code into that. Automatic upgrade mentioned [here ](https://update.angular.io/) doesn't work.
