### ISSUE TITLE
Service worker refuses to cache assets as the ngsw.json is not fetched correctly

### ISSUE THREAD

**Issue by arangates** [angular/angular#24857]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
i did `ng add @angular/pwa` and i have this error in production build

```
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at Driver.<anonymous> (ngsw-worker.js:2297)
    at Generator.next (<anonymous>)
    at fulfilled (ngsw-worker.js:1752)
```
![screenshot from 2018-07-12 16-13-32](https://user-images.githubusercontent.com/7692801/42638683-928aa494-85ee-11e8-9d90-d15d8183f6f4.png)
i did some research and found that there is issue with 
`/ngsw.json?ngsw-cache-bust=0.08769372894975769` GET request. though the fetchLatestManifest returns 200 status code,response is not actually JSON , instead its no script version of `index.html` 

you can see response status is 200 for `/ngsw.json?ngsw-cache-bust=0.08769372894975769`
![screenshot from 2018-07-12 16-18-33](https://user-images.githubusercontent.com/7692801/42639198-b85cd560-85ef-11e8-9cd3-c8f86590169f.png)

but the actual response is not the required JSON
![screenshot from 2018-07-12 16-19-14](https://user-images.githubusercontent.com/7692801/42639199-b87eedda-85ef-11e8-877b-57539959ac75.png)

i tried copy as fetch option in chrome 
Actual
```
fetch("https://officehawk.com/ngsw.json?ngsw-cache-bust=0.7927584506157848", {"credentials":"omit","headers":{},"referrer":"https://officehawk.com/ngsw-worker.js","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"});
```
and i removed `?ngsw-cache-bust=0.7927584506157848` from the URL part of fetch and i can see that the response is JSON.

Edited
```
fetch("https://officehawk.com/ngsw.json", {"credentials":"omit","headers":{},"referrer":"https://officehawk.com/ngsw-worker.js","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"});
```
so you can see the contents of ngsw.json now
![screenshot from 2018-07-12 16-35-24](https://user-images.githubusercontent.com/7692801/42640246-2e313900-85f2-11e8-9347-2285051c6c83.png)

i suspect it has to be handled in this function ?
https://github.com/angular/angular/blob/0b4d85e9f19246af68a75140afc4db3d97f9ddfd/packages/service-worker/worker/src/driver.ts#L645
## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [x ] Chrome (desktop) version 67

**Comment by gkalpak** [comment]
This  doesn't sound like something that should normally happen, so likely something went wrong in the process. In any case, there is nothing we can do without a reproduction (and tbh this sounds more like a support request, for which [StackOverflow](http://stackoverflow.com/) is a more suitable place).

**Comment by jsanta** [comment]
Late response but I think it may help someone in case of having the same issue.
In my case the app is served through nginx, and the ngsw.json file was not found when requested with the cache-busting parameter.

After searching a while came to [this post on StackOverflow](https://stackoverflow.com/questions/51312819/angular-6-service-worker-refuses-to-cache-assets-as-the-ngsw-json-is-not-fetched) where the correct nginx settings are showed. Tried it and it works.
I guess the problem is not Angular but how the ngsw.json file is retrieved from the server.
