### ISSUE TITLE
[Feature] more control on event bubbling for Angular Elements

### ISSUE THREAD

**Issue by benoitjchevalier** [angular/angular#24863]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently when using an Emitter in an angular element there is no control over the `bubble` (event bubbling) and `composed` (traversing shadow dom) part of the event, both being always false: https://github.com/angular/angular/blob/master/packages/elements/src/utils.ts#L61

I am not familiar enough with the angular codebase to propose a solution, maybe this could be something that is passed in the constructor of the Emitter?

The current workaround is to get a reference to the nativeElement and manually dispatch a CustomElement

## Expected behavior
The ability to control the `composed` and `bubble` part of a CustomEvent fired by an angular emitter. 

## What is the motivation / use case for changing the behavior?
It is a common scenario to want events from a webcomponent to bubble so that someone using it can catch the event on a parent (for multiple instance of the same component, to more easily deal with components being dynamically added/removed from the dom..).

For example Polymer usually defaults to firing bubbling and composed custom events.

## Environment

<pre><code>
Angular version: 6.0.9

Browser:
N/A

**Comment by benoitjchevalier** [comment]
It would also be nice to have control over the casing of the event name, typically kebab casing it or at least lowercasing it, allowing other frameworks to have an event name as an attribute

**Comment by gkalpak** [comment]
Closing in favor of #39489, which has more discussion.
