### ISSUE TITLE
[ngClass] not working

### ISSUE THREAD

**Issue by sysmat** [angular/angular#24869]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
```
<i [ngClass]="{'fas fa-user-secret text-danger': true, 'fas fa-user-secret text-success': false}">
</i>

```
Not showing nothing
## Expected behavior

icon fa-user-secret should be rendered

## Environment

<pre><code>
Angular version: 6.0.9

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
Angular CLI: 6.0.8
Node: 9.2.1
OS: win32 x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3

**Comment by duki994** [comment]
Try ```fa``` instead of ```fas```

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/5763#issuecomment-166114033

**Comment by vicb** [comment]
Thanks @ericmartinezr for pointing to the correct answer.
