### ISSUE TITLE
Angular elements: Data Binding not working with lower camel case property name

### ISSUE THREAD

**Issue by SchneiderMK** [angular/angular#24871]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Given is a simple Component with a lower camel case input property called "firstName":
```typescript
import { Component, Input, OnInit, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-first',
  templateUrl: './first.component.html',
  styleUrls: ['./first.component.scss'],
  encapsulation: ViewEncapsulation.Emulated
})
export class FirstComponent implements OnInit {
  @Input() public firstName: string;
  constructor() { }
  ngOnInit() { }
}
```

When I create a web component (@angular/elements) and try to set the attribute firstName, data binding is not working. 
```html
<first-element firstName="Markus"></first-element>
```
After renaming the property to non camel case like "name" data binding works.

## Expected behavior
Data binding for web components should work with lower camel case property names

## Minimal reproduction of the problem with instructions
- Create new Project with @angular/cli
- ng add @angular/elements
- fix document-register-element bug by setting version to 1.8.1
- npm install
- ng g component first
- export component in app.module
- create bootstrapping for web component
- include component in index.html

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: V10.1.0
- Platform:  Windows

Others:

</code></pre>

**Comment by trotyl** [comment]
All inputs are converted to kebab-case in Angular Elements, it's now `first-name`.

**Comment by SchneiderMK** [comment]
many thanks to you!
using kebab-case did the trick.

Greetings
Markus

**Comment by gkalpak** [comment]
To add some context:
The custom elements created by `@angular/elements` are just regular HTML elements and don't go through Angular's compiler. HTML attributes are case-insensitive, so `firstName` is converted to `firstname` before Angular gets to it. Therefore, in order to be able to differentiate between properties `firstname` and `firstName`, input property names are camel-cased (as @trotyl explained above).
