### ISSUE TITLE
Docs - View Source button leads to 404 page

### ISSUE THREAD

**Issue by maxkorz** [angular/angular#24876]
## I'm submitting a...

<pre><code>[x] Documentation issue or request
</code></pre>

## Current behavior

https://angular.io/api/forms/EmailValidator
When I click the "View Source" button browser opens link https://github.com/angular/angular/tree/6.0.9/packages/forms/src/directives/validators.ts#L133-L167

## Expected behavior

Working link is https://github.com/angular/angular/tree/6.0.8/packages/forms/src/directives/validators.ts#L133-L167

I think the problem is that the 6.0.9 tree is not available: https://github.com/angular/angular/tree/6.0.9

**Comment by gkalpak** [comment]
The link is correct. The problem is that there is no `6.0.9` tag on GitHub, but there should be (since 6.0.9 has been released, based on 9e4558908).

cc @mhevery

**Comment by gkalpak** [comment]
@matias created the label. It should work now. Thx for reporting this.
