### ISSUE TITLE
Providing validators in sync function throws ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by piernik** [angular/angular#24873]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Here is reproduction: https://stackblitz.com/edit/angular-1j7x8p?file=src%2Fapp%2Fmy-input.component.ts

I'm creating `FormCotrols` in `ngFor` loop. When I provide standard validators like `Validators.compose([Validators.required])` all is ok. But when I use for this sync function it throws `ExpressionChangedAfterItHasBeenCheckedError`

## Expected behavior
Should not throw `ExpressionChangedAfterItHasBeenCheckedError`

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-1j7x8p?file=src%2Fapp%2Fmy-input.component.ts

Throws `https://stackblitz.com/edit/angular-1j7x8p?file=src%2Fapp%2Fmy-input.component.ts`
Comment in `this.getValidators(this.field.validators)`
Comment out `Validators.compose([Validators.required])`
Alle works

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
Expected behavior, a `FormGroup` cannot be shared between multiple `FormGroupDirective`s.

Also, it's exact the same error as using `Validators.compose()`: https://stackblitz.com/edit/angular-gzxxtq?file=src/app/my-input.component.ts

**Comment by piernik** [comment]
What do You mean: `a FormGroup cannot be shared between multiple FormGroupDirectives.` I think it's normal practice in custom inputs since `formControlName` have to have `FormGroup` as parent.

**Comment by trotyl** [comment]
> I think it's normal practice in custom inputs since `formControlName` have to have `FormGroup` as parent.

You can create `FormGroup` as parent of your control, it's fine, but each `FormGroup` instance can only be used in one place.

If you want to pass an existing `FormGroup` through host boundary, see https://github.com/angular/angular/issues/12504#issuecomment-350133595.

**Comment by kara** [comment]
@piernik  When you add a validator in the init hook of the `MyInput` component, you're recalculating the validation status of the `FormGroup` you passed down from the parent component, and taking it from `valid` to `invalid`. This is problematic because there are classes bound to this validation status in the parent component. They have already been checked by change detection, so the framework rightly throws a "changed after checked" error. So this is working as intended.

For a single custom input like that, you will probably want to try implementing `ControlValueAccessor` and using a `FormArray` rather than looping over and creating two `FormGroupDirectives` manually.

**Comment by piernik** [comment]
@kara thanks for response. I resolved it by adding container component that is responsible for creating `FormGroup`. That way `my-input` has all controlers on init.
