### ISSUE TITLE
Add warning if route resolver never emits before completing

### ISSUE THREAD

**Issue by ukrukarg** [angular/angular#24878]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
If I have a resolver, that completes but never emits (eg. return observableOf()), router start behaving very weirdly (it never updates the URL to new url).

## Expected behavior
I would expect router to print some kind of console warning that says "Your resolver completed but never emitted any value. Navigation failed.". Even if I don't have tracing enabled.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-fkfezm?file=src/app/crisis-center/crisis-detail-resolver.service.ts

Go to crisis-center and click on a crisis. It never navigates, having a warning on the console would be super useful here.

## What is the motivation / use case for changing the behavior?
Easy of debugging.

**Comment by jasonaden** [comment]
Interesting idea. However, this looks like it would be a breaking change to existing apps that may be using resolvers to run code that produces side effects, but don't care about the return value.

If there's a problem where the application is behaving strangely in the case of an empty resolver, please file a bug with reproduction steps for that issue. If you do so, please produce clear steps to reproduce including what's happening and what the expected result is.

**Comment by ukrukarg** [comment]
The thing is, if you do that you still need to emit something, otherwise route resolution never finishes. Resolver needs to emit and complete, if it only completes than routing is broken, like in the sample app I attached.
