### ISSUE TITLE
documentation: beforeEach(async()) is never explained

### ISSUE THREAD

**Issue by ShaneCourtrille** [angular/angular#24882]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
In https://angular.io/guide/testing there is no explanation for beforeEach(async(... and how it differs from beforeEach(... 

## What is the motivation / use case for changing the behavior?
Providing clarity for people writing tests

**Comment by JiaLiPassion** [comment]
@ShaneCourtrille, I had a PR to describe new features of `async`, I would like to add `beforeEach` doc there.  https://github.com/angular/angular/pull/23117

**Comment by ShaneCourtrille** [comment]
@JiaLiPassion That makes sense to me.

**Comment by JiaLiPassion** [comment]
@ShaneCourtrille, I just found in current `angular.io` here  https://angular.io/guide/testing#the-async-beforeeach, there is explanation of `async beforeEach`, so I think I will not add additional information in my PR.

**Comment by ciesielskico** [comment]
There is nothing (anymore?) about `beforeEach` and `async` mentioned in the provided link by @JiaLiPassion

**Comment by gkalpak** [comment]
@ciesielskico: The testing guide has been split up into smaller ones. The new URL is https://v10.angular.io/guide/testing-components-scenarios#the-async-beforeeach.
(Alternatively, you can use the `v9` sub-domain with the old URL: https://v9.angular.io/guide/testing#the-async-beforeeach)

**Comment by aikidave** [comment]
It looks like https://angular.io/guide/testing-components-scenarios#the-async-beforeeach covers this issue. Closing!
