### ISSUE TITLE
ERROR in src/app/heroes/heroes.component.ts(2,22): error TS2307: Cannot find module '../hero'.

### ISSUE THREAD

**Issue by renatoqueiroz** [angular/angular#24887]
Pessoal, Estou Seguindo o tutorial Angular Tour of Heroes e tenho o seguinte problema:
[ts] Não é possível encontrar o módulo '../hero'.

ERROR in src/app/heroes/heroes.component.ts(2,22): error TS2307: Cannot find module '../hero'.

me ajudem a resolver isso por favor!! Grato!!

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
