### ISSUE TITLE
Fix capitalization in API reference templates

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#24880]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[X ] Other... Please describe: API ref generation infrastructure
</code></pre>

## Current behavior

Mix. Some sentence caps, some title caps. 

## Expected behavior

Sentence caps for all headings, per Google Dev Doc Style Guide (yes, we're updating the Angular Authors Guide to match)

## Minimal reproduction of the problem with instructions

https://angular.io/api/animations/AnimationPlayer
"Class Implementations" should be "Class implementations"

## What is the motivation / use case for changing the behavior?

Google style

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
@petebacondarwin Not sure if you already had an issue or PR for tracking this. I took the liberty of assigning and triaging. :-)

**Comment by petebacondarwin** [comment]
I thought I fixed this somewhere. But if not I will knock up a quick fix now.

**Comment by petebacondarwin** [comment]
I did have this PR landed a while back: https://github.com/angular/angular/pull/24527

**Comment by petebacondarwin** [comment]
Perhaps a missed a few?

**Comment by petebacondarwin** [comment]
There you go: https://github.com/angular/angular/pull/24949. Just those two got missed.
