### ISSUE TITLE
Detailed documentation on preserveWhitespaces has disappeared

### ISSUE THREAD

**Issue by pcroc** [angular/angular#24896]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Detailed documentation of preserveWhitespaces no longer exists.

v5 documentation for Component describes preserveWhitespaces and its nuances (ngPreserveWhitespaces, &ngsp etc.):
https://v5.angular.io/api/core/Component
(scroll to the bottom)

v6 (and vNext) documentation does not:
https://angular.io/api/core/Component#preserveWhitespaces
https://next.angular.io/api/core/Component#preserveWhitespaces

## Expected behavior
Details of preserveWhitespaces are documented.

Side note - wherever the preserveWhitespaces details are documented, they should be referenced/linked from all places that mention this (Component, The Ahead-of-Time (AOT) Compiler, compiler options, etc.)

## What is the motivation / use case for changing the behavior?
preserveWhitespaces is now false by default, and has issues (see https://github.com/angular/angular/issues/21049) and there is no documentation that explains the available workarounds other than enabling preserveWhitespaces.

**Comment by trotyl** [comment]
It's still living in code:

https://github.com/angular/angular/blob/74b250b1465661292dfcdd67444261cacb78bf3f/packages/core/src/metadata/directives.ts#L709-L760

This is bug of docs-infra, which extracts `@usageNotes` from `ComponentDecorator` rather than `Component` (or got overwritten).

**Comment by jenniferfell** [comment]
Seems to still be an issue at this time looking at v5 compared to v6.

**Comment by jenniferfell** [comment]
@jbogarthyde @petebacondarwin Is this a template-dgeni issue or a content issue?

**Comment by jbogarthyde** [comment]
I think this is Pete - I'm still a bit confused about where directive doc gets taken from, and where @usageNotes is allowed. Hence the need to get the current template landed so I can see how the test-doc works.

**Comment by jbogarthyde** [comment]
No, I think it's me - half of the usage notes for `@Component` were on the wrong object. This should be fixed in PR #24135

**Comment by IgorMinar** [comment]
We fixed this in the last few weeks and both angular.io and next.angular.io now correctly show the content.

https://angular.io/api/core/Component#preserveWhitespaces
https://next.angular.io/api/core/Component#preserveWhitespaces
