### ISSUE TITLE
ngc's lower_expressions.ts is fragile wrt. AST modifications

### ISSUE THREAD

**Issue by mprobst** [angular/angular#24895]
Angular's compiler at some point during processing constructs a map of expressions that should be extracted out of their context, and later on looks up those expressions to construct extra exports. The map is keyed by the Node's `pos`ition, but also checks its `kind` and `end`.

This data is collected before other transformers run, but then (apparently) only acted on after other transformers have modified the AST.

This is problematic, because the code is now fragile wrt. AST transformations. If a transformer step substitutes a different AST kind of an existing expression, or changes its text range, the later substitution step breaks, causing missing identifiers (apparently other code is keyed off the generated names).

As an example, `tsickle` would like to remove any TypeScript `foo as Bar` style type assertions and replace them with Closure casts, generating `(/** @type {Bar} */ (foo))`. `tsickle` must fully remove the TypeScript cast because TypeScript otherwise removes any extra parentheses around it. Now because Angular depends on a node with `kind == SyntaxKind.TypeAssertion`, things break.

Would it be possible to structure this code to be less fragile wrt AST transformations, e.g. by acting on the collected information in the same processing step, before any other code transforms the AST?

Code in question:
https://github.com/angular/angular/blob/master/packages/compiler-cli/src/transformers/lower_expressions.ts#L290

**Comment by mhevery** [comment]
I believe this will become moot with `ngtsc` @alxhub can you comment?

**Comment by alxhub** [comment]
Agreed, this is moot in Ivy. Closing as "won't fix".
