### ISSUE TITLE
ivy: let method `container` also divide to accept dynamic block like `elementStart` and `containaerRefreshStart`

### ISSUE THREAD

**Issue by studioTeaTwo** [angular/angular#24893]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
`container()` which is public API in render3 takes **static template** as argument. 

## Expected behavior
Divide it into `containerStart()` and` containerEnd()`

## What is the motivation / use case for changing the behavior?
I want to construct dynamically a child template with intervening methods such as `elementStart()`, `text()`. Like below:

```typescript
if (renderFlag & RenderFlags.Create) {
  // some parent template

  containerStart();
    embeddedViewStart(0);
      elementStart(0, 'div');
        text(1, 'text');
      elementEnd();
    embeddedViewEnd();
  containerEnd();
}
```

I am trying to use a template literal syntax using ivy. For example, using **lit-html** like below:

```html
    return html`
      <button on-click=${this.onChange}>Click Me</button>
      ${this.value === 'initial' ?
        html`<span>text1</span>` :
        html`<video><source src="sample.mp4"></video>`}
    `;
```

So, the current implementation, which construct the child template such as `<span> or <video>` 
in the example above, is that it executes only `container()` and `markDirty()` in create mode, then  constructs a real template through `containerRefreshStart()` and `embeddedViewStart()` in update mode.

For more information, the experimental library is here:
https://github.com/studioTeaTwo/lit-fy

**Comment by mhevery** [comment]
@studioTeaTwo Thanks for the request. 

- Ivy is still very much an flux, and we are not considering any features which are not strictly needed to get us to make Ivy the primary renderer (such as this one). 
- What you are requesting would complicate things because it would mean that there are multiple sub blocks in the main template block. I think it is better solved by decomposing it into separate templates as we require now. For this reason, I don't think we want to implement this.

closing as won't implement.

**Comment by studioTeaTwo** [comment]
@mhevery I see.

> it is better solved by decomposing it into separate templates

I think current Angular system is to *decompose it into separate components*(not templates).

I want to do the same thing like *ngIf using standard syntax.
That is to have a simpler way to make us look like we are writing ATOMS and MOLECULES just with templates, even if it is internally processed as a component.

Like this?

```html
const someAtomsA = ng`<h1>${this.title}<h1>`;
const someAtomsB = ng`<span>text1</span>`;
const someAtomsC = ng`<video><source src="sample.mp4"></video>`;

const template = ng`
      ${someAtomsA}
      <button on-click=${this.onChange}>Click Me</button>
      ${this.value === 'initial' ? ${someAtomsB} : ${someAtomsC}}
    `;
```

I trust and love Angular's robust basis. 
With Service, DI and Container Component as usual, I think nice that we will be able to do it.

Thank you.
