### ISSUE TITLE
Issue in documentation UI 

### ISSUE THREAD

**Issue by thamsrang** [angular/angular#24902]
Hi,
In the documentation table header shown as list. 
https://angular.io/api/router/Router#properties

This issue due to style in below line.
https://github.com/angular/angular/blob/74b250b1465661292dfcdd67444261cacb78bf3f/aio/src/styles/2-modules/_api-pages.scss#L35

`display: flex` should be replace with `display: table-cell`

![angular_issue](https://user-images.githubusercontent.com/5862307/42762424-f938f49c-892d-11e8-9559-e1ade7d73437.png)

**Comment by jenniferfell** [comment]
Looks like this is fixed. Thanks for submitting. Closing.
