### ISSUE TITLE
Renderer: Using DynamicComponentLoader to load a component with a template that is

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2490]
a single binding, e.g. {{text}}, fails with an out of range exception.

I can add a simple reprocase if needed.

@tbosch 

Workaround: Wrap in a `<span>`

**Comment by tbosch** [comment]
@matanlurey I just checked in our tests and we actually have a test for exactly this case, which is fine. Could you add a reprocase that is simple but still fails?

**Comment by vicb** [comment]
@matanlurey any chance you have a `<content>` anywhere before the `{{text}}`?

**Comment by matanlurey** [comment]
I haven't had the chance to write a repro case but let's assume that it either works or the workaround is good enough for this release.
