### ISSUE TITLE
"ng g component" command line make app-module.ts error

### ISSUE THREAD

**Issue by xiongyechang** [angular/angular#24903]
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { NgZorroAntdModule, NZ_I18N, zh_CN } from 'ng-zorro-antd';
import { AppComponent } from './app.component';
import { MainComponent } from './components/main/main.component';
import { AdminComponent } from './components/admin/admin.component';
import { SiteComponent } from './components/site/site.component';
import { ResourceComponent } from './components/resource/resource.component';

/** 配置 angular i18n **/
// import { registerLocaleData } from '@angular/common';
// import zh from '@angular/common/locales/zh';
// registerLocaleData(zh);

@NgModule({
  declarations: [
    AppComponent,
    MainComponent,
                                                                   **run "ng g c component/site", then  AdminComponent change 
                                                                   to AdminCompo** 
    AdminCompo, ------------------------------------------------------------------error 1
    SiteComponent,
                                                                  **run "ng g c component/resource", ResourceComponent to be 
                                                                   ResourceComponentnent** 
    ResourceComponentnent ------------------------------------------------------error 2
                                                                 **angular-cli version: **6.0.8****
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpClientModule,
    BrowserAnimationsModule,
    /** 导入 ng-zorro-antd 模块 **/
    NgZorroAntdModule
  ],
  bootstrap: [ AppComponent ],
  /** 配置 ng-zorro-antd 国际化 **/
  providers   : [ { provide: NZ_I18N, useValue: zh_CN } ]
})
export class AppModule { }

**Comment by xiongyechang** [comment]
"ng g component" command line make app-module.ts error

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Please report angular-cli issues in its repo

**Comment by matsko** [comment]
Closing for now. Please refer to @ericmartinezr's comment or look at @angular/cli.
