### ISSUE TITLE
Unable to get element ref using FormControl

### ISSUE THREAD

**Issue by AkhilNaidu09** [angular/angular#24900]
I have a FormGroup with set of FormControls (set of 30+ fields), when i am clicking on submit button i am doing validations with following logic 

 ```
validateAllFields(formGroup: FormGroup) {
        Object.keys(formGroup.controls).forEach(field => {
            const control = formGroup.get(field);
            if (control instanceof FormControl) {
                control.markAsTouched({ onlySelf: true });
            } else if (control instanceof FormGroup) {
                this.validateAllFields(control);
            }
        });
    }
```
validations were firing perfectly but my requirement is along with firing validations i need to focus the first invalid input. I was trying to debug but i was unable to access the respective HTML elements, Can anyone please tell me the best way to solve this issue.

## Environment

<pre><code>
Angular version: 4.4.6

Browser:
- All Browsers

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
