### ISSUE TITLE
how to insert a dom node inside a directive?

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#2491]
Suppose I have a directive:
```js
import { Directive } from 'angular2/angular2';
import { ProtoViewRef, ViewContainerRef } from 'angular2/core'

@Directive({
    selector: 'icon',
    properties: [
        'src'
    ]
})

export class Icon {
    viewContainer: ViewContainerRef;
    protoViewRef: ProtoViewRef;
    _viewContainer: ViewContainerRef;
    constructor(viewContainer: ViewContainerRef) {
        this._viewContainer = viewContainer;
    }
    set src(src: string) {
        let node; // some DOM Node
        this._viewContainer.insert(node); // does not work
    }
}
```
Is there a way to insert something in the view container (which in this case would be the `icon` element)? Node that I am using the `NativeShadowDomStrategy`, so it might mean I have to insert in the shadow dom?

**Comment by mhevery** [comment]
Here is the plan: https://github.com/angular/angular/issues/2476

**Comment by rolandjitsu** [comment]
@mhevery thanks :)

**Comment by rolandjitsu** [comment]
@mhevery should I use `DOM` for appending elements into a directive? I can see that `angular2/src/dom/dom_adapter` exports `DOM` which is also used by the `class` directive to add a class to an element. I suppose I could use the `appendChild` to add a node inside the directive?

Just that I am concerned what happens if the directive has a shadow root, will it still work?!

**Comment by mhevery** [comment]
`DOM` is a private API. We need it because we generate both JS and Dart, but unless you are planning to have your code run on Dart it is not needed.

**Comment by rolandjitsu** [comment]
@mhevery I understand. I actually use the following for appending an element into a directive:
```js
if (supportsNativeShadowDOM) root = this.el.createShadowRoot();
else root = this.el; 
this.icon.get(src).then((svg) => {
    root.appendChild(svg);
});
```
Where `this.el = this.elementRef.domElement;`. That seems to work just fine, the only issue is if I do not use a shadow root and I just `appendChild` to the element I, sometimes, get duplicates. As if I would `appendChild` twice.
You also mentioned that access to `domElement` will be changed, do you have a link to a document showing how I will get access to that in the future?
