### ISSUE TITLE
Support for accounting format in currency pipe

### ISSUE THREAD

**Issue by GazonkFoo** [angular/angular#24917]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Angular uses the currency formatting extracted from CLDR to format currencies with the currency pipe.
However CLDR also contains formatting rules for currencies used in an accounting context.
see currency-accounting: http://cldr.unicode.org/translation/number-patterns

For example the english accounting standard is to use parentheses to display negative numbers.
This is currently not supported by the currency pipe and as far as i can tell this information is not extracted from CLDR.

## Expected behavior

Currency pipe has an option to switch to accounting format (default is non-accounting, as it is now).

## What is the motivation / use case for changing the behavior?

Enterprise application which displays currency values in grids.

## Environment

<pre><code>
Angular version: 6.0.9

**Comment by trotyl** [comment]
Relates to https://github.com/angular/angular/issues/23607 about extra CLDR data support.

**Comment by vicb** [comment]
Thanks for your feature request.

This format is not widely used and we will probably not include that in Angular.

@ocombe has made the scripts that are used to extract CLDR data. He will create a doc that describes how to extract your own data and use them so that you can create your own pipe.

**Comment by petebacondarwin** [comment]
Closing as this feature does not have much interest and it would add more weight to the locale files.
