### ISSUE TITLE
docs: Provide an example for reading the routing data property

### ISSUE THREAD

**Issue by DeborahK** [angular/angular#24910]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

This documentation section: https://angular.io/guide/router

The example routing configuration in the documentation includes this line of code:

`data: { title: 'Heroes List' }`

The text associated with that line of code says: "The data property in the third route is a place to store arbitrary data associated with this specific route. The data property is accessible within each activated route. Use it to store items such as page titles, breadcrumb text, and other read-only, static data."

But then there is no demo code shown for how to *read* that data property. The sample code provided with this documentation does *not* include an example of using this property.

## Expected behavior

The documentation should include an example of how to read this property. And if possible, the sample application should include this example as well.

## What is the motivation / use case for changing the behavior?

This request stems from a stackoverflow question. I wanted to point the posted to the docs and realized that there was no coverage of this.

## Environment

<pre><code>
Angular version: 6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by atscott** [comment]
Closing as likely obsolete. There is an example of reading data in the [router tutorial](https://angular.io/guide/router-tutorial-toh#resolve-pre-fetching-component-data) and the [ActivatedRoute](https://angular.io/api/router/ActivatedRoute#description) description
