### ISSUE TITLE
URI reserved characters []!'()* are not supported in the url 

### ISSUE THREAD

**Issue by arangates** [angular/angular#24921]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

With this routing pattern: path: 'items/:paramA/:paramB' and this url: localhost:4200/items/BA(p9)677/Something, I get Error: Cannot match any routes. URL Segment: 'p9'. Even if I manually decode it to localhost:4200/items/BA%28p9%29677/Something, I get the same error.

## Expected behavior

url must allow parentheses via routing

<pre><code>
Angular version: 6.0.0

**Comment by mlc-mlapis** [comment]
@arangates ... collision with `named routes`?

**Comment by jasonaden** [comment]
It appears @mlc-mlapis is correct. The parenthesis will collide with the named routes feature. There are ways around this such as serializing your URL with the Angular URL serializer, but there's no reproduction attached so can't really point you in the direction of fixing this. Also, this question belongs on StackOverflow.

**Comment by Matmo10** [comment]
This seems like a legit bug in the case where the reserved characters are encoded in the url. Why shouldn't [this](https://github.com/angular/angular/issues/10280#issuecomment-382857471) be possible?

**Comment by jasonaden** [comment]
@Matmo10 I understand what you're saying, but this issue can't be a "legit bug" as it has no reproduction or steps to reproduce.

Maybe with a new issue, we could open up the dialog on this again. However, I'm inclined to just recommend replacing the [UrlSerializer](https://angular.io/api/router/UrlSerializer) with one that fits your application's URL scheme better.

**Comment by Matmo10** [comment]
Thanks for the tip Jason. After further verification, it looks like routing *does* work as long as the reserved characters are encoded. I'll just extend UrlSerializer and manually encode things before letting Angular do its thing.
