### ISSUE TITLE
ShadowDomStrategy should not insert styles into document.head

### ISSUE THREAD

**Issue by vicb** [angular/angular#2492]
As of today the Emulated strategies insert the `<style>` tags into the document head.

This will not work when templates are compiled server-side.

The style information should be part of the template and inserted into the doc head the component is first instantiated.

/cc @tbosch

**Comment by mhevery** [comment]
Is this still an issue with the latest change to the way we do encapsulation?

**Comment by gdi2290** [comment]
the current solution, for server rendering and encapsulation emulated, is combining all the styles using `SharedStylesHost.getAllStyles()` into a serialized stylesheet next to the serialized app. 
```html
<body>
  <!-- stylesheet hosts -->
  <style></style>
  <!-- app -->
  <app></app>
</body>
```
The problem now is that the client is not aware of the host's location generated from the server so it the client injects the styles in the `<head>`. With encapsulation none we have no control and with encapsulation native that just doesn't work on the server

**Comment by tbosch** [comment]
We have a new design for the compiler (will make public soon) that will solve this issue.

**Comment by tbosch** [comment]
The change is not yet implemented on master, but will hopefully be in about 3 weeks.
