### ISSUE TITLE
Convenient way to define context of a sub-template

### ISSUE THREAD

**Issue by sebek64** [angular/angular#24926]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## What is the motivation / use case for changing the behavior?
Assume that you want to define a context for a part of the template, like on the following artificial example:

```
<ng-container [some-way-to-specify-context]="{success: noError && resultAvailable; issueCount: warningCount + errorCount">

<h1 [class.success]="success">
<i class="fas" [class.fa-check]="success">
{{title}}
</h1>

<div>Issue count: {{issueCount}}</div>

<div *ngIf="issueCount > 0">
...
</div>

</ng-container>
```

Currently, we have multiple choices:

- use nested ngIf directives (not convenient for more variables, not usable for variables which can have "false" values like issueCount above)
- use *ngTemplateOutlet (probably the best choice now, but a bit cumbersome)
- use [ngTemplateOutlet] - quite comparable to the previous choice
- write a custom structural directive similar to ngTemplateOutlet
- refactor the code so that the sub-template is moved into a sub-component (often a good idea, but not always)

There might be other options which I do not know about. Here I describe the choices in more detail.

Nested ngIfs:

```
<ng-container *ngIf="noError && resultAvailable as success">
<ng-container *ngIf=warningCount + errorCount as issueCount">
...
</ng-container>
</ng-container>
```

The above code fails if issueCount si 0.

Using *ngTemplateOutlet:

```
<ng-template #xxx let-success="success" let-issueCount="issueCount">
...
</ng-template>
<ng-container *ngTemplateOutlet="xxx; context: {success: noError && resultAvailable, issueCount: warningCount + errorCount}">
</ng-container>
```

The above code works, but it is a bit cumbersome. In my opinion, the biggest problem is unnecessary bloat of global namespace with template reference variable.

Another way to write the same:

```
<ng-template #xxx let-success="success" let-issueCount="issueCount" [ngTemplateOutlet]="xxx" [ngTemplateOutletContext]="{success: noError && resultAvailable, issueCount: warningCount + errorCount}">
...
</ng-template>
```

Another option is to write a custom structural directive. Then, the code might look like (skipping obvious directive implementation):

```
<ng-container *customContext="{success: noError && resultAvailable, issueCount: warningCount + errorCount}">
</ng-container>
```

Nice and clean, but I feel that for something like this, we should have support in angular itself, without the need to write a custom directive. I have two suggestions how this can be achieved.

The first possibility is to allow code like this:

```
<ng-container *ngTemplateOutlet="undefined; context: {success: noError && resultAvailable, issueCount: warningCount + errorCount}">
</ng-container>
```

That would require an extension to ngTemplateOutlet to obtain TemplateRef in its constructor and use that value if undefined is provided as the input.

Other possibility is to extend template syntax to support the following:

```
<ng-container *ngTemplateOutlet="$this; context: {success: noError && resultAvailable, issueCount: warningCount + errorCount}">
</ng-container>
```

where $this may be any string providing a reference to underlying ng-template (for example, ngTemplate string might be used).

I'd like to know angular developers opinion about this. If the first choice is preferred, I'm able to implement that change and send a pull request.

## Environment

<pre><code>
Angular version: 6.0.9

**Comment by mhevery** [comment]
`let` is the way one defines the context of the template as you pointed out. `<ng-template #xxx let-success="success" let-issueCount="issueCount">` Your feature request seems to be to make it less cumbersome, but no syntax has been proposed.

Clearly you put a lot of time into this issue, and we appreciate it. Currently we have no plans to change this syntax since it is not clear what less-cumbersome solution would look like.

**Comment by sebek64** [comment]
@mhevery Well, thank you for your comment on this issue. As I see no particular objections aganst my first suggested solution, I'll try to prepare a pull request.
