### ISSUE TITLE
[i18n][API docs] better describe what getLocaleDayNames returns

### ISSUE THREAD

**Issue by ghost** [angular/angular#24929]
## I'm submitting a...

<pre><code>[x] Bug report</code></pre>

## Current behavior

[getLocaleDayNames](https://angular.io/api/common/getLocaleDayNames) returns `Days of the week for the Gregorian calendar (e.g. [Sunday, Monday, ... Saturday] for en-US).`

It returns `Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday` for en-GB locale

## Expected behavior

It should return days of the week in the correct order for selected locale: `Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday`

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-g9zlfz?file=src%2Fapp%2Fapp.component.html

## What is the motivation / use case for changing the behavior?

I rely on Angular's built-in internationalization and I expect to get the days of week in the correct order for various languages.

## Environment

<pre><code>Angular version: 6.0.9</code></pre>

**Comment by trotyl** [comment]
All locale APIs are low-level and orthogonal, there's already the `getLocaleFirstDayOfWeek` API providing that info and combine them in whatever algorithm.

Since week data are all stored from Sunday to Saturday, it could guarantee no unnecessary computation happens behind the scene, but only direct data-retrieval.

**Comment by vicb** [comment]
As mentioned by trotyl, you should use `getLocaleFirstDayOfWeek` to get the first day of the week.

I'm leaving this issue opened for us to improve the docs on `getLocaleDayNames`.

@ocombe could you please add more details to what is returned by `getLocaleDayNames`. Thanks.

**Comment by petebacondarwin** [comment]
Closing as this has low interest and no one has offered to improve the docs further than they are right now.
