### ISSUE TITLE
Bug in 'Create a delayed sequence' code sample in the observables docs

### ISSUE THREAD

**Issue by mchaitanya** [angular/angular#24939]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The code sample doesn't work. The problem is on this line: 
```ts
doSequence(arr, idx++);
```
The postfix ++ operator returns the original value before the increment. The doSequence call isn't passed the incremented index and the recursion doesn't terminate.

## Minimal reproduction of the problem with instructions

You can run the sample here:
https://stackblitz.com/edit/js-f3ncip

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by brandonroberts** [comment]
Fixed in https://github.com/angular/angular/pull/24911

**Comment by ajitsinghkaler** [comment]
@gkalpak @kapunahelewong I think we can close this as #24911 resolves it
