### ISSUE TITLE
Object doesn't support property or method 'fill' error thrown in IE11 when attempting to fill angular material table with data

### ISSUE THREAD

**Issue by ajborn** [angular/angular#24933]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
MatTable fails to load data in IE11
Error message `SCRIPT438: Object doesn't support property or method 'fill'`

## Expected behavior
MatTable should load data in IE11

## Minimal reproduction of the problem with instructions
Attempt to Angular Material Table with data as shown below
`<table-component (deleted)="onDeleted($event)" [data]="tableData" [displayedColumns]="columns"></table-component>`

`tableData` is passed from ParentComponent as well as `columns`.

## What is the motivation / use case for changing the behavior?
Creating corporate web app to be able to run in IE11.

## Environment
Angular version: 6.0.7

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11
- Platform: Windows

Others:

table.component.ts
`import {	Component, EventEmitter, OnInit, ViewChild, Input, Output } from '@angular/core';
import { MatPaginator, MatSort, MatTableDataSource } from '@angular/material';
import { trigger, state, style, transition, animate } from '@angular/animations';
import { ClientService } from '../../Services/clientService.service';

@Component({
	selector: 'table-component',
	styleUrls: ['table.component.css'],
	templateUrl: 'table.component.html',
	providers:[ClientService]
})
export class TableComponent implements OnInit {
	@Input() data: any[];
	@Input() displayedColumns: string[];
	@Output() deleted = new EventEmitter<boolean>();
	dataSource: MatTableDataSource<any[]>;

	@ViewChild(MatPaginator) paginator: MatPaginator;
	@ViewChild(MatSort) sort: MatSort;

	constructor(private _clientService: ClientService) {}

	ngOnInit() {
		this.dataSource = new MatTableDataSource(this.data);
		this.dataSource.paginator = this.paginator;
		this.dataSource.sort = this.sort;
	}

	applyFilter(filterValue: string) {
		this.dataSource.filter = filterValue.trim().toLowerCase();

		if (this.dataSource.paginator) {
			this.dataSource.paginator.firstPage();
		}
	}
	delete(exception: any) {
		let cle = {
			contractorID: exception.contractorID,
			officeName: exception.officeName,
			prismClientID: exception.prismClientID
		};
		this._clientService.DeleteClientLocatorException(cle).subscribe((data) => {
			this.deleted.emit(true);
			this.dataSource.disconnect();
			this.dataSource.connect();
		});;
	}}`

table.component.html
`<mat-form-field>
	<input matInput (keyup)="applyFilter($event.target.value)" placeholder="Filter">
</mat-form-field>

<div class="mat-elevation-z8">
	<table mat-table [dataSource]="dataSource" matSort [trackBy]="id">

		<ng-container matColumnDef="prismClientName">
			<th mat-header-cell *matHeaderCellDef mat-sort-header> Prism Client Name </th>
			<td mat-cell *matCellDef="let row"> {{row.prismClientName}} </td>
		</ng-container>

		<ng-container matColumnDef="officeName">
			<th mat-header-cell *matHeaderCellDef mat-sort-header> Office Name </th>
			<td mat-cell *matCellDef="let row"> {{row.officeName}} </td>
		</ng-container>

		<ng-container matColumnDef="contr_Cmpy_NM">
			<th mat-header-cell *matHeaderCellDef mat-sort-header> Company Name </th>
			<td mat-cell *matCellDef="let row"> {{row.contr_Cmpy_NM}} </td>
		</ng-container>

		<ng-container matColumnDef="exceptionType">
			<th mat-header-cell *matHeaderCellDef mat-sort-header> Exception Type </th>
			<td mat-cell *matCellDef="let row"> {{row.exceptionType}} </td>
		</ng-container>

		<ng-container matColumnDef="id">
			<th mat-header-cell *matHeaderCellDef></th>
			<td mat-cell *matCellDef="let row"> <a mat-raised-button (click)="delete(row)">REMOVE</a></td>
		</ng-container>

		<tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
		<tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
	</table>

	<mat-paginator [pageSizeOptions]="[5, 10, 25, 100]"></mat-paginator>
</div>

`

**Comment by matsko** [comment]
Hello @ajborn please repost this issue in [https://github.com/angular/material2](@angular/material)

**Comment by ajborn** [comment]
@matsko 

I forgot to put this in. This is the function failing from usin the `Array.fill()` function.  This is also in he angular repo [https://github.com/angular/angular/blob/b7544cccc699c2274bbc9a3e2eb4351632d0b410/packages/core/src/reflection/reflection_capabilities.ts](https://github.com/angular/angular/blob/b7544cccc699c2274bbc9a3e2eb4351632d0b410/packages/core/src/reflection/reflection_capabilities.ts)

`ReflectionCapabilities.prototype._ownParameters = function (type, parentCtor) {
        var typeStr = type.toString();
        // If we have no decorators, we only have function.length as metadata.
        // In that case, to detect whether a child class declared an own constructor or not,
        // we need to look inside of that constructor to check whether it is
        // just calling the parent.
        // This also helps to work around for https://github.com/Microsoft/TypeScript/issues/12439
        // that sets 'design:paramtypes' to []
        // if a class inherits from another class but has no ctor declared itself.
        if (DELEGATE_CTOR.exec(typeStr) ||
            (INHERITED_CLASS.exec(typeStr) && !INHERITED_CLASS_WITH_CTOR.exec(typeStr))) {
            return null;
        }
        // Prefer the direct API.
        if (type.parameters && type.parameters !== parentCtor.parameters) {
            return type.parameters;
        }
        // API of tsickle for lowering decorators to properties on the class.
        var tsickleCtorParams = type.ctorParameters;
        if (tsickleCtorParams && tsickleCtorParams !== parentCtor.ctorParameters) {
            // Newer tsickle uses a function closure
            // Retain the non-function case for compatibility with older tsickle
            var ctorParameters = typeof tsickleCtorParams === 'function' ? tsickleCtorParams() : tsickleCtorParams;
            var paramTypes_1 = ctorParameters.map(function (ctorParam) { return ctorParam && ctorParam.type; });
            var paramAnnotations_1 = ctorParameters.map(function (ctorParam) {
                return ctorParam && convertTsickleDecoratorIntoMetadata(ctorParam.decorators);
            });
            return this._zipTypesAndAnnotations(paramTypes_1, paramAnnotations_1);
        }
        // API for metadata created by invoking the decorators.
        var paramAnnotations = type.hasOwnProperty(PARAMETERS) && type[PARAMETERS];
        var paramTypes = this._reflect && this._reflect.getOwnMetadata &&
            this._reflect.getOwnMetadata('design:paramtypes', type);
        if (paramTypes || paramAnnotations) {
            return this._zipTypesAndAnnotations(paramTypes, paramAnnotations);
        }
        // If a class has no decorators, at least create metadata
        // based on function.length.
        // Note: We know that this is a real constructor as we checked
        // the content of the constructor above.
        return new Array(type.length).fill(undefined);
    };`

**Comment by atdiff** [comment]
@matsko I'm getting the same error in IE - "Object doesn't support property or method 'fill'".  The line it's failing on is 
`var HEADER_FILLER = new Array(HEADER_OFFSET).fill(null);`
which is a part of angular/core.

**Comment by seorefbe** [comment]
Hello @ajborn , @atdiff 

I had the same error but apparently angular planned that.

In `src/polyfill.ts` you just have to uncomment `// import 'core-js/es6/array';` (line 29 for me).

In my case i had to uncomment too `import 'core-js/es6/string';` to fix other ie error with "`startWith`"

Global based on the staff that you use, you have to uncomment the required polyfill.

**Comment by dev-assassin** [comment]
When I run the angular project on Chrome, it works well.
(Angular CLI - 6.1.1, Node- 10.5.0, NPM - 6.1.0)
But when I run this project on IE11, I get the following error and it doesn't work for me.
```
SCRIPT438: Object doesn't support property or method 'fill'
vendor.js (44438,1)
```
In that case, how can I run this on IE?
please teach any suggestions.

**Comment by seorefbe** [comment]
Hi @dev-assassin,

In src/polyfill.ts you just have to uncomment // import 'core-js/es6/array'; (line 29 for me).

**Comment by jayeshchheda14** [comment]
it worked after un-commenting 

import 'core-js/es6/string';
import 'core-js/es6/array';

**Comment by ChrisLeNeve** [comment]
Getting exactly the same issue as @atdiff. I haven't even started coding yet, this is the bare minimum as generated by "ng new projetname".

**Comment by gkalpak** [comment]
FYI: https://angular.io/guide/browser-support#polyfills

**Comment by ranouf** [comment]
Hi,

Do you know why when I build it the fix stop to work?
Here is my polyfill.ts:

> /**
>  * This file includes polyfills needed by Angular and is loaded before the app.
>  * You can add your own extra polyfills to this file.
>  *
>  * This file is divided into 2 sections:
>  *   1. Browser polyfills. These are applied before loading ZoneJS and are sorted by browsers.
>  *   2. Application imports. Files imported after ZoneJS that should be loaded before your main
>  *      file.
>  *
>  * The current setup is for so-called "evergreen" browsers; the last versions of browsers that
>  * automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),
>  * Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.
>  *
>  * Learn more in https://angular.io/docs/ts/latest/guide/browser-support.html
>  */
> 
> /***************************************************************************************************
>  * BROWSER POLYFILLS
>  */
> 
> /** IE9, IE10 and IE11 requires all of the following polyfills. **/
> import 'core-js/es6/symbol';
> import 'core-js/es6/object';
> import 'core-js/es6/function';
> import 'core-js/es6/parse-int';
> import 'core-js/es6/parse-float';
> import 'core-js/es6/number';
> import 'core-js/es6/math';
> import 'core-js/es6/string';
> import 'core-js/es6/date';
> import 'core-js/es6/array';
> import 'core-js/es6/regexp';
> import 'core-js/es6/map';
> import 'core-js/es6/weak-map';
> import 'core-js/es6/set';
> 
> /** IE10 and IE11 requires the following for NgClass support on SVG elements */
> import 'classlist.js';  // Run `npm install --save classlist.js`.
> 
> /** IE10 and IE11 requires the following for the Reflect API. */
> import 'core-js/es6/reflect';
> 
> 
> /** Evergreen browsers require these. **/
> // Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
> import 'core-js/es7/reflect';
> 
> 
> /**
>  * Required to support Web Animations `@angular/platform-browser/animations`.
>  * Needed for: All but Chrome, Firefox and Opera. http://caniuse.com/#feat=web-animation
>  **/
> import 'web-animations-js';  // Run `npm install --save web-animations-js`.
> 
> 
> 
> /***************************************************************************************************
>  * Zone JS is required by default for Angular itself.
>  */
> import 'zone.js/dist/zone';  // Included with Angular CLI.
> 
> 
> 
> /***************************************************************************************************
>  * APPLICATION IMPORTS
>  */
> import 'core-js/fn/array/fill';
> import 'core-js/es7/array';
>

**Comment by gkalpak** [comment]
No idea :grin: I would create a **minimal**, standalone reproduction (e.g. a repo one can checkout and investigate) and ask on StackOverflow or Gitter.
If it turns out there is a bug in Angular or the Angular cli (which I doubt), please reports an issue.
