### ISSUE TITLE
Fetching of ngsw.json Contradicts the Ngnix Configuration in Angular documentation 

### ISSUE THREAD

**Issue by arangates** [angular/angular#24932]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue 
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Angular documentation recommends to use 
```
try_files $uri $uri/ /index.html;
```
in Nginx Configuration which will redirect all the links with Query strings to index.html.
Refer : https://angular.io/guide/deployment#production-servers
but you can see fetchLatestManifest function here https://github.com/angular/angular/blob/0b4d85e9f19246af68a75140afc4db3d97f9ddfd/packages/service-worker/worker/src/driver.ts#L647
makes Http GET request with Query Param `ngsw-cache-bust` like
 https://example.com/ngsw.json?ngsw-cache-bust=0.24039143891136616 which indeed will respond with `index.html` rather than expected `ngsw.json` in response.

## Minimal reproduction of the problem with instructions

Have the following Nginx configuration as recommended in Documentation
```
    server {
      index index.html;
      root /dist;
      listen 80;
      location / {
        try_files $uri $uri/ /index.html;
      }
  }
```
Service worker wont cache any assests,because `ngsw.json` is not received correctly.

## What is the motivation / use case for changing the behavior?

As a result of not fetching `ngsw.json` correctly , no caching is possible , though the service worker is installed and running.This renders whole service worker unusable.

## Environment

<pre><code>
Angular version: 6.0.0

**Comment by gkalpak** [comment]
The nginx docs don't make this very clear, but `$uri` (which is an alias for [$document_uri][1]) does not include the query string (aka arguments), unlike [$request_uri][2] which does.

Closing, since everything works as expected.

[1]: http://nginx.org/en/docs/http/ngx_http_core_module.html#var_document_uri
[2]: http://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_uri

**Comment by jsanta** [comment]
Late response, faced the same issue: https://github.com/angular/angular/issues/24857#issuecomment-483009058
