### ISSUE TITLE
am facing issue while cross component communication

### ISSUE THREAD

**Issue by sureshkuma** [angular/angular#24934]
RecipeDetailComponent.html:8 ERROR TypeError: Cannot read property 'name' of undefined
    at Object.eval [as updateRenderer] (RecipeDetailComponent.html:8)
    at Object.debugUpdateRenderer [as updateRenderer] (core.js:10879)
    at checkAndUpdateView (core.js:10255)
    at callViewAction (core.js:10491)
    at execComponentViewsAction (core.js:10433)
    at checkAndUpdateView (core.js:10256)
    at callViewAction (core.js:10491)
    at execComponentViewsAction (core.js:10433)
    at checkAndUpdateView (core.js:10256)
    at callViewAction (core.js:10491)

Recipescomponent is parent component and its  having two child components recipedetail and recipe list
Recipes ------->1.RecipeDetail
           --------->2.RecipeList
Under RecipeList is having one more child component.
RecipeList------>1.Reccipe -item component

now i want to sent data from Recipe-item component to recipe detail component.
In recipe service am using the Event emitter with property in central place in service , and i emitted the data in recipe-item while subscribe() the data in Recipes that is parent component to all, in Recipes component.html am passing that recipe data way property binding but it will showing the error as mentioned above Can you help guys am working on this issue from last three days am not able getting the solution for this issue.

here my code samples:
Recipe_item.component.ts:------->
import { Component, OnInit, Input } from '@angular/core';
import { Recipe } from '../../recipe.model';
import {RecipeService} from '../../recipe.service';
import {Router, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-recipe-item',
  templateUrl: './recipe-item.component.html',
  styleUrls: ['./recipe-item.component.css']

})
export class RecipeItemComponent implements OnInit {
  // tslint:disable-next-line:no-trailing-whitespace
  
  @Input() selrecp: Recipe ;

  constructor(private recipeService: RecipeService) { }
  ngOnInit() {
  }

  onrecipeselt() {

 this.recipeService.recipeselected.next(this.selrecp);

  }
}
Recipe-Service.ts:----->
import { Recipe } from '../../app/recipes/recipe.model';
import { EventEmitter, Output } from '@angular/core';
import { Subject } from 'rxjs';
import { Ingredient } from '../Shared/Ingredient.model';

export class RecipeService {
   recipeselected = new Subject<Recipe>();
   public recipes: Recipe [] = [
        // tslint:disable:max-line-length
        new Recipe('A Test Server',  'https://upload.wikimedia.org/wikipedia/commons/7/72/Schnitzel.JPG', 'its really taste is good',
        [new Ingredient('meat', '2'),
      new Ingredient('chicken', '2')]),
        new Recipe(' Simply Server', 'https://upload.wikimedia.org/wikipedia/commons/7/72/Schnitzel.JPG' , 'its really taste is good', [new Ingredient('meat', '2'),
        new Ingredient('chicken', '2')]),
        new Recipe(' Routine Server',  'https://upload.wikimedia.org/wikipedia/commons/7/72/Schnitzel.JPG', 'its really taste is good', [new Ingredient('meat', '2'),
        new Ingredient('chicken', '2')]),
        new Recipe('Test Server', 'https://upload.wikimedia.org/wikipedia/commons/7/72/Schnitzel.JPG', 'its really taste is good', [new Ingredient('meat', '2'),
        new Ingredient('chicken', '2')]),
          ];

getRecipes() {
    return this.recipes.slice();
}
GetrecipesbyId(index: number) {

}

}
Recipes-Component.ts:--------->

import { Component, OnInit, Output} from '@angular/core';
import { RecipeService } from './recipe.service';
import { Recipe } from './recipe.model';
import { Data } from '@angular/router';

@Component({
  selector: 'app-recipes',
  templateUrl: './recipes.component.html',
  styleUrls: ['./recipes.component.css'],
  providers: [RecipeService]
})
export class RecipesComponent implements OnInit {
 srecipe: Recipe;
  constructor( private recipeService: RecipeService) { }

  ngOnInit() {
       this.recipeService.recipeselected.subscribe(
         (recipe: Recipe) => {
          this.srecipe = recipe;
         }
       );

    }
}
 
Recipes-component.html:---->
<div class="row">
<div class="col-sm-5">
  <app-recipe-list></app-recipe-list>
</div>
<div class="col-sm-7">
    <app-recipe-detail [recipe]="srecipe"></app-recipe-detail>
</div>
 
</div>

Recipe-detail.component.ts:---->
import { Component, OnInit, Input } from '@angular/core';
import { Recipe } from '../recipe.model';
import { RecipeService } from '../recipe.service';

@Component({
  selector: 'app-recipe-detail',
  templateUrl: './recipe-detail.component.html',
  styleUrls: ['./recipe-detail.component.css']
})
export class RecipeDetailComponent implements OnInit {

 @Input() recipe: Recipe;

  constructor() {
   }

  ngOnInit() {
}
}

**Comment by mlc-mlapis** [comment]
@sureshkuma ... lol, ... simplify your problem to just a really simplest online reproduction ... as simple as possible and then it could have a sense. Now nobody takes a look on it.

**Comment by manklu** [comment]
At least use a service like http://plnkr.co/ to have a complete sample that is directly executable.

**Comment by matsko** [comment]
@sureshkuma when creating issues please follow the issue creation template. This way someone from the team can respond properly. Thank you.
