### ISSUE TITLE
Angular DOM manipulation.

### ISSUE THREAD

**Issue by ramkrishna70** [angular/angular#24948]
Hi All,
I am printing some data with ngFor inside html, and it's working good.
I want to insert a new element inside ngFor, at a specific index, by putting condition inside .ts file checking the dom with ngAfterViewChecked() method.
I am able to insert the new element, but it puts after first element not on a specific index. I am sharing the code snippet here, please help me fixing it.
**home.html**
```
  <div *ngFor="let i of items" #test >
  	<div>{{i.name}}</div>
  </div>
  <div (tap)="add_more()">Add More</div>
```
**home.ts**
```
import { Component,ViewChild, ViewChildren,ElementRef, QueryList, Directive,Renderer2, Input, AfterViewInit,AfterViewChecked,ViewContainerRef , ComponentFactoryResolver} from '@angular/core';

@Component({
  selector: 'dynamic-component',
  template: `<div>I'm dynamically attached</div>`
})
export class DynamicComponent {}


@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})

export class HomePage implements AfterViewInit,AfterViewChecked{ 
    @Input() additionalColumn: DynamicComponent;
	@ViewChildren('test', {read: ViewContainerRef}) test: ViewContainerRef; 
	@ViewChild('test', {read: ViewContainerRef}) test1: ViewContainerRef;
	@ViewChildren('test') test2: QueryList<any>;
	private items:any = [];
	private count:number = undefined; 
	private indexes:Array<number> =  [10, 15,20,25,30];
  constructor(public navCtrl: NavController, 
  	private componentFactoryResolver: ComponentFactoryResolver, 
  	private viewContainerRef: ViewContainerRef, private elRef:ElementRef) {
  	this.items = [
  		{
  			"name":"Test1"
  		},{
  			"name":"Test2"
  		},{
  			"name":"Test3"
  		},{
  			"name":"Test4"
  		},{
  			"name":"Test5"
  		}
  	];
  	this.count = this.items.length;
  }

  ngAfterViewInit() { 
  	console.log("View init");
  	console.log(new Date().getMilliseconds());
  	console.log("&&&&&&&&&&&&&&&&&")
  	console.log(this.test2);
  	console.log(this.test2.length);
  	let firstEl = this.test2.first;
	let lastEl = this.test2.last;
	let data = this.test2.toArray();
	console.log(data);
	console.log(firstEl);
	console.log(lastEl.nativeElement);
	let temp = lastEl;
	temp.nativeElement = '<div><div>Hello</div></div>';
	console.log(temp);
	this.test2.reset([this.test2.toArray(), temp]);
	console.log(this.test2);

  } 

  ngAfterViewChecked() { 
  	console.log("Vew check");
  	console.log("*****************", new Date().getMilliseconds()); 
  	if (!(this.indexes.indexOf(this.test.length) < 0)) { 
  		let factory = this.componentFactoryResolver.resolveComponentFactory(DynamicComponent);
  		let ref = this.test1.createComponent(factory, this.test.length-1);  
  		
  		//createComponent


  		//console.log(this.test.insert(this.ac, this.test.length-1));
  		// alert("Need to insert at this index." + this.test.length);
  	}
  	console.log("Element Count + " + this.test.length);
  }
  add_more() {
  	//this.count += this.count;
  	this.items.push({"name": "Test Click" + ++this.count});
  }
}
```
If I have not approached the correct method, please suggest me.
Thanks

**Comment by mlc-mlapis** [comment]
@ramkrishna70 ... the idea to mutate DOM which is directly managed by Angular API `*ngFor` directive is simply not a good idea. If you change `items` (by pushing a new element) the `*ngFor` should render it ... `trackBy` is supposed to use to allow `*ngFor` to work smart enough (it means to not remove all elements from DOM and that insert them again but insert only a new one).

**Comment by mlc-mlapis** [comment]
@ramkrishna70 ... if you are binding to them in the rest of the code, sure.

**Comment by ramkrishna70** [comment]
Is it possible with DOM manipulation?

**Comment by mlc-mlapis** [comment]
@ramkrishna70 ... hmm, the problem is that I don't understand what is your goal ... what do you want to reach in the end.

**Comment by mlc-mlapis** [comment]
@ramkrishna70 ... hmm, you are going totally in a wrong way ... don't even think by that way ... 😄 You probably have to create your own structural directive as `*myNgFor` which will do it for you or use a component that is able to accept all different JSON elements or use separate `<ng-template>` for each unique data structure of a JSON element, ... the idea is like a grid component where each cell uses its own template `ng-template`, like AgGrid ... https://github.com/ag-grid/ag-grid is doing.

**Comment by ramkrishna70** [comment]
Sorry, I got the fix after long try, in existing code need to modify only this section 
```
if (!(this.indexes.indexOf(this.test.length) < 0)) {
  			let factory = this.componentFactoryResolver.resolveComponentFactory(DynamicComponent); 
  			let ref = this.test.toArray()[this.test.length-1].createComponent(factory);  
  		
  			//createComponent


  			//console.log(this.test.insert(this.ac, this.test.length-1));
  			// alert("Need to insert at this index." + this.test.length);
  		}
  		console.log("Element Count + " + this.test.length);
  	}
```

**Comment by mlc-mlapis** [comment]
@ramkrishna70 ... lol, I totally missed that you are using dynamic way of creating the components via `resolveComponentFactory` probably because of the length of code on the beginning. But still not sure how `DynamicComponent` renders such totally different JSON data structure for each element in that array.
