### ISSUE TITLE
the image path is wrong 

### ISSUE THREAD

**Issue by austzyl** [angular/angular#24950]
Hi 
I'm using Lazy loading,A component references B component.  B's image can not visited in A and show 404 error.
index.html:
`<base href="/project/front/">
`
image in B:http://ip:port/project/front/assets/images/node/nr_server.png ----- can visited 
B in A:http://ip:port/project/front/A/assets/images/node/nr_server.png  -------404

related routers like this:
{
    path: 'B',
    loadChildren: './B/B.module#BModule',
    data: {preload: true}
  },
  {
    path: 'A',
    loadChildren: './A/A.module#AModule',
    data: {preload: false}
  }

why A component visit B component,B's image path has '../A/..' ?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
