### ISSUE TITLE
Why not use types for route parameters?

### ISSUE THREAD

**Issue by simonferndriger** [angular/angular#24955]
I'm just going through the Angular tutorial and am at [7. Routing](https://angular.io/tutorial/toh-pt5).
There is this line of code which just jumped right at me:

`const id = +this.route.snapshot.paramMap.get('id');`

They "hack" the string parameter to a number with the "+" sign which I cannot understand, since everything else is just so beautifully typed (with TYPEScript). Why not extend `get()` with the type, for example like this:  `get('id', type.Number)` ?

**Comment by smnbbrv** [comment]
Please check [ngx-typed-router](https://github.com/smnbbrv/ngx-typed-router). It aims to provide you with all the types.

Map-like parameters cannot be supported, so only normal `params`, `queryParams` and `data` are covered.

**Comment by wtjerry** [comment]
I have no JS background, so i also stumbled on the '+' operator. 
Perhaps a more explicit style would make it more readable, like:
``` Javascript
const id = Number(this.route.snapshot.paramMap.get('id'));
```

**Comment by Flyrell** [comment]
I agree that it should be possible to specify the type of router's data as router now carries the resolver's data. It would probably catch some bugs and remove the need to cast the type when developers try to handle it. 

Right now, to prevent some bugs or just to get the intellisense, we'd do something similar to:

```typescript
interface CustomRouteData {
  users: User[];
}

// ...
ngOnInit(): void {
  (this.router.data as Observable<CustomRouteData>).pipe(/* ... */).subscribe(/* ... */);
}
```

This still has some pitfalls. For example, when you add/remove a resolver in route's definition, you need to alter the type inside your component. Also, someone can just cast the route's data to something totally different.

**Comment by smnbbrv** [comment]
@Flyrell see https://github.com/angular/angular/issues/24955#issuecomment-441603218 . It covers the cases you describe

**Comment by Flyrell** [comment]
@smnbbrv Yeah, I already use the typed router. It's very useful, so thanks for the library. Either way, I still think this should be a "native" thing. Just because developers don't need to rely on the library gets updated when the new version is published etc. It just feels better 😄

**Comment by smnbbrv** [comment]
That’s totally true. I would be happy to have this natively as well. Problem is that it doesn’t look to be on the scope of angular team anyhow...
