### ISSUE TITLE
API call twice

### ISSUE THREAD

**Issue by pratiraksha11** [angular/angular#24953]
I'm trying to hit API request:

export class ActivateUserComponent implements OnInit {

  public message:string;
  private baseURL = server_conf.host;
 
  constructor(private route: ActivatedRoute, private user: UserService, private http: HttpClient) { }

  ngOnInit() {
    const id = this.route.snapshot.paramMap.get('id');

    if(id){
        // const httpOptions = {
        //   headers: new HttpHeaders({ 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': server_conf.server })
        // };
        this.http.get(this.baseURL + 'activate-account/' + id).subscribe((result:any) => {
          this.message = result.message;
        });  
      
    }
  }

But I got two different response one for success and another for error message .

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
