### ISSUE TITLE
invoking a service before oninit on a component

### ISSUE THREAD

**Issue by Shubhangi-yadav** [angular/angular#24951]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I want values to initialize values in an object through invoking a service but by onintit initially null values are being generated .How to basically invoke a service and set values in a component before oninit??

## Expected behavior

I want to use a mat-select attribute with setting values from a service . But unable to generate so in first click . It generates later on after 1 cycle .

## Minimal reproduction of the problem with instructions

The problem exists with the home component and report component of the attached file. I want to get the selected reports while clicking on home component button but unable to do so. Please suggest  a method to do so.

## Environment

<pre><code>
Angular version: 6.0.8

Browser:
- [ ] Chrome (desktop) version 67.0.3396.99
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX   8.11.2
- Platform:  Windows 10
[src.zip](https://github.com/angular/angular/files/2204997/src.zip)

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@Shubhangi-yadav ... it probably leads to a provider defined in `providers: []` metadata directly on a component level.

**Comment by Shubhangi-yadav** [comment]
But still the ngOinit function is implemented first than invoking the service . Please provide a way to initialize 2 d array in a component using a service before ngOninit is invoked.

**Comment by mlc-mlapis** [comment]
@Shubhangi-yadav ... no, all dependency providers are resolved first ... and any code in a component can reference to any theirs properties or methods.

**Comment by Shubhangi-yadav** [comment]
So should i include import a component and change its value on clicking the first button .

**Comment by mlc-mlapis** [comment]
@Shubhangi-yadav ... what do you mean `should i include import a component`? To that provider? No, reverse ... that provider is injected to that component.

**Comment by manklu** [comment]
@Shubhangi-yadav
Maybe you should have a look at chapter 6 of the Angular tutorial.

https://angular.io/tutorial/toh-pt4

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
