### ISSUE TITLE
canActivate() guard is reading the initial value on the first click instead of the real one

### ISSUE THREAD

**Issue by alim90** [angular/angular#24952]
I am setting a variable as false at the beginning of the class:

```
export class AuthApiService {
  public loggedIn:boolean=false;
  //public loggedIn: boolean;

  constructor( private http: HttpClient) {  }

checkLoggedInAdmin()
  {
    //Get the JWT token from local storage
    let jwt = localStorage.getItem('jwt');
    let httpParams = new HttpParams().set('jwt', jwt);
    let headerOptions = new HttpHeaders();
    headerOptions.append('Content-Type', 'application/x-www-form-urlencoded; charset=UTF-8');
    if(jwt!="" || jwt!=null)
    {
      
      this.http.post('http://dev.local/scripts/checkLoginAdmin.php', httpParams, {
        headers: headerOptions
      })
      .subscribe(
        (data)=>{
          //console.log(data)
          if(data==true){
            this.loggedIn = true;
            //console.log(this.loggedIn);
            //return this.loggedIn = true;
            
          }
          if(data==false){
            this.loggedIn = false;
            //return this.loggedIn = false;
          }
        },
        (error)=>{
          console.log('Error '+error);
          this.loggedIn = false;
          //return this.loggedIn = false;
        }

      )
    }
    else
    {
      this.loggedIn = false;
      //return this.loggedIn;
    }
    this.checkIsLogin()
    {
      console.log('Check checkIsLogin() '+this.loggedIn)
    }
    return this.loggedIn;
  }

  checkIsLogin(){
    return this.loggedIn
  }
```

And I reuse it in the checkLoginAdmin() to see if the user is already logged in and is admin, and change it to true.

And then I need to return to a canActivate() guard to give the admin access to a component on button click:

```

import { Injectable } from '@angular/core';
import { CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot, Router } from '@angular/router';
import { Observable, of } from 'rxjs';
import { AuthApiService } from './auth-api.service';
@Injectable({
  providedIn: 'root'
})
export class AuthGuardService implements CanActivate {
  
  constructor(private router: Router, private authApi: AuthApiService) { }

  canActivate(_route: ActivatedRouteSnapshot, 
              _state: RouterStateSnapshot) : Observable<boolean> | Promise<boolean> | boolean
  { 
    console.log('test guard '+this.authApi.checkLoggedInAdmin());

    
    if(this.authApi.checkLoggedInAdmin())
    {
      return true;
    }
    else
    {
      //return false;
      this.router.navigate(['/login.'])
    }
  }

  
}

```

The problem is, when a user admin logged in, and then click on the desired component, he don't get an access from the first time as the result returned is false (which is wrong), then after the second click, it will transform into `true` and then he can access the component.

On SO told me that's because I am not returning an observable.

**Comment by hisorange** [comment]
checkLoggedInAdmin makes an async request and the observable updates a "sync" variable, so when you click the second time the information is arrived, but your AuthGuardService running like a synchronous process.

To solve it, you have to return either a promise or on observable wfrom the checkLoggedInAdmin and wait its result in the canActivate call, lucky you! Because the canActivate can return with boolean | Promise<boolean> | Observable<boolean> so it's easy from there. ^.^

**Comment by alim90** [comment]
@hisorange thanks. I noticed that during my research. But wasn't able to solve it. Can you help me more with some codes ?

**Comment by hisorange** [comment]
@alim90 Read [this](https://netbasal.com/angular-2-persist-your-login-status-with-behaviorsubject-45da9ec43243), this is based on your idea.

**Comment by alim90** [comment]
@hisorange I think a moderator should close it as I am not able to find the button. Thanks for the help anyway.
