### ISSUE TITLE
"keyup" or "input" best practice for autocomplete input field?

### ISSUE THREAD

**Issue by simonferndriger** [angular/angular#24960]
In the https://angular.io/tutorial/toh-pt6#search-by-name tutorial, for the input field, the event "keyup" is used in the example: `<input #searchBox id="search-box" (keyup)="search(searchBox.value)" />` 

But wouldn't it be a better (best) practice to use the "input" event instead? Such that the input field also reacts on copy/paste via mouse for example?

**Comment by codermarcos** [comment]
I think it was an example only for didactic purposes

**Comment by simonferndriger** [comment]
Yes, that is true for sure. But why not lead with a _good_ example? Chances are high, that this practice will influence future developments.

**Comment by chembu** [comment]
Current document uses the input event.

**Comment by simonferndriger** [comment]
Great, thank you!

**Comment by jenniferfell** [comment]
Resolved by https://github.com/angular/angular/pull/26440
