### ISSUE TITLE
feat: Pattern Matching directive for templates

### ISSUE THREAD

**Issue by michaeljota** [angular/angular#24961]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Background

**Current Angular Directives**:
- [*ngIf](https://angular.io/api/common/NgIf)
- [*ngSwitch](https://angular.io/api/common/NgSwitch)

**TC39 Proposal**
- [Pattern Matching](https://github.com/tc39/proposal-pattern-matching)

---

Currently we have some Angular directives that help us to create conditional and dynamic templates. There is also a proposal to add into the language Pattern Matching syntax, to be able to use it. 

## Proposed behavior

I would like a directive that imitates the behavior of the pattern matching proposal.

- `[ngMatch]`: Like `ngSwitch`, but would pass an object in which certain pattern will be matched.
- `*ngMatchWhen`: 
  - `@Input() ngMatchWhen`: A single key string, or an array of key strings.
  - `@Input() ngMatchWhenEquals`: A single value, or an array of values.
  - _Context_: Context of the template, will be giving return the same object given to `ngMatch`.
  - This directive will check for any of the key strings given if they exist in the object given to a parent `ngMatch`. If they do exist, and a value was provided, then this will check if the values also are the same. If they do exist and the value is the same or there was no value giving, the template is created. Else, is destroyed.

---

- Giving the component class:
```ts
class ResponseComponent {
  response: SuccessResponse | FailureResponse
}

type SuccessResponse {
  data: unknown;
}

type FailureResponse {
  error: true;
  reason: string;
}
```

- Possibles templates with `ngMatch`:

```html
<ng-container [ngMatch]="response">
  <ng-container *ngMatchWhen="'data'">
    <pre>
      {{ data | json }}
    </pre>
  </ng-container>
  <ng-container *ngMatchWhen="'error'; equals: true, let reason = reason">
    <div class="error">
      {{ reason }}
    </div>
  </ng-container>
</ng-container>
```

- Semantic 

```html
<element [ngMatch]="object"> </element>
<!--          Assignment^          -->
```
```html
<element *ngMatchWhen="'key'; equals: value; if: condition; let variable = context"> </element>
<!--         Assignment^    ;  ^Assignment ; ^Assignment  ;    ^Declaration        --> 
```

- Example project

https://stackblitz.com/edit/angular-match-directive

## What is the motivation / use case for changing the behavior?

This would allow us to have a even more powerful template syntax to work with and handle more complex templates easily.

I know that pattern matching can be somehow done with current syntax, but I fell this would allow to express the intention of the template more clearly, for all the team. 

## Environment

<pre><code>
Angular version: 6.x

 
For Tooling issues:
- Node version: XX   8.11.2
- Platform:   Windows 10 Abril 2018 Update

Others:

</code></pre>

**Comment by trotyl** [comment]
Not feasible via directive, `MatchPattern` is not kind of `Expression`, but new syntax, thus not compatible with template expression.

**Comment by michaeljota** [comment]
I think that the matching pattern itself can be implemented using current syntax, without needed the proposal to be implemented. As I said, even with current directives something like this is doable, but with the proper directive syntax it would be so much better to develop and express the intention about the template.

**Comment by trotyl** [comment]
A directive can only have API, not syntax. If you're proposing syntax, then defining its semantics. Also they'll be not related to any directive.

**Comment by michaeljota** [comment]
I may have miswriting.

What I mean with _current syntax_ is implement the API of the directive using current ES, not the implementation of the proposal, thus this wouldn't need to wait until the proposal have been implement in every supported browser. 

What I mean with _proper directive syntax_ is the _syntax_ used by the API.
```html
<ng-container [ngMatch]="response">
  <ng-container *ngMatchWhen="{ data }">
    <pre>
      {{ data | json }}
    </pre>
  </ng-container>
  <ng-container *ngMatchWhen="{ error: true, reason }">
    <div class="error">
      {{ reason }}
    </div>
  </ng-container>
</ng-container>
```

This can be currently done by something like this:

```html
<!-- Using ngSwitch -->
<ng-container [ngSwitch]="true">
  <ng-container *ngSwitchCase="!!response.data">
    <pre>
      {{ response.data | json }}
    </pre>
  </ng-container>
  <ng-container *ngSwitchCase="response.error">
    <div class="error">
      {{ response.reason }}
    </div>
  </ng-container>
</ng-container>

<!-- Using ngIf -->
<ng-container *ngIf="response.data">
  <pre>
    {{ response.data | json }}
  </pre>
</ng-container>
<ng-container *ngIf="response.error">
  <div class="error">
    {{ response.reason }}
  </div>
</ng-container>
```

However, you can notice that using `ngMatch` the template express better the wanted behavior, and it's less confuse.

This is a really simple use case, but with more complex scenarios the usage of `ngMatch` would be invaluable.

**Comment by trotyl** [comment]
The syntax of:

```html
<element *ngMatchWhen="{ data }">Some Content</element>
```

Which already has the meaning:

```html
<ng-template [ngMatchWhen]="{ data }">
  <element>Some Content</element>
</ng-template>
```

And `{ data }` is a normal ES2015 object shorthand expression, need to be parsed to `{ data: context.data }`, and will be evaluate again `data` property on the specific component.

Can be expressed as:

```typescript
const context = component;
const template = createTemplate({ ngMatchWhen: { data: context.data } });
// ...
```

That's the semantics of this syntax.

If you have any proposal about new syntax, then describe what the syntax is and what's the semantic of it.

**Comment by trotyl** [comment]
The `<ng-container [ngMatch]="response">` is an early error, an `ng-container` pseudo element cannot have any directive thus no inputs are allowed (not even for proposal).

It can only be `<ng-container *ngMatch="response">` or `<element [ngMatch]="response">`.

The current * micro-syntax is (informative):

```
AttributeValue = Expression SP* [;] SP* ((Assignment / KeyValuePair) SP* [;])*
AttributeValue =/ Assignment SP* [;] SP* ((Assignment / KeyValuePair) SP* [;])*
Assignment = "let" SP* IdentifierName SP* ["=" SP* Expression
KeyValuePair = IdentifierName SP* ":" SP* Expression
```

No matter you proposed `{ data }` / `{ error: true, reason }` or `data` / `error=true; reason` to be the syntax, they're still not distinguishable with `Expression`. So the syntax it not possible to be used.

And what should the sematic be? If used for pattern matching, then no evaluation should be performed, likely results to sequence of key-value pairs such as `[['data']]` / `[['error', true], ['reason']]`.

**Comment by trotyl** [comment]
> I'm currently using [ngSwitch]="" directive inside a ng-container element, so this is not true.

My mistake, sorry for that.

> *ngFor can be giving a list of values separated by coma

That’s just array literal **expression**.

> the object passed to the "match" directive will be evaluated, by the values given to the "when" directives, and the match of that operation will be showed.

I think I have made it clear that **semactic is not related to directive**.

**Comment by trotyl** [comment]
A directive would just read inputs, accept dependencies and take actions.

For example, a common `NgForOf` usage could be:

```html
<element *ngFor="let item of items$ | async as items; index as i"></element>
```

After ASI process it would become:

```html
<element *ngFor="let item; of: (items$ | async); as items; index as i"></element>
```

Which would be expanded to:

```html
<element *ngFor="let item = $implicit; of: (items$ | async); let items = ngForOf; let i = index"></element>
<!--             Declaration           Assignment            Declaration          Declaration           -->
```

The sematic of a `Declaration` is to declare a template variable:

```html
<element *dir="let name = prop"></element>
```

Would be translated to:

```html
<ng-template dir let-name="prop">
  <element></element>
</ng-template>
```

The sematic of a `Assignment` is to add a property binding:

```html
<element *dir="ignoreMe; key: value"></element>
```

Would be translated to:

```html
<ng-template [dir]="ignoreMe" [dirKey]="value">
  <element></element>
</ng-template>
```

So the combination above would results to:

```html
<ng-template ngFor let-item="$implicit" [ngForOf]="items$ | async" let-items="ngForOf" let-i="index">
  <element></element>
</ng-template>
```

So the `NgForOf` directive could now get the input of `ngForOf` and inject the `TemplateRef` dependency which has several context variable binding.

But you haven't expressed what's the sematic of your proposed syntax, it's not about the goal.

**Comment by michaeljota** [comment]
Thank you for explain this. I wasn't understanding your point. I'll update the proposal with some examples about what this should become for the AST then, thanks.

**Comment by michaeljota** [comment]
Hi @trotyl 

I updated the post, let me know if that is what mean. 

- Semantic

```html
<element [ngMatch]="object"> </element>
<!--          Assignment^          -->
```
```html
<element *ngMatchWhen="'key'; equals: value; if: condition; let variable = context"> </element>
<!--         Assignment^    ;  ^Assignment ; ^Assignment  ;    ^Declaration        --> 
```

**Comment by trotyl** [comment]
@michaelchiche I thought you were making a proposal about new template syntax? Seems there's no syntax proposal now but only library proposal?

**Comment by michaeljota** [comment]
I don't think I ever said I wanted a new template syntax, or that I was making a syntax proposal. As the title suggest I would like a new directive. However, I do mention a new syntax, but only to refer the current proposal to the TC39 to introduce to JS a pattern matching syntax.

I also notice that with the current syntax, that we had in Angular and in ES, this could be somehow implemented, but I think this would bring some benefits into libraries development.

**Comment by michaeljota** [comment]
Hi @trotyl 

I update the post with more context, and a little but usable example of the proposal. I hope this helps. Thanks you!

**Comment by trotyl** [comment]
If you just want to make a directive for pattern matching, then the API could be match easier, for example:

```html
<div [ngCase]="res">
  <p *ngCaseWhen="{status: 200, headers: {'Content-Length': '$0'}}; $0 as s">size is {{s}}</p>
  <p *ngCaseWhen="{status: 404}">JSON not found</p>
  <p *ngCaseWhen="{status: '$0'} if {$0: {$gte: 400}}">RequestError</p>
</div>
```

All you want here is to avoid eager evaluation of the expression, so for example [MongoDB query operators](https://docs.mongodb.com/manual/reference/operator/query/) can be used while this is still a normal expression.

Also, a directive won't make any difference in built-in or not, you're welcomed to provide your own library which contains this feature.

**Comment by michaeljota** [comment]
Does not Angular Language Service provides restrictions for the use of ngSwitch and ngSwitchCase?

**Comment by trotyl** [comment]
Angular language service doesn't have special treatment for any directive. So it's true for LS has restriction for directives, but nothing specific to `NgSwitch` or `NgSwitchCase`.

**Comment by Lonli-Lokli** [comment]
I also feel like implementing proposal will give more power for union data states. 
Ngif already have kind of this mechanism with type guard, https://github.com/angular/angular/blob/master/packages/common/src/directives/ng_if.ts#L235

So I think we just need more sugar for this, eg possibility to specify guards for particular type from union.

**Comment by jessicajaniuk** [comment]
This would be really cool, but we would prefer not to implement pattern matching within angular ourselves. Once the TC39 proposal moves beyond Stage 2 and into Stage 3, we can consider implementing the native version of pattern matching. In the meantime, we welcome third party directives.
