### ISSUE TITLE
Function ReflectionCapabilities.prototype._ownParameters fails in IE11

### ISSUE THREAD

**Issue by ajborn** [angular/angular#24970]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
table fails to load data in IE11
Error message SCRIPT438: Object doesn't support property or method 'fill'
Name of function: `ReflectionCapabilities.prototype._ownParameters`
Fails when function attempts to return `return new Array(type.length).fill(undefined);`
This function can be found in the angular.io repository.

## Expected behavior
Data should load in IE11

## Minimal reproduction of the problem with instructions
Filling a table 

## What is the motivation / use case for changing the behavior?
Need app to work in IE11

## Environment

Angular version: 6.0.7

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11
- Platform: Windows

Others:
The table being used is a pre build Angular Material table. Code fails from angular code so I do not believe it is related to the Angular Material MatTable.

**Comment by vicb** [comment]
Please add a repro

**Comment by ajborn** [comment]
.Net Core Angular 5 template does not use polyfills causing my issues in IE.

**Comment by mszkudelski** [comment]
@vicb I have the same issue but in other place in angular/core. It's in file core.js in line 17152 - "const HEADER_FILLER = new Array(HEADER_OFFSET).fill(null);". Would it be helpful? Unfortunately I cannot reproduce this error on new 'clean' project generate in CLI.

**Comment by alexandreolivepro** [comment]
@mszkudelski Same error here, Did you find any fix ?

**Comment by mszkudelski** [comment]
Hi @alexandreolivepro , no, I didn't... I hope that someone from Angular Team will anwer me. @vicb, maybe my comment above will tell you something.

**Comment by alexandreolivepro** [comment]
@mszkudelski After some tests, I found a temporary fix for the issue. I installed the polyfill through npm : `npm install array.prototype.fill` 
and added the index.js in the angular.json file, in the scripts section. 
`"scripts": [
              "node_modules/array.prototype.fill/index.js",
            ]`

My site is now working again in IE11. If this can help anyone.

**Comment by mszkudelski** [comment]
I think it works, because this error doesn't occurs anymore. Thank you, @alexandreolivepro !
