### ISSUE TITLE
document that namespaces are not supported in a directive's selector

### ISSUE THREAD

**Issue by yavulan** [angular/angular#24971]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Directive's selector has no colon support (while component’s selector handles colon properly).

```ts
@Directive({
  selector: '[ns:selector]'
})
```
```html
<span ns:selector></span>
```

Does not work at all and produce no errors.

At the same time selector without namespace (```selector: '[selector]'```) works with any namespace in markup. E.g., with ```<span ns:selector></span>```.

Also tried to use with XML mode https://www.w3.org/TR/html5-diff/#syntax but no success.

## Expected behavior

Colon-separated namespaces in Directive's selector recognized and processed properly.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-gitter-35fnah

## What is the motivation / use case for changing the behavior?

Use colon (XML namespaces) in Directive's selector and in a markup.

Proof of interest: question (not mine) https://stackoverflow.com/questions/39005486/angular-2-selector-with-namespace without an answer.

## Environment
<pre><code>
Angular version: 6.0.3

Browser:
- [x] Chrome (desktop) version 67
</code></pre>

**Comment by splincode** [comment]
It seems to me it is not implemented in the template compiler
@trotyl This is feature request?

**Comment by trotyl** [comment]
![image](https://user-images.githubusercontent.com/6059170/42934493-f0f34334-8b79-11e8-85d3-e7de45f66700.png)

The namespace attribute can never be queried like that. See https://stackoverflow.com/questions/23034283/is-it-possible-to-use-htmls-queryselector-to-select-by-xlink-attribute-in-an.

Possibly it's a valid feature request for matching namespace, but the repro case isn't valid anyway.

**Comment by yavulan** [comment]
Fixed repro to use ```selector: '[ns\\:selector]'```: https://stackblitz.com/edit/angular-gitter-4nmfwj

Please let me know if I should edit the initial message and change "Bug report " to "Feature request" and/or update repro link. Thank you.

**Comment by trotyl** [comment]
There're several concerns:

### 1. Namespace is never being supported as part of selector

https://github.com/angular/angular/blob/d76531d16eb57391a8ee4cf3375a550e72307b67/packages/compiler/src/selector.ts#L11-L21

If element selector works, that would just be an unexpected accident.

### 2. Lacking of supporting namespace should be documented

It's a known fact that directive selector is a subset of CSS selector, but the detail of **subsetting** should be well-documented.

### 3. Unsupported selector type should raise error

Current way of matching RegExp is too weak and tricky, there should be a selector parser and applying restricted rules.

See also https://github.com/angular/angular/issues/2589 & https://github.com/angular/angular/issues/6600.

### 4. Single-element selector should be supported

Even with namespace being part of the selector, it's still for single element and doesn't break any design, should be supported by Angular compiler.

---

It's actually not a big deal for marking it `bug` or `feature` for now, as the problem cannot be easily solved.

**Comment by trotyl** [comment]
@mhevery Given namespace is a valid part of element/attribute selector, why shouldn't it be supported?

**Comment by manklu** [comment]
@trotyl Two thoughts.

1. Namespaces are only allowed with XHTML.
1. It is a big bunch of work to do it correctly.

With namespaces implemented correctly, you would get something like this:

```javascript
@Directive({
  selector: '[http://example.org/QualifiedNamespace:selector]'
})
```
```xml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ns1="http://example.org/QualifiedNamespace">
  <head>
    <title>Title of document</title>
  </head>
  <body>
    <p>
      <span ns1:selector></span>
    </p>
  </body>
</html>
```

**Comment by trotyl** [comment]
@manklu I agree with your points, but given Directive is an enhancer of the elements, and namespaces are already supported in elements:

+ https://angular.io/api/core/Renderer2#createElement
+ https://angular.io/api/core/Renderer2#setAttribute

Then Angular should take the responsibility to make any element interceptable/spyable, it's for consistency.

**Comment by manklu** [comment]
@trotyl

> Namespaces are already well-handled anywhere else than selector in Angular framework.

An example please. I haven't seen any XML-Namespaces yet.

**Comment by trotyl** [comment]
@manklu You already got that from OP, just not use the Directive:

https://stackblitz.com/edit/angular-gitter-rpm9fk?file=app%2Fapp.component.ts

**Comment by trotyl** [comment]
@manklu I'm kind of agree with you now since namespace used in HTML-based documents wouldn't result a different an HTML structure:

![image](https://user-images.githubusercontent.com/6059170/43042098-bf4821b8-8da6-11e8-9475-cb891cf108f3.png)

So there's no difference in selector.

**Comment by jenniferfell** [comment]
One possible location for clarifying doc: https://angular.io/guide/attribute-directives

**Comment by s-gbz** [comment]
I'll add it to the docs 👍

**Comment by aikidave** [comment]
This issue, clarifying that directives do not support namespaces, has been addressed in the current version of this topic: https://angular.io/guide/attribute-directives. Closing!
