### ISSUE TITLE
https://angular.io/guide/reactive-forms shows empty page

### ISSUE THREAD

**Issue by ukrukarg** [angular/angular#24973]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

https://angular.io/guide/reactive-forms shows empty page and this in console:
```
[DocViewer]: Error preparing document 'guide/reactive-forms'. DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at t.extractHeadingSafeHtml (https://angular.io/main.634954f01b01be38505a.bundle.js:1:299121)
    at https://angular.io/main.634954f01b01be38505a.bundle.js:1:298593
```

## Expected behavior

Page should be shown.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by manklu** [comment]
Works for me without problems. Which browser did you use?

**Comment by ukrukarg** [comment]
Actually, now it also works for me. Guess all I had to do was complain :)

**Comment by krcourville** [comment]
I'm seeing this issue on several documentation pages using Chrome 68 on Mac.  Safari seems to work ok.

Some pages I've run across so far that exhibit this behavior:

* https://angular.io/guide/bootstrapping
* https://angular.io/guide/frequent-ngmodules
* https://angular.io/guide/singleton-services

The error in the console is:

```
ERROR [DocViewer] Error preparing document 'guide/singleton-services': Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at t.extractHeadingSafeHtml (https://angular.io/main.2ce174b314884f005f8b.bundle.js:1:264514)
    at https://angular.io/main.2ce174b314884f005f8b.bundle.js:1:263980
    at Array.map (<anonymous>)
    at t.genToc (https://angular.io/main.2ce174b314884f005f8b.bundle.js:1:263947)
    at https://angular.io/main.2ce174b314884f005f8b.bundle.js:1:307681
    at e._next (https://angular.io/main.2ce174b314884f005f8b.bundle.js:1:309978)
    at e.__tryOrSetError (https://angular.io/main.2ce174b314884f005f8b.bundle.js:1:52231)
    at e.next (https://angular.io/main.2ce174b314884f005f8b.bundle.js:1:51342)
    at e._next (https://angular.io/main.2ce174b314884f005f8b.bundle.js:1:50476)
    at e.next (https://angular.io/main.2ce174b314884f005f8b.bundle.js:1:50147)
```

**Comment by gkalpak** [comment]
Thx for the extra info, @krcourville. Interestingly, though, [extractHeadingSafeHtml()][1] does not contain any call to `removeChild()` 😕 
(Sounds like a Chrome bug.)

[1]: https://github.com/angular/angular/blob/d2be3d57759c93bd5f4a2b9df780a8a7f8e12c95/aio/src/app/shared/toc.service.ts#L56-L76

**Comment by yongzhi-chen** [comment]
from the chrome inspect the function extractHeadingSafeHtml clearly has removeChild function. I guess the bundle js is not using the latest version?
 
```
t.prototype.extractHeadingSafeHtml = function(t) {
                var e = this.document.createElement("a");
                e.innerHTML = t.innerHTML;
                var n = e.querySelector("a");
                return n && e.removeChild(n),
                this.domSanitizer.bypassSecurityTrustHtml(e.innerHTML.trim())
            }
```

**Comment by gkalpak** [comment]
This code is from before 12be31161. The current version uses different code.
How come you are getting that old version? I wonder if the SW was keeping you back to an old version.
(Fortunately, we are switching to the latest SW which should be more reliable: #25997)

**Comment by yongzhi-chen** [comment]
hmm it does seem like it. the service worker caches the entry html so Chrome was using the old main.js
