### ISSUE TITLE
Submitting a form by pressing enter in IE11 does not work with 2 or more inputs

### ISSUE THREAD

**Issue by shuhkla** [angular/angular#24984]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

NgSubmit directive does not work in IE 11 with 2 or more inputs when enter key has been pressed on an input. This works in any other browser (Chrome, FF etc.)

## Expected behavior
NgSubmit directive should work in IE 11 with 2 or more inputs.

## Minimal reproduction of the problem with instructions
I'm using Angular 6, but this should be reproducible in any ngx version.

TS:

  ```
  import { Component } from '@angular/core';
    
    @Component({
      selector: 'app-root',
      templateUrl: './app.component.html',
      styleUrls: ['./app.component.css']
    })
    export class AppComponent {
      title = 'app';
    
      public test(): void {
        alert('TEST');
      }
    }
```

Template:

```
<div style="text-align:center">
    <form class="form-horizontal" (ngSubmit)="test()"> 
        <input id="test1" name="what1" type="text" />
        <input id="test2" name="what2" type="text" />
        <input type="submit" name="what3" style="display: none"/> 
    </form>
</div>
```

On Chrome, you can submit the form normally by pressing enter on the input.

On IE 11, this will NOT let you submit the form by pressing enter on the input. However, as soon as I remove one of the inputs (say test2), then IE 11 lets you submit the form.

## What is the motivation / use case for changing the behavior?
Incoherent implementation of form submission. I don't see a reason why this shouldn't work in IE 11. Also doesn't make sense why this works with 1 input but it does not work with 2 or more.

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ X ] IE version 11
- [ ] Edge version XX

</code></pre>

**Comment by manklu** [comment]
IE11 Problem. I have prepared a native html sample without angular and it has the same problem.

https://js-s9scdt.stackblitz.io

**Comment by kara** [comment]
Yeah, it looks like the submit event isn't firing with 2+ inputs in IE11. Since this isn't an Angular issue, closing.
