### ISSUE TITLE
Date Pipe issue on IOS device but working fine on android

### ISSUE THREAD

**Issue by sachinsemlety** [angular/angular#24983]
## Angular DatePipe filter showing incorrect time on ios device i.e the current timestamp + 5 hours.
(don't know why adding 5 hours extra to the timestamp)

The below code is for formatting the date in android which is correct :
<pre><code>let datePipe = new DatePipe("en-US");
this.BOEDateTime = datePipe.transform(timestamp, "dd-MMM-yyyy HH:mm");
console.log("date ",this.BOEDateTime);  //12-Jan-2017 11:00
</code></pre>

## Current behavior for IOS

<pre><code>let datePipe = new DatePipe("en-US");
this.BOEDateTime = datePipe.transform(timestamp, "dd-MMM-yyyy HH:mm");
console.log("date ",this.BOEDateTime);  //12-Jan-2017 16:00 
</code></pre>

## Expected behavior

<pre><code>let datePipe = new DatePipe("en-US");
this.BOEDateTime = datePipe.transform(timestamp, "dd-MMM-yyyy HH:mm");
console.log("date ",this.BOEDateTime);  //12-Jan-2017 11:00
</code></pre>

## Environment

<pre><code>
Angular version: 5.2.10

Browser:
- [ ] Chrome (desktop) version latest
- [ ] Safari (desktop) version latest
- [ ] Safari (iOS) version latest

 
For Tooling issues:
- Node version: v8.11.2  
- Platform:  Mac & IOS

Others:
But when using momentjs it is working fine in android as well as on ios devices.

</code></pre>

**Comment by jainanuj0812** [comment]
Can you please generate this issue on stackblitz and share the link, so that we can look into it

**Comment by sarunint** [comment]
@sachinsemlety And please also state your timezone. Is it UTC+5 or UTC-5?

**Comment by manklu** [comment]
You have not specified the timezone. As result the timezone of the browser is used. Seems you use different ones on your devices.

See https://v5.angular.io/api/common/DatePipe for details.

**Comment by sachinsemlety** [comment]
I have create an issue in stackblitz please check this [link](https://stackblitz.com/edit/angular-1haadu?embed=1&file=src/app/hello.component.ts) 

also the the time is proper in windows browsers and android devices but not on mac or ios browsers like safari ,chrome etc

**Comment by sachinsemlety** [comment]
@sarunint it is adding UTC+5

**Comment by jainanuj0812** [comment]
Hi @sachinsemlety,

I have checked the link you shared and it is working fine for me on safari. Please share the output and the version of safari you are using.

**Comment by sachinsemlety** [comment]
I am using safari v11.1.2 browser on mac and also it is not working fine on ios devices. what is the issue?

**Comment by trotyl** [comment]
@sachinsemlety Check if your devices have different results on https://stackblitz.com/edit/angular-ycuq6r?file=src/app/hello.component.ts, it's using a fixed timezone. If not, then just your devices' problem.

**Comment by vicb** [comment]
Thanks @trotyl for the stackblitz.
@sachinsemlety could you please try on your devices ?

**Comment by vicb** [comment]
Closing as no feedback from @sachinsemlety - please open a new issue if you have feedback later on. Thanks.

**Comment by nemeek2017** [comment]
Hi, i can confirm it. In IOS DatePipe make not rendering the webpage

**Comment by apenachi** [comment]
Hello ... 
I'm using angular 5.1.0 As of now the DatePipe still does not work as expected.  Can some one shed some light in this issue and/or the status.
Thanks
