### ISSUE TITLE
Angular and typescript@2.9.2 Error 

### ISSUE THREAD

**Issue by vishalbedre** [angular/angular#24985]
Hi All, 

I created angular 6 application(node) and install typescript@2.9.2. Giving me error.

> @angular/compiler-cli@6.0.9 requires typescript@'>=2.7.0 <2.8.0' but 2.9.2 was found instead.
> Using this version can result in undefined behaviour and difficult to debug problems.
> 
> Please run the following command to install a compatible version of TypeScript.
> 
>     npm install typescript@'>=2.7.0 <2.8.0'
> 
> To disable this warning run "ng config cli.warnings.typescriptMismatch false".
ERROR in The Angular Compiler requires TypeScript >=2.7.2 and <2.8.0 but 2.9.2 was found instead.

**Comment by mlc-mlapis** [comment]
@vishalbedre ... Angular 6.1 will support TS 2.8 and 2.9.

**Comment by vishalbedre** [comment]
Is Angular 6.1 released?

**Comment by ericmartinezr** [comment]
Check the changelog https://github.com/angular/angular/blob/master/CHANGELOG.md

**Comment by pkozlowski-opensource** [comment]
Same as #24980

**Comment by SerkanSipahi** [comment]
everyone talks about angular v6.1 support typescript v2.9.2. My question: why angular-cli v6.1.2 still install typescript 2.7.2 on new project (ng new foo)? Do I have to install typescript v2.9.2 with angular 6.1.2 myself?
