### ISSUE TITLE
*ngIf behavior with img src attribute ( or any elements which caches data)

### ISSUE THREAD

**Issue by nutangwari** [angular/angular#24990]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I am adding *ngIf to "img" tag, and toggling the ngIf value.
`  <img [src]="url which generates random images" *ngIf="toggleView">`
   `<button (click)="toggleView = !toggleView"></button`

As i understood, ngIf removes element from the DOM, and hence when ngIf evaluates to falsy value, it removes the img element from the DOM, now when I toggle back to true value, it's bringing back the cached url instead of rendering fresh img element.

Note: I am expecting new network call to the img src url.
## Expected behavior
if *ngIf is falsy element should be removed from the DOM, and if later if *ngIf evaluates to be true, it should render the element again instead of cached element.

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by ctomczyk** [comment]
> Note: I am expecting new network call to the img src url.

Angular itself is not responsible for the action you requesting.

Add a random query string value to image URL, e.g. `?nocache=123456` where `123456` changes every time the `toggleView` is `true`.

**Comment by manklu** [comment]
Alternatively, you can ensure that the server sets appropriate caching headers for the image.

**Comment by nutangwari** [comment]
@ctomczyk : thanks, i added new Date().getTime() to randomize number.
i was confused with the DOM removal and insertion point, i thought once element removed from the DOM,  it will lose the cached information.

Though thanks for the help, its working now. Closing the thread,
