### ISSUE TITLE
Named routes not working as expected

### ISSUE THREAD

**Issue by fclmman** [angular/angular#25004]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
named route for subpages is not loaded
https://stackblitz.com/edit/angular-esjv9e?file=src%2Fapp%2Ffeature%2Ffeature.module.ts
in the example you can see that navigating to feature/b does not load BComponent to the panel named router outlet

## Expected behavior
when navigating to feature/b i expect to see BComponent loaded to both outlets

## Minimal reproduction of the problem with instructions
Here is link fully demonstrating the issue
https://stackblitz.com/edit/angular-esjv9e?file=src%2Fapp%2Ffeature%2Ffeature.module.ts

## Environment

<pre><code>
Angular version: 6.0.9

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by fclmman** [comment]
Can anyone provide a workaround to make it work as expected?

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
