### ISSUE TITLE
Error/warning when accidentally using `[attr.XXX]` syntax as a static host attribute

### ISSUE THREAD

**Issue by DevVersion** [angular/angular#25005]
## I'm submitting a...

<pre><code>
[X] Feature request
</code></pre>

## Current behavior

Currently if someone accidentally uses a static host attribute that includes the syntax of a bound attribute binding, the attribute will be just added, even though it can be assumed that this happened by accident.

e.g. 

```ts
@Component({
  ...
  host: {
    'role': 'grid', // Valid attribute
    'attr.aria-readonly': 'true' // Potential mistake?
  },
})
```

## Expected behavior

It would be nice if there would be some warning or error that makes people aware of the potential mistake.

## What is the motivation / use case for changing the behavior?

We actually ran into such an accident on Angular Material: https://github.com/angular/material2/pull/12275

<sup>Sorry for the title changes.. I wasn't really able to find a short and obvious title that does not confuse.</sup>

**Comment by trotyl** [comment]
Relates to or duplicate of https://github.com/angular/angular/issues/3425.

Also, the title says `[attr.XXX]`. However you didn't use `[attr.XXX]` but `attr.XXX`, if you used `[attr.XXX]` then result will still be correct.

**Comment by DevVersion** [comment]
@trotyl True, I messed up the title as you can see in the history. Though the issue should be pretty clear from the code example.

Let's close that issue in favor of #3425
