### ISSUE TITLE
It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened

### ISSUE THREAD

**Issue by indrakumarprajapat** [angular/angular#25000]
In angular 5 project, i am adding java script widget on a component. the widget loaded successfully, but i am getting error,

'Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened'

i already asked this question on stackoverflow, but no replied there, here is the link,
https://stackoverflow.com/questions/51424970/it-isnt-possible-to-write-into-a-document-from-an-asynchronously-loaded-externa

This is the code,

```
export class RprReportDetailComponent {

  constructor( ) {
    this.loadScript();
  }

  loadScript() {
    const dynamicScripts = ['../../../../assets/rprdatascript.js', '//www.narrpr.com/widgets/avm-widget/widget.ashx/script'];

    for (let i = 0; i < dynamicScripts.length; i++) {
    const node = document.createElement('script');
    node.src = dynamicScripts[i];
    node.type = 'text/javascript';
    node.charset = 'utf-8';
    node.async = false;
    document.getElementsByTagName('div')[0].appendChild(node);
    }
  }
}

```

I am not sure its angular issue or not, i found one solution here, but this not working in case of angular 5.

**Comment by robwormald** [comment]
This is not related to Angular.
