### ISSUE TITLE
WindowRef and DocumentRef classes

### ISSUE THREAD

**Issue by FDIM** [angular/angular#25003]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## What is the motivation / use case for changing the behavior?

Currently in each project if you want access to actual document or window instance you either have to:
- provide them in app module with a possibly string token and use `@Inject('window') window: Window` to get a reference
- use global value directly, but this doesn't work well with unit tests

How about having `WindowRef` and `DocumentRef` classes exported from `@angular/platform-browser` that provide `window` and `document` references in the browser module for easy access? They should just extend `Window` and `Document` interfaces available in typescript for proper type checking and autocomplete.

I am considering doing this locally in the project and decided to share here as it would be much nicer as a standard solution. 

Thoughts? I can prepare a PR and update docs

**Comment by vicb** [comment]
> I am considering doing this locally in the project and decided to share here as it would be much nicer as a standard solution.

That;s probably a good idea.
