### ISSUE TITLE
Variable value in html doesn't match the real value in component

### ISSUE THREAD

**Issue by longhuy322000** [angular/angular#25011]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The variable value in HTML doesn't match the real value in component. HTML shows the value slower than expected?

## Expected behavior

The variable value in HTML should match the value in component.

## Minimal reproduction of the problem with instructions

STEPS TO REPRODUCE BUG via https://stackblitz.com/edit/angular-datachannel:
1. Open inspect (development mode)
2. Click connect button
3. Type something in the message input and send.
4. The myMessage value in HTML is different from the value in app component.

## Environment

<pre><code>
Angular version: 6.0.8

Browser:
- [x] Chrome (desktop) version 67
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
Angular would only respond to tasks invoked inside Angular zone, but all of your callbacks are executed outside the Angular zone: https://stackblitz.com/edit/angular-datachannel-vcsmtc?file=src/app/app.component.ts

**Comment by manklu** [comment]
Luckily it's easy to fix.

https://stackblitz.com/edit/angular-datachannel-v2sadh
