### ISSUE TITLE
<form> tag causes wrong display of <select>

### ISSUE THREAD

**Issue by alexandr-osprey** [angular/angular#25013]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Exactly the same code when put into form tag,  displayed wrong initial selected item of select. When out of form tag, select works normally

## Expected behavior
Selected item according to binding

## Minimal reproduction of the problem with instructions
![image](https://user-images.githubusercontent.com/12857502/43035198-f13a627a-8cf3-11e8-91ac-f42b79e1c662.png)

ids displayed below. 1 case is wrong (resolution has id = 2), 2 case is correct.

     <div>
        <form>
          <div class="form-group">
            <div *ngFor="let propertyValue of currentVariant.itemVariantPropertyValues">
              <select class="form-control" id="categoryProperty[]" required
                      name="categoryProperty[]" [(ngModel)]="propertyValue.categoryPropertyId">
                <option *ngFor="let categoryProperty of categoryProperties" [value]="categoryProperty.id">
                  {{categoryProperty.title}}
                </option>
              </select>
              {{propertyValue.categoryPropertyId}}
            </div>
          </div>
        </form>
        <div class="form-group">
          <div *ngFor="let propertyValue of currentVariant.itemVariantPropertyValues">
            <select class="form-control" id="categoryProperty[]" required
                    name="categoryProperty[]" [(ngModel)]="propertyValue.categoryPropertyId">
              <option *ngFor="let categoryProperty of categoryProperties" [value]="categoryProperty.id">
                {{categoryProperty.title}}
              </option>
            </select>
            {{propertyValue.categoryPropertyId}}
          </div>
        </div>
      </div>

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x ] Chrome (desktop) version 67
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 61
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
Please make sure all your `<select>` element have different `name` attributes.

**Comment by alexandr-osprey** [comment]
@trotyl you are right, thank you.
