### ISSUE TITLE
Print code from the AST (HTML / CSS) 

### ISSUE THREAD

**Issue by GrandSchtroumpf** [angular/angular#25029]
## I'm submitting a...
[X] Feature request

## Current behavior
Cannot print the html / CSS code of an AST using HtmlParser / CssParser.

## Expected behavior
I would like to have a `print()` or `toString()` function on top of the `ParseTreeResult` class to easily print the code related to an AST. Something like the `print()` function in the TS Compiler API.

## Minimal reproduction of the problem with instructions
```
const parser = new HtmlParser();
const tree = parser.parse('<h1>Hello World</h1>', '');
// tree has no method to print "<h1>Hello World</h1>"
```

## What is the motivation / use case for changing the behavior?
I want to build a visual programming tool to build Angular apps: 
- **Code -> Visual**: Angular code is parsed into AST. The AST shows buttons to transform the AST visually.
- **Visual -> Code**: Once the AST is transformed, print the result and replace the previous code.

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
not relevant.
 
For Tooling issues:
- Node version: 8.9.0
- Platform:  Windows 10

**Comment by vicb** [comment]
We don't have a use case for this.

**Comment by GrandSchtroumpf** [comment]
Here are two use cases from the Google team: 
- (ngconf 2018) Angular for Designers: https://www.youtube.com/watch?v=LP-fNM8OITI 
- (Angular Blog) Moving Design Beyond Pictures: https://blog.angular.io/moving-design-beyond-pictures-1509c315f94e
I think it would help to build WYSIWYG prototyping tools that export good angular code. And it would ease the boundary between designers, devs, and digital marketers.
