### ISSUE TITLE
support URL schemes in @View Annotation

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2502]
# GOAL

* Angular currently supports absolute URLs in `View.templateUrl` and `View.stylesheetUrls`.
* Angular should support relative URLs with #2383 
* Angular should support custom URL schemes in addition to `http:` such as `my-custom-scheme:path` or `package:path` for dart. This should be plug able.

**Comment by TedSander** [comment]
We had custom URL schemes working for angular.dart using NodeTreeSanitizer and UrlRewriter. It would be nice if more of this code was in angular2 core.

**Comment by evanplaice** [comment]
Yes, please!

Relative paths on template and style urls are essential for component reusability.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
