### ISSUE TITLE
Tutorial Step Slightly Incorrect

### ISSUE THREAD

**Issue by siirtecirlioglu** [angular/angular#25025]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

HTTP section of the tutorial has a sentence that is slightly incorrect. After making some changes it asks us to test our changes providing the steps to take, but one of these steps is unnecessary.

## Expected behavior

The unnecessary step should be removed or better explained.

## Minimal reproduction of the problem with instructions

1. Open https://angular.io/tutorial/toh-pt6#update-heroes
2. Scroll to the last paragraph of that section ('Update Heroes')
3. It says the following sentence: "Refresh the browser, change a hero name, save your change, and click the "go back" button."
4. However we do not need to click the "go back" button as this is already integrated as part of our code in the same section. Below is the code from the same section of the tutorial that already provides this "go back" functionality automatically:
save(): void {
   this.heroService.updateHero(this.hero)
     .subscribe(() => this.goBack());
 } 

## What is the motivation / use case for changing the behavior?

Just to have the tutorial perfect as it has been so far until that sentence.

## Environment

<pre><code>
Angular version: X.Y.Z

Yes

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
* Although I assume it is the same in other browsers too. 

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jainanuj0812** [comment]
+1

**Comment by FrederikSchlemmer** [comment]
I'm going to work on this issue!

**Comment by brandonroberts** [comment]
Fixed via https://github.com/angular/angular/pull/25059
