### ISSUE TITLE
Angular Elements & Server Side Rendering

### ISSUE THREAD

**Issue by IamManchanda** [angular/angular#25035]
## I'm submitting a Feature Request

Source: https://www.udemy.com/the-complete-guide-to-angular-2/

<img width="1495" alt="screen shot 2018-07-23 at 12 05 19 pm" src="https://user-images.githubusercontent.com/4970624/43061088-65d1e008-8e71-11e8-969c-411ac695e7f6.png">

**Comment by IamManchanda** [comment]
@trotyl Any specific reason for disliking this thread. I can only tell you that if I am selling myself into using Angular elements in a Vue or React App. I would need server side rendering, that's obvious I guess with SEO's or Is it? Am I missing something?

cc @TheLarkInn

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
