### ISSUE TITLE
Reactive Input File

### ISSUE THREAD

**Issue by mouradghafiri** [angular/angular#25038]
Hello;

Hope it is time to add this long awaited feature :) 
Adding input file to reactive forms

Thank you in advance :)

**Comment by vicb** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a plunker reproducing the problem and describing the difference between the expected and current behavior. You can use this plunker template: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue
