### ISSUE TITLE
Pass a i18n text as component parameter

### ISSUE THREAD

**Issue by Calion54** [angular/angular#25031]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I would like translate a text who it's pass inside a component like that:

```
<app-empty-result
                    *ngIf="!mySetList.count"
                    [srcImg]="'/assets/images/cancel.svg'"
                    [textImg]="'There are no sets !'">
  </app-empty-result>
```

I didn't find any solution to make it.

## Expected behavior
Do you have any solution ? I think, it will be the good way to do that like this :

```
<app-empty-result
                    *ngIf="!mySetList.count"
                    [srcImg]="'/assets/images/cancel.svg'"
                    [textImg]="'There are no sets !'" i18n-textImg>
  </app-empty-result>
```

## Environment

Angular version: 6.0.7

Thanks

**Comment by Airblader** [comment]
You can use pipes for this.

**Comment by Airblader** [comment]
On a side note, in this specific case you might also want to consider switching your component to content projection:

```
<app-empty-result *ngIf="!mySetList.count" [srcImg]="'/assets/images/cancel.svg'">
  <span emptyResultDescription i18n>There are no sets!</span>
</app-empty-result>
```

**Comment by Calion54** [comment]
Thanks @Airblader , the second solution works perfectly.
But, I'm interested in your first solution because, if the text is using as a placeholder of a select, I can't use ng-content.

**Comment by Airblader** [comment]
It looks like the builtin i18n doesn't provide a pipe, which I intuitively assumed. We use ngx-translate in our project and from the looks of it I'd suggest you use that as well :-)

**Comment by Calion54** [comment]
ok, I see, thanks
