### ISSUE TITLE
Manually injecting HttpClient using Injector.create does not inject HttpClient's dependencies ie. HttpHandler

### ISSUE THREAD

**Issue by dhavalpowar** [angular/angular#25037]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
`HttpClientModule` has already been added in `AppModule`'s `@NgModule.imports`

```
const injector = Injector.create([
  { provide: HttpClient, useClass: HttpClient, deps: [] }
]);

const httpService = httpClientInjector.get(HttpClient);
```
The injector is created successfully, but on using the injector, it cannot find the handle.
```
httpService.get('/some/api/call')
.subscribe(console.log, console.err)
```

Errors out with:
```
TypeError: Cannot read property 'handle' of undefined
    at MergeMapSubscriber.project (http.js:1158)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext (mergeMap.js:117)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next (mergeMap.js:107)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:93)
    at Observable._subscribe (scalar.js:5)
    at Observable.push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe (Observable.js:176)
    at Observable.push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe (Observable.js:161)
    at MergeMapOperator.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapOperator.call (mergeMap.js:80)
    at Observable.push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe (Observable.js:158)
    at FilterOperator.push../node_modules/rxjs/_esm5/internal/operators/filter.js.FilterOperator.call (filter.js:55)
```
The error points into `http.js:1158`
```
// Start with an Observable.of() the initial request, and run the handler (which
        // includes all interceptors) inside a concatMap(). This way, the handler runs
        // inside an Observable chain, which causes interceptors to be re-run on every
        // subscription (this also makes retries re-run the handler, including interceptors).
        var events$ = of(req).pipe(concatMap(function (req) { return _this.handler.handle(req); }));
        // If coming via the API signature which accepts a previously constructed HttpRequest,
        // the only option is to get the event stream. Otherwise, return the event stream if
        // that is what was requested.
``` 
## Expected behavior

Manually injecting `httpService` should have all dependencies of HttpClient (ie. `handler` instanceof `HttpHandler`).

## What is the motivation / use case for changing the behavior?

Need to manually inject HttpClient in order to create custom decorators.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dhavalpowar** [comment]
@trotyl Do you happen to have a solution for this?

**Comment by dhavalpowar** [comment]
Never mind, I figured I'd had to inject all the dependencies upto xhrFactory.

```javascript
const xhrFactoryInjector = Injector.create([
  { provide: BrowserXhr, useClass: BrowserXhr, deps:[] }
]);

const httpHandlerInjector = Injector.create([
  { provide: HttpXhrBackend, useClass: HttpXhrBackend, deps:[BrowserXhr] }
], xhrFactoryInjector);

const httpClientInjector = Injector.create([
  { provide: HttpClient, useClass: HttpClient, deps:[HttpXhrBackend] }
], httpHandlerInjector);
```

**Comment by alxhub** [comment]
> Manually injecting httpService should have all dependencies of HttpClient (ie. handler instanceof HttpHandler).

This is not true. The way you've configured your provider, with `useClass: HttpClient, deps: []`, you're explicitly asking for a version of `HttpClient` to be created _without any of its dependencies_. It's fully expected in this case that `handler` would be `undefined`.

Additionally, you don't need to create a separate `Injector` for each individual dependency. Just stop specifying `deps` and put everything in the injector:

```typescript
const httpClientInjector = Injector.create([
    HttpClient,
    {provide: HttpHandler, useClass: HttpInterceptingHandler},
    HttpXhrBackend,
    {provide: HttpBackend, useExisting: HttpXhrBackend},
    BrowserXhr,
    {provide: XhrFactory, useExisting: BrowserXhr},
]);
```

I feel obliged to point out that this is an unsupported way of creating `HttpClient` instances - the structure of providers may change in any Angular release and break this code.

**Comment by sharikovvladislav** [comment]
What do you want to solve using such injector? @dhavalpowar

**Comment by Prinsn** [comment]
@alxhub your code definition there doesn't work for me, where as @dhavalpowar's does

@sharikovvladislav I ran into a similar problem with trying to setup testing on a project I was just brought onto where decoupling things isn't something that I'm allowed to do prior to the testing being in place.  Catch 22 kind of thing, can't do good code without working with bad code.
