### ISSUE TITLE
Add a reference about disabling/enabling a form control on setValue section

### ISSUE THREAD

**Issue by julianobrasil** [angular/angular#25030]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When you enable/disable a form control, if you don't provide options to the methods `enable()`/`disable()`, it'll reconfigure the `emitEvent` and `onlySelf`, as stated at [here](https://angular.io/api/forms/AbstractControl#enable) and [here ](https://angular.io/api/forms/AbstractControl#disable) 

It is not obvious, if you just read the info about `setValue()`, that a disabled state change also modifies those two options (IMO it's normal if one thinks that just methods that change the control value have the ability to change those behaviors).

## Expected behavior

It would be nice if we have a reference at 
https://angular.io/api/forms/FormControl#setvalue pointing that disable()/enable() also need the `onlySelf` and `emitEvent` to be configured.

## Minimal reproduction of the problem with instructions

Take a look at the console as even with the `emitEvent` set to false in the `setValue`, a value can be seen in the console because I'm also disabling the control in the next code line, without providing any option.

https://stackblitz.com/edit/angular-87wsxj?file=src/app/app.component.ts

```ts
this.control = new FormControl();
this.control.valueChanges.subscribe(value => {
  console.log("Value changed:", value);
});

this.control.setValue('test', { emitEvent: false }); // => this shouldn't fire the valueChanges
this.control.enable(); // => but this line kind of invalidate the emitEvent set in the line before
                       //    by emiting the last value set.
```

## What is the motivation / use case for changing the behavior?

I spent a lot of time today looking for an inexistent bug because I've never suspected that disabling/enabling a control would change the `onlySelf/emitEvent` settings (actually they don't seem to be "settings", just behavior options).

## Environment

<pre><code>
Angular version: 6.1.0-rc.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>
Related to https://github.com/angular/angular/issues/14668

**Comment by DmitryEfimenko** [comment]
For me a similar behavior happened when I had my own custom input component wrapping another component that also implemented `ControlValueAccessor`. The underlying component didn't have `{ emitEvent: false }` option provided and setiting this option in the top level component would do nothing. Kind of hard issue to track.

**Comment by burasuk** [comment]
> For me a similar behavior happened when I had my own custom input component wrapping another component that also implemented `ControlValueAccessor`. The underlying component didn't have `{ emitEvent: false }` option provided and setiting this option in the top level component would do nothing. Kind of hard issue to track.

Can You write something more about this?
I'm facing same behavior, but i can't solve it.

**Comment by DmitryEfimenko** [comment]
@burasuk this was almost **exactly** a year ago for me (1 day difference - how funny!). I don't remember a lot of details. However, I can attempt to help you out if you provide a stackblitz repro.
