### ISSUE TITLE
Best Practice: Update @Input + @Output in component two-way binding?

### ISSUE THREAD

**Issue by Airblader** [angular/angular#25036]
## I'm submitting a...
<pre><code>
[X] Documentation issue or request
</code></pre>

## Current behavior

In documentation such as [for two-way bindings](https://angular.io/guide/template-syntax#two-way-binding---), examples where we have a two-way binding (that is, an input `x` and an output `xChange`) update both from within the component:

```
resize(delta: number) {
    this.size = Math.min(40, Math.max(8, +this.size + delta));
    this.sizeChange.emit(this.size);
}
```

However, there's a case to be made that the component should *only* trigger the output:

1. It allows the parent component to control whether it wants to allow updating the value (e.g., by binding a getter/setter)
2. It can help dealing with asynchronous updates which should maybe delay changing the actual data of the component (but this is very much design-dependent)
3. The very behavior we get from updating both the input and output can also be achieved by binding a setter; the behavior we get when only the output is triggered cannot be achieved without changing the component in question.

However, there's certainly also arguments in favor of the component updating both.

## Expected behavior

I'd like some clarification as to how the Angular team intends two-way bindings to be used. Is it…

* … better to always change both the input and trigger the output?
* … better to always trigger only the output?
* … dependent on the use-case which one is better?

I think ultimately by answering and documenting such things we can encourage users to build better-quality components. I'm staying away from answering the question here myself because I would much rather have the brains behind the framework document their train of thought and how they intend the framework to be used.

## Environment

<pre><code>
Angular version: 6.x.x
</code></pre>

**Comment by jenniferfell** [comment]
@kapunahelewong Is this addressed in the work you're doing on template syntax?

**Comment by kapunahelewong** [comment]
@jenniferfell no, this isn't in the current iteration, but I can certainly pull it in to make sure the message is clear. I don't know the answers to those very good questions though. Hey @brandonroberts could you offer some insight on @Airblader's questions?

**Comment by Airblader** [comment]
@kapunahelewong Since there's been no response by Brandon in the past 2.5 years, anyone else who might be able to give the Angular team's perspective?

**Comment by kapunahelewong** [comment]
Oh, thank you so much for bumping this back up, @Airblader. I'm sorry this has taken so long. @jelbourn, could you advise us on some of the questions here or point us in the right direction? 

cc @aikidave 

@Airblader, I'll also reach out to team members directly to get some direction here.

**Comment by jelbourn** [comment]
@kapunahelewong I'm actually not sure myself how this was intended to work. I think @mhevery would have a better idea.

**Comment by mhevery** [comment]
In the above example 

```
resize(delta: number) {
    this.size = Math.min(40, Math.max(8, +this.size + delta));
    this.sizeChange.emit(this.size);
}
```

The code updates both it's input `size` as well as fire `sizeChange` event. I think that example is reasonable as it mimics what happens with `<input>`. In case of input both the `value` changes as well as `<input>` fires a `change` event. A higher order component can override the `<input>`'s `value` with something else after the `change` event fires. 

If the above code did not update `size` than the component would not be able to work on its own (it would require a parent component to update its `size` input.) So from my point of view the example above sounds reasonable in it is aligned with best practice.

Is there anything else that needs to be done here? (or should we close this issue?)

**Comment by Airblader** [comment]
@mhevery Thanks for your response! I can't actually remember the "counter-examples" from back then anymore which made me open this in the first place; the only ones I could think of I'd probably design differently these days anyway.

I'll close this issue.
