### ISSUE TITLE
HttpTestingController fails to match POST request with HttpParams

### ISSUE THREAD

**Issue by Nexxado** [angular/angular#25047]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

`HttpTestingController` doesn't match the request when method is `POST` with `HttpParams`, resulting in error:

```
Error: Expected one matching request for criteria "Match URL: http://myhost:4200/my/url/endpoint", found none.

Error: Expected no open requests, found 1: POST http://myhost:4200/my/url/endpoint
```

## Expected behavior

`HttpTestingController` should correctly match the request

### Service

```TypeScript
import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';

@Injectable()
export class MyService {
    constructor(
        private http: HttpClient
    ) { }

    myRequest(
        someData: string,
        someParam: string
    ) {
        const body = { myData: someData };
        return this.http.post('/my/url/endpoint', body, {
            params: new HttpParams()
                .append('someParam', someParam)
        });
    }
}

```

### Test

```TypeScript
import { TestBed } from '@angular/core/testing';
import {
    HttpClientTestingModule,
    HttpTestingController
} from '@angular/common/http/testing';

describe('MyService', () => {
    let service: MyService;
    let http: HttpTestingController;

    beforeEach(() => {
        TestBed.configureTestingModule({
            providers: [MyService],
            imports: [HttpClientTestingModule]
        });

        service = TestBed.get(MyService);
        http = TestBed.get(HttpTestingController);
    });

    afterEach(() => http.verify());

    it('should do request', () => {
        const mockData = 'mockData';
        const mockParam = 'mockParam';
        const mockUrl = `/my/url/endpoint?someParam=${mockParam}`;

        service
            .myRequest(mockData, mockParam)
            .subscribe(() => { });

        const req = http.expectOne(mockUrl);
        expect(req.request.urlWithParams).toBe(mockUrl);
        expect(req.request.method).toBe('POST');
        expect(req.request.body).toEqual(mockData);

        req.flush({});
    });
})
```

* Removing params from `mockUrl` doesn't work
* **What worked** was removing the params from the http request in `myRequest` method, meaning modifying the request to this: `return this.http.post('/my/url/endpoint', body)`

## What is the motivation / use case for changing the behavior?

Ability to test all kinds of valid HTTP requests.

## Environment

<pre><code>
Angular version: 4.4.7

Browser:
- [x] Chrome (desktop) version 67.0.3396.99
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.11.3 
- Platform:  Mac 

Others:

</code></pre>

**Comment by fergardi** [comment]
Any news on this one? Just got stucked with this.

**Comment by romanzadorov** [comment]
Same here. Cannot find a solution so far.

**Comment by dave0688** [comment]
Same here. Stuck on that and no solution in sight. Why is such a common thing buggy?

**Comment by lolo101** [comment]
Isn't this a duplicate of  #19974 ?

**Comment by Nexxado** [comment]
@lolo101 Doesn't seem related to me.

The OP in the referenced issue is not asserting on `urlWithParams`.
This issue is a specific problem with `POST` requests.

**Comment by alxhub** [comment]
Hello all,

I could not reproduce this. I tried this test:

```typescript
const mock = new HttpClientTestingBackend();
const client = new HttpClient(mock);

client.post('/some-url', {data: 'data'}, {params: new HttpParams().append('key', 'value')})
    .subscribe();

mock.expectOne('/some-url?key=value');
```

This is able to find the request as expected. If you're still experiencing this issue, could you provide a stackblitz demonstrating the problem?

**Comment by Nexxado** [comment]
Tried recreating it using `Angular v9.1.6` and seems to work fine on both `Karma` and `Jest`.
So I guess this issue can be closed.
