### ISSUE TITLE
Promise from check login method is not returning the promise to canActivate()

### ISSUE THREAD

**Issue by alim90** [angular/angular#25040]
**Demo Link: https://stackblitz.com/edit/angular-czx8sq** 

I have the following login method:

    login(username, password)
      {
        let headerOptions = new HttpHeaders();
        // headerOptions.append('Access-Control-Allow-Origin', '*');
        // headerOptions.append('Access-Control-Request-Headers', '*');
        // headerOptions.append('Content-Type', 'application/json');
        // headerOptions.append('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,PATCH,OPTIONS');
        headerOptions.append('Content-Type', 'application/x-www-form-urlencoded; charset=UTF-8');
    
    
        this.credentials = {user: username, pass: password};
        const httpParams = new HttpParams()
          .set('username', username)
          .set('password', password);
        
        
        //console.log("hi "+ this.credentials);
        return this.http.post('http://dev.local/scripts/login.php', httpParams,  {
          headers: headerOptions,
        })
    }

And when a user is successfully logged in, a JWT array is returned into local storage, so we can check the role, and if it's still logged.

There is a component where only admins has the right to access it, so when a user click on the route:

    {
        path: 'forgot',
        component: ForgotPasswordComponent,
        canActivate: [AuthGuardService]
    },

An authGuard will run using the `canActivate()` guard.

    canActivate(_route: ActivatedRouteSnapshot, 
                  _state: RouterStateSnapshot) : Observable<boolean> | Promise<boolean> | boolean
      {
        if(this.authApi.checkIsLogin())
        {
          return true;
        }
        else
        {
          return false;
        }
    }

Now to check the `checkIsLogin()`, the following script a executed to return a promise:

    checkLoggedInAdmin()
      {
        //Get the JWT token from local storage
        let jwt = localStorage.getItem('jwt');
        let httpParams = new HttpParams().set('jwt', jwt);
        let headerOptions = new HttpHeaders();
        headerOptions.append('Content-Type', 'application/x-www-form-urlencoded; charset=UTF-8');
    
        const promise = new Promise(
          (resolve, reject)=>{
            if(jwt!="" || jwt!=null || jwt!=undefined)
            {
              this.http.post('http://dev.local/scripts/checkLoginAdmin.php', httpParams, {
                headers: headerOptions
              }).subscribe(
                (data)=>{
                  if(data==true)
                  {
                    this.loggedIn=true;
                  }
                  else{
                    this.loggedIn = false;
                  }
                }
              )
            }
            else
            {
             this.loggedIn=false;
            }
    
            resolve(this.loggedIn),
            reject(this.loggedIn)
          }
        )
    }

Where `loggedIn` is defined as boolean on top of the class.

And here is the function `checkIsLogin()`:

    checkIsLogin(){
        return this.loggedIn
    }

When a user logged in, a jwt is returned, with all necessary details. But if it's an admin, and when clicking on the desired route, nothing happened, and no code is executed, with no errors at the console.

**Comment by alim90** [comment]
@trotyl this is the second time you down vote a question from me without even mentioning the reason. I posted this on stack but no one could solve it. So I think some here could help.

**Comment by manklu** [comment]
@alim90 At least you should provide a complete sample that reproduce the problem.

**Comment by alim90** [comment]
@manklu how can I leave a sample, do I upload all the project on github ?

**Comment by manklu** [comment]
I think you look for something like this: https://stackblitz.com/edit/angular-6y9pdt

**Comment by viluon** [comment]
> this is the second time you down vote a question from me without even mentioning the reason

I have a feeling everyone would be much happier if you filled in the [issue template](https://github.com/angular/angular/blob/master/.github/ISSUE_TEMPLATE.md) and provided all important information right away, @alim90.

**Comment by jasonaden** [comment]
@alim90 While the thumbs-down might seem a bit offensive, I believe @trotyl is trying to say it's a bug that doesn't follow the template. We require a minimal reproduction of the issue with the actual steps to reproduce the problem. This explanation should be like you're explaining to a child with zero knowledge of what you're talking about. Your demo, while it might reproduce the issue you're having, has far too much code in it and we would need to walk through that code to figure out what's happening.

The key to making a good bug report is to provide a *minimal reproduction* with instructions that clearly lay out how to reproduce the bug. There really shouldn't be any code in the bug description, only the explanation of the steps and mentions of how you feel it should be working and why.

Therefore, I have to close this bug as it's a support request and doesn't follow the issue template. However, if you can come up with an issue as described above, please file a new issue and we can take a look at it.
