### ISSUE TITLE
{ provide: APP_BASE_HREF, useValue: '/' } is behaving differently from <base href="/">

### ISSUE THREAD

**Issue by dereklin** [angular/angular#25049]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I use &lt;base href="/">, I can refresh a nested route without any issue.  For example: http://localhost:4200/to/f1.
When I comment out &lt;base href="/"> and use { provide: APP_BASE_HREF, useValue: '/' } instead, I get these errors:
```
GET http://localhost:4200/to/runtime.js 404 (Not Found)
5Refused to execute script from '<URL>' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
4f1:13 GET http://localhost:4200/to/polyfills.js 404 (Not Found)
```

## Expected behavior

I expect { provide: APP_BASE_HREF, useValue: '/' }  to behave the same as &lt;base href="/">

## Minimal reproduction of the problem with instructions

git clone https://github.com/dereklin/nrwl-nx-workspace-demo.git
git checkout try-app-base-href
npm i
npm run start:app1
the page loads fine the first time
refresh the page and you should see the errors

## What is the motivation / use case for changing the behavior?

I want to use APP_BASE_HREF to dynamically determine the base.

## Environment

<pre><code>
Angular version: 6.0.9

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dawidgarus** [comment]
Setting `APP_BASE_HREF` is not alternative to `<base href>`. When You load script like this: `<script src="runtime.js">` without `<base href>` it matters if You are on page `http://localhost:4200/` or `http://localhost:4200/to/f1` and it has nothing to do with angular - that's how HTML works in browsers.

**Comment by dereklin** [comment]
I see.  I guess I have to change in both the <base href> and APP_BASE_HREF to make dynamic hosting work properly then.

In the meantime, I am adding the baseHref option in angular.json:

```
"architect": {
        ...
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "app1:build",
            "baseHref": "/"
```

**Comment by Halfist** [comment]
@dawidgarus, according to https://stackoverflow.com/a/34535256/1611569, `APP_BASE_HREF` is an alternative to `<base href>`.

**Comment by dawidgarus** [comment]
@Halfist As I said, angular doesn't care if You use `APP_BASE_HREF` or `<base href>`, but HTML care and browsers care if You have `<base href>`. Angular doesn't load your scripts.

**Comment by Halfist** [comment]
@dawidgarus, I agree, but I don't have `<base href>` in my index.html, only `APP_BASE_HREF` in app.module.ts, and application works fine.

**Comment by dawidgarus** [comment]
@Halfist You might be having absolute paths to resources or using `HashLocationStrategy` - then it shouldn't matter. Or Your server is configured the way that it can server scripts/resources despite it. Or it could be that it doesn't work fine if you refresh You app not on your home page.

**Comment by cyrusfurtado** [comment]
This issue doesn't seem to be fixed. The `APP_BASE_HREF` token in angular seems to be useless. Coz for me the only working solution was to set `<base href="absolute/path/to/my/files">` using `PathLocationStrategy` of course.

**Comment by dawidgarus** [comment]
Here's my example why `<base href>` and `APP_BASE_HREF` are different thing.
I have two apps with shared resources. First app is available at `https://host/first` and second at `https://host/second`. Both apps share resources like images which are available at `https://host/img` and both apps have `<base href="/">` so i can reference the images like this: `<img src="img/my-image.png">`. But... First app have `APP_BASE_HREF` set to `/first` and second app have it set to `/second` so I dont need to add `/first` or `/second` in my router configuration which is desired behaviour because I can share feature module between the two apps and it doesn't need to know what the prefix is. The only thing that `APP_BASE_HREF` have in common with `<base href>` is that former uses the latter as default value if you don't provide one.
