### ISSUE TITLE
MatSelect crashes at page load

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular#25041]
## I'm submitting a...

[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
MatSelect does not open after page refresh when used in a lazy loaded component.

## Expected behavior
Should work without a timeout issue.

## Minimal reproduction of the problem with instructions
Place a mat-select on a lazy loaded component.
Navigate to that component and press F5. 
MatSelect won't open.
Navigate to another component through the angular router (not browser url) and then back to the lazy loaded component. Mat select should now work fine.

A SetTimeout arround the bootstrap resolves that problem.

```
import {enableProdMode} from '@angular/core';
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';
import {AppModule} from './app/app.module';
import {environment} from './environments/environment';
import 'hammerjs';

if (environment.production) {
  enableProdMode();
}

setTimeout(() => {
  platformBrowserDynamic().bootstrapModule(AppModule)
    .catch(err => console.log(err));
}, 100);
```

## What is the motivation / use case for changing the behavior?
Get rid of the SetTimeout...

## Environment
Angular CLI: 6.0.8
Node: 8.9.4
OS: win32 x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.4.0
@angular/cli                      6.0.8
@angular/material                 6.4.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3

Browser:
- [X] Chrome (desktop) version 67
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X] IE version 11
- [X] Edge version 11
 
For Tooling issues:
See above

Others:

**Comment by vicb** [comment]
Could you please report this issue on the material repo https://github.com/angular/material2

Thanks

**Comment by mbeckenbach** [comment]
@vicb 
Sorry that was my intend. ;-)
