### ISSUE TITLE
Error in platform-browser-dynamic incorrectly implements class 'Compiler'.

### ISSUE THREAD

**Issue by vishalbedre** [angular/angular#25045]
Hi All,

I am getting following error please suggest.

 **ERROR in node_modules/@angular/platform-browser-dynamic/src/compiler_factory.d.ts(18,22): error TS2720: Class 'CompilerImpl' incorrectly implements class 'Compiler'. Did you mean to extend 'Compiler' and inherit its members as a subclass?
 Property 'getModuleId' is missing in type 'CompilerImpl'.
 node_modules/@angular/platform-browser-dynamic/testing/src/compiler_factory.d.ts(12,22): error TS2720: Class 'TestingCompilerImpl' incorrectly implements class 'TestingCompiler'. Did you mean to extend 'TestingCompiler' and inherit its members as a subclass?
  Property 'getModuleId' is missing in type 'TestingCompilerImpl'.****

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
