### ISSUE TITLE
RouterLink Incorrectly Serializes '/' for Child Routes in non-primary router outlet.

### ISSUE THREAD

**Issue by rob123456** [angular/angular#25044]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When you use a RouterLink attribute to navigate to a specific location inside a named (non-primary) RouterOutlet it ends up treating the whole path as one URL segment and so escapes all the forward-slashes contained in the path.

e.g. a usage of the form `<a [routerLink]="['', { outlets: { 'modal': ['/wfr/timeseries/data/25/latest', {t:'[533903,13684]'}] } }]">grid</a>` generates URLs of the form `https://localhost/...Primary Router Path...(modal:%2Fwfr%2Ftimeseries%2Fdata%2F25%2Flatest;t=%5B533903,13684%5D)`. The angular router cannot cope with a path in this format.

## Expected behavior
I would expect it to output a URL of the form `https://localhost/...Primary Router Path...(modal:/wfr/timeseries/data/25/latest;t=%5B533903,13684%5D)` (which is successfully routed by Angular)

## Minimal reproduction of the problem with instructions
Steps to reproduce:
* Set up an angular project which a PRIMARY router outlet and a second named router outlet. 
* Create routes with children. Specify that each parent route is resolved via a different outlet. The child routes need not specify the outlet.
* Use the RouterLink directive to target a child route contained within the non-primary outlet. 
* Observe that the URL generated contains escaped forward-slashes.
* Attempt to navigate to the generated link and observe that angular fails to find a suitable route due to the escaped slashes.

## What is the motivation / use case for changing the behavior?
Sanity.

## Environment
All of them

<pre><code>
Angular version: 6.0.7

Browser:
- [X] Chrome (desktop) version XX
- [X] Chrome (Android) version XX
- [X] Chrome (iOS) version XX
- [X] Firefox version XX
- [X] Safari (desktop) version XX
- [X] Safari (iOS) version XX
- [X] IE version XX
- [X] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by rob123456** [comment]
For anyone else with the same problem, here's my hacky fix directive.

```
import { Directive, Input } from "@angular/core"
import { Router, RouterLink, UrlTree, ActivatedRoute, UrlSegmentGroup, UrlSegment, RouterLinkWithHref } from "@angular/router";

import * as _ from "lodash";
import { LocationStrategy } from "@angular/common";

@Directive({ selector: "a[hackyRouterLink]" })
export class HackyRouterLinkWithHref extends RouterLinkWithHref {

    @Input() set hackyRouterLink(commands: any) {
        this.routerLink = commands;
    }

    private originalGetUrlTreeMethod: () => UrlTree;

    constructor(    
        router: Router,
        route: ActivatedRoute,
        locationStrategy: LocationStrategy
    ) {
        super(router, route, locationStrategy);

        //Dodgy override here.
        let objectWithUrlTreeOwnProperty: RouterLink = Object.getPrototypeOf(this);
        while (!objectWithUrlTreeOwnProperty.hasOwnProperty("urlTree")) {
            objectWithUrlTreeOwnProperty = Object.getPrototypeOf(objectWithUrlTreeOwnProperty);
        }

        let originalUrlTreePropertyDescriptor = Object.getOwnPropertyDescriptor(objectWithUrlTreeOwnProperty, "urlTree");
        this.originalGetUrlTreeMethod = originalUrlTreePropertyDescriptor.get.bind(this);

        Object.defineProperty(this, "urlTree", {
            get: this.getUrlTree
        });
    }

    private getUrlTree = (): UrlTree => {
        var urlTree = this.originalGetUrlTreeMethod();
        urlTree.root = this.mapUrlTreeToHackApprovedVersion(urlTree.root);

        return urlTree;
    }

    private mapUrlTreeToHackApprovedVersion = (segmentGroup: UrlSegmentGroup): UrlSegmentGroup => {
        segmentGroup.segments = _.flatMap(segmentGroup.segments, seg => {
            if (seg.path.indexOf("/") >= 0) {
                const newSegsStr = _.trimStart(seg.path, "/")
                    .split("/");

                return newSegsStr
                    .map((pathSeg, i) => {
                        if (i === newSegsStr.length - 1) {
                            //Add the parameters on to the last segment - makes sense.
                            return new UrlSegment(pathSeg, seg.parameters);
                        }
                        return new UrlSegment(pathSeg, {});
                    });
            }

            return [seg];
        });

        if (segmentGroup.hasChildren()) {
            for (let outletName in segmentGroup.children) {
                this.mapUrlTreeToHackApprovedVersion(segmentGroup.children[outletName]);
            }
        }

        return segmentGroup;
    };
}
```

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
