### ISSUE TITLE
Angular almost, but not quite, supports Pale Moon (or vice versa). Can this be improved?

### ISSUE THREAD

**Issue by karptonite** [angular/angular#25046]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
As I understand it, Angular pages, such as angular.io, fail to load in the current version of the browser [Pale Moon](https://github.com/MoonchildProductions/Pale-Moon). it appears from [this discussion](https://forum.palemoon.org/viewtopic.php?t=18192) that the site loads fine if the users change the browser setting so that javascript must be run in "strict mode". That thread includes a brief discussion of what the Pale Moon maintainers seem to think the problem might be. 

## Expected behavior
It would be better if it weren't necessary to adjust the browser settings for Angular pages to work on Pale Moon.

## Minimal reproduction of the problem with instructions
Load angular.io on  the Pale Moon browser. 

## What is the motivation / use case for changing the behavior?
I'm working to convert our website to Angular. The first time I ever heard of Pale Moon is when a few of its users complained that the site didn't work on their browser. I would have just told them that we don't support Pale Moon, but found that we *almost* supported it, and was able to provide instructions for them to change their settings to use the new page.

I'm not asking for Angular to officially support Pale Moon, but if there is any small change that could be made to fix this (at either end) it would save us some grief from the few users who use this browser.

I'll also be filing an issue with Pale Moon, and linking it here. With the two project so close to being compatible out of the box, it would be great if one or the other could make adjustments to get the rest of the way there.

**Comment by dawidgarus** [comment]
Maybe compiling Your app with "alwaysStrict" typescript options enabled will work.

**Comment by karptonite** [comment]
Looks like this should no longer be an issue with Pale Moon 28.
