### ISSUE TITLE
NgModel Doesn't Register FormControl when Used from an ng-template

### ISSUE THREAD

**Issue by viluon** [angular/angular#25050]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using a custom component with `NgModel` inside an `ng-template` loaded via `*ngTemplateOutlet`, the component isn't registered with the parent `form` component.

## Expected behavior

The component should be registered with the parent `form` component, as [per the documentation](https://angular.io/api/forms/NgModel#description):
> ... If used within a parent form, the directive will also register itself with the form as a child control.

## Minimal reproduction of the problem with instructions

[Here](https://stackblitz.com/edit/ng-template-vs-ngmodule) is a StackBlitz with a minimal use case. Input some text into both fields and click both submit buttons. The form values appear in the console - the bottom input's value is missing.

## What is the motivation / use case for changing the behavior?

I'm generating complex forms with templates, and using `ng-template`/`*ngTemplateOutlet` to avoid duplicating large chunks of code.

I'm a novice when it comes to Angular, so it may be nothing more than a silly mistake (or misunderstanding) on my side. I apologize in advance if that is the case. I searched for issues touching similar topics, but I haven't found any dealing with the same problem. I may have missed some, however.

## Environment

<pre><code>
Angular version: 6.0.0, 6.0.9 (latest)

Browser:
- [x] Chrome (desktop) version 67.0.3396.99 (Official Build) Arch Linux (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by maxkorz** [comment]
You can declare the `ng-template` inside the form and it'll work just fine.
https://stackblitz.com/edit/ng-template-vs-ngmodule-tp7rua?file=src/app/app.component.html

**Comment by viluon** [comment]
Thanks @maxkorz! Does that mean I was just using `ng-template` wrongly? If so, I think the docs should mention this (unless they do and I didn't notice).

**Comment by kara** [comment]
@maxkorz The `NgModel` directive registers itself with its parent form by using DI to inject that form. If you put the `NgModel` in an `ng-template`, DI will walk up the parent tree from where the template is declared, *not* where the template is inserted. This is a current limitation of the framework.

Since this framework behavior isn't likely to change soon (e.g. would break many apps), closing this issue.
