### ISSUE TITLE
ng build --prod not find components in lazy loading madules in angular 6

### ISSUE THREAD

**Issue by hesampour** [angular/angular#25057]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

I use lazy loading:
      { path: 'store', loadChildren: 'src/app/admin/store/store.module#StoreModule' },
in angular 5 there were no problem but when migrating to angular 6 I cant build my project with --prod option because of the following error:

Cannot determine the module for class PaymentListComponent in D:/current_projects/maz 8/admin/src/app/admin/userManager/components/PaymentList.component.ts! Add PaymentListComponent to the NgModule to fix it.

but component PaymentListComponent  is in the storeMadule.

**Comment by Zarepheth** [comment]
I'm suffering a similar error.

Two of my components, which are imported into their own modules and where those modules are imported into modules that use their components, and likewise to the top of the application, are being flagged with:
```
Cannot determine the module for class MyComponent in C:/.../myComponent.component.ts! Add MyComponent to the NgModule to fix it.
```

The error occurred after updating from Angular 5 to Angular 6. I have many other components similarly constructed which are not being flagged by the Angular AOT compiler.

Any suggestions for debugging this?
Or is this an actual bug in Angular 6? If so, any work-arounds?

**Comment by Zarepheth** [comment]
Solved - at least for my case.

Apparently, the import statement case sensitivity changed with all the updated npm packages. The two erring components had names on the file system where one or more characters were in a different case than in the import strings of their respective modules.

See here for more info: [https://stackoverflow.com/questions/50071992#51274773](https://stackoverflow.com/questions/50071992#51274773)

**Comment by vicb** [comment]
Please add a minimal repro to this issue.

**Comment by hesampour** [comment]
thank @Zarepheth. my problem also was the same as yours. i was importing with small characters but the real file name started with capital letter. in angular 5 there were no problem.
thanks alot.
