### ISSUE TITLE
AOT compilation does not fail with undefined variable inside ngFor

### ISSUE THREAD

**Issue by mstssk** [angular/angular#25056]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I expected failing `ng build --prod` or `ng build --aot` with below code: using undefined variable inside `ngFor`.
However succeed.

```ts
@Component({
  selector: 'my-app',
  template: `
    <div *ngFor="let v of list">
      {{ foobar }} <!-- 'foobar' is not defined. -->
    </div>
  `
})
export class AppComponent {
  list = [1, 2, 3, 4];
}
```

## Expected behavior

Should fail a build with above code.

## What is the motivation / use case for changing the behavior?

Checkout [my reproduction repo](https://github.com/mstssk/angular-bug-aot-undefined-variable-inside-ngfor), then run `npm install` and `npm run build`.

## Environment

<pre><code>
Angular version: Angular 5.2.11 (angluar/cli 1.7.4)
Angular 6.0.9 (angluar/cli 6.0.8)

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.4.1  
- Platform: macOS Sierra 10.12.6 

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
This pattern is now correctly recognised and reported as error in Angular v9 running ivy: https://ng-run.com/edit/Nolcmtx3J1Tj6EEi2woG
