### ISSUE TITLE
Webpack aot build fails searching for ngfactory Files

### ISSUE THREAD

**Issue by ramuda** [angular/angular#25058]
## Current behavior
Webpack aot build fails searching for ngfactory Files
 building modules 100/109 modules 9 active …modules\@angular\router\fesm5\router.jsModuleNotFoundError: Module not found: Error: Can't resolve '../../node_modules/ngx-toastr/ngx-toastr.ngfactory'
using following tsconfig
{
  "compileOnSave": false,
  "buildOnSave": false,
  "compilerOptions": {
    "declaration": true,
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "lib": ["es2015", "dom"],
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noImplicitAny": false,
    "sourceMap": true,
    "outDir":"./aot",
    "rootDir" : ".",
    "strictPropertyInitialization": false
  },
  "exclude": [
    "node_modules",
    "dist"
  ]
}
Using angular 6.0.3 and @ngtools/webpack 1.10.2

Same config was working with angular 5.1.0

## Expected behavior
Build should pass

## Environment

<pre><code>
Angular version: 6.0.3

 
For Tooling issues:
- Node version: 8.9.2
- Platform:  Windows

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
