### ISSUE TITLE
[Bug] [IE8] [ng-options] Object doesn't support property or method 'prop'

### ISSUE THREAD

**Issue by San4oPanso** [angular/angular#2506]
Hello. Found bug `Object doesn't support property or method 'prop'` at IE8 at ng-options at line
 (element = optionTemplate.clone())
                      .val(option.id)
                      .prop('selected', option.selected)
                      .attr('selected', option.selected)
                      .prop('label', option.label)
                      .text(option.label);

Angular 1.2.28. IE8 (emulation view mode from IE11)

**Comment by PascalPrecht** [comment]
@San4oPanso this is the Angular 2 repository. Please file your issue here: http://github.com/angular/angular.js/issues

Also, if you can, please update your Angular to the latest version.

**Comment by San4oPanso** [comment]
Oh, sorry..found wrong repo..
