### ISSUE TITLE
I can't uninstall the existing service worker

### ISSUE THREAD

**Issue by BUHARIMOHAMEDISMAIL** [angular/angular#25064]
I have create basic sample application and integrated angular/pwa. In ngsw-config .json file i added datagroups for api call. Now i can able to download the application and api call is working fine in offline too.
After that i moved to my application and did the same for pwa. Now api call is not working in offline.  I checked with api call which i used in sample application still i'm getting the data for that url but i didn't specified in ngsw-config.json file.

I can't unregistered my old service worker and create new service worker. In chrome developer tool i unregistered that service worker and again reload my application but still i'm getting the old data.

<pre><code>
Angular version: 6.0.2

Browser:
- [ ] Chrome (desktop) version 
 
For Tooling issues:
- Node version: 8.9.1
- Platform:  Windows

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
