### ISSUE TITLE
Deep linked libraries not being resolved in AOT

### ISSUE THREAD

**Issue by augustobmoura** [angular/angular#25075]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When AOT compiling a project, libs more than 1 level of linking are not being resolved correctly. Example:
```
In a scenario with:

main-project
└─ proxy-lib // linked in `main-project`
      └─ lib-package // linked in `proxy-lib`

All of them AOT compatible (or so it seems), generating `metadata.json`s, typescript d.ts types and esm js only (in our environment we don't need to be CJS or AMD compatible). Also aliasing the peerdeps
````

``` js
/*
lib-package exports some models and objects
*/
// lib-package/dist/service/foo.service.d.ts (also esm .js and metadata.json)
export declare class FooService {}

// lib-package/dist/index.d.ts (also esm .js and metadata.json)
export * from './service/foo.service';

// lib-package/package.json
{
  ...
  "main": "./dist/index.js",
  "module": "./dist/index.js",
  "es2015": "./dist/index.js",
  "typings": "./dist/index.d.ts",
  ...
}
```

``` js
/*
Proxy-lib reexports some of lib-package modules
*/
// proxy-lib/dist/index.d.ts: (also esm .js and metadata.json)
export * from 'lib-package';

// proxy-lib/package.json:
{
  ...
  "main": "./dist/index.js",
  "module": "./dist/index.js",
  "es2015": "./dist/index.js",
  "typings": "./dist/index.d.ts",
  ...
}
```

``` js
/*
Main-project import classes from inner "lib-package" by "proxy-lib" rexports
*/
// main-project/src/app/index.ts:
import { LibPackModule } from 'proxy-lib'
```
JIT compilation works just fine, compiling it with `--aot` throws (error from the example project):
```
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'lib-package/dist/service/foo.service' in '/{path-from-root}/main-package/src/app'
```
`--preserve-symlinks` doesn't seems to help. Maybe I'm getting something wrong with all the AOT thing, if so we really need to write some documentation about aot module resolution differences.

Looks like the compiler is trying to resolve the modules only in the main-project `node_modules`  and not  in the proxy-lib `node_modules` as seem in the verbose error log https://gist.github.com/augustobmoura/c91e68b18686236106dba585cb6692f0 (the error paths are from the reproduction demo).

Noting that when not linking and having the dependencies in the package.json, npm (v6.2.0 and below, i'm not sure when it's changed the behaviour) flatten the packages and the aot compilation works fine, because the deep deps can be found in main-project node_modules

## Expected behavior
Follow correctly the linkages and find the 'lib-package' inside 'proxy-lib' as JIT (and common sense) does

## Minimal reproduction of the problem with instructions
Error demo project https://github.com/augustobmoura/angular-aot-symlink-err

1. `npm install` in all three packages
2. `npm link` in lib-package
3. `npm link` in proxy-lib
4. `npm link lib-package` in proxy-lib (needs to be in this order, or else the npm link will trigger a npm install and override the lib-package link)
5. `npm link proxy-lib` in main-project (now the libs are all linked as descripted Current Behaviour block)
6. `npm run ng -- build --dev` in the main-project, build the project with the cli in package.json (v1.7.4). Works fine, compiles resolving the right packages and works as well
7. `npm run ng -- build --dev --aot` error
8. `npm run ng -- build --dev --aot --preserve-symlinks` also error

## What is the motivation / use case for changing the behavior?
The main use case is using packages as facades reexporting some functionality from others packages and adding extras.

## Environment

<pre><code>
Angular version: 5.2.11

Browser:
- [x] Chrome (desktop) version 67.0.3396.99
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v9.8.0
- Platform:  Linux Ubuntu 16.x

Others:
npm version: 6.2.0
</code></pre>

**Comment by lucas-script** [comment]
Same problem here! following.

**Comment by mlakmal** [comment]
getting same error. we have multiple linked packages using tsconfig paths. initial build works fine, but after a change it will fail on re-build with errors like below.

RROR in ./libs/shared/components/tabbedView2Cmp.ngfactory.js
Module not found: Error: Can't resolve '@anthem/uxd.ngfactory' in '/Users/xxx/stash/features/xxx-ui-v6/libs/shared/components'

**Comment by alxhub** [comment]
Angular (View Engine) has never supported `npm link`, or symlinks in `node_modules` in general. The good news is that the Ivy compiler has no such limitations.

**Comment by JoostK** [comment]
This particular issue is indeed no longer a problem in Ivy, however there can still be unforeseen consequences of using linked libraries. For example, this may result in multiple versions of the Angular runtime or general version incompatibilities in general; in these cases it's typically needed to enable `preserveSymlinks`.
