### ISSUE TITLE
Passing object param to directive undefined in SSR

### ISSUE THREAD

**Issue by mike-suggitt** [angular/angular#25073]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently attempting to pass an object parameter to a custom directive but when logged out inside the directive (on SSR) the variable is always undefined. If I pass this same object into a custom component and log the value then it is defined.

If I switch back to SPA-mode (`ng serve`) the directive behaves exactly the same as the component and logs out the object variable

## Expected behavior

Expect the content of the parameter to be populated for a directive as it appears to be for a component

## Minimal reproduction of the problem with instructions

Create a parent component with a test object property
Create a directive with an input property
Create a child component with an input property
Pass property from parent component into both child component and directive and log out their respective values.

Test on both development mode (`ng serve`) and SSR mode

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by manklu** [comment]
A complete sample that reproduces the problem would be helpful.

**Comment by vikerman** [comment]
No known issues here. Closing this for lack of repro.
