### ISSUE TITLE
Dyamic form with i18n

### ISSUE THREAD

**Issue by FARHANE** [angular/angular#25089]
## I'm submitting a...
<pre><code>

[x] Feature request

</code></pre>

## Current behavior
I am creating forms input dynamicaly somthing like : 
userInputs: Array<InputField<any>> = [
            new TextInputField({
                name: 'firstName',
                id: 'firstName',
                value: this.firstName,
                placeholder: 'Prénom',
                required: true,
                errorMessages: [
                    {
                        validator: 'required',
                        message: 'Le prénom ne peut pas être vide.'
                    }
                ]
            }),
            new TextInputField({
                name: 'lastName',
                id: 'lastName',
                value: this.lastName,
                placeholder: 'Nom',
                required: true,
                errorMessages: [
                    {
                        validator: 'required',
                        message: 'Le nom ne peut pas être vide.'
                    }
                ]
            }),
            new TextInputField({
                name: 'username',
                id: 'username',
                value: this.username,
                placeholder: 'Nom d\'utilisateur',
                required: true,
                errorMessages: [
                    {
                        validator: 'required',
                        message: 'Le nom d\'utilisateur ne peut pas être vide.'
                    }
                ]
            }),
...
]

## Expected behavior
I wanna be able to translate placeholder and validation errors.

**Comment by vicb** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a plunker reproducing the problem and describing the difference between the expected and current behavior. You can use this plunker template: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue
