### ISSUE TITLE
Lazy loading of feature library modules from node_modules

### ISSUE THREAD

**Issue by nitink85** [angular/angular#25083]
## I'm submitting a...

<pre><code>
[ Lazy loading of feature library modules from node_modules, is not working] Bug report  
</code></pre>

## Current behavior

```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

const routes: Routes = [{path: 'feature',
    loadChildren: 'feature#FeatureModule'}];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }

```
```feature``` is a package which is having ```FeatureModule``` module in it, installed as NPM package in my root app. Using router of root app, I am trying to lazy load.
If I do so and use SystemJS(systemjs.conf.ts, System.import(...)), instead CLI, it works fine for me.
But same code is not working when I try on app based on CLI. It is giving me below error.
```
ERROR in ./node_modules/feature/feature.d.ts
Module build failed: Error: /Users/nkumar003c/root-module/node_modules/feature/feature.d.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/nkumar003c/root-module/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:709:23)
    at plugin.done.then (/Users/nkumar003c/root-module/node_modules/@ngtools/webpack/src/loader.js:41:31)
```

## Expected behavior

```loadChildren: 'feature#FeatureModule'``` should work on CLI based app.

## Minimal reproduction of the problem with instructions

- Generate a feature module ```ng new test-feature --style=scss```
- cd test-feature/
- Generate a library module ```ng generate library feature --style=scss```
- Update the library module to adde child router in it, to support lazy loading by root module.
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Routes, RouterModule } from '@angular/router';

import { FeatureComponent } from './feature.component';

const routes: Routes = [
  {
    path: '',
    component: FeatureComponent
  }
];


@NgModule({
  imports: [
    RouterModule.forChild(routes)
  ],
  exports: [RouterModule]
})
export class FeatureRoutingModule { }

@NgModule({
  imports: [
    CommonModule,
    FeatureRoutingModule
  ],
  declarations: [FeatureComponent]
})
export class FeatureModule { }
```
- ng build feature --prod &&  cd dist/feature/ && npm unpub -f && npm pub
- ng new root-module --routing
- Update generated ```app-routing.module.ts```
```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

const routes: Routes = [{path: 'feature',
    loadChildren: 'feature#FeatureModule'}];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```
- Now if we do ```ng build``` or ```ng build --prod```, we are getting above error.

## What is the motivation / use case for changing the behavior?

Found a workaround too, to make it working using CLI as shown below, but looking for a correct way, using router only.

quick-start-lib-lazy-loader.module.ts
```
import { NgModule } from '@angular/core';

import { FeatureModule } from 'feature';

@NgModule({
  imports: [
      FeatureModule
  ]
})
export class QuickstartLibLazyLoader {}
```
```
import { QuickstartLibLazyLoader } from './quick-start-lib-lazy-loader.module';
export const routes: Routes = [
  {
    path: 'feature',
    loadChildren: './quick-start-lib-lazy-loader.module#QuickstartLibLazyLoader'
  }
]
```

## Environment

<pre><code>
Angular version: 6.0.3

ng build && ng build --prod
 
For Tooling issues:
- Node version: 8.11.0, 8.9.0
- Platform:  Mac & Windows

Others:
Tried on both Node version & Platform

**Comment by vicb** [comment]
Closing as not related to angular (thanks @trotyl)
