### ISSUE TITLE
Implement a system that behaves the way Angular's lifecycle does

### ISSUE THREAD

**Issue by trichetriche** [angular/angular#25087]
## I'm submitting a...

<pre><code>
[X] Other... Please describe: 
    I am requesting documentation or help for something 
    I have been working on for a long time
</code></pre>

## Current behavior

```` typescript
export class AppComponent extends CustomEvents implements ICustomEvents {
  constructor(public session: SessionService) {
    super(session);
  }

  onCustomEvents() {
    console.log('event triggered');
  }
}
````

## Expected behavior

```` typescript
export class AppComponent implements ICustomEvents {
  onCustomEvents() {
    console.log('event triggered');
  }
}
````

## Others

Current stackblitz : https://stackblitz.com/edit/angular-d2rthq?file=src%2Fapp%2Fmodel.ts

I am posting an issue here out of despair, because I can't find anything about it online. 

My goal is to implement a system that behaves like lifecycle hooks do. I think you can see what I'm talking about with the behaviors written just above.

Right now, I'm only able to perform something similar with a super class. But I would like to get rid of that super class and rely only on interfaces, like lifecycle hooks do. Is this possible at all ?

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by trichetriche** [comment]
Well I did try both, and I got answers one none. I fugred this would be the place to find an answer ...
