### ISSUE TITLE
Router navigateByUrl doesn't fail when provided with wrong url

### ISSUE THREAD

**Issue by endamaco** [angular/angular#25091]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Router.navigateByUrl is resolving the promise with true even if the given URL is not correct

## Expected behavior
Based on API [documentation](https://angular.io/api/router/Router#navigateByUrl) it should

> Returns a promise that:
> 
> resolves to 'true' when navigation succeeds,
> resolves to 'false' when navigation fails,
> is rejected when an error happens.

## Minimal reproduction of the problem with instructions
Please navigate here https://stackblitz.com/edit/angular-xsaim2 click "CLICK ME" and check console output, it will log "navigation ok" and then true, instead of giving an error or loggin false

## What is the motivation / use case for changing the behavior?
This is not compliant to angular's documentation

## Environment

<pre><code>
Angular version: 6.0.9

Browser:
- [ X ] Chrome (desktop) version XX
- [ X ] Chrome (Android) version XX
- [ X ] Chrome (iOS) version XX
- [ X ] Firefox version XX
- [ X ] Safari (desktop) version XX
- [ X ] Safari (iOS) version XX
- [ X ] IE version XX
- [ X ] Edge version XX
 
</code></pre>

**Comment by trotyl** [comment]
The route for `PageNotFound` (`**`) is still a normal route, and the navigation is successful (landed at `PageNotFound`).

**Comment by endamaco** [comment]
You are true, I didn't see that part of the configuration
