### ISSUE TITLE
radio not checked on input type radio in angular

### ISSUE THREAD

**Issue by bitquality** [angular/angular#25098]
I'm submitting a...

[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:

Current behavior
Radio buttons are not checked by default on page load.

Expected behavior
The radio button is checked.

Minimal reproduction of the problem with instructions
Check the radio buttons not working header.
https://stackblitz.com/edit/angular-ymc5es?file=app%2Fapp.component.html

Environment
Angular version: 5.2.8

Browser:

  Chrome (desktop) version 66 Mac
 

For Tooling issues:

Node version: with Angular 5.2.0 and Node 8.6 | with Angular 6.0.0 and StackBlitz Node version
Platform: Mac

**Comment by manklu** [comment]
Simply change
```javascript
myselectedLevel = this.levels[1];
```
to
```javascript
myselectedLevel = this.mylevels[1];
```
