### ISSUE TITLE
Pipe expression bindings

### ISSUE THREAD

**Issue by jonrimmer** [angular/angular#25093]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Pipes are used in templates to transform data. But what if a component wants to make a transformation externally configurable? This isn't easy, because there is no simple way to supply a pipeline as a deferred unit of behavior. You can do it using the templateRef pattern, but this is quite verbose:

```html
<my-component>
  <ng-template #valueFormatter let-value>
    {{ value | percent:'1.3' }}
  </ng-template>
</my-component>
```

## Proposed behavior

I propose that, in property bindings, template expressions beginning with `|` should be automatically turned into a object implementing a `PipeTransform` and bindable to an `@Input()` property of that type.

E.g. if `my-component` was defined as follows:

```js
@Input()
valueFormat: PipeTransform;
```

I could bind to it as follows:

```html
<my-component [valueFormat]="| percent:'1.3'"></my-component>
``` 

And `my-component` could use it in its template as follows:

```html
<li *ngFor="let value of values">{{ valueFormat.transform(value) }}</li>
```

## Minimal reproduction of the problem with instructions

This demonstrates the templateRef solution:

https://stackblitz.com/edit/angular-cegkka

## What is the motivation / use case for changing the behavior?

It would make it easier to write components that visualise semi-arbitrary data, such as charts and data grids, which require the ability to defer some amount of formatting to their parent.

## Environment

<pre><code>
Angular version: 6.0.9

</code></pre>

**Comment by vicb** [comment]
You can probably do something along those lines:
```html
<my-component [valueFormatter]="formatter"></my-component>

<li *ngFor="let value of values">{{ formatter(value) }}</li>
```
