### ISSUE TITLE
Task 'build.http.example' is not in your gulpfile

### ISSUE THREAD

**Issue by vicb** [angular/angular#2509]
Just noticed this on on Travis for Dart build. Does not cause failures.

https://travis-ci.org/angular/angular/jobs/66496356#L2340

**Comment by caitp** [comment]
as mentioned on slack, this was added to the CI tests here https://github.com/angular/angular/commit/21568106b114943b59ce37832d82c8fb9a63285b#diff-4bab36ce25ca1c9d72a7e6010f6e5ea3R19

@jeffbcross is it safe to remove, or is the plan to create a new gulp task for this?

**Comment by jeffbcross** [comment]
I think @matsko removed it from the gulpfile when he added a new task, but must not have removed it from other scripts. Should be safe to remove.

**Comment by jeffbcross** [comment]
I'll take this.

**Comment by jeffbcross** [comment]
@vicb or @caitp just opened PR #2519. I'm going to go out on a limb and say we don't need to wait for Travis for this one. Can one of you give it an LGTM?
