### ISSUE TITLE
Forms: Unable to bind to controls #regression

### ISSUE THREAD

**Issue by jpsfs** [angular/angular#2510]
Hi,

I'm doing some experiments with forms and found an issue. With alpha 26, it seems that the inputs declared inside a control-group are unable to bound with the ones declared inside the component's constructor.

Didn't find anything on the changelog that justifies this, but maybe I'm missing something. Can someone take a look?

I've make a Plunker with an example: http://plnkr.co/edit/vkhFxh?p=preview
(I've left the plunker pointing to alpha-26, just switch to alpha-25 on index.html to see the difference)

Alpha 26:
![image](https://cloud.githubusercontent.com/assets/1041209/8131659/ac158878-1113-11e5-8259-ed877a63745f.png)

Alpha 25:
![image](https://cloud.githubusercontent.com/assets/1041209/8131669/bce9eb76-1113-11e5-85bc-2769ae9cb53b.png)

**Comment by hpinsley** [comment]
I too find the forms module a bit confusing.  I got your plunker to work, though.  See http://plnkr.co/edit/jjsDAx?p=preview

**Comment by vicb** [comment]
The "ng-" prefix is described in the changelog (I agree, it should have been listed under the breaking changes).

Lately the API has been reworked and examples have been. Hopefully you'll find using it easier.
