### ISSUE TITLE
shrinkwrap on master

### ISSUE THREAD

**Issue by vicb** [angular/angular#2511]
@jeffbcross any chance you've run shrinkwrap not on a Mac ?

As stated in the readme, you **must** run it on a mac or the fsevents pkg will get removed (I must admit I run it on Linux & revert fsevents related changes).

see https://github.com/angular/angular/blob/master/npm-shrinkwrap.readme.md, first bulltet

**Comment by jeffbcross** [comment]
Not sure what went wrong; I did run it on Mac. But it looks like the `fs-events`dependency was removed.

**Comment by jeffbcross** [comment]
Though it is a newer machine, perhaps some misconfiguration caused it.

**Comment by jeffbcross** [comment]
I'll submit a PR soon. Looks like I can manually update chokidar to restore `fsevents`
