### ISSUE TITLE
Support @Input/@Output without @Component/@Directive

### ISSUE THREAD

**Issue by jasonaden** [angular/angular#25129]
Current design after discussing with [~arick1], [~benlesh] and [~misko] : [https://docs.google.com/document/d/1w1RYLQGq0vEoHOvAk-xUAuLwhiDl0AI5K9chSwOcsrM/edit?hl=en#heading=h.u0ixplwg5x25](https://docs.google.com/document/d/1w1RYLQGq0vEoHOvAk-xUAuLwhiDl0AI5K9chSwOcsrM/edit?hl=en#heading=h.u0ixplwg5x25)

Original design by Ben Lesh: [https://docs.google.com/document/d/1TWyt6FtkikdMHMjznUPXCQ9fn4cKETntwMSfok3n3J4](https://docs.google.com/document/d/1TWyt6FtkikdMHMjznUPXCQ9fn4cKETntwMSfok3n3J4/edit?disco=AAAACEe9JKE&ts=5b526f9c)

**Comment by mlc-mlapis** [comment]
... make the design docs public, please.
