### ISSUE TITLE
using routerInjectables throws exception

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#2512]
I am unsure why, but after I updated SystemJS I keep getting the following exception when I insert `routerInjectables` on app bootstrap:

```js
bootstrap(App, [
    shadowDomInjectables,
    formInjectables,
    routerInjectables, // this causes the exception in `browser_adapter.es6`
    pipeInjectables,
    serviceInjectables
]);
````
![screenshot 2015-06-12 17 05 52](https://cloud.githubusercontent.com/assets/1479737/8133022/e1f68e58-1125-11e5-9e4e-0b9264decb63.png)

As soon as I remove it from it, I no longer the get the issue. Does anyone have any clue what might cause it?

**Comment by gdi2290** [comment]
are you using a bundle or are you including angular be itself? because it's a problem with EventEmitter which means you're missing RxJS since it can't read Subject of Rx undefined

**Comment by rolandjitsu** [comment]
@gdi2290 I include each dep. separately (zone.js + long-stack-trace-zone.js, rx.js and angular.js). I tried the following:
```js
System.config({
    map: {
        'rx': 'lib/rx.js'
    }
});
```
Maybe that is the issue here ... is there more to add to the System configuration to make it work? Because when I try to use the bundle on [code.angularjs.org](https://code.angularjs.org) I get into trouble with System, complaining about `rx.js`.

**Comment by gdi2290** [comment]
I think you also need to set the format for rx to commonjs for systemjs

**Comment by rolandjitsu** [comment]
@gdi2290 I think this issue can be closed as it is not caused by a bug, it is just a dependency that is missing, as you explained. I've also managed to get around for now with a different setup, until the next alpha version will be released (which I understood will make it easier to include angular).
