### ISSUE TITLE
Protractor with benchpress runner gives TypeError: capsObject.forEach is not a function

### ISSUE THREAD

**Issue by Autushka** [angular/angular#25139]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When try to run protractor e2e tests with benchpress runner
getting an error:
TypeError: capsObject.forEach is not a function

## Minimal reproduction of the problem with instructions
e2e spec sample:

import {browser} from 'protractor';
import {RegressionSlopeValidator} from "@angular/benchpress";

var benchpress = require('@angular/benchpress');
var runner = new benchpress.Runner([
  //use protractor as Webdriver client
  benchpress.SeleniumWebDriverAdapter.PROTRACTOR_PROVIDERS,
  //use RegressionSlopeValidator to validate samples
  {provide: benchpress.Validator, useExisting: benchpress.RegressionSlopeValidator},
  //use 10 samples to calculate slope regression
  {provide: benchpress.RegressionSlopeValidator.SAMPLE_SIZE, useValue: 1},
  //use the script metric to calculate slope regression
  {provide: benchpress.RegressionSlopeValidator.METRIC, useValue: 'scriptTime'},
  {provide: benchpress.Options.FORCE_GC, useValue: true}
]);

describe('initial load performance', () => {
  it('initial load performance', (done) => {
    runner.sample({
      execute: () => {
        browser.get(`/`);
      },
      userMetrics: {
        timeToBootstrap: 'The time in milliseconds to bootstrap'
      },
      providers: [
        {provide: RegressionSlopeValidator.METRIC, useValue: 'timeToBootstrap'}
      ]
    }).then(done, done.fail);
  });
});

## Environment

<pre><code>
Angular version: "@angular/core": "^6.0.3"

Browser:
- [x] Chrome (desktop) version 67
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.8.0
- Platform:  Windows

Others:

</code></pre>

**Comment by mboughaba** [comment]
I am getting the same error

**Comment by benlesh** [comment]
I'm also hitting this trying to test RxJS 7 with benchpress.

**Comment by warpech** [comment]
This was fixed in https://github.com/angular/angular/pull/21399 and https://github.com/angular/angular/pull/21477 but a new version of Benchpress was not released since.

I guess https://github.com/angular/angular/issues/19442 should be followed about the next release.

**Comment by BioPhoton** [comment]
Any updates here?

**Comment by JoostK** [comment]
Closing as this appears to have been resolved in benchpress 0.2.0 (with 0.3.0 being latest at the moment)
