### ISSUE TITLE
typescript 2.9.x problem with @angular-devkit/build-angular and @angular/compiler-cli

### ISSUE THREAD

**Issue by steve3d** [angular/angular#25141]
## I'm submitting a might be a problem, and I don't think this is a bug.

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[x] Other... Please describe:
</pre></code>

## Current behavior
now with angular 6.1 released, the @angular/core now support ts 2.9.x version, but there are still some packages need ts < 2.9.x:
- `@ngtools/webpack` which is needed by `@angular-devkit/build-angular` sill want ts version < 2.9
- `tsickle` which is needed by @angular/compiler-cli, and this is even worse, the latest version of this still need ts < 2.8.

## Expected behavior
all packages should also support ts 2.9, not only @angular/core

**Comment by britvik** [comment]
I noticed that when I upgraded to angular v6.1.0, `@ngtools/webpack` stayed at my previous version v6.0.1 for some reason.

But even manual install of v6.1.0 did not help since the dependency for typescript is wrong in this version anyway:
`@ngtools/webpack v6.1.0 has dependency "typescript": "~2.4.0 || ~2.5.0 || ~2.6.0 || ~2.7.0",`
`@ngtools/webpack MASTER has dependency "typescript": "~2.4.0 || ~2.5.0 || ~2.6.0 || ~2.7.0 || ~2.8.0 || ~2.9.0",`

**Comment by gkalpak** [comment]
`@angular/cli`, [@ngtools/webpack][1] and [tsickle][2] are indeed fixed.
There is still an issue with `@angular/language-service`, but it can be tracked separately in #24865.

[1]: https://unpkg.com/@ngtools/webpack@6.1.1/package.json
[2]: https://unpkg.com/tsickle@0.32.1/package.json

**Comment by sarunint** [comment]
@gkalpak `tsickle` has released 0.32.1, but `@angular/compiler-cli` still depends on `tsickle@^0.30.0`, which still restrict TypeScript version to 2.8. So I don't think this issue is completely solved.

**Comment by steve3d** [comment]
when can we expect a new fixed `@angular/compiler-cli`?

**Comment by gkalpak** [comment]
If everything goes according to plan, there should be a new release next week (probably ~Wednesday).

**Comment by MattJeanes** [comment]
Thanks @gkalpak - can you let us know on this issue when that has been released?

**Comment by simeyla** [comment]
This issue will never be solved.

**Comment by hakimio** [comment]
@simeyla What? It was fixed.

**Comment by Splaktar** [comment]
Fixed in `7.0.0`.
