### ISSUE TITLE
Bug in Chrome, function($event) randomly throws error “can't read property ”value“ of undefined”

### ISSUE THREAD

**Issue by sebastiangug** [angular/angular#25144]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have some buttons which upon inspection seem to be iterated correctly with ngFor and if I inspect them they have the right attributes, however, when I click on them the function in the controller claims the parameter is 'undefined' every now and then, I guess 50-50 most of the time, quite random.

This is the exact error I get: " ERROR TypeError: Cannot read property 'value' of undefined"  at (the line where the attribute is passed as a parameter in the controller)

Everything worked fine when all the logic was within its controller. But I decided to refactor it and use a service + interceptors. For now, I've included the headers and params in the service.

The thing is, everything works fine in Firefox with no errors, Chrome seems to be the only one experiencing this bug. And if I keep clicking on it, it will keep throwing errors for a while until it just works. Here's a screen recording: https://streamable.com/5f7og

Note: If I just wait without clicking again and again -- nothing happens. Looking in the network tab reveals that the http call simply isn't firing at all.

## Expected behavior

Should call the function with the event object passed to the controller function.

## Minimal reproduction of the problem with instructions

1. Have Service to make http calls.
2. Buttons iterated with custom attributes iterated with ngFor based on the data gotten from the GET call.
3. (click) that triggers a function in controller and passing the $event object.
4. Function in the controller that does something using the custom attribute within that $event object.
5. Test in chrome 

## What is the motivation / use case for changing the behavior?

Stuff just doesn't work without this.

## Environment

<pre><code>
Angular version: 6.0.4

Browser:
- [ X] Chrome (desktop) version 68.0.3440.75
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

My code: 

Code below:

Front end:

```
    <div *ngFor="let button of lvl0 | errorfix">

  <!-- Actual buttons reiterated with ngIF -->
  <button mat-raised-button color="accent" [attr.data-param1]=" button['md:0/413349530_Level 0 – Section'] | lvl0clean " class="lvl0button"
    (click)="reveallvl1($event)" (click)="stepper.reset()" (click)="resetAllSteps()">
    {{ button['md:0/413349530_Level 0 – Section'] | lvl0clean }}
  </button>
</div>
```

Service:

```
initialisingDocs() {
let headers = new HttpHeaders();

headers = headers.append(
  "Authorization",
  "Basic " + btoa("SOMETHINGSOMETHING")
);
headers = headers.append(
  "Content-Type",
  "application/x-www-form-urlencoded"
);
return this.http.get(this.ROOT_URL + "initialising", { headers });
}
```

Controller:

```
  constructor(private service: DocsService) {
// Initialising the first set of buttons

this.lvl0 = this.service.initialisingDocs().subscribe(data => {
  this.lvl0 = data;
  console.log(this.lvl0);
});
}

For the next lvl of buttons:

  reveallvl1($event) {
this.service
  .lvl1Docs($event.target.attributes["data-param1"].value) **// <<ERROR LINE>>**
  .subscribe(data => {
    this.lvl1 = data;
    console.log(data);

    this.step1Folder($event.target.attributes["data-param1"].value);
  });
}

```

**Comment by IgorMinar** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists please open a new issue and provide a stackblitz reproducing the problem and describing the difference between the expected and current behavior. You can use this stackblitz project as a starting point: https://stackblitz.com/fork/angular-gitter
