### ISSUE TITLE
two ways binding from parent to grandchild

### ISSUE THREAD

**Issue by zalshabab** [angular/angular#25146]
I am actually trying to reflect the model value through 3 layers ( parent ->child -> grand Child) but i couldn't..
I created a textbox component <input type="text" [(ngModel)]="value" />.
and a addressInfo component which uses the textBox component. I added a two ways binding property. [(address)] to the addressInfo component to hold the model value.
and created bankDetails component which uses addressInfo component. now when i add [(address)] to the value of the model doesnt get reflected to its model . even though i can see that [(address)} on addressInfo component and ngModel at textBox component hold the correct value

Can you please help?

**Comment by zalshabab** [comment]
note: my issue is actually kinda the opposite of #7645 issue

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem)

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
