### ISSUE TITLE
Scrolling to top on navigation broke expected existing behavior

### ISSUE THREAD

**Issue by dope9967** [angular/angular#25145]
## I'm submitting a...

<pre><code>
[ X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I'm using navigation to update URL and trigger data reload for pagination, filtering and sorting of data table. On 6.1.0 it scrolls to the top of the page.

## Expected behavior

Before 6.1.0, navigation didn't scroll to top and that was good behavior in my case, since I'm only changing table contents, so logically I don't need to scroll to top, I can just stay where the data table is. There should be an option, by providing some `NavigationExtras` or router scroll settings, to choose if you want to scroll to top, or stay where you were.

## Minimal reproduction of the problem with instructions

Any kind of navigation scrolls to top now, there's no specific code for this issue.

## What is the motivation / use case for changing the behavior?

I think there is no reason to not leave an option for things to stay as they were before 6.1.0. Preferably an optional runtime setting. I could implement this in some other way, but I'm not even sure how? Save scroll positions myself and pass them through URL parameters or cookies? Don't use navigation, update URL with `location.go` and use `ngOnChanges()` to update data? Those don't seem like some kind of "best practices".

## Environment

<pre><code>
Angular version: 6.1.0

Browser:
- [ X] Chrome (desktop) version 68.0.3440.75
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3  
- Platform:  Linux 

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Try setting it to disabled https://next.angular.io/api/router/ExtraOptions#scrollPositionRestoration

**Comment by dope9967** [comment]
@ericmartinezr 
That did it. Interestingly enough, documentation notes that `scrollPositionRestoration: 'disabled'` is default, but if I don't set anything - `RouterModule.forRoot(routes)` - then the issue appears. Did I incorrectly understood the documentation or this is not intended? Also, even though my case is fixed by this now, it would still be nice to be able to specify scroll behavior not only at application initialization time, but also at navigation by using some additional parameters, and it would be nice to have `scrollPositionRestoration: 'enabled'` without always impacting navigation forward too.

**Comment by ericmartinezr** [comment]
@dope9967 probably the behavior changed while they were coding it and they forgot to update the docs. Leave the issue open so they can clarify the docs (and land it in the main angular.io website). And regarding your second point it would be nice to open a different issue with a feature request (I'm not yet familiarized with the scroll restoration thing so I'm not sure if that option exists at all or not)
