### ISSUE TITLE
@angular/cli version related angular version

### ISSUE THREAD

**Issue by milap-incashme** [angular/angular#25158]
Hello all

I want to know which @angular/cli version supported to which angular?

For example Angular CLI: 1.7.4 support angular 5,
and Angular CLI: 6.0.8 support angular 6.
Same for angular 2, angular 4, and angularjs 1.2 which are the supported version of @angular/cli ?

Also provide me link if possible where I can found all supported version of Angular CLI regarding angular version.

Thanks in advanced.
**Milap**

**Comment by timjklein36** [comment]
If you head over to the `@angular/cli` project, [angular/angular-cli](https://github.com/angular/angular-cli), and select the branch that corresponds to whichever version you are looking for (for example, [`1.7.X`](https://github.com/angular/angular-cli/tree/1.7.x) - `1.7.4` being the latest, you can check the [`package.json` file](https://github.com/angular/angular-cli/blob/1.7.x/package.json) for instances in the `devDependencies` or `dependencies` of `@angular/core`.

This will tell you what version will be installed when you install that particular version of the CLI. (In the example case, `@angular/cli@1.7.4` corresponds to `@angular/core@^5.2.0`.

***Note:*** *You can switch to `Tags` in the branch selection drop-down to select specific versions to check older patches (for example, [`v1.7.1`](https://github.com/angular/angular-cli/tree/v1.7.1).*

**Comment by IgorMinar** [comment]
As of v6 the major versions of the framework and cli are in sync, so to use framework 6.x.x use cli version 6.x.x.
