### ISSUE TITLE
Custom headers from Angular App not sent to web api back-end

### ISSUE THREAD

**Issue by lorenz31** [angular/angular#25159]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Here's an issue I posted on stackoverflow:
https://stackoverflow.com/questions/51496530/angular-custom-header-not-sent-seen-to-web-api

The custom HttpHeaders I set in my code are not sent/visible to my web api back-end.
Example:
let headers = new HttpHeaders().set("Content-Type", "application/x-www-form-urlencoded").set("client_id", this.clientapphelper.getClientApp());

Where **client_id** is my custom header.

I've tried the options that I found while Googling but none of them fixed my issue.

## Expected behavior

Back-end should be able to receive custom header passed from Angular app

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by mlc-mlapis** [comment]
@lorenz31 ... please, read the docs ... headers are immutable ... you can't mutate them.

**Comment by lorenz31** [comment]
@mlc-mlapis What I'm trying to do is something like this:
https://stackoverflow.com/questions/45286764/angular-httpclient-doesnt-send-header/45286959#45286959

**Comment by timjklein36** [comment]
As @mlc-mlapis has said, check out [this page in the docs](https://angular.io/guide/http#adding-headers).

Your code seems correct at first inspection, since `set()` returns an instance of `HttpHeaders` with the new header that you pass as an argument.

You could try to open the dev tools of your browser when testing the request just to see if the headers are being sent to the back-end and it is not an issue with your back-end software (could be your code, server, hosting platform).

If you can't get the `set()` method to work, you could try to pass the headers as an object to the constructor, like so:

```javascript
let headers = new HttpHeaders({
    'Content-Type': 'application/x-www-form-urlencoded',
    'client_id': this.clientapphelper.getClientApp()
});
```

Another option is to set up an `HttpInterceptor` to check the request before it goes out to the server to ensure the headers are set there.

**Comment by lorenz31** [comment]
@timjklein36  I've already using `HttpInteceptor` and the code you just showed but no luck.

**Comment by timjklein36** [comment]
@lorenz31 Any indication of the header in [dev tools](https://developers.google.com/web/tools/chrome-devtools/network-performance/reference) when you make the request?

**Comment by mlc-mlapis** [comment]
@lorenz31 ... `set()` creates and returns a new `HttpParams` instance, **without mutating the instance** on which `set()` is called.

**Comment by lorenz31** [comment]
@timjklein36 Can't see the client_id being passed.

**Comment by timjklein36** [comment]
@lorenz31 Without seeing more of your code, I can't really suggest anything else. I am not sure what is going wrong.

@mlc-mlapis If you actually look at the assignment line that @lorenz31 posted in the original answer, it is correct.

```javascript
let headers = new HttpHeaders()
    .set("Content-Type", "application/x-www-form-urlencoded")
    .set("client_id", this.clientapphelper.getClientApp());
```

- `new HttpHeaders()` creates a new instance of `HttpHeaders`
- `set("Content-Type", "application/x-www-form-urlencoded")` creates and returns a new instance of `HttpHeaders` with the all of the previous headers from the instance on which it was invoked (none) **plus** the header supplied as an argument (`Content-Type`)
- `set("client_id", this.clientapphelper.getClientApp())` does the same as the previous call resulting in the return of an instance of `HttpHeaders` with two headers applied (`Content-Type` and `client_id`)

**Comment by mlc-mlapis** [comment]
@lorenz31 ... back on the beginning. I tried the following code ... right now ... and it works:
```
const headers = new HttpHeaders({
   'x-custom-version': '1',
   'x-custom-data-request': '...'
});
headers = headers.set('x-foo', 'bar').set('x-debug', '123');

```

**Comment by lorenz31** [comment]
@mlc-mlapis Can you post a screenshot?

**Comment by timjklein36** [comment]
My best guess is that it has to do with the `_` in your desired custom header. It is possible that `client_id` is not a valid header key, but I am not sure.

Try using `client-id` instead...

**Comment by timjklein36** [comment]
@lorenz31 Have a look: [`nginx` underscore headers](https://stackoverflow.com/a/22856867/4362829) and [`requests/requests` underscore headers](https://github.com/requests/requests/issues/1292).

I would assume there is some similar (albeit possibly arbitrary) restriction on using underscores in HTTP Headers.

**Comment by mlc-mlapis** [comment]
@lorenz31 ... just test the simple `dash` instead of `underscore` and you'll see how it's going ...

**Comment by lorenz31** [comment]
Hi guys. Problem solved. You were right. Using dash instead of underscore made it work. 👍
