### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by truimagz** [angular/angular#25154]
## I'm submitting a...

<pre><code>
[X] Bug report  
</code></pre>

## Current behavior
TypeError: Cannot read property 'indexOf' of undefined

ngsw-worker.js:386

this.config.urls.indexOf(url)

## Expected behavior
Should be able to bypass...

(this.config.urls || "").indexOf(url)

## Minimal reproduction of the problem with instructions
Unable to fulfill "urls" attribute

## What is the motivation / use case for changing the behavior?
To allow the worker to function without having "urls" attribute

## Environment

<pre><code>
Angular 5.1.0

Browser:
ALL

**Comment by SukhyAnand** [comment]
Can anybody review the code changes uploaded. Thanks.

**Comment by gkalpak** [comment]
AFAICT, `config.urls` can never be undefined, since this field is [auto-generated][1]. Having an asset group with no URLs is invalid anyway.

[1]: https://github.com/angular/angular/blob/8f81dba367912d5c905dcd90893475e563bc2eea/packages/service-worker/config/src/generator.ts#L77
