### ISSUE TITLE
DI API examples use deprecated ReflectiveInjector instead of static Injector

### ISSUE THREAD

**Issue by jbogarthyde** [angular/angular#25153]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
The following pages use ReflectiveInjector in the examples:

https://angular.io/api/core/InjectionToken
https://angular.io/api/core/Injector

## Expected behavior
Use static create() fn as recommended in the deprecation note for ReflectiveInjector.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by brandonroberts** [comment]
Fixed via https://github.com/angular/angular/pull/25162
