### ISSUE TITLE
AIO search matches on pages that don't contain the search keyword

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#25156]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ X] Other... Please describe: AIO search
</code></pre>

## Current behavior

The Angular site search sometimes matches on pages that don't contain the desired search phrase in any visible text. 

## Expected behavior

The Angular site search only matches on pages that contain the desired search phrase in visible text. 

## Minimal reproduction of the problem with instructions

1. Go to angular.io
2. In the site search, enter "reflective"
3. Search results include 11 guide and 2 tutorial matches
4. Go to either of the tutorial matches. 
5. Use the *browser search feature* to search *in-page* for "reflective". 
6. The only match is the word "reflective" in the AIO site search field. 

Repeat steps 4-6 for both tutorial files and at least the first 6 guide matches. 

## What is the motivation / use case for changing the behavior?

Fewer false positives in search. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

Related issue: https://github.com/angular/angular/issues/23655

You can't reliably highlight search matches (described in 23655) unless you only match on the same files that the browser would match on. 

</code></pre>

**Comment by IgorMinar** [comment]
both of the tutorial pages include words "reflects" or "reflected", which once normalized matches the keyword "reflected".

not doing this kind of normalization would result in lots of queries not match anything at all so that is desirable, but I wonder if we could rank the results better since the most important result "reflective forms" is kind of buried on the search result page.

**Comment by jenniferfell** [comment]
Good point.

Definitely, the exact matches should be at the top of the list. 

Also, we need to enable use of "" for literal strings so we can do literal word or word phrases. Then I could search for "reflective" in the case above. And I could search for "reactive forms" and get exact matches on that complete phrase, instead of matches on every variant of the word reactive and the word form.

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
