### ISSUE TITLE
Nullable variables in Constructors causes AOT to not include the injected Module Type

### ISSUE THREAD

**Issue by darthmolen** [angular/angular#25151]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Nullable constructor variables in services for injectable classes causes AOT transpiler to not include the Module in question.

## Expected behavior

Nullable variables in constructors / Modules should be included for AOT transpilation.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/service-with-nullable-constructor?file=main.ts

Here is an example app that has a nullable constructor in a service for ngx-pwa/localStorage. Stackblitz doesn't have AOT compiling, but this can be a basis to quickly see the issue locally using ng build --prod --source-maps. ngx-pwa/localstorage will no longer be in the source maps after the build finishes.

## What is the motivation / use case for changing the behavior?

Nullable as a variable type means it might be null, or it might not. If the AOT does not include the module in question because it's variable declaration was marked nullable, it breaks 50% of the use case for a nullable variable.

## Environment

Production

<pre><code>
Angular version: 6.0.9
Angular CLI: 6.12.0-rc.3

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.2.0  
- Platform: Windows  
</code></pre>

**Comment by mhevery** [comment]
Please provide reproduction steps. Where should I click, what should I expect to happen, what happens instead. We have a lot of issues to look at and without detailed reprod steps we don't have time to reverse engineer your example. Please make it easy for us.

**Comment by darthmolen** [comment]
I went down the reproduction steps path locally with a test project. upgraded to 6.1. could not reproduce.
