### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error: Template parse errors: Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.) ("

### ISSUE THREAD

**Issue by manzerProgen001** [angular/angular#25164]
Hi,
I am trying to implement as below in .html(template) of angular4 (image attached for code)
![code](https://user-images.githubusercontent.com/31919831/43196509-c0b7581c-9025-11e8-88b1-b67261590ce9.png)

But getting error as:-

ERROR Error: Uncaught (in promise): Error: Template parse errors:
Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.) ("
    </code>
  </div>

Kindly someone help me fixing the bug.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
