### ISSUE TITLE
Service Testing for post / mock backend - Where are the docs / examples https://angular.io/guide/http#testing-http-requests

### ISSUE THREAD

**Issue by chrisj-skinner** [angular/angular#25168]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Looking for documentation on the new mock backend (depreciated - https://angular.io/api/http/testing/MockBackend). Recommends going to -> 
https://angular.io/guide/http#testing-http-requests but there's no examples of a new mock backend / post testing setup

## Environment

<pre><code>
Angular version: 6.0.1

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.11.1
- Platform: Mac

Others:

</code></pre>

**Comment by jenniferfell** [comment]
Hi. Thanks for submitting this issue. May I ask a question for clarification?

https://angular.io/guide/http#testing-http-requests
seems to include all the steps and example code snippets to set things up so the HTTP backend is mocked so your tests can simulate interaction with a remote server. There are also links to a live example and downloadable code. That section uses @angular/common/http/testing, which is the replacement for the deprecated @angular/http/testing.

Can you offer more specifics about what you want to see that was missing?

**Comment by jenniferfell** [comment]
Note for myself: This is related to at least one other issue about ensuring the docs for @angular/common/http are complete and that replacement APIs are clear for all deprecated @angular/http APIs. See also https://github.com/angular/angular/issues/24597

**Comment by chrisj-skinner** [comment]
No POST examples @ https://angular.io/guide/testing - only GET examples

**Comment by chembu** [comment]
Example test cases are available under common/http/test folder

**Comment by kapunahelewong** [comment]
thank you for helping with this, @jsonRUHLS!

**Comment by petebacondarwin** [comment]
This has not got much community support.
There was a PR that went stale and was closed https://github.com/angular/angular/pull/33263. If anyone wants to take that on to improve the docs then feel free to put up a new PR.
Meanwhile I'll close this as the docs team are not likely to get round to adding these examples.
