### ISSUE TITLE
aio - github icon cropped on mobile

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#25167]
The recently added GitHub icon on the top-right corner gets cropped on some mobile devices.
(Apparently works on iPhone 6/7/8 plus :smiley:)

On Galazy S5 (it looks similar on my S8):
![aio-galaxy-s5](https://user-images.githubusercontent.com/8604205/43337429-919d669e-91dc-11e8-926a-e53225af8806.png)

On iPhone X (😱):
![aio-iphone-x](https://user-images.githubusercontent.com/8604205/43337432-941cc7ca-91dc-11e8-9bca-5e51bcb51198.png)

cc @sjtrimble

**Comment by CHBaker** [comment]
I could take this issue

**Comment by sjtrimble** [comment]
I believe this was taken care of with PR #25181 and should be closed.
