### ISSUE TITLE
Typo in Tutorial - section 8 HTTP

### ISSUE THREAD

**Issue by ErezT** [angular/angular#25179]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

https://angular.io/tutorial/toh-pt6#add-heroserviceaddhero
On the second bullet there is a typo:
"it expects the server to generate**s** an id for the new hero..."

## Expected behavior

"it expects the server to generate an id for the new hero..."
No s at the end of generate

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dariobraun** [comment]
Not sure if the old PR is still active, so I made a new one. Feel free to merge whichever PR you like so this issue can be closed :)
