### ISSUE TITLE
Angular " OrderBy: '' " (empty string) no longer sorting by index

### ISSUE THREAD

**Issue by TheMcMurder** [angular/angular#2517]
In previous versions of Angular (1.2) when you passed an empty string to the OrderBy in an ng-repeat it would order by the index of each item in the array.

Now (1.3.15 & 1.4.0) it orders very differently. [This plunk](http://plnkr.co/edit/WSVdJq7unEEElo9LBzzr?p=preview) shows 1.2, 1.3.15, and 1.4.0 and how the order by functions differently in each case. 

It should order by index if OrderBy isn't specified.

**Comment by vicb** [comment]
This repo is for angular 2, please reopen on https://github.com/angular/angular.js
