### ISSUE TITLE
Is email validation outdated?

### ISSUE THREAD

**Issue by ghost** [angular/angular#25186]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

According to https://github.com/angular/angular/issues/18985, EMAIL_REGEXP must match the HTML spec.

[Current version](https://github.com/angular/angular/blob/6.1.0/packages/forms/src/validators.ts#L58): 
```
/^(?=.{1,254}$)(?=.{1,64}@)[-!#$%&'*+/0-9=?A-Z^_`a-z{|}~]+(\.[-!#$%&'*+/0-9=?A-Z^_`a-z{|}~]+)*@[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*$/
```

[WHATWG version](https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address)
```
/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/
```

The WHATWG version is ~50 characters shorter than the current version.

I think the EMAIL_REGEXP is outdated. But if the current version is correct, the reason of the difference should be documented.

**Comment by gkalpak** [comment]
It's not outdated. It is an enhanced version :grin:
Basically, the email regex is ported over [from AngularJS][1].

##
A little background:

A while back, the AngularJS regex looked [almost identical][2] to the WHATWG one (save for some domain name length restrictions).

Then, in angular/angular.js@f3f5cf72e, the regex was enhanced to incorporate more RFC rules (e.g. related to domain names, etc). The commit message has more details.

##
There is no such thing as a perfect email regex, so either one is as good imo.
👍 for documenting what it does, though (even if just a high-level overview; one can always find the full details in the source code :grin:).

[1]: https://github.com/angular/angular.js/blob/c133ef8360c81c9f42713616e6ac8414c0e119c0/src/ng/directive/input.js#L27
[2]: https://github.com/angular/angular.js/blob/2274dc7bb70ae533834a76cfcde8ce8c78888f1f/src/ng/directive/input.js#L27

**Comment by Naveen562117** [comment]
Validators.pattern('([a-zA-Z0-9.!#$%&’*+/=?^_{|}~-]+@[a-zA-Z0-9-]+[.](?:\[a-zA-Z0-9-]+))')

validators pattern for email

**Comment by mlc-mlapis** [comment]
@Naveen562117 ... on a project you usually have your own validation set of validators (mainly because of your own rules for returned errors data structures) where the built in ones you wrap into (+ maybe enhance by your concrete needs).

**Comment by Naveen562117** [comment]
"validators.email" is accepting the 
email ID such as 
"example@gmail"
which is invalid without .com at the end 
example@gmail.com 
is the valid 
 this was the issue i found 
 
and the solution i for this issue is this:
`Validators.pattern ('([a-zA-Z0-9.!#$%&’*+/=?^_{|}~-]+@[a-zA-Z0-9-]+[.](?:\[a-zA-Z0-9-]+))')`

which is accepting the email id

**Comment by maxkorz** [comment]
@Naveen562117 email `example@localhost` is technically valid.

**Comment by trotyl** [comment]
@Naveen562117 `example@gmail` is a valid email address which has been answered for many years:

https://stackoverflow.com/questions/20573488/why-does-html5-form-validation-allow-emails-without-a-dot

An application could use stricter rule for its business requirement, but that won't change what a valid email is.

**Comment by ponkys** [comment]
It seems that the discussion here is over and the issue can be closed.

**Comment by maxkorz** [comment]
@ponkys no. As @gkalpak has pointed out, lack of documentation about what the current regexp does, should be addressed.

**Comment by ponkys** [comment]
@maxkorz You are right about the tests and I agree with you but in terms of documentation, I think the Angular team doesn't need to explain everything they do if it takes a search on google to understand what a valid email is. Looking forward to the final decision about this here.

**Comment by scottseeker** [comment]
@ponkys Disagree.  The email validator does not match the rules provided by the RFC (2822?).  Because of that, I have no idea what their email validator does.  On a project with very specific requirements it would be nice to know without guessing/checking.

For instance their built in validator does not allow " or \ characters and fails against some international characters.

**Comment by ponkys** [comment]
@scottseeker Thanks for pointing this out.
