### ISSUE TITLE
Angular Elements is not working in mozilla firefox on chrome any help?

### ISSUE THREAD

**Issue by richard457** [angular/angular#25199]
[ ] Other... Please describe:
</code></pre>

## Current behavior

Only Work in google chrome

## Expected behavior
Expected to work in all browser

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ yes] Chrome (desktop) version XX

- [no ] Firefox version XX
- [ no] IE version XX

For Tooling issues:
- Node version: v8.9.4
- Platform:  Linux ubuntu

**Comment by sarunint** [comment]
https://caniuse.com/#feat=custom-elementsv1

Custom Elements API is behind a flag in Firefox.

That means no web components will work on Firefox without a polyfill.
