### ISSUE TITLE
[Question] Write a structural directive but display none

### ISSUE THREAD

**Issue by BennieMeng** [angular/angular#25192]
i try to write a directive by myself ,below part of code,
`
import {Directive, ElementRef} from '@angular/core';
@directive({selector: '[light]'})
export class LightDirective{
   constructor(el: ElementRef) {
   el.nativeElement.style.backgroundColor = 'green';
}
`

alse had declarated on NgModule declarations. and bind to one element, such as
`<span *light>123</span>`
i can get information inside constructor , but the element display none , and only `<!-- -->` left,
what's wrong with my step, can you help me ?

**Comment by mlc-mlapis** [comment]
@BennieMeng ... because it is supposed that the structural directive will do it itself, like the following simple `embed` directive:
```
@Directive({
	selector: '[embed]'
})
export class EmbedDirective implements OnInit, OnDestroy {
	private _viewRef: ViewRef;
	constructor(
		private _containerService: ContainerService,
		public tpl: TemplateRef<any>
	) {}
	ngOnInit() {
		this._viewRef = this._containerService.vcr.createEmbeddedView(this.tpl);
	}
	ngOnDestroy() {
		this._viewRef.destroy();
	}
}
```

**Comment by BennieMeng** [comment]
@mlc-mlapis  do you mean i must use containerService to rebuild dom, and how can i get the element bind this directive.

**Comment by mlc-mlapis** [comment]
@BennieMeng ... `ContainerService` is my own service, it's ...
```
import { Injectable, ViewContainerRef } from '@angular/core';

@Injectable()
export class ContainerService {
	vcr: ViewContainerRef;
}
```
but the key for a structural directive is ...
```
constructor(
	public tpl: TemplateRef<any>
) {}
```
because ...
```
<ng-container *embed="myProp">
	<ul>
		<li>{{myProp.One}}</li>
		<li>{{myProp.Two}}</li>
	</ul>
</ng-container>
```
that syntax is translated by Angular compiler to ...
```
<ng-template [embed]="myProp">
	<ul>
		<li>{{myProp.One}}</li>
		<li>{{myProp.Two}}</li>
	</ul>
</ng-template>
```
Read more ... https://angular.io/guide/structural-directives

**Comment by mahendralife** [comment]
@BennieMeng , you need to use ViewContainerRef for structural directive for manipulate native element 

see below example:

import { Directive, TemplateRef, ViewContainerRef } from '@angular/core';

@Directive({
  selector: '[light]'
})
export class LightDirective {
  private  element;
  constructor(
    private _containerService: ViewContainerRef,
    public tpl: TemplateRef<any>
  ) {

    this.element = this._containerService.createEmbeddedView(this.tpl)['rootNodes'][0];
    this.element.style.backgroundColor = 'green';

  }
}


--HTML--
   <div *light>  <span>123</span></div>
    or
   <div *light> 123 </div>

**Comment by BennieMeng** [comment]
@mahendralife thanks, it works by your suggest. i get little about why we must createEmbeddedView template, it maybe need to change the dom construction like to add ng-template and soso.

**Comment by mahendralife** [comment]
if you need to use  structural directive and access  access DOM nativeElement  you must have create dynamic view using createEmbeddedView.
for more information visit below links:

https://angular.io/guide/structural-directives
https://angular.io/api/core/ViewContainerRef

**Comment by BennieMeng** [comment]
@mahendralife when i try to bind eventlistener, what i need to pay attention to ?
`@HostListener('mouseenter') enterEvent() {
     console.log('enter');
   }`,
such as, i can't see enter in my console

**Comment by mlc-mlapis** [comment]
@BennieMeng ... please, don't use this issues channel for private communication. ⛔️

**Comment by BennieMeng** [comment]
@mlc-mlapis  i has set title beginning with a question, i need help and share. sorry for trouble~

**Comment by mlc-mlapis** [comment]
@BennieMeng ... how is `@HostListener` related to a structural directive? Just don't open unrelated things ... keep focus on the main theme ... and avoid to use this channel just for questions when you don't know something. There is mainly Gitter channel for it.

**Comment by BennieMeng** [comment]
get it, it is hard to word follow demo by searching online, i will research on it .

**Comment by mlc-mlapis** [comment]
@BennieMeng ... on Gitter channel just ask ... https://gitter.im/angular/angular ... usually there is always somebody who can help you. But be prepared ... prepare the formulation of your question to allow others to understand. Also if you have some concrete problem ... create an online simple reproduction of it on https://stackblitz.com ... so then anybody can play immediately with it.
