### ISSUE TITLE
docs: Services Tutorial, --module is no longer available

### ISSUE THREAD

**Issue by firrae** [angular/angular#25196]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently the documentation found here: https://angular.io/tutorial/toh-pt4 mentions the command:
`ng generate service hero --module=app`. When run using CLI version 6.1.0, the same version as the documentation I have selected, the CLI returns:
```
Schematic input does not validate against the Schema: {"module":"app","flat":true,"spec":true}
Errors:

  Data path "" should NOT have additional properties(module).
```

## Expected behavior

This should likely be removed and changed to describe the difference between using `{ providedIn: 'root' }` and defining the service in the `providers` array of the module definition.

## What is the motivation / use case for changing the behavior?

The documentation should represent the actual abilities of the current toolset.

## Environment

<pre><code>
Angular version: 6.1.0
Angular-CLI version: 6.1.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.7.0  
- Platform: Mac 

Others:
N/A

</code></pre>

**Comment by brandonroberts** [comment]
This is not an issue with the docs, but with the Angular CLI and should be filed at https://github.com/angular/angular-cli

**Comment by firrae** [comment]
@brandonroberts it looks like the CLI team has removed this functionality meaningfully; https://github.com/angular/angular-cli/pull/10476#issuecomment-385123209. Their documentation has also been updated to show it is no longer available: https://github.com/angular/angular-cli/wiki/generate-service.

This functionality seems to not be coming back so the docs should reflect this, shouldn't it?

**Comment by brandonroberts** [comment]
@firrae Thanks for the link. We'll need to sweep the docs for any other occurrences also.

**Comment by firrae** [comment]
@brandonroberts That was the only that I saw, but it would likely be best. Otherwise, my only other thing, if this section is being looked at, would be to elaborate on why `providedIn: 'root'` should be the default go to. I know the tutorial as it is made me try to use `providedIn: <MyModule>` and ended up confused due to the circular reference issue that generates. The longer issue #10170 ended up clearing it up for me where the documentation didn't make things fully clear.

Just an added thought though, the main thing is fixing that reference so people like me don't try it and just think it's all broken 😝

**Comment by brandonroberts** [comment]
@firrae we are looking at updating the rationale of when you would use `providedIn: 'root'` vs `providedIn: SomeModule`. The short of it is, pretty much always use `providedIn: 'root'`. Using `providedIn: SomeModule` makes more sense for library authors because its provide the benefit of tree-shakable providers for parts of the library that a consumer might not use.

Would you like to submit a PR with a fix for the service command? We are looking a

**Comment by firrae** [comment]
@brandonroberts I managed to figure it out, mostly, after reading more about it over the weekend.

As for a PR I can look at doing one up at work tomorrow to update the command. Though I don't think I understand enough to explain the `providedIn` stuff so I'll just leave that for someone smarter than I.

**Comment by firrae** [comment]
I guess the remainder of this issue is potentially resolved with #21915 unless that bug/fix tag means something more?

**Comment by brandonroberts** [comment]
That's correct. Closing as resolved by https://github.com/angular/angular/pull/25223

**Comment by brandonroberts** [comment]
Thanks for the PR!

**Comment by firrae** [comment]
No problem, thanks for helping me help!
