### ISSUE TITLE
[Feature Request] Module flag for excluding / tree shaking dev modules from the build

### ISSUE THREAD

**Issue by oleersoy** [angular/angular#25195]
During development with Ngxs we usually use the imports:

    import { NgxsReduxDevtoolsPluginModule } from '@ngxs/devtools-plugin';
    import { NgxsLoggerPluginModule } from '@ngxs/logger-plugin';

IIUC these should be removed for production builds.  It would be great if the angular CLI automatically excluded them via a flag or perhaps by reading `package.json`, and removing all dependencies that are dev scoped.

**Comment by IgorMinar** [comment]
I suggest you use environment files to create a list of modules that are dev-time only and import that list in your main.ts. Having an explicit magical support for this would be a bit too magical and could lead to weird issues.
