### ISSUE TITLE
KeyValuePipe interpreting object's number keys as strings when sorting

### ISSUE THREAD

**Issue by adama357** [angular/angular#25202]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When using the KeyValuePipe to sort objects with number keys, the keys are sorted as strings instead of numbers.

## Expected behavior
The number keys should be sorted as numbers, not strings.  (Looking at [defaultComparator](https://github.com/angular/angular/blob/master/packages/common/src/pipes/keyvalue_pipe.ts), it looks like this is supposed to be working, but for some reason it isn't.)  The sorting currently works correctly with Maps, but not objects. 

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular6-keyvaluepipe-demo-iylgej

## Environment

<pre><code>
Angular version: 6.1.0

Browser:
- [x] Chrome (desktop) version 68
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vicb** [comment]
Welcome to JavaScript ;)  

see https://stackoverflow.com/questions/3633362/is-there-any-way-to-use-a-numeric-type-as-an-object-key for more details.

(This is a limitation of the langage - nothing we can do here)
