### ISSUE TITLE
Feat: Add support for TypeScript 3

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#25200]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Supports up to 2.9.x

## Expected behavior
Support typescript V3.

## What is the motivation 
Today Typescript 3 was officially released.

What’s new: 
https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript

**Comment by sarunint** [comment]
[As the team had said](https://blog.angular.io/angular-v6-1-now-available-typescript-2-9-scroll-positioning-and-more-9f1c03007bb6), v6.1 will be the last minor release for v6.x, I think we'll see Angular with TypeScript 3.x support in Angular v7.

That's just my speculation, though.

Side note, it's quite hard to keep up with TypeScript releases because TS introduces breaking changes (to the API) even in minor releases.

**Comment by Teamop** [comment]
But currently, there's an issue with typescript 2.9.2 which will break the auto import feature for javascript and typescript which is a little annoying for developers.
And based on the [issue in vs code](https://github.com/Microsoft/vscode/issues/53597) and https://github.com/Microsoft/TypeScript/issues/23230, currently the only way is to upgrade to 3.0, or just downgrade.

**Comment by VovanSuper** [comment]
Also... some bigger Angular projects are written by dedicating parts of those into Angular Libs; Ts3 brings new features ("composite", "declaration" tsconfig flags, /// <reference lib="..." /> directive) for such cases (afaiu), which would bring even better experience...

**Comment by mhevery** [comment]
PRs welcome.

**Comment by alan-agius4** [comment]
Most likely we'll also have to wait until tsickle supports TypeScript 3 
https://github.com/angular/tsickle/issues/868

**Comment by krokofant** [comment]
@alan-agius4 Why close this?

**Comment by albohlabs** [comment]
@krokofant In favor of a PR https://github.com/jhipster/generator-jhipster/pull/8161

**Comment by albohlabs** [comment]
@krokofant have a look at this PR https://github.com/angular/angular/pull/25275

**Comment by alan-agius4** [comment]
Issue closed as PR was merged.

**Comment by krokofant** [comment]
@alan-agius4  I only see the PR as closed and not merged. 😕

**Comment by alan-agius4** [comment]
That's because it was cherry-picked.

**Comment by dalu** [comment]
so which release version is ts>=3 in now?

**Comment by alan-agius4** [comment]
It’s currently in RC state
https://github.com/angular/angular/blob/master/CHANGELOG.md#700-rc0-2018-09-28
