### ISSUE TITLE
Typo in injectable provider docs

### ISSUE THREAD

**Issue by dariobraun** [angular/angular#25211]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The following sentence is missing an "s" at the end of the word "live" --> wrong conjugation.

> In this sample app, the HeroComponent is created when the application starts and is never destroyed so the HeroService created for the HeroComponent also live for the life of the app.

## Expected behavior

The word "live" should be "lives", as there is only one `HeroService` --> right conjugation.

> In this sample app, the HeroComponent is created when the application starts and is never destroyed so the HeroService created for the HeroComponent also live**s** for the life of the app.

## Minimal reproduction of the problem with instructions

Go to: https://next.angular.io/guide/dependency-injection#injectable-ngmodule-or-component

**Comment by jenniferfell** [comment]
Thanks. Good catch!

This should be fixed by https://github.com/angular/angular/pull/21915

**Comment by FrederikSchlemmer** [comment]
@jenniferfell @jbogarthyde  I think the issue can be closed because the pull request #21915 is merged.
