### ISSUE TITLE
[Feature] Default providers and profiles

### ISSUE THREAD

**Issue by gagle** [angular/angular#25218]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
If we want to follow SOLID principles we need to create an abstract class as interface and a implementation of this class and then use a module to set the providers like so:

```typescript
@Injectable({
  providedIn: ReportModule 
})
abstract class ReportService {
  // abstract functions...
}

@Injectable()
class HTMLReportService implements ReportService {
  // implementation abstract classes
}

@NgModule({
  providers: [
    {
      provide: ReportService,
      useClass: HTMLReportService
    }
  ]
})
export class ReportModule {}
```

This way we can inject `ReportService` into other classes and get an instance of `HTMLReportService`.

So far so good. But encapsulation gets broken. Consumer clients need to know ALL injectable classes to provide an implementation.

A real scenario is when we have Stub classes for every service that communicates with an API for automated tests, so we need to select at compile time by using the `environment.ts` file which classes are provided.

If we scale this, we get an unmaintanable app.module.ts file with plenty of providers. We can use feature modules to try to mitigate this but we're always obligated to select explicitly which class to use. Furthermore, `environment.ts` increments in size for each provider that we need to select. **We need to avoid centralized files.**

## Proposal
Implement default providers and provider profiles. Something like this:

```typescript
@Injectable({
  providedIn: 'root'
})
abstract class ReportService {
  // abstract functions...
}

@Injectable({
  providedWith: ReportService // We select which interface implements
  profile: 'default' // Use the default profile, this line can we also removed if profile is 'default'
})
class HTMLReportService implements ReportService {
  // implementation of  abstract functions
}

@Injectable({
  providedWith: ReportService,
  profile: 'file'
})
class FileReportService implements ReportService {
  // implementation of abstract functions
}
```

And then somehow, if nothing else is configured, when resolving `ReportService` it will be returned an instance of `HTMLReportService`.

We also need a mechanism to select which profile gets injected.

For example:

Per App:

```typescript
platformBrowserDynamic({
  profiles: ['file', ...other profiles]
}).bootstrapModule(AppModule)
```

Per Module:

```typescript
@NgModule({
  profile: 'file' // 'file' profile will be used for any injectable that is providedIn the module
})
export class ReportModule {}
```

**Comment by trotyl** [comment]
Not feasible, all decorator must be pure and cannot break tree-shaking, so `profile: 'file'` cannot perform any side-effect outside the `ReportModule` class. While nothing is importing `ReportModule`, it got removed from runtime and doesn't exist at all.

**Comment by gagle** [comment]
The syntax used in the example is just to show my intentions. The thing is that default providers and by extension profiles is a missing feature that is in another frameworks like spring boot.

**Comment by trotyl** [comment]
@gagle Java type is reflectable and types in package is inspectable, this is not the case in JavaScript. Any type must be referenced directly, that's the basic design principle in JavaScript.

**Comment by gagle** [comment]
@trotyl I believe this feature can be tree-shakeable with some imagination. Angular uses decorators to store metadata. The key is to use some set of classes to decouple the interface and the providers. In this set of classes is where magic happens and this set of classes are used in the `environment.ts` file and select the profile, so the imports occur here, and because env files are replaced at compile time, the other unused providers get removed from the final build by aot. So if profiles cannot be put in the bootstrap or any decorator, you can use environment file.

```typescript
// environment.ts

ProviderProfileSelector.use(ReportModule, ['file']); // 'default' is always included
```

**Comment by trotyl** [comment]
@gagle You cannot achieve that by string token, but only type reference. Like:

```typescript
import { ReportModule } from '???'
import { FileReportService } from '???'

ProviderProfileSelector.use(ReportModule, FileReportService);
```

Without a reference `FileReportService` is not accessible.

**Comment by mhevery** [comment]
I don't thing this is feasible as @trotyl pointed out because it would break tree-shaking. The "some imagination" part is the crux of it. 

Closing as will not implement.
