### ISSUE TITLE
[(ngModel)]

### ISSUE THREAD

**Issue by swaroopbabaleshwar** [angular/angular#25217]
`<input  [id]="textFilterValue" [(ngModel)]="filtersDetails.value"         (ngModelChange)="getSearchDetails(in)"  name="{{inputNum}}" type="text"   [ngbTypeahead]="search"  />`

in this when ever i type a character it will give suggestion and if i select an item from the suggestion list it will be appeared in the input text box and also it will be binded to the filtersDetails variable.

 there is another input text box wch is just below to the other one (above), it also works as the above input box. but there is a add button just next to it, when i press that button item from the 2nd input text box value will be appended to the fist input box text content.

at this point filtersDetails variable holds the only value selected from it, not the one wch is appended ( both items are seperated by the pipe symobol)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
