### ISSUE TITLE
Tour of Heroes: Top Heroes list incorrect

### ISSUE THREAD

**Issue by annoseven** [angular/angular#25212]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Top Heroes does not list the first hero in the list.
Actual first hero is skipped.  First hero shown is the second hero in list.
Line 21 of dashboard.component.ts, slice parameters are incorrect.  Should be (0, 4).
21:       .subscribe(heroes => this.heroes = heroes.slice(1, 5));

## Expected behavior

Should list actual first hero.

## Minimal reproduction of the problem with instructions

See section 7 Routing of tutorial documentation.
See contents of dashboard.component.ts

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ewaschenko** [comment]
That's what it is suppose to do according to the documentation.

> This getHeroes reduces the number of heroes displayed to four (2nd, 3rd, 4th, and 5th).

**Comment by annoseven** [comment]
Oh I see.  Then the title Top Heroes is a bit misleading.

**Comment by FrederikSchlemmer** [comment]
I tried to make it more understandable. I am looking forward to your feedback!
