### ISSUE TITLE
Endless recursion with export * in implicit index module

### ISSUE THREAD

**Issue by Yogu** [angular/angular#25226]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

`ng build` fails with `Maximum call stack size exceeded` in [`bundler.ts`](https://github.com/angular/angular/blob/3f20a2fb5ad243a85a215cbf70269a769804a224/packages/compiler-cli/src/metadata/bundler.ts#L185) (`exportAll(exportFrom)`).

## Minimal reproduction of the problem with instructions

I have the following directory structure:

* `lib/accessor/index.ts`
* `lib/accessor/accessor.ts`

The file `lib/accessor/index.ts` has the line `export * from './accessor';`

The bundler incorrectly resolves the import `./accessor` to `./lib/accessor` which causes the endless recursion.

I could not do a reproduction in StackBlitz because the problem relates to the build (correct me if there is a way). I think the following snippet could work as a spec, but I did not manage to build angular on my Windows machine:

```typescript
  it('should retrieve metadata for an implied index relative path reference with export *', () => {
    const context = new MockAotContext('.', SIMPLE_LIBRARY_WITH_EXPORT_ALL_IN_IMPLIED_INDEX);
    const host = new MockCompilerHost(context);
    const options: ts.CompilerOptions = {
      moduleResolution: ts.ModuleResolutionKind.NodeJs,
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES5,
    };
    const adapter = new CompilerHostAdapter(host, null, options);
    const metadata = adapter.getMetadataFor('./lib', '.');

    expect(metadata).toBeDefined();
    expect(Object.keys(metadata !.metadata).sort()).toEqual([
      'One'
    ]);
  });

export const SIMPLE_LIBRARY_WITH_EXPORT_ALL_IN_IMPLIED_INDEX = {
  'lib': {
    'index.ts': `
      export * from './src';
    `,
    'src': {
      'index.ts': `
        export * from './src'; // this should resolve to lib/src/src.ts
      `,
      'src.ts': `
        export class One {}
      `
    }
  }
};
```

## Environment

<pre><code>
Angular version: 6.1.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3  
- Platform:  Windows 10

Others:

</code></pre>

**Comment by alxhub** [comment]
This seems related to #33121, although not exactly the same issue. The fix, however, is the same: Ivy does not use metadata and does not have the same limitations/bugs.

**Comment by JoostK** [comment]
The Ivy compiler no longer has a metadata collector that was prone to unsupported syntax issues, so closing as resolved.
