### ISSUE TITLE
RxJS ^6.0.0? Are you sure?

### ISSUE THREAD

**Issue by StevenLiekens** [angular/angular#25225]
(Sorry for not using the template, I feel like it gets in the way of my question)

I noticed that angular declares itself to be compatible with rxjs@^6.0.0. I also noticed in your [lock file](/angular/angular/blob/master/yarn.lock#L6068-L6069) that you are developing angular with rxjs@6.2.1.

How do you guarantee compatibility with pre-6.2.0 versions?

- RxJS 6.1.0 added the `isObservable` operator
- RxJS 6.2.0 added the `endWith` operator

You can declare compatibility with RxJS 6.0.x only for as long as contributors don't use these operators. But how do you ensure that nobody uses them?

**Comment by sarunint** [comment]
Added features have nothing to do with Angular. As long as no feature is removed, it's all compatible.

It's a magic of sematic versioning, in minor releases, there are new features, but no breaking changes.

**Comment by gregmagolan** [comment]
https://github.com/angular/angular/pull/25236 reverts rxjs back to 6.0.0 in the lock file. The bump to 6.2.1 was unintentional. Thanks for the catch @StevenLiekens.

**Comment by StevenLiekens** [comment]
> Added features have nothing to do with Angular. As long as no feature is removed, it's all compatible.

@sarunint, you're not considering what happens when angular itself starts using features from rxjs 6.1 or 6.2 but gets installed into a project that is still on rxjs 6.0.

**Comment by StevenLiekens** [comment]
@gregmagolan thanks for the quick fix

**Comment by sarunint** [comment]
My bad, I didn't understand your question clearly back then. Sorry for confusions.
