### ISSUE TITLE
Routing with query params (refreshing page manually)

### ISSUE THREAD

**Issue by sgentile** [angular/angular#25230]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[x ] Other... Please describe:   not sure yet, is it a bug or I'm I not understanding
</code></pre>

## Current behavior

when I navigate to a page with a query params, then refresh the page, or bookmark and return, the router falls to the 404 route.

ie.   foo/mypage?source=a

The router is path 'mypage' - it says it can't find the route and falls back into:
{ path: '**', redirectTo: '/404' }

I am using lazyload, so 'foo' above looks like this:
{
        path: 'foo'',
        loadChildren: './foo/foo.module#FooModule'
  }, 

This all works fine when I just refresh with foo/mypage - but anytime I have a querystring appended it fails to find the route (on refresh only or if user bookmarks, when navigating, ie. with a routerLink inside the app, it works fine)

## Expected behavior

I expect it to goto the foo/mypage route and be able to read the the query params just like I do without a page refresh

## Environment

<pre><code>
Angular version: 6.1.1

Browser:
all
 
For Tooling issues:
- Platform:  

Others:

</code></pre>

**Comment by sgentile** [comment]
(inside the Foo router, my page is like this)

{
  path: 'foo',
...
}

the query string is optional, I check that at a component level

**Comment by splincode** [comment]
add repro please
stackblitz?

**Comment by jasonaden** [comment]
If you still feel this is an issue, please create an isolated reproduction of your use-case in [StackBlitz](http://stackblitz.com) and create a new issue.
