### ISSUE TITLE
Parameter with default value and @Optional() decorator not initialized if dependency is absent

### ISSUE THREAD

**Issue by forever14k** [angular/angular#25233]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
If dependence is absent on parameter with `@Optional()` decorator – angular pass `null` instead of `undefined`, that leads to ignoring parameter default value.

That happens because typescript checks if parameter is `undefined` to initialize it with default value.

## Expected behavior
If dependence is absent on parameter with `@Optional()` decorator – angular should pass `undefined`.

## Minimal reproduction of the problem with instructions
```
export const SOME_CONST_VALUE = new InjectionToken<Object>('SOME_CONST_VALUE');

@Injectable()
export class SomethingService {

    constructor(@Inject(SOME_CONST_VALUE) @Optional() value: Object = {}) {
        if (!value) {
            throw new Error('value is not initialized');
        }
    }

}
```

## What is the motivation / use case for changing the behavior?
Angular should keep typescript compatibility, which is broken in this case.
Current behavior forces developers to write additional code with a `null` test, to initialize optional parameter with default value.

## Environment

<pre><code>
Angular version: 6.1.0

Browsers: ALL
</code></pre>

**Comment by pkozlowski-opensource** [comment]
This is the same as #25395, closing as a duplicate
