### ISSUE TITLE
scroll even for angular select never fires

### ISSUE THREAD

**Issue by qitang** [angular/angular#2523]
Hi,
 I created a directive  to listen on the scroll event from angular select and ng-options but I never fires! However if I use jquery and select without ng-options. Everything seems to be fine. Can anyone tell me why is that? Thanks!
The directive is like this 
```javascript
 app.directive("scrolly", function(){
  return {
    restrict : "A",
    link : function(scope, element,attrs)  {
       element.bind('scroll', function () {
          console.log("scrolled!!");
      });
      element.bind('click',function(){
        console.log("clicked");
      });
    }
  };
});
 
```
There is a live [example](http://jsbin.com/rododajave/1/edit?html,js,console,output)

**Comment by vicb** [comment]
this repo is ng2, please re-open on https://github.com/angular/angular.js
