### ISSUE TITLE
NgContent is bugging 3rd party functionality (Captcha etc.)

### ISSUE THREAD

**Issue by montella1507** [angular/angular#25245]
[x ] Bug report

## Current behavior
If we use several 3rd party libraries like Kendo charts, google maps, or google captcha in ng-content. We would see several "random" malfuctions, like problems with rendering (google map in tabs), problems with SVG rendering (charts), or it doesnt work at all (again, check stackblitz please)

Please check included stackblitz.

## Expected behavior
It should work correctly the behavior in ng-content should be the same.

## Minimal reproduction of the problem with instructions
Stackblitz:
https://stackblitz.com/edit/angular-zfpbj3?file=src%2Fapp%2Fapp.component.html

**Comment by mlc-mlapis** [comment]
@montella1507 ... are you sure that it's related to `<ng-content>`? I can't see any problem.Can you describe better or comment what steps should be done to reproduce the problem? Waiting more then 1 minute ... and it is still the same ... and also how it could be dependent on timing?

**Comment by montella1507** [comment]
@mlc-mlapis 
1) Open stackblitz via that link
2) Wait for 1 minute (it is random, but it will happen everytime when you wait 1+ min)
3) Click on SHOW button
4) Captcha in <div *ngIf> works but Captcha in component with template and ng-content, there will be error about "UNSUPPORTED BROWSER"

**Comment by trotyl** [comment]
@montella1507 ReCaptcha cannot be used on detached element, it has nothing to do with Angular, you'll get exact same behavior on VanillaJS:

https://stackblitz.com/edit/typescript-4fj35x?file=index.ts

**Comment by montella1507** [comment]
@trotyl  have you seen that example? Why does it work in NgIf and not in ng-content then?

**Comment by trotyl** [comment]
@montella1507 Do you understand what a **detached element** is?

**Comment by montella1507** [comment]
Removed from DOM?  Still do not see the difference between ngIf  directly and ngif on component with template and ng-content

**Comment by trotyl** [comment]
@montella1507 **Detached** means **attached and then removed**. And in the second case it's not rendered in the first place.

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/13760 and https://github.com/angular/angular/issues/13921

**Comment by montella1507** [comment]
Thank you, closing (moving issue to component author)
