### ISSUE TITLE
PropertyBindingType not exported in the v6.1.0 @angular/compiler bundle

### ISSUE THREAD

**Issue by tahuba** [angular/angular#25241]
Codelyzer want to use `PropertyBindingType` enum from the `@angular/compiler` package but it is not exported in the production version of it (`template_parser/template_ast.js`). The source code of bundles, esm2015, esm5, fesm2015 and src directories does not contain it.
`PropertyBindingType` was exported only in the <6.1.0 versions of `@angular/compiler`. 

## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
```
var ast = require("@angular/compiler");
// ...
ast.PropertyBindingType.Animation // -> TypeError: Cannot read property 'Animation' of undefined
```

## Expected behavior
`PropertyBindingType` property exists on the `ast` variable.

## Minimal reproduction of the problem with instructions
```
npm pack @angular/compiler@6.1.0
tar -xzvf angular-compiler-6.1.0.tgz
cd package

// grep the expression in the JS files only
grep -rnw '.' --include='*.js' -e 'PropertyBindingType'
// r3_view_compiler.js file imports and uses `PropertyBindingType` but it is nowhere exported
```

## Environment

<pre><code>
Angular version: 6.1.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.7.0
- Platform: Ubuntu 16.04 LTS

Others:
-
</code></pre>

**Comment by mgechev** [comment]
As @JoostK mentioned, codelyzer is using a private; we can close this issue. It's a responsibility of the consumer to handle changes in non-public APIs.
