### ISSUE TITLE
dynamically creating FormGroup

### ISSUE THREAD

**Issue by sysmat** [angular/angular#25244]
## I'm submitting a...

[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:

## Current behavior
template:

```
<form [formGroup]="createFormGroup(record)"
                (ngSubmit)="confirmedEdit(record)"
                #recordForm="ngForm">
<input type="text"
                     class="form-control form-control-sm"
            
                     name="recValue"
                     formControlName="recValue"
                     placeholder='vrednost ...'
                     [ngClass]="{ 'is-invalid': (recordForm.value.get('recValue').touched || recordForm.value.get('recValue').dirty) 
&& 
(recordForm.value.get('recValue').hasError('required') || 
recordForm.value.get('recValue').hasError('maxlength') || 
recordForm.value.get('recValue').hasError('minlength')) }">

<div class="invalid-feedback">
                <div *ngIf="recordForm.value.get('recValue').hasError('required')">
                  obvezno polje
                </div>
</div>
<button [disabled]="!recordForm.valid"
                      (click)="confirmedEdit(record)"
                      class="icon-button btn btn-sm">
                <i title="uredi zapis"
                   class="fas fa-check text-success"></i>
</button>
</form>

```
component:
```

createFormGroup = (record: Record): FormGroup => {
    const formBuilder = new FormBuilder();
    return formBuilder.group({
      recValue: [
        record.value,
        Validators.compose([Validators.required, Validators.minLength(2), Validators.maxLength(255)])
      ],
      recNote: [
        record.note,
        Validators.compose([Validators.required, Validators.minLength(2), Validators.maxLength(255)])
      ]
    });
  }

```

error:

```
TypeError: Cannot read property 'get' of null
```
## Expected behavior
[formGroup] creating on the fly and stored in local variable  #recordForm="ngForm"

## What is the motivation / use case for changing the behavior?
To have in line table editing with form validation

## Environment

Angular version: 6.1.0

Browser:
- [x] Chrome (desktop) version 68.0.3440.84
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:

```
Angular CLI: 6.1.1
Node: 9.2.1
OS: win32 x64
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.1
@angular-devkit/build-angular     0.7.1
@angular-devkit/build-optimizer   0.7.1
@angular-devkit/build-webpack     0.7.1
@angular-devkit/core              0.7.1
@angular-devkit/schematics        0.7.1
@angular/cli                      6.1.1
@ngtools/webpack                  6.1.1
@schematics/angular               0.7.1
@schematics/update                0.7.1
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2
```
Others:

**Comment by sysmat** [comment]
And another problem is in input filed type of text I can changed value in browser, very strange behavior.

What angular is expecting that every thing is a property  of component or class, disappointed with this framework

Regards, Tomaž

**Comment by jotatoledo** [comment]
`<form [formGroup]="createFormGroup(record)"`

Thats a no go, the FormGroup instance will be recreated on every change detection cycle.

The specific error that you mention is triggered because you are trying to bind the underlying `NgForm `directive from a `form[formGroup]` element, but the directive selector disallows `form `elements with `[formGroup]` attribute (see https://angular.io/api/forms/NgForm)

**Comment by sysmat** [comment]
Yes I want change detection cycle to detect beacuse I have table wich 

So you can not mix reactive and template forms, and in ver. 7 they will remove mixing with ngModel.
