### ISSUE TITLE
Non digest warning inside angular code thrown on build/serve

### ISSUE THREAD

**Issue by ugdpy** [angular/angular#25246]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report (i guess)  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When i build my code (ng serve/build and in every configuration), the compiler throw a warning inside the angular code : 

```
WARNING in ./node_modules/@angular/compiler/src/util.js
10:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

## Expected behavior

No warning thrown or, if the problem is inside my code, an understandable warning pointing to my code.

## Minimal reproduction of the problem with instructions

I can't reproduce it, that's kind of the problem here ...

## What is the motivation / use case for changing the behavior?

I don't likes warnings, and I'd like to understand where it comes from

## Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.1.1
Node: 9.11.1
OS: win32 x64
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.7.1
@angular/cli                      6.1.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.7.1
@schematics/update                0.7.1
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3

Others:

</code></pre>

**Comment by ugdpy** [comment]
@timjklein36 I don't see any require statement in the code using "find in project" with a regex and i got no match, so i'm pretty sure

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by ugdpy** [comment]
@IgorMinar 
That was the point of the issue, the warning message doesn't provides information about the issue. I can't provides more information because **it is** the problem here...

**Comment by dpksni** [comment]
@ugdpy Were you able to resolve it. Facing the same issue and have no idea how to resolve it?

**Comment by ugdpy** [comment]
@dpksni
Yes I found out. It appears I was using methods from the angular/core module, thinking it was from lodash (isDefined). This was triggering the warning.

**Comment by dpksni** [comment]
@ugdpy Thanks for replying. I will check my code to find any such instances, I am getting tons of these warnings.
