### ISSUE TITLE
ResolveStart event and ActivateStart events incosistent

### ISSUE THREAD

**Issue by ukrukarg** [angular/angular#25253]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When you enableTracing for routing, ActivationStart/End and ChildActivationStart/End events are emitted per route level, but ResolverStart/End event is emitted once for all the levels. It is inconsistent and might make you wonder if your routing setup actually does what it should be doing.

## Expected behavior
ResolveStart/End should also be emitted per route level.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/router-basic?file=src%2Fapp%2Fcrisis-center%2Fcrisis-detail-resolver.service.ts
Enable tracing in https://stackblitz.com/edit/router-basic?file=src%2Fapp%2Fapp-routing.module.ts and open https://router-basic.stackblitz.io/crisis-center/1

## What is the motivation / use case for changing the behavior?
Current behavior inconsistent.

**Comment by atscott** [comment]
Agreed, this is inconsistent but there's really no signal that we should invest time in changing it. The [documentation](https://angular.io/guide/router-reference#router-events) accurately describes the difference, though not in great detail.
