### ISSUE TITLE
No build in AOT mode after upgrade from v5.0.1 to 6.0.4

### ISSUE THREAD

**Issue by aakashbh2** [angular/angular#25259]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

No build in AOT mode. Build is made properly in dev and prod mode but only when AOT has been set to false.
Dependency of  "@ngtools/webpack": "^6.1.2" has been included

## Expected behavior

Build should be made as expected.

<pre><code>
Angular version: 6.0.4

For Tooling issues:
- Node version: 8.4
- Platform:  Linux

Others:
const aotLoaders = { test: /\.ts$/, loaders: ['@ngtools/webpack'] , exclude : /\.test\.ts$/};
const jitLoaders = {
          test: /\.ts$/,
          loaders: [
          'awesome-typescript-loader',
          'angular2-template-loader',
          'angular2-router-loader'
        ],
          exclude: [path.join(__dirname, "../node_modules")]
        };
const aotPlugin = new ngToolsWebpack.AngularCompilerPlugin({
                tsConfigPath: path.join(__dirname,'../tsconfig.aot.json'),
                entryModule: 'src/app/app.module#AppModule'
            });
My loaders are added like this.

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
