### ISSUE TITLE
base href stops working after hybrid with Angular.js route

### ISSUE THREAD

**Issue by JounQin** [angular/angular#25266]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
- [ ] Other... Please describe:

## Current behavior

When `base href` is set like `/ng-study/` and completing hybrid with Angular.js(angular-route), Angular routerLink and Angular.js href both stop working.

1. open https://jounqin.github.io/ng-study/console
2. click `Go to Login`, it will go to https://jounqin.github.io/ng-study/landing/login without any error
3. click `Go to Phones`, it will go to https://jounqin.github.io/ng-study/console/phones without any error, it contains a hybrid Angular.js app
4. click `Go to Login`(Angular routerLink), there will be an error: `ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'ng-study/landing/login'`
5. get back to 3, and click `Home`(Angular.js href), there will be two errors about `'ng-study/console'` and `'ng-study/console/phones'`		

## Expected behavior

There should be no error.

## Minimal reproduction of the problem with instructions

https://github.com/JounQin/ng-study

run script like: `ng build --base-href=/dist/ --deploy-url=/dist/`

open with something like [live server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) of VSC, you can review this error locally.

## What is the motivation / use case for changing the behavior?

Hybrid app should also work correctly

## Environment

Angular version: 6.1.0

Browser:
- [x] Chrome (desktop) version 67.0.3396.99
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by JounQin** [comment]
This error occurs after running `setUpLocationSync` from `@angular/router/upgrade`, source codes: https://github.com/angular/angular/blob/9141424ac69f8ff9702485e7f00e58fa503d8c42/packages/router/upgrade/src/upgrade.ts#L70-L77
It seems it does not check `base href` setting before navigate, and then `url.pathname` includes `base href` in https://github.com/angular/angular/blob/9141424ac69f8ff9702485e7f00e58fa503d8c42/packages/router/upgrade/src/upgrade.ts#L76, what makes this error.

**Comment by gkalpak** [comment]
Yeah, that sounds reasonable. I think it should be fixed by #20244.
Can you confirm that @JounQin?

**Comment by JounQin** [comment]
duplicate with #20061, and should be fixed by #20244.
