### ISSUE TITLE
Multiple Angular apps routing

### ISSUE THREAD

**Issue by FARHANE** [angular/angular#25260]
Hello world.
## I'm submitting a...
<pre><code>
[X] Feature request
</code></pre>

## Current behavior
I am creating an angular 6 application with multiple sub-apps with the commande:
ng new main-app
cd main-app
ng generate application app1
ng generate application app2
angular create the two sub application under the folder "projects"

## What is the motivation / use case for changing the behavior?
I have a sidenav and a header page in the main menu.
Every sub application has an object that discribe the sidenav items.
I want to be able to update the sidenav when the user click on button "Go to appX".
![new mockup 1](https://user-images.githubusercontent.com/7517235/43574408-64e01a2c-9644-11e8-9135-ad1df012771c.png)
![new mockup 1 copy 2](https://user-images.githubusercontent.com/7517235/43574416-696cee8a-9644-11e8-9b40-966223d28dd4.png)
![new mockup 1 copy](https://user-images.githubusercontent.com/7517235/43574424-6c222956-9644-11e8-87fd-c709e6932216.png)

**Comment by mlc-mlapis** [comment]
@FARHANE ... you missed the basic fact that Angular is primarily SPA application. There some extra cases when you can run multiple Angular apps in one window but you case is not certainly that case.

**Comment by FARHANE** [comment]
Yes, I do not want to run multiple application separately i want to be able to route from the main application to other sub applications because the are il the same project, I don't know if it is possible ?
![capture](https://user-images.githubusercontent.com/7517235/43574845-7c5f101c-9645-11e8-851a-e6a5229f2899.PNG)

**Comment by mlc-mlapis** [comment]
@FARHANE ... sure, but then don't create separate apps using ...
```
ng generate application app1
ng generate application app2
```

**Comment by FARHANE** [comment]
Ok thank you

**Comment by mlc-mlapis** [comment]
@FARHANE ... 👍 so be so kind and close this issue.

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
