### ISSUE TITLE
ng serve --open gives error

### ISSUE THREAD

**Issue by Vis24Freelancer** [angular/angular#25261]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)

## Current behavior
Newly installed ng serve --open gives the following error:

Date: 2018-08-02T10:40:44.506Z
Hash: a3f00ce41431cf441d6e
Time: 27459ms
chunk {main} main.js, main.js.map (main) 11.1 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 227 kB [initial] [r
endered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 15.6 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.26 MB [initial] [rendered]

ERROR in ./ansi-html
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #!/bin/sh
| basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
|
i ?wdm?: Failed to compile.

## Expected behavior
App should run in browser instead of showing Cannot Get.

## Minimal reproduction of the problem with instructions
Install a new angular app. My versions are as follows:

node - 8.9.4
npm - 5.6.0

## Environment

<pre><code>
Angular CLI: 6.1.2
Node: 8.9.4
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.2
@angular-devkit/core         0.7.2
@angular-devkit/schematics   0.7.2
@schematics/angular          0.7.2
@schematics/update           0.7.2
rxjs                         6.2.2
typescript                   2.7.2

Browser:
- [ ] Chrome (desktop) version 68.0.3440.84

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
