### ISSUE TITLE
Angular 5, CSS variables being shared between components unintentionally

### ISSUE THREAD

**Issue by thewickedgoat** [angular/angular#25265]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I navigate between two components, the component first loaded will share its CSS variables (which it gets from its own .component.css class), and change the style of the component which I route to.
If i reload the page, the issue disappears, until I navigate again. I can replicate it 100% of the time in my project. Is this intetional? If so, can It be disabled?

CSS variables sharing between components when navigating
Fx ".mainblock" in component x will also ".mainblock" of component y.

## Expected behavior

Each component should only (by default anyway) use the designated CSS file in component.ts file.

## Minimal reproduction of the problem with instructions
1. Generate two different components: - "ng g c page-x" and ng g c page-y"
2. Create a button with the class "mainblock" in the HTML of both components.
3. Style the .mainblock in the css file of page-x
4. Set up routing between both pages - use the @angular/router 
5. Set up the buttons to route between page-x and y (x -> and y -> x).
6. Load into page-x with the url you setup for it.
7. Click the button that routes the view to page-y, and see that the button in page-y with the class variable of "mainblock" now has the same width as the button in page-x.
8. Reload page-y
9. page-y's button is now styled as expected.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [X ] Chrome (desktop) version XX
- [ X] Chrome (Android) version XX
- [ X] Chrome (iOS) version XX
- [ X] Firefox version XX
- [ X] Safari (desktop) version XX
- [ X] Safari (iOS) version XX
- [ X] IE version XX
- [ X] Edge version XX
 
For Tooling issues:
- Node version: v8.9.4  
- Platform:  

Others:

</code></pre>

**Comment by manklu** [comment]
Please provide a complete sample with https://stackblitz.com/ or a similar service.

**Comment by Ploppy3** [comment]
Unless you messed with the view-encapsulation, The component's css is applied locally using the `_nghost-cn` and `_ngcontent-cn` attributes.

**Comment by thewickedgoat** [comment]
I can't recreate it on Stackblitz, it works as intended there. Odd.

All App's i create in Webstorm have this issue. Must be a local issue then.

**Comment by mhevery** [comment]
closing, no repro
