### ISSUE TITLE
Error in Eventservice of PRIMENG scheduler

### ISSUE THREAD

**Issue by sudhirkumart** [angular/angular#25264]
I am trying to use PRIMENG scheduler in following Angular version. When I am trying to create eventservice for scheduler (following code) and system throws following error

"TS2304: Cannot find name 'HttpClient'"

```
export class EventService {
  constructor(private httpClient: HttpClient) {}
  getEvents() {
      return this.httpClient
      .get('showcase/resources/data/scheduleevents.json')
      .toPromise()
      .then(res => <any[]>res.json().data)
      .then(data => {
        return data;
      });
  }
}
module.ts:

import {
  RadioButtonModule,
  KeyFilterModule,
  DialogModule,
  DropdownModule,
  InputTextModule,
  ScheduleModule,
  TabViewModule,
  MessagesModule,
} from 'primeng/primeng';

import { HttpClientModule } from '@angular/common/http';
import { HttpModule } from '@angular/http';
import { Injectable } from '@angular/core';
Angular version: Angular CLI: 6.0.8 Node: 8.11.3
```

Angular: 6.0.9 - animations, common, compiler, compiler-cli, core, forms http, language-service, platform-browser platform-browser-dynamic, router

I found the above piece of code in primeng website and looks like, this code implemented for Angular 2+ and Http is depreciated in Angular 6 https://www.primefaces.org/primeng/#/schedule
Browser: Chrome
Reproduction: Just try to use HTTP with primeng scheduler.
- Node version: 6.1.0
- Platform: Windows 10

Angular 5 is working as expected.

Can some throw some light on the same? Any help is highly appreciated.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by pkozlowski-opensource** [comment]
@sudhirkumart let's have primeng folks investigate first and we can eventually open an issue here if it is determined that the root cause is on the Angular side.

Please open in the primeng repo, thnx!
