### ISSUE TITLE
Event handler return value

### ISSUE THREAD

**Issue by pauldraper** [angular/angular#25269]
The following link in HTML works

```html
<a href="https://example.com" onclick="menuVisible = false">
```

However, the following link in an Angular template does not.

```html
<a href="https://example.com" (click)="menuVisible = false">
```

Angular uses the last statement in the handler as the return value.

This behavior is undocumented, inconsistent with HTML, surprising, and I suspect usually unintentional. I would consider it a bug.

--

If you want to prevent default browser behavior, it should be

```html
<a href="https://example.com" onclick="return menuVisible = false">
```

```html
<a href="https://example.com" (click)="return menuVisible = false">
```

**Comment by mhevery** [comment]
The return statement is implied in all angular statements. So this is intentional, since we are not planning on adding `return` statement to our vocabulary.

**Comment by pauldraper** [comment]
I still disagree that it is the right thing to behave so much differently than vanilla HTML. FWIW, angular-dart gave up this feature https://github.com/dart-lang/angular/issues/387 

But at least this behavior should be documented?
