### ISSUE TITLE
Identifier 'functionName' is not defined when passing Function into @Input. Causing intellisense errors but compiles fine.

### ISSUE THREAD

**Issue by adam3039** [angular/angular#25270]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I'm using a component that requires a function be passed into an @Input. I can achieve this by creating a property in my component with a :Function typing, and in ngOnInit, I bind it to a method in my component. This works, but it is throwing an intellisense error in the component HTML.

> Identifier 'functionName' is not defined. The component declaration, template variable declarations, and element references do not contain such a member

## Expected behavior

Since the app compiles fine, and the logic works, intellisense shouldn't flag an error. This stops intellisense from working further down the page. It's not a show stopper, just a pain in the ass.

## Minimal reproduction of the problem with instructions

Use a component with an @Input that accepts a function, something like this
`@Input() color: (value: number) => string;`

In another component where you want to use the above component, pass in the function
[color]="someFunction"

In the calling component, create a local member of type Function
```
someFunction: Function;

ngOnInit {
    this.someFunction = this.determineColor.bind(this)
}

determineColor(value: number) {
    return '#FFF';
}
```

In this components HTML, '[color]="someFunction"' will have the intellisense error. Application still compiles fine, and the method works.

## What is the motivation / use case for changing the behavior?

To avoid intellisense breaking down for the rest of the page.

## Environment

<pre><code>
Angular version: 6.1.0

Others:

Visual Studio Code
</code></pre>

**Comment by mlc-mlapis** [comment]
@adam3039 ... the idea of passing a function reference via `@Input()` sounds really strange. It looks like you should re-think the logic ... there is certainly much more Angularic way how to get the same final goal.

**Comment by adam3039** [comment]
Hi @mlc-mlapis 

I completely agree, it's gross. It's a third party component that I need to use because I'd rather not roll my own, and the options are limited.

Anyways, I restarted VS Code and that seemed to remove the intellisense error. My apologies, should've tried that first.
