### ISSUE TITLE
adding routes dynamically to appRoutes in app.module.ts

### ISSUE THREAD

**Issue by Hiyam** [angular/angular#25276]
Hello,

I am developing a web application (more like a CMS) where the admin must be able to create new categories.

Example: the web page has a the following categories: Men, Tshirts, Kids, shoes, etc, and now the admin wants to create a new category called "Women".

For that, what I have in mind is the following: I will, **dynamically**, create a new route called "women" and **I want to add it to the app routes** in app.module.ts.

**Here is my app.module.ts:**

```
import { AppComponent } from './app.component';
import { MainComponent } from './main/main.component';
import { FormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { RouterModule, Routes } from '@angular/router';
import { LoginComponent } from './login/login.component';
import { SignupComponent } from './signup/signup.component';
import { TempComponent } from './temp/temp.component';
import { DynamicComponent } from './dynamic/dynamic.component';


const appRoutes: Routes = [
  {
    path: '',
    component: MainComponent,
  },
  {
    path: 'login',
    component: LoginComponent,
    data: { title: 'Login' }
  },
  {
    path: 'signup',
    component: SignupComponent,
    data: { title: 'Sign Up' }
  },
  {
    path: 'temp',
    component: TempComponent
  }
];

@NgModule({
  declarations: [
    AppComponent,
    MainComponent,
    LoginComponent,
    SignupComponent,
    TempComponent,
    DynamicComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpClientModule,   
    RouterModule.forRoot(
      appRoutes,
      { enableTracing: true } // <-- debugging purposes only
    )
  ],
  entryComponents:[DynamicComponent], // added halla2
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
I have used this.router.config.push and this.router.resetConfig, but they worked only dynamically, i.e they were added only temporarily, but when I close the application and restarted it again the "dynamically added route" was not present there anymore :(

I was thinking of storing these dynamically added routes in the database and reload them again whenever I restart my app, but I'm unsure whether it is a good practice or not.

Thanks in advance.

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
