### ISSUE TITLE
css,scss,less

### ISSUE THREAD

**Issue by J-env** [angular/angular#25274]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>
![image](https://user-images.githubusercontent.com/25259920/43629178-2799eb8e-972f-11e8-8c58-1ccea40fbbb8.png)
![image](https://user-images.githubusercontent.com/25259920/43629190-31d0b416-972f-11e8-9fe5-c4aa8e4a4a10.png)

(variables\minxi\extend):
I need to import this in every component file, which is annoying.
use (@extend   %user-select-none ): 
The style generated using this method is not very good.

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
