### ISSUE TITLE
 Can't resolve 'zone.js/dist/zone'

### ISSUE THREAD

**Issue by Janatbek** [angular/angular#25288]
https://github.com/angular/angular/blob/0822dc70f2580a3d0e5c936ef07707dd09e7a878/aio/src/polyfills.ts#L38

Getting this error: ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'zone.js/dist/zone' in 'C:\Projects\myProject\src'

**Comment by stubbsy345** [comment]
Did you find solution, getting same error?

**Comment by vignesh1991** [comment]
I'm getting below error, any suggestions please 
Error: Module not found: Error: Can't resolve 'zone.js/dist/zone-testing'

**Comment by assadshehbaz** [comment]
> [angular/aio/src/polyfills.ts](https://github.com/angular/angular/blob/0822dc70f2580a3d0e5c936ef07707dd09e7a878/aio/src/polyfills.ts#L38)
> 
> Line 38 in [0822dc7](/angular/angular/commit/0822dc70f2580a3d0e5c936ef07707dd09e7a878)
> 
>  import 'zone.js/dist/zone';  // Included with Angular CLI. 
> Getting this error: ERROR in ./src/polyfills.ts
> Module not found: Error: Can't resolve 'zone.js/dist/zone' in 'C:\Projects\myProject\src'

I have the same error: 

Try this.
> **"npm i zone.js"**
above command worked in my case.

**Comment by spock123** [comment]
Didn't work for me.. anybody have ideas how to solve this?
Really annoying stuff, I*m trying to enable IVY (Angular 8 RC.2) but there are so many issues not mentioned in the IVY guide, this is one of them.

**Comment by QuanVOLEMINH** [comment]
> I'm getting below error, any suggestions please
> Error: Module not found: Error: Can't resolve 'zone.js/dist/zone-testing'

`zone-testing` only exists from `0.8.19`. Try to install the latest version.  `zone.js^0.8.26` worked for me. See [25801](https://github.com/angular/angular/issues/25801).
