### ISSUE TITLE
Production build stuck at 92% percentage

### ISSUE THREAD

**Issue by chdnitinsharma** [angular/angular#25286]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
$ ng build --prod --aot=false
Your global Angular CLI version (6.0.8) is greater than your local
version (1.5.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Date: 2018-08-03T14:20:26.925Z
Hash: 7ef0dc48f58f3c6be114
Time: 81775ms
chunk {0} polyfills.e8c106aae21b5a2364e7.bundle.js (polyfills) 96.2 kB [initial] [rendered]
chunk {1} main.2bfa46edcefe41d2d2ed.bundle.js (main) 1.44 MB [initial] [rendered]
chunk {2} styles.59fd733508abc03f82fb.bundle.css (styles) 370 kB [initial] [rendered]
chunk {3} vendor.abc0af0257250c054d0b.bundle.js (vendor) 4.44 MB [initial] [rendered]
chunk {4} inline.6e1478b27af86e1ddf44.bundle.js (inline) 1.45 kB [entry] [rendered]

--- 
$ ng build --prod
Your global Angular CLI version (6.0.8) is greater than your local
version (1.5.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
 92% chunk asset optimization

Production build with aot It is taking too much time. I have wait for 15 minutes. Still not completed. It was stuck at 92%. Please help me out. Should I deploy  build on server with --aot=false parameter.

## Environment
<pre><code>
_                      _                 ____ _     ___
/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
/ △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
/ ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
|___/

Angular CLI: 1.5.4
Node: 8.9.3
OS: win32 x64
Angular: 5.1.3
... compiler, compiler-cli, core, platform-browser
... platform-browser-dynamic
@angular/animations: 4.4.6
@angular/cdk: 5.2.1
@angular/cli: 1.5.4
@angular/common: 4.4.6
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/material: 5.2.1
@angular/router: 4.4.6
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.4.2
webpack: 3.8.1
</code></pre>

**Comment by JoostK** [comment]
You appear to have a bit of a weird Angular version thing going on, with both Angular 5 and 4 being used. I don't think that is the cause of your issue though.

I have seen stuck builds as well when running `ng test`, also on Windows. The weird thing was that changing a file caused the process to restart and then finish successfully. Perhaps you could try something similar with `ng build --watch`.

**Comment by trotyl** [comment]
Should be reported in https://github.com/angular/angular-cli if you cannot reproduce it with `ngc` directly.

**Comment by kara** [comment]
This looks like a CLI issue. Please open on https://github.com/angular/angular-cli, as @trotyl mentioned.

**Comment by chdnitinsharma** [comment]
@JoostK , @trotyl  and @kara Thanks I have reported in angular cli. [https://github.com/angular/angular-cli/issues/11783](https://github.com/angular/angular-cli/issues/11783.)
