### ISSUE TITLE
Ivy's `cleanUpView` incorrectly checks for existence of `TView`

### ISSUE THREAD

**Issue by JoostK** [angular/angular#25298]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

@kara The following bit of code in Ivy checks for `viewOrContainer` being a view by accessing `[TVIEW]`:

https://github.com/angular/angular/blob/15cc85c54a9146c6d502cffad52a3c1a41fe4dcb/packages/core/src/render3/node_manipulation.ts#L457-L469

This used to be possible when view nodes were objects, however after the refactoring to an array the 0th index (`TVIEW`) also exists for `LContainer`, of which it's the `ACTIVE_INDEX` property/index. Hence, the check is inaccurate.

## Expected behavior
Accurate way of determining view vs container.

**Comment by kara** [comment]
Yeah, looks like we missed this when moving to the array format. Should be a quick fix.

**Comment by kara** [comment]
@JoostK FYI we're going to close this issue, since it's too early to keep track of issues involving Ivy implementation details on Github. But appreciate you flagging this problem - we'll move it to our internal issue tracker.

**Comment by JoostK** [comment]
@kara Please also review the following one:

https://github.com/angular/angular/blob/15cc85c54a9146c6d502cffad52a3c1a41fe4dcb/packages/core/src/render3/node_manipulation.ts#L442

`HOST_NODE` in `LViewData` is `RENDER_PARENT` in `LContainer`
