### ISSUE TITLE
Tooltip + Click Bug.

### ISSUE THREAD

**Issue by pedrosanguineti** [angular/angular#25296]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Desktop: Tooltip disappears when clicking a part of a chart that has the tooltip activated (e.g a pie chart slice). Afterwards, it no longer appears untill the pointer reenters that part of the chart.

## Expected behavior
Desktop: Tooltip should not disappear with a click event.

## Minimal reproduction of the problem with instructions
1. Go to: https://swimlane.github.io/ngx-charts/#/ngx-charts/bar-vertical
2. Move the mouse to a bar activating the tooltip.
3. Click the bar once, the tooltip disappears.

## What is the motivation / use case for changing the behavior?
I believe that this behavior is not intended and should be addressed.

## Environment

<pre><code>

Browser:
- [X] Chrome (desktop) version  67.0.3396.99
 
For Tooling issues:
- Node version: 8.11.3.
- Platform:  Windows.

**Comment by ericmartinezr** [comment]
I'm sorry but this issue is not caused by Angular. Please contact the author(s) of project ngx-charts or file issue on their issue tracker.

**Comment by kara** [comment]
Yeah, this issue doesn't look like it belongs on our repo. Please file with ngx-charts.

**Comment by pedrosanguineti** [comment]
Hmm, my mistake. Not sure how this post ended up here. Sorry.
