### ISSUE TITLE
[Bug/Documentation]: router-outlet activateEvents and deactivateEvents not working ???

### ISSUE THREAD

**Issue by ahnpnl** [angular/angular#25305]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When doing event binding with `activateEvents` and `deactivateEvents` from `router-outlet`, I put console log for these events but I didn't see anything happening. I couldn't find anything from documentation regarding to the usage of those events from https://angular.io/guide/router so I can't confirm whether this is a bug or expected behaviors.

## Expected behavior

If this is simply a missing part in documentation, I'd like to see the documentation update the usage of `activateEvents` and `deactivateEvents` on `router-outlet`.

If this is a bug, the expected behavior should be: it should print to console when these events occurs while navigating to a route.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-zsdefm

- Open console log.
- Click on `Test Component` link
- See the component shows the text `test works` but nothing prints in the console.

## What is the motivation / use case for changing the behavior?

It'd be nice if we can listen to these events to do something on it. Also a clear documentation about the usage of these events would help a lot.

## Environment

<pre><code>
Angular version: 6.1.1

Browser:
- [x] Chrome (desktop) version Version 68.0.3440.84
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3  
- Platform: Mac 

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@ahnpnl ... but it should be ...
```
<router-outlet (activate)="onActivateEvents($event)" (deactivate)="onDeactivateEvents($event)"></router-outlet>
```

**Comment by ahnpnl** [comment]
@mlc-mlapis thank you, it works with `activate`, `deactivate`. I don't know why my Webstorm suggests me to use `activateEvents` and `deactivateEvents` on template instead of `activate` and `deactivate`.

I think a bit documentation about these 2 events would be a bit helpful too for people who wants to use event binding on these events.

**Comment by trotyl** [comment]
![snip20180804_6](https://user-images.githubusercontent.com/6059170/43677759-1650af28-983a-11e8-9814-970907d93e22.png)

@ahnpnl https://angular.io/api/router/RouterOutlet

**Comment by ahnpnl** [comment]
ah I see so it's not in the guide but in the documentation of the class itself. Thank you :)

**Comment by aleksander351** [comment]
How can I call function from injected child component so that it triggers parent component? Like there is with emit...

I.e.:
    `
      onActivate(event: any): void {
          event.childFunction.emit(true); 
      }
    `
