### ISSUE TITLE
Route resolve with async call used in app which is hosted in iframe on MS Edge

### ISSUE THREAD

**Issue by djindjic** [angular/angular#25302]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Adding resolver for fetching data via HttpClient to the route, breaks browser's back button behavior in MS Edge if this angular app is hosted in iframe. When you are at some route and navigate to the route with resolver and then choice browser's back, it redirects the parent window (iframe host) to the last page before angular app iframe has been loaded.

## Expected behavior

Back should work on Edge in same way like it works on latest Chrome, Firefox, Safari and IE 11 (all tested)

## Minimal reproduction of the problem with instructions

In order to reproduce this behaviour, I've created [stackblitz example](https://stackblitz.com/edit/edge-resolve?file=index.html) with iframe pointing to app deployed to firebase hosting because I couldn't point stackblitz to stackblitz. Deployed app is pushed to github repo and [here](https://github.com/djindjic/edge-resolve/blob/master/src/app/app.module.ts) is whole app in one file. 
If you comment out [resolve part](https://github.com/djindjic/edge-resolve/blob/master/src/app/app.module.ts#L41) of routes definition or return some sync result (ex. `Observable.of('123')` ) back button will work normally. Also, everything works perfect if it's not in iframe.

## What is the motivation / use case for changing the behavior?

This is my 3rd project where we are adding new features in iframe and also I know many companies doing it same way in order to avoid conflicts between old and new parts of an existing app. We would like to support all modern browsers.

## Environment

<pre><code>
Angular version: 6.1.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [X] Edge version 42.17134
 
For Tooling issues:
- Node version: v9.6.1  
- Platform: Mac, VirtualBox with Windows 10

**Comment by djindjic** [comment]
hey @jasonaden, I understand it's probably not top priority item, but if you have any idea why this happens maybe you can propose us some alternate solution. We are little bit stuck with our ms edge user's experience.

**Comment by jelbourn** [comment]
Closing old Edge-related issues since any such issues have likely been resolved in the newer Chromium-based Edge.
