### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by osmanm786** [angular/angular#25315]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
no out of the box auth for google, facebook, amazon, azure etc.

## Expected behavior
would be nice to see @angular/auth

## Minimal reproduction of the problem with instructions
n/a

## What is the motivation / use case for changing the behavior?
we tend to look for proper way to have angular's httpclient to help us with authentication.
I know we can doit  with interceptors after we authenticate and set the headers. I would really like to see 
out of the box way of doing it.  Something like amazon auth/ azure auth/ facebook etc. Have the httpclientmodule know that we set that up.

After using angular, i am more comfortable if you great guys can provide a standard to do this and make it easy like everything else in angular.

**Comment by petebacondarwin** [comment]
We are not going to implement this feature in the core framework.
There are various 3rd party libraries that can do this depending upon the auth provider you are using.
