### ISSUE TITLE
Angular Upgrade - `$destroy` event is not fired on angularjs `$element`

### ISSUE THREAD

**Issue by llRandom** [angular/angular#25334]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When upgraded directive was hidden by `*ngIf` directive, `$element` doesn't receive `$destroy` event.

## Expected behavior

In case of angularjs, when condition for `ng-if` is changed from `true` to `false` event is triggered.

## Minimal reproduction of the problem with instructions
1. Add angularjs component with injected `$element`
2. Subscribe to `$destroy` event
3. Make ng6-version using `UpgradeComponent`
4. Put `*ngIf` condition which is initially `true`
5. Trigger some handler that will change it to `false` to hide upgraded component

## What is the motivation / use case for changing the behavior?

Some plugins, like angular-ui-bootstrap components, use these events to dispose component, so these components don't work properly when event is not fired. In particular, angular-ui-bootstrap dropdown has an option to append dropdown to body. In angularjs, if container was hidden, component is disposed properly. In hybrid mode node that is attached to body is not disposed because component doesn't receive `$destroy` event

## Environment

<pre><code>
Angular version: 1.6.1

Browser:
- [x] Chrome (desktop) version 68
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.0.0
- Platform:  Windows

</code></pre>

**Comment by gkalpak** [comment]
Normally, the `$destroy` event is triggered by jqLite/jQuery, which is not used in Angular for removing the element.

I don't see a reason not to trigger the event from `ngUpgrade` ([here][1] and [there][2]).

##
In the meantime, you can augment `UpgradeComponent` to trigger the event (and then use your class instead of `UpgradeComponent` for you upgraded components):

```ts
import {UpgradeComponent} from '@angular/upgrade/static';
import * as angular from 'angular';

export class AugmentedUpgradeComponent extends UpgradeComponent {
  private _element: any;

  constructor(selector: string, elementRef: ElementRef, injector: Injector) {
    super(selector, elementRef, injector);
    this._element = angular.element(elementRef.nativeElement);
  }

  ngOnDestroy() {
    super.ngOnDestroy();
    this._element.triggerHandler('$destroy');
  }
}
```

[1]: https://github.com/angular/angular/blob/2505c077d7e85421b32afed8b18e67b71e322654/packages/upgrade/src/static/upgrade_component.ts#L216-L224
[2]: https://github.com/angular/angular/blob/2505c077d7e85421b32afed8b18e67b71e322654/packages/upgrade/src/dynamic/upgrade_ng1_adapter.ts#L265-L271

**Comment by llRandom** [comment]
For some reason if I trigger `$destroy` on a root element it's not captured by nested elements. If I do something like `(this as any).$element.find('my-ng1-component').trigger('$destroy')` it's working but in some cases it gives me another error

```
TypeError: Cannot read property '$$nextSibling' of null
    at Scope.$broadcast (http://localhost/Scripts/angular/angular.js:18310:59)
    at Scope.$destroy (http://localhost/Scripts/angular/angular.js:17913:14)
    at afterAnimating (http://localhost/Scripts/angular-ui/ui-bootstrap-tpls.js:4115:17)
    at processQueue (http://localhost/Scripts/angular/angular.js:16648:37)
    at http://localhost/Scripts/angular/angular.js:16692:27
    at Scope.$eval (http://localhost/Scripts/angular/angular.js:17972:28)
    at Scope.$digest (http://localhost/Scripts/angular/angular.js:17786:31)
    at my-project-bundle
    at SafeSubscriber.schedulerFn [as _next] (my-project-bundle)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (my-project-bundle) Possibly unhandled rejection: {}
```

It fails inside this angular.js block

          // Insanity Warning: scope depth-first traversal
          // yes, this code is a bit crazy, but it works and we have tests to prove it!
          // this piece should be kept in sync with the traversal in $digest
          // (though it differs due to having the extra check for $$listenerCount)
          if (!(next = ((current.$$listenerCount[name] && current.$$childHead) ||
              (current !== target && current.$$nextSibling)))) {
            while (current !== target && !(next = current.$$nextSibling)) {
              current = current.$parent;
            }
          }
As I understand, it triggers second scope dispose and it fails because `$parent` property is set to `null`. So, something is also wrong with the way Angular Upgrade disposes $scopes

**Comment by gkalpak** [comment]
@llRandom, can you provide a minimal demo showing the failing usecase. (You can extend [my demo][1] from above.)

[1]: https://stackblitz.com/edit/ngupgradestatic-playground-bgdmcz?file=ng1/ng1-demo.component.ts
