### ISSUE TITLE
CanDeactivate being called with null component when refresh the page

### ISSUE THREAD

**Issue by arash3003** [angular/angular#25337]
CanDeactivateGuard is not working properly with lazyloaded component when I refresh the page.

I have placed the guard in the lazy load module and it works perfectly when I navigate to that page. However, if I refresh the page and try to navigate, it says the component is null. 
The same issue happens if I try to navigate to another lazy loaded page.

I am using:
Angular CLI: 1.6.4
Node: 8.11.3

const page2Routes: Routes = [
  {
    path: '',
    component: Page2Component,
    canActivate: [AuthGuard],
    canDeactivate: [CanDeactivateGuard],
    resolve: {
      data1: resolver1,
      data2: resolver2,

    }
  }
];

@NgModule({
  declarations: [
    page2Component
  ],
  imports: [
    RouterModule.forChild(page2Routes),
.
.
.
  ],
  providers: [
    CanDeactivateGuard,
    resolver1,
    resolver2
  ]
})

export class page2RouterModule { }
-----
the main route is like:

{ path: page2, loadChildren: 'app/components/page2-router.module#Page2RouterModule', data: { title: 'page 2' } },

any fix for it?

Thank you

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
