### ISSUE TITLE
CanDeactivate being called with null component when refresh the page

### ISSUE THREAD

**Issue by arash3003** [angular/angular#25338]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
CanDeactivateGuard is not working properly with lazyloaded component when I refresh the page.

I have placed the guard in the lazy load module and it works perfectly when I navigate to that page. However, if I refresh the page and try to navigate, it says the component is null.
The same issue happens if I try to navigate to another lazy loaded page.

## Expected behavior
The guard should work with the lazy loading and page refresh.

## Minimal reproduction of the problem with instructions
 - have 3 pages lazy loaded 
 - 3 routes modules for each lazy loaded page and one app route
 - Create Guard
 - add the guard to one lazy loaded route module
 - run app and navigate from main route to page 1 and then refresh the page and try navigate away and you see the component value is null.
 - or don't refresh the page and try to navigate to page 2 which is lazy loaded and see the same behavior.

const page2Routes: Routes = [
{
path: '',
component: Page2Component,
canActivate: [AuthGuard],
canDeactivate: [CanDeactivateGuard],
resolve: {
data1: resolver1,
data2: resolver2,

}
}
];

@NgModule({
declarations: [
page2Component
],
imports: [
RouterModule.forChild(page2Routes),
.
.
.
],
providers: [
CanDeactivateGuard,
resolver1,
resolver2
]
})

## Environment

<pre><code>
Angular version: 1.6.4

Browser:
- [x] Chrome (desktop) version 67.0.3396.99
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3  
- Platform:  Windows 

Others:

</code></pre>

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
