### ISSUE TITLE
Angular Universal Using Window Scroll To Top Issue

### ISSUE THREAD

**Issue by ABHIRON** [angular/angular#25347]
i created a application using universal and angular.
after building the application i am facing one error called ( RefrenceError window is not defined )

the reason why i am using this window is only because when i change route my page starts from mid i need to implement this because i want route page should start from top

if any one having any solution regarding this please help me with building my project.

**Comment by ZouYouShun** [comment]
Hi @ABHIRON , this problem is because server unknown window object, we can use `isPlatformBrowser` to block your code only run in browser.

```ts
 constructor(@Inject(PLATFORM_ID) private platform: Object) { }

  ngOnInit() {
      if (isPlatformBrowser(this.platform)) {
        // here you can run any browser specific code, like:
        window.alert('This will run only in the browser!');
      }
  }
```

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by ABHIRON** [comment]
@ZouYouShun  i am writing the same way you told me but 

@Inject, PLATFORM_ID, isPlatformBrowser they all throwing error by red underline.
