### ISSUE TITLE
HTTP Response 302, Redirect problem

### ISSUE THREAD

**Issue by copycatam** [angular/angular#25345]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

when I make a http call to my server and it redirects it to the external authentication provider, angular(zone.js) intercept the response and make the redirect as XHR call. 

## Expected behavior
Angular(zone.js) should not handle a 302 redirect response. this should be a browser responsibility.

## Minimal reproduction of the problem with instructions

1- Make a GET request
2- return a 302 redirect response
3- Go to the network tab in the browser and you should have 
 GET                      302          xhr       get
 GET                      302                      zone.js(xxxx in my case 2968)
 redirect URL        200          xhr        other

## Environment

<pre><code>

Angular version: 6.1.1
Zone.js: 0.8.26

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by JoostK** [comment]
A browser will always follow a redirect without any JavaScript code knowing about it, so there's presumably no way to do this differently at this moment in time. 

You could try to use the low-level APIs such as `XMLHttpRequest` or `fetch` yourselves, without any framework or library. You'll notice that it is simply not possible to ever see the redirection response. If I'm not mistaken, it won't even show as separate network response and subsequent request in Web Inspector.

**Comment by copycatam** [comment]
@JoostK TH's for point out me in the right direction. Debuging zone.js, Zones and http.js I understand now what is happening under the hood. The firts mistake I made was that I was expecting a different browser redirect from XHR Request. 

As you said Javascript don't know nothing about 302 Redirect Response, and in fact zone.js never scheduled this redirection request. What was  driving me crazy was the fact that angular end up handling the redirect response. 

But my assumption here is that due to angular is register to "XMLHttpRequest.addEventListener.load" and the type of redirection that the browser makes is XHR. It received the response.
