### ISSUE TITLE
Leverage Guards to Hide/Display Content

### ISSUE THREAD

**Issue by mswilson4040** [angular/angular#25342]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Angular provides you the option to add `canActivate` on a given route and provide it with an array of guards to run and see if a user has access to the page. It would be nice if there was a way to leverage these same Guards on the route to figure out whether or not something should display or not.

## Expected behavior
Currently, Guards only come into play and run when you actually navigate to the route. There doesn't seem to be any straightforward way to leverage that same logic and use the outcome to figure out if something should be displayed or not.

**Use Case:**

In my Angular application, I have multiple areas. All areas are protected by a standard AuthGuard that just makes sure that they are logged in. Once they are logged in, they can navigate to a couple different areas. Within the area they navigate to, I basically build up a navigation menu based off the current `ActivatedRouteSnapshot` which has everything how I want (notably, it has the Guards available). Where I get stuck at is that as I'm building up the navigation menu dynamically based off the values in the `AppRoutingModule`, I eventually get to a Route that requires an extra layer of permissions and roles. Access to that route is covered since I've got an AdminGuard present within the `canActivate` guards array. However, the display of that link is what I'm trying to control. If they don't have access to something (CanActivate returns false), then I don't want the link to display at all.

It would be cool if a Guard Directive or something was available that would act the same as the Routes. Basically, you give it an array of Guards, and if that resolves fine, the link (or component, for that matter) would display. Otherwise, if wouldn't.

Essentially, I think an `*ngIf` that encapsulates that functionality of the canActivate property on a route would be extremely helpful.

## Minimal reproduction of the problem with instructions
Stackblitz: https://stackblitz.com/edit/angular-gitter-1spzsf?file=app%2Fapp.component.html

1. Pull up the Stackblitz
2. Click on Public Portal (You'll see if hits the route just fine)
3. Click on Admin Portal (You'll see that nothing happens because the route guard returns `false`)

## What is the motivation / use case for changing the behavior?
Better flexability in how we configure route security.

## Environment

<pre><code>
Angular version: 6.0.2 but related to all versions where Guard functionality exists

Browser:
- [X ] Chrome (desktop) version 67
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Mac High Sierra

Others:
Current SOF thread: https://stackoverflow.com/questions/51716383/angular-routeguard-dynamic-navigation
</code></pre>

**Comment by mswilson4040** [comment]
This article gives a pretty good overview of use case and how you would go about doing it.

**Comment by mswilson4040** [comment]
Here's what I ended up doing. It's actually pretty simple directive. However, there are two things I don't like here:

- If your Guards have anything that does a redirect, you'll have to change it so the Guard only returns true/false. If it redirects the page on Guard failure, then the directive will just end up redirecting you instead of just hiding the element

- this._elementRef.nativeElement.style.display = hasAccess ? 'block' : 'none'; There's a better solution to this than just doing a simple hide. It should act like *ngIf where it doesn't even render the element at all unless it evaluates to true.

**Implementation:**

`<div appGuard [guards]="myGuardsArray">Something you want to hide .... </div>`

**Directive:**

```
import { Directive, ElementRef, Injector, Input, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';

@Directive({
  selector: '[appGuard]'
})
export class GuardDirective implements OnInit {
  @Input() guards: any[];
  private readonly _elementRef: ElementRef;
  private readonly _activatedRoute: ActivatedRoute;
  private readonly _router: Router;
  private readonly _injector: Injector;
  constructor(_elementRef: ElementRef, _activatedRoute: ActivatedRoute, _router: Router,
              _injector: Injector) {
    this._elementRef = _elementRef;
    this._activatedRoute = _activatedRoute;
    this._router = _router;
    this._injector = _injector;
  }
  async ngOnInit(): Promise<void> {
    const canActivateInstances = this.guards.map( g => this._injector.get(g));
    const results = await Promise.all(canActivateInstances.map( ca => ca.canActivate(this._activatedRoute.snapshot, this._router.routerState.snapshot)));
    const hasAccess = results.find( r => !r) === false ? false : true;
    this._elementRef.nativeElement.style.display = hasAccess ? 'block' : 'none';
  }
}
```

**Comment by mswilson4040** [comment]
Update, if you want to differ between just running the guard logic vs hadling any redirects (as discussed in issue #1 in my previous post), you can just do a check on the state.url. This appears to be the length of 0 when running as a directive whereas if someone were to actually hit the page, it'd have something in the array:

```
async canActivate(
    next: ActivatedRouteSnapshot, state: RouterStateSnapshot): Promise<boolean> {
    const user = await this._meService.getCurrentUser();
    const result = user && user.isUserAdminForCompany;
    if (next.url.length > 0) {
      await this._router.navigateByUrl(`${environment.webRoot}/sign-in`);
    }
    return result;
  }
```

**Comment by ubugnu** [comment]
I'm using this snippet of code:
```
import { Router, ActivationStart } from '@angular/router';
import { filter, map } from 'rxjs/operators';
// ...
  constructor(private router: Router) { }
// ...
  ngOnInit() {
    this.router.events
      .pipe(
        filter(event => event instanceof ActivationStart),
        map((event: ActivationStart) => {
          return event.snapshot.routeConfig.canActivate;
        })
      ).subscribe((f) => {
        this.isGuarded = f !== undefined
      })
  }
// ...
```

**Comment by mswilson4040** [comment]
@ubugnu I like your solution more than mine.

**Comment by fvilers** [comment]
Hi, I was looking for something similar and I came up to this solution. Demo available here : https://angular-guard-directive.stackblitz.io.

Link:
```
<a
  appGuard
  [routerLink]="['page2', 42]"
  (check)="blocked = $event.blocked"
  >
  Page 2
</a>
```

Directive:
```
import { Directive, EventEmitter, Output } from "@angular/core";
import { GuardsCheckEnd, Router, RouterLinkWithHref } from "@angular/router";
import { Subject } from "rxjs";
import { filter, takeUntil } from "rxjs/operators";

type GuardCheckEvent = {
  blocked: boolean;
};

@Directive({
  selector: "[appGuard]"
})
export class GuardDirective {
  @Output()
  check = new EventEmitter<GuardCheckEvent>();

  private destroy$ = new Subject();

  constructor(private routerLink: RouterLinkWithHref, private router: Router) {}

  ngOnInit() {
    this.router.events
      .pipe(
        takeUntil(this.destroy$),
        filter(
          event =>
            event instanceof GuardsCheckEnd &&
            event.url === this.routerLink.href
        )
      )
      .subscribe(({ shouldActivate }: GuardsCheckEnd) => {
        this.check.emit({ blocked: !shouldActivate });
      });
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }
}
```
