### ISSUE TITLE
Angular app no longer hosted on domain name - Service worker survived

### ISSUE THREAD

**Issue by un33k** [angular/angular#25341]
<pre><code>
[x ] Bug report 
</code></pre>

## Current behavior
Service worker hangs when changing domain name.
1. Deploy the Angular 6.0.0 app on foo.com
2. Deploy the backend API on api.foo.com (Django if relevant)
3. Test and ensure everything works on foo.com. (Service worker loads ... all good)
4. Test the backend (loads)
5. Deploy (move) the Angular 6.0.0 app to app.foo.com
66. Deploy (move) the backend API to foo.com
7. Test and ensure everything works on app.foo.com (service worker loads ... all good)
8. Test the backend, (won't load - Service worker hangs, eventhough foo.com is now a Django site)

## Expected behavior
Service worker needs to be automatically removed if the host is no longer serving an angular application.

In the above example, I just swapped the domains. After the swap, the only way to make the Django site load was to flush the browser cache. 

## Minimal reproduction of the problem with instructions
The problem is with a Django site that is bugged down with service worker.  Follow the `Current behavior` steps to reproduce.

## What is the motivation / use case for changing the behavior?
Service worker is there to bring quality of experience to the end user.  There seem to be many corner cases that prevent that at this time.

## Environment

<pre><code>
Angular CLI: 6.1.1
Node: 9.11.2
OS: darwin x64
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.7.1
@angular-devkit/build-angular      0.7.1
@angular-devkit/build-ng-packagr   0.7.1
@angular-devkit/build-optimizer    0.7.1
@angular-devkit/build-webpack      0.7.1
@angular-devkit/core               0.7.1
@angular-devkit/schematics         0.7.1
@angular/cdk                       6.4.2
@angular/cli                       6.1.1
@angular/flex-layout               6.0.0-beta.17
@angular/material                  6.4.2
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.1.1
@schematics/angular                0.7.1
@schematics/update                 0.7.1
ng-packagr                         3.0.6
rxjs                               6.2.2
typescript                         2.9.2
webpack                            4.9.2
Browser:

- [x ] Chrome (desktop) Version 67.0.3396.99 (Official Build) (64-bit)

For Tooling issues:
- Node version: v9.11.2
- Platform: Mac 

Others:
</code></pre>

**Comment by gkalpak** [comment]
There is no reliable way for the SW to know if an Angular app is served or not. The SW does indeed unregister itself if fetching `ngsw.json` results in a 404, so that should be enough for your usecase (provided that your aPI server is appropriately configured).

Furthermore, browsers don't cache the SW script for [more than 24 hours][1] (by default), so that would cause the SW to get unregistered as well.

##
It sounds like something else is going on, @un33k.
Happy to investigate if you can provide a minimal reproduction or more specific info indicating that the behavior is not as described above.

[1]: https://w3c.github.io/ServiceWorker/#ref-for-concept-request-cache-mode%E2%91%A0

**Comment by un33k** [comment]
@gkalpak 

> The SW does indeed unregister itself if fetching ngsw.json results in a 404

That was exactly my point. Some websites/CMS may not do a 404 and might redirect or else instead.

**Comment by gkalpak** [comment]
I know. But like I said, it is not possible for the SW to guess what you are doing on your backend :grin:

You should be able to configure your server to return a 404 for `ngsw.json` (or a script that unregisters the SW for `ngsw-worker.js` - such a script is [already provided][1] by `@angular/servicde-worker`).

And even if not possible, then the SW should be unregistered by the browser when failing to fetch a `.js` file for `ngsw-worker.js` after max. 24 hours.

FWIW, I understand this is inconvenient (especially that it is different from how we usually handle removed or moved `.js` scripts), but ServiceWorkers are a little special and do require specially handling.

[1]: https://unpkg.com/@angular/service-worker@6.1.2/safety-worker.js
