### ISSUE TITLE
how to disable debugger statement in enableProdMode() mode

### ISSUE THREAD

**Issue by jigneshchudasama** [angular/angular#25348]
`enableProdMode()` is still executing `debugger` statement, can anyone please tell me how to disallow or disable the `debugger` statement in production mode.

Thanks

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
