### ISSUE TITLE
don't have aria-label for ng-select creates new input box for placeholder 

### ISSUE THREAD

**Issue by swatiaher** [angular/angular#25349]
Its get issue for WCAG compliance
Tell me how to add aria-label for that input box.
Note: I have already try with [attr.aria.label] to <ng-select tab

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
