### ISSUE TITLE
Wait nested call API before display an array angular material (pls help a noob ^^)

### ISSUE THREAD

**Issue by Raffaele-LIZE** [angular/angular#25352]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

1. call api with my http service for get all users
2. for each user, call api (other entity) with my http service for get all locations.
3. i need associate locations (return by request) with his user.
4. display an array (angular material mat-tab)
5. My array is empty or duplicate user...

## Expected behavior

I need build an array with users and his locations before print mat-tab.

## Minimal reproduction of the problem with instructions

In my component : 

```
public userWithLocations          = [];

ngOnInit () {
		this.loadData();	
	}

loadData() {
		let that = this;
		// get all users
		this.httpSrv.getAllUsers()
			.subscribe(allUser => {

				for (let user in allUser) {

					let currentUser = allUser[user];

                                          // get locations by user
					this.httpSrv.getLocationsByUser(allUser[user]['_id'])
						.subscribe((locations) => {

							currentUser.nb_location = locations;

							that.userWithLocations.push(currentUser);
					})
				}

				console.log(that.userWithLocations); // => []

                                 // Here i need my array with for each user an attribute with locations count

				// init MatTableDataSource dataSource only when receive data (NOT BEFORE)!
				this.dataSource = new MatTableDataSource(that.userWithLocations);
				// init paginator
				this.dataSource.paginator = this.paginator;
				// // init sort
				this.dataSource.sort = this.sort;
			});
	}
```
In my service (http) :

```
// Users requests
	getAllUsers(): Observable<any> {
		// return Observable
		return this.http.get(this.apiURL + 'users');
	}

	getLocationsByUser(id): Observable<any> {
		// return Observable
		return this.http.get(this.apiURL + '/locations/' + id)
			.pipe(map(locations => { return this.size(locations)}));
	}

	// Object length
	size(obj) {
	    var size = 0, key;
	    for (key in obj) {
	        if (obj.hasOwnProperty(key)) size++;
	    }

	    return size;
	};
```

## What is the motivation / use case for changing the behavior?
i am young developer, beginner in angular 6 and i try to learn how to do nested call api with rxjs for my job. 

## Environment

<pre><code>
Angular version: X.Y.Z

> Angular CLI: 6.0.8
> Node: 10.4.0
> OS: darwin x64
> Angular: 6.0.4
> 
> Package                           Version
> -----------------------------------------------------------
> @angular-devkit/architect         0.6.8
> @angular-devkit/build-angular     0.6.8
> @angular-devkit/build-optimizer   0.6.8
> @angular-devkit/core              0.6.8
> @angular-devkit/schematics        0.6.8
> @angular/animations               6.0.5
> @angular/cdk                      6.2.1
> @angular/cli                      6.0.8
> @angular/flex-layout              6.0.0-beta.15
> @angular/material                 6.2.1
> @ngtools/webpack                  6.0.8
> @schematics/angular               0.6.8
> @schematics/update                0.6.8
> rxjs                              6.2.1
> typescript                        2.7.2
> webpack                           4.8.3

Browser:
- [x] Chrome (desktop) Version 68.0.3440.84
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node: 10.4.0
- Platform:  Mac

Others:

</code></pre>

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
