### ISSUE TITLE
Angular is triggering validation of fields that are not in concern

### ISSUE THREAD

**Issue by piernik** [angular/angular#25350]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[x] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I'm building own form creator with fields wrapper. 
Fields are divided into two groups visible and not.
Always visible field has async validator. 

If I toggle not visible field, async validator of visible one is triggered.

## Expected behavior
Operation on field should not trigger validators of other field.
If I for example hide normal field (replace `<app-input-wrapper [formGroup]="formGroup" [formControlName]="'text2'"></app-input-wrapper>` with `<input type="text" formControlName="text2">`) that validator is not triggered.

It also drives to problem with `ExpressionChangedAfterItHasBeenCheckedError` as in example.

## Minimal reproduction of the problem with instructions
Here is reproduction: https://stackblitz.com/edit/angular-svpkpx?file=src%2Fapp%2Fapp.component.html
If You click hide/show button, pending is changing.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kara** [comment]
@piernik When you use `formGroup` as an @Input for your input wrapper, it is still matching the `formGroup` directive from `angular/forms`. This directive is not intended to work on the same element as the `formControlName` directive, esp if you add in custom accessor logic. If you remove this input, it should put you on the right path.

If you're still having problems setting up your form, please try posting your question on [StackOverflow](http://stackoverflow.com/) using tag `angular`.
