### ISSUE TITLE
Page scrolls to top when navigating to the same page

### ISSUE THREAD

**Issue by orijel** [angular/angular#25353]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When navigating to the same page using `Router`, the page scrolls to the top.

## Expected behavior

The page should remain in the same scrolling position when navigating to the same page.

## What is the motivation / use case for changing the behavior?

The `router.navigate()` method provides a good way to update the url parameters of the page, i'm using it in the following way:
`this.router.navigate(['.'], {
      queryParams: params,
      relativeTo: this.route,
      replaceUrl: true,
      queryParamsHandling: 'merge'
    });`

also happens when using:
`this.router.navigate([], {
      queryParams: params,
      relativeTo: this.route,
      replaceUrl: true,
      queryParamsHandling: 'merge'
    });`

## Environment

<pre><code>
Angular version: 6.1.1

This issue happened to me when upgrading from 6.0 -> 6.1.1

Browser:
- [x] Chrome (desktop) version 68.0.3440.84
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.2  
- Platform: windows  

Others:

</code></pre>
Looking at the events from: `this.router.events.subscribe(params => {
      console.log(params);
    });`
i received the following output:
![image](https://user-images.githubusercontent.com/11149593/43775805-a0f7ca6c-9a56-11e8-9760-c23466b93e08.png)
The red arrow indicates the moment when the page scrolls to top.

After further investigation i found out that it's related to the new "Router Scroller" feature introduced in v6.1.
I think that's it's not disabled by default, since updating my RouterModule options from:
`imports: [
    RouterModule.forRoot(routes)
  ],`
to:
`imports: [
    RouterModule.forRoot(routes, {
      scrollPositionRestoration: 'disabled'
    })
  ],`
fixed the issue.

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/25145

**Comment by jasonaden** [comment]
Fixed with #25586 and will be released tomorrow.
