### ISSUE TITLE
Dev experience: do minimal work in test.unit.* tasks

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#2536]
Currently, on my MBP, there is 30+ seconds delay from running one of the `test.unit.*` tasks till tests start to run. Normally this shouldn't be much of the pb, since one wouldn't be obliged to start those tasks often. But in practice there are situations where Karma disconnects and we need to kill the process, we need to switch between dart and JS etc. In short: starting tests tasks isn't that uncommon as we would like to.

My proposal here is to do minimal work before executing tasks so I would propose to remove:
* clang-format and circular dependencies check from `test.unit.js`
* pub update from `test.unit.dart`

WDYT? Are there particular reasons to execute this additional work while booting up unit tests?

**Comment by IgorMinar** [comment]
we moved most of the work out. pub get is needed for transformers to work, so I don't think we can remove that. everything else happens after tests.

**Comment by pkozlowski-opensource** [comment]
Thnx @IgorMinar !
