### ISSUE TITLE
window.location.href doesn't work from Angular Service (@Injectable)

### ISSUE THREAD

**Issue by borasik** [angular/angular#25364]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[X ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

My application has authentication with MS Active Directory with JWT and OpenId Connect
Once user not authenticated I have to redirect to windiw.location.href = microsoft_url_active_directory
If I'm doing redirection from component it's working fine:

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {
  constructor(private oidcSecurityService: OidcSecurityService,
    private authenticationHelperService: AuthenticationHelperService) { }
  ngOnInit() {
    if (!this.authenticationHelperService.isAuthenticated()) {
      **this.oidcSecurityService.authorize(); //window.location.href IS HERE** 
    }
  }
}

But if I'm trying to redirect from Service nothing happen:

@Injectable()
export class GatewayService {
  constructor(private http: Http, private authenticationHelperService: AuthenticationHelperService) {}
   createServiceGet(url: string, options: RequestOptions, headers: Headers = null): Observable<any> {
    if (!this.authenticationHelperService.isAuthenticated()) {
       **this.oidcSecurityService.authorize(); //window.location.href IS HERE**
    }

    options = options == null ? new RequestOptions() : options;
    headers = headers == null ? new Headers() : headers;
    const httpHeaders = this.authenticationHelperService.getTokenHeader();
    Object.assign(headers, httpHeaders);
    headers.append('Content-Type', 'application/json');
    headers.append('Access-Control-Allow-Origin', '*');
    headers.append('Accept', 'q=0.8;application/json;q=0.9');
    options.headers = headers;

    return this.http
      .get(url, options)
      .map(this.extractData)
      .catch(this.handleError);
  }

## Expected behavior

   **this.oidcSecurityService.authorize(); //window.location.href IS HERE** REDIRECTION will happen from services as well.

## Minimal reproduction of the problem with instructions
use window.location.href = 'http://google.com' from @Component
and the do the same from @Injectable service - nothing will happen
## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX   9.2.0
- Platform:   Windows 10

Others:

</code></pre>

**Comment by JoostK** [comment]
Could you provide a reproduction on Stackblitz?

**Comment by mhevery** [comment]
closing as no repro
