### ISSUE TITLE
Entire API is unstable

### ISSUE THREAD

**Issue by arturohernandez10** [angular/angular#25373]
When exploring the API if I select stable from the dropdown everything goes away. Everything is marked as experimental.

Except that there are API elements that are stable. But the documentation browser is broken.

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

**Comment by trotyl** [comment]
![image](https://user-images.githubusercontent.com/6059170/43817412-f26833f4-9b0b-11e8-8cac-0e8859476f61.png)

Stable rate above. But actually it's package-specific stats, the entire rate doesn't make sense (basic the concept of Angular Labs).

The detailed packages rate (testing lib excluded):

Packages | Total | Stable | Deprecated | Stability | Note
----|----|----|----|----|----
animations|38|32|0|84.2%
animations/browser|1|0|0|0.0%
common/http|28|28|0|100.0%
common|83|39|1|47.6%|19 i18n fns
core|153|84|7|57.5%|13 debug
elements|8|0|0|0.0%|Labs
forms|47|40|1|87.0%
http|28|0|28|NaN|Deprecated
platform-browser|26|13|1|52.0%
platform-browser/animations|3|0|0|0.0%
platform-browser-dynamic|3|1|0|50.0%|JIT
platform-server|10|0|0|0.0%|SSR
platform-webworker|17|0|0|0.0%|Experimental
platform-webworker-dynamic|1|0|0|0.0%|Experimental
router|66|44|0|66.7%
router/upgrade|2|0|0|0.0%|Bridge
service-worker|3|0|0|0.0%|Experimental
upgrade|2|0|2|NaN|Deprecated
upgrade/static|9|2|2|28.6%|Bridge

The real stability is high enough, could you elaborate what you think should be stable but still be experimental?

**Comment by arturohernandez10** [comment]
Why are those not showing on the API browser?

**Comment by trotyl** [comment]
@arturohernandez10 Which API do you talking about, again?

**Comment by arturohernandez10** [comment]
https://angular.io/api?status=stable

**Comment by trotyl** [comment]
![image](https://user-images.githubusercontent.com/6059170/43818895-531bec84-9b13-11e8-9e41-90a895309574.png)

I don't have any idea what you mean.

**Comment by arturohernandez10** [comment]
That list appears empty on my PC and on my phone.

**Comment by trotyl** [comment]
@arturohernandez10 

+ Device name and OS;
+ Browser name and version;
+ What console error;
+ What plugin used (remove all and retry);
+ Service worker enabled or not (clear it and retry);

That's basic info to report an web application issue.

**Comment by arturohernandez10** [comment]
Today it's working 👍
