### ISSUE TITLE
Child routes are not notified when resolved data changes

### ISSUE THREAD

**Issue by jonrimmer** [angular/angular#25378]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When a resolver is re-run on a reload of the current URL, using `runGuardsAndResolvers: 'always'`, child route components that have subscribed to data changes are not notified.

## Expected behavior

When a resolver is re-run, *all* components lower in the route tree should be notified. Otherwise they will continue to use / display stale data.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-router-broken

1. Open the console.
2. Note that ParentComponent and ChildComponent both receive the same resolved value "A".
3. Change the resolved value to "B"
4. Click "refresh()"
5. Note that the resolver was run.
6. Note that ParentComponent was notified of the change.
7. Note that ChildComponent was not notified.

## What is the motivation / use case for changing the behavior?

Work towards making the router's resolve functionality usable for real-world apps.

## Environment

<pre><code>
Angular version: 6.1.1

</code></pre>

**Comment by jasonaden** [comment]
The `runGuardsAndResolvers` setting isn't inherited by children. Maybe this is best filed as a feature request, which would need to be evaluated whether it's something that can be added in a way that doesn't break the current API.

By adding `runGuardsAndResolvers: 'always'` to the child config, without any other changes, your example works fine.

If that doesn't solve your issue, please file a new issue as a feature request to allow inheritance of this option. To me, the complexity with inheritance will be crossing the lazy-loaded boundary, as I think it could cause unexpected behavior to allow inheritance across lazy-loaded modules. Would need to think about it a bit more and work up some use cases.

**Comment by jonrimmer** [comment]
This explanation doesn't any logical sense. The resolver isn't declared on the child and doesn't belong to it. What if there's a dozen child states? What if there's a thousand? Are you saying I have to set `runGuardsAndResolver: 'always'` on every single one? What if there are resolvers lower down the tree that I **don't** want run on every navigation? Why should a child state be controlling the lifecycle of a dependency declared by its parent? What your suggesting is a uselessly blunt instrument and a total violation of encapsulation.

Furthermore, the resolver *is* being run, as demonstrated by the fact that the resolver executes and the ParentComponent gets the updated value. I thought the whole *point* of resolvers was to do a single load and share the resolved value between children. Different components having a different view of the same resolved value runs completely contrary to the entire purpose of resolves.

It seems like the whole resolve capability of the Angular router has been cloned badly from UI Router without any real understanding of how it should work, or appreciation of the real world use-cases it is needed to solve. As things stand, it would be better to rip it out entirely and tell people to use a state management system like ngrx, rather than have them waste their time trying to use a half-baked solution that is so limited and mis-designed as to be fundamentally broken.

**Comment by mlc-mlapis** [comment]
@jonrimmer ... so how those children get the initial data?

> ... child route components that have subscribed to data changes are not notified.

**Comment by jonrimmer** [comment]
@mlc-mlapis When the initial navigation happens, the resolver runs, and the resolved value is supplied in the data collection of the parent activated route, and some children (depending on the setting of `paramsInheritanceStrategy` in the `RouterModule`, which controls whether the data inherits only to "empty" child routes (the default) or all child routes (what you actually want 99.9% of the time).

It is only for the second navigation, when the resolver runs again, that the new value is not supplied to the children. The basic flow boils down to this:

 1. Initial navigation
 2. Resolver runs, producing value 'A'
 3. Parent gets 'A'
 4. Child gets 'A'
 2. Second navigation
 3. Resolver runs again, producing value 'B'
 4. Parents gets notified of new value 'B' 
 5. Child does not get notified.

Does this make any kind of sense? It does not.

**Comment by mlc-mlapis** [comment]
@jonrimmer ... ah, I see ... but then it's just a bug and not design problem because this should be exactly cover by `paramsInheritanceStrategy: 'always'` config, right?

Is it related to already existing issues?

https://github.com/angular/angular/issues/21878
https://github.com/angular/angular/issues/25140

**Comment by jonrimmer** [comment]
@mlc-mlapis No. Please read the earlier posts in this thread, including @jasonaden's replies.

**Comment by mlc-mlapis** [comment]
@jonrimmer Maybe it was working in some previous versions? Or the following post was written without any code?
https://kimsereyblog.blogspot.com/2018/02/params-inheritance-strategy-with.html

**Comment by jonrimmer** [comment]
@mlc-mlapis That post does not cover this issue. It only deals with inheriting data on the initial navigation, not when it changes due to the resolver running for a second time.

**Comment by mlc-mlapis** [comment]
@jonrimmer ... hmm, you are right. Then I don't understand also why the same principle is not applied against subscribed observables. For me, the logic is the same so I also don't have any idea why it was limited to just static data.

**Comment by george3447** [comment]
@jonrimmer I have wasted some hours for the same issue, and I have fixed this by adding the runGuardsAndResolvers inside child router config like this

` {
      path: '',
      component: ParentComponent,
      resolve: {
        value: ExampleResolver
      },
      runGuardsAndResolvers: 'always',
      children: [{
        path: '',
        component: ChildComponent,
        runGuardsAndResolvers: 'always',
      }]
    }`

please see below stackblitz link [(https://stackblitz.com/edit/angular-router-broken-frvmid?file=src/app/app.module.ts)]

**Comment by jonrimmer** [comment]
@george3447 Yes, that is the suggestion made by @jasonaden earlier in this thread. It "works" to fix this simple example, but it is not a reasonable solution for all the reasons I gave previously. E.g. it needs to be done on every single child route declaration, and is uselessly blunt in its effect—every other resolver declared in the tree will be always re-run on every navigation, even if they don't need to be. What if those resolvers include expensive/slow network calls?

The entire purpose of the resolver pattern in routers is to centralise data loading into a single place, then distribute the value to all interested state components. For the router to re-run the resolver, then continue to serve stale data to child components is utterly nonsensical and buggy behaviour.
