### ISSUE TITLE
router-outlet no Component Stack

### ISSUE THREAD

**Issue by Eusen** [angular/angular#25372]
## I'm submitting a...

<pre>
<code>[ x ] Feature request</code>
</pre>

## Current behavior

router-outlet no Component Stack

When the path is transformed, the current route will replace the previous route instead of hiding it. On the mobile side, page switching is directional, either forward or backward, and most importantly, when returning to the previous page, the previous page retains its previous state.

The best example is ionic's ion-nav

I think this way of implementation is very good, and I hope router-outlet can support this feature in native.

## Expected behavior

route-outlet can implement functions similar to ion-nav.

## Environment

<pre><code>
Angular version: 6.1.1

Browser:
- [ x ] Chrome (desktop) version 68.x
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.x  
- Platform: Windows 

Others:

</code></pre>

**Comment by jasonaden** [comment]
Thanks, and I generally agree. We have this on the list of items to address for an upcoming release, but it's unlikely to make it into v7 at this point. The idea is to allow many more use cases of dealing with history, including allowing a more tree-based approach, as well as allowing you to "jump" trees such as is done in mobile apps.

Unfortunately I don't think this will be available for 6-8 months, but it's definitely on the radar.
