### ISSUE TITLE
 ngOnInit() is not fire when i changed same route with different parameter

### ISSUE THREAD

**Issue by Rjitendra** [angular/angular#25376]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
ngOnInit() is not fire when i changed same route with different parameter 

url like http://localhost:1029/documentation/53,
http://localhost:1029/documentation/100

## Expected behavior
ngOnInit() should work

## Minimal reproduction of the problem with instructions
export class DocumentationDetailComponent implements OnInit, AfterViewInit {

  documentId: number;
 
  constructor(private router: Router,
    
    private route: ActivatedRoute) {
      this.route.params.subscribe(params => {
        if (params['Id']) {
          this.documentId = params['Id'];
        }
    });
 ngOnInit() {
    alert('ngOnInit fire');
    
  }

routing..
const routes: Routes = [
  {
    path: '', component: DocumentationComponent,
    children: [
      {
        path: '',
        component: DocumentationDetailComponent
      },
      {
        path: ':Id',
        component: DocumentationDetailComponent
      },}]
@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class DocumentationRoutingModule { }

## Environment

<pre><code>
Angular version: 6.1.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  <v8.11.1>
- Platform:   Windows

**Comment by mlc-mlapis** [comment]
@Rjitendra ... no. You should read some doc first. In those cases, you work with the same component instance. The component is not destroyed and re-created. Your code should be able to react to available events and re-init the state without re-instantiation.

**Comment by ponkys** [comment]
@Rjitendra I agree with @mlc-mlapis. Have you checked the same with ngOnDestroy?
```
ngOnDestory() {
alert('ngOnDestroy fire');
}
```

That won't trigger either.

If you need to update something from the view try another approach. I suggest doing it after you subscribe to the route.
```
private route: ActivatedRoute) {
  this.route.params.subscribe(params => {
    if (params['Id']) {
      this.documentId = params['Id'];
      this.initTemplate(this.documentId); // <=== like this.
    }
});
```

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
