### ISSUE TITLE
Conditional providers in angular module throws AOT error

### ISSUE THREAD

**Issue by gpradeepjain** [angular/angular#25374]
Hi,

I am trying to include a provider into my module based on condition. Works fine in JIT but fails in AOT saying  

> function call not allowed in decorator

 or 

> Symbols not allowed in decorator
 if i use variables

```
const IE = detectIE();
    providers: [abcService,
      xyzService,
      (IE) ? [{provide: EVENT_MANAGER_PLUGINS,
        useClass: IeInputEventManagerService,
        deps: [DOCUMENT],
        multi: true
    }] : [],
```
The above code throws AOT error saying symbols not allowed in decorator.

```
const IE = detectIE();
const tempProviders: Array<any> = [
  abcService,
  xyzService];

if(IE) {
tempProviders.push({provide: EVENT_MANAGER_PLUGINS,
    useClass: IeInputEventManagerService,
    deps: [DOCUMENT],
    multi: true
});
}

@NgModule -> continues here
```

In above case, the provider never gets pushed or never gets active. How do i solve this issue?

Hope my code is clear as to what i trying to achieve. Whats the correct way of doing it? It is a valid scenario.

I am submitting a
> [ ] Regression (a behavior that used to work and stopped working in a new release)
> [ X] Bug report  
> [ ] Performance issue
> [ X] Feature request
> [X ] Documentation issue or request
> [ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
> [ ] Other... Please describe:

**Comment by mhevery** [comment]
Providers need to be statically analyzable, so you can't change them in this way. It is not supported. Use `factory` instead.

**Comment by gpradeepjain** [comment]
Even in case of factory only for IE i can return an object but for other browsers what do i return?
