### ISSUE TITLE
Well-support mixins 

### ISSUE THREAD

**Issue by AndriiDidkivsky** [angular/angular#25375]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Within AOT I have to create anonymous class to mixin behaviour of components
Like in this [issue](https://github.com/angular/angular/issues/19145) 

## Expected behavior
Would be great use mixins in AOT like.
Now it's working only in JIT
`mixin(SomeComponent, Printable, Notable)`

## What is the motivation / use case for changing the behavior?
Simplify complex logic to avoid make so much services and compose/duplicate methods. 
Is there any plans to make this happens in near future?

<pre><code>
Angular version: any

Browser: any

**Comment by trotyl** [comment]
This is already the current behavior in Ivy:

https://github.com/angular/angular/blob/732026c3f56a91b016fcf79ebc581569d7c89618/packages/core/src/render3/definition.ts#L232-L238

All life-cycle hooks are determined by `prototype` at runtime, not compiler.

(One exception is `NgOnChanges`, which is not a real life-cycle hook now).

**Comment by AndriiDidkivsky** [comment]
Question is about typo errors during compile AOT if use standard TS tutorial.
```
function applyMixins(derivedCtor: any, baseCtors: any[]) {
    baseCtors.forEach(baseCtor => {
        Object.getOwnPropertyNames(baseCtor.prototype).forEach(name => {
            derivedCtor.prototype[name] = baseCtor.prototype[name];
        });
    });
}
```

Here well-described [issue](https://stackoverflow.com/questions/43679638/angular-4-aot-compiler-does-not-support-mixins)

**Comment by trotyl** [comment]
@AndriiDidkivsky It has nothing to do with Angular, if you want to read or write a undeclared property, you'll need to bypass the type-checking yourself.

**Comment by AndriiDidkivsky** [comment]
@trotyl ok, thanks a lot. I was thinking this could be fixed on compiler level.
