### ISSUE TITLE
DatePipe: First day of week not changing corresponding to set locale in i18n

### ISSUE THREAD

**Issue by maidl** [angular/angular#25380]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

After setting locale to German in i18n, DatePipe doesn't switch first day of week from Sunday to Monday.
Also calendar weeks are starting on Sundays not on Mondays.

## Expected behavior

If transforming a date e.g. 'March 11th 2018' (2018-03-11) with parameter 'w' the output should be '10' instead of '11'.

## Minimal reproduction of the problem with instructions
Take a look at: https://stackblitz.com/edit/angular-gitter-ovkezs

## What is the motivation / use case for changing the behavior?

Implementation of ISO 8601 standard.

> [...] the weekday number, from 1 through 7, beginning with Monday and ending with Sunday.

https://en.wikipedia.org/wiki/ISO_8601#Week_dates

## Environment

<pre><code>
Angular version: 6.1.1

Browser:
(not a Browser-based issue)
 
For Tooling issues:
(N/A)

Others:

</code></pre>

___
EDIT: updated stackblitz

**Comment by maidl** [comment]
@vicb updated in the original report (https://stackblitz.com/edit/angular-gitter-ovkezs)
In my opinion this issue doesn't (and shouldn't) rely on the time zone because no matter where you are, with locale set to a european country, the first day of week always is Monday.

**Comment by vthinkxie** [comment]
Hi @vicb @ocombe 
any update on this issue, we have to introduce date-fns to resolve this problem in our component library because of this issue.

https://ng.ant.design/docs/i18n/en#how-to-format-a-date-using-date-fns

**Comment by prashant-tholia** [comment]
Hi, please ignore the above commit done by me. It includes extra code that is not relevant to this particular issue and the resolution is done through an ISO 8601 implementation. Please excuse me for the inconvenience.

**Comment by prashant-tholia** [comment]
@petebacondarwin , I request you to clarify about how this needs to be fixed. Do we do a locale based implementation or an ISO 8601 implementation irrespective of locale? This choice also affects the implementation of 'W' (month-based week number) format (https://github.com/angular/angular/issues/38826). Thanks.

**Comment by petebacondarwin** [comment]
So the question is whether to have a breaking change for this and move the date functions in Angular over to be ISO8601 compatible. The other idea would be to make it an opt-in but then that might make thing verbose if it has to be provided for each use of the date pipe.

There is already a start at #25451 - although that PR is very old and may well need to be heavily reworked.

What is the community feelling on this?

**Comment by prashanttholia** [comment]
@petebacondarwin, please find below my thoughts on the issue - 

There are only two formats affected by the issue - 'w' & 'Y'. I think that the issue could be simply resolved by introducing two new formats corresponding to the other week start day option. Popular JS date libraries such as moment & date-fns implement it in the same way.

There's another point I wish to mention. My perception is that the usage of the week number based dates is notably more in European and a few Asian countries than the rest of the world. These countries use ISO8601 based dates. Therefore, I suggest that, whichever solution is chosen finally, 'w' & 'Y' be kept for ISO8601 based dates and the other ways (opt-in, other formats or any other solution) be kept for non-ISO based dates. I suggest this for two reasons - 
1. It would be consistent with ISO 8601, the international standard.
2. I am not sure if it would introduce as huge a breaking change as we imagine. In fact, it might introduce a fix for many of the implementations.

Thanks.

**Comment by petebacondarwin** [comment]
Here is some research on various Date formatting tools. It appears that there is little agreement on the tokens to use when formatting dates. Given that we rely upon the CLDR and it references [Unicode Technical Standard #35](http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table), I think we should follow that table for the formatting tokens in the Angular framework.

  | MomentJS | Luxon | date-fns | CLDR | PHP
-- | -- | -- | -- | -- | --
Day of Week | d |   | E | E |  
Day of Week (locale) | e | c/E | c/e | c/e |  
Day of Week (ISO) | E |   | i | - | N
Week of Year (locale?) | w |   | w | w |  
Week of Year (ISO) | W | W | l | - | W
Week of Month (locale) |   |   |   | W |  
Week of Month (ISO) |   |   |   | - |  
Year (ISO?) | Y |   |   | u? | Y
Era Year | y |   |   | y |  
Week Year | g | k | Y | Y | o
Week Year (ISO) | G |   | R | - |  

I note that CLDR/Unicode does not have separate formatting tokens for locale-specific vs ISO formatting.
With this in mind, I think we should follow suit and find an "out of band" approach to decide whether the formatting is using the current locale or ISO.

**Comment by petebacondarwin** [comment]
I also note that the [`formatDate()`](https://angular.io/api/common/formatDate) and [`DatePipe`](https://angular.io/api/common/DatePipe) accept a `locale` parameter, which is the locale to use when formatting the date. 

Currently if this value is `undefined` then it falls back to the value of the [`LOCALE_ID`](https://angular.io/api/core/LOCALE_ID) injectable. And if this is not provided by the application the fallback is `DEFAULT_LOCALE_ID`, which `'en-US'`.

I wonder if we could arrange so that a locale of `'ISO'` (or `'iso'`) would allow the `formatDate()` (and so `DatePipe`) to use ISO formatting rules, rather than the given/current locale? How does that sound?

**Comment by prashanttholia** [comment]
@petebacondarwin, I note that [locale](https://angular.io/guide/i18n#setting-up-the-locale-of-your-app) contains information about language, country, and possibly some other items. I think there would be lots of cases when it would be desired to specify these items along with using ISO format. Will it be possible to specify them together?

**Comment by petebacondarwin** [comment]
Yeah, I don't think it could work for `LOCALE_ID`. Only for the actual calls to `formatDate()` etc. So this is not a workable solution. I think instead, we will need a different solution.

Two ideas that come to mind are:

1. add an additional `iso?: boolean` parameter to `formatDate()` and also to `DatePipe`, and then perhaps have an injectable default for this too.
2. create new function/pipe: `formatDateIso()` and `IsoDatePipe`, which would always use the ISO format whatever the current locale.

Perhaps there is a hybrid approach between the two?

**Comment by petebacondarwin** [comment]
Tracking here #39606.
