### ISSUE TITLE
[IVY] TestBed missing features

### ISSUE THREAD

**Issue by vicb** [angular/angular#25389]
- Some things are still to be implemented for the `Render3DebugContext`:
  - [x] destroying the Debug Nodes when a view is destroyed (`destroyLView`)
  - [x] merge `module_testbed.ts` and `module.ts` - they have a lot of common code
  - [x] do not duplicate the `MetadataOverrider` but use the version in the browser dynamic platform
  - [ ] see `TODO`s in the code

As of today `TestBed` tests are not executed in IVY mode - because the TestBed does not support IVY prior to this PR. However we can not enable all TestBed tests for IVY because a lot of them are failing because of:
- features that are yet to be implemented in IVY,
- (unexpected) breaking changes in IVY

Because the number of failing test when compiled against IVY is huge we need to implement a strategy that would catch regression in the number of passing tests but would not error on all failing tests. That way we can make sure more tests pass over time but we do not fail for all remaining failing tests.

Reference ie `<element #ref>` or `<ng-template #ref>` are not yet supported - note that template references are not yet supported in IVY.

### How to test (ie `NgForSpec`)

- Edit the NgFor spec and change the main `describe` to `fdescribe`
- execute `bazel test //packages/common/test/...  --define=compile=jit`

### Implement new features / fix existing ones in the `TestBedRender3`

You might need to update the `TestBed` own code to fix issues.  Chances are that you need to update the `DebugContext` to add missing functionalities / fix current version in `packages/core/src/render3/debug.ts`

To test your changes:

- change the `describe` to `fdescribe` in `packages/core/test/test_bed_spec.ts`,
- execute `bazel test //packages/core/test/...  --define=compile=jit`

### related PRs

https://github.com/angular/angular/pull/25369

**Comment by pkozlowski-opensource** [comment]
We've got most of it in master already and the remaining work will be done as part of the making ivy tests passing under `TestBed`. Closing it here as there is no reason to track it separately as a GitHub issue here.
