### ISSUE TITLE
SSR fails if app-root is not your selector

### ISSUE THREAD

**Issue by Chris-Devine** [angular/angular#25384]
## I'm submitting a...

<pre><code>
[ x] Bug report  
</code></pre>

## Current behavior
if i set my first component (app.component.ts) selector to "body" instead of "app-root" then SSR will render the view for the user but the client side app will never kick in. 

The ng serve will also work as it should, so finding the bug proves very difficult

## Expected behavior
(app.component.ts) selector to "body" instead of "app-root" and for SSR to serve the page and then the client side app to take over.

## Minimal reproduction of the problem with instructions

1. Download the universal starter and change "app-root" selector to "body" in app.component.ts
2. the use command $ npm run build:ssr
3. the use command $ npm run serve:ssr

## What is the motivation / use case for changing the behavior?
Because its a bug

## Environment

<pre><code>
Angular version: 6.1

Browser:
all
 
For Tooling issues:
- Node version: v8.9.4
- Platform:  W10

**Comment by trotyl** [comment]
Please provide a minimal reproduction, you can create a new Angular CLI project and share the repo link.

**Comment by ChrisDevinePimss** [comment]
Usually i would but i think that would be a bit overkill when to reproduce it you change app-root to body... pretty simple really.

**Comment by vikerman** [comment]
Don't use body as your Angular component selector.
