### ISSUE TITLE
Deleting path from route based on condition

### ISSUE THREAD

**Issue by shabbir-dhangot** [angular/angular#25385]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[X] Removing some routes from the array.
</code></pre>

## Current behavior
I want to create a specific build based on the condition. For that I don't want some of the paths of routes. I tried to delete it but its not deleting. 

Code as below
<pre><code>
var vendor=true;
const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'admins', loadChildren: './admin/admin.module#AdminsModule' },
  { path: 'career', loadChildren: './career/career.module#CareerModule' },
  { path: 'contact', loadChildren: './contact/contact.module#ContactModule' }
]
if(vendor){
    var i=0;
    var found;
    console.log( "My routes", routes)
    routes.forEach(element => {
      console.log(element)
      if(element.path == "career"){
        found=i
        console.log("inside" ,found);
      }
      i++;
  });
  console.log(found);
  routes.splice(found,1);
}
export const routing: ModuleWithProviders = RouterModule.forRoot(routes);
</code></pre>

## Expected behavior
On the final variable its deleting that career page but still its coming in build

## Environment

<pre><code>
Angular version: 5.2.5
</code></pre>

**Comment by jasonaden** [comment]
The Routes array needs to be analyzed by the AOT compiler, so you can't do runtime checks such as this. You should consider the Routes array provided is a constant.

**Comment by shabbir-dhangot** [comment]
@jasonaden appreciate your response. I have done this with defining another route file and using it based on environment variable. 

Thank you for response.
