### ISSUE TITLE
Form doesn't detect prefilled data on onChange events

### ISSUE THREAD

**Issue by Nehareeka** [angular/angular#25398]
## I'm submitting a...
<pre><code>
[x] Bug report 
</code></pre>

## Current behavior
The form is multi-step. There is an event bound to a field in the first steps. When the onChange event triggers, the fields in the next steps(though already filled by user) are shown as "null" which makes the step INVALID. 
Then, the user needs to either make change in the field of that particular step or refresh the form in order to proceed with the form steps.

## Expected behavior
The fields should detect the prefilled data and show VALID once any change event is triggered.

## What is the motivation / use case for changing the behavior?
Blocked if the user decides to fill the multi-step form, goes back to any previous step, changes any field on which change event is bound.

## Environment

<pre><code>
Angular version: 5.2.9
</code></pre>

**Comment by Nehareeka** [comment]
Possibly a fix should be provided in updateValueAndValidity method of forms.js to run it on fields instead of just the parent in case of an onChange event

**Comment by kara** [comment]
@Nehareeka There isn't enough information in the description to investigate your issue, as there is no code. If you think there is a bug in Angular forms, please file a new issue with a minimal Stackblitz reproduction. Closing, as this isn't actionable.
