### ISSUE TITLE
Production build destroys pattern

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#25390]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
ng build --prod removes back slashes of pattern

`pattern="^\d{2}\.\d{2}\.\d{4}$"`

is converted to

`pattern="^d{2}.d{2}.d{4}$"`

## Expected behavior
`ng build --prod` should not destroy the pattern

## Minimal reproduction of the problem with instructions
Use the pattern in any project on an input field and build it with `ng build --prod`.

## Environment
<pre><code>
Angular CLI: 6.1.2
Node: 10.6.0
OS: darwin x64
Angular: 6.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-ng-packagr   0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.7.2
@angular/cli                       6.1.2
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.8
@schematics/angular                0.7.2
@schematics/update                 0.7.2
ng-packagr                         3.0.6
rxjs                               6.2.2
typescript                         2.9.2
webpack                            4.8.3
</code></pre>

**Comment by kara** [comment]
This does not look like an Angular issue. Please file any CLI issues in the angular/angular-cli tracker.
