### ISSUE TITLE
Angular Service Worker makes http requests once offline

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [angular/angular#25405]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have Angular 6 app with SW configured.
<pre><code>
"dataGroups": [
        {
            "name": "cms",
            "urls": [
                "/api/settings/**"
            ],
            "cacheConfig": {
                "maxSize": 100,
                "maxAge": "1d",
                "strategy": "freshness",
                "timeout": "2s"
            }
        }
    ]
</code></pre>

and everything works fine axcept that when i enable offline in chrome dev tool and navigating through previosly visited pages back and forward after some random routrips instead of giving back cached data it tries to make actual request sand retrieves 504.

I have tried different configurations but it isame result Here is requests for 2 pages (https://drive.google.com/file/d/1p2qT3QQ_5uf6izONzLkmPf-lGIc0-e02/view?usp=sharing). As you can see get-sub-pages request 2 times is comming from SW but the third one he is trying to do real request. Any idea?

## Expected behavior
When offline do not try to call service.

## What is the motivation / use case for changing the behavior?
To have PWA

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 67.0.3396.99
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 
- Platform:  Windows
</code></pre>

**Comment by vytautas-pranskunas-** [comment]
I have tried to rebuild it once again to see debug information now it does not call network (because i made redirect on no network exception) and i can see this network activity. Not sure if it is ok now!? I had imagination that requests that comes from W should also be 200.

![image](https://user-images.githubusercontent.com/3918999/44057269-e681e48e-9f4a-11e8-9bda-7636e23840a2.png)

However i did not changed anything but i can navigate as many times back and forward i want. This was not the case when i reported this issue (you could see network activity there). 
In debug mode i can see only failed gogle analytics requests

![image](https://user-images.githubusercontent.com/3918999/44057471-9cc5bacc-9f4b-11e8-9894-2b7199155a09.png)
and
![image](https://user-images.githubusercontent.com/3918999/44057495-aec7443e-9f4b-11e8-836f-8cac619f5d5d.png)

so is that behaviour correct now? If yes - I have no idea why it started to work because i was working on another tasks for 2 weeks.

p.s. out of the topic - is there any way to prvent google analytics calls once offline or?

**Comment by gkalpak** [comment]
The "new" behavior seems correct. The requests with the little gear in front of them originate from the SW and go out to the network. They are expected to be non-200 when offline. The requests without the gear are made from the app and handled by the SW, which returns the response from cache since the network request failed (as expected).

So, I am going to close this since everything seems to work as expected (now :grin:).

<sub>(Regarding analytics, I don't know of any way to avoid calls when offline. I don't think there is a reliable way to know you are offline anyway.</sub>

**Comment by vytautas-pranskunas-** [comment]
You can close it ofcourse but that bahaviour i had was just befor demo and i was rebuilding like 3 times everything because i was surprised that it stopped working... So now i do not have guarantee that it would not stop working again... :(

**Comment by vytautas-pranskunas-** [comment]
As i said i am have no guarantee that it will work - it happened again - api calls are not cached any more. Somehow it seems like SW offline behaviour is unstable.

**Comment by vytautas-pranskunas-** [comment]
Data caching stopped again, After openning ngsw/state i can see some errors there:

Error(Hash mismatch (cacheBustedFetchFromNetwork): https://localhost:4000/index.html: expected a61e573dd9b8dbc91555b705e3877ee450091b91, got 8a5bd23c069fdf7b0a44af0795ab2e3f1ab99289 (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://localhost:4000/index.html: expected a61e573dd9b8dbc91555b705e3877ee450091b91, got 8a5bd23c069fdf7b0a44af0795ab2e3f1ab99289 (after cache busting)
    at PrefetchAssetGroup.<anonymous> (https://localhost:4000/ngsw-worker.js:675:35)
    at Generator.next (<anonymous>)
    at fulfilled (https://localhost:4000/ngsw-worker.js:304:62)) Error occurred while updating to manifest 2f9730e779f10527a670da9ba5be506d750473ae

and 

[42m32s996u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(...domain/api/settings/get-sub-pages?some-params)

any ideas why?
