### ISSUE TITLE
ViewProviders override providers if providers contain the same token as viewProviders

### ISSUE THREAD

**Issue by IliaVolk** [angular/angular#25404]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Console prompts taken from https://stackblitz.com/edit/angular-viewproviders?file=src%2Fapp%2Fhello.component.ts
`viewProviders` override `providers` if `providers` contain the same token as `viewProviders`
If component contains
```
  viewProviders: [{
    provide: View,
    useClass: ViewProvider,
  }],
  providers: [{
    provide: View,
    useClass: SimpleProvider,
  }],
```
console contains
```
In content: ViewProvider {}
In view: ViewProvider {}
```
If component contains 
```
  viewProviders: [{
    provide: View,
    useClass: ViewProvider,
  }],
  providers: [],
```
console contains
```
In content: null
In view: ViewProvider {}
```
## Expected behavior
If component contains
```
  viewProviders: [{
    provide: View,
    useClass: ViewProvider,
  }],
  providers: [{
    provide: View,
    useClass: SimpleProvider,
  }],
```
console contains
```
In content: SimpleProvider {}
In view: ViewProvider {}
```
If component contains 
```
  viewProviders: [{
    provide: View,
    useClass: ViewProvider,
  }],
  providers: [],
```
console contains
```
In content: null
In view: ViewProvider {}
```

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-viewproviders?file=src%2Fapp%2Fhello.component.ts

## What is the motivation / use case for changing the behavior?
Provide different objects to content and view parts
Isolate viewProviders from access from outside

## Environment

<pre><code>
Angular versions: 5.1.0, 6.1.0, 7.0.0-beta.1

Browser:
All

**Comment by IliaVolk** [comment]
Also in this reproduction https://stackblitz.com/edit/angular-viewproviders-2?file=src%2Fapp%2Fhello.component.ts
```
@Directive({
  selector: 'hello',
  providers: [{
    provide: View,
    useClass: SimpleProvider,
  }],
})
export class SupportDirective {}


@Component({
  selector: 'hello',
  template: `<h1>Hello {{name}}!<view></view></h1>`,
  styles: [`h1 { font-family: Lato; }`],
  viewProviders: [{
    provide: View,
    useClass: ViewProvider,
  }],
})
export class HelloComponent  {
```
Expected:
```
In content: SimpleProvider {}
In view: ViewProvider {}
```
Actual:
```
In content: null
In view: SimpleProvider {}
```

**Comment by kara** [comment]
Looks like this is fixed in Ivy version 9: https://stackblitz.com/edit/angular-ivy-rvdank?file=src%2Fapp%2Fhello.component.ts

But it looks like VE still has this bug, so keeping the issue open.

**Comment by JoostK** [comment]
This is indeed working as expected in Ivy however I can't find a corresponding acceptance test, so I'll keep this open to add such a test.

**Comment by AndrewKushnir** [comment]
Closing this ticket since it was marked as ViewEngine-specific and ViewEngine is deprecated. Please reopen if the problem still exists in the latest version of Angular (powered by Ivy).
