### ISSUE TITLE
The return value from the function at the interface is different from the actual return value.

### ISSUE THREAD

**Issue by yagizayer** [angular/angular#25412]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I am trying to do some operations using "IOperation" interface. but i have strange error.
When i log operation values or operation result, there is no problem but when i try to log interface itself, i get overwrited operation values and result. my english is not very good so i put my code here...

## Expected behavior
console logs should be correct and not contradict with itself.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-flpdu1?embed=1&file=src/app/app.component.ts

## What is the motivation / use case for changing the behavior?
I think it is internal problem on angular and i don't know how to fix it

## Environment

<pre><code>
Angular version: 6.0.5

Browser:
- [x] Opera (desktop) version 54.0
- [x] Chrome (desktop) version 68.0
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.11.2  
- Platform:  Windows

Others:
![adsiz](https://user-images.githubusercontent.com/40693974/43910624-0006d600-9c06-11e8-8e33-c22fe4c5f41c.png)
</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mlc-mlapis** [comment]
@yagizayer ... there is no code for interface in final JS code ... it's only for TS typing.

**Comment by benlesh** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
