### ISSUE TITLE
EventEmitter subscribe

### ISSUE THREAD

**Issue by pablochud** [angular/angular#25411]
Did you ever really plan to deprecate subscribe method? Is it true the properly usage EventEmitter is to emit events from one component to another?

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
