### ISSUE TITLE
Create Angular new project Issues with newest version

### ISSUE THREAD

**Issue by chaoy8888** [angular/angular#25414]
Dear Sirs/Madams:
## I'm submitting a issue for:

Our company plan to use Angular to do web development.
So I installed new Aguilar new version (first time) to my Window 7 enterprise , 64 bit machine.
It is installed successfully. But when I start to create the new project. It is failed.

I got some warnings, sample as: 
19362 warn tar ENOENT: no such file or directory, open 'C:\Source\Angular\Hellow2\node_modules\.staging\@angular\core-b4057708\src\sanitization\bypass.d.ts'
19363 warn tar ENOENT: no such file or directory, open 'C:\Source\Angular\Hellow2\node_modules\.staging\@angular\core-b4057708\src\sanitization\html_sanitizer.d.ts'
19364 warn tar ENOENT: no such file or directory, open 'C:\Source\Angular\Hellow2\node_modules\.staging\@angular\core-b4057708\src\sanitization\inert_body.d.ts'

error:

19460 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
19461 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Source\Angular\Hellow2\node_modules\.staging\fsevents-3c65a4c2\node_modules\abbrev' -> 'C:\Source\Angular\Hellow2\node_modules\.staging\abbrev-69719517'
19462 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
19462 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
19463 verbose stack Error: sha512-IMaqx1gIYMqrori41bITgm22patbde/SRINiSggeUqegVhX4b2wIZ6ALIyT6utD2CC9n7oHQgp/VpMVMOIg0yA== integrity checksum failed when using sha512: wanted sha512-IMaqx1gIYMqrori41bITgm22patbde/SRINiSggeUqegVhX4b2wIZ6ALIyT6utD2CC9n7oHQgp/VpMVMOIg0yA== but got sha512-06C1zhmQNBFmEAbjfPKgQUFUhhwcRtKqOcQWTmPQYiIiEFWZWvinD/nNow8b3m5zNMw5Vdq5kohX3Vjumuq7ZA==. (5182224 bytes)
19463 verbose stack     at Transform.on (C:\Program Files\nodejs\node_modules\npm\node_modules\ssri\index.js:275:19)
19463 verbose stack     at emitNone (events.js:111:20)
19463 verbose stack     at Transform.emit (events.js:208:7)
19463 verbose stack     at endReadableNT (_stream_readable.js:1064:12)
19463 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
19463 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
19464 verbose cwd C:\Source\Angular\Hellow2
19465 verbose Windows_NT 6.1.7601
19466 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--quiet"
19467 verbose node v8.11.3
19468 verbose npm  v5.6.0
19469 error code EINTEGRITY
19470 error sha512-IMaqx1gIYMqrori41bITgm22patbde/SRINiSggeUqegVhX4b2wIZ6ALIyT6utD2CC9n7oHQgp/VpMVMOIg0yA== integrity checksum failed when using sha512: wanted sha512-IMaqx1gIYMqrori41bITgm22patbde/SRINiSggeUqegVhX4b2wIZ6ALIyT6utD2CC9n7oHQgp/VpMVMOIg0yA== but got sha512-06C1zhmQNBFmEAbjfPKgQUFUhhwcRtKqOcQWTmPQYiIiEFWZWvinD/nNow8b3m5zNMw5Vdq5kohX3Vjumuq7ZA==. (5182224 bytes)
19471 verbose exit [ 1, true ]

I attached the log file.
I tried to install again to fix that, it is failed still.

Please give me some instruction for that. 

Thanks
Chao

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Minimal reproduction of the problem with instructions

run command:  ng new Hellow --routing

## What is the motivation / use case for changing the behavior?
[2018-08-09T16_06_57_307Z-debug.log](https://github.com/angular/angular/files/2275246/2018-08-09T16_06_57_307Z-debug.log)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: V8.11.3 
-  NPM version: 5.6.0
- Platform:  Windows 7, 64 bit

Others:

</code></pre>

**Comment by benlesh** [comment]
Issue moved to Angular-CLI: https://github.com/angular/angular-cli/issues/11837
