### ISSUE TITLE
Angular apps crash when run by Googlebot or PhantomJS

### ISSUE THREAD

**Issue by schnauss** [angular/angular#25416]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have an Angular 6 app generated with Angular-CLI which works great on Chrome, Firefox and Safari. When I try to scrape it with Googlebot, however, it crashes. I have tried to simulate the issue with PhantomJS (which sources indicate is what Google uses) and I get the following console error:

```
TypeError: undefined is not a constructor (evaluating 'new Array(HEADER_OFFSET).fill(null)')

  http://localhost:4200/vendor.js:44446 in ./node_modules/@angular/core/fesm5/core.js
  http://localhost:4200/runtime.js:77 in __webpack_require__
  http://localhost:4200/main.js:199 in ./src/main.ts
  http://localhost:4200/runtime.js:77 in __webpack_require__
  http://localhost:4200/main.js:224
  http://localhost:4200/runtime.js:77 in __webpack_require__
  http://localhost:4200/runtime.js:44 in checkDeferredModules
  http://localhost:4200/runtime.js:31 in webpackJsonpCallback
```

It seems that the headless browser is running into `new Array(HEADER_OFFSET).fill(null)` and getting confused because it doesn't know about `Array.prototype.fill()`.

[The relevant line of code is here.](https://github.com/angular/angular/blob/master/packages/core/src/render3/instructions.ts#L71)

## Expected behavior

I expect that the compiled app run properly, under PhantomJS and under Googlebot.

## Minimal reproduction of the problem with instructions

1. Create a new Angular project: `ng new googlebottest`.
2. Serve the project: `ng serve`.
3. Snapshot the page with phantomJS, and watch for console messages `phantomjs googlebottest.js`:
```
var page = require('webpage').create();

page.onConsoleMessage = function(msg, lineNum, sourceId) {
  console.log('CONSOLE: ' + msg + ' (from line #' + lineNum + ' in "' + sourceId + '")');
};

page.open('http://localhost:4200', function() {
  page.render('googlebottest.png');
  phantom.exit();
});

```

## What is the motivation / use case for changing the behavior?

People expect that their Angular projects be scrapable by Google. All that turns up on Googlebot (and PhantomJS) is a white screen.

## Environment

<pre><code>
Angular version: 6.1.2

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.0.0  
- Platform:  Mac 

Others:

</code></pre>

**Comment by textbook** [comment]
PhantomJS isn't a [supported browser](https://angular.io/guide/browser-support). Have you tried adding appropriate polyfills?

**Comment by schnauss** [comment]
Thanks for the tip! I uncommented polyfills and it works in both PhantomJS and Googlebot 👍  For future reference if anyone runs into this, the missing polyfill that led to this error was `import 'core-js/es6/array';`.

I wonder if this is something that could be enabled by default? Obviously PhantomJS isn't a common platform for Angular apps but it seems like this could have a big impact on peoples' SEO if Googlebot renders a white screen.

**Comment by pkozlowski-opensource** [comment]
Closing as resolved. If you believe that this polyffil should be included by default please open an issue in the CLI repo.

BTW, now that we've got headless Chrome, PhantomJS usage should be avoided.

**Comment by thongnx6** [comment]
PhantomJS browser needs so-called polyfills to run all the nifty JS features used by Angular.
- Open `src/polyfills.ts`
- Enable big polyfills block at the top and the intl related ones at the bottom
```
/* ... */

/* enable these */
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

/* ... */

/* and these: */

/**
 * Date, currency, decimal and percent pipes.
 * Needed for: All but Chrome, Firefox, Edge, IE11 and Safari 10
 */
import 'intl';  // Run `npm install --save intl`.
/**
 * Need to import at least one locale-data with intl.
 */
import 'intl/locale-data/jsonp/en';
```
