### ISSUE TITLE
fullTemplateTypeCheck with safe navigation operator doesn't work

### ISSUE THREAD

**Issue by Anarkin** [angular/angular#25422]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
```
<stuff *ngIf="items && items.length">
    "items" is accepted by the linter in this scope as DEFINED (fullTemplateTypeCheck)
</stuff>

<stuff *ngIf="items?.length">
    "items" is NOT accepted by the linter in this scope as defined (fullTemplateTypeCheck)
</stuff>
```
## Expected behavior
Both scenarios work the same way

## Environment
<pre><code>
Angular version: 6

For Tooling issues:
- Node version: latest
- Platform:  Windows

**Comment by mhevery** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by mhevery** [comment]
closed as no repro
