### ISSUE TITLE
Setting headers on HttpClient put method

### ISSUE THREAD

**Issue by mhrzenjak** [angular/angular#25426]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
If headers for the put method are added like this they don't get applied:

```
let headers = new HttpHeaders();
headers.set('Content-Type', 'application/json');
let options = { headers: headers };
this.http.put(baseURL, entity, options);
```
They do get applied if written like this:

`this.http.put(baseURL, entity, {headers: new HttpHeaders({'Content-Type':  'application/json'})});`

Other HttpClient methods (get, post, delete) work either way.

## Expected behavior
Consistent behavior between HttpClient methods.

## Environment

<pre><code>
Angular version: 6.1.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by tomvangreen** [comment]
HttpHeaders is an immutable class. The way your example is made you will always add an empty HttpHeaders object into the put request. 

What you need to do in order for it to work is to assign the return value of the `set` call to headers, as the set function will not change the existing HttpHeaders object but rather creates a new one, with the additional headers added.

    let headers = new HttpHeaders();
    headers = headers.set('Content-Type', 'application/json');
    let options = { headers: headers };
    this.http.put(baseURL, entity, options);

I expect the behaviour to be the same if you use any of the request methods of the HttpClient.

**Comment by textbook** [comment]
_"Other HttpClient methods (get, post, delete) work either way."_ - I'm seeing consistent behaviour as documented, currently on Angular `^6.0.3`.
