### ISSUE TITLE
Router: strict route validation, but not for lazy-loaded modules

### ISSUE THREAD

**Issue by dirkluijk** [angular/angular#25431]
## I'm submitting a...

<pre><code>[X] Bug report  
[X] Documentation issue or request
</code></pre>

## Current behavior

When a `Route` only contains a CanActivate guard:
```typescript
const routes = [
  {
    path: '',
    canActivate: [MyRedirectGuard] // always does a dynamic redirect
  }
];
```
You will get a validation error: 
```
Error: Invalid configuration of route ''. One of the following must be provided: component, redirectTo, children or loadChildren
```

However, when this route is in a lazy-loaded module it works perfectly fine.

## Expected behavior
I expect routes in lazy-loaded modules to have the same validation. However, I wish this validation rule to be less strict, because we use CanActivate guards for dynamic redirects.

If the rule is valid, there should be another way to have dynamic redirects on component-less routes, e.g. a new type of guard:

```typescript
const routes = [
  {
    path: '',
    redirect: MyRedirectGuard
  }
];

interface Redirect {
  redirect(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): string | Promise<string> | Observable<string>;
}

class MyRedirectGuard implements Redirect {
  redirect(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): string {
    return 'some-dynamic-url';
  }
}
```

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/component-less-routes

Uncomment the first route in app.module.ts to trigger the error. However, in feature.module.ts it works fine.

## What is the motivation / use case for changing the behavior?

We use `CanActivate` guards to do dynamic redirects whenever we need to. We only want them to trigger for specific urls, so we have component-less routes:

```typescript
const routes = [
  {
    path: 'feature',
    component: FeatureComponent,
    children: [
      {
        path: '',
        canActivate: [MyRedirectGuard] // checks if we need to go to foo or bar
      },
      {
        path: 'foo',
        component: FooComponent
      },
      {
        path: 'bar',
        component: BarComponent
      }
    ]
  }
];
```
With this construction, when a user navigates to `/feature`, it automatically goes to `/feature/foo` or `/feature/bar`.

We want to be able to do the same in modules that are not lazy-loaded, without the need to provide some kind om "dummy" component.

## Environment

<pre><code>Angular version: 6.1.0</code></pre>

**Comment by jasonaden** [comment]
Agreed. This is an odd behavior and should be relatively straight forward to fix by simply wiring in the validation when lazy loading and issuing a warning about incorrect configurations.

Any chance this is something you would like to create a PR for?

**Comment by dirkluijk** [comment]
Yeah, of course. I will try to fix it for lazy loaded modules. So you agree on making the validation less strict?

**Comment by dirkluijk** [comment]
Proposal: https://github.com/angular/angular/pull/25498

**Comment by atscott** [comment]
> However, I wish this validation rule to be less strict, because we use CanActivate guards for dynamic redirects. 

Covered in #18605 / #13373

Keeping this open, as the issue with validation for lazy-loaded modules is not described in those.
