### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by bhosalevishal** [angular/angular#25439]
There is a typo on this screen/page
https://angular.io/guide/architecture

There are **tow** types of data binding: -- NG.
There are **two** types of data binding: -- OK.

**Comment by JoostK** [comment]
Duplicate of pending PR #25438

**Comment by pkozlowski-opensource** [comment]
Thnx @JoostK - it is indeed a duplicate of pending PR #25438. I'm going to close this issue here as the mentioned PR is approved and will be merged.
