### ISSUE TITLE
Allow Route['resolve'] to be a single value/observable/promise

### ISSUE THREAD

**Issue by th0r** [angular/angular#25430]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
`Route['resolve']` property now must be an object containing resolvers.

## Expected behavior
Allow `Route['resolve']` to be a single resolver and store resolved value right into `route.snapshot.data`.

## What is the motivation / use case for changing the behavior?
I think that adding a separate resolver class stored in a separate file for every single route just for fetching a data (and in most cases it's just a single call to a service method) is a perfect example of overengineering (sorry). Recently I came up with an interesting idea - use page component classes as route resolvers. Here is an example:
```ts
interface Post {
  id: number;
  title: string;
}

const routes: Route[] = [
  {
    path: 'post/:id',
    component: PostPageComponent,
    resolve: {
      post: PostPageComponent
    }
  }
];

@Component({
  selector: 'app-post-page',
  template: 'Title: {{ post.title }}'
})
class PostPageComponent implements OnInit, Resolve<Post> {
  post: Post;

  constructor(
    private posts: PostsService,
    private route: ActivatedRoute
  ) {}

  async resolve(route: ActivatedRouteSnapshot): Promise<Post> {
    return this.posts.get(route.params.id);
  }

  ngOnInit() {
    this.post = this.route.snapshot.data.post;
  }
}

@Injectable()
class PostsService {
  async get(id: Post['id']): Promise<Post> {
    // ...fetch post...
    return {id: 1, title: 'Foo'};
  }
}
```
So I just use `PostPageComponent` as resolver for post page data and it works great except one little nuance: I have to provide a name for resolved resource in route configuration (`post` key in `resolve` object) but I don't need it because I want `PostComponent` to fetch all the necessary data and put it straight into the `route.snapshot.data` object. Here is the example:
```ts
class PostPageComponent implements OnInit, Resolve<PostPageData> {
 // ...
  async resolve(route: ActivatedRouteSnapshot): Promise<PostPageData> {
    const author = this.authors.get(route.params.authorId);
    const post = this.posts.get(route.params.postId);
    return {
      author: await author,
      post: await post
    };
  }
  
  ngOnInit() {
    const {author, post} = this.route.snapshot.data as PostPageData;
    this.author = author;
    this.post = post;
  }
  // ...
}
```

Of course I can rename `post` key into `data` but in this case accessing it will look like `route.snapshot.data.data` and it bothers me a little.

So what I propose is to allow `Route['resolve']` property to be a single value / observable / promise. In this case it's resolved value will be stored right into `route.snapshot.data`. If route contains a static `data` object it can be merged into the data from the resolver.

## Environment

<pre><code>
Angular: 6.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router, upgrade
</code></pre>

**Comment by jasonaden** [comment]
I like the idea. I don't think this is something we will be able to get to immediately, but it's something we could work on with the community. Please post here if interested in helping on this, and mention me.

**Comment by th0r** [comment]
> Resolvers are separate services so the component doesn't need to be created.

I understand that but I don't see any value in using a separate service for every single property in the resolved data.

> Some nested resolver can do a redirect to other page and parent components would not be created when it's not required.

Creation of the component instance is just an invocation of it's constructor and injecting dependencies so it should be as cheap as creation of the resolver's instance, right?

> Note that all dependencies must be present when creating a component instance, dependencies as ActivatedRoute or ElementRef and the navigation is not finished yet during resolve.

 I understand that deps like `ElementRef` will not be initiated but you don't need them to fetch the component's data.

Actually, this issue is not about using component as a resolver but about allowing to provide a single resolver instead of a resolver-per-data-property.

**Comment by dawidgarus** [comment]
> I understand that but I don't see any value in using a separate service for every single property in the resolved data.

Resolvers could be reused in other components, which require different set of data where some are overlaping.

> Component-as-resolver can do redirect too and creation of the component instance is just an invocation of it's constructor and injecting dependencies so it should be as cheap as creation of the resolver's instance, right?

Not necessarily. In simple cases yes, but services are created lazily when they are injected and You might want to delay it when not needed. Also You can have component level providers injected to components which You might not want to create yet. And, you are mixing dependencies for resolver and dependencies for component.

> I understand that deps like ElementRef will not be initiated but you don't need them to fetch the component's data.

But You need them to create component instance. Making change so the dependencies would not be ready to use in constructor will break a lot of existing code. Simple example:
```typescript
export class MyComponent {
  readonly element: HTMLElement;
  constructor(elementRef: ElementRef) {
   this.element = elementRef.nativeElement as HTMLElement;
  }
}
```
Constructor is the place to initialize instance properties. Moving it to `ngOnInit` wouldn't feel right.

> Actually, this issue is not about using component as a resolver but about allowing to provide a single resolver instead of a resolver-per-data-property.

You can do it already like this:
```
resolve: { _: PostPageResolver }
```
and:
```
 const {author, post} = this.route.snapshot.data._ as PostPageData;
```

**Comment by th0r** [comment]
> Resolvers could be reused in other components, which require different set of data where some are overlaping.

Reusing resolvers for different routes requires all the route parameters to have the same name and this is a noticeable limitation.

> Not necessarily. In simple cases yes, but services are created lazily when they are injected and You might want to delay it when not needed. Also You can have component level providers injected to components which You might not want to create yet. And, you are mixing dependencies for resolver and dependencies for component.
> 
> EDIT: and remember that services don't have OnInit hook. Most of the initialization is done in constructor.

All of this is not an issue for me.

> Constructor is the place to initialize instance properties. Moving it to ngOnInit wouldn't feel right.

Why not? Most of the properties require inputs to be initialized so `ngOnInit` hook is completely ok. I don't see any reason to spread properties initialization between constructor and ngOnInit.

> resolve: { _: PostPageResolver }

You've just renamed `data` to `_` in my example above. It looks like a workaround, not a real solution.

> EDIT: Also, note that not only resolvers populate route data. There's also data property in route config.

Here is the quote from the main post:
`If route contains a static data object it can be merged into the data from the resolver.`
