### ISSUE TITLE
using ng-control/ng-model/ng-form-control with custom components

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#2543]
Say I have simple component:
```js
import { Component, View } from 'angular2/angular2';
@Component({
    selector: 'checkbox'
})
@View({ template: ´<div></div>´ })
export class Checkbox {}
```
And I want to use one of `ng-control`/`ng-form-control` on it:
```html
<checkbox [ng-control]="foo"></checkbox>
```
How would I go about it? Right now I get an exception `No value accessor for ''` when I try to use it.

**Comment by pkozlowski-opensource** [comment]
You didn't list forms directives in the `@View` annotation, for a start....

**Comment by rolandjitsu** [comment]
@pkozlowski-opensource does the custom component need them? Because I have those directives listed in the place that `<checkbox [ng-control]="foo"></checkbox>` is used.

**Comment by pkozlowski-opensource** [comment]
@rolandjitsu sorry, I've miss-interpreted your code snippet - you don't need to list things that you are not using in your tpl

**Comment by rolandjitsu** [comment]
@pkozlowski-opensource no worries, I should have been more descriptive :) Probably the form control directives expect the node to have a `value` property, otherwise I am unsure why I get the exception.

**Comment by vicb** [comment]
@rolandjitsu the built-in checkbox might be a good starting point: https://github.com/angular/angular/blob/master/modules/angular2/src/forms/directives/checkbox_value_accessor.ts

**Comment by rolandjitsu** [comment]
@vicb thanks, that actually helps. Just that I'm fixed on version alpha 26 and the api has changed. I'm looking forward to the next release :)

**Comment by rolandjitsu** [comment]
@vicb I've tried to find a way to do it but I seem to be failing. So I created the following component (a combination of the `CheckboxValueAccessor` and the angular material checkbox):
```js
import { NumberWrapper, isPresent } from 'angular2/src/facade/lang';
import { KeyboardEvent } from 'angular2/src/facade/browser';
import { Renderer, ElementRef } from 'angular2/angular2';
import { Component, View, Attribute } from 'angular2/annotations';
import { ControlValueAccessor, NgControl } from 'angular2/forms';

import { KEY_SPACE } from 'common/constants';

@Component({
	selector: 'checkbox',
	properties: [
		// 'checked',
		'disabled'
	],
	host: {
		'(keydown)': 'onKeydown($event)',
		'(change)': 'onChange($event.target.checked)',
		'(blur)': 'onTouched()',
		'[checked]': 'checked',
		'[tabindex]': 'tabindex',
		'[attr.role]': '"checkbox"',
		'[attr.aria-checked]': 'checked',
    	'[attr.aria-disabled]': 'disabled',
		'[class.ng-untouched]': 'cd.control?.untouched == true',
		'[class.ng-touched]': 'cd.control?.touched == true',
		'[class.ng-pristine]': 'cd.control?.pristine == true',
		'[class.ng-dirty]': 'cd.control?.dirty == true',
		'[class.ng-valid]': 'cd.control?.valid == true',
		'[class.ng-invalid]': 'cd.control?.valid == false'
	}
})

@View({
	templateUrl: 'app/components/checkbox/checkbox.html',
	styles: [
		'@import "checkbox.css";'
	],
})

export class Checkbox implements ControlValueAccessor {
	checked: boolean;
	tabindex: number;
	onChange: Function;
	onTouched: Function;
	_disabled: boolean;
	
	constructor(private cd: NgControl, private renderer: Renderer, private elementRef: ElementRef, @Attribute('tabindex') tabindex: string) {
		this.checked = false;
		this.tabindex = isPresent(tabindex) ? NumberWrapper.parseInt(tabindex, 10) : 0;
		this.onChange = (_) => {};
		this.onTouched = (_) => {};
		cd.valueAccessor = this;
		this._disabled = false;
		
		console.log(renderer, elementRef, cd);
	}
	
	get disabled() {
		return this._disabled;
	}

	set disabled(value) {
		this._disabled = isPresent(value) && value !== false;
	}
	
	toggle(event) {
		if (this.disabled) return event.stopPropagation();
		this.checked = !this.checked;
	}
	registerOnChange(fn): void {
		this.onChange = fn;
	}
	registerOnTouched(fn): void {
		this.onTouched = fn;
	}
	writeValue(value) {
		this.checked = value;
		this.renderer.setElementProperty(
			this.elementRef.parentView.render,
			this.elementRef.boundElementIndex,
			'checked',
			value
		);
	}
	
	onKeydown(event: KeyboardEvent) {
		if (event.keyCode != KEY_SPACE) return;
		event.preventDefault();
		this.toggle(event);
	}
}
```
And I am trying to use it with a `ng-control` in some other place:
```html
<checkbox ng-control="status"></checkbox>
```
And yes, I do include the directive `Checkbox` in the view I use the custom checkbox. I am also attaching an observer to the `valueChanges` on this custom checkbox, but nothing triggers:
```js
ObservableWrapper.subscribe(that.status.valueChanges, function (value) {
    console.log(value);
})
```
Obviously, `that.status` is the binding created with `ng-control="status"`. It works fine with a `<input type="checkbox>"`, but not with this component. Some more guidance would be nice if possible :)

**Comment by mhevery** [comment]
This is a problem with lack of documentation. @vsavkin could you help out and close this issue.

**Comment by rolandjitsu** [comment]
@vsavkin / @mhevery I figured out how to trigger that `change` event that seemed to not get triggered. I used `EventEmitter` in combination with `events: ['change']` on the [component](https://github.com/rolandjitsu/ng2-play/commit/2e3599eee1c1ddde585c075ee3da74656b9c6dc2).

I am not sure if this is how I'm supposed to handle it, but it seems to work now. Maybe there is another way that is not documented?!

**Comment by rsnider19** [comment]
I am trying to implement my own dropdown component with ngModel and ngControl, but I am getting a `No value accessor for''`. I have the component implementing `ControlValueAccessor` in this [plunk](https://plnkr.co/edit/ESlzDoTl6wgmrJXZTzA8), but there is a fair chance that I am doing it wrong. Looking at my code, I'm pretty sure that the two-way binding won't actually work, but I was expecting it to still render the component.

**Comment by zoechi** [comment]
Seems value accessors need to be registered with DI.

https://plnkr.co/edit/Bz7wLC5qq7s6Fph1UwpC?p=preview
I basically added

    providers: [provide(NG_VALUE_ACCESSOR, {useClass: UIDropdownComp, multi: true})]

to `UIDropdownComp`

I got rid of the error message but don't have time to check if the component now works as intented. I leave this for you as exercise ;-)

**Comment by zoechi** [comment]
I don't know where I have this [plunker link](http://plnkr.co/edit/slVMz6Kgv6KlnUNMDe3o?p=preview) Here they are taking a bit a different approach. They inject `ngControl` to the component and set `ngControl.valueAccessor = this`. Seems the result is the same but by a different approach.

**Comment by KellySGT** [comment]
Hi Zoechi,
 
Thanks for the very clear sample code. But when I run it: 
https://plnkr.co/edit/Bz7wLC5qq7s6Fph1UwpC?p=preview

the [selected] does not change with the selection, something changed meanwhile? The selected showing next to the select control is always B regardless what is selected. I tried on both Firefox and Chrome.

Very nice sample!

Kelly

**Comment by KellySGT** [comment]
Hi Zoechi,

Never mind, I realized your code did not mean to show selection in your {{selected}}. It seems to show selected value in app.ts, an event needs to be fired:

<div>
      <h2>Hello {{name}}</h2>
      <ui-dropdown [options]='OPTIONS'
           (myevent)="handleMyEvent($event)"></ui-dropdown>
           {{selected}} mySel: {{selectedValue}}
</div>

in class App add:
   handleMyEvent(arg){
       console.log("in parent handling myEvent", arg);    
        this.selected = arg;
  }

Also add event for selection change to set value using .next function.
Tried it in your plunk site and this approach works. I wonder if it is possible to use ngModel in parent to get selected value someway.

Kelly

**Comment by WilldelaVega777** [comment]
Hi, after updating from RC1 to RC4 my ValueAccessors are not working anymore, I changed references from @angular/common to @angular/forms for ControlValueAccessor, NG_VALUE_ACCESSOR, but my component still doesn't work with ngModel,  any idea of what I need to change or where is the documentation for this (seemingly obscure) feature?
