### ISSUE TITLE
[Feature Request] Annotation to replace {providedIn: 'root'} for @Injectable() with @RootInjectable()

### ISSUE THREAD

**Issue by oleersoy** [angular/angular#25441]
[x ] Feature request

So in other words if we want the service to be provided in the `root` we just write:

```
@Injectable()
export class MyService ...
```

**Comment by jotatoledo** [comment]
what is the current behavior?

**Comment by oleersoy** [comment]
In all the Angular 6 examples I have seen this is what is done:

```

@Injectable({
  providedIn: 'root'
})
export class TodosService {
```
I'm assuming that 99.9% of the time we want the `@Injectable` to be provided in root, so it should be the default.  If we want it to be provided somewhere else, then we should specify that that is what we want.

**Comment by mlc-mlapis** [comment]
@oleersoy ... but it is the actual syntax from the very beginning of Angular 2 ... so you would introduce a breaking change by that and this is unacceptable.

**Comment by mlc-mlapis** [comment]
@oleersoy ... looks that you don't want to understand that ... how anybody would differentiate the state before and after then?

**Comment by oleersoy** [comment]
When the `@Injectable` annotation runs, which only happens during class loading` the service will be provided in the `root` application dependency injection container if you do `@injectable()` or if you do `@injectable({providedIn: 'root'})`, so there is zero difference between the do.  In the first case, the decorator assumes that `{providedIn: 'root'}` is what you want, in the second case you are just making it explicity.

**Comment by mlc-mlapis** [comment]
@oleersoy ... and what about lazily loaded modules?

**Comment by oleersoy** [comment]
@Injectable({
  providedIn: 'root'
})
export class TodosService {

**Comment by mlc-mlapis** [comment]
@oleersoy ... what? You suggest changing the behavior of the default `@Injectable({})` which is the actual syntax.

**Comment by oleersoy** [comment]
OK - So suppose we have a module.  It's not loaded yet.  It gets loaded and when it's loaded angular injects the service that is annotated with `@injectable()` into the root application container.  What am I missing?

**Comment by mlc-mlapis** [comment]
@oleersoy ... actually `@Injectable()` on services in lazily loaded modules are not instantiated as singletons. They are instances on those modules level.

**Comment by oleersoy** [comment]
Why does it matter what level the service is injected at?  The best practice is to inject it into the root level container.  If you want it injected specifically into a module level container, then specify that like this:

```
@Injectable({
  providedIn: 'thismodule'
})
export class TodosService 
```

But if you do:

```
@Injectable({
  providedIn: 'root'
})
export class TodosService {
```
In other words you are saying inject into the root level container ... it's the same as doing `@injectable()`

**Comment by mlc-mlapis** [comment]
@oleersoy ...but you are still missing the millions of lines of existing code which are written as `@Injectable()` and suppose that the instances are created on lazily loaded modules level and not on root container.

**Comment by mlc-mlapis** [comment]
@oleersoy ... this syntax doesn't exist:
```
@Injectable({
  providedIn: 'thismodule'
})
export class TodosService
```

**Comment by oleersoy** [comment]
So introduce:

```
@Injectable({
  providedIn: 'thismodule'
})
export class TodosService
``
And make `@injectable()` inject into the root container. 

If you keep it the way it is now, then the 1.4 million devs downloading angular each month have to write additional unnecessary boilerplate, whereas the the current lines of code can either stick to the framework the way it is now, or upgrade and change their `@injectable` annotation a little bit.

**Comment by oleersoy** [comment]
Or if it's such a massive deal just introduce a new annotation `@rootinject` that more specifically says the the service will be injected into the root container.

**Comment by benlesh** [comment]
I'm very sorry, I'm not really sure what this issue is describing as a feature request. Please make sure the opening comment in the issue describes the feature you're requesting, so whoever is triaging issues for the Angular team doesn't have to read the whole thread to get the gist (there's a lot to go through). Can you please submit a new issue with a detailed description of the feature you're requesting? Closing this one for now.
