### ISSUE TITLE
Tutorial live example is broken

### ISSUE THREAD

**Issue by kberg** [angular/angular#25446]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
https://angular.io/tutorial provides a link to a `live example`. This link, https://angular.io/generated/live-examples/toh-pt6/eplnkr.html, results in a 404.

## Expected behavior
Yeah, I expected to get a live example! :)

## Minimal reproduction of the problem with instructions
* Navigate to https://angular.io/tutorial
* Click on `live example`.

## What is the motivation / use case for changing the behavior?
Should be obvious.

## Environment

<pre><code>
Angular version: n/a

Browser:
- [X] Chrome (desktop) version 67.0.3396.99
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Ploppy3** [comment]
You may be looking at a old version of the angular.io website, the update may be broken and you may be stuck at an outdated version. If the website does not update by itself, clear the cache of the website.

In the meantime, here is the link of the live example : https://stackblitz.com/angular/lklvbvqexqj

**Comment by kberg** [comment]
Maybe, but I cleared my cache, and got the same result: https://angular.io/generated/live-examples/toh-pt6/eplnkr.html Hmm.

**Comment by jenniferfell** [comment]
Thanks, all. Looks like this is resolved. Clearing the browser cache worked. Doc is correct. LIve example goes to stackblitz: https://angular.io/generated/live-examples/toh-pt6/stackblitz.html
