### ISSUE TITLE
Angular 2+  : refresh page (one component) from other component

### ISSUE THREAD

**Issue by puruprajapati** [angular/angular#25444]
I do have navigation component with a dropdown. On value change of dropdown , other component/page should be refreshed. But these two components are not child and parent.

On navigation component I do have value change method as

```
  changeLocation(loc: string){
    this.selectedLocation = loc;
    localStorage.setItem("userLocation", loc);
    this.getLocation.emit(loc);
  }
```
this will set the value in localstorage, as this needs to be checked in other components as well.

Other page is using this local value to render the page in oninit

```
ngOnInit(){
        var userLocation = localStorage.getItem("userLocation")
        window.scroll(0,0);

        this.venueService.getAllVenues().subscribe(data => {
            this.venues = data.filter(
                v => v.address1 === userLocation);
        })
    }
```

On value change of dropdown, I am not able to refresh the page.
Even though i use route to navigate the same page, it wont call ngoninit as page is already initialized.

Is there any way to forcefully destroy the route , so that ngoninit will get executed each time i do navigate to this page. 

Or is there any way, I can refresh the page on the value change of dropdown.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
