### ISSUE TITLE
NgIf/EventEmitter memory leak

### ISSUE THREAD

**Issue by JohnKis** [angular/angular#25459]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Detached DOM nodes are not cleared up if a child component is removed using *ngIf if the change has been triggered by the child. 

## Expected behavior
Detached DOM nodes should be cleared in all cases to avoid memory leaks.

## Minimal reproduction of the problem with instructions

Since the issue is not apparent on Stackblitz, I created a demo repository.
### Steps to reproduce

- Clone repo: https://github.com/JohnKis/angular-memleak-demo
- Install dependencies
- Run ng serve
- Open the project in Chrome
- Open Chrome DevTools and navigate to the Memory tab
- Click on the Collect Garbage icon
- In the app, click on the Toggle button to show the title and click again to hide it
- In DevTools, click on the Collect Garbage icon
- Take a heap snapshot and verify that there aren't any detached nodes
- In the app, click on the Toggle button to show the title
- Click on the Close button
- In DevTools, click on the Collect Garbage icon
- Take a heap snapshot and observe that there are detached nodes that haven't been garbage collected

The issue only seem to happen if the *ngIf condition change is triggered from the component the *ngIf directive is applied on.

## What is the motivation / use case for changing the behavior?
I have multiple web apps that are running on appliances 24/7. Since this bug causes a constant memory leak, eventually the apps will slow down and crash.

## Environment

<pre><code>
Angular version: 6.1.2

Browser:
- [x] Chrome (desktop) version 68.0.3440.106 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.11.3
- Platform:  Mac

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
I can no longer reproduce with the latest Angular v9 running ivy. Here is the reproduce scenario I was using: https://stackblitz.com/edit/angular-zhue7y?file=src/app/app.module.ts

I was following those instructions to find detached DOM nodes: https://developers.google.com/web/tools/chrome-devtools/memory-problems#discover_detached_dom_tree_memory_leaks_with_heap_snapshots

It appears to be fixed in Angular v9 but if anyone is still seeing detached nodes with the latest Angular in a similar scenario, please open a new issue with more detailed instructions.
