### ISSUE TITLE
How update exiting project locally

### ISSUE THREAD

**Issue by opsional** [angular/angular#25454]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ x ] Other... Updating exiting project.
</code></pre>

## Current behavior

Hello, i have downloaded project with Angular 5.2 and need update to 6.x.x follow instruction from here https://update.angular.io/

## Expected behavior

-

## Minimal reproduction of the problem with instructions

-

## What is the motivation / use case for changing the behavior?

`npm install -g @angular/cli` [success]
`npm install @angular/cli` [success]
`ng update @angular/cli` [success]

But if run `ng update @angular/core` all project on my computer affected!

`
Package "nativescript-angular" has an incompatible peer dependency to "typescript" (requires "~2.6.2", would install "2.9.2").
                  Package "ng2-charts" has an incompatible peer dependency to "@angular/core" (requires "^2.3.0" (extended), would install "6.1.2").
                  Package "@material-git/slide-toggle" has an incompatible peer dependency to "@angular/forms" (requires "^2.0.0" (extended), would install "6.1.2").
                  Package "ng2-charts" has an incompatible peer dependency to "@angular/common" (requires "^2.3.0" (extended), would install "6.1.2").
                  Package "angular-datatables" has an incompatible peer dependency to "rxjs" (requires "^5.5.2", would install "6.2.2").
`
I want only [../path/to/project/](url) update, not affected to all project.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x ] Firefox version
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3  
- Platform:  Linux 
- Angular CLI: 6.1.3

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by benlesh** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
