### ISSUE TITLE
Service Worker ERROR(404) "not found"

### ISSUE THREAD

**Issue by denizakici** [angular/angular#25455]
[Mon Aug 13 2018 13:33:17 GMT+0200 (GMT+02:00)] "GET /styles.c4d05e762c7efc629d7a.css" Error (404): "Not found"
[Mon Aug 13 2018 13:33:17 GMT+0200 (GMT+02:00)] "GET /runtime.a66f828dca56eeb90e02.js" Error (404): "Not found"
[Mon Aug 13 2018 13:33:17 GMT+0200 (GMT+02:00)] "GET /polyfills.7a0e6866a34e280f48e7.js" Error (404): "Not found"
[Mon Aug 13 2018 13:33:17 GMT+0200 (GMT+02:00)] "GET /main.e419c64ea0474571ab0c.js" Error (404): "Not found"

i have this issues, if i want start my Localhost for ServiceWorker.

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter

**Comment by priyanka166** [comment]
Do this  http-server -p 8080 -c-1 dist/

It will serve all files from dist
