### ISSUE TITLE
[Feature Request] @RootInjectable()

### ISSUE THREAD

**Issue by oleersoy** [angular/angular#25466]
For context please see [Earlier Feature Request](https://github.com/angular/angular/issues/25441#event-1785610394).

### Markup
```
@RootInjectable()
export class TodosService
```
### Replacement For
```
@Injectable({
  providedIn: 'root'
})
export class TodosService
```

**Comment by abdulkareemnalband** [comment]
@oleersoy 
What are the benefits of new decorator over existing one

**Comment by mhevery** [comment]
We do have plans to simplify the `@Injectable` with tree-shakable providers but it will not be in this form. 

I am going to close this issue since something similar is already on our roadmap.
