### ISSUE TITLE
query params array dynamically added angular 4

### ISSUE THREAD

**Issue by vinothkumarb** [angular/angular#25460]
const filteredData = []; these my empty array when load my page query Parms stars value i got  [] so my url loading like this kind http://localhost:4200/fr/offres? how to fix..

When do filter I got array filteredData = [5, 3, 2];. I am parsing to queryParams. Once unselect all I got empty array how. to fix this one..

When I add filteredData.lenght > 0 ? null : filteredData my last filter value not removed

onStarChange() {
    const filteredData = [];
    this.router.navigate([], {
            relativeTo: this.route,
            queryParams: {
                stars: filteredData,
            },
            queryParamsHandling: 'merge'

        });
 }

**Comment by textbook** [comment]
To reiterate what the issue template told you: 

> Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by benlesh** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
