### ISSUE TITLE
Add new lifecycle hook between AfterViewInit and first AfterViewChecked

### ISSUE THREAD

**Issue by fr0** [angular/angular#25464]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

During `AfterViewInit`, DOM elements for the view and its children aren't guaranteed to be fully parented in the DOM (e.g. able to traverse `parentElement` all the way up to the `body`). Occasionally it is useful to know when the element has fully finished "rendering" *and* "being placed in the DOM".

Two workarounds:

1. Add setTimeout to `ngAfterViewInit`

```
   ngAfterViewInit() {
    setTimeout(() => {
       // should be able to fully traverse DOM here
    });
  }
```

2. Add code to `ngAfterViewChecked`, with a guard to make sure it only runs once
```
   private initialViewCheck = true;
   ngAfterViewChecked() {
      if (this.initialViewCheck) {
         this.initialViewCheck =  false;
         // add code here
      }
   }
```

See also:  https://stackoverflow.com/questions/31171084/how-to-call-function-after-dom-renders-in-angular2

Neither workaround is ideal.

## Expected behavior

Add new lifecycle hook that fires when the element and its children are fully created and added to the DOM.

## What is the motivation / use case for changing the behavior?

Occasionally, components or directives want to be able to look up information in their ancestry, e.g. as a workaround for https://github.com/angular/angular/issues/24824.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) Version 68.0.3440.106 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by fr0** [comment]
In my case I am trying to attach information to DOM elements so that components exposed through Angular Elements can retrieve them -- basically, a poor man's hierarchical element injector. See https://github.com/angular/angular/issues/24824 for more info.

**Comment by mhevery** [comment]
This is better achieved by the read/write DOM queue pattern. We are planning on adding something like that in the future version. 

```
onDomRead(() => {
  // DOM is fully rendered and all reads can be performed
});
```

Closing as we are not going to take this approach.
