### ISSUE TITLE
Date DatePipe

### ISSUE THREAD

**Issue by borjalo** [angular/angular#25477]
I am trying to show a date with an specific format and in spanish in Angular but it's not working properly. 
My code is: 
`<span class="departure-time-desc">{{ item.date | date: "fullDate" : "es"  }}</span>`

Does someone know how to make it work?

**Comment by borjalo** [comment]
Solved adding 
`import { registerLocaleData } from "@angular/common";
import localeEs from "@angular/common/locales/es";
registerLocaleData(localeEs);`

to my app.module.ts and
`<span class="departure-time-desc">{{ item.date | date: "E d MMM" : "GMT+2" : "es" }}</span>`
to the html

**Comment by CDDelta** [comment]
Please leave support requests on other channels. Also close this issue since you are done with it

**Comment by benlesh** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
