### ISSUE TITLE
Interpolation on custom element not working

### ISSUE THREAD

**Issue by dylanb** [angular/angular#2547]
See the following Plunker, the attribute value interpolation works on the `<li>` element, but not on the `<my-component>` element

http://plnkr.co/edit/Z7INho9vUuco9pQrwyUP?p=preview

**Comment by mhevery** [comment]
You need to have a `properties` annotation in `Component`:

```
@Component({
  properties: ['value']
})
@View(...)
class MyComponent {
  MyComponent() {
    this.value = null;
  }
}
```

**Comment by dylanb** [comment]
I added the properties value and it still does not interpolate correctly

**Comment by mhevery** [comment]
`@Attribute('value') ` does not support interpolation, this is by design. you must use property bindings.

works: http://plnkr.co/edit/HK47Pwgc3QQeK8CkOruc?p=preview

**Comment by dylanb** [comment]
ok, thanks
