### ISSUE TITLE
documentation enhancements

### ISSUE THREAD

**Issue by vickrant** [angular/angular#25476]
sometimes i have to read paragraph 3-4 times to understand what does it mean , angular documentation team had written many things in one line which is very boring and time consuming

**Comment by ericmartinezr** [comment]
What paragraphs for example? How would you have written them in less lines? What are your suggestions to make it better (less boring and less time consuming)?

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter
