### ISSUE TITLE
Is https://material.angular.io/ down?

### ISSUE THREAD

**Issue by wluijk** [angular/angular#25484]
Cant get on https://material.angular.io/ today from the Netherlands. Even proxies all over the world dont let me on the site.

Willem Luijk

**Comment by ericmartinezr** [comment]
Please open it in material's repo https://github.com/angular/material2/issues. Also it seemed to be down until I cleared the cache. I  got this in the console before cleaning the cache.

```
Loading failed for the <script> with source “https://material.angular.io/runtime.6afe30102d8fe7337431.js”. material.angular.io:42
Loading failed for the <script> with source “https://material.angular.io/main.e9d62e5f2e457c932b2d.js”. material.angular.io:42
Source map error: request failed with status 404
Resource URL: https://ajax.googleapis.com/ajax/libs/hammerjs/2.0.8/hammer.min.js
Source Map URL: hammer.min.js.map[Learn More]
```

**Comment by wluijk** [comment]
Solved, thanks!
