### ISSUE TITLE
Anchor links not scrolling to correct position on page refresh

### ISSUE THREAD

**Issue by ImranAhmed** [angular/angular#25489]
<pre><code>
[ x] Bug report 
</code></pre>

## Current behavior
I have upgraded from @angular/router 6.0.0 to @angular/router 6.1.2.

I had some anchor links in my project. These stopped working. I came across some documentation that stated that I now need to activate anchor links as follows as in Angular Router 6.1+. This works fine however when I refresh the page (with the # anchor link) the page does not go back to the position of the anchor but instead always scrolls a little further past the anchor.

```
@NgModule({
  imports: [RouterModule.forRoot(routes, {
    anchorScrolling: 'enabled',
  })],
  exports: [RouterModule]
})

```

## Expected behavior
Refreshing a page with an anchor link (e.g mypage.com/#product) should take me back to the exact scroll position of the anchor.

## Environment

<pre><code>

Angular CLI: 6.1.3
Node: 8.11.3
OS: win32 x64
Angular: 6.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.7.3
@angular/cdk                      6.4.5
@angular/cli                      6.1.3
@angular/flex-layout              6.0.0-beta.17
@angular/material                 6.4.5
@ngtools/webpack                  6.0.8
@schematics/angular               0.7.3
@schematics/update                0.7.3
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.8.3

Browser:
- [ x] Chrome (desktop) version 68.0.3440.106
 
</code></pre>

**Comment by ImranAhmed** [comment]
Even when I try this it still does not scroll to the right position, its always way past the anchor.

this.router.navigate(['/'], { fragment: location });

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
