### ISSUE TITLE
route with multiple params not firing subscribe with prod flag

### ISSUE THREAD

**Issue by rylan** [angular/angular#25485]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Compiled my app using prod flag.  `ng build --prod`
I have a route with two route params for example `path: ':a/:b',` and subscribe to the  `paramsMap`  in my ngOnInit. When I trigger a update through a router link that updates only one of the values the subscribe is not triggered.  

## Expected behavior

I expect if either `:a` or `:b` is updated it would trigger the subscribe against the paramsMap as it currently does when testing with `ng serve` . 

## Environment

<pre><code>
Angular version: 6.1.3

Browser:
- [ X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ X] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Windows 

Others:

</code></pre>

**Comment by rylan** [comment]
The simplest workaround I have come up with is to create an empty component with a `<router-outlet></router-outlet>`  such that my route setup looks like

`
{ path: ':a',  component: EmptyComponent,  children: [ { path: ':b', component: TheRealComponent } ]
` 

but it solves the issue of the paramMap.subscribe not firing when a param changed.

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
