### ISSUE TITLE
Export/expose toDate from i18n/format_date.ts

### ISSUE THREAD

**Issue by jleufven** [angular/angular#25480]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
In [format_date.ts](https://github.com/angular/angular/blob/3beb7116afeb1c7899804f43b8cb78e374d1d5a8/packages/common/src/i18n/format_date.ts#L652) there is an internal method `toDate` for converting/parsing a `string|number|Date` into Date. This is used by the Angular `DatePipe` but its not exported, only `formatDate` is.

## Expected behavior
`toDate` is exported in [common.ts](https://github.com/angular/angular/blob/3beb7116afeb1c7899804f43b8cb78e374d1d5a8/packages/common/src/common.ts#L15) :)

## Minimal reproduction of the problem with instructions
`import { formatDate, toDate } from '@angular/common';`

## What is the motivation / use case for changing the behavior?
We're writing our own date pipe with some custom logic (displaying _yesterday/today/tomorrow_) for dates that are close. We'd like to use the `toDate` to parse the incoming variable, but the method is not exposed.

## Environment
<pre><code>
Angular version: 6.0.1

For Tooling issues:
- Node version: -
- Platform: -

Others:
-

**Comment by vicb** [comment]
@ocombe could you please take a look at this issue ?

**Comment by jonathanlie** [comment]
Same thing here, we would really love to pass around `Date` objects throughout the app.
We're writing our own DateService that wraps around Angular's `formatDate` function, but we need the function to convert string to `Date` so that our object interfaces can use `Date` type comfortably.

**Comment by ocombe** [comment]
@jonathanlie would you be willing to make a PR for that?

**Comment by jonathanlie** [comment]
@ocombe sure thing, let me make a PR soon for this

**Comment by jonathanlie** [comment]
created a PR for this: https://github.com/angular/angular/pull/31143

**Comment by kara** [comment]
Closing, see https://github.com/angular/angular/pull/31143#issuecomment-523540182
