### ISSUE TITLE
Suggest reordering Forms pages

### ISSUE THREAD

**Issue by JesusAngeles** [angular/angular#25497]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

In https://angular.io/tutorial/toh-pt5,
    under FUNDAMENTALS
          under FORMS
                    the order of options is
                           Template-driven Forms
                           Form Validation
                           Reactive Forms
 
## Expected behavior

                    the order should be
                           Template-driven Forms
                           Reactive Forms
                           Form Validation

## What is the motivation / use case for changing the behavior?

it is even implied in the contents of the pages...that should read Reactive Forms before the Form Validation page.....it is the correct order
## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
@brandonroberts If I understand this request correctly, it's not specific to the Tutorial document. The request is to reorder the primary TOC, so that Forms Validation comes after introduction of template-driven and reactive forms. Makes sense to me. Maybe we can make this change when we release the new forms intro?

**Comment by brandonroberts** [comment]
Fixed via https://github.com/angular/angular/pull/25663
