### ISSUE TITLE
`path: '**'` with lazy loading not working as expected

### ISSUE THREAD

**Issue by JounQin** [angular/angular#25494]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
- [ ] Other... Please describe:

## Current behavior

```js
[
  {
    path: '',
    pathMatch: 'full',
    loadChildren: './home/home.module#HomeModule',
  },
  {
    path: '**',
    loadChildren: './downgrade/downgrade.module#DowngradeModule',
  }
]
```
`DowngradeModule` should only be loaded on url which does not match `HomeModule`, however, actually `DowngradeModule` is loaded with `HomeModule` at the same time.

## Expected behavior

`DowngradeModule` should only be loaded on url which other route can not handler.

## Minimal reproduction of the problem with instructions

https://github.com/JounQin/ng-study/blob/master/src/app/console/console.routing.module.ts
1. clone project
2. install dependencies
3. run `yarn start`
4. open `http://localhost:4200/console`
5. see network detail in browser, `home-home-module.js` and `downgrade-downgrade-module.js` are both loaded.

## What is the motivation / use case for changing the behavior?

It makes lazy loading for `path: '**'` useless.

## Environment
```bash
Angular CLI: 6.1.3
Node: 10.8.0
OS: darwin x64
Angular: 6.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.3
@angular-devkit/build-angular     0.7.3
@angular-devkit/build-optimizer   0.7.3
@angular-devkit/build-webpack     0.7.3
@angular-devkit/core              0.7.3
@angular-devkit/schematics        0.7.3
@angular/cli                      6.1.3
@ngtools/webpack                  6.1.3
@schematics/angular               0.7.3
@schematics/update                0.7.3
rxjs                              6.2.2
typescript                        3.0.1
webpack                           4.9.2
```

Browser:
- [x] Chrome (desktop) version 68.0.3440.106
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

**Comment by Vine-grette** [comment]
we can preload lazyloaded modules by having preloadStrategy and tagging the module as preload: true.
By default, angular loads all the modules

**Comment by yueluog** [comment]
In loadModuleFactory function in router_config_loader.ts, changing this line:
      return from(this.loader.load(loadChildren));
to
      return defer(() => this.loader.load(loadChildren));
seems to work for me in my limited testing. But I don't have expertise in rxjs to be certain that this is the right fix.

**Comment by atscott** [comment]
This appears to have been resolved at some point. Here's a stackblitz example in v10 of what I'm understanding from this report: https://stackblitz.com/edit/ivy-lazy-loading-base-cfn2lh?file=src%2Fapp%2Froot-children-routing.module.ts

Customers module is the only one loaded at the root. The wildcard orders module is not loaded.

**Comment by zzmp** [comment]
This issue only manifests with a custom NgFactoryModuleLoader using the deprecated `string` type for `loadChildren`. See https://stackblitz.com/edit/angular-ivy-pe9vnh.

It can be fixed by `defer`ing the call to `load` for the `**` path.
