### ISSUE TITLE
docs(angular/di): docs on transient dependencies aren't correct

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#2549]
Here's what that docs on transient dependencies say:

>Transient Dependencies

>If we need a transient dependency, something that we want a new instance of every single time, we have two options.

>We can create a child injector:

>```
>var child = inj.resolveAndCreateChild([MyClass]);
>child.get(MyClass);
>```
>Or we can register a factory function:

>```
>var inj = Injector.resolveAndCreate([
>  bind('MyClassFactory').toFactory(dep => () => new MyClass(dep), [SomeDependency])
>]);

>var factory = inj.get('MyClassFactory');
>var instance1 = factory(), instance2 = factory();
>// Depends on the implementation of MyClass, but generally holds.
>expect(instance1).not.toBe(instance2);
>```

There are two errors in this documentation.

1) According to the code samples, when a token is bound to a factory, it returns the factory itself so we can call it. But it doesn't, it returns the instance of what the factory returns:

```
class Car {

}

var injector = Injector.createAndResolve([
  bind(Car).toFactory(() => {
    return new Car();
  })
]);

injector.get(Car)() // Error: not a function
```

2) Getting an instance of something that is bound to a factory, also always returns the exact same instance:

```
injector.get(Car) === injector.get(Car) // true
```

Not sure if what the code does is correct and the docs are wrong, or vice versa. Any thoughts? :)

**Comment by vicb** [comment]
`() => {  return new Car();}` vs `dep => () => new MyClass(dep)`

I think there is no error.

**Comment by PascalPrecht** [comment]
@vicb sorry, I can't really follow. What exactly are you comparing there? To me both look like a factory function.

**Comment by vicb** [comment]
In the doc case, the factory creates a factory function while in your code example the factory creates an instance.

For the doc case, it will always return the same factory:

`injector.get(MyClassFactory) === injector.get(MyClassFactory)`

but `MyClassFactory()` will return a new instance each time.

Clear ?

**Comment by PascalPrecht** [comment]
Ah thanks for clarifying. But the docs code also just returns an instance:

`toFactory(dep => () => new MyClass(dep), [SomeDependency])`

So `MyClass` is a factory then?

**Comment by vicb** [comment]
- `() => new MyClass(dep)` is a factory
- `MyClass` is a class

I don't get what you don't get, please ask more specific questions or ping me on hangout victor.berchet at gmail.

**Comment by PascalPrecht** [comment]
Exactly, and this

```
 bind(Car).toFactory(() => {
    return new Car();
  })
```
is also a factory. Same as yours, it just doesn't have an additional dependency. However, I get the instance. Will ping you on hangouts though

**Comment by PascalPrecht** [comment]
Okay, turned our I got confused with the oneliner syntax. It's all clear now, thanks @vicb for your help.
