### ISSUE TITLE
Submit the post data to API

### ISSUE THREAD

**Issue by ambrishyad85** [angular/angular#25499]
You can post the records to API with below Details. if any issue the please let me know we will suggest again.
import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';

const httpOptions = {
  headers: new HttpHeaders(
    {
      //'content-type':'application/json', 
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',  
  }),

};

   Insert(Url : string) 
  {     
         const body = new HttpParams()
          .append('name', "ambrish123")  
          .toString();

         return this._http.post(Url, body, httpOptions) .subscribe((data) => {
          console.log(JSON.stringify(data));        
         })

  }

Thanks,
Ambrish

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
