### ISSUE TITLE
Angular 6 build time is much, much longer than Angular 5 for the same project. Is this expected?

### ISSUE THREAD

**Issue by alex7egli** [angular/angular#25505]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have a project using Angular 5.2.5 and Angular material 5.2.1. I did not use the angular cli to create the project or run any scripts. I use webpack to build the project (see webpack.common.js config file and tsconfig files at bottom of issue). I tried upgrading to Angular 6 following the upgrade guide here: https://update.angular.io/
Afterward I tried my first build and it took over 5 minutes before I headed out to get coffee. I came back about 20 minutes later and it had finished, but with a compilation error inside of the @angular/upgrade project. I don't know how long it took total but I thought it took that long because it was just a first build. I tried running it again and after 5 minutes it was only at 41% so I killed it and reverted to Angular 5. Angular 6 is unusable if builds are going to take that long. Is there some major change I need to make to my webpack or tsconfig files for builds to work properly in Angular 6?

## Expected behavior
Builds should take less than a minute, or at least have the same performance as Angular 5.

## Minimal reproduction of the problem with instructions
Build a project with Angular 6

## Environment
Windows 10
Visual Studio Code 1.26.0
Node 8.9.3
<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.3  
- Platform:  Windows 

Others:

</code></pre>

Webpack Config:
`//configurations common to all environments
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
// var BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
var helpers = require('./helpers');
var glob = require('glob');

module.exports = {
    //entry point files that define the bundles (one bundle is generated for each entry point)
    entry: {
        'vendor': './src/vendor.ts',
        'polyfills': './src/polyfills.ts',
        'app':'./src/main.ts',
        //bundle angularJS files
        'oldApp': glob.sync('./app/scripts/**/*.js').concat(glob.sync('./app/components/**/*.js'))
    },

    //how to resolve filenames when they don't have extensions
    resolve: {
        extensions: ['.ts','.js']
    },

    module: {
        rules: [
            {
                test: /\.ts$/,
                loaders: [
                    {
                        loader: 'awesome-typescript-loader',
                        options: { configFileName: helpers.root('config', 'tsconfig.json') }
                    }, 'angular2-template-loader'
                ]
            },
            {
                test: /\.html$/,
                loader: 'html-loader?attrs=false'
            },
            {//application wide styles
                test: /\.css$/,
                exclude: helpers.root('src', 'app'),
                loader: ExtractTextPlugin.extract({ fallbackLoader: 'style-loader', loader: 'css-loader?sourceMap&url=false'})
            },
            {//component specific styles, specified in styleUrls
                test: /\.css$/,
                include: helpers.root('src','app'),
                loader: 'raw-loader'
            },
            {//component specific sass styles, specified in styleUrls
                test: /\.scss$/,
                include: helpers.root('src','app'),
                loaders: ['raw-loader', 'sass-loader?sourceMap']
            },
            { //pre-Portal 3.0 code
                test: /\.js$/,
                include: helpers.root('app','scripts'),
                loader: 'babel-loader'
            }
        ]
    },

    plugins: [
        //workaround for angular/angular#11580
        new webpack.ContextReplacementPlugin(
            // The (\\|\/) piece accounts for path separators in *nix and Windows
            /angular(\\|\/)core(\\|\/)(esm(\\|\/)src|src)(\\|\/)linker/,
            helpers.root('../src'), // location of your src
            {} // a map of your routes
        ),

        //Make sure that only app code is in app bundle, so when it imports vendor code it won't automatically be bundled into the app bundle
        new webpack.optimize.CommonsChunkPlugin({
            name: ['app','oldApp', 'polyfills','vendor']
        }),

        //Inject js/css files into index.html automatically
        new HtmlWebpackPlugin({
            template: './src/index.html'
        }),

        //Fix bug in moment with webpack where it requires a library that does not exist (https://github.com/moment/moment/issues/2979)
        new webpack.IgnorePlugin(/\.\/locale$/),

        // Provide the moment library as a global variable, otherwise 
        new webpack.ProvidePlugin({
            moment:"moment"
        })

        //Analyze what is actually in each bundle in browser
        // new BundleAnalyzerPlugin({
        //     analyzerMode: 'static'
        // })
    ]
}
`
tsconfig.json
`{
  "compilerOptions": {
    "allowJs": true,
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es2015", "dom" ],
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": [
      "../node_modules/@types/"
    ],
    "types": [ "node", "angular", "jasmine" ]
  },
  "compileOnSave": true,
  "exclude": [
    "node_modules/*",
    "app/bower_components/*",
    "**/*-aot.ts"
  ],
  "outDir":"build"
}
`

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

<hr>

For this issue, I would assume there's something specific to your project as this isn't something that's been generally reported. If it were a general issue, we definitely would have heard about it from others.

So, that being said, if you can provide a Github repo where building with Angular 5 vs Angular 6 shows a significant difference in build time, that would help isolate what the issue is you seem to be having.
