### ISSUE TITLE
Angular crashing completely using TableFilter

### ISSUE THREAD

**Issue by legiscope** [angular/angular#25502]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I created a completely new application, and installed TableFilter : 
npm install tablefilter --save

Then, i'm adding TableFilter to the application and the browser makes thousands of requests to the localhost server until it crashes.

## Minimal reproduction of the problem with instructions

Here's a minimal demo, but just adding TableFilter inside any app will kill crash the application and makes thousands of requests to the localhost server

<button (click)="onClick()" ng-init="count=0">test click</button>

<table id="demo">
    <thead>
        <tr>
            <th>country</th>
            <th>iso</th>
            <th>year</th>
            <th>POP</th>
            <th>XRAT</th>
            <th>PPP</th>
            <th>cgdp</th>
            <th>cc</th>
            <th>ci</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Zimbabwe</td>
            <td>ZWE</td>
            <td>2000</td>
            <td>12627.00</td>
            <td>44.41791916</td>
            <td>9.48</td>
            <td>2607.03</td>
            <td>69.23</td>
            <td>8.62</td>
        </tr>
    </tbody>
</table>

And component does this - you can add nothing as filterConfig it doesn't matter the app crashes anyway : 

  onClick(){

    var filtersConfig = {
        base_path: 'tablefilter/',
        col_1: 'select',
        col_2: 'select',
        col_3: 'select',
        alternate_rows: true,
        rows_counter: true,
        btn_reset: true,
        loader: true,
        status_bar: true,
        mark_active_columns: true,
        highlight_keywords: true,
        col_types: [
            'string', 'string', 'number',
            'number', 'number', 'number',
            'number', 'number', 'number'
        ],
        custom_options: {
            cols:[3],
            texts: [[
                '0 - 25 000',
                '100 000 - 1 500 000'
            ]],
            values: [[
                '>0 && <=25000',
                '>100000 && <=1500000'
            ]],
            sorts: [false]
        },
        col_widths: [
            '150px', '100px', '100px',
            '100px', '100px', '100px',
            '70px', '60px', '60px'
        ],
        extensions:[{ name: 'sort' }]
    };

    var tf = new TableFilter('demo', filtersConfig);  // this totally crashes the app

  }

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter
