### ISSUE TITLE
i18n Unable to generate output file outside project dir (v6.1)

### ISSUE THREAD

**Issue by RoxKilly** [angular/angular#25500]
## I'm submitting a...

<pre><code>[x] Regression (a behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

When running `ng xi18n` with a relative output path outside the project, the operation completes with exit code 0, but no file is created
```
ng xi18n --output-path ../../../../OtherProject/src/locale --i18n-format=xlf --out-file messages.xlf
```
If I use an absolute path to the same directory instead, I get the same result. Exit code 0, but no output. If I make change other than changing the output path to an in-project location such as `locale`, it works as expected and creates `messages.xlf`

## Expected behavior

A successful exit code should mean that the file was created successfully.  Alternatively, an error should be shown explaining why the file was not created. This is not a permissions issue: the same procedure worked in the same directories in v5.2

## Minimal reproduction of the problem with instructions

1. Generate a new cli project
2. Add a component and put an `i18n` tag in its template
3. Run `ng xi18n` with an output path outside the project, in the `xlif` format.

## What is the motivation / use case for changing the behavior?

To use `ng xi18n` to parse templates and output wherever I wish. If you're curious about why, [checkout this Stack question](https://stackoverflow.com/questions/51858326/angular-6-translations-use-ng-i18n-on-a-non-angular-cli-project). My use-case is the same.

## Environment
<pre><code>Angular version: 6.1.2
Node version: 10.7  
Platform:  Windows 10 
</code></pre>

**Comment by alxhub** [comment]
Tested and confirmed this works in latest (7.3.3).
