### ISSUE TITLE
@angular/dev-kit/buildoptimizer uses its own Typescript

### ISSUE THREAD

**Issue by mcblum** [angular/angular#25501]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
We have a vendor file (auth0.js) which causes our builds to fail. A snippet of the failure is:
```
Running: ./node_modules/@angular/cli/bin/ng build --project=member-direct --configuration=test

ERROR in /Revel/clients/node_modules/auth0-js/dist/auth0.js
Module build failed: Error: Debug Failure. False expression.
    at getJSDocTags (/Revel/clients/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:13173:22)
```
According to the Typescript issue I opened, this issue was fixed in 3.0. I update our TS to 3.0, but the build optimizer appears to use its own version, and I can't get the app to build as long as we're including code from that file.

## Expected behavior
The version of TS in the `package.json` file is not used for everything.

## What is the motivation / use case for changing the behavior?
Hacking stuff together when we need to upgrade something and have it be global.

## Environment

<pre><code>
Angular version: 6.1.2
 
For Tooling issues:
- Node version: 10
- Platform:  Mac

Others:
Thank you for all your work on Angular!
</code></pre>

**Comment by alan-agius4** [comment]
Hi,

Angular Devkit and CLI issues should be created in the CLI repo https://github.com/angular/angular-cli/issues

**Comment by pkozlowski-opensource** [comment]
> Angular Devkit and CLI issues should be created in the CLI repo https://github.com/angular/angular-cli/issues

Totally! Closing it here. Please re-create in https://github.com/angular/angular-cli/issues if CLI v6.1.3 doesn't work for you.

Thnx @alan-agius4 @sarunint for helping out with the issues!
