### ISSUE TITLE
docs: security guide short URL is dead

### ISSUE THREAD

**Issue by LayZeeDK** [angular/angular#25514]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Several Angular software components have error descriptions that refer to the angular.io Security Guide with the short URL `http://g.co/ng/security` which redirects to `https://angular.io/guide/security.html`. This URL is dead.

## Expected behavior
The short URL should point to `https://angular.io/guide/security`.

## Minimal reproduction of the problem with instructions
<!--
One example is
https://github.com/angular/angular/blob/6.1.x/packages/platform-browser/src/security/dom_sanitization_service.ts#L213

## What is the motivation / use case for changing the behavior?
As developers, we appreciate Angular's descriptive errors but when the link is dead, it is not helpful.

## Environment

<pre><code>
Angular version: 6.1.x

Others:
The one responsible for the g.co short URL can simply update the target URL for the redirect to `https://angular.io/guide/security`.
</code></pre>

**Comment by gkalpak** [comment]
Firebase used to strip `.html` off, but it doesn't seem to do so any more.
Based on https://github.com/angular/angular/blob/92c8752d0a91da6cb0ae1b42b9f00e155f5e4772/aio/firebase.json#L7 and https://firebase.google.com/docs/hosting/full-config#cleanurls it should:

> If a `.html` extension is added, a 301 redirect will be performed to the same path without the `.html` extension.

Generally, Firebase hosting (maybe just redirects) seems to have been messed up recently.

I don't think there is anything we can do in angukar.io. Someone with access to the `g.co/ng` account should fix the URL (i.e. remove the `.html` extension).

**Comment by IgorMinar** [comment]
I fixed the short link definition so the redirect now works correctly. thanks
