### ISSUE TITLE
Tree type is not supported

### ISSUE THREAD

**Issue by Phunse** [angular/angular#25517]
I am trying to create a new project and I am getting the error "Tree type is not supported."

My Angular CLI version is 6.1.3

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by qiesyan** [comment]
select * from p_employee where userid in ('lilei','hanmeimei');
