### ISSUE TITLE
Invalid source map path for @angular/common/http/testing bundle

### ISSUE THREAD

**Issue by Delagen** [angular/angular#25510]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Cannot find SourceMap 'http__testing.js.map': Error: Can't
 resolve './http__testing.js.map' in '...\node_modules\@angul
ar\common\fesm5\http'

## Expected behavior
No warning.

## Minimal reproduction of the problem with instructions
Open file in npm bundle @angular/common/fesm5/http/testing.js
At the end of file `//# sourceMappingURL=http__testing.js.map`

## What is the motivation / use case for changing the behavior?
Fix bug in build system

## Environment

<pre><code>
Angular version: 6.1.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.9.0
- Platform:  Windows

Others:

</code></pre>

**Comment by Delagen** [comment]
Seems to fixed in 6.1.6.

**Comment by IgorMinar** [comment]
I sent #27313 to fix this.. thanks for the report.
