### ISSUE TITLE
Improve Support for <select> and <option>

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#2551]
The ngOptions directive from Angular 1 provides some extra capabilities that is not supported when you use select directly:

* Handling mismatches between selected value and available options
* Handling prompt options

Maybe we should provide similar capabilities in NG2?

/cc @IgorMinar

**Comment by mhevery** [comment]
Yes we should

**Comment by vicb** [comment]
@kara is this still applicable ?

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
