### ISSUE TITLE
question: How to dynamically add modules from other files in the browser?

### ISSUE THREAD

**Issue by iamruslanbakirov** [angular/angular#25516]
## I'm submitting a..
[ x] Other
I have a standard project structure for the Angular CLI, and I have modules that are standalone applications that I would like to render in a package and connect to the main application if desired.

In the previous version of the angular, this was possible. for example
In app bundle: 
```angular.module('app', []);```

and module in other bundle:
```angular.module('otherModule', []);```

after load all scripts, i found second module and inject dynamically in first:
```angular.module('app').requires.push('otherModule');```

How to implementation this behavior in angular 2+ ?
I need to create modules of another application and dynamically add them to the base application via the script tag.

for example:
```https://gist.github.com/iamruslanbakirov/483b5f7092842a975d5f5bc00bfb53c6```

## Environment
Angular version: 6.0.3
Angular-cli: 6.0.8"

**Comment by diggudg** [comment]
Hi,
You can use `compileModuleAndAllComponentsSync` method of `Compiler` class and dynamically load any other module.

**Comment by iamruslanbakirov** [comment]
after build my module with cli and load on browser, application crashed
i don't know how to build other module and correct loading in browser

webpack with angular cli create in window array with name "webpackJsonp ", and my module pushed in this array after load. 

after append, array has two object with name "main" and app not working

**Comment by Vine-grette** [comment]
you may look at this example where different modules are declared under app.module.ts
[https://github.com/jhipster/jhipster-sample-app-ng2/tree/master/src/main/webapp/app]

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by iamruslanbakirov** [comment]
@Vine-grette thanks you for you help, but modules need append in app.module.ts dynamically.
in you example they are declared before compile app.

**Comment by iamruslanbakirov** [comment]
@jasonaden i have same question in [SO](https://stackoverflow.com/questions/51875238/angular-2-with-cli-add-in-project-modules-from-other-bundle-js)

but, i think this "feature" not unleashes... :-(
