### ISSUE TITLE
Form which contains only disabled fields is invalid

### ISSUE THREAD

**Issue by samu** [angular/angular#25522]
The  problem is reproduced here: https://stackblitz.com/edit/angular-slbaeh

Is this expected? I would expect the form to be valid.

**Comment by jasonaden** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

<hr>

Specifically, please follow the issue template and the requirement to give the steps to reproduce. Please explain what you expect (with detail) and what is actually happening (again, with detail, not just "notice it's broken", but more like "Expected: Validation of type 'number' with a value of '1' should pass. Actual: Validation fails with message 'string is not a number'" (or something with a similar level of detail.
