### ISSUE TITLE
ERROR Error: "StaticInjectorError(uu)[e]:    StaticInjectorError(Platform: core)[e]:      NullInjectorError: No provider for e!"

### ISSUE THREAD

**Issue by Karman40** [angular/angular#25529]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

Error messege:
<code>
ERROR Error: "StaticInjectorError(uu)[e]: 
  StaticInjectorError(Platform: core)[e]: 
    NullInjectorError: No provider for e!"
gethttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:868636thttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:870913thttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:870864gethttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:870838thttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:870913thttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:870864gethttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:870838hohttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:937145gethttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:947987elhttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:951963gethttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:945038ngAfterViewInithttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:1453120llhttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:953072olhttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:952832ilhttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:952697Ilhttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:962066zlhttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:968797jlhttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:968195Ilhttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:962014detectChangeshttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:943474tickhttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:901311tickhttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:901272_loadComponenthttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:901785bootstraphttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:900955_moduleDoBootstraphttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:898023_moduleDoBootstraphttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:897973ohttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:897431invokehttps://infohullam.hu/polyfills.9f773b75ffcda6bb2a95.js:1:7274onInvokehttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:890747invokehttps://infohullam.hu/polyfills.9f773b75ffcda6bb2a95.js:1:7201runhttps://infohullam.hu/polyfills.9f773b75ffcda6bb2a95.js:1:2434zhttps://infohullam.hu/polyfills.9f773b75ffcda6bb2a95.js:1:13698invokeTaskhttps://infohullam.hu/polyfills.9f773b75ffcda6bb2a95.js:1:7949onInvokeTaskhttps://infohullam.hu/main.499fffa9373ce6d02f89.js:1:890659invokeTaskhttps://infohullam.hu/polyfills.9f773b75ffcda6bb2a95.js:1:7862runTaskhttps://infohullam.hu/polyfills.9f773b75ffcda6bb2a95.js:1:3125dhttps://infohullam.hu/polyfills.9f773b75ffcda6bb2a95.js:1:10178 main.499fffa9373ce6d02f89.js:1:873611
ye
https://infohullam.hu/main.499fffa9373ce6d02f89.js:1:873611
zUnb/ve</t.prototype.handleError
https://infohullam.hu/main.499fffa9373ce6d02f89.js:1:873820
zUnb/qn</t.prototype.tick/<
https://infohullam.hu/main.499fffa9373ce6d02f89.js:1:901474
0TWp/</</c</e.prototype.invoke
https://infohullam.hu/polyfills.9f773b75ffcda6bb2a95.js:1:7274
0TWp/</</i</t.prototype.run
https://infohullam.hu/polyfills.9f773b75ffcda6bb2a95.js:1:2434
zUnb/Cn</t.prototype.runOutsideAngular
https://infohullam.hu/main.499fffa9373ce6d02f89.js:1:891766
zUnb/qn</t.prototype.tick
https://infohullam.hu/main.499fffa9373ce6d02f89.js:1:901427
zUnb/qn</t.prototype._loadComponent
https://infohullam.hu/main.499fffa9373ce6d02f89.js:1:901785
zUnb/qn</t.prototype.bootstrap
https://infohullam.hu/main.499fffa9373ce6d02f89.js:1:900955
zUnb/Bn</t.prototype._moduleDoBootstrap/<
https://infohullam.hu/main.499fffa9373ce6d02f89.js:1:898023
zUnb/Bn</t.prototype._moduleDoBootstrap
https://infohullam.hu/main.499fffa9373ce6d02f89.js:1:897973
zUnb/Bn</t.prototype.bootstrapModuleFactory/</</o<
https://infohullam.hu/main.499fffa9373ce6d02f89.js:1:897431
0TWp/</</c</e.prototype.invoke
https://infohullam.hu/polyfills.9f773b75ffcda6bb2a95.js:1:7274
onInvoke
https://infohullam.hu/main.499fffa9373ce6d02f89.js:1:890747
0TWp/</</c</e.prototype.invoke
https://infohullam.hu/polyfills.9f773b75ffcda6bb2a95.js:1:7201
0TWp/</</i</t.prototype.run
https://infohullam.hu/polyfills.9f773b75ffcda6bb2a95.js:1:2434
z/<
https://infohullam.hu/polyfills.9f773b75ffcda6bb2a95.js:1:13698
0TWp/</</c</e.prototype.invokeTask
https://infohullam.hu/polyfills.9f773b75ffcda6bb2a95.js:1:7949
onInvokeTask
https://infohullam.hu/main.499fffa9373ce6d02f89.js:1:890659
0TWp/</</c</e.prototype.invokeTask
https://infohullam.hu/polyfills.9f773b75ffcda6bb2a95.js:1:7862
0TWp/</</i</t.prototype.runTask
https://infohullam.hu/polyfills.9f773b75ffcda6bb2a95.js:1:3125
d
https://infohullam.hu/polyfills.9f773b75ffcda6bb2a95.js:1:10178
</code>

<pre><code>
Angular version: 6.0.3
 
For Tooling issues:
- Node version: 10.5.0
- Platform:  Windows
</pre></code>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Lavanya2021** [comment]
Hello.., I am facing the same issue  with the angular version 7.0.2.
This error is occoured while executing the dist folder in local server as well as in the apache server. 
![static](https://user-images.githubusercontent.com/44113562/63165821-2016f880-c04a-11e9-97cc-b7048b0cd518.jpg)
