### ISSUE TITLE
Angular 6 I18n missing translation files Error

### ISSUE THREAD

**Issue by sreddy77** [angular/angular#25526]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ x] Angular 6 I18n rollup request for missing messages.xlf files
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently we are using Angular 6 i18n  for translating the webpage for 12 different languages .
I have messages.es.xlf file but when I request for **ng serve --configuration=es-US.**
it doesn't rollup to messages.es.xlf . It errors out with missing translation file message.

## Expected behavior
 when es-US request is made and messages.es-US.xlf file is missing  it should rollup to messages.es.xlf file and display the spanish web page

## Minimal reproduction of the problem with instructions
**step 1 : messages.es.xlf**  under src/local/ folder

**step 2: src/app/app.component.html**
<div class="modal-container grid-y">
  <div>
    <h2 id="app-expired-title" i18n="@@app-expired-title" [tabIndex]=0>Your session expired</h2>
  </div>

  <div class="body-container">
    <p id="app-expired-body" i18n="@@app-expired-body" [tabIndex]=0>Any confirmed transactions are saved, but you'll need to restart any searches or unfinished transactions.</p>
  </div>

  <div class="grid-x align-right">
    <button id="app-expired-button" class="primary button full-on-small" (click)="onStartOver()" i18n="@@app-expired-button">Start over</button>
  </div>
</div>**

INPUT:
**step 3 : ng serve --configuration=es-US**
note: **messages.es-US.xlf** is not present in the src/local/ folder 

OUTPUT: 

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2018-08-17T00:21:55.911Z
Hash: bbc99f56691840835b1e
Time: 3065ms
chunk {main} main.js, main.js.map (main) 1.95 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 690 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 206 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 325 kB [initial] [rendered]

ERROR in ENOENT: no such file or directory, open '/Users/sreddy/timeout-warning-modal-lib/src/locale/messages.es-us.xlf'
ℹ ｢wdm｣: Failed to compile.

## What is the motivation / use case for changing the behavior?
Instead of throwing the error it should rollup to  default  es locale and consider the messages.es.xlf and display the spanish version.

I might be wrong as am not sure if angular supports this feature 

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [ ] Chrome (desktop) version 68.0.3440.106
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version 11.1.2
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jasonaden** [comment]
Issues need to have a reproduction. This may get closed once a member of the i18n team takes a look if there's not a reproduction attached. If you want to avoid that, please create a repro using [StackBlitz](https://stackblitz.com/fork/angular-gitter).

**Comment by ocombe** [comment]
Hello, this issue is linked to the way angular cli outputs errors (or not in this case), and it is not an error of the framework itself. Could you open the issue on [the angular cli repository](https://github.com/angular/angular-cli/issues/) instead? thanks!
