### ISSUE TITLE
[elements]: custom element inside a custom element's template throw on destruction

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#25525]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
We have 3 custom elements, A , B and C - All are angular components converted to custom elements.

We create a new A programatically, with an injector.

Inside A we append HTML code, the code includes markup that will create B. (B doesn't have an injector).

In B's template, we have markup to create C.

---

Stopping here to point out that while C is inside an **angular template** markup and **it is an angular component,** the fact that it's declared as a custom element means that it will be handled by `@angular/elements`.

---

Now, **A** was created programatically so we have a reference for it.  
We remove it (`NgElement.remove()`) which starts the destruction process.

When `@angular/elements` starts the destruction process and error is  thrown:

**ERROR TypeError: Cannot read property 'nativeNode' of null**
<details>
    at removeDebugNodeFromIndex (core.js:5407)
    at DebugRenderer2.push.../../node_modules/@angular/core/fesm5/core.js.DebugRenderer2.destroyNode (core.js:11398)
    at destroyViewNodes (core.js:10613)
    at destroyView (core.js:10601)
    at callWithDebugContext (core.js:11351)
    at Object.debugDestroyView [as destroyView] (core.js:11035)
    at ViewRef_.push.../../node_modules/@angular/core/fesm5/core.js.ViewRef_.destroy (core.js:8868)
    at ComponentRef_.push.../../node_modules/@angular/core/fesm5/core.js.ComponentRef_.destroy (core.js:8705)
    at elements.js:236
    at ZoneDelegate.push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
</details>

The error happens when `@anguar/core` try's to destory C.

What happens is that ` DebugRenderer2.destroyNode()` is called **TWICE** for **C**.
My guess is that because C is a custom element used inside an angular template both angular and angular/elements invoke a destroy... something like that I guess.
 
## Expected behavior
Should not throw...

> It's worth noting that even if I disable the delay of destruction it stlll throws

**Comment by shlomiassaf** [comment]
Update:

It looks like 2 instance's of C gets created, the first instance is the one that should get created.

The first one is created inside B, when B's component ref get's created by elements.
element's use angular for that, which means that before creating B is done angular will
create children of B, which is C.

Because C is a component, angular will create an instance for it!!!

The 2nd time is when the browser see C's tag name, which was just assign to a component instance in phase 1. It detects it as a web component and triggers the normal process where element's create an instance of C.

**Comment by trotyl** [comment]
Relates to https://github.com/angular/angular/issues/21585:

> Support using a component in Angular templates and exporting it as a custom element (in the same app).

**Comment by foureighteen** [comment]
I'm having the exact same issue when exporting customElements and using them within components in the same cli project.

**Comment by nvdweem** [comment]
I ran into this problem a while back. At work we are also using Angular Elements both as regular Angular Components and as Custom Elements on pages. We 'solved' this by using a different component selector for the two usecases:
`@Component({
  selector: 'a-component',`

`customElements.define('b-component', createCustomElement(component, {injector}));`

Then, using the a prefix in the angular module and the b prefix as custom elements seems to be ok.

**Comment by nikkonduru88** [comment]
We do have different selectors for the two usecases, but I am still getting that error. It works when I have ng-content inside child component, but when I changed it to slot, then I see this error. Did anybody else notice this with upgrade Angular 7 or in general?

**Comment by maxtacco** [comment]
Any progress on this issue? I'm in the same boat.

**Comment by kevin192291** [comment]
Is there any workaround that we can use now? I am in need as this is preventing me from shipping my next release.

**Comment by thelgevold** [comment]
I believe this PR would fix this issue: https://github.com/angular/angular/pull/27631

**Comment by kevin192291** [comment]
> I believe this PR would fix this issue: #27631

Really hoping that it can be approved very soon. It looks like it just needs an approval to be merged right?

**Comment by Dr0drigues** [comment]
Does anyone have any way to fix this? Or are we still waiting for a PR to be merged?

**Comment by ai-eye** [comment]
If any body does please let me know, this is a big problem for me at the moment.

**Comment by luiscla27** [comment]
Same issue here when using custom element inside custom element:
![image](https://user-images.githubusercontent.com/29953012/71528314-df0adc80-28a4-11ea-813a-d9ffee368340.png)

My use case is that i need an "Element Handler"... so i can manage if they are already rendered or not, i choose this approach because i want to guarantee that all them are being destroyed when they are not in use. My element handler needs to be also an element because i need to access it so i can request the inner elements to be rendered.

> I believe this PR would fix this issue: #27631

Yes it does!

@ayazhafiz, i saw you'r active here! can you please help us reviewing [this PR](https://github.com/angular/angular/pull/27631/files)?

**Comment by irekBudzowski** [comment]
@gkalpak I had the same issue, but I noticed, that the problem has been solved after recompiling dependencies (triggered by adding `"postinstall": "ngcc"` in `package.json` file).

Any way the recompilation break us a different [thing](https://github.com/microsoft/TypeScript/issues/21388#issuecomment-385281089), but it's not related to the topic.

**Comment by JoostK** [comment]
This has been fixed in Angular 11.2.10 in #41565.
