### ISSUE TITLE
Standardize name of Getting Started aka QuickStart 

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#25524]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

TOC: Getting Started
Page title: QuickStart (one word)
Filename: quickstart

## Expected behavior

TOC matches page title
Page titles are written as words, not as filenames 

## Minimal reproduction of the problem with instructions

https://angular.io/guide/quickstart

## What is the motivation / use case for changing the behavior?

Consistency is good.
Many docs refer to this one, and the cross-references are awkward and inconsistent.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
This should be closed now as the linked PR already merged.

**Comment by ajitsinghkaler** [comment]
@gkalpak @kapunahelewong this can be closed

**Comment by gkalpak** [comment]
Fixed with #25762.
