### ISSUE TITLE
docs-infra: Directive API template improvements

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#25530]
* Move all the class-like syntax stuff to the bottom
* Remove "Usage Notes" heading
* Move inputs and outputs into a table

**Comment by jbogarthyde** [comment]
Directives are basically all Usage Notes. The usage is more important to general developers than the implementation syntax. We are moving the Usage Notes section above the syntax sections, where it will blend into the long description. This means that it doesn't need a section heading -- it just serves as a way to add topic headings within the description.

**Comment by jbogarthyde** [comment]
@petebacondarwin Is there any way to add a description to the different selectors? There are lots of them for some of the forms-related directives, it looks to me like they need some commentary or differentiation.

**Comment by petebacondarwin** [comment]
We talked about this last week. It is not possible to do anything "automatic". Instead we agreed that we would have an `@selectors` tag. If this tag is used then we do not render the normal list of selectors. Instead we render the contents of the tag. This allows the author to write a custom description in the cases where the selectors are complicated or confusing.
