### ISSUE TITLE
Wrong example on doc page ( https://angular.io/api/core/ChangeDetectorRef#reattaching-a-detached-component )

### ISSUE THREAD

**Issue by bullwinkle** [angular/angular#25538]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Wrong example on page
https://angular.io/api/core/ChangeDetectorRef#reattaching-a-detached-component .
Last example is simple copy of previous example and does not show nothing about "Reattaching a detached component".

## Expected behavior

Last example on page https://angular.io/api/core/ChangeDetectorRef#reattaching-a-detached-component is right and shows how to use reattaching component's change detector properly.

**Comment by textbook** [comment]
Duplicates #25495

**Comment by jasonaden** [comment]
Thanks. Closing as duplicate.
