### ISSUE TITLE
Add NumberValueAccessor and RangeValueAccessor to public API of @angular/forms

### ISSUE THREAD

**Issue by ivanpadavan** [angular/angular#25541]
So I just think that it's the only ValueAccessor implementation that's not accessable. Is it somehow special?

**Comment by jasonaden** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
