### ISSUE TITLE
Fix typo in reactive forms guide

### ISSUE THREAD

**Issue by jinbeomhong** [angular/angular#25542]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

A form **control** instance has the same properties (such as value and untouched) and methods (such as setValue()) as a form control instance.

## Expected behavior

A form **group** instance has the same properties (such as value and untouched) and methods (such as setValue()) as a form control instance.

## Minimal reproduction of the problem with instructions

1. Move to https://angular.io/guide/reactive-forms#step-1-creating-a-formgroup-instance
2. third paragraph.

**Comment by kara** [comment]
Closed by https://github.com/angular/angular/pull/25543
