### ISSUE TITLE
Outdated hosting of ngForOf Plunker demo

### ISSUE THREAD

**Issue by diminutivesloop** [angular/angular#25547]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The [ngForOf api docs](https://angular.io/api/common/NgForOf) still contains a link to an outdated and broken Plunker demo. This was apparently missed in PR #23966.

**Comment by jenniferfell** [comment]
Demo still seems to be appropriate and correct, but we need to move it from plunkr to stackblitz. plunkr is deprecated for Angular doc examples.

**Comment by Niladri24dutta** [comment]
@jenniferfell  Hi , I have a working stackblitz example of the directive as given in the existing plunker . Can I create a PR for this?

**Comment by Niladri24dutta** [comment]
@jenniferfell here is the link to the stackblitz https://stackblitz.com/edit/angular-ye9moi which I recreated with Angular 6x

**Comment by brandonroberts** [comment]
The plunker example has been removed.
