### ISSUE TITLE
No matching version found for @angular/cli@5.2.9

### ISSUE THREAD

**Issue by Knavaneeth** [angular/angular#25540]
Hi Friends ,
I'm New to Angular , while I'm trying to install a particular a particular version of angular .
I got the below message .

**C:\Users\Dreams>npm install -g @angular/cli@5.2.9**

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular/cli@5.2.9
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dreams\AppData\Roaming\npm-cache\_logs\2018-08-17T09_42_35_435Z-debug.log

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow ](https://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) explanation.

That said, that version doesn't exist. As the latest version of `5.2.x` is `5.2.4`

**Comment by KANekT** [comment]
@alan-agius4 @Knavaneeth https://www.npmjs.com/package/@angular/cli

is not have version 5.*.*

**Comment by alan-agius4** [comment]
Apologies I missed that this was referencing the CLI.

**Comment by jasonaden** [comment]
@Knavaneeth For a little history, the CLI versioning previously didn't match Angular versioning. Prior to the CLI version `6.0`, the next earlier version was `1.7.4`, which is what you would have used with Angular `5.x`.

That being said, you should be able to use CLI version `6.x` with Angular version `5.x`, so you should be able to just `npm install -g @angular/cli@6` (or, possibly easier than remembering version numbers, `npm install -g @angular/cli@latest`).
