### ISSUE TITLE
refactor(http): move mock_backend to test_lib module

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2554]
To be consistent with other submodules, the mock_backend should be exported on a new `test_lib` module in http, so it will not be loaded in production code or bundles.

**Comment by naomiblack** [comment]
@jeffbcross this was in alpha-28 but no one was assigned to it. I'm moving to alpha-29, but it needs an assignee. Any suggestions?

**Comment by jeffbcross** [comment]
@naomiblack sorry slow to follow-up. I'll take it, will be a quick change after I land #2714.

**Comment by rixrix** [comment]
Hi,

I'd like to work on this task and started some initial work on it. It's on my branch at the moment, would be good to get some feedback. thanks

**Comment by PascalPrecht** [comment]
@rixrix LGTM could you send a PR?

**Comment by rixrix** [comment]
@PascalPrecht thanks for looking into this. PR sent.

**Comment by jeffbcross** [comment]
We ended up deciding to move http test dependencies into a separate module and bundle, which for now will be called `http_testing`. Sorry for being slow to update this issue, and thanks for the PR @rixrix! I think @robwormald has started some work on this as part of other work he's been doing, so I'll assign this to him for now.

**Comment by rixrix** [comment]
@jeffbcross no problem at all and thanks for looking into this ;)

**Comment by robwormald** [comment]
This issue was moved to angular/http#81
