### ISSUE TITLE
After ng update, can't run ng commands

### ISSUE THREAD

**Issue by jakehockey10** [angular/angular#25550]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I ran `ng update --all` and now the ng command does not work inside the angular workspace.  The command seems to work fine outside of this directory, but I get the following error:
``` shell
$ ng
ENOENT: no such file or directory, open '/C/Users/j.smith/source/repos/td-reporting/client-workspace/node_modules/@angular/cli/commands/help.json'
Error: ENOENT: no such file or directory, open '/C/Users/j.smith/source/repos/td-reporting/client-workspace/node_modules/@angular/cli/commands/help.json'
    at Object.openSync (fs.js:434:3)
    at Object.readFileSync (fs.js:339:35)
    at findCommand (C:\Users\j.smith\source\repos\td-reporting\client-workspace\node_modules\@angular\cli\models\command-runner.js:302:31)
    at Object.<anonymous> (C:\Users\j.smith\source\repos\td-reporting\client-workspace\node_modules\@angular\cli\models\command-runner.js:77:45)
    at Generator.next (<anonymous>)
    at C:\Users\j.smith\source\repos\td-reporting\client-workspace\node_modules\@angular\cli\models\command-runner.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\j.smith\source\repos\td-reporting\client-workspace\node_modules\@angular\cli\models\command-runner.js:10:12)
    at Object.runCommand (C:\Users\j.smith\source\repos\td-reporting\client-workspace\node_modules\@angular\cli\models\command-runner.js:51:12)
    at C:\Users\j.smith\source\repos\td-reporting\client-workspace\node_modules\@angular\cli\lib\cli\index.js:38:58
```
The particular json file it points to in the error depends on the command I run.  I'm confused what this error is telling me.  Is it asking me to open that file?  Those files exist, I've completely updated node and npm already, and I've blown away my node_modules folder and re-installed.  I even ran `npm cache verify`.

## Expected behavior

After upgrading my angular-related modules, I would expect to be able to run the ng command still.

## Minimal reproduction of the problem with instructions

`ng update --all`

## What is the motivation / use case for changing the behavior?

Doing all the things ;-)

## Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.1.4
Node: 10.9.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.4
@angular-devkit/core         0.7.4
@angular-devkit/schematics   0.7.4
@schematics/angular          0.7.4
@schematics/update           0.7.4
rxjs                         6.2.2
typescript                   2.9.2
</code></pre>

**Comment by sarunint** [comment]
Running `npm install` should fix the problem.

**Comment by jakehockey10** [comment]
It doesn't, however.

**Comment by jakehockey10** [comment]
I reverted the changes to `package.json` and `package-lock.json` and deleted my `node_modules`, then I updated a few outdated dependencies before running `ng update @angular/cli` and then `ng update @angular/core` individually and things seem to be behaving better.
