### ISSUE TITLE
Angular 6.1: page snaps to top when clicking router-link

### ISSUE THREAD

**Issue by karptonite** [angular/angular#25555]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

As of Angular 6.1, when I navigate via `routerLink`, the page snaps to the top, if it is scrolled down. This is a change in behavior--I assume it is related to #20030?

## Expected behavior

I expect that if I navigate by routerLink, the page does not scroll in response to the click. (I'm basing this expectation on how it used to behave).

## Minimal reproduction of the problem with instructions
Here are two Stackblitz links. The first link shows the new behavior. The second shows the old behavior.
https://stackblitz.com/edit/jump-on-click
https://stackblitz.com/edit/non-jumping-links
To see the change in behavior, do the following on each page. 

- click NARCO to load the details page. 
- scroll the window down a bit, so that the dashboard button is still visible, but the window isn't scrolled all the way to the top. 
- click the Dashboard button

In the angular 6.1 version, the page will jump to the top. In the 6.0 version, the scroll position will remain unchanged.

## What is the motivation / use case for changing the behavior?
While this is a small jump here, on our site, we use this to scroll through image pages, and the jump makes for a jarring transition. See: https://boardgamegeek.com/image/1312759/sentinels-multiverse

## Environment

<pre><code>
Angular version: 6.1.3

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/25145, see also https://github.com/angular/angular/issues/24547

**Comment by karptonite** [comment]
Gah, I didn't find the right search term, I guess.

**Comment by karptonite** [comment]
Actually, reopening because the previous issue did not have a repro. Feel free to close if the repro is not useful, though.

**Comment by jasonaden** [comment]
Should be fixed with #25586, and will be released in tomorrow's release.
