### ISSUE TITLE
No changelog for 6.1.3

### ISSUE THREAD

**Issue by fabioemoutinho** [angular/angular#25565]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

No changelog for 6.1.3 at changelog.md

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/25513

Check at 6.1.3 branch. Still weird since there are other 6.1.x logs in master.

**Comment by fabioemoutinho** [comment]
Its good we can find the changelog there, but i think changelog.md at master should be updated.
