### ISSUE TITLE
Ivy runtime performance

### ISSUE THREAD

**Issue by matthewjh** [angular/angular#25569]
What is the expected effect of the Ivy renderer on runtime performance, excluding gains from reduced bundle sizes?

I can see how ideas like breaking the renderer into atomic functions directly called by templates and locality improve bundle size and build times; it's much harder for me to see how that would help runtime performance. It seems that things like whole-program analysis and encoding directive information into consuming templates would improve runtime performance (surely why Angular did them in the first place), and that removing them would be detrimental from that perspective. 

Curious to get your thoughts @mhevery

**Comment by hiepxanh** [comment]
I have the same question

**Comment by matthewjh** [comment]
@trotyl yes, I know and I agree.

However, I'm curious to hear from the angular team because I'm not intimately familiar with Ivy, and there may be changes I'm unaware of that in fact improve the runtime performance beyond that from the smaller bundles.

**Comment by pkozlowski-opensource** [comment]
@matthewjh excited to see all the community interest around ivy! Regarding your question about runtime performance - it is really too early to speculate. In fact it is seldom a good idea to speculate - we need hard numbers.

From our _initial_ testing it seems like we _might_ be faster as compared to the current view on our large tree / large table benchmarks.  But we should wait with any meaningful comparisons till:
* all the functionality is covered;
* all the in-flight / perf-oriented refactorings land;
* we go through a cycle of perf measuring / tunning.

Before the above happens all is just speculation. We need to ask you for more patience till we've got work completed and can share meaningful numbers. 

But yeh, generally speaking we aim at having ivy _at least_ as fast as the current view engine. Only time will tell how good we've managed.

Closing as there is nothing actionable here for now.

**Comment by mlc-mlapis** [comment]
... isn't it the right time to publish some design docs for Ivy? All outside the core time has no real information about the basic build stones and what are the principal game rules. Re-engineering the source code and guess what was on the beginning is really wasting of expensive time.

**Comment by matthewjh** [comment]
thanks @pkozlowski-opensource! Everything you said makes good sense. Looking forward to seeing numbers (including bundle size reduction!) and using Ivy.
