### ISSUE TITLE
Generated Change Detectors do not properly handle pure functions

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#2556]
Fix handling pure functions and reenable change detectors:
https://github.com/angular/angular/blob/master/modules/angular2/src/core/application.ts#L72

Generated change detectors always reset the result of pure functions to undefined.

**Comment by naomiblack** [comment]
Tracking note: this is assigned to vsavkin to see if it can be quickly unblocked, otherwise, please assign to @jakemac53 or @yjbanov.

**Comment by naomiblack** [comment]
internal issue is b/21857179

**Comment by vicb** [comment]
Fixing this would probably close #461
