### ISSUE TITLE
Different behavior in IE when passing undefined as attribute value

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#25575]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
In IE when `undefined` is passed as attribute, the attribute stays unchanged

## Expected behavior
The attribute should be removed from element

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-izw8fv
In Chrome, when You click "set value" value attribute will be added to input and when You click "reset value" the attribute will be removed.
In IE, when You click "reset value" nothing changes

## What is the motivation / use case for changing the behavior?
Consistent behavior across browsers

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dawidgarus** [comment]
@jasonaden I don't think it's an issue with forms, but with binding to attribute (`[attr.value]`)

**Comment by pkozlowski-opensource** [comment]
It looks like IE / Edge bug to me. I've just tried this in the Edge 18 console:
```
var i = document.createElement('input');
i.setAttribute('value', 'value''); // at this point Edge prints <input value="value">
i.removeAttribute('value');

// !!! still prints <input value="value">
```

Looks like, for some reason, Edge can't remove the `value` attribute from the input element?! 

> The attribute should be removed from element

Yep, I would also expect this behaviour but it seems like there is a bug in Edge's implementation (haven't tested other IE versions). Not sure what could Angular do about this as we are trying not to have browser-specific work-arrounds as much as possible.

Alternative approach here would be to bind to the `value` property which is default in Angular and seem to work correctly in Edge: https://stackblitz.com/edit/angular-5wketj?file=src%2Fapp%2Fapp.module.ts

I'm going to close this issue as it seems to be a browser bug.
