### ISSUE TITLE
NullInjectorError: No provider for ChangeDetectorRef!

### ISSUE THREAD

**Issue by dimitriy-k** [angular/angular#25574]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
After upgrade `6.0.9` > `6.1.3`

Error
<code>
StaticInjectorError(AppModule)[ReadMoreComponent -> ChangeDetectorRef]: 
  StaticInjectorError(Platform: core)[ReadMoreComponent -> ChangeDetectorRef]: 
    NullInjectorError: No provider for ChangeDetectorRef!
</code>

## Expected behavior
no error

## Minimal reproduction of the problem with instructions
<pre><code>
import {
  AfterViewInit,
  ChangeDetectorRef,
  Component,
  ElementRef,
  Input,
  OnChanges,
  SimpleChanges
} from '@angular/core';

@Component({
  selector: 'app-read-more',
  template: `
      <span class="read-more-content">{{ fullText }}</span>
      <span *ngIf="readMore && !expanded" (click)="showFull()" class="read-more">...</span>
 })
export class ReadMoreComponent implements AfterViewInit, OnChanges {
  @Input()
  fullText: string;
  public limit = 200;
  public readMore = false;
  public expanded = false;
  public textNode;

  constructor(private elt: ElementRef, private cdr: ChangeDetectorRef) {}

  ngAfterViewInit() {
    this.textNode = this.elt.nativeElement.querySelector('.read-more-content');

    if (this.fullText !== undefined && this.fullText.length > this.limit) {
      this.readMore = true;
      this.setText(this.fullText.substring(0, this.limit));
      this.cdr.detectChanges();
    }
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes.fullText) {
      this.textNode = this.elt.nativeElement.querySelector('.read-more-content');
      const newText = changes.fullText.currentValue;
      if (newText !== undefined && newText.length > this.limit) {
        this.readMore = true;
        this.expanded = false;
        this.setText(newText.substring(0, this.limit));
        this.cdr.detectChanges();
      }
      if (newText !== undefined && newText.length <= this.limit) {
        this.readMore = false;
        this.setText(newText);
        this.cdr.detectChanges();
      }
    }
  }

  showFull() {
    this.expanded = true;
    this.setText(this.fullText);
  }

  setText(text: string) {
    this.textNode.textContent = text;
  }
}
</code></pre>

## Environment

<pre><code>
"dependencies": {
    "@angular/common": "^6.1.3",
    "@angular/compiler": "^6.1.3",
    "@angular/core": "^6.1.3",
    "@angular/forms": "^6.1.3",
    "@angular/http": "^6.1.3",
    "@angular/platform-browser": "^6.1.3",
    "@angular/platform-browser-dynamic": "^6.1.3",
    "@angular/router": "^6.1.3",
    "@ng-bootstrap/ng-bootstrap": "^3.0.0",
    ...
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.7.4",
    "@angular/animations": "^6.1.3",
    "@angular/cli": "^6.1.4",
    "@angular/compiler-cli": "^6.1.3",
    "@angular/platform-server": "^6.1.3",
   ...
  }
</code></pre>

Browser:
- [x ] Chrome (desktop) version XX

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

<hr>

Unfortunately, pasting code into Github isn't a reproduction. It's likely there's some other issue happening here, but if this is a real bug, a reproduction in StackBlitz would allow us to look into it and fix it.

**Comment by mytee306** [comment]
```
Error: StaticInjectorError(AppModule)[AsyncPipe -> ChangeDetectorRef]: 
StaticInjectorError(Platform: core)[AsyncPipe -> ChangeDetectorRef]: 
NullInjectorError: No provider for ChangeDetectorRef!
```

Reproduced [here](https://stackblitz.com/edit/angular-change-detector-ref-issue?file=src%2Fapp%2Flocale-date.pipe.ts)

**Comment by Jordan-Hall** [comment]
@mytee306 

I was getting the same issue with ChangeDetectorRef and wanted to play around with a smaller application to fix it. Looking at your solution, you are implementing things wrong. https://stackblitz.com/edit/angular-change-detector-ref-issue-x29xnl Thats a working version

**Comment by matheo** [comment]
I'm having this issue with `yank link`ed and `hmr` reloaded module, which I think is a recipe to trigger this conflict.

**Comment by ealfonsov89** [comment]
> @mytee306
> 
> I was getting the same issue with ChangeDetectorRef and wanted to play around with a smaller application to fix it. Looking at your solution, you are implementing things wrong. https://stackblitz.com/edit/angular-change-detector-ref-issue-x29xnl Thats a working version

If I have a dynamic pipe where i can call any pipe I want, then i can not use the async like in the sample, I need to inject it in to my custom pipe and use it. Is there not a fix to the error?
