### ISSUE TITLE
Angular lazy loading with router-outlet secondary not working

### ISSUE THREAD

**Issue by kevinlllR** [angular/angular#25571]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

UserComponent and PersonalComponent are not displayed, when you click on the Personal Section or Click UserSection but the route if it is updated and PersonalModule and UserModule they are loaded.

## Expected behavior

Show UserComponent and PersonalComponent, when you click on Click Personal Section or Click UserSection

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-gpxnaf

## What is the motivation / use case for changing the behavior?

use secondary routes with lazy load

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ x] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

I have already implemented lazy loading of this type in another project, I was just making a copy in stackblitz of a similar use case to be able to test some other features, however I can not work the lazy load in this project (Copy of the other project that if it worked exactly the same)

I would appreciate if you told me that I am missing and I have been in this for a few hours and it seems that I can not find the solution

![not-work2](https://user-images.githubusercontent.com/18235710/44314203-791e6300-a3db-11e8-82f6-ce25b6b97028.png)

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

@kevinlllR This type of question is best asked on StackOverlow. However, if you think there's a bug here, please make a much more simple example and explain *exactly* what is happening. This example has lots of buttons, lots of components, and requires looking through the code in some detail to see what you're trying to do. Again, if there's a bug, just send a reproduction with the exact pieces that are broken and nothing else, with clear steps to reproduce.
