### ISSUE TITLE
feat(common/http): include HTTP method in HttpErrorResponse class

### ISSUE THREAD

**Issue by jotatoledo** [angular/angular#25577]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
The used HTTP method in a request that raises an error is not included in the `HttpErrorResponse` instance.

## Expected behavior
The used HTTP method should be included

**Comment by s-gbz** [comment]
I can give it a shot if some of the staff members provide me a little information on how to tackle it and where to look.

Is [this](https://github.com/angular/angular/blob/master/aio/content/examples/http/src/app/http-error-handler.service.ts) the right place to look? (Doesn't seem right 😄)

**Comment by jotatoledo** [comment]
@s-gbz the correct place would be [the base class for all HTTP responses](https://github.com/angular/angular/blob/6.1.7/packages/common/http/src/response.ts#L137-L201). I could tackle this myself, if @alxhub considers this to be a reasonable addition to the API.

My use case: after an error is triggered, I handle them and display a dialog with general information/help text + specific information depending on the status code. In the case of status code 409 (conflict), I need to display extra info depending of which verb was used to perform the request, which is currently only accessible by wrapping the error in another class.

**Comment by petebacondarwin** [comment]
This feature did not receive much community support and can be fairly easily implemented in an interceptor: https://stackblitz.com/edit/angular-ivy-oxsmzm?file=src%2Fapp%2Finterceptor.ts
