### ISSUE TITLE
How do i trigger validate function on @input changes [in custom validation Directive]?

### ISSUE THREAD

**Issue by rcloudsoftwares** [angular/angular#25584]
I created a validation directive, but its not triggering on @input changes

How do i trigger validate function on @input changes?

@Directive({
    selector: '[uppercase]',
    providers: [{
        provide: NG_VALIDATORS,
        useExisting: RdUppercaseDirective,
        multi: true
    }]
})
export class RdUppercaseDirective implements Validator, OnChanges  {
    @Input('uppercase') uppercase: any;

    r = new rdValidators;

    validate(control: AbstractControl): {
        [key: string]: any
    } | null {
        let u = this.uppercase === 'false' || this.uppercase === false ? false : true;
        return u ? this.r.uppercase(u)(control) : null;
    }

    ngOnChanges(changes: SimpleChanges){
        if(changes.uppercase){
           ###  **How do i trigger validate function here**
        }
    }
}

export class rdValidators {

    uppercase(req: boolean): ValidatorFn {
        return (control: AbstractControl): {
            [key: string]: any
        } | null => {
            if(!control.value)
            {
                return null;
            }
            if(req === false)
            {
                return null;
            }            
            var result = (/[a-z]/.test(control.value));
            return control.dirty  && control.value ? result ? { 'uppercase' : true } : null : null;
        }
    }
    
}

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
