### ISSUE TITLE
`[style.mask-image]` doesnt work

### ISSUE THREAD

**Issue by Dok11** [angular/angular#25598]
## I'm submitting a...

<pre><code>
[x] Bug report
</code></pre>

## Current behavior
```html
<div
  [style.mask-image]="'url(assets/image.png)'"
  [style.background-image]="'url(assets/image.png)'">
  Start editing to see some magic happen :)
</div>
```

generate html with:
```html
<div
  _ngcontent-c14=""
  style="background-image: url(&quot;assets/image.png&quot;);">
  Start editing to see some magic happen :)
</div>
```

## Expected behavior
```html
<div
  _ngcontent-c14=""
  style="mask-image: url(assets/image.png;); background-image: url(assets/image.png;);">
  Start editing to see some magic happen :)
</div>
```

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-9jix3u?file=src%2Fapp%2Fapp.component.html

## What is the motivation / use case for changing the behavior?
Work with component templates as it declarated.

## Environment

<pre><code>
Angular version: 6.1.2

**Comment by Dok11** [comment]
I found — `mask-image` uses with `-webkit` prefix, so Angular (or browser) are ignore this property.

**Comment by pkozlowski-opensource** [comment]
> I found — mask-image uses with -webkit prefix, so Angular (or browser) are ignore this property.
> now I think this is not bug of Angular, because them use native functions to set styles. If you agree with me, please close issue :)

Yep, it is about the `-webkit` prefix
