### ISSUE TITLE
No unreachable code detection in HTML via Angular Language Service

### ISSUE THREAD

**Issue by pegak** [angular/angular#25597]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When I run `ng build --prod` and have unreachable code in .ts file e. g.
<pre><code>if (false) {
  console.log('test');
}
</code></pre>
it throws an `ERROR in XXX: error TS7027: Unreachable code detected.`, which is correct. But when I have unreachable code in `*ngIf` it does not detect it, e. g. `<div *ngIf="variable && 0 && variable.property">`

## Expected behavior

I would expect detection of always false (and other unreachable code) in template.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-gitter-zc4o9b

## What is the motivation / use case for changing the behavior?

When changing detection of empty array it happened that there was forgotten 0 in `*ngIf` and that part completely disappeared.

## Environment

<pre><code>Angular version: ^6.0.3
Angular language service: ^6.0.3"</code></pre>

**Comment by kyliau** [comment]
This is will be addressed as part of the language service upgrade after Ivy is released
