### ISSUE TITLE
https://stackoverflow.com/questions/51945178/how-to-display-html-and-component-code-into-web-page

### ISSUE THREAD

**Issue by AnuragCoder** [angular/angular#25592]
please loook into it ..!

https://stackoverflow.com/questions/51945178/how-to-display-html-and-component-code-into-web-page

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
