### ISSUE TITLE
FormArray ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by dsl400** [angular/angular#25606]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

SupplierComponent.html:7 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'disabled: false'. Current value: 'disabled: true'.

## Expected behavior

no error message

## Minimal reproduction of the problem with instructions

using FormGroup and FormArray,
get the form in valid state 
adding another input to the form will change the valid state of the form
behavior is normal, why does it trow errors ?

ngOnInit() {
    this.form$ = this.fb.group({
     ...
      contacts: this.fb.array([]);
    })
  }

get contactForm(){ return this.form$.get('contacts') as FormArray};

addInput(){
    const contact = this.fb.group({
      name: '',
      phone: ''
    })
    this.contactForm.push(contact);
  }

 <input matInput placeholder="Name" name="name" formControlName="name" **required** />

 <button [disabled]=**"!form$.valid"** >
 

## Environment

<pre><code>
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.4.2
@angular/cli                      6.0.8
@angular/material                 6.4.2

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

----

From the code snippet you posted, it seems you are probably missing `Validators.required` when you build up the form model in the class. With reactive form directives, you shouldn't use template-driven validator directives like `required` alone.
