### ISSUE TITLE
cleanup FakeXHR in tests

### ISSUE THREAD

**Issue by vicb** [angular/angular#2560]
Some test use a custom `FakeXHR` class to Fake the `XHR`.

The reason why was introduced is because `MockXHR` didn't play well with cascaded requests as you would have to call `xhr.flush()` multiple time.

We should be able to use `MockXHR` and convert the test to `fakeAsync()`  + flushing microtasks

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

`FakeXHR` no longer exist
