### ISSUE TITLE
Angular injector documentation is outdated

### ISSUE THREAD

**Issue by sridesmet** [angular/angular#25610]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The documentation of https://angular.io/api/core/Injector for the get function is different in the top of the page and the actual documentation of the get function (they forgot the T in front of the get)

## Expected behavior

Updated documentation.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
The problem is there're two `Injector.get` overloads and one of them being ignored. Likely an issue for docs app itself.

**Comment by jenniferfell** [comment]
@petebacondarwin @jbogarthyde : When you get a chance, can you take a look and determine if this is a doc content issue, doc markup issue, or dgeni issue? Thanks!

**Comment by jbogarthyde** [comment]
The page could use better doc, too. I can't figure out the details of how it works from what's there (in either version).

**Comment by petebacondarwin** [comment]
This should fix it https://github.com/angular/angular/pull/25670
It also sneaks in the deprecated information for the overloads.
