### ISSUE TITLE
router able to use modules' non-exported components 

### ISSUE THREAD

**Issue by MrOutput** [angular/angular#25615]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Module A's Router is able to reference Module B's component, though Module B's component is private (not exported).

## Expected behavior
Angular should throw a runtime error.

## Minimal reproduction of the problem with instructions
1. Create Module A
2. Create Module B
3. Create base components for both modules (do not export B's component)
4. Import Module B into Module A
5. Create Router for Module A, import B's non-exported base component
6. Hit Route (loads without issues)

## What is the motivation / use case for changing the behavior?
Angular should behave consistently about non-exported components. Modules shouldn't be able to use other modules' private components.

Angular normally throws a runtime error if this occurs, but if it's the Router that violates this policy, no error.

## Environment

<pre><code>
Angular version: 6.x.x

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 10.x.x
- Platform:  All

Others:
</code></pre>

**Comment by trotyl** [comment]
`exports` only meant for template in the selector matching, and dynamic components only care about `entryComponents`, they're not related.

**Comment by MrOutput** [comment]
@trotyl Are pipes and directives the same?

**Comment by trotyl** [comment]
> Are pipes and directives the same?

@MrOutput True, they're same, you can provide and inject any directive and pipe as normal service and no one could stop from doing it anywhere. There're no standard API for creating imperative directive and pipe for now. (Will be possible for directive in future)

> The exports are only required if the abstraction is used in a template???

True, for a dynamic-component only application (e.g. embedding `ngComponentOutlet`) the `exports` is totally meaningless.

**Comment by MrOutput** [comment]
@trotyl The behavior agrees with your statement, but this should be stated in the docs. Seeing many angular projects, it seems people are exporting things in err.

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

<hr> 

If you create a new issue, it sounds like it would be a docs issue. A thorough description of what needs to be documented would help if you decide to create the new issue.
