### ISSUE TITLE
Custom ErrorHandler doesn't work if error was thrown in not awaited promise

### ISSUE THREAD

**Issue by Sky4CE** [angular/angular#25612]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

### Bug discovery story:
Our project has global custom ErrorHandler to be able centrally process all errors. Everything were good for a while but then QA team started reporting that we missing some errors, I was thinking that this is impossible, but after some investigation I can confirm - indeed some errors just silently fail bypassing global ErrorHandler. This was nasty surprise.
### Bug explanation:
If error happens in sync method - everything is OK.
If error happens in promise which is awaited - everything is OK.
If error happens in promise with no await - everything is OK.
If error happens in promise which is awaited and that promise has `catch` callback declared - everything is OK.
If error happens in promise with no await and that promise has `catch` callback declared - **FAIL**, no error in ErrorHandler!

As an example consider an application with `ng-busy` 3rd party lib as a dependency, it is used to show spinner on UI while promise is in progress. We declare promise in our code and then pass it to `ngBusy` so it shows our spinner. This lib applies `then` and `catch` callbacks to our promise in order to implement its inner logic. Then when our business logic requires to **not** await some promise and when error happens in this promise - we have no error in ErrorHandler, hence miss it.

## Expected behavior

All errors that happen inside application should be caught by ErrorHandler. Either they inside promise or not, awaited or not, have `then`/`catch` callbacks or not, etc...

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/error-handler-bug-angular-6?embed=1&file=src/app/error-bug.component.ts

## What is the motivation / use case for changing the behavior?

To have central place where all errors could be processed.

## Environment

<pre><code>
Angular version: 6.1.3

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 9.3.0  
- Platform:  Windows
- NPM: 6.3.0
- Typescript: 2.9.2
- RxJs: 6.2.2
- Zonejs: 0.8.26

Others:

</code></pre>

**Comment by manklu** [comment]
> If error happens in promise which is awaited and that promise has catch callback declared - everything is OK

This works since await itself throws an exception if a promise is rejected.

> If error happens in promise with no await and that promise has catch callback declared - FAIL, no error in ErrorHandler!

Normal local error handling. You catch an exception, process it and the exception is gone unless you rethow it.

Maybe you should ask the library author why he silently swallow errors.

**Comment by trotyl** [comment]
@Sky4CE You totally misunderstood the Promise chain. When you call `.then` or `.catch` on a Promise then a new Promise is created, which is not related to the previous one you're using (not even referenced).

The Promise created by `.catch` is a successful one, unless you rethrow error inside.

**Comment by Sky4CE** [comment]
@trotyl have you seen my [repro](https://stackblitz.com/edit/error-handler-bug-angular-6?embed=1&file=src/app/error-bug.component.ts) ? Can you confirm that this is valid behavior ? If so could you please explain why only in *FAIL* case `catch` behave like this? I mean if remove `catch` then ErrorHandler catch error. And this happens only in *FAIL* case. Every other cases do not depent on `catch` whether it added or not.

**Comment by trotyl** [comment]
@Sky4CE It's already quite clear from @manklu, the promise generated by `.catch()` has no error thus would not be caught.

**Comment by trotyl** [comment]
@Sky4CE Besides, a direct copy and paste to console would be enough:

![image](https://user-images.githubusercontent.com/6059170/44598824-e9c3e600-a806-11e8-9473-fe41596f6fff.png)

If you have any question about why JavaScript work like this, please consider a legit JavaScript support question channel.

**Comment by Sky4CE** [comment]
@trotyl , @manklu that make sense, thanks for your help!
