### ISSUE TITLE
Cannot read property 'moduleType' of undefined  

### ISSUE THREAD

**Issue by jemin136** [angular/angular#25616]
Cannot read property 'moduleType' of undefined  while serve with --aot 

webpack : compile successfully but getting this error

**Comment by jasonaden** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
