### ISSUE TITLE
AOT Compile (Build, build prod) fail for single component class - probably related to public/private AOT compile

### ISSUE THREAD

**Issue by murphman300** [angular/angular#25624]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Running Serve, or non-aot builds does not catch the following "Property 'deviceName' does not exist on type 'LocationDeviceSettingsComponent" type of error.

## Expected behavior

All of my other components were not catching these errors, including those nested within templates. 

## What is the motivation / use case for changing the behavior?

Well.. it's a classic use-case.. a nested template within another template which is only displayed should a certain condition be met...

## Environment

<pre><code>
Angular version: 6.1.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4  
- Platform: macOS  

Others:

</code></pre>

Here is the component:
https://gist.github.com/5f6358f999918b3536e57409cc1e9d85.git

And here is the HTML
https://gist.github.com/murphman300/55a00de6d4e51d25c992d5a18e233c35

And here are the error logs:
> ERROR in src/app/frame/frames/location/devices/location-device-settings.component.html(25,63): : Property 'deviceName' does not exist on type 'LocationDeviceSettingsComponent'.
> src/app/frame/frames/location/devices/location-device-settings.component.html(25,63): : Property 'deviceName' does not exist on type 'LocationDeviceSettingsComponent'.
> src/app/frame/frames/location/devices/location-device-settings.component.html(25,88): : Property 'removeError' does not exist on type 'LocationDeviceSettingsComponent'.

Like I said, my setup works without AOT. With it, it doesn't work. For some reason, only this component behaves like this, which is odd, because there are three other distinct component classes operating at the same nesting level without any bugs or issues with AOT.

So far I literally changed all properties and methods to public, from app.component.ts down.. this doesn't change the result.

Therefore, I'm not sure if this can be reproduced, but any guidance, or confirmation that this might be a continuance of the prior AOT public/private bugs from the last 2 years would be of great help...

Thanks

**Comment by Destreyf** [comment]
@murphman300 Your code is referencing a class named `LocationDeviceSettingsComponent` but the snippet you posted h as a class name of `LocationDeviceSettingsViewComponent` this makes me wonder if you're using the html in a second place, perhaps where the `LocationDeviceSettingsComponent` is, put that doesn't have a public member named `deviceName`.

I just did an AoT build last night myself without any issues on 6.1.4, so i have to wonder if there's a potential overlap of components.

**Comment by murphman300** [comment]
Right on,
It was in fact two components that pointed to the same HTML file, hence the build-time hickup.

Many thanks for the pointer @Destreyf !
