### ISSUE TITLE
@angular/language-service generates warning for mock components that are used in tests

### ISSUE THREAD

**Issue by fr0** [angular/angular#25623]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
```
ng: Component 'TestingHostComponent' is  not included in a module and will not be avialable inside a template. Consider adding it to a NgModule declaration
```

The error is misleading/incorrect when using mock components for unit tests. They're not supposed to be in a module (apart from the module I configure using `TestBed`) and they never will be.

## Expected behavior

The warning should not be present, [or it should be silenceable](https://github.com/angular/angular/issues/13726). Ideally, the Angular language service would notice that the component is used in a `TestBed` module, and wouldn't complain about it.

## Minimal reproduction of the problem with instructions

Here's a stackblitz that shows off my use case:
https://stackblitz.com/edit/angular-bqhw1k
(I don't think the language service works in stackblitz, though).
Note that I'm using [spectator](https://github.com/NetanelBasal/spectator) to simplify the testing boilerplate, but it just wraps the `TestBed` API.

## What is the motivation / use case for changing the behavior?

Using a host component for unit tests of another component.

## Environment

<pre><code>
Angular version: 6.1.3
Mac, Webstorm 2018.2

**Comment by atscott** [comment]
Closing as obsolete
