### ISSUE TITLE
APP_INITIALIZER provider fails to load from library module in production build

### ISSUE THREAD

**Issue by samherrmann** [angular/angular#25621]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When defining an `APP_INITIALIZER` in a library module, the build fails with the `Lambda not supported` error. The build error is thrown when the function is exported [as per docs](https://angular.io/guide/aot-compiler#function-calls-are-not-supported):

```
import { NgModule, APP_INITIALIZER } from '@angular/core';
import { MylibComponent } from './mylib.component';

export function myLibInit() {
  return () => console.log('Hi from exported function');
}

@NgModule({
  providers: [
    {
      provide: APP_INITIALIZER,
      multi: true,
      useFactory: myLibInit
    }
  ]
})
export class MylibModule { }
```
The build error is thrown in both `dev` and `prod`.

I have alternatively also tried defining the factory function using ES6 object method shorthand notation:

```
import { NgModule, APP_INITIALIZER } from '@angular/core';
import { MylibComponent } from './mylib.component';

@NgModule({
  providers: [
    {
      provide: APP_INITIALIZER,
      multi: true,
      useFactory() {
        return () => console.log('Hi from ES6 object method shorthand')
      }
    }
  ]
})
export class MylibModule { }
```
This passes both the `dev` and `prod` build, but the app throws the `ERROR TypeError: this.appInits[r] is not a function` error at runtime.

## Expected behavior
No build or runtime errors when defining an `APP_INITIALIZER` in a library module.

## Minimal reproduction of the problem with instructions
A reproduction can be found [here](https://github.com/samherrmann/angular-sandbox/commit/0155b17e5873f52d41c4cd6a3921035506060cc5#diff-34f36f8e2a73931ea1bfed30a4d05f22):
1. `git clone https://github.com/samherrmann/angular-sandbox.git`
2. `cd angular-sandbox`
3. `git checkout lambda-not-supported`
4. `npm install`
5. `npm run build`

## What is the motivation / use case for changing the behavior?
To allow libraries to initialize providers when app imports library module.

## Environment
```
Angular CLI: 6.0.0
Node: 8.11.1
OS: linux x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.0
@angular-devkit/build-angular      0.6.0
@angular-devkit/build-ng-packagr   0.6.8
@angular-devkit/build-optimizer    0.6.0
@angular-devkit/core               0.6.0
@angular-devkit/schematics         0.6.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.0
@schematics/angular                0.6.0
@schematics/update                 0.6.0
ng-packagr                         3.0.6
rxjs                               6.1.0
typescript                         2.7.2
webpack                            4.6.0
```

Others:
[Related issue](https://github.com/angular/angular/issues/24944)

**Comment by manklu** [comment]
According to the documentation, your function should return a value, not a function.

**Comment by samherrmann** [comment]
@manklu can you link to the documentation you are referring to? From blogs such as [this one](https://www.intertech.com/Blog/angular-4-tutorial-run-code-during-app-initialization/) and [this one](https://hackernoon.com/hook-into-angular-initialization-process-add41a6b7e), as well as how [Angular uses it internally](https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/platform-webworker/src/web_workers/worker/location_providers.ts#L37), it looks to me that the factory function needs to return a function. Typically that inner function then returns a promise, but it [appears that returning a promise is optional](https://github.com/angular/angular/blob/af07ffc2ad40d647613b1c6a851c1548a30c6707/packages/core/src/application_init.ts#L55).

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by samherrmann** [comment]
For anyone interested, my StackOverflow (with answer) is [here](https://stackoverflow.com/questions/51976671/app-initializer-in-library-causes-lambda-not-supported-error). I have in the meantime also found issue #23629 that tracks the inconsistent behavior between defining a `APP_INITIALIZER` factory function in libraries vs apps.
