### ISSUE TITLE
events (keyup) and (keyup.enter) on <input> don't work together unless they are in one particular order

### ISSUE THREAD

**Issue by lugaramirez** [angular/angular#25622]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

On an input if the (keyup) event is before (keyup.enter), the keyup.enter receives the var.value if a method is introduced. If they appear in reverse, the keyup.enter will receive an empty var.value.

## Expected behavior

Doesn't matter the order of the events, all of them should receive the var.value

## Minimal reproduction of the problem with instructions

- input something on the first input and press enter; the text will change accordingly
- same for the second input; the text wont change

https://stackblitz.com/edit/angular-g3d7iu

(Edit: sorry... bad URL)

## Environment

<pre><code>
Angular version: 6.1.3

Browser:
- [x] Chrome (desktop) version 68
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.4  
- Platform: Windows and Linux 

Others:

</code></pre>

**Comment by jasonaden** [comment]
Per the info you filled out for this issue, this worked in a previous version and then broke (you marked it as a *regression*). Is that correct?

**Comment by trotyl** [comment]
It's indeed the expected behavior, you didn't have any filtering in `(keyup)` handler, meaning it will also response to Enter key, and given `(keyup)` handler is executed after `(keyup.enter)` as your declaration in template.

If it works in v5 then please also provide the "working" repro with the old version, but most likely it's a bug in v5 if it ever worked.

**Comment by lugaramirez** [comment]
oh, ok, that makes sense. Since the last keyup event (not enter) already processed the event, the next keyup (the enter) will have an empty value in the event. Ok, thanks!
