### ISSUE TITLE
Title Attribute doesn't accept safeHtml

### ISSUE THREAD

**Issue by marcelcremer** [angular/angular#25631]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When providing trusted HTML to the title property, Angular replaces it with "SafeValue must use [property]="binding", even if it was precalculcated.

## Expected behavior

The safe HTML should be outputted, e.g.  

``` Foo&amp;Bar```  

becomes

```Foo&Bar.```  

## Minimal reproduction of the problem with instructions

You can see the behaviour in the following StackBlitz:
https://stackblitz.com/edit/angular-irc-starter-cpptfb?file=app/hello.component.ts

## Environment

<pre><code>
Angular version: 6.0.3

**Comment by trotyl** [comment]
Angular didn't sanitize anything in your example, please check the console logs (any sanitization would produce warning). The `title` attribute isn't HTML-aware, you cannot pass HTML literal to it.

![image](https://user-images.githubusercontent.com/6059170/44528255-a476ba00-a71b-11e8-804d-71adcd50d61a.png)

**Comment by marcelcremer** [comment]
@trotyl Mhm strange - the static output was rendered as I expected (Foo&Bar), so angular does something with the static text that it doesn't do with the variable. 

However, I also read that the title isn't HTML-aware a few minutes ago (at least not standard W3C), so I'll close this issue.

Sorry to have bothered you and thank you for your time.
