### ISSUE TITLE
Component with ViewEncapsulation.ShadowDom has all Emulated component's CSS inside its shadow dom

### ISSUE THREAD

**Issue by liorwohl** [angular/angular#25638]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Have an app with some "Emulated" encapsulation components, change one of the components to "ShadowDom" encapsulation.
Inspect element inside the generated shadow-dom - you can see style tags from all the components in the app, with the [_ngcontent-c1] syntax.
The one style that is really needed is also inside the shadow dom, no problem with that.

## Expected behavior

only one style tag of the current component inside the shadow dom.

## What is the motivation / use case for changing the behavior?

the shadow root is messy with irrelevant styles, and it might even apply styles that should not be applied.

## Environment

<pre><code>
Angular version: 7.0.0-beta.2 / 7.0.0-beta.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.1  
- Platform:  Mac 

Others:

</code></pre>

**Comment by trotyl** [comment]
This is how interaction between `Emulated` and `ShadowDom` works, anything inside `shadow-root` is not affected by global `<style>` tags, means that your (emulated) component style would gone if placed inside another (shadowDom) component.

Copying the `<style>` tags is required to preserve the component styles.

**Comment by liorwohl** [comment]
Ok, but still it would be nice if the style-tag-adding inside shadow dom was done on the event of emulated component load (eg when needed)

**Comment by alxhub** [comment]
Working as intended as described by @trotyl.

**Comment by IStranger** [comment]
In such case, it is useless encapsulation mode, because `ViewEncapsulation.ShadowDom` does not adds any additional encapsulation functionality (in comparison with `Emulated`).

@alxhub Could you explain, what is the reason to add excess styles inside of component?

**Comment by mlc-mlapis** [comment]
@IStranger ... it's the principal functionality ... to protect inner part against the outer environment ... bacause the `ViewEncapsulation.Emulated` can be hacked from outside.
