### ISSUE TITLE
Types of property 'canActivateChild' are incompatible.

### ISSUE THREAD

**Issue by annuranjan** [angular/angular#25639]
## I'm submitting a...

<pre><code>
[ x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I'm trying to implement Route protection by using "canActivateChild". This thing worked fine earlier, but there seems to be issue this time. It throws an error: 
```
ERROR in src/app/app-routing.module.ts(8,7): error TS2322: Type '({ path: string; redirectTo: string; pathMatch: string; } | { path: string; component: typeof Log...' is not assignable to type 'Route[]'.
  Type '{ path: string; redirectTo: string; pathMatch: string; } | { path: string; component: typeof Logi...' is not assignable to type 'Route'.
    Type '{ path: string; component: typeof MainContentComponent; canActivateChild: typeof PlayVidAuthGuard...' is not assignable to type 'Route'.
      Types of property 'canActivateChild' are incompatible.
        Type 'typeof PlayVidAuthGuardService' is not assignable to type 'any[]'.
          Property 'includes' is missing in type 'typeof PlayVidAuthGuardService'.
```
Here is my part of code which is causing error: 
```
const appRoutes: Routes = [
  { path: "", redirectTo: "login", pathMatch: "full" },
  { path: "login", component: LoginComponent },
  {
    path: "home",
    component: MainContentComponent,
    canActivateChild: PlayVidAuthGuardService,
    children: [
      {
        path: "",
        component: PlayVideoComponent
      }
    ]
  }
];
```
Now the error goes away when I remove `canActivateChild` field. But that is my requirement. 
Here's PlayVidAuthGuardService .ts file:
```
export class PlayVidAuthGuardService implements CanActivate {
  myBool: boolean = true;
  constructor() {}
  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
    return this.myBool;
  }
```
Even when I put `canActivate` inside of the childroute, I get the same error. 
How can I fix this? Thank you! 
## Environment

<pre><code>
Angular version: 6.1.0

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.9.0
- Platform:  Windows

Others:

</code></pre>

**Comment by manklu** [comment]
I think this part of the error message
```
Type 'typeof PlayVidAuthGuardService' is not assignable to type 'any[]'.
```
and this snippet from the documentation
```javascript
      {
        path: 'root',
        canActivateChild: [CanActivateTeam],
        children: [
```
are helpful for you.

And no, according to the Angular 2 documentation it's no regression.

**Comment by Destreyf** [comment]
@manklu 

Quick question, can you try changing your route on the `canActivateChild`, wrap the `PlayVidAuthGuardService` in square braces like this: `canActivateChild: [PlayVidAuthGuardService]`

I believe that the canActivateChild requires an array of guards (array of any is the thrown error) but you're giving it a single type.

**Comment by annuranjan** [comment]
@manklu @Destreyf 
You guys are right. This is making it work as expected.
@manklu 
Sorry for marking it as regression. It clearly is a mistake on my part.
