### ISSUE TITLE
CLI --dryRun used with alternate case is ignored.

### ISSUE THREAD

**Issue by rlove** [angular/angular#25642]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using using the --dryRun command line parameter,
with an alternate case such as --dryrun or --DryRun 
it will allow the generated command to execute, and files are created.

## Expected behavior

One of two options.
  - Error that alternate cased parameter is not expected and fail to execute
  - accept --dryRun regardless of case used.

## Minimal reproduction of the problem with instructions
<pre>
<code>
PS C:\dev\testapp\src\shared> ng g s myTest --dryrun
CREATE src/shared/my-test.service.spec.ts (375 bytes)
CREATE src/shared/my-test.service.ts (135 bytes)
</code>
</pre>
What happens when used with proper case
<pre>
<code>
PS C:\dev\testapp\src\shared> ng g s myTest2 --dryRun
CREATE src/shared/my-test2.service.spec.ts (381 bytes)
CREATE src/shared/my-test2.service.ts (136 bytes)

NOTE: Run with "dry run" no changes were made.
</code>
</pre>
## What is the motivation / use case for changing the behavior?

Hold the hand of the developer who mistyped the command line.

## Environment

<pre><code>
Angular version: 6.1.2 
Angular CLI version: 6.1.3

For Tooling issues:
- Node version: v8.11.3
- Platform:  Windows
</code></pre>

**Comment by sarunint** [comment]
I root for the second option. 😄

**Comment by sarunint** [comment]
@rlove I didn't realise that you've opened an issue in the wrong repo. File an issue at angular/angular-cli instead!

**Comment by rlove** [comment]
Sure thing

**Comment by rlove** [comment]
When looking at the correct repo this issue is a duplicate of 

#https://github.com/angular/angular-cli/issues/11641
