### ISSUE TITLE
Unexpected behaviour of NgIf directive in the context of child views retrieved via custom RouteReuseStrategy

### ISSUE THREAD

**Issue by jonathan-wilkinson** [angular/angular#25640]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Where a component is served by a router outlet and that same component has also been previously retrieved from a cache via a custom RouteReuseStrategy, an NgIf directive which is a parent of that router outlet will destroy that component and then attempt to reuse it. This results in a "Cannot insert a destroyed View in a ViewContainer" error.

## Expected behavior

When a component which has _not_ been restored via a custom RouteReuseStrategy is is reinitialised. In the context of a component which _has_ been restored via a custom RouteReuseStrategy it would be sensible if either: 

1. The component would not be destroyed by the NgIf directive and could be reused without causing an error
2. The component would be destroyed but then reinitiated (just as all other components).

In other words, there should be _some_ way to use a RouteReuseStrategy in conjunction with NgIf as one of its parents.

## Minimal reproduction of the problem with instructions

See: https://stackblitz.com/edit/angular-gitter-uktujy
Instructions to replicate are included on this page. 

## What is the motivation / use case for changing the behavior?

The use case is where there is a requirement to show persistent components as the output of a router outlet and this outlet is required to be shown/hidden via a parent NgIf directive. 
An example would be an application which has a high-level filter, the results of which shows a variety of detail components navigated by a side-nav. These detail components should be persistent between side-nav navigation changes (for, say, form input or further filtering of the detail component). Where the high-level filter is changed (to update the data shown in the detail components) we want to remove the detail components from display and show a loader instead.

## Environment

<pre><code>
Angular version: 6.0.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jasonaden** [comment]
Closing based on the above comment and no additional activity. If this issue persists, please file a new issue.
