### ISSUE TITLE
refactor(Http): remove HttpFactory

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2564]
There are two things that can be injected in order to perform Http requests, `Http` or `HttpFactory`. Http is a class with the primary method of `request`, plus some shortcut methods like `get`, `post`, etc. `HttpFactory` is a function equivalent to `Http.request`. 

I think having `HttpFactory` adds more concepts/complexity than is warranted, and I'd like to remove it. For one, it requires two more pages of documentation. One page to document the factory itself, and another to document the `IHttp` interface that exists solely to provide type information for the factory.

```js
// Factory
import {HttpFactory, IHttp} from 'angular2/http';
class MyComponent {
  constructor(@Inject(HttpFactory) http:IHttp) {
    http('angular.json').subscribe(ng => this.angular = ng);
  }
}

// Class
import {Http} from 'angular2/http';
class MyComponent {
  constructor(http:Http) {
    http.request('angular.json').subscribe(ng => this.angular = ng);
  }
}
```

The idea of having a simple callable function instead of calling a class method is nice, but I think the trade-off of additional concepts isn't worth the overhead.

@blesh @caitp what do you two think?

**Comment by blesh** [comment]
What are the semantics for more complex use cases, like POST with custom headers vs GET or PUT. How are methods/verbs specified?

**Comment by jeffbcross** [comment]
@blesh those would be specified in the RequestOptions object (or Request) passed to `http.request(opts)`, or one of the respective shortcut methods, `http.get(opts)`.

```js
http.request({
  method: 'GET',
  url: 'foo.json',
  headers: { trustMe: true}
}).subscribe(res => this.res = res);
```

**Comment by blesh** [comment]
Cool. What are the defaults?
