### ISSUE TITLE
How to handle conditional operator value in template using i18n

### ISSUE THREAD

**Issue by shobhit12345** [angular/angular#25655]
How to handle conditional operator value in template using i18n. Do we need to break this condition ?

```
<div  *ngIf="isOK">
<a href="javascript:void(0)" data-toggle="collapse" class="no-underline collapsed" (click)="showHistoryInfo(paymentMethod)">
 {{paymentMethod.historyOpned ? "Hide" : "Show"}} History
</a>
</div>
```

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter

**Comment by davydkov** [comment]
@shobhit12345 Did you find a solution? I have the same issue with `i18n` and conditional strings

**Comment by salah3x** [comment]
@pkozlowski-opensource The problem is for example I have in my template :
`<p i18n> {{ condition ? 'Value1' : 'Value2' }} </p>`
when extracting the translation using `ng xi18n` command, it simply doesn't work :disappointed:

The output is something like this : 
```
<source>
  <x id="INTERPOLATION" equiv-text="{{condition  ? &apos;Value1&apos;: &apos;Value2&apos;}}"/>
</source>
```

Is there any solution or workaround ?

**Comment by salah3x** [comment]
And the same thing goes for `<img i18n-alt [alt]="condition ? 'Value1' : 'Value2'"/>`
This doesn't even get picked up by `ng xi18n`, no output at all.

**Comment by kojilab** [comment]
It gets picked up in the xlf file in my case but the target isn't used when displaying the final result.

**Comment by TatianaBir** [comment]
<p i18n> {{ condition ? 'Value1' : 'Value2' }} </p>
<source>
  <x id="INTERPOLATION" equiv-text="{{condition  ? &apos;Value1&apos;: &apos;Value2&apos;}}"/>
</source>

this works like this:
<target>{{condition  ? &apos;TranslatedValue1&apos;: &apos;TranslatedValue2&apos;}}</target>
