### ISSUE TITLE
ngDoCheck is faster than propagate change from sibling custom form component

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [angular/angular#25656]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have an app with two custom form components.
Component A has two drag and drop list with [ngx-drag-drop](https://github.com/reppners/ngx-drag-drop) in which I `writeValue` to its form control and then propagate change upstream.
Component B has a map integration and has an Input property that is the value from component A form value. Because it is an array I used `ngDoCheck` in component B with a iterable differ. 

Let's suppose I get the lists and drag Element A and element B to the right. I have AB and the map component has AB

It all works fine until I reorder the output lists `(AB -> BA)` when momentarily the list has one extra duplicate element `ABA`. I'm not sure if it's fault from the library where an issue has been raised: reppners/ngx-drag-drop#36

I solved that by setting a timeout to `writeValue` and then there are 2 elements in the array `BA` and I can propage upstream the correct list

```
 writeValue(value: any): void { if (value) {
      console.log(`writeValue value length ${value.length}`);

      this.form.get('input').setValue(value)

      this.propagateChange(this.form.get('input').value);
}}
```

But with `writeValue` as is the change appears to be propagated faster and logged in my `ngDoCheck` in the map component

```
ngDoCheck() {
        if (this.route) {
            if (this.differ.diff(this.route) && this.route.length > 1) {
                console.log(`gonna make a route with ${this.route.length} stops`);
            }
        }
    }
```

So I get this log sequence even though I don't get 3 stops in `writeValue` to propagate.
```
gonna make a route with 3 stops
gonna make a route with 2 stops
writeValue value length 2
```

* If I comment `propageChange` `ngDoCheck` does nothing
* If I don't send any value on `propageChange` `ngDoCheck` does nothing

## Expected behavior

ngDoCheck should only get the value I propagate upwards one value

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/ngx-drag-drop-issue-template-tm-awrzjs

1. Drag two elements from list A to list B.
2. Reorder the elements on list B like  `AB -> BA`
3. Check logs

## Environment

<pre><code>
Angular version: 6.0.2. Stackblitz link above is on 6.1.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.3  
- Platform: macOS 10.13.6  

Others:

</code></pre>

**Comment by mhevery** [comment]
Sorry this repro is way to complicated and we don't have time to figure it out. Please provide *minimal* repro.

**Comment by tiagomsmagalhaes** [comment]
@mhevery How it is too complicated? Most of the code is mandatory code due to `ControlValueAcessor`, `DoCheck` and `IterableDiffers`. The rest of the code is an external library that just interacts explicitly with angular to call `writeValue` in of those methods. If I remove that I can't reproduce the problem.

The reproduction has 3 steps and logs everywhere to help understand the behaviour

**Comment by mhevery** [comment]
We have a lot of things to look at so we don't have time to figure things out. If you want this issue to be looked at than you have to make it super trivial for us, otherwise there are many other issues we need to fix. I understand that these things seem obvious to you but a simple act that drag-and-drop is involved tells me that it is not as simple as it could be.
