### ISSUE TITLE
Angular maxlength validation allows to enter more character in Chrome for android

### ISSUE THREAD

**Issue by navneetsharma1988** [angular/angular#25651]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Angular maxlength validation in template allows entering more character in Chrome for Android, It trims the extra characters on blur event. 
This happens only in Reactive Form input element used with formControlName and works fine in Template Form used with ngModel

## Expected behavior

This should prevent to enter more characters

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [x ] Chrome (Android) version 68
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kara** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter).

If this issue persists, please open a new issue with a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
