### ISSUE TITLE
Index.html page not responding

### ISSUE THREAD

**Issue by shubhanshushukla** [angular/angular#25657]
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
angular index.html page not loading

## Expected behavior
index.html should load correctly

## Minimal reproduction of the problem with instructions
I have created build without any error. Browsing index.html make browser not responding.
Found this line is culprit 
` 	var parentJsonpFunction = oldJsonpFunction;`

If i comment above line it will open blank  blank page means angular not working at all

## Environment

 
Angular version: 6
 

Browser:
- [ *] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ *] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6
- Platform: Linux

Others:

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter
