### ISSUE TITLE
Cannot match any routes , not able to find child routes

### ISSUE THREAD

**Issue by VKSgit** [angular/angular#25654]
Cannot match any routes

Error: 
![capture](https://user-images.githubusercontent.com/26575254/44573138-7c329e00-a7a3-11e8-8bc6-0f322e7885e2.PNG)

Router Config: 
export const appRoutes: Routes = [
  {
    path: '',
    pathMatch: 'full',
    loadChildren: './pages/user/login/login.module#LoginModule'
  },
  {
    path: 'dashboard',
    loadChildren: './pages/desktop/desktop.module#DesktopModule',
    pathMatch: 'full'
  }
];
export const AppRouting: ModuleWithProviders = RouterModule.forRoot(appRoutes);

export const desktopRoutes: Routes = [
  {
    path: '',
    component: DashboardComponent,
    pathMatch: 'full',
    children: [
      {
        path: '',
        component: FirstPageComponent
      },
      {
        path: 'admin',
        loadChildren: './pages/admin/admin.module#AdminModule'
      }
    ]
  }
];

export const DesktopRouting: ModuleWithProviders = RouterModule.forChild(desktopRoutes);

export const adminRoutes: Routes = [
  {
    path: 'assign-leads',
    component: AssignLeadsComponent
  }
];

export const adminRouting: ModuleWithProviders = RouterModule.forChild(adminRoutes);

Angular-cli.json
{
  "name": "franchiseindia",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "bootstrap": "^4.1.3",
    "core-js": "^2.5.4",
    "font-awesome": "^4.7.0",
    "jquery": "^3.3.1",
    "ngx-bootstrap": "^3.0.1",
    "popper.js": "^1.14.4",
    "rxjs": "^6.2.2",
    "rxjs-compat": "^6.2.2",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.7.0",
    "@angular/cli": "~6.1.3",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }
}

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
