### ISSUE TITLE
Excluding additional metadata when localizing i18n strings

### ISSUE THREAD

**Issue by danieldoolabh** [angular/angular#25665]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When upgrading to angular 6.1.1, it looks like there are some additional metadata tags which are now being included in the xmb file that's generated. Example snippet of what the xmb used to look like in angular 4:
```
    <msg id="1143311040585987910" desc="description" meaning="channel#id">
    <source>mycomponent.ts:8,10</source>
        Hello
    <ph name="INTERPOLATION">
      <ex>INTERPOLATION</ex>
    </ph>?
```
Example of what the xmb now looks like with angular 6.1.1:
 ```
   <msg id="1143311040585987910" desc="description" meaning="channel#id">
    <source>mycomponent.html:8,10</source>
        Hello
    <ph name="INTERPOLATION">
      <ex>{{ (target$ | async)?.token | async }}</ex>
    </ph>?
```

## Expected behavior
The interpolated string should not get output in the interpolation section (`<ex>{{ (target$ | async)?.token | async }}</ex>`).

## Minimal reproduction of the problem with instructions
annotate strings with @i18n tags and then generate xmb file with `npm run xi18n`

## What is the motivation / use case for changing the behavior?
 This is causing a lot of issues with our localization process and we will have to write a custom string parser that runs every time to remove the additional metadata

## Environment

<pre><code>
Angular version: 6.1.1

Browser: N/A
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4
- Platform:  Windows

Others:
N/A
</code></pre>

**Comment by ocombe** [comment]
We've added more detailed examples to help with localization, following what is recommended in the XLIFF spec, so this is "working as expected".
Can you tell me how this causes issues with your localization process? Anything in the `ex` tag is an example and should be ignored if you don't use it.

**Comment by danieldoolabh** [comment]
We have an automation tool which would do a comparison of which strings have changed based on whether the metadata have changed. Since the newest version of angular now has metadata for the interpolation, our automated tool is flagging a majority of strings as changed

**Comment by ocombe** [comment]
I see, not really a valid case for changing the current behavior though. I hope that you understand! Thanks for the feedback
