### ISSUE TITLE
Invalid route config shows ERROR in Cannot read property 'loadChildren' of undefined

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#25660]
## I'm submitting a...
[x] Bug report 

## Current behavior
If you have an invalid route config (empty item in the array), the error message isn't helpful to understanding what went wrong.

## Minimal reproduction of the problem with instructions
* ng new my-app --routing
* change route config from `[]` to `[,]` on line 4 of `app-routing.module.ts`
* ng serve

## Expected behavior
App works, or shows an error letting me know my routeConfig has an invalid / empty node

## Observed behavior
```
$ ng serve
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2018-08-24T16:44:47.249Z
Hash: 49a79cb11fa0ca0aa1aa
Time: 1698ms
chunk {main} main.js, main.js.map (main) 1.97 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 703 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 15.6 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 325 kB [initial] [rendered]

ERROR in Cannot read property 'loadChildren' of undefined
ℹ ｢wdm｣: Failed to compile.
```

## Environment

<pre><code>
Angular version: X.Y.Z
Angular CLI: 6.0.8
Node: 9.2.0
OS: linux x64
Angular: 6.1.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3
</code></pre>

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
