### ISSUE TITLE
[DART transformers] Add support for styles and styleUrls in Directive

### ISSUE THREAD

**Issue by vicb** [angular/angular#2566]
/ref #2459 #2563 

Two new properties have been introduced for `Directive`:
- `styles`: a list of css text
- `styleUrls`: a list of css urls

The template loader has been modified to resolved the url in the css and inline `@import` rules (this was previously done by the shadow dom strategies).

I'm not exactly sure what is left to be done in the transformers as they use the `TemplateLoader`.

**Comment by naomiblack** [comment]
@jakemac53 can you have a look at this one? we're hoping it's a straightforward fix at the transformer level.

**Comment by jakemac53** [comment]
can do
