### ISSUE TITLE
Child holding reference to parent array with or without ChangeDetectionStrategy.OnPush?

### ISSUE THREAD

**Issue by momoadeli** [angular/angular#25664]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Parent passes to child @Input an array (`things$ ~= this.thingsList`) observable of strings via template `(things$ async | pipe).things`. Parent subsequently updates `this.thingsList` array by pushing a 'thing' to it. Child view get's updated either immediately (child no ChangeDetectionStrategy,.OnPush) or after mat-accordion panel expansion events (child with ChangeDetectionStrategy,.OnPush). Seems like child is holding reference to parent `this.thingsList` array. This seems like @Inputs are being circumvented a la angularjs days.

## Expected behavior
Child should never hold reference to parent array (this.thingsList). Doesn't  @Input (deep) copy passed attributes?

## Minimal reproduction of the problem with instructions

stackblitz here: https://stackblitz.com/edit/angular-child-updated

NOTE: faking async http calls to return getThings() and addThing() Observables.
Click on 'add thing' button.`this.thingsList.push(thing)` is eventually invoked in parent. 

- Child Case 1 (child No ChangeDetectionStrategy.OnPush): Click on 'add thing' button. Both simple and mat-accordion lists are updated. Why? Seems child holding reference to parent array and @Input is being circumvented?

- Child Case 2 (child with ChangeDetectionStrategy.OnPush): Click on 'add thing' button. Expand mat-accordion panel. Both simple and mat-accordion lists are updated. Why? Seems child holding reference to parent array and @Input is being circumvented?

## What is the motivation / use case for changing the behavior?

Unexpected that child has maintained reference to parent member (array of 'this.thingsList') and child list can change even though @Input set() never get's triggered.

## Environment

<pre><code>
Angular version: 6.0.3
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/animations": "^6.1.4",
    "@angular/cdk": "^6.4.6",
    "@angular/material": "^6.4.6"

Browser:
- [ x ] Chrome (desktop) version 68.0.3440.106
 
For Tooling issues:
- Node version: v8.11.3
- Platform:  macOs Sierra

Others:

**Comment by mlc-mlapis** [comment]
@momoadeli ... related and explained by: https://github.com/angular/angular/issues/23933 ?

**Comment by momoadeli** [comment]
@mlc-mlapis  Perhaps. In my case, I totally understand what is transpiring from a purely JS perspective where the child has a reference to the array`this.thingsList array` in the parent. Since the array reference does NOT change on a push() @Inputs aren't triggered yet the list in the child view get's updated. Although not sure anything can be done, it is rather insidious.

**Comment by mhevery** [comment]
not feasible.
