### ISSUE TITLE
open doc preview in new tab or window

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#25662]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[X ] Other... Please describe: docs-infra aio
</code></pre>

## Current behavior

When I click the mary poppins doc preview link in a PR, the preview doc replaces the PR in the current window or tab. 

## Expected behavior

When I click the mary poppins doc preview link in a PR, the preview doc opens in a new window or tab (_blank), and my PR remains open in the original window or tab. 

## What is the motivation / use case for changing the behavior?

When we're reviewing documentation, it's important to see the preview and the PR side-by-side, so we can compare the preview to the conversation thread and source, mark up the source with changes we'd like to see in the output, etc. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
Yes, we can right-click to open link in new window or tab, but given that we do that almost 100% of the time, this would save us a step many times a day if it can be implemented. Thanks!

**Comment by gkalpak** [comment]
Unfortunately GitHub does not seem to allow it (neither in markdown nor with HTML links - I tried it myself and also [this SO answer][1] confirms it).

You can alwayus CTRL+Click (instead of right-clicking etc.), which adds minimal overhead.

[1]: https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank/42156438#42156438

**Comment by gkalpak** [comment]
(Or we could create a Chrome extension, that modified preview links by adding `target="_blank"` 😛)
