### ISSUE TITLE
How to pause the route change in navigationStart router event

### ISSUE THREAD

**Issue by keshav1007** [angular/angular#25679]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[x] Other... Please describe: I wanted to know how i can pause the route change in navigationStart router event
</code></pre>

## Current behavior
Once the route change starts we are unable to pause the route change in route change events like navigationStart, etc. 

## Expected behavior
There should be some method to pause and proceed in the route change events

## Minimal reproduction of the problem with instructions
redirect to any other route in navigationStart after a timeout but still the current route will be completed and then the navigation to other route will happen

## What is the motivation / use case for changing the behavior?
I have some routes exposed from node modules. I cannot do any changes to those routes hence i cannot use canActivate/canDeactivate here. So i started subscribing to router events and then based on some condition i am redirecting the user to some other page

## Environment

<pre><code>
Angular version: 5.2.8

Browser:
All browsers
 
For Tooling issues:
- Node version: 8.11.3
- Platform: All platforms

</code></pre>

**Comment by dawidgarus** [comment]
You can try navigate to current URL: `router.navigateByUrl(router.url, {  replaceUrl: true });`.
Or create special router like `/cancel-navigation` with `CanActivate` guard and navigate to it when You want to cancel navigation.

**Comment by keshav1007** [comment]
@dawidgarus sorry i am not clear. If i route the user to cancel-navigation also the current route will be completed and then the route to cancel-navigation starts right? because i have an API which will take sometime to respond and based on the response i have to redirect the user to some other page

**Comment by keshav1007** [comment]
https://stackoverflow.com/questions/52010806/how-to-pause-the-route-change-in-navigationstart-router-event - this is my question

**Comment by dawidgarus** [comment]
@keshav1007 It won't be completed if `CanActivate` guard for cancel-navigation guard will always return false. All the logic regarding whether to cancel navigation  or not will be in event handler. You would only redirect navigation to `/cancel-navigation` to do the canceling.

**Comment by keshav1007** [comment]
lets say my current route is '/a' and i clicked on '/b' now in my app.component i am subscribing to route change events and in my navigationStart i have called an API to decide whether to proceed or not. Once i get the positive response i will redirect the user to '/b' if not then i will redirect the user to '/c'. Now where do you want me to put the 'cancel-navigation'

**Comment by keshav1007** [comment]
yes that is my problem here. But i am able to achieve the same in canActivate but i couldnt use the canActivate on some exposed routes from node modules

**Comment by Twois** [comment]
#26297 this two may comes from the same problem

**Comment by Twois** [comment]
This could work as a middlewear. With a separated subscription, if we subscribe that way, we get an next function, and it wilt go forward only if we call it.

**Comment by jasonaden** [comment]
This specific functionality is not currently supported. The events fired are executed synchronously and the router ignores anything done inside them, therefore there is no way to wait for something happening as a side effect of events.

**Comment by swapnilp0x00** [comment]
```if (a instanceof NavigationStart && this.a === 0) {
        this.a = this.a + 1;
        this.router.navigateByUrl(currentActiveRoute);
      }```

**Comment by swapnilp0x00** [comment]
I needed the same behaviour in one of my project.
I found the hook for NavigationStart but didn't find anything to abort or pause the router.
So i navigated the router to currently activated route.
Angular ignores the routing if the routes are same but it prevents all Events from emitted by previous route change so giving you the effect of cancelling routing.

`ngOnInit() {
    this.router.events.subscribe((a) => {
      console.log(a);
      if (a instanceof NavigationStart && this.a === 0) {
        this.a = this.a + 1;
        this.router.navigateByUrl(this.router.url);
      }
    });
  }`
