### ISSUE TITLE
Adding support for CSS variable shimming

### ISSUE THREAD

**Issue by rkirov** [angular/angular#2567]
Polymer 1.0 has that support and is advocating using CSS variables to pierce shadow dom boundaries instead of the `/deep/` combinator. https://www.polymer-project.org/1.0/docs/devguide/styling.html

**Comment by TedSander** [comment]
Also CSS mixins would be appreciated.

Spec for CSS variables here:
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables

**Comment by matanlurey** [comment]
Could Angular also expose a Shim injectable for code that manually manipulates CSS classes?

e.g.

```js
class NgStyleLikeDirective {
  constructor(CssShim cssShim) {
    cssShim('fancy-test') // Becomes fancy-test[_ng_content_628]
  }
}
```

**Comment by vicb** [comment]
I think @matsko has plan to use CSS variables for animations. Not sure if he plan to use the code from Polymer ?

@matanlurey could you please create a separate issue for the shim things with a more detailed explanation about your use case ?

**Comment by tbosch** [comment]
This sounds reasonable. Note that we will probably still be able to do this already during compilation, as we will attach components already during compilation (https://github.com/angular/angular/issues/2529)

**Comment by agalazis** [comment]
+1 this is a must !

**Comment by vagyriag** [comment]
+1

**Comment by jelbourn** [comment]
CSS Custom Properties are now supported in all browsers that Angular supports, so this is no longer necessary.
