### ISSUE TITLE
Issue with defining route with children with outlet specified

### ISSUE THREAD

**Issue by djezzzl** [angular/angular#25673]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Having this route config:
```
{
    path: 'tabs',
    component: TabsPage,
    children: [
      {
        path: 'category',
        outlet: 'category',
        component: CategoryPage,
        children: [
           {
             path: 'create',
             component: CreateCategoryPage
           }
        ]
      }
    ]
  }
```

I can't activate the `CreateCategoryPage` component with the following link: 
`http://localhost:8100/tabs/(category:category/create)` but no **errors** or **redirects** happen.

But I can active it with the following config: 

```
{
    path: 'tabs',
    component: TabsPage,
    children: [
      {
        path: 'category',
        outlet: 'category',
        component: CategoryPage,
      },
      {
        path: 'category/create',
        outlet: 'category',
        component: CreateCategoryPage
      }
    ]
  }
```

So `http://localhost:8100/tabs/(category:category/create)` works as expected.

## Expected behavior

`http://localhost:8100/tabs/(category:category/create)` works with route defined as a child of a route with named outlet. 

## Environment

<pre><code>
Angular version: 6.1.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 61.0.2
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1
- Platform:  macOS High Sierra

Others:

</code></pre>

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
