### ISSUE TITLE
KeyValueDiffers in Angular 4+

### ISSUE THREAD

**Issue by alipup** [angular/angular#25675]
hey guys 

my question is simple .. kind of 
so i have an angular code that utilizes KeyValue class and it's written in angular version 2
and i want to replicate it with the newer version of angular.
but i get all kind of errors.
and i know about the new way of how changedetection works in the new versions of angular 
so i just want to know 
can i use the KeyValueDiffers class to detect changes on lets say a map object?? i tried and failed several times 
and thank u

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
