### ISSUE TITLE
ngcc: improve ngcc renderer tests

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#25695]
The tests are very fragile to changes to the renderer and are difficult to understand and maintain.
We should come up with a cleaner way of testing this.

**Comment by petebacondarwin** [comment]
Thanks @trotyl . You can create new issues when you find these bugs and mention me in them.

**Comment by trotyl** [comment]
@petebacondarwin Thanks, I thought it was mentioned that Ivy isn't ready for issue reports yet.

**Comment by petebacondarwin** [comment]
I hadn't heard that but I am very happy to receive reports on Ngcc!

**Comment by petebacondarwin** [comment]
Closing as this is a very low priority tidy up and unlikely to happen now.
