### ISSUE TITLE
Tour of the Heroes Angular 6 step 7 breaks app

### ISSUE THREAD

**Issue by ilanoh** [angular/angular#25691]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When launching the app on any routes, nothing appears, just blank screen however ng serve shows no error, I'm running the exact same code as the tutorial.

## Expected behavior
Should be a working tour of the heroes app until routes.

## Minimal reproduction of the problem with instructions
Just copy paste the tour of the heroes code from step 7 and run it.

## What is the motivation / use case for changing the behavior?
Having a working tutorial is nice.

## Environment

<pre><code>
Angular version: 6.1.5

Browser:
- [] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 60.0.2
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.2
- Platform:  Linux

Others:
nothing

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
