### ISSUE TITLE
feat(docs): more control over sorting of class properties and methods

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2569]
The docs on angular.io sort properties and methods in alphabetical order, which doesn't necessarily represent the ideal order in which they would be described. 

[This commit](https://github.com/angular/angular/commit/398e70ad3993741ade00b18b0241cb4b020f87fa) from @petebacondarwin introduces the alphabetical ordering, but there is no associated issue describing why alphabetical ordering was decided! (Offline convo, Pete doesn't seem to recall who thought alphabetical was best).

**Comment by jeffbcross** [comment]
I'm happy to make this change. Posting it here for discussion.

**Comment by petebacondarwin** [comment]
Works for me.
