### ISSUE TITLE
In the @angular/compiler-cli@6.1.4 hairstyle version, the exported NgTools_InternalApi_NG_2 cannot be found.

### ISSUE THREAD

**Issue by iwe7** [angular/angular#25696]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

```
// @angular/compiler-cli/index.d.ts at line 20
export { NgTools_InternalApi_NG_2 as __NGTOOLS_PRIVATE_API_2 } from './src/ngtools_api';
```

## Environment

<pre>
// file at @angular/compiler-cli@6.1.4 index.d.ts
export { NgTools_InternalApi_NG_2 as __NGTOOLS_PRIVATE_API_2 } from './src/ngtools_api';
<code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by iwe7** [comment]
has fond the same issue

**Comment by iwe7** [comment]
has fond the same issue

**Comment by Jeff-Kumar** [comment]
What is the solution for this?
