### ISSUE TITLE
Update events page so upcoming events are more prominent than past events

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#25703]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ X] Other... Please describe: AIO site
</code></pre>

## Current behavior

Events listed starting with Nov 2017 at the top. First 8 are past. 

## Expected behavior

Upcoming events are more prominent. Maybe divide page into Past and Upcoming, so all links and events are preserved but it's easier to see what's coming soon.

## Minimal reproduction of the problem with instructions

https://angular.io/events

## What is the motivation / use case for changing the behavior?

At first scan, it feels like this page is entirely out of date. It takes work by a reader to see that the bottom of the table has events that are still coming up this year. Help guide readers to become engaged in what's coming up.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by FrederikSchlemmer** [comment]
@jenniferfell I would work on this issue!

Maybe it would make sense to create two tables where the upper table still contains current events and the lower table already contains passed events?

**Comment by IgorMinar** [comment]
@jenniferfell this change will now mean that we need to keep this page updated every few weeks, otherwise it will be out of date. Is that desirable?

**Comment by jenniferfell** [comment]
Resolved
