### ISSUE TITLE
Angular 6 Header problems

### ISSUE THREAD

**Issue by mblackbourne** [angular/angular#25706]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have an issue with the headers component. I am getting a header error (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

I am using the following code :

--snippet SERVICE.ts

myFunction() { let headers: HttpHeaders = new HttpHeaders(); headers = headers.append('Access-Control-Allow-Origin: *', 'utf-8'); headers = headers.append('Accept', 'application/json'); return this._http.get('https://bittrex.com/api/v1.1/public/getmarkets') .pipe(map(result => result)); }

## Expected behavior

Under network I get a 200 GET getmarkets and retrieving the Response objects perfectly. However I am not able to get the info into my service or component.

## Minimal reproduction of the problem with instructions

Service.ts to component.ts
Comonent:: --Snippet

` ngOnInit() {
this._weather.dailyForcast()
.subscribe(res => {
console.log(res);
});

}`

I am trying to just make sure that I will be able to get my objects into my component.

## What is the motivation / use case for changing the behavior?

If a developer wants to submit a get request from an API, we either have a cors issue or an "authentication" issue. 

## Environment

<pre><code>
Angular version: 6.1.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ X ] Firefox version ESR
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3  
- Platform:  Linux 

Others:

</code></pre>

I have read solutions for building proxies to circumnavigate this issue. But I think there is a better way.

**Comment by mlc-mlapis** [comment]
@mblackbourne ... CORS is just a server-side configuration thing. You can't do a lot with it on a client side (it's hardcoded in a browser functionality), just so-called **simple requests** are the exception but `Content-Type` `application/json` is not a simple request. Look at the spec docs.

**Comment by mblackbourne** [comment]
I understand cors is client side, I am currently using these docs: 

https://angular.io/guide/http#testing-http-requests

I'm not sure exactly what I am missing. I have built this about 5 different ways (mostly from tutorials and documentation) and have ended up with the same result.

**Comment by mblackbourne** [comment]
@mlc-mlapis 

my full service:: 

`import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { map } from 'rxjs/operators';
import 'cors';

 // let headers: HttpHeaders = new HttpHeaders();
 // headers = headers.append('Access-Control-Allow-Origin: *', 'application/json');
 // headers = headers.append('access-control-allow-origin: *', 'charset=utf-8');

 const httpOptions = {
   headers: new HttpHeaders({
     'content-type': 'application/json'
   })
 };

@Injectable({
  providedIn: 'root'
})


export class WeatherService {

  constructor(private _http: HttpClient) { }

  dailyForcast() {
  /*  let headers: HttpHeaders = new HttpHeaders();
 headers = headers.append('Access-Control-Allow-Origin: *', 'utf-8');
 headers = headers.append('Accept', 'application/json'); */
    return this._http.get('https://bittrex.com/api/v1.1/public/getmarkets')
.pipe(map(result => result));

 }

}
`

**Comment by mlc-mlapis** [comment]
@mblackbourne  ... it's simply not true. This theme was mentioned maybe a hundred times ... issues / gitter channel, ... you are not really the first one who hit into.

> I understand cors is client side.

**Comment by mblackbourne** [comment]
@mlc-mlapis I am certain I am not the first. --  I mistyped my statement. I meant server side. 
I am looking for the solution. What I have above is built from the docs, and it doesn't work. I am looking for people whom have had the issue that may be able to help. Hence why I have supplied the code snippets. I am still pretty new to angular in general. There are so many HORRIBLE variations of solutions for this issue, some "require" a proxy-config, others are talking about the functions being wrong, others have suggested to have a wrapper for the call and for the logic, in order to make certain the view is not aware if the service. 

Again, I am here looking for support. Feel free to point out the gitter channel, or other docs you think may help. I have spent HOURS searching for a decent answers and have applied at least 40 variations from angualr 4-6 and suggestions from all over. If this is so "heavily documented" why does there not appear to be a solution? My code above is straight from the docs. 

` import { HttpHeaders } from '@angular/common/http';

const httpOptions = {
  headers: new HttpHeaders({
    'Content-Type':  'application/json',
    'Authorization': 'my-auth-token'
  })
}; `

**Comment by mlc-mlapis** [comment]
@mblackbourne  ... some points:

* You can't directly modify the existing headers within the previous options object because instances of the HttpHeaders class are immutable. Use the set().set().... method instead. It returns a clone of the current instance with the new changes applied. You can't use `.append()` ... more: https://angular.io/guide/http#advanced-usage

* you looking for a non-existed way. Simply you have to configure your server if your request's URL is a different combination of **hostname:port`** than the address from which you loaded your SPA app.

**Comment by manklu** [comment]
> There are so many HORRIBLE variations of solutions for this issue ...

Wrong. For CORS Issues there exist only one solution: Configure your server correctly to allow cross origin requests.

It's completely independent of the client framework you use or it's version. Even with plain JS you would have the same problems.

**Comment by mblackbourne** [comment]
So our findings indicate that we will need need to pass authentication or will need to configure the server to allow cross origin. 

Thank you
