### ISSUE TITLE
More than one component matched on this element error thrown when using Hot Module Reloading

### ISSUE THREAD

**Issue by dkapellusch** [angular/angular#25709]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When I edit a component being used as part of another component, which is also registered with the router I get the error 
<pre><code>
"VM1743 vendor.js:160908 [HMR] Error: Template parse errors:
More than one component matched on this element.
Make sure that only one component's selector can match a given element.
Conflicting components: ReusableComponent,ReusableComponent" 
</code></pre>
which prompts a full refresh.

## Expected behavior
The component reloads using HMR not with a full reload

## Minimal reproduction of the problem with instructions
A minimal repo which repoduces the problem can be found here: https://github.com/dkapellusch/AngularRepro

## Environment

Angular version: 6.1.0

Browser:
- [x] Chrome (desktop) Version 68.0.3440.106 (Official Build) (64-bit)

 
For Tooling issues:
- Node version: v9.3.0
- Platform:  Windows

**Comment by trotyl** [comment]
Please report 3rd-party library usage problem to [their repo](https://github.com/gdi2290/angular-hmr). This is the Angular repo.
