### ISSUE TITLE
Combination of deeply nested formGroupName/formArrayName

### ISSUE THREAD

**Issue by tsamsiyu** [angular/angular#25705]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

### Feature request is to provide possibility to write complex values for formGroupName and formArrayName because in some cases the absence of this make us add many extra div-s that can break html\css. Example see below.

I'll show structure of my form data by defining short typings:

```
type Rule = {}
type Field = { rules: Rule[] } 
type Subcategory = { fields: FIeld[] }
type Category = { subcategories: Subcategory[] }
```
Category presents my form data structure

And I expect to have html something like this:

```
<div formGroupName="category">
    <div formArrayName="subcategories" class="my-column">
         <!-- Here I have to add extra div for ngFor because formArrayName and formControlName can't be placed together with formGroupName  =\ -->
         <div *ngFor="let subcategory of form.controls.subcategories.controls; let i = index" [formGroupName]="i">
            <input type="text" name="name" formControlName="name" />
         </div>
    </div>
    <!-- Here I need [formArrayName]="'subcategories[' + selectedSubcategoryIndex + '].fields'" but it's impossible =\ -->
    <div formArrayName="fields" class="my-column">
         <div *ngFor="let field of selectedSubcategory.controls.fields.controls; let i = index" [formGroupName]="i">
              <input type="text" name="name" formControlName="name" />
         </div>
    </div>
    <!-- Here I need [formArrayName]="'subcategories[' + selectedSubcategoryIndex + '].fields[' + selectedFieldIndex + '].rules'" but it's of course impossible too =\ -->
    <div formArrayName="rules" class="my-column">
         <div *ngFor="let rule of selectedField.controls.rules.controls; let i = index" [formGroupName]="i">
              <input type="text" name="name" formControlName="name" />
         </div>
    </div>
</div>
```
To user it should be 3 columns for subcategories, fields, rules. When user selects subcategory/field - application displays corresponding to it fields/rules.

Currently to handle this case I need to put many extra div-s for each of formGroupName and formArrayName directives into second and third columns, but it seems awful.

**Comment by kara** [comment]
@tsamsiyu You should be able to use `ng-container` for any places where you'd like to avoid adding extra elements to the DOM. You can find the documentation [here](https://angular.io/guide/structural-directives#ng-container-to-the-rescue).
