### ISSUE TITLE
fix(test): Test errors aren't being propagated in gulp test.unit.js (possibly other tasks)

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2570]
See this job for example: https://travis-ci.org/angular/angular/jobs/67065781

If I debug the code, I see the actual error being caught and re-thrown through `InstantiationError` is "Cannot read property 'fromArray' of undefined", an error I immediately know how to fix.

I tinkered with it, and it looks like the problem is when calling `super()` in subclass of BaseException without a message, any message that would be added after calling `super` gets lost. If I pass an arbitrary string to super here: https://github.com/angular/angular/blob/master/modules/angular2/src/di/exceptions.ts#L40 then a better message is displayed. This may be an issue in the underlying engine, and seems related to https://github.com/Microsoft/TypeScript/issues/1168

CC: @alexeagle who has looked at this TS issue before.

**Comment by vicb** [comment]
Could this help ? https://github.com/angular/angular/pull/2102 (not sure if it has been merged and if not why).

:+1: for fixing this, very annoying

**Comment by jeffbcross** [comment]
The version of TypeScript we're using is @alexeagle's fork which declares `Error` as a class, which should be supported according to Microsoft/TypeScript#1168. Though in that issue, others have issues with extending the class.

**Comment by jeffbcross** [comment]
One potential fix is to require that every subclass of `Error` be constructed with an already-formatted message, instead of allowing construction of the message inside the constructor after `super()`.

**Comment by jeffbcross** [comment]
I opened a PR with a unit test for JS. https://github.com/angular/angular/pull/2580

I just call super with the same logic from further down in the constructor where the initial message is generated. This approach may be flawed, in that if the provided function would ever output an empty string (or undefined), the eventual message may still not be logged.

**Comment by jeffbcross** [comment]
Closing PR in favor of #2606
