### ISSUE TITLE
Moving away from the Buffer constructor

### ISSUE THREAD

**Issue by gabrielschulhof** [angular/angular#25707]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
`new Buffer(...)` is deprecated and unsafe. It is used in [one location](https://github.com/angular/angular/search?q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22). Would it be possible to replace that instance with `Buffer.from(...)`?

## Expected behavior

`Buffer.from(...)` used everywhere.

## What is the motivation / use case for changing the behavior?

Deprecation of the `Buffer` constructor.

## Environment
Node.js
<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
The good news is that it's just a spec file so it's not being shipped outside of this repository.
Still a very easy fix though.

**Comment by robwormald** [comment]
Fixed in #25805
