### ISSUE TITLE
TemplateRef for ngModel doesn't work when nested in *ngIf

### ISSUE THREAD

**Issue by klinki** [angular/angular#25700]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Accessing `ngModel` using templateRef doesn't work when it is inside `*ngIf` statement. 

## Expected behavior

It should work.

## Minimal reproduction of the problem with instructions
```html
  <ng-container *ngIf="true">
    <mat-form-field>
      <mat-select [(ngModel)]="selectedValue" placeholder="Select value" #selectElBroken="ngModel">
        <mat-option *ngFor="let item of [1,2,3]" [value]="item">{{item}}</mat-option>
      </mat-select>
    </mat-form-field>
  </ng-container>

  {{selectElBroken?.dirty}}
```

`selectElBroken` will be `undefined`

https://stackblitz.com/edit/angular-rr54wp-template-form-bug

## What is the motivation / use case for changing the behavior?

I need to get state of template-driven form field which is inside `*ngIf`. 

## Environment

<pre><code>
Angular version: 6.1.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

I'm pretty sure it is related to https://github.com/angular/angular/issues/8563

**Comment by pkozlowski-opensource** [comment]
Local vars (like `#selectElBroken="ngModel"`) are scoped to a view (`<ng-template>` boundary in your case). You can _not_ access inner vars from the outter view. What you are trying to do would be equivalent, in JS, to:

```
function outter() {
  function inner() {
    let selectElBroken = ...;
  }
  // trying to access selectElBroken here won't work
}

We need to have _some_ rules for templates and keeping it in sync with JS function scoping is our guiding principle.

Closing as it works as designed.

**Comment by klinki** [comment]
Ok, thanks for the explanation. If I understand it correctly, it is impossible to achieve what I described?

If I use your example with function scoping, would it be possible to use some `outer` function variable to save the inner state?

something like
```javascript
function outer() {
    let selectElBroken = null;

   function inner() {
          selectElBroken = ...;
   }
}
```
In language of angular templates, something like

```html
<input type="hidden" [(ngModel)]="selectedValue" #selectElBroken="ngModel" />
 <ng-container *ngIf="true">
    <mat-form-field>
      <mat-select [(ngModel)]="selectedValue" placeholder="Select value" #selectElBroken="ngModel">
        <mat-option *ngFor="let item of [1,2,3]" [value]="item">{{item}}</mat-option>
      </mat-select>
    </mat-form-field>
  </ng-container>

  {{selectElBroken?.dirty}}
```

**Comment by klinki** [comment]
@pkozlowski-opensource Is there any workaround how to avoid this limitation?
