### ISSUE TITLE
Can not deliver @ContentChild from parent to child

### ISSUE THREAD

**Issue by wenqi73** [angular/angular#25719]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[x] Other... Please describe:
</code></pre>

## Current behavior

I have two components, now I want to input a template as parent's content, the child component also has a `@ContentChild`, but I can't get the `childTemplate` in child component in this case.

**app.component.html**
```html
<app-parent>
  <ng-template #childTemplate>
     how to display this template
  </ng-template>
</app-parent>
```
**parent.component.ts**
```ts
@ContentChild('childTemplate') childTemplate: TemplateRef<{}>
```

**parent.component.html**
```html
<app-child>
  <!-- <ng-template #childTemplate>
    this can work, but I need to input the template in app-parent content
  </ng-template> -->
  <ng-container [ngTemplateOutlet]="childTemplate"></ng-container>
</app-child>
```

**child.component.html**
```html
<ng-container [ngTemplateOutlet]="childTemplate"></ng-container>
```

## Expected behavior

Can deliver `<ng-template>` to child component.

## Minimal reproduction of the problem with instructions

[https://stackblitz.com/edit/insert-template-to-child-component](https://stackblitz.com/edit/insert-template-to-child-component)

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
You need to explicitly pass it as `@Input`: https://stackblitz.com/edit/insert-template-to-child-component-rjw1h3?file=src/app/parent/parent.component.ts

Anyway, this is a support request and as such doesn't belong here: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Comment by wenqi73** [comment]
Thanks, I feel sorry for this.
