### ISSUE TITLE
Angular directive to disable for non-form elements i.e div , h1 , h2  

### ISSUE THREAD

**Issue by imabdullahkhan** [angular/angular#25716]
is there any built-in angular directive to conditional disable  for non-form elements like for custom component , p-tag, div. just same as [disable] directive for forms elements like input button e.t.c.
for example in my case i have 
`<div (click)="something()">edit</div> `
this div click event only works  when certain condition meet . I  can achieve this with using*ngIf like 
`<div *ngif="condtion===true" (click)="something()">edit</div>`
`<div *ngif="condtion===false" >edit</div>`
or 
`function something(){
if(!condtion){
return;
}
//something
}`  or
` <button [disabled] = "!condtion">edit</button>`
 but i want to use div or any other tag like p-tag h1 e.t.c

There should be angular built-in directive for non-form elements  which behaves same as  angular build-in directive [disabled] works. 
like 
`<div [disabled]="!condtion" (click)="something()"> </div>`

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ - ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by phl3x0r** [comment]
how would 'disabled' work for elements that do not have a native specification for it?
I bet this is not something that's going to be implemented by the ng team, but you could easily make a directive with the desired behaviour yourself and even publish it to npm if you feel it could be useful for others too.

**Comment by robwormald** [comment]
`<input [disabled]="someCondition">` isn't a directive - its using the native `.disabled` property on the element - if the DOM element doesn't expose such a property/attribute, there will be no effect. As we're not special casing input/button etc, we can't special case anything else :)
