### ISSUE TITLE
Angular BUG  [solution: <base href="/">]

### ISSUE THREAD

**Issue by renatoprogramer** [angular/angular#25714]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

My routes with parameters does not work is a simple URL with an ID for a detail page, I followed the whole document and nothing works I searched the internet and nothing would like to report this BUG or this poorly written code, is a shame a market framework of that have Problems as simple as this can be wrong more is what it seems after days trying to solve it! 

## Expected behavior

I would like it to work a simple URL ex: HTTP://localhost:4200/evnt-detail/1

## Environment

<pre><code>
Angular version: 6.1.4

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1  
- Platform:   Windows 

Others:

</code></pre>

**Comment by sarunint** [comment]
It's useless to open multiple issues on the same question. This is definitely not abug. I'll say this again. **The issue tracker is not suitable for support questions, please use StackOverflow or Gitter for that.** 

_More hint:  https://angular.io/guide/router#base-href_

**Comment by renatoprogramer** [comment]
@sarunint  Thank you!

**Comment by sarunint** [comment]
@renatoprogramer Could you please close all of your issues?

**Comment by pkozlowski-opensource** [comment]
Closing based on https://github.com/angular/angular/issues/25714#issuecomment-416810211
