### ISSUE TITLE
BUG - ROUTE PARAMETER    [Solution: <base href="/">]

### ISSUE THREAD

**Issue by renatoprogramer** [angular/angular#25712]
I am trying to time make a simple route with the angular and pass parameters and nothing can anyone help me 

![screenshot_5](https://user-images.githubusercontent.com/15394508/44756622-cd26f700-ab01-11e8-9d32-9752b30e46ba.jpg)

![screenshot_3](https://user-images.githubusercontent.com/15394508/44756627-d0ba7e00-ab01-11e8-843e-ff3c48e1a24f.jpg)

![screenshot_2](https://user-images.githubusercontent.com/15394508/44756632-d3b56e80-ab01-11e8-92e8-0e9414f9a00a.jpg)

**Error in console**
![screenshot_1](https://user-images.githubusercontent.com/15394508/44756652-f182d380-ab01-11e8-950d-c55e0840c273.jpg)

![screenshot_4](https://user-images.githubusercontent.com/15394508/44756730-39095f80-ab02-11e8-91d5-193c43d3c4a7.jpg)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular/angular/issues/25714#issuecomment-416810211
