### ISSUE TITLE
Unable to find property when first listed property in component has @Input

### ISSUE THREAD

**Issue by StephenMiracle** [angular/angular#25728]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Angular does not recognize a component property when the first property is decorated with @Input() . I can have a list of 3 properties (making these up): 
@Input() name:string 
description: string
@Input() role:string

Angular will not recognize the name property above since it is first with the input decorator. On the other hand, it will be fine if I switch it with the description property. I haven't tested it with other decorators but have come across this issue at least on 3 separate occasions.

## Expected behavior

I should be able to have an @Input() property be listed first as the first property.

## Minimal reproduction of the problem with instructions
1. create a component
2. add a property "name" immediately following the line of the component class name.
3. add the @Input() decorator to the beginning of name
4. Try to reference the property in the view file.
5. see the error in the console

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
Can't reproduce: https://stackblitz.com/edit/angular-vohyan?file=src%2Fapp%2Fapp.component.ts

We need a minimal reproduce scenario or it is not actionable and will be closed.

**Comment by StephenMiracle** [comment]
Feel free to close if can't be reproduced and I can't do it on StackBlitz nor have the time to try and reproduce on my own. I just know that I've come across this situation on a few cases where I was pulling my hair out until I flipped the first property when it was decorated with @Input() . There may be something else that I'm missing in the issue. But may be something to keep an eye on. 

Thanks!

**Comment by pkozlowski-opensource** [comment]
@StephenMiracle I suspect that something else it at play here so next time you hit it please try to isolate it a bit more...
