### ISSUE TITLE
No Angular v6.1.5 on NPM

### ISSUE THREAD

**Issue by sarunint** [angular/angular#25720]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[x] Other... Please describe: release request
</code></pre>

## Current behavior

Tag v6.1.5 is published in the repo, but no releases have been made on NPM yet.

## Expected behavior

Release v6.1.5 on NPM.

## Minimal reproduction of the problem with instructions

N/A

## What is the motivation / use case for changing the behavior?

N/A

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
> Release v6.1.5 on NPM.

Sure, still fiddling with the internal build bits. We will push it as soon as it is sorted out.
