### ISSUE TITLE
router navigate not working inside ngOnInit

### ISSUE THREAD

**Issue by Jeanclaudeaoun** [angular/angular#25737]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

when i am calling router.navigate(['/login']) inside ngOnInit, it isnt working! it is not loading the page, instead i am getting a blank page but the url is changing!

## Expected behavior

I expect to make the home page secure, if the user is not logged in, i want to navigate back to the login page.

## Minimal reproduction of the problem with instructions
home.page.ts:
```
ngOnInit(){
  if( !this.authenticationService.isUserLoggedIn() ){
    this.router.navigate(['/login']);
  }
}
```
the only workaround was to put ' this.router.navigate(['/login']); ' inside a setTimeout() but it isn't clean code and doesn't always work!

I am using lazy loading of modules:
```
const routes: Routes = [
  {
    path: '',
    redirectTo: 'login',
    pathMatch: 'full'
  },
  {
    path: 'login',
    loadChildren: './login/login.module#LoginPageModule'
  },
  {
    path: 'home',
    loadChildren: './home/home.module#HomePageModule'
  }
];
```
## Environment

<pre><code>
Angular version: 6.0.8

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.6.0
- Platform: Mac

Others:

</code></pre>

**Comment by manklu** [comment]
https://angular.io/guide/router
