### ISSUE TITLE
Angular 6 Zone constantly runs functions passing values to Child from Parent

### ISSUE THREAD

**Issue by knnhcn** [angular/angular#25730]
## I'm submitting a...
<pre><code>
[ ] Regression (a behaviour that used to work and stopped working in a new release)
[ ] Bug report 
[x] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Angular runs all functions in component passing values to Child component again on trigger of single function. On functions which are manipulating DOM, this causes to constant DOM update, unintentionally.

## Expected behavior

Only specific triggered area should be invoked, instead all together are invoked at the same time constantly --> decreasing Performance, freezing until code is done.

## Minimal reproduction of the problem with instructions
In following GitHub repo is a minimal reproduction of the issue. Click on a cell to see all functions in component invoked again.

[https://github.com/knnhcn/Angular6ZoneJsTest](https://github.com/knnhcn/Angular6ZoneJsTest)
## What is the motivation / use case for changing the behavior?
Better overall performance.

## Environment
<pre><code>
Angular version: 6.0.8
dev env (also in production, ng build --prod)

Browser:
- [x] Chrome (desktop) version 68
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.9.0  
- Platform:  Mac, 10.13.6

Others:

</code></pre>

**Comment by splincode** [comment]
This question applies to stackblitz.

Note: you should not usage function in template, you can usage pure pipe or caching value (not function) in template..or set zone 'noop' and manual call detectChanges

**Comment by IgorMinar** [comment]
By default the change detection algorithm checks all the bindings in the application when a new input to the system is detected. You can improve this upon this via the onpush change detection strategy.

https://angular.io/api/core/ChangeDetectionStrategy
https://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html
