### ISSUE TITLE
HTTP Client for Angular 5 has a difference in headers in different browsers

### ISSUE THREAD

**Issue by muzzammilhussain** [angular/angular#25746]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
HTTP Client for Angular 5 has a difference in headers in different browsers

## Expected behavior
Headers must remain the same.

## Minimal reproduction of the problem with instructions

If you want to capture the origin you cannot do that in Angular 5 Prod as header changes to Referer instead of Origin.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [x ] Chrome (Android) version XX
- [x ] Chrome (iOS) version XX
- [ x] Firefox version XX
- [x ] Safari (desktop) version XX
- [ x] Safari (iOS) version XX
- [ x] IE version XX
- [ x] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by manklu** [comment]
AFAIK the referer and origin header are added by the browser.

**Comment by muzzammilhussain** [comment]
How to control headers? We need that always the origin header is added to request

**Comment by pkozlowski-opensource** [comment]
`origin` header is added by a browser and it is not something that you, or Angular, can control:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin
https://stackoverflow.com/q/46808011/1418796

Closing as a support request.
