### ISSUE TITLE
Animations: elements with leave transitions never cleanup causing memory leaks

### ISSUE THREAD

**Issue by alexhobbs** [angular/angular#25744]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>
 
## Current behavior
When a component has a :leave transition the DOM Element reference is never removed from TransitionAnimationEngine.statesByElement map causing detached DOM nodes and out-of-memory crashes.
 
Debugging seems to show that the "hasAnimation" flag is preventing cleanup functions being run (see [_flushAnimations](https://github.com/angular/angular/blob/dd2a650c3455f3bc0a88f8181758a84aacb25fea/packages/animations/browser/src/render/transition_animation_engine.ts#L1204)). Elements never re-enter this function and therefore `removeNodesAfterAnimationDone` or `processLeaveNode` are not triggered.
 
 
## Expected behavior
TransitionAnimationEngine should successfully clean up elements that have left the page.
 
 
## Minimal reproduction of the problem with instructions
1. Create ListItemComponent which has a simple :leave transition in the @Component decorator
2. Include this component with an *ngIf toggle attached to a button in the main AppComponent to trigger the :leave animation
3. Watch detached DOM nodes grow and TransitionAnimationEngine.statesByElement grow
 
## What is the motivation / use case for changing the behavior?
Currently this memory leak is causing performance issues and crashes on dashboard monitor type applications which run for a long time with no user input. Over the cause of a day `statesByElement` has grown from 0 elements to 10,000.
 
 
## Environment
 
<pre><code>
Angular version: 6.1.4

 
Browser:
- [x] Chrome (desktop) version 68
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by babeal** [comment]
@alexhobbs we are running into the same issue.  What did you do to fix it in the mean time?  Pure css animations?

**Comment by AlexNarkevich** [comment]
![image](https://user-images.githubusercontent.com/48122065/53631015-8934bc00-3c22-11e9-906a-62ac363612db.png)
we have the issue as well.

**Comment by alexhobbs** [comment]
@babeal - yes where possible we’ve had to replace with CSS or disable the animation entirely.

**Comment by jpduckwo** [comment]
Hi, we are having issues with angular material because of this bug. Specifically MatFormField inside MatDialog.

**Comment by jpduckwo** [comment]
@matsko have you got any ideas on how to approach fixing this one? I'm willing to do the work if there is a direction to take. At worst opening up some way to call a clean up on TransitionAnimationEngine.statesByElement.

**Comment by denisyilmaz** [comment]
this problem still persists in safari 13.0.4

**Comment by Splaktar** [comment]
@denisyilmaz using `9.0.0-rc.7` or newer? If you have a reproduction, please open an issue and link to this one.

**Comment by denisyilmaz** [comment]
`9.0.0-rc.7` yes. I will try to create a reproduction asap.
