### ISSUE TITLE
Angular Giving error on clicking on the page.

### ISSUE THREAD

**Issue by Jithinqw** [angular/angular#25743]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Angular gives me this error on clicking the on the page. Which does not have any functions in onPage Click.
Uncaught TypeError: Cannot read property 'recordClickType' of undefined
    at HTMLDocument.onClick (content_script.js:14843)
onClick @ content_script.js:14843

## Expected behavior

This should not give any errors or warnings.

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [* ] Chrome (desktop) version 66.0.3359
 
For Tooling issues:
- Node version: 8.11.3
- Platform:  Linux

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by thonymg** [comment]
i have the same issue on Chrome (only)
