### ISSUE TITLE
Feature Request: platform-agnostic Observable creation method (comparable to fromEvent)

### ISSUE THREAD

**Issue by christianliebel** [angular/angular#25741]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The `fromEvent` method of rxjs allows developers to easily register (and unregister) for DOM events which the library maps to an observable. This behavior is helpful but depends on the DOM as a rendering platform.

## Expected behavior

Angular heavily relies on rxjs; thus it would be helpful to consider providing an observable creation method comparable to `fromEvent` which adds/removes event listeners via the renderer.

**Proposal:**
```ts
fromRendererEvent(this.renderer, this.myOtherElementRef.nativeElement, 'click').subscribe(clickEvent => /* do something with it */)
```

If this helper method could get rid of passing in the renderer, it would be even better:

```ts
fromRendererEvent(this.myOtherElementRef.nativeElement, 'click').subscribe(clickEvent => /* do something with it */)
```

This way, the developer can create an event observable in a platform-agnostic manner, whereas the creation method takes care of using the actual platform-specific method via the renderer. A basic implementation of this method can be found in the demo below. I posted this feature request _here_, as:
- Angular could (in some way) resolve the renderer, so the developer doesn’t have to pass it in
- It’s relatively easy to implement
- rxjs’s `fromEvent` does support Node/jQuery-style emitters, but the library shouldn’t need to have a dependency on Angular (which, in turn, Angular already has on rxjs)

Sure, this feature could also be provided as a separate npm module. But as we have many observable helper methods for tests/async pipe/etc., I thought this could be worth a discussion here. What do you think?

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-fromrendererevent

## What is the motivation / use case for changing the behavior?

Better developer experience.

**Comment by mhevery** [comment]
Will not implement.
