### ISSUE TITLE
ANGULAR 6 Installation Problem

### ISSUE THREAD

**Issue by gurumalli** [angular/angular#25742]
![capture](https://user-images.githubusercontent.com/38082329/44842693-2d35ae80-ac64-11e8-9632-0e616a3103c7.PNG)
newTree.optimize is not a function

I found RXJS error while I was installing Angular 6.

I tried by executing  beow command
npm install --save rxjs-compat
and then added following line to polyfill.ts

(window as any).global = window;

Could you please help me with the same.

Regards',
Guru Malli.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by gkalpak** [comment]
To add to what @ericmartinezr said, there seems to have been an error during the global `@angular/cli` installation. I would try to uninstall and re-install `@angular/cli`.

(If you think this is an `@angular/cli` bug, please report and issue on their tracker: https://github.com/angular/angular-cli/issues)
