### ISSUE TITLE
App Module not loading in Feature Module

### ISSUE THREAD

**Issue by 1118187** [angular/angular#25745]
Does App Module Components/Modules get loaded when we are on a particular Feature Module.
If I import Forms Module in App Module and use Form Components like ngModel in feature module , then I should be able to use it ..right? because I have already imported it in App Module. But it not loading and instead throwing an error. 
An when I import it in Feature Module . Its working fine.
Any idea why its not working in the former case?

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
