### ISSUE TITLE
collection issue: improve search 

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#25753]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ X] Other... Please describe: AIO infrastructure and runtime
</code></pre>

## Current behavior

This issue links to a variety of issues related to search behavior

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
Links and groups as of today:

**correct and complete results**

- search doesn't match on phrases with punctuation in search keyword #23652
- AIO search matches on pages that don't contain the search keyword #25156 (and enable literal search for phrases)
- improve search index for animations package #24700
- add inherited members as key terms for search #23800

**recognizing results**

- provide more cues for deprecated APIs #24380
- Highlight search results in page #23655

**reduce steps to execute a search**

- Enable tab to search from browser address bar #24107
- ux problem with interaction of site search field and browser search field #20428

**Comment by jenniferfell** [comment]
Allowing for literal expressions in quotation marks would be one step to alleviating #23652 and #25156

**Comment by jenniferfell** [comment]
@IgorMinar I transferred the consolidation I presented yesterday into this issue, per your suggestion to open an issue and work on the set as a single design/effort.

**Comment by petebacondarwin** [comment]
Setting this to P5 as improving the search would be a significant effort and most people have not complained about it.
