### ISSUE TITLE
embedding PDF docs inside angular component in IE

### ISSUE THREAD

**Issue by tnvpandian** [angular/angular#25758]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
We are working on a component which will get PDF as byte array from backend , store it in a Blob and embed the object using Blob URL with in the HTML template. This works fine in chrome. However, in IE & Edge , it is not rendering the blob. IE does not support embedding blobs and we needed to use navigator.msSaveBlob if the browser is IE. 

## Expected behavior

We would expect same behaviour across browsers ( including IE as well).

## Environment

<pre><code>
Angular version: 6.0.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ X] IE version 11
- [ X] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@tnvpandian ... and you think that this something for which Angular is responsible?

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
