### ISSUE TITLE
Making service call from developement server 

### ISSUE THREAD

**Issue by harshamotwani22** [angular/angular#25766]
I'm using express server for production and making a startup call before serving the static files and saving that data to js file before serving.
I need to do the same for angular developement server.
So can we make a service call using developement server way before html loads and save that data.
Any idea how to approach this problem?

Angular Version-6.0.0
Angualar CLI-6.1.4
Prod Server- express

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
