### ISSUE TITLE
using an http hit with bootstrap type-ahead

### ISSUE THREAD

**Issue by Bridgeway** [angular/angular#25769]
Error: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.

I'm getting the above error when my code hits the following in my component:

search = (text$: Observable<string>) =>
    text$.pipe(
      debounceTime(200),
      distinctUntilChanged(),
      map(term => term.length < 2 ? []       
        : this.engageService.search(term).subscribe(emps => emps.filter(e => e.employeeNames))) 
    );

(where this.engageService.search is calling an http get via a service)

The ngb template code is NgbTypeaheadWindow.html :

<ng-template #rt let-result="result" let-term="term" let-formatter="formatter">
      <ngb-highlight [result]="formatter(result)" [term]="term"></ngb-highlight>
    </ng-template>
    <ng-template ngFor [ngForOf]="results" let-result let-idx="index">
      <button type="button" class="dropdown-item" role="option"
        [id]="id + '-' + idx"
        [class.active]="idx === activeIdx"
        (mouseenter)="markActive(idx)"
        (click)="select(result)">
          <ng-template [ngTemplateOutlet]="resultTemplate || rt"
          [ngTemplateOutletContext]="{result: result, term: term, formatter: formatter}"></ng-template>
      </button>
    </ng-template>

How can I modify my code to get it to work as the only other way I've found so far is sticking the api call in a loop which goes through the alphabet 26 times and loads the results into an array, that array then has for some reason loads of duplicates and 26 api hits to the same endpoint when my component loads is absurd.

**Comment by pkozlowski-opensource** [comment]
You need to return an _array_ not an _object_ from your observable.

---

We reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
