### ISSUE TITLE
Email Validator with single letter domain extension

### ISSUE THREAD

**Issue by martibenj** [angular/angular#25763]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When the Email Validator process the string 'aaa@aaa.a', it consider it as valid

## Expected behavior
Single letter extension aren't used, it should be considered as invalid

## Minimal reproduction of the problem with instructions
Check console prints in https://stackblitz.com/edit/angular-gitter-wqtwff

## What is the motivation / use case for changing the behavior?
Single letter extension aren't used

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x] Chrome (desktop) version 68.0.3440.106
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:
- Node version: v8.11.2
- Platform:  Windows

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@martibenj ... the validator is based on the spec. You have to understand that email address is a bit more general thing than just your personal email address on gmail.com, for example. Inside private networks, you can use such addresses and they are still by the spec. Create your custom validator which wraps the built-in one to extended the checking.

**Comment by pkozlowski-opensource** [comment]
@mlc-mlapis answer is spot-on here
