### ISSUE TITLE
关于在懒加载模块中引入公用模块时，如果公用模块中导出一个组件，在2个不同的懒加载的模块中使用会报错，Type InputComponent is part of the declarations of 2 modules:。。

### ISSUE THREAD

**Issue by jiagouview** [angular/angular#25787]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by alissonbovenzo** [comment]
u're declared this component "InputComponent" 2 times, u only need remove at one

**Comment by jiagouview** [comment]
我没有声明这个组件2次，我仅仅在公用模块中声明了这个组件，然后分别在2个独立的懒加载模块中引入了公用模块。然后就出现了这个错误。 @alissonbovenzo

**Comment by wynfred** [comment]
please at least change the title:
when importing shared module in a lazy loading feature module, if a component is exported in the shared module, error occurs when more than one lazy modules import the shared module

I didn't try to reproduce it though. just provide a translation. i'm using shared modules and lazy loading modules together without any problem

**Comment by IgorMinar** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a plunker reproducing the problem and describing the difference between the expected and current behavior. You can use this plunker template: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by jiagouview** [comment]
谢谢，我用了moduleWithProvider方法，并重新检查了一下代码，发现我很久之前在一个懒加载模块中引入了这个公用组件，导致报错，删除以后正常了。
