### ISSUE TITLE
Tutorial Pages: Step 3: Master/Details Component is broken

### ISSUE THREAD

**Issue by chintupawan** [angular/angular#25786]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

URL: https://angular.io/tutorial/toh-pt3
Tutorial Pages: Step 3: Master/Details Component is broken. 
Error in console: main.bd0d03debaa66852c02f.bundle.js:1 ERROR Error: [DocViewer] Error preparing document 'tutorial/toh-pt3': Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node

## Expected behavior

Page should render

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [X] Chrome (desktop) version  68.0.3440.106 
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ashishpatelcs** [comment]
This is no longer an issue. I believe this issue is closed.

**Comment by IgorMinar** [comment]
@ashishpatelcs thanks

**Comment by chintupawan** [comment]
Has it been released yet. I still see blank screen. I have tried in multiple browsers.
video link [https://drive.google.com/file/d/1lzX3Qt6xyVICtbpteKHNfL6Vly-JdrPD/view](url)

**Comment by chintupawan** [comment]
@trotyl  instead of downvoting please leave a message so that I can understand the reason and rectify it.

**Comment by sarunint** [comment]
@chintupawan please try in Incognito mode
