### ISSUE TITLE
SetInterval will be suspended, when I touchmove

### ISSUE THREAD

**Issue by zhantewei2** [angular/angular#25790]
### app.html
```html

  <div style="overflow:auto;" [style.height]="work?'200px':'600px'">
		  <div style="height:800px;"></div>
 </div>
 <div 
  style="position:fixed;background:rgba(0,0,0,0.2);height:100%;width:100%;top:0;left:0;display:flex;justify- 
 content: center;align-items: center"
>
      <div 
         style="background:white;width:200px;height:200px"
         id="test-content">
		    <button [class.work]="work" (click)="work=true">work</button>
		    <button [class.work]="!work" (click)="work=false">not work</button>
		    <p>{{count}}</p>
      </div>
   </div>


```

### app.ts
```js
@Component({
  selector: 'app-root',
  templateUrl:'./app.html',
  styles:['.work{background:red}']
})
export class AppComponent {
  work:boolean;
  count:number=0;
  constructor(){

  }
  ngOnInit(){
    const test=document.getElementById('test-content');
    
    let i;
    test.addEventListener('touchstart',()=>{
      i=setInterval(()=>{
        console.log('run');
        this.count++;
      },100);
    });
    test.addEventListener('touchend',()=>{
      clearInterval(i);
    })
  }
}

```

## Current behavior
As I touchmove on the  `test-content` element,the `setInterval event` will be suspended!

I tried to use `zone.runOutsideAngular` and I get same result.

But these code works well in the pure JS.
....

 I have one more question
---
`(window as any).__zone_symbol__BLACK_LISTED_EVENTS = ['scroll', 'mousemove'];`

It's useless ,still trigger `ngDoCheck`

## Environment

<pre><code>
Angular version: 6.1.0 && 6.0.1

Browser:
- [ ] Chrome (desktop) version 68.0.3440.106

 
For Tooling issues:
- Node version: 10.1.0

Others:

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
