### ISSUE TITLE
Ability to dynamically lazy load modules

### ISSUE THREAD

**Issue by lincanli** [angular/angular#25798]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[x] Support request(might be)
[ ] Other... Please describe:
</code></pre>

## What is feature?

Some times we want to have different module (not component), with its own routing tree on same parent route.

For example http://example.com/home we might render with different module according to user's account type. and redirect to another url might not be acceptable in business logic.

It's nice if we can have this kind of feature.

Current ViewContainerRef, ResolveComponentFactory, NgmoduleFactoryLoader can only inject component into parent view, but not module with routing tree.

## Environment
<pre><code>
Angular version: X.Y.Z

Angular CLI: 6.0.8
Node: 8.9.4
OS: darwin x64
Angular: 6.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package Version
@angular-devkit/architect 0.6.8
@angular-devkit/build-angular 0.6.8
@angular-devkit/build-optimizer 0.6.8
@angular-devkit/core 0.6.8
@angular-devkit/schematics 0.6.8
@angular/cdk 6.4.3
@angular/cli 6.0.8
@ngtools/webpack 6.0.8
@schematics/angular 0.6.8
@schematics/update 0.6.8
rxjs 6.2.2
typescript 2.7.2
webpack 4.8.3

**Comment by steveblue** [comment]
@lincanli dynamic lazy loading is possible, probably not out of the box however with `@angular/cli`. In order for it to work you need to resolve the configuration prior to bootstrap using `APP_INITIALIZER` and reset the RouteConfig based on the user's account type. As long as the modules are AOT compiled, you can point the route's loadChildren property to the reference of the `NgModuleFactory`.

**Comment by lincanli** [comment]
@steveblue thanks!

**Comment by lincanli** [comment]
for anyone who need more information how to implement it, this is how i did it:

app-loading.service
```
export function init_app(appLoadService: AppLoadService) {
    return () => appLoadService.initializeApp();
}

@Injectable()
export class AppLoadService {

    constructor(private injector: Injector) {
    }

    initializeApp(): Promise<any> {
        const router = this.injector.get(Router);

        return new Promise((resolve, reject) => {
            console.log(`initializeApp:: inside promise`);

            let idx = router.config.findIndex(r => r.path == ':slug');
            router.config[idx].children[0].loadChildren = '../modules/@maple/topping/template.module#TemplateModule';

            resolve();

        });
    }
}
```

app.module
```
providers: [
        AppLoadService,
        {provide: APP_INITIALIZER, useFactory: init_app, deps: [AppLoadService], multi: true},
]
```

**Comment by developer239** [comment]
@lincanli 🤔can you please share an example how would you use your code in a real application. I am new to angular so I am probably missing something.

What I need to do:
- I have `auth`, `core`, `events`, `flash` modules
- `events` module is lazy loaded
- in one route of `auth` module (on profile page), I want to use `ngrx` store to select events for logged in user. this doesn't work because `events` module is loaded only when I go to `/events` route

Is is possible to:
- load module under certain routes
- trigger module load manually in other modules that might need it?

Thanks 🙂

**Comment by developer239** [comment]
Full question on StackOverflow is here: https://stackoverflow.com/questions/54772008/trigger-module-lazy-load-manually-angular-7
