### ISSUE TITLE
the tutorial page: https://angular.io/tutorial/toh-pt3  is hung

### ISSUE THREAD

**Issue by teacherpan** [angular/angular#25796]
when i open https://angular.io/tutorial/toh-pt3 , the page is hung.
The console error as below：
![image](https://user-images.githubusercontent.com/12424383/45005646-2ffb1f80-b027-11e8-89d1-14f5d8a42f6a.png)

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/25786
