### ISSUE TITLE
HTML is not rendered some times when _ngcontent-c6="" in IE 11

### ISSUE THREAD

**Issue by cloudcodemaster** [angular/angular#25809]
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:

## Expected behavior
1. It should display the input element mat-form-field
![image](https://user-images.githubusercontent.com/5492297/45062194-b847e780-b05c-11e8-8f57-5822d7fd3f1b.png)

2. With the _ngcontent-c6 without the =""
![image](https://user-images.githubusercontent.com/5492297/45062288-14127080-b05d-11e8-82ad-68d7ef67ee9c.png)

## Minimal reproduction of the problem with instructions
The issue seldom happens and always when the UI has been recently rendered by the very first time.

1. HTML elements, missing input element is inspected using IE Developer Tools :
![image](https://user-images.githubusercontent.com/5492297/45061802-de6c8800-b05a-11e8-8dad-67834c181100.png)

2. This is the DOM Explorer of the <li> element which already contains the issue _ngcontent-c6=""
![image](https://user-images.githubusercontent.com/5492297/45061934-6fdbfa00-b05b-11e8-80e1-17f464276c6b.png)

## Environment

![image](https://user-images.githubusercontent.com/5492297/45062021-eed13280-b05b-11e8-81bd-bae11501b026.png)

ng -version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.0.8
Node: 10.4.1
OS: win32 x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.0.0
@angular/cli                      6.0.8
@angular/material                 6.0.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- node --version
v10.4.1
- Platform:  Windows 

Others:
 Operating system version: Windows 7
 IDE: Visual Code 1.26.1
 HTTP server: IIS 7.5.7600.16385

THANKS FOR YOUR HELP.

**Comment by mhevery** [comment]
Without a small reproduction case we don't have time to spend on guessing what the issue is. Once you have a  consistent repro case please open a new bug.
