### ISSUE TITLE
Documentation issue - multicast subscriber example contains (tiny?) mistake

### ISSUE THREAD

**Issue by konryd** [angular/angular#25804]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Disclaimer
I'm only getting started with ng2. What I'm describing below might be perfectly fine in ways that I just don't see.

## Current behavior
The observables documentation page contains an example for a multicasting observable here:
https://angular.io/guide/observables#multicasting

Under the header "Create a multicast subscriber"

The example uses a helper function "function doSequence(observer, arr, idx)" which returns a timeoutId. This timeoutId can be used to clearTimeout() (when the observers count drops to 0), but *only when it is the first timeout*. Once the first iteration happened, the sequence must run to the end.

This might be intended behavior (it lets re-subscribe into the middle of the sequence), but the cleanup is still there for the very first timeout. This seems inconsistent to me.

A way to address this would be to either keep the most recent timeoutId in the object's state or drop the clearTimeout() call.

**Comment by jenniferfell** [comment]
@jasonaden Please confirm and recommend a change if appropriate. Thanks!

**Comment by elbaumpj** [comment]
I'd like to jump in on this if a change does need to be made.

**Comment by rockument69** [comment]
@jbogarthyde : As you were the last person to edit this file, do you know if this problem was fixed in the doc? This is the [Multicasting section of Observables Overview](https://angular.io/guide/observables#multicasting).

**Comment by jbogarthyde** [comment]
I don't believe the examples have changed since the page was initially published. The subject-matter expert who provided the examples is no longer on the team. @alxhub is listed as the reviewer in pullapprove.

**Comment by rockument69** [comment]
@elbaumpj and @alxhub : Can either of you recommend what change to make to the example? Would it be to keep the most recent timeoutId in the object's state, or drop the clearTimeout() call? Or some other solution? Or does it work as expected? Thanks.

**Comment by elbaumpj** [comment]
@rockument69 - I'm not working on Angular much these days and don't have capacity to dig too much into this issue. Apologies!

**Comment by petebacondarwin** [comment]
I think I can see what is wrong here. We are only tracking the `timeoutId` from the first `setTimeout()` call. The `doSequence()` will recurse into itself 3 times but only the first `setTimeout()` id is returned and stored.

The code for the `doInSequence()` function is more correct. Each call to `setTimeout()` stores its `timeoutId` and the whole function is inside the closure of the subscriber function.
