### ISSUE TITLE
MatSelectionList in a nested form produces strange results

### ISSUE THREAD

**Issue by steve-todorov** [angular/angular#25814]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`MatSelectionList` in a `FormArray` does not work as expected and produces strange results (some of them are just empty). 

## Expected behavior
When you select options in a `MatSelectionList` it should properly be pushed to the `FormArray`

## Minimal reproduction of the problem with instructions
1. [StackBlitz](https://stackblitz.com/edit/angular-issue-k201zsoa?embed=1&file=app/app.component.ts)
2. Open the console (in stackblitz)
3. Add a privilege (select 1 option)
4. Add another privilege (select more options)
5. Pay attention to the `Parent form privileges` output which will get weird results (on the first add you will get the proper result, but on the second one the records will get messed up.) and the `DEBUG` output in the HTML, which always shows an empty record of the selected privileges.

## Environment
<pre><code>
Angular version: 6.1.6
Browser: Any
</code></pre>

**Comment by manklu** [comment]
You should report that in the Material issue tracker: https://github.com/angular/material2/issues
