### ISSUE TITLE
entryComponents when build as a package

### ISSUE THREAD

**Issue by Liork1** [angular/angular#25815]
Hi all,

I have an angular 5 project which eventually will be given to users as a package.
In it, I'm dynamically rendering templates, and each one of the components being added to **entryComponents** in module.

I'm looking for a way to give the package users an ability to add their own component to the **entryComponents** array.

Did someone had the chance to add dynamic components without tactfully import it in module?
Any lead will be appreciated.

Regards,
Lior

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
