### ISSUE TITLE
formControlName can't be alphanumeric in Angular Reactive Form

### ISSUE THREAD

**Issue by Aman-Jojra** [angular/angular#25830]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

if I define formControlName field as alphanumeric like past8Digits, form validations doesn't work at all.

## Expected behavior

Standard javascript variable name can be alphanumeric. Hence ReactiveFormControlName should be alphanumeric.

## Minimal reproduction of the problem with instructions

```
  testForm = this.fb.group({
    last8Digits: ['', [ <!-- See this alphanumeric field Name-->
      Validators.required,
      Validators.pattern(/^\d+$/),
      Validators.minLength(8),
      Validators.maxLength(8)]
    ]
  });
```

## Environment

<pre><code>
Angular version: X.Y.Z

6.0.0
Browser:
- [ x] Chrome (desktop) version XX
- [ x] Chrome (Android) version XX
- [ x] Chrome (iOS) version XX
- [ x] Firefox version XX
- [ x] Safari (desktop) version XX
- [ x] Safari (iOS) version XX
- [ x] IE version XX
- [ x] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by manklu** [comment]
Works for me
https://stackblitz.com/edit/angular-1f1utx?file=src%2Fapp%2Fhello.component.ts

**Comment by kara** [comment]
@Aman-Jojra Based on your code snippet, validation appears to be working as expected. If you still think there's a bug here, please open a new issue with clear instructions for how to reproduce, what you expect to happen, and what actually happens. Currently there isn't enough actionable info to work with.
