### ISSUE TITLE
Register Locales not only in the Root Module

### ISSUE THREAD

**Issue by rdnscr** [angular/angular#25835]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I use the datepipe with specific localization which i enforce. Therefore i make the explicit registration in my app.module.ts and everything works fine:
```
import { registerLocaleData } from "@angular/common";
import localeEs from "@angular/common/locales/es";

registerLocaleData(localeEs);
```

However we are providing a base framework and i wanted to register the localization there, so consumer projects don't have to mess with localization. From my point of view it looks like it is only possible to register locales in the root module (usually app.module.ts). I could not find a hint for that in the documentation (or i was blind, which happens some times). Is the observed behavior correct and if so could the documentation be updated?

## Expected behavior
The documentation should be updated or it should be possible to register locales globally from multiple points and not only the root module.

## Minimal reproduction of the problem with instructions
Create a regular module where you do the registration of your specific locales and remove the registration from the app.module.ts. From then on datePipes are throwing the missing locales exception again.

Thanks in advance for clarification.

**Comment by ocombe** [comment]
You can register the locales anywhere as long as you do it before you use any of the i18n pipes (number, date, ...), otherwise it might trigger an error saying that it cannot find the locale data for that locale. This is why we prefer not to advertise this behavior, so that people don't fall into weird async bugs that are hard to debug.
