### ISSUE TITLE
node:21980) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

### ISSUE THREAD

**Issue by raghulrajnkl** [angular/angular#25840]
## I'm submitting a...
node:21980) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
@ng-toolkit/universal using serverside rendering, 

Angular version: 6.1.5

"@ng-toolkit/universal": "^1.1.41-beta.110",

 
For Tooling issues:
- Node version: 10.5.0
- Platform:  Windows

**Comment by trotyl** [comment]
It's not caused by Angular, please report to whichever library you're using.

**Comment by IgorMinar** [comment]
can you please report this at https://github.com/maciejtreder/ng-toolkit thanks!

**Comment by kimamula** [comment]
@IgorMinar I came across this warning and found that [the cause of this is xhr2@0.1.4](https://github.com/pwnall/node-xhr2/blob/v0.1.4/src/xml_http_request_upload.coffee#L35) on which [@angular/platform-server depends](https://github.com/angular/angular/blob/e18a52e24a834f8795f8ed07b446f2a21ef28708/packages/platform-server/package.json#L27).

**Comment by Avcajaraville** [comment]
Im having the same issue and I believe @kimamula is right.

**Comment by IgorMinar** [comment]
There are several sources of this warning.

Is there a newer version of xhr2 that doesn't have this problem? Of so,
could you please try to send us a PR with the update?

I think it should be sufficient to update these two files:

https://github.com/angular/angular/blob/master/packages/platform-server/package.json
https://github.com/angular/angular/blob/master/package.json

And rebuild the yarn.lock file.

// @vikerman

**Comment by patrickmichalina** [comment]
hmmmm I see this happening on the server when `HttpClient` is called.

**Comment by dima-gusyatiner** [comment]
I also see it with angular universal when calling HttpClient.

I thought this is what blocked it.
But the universal app seems to still be unresponsive, even on node 8.11, without the deprecation notice for Buffer.
