### ISSUE TITLE
Unit testing hybrid application

### ISSUE THREAD

**Issue by zlaja1983** [angular/angular#25846]
I am using angular 6 and angular 1.6 and running it as a hybrid app. How can I configure angular cli so that it will run *spec.js as well as *spec.ts files. My 1.x specs are using angular-mocks but i can't seem to configure it correctly within test.ts file.

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
