### ISSUE TITLE
NgSelectOption with ngValue excessively calls compareWith function

### ISSUE THREAD

**Issue by fatsu** [angular/angular#25842]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When NgSelectOption receives (set) a value for NgValue, it first adds this value to the _optionMap of the host SelectControlValueAccessor, and then calls writeValue with the current value of the SelectControlValueAccessor.

When writeValue is called, it loops over all entries in the _optionMap until a match is found in order to visually set a correct value on the html element. This causes the compareWith functions to be called up to (n * (n + 1) / 2) times when adding the #n options!

Similar logic is performed when the NgSelectOption is destroyed: the value is removed from the _optionMap and writeValue is called again with the current value of the SelectControlValueAccessor. This causes the compareWith functions to be called up to (n * (n - 1) / 2) times when removing #n options!

## Expected behavior

NgSelectOption should not explicitly set or delete items from SelectControlValueAccessor's _optionMap and call writeValue with the current value, instead it should call new addOption and removeOption functions so that the responsability for the logic lies within SelectControlValueAccessor. This way SelectControlValueAccessor can just compareWith the newly added option to it's 
current value and take actions accordingly. Same for removal.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-csbdgx
(see console logging)

## What is the motivation / use case for changing the behavior?

We have a very complex form (with array) with several selects. When adding or removing formgroup(s) to the form-array, we noticed delays in creation and destruction of the corresponding components and long running script warnings in the console. This appears to be related to the excessive calls to the compareWith functions. 

## Environment

<pre><code>
Angular version: 5.2.11
6.1.7 has similar behaviour

Browser:
- [X] Chrome (desktop) version 68
- [X] IE version 11

</code></pre>

**Comment by ericmartinezr** [comment]
Related/dup https://github.com/angular/angular/issues/19723

**Comment by kara** [comment]
@fatsu Agree we can probably improve here. Let's track in #19723.
