### ISSUE TITLE
environment.ts should be merged not overwritten

### ISSUE THREAD

**Issue by snebjorn** [angular/angular#25844]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
environment.ts is overwritten with environment,target.ts

### Example

**environment.ts**
```
export const environment = {
  production: false,
  foo: "bar"
}
```

**environment.prod.ts**
```
export const environment = {
  production: true
}
```

**Result (ng build --configuration=prod)**
```
{
  production: true
}
```

## Expected behavior
environment.ts should be merged with environment,target.ts

### Example

**environment.ts**
```
export const environment = {
  production: false,
  foo: "bar"
}
```

**environment.prod.ts**
```
export const environment = {
  production: true
}
```

**Expected result (ng build --configuration=prod)**
```
{
  production: true
  foo: "bar"
}
```

## What is the motivation / use case for changing the behavior?
Frameworks like ASP.NET or Spring Boot merge environment configs like the expected example given.

## Workaround
**environment.base.ts**
```
export const environment = {
  production: false,
  foo: "bar"
}
```

**environment.ts**
```
import { environment as base } from "./environment.base";

export const environment = {
  ...base,
}
```

**environment.prod.ts**
```
import { environment as base } from "./environment.base";

export const environment = {
  ...base,
  production: true
}
```

## Environment

<pre><code>
Angular CLI: 6.1.5
Node: 9.10.1
OS: win32 x64
Angular: 6.1.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cdk                      6.4.7
@angular/cli                      6.1.5
@angular/flex-layout              6.0.0-beta.18
@angular/material                 6.4.7
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.3.1
typescript                        2.9.2
webpack                           4.9.2
</code></pre>

**Comment by gkalpak** [comment]
This sounds like an issue for https://github.com/angular/angular-cli.
