### ISSUE TITLE
What browsers does Angular support?

### ISSUE THREAD

**Issue by themihai** [angular/angular#2584]
I couldn't find any list of the supported browsers but there are several references to IE8, IE9, IE10 in the source code (e.g. [0]). Does angular plan to support all these old versions?

[0] https://github.com/angular/angular/blob/9700e80698e867282c4c32741962c334782bef45/modules/angular2/src/render/xhr_impl.ts#L14

**Comment by nomack84** [comment]
AFAIK only evergreen browsers, that means IE10+ and latest versions of Firefox, Chrome, Safari and Opera.

**Comment by gdi2290** [comment]
@themihai that was my fault, Angular2 plans to only support evergreen browsers. There will be a solution for your app to work with legacy browsers if everything goes according to plan. That solution would be limiting but of course so are those browsers. When that solution is finished then IE(8-10) will work without much effort and of course if you're crazy enough we might be able to support everything down to IE6 using the same strategy. Also keep in mind I'm speaking for myself and not for the Angular Team team. My friend and I are making the steps towards this solution and hope to reach our goal before we start experimenting with the impossible ones (IE6-7)

**Comment by themihai** [comment]
@gdi2290 that makes sense. I guess the solution for the legacy browsers will be a kind of polyfill. Wrt evergreen browsers, is it only Edge on the list  or both IE11 and Edge?

**Comment by nomack84** [comment]
@gdi2290 Are you saying that all the Webcomponents stuff will work in IE8? Where did you get that info? The Angular team is agree with this?

**Comment by gdi2290** [comment]
@themihai polyfills aren't fun. Angular currently uses polyfills, even now, for ES6 so adding more would really lag the bootstrap time as experienced by Polymer in ie10. 

@nomack84 sorry, web components won't ever work in IE8.

Again this information is coming from me and I'm working on it. I rather have the angular team and everyone using angular2 developing for modern browsers while having a solution that will work for legacy. Doing so will keep everyone looking forward while not leaving anyone behind. There will be more news in the future so there is no reason to worry about browser support right now especially since Angular2 is still in alpha switch is before beta which is before release candidate which is before stable

**Comment by nomack84** [comment]
@gdi2290 If web components won't ever work on IE8, the Angular2 won't ever work on it.

**Comment by pkozlowski-opensource** [comment]
nomack84 huh? You can use Angular2 without web components perfectly fine.

**Comment by nomack84** [comment]
Oh, sorry, I didn't knew that. I thought it was like Polymer where
webcomponents is a must.

2015-06-17 10:22 GMT-05:00 Pawel Kozlowski <notifications@github.com>:

> nomack84 huh? You can use Angular2 without web components perfectly fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/angular/issues/2584#issuecomment-112843418>.
>



-- 
Ing. Mario A. Alvarez García
Teléfono: +593-998483331

**Comment by pkozlowski-opensource** [comment]
Nope, it is not like polymer. You can use web components in ng2 apps but ng2 components (directives) are not web components (at least not for now - but pretty close semantically!)

**Comment by nomack84** [comment]
I thought it was because all the ShadowDom stuff and cause Angular promotes Custom Components throught directives... :)

**Comment by vicb** [comment]
>   I thought it was like Polymer where webcomponents is a must

Yes it is like Polymer, native WC is optional.

**Comment by themihai** [comment]
@gdi2290 I was actually worried about support of legacy browsers(not the lack of it) after I've seen the commit comments thus the reason of the question. AFAIC it would vote for best Angular on the latest browsers (i.e. Chrome, FF, Safari 9 and IE edge)

**Comment by shahzadmasud** [comment]
Does Angular support IE Edge or not?

**Comment by zoechi** [comment]
@shahzadmasud https://saucelabs.com/u/angular2-ci

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by shahzadmasud** [comment]
Thanks @zoechi; Safari is not listed, does that mean there isn't any plan for that or its implicitly supported.

**Comment by zoechi** [comment]
@shahzadmasud see also #9252

**Comment by cedvdb** [comment]
@pkozlowski-opensource What do you mean not for now ? Will there be a possibility to port an angular 2 component into a native custom element ? Is the big game plan to have angular 2 on top of custom elements in the future ?

**Comment by andyrh3** [comment]
Can you not just transcode? :-)

**Comment by VenkatRamReddyK** [comment]
How to detect the supported browsers list with versions for angular 1.3. 
If I upgrade to angular 1.5 in the future, how to we get the supported browsers list for the latest angular version?. 
O don't a relevant solution for this and this ticket is closed. Weird.
Note: Give an answer for non-IE Browsers.

**Comment by DzmitryShylovich** [comment]
it's angular 2 repo

**Comment by VenkatRamReddyK** [comment]
Sorry, I was in a wrong thread.

**Comment by juztinlazaro** [comment]
Anyone here having solve about angular4 browser compatibility in safari 8?

**Comment by tysonhummel** [comment]
I'm not able to run a fresh angular-cli project in safari 8. I have clients who still use 8 unfortunately and I need a solution.

**Comment by juztinlazaro** [comment]
@tysonhummel 

in polyfills.ts


uncomment this plugins


```
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';

```
