### ISSUE TITLE
[Bug?] In Angular 7 beta 5, ngDoBootstrap doesn't fire from external library module

### ISSUE THREAD

**Issue by alshdavid** [angular/angular#25850]
## I'm submitting a bug

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have the following library in an external library:

```
import { NgModule, DoBootstrap } from '@angular/core';
import { TestLibComponent } from './test-lib.component';

@NgModule({
  imports: [],
  declarations: [TestLibComponent],
  exports: [TestLibComponent]
})
export class TestLibModule implements DoBootstrap {
  ngDoBootstrap() {
    console.log('should fire');
  }
}
```

## Expected behavior
I expect the browser console to display 'should fire'

## Minimal reproduction of the problem with instructions
`ng new test-project`
`ng generate library test-library`

modify the TestLibrary module to the above code

`ng build test-library`
`ng serve`

Open browser and check console

## What is the motivation / use case for changing the behavior?
I am not sure if the feature hasn't been implemented yet, but I am really excited for this as - if I understand it correctly - it will allow me to initialize services and pass in parameters from the `fromRoot()` method like so:

e.g:

```
import { NgModule, DoBootstrap } from '@angular/core';
import { TestService } from './test-lib.service';

@NgModule({
  imports: []
})
export class TestLibModule implements DoBootstrap {
  config

  constructor(testService: TestService){}

  forRoot(config) {
      this.config = config
      return {
        providers: [TestService],
      }
  }

  ngDoBootstrap() {
    testService.init(this.config)
  }
}
```

And when implemented, the services in the TestLibModule will fire up on bootstrap with the following settings
```
import { NgModule, DoBootstrap } from '@angular/core';
import { TestLibModule } from 'test-lib';

@NgModule({
  imports: [
    TestLibModule.forRoot({ my: 'config' })
  ]
})
export class AppModule implements { }
```

## Environment

<pre><code>
Angular version: 7.0.0-beta.5

Browser:
- All
 
For Tooling issues:
- Node version: 10
- Platform:  Windows

Others:
</code></pre>

**Comment by dawidgarus** [comment]
ngDoBoostrap is not to initialize module and services, but to bootstrap the app. It's only used for app module:
```
platformBrowserDynamic().bootstrapModule(AppModule);
                                         ^^^^^^^^^
```
To do what You want to do, just use module's constructor, i.e.:
```ts
export const TEST_LIB_CONFIG = new InjectionToken<any>('TEST_LIB_CONFIG');

export class TestLibModule {

  constructor(@Inject(TEST_LIB_CONFIG) config: any, testService: TestService) {
    testService.init(config);
    // or what's even better - inject TEST_LIB_CONFIG directly to TestService
  }

  static forRoot(config) {
      return {
        providers: [
          { provide: TEST_LIB_CONFIG, useValue: config },
          TestService,
        ],
      };
  }
}
```

**Comment by IgorMinar** [comment]
thanks @dawidgarus !

**Comment by kotelnik** [comment]
Hi! I'm currently using angular version 7.2.9. And I'd still like to know why ngDoBootstrap doesn't fire. There are other use-cases where one use it and it still exists in docs https://angular.io/api/core/DoBootstrap

The possible use-case for it is a custom bootstrap preparing code. Like when one uses dynamic components with help of ng-dynamic-component and wants to place two or more such components (with the same component name) to otherwise non-angular page.
