### ISSUE TITLE
Angular 6 don't show -webkit-linear-gradient

### ISSUE THREAD

**Issue by Nelife** [angular/angular#25854]
<pre><code>
Angular version: 6.1.0

Browser:
- Chrome (desktop) version 68.0.3440.106
 
For Tooling issues:
- Node version: 8.11.4 - Windows 10

</code>
</pre>
Css not show tag "-webkit-linear-gradient"
Detail in image:
![image](https://user-images.githubusercontent.com/12018657/45210585-335a0980-b2ba-11e8-8b65-5c4ebfa0e789.png)
Please help me to fix it. Thank you so much.

**Comment by ericmartinezr** [comment]
Are you using the CLI? Try this comment https://github.com/angular/angular/issues/24183#issuecomment-395283582

**Comment by Nelife** [comment]
Thank you so much.

**Comment by IgorMinar** [comment]
closing in favor of https://github.com/angular/angular/issues/24183

**Comment by alan-agius4** [comment]
@nelife, sorry for getting back to you this late. 

The problem which your code is that most likely browsers you support via browserslist don't require the `-webkit` prefix, and `left` is not a valid directional value.

Valid direction values are:  to bottom, to top, to right, to left, to bottom right, etc..
