### ISSUE TITLE
why lazy loading route make file size bigger ?

### ISSUE THREAD

**Issue by Zuckjet** [angular/angular#25878]
from the angular doc, we can use lazy route to make our angular application rendering faster:
```
{
  path: 'admin',
  loadChildren: 'app/admin/admin.module#AdminModule',
}
```
and I find a very very simple github repo just for displaying lazy route loading [here](https://github.com/saigowthamr/Angular-Lazy-loading).
I will show the route file here:
```
import { NgModule } from "@angular/core";
import { RouterModule, Routes } from "@angular/router";
import { HomeComponent } from "./home/home.component";

const routes: Routes = [
  {
    path: "",
    component: HomeComponent
  },
  {
    path: "posts",
    loadChildren: "../app/posts/posts.module#PostsModule"
  },
  {
    path: "king",
    loadChildren: "../app/king/king.module#KingModule"
  }
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule],
  providers: []
})
export class AppRoutingModule {}
```
from the network, we can see:
![image](https://user-images.githubusercontent.com/17976139/45260135-8d211780-b411-11e8-9c36-0117962e54d1.png)

as the picture show, when i navigate to post page, it will load app-post-post.module.js. and when i navigate to king page, it will load app-king-king.module.js. everything seems perfect.

But when i don't choose lazy load, change the route file like this:
```
const routes: Routes = [
  {
    path: "",
    component: HomeComponent
  },
  {
    path: 'posts',
    component: PostsComponent
  },
  {
    path: 'king',
    component: KingComponent
  }
];
```

from the network, we can see:
![image](https://user-images.githubusercontent.com/17976139/45260165-35cf7700-b412-11e8-9405-a4649379c858.png)

though the lazy load reduce the main.js, but make the sum size bigger than before.
lazy load size: 16.6KB + 55.7KB + 7.5KB
not use lazy load size: 32.2KB

why lazy loading route make the sum size of js file bigger. Since the lazy load make files bigger , is it worth using lazy route load in our project?

**Comment by mlc-mlapis** [comment]
@Zuckjet ... you should certainly check what the `PostsModule` contains ... it looks that the bundle contains more (maybe some polyfills or third-parties) than it should.

**Comment by Zuckjet** [comment]
it really don't contain other library, you can take a look at it. I have shown the github repo above.It is a tiny and basic  repo just for showing the usage of angular lazy routing load.

**Comment by Zuckjet** [comment]
@mlc-mlapis  I dig into the app-posts-posts.module.js for a while. I cannot find anything else but some relevant file of post page.

**Comment by mlc-mlapis** [comment]
@Zuckjet ... I meant using https://www.npmjs.com/package/webpack-bundle-analyzer or https://www.npmjs.com/package/source-map-explorer to show the map. The reality is that some files have to represent the size of that bundle ... it's not just guessing, it's 100 % exact information.

**Comment by Zuckjet** [comment]
@mlc-mlapis many thanks for your reply. I adopt your  advice to analyze my build file by source-map-explore. It turn out to be that the final post module bundle file contain the the **axios** library.
![image](https://user-images.githubusercontent.com/17976139/45280298-5842bc80-b506-11e8-9578-95fdb99878ed.png)

We can see the axios libray take too much size in app-posts-posts-module.js. 
**But when i don't use lazy load routing, the axios libray seems take very very small size**:

![image](https://user-images.githubusercontent.com/17976139/45280438-ee76e280-b506-11e8-9aa6-b800d189b283.png)

here is how axios is used in posts module:
```
import { Component, OnInit } from "@angular/core";
import axios from "axios";

@Component({
  selector: "app-posts",
  templateUrl: "./posts.component.html",
  styleUrls: ["./posts.component.css"]
})
export class PostsComponent implements OnInit {
  data = [];

  show: Boolean;

  constructor() {}

  ngOnInit() {
    this.show = true;
    axios
      .get("https://jsonplaceholder.typicode.com/users")
      .then(res => {

        this.data = res.data;
        this.show = false;
      })
      .catch(err => console.log(err));
  }
}

```
when I use lazy loading route, the bundle file will include much axios code.
If I don't use lazy loading route , it won't include too much code in bundle file.
that really confused me, hope anyone can help me.

**Comment by mlc-mlapis** [comment]
@Zuckjet ... not sure why you are trying to use Axios instead of Angular HttpClient at all.

**Comment by Zuckjet** [comment]
ignore this, I think that doesnot matter in this question. I think it is the angular cli that doesnot do right thing for the lazy load.
Since i have provided  complete code and many details, and nobody can figure it out. I will close the issue. Thank you all the same.

**Comment by cmddavid** [comment]
@Zucket, you did not provide the code before you used lazy loading. Maybe the import statement is different? Or you import axios in both the child module and root module?

**Comment by Zuckjet** [comment]
@cmddavid  I git clone  [this repo](https://github.com/saigowthamr/Angular-Lazy-loading) for testing.
Because it is very simple and only for testing lazy load.
could you take a glance at it , may be you can give me some useful advices?

**Comment by sarunint** [comment]
That's because the way he used Axios is incorrect. So it is included in both Nlnon-lazy module and lazy module.

There are 2 options:

1. Use Angular's `@angular/common/http` instead of Axios.
2. Use dependency injection mechanism to import Axios.

I'm recommending the first choice, though.

**Comment by mlc-mlapis** [comment]
@Zuckjet ... that is the repo for lazy loaded where you are using `import axios from "axios";` in `posts.component.ts` but you didn't show the version without lazily loaded module ... and where you used `import axios from "axios";` because it's not shown on the bundle map above at all.

**Comment by Zuckjet** [comment]
@mlc-mlapis I just change two file for non-lazy-load mode:
app-routing-module.ts changes
```
const routes: Routes = [
  {
    path: "",
    component: HomeComponent
  },
  {
    path: 'posts',
    component: PostsComponent
  },
  {
    path: 'king',
    component: KingComponent
  }
];
```

app.module.ts changes:
```
@NgModule({
  declarations: [AppComponent,HomeComponent],
  imports: [BrowserModule, AppRoutingModule,FormsModule,HttpModule, KingModule, PostsModule],
  providers: [],
  bootstrap: [AppComponent]
})
```

just change the two file, other file remain old content.

**Comment by mlc-mlapis** [comment]
@Zuckjet ... are you looking for the right bundle? Because I can see source TS files ... but they should be JS files in the bundle ... what is the map for?

**Comment by Zuckjet** [comment]
@sarunint  It is common to use dependency injection mechanism to inject serviec, but how to inject a libray, can you show me the simple example or provide reference doc?

**Comment by mlc-mlapis** [comment]
@Zuckjet ... just using wrapping such a library ... as your service which can be injected then.

Btw ... create the map for the vendor.xxxx.bundle.js which should contain all third-parties libs.

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

It looks like some good discussion in this issue. These would be best tracked on StackOverflow. Or, if by the end of this discussion, you feel you've found a bug, please create a new issue with the reproduction. Thanks!
