### ISSUE TITLE
Dynamic compilation of angular component template

### ISSUE THREAD

**Issue by sureshDurai123** [angular/angular#25871]
In our application we are rendering the template dynamically since in AngularJS we $compile to compile html dynamically  like wise is anything available in angular 6 to compile HTML maually.please suggest me.Thanks in advance

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by pkozlowski-opensource** [comment]
> $compile to compile html dynamically like wise is anything available in angular 6 to compile HTML maually

There is no equivalent of `$compile` from AngularJS in Angular 2+. We might have a similar infrastructure in the future but there is no design yet. Closing as not actionable at the moment.
