### ISSUE TITLE
Introduce router.canActivateUrl method

### ISSUE THREAD

**Issue by ramyhhh** [angular/angular#25875]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

In @angular/router: Currently if we have a url we can not know ahead of time if it's going to be activated or not, we can only call navigate which will do the whole navigation process. For many cases it's useful to check if a url can be activated without the actual navigation.
One common example is applying role based authorization using AuthGuard, and where there is a view (typically sidebar) that displays buttons to navigate to different components. The convenient behavior is to hide buttons (links) that will not navigate due to complex business inside AuthGuard.

## Expected behavior

A method inside the router like:```router.canActivateUrl(url)``` or to add property to the extra parameter inside navigateByUrl like: ```router.navigateByUrl(url,{skipActualNavigation})``` which will do everything navigateByUrl do, except for actual navigation (and except for data resolvers since no navigation will happen)

## What is the motivation / use case for changing the behavior?

Applying role based authorization using AuthGuard and view/hide navigation links accordingly

## Others

There is a simple workaround to achieve this which is to do it is to export the Recognizer class which can be used independently of the router.
</code></pre>

**Comment by jasonaden** [comment]
I believe the best way to do this currently would be `router.urlHandlingStrategy.shouldProcessUrl(url)`. Getting any deeper than this would require async APIs because the URL may require module loading in order to get further info.
