### ISSUE TITLE
Website link is broken

### ISSUE THREAD

**Issue by jgenchik** [angular/angular#25881]
The following link is not found: https://angular.io/guide/dependency-injection-pattern

version 6.1.0

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[XX ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Where did you get that link from? The link is https://angular.io/guide/dependency-injection

**Comment by jgenchik** [comment]
Go to angular.io
On the top menu select DOCS
On the side menu click on "Dependency Injection"
The top option of the above submenu is " The Dependency Injection pattern "
Click that in that returns formatted 404 page

**Comment by jgenchik** [comment]
Nevermind. My bad. I just cleared cache and the page came back with the Anguar version 6.1.7 and everything now works. Sorry for the false alarm.
