### ISSUE TITLE
Angular 6 page reload or redirect throws "loadChunkError":true

### ISSUE THREAD

**Issue by vivekkingston** [angular/angular#25884]
I'm  using angular 6 MVC application with webpack build. It throws an **"loadChunkError":true"** randomly on page load or redirect,
After the error occurred, angular routing not works and throws an console error continuously.

[**Note:** Once i cleared the browser cache and then routing works fine]

**Webpack file**
const webpack = require("webpack");
const path = require("path");
const UglifyJsPlugin = require("uglifyjs-webpack-plugin");
const HtmlWebpackPlugin = require('html-webpack-plugin');
var SourceMapDevToolPlugin = require('webpack/lib/SourceMapDevToolPlugin');
let SharedCache = {};
const entryPath = path.resolve(__dirname, "src");
const viewPath = path.resolve(
    __dirname,
    "../Views/Home"
);
const { BaseHrefWebpackPlugin } = require('base-href-webpack-plugin');
const ROOT = path.resolve(__dirname, '');
const app = `${entryPath}`;
module.exports = envOptions => {
  envOptions = envOptions || {};

    const config = {
        entry: {
            polyfills: `${entryPath}\\polyfills.ts`,
            vendors: `${entryPath}\\vendor.ts`,
            app: `${entryPath}\\main.ts`
        },
        output: {
            path: viewPath,
            publicPath: '/',
            filename: "../../angularBundle/[name].js",
            chunkFilename: '../../angularBundle/[name].js',
            sourceMapFilename: "../../angularBundle/[name].js.map",
        },
        resolve: {
            extensions: [".ts", ".js", ".html"],
            alias: {
                jquery: "jquery/src/jquery"
            }
        },  
    module: {
      rules: [
        {
          test: /\.ts$/,
          loaders: ["awesome-typescript-loader?configFileName=./src/tsconfig.json", "angular2-template-loader"]
          },
          {
              test: /\.(ts|js)$/,
              loaders: [
                  'angular-router-loader'
              ]
          },
        {
          test: /\.html$/,
          loader: "raw-loader"
        },
        {
          test: /\.css$/,
          loader: "raw-loader"
          }
          ,
          {
              test: /\.(png|jpg|eot|cur|svg|gif|ttf|woff|otf)$/,
              loader: "file-loader",
              options: {
                  outputPath: 'fonts/'
              }
          } 
      ]
        },
        devtool: 'eval',
        plugins: [
      new webpack.NoEmitOnErrorsPlugin(),
        new HtmlWebpackPlugin({
            template: viewPath + "/loader.cshtml",
            filename: viewPath + "/Index.cshtml",
            inject: false
            })
        ],
      optimization: {
          splitChunks: { chunks: 'all' },
        },
  };

    if (envOptions.MODE === "prod") {
        config.plugins.push(
            new UglifyJsPlugin()
        );
    }

  return config;
};

**Error Snap**
![image](https://user-images.githubusercontent.com/21965691/45208272-d3f2fe00-b2a7-11e8-8ed2-b7ca26099541.png)

Please suggest a solution or steps to fix the issue.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by benlesh** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by shreekrishnaban** [comment]
Just to trace the actual error load component directly instead of loading it lazily.. Then it throws the actual error.. Fix that and again load module as you did before..
