### ISSUE TITLE
Async timeout in Jasmine unit test when clicking a DebugElement that has stopPropagation()

### ISSUE THREAD

**Issue by PooSham** [angular/angular#25887]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

In my Angular 6 application, I have an element which calls event.stopPropagation() when being clicked. The element works as intended when I try it manually. 

I made a unit test in jasmine that makes sure that the propagation is indeed stopped. The test works by accessing its DebugElement and calling `triggerEventHandler('click',  { button: 0 });` on it. This led to an error saying: `Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.`

I solved the issue by using the nativeElement's click method instead, but I don't see why using the debugElement shouldn't work. 

## Expected behavior

`stopPropagation` is handled correctly by the `triggerEventHandler` by not timing out.

## Minimal reproduction of the problem with instructions

I made a post about this on stackoverflow [here](https://stackoverflow.com/questions/52224166/event-stoppropagation-in-angular-app-leads-to-jasmine-timing-out/52254246#52254246). It includes a link to stackblitz.com for a minimal example of how I use `event.stopPropagation()`, but I couldn't figure out how to add a jasmine unit test to it. 

## What is the motivation / use case for changing the behavior?

When testing that clicking an element doesn't accidentally click other elements underneath it. 

## Environment

<pre><code>
Angular version: 6.1.7

Browser:
- [ x ] Chrome (desktop) version 68
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.2 
- Platform: Windows  

Others:
jasmine-core v3.1.0
jasmine-spec-reporter v4.2.1
karma v2.0.4
karma-chrome-launcher v2.2.0
karma-coverage-istanbul-reporter v2.0.0
karma-jasmine v1.1.1
karma-jasmine-html-reporter: v1.1.0
</code></pre>

**Comment by vikerman** [comment]
This is expected behavior. Triggering the native event is the right approach here.
