### ISSUE TITLE
Ivy Render Error

### ISSUE THREAD

**Issue by abadakhshan** [angular/angular#25880]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I install the angular-cli@@7.0.0-beta.2
then I created a new project with option --experimental-ivy

When I run with ng serve  I get this error on chrome 

 ASSERTION ERROR: Type passed in is not ComponentType, it does not have 'ngComponentDef' property.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3 
- Npm version : 5.6.0
- Platform:  Windows

Others:

</code></pre>

**Comment by JoostK** [comment]
Such error is produced for non-AOT bundles, where the Ivy JIT compiler is not enabled.

You can easily avoid this error by running `ng serve --aot` instead, as that will run `ngtsc` to generate the currently missing Ivy definitions.

If you do want JIT, there is some more work to be done. Angular 7's bundles will still have ViewEngine's infrastructure enabled by default, not Ivy's. If you want to enable Ivy in the runtime as well, you'd first have to run `ngcc` to convert packages in node_modules from ViewEngine to Ivy's infrastructure. Alternatively, you could build Angular from source using Bazel and specify `--define=compile=jit`, see [Bazel guide](https://github.com/angular/angular/blob/bbb3f8fa60d5937f3a914a1a9fb498d9a5e970b2/docs/BAZEL.md#various-flags-used-for-tests) for more information.

@hansl Perhaps it would be a good idea to mention somewhere with the `--experimental-ivy` option that it only works OOTB when using AOT builds, as JIT mode requires some more effort that has not yet been documented I think.

**Comment by abadakhshan** [comment]
@JoostK, Thank you 
But when I run `ng serve --aot`  or '`ng build --prod`' I get another error 

_ERROR in Child compilation failed:
Entry module not found: Error: Can't resolve 'E:\angular-test\ivy\test2\E:\angular-test\ivy\test2\src\app\app.component.html' in 'E:\angular-test\ivy\test2'_

I think there is a problem with the relative path

What must I do to fix that?

**Comment by JoostK** [comment]
I don't know, that looks like a legitimate bug.

**Comment by robwormald** [comment]
This code is *experimental*, undocumented, and highly likely to change before release. Please do not open issues (especially those of a how-to nature) related to Ivy until announce the preview. Thanks!

**Comment by darkguy2008** [comment]
Issue closed, but it's 21 Oct and I'm still getting the same issue:

```
ERROR in Child compilation failed:
Entry module not found: Error: Can't resolve 'C:\_git\uw-mfr-v2\dev\mfrweb\C:\_git\uw-mfr-v2\dev\mfrweb\src\app\app.component.html' in 'C:\_git\uw-mfr-v2\dev\mfrweb':
Error: Can't resolve 'C:\_git\uw-mfr-v2\dev\mfrweb\C:\_git\uw-mfr-v2\dev\mfrweb\src\app\app.component.html' in 'C:\_git\uw-mfr-v2\dev\mfrweb'
i ｢wdm｣: Failed to compile.
```

Ideas?

**Comment by JoostK** [comment]
@darkguy2008 ngtsc does not yet run on Windows.
