### ISSUE TITLE
Uncaught TypeError: token.toString is not a function

### ISSUE THREAD

**Issue by stanvanheumen** [angular/angular#25889]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When running my Angular app (v6.1.7) the application won't run in development mode (JIT mode).

## Expected behavior

The application should work properly.

## Minimal reproduction of the problem with instructions
The packages in the environment below cause this issue.

## What is the motivation / use case for changing the behavior?
The error is not clear enough to solve the problem.

## Environment

<pre><code>
Angular version: 6.1.7

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: v10.10.0
- Platform:  Mac
- Package manager: Yarn v1.9.4

Others:
{
    "dependencies": {
        "@agm/core": "^1.0.0-beta.3",
        "@angular/animations": "^6.1.7",
        "@angular/cdk": "^6.4.7",
        "@angular/common": "^6.1.7",
        "@angular/compiler": "^6.1.7",
        "@angular/core": "^6.1.7",
        "@angular/fire": "^5.0.0",
        "@angular/forms": "^6.1.7",
        "@angular/http": "^6.1.7",
        "@angular/platform-browser": "^6.1.7",
        "@angular/platform-browser-dynamic": "^6.1.7",
        "@angular/pwa": "^0.8.1",
        "@angular/router": "^6.1.7",
        "@angular/service-worker": "^6.1.7",
        "@swimlane/ngx-charts": "^9.0.0",
        "classlist.js": "^1.1.20150312",
        "core-js": "^2.5.7",
        "file-saver": "^1.3.8",
        "firebase": "^5.4.2",
        "html2canvas": "^1.0.0-alpha.12",
        "qrious": "^4.0.2",
        "rxjs": "^6.3.2",
        "xlsx": "^0.14.0",
        "zone.js": "^0.8.26"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "~0.8.1",
        "@angular/cli": "^6.2.1",
        "@angular/compiler-cli": "^6.1.7",
        "@angular/language-service": "^6.1.7",
        "@firebase/app-types": "^0.3.2",
        "@types/file-saver": "^1.3.0",
        "@types/html2canvas": "^0.0.33",
        "typescript": ">=2.7.2 <2.8"
    }
}
</code></pre>

**Comment by ericmartinezr** [comment]
>The packages in the environment below cause this issue.

You have 3rd libs. Reproduce the error with angular on its own and **provide a reproduction**, otherwise it's a problem with the libs and the error should be reported in their respectives repositories.

**Comment by stanvanheumen** [comment]
I've investigated some further. It seems that when upgrading the `@angular-devkit/build-angular` to version `~0.8.1` the compiler gives an error. Staying on version `~0.7.5` worked for me.

**Comment by mcm-ham** [comment]
I'm experiencing this too, in my case it's caused by importing a json:

```
import * as config from './config.json';
export const CONFIG = config;
```

This is the line of code that throws an error:
```
function stringify(token) {
    ...
    // WARNING: do not try to `JSON.stringify(token)` here
    // see https://github.com/angular/angular/issues/23440
    var res = token.toString();
    ...
}
```

Adding a toString function to the json object fixes the error for me.
