### ISSUE TITLE
Non-simple selectors should throw error

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2589]
```
@Directive({
  selector: 'parent child'
})
```

Should throw an error, since we don't support selectors which cross elements.

**Comment by jimthedev** [comment]
Should component selectors throw an error as well?

**Comment by vicb** [comment]
@jimthedev we want to be able to select any tag (not custom element only) - angular components and custom components are unrelated.

**Comment by jimthedev** [comment]
Ok thanks.

**Comment by filipbech** [comment]
should this be done on the selector or on the directive_parser?
render/dom/compiler/selector or in render/dom/compiler/directive_parser?

**Comment by vicb** [comment]
I guess the selector

**Comment by jimthedev** [comment]
Seems like we'd need to put it in DomCompiler.prototype.compileHost in render/dom/compiler/compiler as well so that it gets triggered when trying to bootstrap a component with a complex selector that we don't support.

**Comment by jimthedev** [comment]
@vicb @mhevery I am struggling with this but I think I am close.

The last problem is that angular2_material is using the exact kinds of selectors that we don't want to allow. Is there, or should there be, any exceptions for native form elements like those here? https://github.com/angular/angular/blob/master/modules/angular2_material/src/components/input/input.ts#L58

For more info, here is a build: Here is one of the builds: https://travis-ci.org/angular/angular/jobs/68923208

**Comment by mhevery** [comment]
That link (https://github.com/angular/angular/blob/master/modules/angular2_material/src/components/input/input.ts#L58) points to material design component, which is not correct. I believe the current code works because `md-input-container input` selector only uses `md-input-container` and ignores `input`.

**Comment by jimthedev** [comment]
Thanks for clarifying. I'll move this code to selector.ts and remove those complex selectors I find to get the tests passing.

**Comment by ggranum** [comment]
@mhevery After using the md-input as a demo and subsequently ending up here, I am fairly certain that the current md-input only works because it ignores the `md-input-container` and uses `input`. Which of course means it works fine so long... as you want all of your input elements to be md-input elements. If you want a 'naked' input element and a wrapped input element within the same component you're out of luck.

I haven't tested the following with md-input-container, but I'll bet a dollar it will fail with either a missing provider error or an NPE at 'container.register(...)':

```javascript
@View({
  directives: [MdInputContainer ],
  template: `
    <md-input-container>
        <input type="text" etc />
    </md-input-container>
    <div>
        <input type="text" etc />    <!-- boom -->
    </div>
    `
})
etc
```

An exception being thrown on use of complex selectors would have saved me a bit of time, but I (re) read the docs eventually.

**Comment by mhevery** [comment]
@jelbourn Can you comment on https://github.com/angular/angular/issues/2589#issuecomment-132786899 ?

**Comment by jelbourn** [comment]
@ggranum Yeah, the current md-input only "works" in that it hits _all_ input elements. The selector `md-input-container input` should just be throwing an error as this bug describes. The material components that are in the codebase now are mainly experiments and have other issues similar to this.

**Comment by mhevery** [comment]
In that case you should be using a `,` (comma) not a ' ' (space) between
the selectors. No?

**Comment by jelbourn** [comment]
@mhevery the current state of the selector was me checking "Does this work?", to which the answer was "no". I never bothered changing it because the whole component is going to be re-done.

**Comment by danielrasmuson** [comment]
If #3759 gets merged, it would be easy to check for a space in the provided selector, [check here](https://github.com/danielrasmuson/angular/blob/3464/modules/angular2/src/core/render/dom/compiler/selector.ts#L37).

**Comment by Andy1605** [comment]
Is there a good reason why "we don't want to support complex selectors"? It would be a great feature though. The lack of this feature forces me to still use jquery code hacks to support already existing views with complex selector based behavior as i pointed out in my proposal [#7278](https://github.com/angular/angular/issues/7278). It appears a bit senseless to me to write the behavior for my existing view components using jquery which will not do anything else as angular2 does anyways. Why not just support complex selectors and the world would be a better place!?

**Comment by pkozlowski-opensource** [comment]
This could be an easy fix but a conceptual pb needs to be resolved first, see: https://github.com/angular/angular/pull/9347#issuecomment-226988823

**Comment by alirezamirian** [comment]
I think not only it should throw an error, but also an explanation for "what subset of selectors are supported" is missing in the docs. The term "(css) selector" has precise meaning in the web community and people are not going to assume a subset of css selectors are going to work when [docs](https://github.com/angular/angular.io/blob/master/public/docs/ts/latest/guide/attribute-directives.jade#L77) say:

> `@Directive` requires a CSS selector to identify
  the HTML in the template that is associated with the directive

I'm almost sure a lot of developers are getting bit by this issue, specially the "parent child" selector not working and not throwing.

**Comment by splincode** [comment]
@mhevery Is the issue relevant? 
It is necessary to carry out this in codelyzer (tslint)?

**Comment by jelbourn** [comment]
This is still relevant. The framework should never silently accept an input that it does not support.

**Comment by splincode** [comment]
@jelbourn Perhaps this should be done by AST analyzers?

**Comment by jelbourn** [comment]
It's fine if a lint check catches this to work around this shortcoming, but ultimately this is an incorrect behavior in Angular that should be fixed.

**Comment by pkozlowski-opensource** [comment]
We've got a more broad issue that covers any invalid selector here: #6600 - closing as a duplicate.
