### ISSUE TITLE
docs: Universal Guide example - description mismatch

### ISSUE THREAD

**Issue by Gesh4o** [angular/angular#25909]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[*] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
The server side rendering guide [here](https://angular.io/guide/universal#universal-web-server) explains the basics of ExpressJS `server.ts` file. However there is a clear **mismatch** between the image provided and the description below.

<img width="1034" alt="guides-universal-template-engine-mismatch" src="https://user-images.githubusercontent.com/13942085/45369199-04130780-b5ee-11e8-8c52-61215e615a96.png">

## Expected behavior
I would expect the guide to correctly point out and explain different parts of the `server.ts`.

## Minimal reproduction of the problem with instructions
See the link above.

## What is the motivation / use case for changing the behavior?
I am getting started to server side rendering and I want to know more about it and understand how it works. This example is probably old and is a little confusing.

## Environment

<pre><code>
Angular version: 6.x.x

Browser:
- [*] All
 
For Tooling issues:
- Platform:  All
</code></pre>

Thank you for your time!

**Comment by jenniferfell** [comment]
https://angular.io/guide/universal#universal-web-server

**Comment by jenniferfell** [comment]
@jbogarthyde Is this clear enough and easy to fix while you're in the universal doc? If not, let's not get into scope creep on that CLI work; we'll keep this in our backlog. Thanks.

**Comment by jbogarthyde** [comment]
No, sorry, I don't understand this at all.

**Comment by jenniferfell** [comment]
@Gesh4o The Universal doc has been rewritten for v7. Does the rewrite address this issue? Please let us know if you find errors or omissions in the new v7 doc. Thanks!
#25752
https://next.angular.io/guide/universal

**Comment by Gesh4o** [comment]
No, it does not address the issue. These are minor (probably naming) mistakes but they looked confusing to me on first sight.

**Comment by deadandhallowed** [comment]
I agree with @jbogarthyde and @Gesh4o. The documentation as it stands is not sufficient for people new to Angular Universal. Having my own issues with the erroneous documentation is why I found this thread to begin with.

**Comment by jbogarthyde** [comment]
This doc has been completely rewritten (and is being further rewritten by https://github.com/angular/angular/pull/28231). 
This image is no longer part of the doc.
