### ISSUE TITLE
property 'URL' does not exist on window

### ISSUE THREAD

**Issue by Bridgeway** [angular/angular#25906]
I'm trying to implement file download functionality in Angular Six.

In my component I have a function called by the selected item of a drop down:

`this.callService.getEvidenceFile(event.target.value, true).subscribe(data => {

        var binaryData = [];
        binaryData.push(data);
        var downloadLink = document.createElement('a');
        downloadLink.href = window.URL.createObjectURL(new Blob(binaryData));
        document.body.appendChild(downloadLink);
        downloadLink.click();
      });

But URL isn't a property of window

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Bridgeway** [comment]
Apologies, a rogue import at the top of my file was being pulled in - 'window' from some thing or other - but not the actual DOM window!
Incidentally there appears to be a bug (at least in ng 6) where rogue imports, sometimes duplicates of what's already there gets pulled into the component when typing object names.

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter
