### ISSUE TITLE
I got this error on webconsole...while running an angular 6 project after build.

### ISSUE THREAD

**Issue by kavin1092** [angular/angular#25907]
The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by kavin1092** [comment]
StackOverflow link....https://stackoverflow.com/questions/52277358/i-got-this-error-while-running-an-angular-6-project-after-build

**Comment by kavin1092** [comment]
Any particular reason for that error....
