### ISSUE TITLE
"too much recursion" with angular and Jboss richfaces

### ISSUE THREAD

**Issue by Aduske** [angular/angular#25902]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I get an blank page and an error when I try to include the angluar js files (runtime.js, main.js etc.)
in a seam based application with richfaces on an xhtml page. 
The error:
too much recursion
DecoratorFactory  core.js:154
bind/<  http://localhost:8080/cleo/a4j/g/3_3_1.GA/org/ajax4jsf/framework.pack.js:76:26

## Expected behavior

The page show the angular element without failure. 

## Minimal reproduction of the problem with instructions

My problem: I want to use a angular element in the xhtml page of the legacy project. The structure of the project is based on seam with richfaces. Both angular and richfaces have a function "bind".  I think this is the issue for the recursion. But I don't know how to solve it. 
The element works in a jsf xhtml page wihout seam and richfaces.

## What is the motivation / use case for changing the behavior?

To migrate the old seam parts of a system to a angular based page.

## Environment

<pre><code>
Angular version: 6.1.5

Browser:
- [x] Chrome (desktop) version 68.0.3440.106 64bit
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 61.0.2 64bit
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.4  
- Platform:  Windows

Others:

</code></pre>

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter
