### ISSUE TITLE
When Using Reactive Forms, piping ValueChanges with DebounceTime(value > 0) presents weird behaviour with CombineLatest and returns nothing . Angular 6

### ISSUE THREAD

**Issue by ef32** [angular/angular#25910]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using valuechanges with debounceTime(value > 0), and then using the resulting variable within combine latest, the current value is not passed to the map function , it is either null or empty irrespective of any values you pass to the form control

## Expected behavior

I would expect that the behaviour would be as previous; passing the most current value after the debounce time elapses and executing the map function piped from the combinelatest resulting observable. 

## Minimal reproduction of the problem with instructions

*Steps To Reproduce*
- Create an input form control (although i use typeahead directive with mine...shouldnt matter, i have tested and it has nothing to do with the typeahead module).
- pipe Form control with debounceTime lettable operator.

- Create observable stream of search data (preferably any array of strings).
- use static combine latest and map to required result.

## Environment
Windows 7
<pre><code>
Angular version: 6.1.7
Below is my Component in this use case :

// Component (Shortened for Brevity)
---------------------------------------

export class SearchComponent implements OnInit, OnDestroy {
  searchTermCtrl: FormControl = new FormControl('');
  invalid = false;
  dataSource$: Observable<SuggestionsModel[]> = of([]);

  constructor(private searchItemsGetter: SearchItemsGetterService,
    private actionDispatcherService: ActionDispatcherService) {
  }

  ngOnInit() {
    const allData$ = this.searchItemsGetter.getMappedSearchItems$();
    const searchTerm$ =  this.searchTermCtrl.valueChanges.pipe(debounceTime(500));
    const getQueryAndData = combineLatest(searchTerm$, allData$);
    this.dataSource$ = getQueryAndData.pipe(
      map(queryandData => {
        let query = queryandData[0];
        const items = queryandData[1];
        query = query.trim().toLowerCase();
        return query === '' ? [] : items.filter(item => item.searchItem.toLowerCase().indexOf(query) !== -1);
      })
      );

  }
}

</code></pre>

**Comment by kara** [comment]
@ef32 Nothing has changed with the `valueChanges` observable in a while. If you remove your chain of operators (e.g. leaving only `valueChanges`), is the correct value being emitted? If yes, then there is probably a problem with the way the rxjs operators are being chained in your code (which the forms module doesn't directly affect). If you still feel there is a bug in forms, can you provide a minimal repro in Stackblitz where `valueChanges` doesn't emit properly?

**Comment by kara** [comment]
Since there isn't enough actionable info about this issue yet, I'm going to close it. If you can create a minimal repro for us to use down the line, please open a new issue.
