### ISSUE TITLE
Angular localhost server constantly reloading

### ISSUE THREAD

**Issue by mdewell** [angular/angular#25911]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am using Windows 10 and I have a development directory system on my D drive.  This is a separate drive from the hidden AppData directory, in my C drive User's directory.  I write my code, on the D drive directory, start the localhost server from there, and it appears to run fine, for a while, but after a random amount of time, it starts recompiling, and reloading pages.  I tried moving my development directory back to my C drive, into my user directory there, and started the ng serve from the C drive directory, and it runs fine, without reloading all the time.  I would think it would not matter where the code is at, but it appears to.

Note:  I did move my DOcuments, and other personal data directories, by windows procedures, to the D drive.  But I do not think this would matter.

## Expected behavior

I would hope that the web pages/TS code does not have to recompile constantly on a localhost server, when code is not on the same drive as the user's home directory.

## Minimal reproduction of the problem with instructions

Place code for angular site (localhost:4200) on D drive and start ng serve.  Go to the site and start working with the pages.

## What is the motivation / use case for changing the behavior?

Create a more functional development environment for Angular

## Environment

<pre><code>
Angular version:

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.0.8
Node: 8.11.3
OS: win32 x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.2.1
@angular/cli                      6.0.8
@angular/material                 6.2.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3

Browser:
- [ x ] Chrome (desktop) version 69.0.3497.81 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3  
- Platform:  Windows 10

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Please report angular-cli issues in its repo https://github.com/angular/angular-cli 👍

**Comment by mdewell** [comment]
Thanks.  I open an issue in Angular/CLI:  https://github.com/angular/angular-cli/issues/12240
