### ISSUE TITLE
Interpolation is broken on root nodes

### ISSUE THREAD

**Issue by rkirov** [angular/angular#2591]
A component with
```@View(template: `<other-cmp>{{text}}</other-cmp>`})``` does not interpolate text correcty (if fact it doesn't even throw).

However, 
```@View(template: `<other-cmp><div>{{text}}</div></other-cmp>`})``` works, which points to some indices being wrong. It is possible this is related to inserting shimmed CSS and breaking the element counts.

**Comment by vicb** [comment]
>  It is possible this is related to inserting shimmed CSS and breaking the element counts.

Might be related to removing style tags from the template (if using an emulated strategy)

**Comment by rkirov** [comment]
It is just odd that it affects the light dom, if a style tag is inserted the dom will looks like `<style></style><other-cmp></other-cmp>` so I am surprised that `<style></style><other-cmp><div></other-cmp>` fixes it.

**Comment by vicb** [comment]
Actually it should not affect `<other-cmp>{{text}}</other-cmp>` as other will have a `.ng-binding` class. whatever is appended does not matter.

It could affect `{{text}}` though.

**Comment by tbosch** [comment]
@vicb The removal of style elements is definitely a problem as well. And there are 2 cases: 1. when there `<style>` tag is inline, and 2. when the `<style>` tag needs to load an url.

In 1) we calculate the index of text node siblings incorrectly, with 2) we calculate the number of root nodes incorrectly (given the `<style>` is a root element)

**Comment by vicb** [comment]
This should all get fixed when #2563 gets merged - which should happen early next week.

**Comment by vicb** [comment]
More info:
#2563 will actually not this fix as styles will also get removed for emulated strategy.

Could it help to move the shadow DOM compile step to the first position ? The style would be removed before the indexes are computed. It was the case when this was first implemented. I'm not sure about why it has been moved ? @tbosch ?

**Comment by tbosch** [comment]
I have another idea how to make locating text nodes more stable. Will work
on it today...
