### ISSUE TITLE
angular animation: element unresponsive to changes to animated property

### ISSUE THREAD

**Issue by devonsams** [angular/angular#25914]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am animating the height of a div element from 0 to * and back inside of a MatMenu. When I first open the MatMenu, then toggle the animation state, the animation completes successfully.  But after closing the MatMenu and reopening, the div element no longer responds to changes to the height property, and although it does animate, it always reverts to open once the animation completes. The problem is currently happening for me in Chrome. I have also tested in Safari with the web-animations polyfil, but there the issue does not exist.

## Expected behavior

The element should properly animate, and remain in the correct state once animation is complete.

## Minimal reproduction of the problem with instructions

The bug is reproduced here: https://stackblitz.com/edit/angular-gitter-qixggm

## What is the motivation / use case for changing the behavior?

I would like animations to work correctly when performed inside of components like MatMenu, or https://github.com/ncstate-sat/popover

## Environment

<pre><code>
Angular version: 6.0.2

Browser:
- [x] Chrome (desktop) version 68.0.3440.106 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version 11.1.2 (13605.3.8)
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.4
- Platform:  Mac

Others:

</code></pre>

**Comment by dylhunn** [comment]
It would be interesting to see if this still happens in 14, but appears to still reproduce with the above StackBlitz.

**Comment by dylhunn** [comment]
Not reproducible with v14.
