### ISSUE TITLE
Lazy load modules block browsers

### ISSUE THREAD

**Issue by davidoween** [angular/angular#25929]
Animation spinner blocked  when loading module

Example: 
https://github.com/davidoween/lazy-load-block-UI

or 

https://stackblitz.com/edit/angular-lazy-loading-fpm83e?file=app%2Fapp.component.ts

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter
