### ISSUE TITLE
placing #var on item instead of template gets wrong value

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2592]
```
<div *directive #item>{{item}}</div>
```
de-suggars to:

```
<template directive>
  <div #item>{{item}}</div>
</template>
```
When we set `$implicit`
```
view.setLocal('$implicit', 'VALUE');
```

renders as: `<div>VALUE</div>`

But that is wrong, since the `#item` is on `div` not on `template` and therefore it should render as: `<div>ElementRef(...)</div>` because the `#item` is pointing to the element not to local variable.

**Comment by tbosch** [comment]
I think this was fixed yesterday bey Victor. See
d8e279536880968c6b3a83e00d29651006af5f46
