### ISSUE TITLE
How to create drag and drop of table cells into new space using angular 5

### ISSUE THREAD

**Issue by VandanaPareppady** [angular/angular#25922]
Hi all,

  I hope anyone would help me with this concept. 
 I need to create drag and drop of table cells into new space using angular 5. Similar, to the google spread sheets which has table creating button. If anyone knows this concept, please say me how to do it.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
