### ISSUE TITLE
"Cannot resolve all parameters" with AOT

### ISSUE THREAD

**Issue by no-more** [angular/angular#25923]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

According to my researches this issue is not the same as existing ones even if the error message is the same (#22532,  #22244 ...)

## Current behavior

When project is run with `ng serve --aot` I have the following error in the browser :
```
09:32:05.275 main.ts:9 pre-test
09:32:05.277 test.1.ts:46 step 1
09:32:05.278 core.js:1926 Uncaught Error: Cannot resolve all parameters for 'CustomProvider'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'CustomProvider' is decorated with Injectable.
    at noAnnotationError (core.js:1926)
    at _dependenciesFor (core.js:2256)
    at resolveReflectiveFactory (core.js:2157)
    at resolveReflectiveProvider (core.js:2180)
    at Array.map (<anonymous>)
    at resolveReflectiveProviders (core.js:2187)
    at Function.push../node_modules/@angular/core/fesm5/core.js.ReflectiveInjector.resolve (core.js:2384)
    at Function.push../node_modules/@angular/core/fesm5/core.js.ReflectiveInjector.resolveAndCreate (core.js:2410)
    at test (test.1.ts:47)
    at Module../src/main.ts (main.ts:10)
noAnnotationError @ core.js:1926
_dependenciesFor @ core.js:2256
resolveReflectiveFactory @ core.js:2157
resolveReflectiveProvider @ core.js:2180
resolveReflectiveProviders @ core.js:2187
push../node_modules/@angular/core/fesm5/core.js.ReflectiveInjector.resolve @ core.js:2384
push../node_modules/@angular/core/fesm5/core.js.ReflectiveInjector.resolveAndCreate @ core.js:2410
test @ test.1.ts:47
./src/main.ts @ main.ts:10
__webpack_require__ @ bootstrap:78
0 @ test2.ts:15
__webpack_require__ @ bootstrap:78
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
```

## Expected behavior

I should have the same output I have in JIT
```
09:40:34.742 main.ts:9 pre-test
09:40:34.743 test.1.ts:46 step 1
09:40:34.745 test.1.ts:53 step 2
09:40:34.746 test.1.ts:10 LocalBaseClass _injector ReflectiveInjector_ {_constructionCounter: 1, _providers: Array(4), parent: null, keyIds: Array(4), objs: Array(4)}
09:40:34.748 test.1.ts:11 LocalBaseClass this._injector ReflectiveInjector_ {_constructionCounter: 1, _providers: Array(4), parent: null, keyIds: Array(4), objs: Array(4)}
09:40:34.749 test.1.ts:55 step 3
09:40:34.749 test2.ts:11 ExternalBaseClass _injector ReflectiveInjector_ {_constructionCounter: 3, _providers: Array(4), parent: null, keyIds: Array(4), objs: Array(4)}
09:40:34.750 test2.ts:12 ExternalBaseClass this._injector ReflectiveInjector_ {_constructionCounter: 3, _providers: Array(4), parent: null, keyIds: Array(4), objs: Array(4)}
09:40:34.751 test.1.ts:57 step 4
09:40:34.751 main.ts:11 post-test
09:40:34.846 core.js:3123 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
```

## Minimal reproduction of the problem with instructions

I have attached a demo project.
In order to create this project I used `ng` cli to bootstrap the project, then added files `test.1.ts` and `test.2.ts`.
And an simple call to `test()` function from `main.ts`

[test3.zip](https://github.com/angular/angular/files/2373695/test3.zip)

## Environment

<pre><code>
Angular version: ^6.1.0

Browser:
- [X] Chrome (desktop) version 68.0.3440.106
- [ ] Chrome (Android) version ^6.1.0
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.4  
- Platform:  Windows 10

 

Others:

</code></pre>

**Comment by vikram06** [comment]
This not issue.check your code or share your code

**Comment by no-more** [comment]
I have included a zip file in the original request containing a minimal project that reproduce the error.
The project works fine without AOT, and does not produce any compiling error with AOT, but generate an error in the browser when AOT is used for compilation. 

Thanks for your help.

**Comment by no-more** [comment]
Thanks but I don't know how to create a plunker with AOT. Plunker is great tool for code issue, here I think the issue might be related to the compiler (ngc + aot in this case).

**Comment by mlc-mlapis** [comment]
@no-more ... nobody will download a foreign ZIP file. So still create that Plunker demo even if the error wouldn't be seen, because of the source code shows the mistake. From 99,9% it's your mistake.

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists please open a new issue following [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue).
