### ISSUE TITLE
Simple typo at https://angular.io/api/forms/FormArray#parameters

### ISSUE THREAD

**Issue by geoyws** [angular/angular#25921]
[FormArray Documentation](https://angular.io/api/forms/FormArray#parameters)
"where" is spelt as "wheh"

**Comment by jenniferfell** [comment]
https://angular.io/api/forms/FormArray#parameters

**Comment by FrederikSchlemmer** [comment]
@geoyws Would you like to work on this issue or could I take over?

**Comment by FrederikSchlemmer** [comment]
@brandonroberts This issue can be closed because the pull request is merged.
