### ISSUE TITLE
Every time i have to re-compile the code if i refer to a new image from assets folder

### ISSUE THREAD

**Issue by aakashjangid** [angular/angular#25936]
## I'm submitting a Issue regarding img tag

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have some image paths from db which is coming on Angular side dynamically. Every time there is a new image, I have to re-compile the angular code other wise it gives 404 Resource Not Found error. This is really annoying.

## Expected behavior

Ideally there must be no need to re-compile the code for every new image.

## What is the motivation / use case for changing the behavior?

If we have <img /> tag in our html file and it is getting image src dynamically, so for every new image we have to re-compile the code and then it will get the image, otherwise it will give 404 Resource Not Found error.

## Environment

<pre><code>
Angular version: 6.1.5

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.4  
- Platform: Windows 

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@aakashjangid ... sounds strange. Do you mean that the image name is different or what?

**Comment by aakashjangid** [comment]
@mlc-mlapis ... i am uploading an image from angular side and that image is being stored in assets folder by backend code. Once the image is added the page will be reloaded and it has to show image. 

But rather than showing image, it is giving 404 Not found error

**Comment by aakashjangid** [comment]
Hi,

@mlc-mlapis <https://github.com/mlc-mlapis> ... i am uploading an image
from angular side and that image is being stored in assets folder by
backend code. Once the image is added the page will be reloaded and it has
to show image.

But rather than showing image, it is giving 404 Not found error.

**Comment by mlc-mlapis** [comment]
@aakashjangid ... so it sounds that your backend code is saving the uploaded image under a different name, so it's logical that if the client code expects some URL (including the file name) for that image, the 404 is returned because of the location of that file is different.

It's not related to Angular at all probably.

**Comment by skreborn** [comment]
> i am uploading an image from angular side and that image is being stored in assets folder by backend code

> for every new image we have to re-compile the code and then it will get the image

@mlc-mlapis Might be silly, but this sounds to me like @aakashjangid is trying to save the user-uploaded images inside the backend's `src/assets` folder, which will in turn be moved to the compiled application's `assets` folder when it's recompiled.

**Comment by mlc-mlapis** [comment]
@skreborn ... you are probably right ... I was just guessing what leads to the 404 error - finally, the file is saved on a totally wrong place. 😃

**Comment by gkalpak** [comment]
It would help if we had a minimal reproduction to look at (e.g. a standalone repo we can check out and investigate) :wink:

**Comment by skreborn** [comment]
> i am saving the image in angular’s src/assets

@aakashjangid That is exactly your problem. **You should NOT save it to `src/assets`**, as that is merely the source of your application. You should save it directly to the compiled and deployed application's own `assets` folder.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Not related to angular. Barely likely to be angular-cli's issue.
