### ISSUE TITLE
Fix typo in Bootstrapping guide

### ISSUE THREAD

**Issue by michaelnease** [angular/angular#25938]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Incorrect use of "chose" on [page](https://angular.io/guide/bootstrapping#the-imports-array)
"But you will create some before long and you may chose to provide many of them here."

## Expected behavior

"But you will create some before long and you may **choose** to provide many of them here."

## Minimal reproduction of the problem with instructions
Go to this [page](https://angular.io/guide/bootstrapping#the-imports-array) and find the last sentence in "The Imports Array" section.

## What is the motivation / use case for changing the behavior?

Clarity in the docs. 

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX

**Comment by jenniferfell** [comment]
https://angular.io/guide/bootstrapping#the-imports-array

**Comment by jenniferfell** [comment]
@GavinSong123 Thanks for opening this issue and starting a fix. If you'd like, you're welcome to contribute your fix directly as a PR (https://github.com/angular/angular/blob/master/CONTRIBUTING.md)?

**Comment by GavinSong123** [comment]
@jenniferfell I have committed and opened a PR.

**Comment by jenniferfell** [comment]
@GavinSong123 Thanks. Oh, I see that now above. (oops)

I approved the PR. Watching now to see if it passes all CI tests. Thanks again!
