### ISSUE TITLE
Feature request: Router navigateById

### ISSUE THREAD

**Issue by glebmachine** [angular/angular#25930]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[v] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Unable to restore previous history state by NavigationId

## Expected behavior
Able to navigate to previous state simply by it's id.

Will be great to have router method `navigateById`

## What is the motivation / use case for changing the behavior?
You added `id` to router.events, to determine states history.
You added restoredState to NavigationStart to determine restoration of previous router states.
But, there is no option to navigate by this id.

**Comment by dawidgarus** [comment]
You can easily implement it yourself. Just store url in map when NavigationEnd occurs and use it get url from id:
```typescript
export class MyRouter {
  private map: { [id: string]: string } = {};
  constructor(private router: Router) {
    router.events.subscribe(event => {
      if (event instanceof NavigationEnd) {
        this.map[event.id] = event.urlAfterRedirects;
      }
    });
  }
  navigateById(id: string): Promise<boolean> {
    const url = this.map[id];
    if (url) {
      return this.router.navigateByUrl(url);
    } else {
      return Promise.reject(new Error(`Cannot find URL for id "${id}"`));
    }
  }
}
```

**Comment by glebmachine** [comment]
No I don’t because I will got new Id, not restored one.
-- 
Gleb Mikheev
CTO

*Beta Digital Production*
Bersenevsky Lane 5 Building 1

Mobile:  +7 (916) 118-28-21
Telegram: https://t.me/glebmikheev

www.betaagency.ru
www.facebook.com/betadigitalproduction

**Comment by glebmachine** [comment]
I would like to restore exact state, not navigate to previous url again
-- 
Gleb Mikheev
CTO

*Beta Digital Production*
Bersenevsky Lane 5 Building 1

Mobile:  +7 (916) 118-28-21
Telegram: https://t.me/glebmikheev

www.betaagency.ru
www.facebook.com/betadigitalproduction

**Comment by dawidgarus** [comment]
@glebmachine It's still possible to do it yourself. I know because I've done that before, sadly I cannot share code. You would need to provide your own `LocationStrategy`, keep a stack with navigation ids which would be manipulated accordingly on pushState/replaceState/popState/NavigationEnd (really tricky to do it right) and use `window.history.go` - the stack will provide information how far You want to go.

**Comment by glebmachine** [comment]
Not bad, thank you!)

But, i still believe that router state restoration - is great idea, and implementation is incomplete without this method.

@vsavkin could you please take a look, is it related to angular router design or should implemented outside router? You opinion will be very appreciated

**Comment by jasonaden** [comment]
At this point it should be implemented outside the router. While it's a cool idea, it's not something everyone needs and adding this type of custom behavior is best done in packages that don't add to the already large bundle size of the core router.

If you would like to open-source the solution, it could be useful to others. Thanks for the discussion!
