### ISSUE TITLE
Allow `providedIn` in `@Pipe` decorator.

### ISSUE THREAD

**Issue by tytskyi** [angular/angular#25943]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Building error
```
Argument of type '{ name: string; provideIn: string; }' is not assignable to parameter of type 'Pipe'.
  Object literal may only specify known properties, and 'provideIn' does not exist in type 'Pipe'.
```

## Expected behavior
Possible to declare pipe the same way as `@Injectable()` is declared.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-gitter-ewzerg?file=app%2Ftest.pipe.ts

```typescript
import {Pipe, PipeTransform} from "@angular/core";

@Pipe({
  name: "test",
  provideIn: "root",
})
export class TestPipe implements PipeTransform {
  public transform(value: any): string {
    return "";
  }
}
```

## What is the motivation / use case for changing the behavior?

Pipe already can be used as a service. I expect it to be possible to declare the same way.

## Environment

<pre><code>
Angular version: 6.1.7

Browser:
N/A
 
For Tooling issues:
N/A

Others:
N/A

**Comment by dawidgarus** [comment]
That would be impossible for the same reason why components and directives don't have `providedIn`. Such pipe wouldn't not be imported by any module and would not be part of a compilation. How JIT compiler would know that when he encounters pipe "test" in template it should be `DefaultDatePipe`?

**Comment by tytskyi** [comment]
@dawidgarus yes, you are correct
