### ISSUE TITLE
ServiceWorker notification not working on mobile

### ISSUE THREAD

**Issue by MuhoX** [angular/angular#25949]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When update is available, and user navigates or after a certain time, I want to show a notification that there is a new version and user can refresh the page. This all works fine in the desktop browser and android, but on iOS it's not working at all. I couldn't find anything with google, so I thought it was a bug.

## Expected behavior

I want it to work on iOS as well.

## Minimal reproduction of the problem with instructions

In my AppComponent NgOnInit:
``
 this.swUpdate.checkForUpdate();

        this.swUpdate.available.subscribe(event => {
            this.snackBar.open(`Er is een nieuwe versie van de app beschikbaar, wilt u updaten?`, 'Ja graag!')
                .onAction()
                .subscribe(() => {
                    this.swUpdate.activateUpdate()
                        .then(() => document.location.reload());
                });
        });
``

And I also made the services from the documentation page of SW angular: check-for-update.service, prompt-update, log etc.

## What is the motivation / use case for changing the behavior?

The user needs to be able to see a notification if there is a new version.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [X ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [X] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by danwulff** [comment]
@MuhoX This is a limitation with iOS's implementation of service worker at the moment.

You can see that other people are having this issue here: https://stackoverflow.com/questions/51435349/my-pwa-web-app-keep-showing-old-version-after-a-new-release-on-safari-but-works
There is a solution that someone gave here (but it doesn't provide a particular implementation): https://stackoverflow.com/questions/52221805/any-way-yet-to-auto-update-or-just-clear-the-cache-on-a-pwa-on-ios/52238757#52238757

Good luck (and please report back if you get it working!)

**Comment by gkalpak** [comment]
It is not clear what is not working at all, but it sounds like this is a Safari bug, not an Angular one.
Closing, but feel free to continue the discussion below.
