### ISSUE TITLE
Tour of Heroes - First part (pt0) is missing

### ISSUE THREAD

**Issue by luissevergnini** [angular/angular#25946]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Tour of Heroes tutorial is missing its first part: "The Application Shell", which is located at https://angular.io/tutorial/toh-pt0.

This step of the tutorial cannot be found in its current version, at least not before Step 2 (when you are required to style the heroes list). I noticed something was missing when I was required to generate a component when I still had not created the app.

I figured how to do it because I checked the "Getting started" page, but it may confuse others.

![toh](https://user-images.githubusercontent.com/7772075/45487758-a7baff80-b735-11e8-9643-6e1d4359ec8f.PNG)

## Expected behavior

Since the tutorial's introduction does not explain how to create the project, Step 0 should be placed between "Introdution" and "The Hero Editor" steps.

**Comment by ericmartinezr** [comment]
Did you try cleaning your cache?

**Comment by luissevergnini** [comment]
@ericmartinezr Now that you've mentioned, I cleaned it. "The Application Shell" now appears between the Introduction and The Hero Editor. 

Thanks.

P.S.: how could that be? I don't remeber accessing it before, so how could it be a caching problem?
