### ISSUE TITLE
Cannot set variable from subscribe in router events

### ISSUE THREAD

**Issue by rkulinski** [angular/angular#25941]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

```
  ngOnInit() {
    this.prevRoute = 'init';
    this.router.events.pipe(
      filter((e: any) => e instanceof RoutesRecognized),
      pairwise(),
      map((lastRoutes: RoutesRecognized[]) => lastRoutes[0].urlAfterRedirects),
      first(),
    ).subscribe(prevRoute => {
      this.prevRoute  = prevRoute;  // e.g. = '/prev_route'
    });
   
   console.log(this.prevRoute); // here gives 'init' once again.
   ...
  }
```

`this.prevRoute` is set inside subscribe but once it 'goes out' of the subscribe the value is forgotten.

## Expected behavior
Be able to set outer scope variables from `subscribe`.

## Minimal reproduction of the problem with instructions
Use code from above.

## What is the motivation / use case for changing the behavior?
This supposed to be possible.

## Environment
develop (after ng serve)

```
    "@angular/animations": "^6.1.7",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.1.7",
    "@angular/compiler": "^6.1.7",
    "@angular/core": "^6.1.7",
    "@angular/forms": "^6.1.7",
    "@angular/http": "^6.1.7",
    rxjs@^6.3.2,
```
Browser:
- [x] Chrome (desktop) version 69.0.3497.92
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version 11.2
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by ericmartinezr** [comment]
This has nothing to do with angular

<hr>

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by rkulinski** [comment]
Quite strong opinion especially if you didn't point out what's the reason behind that ;)

IMO - I'm not sure if this has nothing to do with angular. This is "Angular way" of "handling" navigation stack. Recommended by one of the contributors:
https://github.com/angular/angular/issues/11268

Router and event comes from Angular. So I would guess that something weird must be happening inside this event.

**Comment by ericmartinezr** [comment]
@rkulinski if it is a valid bug then you should report it (make sure to look if it exists already a report, to avoid duplicated reports). The problem is that this issue isn't related to your last comment. Also, provide a reproduction of the bug (you can use this to do it https://stackblitz.com/edit/angular-p5gpvv).
