### ISSUE TITLE
[Feature Request] Async methods in renderer to manipulate DOM.

### ISSUE THREAD

**Issue by michaeljota** [angular/angular#25951]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The current renderer, `Renderer2`, has methods to perform DOM manipulation. I think this methods wanted to resemble the DOM standard methods, but at the end of the day, DOM manipulation happens kind of an asynchronous way. 

## Expected behavior

By providing this methods as async methods, certain edge cases could be handled more easily. Methods such `appendChild` or `removeChild`, are being executed immediately, but the element is not created immediately. This depends upon what element are being created, as most common elements would only need a single frame to be renderer, but some complex elements, such `iframes`, needs some time to be created and fulfilled.

If `appendChild` had an counterpart as a async method, that emits and completes (rxjs) or resolves (promises) when the element is already finish the creation, you could do manipulations to that element in a straight forward way. Knowing if when the element is finished creating is specially useful when you want to send a message to an `iframe`. 

## What is the motivation / use case for changing the behavior?

A better API to manage DOM manipulation. I know that this shouldn't be something the developer should do, but its something that we usually do anyway. 

## Environment

```shell
Angular CLI: 1.6.3
Node: 8.11.2
OS: win32 x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

**Comment by splincode** [comment]
relative: https://github.com/angular/angular/issues/19030

**Comment by mhevery** [comment]
Will not implement.
