### ISSUE TITLE
Make archived banner on AIO pages for older versions more prominent

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#25968]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
The first result for `angular webpack` in google yields this https://v5.angular.io/guide/webpack

This is an archived page, however it is not clearly visible as apart from the different color of the layout, there is only a small note at the top which might get lost in a lot of text.
<img width="1598" alt="screen shot 2018-09-14 at 17 17 47" src="https://user-images.githubusercontent.com/17563226/45559202-2309d780-b842-11e8-8d86-66e48e8f0f4f.png">

## Expected behavior

IMHO I suggest that such archived pages should have a more distinctive/ eye caching message that indicates that this page is archived, for instance something like;

<img width="1598" alt="screen shot 2018-09-14 at 17 25 01" src="https://user-images.githubusercontent.com/17563226/45559578-25206600-b843-11e8-9edb-2a90f2b785a4.png">

**Comment by petebacondarwin** [comment]
Related to #21312
