### ISSUE TITLE
How do I use `pug` template in angular 6 project

### ISSUE THREAD

**Issue by fengxinming** [angular/angular#25960]
## I'm submitting a...
I changed `app.component.html` as `app.component.pug` and modified that content, on terminal it showed
```bash
ERROR in ./src/app/app.component.pug 4:14
Module parse failed: Unexpected token (4:14)
You may need an appropriate loader to handle this file type.
| div(style='text-align:center')
|   h1
>     | Welcome to {{ title }}!
|   img(width='300', alt='Angular Logo', src='data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==')
| h2 Here are some links to help you start:
ℹ ｢wdm｣: Failed to compile.

```

## Current behavior
Module parse failed: Unexpected token
 ｢wdm｣: Failed to compile.

## Expected behavior
 ｢wdm｣: Compiled successfully.

## Environment

<pre><code>
Angular version: 6.1.0
 
For Tooling issues:
- Node version: 8.11.1
- Platform:  Mac

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/20147

<hr>

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by fengxinming** [comment]
@ericmartinezr you all didn't resolve this issure, I have checked `/Users/jesse/workspace/ng-demo/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js`, there are not any config about `pug`

**Comment by fengxinming** [comment]
@dawidgarus I directly use `@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js`

**Comment by ericmartinezr** [comment]
There's no issue to be resolved here. Like @dawidgarus pointed out, you need a loader for pug files, meaning you either google a solution or your write your own, but angular doesn't provide one and like it is mentioned in the issue I linked (the one you didn't read)

>Anyway as said might be something to consider as a build step but it will never be supported by the core itself.

**Comment by fengxinming** [comment]
@ericmartinezr I don't understand why you all support `sass`, `stylus`, `less` those style templates, but you didn't support `pug` in `@angular-devkit`.

**Comment by dawidgarus** [comment]
@fengxinming Is not as easy as adding new loader to have support for pug. Language service should also have a support for pug and that's way more work. If you want to use pug with angular, you will be missing cool features like autocompletion and navigation in templates.
Also I don't think that `@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js` is meant to be used directly. Use `@ngtools/webpack` to create Your own webpack config or if you insist use tools like `webpack-merge` to extend webpack config and add custom loaders to it.

**Comment by benlesh** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by fengxinming** [comment]
@benlesh anyway, thank you for the suggestion, I suppose it is time to migrate `angular` to `vue`.

**Comment by sinsunsan** [comment]
you have a working loader for pug + angular https://www.npmjs.com/package/ng-cli-pug-loader
