### ISSUE TITLE
View query documentation does not match reality

### ISSUE THREAD

**Issue by jonrimmer** [angular/angular#25961]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

[The current documentation says](https://angular.io/api/core/ViewChild) that `@ViewChild()` view queries are set "before the ngAfterViewInit callback is called". While this is technically true, in at least some cases view queries are actually set much earlier in the lifecycle, before the OnInit lifecycle callback is called (see the example below for proof).

## Expected behavior

There is a significant difference between the OnInit an AfterViewInit lifecycle callbacks: The latter runs after change detection has finished, and attempting to use the results of a view query will often result in ExpressionChangedAfterItHasBeenChecked errors, requiring extra complexity be introduced to do things in an asynchronous manner.

Therefore, there is often a strong motivation to use view query results in OnInit, if they are available. But is this supported behaviour? Can it be relied upon? The developer is put in a difficult position where the simplest solution runs counter to what the documentation suggests should work.

If this is not supported behaviour, it seems like the framework should, at the very least, print a warning of some kind indicating that it is unsupported and could break in a future release. If it is supported behaviour, the documentation should say so, so that the developer has more confidence that the solution arrived upon is safe.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-9f1q8j?file=src%2Fapp%2Fapp.component.ts

## What is the motivation / use case for changing the behavior?

Because of the helpfulness of early access to view query results, as described above, there is likely to be a large and increasing amount of extant code that inadvertently relies upon view queries being set in OnInit. If the framework ever changes so that view queries are never available in OnInit, this code will break. Conversely, if this will not change in future, knowing so will allow developers to confidently use view queries in simpler way.

## Environment

<pre><code>
Angular version: 6.1.7
</code></pre>

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/21800

**Comment by jonrimmer** [comment]
:+1:
