### ISSUE TITLE
currencyPipe`s result was dislocation when the number is minus

### ISSUE THREAD

**Issue by SubinY** [angular/angular#25973]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

#### template use the CurrencyPipe
![image](https://user-images.githubusercontent.com/21135159/45583695-683d1080-b8f9-11e8-9617-d8c07e2c8231.png)
#### result
![image](https://user-images.githubusercontent.com/21135159/45583703-8276ee80-b8f9-11e8-8a98-5b97fda505af.png)

## Expected behavior
the minus should be renderd before the number, but not now

## Environment
<pre><code>
Angular version: 6+

**Comment by manklu** [comment]
The formatting of the number depends on the used locale.

https://stackblitz.com/edit/angular-diyta9

**Comment by SubinY** [comment]
thx manklu. I get the solution to  resolve this issue depend on your stackblitz code


```
<span class="total-fee">￥{{_extraField.totalFee | currency:'CNY':'':'0.2-2'}}</span>
```
