### ISSUE TITLE
sockjs error when using deploy-url, base-href build options

### ISSUE THREAD

**Issue by jtal** [angular/angular#25972]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

After setting deployUrl and baseHref, a repetitive 404 (Not Found) error is produced in the browser. Something appears to be requesting /sockjs-node/info without considering deployUrl/baseHref.

## Expected behavior
The request should be made to $deployUrl/sockjs-node/info. No 404 errors.

## Minimal reproduction of the problem with instructions

1. Create & serve an app:

`ng new my-app`
`cd my-app`
`ng --deploy-url "/myapp/" --base-href "/myapp/" serve`

2. Create a proxy for /myapp location (I'm using nginx):

> location /myapp {
> proxy_set_header  X-Real-IP $remote_addr;
> proxy_set_header  Host      $http_host;
> proxy_pass        http://localhost:4200;
> }

3. Open Chrome (and dev console) and visit http://localhost/myapp

## What is the motivation / use case for changing the behavior?

A user wants their website to be made of multiple projects listening on different ports behind a proxy.

## Environment
<pre><code>
Angular version: 6.1.7

Browser:
- [x ] Chrome (desktop) Version 65.0.3325.146 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.8.0   
- Platform: Linux 

Others:

nginx version: nginx/1.10.3 (Ubuntu)
OS: Ubuntu 16.04.4 LTS
</code></pre>

Thanks!

**Comment by trotyl** [comment]
Please report the issue to https://github.com/angular/angular-cli, and provides the minimal reproduction.
