### ISSUE TITLE
Bootstrapping section alludes to referencing services in imports array

### ISSUE THREAD

**Issue by Lx** [angular/angular#25978]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The last paragraph of the [“The `imports` array” section of the docs](https://angular.io/guide/bootstrapping#the-imports-array) says:

> You don't have any services to provide yet. But you will create some before long and you may choose to provide many of them here.

## Expected behavior

I expect that this line actually belongs in the following section, entitled [“The `providers` array”](https://angular.io/guide/bootstrapping#the-providers-array).

## Minimal reproduction of the problem with instructions

Read documentation sections linked above.

## What is the motivation / use case for changing the behavior?

More accurate documentation.

## Environment

<pre><code>
Angular version: 6.0.6-build.45561+sha.aa66e84

Browser:
- [x] Chrome (desktop) version 68.0.3440.106 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kapunahelewong** [comment]
Great catch @Lx. Fixed and PR submitted. I decided to remove it altogether because that sentence was in the context of when it was in a larger series of steps in which the reader would add services later. Now it is more of a reference with steps like that being more in line with the Tour of Heroes. Good eye! :)

**Comment by dariobraun** [comment]
Looks like this issue can be closed?

**Comment by kapunahelewong** [comment]
Yes, thank you @dariobraun 🙂
