### ISSUE TITLE
Date format 'shortDate' in different locales

### ISSUE THREAD

**Issue by AlexDonn19** [angular/angular#25982]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[x] Other... Please describe: format of "shortDate" in different locales
</code></pre>

## Current behavior

There is some difference in "shortDate" format in uk.ts and ru-UA.ts
In the first one it is 'dd.MM.yy', in the second - 'dd.MM.y'.

## Expected behavior

It would be better to have one standart like 'dd.MM.y'
The right shortening of "Ukraine" is "UA", not "UK"

## What is the motivation / use case for changing the behavior?

It would be better to have one standart 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version All
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: All  
- Platform: All 

Others:

</code></pre>

**Comment by AlexDonn19** [comment]
https://github.com/angular/angular/blob/master/packages/common/locales/uk.ts
https://github.com/angular/angular/blob/master/packages/common/locales/ru-UA.ts

**Comment by trotyl** [comment]
The formats are defined by Unicode CLDR:

https://github.com/unicode-cldr/cldr-dates-full/blob/master/main/uk/ca-generic.json#L308
https://github.com/unicode-cldr/cldr-dates-full/blob/master/main/ru-UA/ca-generic.json#L309

If you believe it's incorrect, please raise a ticket there.

**Comment by ocombe** [comment]
Hello, @trotyl is right, we use the formats defined by CLDR which is the standard that everyone uses. Still sometimes they make mistakes, if you think this is one, you can open a ticket at the link given above.

**Comment by AlexDonn19** [comment]
thanks
