### ISSUE TITLE
bypassSecurityTrustResourceUrl give access denied for PDF on Edge browser

### ISSUE THREAD

**Issue by almgwary** [angular/angular#25980]
## I'm submitting a...
<pre><code>
[x] Bug report  
</code></pre>

## Current behavior
Can't open PDF file, `bypassSecurityTrustResourceUrl` give access denied for PDF on Edge browser

## Expected behavior
Should  view PDF file

## Minimal reproduction of the problem with instructions

This line  produce the issue

`<object  [data]="pdfURL | safeUrl" > </object>`

This line working ok
it works if PDF URL already written in the html
`<object  data="https://pdfobject.com/pdf/sample-3pp.pdf" > </object>`

this is the safeUrl pipe

```
@Pipe({ name: 'safeUrl'})
export class SafeUrlPipe implements PipeTransform  {
  constructor(private sanitized: DomSanitizer) {}
  transform(value) {
    return this.sanitized.bypassSecurityTrustResourceUrl(value);
  }
}
```
## Environment

<pre><code>
Angular CLI: 6.1.1
Node: 8.11.3
OS: win32 x64
Angular: 4.4.7
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, tsc-wrapped

Browser:
- [x ] Edge version Default
 
For Tooling issues:
- Node version: XX  
- Platform:  Windows 

Others:
</code></pre>

**Comment by manekinekko** [comment]
@almgwary Your issue requires a StackBlitz reproducing the problem.
Please create a StackBlitz using this template: https://stackblitz.com/fork/angular-gitter

**Comment by almgwary** [comment]
Following link is my question at stackoverflow

 [get-access-denied-for-pdf-bypasssecuritytrustresourceurl-on-edge-browser](https://stackoverflow.com/questions/52364931/get-access-denied-for-pdf-bypasssecuritytrustresourceurl-on-edge-browser)

And here an [answer](https://stackoverflow.com/a/52367366/6786941) says: 

```

As per the https://stackoverflow.com/questions/36725764/pdf-viewer-using-object-tag-not-working-for-edge

We need to set the data attribute using DOM elementRef.

**Template:**

  

    <object [data]="pdfurl | safeUrl" #pdfobject></object>

**Component:**

    @ViewChild('pdfobject') pdfobject: ElementRef;
    this.pdfobject.nativeElement.setAttribute('data', 'https://pdfobject.com/pdf/sample-3pp.pdf');

```
i will check it when have time

**Comment by petebacondarwin** [comment]
This is an issue with MS Edge - see https://github.com/microsoft/ChakraCore/issues/903
Your `safeUrl` pipe (and Angular) is working correctly.

I created a repro on Stackblitz here https://stackblitz.com/edit/ivy-7edrgu?file=src%2Fapp%2Fapp.component.html

You can see that on Chrome it displays the PDF twice.  On Edge, only once.

I also tried out the approach above but to no avail: https://stackblitz.com/edit/ivy-ytwurx?file=src%2Fapp%2Fapp.component.html

From what I read in StackOverflow your only option is to create the element dynamically with the data attribute already set.

**Comment by petebacondarwin** [comment]
Closing as this is not a bug in Angular, but one in Edge.
