### ISSUE TITLE
Auxilary routing not working in lazy loading - Angular 6.1.7

### ISSUE THREAD

**Issue by LTAravindh** [angular/angular#25985]
I'm facing below console error when try to use named routlet. 

> ERROR
> Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'lazy/aux1'
> Error: Cannot match any routes. URL Segment: 'lazy/aux1'
> at ApplyRedirects.noMatchError (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/@angular/router@6.1.7/bundles/router.umd.js:1455:20)
> at CatchSubscriber.eval [as selector] (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/@angular/router@6.1.7/bundles/router.umd.js:1436:33)
> at CatchSubscriber.error (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/rxjs@6.3.2/internal/operators/catchError.js:48:31)
> at MapSubscriber.Subscriber._error (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/rxjs@6.3.2/internal/Subscriber.js:96:26)
> at MapSubscriber.Subscriber.error (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/rxjs@6.3.2/internal/Subscriber.js:74:18)
> at MapSubscriber.Subscriber._error (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/rxjs@6.3.2/internal/Subscriber.js:96:26)
> at MapSubscriber.Subscriber.error (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/rxjs@6.3.2/internal/Subscriber.js:74:18)
> at MapSubscriber.Subscriber._error (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/rxjs@6.3.2/internal/Subscriber.js:96:26)
> at MapSubscriber.Subscriber.error (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/rxjs@6.3.2/internal/Subscriber.js:74:18)
> at TapSubscriber._error (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/rxjs@6.3.2/internal/operators/tap.js:75:26)

Please find the sample link here.
https://stackblitz.com/edit/lazy-load-auxilary-b7vpg-e2ax7j

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter
