### ISSUE TITLE
Lazy loading auxilary issue

### ISSUE THREAD

**Issue by LTAravindh** [angular/angular#25986]
This issue regarding to #25985 .

I need load detail in lazy module based on url. So, I had used lazy auxilary routing. But, when I use auxilary routing, i'm facing below issue.

> 
> ERROR
> Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'lazy/aux1'
> Error: Cannot match any routes. URL Segment: 'lazy/aux1'
> at ApplyRedirects.noMatchError (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/@angular/router@6.1.7/bundles/router.umd.js:1455:20)
> at CatchSubscriber.eval [as selector] (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/@angular/router@6.1.7/bundles/router.umd.js:1436:33)
> at CatchSubscriber.error (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/rxjs@6.3.2/internal/operators/catchError.js:48:31)
> at MapSubscriber.Subscriber._error (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/rxjs@6.3.2/internal/Subscriber.js:96:26)
> at MapSubscriber.Subscriber.error (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/rxjs@6.3.2/internal/Subscriber.js:74:18)
> at MapSubscriber.Subscriber._error (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/rxjs@6.3.2/internal/Subscriber.js:96:26)
> at MapSubscriber.Subscriber.error (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/rxjs@6.3.2/internal/Subscriber.js:74:18)
> at MapSubscriber.Subscriber._error (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/rxjs@6.3.2/internal/Subscriber.js:96:26)
> at MapSubscriber.Subscriber.error (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/rxjs@6.3.2/internal/Subscriber.js:74:18)
> at TapSubscriber._error (https://lazy-load-auxilary-b7vpg-e2ax7j.stackblitz.io/turbo_modules/rxjs@6.3.2/internal/operators/tap.js:75:26)
> 

Please find the sample link and reproducing steps below:

1. Go to sample link https://stackblitz.com/edit/lazy-load-auxilary-b7vpg-e2ax7j
2.  Click lazy-route link 
![image](https://user-images.githubusercontent.com/33062693/45642574-32a14e80-bad6-11e8-81a1-b5323d8ec856.png)
3. Then click any one of aux route
![image](https://user-images.githubusercontent.com/33062693/45642627-5f556600-bad6-11e8-8b90-bca620bd87e0.png)

How can I resolve this issue?
Can any one help me to resolve this issue?

**Comment by LTAravindh** [comment]
@ericmartinezr May I know the reason for thumbs down?

**Comment by mlc-mlapis** [comment]
@LTAravindh ... read first https://github.com/angular/angular/issues/12842

**Comment by manekinekko** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by LTAravindh** [comment]
@manekinekko Okay. Will post it in StackOverflow.

**Comment by manekinekko** [comment]
@LTAravindh Thanks. Don't forget to close this issue :)

**Comment by benlesh** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
