### ISSUE TITLE
platform-browser: HAMMER_LOADER is executed multiple times

### ISSUE THREAD

**Issue by ajafff** [angular/angular#25995]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

`HAMMER_LOADER` is executed multiple times, once for each touch gesture event binding.

## Expected behavior

`HAMMER_LOADER` is executed only once, the returned Promise is used internally for all event bindings.

## Minimal reproduction of the problem with instructions
Open https://stackblitz.com/edit/angular-gitter-tzrlpn
Console will contain 2 entries for `loading HammerJS`. I guess depending on your browser and caching it might also load the HammerJS scripts multiple times.

## Environment

<pre><code>
Angular version: 6.1.7

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

/cc @CSchulz

**Comment by pkozlowski-opensource** [comment]
This continues to be a problem in Angular v9 running ivy, here is an updated reproduce scenario: https://stackblitz.com/edit/angular-vkluhl?file=src/app/app.module.ts

Two additional comments:
* we do have a PR for this issue so we should review it;
* there is another issues that talks about timing of hammer loading (#37149), we should probably review both issues together when fixing.
