### ISSUE TITLE
Documentation not working in guide/architecture

### ISSUE THREAD

**Issue by lk77** [angular/angular#25993]
Hello,

there is a problem with the documentation in guide/architecture

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

https://next.angular.io/guide/architecture not working

```
REQUEST FOR DOCUMENT FAILED.
We are unable to retrieve the "guide/architecture" page at this time. Please check your connection and try again later.
```

## Expected behavior

The page shows correctly

## Environment

Browser:
- chromium 69
 
Thanks

**Comment by manekinekko** [comment]
@lk77 the documentation is loading ok. Please clean your cache and reload angular.io.

![image](https://user-images.githubusercontent.com/1699357/45678884-ade71c80-bb37-11e8-8623-c22aa5362738.png)


@benlesh this issue can be closed.

**Comment by lk77** [comment]
it's working again, thanks.
