### ISSUE TITLE
On Http Post request  HttpClient  X-XSRF-Token are not setting  in an Angular 6

### ISSUE THREAD

**Issue by nishanth6** [angular/angular#25996]
```
import {HttpClientModule, HttpClientXsrfModule} from "@angular/common/http";

imports: [
    ...
    HttpClientModule,
    HttpClientXsrfModule.withOptions({
      cookieName: 'XSRF-TOKEN',
      headerName: 'X-CSRF-TOKEN'
    })
  ],
...
```

```
import {HttpClient, HttpClientModule, HttpClientXsrfModule} from "@angular/common/http";

constructor(private _http:HttpClient) { }

  addUser(info){
    return this._http.post(this.apiURL, info, {
      headers:  { 'Content-Type': 'application/x-www-form-urlencoded' },
      withCredentials: true,
      responseType: "arraybuffer",
    }
 }
```
The default interceptor created behind the scene by HttpClientXsrfModule does not seem to handle absolute urls....

So I've changed the
apiURL = "http://localhost/simple_api/insert.php";
TO
apiURL = "//localhost/simple_api/insert.php";

Working Fine. But unable var_dump or print the headers attached in the PHP script.
But I'm getting the form data submitted successfully.

**Comment by nishanth6** [comment]
> Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.
> 
> If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

Hi, @manekinekko Good to see you

I want to make the question simple and straight forward
In most of popular MVC Web framework CSRF Token will be generated automatically in the view from the controller and then it passed on to Model for saving the form data right?

In my case I have achieved generating XSRF Token from the backend of the server via cookies by calling  the API scripted in PHP, then what's the use of importing `HttpClientXsrfModule`

As I'm doing coding with template driven form approach & all the views & components were buided from angular syntax. I just need to generate XSRF Token from the built in angular modules in the view page and later passing that Token to the TypeScript of the view component 

I did R&D on generating XSRF Token from the Angular version 6 while importing from the  built in module by using oAuth, JWT, HttpInterceptor and soon.

Kindly suggest me the relevant approach for generating CSRF Token while Registering, Logging and forgotten password Page

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter

**Comment by nishanth6** [comment]
@benlesh @manekinekko 

[Click Here](https://stackblitz.com/edit/nishanthj123)

Here is my complete code. As I'm new to run this code

From the usr.service.ts it was consoling all the headers after posting the data
Headers should be posted or printed on the console

I have a screen Shot of console [Click](https://stackoverflow.com/q/52342195/7713811)
