### ISSUE TITLE
iOS 12 array reverse bug

### ISSUE THREAD

**Issue by Brooooooklyn** [angular/angular#26008]
https://stackoverflow.com/questions/52390368/array-state-will-be-cached-in-ios-12-safari-is-bug-or-feature/52394459

I searched in angular source codes, there are lot of Array#reverse codes, maybe this safari bug already effected angular.

## Environment

<pre><code>
Angular version: latest

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [x] Safari (iOS) 12
- [ ] IE version XX
- [ ] Edge version XX

**Comment by gkalpak** [comment]
:joy:

**Comment by manklu** [comment]
Already fixed

https://bugs.webkit.org/show_bug.cgi?id=188794

**Comment by mhevery** [comment]
this is outside of Angular's responsibility.
