### ISSUE TITLE
Child nodes of unsafe HTML nodes returned in sanitized output - displayed as raw HTML tags

### ISSUE THREAD

**Issue by shinok01** [angular/angular#26007]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

when the input to html_sanitizer.ts ::_sanitizeHtml method is -

```
unsafeHtmlInput = "<style><!-- foobar --></style><div>hie</div>"

The returned output safeHtml is -
"&lt;!-- foobar --&gt;<div>hie</div>"
```

Which ends up displaying raw comment tags.

## Expected behavior

If the html element tag is removed as "unsafe" then its content should also be removed and the expected value of safeHtml should be 

```
"<div>hie</div>"
```

## Environment

<pre><code>
Angular version: 6

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by benlesh** [comment]
Thank you @shinok01.

**Comment by benlesh** [comment]
Related buganizer: https://b.corp.google.com/issues/112758932

**Comment by mhevery** [comment]
Closed by https://github.com/angular/angular/pull/25879
