### ISSUE TITLE
Service Worker: Implement Cache then Network strategy

### ISSUE THREAD

**Issue by danielfoth** [angular/angular#26000]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently the Angular Service Worker supports [two strategies](https://angular.io/guide/service-worker-config#cacheconfig): performance (cache, falling back to network) and freshness (network, falling back to cache)

## Expected behavior

Support for the [Cache then Network](https://developers.google.com/web/fundamentals/instant-and-offline/offline-cookbook/#cache-then-network) strategy.

Also the other strategies would be nice.

## What is the motivation / use case for changing the behavior?

The app is often used in areas with slow or even no network connection. The data have to be fresh if possible, but user experience is also an important issue. Therefor showing cached data first and updating them as soon as fresh data are available is the best solution.

## Environment

<pre><code>
Angular version: 6.1.0

</code></pre>

**Comment by gkalpak** [comment]
AFAICT, there are two variations:
1. Show content from cache and update cache in background (so next request will show updated content).
2. Show content from cache, update cache in background and show updated content as soon as it arrives.

If I understand correctly, for the second variation the app needs to make too separate "requests" (one to the network and one to the cache). This is app-specific and not something the SW is involved with.

The first variation has been requested as a feature in #20402. See https://github.com/angular/angular/issues/20402#issuecomment-421938871 on how to easily achieve this with the existing strategies.
(Contributions (e.g. adding a mention in the docs or implementing a shorthand for this strategy) are very welcome :smiley:)
