### ISSUE TITLE
How to Set withCredentials:true in Angular 6 HttpClient.

### ISSUE THREAD

**Issue by GopiKrishna10** [angular/angular#26009]
HI Guys,

  Am facing a issue which is related to withCredentials:true in angular6 httpClient.In my project need to send the {withCredentials:True} in Headers.Am sending this like below code . could you please check and let me know. API is working but am not getting the setCookie key,value from the responseHeaders. Am running in the localhost.
Here is the code.Let me know guys if u need more info about this.

**Code**

let headers;
        if (reqUrl == 'validateSoftLoginInvestor' || 'validateOTP' || 'loadSoftLoginDetails') {
            headers = new HttpHeaders({ 'Content-Type': 'application/x-www-form-urlencoded', 'withCredentials': 'true' });
        } else {
            headers = new HttpHeaders({ 'Content-Type': 'application/json', 'Accept': 'application/json', 'Authorization': localStorage.getItem('accessToken') });
        }
        return this.http.post(`${this.baseUrl}` + reqUrl, body, headers).pipe(
            map((res: HttpResponse<Object>) => res))
    }

## Current behavior

Am not getting the setCookie key with value from the response headers.From where i can send the {withCredentials:true} in httpClient.

## Expected behavior
want to get the setCookie key value from the response Headers.

## Environment

<pre><code>
Angular version:6.1.0

**Thanks in Advance Guys.**

**Comment by mlc-mlapis** [comment]
@GopiKrishna10 ... can you read the docs on https://angular.io/guide/http first?

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by joesleiman** [comment]
create HttpInterceptor
@Injectable()
export class CustomInterceptor implements HttpInterceptor { 

    intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {

        const copiedReq = request.clone({
            withCredentials: true
        });

        return next.handle(copiedReq );
    }
}

@NgModule({
  bootstrap: [AppComponent],
  imports: [...],
  providers: [
    {
      provide: HTTP_INTERCEPTORS,
      useClass: CustomInterceptor ,
      multi: true
    }
  ]
})
export class AppModule {}

**Comment by hpawe01** [comment]
@joesleiman I would recommend, that you check first, if the `withCredentials` property is already set. I just lost some time in debugging, why my http request wasn't considering my `withCredentials: false` config:
```typescript
    if (request.withCredentials === undefined) {
      request = request.clone({
        withCredentials: true,
      });
    }
```
