### ISSUE TITLE
Set scroll position per router link or navigation

### ISSUE THREAD

**Issue by hamedsabzian** [angular/angular#26005]
scrollPositionRestoration options, not satisfy for scroll position management. 
i have some child route that i do not want scroll position go to top. but for other route it is required.

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter
