### ISSUE TITLE
html5 datalist is not supported for databinding (ngModel)

### ISSUE THREAD

**Issue by SimonAdesso** [angular/angular#26011]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
The model binding for <code>datalist</code> HTML-elements is not supported.

<pre><code>
ERROR Error: Uncaught (in promise): Error: No value accessor for form control with name: 'myModel'
[...]
</pre></code>

## Expected behavior
Binding with <code>datalist</code>-tag should work as with the <code>select</code>-tag

## Minimal reproduction of the problem with instructions
ngModel-Binding on a <code>datalist</code>-tag:

`<datalist [(ngModel)]="myModel">`
`<option *ngFor="let element of myModel" [ngValue]="element">`
`    {{ element.name }}`
`  </option>`
`</datalist>`

## What is the motivation / use case for changing the behavior?
Currently it's not possible to use the datalist-html-element.

## Environment
<pre><code>
Angular version: 5.2.10 & Angular 6.1.0
</pre></code>

Browser:
<pre><code>
- [X] Chrome (desktop) version 69.0.3497.92 (64-Bit)
- [X] the other should show the same problem (untestet)
</pre></code>

**Comment by skreborn** [comment]
The [`datalist`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) tag is not the one handling input - it's merely a provider of pre-defined autocomplete options for a regular [`input`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) tag. You should use the [`[(ngModel)]`](https://angular.io/api/forms/NgModel) binding on the [`input`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) instead.

You also shouldn't use `ngValue` on the [`option`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option) tag here, as this is built-in browser behavior and doesn't need Angular's special treatment.

```html
<input [(ngModel)]="value" list="options">

<datalist id="options">
  <option *ngFor="let element of elements" [value]="element">{{ element }}</option>
</datalist>
```

[Here](https://stackblitz.com/edit/angular-gitter-mm9tum?file=app%2Fapp.component.html)'s a working demo.
