### ISSUE TITLE
HostListener emits event even the component is hidden by ngIf when ng-content is used

### ISSUE THREAD

**Issue by wachri** [angular/angular#26016]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
If you have a inner component with a `HostListener`
```typescript
@Component({
  selector: 'app-inner',
  templateUrl: './inner.component.html',
  styleUrls: ['./inner.component.css']
})
export class InnerComponent {
    @HostListener('document:click', ['$event'])
    onDocumentClick(event: MouseEvent): void {
      alert('click listener in inner component');
    }
}
```

and project the component in another component with a `ngIf`

```html
<div *ngIf="false">
  <ng-content></ng-content>
</div>
```

then the  `@HostListener` emitting events, even the content is hidden

## Expected behavior
Events should only emitted when the `InnerComponent` is really displayed, like in components which are hidden with `ngIf` without content projection

## Minimal reproduction of the problem with instructions
Demo: https://stackblitz.com/edit/angular-tmrnfv
(do a click an you see a alert which shouldn't be there)

## What is the motivation / use case for changing the behavior?

- Code which you don't expect is executed, which leads to errors and strange behaviors
- Consistency: When you hide a component without content projection there is no emit

## Environment

<pre><code>
Angular version: 6.1.4

Browser:
- [X] Chrome (desktop) version 69.0
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by devoto13** [comment]
@wachri This is by design. Please read article linked from https://github.com/angular/angular/issues/17983#issuecomment-322613804 to learn more about ng-content.

**Comment by mlc-mlapis** [comment]
@wachri `InnerComponent` is created in a different moment than you think and its instance still lives = is not destroyed by that `*ngIf`.

**Comment by wachri** [comment]
@devoto13 Thx for the link. Especially the "The solution" part of the mention block post is interesting :).
