### ISSUE TITLE
Angular 6 On Http Post request HttpClient X-XSRF-Token are not setting automatically

### ISSUE THREAD

**Issue by nishanth6** [angular/angular#26010]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I had achieved in generating XSRF Token from the backend of the server via cookies by calling the API scripted in PHP,
```
    let headerOptions = new HttpHeaders();
    headerOptions.append('Access-Control-Allow-Origin', '*');
    headerOptions.append('Content-Type', 'application/json');
    headerOptions.append('Access-Control-Request-Headers', '*');
    headerOptions.append('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,PATCH,OPTIONS');
    return this._http.post(this.apiLoginUserURL, {'email_id':email_name, 'password':password}, {
      headers:  headerOptions },
      withCredentials: true,
      responseType: "arraybuffer",
    }, )
    .subscribe();
    );
```

## Expected behavior
Generate XSRF Token based on HttpClientXsrfModule or oAuth, JWT, HttpInterceptor and any other.

I need to add XSRF Token which needs to be generated by Angular
And How am I suppossed to get the response from the server. In console I'm not getting any Errors 
How should I need to get the response from the server i.e, whether the user is legimate or not

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/nishanthj123
@benlesh @manekinekko 

[Click Here](https://stackblitz.com/edit/nishanthj123)

Here is my complete code. As I'm new to run this code

From the usr.service.ts it was consoling all the headers after posting the data
Headers should be posted or printed with XSRF Token on the console. But it's not going to happen?

I have a screen Shot of console [Click](https://stackoverflow.com/q/52342195/7713811)

## What is the motivation / use case for changing the behavior?
As I'm doing coding with template driven form approach and all the views & components were built from the angular syntax. I just need to generate XSRF Token from the built-in angular imported modules displayed in the hidden field of the view page and later that Token is passed to the TypeScript of the view component

## Environment

<pre><code>
Angular version: 6.2.1

Browser:
- [X] Chrome (desktop) version 69.0.3497.81
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.11.4

- Platform:  Windows

**Comment by alxhub** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
