### ISSUE TITLE
angular.io website fail to search in firefox

### ISSUE THREAD

**Issue by pickfire** [angular/angular#26018]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[x] Other... Please describe: website
</code></pre>

## Current behavior

Fail to search the website with Mozilla Firefox and get protocol error most of the time.

## Expected behavior

Search should work and website should not get error.

## Minimal reproduction of the problem with instructions

1. Open `firefox`
2. Browse `angular.io`
3. <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>r</kbd> to force reload (angular.io gets protocol error)
4. Type in the search bar
5. loading...

## What is the motivation / use case for changing the behavior?

- no protocol error
- search successfully

## Environment

<pre><code>
Angular version: ?

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 62.0
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.10.0  
- Platform: Linux 

Others:

</code></pre>

**Comment by gkalpak** [comment]
I am not getting any errors 😕
Have you tried clearing the cache? Does next.angular.io work?

**Comment by pickfire** [comment]
It works after I removed everything from storage. @gkalpak Thanks a lot! It might be confusing that people needs to manually delete items from storage though.

**Comment by gkalpak** [comment]
@pickfire, glad you got it working. Manually clearing the cache is not part of the intended workflow, of course. But sometimes things go wrong 😅
Hopefully, once we upgrade to the new SW (see #25997), things will go wrong less often :grin:
