### ISSUE TITLE
Serviceworker not opening index.html file

### ISSUE THREAD

**Issue by akilmakda** [angular/angular#26015]
## Current behavior

http://127.0.0.1:8000/assets/
not work

getting below error: 
GET /assets/incex.html" Error (404): "Not found

http://127.0.0.1:8000/assets/index.html
this is work fine.

## Expected behavior

 http://127.0.0.1:8000/assets/ 
This should be load index.html file

## Environment

<pre><code>
Angular version: 5.2.5

Browser:
- [ ] Chrome (desktop) version XX
 
For Tooling issues:
- Node version: XX  
- Platform:

**Comment by gkalpak** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
