### ISSUE TITLE
Support declarative route matching in component templates

### ISSUE THREAD

**Issue by jonrimmer** [angular/angular#26013]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

At present, the Angular route only supports the declaration of routes as static data provided to the RouterModule NgModule.

## Expected behavior

The router should support an alternative configuration mode where routes are defined declaratively within component templates.

The `router-outlet` directive could be extended to accept a path fragment to match, and a component to render:

```html
<router-outlet
  path="/project/:projectId"
  [component]="ProjectOverviewComponent"
></router-outlet>
```

It could also accept a template reference to render instead of a component:

```html
<router-outlet
  path="/project/:projectId"
  [template]="projectRoute"
></router-outlet>

<ng-template #projectRoute let-route>
  <my-project-overview-component
    [projectId]="route.snapshot.params.projectId"
    [user]="route.snapshot.data.userProfile"
  ></my-project-overview-component>
</ng-template>
```

## What is the motivation / use case for changing the behavior?

Keeping route configuration inline is a valid alternative to centralising it into a configuration blob, and can make it easier to grok the routing behaviour on individual components. Other types of dynamic rendering such as if / for / switch are configured within templates. It is not obvious why routing must be a special case in this regard.

This feature would provide equivalence with the routing approach of [other popular frameworks](https://reacttraining.com/react-router/web/api/Route). It also supports more dynamic scenarios, as the component/template to render can now be controlled dynamically.

## Environment

<pre><code>
Angular version: 6.1.7
</code></pre>

**Comment by jonrimmer** [comment]
You would still have access to static configuration if you wanted it. But you could definitely support the things you mention via an inline approach. For example, you could have a `(matched)` event on the outlet that supported asynchronous cancellation:

```html
<router-outet
  path="/project/:projectId">
  [component]="ProjectOverviewComponent"
  (matched)="guardProjectRoute($event)"
></router-outlet>
```

```ts
guardProjectRoute(navigation) {
  navigation.redirectIf(this.authService.loggedOut$, '/login');
}
```

It wouldn't be difficult to add similar APIs to asynchronously resolve resources and provide them as route data, with the ability to defer outlet rendering until they resolved.

**Comment by jasonaden** [comment]
Excellent idea, and this is on a list of things we would like to do next year to give more options of how to configure the router. There are a number of other features that would come along with it. I'll close this issue, but have it noted as one of the supporting requests for this functionality.
