### ISSUE TITLE
Add conditional HttpParams.set

### ISSUE THREAD

**Issue by serhioV** [angular/angular#26021]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

We can't conditionally add a HttpParam to HttpParams

## Current behavior
```
function (page, filter) {
  let hp = new HttpParams();
  if (page !== undefined) {
    hp = hp.set('page', page);
  }
  if (page !== undefined) {
    hp = hp.set('elementsPerPage', 10);
  }
  if (filter !== undefined) {
    hp = hp.set('filter', filter);
  }
```
we can't conditionally add a HttpParam to HttpParams

## Expected behavior
```
function (page, filter) {
  let hp = new HttpParams()
      .set('page', page, page !== undefined)
      .set('elementsPerPage', 10, page !== undefined)
      .set('filter', filter, filter !== undefined);
  }
```

**Comment by alxhub** [comment]
I don't believe we will introduce this API at this time.

**Comment by DanielFrugoni** [comment]
let params  = new HttpParams().set('Gpclave',  term); ONLY works with exact match????
why not a wild card ? or where can i do that ???

**Comment by mfish0005** [comment]
I  think the docs are just lacking a decent example of set/append using conditionals.
