### ISSUE TITLE
Possibility to specify translation pr angular module

### ISSUE THREAD

**Issue by Diemauerdk** [angular/angular#26038]
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
There can only be one application wide translation file pr language for internationalization. 

## Expected behavior
Possibility to add and configure translation files to be applied pr language pr angular module.

## What is the motivation / use case for changing the behavior?
To separate translations into the modules they belong to.

## Environment
Angular version: 6.1.0

Browser:
- [ X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  v8.11.4
- Platform:  Windows

## Others
I have been reading the documentation(https://angular.io/guide/i18n) through and could not find any way of dealing with this. I have been googling the issue but most people seems to use ngx-translate which i understand might be deprecated in the future(so that's not a solution for me :)).

**Comment by LosD** [comment]
@Diemauerdk Why do you think that ngx-translate would be deprecated in the future?

It's clearly the better solution. And it should be made the official solution (or at least it's runtime support), Angular's i18n support is honestly a bit of a joke without it.

**Comment by Diemauerdk** [comment]
@LosD Because the developer of the ngx-translate package, ocombe, has stated in several threads that it is going to be deprecated whenever Angular catches up. He is also a part of the Angular core team developing internationalization. For reference see for example this link: https://github.com/ngx-translate/core/issues/495

**Comment by LosD** [comment]
@Diemauerdk Hmmm, fair point.

**Comment by dylhunn** [comment]
Related to [this issue.](https://github.com/angular/angular/issues/36757) If we ever support this, it will be via providing different files on a per-package or per-library basis.
