### ISSUE TITLE
Query only directives on self

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#2603]
Currently query has two scopes: direct children and descendants. It should also be possible to query directives created on the same element.
 
One example where it can be useful is querying validator directives.

```
class Control {
  constructor(@Query(ControlValidator, {onlySelf:true}) validators) {}
}
```

**Comment by rkirov** [comment]
This needs to be revisited after the similar visibility rules for injectors are redesigned:
@vsavkin ping this back when those have landed.

**Comment by rkirov** [comment]
Here is the final design as discussed by Misko, Victor, Tobias and me:

Only Query supports visibility modifiers, while ViewQuery queries all of the view. 

```
enum Horizon {
  Self, Children, Unbounded
}

@Query(skipSelf: boolean = false, horizon: Horizon = Horizon.Children)

@ViewQuery()
```
To define the visibility we use a notion of distance based on the number of DOM nodes (not injectors) between the element where the query lives and where the directive lives.
skipSelf sets the lower bound of visibility to 0 or 1
Horizon sets the upper bound of visilibity to 0 (Self), 1(Children) and infinity (Unbounded).

**Comment by rkirov** [comment]
Alternative suggestion from Victor (closer to DI semantics):
```
enum Visibility {
  Self, Children, Descendants
}
```

**Comment by mhevery** [comment]
@rkirov is this still an issue or can this be closed?

**Comment by rkirov** [comment]
Superceeded by #3922
