### ISSUE TITLE
It shouldn't to execute the AsyncValidatorFn

### ISSUE THREAD

**Issue by liyanq528** [angular/angular#26049]
##  my component
<pre><code>
export class CsInputComponent implements OnInit {
   ...
  inputFormGroup: FormGroup;
  public inputControl: FormControl;
  ...
  @Input() customerValidatorAsyncFunc: AsyncValidatorFn;
  ...
  constructor() {
    ...
    this.inputControl = new FormControl("", {updateOn: 'blur'});
    this.inputFormGroup = new FormGroup({inputControl: this.inputControl}, {updateOn: 'blur'});
  }
  ngOnInit() {
    setTimeout(() => {//Todo:Bad method for prevent validate when dynamic create;
      if (this.customerValidatorAsyncFunc) {
        this.inputControl.setAsyncValidators(this.customerValidatorAsyncFunc);
      }
    });
    ...
</code></pre>

## Current behavior

When I create my component by *ngFor and the customerValidatorAsyncFunc property is valid, and then the AsyncValidatorFn was execute.I think, it isn't normally.

## Expected behavior

It should't to execute the AsyncValidatorFn when I create my component by *ngFor.

**Comment by kara** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
