### ISSUE TITLE
[routerLink]="null" should not affect the href attribute

### ISSUE THREAD

**Issue by BarnT** [angular/angular#26040]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
the following template: `<a href="my/custom/url" [routerLink]="null">link</a>`
is generated to: `<a href="current/page/url">link</a>`

## Expected behavior
the following template: `<a href="my/custom/url" [routerLink]="null">link</a>`
should be generated to: `<a href="my/custom/url">link</a>`

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gitter-63xra2?file=app%2Fapp.component.html

## What is the motivation / use case for changing the behavior?
In case you have an array of links to handle, and the array includes links with 'routerLink routes' and 'normal (pl absolute-) URLs'. Then it's much easier to handle them in a template (see: reproduction example)

## Environment

<pre><code>
Angular version: 6.1.7

**Comment by jasonaden** [comment]
Thanks for the issue. This seems quite specific, so I set the frequency to `low`, but at the same time it's definitely broken. I don't think it's a feature request, but actually a bug.

I don't know when this one can get scheduled. I'm putting on the `community-help` label to see if someone can help grab this and get it fixed.

**Comment by thanhcng** [comment]
I guess there's something needs to be fixed in this [urlTree method](https://github.com/angular/angular/blob/4c2ce4e8ba4c5ac5ce8754d67bc6603eaad4564a/packages/router/src/directives/router_link.ts#L249).

**Comment by maximelafarie** [comment]
@jasonaden I've done a fix for this issue (as a first contribution 🎉). So I'll commit it as a `fix`, and if you agree with that, I'll mention you in the PR description in order to check everything is ok. 😉

**Comment by nhhockeyplayer** [comment]
Im seeing ALL attempts to create 

<a href=www.google.com" ></a>

are broken

including writing special directive to do externalRedirect

2-way binding fails

cannot bind anything to <a> tag with href

alot of issues on this date back to 2012

we are spending hours to workaround and none yet

**Comment by atscott** [comment]
Very much related to #13980. It's the same issue, but with a different desired outcome.

**Comment by atscott** [comment]
Closing this in favor of #13980. `routerLink` inherently modifies the `href` attribute. Setting it to `null` should clear the `href` instead of leaving it alone. If a `routerLink` that does not affect the `href` attribute is desired, I would recommend copying the `RouterLinkWithHref` code and creating your own directive for this special case.
