### ISSUE TITLE
Transformer hangs when invalid templateUrl is used

### ISSUE THREAD

**Issue by TedSander** [angular/angular#2605]
When using pub serve transformer can hang when using an invalid url.

Example templateUrl: '/gallery/gallery.html', (Which actually is a valid pub url but the transformer can't handle it now will file a separate issue for that.)

Exception:
Build completed successfully
in ShutdownIsolate: Unhandled exception:
Uncaught Error: The null object does not have a getter 'package'.

NoSuchMethodError: method not found: 'package'
Receiver: null
Arguments: []
Stack Trace:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      serializeId (package:$pub/serialize.dart:24:47)
#3      ForeignTransform.getInput (package:$pub/serialize/transform.dart:121:13)
#4      _ForeignBaseTransform&GetInputTransform.hasInput (package:$pub/serialize/get_input_transform.dart:29:12)
#5      _TransformAssetReader.hasInput (package:angular2/src/transform/common/asset_reader.dart:27:42)
#6      XhrImpl.get.<get_async_body> (package:angular2/src/transform/common/xhr_impl.dart:19:40)
#7      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#9      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

**Comment by TedSander** [comment]
@jakemac53 Can you take a look at this when you get a chance. Tracking internal b/21903876

**Comment by jakemac53** [comment]
I haven't been able to repro that exact error, but I do see pub serve hang. I think this is because we are logging an error which causes barback to not output the file. We could just downgrade it to a warning, but that doesn't really seem correct either... will need to think on this one.
