### ISSUE TITLE
Routerlink not work when using getter to provide data

### ISSUE THREAD

**Issue by ymchun** [angular/angular#26068]
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
- [ ] Other... Please describe:

I am using angular 6 to develop my email application, I have a list of mail boxes for users who can click on the link to go to each mail box.

However, when I use component `version A` to render the list, nothing will happen when click on the router link (no route will be triggered). But `version B` works as expected. Both `version A` and `version B` render the UI properly. I wonder what is happening under the hood, it this is the correct behaviour of getter accessor? Or this is a bug of angular?

## Current behavior
`version A` routerlink not triggered when clicked
`version B` routerlink works as expected

## Expected behavior
Both versions' routerlink will go to route when clicked

## Minimal reproduction of the problem with instructions
component (version A)

    import { Component } from '@angular/core';
    import { EmailService } from '~/email/services/email.service';

    @Component({
        templateUrl: '../views/email.view.html',
    })
    export class EmailComponent {

        public constructor(private emailService: EmailService) {}

        public get mailboxes(): Mailbox[] {
            return this.emailService.mailboxes;
        }
    }

component (version B)

    import { Component, OnInit } from '@angular/core';
    import { EmailService } from '~/email/services/email.service';

    @Component({
        templateUrl: '../views/email.view.html',
    })
    export class EmailComponent implements OnInit {

        public mailboxes: Mailbox[];

        public constructor(private emailService: EmailService) {}

        public async ngOnInit(): Promise<void> {
            this.mailboxes = this.emailService.mailboxes;
        }
    }

service

    @Injectable()
    export class EmailService {

        public get mailboxes(): Mailbox[] {
            return [
                { name: 'Inbox', icon: 'inbox', link: 'inbox' },
                { name: 'Sent', icon: 'send', link: 'sent' },
                { name: 'Drafts', icon: 'drafts', link: 'drafts' },
                { name: 'Spam', icon: 'report', link: 'spam' },
                { name: 'Trash', icon: 'delete', link: 'trash' },
                { name: 'Archive', icon: 'archive', link: 'archive' },
            ];
        }
    }

template

    <mat-nav-list>
        <a mat-list-item *ngFor="let mailbox of mailboxes"
            routerLink="{{'mailboxes/' + mailbox.link}}">
            <mat-icon matListIcon>{{mailbox.icon}}</mat-icon>
            <h4 matLine>{{mailbox.name}}</h4>
        </a>
    </mat-nav-list>

## Environment

Angular version: 6.1.8

Browser:
- [x] Chrome (desktop) version 69
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.7.0
- Platform:  Mac

**Comment by manklu** [comment]
You should provide a complete sample. For stackblitz you can use https://stackblitz.com/fork/angular-gitter as a starting point.

**Comment by ymchun** [comment]
thx @manklu 
here is the sample: https://stackblitz.com/edit/angular-gitter-clsw1d

in `app.component.ts`, now the data is from `getter`. The url won't change of you click on the link.

**Comment by ymchun** [comment]
close
see https://stackoverflow.com/a/52474924/3771520
