### ISSUE TITLE
ml_parser - leading '&#' leads to a cryptic error

### ISSUE THREAD

**Issue by StarpTech** [angular/angular#26067]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Any attribute value with an leading `&#` will throw:
```
Template parse errors:
Unexpected character "'" ("<hello name="{{ name }}" [icon]="'&#[ERROR ->]'"></hello>
<p>
Start editing to see some magic happen :)
"): ng:///AppModule/AppComponent.html@0:36
Unexpected closing tag "hello". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("<hello name="{{ name }}" [icon]="'&#'">[ERROR ->]</hello>
<p>
Start editing to see some magic happen :)
"): ng:///AppModule/AppComponent.html@0:39
Evaluating src/main.ts
Booting application
```

## Expected behavior

1. The parser should point to the exact issue that an entity was expected. The error message [here](https://github.com/angular/angular/blob/master/packages/compiler/src/ml_parser/lexer.ts#L330) should be more meaningful. **or**
2. The parser should proceed and handle it as text because parser can't know if it's an entity. **or**
3. **or** Handle e.g `&#333` as `ō` that's the behaviour of [parse5](https://astexplorer.net/#/gist/f538a3a7119c6c1aff26693455d52e7a/5fe7c65b6d20130bc8ef79002807f079cedef702)

But we can definitly improve the error message.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-fjgsqz?file=src/app/app.component.html

## What is the motivation / use case for changing the behavior?
User should get the correct error message

## Environment
Angular version: 6.0.0

**Comment by manklu** [comment]
> The parser should proceed and handle it as text because parser can't know if it's an entity.

Per html definition, anything that starts with an ampersand is an entity. If you want to output one you should use `&amp;`.

> Handle e.g &#333 as ō that's the behaviour of parse5

If you use the correct syntax it works: `&#333;`

**Comment by StarpTech** [comment]
@manklu yes it works if you use the correct syntax but this is not the issue. If you `&#333` angular will throw an issue instead to decode it according to the specs . The second point is that this error is very cryptic we could just say "entity could not be encoded" which would be more meaningful.

**Comment by trotyl** [comment]
In HTML spec it's an [`missing-semicolon-after-character-reference` parse error](https://html.spec.whatwg.org/#parse-error-missing-semicolon-after-character-reference), the error message produced by W3C validator is: 

```
Character reference was not terminated by a semicolon.
```

Likely this error message would be more helpful.

**Comment by StarpTech** [comment]
@trotyl thanks for the pointer that's indeed the correct error message.

**Comment by manklu** [comment]
@StarpTech 
> The second point is that this error is very cryptic

I have never said the error message is good :smirk:

**Comment by pkozlowski-opensource** [comment]
This continues to be an issue in Angular v9 running ivy, here is a minimal reproduce scenario: https://stackblitz.com/edit/angular-czurvn?file=src/app/app.module.ts

I do agree that we should improve error message to indicate that we are trying to parse an HTML entity. Please note that the cryptic error can be triggered at any point in the template, not only in attributes, so adjusting the issue title accordingly.
