### ISSUE TITLE
Transformer does not work well with web urls

### ISSUE THREAD

**Issue by TedSander** [angular/angular#2607]
Angular itself can handle a templateUrl such as:
  templateUrl: 'gallery/gallery.html',
Yet the transformer itself will fail with a asset not found. Asset is under web/gallery/gallery.html

The transformer can find the relative asset like so:
  templateUrl: 'gallery.html',
Yet reflective mode can't handle that case yet.

**Comment by TedSander** [comment]
@jakemac53  can you take a look at this. Internal tracking b/21903876

**Comment by jakemac53** [comment]
Not quite sure I understand this, should that path work from any file in any subdirectory of web, so it is essentially a special type of absolute url?

**Comment by jakemac53** [comment]
or did you mean `/gallery/gallery.html`?

**Comment by jakemac53** [comment]
@TedSander to confirm what you would like is support for absolute urls? To me this seems like an anti-pattern in dart code, typically anything you would want to point to via an absolute url you should instead put inside lib and then access it via a package url.

**Comment by TedSander** [comment]
I would say this isn't an anti-pattern or else why does dart have a web/ directory, sure those resources can't be shared across apps, but a lot of times you don't want them to. Basically it should support what is outlined in the barback document here:
https://docs.google.com/document/d/1juHkCRg-1YH6LvwhGPHgF2ihX-UQtR1fv-8aknO7t_4/edit?pli=1#heading=h.qse5zkbqletn

I had this working for angular.dart. It shouldn't be too hard to get it working for angular2.

**Comment by jakemac53** [comment]
One question here is what is considered the `root` of the application (ie: '/')? You can run a server from any folder in your package, and we don't really want to be opinionated about telling people where they should start their server from. The transformer doesn't know what folder the server will be started from,  so it would just have to assume something like the top level directory in your package that the current file lives in (ie: lib/web/test/example/benchmark). If somebody serves the web/foo directory of their app, then the runtime version is going to treat `web/foo` as the `root` and the transformer will treat `web` as the root, and so you have inconsistent behavior.

**Comment by tbosch** [comment]
@TedSander This should be solved by the new compiler. Could you double check once it is in G3?

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
