### ISSUE TITLE
DowngradeComponents are never created on screen

### ISSUE THREAD

**Issue by chris-eaton** [angular/angular#26097]
Hey

I have created a hybrid app based on the official documentation (and any other link I could find) which seems to build, but, if I add an Angular component, then downgrade it, its never rendered on screen.

After my actual component didn't work I created a test component called "ng2-test" which also doesnt work.

Bootstrap:

```
import * as angular from "angular";

import { downgradeModule, downgradeComponent } from "@angular/upgrade/static";
import { platformBrowser } from "@angular/platform-browser";
import { StaticProvider } from "@angular/core";

import { MainAngularModule, Ng2TestComponent } from "./app.module";
import "./index.module";

const bootstrapFn = (extraProviders: StaticProvider[]) => {
    const platformRef = platformBrowser(extraProviders);
    return platformRef.bootstrapModule(MainAngularModule);
};

const downgradedModule = downgradeModule(bootstrapFn);

angular.module('angularJsModule', ['veriApp', downgradedModule]).component("ng2-test", downgradeComponent({ component: Ng2TestComponent }));
angular.bootstrap(document, ['angularJsModule']);

```

App.Module
```
import { NgModule, Component } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { UpgradeModule } from '@angular/upgrade/static';

@Component({
    selector: "ng2-test",
    template: "YO"
})
export class Ng2TestComponent {
    constructor() {
        console.log("ng2-test");
    }
}

@NgModule({
    imports: [
        BrowserModule,
        UpgradeModule
    ],
    declarations: [Ng2TestComponent]
})

export class MainAngularModule {
    // Empty placeholder method to satisfy the `Compiler`.
    ngDoBootstrap() { }
}

```

Usage in HTML:
```
<ng2-test></ng2-test>
```

**Comment by gkalpak** [comment]
This is probably because you are using `platformBrowser` with a module. You either need to use `platformBrowserDynamic` or use an `.ngfactory` file. See [here][1] (and the resources linked to from there) for more info.

Typically, `@angular/cli` takes care of this for you under the hood, but in a manual setup (such as with `ngUpgrade`), you need to do it yourself. If you are starting out and/or evaluating the approach, it is simpler to just use `platformBrowserDynamic` instead.

[1]: https://angular.io/guide/upgrade-performance#using-ahead-of-time-compilation-with-hybrid-apps

**Comment by chris-eaton** [comment]
@gkalpak Hey Thanks for the response. If I switch to that it still doesnt work.

I created a stackblitz and it still isnt working https://stackblitz.com/edit/angularjs-q1vrpe?file=app.module.js

**Comment by chris-eaton** [comment]
P.s. I see you closed the issue, presumably because it is an issue I am having rather than a framework issue. But where does one go to get help on this? I have tried following the official documentation time and time again and either I am missing something obvious or there are holes in it. I only posted here as a last resort!

**Comment by gkalpak** [comment]
For support questions, you can try on StackOverflow or Gitter (see [here][1]). Your example has a number of issues.
You can use [this StackBlitz project][2] as a basis.

We are aware that the `ngUpgrade` documentation is not great (this is tracked in other issues, e.g.: #19102, #24867, #25928).
It shouldn't be broken, though. If there are specific problems or bugs where following the docs results in a broken app, please open a new issue with the necessary details (or even better submit a pull request with the fix :tada:).

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[2]: https://stackblitz.com/edit/ngupgradelite-playground

**Comment by gkalpak** [comment]
(You might also want to check out https://github.com/angular/ngMigration-Forum.)
