### ISSUE TITLE
Error: Trying to get the AngularJS injector before it being set. when injecting an upgraded angular1 service into an angular6 error interceptor

### ISSUE THREAD

**Issue by FaabLondon** [angular/angular#26101]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  

</code></pre>

## Current behavior
In my hybrid app, I cannot inject an upgraded ng1 service into an Angular6 ErrorInterceptor because $injector is undefined. The hybrid app uses both AngularJS and Angular6 routers.
However, I have no error when I inject the same service in a downgraded Angular6 component.

## Expected behavior
I can inject the upgraded ng1 service

## Minimal reproduction of the problem with instructions
**index.html**
<body>
  <app-root></app-root>
</body>

 **app.module.ts**
import { ErrorInterceptor } from './_helpers/error.interceptor';
/ Upgraded Angular1 service/factory 
import { AuthInterceptorService } from './services/authInterceptor/authInterceptor.service';

[…]
providers: [
	AuthInterceptorService,
	ErrorInterceptor,
    { provide: HTTP_INTERCEPTORS, useClass: ErrorInterceptor, multi: true }],
  bootstrap: [AppComponent]
})
export class AppModule { 
}

**app.component.ts**
constructor(private upgrade: UpgradeModule) { }
    ngOnInit() {
    this.upgrade.bootstrap(document.body, [‘nameAngular1App’]);
  }

**app.component.html**
<div class="view-container">
  <div ui-view id="ui-view-container"></div>
   <router-outlet></router-outlet>
</div>

**main.ts**
platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.log(err));

**error.interceptor.ts**
constructor(@Inject(AUTHINTERCEPTOR) private authService: any) { } //this causes the error message

    intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
		[…]

    }

**authInterceptor.service.ts**
import { InjectionToken } from '@angular/core';

export const AUTHINTERCEPTOR = new InjectionToken<any>('AUTHINTERCEPTOR');

export function createAuthService(i) {
    return i.get('authInterceptor'); // Service/factory defined in angular1 app
}

export const AuthInterceptorService = {
    provide: AUTHINTERCEPTOR,
    useFactory: createAuthService,
    deps: ['$injector']
}

## What is the motivation / use case for changing the behavior?
To use angular1 services within an angular6 context while gradually moving towards an angular6 application.

## Environment

OS: macOS High Sierra 10.13.6  IDE: Visual studio code Package manager: NPM,
Build system: Webpack,  
	•	Angular version: 1.7.3 and 6.1.0 
	•	Browser:  Chrome 
	•	Language: [all | TypeScript X.X | ES6/7 | ES5] Typescript 2.7.2 
	•	Node (for AoT issues): node --version = 6.4.1 
</code></pre>

**Comment by gkalpak** [comment]
Can you please create a minimal live reproduction, e.g. using StackBlitz? You can use [this project][1] as a basis.

[1]: https://stackblitz.com/edit/ngupgradestatic-playground

**Comment by FaabLondon** [comment]
Thanks for the link to the project. However my ng1 app is still written in js and I can't add js fuiles, just ts...
What shall I do?

**Comment by gkalpak** [comment]
So, how do you bring the ng1 part into the app? Include with `<script>` tags in `index.html`?

**Comment by FaabLondon** [comment]
Yes

**Comment by FaabLondon** [comment]
By the way, I have tried the solution in the bug #14993
@NgModule({
  ...
  bootstrap: [RootComponent],
})
class AppModule {
  constructor(upgrade: UpgradeModule) {
    upgrade.bootstrap(document.documentElement, ['demo']);
  }
}
but the demo (ng1) app does not load in that case...

**Comment by FaabLondon** [comment]
Also, I have used the exact approach stated in step 6 and step 7 in this tutorial https://www.softwarearchitekt.at/post/2017/07/14/directly-upgrading-from-angularjs-1-x-to-angular-by-skipping-preparation.aspx

**Comment by gkalpak** [comment]
On StackBlitz, you can put the code inside `<script type="text/javascript">/* Code goes here */</script>` tags in `index.html`.

**Comment by FaabLondon** [comment]
And how do I include the dependencies in index.html. Currently I include them through script tags with a src pointing at the angular1 node_modules...?

**Comment by FaabLondon** [comment]
Here is my code in StackBlitz: https://stackblitz.com/edit/ngupgradestatic-playground
Can you confirm you can see the updated version of the code though as I am not sure how to change the changes. 
I have tried to replicate the error, however for now, my app is not even loading as I get 'ERROR
Error: AngularJS v1.x is not loaded!'.

**Comment by FaabLondon** [comment]
Here is my code in StackBlitz: https://stackblitz.com/edit/ngupgradestatic-playground
Can you confirm you can see the updated version of the code though as I am not sure how to save the changes.
I have tried to replicate the error, however for now, my app is not even loading as I get 'ERROR
Error: AngularJS v1.x is not loaded!'.

Also I get another error message when I have the following in ng2-demo-module.ts: `declare var angular: any;
angular.module('ng1App')
   .directive('Ng2DemoComponent', downgradeComponent({ component: Ng2DemoComponent }))`

**Comment by gkalpak** [comment]
No, I don't see the changes. You have to fork the project to be able to save the changes.

**Comment by FaabLondon** [comment]
thanks. Here is the link to my StackBlitz hybrid app. 
https://stackblitz.com/edit/ngupgradestatic-playground-hlfso8
As explained above, I can't replicate the 'Error: Trying to get the AngularJS injector before it being set' error yet as I am getting another error : Error: AngularJS v1.x is not loaded!'. Please note that I have used the following tutorial to build my hybrid app. The app works fine until I try to inject an upgraded authInterceptor service into a angular6 errorInterceptor. However when I inject that same service into an angular 6 component (downgraded or not downgraded) it works fine.

**Comment by gkalpak** [comment]
@FaabLondon, your example has some issues (besides the "AngularJS is not loaded" error).
I cleaned it up a bit and created a basic dual-router setup [here][1]. (It uses `ngRoute` instead of `ui.router`, but the concepts are the same).

Can you, please, that new project as a basis and create a minimal reproduction of your issue?

[1]: https://stackblitz.com/edit/ngupgradestatic-dual-router-playground-js

**Comment by FaabLondon** [comment]
@gkalpak the bug disappeared when I changed the way I was loading my config file before boostrapping the app. I was using APP_INITIALIZER which I think was messing up things with the HTTP_INTERCEPTOR.

**Comment by gkalpak** [comment]
Glad your were able to get it working :)

**Comment by jessiejuachon** [comment]
> @gkalpak the bug disappeared when I changed the way I was loading my config file before boostrapping the app. I was using APP_INITIALIZER which I think was messing up things with the HTTP_INTERCEPTOR.

How did you load your config then? I am encountering the same issue and I am using APP_INITIALIZER.
