### ISSUE TITLE
[API BUG/Router] RouteReuseStrategy.shouldReuseRoute arguments order is inconsistent and unreliable

### ISSUE THREAD

**Issue by lemoinem** [angular/angular#26100]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
The argument to shouldReuseRoute are provided in the wrong order:
The order should be (future, current), and they are in the call at https://github.com/angular/angular/blob/cf095d982dec9fe9bfd66d3df6eb4fe3d4034dd9/packages/router/src/create_router_state.ts#L26

However, in the same file, L. 68, the arguments seem to be inversed:
https://github.com/angular/angular/blob/cf095d982dec9fe9bfd66d3df6eb4fe3d4034dd9/packages/router/src/create_router_state.ts#L62-L70

`child` comes from `curr` and `p` comes from `prevState`. This makes me think the order should be `(p.value.snapshot, child.value)`.

I've noticed that, because when defining my own routeReuseStrategy, I had the states reversed.
This prevents me from reusing a component across different routes.

I have a trivial patch (https://github.com/lemoinem/angular/commit/deaeb3eed869f62d2b595db1696a16bdfd09f006), but I'm not sure what test I could write to ensure this doesn't reoccur and would love having some help for this.

## Expected behavior
The method should be called with the proper argument reliably.
If the behavior is inconsistent with the documentation, the documentation should be updated.

## Minimal reproduction of the problem with instructions
Implement an asymmetric route reuse strategy.

## What is the motivation / use case for changing the behavior?
My use case is the following: 
I have a very heavy component with a lot of internal state that's used to create or edit a huge entity. When creating a new instance, I go to `/entity/new`, but once I save the entity, I would like to preserve the component and change the url to `/entity/:id`.

The way I went for solving it and checking in shouldReuseRoute for this transition and reuse the route in this case.

Having the arguments in reverse order sometimes defeat the purpose. Of course, if someone is editing an existing entity, but choose to create a new one, I should re-initialize the component.

## Environment

<pre><code>
Angular version: 6.0.7
As per the source code linked, this is still an issue as of 7.0.0-beta6 (cf095d982dec9fe9bfd66d3df6eb4fe3d4034dd9)

Browser: Irrelevant
Tooling: Irrelevant
</code></pre>

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/16192

**Comment by lemoinem** [comment]
Indeed. I did a search, but I haven't found it.
Thanks.
