### ISSUE TITLE
Issue With Angular Universal

### ISSUE THREAD

**Issue by sksingh1995** [angular/angular#26116]
In Angular Universal, when we refresh the page, it hits the backend api's twice.
Angular Universal is too slow.

Please check the link and give some suggestion for faster performance and prevent twice backend call.

https://shaadion.com

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
