### ISSUE TITLE
Nested tbody when using ng-content

### ISSUE THREAD

**Issue by Magador** [angular/angular#26114]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

Possible regression of #5967

## Current behavior

Angular adds a `<tbody>` around the content projected via a `ng-content` in a `<table>`.

## Expected behavior

Not to add a `<tbody>` around the content projected by `ng-content`.

## Minimal reproduction of the problem with instructions

On this demo https://stackblitz.com/edit/angular-gitter-eqtefe :
- Inspect the DOM of the table

## What is the motivation / use case for changing the behavior?

Presence of `tbody` in another `tbody` is against HTML Specification.

## Environment

<pre><code>
Angular version: 6.1.8 (most recent at time of writing)

Browser:
- [x] Chrome (desktop) version 69
- [x] Chrome (Android) version 69
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11.228.17134.0
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Sounds like a regression https://github.com/angular/angular/issues/5967 (fixed by https://github.com/angular/angular/commit/e484c62a8d369c28ab1f4e8a256257620bf53a8b)

**Comment by trotyl** [comment]
The mental model of content projection is:

1. Create the DOM tree according to the HTML declaration;
2. Move the already created nodes to some part of the internal view;

So the requirements is, the HTML itself must be valid before movement happens (imagine there's no projection), but your code violates that in both light DOM and shadow DOM:

```html
<app-table>
  <tr>...</tr>
</app-table>
```

This is not valid as `<tr>` cannot be placed under `<app-table>`.

```html
<tbody>
  <ng-content></ng-content>
</tbody>
```

This is not valid as well, `<ng-content>` cannot be placed under `<tbody>`.

You can check the [native web behavior](http://jsbin.com/roxocecovo/1/edit?html,output
) in any latest browser:

![image](https://user-images.githubusercontent.com/6059170/46084885-41bf8500-c1d7-11e8-8e94-7841cf8b2eec.png)

As you can see, the `<slot>` element were pushed outside `<table>` and the projected `<tr>` got removed.

Please be aware that Angular content projection is designed to be an exact polyfill of web components, and `<ng-content>` is corresponding to [`<content>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/content), which has changed to [`<slot>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot) in newer version of spec.

Making inconsistency between `ViewEncapsulation.ShadowDom` and `ViewEncapsulation.Emulated` is never a good thing. (Eventually it will still be `ViewEncapsulation.ShadowDom` whenever possible)

But Angular should still provide more consistent error behavior as per Shadow DOM spec or produce a error message directly.

**Comment by alxhub** [comment]
@trotyl's reply is very informative and correct.
