### ISSUE TITLE
[Angular Elements]: Adding ComponentNgElementStrategyFactory & ComponentNgElementStrategy to public API

### ISSUE THREAD

**Issue by jKelio** [angular/angular#26112]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
On implementing an optional custom strategy provider, when I create a new custom element with an angular component, I am forced to implement a complete new custom strategy provider with an own factory.

## Expected behavior
But if I want to hook up a custom behavior to the default ComponentNgElementStrategy, I have to copy&paste the default class. Maybe it would be better, to import the default class that the custom element strategy could inherit from the default one.

## Minimal reproduction of the problem with instructions
I have pushed an angular elements example with a custom behavior hooked up into the default copied and pasted ComponentNgElementStrategy on the connect method:
[https://github.com/jKelio/angular-element-example](https://github.com/jKelio/angular-element-example)

## What is the motivation / use case for changing the behavior?
Avoiding too much coping&pasting stuff from the angular framework itself.

## Environment

<pre><code>
Angular version: 6.1.0
</code></pre>

**Comment by remackgeek** [comment]
This would be useful. While waiting for the zone changes to land, I had to do some hacky things to be able to wrap ComponentNgElementStrategy. See [elements-zone-strategy](https://github.com/remackgeek/elements-zone-strategy)

**Comment by totszwai** [comment]
We need this to workaround the issue mentioned in https://github.com/angular/angular/issues/29606

**Comment by gkalpak** [comment]
We have decided to not make `ComponentNgElementStrategy` part of the public API. See https://github.com/angular/angular/pull/37416#issuecomment-648180446 for more info.

If you need to define your own strategy, you can copy `ComponentNgElementStrategy` (and the corresponding factory).
