### ISSUE TITLE
cannot resolve all parameters for DefaultValueAccessor

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#2612]
I get this exception when using forms, not sure why though, because I do not directly use it anywhere, I just inject it as `directives: ['DefaultValueAccessor']` into a component.

![screenshot 2015-06-18 09 57 19](https://cloud.githubusercontent.com/assets/1479737/8226611/7ac2a198-15a0-11e5-808e-2812ed19a276.png)

**Comment by rolandjitsu** [comment]
This error seems to be thrown only if I use the `.js` files at the root of the npm package. If I instead compile the ES6 files using traceur, for instance, I do not get the error anymore.

**Comment by rolandjitsu** [comment]
Just discovered that if I compile the `.ts` files (ignoring all the semantic errors thrown in the terminal), I have the same issue as described above. Only by transpiling the `es6/prod/**/*.js` files with traceur I will not get that error.

@mhevery any clues why this happens?

**Comment by gdi2290** [comment]
I ran into this problem too when including formDirectives

**Comment by rolandjitsu** [comment]
@gdi2290 if you compile the files from `es6/prod` (from the npm package) using traceur, the error will not get thrown anymore. I am not sure about `es6/dev` though.

Same issue if I compile the `.ts` files.

**Comment by gdi2290** [comment]
it looks like it's something to do with `renderer: Renderer` not being injected [default_value_accessor.ts#L39](https://github.com/angular/angular/blob/2.0.0-alpha.27/modules/angular2/src/forms/directives/default_value_accessor.ts#L39)

**Comment by rolandjitsu** [comment]
@gdi2290 I noticed. But it's strange, because I do use the `Renderer` in some other [component](https://github.com/rolandjitsu/ng2-play/blob/master/src/app/components/checkbox/checkbox.ts#L52) and it seems to be injected just fine.

**Comment by mhevery** [comment]
@vsavkin can you help out and close

**Comment by vsavkin** [comment]
I suspect it might be an issue with cyclic dependencies, where DefaultValueAccessor depends on `angular2/angular2`, which reexports forms. 

You can check if this is the case by changing `import {Directive, Renderer, ElementRef} from 'angular2/angular2'` to 

```
import * as ng from 'angular2/angular2';

export class DefaultValueAccessor implements ControlValueAccessor {
  value: string = null;
  onChange = (_) => {};
  onTouched = () => {};

  constructor(private cd: NgControl, private renderer: ng.Renderer, private elementRef: ng.ElementRef) {
    cd.valueAccessor = this;
  }

  writeValue(value) {
    // both this.value and setProperty are required at the moment
    // remove when a proper imperative API is provided
    this.value = isBlank(value) ? '' : value;
    setProperty(this.renderer, this.elementRef, 'value', this.value);
  }

  registerOnChange(fn): void { this.onChange = fn; }

  registerOnTouched(fn): void { this.onTouched = fn; }
}
```

**Comment by rolandjitsu** [comment]
@vsavkin actually that did not fix it, but the following helped:
```js
// import {Directive, Renderer, ElementRef} from 'angular2/angular2';
import { ElementRef } from 'angular2/core';
import { Renderer } from 'angular2/render';
import { Directive } from 'angular2/annotations';
```
Will you make this change to `default_value_accessor.ts` directive? Or should I make a pull request?

**Comment by gdi2290** [comment]
this is resolved and can be closed

**Comment by rolandjitsu** [comment]
@gdi2290 it is, I have tried to use both the `ts` and the `js` files from the npm package and it works.
