### ISSUE TITLE
Certain template errors don't return file path

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#26129]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

This is from https://github.com/angular/angular-cli/issues/11362

## Current behavior
```
ERROR in : Can't bind to 'ngI' since it isn't a known property of 'div'. ("
      <br/><br/>

      <div [ERROR ->]*ngI='edit.parent'>
        parent: {{edit.parent}}
      </div>
")
: Property binding ngI not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
      <br/><br/>

      [ERROR ->]<div *ngI='edit.parent'>
        parent: {{edit.parent}}
      </div>
")
```
## Expected behavior
The error should indicate the file path.

## What is the motivation / use case for changing the behavior?
Do a typo with *ngIf:
```html
     <div *ngI='edit.parent'>
        parent: {{edit.parent}}
      </div>
```

and run `ngc`.

The error doesn't indicate the file path that has the error.

## Environment

```
Angular version: 6.1.x
```

//cc @alexfung888

**Comment by pkozlowski-opensource** [comment]
In Angular v9 with ivy the file path is part of the error in such situations now: https://ng-run.com/edit/b9b7lSAh5Xy7Vcm8ByRs
