### ISSUE TITLE
No way to generate component's CSS source maps

### ISSUE THREAD

**Issue by x-yuri** [angular/angular#26123]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

In Chrome Developer Tools on the Elements tab I choose an element, and get the following styles:

![](https://i.imgur.com/FZH1l0S.png)

Clicking on the `<style>...</style>` part doesn't show me the corresponding stylesheet file.

## Expected behavior

The corresponding file is opened on the Sources tab.

## Minimal reproduction of the problem with instructions

* download the [Tour of Heroes](https://angular.io/generated/zips/toh-pt6/toh-pt6.zip), extract it and `cd` into corresponding directory
* `npm i`
* `./node_modules/.bin/ng serve --open`
* `Ctrl-Shift-C`
* click on `h1`
* click on `<style>...</style>`

## Why not angular-cli issue?

Let's say I have a SASS file for a component. The only way to pass source map to [`StyleCompiler`][1] is to inline it. So no option for [SASS][2]. That is achievable with [PostCSS][3], but I see no effort on the part of `StyleCompiler` to [try][4] and [parse][5] it. On top of that, Angular changes the stylesheet, so even if I managed to embed the source map, it's no longer relevant. While it might be not much of an issue for development build (not sure), it *is* an issue for production one (minified stylesheets). Am I missing something?

[1]: https://github.com/angular/angular/blob/6.1.9/packages/compiler/src/style_compiler.ts#L32
[2]: https://github.com/webpack-contrib/sass-loader/blob/v7.1.0/README.md#source-maps
[3]: https://github.com/postcss/postcss-loader/blob/master/README.md#inline
[4]: https://github.com/angular/angular/blob/6.1.9/packages/compiler/src/style_compiler.ts#L39-L45
[5]: https://github.com/angular/angular/blob/6.1.9/packages/compiler/src/style_compiler.ts#L77-L82

## What is the motivation / use case for changing the behavior?

Better development experience.

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [x] Chrome (desktop) version 68.0.3440.106
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.9.0  
- Platform: Arch Linux 

Others:

</code></pre>

**Comment by x-yuri** [comment]
Feature, you say...

**Comment by trotyl** [comment]
The feature is not quite viable in current architecture, the `<style>` content is generated at runtime when rendering:

https://github.com/angular/angular/blob/65943b458fa11a8d891b1dcee8ccf664038c485b/packages/platform-browser/src/dom/dom_renderer.ts#L43

As the content is not determined until the component being rendered, so the sourcemap also need to be generated at runtime, which is harmful for performance (both size and speed).

A possible solution is waiting for https://github.com/angular/angular/issues/14914, so that the css file could be exposed to build tool and let it deal with sourcemap chaining.

**Comment by alxhub** [comment]
Closing due to insufficient votes.
