### ISSUE TITLE
There is no release note in changelog about v6.1.8

### ISSUE THREAD

**Issue by Twois** [angular/angular#26130]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

There is no release note in changelog about v6.1.8

## Expected behavior

It should to contain the changes

## Minimal reproduction of the problem with instructions

Open the changelog.md file

## What is the motivation / use case for changing the behavior?

Its interesting to me what changes are happened

**Comment by macjohnny** [comment]
https://github.com/angular/angular/blob/6.1.8/CHANGELOG.md#618-2018-09-19
