### ISSUE TITLE
Cant use one module in multiple places in single page.

### ISSUE THREAD

**Issue by sathishkumar94** [angular/angular#26135]
For ex,

ObjectModule --> createModule --> render all attributes and input elements.

But my requirement,

when am clicking button in same page , need to open

+ --> objectModule -> createModule.

But its throwing a warning message like,
WARNING in Circular dependency detected:
src/app/common/object/object/object.create.module.ts -> src/app/common/create/create.module.ts -> src/app/common/object/object/object.create.module.ts

**Comment by sathishkumar94** [comment]
Is there anyway to access same module in same page with multiple places.??

Please respond me ASAP.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
