### ISSUE TITLE
Angular 5 Exist Static list Colomn data Push another List

### ISSUE THREAD

**Issue by HabeebinAli** [angular/angular#26132]
Sir,

I am Created a static list.

for example ListA=[{ Id: 1, Name: "Tawaf" } , 
  { Id: 2, Name: "Way to umra" },{Id: 3, Name: "Select" }]
    
Another ListB=[]  
Here ListB Column Name is SlNo and CustomerName
**How to push ListA Columns data to ListB using angular 5 Componets.ts??**

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
