### ISSUE TITLE
HTTP section skips a step creating in-memory-data.service

### ISSUE THREAD

**Issue by f8is2l8** [angular/angular#26146]
## I'm submitting a...

[X] Other... Please describe:

## Current behavior

https://angular.io/tutorial
Tour of Heroes Angular tutorial, HTTP step 8:
in-memory-data.service.ts is missing.
 
## Expected behavior

in-memory-data.service.ts is created in app folder.

## Environment

Solution:
Use the CLI to generate the service:
ng generate service InMemoryData --module=app

Found solution here:
https://stackoverflow.com/questions/39877282/cannot-find-module-in-memory-data-service-in-tour-of-heroes-for-angular2

**Comment by Nazanin1369** [comment]
I'd love to take this.

**Comment by chembu** [comment]
Fixed in docs: add missing instruction in HTTP section #25715
