### ISSUE TITLE
Feature: initialize app before components are compiled

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#26157]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Module bootstrap starts with compilation of module and it's components

## Expected behavior
`APP_INITIALIZER` functions should be called as soon as posible before components are compiled

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-pndlxe?embed=1&file=src/app/app.module.ts
You can see in the profiler that `INIT` function is called at the very end

## What is the motivation / use case for changing the behavior?
While components are compiled the app is blocked, but it doesn't mean it can't do anything useful in the meantime. You can fetch data from the server, preload resources or preload lazy loaded routes.
While it's possible to do make the calls before bootstrap, You won't have access to other services like `HttpClient`.

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [x] Chrome (desktop) version XX
</code></pre>

**Comment by trotyl** [comment]
What if some `APP_INITIALIZER` depends on compiled components?

```typescript
function createAppInitializer(cfr: ComponentFactoryResolver, injector: Injector) {
  return () => {
    cfr.resolveComponentFactory(MyComponent).create(injector, undefined, 'my-element')
  }
}
```

Also there's no more compilation stage in Ivy.

**Comment by trotyl** [comment]
> Maybe introduce new token then?

Sounds good to me if non-breaking, my only concern is would it be too short-lived for being introduced now and deprecated in Ivy?

**Comment by dawidgarus** [comment]
> Sounds good to me if non-breaking, my only concern is would it be too short-lived for being introduced now and deprecated in Ivy?

Would it be? It really depends on Ivy implementation detail of which I know little. If `APP_INITIALIZER` function are called as soon as possible - when `Injector` is ready, but before bootstrap component is rendered then it would be obsolete feature.

**Comment by trotyl** [comment]
In Ivy, the compilation is done during the decorator function call<sup>*</sup>, namely when the class being evaluated to a reference. Every time you refer to a component class it would always been compiled already.

So there's no way to hook before compilation, which just part of the synchronous `<script>` execution unrelated to the bootstrapping API.

*One exception is `templateUrl`/`styleUrls`, the compilation happens on XHR fulfilled.

**Comment by robwormald** [comment]
The premise of this question makes me nervous - compilation should happen at build time, so this shouldn't be an issue in real world applications and would seem to only affect JIT-compiled apps, no? (which is a bad idea in production...)
