### ISSUE TITLE
Please check the site https://code.angularjs.org/

### ISSUE THREAD

**Issue by vedavyasg507** [angular/angular#26153]
I'm submitting this issue considering security parameters as it is displaying the whole directory list and its contents at https://code.angularjs.org/.
It only displaying the content as a web page only after accessing some internal folders.
Hoping this would be updated to the new url (i am assuming based on .io extension for docs)

I was going through Angular js docs and other urls and found the issue. Hope it was worth mentioning.
![angularjs](https://user-images.githubusercontent.com/40467721/46194001-a8e75180-c31d-11e8-8c5f-a3c479680c3e.png)

**Comment by gkalpak** [comment]
code.angularjs.org is for [AngularJS][1] (i.e. 1.x). This repository is not Angular (i.e. 2+).
That said, the directory listing is [intended behavior][2] (not sure what security implications you have in mind).

[1]: https://github.com/angular/angular.js
[2]: https://github.com/angular/angular.js/blob/26ddc5f830f902a3d22f4b2aab70d86d4d688c82/scripts/code.angularjs.org-firebase/functions/index.js#L99-L155
