### ISSUE TITLE
platform-server depends on @angular/http but not in peerDeps

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#26154]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

`ServerModule` of `@angular/platform-server` depends on `HttpClient` of the old `@angular/http`. 
But its `peerDependencies` doesn't include it.

## Expected behavior

2 options

1. Add `@angular/http` to `peerDependencies`
2. Remove the dependency on `@angular/http` from platform-server. (breaking change)

## Minimal reproduction of the problem with instructions

https://github.com/angular/angular/blob/master/packages/platform-server/package.json#L15-L27

https://github.com/angular/angular/blob/master/packages/platform-server/src/server.ts#L13

## What is the motivation / use case for changing the behavior?

- Implicit peer dependency is not good.
- `@angular/http` is deprecated. 

## Environment

<pre><code>
Angular version: 6.1.9

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sarunint** [comment]
`@angular/http` should be add to peerDependencies of 6.x branch. In master, it should be removed.
