### ISSUE TITLE
Change @angular/common/http methods to use unknown

### ISSUE THREAD

**Issue by Barbiero** [angular/angular#26150]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

Currently, most HTTP methods(get,post,request etc) have a default implementation typed as `any`; however with typescript 3.0 support (#25275), we can now use the `unknown` type here to force whoever is using the method to type-check it's result.

This is a breaking change with the benefit of enforcing a strongly typed use of these methods. Calling them in their typed form (as in `get<Type>()`) would still work the same, since that overload would overwrite the `unknown`s.

Similarly, the `json`-version of these methods(currently with a return type of `Observable<Object>`) could also be turned into a return type of `Observable<unknown>`, although that sounds slightly dangerous since `unknown` includes primitives as well as objects. That said, since `unknown` forces type-checking anyway, I don't think it's a major problem -- and forces the user to typecheck properly instead of using a generic object.

For instances where the user does _not_ want to typecheck, they can still explicitly call the typed functions with `<any>` as their parameter type.

**Comment by alxhub** [comment]
I agree that we should do this. I need to investigate whether this would be a breaking change or not.
