### ISSUE TITLE
Service worker not caching project font files

### ISSUE THREAD

**Issue by oliveti** [angular/angular#26156]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>
The service worker does not cache project fonts, only external fonts are cached.

## Current behavior

Service worker is trigger a load of project fonts on every page load.

## Expected behavior

Service worker is caching internal font to not have to load it again.

## Minimal reproduction of the problem with instructions

Hard to provide a stackblitz for this. I integrate a screen capture.

<img width="1737" alt="screenshot 2018-09-28 at 11 34 59" src="https://user-images.githubusercontent.com/1235503/46200806-e4c8e980-c312-11e8-9696-eac095f950dd.png">

And a gitHub to reproduce issue : https://github.com/oliveti/angular-sw-font-bug

## What is the motivation / use case for changing the behavior?

Improve performances and pwa with internal fonts.

## Environment

<pre><code>
Angular version: 6.1.9

Browser:
- [X] Chrome (desktop) version 69
 
Thank you

**Comment by gkalpak** [comment]
I tried with your project and it works correctly. Maybe your screenshot is before the SW had a chance to cache all the assets.

**Comment by oliveti** [comment]
Hi,

Sorry but does not come from angular, that's an issue with the web server we use 'live-web-server', it is not setting the content type for fonts.

Here is a link to the issue I created on their repo : https://github.com/lwsjs/local-web-server/issues/102
