### ISSUE TITLE
using '/' as path in @RouteConfig causes component to be rendered two times

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#2615]
I just noticed after I update to version alpha `27` that if I have the following `@RouteConfig`:
```js
@RouteConfig([{
    component: Test,
    path: '/',
    as: 'test'
}])
```
I will see two of the same component, but if I change the path to anything else I do not get the same behaviour.

**Comment by gdi2290** [comment]
I have this too. I ended up redirecting to what was suppose to be my home route

```es6
@RouteConfig([
  { path: '/',  redirectTo: '/test' },
  { component: Test, path: '/test', as: 'test' }
])
```

**Comment by rolandjitsu** [comment]
@gdi2290 yep, I am doing the same thing, I am redirecting to a different route.

**Comment by rolandjitsu** [comment]
@gdi2290 I just updated to alpha `28` and it seems like this issue is fixed. But I am not absolutely sure, @mhevery?

**Comment by lnlwd** [comment]
I'm using this way:
```typescript
@RouteConfig([
  { path: '/',          as: 'home',      component: HomeComponent }
])

export class App {
  router: Router;
  constructor(router: Router, location: Location) {
    // we need to manually go to the correct uri until the router is fixed
    this.router = router;
    let uri = location.path();
    if (uri === '' || uri === '/') {
      router.navigate('/home');
    } else {
      router.navigate(uri);
    }
  }
}
```

It's working fine, but if i use `router.navigate('/')` i get duplicated object too

Anyway i'm using this 'hack' until problem is solved...

Sorry my bad english!

:smile:

**Comment by rolandjitsu** [comment]
@lnlwd if you use alpha version `28` you no longer need to use the following:
```js
this.router = router;
let uri = location.path();
if (uri === '' || uri === '/') {
    router.navigate('/home');
} else {
    router.navigate(uri);
}
```

**Comment by lnlwd** [comment]
Ok, really the problem is solved, no more duplicated items...

**Comment by btford** [comment]
I'm going to close this since @lnlwd isn't seeing this anymore.
