### ISSUE TITLE
removing 'as' from a route config throws exception

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#2616]
If I remove the `as` key from a route config or if the alias name is different from the path name, I will get the following exception:
![screenshot 2015-06-18 14 16 50](https://cloud.githubusercontent.com/assets/1479737/8230905/c60b3a74-15c4-11e5-9c82-6208be798bac.png)

**Comment by btford** [comment]
What version of Angular? And can you please provide a reproduction?

**Comment by rolandjitsu** [comment]
@btford yes, [here](https://github.com/rolandjitsu/ng2-play/blob/master/src/app/components/app/app.ts) is where I use it, but this exception occured one version back at alpha `29`. I am not sure if it still happens.

**Comment by btford** [comment]
@rolandjitsu Can you try with the latest and let me know if it's still broken?

**Comment by rolandjitsu** [comment]
@btford I will do it today with the latest release and I will close this if it doesn't happen anymore.

**Comment by rolandjitsu** [comment]
@btford now it complains about `TypeError: Cannot read property 'url' of null in [['./todos'] in null]` where I have my route config:
```js
let routes: IRoutes = [
    {
        component: Todos,
        path: '/'
        // as: 'todos'
    }
];
```
and I try to get the url by using:
```html
<a [router-link]="['./todos']">Todos</a>
```

**Comment by btford** [comment]
Hmmm.

Can you post a small reproduction somewhere so I can debug?

**Comment by rolandjitsu** [comment]
@btford it's in the same [repo](https://github.com/rolandjitsu/ng2-play), I just updated to latest (alpha `31`) and I tried to remove `as`. You can clone it and try it (I used Chrome `44.0.2403.89`).

**Comment by btford** [comment]
Great. Thank you!

**Comment by btford** [comment]
This'll take a bit of time for me to investigate, but I've tentatively slated a fix for alpha-33.

**Comment by btford** [comment]
I have some time today, so I'm going to try to reproduce.

**Comment by btford** [comment]
This is already improved in master via 8bdca5c03ef675dfcc39111cf3429904711ab507, specifically here: https://github.com/angular/angular/commit/8bdca5c03ef675dfcc39111cf3429904711ab507#diff-b9cb9abe596c64a002082ac6c05d696eR182

Instead of the NPE, you'll get a message like `AppCmp has no route named "todos"`.

**Comment by rolandjitsu** [comment]
@btford but there is a route config, so what I don't understand is why does it throw the exception since the route is configured?
