### ISSUE TITLE
OutputPath sub-directories are needed for real world deployment.

### ISSUE THREAD

**Issue by gitdisrupt** [angular/angular#26160]
[ X] Performance issue
[X ] Feature request

Simply put, if Angular is going to work in the real world, we need more granular control over the build process.

My server administrators have a strict requirement that all of my assets, js and css live on a CDN.

The `--deploy-url` flag would suffice except for the fact that this requirement specifies that my JS and CSS live in their own respective subdirectories. `/js` and `/css`

## Current behavior

`ng build --prod --deploy-url MY_CDN`

Unless i am missing something in the Angular documentation, it seems as though my only option for moving my JS and CSS to respective sub-directories is to use a task manager to modify the compiled files to achieve something seemingly so simple. 

Id have to modify the deploy url in my compiled `runtime.js` for starters.
Obviously this is not ideal. Id really like to avoid this approach but i am out of time. ugh.

## Expected behavior
Id like to be able to specify where to output my JS and CSS files, I am assuming somewhere in my `angular.json` config.

## What is the motivation / use case for changing the behavior?
A real world use case.

## Environment
Angular CLI: 6.2.3
Node: 8.11.4
OS: darwin x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/.DS_Store         <error>
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.4.7
@angular/cli                      6.2.3
@angular/pwa                      0.6.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.8.3
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.8.3

**Comment by trotyl** [comment]
Wrong repo, please report it to https://github.com/angular/angular-cli.

**Comment by gitdisrupt** [comment]
Apologies, moved here:
[https://github.com/angular/angular-cli/issues/12407](url)
