### ISSUE TITLE
angular with php

### ISSUE THREAD

**Issue by imsheng** [angular/angular#26175]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

How to make a dynamic web page ， just like angularJS,vue
I need to make a dynamic web page in PHP.
But I don't know how to use it.
https://angular.io/guide/browser-support#polyfills-for-non-cli-users

```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>MyApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="node_modules/core-js/client/shim.min.js"></script>
  <script src="node_modules/zone.js/dist/zone.js"></script>
</head>
<body>
  <h1>{{title}}</h1>
  <script>
  // ?
</script>
</body>
</html>
```

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
