### ISSUE TITLE
Updates to docs to align with RxJS updates

### ISSUE THREAD

**Issue by reidreid46** [angular/angular#26182]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Documentation for Angular 6 uses references to setting up observables using "Observable.of". However, the version of RxJS that Angular 6 uses means the right way to use that function is to drop "Observable" and just use "of".

## Expected behavior
References to using the "of" function should just be "of", not "Observable.of"

## Minimal reproduction of the problem with instructions
Visit page in browser: https://angular.io/guide/observables
Search for "Observable.of"

## What is the motivation / use case for changing the behavior?
Inaccurate documentation leads to confusing, and inoperable code examples.

## Environment

<pre><code>
Angular version: 6.1.9

Browser:
- [X ] Chrome (desktop) version XX
- [ X] Chrome (Android) version XX
- [ X] Chrome (iOS) version XX
- [ X] Firefox version XX
- [ X] Safari (desktop) version XX
- [ X] Safari (iOS) version XX
- [ X] IE version XX
- [ X] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by siddhant1** [comment]
Working on this one . Can you tell me the source file where the documentation is written.
PS :- Sorry I am just starting out

**Comment by gkalpak** [comment]
Thx, @siddhant1 ❤️

On the top right corner of each guide, there is a button that sents you to the corresponding file on GitHub to edit. Generally, the source files for the guides are in https://github.com/angular/angular/tree/master/aio/content/guide.

**Comment by brandonroberts** [comment]
Fixed via https://github.com/angular/angular/pull/26238
