### ISSUE TITLE
fromEvent callback always runs inside angular zone

### ISSUE THREAD

**Issue by FDIM** [angular/angular#26187]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Any event that you subscribe outside angular zone using `fromEvent` triggers change detection
```
this.zone.runOutsideAngular(()=> fromEvent(this.elementRef.nativeElement, 'click')).subscribe(()=>{
  // change detection is not needed after this code runs
});
```

## Expected behavior

Change detection should not run

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-lw51rb?file=src%2Fapp%2Fhello.component.ts

You'll find 2 clickable headers in the example, clicking on either of them should not trigger change detection. Currently it does when you click the first one.

## What is the motivation / use case for changing the behavior?

It should be possible to subscribe to any event using rxjs and avoid triggering change detection. 

Possible workaround is to use `addEventListener` \ `removeEventListener` directly or [custom observable factory](https://stackblitz.com/edit/angular-lw51rb?file=src%2Frxjs.utils.ts)

## Environment

<pre><code>
Angular version: 6.1.9

Browser: any

Others:

</code></pre>

**Comment by Eusen** [comment]
you can try this:
'''
fromEvent(this.elementRef.nativeElement, 'click')).subscribe(()=>this.zone.runOutsideAngular(()=> {
  // change detection is not needed after this code runs
});
'''
click will inevitably trigger detection

**Comment by JiaLiPassion** [comment]
@FDIM, the reason is your `subscribe` code is run inside `ngZone`. 
```
clicks.subscribe(() => {
      this.counter++;
});
```

`rxjs` is `lazy`, and it will only call `addEventListener` when you `subscribe` the observable returned from `fromEvent`.

So you need to 
```
this.zone.runOutsideAngular(()=> {
    clicks = fromEvent(this.elementRef.nativeElement, 'click');
    clicks.subscribe(() => {
      this.counter++;
    });
});
```

**Comment by FDIM** [comment]
@JiaLiPassion Thanks! That makes perfect sense. It's still a bit weird behavior though, but I guess this is one of those things that you just have to remember.
