### ISSUE TITLE
perf(SystemJS): create SystemJS benchmarks

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2618]
We should have benchmarks that test SystemJS loading of bundled and unbundled Angular, using an HTTP/1.1 server and an HTTP/2 server. Benchpress should collect script time and network time information.

**Comment by gdi2290** [comment]
bootstrapping on mobile takes way longer so I think that should have a high priority if possible.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
