### ISSUE TITLE
[Discuss] Some views on Angular

### ISSUE THREAD

**Issue by Eusen** [angular/angular#26185]
1. routing system is not perfect. The performance of the routing system on the PC side is still good, but the performance on the mobile side is somewhat unsatisfactory.

2. @angular/animation is a bit cumbersome, and the animation system accounts for nearly 70kb after compression. 
![image](https://user-images.githubusercontent.com/14822175/46265420-ec79cf80-c558-11e8-8772-bb81d552a742.png)
Complex usage leads to low utilization. CSS is enough for some needs. It is better to bind the life cycle of a component to its class, such as birth and death.

3. I think some parts can continue to be streamlined. It is also important to reduce complexity and improve flexibility. Some functions can be implemented within the framework only by making some modifications.

4. Dynamically loading modules and components. I hope to dynamically manage modules and components in the project, and even manage them after running.
It's also important that if angular can be loaded dynamically, the Cordova hot update doesn't require a native plug-in at all. If this can be achieved, I think it will be wonderful.

5. Share components, directives and pipes. If dynamic loading is difficult to implement, share the internals, and I hope I can create components directly in module A without importing them after loading module B. I know this may be a problem of renaming, but throwing an exception at compile time 
 or runtime effectively alerts people to change names. After all, there are too many ways to name, and the problem of duplication is not particularly serious.

6. I hope angular‘s system will be more open, and the limited structure will make more possibilities disappear.

...to be continued.

**Comment by StephenFluin** [comment]
Thanks for the feedback @Eusen. It's always useful to hear what developers care about. I won't touch this issue for now so that it can be commented on, but feel free to email us at devrel@angular.io if you want to share more details or specific use cases.

**Comment by andrewtw** [comment]
@Eusen Can you elaborate the routing performance issue?

**Comment by Eusen** [comment]
Sorry, I'm on holiday recently. I'll give you some examples in detail in the next few days. Thanks for your reply!

**Comment by Eusen** [comment]
It's 0 a.m. Beijing time. I am so sorry because I am busy with my work, it is hard to find nice time to reply this topic in detail.

**But today, I don't want to delay it any longer.**

This time I would like to elaborate on two points, **Router** and **Module**. These two points often make me feel awkward when I design my own UI framework.

**1. Router**
In the current Angular2+ system, routing is divided into two main camps: the ionic camp and the angular camp.

I went through the upgrade from angularjs to angular2+ to angular7.x. Also experienced the growth of ionic2 to ionic3. I'm probably more familiar with ionic 2-3 than you might imagine, because over the course of a year, I've tried to build a mobile and browser-based, highly efficient UI framework based on ionic 2-3.

I chose ionic as the foundation, to be honest, I took a fancy to its routing system: it's really convenient. It doesn't require complicated configuration, and it automatically adds IonicPage to the page, which greatly reduces the cost of building the project.

But after many attempts, I gave up ionic. I don't need it because it's so much integrated, and although I've tried to modify the source code, it's hard to get popular and upgrade.

But what really bothers me most is that ionic implies a lot of bugs, and when we apply it to a business project, a small bug, and a bug in the framework, is often insane. Because it may take three or four days to repair, but our project can't wait for so long. If you change the source code, it can not be applied to all projects. So, I can not control the details of implementation, and can not quickly update the repair, let me decide to return Angular.

I wanted my UI framework to be extremely streamlined, efficient, and in control of the implementation details, so I went back to Angular and built the framework on Material as the UI foundation.

**OK, let's return to the theme**. The most fatal aspect of Angular routing is the concept of no stack. Maybe this is to keep the number of tags in DOM as few as possible. I think that's a good thing to do. But it does not apply to all situations.

At present, there are only two kinds of pages in Angular: **birth** and **death**.

But in the mobile terminal, there are four kinds of pages: **birth**,  **sneak**, **emerge**, and **death**.
1. Birth and death need not be explained.
2. **Sneak**: occurs when new page enters, original page state remains. The current alternative is to use MatDialog to pop up new pages. But this way is not very convenient.
3. **Emerge**: the death of the new page occurs, and the original page appears again.

So, I say router-outlet is not perfect, that's why.
I hope router-outlet can realize the sneak and emerge of the page.

**Comment by Eusen** [comment]
**2. Module**
I think I am most proud of the dynamic module loading that I tried in Ionic2-3. But it only works with a compiler, so this one that I'm proud of was eventually abandoned.

The specific way to achieve this is to let each module be allocated to different blocks independently.
Like this:
```
0.js // MatModules
1.js // NgZorroModules
2.js // JQuery
```
Then I intruded and controlled the loading of the routing. When the page(10.js) needed to be displayed, and it relied on MatModules(0. js) and JQuery(2. js), I will loaded (0. js) and (2.js) first, and managed the MatModules, and loaded JQuery libraries into Windows.

When the page(10.js) loaded, it could take MatModules directly from my module manager and inject them into the module.

Because there are compilers, everything happens all the time. The benefit is obvious, too, that you can start with very, very few things to load, and then you can load different modules dynamically according to your needs.

However, because of the inability to AOT, the plan was undoubtedly rejected.

Although the plan has been rejected, the problem still exists. How can we make the boot load code minimal? How do you load modules dynamically?

At present, I think of a library solution is to use cnd, the library host link with script dynamic introduction. But there is still no good way to load dynamically between modules.

**Comment by Eusen** [comment]
At present, the functions I hope to achieve are:

1. I can create a page directly. Instead of creating a module first, create a component and then link it up.

2. I can write <button mat-button></button> directly on the page, and the editor can pop up a small window to tell me what modules to import, and then I click the improt button directly to add the modules automatically. The same is true for service. I hope I can import it myself. Just one of the latest popular jokes: You're a full-fledged editor, and you can write, test, maintain, and publish projects yourself.

**Comment by Eusen** [comment]
@StephenFluin Hi there!

I share some content here. If you have time, you can have a look.

**Comment by Eusen** [comment]
Finally, I want to talk about what I want to do in the future: replace Cordova + Angular. with Flutter + Angular.

I think Flutter must be more suitable for cross platform than Cordova. So when I finish the Angular mobile terminal framework, I will spend time studying this. If implemented perfectly, it will definitely be the best solution for mobile App in the future.

**Comment by Eusen** [comment]
I think my ideal module, like JQ, should be able to be introduced directly with script tags and be used in other modules. This is a bit like NG1. If modules can be loaded through an external chain, then modules can be published on the cdn, as small as modules can be, right?

**Comment by Eusen** [comment]
@StephenFluin  @alxhub @andrewseguin  @jenniferfell

**Comment by atscott** [comment]
Hi @Eusen, thanks for your input on how you think the framework can be improved! Could you please separate these points into new, separate issues? This issue contains too many points that cannot be triaged into component buckets and isn't actionable in its current state.
