### ISSUE TITLE
[Language Service] Template reference without assignation should show an error

### ISSUE THREAD

**Issue by michaeljota** [angular/angular#26190]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

If you have a template reference without an assignation is a runtime error: `Error: Failed to execute 'setAttribute' on 'Element': '#' is not a valid attribute name.`

## Expected behavior

This should be considered as a non intentional typo from the developer, and such, it should be showed as a static error by the language service. 

## Minimal reproduction of the problem with instructions

[Repo](https://stackblitz.com/edit/angular-template-reference-unassigned)

## What is the motivation / use case for changing the behavior?

It seems right to get this kind of errors in as static errors as we could catch them better. Is really hard to understand what `'Element': '#' is not a valid attribute name.` in runtime. 

## Environment

<pre>
Angular version: 6.1.9

Browser:
All
 
For Tooling issues:
- Node version: 8.10.0 LTS
- Platform:  Windows 10 April Update

Others:

</pre>

**Comment by kyliau** [comment]
tracking this in https://github.com/angular/vscode-ng-language-service/issues/293
