### ISSUE TITLE
Conditional FormControls with Validation in ReactiveForms 

### ISSUE THREAD

**Issue by Jensiator** [angular/angular#26192]
## I'm submitting a...
<pre><code>
[x ] Bug report  
</code></pre>

## Current behavior
Adding conditional form control validation using:
<pre><code>
this.group.addControl("ValidFrom",new FormControl("",Validators.required));
</code></pre>
Will not add any Validation to the Form and the FormControl
But doing this will:
<pre><code>
this.group.addControl("ValidFrom", new FormControl(""));
this.group.get("ValidFrom").setValidators(Validators.required);
</code></pre>

## Expected behavior
<pre><code>
this.group.addControl("ValidFrom",new FormControl("",Validators.required));
</code></pre>
Should set the form to invalid, if no value is provided for 'ValidFrom' , because the second constructor parameter of the FormControl is its validators.

## Minimal reproduction of the problem with instructions
Create a very simple Reactive form. Add a 
<code><select formControlName="Type" (change)="onTypeChange()"></code>

And in In typescript:

<pre><code>
public onTypeChange(): void {
		if (this.form.get("Type").value !== "X") {
			this.form.removeControl("ValidFrom");
			this.form.removeControl("ValidTo");
		} else {
			this.form.addControl("ValidFrom", new FormControl(""));
			this.form.get("ValidFrom").setValidators(Validators.required);
}
</code>
</pre>

## What is the motivation / use case for changing the behavior?
Dynamic form validation using Reactive Forms. Ex: Switching a select that adds an extra formcontrol with validation.
## Environment

<pre><code>
Angular version: 6.1.0
Browser:
- [x ] Firefox version XX
 
For Tooling issues:
- Node version: v8.11.4
- Platform:  Windows

Others:
IntelliJ IDEA

</code></pre>

**Comment by NetanelBasal** [comment]
It's working as expected. Live example: https://stackblitz.com/edit/angular-reactive-forms-tdgjal

**Comment by kara** [comment]
@Jensiator As far as I can tell, this is working as intended. See https://stackblitz.com/edit/angular-mrng7i?file=src%2Fapp%2Fapp.component.ts (@NetanelBasal your link wasn't working for me for some reason).

If you still think there's a bug, please open a new issue with a minimal repro in Stackblitz so we can investigate.
