### ISSUE TITLE
POST request payload empty for ArrayBuffer

### ISSUE THREAD

**Issue by Blazingspike** [angular/angular#2619]
Hi there,

I tried to use POST to send some bytes using ArrayBuffer, but it seems that the request payload is always empty. Here's some code snippet:

var buffer = new ArrayBuffer(10);
var request = {
  method: 'POST',
  url: '/api/get_recent_hottos',
  headers: {'Content-Type': 'application/octet-stream'},
  data: buffer,
  responseType: 'arraybuffer'
};
$http(request)
  .success(function(data, status, headers, config) { ... })
  .error(function(data, status, headers, config) { ... });

Any one has some ideas or suggestions? Thanks in advance.

**Comment by pkozlowski-opensource** [comment]
@Blazingspike:
* this is wrong repo, you are looking for https://github.com/angular/angular.js
* general support questions should be asked using a dedicated support channel: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
