### ISSUE TITLE
Uncaught Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by asnov** [angular/angular#26204]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have an runtime error `Uncaught Error: Cannot find module 'tslib'` in a production build using Angular 6 CLI when I am using default startup project and third party npm typescript library compiled with the default settings:
```
"importHelpers": false,
"noEmitHelpers": false,
```
Full tsconfig.json is available here: https://github.com/ethers-io/ethers.js/blob/typescript/tsconfig.json

Commands I'm using for production build: `ng serve --prod` or `ng build --prod`.
In development build (`ng serve` or `ng build`) the same code works fine.

## Expected behavior

`ng serve --prod` and `ng build --prod` expected to work without errors like `ng serve` and `ng build`.

## Minimal reproduction of the problem with instructions

*STEPS TO REPRODUCE* 
I'm generating standard cli starter project with the library:
```
ng new angular-tslib-issue
cd angular-tslib-issue
yarn add ethers@4.0.0-beta.15
```
then I add somewhere these test code, for example in the src/app/app.component.ts:
```typescript
import {ethers} from 'ethers';

  constructor() {
    const bn: ethers.utils.BigNumber = ethers.utils.bigNumberify(1);
    console.log(`BigNumber=`, bn);
  }
```
Then `ng serve` works fine but `ng serve --prod` gives me an `Cannot find module 'tslib'` error:
```
Uncaught Error: Cannot find module 'tslib'
    at o (main.34e371fac685d31927eb.js:1)
    at main.34e371fac685d31927eb.js:1
    at Object.Fkem.e.exports.4../abstract-signer (main.34e371fac685d31927eb.js:1)
    at o (main.34e371fac685d31927eb.js:1)
    at main.34e371fac685d31927eb.js:1
    at Object.Fkem.e.exports.6../_version (main.34e371fac685d31927eb.js:1)
    at o (main.34e371fac685d31927eb.js:1)
    at main.34e371fac685d31927eb.js:1
    at Object.Fkem.e.exports.7../ethers (main.34e371fac685d31927eb.js:1)
    at o (main.34e371fac685d31927eb.js:1)
```

*MINIMAL DEMO* 
I prepared a small repo to demonstrate the issue: https://github.com/asnov/small-test

I also created an issue in the library repository: https://github.com/ethers-io/ethers.js/issues/278 but I believe this is a Angular CLI bug when it runs webpack with wrong config.

## What is the motivation / use case for changing the behavior?

When Typescript compiles the library it puts tslib helpers inline to the result file:
```javascript
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
```
So this looks fine and works fine.
Then Angular CLI runs webpack which includes all libraries to the vendor.js file, sees the repeated helpers code, tries to optimize the build and removes the helpers code.
It seems reasonable to replace all inline helpers with the calls to tslib functions.
The problem, as I understand, is that it does not include tslib library code to the resulted build so the library link does not resolved in runtime.

## Environment

<pre><code>
Angular version: 6.2.0
This is still an issue in the most recent Angular version.

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version XX
- [X] Safari (desktop) version XX
- [X] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.11.2
- Platform:  Mac

</code></pre>

**Comment by dawidgarus** [comment]
You should report it in angular-cli repo: https://github.com/angular/angular-cli

**Comment by asnov** [comment]
Done: https://github.com/angular/angular-cli/issues/8442
Should I close it here?

**Comment by asnov** [comment]
Moved it to angular-cli repo.
