### ISSUE TITLE
Animations guide: user goals and tasks to add or refine

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#26214]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

*This issue is a collection place for other specific animations guide/cookbook tasks our readers would like to see. We'll collect for a bit here, so we can get a sense of priorities. Feel free to add your suggestions as comments, or to thumbs-up and second suggestions from others!*

In September, we released a rewrite of the animations guide, which includes these major sections: 

https://angular.io/guide/animations
https://angular.io/guide/transition-and-triggers
https://angular.io/guide/complex-animation-sequences
https://angular.io/guide/reusable-animations
https://angular.io/guide/route-animations

## Expected behavior

Our goal was to move toward:
* A more defined introduction - defining key concepts and getting a small animation working
* Subsequent sections focused more on app goals ("do this kind of thing in my app") than on Angular code constructs ("using this part of Angular"). 

We made progress, but there's always more to do. Even the "do this kind of thing in my app" can be phrased in the docs based on what the user sees ("show fireworks animation when user is successful") or based on HTML/CSS concepts that are universal to web programmers ("using keyframes").

The next step for improving these docs is feedback from readers/developers. What goals or tasks are you trying to do? How do you think of (talk about, look up) those tasks or goals? Where should we consider repositioning content that we have to focus slightly differently, to be easier to recognize that this what you need to read to do what you want?

## What is the motivation / use case for changing the behavior?

Continue improving doc to be easy to use when creating real-world apps. To better accelerate key development tasks. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
Starter suggestions from Twitter 
@NutonDev Sep 21
"Great start! I would hope to find recipes there at some point, such as: crossfades, animating routes, add/remove a list item with animation, globally disabling animations (a11y), etc."
"And obviously examples as embedded playable stackblitzes or at least animated gifs, please :)"

**Comment by jenniferfell** [comment]
@chembu @matsko I assigned you both, so you can also monitor this issue. If you prefer to monitor using "follow", feel free to unassign yourself. :-)

**Comment by ajitsinghkaler** [comment]
@kapunahelewong @matsko Can I take this

**Comment by kapunahelewong** [comment]
Thanks for the offer, @ajitsinghkaler, but the scope of this issue has expanded to include the docs in general and is currently serving as a guide post or reminder as we re-work and re-think the presentation of the content of the site as a whole and how readers search for and find what they need. We are currently in conversation on the docs team on how to best proceed with these ideas in mind. So it isn't a candidate for a single PR, rather it is a note about a principle to keep in mind as we work with the content. 

That said, if you have ideas about how we could improve in this regard, we'd love for you (and others) to post them here or in new issues so we can be sure to include your thoughts as we try things out.

**Comment by intellix** [comment]
don't know if this issue will ever get seen again, but one annoying thing about the Animations documentation is that all of the complex/useful examples were on @matsko personal blog site: yearofmoo.com in the post: `Angular animations: New wave of features` of which is now a dead URL. 

Are there any plans to perhaps bring it back up or port over some of those examples into the angular.io docs?

**Comment by petebacondarwin** [comment]
@aikidave - what do you think about this request from @intellix ? Perhaps we could ask @matsko  to send over the content from the URL that no longer works? Or perhaps grab it from the WayBackMachine?
