### ISSUE TITLE
Move environment.ts out of the build

### ISSUE THREAD

**Issue by kayvanbree** [angular/angular#26212]
I could not find the same issue in the 2177 issues currently on this repository, so I created one. I don't know if this would be the best solution to my problem, this is a suggestion to my problem. If there are better solutions I'm open for everything right now. 

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

You cannot edit settings after the Angular build is done. To be able to deploy the same Angular build to different environments, you need to hack your way to a workable solution.

## Expected behavior

Environment.ts (or environment.prod.ts) should not be included in the build but rather be a separate file, like polyfills and the css file. This way you should be able to run your site in a different subdirectory, use another API, use another license, etc. Environment.ts should just be a file in your dist folder that you can change after the build was made. 

## What is the motivation / use case for changing the behavior?

Currently, it is not possible to configure Angular after the build is done. Environment variables don't do anything because Angular's code is not running on the server, or a Docker container. It's running in the client's browser. This gives a lot of problems for people trying to run Angular in different environments. 

### Running in a subdirectory

At the moment, I'm trying to run the same Angular application on a server on `http://somedomain.com/` and `http://somedomain.com/subdirectory`. Currently, that's impossible to do without hacking something together. At the moment we have 2 environments, but our application needs to be deployed on several servers for several customers. I know this is not a niche problem, as there is tons of Google results on this subject. 

### Licenses

Some software vendors (like Wijmo) require you to get a license key for every domain you use. Currently, you'd have to rebuild for every domain.  

### Different API's

Sometimes you need a different API url for every environment. A co-worker solved this by re-routing `/myapi` to `http://myapi.com/api/` in his nginx installation. I don't like this way as I want to be able to just docker-compose up my containers and have it work out of the box with some environment settings for a proxy container.

**Comment by trotyl** [comment]
Please make this feature request to https://github.com/angular/angular-cli, the project structure and build steps are not related to this repo.

**Comment by kayvanbree** [comment]
I will. Thanks!
