### ISSUE TITLE
Unable to fetch to third level array filter using pipe

### ISSUE THREAD

**Issue by Sushilagale123** [angular/angular#26228]
return items.filter(it =>
                Object.keys(it).some(k => it[k] != null &&
                    it[k].toString().toLowerCase().includes(searchText)) || Object.keys(it).some(k => it[k] != null &&  Object.keys(k).some(gt => it[k][gt] != null &&
                        it[k][gt].toString().toLowerCase().includes(searchText)))
            );

Array sample =[1,2,3,xyz[1,2,3,8,9, abc[ a,,b,c,]]]

Need to access all the element using searchText

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
