### ISSUE TITLE
ng build library failed...

### ISSUE THREAD

**Issue by bit-warrior** [angular/angular#26229]
I am trying to build this libraray with external js libraray dependency
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(scripts)
```
"ng-somelibraray": {
      "root": "projects/ng-somelibraray",
      "sourceRoot": "projects/ng-somelibraray/src",
      "projectType": "library",
      "prefix": "av",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "projects/ng-web3/tsconfig.lib.json",
            "project": "projects/ng-web3/ng-package.json",
            "scripts": ["src/lib/external.js"]
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "projects/ng-web3/src/test.ts",
            "tsConfig": "projects/ng-web3/tsconfig.spec.json",
            "karmaConfig": "projects/ng-web3/karma.conf.js"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "projects/ng-web3/tsconfig.lib.json",
              "projects/ng-web3/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
```

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.9.0-rc.1
@angular-devkit/build-angular      0.9.0-rc.1
@angular-devkit/build-ng-packagr   0.9.0-rc.1
@angular-devkit/build-optimizer    0.9.0-rc.1
@angular-devkit/build-webpack      0.9.0-rc.1
@angular-devkit/core               7.0.0-rc.1
@angular-devkit/schematics         7.0.0-rc.1
@angular/cli                       7.0.0-rc.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.0-rc.1
@schematics/angular                7.0.0-rc.1
@schematics/update                 0.9.0-rc.1
ng-packagr                         4.2.0
rxjs                               6.2.2
typescript                         3.1.1
webpack

**Comment by alxhub** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
