### ISSUE TITLE
HttpInterceptor: Intercepted result don't contain HttpResponses

### ISSUE THREAD

**Issue by jjdf01** [angular/angular#26227]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When doing a call that times out i am not getting an error, the success part of the observable is called, als i dont get a HttpRespone but an object like this: { type: 0 } 

Consider in the following code this gets logged:
response is not http repsonse: { type: 0 }
I looked at this issue and it is very similar only the conclusions are not what i am seeing in my app:
https://github.com/angular/angular/issues/18098

` intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {

        return next.handle(request)

            .pipe(tap(response => {

                if (response instanceof HttpResponse) {

                    this.onSuccess(request.url);

                } else {
                    // this is where i end up with a timeout and response is { type: 0 }
                    Logger.info('response is not http repsonse: ', response);

                }
            }, error => {
                if (error instanceof HttpErrorResponse) {
                    this.onError(error, request.method, request.url);
                } else {
                    // should end up here
                    Logger.info('error is not HttpErrorResponse: ', errorResponse);
                }
            }, () => Logger.info('complete')));
    }`

## Expected behavior

At least this should come back in the error channel of the observable. I do not consider a timout a success. Also this could be a HttpError (not a response error since there is no response).

## Environment

<pre><code>
Angular version: 6.1.1

Browser:
- Cordova on IOS so it is IOS Safari of iPhoneX
 
For Tooling issues:
- Platform: Cordova

Others:

</code></pre>

**Comment by alxhub** [comment]
`0` is `HttpEventType.Sent`. It's an event indicating the request has been fully sent to the server.

**Comment by jjdf01** [comment]
maybe it is the F5 firewall cutting of the response

**Comment by fxck** [comment]
How do you catch error on `handle()` then? I want to `handle().pipe(tap(dosomething))`, but tap triggers despite `handle()` resulting in another error..
