### ISSUE TITLE
problems with template driven form validation in custom component

### ISSUE THREAD

**Issue by westor21** [angular/angular#26223]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
The validation of input field and the surrounding form in a custom constrol with controlValueAccessor seems to be buggy.

## Expected behavior
Input and Form should have consistent informations about validity, dirty etc.

## Minimal reproduction of the problem with instructions
I have a custom component with input and ControlValueAccessor implementation.
The input has two validations: **required** and **minlength="9"** and the **ngModel** directive for validation.
The outer form displays the current form properties.

The inital value is set with the value "initial", therefore I would expect the following model error state:
ModelErrors: { "minlength": { "requiredLength": 9, "actualLength": 7 } }
Instead minlength is not validated correctly, but required is also not validated correctly because ModelErrors shows: { "required": true }
When I focus the input and change one letter, the validation is correct.
But the it comes to the next problem: **The error state of the control is not reflected in the surrounding form.**

The following stackblitz demonstates the problem:
https://stackblitz.com/edit/angular-form-validation-problem

## Environment

<pre><code>
Angular version: 6.0.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by kara** [comment]
@westor21 In your example, it looks like your control value accessor isn't implementing the necessary `Validator` interface. The implementations of custom control value accessors are encapsulated by design, so value accessors must use the `Validator` API to expose internal state with parent forms.  See example of how to fix here: https://stackblitz.com/edit/angular-form-validation-problem-nnp9nn?file=src%2Fapp%2Fmy-input.component.ts

Closed, as this is working as intended.

**Comment by westor21** [comment]
For the sake of completeness: @kara I completed the example here, and now it ist working like expected:
https://stackblitz.com/edit/angular-form-validation-problem-euavmr
Thank you for the hint regarding using of validator API.
