### ISSUE TITLE
"ng build --prod" Error when destructuring an array from namespace

### ISSUE THREAD

**Issue by mcherb** [angular/angular#26222]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have this namespace
<pre><code>
export namespace Anamespace {
  export const Components = [
    AComponent1,
    AComponent2
  ];
}
</code></pre>
in another file a declared a module that uses the namespace above

<pre><code>
@NgModule({
  declarations: [...Anamespace.Components],
  exports: [...Anamespace.Components]
})
export classe Amodule{}
</code></pre>

when running "ng serve" everything works fine. But when running "ng build --prod" i get this error:

ERROR in Error during template compile of 'Amodule'
  Unsupported import syntax.

## Environment

<pre><code>
Angular version: ^5.2.11

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.3  
- Platform:   Linux

Others:

</code></pre>

**Comment by manklu** [comment]
The compiler statically analyzes the source. That may be one of the patterns that can't be resolved.

**Comment by frederikprijck** [comment]
@mcherb It looks like this is fixed with Ivy. Afaik Ivy isn't released yet. So this would mean it's not fixed in Angular 7 . You could try enabling Ivy and see how it works out for you, but I don't think that's recommended for production yet.

**Comment by mhevery** [comment]
ivy is now released so marking as resolved.
