### ISSUE TITLE
Pathless route consumes next path

### ISSUE THREAD

**Issue by miginmrs** [angular/angular#26224]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When we create a url using a relativeTo pathless ActivatedRoute, it does consider the next non empty path of this ActivatedRoute as a part of the url.

## Expected behavior

RelativeTo is understood as a base for the relative url so its expected to not add its children as parent of the current commands.

## Minimal reproduction of the problem with instructions

In this example: https://stackblitz.com/edit/pathless-route we can see that links are correct only when the parent route is path-full or it has no activated child.
## What is the motivation / use case for changing the behavior?

The importance of the correction of this behavior is to allow using many routes on the same level including a pathless route as a default route (as for languages) with the same children.

## Environment

<pre><code>Angular version: 6.1.9</code></pre>

**Comment by manklu** [comment]
@miginmrs If I understand you correctly, it will work if you correct your setting of the parent flag.

Change
```javascript
const routes: Routes = [
  {path: "", component: RoutedComponent, data: {name: 'Pathless Parent', parent: true}, children},
  {path: "index", component: RoutedComponent, data: {name: 'Pathfull Parent', parent: true}, children},
]
```
to
```javascript
const routes: Routes = [
  {path: "", component: RoutedComponent, data: {name: 'Pathless Parent', parent: false}, children},
  {path: "index", component: RoutedComponent, data: {name: 'Pathfull Parent', parent: true}, children},
]
```

**Comment by miginmrs** [comment]
@manklu Sorry if I was not very clear. 
Just to not create two different components ParentComponent and ChildComponent (and that is the real case), I passed the parent data property to the only one common component just to make the distinction. So its not possible to change this property because it means replacing the component in route with another which is not what we need. 
That a point. The other point is that what you proposed doesn't solve the incorrect links in the children.
Btw, thanks for your comment 👍 I hope I am more clear now.

**Comment by jasonaden** [comment]
Thanks for the issue and PR. I'll try to get to the PR shortly and let you know.
