### ISSUE TITLE
main.***.js file content-length set 0 in Catch Storage when upload to server

### ISSUE THREAD

**Issue by akilmakda** [angular/angular#26230]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

main.**.js file have 0 content-length in server 
![image](https://user-images.githubusercontent.com/24309502/46411947-b5631400-c73a-11e8-91df-3577366a043c.png)

URL: https://qa.turacomobile.com/

## Expected behavior

main.**.js file must have content-length.

## Environment

<pre><code>
Angular CLI: 6.2.3
Angular PWA: 0.6.8
Angular Service-worker: 6.0.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
This is unrelated to Angular.
