### ISSUE TITLE
get the name of property that is binded to ngModel

### ISSUE THREAD

**Issue by Elias-Heydarpour** [angular/angular#26232]
is it possible to obtain the name of property that bind to ngModel for example
<input [(ngModel)]="myModel.CompanyName" />
i need get  "myModel.CompanyName" for use in my ts code,(without create any new input or directive)
is there any idea ?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
