### ISSUE TITLE
'async' utility makes tests depend on each other

### ISSUE THREAD

**Issue by AndriiShpak** [angular/angular#26234]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Having test without 'async' that includes code failing in next event tick will fail another test that uses 'async' utility

## Expected behavior
Test should not fail even if previous one schedules something

## Minimal reproduction of the problem with instructions
1) Create angular app using angular-cli
2) Paste this code in the test file
<pre><code>
  import { async } from '@angular/core/testing';

  it('should schedule macrotask and not fail', () => {
    setTimeout(() => {
      let a;
      a.foo();
    });

    expect(true).toBeTruthy();
  });

  it('should not fail', async(() => {
    expect(true).toBeTruthy();
  }));
</pre></code>
3) Run both tests together

_Result:_ second test fails because of the first one
## What is the motivation / use case for changing the behavior?
Tests should not depend on each other even with 'async' utility

## Environment
Can be reproduced in the newly created angular-cli project by adding code snippet provided above to any spec file.
_Note:_ couldn't reproduce in stackblitz

Angular-cli version: 6.2.4
Angular version: 6.1.9
Zone version: 0.8.26

**Comment by JiaLiPassion** [comment]
I will check this one, thanks!

**Comment by dylhunn** [comment]
@JiaLiPassion Do you think this might still be an issue, or is it safe to close?

**Comment by JiaLiPassion** [comment]
@dylhunn , sure, I will check this one soon.

**Comment by JeanMeche** [comment]
I did the test on v16, the issue doesn't reproduce.
