### ISSUE TITLE
Building angular service library with external js libraray

### ISSUE THREAD

**Issue by bit-warrior** [angular/angular#26242]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have a angular service library which is using a couple of  extenal javascript libraray . so i have added them in root level angular.json like  
```
  "scripts": ["src/lib/one.js","src/lib/two.js"]
```
```
"ng-test-library": {
      "root": "projects/ng-test-library",
      "sourceRoot": "projects/ng-test-library/src",
      "projectType": "library",
      "prefix": "av",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "projects/ng-test-library/tsconfig.lib.json",
            "project": "projects/ng-test-library/ng-package.json",
            "scripts": ["src/lib/one.js","src/lib/two.js"]
          }
        },
     ...................................
      }
    }

```
when i run ng build ng-test-library, its complaining about script property that i have added , error below

Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(scripts).
## Expected behavior
its should build

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.9.0-rc.1
@angular-devkit/build-angular      0.9.0-rc.1
@angular-devkit/build-ng-packagr   0.9.0-rc.1
@angular-devkit/build-optimizer    0.9.0-rc.1
@angular-devkit/build-webpack      0.9.0-rc.1
@angular-devkit/core               7.0.0-rc.1
@angular-devkit/schematics         7.0.0-rc.1
@angular/cli                       7.0.0-rc.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.0-rc.1
@schematics/angular                7.0.0-rc.1
@schematics/update                 0.9.0-rc.1
ng-packagr                         4.2.0
rxjs                               6.2.2
typescript                         3.1.1
webpack                            4.19.1

**Comment by gkalpak** [comment]
Please open an issue on the [@angular/cli][1] repo.

[1]: https://github.com/angular/angular-cli
