### ISSUE TITLE
INSTALLING ANGULAR

### ISSUE THREAD

**Issue by dreamerboy2998** [angular/angular#26241]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I'm tried to install angular by npm, that show me an error 
and I don't know, why this happends
This is the error
npm ERR! Unexpected end of JSON input while parsing near '...^1.5.6","jshint":"^2.'
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\toto_\AppData\Roaming\npm-cache\_logs\2018-10-03T22_42_51_254Z-debug.log

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
It sounds like some file is corrupted (possibly due to a bad network connection).
I would suggest deleting the project's `node_modules/` directory and trying again.

In any case, this is not related to Angular itself.
