### ISSUE TITLE
Loading component styles with source map

### ISSUE THREAD

**Issue by devpreview** [angular/angular#26253]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Now Angular does not load source map of component styles. For example:

```
@Component({
    selector: 'app-test',
    template: '<div>test...</div>',
    styleUrls: ['./test.component.scss']
})
export class TestComponent implements OnInit {
    public ngOnInit(): void {
        console.log(require('./test.component.scss'));
    }
}
```

This example return the following result:

```
<head>
<style>div[_ngcontent-c0] {
  color: red; }</style>
</head>
```

And log to console:

```
div {
  color: red; }

/*# sourceURL=/home/sabo/Workspace/R7Tech/Frontend/Frontend/src/app/test.component.scss */
/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi9ob21lL3NhYm8vV29ya3NwYWNlL1I3VGVjaC9Gcm9udGVuZC9Gcm9udGVuZC9zcmMvYXBwL3Rlc3QuY29tcG9uZW50LnNjc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7RUFDRSxXQUFVLEVBQ1giLCJmaWxlIjoidGVzdC5jb21wb25lbnQuc2NzcyIsInNvdXJjZXNDb250ZW50IjpbImRpdiB7XG4gIGNvbG9yOiByZWQ7XG59XG4iXSwic291cmNlUm9vdCI6IiJ9 */
```

## Expected behavior

Add a link to the map in styles:

```
<head>
<style>div[_ngcontent-c0] {
  color: red; }
/*# sourceURL=/home/sabo/Workspace/R7Tech/Frontend/Frontend/src/app/test.component.scss */
</style>
</head>
```

## Environment

<pre><code>
Angular version: 6.1.9
Webpack version: 4.19.1
@ngtools/webpack version: 6.2.4

For Tooling issues:
- Node version: v10.11.0  
- Platform: Linux  

</code></pre>

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/26123

**Comment by devpreview** [comment]
@trotyl sorry, close issue.
