### ISSUE TITLE
Angular 5 calling some route without call on typescript source

### ISSUE THREAD

**Issue by raimundocolombo** [angular/angular#26252]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have an Angular 5 application and my html have a button that calls on (click) the save($event) method on my typescript and on the save($event) method I have to execute some save action and stay on the same page, but even without a this.router.navigate(['tarefas']); call, the application call the this.router.navigate(['tarefas']); in some way. This is a strange behavior.

This behavior is intermittent.

## Expected behavior

The correct behavior would be stay on the same page after the save($event) method ends.

## Minimal reproduction of the problem with instructions

HERE IS MY HTML CODE:

<form #distribuirSolicitacaoForm="ngForm" class="formCustom" onload="carregaDependenciaBeneficiaria()">
      

        <div>
          <h4 class="titleForm">Formulário de Distribuição de Solicitação</h4>
          <input type="hidden" name="taskId" [(ngModel)]="this.soaCall.taskId" />
          <input type="hidden" name="soaUrl"  [(ngModel)]="this.soaCall.soaUrl" />
          <input type="hidden" name="ctxToken" [(ngModel)]="this.soaCall.ctxToken" />

          <div class="row">
            <div class="col-md-12">
              <h4 class="titleForm">Dados da Inclusão</h4>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <label class="radio-inline">
                <span> Número da Solicitação: #{{solicitacao.idSolicitacao}}</span>
              </label>
            </div>
            <div class="col-md-12">
              <label class="radio-inline">
                <span> Modalidade da Solicitaçao: {{solicitacao.modalidade?.dsModalidade}}</span>
              </label>
            </div>

            <div class="col-md-12">
              <label class="radio-inline">
                <span> Tipo de documento de Solicitaçao: {{tipoDocumento}}</span>
              </label>
            </div>
            <div class="col-md-12">
              <label class="radio-inline">
                <span> Número do documento de Solicitaçao: {{solicitacao.numDocumento}}</span>
              </label>
            </div>
            <div class="col-md-12">
              <label class="radio-inline">
                <span> Data do documento de Solicitaçao: {{solicitacao.dtDocSolicitacao | date:'dd/MM/yyyy'}}</span>
              </label>
            </div>
            <div class="col-md-12">
              <label class="radio-inline">
                <span> Objeto: {{solicitacao.objetoSolicitacao}}</span>
              </label>
            </div>
          </div>

          <div class="row col-md-12">
            <div class="panel">
              <label class="radio-inline">
                <span> Dependências</span>
              </label>
              <div class="panel-body">
                <ul >
                  <li *ngFor="let dep of solicitacao.dependencias">
                    <span>{{dep.dsDependencia}}</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          <div class="row col-md-12">
            <div class="panel">
              <label class="radio-inline">
                <span> Requisitantes no Processo</span>
              </label>
              <div class="panel-body">
                <ul >
                  <li *ngFor="let req of solicitacao.requisitantes">
                    <span>{{req.siglaRequisitante}} - {{req.dsRequisitante}} </span>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <h4 class="titleForm">Dados da Distribuição</h4>
            </div>
          </div>
          <div class="row">
            <form-control [colSize]="6">
              <custom-select
                label="Tipo de Licitação"
                [(ngModel)]="solicitacao.tipoLicitacao"
                name="tipoLicitacao"
                [lista]="tipoLicitacoesDb"
                descricao="dsTipoLicitacao"
                [required]="true">
              </custom-select>
            </form-control>

            <form-control [colSize]="6">
              <custom-select
                label="Classificação"
                [(ngModel)]="solicitacao.classificacao"
                name="classificacao"

                [lista]="classificacoesDb"
                descricao="dsClassificacao"
                [required]="true">
              </custom-select>
            </form-control>

          </div>

          <div class="row">
            
            <form-control [colSize]="12">
              <custom-select
                label="Unidade de Apoio"
                name="unidadeApoio"
                [(ngModel)]="solicitacao.unidadeApoio"
                [lista]="unidadesApoioDb"
                [required]="true"
                descricao="siglaUnidade">
              </custom-select>
            </form-control>
          </div>

          <div class="row">
            
            <form-control [colSize]="12">
              <custom-select
                label="Dependência Beneficiária para a Numeração do Processo"
                [(ngModel)]="solicitacao.dependenciaBeneficiaria"
                name="dependenciaBeneficiaria"
                [lista]="dependenciasDb"
                descricao="dsDependencia"
                [required]="true">
              </custom-select>
            </form-control>
          </div>

          <div class="row">
            <form-control [colSize]="4" [pularLinhaError]="true">
              <label class="radio-inline">
                <input type="checkbox" name="icDivulgacaoIrp" [(ngModel)]="divulgacaoIrp"> IRP
              </label>
            </form-control>
          </div>
          <h4 class="titleForm">Interessados no Processo</h4>
          <form #formPesquisar="ngForm">
            <div class="row">
              <form-control [colSize]="10">
                <custom-input
                  [required]="true"
                  name="inputPesquisa"
                  [(ngModel)]="nomeFuncionario"
                  label="Nome Empregado">
                </custom-input>
              </form-control>
              <div class="col-md-2 no-label">
                <button (click)="pesquisar()" class="btn btn-green no-label" name="button">Pesquisar</button>
              </div>
            </div>
          </form>
          <div class="table-responsive">
            <table class="table table-striped noMarginTop">
              <tr>
                <th COLSPAN="4"><b>Resultado da Consulta</b></th>
              </tr>
              <tr>
                <th align="left">Matrícula</th>
                <th align="left">Nome</th>
                <th align="left" colspan="2">E-mail</th>
              </tr>
              <tr *ngFor="let integrante of funcionariosPesquisados">
                <td>{{integrante.matricula}}</td>
                <td>{{integrante.nome}}</td>
                <td>{{integrante.email}}</td>
                <td class="text-center">
                  <button type="button" class="btn btn-primary"
                          (click)="adicionarInteressado(integrante)">
                    Adicionar
                  </button>
                </td>
              </tr>
            </table>
          </div>

          <div class="table-responsive">
            <table class="table table-striped noMarginTop">
              <tr>
                <th COLSPAN="3"><b>Interessados no Processo</b></th>
              </tr>
              <tr>
                <th>Nome</th>
                <th colspan="2">E-mail</th>
              </tr>
              <tr *ngFor="let adicionado of interessadosList; let i = index" [attr.data-index]="i">
                <td>{{adicionado.nomeInteressado}}</td>
                <td>{{adicionado.emailInteressado}}</td>
                <td class="text-center">
                  <button type="button"
                          (click)="deleteInteressado(adicionado)">
                    <i class="fas fa-times"></i>
                  </button>
                </td>
              </tr>
            </table>
            <div class="col-md-12">
              <div class="alert alert-danger" *ngIf="interessadosList.length == 0">
                <strong>Atenção!</strong> Adicione um ou mais interessados para a solicitação.
              </div>
            </div>
          </div>

          
          
          

          
          <div class="row">
            <div class="col-md-12">
              <label><span class="required text-center">*</span> Anexos </label>
              <div class="tab-container">
                <app-file-picker #filePicker></app-file-picker>
                
              </div>

            </div>
          </div>

          <div class="row">
            <div class="panel" *ngIf="anexosList.length > 0">
              <div class="panel-body">
                <ul >
                  <li *ngFor="let anexo of anexosList">
                    <span>{{anexo.arquivo}}</span>
                    <a (click)="deleteAnexo(anexo)"><i class="fas fa-times"></i></a>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          

          <div class="row">
            <div class="col-md-12 searchBtnBar text-center">
              <button type="button" (click)="salvar($event)" name="btnSalvar" id="salvar" class="btn btn-green">Salvar</button>
              <button type="button" name="btnReset" (click)="resetFields($event)" class="btn btn-gray-ghost">Limpar</button>
            </div>
          </div>
          
        </div>

      </form>

The save($event) method is called on the button: 
<button type="button" (click)="salvar($event)" name="btnSalvar" id="salvar" class="btn btn-green">Salvar</button>

HERE IS THE TYPESCRIPT CODE:

salvar(e) {
    e.preventDefault();

    this.form.onSubmit(e);

    if(this.form.valid) {
      if (this.solicitacao) {

        if (this.validarFormulario()) {
          this.licitacoesService.updateSolicitacao(this.solicitacao).subscribe(data => {
            this.modalService.showSuccess('Solicitação salva com sucesso!').subscribe(() => {
              console.log('Emitiu a mensagem...');
            });

            console.log('saiu do subscribe...');

          }, error => {
            this.showErrorMessage(error);
          });
          console.log('saiu ....');
        }
      }
    } else {
      return;
    }

  }

I put some console.log on the code and after that the issue stopped to happen. But this happened many times and after some time the issue happen again.

The call this.licitacoesService.updateSolicitacao(this.solicitacao).subscribe() on the typescript code calls the code bellow:

// Serviço atualização de Solicitação
  updateSolicitacao(solicitacao: Solicitacao): Observable<Solicitacao> {
    let idSolicitacao = solicitacao.idSolicitacao;
    solicitacao.processo = null;
    console.log('VAI CHAMAR O ENDPOINT >>>>' + this.baseRestUrl + this.urlSolicitacoes + idSolicitacao);
    return this.http.put<Solicitacao>(this.baseRestUrl + this.urlSolicitacoes + solicitacao.idSolicitacao, solicitacao, httpOptions)
      .pipe(
      catchError(this.tratarErro)
    );
  }

This is a call for the spring boot rest app.

I appreciate some help, even in case of suspicion.

## Environment

<pre><code>
Angular version: 1.6.6
Spring boot version: 1.5.10
Weblogic Server version: 12.2.1.3.0

Browser:
- [ X ] Chrome (desktop) version 65.0.3325.181 (Versão oficial) 64 bits
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ X ] Firefox version 62.0 (64-bit)
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v9.9.0
- Platform:  Ubuntu 16.04 LTS

Others:

</code></pre>

**Comment by dblVs** [comment]
@raimundocolombo you should ask for help in Gitter/StackOverflow. You should create a small demo that creates the bug you face. 

Currently it seems to me the issue is with your implementation. Also be mindful of angular contributors since they spend their time looking through something unreadable and trying to understand.

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
