### ISSUE TITLE
Unhandled Navigation Error

### ISSUE THREAD

**Issue by SlimAidar** [angular/angular#26274]
After building and opening my index.html I got this error and can't navigate through pages: Unhandled Navigation Error

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
