### ISSUE TITLE
integrate angular 6 in MVC .net Framework 4.5 +

### ISSUE THREAD

**Issue by aliajmat** [angular/angular#26271]
i am unable to integrate angular 6 project in visual studio 2015. I have buy angular 6 admin template from theme forest and want to integrate in .Net MVC application.
after integrating the src/ package.json, tsconfig and tslint and updating the base path, the application is running but no any component is loaded.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
