### ISSUE TITLE
this.router.isActive(url, false) does not work properly in some case

### ISSUE THREAD

**Issue by efriandika** [angular/angular#26288]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
`this.router.isActive(url, exact)` does not working properly on first click via `<a [routerLink]="'/xxx'" ...`. It always returns false on first click (when the link has been clicked for 1st time)

It will work after first click.

It will be happen if my routing is like this:
```
export const routes: Routes = [
    { path: '', redirectTo: '/dashboard', pathMatch: 'full' },
    {
        path: '',
        component: LayoutComponent,
        children: [
            { path: 'dashboard', loadChildren: './dashboard/dashboard.module#DashboardModule' },
            { path: 'parameter', loadChildren: './parameter/parameter.module#ParameterModule' }
        ]
    },
    { path: '**', component: NotFoundComponent }
];

@NgModule({
    imports: [RouterModule.forRoot(routes)],
    exports: [RouterModule]
})
export class AppRoutingModule {
}
```
- hit the url /dashboard in browser
- then click a link /parameter
- check the value of `this.router.isActive('/dashboard', exact)` it will not correct. It will be correct if you re-click a link /dashboard again and then click again /parameter.

## Expected behavior
It works properly for the routing that is like above routing code:

## Environment

<pre><code>
Angular version: 6.1.9

Browser:
All  Browser

</code></pre>

**Comment by jasonaden** [comment]
Reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

Please create this running reproduction so we can accept this issue.

**Comment by jasonaden** [comment]
(closing as per above comment)
