### ISSUE TITLE
Radio button has inconsistent behavior when deciding its checked state when using objects as value

### ISSUE THREAD

**Issue by CurtisDS** [angular/angular#26283]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

### Using FormControl

**The set up:**
I have defined an object: 
```
Foo: {
    bar: number
}
```

Using a `FormControl` attached to a set of radio buttons I set the value to a new instance of `Foo`: `{bar:1}`. Each button has a value of the same `Foo` type as the `FormControl`, ie: `{bar:1}`, `{bar:2}`, `{bar:3}`. Both the values for the radio button and the default value for the `FormControl` are returned by an API meaning I am not setting the `FormControl` to the exact same instance of `Foo` that is stored in the radio buttons; the value is set to a new instance of `Foo` with the same `bar` value as one of the radio buttons. This is normally an issue because the radio buttons use a simple reference based comparison to tell if they should be checked or not, meaning if I pass a new instance of an object even if they both share the same `bar` value they will not be considered equal. Because of this I wrote a compare method for `Foo`:
```
comp(ob1: Foo, ob2: Foo) {
    return ob1.bar === ob2.bar
}
```
I set the radio button's `checked` property to the result of `comp(radio.value, formControl.value)`. This allows the correct radio button to be selected when the controls are initialized. I then add a reset button to my form that will use the `FormControl.reset(value)` method to reset the control to the default value which was returned by the API.

**The issue:**
When I press the reset button it will reset the FormControl's value and the correct radio will get selected, meaning the compare function is doing what I expect it to do and is working. However if the FormControl's value is already set to the default value and the reset button is pressed the radio button will become unchecked. Even though the result of the compare function still accurately returns true.

This also happens when using `FormControl.setValue(value)` and `FormControl.patchValue(value)` when using new instances of `Foo` as the value. (IE: It works the first time you set the value, but not the second time)

### Using NgModel
**The set up:**
Same as before but instead of `FormControl` we use the `NgModel` approach.

**The issue:**
When using `NgModel` the `checked` property is completely ignored.

## Expected behavior

For the control to listen to the `checked` property and be checked when true.

## Minimal reproduction of the problem with instructions

I already explained the set up. Here are the demos:

formControl examples:
[[minimal](https://stackblitz.com/edit/angular-radio-not-checked-bug-minimal)] [[more detailed](https://stackblitz.com/edit/angular-radio-not-checked-bug)]

ngModel examples:
[[minimal](https://stackblitz.com/edit/angular-radio-not-checked-bug-ngmodel-minimal)] [[more detailed](https://stackblitz.com/edit/angular-radio-not-checked-bug-ngmodel)]

## What is the motivation / use case for changing the behavior?

I use an API to get the values for the radio buttons. Through out my code I have to do things like reset forms or change the value of a control programmatically and I don't have easy access to the original objects used to set the values for the radio inputs so allowing me to set the radio buttons using the checked property would be nice. Alternatively allowing me to stipulate a compare function would also probably solve the issue.

That said, this bug report is more to do with the inconsistent behavior. When using formControl why does the reset work the first time but not the second time, and why does it not work at all with ngModel. I think this should be changed so that the behavior is consistent.

## Environment

<pre><code>
Angular version: 6.1.9

Browser:
- [x] Chrome (desktop) version 69.0.3497.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 62.0.3
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dawidgarus** [comment]
I don't think checked property should be used with ngModel/formControl - tt's their responsibility to mark input as checked. Radio should have `compareWith` property similar how it's done with select: https://angular.io/api/forms/SelectControlValueAccessor#properties
