### ISSUE TITLE
Regression routerNavigateByUrl + canLoad in 7.0-rc.0 <> 6.1

### ISSUE THREAD

**Issue by timdeschryver** [angular/angular#26284]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When calling `router.navigateUrl('/route').then(...)` in combination with a `canLoad` guard that returns false, the Promise isn't getting resolved (`then` function isn't getting invoked).

## Expected behavior

If this is the desired result, this is OK for me 😅
I just wanted to be sure of this, because this was working in v6.1

## Minimal reproduction of the problem with instructions

There is a guard on the `lazy` route which returns `false`. When we click on the button it tries to navigate to the lazy loaded module guarded by a `canLoad` guard.

```ts
this.router.navigateByUrl('/lazy').then((result) =>{
      console.log('ok:', result);
    }).catch(err => {
      console.log('catch:', err);
});
```

Notice that in v6.1 it logs `ok: false` whereas in v7.0 it does not.
(After clicking it 3 times, the guard does return true).

**Version 6.1: https://stackblitz.com/edit/load-guard-6?file=src%2Fapp%2Fapp.module.ts**

![angular6](https://user-images.githubusercontent.com/28659384/46575237-06c90880-c9b2-11e8-9d19-260c7b808784.gif)

**Version 7.0-rc.0: https://stackblitz.com/edit/load-guard-7?file=src%2Fapp%2Fapp.module.ts**

![angular7](https://user-images.githubusercontent.com/28659384/46575236-0597db80-c9b2-11e8-8c1e-8fa2529d3831.gif)

## What is the motivation / use case for changing the behavior?

I encountered this while upgrading the NgRx repo to the rc version and encountered this issue in our tests - https://github.com/ngrx/platform/pull/1354#discussion_r223185634

## Environment

<pre><code>
Angular version: 7.0-rc.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

## Others:

I'm not sure but I think this behavior comes from throwing an error at https://github.com/angular/angular/blob/master/packages/router/src/apply_redirects.ts#L90 but not catching it and dispatching a `NavigationCancel` event at https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L410.

**Comment by jasonaden** [comment]
Thanks for the issue and for looking into it. We'll pull this in to get fixed ASAP.

**Comment by timdeschryver** [comment]
Thanks @jasonaden !

**Comment by JounQin** [comment]
Seems like #26757 which still does not work for now.
