### ISSUE TITLE
Lazy Loading using #hash usage for component breaks A6 PWA in chrome devtools hangs/thrashes

### ISSUE THREAD

**Issue by nhhockeyplayer** [angular/angular#26285]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
inside my shared.module.ts

```
const routerConfig: Routes = [
  {
    path: 'contentprojector',
    loadChildren: './services/contentprojector/contentprojector.module#ContentprojectorModule'
  },
  {
    path: 'contentprojection',
    loadChildren: './components/contentprojection/contentprojection.module#ContentprojectionModule'
  }
]

```
usage of #ContentprojectorModule and #ContentprojectionModule

are what trigger the PWA to fail loading in chrome devtools

## Expected behavior
PWA should at least load and fall into place as it does if I remove hashtag usage for lazy loadinng

## Minimal reproduction of the problem with instructions
repo reproducing the issue is here
https://github.com/nhhockeyplayer/dpcore

## What is the motivation / use case for changing the behavior?
Just trying to operate shared modules when routes are hit

## Environment
Windows 7 x64

C:\apache-tomcat-9.0.0.M17\webapps\ROOT\akumina\dpcore>node -v
v8.12.0

C:\apache-tomcat-9.0.0.M17\webapps\ROOT\akumina\dpcore>npm -v
6.4.0

C:\apache-tomcat-9.0.0.M17\webapps\ROOT\akumina\dpcore>ng -v

Angular CLI: 6.2.4
Node: 8.12.0
OS: win32 x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.4
@angular-devkit/build-angular     0.8.4
@angular-devkit/build-optimizer   0.8.4
@angular-devkit/build-webpack     0.8.4
@angular-devkit/core              0.8.4
@angular-devkit/schematics        0.8.4
@angular/cdk                      6.4.7
@angular/cli                      6.2.4
@angular/flex-layout              6.0.0-beta.18
@angular/material                 6.4.7
@angular/pwa                      0.8.4
@ngtools/webpack                  6.2.4
@schematics/angular               0.8.4
@schematics/update                0.8.4
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.20.2

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by nhhockeyplayer** [comment]
much code has been commented out and also in state of hack/flux trying to shake this out
please excuse

I isolated it down to usage of the hash

**Comment by gkalpak** [comment]
I couldn't reproduce the issue with the reproduction you provided. The `#` should not affect the SW anyway (since it is stripped from the request URL). There must be something else that's causing the problem.

If you still think this is an issue in Angular, please provide detailed instructions on how to reproduce the problem.
