### ISSUE TITLE
Angular purges <script type="text/plain" as if it were a security vulnerability

### ISSUE THREAD

**Issue by AlexanderJohr** [angular/angular#26293]
## I'm submitting a...
<pre><code>
[x] Bug report  
[x] Feature request
</code></pre>

## Background

Imagine you have the following webcomponent:

``` html
<expression>
	<script type='text/plain'>
		If(var1 < var2,
			Sum([Field 1])
		,
			Sum([Field 2])
		)
	</script>
</expression>
```
The component reads the text inside the script tag and sends it to a server which evaluates the result.

The webcomponent should be embedded in an Angular App. It is no Angular component and should just rendered as is.

It has to contain a script tag because `'text/plain'` allows it not to be parsed as HTML and like this, it is possible for expressions to contain characters like `<` as in `var1 < var2` without being recognized as the beginning of a html tag.

## Current behavior
Angular deletes all script tags inside templates, also those with text/plain. I read, that this is because you shouldn't mix JavaScript with Angular Templates, but this is just plain text.

## Expected behavior
`<script type="text/plain"` should not be deleted. It is the only way to integrate text without having to escape all html characters.

## Minimal reproduction of the problem with instructions
Insert the following code into a template and see if it will be deleted.

``` html
<script type='text/plain'>
    If(var1 < var2,
        Sum([Field 1])
    ,
        Sum([Field 2])
    )
</script>
```

## What is the motivation / use case for changing the behavior?
If `<script type="text/plain"` would not be deleted it is possible to insert everything which is not html without having to escape it. HTML 5 supports it and as far as I know there is no alternative. Also it isn't a security vulnerability.

## Environment

<pre><code>
Angular version: 6.1.0
Browser:
- [x] Chrome (desktop) version 69
</code></pre>

**Comment by AlexanderJohr** [comment]
I also filed it in the Angular Dart repo: https://github.com/dart-lang/angular/issues/1630

**Comment by AllTerrainDeveloper** [comment]
Why don't you use...
```
<expression>
     {{var1 < var2 ? Sum([Field 1]); : Sum([Field 2]);}}
</expression>
```

**Comment by AlexanderJohr** [comment]
Because it isn't an Angular expression. It is Text, but text without having to escape the HTML characters.

Take this example with SQL for example:

``` html
<sql-table>
	<script type='text/plain'>
SELECT DepartmentID, Name  
FROM HumanResources.Department  
WHERE DepartmentID <= 3  
ORDER BY DepartmentID;  
	</script>
</sql-table>
```

The expression will be sent to the SQL Server and the table will be displayed by the component.

The text (code in this case) contains a `<`, so it must be escaped or it will be parsed as an HTML character.

In order not to escape it it is also possible to wrap it inside `<script type='text/plain'>`

**Comment by robwormald** [comment]
This is going to require changes to the security layer in Angular, so just to set expectations, it's not likely to happen quickly. I've forwarded it to our internal security team to get their feedback.

**Comment by pkozlowski-opensource** [comment]
This is the same / duplicate of #9695.

**Comment by pkozlowski-opensource** [comment]
As @robwormald pointed out adding support for `<script>` tags has non-trivial security implications. But since we don't support them we should, as a very minimum, have a meaningful error / warning message as today `<script>` tags are removed silently.

**Comment by Vandivier** [comment]
Please take a look at the following, and consider upvoting, as a generic solution for this and other similar problems:
https://github.com/angular/angular/issues/36650

**Comment by AlexanderJohr** [comment]
Not a concern anymore!

This issue and many more fucked me up so hard, that I switched to Flutter.

Just kidding! 😄 Thanks for letting me know, you helpful robot!

But honestly! Flutter is awesome!
