### ISSUE TITLE
using self=this cause errors in live reloading

### ISSUE THREAD

**Issue by JacopoSciampi** [angular/angular#26294]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior
I have a project, and inside one component, i declared a variable 

`let self: any;`

then assigned in this way:

`self = this;`

and used in few cases for ding stuff.

## Expected behavior
I don't get it why is complining but not live reloading the browser.

## Minimal reproduction of the problem with instructions
I believe just putting this simple code will cause the error.
## Environment

<pre><code>
Angular version: 5.2.5

Browser:
- [x ] Chrome (desktop) version XX
 
For Tooling issues:
- Node version: 8.11.4
- Platform: Windows

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
