### ISSUE TITLE
Clearing input box in Edge does not emit valueChanges using reactive forms

### ISSUE THREAD

**Issue by acohenOT** [angular/angular#26307]
## I'm submitting a...
<pre><code>
[x ] Bug report  
</code></pre>

## Current behavior
In Microsoft Edge, using reactive forms, valueChanges observable does not emit when the browser's native "clear" button is clicked after entering text into a input box.

## Expected behavior
When entering text into a text box and you click the "clear" button that is displayed by Edge, valueChanges should emit and any element using that value would update.

## Minimal reproduction of the problem with instructions
Reactive Forms live demo with no changes required

Run using Microsoft Edge:
[https://stackblitz.com/edit/angular-kddsom](https://stackblitz.com/edit/angular-kddsom)

Steps:

1. Click Name Editor
2. Type in a name, notice Value properly updates as you type
3. Click the "X" button in the text box to clear the field (<-- you will only see this using Edge)
4. The input box clears but Value does not

A similar "X" clear button is also displayed in IE11, but clicking that will properly emit valueChanges and the value updates. This issue is specific to Edge.

## What is the motivation / use case for changing the behavior?
Clearing an input field using the browser's native clear button should be considered changing the value.

## Environment

<pre><code>

Angular version: 6.1.10

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 44
 

Others:
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763
Windows 10 x64 October 2018 Update
</code></pre>

**Comment by acohenOT** [comment]
See screenshots
![edge1](https://user-images.githubusercontent.com/34688558/46632231-eadf7700-cb17-11e8-8660-723283b5508e.png)
![edge2](https://user-images.githubusercontent.com/34688558/46632232-eb780d80-cb17-11e8-9c3d-06c35e99799b.png)

**Comment by acohenOT** [comment]
@robwormald I see now that it's broken in Edge and not a bug in Angular. I think no action needed here. Thanks.

**Comment by kara** [comment]
Thanks @robwormald for the background info and @acohenOT for the clear issue report. It sounds like the ball is in Edge's court here, so I'm closing this issue.

**Comment by chrismbarr** [comment]
To potentially help out future googlers, here's a workaround I've found that works:

```html
<input type="search"
       [(ngModel)]="searchTerm"
       (ngModelChange)="performSearch()"
       (mouseup)="detectSearchClear($event)">
```

```ts
searchTerm: string = '';

performSearch(): void {
    this.searchService.doSearch(this.searchTerm);
}

/** This allows the "clear search" X button to properly update the value for Edge & IE browsers */
detectSearchClear($event: Event): void {
    if ($event.target) {
        const inputEl = $event.target as HTMLInputElement;
        const beforeVal = inputEl.value;
        setTimeout(() => {
            const afterVal = inputEl.value;
            if (beforeVal !== '' && afterVal === '') {
                this.searchTerm = '';
                this.performSearch();
            }
        }, 1);
    }
}
```

Please note that when using Chrome, Firefox, or any other browser that supports the "clear search" event natively, this will cause the `performSearch()` method to be called twice within a short period of time, so it's a good idea to debounce calls to whatever does the actual searching.
