### ISSUE TITLE
Service worker docs out of date - only says the latest Chrome/FF are supported

### ISSUE THREAD

**Issue by andrewseguin** [angular/angular#26308]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

1. Check out https://angular.io/guide/service-worker-intro#prerequisites
2. (Under Prerequisitites) Docs say "Currently, the latest versions of Chrome and Firefox are supported."

## Expected behavior

Based on caseiuse.com, looks like this is out of date and can be updated to say that it supports nearly all browsers

**Comment by nik72619c** [comment]
Will try to resolve this issue. Trying to  work on it

**Comment by nik72619c** [comment]
@jenniferfell @andrewseguin kindly view the changes.
