### ISSUE TITLE
Angular doesn't allow prototype extensions on 'Object'

### ISSUE THREAD

**Issue by andifined-de** [angular/angular#26318]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When extending the Object prototype with own functions, angular crashes with the following TypeError:
<pre><code>ERROR TypeError: instance[output.propName].subscribe is not a function
    at createDirectiveInstance (core.js:9190)
    at createViewNodes (core.js:10406)
    at callViewAction (core.js:10722)
    at execComponentViewsAction (core.js:10641)
    at createViewNodes (core.js:10434)
    at callViewAction (core.js:10722)
    at execComponentViewsAction (core.js:10641)
    at createViewNodes (core.js:10434)
    at createRootView (core.js:10320)
    at callWithDebugContext (core.js:11351)
</code></pre>
Extending other prototypes like Array, Function or String works as expected.
This doesn't seem to be a TypeScript error, since everything compiles nicely and only crashes when running the app. I don't know where the crash exactly happens, since the first components get rendered.

## Expected behavior

It should be possible to extend the Object prototype

## Minimal reproduction of the problem with instructions

Create  a `typings.d.ts` in your src/app folder and extend the Object interface with your method:
<pre><code>interface Object {
  test(): void;
}</code></pre>

Add the new function to your `app.module.ts` or implement it in another file and import it here:
<pre><code>(function () {
  if (!Object.prototype.test) {
    Object.prototype.test = function () {
      console.log(':(');
    };
  }
})();</code></pre>

## What is the motivation / use case for changing the behavior?

It would be nice to add own functions to all prototypes (and if not possible, at lease documented).

## Environment

<pre><code>Angular version: 6.1.3
CLI version: 6.0.8
</code></pre>

**Comment by andifined-de** [comment]
@trotyl Care to explain why the thumbs down? If I am mistaken, I'd love to know where I did something wrong.

**Comment by trotyl** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

It has nothing to do with Angular, it's just affect any property checking, change the property name and it would break something else.

**Comment by andifined-de** [comment]
Thanks for the answer @trotyl . Still, I think that this is definitely a bug and not a fault on my side, although I might be wrong. I will do some quick research and update or delete this issue.

**Comment by robwormald** [comment]
Unless you're polyfilling some existing API, this is generally a [Bad Idea](http://perfectionkills.com/whats-wrong-with-extending-the-dom/). That said, Angular should not care one way or the other (Angular CLI itself includes a variety polyfills that do this, so it's nothing that we prevent).

But seriously, don't do this. It's likely to cause all manner of crazy things to happen, and we won't make any special affordances for it.
