### ISSUE TITLE
Content Security Policy directive: “connect-src 'self' https://apis.google.com”

### ISSUE THREAD

**Issue by cstrd** [angular/angular#26317]
I have Implemented the Content Security Policy in the Nginx server for my website. please check the below-Configured code:-

```
add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'https://code.jquery.com, https://cdn.flipboard.com; 
img-src 'self' data:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; 
font-src 'self' data:; frame-src 'self'; connect-src 'self' 
https://apis.google.com; object-src 'none' ";
```
After Implementing, i'm not able to get the data from server & it is not displaying in page. Please check below Screenshot of the console of the page.
![22](https://user-images.githubusercontent.com/11487982/46651698-77dd0b80-cbbe-11e8-91a3-c9e036a406ad.png)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
