### ISSUE TITLE
export of API docs includes too much: gulp docs/angular.io produces unexpected filenames

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#2632]
Please have a look at this angular.io pull request: https://github.com/angular/angular.io/pull/151

We now have files named things like `"public/docs/js/latest/api/forms/TemplateDrivenFormDirective extends  ControlContainerDirective implements \n    FormDirective-class.jade"`
and
`public/docs/js/latest/api/pipes/IterableChanges extends  Pipe-class.jade`

@petebacondarwin can you have a look and see if this is something easily fixed? I'm not sure why this started happening post ts-ification. @vsavkin was also going to look into how we export libraries to try and simplify the published API surface for forms... not sure this is related to that however.

marking as urgent -- would really like to fix this before the big conference.

**Comment by petebacondarwin** [comment]
Hi Naomi
These problems were fixed by the changes I mentioned a few days ago.
I regenerated from master, which may or may not be correct for alpha-27 and these issue don't appear.
See #152

**Comment by naomiblack** [comment]
Indeed. Fixed.
