### ISSUE TITLE
Tutorial search fails for non-keyed input

### ISSUE THREAD

**Issue by breyed** [angular/angular#26335]
## I'm submitting a...
<pre><code>
[X] Bug report  
[X] Documentation issue or request
</code></pre>

## Current behavior
In the tutorial's [hero-search.component](https://angular.io/tutorial/toh-pt6#create-herosearchcomponent), search input is detected via `keyup`. As such, non-keyboard input does not trigger a search.

## Expected behavior
Any form of input (keyboard based or otherwise) into the search box causes a search operation.

## Minimal reproduction of the problem with instructions
In a non-web-browser app, copy some text into the clipboard. In the browser, right click the mouse on the search box and click paste. Notice that no search is performed.

Alternatively, use an assistive technology device that provides input without simulating a keyboard.

## What is the motivation / use case for changing the behavior?
Searching in the hero app is not important per se; however, the tutorial is seen as a demonstration of best practices. Techniques in the tutorial are readily copied into production apps. At minimum, there should be a "don't do this in production" warning. Better would be to search based on textbox content change rather than key up.

## Environment

Browser:
- [X] Chrome (desktop) version 69.0.3497.100

**Comment by lazarljubenovic** [comment]
Indeed, the `input` event is the correct choice here based on the intended functionality.

**Comment by nik72619c** [comment]
can I work on this issue?  I have got the answer regarding it. Kindly reply please

**Comment by nik72619c** [comment]
How can I find the html file for hero-search.component.html to make the necessary changes?

**Comment by nik72619c** [comment]
ref #26439

**Comment by brandonroberts** [comment]
Fixed via https://github.com/angular/angular/pull/26440
