### ISSUE TITLE
API doc comments not parsed by dgeni

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#2633]
Look at the members of https://angular.io/docs/js/latest/api/test/TestBed-class.html. The following API comment block is showing up unparsed in the API doc output:

```
/**
   * Overrides only the html of a {@link Component}.
   * All the other propoerties of the component's {@link View} are preserved.
   *
   * @param {Type} component
   * @param {string} html
   */
```
 in API docs:
![screen shot 2015-06-18 at 10 47 42 pm](https://cloud.githubusercontent.com/assets/2286589/8247866/2cce4b88-160c-11e5-91ad-034342dbb45d.png)

**Comment by petebacondarwin** [comment]
Strictly it is all the `@param` tags that are not being processed. The rest of the block is being processed, as can be seen by the `{@link}` tag being converted to a real link.
I think that we are just ignoring `@param` in processing a the moment. I will take a look.
