### ISSUE TITLE
http: should complete after response

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#2635]
making a `http.get().subscribe` doesn't fire `complete` after success (it should `next` only once)

```es6
observer.onNext(value);
observer.onCompleted();
```

**Comment by mhevery** [comment]
@gdi2290 could you provide more info.

**Comment by gdi2290** [comment]
when you make an http call you only have one response since it's not a stream unless specified. Since I'm making a get request `http.get('/api/todos').map(res => res.json());` the response is complete once I get my first result.
```es6
var todoSubscription = this.http.get('/api/todos').
      filter(res => res.status >= 200 && res.status < 300).
      map(res => res.json());
todoSubscription.subscribe(
  value =>  console.log('next', value),
  err => {
    debugger;
    console.log('err', err)
  },
  complete => {
    debugger;
    console.log('complete', complete)
  }
);
```
the observable should fire the onComplete unless I map to `arrayBuffer` which returns `ArrayBuffer`s then it would fire onComplete until it's done.

**Comment by jeffbcross** [comment]
Yes, it should complete.
