### ISSUE TITLE
TypeError: provider.ngOnDestroy is not a function

### ISSUE THREAD

**Issue by jcjobin** [angular/angular#26368]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

A prod build has all of the router links breaking. Console reads "TypeError: provider.ngOnDestroy is not a function". This can be found in my core bundle "core.umd.js" in callProviderLifecycles().
If I go to a page by typing the link in the url, it loads as expected. But when I click a "[routerLink]" the error occurs.
I cannot duplicate this on a local ng serve, but only happens when the prod bundle is deployed.

## Expected behavior

Should be able to navigate the site without a console error on each routerLink.

## Minimal reproduction of the problem with instructions

I do not have a demo. But, I updated my Angular environment and started having this error.

## What is the motivation / use case for changing the behavior?

Routing seems to be broken.

## Environment
Taken from my package.json:
    "@angular/animations": "^6.1.9",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.1.9",
    "@angular/compiler": "^6.1.9",
    "@angular/core": "^6.1.9",
    "@angular/flex-layout": "^6.0.0-beta.18",
    "@angular/forms": "^6.1.9",
    "@angular/http": "^6.1.9",
    "@angular/material": "^6.4.7",
    "@angular/platform-browser": "^6.1.9",
    "@angular/platform-browser-dynamic": "^6.1.9",
    "@angular/router": "^6.1.9",

<pre><code>
Angular version: 6.1.9

Browser:
- [x ] Chrome (desktop) version 69.0.3497.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version 62.0.3 (64-bit)
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x ] Edge version 42.17134.1.0
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
