### ISSUE TITLE
i18n translation id for "String + Plural" expression

### ISSUE THREAD

**Issue by andresoviedo** [angular/angular#26379]
## I'm submitting an **i18n feature request**

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am following the Angular 6 i18n guide: https://angular.io/guide/i18n
Apparently there is no option to customize the **id of the inner plural expression** in an interpolated expression like "**String + Plural**"

Example:
```
<span i18n="@@interpolated-time">Time: {minutes, plural, other {{{minutes}} elapsed}}</span>`

<trans-unit id="interpolated-time" datatype="html">
        <source>Time: <x id="ICU" equiv-text="{minutes, plural, other {...}}"/></source>
        <target>Tiempo: <x id="ICU" equiv-text="{minutes, plural, other {...}}"/></target>
</trans-unit>
<trans-unit id="plural-time" datatype="html">
        <source>{VAR_PLURAL, plural, other {<x id="INTERPOLATION" equiv-text="{{minutes}}"/> elapsed} }</source>
        <target>{VAR_PLURAL, plural, other {<x id="INTERPOLATION" equiv-text="{{minutes}}"/> transcurridos} }</target>
      </trans-unit>
```

The result is:  `Tiempo: 1440 elapsed`

The workaround is to separate the expression in 2 simple expressions "string" + "plural".

## Expected behavior

- The translation result should be `Tiempo: 1440 transcurridos`
- Either, trans-unit should be detected automatically (by source) or the inner expression id should be customizable.

## What is the motivation / use case for changing the behavior?

- Generating random translation id for inner expressions is not mantainable.
- Managing inner expression ids is mantainable.

## Environment

<pre><code>
Angular version: 6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by andresoviedo** [comment]
AFAIK, Angular splits "String + Plural" expression in 2 simpler expressions.

The plural inner expression gets a random identifier and it should match the trans-unit "id" in the messages.xlf file in order to work.

The exact **Translate a nested expression** example in https://angular.io/guide/i18n should be like this:

    <trans-unit id="interpolated-time" datatype="html">
        <source>Updated: <x id="ICU" equiv-text="{minutes, plural, =0 {...} =1 {...} other {...}}"/></source>
        <target>Actualizado: <x id="ICU" equiv-text="{minutes, plural, =0 {...} =1 {...} other {...}}"/></target>
      </trans-unit>
      <trans-unit id="7151c2e67748b726f0864fc443861d45df21d706" datatype="html">
        <source>{VAR_PLURAL, plural, =0 {just now} =1 {one minute ago} other {<x id="INTERPOLATION" equiv-text="{{minutes}}"/> minutes ago by {VAR_SELECT, select, male {male} female {female} other {other} }} }</source>
        <target>{VAR_PLURAL, plural, =0 {justo ahora} =1 {hace 1 minuto} other {hace <x id="INTERPOLATION" equiv-text="{{minutes}}"/> minutos por {VAR_SELECT, select, male {un hombre} female {una dama} other {otro} }} }</target>
      </trans-unit>


The id **7151c2e67748b726f0864fc443861d45df21d706** should be obtained from compilation output:

    Missing translation for message "7151c2e67748b726f0864fc443861d45df21d706"

Is there any option to customize this **random generated id** in the expression?

**Comment by izogfif** [comment]
Here is the related StackOverflow question: https://stackoverflow.com/questions/52745049/angular-i18n-interpolation
