### ISSUE TITLE
Method decorators that live on the class

### ISSUE THREAD

**Issue by btford** [angular/angular#2638]
For the router, I need some way to implement lifecycle hooks. After chatting with @yjbanov, it sounds like for Dart, interfaces are the way to go. But for JS, I think we want decorators that look like this:

```js
MyCmp {
  @CanActivate()
  doAuth(){ ... }
}
```

I want to be able to ask `MyCmp` for its `CanActivate` decorators rather than asking `MyCmp.prototype.doAuth` for its decorators and then filtering by `instanceof CanActivate`.

I'll also need a facade that does either `is CanActivateInterface` for Dart, but checks the decorators for JS.

/cc @IgorMinar

**Comment by btford** [comment]
Needed for #2640

**Comment by yjbanov** [comment]
What is the final proposal? Or is this issue a RFC? I should point out that we need something similar for core lifecycle methods (`onChange`, `onDestroy`). Whatever we decide to do, we should make sure we're consistent.

**Comment by mhevery** [comment]
We check for method names (structural check) in JS and implements in Dart. Can't we just do the same here?

So:

```
class MyCompon {
  onInit() {}
}
```

should implement `OnInit` interface. 

PS: Not sure if that feature has been implemented yet, but it has been discussed.

**Comment by naomiblack** [comment]
No assignee; less urgent --> backlog. This should be provided by angular core, not just a router change.

**Comment by btford** [comment]
@yjbanov – I'm not sure what's best. I just want to be able to reflect on a class and see whether or not it has a given hook in a way that is idiomatic for Dart and idiomatic for TS.

Since core lifecycle methods should follow the same pattern, it'd be good if someone who understands those better could own this.

@naomiblack – Is there anyone with free cycles this week who could own this? @rkirov also knows about this.

**Comment by naomiblack** [comment]
After much discussion and whiteboard with @tbosch and @rkirov, @btford will implement a solution based on interfaces for Dart and on checking at runtime whether the field exists in javascript. We'll use this to find out if it works as a solution for GT.

**Comment by btford** [comment]
I summarized what this will look like in terms of the router here: https://github.com/angular/angular/issues/2640#issue-89635006

I'll start with the Dart and ES5 approaches, and then later handle the decorator approach. We'll still need to implement Method Decorators when we get to TS, so this should remain open.

**Comment by btford** [comment]
I'm going to move this to the backlog because are more urgent issues and I'm not likely to get to this in the next two releases.

**Comment by mhevery** [comment]
Will not implement.
