### ISSUE TITLE
Uncaught (in promise): Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by gowthamr123** [angular/angular#26389]
### Versions
"devDependencies": {
    "@angular-devkit/build-angular": "^0.7.0-rc.0",
    "@angular/cli": "^6.2.3",
    "@angular/compiler-cli": "^6.1.8",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "pre-commit": "^1.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }

### Repro steps

Getting following error when using external angular elements (webcomponents) in my angular application.

![error](https://user-images.githubusercontent.com/3348112/46615320-88956f00-cb35-11e8-8cb6-f7396cf77f2d.png)

It occurs only when building in production mode (ng build --prod), when optimisation is set true and with lazy loading.

headerfooter is a JS file that is generated as part of webcomponent. Following is the AppModule file of webcomponent.
```

Git repo :

https://github.com/gowthamr123/repro-app

after running npm install do ng serve and go to below url :

http://localhost:4200/selfcare/tariff-change

It will work fine.

Now run in production mode ng serve --prod

Error occurs :

Uncaught (in promise): TypeError: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined

Following is the index.html of end application where I am using angular elements by including js files. **This issue occurs when using lazy loading and ng build --prod.**


### Desired functionality
ng build --prod should work correctly

**Comment by igor-smi** [comment]
I have the same problem

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
