### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError After upgraded to Angular 6

### ISSUE THREAD

**Issue by yc-shawn** [angular/angular#26385]
## `ExpressionChangedAfterItHasBeenCheckedError` After upgraded to Angular 6 with same code

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior
After I upgraded Angular from 5 to 6, `ExpressionChangedAfterItHasBeenCheckedError` shows up for the `ngForOf` and `ngIf` with exact same code. And only for dev envirmonent, if I'm using prod envirmonent, the bug not shows up

## Expected behavior
dev envirmonent should be same with the prod environment

## What is the motivation / use case for changing the behavior?
Upgrade to angular 6

## Environment

<pre><code>
Angular version: 6.1.10

Browser:
- [x] Chrome (desktop) version 69.0.3497.100
 
For Tooling issues:
- Node version: 8.10.0
- Platform:  Mac

**Comment by mlc-mlapis** [comment]
@yc-shawn ... things were improved in the code between version 5 and the version you are using now (it means also some issues with the CD checking).

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
