### ISSUE TITLE
build(ivy): changes to ngtsc cause full rebuild of npm packages

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#26392]
To reproduce, check out a clean copy of master, then build the distributables, make a change to a file in ngtsc that doesn't affect output of ngtsc and then build again.

I would expect that only the compiler and compiler-cli packages would need to be rebuilt. Instead all the angular packages are rebuilt (both via the TypeScript and `ng_package` rules) even though they have not changed.

This may be related to the fact that `ngc` is run over each of the packages, and `ngc` is dependent upon `ngtsc`.

```
$ git checkout master
$ ./scripts/build-packages-dist.sh 

INFO: Analysed 23 targets (49 packages loaded).
INFO: Found 23 targets...
...
INFO: Elapsed time: 1247.429s, Critical Path: 206.70s
INFO: 402 processes: 288 darwin-sandbox, 114 worker.
INFO: Build completed successfully, 1387 total actions

# now make a change to a file such as packages/compiler-cli/src/ngtsc/metadata/src/reflector.ts
# e.g. add a console.log() statement to a method

$ ./scripts/build-packages-dist.sh 

INFO: Analysed 23 targets (1 packages loaded).
INFO: Found 23 targets...
WARNING: TypeScriptCompile worker (id 3) can no longer be used, because its files have changed on disk:
bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped_bin.runfiles/angular/external/nodejs/bin/nodejs/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSUtil.pyc: 5ea4054a61bfbe521e6f6c59dd4887abdab21c7e89f1c7b073dd6118676eae99 -> <none>
...
INFO: Elapsed time: 1104.717s, Critical Path: 195.21s
INFO: 402 processes: 288 darwin-sandbox, 114 worker.
INFO: Build completed successfully, 423 total actions
```

**Comment by IgorMinar** [comment]
@alexeagle or @gregmagolan could you take a look? this seems related to: https://github.com/bazelbuild/rules_typescript/issues/300

**Comment by dylhunn** [comment]
I haven't heard any complaints about this, and Pete has left, so closing as WAI.
