### ISSUE TITLE
Needed suggestions related to aio-toc

### ISSUE THREAD

**Issue by Mythrim** [angular/angular#26390]
Hi, I am working on anchor scrolling in an application which is using angular 6, So I am able to achieve the anchor scrolling using fragment and router in angular 6, To highlight active anchor links on the scroll which is similar to aio-toc can you suggest how can we achieve that for the smaller purpose.

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
