### ISSUE TITLE
Style guide: Leading underscore conflict with TypeScript docs

### ISSUE THREAD

**Issue by pburkindine** [angular/angular#26393]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The style guide states:

```
Avoid prefixing private properties and methods with an underscore.
https://angular.io/guide/styleguide#style-03-04
```

This is in conflict with how TypeScript documentation suggests we create getters and setters, and the behavior of both WebStorm and the prominent VSC extension when autogenerating getters and setters.

The pattern is like:
```
export class Foo {
  private _bar: string;

  ...

  public get bar(): string { return this._bar; }
```

Ref:

https://www.typescriptlang.org/docs/handbook/classes.html#accessors

https://github.com/johnpapa/angular-styleguide/issues/861

## Expected behavior

Style guide should either provide a recommendation on preferred alternative or remove this guideline.

Preferred alternative should be lintable, by e.g. tslint-consistent-codestyle.naming-convention (should be a universal rule for private fields and methods).

## What is the motivation / use case for changing the behavior?

Our organization is put in friction because we are required to encapsulate, required to follow TS documentation, and required to follow the style guide.

## Environment

<pre><code>
Angular version: N/A

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
This has been discussed before https://github.com/angular/angular/issues/16893 (specially this one), https://github.com/angular/angular.io/issues/1108, https://github.com/johnpapa/angular-styleguide/issues/703. Really old issues though.

**Comment by pburkindine** [comment]
Yeah, have read the threads and I do understand the rationale. Ynfortunately, it's in conflict with other official documentation and the behavior of the tooling.  Docs should at minimum suggest an alternative convention imo.

**Comment by pburkindine** [comment]
Mentioned this to Google folks at Angular Mix this week and was advised to open an issue.

**Comment by nik72619c** [comment]
May I work on this if no one has taken it?

**Comment by pburkindine** [comment]
I'm not sure what you mean.  The case shown is the one from the TypeScript docs:

```
class Employee {
    private _fullName: string;

    get fullName(): string {
        return this._fullName;
}
```

If there is another pattern that is recommended, the style guide should include it.  This pattern is the one autogenerated by the tooling in both Storm and VSC.

**Comment by manklu** [comment]
@pburkindine Yes, and the attribut must not have the same name as the getter.

The style guide says you should avoid it. If it is unavoidable, do what you want.

**Comment by manklu** [comment]
@pburkindine You should avoid prefixing **every** private attribute with an underscrore. In your case it's the best solution to the problem.

IMO Avoid doesn't mean forbidden.

**Comment by pburkindine** [comment]
That answer would be fine if it could be included in the docs,

'Avoid using leading underscore, except for backing variables of public properties...'

From the linting perspective that's not an easy thing to enforce, though?

**Comment by pburkindine** [comment]
As far as avoid vs forbid goes, folks should understand that this style guide is being treated as "official best practices" documentation by consumers, and as such nobody's home if I go around claiming I think an exception should be made in such and such cases.

Since this is a very common use case, the style guide needs to address it imo.

**Comment by jenniferfell** [comment]
@IgorMinar : Please weigh in on this. Thanks!

**Comment by pburkindine** [comment]
@mikesm I am fine with the idea of a suffix. My main concern is that some official recommended workaround be included in the docs, even if it's vague like

`<b>Consider</b> using a suffix on variables exposed by accessors/mutators`

**Comment by julianpoemp** [comment]
Adding a new rule to my tslint.config fixed to me:
    
    "variable-name": [
      true,
      "allow-leading-underscore"
    ]

I'm using PHPStorm and the "no-underscore" rule makes no sense to me. It's much easier and more efficient to use an leading underscore. Adding prefixes like "get" or "set" to getter/setters makes the code ugly. That's not Java, it's Typescript. 

Furthermore the angular guidelines describes only that underscores shouldn't be used but explain nothing about any alternative when using getter/setters. Renaming the getter/setters manually is not an option.
https://angular.io/guide/styleguide#style-03-04

**Comment by pburkindine** [comment]
@jenniferfell @IgorMinar any update here?

**Comment by trotyl** [comment]
Closed by https://github.com/angular/angular/pull/30334, all these conventions have been removed.

**Comment by dalu** [comment]
This is still or rather has become an issue in Webstorm for a few months already.
Adding what julianpoemp wrote to tslint under rules does nothing.
And with every git commit and code being analyzed it triggers new warnings, which is annoying, a waste of time.
I'm blaming this line in tslint.json
```
  "rulesDirectory": [
    "codelyzer"
  ]
```

It makes no sense that you have to edit every project's tslint settings.
allow-leading-underscore should be default.

**Comment by pburkindine** [comment]
@trotyl Thanks, I very much appreciate you all working on this

**Comment by cedvdb** [comment]
@pburkindine why did you close this ?
