### ISSUE TITLE
Add description to the Angular(2) gitter chat.

### ISSUE THREAD

**Issue by chrisber** [angular/angular#2639]
There are many questions for Angular 1 in the Angular(2) [gitter](https://gitter.im/angular/angular) chat lately. Because people can not distinguish between these two. Furthermore Several questions about `is Angular ready`are spamming the room.
Gitter supports to add a descriptions below the header name. Is it possible that the you add a description there to clarify that this room is Angular2.

Helpful would be also to add these links to mute repeating questions:
- [Is Angular2 ready?](http://splintercode.github.io/is-angular-2-ready/)
- [Official resources](https://angular.io/docs/js/latest/resources.html)
- [Community resources](https://github.com/timjacobi/angular2-education)

**Comment by mhevery** [comment]
I am happy to add this, but I can't seem to find where I can do this in Gitter. Do you have a link?

**Comment by SebastianM** [comment]
@mhevery Double-click on the white space underneath the angular/angular headline should work.

**Comment by chrisber** [comment]
Yes that is the correct solution, not really intuitive. Thanks for doing that.

**Comment by mhevery** [comment]
DONE. Limited non breakable space so I did not add the rest of the text.
