### ISSUE TITLE
feat(router): lifecycle hooks

### ISSUE THREAD

**Issue by btford** [angular/angular#2640]
Implement lifecycle hooks: `CanActivate`, `CanReuse`, `CanDeactivate`, `Activate`, `Reuse`, and `Deactivate`.

For ES5:

```
function Cmp() {
  // hook inferred by name
  this.$canActivate = function () { ... };
}
```

For TS:
```
class Cmp {
  // hook inferred by decorator
  @CanActivate()
  foo():Promise<boolean> { ... }
}
```

For Dart:
```
class Cmp implements CanActivateLifecycle {
  // hook inferred by interface
  canActivate() { ... }
}
```

**Comment by btford** [comment]
Pushing this to alpha-29 to prioritize #2642.

**Comment by mhevery** [comment]
We already do something similar for `OnChange`, `OnInit`, and so on, please follow the same style.

**Comment by naomiblack** [comment]
This is blocked by a general core feature that is needed (https://github.com/angular/angular/issues/2638)
