### ISSUE TITLE
lazy loaded feature module in angular 6 library giving the error

### ISSUE THREAD

**Issue by bharu12345** [angular/angular#26414]
Hi,

I am implement lazy loading feature module in  angular 6 library, library build working fine but when I run the ng serve getting the error "ERROR in Could not resolve module ./fall-out/fall-out.module relative to D:/angular_multiple_apps/app_demo/dashboard-management/dist/dashboard-management/dashboard-management.d.ts". route for the lazy load
{
        path: 'fallout',
        loadChildren: './fall-out/fall-out.module#FallOutModule',
        outlet: 'fallout'
      }

I tried with absolute path as well but still getting the error.

It will be great if some one can provide their inputs.

Thanks,

**Comment by shabbir-dhangot** [comment]
SO answer might be helpful in this case. https://stackoverflow.com/questions/47601637/angular-4-could-not-resolve-submodule-for-for-routing

**Comment by lazarljubenovic** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
