### ISSUE TITLE
Highcharts not showing colors in charts - Angular 6

### ISSUE THREAD

**Issue by a2441918** [angular/angular#26423]
## I'm submitting a...

<pre><code>
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
doesnt show color of charts

## Expected behavior
show proper color of charts

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ x] Chrome (desktop) version 68.0.3440.106
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x ] IE version XX
- [x ] Edge version XX
 
For Tooling issues:
- Node version: Node 10.11.0
- Platform:  Windows

Others:

</code></pre>

Hi I have a couple of charts showing up in my app. I am using Angular-Highcharts package and for some reason the colors dont show up properly in my chart.

[![enter image description here][1]][1]

I inspected using chrome dev tools and it shows that the fill is transparent.

I also have a sunburst chart implemented and it works just fine.

I even tried the demo code form [here][2] but its still the same with the demo code.

I kinda get a feel its got to do with the compiler.

Anyone experienced this and fixed this? Please advice.

This is a screenshot of the demo code on my machine.

[![enter image description here][3]][3]

I did it in [Stackblitz][4] and it works fine. The same code is running on my local machine as well as on my server.

  [1]: https://i.stack.imgur.com/JGDoR.png
  [2]: https://www.highcharts.com/demo/combo-dual-axes
  [3]: https://i.stack.imgur.com/ypmM5.png
  [4]: https://hello-angular-6.stackblitz.io

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
