### ISSUE TITLE
Remove component from CLI

### ISSUE THREAD

**Issue by ahamedama** [angular/angular#26429]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Generating component is already equipped well. But deleting the component is also be a much-needed feature.

## Expected behavior

Deleting means
-Remove the generated component files.
-Remove the references that made when generating the component file.

## What is the motivation / use case for changing the behavior?

A lot to say here! It's the painstaking thing to check all the instance of reference and its files If a developer made a typo

## Environment

<pre><code>
Angular version: X.Y.Z

Yes, upto the recent version.

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sarunint** [comment]
Wrong repo, use https://github.com/angular/angular-cli instead.

**Comment by ahamedama** [comment]
Thanks @sarunint. I will close here and open right there

**Comment by ahamedama** [comment]
@sarunint Kindly take a look and feel free to contribute if possible. 
https://github.com/angular/angular-cli/issues/12576
