### ISSUE TITLE
feat(router): deep-linking

### ISSUE THREAD

**Issue by btford** [angular/angular#2642]
- [x] `router.generate` takes an array like `['/foo', { id: 3 }, 'bar', {post: 4}]` and returns a URL.
  - [ ] for now, each URL must start with `./` (child), `/` (root), or `..` (parent) – later we can implement a sane default behavior for segments with no prefix
- [x] `router-link` directive uses router.generate API
- [ ] Exception thrown when route not found (see #2323)
- [ ] Ability to link to route params for the current route without affecting children: `[router-link] = "[{ order: 'asc' }]"`

**Comment by btford** [comment]
JK, this is what I'll work on next week.

**Comment by naomiblack** [comment]
This should be landing by July 1 -- just missed the alpha-29 cutoff. Igor and Brian were pairing on this today.
