### ISSUE TITLE
Angular ng binding problem: primeng p-table will not update immediately when datas changed due to triggered by echarts legendselectchanged event

### ISSUE THREAD

**Issue by qiaojianqj** [angular/angular#26427]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

<img width="993" alt="3665ad50-d861-4aee-bef6-8405a33ff7d5" src="https://user-images.githubusercontent.com/4402452/46900133-f643f100-cecf-11e8-94f7-e6df1b58a576.png">

I have a echarts to show all datas and a primeng p-table to display the specified datas.

I expect that I click the legends in echarts to trigger the corresponding specified datas in p-table to change and update.
But the fact that the datas in p-table has changed but the p-table display has not update.

Click the legends in echarts to trigger a legendselectchanged event, and then emit a EventEmitter in the legendselectchanged event handler function. 
In the Component, handle the EventEmitter event. I  has changed the p-table [value] binding datas in the handler, but the p-table will not update immediately.  It just update when mouse move out of the echarts.

I think the problem is due to the ng binding mechanism.

## Expected behavior

I expect that I click the legends in echarts, the p-table will update immediately.

## Minimal reproduction of the problem with instructions

STEPS 1:  echarts to show some datas, primeng p-table to show some other datas
STEPS 2:  register a legendselectchanged event, emit a EventEmitter event in the handler
STEPS 3:  caputer the EventEmitter event in  component where echarts is referenced, and then change the primeng p-table datas in the EventEmitter event handler

## What is the motivation / use case for changing the behavior?

Click legend in echarts to trigger legendselectchanged event,
then emit an EventEmitter in the legendselectchanged event handler.
Capture the EventEmitter event in where you used the echarts component, you change the p-table value binding datas in the EventEmitter event handler.

## Environment

<pre><code>
Angular version: 6.1.0
echarts version: 4.1.0
primeng version: 6.1.0

Browser:
- [X] Chrome (desktop) version 69.0.3497.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.8.0  
- Platform:  Mac 

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
