### ISSUE TITLE
[DART transformers] Inline Import Styles inlined to page

### ISSUE THREAD

**Issue by TedSander** [angular/angular#2643]
Low Priority feature request. Have an option to inline @import in styles tags inside of the html templates from transformers.

**Comment by vicb** [comment]
related to #1694

**Comment by tbosch** [comment]
If the dart transformer used the `ViewLoader`, it would get inlining automatically as of the latest commits from @vicb

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
