### ISSUE TITLE
Why Vue's stars or React's stars is more than yours?

### ISSUE THREAD

**Issue by AmandaYi** [angular/angular#26431]
Why Vue's stars or React's stars is more than yours? 
116k  VUE
113K React
41K Angular
Thanks

**Comment by sarunint** [comment]
I don't think it matters which framework has more stars.

**Comment by mlc-mlapis** [comment]
@AmandaYi ... it could be also highly related to the social behavior. I mean how different people perceive and what they need to entrust to their surroundings. So the fact could be that Angular has simply different type of developers. If they were all like me, Facebook has only 10 users, for example ...

**Comment by ericmartinezr** [comment]
Why? Because people is free to like whatever they want :D

Also https://github.com/angular/angular/issues/24140

**Comment by lazarljubenovic** [comment]
It's all a part of a mass-scale psychological experiment based on a mutual agreement between Google, Facebook and the Chinese government to see if people _really_ choose a framework based on the star count. 

Thank you for your contribution; they've just incremented The Counter © based on this thread.

<sub>PS. The Counter © was written in Angular.</sub>

**Comment by bradlygreen** [comment]
Hey folks, yes what @mlc-mlapis says is right to our knowledge - it's mostly about who uses Angular. Enterprise developers are traditionally not as concerned with open source and aren't as active on GitHub (and Twitter). This is similarly why NPM downloads are a poor signal for us as the majority of enterprises use a cache (jFrog, etc.). See my keynote from last week for details on our momentum http://bit.ly/AngularMix-2018.

At the same time, we'd love to grow in the folks who do use GitHub as well as Enterprise. We'll be pushing on this next year with the Ivy renderer, Angular Elements, and much simpler ways to get started with Angular for lightweight use cases.

**Comment by steida** [comment]
Stars are not relevant. Issues are. And in that game Angular is the winner.

**Comment by steida** [comment]
Stars are not relevant. Issues are. And in that, Angular is the winner.

**Comment by lazarljubenovic** [comment]
The only three relevant things for choosing a framework are:

- Can it get the job done?
- Do you enjoy working with it?
- Does it speed up the process instead of slowing you down, on the long run?

The first one depends on the project. The other two depend on the person. Hence there can be no objective ultimate method to deduce which framework is "better". You can compare them in various ways but ultimately the comparison means nothing and you need to evaluate (per project, per team) over the three questions above.

</thread>

**Comment by IgorMinar** [comment]
I believe that @mlc-mlapis and @bradlygreen answered this sufficiently. I'm going to close this issue now. If the number of github stars matters to you, you can ask your fellow Angular developers to go and star the repo. Thanks!!
