### ISSUE TITLE
Create New Project issue

### ISSUE THREAD

**Issue by InCodingNowLiu** [angular/angular#26446]
CREATE frontend/README.md (1025 bytes)
CREATE frontend/angular.json (3416 bytes)
CREATE frontend/package.json (1312 bytes)
CREATE frontend/tsconfig.json (384 bytes)
CREATE frontend/tslint.json (2805 bytes)
CREATE frontend/.editorconfig (245 bytes)
CREATE frontend/.gitignore (503 bytes)
CREATE frontend/src/environments/environment.prod.ts (51 bytes)
CREATE frontend/src/environments/environment.ts (631 bytes)
CREATE frontend/src/favicon.ico (5430 bytes)
CREATE frontend/src/index.html (295 bytes)
CREATE frontend/src/main.ts (370 bytes)
CREATE frontend/src/polyfills.ts (3194 bytes)
CREATE frontend/src/test.ts (642 bytes)
CREATE frontend/src/assets/.gitkeep (0 bytes)
CREATE frontend/src/styles.css (80 bytes)
CREATE frontend/src/browserslist (375 bytes)
CREATE frontend/src/karma.conf.js (964 bytes)
CREATE frontend/src/tsconfig.app.json (194 bytes)
CREATE frontend/src/tsconfig.spec.json (282 bytes)
CREATE frontend/src/tslint.json (314 bytes)
CREATE frontend/src/app/app.module.ts (314 bytes)
CREATE frontend/src/app/app.component.css (0 bytes)
CREATE frontend/src/app/app.component.html (1141 bytes)
CREATE frontend/src/app/app.component.spec.ts (986 bytes)
CREATE frontend/src/app/app.component.ts (207 bytes)
CREATE frontend/e2e/protractor.conf.js (752 bytes)
CREATE frontend/e2e/src/app.e2e-spec.ts (299 bytes)
CREATE frontend/e2e/src/app.po.ts (208 bytes)
CREATE frontend/e2e/tsconfig.e2e.json (213 bytes)
npm ERR! Unexpected end of JSON input while parsing near '...va":"0.21.0","xo":"0.'

npm ERR! A complete log of this run can be found in:
npm ERR! /xxx/xxxx/.npm/_logs/2018-10-15T02_29_07_327Z-debug.log
Package install failed, see above.

**Comment by InCodingNowLiu** [comment]
2961 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...va":"0.21.0","xo":"0.'
2961 verbose stack at JSON.parse ()
2961 verbose stack at parseJson (/Users/jliu396/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
2961 verbose stack at consumeBody.call.then.buffer (/Users/jliu396/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
2961 verbose stack at 
2961 verbose stack at process._tickCallback (internal/process/next_tick.js:188:7)
2962 verbose cwd /Users/jliu396/myProject/normalBackend/frontend
2963 verbose Darwin 17.7.0
2964 verbose argv "/Users/jliu396/.nvm/versions/node/v8.9.1/bin/node" "/Users/jliu396/.nvm/versions/node/v8.9.1/bin/npm" "install"
2965 verbose node v8.9.1
2966 verbose npm v6.1.0
2967 error Unexpected end of JSON input while parsing near '...va":"0.21.0","xo":"0.'
2968 verbose exit [ 1, true ]

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by pkozlowski-opensource** [comment]
Please re-open in https://github.com/angular/angular-cli
