### ISSUE TITLE
Do not switch to client App in server side Rendering ?

### ISSUE THREAD

**Issue by shubh4git** [angular/angular#26448]
I do not want to switch my server side rendered page with client app, is there any solution to do that and in my rendered page i am getting these script tag of pollyfill, and other build.js, how to get rid of these script tag from server side rendered page.

**Comment by lazarljubenovic** [comment]
> I do not want to switch my server side rendered page with client app

Then do not use Angular.

**Comment by shubh4git** [comment]
I have deployed the client side version which is working great. I just
wanted to use server side rendering for serving dynamic page to GoogleBot.
In this case there is no need of switching server side rendered page to
client App. Please provide the solution as i am new to Angular Universal.

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
