### ISSUE TITLE
Any plans for angular team to end support for IE 11 ?

### ISSUE THREAD

**Issue by sreekumarp** [angular/angular#26449]
Just curious to know when Angular team is going to end support for IE 11 or any plans yets?

My question is in favour if these blog posts,

- [The End of Life of Internet Explorer 11][1]
- [Chrome now most used browser in the enterprise: analyst][2]
- [King Chrome: Microsoft's browsers sidelined on its own OS][3]
- [Who's still using Internet Explorer? And why won't they upgrade?][4]

  [1]: https://medium.com/@burger.neal/the-end-of-life-of-internet-explorer-11-12736f9ff75f
  [2]: http://www.cw.com.hk/digital-transformation/chrome-now-most-used-browser-enterprise-analyst
  [3]: http://www.computerworld.com/article/3198479/microsoft-windows/king-chrome-microsofts-browsers-sidelined-on-its-own-os.html
  [4]: https://www.zdnet.com/article/whos-still-using-internet-explorer-and-why-wont-they-upgrade/

**Comment by IgorMinar** [comment]
v7 and most likely also v8 will still support IE11. We've been gradually working on supporting primarily newer browsers and depending on optional polyfills for older browsers. We are working on a plan to be more aggressive about this and actually providing two different build outputs from the CLI - one for modern browsers and one for old browser (e..g IE11).

**Comment by mixalistzikas** [comment]
Any plans about IE11?

**Comment by hakimio** [comment]
@IgorMinar do you have any concrete plans to end IE11 support anytime soon?

**Comment by waynon** [comment]
According to this RFC, Vue 3 is going to drop ie11 support.
https://github.com/vuejs/rfcs/pull/294

**Comment by mlc-mlapis** [comment]
@waynon It was already decided, and IE11 will be depreciated in Angular 12.

https://github.com/angular/angular/pull/41147/commits/24f946a2e54c80f9d843ee0c616657b5d358269d

**Comment by gkalpak** [comment]
Closing (see https://github.com/angular/angular/issues/26449#issuecomment-820458913).
