### ISSUE TITLE
String Externalisation documentation is not provided in angular website

### ISSUE THREAD

**Issue by NayabHussain** [angular/angular#26441]
## Current behaviour
We are trying load string label constants based on some criteria, So that it can be configurable without build and code modification.

## Expected behaviour
Should provide some configuration files outside of an app folder, based on the criteria, fetch the specific label configurations and the app should load after getting the configuration file.

We need to have some configurations like the example described below.

## Example: 
**app.component.html**
<i class="fa fa-calendar"></i>{{labelConstant.TEST_LABEL}}

**app.component.ts**
export class AppComponent {
            LabelConstant = LabelConfig.getLabels();
}

**college.json**
{
        "TEST_LABEL" : "Internal Assessment Configuration"
}

**schooling.json**
{
        "TEST_LABEL" : "Unit Test Configuration"
}

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
