### ISSUE TITLE
Service Worker configuration documentation for datagroups.cacheConfig.timeout

### ISSUE THREAD

**Issue by antonin07130** [angular/angular#26454]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When setting up Angular service worker, the section about `dataGroups` does not explain the formatting nor the unit used for `timeout` item : https://angular.io/guide/service-worker-config#timeout

## Expected behavior

`a description of timeout unit and/or formatting.`

## Minimal reproduction of the problem with instructions

this dataGroups section is invalid because timeout string contains `ms` the provided error message from angular does not explain where the error is from in the json configuration file.
```json
"dataGroups": [
    {
      "name": "api",
      "urls": ["/api/**"],
      "cacheConfig": {
        "maxSize": 100000,
        "maxAge": "1d",
        "timeout": "3000ms",
        "strategy": "performance"
      }
    }
  ]
```
## What is the motivation / use case for changing the behavior?
I did have to chek timeout unit in code, and timeout formatting as string (but expecting a number).

## Environment

Angular version: 6.1.0

**Comment by Nazanin1369** [comment]
I am working on this

**Comment by jenniferfell** [comment]
Closed by https://github.com/angular/angular/pull/26469
