### ISSUE TITLE
HttpClient response observable is not cleaned up on Safari when requests times out

### ISSUE THREAD

**Issue by alleyj** [angular/angular#26453]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

On Safari only if a request made via HttpClient times out, such as if the server is not connected to the network, the observable returned by HttpClient never emits an error. The core problem is that Safari sends a timeout event in this situation instead of an error event.

This was written up and fixed in AngularJS [#15380](https://github.com/angular/angular.js/issues/15380#issue-188287735).
This has been written up before for Angular #13592 but was closed as part of a feature that got dropped.

## Expected behavior

Request timeouts should emit an error on the response observable.

## Minimal reproduction of the problem with instructions

<pre><code>
import { HttpClient } from '@angular/common/http';

  // IP Address of some machine that isn't connected to the network
  this.httpClient.get('x.x.x.x')
  .subscribe(() => {
    console.log('Request succeeded');
  }, () => {
    // This block never runs on Safari
    console.log('Request failed');
  })
</code></pre>

## What is the motivation / use case for changing the behavior?

So we can properly handle request errors.

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version 12, 9
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by alxhub** [comment]
Yep - this should be fixed.
