### ISSUE TITLE
ng serve does not recognize "Accept: */*" header and returns a 404 for requests with route fragments

### ISSUE THREAD

**Issue by vsviridov** [angular/angular#26464]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Requesting a site using IE and a route causes the server to return 404

## Expected behavior

Page should load and application should work

## Minimal reproduction of the problem with instructions

`curl -sv "http://angular.app/someRoute" -H "Accept: text/html"` returns 200
`curl -sv "http://angular.app/someRoute" -H "Accept: */*"` returns 404

run `ng serve` and try accessing the site in IE using short form for the url

## Caveats
Do not use FQDN
Use a route fragment

## Investigation
IE in some cases enforces compatibility mode for intranet sites.
Short form domain name makes IE think it's an intranet site
IE sends different Accept header in compatibility mode, but it does include a `*/*` fallback
`ng serve` `express` middleware does some content negotiation and seems to ignore `*/*` prefering `text/html`

## Environment

<pre><code>
Angular CLI: 6.0.5                                              
Node: 8.11.3                                                    
OS: linux x64                                                   
Angular: 6.0.5                                                  
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser                    
... platform-browser-dynamic, platform-server, router           
                                                                
Package                           Version                       
-----------------------------------------------------------     
@angular-devkit/architect         0.8.4                         
@angular-devkit/build-angular     0.8.4                         
@angular-devkit/build-optimizer   0.8.4                         
@angular-devkit/build-webpack     0.8.4                         
@angular-devkit/core              0.6.5                         
@angular-devkit/schematics        0.6.5                         
@angular/cdk                      6.2.1                         
@ngtools/webpack                  6.2.4                         
@schematics/angular               0.6.5                         
@schematics/update                0.6.5                         
rxjs                              6.2.1                         
typescript                        2.7.2                         
webpack                           4.20.2                        

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X] IE version 11
- [ ] Edge version XX
</code></pre>

**Comment by trotyl** [comment]
Wrong repo, please report it to https://github.com/angular/angular-cli.
