### ISSUE TITLE
[DART transformers] Add a baseUrl to @View directive with transformers

### ISSUE THREAD

**Issue by TedSander** [angular/angular#2646]
The angular system needs to know the original url for a view. This is specified in the baseUrl attribute. Transformers strip this information when they are inling the View. Calculate and write the baseURL back to the directive metadata.

**Comment by jakemac53** [comment]
@sigmundch I think you had a fix for this?

**Comment by sigmundch** [comment]
My fix was to preserve the `templateUrl` while doing inlining (see https://github.com/angular/angular/commit/62589293aaa9efc6849e06c7f3629731699784de), @TedSander - is this addressing the issue?

**Comment by mhevery** [comment]
@TedSander Is there an update on this?

**Comment by TedSander** [comment]
Sorry yes marking this as closed.
