### ISSUE TITLE
Remove "setup for local development" and dependency on old QuickStart repo

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#26461]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Some documents still depend on the old QuickStart repo ( https://github.com/angular/quickstart.git)  and the related "Setup for Local Development" doc. 

These docs are affected: 
https://angular.io/guide/setup
https://angular.io/guide/typescript-configuration
https://angular.io/guide/deployment
https://angular.io/guide/upgrade
https://angular.io/guide/upgrade-performance

Related discussion on PR https://github.com/angular/angular/pull/26380

## Expected behavior

Nothing should depend on the old QuickStart repo. 

https://angular.io/guide/setup - This document should be removed. URL should redirect to https://angular.io/guide/quickstart.

These other docs should be updated to reference Getting Started (https://angular.io/guide/quickstart) and the initial app created by `ng new` or the app at the end of that Getting Started.

https://angular.io/guide/typescript-configuration
https://angular.io/guide/deployment
https://angular.io/guide/upgrade
https://angular.io/guide/upgrade-performance

The architecture doc next steps (https://angular.io/guide/architecture-next-steps) contains a link to the setup.md file, but it does not depend on the old QuickStart repo. That link can be replaced with a link to Getting Started right away.

Recommended stages to get us there: 
Setup: Stage 1

* Leave setup the file in the doc set for now.
* Leave setup hidden in the nav for now (as was before this PR).
* Do NOT redirect setup URL.
* Update Architecture next steps link to setup.md to go to quickstart.md

This allows users of dependent docs to see/read the old setup.md, but it removes non-dependent cross references and stops showing the doc in the navigation. 

Setup: Stage 2 

* Rewrite Typescript Configuration to use new getting started app and config files as point-of-reference.
* Rewrite Deployment to use the CLI-generated Getting Started for bundle sizes and lite server
* Rewrite upgrade.md to directly include the main info from setup.md, so that only upgrading users are directed to use the old quickstart repo and app.
* Remove setup.md and do the redirects to quickstart.md

Setup: Stage 3 in a new PR when we have engineering time to ensure we get it right

* Rewrite upgrade.md to use a CLI-based app instead of the old quickstart repo app

## What is the motivation / use case for changing the behavior?

Current best practices. Accuracy for CLI-managed apps. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
Fix for Architecture doc is here: https://github.com/angular/angular/pull/26463

**Comment by jenniferfell** [comment]
Partial fix here: https://github.com/angular/angular/pull/26758

**Comment by alexmiddeleer** [comment]
This docs update would be great. The learning curve for upgrading an Angular.js (v1) app is already daunting, and being ushered over to a deprecated quickstart repo without explaining that "hey, this is still valid for users upgrading angular" would be great. Otherwise, it feels like the guide is outdated (which is scary since I'm not aware of any other guides for this process which are still maintained).

**Comment by aikidave** [comment]
I've done some digging around, and I think we've addressed this issue through numerous documentation updates. I'm closing this issue; however, if there is more work to be done, please let me know!
