### ISSUE TITLE
Header css on main page work incorrect

### ISSUE THREAD

**Issue by EndyKaufman** [angular/angular#26468]
## I'm submitting a...
![wrong-header](https://user-images.githubusercontent.com/4127109/46994182-c47b9600-d12c-11e8-8e2c-48c716974506.png)

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by EndyKaufman** [comment]
for fix add 
```
transform: translateX(12px)!important;
```
to
https://github.com/angular/angular/blob/e8d4211d5c68927ffb82fb0fd97ae8b916cc2add/aio/src/app/app.component.html#L26

result:
      <img *ngSwitchCase="true" src="assets/images/logos/angular/logo-nav@2x.png" style="transform: translateX(12px)!important;" width="150" height="40" title="Home" alt="Home">
:smile:

**Comment by gkalpak** [comment]
Background:
This was broken when upgrading `@angular/material` to 7.x. The `.mat-button` width changed to align with latest Material Design specs in angular/material2#13083.
