### ISSUE TITLE
Feature request: Encapsulated shared styles for the components

### ISSUE THREAD

**Issue by DzmVasileusky** [angular/angular#26476]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

You can import the same css style into a several Angular components and use it.
But it will be duplicated in the `<head>` per each usage like in the example below.
```
<style>
.some-class[_ngcontent-etx-1] {
    color: red;
}
</style>
<style>
.some-class[_ngcontent-etx-2] {
    color: red;
}
</style>
```

## Expected behavior

It would be great to manually add namespace key to share style within components.
```
@Component({
    selector: 'component-1',
    styles: [require('./some-styles.less')],
    stylesNamespace: 'unique-key-1',
    template: '...<div class="some-class"></div>...'
    ...
})
@Component({
    selector: 'component-2',
    styles: [require('./some-styles.less')],
    stylesNamespace: 'unique-key-1',
    template: '...<div class="some-class"></div>...'
    ...
})
```
which would result as
```
<style>
.some-class[_ngcontent-unique-key-1] {
    color: red;
}
</style>
```

**Comment by IgorMinar** [comment]
hi there,

this feature has been implemented a long time ago but you can't use `require` statements to pull the stylesheets in. As long as you import the shared stylesheet via a [styleUrls](https://angular.io/api/core/Component#styleUrls) the compiler will avoid duplication. 

if this feature doesn't work for your use-case, please create a reproduction on stackblitz and file a new issue. thanks
