### ISSUE TITLE
Review public API and angular2.d.ts content

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2647]
- make sure right things are there
- make sure extra things are removed

**Comment by Ludo09** [comment]
```Validators.required``` seems to be missing in Angular2.d.ts (2.0.0-alpha.28)

**Comment by naomiblack** [comment]
reminder: this is blocking some of the api docs effort.

**Comment by naomiblack** [comment]
P2 since design input for pipes is more urgent.

**Comment by mhevery** [comment]
I am hoping that I will get a chance to work on this in the next few days.

**Comment by codylerum** [comment]
Looks like the docs @ https://angular.io/docs/js/latest/api/ are about a month old. 

(rev https://github.com/angular/angular/commits/3a0410a46dcb8db7cf0d9dd0201a533647d1c09e)

Is this related to that?

**Comment by mhevery** [comment]
Have done a some of progress on this:

* #2918 
* #2851 
* #2852
* #2929 
* https://github.com/angular/angular/pull/2996

**Comment by rolandjitsu** [comment]
[Pipes.extend](https://github.com/angular/angular/issues/3422) is also missing and `ViewEncapsulation` as well.

**Comment by mhevery** [comment]
I think This is done. So I am going to close and treat the remainder as specific errors.
