### ISSUE TITLE
Event transitionend is missing in test without breakpoints

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#26475]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I am using a third party library called tingle.js and it adds some CSS animations to its elements. If the browser supports CSS animations, it waits until the transition is completed before calling the callback method.
The current test environment seems to miss this event if not running with an active debugger.

## Expected behavior
The test environment should propagate / handle CSS transitions events from third party library.

## Minimal reproduction of the problem with instructions
https://github.com/CSchulz/angular-missing-transition-end

Run tests with `npm tests` will result in a failing test (ModalComponent).

Run the ModalComponent and enable one breakpoint, the test succeeds.

Run `npm start` to see modal's behavior.

## What is the motivation / use case for changing the behavior?
It would be helpful to be able write tests for own components using third party libraries without mocking some stuff.
tingle.js is only one example, I think there are more libraries out there containing some pre defined animations.

## Environment

<pre><code>
Angular CLI: 6.2.5
Node: 10.11.0
OS: darwin x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.5
@angular-devkit/build-angular     0.8.5
@angular-devkit/build-optimizer   0.8.5
@angular-devkit/build-webpack     0.8.5
@angular-devkit/core              0.8.5
@angular-devkit/schematics        0.8.5
@angular/cli                      6.2.5
@ngtools/webpack                  6.2.5
@schematics/angular               0.8.5
@schematics/update                0.8.5
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.20.2

Browser:
- [X] Chrome (desktop) version 69
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by mhevery** [comment]
We much prefer https://stackblitz.com/edit/angular-example-repro Could you make our life easier by moving the repro there.

**Comment by CSchulz** [comment]
I have used another template, but it shows the issue, too

https://stackblitz.com/edit/testing-lhel3z

**Comment by CSchulz** [comment]
There was a mistake in the repro, I forgot the css.

If you add the breakpoint on the `closeButton.click`, the modal's visibility is changed based on the CSS transition.

**Comment by CSchulz** [comment]
@trotyl There was a mistake in the repro.

I think it is more a timing issue with the test environment.
The test succeeds, if you set a breakpoint at `closeButton.click` and open the debugger.

Perhaps it is not directly related to Angular.

**Comment by trotyl** [comment]
@CSchulz You'll need another timeout before click as that modal also have show-up animation:

https://stackblitz.com/edit/testing-zjf3gd?file=app/modal.component.spec.ts

The problem is completely unrelated to Angular.

**Comment by CSchulz** [comment]
oh my gosh ... i didn't see it the whole time ... 🙄
