### ISSUE TITLE
Found the synthetic property @SOME_STATE. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.

### ISSUE THREAD

**Issue by thiagopaiva99** [angular/angular#26485]
## I'm submitting a...

[  ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[  ] Feature request
[  ] Documentation issue or request
[  ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
## Current behavior
```
ERROR Error: Found the synthetic property @menuState. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
    at checkNoSyntheticProp (platform-browser.es5.js:2930)
    at EmulatedEncapsulationDomRenderer2.webpackJsonp.../../../platform-browser/@angular/platform-browser.es5.js.DefaultDomRenderer2.setProperty (platform-browser.es5.js:2898)
    at BaseAnimationRenderer.webpackJsonp.../../../platform-browser/@angular/platform-browser/animations.es5.js.BaseAnimationRenderer.setProperty (animations.es5.js:473)
    at DebugRenderer2.webpackJsonp.../../../core/@angular/core.es5.js.DebugRenderer2.setProperty (core.es5.js:13738)
    at setElementProperty (core.es5.js:9386)
    at checkAndUpdateElementValue (core.es5.js:9305)
    at checkAndUpdateElementInline (core.es5.js:9239)
    at checkAndUpdateNodeInline (core.es5.js:12332)
    at checkAndUpdateNode (core.es5.js:12278)
    at debugCheckAndUpdateNode (core.es5.js:13139)
```
## Expected behavior
Should run without error.

## Minimal reproduction of the problem with instructions
Imported BrowserAnimationsModule in app.module.ts
```
import { BrowserAnimationsModule } from '@angular/platform-browser/animations'
```
Added to imports in app.module.ts
```
imports: [
    BrowserModule,
    BrowserAnimationsModule,
    RouterModule.forRoot(myRoutes),
    HttpModule,
    HttpClientModule,
  ]
```
In my menu component:
```
import { trigger, state, style, transition, animate } from '@angular/animations';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.scss'],
  animations: [
   trigger('menuState', [
    state('closed', style({
        height: '0px',
        overflow: 'hidden'
    })),
    state('opened', style({
        height: '700px',
        overflow: 'scroll'
    })),
    transition('closed <=> opened', animate('500ms 0ms ease-in'))
  ])
 ]
})
```
In the html of the nav-bar:
```
<div class="menu-items" [@menuState]="!open ? 'closed' : 'opened'"></div>
```
To run and test:
```
ng serve --prod
```

## What is the motivation / use case for changing the behavior?
Have the same behavior in production that one has locally

## Environment

Angular version: 6.1.0

Browser:
[x] Chrome (Desktop) version 69.0.3497.81 (Versão oficial) 64 bits
[ ] Chrome (Android) version XX
[ ] Chrome (iOS) version XX
[ ] Firefox version XX
[ ] Safari (desktop) version XX
[ ] Safari (iOS) version XX
[ ] IE version XX
[x] Edge version XX
 
For Tooling issues:
- Node version: 8.4.11
- Platform:  Linux ElementaryOS

Others:

**Comment by thiagopaiva99** [comment]
@IgorMinar man, who can help me with this, do you know? Its very urgent.

**Comment by martinbroeckl** [comment]
+1

**Comment by barocsi** [comment]
ideas for whats causing this? workarounds?
I cant port my ionic 3 app without bumping in a bug each line

**Comment by liam-mcdermott** [comment]
+1
