### ISSUE TITLE
blank space after link text and before period

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#26487]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ X] Other... Please describe:
</code></pre>

## Current behavior

When there is a link followed by a period, we're seeing a blank space before the period. The blank space shouldn't be there. See this PR: https://github.com/angular/angular/pull/26256
The preview of the first table has several instances. Igor thinks dgeni is adding a new line and that new line appears as a blank space. 

`See [Getting Started](guide/quickstart).`

Would appear as

`See Getting Started .`

## Expected behavior

No blank space 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by petebacondarwin** [comment]
A temporary workaround is to put the punctuation inside the link... e.g. ` [Getting Started.](guide/quickstart)`

**Comment by petebacondarwin** [comment]
This is a bug in the libraries we use to render markdown. It is fixed in https://github.com/syntax-tree/mdast-util-to-hast/releases/tag/3.0.1 - specifically this commit - https://github.com/syntax-tree/mdast-util-to-hast/commit/542060405b456c17be51507af62fd05e0ea0bdbd.

I will update our dependencies to grab the latest fixed version.
