### ISSUE TITLE
Local workspace file ('angular.json') could not be found

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#26498]
I am getting this error after adding angular material.

[- ] Bug report  

![image](https://user-images.githubusercontent.com/23274631/47065294-19d4a780-d200-11e8-87be-ded1119c5c6f.png)

![image](https://user-images.githubusercontent.com/23274631/47065307-278a2d00-d200-11e8-8d03-2efaa4084e95.png)

![image](https://user-images.githubusercontent.com/23274631/47065321-37097600-d200-11e8-8128-938030ca1673.png)

![image](https://user-images.githubusercontent.com/23274631/47065367-5accbc00-d200-11e8-8b0f-340df99d7810.png)

![image](https://user-images.githubusercontent.com/23274631/47065526-eb0b0100-d200-11e8-83df-09ecc5cce796.png)

Windows 10

Thank you!

**Comment by pkozlowski-opensource** [comment]
Please open in https://github.com/angular/angular-cli for initial investigations
