### ISSUE TITLE
Input tag with ngModel --> while entering text, we are facing extremely slow responsive in ui. 

### ISSUE THREAD

**Issue by harshabada** [angular/angular#26499]
## Current behavior
the input tag in a big applications is sluggish/extemely slow 

## Expected behavior
should be responsive while entering input

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gitter-2syq3t

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
