### ISSUE TITLE
Directive class selector tslint error

### ISSUE THREAD

**Issue by miikaeru** [angular/angular#26490]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When using a class selector in a directive tslint is showing an error. According the [Angular documentation](https://angular.io/api/core/Directive#selector) using a class selector should be allright. My definition is (It's working fine) :

![image](https://user-images.githubusercontent.com/28813834/47046696-0bea3c80-d196-11e8-8b31-b0a81efed0ef.png)

## Expected behavior

Tslint error shouldn't be shown.

## Minimal reproduction of the problem with instructions

Use a class as a directive selector

```ts
@Directive({
  selector: '.form-control'
})
```

## What is the motivation / use case for changing the behavior?

Commenting our or disable the tslint rule shouldn't be the way to go

## Environment

<pre><code>
Angular version: 6.1.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by manklu** [comment]
From https://angular.io/guide/styleguide#style-02-06

>Do Use lower camel case for naming the selectors of directives.
Why? Keeps the names of the properties defined in the directives that are bound to the view consistent with the attribute names.
Why? The Angular HTML parser is case sensitive and recognizes lower camel case.

**Comment by IgorMinar** [comment]
While Angular does support class selectors for directives, this feature should be used only in special circumstances because it makes it hard to understand which parts of the template are regular classes and which are directives. This is why this syntax is tslint warning and not a compilation error.

If you insist on using this selector style, you can change the tslint config, or prefix the callsite in the code with tslint ignore comment, but you'll make your life and other's life easier if you stick to attribute selectors instead.

**Comment by manklu** [comment]
@IgorMinar The link in the warning should then point to a correct explanation.

**Comment by trotyl** [comment]
@manklu Feel free to make a request to https://github.com/mgechev/codelyzer about your suggested message, but which is unrelated to this repo.
