### ISSUE TITLE
disallow setters for non-existing properties on contexts

### ISSUE THREAD

**Issue by rkirov** [angular/angular#265]
Consider a component `Cmp` that does not have a prop `foo` set. If in its template we have
```<div on-click="foo = 3"></div>```
the expression evaluation should throw when clicked. This would force the component authors to explicitly declare all properties they plan to use. This would benefit hidden-class optimizations in JS engines. Also brings parity with locals which do not allow for extending with non-declared keys.

**Comment by mhevery** [comment]
I understand that this will create different behavior from JS, but I think in this case we are actually benefiting the user by being helpful. We already deviate with JS because we do null suppression, without no property error this will be hard to use. I vote for throwing.

**Comment by vicb** [comment]
Not really sure if we should throw:

```
class TSClass {
  myProp: string;
}

{{ tsClass.myProp }} // it would be weird to throw although the property is declared 
```

**Comment by tbosch** [comment]
I think we can check for this case via 'myProp in tsClass'...

**Comment by vicb** [comment]
Doesn't seem like

```ts
class TSClass {
	prop: number;
}

var tsClass = new TSClass();

// transpiles to 

var TSClass = (function () {
    function TSClass() {
    }
    return TSClass;
})();
var tsClass = new TSClass();

```

**Comment by mhevery** [comment]
obsolete. The generated code with TS now has proper types, and the compilation will fail.
