### ISSUE TITLE
example(router): add simple example app

### ISSUE THREAD

**Issue by btford** [angular/angular#2650]
@IgorMinar is going to take over this branch @matsko started to add a simple app + E2E tests with the router.

* https://github.com/matsko/angular/tree/routing_tests

**Comment by matsko** [comment]
Sounds good.

**Comment by naomiblack** [comment]
Igor should have something by July 4.

**Comment by btford** [comment]
Moving this to alpha-31 since this doesn't directly affect the release

**Comment by btford** [comment]
I don't think this is actually in yet since we had to revert the commit.

**Comment by matsko** [comment]
I'm going to continue working on this today.
