### ISSUE TITLE
FetchEvent.respondWith received an error: TypeError: Internal error (WebKitServiceWorker: 0)

### ISSUE THREAD

**Issue by zgabievi** [angular/angular#26500]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

On Safari, if you have service worker registered, when you "Empty Cache" and refresh page, you get an error:

![image](https://user-images.githubusercontent.com/1515299/47070231-dd09b000-d201-11e8-9e90-2a9bd335a7d3.png)

## Expected behavior

There should be polyfill that fixes this error.

## Minimal reproduction of the problem with instructions

* Register service worker on project
* Open in safari
* Empty cache
* Refresh page

## What is the motivation / use case for changing the behavior?

To make service worker workable in Safari

## Environment

<pre><code>
Angular version: 6.1.9

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version 12.0
- [x] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.10.0  
- Platform:  Mac 

Others:

</code></pre>

**Comment by gkalpak** [comment]
I am not sure what the exact problem is, but it has hopefully been fixed by #26042.
It is included in 7.0.0-beta.7+, but not in 6.x yet (not sure if there is going to be another 6.x release).

Closing this as "fixed", but feel free to open a new issue if you try with the latest version and it is still a problem.

**Comment by NourasHamwi** [comment]
I am having the same error.

**Comment by NourasHamwi** [comment]
I am having the same problem, I am not able to access angular.io from Safari 12.0, but when entering responsive mode, the website works.
