### ISSUE TITLE
Property not being reevaluated on Edge and IE11

### ISSUE THREAD

**Issue by JackPanzer** [angular/angular#26503]
## I'm submitting a...

[x] Bug report
[  ] Performance issue
[  ] Feature request
[  ] Documentation issue or request

## Current behavior
Using a reactive form, to show the validation messages I check if the input form has the states dirty and invalid. If that condition checks, I start iterating through the validation errors and input them. In the current scenario, regardless the state of the input, it doesn't show anything.

## Expected behavior
Under the field there should be a message with the detected errors.

## Minimal reproduction of the problem with instructions
Html template chunk

```HTML
<div>
   <input 
      type="text" 
      placeholder="E.g., User" 
      aria-labelledby="firstname-label" 
      aria-describedby="firstname-error"  
      name="firstName"                                                                        
      id="firstName"
      formControlName="firstName"
      />
</div>
   <div [style.visibility]="(userInfoForm.get('firstName').dirty && userInfoForm.get('firstName').invalid) ? 'unset' : 'hidden'" class="field-error" role="alert" id="name-error">
   {{ (userInfoForm.get('firstName').hasError('required')) ? 'The name is required' : '' }}
   {{ (userInfoForm.get('firstName').hasError('minlength')) ? 'The name is not valid' : '' }}
   </div>
</div>
```

Component TS chunk
```TypeScript
@Component({
    selector: 'ss-register-user',
    templateUrl: 'register-user.component.html',
    styleUrls: ['register-user.component.scss']
})
export class RegisterUserComponent {

userInfo: RegisterUserModel; // A basic object with a firstName field
userInfoForm: FormGroup;

constructor( ) {
        this.userInfo = new RegisterUserModel();
        this.userInfoForm = this.fb.group({
            firstName: new FormControl(this.userInfo.firstName,
                    {validators: [Validators.required, Validators.minLength(2)], updateOn: 'blur'})
        });
    }
}
```

## Environment

Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [x] Edge version 41
 
For Tooling issues:
- Node version: 8.12.0
- Platform:  Windows 10 Pro 10.0.16299

**Comment by manklu** [comment]
Seems tha Edge doesn't like ```visibility:unset;```

No Angular problem.

**Comment by JackPanzer** [comment]
The thing is that it stays in hidden, it is not changing the value of the property

**Comment by manklu** [comment]
It doesn't stay hidden if you use visible instead of unset.

**Comment by JackPanzer** [comment]
I get what you say, but what I'm trying to say is that the property never changes from hidden to unset, is not about seeying it or not, is that the property value is not changing

**Comment by trotyl** [comment]
Please make a minimal reproduction in https://stackblitz.com/, and remove anything irrelevant.

**Comment by JackPanzer** [comment]
Hello! Excuse me for the delayed answer :)

I managed to isolate it with stackblitz (didn't know about that tool, it came really handy :D) and you can see it here:

https://angular-ec3n7x.stackblitz.io

The thing is, using hidden instead of style.visibility seems to work, so I don't know if this will be an issue with the style property with Edge and IE11, so as a workaround I can use the hidden property instead of the style.visibility, but I found that behaviour kind of weird.

**Comment by mhevery** [comment]
Need reproduction steps. What do I click on what should happen, what actually does happen.

**Comment by manklu** [comment]
@mhevery Edit Link: https://stackblitz.com/edit/angular-ec3n7x

**Comment by JoostK** [comment]
Closing as IE and non-Chromium Edge are no longer supported.
