### ISSUE TITLE
"Out of stack space" errors with routing in Edge extension popup

### ISSUE THREAD

**Issue by kspearrin** [angular/angular#26508]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When trying to use routing in an Angular app that is loaded as an Edge extension popup, Edge throws "Out of stack space" errors.

```
ERROR Error: Uncaught (in promise): Error: Out of stack space
Error: Out of stack space
   at defaultErrorHandler (ms-browser-extension://MSG_extName___498F3425FF2D46BA888ED109828A066C/popup/vendor.js:34752:5)
   at Anonymous function (ms-browser-extension://MSG_extName___498F3425FF2D46BA888ED109828A066C/popup/vendor.js:35330:21)
   at ZoneDelegate.prototype.invoke (ms-browser-extension://MSG_extName___498F3425FF2D46BA888ED109828A066C/popup/vendor.js:69892:13)
   at onInvoke (ms-browser-extension://MSG_extName___498F3425FF2D46BA888ED109828A066C/popup/vendor.js:4129:17)
   at ZoneDelegate.prototype.invoke (ms-browser-extension://MSG_extName___498F3425FF2D46BA888ED109828A066C/popup/vendor.js:69892:13)
   at Zone.prototype.run (ms-browser-extension://MSG_extName___498F3425FF2D46BA888ED109828A066C/popup/vendor.js:69644:17)
   at Anonymous function (ms-browser-extension://MSG_extName___498F3425FF2D46BA888ED109828A066C/popup/vendor.js:70378:17)
   at ZoneDelegate.prototype.invokeTask (ms-browser-extension://MSG_ext
```

It the app just loads a simple component without any routing, there is no error.

This problem did not start until the latest Windows 1809 update with Edge 44, so it would seem to me that it is a regression in Edge itself. There is an open issue reported on the edge issue tracker [here](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19075248/) (additional context and history can be read from that reported issue).

I am opening the issue here in hopes that there is possibly some workaround that can be discovered or developed to deal with this problem so that Angular is still usable in this environment. Right now this has completely broken our Edge extension for users and I am not hopeful that Microsoft will fix the problem any time soon (if ever). I am not familiar with the inner-workings of Angular so I am not sure what would be the cause of this problem. I have only observed that it has to do with routing.

## Expected behavior
Routing works without errors.

## Minimal reproduction of the problem with instructions
Here is a reproduction using the tour of heroes tutorial app adapted to build as a browser extension:

[edge-ext-angular-bug.zip](https://github.com/angular/angular/files/2487399/edge-ext-angular-bug.zip)

```
npm i
npm run build
```

Then side load the `./dist` directory in Edge as an extension (you'll need to configure your machine for windows development mode and turn on extension development at `about:flags` in Edge).

Open the popup and observe the error in dev tools.

You could also observe this with our official extension app, which can be pulled and built from our repo here: https://github.com/bitwarden/browser

## What is the motivation / use case for changing the behavior?
So that one can use Angular to develop web extensions for Edge.

## Environment

<pre><code>
Angular version: 6.1.7

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 44.17763.1.0
 
For Tooling issues:
- Node version: 10
- Platform:  Windows 10

Others:

</code></pre>

**Comment by mhevery** [comment]
We much prefer https://stackblitz.com/edit/angular-example-repro Could you make our life easier by moving the repro there.

**Comment by kspearrin** [comment]
@mhevery This issue is only reproducible as an Edge extension. Stackblitz won't work or that.

**Comment by alokdida** [comment]
I am also facing the same issue. Does anyone know? My application is working fine perfectly but whenever I am trying some sample code in stackblitz. it's giving me same error. It's happening with edge browser only.

**Comment by merijndejonge** [comment]
Any news? My angular-based browser extension stopped to work on Edge because of this issue.

**Comment by ruffy91** [comment]
News are that Microsoft is abandoning EdgeHTML in favor of chromium. Don't expect them to fix any more bugs in Edge based on EdgeHTML.

**Comment by merijndejonge** [comment]
Thanks, I was afraid for that.
Is there a known workaround, such that I can get my extension to work again. Customers are complaining :-(

**Comment by merijndejonge** [comment]
@kspearrin a.o. did you consider implementing an alternative router to replace the default Angular one for your browser extension?
As navigation in a browser extension is relatively straight-forward (no back/forward button, no address bar...), I created my own simple router + outlet for my browser extension. I managed to keep the API the same/similar as in angular. This works perfectly in Edge (and chrome).
I'm not sure if you need any of the advanced features of the router.
If you're interested I can send you the code.

**Comment by SonofNun15** [comment]
We have a client running into the same issue with Edge 44. Would be interested in seeing your workaround @merijndejonge. We may encourage this client to install Edge based on chromium in the meantime...

**Comment by jelbourn** [comment]
Closing old Edge-related issues since any such issues have likely been resolved in the newer Chromium-based Edge.
