### ISSUE TITLE
Angular docs: Suggest es7/array polyfill for hash-based routing

### ISSUE THREAD

**Issue by rmorrise** [angular/angular#26511]
## I'm submitting a...

<pre><code>
[x] Documentation issue or request
</code></pre>

## Current behavior

Using hash-based routing strategy in IE11, angular throws an error:
<code>IE11 - Object doesn't support property or method 'includes' - javascript window.location.hash</code>

The solution is to add the <code>es7/array</code> polyfill to <code>polyfills.ts</code>:
https://stackoverflow.com/a/52630710/166850

## Expected behavior

Please add this polyfill to the table of polyfills in the Angular documentation.

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [ ] Edge version XX
 
Others:

</code></pre>

**Comment by jenniferfell** [comment]
https://angular.io/guide/browser-support#suggested-polyfills
