### ISSUE TITLE
move dev-time serving out of deployment guide

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#26527]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

https://next.angular.io/guide/deployment contains a section called "Development servers".

## Expected behavior

We want to use deployment to mean...well...deployment. 
This content is about development-time serving, not deployment. 
Move to build.md with other content about serving (ng serve)

## What is the motivation / use case for changing the behavior?

Clarify the dev-deployment lifecycle content. 
This came up in a docs review with @IgorMinar 
All of deployment probably needs a rewrite, but this content in particular needs to move to build-serving guide. 

Original CLI wiki source: https://github.com/angular/angular-cli/wiki/stories-disk-serve

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
Removal by Igor in this PR: https://github.com/angular/angular/pull/26486

Need to add content back into doc set.

**Comment by elbaumpj** [comment]
@jenniferfell is the rest of this issue actionable? If so, I'd like to handle putting that content back into the appropriate place.

**Comment by josephperrott** [comment]
Closing as this content has already been updated/migrated in previous work.
