### ISSUE TITLE
Dynamical Input Inside Table with (blur) run mutiple times.

### ISSUE THREAD

**Issue by renanpaiva64** [angular/angular#26526]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The code inside event function run multiple times.

## Expected behavior

The code should run just one time.

## Minimal reproduction of the problem with instructions

To reproduce this issue please use the code bellow, change the value after change input copple times.

access: https://stackblitz.com/edit/angular-rpumgc

or use the code

```
<form [formGroup]="tableForm">
	<table class="shop-table table-responsive" cellspacing="0">
		<tbody formArrayName="arr">
			<tr class="cart_item" *ngFor="let a of this.tableForm.get('arr')['controls']; let i= index;">
				<td class="product-quantity" [formGroupName]="i">
					<div class="quantity buttons_added">
						<input type="number" formControlName="variant_sku" (blur)="teste($event)">
            <p *ngIf="a.hasError('required', 'variant_sku')">Required!</p>
					</div>
				</td>
			</tr>
		</tbody>
	</table>
</form>

import { Component } from '@angular/core';
import { FormGroup, FormBuilder, FormControl, Validators, FormArray } from '@angular/forms';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  tableForm: FormGroup;

  final_selected_data = [{ variant_sku: '' }, { variant_sku: '' }]

  constructor(private fb: FormBuilder) {

  }
  ngOnInit() {
    this.tableForm = this.fb.group({
      arr: this.fb.array([])
    })
    let arr = this.tableForm.get('arr') as FormArray;
    for (let i = 0; i < this.final_selected_data.length; i++) {
      arr.push(this.fb.group({
        variant_sku: [this.final_selected_data[i].variant_sku, [Validators.required]]
      }))
    }
  }

  teste(event: any): void{
    alert(event.target.valueAsNumber);
  }
}
```

## Environment

<pre><code>
Angular version: 6.2.3

Browser:
- [x] Chrome (desktop) version  69.0.3497.100 (Versão oficial) 64 bits
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
Anything works well in your repro, except for using `alert` which will got focus for itself and blur any other controls.

Could you explain what the problem is using `console.log`?

https://stackblitz.com/edit/angular-qdkcuq?file=src/app/app.component.ts

**Comment by mhevery** [comment]
Please provide simpler repro and use https://stackblitz.com/edit/angular-example-repro as an example

**Comment by pkozlowski-opensource** [comment]
Going to close this now as we haven't heard back with a valid reproduce scenario.
