### ISSUE TITLE
ngClass not working with Optimization: true in angular.json after ng build --prod.

### ISSUE THREAD

**Issue by nitin1982** [angular/angular#26528]
I have a requirement where I apply a class based on navigation.
I apply fixedFooter class only when I am on HomeComponent.

I have checked in the code at below git hub repository.
[https://stackblitz.com/github/nitin1982/FinanceApp](https://stackblitz.com/github/nitin1982/FinanceApp)
[https://github.com/nitin1982/FinanceApp](https://github.com/nitin1982/FinanceApp)

See the code in [app.component.ts](https://github.com/nitin1982/FinanceApp/blob/master/src/app/app.component.ts) class and ngOnInit event. I am setting the flag **fixedFooterFlag** true only when the activated component is Home Component.

<div>
  <footer class="container-fluid text-center bg-primary" [ngClass]="{'fixedFooter': fixedFooterFlag}">
    <span class="align-middle">Developed by ABC Development Team - Version 1.0
    </span>
  </footer>
</div>

This code(ngClass) does not work in the the deployed code or after **ng build --configuration=production**

If I turn off the Optimization in the angular.json for production, it works.

Any suggestions?

Thanks,
Nitin

**Comment by SandyVeliz** [comment]
Im having the same issue with the 6.2.5 v

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/26520

**Comment by trotyl** [comment]
Your production is completely unrelated to `NgClass`:

```typescript
switch(componentName){
  case "HomeComponent":
    this.fixedFooterFlag = true;          
    break;
  default:
    this.fixedFooterFlag = false;
    break;
}
```

You cannot depend on `Function.name` at runtime, which is not an Angular issue.

**Comment by nitin1982** [comment]
I got it, thanks.
