### ISSUE TITLE
What is name database can connect with angular 6 ?

### ISSUE THREAD

**Issue by Omar-Qalei** [angular/angular#26535]
What is name database can connect with angular 6 ?
I wanna database can use with angular 6 such as Mongodb instead of Firebase .
Can I see all types of database support for angular 6 ?
My propose queries work such as MySQL.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Omar-Qalei** [comment]
Ok sorry.
