### ISSUE TITLE
Public API Docs - API surface needs curation

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#2653]
We need to explicitly specify what we export form core, annotations, and render. Similar to https://github.com/angular/angular/pull/2652

**Comment by DavidSouther** [comment]
@vsavkin I'd be down to take a crack at this. This would be https://github.com/angular/angular/pull/2652/files#diff-d4a8211f46ad807ad291e3938805df66L2 , 3 and 4, right?

**Comment by mhevery** [comment]
I believe we have refactored the code so that this Issue is satisfied. closing.
