### ISSUE TITLE
Problems on your front website

### ISSUE THREAD

**Issue by BaptisteKeetiz** [angular/angular#26536]
Hello angular teams, we were on your website with a colegue and we've noticed that the Angular logo is not well placed on your topbar, a little bit too much on the left.

we have also noticed that this problem is resolved when we pass your the margin of the element 
.nav-link.home
from
margin : 0 16px 0 0

![image](https://user-images.githubusercontent.com/42996485/47155115-5c6fb000-d2e4-11e8-9645-5d3f287830a3.png)

![image](https://user-images.githubusercontent.com/42996485/47155362-d43dda80-d2e4-11e8-8f10-bb091d3b148b.png)

to 
margin: 0 16px 0

![image](https://user-images.githubusercontent.com/42996485/47155514-30a0fa00-d2e5-11e8-92fb-066259105ec1.png)

![image](https://user-images.githubusercontent.com/42996485/47155488-21ba4780-d2e5-11e8-89d8-9a292a8b9c2f.png)

hope this helps your developper team 

Regards
Baptiste Valette

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/26468

**Comment by gkalpak** [comment]
Thx for reporting this issue, @BaptisteKeetiz.
This has already been fixed with #26473 and should be deployed to the stble version soon.
