### ISSUE TITLE
Accept-Language header ignored on Chrome

### ISSUE THREAD

**Issue by mkp05** [angular/angular#26534]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
On Chrome no matter what value was put in HTTP request interceptor in "Accept-Language" header always value from browser settings is set.
On Firefox or IE everything works as intended (value set in interceptor i passed to the server).

## Expected behavior
Value set in interceptor is passed to the server.

## Minimal reproduction of the problem with instructions
Sample code in here - https://plnkr.co/edit/hB3biPPvGXNwIsqe9nP2 (it's on Angular 5, but future versions are also affected)

1. Open and run plunker
1. Monitor HTTP requests with any tool
1. Click "fetch people"
1. Observe "Accept-Language" header in request

## What is the motivation / use case for changing the behavior?
With multilanguage application would be nice to adjust Accept-Language header to language selected in application without need to reconfigure browser settings.

## Environment
<pre><code>
Angular version: 5.2.10 and later (not verified on previous)

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.10.0
- Platform:  Windows

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
You can't control this header programmatically: 

> Browsers set adequate values for this header according to their user interface language

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language

This is the default browser behaviour, nothing that JS / Angular can control or do about.
