### ISSUE TITLE
docs: in cli command reference, improve how long description is presented

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#26556]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Long description appears at the end of the page. 
There is no right side TOC entry.
One user has described it as "footnotes". Indeed, it looks a bit lost. 
Long description usually has important information about usage, not footnote or corner cases. 

## Expected behavior

Some options:
* Add "Usage notes" as a heading before this long description. Add heading to right TOC.
* Move long description up immediately below syntax, so it's integrated into the area with the short description and syntax, before the tables of options and arguments. 
* Others?

## Minimal reproduction of the problem with instructions

https://angular.io/cli/add
![cli-add-longdesc](https://user-images.githubusercontent.com/31675481/47183958-9cd02d80-d2e6-11e8-84cd-1042037e6f82.png)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by petebacondarwin** [comment]
I will await the decision on what to do here. My preference would be for moving this "long description/usage notes" to directly below the syntax.
