### ISSUE TITLE
npm latest is advanced then next

### ISSUE THREAD

**Issue by richlim** [angular/angular#26565]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ x] Other... Please describe: npm issue
</code></pre>

## Current behavior

npm info @angular/core yields:
latest: 7.0.0     next: 7.0.0-rc.1  v4-lts: 4.4.7     v5-lts: 5.2.11    

## Expected behavior

next should be advanced then latest

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by IgorMinar** [comment]
I've updated the tags. thanks
