### ISSUE TITLE
docs: ng build options are not all relevant for library

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#26569]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
At the moment, only a small subset of the options listed in https://angular.io/cli/build are available to be used when targeting a library project. 

While it is the same command `ng build` for libraries and application are two different builders, and thus 2 separate schemas and descriptions

**Library builder**
https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_ng_packagr/src/build/schema.json

**Application builder**
https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/browser/schema.json

## Expected behavior
We should make it clear to the users which options can be used in applications and which in libraries projects, so that we avoid users opening issues that certain options are not working or have no effect when targeting a library.

**Comment by woppa684** [comment]
Will these options for libraries also be extended? For example the "--outputPath" would be very nice, since we have to write all intermediate build output to some dynamic folder in our organisation and the current builder for libraries does not allow that ...

**Comment by mistic100** [comment]
In the same topic, please allow deleteOutputPath=false for libraries. Whith current behaviour it is extremely complicated to have librairies automatically building along the application when developing.
