### ISSUE TITLE
Update guide on update.angular.io shows info for 5 -> 6 update instead of 6 -> 7

### ISSUE THREAD

**Issue by wilgert** [angular/angular#26566]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The update guide on update.angular.io shows information about updating from 5 to 6 when selecting 6(.1) and 7.

## Expected behavior

The update guide shows info on updating from 6(.1) to 7.

## Minimal reproduction of the problem with instructions

1. Go to https://update.angular.io/
2. select Version 6 or 6.1 in the first dropdown and 7.0 in the second.
3. Click Show me how to update!
4. See that the info is outdated.

## What is the motivation / use case for changing the behavior?
I want to know how to upgrade.

**Comment by sarunint** [comment]
I think the instruction is correct. Could you elaborate more on this issue?

cc @StephenFluin

**Comment by wilgert** [comment]
It looks like it is correct now.
Maybe I was mistaken but I think I saw instructions on changing Http to HttpClient and other instructions that would apply to 5 -> 6 or 7 update.
Currently this line `rxjs-5-to-6-migrate -p src/tsconfig.app.json` is still a bit confusing because Angular 6 already uses RxJS 6.

**Comment by StephenFluin** [comment]
@wilgert That line is there because v6 still supports the rxjs-compat package, so developers may not have updated yet, this is to make sure they update before moving to 7.
