### ISSUE TITLE
v7 release announcement link in 7.0.0/CHANGELOG.md

### ISSUE THREAD

**Issue by SvenAtGit** [angular/angular#26564]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When i navigate on the link  **v7 release announcement** in the aricle [https://github.com/angular/angular/blob/7.0.0/CHANGELOG.md](https://github.com/angular/angular/blob/7.0.0/CHANGELOG.md)  i don't expect a 404 TODO message

## Expected behavior

A overview of the v7 release announcement

## Minimal reproduction of the problem with instructions
Navigate on the link

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [x ] Chrome (Android) version XX
- [x ] Chrome (iOS) version XX
- [x ] Firefox version XX
- [x ] Safari (desktop) version XX
- [x ] Safari (iOS) version XX
- [x ] IE version XX
- [x ] Edge version XX
 

Others:

</code></pre>

**Comment by gkalpak** [comment]
It is indeed fixed on master. We should fix it on 7.0.0 too, by backporting 72c2578d1 and 331989cea.

**Comment by sarunint** [comment]
Oh, right.

**Comment by gkalpak** [comment]
(For reference, fixed in 6c4845515.)
