### ISSUE TITLE
second compile time is too long after upgrade to 7.0

### ISSUE THREAD

**Issue by alialtun14** [angular/angular#26572]
[x] Bug report

## Current behavior
First compile: 26337 ms   
compiling after addding an empty line to any ts file.. 
Second compile time: 77672 ms  
Third compile time: 75357 ms  

First compile

<pre><code>
PS E:\Qlass>  ng serve
** Angular Live Development Server is listening on localhost:4200..
Date: 2018-10-19T07:17:47.954Z
Hash: 9e17bb481bfa5db35b04
Time: 26337ms
chunk {main} main.js, main.js.map (main) 1.91 MB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 248 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 116 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 6.94 MB [initial] [rendered]
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
</code></pre>

Second compile  
<pre><code>
Date: 2018-10-19T07:19:25.629Z - Hash: 9e17bb481bfa5db35b04 - Time: 77672ms
5 unchanged chunks
i ｢wdm｣: Compiled successfully.
</code></pre>

## Expected behavior
Second compile time must be below 1 second.  But It takes 3 times longer than first compile.
There is no problem when compiling with angular 6.1

## Environment

Angular version: 7.0

Browser:
- [x] Chrome (desktop) version XX
 
For Tooling issues:
- Node version: 10.12
- Platform:  Windows 10 Pro

Others:

<pre><code>
package.json
{
  "name": "qlass7",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "ngs": "node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "bundle-report": "webpack-bundle-analyzer _qdist/stats.json"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.0.0",
    "@angular/cdk": "^7.0.0",
    "@angular/cli": "^7.0.1",
    "@angular/common": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@angular/forms": "^7.0.0",
    "@angular/material": "^7.0.0",
    "@angular/platform-browser": "^7.0.0",
    "@angular/platform-browser-dynamic": "^7.0.0",
    "@angular/router": "^7.0.0",
    "core-js": "^2.5.4",
    "font-awesome": "^4.7.0",
    "intl": "^1.2.5",
    "rxjs": "^6.3.3",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.8.1",
    "@angular-devkit/build-optimizer": "^0.8.1",
    "@angular/compiler": "^7.0.0",
    "@angular/compiler-cli": "^7.0.0",
    "@types/angular": "^1.6.50",
    "@types/angular-route": "^1.3.5",
    "typescript": "^3.1.3"
  }
}
</code></pre>

**Comment by alialtun14** [comment]
There is no failure , the second ve following builds take a very long time to complete its stuck at
10% building modules 0/55 modules 55 active ....js!E:\Qlass\src\app\ausel\yuser_exp.ts
and I have to wait for 80 second to get the build completed.

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/21361

**Comment by alialtun14** [comment]
I thinks this isn't duplicate of #21361. Because yesterday I haven't any issue when using angular 6.1. After upgrading to angular 7.0 I have met this compile time problem.

**Comment by alialtun14** [comment]
after 
npm install @angular-devkit/build-angular
npm install @angular-devkit/build-optimizer

everything is okey.
