### ISSUE TITLE
Scrolling by clicking mouse wheel doesn't scroll to the top of the list in Virtual scrolling

### ISSUE THREAD

**Issue by mishotek** [angular/angular#26571]
## Current behavior
When clicking a mouse wheel in the virtual scroll in [example](https://material.angular.io/cdk/scrolling/overview) and scrolling down with it, it scrolls to an end as it's supposed to, but when scrolling up it scrolls just by a chunk and then stops instead of rendering a new chunk of items.

## Expected behavior
Scrolling by clicking mouse wheel and dragging the cursor to the top should make list scroll to the top, even if more chunks have to be rendered.

## Minimal reproduction of the problem with instructions
Scroll down by rotating a mouse wheel, then inside of the virtual scroll component click a mouse wheel and drag it to the top to start scrolling in that direction. After scrolling some items, the scroll will stop event tho it hasn't reached the top of the list.

## What is the motivation / use case for changing the behavior?
The current behavior is unexpected. Especially when it is possible to scroll down by clicking a mouse wheel, but impossible to scroll down.

## Environment
I caught this bug in an official example on [Angular material website](https://material.angular.io/cdk/scrolling/overview)

Browser:
Chrome (desktop) Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by pkozlowski-opensource** [comment]
Please open in https://github.com/angular/material2

**Comment by skreborn** [comment]
@mishotek When you move the issue, please mention that it also happens in a downwards direction, **but it takes significantly longer**. Doesn't happen in Firefox whatsoever as far as I can tell.
