### ISSUE TITLE
docs: list of deprecated APIs

### ISSUE THREAD

**Issue by sarunint** [angular/angular#26585]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

There are many APIs that are deprecated long ago but not removed yet. For example, `@angular/http` and `DeprecatedI18NPipesModule` is deprecated as of v5. Or `ViewEncapsulation.Native` is deprecated as of v6.1. But there isn't a way to know things which is deprecated other than going to the page.

## Expected behavior

I'd like to have a page which shows deprecated APIs so that developers can avoid using them.

## Minimal reproduction of the problem with instructions

N/A

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>
My mental image of what could this look like:
![image](https://user-images.githubusercontent.com/3850197/47214090-19d2d400-d3c7-11e8-9b40-4923313ade63.png)

**Comment by IgorMinar** [comment]
This is the current list: https://angular.io/api?status=deprecated

We should create a table like the one you suggested though.

**Comment by jenniferfell** [comment]
I started a Google doc over the summer, with the intent to move to .md and submit to aio doc set. Will resume now that v7 work is complete. Thanks for letting know this will be useful.

**Comment by jenniferfell** [comment]
Immediate workaround: Go to API List and filter by status: deprecated.

**Comment by gkalpak** [comment]
We now have a dedecated page for deprecated APIs/features: https://angular.io/guide/deprecations
Closing...
