### ISSUE TITLE
Router - Paste URL with params in navigation-bar not working anymore in 7.0 

### ISSUE THREAD

**Issue by Knacktus** [angular/angular#26582]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior
Pasting an URL with params into the Navbar (e.g. http://localhost:4200/connect/123/123 where 123/123 are the params) is not working any more. 

Looks like Angular doesn't interpret the route correctly anymore? Angular seems to treat connect as the base url.

Error Messages:

<pre><code>
Loading failed for the <script> with source “http://localhost:4200/connect/123/runtime.js”. 123:15:1
Loading failed for the <script> with source “http://localhost:4200/connect/123/polyfills.js”. 123:15:1
Loading failed for the <script> with source “http://localhost:4200/connect/123/styles.js”. 123:15:1
Loading failed for the <script> with source “http://localhost:4200/connect/123/vendor.js”. 123:15:1
Loading failed for the <script> with source “http://localhost:4200/connect/123/main.js”. 123:15:1 
</code></pre>

These are my route definitions (feature module) - the second should be resolved:

<pre><code>
const routes: Routes = [
  {
    path: "connect/:connectProdRevId/:revRule/:asOf",
    canActivate: [ConnectRouteGuardService],
    component: ConnectComponent
  },
  { path: "connect/:connectProdRevId/:revRule", canActivate: [ConnectRouteGuardService], component: ConnectComponent },
  {
    path: "connect",
    component: ConnectProjectChooserComponent,
    children: [{ path: "**", component: ConnectProjectChooserComponent }]
  }
];
</code></pre>

## Expected behavior
Should load the app, navigate to the url and resolve the params.

## Environment

<pre><code>
Angular version: 7.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3
- Platform:  Windows 10

**Comment by RicardoVaranda** [comment]
Hi Knacktus,

Thanks for your report, any chance you could provide us with an example repo showing this behavior?

**Comment by Knacktus** [comment]
I've found the reason ... I've played with Electron the night before upgrading and kept the dot in front of the html base href:

`<base href="./"> // noooo!`
`<base href="/"> // yes!`

Sorry for the false alert. 

Cheers
