### ISSUE TITLE
Extending abstract class

### ISSUE THREAD

**Issue by piernik** [angular/angular#26587]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Component is extenting abstract class that has constructor params.
Those params are not resolved if abstract class does not have `@Component` decorator.
But when in `aot` mode (with @Component decorator in abstract class) angular complains that `Cannot determine the module for class`

## Expected behavior
Should always work with or without decorator

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-3kvqu5?file=src%2Fapp%2Fabstract.ts

## Environment

<pre><code>
Angular version: 7.0.0

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/16566, https://github.com/angular/angular/issues/16637

**Comment by piernik** [comment]
Thanks !

```
@Injectable()   // Injectable for base class 
export abstract class AbstractForm{
 abstract data;
 constructor(protected dialog: DialogService){}
}

@Component({...})    // Component for derived class
export class AbcComponent extends AbstractForm{
 data = {}
}
```
