### ISSUE TITLE
App will not load after version 7, broswer tab is using 100% CPU

### ISSUE THREAD

**Issue by AlQuraian** [angular/angular#26586]
Edit 1:
I think I may know what's the problem. This code that is using Angular Material BreakpointObserver seems to be the cause. It's being called on AppComponent, i.e the first bootstrapped component.
~~I'll try to submit a sample app to reproduce the bug.~~

```ts
 return this.breakpointObserver.observe([Breakpoints.Handset])
    .pipe(map(bp => bp.matches));
```
Edit 2:
I added the way to reproduce the issue, should create an issue in the Angular Material repo? 

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The app does not load, I see a few http calls pending but not completing! The browser tab is using 100% CPU. I have faced this on beta and RC.
I even compiled the app and served the production build with the same issue. Angular 6 works fine.
I also removed some dependencies and all APP_INITIALIZER with no luck.

## Expected behavior

App loads

## Minimal reproduction of the problem with instructions

- Create a new Angular 7 App
- ng add @angular/material
- Add the following getter in the AppComponent:
```ts
constructor(private breakpointObserver: BreakpointObserver) {}

get height(): Observable<number> {
    return this.breakpointObserver.observe([Breakpoints.Handset])
      .pipe(map(bp => bp.matches ? 100 : 50));
  }
```
- Add the following to an element in the AppComponent template:
```
[style.minHeight.px]="height | async"
```

~~Unfortunately I don't know how to reproduce the issue. I was hoping that someone might have had the same issue and has a clue of what's wrong.~~

## Environment

<pre><code>
Angular version: 7.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: v10.12.0
- Platform:  Windows
</code></pre>

**Comment by markpeterfejes** [comment]
I'm experiencing the same problem, will try to come up with a repro code, but the only thing I get in the devTools is a warning.

`platform-browser.js:612 Throttling history state changes to prevent the browser from hanging.`

I'm also using ngrx, with the router-store which may cause, but I haven't tested it yet.

**Comment by hakimio** [comment]
Some [CI tests](https://circleci.com/gh/angular/angular/89772) related to routing seem to be failing as well.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
