### ISSUE TITLE
docs: code example styles not conforming to docs style guide

### ISSUE THREAD

**Issue by preethamvishy** [angular/angular#26581]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

> For terminal input and output, put the content between `<code-example>` tags, set the CSS class to `code-shell`, and set the language attribute to `sh` 

Multiple code examples do not conform to this guide.

## Expected behavior

`<code-example language="sh" class="code-shell">` should be used for all code examples.

**Comment by ajitsinghkaler** [comment]
@gkalpak @kapunahelewong I think this can be closed

**Comment by gkalpak** [comment]
@ajitsinghkaler, why do think this can be closed?

**Comment by ajitsinghkaler** [comment]
@gkalpak a lot of changes have been made on the platform after this I don't think this is applicable on current platform

**Comment by gkalpak** [comment]
Hm...I am not sure what you mean by "platform" (😅), but I did a quick search and I couldn't find any specific code-snippets that are missing the `language="sh"` attribute.

Let's close this, then. If you have specific examples in mind, @preethamvishy, please open a new issue.

**Comment by ajitsinghkaler** [comment]
by platform, I meant the angular.io website
