### ISSUE TITLE
Angular 5.2 Router cancels navigation after getting Observable<boolean> true from canActivate

### ISSUE THREAD

**Issue by HugoJak** [angular/angular#26592]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ x ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have implemented CanActivateGuard that returns either boolean or Observable<boolean>.
When returning boolean true, all works fine. Returning Observable resolved to true leads to GuardsCheckEnd with shouldActivate: true, but jumps to NavigationCancel without any reason. 

## Expected behavior
CanActivateGuard should work the same way no matter if it gets boolean: true or Observable<boolean> true.

## Minimal reproduction of the problem with instructions
 if (returnImmediately) {
      return true;   // Navigation finished OK
 } else {
      return Observable.timer(0).map((t) => {return true;});  // Navigation cancelled !!! 
 }

ROUTER TRACING:
GuardsCheckEnd(id: 9, url: '/requestedUrl(namedOutlet:otherUrl)', urlAfterRedirects: '/requestedUrl(namedOutlet:otherUrl)', state: Route(url:'', path:'') { Route(url:'requestedUrl', path:'requestedUrl'), Route(url:'otherUrl', path:'otherUrl') } , shouldActivate: true)

NavigationCancel(id: 9, url: '/requestedUrl(otherUrl)')

## What is the motivation / use case for changing the behavior?
Confirmable dialog before routing (user has to accept something) before navigation.

## Environment

<pre><code>
Angular version: 5.2.11

Browser:
- [ X ] Chrome (desktop) version latest
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ X ] Firefox version latest
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
