### ISSUE TITLE
Parent annotation (and others) not working in TypeScript

### ISSUE THREAD

**Issue by woppa684** [angular/angular#2660]
I know that there were previous issues about this but I can't find them anymore (the last I saw was 'tracked elsewhere'). I use alpha 27 and the latest d.ts file from the DefinitelyTyped repo. When I try this basic example:

```typescript
/// <reference path="typings/angular2/angular2.d.ts" />
import {Parent, Component, View, bootstrap} from "angular2/angular2";

@Component({
    selector: "c"
})
@View({
    template: `<p>{{app.message}}</p>`
})
class C {
    app: App;
    constructor( @Parent() app: App) {
        this.app = app;
    }
}

@Component({
    selector: "app"
})
@View({
    template: `<c></c>`,
    directives: [C]
})
class App {
    message = "test";
}

bootstrap(App);
```
It always gives me the following error:

```
Cannot resolve all parameters for C(undefined @Parent(self: false})). Make sure they all have valid type or annotations.

Error
    at NoAnnotationError.BaseException (http://localhost:8080/bundle/angular2.js:7248:25)
    at new NoAnnotationError (http://localhost:8080/bundle/angular2.js:10579:63)
    at _extractToken (http://localhost:8080/bundle/angular2.js:22015:13)
    at http://localhost:8080/bundle/angular2.js:21978:14
    at Array.map (native)
    at Function.execute.ListWrapper.map (http://localhost:8080/bundle/angular2.js:7707:26)
    at _dependenciesFor (http://localhost:8080/bundle/angular2.js:21977:24)
    at execute.Binding.resolve (http://localhost:8080/bundle/angular2.js:22108:28)
    at Function.execute.DirectiveBinding.createFromBinding (http://localhost:8080/bundle/angular2.js:25916:30)
    at Function.execute.DirectiveBinding.createFromType (http://localhost:8080/bundle/angular2.js:25951:37)
```
Am I doing anything wrong? If not, is there a workaround for this issue or, where is this issue tracked?

**Comment by 0Decoherence** [comment]
https://github.com/angular/angular/issues/1831

**Comment by woppa684** [comment]
Yes, but where are we tracking it "elsewhere"?

**Comment by jomeier** [comment]
Hm ... I thought it's resolved already.

**Comment by woppa684** [comment]
@vicb That issue is about it not working on the top level component, right? But it also doesn't work on nested components as far as I know (tried that first but this was the minimal example)...

**Comment by vicb** [comment]
Agree, we have two different issues here but once the first one will be resolved (`Cannot resolve all parameters for...`), the code will hit the one I previously referred.

**Comment by mhevery** [comment]
This is a forward declaration issue. In your case `App` is declared later, and so TypeScript does not supply the type information to Angular and hence the error:  `C(undefined @Parent(self: false}))` Which means that angular sees `undefined` for the type. Move the `App` declaration earlier or use https://angular.io/docs/js/latest/api/di/forwardRef-function.html

In a strange way this works as intended. :-( (but I agree that it is not so great of a user experience.)

**Comment by mhevery** [comment]
Closing since it works as intended.

**Comment by woppa684** [comment]
To be sure, the code belows works as intended, but is this the proper way to do it?

'''typescript
/// <reference path="typings/angular2/angular2.d.ts" />
import {Inject, Parent, Component, View, bootstrap, forwardRef} from "angular2/angular2";

@Component({
    selector: "c"
})
@View({
    template: `<p>{{app.message}}</p>`
})
class C {
    app: App;
    constructor( @Parent() @Inject(forwardRef(() => App)) app: App) {
        this.app = app;
    }
}

@Component({
    selector: "app"
})
@View({
    template: `<c></c>`,
    directives: [C]
})
class App {
    message = "test";
}

bootstrap(App);
'''

**Comment by woppa684** [comment]
And this only works when "App" is in the same file / module right? If I have something like this:

```typescript
import {Something} from 'amodule';
...
constructor( @Parent() @Inject(forwardRef(() => Something)) app: Something) {
````

gets compiled to:

```javascript
var angular2_1 = require('angular2/angular2');
var amodule_1 = require('amodule');
...
        __param(0, angular2_1.Parent()),
        __param(0, angular2_1.Inject(angular2_1.forwardRef(function () { return Something; }))), 
        __metadata('design:paramtypes', [amodule_1.Something])
```

and of course then I would get the error:
```
ReferenceError: Something is not defined
```
the forwardRef function here should return amodule_1.Something I guess?
