### ISSUE TITLE
I updated angular / cli 7.0.2 on windows 10 and an error occurred while creating a new project.

### ISSUE THREAD

**Issue by MangoWHL** [angular/angular#26609]
E:\>ng new aaa
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
CREATE aaa/angular.json (3741 bytes)
CREATE aaa/package.json (1310 bytes)
CREATE aaa/README.md (1020 bytes)
CREATE aaa/tsconfig.json (408 bytes)
CREATE aaa/tslint.json (2837 bytes)
CREATE aaa/.editorconfig (245 bytes)
CREATE aaa/.gitignore (503 bytes)
CREATE aaa/src/favicon.ico (5430 bytes)
CREATE aaa/src/index.html (290 bytes)
CREATE aaa/src/main.ts (372 bytes)
CREATE aaa/src/polyfills.ts (3234 bytes)
CREATE aaa/src/test.ts (642 bytes)
CREATE aaa/src/styles.css (80 bytes)
CREATE aaa/src/browserslist (388 bytes)
CREATE aaa/src/karma.conf.js (964 bytes)
CREATE aaa/src/tsconfig.app.json (166 bytes)
CREATE aaa/src/tsconfig.spec.json (256 bytes)
CREATE aaa/src/tslint.json (314 bytes)
CREATE aaa/src/assets/.gitkeep (0 bytes)
CREATE aaa/src/environments/environment.prod.ts (51 bytes)
CREATE aaa/src/environments/environment.ts (662 bytes)
CREATE aaa/src/app/app-routing.module.ts (245 bytes)
CREATE aaa/src/app/app.module.ts (393 bytes)
CREATE aaa/src/app/app.component.html (1173 bytes)
CREATE aaa/src/app/app.component.spec.ts (1086 bytes)
CREATE aaa/src/app/app.component.ts (207 bytes)
CREATE aaa/src/app/app.component.css (0 bytes)
CREATE aaa/e2e/protractor.conf.js (752 bytes)
CREATE aaa/e2e/tsconfig.e2e.json (213 bytes)
CREATE aaa/e2e/src/app.e2e-spec.ts (299 bytes)
CREATE aaa/e2e/src/app.po.ts (208 bytes)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Windows\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by matsko** [comment]
As @jotatoledo mentioned, please follow the issue template and produce a new issue with the proper reproduction steps. Closing for now. Thank you.

**Comment by epena76** [comment]
I'm having the same problem, what can I do.

**Comment by epena76** [comment]
Getting Started - Local Development
Installation
To get started locally, follow these instructions:
If you haven't done it already, make a fork of this repo.
Clone to your local computer using git.
Make sure that you have Node 10.9 or later installed. See instructions here. The Angular CLI requires Node 8, but development requires Node 10.
Make sure that you have yarn installed; see instructions here.
Run yarn (no arguments) from the root of your clone of this project.
Run yarn link to add all custom scripts we use to your global install.

this line help me with this error.
thanks.
