### ISSUE TITLE
build: make it easier to keep npm dependencies in sync between package.json files in repo

### ISSUE THREAD

**Issue by gregmagolan** [angular/angular#26605]
This is reminder issue to find a good way to keep the following package.json files & their yarn.lock files in sync: `/package.json`, `/tools/npm/package.json`, `/integration/bazel/src/package.json`.

This is currently on https://github.com/angular/angular/pull/26488 which will be merged into master shortly.

//cc @alexeagle @IgorMinar

**Comment by jelbourn** [comment]
@gregmagolan is this issue still relevant?

**Comment by alxhub** [comment]
This is no longer relevant.
