### ISSUE TITLE
docs: request to update release schedule after 7.0.0

### ISSUE THREAD

**Issue by preethamvishy** [angular/angular#26617]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

[Release schedule](https://angular.io/guide/releases#support-policy) has 7.0.0 and 8.0.0

## Expected behavior

[Release schedule](https://angular.io/guide/releases#support-policy) should have 8.0.0 and next planned version.

**Comment by jenniferfell** [comment]
https://github.com/angular/angular/pull/26660

**Comment by IgorMinar** [comment]
Fixed
