### ISSUE TITLE
docs: inconsistent syntax highlighting in cli docs

### ISSUE THREAD

**Issue by preethamvishy** [angular/angular#26614]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Note the syntax highlighting of `build` and `version` as compared `add` and `new`
![image](https://user-images.githubusercontent.com/10463855/47253495-ab6f2f80-d421-11e8-848b-730ad5cf3546.png)

![image](https://user-images.githubusercontent.com/10463855/47253501-c8a3fe00-d421-11e8-9cc8-fadb79450ddd.png)

![image](https://user-images.githubusercontent.com/10463855/47253515-ed987100-d421-11e8-841b-504e35e649e0.png)

![image](https://user-images.githubusercontent.com/10463855/47253519-fbe68d00-d421-11e8-8ef8-1dc9f05cb28b.png)

**Comment by textbook** [comment]
In the Angular docs? Where - which pages? Or in the CLI docs, in which case see https://github.com/angular/angular-cli/issues?

**Comment by textbook** [comment]
Links: e.g. [`ng add`](https://angular.io/cli/add), [`ng build`](https://angular.io/cli/build).

**Comment by preethamvishy** [comment]
Thanks, @textbook. I should have included these.

**Comment by jenniferfell** [comment]
Related https://github.com/angular/angular/issues/26657

**Comment by jenniferfell** [comment]
Fixed. CLI doc uses black for command names, never blue.
