### ISSUE TITLE
Angular doesn't load due typo in httpFactory

### ISSUE THREAD

**Issue by Agrumas** [angular/angular#2661]
https://github.com/angular/angular/blob/5b5ffe75d0d1a3ac6204114203d8d566d49e9c70/modules/angular2/src/http/http.ts#L146
Should be:
```javascript
Observable = (<any>Rx).default.Observable;
```

**Comment by gdi2290** [comment]
if you're not using the bundled version of angular then you need to include rx, reflect-metadata, zone.js, and traceur-runtime

**Comment by vicb** [comment]
also see #1798
