### ISSUE TITLE
Page rendered blank with geneated component using cmd - "ng generate @angular/material:material-nav --name=app-nav"

### ISSUE THREAD

**Issue by NLSrikanth** [angular/angular#26610]
## I'm submitting a...

<pre><code>
[ ] Bug report 

## Current behavior
I've generated a component using command - "ng generate @angular/material:material-nav --name=app-nav". Now when I run the app with the page is rendered blank. Following is the default content in app-nav.component.html :

I'm using the latest angular core, material and cdk.

## Expected behavior
Content of sidenav should be displayed properly.

## Minimal reproduction of the problem with instructions

1. Generate a component using cmd - "ng generate @angular/material:material-nav --name=app-nav"
2. use that selector in app.component.html ''.
3. start the app.

## Environment

<pre><code>
Angular version: X.Y.Z
"@angular-devkit/build-angular": "^0.10.1",
"@angular/animations": "^7.0.0",
"@angular/cdk": "^7.0.0",
"@angular/common": "^7.0.0",
"@angular/compiler": "^7.0.0",
"@angular/core": "^7.0.0",
"@angular/flex-layout": "^7.0.0-beta.19",
"@angular/forms": "^7.0.0",
"@angular/http": "^7.0.0",
"@angular/material": "^7.0.0",
"@angular/platform-browser": "^7.0.0",
"@angular/platform-browser-dynamic": "^7.0.0",
"@angular/router": "^7.0.0",
"core-js": "^2.5.4",
"ngx-perfect-scrollbar": "^6.3.1",
"rxjs": "^6.0.0",
"zone.js": "^0.8.26"

Browser:
- [ ] Chrome (desktop) version 69.0.3497.100
- [ ] Firefox version 62.0.3
 
For Tooling issues:
- Node version: v8.11.3
- Platform:  Windows

Others:
No error reported on console. Compilation is successful.

**Comment by NLSrikanth** [comment]
Another observation:

When I replace the default content of 'app-nav.component.html' with simple html paragraph code then it's rendering the content properly. Seems like the issue is with the code generated by default.

**Comment by matsko** [comment]
@NLSrikanth please add this into https://github.com/angular/angular-cli since thiere's not much that can be done in angular/angular directly.
