### ISSUE TITLE
docs: update support policy of angular releases to account for 7.0.0 release

### ISSUE THREAD

**Issue by preethamvishy** [angular/angular#26616]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Support policy only lists support upto ^6.0.0

## Expected behavior

Support policy to account for 7.0.0 release

**Comment by IgorMinar** [comment]
Fixed. Thanks
