### ISSUE TITLE
ngStyle does not working when resizing window

### ISSUE THREAD

**Issue by byungjur96** [angular/angular#26638]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I resize the window, ngStyle directive does not work after I updated my project from Angular 6 to Angular 7. ngStyle directive on my project gets offsetWidth of other element and set it as component's width. However, the width of component which contains ngStyle directive doesn't make update when I resize the window. However, the component makes update when I make wheel event.

My method is something like
<pre><code>
public myMethod(): string {
 return document.getElementById('divName').offsetWidth.toString() + 'px';
};
</pre></code>

and all I do in my template file is 
<pre><code>
&lt;my-component [ngStyle]="{'width': myMethod()}"&gt&lt;/my-component &gt
</code></pre>

## Expected behavior

ngStyle directive should work and resize the width of my component when I resize the window.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ 7.0.0 ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by cmddavid** [comment]
`ngStyle` doesn't have any sort of window resize listener by default. It's also not recommended to use methods inside your template. So I would encourage you to use a event listener to set a variable containing the width, and utilizing that inside your template.

**Comment by pkozlowski-opensource** [comment]
@cmddavid answer is spot-on here.

**Comment by byungjur96** [comment]
@cmddavid I just use ngstyle in this way since it worked in Angular 6.
I should have checked the documentation for its right usage.
Thanks for your reply
