### ISSUE TITLE
Unable to get rid of peer-dependency warnings when upgrading from 6.1 to 7.0

### ISSUE THREAD

**Issue by jimshowalter** [angular/angular#26636]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Following the steps in https://update.angular.io/ generates warnings:

<code>
> ng update @angular/cli @angular/core
UPDATE package.json (1450 bytes)
npm WARN @ng-bootstrap/ng-bootstrap@3.3.0 requires a peer of @angular/common@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@3.3.0 requires a peer of @angular/core@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@3.3.0 requires a peer of @angular/forms@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@6.2.4 requires a peer of typescript@~2.4.0 || ~2.5.0 || ~2.6.0 || ~2.7.0 || ~2.8.0 || ~2.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.3.0 requires a peer of @angular/compiler@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.3.0 requires a peer of @angular/core@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.

audited 39154 packages in 10.455s
found 0 vulnerabilities

> ng update @angular/material
UPDATE package.json (1450 bytes)
npm WARN @ng-bootstrap/ng-bootstrap@3.3.0 requires a peer of @angular/common@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@3.3.0 requires a peer of @angular/core@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@3.3.0 requires a peer of @angular/forms@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@6.2.4 requires a peer of typescript@~2.4.0 || ~2.5.0 || ~2.6.0 || ~2.7.0 || ~2.8.0 || ~2.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.3.0 requires a peer of @angular/compiler@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.3.0 requires a peer of @angular/core@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.

audited 39154 packages in 10.141s
found 0 vulnerabilities
</code>

Attempting to update the peer dependencies fails:

<code>
> ng update @ng-bootstrap/ng-bootstrap
                  Package "@ng-bootstrap/ng-bootstrap" has an incompatible peer dependency to "@angular/common" (requires "^6.1.0", would install "7.0.0")
Incompatible peer dependencies found. See above.
>
</code>

## Expected behavior

A consistent set of dependencies and no warnings.

## Minimal reproduction of the problem with instructions

See above.

## What is the motivation / use case for changing the behavior?

The upgrade results in an inconsistent dependency closure.

## Environment

<pre><code>
Angular version: 6.1 and 7.0

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.12.0  
- Platform:  Windows 10 

Others:

</code></pre>

**Comment by manklu** [comment]
> @ng-bootstrap/ng-bootstrap@3.3.0 requires a peer of @angular/common@^6.1.0

How should angular solve the fact that ng-bootstrap doesn't support 7.0 yet?

**Comment by jimshowalter** [comment]
So just ignore the warnings until other projects catch up?
