### ISSUE TITLE
Missing ngsw-worker.js and ngsw.json on dist folder upon production build after update to angular 7.0.0

### ISSUE THREAD

**Issue by datariomj** [angular/angular#26635]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
There's no ngsw-worker.js and ngsw.json on dist folder when running ng build --prod.

## Expected behavior
There's should be ngsw-worker.js and ngsw.json on running ng build --prod

## Minimal reproduction of the problem with instructions
- Angular cli should be version 7
- Build with new app ng new sw --service-worker
- Run ng build --prod

## Environment

<pre><code>
Angular version: 7.0.0

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.12.0
- Platform: Windows

Others:
- None
</code></pre>

**Comment by gkalpak** [comment]
The current way for creating a PWA (and adding SW to your app), is:

```
ng new my-app
cd my-app
ng add @angular/pwa
```

Also, see [here][1] for the flags currently supported by `ng new` (spoiler: `--service-worker` is not among them :wink:)

##
Closing, since everything works as expected afaict.
Feel free to open a new issue with more info in case I missed anything.

[1]: https://angular.io/cli/new

**Comment by datariomj** [comment]
You're right, it's working thanks. The issue was when i added angular playground  `ng add angular-playground` then it breaks. Maybe v7 is not yet supported. Thanks again
