### ISSUE TITLE
ng build --prod    go wrong  

### ISSUE THREAD

**Issue by 944060264** [angular/angular#26639]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

![zfs 0 0d 52i1eh6mpra6v](https://user-images.githubusercontent.com/19258806/47282398-a1138800-d611-11e8-8f11-eee2395c733b.png)

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.9.0  
- Platform:  Windows 

Others:

</code></pre>

**Comment by matsko** [comment]
Hey @944060264 can you open up a new issue with all the reproduction steps included? Thank you.
