### ISSUE TITLE
Hello,Angular  Support for dynamic change templateUrl?

### ISSUE THREAD

**Issue by bestbelief** [angular/angular#26641]
Hello, I think there is code in component.ts to change templateUrl dynamically. Is that ok?

**Comment by bestbelief** [comment]
I'm very sorry. Yesterday the page was a bit carded. I thought the problem was not submitted successfully, so I submitted it again.

**Comment by mlc-mlapis** [comment]
@bestbelief ...you missed the basic Angular functionality ... all HTML template is compiled to JS so what do you want to replace?

**Comment by cmddavid** [comment]
This is only possible with the JIT compiler(development only), you can however use the `innerHTML` property on HTML elements to at least render plain HMTL. You won't be able to utilize any of the Angular templating language capabilities inside HTML.

This repo might give you more info on the exact possibilities: https://github.com/lacolaco/ng-dynamic

**Comment by pkozlowski-opensource** [comment]
Closing as a support request, see @cmddavid answer

**Comment by bestbelief** [comment]
Thank you for your reply! I now need to write a website, each module of the site is a different layout, and these layouts are different templates, I wrote a lot of templates on the front-end html, according to the data from the database specified templates to be displayed as required
