### ISSUE TITLE
i18n Unknown placeholder, add ID to current message error

### ISSUE THREAD

**Issue by elvisbegovic** [angular/angular#26647]
## I'm submitting a...
<pre><code>
[x] Feature request
</code></pre>

## Current behavior
With this translatable string:
`<span i18n>Période du {{startDate}} au {{endDate}} ({{daysCount}} jours)</span>`
Due to translator (human error) one language and by mistake I have this in my `de.xtb` file:
```
<translation id="5255287352439643455" xml:space="default">
   Periode vom
   <ph name="INTERPOLATION">
      <ex>INTERPOLATION</ex>
   </ph>
   bis
   <ph name="INTERPOLATION_1">
      <ex>INTERPOLATION_1</ex>
   </ph>
   (
   <ph name="INTERPOLATION_3">
      <ex>INTERPOLATION_3</ex>
   </ph>
   Tage)
</translation>
```
When I build my app it throw error : 

> ERROR in Unknown placeholder "INTERPOLATION_3" ("POLATION"><ex>INTERPOLATION</ex></ph> bis <ph name="INTERPOLATION_1"><ex>INTERPOLATION_1</ex></ph> ([ERROR ->]<ph name="INTERPOLATION_3"><ex>INTERPOLATION_3</ex></ph> Tage)"): i18n@0:160

This is because `INTERPOLATION_3` should be here `INTERPOLATION_2` instead. This message error not help me to find string in minified file `de.xtb`, it is hard when I have (>5k string to translate) 

## Expected behavior
Improve message error and add at least `id:5255287352439643455` to the current error message!

## What is the motivation / use case for changing the behavior?
Find faster error in minified `xtb` file by searching by `id` when we have big amount fo translations strings.

## Environment
<pre><code>
Angular version: 7.0.0

For Tooling issues:
- Node version: 10
- Platform:  win10
</code></pre>

**Comment by colas74** [comment]
+1, this feature will be useful without a doubt until next release of i18n
