### ISSUE TITLE
Angular format_date input date localization

### ISSUE THREAD

**Issue by lukasmatta** [angular/angular#26648]
Hello,

When I pass locale as an argument to _formatDate()_  function, it only affects output of the function. However, function still only accepts date in English language.

This doesn't work (month in Czech language):
`formatDate('Po 05.dub.2018 12:45:32', 'dd.MMM.yyyy HH:mm:ss', 'cs');`
`// Produces: ERROR`

This works (month in English language):
`formatDate('Po 05.apr.2018 12:45:32', 'dd.MMM.yyyy HH:mm:ss', 'cs');`
`// Produces: 05.dub.18 12:45:32`

Thanks.

**Comment by sbappoo** [comment]
Have you tried to use a DateAdapter to cope with the language?

**Comment by sbappoo** [comment]
> Hello,
> 
> When I pass locale as an argument to _formatDate()_ function, it only affects output of the function. However, function still only accepts date in English language.
> 
> This doesn't work (month in Czech language):
> `formatDate('Po 05.dub.2018 12:45:32', 'dd.MMM.yyyy HH:mm:ss', 'cs');`
> `// Produces: ERROR`
> 
> This works (month in English language):
> `formatDate('Po 05.apr.2018 12:45:32', 'dd.MMM.yyyy HH:mm:ss', 'cs');`
> `// Produces: 05.dub.18 12:45:32`
> 
> Thanks.

Have you tried to use a DateAdapter to cope with the language?

**Comment by trotyl** [comment]
It's determined by browser implementation:

![image](https://user-images.githubusercontent.com/6059170/47345766-26fd0500-d6de-11e8-87a1-b97961188c41.png)

Given this is not part of ECMAScript support (undefined fallback behavior for invalid formats), anyone should not depend on it. Instead, use an ECMAScript-compatible ISO format, or a Date object.

**Comment by lukasmatta** [comment]
@trotyl But Angular is obviously able to recognize localized date as it can produce it as an output. 

Basically, my question is: If you can specify the language of the output date, is there a possibility to specify the language of output date? It is a possible feature request.

**Comment by ocombe** [comment]
Angular can output a localized date, but not necessarily use it as an input. Like @trotyl explained we use `Date` (and some other formats, like ISO, mysql, timestamp ...) as an input.

I don't see this change anytime soon, sorry.
