### ISSUE TITLE
Hello, do I want to dynamically change the templateUrl support in component.ts?

### ISSUE THREAD

**Issue by bestbelief** [angular/angular#26643]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
Sounds like it is the same as #26641

**Comment by bestbelief** [comment]
I'm very sorry. Yesterday the page was a bit carded. I thought the problem was not submitted successfully, so I submitted it again.

**Comment by bestbelief** [comment]
I'm very sorry. Yesterday the page was a bit carded. I thought the problem was not submitted successfully, so I submitted it again.
