### ISSUE TITLE
docs-css: use standard colors across API docs and guides

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#26661]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[X ] Other... Please describe: docs-infra and css for API docs
</code></pre>

## Current behavior

API docs use colors in different ways than guides:
* Red for hyperlinks (versus blue in guides)
* Blue for ? ( versus blue for hyperlinks in guides

See https://angular.io/api/animations/animate
* Why is null blue?
* Why aren't hyperlinks blue instead of red

## Expected behavior

* blue = hyperlinks throughout doc set
* Need a diff color for whatever we intended to highlight by making `null` blue

## Minimal reproduction of the problem with instructions

See link above

## What is the motivation / use case for changing the behavior?

Basic standardization, so colors preserve meaning throughout the doc set

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
Reason for current colors: Matches what you'd see in code. Probably default palette from prettify. https://www.prettifyjs.net/

**Comment by jenniferfell** [comment]
Notes:
* Code blocks are consistent with API syntax (well, similar if not exact colors)

**Comment by jenniferfell** [comment]
Related: https://github.com/angular/angular/issues/26370

**Comment by jenniferfell** [comment]
Related re title area of code and example boxes: https://github.com/angular/angular/issues/23984

**Comment by ajitsinghkaler** [comment]
@gkalpak is this still applicable

**Comment by gkalpak** [comment]
No, I don't think so. The color highlighting/coloring comes from prettify. The fact that some things in color-highlighted code-snippets are converted to links is just an extra feature to help people navigate to related things, but we should not change the coloring of those links imo.

I am going to close this. There are other issues (mentioned above) to track related areas where we could improve.
