### ISSUE TITLE
dynamically render a component in lazy loaded module with AOT cant find component factory

### ISSUE THREAD

**Issue by glappatoni** [angular/angular#26665]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I declared those dynamic components as entry components in the module where I also want to render them. With JIT it works fine.
Following structure has the part of my app I want to render them: app -> home (lazy) -> contracts (lazy) -> search. So I added those components to the module I use for the search component/route. When Im compiling with AOT, everytime I visit the search route, the app tells me there is no component factory. Of course I searched google and found some results: I tried adding them to the `ANALYZE_FOR_ENTRY_COMPONENTS` provider, I tried to import a `ModuleWithProviders` with `.forRoot()` in my app.module and I also tried simply importing and declaring my dynamic and all of its dependant components in the root module (app.module). Everything resulting in the same error.

I declare my dynamic components as entry components like so:
```
@NgModule({
  imports: [SharedComponentsModule, FinoSchemaFormsModule, TabGroupModule, FinoInputModule],
  declarations: [EnergySearchSettingsComponent, DslSearchSettingsComponent, MobileSearchSettingsComponent, ComparisonDetailSectionComponent],
  entryComponents: [EnergySearchSettingsComponent, DslSearchSettingsComponent, MobileSearchSettingsComponent],
  exports: [EnergySearchSettingsComponent, DslSearchSettingsComponent, MobileSearchSettingsComponent, ComparisonDetailSectionComponent],
  providers: [CategoryMappingProvider]
})
export class ComparisonComponentsModule { }
```

This module gets imported in the `SearchModule`, where also my `SearchComponent` is declared. In this component I want to render those components dynamically using the `ComponentFactoryResolver` I inject in the `SearchComponent`. 
```
ngOnInit() {
    this.searchSettingsComponent = this.comparisonService.getSearchComponent(); // returns either EnergySearchSettingsComponent, DslSearchSettingsComponent or MobileSearchSettingsComponent
    let componentFactory = this.componentFactoryResolver.resolveComponentFactory(searchSettingsComponent);
    this.searchSettingsComponent = this.searchContainer.createComponent(componentFactory);
    this.searchSettingsComponent.instance.comparisonSettings = comparisonSettings;
    this.searchSettingsComponent.instance.onSave.subscribe(settings => this.saveSearchSettings(settings));
}
```

The `SearchComponent` is the routing component of the `search` route, which is a child route of my `contract` route, which gets lazy loaded. This again is a child route of my home route (also lazy loaded) and this belongs to the main route.

## Expected behavior
Render da compontenz!
Or maybe point me in the right direction as what is going wrong here/what do I misunderstand?

## Minimal reproduction of the problem with instructions
I think I described the problem and my project structure well enough to reproduce this issue.

## Environment

<pre><code>
Angular version: 5.2.4
 
For Tooling issues:
- Node version: 8.11.3
- Platform:  Mac

</code></pre>

**Comment by glappatoni** [comment]
> This sounds similar to #14324.
> 
> There is a solution/workaround described in the replies which might work for you.

No, this is another issue. He tries to render a dynamic component, declared in a lazy module. He wants to render it outside this lazy module.
I just want to render it in the same module I declare it and add it as entryComponent. But that does not work. Seems like you cant dynamically render a component in a lazy loaded module.

**Comment by mlc-mlapis** [comment]
@glappatoni ... what do you call `dynamically render a component in a lazy loaded module`? You mean using:

```
constructor(private componentFactoryResolver: ComponentFactoryResolver) {}
...
let componentFactory = this.componentFactoryResolver.resolveComponentFactory(...);
```

And when do you want to render it? You first load a lazily loaded module via routing and then you are trying to get the factory ... and where? On the base of `componentFactoryResolver` taken from a constructor?

**Comment by glappatoni** [comment]
> @glappatoni ... what do you call `dynamically render a component in a lazy loaded module`? You mean using:
> 
> ```
> constructor(private componentFactoryResolver: ComponentFactoryResolver) {}
> ...
> let componentFactory = this.componentFactoryResolver.resolveComponentFactory(...);
> ```
> And when do you want to render it? You first load a lazily loaded module via routing and then you are trying to get the factory ... and where? On the base of `componentFactoryResolver` taken from a constructor?

I updated my issue

**Comment by mlc-mlapis** [comment]
@glappatoni ... still not exactly clear what you are doing ... if you want a help, prepare a reproduction demo ... as simple as possible ... do it in http://stackblitz.com ... even it is JIT environment ... but it is simple to take it and run it locally in AOT mode or create a simple project repo using CLI.

**Comment by mlc-mlapis** [comment]
@glappatoni ... just one notice ... `componentFactoryResolver` is always related to a module, so if you want to exactly control **when and what** ... probably the simplest way is to load the lazily loaded module programmatically ... so you can simply use a module reference .... like:
```
const _cmpFactory: ComponentFactory<any> = _ngModuleRef.componentFactoryResolver.resolveComponentFactory(_cmpType);
```

**Comment by pkozlowski-opensource** [comment]
I'm going to close this issue as we never heard back with a reproduce scenario. If anyone is bumping into anything similar, please open a new GitHub issue with a minimal reproduce scenario. Thnx!
