### ISSUE TITLE
Input wrapper component on Reactive Forms  

### ISSUE THREAD

**Issue by borriej** [angular/angular#26679]
Angular 6.x

Hi,

Im having a simple, but rather complex issue:

Inside my Reactive Form I want to use a component thats wraps ```<input>``` and re-use FormControl. So I have a generic way inside my project to render inputs with error classes etc.

```
<custom-input [control]="form.get('contactDetails').get('firstName')"></custom-input>
```

the CustomInput component looks like this:
``` 
import { Component, Input } from '@angular/core';
import { AbstractControl } from '@angular/forms';

@Component({
  selector: 'custom-input',
  templateUrl: './custom-input.component.html',
  styleUrls: ['./custom-input.component.css']
})
export class CustomInputComponent {
  @Input() control: AbstractControl;
  @Input() customClass: any;
  @Input() customPlaceholder: string;
  @Input() customId: string;
}
```
```
<input type="text"
       [attr.id]="customId"
       class="form-control {{ customClass }}"
       [formControl]="control"
       placeholder="{{ customPlaceholder }}"
       [ngClass]="{'is-invalid': control.errors && (control.touched || control.dirty) }">
```

As you can see, i dont use ```ControlValueAccessor```, but i just re-use FormControl. This saves tons of code. Because its already a native form element.

But I get this tslint:
```
Call expressions are not allowed in templates except in output handlers
```
(So apparently ```form.get()``` is not allowed)

So i rewrote this to
```
<custom-input [control]="form.controls['contactDetails'].controls['firstName']"></custom-input>
```
but this gave me a build error
```
Property 'controls' does not exist on type 'AbstractControl'.
```

So i rewrote everything to Reactive Forms patterns, like:
```
<custom-input formControlName="email"></custom-input>
<show-errors formControlName="email"></show-errors>
```

But now I have to use ```ControlValueAccessor```for around 9 input wrapper components in my project... and I have to add an extra 40-50 lines of code per component.

* What i want is that for native form element i can just pass ```FormControl``` inside an ```@Input```   
* I also want to use ```form.get('findGroup').get('findField')``` instead of writing ```form.controls['findGroup'].controls['findField']``` (this is not nice for development)
* I there and official stand point on this? What is best practice? 

Example of my form pattern
```
<form [formGroup]="form"
      (ngSubmit)="submit(form)"
      #form
      class="form"
      novalidate>
  <div class="form-group">
    <label>Sign up for the newsletter:</label>
    <custom-input [control]="form.get('email')" customPlaceholder="Email"></custom-input>
    <show-errors [control]="form.get('email')"></show-errors>
  </div>
  <div class="d-flex"
       *ngIf="submitBtnShow">
    <button type="submit"
            class="btn {{ submitBtnClass }} ml-auto"
            [disabled]="signInForm['disabled']">
      {{ submitBtnLabel }}
    </button>
  </div>
</form>
```

**Comment by dawidgarus** [comment]
Maybe use pipe:
```typescript
@Pipe({
  name: 'control'
})
export class ControlPipe implements PipeTransform {
  transform(form: FormGroup, path: string|(string|number)[]): AbstractControl {
    return form.get(path);
  }
}
```
```html
<custom-input [control]="form | control:'contactDetails.firstName'">
```

**Comment by kara** [comment]
We reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on Gitter or [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

That said, you might try using a getter, e.g. 
```ts
get firstNameControl() { return this.form.get('contactDetails.firstName'); }
```
