### ISSUE TITLE
Multiplication error

### ISSUE THREAD

**Issue by nadwath** [angular/angular#26680]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

3.65 * 1369 = 4996.849999999999

## Expected behavior

3.65 * 1369 = 4996.85

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-j1mvba?file=src%2Fapp%2Fapp.component.ts

## Environment

<pre><code>
Angular version: 4.3.2

Browser:
- [x] Chrome (desktop) version 70.0.3538.67 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 62.0.3 (64-bit)
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.12.0  
- Platform:  Ubuntu
</code></pre>

**Comment by rodolfojnn** [comment]
This is not a "Angular" thing. This is a normal floating point behavior in Javascript. If you want absolute accuracy, you'll need to work exclusively in integers.

**Comment by manklu** [comment]
> This is a normal floating point behavior in Javascript.

This is normal floating point behaviour in any language I know.

**Comment by pkozlowski-opensource** [comment]
As others pointed out, this is JS behaviour, nothing specific to Angular.
