### ISSUE TITLE
Validators : UpdateOn => blurChange

### ISSUE THREAD

**Issue by Zelarith** [angular/angular#26683]
## Current behavior
We can either set "updateOn" to "change", "blur" or "submit".

My problem with "change" is that it happens too soon : you type a letter, and the validation will immediatly trigger and shout errors.

"Submit" is kinda late, on big forms (i.e. a page where you need to scroll), you'd need to re visit the whole page, searching for the errors.

"Blur" is the best compromise, it pops when it needs to. 
The issue? It doesn't track programatical changes AND it doesn't trigger again on submit

## Expected behavior

1 - "Blur" should also trigger on submit.

2 - If not "blur", a new "updateOn" value such as "blurChange" should pick up programatical changes.

## What is the motivation / use case for changing the behavior?
1 - Let's say you have validators on a "name" field saying 
- this field can be empty
- this field, if not left empty, should match "(Mr|Ms) \w+"

And you also have a "gender" radio button wich will automatically fill "Mr " or "Ms " in the "name" field.

In a scenario where we only click the gender button and then submit the form, "name" started empty and, as such, was originally controlled as valid. It is never controlled again, but ends up with the value "Mr " or "Ms " wich doesn't match my regex, and should be rejected.

2 - I'm creating a new user, with login/password on my app.
My browser recognizes my usual login and suggests a password.
Password field is filled programatically by an external source (my browser), and so "blur" is never triggered.
Note : "change" would have been triggered.
As a result, my password is never validated, not even when I click submit. I have to focus / blur my password field for validation to be properly executed.

## Environment

Angular version: 6.1.10 I think (according to @angular/core => package.json => "_id" property)
Browser: Firefox

**Comment by ChrisDahmCS** [comment]
@Zelarith I believe this kind of interaction can be achieved by using a formGroup with your changeOn as the desired 'submit', and the individual controls can have the changeOn as 'blur'. With the notes [here](https://github.com/angular/angular/commit/ff5c58be6b843bc8f79613dbefc5e4951c125f3d), you should be able to combine such functionalities as you see fit. 

For example 1:
Have an encompassing FormGroup with updateOn set to 'submit'.
The same child FormControls for text can have the updateOn set to 'blur'.
The toggles or whatever is prepending your name can have the updateOn set to 'change'.

When the parent FormGroup has a child that triggers the updateValueAndValidity method, it should force it on the FormGroup as well. When the form is submitted, it'll trigger that method from the FormGroup's updateOn 'submit' value. 

I know [this example on StackBlitz](https://stackblitz.com/edit/angular-form-control-fun-stuff) isn't exactly what you are asking for, but I think via the change cycle and subscriptions it shows how you can achieve what you are asking for part 1. When changing the name, it does not update anything. When navigating off the field, it updates. When changing the prepend, it updates. When submitting, it updates.

For example two, the FormGroup having updateOn as 'submit' will solve this issue (while still having the FormControls updateOn as 'blur'.

Does this help with the issue you are having?

**Comment by Zelarith** [comment]
@ChrisDahmCS I didn't know we could set updateOn on the form group itself.
It certainly does make sense to.

However, I'm not sure it will be able to fix the issue though, since the default value for "updateOn" seems to be... Well... 'default', wich appears to update whenever there is any change in the "scope" (not sure this is the correct word... It was for AngularJS !)

Based on this observation, I expect the validation of the FormGroup to only check the validity status of its child FormControls, without forcing them to actually rerun the validators.

Anyway, I'll give it a try when I'm given the opportunity, sadly I was just assigned to another project so I guess it'll have to wait a bit longer.

**Comment by ChrisDahmCS** [comment]
@zelarith I'll be happy to look into this more with you in the future-

**Comment by thefliik** [comment]
I just made a proposal which addresses this issue over in #31963. I'd be very interested in any feedback you might have. Specifically, it allows a service to add/remove errors from a control. Because errors are keyed to the service which adds them, one service cannot overwrite another's errors. 

For example, this hypothetical service checks the `usernameControl` to see if the entered username already exists or not. It uses debounce time to ensure that checks aren't made too frequently. 

```ts
const usernameControl = new FormControl();

usernameControl.valueChanges
  .pipe(
    tap(() => usernameControl.markPending('userService', true)),
    debounceTime(500),
    switchMap(value => this.userService.doesNameExist(value)),
    tap(() => usernameControl.markPending('userService', false)),
    map(response => ({
      sources: ['MyUserService'],
      type: 'errors',
      value: response.payload ? { userNameExists: true } : null, <-- this is an error (or null)
    })),
  )
  .subscribe(usernameControl.source);
```

More broadly, this allows you to programmatically add errors to a control however you see fit, either synchronously or asynchronously (in addition to using `ValidatorFn` / `AsyncValidatorFn`). It would allow you to create a custom "validation" interval.

**Comment by intellix** [comment]
Thought something like this would work but seems not:
```ts
  form = new FormGroup({
    username: new FormControl('', { updateOn: 'blur' }),
    password: new FormControl('', { updateOn: 'blur' }),
  }, { updateOn: 'submit' });
```

Example of bug: https://stackblitz.com/edit/angular-reactive-form-blur-submit?file=src%2Fapp%2Fapp.component.html

**Comment by branhill** [comment]
A quick and dirty fix using directive:

```ts
import { Directive, ElementRef, HostListener } from '@angular/core';
import { NgControl } from '@angular/forms';

@Directive({
  // https://github.com/angular/angular/blob/master/packages/forms/src/directives/default_value_accessor.ts#L63
  selector:
    'input:not([type=checkbox])[formControlName],textarea[formControlName],input:not([type=checkbox])[formControl],textarea[formControl],input:not([type=checkbox])[ngModel],textarea[ngModel],[ngDefaultControl]',
})
export class ControlUpdateOnBlurOrChangeDirective {
  constructor(private elementRef: ElementRef, private ngControl: NgControl) {}

  @HostListener('input')
  onInput() {
    if (this.elementRef.nativeElement !== document.activeElement) {
      this.tryDispatchBlurEvent();
    }
  }

  @HostListener('keydown.enter')
  onEnterKeydown() {
    this.tryDispatchBlurEvent();
  }

  private tryDispatchBlurEvent() {
    if (this.ngControl?.control?.updateOn === 'blur') {
      this.elementRef.nativeElement.dispatchEvent(new Event('blur'));
    }
  }
}
```

**Comment by KseinyaR-STCU** [comment]
Just ran into this problem in our own app, and the implications are a little concerning.

Small repro:  https://stackblitz.com/edit/angular-ivy-qc4gzo

If you type something into the field and press the Enter key, the input field still has focus, so the value entered isn't saved and is considered invalid.

If you type something and click Submit with the mouse, this moves the focus to the button, so the value is saved and valid.

If you type something, click out of the field (moving the focus, hence updating the field), and then GO BACK into the field and change the value, this does not get updated on an Enter keypress. This would cause a form submitted with the Enter key to submit the wrong value.

Our current workaround is to force focus onto the submit button whenever the submit function is triggered, but this is breaking Angular "rules" with manipulating the dom directly.
