### ISSUE TITLE
component reuse with lazy loaded module

### ISSUE THREAD

**Issue by henryhe1993** [angular/angular#26681]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[-] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have 2 lazy loaded modules, module-one and module-two.
app-routing.module.ts: 
const routes: Routes = [
  {path: '', children: [
    {path: 'one', loadChildren: '../pages/module-one/module-one.module#ModuleOneModule'},
    {path: 'two', loadChildren: '../pages/module-two/module-two.module#ModuleTwoModule'}
  ]},
  {path: '**', redirectTo: ''}
];

where module-one has 2 paths:
module-one-routing.module.ts
const routes: Routes = [
  {path: 'one', component: TestOneComponent},
  {path: 'two', component: TestTwoComponent},
  {path: '**', redirectTo: 'one'}
];

module-two has 1 path:
const routes: Routes = [
  {path: '', component: ComComponent},
  {path: '**', redirectTo:''}
];

I wanted to apply the Component Reuse Strategy.
export class CustomReuseStrategy implements RouteReuseStrategy { 
  private handlers: {[key: string]: DetachedRouteHandle} = {};
  shouldDetach(route: ActivatedRouteSnapshot): boolean {
    return true;
  }

  store(route: ActivatedRouteSnapshot, handle: DetachedRouteHandle): void {
    this.handlers[this.calcPath(route)] = handle;
  }

  shouldAttach(route: ActivatedRouteSnapshot): boolean {
    return !!this.handlers[this.calcPath(route)];
  }

  retrieve(route: ActivatedRouteSnapshot): DetachedRouteHandle {
    return this.handlers[this.calcPath(route)];    
  }

  shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {
    return future.routeConfig === curr.routeConfig;
  }

  private calcPath(route: ActivatedRouteSnapshot) {
    return (route as any)._routerState.url;
  }
}

Suppose:
STEP 1: start from /two to /one/one     ok;
STEP 2: then to /one/two                      ok;
STEP 3: then to /two                              ok and component used;

STEP 4: then to /one/one **fail**
Error: Uncaught (in promise): Error: Cannot reattach ActivatedRouteSnapshot created from a different route
Error: Cannot reattach ActivatedRouteSnapshot created from a different route

BUT, it can successfully navigate to /one/two, then to /one/one;

I found that:
In STEP 2, the store(route: ActivatedRouteSnapshot, handle: DetachedRouteHandle) receives a route {children: [], routeConfig: {component: ..., path: 'one'}} (as it is a route change inside module one??? )

In STEP 3,  the store(route: ActivatedRouteSnapshot, handle: DetachedRouteHandle) receives a route {children: [ActivatedRouteSnapshot], routeConfig: {loadChildren: ..., path: 'one'}} (guess this is the correct one?)

So, when STEP 4 takes place (in the setFutureSnapshotsOfActivatedRoutes() at router.js 2280), the curr.value.routeConfig does not match result.value.routeConfig and throws an error.

## Expected behavior

successful component reuse or if there is a workaround

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-gitter-vaa4tr?embed=1&file=app/app.module.ts

**Comment by Ardaipek** [comment]
Any update on this?

**Comment by shammy8** [comment]
I'm also interested in this. @Ardaipek can you call the onDestroy manually using the handles? I need to take a deeper look when I have time.

**Comment by me-dira** [comment]
Hello dear, too many people have problems with Angular Reusable Route Strategy.
but for this specific error: `Cannot reattach ActivatedRouteSnapshot created from a different route` I should say that it's because of keys and the way you generate the keys. Too many people use the `ActivatedRouteSnapshot.routeConfig.path` property to generate the key to store the handlers but you should understand that the mentioned property is not unique for example:
in  /user/panel/add => `ActivatedRouteSnapshot.routeConfig.path` is add
and in  /user/somethingelse/add => `ActivatedRouteSnapshot.routeConfig.path` is add
and also in /add => `ActivatedRouteSnapshot.routeConfig.path` is add
 

I'm using the below code for my application and it works even for `lazy loaded modules` everything works but you should understand I'm using a hash library called crc32 to create unique keys for cached handlers.
for the test just omit those parts.
pay attention that generating a unique key for that handler is very important when it's time to retrieve the cached route handler.

```

import { ActivatedRouteSnapshot, DetachedRouteHandle, RouteReuseStrategy, UrlSegment } from '@angular/router';

// Self written hash utility.
import { Crc32HashBlockInstance } from 'src/app/shared/utilities/hash/Crc32HashBlockWithInstance';

export class CustomRouteReuseStrategy implements RouteReuseStrategy {
  private handlers: Record<string, DetachedRouteHandle> = {};

  shouldDetach(route: ActivatedRouteSnapshot): boolean { return true; }

  store(route: ActivatedRouteSnapshot, handle: DetachedRouteHandle): void {
    this.handlers[this.getKey(route)] = handle;
  }

  shouldAttach(route: ActivatedRouteSnapshot): boolean {
    return !!route.routeConfig && !!this.handlers[this.getKey(route)];
  }

  retrieve(route: ActivatedRouteSnapshot): DetachedRouteHandle | null {
    if (!route.routeConfig) {
      return null;
    }
    return this.handlers[this.getKey(route)];
  }

  shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {
    return curr.routeConfig === future.routeConfig;
  }

  private getKey(route: ActivatedRouteSnapshot): string {
    const realRootPath = this.getRootPath(route);
    let key: string;

    if (route.component) {
      key = (route.component as any)['name'];
    } else {
      key = (route.firstChild!.component as any)['name'];
    }
    
    // Im using hash but I think realRootPath is enough.
    const hashObject = new Crc32HashBlockInstance(realRootPath + key);
    const hash = hashObject.asHex();

    return `${hash!}`;
  }

  // This method returns full path like /panel/user/add instead of /add or add. It helps to generate unique keys.
  private getRootPath(route: ActivatedRouteSnapshot) {
    return ((route as any)["_urlSegment"]["segments"] as UrlSegment[])
      .map((seg) => seg.path)
      .join("/");
  }

}
```

**Comment by me-dira** [comment]
try this working example:
https://stackblitz.com/edit/angular-gitter-gz5zcd?embed=1&file=app/app.module.ts
There is no need to disable ngOnDestroy hooks.

```

export class CustomReuseStrategy implements RouteReuseStrategy {
  private handlers: Record<string, DetachedRouteHandle> = {};

  shouldDetach(route: ActivatedRouteSnapshot): boolean {
    return false;
  }

  store(route: ActivatedRouteSnapshot, handle: DetachedRouteHandle): void {
    this.handlers[this.getKey(route)] = handle;
  }

  shouldAttach(route: ActivatedRouteSnapshot): boolean {
    return !!route.routeConfig && !!this.handlers[this.getKey(route)];
  }

  retrieve(route: ActivatedRouteSnapshot): DetachedRouteHandle | null {
    if (!route.routeConfig) {
      return null;
    }
    return this.handlers[this.getKey(route)];
  }

  shouldReuseRoute(
    future: ActivatedRouteSnapshot,
    curr: ActivatedRouteSnapshot
  ): boolean {
    return curr.routeConfig?.path === future.routeConfig?.path;
  }

  private getKey(route: ActivatedRouteSnapshot): string {
    const realRootPath = this.getRootPath(route);
    let key: string;

    if (route.component) {
      key = (route.component as any)['name'];
    } else {
      key = (route?.firstChild?.component as any)?.['name'] || 'homechild';
    }

    return `${key!}`;
  }

  private getRootPath(route: ActivatedRouteSnapshot) {
    return ((route as any)['_urlSegment']['segments'] as UrlSegment[])
      .map((seg) => seg.path)
      .join('/');
  }
}
```

**Comment by me-dira** [comment]
Sorry, I'm posting multiple times.
I was playing with your code and I understand the problem can be resolved if you name your `<router-outlet>` in `app.component.html`
https://stackblitz.com/edit/angular-gitter-lgje7v?embed=1&file=app/app.module.ts

**Comment by atscott** [comment]
Closing as resolved. Updated the example to v14 and changed the reuse strategy to track handles by the associated `Route`: https://stackblitz.com/edit/angular-ivy-v1bxpr?file=src%2Fapp%2Fapp.component.ts,src%2Findex.html
