### ISSUE TITLE
FetchEvent.respondWith received an error: TypeError: Internal error (WebKitServiceWorker: 0)

### ISSUE THREAD

**Issue by zgabievi** [angular/angular#26690]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

On Safari, if you have service worker registered, when you "Empty Cache" and refresh page, you get an error:

![image](https://user-images.githubusercontent.com/1515299/47070231-dd09b000-d201-11e8-9e90-2a9bd335a7d3.png)

## Expected behavior

There should be polyfill that fixes this error.

## Minimal reproduction of the problem with instructions

* Register service worker on project
* Open in safari
* Empty cache
* Refresh page

## What is the motivation / use case for changing the behavior?

To make service worker workable in Safari

## Environment

<pre><code>
Angular version: 7.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version 12.0
- [x] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.10.0  
- Platform:  Mac 

Others:

I had previously created same issue for Angular 6, but it still exists in version 7. 
</code></pre>

**Comment by patrickmichalina** [comment]
Same issue here!

**Comment by Floaz** [comment]
Same issue here!

I get the error even when the update process is running in the background. (without purging cache)
And that is a more serious problem.
Do you have the same?

**Comment by gkalpak** [comment]
Can someone confirm whether this is still an issue? We have made some changes recently that should have made the SW more resilient to issue with corrupt/cleared caches, so maybe this problem has been addressed.

**Comment by patrickmichalina** [comment]
@gkalpak I have not see this in quite some time, thanks!

**Comment by gkalpak** [comment]
Thx, @patrickmichalina. I am going to close this one then. (The range issue is being tracked in #25865.)
If anyone is still running into this problem with the latest SW, please open a new issue.
