### ISSUE TITLE
docs: code references may link to incorrect symbol

### ISSUE THREAD

**Issue by JoostK** [angular/angular#26696]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

On angular.io, several `<code>` fragments point to an incorrect location when multiple symbols of the same name exist. For example, all [`group` function references on this page](https://angular.io/guide/complex-animation-sequences) refer to `FormBuilder`'s `group` method, not the animations `group` function.

Another example is the usage of `easing` here, it refers to a property in `MockAnimationPlayer`:

https://github.com/angular/angular/blob/d0cc019c1ae03555c61b47152ff4ce4616ebd21e/aio/content/guide/complex-animation-sequences.md#L45

## Expected behavior

Linked references point to the correct symbol documentation page.

Others:

</code></pre>

@petebacondarwin Is the generation of links done in dgeni, or somewhere else in the pipeline?

**Comment by petebacondarwin** [comment]
@JoostK yes it is done in the dgeni processing... here: https://github.com/angular/angular/blob/master/aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js

**Comment by petebacondarwin** [comment]
And the `getDocFromAlias` from is defined here https://github.com/angular/angular/blob/master/aio/tools/transforms/links-package/services/getDocFromAlias.js

and that uses "disambiguators" to try to reduce ambiguous matching aliases: https://github.com/angular/angular/tree/master/aio/tools/transforms/links-package/services/disambiguators

**Comment by petebacondarwin** [comment]
It is a kind of heuristic approach, which probably needs some fine tuning :-)

**Comment by JoostK** [comment]
@petebacondarwin Ah, thanks, that is indeed what I was looking for. I see now, because the links I provided are general documentation pages the `disambiguateByModule` will not kick in. For the `easing` link, looks like it shouldn't actually be a code reference (the `disambiguateByNonMember` is already in place to prefer top-level exports but there's no such thing in this case.)

**Comment by JoostK** [comment]
Regarding the module heuristics, is there some sort of tagging mechanism for general documentation pages? That would do the trick here, as we could then have a heuristic to prefer the animations package over forms.

**Comment by petebacondarwin** [comment]
Are you suggesting that we associate guides with modules... that is an interesting idea! Guides can have jsdoc tags, just like any other doc in dgeni. So we could add something like `@module animations` tag to the guide. But then we would need to write a processor that actually wires up the `moduleDoc` property on the doc to the real module doc.

**Comment by JoostK** [comment]
Something like that, yes. Inspired by e.g. https://github.com/gohugoio/hugoDocs/blob/master/content/en/documentation.md where a small yaml document is present for metadata.

**Comment by petebacondarwin** [comment]
You can see jsdoc tags in action in this file: https://github.com/angular/angular/blob/master/aio/content/license.md

We wanted to set the title to empty, rather than computing the title from the filename.

**Comment by petebacondarwin** [comment]
Actually, thinking about a solution, I would rather store this information outside of the source files. We should have some kind of "bundle" information stored in a separate file that helps knit together the API source files, the examples and the guides. This is already done imperatively (which is bad) for the `docs-watch` task to work. See https://github.com/angular/angular/blob/master/aio/tools/transforms/authors-package/api-package.js#L12-L27

**Comment by METACEO** [comment]
Just hit this bad link myself and was thinking it'd be a quick fix. There's another effort (#29213) that I think is getting mixed up in this, too.

**Comment by dylhunn** [comment]
The specific issue highlighted at the top (animations `group()`) was fixed on its own. The general issue is how Dgeni resolves ambiguous references. Degni will do _something_, but it's best to just include the full path when referring to overloaded API symbol.
