### ISSUE TITLE
Interpolation using JSON data in dart doesn't work

### ISSUE THREAD

**Issue by lnlwd** [angular/angular#2670]
I have the following problem in dart:

I'm using JSON data in dart, but the same thing happens with List type, my code:

    import 'dart:convert';
    import 'package:angular2/angular2.dart';
    @Component(
        selector: 'app'
    )
    @View(
        template: '''
        <ul>
            <li *ng-for="#todo of list">
                {{todo.name}}
            </li>
        </ul>
    ''',directives: const [NgFor]
    )
    class App {
        var list = JSON.decode('''[
            {
                "name": "Task1"
            },
            {
                "name": "Task2"
           }
        ]''');
    }

So, when I use in template ``{{todo}}`` I get:
*    {name:Task1}
*    {name:Task2}

But, when I use ``{{todo.name}}`` I get only empty list items:

*    
*    

The same thing happens when using ``JSON.decode`` or ``List<Map>`` 

Sorry my bad english!!

Thanks for help! :smile:

**Comment by matanlurey** [comment]
Could you try `{{todo['name']}}`? I think Angular 2 does not pretend Maps and Objects are the same thing like Angular 1.0 dart did.

**Comment by lnlwd** [comment]
Works fine guy! Many Thanks!! :smile:
