### ISSUE TITLE
Failed to execute 'animate' on 'Element': Partial keyframes are not supported in a loop

### ISSUE THREAD

**Issue by AlexanderBukhtaty** [angular/angular#26709]
hi.
i have catch an error (if i use the directive in the inside of the component which is in the loop)
Error: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
source
[angular5-collapse-directive-with-animation](https://stackblitz.com/edit/angular5-collapse-directive-with-animation)

**Comment by AlexanderBukhtaty** [comment]
problem in this.update(); in the constructor

**Comment by matsko** [comment]
Is this solved with your fix? The demo looks operational? Please reopen if it's still unsolved.
