### ISSUE TITLE
TypeError: Reflect.getMetadata is not a function

### ISSUE THREAD

**Issue by splincode** [angular/angular#26714]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

`ng update @angular/core@7.0.0`

after update removed from polyfills.ts `import 'core-js/es7/reflect'`

if we run AOT mode

![image](https://user-images.githubusercontent.com/12021443/47421909-3b96d700-d78a-11e8-9d48-cd5e6f3db24e.png)

Many projects use a package https://github.com/typestack/class-transformer

https://github.com/typestack/class-transformer/issues/52

## Expected behavior

Why remove the polyfill?

## Environment

<pre><code>
Angular version: 7.0.0

</code></pre>

**Comment by chaosmonster** [comment]
This is intended behaviour. You can read about it and the reasons here https://blog.angular.io/version-7-of-angular-cli-prompts-virtual-scroll-drag-and-drop-and-more-c594e22e7b8c

**Comment by Wisdomb33r** [comment]
I'm having the same error message after my Angular 7 migration.

@chaosmonster your link is saying why the polyfill was removed, but also says it is not needed for production builds. But apparently it may be needed in some situations. I do not have the crash in dev mode (JIT), but have the crash in prod mode (AOT). Splincode seems to have the same crash using AOT. If not needed for prod build, can you explain why we do have a prod mode crash ? And if re-adding the polyfill is not the correct solution, is there somewhere documentation to solve this the proper manner ?

**Comment by jpduckwo** [comment]
@Wisdomb33r did you find any further info? I've the same issue that the error appears in prod only...

**Comment by Wisdomb33r** [comment]
@jpduckwo Fow now, I restored the polyfill. As far as I understood the error, it is related to the class-transformer library. Might be that Angular itself needs the polyfill only in dev mode, but class-transformer library needs it in prod. I could not find more documentations about this yet.

**Comment by jpduckwo** [comment]
Thanks for the reply @Wisdomb33r, I came to the same conclusion too!

**Comment by markmakes** [comment]
@Wisdomb33r how did you restore only this polyfill?

**Comment by jpduckwo** [comment]
@markmakes put 
```
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect';
```
back in your polyfills.ts

**Comment by markmakes** [comment]
@jpduckwo thank you sir!

**Comment by IgorMinar** [comment]
As mentioned in the comments above, the removal of the reflect-metadata polyfill is not a regression but an intentional change. Great majority of the existing projects don't need it any more and for the few projects that have other libraries that depend on this polyfill the solution is to explicitly add it back to polyfills.ts (as mentioned in https://github.com/angular/angular/issues/26714#issuecomment-438830593). 

I'm sorry about the inconvenience but if we didn't remove the polyfill automatically, most projects would keep on including it unnecessarily. Going forward we'll document these changes better in the release notes.
