### ISSUE TITLE
Nested content does not propagate click events

### ISSUE THREAD

**Issue by Runeboy** [angular/angular#2671]
Related to Alpha 27.

There may an issue with missing propagation of click events from nested content (when writing 
components using the <content></content>). E.g. the following container component
`<div (click)="onClick()">    
    <content></content>
</div>`
The usage is for a context menu component with nested menu item components:

![image](https://cloud.githubusercontent.com/assets/12996372/8277456/43451040-18c3-11e5-9db4-725ec9c41178.png)

The handler is only invoked when clicking outside the text (event does not bubble up).

**Comment by vicb** [comment]
"(click)" does not bubble up, "(^click)" does.

**Comment by Runeboy** [comment]
I can confirm that works. Merci bcp!
