### ISSUE TITLE
Angular service worker  not work in online environment deploy by nginx

### ISSUE THREAD

**Issue by 100cm** [angular/angular#26713]
## Current behavior
Service worker works in local http server but not work with nginx 

## Minimal reproduction of the problem with instructions
[online location](http://ng-at.thunderjava.com)

## Environment

Angular version: 7.0.0

For Tooling issues:
- Node version: 10.x
- Platform:  Mac

code repo:

https://github.com/100cm/at-ui-angular/tree/versions-7.x

Nginx Conf

```
server{
      server_name ng-at.thunderjava.com;
      listen 80;
       location /{
            root /root/ng-at/;
            autoindex on;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            error_page 404 =200 /index.html;
            if (-f $request_filename/index.html) {
                rewrite (.*) $1/index.html break;
            }
            if (-f $request_filename.html) {
                rewrite (.*) $1.html break;
            }

            if (!-f $request_filename) {
                break;
            }
                }

    listen 443  ssl; # managed by Certbot
    ssl on;
    ssl_certificate /etc/letsencrypt/live/thunderjava.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/thunderjava.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
....

```

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
