### ISSUE TITLE
Behaviour of Outputs change when rewriting an UpgradeComponent as a pure Angular component

### ISSUE THREAD

**Issue by thesam** [angular/angular#26710]
First of all, thank you very much for Angular and the UpgradeModule!

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I am using an UpgradeComponent with an Output defined for the "&" binding in the AngularJS component. The AngularJS component wraps its output data in an $event object making it possible for other AngularJS components to use the syntax "trigger="$ctrl.onTrigger($event)"" to pass the data to a handler function.

However, when the same component is used as an UpgradeComponent, the output is always wrapped in an extra $event object. This means that Angular components must access the data with "$event.$event".

When the UpgradeComponent is eventually rewritten as an Angular component and uses EventEmitter.emit instead of wrapping in an $event manually, all Angular components that listen to the Output must also be modified since the API has changed. (The "outer" $event layer will disappear).

```
// Bindings in the AngularJS component
  bindings: {
    trigger: "&"
  }

// Emitting function in the AngularJS component
    this.onClick = () => {
      this.trigger({
        $event: 'World!'
      })
    }

// Usage in another AngularJS component
<old trigger="$ctrl.onTrigger($event)"></old>

// Usage in Angular component (workaround)

<old-upgraded (trigger)="onTrigger($event.$event)"></old-upgraded>

```

## Expected behavior
In my case it would be best if the UpgradeComponent could detect that the data is already wrapped in an $event object and just pass it along.

I could not find any examples in the upgrade guide (https://angular.io/guide/upgrade) on "best practices" for UpgradeComponents with Outputs when the original component is still being used by other AngularJS components. If everything is working as intended and I'm doing something incorrectly I would like to know. :)

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/q9pzkIEubvmZhM20q3NH?p=preview

## What is the motivation / use case for changing the behavior?
I want the usage of UpgradeComponents to be a seamless as possible, and other components should not have to be modified once the UpgradeComponent is rewritten as a pure Angular component.

## Environment

<pre><code>
Angular version: 6.1.10

Browser:
- [X] Chrome (desktop) version 69.0.3497.100

**Comment by mgechev** [comment]
Seems like a niche issue. I'll suggest to keep it outside the docs scope and leave it as an opportunity for community content.
