### ISSUE TITLE
Support Node 11

### ISSUE THREAD

**Issue by nj-op** [angular/angular#26725]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Angular supports up to Node 10. See [this blog](https://blog.angular.io/version-7-of-angular-cli-prompts-virtual-scroll-drag-and-drop-and-more-c594e22e7b8c) for the feature announcement.

## Expected behavior
Angular should be updated to support [Node 11](https://medium.com/@nodejs/october-brings-node-js-10-x-to-lts-and-node-js-11-to-current-ae19f8f12b51).

Others:
I didn't know Angular had to explicitly support Node versions. I was always using/updating my Node 10 installation on Angular 6 and no problems were ever encountered. What changed in Angular 7 to make such support "official" for Node 10? Will Node 11 work with Angular 7 or is there a possibility of issues and I should wait for "official" support in Angular?

**Comment by jdelman67** [comment]
Status update? No one ever answered the question in the post. Can I install Node 11 on my machine or am I restricted to the 10.x LTS series until support for 11 is added?

**Comment by manklu** [comment]
> No one ever answered the question in the post.

Maybe because it's a short-lived version? EOL date is June 2019
https://github.com/nodejs/Release#release-schedule

**Comment by az-copy45** [comment]
Node 12 is out now, issue for that one is [here](https://github.com/angular/angular/issues/30227).

What happened with Node 11 support? If it won't be added, someone should close this.

**Comment by mlc-mlapis** [comment]
@az-copy45 ... we use NodeJS 11.13.0 on Windows 10 and we don't have any problems.

**Comment by gcalison** [comment]
This should be closed, [Angular now recommends Node 12](https://stackoverflow.com/questions/56559152/why-does-angular-8-recommend-node-12).

**Comment by pkozlowski-opensource** [comment]
This is now obsolete / fixed.
