### ISSUE TITLE
ngForm conflicts with the input display

### ISSUE THREAD

**Issue by makbari** [angular/angular#26721]
## I'm submitting a semi-bug
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
The input text is connected to the name attribute when there is ngModel, so when you change the object in component, also other input with the same name. 
However the Object is not changing. So, this is only matter of input displays wrong value. 
(I know this is not the best way to work with forms, but I found it in old project, and it is consistent with new versions).

## Expected behavior
updating input should be independent of the input's name attribute.

## Minimal reproduction of the problem with instructions
[Link to reproduce the bug](https://stackblitz.com/edit/angular-pcdwdy)

## Environment

<pre><code>
Angular version: 7.0.0 and also older versions

Browser:
- [x] Chrome (desktop) version latest

For Tooling issues:
- Node version: 10.12.0
- Platform: MAC

Others:

</code></pre>

**Comment by kara** [comment]
@makbari This is actually working as intended, as this use case is not currently supported. If two inputs should be synced, they should share a name *and* a model. If you try to share the name and have two separate models, there isn't really a source of truth for determining the value of the form and they will conflict.
