### ISSUE TITLE
Router Navigate ['..', '..'] works differently from ['..']

### ISSUE THREAD

**Issue by thepian** [angular/angular#26720]
## I'm submitting a...

<code><pre>
[x] Bug report  
</code></pre>

## Current behavior

<code><pre>
navigate(['..'], {relativeTo: this.route});
</code></pre>

Works as expected going from `sites/map` to `sites`.

<code><pre>
navigate(['..','..'], {relativeTo: this.route});
</code></pre>

Goes from `sites/1234/overview` to `sites/`.

## Expected behavior

I haven't found a way to make it got to `sites`. 
Regardless, it seems to be inconsistent

## Minimal reproduction of the problem with instructions

```
export const sitesRouting = [
    { path: 'sites', component: SitesPageComponent, resolve: { SonataSessionGuard } },
    { path: 'sites/map', component: MapTileComponent, resolve: { SonataSessionGuard }, data: { closeTile: '..' } },
    {
        path: 'sites/assurance',
        component: AssuranceStateTileComponent,
        resolve: { SonataSessionGuard },
        data: { closeTile: '..' },
    },
    {
        path: 'sites/:id/:tab',
        component: SiteTileComponent,
        resolve: { SonataSessionGuard },
        data: { closeTile: '../..' },
    },
];
```

`closeTile` is used to navigate from the sites sub-view to the sites main-view

## What is the motivation / use case for changing the behavior?

Consistency.
Being able to move easily from sub-path to main-path.

## Environment

<pre><code>
Angular version: 5.2.11

Browser:
- [x] Chrome (desktop) version XX

For Tooling issues:
- Node version: 11  
- Platform:  Mac

Others:

We'd love to upgrade to v6, but are held back by migration of our build to WebPack 4 with the new plugins.

**Comment by jasonaden** [comment]
Can you please check this against the current version of Angular? We don't patch earlier versions other than for security reasons.

If you're still having the issue, you can create a new bug report but you need to include a running reproduction. Recommended to use StackBlitz.
