### ISSUE TITLE
Angular 7 Routing vs CanActivate ISSUE 

### ISSUE THREAD

**Issue by scv9** [angular/angular#26737]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Angular Router CanActivate
I've got  Main Router Config entry:
`{
        path: ':profileName',
        component: AdminLayoutComponent,
        canActivate: [ProfileExistenceGuard],
        loadChildren: './views/profile/profile.module#ProfileModule'
}`

ProfileExistenceGuard:
`export class ProfileExistenceGuard implements CanActivate {
  constructor(private router: Router, private profileService: ProfileService) {}

  canActivate(route: ActivatedRouteSnapshot): Observable<boolean> | boolean {
    const profileName = (
      route.paramMap.get("profileName") ||
      route.parent.paramMap.get("profileName")
    ).toLowerCase();
    console.log("Checking Profile Existence");
    if (
      profileName ===
      (this.profileService.viewProfile.getValue()
        ? this.profileService.viewProfile.getValue().profileName
        : null)
    ) {
      console.log("Profile Already Checked");
      return true;
    } else {
      console.log("Profile Not Checked Yet, Retrieving From DB");
      return from(
        this.profileService.getProfileByName(profileName).then(result => {
          if (!result.empty) {
            console.log("PROFILE EXISTS");
            result.forEach(item => {
              const profile = new Profile(item.data());
              profile.uid = item.id;
              this.profileService.viewProfile.next(profile);
            });
            return true;
          } else {
            console.log("PROFILE NOT EXISTS");
            this.router.navigate(["sessions/404"]);
            return false;
          }
        })
      );
    }
  }
}`

This are ProfileRoutes:
`export const ProfileRoutes: Routes = [
    {
        path: '',
        component: ProfileComponent,
        children: [
            {
                path: '',
                component: CardComponent,
            },
            {
                path: 'dashboard',
                canActivate: [AdminAuthGuard, ProfileExistenceGuard],
                loadChildren: '../dashboard/dashboard.module#DashboardModule',
            },
            {
                path: 'market',
                canActivate: [ProfileExistenceGuard],
                loadChildren: 'app/views/shop/shop.module#ShopModule',
            },
        ]
    },
    ];`

## Expected behavior
Should render CardComponent

## Minimal reproduction of the problem with instructions
I'm using Google Cloud Functions, either there or while running via node
App got stack when I try to route by "profileName" here:
`export const ProfileRoutes: Routes = [
    {
        path: '',
        component: ProfileComponent,
        children: [
            {
                path: '',
                component: CardComponent,
            },
            {
                path: 'dashboard',
                loadChildren: '../dashboard/dashboard.module#DashboardModule',
            },
            {
                path: 'market',
                loadChildren: 'app/views/shop/shop.module#ShopModule',
            },
        ]
    },
    ];`

More concrete here:
`{
                path: '',
                component: CardComponent,
            },`

Card component init, then after 60 sec I've got timeout.
Looking into Network log in Chrome debugger, I see that Waiting (TTFB) is the reason. So I've got no response from node.

Other routes, including child routes of "profileName/smth" are working fine.
So this is a problem, and it happens even with blank "CardComponent"

Problem disappears while removing canActivate: [ProfileExistenceGuard] from main route config

`{
        path: ':profileName',
        component: AdminLayoutComponent,
        canActivate: [ProfileExistenceGuard],
        loadChildren: './views/profile/profile.module#ProfileModule'
}`

I Guess this is not my fault, if it is, please say how to deal with it

## What is the motivation / use case for changing the behavior?
Motivation is to use SSR properly in Angular

## Environment

<pre><code>
Angular version: 7.0.0

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [X ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [X ] Safari (desktop) version XX
- [X ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.11.1
- Platform:  Mac

Others:
No
</code></pre>

**Comment by evankoehler** [comment]
I believe I am seeing this problem as well. We have canActivate and canActivateChild guarding our routes in the app.routing.module. The app tries to load, then stops throwing this error:
Error: StaticInjectorError[t]: 
StaticInjectorError(Platform: core)[t]: 
NullInjectorError: No provider for t!

When we remove the canActivate and canActivateChild, the app loads with no error.

Unfortunately, I can't point you to our repo, as it is private, but let me know if I can provide anything else to help.

**Comment by scv9** [comment]
Issue resolved by changing 
`return from(Promise<boolean>)` 

to 
```
return new Observable<boolean>(observer => {
observer.next(boolean)
})
```

**Comment by scv9** [comment]
No, Not working

**Comment by scv9** [comment]
Rewrited canactivate to
```
canActivate(route: ActivatedRouteSnapshot): Observable<boolean> {
    return new Observable<boolean>(observer => {
      this.profileService.checkProfileExists(route.paramMap.get("profileName").toLowerCase()).subscribe(exists => {
        if (exists) {
          console.log("PROFILE EXISTS");
          return observer.next(true);
        } else {
          console.log("PROFILE NOT EXISTS");
          this.router.navigate(["sessions/404"]);
          return observer.next(false);
        }
      });
    });
  }
```
and functions in profile service to 

```
checkProfileExists(profileName: string){
    return new Observable<boolean>(observer=>{
      this.getProfileByName(profileName).subscribe(profile=>{
        if(profile){
          observer.next(true)
        }else{
          observer.next(false)
        }
      })
    })

  }

  getProfileByName(
    profileName: string
  ): Observable<Profile | null>{
    return new Observable<Profile|null>(observer=>{
      this.profilesRef.where("profileName", "==", profileName).onSnapshot((qs=>{
        qs.docs.forEach((qds)=>{
          if(qds.exists){
            let profile = new Profile(qds.data())
            profile.uid = qds.id
            this.viewProfile.next(profile)
            observer.next(profile)
          }else{
            observer.next(null)
          }
        })
      }));
    })
  }
```

now it works. DONT KNOW WHY!

**Comment by scv9** [comment]
SOLVED
