### ISSUE TITLE
router.navigate to child route re-renders the calling parent component

### ISSUE THREAD

**Issue by Harisasghar** [angular/angular#26749]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[x] Other... Please describe: Unexpected behaviour
</code></pre>

## Current behavior
I have a parent and child route in my angular version 6 app. Parent route is called 'knowledgebase' and child route is 'topic/:id'. 
Routing looks like this:

`path: 'knowledgebase', component: KnowledgebaseComponent,
      children: [
          { path: 'topic/:topicid', component: TopicComponent},
          {path: 'topic/topics/new', component: NewTopicComponent}
]}`

knowledgebase component has 'router-outlet'. From knowledgebase component I navigate to topic route like this: `this.router.navigate(['topic', id], {relativeTo: this.activeRoute } );`. 
It re-renders the knowledgebase (parent) component itself (constructor and ngOnInit is called)and then renders the Topic (child) component afterwards!
I also tried: 
`this.router.navigate(['./topic', id], {relativeTo: this.activeRoute } );`
`this.router.navigate(['topic/' + id], {relativeTo: this.activeRoute } );`
`this.router.navigate(['./topic/' + id], {relativeTo: this.activeRoute } );`

All these have the same behavior. Why is this happening?

## Expected behavior

When I navigate to child route, it should only render the child component. Constructor and ngOnInit for parent should not be called!

## Environment
    "@angular/cdk": "^6.4.7",
    "@angular/common": "6.1.10",
    "@angular/compiler": "6.1.10",
    "@angular/core": "6.1.10",
    "@angular/forms": "6.1.10",
    "@angular/http": "6.1.10",
    "@angular/material": "^6.4.7",
    "@angular/platform-browser": "6.1.10",
    "@angular/platform-browser-dynamic": "6.1.10",

<pre><code>
Angular version: 6.1.10

Browser:
- [x] Chrome (desktop) version 69.0.3497.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 62.0.3
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4
- Platform:  Windows

Others:
</code></pre>

**Comment by phil773** [comment]
Are there any news?
I also look for a solution to skip the reload of a component after routing.

**Comment by Harisasghar** [comment]
> 
> 
> Are there any news?
> I also look for a solution to skip the reload of a component after routing.

No, I did not find any solution, maybe this is a bug? I just wrote my logic i a way that reload of parent does not cause any problems. I had to do some small workarounds, so not the best solution.

**Comment by Wheater** [comment]
Any update?

**Comment by Harisasghar** [comment]
> Any update?

Not that I know, you can test the latest angular version and try  to reproduce this bug. I am not using the newest Angular version and not on same project either.

**Comment by brijeshborad** [comment]
Hello, Is there any update regarding this issue? I am also facing same issue. When child routes are called, it is re-rendering parent component which causes some other problems. Is there any solution to prevent parent component to re-render while navigating through child routes?

**Comment by Harisasghar** [comment]
> Hello, Is there any update regarding this issue? I am also facing same issue. When child routes are called, it is re-rendering parent component which causes some other problems. Is there any solution to prevent parent component to re-render while navigating through child routes?
