### ISSUE TITLE
angular2.d.ts is missing info on rx, rx-lite, and es6-promise

### ISSUE THREAD

**Issue by yfain** [angular/angular#2674]
I've created a simple HelloWorld app in TypeScript/Angular 2 (alpha 27). Installed angular2.d.ts using the following command:

tsd query angular2 --action install

Then tried to compile it with tsc and got errors that the definitions for rs, es6-promise, and rx-lite are missing. After running manually the following commands the code started to compile fine:

tsd query rx --action install
tsd query rx-lite --action install
tsd query es6-promise --action install

The definitions from the above three files should be included in angular2.d.ts.

**Comment by mhevery** [comment]
Yes, we are aware that there are many things missing in the `.d.ts` file. We are reworking it to figure out the best way.

(Closing since this is a general statement, rather then something specific for us to track.)
