### ISSUE TITLE
Document `window.ng`, ng.coreTokens, and ng.probe()

### ISSUE THREAD

**Issue by epelc** [angular/angular#26752]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

`window.ng` is not documented and contains a few items.

`ng.probe()` some sort of component debugging?
`ng.coreTokens` contains appref, router, etc but they are just the classes instead of instances? Does this work with `ng.probe` somehow?

It is used for some debugging purposes and referenced by the augury docs. 

https://augury.rangle.io/pages/guides/architecture.html

## Environment

Angular version: 7.0.0

**Comment by lukaszprus** [comment]
Why is it not documented yet? What's the best source of information for all that `ng.` stuff?

**Comment by JoostK** [comment]
The `ng` namespace no longer includes `coreTokens` and `probe` in Ivy; all other methods that are available on `ng` [are documented here](https://angular.io/api/core/global).

**Comment by JoostK** [comment]
@aikidave I think it would be nice to have a link [to this reference page](https://angular.io/api/core/global) from somewhere in the docs (it's currently only reachable from [the API reference](https://angular.io/api)) but I can't quite find a good spot for it. Do you have suggestions for where to add this link?

**Comment by aikidave** [comment]
Would this topic be an appropriate location: https://angular.io/guide/testing-utility-apis?

**Comment by mgechev** [comment]
Our official recommendation is Angular DevTools https://angular.io/devtools. Let's keep this outside of the scope of the project for now.
