### ISSUE TITLE
`router.navigateByUrl` resolves `false` when hybrid with `ui-router`, previous version works

### ISSUE THREAD

**Issue by JounQin** [angular/angular#26757]
## I'm submitting a...

- [x] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
- [ ] Other... Please describe:

## Current behavior

`router.navigateByUrl` resolves `false` when hybrid with `ui-router`

## Expected behavior

navigate correctly

## Minimal reproduction of the problem with instructions

https://github.com/JounQin/ng-study/blob/angular-router/src/legacy/app.config.ts#L32

This function stops working after upgrading to `@angular/router@7.0.1`, unless wrapping it into a `setTimeout` function with about 100ms timeout delay.

## What is the motivation / use case for changing the behavior?

It's a regression.

## Environment

Angular version: 7.0.1

Browser:
- [x] Chrome (desktop) version 69.0.3497.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v11.0.0  
- Platform:  Mac 

Others:

**Comment by jasonaden** [comment]
@JounQin Thanks for the issue, however, this really needs a minimal reproduction, not a reference to an existing app. I'll close this issue as it doesn't have the reproduction, but if you find it's still an issue please follow the new issue template and create a *minimal* repro with exact steps to see this behavior.

If it's a regression, we will get it pulled in and fixed quickly.
