### ISSUE TITLE
Async pipe should be able to automatically handle change detection within *ngIf for rendering child components

### ISSUE THREAD

**Issue by selipso** [angular/angular#26762]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

In dev mode, using async pipe with an observable used for conditionally rendering a child component throws an `ExpressionChangedAfterItHasBeenCheckedError`

Considering the async pipe is the recommended and preferred method to use with async operations, maybe this issue should be automatically handled by it under the hood.

## Expected behavior

Async pipe should be able to automatically handle change detection for child components when an observable has been updated without having to manually call `ngDoCheck()` or do any of the other infamous workarounds resembling Angular 1 and its digest cycle.

## Minimal reproduction of the problem with instructions

Original repro posted here: 
https://github.com/angular/angular/issues/16921#issuecomment-394411827

My own fork of the original user's StackBlitz: 
https://stackblitz.com/edit/angular-async-change-detection-error-ebo1uw

## What is the motivation / use case for changing the behavior?

Conditionally rendering child components based on the value of a boolean observable.

## Environment
Angular version: ~6.1.10

**Comment by manklu** [comment]
```javascript
// throws an ExpressionChangedAfterItHasBeenCheckedError error
this.updateBoolean();
```
You change the value *during* change detection. Even if you don't get an exception chances are good that it won't work as expected.

```javascript
// doesn't throw an error ExpressionChangedAfterItHasBeenCheckedError
setTimeout(() => {
    this.updateBoolean()
}, 0)
```
Here you are change the value *after* the change detection cycle. Alternatively you could use

```javascript
Promise.resolve()
  .then(_ => this.updateBoolean())
```

**Comment by selipso** [comment]
Ok, so shifting the update code to the constructor or to a different lifecycle hook like `ngAfterViewInit()` would also prevent this. It makes sense, I'm just wondering if there's a way to handle this common situation within the async pipe like by adding the equivalent of a debounceTime of 0? I think it would go a long way towards preventing this confusing error from appearing with many developers.

**Comment by manklu** [comment]
@selipso
> then changes triggered by the child have the potential to affect the parent

This is no problem as long as you don't dispatch actions during change detection. 

It should be possible to implement a meta-reducer to detect such actions an log an error.

**Comment by ChrisDahmCS** [comment]
@selipso is that stackblitz supposed to show the issue? I'm not seeing it- sorry.

**Comment by selipso** [comment]
@ChrisDahmCS Updated the Stackblitz to reflect a clearer variation on the issue including the async pipe.

**Comment by ChrisDahmCS** [comment]
@selipso I seem to be able to solve the issue by keeping the observables and behaviorsubjects in the service and passing the observables via async pipe that way. 

Service:
```
import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs/internal/BehaviorSubject';

@Injectable({
  providedIn: 'root'
})
export class BooleanService {
  myProp = new BehaviorSubject<boolean>(true);
  nameProp = new BehaviorSubject<string>('Angular 7');

  myProp$ = this.myProp.asObservable();
  nameProp$ = this.nameProp.asObservable();

  constructor() { }
}
```

App Component ts:
```
import { Component } from '@angular/core';
import { BooleanService } from './boolean.service';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  name = 'Angular 6';

  constructor(
    public service: BooleanService
  ) { }

  useSix() {
    this.service.nameProp.next(this.name);
    this.service.myProp.next(false);
  }
}
```

App Component HTML:
```
<p *ngIf="service.myProp$ | async">
  boolean is true
</p>
<button (click)="useSix()">Use v6</button>
<app-child *ngIf="(service.nameProp$ | async) === 'Angular 7'"></app-child>
```

Child Component: unchanged - but tested with your method in the init, no issue.

I believe the reason this works is because the view is not updating itself since the source of truth is in the service now- but you can read a lot more on it [here](https://blog.angular-university.io/angular-debugging/) and [here](https://blog.angularindepth.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4).

**Comment by selipso** [comment]
Ah ok, I think the misunderstanding in this situation came from the way `.asObservable()` works in BehaviorSubject. I guess it creates a new reference to the underlying observable rather than returning some internally cached value. Thanks for the explanation and solution @ChrisDahmCS. Closing this since there is an acceptable workaround built-in already.
