### ISSUE TITLE
Angular service Worker will  not work in some situation rendered by express / hapi.js

### ISSUE THREAD

**Issue by 100cm** [angular/angular#26772]
First, this is not an Angular service worker self's problem  , but its related to Angular service Worker

I write this just for someone have the same problem or same doubt

Angular Version: 7.0.0

Cli Version :7.0.2

Node server : express / hapi / http-server

server code:

```
const Path = require('path');
const Hoek = require('hoek');
const fs = require('fs');
const yaml = require('js-yaml');
let env = process.env.NODE_ENV || 'dev'
var config = require('./config.json')[env];
var ngsw_json = require('./dist/ngsw.json')
var crypto = require('crypto');
var proxy = require('express-http-proxy');
// export NODE_ENV=dev && node site-init.js

const express = require('express')
const app = express()
const port = config.port || 4200
app.use(express.static(__dirname + '/dist', {
  'index': false
}))
app.set('views', Path.join(__dirname, 'dist'));
app.engine('html', require('ejs').renderFile);
app.set('view engine', 'html');


// set proxy
app.use('/uploads', proxy(`${config.api_host}:${config.api_port}`, {
  parseReqBody: false,
  proxyReqPathResolver: (req) => {
    console.log(req.url)
    return "/uploads" + req.url
  }
}));

app.get('*', (req, res) => {
  let host = req.hostname
  let param = req.originalUrl
  let project = {}
  console.log(req.url)
  res.setHeader('Cache-Control', '99999')
  res.render(config.index || 'index', {
    project_title: project.name,
    favicon: favicon,
    desc: desc,
    keyword: keyword,
    cdn: cdns[env] || '',
  })

})


app.listen(port, () => console.log(`app listening on port ${port}!`))
```

**Pay attention to the proxy config**

AppModule :

`  ServiceWorkerModule.register('/ngsw-worker.js', {enabled: environment.production}),`

And other configs were the default that cli generated

As the example , I want to serve my application by express  or other node.js server , and  all  **uploads** request proxy to my api server port

Just same as Nginx proxy_pass config .

But by my test .

I found a interesting problem:

If  I Add the proxy to express  (not only express ,hapi will too)

proxy code
```
app.use('/uploads', proxy(`${config.api_host}:${config.api_port}`, {
  parseReqBody: false,
  proxyReqPathResolver: (req) => {
    console.log(req.url)
    return "/uploads" + req.url
  }
}));
```

**ngsw-worker.js will not load and  install**

you must add other line when angular app bootstrap in ***main.ts***

` navigator.serviceWorker.getRegistration().then(active => !active && navigator.serviceWorker.register('/ngsw-worker.js')).catch(console.error);`

and then rebuild your app ,the ngsw-worker.js will work fine.

I have tried 3 ways to start up my application  (http-server,hapi,express)

If only I setup the proxy config, the problem will occurred

I think my other issue last year may related to this.  #21198

Just  share my discovery.

**Comment by gkalpak** [comment]
Thx for sharing your experience (although, tbh, I don't see how the server config can affect the SW registration).
I'm going to close this, since it is not actionable (afaict).
