### ISSUE TITLE
Reactive form inside virtual scroll list problem

### ISSUE THREAD

**Issue by fahadmajeed** [angular/angular#26781]
Hi Angular team,
I was checking virtual scroll list with reactive forms. Scenario is that i have thousands of rows to show 
in a list with checkboxes to approve or disprove. 
So inside virtual list i am generating form group with [formGroupName]="i". 
But if i check one checkbox, while scrolling it randomly selects and checks other checkboxes too. 
This is really weird. 
Any advice or tips would be helpful. Thanks

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: 7.0.0

Browser:
- [x] Chrome (desktop) version XX
- [x ] Firefox version XX
- [ x] Safari (desktop) version XX
- [x] IE version XX

 </code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by fahadmajeed** [comment]
OK thanks
