### ISSUE TITLE
Error on sanitizing resource url

### ISSUE THREAD

**Issue by armaserg** [angular/angular#26782]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Error is throwing when I'm trying to sanitize unsafe resource url (for iframe src)

## Expected behavior

unsafe resource url should be sanitized to safe string

## Minimal reproduction of the problem with instructions

this.sanitizer.sanitize(SecurityContext.RESOURCE_URL, 'data:text/html,<script>alert(1)</script>') throws error
https://stackblitz.com/edit/angular-9zjuc7

## What is the motivation / use case for changing the behavior?

URL provided by user should be used as src for iframe

## Environment

<pre><code>
Angular version: 7.0.1

**Comment by chaosmonster** [comment]
Lookint at your stackblitz the expected xss attack seems legit. Because you try to add a script tag in an url. Looking at this [switch case](https://github.com/angular/angular/blob/cf0968f98e844043a0f6c2548201f3c0dfd329a7/packages/platform-browser/src/security/dom_sanitization_service.ts#L169)  I think the `SafeResourceUrl`service might be more helpful.

**Comment by trotyl** [comment]
It's by design, `SecurityContext.RESOURCE_URL` is meant for application data (like JSON files), the sanitization would always break application logic, so an explicit error must be throw. Otherwise you should use `SecurityContext.URL` instead which will just print warning.

**Comment by trotyl** [comment]
The only point is whether you expect an untrusted URL to break the application, and the only purpose for `RESOURCE_URL` to exist is for throwing that error explicit.

**Comment by chaosmonster** [comment]
The documentation says to use `bypassSecurityTrustResourceUrl` for `<ifrmae>` your stackblitz uses `DomSanitizer.sanitze`

**Comment by armaserg** [comment]
bypassSecurityTrustResourceUrl can't be used for data provided by users.

With SecurityContext.URL it works, but not sure does it work really correct... It leaves whole unsafe string and prefix it with "unsafe:" (good thing: alert(1) doesn't execute)

https://stackblitz.com/edit/angular-n7pwhf (chaosmonster try to uncomment commented line and you'll see that simple bypassSecurityTrustResourceUrl is not sulution)

**Comment by trotyl** [comment]
@armaserg The entire idea of URL sanitization is making it an invalid URL that will not work anyway, there's no strip-some-part option.

**Comment by armaserg** [comment]
ok. in this case it works correct.
so, is `this.sanitizer.bypassSecurityTrustResourceUrl(this.sanitizer.sanitize(SecurityContext.URL, this.iframeSrcProvidedByUser))` only option in my situation?

**Comment by trotyl** [comment]
The `Sanitizer` service is only designed for template binding in Angular, not your application logic. And if you do use it in application logic, then you can just report error about the vulnerable URL to user and stop processing, rather than pass the already known-vulnerable URL to Angular again.

**Comment by armaserg** [comment]
Ok. But why does it automatically sanitize src for image but throws error for iframe src?
https://stackblitz.com/edit/angular-n7pwhf

**Comment by trotyl** [comment]
That’s the role of `RESOURCE_URL`, it’s considered a critical path of the application, so Angular would never cause an incomplete application by implicit sanitization, but let you know it must be handled by developers.

**Comment by armaserg** [comment]
ok. thanks...
