### ISSUE TITLE
Imported json file as indexed type always giving undefined when Angular is not running in production mode

### ISSUE THREAD

**Issue by pnguyen9** [angular/angular#26785]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Imported json, when used as an indexed type/as a Map<key, value> variable, is always giving "undefined". 

## Expected behavior
It should return the expected value, instead of "undefined" for everything. 

## Minimal reproduction of the problem with instructions
The following is a stackblitz demo link: 
https://stackblitz.com/edit/angular-h2aspf?file=tsconfig.json

If you run it on the browser, it will work properly (the console will properly display "Change language"). 

However, if you download it and run it locally, you will notice that the console will display "undefined" instead.

To run it locally:

    Download and unzip the stackblitz demo in a folder
    Run npm i in the project folder
    Run ng serve and notice the "undefined" output in the web browser console
    Run again with ng serve --prod, and notice the "Change language" output in the web browser

## What is the motivation / use case for changing the behavior?
There's no reason it should only work in production mode. 

## Environment

<pre><code>
Angular version: 7.0.2

Browser:
- [x] Firefox version 63
 
For Tooling issues:
Node (node --version): v9.11.1
npm (npm --version): v5.6.0
Angular CLI (ng --version): 7.0.2

Others:
OS: Debian GNU/Linux 8 (jessie)
Package manager: npm
IDE: VSCode
I've also opened an issue on the Angular CLI project: https://github.com/angular/angular-cli/issues/12781
</code></pre>

**Comment by pkozlowski-opensource** [comment]
It sounds like `import * as resources from '../assets/resources/ResourcesBundle.json';` is not supported in prod mode - please open in https://github.com/angular/angular-cli

**Comment by pnguyen9** [comment]
It's weird, because the example I gave is working only when I do run in prod mode. When I run the ng serve command without the prod parameter, it doesn't work. 

Otherwise, I did open an issue on Angular CLI, though the link enclosed to the original post wasn't very visible: https://github.com/angular/angular-cli/issues/12781
