### ISSUE TITLE
Internal Error while in watch mode when I change the template

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#26780]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I get the following Internal Error:
https://github.com/angular/angular/blob/9993c723359dad79e1162ec728572f7f6c817f5c/packages/compiler-cli/src/transformers/program.ts#L729

In a component, I move around `<ng-content>` nodes.
In particular, I have one catch-all `<ng-content></ng-content>` and one with a selector `<ng-content select=".some-class"></ng-content>`. When I change the order in the template while in webpack watch mode, the error is shown on the console.

## Expected behavior
No error.

## What is the motivation / use case for changing the behavior?

To have no error.

## Environment

<pre><code>
Angular version: 7.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.12.0  
- Platform:  Windows 

Others:

</code></pre>

**Comment by Tragetaschen** [comment]
Correct. I just changed some text within a `<div>` and got the error output

**Comment by errorx666** [comment]
Does this error need to be fatal?  I get a working build when I suppress the error.  Maybe a warning is more appropriate.

**Comment by ljupcospeci** [comment]
+1, experiencing the same issue. Any news?

**Comment by mattneel** [comment]
+1, same here. This is preventing me from pushing a new version to prod...

**Comment by thesam** [comment]
In my case it seems the problem disappeared when I upgraded from Node 8 to Node 10.

**Comment by errorx666** [comment]
I still have this issue persistently in Node 10 and 11.

**Comment by errorx666** [comment]
Since this issue occurs every time I do a `yarn install`, I've put a `postinstall` script in my `package.json` that calls the following gulp task:
```js
gulp.task( 'patch:fix-angular-issue-26780', async () => {
	const fs = require( 'fs' );
	const path = require( 'path' );
	const { promisify } = require( 'util' );
	const target = path.resolve( __dirname, 'node_modules', '@angular', 'compiler-cli', 'src', 'transformers', 'program.js' );
	const src = await promisify( fs.readFile )( target, 'utf8' );
	const pattern = /^\s{0,3}(\s*throw new Error\(\s*"Internal error: The structure of the program changed during codegen."\s*\);)$/mi;
	const dest = src.replace( pattern, '/* $1 */' );
	if( src === dest ) return;
	await promisify( fs.writeFile )( target, dest, 'utf8' );
} );
```

**Comment by alxhub** [comment]
@Tragetaschen good news and bad news.

The good news is, this should not be an issue in Angular 9 + Ivy.
The bad news is that Ivy is the fix, it won't be fixed in View Engine, so you'll have to upgrade to avoid the bug.

I'm going to close this issue as resolved.
