### ISSUE TITLE
Angular input validation not in sync with HTMLInputElement validity

### ISSUE THREAD

**Issue by PRR24** [angular/angular#26787]
## I'm submitting a...
<pre><code>
[X] Bug report  
</code></pre>

## Current behavior
Angular FormControl.valid is true even though HTMLInputElement.checkValidity() returns false

## Expected behavior
Angular validity check should be equal or more restrictive than native one, eg
- if HTMLInputElement is not valid, FormControl should always be not valid
- if HTMLInputElement is valid, FormControl may be not valid because of additional validators.

## Minimal reproduction of the problem with instructions
```
<form novalidate>
    <input #test #testModel="ngModel" type="number" name="test" ngModel>
    <div>Native: {{ test.checkValidity() }} Angular: {{ testModel.valid }}</div>
</form>
```
Enter "asdf" in the input
Expected: Native and Angular should both display false
Actual: Native displays false, Angular displays true

## What is the motivation / use case for changing the behavior?
Consistent input validation. Currently entering "10,000,000" in numeric field renders to null value through ngModel (parseFloat) binding and user gets no error feedback.

## Environment

<pre><code>
Angular version: 4 .. 7

Browser:
- [X] Safari 12
- [X] Firefox 62

**Comment by PRR24** [comment]
To work around the issue, one can use better/different ControlValueAccessor. For simpler use cases, simple workaround would probably be sufficient:
```
@Directive({
    selector: "input[type=number][ngModel]",
    providers: [
        { provide: NG_VALIDATORS, useExisting: forwardRef(() => NativeValidator), multi: true }
    ]
})
export class NativeValidator implements Validator {

    constructor(
        private element: ElementRef
    ) {
    }

    validate(c: AbstractControl): ValidationErrors {
        if (!this.element.nativeElement.checkValidity()) {
            return { native: true };
        }
        return null;
    }
}
```

**Comment by thw0rted** [comment]
I'm still reading issues (there are a lot of them!) but I don't understand why this isn't built-in behavior.  "Native element is invalid" *should* be an error case for all template form controls, out of the box, automatically.  The exact example you posted -- where `test.validity.valid` is false but `testModel.valid` is true -- should never happen.

Is there a good argument against adding a default validation to all `NgModel.control` instances exactly like this?

**Comment by thw0rted** [comment]
Also, trackbacks to #16352, #17491, #23635.
