### ISSUE TITLE
Empty css file import (from Component SyleUrls) when file begins with block comment.

### ISSUE THREAD

**Issue by me-sha** [angular/angular#26798]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Imported css style sheet is empty when it begins with a block comment /**/
when imported with Component StyleUrls attribute.

## Expected behavior

Original content of css style sheet file is imported.

## Minimal reproduction of the problem with instructions

Import css style sheet file via StylesUrl attribute in component.
Add block comment at the begining of the file (first line) e.g.: `/**/`
Observe in browser dev tools imported style sheet is empty.

## Environment

<pre><code>
Angular version: 7.0.1 

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x] Firefox version 63
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10  
- Platform: Linux, Arch 
Others:

</code></pre>

**Comment by manklu** [comment]
Works for me

https://stackblitz.com/edit/angular-1sskeq?file=src%2Fapp%2Fapp.component.css

**Comment by me-sha** [comment]
Tried to reproduce on stackblitz as well but no cigar. So problem must be related to version update. maybe caching issue? Cant think of anything else. Guess I close this. Thanks for your time @manklu.
