### ISSUE TITLE
Support stylesheet bindings

### ISSUE THREAD

**Issue by chris13524** [angular/angular#26800]
## I'm submitting a...
    [x] Feature request

I suggest that you should be able to use the `{{}}` syntax in component stylesheets.

Currently, in order to get some degree of style bindings, you have to use the style attribute in the template:

    [style.color]="abc"

While this works for most styles, it does not work for cases where you want to style a `:before` or make use of `host-context`.

The only way to accomplish this currently, is to use [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables), but these have their own issues in Angular (see #9343) and also lack browser support.

**Comment by chris13524** [comment]
One way to accomplish this is to interact with [`document.styleSheets`](https://www.w3.org/wiki/Dynamic_style_-_manipulating_CSS_with_JavaScript). Something like this: `document.styleSheets[6].cssRules[0].style.color = "green"`

An issue to consider is that stylesheets are designed to work generically across all instances of a component. So changing a property in a rule in the stylesheet would change the style for all instances of the component, not just one. To fix this, there would need to be duplicates of each rule with some sort of selector to scope it to one particular instances of the component. This could utilize `CSSStyleSheet.insertRule()` and `CSSStyleSheet.deleteRule()`.

**Comment by Frimlik** [comment]
Any update of this issue? I added a comment to [#7251](https://github.com/angular/angular/issues/7251) as well, but without any reaction.
Thanks.
