### ISSUE TITLE
Cannot use class decorators with AOT compilation

### ISSUE THREAD

**Issue by emilio-martinez** [angular/angular#26808]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
It seems class decorators cannot be processed with Angular's AOT compilation. In the past, I've read issues where this was related to issues between barrel files and static resolution, but I've done a series of tests without success with [`@polymer/lit-element`](https://github.com/Polymer/lit-element), and can't seem to successfully compile.

## Expected behavior
To be able to AOT compile a project while using class decorators other than those provided by Angular.

## Minimal reproduction of the problem with instructions
I've created a project in Stackblitz that easily shows this issue: https://stackblitz.com/edit/angular-bug-26808-q48xsb.

Of course, Stacblitz doesn't AOT, but this can be reproduced by clicking the download button, installing depdendencies (via npm, yarn, or other), and then `npx ng build --prod`. Below is the output I get:

```sh
➜ npm i --silent 
[fsevents] Success: "/angular-bug-26808-q48xsb/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
Cached binary found at /Users/username/.npm/node-sass/4.9.3/darwin-x64-57_binding.node
Binary found at /angular-bug-26808-q48xsb/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine
added 1165 packages from 1173 contributors and audited 39127 packages in 22.075s
found 0 vulnerabilities

➜ npx ng build --prod
                                                                                     
Date: 2018-10-28T23:09:34.055Z
Hash: 530e6c8dad9fa61c4815
Time: 4976ms
chunk {0} runtime.ec2944dd8b20ec099bf3.js (runtime) 1.44 kB [entry] [rendered]
chunk {1} main.9868d9b237c3a48c54da.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills.85f47f0bf59079cbc23a.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} styles.5413946c31efe8ce9712.css (styles) 0 bytes [initial] [rendered]

ERROR in app/lit-component.ts(3,2): Error during template compile of 'MyElement'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler in 'customElement'
    'customElement' references 'customElement'
      'customElement' is not initialized at ../@polymer/lit-element/lib/decorators.ts(37,22).
```

If I modified the project to avoid the barrel file, i.e:

```ts
import { LitElement, html, property } from '@polymer/lit-element';
import { customElement } from '@polymer/lit-element/lib/decorators';
```

The only difference is I don't get the `'customElement' references 'customElement'` line.

## What is the motivation / use case for changing the behavior?
In the example above, I could setup a separate build pipeline to build by web components and then include them in Angular, but that just seems like a waste of time... and would likely force me off of the Angular CLI which is perhaps even worse.

In this case, even `@polymer/lit-element` is built on typescript and exports it's entire definitions, so my assumption would be that Angular's compiler should have all it needs to statically resolve anything it requires.

## Environment

<pre><code>
Angular CLI: 7.0.3
Node: 8.11.4
OS: darwin x64
Angular: 7.0.1
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.3
@angular-devkit/build-angular     0.10.3
@angular-devkit/build-optimizer   0.10.3
@angular-devkit/build-webpack     0.10.3
@angular-devkit/core              7.0.3
@angular-devkit/schematics        7.0.3
@angular/cli                      7.0.3
@ngtools/webpack                  7.0.3
@schematics/angular               7.0.3
@schematics/update                0.10.3
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1
</code></pre>

**Comment by JoostK** [comment]
This has been fixed by Ivy. Libraries that want to use this require `strictMetadataEmit` to be disabled, as it would otherwise still produce this error.

**Comment by emilio-martinez** [comment]
So how was this actually fixed? Isn't opting out of strict metadata kind of counter-intuitive? Is this recommendation documented anywhere, or how would people even know?

**Comment by JoostK** [comment]
@emilio-martinez good question. As of this moment, libraries still have to be published using the old compiler, which means that metadata is still produced. When consuming the library in Ivy however, this metadata is not used at all. Therefore, any metadata errors wouldn't be of relevance in Ivy.

I do agree that opting out of `strictMetadataEmit` may be undesirable if the library continues to offer support for ViewEngine (the old renderer), which I expect is probably the case. It would mean that the `lit-element` occurrences would cause the metadata to have errors, which could potentially mean that an application doesn't compile if it ends up needing that metadata. Even worse perhaps is the ability to introduce new errors that you wouldn't be aware of.

So I think the main question is whether you accept the risk of potential compilation errors in ViewEngine applications (if `strictMetadataEmit` is disabled you wouldn't be aware of the errors) versus allowing Ivy consumers to benefit from AOT compilation together with `lit-element`.

You are correct that documentation on this subject is very lacking at the moment. All AOT related documentation is still targeting the metadata system, the way it works in Ivy has not yet been documented.

If you feel it would be better for this issue to remain open, perhaps for visibility, I am okay with reopening. Or, if you need more info please ask.
