### ISSUE TITLE
github-pages deployment instructions are not working

### ISSUE THREAD

**Issue by sasidhar** [angular/angular#26803]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
- Followed instructions at: https://angular.io/guide/deployment#deploy-to-github-pages
- After deploying, the URL contains a duplicate of project name.
- Built files are throwing console errors.
- No changes were made after generating the files using angular CLI
- Repo URL: https://github.com/sasidhar/ng-cli-test
- Github Pages URL: https://sasidhar.github.io/ng-cli-test
- Check screenshot for the bugs
![github-pages-issue](https://user-images.githubusercontent.com/897339/47610618-1d410d80-da0e-11e8-9388-965dec9d51f7.png)

## Expected behavior
- Built files run without any console errors
- URL should not contain duplicate project name

## Minimal reproduction of the problem with instructions

Followed instructions in the Angular documentation

## Environment

<pre><code>
Angular version: 7.0.1

Angular CLI Version: 7.0.3
Refer attached screenshot
<img width="650" alt="ng-cli" src="https://user-images.githubusercontent.com/897339/47610626-7741d300-da0e-11e8-8f94-681b56655e5c.png">

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.4  
- Platform:  Mac

Others:

</code></pre>

**Comment by snerks** [comment]
Have you tried this slightly different command (note backslash characters surrounding <project_name>):

`ng build --prod --output-path docs --base-href \<project_name>\`

**Comment by sasidhar** [comment]
@snerks It worked. Thanks!
