### ISSUE TITLE
WebStorm 2018.2.25 Error:Initialization error (angular 2 language service). Cannot read property 'CommandTypes' of undefined

### ISSUE THREAD

**Issue by littleOStar** [angular/angular#26814]
## I'm submitting a...

<pre><code>
[ ] Other... Please describe: WebStorm 2018.2.5 -> TypeScript Errors 
</code></pre>

## Current behavior

Error:Initialization error (angular 2 language service). Cannot read property 'CommandTypes' of undefined

## Environment

<pre><code>
Angular version: 7.0.3

Browser:
- [ ] Chrome (desktop) version 版本 70.0.3538.77（正式版本） （64 位）

 
For Tooling issues:
- Node version: 8.12.0
- Platform:  Windows 

Others:

System: Windows 10 1803 17134.376
Tool: WebStorm 2018.2.5
</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by littleOStar** [comment]
solved，
https://stackoverflow.com/questions/52967980/typescript-initialization-error-in-webstorm-after-update-to-angular-7
