### ISSUE TITLE
 Handle 400 Bad Request From WebApi In Angular 6

### ISSUE THREAD

**Issue by Bigbhardwaj** [angular/angular#26817]
Below is an Asp.net Core WebAPI which returns bad request with Error details as its param when let's say duplicate a user is trying to register.
![image](https://user-images.githubusercontent.com/9026778/47654129-2ff34800-dbb0-11e8-8a0c-ab9be2ddcfe9.png)

The response is being handled at Angular side as follows:
**user.service.ts**

![image](https://user-images.githubusercontent.com/9026778/47654276-6f219900-dbb0-11e8-9018-7d0617482ffa.png)

above method being called out in:
register.component.ts

![image](https://user-images.githubusercontent.com/9026778/47654334-95473900-dbb0-11e8-8ee5-fae566c1f8fe.png)

When I tried to do Postman I get perfect result as below (with error description):

![image](https://user-images.githubusercontent.com/9026778/47654586-20283380-dbb1-11e8-918f-bf189d862f16.png)

But the same result despite trying multiple code snippet doesn't work out and all it log 'Bad result' as response.

![image](https://user-images.githubusercontent.com/9026778/47654447-d50e2080-dbb0-11e8-9a45-9c666b5dc4ca.png)

What's am I missing here ?

**Comment by aledpardo** [comment]
All responses from 4xx HTTP status HTTPClient throws as error. You should add in the pipe the catchError operator to handle the response there.

**Comment by Bigbhardwaj** [comment]
Same result :(
![image](https://user-images.githubusercontent.com/9026778/47663376-d8120c80-dbc2-11e8-8b1a-ed7f268a07c2.png)

I did notice though the response lies in network tab..  just short of an idea to process and show it at UI.

![image](https://user-images.githubusercontent.com/9026778/47663475-20312f00-dbc3-11e8-9ced-6e61339a5244.png)

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Bigbhardwaj** [comment]
Did it.. any suggestion ?
https://stackoverflow.com/questions/53045081/handle-400-bad-request-from-webapi-in-angular-6

**Comment by Bigbhardwaj** [comment]
Did it.. any suggestion ?
https://stackoverflow.com/questions/53045081/handle-400-bad-request-from-webapi-in-angular-6

**Comment by shekarreddyb** [comment]
I have faced similar issue, verify if you have any interceptors that are changing the error response. one of my interceptor was re throwing error using throwError with error message inside catchError
