### ISSUE TITLE
gulp serve.js.prod can not be interrupted

### ISSUE THREAD

**Issue by vicb** [angular/angular#2681]
Seems like there is no way to exit this task (other than killing gulp).

Please restore support for Ctrl + C

**Comment by mhevery** [comment]
did you try `ctrl + \` That one does it for me, but I agree it should support `ctrl + c` as well.

**Comment by mhevery** [comment]
I am going to close this as there is a work around, and it seems like no one is working on it. Reopen if you feel otherwis.

**Comment by vicb** [comment]
out of date
