### ISSUE TITLE
Problem with path img in production build

### ISSUE THREAD

**Issue by uulgie** [angular/angular#26813]
## Hello everyone i've problem with path images in building

When i run my app in local all images work : 
```
http://localhost:4200/
```

```html

<section class="bg-light p-5">
  <img width="400" src="../../assets/img/bg.jpg" alt="">
</section>

```
## Build --prod

> All path images not working

<a href="https://i.suar.me/P0naQ/l">
    <img src="https://i.suar.me/P0naQ/l" width=1012 height=172>
  </a>

## Folder dist

> index.html file and the assets folder in the same root

### How can i remove all this  on build
```
../../
../../../
```

```html
 Example path correct

<section class="bg-light p-5">
  <img width="400" src="assets/img/bg.jpg" alt="">
</section>

```
## home.component.html
  <a href="https://i.suar.me/my671/l">
    <img src="https://i.suar.me/my671/l" width=540 height=720>
  </a>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by auqfyanjun** [comment]
1 : <img src = '/assets/img/bg.jpg' >    
2: You need to set the path of your server's static resources to assets.

**Comment by auqfyanjun** [comment]
1 ： src = "/assets/img/bg.jpg"
2 : You need to set the path of your server's static resources to   assets.

**Comment by uulgie** [comment]
> 1 ： src = "/assets/img/bg.jpg"
> 2 : You need to set the path of your server's static resources to assets.

```
http://localhost:4200/assets/img/bg.jpg
but on dev don't work
```

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
