### ISSUE TITLE
FakeAsync swallows exceptions 

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#2682]
I think an uncaught exception should fail a fake async test.

For instance, the following test should fail:

```
it("should work with single fields", inject([TestBed], fakeAsync((tb: TestBed) => {
  new Promise(() => {throw "BOOM"});
  tick();
});
```

Otherwise, we have to use AsyncTestCompleter even in fake async tests.

/cc @vicb

**Comment by vicb** [comment]
An "regular" async test using `AsyncTestCompleter` would also fail (to fail) here (see #864).

TL;DR: there is no consistent/specified way to catch a rejected Promise in JS.

My current thinking is to add more expectations:

`expect(p).willResolve((res) => void)`;
`expect(p).willReject((res) => void)`;

Still that will be opt-in.

/cc @pkozlowski-opensource @rkirov @juliemr

**Comment by vicb** [comment]
I have the approach described in my previous comment.

One problem is that `fail()` will be called asynchronously. It should not be an issue with `fakeAsync` but it is with the `AsyncTestCompleter`: if `async.done()` is called before the promise is settled, the `expect`ation is ineffective. One solution could be that `willXXX` expectation delay the `done()` until promises are settled. I'll try this next.

**Comment by mhevery** [comment]
Is this still an issue, or can this be closed?

**Comment by pkozlowski-opensource** [comment]
Yep, unfortunatelly this is still a pb and quite a pesky one, since it really slows down developer flow when doing TDD on async tests....

**Comment by vicb** [comment]
fixed
