### ISSUE TITLE
Documentation of Routing chapter for Tour of Heroes outdated / wrong.

### ISSUE THREAD

**Issue by daniel-de-wit** [angular/angular#26824]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Following instructions from the [Routing chapter of the Tour of Heroes Tutorial](https://angular.io/tutorial/toh-pt5) it says:

```
ng generate module app-routing --flat --module=app
```

Which is supposed to create a single file called `app-routing.module.ts` directly inside the `src/app` directory ( I think ).

However, the CLI gives warnings about the flags being unsupported and creates a folder `src/app/app-routing` with a `app-routing.module.ts` file in it.

Output cli:
```
The option '--flat' is not registered with the generate command. Run `ng generate --help` for a list of supported options.
The option '--module' is not registered with the generate command. Run `ng generate --help` for a list of supported options.
```

Please update the documentation, this is slightly confusing for a newcomers like me.

Thank you.

## Expected behavior

```
ng generate module app-routing --flat --module=app
```

Would create a file: `src/app/app-routing.module.ts` as explained by the surrounding documentation.

## Minimal reproduction of the problem with instructions

```
ng new angular-tour-of-heroes

ng generate module app-routing --flat --module=app
```

## What is the motivation / use case for changing the behavior?
Documentation does not reflect the actual CLI options.

## Environment

<pre><code>
angular-cli: 1.0.0-beta.28.3
node: 10.12.0
os: darwin x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/compiler-cli: 2.4.10

**Comment by brandonroberts** [comment]
@daniel-de-wit from your environment information, it looks like all your dependencies are extremely out of date. Have you tried installing the latest version of the CLI and related dependencies?

**Comment by daniel-de-wit** [comment]
@brandonroberts You are absolutely right. Seems I installed the old CLI version instead of `npm install -g @angular/cli`.

Thanks for the help!
