### ISSUE TITLE
Path "/src/app/app.module.ts" already exist.

### ISSUE THREAD

**Issue by MohammedKhalid96** [angular/angular#26836]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
'
when i try to create a new angular project using this command ( ng new project-name ), it gives me that error ( Path "/src/app/app.module.ts" already exist ).

## Environment

<pre><code>
Angular version: angular/cli@7.0.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.6.0  
- Platform:  Windows 

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Please open angular-cli issues in its repo https://github.com/angular/angular-cli 👍

**Comment by pkozlowski-opensource** [comment]
Sounds like you might have already created this project before? Anyway, agree with @ericmartinezr that it should go to  https://github.com/angular/angular-cli instead so closing it here.
