### ISSUE TITLE
Angular should throw when zone.js is not present

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#2683]
Currently, the application will bootstrap, and the first digest will run successfully. But after that the application will stop reacting to changes, which is extremely confusing.

**Comment by SebastianM** [comment]
Ran into this issue a few times. IMHO a message for reflect-meta could be useful too.

**Comment by rkirov** [comment]
Reflect-metadata has that already  - https://github.com/angular/angular/blob/master/modules/angular2/src/util/decorators.ts#L92

**Comment by vicb** [comment]
@mjw56 are you loking at this ?

**Comment by gdi2290** [comment]
Can we also have an option not to throw? For universal/server we are manually triggering the change detection during each request (which is fine for most cases not advanced ones using `|async` at the moment). Manually triggering change detection allows us not to include zone.js   

on each request
1. read template
2. create host element from selector
3. compile App component with host element to host document
4. Detect Changes
5. serialize App component from host element
6. replace template from selector with serialized component as rendered string
7. dispose App component
8. remove host element from host document
9. serve rendered string

**Comment by vsavkin** [comment]
@gdi2290 I think that since most developers will use Angular in the browser and will require zone.js, throwing should be the default behavior. But we should have an option not to throw.

Currently, we do the following in ng_zone.ts. 
```
    if (global.zone) {
      this._disabled = false;
      this._mountZone = global.zone;
      this._innerZone = this._createInnerZone(this._mountZone, enableLongStackTrace)
    } else {
      this._disabled = true;
      this._mountZone = null;
    }
```

I think we should remove the if statement and the _disabled flag and instead have a different implementation of NgZone that does not use zone.js. You will be able to provide that implementation as a binding when running Angular on the server. Will it work for you?

**Comment by gdi2290** [comment]
@vsavkin yup that works for me, thanks!

**Comment by pkozlowski-opensource** [comment]
Update: the check for Reflect metadata is done in https://github.com/angular/angular/blob/450d3630cc2eb5afdbb535334d647a830badf91c/modules/angular2/src/util/decorators.ts#L230

**Comment by pkozlowski-opensource** [comment]
Moving to backlog as not sure I will have time to dive to zones in the coming week(s).

**Comment by fbeauchamp** [comment]
That's a really frustrating bug. 
A simple warning in the console can do the job temporarily : "zone.js is missing, this application will not be able to detect data change automatically" or something like that.

**Comment by evanplaice** [comment]
:+1: Just ran into this issue.

Throwing will work, logging a warning when running in dev mode would also work.

Surprisingly, Angular2 can do quite a lot without Zone.js. All the routing, component linking, property passing worked right up until I added a feature that required change detection. I was surprised when I finally realized that I forgot to import zone.js.

**Comment by gdi2290** [comment]
I heard you have to use `$apply()`
*joking*

**Comment by mhevery** [comment]
it does:

```
Error: (SystemJS) EXCEPTION: Error during instantiation of NgZone! (ApplicationRef -> ApplicationRef_ -> NgZone).
	ORIGINAL EXCEPTION: ReferenceError: Zone is not defined
	ORIGINAL STACKTRACE:
	ReferenceError: Zone is not defined
	    at new NgZoneImpl (https://npmcdn.com/@angular/core/bundles/core.umd.js:9077:17)
	    at new NgZone (https://npmcdn.com/@angular/core/bundles/core.umd.js:9229:30)
	    at createNgZone (https://npmcdn.com/@angular/core/bundles/core.umd.js:9519:16)
	    at ReflectiveInjector_._instantiate (https://npmcdn.com/@angular/core/bundles/core.umd.js:6370:31)
	    at ReflectiveInjector_._instantiateProvider (https://npmcdn.com/@angular/core/bundles/core.umd.js:6311:29)
	    at ReflectiveInjector_._new (https://npmcdn.com/@angular/core/bundles/core.umd.js:6300:25)
	    at ReflectiveInjectorDynamicStrategy.getObjByKeyId (https://npmcdn.com/@angular/core/bundles/core.umd.js:5954:54)
	    at ReflectiveInjector_._getByKeyDefault (https://npmcdn.com/@angular/core/bundles/core.umd.js:6480:42)
	    at ReflectiveInjector_._getByKey (https://npmcdn.com/@angular/core/bundles/core.umd.js:6452:29)
	    at ReflectiveInjector_._getByReflectiveDependency (https://npmcdn.com/@angular/core/bundles/core.umd.js:6442:25)
	Error loading http://run.plnkr.co/SpbIFRCM3oP2G9Zc/src/main.ts
```
