### ISSUE TITLE
scrollPositionRestoration shouldn't restore router-outlet who's route wasn't changed

### ISSUE THREAD

**Issue by bobvandenberge** [angular/angular#26848]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
We use a named router-outlet to display a 'knowledge center' type of popup. This knowledge center can be opened on any page. Since Angular 6.1 we use `scrollPositionRestoration: 'top'` configuration for the RouterModule. However, this means that pages also scroll to the top when we open the knowledge center popup (as this is a route change).

## Expected behavior
Only restore the scroll position for the router-outlet that had its route changed

## Minimal reproduction of the problem with instructions
1) Set `scrollPositionRestoration` to `top`
2) Scroll down a page 
3) Open an auxiliary route
4) Notice that your primary outlet has scrolled to the top

## What is the motivation / use case for changing the behavior?
So our problem with the current behavior

## Environment

<pre><code>
Angular version: 6.1.1

Browser:
- [x] Chrome (desktop) version 70.0.3538.77 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
