### ISSUE TITLE
HTTP_INTERCEPTOR does not wait for APP_INITIALLIZER

### ISSUE THREAD

**Issue by rupamroy** [angular/angular#26845]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have an service which has a `load` method which returns a promise , and in doing so it stores the data in a property within itself. This method is called using the `useFactory` of an APP_INITIALIZER.

When i use this service in a component's constructor and try to access that property it works fine. 

But if the same service is injected in an HTTP_INTERCEPTOR and we try to access the property , then it says the property is undefined which implies that the constructor for the interceptor is trying to access the property before the APP_INITIALIZER is resolved.

Look at the stackblitz code mentioned below

## Expected behavior
HTTP_INTERCEPTOR constructor should be fired after the APP_INITIALIZER is resolved.

Note: This used to work fine in angular 5.x.x.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-mh42ia

If you run this code you will see console error being thrown, if you comment the HTTP_INTERCEPTOR provide in app.module , everything will work well.

## What is the motivation / use case for changing the behavior?
APP_INITIALLIZER may be required to bring in configuration data which may be required in HTTP_INTERCEPTOR's too. 

## Environment

<pre><code>
Angular version: 6.2.x through 7.0.x

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by dielangsea** [comment]
i had the same problem here, expect it work in order.

**Comment by trotyl** [comment]
The problem is that you made an `APP_INITIALIZER` depends on `HttpClient`, which in turn depends on `HTTP_INTERCEPTORS`, so force it to instantiate eagerly, try remove `NameService` from your `NoopInterceptor` and it would work well:

https://stackblitz.com/edit/angular-u5htip?file=src/app/noop-interceptor.ts

**Comment by rupamroy** [comment]
Well, Here is my scenario - Every http call in my app is intercepted and then based on the url a modal or a redbar is shown, The decision to show a modal or redbar is made using a mapping stored in server config. So as you can see that mapping information is required in the interceptor itself . That is why i made the decision of loading that information using an APP_INITIALIZER to call a service which uses an http call to fetch that maping- thinking that APP_INITIALIZER would be called before the application loads and then the Interceptor would not come to play. But why is angular eager loading the HTTP_INTERCEPTOR an an APP_INITALIZER call. I believe APP_INITALIZER should be left alone and  should not be impacted by any provider unless injected in the loading factory.

**Comment by trotyl** [comment]
> But why is angular eager loading the HTTP_INTERCEPTOR an an APP_INITALIZER call.

It's eagerly instantiated because you eagerly used it, it's not a technical detail, just your business logic.

**Comment by alxhub** [comment]
@trotyl is correct, these are two separate concerns. DI providers (including `APP_INITIALIZER`, `HttpClient` and any interceptors) are constructed upon request by the `Injector`, even before the component bootstrap has occurred. If you don't want interceptors to run before `APP_INITIALIZER`, don't make HTTP requests.

**Comment by CreepyGnome** [comment]
@alxhub Then how do you load a client-side config file that has to be loaded before anything else? It requires HttpClient. Items in this config file and therefore by the Config Service are required by the authentication service. And this Auth service is required by the HttpInterceptor so it can inject JwtTokens.

So how do you load a client-side config based on the environment name without using HttpClient?

**Comment by dielangsea** [comment]
just use ajax


 
---Original---

**Comment by CreepyGnome** [comment]
@dielangsea How does "ajax" solve the issue within Angular 6 or 7 of loading local settings from a JSON file into a service or singleton like an instance that can be accessed anywhere or injected without triggering this circular dependency described in this issue? 

Would you like to elaborate with a stackblitz?

**Comment by mlc-mlapis** [comment]
@CreepyGnome ... it was probably meant to use just pure JS XHR request to get some data from anywhere and without any Angular instrumentation.

**Comment by CreepyGnome** [comment]
Thanks @mlc-mlapis ... AJAX is a broad topic and does not specifically mean anything without some context here. So thanks for being more specific and yeah since interceptors only work with HttpClient XHR should workaround this problem as it keeps the intent and design basically the same. If someone didn't want to do that they could bastardize the environment const class and having it replaced during the build.  Anyway thanks again @mlc-mlapis !

**Comment by dielangsea** [comment]
1.make a json file,  2.before app init use ajax to request json file, 3.make a provider to get the same construct object from json.
 
---Original---

**Comment by dielangsea** [comment]
before app init make an ajax,  use the same construct object to get the json.


 
---Original---

**Comment by kavinda1995** [comment]
I fixed this by using this method

[https://stackoverflow.com/a/49013534/6686446](https://stackoverflow.com/a/49013534/6686446)

Hope this helps
