### ISSUE TITLE
Calling Share point REST API from Angular Application

### ISSUE THREAD

**Issue by kishoreaoe** [angular/angular#26850]
Scenario:
1. From Angular application, we are using HTTP.get() in order to hit SHARE POINT rest api url.
2. Share point URL is public url and can be accessed by any one.

Result:   We are getting 401 unauthorized error.

If we hit the same url in the web browser, we were able to get the response with out any problem.

Observations:
1. when we hit the rest api in normal web browser, we are getting TYPE as 'document'.
2. when we hit the rest api with in Angular Application. the request is going as TYPE 'XHR'.

Anyone please help us on this issue.

Regards,
Kishore Kumar. K

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
