### ISSUE TITLE
feat Angular Language Service TS to HTML awareness

### ISSUE THREAD

**Issue by william-lohan** [angular/angular#26858]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
my.component.html

    <button (click)="onButtonClick()">My Button</button>

my.component.ts (vs code with typescript.referencesCodeLens.enabled)
<pre><code>
    <sub>0 references</sub>
    public onButtonClick() {}
</code></pre>
or right-click Find All Refrences (<kbd>Shift</kbd> + <kbd>F12</kbd>) doesn't show html template

## Expected behavior
my.component.ts (vs code with typescript.referencesCodeLens.enabled)
<pre><code>
    <sub>1 reference</sub>
    public onButtonClick() {}
</code></pre>
or right-click Find All Refrences (<kbd>Shift</kbd> + <kbd>F12</kbd>) does show html template

**Comment by abhiad** [comment]
why i am receiving these male just irritating.

**Comment by lemoinem** [comment]
@abhiad You must have watched the repository on Github. If you watch a repository, you will be sent an email for each new issue and/or PR.
The best would probably be to unwatch the repository and only subscribe to individual issues that interest you.
Go to GitHub, repository angular/angular, then at the top, next to the repo's name, you'll have three buttons "Unwatch", "Star", "Fork".
Click on "Unwatch" and then on "Not Watching".

Maybe reviewing your Github preferences to make sure you do not start watching automatically stuff that you don't want to could help as well.

**Comment by kyliau** [comment]
This is will be addressed as part of the language service upgrade after Ivy is released

**Comment by kyliau** [comment]
Tracking this work in https://github.com/angular/vscode-ng-language-service/issues/29
