### ISSUE TITLE
Posting data with the HttpClient

### ISSUE THREAD

**Issue by cliffordusidamen** [angular/angular#26851]
Am new to angular and didn't know where to go for help. So if this is not supposed to be here, please move it to the correct place.

The thing is that i tried posting some data to my back end, but at the back end the entire data i posted is actually set as the key (stringified) with an empty value.

Here is the code:
    this.http.post(url, data, httpOption)

Explanation:
    if data is {someprop: 'value'} at the back end this is what i get as PHP array:
    [
         "{'someprop': 'value'}": ""
    ]

Am i doing it wrong?

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
