### ISSUE TITLE
[Angular] Can't bind to 'limit' since it isn't a known property of 'input'.

### ISSUE THREAD

**Issue by ManojEtech** [angular/angular#26866]
-- Directive
`import { Directive, Attribute } from '@angular/core';
import { NgControl } from '@angular/forms';

@Directive({
    selector: '[inputLimit]',
    host: {
        '(input)': 'onInput()'
    }
})
export class InputLimitDirective {
    constructor(private ngControl: NgControl, @Attribute('inputLimit') public inputLimit: string) { }
    public onInput() {
        let newVal = this.ngControl.value.substr(0, this.inputLimit);
        this.ngControl.control.setValue(newVal);
    }
}`

-- HTML
`<input type="text" class="form-control" inputLimit="{{ constant.MAX_LENGTH }}" [(ngModel)]="form.value.limit" preventWhiteSpace>
`
i want to get MAX_LENGTH form constant file but we are getting error like...
**[Angular] Can't bind to 'inputLimit' since it isn't a known property of 'input'.**

where is the problem?

**Comment by ManojEtech** [comment]
Where is the problems? can you help me?

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

You are binding to `inputLimit` in `<input type="text" class="form-control" inputLimit="{{ constant.MAX_LENGTH }}" ` but your directive doesn't seem to have such `@Input`. Hard to say more without a reproduce scenario.

Prepare a minimal stackblitz and ask a question on StackOverflow if you still face issues.
