### ISSUE TITLE
Angular 2 save file from Nodejs

### ISSUE THREAD

**Issue by diogo5santos5** [angular/angular#26868]
I have the snipped in NodeJS to try to do a download from my server.

    router.post("/download", function(req, res, next) {
      console.log(req);
      filepath = path.join(__dirname, "/files") + "/" + req.body.filename;
      console.log(filepath);
      res.sendFile(filepath);
    });

This is my Angular 2 code:
**Component.ts**

      download(index) {
        var filename = this.attachmentList[index].uploadname;
        this._uploadService
          .downloadFile(filename)
          .subscribe(data => saveAs(data, filename), error => console.log(error));
      }

**Service.ts**

    export class UploadService {
      constructor(private http: HttpClient, private loginService: LoginService) {}
      httpOptions = {
        headers: new HttpHeaders({
          "Content-Type": "application/json",
          responseType: "blob"
        })
      };
    
      downloadFile(file: string): Observable<Blob> {
        var body = { filename: file };
        console.log(body);
        return this.http.post<Blob>(
          "http://localhost:8080/download",
          body,
          this.httpOptions
        );
      }
In my HTML response I get the file correctly recording to my browser's network inspection tool. However Angular is trying to parse the response into a JSON object which obviously doesn't work since the response is a blob.

The error I get is this:

> Unexpected token % in JSON at position 0 at JSON.parse (<anonymous>)
> at XMLHttpRequest.onLoad angular 2

After that I changed the responseType to the httpOptions instead of header and it give me that error:

> "ERROR in src/app/services/upload.service.ts(25,7): error TS2345: Argument of type '{ headers: HttpHeaders; responseType: string; }' is not assignable to parameter of type '{ headers?: HttpHeaders | { [header: string]: string | string[]; }; observe?: "body"; params?: Ht...'. Types of property 'responseType' are incompatible. Type 'string' is not assignable to type '"json"'."

 Does anyone have a solution for this?

Thanks in advance!

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
