### ISSUE TITLE
It's unclear what @dynamic actually does

### ISSUE THREAD

**Issue by waterplea** [angular/angular#26874]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When you use arrow functions inside decorators you get an error in AOT

## Expected behavior

Documentation tells us that strictMetadataEmit can cause some errors that are not going to actually be errors and to suppress them we need to add // @dynamic to our component:
https://angular.io/guide/aot-compiler#strictmetadataemit

## What is the motivation / use case for changing the behavior?

I'm working on a decorator that requires an arrow function to be passed and I want to know if there are any drawbacks to adding @dynamic to my component.

## Environment

<pre><code>
Angular version: 5.2.0

**Comment by jenniferfell** [comment]
Related doc: 
https://angular.io/guide/aot-compiler#strictmetadataemit

I didn't find any doc for @dynamic other than what's in that page.

**Comment by jenniferfell** [comment]
@brandonroberts : Do you have any info that could help @waterplea understand the implications of adding @dynamic? If not, we can mark as needs eng input. Thx.

**Comment by alexzuza** [comment]
@jenniferfell https://github.com/angular/angular/issues/19698#issuecomment-338340211 https://github.com/angular/angular/issues/19765#issuecomment-337406946 https://github.com/angular/angular/issues/20351#issuecomment-344009887 https://github.com/angular/angular/issues/20903 https://github.com/angular/angular/issues/21111#issuecomment-353193249

**Comment by JoostK** [comment]
The `@dynamic` annotation is obsolete as of Ivy given that its metadata system is being phased out, so I'm closing this as won't fix as well.
