### ISSUE TITLE
PathRewrite and eventSource problem for server side event

### ISSUE THREAD

**Issue by Alann37** [angular/angular#26873]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I use a proxy.conf.json configuration to access my back-office and I try to implement a Server Side Event to notify my application of new information to display
The problem is, when I try to use my pathRewrite with an EventSource, I have a 406 error Not Acceptable.
But if I give to the eventSource the complete path to my back-office,  it works

## Expected behavior
The eventSource work with the use of my pathRewrite configuration

## Minimal reproduction of the problem with instructions

1 back-office which handle Server Side Event
1 angular app with a proxy conf configuration with path rewrite
trying to create an eventSource with the pathRewrite

## Environment

<pre><code>
Angular version: 6.1.7

Browser:
- [X ] Chrome (desktop) version 69.0.3497.100
 
For Tooling issues:
- Node version: v8.12.0
- Platform:  Windows 10

Others:
I don't know if this is the right place to post this problem.
I have also make a stackOverflow question https://stackoverflow.com/questions/53065598/angular-6-error-with-pathrewrite-and-eventsource
</code></pre>

**Comment by dylhunn** [comment]
Not enough information to reproduce.
