### ISSUE TITLE
add previousPath API to LocationService

### ISSUE THREAD

**Issue by odahcam** [angular/angular#26872]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Can't know if there was a previous route before the user gets to the current.

## Expected behavior
I wanted to know if the user has passed for any page before gatting to the current one.

## What is the motivation / use case for changing the behavior?
I have a back button in my application that uses `location.back()` to navigate to the previous route and I don't wanna show it if there's no previous route. I don't wanna to plug my router to my application's state just to get the previous route, but any recomended alternative solution is welcome.

## Environment

<pre><code>
Angular version: 6.1.x

Others:

</code></pre>

**Comment by odahcam** [comment]
> After upgrading to Angular 7 (just to register the fact I'm not on v6 anymore).

In my use case motivation, I was able to solve my issue by using the `Router.navigated` property, which says if any navigation has ever happened since the app boot.

I can no longer defend my use case for this issue, so consider it "closeable".

Thanks.

**Comment by jasonaden** [comment]
Thanks for the update on the issue. I'll close.
