### ISSUE TITLE
bundle does not contain NativeShadowDomStrategy

### ISSUE THREAD

**Issue by tbosch** [angular/angular#2688]

**Comment by rkirov** [comment]
It should be because it is exported here https://github.com/angular/angular/blob/master/modules/angular2/render.ts#L10

**Comment by PascalPrecht** [comment]
@rkirov unfortunately both, `EmulatedScopedShadowDomStrategy` and `NativeShadowDomStrategy` are not part of the bundle. Try a simple search here: https://code.angularjs.org/2.0.0-alpha.27/angular2.dev.js

**Comment by rkirov** [comment]
The problem is in the entry point for the bundle which is `angular2.ts` we don't import the `render.ts` module.

https://github.com/angular/angular/blob/master/modules/angular2/angular2.ts#L76

Instead we reexport `angular2/src/render/api`. @tbosch what is the reason for that, and are you ok with changing that line to `angular2/render`?

**Comment by PascalPrecht** [comment]
Prepared a PR at #2717 that can be merged, once @tbosch made a decision.

**Comment by tbosch** [comment]
Yes, please export everything from `angular2/render`.

**Comment by rkirov** [comment]
Pascal can you change your PR to just reexport `angular2/render` and reassign the PR to me for review.
Ideally, `angular2/angular2` should not have any `angular2/src/*` paths.

**Comment by PascalPrecht** [comment]
Yeap, taking care of this!

**Comment by PascalPrecht** [comment]
Just one quick question: There are a couple of imports that come from angular2/src/render but are **not** exported by angular2/render e.g. https://github.com/angular/angular/blob/master/modules/angular2/src/core/application.ts#L40-L41

Shall I just leave them in?

**Comment by mhevery** [comment]
Obsolete
