### ISSUE TITLE
Change script inclusion to be compatible with CSP hashes

### ISSUE THREAD

**Issue by ChaosCrafter** [angular/angular#26885]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When a page is deployed the compiled scripts are included inline after the app-root tags.
e.g. 
  ```
  <body>
    <app-root></app-root>
    <script type="text/javascript" src="runtime.a66f828dca56eeb90e02.js"></script>
    <script type="text/javascript" src="polyfills.aa65e3378ecb188e0792.js"></script>
    <script type="text/javascript" src="scripts.f9bdf93c4ffe3565303b.js"></script>
    <script type="text/javascript" src="main.9742cee6e57f256e947f.js"></script>
  </body>
```

This is difficult (impossible?) to make function when using CSP without reverting to allowing 'unsafe-inline' which allows any script in the page to run.

## Expected behavior

Ideally the only inline script would be a simple, static script that could have a constant hash used in the CSP.  It would then load the scripts from locally.  The CSP would be script-src 'self' 'sha-{base64hashofstaticcontent}'; to allow just local files and the one static script (startApp() in the example below.
The code would then appear as 
```
  <script type="text/javascript" src="runtime.a66f828dca56eeb90e02.js"></script>
  <script type="text/javascript" src="polyfills.aa65e3378ecb188e0792.js"></script>
  <script type="text/javascript" src="scripts.f9bdf93c4ffe3565303b.js"></script>
  <script type="text/javascript" src="main.9742cee6e57f256e947f.js"></script>
  <body>
    <app-root></app-root>
    <script type="text/javascript">startApp();</script>
  </body>
```

## Minimal reproduction of the problem with instructions

This is difficult to demonstrate as it requires csp header injection.
With any normal site the layout is appearent, but the failure only occurs once you add CSP

Steps to reproduce.
1. deploy a site to an S3 bucket.
2. set up cloud-front to force https and to allow header injection through lambdas
3. set up the lambdas to include script-src 'self';
4. access the site through cloudfront and observe the console errors caused by the security tokens.

## What is the motivation / use case for changing the behavior?
It will allow proper securing of sites against script injection in-page by denying all inline scripts except ones specifically allowed by csp hash.  It avoids the need to open site security by using script-src 'unsafe-inline';

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:
</code></pre>
While this may seem like an AWS issue, the core of the issue is that there is content in the page that we have no control of and that is not compliant with modern security standards.

**Comment by ChaosCrafter** [comment]
note the examples above have removed some of the tags referenced. (in particular the body tags)
The key to this is that script files should be pre-loaded and then started with a single static call.  The call by being static is able to be hashed once and included in the authorised hashes in the CSP.  The files are local so they are also legal.

**Comment by trotyl** [comment]
Please report it to https://github.com/angular/angular-cli.

**Comment by kara** [comment]
Yep, this issue should be reported in the Angular CLI repo linked above. Closing here.
