### ISSUE TITLE
Angular 7 upgrade karma timeouts and slow test runner when using --watch flag

### ISSUE THREAD

**Issue by sssalib42** [angular/angular#26881]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
After the Angular 7 upgrade from Angular 6 with minimal changes, Karma tests run a lot slower and fail with timeout errors much more often. When running in watch mode, the tests take an average of 4 minutes just to kick off the next run, and often fail unexpectedly. To give a perspective, our full list of unit tests used to run in under 3 minutes running on Angular 6, and saving a file rebuilt in seconds!

## Expected behavior
To run as it used to do, with "normal speed".

## Environment

<pre><code>
Angular version: 7.0.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.10.0
- Platform:  Windows

Others:

</code></pre>

**Comment by kara** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
