### ISSUE TITLE
<tag innerHTML="..."></tag> Should Behave the Same as <tag>...</tag>

### ISSUE THREAD

**Issue by hasahmed** [angular/angular#26887]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Setting tags `innerHTML` to be a router link (or other angular-specific stuff) doesn't result in a router link.

## Expected behavior

Setting the innerHTML should behave the same as writing the HTML inline right there.

## Minimal reproduction of the problem with instructions
```javascript
// mycomponent.component.ts
htmlString(){
 return this.domSanitizer.bypassSecurityTrustHtml('<a routerLink="hello">Hey</a>')
}
```
```html
<!-- mycomponent.component.html -->
<div [innerHTML]="htmlString()">
</div>
```
The above would result in an just the text `Hey` inside the. Not a link.

## What is the motivation / use case for changing the behavior?

I have a component which is a data table which is used in a few places in my application and I want to be able to supply custom html to use in the tables data if need be. In one place the custom html is a link to something, in another case the custom html is a routerLink to something.

**Comment by mlc-mlapis** [comment]
@hasahmed ... there in no Angular compiler in run-time so you can't pass any Angular bindings into `[innerHTML]` because of there is nothing what could compile such bindings. So you can pass just pure HTML code.

**Comment by hasahmed** [comment]
@mlc-mlapis Perhaps there should be an optional angular runtime compiler that could be included. These seems like functionality that should be available.

**Comment by mlc-mlapis** [comment]
@hasahmed ... there is the JIT compiler which can be loaded and injected in run-time ... even inside AOT app. Then you can create any dynamic component / module with any HTML template. But this is extra feature which you have to configure and use by your code. Don't count with some type of auto optional feature which does it automatically for you.

**Comment by mhevery** [comment]
closing as this would require compiler and would severely complicate the mental model and have large negative perf penalty.
