### ISSUE TITLE
JIT Compiler errors

### ISSUE THREAD

**Issue by Frozen-byte** [angular/angular#26884]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
After upgrading from Angular v6
When starting my app with `ng serve` the App crashes on browser with an error ([jit-error.log](https://github.com/angular/angular/files/2536511/jit-error.log) appended).
When starting my app with `ng serve --aot` the App runs well in browser.

## Expected behavior
ng serve jit compiling should not fail with error
`core.js:1394 Uncaught TypeError: ctorParameters.map is not a function`

## Environment

<pre><code>
Angular version: 7.0.1

Browser:
- [x ] Chrome (desktop) version 70
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.10
- Platform:  Linux

**Comment by kara** [comment]
@Frozen-byte This looks like something that should probably be filed in the angular/angular-cli repo.

**Comment by Frozen-byte** [comment]
Thank you I openend it https://github.com/angular/angular-cli/issues/12832
