### ISSUE TITLE
angular not serving

### ISSUE THREAD

**Issue by Abayomzee** [angular/angular#26892]
The serve command requires to be run in an Angular project, but a project definition could not be found.

Please help

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
