### ISSUE TITLE
Multiple form controls are bound to the same input element, when I use ngIf directive

### ISSUE THREAD

**Issue by sergey-malykh** [angular/angular#26890]
## I'm submitting a...

<pre><code>
[ x ] Bug report
</code></pre>

## Current behavior

There is ngIf directive with input field inside. And multiple contols which I bind to this field. Changing the current control results in the binding of invisible controls. Calling setValue on invisible controls set value in the input field. If I call a _clearChangeFns function when i select tab everything will work correctly.

## Expected behavior
Input's value is the same as form control value

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gitter-tetzfn

## Environment

<pre><code>
Angular version: 6.1.9

Browser:
- [ x ] Chrome (desktop) version 69

**Comment by AndrewKushnir** [comment]
This issue should be resolved by #39235 and the changes would be available in v11.1.0. Please create a new ticket if the problem still exists after upgrading to v11.1.0 (once it's available on NPM later this month). Thank you.
