### ISSUE TITLE
feat(service-worker): provide more options for notification click actions

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#26907]
Currently, clicking on a push notification emits a value on `SwPush#notificationClicks`. This is fine, but limited (e.g. when there is no app instance currently open).

We need a way to provide more advanced configuration options wrt handling notification clicks.

Possible options off the top of my head:

- If there are no open clients:
  1. Open a new window at `ServiceWorkerRegistration#scope`.
  2. Open a new window at a URL defined in `Notification#data.url` (or some other property we agree on).
  3. Have another convention to specify URLs per action in `Notification#data.urlPerAction`. Then we could look up the URL to open based on the action's name.

- If there are clients open:
  1. Focus the last focused client. 
  2. Navigate the last focused client to a specific URL (e.g. if specified in `Notification#data.url` or `Notification#data.urlPerAction`).

Alternatively, we could specify some operations per action according to some predefined convention. E.g.:

```ts
notification: NotificationOptions = {
  actions: [
    {action: 'foo', title: 'Open new tab'},
    {action: 'bar', title: 'Navigate in last focused tab'},
    {action: 'baz', title: 'Focus last focused tab'},
    {action: 'qux', title: 'Focus last focused tab (if any) or open new tab'},
  ],
  data: {
    onActionClick: {
      foo: {operation: 'openWindow', url: 'http://example.com/foo'},
      bar: {operation: 'navigateLastFocused', url: 'http://example.com/bar'},
      baz: {operation: 'focusLastFocused'},
      qux: {operation: 'focusLastFocusedOrOpen', url: 'http://example.com/qux'},
    },
  },
}
```

_Originally posted by @gkalpak in https://github.com/angular/angular/pull/25860_

**Comment by gkalpak** [comment]
cc @alxhub

**Comment by webmaxru** [comment]
Just to keep track of the current support of Notification#actions: https://web-confluence.appspot.com/#!/catalog?q=%22Notification%23actions%22

**Comment by Metsuryu** [comment]
Any progress on this? Is it now possible to click on a notification and open an URL?

**Comment by smarth55** [comment]
Not sure if you are still looking for a solution to this, but you could make your own service worker and import the cli built one into yours.
In ./src, create a `sw.js`

```
importScripts('./ngsw-worker.js');
self.addEventListener('notificationclick', (event) => {
  //do something here
})
```

Then when you register your service worker in your app, use
`ServiceWorkerModule.register('/sw.js', { enabled: environment.production })`
and be sure to add it to the assets in `angular.json`

**Comment by christophearg** [comment]
This workaround does not work anymore, self is undefined at this point and we can't get a reference to the service worker itself. Any news on this feature request? It is really needed.

**Comment by smarth55** [comment]
@christophearg I'm not sure how `self` can be undefined within a service worker. Is it possible that somewhere in your service worker you are redefining it, like `const self = this;`?

**Comment by christophearg** [comment]
I was talking about this workaround:
`importScripts('./ngsw-worker.js');
self.addEventListener('notificationclick', (event) => {
  //do something here
})`

In this workaround, self was still inside the service worker, but in latest version it is not anymore.

**Comment by dhruvgajwa** [comment]
in ngsw-worker.js
```
onClick(event) {
            if(this.scope.clients !== undefined) {
                this.scope.clients.openWindow('https://github.com/angular/angular/issues/29359').then(function(WindowClient) {
                    // Do something with your WindowClient
                  });
            } else {
                console.log('scope is undefined');
            }
           
            // Handle the click event and keep the SW alive until it's handled.
            event.waitUntil(this.handleClick(event.notification, event.action));
        }
```
this.scope.clients.openWindow(url).... does the work,
in new versions, you have to first build the project(with production tag) and then in dist/Project-name/ngsw-worker.js you can put this code in 'notificationclick' event handler function...

you can get this url from the payload as well!

this methods works even when your application is not in scope, as compared to the SwPush class which works only if the application is opened .


this.scope is the "ServiceWorkerGlobalScope" you can use "self" as well.
Have fun!

**Comment by TristanMarion** [comment]
Hi @gkalpak, do you have any news about this feature ?

**Comment by gkalpak** [comment]
No concrete plans to work on this yet. If someone wants to take it on, I would be happy to help/review.

It would also be helpful if someone knows (or could look into) how this is handled in other ServiceWorker implementations/libraries.

**Comment by TristanMarion** [comment]
Thanks for your reactivity ! I will try to search how this is handled and try to implement it. This will be my first contribution so I don't really know how to start 😅 
Coming back soon with more infos !

**Comment by dhruvgajwa** [comment]
Hey
Tristan Marion,   It's a great step  to take! And even I was hoping to
learn this stuff.
 Is this possible that we can learn this together? (from a peer learning
point of view)

**Comment by TristanMarion** [comment]
@dhruvgajwa Let's do that 😄

**Comment by dhruvgajwa** [comment]
let's get started!
we can get connected @gmail ->
myEmail: dhruvg.dakshana16@gmail.com

**Comment by tsproesser** [comment]
Hey, got redirected from my issue to this one - any news on this? I can't believe that notificationClick is almost useless for years now and noone cares! Really feels like ngsw isn't used in a production system out there at all!

I've seen the solution "subclassing" the ngsw-worker.js but that really feels kinda hacky. Yet no plans to better support notification clicks? Only being able to process them while the application is running is even worse than not offering it at all!

**Comment by gkalpak** [comment]
FWIW, it is up for grabs if someone is interested :wink: https://github.com/angular/angular/issues/26907#issuecomment-604627209
(Even just doing a research on how this is handled in other implementations would be quite useful.)

**Comment by prom00** [comment]
I thought I've seen a (small) change a while back...
Not sure though, but I thought this wasn't it there earlier:

`this.scope.addEventListener('notificationclick', (event) => this.onClick(event));`

I've been doing some changes in the ngsw-worker.js file, but it's a mess to keep your changes, as everytime you build the application, it get's overwritten....

**Comment by tsproesser** [comment]
> I thought I've seen a (small) change a while back...
> Not sure though, but I thought this wasn't it there earlier:
> 
> `this.scope.addEventListener('notificationclick', (event) => this.onClick(event));`
> 
> I've been doing some changes in the ngsw-worker.js file, but it's a mess to keep your changes, as everytime you build the application, it get's overwritten....

There is a neat workaround for keeping your service worker modifications:

1. Add a "custom-service-worker.js" to your src folder
2. Import the angular service worker and add your own code, e.g.

`importScripts('./ngsw-worker.js');

(function () {
    'use strict';

    self.addEventListener('notificationclick', (event) => {
        console.log("This is custom service worker notificationclick method.");
    });
}());` 

3. Add "custom-service-worker.js" to your assets (angular.json)
4. Make `ServiceWorkerModule` use your custom js (`ServiceWorkerModule.register('custom-service-worker.js', ...`)

**Comment by abdatta** [comment]
It is surprising that we still have to do "workarounds" to do such a basic notification thing in Angular! Why is this still not in priority? It has been a few years now! Are there any plans for a proper angular way to do this, instead of such workarounds?

**Comment by prom00** [comment]
> > I thought I've seen a (small) change a while back...
> > Not sure though, but I thought this wasn't it there earlier:
> > `this.scope.addEventListener('notificationclick', (event) => this.onClick(event));`
> > I've been doing some changes in the ngsw-worker.js file, but it's a mess to keep your changes, as everytime you build the application, it get's overwritten....
> 
> There is a neat workaround for keeping your service worker modifications:
> 
> 1. Add a "custom-service-worker.js" to your src folder
> 2. Import the angular service worker and add your own code, e.g.
> 
> `importScripts('./ngsw-worker.js');
> 
> ```
> (function () {
> 	'use strict';
> 
> 	self.addEventListener('notificationclick', (event) => {
> 		console.log("This is custom service worker notificationclick method.");
> 	});
> }());` 
> ```
> 
> 1. Add "custom-service-worker.js" to your assets (angular.json)
> 2. Make `ServiceWorkerModule` use your custom js (`ServiceWorkerModule.register('custom-service-worker.js', ...`)

This is indeed a good workaround, I do however don't like the idea of building this workaround when this should be something that should've been implemented already.



> It is surprising that we still have to do "workarounds" to do such a basic notification thing in Angular! Why is this still not in priority? It has been a few years now! Are there any plans for a proper angular way to do this, instead of such workarounds?

I agree with this... I was hopefully waiting for a solution, so I wouldn't have to implement the workarounds.
I'd love to know what's the plan on Angular with this, do you guys advise to go for the workaround, or wait a little more and see it get updated?

**Comment by tsproesser** [comment]
> > > I thought I've seen a (small) change a while back...
> > > Not sure though, but I thought this wasn't it there earlier:
> > > `this.scope.addEventListener('notificationclick', (event) => this.onClick(event));`
> > > I've been doing some changes in the ngsw-worker.js file, but it's a mess to keep your changes, as everytime you build the application, it get's overwritten....
> > 
> > 
> > There is a neat workaround for keeping your service worker modifications:
> > 
> > 1. Add a "custom-service-worker.js" to your src folder
> > 2. Import the angular service worker and add your own code, e.g.
> > 
> > `importScripts('./ngsw-worker.js');
> > ```
> > (function () {
> > 	'use strict';
> > 
> > 	self.addEventListener('notificationclick', (event) => {
> > 		console.log("This is custom service worker notificationclick method.");
> > 	});
> > }());` 
> > ```
> > 
> > 
> > 
> > 1. Add "custom-service-worker.js" to your assets (angular.json)
> > 2. Make `ServiceWorkerModule` use your custom js (`ServiceWorkerModule.register('custom-service-worker.js', ...`)
> 
> This is indeed a good workaround, I do however don't like the idea of building this workaround when this should be something that should've been implemented already.
> 
> > It is surprising that we still have to do "workarounds" to do such a basic notification thing in Angular! Why is this still not in priority? It has been a few years now! Are there any plans for a proper angular way to do this, instead of such workarounds?
> 
> I agree with this... I was hopefully waiting for a solution, so I wouldn't have to implement the workarounds.
> I'd love to know what's the plan on Angular with this, do you guys advise to go for the workaround, or wait a little more and see it get updated?

Yeah, that's my problem, too. I can use this workaround now and send direct Http-Calls with my custom handler so I can be sure a notification action click gets handled. **But:** Angulars native solution is really more a proofe of concept than a reliable one!

Since PWAs get more and more important and it's support is one of Angulars key features, I really don't get why it's left out in the cold. Looking for my issue (at least I first thought it **must** have been an issue) I found pretty old cases with persons struggling with this problem. And adding actions who's execution is not reliable is really no stable solution!

And as far as I know there are no plans for the future? Some official information would be great :)

**Comment by angelaki** [comment]
Any news on this? Or actually stil open / pending? Been a while now and this feature really is production relevant, isn't it?
