### ISSUE TITLE
Please provide a simple way to reset a FormGroup to its INITIAL state, not just a null state.

### ISSUE THREAD

**Issue by jlem** [angular/angular#26903]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Forms do not provide a way to reset them to their initial state/values. Calling `FormGroup.reset()` nulls out values, even if the form group was initialized with certain values. 

This requires you to take a snapshot of the state of its values upon initialization, and then call reset with that state. It's not clear if that state also includes any dynamic validators that were updated in dynamic forms (if it was a dynamic form). 

It also does not adequately mark all children as pristine and untouched on custom form controls implemented via value accessors. These methods have to be called manually after `reset()`. 

## Expected behavior
I expect the FormGroup to provide a simple method for restoring the state of the form that it was initialized with, as if the user had done a hard refresh on the page and the form had been re-constructed with the same data and validators that it was initialized with on page load. 

## Minimal reproduction of the problem with instructions
1. Create a new form group with some initial values (as if you were editing an entity and initializing it with that entity's info from an API)

2. Call `reset()` on that form group. 

3. All values are nulled out instead of just going back to the state they were initialized with.

4. To correct this, you must assign `formGroup.values` to a property, then then call `formGroup.reset(this.initialValues)` (again, it is unclear if this also resets dynamically added validators).

## What is the motivation / use case for changing the behavior?
It is extremely common to initialize a FormGroup with values, and for some FormControls to have non-null values (e.g. a pair of radio buttons whose values are `true` and `false`). Thus it should be simple to turn the FormGroup back to that state (including dynamically changed validators), without having to manually track snapshots of that state.

## Environment

<pre><code>
Angular version: 6.x.x

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.11.4  
- Platform:  Windows 

Others:

</code></pre>

**Comment by kara** [comment]
Closing as dupe
