### ISSUE TITLE
Error loading component using ViewEncapsulation.Native in Firefox and ipad chrome

### ISSUE THREAD

**Issue by RezaRahmati** [angular/angular#26904]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
log this error in console **Error: hostEl.createShadowRoot is not a function**

## Expected behavior
Display component correctly

## Minimal reproduction of the problem with instructions
Open this in firefox , and see the console. 
[https://stackblitz.com/edit/angular-webcomponent-polyfill](https://stackblitz.com/edit/angular-webcomponent-polyfill)

based on other threads, I already added webcomponentsjs package and imported polyfill into the app, and still not working

## Environment

<pre><code>
Angular version: 6.1.0 and 7

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 8
- Platform:  Windows

</code></pre>

**Comment by manklu** [comment]
ViewEncapsulation.Native is Shadow DOM v0 which you must activate in Firefox (and which is deprecated as standard). Your polyfill implements Shadow DOM v1, so not the right one.

If you use ViewEncapsulation.ShadowDom it will work in Firefox without polyfill.

**Comment by RezaRahmati** [comment]
> ViewEncapsulation.Native is Shadow DOM v0 which you must activate in Firefox (and which is deprecated as standard). Your polyfill implements Shadow DOM v1, so not the right one.
> 
> If you use ViewEncapsulation.ShadowDom it will work in Firefox without polyfill.
@manklu You saved my day,
even it's not documented in here [https://angular.io/api/core/Component#encapsulation](https://angular.io/api/core/Component#encapsulation)
