### ISSUE TITLE
Angular @Input() question

### ISSUE THREAD

**Issue by mohsin31** [angular/angular#26920]
Please help.
I have an @Input() of string/number/primitive type  in child.
When I use parent to pass this value it works.
But If I set value to @Input()  within the child component then passing this value from parent is not set until I click any of the button in the child component which will cause life cycle events to execute.
This is happening with string/number/boolean type.
When I use reference type "{name:string}" everything works fine even if I set value to object within component.
Any Idea?

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
