### ISSUE TITLE
Can't create app : Cannot find module './clone.js'

### ISSUE THREAD

**Issue by MathRobin** [angular/angular#26928]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When trying to create a new app, can't make it because of this message : 

``` bash
$ ng new some-app 
module.js:549
    throw err;
    ^

Error: Cannot find module './clone.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/math/.nvm/versions/node/v8.11.4/lib/node_modules/@angular/cli/node_modules/graceful-fs/graceful-fs.js:4:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

## Expected behavior
Should create an app

## Minimal reproduction of the problem with instructions
```bash
$ node -v
8.11.4
$ npm -v
5.6.0
$ npm install -g @angular/cli
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/@angular/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @angular/cli@7.0.4
updated 1 package in 1.906s
$ ng new some-app
[here comes the error mentionned]
```

## Environment

<pre><code>
Angular version: 7.04

For Tooling issues:
- Node version: 8.11.4
- Platform:  Linux Ubuntu

Others:
Nothing special
</code></pre>

**Comment by jaxoncreed** [comment]
I'm coming here by trying to create a React Native App. Same issue. Must be some module shared between the two.

**Comment by mkeymolen** [comment]
I have the same issue since a few hours. half a day ago there was no issue yet. Seems to be the graceful-fs module

**Comment by gwartnes** [comment]
Same thing happened to me just now. I just ran `npm install -g @angular/cli@latest` again and it updated 2 packages...now ng cli works again.

**Comment by codemonkey800** [comment]
Seeing the same error when I try to run `webpack` and `eslint` 😢

**Comment by mkeymolen** [comment]
for me, creating an app works fine, but "ng serve" gives this error.. did a latest install of @angular/cli but no difference...

**Comment by droidenator** [comment]
I don't have any to add other than I'm seeing the same error with an application created with Create React App

**Comment by Burry** [comment]
+1, getting this error with CRA and the [AWS Amplify CLI](https://aws-amplify.github.io/docs/js/start)

**Comment by droidenator** [comment]
Just a heads up that I fixed my app with `npm install graceful-fs@4.1.13`

**Comment by LeensCrystal** [comment]
Getting this error after `ng serve `. `ng new` seems to work fine though.

**Comment by darkguy2008** [comment]
Same here, bitbucket pipeline simply crashes now. What's going on?

**Comment by aldo-roman** [comment]
sounds like a recent update on some subdependency is missing `graceful-fs`

**Comment by mkeymolen** [comment]
see @codemonkey800 post above.. it is being solved isaacs/node-graceful-fs#139

**Comment by ericmartinezr** [comment]
Please report the issue here https://github.com/angular/angular-cli 👍

**Comment by mkeymolen** [comment]
issue can be closed.. as @droidenator mentioned: npm install graceful-fs@4.1.13 fixes the issue.

**Comment by marioavs** [comment]
I looks like just need to wait for the last release to be available in npmjs.com

**Comment by CheemalaN** [comment]
This issue was fixed when I have installed clone js package 

npm i clone --save --dev

**Comment by in43sh** [comment]
> npm install graceful-fs@4.1.13

I tried that too, but it didn't work. Also, I'm working with Node only, not Angular.
