### ISSUE TITLE
Suggestions for CLI doc reference

### ISSUE THREAD

**Issue by DeborahK** [angular/angular#26924]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

It is GREAT to see the Angular CLI content in the docs! I'd like to see it expanded to be even more helpful.

## Expected behavior

Would like to see more thorough descriptions, more options, and brief examples.

## Minimal reproduction of the problem with instructions

Let's look at this one for example: https://angular.io/cli/generate#service-command

- The second line should show "ng g s<name> [options] as "s" is the appropriate shortcut for a service.
- The description of the name should provide more information. The name can include a folder name to identify where the service should be generated. It should mention that the name should *not* include ".service" as that will automatically be added. 
- It would be quite helpful to show a few examples here:
   ng g s heros/heroData  -> results in app/heros/heroData.service.ts
   ng g s logging -> results in app/logging.service.ts
   etc ...
- Some common options are missing, such as dry run
- I don't think --flat works with services as no directory is created unless specified as part of the name?
- Would be great to have more detail on the option descriptions. 

## What is the motivation / use case for changing the behavior?

Especially for beginners, the CLI is a great tool but sometimes seems like magic. It would be great to provide more information on what it does and how to get it to do what you need.

## Environment

<pre><code>
Angular version: 7.x

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by elbaumpj** [comment]
I'd like to jump in on this--I'll start working on modifications as described above.

**Comment by jenniferfell** [comment]
@DeborahK : Thanks for these suggestions, esp specific use cases to include as examples or with more details. 

@elbaumpj : Thanks for offering to help. We recently put together a doc on how to update the CLI command reference (source in the CLI repo) and be able to take advantage of the preview ability in AIO: https://github.com/ExpertSupport/doc-workflow/wiki/CLI-Reference-Doc-Workflow
We might need to have @jbogarthyde help you with logistics, but any help with writing is much appreciated.

**Comment by mgechev** [comment]
@DeborahK, thank you for the suggestion! I'll suggest closing the feature request for now and reevaluate in case it pops up again in the issue tracker with more folks needing it.
