### ISSUE TITLE
ICU standard Stand Alone day of week with DatePipe is not supported

### ISSUE THREAD

**Issue by ScoutPanda** [angular/angular#26922]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
It's not possible to format a date to Stand Alone day of week with the DatePipe. (ICU standard c http://userguide.icu-project.org/formatparse/datetime)

## Expected behavior
For example, the fi.ts locale file contains definitions for array position DaysStandalone, defined in the enum LocaleDataIndex, and if the getLocaleDayNames function is called directly with the FormStyle.StandAlone parameter everything works as expected (with Finnish I would get maanantai instead of maanantaina). However, format_date.ts getDateFormatter function does not have a case that would pass FormStyle.StandAlone to dateStrGetter. This is interesting because months have a case for both Format and StandAlone (ICU standard M and L, respectively). I would propose that cases would be added to getDateFormatter for the following cases as per in line with ICU standard:
// Day of the Week StandAlone
    case 'c':
    case 'cc':
    case 'ccc':
      formatter = dateStrGetter(TranslationType.Days, TranslationWidth.Abbreviated, FormStyle.Standalone);
      break;
    case 'cccc':
      formatter = dateStrGetter(TranslationType.Days, TranslationWidth.Wide, FormStyle.Standalone);
      break;
    case 'ccccc':
      formatter = dateStrGetter(TranslationType.Days, TranslationWidth.Narrow, FormStyle.Standalone);
      break;
    case 'cccccc':
      formatter = dateStrGetter(TranslationType.Days, TranslationWidth.Short, FormStyle.Standalone);
      break;

## Minimal reproduction of the problem with instructions
Here is a link to a stackblitz that shows the problem
https://stackblitz.com/edit/angular-gitter-qzhwvm

## What is the motivation / use case for changing the behavior?
To be able to use angular internationalization with the DatePipe without having to resort to hacks

## Environment

<pre><code>
Angular version: 6.0.2
I have checked that there are no implementations for this in the most current angular version and have tested it with most current angular cli
</code></pre>

**Comment by reduckted** [comment]
It's also worth noting that the format string for a wide date in Finnish uses `cccc`, so even formatting the date with a named format won't work correctly.

https://github.com/angular/angular/blob/dc300c5c4172e1f8a6f3f84da6797e427e3626c0/packages/common/locales/fi.ts#L61

```js
console.log(formatDate(new Date(), 'fullDate', 'fi'));
// Prints "cccc 23. marraskuuta 2018"
```

The only other locale I could find that also uses `cccc` is "smn" or Sami (Inari):

https://github.com/angular/angular/blob/dc300c5c4172e1f8a6f3f84da6797e427e3626c0/packages/common/locales/smn.ts#L51

**Comment by Brosten** [comment]
I'm also having trouble printing fullDate in finnish. As described above. Any timeframe for a fix, or what's the best workaround?

**Comment by ScoutPanda** [comment]
In my case I only needed to show the name of the day, so I ended up making a pipe which removes "na" from the end, so for example Maanantaina becomes Maanantai. Wouldn't call it best practice or anything, but it works for me. I imagine it would be possible to make similar pipe for month also since all of them end with "ta".

**Comment by petebacondarwin** [comment]
I think this should be a fairly straightforward feature to add. Happy for someone to volunteer a PR.

**Comment by AndrewKushnir** [comment]
// cc @NothingEverHappens

**Comment by NothingEverHappens** [comment]
Will potentially take a look tomorrow
