### ISSUE TITLE
cdk/drag-drop does not work for wrapped lists

### ISSUE THREAD

**Issue by lukebooroo** [angular/angular#26921]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Using cdkDropList on a horizontal list of elements which wraps to the next line will not sort correctly.

## Expected behavior
The ability to sort the list

## Minimal reproduction of the problem with instructions
HTML
<pre><code>
<ul cdkDropList>
     <li cdkDrag>Item One</li>
     <li cdkDrag>Item One</li>
     <li cdkDrag>Item One</li>
     <li cdkDrag>Item One</li>
     <li cdkDrag>Item One</li>
</ul>
</code></pre>
CSS
<pre><code>
ul {
    display: flex;
    flex-wrap: wrap;
}
li {
    display: block;
    width: 33.333%
}
</code></pre>

**Comment by ericmartinezr** [comment]
@lukebooroo please open this issue in material's repo https://github.com/angular/material2 👍
