### ISSUE TITLE
Lazy Load Modules are not working properly in Angular 5

### ISSUE THREAD

**Issue by HillenLin** [angular/angular#26938]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

We have come across a very weird routing issue in our app. Angular Lazy Load Module is not working as expected. 

If I don't import lazy load module ( promotions.module ) into the app.module.ts, the proud build will fail and the routing is not working at all. The below is the error message: 

> ERROR Error: Uncaught (in promise): Error: Loading chunk promotions.module failed.

However, there are some modules in our app, which uses the same logic as the broken modules. It works without importing the module into the app.module.ts

According to #10981 , and we also did lots of research in StackOverflow. the following is what we found: 

- Some developer said Angular lazy load module is not working for complex and large-sized application, and it only works for simple application? It is true?

- Some developers suggest to use` loadChildren: () => PromotionsModule`. But apparently this is not a solution and it is only a dirty workaround. Additionally, it will cause proud build fail. 

- According to #10981, it seems like there is a bug when using Angular Lazy Load Module. Should I upgrade to the latest Angular to fix the problem?

I know Angular is an open source, but this problem is really slowing down our development speed. Can anyone give a guidance what causes the issue and how to fix it? 

## Expected behavior

`loadChildren: './my-orders/my-order.module#MyOrderModule'` should be work without importing lazy loaded modules into app.module.ts.

## Minimal reproduction of the problem with instructions

in app.routing.ts: 

```
const appRoutes: Routes = [
    {
        path: '',
        redirectTo: '/home',
        pathMatch: 'full'
    },
    {
        path: 'home',
        component: HomePageComponent
    },
    {
        path: 'myOrder',
        loadChildren: './my-orders/my-order.module#MyOrderModule',
    }
]

```

in my-order.module.ts: 

```
const routes: Routes = [
  {
    path: '',
    component: MyOrdersComponent
  }
];
```

in app.module.ts: 

`//Don't import any lazy modules here
`
## What is the motivation / use case for changing the behavior?

Currently. What I did to fix the problem is as below. But I don't think it is the right way. (It works exactly as what we expect, but is it still lazy loaded? )

- Importing all the lazy load modules into the app.module.ts. 

- at each lazy loaded module, instead of leaving the parent path as an empty string, change to the below

```
const routes: Routes = [
  {
    path: 'aboutInfo',
    component: AboutInfoComponent,
    children: [
      ........
    ]
  }
];
```

## Environment
Angular CLI: 1.6.8
Node: 8.11.3
OS: win32 x64
Angular: 5.2.5

@angular/animations: 5.2.11
@angular/cli: 1.6.8
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

**Browser**: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by geromegrignon** [comment]
Using the same environnement, it's working for me : https://stackblitz.com/edit/github-fxdeaw?file=src%2Fapp%2Fapp.module.ts

**Comment by geromegrignon** [comment]
Take a look at this issue : https://github.com/angular/angular-cli/issues/8722

The solution would be to use absolute path rather than relative ones for loadchildren attribute.

`loadChildren: 'app/my-orders/my-order.module#MyOrderModule'`

**Comment by vlaco** [comment]
I have a problem with lazy loading too... I used RouterModule.forRoot/.forChild, I tried both relative and absolute path... It doesn't show any errors and it creates a separate chunk but when I go to the route where it should load the lazy module it just doesn't load it, it shows my NoContentComponent. 
`{ path: '**', component: NoContentComponent },`
I am using webpack, maybe an issue is somewhere in there? I also tried setting publicPath in webpack output and it didn't work. Any ideas what else could it be?

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

<hr>

Additionally, please update the example to `v7` as that is the current version of Angular. We only provide security updates for previous versions of Angular since the upgrade to new versions shouldn't require extensive work due to a low number of breaking changes between versions.
