### ISSUE TITLE
Nested routerLink doesn't work

### ISSUE THREAD

**Issue by RezaRahmati** [angular/angular#26939]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
If you have a nested routerLink, the inner one doesn't work
Even it doesn't matter to use `<a>` or `<span>`, it's same

## Expected behavior
Inner routerLink navigates to correct route

## Minimal reproduction of the problem with instructions
1 - Open [https://stackblitz.com/edit/angular-nested-router](https://stackblitz.com/edit/angular-nested-router)
2 - click on `Navigate to comp2 (Nested)`
3- It navigates to `Comp 1`, while it shoudl have navigated to `Comp 2`

```
	<span [routerLink]="[ './comp1']" >
		Comp1
		<span [routerLink]="['./comp2']" >
			Navigate to comp2 (Nested)
		</span>
	</span>

```

## Environment

<pre><code>
Angular version: 7

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 7
- Platform:  Windows 

Others:
</code></pre>

**Comment by manklu** [comment]
@RezaRahmati Due to event bubbling you click both links at the same time. First the inner and than the outer link. Not much that angular can do here.

https://stackblitz.com/edit/angular-nested-router-gnpykn?file=src/app/app.component.html

**Comment by RezaRahmati** [comment]
@manklu Thanks, yes that will work

[https://stackblitz.com/edit/angular-nested-router-j5eg95](https://stackblitz.com/edit/angular-nested-router-j5eg95)
