### ISSUE TITLE
Include ngxs state management library in 'EXPLORE ANGULAR RESOURCES' section

### ISSUE THREAD

**Issue by siva636** [angular/angular#26932]
Ngxs is a modern state management library for Angular applications. This great open source project has already received **more than 1500 stars at Github** (https://github.com/ngxs/store) at the time of this writing. 

Please add this to 'EXPLORE ANGULAR RESOURCES' section at the following url in the documentation website:
https://angular.io/resources

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
PRs welcome :smiley: See [resources-contributing.md][1].

[1]: https://github.com/angular/angular/blob/7d2a746090b720aea01d6b437d578ed84efb897e/aio/content/marketing/resources-contributing.md
