### ISSUE TITLE
Discussion: should r/Angular2 subreddit be added to community list?

### ISSUE THREAD

**Issue by sarunint** [angular/angular#26941]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
For those who don't know, there is a [subreddit](https://www.reddit.com/r/Angular2) for Angular out there and it gain quite a lot of popularity. Unfortunately, the subreddit was created a year before Angular v2 was released, so the name is `Angular2`, which violates the branding guideline. (The mods solve this problem by putting Angular (2+) in the banner of the subreddit, though.)

The question is, do you think this subreddit should be added to the list of communities in resources.json?

P.S. Before you ask, there is r/angular but it's not quite popular as this one.

## Expected behavior
N/A

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?
N/A

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
It should, as it was added before https://github.com/angular/angular.io/pull/901 (the old repo for the website), probably lost in some change.
