### ISSUE TITLE
InjectableDecorator should have a more specific return type than `any`

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [angular/angular#26942]
## I'm submitting a...
<pre><code>
[x] Bug report
</code></pre>

## Current behavior

`InjectableDecorator`, when called as a function, has the return type `any`. 
Using `Injectable()` as a decorator therefore causes a violation of TSLint's `no-unsafe-any` rule. See https://github.com/palantir/tslint/issues/3784.

## Expected behavior
 The `any` type is generally something to avoid in TypeScript because it removes type safety from operations it's involved in.

## Minimal reproduction of the problem with instructions

`MyComponent.ts`:

```typescript
import { Injectable } from "@angular/core";

@Injectable()
export class MyComponent {
    // ...
}
```

`tslint.json`:

```json
{
  "rules": {
     "no-unsafe-any": true
  }
}
```

## What is the motivation / use case for changing the behavior?

Until the return type is more specific, TSLint users will need to disable the otherwise-useful `no-unsafe-any`.

For Tooling issues:
<pre><code>
- TSLint version: 5.11.0
- TypeScript version: 3.1.3
</code></pre>

**Comment by mhevery** [comment]
This is a really trivial fix as [InjectableDecorator](https://github.com/angular/angular/blob/4c2ce4e8ba4c5ac5ce8754d67bc6603eaad4564a/packages/core/src/di/injectable.ts#L48-L49) should return [TypeDecorator](https://github.com/angular/angular/blob/39e426cde3f08feaccb2118bfaaa27272f53965f/packages/core/src/util/decorators.ts#L25) instead of `any`.

Would anyone in the community be willing to take this on?

**Comment by mbinic** [comment]
@mhevery, I'm seeing the same reports for [`@Input`](https://github.com/angular/angular/blob/39e426cde3f08feaccb2118bfaaa27272f53965f/packages/core/src/metadata/directives.ts#L623) and [`@Output`](https://github.com/angular/angular/blob/39e426cde3f08feaccb2118bfaaa27272f53965f/packages/core/src/metadata/directives.ts#L747) decorators by TSLint 5.16 for ng 7.2.0.

I'd say the same fix is applicable, and I can make the change and send a PR if you think that's ok?
