### ISSUE TITLE
Proposal: `exportAsCustomElement` metadata in @Component

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#26955]
# 🚀 feature request

### Releavant Package

 This feature request is for @angular/....

- @angular/core
- @angular/compiler

### Description

Currently, to export Angular components as native Custom Elements, it needs 3 steps.

1. add a component to `entryComponents` array
2. create element class with `createCustomElement` API
3. define the element with `customElements.define` API

```

import { BrowserModule } from '@angular/platform-browser';
import { NgModule, Injector } from '@angular/core';
import { createCustomElement } from '@angular/elements';
 
import { HelloComponent } from './hello.component';
 
@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule],
  providers: [],
  entryComponents: [HelloComponent]
})
export class AppModule {
  constructor(injector: Injector) {
    const el = createCustomElement(HelloComponent, { injector });
    customElements.define('app-hello', el);
  }
}
```

There are a few points I think it can be improved.

1. The created element's selector is the same to original component's one in most case. Now it needs  to write it twice. 
2. `createCustomElement(***Component, { injector });` is a boilerplate code. In most case, passing injector directly. 
3. `entryComponents` is not an intuitive step to create a Custom Element. It can be automatically registered like `RouterModule.forRoot` components.

### Describe the solution you'd like
 

My proposal introduces new `exportAsCustomElement` field in `@Component` metadata.
It gives us to following benefits;

1. Angular Compiler can know the component is or isn't going to be Custom Elements. So all above 3 steps can be generated and the Custom Element is **automatically** enabled.
2. One selector in the component selector. 

Once set `exportAsCustomElement`, it will be defined automatically while Angular bootstrapping.
Any `NgModule`s don't have to know about Custom Elements. It will be just a matter of each Angular components.

```
@Component({
  selector: 'app-hello',
  template: `...`,
  exportAsCustomElement: true
})
export class HelloComponent {}
```

If you want to change its selector as a Custom Element, it can be accepted in the same metadata.

```
@Component({
  selector: 'app-hello',
  template: `...`,
  exportAsCustomElement: 'hello-element'
})
export class HelloComponent {}
```

so, the type of `exportAsCustomElement` is `boolean | string`. By default, it is `false`.

**Comment by gkalpak** [comment]
I don't think we are at a point where adding this syntactic sugar would improve things noticeably. The `entryComponents` are no longer a thing, so that improves the situation a bit.

Also, we would need to keep the existing APIs, because there are cases where you want more configurability. As a result, we would be introducing multiple ways to achieve the same thing, which is undesirable.

Based on the above (and the relatively low number of upvotes), I am going to close it. In the future, once the `@angular/elements` APIs are more refined and stabilized, we can look into ways to streamline the syntax.
