### ISSUE TITLE
packages/http does not generate correct ngsummary

### ISSUE THREAD

**Issue by Toxicable** [angular/angular#26967]
# 🐞 bug report

### Affected Package
packages/http

### Is this a regression?
yes.
It did not happen on current angular/universal: https://github.com/angular/universal/blob/master/WORKSPACE

### Description
upon upgrading angular/universal to bazel fine grained deps we're running into an issue where there is no DI information for packages/http
```
Unhandled Promise rejection: Can't resolve all parameters for XHRBackend: (?, ?, ?). ; Zone: <root> ; Task: Promise.then ; Value: { Error: Can't resolve all parameters for XHRBackend: (?, ?, ?).
```
inspecting the ngsummary for it you can see there is no DI information produced
```
Object.defineProperty(exports, "__esModule", { value: true });
    var i0 = require("@angular/http/src/backends/browser_xhr");
    function BrowserXhrNgSummary() { return [{ summaryKind: 3, type: { reference: i0.BrowserXhr, diDeps: [], lifecycleHooks: [] } }]; }
    exports.BrowserXhrNgSummary = BrowserXhrNgSummary;
```
`diDeps: []`

## 🔬 Minimal Reproduction
Clone this PR here: https://github.com/angular/universal/pull/1083
you'll need to add a couple of deps - once updated you'll see this error from running `bazel test ...`

## 🔥 Exception or Error
as in Description

## 🌍  Your Environment

**Angular Version:** https://github.com/angular/angular/archive/08e4489cf5a93a352954f1639da5e92112993753.zip
bazel > 0.17

**Anything else relevant?**

**Comment by alexeagle** [comment]
packages/http is no longer published. Not sure if this is reproducible somewhere else? pls file a new issue if so
