### ISSUE TITLE
Find a control from $sce.trustAsHtml()

### ISSUE THREAD

**Issue by manishkrai** [angular/angular#2696]
Hello,
I have a string that contains some html data. Here I am using $sce.trustAsHtml() to produce safe  data for using with ng-bind. This string may contains few hyperlinks that I have to disable before the binding.

Currently, I am using regex.Replace to achieve the same  and its working fine. But I think this is not a good solution. 

var regexPatternSearchHyperlinks = "<[aA]\\s+(?:[^>]*?\\s+)?href=\"([^\"]*)\"";
var disableHyperlinkPattern = "<a href=\"$1\" disabled=\"disabled\" onclick=\"return false;\"";
var messageBody = self.SelectedMessage.Body;
messageBody = messageBody.replace(new RegExp(regexPatternSearchHyperlinks, "gi"), disableHyperlinkPattern);
self.SelectedMessageBody = $sce.trustAsHtml(messageBody);

Can I use some jquery/angular selector on self.SelectedMessageBody to find all available hyperlinks 
and just disable this by doing something like - 

$("a").click(function() { return false }); 

Regards,
Manish

**Comment by pkozlowski-opensource** [comment]
Wrong repo, I guess you are looking for https://github.com/angular/angular.js

Having said this, it sounds like a general support question and as such should be asked using an appropriate support channel: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by manishkrai** [comment]
Thanks pkozlowski.. I am going to post on https://github.com/angular/angular.js..
