### ISSUE TITLE
Location path returns empty

### ISSUE THREAD

**Issue by MurhafSousli** [angular/angular#26969]
# 🐞 bug report

### Affected Package

@angular/platform-browser

### Description

I want to get the current location using the `Location` service instead of `window.location.href`
but the problem that it returns empty, I tried [angular.io/api/common/Location#example](https://angular.io/api/common/Location#example) in a stackblitz, it returns empty

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-u1uqcd?file=src%2Fapp%2Fapp.component.html

## 🔥 Exception or Error

No errors

## 🌍  Your Environment

**Angular Version:** 7.0.2

**Comment by meriturva** [comment]
Seems to be correct. Actually `path` part of an URL is different compared to href and in your example is empty....so Location just works as expected.

Just search on google...`anatomy of url` or something similar.

Please close it.

**Comment by MurhafSousli** [comment]
@meriturva Okay, so `window.href.location` is the proper way to get the current URL?

**Comment by meriturva** [comment]
Currect one: `window.location.href ` . See https://developer.mozilla.org/en-US/docs/Web/API/Window/location

**Comment by MurhafSousli** [comment]
Thanks
