### ISSUE TITLE
Router: regression in relativeLinkResolution since 7.0.0 

### ISSUE THREAD

**Issue by dirkluijk** [angular/angular#26983]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router.

### Is this a regression?
Yes, the previous version in which this bug was not present was: `^6.1.0`

### Description
The `relativeLinkResolution: "corrected"` in Angular Router, which was introduced in https://github.com/angular/angular/pull/22394, is broken in Angular 7.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/relative-link-res-7

* Click on the `/lazy/comp/b/comp/c` hyperlink
* Click on the `../../` relative hyperlink
* An error occurs: `Error: Cannot match any routes. URL Segment: 'lazy/comp/b/comp'
* Expected: route changing to `/lazy/comp/b`

This works on Angular 6.1: https://stackblitz.com/edit/relative-link-res-6

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.4
@angular-devkit/build-angular     0.10.4
@angular-devkit/build-optimizer   0.10.4
@angular-devkit/build-webpack     0.10.4
@angular-devkit/core              7.0.4
@angular-devkit/schematics        7.0.4
@angular/cli                      7.0.4
@angular/compiler                 7.0.0
@ngtools/webpack                  7.0.4
@schematics/angular               7.0.4
@schematics/update                0.10.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
</code></pre>

**Comment by sarunint** [comment]
Looks like #25740 caused this.

**Comment by sarunint** [comment]
PR opened: #26990

**Comment by dirkluijk** [comment]
While investigating further, it seems there are more things broken.

| | Angular 6  |  master |
|---|---|---|
| corrected  | as expected   |  broken in lazy-loaded modules  |
|  legacy |  broken in normally-loaded modules  |  broken in normally-loaded modules  |

Compare:
* https://stackblitz.com/edit/relative-link-res-6
* https://stackblitz.com/edit/relative-link-res-6-legacy
* https://stackblitz.com/edit/relative-link-res-7
* https://stackblitz.com/edit/relative-link-res-7-legacy
