### ISSUE TITLE
gRPC / grpc-web support

### ISSUE THREAD

**Issue by smnbbrv** [angular/angular#26987]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....

- @angular/cli

and / or maybe a new one

- @angular/grpc

### Description
 A clear and concise description of the problem or missing capability...

As long as there is a native `HttpClient`, it would be super to have a native support of gRPC.

There is already a library https://github.com/grpc/grpc-web that implements gRPC communication and the clients generation, however there are two problems out there:

1. The generated client classes are not Angular services
2. Angular CLI is not involved into the generating / updating the gRPC services. It would be super if generating the gRPC clients is done by CLI and, more important, CLI would define the location and accessibility of those generated files according to the best practices

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

I'd love to have grpc-web nicely playing together with all Angular magic

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

Well, using https://github.com/grpc/grpc-web as-is is also fine. This feature is not *must*, but *would-be-good-to-have*

**Comment by kara** [comment]
Feature requests for the @angular/cli should be filed in the issue tracker for angular/angular-cli. Please re-open this issue in that repo, thanks!

**Comment by smnbbrv** [comment]
Hi @kara 

this is not really an issue of angular cli. I want to raise a global question here: whether angular should implement the grpc module / clients or use the grpc-web thing.

I just want to know one thing: whether this is going to happen one day, or grpc-web (at least for now) would be the only option in the scope of closest angular releases.
