### ISSUE TITLE
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them

### ISSUE THREAD

**Issue by dotNetAthlete** [angular/angular#26988]
I really, really, need to understand what causes the above, how and why it happens.

At the moment, I get this when I click the mouse to open an ngbdropdownMenu, but this only happens when the ngbdropdownMenu items have been dynamically created and loaded outside of the constructor or ngOnInit

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
