### ISSUE TITLE
DomSanitizer on grid-area

### ISSUE THREAD

**Issue by raxim1** [angular/angular#26994]
I don't want to call DomSanitizer on a valid grid-area which can contain a slash inside.

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by raxim1** [comment]
class Kushnir {
 andrew = "1 / 2"
}

[style.grid-area]="andrew" -> 1 / 2 is unsafe
