### ISSUE TITLE
Dynamically changing reactive forms throws a registerOnChange error

### ISSUE THREAD

**Issue by natcohen** [angular/angular#26998]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[   ] feature request
[   ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Changing a reactive form template fails. When replacing the form, it throws an error: `ERROR TypeError: control.registerOnChange is not a function`

**Expected behavior**

It should not throw any error... and should change the template

**Minimal reproduction of the problem with instructions**

http://next.plnkr.co/edit/vh1HCo2WrwNgr95G?open=lib%2Fapp.ts&deferRun=1

Click on "new template" and check the console

**Please tell us about your environment:**

NodeJS 8 running on Windows 10

* **Angular version:** 6.0.9

* **Browser:** Chrome 70 64bit

* **Language:** Typescript

**Comment by natcohen** [comment]
Would love to have an update on this one...

**Comment by tiagomsmagalhaes** [comment]
Hi... Any update on this one @AndrewKushnir ? I remembered I had this issue once like 2 years ago, and now I need this specific use case of adding dynamic instances of a `FormGroup` to `FormArray`. @natcohen even made a PR on #27246 that no one from Angular Team. Even it has a older sibling issue #13788

**Comment by AndrewKushnir** [comment]
Closing this as a duplicate of #13788. Will provide more updates in #13788. Thank you.
