### ISSUE TITLE
npm install error ionic

### ISSUE THREAD

**Issue by niketnaik** [angular/angular#26995]
npm WARN @angular/cdk@6.4.7 requires a peer of @angular/core@>=6.0.0-beta.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@6.4.7 requires a peer of @angular/core@>=6.0.0-beta.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/animations@5.2.10 requires a peer of @angular/core@5.2.10 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@6.1.10 requires a peer of rxjs@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@6.1.10 requires a peer of @angular/core@6.1.10 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/common@6.1.10 requires a peer of rxjs@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/common@6.1.10 requires a peer of @angular/core@6.1.10 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@6.1.10 requires a peer of rxjs@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@6.1.10 requires a peer of @angular/core@6.1.10 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser-dynamic@6.1.10 requires a peer of @angular/core@6.1.10 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser@6.1.10 requires a peer of @angular/core@6.1.10 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-time-select@0.9.3 requires a peer of angular2@2.0.0-beta.14 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package typescript is included as both a dev and production dependency.

Here is my package.json file :
 
```


{
  "name": "Bokies",
  "version": "1.0.0",
  "author": "titen",
  "homepage": "http://tisnsa.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/animations": "5.2.10",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.0.7",
    "@angular/compiler": "^6.0.7",
    "@angular/compiler-cli": "^6.1.10",
    "@angular/core": "^5.2.10",
    "@angular/forms": "^6.0.7",
    "@angular/http": "^6.0.7",
    "@angular/material": "^6.4.7",
    "@angular/platform-browser": "^6.0.7",
    "@angular/platform-browser-dynamic": "^6.0.7",
    "@ionic-native/camera": "^4.12.0",
    "@ionic-native/core": "^4.12.0",
    "@ionic-native/file": "^4.12.0",
    "@ionic-native/file-picker": "^4.12.0",
    "@ionic-native/file-transfer": "^4.12.0",
    "@ionic-native/image-picker": "^4.12.0",
    "@ionic-native/keyboard": "4.12.0",
    "@ionic-native/native-storage": "^4.10.1",
    "@ionic-native/network": "^4.8.0",
    "@ionic-native/onesignal": "^4.15.0",
    "@ionic-native/splash-screen": "4.7.0",
    "@ionic-native/status-bar": "^4.12.2",
    "@ionic-native/three-dee-touch": "^4.14.0",
    "@ionic/storage": "2.1.3",
    "again": "0.0.1",
    "and": "0.0.3",
    "angular2-time-select": "^0.9.3",
    "ionic-angular": "3.9.2",
    "ionic-parallax": "^0.2.0",
    "ionic2-datepicker": "^0.1.0",
    "ionic3-datepicker": "^2.5.3",
    "ionicons": "3.0.0",
    "npm-install-peers": "^1.2.1",
    "rxjs": "^5.5.11",
    "rxjs-compat": "^6.2.1",
    "sw-toolbox": "3.6.0",
    "typescript": "^2.7.2",
    "works": "0.0.1-beta-7",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.9",
    "typescript": "~2.6.2"
  },
  "description": "Great app for book a service and communicate to employee"
}

```

**Comment by pkozlowski-opensource** [comment]
You are mixing different Angular versions in your package.json:

```
   "@angular/common": "^6.0.7",
    "@angular/compiler": "^6.0.7",
    "@angular/compiler-cli": "^6.1.10",
    "@angular/core": "^5.2.10",
    "@angular/forms": "^6.0.7",
    "@angular/http": "^6.0.7",
```

You should use one and only one version for all the `@angular/...` packages (`material` and `cdk` got their own release versioning so it is ok to have those different from, say, `@angula/core`).
