### ISSUE TITLE
If the URL path is empty,  router.navigateByUrl("/"); doesn't do anything

### ISSUE THREAD

**Issue by alessiostalla** [angular/angular#27006]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

If the URL path is empty,  `router.navigateByUrl("/");` doesn't do anything, even when `onSameUrlNavigation` is `"reload"`. 

## Expected behavior

It should reload the route, as it does for other routes.

## Minimal reproduction of the problem with instructions

Write a single component and a single route mapping / to that component. Log something when the component is initialized. Inject the router into the component and later call `router.navigateByUrl("/");`, for example at the press of a button. Nothing happens. 

## What is the motivation / use case for changing the behavior?

Being uniform with the behavior of the router with every other possible route.

## Environment

<pre><code>
Angular version: 7.0.3

Browser:
- [X] Firefox version 62.0.3
</code></pre>

**Comment by atscott** [comment]
Duplicate of #21115. I'm keeping that one open, as I think the documentation should be improved.

Note that it does re-trigger all the navigation events:
https://stackblitz.com/edit/angular-ivy-router-base-1uzh1q?file=src%2Fapp%2Fapp.module.ts
