### ISSUE TITLE
Error root causes are swallowed in tests when using TestBed, AsyncTestCompleter 

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#2700]
Steps to reproduce (in JS):
* run `gulp test.unit.js`
* modify a template to trigger compilation failure, for example by "breaking" object literal (ex. remove last `}`) [here](https://github.com/angular/angular/blob/a67f2314f997a785d01163498b231435cb9b4680/modules/angular2/test/directives/class_spec.ts#L29)
* you will see a failing test with a message that doesn't point to the root cause:

> Chrome 45.0.2439 (Mac OS X 10.9.5) binding to CSS class list should add classes specified in an object literal FAILED
	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL. 

@vicb this is the reproduce scenario for the silent failure pb we've been discussing. Please let me know if you've got troubles reproducing.

**Comment by vicb** [comment]
If this is a dup of #2682
