### ISSUE TITLE
[Feature]: new lifecycle hook ngRouterChange

### ISSUE THREAD

**Issue by splincode** [angular/angular#27000]
# 🚀 feature request

### Releavant Package

 This feature request is for @angular/router

### Description

It would be very convenient if the components had a life hook, thanks to which it would be possible to use navigation events and not reinvent the wheel.

```ts
@Component({ .. })
class AppComponent {
 
  public ngRouterChange(event: RouterEvent) {
    //
  }

}
```

**Comment by picheli20** [comment]
I would be quite handy instead of subscribing on the router, but on the other hand, this would create some directly dependency with the router, no?

**Comment by jasonaden** [comment]
Thanks for the feature request. This is something we may look into in the future, but as @picheli20 said, it would create a dependency on the router which we won't be able to add.

The actual feature this requires would be the ability to create custom lifecycle hooks, which we don't have right now and isn't on the roadmap currently. This might be something to look at after Ivy is released.
