### ISSUE TITLE
MM/dd/yy hh:mm tt is not formatting using Date Pipe

### ISSUE THREAD

**Issue by MadhukarBandari** [angular/angular#27001]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please help us process issues more efficiently by filing an
issue using one of the following templates:

https://github.com/angular/angular/issues/new/choose

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by MadhukarBandari** [comment]
"MM/dd/yy hh:mm tt" is not formatting using Date Pipe Angular 4 

export class DateFormatPipe extends DatePipe implements PipeTransform {
    transform(value: any, args?: any): any {
        return super.transform(value, "MM/dd/yy hh:mm tt");
      }
}

**Comment by rodolfojnn** [comment]
Dont you mean "MM/dd/yy hh:mm zz"?

https://stackblitz.com/edit/angular-gacjtj

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
