### ISSUE TITLE
Issue with dynamically created ng element

### ISSUE THREAD

**Issue by valentin78** [angular/angular#27017]
steps to reproduce
1. create simple ng element bundle 
2. include this script to some empty page
3. after load page & script add component (like <my-component>) to body
4. issue: change detection not work (Title must update every 10 ms to current DateTime) (see index2.html how it should work)

DEMO https://codepen.io/valentin78/project/editor/AEyxdq

other case, if you add this component to body before script load, after that all components that will load dynamically will work (see index2.html)

**Comment by valentin78** [comment]
I guess it tied with https://github.com/angular/angular/issues/24061

**Comment by andrewseguin** [comment]
Duplicate of #24061
