### ISSUE TITLE
Angular 7 AOT: More Flexible Configuration For Multiple Projects

### ISSUE THREAD

**Issue by jpakulski** [angular/angular#27014]
### Question / Problem:

Is there a way to restrict the files the AOT compiler includes with angular.json project options such as "main" or "tsConfig". Is a different "sourceRoot" required?

### Our Scenario:

We are trying to bolt on a 2nd app to an exisiting application. The two would share most components / code.

Angular 7 Projects seemed like a great way to accomplish this.

**Attempt 1) Specifying a different main for each project:**

We manually added a new project block into angular.json gave it it's own main and outputPath and thought we're done. Each main file specified it's own bootstrap module. All works well when JIT served/build but when AOT is enabled the build fails due to multiple declarations of the same modules. The error is something like this:

> _ERROR in : Type AppComponent in xxx/app.component.ts is part of the declarations of 2 modules: ModuleA in xxx/a.module.ts and ModuleB in xxx/b.module.ts! Please consider moving AppComponent in xxx/app.component.ts to a higher module that imports ModuleA in xxx/a.module.ts and ModuleB in xxx/b.module.ts. 
> You can also create a new NgModule that exports and includes AppComponent in xxx/app.component.ts then import that NgModule in ModuleA in xxx/a.module.ts and ModuleB in xxx/b.module.ts._

So it seemed that when AOT is enabled the main setting is ignored.

**Attempt 2) Specifying a different tsConfig file with a custom exclude block:**

Next we tried specifying a seperate tsConfig for the two apps and using the exclude block to restrict the modules we load. This however did nothing and we got the same error.

**Attempt 3) Using fileReplacements, exclude clause:**

A bit more whacky but we tried using fileReplacements to create / overwrite the main modules used. This resulted in no modules being found.

Also **exclude** is not a valid option for either build or build -> options blocks.

### The Presumed Proper Way = Overkill:

I suppose the proper way to do this is to extract the common modules (most of them in our case) into a library and then share that between the 2 different projects. And move our bolted on app into it's own directory (src/app/projects/bolt-on-app). This just seems like a lot of work with many disadvantages (no live reload when lib changes, forced refactoring when a module is shared / unshared). 

**Is there really no way to restrict the files the AOT compiler includes? Or did I mess something up?**

### Our dev. environment:

```
Angular CLI: 7.0.4
Node: 10.12.0
OS: darwin x64
Angular: 7.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.4
@angular-devkit/build-angular     0.10.4
@angular-devkit/build-optimizer   0.10.4
@angular-devkit/build-webpack     0.10.4
@angular-devkit/core              7.0.4
@angular-devkit/schematics        7.0.4
@angular/cli                      7.0.4
@ngtools/webpack                  7.0.4
@schematics/angular               7.0.4
@schematics/update                0.10.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
```

Thank You

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
