### ISSUE TITLE
Remove declarations and providers from the modules

### ISSUE THREAD

**Issue by mhamri** [angular/angular#27019]
# 🚀 feature request

### Releavant Package
@angular/core

### Description
do we really need `declarations` and `providers`? 
all the declarations and providers can be resolved from the components automatically.
at the moment the angular needs declaration because HTML can't be converted to the component name, so we need to pre-register the component. but what if like jsx instead of a tag name we use the component name? this way we only need to es6-importing the component.
the component even can be discovered from routes. in this way any component that is not used also can go into the tree shake process.
the tag name can be resolved automatically from the component name. just convert a pascal case to snake case. 
it becomes even better if we let the user override the tag name if the selector option is available inside the component attribute. 
the component prefix becomes unnecessary for all the component files.
if we solve the components' problem then we can resolve the providers automatically too. because they are injected into the component with an ES6 import.
at the moment we are es6-importing the providers twice, once in a module and once in a component. we are doing so in a component to get intellisense. but why still we need to do it in a module?

for those who already saying it can't be done, i should refer you to StencilJs, it can be done. to be frank i read more about stencil, i belive more we can simplify the angular syntax and ceremony.

### JSA (jsx for angular) instead of JSX
don't get me wrong. JSX is ugly. I root for ngFor and ngIf instead of write ugly map function here and there. keep what we have now in angular, just instead of HTML make it JSX alike. in other words it look like JSX but with all angular feature. 

## sample code
it's a simple example i created to demonstrate, i believe it's backward compatible and also it's easy to change the @Component  implementation.

```TS
//sample.tsa
import {Component} from "@angular/core";
@Component({
    //it support old good string. 
    //string for old convention and function for jsx like type (i call it jsa!jsx for angular)
    // if the user decide to use string, then they need to add it to the declaration of the module
    tag: `
        <p *ngFor="let item of items">{{item}}</p>
        <some-other-tag-defined-in-module/>
    ` ,
    styleUrl:['./sample.scss']
})
export class Sample{    
}
```
```TS
//sampleDashboard.tsa
import {Component} from "@angular/core";
import {Sample} from './sample' //it's a component now, angular know it because it's having a @Component attribute
import {ISample} from './Isample' //it's not a component. if the user used this in the jsa, angular can throw an error
@Component({
    tag: ()=>(
        <div>
            <Sample [items]="items" *ngIf={items.Length>0}> // instead of using quotation that make new users confuse between string and normal binding, we can use {}
            </Sample>
        </div>
    ),
    styleUrl:['./sampleDashboard.scss']
})
export class SampleDashboard{
    items=[1,2,3];
}
```
```TS
//sampleRoot.tsa
import {Component} from "@angular/core";
import {SampleDashboard} from './sampleDashboard' 

@Component({
    selector:'my-app', //here user want to override it
    tag: ()=>(
            <SampleDashboard />
    )
})
export class SampleRoot{
}
```
```HTML
//output
//the app prefix should be something we can define in module maybe? or globaly in angular config
//another possiblity of app prefix is to extract it from module, if the module is appModule then the prefix become app
//another possiblity is to add component postfix to any of the compoent tag name
<my-app>
    <app-sample-dashboard>
        <app-sample>
            <p>1</p>
            <p>2</p>
            <p>3</p>
        </app-sample>
    </app-sample-dashboard>
</my-app>
```

**Comment by trotyl** [comment]
Inventing a new language is a nonstarter, it must be valid TypeScript code.

**Comment by mhamri** [comment]
oh this one still is open! 

So couple of thought after 2 years, I believe angular already got rid of the `providers` somehow. But still I'm not happy how DI is implemented in Angular. 

In DI we have three types of instances. Scoped, Transient and Singleton. we have a strait path when defining transient and singleton in angular, but for the Scoped we still need ngModule. 

this suggestion was on this fact that we can remove the ngModule, but before that we need to figure out how to create scoped services without needing ngModule. 

also, separate of concern was a big part of angular, maybe inside `@component` like inline JSX we should be able to pass a file. 

JSX doesn't support async pipe or even pipe, so to keep it compatible it should be an angular flavored of JSX, but it helps greatly to simplify the angular, specially by removing the ngModule

**Comment by pkozlowski-opensource** [comment]
We did a couple of changes in the framework recently:
* introduced tree-shakable providers so you don't need to add them to NgModule `providers`;
* we are rolling out [standalone components, directives and pipes](https://github.com/angular/angular/discussions/43784) so declarations are not mandatory either.
