### ISSUE TITLE
No proper documentation on WebWorkers 

### ISSUE THREAD

**Issue by bharathmuppa** [angular/angular#27016]
It would be nice that angular docs should have" how to implement web worker "  in docs.

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/17779, https://github.com/angular/angular/issues/18328, https://github.com/angular/angular/issues/23730

**Comment by AndrewKushnir** [comment]
@bharathmuppa as @trotyl mentioned in the comment above, this request is a duplicate of existing ones #17779, #18328, #23730. Please subscribe to the mentioned threads for future updates.
