### ISSUE TITLE
Dynamic HTML load in a Component

### ISSUE THREAD

**Issue by viswarupam45** [angular/angular#27012]
Hi Team,

I need to create a Angular component such as Dynamic HTML as Script with ID  or HTML as String or HTML in a file using Dynamic URL. Means, I need to pass as template/Template URL as argument/parameter to Component. So it automatically load that HTML and all events will work (click, change,blur ....etc).

How we can achieve this ..?, Any one please help me on this.

**Comment by mlc-mlapis** [comment]
@viswarupam45 ... you can inject Angular JIT compiler into AOT main app and then you can create any component / module with any dynamic HTML template on-demand in run-time. The best way in a lazy loaded module, so you get the best performance with dynamic flexibility.

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
