### ISSUE TITLE
angular routes without rerendering

### ISSUE THREAD

**Issue by raxim1** [angular/angular#27011]
I have used ionic 3, but after that i had to create my own component library, because it was lagging.
Unfortunately took me a lot of time, and some features what angular routing has, are missing.

Imagine 4 tabs on the screen which has virtual scrolls inside. You want to switch back and forth without lagging. Ionic 3 used display:none value, but the problem with it, that it's lagging. I'm using z-index-es instead to hide and show. Nowadays i'm thinking to integrate the css-grid logic inside, so my virtual-scroll implementation not just figuring out the row height, the element width also, whether it has been positioned by the css grid in one row. Features what i have already does not exist in the CDK.

My question is related to implementation details of the angular router, not related to how to use it, as hybrid apps simply a pain when you want to speed up.

Can you guide me, how angular routes working in this case? I guess it's re-renders the tab with the virtual scroll inside.

What i want is to hold the position wherever the scrolling left, and switch between tabs in a smooth way. (orientation resistant also). What feature is missing from my implementation the nested routing url with parameter attributes. So if it's possible, what i'm asking i might jump back to the "official" routing way.

The only option is the z-index manipulation in my case, so are there any specific configuration when i can tell the angular just use z-index history? (what i have already implemented in my approach, but unfortunately i'm alone and cannot redevelop the whole angular)

Just hide and show elements with display:none what ionic is using simply not an option for me! (so rerendering not an option)

My solution is pretty neat as i'm holding my whole app without rerender (if it has been rendered), it does not cost that much, but at least it's not lagging, it's responding right away.

My problem is not with the angular, simply the browser was not able to deal with the amount of components (it has been redesigned several times - but to be honest it's not that complex page on mobile devices should be that painful). Even the RXJs was terribly slow, so i had my own implementation on this also.

Although angular is rapidly evolving but simply i needed the features yesterday, not tomorrow, as i'm developing the app in the last 2 years, from the time when angular / cli just messing around, and you cannot ask another two years me to follow your new guides which simply changing in every month.

I have experienced that on mobile devices only the css transform works properly, any other needs rigorous testing, and time. Which means going into native app would be better, is there were css grid for example.

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by raxim1** [comment]
Angular simply does not able to achieve the speed what i have requested, that's the fact, and i had to code the whole angular myself. It's not a stackoverflow question, you are lazy. Thanks God, i simply step by step removing angular from my code.
