### ISSUE TITLE
gulp build.dart failing & can't get why

### ISSUE THREAD

**Issue by vicb** [angular/angular#2701]
This is the error

```
line 36, column 726 of tmp/diffing_plugin_wrapper-cache_path-dHd8FEdv.tmp/angular2/src/services/url_resolver.dart: Unexpected token ';'
oin ( "" ) ; } ;…
               ^

```

When the gulp tasks ends tmp has been deleted, no way to figure out what's going wrong !

**Comment by vicb** [comment]
I have figured out but still we should be able to inspect the generated file on such errors

**Comment by IgorMinar** [comment]
the full path to the file is listed in the error message: tmp/diffing_plugin_wrapper-cache_path-dHd8FEdv.tmp/angular2/src/services/url_resolver.dart

would providing more context in this case be more useful?

**Comment by IgorMinar** [comment]
please reopen if this is still an issue.
