### ISSUE TITLE
CircleCI does not kick in on PRs after force push

### ISSUE THREAD

**Issue by sarunint** [angular/angular#27020]
# 🐞 bug report

### Affected Package

 The issue is caused by N/A

### Is this a regression?

 No

### Description

 I opened PR #26990 and force push it many times. After a force push, CircleCI fails to kick in. So I can't see the result of the build.

## 🔬 Minimal Reproduction

N/A

## 🔥 Exception or Error
N/A

## 🌍  Your Environment

N/A

**Anything else relevant?**

Screenshot:
![image](https://user-images.githubusercontent.com/3850197/48252541-a3f6e100-e437-11e8-886e-9daa7ca4383e.png)

**Comment by mlc-mlapis** [comment]
@sarunint ... CircleCI?

**Comment by sarunint** [comment]
Yes, CircleCI...

**Comment by mlc-mlapis** [comment]
@sarunint ... ahh, so you have a clone on CircleCI. And normally it works? Or is it a really new clone?

**Comment by sarunint** [comment]
Nope, I didn't registered CircleCI on my fork.

**Comment by gkalpak** [comment]
Thx for the heads-up. This is a known issue and CircleCI is aware and working on a fix.
In the meantime, closing and reopening or force-pushing to the branch (eventually) trigger CircleCI (but it sometimes takes a few attempts 🤷‍♂️).

Closing, since this is not actionable on our part.

**Comment by sarunint** [comment]
OMG, thanks for the trick!

**Comment by gkalpak** [comment]
:smiley:
BTW, beware that closing and re-opening causes PullApprove to dismiss any approvals.
