### ISSUE TITLE
Get only variables in $scope

### ISSUE THREAD

**Issue by alexandernst** [angular/angular#2702]
Let's say I store a few variables in a `$scope`, like this:

```javascript
$scope.a = "Test";
$scope.b =  {x: 42, y: 5};
$scope.c = 99;
```

Is there a way I could get a list of that scope containing `a, b, c`, aka, the data that doesn't belong to Angular?

**Comment by SebastianM** [comment]
@alexandernst You are in the Angular2 respository asking an AngularJS 1 related question.
The right place for Angular1 related questions is the mailing list: https://groups.google.com/forum/#!forum/angular

**Comment by alexandernst** [comment]
Oops, my bad! That repo name should contain a `2.0` :P

**Comment by gdi2290** [comment]
@alexandernst for angular1 you're probably looking for something like
```es6
var props = Object.keys($scope).filter(prop => prop.charAt(0) !== '$'); // ignore props that begin with '$'
```
