### ISSUE TITLE
Angular 2+ supports Typescript, ES5 and Dart as languages?

### ISSUE THREAD

**Issue by Phara0h** [angular/angular#27030]
# 📚 Docs or angular.io bug report

### Description

 I was told Angular 2+ supports Typescript, ES5 and Dart as languages that it can be used with. However, the documentation on your website does not show any evidence of this. It only shows stuff in typescript. I personly would like to use angular, but not interested in learning another ripoff langue created by Microsoft. I can just use the standard ES6/7 and get the same features and be natively supported in the browser without needing to compile. Is there some hidden button I am not seeing to switch the docs between ES5, Dart and typescript?

**Comment by mlc-mlapis** [comment]
@Phara0h ... yep, if you want to torture yourself, you can ... use pure JS for sure.

**Comment by Phara0h** [comment]
> @Phara0h ... yep, if you want to torture yourself, you can ... use pure JS for sure.

I think I would be torturing my self if I had to use a compiler for a language that was designed to not be compiled nor typed.

**Comment by jotatoledo** [comment]
[In older versions of angular.io](https://v2.angular.io/docs/ts/latest/), there were indeed API references/tutorials in plain js, but they were removed down the line as I guess [most ppl were interested in the combination of angular with typescript](https://trends.google.com/trends/explore?date=today%205-y&q=angular%202%20typescript,angular%202%20javascript), and not with plain js.

Feel free to waste your time writing angular in vanilla js if you like though.

As mentioned already, angular dart is different and resides on [its own repo](https://github.com/dart-lang/angular)

Furthermore, if you go to [the docs](https://angular.io/docs), using the button on the bottom left of the sidenav list you can toggle between different versions of the framework + angular dart.

**Comment by spock123** [comment]
@Phara0h Can you name me one modern framework that doesn't require "compilation/transpilation"? No, AngularJS doesn't count :)

How are you going to deliver your payloads? Minify it? Lazy load it?
You want to use ES6/7 and expect browsers to support it directly. Does that mean you also expect browser to support Observables? 

Very few browser support module loading, how are you going to bundle your code? 
You're going to concatenate all your files and then just deliver it to your browser? 

What is your build process like?

**Comment by jenniferfell** [comment]
The standing decision has been to document Angular + TypeScript. I've flagged this request for review by the devrel and engineering leads. 

* Minimal effort:  Clearly mention in the docs that TS, JS, and Dart are supported. 
* Much larger effort: Provide alternative examples in JS and Dart.

**Comment by Phara0h** [comment]
> @Phara0h Can you name me one modern framework that doesn't require "compilation/transpilation"? No, AngularJS doesn't count :)
> 
> How are you going to deliver your payloads? Minify it? Lazy load it?
> You want to use ES6/7 and expect browsers to support it directly. Does that mean you also expect browser to support Observables?
> 
> Very few browser support module loading, how are you going to bundle your code?
> You're going to concatenate all your files and then just deliver it to your browser?
> 
> What is your build process like?

Polymer does not require computation. Which is what I use over Angular

**Comment by trotyl** [comment]
@Phara0h Polymer is [reusing native HTML parser (by setting `innerHTML`)](https://github.com/Polymer/polymer/blob/a7c861b1f34317a2c81dee9c6a21cf4a5372649d/lib/utils/html-tag.js#L94-L99) for runtime compilation, which is equivalent to a JIT process, but less bundle size. 

But it couldn't achieve as good performance as a static build step does.

**Comment by mgechev** [comment]
Just like the documentation states, TypeScript is the official language that Angular supports. If you're interested in using Dart, you can check [AngularDart](https://angulardart.dev/)
