### ISSUE TITLE
How to display uploaded images with multer in angular

### ISSUE THREAD

**Issue by alikkane** [angular/angular#27046]
![capture d ecran 2018-11-10 a 20 20 12](https://user-images.githubusercontent.com/26570937/48305671-05e24400-e527-11e8-859b-e5ea74a56b04.png)

![capture d ecran 2018-11-10 a 20 26 16](https://user-images.githubusercontent.com/26570937/48305675-23afa900-e527-11e8-95ff-21be8c79c985.png)

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
