### ISSUE TITLE
Allow formGroupName=""  and distributed in several tags

### ISSUE THREAD

**Issue by lvillal** [angular/angular#27048]
Hi.
Would you allow formGroupName with "" value?
and It would be helpful if diferent divs would have same formGroupName="x" too.

This would allow to create dinamyc and configurables reactive forms.

**Comment by AndrewKushnir** [comment]
Thanks for sharing your proposal. However, you didn't provide sufficient information for us to continue reviewing it. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information. Please follow the [Feature Request](https://github.com/angular/angular/issues/new?template=2-feature-request.md) template and provide more information/details on your proposal.
