### ISSUE TITLE
ctorParameters.map is not a function

### ISSUE THREAD

**Issue by ng-swapna** [angular/angular#27058]
Hello Folks!

I am getting below error when I am trying to import **[MatTableModule](https://github.com/ng-swapna/ng7-mat-table/blob/ba959f344697b713d25f30282e63f0f5a4d6c80c/src/app/app.module.ts#L14)** in app.module.ts:

![image](https://user-images.githubusercontent.com/17465929/48344944-94c49d00-e69c-11e8-9782-960c49ae686a.png)

I am using latest angular packages:

![image](https://user-images.githubusercontent.com/17465929/48344898-6e066680-e69c-11e8-90ff-346a9894e920.png)

When i debug and see **ctorParameters** is supposed to be array but function in this case.
![image](https://user-images.githubusercontent.com/17465929/48344846-41524f00-e69c-11e8-80ef-33a92f9d239d.png)

**[Github](https://github.com/ng-swapna/ng7-mat-table/)**

Appreciate your help! Thank You.

**Comment by pkozlowski-opensource** [comment]
Please open in https://github.com/angular/material2 following the issue template in this repository
