### ISSUE TITLE
Testing: inconsistencies between Location and SpyLocation

### ISSUE THREAD

**Issue by robisim74** [angular/angular#27059]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common/testing

### Is this a regression?

 No, I think it never worked.

### Description

- The `normalize` method in the `Location` class works correctly, when in the `SpyLocation` class it always returns `null `(https://github.com/angular/angular/blob/7.0.3/packages/common/testing/src/location_mock.ts#L120)
- The `subscribe` method in the `Location` class is fired only on `popstate` event (https://github.com/angular/angular/blob/7.0.3/packages/common/src/location/location.ts#L140), when in the `SpyLocation` class is fired on each navigation (https://github.com/angular/angular/blob/7.0.3/packages/common/testing/src/location_mock.ts#L115) 

## 🔥 Exception or Error
The different behavior breaks the tests.

## 🌍  Your Environment
**Angular Version:**
```
Angular CLI: 7.0.1
Node: 8.11.1
OS: win32 x64
Angular: 7.0.0
```

**Anything else relevant?**
There are unresolved issues related to these inconsistencies: https://github.com/angular/angular/issues/10963 and https://stackoverflow.com/questions/47484775/location-class-from-angular-common-doesnt-work-in-unit-tests

Thanks!

**Comment by yggg** [comment]
Also, `SpyLocation.path` method always returns path with the fragment when `Location` has an `includeHash` parameter which is false by default.

**Comment by ondrasej** [comment]
Also, `SpyLocation.path()`returns only the path, but not the query. `Location.path()` returns the path and the query.
