### ISSUE TITLE
routing with if seems to be impossible

### ISSUE THREAD

**Issue by gocarlos** [angular/angular#27061]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

```json
    "@angular-devkit/build-angular": "~0.7.1",
    "@angular/animations": "^6.1.0",
    "@angular/cdk": "^6.4.7",
    "@angular/cli": "^6.1.1",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/flex-layout": "^6.0.0-beta.18",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@angular/material": "^6.4.7",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^3.0.1",

```

### Description

defining an empty routes array and assigning it later depending on the environment seems impossible
if the appRoutes is defined at the start, then it works well

```ts
let appRoutes: Routes = [];

if (environment.webAppType === 'ctrl') {
  appRoutes = [
    {
      path: 'landing',
      component: LandingComponent,
      children: [
        { path: 'login', component: LoginComponent },
        { path: 'oss', component: OSSComponent },
        {
          path: 'logout',
          redirectTo: '/landing/login?logout=true',
          pathMatch: 'full'
        },
        { path: '**', redirectTo: '/landing/login', pathMatch: 'full' }
      ]
    },
    {
      path: 'main',
      component: MainComponent,
      canActivate: [AuthGuard],
      canActivateChild: [AuthGuard],
      children: [
        {
          path: 'my-component-onboarding',
          component: MyComponent
        },
        { path: '**', redirectTo: '/main/my-component-onboarding', pathMatch: 'full' },
      ]
    },
    { path: '', redirectTo: '/landing/login', pathMatch: 'full' },
    { path: '**', redirectTo: '/landing/login', pathMatch: 'full' }
  ];
} else {
  appRoutes = [
    {
      path: 'landing',
      component: LandingComponent,
      children: [
        { path: 'oss', component: OSSComponent },
      ]
    },
    {
      path: 'main',
      component: MainComponent,
      canActivate: [AuthGuard],
      canActivateChild: [AuthGuard],
      children: [
        {
          path: 'start',
          component: StartComponent
        }
    },
    { path: '', redirectTo: '/main/start', pathMatch: 'full' },
    { path: '**', redirectTo: '/main/start', pathMatch: 'full' }
  ];
}

@NgModule({
  imports: [RouterModule.forRoot(appRoutes, { useHash: environment.useHash })],
  exports: [RouterModule]
})
export class AppRoutingModule {
}
```

## 🔥 Exception or Error
page is blank, if entering a route: Cannot match any routes. URL Segment

## 🌍  Your Environment

**Angular Version:**
<pre>

Angular CLI: 6.2.6
Node: 10.13.0
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.8.6
@angular-devkit/schematics        0.8.6
@angular/cdk                      6.4.7
@angular/cli                      6.2.6
@angular/flex-layout              6.0.0-beta.18
@angular/material                 6.4.7
@ngtools/webpack                  6.1.5
@schematics/angular               0.8.6
@schematics/update                0.8.6
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.9.2
</pre>

**Anything else relevant?**

**Comment by ericmartinezr** [comment]
Try this https://angular.io/api/router/Router#resetConfig

**Comment by dawidgarus** [comment]
It's possible that's because your code is not statically analyzable: https://angular.io/guide/aot-compiler#how-aot-works
Try ?: instead of if-else.
But I would suggest separate modules for each case. Currently components from unused routes will be included in your bundle, for example `StartComponent` when `environment.webAppType === 'ctrl'`.
Try exporting route configuration from `environment.ts` - I'm not sure but it should work

**Comment by gocarlos** [comment]
@ericmartinezr thanks, that fixed the problem.

basically we define two routes (`appCloudRoutes`, `appCtrlRoutes`) and add one to the 
```ts
  imports: [RouterModule.forRoot(appCloudRoutes, { useHash: environment.useHash })],
```

and then in: 

```ts
export class AppRoutingModule {

  public constructor(private router: Router) {
    if (environment.webAppType === 'ctrl') {
      router.resetConfig(appCtrlRoutes);
    }
  }
}  
```

and then: 

```
@NgModule({
...
  entryComponents: [
    LandingComponent,
    LoginComponent,
    OSSComponent,
    MainComponent,
...
  ],
...
```
