### ISSUE TITLE
Angular routing how to skip reloading a component

### ISSUE THREAD

**Issue by phil773** [angular/angular#27060]
I'm using the the Angular router with 2 Components.
Component A is a list of Information.
Component B is the detailView of an Item of the list.

In Component A I use the DevExtreme Widget DataGrid and load the data in the ngOninit().
If I switch from Component B back to A the Component reloads and I have to wait for my Server respond.

Is it possible to prevent component A to reload when switching between A and B, I'd like to Init component A just once.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
