### ISSUE TITLE
PercentPipe maxFractionDigits default values are wrong/missleading

### ISSUE THREAD

**Issue by paulferaud** [angular/angular#27079]
# 📚 Docs or angular.io bug report

### Description

PercentPipe maxFractionDigits default values are wrong/missleading

## 🔬 Minimal Reproduction
<pre><code>
{{1.12/100|percent}} - {{1.12/100|percent:'1.0-3'}}
</code></pre>
Output:
1% - 1.12%

### What's the affected URL?**
https://angular.io/api/common/PercentPipe

### Reproduction Steps**
Documentation says:
maxFractionDigits: The maximum number of digits after the decimal point. Default is 3.

Actual value seems to be '0'

### Expected vs Actual Behavior**
This may either be an implementation or documentation issue. I *believe* it is a documentation issue, probably a copy-paste issue from DecimalType, whose actual defaults are '1.0-3'

**Comment by ChrisDahmCS** [comment]
I agree, adding to this and being more specific with more decimal places, the 1.0-3 config should yield the same result as providing no config (based on the docs).

`{{.11111111|percent}} - {{.11111111|percent:'1.0-3'}}`

Instead displays as

`11% - 11.111%`

It seems like the PercentPipe documentation could be a copy paste issue from the DecimalPipe

[DecimalPipe](https://github.com/angular/angular/blame/7.0.4/packages/common/src/pipes/number_pipe.ts#L50-L68)

[PercentPipe](https://github.com/angular/angular/blame/7.0.4/packages/common/src/pipes/number_pipe.ts#L103-L122)

I cannot recall the PercentPipe ever showing out to three decimal places, does anyone else?


I'd be happy to do the fix PR if this is a documentation fix-

**Comment by ChrisDahmCS** [comment]
I generated three projects to test this functionality spanning ng5, ng6 and ng7 to confirm. The pipe seems to behave the same for all three versions.
