### ISSUE TITLE
ngModel ng-reflect in input type password

### ISSUE THREAD

**Issue by makbari** [angular/angular#27073]
# 🐞 bug report
### Description
I do not know if this is a bug o a feature. However if you inspect a input with type password, you can see the password in the ng-reflect-{variableName}. 
Is it better to not showing this in html inspector? 
Yes, also if you change type password to text in inspector, you can see the password, but in my opinion it is better to not show reflected value in html.

### Is this a regression?

 No, The bug is also presents in previous version

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
 https://stackblitz.com/edit/angular-yiqgsz

**Comment by sarunint** [comment]
It's there for debugging purpose only, it should go away in production mode.

**Comment by makbari** [comment]
I close this issue, because it is not present in --prod.
