### ISSUE TITLE
distance to parent in protoElementInjector does not reflect dynamic injectors

### ISSUE THREAD

**Issue by rkirov** [angular/angular#2707]
For example the injector creating MyComponent would not have distanceToParent `1`, but rather `-1`
```<other-cmp><my-cmp *ng-if="'true'"></my-cmp></other-cmp>```

**Comment by mhevery** [comment]
Is this still an issue?

**Comment by rkirov** [comment]
Yes, this is an issue and is needed for queries if they are to use DOM distance to determine what is a direct children.

Currently, as a stop gap we use the injector distance (i.e. direct child means `child.parent = injector`), if we flip to using `distanceToParent` the following example will break.
```
<queries-for-foo><foo *ng-for="'true'"></foo></queries-for-foo>``

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
