### ISSUE TITLE
Support colons in select option values

### ISSUE THREAD

**Issue by simonv3** [angular/angular#27081]
# 🐞 bug report

### Description
When using a template form with options, if there is a default "null" value then any option with a string starting with a 0 is counted as null. I can fix it by prepending ` ` blank strings to the front of the string. 

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-issue-repro2-ji7d9k

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 1.7.4
Node: 8.10.0
OS: linux x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.7.4
@angular/service-worker: 5.2.10
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.4.9
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.2
webpack-cleanup-plugin: 0.5.1
webpack: 2.7.0
</code></pre>

But on stackblitz this is still happening in 6.1.9

This is on firefox.

**Comment by trotyl** [comment]
The pattern with colon is preserved for special purpose and cannot be used:

https://github.com/angular/angular/blob/a752971bca0ab434971b61569545b55d4c883505/packages/forms/src/directives/select_control_value_accessor.ts#L25-L27

 change it to something like `0-hello` (anything without colon) and it would work.
