### ISSUE TITLE
Build single project from multiple projects

### ISSUE THREAD

**Issue by kvkb** [angular/angular#27097]
# 🐞 bug report

### Description

i want to build two or more separate angular projects and use them in a third project where i can have all the features together. I tried converting the projects to angular elements and use them, they are not rendering. 

i've created a repository with all the project files - [repo link](https://github.com/kvkb/angular-element-issue)

**Sample-project-for-angular-element** will create an angular element to be used in the **Shell** project

Please help me - 
If this approach is wrong - what is the better one 

## 🌍  Your Environment

Angular CLI: 6.1.4
Node: 8.11.3
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.4
@angular-devkit/core         0.7.4
@angular-devkit/schematics   0.7.4
@schematics/angular          0.7.4
@schematics/update           0.7.4
rxjs                         6.2.2
typescript                   2.9.2

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
