### ISSUE TITLE
Input (change) event not fired when using native arrows 

### ISSUE THREAD

**Issue by HDinger** [angular/angular#27091]
# 🐞 bug report

### Description

Given an input of type `number` with a `(change)` method. When using the inside arrows of the input to increase the value, the change method is only fired on the first click, but not on the second, third.. When you move the mouse it is fired again. 

![input_click_bug](https://user-images.githubusercontent.com/7457313/48481242-1e937800-e80d-11e8-9fc0-22b0b3af749d.gif)

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-gay4xb?file=src/app/app.component.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.0.4
Node: 11.1.0
OS: darwin x64
Angular: 7.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.2
@angular-devkit/build-angular     0.10.2
@angular-devkit/build-optimizer   0.10.2
@angular-devkit/build-webpack     0.10.2
@angular-devkit/core              7.0.2
@angular-devkit/schematics        7.0.4
@angular/cli                      7.0.4
@ngtools/webpack                  7.0.2
@schematics/angular               7.0.4
@schematics/update                0.10.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.16.1

</code></pre>

**Anything else**
* It seems to work in FF, however not in Chrome

**Comment by ericmartinezr** [comment]
Try `(input)` instead. Anyway, with FF your stackblitz works fine, it seems to _fail_ with Chrome.

**Comment by HDinger** [comment]
Thanks a lot, that works in Chrome, too! 👍 Any idea why the `(change)` method fails there?

**Comment by gkalpak** [comment]
Yes, this is not related to Angular. Basically, the spec leaves room for interpretation as to when the `change` event should be fired, so different browsers behave differently.
