### ISSUE TITLE
Service worker caching issues

### ISSUE THREAD

**Issue by Belshazzar684** [angular/angular#27094]
I'm using service worker to cache api call, here're my config:

`"dataGroups": [
    {
      "name": "api-offline",
      "urls": [
        "/api/Users",
      ],
      "cacheConfig": {
        "strategy": "freshness",
        "maxSize": 100,
        "maxAge": "30d"
      }
    }
  ]`

And i'm using http HEAD request to check if a username is existed or not. Eg: **_/api/Users/john.doe_** to check if john.doe is existed or not

However service worker decided to cache my check username api and throw the following error: _**Request method 'HEAD' is unsupported**_ 

How can i fix this or i have to change my api to a different name?

Edit: Just to clarify, i don't want to cache the HEAD request. I just want to cache list of users of api/users

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
