### ISSUE TITLE
Angular 7 CLI ng build options don't work for --deleteOutputPath or --verbose

### ISSUE THREAD

**Issue by hughanderson4** [angular/angular#27099]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/cli version 7.0.5

### Description

In Angular CLI when I try to use `--deleteOutputPath` or `--verbose` I get an error about "Unknown option"

## 🔬 Minimal Reproduction

 
1. Open Console.
2. Type `ng build --watch=true --deleteOutputPath=false --verbose=true`
3. Notice the following error:
```
Unknown option: '--deleteOutputPath'
Unknown option: '--verbose'
```
I have the expectation that these are CLI options due to the documentation I found on this page: https://angular.io/cli/build#options

## 🔥 Exception or Error
<pre><code>$>ng build --watch=true --deleteOutputPath=false --verbose=true
Unknown option: '--deleteOutputPath'
Unknown option: '--verbose'
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>$>ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.0.5
Node: 8.12.0
OS: win32 x64
Angular: 7.0.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.5
@angular-devkit/build-angular      0.10.5
@angular-devkit/build-ng-packagr   0.10.5
@angular-devkit/build-optimizer    0.10.5
@angular-devkit/build-webpack      0.10.5
@angular-devkit/core               7.0.5
@angular-devkit/schematics         7.0.5
@angular/cli                       7.0.5
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.5
@schematics/angular                7.0.5
@schematics/update                 0.10.5
ng-packagr                         4.4.0
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.19.1
</code></pre>

**Comment by pkozlowski-opensource** [comment]
> The issue is caused by package @angular/cli

Could you please report in https://github.com/angular/angular-cli? Thnx!
