### ISSUE TITLE
Platform is not described in documentation glossary

### ISSUE THREAD

**Issue by BrunnerLivio** [angular/angular#27096]
# 📚 Docs or angular.io bug report

### Description

Lurking through the angular source code I've found `createPlatform`. Unfortunately I have not found out through the docs or comments of Angular what a `platform` actually represents. I think the glossary would be the best place for a description?

### What's the affected URL?**
https://angular.io/guide/glossary

**Comment by jenniferfell** [comment]
Starter definition: https://en.wikipedia.org/wiki/Computing_platform
"he environment in which a piece of software is executed. It may be the hardware or the operating system (OS), even a web browser and associated application programming interfaces, or other underlying software, as long as the program code is executed with it. "

In the context of Angular, "platform" can mean all of Angular or more specifically the context in which the Angular app runs. We could be more clear about what "runs" means in that loose definition.

In addition to a glossary addition, the following APIs docs should be clear about how "platform" is used in this context
* common/isPlatform* 
* platform-browser package
* platform-server package
* platform-webworker package

**Comment by BrunnerLivio** [comment]
I see.. What kind of confused me was the platform `platformCore`, which is not tied to any "platform" which an Angular app runs on. But after some digging I realized platforms kind of *inherit* themselves `platformCore <- platformCoreDynamic <- platformBrowserDynamic` and each platform comes with its own providers. So `platformCore` seems to be an *abstract* platfom?

Am I getting this right?
If so I think it would be quite interesting to see in the docs platform X is based on platform Y and which providers come with it.

**Comment by gkalpak** [comment]
Basically, the main docs for Angular's `PlatformRef` is [here][1], but I agree that the docs for the specific platformRefs created by the various factories (e.g. [platformBrowser()][2], [platformBrowserDynamic()][3], etc) are pretty thin on details 😳 

[1]: https://angular.io/api/core/PlatformRef
[2]: https://angular.io/api/platform-browser/platformBrowser
[3]: https://angular.io/api/platform-browser-dynamic/platformBrowserDynamic

**Comment by Splaktar** [comment]
We needed these docs today while trying to explain the `@angular/webworker` deprecation in https://github.com/angular/angular/pull/30598.

**Comment by kapunahelewong** [comment]
fyi @dennispbrown and @brandonroberts.
