### ISSUE TITLE
Manual updation for Angular Validation min and max (number type) can be modified manually 

### ISSUE THREAD

**Issue by rohanshenoy96** [angular/angular#27093]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

I'm not sure, new to angular.
 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
If I set the min(angular directive) to 5 , I expect the minimum value that can be set is 5. Using the increase and decrease arrow this is true, but if I manually enter values then this constraint is no longer maintained.

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.0.3
Node: 8.11.3
OS: win32 x64
Angular: 7.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.3
@angular-devkit/build-angular     0.10.3
@angular-devkit/build-optimizer   0.10.3
@angular-devkit/build-webpack     0.10.3
@angular-devkit/core              7.0.3
@angular-devkit/schematics        7.0.3
@angular/cdk                      7.0.2
@angular/cli                      7.0.3
@angular/flex-layout              7.0.0-beta.19
@angular/material                 7.0.2
@ngtools/webpack                  7.0.3
@schematics/angular               7.0.3
@schematics/update                0.10.3
rxjs                              6.3.3
typescript                        3.1.4
webpack                           4.19.1

</code></pre>

**Anything else relevant?**

I have not added a demo as the problem is not that difficult to understand. If you like more clarification feel free to contact me on rohanshenoy96@gmail.com.

**Comment by lazarljubenovic** [comment]
That's just how `input` works in HTML. Nothing Angular can or should do here.

**Comment by rohanshenoy96** [comment]
Thank you for such a quick reply. I know but there can be an indication that the input is invalid, by giving some red border, like the other material inputs.

**Comment by pkozlowski-opensource** [comment]
>  I know but there can be an indication that the input is invalid, by giving some red border, like the other material inputs.

Angular forms will set control's state to the invalid validation status but won't add any visual indication. It is up to application developer to decide how users should be notified about invalid input.

Closing since this works as expected.
