### ISSUE TITLE
Can't resolve built library

### ISSUE THREAD

**Issue by ljmerza** [angular/angular#27104]
# 🐞 bug report

### Description
Following [these](https://blog.angularindepth.com/creating-a-library-in-angular-6-87799552e7e5) guidelines I get the following error:
`
Module not found: Error: Can't resolve 'example-ng6-lib' in 'C:\Users\Leo\Documents\test\example-ng6-lib\src\app'
`

I tried these steps from my current project and a completely new project and have followed every step given in the article but still get the same error. The ts config file is setup to point to the correct folder and the library built correctly:

<pre><code>
Building Angular Package
Building entry point 'example-ng6-lib'
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Copying declaration files
Writing package metadata
Removing scripts section in package.json as it's considered a potential security vulnerability.
Built example-ng6-lib
Built Angular Package!
</code></pre>

## 🔬 Minimal Reproduction
https://github.com/ljmerza/example-ng6-lib

## 🔥 Exception or Error
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'example-ng6-lib' in 'C:\Users\Leo\Documents\test\example-ng6-lib\src\app'
i ｢wdm｣: Failed to compile.

ERROR in src/app/app.module.ts(5,37): error TS2307: Cannot find module 'example-ng6-lib'.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.0.6
Node: 10.13.0
OS: win32 x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.6
@angular-devkit/build-angular      0.10.6
@angular-devkit/build-ng-packagr   0.10.6
@angular-devkit/build-optimizer    0.10.6
@angular-devkit/build-webpack      0.10.6
@angular-devkit/core               7.0.6
@angular-devkit/schematics         7.0.6
@angular/cli                       7.0.6
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.6
@schematics/angular                7.0.6
@schematics/update                 0.10.6
ng-packagr                         4.4.0
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.19.1
</code></pre>

**Comment by AnthonyPierrat** [comment]
Hello !, 

I don't know if it's the perfect answer but you can run `npm install dist/your-library` in your application/project or publish it to have your library as a package. Check if the installation worked in your package.json on dependencies.

Then try importing your library in app.modules.ts, make sure it points to your npm package.
Don't forget to build your library with `ng build your-library` and export everything in your public_api.ts.

**Comment by jasonaden** [comment]
Closing based on the above recommendations. If your issue persists, please create a new github issue with details.

**Comment by agodinhost** [comment]
I think that would be really good to have one sample application as demo to this recommendations above.
