### ISSUE TITLE
Clarify testing documentation for `whenStable`

### ISSUE THREAD

**Issue by ericksoen** [angular/angular#27109]
# 📚 Docs or angular.io bug report

### Description
Angular docs suggest that `whenStable` is a relevant testing construct when dealing with asynchronous activity. 
> This can be used to resume testing after events have triggered asynchronous activity or asynchronous change detection

In the Angular testing guide, the mechanics are further clarified:
> The fixture.whenStable() returns a promise that resolves when the JavaScript engine's task queue becomes empty.

### What's the affected URL?**
https://angular.io/api/core/testing/ComponentFixture#whenstable
https://angular.io/guide/testing

### Reproduction Steps**
Please see associated [StackBlitz](https://stackblitz.com/edit/angular-when-stable-blitz) with passing asynchronous tests using `whenStable` (Observable based) and failing asynchronous tests using `whenStable` (setTimeout and promise based).

### Expected vs Actual Behavior**
Documents more clearly describe under what asynchronous test scenarios, i.e., `setTimeout`, `Promises`, etc. `whenStable` is a relevant construct.

## 🌍  Your Environment
```
  "dependencies": {
    "@angular/common": "7.0.1",
    "@angular/compiler": "7.0.1",
    "@angular/core": "7.0.1",
    "@angular/forms": "7.0.1",
    "@angular/platform-browser": "7.0.1",
    "@angular/platform-browser-dynamic": "7.0.1",
    "@angular/router": "7.0.1",
    "core-js": "2.5.7",
    "jasmine-core": "^3.3.0",
    "rxjs": "6.3.3",
    "zone.js": "0.8.26"
  },
```

**Comment by ericksoen** [comment]
I updated the [StackBliz](https://stackblitz.com/edit/angular-when-stable-blitz) with a few more behaviors based on the [`component_fixture_spec`](https://github.com/angular/angular/blob/master/packages/core/test/component_fixture_spec.ts) and have a slightly more consistent behavior.

|Async Behavior|Component method|Life Cycle Hook (OnInit)|Browser Event (click)|
|-----------------|----------------------|--------------------------|-----------------------|
|setTimeout|fails|passes|passes|
|promises|fails|passes|passes|
|observable|fails|fails|fails|

Based on this line from the `ComponentFixture` API documentation, "This can be used to resume testing after events have triggered asynchronous activity or asynchronous change detection.", is it appropriate to say that both the `OnInit` and browser click are hooking into some event behavior that directly invoking the component instance skips?

It's still not clear to me what's going on with the `Observable` tests, other than that it looks like the component is consistently stable.

**Comment by JiaLiPassion** [comment]
I will check this one, Thanks!

**Comment by thw0rted** [comment]
Was `setInterval` intentionally excluded from this list?  I'm having a heck of a time setting up testing for a component that uses intervals...

**Comment by thw0rted** [comment]
@jenniferfell @JiaLiPassion can we get the "feature" label (and accompanying murder-bot tags) removed?  Improving the docs is not a "feature" and shouldn't be contingent on popular vote.

**Comment by jessicajaniuk** [comment]
We have this much more detailed page on `whenStable` here: https://angular.io/guide/testing-components-scenarios#whenstable. Marking this as done.
