### ISSUE TITLE
ng test not working with ngrx effects

### ISSUE THREAD

**Issue by amitcdubey** [angular/angular#27118]
Hi am new in angular ..i have created one application based on angular +ngrx ,but  while am using EffectsModule.forFeature in my module  ng test not working its not even call the app.component.spec.ts  ..every time getting 
Executed 0 of 0 ERROR

kindly let me know what I need to do

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
