### ISSUE TITLE
Url is only updated the first time with UrlUpdateStrategy = "eager"

### ISSUE THREAD

**Issue by marcinsydor** [angular/angular#27116]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router 

### Is this a regression?
It's a new future in ^7.1.0-rc.0

### Description

I have "protected" page and a guard which returns UrlTree object after 3s. As I expect the first time when I click "protected" link the url is updated to `/protected` and after 3 seconds to `/login` segment. And I see the login page content. 

When I click again "protected" link the url is changed to `/protected` but after 3 seconds the segment remaind the same. I think it sould see `/login` segment again.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-routing-eager-strategy

**Comment by jasonaden** [comment]
Awesome issue. Thanks for this one! I'll mark this for our next iteration and it should be pulled in within a couple weeks.
