### ISSUE TITLE
Core support for modal dialogs

### ISSUE THREAD

**Issue by kdekooter** [angular/angular#27114]
# 🚀 feature request
Support modal dialogs in the core of the framework.

### Describe the solution you'd like
Some service that can instantiate a dialog with a component determined at runtime. The component should be able to get data passed in and out back to the parent/calling component.

### Describe alternatives you've considered
I have looked at about 55 npm packages matching `ngx-*-modal-*`. Quality varies heavily, most of these modules are not actively maintained and have lots of open issues.

Next to that the only alternative is to adopt one of the huge UI libraries like material or bootstrap.

**Comment by skreborn** [comment]
You could simply use [CDK](https://slackstack.rapaxsoft.com/#15) from the Material team. You might need to combine two or more common behaviors for the desired effect (namely [Overlay](https://material.angular.io/cdk/overlay/overview) and [Portal](https://material.angular.io/cdk/portal/overview)), but the building blocks are definitely there.

**Comment by kdekooter** [comment]
Thanks for the suggestion. However I do not want to include a UI framework. Perfectly happy with my own lean and mean CSS.

**Comment by skreborn** [comment]
@kdekooter That is exactly what CDK provides. It gives you the machinery without any styles so that you can make it entirely your own.

**Comment by kdekooter** [comment]
I guess your link is pointing in the wrong direction? https://slackstack.rapaxsoft.com/#15

**Comment by kdekooter** [comment]
OK, but that would still mean a dependency on angular-material, right? I really don't get why core angular does not support such a basic use case.

**Comment by skreborn** [comment]
No, you would depend on [`@angular/cdk`](https://www.npmjs.com/package/@angular/cdk) only. [`@angular/material`](https://www.npmjs.com/package/@angular/material) itself builds on top of CDK.

**Comment by ChristopherKiss** [comment]
@kdekooter,

Angular doesn't support any other components out of the box, why should they support modals? What happens if someone wants to use a different ui framework that has modals? Now there are two implementations? Plus the angular team already supports modals in their cdk.

As @skreborn has said, you can use the cdk, which is the core building blocks you can use to create your own components, these don't contain styles and is a smaller package than angular material.

You suggested looking through various npm packages, I think there are solid packages no matter what styles you want to use.

Material, just use angular material
Bootstrap, there are several maintained packages for this, ng-bootstrap, ngx-bootstrap
Bulma, ng-wizi-bulma
Your own modals, use the cdk, or take a peek at how they do it in the cdk and roll your own package

**Comment by kdekooter** [comment]
@ChristopherKiss thank you for your response. I think every JS-frontend-framework should support modals out of the box because it is an essential and integral part of virtually every webapp. There is no argument about Angular supporting a router and an http client is there? Why the resistance of adding functionality that every web developer out there needs?

Unless CDK should be considered a "core-extension" to angular, of course. But for now it is presented as part of an optional UI layer. And still for modals "You might need to combine two or more common behaviors for the desired effect". A small recipe would be nice.

**Comment by skreborn** [comment]
@kdekooter The difference between dialogs and a router or HTTP client is that the former is strictly visual. It's outside of Angular core's goals to provide you with built-in components - that's what CDK is for.

Here's a [StackBlitz ](https://stackblitz.com/edit/angular-1m7zjl?file=src%2Fapp%2Fapp.component.ts) I whipped up in a few minutes to show you how simple it is to create your own styled modal dialogs using CDK. Read more about the strategies in the documentation. Please note that this is a very simple demonstration and you'd normally want to build at least a simple service around this to show arbitrary dialogs easily.

**Comment by kdekooter** [comment]
Thanks for your efforts @skreborn, I'll use your example as a starting point. 

And let's agree to disagree on what should be part of the core of a framework ;-). Closing the issue now.
