### ISSUE TITLE
`No provider for` error is thrown for optional dependency if it registered as existing which is missing.

### ISSUE THREAD

**Issue by WiseBird** [angular/angular#27111]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 No

### Description

 
In `app.component`:
```
constructor(
    @Inject(TOKEN) @Optional() public dep: any,
  ) {
  }
```
In `app.moduel`
```
  providers: [{
    provide: TOKEN,
    useExisting: TOKEN2, // There is no provider for TOKEN2
  }]
```
If `providers` section is removed - no error.

## 🔬 Minimal Reproduction

[https://stackblitz.com/edit/angular-3pgcnh](https://stackblitz.com/edit/angular-3pgcnh)

## 🔥 Exception or Error
<pre><code>

Error: StaticInjectorError(AppModule)[InjectionToken TOKEN -> InjectionToken TOKEN]:
StaticInjectorError(Platform: core)[InjectionToken TOKEN -> InjectionToken TOKEN]: 
NullInjectorError: No provider for InjectionToken TOKEN!

</code></pre>

## 🌍  Your Environment

**Angular Version:**
7.0.4

**Anything else relevant?**

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by WiseBird** [comment]
@mhevery This is clearly not a question. Can you please elaborate how `No provider` error for optional dependency is not a bug?
