### ISSUE TITLE
Router: Warn if navigateByUrl is called while a navigation is already running

### ISSUE THREAD

**Issue by jasonaden** [angular/angular#27124]
Navigations should only be called when the application is stable, from a routerLink click, or from the redirect API for guards.

We need a warning to be issued in dev mode when navigations are called imperatively from application code. This will show up when they are called from within routing events, guards, or resolvers, all of which are anti-patterns.

FW-675

**Comment by dawidgarus** [comment]
I can see no reason why, but I can give You real world example from my app how it would break things.
I have modal dialogues opened as auxiliary routes. When I send form that's inside modal I use navigateByUrl to close it, and from completely different place at the same time I use navigateByUrl to go to other page in my primary outlet as a result of state change when the form is sent. It's it intentional by design.
Such thing would be impossible if we were to restrict redirects to only from withing guards.

**Comment by jasonaden** [comment]
@dawidgarus Thanks for the use case.

I've updated the description. Please see if that clarifies.

The idea is that, in general, navigations shouldn't be called while a navigation is already running. For instance, from capturing a navigation event. Note that this is theoretically correct, but like you said in your example, there might be situations in practice where this just doesn't work.

Can you explain how this completely different place is capturing an event that ends up triggering `navigateByUrl`? Does the navigation used to close the modal not complete before the state changes and you navigate again? Is it a state change that initially causes the `navigateByUrl` that closes the modal, or is that handled differently?

Thanks for the use case. I would like to collect these before actually implementing since, as you're pointing out, there may be a number of places this assumption isn't correct.

**Comment by dawidgarus** [comment]
@jasonaden 
I store list of my items in a service (state).
I have a route to see list of items: `/list`, details of item: `/details/:id`, and auxiliary route to edit item: `(modal:edit/:id)`.
Lets say I open edit modal from details and I have a path `/details/:id(modal:edit/:id)`.
I can delete item from the edit modal. When I do so, I dispatch action "DELETE" and close modal using navigation and that's all that the modal cares.
Then in the details component I subscribe for the change in state in if current item is no longer available (and only then) I navigate to `/list`.
Both navigations are completely independent. For example, I could delete item (dispatch action "DELETE") from the list component or edit item (open modal) from the list (go to `/list(modal:edit/:id)`). The point is, I don't make assumptions what component deletes item or what component is behind modal.

Also, the restriction that navigation should not be called when navigation is already running make no sense. I can't see what's the point? What if I navigate to one page, but it take forever to load (resolve data) so I click to navigate to other. So I must use `RouterLink` directive? What if I don't use it. I have custom abstraction over angular router and my own directive. Or in some places I do `(click)="navigateWithComplexLogicToDetermineUrlBasedOnItem(item)"`.

**Comment by jasonaden** [comment]
Thanks for writing this up. I'm going to go ahead and close this issue based on this data.
