### ISSUE TITLE
select change event does not fire on form reset

### ISSUE THREAD

**Issue by Trisped** [angular/angular#27123]
# 🐞 bug report

### Affected Package

 Not sure which package caused this.

### Is this a regression?

 Unknown, I have not used previous versions.

### Description

 When a select (dropdown) is reset using ngForm.reset(), the change event of the select is not fired.

## 🔬 Minimal Reproduction

 http://next.plnkr.co/edit/fVtjb4khbqgrouyK?open=lib%2Fapp.ts&deferRun=1&preview

If you change the select from Option 1 to Option 2 an alert pops up, but if you reset the form (changing the selected item to null) no alert appears because the change event is not firing.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 6.1.2
Node: 8.11.3
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.2
@angular-devkit/core         0.7.2
@angular-devkit/schematics   0.7.2
@schematics/angular          0.7.2
@schematics/update           0.7.2
rxjs                         6.2.2
typescript                   2.7.2
</code></pre>

**Anything else relevant?**

Chrome Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by kara** [comment]
Thanks @trotyl for the detailed explanation. @Trisped As mentioned, this is working as intended.
