### ISSUE TITLE
Simplify relationship between Getting Started and Tutorial (TOH)

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#27126]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...
Currently, the Getting Started guide and the Tutorial (TOH) both describe how to create a workspace with a starter app, and make a basic modification to that app. If you do Getting Started, you throw that work away and create a new workspace and starter app for TOH. 

It would reduce content duplication and user rework if Getting Started created the app shell that can also be used for TOH. Then TOH can remove "The Application Shell" section (which is problematically numbered section 0) and pre-req doing the Getting Started. 

## 🔬 Minimal Reproduction
See description

### What's the affected URL?**
 https://angular.io/...
See https://angular.io/guide/quickstart and https://angular.io/tutorial/toh-pt0

### Reproduction Steps**

See description. Do Getting Started. Then do TOH Tutorial through to the end of "The Application Shell."

### Expected vs Actual Behavior**

See Description

## 📷Screenshot

none

## 🔥 Exception or Error
<pre><code>

none
</code></pre>

### Browser info

no

### Anything else relevant?

no

**Comment by jenniferfell** [comment]
Note: WIP on a completely new Getting Started/Tutorial, so the resources might be invested there instead. v7 TOH has been updated to be more clear about the need to create a new workspace for TOH, so that readers at least understand that they can't reuse the GS workspace.

**Comment by ajitsinghkaler** [comment]
@gkalpak @kapunahelewong I think we can close this now these are two very different modules.

**Comment by gkalpak** [comment]
Agreed. The sections are completely different now (one is an online store, the other a heroes dashboard), so they can't really build on top of each other.
