### ISSUE TITLE
Bug: Style bindings don't work with custom CSS properties

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#27131]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core and @angular/common

### Is this a regression?

 I don't think so

### Description
Using style bindings:
```typescript
<div [style.--custom-property]="'value'"></div>
<div [ngStyle]="{'--custom-property': 'value'}"></div>
```
doesn't work. Custom properties are not applied

EDIT: other cases that won't work either:
```typescript
<div [attr.style]="'--custom-property: value'"></div>
<div style="--custom-property: {{'value'}}"></div>
```

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-mke3le?file=src%2Fapp%2Fapp.component.html

## 🔥 Exception or Error
N/A

## 🌍  Your Environment

**Angular Version:**
<pre><code>@angular/common 7.0.1
@angular/compiler 7.0.1
@angular/core 7.0.1
@angular/forms 7.0.1
@angular/platform-browser 7.0.1
@angular/platform-browser-dynamic 7.0.1
@angular/router 7.0.1
core-js 2.5.7
rxjs 6.3.3
zone.js 0.8.26</code></pre>

**Anything else relevant?**
N/A

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/9343

**Comment by dawidgarus** [comment]
I'm closing as duplicate
