### ISSUE TITLE
build.sh is not compiling subpackage service-worker/worker

### ISSUE THREAD

**Issue by Serginho** [angular/angular#27137]
# 🐞 bug report

### Affected Package
@angular/service-worker

### Is this a regression?
I tested in 5.2.11 and works properly.
Not working on 7.0.3 and master

### Description
The script build.sh which is the root project is not compiling properly service worker package.
ngsw-worker.js, ngsw-config.js are not generated in dist/packages-dist/ 

## 🔬 Minimal Reproduction
execute ./build.sh on 7.0.3 or master.
ngsw-worker.js is not generated

## 🌍  Your Environment

**Angular Version:**
Tested on 7.0.3 and master.

**Comment by gkalpak** [comment]
You should really be using `scripts/build-packages-dist.sh`. (It might not work on Windows, though.)

Not sure what if `./build.sh` is used any more.
Maybe we should remove it (and update any docs that still mention it).

**Comment by Serginho** [comment]
I could solve it. In the version 5 the worker subpackage has a build.sh file that the main script uses to copy the service worker.
It's working with both files `build.sh`and `scripts/build-packages-dist.sh`.

Thanks @gkalpak
