### ISSUE TITLE
Tutorial should be clear immediately if the app fails at one step but will be fixed at a later step

### ISSUE THREAD

**Issue by ArunEdathadan** [angular/angular#27147]
### Description
When following the angular tutorial, some bugs are expected to occur, as the bug is not informed earlier
, I tried to fix it myself, and lost a lot of time. Happened multiple times in the angular tutorial.

When copy pasting code, as a developer, I expect it to work in each step. when its not working, I tried to fix,thinking its my mistake, only after finding a solution online, I go to next steps. Shit - this was supposed to happen. Then goes through rest of the documentation.

For eg  -  [Angular Tutorial](https://angular.io/tutorial/toh-pt2)

![chrome_2018-11-18_18-10-10](https://user-images.githubusercontent.com/16814342/48672548-38aabe80-eb5d-11e8-92c9-7447ebe49fcb.png)

**Comment by Gillespie59** [comment]
Can you give an example of bugs ?

**Comment by ArunEdathadan** [comment]
![chrome_2018-11-18_18-10-10](https://user-images.githubusercontent.com/16814342/48672558-5a0baa80-eb5d-11e8-8f16-b869cb70a463.png)

When copy pasting code, as a developer, I expect it to work in each step. when its not working, I tried to fix, only then goes through rest of the documentation.

**Comment by jenniferfell** [comment]
https://angular.io/tutorial/toh-pt2#update-the-details-template

**Comment by chembu** [comment]
fixed in #27329
