### ISSUE TITLE
Documentation states incorrectly that --progress is false by default

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [angular/angular#27146]
### Description
`--progress=true\|false - Log progress to the console while building. Default: false`

But it's true by default. Every new project outputs progress. You have to set it to false specifically, to see the difference.

### What's the affected URL?**
https://angular.io/cli/build

### Reproduction Steps**
ng new yourapp, ng build
observe the progress being reported to console

**Comment by gkalpak** [comment]
Duplicate of angular/angular-cli#12816. (Will be addressed by #27024.)
