### ISSUE TITLE
Angular Universal

### ISSUE THREAD

**Issue by Gaborpg** [angular/angular#27157]
Oh hi there! 😄

On the website under Angular universal I found an issue:

Step 5: Pack and run the app on the server
.

content_copy
@NgModule({ **### // you dont need ngModule** 
const path = require('path');
const webpack = require('webpack');

**Comment by trotyl** [comment]
Ref: https://github.com/angular/angular/pull/26959

**Comment by brandonroberts** [comment]
Fixed via #26959
