### ISSUE TITLE
ng add @angular/pwa not genreate manifest.json and ngsw-config.json file in project structure

### ISSUE THREAD

**Issue by rahulnaik2894** [angular/angular#27167]

**Comment by gkalpak** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
