### ISSUE TITLE
Dependency injection wraps into an extra object when passing to forRoot in a library

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#27166]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions
MacOS Mojave 10.14
Node: v10.13.0
npm: 6.4.1
@angular-devkit/\*: 0.10.6
@angular-devkit/\*: 7.0.6
@angular/cli: 7.0.6
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 7.0.6
@schematics/angular: 7.0.6
@schematics/update: 0.10.6
ng-packagr: 4.4.0
rxjs: 6.3.3
typescript: 3.1.6
webpack: 4.19.1

### Repro steps
I tried to compare this issue with another forRoot issues in this repo, but it seems that my reproduction is different.

To reproduce:

1. Clone https://github.com/maksymzav/ng-library
2. Run `npm i`
3. Build a library `ng build my-lib`
4. Build a project: `ng build --prod`
5. Serve the project: `cd dist/ng-library && static --port=4209`
6. Open in the browser http://127.0.0.1:4209/ and see the console.

In couple of words:
we have a `forRoot({ myToken: 'my token', myToken2: 'my token2', myToken3: 'my token3'})` call, that must assign 3 injection tokens:
MY_TOKEN =  'my token',
MY_TOKEN2 =  'my token2',
MY_TOKEN3 =  'my token3',
And we do have these 3 properly assigned injection tokens, when we run `ng serve`.

But when we run a production build `ng build --prod` we get:
MY_TOKEN = { myToken: 'my token', myToken2: 'my token2', myToken3: 'my token3'}
MY_TOKEN2 =  undefined,
MY_TOKEN3 =  undefined.

This behavior is inconsistent because for prod and dev builds we have different logic.

Relevant parts of the app:

> projects/my-lib/src/lib/my-lib.module.ts
```
export const MY_TOKEN = new InjectionToken('my.token');
export const MY_TOKEN2 = new InjectionToken('my.token2');
export const MY_TOKEN3 = new InjectionToken('my.token3');

@NgModule({
 ...
})
export class MyLibModule {
  static forRoot({myToken, myToken2, myToken3}): ModuleWithProviders {
    return {
      ...
      providers: [
        {provide: MY_TOKEN, useValue: myToken},
        {provide: MY_TOKEN2, useValue: myToken2},
        {provide: MY_TOKEN3, useValue: myToken3},
      ]
    };
  }
}
```
> projects/my-lib/src/lib/my-lib.service.ts
```
@Injectable({
  providedIn: 'root'
})
export class MyLibService {

  constructor(@Inject(MY_TOKEN) protected myToken, @Inject(MY_TOKEN2) protected myToken2, @Inject(MY_TOKEN3) protected myToken3) {
  }

  getMyToken() {
    return this.myToken;
  }

  getMyToken2() {
    return this.myToken2;
  }

  getMyToken3() {
    return this.myToken3;
  }
}

```
> ng-library/src/app/app.module.ts

```
@NgModule({
  ....
  imports: [
   ...
    MyLibModule.forRoot(
      {
        myToken: 'my token',
        myToken2: 'my token2',
        myToken3: 'my token3'
      },
    )
  ],
  ...
})
export class AppModule {
}
```
> ng-library/src/app/app.component.ts

```
constructor(protected myLibService: MyLibService) {
  }

  ngOnInit() {
    this.myToken = this.myLibService.getMyToken();
    this.myToken2 = this.myLibService.getMyToken2();
    this.myToken3 = this.myLibService.getMyToken3();
    console.log(this.myToken, this.myToken2, this.myToken3);
  }
```

So, if we `ng serve` the app, console outputs
my token, my token2, my token3

If we `ng build --prod`, console outputs:
{myToken: 'my token', myToken2: 'my token2', myToken3: 'my token3}, undefined, undefined

### Desired functionality
The behavior should be consistent, for `ng build --prod` we should the same injection token assignments, as for `ng serve`.

### Mention any other details that might be useful
The situation described above happens only when we accept an object destructuring assignment in the forRoot(). If we replace:
> projects/my-lib/src/lib/my-lib.module.ts
```
static forRoot({myToken, myToken2, myToken3}): ModuleWithProviders {
    return {
      ngModule: MyLibModule,
      providers: [
        {provide: MY_TOKEN, useValue: myToken},
        {provide: MY_TOKEN2, useValue: myToken2},
        {provide: MY_TOKEN3, useValue: myToken3},
      ]
    };
  }
```
with:
```
static forRoot(dependencies: {myToken, myToken2, myToken3}): ModuleWithProviders {
    return {
      ngModule: MyLibModule,
      providers: [
        {provide: MY_TOKEN, useValue: dependencies.myToken},
        {provide: MY_TOKEN2, useValue: dependencies.myToken2},
        {provide: MY_TOKEN3, useValue: dependencies.myToken3},
      ]
    };
  }
```

then everything works as the same as we run `ng serve`, so for both cases console.log outputs:
my token my token2 my token3

Opened from: https://github.com/angular/angular-cli/issues/12971
//cc @maksymzav

 I had a quick look at this and it seems the issue is coming from the AOT compiler. As even disabling build optimizer and minificiation the result is the same.

Also the above deconstruction seems to be generated as 3 parameters in the metadata.

```
"forRoot": {
    "__symbolic": "function",
    "parameters": [
        "myToken",
        "myToken2",
        "myToken3"
    ],
...
}
```

**Comment by dawidgarus** [comment]
It's not a bug but documented behavior: https://angular.io/guide/aot-compiler#destructured-variable-not-supported

**Comment by trotyl** [comment]
Possibly it can be made a feature request for explicit error message? Silent failure with unexpected result is no good for user.
