### ISSUE TITLE
API Proposal for Shallow Rendering 

### ISSUE THREAD

**Issue by michaeljota** [angular/angular#27174]
# 🚀 feature request

### Relevant Package

 
This feature request is for `@angular/core/testing`

### Description
 A clear and concise description of the problem or missing capability...

If I want to test a component, I must provide a mock or implementation of components, providers, pipes, and others dependencies my component have. Shallow Rendering is the ability to provide a rendered component without providing any additional dependency, as all the dependencies are being handled by the framework. 

Shallow Rendering have been requested before, #17474, #22797, and maybe others. Notice that #17474 has been closed by the OP, so I'm open this to continue making the request for this feature, and also to discuss a posible implementation of this.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

I would like to be able to request a component fixture without providing all the dependencies information. I request explicitly for a shallow rendering. This could be done with a new static method of the `TestBed` object. 

```ts
fixture = TestBed.shallowRender(AppComponent);
```

Notice that I don't want to pass any other arguments to this, but just the component I want to test.

#### Mocking strategy proposal:

- __Components__: I think that other components should only use `<ng-content></ng-content>` as a template to just print whatever the main component whats to print inside. 
- __Directives__: I think normal directives can be ignored. However, I don't think that template directives should be mocked, as they can change the template output. Maybe just provide common template directives out the box if the user request for a shallow rendered component. 
- __Pipes__: Pipes should return the input value. This way the user can test that the output value is being showed in the template. 
- __Services__: I think services is the most complicated dependency to mock. `Proxy` could be used for mocking function calls, and properties gets, but they won't provide any value. However, I think this could be the most compromised way to do this right. If the user wants a service to provide a specific value, then the user should provide a mock for that service, using `configureTestingModule` or `overrideProvider` methods of `TestBed`. 

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

The current workaround it's to mock, or implement every dependency of a component. 

There are several tools and packages to help with this task:

- [ng-mocks](https://github.com/ike18t/ng-mocks). This works in the intent to mock components, pipes, and others dependencies, but this doesn't provide any way to mock services. However, this seems to be very depended of private APIs of Angular, so it could break if any of those API are changed at any time.
- [shallow-render](https://github.com/getsaf/shallow-render) (I think this use ng-mocks underneath)

**Comment by dblVs** [comment]
@michaeljota I don't know if you still deal with angular, but this is not very straight forward as it seems. Things get complex as soon as templates and content projection get involved.
Example being how will this be shallow rendered

```
<some-component>
  <some-other-component selectorForTheTransclusionSlot></some-other-component>
</some-component>
```
Also what about this
```
<some-component>
  <ng-template let-variable> {{ variable }} </ng-template>
</some-component>
```

P.S. I'm the OP of #17474
The reason why I closed the issue was because I realised that as soon as you venture into something more complex most solutions for mocking fail and you need to create a specific one for your case. There are few more interesting cases like querying (ViewChild/Children, ContentChild/Children) that reads the component instance, where if you mocked it, the object might be in a wrong shape. Hence in my company we went ahead with custom made mocks. 

Although a simple version of this might still be cool. (one which doesn't support content projection and querying)

**Comment by michaeljota** [comment]
I still use Angular, not as my main framework as right now, but I just love it. And after a few with React, I just see this is really something that would improve Angular testing. Angular is powerful enough to let you do something like this for simple components, and configure the TestBed as you want, for complex ones, like the one in your example.

I don't think this will replace every use case, but it would lower the bar for newbies.
