### ISSUE TITLE
higher module that imports error

### ISSUE THREAD

**Issue by shirmukesh** [angular/angular#27173]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: 
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by shirmukesh** [comment]
ERROR in : Type LovdialogComponent in D:/TakeBkp/IMMSTNG/IMMS-TNG/IMMSTNGWEB/AngularWeb/TNGWeb/src/app/shared/lovdialog/lovdialog.component.ts is part of the declarations of 2 modules: EmailModule in D:/TakeBkp/IMMSTNG/IMMS-TNG/IMMSTNGWEB/AngularWeb/TNGWeb/src/app/email/email.module.ts and sharedComponetModule in D:/TakeBkp/IMMSTNG/IMMS-TNG/IMMSTNGWEB/AngularWeb/TNGWeb/src/app/shared/comman/models/SharedComponet.module.ts! Please consider moving LovdialogComponent in D:/TakeBkp/IMMSTNG/IMMS-TNG/IMMSTNGWEB/AngularWeb/TNGWeb/src/app/shared/lovdialog/lovdialog.component.ts to a higher module that imports EmailModule in D:/TakeBkp/IMMSTNG/IMMS-TNG/IMMSTNGWEB/AngularWeb/TNGWeb/src/app/email/email.module.ts and sharedComponetModule in D:/TakeBkp/IMMSTNG/IMMS-TNG/IMMSTNGWEB/AngularWeb/TNGWeb/src/app/shared/comman/models/SharedComponet.module.ts. You can also create a new NgModule that exports and includes LovdialogComponent in D:/TakeBkp/IMMSTNG/IMMS-TNG/IMMSTNGWEB/AngularWeb/TNGWeb/src/app/shared/lovdialog/lovdialog.component.ts then import that NgModule in EmailModule in D:/TakeBkp/IMMSTNG/IMMS-TNG/IMMSTNGWEB/AngularWeb/TNGWeb/src/app/email/email.module.ts and sharedComponetModule in D:/TakeBkp/IMMSTNG/IMMS-TNG/IMMSTNGWEB/AngularWeb/TNGWeb/src/app/shared/comman/models/SharedComponet.module.ts.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
