### ISSUE TITLE
Prefetch Component Data Missing file

### ISSUE THREAD

**Issue by phamhuy** [angular/angular#27187]
# 📚 Docs or angular.io bug report

### Description
In Angular documentation > Fundamentals > Routing & Navigation > Prefetch Component Data > Details of files, the crisis-detail.component.html file is included twice, and the crisis-detail.component.ts is missing.

### What's the affected URL?**
https://angular.io/guide/router#resolve-pre-fetching-component-data

### Expected vs Actual Behavior**
One of the crisis-detail.component.html should be crisis-detail.component.ts instead.

## 📷Screenshot
![image](https://user-images.githubusercontent.com/6052918/48767001-85c88680-ec6a-11e8-98d3-068cbc1e998d.png)

**Comment by FrederikSchlemmer** [comment]
Created a pull request for this issue! PR #27505

**Comment by brandonroberts** [comment]
Fixed via #27025
