### ISSUE TITLE
ci: pullapprove sometimes gets stuck in pending commit status state in spite of all the approvals received

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#27199]
Example PR: https://github.com/angular/angular/pull/27193

PR approved on github:
![screen shot 2018-11-20 at 11 33 12 am](https://user-images.githubusercontent.com/216296/48797859-298c5380-ecb8-11e8-840f-880829ea3a16.png)

Pullapprove not reflecting it and reporting missing approval for docs-infra group:
![screen shot 2018-11-20 at 11 33 18 am](https://user-images.githubusercontent.com/216296/48797878-327d2500-ecb8-11e8-9302-415e02716942.png)

The same state is reported in the pullapprove ui:
![screen shot 2018-11-20 at 11 33 26 am](https://user-images.githubusercontent.com/216296/48797896-3f9a1400-ecb8-11e8-98b3-ef53c301fc33.png)

But in the same ui the config shows that IgorMinar is in the docs-infra group, so the PR should have been considered as approved:
![screen shot 2018-11-20 at 11 33 41 am](https://user-images.githubusercontent.com/216296/48797951-61939680-ecb8-11e8-885c-1e6d9f928f0c.png)

It seems that the issue happens when a review initially requested changes, but later approved the PR. The later approval is not being registered by pullapprove. See the following for the same PR where it's clear that pullapprove is only aware of the inital rejection (request for change) and not the following approval:

![screen shot 2018-11-20 at 11 41 38 am](https://user-images.githubusercontent.com/216296/48798431-80465d00-ecb9-11e8-8693-b0b08329cd74.png)

Possible solutions:
* Pullapprove v3 supposedly solves some of these reliability issues but we don't have a guarantee that we won't see this problem again
  * https://medium.com/dropseed/introducing-pullapprove-version-3-4da68e14a623
  * https://www.pullapprove.com/docs/migration/
* We could consider using GitHub Owners instead, but we'd lose some features and have to go through a more complex migration. The tighter integration with PRs might however be worth it.
  * https://blog.github.com/2017-07-06-introducing-code-owners/
  * https://help.github.com/articles/about-codeowners/

Workaround:
* go the the pullapprove UI
* go to the reviews tab
* set the approval via the UI for the group where approval is missing
* use the wrench icon to "re-send status to GitHub"

**Comment by gkalpak** [comment]
I assume this is now obsolete thanks to #27690. Closing...
