### ISSUE TITLE
ng-component element not removing after routerLink clicked in the Edge browser

### ISSUE THREAD

**Issue by ngor83** [angular/angular#27191]
Hello.
Situation is following:
Angular 6 site, with header logo that redirect to main page, the html looks like

div class="header-logo">
a [routerLink]="['/']" >...</a
/div>

from the page localhost:4200/someurlpart/someurlpart

If user clicks on logo and redirected to the main page and in Edge browser ng-component from last page not removing, and content from previous page become shown after content of main page 
...
ng-component>...</ng-component
ng-component>...</ng-component
...

The Chrome browser delete second <ng-component> element after page loaded, but Edge not, please help, seems like a bug for Edge browser.

There is bug here?

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
