### ISSUE TITLE
ci: restrict CircleCI access to angular/angular

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#27201]
Per CircleCI support, we could restrict the write access CircleCI has to our repo via [OAuth App Access Restrictions](https://help.github.com/articles/enabling-oauth-app-access-restrictions-for-your-organization/).

See https://github.com/orgs/angular/policies/applications/68021 

We currently don't have this option enabled on our repo, but we should turn it on. This will unfortunately mean that we'll need to re-authorize all the other integrations we have for all of our repos, so it will take some coordination work. 

// @jelbourn has been interested in resolving this as well.

**Comment by jelbourn** [comment]
@josephperrott @IgorMinar confirming that we still care about resolving this at some point, yes? Anything actionable with CircleCI?

**Comment by josephperrott** [comment]
Yes, this is something we should eventually get to.  At this point it does not seem that there is anything from CircleCI that we need.

**Comment by jessicajaniuk** [comment]
@josephperrott Is this still needed?
