### ISSUE TITLE
Enum types generated improperly by ng build [libName].

### ISSUE THREAD

**Issue by damienwebdev** [angular/angular#27214]
# 🐞 bug report

### Affected Package
I believe this is a bug in `@angular/compiler` or `ng-packagr`, but I'm not 100% sure.

### Is this a regression?
This is my first time trying something like this, so I'm unaware whether or not it is a regression.

### Description
When compiling an Angular library, the type generated for an enum by `ng build [libName`] is slightly different than the one in source, causing some unexpected compile-time typing errors.

For example, here is the original typescript file

```ts
import { Action } from '@ngrx/store';

export enum CartActionTypes {
    CartLoadAction = "[Cart] Load Action",
    CartResetAction = "[Cart] Reset Action"
}

export class CartLoad implements Action {
  readonly type = CartActionTypes.CartLoadAction;
}
export class CartReset implements Action {
    readonly type = CartActionTypes.CartResetAction;
}

export type CartActions = 
    | CartLoad 
    | CartReset;
```

When going through a build, the final output type is 

```ts
export declare enum CartActionTypes {
    CartLoadAction = "[Cart] Load Action",
    CartResetAction = "[Cart] Reset Action"
}
export declare class CartLoad implements Action {
    readonly type: CartActionTypes;
}

export declare class CartReset implements Action {
    readonly type: CartActionTypes;
}
export declare type CartActions = CartLoad | CartReset;
```

You can see for example that:

```ts
export class CartReset implements Action {
    readonly type = CartActionTypes.CartResetAction;
}
```

changed to:

```ts
export declare class CartReset implements Action {
    readonly type: CartActionTypes;
}
```

This change in the type of `type` from `CartActionTypes.CartResetAction` to `CartActionTypes` causes down-stream effects in consuming libraries/apps that depend on matching the proper enum type in switch/case statement like:

```ts
import { ProductModalActionTypes, ProductModalActions } from '../actions/product-modal.actions';
import { AddToCart, CartActionTypes, CartLoad } from '@daffodil/state';

export interface State {
  showProductModal: boolean,
  productQty: number
}

export const initialState: State = {
  showProductModal: false,
  productQty: 0
};

export function reducer(state = initialState, action: ProductModalActions | AddToCart | CartLoad): State {
  switch (action.type) {
    case ProductModalActionTypes.ShowProductModalAction:
      return {...state, showProductModal: !state.showProductModal};
    case ProductModalActionTypes.CloseProductModalAction:
      return {...state, showProductModal: false};
    case CartActionTypes.AddToCartAction:
      return {...state, productQty: action.payload.qty};
    default:
      return state;
  }
}
```

## 🔥 Exception or Error
The error is a type error on `action.payload.qty` indicating that 
```
`payload` does not exist on an action of type `AddToCart | CartLoad`.
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 6.2.4
Node: 9.2.1
OS: darwin x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.8.4
@angular-devkit/build-angular      0.8.4
@angular-devkit/build-ng-packagr   0.8.4
@angular-devkit/build-optimizer    0.8.4
@angular-devkit/build-webpack      0.8.4
@angular-devkit/core               0.8.4
@angular-devkit/schematics         0.8.4
@angular/cdk                       6.4.7
@angular/cli                       6.2.4
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.2.4
@schematics/angular                0.8.4
@schematics/update                 0.8.4
ng-packagr                         4.2.0
rxjs                               6.3.3
typescript                         2.9.2
webpack                            4.20.2
</code></pre>

**Comment by ChrisDahmCS** [comment]
Hey @damienwebdev!

I was wondering what the `AddToCart` and `CartLoad` look like in `import { AddToCart, CartActionTypes, CartLoad } from '@daffodil/state';`. I'm familiar with running into the error you are seeing is when my Action class don't have a `constructor(public payload: <your-type>) {}`. This is because the default `Action` type [(seen here)](https://github.com/ngrx/platform/blob/master/modules/store/src/models.ts#L1-L3) does not have a `payload` (it was removed somewhere between versions 2 and 4 I believe). There is [this StackOverflow answer](https://stackoverflow.com/a/45414250) explaining more about that with the Action API for @ngrx.

Example Steps:

`ng new test-actions`
`cd test-actions`
`npm i -s @ngrx/store @ngrx/effects`
`ng g library state-lib --prefix sl`

Now under `test-actions/projects/state-lib/src/lib`, create an "actions" file (mine is `cart.action.ts` to try and emulate yours).
I export that from within the `public_api.ts`.

I've expanded my action to show both a payload and no payload example:
```
import {Action} from '@ngrx/store';

export enum CartActionTypesNoPayload {
  CartLoadActionNoPayload = '[Cart] Load Action No Payload',
  CartResetActionNoPayload = '[Cart] Reset Action No Payload'
}

export class CartLoadNP implements Action {
  readonly type = CartActionTypesNoPayload.CartLoadActionNoPayload;
}

export class CartResetNP implements Action {
  readonly type = CartActionTypesNoPayload.CartResetActionNoPayload;
}

export type CartActionsNoPayload =
  | CartLoadNP
  | CartResetNP
  ;

export enum CartActionTypesHasPayload {
  CartLoadActionHasPayload = '[Cart] Load Action Has Payload',
  CartResetActionHasPayload = '[Cart] Reset Action Has Payload'
}

export class CartLoadHP implements Action {
  readonly type = CartActionTypesHasPayload.CartLoadActionHasPayload;
  constructor(payload: any) {}
}

export class CartResetHP implements Action {
  readonly type = CartActionTypesHasPayload.CartResetActionHasPayload;
  constructor(payload: any) {}
}

export type CartActionsHasPayload =
  | CartLoadHP
  | CartResetHP
  ;
```

Now I build the lib `ng build state-lib` and get the following cart.action.d.ts:
```
import { Action } from '@ngrx/store';
export declare enum CartActionTypesNoPayload {
    CartLoadActionNoPayload = "[Cart] Load Action No Payload",
    CartResetActionNoPayload = "[Cart] Reset Action No Payload",
}
export declare class CartLoadNP implements Action {
    readonly type: CartActionTypesNoPayload;
}
export declare class CartResetNP implements Action {
    readonly type: CartActionTypesNoPayload;
}
export declare type CartActionsNoPayload = CartLoadNP | CartResetNP;
export declare enum CartActionTypesHasPayload {
    CartLoadActionHasPayload = "[Cart] Load Action Has Payload",
    CartResetActionHasPayload = "[Cart] Reset Action Has Payload",
}
export declare class CartLoadHP implements Action {
    readonly type: CartActionTypesHasPayload;
    constructor(payload: any);
}
export declare class CartResetHP implements Action {
    readonly type: CartActionTypesHasPayload;
    constructor(payload: any);
}
export declare type CartActionsHasPayload = CartLoadHP | CartResetHP;
```

Now I add the `reducer.ts` file under `test-actions/src/app` with the following contents:
```
import {
  CartActionTypesHasPayload,
  CartActionTypesNoPayload,
  CartLoadHP,
  CartLoadNP
} from '../../projects/state-lib/src/lib/cart.action';

export interface State {
  showProductModal: boolean;
  productQty: number;
}

export const initialState: State = {
  showProductModal: false,
  productQty: 0
};

export function reducer(state = initialState, action: CartLoadNP | CartLoadHP): State {
  switch (action.type) {
    case CartActionTypesNoPayload.CartLoadActionNoPayload:
      return {...state, showProductModal: !state.showProductModal};
    case CartActionTypesHasPayload.CartLoadActionHasPayload:
      return {...state, productQty: action.payload.qty};
    default:
      return state;
  }
}
```

Attempting to build the file as such:
```
import {
  CartActionTypesHasPayload,
  CartActionTypesNoPayload,
  CartLoadHP,
  CartLoadNP
} from '../../projects/state-lib/src/lib/cart.action';

export interface State {
  showProductModal: boolean;
  productQty: number;
}

export const initialState: State = {
  showProductModal: false,
  productQty: 0
};

export function reducer(state = initialState, action: CartLoadNP | CartLoadHP): State {
  switch (action.type) {
    case CartActionTypesNoPayload.CartLoadActionNoPayload:
      return {...state, productQty: action.payload.qty};
    case CartActionTypesHasPayload.CartLoadActionHasPayload:
      return {...state, productQty: action.payload.qty};
    default:
      return state;
  }
}
```

results in the same error you are seeing. 

Does adding the `constructor(public payload: <your-type>) {}` to your CartActionTypes.AddToCartAction solve the issue?

**Comment by damienwebdev** [comment]
@ChrisDahmCS it wouldn't. But I have a few actions that are payloadless, so a constructor is not needed at all.

**Comment by damienwebdev** [comment]
@ChrisDahmCS 

> I was wondering what the AddToCart and CartLoad look like in import { AddToCart, CartActionTypes, CartLoad } from '@daffodil/state';

These are listed above, but[ you can see the source.](https://github.com/graycoreio/daffodil/blob/develop/libs/state/src/cart/actions/cart.actions.ts)

>  I'm familiar with running into the error you are seeing is when my Action class don't have a constructor(public payload: <your-type>) {}. This is because the default Action type (seen here) does not have a payload (it was removed somewhere between versions 2 and 4 I believe).

Yes, that is partially correct, but also only part of the problem. The `Action` type does not need nor warrant a payload in every case. 

Your `cart.action.d.ts` also highlights the issue I'm trying to show:

```
export class CartLoadHP implements Action {
  readonly type = CartActionTypesHasPayload.CartLoadActionHasPayload;
  constructor(payload: any) {}
}
```

becomes:

```
export declare class CartLoadHP implements Action {
    readonly type: CartActionTypesHasPayload;
    constructor(payload: any);
}
```

The enum type **clearly** changed as a result of the build when it absolutely should not have. Granted, my compiler theory and typescript is weak, but at the very least, I believe this is a bug, and not intentional.

**Comment by ChrisDahmCS** [comment]
@damienwebdev yes, I think that is because when you create the class, `readonly type = CartActionTypesHasPayload.CartLoadActionHasPayload;` is setting the value, however `readonly type: CartActionTypesHasPayload;` is showing the actual type (the enum).

**Comment by damienwebdev** [comment]
Hrm, well, maybe I'm misunderstanding something.  The issue is that when used in a switch case in the same module (as opposed imported from a post-build library) the type inference works just fine.

**Comment by damienwebdev** [comment]
@ChrisDahmCS did you `ng build` using cli7 or cli6?

**Comment by ChrisDahmCS** [comment]
I am at cli7, but will work on a stackblitz for cli6 so we can be on the same boat-

**Comment by damienwebdev** [comment]
@ChrisDahmCS Actually, upon upgrading to ng7, the result is actually quite different and resolves this issue. 

```
import { Action } from '@ngrx/store';

export declare enum CartActionTypes {
    CartLoadAction = "[Cart] Load Action",
    AddToCartAction = "[Cart] Add To Cart Action",
}
export declare class CartLoad implements Action {
    readonly type = CartActionTypes.CartLoadAction;
    constructor();
}
export declare class AddToCart implements Action {
    payload: {
        productId: string;
        qty: number;
    };
    readonly type = CartActionTypes.AddToCartAction;
    constructor(payload: {
        productId: string;
        qty: number;
    });
}

export declare type CartActions = CartLoad | AddToCart;
```

**Comment by ChrisDahmCS** [comment]
Oh wow, that's actually incredible. Do you know if there was a bug already worked resolved for it after 6.1.9?

**Comment by damienwebdev** [comment]
@ChrisDahmCS I did a cursory overview of the changelog and the bug list, and didn't see anything related to this, which I found rather surprising.

If anyone on the core team could just respond with the relevant commit/PR that changed this functionality, I'd appreciate it, hopefully it could provide clarity to any future visitors.

**Comment by ChrisDahmCS** [comment]
In any case, I'm glad it's working for you!
