### ISSUE TITLE
Ang 7 draggable anchor bug

### ISSUE THREAD

**Issue by dcarlsoncityworks** [angular/angular#27219]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/cdk/drag-drop

### Is this a regression?

No, dragging is a new feature in Ang 7

### Description

When I create a draggable anchor, Firefox thinks I am trying to drag the anchor, so I have to click and then release the mouse click in order for angular dragging to begin.

## 🔬 Minimal Reproduction
<a cdkDrag>Drag me!!</a>

## 🌍  Your Environment

**Angular Version:**
7.0

**Anything else relevant?**

Firefox 63.0.3 (64-bit)
A temporary fix:
<a cdkDrag ondragstart="event.preventDefault()">Drag me!!</a>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
