### ISSUE TITLE
Url service - what do we need ?

### ISSUE THREAD

**Issue by vicb** [angular/angular#2722]
As part of #2563, the former implementation of the `UrlResolver` which was relying on an anchor element to resolve urls has been replaced by a programmatic resolution.

Benefits:
- The resolver could be used in a server or web worker env,
- Absolute urls can be resolved, ie `resolve('http://ng.io/path/to.html', '/other/path')`

[The code](https://github.com/angular/angular/blob/master/modules/angular2/src/services/url_resolver.ts) is copied over from Traceur but is heavily based on the [Closure lib](https://github.com/google/closure-library/blob/master/closure/goog/uri/uri.js).

One idea from @tbosch would be to re-use the code (& tests) from closure. 

We probably should take this opportunity to expand the `UrlResolver` to a more generic `Url` service that could be re-used, ie by the router.

To discuss:
- [ ] what methods do we need in this service (in addition to `resolve()`)
- [ ] what library should we use (ie closure or ...)

/cc @btford @IgorMinar could you please add your thoughts here ?

**Comment by vicb** [comment]
One possibilty might be to use JS native [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) - we would need a polyfill when this is not available.

ref:
- https://gist.github.com/Yaffle/1088850 (used by SystemJS),
- https://github.com/Polymer/URL

**Comment by IgorMinar** [comment]
in Angular 1 we have this urlUtil library that we use for parsing urls: https://github.com/angular/angular.js/blob/master/src/ng/urlUtils.js

it relies on the internal browser parser and works on all browsers down to IE8 or 9.

the only downside is that it requires DOM, which would be problematic in node.js, but there we have parse5 so it should be fine too.

Could that be used instead?

**Comment by mhevery** [comment]
@vicb what is the update on this? Still a valid issue?

**Comment by vicb** [comment]
I think it would still be nice to find a more generic solution. I'll investigate parse5 (I hadn't seen the Igor's comment)
