### ISSUE TITLE
Scripts for running an universal app should be added to package.json instead of angular.json

### ISSUE THREAD

**Issue by kimamula** [angular/angular#27224]
# 📚 Docs or angular.io bug report

### Description

"Step 5: Pack and run the app on the server - Creating scripts" section says that you can add scripts that can be run with `npm run` in the "server" section of `angular.json`.

It is likely these scripts should be added to `package.json` instead.

### What's the affected URL?**
https://angular.io/guide/universal#creating-scripts

**Comment by vikerman** [comment]
Ugh - Correct. It should have said package.json and the example should look like package.json. Will send a PR shortly.

**Comment by jenniferfell** [comment]
@vikerman How does the server section of package.json relate to the server section within a project's config settings in angular.json?

**Comment by jenniferfell** [comment]
@jbogarthyde FYI

**Comment by vikerman** [comment]
They are not related. We add some useful scripts in package.json that lets you build and run the Node.js server.

**Comment by jlguenego** [comment]
While correcting this part of the documentation, there is much more to refactor.
Fortunately, at current time, the linked project is working. So it allows me to fill the gap.

But for a better developer experience, it would be better to resync the doc.

**Comment by brandonroberts** [comment]
Closing as resolved. The universal guide has been rewritten
