### ISSUE TITLE
Unable to logout on  chrome and firefox in Angular6 + windows authentication 

### ISSUE THREAD

**Issue by ankurjasoria** [angular/angular#27226]
Hi All,

We are stuck in middle when implementing windows authentication on Angular6 and facing below issue 

Issue : Unable to logout on  chrome and firefox in Angular6 + windows authentication  and 
We have successfully did logout in IE browser.

So please help me for same.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
