### ISSUE TITLE
Language Service. Throws `Component '...' is not included in a module` for exported test components

### ISSUE THREAD

**Issue by WiseBird** [angular/angular#27227]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/language-service

### Is this a regression?

 No

### Description

 
[Test host component](https://angular.io/guide/testing#component-inside-a-test-host) reported as not included into a module if it is exported from `spec` file.

```
@Component({
  selector: 'app-test',
  template: ``,
})
export class TestHostComponent {
}

...

    TestBed.configureTestingModule({
      declarations: [
        AppComponent,
        TestHostComponent,
      ],
...
```

I need it exported because we split spec file in two - one with configuration and helper classes and other with tests.

## 🔬 Minimal Reproduction

 
[https://github.com/WiseBird/angular-ls-spec-host-component](https://github.com/WiseBird/angular-ls-spec-host-component)

## 🔥 Exception or Error
<pre><code>
Component 'TestHostComponent' is not included in a module and will not be available inside a template. Consider adding it to a NgModule declaration
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.0.6
Node: 8.9.3
OS: linux x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.6
@angular-devkit/build-angular     0.10.6
@angular-devkit/build-optimizer   0.10.6
@angular-devkit/build-webpack     0.10.6
@angular-devkit/core              7.0.6
@angular-devkit/schematics        7.0.6
@angular/cli                      7.0.6
@ngtools/webpack                  7.0.6
@schematics/angular               7.0.6
@schematics/update                0.10.6
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1

</code></pre>

**Anything else relevant?**

IDE - WebStorm 2018.3

**Comment by igabesz** [comment]
I've got the same error when creating components that are lazy-loaded and used in dynamically created components. In such cases the compiler cannot know whether such components will be used in any modules. 

Related to: #13726

**Comment by kyliau** [comment]
This should not be an issue anymore, now that the v9 extension is released. Please open a new issue if this is not the case. The latest version could be downloaded from https://marketplace.visualstudio.com/items?itemName=Angular.ng-template
