### ISSUE TITLE
Managing subscription with route reuse strategy

### ISSUE THREAD

**Issue by NandhaKumar63** [angular/angular#27229]
I am using **RouteReuseStrategy** for saving the current route when I navigate from Page A to Page B,
when I navigate back from Page B to Page A, I am reusing the saved snapshot of Page A component.

In this particular scenario the Page A subscription is still live due to **RouteReuseStrategy** doesn't destroy the Page A component(**On Destroy** only I unsubscribed all the subscription).

So if I navigate from Page C or D component, I am re-initializing the Page A Component, at that time there will be 2 instances of Page A Component. Due to which the subscription is calling twice. 

Is there any way to handle the manual subscription and angular's internal subscriptions for that specific Page A Component and its child Components.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by jasonaden** [comment]
Closing based on above
