### ISSUE TITLE
Does it still worth to open pull requests?

### ISSUE THREAD

**Issue by natcohen** [angular/angular#27231]
Maybe it's a little bit provocative  (so please take it with a grain of salt).

For the last month, only 2 have been merged while 91 have been opened. So the question is, I think, legitimate...

**Comment by natcohen** [comment]
Not sure what you mean by "Closed" by github... here is what I see:

![image](https://user-images.githubusercontent.com/7813574/48910293-dbba4b80-ee6f-11e8-8fd8-3bb4a2ceb8a1.png)

I don't think you can merge pull requests without doing so through github, I might be wrong though.

**Comment by pkozlowski-opensource** [comment]
> I don't think you can merge pull requests without doing so through github, I might be wrong though.

You definitively can by pushing a commit with a reference to the PR, ex. my PR https://github.com/angular/angular/pull/27196 opened and merged yesterday.

GitHub won't count such PRs as "merged" in the stats that you are sharing. As such those stats are not really relevant given the merging method we are using...

**Comment by sarunint** [comment]
@natcohen, that's a valid question. I myself got confused the first time sending a PR as well.

Angular's repository has 2 active branches: patch and master. Each PR will be categorised by the caretaker, aka, the person who is responsible for the merge, either `PR target: master & patch`, `PR target: master only` or `PR target: patch only`. After the PR has been approved by the Angular team, the care taker will cherry pick into each respective branch accordingly. So you will see `#<PRnumber> has been closed in <SHA>` and the PR status is changed to `closed`, not `merged`.

To clarify even more, the patch branch is what minor version is doing, for instance, the current version is 7.1.0, patch branch is `7.1.x`. The master branch is what will become 7.2.0.

**Comment by sarunint** [comment]
Also, there is `PR target: LTS-only` for LTS branches.

**Comment by natcohen** [comment]
@pkozlowski-opensource Good to know... My comment comes from the frustration of a bug I am struggling with for more than 2 years. At the time, a PR has been proposed. I have tried myself to propose a PR 2 weeks ago since the bug has been forgotten by the angular team. I have very little hope when I see the statistic of 2 PR merged/month.

I really want this bug to be fixed, it is a blocking issue for me and I am willing to help the team but I can't even grab the attention of anyone from the team. What can I do?

@sarunint Thanks for the clarification!

**Comment by natcohen** [comment]
@pkozlowski-opensource I understand Google has to make sure everything done on Angular has to meet its standards but contributing to such project is almost impossible. Most PRs are being ignored even though they pass all the tests.

I am not saying Google should completely change the way they develop Angular but the team should at least consider more its contributors and their effort to fix the problem they encounter.
