### ISSUE TITLE
@angular/service-worker wrong peerDependency in 7.1.0

### ISSUE THREAD

**Issue by tpeter1985** [angular/angular#27233]
# 🐞 bug report

### Affected Package
The issue is caused by package _@angular/service-worker_.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 7.0.4

### Description

When updating a pwa enabled project from angular 6 to angular 7 it breaks since 7.1.0 was released.
The following Command fails:
_ng update @angular/cli @angular/core_

**Workaround: Call this instead: _ng update @angular/cli@7.0.4 @angular/core@7.0.4_**

## 🔥 Exception or Error
<pre><code>
Package "@angular/service-worker" has an incompatible peer dependency to "@angular/core" (requires "7.0.4" (extended), would install "7.1.0").
Package "@angular/service-worker" has an incompatible peer dependency to "@angular/common" (requires "7.0.4" (extended), would install "7.1.0").
Package "@angular/service-worker" has an incompatible peer dependency to "@angular/core" (requires "7.0.4", would install "7.1.0")
Incompatible peer dependencies found. See above.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.4.7
@angular/cli                      6.2.7
@angular/flex-layout              6.0.0-beta.18
@angular/material                 6.4.7
@angular/pwa                      0.6.8
@ngtools/webpack                  6.1.5
@schematics/angular               0.6.8
@schematics/update                0.8.7
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.9.2

</code></pre>

**Anything else relevant?**
In my opinion this happens because of the wrong peer dependencies in package.json of @angular/service-worker@7.1.0.

<pre><code>
"peerDependencies": {
    "@angular/core": "7.0.4",
    "@angular/common": "7.0.4"
  },
</code></pre>

**Comment by gkalpak** [comment]
I see the correct peer dependencies in [@angular/service-worker@7.1.0][1]. It might be an issue with `ng update`.
Please, report on the [@angular/cli repo][2].

[1]: https://unpkg.com/@angular/service-worker@7.1.0/package.json
[2]: https://github.com/angular/angular-cli/issues

**Comment by dalu** [comment]
https://github.com/angular/angular-cli/issues/13095
