### ISSUE TITLE
grid-colum-template "repeat" function has been converted while calling setStyle on Renderer2

### ISSUE THREAD

**Issue by raxim1** [angular/angular#27239]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?

Yes, i have upgraded from v5 -> 7.0.4 to see problem exists

### Description

It's an easy problem, but nasty, you can easily reproduce.

Renderer2.setStyle / setAttribute converts my grid-column-template "repeat" to single entries.

If you have let's say 10-50 repeats, how effectively the browser parse that string, i'm not so sure.

grid-template-rows: repeat(10, 1fr) -> grid-template-rows: 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr

It's messing the style parameter, so it's unreadable on development time, and it's hard to manipulate on the fly.

## 🔬 Minimal Reproduction
nativeElement can be any div - we are talking about a basic css grid - don't need to add any element inside, until the browser does not ignore it.

Inject a Renderer2 to your class, and call setStyle(nativElement,"style", "display:grid; grid-template-rows: repeat(10, 1fr)");
You can do it with setAttribute, the problem persist.

To make a workaround i have used css variable, but it's only supported from chrome v70. (which is the latest one. It's a little bit worrying, although my project has 2-3 month to go into production)

## 🔥 Exception or Error
No

## 🌍  Your Environment

**Angular Version:**
7.0.4

**Anything else relevant?**
I'm using many css function, but only the repeat has been picked up in this way by angular.

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

**Comment by raxim1** [comment]
It's not happening on stackblitz, although it's on a different angular-cli (not the latest one), pls. consider not to close issues, just ask for more info, what Google does, now I'm just messing up your repo with duplicating the issue
