### ISSUE TITLE
Support generics in NgIf context

### ISSUE THREAD

**Issue by jotatoledo** [angular/angular#27235]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/common

### Description
Currently the `NgIfContext` is type agnostic, as it has no info about the type of the bounded value.

### Describe the solution you'd like
Type awareness when using expressions of the form:

````typescript
login$: Observable<Login>
<div *ngIf="login$ | async as login">
	{{ login. }}
</div>
````

### Describe alternatives you've considered
#25983 introduced the required changes, but was abandoned due to lack of feedback

**Comment by sod** [comment]
In the meantime if you want typechecking by angular you can stop using `*ngIf="... as x"` syntax and use a sideeffect instead. Not very elegant, but at least type safe and checked by AngularCompilerPlugin and ngc.

```typescript
@Component({
    selector: 'foo',
    template: `<div *ngIf="stream$|async">{{ stream.bar }}</div>`
})
class FooComponent {
    stream$ = of({baz: 1}).pipe(tap((value) => this.stream = value));
    stream: {baz: number};
}

// Error: foo-component.ts.FooComponent.html(9,34): : Property 'bar' does not exist on type 'ProductListView'. Did you mean 'baz'?
```

**Comment by sod** [comment]
This may come with angular9. Was this fixed by https://github.com/angular/angular/pull/33016?

**Comment by alxhub** [comment]
This has been implemented!
