### ISSUE TITLE
DebugElement.nativeElement typing should be Element

### ISSUE THREAD

**Issue by CraigComeOnThisNameCantBeTaken** [angular/angular#27238]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
@angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
the nativeElement property on the DebugElement type in debug_node.d.ts is incorrectly set with an any type when it should be Element.

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment]
> nativeElement property on the DebugElement type in debug_node.d.ts is incorrectly set with an any type when it should be Element.

This would be true in the browser / DOM environment. But the goal of the `DebugElement` is to abstract the underlying native implementation.
