### ISSUE TITLE
ActivatedRoute.data type declaration is not good feet for strict mode

### ISSUE THREAD

**Issue by korvinko** [angular/angular#27240]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/router

### Description
Current type declaration for ActivatedRoute.data is
```
{
    [name: string]: any;
}
```

I enabled strictFunctionTypes in tsconfig.json:
```
{
   ...
    strictFunctionTypes": true,
}
```
In route component with ngOnOnit I have follow code: 
```
  public ngOnInit(): void {
    this.route.data.pipe(
      tap((data: MyTypeForRouteData) => {
          ...
      }))
      .subscribe();
  } 
```

I can`t provide MyTypeForRouteData for route.data because types incompatible

### Describe the solution you'd like
Declare ActivatedRoute.data as T

### Describe alternatives you've considered
Workaround that I using now:
```
    this.route.data.pipe(
      tap((data: MyTypeForRouteData|Data) => {
          ...
      }))
      .subscribe();
```

**Comment by icguy** [comment]
@jasonaden how about making it Route<T = any> ? That way you preserve backwards compatibility and provide a way for fancy type-fetishist programmers to do things with typecheck.

**Comment by Wilt** [comment]
It is easy to prevent any backward compatibility issues by making the `ActivatedRoute` and `ActivatedRouteSnapshot` classes generic with a simple default fallback value to the `Data` type as it is today:

```
class ActivatedRoute<T = Data> {
  //...
}
```
```
class ActivatedRouteSnapshot<T = Data> {
  //...
}
```

**Comment by ahnpnl** [comment]
I agree with @Wilt

is there something else blocking the change with the proposal using generic above?

**Comment by Wilt** [comment]
Related issue is also up for voting here: https://github.com/angular/angular/issues/38559

**Comment by dylhunn** [comment]
We believe it is not possible to improve the types here, due to how types in the DI system work.
