### ISSUE TITLE
Can I remove encapsulation for specific pages, I want only parent to get children css

### ISSUE THREAD

**Issue by KumailHussain** [angular/angular#27247]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by KumailHussain** [comment]
https://stackoverflow.com/questions/53443566/view-encapsulation-issue-angular5


see the issue

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by gkalpak** [comment]
In addition to what @ericmartinezr said, the issue template has not been filled out.
