### ISSUE TITLE
Change detection does not trigger between sibling components

### ISSUE THREAD

**Issue by sameh-g** [angular/angular#27249]
I found an issue while binding an object with two components, this object have multiple of properties and array. 
When operating in one of the components on this object that is blinded in both component the other component is not be able to be refreshed or fire on changes I have done a work around to that adding new binding property with number value to both components and once I fire an event in any component I increase this property number. 

            <container
                [page]="page"
                [renderBuster]="page._renderBuster">
            </container>
            <pagePublished 
                [(page)]="page"
                [renderBuster]="page._renderBuster">
            </pagePublished>

Just after increasing page ._renderBuster++ in any event it will fire the ngonchange event in the other component.

**Comment by mlc-mlapis** [comment]
@sameh-g ... you shouldn't use two-ways binding but unidirectional principle ... like:
```
<pagePublished 
            [page]="page"
            (pageChanged)="pageChange($event)"
</pagePublished>
```
where `pageChange(...)` method updates finally the `page` property.

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
