### ISSUE TITLE
KeyValuePipe returns undefined for empty object, rather than an empty array

### ISSUE THREAD

**Issue by ocvx** [angular/angular#27243]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common

### Is this a regression?

 No

### Description
When an empty object (`{}`)  is passed to the KeyValue pipe it returns an `undefined`. Since the purpose of this pipe is to return an array of all keys, the logical thing to return on an empty object would be an empty array.

## 🔬 Minimal Reproduction

 [Stackblitz](https://stackblitz.com/edit/keyvalue-pipe-error?file=src%2Fapp%2Fapp.component.html) - here I try to pass it on to another pipe named 'toKeys', which expects to get an array, since 'toKeys' gets an undefined the next pipe throws an error `ERROR
Error: Cannot read property 'map' of undefined`.

## 🔥 Exception or Error
As mentioned above, when chaining to another pipe that expects to get an array I'll get this error:
<pre><code>
ERROR
Error: Cannot read property 'map' of undefined
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.0.6
Node: 10.13.0
OS: linux x64
Angular: 7.0.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.6
@angular-devkit/build-angular     0.10.6
@angular-devkit/build-optimizer   0.10.6
@angular-devkit/build-webpack     0.10.6
@angular-devkit/core              7.0.6
@angular-devkit/schematics        7.0.6
@angular/cli                      7.0.6
@ngtools/webpack                  7.0.6
@schematics/angular               7.0.6
@schematics/update                0.10.6
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
    

</code></pre>

**Anything else relevant?**

**Comment by trotyl** [comment]
Confirmed, `KeyValueDiffer` would return `null` when there's no change (empty object), and `KeyValuePipe` fails to initialize it:

https://github.com/angular/angular/blob/dc300c5c4172e1f8a6f3f84da6797e427e3626c0/packages/common/src/pipes/keyvalue_pipe.ts#L79-L88

**Comment by pkozlowski-opensource** [comment]
This got fixed in b39efdd
