### ISSUE TITLE
Building nested menu with recursions and routerLink

### ISSUE THREAD

**Issue by gultyaev** [angular/angular#27257]
I'm trying to build a nested menu with Angular 7. Since I want to make my menu flexible I don't specify the level of nesting and build my menu recursively from object. The problem is that I need to somehow populate child's `routerLinkActive` to it's parent so that it could apply a css class and expand the menu (it's accordion like) and since it's a nested menu not all the items really have links, due to their purpose of semantic grouping and expanding/collapsing. 

I have the following [blitz](https://stackblitz.com/edit/angular-jwwrse) which I'm trying to resolve for a while and here's the question on [stack](https://stackoverflow.com/questions/53299952/angular-router-link-active-nested-menu/53418795?noredirect=1#comment93774784_53418795) meaning that not only I found it difficult to implement in recursive building way. Because, when I apply `routerLinkActive="active"` to the parent it doesn't see the children which are rendered only when they are present in `children` in menu object. 

I've tried also to add `routerLinkActive #rla="routerLinkActive` and track it from component, but it's not an observable and it's changing emits nothing so that I cannot track the moment of changing the routerLinkActive. OnChanges isn't called when the routerLinkActive is changed even though it's being passed to component via `@ViewChild('rla') rla`.

How do I do this state propagation of non-observable object? For now I can think of only pinging this state every N ms for changes and then emitting the event, but it doesn't look right.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by gultyaev** [comment]
@ericmartinezr as I've mentioned it's been on StackOverflow for a while but no suitable help has gotten.

**Comment by benlesh** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
