### ISSUE TITLE
ERROR in : TypeError: Cannot read property 'visit' of undefined

### ISSUE THREAD

**Issue by PhilipMantrov** [angular/angular#27254]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler

### Is this a regression?
Yes, the previous version in which this bug was not present was Angular 6.1

### Description
After update big application from Angular 6.1 to Angular 7.1, this bug appear

## 🔥 Exception or Error
<pre><code>
ERROR in : TypeError: Cannot read property 'visit' of undefined
    at convertPropertyBinding (C:\git\evodesk-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:7038:52)
    at TemplateDefinitionBuilder.convertPropertyBinding (C:\git\evodesk-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:14187:44)
    at C:\git\evodesk-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:13993:35
    at C:\git\evodesk-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:14147:71
    at C:\git\evodesk-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:13633:86
    at Array.map (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (C:\git\evodesk-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:13633:56)
    at C:\git\evodesk-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:14067:60
    at C:\git\evodesk-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:13626:81
    at Array.forEach (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (C:\git\evodesk-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:13626:37)
    at C:\git\evodesk-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:14067:60
    at C:\git\evodesk-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:13626:81
    at Array.forEach (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (C:\git\evodesk-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:13626:37)
    at compileComponentFromMetadata (C:\git\evodesk-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:14848:58)
</code></pre>

## 🌍  Your Environment
<pre><code>
Angular CLI: 7.0.6
Node: 9.6.1
OS: win32 x64
Angular: 7.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.6
@angular-devkit/build-angular     0.10.6
@angular-devkit/build-optimizer   0.10.6
@angular-devkit/build-webpack     0.10.6
@angular-devkit/core              7.0.6
@angular-devkit/schematics        7.0.6
@angular/cli                      7.0.6
@ngtools/webpack                  7.0.6
@schematics/angular               7.0.6
@schematics/update                0.10.6
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1

</code></pre>

**Anything else relevant?**
I think its related with lazyloading modules, after update to Angular 7, it cant build with string path in loadChildren (`() => ModuleName` works perfectly in build without aot).

**Comment by JoostK** [comment]
Could you share your `tsconfig.json` configurations? The stack trace indicates that the Ivy compilation path is being taking under the current AOT compiler, which should only be activated when `enableIvy` is configured as such.

**Comment by PhilipMantrov** [comment]
> Could you share your `tsconfig.json` configurations? The stack trace indicates that the Ivy compilation path is being taking under the current AOT compiler, which should only be activated when `enableIvy` is configured as such.

Oh, thx man, enableIvy: false and now everything builds well.
But why does it happen? We had Ivy compiler in Angular 6.1 and we did not have any problem with it.

**Comment by JoostK** [comment]
Well, it surprises me that you have been using the Ivy compiler for production already?

It is actually a legitimate bug in Ivy's template compiler. After inspecting the code I can find a code path where a template AST `EmptyExpr` node will cause your issue to occur.

At this moment in time the team does not yet accept Ivy issues on GH, so there's nothing you need to do right now. I'll put this on my list to have a look at sometime 👍

**Comment by PhilipMantrov** [comment]
>Well, it surprises me that you have been using the Ivy compiler for production already?
Yea, from the start refactoring of project (Angular 6.0, then 6.1, now 7.1). We use Ivy from August in production and its work's correctly until now. And i dont remeber that we was configure anything, we just add in tsconfig `"enableIvy": true`.
