### ISSUE TITLE
Dev app does not work with firefox

### ISSUE THREAD

**Issue by hankduan** [angular/angular#2726]
The dev app (i.e. `gulp serve.js.prod`) does not work with firefox driver, and to an extent doesn't work with the firefox browser.

First, firefox driver would always crash whenever it tries to access any element in the app, i.e. the following would crash: 

```javascript
var webdriver = require('selenium-webdriver');
 
// Uncomment chrome and comment out firefox, and this will work fine though 
// var capabilities =  webdriver.Capabilities.chrome(); 
var capabilities =  webdriver.Capabilities.firefox();
 
var driver = new webdriver.Builder().
  usingServer('http://localhost:4444/wd/hub').
  withCapabilities(capabilities).
  build();
 
driver.get('http://localhost:8001/benchmarks/src/tree/tree_benchmark.html?depth=9&viewcache=true');
driver.sleep(3000);
driver.findElement(webdriver.By.css('#baselineCreateDom')).click();
driver.quit();
```

App and firefox browser:
1) *Manually* open `http://localhost:8001/benchmarks/src/tree/tree_benchmark.html?depth=9&viewcache=true` in firefox browser
2) click on 'createDom' under **baseline**

Nothing will happen, but there are no errors either. (clicking on 'createDom' under 'angular2 tree benchmark' works though).

**Comment by mhevery** [comment]
Obsolete, it should work now.
