### ISSUE TITLE
Cannot bind Attribute "For" of a Label

### ISSUE THREAD

**Issue by Sabartius** [angular/angular#2728]
I have a form, where the id of an input and the label-for are bound. The id is correctly transformed to the bound value, label for remains as written in the template

My Form:

    <p *ng-for="var colour of colours">
        <input id="{{colour.text}}" name="someColour" type="radio"
        ng-control="someColour"
        [checked]="myForm.controls.someColour.value == colour.text">
                <label for="{{colour.text}}">{{colour.text}}</label>
    </p>

How the label is present in the dom:

    <label for="{{colour.text}}">blue</label>

**Comment by PascalPrecht** [comment]
@Sabartius since you're using an expression, you need to bind to the property instead of the attribute. Try:

```html
<label [for]="colour.text">...</label>
```

Inside an element, you can still use `{{colour.text}}` since this is a shorthand syntax for a property binding as well. But attributes only understand strings. If you pass `{{colour.text}}` to an attribute, then that's the string it takes.

**Comment by mlaval** [comment]
Both `for="{{colour.text}}"` and `[for]="colour.text"` binds to the for property, which doesn't exist.

To bind to the attribute, you need `[attr.for]="colour.text"` instead

**Comment by PascalPrecht** [comment]
Ah thought that `[for]` would create the property accordingly.

**Comment by Sabartius** [comment]
Funny thing is, that i can bind the "id" of my input like this `id="{{colour.text}}"`
Does that mean, that input-Elements have a property called id, that resolves to the attribute of the dom-element?

**Comment by pkozlowski-opensource** [comment]
@Sabartius some elements have property and attribute with the same name. It is common in HTML world that an attribute is used to initialise (from HTML) value of a property that later on can be manipulated programatically. 

Closing, as I believe that things work as expected.
