### ISSUE TITLE
Lazy modules not found with preserveSymlinks enabled (core.js 15070)

### ISSUE THREAD

**Issue by nhnb** [angular/angular#27292]
# 🐞 bug report

### Affected Package
The issue is caused by the Angular CLI or package @angular/core.

### Is this a regression?
Yes, in Angular 5 with `ng serve --preserveSymlinks` the issue did not occur.

### Description

Lazy modules cannot be found when node_modules is a symlink and `preserveSymlinks`is enabled in angular.json

~~~~
ERROR Error: "Uncaught (in promise): Error: Cannot find module './lazy.module'
webpackEmptyAsyncContext/<@http://localhost:4200/main.js:48:11
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke@http://localhost:4200/polyfills.js:2733:17
onInvoke@http://localhost:4200/vendor.js:55770:24
~~~~

There is a warning on `ng serve` or `ng build`:

~~~~
WARNING in ./node_modules/@angular/core/fesm5/core.js 15070:15-36
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/@angular/core/fesm5/core.js 15082:15-102
Critical dependency: the request of a dependency is an expression
Compiled with warnings.
~~~~

| node_modules  | preserveSymlinks | Result |
| ------------------ | -----------------------|----------|
| folder              | true                      | ok |
| folder              | false                      | ok |
| symlink              | true                      | error |
| symlink              | false                      | ok (1)  |

(1) While this issue does not occur in this combination, it is not a workaround: Entries in styles [] in angular.json, that point to node_modules, are silently ignored.

### Premade project

I created a minimal project to demonstrate the issue: https://github.com/nhnb/symlinklazy

After checkout, please verify that `symlinklazy/node_modules` is still a symlink pointing to `../node_modules`.

~~~~
cd symlinklazy
ng serve
~~~~

Expected result: No warnings. In the browser, you see `app-component Lazy`.

Actual result: Warnings as mentioned above. In the browser, you only see `app-component`. In the browser console, there is the error mentioned above.

### From scratch

- Create a new project using `ng`
- Create a new lazy module with a simple hello-world-component and setup the router
- Move node_modules to parent folder
- Create a symlink from ../node_modules to node_modules
- Add `"preserveSymlinks": true` to build options in angujar.json
- Run `ng serve`

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.0.7
Node: 8.10.0
OS: linux x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1

</code></pre>

**Anything else relevant?**
 Ubuntu 18.04.1 LTS

**Comment by jasonaden** [comment]
Thank you for the detailed issue report. I'm marking this for `@angular/core`, but it might need to be moved to the `angular-cli` project if it's found to be an issue for the CLI.

**Comment by alxhub** [comment]
This looks like a CLI issue to me. Please file it against the `@angular/clI` repo.

**Comment by nhnb** [comment]
I am sorry, I did not see the existing report on the angular-cli repository: angular/angular-cli#11653
