### ISSUE TITLE
Angular material io - have item id for the checkbox tree view

### ISSUE THREAD

**Issue by paithalmi** [angular/angular#27295]

**Comment by paithalmi** [comment]
https://stackoverflow.com/questions/53359632/angular-material-io-have-item-id-for-the-checkbox-tree-view

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by jasonaden** [comment]
Closing based on the above.

**Comment by paithalmi** [comment]
Hi, i posted the isue in stackoverflow. but i didn't get any response back.
Stackoverflow link: https://stackoverflow.com/questions/53359632/angular-material-io-have-item-id-for-the-checkbox-tree-view
