### ISSUE TITLE
Empty spaces in Extra Options router properties docs

### ISSUE THREAD

**Issue by vvasc** [angular/angular#27296]
# 📚 Docs or angular.io bug report

### Description

Empty spaces at https://angular.io/api/router/ExtraOptions between properties

### Expected vs Actual Behavior**
Do not show empty spaces between properties

**Comment by gkalpak** [comment]
@vvasc, are you referring to the fact that the first column (`Property`) is too wide?
This is because there is one particularly long property signature 😞

cc @petebacondarwin

**Comment by vvasc** [comment]
oh, my mistake

**Comment by ericmartinezr** [comment]
My 5c here. In small screens it looks like there's no 2nd column, and you have to scroll all the way down to see the horizontal scrollbar.

![image](https://user-images.githubusercontent.com/13039652/49101744-b6558500-f255-11e8-98b9-ac16b388f9fc.png)

In wider screens you can see part of the 2nd column

![image](https://user-images.githubusercontent.com/13039652/49101791-d422ea00-f255-11e8-94e7-47093c4ffe37.png)

**Comment by gkalpak** [comment]
I agree this is a little problematic. If anything, there should be a max cell width and the horizontal scrolling should happen on the cell-level.

**Comment by petebacondarwin** [comment]
I believe we have an issue somewhere about the many issues of tables and their layout in the docs... @jenniferfell ?

**Comment by s-gbz** [comment]
Faced the same issue on Firefox 66.0.2

![angular-too-wide-router-extraOption](https://user-images.githubusercontent.com/23424538/55705691-a5750700-59df-11e9-9824-71a63aae0c43.png)

**Comment by sjtrimble** [comment]
Is there a reason we have the `white-space: pre; ` styling on these `code` elements? If we remove this, it helps. Still need to fix how the table columns behave.

**Comment by petebacondarwin** [comment]
Do you suggest `pre-wrap` or `pre-line` or something instead? The trouble is that occasionally these code elements are multi-line (I think) and they may contain indentation. E.g.

```
{
  someProp: 1;
}
```

**Comment by gkalpak** [comment]
The situation has been considerably improved with #31013.

![router-extra-options](https://user-images.githubusercontent.com/8604205/71327914-57754480-2517-11ea-8c6b-6c9013a171e6.png)

Should this be closed or are there more improvements we want to do?

**Comment by ericmartinezr** [comment]
Can I be a little bit annoying? :P 

This happens now with wider screens (2560 x 1440) (only in API docs, the other docs are fine)

![image](https://user-images.githubusercontent.com/13039652/73123833-0374da00-3f73-11ea-8fa2-3ed997ffb9d5.png)

It's not something I would prioritize since I don't think there are too many people using wide screens, but wanted to let you guys know.

**Comment by sjtrimble** [comment]
@ericmartinezr 🤔can you explain what you're seeing. Are you referring to the large white space on the right, or something else?

**Comment by ericmartinezr** [comment]
@sjtrimble yes, sorry, I wasn't clear enough. Just be a little be more clear, comparing it to the other docs (not api)

![image](https://user-images.githubusercontent.com/13039652/73126232-eea63f80-3f8e-11ea-92a4-75f96d985a99.png)

**Comment by JeanMeche** [comment]
I'll close this as the initial issue is solved.
