### ISSUE TITLE
Use angular element in older angular version (like angular 5)

### ISSUE THREAD

**Issue by ArielBar** [angular/angular#27303]
Hey,
I created an angular element and I tried to put in basic html file and it worked fine.
But when I tried to use it in older angular version I got error like:
“Uncaught TypeError: parentJsonpFunction is not a function
    at webpackJsonpCallback (bootstrap f3a05b3098d404d7f157:18)
    at polyfills.bundle.js:1”

My question is : is it possible to do what I tried to do?

**Comment by Airblader** [comment]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: 
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by ArielBar** [comment]
Sorry

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
