### ISSUE TITLE
ng serve --aot, subsequent compilations are successful regardless of type errors.

### ISSUE THREAD

**Issue by DanielSwiegersServian** [angular/angular#27314]
# 🐞 bug report

### Affected Package
@angular/cli

### Is this a regression?
Yes

### Description

if ```ng serve --aot``` successfully compiles the first time, any subsequent **type** errors are ignored.  
If these **type** errors are present on the first run then it fails to compile as expected.

It still prints the type errors when they occur on the console.
But the compilation succeeds before any errors are printed.

Compilation still fails as expected when creating a non type error (e.g. renaming a component class but not its module declaration)

## 🔥 Exception or Error
<pre><code>Date: 2018-11-28T03:54:22.956Z
Hash: 6752187e9ec9be932aff
Time: 8915ms
chunk {main} main.js, main.js.map (main) 64.6 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 131 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 16.5 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 2.44 MB [initial] [rendered]
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...

Date: 2018-11-28T03:55:02.230Z - Hash: 99b15fd21906159fa958 - Time: 3975ms
4 unchanged chunks
chunk {main} main.js, main.js.map (main) 64.6 kB [initial] [rendered]
ℹ ｢wdm｣: Compiled successfully.

ERROR in src/app/app.component.html(2,58): : Property 'ids' does not exist on type 'Survey'.

ℹ ｢wdm｣: Compiling...

Date: 2018-11-28T03:55:08.278Z - Hash: 499f6e1aca0566959037 - Time: 814ms
4 unchanged chunks
chunk {main} main.js, main.js.map (main) 86.4 kB [initial] [rendered]
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...

Date: 2018-11-28T03:55:09.601Z - Hash: 6f8e3b99ed97a4d7393b - Time: 610ms
4 unchanged chunks
chunk {main} main.js, main.js.map (main) 86.4 kB [initial] [rendered]
ℹ ｢wdm｣: Compiled successfully.

ERROR in src/app/app.component.html(2,58): : Property 'idss' does not exist on type 'Survey'.

ERROR in src/app/app.component.html(2,58): : Property 'idsss' does not exist on type 'Survey'.

ℹ ｢wdm｣: Compiling...

Date: 2018-11-28T03:55:20.819Z - Hash: 0d937fdc89291121c6d8 - Time: 572ms
4 unchanged chunks
chunk {main} main.js, main.js.map (main) 86.4 kB [initial] [rendered]
ℹ ｢wdm｣: Compiled successfully.

ERROR in src/app/app.component.ts(21,17): error TS2339: Property 'nope' does not exist on type 'Survey'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.0.7
Node: 10.13.0
OS: linux x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
</code></pre>

**Comment by jasonaden** [comment]
Thanks for the issue and thorough description. Please head over to the [Angular CLI](https://github.com/angular/angular-cli) project and file it there as this appears to only be related to the CLI. You should also include a reproduction to show the issue.

**Comment by DanielSwiegersServian** [comment]
Issue opened at [https://github.com/angular/angular-cli/issues/13083](https://github.com/angular/angular-cli/issues/13083)
