### ISSUE TITLE
about "ng build" compatibility

### ISSUE THREAD

**Issue by liwei511** [angular/angular#27316]
1. when use fireFox, and version < 50:
    ng build --aot --optimization=true --source-map=false --extract-css
2. when use other:
    ng build --prod
3. "ng build --prod" is not supported fireFox<50

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by jasonaden** [comment]
Closing based on above.
