### ISSUE TITLE
Please add setTouchedState on ControlValueAccessor interface

### ISSUE THREAD

**Issue by JiajunHan** [angular/angular#27315]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/forms

### Description
Custom form field by implementing ControlValueAccessor missing the ability to mark untouched.

For my problem, I encapsulated a input field with a long list of error messages into a custom form field. Inside this custom form field component, it has it's private formControl, handling the validation and error display, etc. If I implement this interface to make a bridge between this private formControl with the outside world formControl, there is no way I can mark that private formControl untouched to clear the error message. So I really need a setTouchedState just like setDisabledState.

### Describe the solution you'd like
Add setTouchedState method in ControlValueAccessor interface. Hopefully it's not a big change.

### Describe alternatives you've considered
Not really.

**Comment by xdevnull** [comment]
any update?

**Comment by irekBudzowski** [comment]
Hi, is there any news?

**Comment by AndrewKushnir** [comment]
This feature request looks similar to #24444 and it would be taken into account during a larger effort to improve events emitted by `AbstractControl`s, see #42862.
