### ISSUE TITLE
Why do we check all properties on all async events when we can use getter setter methods?

### ISSUE THREAD

**Issue by hnviradiya** [angular/angular#27317]
This is just a question I tried on stackoverflow.

Why do we check all properties on all async events when we can use getter setter methods? Like vue does?

https://stackoverflow.com/questions/53498840/why-different-change-detection-mechanism-in-vue-and-angular

**Comment by dawidgarus** [comment]
What about binding like `{{model.property[0]}}`? It's not possible to detect changes in mutable objects using only getters and setters.

**Comment by mlc-mlapis** [comment]
@hnviradiya ... you mean the all data flow should go only and only through getters / setters?

**Comment by jasonaden** [comment]
For a quick answer, @dawidgarus' response above is probably the best. There are additional trade-offs between both methodologies and they each have their plusses and minuses, but this is not the forum to discuss.
