### ISSUE TITLE
HostListener event doesn't react on disabled input with Firefox

### ISSUE THREAD

**Issue by CDelgrange** [angular/angular#27312]
🐞 bug report

Hi everyone!

I encounter an issue with Firefox, Reactive Forms, and the HostListener decorator.
The code is simple:
 - I have a form with an input
 - The input is disabled
 - I listen to the "click" event with the HostListener decorator, and just print something in the console

=> With Chrome, if I click on the input, the HostListener react and the console print what I want
=> With Firefox, no reaction, no console print

A Stackblitz is worth 71 words : https://stackblitz.com/edit/angular-rerzke 

### Affected Package
- @angular/core
- @angular/forms

### Is this a regression?
I don't think it's a regression

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 6.2.7
Node: 10.4.1
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.7
@angular-devkit/build-angular     0.8.7
@angular-devkit/build-optimizer   0.8.7
@angular-devkit/build-webpack     0.8.7
@angular-devkit/core              0.8.7
@angular-devkit/schematics        0.8.7
@angular/cli                      6.2.7
@ngtools/webpack                  6.2.7
@schematics/angular               0.8.7
@schematics/update                0.8.7
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.16.4

</code></pre>

**Comment by trotyl** [comment]
It's most likely to be a Chrome bug, a disabled control element is not clickable:

+ https://stackoverflow.com/questions/3100319/event-on-a-disabled-input
+ https://stackoverflow.com/questions/16109228/clicking-a-disabled-input-or-button
+ https://stackoverflow.com/questions/20898344/click-on-disabled-input-not-getting-triggered-on-mozilla

**Comment by CDelgrange** [comment]
Huh... You're right, thanks a lot for that share!
I guess I'll go with some HTML / CSS hacks then :(
