### ISSUE TITLE
HttpClient overloads are indistinguishable from each other in api doc

### ISSUE THREAD

**Issue by jnizet** [angular/angular#27335]
# 📚 Docs or angular.io bug report

### Description

The signature of the overloaded methods of HttpClient is now truncated, which makes it impossible to disinguish one overload from the other. For example, the displayed signature of the first overload of get() is

```
get(url: string, options: { headers?: HttpHeaders | { [header: string]: string | string[]; }; observe?: "body"; params?: Ht...): Observable<ArrayBuffer>
```

and the displayed signature of the second one is

```
get(url: string, options: { headers?: HttpHeaders | { [header: string]: string | string[]; }; observe?: "body"; params?: Ht...): Observable<Blob>
``` 

So we know that the two overloads return something different, but since the arguments are truncated, it's impossible to know what the difference is between the two overloads, which look completely identical.

The textual documentation doesn't help, since it doesn't say what triggers the choice of that specific overload.

## 🔬 Minimal Reproduction

Go to https://angular.io/api/common/http/HttpClient#get, expand the overloads, try to understand what the difference between the first and the second overload is.

### What's the affected URL?**
https://angular.io/api/common/http/HttpClient#get

### Expected vs Actual Behavior**

Expected: the signature shouldn't be truncated. Or it should at least be able to expand it to view it completely. A textual description of what triggers each specific overload (for example, the value of the `responseType` option set to 'blob') would be a nice to have.

Actual: it's impossible to view the complete signature

## 📷Screenshot

<img width="847" alt="capture d ecran 2018-11-28 a 21 42 23" src="https://user-images.githubusercontent.com/1608223/49180934-5db9e100-f356-11e8-9843-d91593da2b79.png">

As a side note: having the most commonly used overloads listed first (i.e. the one returning `T`, and the one returning `HttpResponse<T>`) would be nice. They're currently the 15th and the 13th one, although these are the ones documented in the HttpClient guide.

**Comment by jenniferfell** [comment]
@petebacondarwin @jbogarthyde @IgorMinar : Good point. I know we had several ideas with overloads. Looks like we're back to 'em. :-)

**Comment by jbogarthyde** [comment]
This has been fixed.
