### ISSUE TITLE
Convert relative template and style URLs in dart transformer

### ISSUE THREAD

**Issue by TedSander** [angular/angular#2733]
Convert relative template/style URLs in the transformer for use when URLs are not inlined to the application.

**Comment by tbosch** [comment]
@TedSander The new compiler does this now: It converts all stylesheets into separate `.dart` files that follow the `@import` path. I.e. if a stylesheet is used by 2 components, their generated template used the same generated `.dart` file. 

Also, the new compiler understands relative template/style urls now.

Leaving open until the new compiler is in Google3

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
