### ISSUE TITLE
Upgrade from 6.1 to 7 causes Karma debugging to fail

### ISSUE THREAD

**Issue by JOGrady77** [angular/angular#27333]
I've noticed that after I updated an Angular 6.1 app to 7.0 I was unable to debug Karma Unit tests.  To replicate,  create a new Angular 6.1 app 
`ng new ssApp`
enable debugging for system test by updating the launch.json file
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}"
        },
        {
            "type": "chrome",
            "request": "attach",
            "name": "Unit tests",
            "address": "localhost",
            "port": 9333,
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
          }
    ]
}

```
and update the karma.config.js file

```
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      reports: ['html', 'lcovonly'],
      fixWebpackSourcePaths: true
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false,
    customLaunchers: {
      ChromeDebug: {
        base: 'Chrome',
        flags: [ '--remote-debugging-port=9333' ]
      }
    }
  });
};

```
Test to insure you can debug a unit test, set a breakpoint in a the app.component.spec.ts file
`ng test --browsers ChromeDebug`
debug breakpoint should be hit

Upgrade to angular 7.0 
`ng update @angular/cli @angular/core`

Repeat test, can't hit breakpoint.  Error message received "Breakpoint ignored because generated code not found"

**Comment by ChrisDahmCS** [comment]
@JOGrady77
To help others looking into issues, please reference the [contributing guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question) when reporting an issue. 

Using the steps provided, I am unable to reproduce the issue you have submitted. Do you have any other steps for getting to this point? Please note that any specific configs/plugins/settings that are not part of a vanilla install should be mentioned as well.

**Comment by JOGrady77** [comment]
Hi Chris
Thanks for your help in this issue!

Not sure why you are unable to replicate my results.  I walked through it again and got the same results.  To recap

1. Created a folder and ran the ng command to create a default Angular project
2. ran "npm install" to bring down the needed libraries
3. Verified that I could build and run the project
4. Updated my Karma.config.js file and launch.json to enable karma unit test debugging
5. set a breakpoint in the app.component.spec.ts, verified that I could hit it in debug mode
6. copied the entire project to a new folder
7. ran "ng update @angular/cli @angular/core" to update the copy to angular 7
8. was unable to hit the breakpoint

I checked to see what files were different between the two projects (excluding the node_modules folder)
It was these 4 files

1. package-lock.json
2. package.json
3. tsconfig.json
4. src\ployfills.ts

tsconfig.json and polyfills.ts had very minimal differences, swapping them out between angular 6 and 7 didn't fix my issue

Embedded is the package.json file from both versions

```
{
  "name": "ss-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.2.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.8.0",
    "@angular/cli": "~6.2.1",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  }
}

```
```
{
  "name": "ss-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.1.1",
    "@angular/common": "^7.1.1",
    "@angular/compiler": "^7.1.1",
    "@angular/core": "^7.1.1",
    "@angular/forms": "^7.1.1",
    "@angular/http": "^7.1.1",
    "@angular/platform-browser": "^7.1.1",
    "@angular/platform-browser-dynamic": "^7.1.1",
    "@angular/router": "^7.1.1",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.11.0",
    "@angular/cli": "~7.1.0",
    "@angular/compiler-cli": "^7.1.1",
    "@angular/language-service": "^7.1.1",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }
}

```
You can see these are OOB projects.  I have added nothing.  I am on a Windows PC using VS Code as my editor.  

HTH, Jim

**Comment by ChrisDahmCS** [comment]
Hey Jim!

Thanks for the extra info, I'm going to put in some extra effort to try and replicate.

Best regards-

Chris

**Comment by JOGrady77** [comment]
Any luck?

**Comment by JOGrady77** [comment]
I have this working.  I was upgrading using this command

`ng update @angular/cli @angular/core`

Instead if I do this

`ng update @angular/cli ng update @angular/core ng update rxjs`

it works, so I guess rxjs was the difference, or it was fixed in an updated version.  In either case, you can close this
