### ISSUE TITLE
Angular cli - not removing dependencies of unused library components

### ISSUE THREAD

**Issue by babeal** [angular/angular#27340]
# 🐞 bug report

### Affected Package
Unknown

### Is this a regression?
No

### Description
The angular build/packaging process is unable to remove third party dependencies from unused components in a library.  The example provided includes a library called components containing a component that imports moment.js and one that doesn't.  When only the component that DOES NOT use moment is imported into the application the resulting application bundle will still contain moment.  I have tried to force the build process to use esm5 instead of fesm 5 and this does not help. The only thing left referencing moment would be the metadata.json.  This problem makes it difficult to build large component libraries using the cli due to the fact that all runtime transitive dependencies will be included in the final bundle whether they are used or not.  I would like to know why this is and where the problem resides.

## 🔬 Minimal Reproduction

https://github.com/babeal/ng-tdp

clone, run ```npm install```, then ```npm run analyze```

## 🔥 Exception or Error

The results of the webpack analysis will show moment in the main bundle as well as inspecting the minified main.js in the dist folder.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.1.0
Node: 8.12.0
OS: darwin x64
Angular: 7.1.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.11.0
@angular-devkit/build-angular      0.11.0
@angular-devkit/build-ng-packagr   0.11.0
@angular-devkit/build-optimizer    0.11.0
@angular-devkit/build-webpack      0.11.0
@angular-devkit/core               7.1.0
@angular-devkit/schematics         7.1.0
@angular/cli                       7.1.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.1.0
@schematics/angular                7.1.0
@schematics/update                 0.11.0
ng-packagr                         4.4.0
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.23.1

</code></pre>

**Comment by trotyl** [comment]
Please report to https://github.com/angular/angular-cli

**Comment by babeal** [comment]
will do

**Comment by babeal** [comment]
moved to angular-cli
