### ISSUE TITLE
Twice bracket and parenthesis with language service

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular#27349]
# 🐞 bug report

### Affected Package
The issue is caused by package `@angular/language-service`

### Is this a regression?
No, the issue was already here in previous versions.

### Description

The Angular language service is adding a second/double ending bracket for attribute completion or a second/double ending parenthesis for event completion instead of having only a single ending character.

## 🔬 Minimal Reproduction
Can't be shown on Stackblitz.

* `ng new --inlineTemplate` (this option is important, as using the language service directly only works for inline templates)
* add Angular language service in `tsconfig.json`:
```json
{
  "compilerOptions": {
    "plugins": [{ "name": "@angular/language-service" }]
  }
}
```

The previous steps are already done in this Github repro: [https://github.com/cyrilletuzi/ng-languageservice-issue](https://github.com/cyrilletuzi/ng-languageservice-issue)

Then:
* **in VS Code, be sure to switch to project version of TypeScript** (instead of VS Code version, otherwise the previous step won't have any effect)
* **be sure to not have the Angular Language Service VS Code extension activated** (meaning a reload of VS Code, otherwise it will interfere),
* in `app.component.ts`, try to add an attribute binding on some HTML element, for example `[src]` on `img`:
  * type a first bracket `[` => VS Code will automatically add the ending bracket `]`
  * start to type `sr`
  * choose the `[src]` suggestion
  * Angular will do the `[src]` completion, taking care to replace the starting bracket, but not the ending one, resulting in `[src]]`

Same with events (for exemple, adding the `click` event will end up with `(click))`.

## 🌍  Your Environment

**Angular Version:**
VS Code 1.29.1
`@angular/language-service` 7.1.1

**Anything else relevant?**
Those kind of issues are important to fix to be able to use `@angular/language-service` as a TypeScript plugin, for better performance, like this [VS Code extension](https://github.com/cyrilletuzi/vscode-typescript-angular-plugin) is already trying to do.

I think it's an easy PR. I tried to do it myself, but having reviewed all the code in `@angular/language-service`, I can't find where the completion replacement happen.

**Comment by cdahm11** [comment]
@cyrilletuzi, I am unable to replicate this in other editors (ex: Webstorm), so I'm not sure this is a problem with the @angular/language-service. Are you able to reproduce this with a clean install of VSCode (no extra plugins or settings changed from default)?

**Comment by ChrisDahmCS** [comment]
@cyrilletuzi, I am unable to replicate this in other editors (ex: Webstorm), so I'm not sure this is a problem with the @angular/language-service. Are you able to reproduce this with a clean install of VSCode (no extra plugins or settings changed from default)?

**Comment by okeefem2** [comment]
Hello! I just tried replicating the steps you have described and was not able to get the same results.

I did indeed get auto completion of `[]` when typing the first `[` then typing `sr` and selecting src for auto-completion resulted in `[src]` with my cursor placed after the `]`. Along with the previous comment by @ChrisDahmCS I am wondering if you have any other plugins that may be causing this to happen?

**Comment by cyrilletuzi** [comment]
I can replicate in a new and clean install of VS Code with no plugin and no custom setting at all. You have to make sure it uses the workspace version of VS Code (ie. the version used by Angular).

Webstorm has a custom implementation of Angular language service, so it's not relevant here.

**Comment by cyrilletuzi** [comment]
Btw, it's already replicated, as it has been reported by someone else in cyrilletuzi/vscode-typescript-angular-plugin#3.

**Comment by ChrisDahmCS** [comment]
@cyrilletuzi 

I installed VSCode (1.29.1 fresh on this machine (never before used). I followed the steps you provided (including adding the plugin and adding the .vscode/settings.json option). By default, VSCode does not come with extensions installed, so it seems like there is no angular related auto-complete like `<button (click)>`. I checked by going to extensions -> show installed extensions. I double checked this by running `code --list-extensions` in the terminal.

So, I followed [these steps](https://angular.io/guide/language-service) to install the Angular Language Service extension (which you said should be disabled). This gives the expected functionality of `<button (click)` having the correct auto completion. I then uninstalled the plugin.

So, I removed the extension, and installed [your extension](https://marketplace.visualstudio.com/items?itemName=cyrilletuzi.typescript-angular-plugin) where the issue is reported. When I try the same auto complete scenario, I get `<button (click))` with the extra closing paren. I then uninstalled the plugin, and again was back to step 1.

Can you please offer more insight into how the issue can be replicated?

**Comment by cyrilletuzi** [comment]
@ChrisDahmCS So you replicated the issue then (even if nobody asked you to, it's not a support request, it's an issue addressed to the Angular team).

**Comment by okeefem2** [comment]
@cyrilletuzi I don’t think that was a fair comment, as Angular is an open repository I believe it is encouraged that the community helps each other out, especially with how busy the core team is!

I think that what @ChrisDahmCs is trying to say is that he was able to reproduce the issue, but only while using that extension in VS Code. Not with any other IDE or extension that also uses the Angular language service. And I believe he is looking for an explanation on how the Angular language service is at fault in that case.

**Comment by cyrilletuzi** [comment]
@okeefem2 My last comment wasn't directed to you.

Helping is welcomed when it's coming from good intention, and I'm not sure the other intervention is benevolent. Chris directly tagged my issue with a bad reaction smiley, without even waiting for my answer.

Github show I already contributed to this repo, that this issue is referenced from a repo of an extension about the language service, that the issue was reported by someone else too, and I provided a full reproduction of the issue. So it doesn't mean I can't make an error, but there are many signs I master what I'm talking about at least a little.

To come back to the issue: until now, the `@angular/language-service` was consumed by editor-specific extensions. At the same time, they added a lot of things on top of `@angular/language-service` (additional features and circumvention of some issues, probably like this one).

But these kind of extensions (like the TSLint extension) have a performance issue: each one uses its own TypeScript service. So if you have TSLint + Angular Language services extensions, it means your code is reanalyzed 3 times.

It's now possible to consume those tools directly from TypeScript, as plugins. It's already be done for [TS Lint](https://github.com/Microsoft/vscode-typescript-tslint-plugin), and them same can be done with `@angular/language-service` Meaning there will now be just one analyze of the code.

But it means `@angular/language-service` must do everything correctly by itself, as it's not helped by an extension anymore.

Following the exact steps I've provided is essential, as what's activated and used by the editor is not the same if it's the VS Code or the project version of TypeScript which is set, or if the legacy Angular Language Service extension is still enabled.

**Comment by cyrilletuzi** [comment]
I've modified the first report a little so the important steps are clear.

**Comment by ChrisDahmCS** [comment]
I apologize if my initial inquiry seemed aggressive or doubtful, that was not the intention. My intention was first to be able to replicate the issue with the steps provided or see it from another direction.

Thank you for the clarification on lib(s) being standalone vs consumed by editors!

**Comment by cyrilletuzi** [comment]
I apologize too as I may have overreact.

**Comment by cyrilletuzi** [comment]
Closing as the language service has been announced to be fully revamped for Ivy.
