### ISSUE TITLE
Ivy Renderer (not security related ;)) ^_^

### ISSUE THREAD

**Issue by PeterDavidCarter** [angular/angular#27353]
_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^

Please read nietzsche on how to disclose security related issues.

_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^_^-^

Ivy renderer is still not here and Angular keeps getting in our way all the time plz fix plz fix plz fix I heard Ivy renderer is magic and Angular keeps getting in my team's way plz fix.

**Comment by gkalpak** [comment]
On it :wink:
