### ISSUE TITLE
FormGroup validator on init

### ISSUE THREAD

**Issue by holikz** [angular/angular#27368]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 7.0.4

### Description

The validator on the FormGroup (made by the FormBuilder) does run a validaton process, so the form is invalid when the application loaded.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ammice

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.1.0
Node: 10.13.0
OS: win32 x64
Angular: 7.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.11.0
@angular-devkit/build-angular      0.11.0
@angular-devkit/build-ng-packagr   0.11.0
@angular-devkit/build-optimizer    0.11.0
@angular-devkit/build-webpack      0.11.0
@angular-devkit/core               7.1.0
@angular-devkit/schematics         7.1.0
@angular/cdk                       7.1.0
@angular/cli                       7.1.0
@angular/material                  7.1.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.1.0
@schematics/angular                7.1.0
@schematics/update                 0.11.0
ng-packagr                         4.4.0
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.23.1

</code></pre>

**Anything else relevant?**

**Comment by dawidgarus** [comment]
Angular changed API:
https://github.com/angular/angular/commit/a4398aa17fd11c1c78ad5e514756e901dd2eff96#diff-142bb87a79583032105e2c4d1f367bcf
The validator SHOULD run. It doesn't in older version (7.0.1 in stackblitz example) because you use newer API (`validators` instead of `validator`), but the older angular version doesn't recognize the property and ignores validator.

**Comment by holikz** [comment]
I understand, but why should run on init without any user interaction?
I updated the stackblitz example (to 7.1.0). As you can see now, when the application starts the form is invalid without any user interaction.

**Comment by dawidgarus** [comment]
> I understand, but why should run on init without any user interaction?

@holikz Form initial state can be invalid, that's intended behavior. If you have required field and it's empty by default, you typically want it to be invalid despite the fact that nobody has touched it. There are also other ways that do (and should) trigger validation, for example if the model has been change programmatically. Basically form status should be up to date with it's value no matter how you set the value.
If for some reason you want to check whether control is invalid only after user interaction, you might want to use condition `control.invalid && control.touched`

**Comment by holikz** [comment]
> If you have required field and it's empty by default, you typically want it to be invalid despite the fact that nobody has touched it.

@dawidgarus Actually, i don't want to be invalid, becuase i don't do anyithing with it. Imagine that we have a registration form for example. On initialization and don't want to invalid, because when i hit the submit button all the validators execute's. 

Reactive forms statuses based on user interactions (like dirty, invalid, touched) just like validators on previous releases.

> Basically form status should be up to date with it's value no matter how you set the value.

There IS a difference how you set the value. When you set it programmatically the touched flag is still false, because there wasn't any user interaction. This is why there are the patchValue and the setValue methods with the onlyself/emitEvent options.

> ...you might want to use condition control.invalid && control.touched

If this is true, you need to add this condition to all of your custom validators, and you can't use the integrated Angular validators foe example Validators.required.

And last of all, if you update your application from 7.0.4 to 7.1.0 you need to refactor all of your validation/validators, because they don't work as you expected.

**Comment by dawidgarus** [comment]
> If this is true, you need to add this condition to all of your custom validators, and you can't use the integrated Angular validators foe example Validators.required.

Don't know what's the problem:

```html
<input #inputModel="ngModel" [(ngModel)]="value" required [maxlength]="20">
<ng-container *ngIf="inputModel.invalid && inputModel.touched">
Error message
</ng-container>
```
You can also use .ng-invalid.ng-touched selector to style item.
This is how I do it in my apps.

> I think it is still a bug.

It's the way it's always has been. It's not a bug, that's how validation works. Even build-in validation works this way: https://jsfiddle.net/9kc0btz1/

**Comment by pkozlowski-opensource** [comment]
@dawidgarus explanations are correct. A control is valid or not regardless of users interaction with it. Touched / untouched status can be used to report validity states to users after the interaction has happened.

**Comment by thatsmeta** [comment]
Sorry to comment on this long closed issue, but I am also confused about validation on init.
I have a form with 1 group containing 10 controls. I have a validator on the form group with ```updateOn: 'submit'``` When the form is initialized, the validator is called at least 10 times, which does not seem right to me.
Also, I'm planning to add an async validator making an AJAX call and I would not like for that one to be called multiple times, despite the user never even having touched the form.
How am I supposed to handle that?
