### ISSUE TITLE
Clicking untouched required field doesn't fire statusChanges

### ISSUE THREAD

**Issue by galki** [angular/angular#27367]
The below code doesn't fire when clicking an untouched required field, even though the html attributes of the field get set to `ng-touched` and `ng-invalid`.
```
form.statusChanges.subscribe(() => console.log('form status changed'));
```

**Comment by dawidgarus** [comment]
Control status can be one of VALID, INVALID, PENDING or DISABLED.
Clicking doesn't change it's status. If it is invalid, it was also invalid before the click.
Touched or dirty are additional flags which don't affect controls status.

**Comment by galki** [comment]
@dawidgarus thanks for making it clear.

### problem
With a reactive form all empty required fields are in fact invalid but will not be accessible with `onStatusChanged` right after build... meaning to display error hints so as to be consistent with the input "going red" when a user first clicks a required field, you need your logic to prepare the hints right after building the form.

**Comment by galki** [comment]
Since I was using Angular Material I solved the problem by adding [the following](https://material.angular.io/components/input/overview#changing-when-error-messages-are-shown)
```
@NgModule({
  providers: [
    {provide: ErrorStateMatcher, useClass: ShowOnDirtyErrorStateMatcher}
  ]
})
```
