### ISSUE TITLE
Add findLocaleData to angular/common export

### ISSUE THREAD

**Issue by michelschmit** [angular/angular#27373]
# 🚀 feature request

### Relevant Package
This feature request is for `@angular/common`

### Description
I'll try to find a way to check if my value setted in `LOCAL_ID` is defined in the registered local data. To do this I would like to use  `findLocaleData()`.
The method `findLocaleData()` seem to be export in `@angular/common/common.d.ts` but cannot be used with `@angular/common` package.

### Describe the solution you'd like
Can you add `findLocaleData()` to `@angular/common/src/common.d.ts` so we can use it outside the library ?
Thanks!

**Comment by michelschmit** [comment]
Oup found it, it's can be called form `getLocaleId()`.

**Comment by ocombe** [comment]
Yes I was going to suggest to use `getLocaleId` instead.
`findLocaleData()` is an internal method because we want to be able to change the implementation without making a breaking change.
