### ISSUE TITLE
use systemjs with releases from code.angularjs.org

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#2739]
I use the npm package and I compile all the ES6 files to ES5 (because of [2612](https://github.com/angular/angular/issues/2612) I cannot just use the `js` files at the root)  and I load it together with the other deps using the following setup:
```html
<!-- ES6 -->
<script src="lib/traceur-runtime.js"></script>
<script src="lib/system.js"></script>
<!-- Angular Deps -->
<script src="lib/reflect.js"></script>
<script src="lib/zone.js"></script>
<script src="lib/long-stack-trace-zone.js"></script>
<script src="lib/rx.js"></script>
<script>
    System.defaultJSExtensions = true;
    System.config({
        paths: {
            'angular2/*': 'lib/angular2/*'
        },
        meta: {
            'lib/rx.js': {
                format: 'cjs'
            }
        },
        map: {
            rx: 'lib/rx.js'
        }
    });
    System.import('app/bootstrap').catch(
        console.error.bind(console)
    );
</script>
```
Under `lib/angular2` I have all the compiled files. This setup works fine, but if I want to use the release files at [code.angularjs.org](https://code.angularjs.org/2.0.0-alpha.28), more specifically [angular2.dev.js](https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js) it no longer works with the newest version of SystemJS ([0.18.3](https://github.com/systemjs/systemjs/releases/tag/0.18.3)) and it complains about `rx.js` (I removed all the SystemJS config and the `defaultJSExtensions` in the above example).

![screenshot 2015-06-26 10 33 45](https://cloud.githubusercontent.com/assets/1479737/8373633/daa7debc-1bee-11e5-9a52-9ef6352cd17e.png)

It would be helpful if a clear example of how to setup SystemJS to make it work would be made.

**Comment by TiagoBraga39** [comment]
I also have a similar problem when trying locally.
Don't know how, but this CDN is working for me: <a>http://jspm.io/system.js</a>

Hope it helps,
Tiago Braga

**Comment by rolandjitsu** [comment]
@TiagoBraga39 if you take a look at the version you will see it is [0.16.11](https://jspm.io/system@0.16.11.js), that is why it works :)

**Comment by TiagoBraga39** [comment]
Oh I didn't see you were using 0.18 :)

**Comment by robwormald** [comment]
if you want to use the latest / betas of SystemJS, the best thing to do is to build from source, either the commonJS or ES6, which are both available via npm or jspm (npm/jspm install angular2), rather than using the bundled code. 

there are a significant number of changes between 0.16 and 0.18 of SystemJS, and as of now 0.16 is the stable release, so it doesn't make sense to use 0.18 yet. 

see https://gist.github.com/robwormald/429e01c6d802767441ec for a few tips on setup using the beta.

**Comment by mhevery** [comment]
We do use system.js, but an older version. We are in the process of upgrading but it is blocked on removing traceur. 

I am going to close this as it is a dup of work we are already doing.

**Comment by rolandjitsu** [comment]
@mhevery sounds fair to me :)
