### ISSUE TITLE
d

### ISSUE THREAD

**Issue by raxim1** [angular/angular#27396]

**Comment by raxim1** [comment]
It's not for support, this shit is going to a never-ending cycle.

This is a bogus sanitizer introduced coming from the Angular team, everybody can go into the same trap and can take hours to figure out what the hell is going on.

**Comment by raxim1** [comment]
Pls. fix it.

**Comment by Airblader** [comment]
This is a clear CoC violation, can someone from the core team do something about it please? @jasonaden

**Comment by lazarljubenovic** [comment]
> I'm not asking for your support, just fix this nightmare.

I've got a fix for all your nightmares.

```
rm -rf ./my-project
mkdir my-project
cd $_
yarn init -y
yarn add my-framework-which-is-not-a-nightmare
```

Thanks for the report. Now we can close the issue, right? :smile:

**Comment by raxim1** [comment]
> This is a clear CoC violation, can someone from the core team do something about it please? @jasonaden
> 
> Edit: I've reported this to [conduct@angular.io](mailto:conduct@angular.io) now as well as reported him to Github for abusive language.

Angular abused me in the last 2 years, DomSanitizer was written with complete negligence what i'm fed up with in the last 2 years, and because you guys not focusing on the issues to solve just filtering which one can be ignored, simply there wasn't any better way to report this issue.

I filed my concerns to the conduct@angular.io.

**Comment by Airblader** [comment]
If you feel absued by the framework, I suggest you either help improve it or avoid using it for a prolonged time. Either way, your language is absolutely unacceptable.

For anyone reading this after the fact I'd like to point out that the user chose to cover up his tracks by editing title and content which contained foul language (you can see the edits) as well as deleted further comments of the same pattern.
