### ISSUE TITLE
Imports does not works in dynamic components in production mode 

### ISSUE THREAD

**Issue by mazhekin** [angular/angular#27405]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Description

I am creating the Angular (6.1.0) component dynamically:
`
const TemplateComponent = Component({template})(class {});

const TemplateModule = NgModule({declarations: [TemplateComponent], imports: []})(class {});

const module = this.compiler.compileModuleAndAllComponentsSync(TemplateModule); 
`

I works fine in dev mode and in production mode. But I try to add standard import library CommonModule in TemplateModule. Like this.

`
import {CommonModule} from '@angular/common';

const TemplateModule = NgModule({
    declarations: [TemplateComponent],
    imports: [**CommonModule**]})(class {});
`

Ant it works fine in dev mode. But production failed. In unminified version it shows the error:

## 🔥 Exception or Error
<pre><code>
Unexpected value 'CommonModule' imported by the module 'TemplateModule'. Please add a @NgModule annotation.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
"@angular/core": "^6.1.0",
</code></pre>
![7df26328f2](https://user-images.githubusercontent.com/846556/49357790-137b8b80-f6d9-11e8-883a-a1b62c30e0fa.jpg)

**Comment by mlc-mlapis** [comment]
trotyl ... hmm, theoretically possible by disabling optimization step during AOT build process?

**Comment by trotyl** [comment]
@mlc-mlapis `optimization` is mostly about webpack/uglify level configuration, while `removeDecorators` is an [direct step in transformers controlled by JIT/AOT switch](https://github.com/angular/angular-cli/blob/8bc6e79d896661a52ce3c77dce3d562b0ff2719d/packages/ngtools/webpack/src/angular_compiler_plugin.ts#L843-L846).

**Comment by mlc-mlapis** [comment]
@trotyl ... ah, I already forget about the details of that issue. You are right. Thanks.

**Comment by trotyl** [comment]
@mlc-mlapis It's indeed confusing, there's also a [build-optimizer step](https://github.com/angular/angular-cli/tree/master/packages/angular_devkit/build_optimizer#scrub-file) doing the same thing...

**Comment by mlc-mlapis** [comment]
@trotyl ... lol, so did I really remember that correctly?

The resume could be: **If you disable `build-optimzer step` you are able to keep decorators in the final AOT code but it also means that its size is actually significantly much bigger.** Right?

**Comment by mlc-mlapis** [comment]
@trotyl ... I understand. OK.

**Comment by alxhub** [comment]
Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Thank you!
