### ISSUE TITLE
event emitter with (activate) name bind native activate event in IE11 only

### ISSUE THREAD

**Issue by djleonskennedy** [angular/angular#27418]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common

### Is this a regression?

No

### Description

If you create output with name `activate` in Internet Explorer 11, it'll bind this event also as UI Event
from here: https://developer.mozilla.org/en-US/docs/Web/Events/Activate
why bug, in my opinion behavior have to be same in all browser, but this problem appears in IE11 only

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-oqzmkk?file=src%2Fapp%2Fhello.component.ts

## 🔥 Exception or Error
<pre><code>
Look at console in reproduction link
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 6.1.3
Node: 8.9.4
OS: win32 x64
Angular: 6.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.7.3
@angular/cdk                      6.4.5
@angular/cli                      6.1.3
@angular/material                 6.4.5
@ngtools/webpack                  6.0.8
@schematics/angular               0.7.3
@schematics/update                0.7.3
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3
</code></pre>

**Anything else relevant?**
Internet Explorer 11

**Comment by djleonskennedy** [comment]
Problem source provided by @AndriiDidkivsky

**Comment by trotyl** [comment]
It's expected behavior, see https://medium.com/sv-blog/angular-activate-and-deactivate-event-gotcha-in-ie-882e6d3cd8ce for more information.

**Comment by djleonskennedy** [comment]
@trotyl Thank you for info, might this issue will be helpful for some one
