### ISSUE TITLE
Angular 7 Drop down list inside material table data source is selecting the last item of the array

### ISSUE THREAD

**Issue by alim90** [angular/angular#27412]
I have this form group inside an angular material table having data source;

    <ng-container matColumnDef="fr">
        <th mat-header-cell *matHeaderCellDef> Family Rel. </th>
        <td mat-cell *matCellDef="let element">
            <mat-form-field color="warn" appearance="outline">
            <mat-label>Family Relation</mat-label>
                 <mat-select id="family_relation" formControlName="family_relation" placeholder="Family Relation">
                       <mat-option *ngFor="let familyRelation of familyRelationArray; let i = index" [value]="familyRelation.family_relation_id">
                            {{familyRelation.family_relation_type}}
                       </mat-option>
                 </mat-select>
            </mat-form-field>&nbsp;
                      {{element.fr}}
        </td>
    </ng-container>

I am getting `familyRelationArray` from this method:

    getFamilyRelation() {
        let status = 'Active';
        this.auth.getFamilyRelation(status).subscribe(
          (data) => {
            this.familyRelationArray = data;
          },
          (error) => {
            console.log(error);
          }
        );
      }

For each row displayed in my material table, their is a different family relation.

I am displaying data using the following:

    getData()
      {
        this.auth.getIndPerHousehold(this.hh_id).subscribe(
          (data)=>{
            if(data=="empty")
            {
              this.showEmpty = true;
            }
            else
            {
              this.showEmpty = false;
              this.dataSource = new MatTableDataSource(Object.values(data));
              this.resultsLength = Object.values(data).length;
              this.dataSource.paginator = this.paginator;
              this.dataSource.sort = this.sort;
              // this.formGroup.controls['family_relation'].setValue(Object.values(data[0]['frid']));
              Object.values(data).forEach(element => {
                //console.log(element.frid)
                this.formGroup.get('family_relation').setValue(element.frid);
              });
            }
          },
          (error)=>
          {
            console.log(error);
          }
        );
      }

I am using the following to select the correspondent relation of each individual in the family:

    Object.values(data).forEach(element => {
        //console.log(element.frid)
        this.formGroup.get('family_relation').setValue(element.frid);
    });

What is displayed in the table is the regular data but the drop down lists are selecting the last imported value of `element.frid`.

So the last row is a child, all the drop down lists are selecting `child`.

[![enter image description here][1]][1]

Please note that `frid` is the same as family_relation_id.

How to run a loop inside datasource subscribe result to let the drop down list select the exact value of each row ?

  [1]: https://i.stack.imgur.com/yg1BF.jpg

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
