### ISSUE TITLE
Subscribing to query params not working after returning to the page

### ISSUE THREAD

**Issue by ildar-icoosoft** [angular/angular#27429]
I have a page: /news with query parameter page.

I have a subscription to query params

```
export class NewsPage implements OnInit {
    ngOnInit() {
        this.route.queryParams.subscribe(params => {
            ...
        });
    }
}
```

If I open /news and navigate to /news?page=1 then subscription works fine.

But if I open /news and navigate to /another-page and then again navigate to /news and navigate to /news?page=1 then subscription is not working anymore. I use Angular 6

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/27430
