### ISSUE TITLE
Investigate init phase time Bazel unit tests

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#27427]
Aside from execution proper, there is always ~1.6s spent in the initialization phase. 

This seems somehow related to rules_typescript and rules_go and should be investigated further.

**Comment by filipesilva** [comment]
For added context, these are the reproduction steps to see time spent in init phase:
```
git clone https://github.com/angular/angular
cd angular
yarn
yarn bazel test //packages/core/test/render3
yarn bazel test //packages/core/test/render3 --profile debug.profile
yarn bazel analyze-profile debug.profile  --html --html_details --html_histograms
yarn bazel analyze-profile debug.profile --task_tree ".*" --task_tree_threshold 0 --record_full_profiler_data
```

@meteorcloudy did a lot of work investigating how these VFS calls were originating inside of Bazel, the our best guess so far is a set of globs that both `rules_nodejs` and `rules_go` use:

https://github.com/bazelbuild/rules_nodejs/blob/01ab48e71c6ea2643c244cbb7d46d299f7340e4a/internal/node/node_repositories.bzl#L248-L265
```
filegroup(
  name = "node_runfiles",
  srcs = glob(
    [
      "bin/node.js",
      "{node_dir}/**",
      "{yarn_dir}/**",
    ],
    exclude = [
      "**/*.md",
      "**/*.html",
      # These files are generated during node-gyp compilation and include
      # absolute paths, making them non-hermetic.
      # See https://github.com/bazelbuild/rules_nodejs/issues/347
      "**/*.pyc",
    ],
  ),
)
```

https://github.com/bazelbuild/rules_go/blob/368049409d12d0827dcfd0bd401188c22651cc29/go/private/BUILD.sdk.bazel#L57-L64
```
filegroup(
    name = "files",
    srcs = glob([
        "bin/go*",
        "src/**",
        "pkg/**",
    ]),
)
```

In both cases the globs seem to be part of templates, which we have seen in the past (https://github.com/bazelbuild/rules_nodejs/pull/405) can be problematic for performance.

**Comment by filipesilva** [comment]
rules_nodejs PR up in https://github.com/bazelbuild/rules_nodejs/pull/472, rules_go issue file as https://github.com/bazelbuild/rules_go/issues/1862.

**Comment by meteorcloudy** [comment]
Wow, this is so nice!

**Comment by filipesilva** [comment]
Closed as https://github.com/bazelbuild/rules_nodejs/pull/472 is now merged.
