### ISSUE TITLE
__Zone_disable_requestAnimationFrame and other overrides are applied too late

### ISSUE THREAD

**Issue by drummerboof** [angular/angular#27428]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/angular-cli

### Is this a regression?
Not sure

### Description
The polyfill file that comes with angular-cli has a section containing overrides for ZoneJS: https://github.com/angular/angular-cli/blob/64d15246494e92d0f27a100eac1b3450d1201d6b/packages/schematics/angular/application/files/src/polyfills.ts#L62

I noticed when setting `__Zone_disable_requestAnimationFrame` in a project that it wasn't actually stopping ZoneJS from patching it. When I added some logging in, it was apparent that Zone.JS was running and patching DOM APIs *before* that value wasa being set. 

I believe this is because Zone.JS is brought in using the `import` statement which gets hoisted to the top of the file so the ZoneJS code is running before that flag is applied

## 🔬 Minimal Reproduction
I have created a repo demonistrating this [here](https://github.com/drummerboof/angular-raf-issue). This is literally the CLI cloned and then setting that variable. Interestingly, the issue is not reproducible on Stackblitz.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.0.7
Node: 8.9.4
OS: darwin x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
</code></pre>

**Anything else relevant?**
Not happening in StackBlitz.

**Comment by JiaLiPassion** [comment]
I will check it ,thanks!

**Comment by longgt** [comment]
@drummerboof @JiaLiPassion description and workaround is here
https://github.com/angular/angular-cli/issues/12886

I think it's duplicated with it.

**Comment by JiaLiPassion** [comment]
@longgt, thanks for the information.

**Comment by drummerboof** [comment]
Ah yes - that is the same issue for sure - thanks! Not sure why I didn't check in or open this in angular-cli tbh. Glad it's on the radar! I'll close this as it is a duplicate.
