### ISSUE TITLE
Reduce Angular Template compilation time in Bazel unit tests

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#27424]
Angular Template compilation is where most time is being spent, always running over core/common/platform-browser/http/platform-server when changing the ivy runtime. Most of these only take <100ms, but core takes 11s. 

It is not clear to me if this compilation is necessary, and can perhaps be wholly eliminated from the dependency graph. Otherwise it would need to be massively improved to ever reach the expectations.

**Comment by filipesilva** [comment]
The command to run ivy tests is `yarn bazel test //packages/core/test/render3`. A profile for this run can be generated by adding `--profile PROFILE_NAME.profile` to the command. You can read more about profiling in [docs/BAZEL.md#diagnosing-slow-builds](https://github.com/angular/angular/blob/master/docs/BAZEL.md#diagnosing-slow-builds).

When changing the Ivy source code itself I have observed that template compilation for a core/common/platform-browser/http/platform-server is part of it.

You can see this by following these steps:
- setup the angular repository `git clone https://github.com/angular/angular && cd angular && yarn`
- run a first build to load all dependencies `yarn bazel test //packages/core/test/render3`
- change `packages/core/src/render3/assert.ts` by adding a space to one of the error messages in that file (e.g. in `assertComponentType` add a space after `property.`)
- profile this rebuild `yarn bazel test //packages/core/test/render3 --profile change-runtime.profile`
- analyze the profile `yarn bazel analyze-profile change-runtime.profile`
- see the critical path at the end of the report:
```
Critical path (26.729 s):
    Id        Time Percentage   Description
  1743     9.941 s   37.19%   action 'Testing //packages/core/test/render3 render3'
  1742     36.8 ms    0.14%   runfiles for //packages/core/test/render3 render3
  1741     5.50 ms    0.02%   action 'Compiling TypeScript (devmode) //packages/core/test/render3 domino'
  1740     53.4 ms    0.20%   action 'Compiling Angular templates (ngc) //packages/platform-server platform-server'
  1739     54.3 ms    0.20%   action 'Compiling Angular templates (ngc) //packages/http http'
  1738     91.4 ms    0.34%   action 'Compiling Angular templates (ngc) //packages/platform-browser platform-browser'
  1737      150 ms    0.56%   action 'Compiling Angular templates (ngc) //packages/common common'
  1736    16.396 s   61.34%   action 'Compiling Angular templates (ngc) //packages/core core'
```

You can see that `Compiling Angular templates (ngc)` takes about two thirds of the time in the critical path. This is somewhat puzzling because it is not clear why templates for http need to be compiled before running unit tests in `//packages/core/test/render3`.

Bazel allows [querying](https://docs.bazel.build/versions/master/query-how-to.html), and one of the ways we can query is to trace the dependency chain between two targets.

To know why `//packages/core/test/render3` needs to be rebuilt when we changed `packages/core/src/render3/assert.ts`, we can run `yarn bazel query "somepath(//packages/core/test/render3, //packages/core:src/render3/assert.ts)"`:
```
$ yarn bazel query "somepath(//packages/core/test/render3, //packages/core:src/render3/assert.ts)"
yarn run v1.10.1
$ bazel query "somepath(//packages/core/test/render3, //packages/core:src/render3/assert.ts)"
nodejs_test rule //packages/core/test/render3:render3
ts_library rule //packages/core/test/render3:render3_node_lib
ts_library rule //packages/core/test/render3:render3_lib
ng_module rule //packages/core:core
source file //packages/core:src/render3/assert.ts
Done in 1.63s.
```

And to know how `//packages/core/test/render3,` depends on `//packages/http`, we can run `yarn bazel query "somepath(//packages/core/test/render3, //packages/http)"`:

```
$ yarn bazel query "somepath(//packages/core/test/render3, //packages/http)"
yarn run v1.10.1
$ bazel query "somepath(//packages/core/test/render3, //packages/http)"
nodejs_test rule //packages/core/test/render3:render3
ts_library rule //packages/core/test/render3:render3_node_lib
ts_library rule //packages/core/test/render3:domino
ng_module rule //packages/platform-server:platform-server
ng_module rule //packages/http:http
Done in 1.60s.
```

It looks like `//packages/core/test/render3:domino` is the connection point. This explains why `//packages/http:http` and others show up when building `//packages/core/test/render3`. 

But it is not clear why `//packages/http:http` needs to be rebuilt when the ``packages/core/src/render3/assert.ts`` file changed. Again we can query to know:
```
$ yarn bazel query "somepath(//packages/http, //packages/core:src/render3/assert.ts)"
yarn run v1.10.1
$ bazel query "somepath(//packages/http, //packages/core:src/render3/assert.ts)"
ng_module rule //packages/http:http
ng_module rule //packages/core:core
source file //packages/core:src/render3/assert.ts
Done in 1.57s.
```

The end result is that changing `packages/core/src/render3/assert.ts` causes `//packages/core` to be rebuilt, and since the `//packages/core/test/render3` depends on core/common/platform-browser/http/platform-server then it must wait for all of those to be rebuilt before the tests can run.

**Comment by filipesilva** [comment]
It's also worth noting what the dependencies for `//packages/core/test/render3` are:
```
ts_library(
    name = "render3_lib",
    testonly = True,
    srcs = glob(
        ["**/*.ts"],
        exclude = [
            "**/*_perf.ts",
            "domino.d.ts",
            "load_domino.ts",
            "jit_spec.ts",
        ],
    ),
    deps = [
        "//packages:types",
        "//packages/animations",
        "//packages/animations/browser",
        "//packages/animations/browser/testing",
        "//packages/common",
        "//packages/compiler",
        "//packages/core",
        "//packages/core/testing",
        "//packages/platform-browser",
        "//packages/platform-browser/animations",
        "//packages/platform-browser/testing",
        "//packages/private/testing",
    ],
)

ts_library(
    name = "domino",
    testonly = True,
    srcs = [
        "domino.d.ts",
        "load_domino.ts",
    ],
    deps = [
        "//packages/compiler",
        "//packages/platform-browser",
        "//packages/platform-server",
        "@ngdeps//zone.js",
    ],
)
```

In hindsight it is not surprising these tests are slow to build. They depend on almost all the other Angular packages, and most of those also depend on `//packages/core`.

When `//packages/core` change, most things need to be rebuilt.

**Comment by filipesilva** [comment]
To test the impact of having so many dependencies for render3 tests, I added a mini set of tests that depends only on core and nothing else:
```
// packages/core/test/render3/BUILD.bazel

ts_library(
    name = "render3_mini_lib",
    testonly = True,
    srcs = glob(
        ["util_spec.ts"],
    ),
    deps = [
        "//packages/core",
    ],
)

jasmine_node_test(
    name = "render3_mini",
    deps = [
        ":render3_mini_lib",
    ],
)
```

The `util_spec.ts` test only checks utility functions and does not need any other setup. 

I gathered the profile in the same way listed in https://github.com/angular/angular/issues/27424#issuecomment-444116352, except I the `//packages/core/test/render3:render3_mini` target instead and edited `packages/core/render3/util.ts` by adding a space to the string in `assertDefined(rootView[CONTEXT], 'RootView has no context. Perhaps it is disconnected?');`.

```
Critical path (10.731 s):
    Id        Time Percentage   Description
  1886     1.312 s   12.23%   action 'Testing //packages/core/test/render3 render3_mini'
  1885     15.4 ms    0.14%   runfiles for //packages/core/test/render3 render3_mini
  1884     1.67 ms    0.02%   action 'Compiling TypeScript (devmode) //packages/core/test/render3 render3_mini_lib'
  1883     9.402 s   87.62%   action 'Compiling Angular templates (ngc) //packages/core core'
```

This critical path was much shorter (10.7s vs 26.7) but it still contained the largest item as Angular template compilation for `//packages/core`. It is interesting to see that running the tests themselves were also much faster (1.3s vs 9.7s).

It's relevant to mention that although the critical path was much shorter, it's distribution was mostly the same: mostly `'Compiling Angular templates (ngc) //packages/core core'` and `'Testing //packages/core/test/render3 render3_mini'`, with minuscule time taken in anything else. These tests are highly dependent on the available resources of the host machine and were taken in different days, so perhaps the decrease is not as significant as it seems given the time is still mostly spent on the same thing.

The 1.3s test runtime is small shorter than the [previously observed 3.4s](https://docs.google.com/document/d/1KFojATGea84_GA3qwRk2cLopPs0LwjZUpT0j7xFasm4/edit#heading=h.4xaywtqhcvak) for a focused test. This suggests that module loading and test setup for `//packages/core/test/render3` might account for more time than previously thought. Conversely, the startup time for `jasmine_node_test` without workers must be less than I thought.

One such setup file that seems to drastically increase test boot time is `load_domino`. Adding it back to the `render3_mini` target
```
jasmine_node_test(
    name = "render3_mini",
    bootstrap = [
        "angular/packages/core/test/render3/load_domino",
    ],
    deps = [
        ":render3_mini_lib",
    ],
)
```
Increases the test run time from 1.3s to 2.6s. 

Looking into the `load_domino.ts` file we can see it is rather simple: a few imports and function calls. Commenting out everything but the imports, but still using them via `console.log(DominoAdapter, getDOM, domino);`, we can see a ~2.5s test run time. Removing the `console.log` returns the runtime to ~1.4s.

This result indicates that a significant amount of time is spent merely loading the imports.

The still long (9.7s) Angular template compilation for `//packages/core` suggests that is the main time spender, regardless of the simplified dependency graph.

We can validate this hypothesis without tests by profiling a build of `//packages/core` with the same change to `packages/core/render3/util.ts` as above. 
```
Critical path (6.484 s):
    Id        Time Percentage   Description
  1238     6.484 s  100.00%   action 'Compiling Angular templates (ngc) //packages/core core'
```

We can see here that changing core incurred a 6.5s build time. 

Thus (for now) we can conclude that:
- a smaller dependency graph for `//packages/core/test/render3` reduces total time, but most of the time is still being spent in compiling core and test runtime.
- loading modules in `jasmine_node_test` seems to take a long time
- building core always takes a long time

**Comment by alexeagle** [comment]
Drilling into why `//packages/core` is slow to build.

It has nearly 35K LOC
```
$ find packages/core/src -name "*.ts" | xargs cat | wc -l
   34916
```

Drilling down by directory:
```
$ for d in $(find packages/core/src -type d); do (echo -n $d; cat $d/*.ts | wc -l); done
packages/core/src    1777
packages/core/src/change_detection     394
packages/core/src/change_detection/differs    1396
packages/core/src/debug     445
packages/core/src/di    3139
packages/core/src/i18n     111
packages/core/src/linker    1067
packages/core/src/metadata    2069
packages/core/src/profile     159
packages/core/src/reflection     393
packages/core/src/render     383
packages/core/src/render3   11319
packages/core/src/render3/features     355
packages/core/src/render3/interfaces    2854
packages/core/src/render3/jit     927
packages/core/src/render3/styling    1186
packages/core/src/sanitization     957
packages/core/src/testability     313
packages/core/src/util     265
packages/core/src/view    5072
packages/core/src/zone     335
```

Note that in google3 we would never have 35K LOC in a single compilation unit. The solution is to break it up, starting with render3 as its own library target.

**Comment by filipesilva** [comment]
I took a Bazel profile and Chrome profile of `yarn bazel build //packages/core` with a single space change using https://github.com/bazelbuild/rules_typescript/pull/345.
- Bazel profile: [ngc-with-profiler.bazelprofile](https://drive.google.com/open?id=1lbHfCr2CC6Za-pBFDchOb0EeUvNCcwL9)
- Chrome profile: [ngc-with-profiler.cpuprofile](https://drive.google.com/open?id=1k1MYUwCc-IwNHCZrXTUCVv9wSNktcKzS)

You can analyze the bazel profile with `yarn bazel analyze-profile ngc-with-profiler.bazelprofile`. The relevant part is the critical path:
```
Critical path (12.778 s):
    Id        Time Percentage   Description
   759    12.778 s  100.00%   action 'Compiling Angular templates (ngc) //packages/core core'
```

This means all of the time in the critical path was spent in `ngc`. The 12.7s shown are longer than previously reported times, but it's not surprising since profiling itself always makes the process slower.

To open the Chrome profile I recommend https://github.com/GoogleChromeLabs/ndb, but the performance tab in Chrome works as well.

The Chrome profile shows a total of 8.9s profiled. It's not unusual to miss a couple of seconds as the profiler starts up, but perhaps the missing time should be further scrutinized. Regardless, the 8.9s matches previous durations of the critical path without the profiler, so it is plausible enough.

The call tree of the compilation shows the major contributors to time as;
- TypeScripts `emit` at 4.4s
- TypeScripts `gatherSemanticDiagnostics` at 1.7s
- AngularCompilers `getTsProgram` at 1.6s (this call includes program creation and update)

![image](https://user-images.githubusercontent.com/4172079/49732141-8060c980-fc75-11e8-96f2-5da3a3fc3606.png)

So although it is slow, nothing obvious stands out as out of place. This lends further support that `//packages/core` is just fairly large as far as Ts compilation units go.

**Comment by atscott** [comment]
@filipesilva @josephperrott  Is there anything here that's still relevant or can this be closed?

**Comment by filipesilva** [comment]
@atscott might be better to ask @pkozlowski-opensource, this analysis started from his report that FW unit tests were slow. I'm not sure if it's still true.

**Comment by AndrewKushnir** [comment]
I've set the priority as `P4` for now, since the perf can definitely be improved (thus investigation results are useful), but it's not the top priority atm.

**Comment by alxhub** [comment]
Closing; no longer relevant.
