### ISSUE TITLE
Angular Upgrade - upgraded components don't work when used inside entryComponents loaded dynamically

### ISSUE THREAD

**Issue by llRandom** [angular/angular#27432]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/upgrade

### Is this a regression?
No

### Description
I have an angular 6 component loaded dynamically and added to `entryComponents`. When I use any upgraded component inside it I get `No provider for $scope` error

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-issue-repro2-htx2fm

## 🔥 Exception or Error
<pre><code>
Error: StaticInjectorError(AppModule)[$scope]: 
  StaticInjectorError(Platform: core)[$scope]: 
    NullInjectorError: No provider for $scope!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:979)
    at resolveToken (core.js:1232)
    at tryResolveToken (core.js:1182)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1077)
    at resolveToken (core.js:1232)
    at tryResolveToken (core.js:1182)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1077)
    at resolveNgModuleDep (core.js:9217)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:9911)
    at Object.resolveDep (core.js:10276)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>6.0.0</code></pre>

**Comment by alexzuza** [comment]
Angular is looking for providers by walking up first the element injector tree and then the module injector tree.

`$scope` provider is registered as root element injector for your AppComponent
https://github.com/angular/angular/blob/140217546d9cc99d8063cc37de6d054fd3297b08/packages/upgrade/src/common/downgrade_component_adapter.ts#L61-L66 
but you use module injector when creating your dynamic component.

To workaround it you can pass element injector to your method.

```
export class AppComponent implements OnInit {
  constructor(private domService: DomService, private elInjector: Injector) { }

  ngOnInit() {
    this.domService.appendComponentToContainer(NestedComponent, document.body, this.elInjector);                                                                                                        
  }
} 

...
  appendComponentToContainer<T>(component: Type<T>, container: Node, injector: Injector) {
    const componentRef = this.componentFactoryResolver
      .resolveComponentFactory(component)
      .create(injector); 
```

**Comment by llRandom** [comment]
And if the actual dependency graph is more complex, if component is created inside another service that has no direct dependency on root component, is there any way to resolve the right `Injector` in constructor or the only way is to pass it through the whole callstack as an argument?

**Comment by gkalpak** [comment]
@alexzuza is right. If the root of your hybrid is `AppComponent`, then other upgraded/downgraded components need to be "linked" to that.
You don't have to pass `AppComponent`'s injector; you can pass the injector of an element that is "linked" to `AppComponent` (e.g. a descendant). The main point is that the component that adds this lazy component (which must be part of the hybrid app) has to link it to _its_ injector.

Closing, since everything seems to be working as expected, but feel free to continue the discussion below.

**Comment by llRandom** [comment]
is it possible to define provider that will resolve it to a proper `Injector` instance?

**Comment by gkalpak** [comment]
It depends on how you bootstrap your component and what you "root" downgraded component is.
Off the top of my head, for your example you could have a method on `DomService` to set the downgraded "rootInjector":

```ts
class DomService {
  ...
  appendComponentToContainer<T>(component: Type<T>, container: Node) {
    const componentRef = this.componentFactoryResolver
        .resolveComponentFactory(component)
        .create(this.rootInjector);
    ...
  }
 
  setRootInjector(injector: Injector) {
    this.rootInjector = injector;
  }
}

class AppComponent {
  constructor(private domService: DomService, elInjector: Injector) {
    domService.setRootInjector(elInjector);
  }
  ...
}
```
