### ISSUE TITLE
Subscribing to route params is not working

### ISSUE THREAD

**Issue by ildar-icoosoft** [angular/angular#27430]
I have a page /news with parameter "page". For example: "/news;page=2". I don't want to reinitialize news page when page is changed. I just want to subscribe to page changes, I've tried this code:

```
export class NewsPage implements OnInit {
    constructor() {
    }

    ngOnInit() {
        this.route.params.subscribe(params => {
            ...
        });
    }
}
```

If /news page is opened and I navigate to /news page with different page parameter (this.router.navigate(['/news', {page: 2} ])) then the page is reinitialized (the page is destroyed and created again).

But if I use queryParams (/news?page=2) instead of params (/news;page=2) then everything works fine:

```
export class NewsPage implements OnInit {
    constructor() {
    }

    ngOnInit() {
        this.route.queryParams.subscribe(params => {
            ...
        });
    }
}
```

If I call this.router.navigate(['/news'], {queryParams: {page: 2}} ) then the page is NOT reinitilized. Just subscribe callback is executed. Why does it happen?

**Comment by ericmartinezr** [comment]
I'm sorry but reported issues require a StackBlitz reproducing the problem.

If this issue persists, please create a StackBlitz using this template and describe the difference between the expected and current behavior and create a new issue: https://stackblitz.com/fork/angular-gitter

**Comment by Gillespie59** [comment]
Your URL "/news;page=2" looks incorrect to me. URL with params should like "news/2", "news/1", ...

**Comment by djleonskennedy** [comment]
@Gillespie59 could you attach you config ?

**Comment by ildar-icoosoft** [comment]
I'm sorry, I get this error only in Ionic, it's ok in pure angular
