### ISSUE TITLE
When the website is switched to offline mode, ServiceWorker is unable to retrieve manifest file - Angular 6

### ISSUE THREAD

**Issue by nishant-garg17** [angular/angular#27448]

**Comment by gkalpak** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
