### ISSUE TITLE
why latest angular framework is extremely slow on low cpu device(Windows 10  Ram:2gb  processor: 1.00GHz)  on google chrome 

### ISSUE THREAD

**Issue by arya-himanshu** [angular/angular#27453]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 have created a simple project in which i have install bootstrap 4. But it seem its taking 8-10 second to load the page and CPU usage > 100 %.

Please find all the required details on below mentioned link 

https://stackoverflow.com/questions/53609108/angular-7-why-framework-is-extremely-slow-on-low-cpu-device-windows-10-on-go

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
