### ISSUE TITLE
Angular material loses css files during build step

### ISSUE THREAD

**Issue by jakemac53** [angular/angular#2745]
Under dist/dart/angular2_material/lib/src/components I only see dart and html files, not css files.

**Comment by naomiblack** [comment]
@rkirov @jelbourn can one of you have a look at this? It is one of the blockers for adding transformers for material

**Comment by jelbourn** [comment]
@jakemac53 Did you run `gulp build.dart.material` ?

**Comment by jakemac53** [comment]
I ran gulp build/packages.dart, which in the past has always been enough for me... it does create that angular_material folder so I would expect it to be functioning. Maybe that build command just needs to have an additional step added or something?

**Comment by jelbourn** [comment]
Only the commands that have `material` in the name do anything with CSS; I didn't want to pollute the angular-core build rules with additional components work. `gulp build.dart.material` will give you the CSS for Dart. `build.js.material` and `build.dart2js.material` will also output the CSS into the appropriate directories.

@jakemac53  Does that give you what you need?

**Comment by jakemac53** [comment]
sounds like it does yes, do we have all these build rules documented anywhere? It still seems wrong to me that build/packages.dart makes a non-functioning angular2_material folder....

**Comment by jelbourn** [comment]
Nowhere other than the gulpfile itself, unfortunately. The difference between `build/packages.dart` and the material rule is that the latter will eventually be removed when the components are extracted into their own library.

**Comment by jakemac53** [comment]
I tried this but I still don't see the css files under `lib/src`. I do see them under `src` though.... and maybe this is working as intended for js but it seems like it will need to change for dart. The styles typically have an @import to "angular2_material/src/components/*/*.css". In dart you won't be able to access things in a top level `src` folder, they will need to be under `lib/src`.

Maybe something else is going on here which I can't see directly?

**Comment by jakemac53** [comment]
Nvm, build was in a broken state I see them now. We are probably going to need to do something with the urls still at some point (convert to package: urls?), but thats a separate issue.
