### ISSUE TITLE
Angular Router - routerLinkActive ignores fragments

### ISSUE THREAD

**Issue by dvdvnl** [angular/angular#27450]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?
I can not say. I've first tried implementing it in 7.0.* where the behaviour was the same.

### Description
The goal is a navigation with anchor links which are highlighted as active whenever the route points to the link's (complete) url (e.g. _/foo/bar#one_).

The issue manifests itself when working with _routerLink_, _routerLinkActive_, _routerLinkActiveOptions_, and _fragment_. When setting _routerLinkActiveOptions_ to `{exact: true}`, according to [the documentation](https://angular.io/api/router/RouterLinkActive#routerLinkActiveOptions), the router is expected to set the _routerLink_ as active only if the url matches exactly. By my assumption this includes parameters and anchor tags as well - otherwise it would not make much sense to set `[routerLinkActiveOptions]="{exact: true}"` at all.
However, this is not the case, as every link that points to the same (routerLink) url is set as active.

While researching the issue I found a [PR](https://github.com/angular/angular/pull/27108) that targets a similar behaviour with url parameters (related to [#19399](https://github.com/angular/angular/issues/19399) and [#20698](https://github.com/angular/angular/issues/20698)).

## 🔬 Minimal Reproduction
[→ StackBlitz](https://stackblitz.com/edit/dvl-ng-router-anchorscrolling)

## 🌍  Your Environment

**Angular Version:**
<pre><code>"@angular/compiler": "^7.1.1",
"@angular/core": "^7.1.1",
"@angular/common": "^7.1.1",
"@angular/router": "^7.1.1",</code></pre>
[→ Link to package.json](https://stackblitz.com/edit/dvl-ng-router-anchorscrolling?file=package.json)

**Anything else relevant?**

The behaviour persists in the following browsers (all that I tested):

Windows 10:
- Chrome 70
- Firefox 63
- Edge 42
- IE 11

Mac OS Mojave:
- Safari 12
- Chrome 70
- Firefox 63

**Comment by jasonaden** [comment]
Thanks for the issue and the link to the PR regarding matrix params. I've added this issue and that PR to my next iteration so will be looking at both in the next couple weeks.

**Comment by tuxd** [comment]
I'm having the same problem, is there a fix for it?

**Comment by dvdvnl** [comment]
> Thanks for the issue and the link to the PR regarding matrix params. I've added this issue and that PR to my next iteration so will be looking at both in the next couple weeks.

@jasonaden Did you already get a chance to look into this and/or #27108 ?

**Comment by BenRacicot** [comment]
Just thought I'd ask if there are plans to merge [pull/27108](https://github.com/angular/angular/pull/27108)

**Comment by shaji-Dev** [comment]
Having the same issues. Is there a fix for this? To support fragments?

**Comment by tommck** [comment]
I can't believe this issue (and many like it) have not been addressed since **Angular 2**.

**Comment by atscott** [comment]
Resolved in #40303
