### ISSUE TITLE
Add "Was this helpful?" widget to docs pages

### ISSUE THREAD

**Issue by robwormald** [angular/angular#27463]
### Description
Google web-related docs pages are standardizing on a GA-backed "Was this helpful?" widget for capturing feedback on docs pages. We'd like to implement this for the Angular docs.

## 🔬 Minimal Reproduction
Examples of this already implemented:
- k8s docs - https://github.com/kubernetes/website/pull/11037
- simple glitch demo - https://glitch.com/edit/#!/wasthispagehelpful?path=index.html:1:0

### Anything else relevant?
@kaycebasques offered to help with implementation (and did the above demos).
Uses Google Analytics (which we already use on aio).

**Comment by kaycebasques** [comment]
By "standardizing" Rob of course meant "Kayce is on a one-man crusade" to make this happen.

Happy to provide more context on how to make this data useful, and why I recommend using Google Analytics Events for the tracking.

We've also implemented these widgets on most of the pages on developers.google.com/web.

**Comment by gkalpak** [comment]
Sounds cool! ✨ 

One way to incorporate this into angular.io would be having the `DovViewer` (which manages swapping the main doc content) inject an element to the bottom of each page (except for marketing pages probably). This would be similar to how we [inject the Table-Of-Contents component][1].

Then we would need a new Angular component (that would be converted to a custom element) added [here][2] (similar to the others in there). It would be a simple component with two button, a message (to be displayed on reponse) and a click handler that would use the [GaService][3] (e.g. [sendEvent()][4] or something similar) to record the feedback.

@kaycebasques, would you be interested in working on this? 🤔 

[1]: https://github.com/angular/angular/blob/6740d0de74e3c399bd09254df579d6a3828fa7ee/aio/src/app/layout/doc-viewer/doc-viewer.component.ts#L102
[2]: https://github.com/angular/angular/tree/master/aio/src/app/custom-elements
[3]: https://github.com/angular/angular/blob/6740d0de74e3c399bd09254df579d6a3828fa7ee/aio/src/app/shared/ga.service.ts
[4]: https://github.com/angular/angular/blob/6740d0de74e3c399bd09254df579d6a3828fa7ee/aio/src/app/shared/ga.service.ts#L32-L34

**Comment by kaycebasques** [comment]
Those seem like helpful instructions, @gkalpak. I'll take a go at it.

**Comment by ajitsinghkaler** [comment]
@gkalpak if you can guide me through it I can try it

**Comment by gkalpak** [comment]
Not sure if we should move forward with this. @robwormald, @IgorMinar?

**Comment by ajitsinghkaler** [comment]
@gkalpak should I TRY THIS

**Comment by gkalpak** [comment]
https://github.com/angular/angular/issues/27463#issuecomment-558096438 :grin:

**Comment by petebacondarwin** [comment]
Closing as there has been little activity in implementing this; moreover the dev-rel / docs teams have not shown an interest in acquiring this kind of information over what we get from Google analytics already.
