### ISSUE TITLE
It is unclear when looking at the docs whether or not private viewchild is allowed

### ISSUE THREAD

**Issue by KrisHaney** [angular/angular#27467]
# 📚 Docs or angular.io bug report

### Description

Found here:
https://angular.io/guide/aot-compiler#phase-2-code-generation
is the statement:
> Decorated component class members must be public. You cannot make an @Input() property private or internal.

But here:
https://angular.io/guide/component-interaction#parent-calls-an-viewchild
is an example of a private @ViewChild

Further more, performing my own checks with '--prod' seems to confirm that it does work just fine.  I would like to be able to make a member private if it's truly only in use internally by the class (obviously still needs to be public if used by the template).

### What's the affected URL?**

https://angular.io/guide/aot-compiler#phase-2-code-generation
https://angular.io/guide/component-interaction#parent-calls-an-viewchild

### Reproduction Steps**

Create an annotated member like the following:

``` ts
@ViewChild(MyDirective)
private myDirective: MyDirective;
```
And verify that by OnAfterViewInit, there is a valid reference in the private field.

An example is here:

https://stackblitz.com/edit/angular-vxbpuk?file=src%2Fapp%2Fapp.component.ts

## 🌍  Your Environment

Angular 7.03

**Comment by RonanC** [comment]
Personally I would go with having all the decorators public, as this line is pretty strong:
> "Decorated component class members **must be public**. You cannot make an **@input()** property private or internal."

Compared to a simple code sample where they have a private `@ViewChild`.
It could very well be a mistake in the code sample.

If that is the case the Angular team should change it to public to avoid confusion.
Any update on this issue? Should be a fairly simple one to address?

**Comment by devversion** [comment]
This is related to https://github.com/angular/angular/issues/27760#issuecomment-449202842. Queries never had to be `public` like other class members which are accessed in component templates. This is because queries are not type-checked.

**Comment by ArslanWaqar** [comment]
Why has Angular team mentioned this in their docs?

AOT compilation complains when a private class member is used in template but doesn't complain when a Decorated function or class member is kept private.

Is this something which will be implemented/enforced in later or newer versions?
