### ISSUE TITLE
Getting duplicated items using Http Service

### ISSUE THREAD

**Issue by lnlwd** [angular/angular#2747]
Hey guys, I have a problem using http requests...

My code:

##### services/home.ts
```typescript
import {Http} from 'angular2/http';
export class HomeService {  
  list: Object;
  constructor(){
  }
  getAll(http: Http){
    http.get('/api/todo/')
      // Call map on the response observable to get the parsed people object
      .map(res => res.json())
      // Subscribe to the observable to get the parsed people object and attach it to the
      // component
      .subscribe(todo => this.list = todo);
  }
}
```
##### components/home.ts
```typescript
import {View, Component, NgFor} from 'angular2/angular2';
import {coreDirectives} from 'angular2/directives';
import {httpInjectables, Http} from 'angular2/http';
import {HomeService} from 'home/services/home';

@Component({
  selector: 'home',
  appInjector: [HomeService,httpInjectables]
})
@View({
  templateUrl:`modules/core/home/views/home.html`,
  directives: [coreDirectives, NgFor]
})
export class HomeComponent {
  homeService: HomeService;
  constructor(homeService: HomeService, http: Http) {
    this.homeService = homeService;
    homeService.getAll(http);
  }
}
```
##### home.html
```html
<h1>Todo List</h1>
<ul>
	<li *ng-for="#todo of homeService.list; #i = index">
	   {{i}} - {{ todo.name }} {{todo.checked}}
	</li>
</ul>
```
So, when I use `homeService.getAll(http);` in the Component, I get the list of items, but duplicated...

If I don't use this call, the list do not appear

What's the better way to do this correctly?

Thanks! :smile:

**Comment by jeffbcross** [comment]
Hey @lnlwd could you throw your complete app in a [plunker](plnkr.co) so I could take a look?

BTW, a more "side-effect-free" way to do this would be to let the HomeComponent subscribe to the observable, keeping no state in the service itself. That way, you could also hook into the component's `onDestroy` to cancel the subscription if the component is destroyed.

```typescript
getAll(http: Http){
    return http.get('/api/todo/')
      .map(res => res.json());
  }
...

export class HomeComponent {
  homeService: HomeService;
  homeServiceSubscription: any;
  constructor(homeService: HomeService, http: Http) {
    this.homeService = homeService;
    this.homeServiceSubscription = homeService.getAll(http).subscribe(todos => this.todos = todos);
  }

  onDestroy() {
    //Clean up subscription, abort XHR request
    this.homeServiceSubscription.dispose();
}
```

**Comment by lnlwd** [comment]
Hey @jeffbcross, i have changed my code looking your example and I get the same problem...

This application is available in this repo https://github.com/lnlwd/zyon

Thanks for helping!

**Comment by jeffbcross** [comment]
Hi @lnlwd, thanks for sharing the source, could you throw the app in a fully-working example on plunker or the like?

**Comment by lnlwd** [comment]
Ok... Here is: http://plnkr.co/edit/COjdftiCVLDCsx81iq2r

I used compiled JavaScript of my typescript files... All in this plunker... Thanks!

**Comment by gdi2290** [comment]
this might be a problem with ngFor
![screen shot 2015-06-26 at 7 39 13 pm](https://cloud.githubusercontent.com/assets/1016365/8390162/13796fa2-1c3b-11e5-8a03-f8412fb9f88d.png)

**Comment by mjw56** [comment]
Try removing coreDirectives from the View directives property and only using NgFor.

**Comment by lnlwd** [comment]
Ok, It works! I don't have thought about this `coreDirectives` call, many thanks!

**Comment by jeffbcross** [comment]
Good catch, @mjw56. Hmm, seems to me like framework should throw or at least no-op if the same directive is included twice. @lnlwd do you want to open another issue to this affect, with a simplified reduction on plunker? Closing this issue.

**Comment by lnlwd** [comment]
Yes @jeffbcross !! I will do this tomorrow because is 2:00 AM and i'm going to sleep...
