### ISSUE TITLE
view container can emptied before dispose is called on a dynamic component

### ISSUE THREAD

**Issue by rkirov** [angular/angular#2748]
https://github.com/angular/angular/blob/5a21dc534046004d8ed383bb93d7df39b70f982a/modules/angular2/src/core/compiler/dynamic_component_loader.ts#L75 needs an `index != -1` check.

**Comment by TedSander** [comment]
@rkirov @tbosch  This is still happening for me on the latests drop.

destroyViewInContainer is trying to remove something at index -1. We can reproduce it with Overlays when they try to be unloaded. I'll stop by to show you what is happening.
