### ISSUE TITLE
feat(docs-infra): add option to cache all docs (e.g. for offline access)

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#27492]
We are currently able to persistently [cache via the SW][1] any doc (guide, tutorial, API page, etc.) that a user visits.
We could utilize that to provide an option to cache all docs eagerly (so that they are available offline, load faster on first visit, etc.).

Currently it is possible to hack your way there by manually running [this code][2] (e.g. via DevTools or as a bookmarklet).

##
**Possible options:**
- A button "hidden" somewhere (e.g. in the footer).
- A separate page with some (minimal or not so minimal) UI and explanation of the implications.

##
**Considerations:**
- How to handle errors. E.g.:
  * Sometimes some file requests randomly fail. (Re-download? Just log?)
- There is currently no reliable way to undo this. Once all files are cached, they will continue to be re-fetched and cached every time there is a change.
   (Fortunately, only the files that _did_ change are fetched.)

[1]: https://github.com/angular/angular/blob/8973dd5a7e6ede6d29a98684255088afac294a81/aio/ngsw-config.json#L60-L70
[2]: https://twitter.com/gkalpakas/status/1065929759593562113

**Comment by thefliik** [comment]
Recently I've been running into this because of the California power outages. The ability to access the docs offline would be a useful feature.

**Comment by sonukapoor** [comment]
@gkalpak I will take a look at this one. Please assign to me.

**Comment by gkalpak** [comment]
Un-assigning @sonukapoor, since @ajitsinghkaler created a PR already.

##
<sub>@ajitsinghkaler, in the future please try to make sure an issue is not being worked on before picking it up. This way we can avoid stepping on each others toes and prevent duplication of effort :wink:
</sub>

**Comment by ajitsinghkaler** [comment]
Next time will ask permission before making some pull requests if it is assigned to someone else. Did it because @sonukapoor made that comment a month back. I thought he has no interest in this issue.

I will keep this in mind from now on. Sorry @sonukapoor if I overstepped my bounds.

**Comment by gkalpak** [comment]
No worries, @ajitsinghkaler! We love your and @sonukapoor's enthusiasm, so keep it up ❤️

<sub>
For context: I was holding back @sonukapoor, because I wanted to discuss this with the team first 😇
</sub>

**Comment by sonukapoor** [comment]
No worries @ajitsinghkaler.

**Comment by jessicajaniuk** [comment]
@gkalpak What happened with this issue? I see there's a commit in @ajitsinghkaler's fork, but it doesn't look like it made it into a PR.

**Comment by gkalpak** [comment]
There was a PR (#35251), but it was closed (as it needed more work).
This is not a trivial feature to add and is relatively low priority, so let's close it for now.
