### ISSUE TITLE
Animation on IOS chrome

### ISSUE THREAD

**Issue by omrirz** [angular/angular#27506]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/platform-browser/animations, i guess

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 4.1.2 (the last one i used and it worked)

### Description

on IOS Chrome the animations works fine but if you switch to another tab and goes back to the angular app then the animation is not smooth and has jumps.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ssjdcw

## 🌍  Your Environment
**Angular Version:**
<pre><code>

Angular CLI: 7.1.1
Node: 10.8.0
OS: darwin x64
Angular: 7.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.1
@angular-devkit/build-angular     0.11.1
@angular-devkit/build-optimizer   0.11.1
@angular-devkit/build-webpack     0.11.1
@angular-devkit/core              7.1.1
@angular-devkit/schematics        7.1.1
@ngtools/webpack                  7.1.1
@schematics/angular               7.1.1
@schematics/update                0.11.1
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

</code></pre>

**Anything else relevant?**

Yes, this happens on Chrome IOS and not Chrome desktop. other IOS browsers such as Firefox and Safari doesn't have this problem.

**Comment by simeyla** [comment]
iOS really likes to do 'secret clever things' to try to maximize performance. Sometimes this can be the reason you get 'jumps'.

I had an animation which faded out some buttons and then when you scrolled the window it was supposed to fade them in again, but it jumped from 0 to 100% opacity. This all using RxJS.

The only difference between the fading in and fading out was the event that was causing the animation, so I realized iOS must be preventing an animation as a direct result of `window.scroll`. 

I was able to fix this easily by adding `delay(0)` to the observable `fromEvent(window, 'scroll')`

**Comment by dario-piotrowicz** [comment]
> So anything IOS related uses CSS keyframes to push for the animations. Unfortunately this isn't well optimized by IOS and this causes lag when more resources are used by the OS.
> 
> The solution to use this to have Angular use transitions instead of keyframes. Up until recently this hasn't really been possible because transitions are severely limited. But with #26931 it kinda proved that this is possible using clever DOM hacks. I will talk with the team and see what we can do.

Hopefully we can drop the CSS keyframes animations (https://github.com/angular/angular/issues/44520), hopefully that could fix this issue too 🙂

**Comment by jessicajaniuk** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
