### ISSUE TITLE
BuildKite failure tracking

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#27508]
We've recently added the [BuildKite CI check ](https://github.com/angular/angular/pull/27205) and are now tracking how reliable it is, and how it fails.

So far the following failures have been observed:
- `Warning: Checkout failed` ([build log](https://buildkite.com/angular/angular/builds/97#49ffb1e8-0930-453d-ae7a-439437201014))
- `warning: failed to remove node_modules/...` followed by `Warning: Checkout failed!` ([build log 1](https://buildkite.com/angular/angular/builds/70#9fc8283b-7088-4aee-9582-53166c9a8d3d), [2](https://buildkite.com/angular/angular/builds/96#65a95d9f-7677-4d22-b794-d56b985463aa), [3](https://buildkite.com/angular/angular/builds/67#f8dc2fab-07e5-489e-8be4-f7a64d1099c9))
  - these two seems to happen when the buildkite scripts end up in a state where the folder is no longer a repository. Reported to BuildKite as https://github.com/buildkite/agent/issues/866.
- Bazels `yarn_install` fails ([build log 1](https://buildkite.com/angular/angular/builds/100#e9e5c732-0ac1-49d1-8e48-70218e2d1d68), [2](https://buildkite.com/angular/angular/builds/45#4da019bb-5176-4fdd-bcb6-84062fce7f87), [3](https://buildkite.com/angular/angular/builds/81#8f8c6b7d-acd8-4a9f-9010-e21e99a4d0f1))
  - this failure happens when running Bazel and is always preceded by `warning Waiting for the other yarn instance to finish (8340)`. Perhaps related to https://github.com/bazelbuild/rules_nodejs/pull/419. Warnings also seen in [circleci builds](https://circleci.com/gh/angular/angular/120474?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) but did not lead to failure there.
- `ENOSPC: no space left on device,` ([build log](https://buildkite.com/angular/angular/builds/48#8084e592-1c6a-4895-950e-009b780fb4ee)). 
  - ~~we have increased disk space on windows VMs (32GB to 192GB) to validate if this error is legitimate and was truly caused by lack of disk space.~~ Still seeing out of space errors ([build 120](https://buildkite.com/angular/angular/builds/120#4d7a787c-7e27-4d3b-8c73-45080eea9006) after we increased disk size, so it's likely not really a disk space thing.

There is two others identified failure mode that are expected and will not be investigated:
- Could not find a default pipeline configuration file. ([build log 1](https://buildkite.com/angular/angular/builds/85#3da718aa-feb8-49f8-a8a4-fffdedc3fc89), [2](https://buildkite.com/angular/angular/builds/92#2dee910c-0768-4468-bde6-816e62fb8848))
  - this happens when a PR that is not up to date with master fails to build because the buildkite configuration cannot be found. It s is expected and should go away in a couple of weeks as PRs become up to date.
- Canceled automatically ([build log](https://buildkite.com/angular/angular/builds/95#c2563d19-c6d7-4e68-b5a2-bbb189b91269))
  - Intermediate builds are cancelled as new commits arrive. This does not affect the master branch.

cc @alexeagle @IgorMinar

**Comment by IgorMinar** [comment]
another build that failed with out of space: https://buildkite.com/angular/angular/builds/120#4d7a787c-7e27-4d3b-8c73-45080eea9006

**Comment by filipesilva** [comment]
We've removed the github status reporting for BuildKite, which means it will still run but not report anything on PRs. Once it is more stable we will re-enable it.

**Comment by filipesilva** [comment]
Today I reprovisioned the VM with the following changes:
- new version of buildkite agent (might fix checkout errors https://github.com/buildkite/agent/issues/866#issuecomment-448058797)
- more RAM (GCE was giving warnings about the VM being at the memory limit, also updated doc https://github.com/angular/angular/pull/27728)

Briefly looked into [Docker for Windows "no space" errors](https://github.com/docker/for-win/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%22no+space%22) and found a couple of promising hits: https://github.com/docker/for-win/issues/1042, https://github.com/docker/for-win/issues/745, https://github.com/docker/for-win/issues/244. 

There seem to be a few situations where Docker for Windows keeps taking more and more disk space. cc @gkalpak

**Comment by filipesilva** [comment]
Checked the health of builds on master since the last comment:
- 24 total builds
- 5 of which were failures
  - 1 `Warning: Checkout failed`([1190](https://buildkite.com/angular/angular/builds/1190)), reported back on https://github.com/buildkite/agent/issues/866#issuecomment-450344291
  - 4 Bazel yarn_install timeouts ([1051](https://buildkite.com/angular/angular/builds/1051), [1189](https://buildkite.com/angular/angular/builds/1189), [1213](https://buildkite.com/angular/angular/builds/1213), [1301](https://buildkite.com/angular/angular/builds/1301))

The timeouts seem to be the worst ones. Normal green builds take around 8-13m, but the ones that have bazel yarn_install timeouts take 16-90m. @gkalpak also saw a green build that actually took 30m.

When the bazel yarn_install times out, it looks like the non-bazel `yarn install` also takes a while. Perhaps it's not really Bazel specific, but rather the connection from the CI machine to the yarn servers, or the yarn servers themselves.

I also checked the host VM disk space. It was started with 128GB and seems to still have 110GB free.

**Comment by filipesilva** [comment]
Another health check, for builds from the 28th December 2019 to 7 January 2019:
- 48 [builds on master](https://buildkite.com/angular/angular/builds?branch=master)
- of which there were 21 failures
  - 5 `Warning: Checkout failed!`: [1465](https://buildkite.com/angular/angular/builds/1465#a653fbad-6cc1-49c7-a3c5-62e23a967e6e), [1467](https://buildkite.com/angular/angular/builds/1467#90e86b9c-8f85-477a-bf63-6c56dbbe30da), [1512](https://buildkite.com/angular/angular/builds/1512#059ef5b7-7160-49f2-bbb4-42dfc2fa35f1), [1677](https://buildkite.com/angular/angular/builds/1677#6ea21072-358c-433b-8ca5-fc3e9dee0536), [1678](https://buildkite.com/angular/angular/builds/1678#7c332a7e-50e5-416b-a31e-87ca9b5cb8fc)
     - reported on https://github.com/buildkite/agent/issues/866.
  - 7 Bazel yarn_install timeouts: [1489](https://buildkite.com/angular/angular/builds/1489#072a0bcb-3587-41a8-8f3b-cb374fc2d007), [1570](https://buildkite.com/angular/angular/builds/1570#4230c53d-5c55-49fd-91e6-2bd55b0e2d59), [1583](https://buildkite.com/angular/angular/builds/1583#84aa9bd1-65ff-43e5-b625-e1cc2de5fb0f), [1592](https://buildkite.com/angular/angular/builds/1592#16b64bdb-318d-4b2b-ab05-d11a527e21ed), [1594](https://buildkite.com/angular/angular/builds/1594#d37855e4-14d9-4ade-9189-245a4ec54f26), [1603](https://buildkite.com/angular/angular/builds/1603#cbe76b44-6101-44c4-b6ca-f9ce2fec93be), [1604](https://buildkite.com/angular/angular/builds/1604#61ad0d2d-9845-4bba-9199-3101b8dce440)
      - should be addressed by https://github.com/bazelbuild/rules_nodejs/pull/485, available next release of rules_nodejs.
  - 9 `no such package '@remotejdk_win//': java.io.IOException: thread interrupted and referenced by '@bazel_tools//tools/jdk:remote_jdk'`: [1736](https://buildkite.com/angular/angular/builds/1736#07454ee2-f150-4f29-8daf-e8340914ca0c), [1737](https://buildkite.com/angular/angular/builds/1737#681d86e2-69f6-4320-993d-3a6bb73d47d3), [1765](https://buildkite.com/angular/angular/builds/1765#5e7eaaba-bf72-4e54-9768-77941ad71313), [1738](https://buildkite.com/angular/angular/builds/1738#1020c439-7517-4404-a4a9-7607b68fee85), [1741](https://buildkite.com/angular/angular/builds/1741#5b9d358b-6558-471e-b582-a2f6aa26f664), [1764](https://buildkite.com/angular/angular/builds/1764#69351c09-1527-423f-b31f-ce30ef4d0a1e), [1766](https://buildkite.com/angular/angular/builds/1766#ffba025e-f573-4470-91d5-b12894460f0d), [1796](https://buildkite.com/angular/angular/builds/1796#6247e072-a68e-4001-a6a1-0ed87907b237), [1769](https://buildkite.com/angular/angular/builds/1769#dfb29319-ecc8-4767-9bdb-e7fd178b248f)
      - New failure mode. 

The new failure is only present in, but very frequent for, builds in the last 24h. Intersped with successful builds so it's not just a broken master on windows. Those builds did not exhibit abnormally lengthy yarn install phases so it doesn't seem like it's a slow network.

Previous step is always the yarn install, which seems to finish installing packages and then process to update webdriver in a postinstall script. I don't think it's related to the postinstall because the error mentions `@bazel_tools//tools/jdk:remote_jdk` and the node postinstall does not know of bazel at all.

Seems to always happen around 2m 20s after the previous bazel log, which suggests a 120s timeout somewhere.

**Comment by filipesilva** [comment]
Regarding the `no such package '@remotejdk_win` error, @alexeagle highlights that https://github.com/angular/angular/commit/e7f43386a606bd4bfa960e69d43021ca57abbc90 was merged recently. These failures started happening 3 builds after that. Might be related. 

@meteorcloudy are you familiar with this error?

**Comment by laszlocsomor** [comment]
> @laszlocsomor mentioned it's worth it to try `--noincompatible_strict_action_env` to see if it's related, since that flag default changed in 0.21 and it seems to be causing unexpected trouble.

I want to clarify that this just a shot in the dark.

Also, here's the list of changed flags in 0.21: https://blog.bazel.build/2018/12/19/bazel-0.21.html
If upgrading from Bazel 0.20 to 0.21 is indeed the culprit of errors, then these flags should also be suspicious.

**Comment by meteorcloudy** [comment]
I have never seen this error before. @meisterT , do you have any idea what's causing this with 0.21?

**Comment by meteorcloudy** [comment]
I tried to directly build `@bazel_tools//tools/jdk:remote_jdk` with 0.21.0 on my machine, there's no problem.

**Comment by gkalpak** [comment]
Closing, since we are not using BuildKite any more.
