### ISSUE TITLE
aio: CLI docs and updates

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#27507]
## Matching CLI docs versions to Angular versions

**Current state:**

The `@angular/cli` docs built as part of angular.io, are extracted from the [cli-builds][cli-builds] repo, based on a hard-coded SHA in [aio/package.json][aio-pkg-sha].

We have to keep different SHAs on Angular `main` and stable branches, since the CLI docs major versions should match with Angular's major version. E.g. [cli-builds#main][cli-builds-main] (which is based on [angular-cli#main][cli-main]) should be used for building aio on [angular#main][ng-main] and [cli-builds#7.1.x][cli-builds-stable] (which is based on [angular-cli#7.1.x][cli-stable]) should be used for building aio on [angular#7.1.x][ng-stable].
<sub>It just so happens that the latest minor versions for both Angular and CLI are 7.1.x atm, but only the major versions are guaranteed to be aligned.</sub>

As a consequence, when we want to update the SHA used in one of Angular's branches, we need to submit a PR against that branch (and make sure PRs targeting `main` are not accidentally cherry-picked into stable).

The upside is that by submitting PRs against the targeted branch, the PR previews are created for and the tests run against that specific branch.

##
**Alternative plan:**

We can have the two different SHAs (one for `main` and one for the stable branch) in a config file that we keep in-sync between both branches.

As a consequence, the previews will be created for and the tests will be run against the `main` branch (using the corresponding SHA), which is not useful when updating the SHA for the stable branch. However, if the tests fail when cherry-picked to the stable branch, the broken version will not be deployed (it's just that we wouldn't be able to automatically catch the failures before merging the PR).

The upside is that the PRs updating one of the SHAs will always be submitted against `main` and always cherry-picked to the stable branch. There is no way to accidentally merge/cherry-pick a SHA to the wrong branch.

##
**Thoughts/Considerations:**

- With the current state, it is possible for a commit from `angular-cli#main` to end up in the docs for `angular#<stable>`, due to the different release cadence of the projects.
    (See, also, https://github.com/angular/angular/pull/27556#issuecomment-445455459.)
- With the alternative plan, it will be more complicated to determine which SHA to use (unless we have a reliable way to look it up; e.g. via `package.json#version`).
  We would need to decide which branch we are building the docs for, which can be [non-trivial][aio-deploy-script] (and possibly impossible when building on a local branch)?

---
## Automatic updates.

**Current state:**

In order to avoid having to manually update the SHA, there is [a script][upgrade-cli-src] that runs daily in a ~~TravisCI cron job~~ _cron-based GitHub Action_ (in [gkalpak/ngx-deps-upgrade][ngx-deps-upgrade]) and submits a PR if there are changes in the CLI docs.

The script checks the `main` branch, the RC branch (if any) and the stable branch. 

##
**Plan:**

- Move the script to [angular/angular][ng] and set it up to run in a CircleCI cron job (similar to [aio_monitoring][aio-monitoring-cfg]).
- Make the script run as a non-privileged user (e.g. @MaryPoppins). 
 
##
**Thoughts/Considerations:**

- The script requires a GitHub access token to retrieve data from GitHub and create branches/PRs. (The `public_repo` scope is needed for the latter).
  Make sure the token remains secure.
- (Not thought-out) Alternative 1: We could setup CircleCI to run on Mary Poppins' fork (e.g. pull the script from [angular/angular][ng] and run it), so only those with access to her fork would have access to the token.
  <sub>Who would have access to the logs (e.g. for debugging)?</sub>
- (Not thought-out) Alternative 2: We could re-purpose the preview server to do things like that. E.g. ping it from a CircleCI cron job and have it run the script locally.
  <sub>(We need to think more about security implications.)</sub>

[ng]: https://github.com/angular/angular
[ng-main]: https://github.com/angular/angular/tree/main
[ng-stable]: https://github.com/angular/angular/tree/7.1.x

[cli]: https://github.com/angular/angular-cli
[cli-main]: https://github.com/angular/angular-cli/tree/main
[cli-stable]: https://github.com/angular/angular-cli/tree/7.1.x

[cli-builds]: https://github.com/angular/cli-builds
[cli-builds-main]: https://github.com/angular/cli-builds/tree/main
[cli-builds-stable]: https://github.com/angular/cli-builds/tree/7.1.x

[aio-deploy-script]: https://github.com/angular/angular/blob/6740d0de74e3c399bd09254df579d6a3828fa7ee/aio/scripts/deploy-to-firebase.sh#L25-L62
[aio-monitoring-cfg]: https://github.com/angular/angular/blob/6740d0de74e3c399bd09254df579d6a3828fa7ee/.circleci/config.yml#L454-L463
[aio-pkg-sha]: https://github.com/angular/angular/blob/6740d0de74e3c399bd09254df579d6a3828fa7ee/aio/package.json#L21

[ngx-deps-upgrade]: https://github.com/gkalpak/ngx-deps-upgrade
[upgrade-cli-src]: https://github.com/gkalpak/ngx-deps-upgrade/blob/master/src/lib/aio/upgrade-cli-src.ts

**Comment by jenniferfell** [comment]
@jbogarthyde FYI

**Comment by IgorMinar** [comment]
If the circle job is triggered via timer then it runs as upstream build and not as a pr build which means that we could use the encrypted variables to make the github token available in a secure way.

Did you intentionally ommit the mention of ssh key needed for creating the pr branch? Can we use the token for that without the ssh key?

**Comment by gkalpak** [comment]
Yes, you can use the token for everything (as long as it has the `public_repo` scope).

**Comment by IgorMinar** [comment]
I discussed this with @alexeagle and he suggested that we use renovate for this instead of our own custom stuff. We should discuss this more before we settle on a solution.

Yet another option is to merge the angular and angular-cli repos into a monotree setup and have infrastructure to sync the two forks of the monotree.

**Comment by jelbourn** [comment]
@josephperrott is there anything still relevant here?

**Comment by gkalpak** [comment]
Yes, this is still relevant. (Whether we'll ever get to prioritize it, is a different discussion 😛)
