### ISSUE TITLE
How to load the ng-template in separate file?

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular#27503]
# 🐞 bug report

### Affected Package
not able use ng-template in seperate file

### Description

In below sample, i have used ng-template like below and it is working fine

**sample:** https://stackblitz.com/edit/angular-mdksym-bihcup?file=default.html 

But I want to create a new file for ng-template content and I want to use it in another file. I have tried like below but not working. Please help me find a solution for this case.

> template.html

`<ng-template #template let-dataSource="">
  <span *ngIf="dataSource.iconCss" class="e-menu-icon {{dataSource.iconCss}}"></span>
  {{dataSource.header}} {{dataSource.text}}
  <span *ngIf="dataSource.templateHeader" class="e-login-content">
    <button ejs-button cssClass="e-info">Sign In</button>
  </span>
</ng-template>`

> default.html
`<div class="control-section">
  <ejs-menu #menu [items]='dataSource' [fields]='menuFields'>
    <ng-container *ngTemplateOutlet="template;"></ng-container>
  </ejs-menu>
</div>`

## 🔬 Minimal Reproduction

not working sample link: https://stackblitz.com/edit/angular-mdksym-r76qei?file=template.html

## 🌍  Your Environment

**Angular Version:**
    "@angular/cli": "~6.1.1",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",

**Anything else relevant?**

**Comment by kumaresan-subramani** [comment]
I have posted same question in stackblitz. please check this link:  https://stackoverflow.com/questions/53645174/how-to-load-the-ng-template-in-separate-file

**Comment by kumaresan-subramani** [comment]
Hi ,
Please update to me.

**Comment by dawidgarus** [comment]
You cannot have just template in separate file. Template must be defined as a part of component. You can create a wrapper component with template definition inside, then you can reference template like this:
```html
<ng-container *ngTemplateOutlet="templates.template"></ng-container>
<my-templates #templates></my-template>
```

**Comment by kumaresan-subramani** [comment]
still not able to achieve my requirement:  https://stackblitz.com/edit/angular-mdksym-r76qei?file=template.html

but if i use like this it is working fine:  https://stackblitz.com/edit/angular-mdksym-bihcup?file=default.html

**Comment by dawidgarus** [comment]
You probably want something like this: https://stackblitz.com/edit/angular-mdksym-kmeewq?file=default.html

**Comment by alxhub** [comment]
Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: 
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Thank you!

**Comment by kumaresan-subramani** [comment]
Hi @dawidgarus ,
Thank you for your support, thank you so much
