### ISSUE TITLE
Baseline benchmark running full benchmark samples on Travis

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2751]
See the benchmark run in Firefox as a full sample, rather than as an e2e spec: https://travis-ci.org/angular/angular/jobs/68390758#L572

Introduced by: https://github.com/angular/angular/commit/0949a4b045a6729008d34b06257c2134e6548eee

CC: @tbosch @hankduan

**Comment by hankduan** [comment]
Do you mean run it like chrome is running? That can't be done until this is resolved: https://github.com/angular/angular/issues/2726

**Comment by tbosch** [comment]
Yes, this is true. We probably should change the sample benchmark to use the settings from [here](https://github.com/angular/angular/blob/master/protractor-shared.js#L243-L244) so that it only uses 1 iteration.

**Comment by tbosch** [comment]
No more applicable.
