### ISSUE TITLE
angular post requests error

### ISSUE THREAD

**Issue by yogender1995** [angular/angular#27518]
Access to XMLHttpRequest at 'http://localhost/ci/api/heros/update_hero' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

please help me..
i have also added headers:
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: X-Requested-With, Content-Type, Accept, Origin');
header('Access-Control-Allow-Methods','GET, POST, PUT, DELETE, OPTIONS');

but it still showing this cors  policy error

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
