### ISSUE TITLE
Directive not activated when component lazy loaded

### ISSUE THREAD

**Issue by rajeev-john** [angular/angular#27517]
Hi,
     I am having an issue of directive not triggering when the attached component is lazy loaded. 

# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Description

      Please see below the sample

`@Directive({
  selector: 'my-directive'
})`
     The above directive is part of a module `MyDirectiveModule`

`@Component({
  selector: 'my-directive',
  templateUrl: './my-directive.component.html'
})`
    The component selector is set to same as that of the directive to match the element name. The above component is part of a module `MyDirectiveComponentModule`. Also i have imported `MyDirectiveModule` in `MyDirectiveComponentModule`.

The issue that is currently faced is that, when `MyDirectiveComponentModule` is loaded to `<router-outlet></router-outlet>` via lazy loading the corresponding directive is not getting triggered. I tried adding the directive module to `AppModule` as well based on some google results but not luck. I am not sure if I am doing something wrong or is it the expected behavior. Appreciate your help and Thanks in advance.

### Is this a regression?
Have faced the same issue with with Angular 7.0 & 7.1. Not sure about the previous versions.

## 🌍  Your Environment
**Angular Version:**
<pre><code>

Angular CLI: 7.1.1
Node: 10.14.1
OS: win32 x64
Angular: 7.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.3
@angular-devkit/build-angular     0.10.3
@angular-devkit/build-optimizer   0.10.3
@angular-devkit/build-webpack     0.10.3
@angular-devkit/core              7.0.3
@angular-devkit/schematics        7.1.1
@ngtools/webpack                  7.0.3
@schematics/angular               7.1.1
@schematics/update                0.11.1
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
</code></pre>

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by mlc-mlapis** [comment]
@rajeev-john ... so you have something like `{path: 'demo', loadChildren: './modules/demo/demo.module#DemoModule'},` in the main routing and in the routing of that lazy loaded module you have `{path: '', component: DemoComponent}` and you suppose that **DemoComponent** will be instantiated in `<router-outlet></router-outlet>` together with the directive of the same selector?

**Comment by rajeev-john** [comment]
@mlc-mlapis yes what ever you have said is the given setup. As of now the component is loaded successfully in <router-outlet></router-outlet> but the expected output of the directive not happening. But the directive is working when the component is not loaded lazy.

**Comment by mlc-mlapis** [comment]
@rajeev-john ... and when the module is not lazy loaded ... you mean the component instantiation just again via router ... like `{path: 'any', component: AnyComponent}` or via template like:
```
...
<any-component>...</any-component>
```

**Comment by rajeev-john** [comment]
@mlc-mlapis Via template like what you mentioned.

**Comment by mlc-mlapis** [comment]
@rajeev-john ... ahh, but then it's totally different situation ... so you can't say:

> But the directive is working when the component is not loaded lazy.

because you are using a different way how to instantiate that component. You should try what happens when you'll instantiate it via a route, like: `{path: 'any', component: AnyComponent}`

**Comment by ChrisDahmCS** [comment]
@rajeev-john can you please provide a [StackBlitz](https://stackblitz.com/) replicating the issue?

**Comment by alxhub** [comment]
This is not supported in Angular - directives are only matched on compiled templates, not when dynamically rendering a component.
