### ISSUE TITLE
Custom Form Component - CSS Classes

### ISSUE THREAD

**Issue by juanpmarengo** [angular/angular#27513]
I got a custom form component and I want to subscribe to the classes that are applied to the host.

I tried with:

```
@HostBinding('attr.class')
@Input() class: string;
```

With this approach I could only get the initial class, but this component uses the validator **required** that attaches the classes _.ng-valid_ or _.ng-invalid_ dynamically.

Is there a way to bind to those class changes?

**Comment by dawidgarus** [comment]
That's not how input works. `@Input` doesn't watch for changes in attribute. Use `MutationObserver` if you wan't to watch for changes in attributes.
Or, you are are interested specifically in control state and whether it's valid or invalid, you may wan't to inject `NgControl` and subscribe to `statusChanges`

**Comment by juanpmarengo** [comment]
I want to have the host classes at anytime, binded in a variable as other @Input s.

**Comment by dawidgarus** [comment]
You can inject `ElementRef` and access host classes directly: `elementRef.nativeElement.className`

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
