### ISSUE TITLE
Inconsistency in how providers are referred to

### ISSUE THREAD

**Issue by AnthonyPAlicea** [angular/angular#27520]
# 📚 Docs bug report

### Description

When answering the question 'what is a provider' there is a bit of an inconsistency in the docs. The glossary definition is "an object that implements one of the Provider interfaces" and, for example, a ClassProvider's interface is:

```
interface ClassProvider extends ClassSansProvider {
  provide: any
  multi?: boolean
}
```

This is consistent with several other places in the documentation where a provider is referred to as the object used to configure the injector.

This would all suggest the answer to the question "show me what a provider looks like" would be:

`{ provide: Logger, useClass: Logger }`

However the page Dependency Injection -> Angular Dependency Injection states: "A provider can be the service class itself, so that the injector can use new to create an instance." This statement suggests the provider is the _class itself_, not the configuration object.

This is exacerbated by many sources online referring to an Angular provider and service as essentially the same thing.

Personally I find stating that a provider is the configuration object that is passed to the injector makes explaining DI much easier (i.e. the provider provides the information the injector needs to know).

If that is the correct answer, then perhaps documentation should say something to the effect: "The service class itself can be specified in the provider object, so that the injector can use new to create an instance."

Or perhaps I am incorrect in my reading of the documentation.

### What's the affected URL?**
https://angular.io/guide/dependency-injection

**Comment by AnthonyPAlicea** [comment]
Perhaps a better alternative: "The service class itself can be specified as the provider object, which is automatically expanded into a simple provider configuration object. The injector can then use new to create a new instance." This would be in keeping with the description in the Dependency Injection -> DI Providers page and the glossary https://angular.io/guide/glossary#provider.

**Comment by ajitsinghkaler** [comment]
@gkalpak @kapunahelewong I think this has been corrected please have alook

**Comment by kapunahelewong** [comment]
I really like your examination of the definition, @AnthonyPAlicea. I'll close this issue as the glossary has been updated since you filed this. If you feel it's still in need of more clarity, please feel free to re-open and tag me. Thank you!!
