### ISSUE TITLE
Adding .text() or .selectedOption or .selected.text feature to angular reactive form control drop down list to get the text instead of the value when needed

### ISSUE THREAD

**Issue by alim90** [angular/angular#27534]
### Relevant Package

@angular/forms

### Description

Adding a new feature to reactive form controls to get the text of a selected option in drop down list instead of its value.

In vanilla javascript, we used to work with `innerText` or with jQuery using `.text()`, but in angular, the only way is by: `this.formGroup.get('control').value`. And sometimes we need the text not the value of it.

### Describe the solution you'd like
The solution would be like adding a `.text()` or `.text` to get the selected text value of a reactive form control, so it would be something like, it `<FormControl>` is a drop list normal html `<select>` or even `<mat-select>` for angular material:

`this.formGroup.get('control').selected.text`

Or

`this.formGroup.get('control').text`

### Describe alternatives you've considered
Currently, we add a click event for each `<mat-option>` or `<option>` to return the text value on click.
Here is a [stackblitz](https://stackblitz.com/edit/angular-material-w89kwc?embed=1&file=app/app.component.ts).

**Comment by eklavyalodha** [comment]
> ### Relevant Package
> @angular/forms
> 
> ### Description
> Adding a new feature to reactive form controls to get the text of a selected option in drop down list instead of its value.
> 
> In vanilla javascript, we used to work with `innerText` or with jQuery using `.text()`, but in angular, the only way is by: `this.formGroup.get('control').value`. And sometimes we need the text not the value of it.
> 
> ### Describe the solution you'd like
> The solution would be like adding a `.text()` or `.text` to get the selected text value of a reactive form control, so it would be something like, it `<FormControl>` is a drop list normal html `<select>` or even `<mat-select>` for angular material:
> 
> `this.formGroup.get('control').selected.text`
> 
> Or
> 
> `this.formGroup.get('control').text`
> 
> ### Describe alternatives you've considered
> Currently, we add a click event for each `<mat-option>` or `<option>` to return the text value on click.
> Here is a [stackblitz](https://stackblitz.com/edit/angular-material-w89kwc?embed=1&file=app/app.component.ts).

This feature is required.

**Comment by dylhunn** [comment]
Thanks for your feature request! As it doesn't have many community upvotes, and a workaround exists, it is not currently a candidate for prioritization.
