### ISSUE TITLE
清除定时器

### ISSUE THREAD

**Issue by lfzx** [angular/angular#27530]
![image](https://user-images.githubusercontent.com/34572392/49626914-f7e4ed80-fa16-11e8-879a-42d91268c260.png)
查看网上资料后，发现都是销毁组件时才会清除定时器，而只是点击另一个页面，没有关闭该组件时，这个循环定时器还在执行，这肯定是不行的，会影响系统的性能。如第2张图片中所示，定时器1开启，我点击定时器2后，定时器1还在运行，必须把定时器1关闭后，循环定时器才会停止。请问有没有方法可以不销毁组件，定时器也能被清除？
![image](https://user-images.githubusercontent.com/34572392/49627070-b7d23a80-fa17-11e8-9a8d-a06502782fa0.png)

**Comment by alexzuza** [comment]
I would say it doesn't fall into the bug report or feature request category. You have to manage that timer by yourself if you don't destroy component.

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag angular(and in English please).
