### ISSUE TITLE
4.0.0-beta.17: navigating with location.back() causes error run outside of angular zone

### ISSUE THREAD

**Issue by askona** [angular/angular#27540]
# 🐞 bug report

### Affected Package
"@angular/common": "~7.0.3",
"@angular/core": "~7.0.3",
"@angular/router": "~7.0.3",

### Is this a regression?

After updating from 4.0.0-beta.16 to beta17, i got issue

### Description

When navigating with {Location} from '@angular/common'
location.back();
and going to other tabs (i have tab based application), i got empty pages, and warning
Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?

## 🔬 Minimal Reproduction

1. Create tab-based app
2. Choose any tab, and navigate on pages using location.back()
3. Click on any other tab ====>
4. Got message about outside angular zone and see that page content is empty

## 🔥 Exception or Error
<pre><code>
Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?

</code></pre>

## 🌍  Your Environment

"@angular/common": "~7.0.3",
"@angular/core": "~7.0.3",
"@angular/router": "~7.0.3",
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by ocombe** [comment]
Are you on `7.0.3` or `4.0.0 beta 16`?!
If you're still on v4, we do not support this version anymore as you can see on the support policy: https://angular.io/guide/releases#support-policy-and-schedule

**Comment by alxhub** [comment]
Hello @askona, thank you for the regression report. Unfortunately we cannot investigate the issue as reported due to a lack of details. Can you please include a reproduction of the regression using Stackblitz or as a standalone Github repo using the CLI?

Thanks,
Alex

**Comment by askona** [comment]
Sorry, that issue was for Ionic, not for angular, i missed the repo
