### ISSUE TITLE
Errors in ts_library are not breaking builds

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#27569]
When using `ts_library` and introducing a code errors, the build will not fail.

This is reproduced by @IgorMinar in https://github.com/angular/angular/pull/27558. 

@petebacondarwin suggests this behaviour is due to `"noEmitOnError": False,` in https://github.com/bazelbuild/rules_typescript/blob/0153b82e50b6dc84887754649e95292fd4689b98/internal/common/tsconfig.bzl#L242. When changing that value to `True`, the build will fail correctly.

@alexeagle seems to have identified this questionable value in https://github.com/bazelbuild/rules_typescript/blob/552822bddd6a0406ce4ebecfa0604f23b8566542/internal/tsc_wrapped/tsconfig.ts#L224.

**Comment by alexeagle** [comment]
Haha, oops - https://github.com/bazelbuild/rules_typescript/commit/6b3ce2af98db257a4377afcc1ea9f45fa7783a4d introduced a helper method `gatherDiagnostics` but it is never called, so we stopped doing type-checking altogether 😱

**Comment by alexeagle** [comment]
Gah none of the tests in internal/tsc_wrapped are getting run either!
