### ISSUE TITLE
Bug on Directives

### ISSUE THREAD

**Issue by lnlwd** [angular/angular#2756]
Hello!
On directives I have detected the following problem:

If you include `coreDirectives` and `NgFor` in the same component, the ng-for instruction will be executed two times.

Example in this plunker: http://plnkr.co/edit/tFGJVjO3z78GEXCTKFh4?p=preview

I think the framework need report an error with this info or render only one time the ng-for...

Thanks and sorry my bad english :smile:

**Comment by pkozlowski-opensource** [comment]
Right, we are aware of this, see #2568. 

@tbosch would you have any pointers as where would be the best place of fixing this one. I had a quick look at the code and the fact that directives can be both a type and a binding makes things slightly more complex - that it - we need to wait with duplicate removal till bindings are resolved and I'm not sure where to stick this logic...

**Comment by lnlwd** [comment]
Ok Thanks!
