### ISSUE TITLE
If else missing

### ISSUE THREAD

**Issue by rajinder-yadav** [angular/angular#27564]
If else is missing from docs: https://angular.io/guide/structural-directives#ngif-case-study

**Comment by jotatoledo** [comment]
Not really, see https://angular.io/api/common/NgIf

**Comment by gkalpak** [comment]
It is mentioned in the API docs for `NgIf`, but not the guide on structural directives (including `NgIf`).
There should be a mention in the guide or at least the guide should explicitly point to the API docs for more advanced features/usecases.

**Comment by bradtaniguchi** [comment]
Under the first example for "What are structural Directives?" there's this line:

> This guide won't repeat how to use them. But it does explain how they work and how to write your own structural directive.

**Comment by jenniferfell** [comment]
@rajinder-yadav  Does the update to https://angular.io/api/common/NgIf in this PR resolve this issue 
https://github.com/angular/angular/pull/27376

**Comment by jenniferfell** [comment]
@rajinder-yadav @gkalpak I've mentioned this thread on a related PR https://github.com/angular/angular/pull/27273

**Comment by kapunahelewong** [comment]
Hi @rajinder-yadav, since #27273 was merged, thereʻs some new info in the docs about `ngIf`. Do these resolve your concern?

The doc: https://angular.io/guide/template-syntax#ngif
Stackblitz: https://stackblitz.com/angular/maegbyebkjn <--scroll down to the `ngIf` section.

**Comment by ajitsinghkaler** [comment]
@gkalpak @kapunahelewong I think we can close this issue.
