### ISSUE TITLE
Hosting an angular library outside the application module

### ISSUE THREAD

**Issue by djflex68** [angular/angular#27573]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI: 7.1.2
Node: 8.11.3
OS: win32 x64

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.11.2
@angular-devkit/core         7.1.2
@angular-devkit/schematics   7.1.2
@schematics/angular          7.1.2
@schematics/update           0.11.2
rxjs                         6.3.3
typescript                   3.1.6

### Repro steps
ng generate library "mylib"

### Desired functionality
Hi,

I want to create Angular libraries, while having the "container" app living in another "npm" module. I need to do this for module sharing purposes, for clear module separation concerns and because our app is already organized in that way.
This is the target architecture I'm trying to achieve : 
-> myApp (NPM module)
     ----> angular.json
     ----> src
     ----> package.json
-> myLib1 (another NPM module, not living inside myApp)
      ----> src
               ----> some .ts files
      ----> dist
      ----> package.json
-> myLib2 (yet another NPM module not living inside myApp)
     ----> src
              ----> some .ts files
     ----> dist
     ----> package.json

I cannot achieve this result by using CLI options or by setting "newProjectRoot" parameter to ".. " in myApp/angular.json for example.
I would like to avoid re-creating **for each library** an empty "app" container, that embeds a "projects" folder, itself contains a "library" folder, itself containing an "src" folder...
Since I'm using Yarn, I have a root-level "nodes_modules" folder containing symlinks pointing to myLib1 and myLib2, so I do not need to have everything "installed" in the same folder.

Do you see a solution with actual CLI tools for :
- having the bootstrapping app in one module
- having the library folder in another module, not inside the app
- avoiding recreating a folder scaffolding in each library ?

Thanks in advance ;)

**Comment by alxhub** [comment]
Please file any Angular CLI issues at: https://github.com/angular/angular-cli/issues/new

For the time being, we keep Angular CLI issues in a separate repository.
