### ISSUE TITLE
ENOENT and EPERM  no such file or directory in create new angular app

### ISSUE THREAD

**Issue by michaeldoss21** [angular/angular#27571]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please file any Angular CLI iss
![issue2](https://user-images.githubusercontent.com/45739271/49732780-b6b63d00-fca5-11e8-82bf-3f3c7579dcfa.png)
![issue3](https://user-images.githubusercontent.com/45739271/49732781-b6b63d00-fca5-11e8-834a-316b2703455d.png)

ues at: https://github.com/angular/angular-cli/issues/new

For the time being, we keep Angular CLI issues in a separate repository.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Please open angular-cli issues in its repo just like the template suggested you...
