### ISSUE TITLE
Provide some examples on Authentication and Authorization

### ISSUE THREAD

**Issue by bond-** [angular/angular#27579]
# 📚 Docs or angular.io bug report
FYI, I've looked at #1067 and #1403. I feel that providing these examples would increase adoption of Angular.

There are tons of examples which cite using localStorage for implementing authentication and then there are examples which say that localStorage shouldn't be used and should be encrypted in a Cookie.

I haven't really bumped in to good Roles/Role Hierarchy/Authorization yet. I am coming from a traditional webapp development perspective with Java, Spring Boot, Spring Security. I've developed some AngularJS apps but implementing Authentication and Authorization in latest Angular is consuming significant amount of time.

Although this seems trivial but adding those example would essentially improve adoption of Angular. A significant amount of Apps require this.

**Comment by bond-** [comment]
@alxhub or @jenniferfell Is there a possibility to prioritize this issue?

**Comment by atscott** [comment]
This is a great opportunity for the community to provide content around this but as far as a tutorial on the angular.io site goes, we feel that this is outside the realm of needed documentation for the Angular framework. The topic itself is tremendously far reaching. We provide some basic ideas for these kinds of workflows such as using guards in the router tutorial. Beyond that, a more in-depth guide for domain-specific needs should be provided elsewhere.
