### ISSUE TITLE
I update angular cli latest version & error found 

### ISSUE THREAD

**Issue by souravsg** [angular/angular#27570]
Hi,

When i update angular cli in latest version then i found below error...
Code used:
```
npm un -g @angular/cli
npm cache clean --force
npm i -g @angular/cli@latest
```

**npm ERR! Unexpected end of JSON input while parsing near '....31.tgz"}},"2.9.32":{"'
npm ERR! A complete log of this run can be found in:
npm Err!   C:\Users\....\Appdata\Roaming\npm-cache\_logs\2018-12-10T09_26_39_871Z-debug.log**

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by gkalpak** [comment]
In addition to what @ericmartinezr said, this sounds like an temporary npm or network error.
In any case, it is not related to Angular or Angular CLI.
