### ISSUE TITLE
Doc error - Observe geolocation updates

### ISSUE THREAD

**Issue by fatalcaron** [angular/angular#27597]
# 📚 Docs or angular.io bug report

### Description

 I try your example of geolocation updates via Observables and I got an error.

### What's the affected URL?**
 https://angular.io/guide/observables

### Reproduction Steps**

 Copy paste your example in a new Angular project and run

## 🔥 Exception or Error
<pre>ERROR TypeError: Cannot read property 'isStopped' of null<code>

</code></pre>

## 🌍  Your Environment
Angular 7.0.0
Rxjs 6.3.0

### Anything else relevant?

Replace the callback and it work...
<code>const { next, error } = observer;</code>
By:
<code>
const onSuccess: PositionCallback = (pos: Position) => {
   observer.next(pos);
 };

 const onError: PositionErrorCallback = (error) => {
   observer.error(error);
 };
</code>

**Comment by ericmartinezr** [comment]
See if this PR fixes it https://github.com/angular/angular/pull/27260

**Comment by fatalcaron** [comment]
Quick like a lightning!!! 
Thanks

**Comment by fatalcaron** [comment]
I spoke too fast, the PR does not solve the problem

**Comment by dariobraun** [comment]
Any idea how to fix this?

**Comment by fatalcaron** [comment]
@dariobraun Try this:

```
createWatchPosition(options?: PositionOptions): Observable<Position> {
  return new Observable((observer) => {
    // Get the next and error callbacks. These will be passed in when
    // the consumer subscribes.
    let watchId;

    const onSuccess: PositionCallback = (pos: Position) => {
      observer.next(pos);
    };

    const onError: PositionErrorCallback | any = (error) => {
      observer.error(error);
    };

    // Simple geolocation API check provides values to publish
    if (this.hasGeolocation) {
      watchId = navigator.geolocation.watchPosition(onSuccess, onError, options);
    } else {
      onError('Geolocation not available');
    }

    // When the consumer unsubscribes, clean up data ready for next subscription.
    return { unsubscribe() { navigator.geolocation.clearWatch(watchId); } };
  });
}
```

**Comment by rockument69** [comment]
This was fixed by PR [34705](https://github.com/angular/angular/pull/34705). I am therefore closing this issue.
