### ISSUE TITLE
Array Issues

### ISSUE THREAD

**Issue by sunny1610** [angular/angular#27599]
I have two arrays of same type in ts page and they are having different objects.
When I update particular value on  an index in one array ,if that object exists in second array that value also gets updated in second array.
Please suggest

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
