### ISSUE TITLE
Event when Style is added to DOM

### ISSUE THREAD

**Issue by habibialkaff** [angular/angular#27606]
# 🚀 feature request
Event Listener or Lifecycle Hook when Style is added to Host
### Relevant Package

 This feature request is for @angular/platform-browser

### Description

I'm using CSS Variables in my Website because some css properties can be unique for each user session. However, IE11 doesn't support it. So I have a polyfill that manipulates the style string by replacing the css variables with the correct value.
Since This can only be done when the component is rendered, I need to know when Angular adds the style to DOM
It seems that the style is added in DomSharedStylesHost._addStylesToHost

### Describe the solution you'd like
 
Possibly something that I can subscribe in the Dom during ngOnInit, or a new Lifecycle Hook

### Describe alternatives you've considered
 
Current workaround is to have the style not encapsulated within a component. So all styles are bundled as separate css files. They are then referenced manually as  "link"  tag, which I can then apply the polyfill when the page is loaded
But this is not a nice workaround because I'm losing the capability of style encapsulation in each component.

**Comment by alxhub** [comment]
I don't think we want to expose Angular's management of styles as a public API, unfortunately.
