### ISSUE TITLE
Console warn if global Zone.js is not loaded onto the page

### ISSUE THREAD

**Issue by mjw56** [angular/angular#2761]
I ran into this issue recently. I spent a good amount of time trying to find the cause for why my data was not updating on the UI only to realize that I had not imported Zone.js.

I'm wondering if it makes sense to warn the developer in this scenario?

```js
if (global.zone) {
  this._disabled = false;
  this._mountZone = global.zone;
  this._innerZone = this._createInnerZone(this._mountZone, enableLongStackTrace)
} else {
  console.warn('Could not find Zone.js loaded onto the page. Are you sure you\'ve imported it?')
  this._disabled = true;
  this._mountZone = null;
}
```

**Comment by vicb** [comment]
dup of #2683

**Comment by vicb** [comment]
- We probably want to throw if zone has not been installed (instead of only logging a warning),
- We should also throw if zone don't have support for microtasks (ie zone.js has been loaded instead of zone-microtask.js) The condition should be `!global.zone.scheduleMicrotask`
