### ISSUE TITLE
Confirmation event to child component from parent component

### ISSUE THREAD

**Issue by veereshradder** [angular/angular#27617]
Hi Folks, First of all, I am sorry to post support question here.
I posted this in SO but no response yet, or my question itself might be wrong please let me know anything on this.

**Context:**
Working on generic data table with inline edit feature.

**Components:**
component - data-table.component.(ts|html|css)

**Process:**
- This is a generic data table, can be used just by passing columns and rows to display. 
- It has inline edit feature for some of the cells
- On edit complete, an event will be sent to feature component(parent).
- Business logic to handle save data is up to the feature component(parent).

**Question:**
**- Save is an async process, on complete of save, how can I send confirmation response back to data table component if the save was success or fail ?**

Thanks

**Comment by dawidgarus** [comment]
I suggest passing `PartialObserver` as value in your data-table's output:
```html
<data-table (edit)="onEdit($event.value, $event.response)">
```
```typescript
onEdit(value: any, response: PartialObserver<any>): void {
 doSomethingAsyncWithValueAndReturnObservable(value).subscribe(response);
}
```
