### ISSUE TITLE
Angular Animations translateY on Chrome on iPhone finishes early

### ISSUE THREAD

**Issue by ReallyNotARussianSpy** [angular/angular#27629]
# 🐞 bug report

### Affected Package
 
 The issue is caused by package @angular/animations

### Is this a regression?

 No

### Description

 I have a scroll animation in my app which uses translateY to translate the body to the next question in a list after the previous question is answered. This behavior is working fine on desktop on all browsers, and in mobile in Safari. However, for certain iPhone's on Chrome the transition finishes in under 100ms when it is supposed to finish in 700ms, causing a noticeable skip. I was able to reproduce the issue in Chrome on an iPhone 6, 6S and XR. However, an iPhone 8 did not have the problem.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-reqqdv

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.1.2
Node: 8.11.2
OS: linux x64
Angular: 7.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.2
@angular-devkit/build-angular     0.11.2
@angular-devkit/build-optimizer   0.11.2
@angular-devkit/build-webpack     0.11.2
@angular-devkit/core              7.1.2
@angular-devkit/schematics        7.1.2
@angular/cdk                      7.1.1
@angular/cli                      7.1.2
@angular/material                 7.1.1
@ngtools/webpack                  7.1.2
@schematics/angular               7.1.2
@schematics/update                0.11.2
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.27.1

</code></pre>

**Anything else relevant?**
iPhone 6, 6S and XR reproduce the issue in Chrome. It always works in Safari. iPhone 8 in Chrome works.

Screen recordings showing the issue:

iPhone XR - Safari (Working): https://youtu.be/fM6-hh_L1_Y

iPhone XR - Chrome (Broken): https://youtu.be/d_WblMfK3nc

iPhone 6 - Chrome (Broken): https://youtu.be/WT6cHR-ZhlI

iPhone 6S - Chrome (Broken): https://youtu.be/kqvE2zqf4wc

iPhone 8 - Chrome (Working): https://youtu.be/h9oP8Jc0Ix4

Desktop - Chrome (MacBook Pro, Working): https://youtu.be/j93sqSXjIMI

**Comment by atscott** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
