### ISSUE TITLE
Wildcard ** route is not working with Lazy loading modules in Angular 6

### ISSUE THREAD

**Issue by vikrantsahoo** [angular/angular#27632]
I am using angular 6 ("@angular/core": "6.0.7") and using lazy loading it working fine with all my provided types but when I am using wildcard route to load my module its NOT loading anything.
I didn't find any solution. Does angular support lazy loading with wildcard route?

My **AppRoutingModule** Sample code

```ts
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { ErrorHandlerComponent } from './error-handler/error-handler.component';

const routes: Routes = [
  {
    path: '', component: ErrorHandlerComponent
  },
  {
    path: 'LIVE',
    loadChildren: './livestock-policy/livestock-policy.module#LivestockPolicyModule'
  },
  {
    path: 'HALL',
    loadChildren: './hail-policy/hail-policy.module#HailPolicyModule'
  },
  {
    path: 'CPMP',
    loadChildren: './mpci-policy/mpci-policy.module#MpciPolicyModule'
  },
  {
    path: '**',  // this is not working
    loadChildren: './np-policy/np-policy.module#NpPolicyModule'
  } 
];

@NgModule({
  imports: [RouterModule.forRoot(routes, { enableTracing: true })],
  exports: [RouterModule]
})
export class AppRoutingModule {
}
```

**Comment by benlesh** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
