### ISSUE TITLE
Angular 5/6 Critical Performance issues with Server Side Rendering (SEO Support)

### ISSUE THREAD

**Issue by engrzrg** [angular/angular#27640]
We’re facing problems with Angular 5/6 and need to implement server-side rendering to support Search Engine Optimization (SEO).  As Google Crawler not able to resolve the Angular Tags, so only options we have is server-side rendering.
Technically, its working fine but after implementation, performance is downgraded considerably, page load time is taking 8-12s. Ideally, we need 3-5 seconds for any standard benchmark.

We have followed the instruction detail for universal server rendering feature: 
https://stackoverflow.com/questions/46096282/how-to-deploy-angular-to-production-server-using-angular-cli-and-its-new-univers

We also tried use the ng-toolkit approach by followed these links: https://medium.com/@maciejtreder/angular-server-side-rendering-with-ng-toolkit-universal-c08479ca688
 https://medium.com/@maciejtreder/angular-serverless-a713e86ea07a.

Can someone please help us about he best practices for Angular 5/6 supporting SEO with load time 2-3 seconds.

**Comment by alxhub** [comment]
Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Thank you!
