### ISSUE TITLE
 rxjs6 - TypeError: Cannot read property 'pipe' of undefined

### ISSUE THREAD

**Issue by Anilpandiya** [angular/angular#27648]
After migrating from RxJs 5 beta version to RxJs 6 getting below error -

ERROR TypeError: Cannot read property 'pipe' of undefined at Object.get [as selectedTimecard]

<img width="516" alt="error" src="https://user-images.githubusercontent.com/13769938/49936051-dabd8c80-fef8-11e8-85c8-966a7765e4ef.png">

In selectedTimecard(), selectedTimecard$ objservable is causing issue while using pipe/take operations.

Please help us in resolving this issue.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by benlesh** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
