### ISSUE TITLE
Change CSSClass selector from [class] to [ng-class]

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#2765]
@mhevery I would like to discuss changing the [CSSClass directive selector](https://github.com/angular/angular/blob/f1cf5298d8f875c13177884152426064721e0847/modules/angular2/src/directives/class.ts#L11) from `[class]` to `[ng-class]`, the arguments being:
* it avoid doing unnecessary work for "static" class attributes in cases like `<div class="foo"`>
* clearly follows the convention of having directives prefixed
* avoids non-obvious cases like ``<div class="foo"` [class]="exp">`
* would ease migration from ng1

WDYT?

**Comment by mhevery** [comment]
> - it avoid doing unnecessary work for "static" class attributes in cases like <div class="foo">
This could be solved by `selector: '[bind-class]'` which would only trigger on expression bindings.

> - clearly follows the convention of having directives prefixed
True, but it creates this strangeness which is:
```
<div class='foo">
<div [class.foo]="true">
<div [ng-class]="{'foo': true}">
```
It feel strange that we have class, and then we just jump to `ng-class`

> - avoids non-obvious cases like `<div class="foo" [class]="exp">`
This case already exists: `<div class="foo" [class]" 'foo' " [class.foo]="true">`

> - would ease migration from ng1
Could you enumerate how it would help?



The mental model is that `[prop]` binds to properties. It is best to think of `class` as a set of properties one can bind to. `ng-class` breaks this mental model for me. 


Could we enumerate what the issues we are running into are?

**Comment by mhevery** [comment]
@pkozlowski-opensource any update on this?

**Comment by pkozlowski-opensource** [comment]
@mhevery for me the main question is - should the `[class]="exp"` binding be a special-case in a compiler or a directive? If a directive I would rename it to `ng-class`, otherwise people might expect `[class]: exp` to work in host properties.

Could we have a short chat about it tomorrow?

**Comment by pkozlowski-opensource** [comment]
Based on discussion with @mhevery the current thinking is that we are going to special-case binding to `[class]` in the compiler. This will be done as part of the #2364, so closing this one here.

If anyone is against special-casing `[class]="exp"` binding, now is the time to speak up :-)
