### ISSUE TITLE
Tutorial fails w/ Angular 7.1 due to deprecated dependency from angular-in-memory-web-api

### ISSUE THREAD

**Issue by darkn3rd** [angular/angular#27658]
# 📚 Docs or angular.io bug report

### Description

The tutorial tour of heroes, lesson 6 http (https://angular.io/tutorial/toh-pt6), no longer works with the step 

```
npm install angular-in-memory-web-api --save
```

This causes errors with:

```
ERROR in node_modules/angular-in-memory-web-api/http-backend.service.d.ts(2,75): error TS2307: Cannot find module '@angular/http'.
node_modules/angular-in-memory-web-api/http-in-memory-web-api.module.d.ts(2,28): error TS2307: Cannot find module '@angular/http'.
```

### What's the affected URL?**
https://angular.io/tutorial/toh-pt6

### Reproduction Steps**
```
npm install angular-in-memory-web-api --save
```

### Expected vs Actual Behavior**

Expected behavior is that this works, actual behavior is that cannot load the view anymore.

```
ERROR in node_modules/angular-in-memory-web-api/http-backend.service.d.ts(2,75): error TS2307: Cannot find module '@angular/http'.
node_modules/angular-in-memory-web-api/http-in-memory-web-api.module.d.ts(2,28): error TS2307: Cannot find module '@angular/http'.
```

## 📷Screenshot

The URL of `http://localhost:4200/heroes` shows.

```
Failed to compile.

node_modules/angular-in-memory-web-api/http-backend.service.d.ts(2,75): error TS2307: Cannot find module '@angular/http'. node_modules/angular-in-memory-web-api/http-in-memory-web-api.module.d.ts(2,28): error TS2307: Cannot find module '@angular/http'.
```

### Browser info

* Firefox Quantum 63.0.3 (64-bit)
* Mac OS X 10.14.1
* Node v10.14.0
* @angular/cli@7.1.2
* angular-in-memory-web-api@0.7.0
### Anything else relevant?

Was the API deprecated?  I noticed that instructions reference `@angular/common/http`, while package installed as per instructions looks for `@angular/http`.

### Workaround

```
npm install @angular/http --save
```

This may not be straightforward, as if Angular updates, the package version is not consistent.  When I started in December, the `package.json` had `7.1.0`, but running this command, the version it got was `7.1.3`.  I either had to manually change the package version, or update everything to `7.1.3` and stop/restart the service, CTRL-C + `ng serve`.  This may not be easy for new users.

**Comment by alxhub** [comment]
I can't reproduce this. The `package.json` for TOH part 6 installs both `@angular/common` and `@angular/http`, so `angular-in-memory-web-api` can work with it (and in fact it does build correctly). Please make sure your `node_modules` are up to date.
