### ISSUE TITLE
Router Guards inconsistency

### ISSUE THREAD

**Issue by UserGalileo** [angular/angular#27656]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/router

### Description

CanActivate, CanActivateChild and CanDeactivate wait for the first value emitted from the returned observable, while CanLoad waits for the observable to complete.

I find inconsistent how router guards behave, as it was stated in #25262.

It was stated that this behavior is documented, but it's not. The documentation says that 

> The Router guards require an observable to complete

, but it's not true. CanActivate and other guards don't require it.

Even if it was well documented, I think this behavior should be standardized.
What do you think? :) 

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-canload-test

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.1.1
Node: 8.11.1
OS: darwin x64
Angular: 7.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.1
@angular-devkit/build-angular     0.11.1
@angular-devkit/build-optimizer   0.11.1
@angular-devkit/build-webpack     0.11.1
@angular-devkit/core              7.1.1
@angular-devkit/schematics        7.1.1
@angular/pwa                      0.11.1
@ngtools/webpack                  7.1.1
@schematics/angular               7.1.1
@schematics/update                0.11.1
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
</code></pre>

**Comment by UserGalileo** [comment]
Just out of curiosity, why does it look like long-term to you? Do you think this would be a big breaking change for devs? Personally I’ve always used the take() operator with observables in canLoad so my logic wouldn’t break, I think the majority of us wouldn’t even notice, but it’s just my opinion :) Thanks!

**Comment by pshem** [comment]
Bump! https://angular.io/api/router/CanActivate#description still has no mention of the observable needing to complete and I've just wasted a day figuring out why my observable boolean wouldn't work, so I'd like to spare future developers the problem

**Comment by atscott** [comment]
Closing as obsolete. Updating the above example shows that the guards do not need to complete and that they all work the same. https://github.com/angular/angular/blob/cb48bde35d24f78f93e38fe487a0c42fee234ce6/packages/router/src/operators/check_guards.ts#L124
