### ISSUE TITLE
Bazel: ng serve gives a reference error

### ISSUE THREAD

**Issue by m0t0r** [angular/angular#27673]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/bazel

### Is this a regression?

 No

### Description

 
As recently `ng add` schematic was added for Angular CLI to create an Angular app with Bazel, I decided to give it a try and unfortunately got a reference error with `ng serve`

## 🔬 Minimal Reproduction

Install `@angular/bazel` with
```shell
npm i -g @angular/bazel@next
```
create a new Angular app with bazel collection
```shell
ng new bazel-app --collection=@angular/bazel --routing
```
the app is going to be generated, though npm install is not going to be run automatically (not sure why). I also changed versions of angular packages in generated `package.json` from `~7.1.0` to `7.2.0-beta.2` and run
```shell
npm i
```
then I tried
```shell
ng serve
```
and got the error below

## 🔥 Exception or Error
<pre><code>
Cannot find module 'angular/packages/bazel/src/builders/bazel'
Error: Cannot find module 'angular/packages/bazel/src/builders/bazel'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/m0t0r/WebstormProjects/bazel-app/node_modules/@angular/bazel/src/builders/index.js:24:19
    at /Users/m0t0r/WebstormProjects/bazel-app/node_modules/@angular/bazel/src/builders/index.js:12:17
    at Object.<anonymous> (/Users/m0t0r/WebstormProjects/bazel-app/node_modules/@angular/bazel/src/builders/index.js:18:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
7.2.0-beta.2
</code></pre>

**Anything else relevant?**

Thanks

**Comment by kyliau** [comment]
Thanks for trying out ABC! (Angular + Bazel + CLI)

1. `npm_install` is not run automatically in Bazel because Bazel manages its own node_modules. Running `npm install` would therefore be unnecessary.

2. The error with node module resolution is fixed in https://github.com/angular/angular/pull/27715
(Meanwhile, you can run `yarn bazel run //src:devserver` to achieve the same goal)

**Comment by kyliau** [comment]
Regarding angular version, the schematics would reuse existing Angular installation if it detects one.
I've updated the schematics to make this more explicit: 
https://github.com/angular/angular/blob/master/packages/bazel/src/schematics/bazel-workspace/index.ts#L78

**Comment by m0t0r** [comment]
Great, thanks a lot @kyliau !
