### ISSUE TITLE
Router: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by devpreview** [angular/angular#27674]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 No. See issue #22643 

### Description

 If route contain component with empty path:

```
const routes: Routes = [
  {
    path: '',
    component: IndexComponent
  },
  {
    path: 'parent',
    component: ParentComponent,
    children: [
      {
        path: 'child',
        component: ChildComponent,
        children: [
          {
            path: '', // <-- Error appears here
            component: ThirdComponent
          }
        ]
      }
    ]
  }
];
```

`routerLink` directive can create relative url tree.

![Image of Reproduction](https://habrastorage.org/webt/gc/mz/j_/gcmzj_gwdzlhkuov6r5bfuk_v7g.png)

## 🔬 Minimal Reproduction

 

https://angular-router-error.stackblitz.io/parent/child

https://stackblitz.com/edit/angular-router-error

## 🔥 Exception or Error
<pre><code>ERROR TypeError: Cannot read property 'path' of undefined</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular v7.1.3</code></pre>

**Comment by jasonaden** [comment]
@devpreview Thanks for creating a new issue on this. I see there's history on the closed issue, but we typically don't get a chance to go into closed issues so it's much better to just create a new one.

Based on the history here, I'm adding this to be looked at in one of the upcoming iterations. Due to the holidays in the US, it will likely be just after the New Year, but again, thanks for filing this new issue.

**Comment by dariobraun** [comment]
@jasonaden how would one go about fixing this?

**Comment by sambaptista** [comment]
Interesting bug. I share my usecase in case it could help.

I re-used a component from a project in a new one. Only the routing changed and this bug happened.

Before it was working with following structure :

```js
const routes: Routes = [
    { 
        path: 'user',
        component: UsersComponent,
    }
]
```

New structure don't work : 

```js
const routes: Routes = [
    { 
        path: 'user',
        children :  { 
            path: '', <-- error because of this
            component: UsersComponent,
        }
    }
]
```

My listings use matrix/optional params to store filtering/pagination `/users;pageSize=123` by using `this.router.navigate(['.', params], {relativeTo: route});`

I will return back to old routing structure for now.

**Comment by giniedp** [comment]
Running into the same error when using relative navigation and changing optional params only

```ts
this.router.navigate([{
  tab: this.activeTab,
}], {
  relativeTo: this.route,
})
```

**Comment by cyberiny** [comment]
Can anyone tell if this issue has been resolved, please?

**Comment by sambaptista** [comment]
It's fixed for me (angular 7.2 and 8.2)

**Comment by sambaptista** [comment]
Not yet.

**Comment by VladimirMishyn** [comment]
Still remains broken in @angular/router 8.0.3 . It's common use case, and there should be a simple way to update optional(matrix) params of current route without clumsy workarounds or redisigning routes hierarchy.

**Comment by MarkoSulamagi** [comment]
Bumping this bug, so the bot wouldn't close it :) Same issue for me.

**Comment by paya-cz** [comment]
I had the same problem. For me, the issue got resolved after using `relativeLinkResolution: 'corrected'`.

https://angular.io/api/router/ExtraOptions

eg.:

```ts
@NgModule({
    imports: [
        RouterModule.forRoot(
            appRoutes,
            {
                relativeLinkResolution: 'corrected'
            }
        )
    ],

    exports: [
        RouterModule
    ]
})
export class AppRoutingModule { }
```

**Comment by atscott** [comment]
As @paya-cz mentioned, `relativeLinkResolution: 'corrected'` is the fix for the issue described here. I've opened #37355 to make this option the default.
