### ISSUE TITLE
FormGroup reset() throws if a control is removed from valueChanges subscription

### ISSUE THREAD

**Issue by ShiftySituation** [angular/angular#27679]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

 
not sure

### Description

During OnChanges, we reset a form group.  This causes the valueChanges to fire which causes a control to be remove from the group, via a subscription to the valueChanges event.  The issue is that this control is still part of the form groups dictionary of named control but the value is null.   

## 🔬 Minimal Reproduction

The below code for the reset function calls control.reset as it iterates each control.  Since the control is null, there is no reset function.
- the work around was to set the emitEvent option to false, but that causes other issues since we are listening for other valueChanges events... so we have to work around those.
`
FormGroup.prototype.reset = function (value, options) {
        if (value === void 0) { value = {}; }
        if (options === void 0) { options = {}; }
        this._forEachChild(function (control, name) {
            control.reset(value[name], { onlySelf: true, emitEvent: options.emitEvent });
        });
        this.updateValueAndValidity(options);
        this._updatePristine(options);
        this._updateTouched(options);
    };`

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

TypeError: Cannot read property 'reset' of undefined
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

6.1
</code></pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment]
Could you please provide a minimal reproduce scenario in a stackblitz?

**Comment by kara** [comment]
Closing, as we have no repro case

**Comment by ShiftySituation** [comment]
I'll test this again and provide a repro tomorrow.   been on vacation for the past month ;)

**Comment by ShiftySituation** [comment]
I couldn't reproduce this issue.

**Comment by ShiftySituation** [comment]
@kara I ran into the issue again today and created a repo while it was still fresh in my mind.

https://stackblitz.com/edit/angular-uiibu2

simply type 1 in the input box and hit save.  when you type 1, it will cause the value change to fire which adds another control to the form group via the subscription set up in ngOnInit.  When you hit save, it resets the formGroup, causing the value change to fire again which removes the control.  This creates the error, "TypeError: Cannot read property 'reset' of undefined" since it is trying to reset each control of the formGroup even though the control has been removed.

**Comment by ShiftySituation** [comment]
> Closing, as we have no repro case

reopen please?

**Comment by mohammedzamakhan** [comment]
@ShiftySituation You need to unsubscribe your subscription
https://stackblitz.com/edit/angular-jw9qaw?file=src/app/app.component.ts

**Comment by ShiftySituation** [comment]
> @ShiftySituation You need to unsubscribe your subscription
> https://stackblitz.com/edit/angular-jw9qaw?file=src/app/app.component.ts

this keeps the error from happening but the form control that should be removed is still present, which isn't the desired approach.  now I have to know everything about my form and do extensive cleanup where an imperative approach is desired.

**Comment by ShiftySituation** [comment]
Is there something special that I need to do to get this recognized as an actual issue and re-opened?  I'll be more than happy to submit a PR as well.
