### ISSUE TITLE
Broken tutorial

### ISSUE THREAD

**Issue by ghost** [angular/angular#27683]

**Comment by hungerregnuh** [comment]
What exactly isn't working for you? both the live example on stackblitz and the zip file in the ToH Tutorial both work fine for me.

**Comment by jotatoledo** [comment]
A lot of nonsense in such a small text.

> The angular tour of heroes tutorial is completely broken. Either update it or remove it entirely, because it is completely useless as is.

Could you please be more specific about this statement? AFAIK the TOH works as expected.

> The fact that you're changing basic packages so much behind the scenes is really disconcerting. 

Again, could you be more specific? The only large change that I can remember was the migration from the old `Http `API to the new `HttpClient `API.

> Why would I ever want to use Angular when you're changing the underlying implementation? If I had deployed this app, you would have broken it now.

Sure, angular has refactored its render engine a couple of times until now. And the reasons that you want that would be:

- Faster
- Smaller
- Backwards compatible

Considering that angular sticks largely to semver standards, internal changes wont break existing apps in most cases, unless you YOLO and update to a mayor release without taking care of breaking changes.

**Comment by pkozlowski-opensource** [comment]
Going to close it as the issue description is now empty...
