### ISSUE TITLE
Fix webdriver-js-extender now.

### ISSUE THREAD

**Issue by Trojaner** [angular/angular#27681]
It looks like the package is kinda abandoned. A huge breaking bug exists which also has a pull request for fix (1 line change). 

The pull request exists since 14th August 2018. It has been 4 months now.

https://github.com/angular/webdriver-js-extender/issues/27
https://github.com/angular/webdriver-js-extender/pull/26

**Comment by pkozlowski-opensource** [comment]
Followed up with the owners of https://github.com/angular/webdriver-js-extender/ - hopefully you will see some progress on those issues in the coming days.

**Comment by Trojaner** [comment]
No progress since 2 months.
This is pure chaos.

**Comment by SliceofCheese** [comment]
Agreed. It's a problem for trying to pull from remote repositories to have everyone's local repository set up to date.
