### ISSUE TITLE
[Feature Request] [Fetch API] Support for JavaScript fetch API

### ISSUE THREAD

**Issue by kaushiksamanta** [angular/angular#27689]
It would be nice to have support for fetch API built into httpClient module.
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

**Comment by dawidgarus** [comment]
Fell free to implement custom HttpBackend that uses Fetch API. For what I know, not all features can be implemented using fetch - there are issues with upload progress indication.

**Comment by alxhub** [comment]
With the deprecation of IE11, there are no technical blockers to a `fetch` based backend that I'm aware of.

**Comment by jimmywarting** [comment]
> not all features can be implemented using fetch - there are issues with upload progress indication.

Well, there are issues with XHR as well, you can't get a readable stream for instances...
and what do you mean by *all*? the only thing i can really think of is progress event
fetch can be aborted using abortSignal

and progress can somewhat be monitored for progress if you can pipe the readable stream through a transform stream that calculates bytes that has passed through. but it is not the best solution as you need to know content-length and then it can not be compressed using gzip, deflate or br. It's not the best solution but something that kind of work in user land

**Comment by dylhunn** [comment]
The different design assumptions of fetch as compared to XHR means it's not a drop-in replacement with HTTPClient, and design changes would be needed. Until we do so, however, you can just use fetch on its own without HTTPClient, of course.

**Comment by thw0rted** [comment]
@dylhunn the main reason I switched from using `fetch` directly to using `HTTPClient` was that the latter is easy to stub out for testing, while the former would require that I start injecting a `fetch` alias with a token, then find or write a library for mocking requests during testing.

**Comment by JeanMeche** [comment]
Support has been added in 16.1 per #50247
