### ISSUE TITLE
feat(EventEmitter): add common combinators from Dart Streams and RxJS Lite

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2768]
I'm particularly motivated to do this quickly since the `Http` lib is being refactored to use `EventEmitter`, which uses RxJS implicitly as a private subject, but doesn't yet surface any of the RxJS combinators. This list is not exhaustive, but includes the combinators I care most about for `http`. From a cursory look, many of these combinators look similar enough between [RxJS lite](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/libraries/lite/rx.lite.md) and [Dart Streams](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:async.Stream) to go ahead and add the methods to the `ObservableWrapper` facade.

Class Methods

 * [interval](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/interval.md)/[periodic](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:async.Stream#id_Stream-periodic) (Useful for short polling)

Instance Methods
 * [map](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/select.md) ([dart](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:async.Stream#id_map))
 * [flatMapLatest](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/flatmaplatest.md) (Not implemented in Dart Streams)
 * [retry](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/retry.md) (Not implemented in Dart Streams)
 * [retryWhen](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/retrywhen.md) (Not implemented in Dart Streams)
 * [toPromise](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/topromise.md) / toFuture (Not implemented in Dart Streams)
 * [multicast](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/multicast.md) / [asBroadcastStream](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:async.Stream#id_asBroadcastStream)
 * [do](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/do.md) (Not implemented in Dart Streams)
 * [filter](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/where.md) / [where](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:async.Stream#id_where)
 * [repeat](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/repeat.md) (Not implemented in Dart Streams. Useful for long polling.)
 * [throttle](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/debounce.md) (Not implemented in Dart Streams)

This brings up the question, why don't we just expose the underlying primitive (Observable or Stream) from the different APIs (like `Http`), and let users use whichever primitive is supported by their language (`EventEmitter` already provides a `toRx` method)? The challenge for `Http`, forms, and other parts of Angular, is that the framework may want to take advantage of these combinators, like providing simpler abstractions to handle common use cases like polling. Without these combinators existing on `EventEmitter`, separate special-cased implementations of these features would have to be developed for JS and Dart.

CC @vsavkin @yjbanov

**Comment by yjbanov** [comment]
This issue just popped up today. The fact that we require that components
publish events as EventEmitter doesn't work well in Dart, where you want to
be able to export events from existing stream controllers. Also,
EventEmitter is simultaneously the sink and source of events, which means
that the *users* of components can push events into them. This breaks
encapsulation.

**Comment by jeffbcross** [comment]
@vsavkin and I chatted a little bit about it this morning, and his thinking is that we should return the primitive-of-choice for the target platform (Rx Observable for JS, Stream for Dart) instead of return EventEmitter. For places in the framework that would take advantage of features of Observables or Streams, there would need to be an Observable implementation, and a Dart stream implementation. For example, if I wanted to create a polling function like so: `poll(http.request({url: 'https://foo'}), 1000)`, I would need to implement two versions of that function. I've come around to this idea more than my original proposal, given how limiting it would be to have a single common interface that plays well with Streams and Observables. 

But the convenience of relying on distinct, platform-specific primitives costs us some simplicity and usability in how we build tooling and communicate best practices to users. I'm curious what the alternative costs (performance, usability, maintenance, otherwise) are associated with porting RxJS to dart (with fromStream and toStream operators to make stream interop easy). I have an idea what the maintenance and up-front cost would be to do this, but what would other considerations be, @yjbanov?

CC @alxhub

**Comment by yjbanov** [comment]
I vote for platform-specific primitives. It will produce much more idiomatic API. Especially in Dart, where Stream is part of the core library and is familiar to everyone and API-compatible with all Stream libraries out there. There are several ports of Rx utilities to Dart already (https://github.com/google/quiver-dart, https://github.com/danschultz/stream_transformers, https://github.com/theburningmonk/stream_ext). Another port that uses non-standard API would add no value to a Dart developer. We would basically have them learn a second stream API and have them connect the two, which means more wasted brain cycles and coding on their part. Also such a port would add to code size.

**Comment by jeffbcross** [comment]
K, sounds like the lowest hanging fruit that we all agree on is to start exporting observables and streams in the places that are currently using eventemitter. As more concrete use cases arise to build features around these primitives, we can open new discussions.
