### ISSUE TITLE
Form inputs created with *ngFor ( and thus having same "name") are having same value

### ISSUE THREAD

**Issue by sangupta007** [angular/angular#27692]
# 🐞 bug report
Following code is having different outputs when its inside of a form vs inside of a normal div.
```
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
  <p>Inside form</p>
  <form #myForm="ngForm">
    <div *ngFor="let item of arr; let i = index">
      <input name="name" [ngModel]="arr[i]">
    </div>
  </form>

  <br>
  <p>Inside normal div</p>
  <div>
    <div *ngFor="let item of arr; let i = index">
      <input name="name" [ngModel]="arr[i]">
    </div>
  </div>
`
})
export class AppComponent {
  arr = [1, 4];
}

```
**Result:**
<img width="176" alt="so" src="https://user-images.githubusercontent.com/16303528/50047209-1d3cc000-00d7-11e9-9a22-42bf9a15951d.png">

### Description
As you can see in above code when inside of a form, `*ngFor` iterate over the array to produce inputs with the same value. I am curious what is causing this behaviour. **I admit that in case of the form, both the inputs are represented by the same FormControl because of same ```name```.** But even then, their value should be tied to  `arr[i]` as per ` [ngModel]` and not to `FormControl`. 

Note : I am aware this isn't recommended way to write this code and both `input `should have different `name`. I am asking this only because I am curious why the code behaves that way. Maybe its a bug?

## 🔬 Minimal Reproduction
[Stackblitz link](https://stackblitz.com/edit/angular-mctp2s?file=src%2Fapp%2Fapp.component.ts)

**Comment by manklu** [comment]
> I admit that in case of the form, both the inputs are represented by the same FormControl because of same name.

Same form control means same value. If you want the same behaviour as with the div you should use:
```html
<form ngNoForm>
  <div *ngFor="let item of arr; let i = index">
    <input name="name" [ngModel]="arr[i]">
  </div>
</form>
```

> But even then, their value should be tied to arr[i] as per [ngModel] and not to FormControl.

Work as designed

> vs inside of a normal div

Here the inputs don't have a parent form group. As result each get it's own form control. If you want the same behaviour as with the form you should use:
```html
<div ngForm>
  <div *ngFor="let item of arr; let i = index">
    <input name="name" [ngModel]="arr[i]">
  </div>
</div>
```

**Comment by pkozlowski-opensource** [comment]
Sounds like a support request - thnx @manklu for helping out others (and us)!
