### ISSUE TITLE
changeDetection Not checking for update when i use rxjs interval with ApplicationRef.isStable

### ISSUE THREAD

**Issue by sheikalthaf** [angular/angular#27704]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

Don't know whether it is worked in previous or not

### Description

 A clear and concise description of the problem...
If i want to use interval in my application i have to start interval after app isStable. But it makes application not to check for changes

## 🔬 Minimal Reproduction

 
https://stackblitz.com/edit/angular-if8xoz

In above link `app.component.ts - ngOnInit` hook my interval is running and console log give the correct value but the ui is not updating. This occurs only when i use `ApplicationRef.isStable`

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.0.7
Node: 10.10.0
OS: win32 x64
Angular: 7.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@angular/fire                     5.1.1
@angular/pwa                      0.10.7
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
</code></pre>

**Anything else relevant?**

**Comment by sheikalthaf** [comment]
@gkalpak any help will be appreciated. Because in my application i'm using PWA, If i activate interval without app isStable it breaks the PWA registration.

**Comment by JiaLiPassion** [comment]
I believe `isStable observable` is run outside of `ngZone`, so you need to use `ngZone.run` in your logic.

**Comment by gkalpak** [comment]
@JiaLiPassion is right: The `isStable` observable is run [outside the Angular zone][1], so you need to manually re-enter the zone (with `ngZone.run()`):

```ts
return isStable.
  pipe(switchMap(() => interval$)).
  subscribe(e => this.zone.run(() => ...));
```

[1]: https://github.com/angular/angular/blob/5452889aa61a9963f443302d93d8af6c4131aa10/packages/core/src/application_ref.ts#L403

**Comment by sheikalthaf** [comment]
@gkalpak @JiaLiPassion thanks for the clarification. As per my requirment i can't able to use zone after subscribe because it is used in many places. I tried this one also but still fails. 

```javascript
return isStable.
  pipe(switchMap(() => this.zone.run(() =>interval$))).
  subscribe(e => data...));
```

May i know any trick to use zone before subscribe?

**Comment by gkalpak** [comment]
I might do something like below (but I am neither a Zone.js nor an RxJS expert :grin:):

```ts
const isStable$ = this.appRef.isStable.pipe(first(x => x));
const interval$ = interval(1000).pipe(startWith(null));
 
return new Observable(observer =>
  isStable$.subscribe(() =>
    this.zone.run(() => {
      let count = 0;
      return interval$.
        pipe(
          map(() => count++),
          tap(() => console.log('emit')),
        ).
        subscribe(observer);
    })));
```

**Comment by JiaLiPassion** [comment]
@gkalpak, thanks for the update, and I believe `isStable` is `outsideOf ngZone` to avoid endless loop.
So `isStable next -> ngZone.run -> isStable next ...`.

**Comment by sheikalthaf** [comment]
@JiaLiPassion @gkalpak thanks for the clarifications. For the first time I'm trying PWA in our apps and it is ready for Production

1. I want to know why we have to check for isStable before running any `interval or timer`.
    * One purpose i know is that for registering service worker file because it is registers only on stable app
    * any other thing.

2. Another one is `isStable` checks once in app runtime or it checks always for app stable and emits.

    * because i have some timers in  my app it will get starts once app isStable after that i have some pages where I run intervals and again i'm checking for `isStable` to run interval on that time already timer is running. What will happen?

**Comment by JiaLiPassion** [comment]
@sheikalthaf, ok, I think I may know your case. I created a PR for the similar issue here, https://github.com/angular/angular/pull/21842

If you have some `timer` or `interval` when `startup of PWA`, `angular PWA` will never get chance to register automatically. so you have to `register manually` by yourself. You can check the PR above.

**Comment by sheikalthaf** [comment]
@JiaLiPassion @gkalpak may i know when this will gets merged because my application will soon will be ready for production.

Also #27080 this PR also still in pending. @gkalpak any info will helps us to solve

**Comment by gkalpak** [comment]
@sheikalthaf, I have approved #27080, but it needs more approvals. Right now, Ivy is the highest priority, so other things get a lower priority, so it might take some time.
