### ISSUE TITLE
Support relative urls in dart

### ISSUE THREAD

**Issue by jakemac53** [angular/angular#2771]
Dart part of https://github.com/angular/angular/issues/2383. We need to make a runtime and transformed version of [ComponentUrlMapper](https://github.com/angular/angular/blob/master/modules/angular2/src/core/compiler/component_url_mapper.ts). Dynamic version can just use mirrors and compute the path based on the type. The transformer should populate a static map with the paths to all component types, and use that to compute relative paths to the root of the app dynamically. This can probably be populated inside of the ng_deps.dart files.

**Comment by jakemac53** [comment]
see also https://github.com/angular/angular/pull/2658, this is what adds the ability to not inline urls

**Comment by jakemac53** [comment]
@munificent is working on at least the mirrors based version of this, but can't assign him because hes not part of the org yet

**Comment by munificent** [comment]
Yes, see: https://github.com/angular/angular/pull/2827
