### ISSUE TITLE
Offline Angular PWA fails on iPhone after a short period

### ISSUE THREAD

**Issue by Sharpiro** [angular/angular#27713]
# 🐞 bug report

### Affected Package

The issue is caused by package:
 ```
"@angular/pwa": "^0.11.3"
"@angular/service-worker": "~7.1.0"
```

### Description

Currently the Angular PWA package seems to work great, especially with the CLI, very simple and easy to use.  

However I have noticed a very odd bug.  When I do "Add to Home Screen" on my iPhone, and begin to test the offline functionality, the application will work for up to a few hours, at which point the app will seize to load and simply display a blank page or display, "Safari cannot open the page because your iPhone is not connected to the internet".  If I turn off the web server at this point and turn on iPhone networking, then the PWA will display the blank page.  

At first I assumed this was a current limitation of using an iPhone with PWAs, however, I tested 2 other (non-angular) PWAs and they work offline permanently on iPhone: [The Cube](https://bsehovac.github.io/the-cube/) and [Dinosaur Game](https://offline-dino-game.firebaseapp.com/)

I tested this on 2 iPhones running IOS 12.1 and 12.1.1, and they both lost the ability to load the PWA at the exact same time (about an hour).  It seems like some sort of cache time limit gets hit where it then requires a network refresh.

## 🔬 Minimal Reproduction

```
ng new pwatest
cd pwatest
ng add @angular/pwa -s
ng build --prod
http-server dist\pwatest
```
* verify loading works offline in chrome network tab
* navigate to site through iphone safari browser and "Add to Home Screen"
* verify PWA loads from home screen icon
* disable all network connections on iPhone
* wait unknown amount of time for PWA to fail to reload and then not function again until network connection re-established

> Couldn't figure out how to get stackblitz working with angular service workers

## 🌍  Your Environment

**Angular Version:**
```
Angular CLI: 7.1.3
Node: 11.3.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.11.3
@angular-devkit/core         7.1.3
@angular-devkit/schematics   7.1.3
@schematics/angular          7.1.3
@schematics/update           0.11.3
rxjs                         6.3.3
typescript                   3.1.6
```

**Comment by gkalpak** [comment]
I don't have an iPhone to investigate this, but here are a couple of questions:
1. Does it work if you don't add it to Home screen?
2. While it is broken from Home screen, does it work in the browser?
3. While it is broken, what does the browser show when you navigate to `<your-domain>/ngsw/state`?

**Comment by Sharpiro** [comment]
1. Yes, it works fine from the mobile browser, but no offline activity works at all, not even temporarily.
2.  & 3. see below

Ok, I just ran the experiment again with 2 iPhones and 1 web browser.  I set them all up w/ the PWA working and then I killed the server.

The 2 iPhones again cut out at the same time, at almost exactly 1 hour

In chrome, I am still able to access the PWA and refresh it normally.

Browser Debug Info:
```
NGSW Debug Info:

Driver state: NORMAL ((nominal))
Latest manifest hash: 72fb15a2661dd35e9e198e9c806c8e81d10b475a
Last update check: 1h8m42s892u

=== Version 72fb15a2661dd35e9e198e9c806c8e81d10b475a ===

Clients: 5b4d38ca-7d52-48cb-8872-1cb2fd786d87, f8518fca-ffc9-4526-9b80-40871263ad64, 07ad2c89-fa36-47b9-b166-b3d70d17477d, d6e1e438-259d-4a56-8aef-14afd6e58220, aa97a71a-a9c2-4f2d-ad91-bd539ff834e7, 590a7fe6-b67e-4e85-b12f-957c7391d91f, e5541d06-a89c-49b2-b0a3-25b4ee663d70, 3b8dab08-ca86-4c5c-9e9f-252c655eef9e, 0044007e-1690-4ac4-b96c-f663fb9708b2, 0228460c-07fd-44db-9cf9-793a435a41ef

=== Idle Task Queue ===
Last update tick: 1m56s963u
Last update run: 1m51s962u
Task queue:


Debug log:

[1h8m8s464u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(http://localhost:8080/ngsw.json?ngsw-cache-bust=0.5195074785963936)
[1h8m8s464u] Check for update aborted. (Client or server offline.) 
[1h7m38s510u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(http://localhost:8080/ngsw.json?ngsw-cache-bust=0.6587310261113983)
[1h7m38s510u] Check for update aborted. (Client or server offline.) 
[1h6m45s468u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(http://localhost:8080/ngsw.json?ngsw-cache-bust=0.7153353153529416)
[1h6m45s468u] Check for update aborted. (Client or server offline.) 
[17m29s147u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(http://localhost:8080/ngsw.json?ngsw-cache-bust=0.8917368902216467)
[17m29s146u] Check for update aborted. (Client or server offline.) 
[1m49s944u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(http://localhost:8080/ngsw.json?ngsw-cache-bust=0.1488647441806794)
[1m49s944u] Check for update aborted. (Client or server offline.) 
```

**Comment by gkalpak** [comment]
> Yes, it works fine from the mobile browser, but no offline activity works at all, not even temporarily.

I'm a little confused by that. What do you mean it works but no offline activity? (Doesn't it mean that it doesn't work, then? :grin:)
And which browser did you use? Safari?

Basically, the only difference between running the app in the browser and launching it from the Home screen is whether the browser UI (like address bar, back/forward buttons, etc) is shown. Under the hood, it is always run by the browser and should function the same.

**Comment by Sharpiro** [comment]
Oh man, I'm having trouble understanding what's going on here.

OK, so without doing any kind of "Add to Home Screen" functionality, and just trying to run offline through the safari mobile web browser, I'm getting different results from different web servers.

So when using ```http-server``` or ```angular-http-server``` over my local network, as soon as I turn on airplane mode, the application will be completely offline in mobile safari.

However, if I load the webpage from [Azure](https://statichostsharp.z13.web.core.windows.net/), I am able to continue to refresh the webpage offline.

I think this is a better test case b/c it doesn't involve "installing" a PWA, and waiting an unknown amount of time for it to fail.

**Comment by gkalpak** [comment]
Note that ServiceWorkers require a secure connection. So, if you don't use HTTPS, the SW will not be registered. One exception is `localhost`, which is considered a secure origin for development purposes. So, make sure you are serving over HTTPS or on `localhost` when using a local server.

**Comment by Sharpiro** [comment]
Ok my fault, that explains why the local http servers don't work at all.  I'm testing https Azure hosting now versus github which is what I was using before, which has more complexities due to different base addresses and interaction w/ 404.html

**Comment by Sharpiro** [comment]
I can confirm now that the angular service worker is working just as well as others when it comes to offline mode.

My issue now seems to be the relationship with service workers and github hosting, specifically the added complexity of having to deal with github's 404.html, and building an angular app w/ a different base address. E.g. ```ng build --prod --base-href "https://sharpiro.github.io/health/"```

On Azure everything seems to work fine, but when hosting to github, offline mode breaks immediately, even just in a desktop web browser.

I have a working example of this here:
* [Offline working on Azure](https://statichostsharp.z13.web.core.windows.net)
* [Offline broken on Github](https://sharpiro.github.io/health)

> When navigating to the above 2 links, you must refresh the page normally at least once before testing offline mode

**Comment by gkalpak** [comment]
Thx for following up on this. From a quick look, the reaosn it doesn't work on GitHub is that it serves 404.html with a 404 status code (which looks like a failed response to the SW and thus won't be cached). It is a long-standing issue: isaacs/github#408

Closing, since everything seems to be working as expected as far as Angular's SW is concerned.
