### ISSUE TITLE
ngModelGroup directive does not create an attribute

### ISSUE THREAD

**Issue by whein** [angular/angular#27716]
# 🐞 bug report

### Description

 The ngModelGroup directive does not create an attribute on the resulting HTML element if the group name is dynamic.

In the below StackBlitz, there are 3 fieldsets but only the output of the third fieldset element has the expected attribute.

```
  <fieldset ngModelGroup="{{id}}-test">
    <input type="text"/>
  </fieldset>
  <fieldset [ngModelGroup]="id + '-test'">
    <input type="text"/>
  </fieldset>
  <fieldset ngModelGroup="test">
    <input type="text"/>
  </fieldset>
```

![image](https://user-images.githubusercontent.com/810214/50117461-174ff780-021b-11e9-9220-37e90c419eb5.png)

## 🔬 Minimal Reproduction

[StackBlitz](https://stackblitz.com/edit/angular-77vuhq)

**Comment by pkozlowski-opensource** [comment]
> but only the output of the third fieldset element has the expected attribute.

Looking at your example it works as expected - in the 2 first cases we are binding to custom directive `@Inputs` and there is nothing to be written to the DOM. 

Are you expecting the `ngModelGroup ` _attribute_ to be reflected in the DOM? If so, why? What is the practical issue that you are trying to address? 

For now it looks to me as "works as expected" - we need more info.

**Comment by whein** [comment]
My expectation was that binding to the input of an attribute directive would write the resulting attribute to the HTML, similar to how one can bind the id attribute.

`<div [id]="variable + '-id'"></div>`

The use case that I ran into was trying to apply as CSS selector based on the attribute being present, specifically using the selector `.ng-invalid:not([ngModelGroup])`.

Originally this worked because our ngModelGroup names were static (situation 3 from my example),  but once we made the change to make the component re-usable by binding the name (situation 1 & 2) the above selector no longer works.

While I find this troublesome for my use case, I think I understand why this is the intended behavior - `@Input()` values can be objects, which don't make sense to put into the DOM. It'd be nice if there was some way I could say "this is a string, please put it in the DOM", but oh well.

Thanks for the explanation!

**Comment by pkozlowski-opensource** [comment]
> My expectation was that binding to the input of an attribute directive would write the resulting attribute to the HTML, similar to how one can bind the id attribute.

Now, directives are not automatically reflecting binding values to the DOM. This needs to be specifically coded as part of a directive. This is _not_ the same behaviour as for DOM properties (where most, but not all, property bindings are reflected as attributes in the DOM - but even in this case this is the DOM impl that does it, not Angular).

I full agree that difference between `ngModelGroup="test"` and `ngModelGroup="{{id}}-test"` is confusing and we are well aware of it. 

Anyway, I'm going to close it as it "works as designed" - but fully acknowledging that there is ample room for improvement in terms of syntax clarification so people are not getting caught up by surprise.

**Comment by whein** [comment]
Just in case anyone else runs into this, to resolve my problem I created my own custom directive that inherits from NgModelGroup.

```
export const modelGroupProvider: any = {
    provide: ControlContainer,
    useExisting: forwardRef(() => ModelGroupDirective)
  };

@Directive({
    selector: "[myModelGroup]",
    providers: [modelGroupProvider],
    exportAs: "myModelGroup"
})
export class ModelGroupDirective extends NgModelGroup implements OnInit {

    @Input("myModelGroup") name: string;

    constructor(
        private element: ElementRef<HTMLElement>,
        @Host() @SkipSelf() parent: ControlContainer,
        @Optional() @Self() @Inject(NG_VALIDATORS) validators: any[],
        @Optional() @Self() @Inject(NG_ASYNC_VALIDATORS) asyncValidators: any[]) {
        super(parent, validators, asyncValidators);
    }

    ngOnInit() {
        super.ngOnInit();

        if (typeof this.name === "string") {
            this.element.nativeElement.setAttribute("myModelGroup", this.name);
        }
    }
}
```

This functions identically to NgModelGroup, but it ensures that the attribute will always be present
