### ISSUE TITLE
XHR username and password cannot be set

### ISSUE THREAD

**Issue by fishbone1** [angular/angular#27724]
# 🚀 feature request

### Relevant Package

This feature request is for @angular/common/http

### Description
 

Angular doesn't allow setting the username and password for `HttpClient` requests. Most users suggest to set the `Authorization` HTTP header manually. However setting this request header and passing `username`/`password` arguments to `xhr.open()` are two different things, although it will work for most environments and noone will even experience different behavior.

However in my case there is a difference. I'm writing a Cordova app for iOS which uses WKWebView. XHRs don't work at all (!) as soon as I pass the `Authorization` header. But they work if I pass the `username` and `password` arguments to `xhr.open()`.

I guess the problem arises from the pre-flight `OPTIONS` request which is sent before the actual `GET` request due to CORS. Notice that the HTTP server ignores the `Authorization` header for `OPTION` requests. It seems to be a problem of the WKWebView itself.

### Describe the solution you'd like
 

Provide new options `username` and `password` for `HttpClient.request()`s `option`-argument. Pass these values to `xhr.open` here, if set:

https://github.com/angular/angular/blob/e98c57a404040c4e9841d5d65f99207444f16ae5/packages/common/http/src/xhr.ts#L85

### Describe alternatives you've considered

At the moment I plan to provide a custom `XhrFactory` which returns a patched `XMLHttpRequest` object. I add more details here when finished.

**Comment by fishbone1** [comment]
If the backend server is under your control you can fix it on the server side: You have to allow the `Authorization` header by setting the respective CORS response header, e.g.

```
Header always set Access-Control-Allow-Headers "authorization, x-requested-with, Content-Type, origin, accept, client-security-token"
```

**Comment by molysama** [comment]
The same problem. CORS work after change param to HttpParams.
```
// old
this.http.post(url, { 
  username: username
}).pipe(
```
```
// change to HttpParams
let body = new HttpParams()
body.set('username', username)
this.http.post(url, body)
```
