### ISSUE TITLE
injector.get() returns undefined instead of default value

### ISSUE THREAD

**Issue by thekiba** [angular/angular#27729]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: @angular/core@6.0.0-beta.3

### Description

 <b>injector.get()</b> returns undefined instead of the default value if such a token is not found and <b>InjectFlag.Self</b> is added.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-injector-bug-with-default-value-and-self-flag?file=index.ts

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.1.3
Node: 11.4.0
OS: darwin x64
Angular: 7.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.11.3
@angular-devkit/build-angular      0.11.3
@angular-devkit/build-ng-packagr   0.11.3
@angular-devkit/build-optimizer    0.11.3
@angular-devkit/build-webpack      0.11.3
@angular-devkit/core               7.1.3
@angular-devkit/schematics         7.1.3
@angular/cdk                       7.1.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.1.3
@schematics/angular                7.1.3
@schematics/update                 0.11.3
ng-packagr                         4.4.5
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.23.1

</code></pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment]
Ha, an interesting one! This behaviour is surprising since `InjectFlags.Self` only makes sense for node injectors and not for provider injectors. In other words, this flag should have no effect here - but it does as we can see in the stackblitz. 

Marking it as a bug, thnx for reporting!

**Comment by pkozlowski-opensource** [comment]
@marclaval this is probably an interesting case for the work you do in ivy.

**Comment by thekiba** [comment]
@pkozlowski-opensource, can i try fix bug by myself?

**Comment by pkozlowski-opensource** [comment]
@thekiba you can definitely work towards sending us a PR, this would be much appreciated! Thank you for taking time to report issues and willingness to help solving them!.

**Comment by thekiba** [comment]
I'm still having this issue
