### ISSUE TITLE
Angular is removing the index.aspx from the url

### ISSUE THREAD

**Issue by Korigoth** [angular/angular#27730]
# 🐞 bug report

### Affected Package
@angular/angular-cli

### Is this a regression?

Yes, it was working perfectly in Angular 5 but it doesn't in Angular 6 and 7.

### Description

I'm deploying my app in a SharePoint File Libs.
In Angular 5, while I was going on the web site the url was looking this way
www.mysharepointurl.com/App/index.aspx/#/home

but with the new configuration in angular (6 or 7), i'm now getting this url
www.mysharepointurl.com/App/#/home

it's breaking browser navigation.

## 🔬 Minimal Reproduction
i cannot make a minimal reproduction because it require a SharePoint site collection.

## 🔥 Exception or Error

the URL is wrong in the browser after Angular has loaded.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
    "@angular/compiler-cli": "7.0.3",
    "@angular/language-service": "7.0.3",
    "@angular/service-worker": "7.0.3",

    "@angular/animations": "7.0.3",
    "@angular/common": "7.0.3",
    "@angular/compiler": "7.0.3",
    "@angular/core": "7.0.3",
    "@angular/forms": "7.0.3",
    "@angular/platform-browser": "7.0.3",
    "@angular/platform-browser-dynamic": "7.0.3",
    "@angular/router": "7.0.3",

</code></pre>

**Anything else relevant?**
I think it's coming from the new way to build the project but i'm not sure about it.

Server : SharePoint in a File Libs.

**Comment by Korigoth** [comment]
I've finaly found it...
So many hours to find it and i always get the answers after i ask on SO or Github!

this is the url where i found my solution
https://shekhargulati.com/2017/07/06/angular-4-use-of-base-href-and-deploy-url-build-options/

DeployUrl = /App/
BaseHref = /App/index.aspx/ 

Now it seems to work like it was working in Angular5.
I don't know why we didnt have to put the --deployurl in angular 5 but now it work so its the important thing!

**Comment by gkalpak** [comment]
Closing since you were able to solve the problem and it is not clear whether it is related to Angular or Angular CLI and how.
