### ISSUE TITLE
v7.1.4 initial package.json no longer includes @angular/http, breaks TOH tutorial

### ISSUE THREAD

**Issue by Dubtuff64** [angular/angular#27746]
# 📚 Docs or angular.io bug report

### Description
The @angular/http is no longer a default dependency included in package.json of angular projects. It has to be added manually or an error occurs. Including the instructions to do so will prevent frustration for beginners attempting the Tour of Hero's Tutorial.

### What's the affected URL?**
https://angular.io/tutorial/toh-pt6

### Reproduction Steps**

1. Attempt Tour of Heros Tutorial on the most recent version of Angular.
2. Complete up to the 6th Part: HTTP
3. Begin refactoring code to rely on an in-memory-data service instead of mock-heroes.
4. Attempt to ng serve when there are no coding errors.

### Expected vs Actual Behavior**

The code is expected to run without errors.
Instead the following compile time error appears due to a missing dependency.

## 🔥 Exception or Error
<pre><code>

ERROR in node_modules/angular-in-memory-web-api/http-backend.service.d.ts(2,75): error TS2307: Cannot find module '@angular/http'.
node_modules/angular-in-memory-web-api/http-in-memory-web-api.module.d.ts(2,28): error TS2307: Cannot find module '@angular/http'.

</code></pre>

## 🌍  Your Environment
Visual Studio Code 1.30.0
### Anything else relevant?

The solution for the error is readding @angular/http to the package.json. The real issue is having the solution amended to the Tutorial Page.

**Comment by ericmartinezr** [comment]
Related/dup https://github.com/angular/angular/pull/27434#issuecomment-444596254

**Comment by jenniferfell** [comment]
Thanks for letting us know. There appears to have been a change in the initial package.json between 7.0 and 7.1.4. The required line is included in this snippet: 

  "dependencies": {
    "@angular/animations": "~7.0.0-beta.5",
    "@angular/common": "~7.0.0-beta.5",
    "@angular/compiler": "~7.0.0-beta.5",
    "@angular/core": "~7.0.0-beta.5",
    "@angular/forms": "~7.0.0-beta.5",
    "@angular/http": "~7.0.0-beta.5",
    "@angular/platform-browser": "~7.0.0-beta.5",
    "@angular/platform-browser-dynamic": "~7.0.0-beta.5",
    "@angular/router": "~7.0.0-beta.5",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.2",
    "zone.js": "~0.8.26"
  },

**Comment by jenniferfell** [comment]
[package-714.json.txt](https://github.com/angular/angular/files/2700757/package-714.json.txt)
[package-70.json.txt](https://github.com/angular/angular/files/2700758/package-70.json.txt)
