### ISSUE TITLE
feat(router): Matrix params

### ISSUE THREAD

**Issue by btford** [angular/angular#2774]

**Comment by naomiblack** [comment]
slipped to alpha-30. this was more work than anticipated.

**Comment by naomiblack** [comment]
Pushed to alpha-31 -- Matias and Brian need to pair in person to get this started.

**Comment by yjbanov** [comment]
This issue is not on any hotlist. Why is it a P1? Also, what is "matrix params"? :)

**Comment by btford** [comment]
@yjbanov think of it as a generalized queryParams – http://www.w3.org/DesignIssues/MatrixURIs.html

Not sure why @naomiblack made it a P1.

**Comment by naomiblack** [comment]
I think because it was blocking other things at the time? Demoting to P2.

**Comment by matsko** [comment]
It's merged in now anyway.
