### ISSUE TITLE
compiler outputs invalid summaries for imported @angular/common/http

### ISSUE THREAD

**Issue by anhallbe** [angular/angular#27749]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler and/or @angular/common/http version 7.1.3

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 6.0.0

### Description

 One of the files (app.ts) in our project is using the following import:
```
import { HttpClientModule } from "@angular/common/http";
```
When compiling with `ngc -w`, this is what the `app.ngsummary.js` initially looks like:
```
...
var i249 = require("../../../node_modules/@angular/common/http/http.summary");
...
```
But when some file changes, which causes the code to re-compile, the output looks like this:
```
...
var i249 = require("../../../node_modules/@angular/common/http.summary");
...
```
...but the file `node_modules/@angular/common/http.summary` does not exist, which causes runtime errors.

## 🔬 Minimal Reproduction

https://github.com/anhallbe/ngc-repro

## 🔥 Exception or Error
<pre><code>

Failed to load resource: the server responded with a status of 404 (Not Found)
base-bundle.js:41 Unhandled Promise rejection: Fetch error: 404 Not Found
  Instantiating http://localhost:8080/node_modules/@angular/common/http.ngsummary.js
  Loading http://localhost:8080/path/to/app.ngsummary.js
  Loading main ; Zone: <root> ; Task: Promise.then ; Value: Error: Fetch error: 404 Not Found
    at base-bundle.js:46
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

// Not using @angular/cli. But versions as reported by npm are:
@angular/animations                  7.1.3
@angular/common                      7.1.3
@angular/compiler                    7.1.3
@angular/compiler-cli                7.1.3
@angular/core                        7.1.3
@angular/forms                       7.1.3
@angular/platform-browser            7.1.3
@angular/platform-browser-dynamic    7.1.3
@angular/router                      7.1.3
</code></pre>

**Anything else relevant?**

**Comment by fdragoon** [comment]
## Interim solution
use 
````typescript
import { HttpClientModule } from "@angular/common/http/http";
````

## Problem

in file `packages\compiler\src\aot\static_symbol_resolver.ts` line 109-134
````typescript
  getImportAs(staticSymbol: StaticSymbol, useSummaries: boolean = true): StaticSymbol|null {
    if (staticSymbol.members.length) {
      const baseSymbol = this.getStaticSymbol(staticSymbol.filePath, staticSymbol.name);
      const baseImportAs = this.getImportAs(baseSymbol, useSummaries);
      return baseImportAs ?
          this.getStaticSymbol(baseImportAs.filePath, baseImportAs.name, staticSymbol.members) :
          null;
    }
    const summarizedFileName = stripSummaryForJitFileSuffix(staticSymbol.filePath);
    if (summarizedFileName !== staticSymbol.filePath) {
      const summarizedName = stripSummaryForJitNameSuffix(staticSymbol.name);
      const baseSymbol =
          this.getStaticSymbol(summarizedFileName, summarizedName, staticSymbol.members);
      const baseImportAs = this.getImportAs(baseSymbol, useSummaries);
      return baseImportAs ?
          this.getStaticSymbol(
              summaryForJitFileName(baseImportAs.filePath), summaryForJitName(baseImportAs.name),
              baseSymbol.members) :
          null;
    }
    let result = (useSummaries && this.summaryResolver.getImportAs(staticSymbol)) || null;
    if (!result) {
      result = this.importAs.get(staticSymbol) !;
    }
    return result;
  }
````
`this.getImportAs(baseSymbol, useSummaries)` return value is different:

1. compile, return undifined and everything is normal.
2. recompile, return symbol with filePath `@angular/common/http.d.ts` and then convert to `@angular/common/http.summary.json`.

but I don't know how to fix it. but it has a simply way to resolve.

**Comment by anhallbe** [comment]
One work-around that seems to be working is to just move the summary file after the `npm install`:
```
mv node_modules/@angular/common/http/http.ngsummary.js node_modules/@angular/common/
```

@alxhub Ok, since we're only encountering this error during development (i.e running the compiler in watch-mode) I think we're fine with a work-around until we can move to the new compiler.

As for how we got here, it's a long story of AngularJS->Angular migration, mixed AOT & JIT compatibility, SystemJS and quite a bit of legacy code... 😅

**Comment by alxhub** [comment]
@anhallbe okay, sounds good to me. I'm going to close this as "Won't Fix", and hopefully Ivy completely solves the problem.
