### ISSUE TITLE
feat(router): auxiliary (aka "double slash") routes

### ISSUE THREAD

**Issue by btford** [angular/angular#2775]

**Comment by naomiblack** [comment]
punted back to backlog as a few other router issues more urgent.

**Comment by btford** [comment]
I have some work done on this, but not enough for a PR. I'm going to punt this to next week to prioritize bug fixes. @matanlurey has encountered some problems that he's going to file issues for.

**Comment by btford** [comment]
I made some headway on this last week.

I just need to re-implement redirects, fix a few broken tests, and add tests for more complex use cases.
