### ISSUE TITLE
Input autofocus not working in IE 11

### ISSUE THREAD

**Issue by texas-cody** [angular/angular#27757]
# 🐞 bug report

### Description

When opening a modal the first input is not automatically focused within said modal. This behavior occurs within IE 11 only and not Chrome/Firefox.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-nbytlr-bzvpqk

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Package                            Version  
--------------------------------------------
@angular-devkit/architect          0.10.6   
@angular-devkit/build-angular      0.10.6   
@angular-devkit/build-optimizer    0.10.6   
@angular-devkit/build-webpack      0.10.6   
@angular-devkit/core               7.0.6    
@angular-devkit/schematics         7.0.6    
@angular/cdk                       7.1.1    
@angular/cli                       7.0.6    
@angular/flex-layout               7.0.0-bet
@angular/material                  7.1.1    
@angular/material-moment-adapter   7.1.0    
@ngtools/webpack                   7.0.6    
@schematics/angular                7.0.6    
@schematics/update                 0.10.6   
rxjs                               6.3.3    
typescript                         3.1.6    
webpack                            4.19.1   
</code></pre>

**Anything else relevant?**

Version: IE 11.407.17134.0
Update VVersions: 11.0.95 (KB4466536)

**Comment by texas-cody** [comment]
Resubmission of #27756 - added Minimal Reproduction (accidentally forgotten)

**Comment by pkozlowski-opensource** [comment]
Thnx @texas-cody for adding reproduce scenario - however this seems to be something specific to material components and as such should be opened in https://github.com/angular/material2

Could you please move it to https://github.com/angular/material2? Thnx!

**Comment by texas-cody** [comment]
Can do thansk @pkozlowski-opensource
