### ISSUE TITLE
Input autofocus not working in IE 11

### ISSUE THREAD

**Issue by texas-cody** [angular/angular#27756]
# 🐞 bug report

### Description

When opening a modal the first input is not automatically focused within said modal. This behavior occurs within IE 11 only and not Chrome/Firefox.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Package                            Version  
--------------------------------------------
@angular-devkit/architect          0.10.6   
@angular-devkit/build-angular      0.10.6   
@angular-devkit/build-optimizer    0.10.6   
@angular-devkit/build-webpack      0.10.6   
@angular-devkit/core               7.0.6    
@angular-devkit/schematics         7.0.6    
@angular/cdk                       7.1.1    
@angular/cli                       7.0.6    
@angular/flex-layout               7.0.0-bet
@angular/material                  7.1.1    
@angular/material-moment-adapter   7.1.0    
@ngtools/webpack                   7.0.6    
@schematics/angular                7.0.6    
@schematics/update                 0.10.6   
rxjs                               6.3.3    
typescript                         3.1.6    
webpack                            4.19.1   
</code></pre>

**Anything else relevant?**

Version: IE 11.407.17134.0
Update VVersions: 11.0.95 (KB4466536)

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
