### ISSUE TITLE
Pattern validation does not work correctly with input type number

### ISSUE THREAD

**Issue by tommueller** [angular/angular#27758]
### Affected Package
@angular/forms

### Is this a regression?
No, I don't think so.

### Description
Using a pattern validator to only allow commas as decimal separator like this:
`Validators.pattern(/^[+-]?[0-9]+(,[0-9]+)?$/);`
is working fine on inputs, as long as the input is not defined as `type="number"`. Validation of the pattern then does not work anymore.
I assume this issue exists, because the browser does his magic first, before passing the value to Angular?!

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-wmcekk?file=src%2Fapp%2Fapp.component.html

There is way more information in my StackOverflow-question here: https://stackoverflow.com/questions/53853676/reactive-form-pattern-validator-not-validating-the-pattern-correctly

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 6.2.4
Node: 8.13.0
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.4
@angular-devkit/build-angular     0.8.4
@angular-devkit/build-optimizer   0.8.4
@angular-devkit/core              0.0.29
@angular-devkit/schematics        0.8.4
@angular/cdk                      6.4.7
@angular/cli                      6.2.4
@angular/material                 6.4.7
@schematics/angular               0.8.4
@schematics/update                0.8.4
rxjs                              6.3.3
typescript                        2.9.2
webpack                           3.11.0
</code></pre>

**Comment by sarunint** [comment]
Because the value returned is already a number. Not a string. So naturally it does not match any RegEx's.

**Comment by kara** [comment]
@tommueller This is actually working as intended. We align with the spec, which dictates that pattern validation isn't compatible with number inputs (see [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#Pattern_validation)). We should probably have linting that prevents people from using it accidentally though, so perhaps we should open an issue in codelyzer repo?

**Comment by tommueller** [comment]
Thank you for the clarification @kara 
I think a feature request in codelyzer is great, I will do this, as well as a feature request that Angular enforces usage of right decimal separator for number inputs ootb.
