### ISSUE TITLE
ES2015 iteration not supported

### ISSUE THREAD

**Issue by alxhub** [angular/angular#27762]
Iterating over an ES2015 collection is not supported in our compilation. Ex:

```javascript
const edges = new Set([1, 2, 3]);
for (const edge of edges) { ... }
```

It gets transpiled correctly when built under Bazel, but will fail on Travis in the old `build.sh` system, as that uses a set of `tsconfig`s and a version of TS that don't seem to support it. The error is:

```
error TS2569: Type 'Set<T>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.
```

**Comment by Peilonrayz** [comment]
Add the following to your [`tsconfig.json`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html):

```json
{
  "compilerOptions": {
    "downlevelIteration": true
  }
}
```

**Comment by trotyl** [comment]
Turing on `downlevelIteration` would change the output of all `for-of` loops to use additional runtime helper, not only ones with `Iterable`. This would cause significant slow down in `Array` loops, which occurs far more than `Set` loops.

It's a common convention to not use `downlevelIteration` in library, but freely in application as long as not being CPU important.
