### ISSUE TITLE
Broken link to XSS sanitizing HTML

### ISSUE THREAD

**Issue by elboukhari** [angular/angular#27773]
# 📚 Docs or angular.io bug report

### Description

The message logged in the console:
`WARNING: sanitizing HTML stripped some content (see http://g.co/ng/security#xss).`

The two symbols ). are included as a part of the link. They broke it !

### What's the affected URL?**
The code is under the `core.js` file at this lines:

<code><pre>
 if (isDevMode() && sanitizer.sanitizedSomething) {
            console.warn('WARNING: sanitizing HTML stripped some content (see http://g.co/ng/security#xss).');
        }
</code></pre>

**Comment by elboukhari** [comment]
Sorry, as I mentioned at the first post yes the resulting url contains at its end those two symbols ")."

**Comment by pkozlowski-opensource** [comment]
@elboukhari could you please provide a minimal reproduce scenario in a stackblitz and indelicate a browser used, as requested in the issue template?

I've just did `console.warn('WARNING: sanitizing HTML stripped some content (see http://g.co/ng/security#xss).')` in a various browsers and tried to click on the http://g.co/ng/security#xss link. Results:
* Chrome lands me correctly on http://g.co/ng/security#xss
* FFox uses the `https://angular.io/guide/security#xss).` as the link (notice `).` at the end.

So it seems that this error message doesn't lead to a clickable link in all browsers... We should probably change it to sth else, ex.: `WARNING: sanitizing HTML stripped some content, see http://g.co/ng/security#xss`

To be modified in the code and tests:
* https://github.com/angular/angular/blob/50a91ba28c857b1f22dc84e7db2110e2a8a3e004/packages/core/src/sanitization/html_sanitizer.ts#L253
* https://github.com/angular/angular/blob/50a91ba28c857b1f22dc84e7db2110e2a8a3e004/packages/core/test/sanitization/html_sanitizer_spec.ts#L66
* https://github.com/angular/angular/blob/50a91ba28c857b1f22dc84e7db2110e2a8a3e004/packages/core/test/sanitization/html_sanitizer_spec.ts#L141

**Comment by pkozlowski-opensource** [comment]
PRs welcomed!

**Comment by dariobraun** [comment]
Fixed in #27982
