### ISSUE TITLE
angular/elements complicated @input parameter cannot be accessed in ngOnInit

### ISSUE THREAD

**Issue by arwindgao** [angular/angular#27771]
Hello everyone
Now i am trying to package my angular component to js via @angular/element 7.0
In my situation, i had defined a interface parameter with my ng component, so i need to pass it from js page. i refer to this link: https://stackoverflow.com/questions/50793080/angular-elements-pass-a-complicated-input-to-my-web-component and make it works.
Now my question is i can get the @Input complicated parameters on ngOnChanges event, if i want to do some works in ngOnInit, and i find the @Input parameters is undefined. 
Can anyone help on this or this is a unsupported way? Thanks in advanced.

Here my sample code:
Angular components:

**Comment by arwindgao** [comment]
export class AppComponent implements OnInit, OnChanges {
  title = 'angular-elements';
  @Input() name = '111';

  ngOnInit(): void {
    console.log(this.name);
  }

  ngOnChanges(): void {
    console.log(this.name);
  }
}

Index.html

<body>
  
  <app-message ></app-message>

  <script type="text/javascript" src="runtime.js"></script>
  <script type="text/javascript" src="polyfills.js"></script>
  <script type="text/javascript" src="styles.js"></script>
  <script type="text/javascript" src="scripts.js"></script>
  <script type="text/javascript" src="vendor.js"></script>
  <script type="text/javascript" src="main.js"></script>

  <script>
      let wrk = document.querySelector('app-message');
      wrk.name = {name:'dj3'};
    </script>
</body> 

In ngOnInit event : name = '111'
In ngOnChanges event : name = {name:'dj3'}
Can I get the name = {name:'dj3'} in ngOnInit event?

**Comment by arwindgao** [comment]
export class AppComponent implements OnInit, OnChanges {
title = 'angular-elements';
@input() name = '111';

ngOnInit(): void {
console.log(this.name);
}

ngOnChanges(): void {
console.log(this.name);
}
}

Index.html

<script type="text/javascript" src="runtime.js"></script> 
<script type="text/javascript" src="polyfills.js"></script> 
<script type="text/javascript" src="styles.js"></script>
 <script type="text/javascript" src="scripts.js"></script>
 <script type="text/javascript" src="vendor.js"></script> 
<script type="text/javascript" src="main.js"></script> 
<script>
 let wrk = document.querySelector('app-message');
 wrk.name = {name:'dj3'}; 
</script>

So
In ngOnInit event : name = '111'
In ngOnChanges event : name = {name:'dj3'}
Is anyway I can also get the name = {name:'dj3'} in ngOnInit event?

**Comment by arwindgao** [comment]
<script type="text/javascript" src="runtime.js"></script> <script type="text/javascript" src="polyfills.js"></script> <script type="text/javascript" src="styles.js"></script> <script type="text/javascript" src="scripts.js"></script> <script type="text/javascript" src="vendor.js"></script> <script type="text/javascript" src="main.js"></script> <script> let wrk = document.querySelector('app-message'); wrk.name = {name:'dj3'}; </script>

**Comment by arwindgao** [comment]
<script type="text/javascript" src="runtime.js"></script> 
<script type="text/javascript" src="polyfills.js"></script> 
<script type="text/javascript" src="styles.js"></script>
 <script type="text/javascript" src="scripts.js"></script> 
<script type="text/javascript" src="vendor.js"></script> 
<script type="text/javascript" src="main.js"></script> 
<script>
 let wrk = document.querySelector('app-message'); 
wrk.name = {name:'dj3'}; 
</script>

**Comment by arwindgao** [comment]
can anybody help on this? :-(

**Comment by qkhanhpro** [comment]
> Hello everyone
> Now i am trying to package my angular component to js via @angular/element 7.0
> In my situation, i had defined a interface parameter with my ng component, so i need to pass it from js page. i refer to this link: https://stackoverflow.com/questions/50793080/angular-elements-pass-a-complicated-input-to-my-web-component and make it works.
> Now my question is i can get the @input complicated parameters on ngOnChanges event, if i want to do some works in ngOnInit, and i find the @input parameters is undefined.
> Can anyone help on this or this is a unsupported way? Thanks in advanced.
> 
> Here my sample code:
> Angular components:

Hello arwindgao,

I got into the same problem trying to access angular element on init / in template
I created an issue here https://github.com/angular/angular/issues/29050 and stackblitz here
https://stackblitz.com/edit/is-not-a-function

does that demonstrate the same problem you have?
Did you ever success to resolve it?

**Comment by MirkoTV** [comment]
Any help with this one?

I got the same problem @arwindgao is facing here, I thought ngOnChanges would will save the day, but I noticed that if I run something more complicated in the ngOnChanges method like changing the view this is not reflected in the UI  (except for the properties decorated with @Input, They are correctly updated in the UI). I think it is because chageDetection is not being performed since ngOnChanges was called outside the scope of Angular

**Comment by dimarafonseca** [comment]
I'm having something similar, but it only happens if I use Angular Elements in Angular Project. I noticed in my ngAfterViewInit event the @inputs() properties are always undefined. However, if I use these angular custom elements in a regular HTML page it works fine and the @inputs() in my ngAfterViewInit event have value.
https://github.com/dimarafonseca/custom-angular-example - example with two projects: A custom elements and the other one using this element.
Thanks

**Comment by robwormald** [comment]
See https://github.com/angular/angular/issues/18909 for the root cause of this.

**Comment by vishranti5** [comment]
Hi, i am also facing same issue, any updates on same?
I have used angular element to create webcomponent and used this webcomponent in base application. while passing complex object from base application as input property, i get this object on Onchanges in webcomponent but Oninit it is undefined

**Comment by dimarafonseca** [comment]
Hi @vishranti5, I didn't have any updates about this issue, however, for now, I am doing @Input() set nameOfProperty(value: any) {} and then I set the value for my property. it's working for me. 
![image](https://user-images.githubusercontent.com/20342790/60547618-ca7acc80-9ce5-11e9-89fc-fc9f1ade9269.png)

**Comment by vishranti5** [comment]
Hi @dimarafonseca  i get object as input propery in ngOnchanges and  input properties getter setter, however i need it in ngOnInit. On ngOninit it is undefined.

The reason for this is for angular elements ngOninit fires first then input properties getter setter and then ngOnchanges.
Not sure why this happens, But i need input propert in ngOnInit

**Comment by dimarafonseca** [comment]
Hi @vishranti5, I'm sorry to hear that, this was the only that I found to work for me, I applied the routine that I had on ngOnInit on my setter. because I was having the issue as you mentioned in the ngOnInit method. It seems an issue on rendering page because if you create a setTimeout in your ngOnInit you can have the values, but it's a bad solution.

**Comment by paulogr** [comment]
@vishranti5 as mentioned on https://github.com/angular/angular/issues/27771#issuecomment-497118043 it's about how you instantiate your webcomponent.

could you show how are you loading your webcomponent?

**Comment by vishranti5** [comment]
Hi @paulogr please find below code snippets.

Inside base application, appcomponent is main component (bootstrapping one), here we added web-components reference ( java script file) dynamically

**app.component.t**s -
ngOnInit(): void {
    const content = document.getElementById('content');
    const findingsPathApp = document.createElement('script');
    findingsPathApp.src = environment.microApps.findingsPath;
    content.appendChild(findingsPathApp);
}

**app.component.html** -
    <ul class="nav nav-tabs masterTabs">
            <li><a routerLink="/findings" >Findings <span class="countNo">12</span></a></li>
    </ul>         
 <div id="content"></div>

**app-routing.Module.ts** -
    
const routes: Routes = [
  {path : 'findings', component : FindingsComponent},
];

@NgModule({
  imports: [RouterModule.forRoot(routes,{useHash: true})],
  exports: [RouterModule]
})
export class AppRoutingModule { }


**Findings.component.ts** -

interface Context {
  clientId: string ;
  tenantId: string ;
  token: string ;
  archimedesbackend: string ;
  applicationbackend: string ;
}
@Component({
  selector: 'app-findings',
   templateUrl: './findings.component.html',
  styleUrls: ['./findings.component.sass']
})

export class FindingsComponent implements OnInit, OnChanges {
  context: any;
  constructor() {
    this.context = {
    clientId: 'abc',
    tenantId: 'xyz',
    token: 'qwe',
    archimedesbackend: 'https://www.google.com',
    applicationbackend: 'https://www.facebook.com'
  };
}
  ngOnInit() {
    console.log('inside parent');
    console.log(this.context);
  }
  ngOnChanges() {
    console.log('parent onchanges');
    console.log(this.context);
  }
}

**findings.component.html** - where we added webcomponent and passed input parameter
<archimedes-findings [context]="this.context"></archimedes-findings>


Now we have microapplication where we created Webcomponent ( archimedes-findings),

**app.module.ts** -

@NgModule({
  declarations: [
    AppComponent,
    FindingListComponent
  ],
  imports: [],
  providers: [],
  bootstrap: [],
  entryComponents: [FindingListComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],

})
export class AppModule {
  constructor(private injector: Injector) {

  }
  ngDoBootstrap() {
  const strategyFactory = new ElementZoneStrategyFactory(FindingListComponent, this.injector);
  const findingsElement = createCustomElement(FindingListComponent, { injector: this.injector, strategyFactory });
    customElements.define('archimedes-findings', findingsElement);
  }
}

**FindingListComponent. ts**

import { Component, OnInit, ViewEncapsulation, Input, OnChanges, SimpleChanges, SimpleChange, ChangeDetectorRef } from '@angular/core';
import { FindingService } from '../shared/finding.service';
import {environment} from './../../../environments/environment';
@Component({
  selector: 'app-finding-list',
  templateUrl: './finding-list.component.html',
  styleUrls: [
    './finding-list.component.css',
  ],
   encapsulation: ViewEncapsulation.ShadowDom
})
export class FindingListComponent implements OnInit, OnChanges {
  varcontext: any;

  @Input()
  public set context(value: any) {
    this.varcontext = value;;
  }

  public get context() {
    return this.varcontext;
  }
  constructor(private findingService: FindingService) {
   }

 ngOnChanges() {
   }

  ngOnInit() {
    console.log('inside childs oninit');
    console.log(this.context);
  }
}

Problem is - if i click on finding link, (which i mentioned in base components app.components.html page) i get input property (context object) inside input getter setter and on ngOnchanges.

But if i provide route ( https://localhost/findings ) through browser directly i dont get input property (context object ) inside ngOninit, In this case ngonchanges and input properties getter setter never fires. 
Also event occures are - base components oninit (findings), webcomponents oninit (findinglist). and In this case inside base application finding components templates display first then its constructor and then oninit.  while if i click on anchor tab constructor fires first

Any idea about this?
