### ISSUE TITLE
NgFor loses focus on reorder to lower index

### ISSUE THREAD

**Issue by diminutivesloop** [angular/angular#27782]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?
No

### Description
When an element within an `ngFor` is re-ordered and that element contains the currently focused control, focus is not preserved if the re-ordering moves the element to a lower index (i.e. towards the top of the list). However if the element is re-ordered to a higher index, focus on the control is preserved. This happens whether or not a `trackBy` function is used.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-mmiwej

1. Select the **Down** radio button.  
2. Tab to the **Reorder** button for item 1.
3. Press enter.
=> Item 1 is moved to position 2 and the **Reorder** button remains focused.
4. Select the **Up** radio button.  
5. Repeat steps 2-3.
=> Item 1 is moved back to position 1 and the **Reorder** button loses focus.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.0.6
Node: 8.11.3
OS: win32 x64
Angular: 7.0.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        7.0.6
@angular/cli                      7.0.6
@ngtools/webpack                  6.0.3
@schematics/angular               7.0.6
@schematics/update                0.10.6
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.8.3
</code></pre>

**Comment by mlc-mlapis** [comment]
@diminutivesloop ... it's the expected behavior.

**Comment by mhevery** [comment]
Thanks for the repro application. Please include detailed steps of what to click on and what to expect as I interact with the application. As of right now I see an app, but I don't know how to reproduce your problem.

**Comment by pkozlowski-opensource** [comment]
As @mlc-mlapis suggested this is a "classical" case for `trackBy`: https://stackblitz.com/edit/angular-r59b1m?file=src%2Fapp%2Fapp.component.html

More info here: https://angular.io/api/common/NgForOf#ngForTrackBy

Closing as a support request.

**Comment by diminutivesloop** [comment]
Sorry for the lack of repro details. I've added detailed steps and I've updated the stackblitz demo to show that adding a custom `trackBy` function does not solve this issue. Please consider re-opening.

**Comment by trotyl** [comment]
It's still the expected behavior, **reorder** is just an illustration, this operation doesn't exist at all. When talking about fake "reorder A & B", it could be either:

+ Keep A untouched, detach B, insert B before A;
+ Keep B untouched, detach A, insert A after B;

There must be some node being manipulated in the DOM, and in a declarative system, the underlying operation should never be depend on or take control with.

**Comment by diminutivesloop** [comment]
Ok that makes sense, but if the node is really being destroyed then why are any edits I've made to the adjacent text field preserved when the focus state isn't? The text field uses a one-way value binding so if the nodes are being re-created shouldn't its value also be reset to the bound value?

**Comment by diminutivesloop** [comment]
Got it.

**Comment by pkozlowski-opensource** [comment]
Thnx @trotyl
