### ISSUE TITLE
Adding RouterModule breaks Ivy apps using platformBrowserDynamic

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#27794]
# 🐞 bug report

### Affected Package
`StaticInjector` in `@angular/core`

### Description

When adding the `RouterModule` and use `ngtsc`, together with the usual `platformBrowserDynamic` bootstrapping code causes a runtime error.

## 🔬 Minimal Reproduction
```
git clone https://github.com/alan-agius4/ivy-router-issue.git
npm i
node_modules\.bin\ivy-ngcc
ng serve --prod
```

## 🔥 Exception or Error
Runtime error:
```
core.js:15268 ERROR TypeError: Cannot read property '__source' of undefined
    at t.get (core.js:8532)
    at t.get (core.js:8894)
    at core.js:1207
    at Ne (core.js:1207)
    at Object.t_Factory [as factory] (ngInjectableDef.js:8)
    at t.hydrate (core.js:9017)
    at t.get (core.js:8888)
    at core.js:1207
    at Ne (core.js:1207)
    at Fe (core.js:1264)
```

## 🌍  Your Environment

**Angular Version:**
```
Angular CLI: 7.2.0-rc.0
Node: 11.0.0
OS: win32 x64
Angular: 7.2.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.0-rc.0
@angular-devkit/build-angular     0.12.0-rc.0
@angular-devkit/build-optimizer   0.12.0-rc.0
@angular-devkit/build-webpack     0.12.0-rc.0
@angular-devkit/core              7.2.0-rc.0
@angular-devkit/schematics        7.2.0-rc.0
@ngtools/webpack                  7.2.0-rc.0
@schematics/angular               7.2.0-rc.0
@schematics/update                0.12.0-rc.0
rxjs                              6.3.3
typescript                        3.2.2
webpack                           4.23.1
```

**Anything else relevant?**
At first glace, it doesn't look like this is a CLI issue as disabling Optimizations and Build Optimizer, yields the same result.

**Comment by alexzuza** [comment]
Looks like ngcc issue since it can't transform `_decorate` statement from `Location` to `Location.ngInjectableDef` due to the fact that Location contains static methods that result in 

**fesm5/common.js**
```
Location = Location_1 = __decorate([
        Injectable(),
```
And ngcc compiler is trying to recognize it as follows:

![ngcc](https://user-images.githubusercontent.com/4223314/50573138-700cbc00-0de7-11e9-99ef-fdb460335626.png)
