### ISSUE TITLE
Can't bind to 'controlGroup' since it isn't a know property of the 'div' element

### ISSUE THREAD

**Issue by Ludo09** [angular/angular#2779]
Hi everyone,

I'm trying to build a small app using Angular2.0.0-alpha.28 (with corresponding .d.ts) + TypeScript 1.5.0-beta and I got the following message:

Can't bind to 'controlGroup' since it isn't a know property of the 'div' element and there are no matching directives with a corresponding property
index.html

```html
<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<title>Angular 2</title>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.min.css" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" />

<script src="https://github.jspm.io/jmcriffey/bower-traceur-runtime@0.0.87/traceur-runtime.js"></script>
<script src="https://jspm.io/system@0.16.js"></script>
<script src="https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js">    </script>
</head>
<body>

<radar>Loading...</radar>
<script>System.import('radar-view');</script>

</body>
</html>
```

radar-view.ts

```typescript
/// <reference path="typings/angular2/angular2.d.ts" />
import {Component, View, bootstrap} from 'angular2/angular2';
import {FormBuilder, Validators, formDirectives, ControlGroup} from 'angular2/angular2';

@Component({
selector: 'radar',
appInjector: [FormBuilder]
})
@View({
template: '<div [control-group]="form"><input control="levels">    {{form.controls.levels.value}}</div>',
directives: [formDirectives]
})
export class RadarView {
form: ControlGroup;
builder: FormBuilder;

constructor(builder: FormBuilder) {
    this.builder = builder;
    this.form = builder.group({
        levels: ["5"]
    });
}
}

bootstrap(RadarView);
```

compiling

tsc --watch --target es5 --module commonjs --emitDecoratorMetadata
Also when I try to use validators.required it looks like it's not found either:

```typescript
this.form = builder.group({
    levels: ["5", Validators.required]
});
```
Error:(21, 38) TS2339: Property 'required' does not exist on type 'typeof Validators'.

Any idea about what's wrong with my code?

**Comment by ericmdantas** [comment]
Try using ```@Inject```:

```js
/// <reference path="typings/angular2/angular2.d.ts" />
import {Component, View, bootstrap} from 'angular2/angular2';
import {FormBuilder, Validators, formDirectives, ControlGroup} from 'angular2/angular2';
import {Inject} from 'angular2/di';

@Component({
selector: 'radar',
appInjector: [FormBuilder]
})
@View({
template: '<div [control-group]="form"><input control="levels">    {{form.controls.levels.value}}</div>',
directives: [formDirectives]
})
export class RadarView {
form: ControlGroup;
builder: FormBuilder;

constructor(@Inject(FormBuilder) builder: FormBuilder) {
    this.builder = builder;
    this.form = builder.group({
        levels: ["5"]
    });
}
}

bootstrap(RadarView);
```

**Comment by Ludo09** [comment]
I tried with ```typescript import {Inject} from 'angular2/angular2'``` +  ```typescript @Inject(FormBuilder)``` as you suggested and it doesn't work.

Regarding ```typescript Validators.required``` I guess it's simply missing from angular2.d.ts

**Comment by pkozlowski-opensource** [comment]
The error says what the problem is - there is no `controlGroup` property on a div and there is no matching directive with this property, since the `NgControlGroup` has only `ng-control-group` binding, see: https://github.com/angular/angular/blob/3e6503789ff445b765996bcb530e4ad88ace19e0/modules/angular2/src/forms/directives/ng_control_group.ts#L54

In short: change `<div [control-group]="form">` to `<div [ng-control-group]="form">` to get rid of the error reported in this issue.

**Comment by Ludo09** [comment]
Fair enough but now I'm getting ```no provider for Container! ($__0 -> ControlContainer) angular2.dev.js:19379``` on the console.

Btw should I remove ```@Inject(FormBuilder)```?

**Comment by ericmdantas** [comment]
Also, I think you should add a form to your template, otherwise I'd say the form won't work correctly with angular2.

[Here's a working component](https://github.com/ericmdantas/angular2-typescript-todo/blob/master/todo/components/todo.ts) and its [html](https://github.com/ericmdantas/angular2-typescript-todo/blob/master/todo/components/todo.html).
