### ISSUE TITLE
Issue with @Component decorator extension in production build

### ISSUE THREAD

**Issue by LegendaryMike** [angular/angular#27801]
# 🐞 bug report

### Description

I am using the following pattern to extend the @Component decorator
I am doing this to inject ServiceBagService to all my components since I need a separate instance of it 
Perhaps there is a better way, but this is what I found in order not to forget it on any component

```typescript
import { Component } from '@angular/core';
import { ServiceBagService } from './ServiceBag';
function ComponentEx(args: any = {}): (cls: any) => any
{
    args.providers = [ServiceBagService];
    return Component(args);
}
export default ComponentEx;
```

and then on my components I use @ComponentEx decorator instead of @Component:

```typescript
@ComponentEx({
    selector: 'app-prospect',
    templateUrl: './prospect.component.html',
    styleUrls: ['./prospect.component.scss'],
})
export class ProspectComponent extends BasePageComponent<Prospect, State>
{
...
}
```

This works fine in development, but when doing a production build with ng build --prod (using default config for pretty much everything) I get this error message:

```
ERROR in : Unexpected value 'ProspectListComponent in G:/Projects/Leader/Angular/ClientApp/src/pages/prospect/prospectlist.component.ts' declared by the module 'AppModule in G:/Projects/Leader/Angular/ClientApp/src/_zzz/Main.ts'. Please add a @Pipe/@Directive/@Component annotation.
```

Using angular 6

**Comment by mhevery** [comment]
Extending decorators is not supported by Angular AOT. Works as intended.

**Comment by LegendaryMike** [comment]
Can you suggest a different solution to acheive that purpose?
