### ISSUE TITLE
Allow linebreaks in i18n translations

### ISSUE THREAD

**Issue by armaserg** [angular/angular#27809]
# 🚀 feature request

### Description

This problem already was discussed here: https://github.com/angular/angular/issues/25242
But it was closed without resolving it. Also, @vicb in https://github.com/angular/angular/pull/23053 wrote:
> We don't monitor close PRs nor issues

so, I have to open new ticket for this.
Translations for different languages could have different length.
In some cases original english phrase nicely fits in one line, but german translation could be much longer, so for site design it will be better to break it to 2 lines after specific word. But it is not possible :(

If I add "`<ph name="LINE_BREAK"><ex>&lt;br&gt;</ex></ph>`" - build will throw "parse errors: Unexpected tag"
If I add "`<br>`" or "`&lt;br&gt;`" - it will add escaped version of tag.

### Describe the solution you'd like
Allow `<br>` tags in translations. Maybe also `<b>` and `<i>` tags.
`<i>` tag - because in some translations we should italicize foreign words and phrases https://intelligentediting.com/blog/how-to-decide-if-you-should-italicize-foreign-words-and-phrases/

**Comment by ocombe** [comment]
@AndrewKushnir do you know if it's possible in ivy with runtime i18n to add a line break to a translation with something like `\n`?

**Comment by trotyl** [comment]
@ocombe One can just apply [`white-space`](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) to render `\n` as line break, no need for special handing in the source.

**Comment by ocombe** [comment]
yes, I just wanted to make sure that they weren't striped or anything

**Comment by trotyl** [comment]
Yep, they're also stripped by default as if being the original source code, so `ngPreserveWhitespaces` or equivalent configuration is required to force preserve them.

**Comment by AndrewKushnir** [comment]
As @trotyl mentioned, the combination of [ngPreserveWhitespaces](https://angular.io/api/core/Component#preserving-whitespace) and [white-space](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) CSS rule should help achieve the necessary result. Thank you.
