### ISSUE TITLE
Angular 6 Post Method Error

### ISSUE THREAD

**Issue by timusiiit123** [angular/angular#27816]
Error:  
HttpErrorResponse {headers: HttpHeaders, status: 200, statusText: "OK", url: "**myCustomURL**", ok: false, …}
error: {error: SyntaxError: Unexpected token s in JSON at position 0 at JSON.parse (<anonymous>) at XMLHttp…, text: "success"}
headers: HttpHeaders {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
message: "Http failure during parsing for **myCustomURL**"
name: "HttpErrorResponse"
ok: false
status: 200
statusText: "OK"
url: "**myCustomURL**"
__proto__: HttpResponseBase

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by timusiiit123** [comment]
I did not find the answer by searching. Can you help me or provide me some link regarding this?

**Comment by mlc-mlapis** [comment]
@timusiiit123 ... please respect, that just showing the error as above has really no sense for anybody.

... btw: ` Unexpected token s in JSON at position 0` generally means that the response content is not parse-able JSON string ... which is the default action of `HttpClient`, if it's not specified otherwise.

**Comment by timusiiit123** [comment]
@mlc-mlapis I know what that means. I want to know how to do post in angular6. I followed the Angular Docs and I did not get any response and when I try to call the API in Postman that works. I means no API error. I want to know just the Angular6 Post Method.
