### ISSUE TITLE
_ngcontent-* attribute is used as a selector even for polyfill-non-strict{} styles for custom DOM elements

### ISSUE THREAD

**Issue by psunkari** [angular/angular#2782]
/cc @rkirov, @vicb

**Comment by mhevery** [comment]
This issue needs better explanation. What is the seen vs expected behavior. What should be done about this.

**Comment by rkirov** [comment]
I talked with @matanl offline, he was referring to this feature we had in angular.dart 1 - https://github.com/angular/angular.dart/wiki/CSS-Shim.

**Comment by rkirov** [comment]
We already have a similar feature implemented `polyfill-unscoped-rule`, see https://github.com/angular/angular/blob/master/modules/angular2/test/render/dom/shadow_dom/shadow_css_spec.ts#L120 

The difference is that `polyfill-non-strict` shim the upper bound on CSS encapsulation  - a component is protected from its DOM's parents CSS, but its CSS can affect children. While `polyfill-unscoped-rule` leaves the CSS rule unshimmed, thus potentially affecting ancestors and descendants.

Would using `polyfill-non-strict` get you unblocked for now?

**Comment by rkirov** [comment]
AFAIKT, polyfill-non-strict is no longer supported in webcomponents.js - https://github.com/webcomponents/webcomponentsjs/blob/master/src/ShadowCSS/ShadowCSS.js

We have the mechanism for non-strict polyfilling, but it is exposed as a global flag, not configurable per rule - https://github.com/angular/angular/blob/master/modules/angular2/src/render/dom/shadow_dom/shadow_css.ts#L140

However, I think that the syntax would be more consistent with polyfill-unscoped-rule and the other existing modifiers. 

What used to be 
```
polyfill-non-strict {} one, two { color: red }
```
should be
```
polyfill-non-strict {content: `one, two`; color: red }
```

The resulting CSS would still be
```
component-name one, component-name two { color: red }
```

@vicb Any info on why polyfill-non-strict was not implemented in webcomponents and why didn't it use 'content' in angular.dart 1.

**Comment by rkirov** [comment]
On second thought, it looks that `:host one` would translate to `component-name one` and basically provide the same functionality as `polyfill-non-strict`, so I think that should be used going forward. Ideally, I would like too keep feature-parity between our port of webcomponents and their repo.

@jmesserly What was the reason behind removing `polyfill-non-strict` from webcomponents.js? Also, is `:host` the intended replacement?

**Comment by jmesserly** [comment]
> @jmesserly What was the reason behind removing polyfill-non-strict from webcomponents.js? Also, is :host the intended replacement?

Hey! I'm pretty familiar with Shadow DOM, but not as familiar with Shadow CSS polyfill. I can try to help though.

I don't recall a polyfill-non-strict in Shadow CSS. Is it possibly an Angular feature? Could just be my memory. What I recall: there was a lot of spec churn on Shadow CSS. It may be helpful to look at the current spec draft: http://dev.w3.org/csswg/css-scoping/

Also Polymer 1.0 docs cover the current state of things in webcomponents-lite.js: https://www.polymer-project.org/1.0/docs/devguide/styling.html

> This issue needs better explanation. What is the seen vs expected behavior. What should be done about this.

yeah, I'm kind of in the same boat ... maybe an example would help? e.g. given this HTML+CSS, I expect this to happen, but this is happening instead.

**Comment by rkirov** [comment]
You are right, looks like polyfill-non-strict and polyfill-unscoped-next-selector were custom angular polyfill- extensions added in angular.dart 1.x - https://github.com/angular/angular.dart/pull/1556.

What I gathered from @vsavkin is that at the time they were needed as workarounds for incorrect shimming of `foo::shadow bar` selectors (which is exactly issue [2932](https://github.com/angular/angular/issues/2932)).

@jmesserly I don't see any mention of `polyfill-` directives at https://www.polymer-project.org/1.0/docs/devguide/styling.html, does that mean you are planning on removing them?

**Comment by jmesserly** [comment]
> @jmesserly I don't see any mention of polyfill- directives at https://www.polymer-project.org/1.0/docs/devguide/styling.html, does that mean you are planning on removing them?

Ah, I can't answer about plans and stuff, since it's not my code :). I'm not super familiar with the polyfill, my knowledge is more at the spec level (if you want to know about Shadow DOM polyfill, though, I know plenty about that one). But we can try to read it together and figure it out maybe?

There's a comment explaining them, though:
https://github.com/webcomponents/webcomponentsjs/blob/fee543f9cc377a8fd4b7d37f5a9f124fca027651/src/ShadowCSS/ShadowCSS.js#L121

looks like they're to help deal with cases where you've got a native ShadowDOM available, and then you've got some polyfill selectors which are different. Historically there was a lot of churn in the spec, so I imagine having some polyfill helpers was pretty useful.

**Comment by psunkari** [comment]
Currently, when we use emulated shadow root, the CSS is being shimmed

**Comment by psunkari** [comment]
As of now polyfill-unscoped-rule does not seem to be doing anything.

polyfill-unscoped-rule { content: '.table-header';
  min-height: 56px;
  background-color: white;
}

comes out as 

polyfill-unscoped-rule[_ngcontent-6] { content: '.table-header';
  min-height: 56px;
  background-color: white;
}

https://github.com/angular/angular/blob/master/modules/angular2/test/render/dom/shadow_dom/shadow_css_spec.ts#L119

**Comment by rkirov** [comment]
@jmesserly, thanks for the offering to work through the shim. After some talk with @psunkari looks like `polyfill-unscoped-rule` is good enough for their usecase, and we are investigating whether it is implemented properly in our port. If we discover something that is also broken on webcomponentsjs I will file a bug back with you guys.

@psunkari The original rule is kept (and shimmed), not sure if that is of much use, but it is nice to see for debugging. However, the unscoped output is appended to the end of the style tag.

https://github.com/angular/angular/blob/master/modules/angular2/src/render/dom/shadow_dom/shadow_css.ts#L234

**Comment by psunkari** [comment]
After taking a look at the code/output with @rkirov, there seems to be a small bug that caused only the last polyfill-unscoped-rule to be appended to the style tag.

https://github.com/angular/angular/blob/master/modules/angular2/src/render/dom/shadow_dom/shadow_css.ts#L261 should append the text to string instead of assigning it.
