### ISSUE TITLE
Angular 5 to Angular 6, global is not defined

### ISSUE THREAD

**Issue by Xen3r0** [angular/angular#27823]
# 🐞 bug report
### Affected Package
"@angular/core": "^6.1.10"
"@angular/cli": "~7.0.2"

### Is this a regression?
Yes, it's working in Angular 5

### Description
I want update my application from angular 5 to angular 6, but i have a error about global variable.

## 🔬 Minimal Reproduction
Get https://github.com/Xen3r0/angular5-upgrade repository, npm install & npm run start.

## 🔥 Exception or Error
<pre><code>
Uncaught ReferenceError: global is not defined
    at Object../node_modules/intl/index.js (polyfills.js:7249)
    at __webpack_require__ (runtime.js:79)
    at Module../src/polyfills.ts (polyfills.js:15246)
    at __webpack_require__ (runtime.js:79)
    at Object.1 (polyfills.js:15286)
    at __webpack_require__ (runtime.js:79)
    at checkDeferredModules (runtime.js:46)
    at Array.webpackJsonpCallback [as push] (runtime.js:33)
    at polyfills.js:1
</code></pre>

**Comment by mnahkies** [comment]
You may be able to solve this by adding a snippet like this to your index.html:
```
if(window['global'] === undefined){ window['global'] = window }
```

In terms of root cause, this is due to the webpack configuration not enabling node js polyfills, as can be seen here: https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts#L123

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
