### ISSUE TITLE
ngc compiler points to relative path

### ISSUE THREAD

**Issue by mitsoe** [angular/angular#27825]
# 🐞 bug report

### Affected Package
Issue is caused by the NGC compiler

### Description
When running the ng compiler the output files have paths pointing towards relative paths in the parents node_modules folder.

import * as i2 from "../../../../node_modules/@angular/router/router.ngfactory";

This appears to be happening when the module that is included in the project contains entryComponents.

We are expecting that this should point towards @angular/router in this specific case.

## 🔬 Minimal Reproduction

Clone https://github.com/mitsoe/compile-issue
npm install
npm run build
you can see the ngc output in the dist folder. this contains the relative paths to the node_modules of its parent.

**Comment by alxhub** [comment]
This is by design.

The `node_modules` directory there isn't your actual `node_modules`, but a parallel directory that contains generated ngfactory files.
