### ISSUE TITLE
Child canLoad executes before parent canActivate on child reload.

### ISSUE THREAD

**Issue by Msender** [angular/angular#27826]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/router

### Description
When using lazy loading with a canLoad guard, if we reload the page on the child (lazy loaded) route, the child canLoad gets called before the parent route canActivate.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-zhyqwj, click on loadChild then reload page and watch console, output is in this order: 
**ChildGuard canLoad
AppGuard canActivate
AppResolver resolve**

even though the order of the routes are like this:

`const routes: Routes = [
  {
    path: '',
    component: AppComponent,
    resolve: [AppResolver],
    children: [
      {
        path: '', canActivate: [AppGuard], children: [
          {
            path: 'child',
            loadChildren: 'app/child/child.module#ChildModule',
            canLoad: [ChildGuard]
          }
        ]
      }
    ]
  }
];`

## 🌍  Your Environment

**Angular Version:**
7.0.1

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

<br>

The logic here is we need to know what routes are planned to be activated. All loading happens while the route is being recognized since we don't even know if we have a valid route until the configs are loaded.

**Comment by jeffaxial** [comment]
@jasonaden I am also very confused why this works this way. If I put a guard on a parent route, my _intention_ is to prevent further action for the guarded route AND its children if it resolves false. If my child has a guard, what is the *real life, practical use case* for the guard running, and *before* the parent?

My personal use case and conflict with the ordering problem: I'm trying to implement some general application permissions. I would expect a parent resolver or guard to allow me to set some permissions before a child needs to check against them. But this isn't the case.
