### ISSUE TITLE
HttpClient.get() linked to https://angular.io instead of actual link

### ISSUE THREAD

**Issue by karthick-manoharan** [angular/angular#27820]
# 📚 Docs or angular.io bug report

### Description

All links for `HttpClient.get()` from [HttpClient guide](https://angular.io/guide/http) points to www.angular.io

### What's the affected URL?**
https://angular.io/guide/http

### Reproduction Steps**
Search for `HttpClient.get()` and check the links

### Expected vs Actual Behavior**
 Actual link for `HttpClient.get()` should be https://angular.io/api/common/http/HttpClient#get

### Browser info

Chrome 71.0.3578.98
macOS High Sierra

**Comment by petebacondarwin** [comment]
The reason the links are not being generated correctly is because the aliases for members are broken in the current dgeni-packages. I will have a PR and a new release of dgeni-packages to fix it shortly.

**Comment by petebacondarwin** [comment]
#27864 fixes this problem. See https://pr27864-becdd44.ngbuilds.io/guide/http#type-checking-the-response
