### ISSUE TITLE
ngOnInit finishes before all microtasks

### ISSUE THREAD

**Issue by DenisBarzanov** [angular/angular#27838]
# 🐞 bug report

### Description

  
The view gets parsed before `ngOnInit` is finished if there is async code in the `ngOnInit`, it thinks the ngOnInit is finished and starts parsing the view. I've already asked this on 
[StackOverflow](https://stackoverflow.com/questions/53925659/angular-material-table-typeerror-cannot-read-property-cars-of-undefined), which includes a rich description of the issue. 

Basically I have a function: 
<pre><code>   async ngOnInit() {
    console.log('before getting cars: ');
    console.log(this.cars);
    this.cars = await this.carService.getCars().toPromise();
    console.log('got cars:');
    console.log(this.cars);
    this.dataSource = new CarsTableDataSource(this.paginator, this.sort, this.cars);
  }
</pre></code>
which awaits some objects from a database and then sets a `dataSource` for a table, but there is an error on this line of the html:
<pre><code>[length]="dataSource.cars.length"
</pre></code>
The error happens, because the dataSource is undefined (uninitialized during parsing of template). The template gets parsed after it sees the `await` in the `ngOnInit`
## 🔬 Minimal Reproduction

https://stackblitz.com/edit/github-wmxs4k

## 🔥 Exception or Error
<img width="100%" src="https://i.stack.imgur.com/cmBdK.png" />
<img width="100%" src="https://i.stack.imgur.com/n3EhQ.png" />

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.1.3
Node: 10.14.2
OS: linux x64
Angular: 7.1.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.3
@angular-devkit/build-angular     0.11.3
@angular-devkit/build-optimizer   0.11.3
@angular-devkit/build-webpack     0.11.3
@angular-devkit/core              7.1.3
@angular-devkit/schematics        7.1.3
@angular/cdk                      7.2.0
@angular/cli                      7.1.3
@angular/flex-layout              7.0.0-beta.22
@angular/material                 7.2.0
@ngtools/webpack                  7.1.3
@schematics/angular               7.1.3
@schematics/update                0.11.3
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

</code></pre>

**Anything else relevant?**

**Comment by pauldraper** [comment]
Angular does not wait on any promise returned by ngOnInit or any other hook.

If you don't want to render the component's view after the component as been created, you can use `*ngIf` to hide the view until the data is ready.
