### ISSUE TITLE
Make test injector and test component builder (more) agnostic to the test environment

### ISSUE THREAD

**Issue by juliemr** [angular/angular#2783]
The test_lib contains many helpers, but it's closely coupled with the Jasmine-style BDD environment. Decouple where possible - in particular, to enable running with the dart:test package, and to enable running in JavaScript outside of Angular's own repository.

**Comment by juliemr** [comment]
In regards to dart:test:

Most of the things that the test lib does are not generalizable. They are simple functions that wrap around testing functions (like `beforeEach` and `it`). I think there is actually nothing that would be helpful to pull out - we should just have a separate adapter for dart:test.

There are also several matchers and spy functions, which may be nice to have but should be doable with basic dart:test and a mock library (dart recommends mockito).

**Comment by kevmoo** [comment]
Agreeing with @juliemr. It'd be really nice if `guinness` was split into helpers vs the imperative functions.

**Comment by naomiblack** [comment]
@juliemr can you figure out handoff if this one isn't landing before your OOO?

**Comment by zzo** [comment]
is there documentation for how to use test_bed/TestComponentBuilder somewhere?  Personally am only interested in the JS side of things thanks! :)

**Comment by juliemr** [comment]
Update: I am stuck on some injector issues while decoupling - bumping to next milestone.

**Comment by juliemr** [comment]
Here is a working example of a unit test written using dart:test, using the test injector and TestComponentBuilder: https://github.com/juliemr/angular/tree/test-lib-package-2/darttest

Next up I'll be adding useful helpers from test_lib.

**Comment by juliemr** [comment]
Continues to be in progress, see https://github.com/juliemr/angular/tree/test-lib-package-3/modules_dart/angular2_test.

Bumping to 33, since this is non-urgent.

**Comment by jeffbcross** [comment]
Removed this from milestone 34 but left assigned to Julie since it's WIP

**Comment by juliemr** [comment]
This is largely done - most of the actual control is in the `testInjector` now. See https://github.com/angular/angular/issues/7266 for one remaining idea.
