### ISSUE TITLE
[router/testing] `No base href set` errors in tests appear with router

### ISSUE THREAD

**Issue by yd021976** [angular/angular#27831]
Hi All !

I'm submitting a bug relative to closed issue #12295 that seems to partially solve the router module problem: 
> Works fine with karma in "normal" mode
> Doesn't work when in "debug runner" mode (click on the up right "debug" button"

In the case of debugging, the message `Error: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.`

**Comment by jasonaden** [comment]
Hi. Thanks for sending a bug, but please follow the new issue template when creating this bug. I will close this issue, and please follow the template including a reproduction if you want to create a new issue.
