### ISSUE TITLE
how to disable mat row on button click

### ISSUE THREAD

**Issue by Mohit-Purbia** [angular/angular#27835]
i am trying to disable a particular row on click on his action button using angular  and typescript
<-- Code -->
 <ng-container matColumnDef="action">
                  <mat-header-cell *matHeaderCellDef> Action </mat-header-cell>
                  <mat-cell *matCellDef="let element">
                    <button mat-icon-button color="warn" [disabled]="isDisabled(row)"> 
                                        <mat-icon>delete</mat-icon>
                                     </button>

                  </mat-cell>
                </ng-container>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
