### ISSUE TITLE
Navigation in not explicit for a mobile user in the Tour of Heroes Tutorial.

### ISSUE THREAD

**Issue by ninio** [angular/angular#27834]
# 📚 Docs or angular.io bug report

### Description
When a user opens the tutorial from a mobile device (e.g. an Android phone) the side nav is hidden.
Reading through the [Introduction page](https://angular.io/tutorial) the user is left without a link to continue to the next step of the tutorial. 

This is valid for each of the tutorial steps.

### What's the affected URL?**
https://angular.io/tutorial/*

### Reproduction Steps**
Open the tutorial from a phone screen (that is falling in a (@max-width: 992 px;) media query).

### Expected vs Actual Behavior**
A section with "Next step" after each step in the tutorial would make the navigation more intuitive.

</code></pre>

**Comment by ericmartinezr** [comment]
This is being addressed by https://github.com/angular/angular/pull/26065

**Comment by atscott** [comment]
Closing as obsolete. I'm not sure what the previous tutorial looked like exactly, but it sounds as though it was made up of separate pages that needed to be linked together. The tutorial is now just one page so you just scroll down to the next milestone when finishing the previous.
