### ISSUE TITLE
ngcc not running on all files (ESM5)

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#27841]
# 🐞 bug report

### Affected Package
All packages are effected by the output of `ngcc`

### Description

After running `ngcc` via `node_modules/.bin/ivy-ngcc` certain Angular decorators are being retained, this is break production builds with Build Optimzer https://github.com/angular/angular-cli/issues/13261.

## 🔬 Minimal Reproduction

- Run ngcc against a node_modules/@angular directory
- Open node_modules/@angular/platform-browser/esm5/src/browser.js
```ts
var BrowserModule_1;
BrowserModule = BrowserModule_1 = tslib_1.__decorate([
	NgModule({ providers: BROWSER_MODULE_PROVIDERS, exports: [CommonModule, ApplicationModule] }),
	tslib_1.__param(0, Optional()), tslib_1.__param(0, SkipSelf()), tslib_1.__param(0, Inject(BrowserModule_1)),
	tslib_1.__metadata("design:paramtypes", [Object])
], BrowserModule);
return BrowserModule;
```

## 🌍  Your Environment

**Angular Version:**
```
Node: 10.10.0
OS: win32 x64
Angular: 7.2.0-rc.0
```

**Anything else relevant?**
According to @IgorMinar, there should not be any Angular specific decorators after running `ngcc`.

**Comment by petebacondarwin** [comment]
Quick update: an initial investigation seems to indicate that the ESM5 browser.js is not being processed at all. Or at least the NgModule aspect of this file is not being processed, which is why the decorator is not being removed.

Other files containing NgModule decorators are being processed.

**Comment by alan-agius4** [comment]
There seems to be other files which are not being processed, for example

node_modules/@angular/common/esm5/src/pipes/date_pipe.js

```
    var DatePipe_1;
    DatePipe = DatePipe_1 = tslib_1.__decorate([
        Pipe({ name: 'date', pure: true }),
        tslib_1.__param(0, Inject(LOCALE_ID)),
        tslib_1.__metadata("design:paramtypes", [String])
    ], DatePipe);
    return DatePipe;
```

**Comment by JoostK** [comment]
@alan-agius4 Can you cherry-pick f13fb367e03983fd2e11f7cf344162b1c78c5962 from #26947 and see if that resolves the issue? We are aware of inconsistent behavior in the ESM5 reflection which should have been accounted for in that commit.

**Comment by JoostK** [comment]
@alan-agius4 ah, pity. It is related to that though, as the source that fails to be recognized is as follows:

```javascript
var DatePipe_1;
    DatePipe = DatePipe_1 = tslib_1.__decorate([
```

The intermediate assignment apparently fails to be recognized in ngcc's relfection host for ESM5.

**Comment by petebacondarwin** [comment]
I believe the error is in this method:

```
  protected getHelperCall(statement: ts.Statement, helperName: string): ts.CallExpression|null {
    if (ts.isExpressionStatement(statement)) {
      const expression =
          isAssignmentStatement(statement) ? statement.expression.right : statement.expression;
      if (ts.isCallExpression(expression) && getCalleeName(expression) === helperName) {
        return expression;
      }
    }
    return null;
  }
```

Not that if the statement is an assignment then we take the right hand of the assignment. This works in the case of 

```
DatePipe = tslib_1.__decorate([...]);
```

giving us the call to `__decorate()` but it does not work when there is a chain of assignnments:

```
DatePipe = DatePipe_1 = tslib_1.__decorate([
```
