### ISSUE TITLE
Redirect to root url does not work when returning UrlTree from guard

### ISSUE THREAD

**Issue by chrstnbrn** [angular/angular#27845]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

  No.

### Description

I use a guard to protect a route. If the user is not allowed to access the route I'd like to redirect to the root url. I'm doing this by returning an UrlTree from the canActivate method. To get the UrlTree for the root url I'm calling router.parseUrl('/'). However when I navigate to the protected page the redirect to the root url does not happen. The protected page isn't displayed either and there are no errors in the console.

If I change the guard to return router.parseUrl('/unauthorized') the redirect to the unauthorized page works as expected. I think this should also work for the root url. Am I missing something or is this a bug?

## 🔬 Minimal Reproduction

[https://stackblitz.com/edit/angular-issue-repro2-w72ytp](https://stackblitz.com/edit/angular-issue-repro2-w72ytp)

## 🔥 Exception or Error

 None

## 🌍  Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 7.1.4
Node: 10.13.0
OS: win32 x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@angular/cdk                      7.2.0
@angular/flex-layout              7.0.0-beta.22
@angular/material                 7.2.0
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
</code></pre>

**Anything else relevant?**

**Comment by jasonaden** [comment]
Thanks! This sounds like a bug. I've added this to a list to be looked into soon. Thanks!

**Comment by vixriihi** [comment]
We're facing the same issue. As a workaround we had to check if the redirect url was '/' and then just return true from the guard and redirect in the components ngOnInit.

**Comment by stoneLeaf** [comment]
I stumbled upon the same issue and found the cause, see my PR.
