### ISSUE TITLE
Move/share much of the 'NgZone' elsewhere?

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2785]
Lots of the code in NgZone is actually pretty useful outside of just Angular, (E.g. implementing a tracking zone), and I'd hate to just copy and paste it. How would people feel about creating another pub package (maybe tracked_zone) and exporting outside of Angular proper? Then NgZone could just extend it or compose on top of it.

Not the end of the world if not, just an idea. @vicb @yjbanov

**Comment by martinmcwhorter** [comment]
Zone.js has its own github repo https://github.com/btford/zone.js/

The version in the Angular repo may have some new bug fixes/features. Hopefully those will be merged into thr main repo.

**Comment by vicb** [comment]
`Zone.js` is one thing (and Dart has the "equivalent" native Zone). `NgZone` is an other thing built on top of `Zone.js` / `Zone`.

If we split `NgZone` to a separate package, it would probably make sense to move `NgZone` (renamed) to the zone.js repo.

**Comment by matanlurey** [comment]
+1. We can talk about this later, no rush.

**Comment by mhevery** [comment]
I am hesitant to support more API surface. I think we should let others implement the missing functionality independent of the Zone. 

Closing, reopen if you feel strongly.
