### ISSUE TITLE
Aot compiler breaking string concatination

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#27856]
Copied from https://github.com/angular/angular-cli/issues/12258

### Bug Report or Feature Request (mark with an `x`)
```
- [*] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [*] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node: 
````
v10.5.0
````
npm: 
````
6.1.0
````
Angular:
````
Angular CLI: 6.0.8
Node: 10.5.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.8
@angular-devkit/core         0.6.8
@angular-devkit/schematics   0.6.8
@schematics/angular          0.6.8
@schematics/update           0.6.8
rxjs                         6.2.1
typescript                   2.7.2
````

### Repro steps

1. create an Angular project
2. create a file which has a namespace with a const value：
src/app/const.ts
````
export namespace Const {
    export const Value = 'a';
}
````
3. create a lazy module, use the const value
src/app/a/a.module.ts
````
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { Const } from '../const';

@NgModule({
  imports: [
    RouterModule.forChild([
      // BUG 
      { path: `${Const.Value}b` },
    ]),
  ]
})
export class AModule {
}
````
src/app/app.module.ts
````
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { RouterModule } from '@angular/router';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    RouterModule.forRoot([
      {
        path: 'a',
        loadChildren: './a/a.module#AModule'
      },
    ]),
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
````
4. run `ng build --prod`

### The log given by the failure

The output js file of AModule has wrong path value.
dist/<project_name>/0.fc3e9f73dd253ec7a2f8.js
````
(window.webpackJsonp=window.webpackJsonp||[]).push([[0],{KImX:function(n,t,a){"use strict";a.r(t);var c=a("CcnG"),o=function(){},r=a("pMnS"),u=a("ZYCi");a.d(t,"AModuleNgFactory",function(){return i});var i=c.Fa(o,[],function(n){return c.Na([c.Oa(512,c.j,c.V,[[8,[r.a]],[3,c.j],c.u]),c.Oa(1073742336,u.l,u.l,[[2,u.r],[2,u.k]]),c.Oa(1073742336,o,o,[]),c.Oa(1024,u.i,function(){return[[{path:"[object Object]b"}]]},[])])})}}]);
````
expect `{path:"ab"}` but result is `{path:"[object Object]b"}` 

### Mention any other details that might be useful

1. without "--prod" flag is correct
2. without namespace is correct
3. ` ${Const.Value}b ` and `Const.Value + 'b' ` are same

This is re-predicable using the ngc compiler directly.

//cc @fdragoon

**Comment by alexzuza** [comment]
`const.ts` file contains module declaration.

AFAIK `MetadataCollector` doesn't process nodes with kind of `ts.SyntaxKind.ModuleDeclaration` so that we're getting empty metadata for `const.ts` file.

As a result simplification for `${Const.Value}` expression returns `StaticSymbol`
https://github.com/angular/angular/blob/c4f772740885c87788f9b8882168dcb0801d1ba0/packages/compiler/src/aot/static_reflector.ts#L606

and results in unexpected concatenation that object with string

**Comment by mhevery** [comment]
Works as designed.

**Comment by alxhub** [comment]
@alexzuza is correct - the mechanism by which `Const` is declared is not understood by our partial evaluator. Avoid using `namespace`. In the future this will be a compilation error, not an incorrect result.
