### ISSUE TITLE
@angular/elements creating is 7-10 times slower than native custom elements

### ISSUE THREAD

**Issue by artaommahe** [angular/angular#27858]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/elements

### Is this a regression?

dunno

### Description

Creating custom elements via @angular/elements is extremely slow. Simple test with ~600 components shows 7-10x slowdown related to native custom element.

@angular/elements with NgZone, prod mode
180ms creation + 220ms of raf hell
![image](https://user-images.githubusercontent.com/1944061/50519599-cb2f6d80-0acc-11e9-95a5-68bab76206fd.png)

@angular/elements without NgZone, prod mode
180ms creation + short raf mini-hell
![image](https://user-images.githubusercontent.com/1944061/50519530-725fd500-0acc-11e9-860e-172f2cecbb7d.png)

native custom element
20ms creation
![image](https://user-images.githubusercontent.com/1944061/50519553-80adf100-0acc-11e9-9df0-50e2640ecdcb.png)

## 🔬 Minimal Reproduction

@angular/elements without NgZone
https://stackblitz.com/edit/content-assemble-angular-elements?file=app%2Fhello.component.ts
for NgZone enabling comment out `{ ngZone: 'noop' }` in `main.ts`

native custom elements
https://stackblitz.com/edit/content-assemble-custom-elements?file=app%2Fhello.component.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>
7.1.4
</code></pre>

**Anything else relevant?**
It's not a synthetic case, we have a real case with thousands of lessons slides that are created in separate cms as html markup with a lot of components/exercises (usually 500-2k components nodes per slide). Currently we are using old aio approach with manual createComponent calls on appropriate nodes and its faster than using @angular/elements (https://stackblitz.com/edit/content-assemble-html-v2?file=app%2Fapp.component.ts 80ms for same example).

**Comment by robwormald** [comment]
We'll improve this in the next Elements API - for the moment, Elements is optimized for shipping a top level component to the outside world, vs instantiating hundreds of them. The current API is a balance. You can take control of this fully by implementing a custom strategy which might not use rAF...

Note that Elements are still Angular under the hood, so comparing them to a vanilla custom element isn't a great metric.
