### ISSUE TITLE
catchError of sample “https://angular.io/tutorial/toh-pt6” it's not working

### ISSUE THREAD

**Issue by rogerfsg** [angular/angular#27866]
# 📚 Docs or angular.io bug report

### Description

All the details you can see in the link:
https://stackoverflow.com/questions/53976697/catcherror-of-sample-https-angular-io-tutorial-toh-pt6-its-not-working?noredirect=1#comment94791288_53976697

### What's the affected URL?**
https://angular.io/tutorial/toh-pt6

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by jenniferfell** [comment]
Copied some key details from the comment thread on stackblitz: 

i pasted the code into stackblitz. At least for typescript 3.11, angular 7.01 and rxjs6.6.3 there are no typeerrors. Which versions do you use? – A.Winnen Dec 30 '18 at 10:27 

"@angular/cli": "~7.1.4", "rxjs": "~6.3.3", "typescript": "~3.1.6" – Roger Gusmao Dec 30 '18 at 10:35
@RogerGusmao 

I'm using "@angular/cli": "~7.0.6", "rxjs": "~6.3.3", "typescript": "~3.1.6" versions and I also cannot see any type errors. – Saddam Pojee Dec 30 '18 at 11:22

**Comment by jenniferfell** [comment]
@brandonroberts @IgorMinar Is this related to the 7.1.x change in the initial package.json file that is created by `ng new` (exclusion of @angular/http)?

**Comment by jenniferfell** [comment]
I believe the issue can be resolved by:

* getting the latest version of the in-memory-web-api package (https://github.com/angular/in-memory-web-api) mentioned in "Simulate a data server" section of the TOH part 6
or 
* adding @angular/http to package.json
or
* starting the tutorial from scratch

**Comment by brandonroberts** [comment]
Closing as resolved. The angular-in-memory-web-api package no longer depends on `@angular/http` and the changes have landed in master.
