### ISSUE TITLE
Non-inline styles not working: probably to do with Ivy Renderer

### ISSUE THREAD

**Issue by Mrspaceowl** [angular/angular#27869]
# 🐞 bug report

### Affected Package

 The issue might be caused by: the Ivy Renderer...

### Is this a regression?

Nope.

### Description

When using an Angular CLI generated project with the Ivy Renderer, ShadowDom encapsulation and  with scss stylesheets enabled, the project does not respond to alterations in the scss.

## 🔬 Minimal Reproduction

Generate a new project using the following command in the Konsole application within an Ubuntu VM (using VirtualBox):

`ng new OvalPlay --prefix op --routing --style scss --view-encapsulation ShadowDom --experimental-ivy`

Add the following to the `app.component.html`:

```
<div class="op-main-content">

  <header><h1>A Polygon of Virtue</h1></header>

  <p>Throughout history polygons have been oppressed and taught that their number of sides
    was their only benefit to society. Snakes and smaller mammals were thought exempt.
    Yet it was so that the tyranny of the militant lines, whether straight, or where by nature
    or form they took on a prismatic curvature when viewed, has brought about terror on a scale
    never before anticipated. This is a site about the tyranny of lines that anyone can edit,
    except when I say they can't, which is when views expressed contradict views I hold concerning 
    polygons. This site is not affiliated with either Polygon or their parent company Salon.com, 
    nor is it involved in the arms deals with Iran and Saudi Arabia both Polygon and Salon.com 
    participate willingly and knowingly in. Rather, it is a site concerned simply with angles of a 
    base polygonal form, and nothing else.
  </p>

</div>
<router-outlet></router-outlet>
```

And the following to the app.component.scss:

`.op-main-content {
    border: 3px dashed green;
    background-color: blue;
}`

You will notice the div with the tag op-main-content does not take on these horrific shades, as I wanted it to. Instead you will need to add the following to the HTML:

`style="border: 3px dashed green; background-color: blue;"`

Nothing further should be required.

## 🌍  Your Environment
Angular CLI: 7.1.4

**Anything else relevant?**

**Comment by JoostK** [comment]
@Mrspaceowl I can no longer reproduce with latest `8.1.0-next.3`, could you verify that your issue has been fixed?

**Comment by pkozlowski-opensource** [comment]
Going to close this one as appears to be fixed and we haven't heard back from the original issue author. Please open a new issue with a reproduce scenario if you still bumping into problems.
