### ISSUE TITLE
System.import('app'), app relative address error

### ISSUE THREAD

**Issue by zsqk** [angular/angular#2786]
use `https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js` is normal.

app is seen `https://registry.jspm.io/app.js` after used `https://code.angularjs.org/2.0.0-alpha.28/angular2.min.js`.

```
<script src="https://jspm.io/system@0.16.js"></script>
<script>System.import('app');</script>
```

**Comment by mhevery** [comment]
Can not reproduce, please create full repro on http://plnkr.co/ and reopen the issue.
