### ISSUE TITLE
Document that `whenStable` requires `await` within the test function

### ISSUE THREAD

**Issue by devrandom** [angular/angular#27863]
# 📚 Docs or angular.io bug report

### Description

`whenStable` returns a promise.  If the test does not perform an `await` on the promise, any failure may be missed or propagate during `afterAll`.

## 🔬 Minimal Reproduction

It is difficult to reproduce this reliably because of the async nature.

### What's the affected URL?

https://angular.io/guide/testing#more-async-tests

### Reproduction Steps

Any test with a failure inside the `whenStable` block.

### Expected vs Actual Behavior

Success of the test instead of failure, especially when there are additional tests run after.

**Comment by rockument69** [comment]
@gkalpak : Triaging this. Is there something to fix in the `whenStable` [section of the doc](https://angular.io/guide/testing#whenstable)? It doesn't seem so to me, but I may be missing something. Thanks.

**Comment by gkalpak** [comment]
AFAICT, you are right, @rockument69.

##
@devrandom, it is stated in the guide that `whenStable()` returns a promise and that the test assertions should happen in the promises callback. Additionally, the example shows using the `async()` testing helper (note this is different that the `async/await` keywords), which will surface uncaught promise rejections correctly (i.e. as part of the failing testcase and not in an `afterAll()` block).

I am going to close this, but if you think we missed something, please open a new issue and provide a minimal reproduction (e.g. using StackBlitz).
