### ISSUE TITLE
HttpUrlEncodingCodec lacks detail

### ISSUE THREAD

**Issue by dfong** [angular/angular#27870]
# 📚 Docs or angular.io bug report

### Description

the page for HttpUrlEncodingCodec lacks any useful details of what the methods do.

### What's the affected URL?**
https://angular.io/api/common/http/HttpUrlEncodingCodec

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by chembu** [comment]
fixed in #28597
