### ISSUE TITLE
Language service ignores excluded files

### ISSUE THREAD

**Issue by Airblader** [angular/angular#27872]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/language-service

### Is this a regression?

I'm not sure.

### Description

In my demo project, I have `*.ts` files which I load dynamically to render their code. As such, I don't need a warning like »Component 'ExampleComponent' is not included in a module and will not be available inside a template.« and similar.

I've excluded these files (`**/*.example.ts`) both in the tslint config as well as in `angular.json`, but the language service seems to ignore these exclusions (excluding it from tslint works).

## 🔬 Minimal Reproduction

https://github.com/Airblader/angular-lsbug-demo

Just open `foo.example.ts` and an IDE like WebStorm will show an error on the decorator.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.1.2
Node: 10.14.1
OS: linux x64
Angular: 7.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.11.2
@angular-devkit/build-angular      0.11.2
@angular-devkit/build-ng-packagr   0.11.2
@angular-devkit/build-optimizer    0.11.2
@angular-devkit/build-webpack      0.11.2
@angular-devkit/core               7.1.2
@angular-devkit/schematics         7.1.2
@angular/language-service          7.1.4
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.1.2
@schematics/angular                7.1.2
@schematics/update                 0.11.2
ng-packagr                         4.4.5
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.23.1
</code></pre>

**Anything else relevant?**

Related to #13726, #25623, #27227

**Comment by kyliau** [comment]
The language service reads tsconfig.json, so ignore the files in tslint and angular.json has no effect.
Could you please make sure that the relevant files are also ignored in tsconfig.json?

**Comment by kyliau** [comment]
This should not be an issue anymore, now that the v9 extension is released. Please open a new issue if this is not the case. The latest version could be downloaded from https://marketplace.visualstudio.com/items?itemName=Angular.ng-template
