### ISSUE TITLE
RouterLink generation throws exception on parameters even with safe operator

### ISSUE THREAD

**Issue by jimmykane** [angular/angular#27876]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

Doesn't work:

`<a [routerLink]="['/preview/referral/', report?.referral?.id]">#{{ report?.referral?.id }}</a>`
But this, that I understand it is the workaround, works

`<a [routerLink]="['/preview/referral/' + report?.referral?.id]">#{{ report?.referral?.id }}</a>`
Thanks

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code> Cannot read property 'outlets' of null</pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

Please see #9801 

Under request of @vsavkin at comment https://github.com/angular/angular/issues/9801#issuecomment-234661861

Doesn't work:

`<a [routerLink]="['/preview/referral/', report?.referral?.id]">#{{ report?.referral?.id }}</a>`
But this, that I understand it is the workaround, works

`<a [routerLink]="['/preview/referral/' + report?.referral?.id]">#{{ report?.referral?.id }}</a>`
Thanks

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

**Comment by jimmykane** [comment]
@jasonaden  I believe the closed issue has the not working link there. 

To summarise there was a bug report that one of your team memebers closes without resolution and asked to open a new one. 

That is what I did. 


http://plnkr.co/edit/J8estcmCxqUWJZZ1eO28?p=preview 

Here is your plunkr 

Navigate to product detail broken routerlink to see the issue manifest

**Comment by jimmykane** [comment]
I ll reopen one an play the little game you propose thanks.

**Comment by jimmykane** [comment]
@jasonaden  here you go another bug opened https://github.com/angular/angular/issues/27927
