### ISSUE TITLE
i18n: change default language from english

### ISSUE THREAD

**Issue by cakeinpanic** [angular/angular#27883]
# 🚀i18n: Add possibility to specify default language different from english

### Relevant Package
angular v.7

### Description
By now if you want to add i18n, you must use english as a default language – use it in all templates and set as base language in `.xlf` files for translate.
Related question: https://stackoverflow.com/questions/53947461/ng2-i18n-use-not-english-as-a-default-language-in-templates

### Describe the solution you'd like
I'd like to have possibility to set default language by myself. Because sometimes app is multi language but there is no english in language list. Or you want to use another language in templates. It is very useful when you need to add i18n _after_ the project is released for default language.
I suggest to use something like in `angular.json`:
```
"configurations": {
              "fr": {
                  "defaultLanguage": "true",
                   ...
              }
```
### Current workaround
By now I have found a workaround: never build app with default language and for _really default language_ specify translations the same with source.
For example if my default language is french and second language is spanish:
```
<h3 i18n="@@myId">Bonjour</h3>
```

`angular.json` 
```
 "configurations": {
              "fr": {
                  "i18nFile": "app/assets/i18n/messages.fr.xlf",
                  "i18nLocale": "fr"
              },
              "es": {
                  "i18nFile": "app/assets/i18n/messages.es.xlf",
                  "i18nLocale": "es"
              }
 }
```
messages.fr.xlf
```
<file source-language="fr" datatype="plaintext">
    ....
    <trans-unit id="myId" datatype="html">
      <source>Bonjour</source>
      <target>Bonjour</target>
    </trans-unit>
```
messages.es.xlf
```
<file source-language="fr" datatype="plaintext">
    ....
    <trans-unit id="myId" datatype="html">
      <source>Bonjour</source>
      <target>Hola</target>
    </trans-unit>
```

**Comment by ocombe** [comment]
You can specify the locale of your app when you extract: https://angular.io/guide/i18n#output-options `ng xi18n --i18n-locale fr`
Doesn't it work as you expect?

**Comment by wartab** [comment]
I can confirm that `ng xi18n --i18n-locale fr` works perfectly fine. We've been using that for over a year without any issue. What kind of problems are you experiencing?

**Comment by cakeinpanic** [comment]
When I specify language with `xi18n`, the only effect I get is language specified in calf file.
Quote from documentation: 
`This information is not used by Angular, but external translation tools may need it.`

My problem is that I need it to be used in angular)
Because if I use French in all my templates and then compile app without specifying language, I get`en-US` in LOCALE_ID and French words in app.
If I specify language, I get correct LOCALE, but an error because there is no <target> in .xlf, only <source> tags.

**Comment by wartab** [comment]
Compilation without i18n flags will not load any translation files. If you want i18n, you need to set those flags and that works perfectly fine even if your original language is French.

You have two options to do that, either you pass the target language in your command:
`ng build --prod --i18n-locale=fr --i18n-file=PATHTOFI18NFILE`

Or you edit your `angular.json` file:
```json
"options": {
...
 "i18nLocale": "fr",
"i18nFile": "src/locale/messages.fr.xlf",
"i18nFormat": "xlf",
...
}
```

**Comment by wartab** [comment]
As for the issue for no targets being defined in French, you can use the following flag:
https://angular.io/api/core/MissingTranslationStrategy

**Comment by AndrewKushnir** [comment]
Hi, as @ocombe and @wartab mentioned, the `--i18n-locale` flag should help achieve the necessary functionality, so I'm closing this ticket. Thank you.

**Comment by jomalJohny** [comment]
Will you explain how to use RTL direction using this
