### ISSUE TITLE
fix(http): http class requires @Inject decorator to be injected when using TypeScript

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#2788]
Not a big deal, but this should work without explicit decorators in TS.

Not sure if I need to do anything in my local environment either (typings?) Would love to fix it, but I think I need some pointers for that, since I have really no idea what teaches TS to translate constructor type annotations to parameter annotations...

**Comment by ericmdantas** [comment]
Same with ```FormBuilder```.

**Comment by jeffbcross** [comment]
@PascalPrecht what version are you using? Can you share some code?

In the example used for E2E tests, it is injected fine without explicit decorators: https://github.com/angular/angular/blob/5b5ffe75d0d1a3ac6204114203d8d566d49e9c70/modules/examples/src/http/http_comp.ts#L18

**Comment by PascalPrecht** [comment]
It's alpha 28 with typescript. Unfortunately plunkr doesn't support
typescript so there's no way to demonstrate it, but in the end it's really
just importing Http and having angular telling me that it can't resolve a
dependency due to broken annotations.

I can push some code to github tho. Maybe it has something to do with my
local env.

**Comment by jeffbcross** [comment]
Are you injecting `httpInjectables` somewhere along the way?

**Comment by dsebastien** [comment]
Hey there. I have a very shallow understanding of how DI works in Angular2 (I'm still down below on the learning curve ^^), but I encountered this issue (or a related one), using Alpha 28 & TypeScript. Here's my scenario.

I have a component in which I inject a 'service' class, which does get instantiated & injected by Angular (thanks to the appInjector property) but that in that service class I wanted Angular to inject an instance of Http. So I first added httpInjectables in my app's bootstrap, thinking that Angular's DI system would then always know how to inject such objects but that didn't quite work. 

The only way I found to have the Http object to be injected was to add the @Component annotation on my 'service' class with the appInjector property & httpInjectables.

Here's the service class:
https://github.com/dsebastien/midnightLightV2/blob/master/app/components/posts/posts.service.ts

Configured as such, the DI system does instantiate & inject the Http object before injecting the object in there:
https://github.com/dsebastien/midnightLightV2/blob/master/app/components/posts/posts.ts

It isn't particularly intuitive why it only works that way. Coming from the Java-verse where DI is pretty mature, I'm used to only configuring the DI system once and be confident that it'll automagically recognize what to inject where.

**Comment by PascalPrecht** [comment]
@jeffbcross yeap, `httpInjectables` are passed to `bootstrap()`. I'm going to setup a repo so you can play with the code.

@dsebastien if you have `httpInjectables` passed your your `bootstrap()` function, all the injectables should be available application wide. Which means, there's no need to make your service a component to use `appInjector`. You should be able to just do this: https://github.com/dsebastien/midnightLightV2/blob/master/app/components/posts/posts.service.ts#L19

However, as this issue states, it seems there's a problem with exactly that. I could work around it, by using explicit decorators a la:

```js
import {Inject, Http} from `angular2/angular`;

class myService {
  constructor (@Inject(Http): http:Http) {

  }
}
```

If this is entirely new to you, I recommend this article: http://blog.thoughtram.io/angular/2015/05/18/dependency-injection-in-angular-2.html

**Comment by dsebastien** [comment]
@PascalPrecht is appInjector still there in alpha 29? I'm under the impression that I should be using something else now, I just don't know what ;-)

**Comment by PascalPrecht** [comment]
@dsebastien currently it's `viewInjector`. Things are moving fast: https://github.com/angular/angular/blob/master/modules/angular2/src/core/annotations_impl/annotations.ts#L907

Not sure if this is already part of your local version tho

**Comment by dsebastien** [comment]
@PascalPrecht i'll take a look at it thanks. That's what I get when I try and play with alpha software.. But it's interesting as it allows to better understand (progressively) how it all evolves :). The biggest pain for me now is the fact that the typings on DefinitelyTyped always lag behing/are incomplete (I know this is being worked upon).

**Comment by PascalPrecht** [comment]
@jeffbcross okay so the repository is http://github.com/kanvaz/kanvaz-app

You need to checkout the `webpack` branch. Run `npm install` and then `npm start`

You'll prolly get some errors due to a non existing server but to reproduce the `@inject` problem, try to change this line: https://github.com/kanvaz/kanvaz-app/blob/webpack/src/app/services/kanvaz_service/kanvaz_service.ts#L12

Let me know if you need further help to reproduce the issue.

**Comment by robwormald** [comment]
this works fine for me - https://github.com/robwormald/fix-me-rob/blob/rob-fixt-it/src/main.ts 

That's using SystemJS - possible that webpack is handling something differently?

**Comment by gdi2290** [comment]
the problem is due to typescript and it's paramtypes. I have the same example of Http working when using a component [app-simple.ts#L55](https://github.com/angular-class/angular2-webpack-starter/blob/7a37cbb6cb66647741cf283ea9e54839aecd88b2/src/app/components/app-simple.ts#L55) but when I try to inject it in a service typescript isn't picking it up correctly. 
<img width="543" alt="screen shot 2015-07-04 at 8 00 13 pm" src="https://cloud.githubusercontent.com/assets/1016365/8510137/562148dc-2287-11e5-8273-860ca507789c.png">

here's my typedefinition 
```typescript
declare module "angular2/http" {
  class Http {
    private _backend;
    private _defaultOptions;
    constructor(_backend: any, _defaultOptions: any);
    request(url: string, options?: any): any;
    get(url: string, options?: any): any;
    post(url: string, body: any, options?: any): any;
    put(url: string, body: any, options?: any): any;
    delete(url: string, options?: any): any;
    patch(url: string, body: any, options?: any): any;
    head(url: string, options?: any): any;
  }
  class HttpFactory {}
  class MockBackend {}
  class XHRBackend {}
  class BaseRequestOptions {}
  var httpInjectables: Array<any>;
}
```
if you use `import * as ngHttp from 'angular2/http'` then it works with `ngHttp.Http`

**Comment by robwormald** [comment]
Same thing using SystemJS works absolutely fine?
https://github.com/robwormald/fix-me-rob/blob/rob-fixt-it/src/TestService.ts

**Comment by robwormald** [comment]
good news - https://github.com/Microsoft/TypeScript/pull/3690 fixes this error - @gdi2290 verified with your repo

**Comment by gdi2290** [comment]
kool

**Comment by PascalPrecht** [comment]
@gdi2290 thanks for digging into it. So this is a bug in TypeScript then? Is there a dedicated issue at the TS project already?

**Comment by robwormald** [comment]
hmm, so I poked around this a bit more today, because I felt like I was taking crazy pills - I backed out to .27 and the same exact behaviour appeared. 

On a whim, I imported the Injectable annotation and tagged my service with it, and that fixed the issue. On a further whim, I made a (do-nothing) decorator `@TestDecorator` and tagged my service, and that *also* fixed the issue (?!). My best guess is that TypeScript isn't doing the metadata thing unless any @Decorator appears in a file.

**Comment by gdi2290** [comment]
ah okay so if we use the `@Injectable` (only useful for compiling to Dart) decorator than we can force typescript to correctly attach the metadata.

**Comment by rixrix** [comment]
I was poking around this yesterday and this setup worked for me, at least, by looking and incorporating the comments and suggestions above.

`main.ts`
```javascript
import {bootstrap} from 'angular2/angular2';
import {httpInjectables} from 'angular2/http';
import {routerInjectables} from 'angular2/router';

import {MyApp} from './myapp';

bootstrap(
   MyApp,[
   routerInjectables,
   httpInjectables
]);
```
`myapp.ts`
```javascript
import {Component, View, Inject} from 'angular2/angular2';
import {Http} from 'angular2/http';
// plus other imports eg. RouteConfig, RouterOutlet, RouterLink, Router
.....

export class MyApp {
    constructor(@Inject(http) http: Http) {
        console.log(http); // previously, you won't get to this far w/o `@Inject`
    }
}
```
On last thing, from the `http.ts` source doc, it says `@Component({selector: 'http-app', viewInjector: [httpInjectables]})`, but `viewInjector` thingy didn't work for me, so I leave it off from my component. FYI

My env
* webpack
* typescript 1.5-beta
* angular 2.0.0-alpha.30
* MacOSX

**Comment by robwormald** [comment]
@rixrix yeah, the basic issue is that (in theory) we shouldn't have to do the manual @Inject(Http) bit while using typescript.

**Comment by gdi2290** [comment]
our correct workaround is using a decorator to force typescript to compile the metadata correctly. we can use `@Injectable()` for this
```typescript
import {Component, View} from 'angular2/annotations';
import {Inject, Injectable} from 'angular2/di';
import {Http} from 'angular2/http';
.....
@Injectable()
export class MyApp {
    constructor(http: Http) {
        console.log(http); // using a decorator will force typescript to correctly add metadata
    }
}
```

**Comment by jeffbcross** [comment]
Hmm, I'm able to reproduce this issue now. Adding Injectable decorator doesn't fix it in my case. Will look into it further.

**Comment by thelgevold** [comment]
Seems to work fine in alpha.31. I had to hack in some custom typings, but beyond that I could pretty much follow the examples in the Angular repo:
My code is here if you are interested: http://www.syntaxsuccess.com/viewarticle/angular-2.0-and-http

It would be awesome to get the http typings on DefinitelyTyped to avoid hacking in custom temporary files :-)

**Comment by jeffbcross** [comment]
@thelgevold the typings are there in DefinitelyTyped: https://github.com/borisyankov/DefinitelyTyped/blob/master/angular2/angular2.d.ts#L5779

Are they not working properly?

**Comment by thelgevold** [comment]
@jeffbcross Ah I see. I think for some reason I was under the impression that httpInjectables and http lived under a module named angular2/http. I did not see that module being declared, so I temporarily declared it locally. Looks like with this setup we get the http dependencies directly from the angular2/angular2 module which seems to be ok when I run the TypeScript compiler. The comments in the typings file still reference angular2/http though.

**Comment by PascalPrecht** [comment]
Another update on this one:

I'm getting the same error, when I use `Http` as type annotation for dependency injection of a service. E.g. if I have this:

```
import {Http} from 'angular2/angular2';
class MyService {
   constructor(http: Http) {

   }
}
```
And I use it here:
```js
import {httpInjectables} from `angular2/angular2';

@Component({
   viewInjector: [httpInjectables]
})
class MyComponent {

}
```

In that case `MyService` dependencies can't be resolved. Same issue occurs when changing it to:

```
class MyService {
   constructor(@Inject(Http) http: Http) {

   }
}
```

However, this solves the issue:

```
class MyService {
   constructor(@Inject(Http) http) {

   }
}
```
I think this is related.

**Comment by cfontes** [comment]
I am having issues as well with 2.0.0_33 with typescript and the injection of http module.

I am using definetlyTyped and TypeScript 1.5 so I think (?) i can import it like this, and use @Inject to add it to my constructor.

But I am getting the error message below:

```
EXCEPTION: No provider for function (_backend, _defaultOptions) {! (Todo -> function (_backend, _defaultOptions) {)
"STACKTRACE:"1 angular2.dev.js:21831:13
"BaseException@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:7738:25
AbstractBindingError@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:8931:11
NoBindingError@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:8954:11
.execute/Injector</<._throwOrNull@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:28051:21
.execute/Injector</<._getByKeyUnbounded@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:28096:20
.execute/Injector</<._getByKey@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:28044:22
.execute/Injector</<._getByDependency@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:28032:22
.execute/Injector</<._new@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:27929:33
.execute/InjectorInlineStrategy</<.instantiateBinding@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:27700:20
.execute/ElementInjectorInlineStrategy</<.hydrate@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:29243:24
.execute/ElementInjector</<.hydrate@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:28907:13
.execute/AppViewManagerUtils<._hydrateView@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:23693:19
.execute/AppViewManagerUtils<.hydrateRootHostView@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:23613:11
.execute/AppViewManager<.createRootHostView@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:26673:11
.execute/DynamicComponentLoader<.loadAsRoot/<@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:16682:31
run@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:136:14
.execute/NgZone</<._createInnerZone/<.$run/<@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:16029:28
zoneBoundFn@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:109:14
lib$es6$promise$$internal$$tryCatch@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:1359:16
lib$es6$promise$$internal$$invokeCallback@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:1371:17
lib$es6$promise$$internal$$publish@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:1342:11
[3]</</</<@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:187:5
.execute/NgZone</<._createInnerZone/<.$scheduleMicrotask/</microtask@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:16054:23
run@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:136:14
.execute/NgZone</<._createInnerZone/<.$run/<@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:16029:28
zoneBoundFn@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:109:14
lib$es6$promise$asap$$flush@https://code.angularjs.org/2.0.0-alpha.33/angular2.dev.js:1153:9
"1 angular2.dev.js:21831:13
"ERROR CONTEXT:"1 angular2.dev.js:21831:13
Object { element: <todo-list>, componentElement: null, injector: Object }1 angular2.dev.js:21831:13
```

```typescript
import {Component, View, bootstrap, NgFor, NgIf, Http, Inject} from 'angular2/angular2';
@Component({
    selector: 'person-list',
})
@View({
    template: `
    <ul>
      <li *ng-for="#person of people">
        {{ person }}
      </li>
    </ul>
    <input #persontext (keyup)="doneTyping($event)">
    <button (click)="addPerson(persontext.value)">Add Person</button>
    <p *ng-if="people.length > 3">You have many friends!</p>
    `,
    directives:[NgFor, NgIf]
})

class PersonList {
    peopleList: Array<string>;
    http: Http;

    constructor(@Inject(Http) http: Http) {
        this.http = http;
        this.peopleList = ["Eat Breakfast", "Walk Dog", "Breathe"];
        //http.get('/persons').toRx().map(res => res.json()).subscribe(people => this.peopleList.push(people));
    }
    addPerson(personName: string) {
        this.http.post('/person','{name: '+personName+", age: 15}");
    }
    doneTyping($event) {
        if($event.which === 13) {
            this.addPerson($event.target.value);
            $event.target.value = null;
        }
    }
}
bootstrap(PersonList);
```

**Comment by rixrix** [comment]
I made some basic modification of my little project (initially based of AngularClass starter) against @cfontes examples on xxx.33 release.

w/ xxx.33 release, if I inject `httpInjectables` globally at `bootstrap` location I don't have to do any `@Inject..` at the constructor level, unlike my previous post. However, injecting it via `viewInjector` would require me to use `@Inject (Http) http: Http` in the constructor.

w/ xxx.34 release, I don't have to do `@Inject...` anymore, either if I inject it globally or at the component level. One thing to note though, at the component level, you might need to use the `viewBindings` instead of the `viewInjector`. So maybe try and sync w/ the .34 release. ;)

**Comment by jessegood** [comment]
Not sure why, but after upgrading from `alpha-33` to `alpha-34`, this problem has gone away. Anybody still experiencing this in alpha-34?

**Comment by cfontes** [comment]
@rixrix nice, thanks. 

Why should I use viewBindings  instead of viewInjector? I can't find a reference to this information.

**Comment by ericmdantas** [comment]
@cfontes because in .34 viewInjector doesn't exist anymore. It's now called viewBindings.

**Comment by cfontes** [comment]
That is a very good reason ;)
On qua, 12 de ago de 2015 at 15:14 Eric Mendes Dantas <
notifications@github.com> wrote:

> @cfontes <https://github.com/cfontes> because in .34 viewInjector doesn't
> exist anymore. It's now called viewBindings.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/angular/issues/2788#issuecomment-130398361>.
>
-- 
Cristiano Fontes

**Comment by jeffbcross** [comment]
@vsavkin deviated from semantic versioning in this commit, which prevented it from making it into the changelog. https://github.com/angular/angular/commit/3cda7128d0a74661511390f4713682973e63b1fc

**Comment by jeffbcross** [comment]
I'll verify that my reproduction of this issue is fixed with the newer releases.

**Comment by mhevery** [comment]
I think TypeScript needs to have some hint that it should generate runtime type information for the DI. Therefore this is a requirement. Injection with no decorator will not work. 

@jeffbcross can this be closed?

**Comment by robwormald** [comment]
it sure would be nice if we could tell the TS compiler to always generate them, rather than having to import {Injectable} in every single file...

**Comment by PascalPrecht** [comment]
@mhevery shouldn't simply `@Inject` do the trick then?

**Comment by robwormald** [comment]
you could do

class Foo {
  constructor(@Inject(Bar) bar){

  }
}

but 

@Injectable()
class Foo {
  constructor(bar: Bar){}
}

feels like more idiomatic TS to me. it doesn't appear to matter *what* the decorator is, as long as there *is* one. Which is why it seems like this could be a flag in the ts compiler options like "alwaysGenerateMetadata" or w/e.

**Comment by ericmartinezr** [comment]
In case you want to know, in alpha37 is a requirement to use `@Inject` with `Http` in constructors. So I think you can close this.

**Comment by dsebastien** [comment]
@Injectable() is actually a good marker decorator I think, it clearly conveys the idea that the annotated class can be injected where need be :)

**Comment by robwormald** [comment]
i'm sorta 50/50 on it, to be honest. its a good marker as @dsebastien says, but it means that if i want to write a 3rd party library to work with angular, I have to actually import angular to get that annotation, which is kind of a bummer.

I'm still reasonably certain here *what* the decorator is irrelevant, it just needs *some* decorator to force typescript to emit the appropriate param decoration stuff, and that only happens if an @something annotation appears.

**Comment by ericmartinezr** [comment]
Just for your information, as @jessegood suggested (see [here](https://gitter.im/angular/angular?at=55f1fca32dc7775178dd402c)) using typescript 1.6.0-beta you don't need to use `@Inject` for Http in constructors (works with ng2 components, you still need `@Inject` in services)

**Comment by thelgevold** [comment]
This is great. I just upgraded to alpha.37 and typescript 1.6.0-beta and I can confirm that @Inject is not needed. Upgraded code deployed here: http://www.syntaxsuccess.com/angular-2-samples/
@ericmartinezr  Thanks for the tip!

**Comment by ericmartinezr** [comment]
@thelgevold those typings were already added, see https://github.com/borisyankov/DefinitelyTyped/tree/master/angular2

**Comment by thelgevold** [comment]
Ah. I must have just missed them :-)

**Comment by PascalPrecht** [comment]
For everyones interest, everything related to that issue is written down here: http://blog.thoughtram.io/angular/2015/09/17/resolve-service-dependencies-in-angular-2.html

I think this can be closed now.

**Comment by jeffbcross** [comment]
Thanks for linking the article, @PascalPrecht! I hope we can find a good way to remove the need for `@Injectable`...

**Comment by mesoamerica** [comment]
I found that to get the DI correctly working when using TS, we need to set emitDecoratorMetadata to true in the tsconfig.json.  Please refer to this article: https://toddmotto.com/angular-dependency-injection
This got my code working as expected.

**Comment by bill-mybiz** [comment]
@mesoamerica Thanks for the fix. I've been simply putting `@Inject(MyService)` all over the place. I found in the documentation that this option is barely a recommendation in a side note:

> Not every JavaScript class has metadata. The TypeScript compiler discards metadata by default. If the emitDecoratorMetadata compiler option is true (as it should be in the tsconfig.json), the compiler adds the metadata to the generated JavaScript for every class with at least one decorator.

Just below that is a big red box about `@Injectable()` needing parentheses. There should be a big red box about this setting, as it _defaults_ to false and must be explicitly set to true. Otherwise it simply and mysteriously doesn't work at runtime. In comparison, if I forget the parentheses on `@Injectable`, I get a red squiggly telling me it's wrong.

Thanks again for your fix!
