### ISSUE TITLE
Run events and lifecycles hooks in per-component zones

### ISSUE THREAD

**Issue by pauldraper** [angular/angular#27885]
# 🚀 feature request

### Relevant Package

@angular/core

### Description

`OnPush` is a necessity in any large app, but it is error-prone to markForCheck on every subscription, await, setTimeout, etc. A common case is HttpClient requests.

### Describe the solution you'd like

Each component should have its own forked Zone for running hooks and event handlers. Then, Angular can automatically markForCheck() on the proper component.

If this happened, OnPush would virtually always work, improving many apps performance with minimal development.

### Describe alternatives you've considered

I don't know any easy way to add this after. A custom decorators could take care of part, but there isn't DI that would allow me to get a ChangeDetectorRef.

I'm not aware of any injectable today that I could hook and get this to work. Plus per-component injection scope is verbose. (#18015)

**Comment by JiaLiPassion** [comment]
@pauldraper, could you post some `sample repo` to explain your requirement use case?  Thanks!

**Comment by pauldraper** [comment]
The real answer for this, it seems, is to always use the `async` pipe for any value passed to the view.

**Comment by sharikovvladislav** [comment]
@pauldraper did you solve the problem another way? you closed the issue
