### ISSUE TITLE
If Injector or DynamicComponentLoader fails, errors are cryptic/not helpful

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2790]
E.g. I see stack traces about "dehydrated components" and NPE's accessing ChangeDetector instead of the actual problem (e.g. DCL failed because of X or provider not found).

**Comment by mhevery** [comment]
Can you add repro case or at least the stack trace. This is not very actionable.

**Comment by matanlurey** [comment]
Yes I'll post repros for both cases.

**Comment by mhevery** [comment]
@matanlurey any update on this?

**Comment by matanlurey** [comment]
Will get to this today. Sorry for the delay.

**Comment by mhevery** [comment]
Closing as stale.
