### ISSUE TITLE
http get responeType return problem

### ISSUE THREAD

**Issue by dielangsea** [angular/angular#27900]
# 🐞 bug report

### Affected Package

 angular/common/http

### Is this a regression?

  angular 5.0.0

### Description

(1) i set { responseType: 'json' }, but when respone value is 0 will be error and cannot recive the respone, but broswer had got this response.

(2) i set  { responseType: 'text' }, but cannot recive the blank string like ''.

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

	GET(url: string, options?): Observable<any> {
		let currentUrl = this.baseUrl + url;
		const opts = options || {};
		return this.http.get(currentUrl, { responseType: 'json', ...opts, withCredentials: true });
	}
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

5.0.0
</code></pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we can't reproduce the problem you are reporting. We require that reported issues have a minimal reproduction that showcases the problem.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template that include info on how to create a reproduction using our template.
