### ISSUE TITLE
Missing 'crisis-detail.component.ts' in router docs code tabs

### ISSUE THREAD

**Issue by muuvmuuv** [angular/angular#27906]
# 📚 Docs report

In https://angular.io/guide/router#resolve-pre-fetching-component-data at "Two critical points" in the code-tabs is `crisis-detail.component.ts` missing and `crisis-detail.component.html` exists twice.

It is on line 3795: https://github.com/angular/angular/edit/master/aio/content/guide/router.md

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/pull/27025
