### ISSUE TITLE
Can loadChildren be used in combination with canActivate

### ISSUE THREAD

**Issue by oleersoy** [angular/angular#27918]
[I've asked about this on Stackoverflow]🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑(https://stackoverflow.com/questions/54009560/canactivate-authguard-ignored) and the answer was that `canActivate` should be combined with the specific component path routing, and should not be used to guard against lazy module loading.

However it works in past demos like this:
https://stackblitz.com/edit/akita-books-store
https://engineering.datorama.com/i-built-the-ngrx-demo-app-with-akita-heres-the-result-57f83fe92192
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
So just curious what the official "Angular spec" is on this?  

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑BTW - Not sure why there are red stop sign looking symbols in the post ....

**Comment by Airblader** [comment]
> BTW - Not sure why there are red stop sign looking symbols in the post ....

Probably you used the "Support request" issue template and managed to delete all the lines like this one:

> Please do not file questions or support requests on the GitHub issues tracker.

while keeping the red symbols?

**Comment by oleersoy** [comment]
I'm hoping we can see this as a documentation clarification feature request / possible bug report.  For [example for this article - with embedded stackblitz demo](https://engineering.datorama.com/i-built-the-ngrx-demo-app-with-akita-heres-the-result-57f83fe92192) the author combines `loadChildren` with `canActivate` and it works fine.  In other words `loadChildren` does not trigger until `canActivate` allows it too.  However in the latest version of Angular it no longer works.  

So is it supposed to work, and it's broken (In which case this is a bug report), or was it never supposed to work, and has been disabled.  

If it is the latter then this is a request for better error reporting.  Something that throws an exception indicating that `loadChildren` should not be combined `canActivate`.  It could also indicate that the user should use `canLoad` instead.

I can start a new issue once it's clear what the exact behavior is supposed to be.

**Comment by oleersoy** [comment]
One reason to allow `canActivate` to be used with `loadChildren` is that in this case the module can be prefetched.  With `canLoad` the module cannot be prefetched.

**Comment by jasonaden** [comment]
@oleersoy Thanks for the issue. However, I'm not seeing that `canActivate` used to work as you describe above. I'm seeing that the lazy loaded module is loaded and the module instantiated before the `canActivate` runs.

If you can produce a more isolated example showing this issue, please go ahead and do so. If it used to work this way in the past, it could be considered a regression. However, like I said above I'm not seeing that.

That being said, I think it's working as intended. `canActivate` is later in the cycle of routing than the loading. If you want the behavior I think you're looking for, the same guard should be used for both `canActivate` and `canLoad`.

If you can produce an isolated example showing this problem, please create a new issue with the StackBlitz attached. I'll close for now as I can't reproduce with the example linked above (https://stackblitz.com/edit/akita-books-store).
