### ISSUE TITLE
RouterLink generation throws exception on parameters even with safe operator

### ISSUE THREAD

**Issue by jimmykane** [angular/angular#27927]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/router

### Description

When you use a routerlink with safe operator the safe operator does not work. 

Example: 

```
<a [routerLink]="['user', user?.id]">test</a>
```
neither: 
```

<a ngif="user?.id" [routerLink]="['user', user?.id]">test</a>
```

or 
```
<a ngif="user" [routerLink]="['user', user?.id]">test</a>
```

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-gitter-htflku

## 🔥 Exception or Error

```
ERROR
Error: Cannot read property 'outlets' of null
```

## 🌍  Your Environment

**Angular Version:**
6.0.2

**Anything else relevant?**

This is the 3rd time at least this issue is reported and closed by the angular team members. 

https://github.com/angular/angular/issues/27876
https://github.com/angular/angular/issues/9801

**Comment by manklu** [comment]
```typescript
report?.referral?.id
```
is more ore less equal to
```typescript
report != null ? (report.referral != null ? (report.referral.id != null ? report.referral.id : null) : null) : null
```

What do you expect from 
```html
<a [routerLink]="['/preview/referral/', null]">#{{ report?.referral?.id }}</a>
```

On the other hand the result of ```'/preview/referral/' + report?.referral?.id``` is ```'/preview/referral/null'```. A valid string.

**Comment by jimmykane** [comment]
@manklu did you even see my code that was a previous example: 

See again in my stackbliz: 
```
<a [routerLink]="['user', user?.id]">test</a>
```

Why would the above not evaluate as safe? Or we should not use this pattern? 

Do I need to open up again a new issue? Waiting for user feedback here even 2 hours would be beneficial

**Comment by jimmykane** [comment]
@manklu I have updated the issue description and if needed I can update the Stackbliz but I think it's trivial to update that one

**Comment by jimmykane** [comment]
hmm right checking my code atm to ensure the example is correct.

**Comment by jimmykane** [comment]
Might I have some type on my real code @manklu ? 

Care to have a look? 

```
  <mat-list-item
    *ngIf="authService.authenticated() && (authService.user | async)?.uid"
    routerLinkActive="active"
    [routerLink]="['/user/', (authService.user | async)?.uid]">
    <mat-icon>account_circle</mat-icon>
    <span>My Profile</span>
  </mat-list-item>
```

**Comment by jimmykane** [comment]
Closing this till I provide another example that it fails with observables. My example is not correct I am very sorry
