### ISSUE TITLE
Micro Frontends, Using angular framework as externals

### ISSUE THREAD

**Issue by manavmanocha** [angular/angular#27924]
We are trying to split the a big front-end application (app.mydomain.com) into 2 smaller applications
1. Pre-Login application (prelogin.mydomain.com) - This includes everything before the user logs in
2. Post-Login application (postlogin.mydomain.com) - This includes everything after the user logs in

Both of these applications use angular framework which is currently being bundled along with other java-script files. Since angular framework is quite big in size, this increases the bundle size and hence impacts the frontend page loading performance. 

Since both of these micro applications are using the angular framework, we don't want to reload angular for second time (when user switches from prelogin to postlogin). Instead, we want to load angular as a external script from third domain (third.mydomain.com) and cache it in browser for future uses. Hence, when user switches from prelogin to postlogin, instead of loading the bundle again, a cached angular bundle from browser will be used.

I could not find anything in Official angular documentation which talks about loading angular in HTML (as a external script). Is this something which angular supports? Does angular provides a UMD module?

Regards,
Manav

**Comment by manavmanocha** [comment]
Apart from Angular, following are other major contributors to bundle size

1. RxJS
2. Zone.js

See attached screenshot for webpack bundle analyser. Is there a way RxJS or zone.js be loaded as external script?

![abundles](https://user-images.githubusercontent.com/2346005/50685226-5e712180-103e-11e9-9d12-173cfa87dae4.png)
![vbundles](https://user-images.githubusercontent.com/2346005/50685227-5f09b800-103e-11e9-9e16-998eab9c7377.png)

**Comment by sarunint** [comment]
Firstly, this is an issue tracker, not a support forum. You should not ask questions in this tracker. Use StackOverflow or Gitter.

Secondly, how do you bundle your application. It seems unusually large.

Thirdly, Angular provides UMD bundle, but it's not for production use. It bundles everything even the thing you don't use.

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by manavmanocha** [comment]
@sarunint, @kara - Thank you and I apologize for adding the question here. I will add this in StackOverflow.

@sarunint - This is non minified and non gzipped size of my bundle. It is not that large when it is minified.
