### ISSUE TITLE
Adding :id to guarded component path causes infinite loop

### ISSUE THREAD

**Issue by oleersoy** [angular/angular#27920]
[I've documented and provided a demo of this in this SO post](https://stackoverflow.com/questions/54030737/adding-id-to-guarded-component-path-causes-infinite-loop)

Even if the order is not correct, should the miss configuration cause an infinite loop?

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

**Comment by oleersoy** [comment]
@jasonaden the first sentence in the SO link has the Stackblitz demo:
https://stackblitz.com/edit/angular-ngrx-slice-demo-guard?file=src%2Fapp%2Fbooks%2Findex.ts
