### ISSUE TITLE
TypeError: n.share is not a function - angular 7.1.4

### ISSUE THREAD

**Issue by bitsjuanleal** [angular/angular#27926]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core/bundles/core.umd.min.js

### Description

 The error is in the bootstrapping.
`return platformBrowserDynamic().bootstrapModule(AppModule)
        .catch(err => console.log(err));`

This is the code of my main module

```
import {NgModule, SystemJsNgModuleLoader} from '@angular/core';
import {HttpModule} from '@angular/http';
import {BrowserModule} from '@angular/platform-browser';
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';

import {ScrollLoader} from 'classes/scroll-loader';
import {GlobalProviders} from 'classes/global-providers';

// Components contains metadata about all ngx components on the page.
const components = drupalSettings.adf_ui.ngx.components;
console.log(drupalSettings);
// Dynamically load all globally shared @Injectable services and pass as
// providers into main app bootstrap.
const globalProviders = new GlobalProviders(components);

Promise.all(globalProviders.importGlobalInjectables())
    .then(globalServices => {
        // array of providers to pass into longform bootstrap to make @Injectable
        // services shared globally.
        let globals = globalProviders
            .createGlobalProvidersArray(globalServices);

        /**
         * Root module for the whole application
         */
        @NgModule({
            providers: [SystemJsNgModuleLoader, ...globals.globalProviders],
            imports: [BrowserModule,HttpModule, ...globals.globalImports]
        })
        class AppModule {
            public ngDoBootstrap(): void {}
        }

        return platformBrowserDynamic().bootstrapModule(AppModule)
        .catch(err => console.log(err));
    })
    .then(appModule => {
        let loader = new ScrollLoader(appModule, components);
        loader.initialize();
    });

```

## 🔥 Exception or Error
<pre><code>

Unhandled Promise rejection: n.share is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: n.share is not a function

TypeError: n.share is not a function
    at new e (core.umd.min.js:621)
    at r (core.umd.min.js:716)
    at Yh (core.umd.min.js:716)
    at o (core.umd.min.js:731)
    at new t (core.umd.min.js:731)
    at gv (core.umd.min.js:731)
    at Object.Cg [as createNgModuleRef] (core.umd.min.js:780)
    at t.create (core.umd.min.js:780)
    at eval (core.umd.min.js:621)
    at ZoneDelegate.invoke (zone.js?v=2.4.0:388)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code> Version 7.1.4

</code></pre>

**Anything else relevant?**

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
