### ISSUE TITLE
*ngIf/For as a TemplateRef might cause troubles

### ISSUE THREAD

**Issue by EmaGht** [angular/angular#27933]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?
Don't think so/Don't know

### Description
Apparently, because *ngIf, and *ngFor (for example) are treated as TemplateRefs this markup

```
<ng-container *ngIf="true" mycontainer>
    This shouldn't be considered a Template, IMHO
</ng-container>

<ng-template>
    Right Template
</ng-template>
```

Used by a component that wraps it and uses it like this:

```
//Should get the ng-container tagged as "mycontainer"
<ng-content select="[mycontainer]"></ng-content>

//Should get the ng-template element
<ng-template [ngTemplateOutlet]="templateRef"></ng-template>
```

Where "templateRef" is retrieved with ContentChild like this:
```
@ContentChild(TemplateRef) templateRef;
```

Will end up printing in the HTML the sentence "This shouldn't be considered a Template, IMHO" twice.
The fact that items tagged with *ngIf *ngFor are considered templates is extremely confusing. It took me a miracle to figure out that could be the problem in my application.

## 🔬 Minimal Reproduction
I'm sorry but i honestly have not enough time to create a working repro... I'm writing this between one work and the other. 
If what i wrote here will be considered even slightly that's enough for me, in any case i felt this was important enough to tell you guys.

Love your work by the way (It's true ofc but also flattering helps 😄)

## 🌍  Your Environment

**Angular Version:**
6.X

**Comment by Airblader** [comment]
> The fact that items tagged with *ngIf *ngFor are considered templates is extremely confusing

They aren't "considered" templates, they *are* templates. That's just how structural directives work, they are merely syntactical sugar. 

```
<app-foo *ngIf="true"></app-foo>
```

desugars into

```
<ng-template [ngIf]="true">
  <app-foo></app-foo>
</ng-template>
```

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/24833

**Comment by EmaGht** [comment]
> 
> 
> Duplicate of #24833

Damn i couldn't find it when i was searching for a similar/same issue...

Also thanks @Airblader for the clarification
