### ISSUE TITLE
ActivatedRoute should provide an observable for child route changes

### ISSUE THREAD

**Issue by rmorrise** [angular/angular#27932]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/router

### Description

I have a parent-and-child component setup, where the parent component needs to display data from the child route. When I subscribe to ```activatedRoute.firstChild.data```, the data is displayed correctly on page load, but is not updated when the users switches to a different child route.

I believe this happens because ```activatedRoute.firstChild``` was changed, and the subscription is still attached to the data from the old child route.

### Describe the solution you'd like

I want my code to look something like this:
```
    this.viewTitle$ = this.activatedRoute.firstChild$.pipe(
        pluck('data', TITLE_DATA_PARAM)
    );
```

### Describe alternatives you've considered

Here is a workaround which produces the expected behavior.
```
    const childDataUpdates$ = this.router.events.pipe(
      switchMap(() => this.activatedRoute.firstChild.data)
    );
    const childData$ = merge(this.activatedRoute.firstChild.data, childDataUpdates$);

    this.viewTitle$ = childData$.pipe(
      pluck(TITLE_DATA_PARAM)
    );
```

I find this solution to be verbose and unintuitive.

**Comment by jasonaden** [comment]
While this is an interesting idea, I don't think it's something we will be able to add. It would need to work well with lazy-loaded modules which can have an impact on what the `firstChild` is at runtime.

Also, data should generally be flowing from the top down, so relying on a data from a child in the parent doesn't seem like a pattern we would like to support. In the future we have plans to make the router state serializable, and having references from parent to child can affect the serializability of the router state.

**Comment by rmorrise** [comment]
@jasonaden We have a common parent component which loads some metadata and displays a title section. The title section content changes depending on which view is currently selected, which is displayed in the child router outlet.

If you don't plan to support the pattern we use, please suggest an alternative approach to implement this type of feature.
