### ISSUE TITLE
Get HTML with angular events from ng-content

### ISSUE THREAD

**Issue by xonuzofa** [angular/angular#27930]
# 🚀 feature request

### Relevant Package
Angular 7.1.4

### Description

Same issue on SO: https://stackoverflow.com/questions/54025301/angular-7-sortable-table-inside-template

Seems like the only reason for using ng-content is to move the html template around wherever, style around it or using host deep to style components inside ng-content.  There is no way to actually grab the HTML inside ng-content with ALL events, nothing stripped.  This is a missing feature.  There is nowhere in angular to grab the content, change/modify it and then dump it back into a different element.  

When using a component with ng-content in the template, there is no way to grab the actual templated HTML from the child component.  I can retrieve the angular-event stripped HTML but that does not help me.

Example: Collapse Table

Collapse Table Component
`selector: 'collapse-table'`

Collapse Table HTML Template
```
<table #tableContent>
    <ng-content></ng-content>
</table>
```

Usage: 

```
<collapse-table>
    <thead>
        <tr>
            <th>Test</th>
        </tr>
    </thead>
    <tbody>
        <tr *ngFor="let item of items">
            <td (click)="test()">{{item.test}}</td>
        </tr>
    </tbody>
</collapse-table>
```

Inside Collapse Table Component I am using a @ViewChild and grabbing tableContent.  The innerHtml of tableContent strips out the (click)="test()" event, which I need!  Why can I not grab the entire template?

What I am attempting to do is grab the data, sort it via the collapse table component and output it into a new element and hide the original ng-content.  

### Describe the solution you'd like
Should be able to grab the actual content of ng-content with all events, and allow that HTML to then be place into another element's `[innerHtml]`.  

### Describe alternatives you've considered
There are no workaround since the events get stripped out.  Theres seems to be no way to modify the data of ng-content at this time.

**Comment by Airblader** [comment]
> Why can I not grab the entire template?

I don't get why you would want to, this really sounds like a design issue in your application to me. Also this would prevent AoT from being possible if I understand it correctly.

**Comment by xonuzofa** [comment]
Why not?  I get that I can use a component with `@Input`s and fill out columns and data and then sort them properly.  But this is a big headache when I have multiple levels of nested tables and other nested components.

To me, its a much better solution to have ng-content and allow me to dynamically add content, and then from the parent component side, if there was a function to grab template that would bypass security as safe HTML, then I could insert that content into another elements [innerHtml].

Theres no way to modify the ng-content data at all.  How is that not missing functionality in angular?  You can only use ng-content to style and wrap other elements inside, but nothing with manipulating the source?

**Comment by Airblader** [comment]
As I said, this wouldn't work with AoT anyway. And there's other ways than using inputs. You could also use DI to provide whatever data you want. Or pass templates and abstract the concept more similar to what Angular Material is doing in MatTable etc.

**Comment by xonuzofa** [comment]
The DI way would not work for me.  Passing in templates, how is that any different than what I am doing?  Is ng-content pretty much a template, correct?  If i pass a template, I still don't have access to manipulate the data.

**Comment by Airblader** [comment]
> If i pass a template, I still don't have access to manipulate the data.

I would again advise to take a look at Angular Material. In terms of sorting data (nested or not), just define some `DataProvider` which can handle this and requires a single `@Input()` later on. You can put all the sorting logic or nesting capabilities you want into such an layer.

In any case, let's not further this discussion here. It's not the place to talk about how to use Angular; you made a feature request and someone will have to make a decision on it.

**Comment by xonuzofa** [comment]
I will take a look.  I appreciate the information.

**Comment by xonuzofa** [comment]
I understand now.  Using directives, this is all possible.  That is what I was missing.  Thanks.
