### ISSUE TITLE
feat(http): directly return RxJS Observable from Http methods

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2794]
Instead of returning the platform-agnostic `EventEmitter` from `Http` methods like `http.request()`, return an observable or stream directly. JavaScript or Dart users shouldn't have to learn about our abstraction in order to make use of the underlying primitives.

Blocked by #3110

**Comment by jeffbcross** [comment]
I'm going to make this my focus for Milestone 31. 

As part of this, I'm going to attempt to bring in the [RxJS Next project](https://github.com/reactivex/rxjs) in place of RxJS.

CC @vsavkin @blesh @caitp

**Comment by blesh** [comment]
The es-observable spec seems to have a good deal of flux around some of it's behaviors/API, so while we want to meet those, we also want to create something that provides the best experience to the consumers of the lib. I don't foresee any major changes to the outward API of the RxJS Next project for the time being, but there may be some minor changes to behavior. I'll try to keep your ahead of these changes and informed directly. (It's pre-alpha for a reason, haha).

**Comment by jeffbcross** [comment]
Moved this to next milestone since other internal needs have taken precedence. Sounds like good timing so I can circle back with @blesh on potential API changes.

**Comment by jeffbcross** [comment]
I'm starting to experiment with installing from the RxJS-next from the [lift branch](https://github.com/reactivex/rxjs/tree/lift) per @blesh 's recommendation. Right now, I'm just testing in JavaScript and keeping the APIs of Observable/EventEmitter/ObservableWrapper the same while switching the implementation underneath.

**Comment by jeffbcross** [comment]
Removing from Alpha-32 in favor of the more focused #3110 task.

**Comment by robwormald** [comment]
closed by #4455
