### ISSUE TITLE
ngcc tries reading schematic "package.json" files

### ISSUE THREAD

**Issue by devversion** [angular/angular#27950]
Currently in our `cli-hello-world-ivy` integration test:

```
Failed to read entry point info from /home/circleci/ng/integration/cli-hello-world-ivy/node_modules/@schematics/angular/workspace/files/package.json with error SyntaxError: Unexpected token < in JSON at position 1121.
```

It looks like this happens because ngcc just tries to read all `package.json` files and `@schematics/angular` ships their templated `package.json` file without using the `.template` suffix.

I suspect the real fix would be that `@schematics/angular` just uses the `.template` suffix for their templated files, so that ngcc does not even try to read it.

We can move this issue to the CLI if @petebacondarwin thinks that this is the right solution, but I've submitted it here to see if there is something ngcc needs to handle differently.

**Comment by petebacondarwin** [comment]
I am sure we fixed this (or at least had a PR for this) already...

**Comment by petebacondarwin** [comment]
https://github.com/angular/angular/pull/26539

**Comment by devversion** [comment]
Do you mean this one? https://github.com/angular/angular/pull/26539. It currently does not fail, but we should try to avoid having this warning in the integration test output?

Personally I could see that `ngcc` is probably fine doing what it does, and we would just need to move this over to the CLI, so that they can consider using `package.json.template` instead of just `package.json` which will be picked up by ngcc.

**Comment by devversion** [comment]
Just saw that you edited your message. I agree with that said. Igor just mentioned it to me today, and so I wanted to track it somewhere. Let's move that to the CLI then.
