### ISSUE TITLE
feat(http): implement streaming upload/download

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2795]
A user should be able to provide observers as part of a `Request` or `RequestOptions` object in order to receive progress updates and chunks of data for uploading and downloading of data. 

Download observers will receive `Responses`, while upload observers will receive some form of [Progress Event](https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent)

To support different semantics of subscriptions between RxJS Observables and Dart Streams, an `Observer` implementation should be provided which will translate nicely to both platforms.

```typescript
var myObserver = new Observer(res => this.progress = res.bytesLoaded / res.totalBytes);
http.request('https://foo', {
  downloadObserver: myObserver,
  uploadObserver: null
}).subscribe(res => this.finalResponse = res.json());
```

The Response Observable returned from `Http` should still emit a single `Response` value and complete when the connection closes.

In order to perform the request without requiring a subscription on the `Response Observable` this feature would also require providing a means of specifying that the request should be executed immediately. This should be an additional property of `Request` and `RequestOptions`, name TBD.

These observers can be tested with the `MockBackend`, using methods called `mockUpload` and `mockDownload`.

**Comment by letmejustfixthatohitsbroken** [comment]
since there wasn't an update in 6 months here, is there any information when this feature is going to be implemented? I want to build a server-sided push-service using a constant http-stream and would love this very much.

**Comment by robwormald** [comment]
This issue was moved to angular/http#77

**Comment by adarshaj** [comment]
Where is this issue being tracked now?

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/issues/10424
