### ISSUE TITLE
Angular Resources, UI Components, add component.

### ISSUE THREAD

**Issue by MikhailTatsky** [angular/angular#27969]
Add link on one more component.

### Description

Add on page https://angular.io/resources in section UI Components, one more good grid library, please.
FancyGrid
https://fancygrid.com

**Comment by jenniferfell** [comment]
@MikhailTatsky : Thank you for submitting this suggestion. The resources list is moderated by @StephenFluin , so I've added him to this discussion. 

If you'd like to contribute the proposed addition, see [Contributing to resources.json](https://github.com/angular/angular/blob/master/aio/content/marketing/resources-contributing.md) and  [Contributing to Angular](https://github.com/angular/angular/blob/master/CONTRIBUTING.md).

**Comment by StephenFluin** [comment]
It looks like FancyGrid has good support for Angular, definitely feel free to submit a PR adding it!

https://fancygrid.com/docs/getting-started/angular

**Comment by ajitsinghkaler** [comment]
@gkalpak @kapunahelewong I think we can close this issue.
