### ISSUE TITLE
Remove version number from package.json; rely on git tag

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#2796]
We currently record the current version of ng2 in `package.json` and our publish scripts use it to set the version in pub and npm. This makes it hard (impossible) to release ng2 based on SHA that's not the latest master. By moving the version number out of the repo we'll be able to pick any SHA to release from.

**Comment by mhevery** [comment]
Is this still relevant?

**Comment by yjbanov** [comment]
Yes, but probably merely nice to have i.e. P4.

**Comment by malekpour** [comment]
In addition to `package.json`, why do we need the version number in the code?
```ts
import {Component} from 'angular2/core';
```
to
```ts
import {Component} from 'angular/core';
```

**Comment by IgorMinar** [comment]
Because if you have Angular 1 app that uses npm for dependency management
and now you want to upgrade it to Angular 2, you don't have a way to
specify two versions of Angular in a single package.json.

You could create two package.jsons but since you want to share many other
dependencies that would not be a good solution.

**Comment by malekpour** [comment]
@IgorMinar Looking backward, supporting both v1 and v2 in one project is really critical. Your point is understandable and I personally need it.

But in the future, hopefully much less than 7 years from now (the gap between v1 and v2) angular 3 will be out and we really want smoother migration. I believe the community really expects to run simple angular2 project in future versions without changing every `.ts` file.

In couple of years there will be millions of lines of typescript code containing `'angular2/...` and then it will be a much bigger issue. BTW the practice is against semantic versioning which npm follows.

Today's angular1 projects are barley using npm or rely on package.json fundamentally. Even if they are they can reference `angular-legacy`, `angularjs` or something like that for v1.

**Comment by IgorMinar** [comment]
My goal is to create enough tooling that we'll be able to migrate Angular
projects in the future in an automated way. We are not quite there yet, but
with our new templating and TS we have the foundations in place.

I'll bring up your concern about "angular" npm namespace at our next team
meeting.

**Comment by vicb** [comment]
My understanding is that `angular2` is not incompatible with semantic versioning, it's only the project name, ie you can have `angular2` v1.x, v2.x, v3.x, ...

**Comment by IgorMinar** [comment]
theoretically yes, but that would be super confusing.

let's talk to npm folks about their guidance on this issue.

**Comment by malekpour** [comment]
@IgorMinar So please consider the following concerns too:

How about using npm scope https://docs.npmjs.com/misc/scope just like https://www.npmjs.com/package/@reactivex/rxjs

We can have split packages which makes more sense and has much more benefits:
```
@angular/core
@angular/router
@angular/animate
@angular/material
```
so we will have
```ts
import {Component} from '@angular/core'; // not very different than current 'angular2/core'
```
and `package.json` like this:
```js
"dependencies": {
  "@angular/core": "^2.0.0-beta.0",
  "@angular/router": "^2.0.0-alpha.20", // possible to use a different version than core
  "@reactivex/rxjs": "^5.0.0-beta.0"
}
```
Current repository and `angular2` npm module contains around 1800+ files including a back ported v1 router and an incomplete material implementation. Obviously, having everything in one place worked very well during alpha development, but now it would be a great time to separate concepts in individual repositories and their corresponding npm packages.

**Comment by IgorMinar** [comment]
We considered using scoped packages but ran into some issues with tooling support. Now this is fixable but we didn't have time for it. Time to reconsider?

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

implement scoped packages, have nightlies.
