### ISSUE TITLE
Forms: provide an ability to configure email validator RegExp

### ISSUE THREAD

**Issue by scottseeker** [angular/angular#27963]
# feature/bug

### Affected Package
The issue is caused by package @angular/forms

### Is this a regression?
No, has always been an issue.

### Description
The e-mail address validator does not follow the rules specified in RFC 5322 https://tools.ietf.org/html/rfc5322

## 🔬 Minimal Reproduction
Attempt to validate e-mail address with double quotes or backslashes in the local portion of the e-mail address.  It will fail validation even though they are valid characters in an e-mail address.  International characters (some) do not work either (already an existing issue for that).

## 🌍  Your Environment

**Angular Version:**
<pre>
Angular CLI: 6.0.8
Node: 8.12.0
OS: win32 x64
Angular: 6.0.8
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.8 (cli-only)
@angular-devkit/core         0.6.8 (cli-only)
@angular-devkit/schematics   0.6.8 (cli-only)
@schematics/angular          0.6.8 (cli-only)
@schematics/update           0.6.8 (cli-only)
rxjs                         6.2.2
<code>

</code></pre>

edit: updated to non-obsolete RFC

**Comment by scottseeker** [comment]
RFC 3696 Provides some examples (https://tools.ietf.org/html/rfc3696)

RFC 5322 Provides technical documentation of e-mail address (https://tools.ietf.org/html/rfc5322) see section 3.4.1.

**Comment by mkanakis** [comment]
Hi, 

Any updates on that?

Best, Marios.

**Comment by dylhunn** [comment]
The email validator has not kept up with the demands of the times, but we can't change it -- it would be too breaking, and it would take a ton of code to accurately reflect the spec. (Here's a long list of issues and PRs requesting changes, all of which we closed:  #43976, #26395, #17296, #25186, #25763, #16976, #16544, #24743.)

@AndrewKushnir, WDYT about deprecating the email validator?

**Comment by dylhunn** [comment]
Users can actually just use `Validator.pattern`, so would it be redundant to make `email` accept a regex? Perhaps we should consider something more specific to emails (like a second pattern that obeys the RFCs).

**Comment by AndrewKushnir** [comment]
We've discussed this question with @dylhunn further. Given the motivation behind the email validator logic ([see here](https://angular.io/api/forms/Validators#email)), additional context from https://github.com/angular/angular/issues/25186#issuecomment-408665555, the fact that this would likely be a huge breaking change, we do not plan to change the email validation right now, but we'll add more info to the docs, see #44937.
