### ISSUE TITLE
Remove Browser Address bar and Bottom Bar

### ISSUE THREAD

**Issue by timusiiit123** [angular/angular#27976]
I have created a web app in Angular 6. I don't know how to hide the address bar and bottom navigation bar while on scrolling down or create a full screen web app. I used **requestFullScreen**, **window.scroll(0,1)** and **apple meta tag** but this did not work in angular 6. Can anyone suggest me to help in this problem?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
