### ISSUE TITLE
CircleCI workflow listing contains bogus links to GistIcon#20

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#27986]
Notice how each entry links to `#20` which is https://github.com/GistIcon/angular/pull/20:
<img width="1219" alt="screen shot 2019-01-08 at 7 06 41 am" src="https://user-images.githubusercontent.com/216296/50838942-1a1ea380-1314-11e9-821c-0ac5e67100ca.png">

this is wrong.. I'll follow up with CircleCI on this.

**Comment by gkalpak** [comment]
This is still an issue in the new UI. See for example [here](https://app.circleci.com/pipelines/github/angular/angular/23226/workflows/fcbbb82f-c2d6-417b-b9d8-0a683aa5d658/jobs/835951):

![circleci-gisticon-20](https://user-images.githubusercontent.com/8604205/96348114-eeb31600-10ae-11eb-939b-8ca75a661788.png)

**Comment by JeanMeche** [comment]
This works as expected now.
