### ISSUE TITLE
Set()

### ISSUE THREAD

**Issue by DanielFrugoni** [angular/angular#27992]
let params  = new HttpParams().set('Gpclave',  term);
only search for exact match , why ???
where do I put the wild card ???

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
