### ISSUE TITLE
Input binding broken with Directive

### ISSUE THREAD

**Issue by rajinder-yadav** [angular/angular#28007]
# 🐞 bug report

### Affected Package

`@angular/core`

### Description

Input binding in a Directive does not work, the value is always `undefined`.

## 🔬 Minimal Reproduction
App showing the bug: https://github.com/rajinder-yadav/ng-directive-bug

Look at file `highlight.directive.ts`, class field, 'color` does not get assigned a value.

Also try removing the alias 'appHighlight', this is also broken.

Change
```
@Input('appHighlight') color: string;
```
To
```js
@Input() color: string;
```
Ref: https://angular.io/guide/attribute-directives#pass-values-into-the-directive-with-an-input-data-binding

## 🌍  Your Environment

**Angular Version: ~7.1.0**
<pre><code>
Angular CLI: 7.1.4
Node: 10.14.1
OS: linux x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
<code></pre>

**Comment by Zuckjet** [comment]
You should do your operation in other lifecycle hooks, not in constructor.
From the [doc](https://angular.io/guide/lifecycle-hooks#lifecycle-sequence), we can see the ngOnInit's description:

> Initialize the directive/component after Angular first displays the data-bound properties and sets the directive/component's input properties.

So do your operations in other lifecycle hooks such as ngOnInit, will do what you want.
If you have troubles in learning angular, you can ask for help on stackoverflow first. Pleas close this bug issue.

**Comment by jotatoledo** [comment]
> Look at file highlight.directive.ts, class field, 'color` does not get assigned a value.

Expected behavior, as values bounded through input properties are not set on initialization of a component/directive instance (constructor).

To solve your issue you can either:

- Use the HostBinding decorator
- Use some appropiate lifecycle hook
- Transform the color property into a setter with your logic in it

> Also try removing the alias 'appHighlight', this is also broken.

Could you be more specific?

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by rajinder-yadav** [comment]
So this is from the Angular doc, it is doing stuff in the ctor

```js
import { Directive, ElementRef } from '@angular/core';

@Directive({
  selector: '[appHighlight]'
})
export class HighlightDirective {
    constructor(el: ElementRef) {
       el.nativeElement.style.backgroundColor = 'yellow';
    }
}
```

Am I missing something? https://angular.io/guide/attribute-directives#pass-values-into-the-directive-with-an-input-data-binding
I can't be faulted for following the example there.
