### ISSUE TITLE
Different maxlength behavior depending on definition

### ISSUE THREAD

**Issue by StefanKern** [angular/angular#28008]
### Description

Depending, if the validation rules where created on the HTML element (`[maxLength]="5"`) or inside the controller (`new FormControl('', [Validators.maxLength(5)]);`) the "maxLength "Validation" behaves differently.

1. If created via `[maxLength]="5"` only 5 characters can be added into the input/ textarea but a error message is never shown (it is valid after all)
2. If added inside the controller any number of characters can be added but if the number exceeds 5, and error is displayed 

The expected behavior would be an identical functionality independent of the declaration. 

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-fw7tpa

HTML:
```html
<form class="example-form">
  <mat-form-field class="example-full-width">
    <input matInput placeholder="Validation rules from controller" 
           [formControl]="validationRulesFromController"
           [errorStateMatcher]="matcher">
    <mat-hint>Can type as long as I want, only the error appears</mat-hint>
    <mat-error>
      Too long
    </mat-error>
  </mat-form-field>
  <mat-form-field class="example-full-width">
    <input matInput placeholder="Validation rules from input element" 
           [formControl]="validationRulesFromInputElement" [maxLength]="5"
           [errorStateMatcher]="matcher">
    <mat-hint>Can only type 5 charactes, no error appears.</mat-hint>
    <mat-error>
      Too long
    </mat-error>
  </mat-form-field>
</form>
```

Controller:
```ts
import {Component} from '@angular/core';
import {FormControl, FormGroupDirective, NgForm, Validators} from '@angular/forms';
import {ErrorStateMatcher} from '@angular/material/core';

/** Error when invalid control is dirty, touched, or submitted. */
export class MyErrorStateMatcher implements ErrorStateMatcher {
  isErrorState(control: FormControl | null, form: FormGroupDirective | NgForm | null): boolean {
    const isSubmitted = form && form.submitted;
    return !!(control && control.invalid && (control.dirty || control.touched || isSubmitted));
  }
}

/** @title Input with a custom ErrorStateMatcher */
@Component({
  selector: 'input-error-state-matcher-example',
  templateUrl: './input-error-state-matcher-example.html',
  styleUrls: ['./input-error-state-matcher-example.css'],
})
export class InputErrorStateMatcherExample {
  validationRulesFromController = new FormControl('', [Validators.maxLength(5)]);

  matcher = new MyErrorStateMatcher();
}
```

**Comment by kara** [comment]
@StefanKern The input length restriction (where you can't type past the length) is actually a native feature of the browser. When you add the `maxlength` attribute to any input (not just in Angular), native validation enforces that you can't type more than that length.  If you want that same behavior with Angular constructs like `Validators.maxLength`, you can add the attribute in the template as well.

Worth noting that we have an open issue to automatically add attributes so native validation kicks in. You can follow it [here](https://github.com/angular/angular/issues/9121).
