### ISSUE TITLE
Docs Angular universal use --app which is no longer supported

### ISSUE THREAD

**Issue by c00** [angular/angular#28018]
# 📚 Docs or angular.io bug report

### Description

The script referenced in [this](https://v6.angular.io/guide/universal#creating-scripts) chapter uses the option `--app` which is no longer supported in the Angular CLI. This results in an error `Unknown option: '--app'`

The full command in the script is:
```
ng build --prod && ng build --prod --app 1 --output-hashing=false
```

## 🔬 Minimal Reproduction

```
ng build --prod --app 1
```

### What's the affected URL?**
https://v6.angular.io/guide/universal#creating-scripts

The latest version of the docs also mention the same command. While I haven't tried it, I assume `--app` wasn't reintroduced, so this should be updated as well.

### Reproduction Steps**
Follow all the steps up to and including Step 5 in the referenced document.

## 📷Screenshot
![image](https://user-images.githubusercontent.com/6259056/50912097-e5b9fd00-1463-11e9-91b6-3a2bbe040f41.png)

## 🔥 Exception or Error
<pre><code>
Unknown option: '--app'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cirquel-library@0.0.0 build:client-and-server-bundles: `ng build --prod && ng build --prod --app 1 --output-hashing=false`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cirquel-library@0.0.0 build:client-and-server-bundles script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/coo/.npm/_logs/2019-01-09T16_11_09_686Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cirquel-library@0.0.0 build:ssr: `npm run build:client-and-server-bundles && npm run webpack:server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cirquel-library@0.0.0 build:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/coo/.npm/_logs/2019-01-09T16_11_09_703Z-debug.log
</code></pre>

## 🌍  Your Environment

I'm using ubuntu 18.04
Node v8.11.3
npm 6.5.0
Angular CLI: 6.1.5
Node: 8.11.3
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cli                      6.1.5
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.3.3
typescript                        2.7.2
webpack                           4.9.2

**Comment by FrederikSchlemmer** [comment]
Related to [Angular CLI Issue #10743](https://github.com/angular/angular-cli/issues/10743)?

In the current documentation, the command in the downloadable example has already been changed to the new functionality of the Angular CLI. In the example, the command has been changed to:

> "build:client-and-server-bundles": "ng build --prod && ng run angular.io-example:server"

I'm going to create a pull request for this one.

**Comment by FrederikSchlemmer** [comment]
@brandonroberts this issue can be closed too!

**Comment by brandonroberts** [comment]
Thanks @FrederikSchlemmer!
