### ISSUE TITLE
docs: add tests for RxJS guide examples

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#28017]
# 📚 Docs or angular.io bug report

### Description

The [examples][1] used in the [RxJS guide][2] have no tests ensuring they are valid. (They are not even, at least, compiled to ensure they are valid TS code 😱)

### What's the affected URL?**

https://angular.io/guide/rx-library

[1]: https://github.com/angular/angular/tree/master/aio/content/examples/rx-library
[2]: https://github.com/angular/angular/blob/c3aa24c3f9699242331ca014b1616e968c1a7f8c/aio/content/guide/rx-library.md

**Comment by santoshyadav198613** [comment]
Hi @gkalpak ,
Is this still open, will work on this.

**Comment by gkalpak** [comment]
Sure, thx, @santoshyadav198613 ❤️
Ping me if you need any help :wink:

**Comment by santoshyadav198613** [comment]
Hi @gkalpak ,

How to run the test case for examples, can not see any scripts, Can you please guide.

**Comment by gkalpak** [comment]
In a nutshell, each example in `aio/content/examples/` is a mini-app (most of them are cli apps, so the regular commands, such as `ng test` or `ng e2e`, should work - once you set them up).

Since we don't want to have dozen of copies of `node_modules/` and other boilerplate files, we have some commands that set up the examples (copy boilerplate files in each directory, creating symlinks to one `node_modules/` directory, etc).

There is some info in [aio/README.md][1], but simplest way would be to run `yarn setup` inside `aio/` (which will take care of all necessary setting up) and then `cd` into the example directory you care about and run the standard cli commands - e.g. `ng e2e`. (Note that for `examples` we mainly focus on e2e tests, since these are run on CI.)

Let me know, if this works for you.

[1]: https://github.com/angular/angular/blob/2a6e6c02e/aio/README.md

**Comment by santoshyadav198613** [comment]
Thanks @gkalpak , got it, I thought we need unit test will work on it.

**Comment by sonukapoor** [comment]
I can work on this if nobody else has taken it yet.

**Comment by gkalpak** [comment]
Thx, @sonukapoor :tada:
