### ISSUE TITLE
AOT: directive of subclass not working

### ISSUE THREAD

**Issue by CaerusKaru** [angular/angular#28029]
# 🐞 bug report

### Affected Package

`@angular/compiler` would be my best guess

### Is this a regression?

Uncertain

### Description

In Flex Layout, we recently changed the structure of our library from one where our directives were subclasses that were then extended to a _new_ structure where the directives are subclasses _of subclasses_ of an abstract base class.

Here's where the weirdness comes in: our own internal directives compile and work fine. But when others try to extend our subclasses to make their own directives (which should be supported), the directives fail to work in AOT.

## 🔬 Minimal Reproduction

StackBlitz: [https://stackblitz.com/edit/angular-layout-custom-hide](https://stackblitz.com/edit/angular-layout-custom-hide)
More context here: https://github.com/angular/flex-layout/issues/961

Instructions:
* Download the StackBlitz and run in non-AOT mode (This will show that at a certain height, around 600px, the element will disappear and reappear)
* Run in AOT mode and notice the same behavior doesn't occur

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.0.5
Node: 10.14.2
OS: darwin x64
Angular: 7.2.0
... animations, bazel, common, compiler, compiler-cli, core
... forms, http, platform-browser, platform-browser-dynamic
... platform-server, router
</code></pre>

**Comment by CaerusKaru** [comment]
cc @alxhub @vikerman

**Comment by ThomasBurleson** [comment]
Here is the pertinent code parts:

```ts
/**
 * This one fails to instantiate in demo app with AOT!!
 */
@Directive({selector, inputs})
export class CustomHideDirective extends ShowHideDirective {
   protected inputs = inputs;
}

// ****************************************
// Core Library 
// ****************************************

/**
 * Core ‘show’ Layout API directive
 */
@Directive({selector, inputs})
export class DefaultShowHideDirective extends ShowHideDirective {
  protected inputs = inputs;
}

export class ShowHideDirective extends BaseDirective2 implements AfterViewInit, OnChanges {
  constructor(protected elementRef: ElementRef,
              protected styleBuilder: ShowHideStyleBuilder,
              protected styler: StyleUtils,
              protected marshal: MediaMarshaller,
              @Inject(LAYOUT_CONFIG) protected layoutConfig: LayoutConfigOptions,
              @Inject(PLATFORM_ID) protected platformId: Object,
              @Optional() @Inject(SERVER_TOKEN) protected serverModuleLoaded: boolean) {
    super(elementRef, styleBuilder, styler, marshal);
  }

 //....
}

export abstract class BaseDirective2 implements OnChanges, OnDestroy {
  protected constructor(protected elementRef: ElementRef,
                        protected styleBuilder: StyleBuilder,
                        protected styler: StyleUtils,
                        protected marshal: MediaMarshaller) {
  }

 //....
}
```

*  [BaseDirective2](https://github.com/angular/flex-layout/blob/master/src/lib/core/base/base2.ts#L16)
*  [ShowHideDirective](https://github.com/angular/flex-layout/blob/master/src/lib/extended/show-hide/show-hide.ts#L44)

**Comment by mhevery** [comment]
Could we have a *minimal* reproduction which does not include flex as a dependency?

**Comment by CaerusKaru** [comment]
Status update on this is that I can't replicate the issue with Angular 7.2 (for Flex we had been on 7.1 until today). I'm going to double back and confirm this has been fixed and then I'll close this issue.

**Comment by CaerusKaru** [comment]
Yep, definitely patched. We also made some UMD bundle updates in our library. There's a chance some confluence events transpired to fix this. Regardless, this is no longer an Angular issue, so I'm closing this. Thanks for getting back to us.
