### ISSUE TITLE
feat(http): Support many types of body on Request/Response and all ConnectionBackend implementations

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2803]
These types should be supported by all backends, as much as each backend is technically capable of supporting:

 * FormData (for request only)
 * Blob
 * Document (for response only)
 * Text (String)
 * JSON

TBD: ArrayBufferView/ArrayBuffer?

All expected response types should be able to be explicitly declared on the `Request`, so that they can be optimized by the underlying primitive (see #2609). Request body types won't be explicitly declared.

**Comment by robwormald** [comment]
This issue was moved to angular/http#75

**Comment by squadwuschel** [comment]
the moves Link was not found @robwormald
