### ISSUE TITLE
The `InputDecorator` (`@Input`) api description is incorrect

### ISSUE THREAD

**Issue by SteveVanOpstal** [angular/angular#28043]
# 📚 Docs or angular.io bug report

### Description

The `InputDecorator` api description is replaced with the pipe description in following commit:
https://github.com/angular/angular/commit/7d318743c1337507d75847f2db2dfedcc0be7ca8#diff-0de86edfd2eefb71d70045fbaeebdb1dL821

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by Suresh918** [comment]
I checked this and issue is there in the master branch. Can I do PR ?

**Comment by brandonroberts** [comment]
Fixed via #28836
