### ISSUE TITLE
Update TRIAGE_AND_LABELS doc to include new required labels for PRs

### ISSUE THREAD

**Issue by kara** [angular/angular#28058]
The TRIAGE_AND_LABELS.md file has some outdated info on how PRs should be triaged. Labels to indicate both risk and effort are required for the bot to move something from "triage" to "backlog", but there's no mention of it in the doc.

**Comment by IgorMinar** [comment]
@ocombe can you please document the current labeling requirements based on how the bot is setup? Thanks!
