### ISSUE TITLE
ts-api-guardian doesn't understand/follow transitive bazel dependencies

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#28057]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
[ts-api-guardian](https://github.com/angular/angular/blob/master/tools/ts-api-guardian)

### Description

 A clear and concise description of the problem...
ts-api-guardian doesn't follow transitive bazel dependencies automatically, so after we split up //packages/core/src into bazel sub-packages we now have to explicitly specify all transitive deps. This should not be necessary.

## 🔬 Minimal Reproduction
See: public_api_guard/BUILD.bazel change in https://github.com/angular/angular/pull/28028/files#diff-e3636bed18e8113bcb42dd2d864d96d8R12

**Comment by devversion** [comment]
Closing as we removed TS API guardian from the repo.
