### ISSUE TITLE
Animation triggers are not executed on an element with hostBindings for enter/leave animations

### ISSUE THREAD

**Issue by matsko** [angular/angular#28060]
# 🐞 bug report

### Affected Package
@angular/animations and @angular/core

### Is this a regression?
Yes because this should've been fixed by #15193

### Description
If a component exists with only a host binding that talks to an animation then if that host element is removed from the parent component it will not trigger the animations to run.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ctywai?file=src%2Findex.html

## 🔥 Exception or Error
No animations are run

## 🌍  Your Environment

**Angular Version:**
Angular 7.0.0 on Chrome.

**Comment by RyannGalea** [comment]
Any info on this being fixed?
