### ISSUE TITLE
ivy: Types of property 'ngDirectiveDef' are incompatible using "strictFunctionTypes": true in TS config

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#28079]
# 🐞 bug report

### Description

`ngtsc` fails to compile an application using ng-bootstrap with `"strictFunctionTypes": true` in TS config, because the code compiled by ngcc is:

```typescript
export declare class NgbDropdownAnchor {
    dropdown: any;
    private _elementRef;
    anchorEl: any;
    constructor(dropdown: any, _elementRef: ElementRef<HTMLElement>);
    isEventFrom($event: any): boolean;
    static ngDirectiveDef: ɵngcc0.ɵDirectiveDefWithMeta<NgbDropdownAnchor, '[ngbDropdownAnchor]', never, {}, {}, never>;
}
export declare class NgbDropdownToggle extends NgbDropdownAnchor {
    constructor(dropdown: any, elementRef: ElementRef<HTMLElement>);
    toggleOpen(): void;
    static ngDirectiveDef: ɵngcc0.ɵDirectiveDefWithMeta<NgbDropdownToggle, '[ngbDropdownToggle]', never, {}, {}, never>;
}
```

and that produces after `ng build --aot` in an Ivy app:

```
ERROR in node_modules/@ng-bootstrap/ng-bootstrap/dropdown/dropdown.d.ts(39,22): error TS2417: Class static side 'typeof NgbDropdownToggle' incorrectly extends base class static side 'typeof NgbDropdownAnchor'.
  Types of property 'ngDirectiveDef' are incompatible.
    Type 'DirectiveDef<NgbDropdownToggle>' is not assignable to type 'DirectiveDef<NgbDropdownAnchor>'.
      Types of property 'providersResolver' are incompatible.
        Type '(def: DirectiveDef<NgbDropdownToggle>) => void' is not assignable to type '(def: DirectiveDef<NgbDropdownAnchor>) => void'.
          Types of parameters 'def' and 'def' are incompatible.
            Type 'DirectiveDef<NgbDropdownAnchor>' is not assignable to type 'DirectiveDef<NgbDropdownToggle>'.
              Types of property 'type' are incompatible.
                Type 'Type<NgbDropdownAnchor>' is not assignable to type 'Type<NgbDropdownToggle>'.
                  Type 'NgbDropdownAnchor' is not assignable to type 'NgbDropdownToggle'.
```

### Is this a regression?

Not it has been present for a while

## 🔬 Minimal Reproduction

```
ng new ivy-boostrap --defaults
npm i --save @ng-bootstrap/ng-bootstrap
$(npm bin)/ivy-ngcc
# if ngcc fails apply https://github.com/angular/angular/pull/28076 manually and rerun
# add NgDropdownModule to AppModule (see above)
# enable ivy to use ngtsc
# add "strictFunctionTypes": true to tsconfig.json
ng build --aot 
```

app.module.ts
```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    NgbDropdownModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
## 🔥 Exception or Error

`ng build --aot` yields:
<pre><code>
ERROR in node_modules/@ng-bootstrap/ng-bootstrap/dropdown/dropdown.d.ts(39,22): error TS2417: Class static side 'typeof NgbDropdownToggle' incorrectly extends base class static side 'typeof NgbDropdownAnchor'.
  Types of property 'ngDirectiveDef' are incompatible.
    Type 'DirectiveDef<NgbDropdownToggle>' is not assignable to type 'DirectiveDef<NgbDropdownAnchor>'.
      Types of property 'providersResolver' are incompatible.
        Type '(def: DirectiveDef<NgbDropdownToggle>) => void' is not assignable to type '(def: DirectiveDef<NgbDropdownAnchor>) => void'.
          Types of parameters 'def' and 'def' are incompatible.
            Type 'DirectiveDef<NgbDropdownAnchor>' is not assignable to type 'DirectiveDef<NgbDropdownToggle>'.
              Types of property 'type' are incompatible.
                Type 'Type<NgbDropdownAnchor>' is not assignable to type 'Type<NgbDropdownToggle>'.
                  Type 'NgbDropdownAnchor' is not assignable to type 'NgbDropdownToggle'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.2.0
Node: 10.14.1
OS: darwin x64
Angular: 7.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.0
@angular-devkit/build-angular     0.12.0
@angular-devkit/build-optimizer   0.12.0
@angular-devkit/build-webpack     0.12.0
@angular-devkit/core              7.2.0
@angular-devkit/schematics        7.2.0
@ngtools/webpack                  7.2.0
@schematics/angular               7.2.0
@schematics/update                0.12.0
rxjs                              6.3.3
typescript                        3.2.2
webpack                           4.23.1
</code></pre>

**Anything else relevant?**

Note that this error does not arise if `"strictFunctionTypes": true` is not set in `tsconfig.json`

**Comment by petebacondarwin** [comment]
Not sure how we can get around this... The child class needs to have a different static `componentDef` type so that the compiler knows how to use it in compilation but equally we need the `extends` information too...

I wonder if there is some pragma that can tell TS to ignore this check for that line?

**Comment by JoostK** [comment]
@petebacondarwin not at the moment it would seem: https://github.com/Microsoft/TypeScript/issues/19139

**Comment by thorn0** [comment]
Methods are always bivariant, so you can try to redefine some members of `DirectiveDef` using the method syntax.
