### ISSUE TITLE
Route Guards - Evaluation different from Documentation

### ISSUE THREAD

**Issue by darge98** [angular/angular#28082]
# 📚 Docs or angular.io bug report

### Description

Hi, I have a few problems with router guards. 
In the Documentation in section 'Routing & Navigation', Milestone 5, there's written: 

> You can have multiple guards at every level of a routing hierarchy. The router checks the CanDeactivate and CanActivateChild guards first, from the deepest child route to the top. Then it checks the CanActivate guards from the top down to the deepest child route.

I set a CanActivate and CanActivateChild to the same route node, I expected that the CanActivateChild guard was evaluate before than CanActivate, but it isn't.

### What's the affected URL?**
([Here](https://angular.io/guide/router#milestone-5-route-guards))

### Reproduction Steps**
I create a Demo in StackBlitz [Here](https://stackblitz.com/edit/guardsequence)

### Expected vs Actual Behavior**
I expected that CanActivateChild guard was evaluated before than CanActivate guard

## 📷Screenshot
///

## 🔥 Exception or Error
///

### Browser info
///

### Anything else relevant?
///

**Comment by jasonaden** [comment]
This is working as intended. If the `CanActivate` is on the same route as `CanActivateChild`, `CanActivate` should run first. The docs likely need clarification here.

**Comment by darge98** [comment]
@jasonaden Ok, thanks you!
