### ISSUE TITLE
Datepipe on iOS 12.1.2

### ISSUE THREAD

**Issue by Marugera** [angular/angular#28081]
I want so show a date in angular date-pipe in an element. It works on windows and android perfectly, but not on any iOS device. 

```
<div class="date">
      <p>{{ gameStart | date:'short':'UTC+1':'de' }}</p>
</div>
```

This is my error in console and the place were the date should been is empty:
`InvalidPipeArgument: 'Unable to convert "Invalid Date" into a date' for pipe 't'`

Is there a workaround or a solution for that problem?

**Comment by pkozlowski-opensource** [comment]
Please provide a minimal reproduce scenario using stackblitz - this issue is not actionable as-is as we don't know what is the value of `gameStart`, which version of Angular you are using etc.

**Comment by matsko** [comment]
Closing for now. Please reopen if it's still an issue.
