### ISSUE TITLE
Syntax error in Tour of Heroes example

### ISSUE THREAD

**Issue by cskeefer** [angular/angular#28096]
# 📚 Docs or angular.io bug report

### Description

I'm following along the Tour of Heroes tutorial and ran into an issue in Section 2: Displaying a List. It is in the part where the mock-heroes array constant is imported and used. The documentation says to update the HeroesComponent class like:

``` javascript
export class HeroesComponent implements OnInit {
heroes = HEROES;
```
but this throws the following error:
> ERROR in src/app/heroes/heroes.component.ts(11,11): error TS2304: Cannot find name 'HEROES'.

I think it should be changed to:
``` javascript 
export class HeroesComponent implements OnInit {
heroes: Hero[] = HEROES;
```

### What's the affected URL?**
https://angular.io/tutorial/toh-pt2#displaying-heroes

## 🔥 Exception or Error
<pre><code>
ERROR in src/app/heroes/heroes.component.ts(11,11): error TS2304: Cannot find name 'HEROES'.
</code></pre>

### Browser info
Google Chrome 71.0.3578.30

**Comment by cskeefer** [comment]
@manklu thanks for the response. I see my mistake now; I had a ":" in there:

I mistakenly had:
```javascript
heroes: HEROES;
```
rather than using '='. I then changed to hero: Hero[] = HEROES; to get it to work. Anyway, my mistake for not typing in what was clearly in the tutorial. Sorry for wasting time!

**Comment by manklu** [comment]
@cskeefer It was obvious and so only a very small waste of time 😉
