### ISSUE TITLE
Union types cause error even though conditionally segregated with instanceof

### ISSUE THREAD

**Issue by GregKass** [angular/angular#28092]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

I specifically can produce the issue in @angular/forms, but I believe the issue is more generally with the Typescript compiler

### Is this a regression?

 I do not believe so, or I do not know

### Description

 I have a variable defined by a union of multiple types. If I conditionally narrow down to one type in the code below, using instanceof, I see an error due to a type that I am not referencing in the if block. If I try to build using ng serve, the CLI compiler fails with the error below, although active editing only causes the error to show in the console while it states that it compiled successfully, as well as showing the error in my IDE.

Here is the minimal code where the problem occurs:
<pre><code>
  @Input() parentForm: FormGroup | NgModelGroup | NgForm;
  @Input() options: {values: any};

  constructor(private fb: FormBuilder) {};

  ngOnInit() {
    if (this.parentForm instanceof NgModelGroup || this.parentForm instanceof NgForm) {

    } else if (this.parentForm instanceof FormGroup) {
      this.options.values.forEach(value => {
        this.parentForm.addControl(value.value, this.fb.control(""));
      });
    }
  }
</code></pre>
I receive the error:
<pre><code>Property 'addControl' does not exist on type 'FormGroup | NgModelGroup | NgForm'.
  Property 'addControl' does not exist on type 'NgModelGroup'.</code></pre>
According to the Typescript spec, I shouldn't even need an "else if". Just an "else" should work.
## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-f5s4m5?file=src%2Fapp%2Fhello.component.ts

## 🔥 Exception or Error
<pre><code>

error TS2339: Property 'addControl' does not exist on type 'FormGroup | NgModelGroup | NgForm'.
  Property 'addControl' does not exist on type 'NgModelGroup'.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 1.7.4
Node: 8.0.0
OS: darwin x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.2.5
@angular/cli: 1.7.4
@angular/language-service: 6.1.8
@angular/material: 5.2.5
@angular/upgrade: 4.4.7
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.5.13
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack-concat-plugin: 1.4.0
webpack-dev-server: 2.7.1
webpack: 3.6.0
</code></pre>

**Anything else relevant?**

**Comment by matthew-ch** [comment]
This works.
```typescript
  ngOnInit() {
    if (this.parentForm instanceof NgModelGroup || this.parentForm instanceof NgForm) {

    } else {
      const form = this.parentForm;
      this.options.values.forEach(value => {
        form.addControl(value.value, this.fb.control(""));
      });
    }
  }
```

**Comment by skreborn** [comment]
For what it's worth, I believe the reason @matthew-ch's answer works and your original solution doesn't is because TypeScript have no way of knowing when a piece of callback code will be executed - especially  whether it will be done synchronously or not -, and thus can't guarantee that the type of the member won't change by the time that happens. Saving it instead to a local variable ensures that the type is fixed regardless of when the execution happens.

**Comment by alxhub** [comment]
@matthew-ch and @skreborn are correct.

**Comment by GregKass** [comment]
@skreborn was correct. @matthew-ch offered a workaround, not an explanation. Was going to recommend closing it myself but didn't get to it on time. I'm not certain I agree with Typescript's spec, but it is what it is. There is no way a forEach callback is going to mutate the type, unless I intentionally do it myself within the callback. Ironically, I could also mutate it through an iterative loop, which would be allowed.

**Comment by GregKass** [comment]
@matthew-ch Type Guards allow you to narrow down the type of an object within a conditional block. However, type guards are not supported to be extended through callbacks. The reasoning is that the type could somehow be changed externally before the callback execution. If I had looped over the array instead of using ```forEach```, this all would have worked. Personally, I feel this doesn't make sense in this instance where there is a callback in a built-in JavaScript function that is bound in scope by an arrow function. ```forEach``` would never be able to change the type of ```parentForm```. However, TypeScript has to "draw the line" somewhere, and this is where they have chosen.
