### ISSUE TITLE
clang-format is not idempotent

### ISSUE THREAD

**Issue by btford** [angular/angular#2809]
In this diff: https://github.com/angular/angular/commit/27c050be863e24f3a99706a890a44f5ec8814acc

When the code is in the state on the left side of the diff, `clang-format` transforms it to the state on the right. And when it's in the state on the right, `clang-format` transforms it to the state on the left.

**Comment by naomiblack** [comment]
@mprobst can you have a look?

**Comment by vicb** [comment]
clang format has a know issue with template string, see https://github.com/angular/clang-format/issues/13

Closing the issue here it is it already reported on the clang-format repo.
