### ISSUE TITLE
Model is not updated on ngModelChange

### ISSUE THREAD

**Issue by maximedupre** [angular/angular#28107]
# 🐞 bug report

### Description
When the `ngModelChange` event is called, `$event` contains the updated value, but the model isn't updated yet.

I'm not sure if it's the expected behaviour, but according to this change (https://github.com/angular/angular/blob/master/CHANGELOG.md#possible-breaking-changes), the model should contain the new value.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-issue-repro2-vwvdsf

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.2.1
Node: 9.5.0
OS: darwin x64
Angular: 7.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.1
@angular-devkit/build-angular     0.12.1
@angular-devkit/build-optimizer   0.12.1
@angular-devkit/build-webpack     0.12.1
@angular-devkit/core              7.2.1
@angular-devkit/schematics        7.2.1
@angular/cli                      7.2.1
@ngtools/webpack                  7.2.1
@schematics/angular               7.2.1
@schematics/update                0.12.1
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
</code></pre>

**Comment by alexzuza** [comment]
Place `(ngModelChange)` after banana in a box binding so that you will get update model in your second output event.

```
[(ngModel)]="modalGoal.limitDate" (ngModelChange)="limitDateChanged($event)"
```

https://stackblitz.com/edit/angular-issue-repro2-b7peri?file=src/app/app.component.ts

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
