### ISSUE TITLE
Issue with DatePipe when displaying BCE dates and year 0

### ISSUE THREAD

**Issue by brandonwisnicki** [angular/angular#28118]
Hello,
The DatePipe has a slight issue when dealing with any dates during or before Year 0. All dates are one year less than the specified date in the Date var. It is impossible to actually have Year 0 in the Date Pipe. Year 0 will be displayed as 1 BC. 1 BC will be displayed as 2 BC... and so on. Are there any workarounds for this? Thank you.
https://stackblitz.com/edit/angular-yucsdh

**Comment by trotyl** [comment]
> This calendar era is based on the traditionally reckoned year of the conception or birth of Jesus of Nazareth, with AD counting years from the start of this epoch, and BC denoting years before the start of the era. **There is no year zero in this scheme, so the year AD 1 immediately follows the year 1 BC.**

https://en.wikipedia.org/wiki/Anno_Domini

**Comment by brandonwisnicki** [comment]
Yes of course, but Javascript date allows for Year 0000. The issue is that Angular sees Year 0000 as Year 0001 BCE.

**Comment by trotyl** [comment]
![image](https://user-images.githubusercontent.com/6059170/51095781-1bf3d580-17f2-11e9-9a1e-b0734075470e.png)

Year `0` is `1BC` and year `-1` is `2BC`, that's how date stored in JavaScript.

**Comment by AndrewKushnir** [comment]
As @trotyl described, the DatePipe's logic is consistent with native JavaScript and works as expected. Thank you.
