### ISSUE TITLE
ngcc: no ngModuleDef and ngInjectorDef on BrowserModule for esm5 and fesm5

### ISSUE THREAD

**Issue by stefanocke** [angular/angular#28110]
# 🐞 bug report

### Affected Package

- ivy-ngcc
- angular/platform-browser

### Description

- After running ivy-ngcc, there are no ngModuleDef and ngInjectorDef on BrowserModule for esm5 and fesm5
- For esm2015 and fesm2015 they are generated correctly.
- For other modules like ApplicationModule, they are generated for all formats, including esm5 and fesm5.
- There are markers __modified_by_ngcc_for_esm5__ and __modified_by_ngcc_for_fesm5__ , so there is some prove that ngcc has at least tried to process esm5 and fesm5 for angular/platform-browser

## 🔬 Minimal Reproduction
- Run ivy-ngcc in Angular 7.2.0 project.

## Versions
- Angular Version: 7.2.0

**Comment by alexzuza** [comment]
Looks like it has been covereder by https://github.com/angular/angular/pull/27848. But it has not been released yet.

Can you try it with current version of @angular/compiler-cli?

**package.json**
```
"devDependencies": {
  "@angular/compiler-cli": "github:angular/compiler-cli-builds"
}
```

**Comment by stefanocke** [comment]
@alexzuza , thank you. I am quite sure you are right. 
Unfortunately, I cannot verify, since with github:angular/compiler-cli-builds I get an error now:
```
Compiling @angular/common - fesm2015
TypeError: Cannot read property 'usesOnChanges' of undefined
    at addFeatures (.....\node_modules\@angular\compiler\bundles\compiler.umd.js:14997:28)
    at Object.compileDirectiveFromMetadata (.....\node_modules\@angular\compiler\bundles\compiler.umd.js:15009:9)
```

**Comment by alexzuza** [comment]
@stefanocke Try using the same version of other angular packages

**Comment by stefanocke** [comment]
@alexzuza works. Thanks again.
