### ISSUE TITLE
Imports with alias broken since Angular 7.2 & TypeScript 3.2

### ISSUE THREAD

**Issue by FrancescoBorzi** [angular/angular#28123]
# 🐞 bug report

### Affected Package

Not sure which specific package is causing the issue.

### Is this a regression?

Yes, this issue has been introduced when I upgraded FROM:

Angular `^7.1.4`
TypeScript `~3.1.6`

TO:
Angular `^7.2.0`
TypeScript `~3.2.2`

### Description

Whenever I used alias imports, such as:

`import { of as observableOf } from 'rxjs';`

(and similar imports) it is going to fail in PRODUCTION with the following console error:

> main.b41b13f112713e7d9a13.js:1 ERROR ReferenceError: observableOf is not defined

this issue affects only production, development mode is fine.

Workaround: remove this kind of aliases (i.e. just use `import { of } from 'rxjs';`).

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.2.1
Node: 10.15.0
OS: linux x64
Angular: 7.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.2.1
@angular/cli                      7.2.1
@ngtools/webpack                  7.0.7
@schematics/angular               7.2.1
@schematics/update                0.12.1
rxjs                              6.3.3
typescript                        3.2.2
webpack                           4.19.1

</code></pre>

**Comment by ericmartinezr** [comment]
Possibly related https://github.com/angular/angular/issues/28078 (sounds similar)

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/13212

**Comment by alan-agius4** [comment]
Kindly update the `@angular-devkit/build-angular` packages to the current latest version `0.12.1`

**Comment by FrancescoBorzi** [comment]
ok then I'm closing this, thanks guys
