### ISSUE TITLE
method param names are being incorrectly linkyfied

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#28120]
- Go to https://angular.io/api/common/Location#go
- mouse over "state"

Expected: not a link

Actual: link to https://angular.io/api/animations/state

<img width="1226" alt="screen shot 2019-01-13 at 11 57 59 pm" src="https://user-images.githubusercontent.com/216296/51101348-2761e500-178f-11e9-9779-1de44fa199df.png">

**Comment by sonukapoor** [comment]
@IgorMinar Can I help with this request?

**Comment by gkalpak** [comment]
`state` is no longer incorrectly linkified, but now the `query` param is 🤦‍♂️
