### ISSUE TITLE
best way for pass very big object between two pages with routing

### ISSUE THREAD

**Issue by shomid** [angular/angular#28128]
I want to pass big object between two pages .
project hangs(chunk error) when using of queryparam for routing big object.
What is the best way for pass big object between two pages with routing ?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
