### ISSUE TITLE
Do not deprecate Injector.get(TOKEN_NAME)

### ISSUE THREAD

**Issue by mohyeid** [angular/angular#28136]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
Currently,  `Injector.get(token:any) ` is marked as deprecated. Its in favor of using `.get(InjectionToken<T>)`. The last one does not exactly do the same thing that `.get(token)` does.  `.get(token)` allows you to get dynamically injected services only by their token name, which in my case is saved in the database. Now with the fact that you have to create an `InjectionToken` and share it across modules/libs/projects, this builds unnecessary dependency. Example: 

Shared Module: have abstract service 
Module2: allow dynamically providing implementations of base service 
Module3 or parent module: Implements abstract base services, and provide them to Module2. 

With `.get(token)` you could just use the name of the service and only depend on the shared module to resolve the services. With `InjectionToken`, you will have to pass the original token from the parent module and import it in Module2, which creates another dependency that we can avoid. 

 Example: https://stackblitz.com/edit/angular-injection-token-test?file=src%2Fapp%2Fmodule2%2Fservice-provider.service.ts 

### Describe the solution you'd like
 Maybe keep `.get(token)`, or allow `InjectionToken` to have a similar behavior to the `.get(token)`. 

### Describe alternatives you've considered
 Implement a bad design and have circular dependency? I hope this will not be a solution. 

Please, note I opened this  as a feature as it was opened as a bug before and it got closed: https://github.com/angular/angular/issues/27112

**Comment by alxhub** [comment]
Hello @mohyeid! I think you might have misunderstood which parts of the API are deprecated. It's only the untyped variant which will be removed.

```typescript
Injector.get(token: any, notFoundValue?: any): any;`
```

is the deprecated signature. The other flavor of `get` is not going away - that is:

```typescript
Injector.get<T>(token: Type<T>|InjectionToken<T>, notFoundValue?: T, flags?: InjectFlags): T;
```

Note that this accepts either a `Type<T>` or an `InjectionToken<T>`. That means that `.get(Service)` is perfectly fine (a `Type` is any constructable class/function). This mostly affects the ability to use string tokens (`{provide: 'someStringToken'}`), which aren't accepted under the typed API.

**Comment by mohyeid** [comment]
Hello @alxhub thanks for the reply, but I think the purpose of the ask was exactly for the string token. The case I am providing in the stackblitz is an example of a string token that is used to differentiate between 2 implementations of a base class. 

`{
    // provide: INJECTED, // Works, but build dependency 
    provide: 'Impl1',
    useClass: BaseImpl1Service
  }, {
    provide: 'Impl2',
    useClass: BaseImpl2Service
  }
`
The consumable is not aware of the different implementations, but its only aware of the string token and the base class. Using the `Type<T>` and providing the base class, will not be able to solve the 2 implementations of the class. So to best what I know, string token is the way to do.

**Comment by larssn** [comment]
It's just that VSCode tends to favour the untyped function.
Currently you have to do `injector.get<MyComponent>(MyComponent);` in order to not get the deprecation warning, which seem redundant. This type would normally be inferred, but it can't since both signatures exist.

**Comment by mdudek** [comment]
I'm facing problem. I have implemented plugin system where plugins are isolated projects (They are built separately) and providing some components using string provider key.  The main app is loading these plugins using SystemJS loader and need to get components provided by these loaded plugins. Everything is working fine now, but I can't find a away, how to use this pattern without string provider keys.

**Comment by mlc-mlapis** [comment]
@mdudek ... I understand what you mean. If the string provider key is deprecated you can still use another way how to get those components from your plug-ins module. We use a map like for example:
```
export default class ProductSet001Module {
	cmps: Map<string, Type<any>> = new Map();
	constructor() {
		this.cmps.set('product-set-001', ProductSet001Component);
	}
}
```
