### ISSUE TITLE
@InjectPromise behaves as @Inject

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#2813]
This may relate to [1623](https://github.com/angular/angular/issues/1623) as when I am using `@InjectPromise(MyService) tf: Promise<MyService>` on a component I get an exception telling me that I cannot load `MyService` synchronously because it's provided as a promise:

![screenshot 2015-07-01 10 03 13](https://cloud.githubusercontent.com/assets/1479737/8450162/5d48d596-1fd8-11e5-9ac4-31fe23c1502e.png)

**Comment by PascalPrecht** [comment]
@rolandjitsu which Angular version are you using? There has been a huge refactoring lately in the DI system https://github.com/angular/angular/commit/22d39438315ec718c860cef46a1c14acac828065

That refactoring removed `@InjectLazy` and `@InjectPromise` and also `.toAsyncFactory()` binding.

**Comment by rolandjitsu** [comment]
@PascalPrecht I am using alpha `28`. If those were removed, what can I use for async DI?

**Comment by PascalPrecht** [comment]
@rolandjitsu I don't know tbh. Trying to catch up with the latest changes, but it's pretty much a full-time job. :(

**Comment by PascalPrecht** [comment]
@rolandjitsu apparently this is now done using `DynamicComponentLoader` https://github.com/angular/angular/commit/22d39438315ec718c860cef46a1c14acac828065#diff-de154d7de5803f418bd0c8b5438f444eL86

**Comment by rolandjitsu** [comment]
@PascalPrecht yeah, I too have a hard time catching up with all the changes, but it seems like it's stabilizing a little bit and some of the API hasn't drastically changed. I think this refactoring is not yet in the version I am using.

**Comment by rolandjitsu** [comment]
@PascalPrecht actually, it seems like I can find the same code in the npm version, even though this commit seems only 4 days old.

**Comment by rolandjitsu** [comment]
It seems like `dynamicComponentLoader.loadAsRoot` expects a directive (`Error during instantiation of Test! (Todos -> Test). ORIGINAL ERROR: No Directive annotation found on Test2`), so I am unsure if I can load a service, but that may be due to the version I have.

**Comment by gdi2290** [comment]
`@InjectPromise`, `@ InjectLazy` and `.toAsyncFactory` have been removed for now via https://github.com/angular/angular/commit/22d39438315ec718c860cef46a1c14acac828065

**Comment by rolandjitsu** [comment]
@gdi2290 yeah, @PascalPrecht has mentioned that and I thought I could use the `DynamicComponentLoader ` to load the service async, but that did not work. So instead I had to do the following (you can see the source [here](https://github.com/rolandjitsu/ng2-play/blob/master/src/app/services.ts)):
```js
bind(TodoStore).toFactory((promise: Promise<Firebase>) => promise.then((ref: Firebase) => new TodoStore(ref)), [firebaseRef]),
bind(firebaseRef).toFactory(
    () => {
        let defer: Defer<Firebase> = new Defer();
        let authHandler = (auth: FirebaseAuthData) => {
            if (auth !== null) {
                root.offAuth(authHandler);
                let ref: Firebase = root.child('/chores/' + auth.uid);
                defer.resolve(ref);
            }
        };
        root.onAuth(authHandler);
        return defer.promise;
    }
)
```
The only downside is that when I ask for the `TodoStore` dependency it's a promise. I am not sure if there is a way to get the value of the promise when I ask for the dependency instead of the promise.

**Comment by gdi2290** [comment]
for now you just have to deal with resolving the promise after injecting it until they fix the async problems with the injector. If you want to delay bootstrapping (you shouldn't do this) you would wait until firebase is ready before importing your app (simplest solution)

```html
<script>
FirebaseReadyPromise.then(function(firebaseRef) {
  return System.import('app').then(function(module) {
    return module.main(firebaseRef);
  });
});
</script>
```

**Comment by rolandjitsu** [comment]
@gdi2290 I think I will stick with what I currently have instead of delaying the app bootstrap. Do you have any idea how the async injection will be handled in the future?

**Comment by masaeedu** [comment]
It's weird that it's been removed, but if the team is taking suggestions on what shape it should take on in the future, it would be great if we had something similar to the following:

    class FooServiceFactory {
        @InjectorFor(FooService)
        static loadFooService(): Promise<FooService>() {
            // Return a promise that resolves to an instance of FooService
        }
    }

**Comment by mhevery** [comment]
Stale, as this feature has been removed.
