### ISSUE TITLE
Angular decorators do not work with symbol keys

### ISSUE THREAD

**Issue by waterplea** [angular/angular#28148]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 No

### Description

 Angular decorators (namely HostListener/HostBinding) do not work with symbols, only strings as keys.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/host-listener-bug

## 🌍  Your Environment

**Angular Version:**
<pre><code>7.0.0</code></pre>

**Anything else relevant?**

Check out stackblitz I've linked — I've been experimenting with some decorators, not really relevant what I was trying to do but I noticed that if I try to feed `HostListener` symbols rather than string it didn't work. In **`decorator.ts`** file there are 2 lines, one of which is commented — you can see that if you use `string` as a key — callback is called on click, but if you use `symbol` it is not, although the property exists on the target. Looks like there is some conversion to `string` somewhere down the line in Angular core. However TypeScript says that `propertyKey` in `MethodDecorator` can be `string | symbol`.

**Comment by alxhub** [comment]
Sorry, this is not and will not be supported - our compiler looks for Angular decorators specifically. You can't inherit, extend, or otherwise wrap them.
