### ISSUE TITLE
Router.navigateByUrl does not support question mark "encoded" by HttpUrlEncodingCodec

### ISSUE THREAD

**Issue by kondi** [angular/angular#28154]
# 🐞 bug report

### Affected Package
The issue is caused by package `@angular/router`, but `@angular/common/http` is related.

### Description

The querystring serialized with `HttpParams` using the default `HttpUrlEncodingCodec` is not compatible with `Router.navigateByUrl` if a value contains a question mark.

The documentation (https://github.com/angular/angular/blob/7.2.0/packages/common/http/src/params.ts#L25) of `HttpUrlEncodingCodec` states it is using `encodeURIComponent` to serialize and URL parameter keys and values:

> A `HttpParameterCodec` that uses `encodeURIComponent` and `decodeURIComponent` to serialize and parse URL parameter keys and values.

In fact, this is not true. As far as I have found, the difference and reasoning is explained here: https://github.com/angular/angular/blob/7.2.0/packages/http/src/url_search_params.ts#L55 (By the way, some part of this comment could be migrated from this deprecated `URLSearchParams` class to its replacement `HttpParams`).

> By default, `QueryEncoder` encodes keys and values of parameters using `encodeURIComponent`, and then un-encodes certain characters that are allowed to be part of the query according to IETF RFC 3986: https://tools.ietf.org/html/rfc3986.
>
> These are the characters that are not encoded: `! $ \' ( ) * + , ; A 9 - . _ ~ ? /`
>
> If the set of allowed query characters is not acceptable for a particular backend, `QueryEncoder` can be subclassed and provided as the 2nd argument to URLSearchParams.

In this issue, it is not "a particular backend", it is actually the angular router which does not handle well the question mark character if it is not encoded. If I override the  `encodeValue` of `HttpUrlEncodingCodec` to really use `encodeURIComponent`, the router is working as expected.

Please fix the router to support these query params in `Router.navigateByUrl`. Otherwise change the `HttpUrlEncodingCodec` to encode the question mark as well to make it consistent across the code of the framework.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-74yems?file=src%2Fapp%2Fapp.component.ts

## 🌍  Your Environment

https://stackblitz.com/edit/angular-74yems?file=package.json

**Comment by jasonaden** [comment]
Thanks for the issue. Agreed, these should work well together. Putting the `community-help` label on and if anyone has time to look into and fix this issue, it should be relatively straightforward.

**Comment by jasonhodges** [comment]
I believe this is related to the open PR https://github.com/angular/angular/pull/19710

**Comment by mmaterowski** [comment]
I believe this issue is solved already. After updating all dependencies in @kondi stackblitz url string seems to be correctly handled
https://stackblitz.com/edit/angular-sxrxc2?file=src/app/app.component.ts

**Comment by JeanMeche** [comment]
@atscott Per above, you can close this !
