### ISSUE TITLE
Currency pipe do not throw exception when gets NaN 

### ISSUE THREAD

**Issue by temyrrian-dev** [angular/angular#28153]
# 🐞 bug report

### Description

So, hello, guys. I find out that currency pipe do not throw exception when gets NaN. Its just does nothing and return nothing. I don't sure does it's really bug. But maybe in this case currency pipe may rise exception.

**Angular Version:**
<pre><code>

7.1
</code></pre>

**Comment by pkozlowski-opensource** [comment]
It is by design, check here: https://github.com/angular/angular/blob/06e5bf16613cc57ed6bf1fdf4bd687f9b5f0a182/packages/common/src/pipes/number_pipe.ts#L196
