### ISSUE TITLE
Angular language service - error when using ngIf and strictNullChecks

### ISSUE THREAD

**Issue by klemenoslaj** [angular/angular#28164]
# 🐞 bug report

### Affected Package
@angular/language-service

### Is this a regression?

No.

### Description

Language service is not working correctly with `ngIf` and `strictNullChecks`.

There is a [documentation](https://angular.io/guide/template-syntax#the-non-null-assertion-operator---) about this exact thing, but it makes no sense because of the following:

1. **Following TypeScript code is OK with full `strict` mode enabled**

```typescript
public obj?: { val: string };

if (this.obj) {
  console.log(this.obj.val); // IT'S ALL GOOD
}
```

2. **The same logic in Angular template throws an error trough language service:**

```html
<ng-container *ngIf="obj">{{ obj.val }}</ng-container>
```

This really makes no sense, and the official solution is to add `!` after `obj`, like `{{ obj!.val }}` which feels more like a workaround.

I did as well found out that creating a variable in ngIf directive will prevent the error from appearing, therefore it is inconsistent as well:

```html
<ng-container *ngIf="obj; let obj">{{ obj.val }}</ng-container>
```

## 🔬 Minimal Reproduction

In any latest Angular project, that is using `@angular/language-service` apply code snippets from the description.

## 🔥 Exception or Error

`[Angular] The expression might be null`

## 🌍  Your Environment

**Angular Version:**

```
Angular CLI: 7.2.1
Node: 10.15.0
OS: darwin x64
Angular: 7.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router
```

**Anything else relevant?**

If required I can create a repository with the code snippets. I didn't do so because it should be easy to reproduce. If I am wrong, please let me know and I will provide the repo.

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/21954

**Comment by klemenoslaj** [comment]
Indeed, I just mentioned #21954 myself.
Mentioned issue treats this problem as a feature request, while this issue states it's a bug.

---

If it really is a feature request feel free to close this issue.

**Comment by dirkluijk** [comment]
I think with Ivy the language service will be rewritten. Maybe typescript strict checks will be more easily supported?

**Comment by dzuspiir** [comment]
Another way to access the property using bracket notation:

```javascript
<ng-container *ngIf="obj">{{ obj['val'] }}</ng-container>
```

Which suppresses the error but now you have another inconsistency by having a different way of accessing the property.

**Comment by aleksandar-kandzhichki** [comment]
Any update on this? It is really annoying having the whole HTML spammed of this error :(

**Comment by thw0rted** [comment]
Has anybody tried this in Ivy yet?  I came looking for a more recent report of #18248 because that issue just got closed by the lock-bot, and I wanted to make sure it's still being tracked at all.  (I *think* that's the same issue being seen here?)

**Comment by reed-lawrence** [comment]
Any update to this issue?

**Comment by DmitryEfimenko** [comment]
+1

**Comment by cyrilletuzi** [comment]
Note: with Angular 9 (so with Ivy), even with all strict flags enabled (ie. `noImplicityAny`, `strictNullChecks`, `fullTemplateTypeCheck` and even the new very agressive `strictTemplates`), the code compiles well if `null` are correctly managed. So this is an issue with the language service, not the compiler.

**Comment by darchigh** [comment]
this is preventing us from using strictTemplates sadly :-(

**Comment by thw0rted** [comment]
Trackback to #34572 which may or may not be the same thing (specific to `async` pipe).

**Comment by Lonli-Lokli** [comment]
I believe we should live with it until language service be rewritten with ivy engine.
Maybe in angular 17...

**Comment by JoostK** [comment]
> I believe we should live with it until language service be rewritten with ivy engine.
> Maybe in angular 17...

v12 it is!

With the Ivy language service this issue has been resolved; compiler options such as `strictNullChecks` now work correctly together with `ngIf` narrowing.
