### ISSUE TITLE
multiple templateUrls for @Component definition 

### ISSUE THREAD

**Issue by xmlking** [angular/angular#28161]
# 🚀 feature request

### Relevant Package

This feature request is for @angular/core

### Description
Add ability to use multiple templateUrls for component declaration 

**Why:** want to reuse base template with multiple derived components 
### Describe the solution you'd like

```ts
@Component({
  selector: 'ngx-accounts-table',
  templateUrl: ['../base-entity.component.html', 'accounts-entity.component.html'],
  styleUrls: ['../base-entity.component.scss', 'accounts-entity.component.scss'],
})
export class AccountsTableComponent extends EntitiesComponent<Account, AccountService> {
}
```

### Describe alternatives you've considered

```ts
const entityHtmlTpl = require('../base-entity.component.html');
const accountsHtmlTpl = require('./accounts-entity.templates.html');

@Component({
  selector: 'ngx-accounts-table',
  // FIXME: AOT build not working with require
  template: entityHtmlTpl + accountsHtmlTpl,
  styleUrls: ['../base-entity.component.scss', 'accounts-entity.component.scss'],
})
export class AccountsTableComponent extends EntitiesComponent<Account, AccountService> {
}
```

### Example 
example code, showcasing need for the request:

https://github.com/xmlking/entity-demo

e.g., `notifications.component.html`  and  `subscriptions.component.html` has 99% same code that can be abstracted.

**Comment by dirkluijk** [comment]
I think you should focus on reusing components, not templates. Not templates, but components are first-class citizens in Angular.

**Comment by manklu** [comment]
@dawidgarus
This doesn't help you with the AOT compiler

**Comment by manklu** [comment]
@dirkluijk

In the case of extending a component, the child **must** provide a complete template. In this case it would be useful to reuse parts of the parent template.

**Comment by mohammedzamakhan** [comment]
Styles does not need any AOT (Ahead of time compilation - which is the way to create optimized production app), but the Angular does need to Templates for AOT compilation. If you understand the component Architecture, you should be able to reuse the code between two different component.

You need to create an extra component, in your case `BaseEntityComponent`, and then include that in accounts-entity.component.html file

**Comment by dawidgarus** [comment]
@manklu I'm using custom loader to transform templates and it works fine with AOT when using `@ngtools/webpack`.

**Comment by xmlking** [comment]
@mohammedzamakhan thank you  for your recommendation of component composition instead of inheretiency. However for my usecase, inheritance is ideal and allow me reuse code. I can change something in base template and let all derived components take advantage of it. We have 30+ table views with same CRUD style user interactions. But we has to customize some table views without edit options (readonly), have  some custom column rendering requirements and much more... .  My ask is to allow build-time joining  of 2+ templates as @manklu suggested but natively...

**Comment by GeorgiyZhuravlev** [comment]
Actually, It would work just great when dealing with multiply `<ng-template>`s.
Some components may have many ng-templates defined in a component's template.
It would be fine to be able to spread these to separate files.
One of the use cases (our web app):
Some components have the template "to look like and work" somehow + couple of `<ng-template>`s to list small UI tools, like buttons/inputs/dropdowns... We then insert them to the required toolbars outside of the component with the CDK Portals feature. Very convenient! Every component brings its tools with it. Those do not deserve to be separate components.

**Comment by betterbuiltcows** [comment]
Here is another use-case for this feature request... (1) A model entity with many fields, (2) A CRUD form and component to view/edit all fields, (3) A search form and component with a subset of the same fields.

There is a lot of overlap, but not an exact match, between (2) and (3).   A few fields are not appropriate for search, some need a slightly different data entry method, and some field groupings have a different precedence in (2) vs (3) per user requirements. The feature requested here would be a useful tool in solving this problem in the cleanest possible manner.

So for example, consider that component (2) has fields that could be contained in multiple html files A-B-C-D-E.  And component (3) has fields contained in those same html files but needs the fields like this, A-C-E-D.

Contrary to some of the thoughts above, joining template files to accomplish this is actually a very good example of composition.  The composition of components on the page is very important, but there is also a composition of elements within each component's space.  The feature request would provide a lot of flexibility with this lower level of composition.

**Comment by lixaotec** [comment]
+1. This is extremely useful.

**Comment by lixaotec** [comment]
> If you are using webpack, then you could write a loader that would work like this:
> `templateUrl: 'prepend-template?path=../base-entity.component.html!accounts-entity.component.html'`

May you provide your custom loader?

**Comment by lixaotec** [comment]
@xmlking how did you solve this? Workaround maybe?

How to achieve a webpack plugin like prepend-template?

tks

**Comment by lixaotec** [comment]
@dawidgarus tried everything to build a prepend-template loader, that concatenates like the expression you said, howerver when Aot builds, it always end in error that it 'coulnt resolve resource 'prepend-template?path=../base-entity.component.html!accounts-entity.component.html'. Please any help?

It does work with JIT

**Comment by lixaotec** [comment]
Is it possible to add a baseTemplateUrl property inthe anotation? 

`
@Component({
  selector: 'ngx-accounts-table',
  baseTemplateUrl: '../base-entity.component.html',
  templateUrl: './accounts-entity.templates.html',
  styleUrls: ['../base-entity.component.scss', 'accounts-entity.component.scss'],
})
export class AccountsTableComponent extends EntitiesComponent<Account, AccountService> {
}
`

And make my loader concatenate them?

**Comment by lixaotec** [comment]
just dont understand why this works with dev-server but not with builder 
templateUrl: 'prepend-template?path=../base-entity.component.html!accounts-entity.component.html'

**Comment by mlc-mlapis** [comment]
@lixaotec Because JIT and AOT compilations are totally different processes with different functionality.

For AOT, the returned value of the `templateUrl` property has to be:

> **That means that the value is a URL value relative to the component class file.**

This is not true in your case!

**Comment by alxhub** [comment]
Closing as won't fix - the complexity here is far too great for the limited utility.

**Comment by morbargig** [comment]
I think you should consider it in next version
I have few complex situations that will be easily fixed with this thing

It can make angular to the best framework ever 
however 'ComponentFactoryResolver' if i can change the template with this service or an outer please let me know

**Comment by zohar1000** [comment]
I join the request to provide inclusion of external templates in a component, this is extermely useful in medium and large apps.
We have a few large projects where we face a repeating issue in them, pieces of templates are duplicated across components.
I got to this thread after searching for a solution, I hope the angular team will implement it. 
The community voting is not always effective as almost every angular programmer I know of is not signed to the community, so voting based on count does not neccessarily reflect the need.
