### ISSUE TITLE
Ng-template render twice under certain conditions

### ISSUE THREAD

**Issue by ovchinnikov** [angular/angular#28178]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?
No

## 🔬 Minimal Reproduction
I've created two online demos:
1) https://stackblitz.com/edit/angular-kyx7r6?file=src%2Fapp%2Fapp.component.html
2) https://stackblitz.com/edit/angular-9dgmdg?file=src%2Fapp%2Fapp.component.html
 
The difference is only in one **inner-component** that is placed inside _ng-template_.
 
## Actual result
_ng-template_ was rendered once in the first example and two times - in the second one
 
## Expected result
_ng-template_ should be rendered once in both examples

**Comment by alexzuza** [comment]
Seems it has something to do with a lot of ContentQueries.

Under certain condition your query `@ContentChildren(InnerComponent)` becomes dirty during createEmbeddedView:

https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/core/src/view/query.ts#L56-L68

The key point here is the condition:

```
(nodeDef.query !.filterId & queryIds) === nodeDef.query !.filterId) { 
```

We have two views here: `AppComponentView(View_AppComponent_0)` and child `TemplateView(View_AppComponent_1)`

The `dirtyParentQueries` method from the code above takes `nodeMatchedQueries`. It's set of bit masks combined from child view(View_AppComponent_1). And then the code loops through the nodes from View_AppComponent_0 and checks dynamic content queries(ContentChildren)

Now let's look at the generated ngfactory:

![bug](https://user-images.githubusercontent.com/4223314/51387281-e37c3080-1b3e-11e9-986c-f0c10cc7caac.png)

In the picture above we see that we have queryDef with id 2. And also in the child view we have query match `[[34, 4], ..]`  For those ids (2 and 34) Angular compiler generates `filterId` via the following formula:

https://github.com/angular/angular/blob/885f1af509eb7d9ee049349a2fe5565282fbfefb/packages/core/src/view/util.ts#L185-L187

It's like a mask generator and js works with 32 integers. 

We can see that filterId for 2 and 34 will be the same: 4 (`100` in binary format)

So the condition

```

 (nodeDef.query !.filterId  & queryIds)  === nodeDef.query !.filterId) { 
                           ||                     ||
                   filterId(2)       (filterId(34) | other matched queries)
```

will result in `true`


Also here is the same bug but with a bit different structure https://stackblitz.com/edit/angular-zf8xwk?file=src%2Fapp%2Fapp.component.html

**Comment by pkozlowski-opensource** [comment]
This is fixed in Angular v9 running on ivy: https://ng-run.com/edit/PuZf1bZlNeWwkyV5m0J9
