### ISSUE TITLE
some properties in API docs are not linkyfied e.g. ApplicationRef#isStable

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#28171]
repro:

1. go to https://angular.io/api/core/ApplicationRef#isStable
2. try to click on the "isStable"

(I usually do this to obtain the deep link, the deep link above was constructed manually for the purposes of the repro)

expected result: "isStable" is a link to #isStable
actual result: "isStable" is just a plain text

Screenshot:
<img width="1139" alt="screen shot 2019-01-15 at 9 47 45 pm" src="https://user-images.githubusercontent.com/216296/51229002-8fd7d000-190f-11e9-9579-79eda6ed4807.png">

**Comment by gkalpak** [comment]
I assume this happens because there are several `isStable`s and we can't disambiguate. Maybe we could have a disabiguator that prioritizes symbols inside the same doc (e.g. link to `ApplicationRef#isStable` from within `ApplicationRef` docs).

**Comment by JeanMeche** [comment]
Even worse, on the same `ApplicationRef` page, the `tick` methods links to https://angular.io/api/core/testing/tick
