### ISSUE TITLE
angular.io pages not loading - headers do not match, promise was rejected

### ISSUE THREAD

**Issue by fmflame** [angular/angular#28184]
# 📚 Docs or angular.io bug report
 Description

Trying to load pages like this one: [https://angular.io/cli/generate#application](https://angular.io/cli/generate#application) results in 
```
REQUEST FOR DOCUMENT FAILED.
We are unable to retrieve the "cli/generate" page at this time. Please check your connection and try again later.
```

### What's the affected URL?**
Pretty much all pages. For example all pages from the cli section like this one:
[https://angular.io/cli/generate#application](https://angular.io/cli/generate#application) 

### Reproduction Steps**
Just try to open any page like: [https://angular.io/cli/generate#application](https://angular.io/cli/generate#application) 

### Expected vs Actual Behavior**
I expect to be able to access the angular.io docs...

## 🔥 Exception or Error
<pre><code>
polyfills.484bababb6e0f3a2b3fc.js:sourcemap:1 A preload for 'https://angular.io/generated/navigation.json' is found, but is not used because the request headers do not match.
</code></pre>
<pre><code>
GET https://angular.io/assets/images/favicons/favicon-16x16.png net::ERR_CONNECTION_TIMED_OUT
</code></pre>
<pre><code>
The FetchEvent for "https://angular.io/generated/docs/cli/generate.json" resulted in a network error response: the promise was rejected.
</code></pre>
<pre><code>
ngsw-worker.js:589 Uncaught (in promise) Error: Response not Ok (fetchAndCacheOnce): request for https://angular.io/generated/docs/cli/generate.json returned response 504 Gateway Timeout
</code></pre>
<pre><code>
polyfills.484bababb6e0f3a2b3fc.js:1 GET https://angular.io/generated/docs/cli/generate.json net::ERR_FAILED
</code></pre>
<pre><code>
ngsw-worker.js:589 Uncaught (in promise) Error: Response not Ok (fetchAndCacheOnce): request for https://angular.io/generated/docs/cli/generate.json returned response 504 Gateway Timeout
</code></pre>
<pre><code>
main.50c889384f59db4dbadf.js:1 ERROR Error: Error fetching document 'cli/generate': (Http failure response for (unknown url): 0 Unknown Error)
</code></pre>
<pre><code>
GET https://angular.io/angular_whiteTransparent_withMargin.69f1fb57db78bb0b878f.png 504 (Gateway Timeout)
</code></pre>
<pre><code>
The resource https://angular.io/generated/docs/index.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
</code></pre>
<pre><code>
The resource https://angular.io/generated/navigation.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
</code></pre>
<pre><code>
GET https://angular.io/assets/images/favicons/favicon-32x32.png net::ERR_CONNECTION_TIMED_OUT
/assets/images/favicons/favicon-16x16.png:1 GET https://angular.io/assets/images/favicons/favicon-16x16.png net::ERR_CONNECTION_TIMED_OUT
An unknown error occurred when fetching the script.
Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
/assets/images/favicons/favicon-96x96.png:1 GET https://angular.io/assets/images/favicons/favicon-96x96.png net::ERR_CONNECTION_TIMED_OUT
/assets/images/favicons/favicon-194x194.png:1 GET https://angular.io/assets/images/favicons/favicon-194x194.png net::ERR_CONNECTION_TIMED_OUT
/assets/images/favicons/favicon.ico:1 GET https://angular.io/assets/images/favicons/favicon.ico net::ERR_CONNECTION_TIMED_OUT
</code></pre>

### Browser info
Google Chrome
Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by fmflame** [comment]
I tried to unregister the web worker and now I get `This site can’t be reached` for all of the website...

**Comment by gkalpak** [comment]
The page loads fine for me. It seems like something is wrong with the SW.
You were not offline, right?

**Comment by wKoza** [comment]
Can you test it with the mode private navigation ? You don't have a chrome plugin shady ?

**Comment by fmflame** [comment]
I tested going incognito, tested with all extensions disabled and tested online of course ;) All my other websites open except this one.

Here is what happens when i `tracert angular.io`: 
```
1    <1 ms    <1 ms    <1 ms  www.net.is [192.168.121.1]
  2     1 ms     1 ms    <1 ms  77.71.120.1
  3     1 ms    <1 ms     1 ms  router.goonet.org [77.71.116.2]
  4     2 ms     1 ms     1 ms  85.14.40.129
  5     1 ms     1 ms     1 ms  85.14.40.65
  6     7 ms     7 ms     7 ms  1323.po2.cr2.sof2.evolink.net [85.14.22.196]
  7    38 ms     7 ms     7 ms  15.xe-0-0-0.br2.sof2.evolink.net [85.14.2.135]
  8     7 ms     7 ms     7 ms  85.14.2.8
  9    24 ms    19 ms    22 ms  85.14.40.187
 10     *        *        *     Request timed out.
 11     *        *        *     Request timed out.
 12     *        *        *     Request timed out.
 13     *        *        *     Request timed out.
 14     *        *        *     Request timed out.
 15     *        *        *     Request timed out.
 16     *        *        *     Request timed out.
 17     *        *        *     Request timed out.
 18     *        *        *     Request timed out.
...
```

**Comment by petebacondarwin** [comment]
@fmflame any update on this problem?

**Comment by fmflame** [comment]
I just checked it out, it was not working yesterday but it it is. Not sure if my ISP did something about it. I did call them, but no one got back to me.
Here is the updated tracert:
```
  1     3 ms    <1 ms    <1 ms  www.net.is [192.168.121.1]
  2    <1 ms    <1 ms    <1 ms  77.71.120.1
  3    <1 ms    <1 ms    <1 ms  router.goonet.org [77.71.116.2]
  4     1 ms     1 ms    <1 ms  85.14.40.129
  5     1 ms    <1 ms    <1 ms  85.14.40.65
  6     7 ms     7 ms     7 ms  1323.po2.cr2.sof2.evolink.net [85.14.22.196]
  7     7 ms     7 ms     7 ms  15.xe-0-0-0.br2.sof2.evolink.net [85.14.2.135]
  8    17 ms     7 ms     7 ms  xe-0-2-0-302.cr0-sof1.ip4.gtt.net [46.33.95.225]
  9    36 ms    33 ms    42 ms  xe-1-0-2.cr0-buc1.ip4.gtt.net [213.200.114.102]
 10    28 ms    28 ms    28 ms  ip4.gtt.net [46.33.78.154]
 11    53 ms    52 ms    53 ms  ae-18.r24.amstnl02.nl.bb.gin.ntt.net [129.250.3.62]
 12    52 ms    53 ms    52 ms  ae-7.r03.amstnl02.nl.bb.gin.ntt.net [129.250.2.103]
 13    52 ms    52 ms    52 ms  81.20.67.250
 14    48 ms    48 ms    48 ms  151.101.1.195
```

So problem is somehow resolved. Thanks for looking into this. Good to have access to the docs again :)

**Comment by petebacondarwin** [comment]
Glad you are back online! Please open another issue if the problem recurs or you have more information.
