### ISSUE TITLE
`ng_module` with `--define=compile=aot` fails outside this repository

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#28182]
# 🐞 bug report

### Affected Package
The issue is caused by package `@angular/bazel`

### Is this a regression?

This problem was fixed in the past via https://github.com/angular/angular/pull/25581 but it has resurfaced.

### Description

When using `ng_module` with `--define=compile=aot` outside this repository, the TS compilation fails.

## 🔬 Minimal Reproduction
```
git clone https://github.com/filipesilva/ivy-bundle-size
cd ivy-bundle-size
yarn
yarn bazel-ivy
```

## 🔥 Exception or Error
<pre><code>
ERROR: D:/sandbox/ivy-bundle-size/src/BUILD.bazel:29:1: Compiling TypeScript (ES5 with ES Modules) //src:ngmodule_ivy failed (Exit 1)

external/angular/packages/types.d.ts(12,23): error TS2688: Cannot find type definition file for 'zone.js'.
external/angular/packages/types.d.ts(39,23): error TS2304: Cannot find name 'MatchersUtil'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code> 7.2.0
</code></pre>

**Anything else relevant?**

cc @gregmagolan

**Comment by gregmagolan** [comment]
Ok. I've think I've what is happening. There are few issues that lead to these error:

1) The ivy compile now depends on `@types/hammerjs` downstream
2) The rules_typescript

**Comment by gregmagolan** [comment]
I'll make fix for the rules_typescript issue on the flight back today and investigate the other two.

//cc @alexeagle

**Comment by atscott** [comment]
@gregmagolan is there anything here that's still relevant or can this issue be closed?

**Comment by jelbourn** [comment]
Closing since I think this is obsolete.
