### ISSUE TITLE
feat(http): add JsonP and JsonPBackend

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2818]
Create a new subclass of `Http` called `JsonP`, which uses a new `JsonPBackend` to perform requests using [JsonP](https://en.wikipedia.org/wiki/JSONP) techniques. 

The callback name to provide in the URL should be `JSON_CALLBACK`, similar to AngularJS 1.x.

The `JsonP` implementation should throw if asked to perform the request with a method other "GET". 

This should have its own `injectables` so that users who don't need it don't get the extra bytes.

**Comment by caitp** [comment]
Jeff suggested I might take this one as I implemented this before --- I'll work on this for m31?
