### ISSUE TITLE
hook for angular 

### ISSUE THREAD

**Issue by mhosseinkhani** [angular/angular#28208]
hi! 😄 

I think angular need stuffs like the hook in WordPress and ... 
I and my friends wrote like the hook for angular but this needs more things.

GitHub repository 
https://github.com/mhosseinkhani/hookis

**Comment by alxhub** [comment]
Hello! I'm going to close this issue right now because it's unclear what specific feature you're requesting in Angular. Please feel free to re-open the request with more details on the change you'd like to see us make to the framework.
