### ISSUE TITLE
Service Worker caches redirected URL (301)

### ISSUE THREAD

**Issue by eddiefrank** [angular/angular#28205]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/service-worker

### Is this a regression?

 No

### Description

 
For the first time 301 redirect works after SW is installed he overtakes url that should be redirected and tries to serve it. (But this url does not exists in application.)

https://stackoverflow.com/questions/53508908/nginx-redirects-does-not-work-with-serviceworker/54239732#54239732

## 🔬 Minimal Reproduction

https://www.wearlenses.co.uk/promo/dailies_total1_multifocal/

## 🌍  Your Environment

**Angular Version:**
<pre><code>

@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cli                      6.1.5
@angular/pwa                      0.7.5
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.3.2
typescript                        2.9.2
webpack                           4.9.2
</code></pre>

**Comment by gkalpak** [comment]
It sounds like this is a configuration issue. [Answered on SO][1].

[1]: https://stackoverflow.com/questions/53508908/nginx-redirects-does-not-work-with-serviceworker/54243313#answer-54243313

**Comment by eddiefrank** [comment]
Hi, thanks for the answer but this is not solution in our case. We have 16 countries with 150 localized legacy urls for each. So we will end up with 2k url. It will be better either you will not cache 301 urls either (even better) add callback hook to ServiceWorkerModule.register with requests or/and response comming so we can decide cache it or not.
