### ISSUE TITLE
Calling functions which return new object from templates freezes Angular and the whole browser.

### ISSUE THREAD

**Issue by boris-marinov** [angular/angular#28201]
# 🐞 bug report

### Affected Package

@angular/core

### Is this a regression?
Possibly

### Description
When calling a function from template, and this function returns a fresh object every time, the app freezes and the whole browser crashes.

## 🔬 Minimal Reproduction

I am sharing the controller which caused the issue. Should be simple to simulate
```
import * as _ from "lodash";
import { Component, Input, OnChanges, SimpleChanges } from "@angular/core";
import { Reservation } from "../../../../types/reservation.type";

@Component({
    selector: `usq-reservation-grid-slot-player-checkin-indicator`,
    template: `
    <i
        class="daily-view-player-confirmed-checkmark fas"
        [ngClass]="getClass()" <!-- This line breaks the whole app. Works when you replace with ngClass]="class"-->
        *ngIf="player && player.player"
        >
    </i>
    `,
})
export class UsqReservationGridSlotPlayerCheckinIndicator {
    @Input() public match: Reservation;
    @Input() public player: Reservation["Players"][0];
    public class: {[key: string]: boolean};

    public ngOnChanges() {
        this.class = this.getClass();
    }
    public getClass() {
        const playerHasConfirmed = (p: Reservation["Players"][0]) => {
            return p.player && p.confirmed;
        };
        if (!this.player) { return {}; }
        const player = this.player;
        const atLeastOneConfirmed = _.some(this.match.Players, playerHasConfirmed);
        const returnObj = {
            'fa-check': player.confirmed,
            'fa-times': !player.confirmed
        };
        const propColor = player.confirmed ? 'green' : (atLeastOneConfirmed ? 'yellow' : 'red');
        returnObj[propColor] = true;
        return returnObj;
    }
}
```

## 🔥 Exception or Error

The whole app crashes without throwing any error.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
    "@angular/animations": "7.1.1",
    "@angular/cdk": "7.1.0",
    "@angular/common": "7.1.1",
    "@angular/compiler": "7.1.1",
    "@angular/core": "7.1.1",
    "@angular/flex-layout": "7.0.0-beta.19",
    "@angular/forms": "7.1.1",
    "@angular/material": "7.1.0",
    "@angular/material-moment-adapter": "7.1.0",
    "@angular/platform-browser": "7.1.1",
    "@angular/platform-browser-dynamic": "7.1.1",
    "@angular/router": "7.1.1",

</code></pre>

**Anything else relevant?**
If you cannot make it work with fresh objects, at least throw some error and don't crash the app... and the browser.

**Comment by mohammedzamakhan** [comment]
Its always better not to have function calls in the template. The best option would be the use of custom pipe.

**Comment by thesayyn** [comment]
As far as I know the core key value differ will do reference check before checking the keys so change detector will find change evenif there's no structural changes because the reference of object has been changed. (You will see what I meant if you can place a console.log into your method. It will be called whenever change detector ran) 

So you should use an getter property or bind classes separately

**Comment by alxhub** [comment]
@mohammedzamakhan and @thesayyn are correct - changing the reference every time it's checked will cause change detection to run repeatedly. Couple that with a process that generates lots of change detections, and this could easily lock a browser.

This is not an Angular bug.

**Comment by boris-marinov** [comment]
Well, yeah they are correct. But is it correct to leave an issue which causes browser freezes hanging, just because the developer made a mistake?

Angular is advertised as a framework for building huge webapps with a lots of modules. In one such application, should one mistake in one module be the reason for the whole application to stop working?

OK, if you decided that this is no longer accepted (as it *were* accepted in Angular 1.XX), but any unaccepted behavior should throw an error which would indicate to the user what is broken and why.

The least you can do is to add a flag in Developer Mode which measures how many times is the change detection function is called and shows some warning if that rate is too high.

If you don't agree, change the status of this to an improvement, but I think any issue which causes computer freezes should be a bug.

**Comment by trotyl** [comment]
Angular won't freeze or crash even when you're calling function in template (unless you're keep scheduling new async tasks), even it's a bad approach for performance.

Please make a reproduction via https://stackblitz.com/ if you have difference case.
