### ISSUE TITLE
changelog.md does not mention change to package.json that happened after 7.0 released

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#28218]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...
Sometime after 7.0.0 was verified with the docs and examples (in particular with the TOH Tutorial), the initial package.json that is created by `ng new` was changed. It no longer includes @angular/http and that breaks both examples and doc instructions. We've had a lot of issues filed against doc and there is a lot of stackblitz discussion related to failures in the HTTP module of the tutorial. 

The changelog only mentions this: 
```
platform-server: add @angular/http to the list of peerDependencies (#27307) (32c5be9), closes #26154
```
You have to dig to understand that change needed to happen because @angular/http is no longer listed in package.json's dependencies. 

### What's the affected URL?**
 https://angular.io/...
https://github.com/angular/angular/blob/master/CHANGELOG.md

### Reproduction Steps**

Search for @angular/http and package.json. 

### Expected vs Actual Behavior**

See above.

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Anything else relevant?

This file is not owned by doc team. Eng needs to make the change.

**Comment by jenniferfell** [comment]
@IgorMinar : It seems like there should be something in changelog.md to mention that the default package.json no longer contains @angular/http. Yes?

**Comment by gkalpak** [comment]
This change is related to the cli which generates the `package.json` file, so I don't think there should be something in the Angular changelog.
Have the examples/tutorial been switched to `@angular/common/http`?

**Comment by jenniferfell** [comment]
@gkalpak I see your point, but IMO Angular users shouldn't have to read two changelogs to know about changes to basic features that are documented in the Angular documentation set. We already decided that the CLI is an integral part of using Angular, and not a separate add-on with separate docs. Seems like this is one more step in that unification? We no longer maintain docs on the CLI wiki, so it seems odd to have the main docs in one place and user-visible change documented in another repo. Maybe we can publish CLI wiki in both places, or have some commits handled like breaking changes and dual-publish those major items? 

Re examples/tutorial, they had already been switched previously...but one of the things we import from a 3rd party hadn't been updated yet. Oops.

**Comment by gkalpak** [comment]
I think it is commonly understood that changelog files (for OSS projects at least?) basically list the commits (and changes thereof) that were included in a release. It would be very weird (imo) to list commits/changes from another project in our changelog (even if that over project is an integral part of the ecosystem and most (but not all) users will be using it).

At some point, we might bring the cli into this repo (and then have a unified changelog?), but as long as they are separate repositories they should have separate changelogs.

(The way I see it, this is similar to how people have to read a different changelog for RxJS (which is a hard dependency of Angular, unlike the cli), a different changelog for TypeScript, Jasmine, Node.js, etc.)

**Comment by gkalpak** [comment]
(Not a hill I will die on :grin: Just describing my perspective.)

**Comment by rockument69** [comment]
@kapunahelewong : I think we can safely close this one, no action required.

**Comment by JoostK** [comment]
Closing as obsolete by now.
