### ISSUE TITLE
EMPTY_ARRAY used for identity checks, but multiple are declared in core

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#28229]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Unsure.

### Description

`packages/core/src/render3/empty.ts` states:
```
/**
 * This file contains reuseable "empty" symbols that can be used as default return values
 * in different parts of the rendering code. Because the same symbols are returned, this
 * allows for identity checks against these values to be consistently used by the framework
 * code.
 */
export var EMPTY_OBJ = {};
export var EMPTY_ARRAY = [];
```

But at the moment there are 6 instances of `const EMPTY_ARRAY` in `//packages/core/src`, 3 of which are exported.

Since it's supposedly being used for identify checks, it probably should either:
- use the same one everywhere
- if they mean different things, name them differently

If they should be the same one, some identity checks are likely incorrect at the moment.

## 🔬 Minimal Reproduction

I don't think this is a runtime problem. It's just something in the sourcecode.

## 🌍  Your Environment

**Angular Version:**
<pre><code> master in github

</code></pre>

**Anything else relevant?**

**Comment by alexzuza** [comment]
Somewhere it's also declared as:

```
const EMPTY_CONTEXT = new Object();
```

**Comment by JoostK** [comment]
Closing as #40587 was just merged.
