### ISSUE TITLE
Date Pipe Showing Incorrect Date

### ISSUE THREAD

**Issue by vandensd** [angular/angular#28222]
# 🐞 bug report

### Affected Package
Angular 7.1.1+

### Is this a regression?

Not sure

### Description

Dates that are coming into Chrome correctly over network tab are being formatted incorrectly using the 'date' pipe.  The bug behavior however is not consistent.  For instance, the image below only occurs on Monday dates (where bug is displaying Sunday instead) whereas I have other scheduled dates (Tuesday, Wednesday) that are not being offset by 1 day.

## 🔬 Minimal Reproduction
![image](https://user-images.githubusercontent.com/1239228/51365083-a5cec780-1aac-11e9-8a5a-a09a19290192.png)

## 🔥 Exception or Error
None

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.1.4                                                               
Node: 10.15.0                                                                    
OS: win32 x64                                                                    
Angular: 7.1.1                                                                   
... animations, common, compiler, compiler-cli, core, forms                      
... http, language-service, platform-browser                                     
... platform-browser-dynamic, router
--

@angular-devkit/architect         0.11.0                                         
@angular-devkit/build-angular     0.11.0                                         
@angular-devkit/build-optimizer   0.11.0                                         
@angular-devkit/build-webpack     0.11.0                                         
@angular-devkit/core              7.1.4                                          
@angular-devkit/schematics        7.1.4                                          
@angular/cdk                      6.4.7                                          
@angular/cli                      7.1.4                                          
@ngtools/webpack                  7.1.0                                          
@schematics/angular               7.1.4                                          
@schematics/update                0.11.4                                         
rxjs                              6.3.3                                          
typescript                        3.1.6                                          
webpack                           4.23.1
--

</code></pre>

**Anything else relevant?**

No

No

**Comment by mohammedzamakhan** [comment]
I think the date conversion to your local machine, is what's making the change of date. I don't think this is an issue with date pipe. Consider using moment.js to convert it into the correct timezone, which you want to display

**Comment by vandensd** [comment]
I’m not performing any conversion. I’m literally taking the value and using | date. This still doesn’t explain why any other day of the week displays as expected. The value you see in the network tab is the input to the pipe.

**Comment by mohammedzamakhan** [comment]
The time you are getting is a GMT timezone, and when the Pipe uses it, it converts it to your machines timezone timezone. 

Like Currently in Dallas, it is Jan 17 10:53PM but the GMT time is Jan 18 4:54 AM. 

So your server will send Jan 18 4:54 AM (GMT time zone) and what date pipe or `new Date(serverDate)` gives you is the your local machine time Jan 17 10:53 PM

**Comment by vandensd** [comment]
My database UI was not accounting for my local time so there were some dates not offset by timezone and caused me to evaluate the situation incorrectly.  Closing this.
