### ISSUE TITLE
Duplicate files leftover in package/core

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#28228]
There's a couple of duplicate files in core that aren't being used but still packaged:
- `./src/util/empty.js` is unused and the same as the (used) `./src/render3/empty.js`
- `./src/util/forward_ref.js` is unused and the same as the (used) `./src/dir/forward_ref.js`
- `./src/util/WrappedValue.js` is unused and included in `./src/change_detections/change_detection_util.js`

We shouldn't package these. Even better, we should detect these dangling files at build time.

**Comment by JoostK** [comment]
`WrappedValue` has been removed in the #37940, `forwardRef` was removed in #31423 and `empty` was removed in #41066.
