### ISSUE TITLE
@.disabled with infinite child animations freezes the tab / process

### ISSUE THREAD

**Issue by BaggersIO** [angular/angular#28235]
# 🐞 bug report

### Affected Package
```
@angular/animations
@angular/platform-browser/animations
```

### Is this a regression?

No.

### Description

1. I played with infinite animations. One approach was to trigger a random state after `animation.done` for replay. This works fine.

2. Now I want to disable the animation using `@.disabled` in a parent element. This freezes the tab / browser.

__What happens?__

When using `@.disabled` Angular starts the child animation and stops it immediately. This triggers animation.start and animation.done even the animation should be 'disabled'. 
In my example `animation.done` generates a new state which kicks off another animation; but it will be canceled by the parent `@.disabled` and so on. This results in infinite animation start/stop events and freezes the client.

It does not matter whether the child animation is in the same view, in a nested view or in projected content (ng-content).

## 🔬 Minimal Reproduction

Add the `@.disabled` attribute to the parent div in line one to reproduce the bug.

https://stackblitz.com/edit/angular-disabled-animation-bug?file=src%2Fapp%2Fapp.component.html

## 🔥 Exception or Error

No error thrown but the tab/process freezes.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.2.1
Node: 10.14.2
OS: darwin x64
Angular: 7.2.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.1
@angular-devkit/build-angular     0.12.1
@angular-devkit/build-optimizer   0.12.1
@angular-devkit/build-webpack     0.12.1
@angular-devkit/core              7.2.1
@angular-devkit/schematics        7.2.1
@angular/cli                      7.2.1
@ngtools/webpack                  7.2.1
@schematics/angular               7.2.1
@schematics/update                0.12.1
rxjs                              6.3.3
typescript                        3.2.2
webpack                           4.23.1
</code></pre>

**Anything else relevant?**

MacOS Mojave 10.14.2 
Affects Chrome 71, Brave 71, Firefox, Safari

**Comment by dylhunn** [comment]
We don't support animating infinitely.
