### ISSUE TITLE
Using "title" as a component input

### ISSUE THREAD

**Issue by nknoeppel** [angular/angular#28247]
To be clear, this is not a bug. However, I have noticed that if I use an input called "title" for a component, when the user hovers over this component in the DOM, the value of the "title" input appears next to the cursor. I realize this is because [title] is a valid HTML attribute, however, it would be nice to be able to use this as the name of an input without experiencing this functionality. Not sure if this is even possible, just pointing it out at this point in the hopes that someone reads this.

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/24376

**Comment by ChrisDahmCS** [comment]
@nknoeppel 
When you pass parameters like how the StackBlitz starter project does (without using input bindings syntax [] ), it is valid HTML and must be processed as such. However! When using the input binding [], it won't pick it up (or shouldn't).

[Here is an example](https://stackblitz.com/edit/angular-props-in-general?file=src/app/app.component.html) showing the difference between the two.

**Comment by nknoeppel** [comment]
That makes sense. Hard to expect all team members to know the impact of not using [title]="'whatever'" syntax I guess. Thanks for quick reply!
