### ISSUE TITLE
forms: submit fires synchronously while model changes happen async

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#2824]
see: https://github.com/IgorMinar/todomvc/commit/c1c9be98c0f24b1c65f5974b229bc08b1251cf52#diff-370a0e3c1e8590cb7dc171e741340f29R31 - the setTimeout is used to force correct order of events (ngmodel settles first, the submit is handled)

per discussion with Victor, this is because our current rx version that we use for delivery of ng-model events is async. This will change with rx3.

If we switch over to rx3 in the next 2-3 weeks, then we'll just deal with this, otherwise we'll need to come up with a workaround (like forcing submit to be handled asynchronously).

**Comment by vsavkin** [comment]
The workaround is to use ng-submit instead of submit. NgSubmit goes through an rx stream, so the order of updates will be correct. Once we switch to RxNext, we can revisit it.
