### ISSUE TITLE
low hanging fruit: the error messaging for ngFor unable to iterate objects

### ISSUE THREAD

**Issue by activedecay** [angular/angular#28240]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 No, this is a developer experience issue. 

### Description

 You could easily detect when the developer wants to use an object, but passed the object to ngFor without using the `| keyvalue` pipe

I would like to see the `keyvalue` pipe mentioned in the error message, something like: "NgFor only supports binding to Iterables such as Arrays. Did you mean to use the `keyvalue` pipe? See `doc link here`"

## 🔬 Minimal Reproduction

 https://angular-issue-repro2-qkrgwg.stackblitz.io

## 🔥 Exception or Error
<pre><code>

Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.1.4
Node: 8.12.0
OS: linux x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

</code></pre>

**Anything else relevant?**
This is really low-hanging fruit. Why make developers search the universe for something you know they probably wanted to do?

**Comment by petebacondarwin** [comment]
I think the only decision that needs to be made here is whether this is definitely the right message to give to developers and whether it is worth adding to the bundle size by increasing the length of the error message.

There has been some discussion about having shorter in-place errors, which link to longer explanations and advice at a web page. If that comes to fruition then I think we should add this extra information there.

**Comment by petebacondarwin** [comment]
Related internal tasks: FW-1523 and FW-371

**Comment by dsl400** [comment]
not shure if it is related ...
ngFor  shold not throw this error if data is piped thru something that returns an array

`
Angular CLI: 11.0.2
Node: 14.15.0
OS: win32 x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------       
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@angular/cdk                    11.0.1
@angular/fire                   6.1.3
@angular/flex-layout            11.0.0-beta.33
@angular/material               11.0.1
@angular/service-worker         11.0.3
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5`

**Comment by petebacondarwin** [comment]
For your information, extended error message information is being worked on here: https://github.com/angular/angular/pull/40060
