### ISSUE TITLE
Update from 7.1.4 to 7.2.1 and everything quit working. Great job Angular developers!

### ISSUE THREAD

**Issue by paulpottertasd** [angular/angular#28244]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by paulpottertasd** [comment]
Should say that everything works fine on development system. ng build --prod and put it onto product server and errors everywhere! Did some programmers from Microsoft come over to the Angular group?

**Comment by alxhub** [comment]
Hello @paulpottertasd,

Can you provide some context as to the failures you're seeing? Ideally we're looking for a reproduction of the problem in the form of either a stackblitz or a Github repo that demonstrates the failure(s). 

Without such a reproduction or a stack trace or the error message text, there is no way for us to investigate this failure.

Additionally, I would like to remind you that in the Angular Github issue tracker, our [community Code of Conduct](https://github.com/angular/angular/blob/master/CODE_OF_CONDUCT.md) applies. While I understand your frustration, I need you to refrain from making insulting comments about other groups of developers.

**Comment by alxhub** [comment]
I've tested upgrading a CLI app from 7.1.4 to 7.2.1 and the production build has no issues.

**Comment by alxhub** [comment]
I'm wondering if this is related to #28179.

**Comment by ngfelixl** [comment]
Can not confirm this issue either. Updated an angular cli application from 7.1.0 to 7.2.1 with no production build issues.

**Comment by mlc-mlapis** [comment]
... we also can't confirm that behavior. We migrated to 7.2.1 without any problem.

**Comment by ericmartinezr** [comment]
This is clearly a pebcak case, it should be closed.

**Comment by beeing** [comment]
I do faced this problem and spent the last 2 days finding out the issue.

The issue that I faced is due to:

```ts
import { Something as someAlias } from 'somewhere'
```

There is no build error (for --prod) but when navigate to the component there will be errors that someAlias is not found / defined.

**Comment by paulpottertasd** [comment]
Completely deleted node_modules and ran npm install on app and everything is now working. Is this a common process/necessity within Angular apps?

**Comment by alxhub** [comment]
@paulpottertasd typically when deleting node_modules helps, it happens because node_modules got out of sync with package.json - for example, changing version numbers of packages in package.json but forgetting to run `npm install`.
