### ISSUE TITLE
Implement findBindings for Testability

### ISSUE THREAD

**Issue by juliemr** [angular/angular#2825]
`window.getAngularTestability(body).findBindings(myElement, 'my-binding-name')` should work as it does for [Angular1](https://github.com/angular/angular.js/blob/291d7c467fba51a9cb89cbeee62202d51fe64b09/src/ng/testability.js#L17)

There was a working implementation at https://github.com/angular/angular/pull/1855, but we may want to take a different strategy.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

This is implement in some form.

**Comment by splincode** [comment]
@mhevery Is the issue relevant? Maybe close the task...

**Comment by mhevery** [comment]
We will be taking a different approach with ivy. Closing this one.
