### ISSUE TITLE
Router 7.2.1 breaks navigation

### ISSUE THREAD

**Issue by paul-atek** [angular/angular#28257]
# 🐞 bug report

### Affected Package

@angular/router

### Is this a regression?

Yes, it was fine in 7.2.0.

### Description

In 7.2.0 I have a routerLink to go back to the root of my application, like so:

`routerLink="/"`

Upgrading to 7.2.1 this no longer goes back to the root but submits my form!

If I revert to 7.2.0 of the router it works fine.

**Comment by manklu** [comment]
@paul-atek You should provide a minimal sample demonstrating your problem.

**Comment by AndrewKushnir** [comment]
Hi @paul-atek, as @manklu mentioned, it'd be very helpful if you could provide an example of an app (using StackBlitz) where we can reproduce the problem and perform the necessary investigation. Thank you.

**Comment by paul-atek** [comment]
Fair enough. I did start doing just that, but with a minimal reproduction it was working fine.

Must be something deeper that only occurs in tandem with other modules, it's certainly happening but I appreciate it's not possible to proceed without a repro.

Cheers

Paul
