### ISSUE TITLE
Provide a way to modify modules via e2e tests

### ISSUE THREAD

**Issue by juliemr** [angular/angular#2826]
Provide a way for an end to end test to modify modules during page load. In angular.js 1, this is done by setting a variable on the window that Angular searches for before it bootstraps itself. It allows the test writer to override potentially expensive modules that they do not want used in the test.

In pseudocode, something like this.

Suppose you have a EmailSender binding which you don't actually want active during tests.
```js
// e2e Test file
browser.overrideApplicationBinding('EmailSender',
    function() { this.send = function() { return null })});

browser.get('myurl');
// ... other things in the test.
```

**Comment by hankduan** [comment]
May be affected by https://github.com/angular/angular/issues/1594

**Comment by mhevery** [comment]
Will not implement.
