### ISSUE TITLE
Angular elements OnChanges/OnInit hooks call order error on init

### ISSUE THREAD

**Issue by artaommahe** [angular/angular#28266]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/elements

### Is this a regression?

dunno

### Description

Angular elements OnChanges and OnInit hooks are called in wrong order on init in regular angular component's template: OnInit fires first and has `undefined` in inputs.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-elements-onchanges-order?file=app%2Fapp.component.html
```
> parent OnInit, input value: undefined
> child OnInit, input value: undefined
> parent OnChanges, input value: 1
> child OnChanges, input value: 2
```
expected (like in regular components)
```
> parent OnChanges, input value: 1
> parent OnInit, input value: 1
> child OnChanges, input value: 2
> child OnInit, input value: 2
```

## 🌍  Your Environment

**Angular Version:**
7.1.4

**Comment by robwormald** [comment]
pretty sure this is the same as https://github.com/angular/angular/issues/18909 - can you confirm @artaommahe ?

**Comment by vishranti5** [comment]
Hi, i am also facing same issue, any updates on same?
I have used angular element to create webcomponent and used this webcomponent in base application. while passing complex object from base application as input property, i get this object on Onchanges but Oninit it is undefined
