### ISSUE TITLE
Automate releases and execute them on CI

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#28279]
Our releases are currently only half-automated.

The caretaker needs to follow release instructions and run various scripts or commands. This has two problems:
- caretaker's local dev environment might be corrupted or compromised
- the caretaker can make a mistake while following the instructions

The solution to these problems is to automate the releases and run them from CI.

This is how it could work:
1. caretaker prepares a release by
  - running the changelog script to update CHANGELOG.md
  - bumps the version in package.json
  - committing these changes to the release branch
  - tagging the commit
  - pushing the commit to the upstream branch
2. the CI triggers an upstream build
  - CI creates build artifacts and runs all the tests
  - as the last step in the CI workflow, we check and notices that this build was tagged, the CI will then pause and require [manual job approval from the caretaker](https://circleci.com/blog/manual-job-approval-and-scheduled-workflow-runs/) before publishing the build artifacts to npm
  - after manual approval, the CI proceeds to publish the build artifacts to npm

We could consider modifying this process, by automating even more of the first step, but that will require CI to create and push commits upstream. I suggest that we leave this enhancement as a follow up step, because it will require more security reviews and more complicated setup. We however did this on AngularJS a few years ago, so we already have expertise in how to set this up.

**Comment by petebacondarwin** [comment]
I think it would be reasonable to put the following steps into a script that is run "locally", i.e. not by CI:

* bump the version in package.json
* commit these changes to the release branch
* tag the commit
* push the commit to the upstream branch

I don't think there is much point in moving these steps to CI, but a single script that does these steps would lower the risk of a mistake.

**Comment by dylhunn** [comment]
This is very out of date with respect to current tooling. I'm going to close this, unless @josephperrott has anything to say here.
