### ISSUE TITLE
Cannot combine HttpInterceptor and canActivate in one call

### ISSUE THREAD

**Issue by ioqayl** [angular/angular#28277]
# 🐞 bug report

### Affected Package
The issue is caused by to @angular/common/http/HttpInterceptor and @angular/router/CanActivate

### Description
the requests haven't been intercepted by custom interceptors services, if the invoked route use a guard service.

### Source code
NoAuthGuard.ts
<pre><code>
import { Injectable } from '@angular/core';
import { CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot, Router } from '@angular/router';
import { take, map } from 'rxjs/operators';
import { AuthService } from '../services';
import { Observable } from 'rxjs';

@Injectable()
export class NoAuthGuard implements CanActivate {

  constructor(private _router: Router,
              private authService: AuthService) { }

  canActivate(_next: ActivatedRouteSnapshot, _state: RouterStateSnapshot): Observable<boolean> | Promise<boolean> | boolean {
    console.log('I m in No auth guard Service');

    this.authService.populate();

    return this.authService.isAuthenticated.pipe(take(1), map(isAuth => {
        if (isAuth) { this._router.navigate(['/404'], { skipLocationChange: true }); }
        return !isAuth;
    }));
  }
}
</code></pre>

HomeRoutingModule
<pre><code>
import { NgModule } from '@angular/core';
import { HomeComponent } from './home.component';
import { Routes, RouterModule } from '@angular/router';
import { NoAuthGuard } from '../core';

const routes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: '/articles'},
  { path: 'articles', component: HomeComponent, canActivate: [NoAuthGuard]}
];

@NgModule({
  declarations: [],
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class HomeRoutingModule { }
</code></pre>

HttpTokenInterceptor
<pre><code>
import { Injectable } from '@angular/core';
import { HttpEvent, HttpInterceptor, HttpHandler, HttpRequest } from '@angular/common/http';
import { Observable } from 'rxjs';
import { JwtService } from '../services';

@Injectable()
export class HttpTokenInterceptor implements HttpInterceptor {

    public constructor(private _jwtService: JwtService) { }

    intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        const headersConfig = {
            'Content-Type': 'application/json',
            'Accept': 'application/json'
        };

        const token = this._jwtService.getToken();

        if (token) {
            headersConfig['Authorization'] = `Token ${token}`;
        }

        console.log('I m in Http Interceptors Service: ' + JSON.stringify(headersConfig));

        const request = req.clone({ setHeaders: headersConfig });
        return next.handle(request);
    }
}
</code></pre>

CoreModule
<pre><code>
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { ApiService, JwtService } from './services';
import { HttpTokenInterceptor } from './interceptors';

@NgModule({
  declarations: [],
  imports: [
      CommonModule,
      HttpClientModule
    ],
  providers: [
    ApiService,
    JwtService,
    {provide: HTTP_INTERCEPTORS, useClass: HttpTokenInterceptor, multi: true}
  ],
  exports: []
})
export class CoreModule { }
</code></pre>

AppModule
<pre><code>
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { HomeModule } from './home';
import { CoreModule } from './core';
import { SharedModule } from './shared';
import { AuthModule } from './auth';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    CoreModule,
    SharedModule,
    HomeModule,
    AuthModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
</code></pre>

### Exptected Behavior
Console
<pre><code>
I m in No auth guard Service --displayed by NoAuthGuard service
I m in Http Interceptors:{"Content-Type":"application/json","Accept":"application/json"} --displayed by HttpTokenInterceptor service
</code></pre>

### Current Behavior
Console
<pre><code>
I m in No auth guard Service --displayed by NoAuthGuard service
</code></pre>

### Environment
<pre><code>
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
</code></pre>

**Comment by thesayyn** [comment]
A reproduction link would help to figure out what happening

**Comment by tanato-cit** [comment]
I didn't find where you are doing the Http call to be intercepted. Is the Http call inside your AuthService?

**Comment by ioqayl** [comment]
> I didn't find where you are doing the Http call to be intercepted. Is the Http call inside your AuthService?

Yes, it's inside the AuthService.

**Comment by jasonaden** [comment]
Thanks for the issue, however it looks like the bug template was modified as we don't have a `Source Code` section in there. Instead, please create a reproduction using [StackBlitz](https://stackblitz.com/fork/angular-issue-repro2) and add to a new issue.
