### ISSUE TITLE
Compiler Metadata fetch causes error in Prod/AOT Build..

### ISSUE THREAD

**Issue by subodhkumar** [angular/angular#28272]
# 🚀 feature request
Compiler._metadataResolver._pipeCache fails in the PROD Build and did not see any public API to do that as well...Can you please suggest a solution.

Thanks.
### Relevant Package
@angular/core

### Description
Need a way to read meta data of pipes which does not fail in the Prod/AOT build... 

We are using the metadata fetched to initialize some logic so stuck without the option in Prod build.

### Describe the solution you'd like
A Way/API to fetch PipeMetaData which works in Prod/AOT Build.

### Describe alternatives you've considered
Checked the code, and could not find any public methods/properties.

**Comment by subodhkumar** [comment]
@ericmartinezr just wanted to know your thoughts..missing anything?

**Comment by alxhub** [comment]
@subodhkumar there is no such API in Angular - you don't have access to the compile-time metadata of decorated classes

**Comment by subodhkumar** [comment]
Thanks @alxhub for the response...just need help with one more query. 

#1 | If there is any code which has following snippet
...
(<any>this.compiler)._metedataResolver._pipeCache.*
...
Seems to work in dev build and we realize that such API is not allowed only when do an AOT/Prod build. Wouldnt it be confusing to have a code which works in Dev but not in Prod.

Is there a guide/documentation which developer can check when writing code for having it AOT ready. (I checked Angular documentation and i did not find any). Can you please suggest.
