### ISSUE TITLE
Try to load different modules using bootstrap module, getting error while loading child modules

### ISSUE THREAD

**Issue by chandu20000** [angular/angular#28280]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Angular 6

copied code is not loading the child modules which are available in App module

main.ts
if(window !== window.parent && !window.opener) {
    platformBrowserDynamic().bootstrapModule(MyMsalModule);
  } 
  else {
    platformBrowserDynamic().bootstrapModule(AppModule)
  }

MyMsalModule.ts

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import {LogLevel} from "msal";
import {MsalModule} from "@azure/msal-angular";
import { RouterModule } from '@angular/router';
import { MsalComponent } from './MyMSal.Component';
import { AppRoutingModule } from './app-routing.module';

@NgModule({
  declarations: [
    MsalComponent,
  ],
  imports: [
    BrowserModule,
    RouterModule.forRoot([{path: '', component: MsalComponent}, {path: '**', redirectTo: ''}]),
    MsalModule.forRoot({
      clientID: 'sfdf',
      authority: "sdff",
      validateAuthority: true,
      //redirectUri: "dsff",
      redirectUri: "http://localhost:4200/",
      cacheLocation : "sessionStorage",
      //postLogoutRedirectUri: "dsf",
      navigateToLoginRequestUrl: true,
      popUp: false,
      consentScopes: ["dsff"],
      //unprotectedResources: ["dsf"],
      //protectedResourceMap: protectedResourceMap,
      //logger: loggerCallback,
      correlationId: '1234',
      level: LogLevel.Info,
      piiLoggingEnabled: true,
      extraQueryParameters: "p=B2C_1_Billing_SignIn&scope=profile&nux=1&state=login",

       }
    ),
    AppRoutingModule
  ],
  bootstrap: [MsalComponent]
})
export class MyMsalModule {
}

AppModule.ts

import { SharedModule } from './shared/shared.module';
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { DeviceDetectorModule } from 'ngx-device-detector';

import { AppComponent } from './app.component';
import { routingComponents, AppRoutingModule } from './app-routing.module';
import { AuthModule } from './auth/auth.module';
import { CoreModule } from './core/core.module';
import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { TokenInterceptor } from './core/interceptors/token.interceptor';
import { VideostorageModule } from './videostorage/videostorage.module';
import { EulaTabComponent } from './shared/layout/eulatab/eulatab.component';
import { EulaPrivacyComponent } from './videostorage/eula-payment/eula-privacy.component';
import { EulaTermsComponent } from './videostorage/eula-payment/eula-terms.component';
import { LoggerModule, NgxLoggerLevel, NGXLogger } from 'ngx-logger';
import { environment } from '../environments/environment';
import { IdleTimeoutService } from './IdleTimeoutService';
import { BrowserSupportedComponent } from './videostorage/eula-payment/browser-support.component';
import { ServerErrorComponent } from './shared/navigation/server-error/server-error.component';
import { AuthService } from './auth.service';
import {LogLevel} from "msal";
import {MsalModule} from "@azure/msal-angular";
import { BackendService } from './backend.service';

export function loggerCallback(logLevel, message, piiEnabled) {
  console.log("client logging" + message);
}

@NgModule({
  declarations: [
    AppComponent,
    routingComponents,
    EulaTabComponent,
    EulaPrivacyComponent,
    EulaTermsComponent,
    BrowserSupportedComponent,
    ServerErrorComponent
  ],
  imports: [
    BrowserModule,
    MsalModule.forRoot({
      clientID: 'ggg',
      authority: "deddf",
      validateAuthority: true,
      //redirectUri: "dffd",
      redirectUri: "http://localhost:4200",
      cacheLocation : "sessionStorage",
       postLogoutRedirectUri: "http://localhost:4200",
      //postLogoutRedirectUri: "sfsf",
      navigateToLoginRequestUrl: true,
      popUp: false,
      consentScopes: ["sff"],
      //unprotectedResources: ["https://lyricdev.onmicrosoft.com/"],
      //protectedResourceMap: protectedResourceMap,
      logger: loggerCallback,
      correlationId: '1234',
      level: LogLevel.Info,
      piiLoggingEnabled: true,
      extraQueryParameters: "p=B2C_1_Billing_SignIn&scope=profile&nux=1&state=login",

       }
    ),
    AppRoutingModule,
    AuthModule,
    CoreModule,
    SharedModule,
    DeviceDetectorModule.forRoot(),
    LoggerModule.forRoot({
      serverLoggingUrl: environment.settings.chilurl + "log",
      level: NgxLoggerLevel.DEBUG,
      serverLogLevel: NgxLoggerLevel.INFO
    })
  ],
  providers: [
    {
      provide: HTTP_INTERCEPTORS,
      useClass: TokenInterceptor,
      multi: true
    },
    AuthService,
    NGXLogger,
    IdleTimeoutService,
    BackendService
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

app-routing.module.ts

import { NgModule } from '@angular/core';
import { RouterModule, Routes, PreloadAllModules } from '@angular/router';
import { HeaderComponent } from './shared/layout/header/header.component';
import { PageNotFoundComponent } from './shared/navigation/page-not-found/page-not-found.component';
import { EulaTabComponent } from './shared/layout/eulatab/eulatab.component';
import { EulaTermsComponent } from './videostorage/eula-payment/eula-terms.component';
import { EulaPrivacyComponent } from './videostorage/eula-payment/eula-privacy.component';
import { BrowserSupportedComponent } from './videostorage/eula-payment/browser-support.component';

const routes: Routes = [
  {
    path: "video",
    loadChildren: "./video/video.module#VideoModule",
    pathMatch: 'full'
  },
  {
    path: "details",
    loadChildren:
      "./shared/details/details.module#DetailsModule",
    pathMatch: 'full'
  },
  {
    path: "terms",
    component: EulaTermsComponent
  },

  {
    path: "privacy",
    component: EulaPrivacyComponent
  },

  {
    path: "browser",
    component: BrowserSupportedComponent
  },

  {
    path: "",
    loadChildren: "./auth/auth.module#AuthModule",
    pathMatch: 'full'
  },

  { path: "**", component: PageNotFoundComponent }
];

@NgModule({
  imports: [RouterModule.forRoot(routes,{
    preloadingStrategy: PreloadAllModules
  })],
  exports: [RouterModule]
})
export class AppRoutingModule { }

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alxhub** [comment]
Hello,

This reproduction is impossible to follow. Please post a working reproduction, in the form of a stackblitz or a Github repo with instructions.

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-issue-repro2).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
