### ISSUE TITLE
docs:TOH - Missing article in HTTP section

### ISSUE THREAD

**Issue by dariobraun** [angular/angular#28284]
# 📚 Docs or angular.io bug report

### Description
Under the HTTP section of the TOH tutorial inside the "Heroes and HTTP" sub section there is the sentence

> You'll call it so frequently that you'll wrap it in private log method.

which seems to be missing an article.

### What's the affected URL?**
https://angular.io/tutorial/toh-pt6#heroes-and-http

### Expected vs Actual Behavior**
Correct use of the article:

> You'll call it so frequently that you'll wrap it in **a** private log method.

It might also make sense to use the "method()"-syntax to better distinguish the method name "log"

> You'll call it so frequently that you'll wrap it in **a** private **log()** method.

**Comment by jenniferfell** [comment]
Resolved. Thank you!
