### ISSUE TITLE
docs: TOH - possibly wrong links in "Routing" section

### ISSUE THREAD

**Issue by dariobraun** [angular/angular#28283]
# 📚 Docs or angular.io bug report

### Description

Inside the "Routing" section of the Tour Of Heroes tutorial under "[Add a navigation link (routerLink)](https://angular.io/tutorial/toh-pt5#add-a-navigation-link-routerlink)" there are the following two links that lead to the sub section itself instead of some sort of reference or documentation:

[routerLink attribute](https://angular.io/tutorial/toh-pt5#routerlink)
[RouterLink directive](https://angular.io/tutorial/toh-pt5#routerlink)

Is this intended? If so, what is the use? If not, the links should point to another source of information (for example the [RouterLink reference](https://angular.io/api/router/RouterLink)) or be removed.

### What's the affected URL?**
https://angular.io/tutorial/toh-pt5#add-a-navigation-link-routerlink

### Expected vs Actual Behavior**

Links should point to another source of information (for example the RouterLink reference) or not be present at all instead of linking to the exact subsection they are located in.

**Comment by jenniferfell** [comment]
@dariobraun : Good catch. My take on this: 
* The first link should just be removed. 
* The second link should go to https://angular.io/api/router/RouterLink
(Capturing that so we have the fix handy when we have this doc open next.)

**Comment by chembu** [comment]
Fixed as part of https://github.com/angular/angular/pull/28571
