### ISSUE TITLE
Is there a possibility for angular to develop flutter applications

### ISSUE THREAD

**Issue by DreamPWJ** [angular/angular#28281]
# 🚀 feature request

Is there a possibility for angular to develop flutter applications

### Description
We like to develop flutter applications in angular to reduce development costs. Is it possible to build an angular dart flutter compiler

### Describe the solution you'd like
Is there a possibility for angular to develop flutter applications

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by alxhub** [comment]
Flutter is a different framework than Angular, written in a different language. You might consider looking at the [AngularDart](https://webdev.dartlang.org/angular) framework, or another technology such as [NativeScript](https://www.nativescript.org/)

**Comment by DreamPWJ** [comment]
Flutter can be for web, why can't angular be for flutter@alxhub
