### ISSUE TITLE
docs: Bump angular-in-memory-web-api to latest version for examples

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#28294]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Anything else relevant?

Update to version `0.8.0` and fix examples where `@angular/http` is still used.

**Comment by CaerusKaru** [comment]
@brandonroberts if you want, I can spin this out of #27038

**Comment by CaerusKaru** [comment]
@brandonroberts see #28296

**Comment by brandonroberts** [comment]
Fixed via #28296
