### ISSUE TITLE
Angular 6, brackets in DomSanitizer with div background

### ISSUE THREAD

**Issue by andreyderevyanko** [angular/angular#28295]
**Hello!**

DomSanitizer doesn't support url's with parenthesis, for example:

_/publishingimages/2018/11/29/2018_11_29_11_47_737_image%20(2).jpg_

**Solution to fix**: .replace("(", "%28").replace(")", "%29")

**Comment by MOHAMMADHMEAD** [comment]
try use  sanitizer: DomSanitizer
this.sanitizer.bypassSecurityTrustResourceUrl(this.path)

it's work for me

**Comment by MOHAMMADHMEAD** [comment]
https://stackblitz.com/edit/angular-5mir29 @mhevery

**Comment by pkozlowski-opensource** [comment]
As commented by @MOHAMMADHMEAD I think that it works as expected with `bypassSecurityTrustResourceUrl`: https://stackblitz.com/edit/angular-t1zpdh?file=src%2Fapp%2Fapp.component.ts

(the image in this stackblitz won't load but it is not rejected by a sanitiser and ends up in the DOM as expected).

I'm going to close this one for now but if anyone has a reproduce scenario that shows a bug - please open a new issue attaching a minimal reproduce scenario.
