### ISSUE TITLE
Remove traceur from the build

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#2829]
Also removes traceur-runtime by replacing with per-feature polyfills.
See WIP: https://github.com/angular/angular/pull/2573
Some obstacles documented here: https://docs.google.com/document/d/1gD-yGNp6TDR6YvfrQAUm47hGT0rdGykS6ctUrPTx2eU/edit

**Comment by alexeagle** [comment]
Also needs to happen:
- [ ] remove `es5build.js` from our npm releases

cc: @ttowncompiled

**Comment by naomiblack** [comment]
@alexeagle to investigate commonjs as the path forward in alpha-32

**Comment by alexeagle** [comment]
Carved out a subtask in #3094 
and pushing the remaining work until later.

**Comment by alexeagle** [comment]
Requires more breakdown with @ttowncompiled , but I'm on-duty for google3 sync so it may have to wait until later this week.

**Comment by alexeagle** [comment]
Sorry, I still have not prioritized this, nor do I have a breakdown of what to do first.

**Comment by IgorMinar** [comment]
We landed part of this, but there is more cleanup needed. @jeffbcross is working #3694. After that one lands, we still need to crawl the repo and look for any other traceur use, which should be just mechanical cleanup work.

**Comment by alexeagle** [comment]
@rkirov finished this last week.
