### ISSUE TITLE
HTTP processing?

### ISSUE THREAD

**Issue by KhalitovAdel** [angular/angular#28302]
I'm building my frontent projects on angular, back-end in nodejs.

I send POST request to server from angular, server send me answer by redirect to something directory, but angular do not redirect me.

I need to processing answers from the server by angular, or I dont know something?

**Comment by ericmartinezr** [comment]
https://angular.io/guide/http

<hr>

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
