### ISSUE TITLE
remove `rtts_assert` subproject and figure out a way to trigger development mode

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#2830]

**Comment by mhevery** [comment]
I think we should have two separate builds for our users. One with dev enabled and one with it disabled. Thoughts?

**Comment by rolandjitsu** [comment]
@mhevery could it be a flag that we set when we bootstrap/config the app instead of two builds? Perhaps on the bootstrap function itself:
```js
import { bootstrap } from 'angular2/bootstrap';
import { App } from 'components/app';

bootstrap(
    App,
    [],
    true // dev mode now
);
```
And maybe, for an app that is already in production and has dev mode disabled, could be enabled by calling a function in the console, the same way Angular 1 has [reloadWithDebugInfo](https://docs.angularjs.org/api/ng/function/angular.reloadWithDebugInfo).

**Comment by mhevery** [comment]
Yes I think it could be runtime based.

AtScript needed a compile time solution, but I don't think that requirement
exist with typescript.

**Comment by tbosch** [comment]
But that would have to be a global variable then, as I am not sure that we
have access to DI at all of the places where we need it...

For JS we could have dev mode enabled in the non minified build and disable
it in the minified build (that's what eg react is doing)

For Dart we could have a special transformer that disables it and which is
used when doing dart2js

**Comment by mhevery** [comment]
In this case global var should be ok as it is a constant and does not
change for the duration of the application.

**Comment by rolandjitsu** [comment]
@tbosch oh yeah, I forgot that right now there is no global variables exposed from within the library (only for the users that use it with ES5), is that right?

But as @mhevery says, it should not have any impact on the application performance, unless there is more to be done than just exposing a global constant in the browser.

Anyway, I would rather not be switching between two scripts to enable/disable dev mode, just a personal opinion, and I would rather keep consistent with the previous version of Angular. Yet again, if having dev mode enabled means having a lot more code that affects application performance, then I'd rather swittch between two scripts.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
