### ISSUE TITLE
docs: ViewEncapsulation.ShadowDom option is not available in component doc

### ISSUE THREAD

**Issue by billyjov** [angular/angular#28310]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
https://angular.io/api/core/Component#encapsulation

## 📷Screenshot

![ng-doc-bug](https://user-images.githubusercontent.com/18737653/51601133-dd51cf80-1f03-11e9-9846-4b4e97397467.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by sarunint** [comment]
Fixed by #26361, still to be released.

**Comment by brandonroberts** [comment]
Fixed via #26361 and has landed on stable
