### ISSUE TITLE
docs: Redundant "See also:" link in ContentChild documentation

### ISSUE THREAD

**Issue by dariobraun** [angular/angular#28318]
# 📚 Docs or angular.io bug report

### Description

Inside the [ContentChild documentation](https://angular.io/api/core/ContentChild) under "See also:" there is a link linking to the documentation itself. It feels like the link should be linking to another reference or not be there at all.

### What's the affected URL?**
https://angular.io/api/core/ContentChild

**Comment by jithil-kore** [comment]
PR Created https://github.com/angular/angular/pull/28334

**Comment by jithil-kore** [comment]
> # 📚 Docs or angular.io bug report
> ### Description
> Inside the [ContentChild documentation](https://angular.io/api/core/ContentChild) under "See also:" there is a link linking to the documentation itself. It feels like the link should be linking to another reference or not be there at all.
> 
> ## 🔬 Minimal Reproduction
> ### What's the affected URL?**
> https://angular.io/api/core/ContentChild
PR Created #28334

**Comment by jithil-kore** [comment]
Pr has been merged. Please close this case. @jenniferfell
