### ISSUE TITLE
Remove _abstract() workaround

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#2832]
We have non-idiomatic TS code like
```
function _abstract() {
  return new BaseException('This method is abstract');
}
export class DomAdapter {
  hasProperty(element, name: string): boolean { throw _abstract(); }
}
```

which I believe we could represent as
```
export interface DomAdapter {
  hasProperty(element, name: string): boolean;
}
var DomAdapter;
```

We should try that and then remove all the awkward "pure abstract classes" in the angular codebase.

**Comment by vicb** [comment]
I think `interface`s still can not be used with the DI (ie `bind(Interface).toClass(Impl)`).
That should explain why we have a few occurrence of this pattern.

**Comment by mhevery** [comment]
agree with @vicb. Interface disappear at runtime, so they break DI. But I think most of the usage of `_abstract` is not related to DI and could be removed. Perhaps we should way for TS 1.6 which has implemented abstract keyword: https://github.com/Microsoft/TypeScript/issues/6

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
