### ISSUE TITLE
Custom context support for else block

### ISSUE THREAD

**Issue by giordanocardillo** [angular/angular#28336]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/core

### Description
I'd like to pass a custom context to the `else` template block in `*ngIfElse` because if I have a template that's in anothe block of code I'm forced to duplicate the block with the ngIf condition to display two different templates with different contents

### Describe the solution you'd like
It could be nice to add another parameter to the ngIfElse, like `*ngIf="condition; else myTemplate; elseContext: {$implicit: element}"`

### Describe alternatives you've considered
A current workaround is to use an ngSwitch or duplicate the ngIf with reversed condition

**Comment by Carniatto** [comment]
There is any other solution to this or this PR will eventually ve merged?

**Comment by alxhub** [comment]
Closing as a duplicate of #28731
