### ISSUE TITLE
Angular bindings not working with webcomponent built with @angular/elements

### ISSUE THREAD

**Issue by chainlist** [angular/angular#28340]
# 🐞 bug report

### Affected Package
Issue might be caused by @angular/elements or @angular/core

### Is this a regression?

No

### Description

When using WebComponents built with @angular/elements within an angular app, data binding is not working properly.

## 🔬 Minimal Reproduction
You can reproduced the bug by cloning the following repository: [link](https://github.com/chainlist/test-elements)

Simply, run `yarn start` and test it out.
You can check the difference between angular and non-angular part within the index.html

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.2.2
Node: 9.8.0
OS: win32 x64
Angular: 7.2.2
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.2
@angular-devkit/build-angular     0.12.2
@angular-devkit/build-optimizer   0.12.2
@angular-devkit/build-webpack     0.12.2
@angular-devkit/core              7.2.2
@angular-devkit/schematics        7.2.2
@ngtools/webpack                  7.2.2
@schematics/angular               7.2.2
@schematics/update                0.12.2
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4
</code></pre>

**Anything else relevant?**

You can find sources of the compiled element.js file inside the directory `elements-src` in the repository.

FYI: It seems the bindings itself are parsed correctly because the DOM instance has the property correctly set to the App instance property, but the Angular instance of the WebComponent is not receiving the data.
I don't know if I am really clear on that. Don't hesitate to ask for more info.

**Comment by jasonaden** [comment]
Can you please make this work in [StackBlitz](https://stackblitz.com/github/chainlist/test-elements)?

Angular CLI projects should work there automatically, but this one doesn't:

https://stackblitz.com/github/chainlist/test-elements

**Comment by chainlist** [comment]
Yes, I don't why it is not working with stackblitz. I think angular-elements is not compatible with stackblitz.
That's my generated file from my library using @angular-elements which is throwing the error.

**Comment by robwormald** [comment]
this is the same issue as described in #30028 - same fix applies. Here's a working stackblitz, just to confirm - https://stackblitz.com/edit/github-p8ydeg?file=src/assets/element.js - I just replaced all references to `webpackjsonp` to `webpackjsonp2` - this can be done via ngx-builds-plus. See the linked issue for more details.
