### ISSUE TITLE
Add `TestComponentBuilder.create` and make all integration specs sync

### ISSUE THREAD

**Issue by tbosch** [angular/angular#2835]
Right now, `TestComponentBuilder` provides `.createAsync`, which returns a promise. However, as we also have `fakeAsync` working now, we can implement `TestComponentBuilder.create(type)` which would return the component instance synchronously like this:

```javascript
  create(rootComponentType: Type): RootTestComponent {
    var rootTc;
    var error;
    this.createAsync(rootComponentType).then((root) => { rootTc = root; }, (err) => error = err);
    tick();
    if (isPresent(error)) {
      throw error;
    }
    return rootTc;        
  }
```

Given this, all tests in `core/compiler/integration_spec` can be made synchronous.

**Comment by tbosch** [comment]
A side effect of this is that we get real stack traces when one of the integration tests fail, not just `Test timed out` (for JS).

**Comment by juliemr** [comment]
We decided that this is pending codegen - will review after that hits.

**Comment by mhevery** [comment]
i believe this is implemented
