### ISSUE TITLE
Cant save a filet type exe using reader.readAsArrayBuffer()

### ISSUE THREAD

**Issue by DanielFrugoni** [angular/angular#28359]
let reader = new FileReader();
      reader.readAsArrayBuffer(this.miArchiv);
      reader.onload = () => {       
      this.datosForm.get('Archivo').setValue(reader.result)
);
The json is empty.
If Im doing wrong, how can I save an Exe file in a form fiel ?
Thx

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
