### ISSUE TITLE
AOT: Accessing enum with keyof detected as wrong type 'string'

### ISSUE THREAD

**Issue by magnattic** [angular/angular#28369]
<# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler.

### Is this a regression?

No

### Description and minimal reproduction

When I use an enum in my template and try to access an enum value by either 'string' or 'keyof typeof MyEnum', the compiler thinks the result is of type 'string' (instead of the actual enum type).

The following template throws the error 
**`This condition will always return 'false' since the types 'string' and 'OrderByMode' have no overlap.`**
for the third line, when compiled with AOT and `fullTemplateTypeCheck` enabled.

However, during runtime everything works great. 
And in fact, if I use `OrderByMode[keyof typeof OrderByMode]` in the component itself, TS correctly resolves the type to OrderByMode. This leads me to believe that the compiler is not producing the wrong type here.

The template:
``` 
    <option *ngFor="let key of (keys$ | async)"
      [value]="key"
      [selected]="OrderByMode[key] === OrderByMode.Distance"
    >
      {{ key }}
    </option>
``` 

The component class:
```
export class OrderSelectorComponent {
  public keys$: Observable<(keyof typeof OrderByMode)[]>;

  public OrderByMode = OrderByMode;

  constructor() {
    this.keys$ = of(
      [OrderByMode.Random, OrderByMode.Distance, OrderByMode.Popularity, OrderByMode.Price].map(
        x => OrderByMode[x] as keyof typeof OrderByMode
      )
    );
  }
}
```

The enum:
```
export enum OrderByMode {
  Random,
  Distance,
  Price,
  Popularity
}
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 7.2.2
Node: 10.15.0
OS: linux x64
Angular: 7.2.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.12.2
@angular-devkit/build-angular      0.12.2
@angular-devkit/build-ng-packagr   0.12.2
@angular-devkit/build-optimizer    0.12.2
@angular-devkit/build-webpack      0.12.2
@angular-devkit/core               7.2.2
@angular-devkit/schematics         7.2.2
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.2.2
@schematics/angular                7.2.2
@schematics/update                 0.12.2
ng-packagr                         4.6.0
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.28.4
</code></pre>

**Comment by jasonaden** [comment]
Thanks for the issue. Reported issues require a reproduction of the issue as per the issue template. I've assigned this to the Core/Compiler team, but without a reproduction it will likely get closed. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-issue-repro2).

**Comment by magnattic** [comment]
@jasonaden StackBlitz doesn't support AOT compilation (afaik).

I setup a [minimal reproduction repo](https://github.com/magnattic/ng-template-enum).

Steps to reproduce:
1. `git clone git@github.com:magnattic/ng-template-enum.git`
2. Run `npm run build:prod`

It's a standard ng new repo where I only changed the AppComponent and added `fullTemplateTypeCheck` to the tsconfig.app.json.

It will throw the AOT error **`This condition will always return 'false' since the types 'string' and 'OrderByMode' have no overlap.`**

If you run it with `npm start` it will work just fine. The same if you disable `fullTemplateTypeCheck` (obviously).

**Comment by magnattic** [comment]
Can this be reopened or should I open a new issue?
