### ISSUE TITLE
DomSanitizer not working on tag of SVG image

### ISSUE THREAD

**Issue by khanghyxda** [angular/angular#28362]
DomSanitizer seems to work only with HTML tags.
When i have error unsafe on SVG tags (tag image), I try use DomSanitizer but its not working
My code
![image](https://user-images.githubusercontent.com/5491573/51727795-f946a400-20b0-11e9-8e14-52e0d4151254.png)
![image](https://user-images.githubusercontent.com/5491573/51727804-05cafc80-20b1-11e9-8b79-6671f0685bfb.png)
Error
![image](https://user-images.githubusercontent.com/5491573/51727827-1c715380-20b1-11e9-9427-11459bce750e.png)

**Comment by jasonaden** [comment]
Thank you for submitting this issue. However, it appears you didn't utilize the issue template when creating it. We require that all newly created issues follow the template for the issue type.

If your situation persists, please create a new issue utilizing the template.
