### ISSUE TITLE
The rendering is different between IE11 and Chrome on angular.io

### ISSUE THREAD

**Issue by wKoza** [angular/angular#28364]
This is the rendering on Chrome:

![angular_io_chrome](https://user-images.githubusercontent.com/11403260/51737596-487add80-208d-11e9-9704-5b47d8b0e40c.PNG)

Fine!

But, this is the same page on IE:

![angular_io_ie](https://user-images.githubusercontent.com/11403260/51737673-795b1280-208d-11e9-9e66-74eb52d9a880.PNG)

There is a problem with the margin and we can see that the header is truncated (the title is dropped). The "hamburger" takes the same way.

**Comment by wKoza** [comment]
see also https://github.com/angular/angular/pull/28188#issuecomment-455177621

**Comment by gkalpak** [comment]
The margin issue seems to have been fixed on IE11. At this point (with Angular's IE11 support being deprecated) it doesn't make sense to try to get the docs pixel-perfect on IE11 😅.
