### ISSUE TITLE
cant get state of animation to achieve transition('${state} => void') working with dynamic create component

### ISSUE THREAD

**Issue by kernyden** [angular/angular#28365]
what i need:

2 buttons have to work with animation(now its working right only for prev button, another button needs own styles on translateX, to do it for the "next button" need to change in animation param to translateX(100%) instead of translateX(-100%).  - "prev button" with translateX(-100%), "next button" with translateX(100%), it gives me an effect that slide :leave and slide  :enter is still running when i click on one of the buttons.

code:
https://stackblitz.com/edit/angular-tkzrpc?file=src%2Fapp%2Fapp.component.ts

expected effect:
https://stackblitz.com/edit/angular-carousel-example-m8hrxa?file=src%2Fapp%2Fapp.component.ts

I don't really know is that a feature or it can't be done for that way(for the same component is destroyed or is created).  And variables in animation dont work , i think cause component also has been destroyed.

**Comment by jasonaden** [comment]
Thank you for submitting this issue. However, it appears you didn't utilize the issue template when creating it. We require that all newly created issues follow the template for the issue type.

If your situation persists, please create a new issue utilizing the template.
