### ISSUE TITLE
Angular 7 application browser navigation ( back and forward ) not working.

### ISSUE THREAD

**Issue by pavinthan** [angular/angular#28363]
Oh hi there! 😄

# 🐞 bug report
### Description

Browser navigation not working in `ng build --aot --prod` build application,
Once we deployed application to server and navigate to any routes It's working but once click the browser back and forward buttons It's navigate to route but component not render correctly

Components lifecycle methods not called

**Angular Version:**
<pre><code>
Angular CLI: 7.0.7
Node: 11.6.0
OS: darwin x64
Angular: 7.2.2
... animations, common, compiler, core, forms, http
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.3
@angular-devkit/build-angular     0.12.3
@angular-devkit/build-optimizer   0.12.3
@angular-devkit/build-webpack     0.12.3
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@angular/compiler-cli             7.0.4
@angular/language-service         7.0.4
@ngtools/webpack                  7.2.3
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.28.4
</code></pre>

**Comment by pavinthan** [comment]
Just dive into this the issue was `RouteReuseStrategy` how to remove `RouteReuseStrategy` ?

**Comment by jasonaden** [comment]
You can replace the `RouteReuseStrategy` with one of your own through dependency injection. Simply return `false` on `shouldReuseRoute`.

Future questions such as this should be sent to StackOverflow.
