### ISSUE TITLE
No error thrown when invalid html binding in AOT mode and [*ngIf ] is used

### ISSUE THREAD

**Issue by VSUser** [angular/angular#28371]
Html contains a binding to not existing property in TS file. 
The binding is placed in a tag with always true *ngIf condition.
A compiler doesn't throw an error if build with "ng build --prod".

**Steps to reproduce:**

1. Create an empty component with html:
```
<div *ngIf="true">
{{notExistingProp}}
</div>
```
2. Run "ng build --prod".
3. No error is thrown.

If remove *ngIf condition and build again it will throw an error "ERROR in src\app\app.component.html(1,6): : Property 'notExistingProp' does not exist on type 'AppComponent'."
```
<div>
  {{notExistingProp}}
</div>
```

**Expected behavior:** throw an error in both cases.

**Versions:**
 "@angular/cli": "~7.2.3",
 "@angular/core": "^7.2.2",
 "@angular/compiler-cli": "^7.2.2",
 "typescript": "~3.2.4"

**Comment by jasonaden** [comment]
Thank you for submitting this issue. However, it appears you didn't utilize the issue template when creating it. We require that all newly created issues follow the template for the issue type.

If your situation persists, please create a new issue utilizing the template.
