### ISSUE TITLE
ContentChildren won't load RouterLink or RouterLinkWithHref when used within a structural directive

### ISSUE THREAD

**Issue by marcosdimitrio** [angular/angular#28391]
# 🐞 bug report

### Description

When I use ContentChildren with RouterLink or RouterLinkWithHref and then try to update the container with ViewContainerRef.createEmbeddedView, then ContentChildren stops returning results.

```typescript
// TODO(issue/24571): remove '!'.
@ContentChildren(RouterLink, { descendants: true })
links !: QueryList<RouterLink>;

// TODO(issue/24571): remove '!'.
@ContentChildren(RouterLinkWithHref, { descendants: true })
linksWithHrefs !: QueryList<RouterLinkWithHref>;
```

Template:

```html
<p *appUnless="false">
    This paragraph is displayed because the condition is false.
    <a routerLink="/another-page">my link</a>
</p>
```

Code:

```typescript
ngAfterContentInit(): void {
    console.log("links length", this.links.length);
    console.log("linksWithHrefs length", this.linksWithHrefs.length);
}
```

I tried [asking on stackoverflow](https://stackoverflow.com/questions/54139543/contentchildren-wont-load-any-data-when-querying-routerlink-and-routerlinkwithh), but didn't find a solution.

## 🔬 Minimal Reproduction
You can see this behavior in [this stackblitz](https://stackblitz.com/edit/angular-rkkp6z). This [other one](https://stackblitz.com/edit/angular-segeto) shows that it works without the call to ViewContainerRef.createEmbeddedView.

## 🌍  Your Environment

Using Angular 7.2.3.

    Angular CLI: 7.2.3
    Node: 8.11.3
    OS: win32 x64
    Angular: 7.2.0
    ... animations, common, compiler, compiler-cli, core, forms
    ... language-service, platform-browser, platform-browser-dynamic
    ... router

    Package                           Version
    -----------------------------------------------------------
    @angular-devkit/architect         0.12.1
    @angular-devkit/build-angular     0.12.1
    @angular-devkit/build-optimizer   0.12.1
    @angular-devkit/build-webpack     0.12.1
    @angular-devkit/core              7.2.1
    @angular-devkit/schematics        7.2.3
    @angular/cli                      7.2.3
    @ngtools/webpack                  7.2.1
    @schematics/angular               7.2.3
    @schematics/update                0.12.3
    rxjs                              6.3.3
    typescript                        3.2.2
    webpack                           4.23.1

**Comment by pkozlowski-opensource** [comment]
The 2 stackblitz you've linked present a _totally_ different situation, so those are not comparable. Let's examine what is going on here by de-sugaring the `*` syntax.

### "Non-working"

De-sugars to:

```html
<ng-template [appUnless]="false">
  <p>
  This paragraph is displayed because the condition is false.
  <a routerLink="/another-page">my link</a>
  </p>
</ng-template>
```

Notice that there is no content here for `appUnless` since it "sits" on top of `<ng-template>` and this element has no content in itself - it might _produce_ content when it is instantiated. 

### "Working"

De-sugars to:

```html
<p [appUnless]="false">
  This paragraph is displayed because the condition is false.
  <a routerLink="/another-page">my link</a>
</p>
```
and here `<p>` has content for `appUnless` to query.

I hope that the above explanation is sufficient to understand what is going on here. I'm going to close this issue since it behaves as expected. At the same it looks you are trying to do something that doesn't work for you and I would like to better understand your use-case. Feel free to continue the discussion in there so I can grasp what you are trying to do and suggest an alternative approach.

**Comment by marcosdimitrio** [comment]
Thank you for your response! The "Working" example was provided by another user from the [question](https://stackoverflow.com/questions/54139543/contentchildren-wont-load-any-data-when-querying-routerlink-and-routerlinkwithh) I opened on Stackoverflow, so I didn't notice the `*` wasn't there until you mentioned it.

I need to integrate an existing permission system with Angular. I already successfully implemented the service and the guard for this, but I want to conditionally display links based on permissions.

What I already have is:

```html
<p appHasPermissionTo="AccessAnotherPage">
  <a routerLink="/another-page">my link</a>
</p>
<p appHasPermissionToAny="['EditPosts', 'DeletePosts']">
  <p appHasPermissionTo="EditPosts">
    <a routerLink="/edit">edit</a>
  </p>
  <p appHasPermissionTo="DeletePosts">
    <a routerLink="/delete">delete</a>
  </p>
</p>
```

Even though it works, I want something that required less effort from my team, since we already map every route. My idea is to have something like:

```html
<p *appHasPermissionTo>
  <a routerLink="/another-page">my link</a>
</p>
<p *appHasPermissionToAny>
  <p *appHasPermissionTo>
    <a routerLink="/edit">edit</a>
  </p>
  <p *appHasPermissionTo>
    <a routerLink="/delete">delete</a>
  </p>
</p>
```

I tried creating a Structural Directive that can read the child links so that it can conditionally display the contents based on that list. In my attempt I tried mixing together the "[Write a structural directive](https://angular.io/guide/structural-directives#write-a-structural-directive)" example from the docs and the [RouterLinkActive directive](https://github.com/angular/angular/blob/master/packages/router/src/directives/router_link_active.ts).

Is there a way that to access the child links from within a Structural Directive? Or am I on the wrong path here?

**Comment by pkozlowski-opensource** [comment]
> Is there a way that to access the child links from within a Structural Directive? Or am I on the wrong path here?

So I see a conceptual problem here: you want to grab something that is potentially not yet displayed / instantiated to drive UI display. Or, in other words you would like to introspect on what _might_ be displayed to drive other parts of the display. We don't support those things in Angular as we want drive UI display based on _model_ (data) and not on parts of UI (display).

At this point I think that you might be better off driving your UI from the permission, that is, display a set of links based on the set of permission that a user has.
