### ISSUE TITLE
IndexedDB transactions break on Safari with angular 7.2.2

### ISSUE THREAD

**Issue by jpike88** [angular/angular#28397]
# 🐞 bug report

https://github.com/angular/zone.js/issues/1183

### Affected Package

 I believe the issue rests with zone.js, but considering the severity of the issue, I figured it would be worth flagging to the main angular project.

### Is this a regression?

 I don't know, it's a fresh install, I was attempting to migrate from ng1.6

### Description

 
See https://github.com/angular/zone.js/issues/1183 for details, but basically it is an error related to performing an IndexedDB transaction operation. 

Error is:

```Error: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.```

This breaks PouchDB for example... and it's a showstopper for my migration attempt.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-issue-repro2-bo2cgs

Interesting note: Property 'result' does not exist on type 'EventTarget' TS error is present.

**Comment by manklu** [comment]
@jpike88 You don't create the object stores in you sample. This will fail even in native javascript.

https://stackblitz.com/edit/js-skrhrr?file=index.js

**Comment by jpike88** [comment]
Not sure why I'm getting thumbs down just for a bug report?!

https://github.com/pouchdb/pouchdb/blob/d098c22494f1a2c2d25c6f65ef2617dcfddedffc/packages/node_modules/pouchdb-adapter-idb/src/index.js#L645

https://github.com/pouchdb/pouchdb/blob/d098c22494f1a2c2d25c6f65ef2617dcfddedffc/packages/node_modules/pouchdb-adapter-idb/src/index.js#L708

Can you explain how the two above lines are any different from the code example I posted then? Is this perhaps a PouchDB issue, or is there an inconsistency with how I've tried to reproduce? This issue occurred originally with pouchdb-browser installed, and I breakpointed it to confirm the behaviour is the same as my code example.

**Comment by manklu** [comment]
@jpike88 If you create a new database and don't create the object stores you will get the described error in every browser on every platform even without any framework.

**Comment by jpike88** [comment]
Looks like an obscure issue with my dependencies. I spent the whole damn weekend on this X(
