### ISSUE TITLE
Angular 6 about xhr.status or xhr.responseURL

### ISSUE THREAD

**Issue by kisslove** [angular/angular#28394]
In angular 5,I use  xhr.addEventListener('loadend', onLoadEnd) to monitor http's response,I can get response.status, or xhr.responseURL.
like this:
![image](https://user-images.githubusercontent.com/7383584/51802038-99065c80-2280-11e9-9473-c884a6ad63c0.png)

But,in angular 6,I can't !!! any questions?
this result is that:
![image](https://user-images.githubusercontent.com/7383584/51801939-51330580-227f-11e9-983d-b1bd897e3d43.png)

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template
