### ISSUE TITLE
IE11 not work after building in prod enviroment

### ISSUE THREAD

**Issue by node-rookie** [angular/angular#28399]
# 🐞 bug report
ie11 now work in prod environment
![image](https://user-images.githubusercontent.com/7260662/51822286-bbe35000-2316-11e9-9867-7aa080568a64.png)

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre>
![image](https://user-images.githubusercontent.com/7260662/51822317-d74e5b00-2316-11e9-9dbe-339bd382f6c8.png)
<code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>7.2.2<code>

</code></pre>

**Anything else relevant?**

**Comment by MattiJarvinen-BA** [comment]
Have you uncommented all lines concerning IE11 in `src/polyfills.ts`, especially `import 'core-js/es6/object';`?

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
