### ISSUE TITLE
ViewEncapsulation.ShadowDom not transclude style into component

### ISSUE THREAD

**Issue by keatkeat87** [angular/angular#28392]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
7.2.0

### Is this a regression?
no

 Yes, the previous version in which this bug was not present was: ....

### Description
i m playing with angular ViewEncapsulation.ShadowDom
i found the behavior is not same with native shadow dom 
https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots
in angular the transclude element not using outside's style.

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...
https://stackblitz.com/edit/angular-snckwl?file=src%2Fapp%2Fapp.component.html

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.2.3
Node: 10.15.0
OS: win32 x64
Angular: 7.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.3
@angular-devkit/build-angular     0.12.3
@angular-devkit/build-optimizer   0.12.3
@angular-devkit/build-webpack     0.12.3
@angular-devkit/core              7.2.3
@angular-devkit/schematics        7.2.3
@angular/cli                      7.2.3
@ngtools/webpack                  7.2.3
@schematics/angular               7.2.3
@schematics/update                0.12.3
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4

</code></pre>

**Anything else relevant?**

**Comment by mhevery** [comment]
It is not supposed to be the same, since it is only inspired by. To be exact it would take a lot of parsing at runtime which would be prohibitive.
