### ISSUE TITLE
Delay rendering until required @Input are ready

### ISSUE THREAD

**Issue by okeydoky** [angular/angular#28403]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
 A clear and concise description of the problem or missing capability...
When you are writing a component, there are usually some vital inputs need to be ready for your component to work/render properly. The problem is these inputs may not be ready at the component instantiate time. To guard this scenario, the component author usually needs to provide some default values to these inputs, so the null/undefined inputs field won't break your component. But not every input type has an obvious default. For example, an object input will require to write a long object literal or your need to add a bunch of safe operator ?. in your template. A function as an input is another example.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
If we can have a decorator, say @Required and use it like:
`export class SomeComponent {
  @Required @Input requiredProperty;
}`

and usage of the component:
`<some-component [requiredProperty]="asyncData"></some-component>`
will be equivalent to
`<some-component *ngIf="requiredProperty" [requiredProperty]="asyncData"></some-component>`

I believe there are many benefits if we have this capability:

- It specifies a clear contract what component author expects component users to provide.
- Component author no longer needs to worry the inputs are in inconsistent state while waiting they arrive.
- It relieve the component users the burdens to write those *ngIf check. Image if a component has 4 or more required inputs.
- The component users may even get a compiler warning/error when they forget to bind some required inputs.

Am I too naive? Does this make sense?

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by alan-mroczek** [comment]
That's an interesting idea. However, have you considered using `*ngIf` with async pipe, and relying on data being stored in Observables? Like here:

[https://toddmotto.com/angular-ngif-async-pipe](https://toddmotto.com/angular-ngif-async-pipe)

**Comment by okeydoky** [comment]
@alan-mroczek Thanks for the tips. Yes, if I am **both** the component author and component users, I will definitely take this approach to handle the possible async input.

However, if I am writing a reusable component that meant to be used by unspecified users, I have no clues whether these inputs will come in sync or async. And I wouldn't want to force the users to pass in an observable in order to use my component.

My point is if a component relies on some inputs to be set in order to function properly, it will be either author's responsibility to handle possible null/undefined inputs so the component won't break or it will be user's responsibility to make sure these inputs are ready at the component instantiation time. In either case, somebody has to do the job.

That prompt me to think if the framework to handle it, that will relieve the burdens on both sides and lead to even cleaner codes.

**Comment by pkozlowski-opensource** [comment]
So I think that the idea is interesting but my immediate reaction to `@Required()` is that it should _throw_ if not provided rather than delay. But this is not about the name really, IMO it is super-hard to capture in a declarative way (in an annotation) conditions under which a component is displayed or not. Cases like "display only when an observable emits vale X" would still require `ngIf`. 

More generally, I believe that:
* conditions are better expressed in an imperative TS code;
* decisions about showing or not a given component should be left to the owning template.

I'm going to close this issue as won't fix based on the above. We can revisit in the future if this one gets more traction.
