### ISSUE TITLE
Http always return status 200

### ISSUE THREAD

**Issue by Delagen** [angular/angular#2841]
```
http
			.post("/api/cap/user/ping2")
			.toRx()
			//.map((response:Response) => response.json())
			.subscribe(
			(data:Object) => console.log(data),
			(data:Object) => console.error(data),
			(data:Object) => console.debug(data)
		);
```

In network tab on developer tools in browser status 404.
But in console always object with status 200.

**Comment by vicb** [comment]
release / SHA1 please ?

**Comment by Delagen** [comment]
latest alpha 29 npm release

**Comment by timjacobi** [comment]
https://github.com/angular/angular/blob/master/modules/angular2/src/http/backends/xhr_backend.ts#L40
Looks like the actual status code, among other properties, is not returned. Happy to provide a fix. Could anyone point out which properties are expected to be returned please?

**Comment by caitp** [comment]
@timjacobi you can get the status code from `this._xhr.status` --- this can do weird things sometimes though, like incorrectly reporting a network error status for file:/// requests (IIRC). There is code in 1.x $http working around that.

**Comment by timjacobi** [comment]
Thanks for info. Plan of action then? I have some time this weekend :)

**Comment by caitp** [comment]
well OTOH, an MVP fix would just pass `this._xhr.status` into the Response constructor (by adding another property `status` to the object) --- that may be enough to do it. We could worry about translating the network error status on mobile later. Feel free to send a PR

**Comment by gdi2290** [comment]
I have a PR open with the fix https://github.com/angular/angular/pull/2882

**Comment by aboeglin** [comment]
The bug concerning the status seems to be fixed on my tests, but the statusText still defaults to Ok. Maybe we could have a test on the status code and use the generic http error ( Internal Server Error and so on ). Also, it seems that the EventEmitter returned by Http.request() is calling Observer.next() even when status reports an error. In case of a 4xx or 5xx it should rather pass it to Observer.throw().
