### ISSUE TITLE
http.request always use get

### ISSUE THREAD

**Issue by Delagen** [angular/angular#2842]
```
http.request("url", {method: RequestMethods.POST})
```
send GET request instead of supplied POST

**Comment by vicb** [comment]
with which release or SHA1 ?

**Comment by Delagen** [comment]
latest alpha 29 npm release

**Comment by timjacobi** [comment]
Spotted and happy to work on it

**Comment by caitp** [comment]
that seems like a bug with the mergeOptions method, IIRC (was looking at this yesterday)

**Comment by timjacobi** [comment]
https://github.com/angular/angular/blob/master/modules/angular2/src/http/http.ts#L118
I think the problem is that we're passing `RequestMethods.GET` in here. Should be `null` instead.
I have a test case to verify this.

**Comment by timjacobi** [comment]
I have fixed it. Do you expect a test case for each HTTP verb?

**Comment by caitp** [comment]
I don’t think it should be “null”, I think the ordering in mergeOptions is just wrong — we want to send GET request by “default”, if it’s not specified in the request options.

The way mergeOptions is written, it will always overwrite the options-specified method with the default method

**Comment by caitp** [comment]
Lets wait for @jeffbcross to get in and take a look because I might be misreading his intent, but it definitely looks like the method parameter for mergeOptions is meant as a "default if not specified", it just isn't implemented that way

**Comment by timjacobi** [comment]
That would indeed make more sense since `GET` is already set as a default option in `BaseRequestOptions`

**Comment by jeffbcross** [comment]
Yeah, this got mangled in the Great Refactoring to support Dart. I'll add some comments on the PR

**Comment by jeffbcross** [comment]
@timjacobi can you open as a PR so Travis can run? In the meantime, I'm leaving comments on https://github.com/timjacobi/angular/commit/a486335266835050dd4be3152a44c79b4f5c3062

**Comment by jeffbcross** [comment]
Hey @timjacobi are you planning to open a PR for this?

**Comment by timjacobi** [comment]
Yes but I had another question
https://github.com/timjacobi/angular/commit/a486335266835050dd4be3152a44c79b4f5c3062#commitcomment-12060723

**Comment by mhevery** [comment]
Is this still an issue?
