### ISSUE TITLE
Unexpected sanitizer breaking change in 7.1.0-beta.1

### ISSUE THREAD

**Issue by artaommahe** [angular/angular#28427]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core (?)

### Is this a regression?

Yes, the previous version in which this bug was not present was: 7.1.0-beta.0

### Description

Since 7.1.0-beta.1 sanitizer removes all content inside unknown html tags. Before it removed only tags

## 🔬 Minimal Reproduction
```ts
  content = `
    <div>
      <unknown-element>
        content
      </unknown-element>
    </div>
  `;
```
```html
<div [innerHTML]="content"></div>
```

expected ( <= 7.1.0-beta.0)
https://stackblitz.com/edit/angular-innerhtml-sanitize-710beta0?file=src%2Fapp%2Fapp.component.html
```html
<div _ngcontent-c1="">
    <div>
      
        content
      
    </div>
</div>
```
actual (>= 7.1.0-beta.1)
https://stackblitz.com/edit/angular-innerhtml-sanitize-710beta1?file=src%2Fapp%2Fapp.component.html
```html
<div _ngcontent-c1="">
    <div>
      
    </div>
</div>
```

**Comment by gkalpak** [comment]
I think this was changed in #25879 and seems like an intentional change (a fix).

**Comment by artaommahe** [comment]
@gkalpak yep, but there is no `comment nodes`, it's regular nodes and they are removed. Looks like breaking change

**Comment by gkalpak** [comment]
I don't know the details (just stating the facts (that it was changed in #25879 and seems intentional).
@mhevery or @IgorMinar should know more (including whether this qualifies as a breaking change or not and why) :grin:

**Comment by mhevery** [comment]
Yes this was intentional change. The reason we remove the unknown elements is that they could be web-components which would allow user to trigger code, and could provide security hole.

So this works as intended.

**Comment by artaommahe** [comment]
@mhevery but there is nothing in changelog about this change and it's really is breaking one cause breaks previous behavior

**Comment by artaommahe** [comment]
https://angular.io/guide/releases
> Minor releases are fully backward-compatible; no developer assistance is expected during update

i've simply updated an app from 7.0.3 to 7.2.2 and this suddenly breaks part of our major functional (expected sanitized text became empty).
Just to be clear: i want to rely on angular versioning without testing everything on minor update and guessing what breaks it.

**Comment by mhevery** [comment]
> i've simply updated an app from 7.0.3 to 7.2.2 and this suddenly breaks part of our major functional (expected sanitized text became empty).
> Just to be clear: i want to rely on angular versioning without testing everything on minor update and guessing what breaks it (nothing in changelog about this, only about comments removing)

Yes, you are right, we should have done a better job communicating, and we are sorry. Normally we have these higher risk items in major versions only, but because this one had security implications it was included in the patch release.

**Comment by artaommahe** [comment]
@mhevery hm, just noticed
> The reason we remove the unknown elements

but the problem is not with the elements removing, this does not changed in that update, the problem is with inner text removing

**Comment by gkalpak** [comment]
> The reason we remove the unknown elements is that they could be web-components which would allow user to trigger code, and could provide security hole.

@mhevery, I don't understand. The old behavior was to keep the safe content (so unknown custom elements would still be stripped of, but their safe content such as text nodes would be retained). There was a problem with comment nodes being converted to text nodes (#26007), but that could have been fixed in a non-breaking way, I guess.

I don't understand what security implications this change had 😕

**Comment by gkalpak** [comment]
I submitted #28804. @mhevery, ptal.
