### ISSUE TITLE
Color Palette Angular - Custom Theme 

### ISSUE THREAD

**Issue by rqdzs** [angular/angular#28422]
Does anyone knows how to generate a color pallete on an angular 6/7 application?

I'm trying to do an application where the user can change the theme colors on real time.....
.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
