### ISSUE TITLE
minimal renderComponent Ivy app cannot be found by Protractor

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#28449]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?
Non-ivy apps can be found by Protractor.

### Description

When running Protractor e2e tests with a minimal Ivy app, Protractor cannot find the app.

This can be worked around by adding `browser.waitForAngularEnabled(false);` in the protractor tests.

## 🔬 Minimal Reproduction
- use at least Angular CLI 7.3.0-rc.0
- `ng new latest-app` 
- replace the content of `src/main.ts` with
```
import { Component, ɵrenderComponent as renderComponent } from '@angular/core';
@Component({ selector: 'app-root', template: '<h1>Welcome to ivy-latest-project!</h1>' })
class HelloWorld { }
renderComponent(HelloWorld);
```
- run `ng e2e --prod`

## 🔥 Exception or Error
```
  - Failed: Angular could not be found on the page http://localhost:4200/. If this is not an Angular application, you may need to turn off waiting for Angular.
                            Please see
                            https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
```

## 🌍  Your Environment

**Angular Version:** 7.2.2
<pre><code>
Angular CLI: 7.3.0-rc.0
Node: 10.10.0
OS: win32 x64
Angular: 7.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.0-rc.0
@angular-devkit/build-angular     0.13.0-rc.0
@angular-devkit/build-optimizer   0.13.0-rc.0
@angular-devkit/build-webpack     0.13.0-rc.0
@angular-devkit/core              7.3.0-rc.0
@angular-devkit/schematics        7.3.0-rc.0
@angular/cli                      7.3.0-rc.0
@ngtools/webpack                  7.3.0-rc.0
@schematics/angular               7.3.0-rc.0
@schematics/update                0.13.0-rc.0
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

/cc @IgorMinar @gkalpak

**Comment by kara** [comment]
This is probably because the minimal example doesn't have platform-browser, which is what provides `ELEMENT_PROBE_PROVIDERS`. For this use case, we could probably provide a lighter weight "angular" object for protractor than the full NgProbe utilities.

**Comment by sharikovvladislav** [comment]
I got something similar around ng.probe & DebugElement. Here is my comment in another thread: https://github.com/angular/angular/issues/21706#issuecomment-551087102

**Comment by JoostK** [comment]
Closing as `renderComponent` is not public API and the new `bootstrapApplication` API does support Protractor if used with `provideProtractorTestingSupport()` as provider.
