### ISSUE TITLE
ng serve --open exit with error 

### ISSUE THREAD

**Issue by gudge25** [angular/angular#28448]
# 🐞 bug report

### Affected Package
/usr/local/src/my-app # node -v
v10.15.0
/usr/local/src/my-app # npm -v
6.4.1

### Is this a regression?
first time installing 

### Description

i use step-by-step https://angular.io/guide/quickstart 

# cd my-app       
# ng serve --open
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
                                                                                          
Date: 2019-01-30T12:52:05.616Z
Hash: aa78689a23ef41f69aa4
Time: 11385ms
chunk {main} main.js, main.js.map (main) 9.73 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 236 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 16.3 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.5 MB [initial] [rendered]
ℹ ｢wdm｣: Compiled successfully.
(node:658) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/my-app/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:285:13)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:978:16)
    at Socket.stream.socket.on (internal/child_process.js:395:11)
    at Socket.emit (events.js:197:13)
    at Pipe._handle.close (net.js:611:12)
(node:658) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:658) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## 🔬 Minimal Reproduction
Dockerfile to use :

# Use an official Node runtime as a parent image
# For Angular 7  Docker
FROM node:lts-alpine
WORKDIR /usr/local/src
RUN apk add git \
&& git config --global user.email "you@example.com" \
&& git config --global user.name "Your Name"# \
&& npm install -g @angular/cli \
&& ng new my-app --defaults=true \
&& cd my-app \
&& ng serve --open
EXPOSE 4200

**Comment by jasonaden** [comment]
Thanks for the issue. Please head over to the [Angular CLI](https://github.com/angular/angular-cli) project and file it there as this appears to only be related to the CLI.
