### ISSUE TITLE
Service worker cache.match options

### ISSUE THREAD

**Issue by vitaliy-patsay** [angular/angular#28443]
# 🚀 feature request

### Relevant Package
@angular/service-worker
@angular/pwa

### Description
At the moment there is no support for [cache.match options](https://developer.mozilla.org/en-US/docs/Web/API/Cache/match)  in listed above package. I have a scenario with images which have some dynamic hashes as url parameters. 

### Desired behaviour 
The same image 

- https://cdn.example.com/image1.png?foo=bar1
- https://cdn.example.com/image1.png?foo=bar2
- https://cdn.example.com/image1.png?foo=bar3

to be cached as 

- https://cdn.example.com/image1.png

### Describe the solution you'd like
It's good to have possibility to specify some properties in ngsw-config.json assetGroup like
```
interface AssetGroup {
  name: string;
  installMode?: 'prefetch' | 'lazy';
  ...  
  cacheOptions?: {
    ignoreSearch?: boolean;
    ignoreMethod?: boolean;
    ignoreVary?: boolean;
  };
  ...
}

```

**Comment by tpiros** [comment]
I have a similar scenario which warrants for adding especially `ignoreVary` to the `AssetGroup` interface. I am using images coming from Cloudinary who have a special flag called `f_auto` to dynamagically return the right image format to the browser - i.e. WebP for Chrome, JPG or JPEG 2000 to IE so on and so forth. When requesting an image asset with the `f_auto` flag it is adding the `Vary: User-Agent` header to the response which means that even though I have an item cached it will not return anything and instead - in offline mode - will try to access the image, resulting in a 504 Gateway error.

**Comment by spike-rabbit** [comment]
As were are facing a similiar issue in my project I would like to provide a pull request.
Suggested API:
```ts
interface AssetGroup {
  name: string;
  installMode?: 'prefetch' | 'lazy';
  ...  
  cacheMatchOptions?: ClientMatchOptions;
  ...
}

export interface DataGroup {
  name: string;
  ...
  cacheMatchOptions?: ClientMatchOptions,
  cacheConfig: {
    ...
  };
}

// from DOM lib...
export interface ClientMatchOptions {
  ignoreMethod?: boolean;
  ignoreSearch?: boolean;
  ignoreVary?: boolean;
}
```

Since the ngsw always creates new requests for fetching resources without copying the original headers I would also suggest to provide default ClientMatchOptions = `{ignoreVary: true}`. Otherwise requests will never match any cached resources if a header which is listed in Vary is present.

**Comment by gkalpak** [comment]
@spike-rabbit, your recommendation sounds reasonable (from a super quick look). Feel free to create a PR and we can discuss the details there.
(Ping me if you need any help getting set up and submitting the PR.)
