### ISSUE TITLE
Allow easy way of subclassing Views

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2844]
# Goal

Listing directives in `@View` is verbose. For this reason it should be easy to make subclass of Views which have a preconfigured set of directives.

# Implementation

- [ ] Rename current `View` to `BaseView`.
- [ ] Introduce a concept of extending or subclassing the `View` where it is easy to list preset values.
- [ ] Introduce `prototype` field on the `View` which points to an existing `View` instance. Update the angular compiler logic to flatten the fields on the `View` with the `prototype` view recursively.

```
var coreView = new BaseView({
  directives: codeDirectives
})

var View = coreView.createPrototype();
// View now has all angular directives (`NgIf`, `NgFor`, etc...);

var MyAppView = new View({
  directives: [MyApp, MyMenu, ....]
}).createPrototype();

@Component(...)
@MyAppView({
  template: '...'
})
class MyComponent {
}
```

```
class BaseView {
  prototype: View; // New field
  // all existing fields

  constructor({..., prototype}) {
    this.prototype = prototype;
  }

  createPrototype() {
    var self = this;
    return function(....) {
       BaseView.apply(this, arguments);
       this.prototype = self;
    }
  }
}
```

## Dart 

In dart one can not create classes on the fly and so we need to take subclass approach.

```
const myApp = const View({
  directives: [myApp, ...]
})

class MyApp extends View {
  MyApp(...): super(..., prototype: myApp);
}
```

**Comment by PascalPrecht** [comment]
But creating a subview for a component is optional right? E.g. if I don't need anything than just a template I can still use `@View` decorator?

**Comment by alexpods** [comment]
@PascalPrecht If I understood this proposal correctly, `@View` decorator will be renamed to `@BaseView` and you'll can continue to use it.

IMHO: creating different view types only for listing of directives looks like completely overkill to me.

**Comment by pkozlowski-opensource** [comment]
> @PascalPrecht If I understood this proposal correctly, @View decorator will be renamed to @BaseView and you'll can continue to use it as usual.

This is correct

> IMHO: creating different view types only for listing of directives looks like completely overkill to me. Also I think it's easier to reason about the code when all directives are listed explicitly.

Agreed, but IMO it is more complex than this. Listing all the directives all the time isn't fun, either...

**Comment by mhevery** [comment]
@PascalPrecht yes (https://github.com/angular/angular/issues/2844#issuecomment-118011487) it is optional.

**Comment by muhammedea** [comment]
Why not defining dependencies in themplate itself. Like Aurelia framework does. 
HTML include syntax or a special directive would work. It is good for seperation of concern, as well.
Maybe this subclassing method can be used in themplates too.

**Comment by PascalPrecht** [comment]
@muhammedea I think Angular 2 is not designed to work with HTML imports like this. In addition, you prolly lose a lot of tooling capabilities.

**Comment by pkozlowski-opensource** [comment]
Didn't progress on this one during .33, moving to .34

**Comment by jeffbcross** [comment]
@pkozlowski-opensource is this still in progress? I moved to alpha 35, but please remove milestone if you don't think it will land by this Wednesday.

**Comment by pkozlowski-opensource** [comment]
Moving to .36, won't be able to finish it today.

**Comment by jessegood** [comment]
FYI: Seems the milestone needs to be updated.

**Comment by hitmanmcc** [comment]
Hello, I was wondering if you guys are still giving this some thought? We are trying to develop a component (base maintenance view container) that acts as a container for other components (entity maintenance screens). The idea is that the base maintenance view container would afford the other maintenance screens common behaviour and some common UI elements. My view is that this could be done by using this concept of view subclassing but perhaps my knowledge of the framework is leading me in the wrong direction.
If anyone has another way to achieve this, please do share. :)

Best regards,
André

**Comment by mhevery** [comment]
This is on hold until we sort out best way forward. Details here: https://docs.google.com/document/d/1rbVTKTYLz6p2smQNYI8h4-QN-m2PS6F3iQIDmSzn0Ww/edit#heading=h.6pb2txdejnyn

**Comment by pkozlowski-opensource** [comment]
I believe that this is no longer needed with the introduction of ambient directives. Closing.

**Comment by adsva** [comment]
I can't find a lot of info on ambient directives, and I'm still trying to find out if there's a way to avoid specifying all my common directives in the directives list every time. The issue threads for this seem to stop here, could you point me in the right direction?

**Comment by ericmartinezr** [comment]
@adsva https://angular.io/docs/ts/latest/api/core/index/PLATFORM_DIRECTIVES-let.html any question about it you're welcome over here https://gitter.im/angular/angular :D

**Comment by adsva** [comment]
Sweet! Thanks for the  quick reply!
