### ISSUE TITLE
HttpParams fromObject should accept ReadonlyArray<string>

### ISSUE THREAD

**Issue by jinder** [angular/angular#28452]
# 🚀 feature request

### Relevant Package
@angular/common/http

### Description
The type definition for HttpParamsOptions fromObject property only accepts string and string[].  If using immutable types, such as ReadonlyArray, you must create a new array unnecessarily to satisfy the type.

### Describe the solution you'd like
Please change the type to the following (which is backwards compatible):

```
    fromObject?: {
        [param: string]: string | string[] | ReadonlyArray<string>;
    };
```

**Comment by alan-mroczek** [comment]
Hi @jinder. How about without second array, just by casting types:

`
fromObject: {
  yourParamName: ['example', 'example2'] as string[]
}
`

I can create PR with that change, because it shouldn't be that hard to implement, but I'm not sure if it's needed.

**Comment by jinder** [comment]
@alan-mroczek I think it's poor practice to cast a immutable type to a mutable one (and preferable to slice it if need be).   

Angular's API surface should really use immutable types where possible, as they are subset of the mutable version.
