### ISSUE TITLE
feat(router): improve RouterLink usability with a Link DSL

### ISSUE THREAD

**Issue by vicb** [angular/angular#2845]
```<a router-link="/route1">route1</a>``` will crash badly (see #2843) because the expected syntax is
```<a [router-link]="['/route1']">route1</a>```

What about allowing the former syntax ? (using an array is overkill for simple use cases).

If we want to support array only, we should check the value when it is set.

/cc @Delagen

**Comment by gdi2290** [comment]
> `router-link="/route1"` is the correct syntax since it's a static value
>  otherwise `[router-link]=" '/route1' "` is correct

I don't like having to use the slash when dealing with my alias route. For example
```es6
@RouteConfig([
  {  path: '/', as: 'home', component: Home }
])
```
my link would have to be `/home` rather than `home`
`<a [router-link]="['/home']">Home</a>`

**Comment by vicb** [comment]
Not sure to get the first part of your comment (also I'm considering master)

**Comment by btford** [comment]
We (@IgorMinar, @matsko, and myself) totally agree that this is cumbersome, but there's a planned feature binding AST transformation feature that will allow us to re-introduce a nice DSL.

**Comment by vicb** [comment]
What about tracking this via this issue or a todo comment in the code ?

**Comment by btford** [comment]
I think it'd be good to start talking about this feature a bit more because the AST transformer bits will be an important generic mechanism for features besides just the route-link DSL. I'm going to start an email thread to figure out when to slate the feature, and then follow up with GitHub issues so we can discuss publicly.

**Comment by gajus** [comment]
It would be nice to have a more user friendly error. I have spent the last 2 hours trying to understand whats causing:

```js
TypeError: list.reduce is not a function in [red in null]
STACKTRACE:
Error: TypeError: list.reduce is not a function in [red in null]
    at ChangeDetectionError.BaseException (http://127.0.0.1:8000/static/app.js:9569:24)
    at new ChangeDetectionError (http://127.0.0.1:8000/static/app.js:13676:17)
    at AbstractChangeDetector.throwError (http://127.0.0.1:8000/static/app.js:14477:16)
    at AbstractChangeDetector.ChangeDetector_App_comp_0.detectChangesInRecords (eval at <anonymous> (http://127.0.0.1:8000/static/app.js:16974:17), <anonymous>:30:16)
    at AbstractChangeDetector._detectChanges (http://127.0.0.1:8000/static/app.js:14443:15)
    at AbstractChangeDetector._detectChangesInShadowDomChildren (http://127.0.0.1:8000/static/app.js:14464:19)
    at AbstractChangeDetector._detectChanges (http://127.0.0.1:8000/static/app.js:14447:15)
    at AbstractChangeDetector.detectChanges (http://127.0.0.1:8000/static/app.js:14438:74)
    at LifeCycle.tick (http://127.0.0.1:8000/static/app.js:34739:35)
    at tick (http://127.0.0.1:8000/static/app.js:30323:17)
```

when declaring `router-link` using `<a router-link='red'>Red</a>` syntax.

With help from @gdi2290, I have discovered this thread.

**Comment by btford** [comment]
@gajus– noted. Better error messages are a theme for me for this current iteration.

**Comment by btford** [comment]
Looking closer at that error, it originates from change detection. I could add something at the RouterLink boundary, but this seems like a case where change detection could produce a better error in general.

@rkirov @tbosch – would this be possible?

**Comment by gajus** [comment]
Knowing what has caused the error, the error itself makes more sense. That said, using a stack trace to locate the interpretation of the attribute value is impossible. If the error were what it is, but the stack trace was easy enough to see that the value of a property is being treated as an array, it would have been enough to trigger suspicion that I am using wrong syntax. You cannot make every dynamically generated error clear, but you can improve debugging experience.

**Comment by btford** [comment]
@gajus I'm not suggesting that an end user should have to look at the stack trace to make sense of things. I'm suggesting we improve the error message at the change detection level rather than the RouterLink level. This strategy is more general while also helping users diagnose this specific case.

**Comment by gajus** [comment]
@btford Its me who is suggesting that the end user should be able to look at the stack trace to make sense of things. This strategy is more general while also helping users diagnose this specific case.

**Comment by thekennysong** [comment]
@btford Is there a way for dynamic router-links in a template?

**Comment by mhevery** [comment]
@btford Can you provide an update?

**Comment by btford** [comment]
Do we? AFAIK, we haven't yet started work on binding AST transformations, which we need in order to implement a better linking DSL.

**Comment by ewinslow** [comment]
I'm curious whether a DSL is truly necessary or if router-link directive could just be more permissive with inputs.

I.e., if string, wrap in array and continue. That seems to make the simplest case much simpler without much extra effort.

router-link="/Index" is shorthand for [router-link]="'/Index'" just because of angular2 template semantics. That would take care of the use case that motivated this ticket.

Are there other use cases that we think a DSL would be the best solution for?

**Comment by pkozlowski-opensource** [comment]
I must say that as @ewinslow I'm not big fan of introducing custom DSL here. In my opinion cost of it (need to learn, additional code etc.) doesn't pay for benefits ("nicer" syntax).

**Comment by btford** [comment]
First, this isn't about "nicer" syntax or "shorter" links, it's about addressing a very real usability problem that the majority of early users encountered. I'm typically against inventing DSLs just for funsies, but it seems to be the appropriate approach here.

I don't think a DSL should be mandatory– it should be optional. Honestly this is more syntax sugar than DSL.

And I agree we can wrap a single string in an array for the simple case.

One issue the "DSL" (sugar) tries to fix is that newcomers find it surprising that `[router-link]="RouteName"` doesn't work. You have to quote the string– `[router-link]="'RouteName'"`. I suppose we also handle `router-link="RouteName"`, but then you have to fiddle the quotes/braces as soon as you add params.

Ideally, we have a uniform system that is short for the simple case, and doesn't require to remember to change the quotes as you add/remove stuff– which is what the DSL accomplishes.

Yes, you can avoid the DSL once you understand Angular semantics, but 90% of users aren't going to be in that boat.

The DSL also helps to avoid "lexical illusions" – it can be difficult to distinguish `"'` from `'"` from `"`. Not all editors/color schemes will make matching the braces in `['/Foo', [ 'Bar', 'Baz' ], [ 'Blah' ] ]` within an HTML attribute easy.

**Comment by IgorMinar** [comment]
landed via #5557 but we are not happy with that solution. we have a better plan that we'll implement post beta.0

closing this for now

// @btford

**Comment by bradlygreen** [comment]
Reopening for ng2 final

**Comment by IgorMinar** [comment]
@vicb is this now obsolete due to router v3?

**Comment by vsavkin** [comment]
It is obsolete.
