### ISSUE TITLE
Service Worker: missing ressource cause SW to fail silently

### ISSUE THREAD

**Issue by nreynis** [angular/angular#28464]
# 🚀 feature request

### Relevant Package
angular/service-worker

### Description
When a ressource that should be prefetched from the manifest is missing the SW enter a failsafe state `EXISTING_CLIENTS_ONLY`.
The issue with this is that it happens silently: it's really difficult to pinpoint the root cause of the problem. In my case a missing favicon in the target environment made the whole system fail. It took me three hours of debugging and backtracking to find what was wrong.

### Describe the solution you'd like
Please add some sensible error logging. A simple console.error when this throws (https://github.com/angular/service-worker-builds/blob/master/ngsw-worker.js#L780) could have turned thoses hours of painfull debugging in just seconds.

**Comment by gkalpak** [comment]
We log such failures (in SW's internal debug logger). You can find them in `/ngsw/state`.
Have you looked at [Debugging the Angular SW][1]?

[1]: https://angular.io/guide/service-worker-devops#debugging-the-angular-service-worker

**Comment by nreynis** [comment]
I just double checked and it work as expected.
When I tried `/ngsw/state` the other day, somehow the stacktraces where not there, only the clients hashes...
I guess I messed up and weren't looking at the right one.

**Comment by gkalpak** [comment]
Given the low demand for and low priority of this issue, we will likely never get around to implementing it. Closing it, but if someone feels strongly about it, we could probably accept a contribution :wink:
