### ISSUE TITLE
AOT: False positive compiler error when accessing enum in *ngFor

### ISSUE THREAD

**Issue by magnattic** [angular/angular#28469]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler

### Is this a regression?
No

### Description
When accessing an Enum type with a `string` or `keyof` variable that has been set by *ngFor, the type is not detected correctly and AOT fails with resulting type errors if you enable `fullTemplateTypeCheck`.

Example:
```
<div *ngFor="let enumKey of enumKeys; let index = index">
  {{ OrderByMode[enumKey[index]] == OrderByMode.Distance }}
</div>

<div *ngFor="let enumKey of enumKeys">
  {{ OrderByMode[enumKey] == OrderByMode.Distance }}
</div>
```
The first comparison works, the second one fails with a compiler error, because `OrderByMode[enumKey]` is not detected as being of type `OrderByMode`.

This prevents me from using template type checking in our project, as the compiler fails with wrongly detected errors.

## 🔬 Minimal Reproduction
**Note:** Using Stackblitz for this is impossible as it doesn't provide AOT compilation.

I set up a [minimal reproduction repo](https://github.com/magnattic/ng-template-enum).

Steps to reproduce:
1. `git clone git@github.com:magnattic/ng-template-enum.git`
2. Run `npm run build:prod`

## 🔥 Exception or Error
**This condition will always return 'false' since the types 'string' and 'OrderByMode' have no overlap.**

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 7.2.2
Node: 10.15.0
OS: linux x64
Angular: 7.2.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.12.2
@angular-devkit/build-angular      0.12.2
@angular-devkit/build-ng-packagr   0.12.2
@angular-devkit/build-optimizer    0.12.2
@angular-devkit/build-webpack      0.12.2
@angular-devkit/core               7.2.2
@angular-devkit/schematics         7.2.2
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.2.2
@schematics/angular                7.2.2
@schematics/update                 0.12.2
ng-packagr                         4.6.0
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.28.4
</code></pre>

**Anything else relevant?**
`fullTemplateTypeCheck` has to be enabled.

This last time I opened this issue (https://github.com/angular/angular/issues/28369) it got closed because of no reproduction. I hope this one is clearer.

This issue could be related to (and possibly fixed by?) https://github.com/angular/angular/issues/12398

**Comment by JoostK** [comment]
This works correctly in Ivy's template type checker, both expressions are checked correctly. (I had to change `enumKey[index]` to `enumKeys[index]` in the first example)
