### ISSUE TITLE
Error while creating new project wtuh SASS [Angular CLI : 7.3.0]

### ISSUE THREAD

**Issue by sid-sawant** [angular/angular#28485]
I created a new project **ng new appname** and selected style as **SASS** .
Once all npm install was finished, I ran the usual **ng serve** command.

There was an error 

> ERROR in multi ./src/styles.sass
> Module not found: Error: Can't resolve '..\path\appname\src\styles.sass' in ..\path\appname\'

The CLI actually created **.scss** file instead of **.sass**

To fix the issue just rename **style.scss** to **style.sass**

**Comment by robbailey3** [comment]
Hi, 
Selecting 'Sass' as an option when generating the project creates the correct styles.scss file, however within angular.json there is:
```
"styles": [
    "src/styles.sass"
],...
```
This, I think, is causing the error alluded to above. I.e. the compiler is searching for the .sass file and not finding it. 
Changing `styles.sass` to `styles.scss` resolves the issue.

**Comment by pkozlowski-opensource** [comment]
Belongs to https://github.com/angular/angular-cli

**Comment by Vandivier** [comment]
On angular-cli it's https://github.com/angular/angular-cli/issues/13550

Resolved in updated cli via PR https://github.com/angular/angular-cli/pull/13552
