### ISSUE TITLE
docs: Typo in Hierarchical Dependency Injectors doc

### ISSUE THREAD

**Issue by ukyo** [angular/angular#28483]
# 📚 Docs or angular.io bug report

### Description

Typo in https://angular.io/guide/hierarchical-dependency-injection#where-to-configure-providers .

### What's the affected URL?**
https://angular.io/guide/hierarchical-dependency-injection#where-to-configure-providers

### Expected vs Actual Behavior**

Actual

```
Use the `@NgModule()` `provides` option ...
```

Expected

```
Use the `@NgModule()` `providers` option ...
```

## 📷Screenshot

<img width="502" alt="2019-02-01 13 42 58" src="https://user-images.githubusercontent.com/373554/52103091-513c5800-2627-11e9-85fb-4f303f330951.png">

**Comment by brandonroberts** [comment]
Fixed via #28618
