### ISSUE TITLE
docs: Escape generics in guide/testing

### ISSUE THREAD

**Issue by ukyo** [angular/angular#28484]
# 📚 Docs or angular.io bug report

### Description

Since generics are not escaped, they can not be seen.

### What's the affected URL?**
- https://angular.io/guide/testing#the-overridecomponent-method
- https://angular.io/guide/testing#testbed-class-summary

### Expected vs Actual Behavior**

`<T>` to `&lt;T&gt;`.

## 📷Screenshot

https://angular.io/guide/testing#the-overridecomponent-method

<img width="754" alt="2019-02-01 14 10 22" src="https://user-images.githubusercontent.com/373554/52103903-556a7480-262b-11e9-8b78-d16506869c32.png">

https://angular.io/guide/testing#testbed-class-summary

<img width="752" alt="2019-02-01 14 09 22" src="https://user-images.githubusercontent.com/373554/52103935-6ca96200-262b-11e9-80bd-4ab8497f2680.png">

<img width="753" alt="2019-02-01 14 09 10" src="https://user-images.githubusercontent.com/373554/52103944-7cc14180-262b-11e9-8f1d-66a39085d553.png">

**Comment by jenniferfell** [comment]
Fixed by https://github.com/angular/angular/pull/28619
