### ISSUE TITLE
queryParamMap emits outside outside any navigation

### ISSUE THREAD

**Issue by Airblader** [angular/angular#28504]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?

I'm not entirely sure, but at least it doesn't appear to be one since Angular 6.

### Description

When subscribing to `ActivatedRoute#queryParamMap`, the initial navigation seems to emit on this observable outside any navigation. This leads to the following behavior:

1. Initial URL is `/` → `queryParamMap` emits once
2. Initial URL is `/?x=` → `queryParamMap` emits twice

With "outside any navigation" I mean that `Router#getCurrentNavigation` returns `null` in this case as well as enabling tracing in `RouterModule` shows no events before this emission. This initial emission of the parameters is always empty.

My understanding of `initialNaviation: "enabled"` based on the docs is that the initial navigation should happen before any component has been created, which should also mean that a component subscribing to it should get (only) the correct query params as at the point of injection of ActivatedRoute the initial navigation should already have happened.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-dtjazh

Note that to reproduce this, one has to manually enter the URL in the preview URL bar. Have a look at the console and observe how when adding `/?x=` to the URL, there's now two emissions, and how in either case the first emission happens before any actual navigation seems to be happening.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
7.2.0
</code></pre>

**Comment by atscott** [comment]
Hi @Airblader, I think this is working as intended. The default for `initialNavigation` is `'legacy_enabled'`, which is what your example is using. If I change it to `'enabled'` then the bootstrap _is_ blocked until initial navigation completes. 
We're also aware of how confusing these options are and are in the process of updating them to be more clear https://github.com/angular/angular/pull/37480 will introduce the new options and we will remove/deprecate old ones in v11/13. The goal is to have the options be `enabledBlocking`, `enabledNonBlocking`, and `disabled` in the end.
