### ISSUE TITLE
Seeming example mix-up in forms overview

### ISSUE THREAD

**Issue by pasha-bolokhov** [angular/angular#28505]
# 📚 Docs or angular.io bug report

### Description

 Examples of code on model-to-view and view-to-model tests seem to be mixed-up

### What's the affected URL?**
 https://angular.io/guide/forms-overview

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by brandonroberts** [comment]
@pasha-bolokhov the testing examples look correct to me. How are they incorrect for you?

**Comment by kara** [comment]
There isn't enough information here to address the issue. Please re-open a new issue that fills out the issue template and we can take another look.
