### ISSUE TITLE
docs: Hierarchical Injectors document is a bit misleading.

### ISSUE THREAD

**Issue by srcdes** [angular/angular#28508]
# 📚 Docs or angular.io bug report

### Description

The document says following:

> You can configure a provider at the module level using the providedIn metadata option for a non-root NgModule, in order to limit the scope of the provider to that module.

But, we can't limit the scope of providers declared in NgModule, unless the module is lazy loaded. Because, eagerly loaded NgModule doesn't have separate injector, it doesn't have a scope. It has a application(global) scope. The document need to state this.

### What's the affected URL?**
https://angular.io/guide/hierarchical-dependency-injection#ngmodule-level-injectors

### Expected vs Actual Behavior**

> You can configure a provider at the module level using the providedIn metadata option for a non-root NgModule, in order to limit the scope of the provider to that module **(when it is lazy loaded)**.

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by kapunahelewong** [comment]
Hi @jinbeomhong! Thanks for pointing this out. I've submitted a PR for this along with a few other small things I saw while I was in there.

**Comment by jinbeomhong** [comment]
@kapunahelewong I think this (https://angular.io/guide/providers#providedin-and-ngmodules ) also need to be updated.

**Comment by jinbeomhong** [comment]
@kapunahelewong This ( https://angular.io/guide/providers#providedin-and-ngmodules ) needs to be updated too:

> It's also possible to specify that a service should be provided in a particular `@NgModule`. For example, if you don't want UserService to be available to applications unless they import a UserModule you've created, you can specify that the service should be provided in the module:

```ts
import { Injectable } from '@angular/core';
import { UserModule } from './user.module';

@Injectable({
  providedIn: UserModule,
})
export class UserService {
}
```

> The example above shows the preferred way to provide a service in a module. This method is preferred because it enables tree-shaking of the service if nothing injects it. If it's not possible to specify in the service which module should provide it, you can also declare a provider for the service within the module:

```ts
import { NgModule } from '@angular/core';

import { UserService } from './user.service';

@NgModule({
  providers: [UserService],
})
export class UserModule {
}
```

Do i need to create another issue?

**Comment by jinbeomhong** [comment]
This (https://angular.io/guide/sharing-ngmodules#using-components-vs-services-from-other-modules ) will also only be applied when a imported module is lazy loaded:

> Importing a module with services means that you will have a new instance of that service, which typically is not what you need (typically one wants to reuse an existing service).
