### ISSUE TITLE
Getting error TypeError: Cannot read property 'minify' of undefined on prod build

### ISSUE THREAD

**Issue by vasicvuk** [angular/angular#28502]
# 🐞 bug report

### Affected Package

I tested with @angular packages version 7.2.3 and 7.2.2 but for both i get 

TypeError: Cannot read property 'minify' of undefined at minify terser-webpack-plugin/dist/minify.js:175:23

### Description

while running the command ng build --prod --build-optmizer=false i get error:

TypeError: Cannot read property 'minify' of undefined at minify terser-webpack-plugin/dist/minify.js:175:23

I have build application last day and i have logs from CI that the same code was built last day. It seems that some package is broker.

## 🌍  Your Environment

**Angular Version:**

```
@angular-devkit/architect         0.12.1
@angular-devkit/build-angular     0.12.1
@angular-devkit/build-optimizer   0.12.1
@angular-devkit/build-webpack     0.12.1
@angular-devkit/core              7.2.1
@angular-devkit/schematics        7.2.2
@angular/cdk                      7.3.0
@angular/material                 7.3.0
@ngtools/webpack                  7.2.1
@schematics/angular               7.2.2
@schematics/update                0.12.2
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
```

**Comment by teogl** [comment]
You can see a temporary solution in [https://github.com/angular/angular-cli/issues/13582](url)

**Comment by vasicvuk** [comment]
Closing since it is duplicate of #13582
