### ISSUE TITLE
copy right details not updated

### ISSUE THREAD

**Issue by AbinayaSubbiah** [angular/angular#28511]
https://angular.io/guide/typescript-configuration

![image](https://user-images.githubusercontent.com/21117461/52207035-2c074e00-28a2-11e9-908f-b6596459594e.png)

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/pull/28220 and the referenced issue

**Comment by kapunahelewong** [comment]
Closing since #28220 was merged. Thank you @AbinayaSubbiah!
