### ISSUE TITLE
docs: Provide an example of nested Angular Elements bootstrapping / usage

### ISSUE THREAD

**Issue by maxtacco** [angular/angular#28517]
# 📚 Docs or angular.io bug report

### Description

Angular Elements docs only show basic usage. There are no examples of Angular elements using other Angular elements. There is no clear explanation of how these nested elements should be bootstrapped without creating a conflict with the standard Angular component bootstrapping when Angular/custom element's tag name matches Angular component's selector.

Note, that @robwormald gave a short description of how nested Angular elements can work in https://github.com/angular/angular/issues/24397#issuecomment-396009894, but he didn't provide an explanation/example on how "to put each element in its own NgModule, and bootstrap them separately".

Thank you.

## 🌍  Your Environment
Angular/Elements 7.2.3 
### Browser info
Chrome Version 71.0.3578.98 (Official Build) (64-bit)

### Anything else relevant?
Related issue: https://github.com/angular/angular/issues/24397

**Comment by maxtacco** [comment]
Ok, I think I found an example of how nested Angular elements can be bootstrapped using separate modules: https://stackblitz.com/edit/nesting-angular-elements-example
Still, would be nice to have this in the official docs.

**Comment by EpicDrakkar** [comment]
Two modules from the same project is straightforward, but Im actually creating 2 projects (As a result two wrapped javascript wc).

Im trying to add this in a external node js server (:8080) And attach One js.Wc (wc-parent) which calls another js.Wc (wc-child) inside of it, its not rendering the child only the parent. Funny part is that both projects runs perfectly when separated, No errors, no logs. :*(

**Comment by spk27** [comment]
I'm having the same problem. Individual external source component works well, however, nested component doesn't work. 
Both, parent and child should recieve Input data (object), but they don't. Debugging, I realize that there is a big delay attaching that data.
It would be great to see an example with external source components with at least one nested component, both registrered as angular elements on their own app.

**Comment by mgechev** [comment]
That's not on our immediate priority list right now. I'll suggest closing the issue for now and revisiting when we invest further in Angular Elements. Until then, it's an excellent opportunity for community contribution.
