### ISSUE TITLE
animations component inject array key / value

### ISSUE THREAD

**Issue by yanis-git** [angular/angular#28513]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/animations

### Is this a regression?

I'am not sure to be honest, but i don't think so.

### Description

When you inspect element where animation is processed, you can find injected property like following : 

    element.style {
        height: 200px;
        opacity: 1;
        background-color: yellow;
        0: height;
        1: opacity;
        2: background-color;
        background-color: yellow;
        height: 200px;
        opacity: 1;
        webkit-opacity: 1;
    }

As you can see, you can find unexpected  css property : 

    element.style {
       // [...]
        0: height;
        1: opacity;
        2: background-color;
       // [...]
    }

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-i1xwys

## 🌍  Your Environment

**Angular Version:**
@angular/animation version 7.2.2

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/27958
