### ISSUE TITLE
docs: Singleton services docs example shows wrong comments.

### ISSUE THREAD

**Issue by srcdes** [angular/angular#28524]
# 📚 Docs or angular.io bug report

### Description

`forRoot()` part(https://angular.io/guide/singleton-services#forroot) explains how we can have services provided at module level as a singleton(app-wide). The example shows that `UserServiceConfig` is singleton, not `UserService`. The `UserService` is not singleton, because it is not following `forRoot()` pattern. But, see the comments within live example. This is wrong comments, isn't it?:

```ts
// Proves that UserService is an app-wide singleton and only instantiated once
// IFF shared.module follows the `forRoot` pattern.
//
// If it didn't, a new instance of UserService would be created
// after each lazy load and the userName would double up.
import { Injectable, Optional } from '@angular/core';

let nextId = 1;

export class UserServiceConfig {
  userName = 'Philip Marlowe';

  constructor() {
    console.log('UserServiceConfig is created')
  }
}

@Injectable()
export class UserService {
  id = nextId++;
  private _userName = 'Sherlock Holmes';

  constructor(@Optional() config: UserServiceConfig) {
    if (config) { this._userName = config.userName; }
    console.log('UserService is created');
  }

  get userName() {
    // Demo: add a suffix if this service has been created more than once
    const suffix = this.id > 1 ? ` times ${this.id}` : '';
    return this._userName + suffix;
  }
}
```

You could see the `UserSerivce` is not following `forRoot()` pattern, but `UserServiceConfig` is following the pattern:

```ts
@NgModule({
  imports:      [ CommonModule ],
  declarations: [ TitleComponent ],
  exports:      [ TitleComponent ],
  providers:    [ UserService ] // UserSerivce is declared at providers. It is not making this singleton.
})
export class CoreModule {
  // We should ignore CoreModule's constructor, because it is not addressed in this docs part.
  // So, we should consider CoreModule has a default constructor.

  static forRoot(config: UserServiceConfig): ModuleWithProviders {
    return {
      ngModule: CoreModule,

      // But, UserServiceConfig is a singleton, because it is following the pattern.
      providers: [
        {provide: UserServiceConfig, useValue: config }
      ]
    };
  }
}
```

You can prove the `UserService` is not singleton by adding the `console.log()` within constructor:

```ts
export class UserServiceConfig {
  userName = 'Philip Marlowe';

  constructor() {
    console.log('UserServiceConfig is created'); // log
  }
}

@Injectable()
export class UserService {
  // ...

  constructor(@Optional() config: UserServiceConfig) {
    if (config) { this._userName = config.userName; }

    console.log('UserSerivce is created'); // log
  }

  // ...
}
```

Because `CustomersComponent` has declared `UserService` as a provider, we have to remove the provider: 

```ts
@Component({
  template: `
    <h2>Customers of {{userName}}</h2>
    <router-outlet></router-outlet>
  `,
  providers: [ UserService ] // <--- remove it from providers
})
export class CustomersComponent {
  userName = '';
  constructor(userService: UserService) {
    this.userName = userService.userName;
  }
}
```

For now, `UserService` is injected into `CustomersComponent` as a singleton. Nevertheless,  `UserService` is still not singleton. Because, `CoreModule` doesn't force it as a singleton. Currently, `UserService` is injected into `CustomersComponent` from parent injector(application root injector). We also have to use `forRoot()` pattern to `UserService` too, to force it as singleton.

### What's the affected URL?**

docs : https://angular.io/guide/singleton-services#forroot
live example : https://angular.io/generated/live-examples/ngmodules/stackblitz.html

## 📷Screenshot

Whenever we visit Customer menu, `UserService` is created. But, `UserServiceConfig` is not:

<img width="403" alt="screenshot" src="https://user-images.githubusercontent.com/32840866/52235584-dfeef480-2907-11e9-9748-ab01ace5b425.png">

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by kapunahelewong** [comment]
Thank you, @jinbeomhong! Great catch. Is this better? [https://github.com/angular/angular/blob/e39a744f44c29b6d79ec53428850327b1045bc05/aio/content/examples/ngmodules/src/app/greeting/user.service.ts#L1](https://github.com/angular/angular/blob/e39a744f44c29b6d79ec53428850327b1045bc05/aio/content/examples/ngmodules/src/app/greeting/user.service.ts#L1)

**Comment by srcdes** [comment]
@kapunahelewong Is this can be closed?

**Comment by kapunahelewong** [comment]
Oh yes, thank you, @srcdes :)
