### ISSUE TITLE
[docs] Consider detailing what lazy loading *is*

### ISSUE THREAD

**Issue by DeborahK** [angular/angular#28547]
# 📚 Docs or angular.io bug report

### Description
At this link: https://angular.io/guide/lazy-loading-ngmodules, as part of the discussion of the high level view, consider describing what lazy loading *is* and why someone would want to use it before providing the steps for how to implement it.

This would make it easier to point developers to this page to get the entire overview of lazy loading.

 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/guide/lazy-loading-ngmodules

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by kapunahelewong** [comment]
Closing since PR is merged. Thanks for pointing this out, @DeborahK! 🌺💚🌷
