### ISSUE TITLE
subscribe show deprecate.

### ISSUE THREAD

**Issue by shekharsumanpandey-tudip** [angular/angular#28559]
Hello,

I have a problem with subscribe which show depricate.
Node: 8.11.2,
Npm: 6.7.0

  "@angular/animations": "^7.2.3",
    "@angular/common": "^7.2.3",
    "@angular/compiler": "^7.2.3",
    "@angular/core": "^7.2.3",
    "@angular/forms": "^7.2.3",
    "@angular/http": "^7.2.3",
    "@angular/platform-browser": "^7.2.3",
    "@angular/platform-browser-dynamic": "^7.2.3",
    "@angular/router": "^7.2.3",

 "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "^7.3.0",
    "@angular/compiler-cli": "^7.2.3",
    "@types/core-js": "0.9.35",
    "@types/jasmine": "2.5.38",
    "@types/jquery.slimscroll": "1.3.30",
    "@types/node": "6.0.60",
    "typescript": "3.1.1"
  }
}
We are using HttpClient for API call.

![subscribe_issue](https://user-images.githubusercontent.com/23448126/52341039-85ed4c80-2a37-11e9-9514-62ced3cbec5e.png)

Please find the attached screenshot of the code snippet.
 
Can any one help me out with this.

**Comment by pkozlowski-opensource** [comment]
The whole `@angular/http` package was deprecated long time ago, you should migrate to ` @angular/common/http`, see: https://angular.io/guide/http

Your IDE gives you a warning that something was deprecated so it is a good hint to follow and start updating your code.

**Comment by ericmartinezr** [comment]
This seems to be the cause https://github.com/ReactiveX/rxjs/pull/4202 which appears in their changelog https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#640-2019-01-30 .

**Comment by ericmartinezr** [comment]
I just wanted to ads that the subscribe signature changed too, so it could be both https://github.com/ReactiveX/rxjs/pull/4202

**Comment by shekharsumanpandey-tudip** [comment]
> The whole `@angular/http` package was deprecated long time ago, you should migrate to ` @angular/common/http`, see: https://angular.io/guide/http
> 
> Your IDE gives you a warning that something was deprecated so it is a good hint to follow and start updating your code.

Thanks Pawel Kozlowski,

I have already use @angular/common/http but it shows me deprecated
So, can I remove @angular/http from package.json?

**Comment by pkozlowski-opensource** [comment]
> I have already use @angular/common/http but it shows me deprecated

It might be RxJs than as pointed by @ericmartinezr 

> So, can I remove @angular/http from package.json?

If you don't use it.

**Comment by shekharsumanpandey-tudip** [comment]
> > I have already use @angular/common/http but it shows me deprecated
> 
> It might be RxJs than as pointed by @ericmartinezr
> 
> > So, can I remove @angular/http from package.json?
> 
> If you don't use it.

So how I can solve this issue

**Comment by trotyl** [comment]
This is most likely a WebStorm issue which doesn't use TypeScript language server, resulting in incorrect overload resolution, better to report it there.

**Comment by shekharsumanpandey-tudip** [comment]
> This is most likely a WebStorm issue which doesn't use TypeScript language server, resulting in incorrect overload resolution, better to report it there.

Thanks @trotyl 
But on few component,s it does not show deprecate, only HttpClient request it gives me issue.

**Comment by trotyl** [comment]
@shekharsumanpandey-tudip Please provide a minimal reproduction without using IDE, e.g. [TSLint](https://palantir.github.io/tslint/rules/deprecation/).
