### ISSUE TITLE
Bazel yarn_install doesn't work with package.json postinstall script.

### ISSUE THREAD

**Issue by Serginho** [angular/angular#28556]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/bazel

### Is this a regression?
No

## 🔬 Minimal Reproduction
- `ng new testproject`
- Go to `package.json` and add `postinstall: "node ./scripts/vendor-patches.js"`
- Run bazel
## 🔥 Exception or Error
<pre><code>
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/private/var/tmp/_bazel_user/1278b7bdb66d5638f4b8805b0e51d711/external/npm/scripts/vendor-patches.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
error Command failed with exit code 1.

</code></pre>

## 🌍  Your Environment

**Angular Version:** 7.2.2

</code></pre>

**Anything else relevant?**

**Comment by kyliau** [comment]
This is by design. Bazel needs to be informed of the script that's needed by postinstall.
This can be solved by adding the script to `data` attribute of `yarn_install`.
For more info, see example https://github.com/angular/angular/blob/master/integration/bazel/WORKSPACE#L48
