### ISSUE TITLE
source code is displaying in to input field

### ISSUE THREAD

**Issue by santhoshraju621** [angular/angular#28565]
hi
 i am using the reactive forms while initiating the form controls native code is displaying.

i declared the form like this. it is injecting the code to input element.

`this.addCourses = new FormGroup({
      "courseName":new FormControl([Validators.required,Validators.minLength(2),Validators.maxLength(150)]),
      "title":new FormControl('',[Validators.required,Validators.minLength(3),Validators.maxLength(150)]),
      "description":new FormControl('',[Validators.required,Validators.minLength(10),Validators.maxLength(200)]),
      "startDate":new FormControl(null,[Validators.required]),
      "courseDuration":new FormControl('',[Validators.required,Validators.min(1)])
    });`

i got the output like this in the screen shot.

https://lh3.googleusercontent.com/-WHHKm4wOVxo/XFr7S90R4fI/AAAAAAAAA9Y/VBvQUr0q8pkp96w5t9u0pdFc3hFNWhezgCL0BGAYYCw/h768/2019-02-06.png

i am using Angular version 5.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
