### ISSUE TITLE
Mistake in the Router docs - slideInDownAnimation should be slideInAnimation

### ISSUE THREAD

**Issue by sharp0111** [angular/angular#28572]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...
In the Routing & Navigation -> Milestone 3: Heroes feature -> Adding routable animations section of the documentation, there is a typo - slideInDownAnimation, but it should be slideInAnimation in these paragraphs:
"Back in the AppComponent, import the RouterOutlet token from the @angular/router package and the slideInDownAnimation from './animations.ts.
Add an animations array to the @Component metadata's that contains the slideInDownAnimation."

### What's the affected URL?**
https://angular.io/guide/router#adding-animations-to-the-routed-component

### Expected vs Actual Behavior**

Expected: slideInAnimation
Actual: slideInDownAnimation

**Comment by sharp0111** [comment]
Actually, there are a bunch of typos and inconsistencies throughout the entire document!!!

**Comment by kapunahelewong** [comment]
Thank you, @SebastienBtr!

**Comment by sharp0111** [comment]
Thank you, all!

**Comment by kapunahelewong** [comment]
@sharp0111 Thanks for bringing it up. We try to catch and fix things like this but sometimes don't see it yet. Pointing them out is always welcome. :)

**Comment by gkalpak** [comment]
BTW, this will be partially fixed by #28640.
