### ISSUE TITLE
Angular-Flask issue for Uploading file through api call

### ISSUE THREAD

**Issue by akshayklr057** [angular/angular#28586]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please help us process issues more efficiently by filing an
issue using one of the following templates:

https://github.com/angular/angular/issues/new/choose

Thank you!
Hi team,
For my project, I am using Flask at server side and Angular at the client side. When I call a flask API to upload a CSV file then sometimes the file gets uploaded successfully and sometimes it throws the keyError on the file name.
I am continuously facing this issue and have tried various methods to handle the header while calling the API, but no luck in that. 
I have contacted the Flask community for the same but they are saying that it's some bug in the client-side. 
This is something to do with the form data being sent from the client side (angular) to server side and not getting passed correctly

I have tried using **headers: {'Content-Type': 'application/x-www-form-urlencoded'})**

The client-side is showing some CORS-POLICY error. 
And the funny part is that this error is coming sometimes and sometimes the file gets uploaded successfully.
[full_traceback.txt](https://github.com/angular/angular/files/2839989/full_traceback.txt)

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
