### ISSUE TITLE
Location service not provided in CommonModule

### ISSUE THREAD

**Issue by jasonaden** [angular/angular#28580]
The `Location` service is used by the Angular Router. But it's difficult to use outside the router because it's not provided in the `CommonModule`. Instead, it's configured to be provided in the [RouterModule](https://github.com/angular/angular/blob/master/packages/router/src/router_module.ts#L58).

All existing examples I can find use the Router, so they wouldn't break. However, this makes it difficult to use `Location` on it's own.

**Comment by atscott** [comment]
`Location` is now provided in `CommonModule`: https://angular.io/api/common/Location
