### ISSUE TITLE
ivy: async pipe in ngIf throws error at runtime

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#28587]
# 🐞 bug report

### Is this a regression?

This is not working only when using Ivy

### Description

Using the `async` pipe in an `ngIf` while using Ivy throws an error at runtime.

## 🔬 Minimal Reproduction
```
ng new ivy-async --defaults --experimental-ivy
# bump ng packages to 8.0.0-beta.3
# change app.component.ts and app.component.html to code below
ng serve --aot
```

app.component.ts
```typescript
import { Component } from '@angular/core';
import { interval } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  obs$ = interval(1000);
}
```

app.component.html
```html
<div *ngIf="obs$ | async">hello</div>
```

## 🔥 Exception or Error

Runtime error in Chrome
<pre><code>
ERROR TypeError: Cannot read property 'length' of null
    at getComponentViewByIndex (core.js:3131)
    at createViewRef (core.js:13421)
    at injectChangeDetectorRef (core.js:13408)
    at push../node_modules/@angular/core/fesm5/core.js.ChangeDetectorRef.__NG_ELEMENT_ID__ (core.js:14774)
    at getOrCreateInjectable (core.js:4353)
    at Module.directiveInject (core.js:11467)
    at Object.AsyncPipe_Factory [as factory] (common.js:5056)
    at Module.pipe (core.js:18754)
    at AppComponent_Template (app.component.ts:9)
    at checkView (core.js:11151)
</code></pre>

Note that the stack trace is slightly different in Firefox:
<pre><code>
ERROR TypeError: "slotValue is null"
    getComponentViewByIndex
   AppComponent_Template
   checkView
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.0
Node: 11.9.0
OS: darwin x64
Angular: 8.0.0-beta.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.0
@angular-devkit/build-angular     0.13.0
@angular-devkit/build-optimizer   0.13.0
@angular-devkit/build-webpack     0.13.0
@angular-devkit/core              7.3.0
@angular-devkit/schematics        7.3.0
@angular/cli                      7.3.0
@ngtools/webpack                  7.3.0
@schematics/angular               7.3.0
@schematics/update                0.13.0
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

Note that the `*ngIf` is responsible here, simply using:

```html
<div>{{ obs$ | async }}</div>
```
is working.

Using the `as` syntax is also throwing with the same error

**Comment by cexbrayat** [comment]
I found this issue while trying to reproduce one I have in a real application. The error I have in my real application is slightly different:

```
ERROR Error: No provider for ChangeDetectorRef!
    at getOrCreateInjectable (core.js:4355)
    at Module.directiveInject (core.js:11481)
    at Object.AsyncPipe_Factory [as factory] (common.js:5056)
    at Module.pipe (core.js:18764)
    at MenuComponent_Template (menu.component.ts:21)
    at checkView (core.js:11165)
    at componentRefresh (core.js:10796)
    at refreshChildComponents (core.js:8906)
    at refreshDescendantViews (core.js:8851)
    at checkView (core.js:11166)
```

but I can't reproduce in a small repro...

After digging a little, I tend to think that they are maybe linked, as the small repro is throwing in `injectChangeDetectorRef` and my real app is throwing with `No provider for ChangeDetectorRef`.

**Comment by pkozlowski-opensource** [comment]
@cexbrayat I start to suspect that it has nothing to do with the async pipe but simply something that is trying to inject `ChangeDetectorRef` inside an embedded view. 

Could you try to write a minimal directive that tries to inject  `ChangeDetectorRef` and put it inside `ngIf`? What would help us even more would be a PR with a test that is passing in a view engine and fails in ivy. A good place for such test would be somewhere around [here](https://github.com/angular/angular/blob/master/packages/core/test/linker/view_injector_integration_spec.ts#L807) - there is a directive that is trying to inject  `ChangeDetectorRef` there, we just need a test where this directive is put inside `ngIf`.

**Comment by cexbrayat** [comment]
@pkozlowski-opensource Hmm, maybe I'm missing something but it looks like it's working if I do:

```typescript
@Directive({
  selector: '[appInjectCdref]'
})
export class InjectCdrefDirective {

  constructor(private cd: ChangeDetectorRef) {
    console.log(this.cd);
  }
}
```

and use it inside a `ngIf`:
```html
<div *ngIf="show">
  <div appInjectCdref></div>
</div>
```

Was it what you had in mind?

**Comment by pkozlowski-opensource** [comment]
Yep, this is what I had on my mind but it seems like it is linked to pipes somehow (or something else that I'm not seeing). In any case it looks like a bug that needs to be investigated / fixed. We will take care of it as part of our backlog of other bugs we've discovered. Thnx for reporting!

**Comment by petebacondarwin** [comment]
Logged internally as FW-1048

**Comment by alexzuza** [comment]
Reproduction:

```
@Pipe({ name: 'pipeWithCdRefInjection' })
export class PipeWithCdRefInjection implements PipeTransform {

  constructor(private cd: ChangeDetectorRef) {}

  transform(value: any): any {
    return value;
  }
}

@Component({
  selector: 'my-app',
  template: `<div *ngIf="1 | pipeWithCdRefInjection">1</div>`
})
export class AppComponent {}
```

**Comment by aitboudad** [comment]
another issue that I've got which may related to `async` piep is when compiling (`ivy-ngcc`) the [@ngx-loading-bar](https://github.com/aitboudad/ngx-loading-bar/blob/master/packages/core/src/loading-bar.component.ts#L7) package the following error is raised:

```batch
Error: Illegal state: Pipes should have been converted into functions. Pipe: async
```

the code is:
```html
<ng-container *ngIf="(value !== null ? value : loader.progress$|async) as progress">
  ...
</ng-container>
```

**Comment by alexzuza** [comment]
@aitboudad 
Seems your case is a compile time error while the current issue is a runtime error.

Your issue may related to the fact that ViewBuilder(ViewEngine) transforms pipe to BuiltinFunctionCall while TemplateDefinitionBuilder(IVy) doesn't.

For example, the following will also fail:

    {{ x ? 1 : 2 | json }}

**Comment by JoostK** [comment]
I have updated #27565 with a proper fix this time around. The following two scenarios could previously occur:

1. If the template was at the root of a view, the previously processed
node would be the component's host node outside of the current view.
Accessing that node in the context of the current view results in a crash.
2. For templates not at the root, the ChangeDetectorRef injected into the
pipe would correspond with the previously processed node. If that node
hosts a component, the ChangeDetectorRef would not correspond with the
view that the ng-template is part of.

The `ERROR TypeError: Cannot read property 'length' of null` corresponds with situation 1.

**Comment by alexzuza** [comment]
@aitboudad I opened https://github.com/angular/angular/pull/28635 which is addressed to your issue
