### ISSUE TITLE
Autocomplete through the `FormGroup` class

### ISSUE THREAD

**Issue by LukasLSC** [angular/angular#28590]
# 🚀 feature request

### Relevant Package

This feature request is for **@angular/forms**.

### Description
The ability to have an autocomplete using the `FormGroup` class with a type parameter.

So, instead of writing this:

```ts
contactUs: new FormGroup({ ... });
```

We'd be able to write this:

```ts
contactUs: new FormGroup<ContactUs>({ ... });
```

`ContactUs` would be a class, an interface or a type which would help with the autocomplete and the easier usage. For example, in my case, `ContactUs` is an interface:

```ts
interface ContactUs {
    name: FormControl;
    email: FormControl;
    message: FormControl;
}
```

### Describe the solution you'd like
I digged into the `~\angular\node_modules\@angular\forms\src\model.d.ts` file, moved to the `FormGroup` type class declaration.

That's how the `model.d.ts` file looked before:
![Default type definition](https://i.imgur.com/VRnpeWM.png)

First, I changed the `constructor` first parameter's type from:
```ts
[key: string]: AbstractControl;` to `[P in keyof T]: AbstractControl;`
```

Then, changed the class to a generic. From `FormGroup` to `FormGroup<T>`.
![Updated type definition](https://i.imgur.com/uDv8PDS.png)

We've got two another issues:

> Generic type 'FormGroup<T>' requires 1 type argument(s). ts(2314) [101, 22]
> Generic type 'FormGroup<T>' requires 1 type argument(s). ts(2314) [348, 23]

Changed the **101** line from:

```ts
readonly parent: FormGroup | FormArray;
```

To:

```ts
readonly parent: FormGroup<{ [key: string]: AbstractControl }> | FormArray;
```

And same with the line **348**.

Not sure if that's a perfect solution, but that's what I came to :) This way, I was able to get a perfect autocomplete based on the type I've provided in the type parameter:

![Autocomplete in action](https://i.imgur.com/VauRGHG.png)

`[key: string]` doesn't help a lot in this situation, updating the type definition would be very nice :)

**Comment by alexzuza** [comment]
Dup of https://github.com/angular/angular/issues/13721?

**Comment by LukasLSC** [comment]
Yes, haven't seen this thread before, sorry.
