### ISSUE TITLE
Angular 7 Checkbox: Template driven form ngModel - not working

### ISSUE THREAD

**Issue by jvutukur** [angular/angular#28606]
# 🐞 bug report

### Affected Package
'@angular/forms';

### Description
Template driven form - with NgModel no data binding. Unable to fetch user checkbox input
On change of checkbox. Value of checkbox in form in not changing. 
Able to get the  values of all other fields like textbox, dropdown, radio button.

`<form #filterForm="ngForm" ngNativeValidate>`
`   <div *ngFor="let filter of filterRadioGroup.filters">`
`        <div [ngSwitch]="filter.fieldType">`
`             <div *ngSwitchCase="'checkbox'" class="form-group filter-element">`
`                <input [type]="filter.fieldType" [name]="filter.filterName"  ngModel/>`
`               <label>  {{ filter.displayName }}</label>       `
`             </div>`
`            <!-- switch cases for other inputs like textbox, select(dropdown)  all others works-->`
`        </div>`
`   </div>`
`</form>`

## 🔥 Exception or Error

Unable to fetch Checkbox selection.

## 🌍  Your Environment

**Angular Version:** 
    "@angular/animations": "^7.1.1",
    "@angular/common": "^7.1.1",
    "@angular/compiler": "^7.1.1",
    "@angular/core": "^7.1.1",
    "@angular/forms": "^7.1.1",
    "@angular/http": "^7.1.1",
    "@angular/platform-browser": "^7.1.1",
    "@angular/platform-browser-dynamic": "^7.1.1",
    "@angular/router": "^7.1.1",
    "@angular/service-worker": "^7.1.1",
    "alasql": "^0.4.11",
    "core-js": "^2.5.2",
    "font-awesome": "^4.7.0",
    "rxjs": "^6.2.1",
    "tslib": "^1.9.0",
    "zone.js": "^0.8.26"

**Comment by jvutukur** [comment]
Stackbliz url - https://stackblitz.com/edit/angular-qmnefx

**Comment by alexzuza** [comment]
You should write `type="checkbox"` explicity if you want CheckboxControlValueAccessor to be applied on your element.

```
<div *ngSwitchCase="'checkbox'" class="form-group filter-element">
  <input type="checkbox" [name]="filter.filterName" ngModel/>
   ..
</div>
```

Otherwise Angular treats this input as `input[type=text]` and uses DefaultValueAccessor. That's why you always get value as a string `""`

https://stackblitz.com/edit/angular-9r7et1?file=src/app/app.component.html

**Comment by pkozlowski-opensource** [comment]
Wow, thnx for digging into it and helping out with the issues @alexzuza ! I guess this one can be closed now as a support request.
