### ISSUE TITLE
ci: Global approvers list in CODEOWNERS doesn't seem to work

### ISSUE THREAD

**Issue by kara** [angular/angular#28601]
We have a "@angular/framework-global-approvers" group in the [CODEOWNERS file](https://github.com/angular/angular/blob/master/.github/CODEOWNERS#L81). This group of people should be able to approve PRs even if they are not a part of the specific sub-group(s) that own the files in the PR.  Currently, this doesn't work. If a person in the global approval group approves a PR, it still requests approval from any other sub-group that that person is not directly a part of.

**Comment by gkalpak** [comment]
Obsolete, since we have now moved from CODEOWNERS to PullApprove (in #34814), which does support global approvers groups.
