### ISSUE TITLE
Tour of Heroes doesn't compile with Ivy and angular-in-memory-web-api

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#28603]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 

Yes

### Description

 A clear and concise description of the problem...

When using Ivy/ngcc with angular-in-memory-api version 0.8.0, the app does not compile and emits an error.

The app currently works under V7 and V8 without Ivy with no issues.

## 🔬 Minimal Reproduction

 https://github.com/brandonroberts/ivy-in-memory

Instructions to reproduce are in the README

## 🔥 Exception or Error
<pre><code>

```
ERROR in Value at position 4 in imports array is not a reference: [object Object]
```
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.1.4
Node: 10.14.2
OS: linux x64
Angular: 8.0.0-beta.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@angular/cli                      7.1.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
</code></pre>

**Anything else relevant?**

I did an additional build of `angular-in-memory-web-api` with `ng-packagr` and `8.0.0-beta.3` and the app works correctly under Ivy/ngcc.

Build repo is here: https://github.com/brandonroberts/in-memory-web-api-bazel
Build branch is here: https://github.com/brandonroberts/in-memory-web-api/tree/ng-packagr-build

cc: @kara @IgorMinar @petebacondarwin

**Comment by alexzuza** [comment]
Ivy compiler does not resolve ModuleWithProviders yet.

```
HttpClientInMemoryWebApiModule.forRoot(
  InMemoryDataService, { dataEncapsulation: false }
)
```

https://github.com/angular/angular/blob/50732e1564d99a36e223cf4183ea09c5cc1fb993/packages/compiler-cli/src/ngtsc/annotations/src/ng_module.ts#L331-L332

cc @alxhub

**Comment by alxhub** [comment]
I think that `TODO` is incorrect, we do indeed process `ModuleWithProviders` (a few lines above, actually, with another comment).

**Comment by petebacondarwin** [comment]
But it looks like the error that is being reported in this issue comes from that line.

**Comment by brandonroberts** [comment]
I'm still seeing this issue with the latest beta(11). Was https://github.com/angular/angular/pull/29119 supposed to fix this issue @JoostK?

```
Angular CLI: 8.0.0-beta.11
Node: 10.15.3
OS: linux x64
Angular: 8.0.0-beta.11
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-beta.11
@angular-devkit/build-angular     0.800.0-beta.11
@angular-devkit/build-optimizer   0.800.0-beta.11
@angular-devkit/build-webpack     0.800.0-beta.11
@angular-devkit/core              8.0.0-beta.11
@angular-devkit/schematics        8.0.0-beta.11
@ngtools/webpack                  8.0.0-beta.11
@schematics/angular               8.0.0-beta.11
@schematics/update                0.800.0-beta.11
rxjs                              6.4.0
typescript                        3.3.4000
webpack                           4.29.6
```

**Comment by brandonroberts** [comment]
I've updated the repo also https://github.com/brandonroberts/ivy-in-memory

cc: @alxhub

**Comment by JoostK** [comment]
@brandonroberts Hmm, seeing that [angular-in-memory-web-api](https://unpkg.com/angular-in-memory-web-api@0.8.0/in-memory-web-api.module.js) also has that `InMemoryWebApiModule_1` indirection going on it *should* be supported with #29119. I'm not sure what would prevent this from working this time around, I'll need to take a look at it.

**Comment by JoostK** [comment]
Okay, I ran through the repro and have found the culprit on why `angular-in-memory-web-api` is causing problems. The root issue is that its `package.json` does not specify a `typings` nor `types` issue, which `ngcc` tests for a prerequisite for processing an entry-point:

https://github.com/angular/angular/blob/ea70d41ac2314cdfc58688b488f85108466e5f92/packages/compiler-cli/ngcc/src/packages/entry_point.ts#L83-L87

The `null` return causes the entry-point to be dropped from further processing, as it is considered not to be an Angular package at all.

**Comment by JoostK** [comment]
Tracked as FW-1299
