### ISSUE TITLE
"Too long with no output" error in integration_test job

### ISSUE THREAD

**Issue by kara** [angular/angular#28611]
The "integration_test" job seems to fail consistently in the "run_tests" step with a "Too long with no output" error:

See https://circleci.com/gh/angular/angular/194384

Debugged a bit with SSH and looks like the yarn install is hanging when it starts running the bazel  integration test:

```
#################################
Running integration test bazel
#################################
yarn install v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
```

**Comment by gkalpak** [comment]
Note that the output of the linked job is different than what you saw when debugging via SSH:

```
#!/bin/bash -eo pipefail
./integration/run_tests.sh ${CIRCLE_NODE_INDEX} ${CIRCLE_NODE_TOTAL}
Too long with no output (exceeded 10m0s)
```

The latter output is what I also see most often. It should be fixed by #28615.
(Once #28615 is merged, then we might start seeing specific tests (such as the `bazel` test) fail :grin:)

**Comment by kara** [comment]
Oh, I assumed that the log in the linked job wasn't the full output. So it looks like we have two different issues then.

**Comment by kara** [comment]
Looks like the root issue is resolved for now. If anyone else sees this, please re-open the issue with a link to the failing job.

**Comment by kara** [comment]
Seeing the integration test error again:

```
#################################
Running integration test bazel
#################################
yarn install v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
```

https://circleci.com/gh/angular/angular/236296

**Comment by kara** [comment]
This is outdated. Closing.
