### ISSUE TITLE
NgModule compilation errors being ignored with ivy/ngtsc

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#28621]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Components not being included in any NgModules, or included in the declarations of multiple NgModules caused compilation errors when running in AoT mode.

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 

https://github.com/brandonroberts/ivy-declarations-ngmodules-compilation

The repro steps are in the README

## 🔥 Exception or Error

<pre><code>

ERROR in : Cannot determine the module for class StrayComponent! Add StrayComponent to the NgModule to fix it
</code></pre>

<pre><code>

ERROR in : Type StrayComponent is part of the declarations of 2 modules
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.1.4
Node: 10.14.2
OS: linux x64
Angular: 8.0.0-beta.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@angular/cli                      7.1.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

</code></pre>

**Anything else relevant?**

**Comment by brandonroberts** [comment]
cc: @IgorMinar @alxhub @kara

**Comment by wKoza** [comment]
@brandonroberts , does your problem not be related to [this](https://github.com/angular/angular/pull/28542/files#diff-a99bf5f134ec27231d944f3f9cf41dc9L40) ?

**Comment by JoostK** [comment]
This is duplicated by #31108 which already has a bit more info, @brandonroberts do you agree we can close this?

**Comment by brandonroberts** [comment]
Sure
