### ISSUE TITLE
ERROR TypeError: "jit_nodeValue_8(...) is not a function"

### ISSUE THREAD

**Issue by altreze** [angular/angular#28632]
# 🐞 bug report

### Affected Package

 I am using angular 7. Once clicking to call logout() on anchor tag, please check the snippet code below.

I do receive an exception on the browser :
`ERROR TypeError: "jit_nodeValue_8(...) is not a function"`

In fact there is some confusion between `#logout` on ng-template tag and the method appended to click within anchor tag.

In case, I change the method name to whatever other name the click event works and triggers the method.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
```html
          <div class="dropdown-divider"></div>
          <a *ngIf="test_var; else logout" class="dropdown-item" href="#">Settings</a>
          <ng-template #logout>
            <a class="dropdown-item" href="#">Something else here</a>
          </ng-template>
        </div>
      </li>

    </ul>

    <ul class="navbar-nav">
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" (click)="logout()">Logout</a>
          </div>
      </li>
    </ul>
```

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>
<code>
    "@angular/animations": "~7.1.0",
    "@angular/common": "~7.1.0",
    "@angular/compiler": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/forms": "~7.1.0",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/router": "~7.1.0",
    "@auth0/angular-jwt": "^2.1.0",
    "@ngrx/effects": "^7.2.0",
    "@ngrx/entity": "^7.0.0",
    "@ngrx/store": "^7.0.0",
    "@ngrx/store-devtools": "^7.0.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "bootstrap": "^4.2.1",
    "core-js": "^2.5.4",
    "jquery": "^3.3.1",
    "ngx-bootstrap": "^3.2.0",
    "rxjs": "^6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
</code>
</pre>

**Anything else relevant?**

**Comment by alexzuza** [comment]
Your handler name(`logout()`) is conflicting with your template reference variable(`#logout`).

```
 <ng-template #logout>
   <a class="dropdown-item" href="#">Something else here</a>
</ng-template>

 <a class="dropdown-item" (click)="logout()">Logout</a>
```

Consider another name for your `ng-template` and you will be able to fix this issue

**Comment by pkozlowski-opensource** [comment]
Thnx @alexzuza for investigating it - your findings are spot on! What is going on here is a case of local vars shadowing and I wonder if we could detect it in a compiler (might be tricky in case of nested templates and components inheritance, but still worth trying).

**Comment by altreze** [comment]
Many thanks for the swift response. Indeed, it could be interesting having the error thrown at compilation time, The compilation passes with no error.

Even at runtime, the exception throw does provide any tip what is happening. The message does not explain what is the issue.

It was after couple of tries that I could see that reference interferes with the handler, which in all cases should not be the case.
