### ISSUE TITLE
关于angular打包后生成的文件的一个小问题

### ISSUE THREAD

**Issue by lijiadashaoye** [angular/angular#28639]
中文：angular打包后index.html里的<script>标签有必要添加defer或async吗？或者在打包时可不可以设置一下，让打包好的文件自动添加好；
English:Is it necessary to add 'defer' or 'async' to the <script> tag in 'index.html' after angular packaging? Or can you set it when you package it, and let the packaged file be added automatically?

**Comment by destus90** [comment]
@lijiadashaoye you should explain things in globally accepted language (English)

**Comment by codymikol** [comment]
"Is it necessary to add defer or async to the <script> tag in index.html after angular packaging? Or can you set it when you package it, and let the packaged file be added automatically?"

**Comment by benlesh** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
