### ISSUE TITLE
Animations: transition between states broken when combined with query

### ISSUE THREAD

**Issue by dirkluijk** [angular/angular#28654]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/animations

### Is this a regression?
Not sure.

### Description

```typescript
state('state1', style({ /*...*/ })),
state('state2', style({ /*...*/ })),
transition('state1 <=> state2', [
  animate(500),
  query(/* ... */)
])
```
Does not work as expected. It does not transition to the states.

However, when swapping the `animate()` and `query()`, it does work:

```typescript
state('state1', style({ /*...*/ })),
state('state2', style({ /*...*/ })),
transition('state1 <=> state2', [
  query(/* ... */),
  animate(500)
])
```

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/animation-bug

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular 7</code></pre>

**Anything else relevant?**
See also: https://stackoverflow.com/questions/51726044/angular-transition-between-states-isnt-animated-correctly-if-animate-is-place/54631683#54631683

**Comment by shadyabouelmakarem** [comment]
I'm facing the same issue and used the same mentioned workaround, any updates on any plan to fix this?

**Comment by dario-piotrowicz** [comment]
All working as expected with the latest version of the animations package :smile: :tada: 

https://stackblitz.com/edit/angular-ivy-yx8q4g?file=src%2Fapp%2Fapp.component.html
