### ISSUE TITLE
Alpha 29: Bundle not available through https://code.angularjs.org/

### ISSUE THREAD

**Issue by jomeier** [angular/angular#2865]
The title says everything :-) Thanks for uploading the bundle.

**Comment by ericmdantas** [comment]
I too use the bundle from the cdn, it's by far the easiest and fastest way to get stuff done.

**Comment by jpsfs** [comment]
Hi!

If you don't mind borrowing this thread, any news on typing for alpha 29?
Not only, but mostly because of the appInject change, updated typings will smooth the alpha 28 > 29 transition.

https://github.com/borisyankov/DefinitelyTyped/tree/master/angular2

**Comment by ericmdantas** [comment]
Still not available :cry:

**Comment by Sabartius** [comment]
Alpha 30 is also not available :(

**Comment by ericmdantas** [comment]
[.30 bundle is available](https://code.angularjs.org/2.0.0-alpha.30/)

**Comment by naomiblack** [comment]
Yes, sorry -- we have been changing our release process and we dropped alpha-29. Closing this issue as the problem is fixed for milestones 30 onward
