### ISSUE TITLE
app run on  local area network - proxy backend - connection refused

### ISSUE THREAD

**Issue by gxg10** [angular/angular#28665]
I have an app that will be run for the moment only on local area pc's. 
I have an angular app using a spring boot backend that will run on one pc and other pc's in the network will access the angular app. I followed this to set up a proxy to my backend:
https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/proxy.md
I run ng serve --host 0.0.0.0, i can access the angular app on other pc's, all the requests are getting ok status but a get request ( download controller of files ) is getting connection refused.
I also created a stackoverflow question.
https://stackoverflow.com/questions/54651553/connection-refused-when-downloading-file-on-a-local-area-pc-using-proxy-to-backe
What can i do to remove the errors ?

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
