### ISSUE TITLE
Does RxJs broke @angular/flex-layout?

### ISSUE THREAD

**Issue by kaankoken** [angular/angular#28666]
I found an old angular project, and I run it with this specs

**Before Update**
`"dependencies": {
    "@angular/animations": "6.0.0",
    "@angular/cdk": "6.0.1",
    "@angular/common": "6.0.0",
    "@angular/compiler": "6.0.0",
    "@angular/core": "6.0.0",
    "@angular/flex-layout": "2.0.0-beta.10",
    "@angular/forms": "6.0.0",
    "@angular/http": "6.0.0",
    "@angular/material": "6.0.1",
    "@angular/platform-browser": "6.0.0",
    "@angular/platform-browser-dynamic": "6.0.0",
    "@angular/router": "6.0.0",
    "@ngu/carousel": "1.4.2",
    "classlist.js": "1.1.20150312",
    "core-js": "2.4.1",
    "date-fns": "1.28.5",
    "hammerjs": "2.0.8",
    "ng2-validation": "4.2.0",
    "perfect-scrollbar": "1.3.0",
    "rxjs": "6.1.0",
    "rxjs-compat": "6.1.0",
    "web-animations-js": "2.3.1",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.0",
    "@angular-devkit/core": "0.6.0",
    "@angular/cli": "6.0.0",
    "@angular/compiler-cli": "6.0.0",
    "@types/hopscotch": "0.2.28",
    "@types/jasmine": "2.5.38",
    "@types/node": "6.0.60",
    "codelyzer": "~2.0.0",
    "enhanced-resolve": "3.3.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "~0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "~0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "2.0.0",
    "tslint": "4.5.0",
    "typescript": "2.7.2"
  }`

**After update**

`"dependencies": {
    "@angular/animations": "~7.1.0",
    "@angular/cdk": "^7.3.0",
    "@angular/common": "~7.1.0",
    "@angular/compiler": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/flex-layout": "^7.0.0-beta.23",
    "@angular/forms": "~7.1.0",
    "@angular/material": "^7.3.0",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/router": "~7.1.0",
    "@ngu/carousel": "1.4.2",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "perfect-scrollbar": "^1.4.0",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.1.0",
    "tslib": "^1.9.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.1",
    "@angular/cli": "~7.1.4",
    "@angular/compiler-cli": "~7.1.0",
    "@angular/language-service": "~7.1.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }`

It was working fine until I updated all the packages. At first `header` of the project was working fine. After update, when I toggle the `header` with `toggle button`, the header is not showing the logo, and make a weird whitespace. (Logo should be on the same line with toggle button)

**Before toggle**
![image](https://user-images.githubusercontent.com/28218396/52674090-37eeb200-2f2b-11e9-92af-8c35690efcd8.png)

**After toggle**
![image](https://user-images.githubusercontent.com/28218396/52674048-1a214d00-2f2b-11e9-8ef8-219b69cde2d0.png)

Is there any fix for that?

**Comment by CaerusKaru** [comment]
Please file this issue under https://github.com/angular/flex-layout
