### ISSUE TITLE
Function calls are not supported in decorators but...

### ISSUE THREAD

**Issue by Leijiawei** [angular/angular#28673]
when I package my application with SxfedModule, I will have the problem.

![qq 20190213154911](https://user-images.githubusercontent.com/11434308/52695368-49759f80-2fa7-11e9-87a4-9bbe4d6e8eeb.png)

![image](https://user-images.githubusercontent.com/11434308/52695451-893c8700-2fa7-11e9-8466-0442544f61d5.png)

with ng build --prod

please help me, thank you very much.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
