### ISSUE TITLE
Angular 自带的数字管道 number 传输给管道的不是一个数字或者空白时

### ISSUE THREAD

**Issue by 1091313059** [angular/angular#28678]
Angular 自带的数字管道 number ,
当传给管道的参数不是一个数字或者空白时,会报错:is not a number' for pipe 'e'

但有时候参数确实是一个空白,
希望能给该管道做一定得修改:
如果传给管道的参数不是一个数值时,直接返回本身,或者返回空白,而不是报错.最好能自定义不是数值时的返回值;

每个内置的管道都可以多增加一个可选的参数,该参数用来显示管道发生错误时的默认值.

感谢 Angular!

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
