### ISSUE TITLE
Local Karma tests don't run any more

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#28681]
Seems like local Karma-based tests are not working any more - a command like `yarn bazel test //packages/core/test:test_web_chromium-local --define=compile=aot ` results in:

```
Karma version: 4.0.0
13 02 2019 09:56:57.161:INFO [karma-server]: Karma v4.0.0 server started at http://0.0.0.0:9876/
13 02 2019 09:56:57.165:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
13 02 2019 09:56:57.179:INFO [launcher]: Starting browser ChromeHeadless
13 02 2019 09:57:57.181:WARN [launcher]: ChromeHeadless have not captured in 60000 ms, killing.
13 02 2019 09:57:57.209:INFO [launcher]: Trying to start ChromeHeadless again (1/2).
13 02 2019 09:58:57.211:WARN [launcher]: ChromeHeadless have not captured in 60000 ms, killing.
13 02 2019 09:58:57.248:INFO [launcher]: Trying to start ChromeHeadless again (2/2).
13 02 2019 09:59:57.249:WARN [launcher]: ChromeHeadless have not captured in 60000 ms, killing.
13 02 2019 09:59:57.274:ERROR [launcher]: ChromeHeadless failed 2 times (timeout). Giving up.
```

It was reported by several developers on OSX. Definitively a recent regression, was working just fine last week.

**Comment by kyliau** [comment]
This only affects Mac OS. @gregmagolan has a PR to fix this (https://github.com/bazelbuild/rules_typescript/pull/418) but the proper fix is to wait for the rules_webtesting team to add some .bzl files that we can use with working browser versions.

**Comment by gregmagolan** [comment]
In the meantime we could pin the browser versions in angular/angular as we do in the main rules_typescript WORKSPACE: https://github.com/bazelbuild/rules_typescript/blob/master/WORKSPACE#L97. Instead of calling `rules_webtesting` `browser_repositories`, we pin the browsers manually with ```platform_http_file(
    name = "org_chromium_chromium",
...```

https://github.com/bazelbuild/rules_typescript/pull/418 just also adds the pinning to the nested workspaces.

**Comment by pkozlowski-opensource** [comment]
Seems like it was worked-around in #28698 and we've got #28724 to track final solution. Closing this one here.
