### ISSUE TITLE
Allow add additional file style to component in template

### ISSUE THREAD

**Issue by nikitalarionov** [angular/angular#28684]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
 Everyone knows about css methodology 'bem'. I try to use this, but i have problem when i need to override component styles. For example i have base button.scss and also i want to have extended.button.scss. To solve my problem i need use component decorator or inheritance and change styleUrls.

### Describe the solution you'd like
 But i want to have something that i can put in template [addStyleUrls]=["extended.button.scss"] to override base.scss and add additional styles logic. It allows us to make level scss heirarchy which helps split base geometry styles from specific design styles at project level or at many project levels.

### Describe alternatives you've considered
 Other alternative solutions depends on build systems, where we can @import one css, and another import second file in endpoint css file.

**Comment by Airblader** [comment]
I'm unclear what you're asking for here. `styleUrls` already accepts an array of files, and to actually extend a style file you can use `@import` as you mentioned. What's missing?

**Comment by alxhub** [comment]
I'm going to close this actually, because @Airblader is right - you can already specify both multiple `styleUrls` as well as `@import` within a CSS file. Additionally `<link rel="stylesheet">` is supported within templates (almost nobody knows this).
