### ISSUE TITLE
Forms. updateOn: 'blur' leads to incorrect value being submitted by enter

### ISSUE THREAD

**Issue by WiseBird** [angular/angular#28686]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

 It worked the same at least in angular 6.

### Description

Setting `[ngModelOptions]="{updateOn: 'blur'}"` to the from control results in incorrect value submitted by enter.

Look into console:
![peek 2019-02-13 16-05](https://user-images.githubusercontent.com/1745378/52713787-49769f00-2fa9-11e9-8610-1c947920f603.gif)

## 🔬 Minimal Reproduction

 

[https://stackblitz.com/edit/angular-submit-on-blur?](https://stackblitz.com/edit/angular-submit-on-blur)

## 🌍  Your Environment

**Angular Version:**
<pre><code>7.2.4
</code></pre>

**Anything else relevant?**

This problem is mentioned in improvement #26683, in my opinion this is clearly not a feature but a bug that makes `{updateOn: 'blur'}` almost unusable.

**Comment by kara** [comment]
As you mention, there is an existing issue to track this behavior here: https://github.com/angular/angular/issues/26683. I think one issue is sufficient to track progress. 

If you want to ensure your use case is logged specifically, I'd comment on the existing issue. Closing this as a dupe.

**Comment by rshchpkn** [comment]
@kara I think existing issue [#26683](https://github.com/angular/angular/issues/26683) don’t fully describe the bug. In my opinion `updateOn: blur` should be fixed regardless of [#26683](https://github.com/angular/angular/issues/26683) result.
Thank you in advance and I’m open for a discussion.
