### ISSUE TITLE
router: parseUrl breaks when using ../ relative paths

### ISSUE THREAD

**Issue by dirkluijk** [angular/angular#28682]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?
Not sure.

### Description
In a `CanActivate` guard, you sometimes want to redirect to a relative URL. The only way we can do that, is by using:

```typescript
return this.router.parseUrl(`${state.url}/../../other/route`);
```

However, `parseUrl()` does not seem to recognize the `../..` part. The location is correctly updated, so when refreshing the page, the new route gets actually activated.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/parse-url-bug
```
Cannot match any routes. URL Segment: 'a/1/next/../../2'
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular 7.1.4
</code></pre>

**Comment by jasonaden** [comment]
I think what you want is to turn on the `corrected` option for `relativeLinkResolution`. This was a breaking change and we haven't been able to enable it by default, but you should turn that on and it should fix your problem.

Here is the doc:

https://angular.io/api/router/ExtraOptions

If you continue to have a problem, please create a new issue (closing this one) as I don't get notifications on closed issues.
