### ISSUE TITLE
Yarn is unable to fetch packages sometimes with "503 Service Unavailable" error

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#28702]
Example CI job (the `build-ivy-npm-packages` one) that failed because of that:

https://circleci.com/gh/angular/angular/202664?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Error message:
```
$ node tools/yarn/check-yarn.js
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error https://registry.yarnpkg.com/@bazel/bazel-win32_x64/-/bazel-win32_x64-0.22.0.tgz: Request failed "503 Service Unavailable"
```

The error disappeared after CircleCI job restart. Creating a ticket in case the problem happens again for other PRs.

**Comment by gkalpak** [comment]
We can't really do much about that error specifically, but we could try switching to the npm registry, which might be more robust (according to anecdotal evidence).

**Comment by AndrewKushnir** [comment]
@gkalpak thanks for the reply, understood. I'd keep this ticket around for a few days to see if we have more issues like that and close it if we don't. I believe the issue might be caused by the temporary unavailability of the service and if so - no actions are required.
