### ISSUE TITLE
Angular Route intercepting Service Worker file request. 

### ISSUE THREAD

**Issue by cozzbie** [angular/angular#28701]
# 🐞 bug report

### Affected Package
@angular/service-worker

### Is this a regression?
No

### Description
Trying to load the service worker file using the base-href reference returns the wildcard component defined in the routes.

## routes
`
[
...
{ path: '**', component: PageNotFoundComponent }
]
`

So assuming the service worker file loads from `domain/basehref/ngsw-worker.js`, the registration fails because the rendered `PageNotFoundComponent` is what is being returned by the route which is interrupting requests/fetches for the ngsw-worker.js file

## 🔥 Exception or Error
<pre><code>

ERROR Error: Uncaught (in promise): SecurityError: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html').

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.3
@angular-devkit/build-angular     0.7.3
@angular-devkit/build-optimizer   0.7.3
@angular-devkit/build-webpack     0.7.3
@angular-devkit/core              0.7.3
@angular-devkit/schematics        0.6.8
@angular/cli                      6.1.3
@angular/pwa                      0.6.8
@ngtools/webpack                  6.1.3
@schematics/angular               0.6.8
@schematics/update                0.7.3
rxjs                              5.5.11
typescript                        2.5.3
webpack                           4.9.2

</code></pre>

**Comment by gkalpak** [comment]
The router cannot intercept such requests (afaict). There must be something else (maybe a server-side config issue?).
In any case, there is nothing we can do without a reproduction. I am going to close this as non-actionable, but happy to reopen/investigate if you can provide the necessry info (i.e. a reproduction :grin:).

**Comment by cozzbie** [comment]
Yeah, you are right @gkalpak. Thanks

**Comment by yuricamara** [comment]
Same problem here! Did you solve it, @cozzbie ?
