### ISSUE TITLE
HttpParams fromString first param not updating

### ISSUE THREAD

**Issue by mcm-ham** [angular/angular#28722]
# 🐞 bug report

### Affected Package
@angular/common/http

### Description

The delete and set methods do not work as expected for the first param when fromString starts with a `?` i.e.

```
new HttpParams({ fromString: '?test=string' }).set('test', 'value').toString() // ?test=string&test=value instead of ?test=value
```
It's useful to support `?` because `window.location.search` starts with that character.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-zztqky?file=src%2Fapp%2Fapp.component.ts

## 🌍  Your Environment

**Angular Version:**
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.1
@angular-devkit/build-angular     0.13.1
@angular-devkit/build-optimizer   0.13.1
@angular-devkit/build-webpack     0.13.1
@angular-devkit/core              7.3.1
@angular-devkit/schematics        7.3.1
@angular/cli                      7.3.1
@ngtools/webpack                  7.3.1
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

**Comment by trotyl** [comment]
Relates to https://github.com/angular/angular/issues/14531

---

`?` should be indeed be stripped per spec behavior:

![image](https://user-images.githubusercontent.com/6059170/52765124-ca8f6e00-305d-11e9-9116-d6a8e5187b1c.png)
![image](https://user-images.githubusercontent.com/6059170/52765157-f4e12b80-305d-11e9-87c6-f132b3be0ec7.png)

**Comment by alxhub** [comment]
This definitely seems like something we could easily support, and a great opportunity for a community PR :)
