### ISSUE TITLE
Bazel schematics: Karma test broken on Mac OS

### ISSUE THREAD

**Issue by kyliau** [angular/angular#28724]
Karma test is currently broken due to the latest Chrome browser in rules_webtesting.
While waiting for upstream changes, users can pin the browser versions as done here:
https://github.com/angular/angular/pull/28698
https://github.com/bazelbuild/rules_typescript/pull/418

**Comment by weibon** [comment]
My bazel karma project @build_bazel_rules_karma has no package.bzl file
