### ISSUE TITLE
ngOnChanges split  into two lifecycle functions

### ISSUE THREAD

**Issue by goldiwill** [angular/angular#28728]
Can you split the ngOnChanges lifecycle function into two lifecycle functions? Because in the application process, you only need to call the ngOnChanges lifecycle function after the ngOnInit lifecycle call. In general, this method is called twice.

**Comment by pkozlowski-opensource** [comment]
I'm sorry but it is not very clear to my what you are asking for. Why do you want to have this lifecycle hook split? Could you please provide a minimal stackblitz that shows "In general, this method is called twice." and practical, negative consequences of it?

**Comment by jinbeomhong** [comment]
@pkozlowski-opensource Maybe, "this method is called twice" means "Called before `ngOnInit()` and whenever one or more data-bound input properties change."

@goldiwill What about to split the logic in `ngOnChanges` using `if`/`else`? The method has a `SimpleChanges` parameter. The `SimpleChanges` is `SimpleChange`'s array simply. The `SimpleChange` has a method `isFirstChange(): boolean` as well as `firstChange: boolean` property. You can use them.

https://angular.io/api/core/SimpleChange

**Comment by pkozlowski-opensource** [comment]
Going to close this one for now as we haven't heard back from the issue author.
