### ISSUE TITLE
Provide Config to internal Modules within my angular library

### ISSUE THREAD

**Issue by codekeyz** [angular/angular#28725]
I am wondering how i can provide Configs to other imported modules inside my custom angular libary.

```typescript

export interface Config {
  isDevMode: boolean;
}

@NgModule({
  exports: [],
  imports: [
    HttpClientModule,
    JwtModule.forRoot({
      config: {
        tokenGetter: ''           // I want to provide these config dynamically through the BankModule forRoot method,
        skipWhenExpired: true,
        whitelistedDomains: [
          // I want to provide these config dynamically through the BankModule forRoot method
        ],
        blacklistedRoutes: [
         // I want to provide these config dynamically through the BankModule forRoot method
        ]
      }
    })
  ]
})
export class BankModule {
  static forRoot(config: Config): ModuleWithProviders {
    return {
      ngModule: BankModule,
      providers: [
        BankService,
        BankAuthService,
        {
          provide: 'config',
          useValue: config
        }
      ]
    };
  }
}
```

I want to provide configuration for JwtModule through the static forRoot in my BankModule class. Any help ?

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
