### ISSUE TITLE
Description tooltip appearing multiple times on VS code

### ISSUE THREAD

**Issue by ElianCordoba** [angular/angular#28734]
# 🐞 bug report

### Description
As seen in the image the description of the property appear multiple times

## 🔬 Minimal Reproduction
In the providers array open brackets and type `provide` or `multi`. For some reason `useClass` seems to work

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 7.3.1
Node: 10.14.2
OS: darwin x64
Angular: 7.2.4

**Vscode: 1.31.1**
![screen shot 2019-02-14 at 16 44 20](https://user-images.githubusercontent.com/34920585/52803064-23b8cb00-3079-11e9-88cc-611ef67151c0.png)
![screen shot 2019-02-14 at 16 50 09](https://user-images.githubusercontent.com/34920585/52803065-23b8cb00-3079-11e9-9506-18eb5cdf4963.png)

**Comment by kyliau** [comment]
This should not be an issue anymore, now that the v9 extension is released. Please open a new issue if this is not the case. The latest version could be downloaded from https://marketplace.visualstudio.com/items?itemName=Angular.ng-template
