### ISSUE TITLE
Tour of Heroes Messages critique

### ISSUE THREAD

**Issue by EvanCarroll** [angular/angular#28739]
For TOH-4 on messages I have a few points of advice.

1. It's confusing when `messages` is an array (and named plural -- with an 's') if it can only ever show one message. I would have expected from the demo to see **more than one message.**

* Click a hero
* Click another hero (more fetching)
* Still One message?

2. The method `clear` is confusing when it sets messages to a `[]` and **never displays a new event in the object on subsequent (post-clear) fetches.**

* Click https://stackblitz.com/angular/bvprepbxlrv
* Click a hero
* Click clear to wipe messages
* Click a new hero (still nothing)

**Comment by mlc-mlapis** [comment]
@EvanCarroll ...

1) Because of ` <div *ngFor='let message of messageService.messages'> {{message}} </div>`
2) There is a message ...

![image](https://user-images.githubusercontent.com/5693835/52811560-b5363600-3095-11e9-8ca3-42d551be166b.png)

**Comment by EvanCarroll** [comment]
I'm not sure how either of those answer the contention. There being one message is weird becuase you're calling the class messageS and storing it it in an array. I would expect there to be a ceiling of >1 message. 

Click "clear" and then try to get another message.

**Comment by ajitsinghkaler** [comment]
@gkalpak Can I take this.

**Comment by gkalpak** [comment]
Sure, @ajitsinghkaler (I guess) :tada:
BTW, for docs content (not docs infrastructure/tooling) changes, you would be better off coordinating with someone from the docs team (e.g. @kapunahelewong); I am not really involved with docs content :grin:

**Comment by ajitsinghkaler** [comment]
@kapunahelewong can you guide me through this

**Comment by kapunahelewong** [comment]
Hi @ajitsinghkaler! @EvanCarroll definitely has a good point that this could be clarified. If we refactor the example, we will also need to edit the doc that describes that part. What do you have in mind for the messages? Maybe you could create a stackblitz with the improvements - that could be a quick way to try out ideas. What do you think?

**Comment by ajitsinghkaler** [comment]
@kapunahelewong Yes, I'm creating a new example when I'm done I'll ping you

**Comment by ajitsinghkaler** [comment]
@kapunahelewong I've added the new example here https://angular-ubavw5.stackblitz.io. Please have a look and review.

What I've done is add a new message when user selects a new hero like HeroService: Selected hero id=18

What do you think will it be enough

**Comment by ajitsinghkaler** [comment]
@kapunahelewong can you please have a look at this.

**Comment by kapunahelewong** [comment]
Yes, @ajitsinghkaler, this is a great improvement! Love the example! Please do tag me when you're ready. Thank you!

**Comment by ajitsinghkaler** [comment]
@kapunahelewong will ping you when completed
