### ISSUE TITLE
Function calls are not supported in decorators but...

### ISSUE THREAD

**Issue by Leijiawei** [angular/angular#28747]
# 📚 Function calls are not supported in decorators but...

### Description

 I wrote an angular library SxfedModule and use it in a different angular applications. when I packaged my application with the library, evenything works fine without --prod.

### Reproduction Steps
Use this library in a new angular application which is generated by the angular cli by calling SxfedModule .forRoot() in the app.module.ts.

NgModule of the library:
<pre><code>
import { NgModule, ModuleWithProviders } from '@angular/core';  
import { SxfedformModule } from './component/sxfedform/sxfedform.module';
export const ElChildModules: any = {
  SxfedformModule,
}
export const ELMODULES_GROUP: any[] = [
  SxfedformModule,
]
@NgModule({
  imports: [
    SxfedformModule.forRoot(),
  ],
  exports: ELMODULES_GROUP,
})
class SxfedModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: SxfedModule,
      providers: [],
    };
  }
}
export {
  SxfedModule,
};
</code></pre>

NgModule of the application:
<pre><code>
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import { ElModule } from 'element-angular';
import { SxfedModule } from 'sxfed-angular-ui';
import { RouterModule } from '@angular/router';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { appRoutes } from './app.routes';
@NgModule({
  declarations: [
    AppComponent,
    LoginComponent,
  ],
  imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    BrowserAnimationsModule,
    ElModule.forRoot(),
    SxfedModule.forRoot(),
    RouterModule,
    RouterModule.forRoot(appRoutes),
  ],
  providers: [
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
</code></pre>

Try ng build --prod

## 📷Screenshot

![image](https://user-images.githubusercontent.com/11434308/52829529-231b4580-3108-11e9-9b46-bc17fa979271.png)

## 🌍  Your Environment
Angular CLI: 7.2.3
Node: 8.11.1
OS: win32 x64
Angular: 7.2.2

Thank you for reading my problem.
Please help me, thank you.

**Comment by alexzuza** [comment]
Can you setup a minimal repro please?
