### ISSUE TITLE
Invalid metadata for flat module indices with static class members

### ISSUE THREAD

**Issue by devversion** [angular/angular#28741]
# 🐞 bug report

### Affected Package

@angular/compiler-cli

### Is this a regression?

Nope,

## 🔬 Minimal Reproduction

https://github.com/devversion/static-class-properties-invalid-metadata

## 🔥 Exception or Error

Summary output with invalid metadata files. This bug is also happening for `@angular/core` where we generated an invalid `core.metadata.json` file and ship it to NPM.

e.g. see: https://unpkg.com/@angular/core@7.2.2/core.metadata.json

The problem is that the metadata references static symbols using relative paths which are no longer valid due to the metadata being bundled at the package root next to the flat module index file.

e.g. search for `../../di` which should be something like `./src/di/index`.

This is happening because the `bunder` in the `@angular/compiler-cli` does not rewrite relative URLs within static class members into the corresponding package-relative paths. This seems to be an **oversight** in the metadata bundler that now causes issues with Ivy where **static class members** can be used to declare injectables.

For example:
```ts
export class KeyValueDiffers {
  /** @nocollapse */
  static ngInjectableDef = defineInjectable({
    providedIn: 'root',
    factory: () => new KeyValueDiffers([new DefaultKeyValueDifferFactory()])
  });
``` 

---> The resulting summary file from that corrupt metadata file looks like that:

```js
"metadata": {
  "__symbolic": "class",
  "members": {
    "__ctor__": ["..."],
    "find": ["..."]
  },
  "statics": {
    "ngInjectableDef": {
      "__symbolic": "call",
      "expression": {
        "__symbolic": "error",
        "message": "Could not resolve ../../di/defs relative to [object Object].",
        "fileName": "@angular\\core\\core.ts"
      },
      "arguments": ["..."]
    },
```

Notice how it couldn't resolve `../../di/defs`. This is because this path is not valid when considered relative to the `@angular/core/core.d.ts` file. 

## 🌍  Your Environment

**Angular Version:**
<pre><code>v8.0.0-beta.3</code></pre>

**Anything else relevant?**

This is fixed with Ivy/`ngtsc`, but it can currently cause unexpected behavior when the AOT compiler tries to resolve the references from incorrect module paths. e.g. it resolves `../../di` to another node module that is called `di`. Causing an exception like:

```
: Error: Could not resolve di/lib/index from
 /bazel_integration_test/external/npm/node_modules/@angular/core/core.d.ts
```

This can only happen if the `di` node module is part of the TypeScript compilation though. So the severity is extremely low, but it seems hard to work around this because TypeScript naturally uses the resolved module (and there is no easy for us to exclude that).

**Comment by JoostK** [comment]
Please note that this is not Ivy specific: `static ngInjectableDef` is also emitted by ngc (View Engine) for tree-schakeable providers since v6.

**Comment by devversion** [comment]
@JoostK Yeah it's not Ivy specific, but will be fixed by Ivy. 

Also issue is only about manually declared static class members which aren't properly handled in the generated `metadata` with flat module indices.
