### ISSUE TITLE
Add submit and success events to reactive forms

### ISSUE THREAD

**Issue by BenRacicot** [angular/angular#28743]
# 🚀 feature request

### Relevant Package
@angular/forms

### Description
Accessing the `submit` event in a form is not available to child components without passing the event itself. 

I have researched this for the better part of 2 days in regards to a validation and submission messaging component I'm [working on](https://stackblitz.com/edit/validator-component). I found that we must pass the `$event` to child components in order to react to a submit event despite having already sent the FormGroup.
```
<form (ngSubmit)="onSubmit($event)"...
    <app-validator [formGroup]="form" [parentEvent]="evt"></app-validator>
```

### Describe the solution you'd like
FormGroup's `statusChanges` could include a `submitted` flag.

I do realize that `submitted` does not denote success. However, this seems to be the same logic where some validators do not trigger an `INVALID` FormGroup status.

To be able to tie our endpoint/observable response to the form to create a `submitted:success` flag as well sounds helpful. But that may out of scope to my request.

1. `submitted:true` be added to FormGroup's `statusChanges` when the form has been submitted by the user and ngSubmit has triggered a `submit` event.
2. `submitted:invalid` could denote that a form submission has been attempted while a form control(s) was invalid.
3. `submitted:finished` when the application has returned from the server and the application updates the form's statusChanges that a successful round trip has occurred.
Referencing RESTful best practice perhaps even going as far as error codes or `submitted: GET/POST/PUT/DELETE` or even our own custom codes? 

Form usage after _finished_ could typically trigger setting the form to pristine and `submitted:null` to start the UX process over.

I wrote more on my proposed solution on [Medium](https://medium.com/@BenRacicot/success-handling-is-everyones-responsibility-40d844e6cc42). If I'm off I'd like to be corrected and shown the best way. Thank you.

### Describe alternatives you've considered
- ControlValueAccessor does not seem to have access to the form events
- FormControl and FormGroup have `errors` and `statusChanges` but do not include a "submitted" event
- There is no safe way to "ViewParent" from a component which is what others have mentioned on StackOverflow
- Event emitting adds overhead to components where the parent must work with the child, sometimes defeating the purpose of reusable components. (my case) Lets not forget that passing the event is a "[dubious practice](https://angular.io/guide/user-input#passing-event-is-a-dubious-practice)".
- Began at [StackOverflow](https://stackoverflow.com/q/54678936/1440240). Question has no answers

**Comment by kara** [comment]
Appreciate the detailed write-up!  Thanks for taking the time to look into this.  It's worth noting that we do have `submitted` property on `FormGroupDirective` itself, just not on `FormGroup`. But in many cases, we found that this isn't enough, so we have an existing issue to design a solution here: https://github.com/angular/angular/issues/21823.

Seems like we should track these related problems in one place, so I'm linking this to the existing issue and closing as a dupe.
