### ISSUE TITLE
aio: annoying separator in ObjectType in the API section

### ISSUE THREAD

**Issue by wKoza** [angular/angular#28751]
# 📚 Docs or angular.io bug report

### Description

In the API section, when we have an object inline as parameter, the separator is a `;` instead of ','.

For instance, [here](https://angular.io/api/common/http/HttpClientXsrfModule#withoptions)

We have this:
```
static withOptions(options: { cookieName?: string; headerName?: string; } = {}): ModuleWithProviders<HttpClientXsrfModule>
```
instead of 
```
static withOptions(options: { cookieName?: string, headerName?: string; } = {}): ModuleWithProviders<HttpClientXsrfModule>
```

I'm not sure it's a problem with the tooling of aio, it's maybe a problem with dgeni.

cc @petebacondarwin

**Comment by petebacondarwin** [comment]
Looking into it...

**Comment by petebacondarwin** [comment]
To debug this I did the following...

Noticed that the params are rendered in an element called `<div class="overload-info">`.

Looked in:

```
aio/tools/transforms/templates/api/class.template.html
({% include "includes/class-members.html" %})
  -> aio/tools/transforms/templates/api/includes/class-members.html
     ({$ memberHelpers.renderMethodDetails(versionInfo, doc.methods, 'instance-methods', 'instance-method', 'Methods') $})
    -> aio/tools/transforms/templates/api/lib/membersHelpers.html
       (renderMethodDetails -> renderMethodDetail -> renderOverloadInfo -> renderMemberSyntax)
```

Noted this call: `params.paramList(member.parameters, truncateLines)`.
Noted that `member` originally came from `doc.methods`.

Searched `aio/tools/transforms/angular-api-package` for `methods`.

Found that `processClassLikeMembers` processor in `aio/tools/transforms/angular-api-package/processors/processClassLikeMembers.js` creates this property from `doc.members`.

Searched `aio/tools/transforms/angular-api-package` for `members`. No obvious hits so searched inside `node_module/dgeni-packages/typescript/src` instead.

Now we are inside TypeScript code, so things get easier. Found references to `members` property in `ClassExportDoc` but then found definition of `members` in `ContainerExportDoc` (`aio/node_modules/dgeni-packages/typescript/src/api-doc-types/ContainerExportDoc.ts`).

Next looked at `MethodMemberDoc`, computes the `parameters` property being rendered via `getParameters` call and then mapping to `p.paramText`.

`paramText` is a property on `ParameterDoc` generated by calling `getParamText()`.

This method gets the parameter type from `this.type`, which is generated by a call to `this.getTypeString(this.declaration)`, which calls `this.host.typeToString(this.typeChecker, type);`

And this... finally... calls `typeToString()` on the TS `TypeChecker`. I believe that this call is what is adding the semi-colons.

We need to work out how to tell this TS helper method that the type is within a parameter list...

**Comment by wKoza** [comment]
Thanks you very much for your explain; I stopped on `processClassLikeMembers.js` and I didn't know `dgeni-packages`.

**Comment by petebacondarwin** [comment]
Yeah - I didn't expect you to. Dgebugging (dgeni-debugging) is a bit of a pain. Once you get into the land of the untyped dependency injection, and arbitrary mutatable docs, it is pretty hard to find where things come from.

**Comment by petebacondarwin** [comment]
I just found out that commas and semicolons are both equally valid separators in type literals: https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcAUAjAhgJwFyIDeWBYIAthgKY4DciAHgQM5Q4xgDmAvgJRHcgA
And in fact we often use semicolons in the framework codebase.

So I don't think is something that we will fix.
