### ISSUE TITLE
Ambiguous NgFor errors

### ISSUE THREAD

**Issue by justindujardin** [angular/angular#2875]
Sometimes I mess things up while getting used to angular2, and with NgFor the errors that are provided don't help me quickly overcome my problem.   I would hope to see more descriptive errors, so I can get things resolved and move on.

Here are a few examples:

## Missing `#` in for expression

    @View({
      template: '<ul><li *ng-for="item of person.inventory" [inner-text]="item"></li></ul>',
      directives:[NgFor]
    })
    class App { ... }

**Error**
> Can't bind to 'ngFor' since it isn't a know property of the 'template' element and there are no matching directives with a corresponding property

**Suggestion**
> NgFor expression has invalid syntax, expected form `#item of items`

http://plnkr.co/edit/YOC4KUwhWdYb3GSEs0Sd?p=preview

## NgFor is missing from directives array

    @View({
      template: '<ul><li *ng-for="#item of person.inventory" [inner-text]="item"></li></ul>'
    })
    class App { ... }

**Error**
> Can't bind to 'ngForOf' since it isn't a know property of the 'template' element and there are no matching directives with a corresponding property

**Suggestion**
> No valid directives or properties found for 'ngForOf'

http://plnkr.co/edit/nWzYZ3pGSHgwoaoDb96D?p=preview

**Comment by pkozlowski-opensource** [comment]
@justindujardin what would be your ideal error messages in each of those cases? I'm doing several improvements for error messages, but sometimes it is not obvious how to keep the framework generic / flexible and have precise error messages :-/ This is why it is important to get feedback from users - what would you like to see as a message? What would make you know instantly what is going on?

**Comment by justindujardin** [comment]
@pkozlowski-opensource That's always the hard problem isn't it?  I'm not sure they're great, but I've added suggestions to the original post.

**Comment by justindujardin** [comment]
related to https://github.com/angular/angular/issues/2014

**Comment by pkozlowski-opensource** [comment]
@justindujardin thnx for the suggestion. Regarding this one:

> No valid directives or properties found for 'ngForOf'

I think that it is actually more confusing that the existing one as it drops important context info (an element on which the binding fails). We can try to rephrase things but we need to keep the info that can aid with debugging.

The 

> NgFor expression has invalid syntax, expected form #item of items

is more tricky as the error is thrown before we can have checks on the NgFor level. I need to see what we can do here, but I can't see any obvious solution for now :-/

BTW, I don't think that schema support (#2014) will help much here... How would you see it aiding with this particular situation.

**Comment by justindujardin** [comment]
@pkozlowski-opensource  Right, you could append the element:

> No valid directives or properties found for 'ngForOf' on element 'div'

Do you know the component selector?  If so you could alert the user to the component associated with the error:

> No valid directives or properties found for 'ngForOf' on element 'div' of 'my-component'

I might have misunderstood #2014, but the original post mentioned better error reporting around the invalid `NgFor` expression cases, so I imagined you could identify the "bad syntax" errors during schema validation.

given that
```html
<li *ng-for="item in items">{{item}}</li>
```   
expands to 
```html
<template [ng-for]="item" [ng-for-in]="items">
  <li>{{item}}</li>
</template>
```   
 - is `[ng-for]="item"` ever valid?  If not, you could hint about needing `var item` or `#item`
 - is `[ng-for-in]="items"` ever valid?  If not, you could hint about expecting `of` instead of `in`

I'm not sure how would report on this while maintaining a good separation of concerns.  Perhaps you could have a mapping of schema validation errors to friendly messages in a decorator?  The schema validation code could look at this meta data when encountering validation errors.

Sorry if these suggestions are impractical, I'm not familiar with the internals of angular2.

**Comment by mhevery** [comment]
@pkozlowski-opensource Are we planing on doing any more work here?

**Comment by pkozlowski-opensource** [comment]
@mhevery at this point I'm not sure what we could do to improve those err messages without compromising generality of template syntax parsing. IMO we are getting a lot of millage from detecting dangling bindings already and we've got some more issues in the pipe to detect dangling events, attributes etc. But I don't think we should do more for template syntax.

My vote goes to closing this one for now - I think we can have better productivity gains from tackling other items.

**Comment by mhevery** [comment]
@pkozlowski-opensource SGTM

**Comment by petebacondarwin** [comment]
@mhevery and @pkozlowski-opensource - just for the record, I just got this same error in my app and it was only by Googling and finding this issue that I was able to resolve it. The current error message is hugely misleading.

**Comment by jteplitz602** [comment]
@pkozlowski-opensource I also ran into this error and had to find this issue to fix it. Going to echo Pete here and say that the current error message is incredibly confusing even if someone is familiar with angular.

**Comment by HB-2012** [comment]
I would suggest updating the tutorials and manuals on the main website. I've followed the tutorial one by one and ran into this issue as well.

Not very friendly towards new users adapting to angular2.
