### ISSUE TITLE
ActivatedRoute

### ISSUE THREAD

**Issue by KiseleAndrey** [angular/angular#28761]
Hello!
I have a quastion about  ActivatedRoute.
I dont have to unsubscribe from Observable when i use  ActivatedRoute,  because Angular does it himself(The ActivatedRoute observables are among the exceptions.
The ActivatedRoute and its observables are insulated from the Router itself. The Router destroys a routed component when it is no longer needed and the injected ActivatedRoute dies with it.).

 It works when use routing, but it does't work when use *ngIf.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
