### ISSUE TITLE
Declaring an InjectionToken Key and exporting it from the AppModule causes errors.

### ISSUE THREAD

**Issue by oleersoy** [angular/angular#28766]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?

Not sure

### Description

If we create an export an `InjectionToken` in the `AppModule` the application will error.  If we move the `InjectionToken` to a separate file then the injection succeeds.

## 🔬 Minimal Reproduction
[This SO](https://stackoverflow.com/questions/54701579/injection-using-an-injectiontoken) issue has more details and stackblitz links.  Here they are again for convenience:

[Working - Separate Token File](https://stackblitz.com/edit/angular-configuration-injection2?file=src%2Fapp%2Fapp.component.ts)
[Not Working - Token declared inside AppModule](https://stackblitz.com/edit/angular-configuration-injection?file=src%2Fapp%2Fapp.module.ts)

**Comment by pkozlowski-opensource** [comment]
Aren't you creating a circular dependency in your file imports?

**Comment by oleersoy** [comment]
Indeed I see it now.  I thought perhaps the typescript runtime would have support for it, but seeing as this type of thing could get hair fast it's probably best just to avoid it.  I'll close this issue.
