### ISSUE TITLE
docs: specify default value for CLI options

### ISSUE THREAD

**Issue by jinbeomhong** [angular/angular#28779]
# 📚 Docs or angular.io bug report

### Description

Default value for CLI options need to be specified. Some options were specified and the other options weren't specified, now.

### What's the affected URL?**

- https://next.angular.io/cli/add
- ...
- https://next.angular.io/cli/xi18n

## 📷Screenshot

<img width="1042" alt="add" src="https://user-images.githubusercontent.com/32840866/52910600-2582c880-32dd-11e9-8653-ccd351c6c225.png">

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by alan-agius4** [comment]
Hi,

Those default values are or specified in this case because the default are set during runtime based on your terminal.

If you terminal is not TTY, it will be set to false, otherwise it will be set to true.
