### ISSUE TITLE
Specifying "multi" when defining injection token

### ISSUE THREAD

**Issue by alirezamirian** [angular/angular#28778]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
Some injection tokens (like `HTTP_INTERCEPTORS`) are conceptually multi-value. 
This attribute is currently specified when **providing** these injectables, by specifying `multi: true` in [provider descriptor](https://angular.io/api/core/Provider). I think it makes more sense to specify this `multi` attribute when defining injection token (or maybe also with a class decorator, when injection token is a class). 
These are the reasons I think so:
* It's meaningless to provide an injection token with `multi: true` in one place and without it in another module. An error is currently thrown in these cases.
* Services that need to use value of a multi injection token don't know if they get an array or a single value. This normalization from single or multi value to multi value could be handled by DI framework, if `multi` was specified as an attribute of injectable token instead of provider.

### Describe the solution you'd like
One alternative is to add `multi` attribute to `InjectionToken`, instead of `Provider`.

### Describe alternatives you've considered
Another solution could be to add a `multi` decorator to be used like `@Optional()`, in usage side. Angular
then can keep instances of all providers and wire **one** or **all** of them, based on that decorator.

**Comment by trotyl** [comment]
> Services that need to use value of a multi injection token don't know if they get an array or a single value.

This is already specified by the type, a single-value token would be `new InjectionToken<T>()` and a multi-value token is `new InjectionToken<T[]>()`.

For example, in [`HttpInterceptor`](https://angular.io/api/common/http/HTTP_INTERCEPTORS):

```typescript
const HTTP_INTERCEPTORS: InjectionToken<HttpInterceptor[]>;
```

And `injector.get(HTTP_INTERCEPTORS)` would results to `HttpInterceptor[]` automatically.

**Comment by alirezamirian** [comment]
> And injector.get(HTTP_INTERCEPTORS) would results to HttpInterceptor[] automatically.

Are you sure? 
What I experienced is that defining `T[]` instead of `T` in injection token generic parameter doesn't result in getting array "automatically". In fact, getting an array or a single value from injector only depends on whether it's provided with a `multi` provider or not. It doesn't depend on injection token definition.

**Comment by trotyl** [comment]
> What I experienced is that defining `T[]` instead of `T` in injection token generic parameter doesn't result in getting array "automatically".

I mean the type is only defined by `InjectionToken` itself, so by injecting `HTTP_INTERCEPTORS` you can only get a result of `HttpInterceptor[]`, that's defined by type signature. But there's no type-checking in `Provider` side, so invalid value can still be provided.
