### ISSUE TITLE
Applying query to data received from firebase databse

### ISSUE THREAD

**Issue by ratnabh** [angular/angular#28777]
I fetched my data from my firebase database but i wanna apply query to it and order it by child by applying orderByChild to it, so while using db we can apply query to it by

`return this.db.list('/categories',{
query:{
orderByChild:'name'
}
})`
but my way of retreiving data is slight different , so how do i apply query here? Below is the code

service file

```
import { Injectable } from '@angular/core';
import {AngularFirestore} from 'angularfire2/firestore';
import {  Observable } from 'rxjs';
import {AngularFireDatabase} from 'angularfire2/database';

@Injectable({
providedIn: 'root'
})
export class CategoryserviceService {

categories:Observable<any>
constructor(private afs:AngularFirestore) { 
this.categories=this.afs.collection('categories').valueChanges()
}
getcategories(){
return this.categories
}

}
```

component.ts file

```
import { Component, OnInit } from '@angular/core';
import { CategoryserviceService } from 
'src/app/sevices/categoryservice.service';

@Component({
selector: 'app-newproducts',
templateUrl: './newproducts.component.html',
styleUrls: ['./newproducts.component.scss']
})
export class NewproductsComponent implements OnInit {
categoriesfromdatabase
constructor(private ctservice:CategoryserviceService) { }

ngOnInit() {
this.ctservice.getcategories().subscribe(categories=>{
  // console.log(categories)
  this.categoriesfromdatabase=categories
  console.log(this.categoriesfromdatabase)
})
}

}
```

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
