### ISSUE TITLE
StackBlitz + useHash + replaceUrl not working

### ISSUE THREAD

**Issue by pcurrivan** [angular/angular#28782]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router.... (or maybe StackBlitz)

### Description

When rendering the page in StackBlitz's side panel, if useHash is enabled, navigating with replaceUrl enabled still pushes a new history state.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-issue-repro2-unedfj

## 🌍  Your Environment

**Seen on Angular Version 6.1.9 and 7.2.5**

**Comment by trotyl** [comment]
> navigating with replaceUrl enabled still pushes a new history state.

No, it didn't.

"pushing state" means [`history.pushState(state, url)`](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_pushState()_method), "replacing state" means [`history.replaceState(state, url)`](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_replaceState()_method).

 In both case state (and/or url) will be changed, of course. The only difference is whether or not adding a new item to the history stack, you can check `history.length` always be `1`.

**Comment by pcurrivan** [comment]
Must be a StackBlitz issue, then.
