### ISSUE TITLE
`ng-reflect-*` values truncated too much

### ISSUE THREAD

**Issue by msorens** [angular/angular#28786]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core.

### Is this a regression?

 No.

### Description

 The function `normalizeDebugBindingValue` is hard-coded to return a maximum of 30 characters...

https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/core/src/util/ng_reflect.ts#L24

... for the reason given in a comment (shown below). The choice of words there ("gets polluted") would seem to imply either visually distracting or a bit cumbersome in some cases for some users, perhaps, rather than causing any major performance hit. But that arbitrary 30-char limit is a major problem for some unit tests I would like to write. Could this value be increased (perhaps 100 chars?) or at least configurable?

Of course, one could argue that this is a feature request rather than a bug, but after spending a couple hours isolating this problem, it sure acted and smelled like a bug to me (;-)), hence my calling it a bug.
(Should think that that magic number should be a named constant, at a minimum.)

Here is the function in its entirety at the time of this writing:
```
export function normalizeDebugBindingValue(value: any): string {
  try {
    // Limit the size of the value as otherwise the DOM just gets polluted.
    return value != null ? value.toString().slice(0, 30) : value;
  } catch (e) {
    return '[ERROR] Exception while trying to serialize the value';
  }
}
```

## 🔬 Minimal Reproduction

 Not applicable--my description above provides all necessary details.

## 🔥 Exception or Error
Not applicable

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 6.1.4
Node: 8.9.4
OS: darwin x64
Angular: 6.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.4
@angular-devkit/build-angular     0.7.4
@angular-devkit/build-optimizer   0.7.4
@angular-devkit/build-webpack     0.7.4
@angular-devkit/core              0.7.4
@angular-devkit/schematics        0.7.4
@angular/cdk                      6.4.6
@angular/cli                      6.1.4
@angular/material                 6.4.6
@ngtools/webpack                  6.1.4
@schematics/angular               0.7.4
@schematics/update                0.7.4
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.9.2
</code></pre>

**Anything else relevant?**

Not applicable

**Comment by pkozlowski-opensource** [comment]
> But that arbitrary 30-char limit is a major problem for some unit tests I would like to write.

@msorens could you please elaborate on this? Are you saying that you are using `ng-reflect-*` attributes in your tests to assert on them? What kind of tests are we talking about here? Why do you need to inspect `ng-reflect-*`  in your tests?

Anything that would help us understand a scenario from the point of view would help us to decide on next steps...

**Comment by msorens** [comment]
Happy to oblige, @pkozlowski-opensource .

_This first paragraph is not strictly necessary, but it gives you a flavor..._
I have an Angular template that renders a sidebar where each entry in the sidebar is guarded by a custom component that checks the user's permissions to access the page for that entry. 
When the user attempts to enter the portion of the app where this sidebar would be rendered, there is another custom component that serves as a landing page which then routes the user to the first entry from the above sidebar for which he/she has permission to access. 

_So what is specifically relevant is this:_
I have a template that contains a series of a dozen or so instances of the custom element `<app-custom-1 [anyOf]="v1,v2,v3,v{n},...">` where the value of that `anyOf` property is a list of from 1 to 5 items and each item `v{n}` may itself be 20 or 30 characters each, so the length of the whole `anyOf` property could be 100 characters (or more).
I have another custom component that needs to duplicate that list in code and it must always match the list in the template. In order to eliminate any maintenance headaches, I have a unit test that monitors that equivalence:
```
for (let i = 0; i < LandingComponent.scanList.length; i++) {
        const elem = <HTMLElement>elements[i];
        checkPerms(
          elem.getAttribute('ng-reflect-any-of'), LandingComponent.scanList[i].anyOfCheck);
      }
```
The difficulty is that the value of `anyOf` (i.e. `ng-reflect-any-of`) often exceeds 30 characters.

**Comment by pkozlowski-opensource** [comment]
Thnx @msorens for the detailed write-up. Marking it as a feature request to configure size limit for `ng-reflect-*`

**Comment by BillSheldon-HunterIndustries** [comment]
Seeing this same issue when attempting to karma/jasmine test the contents of tooltips.  We have tool tips that contain 30+ characters that includes calculated data.  Everything runs fine, but when we access ng-reflect-message, the tests are unable to determine if the tool tip is populated correctly.

**Comment by BillSheldon-HunterIndustries** [comment]
We found a work around for this issue. For our Jasmine/Karma tests, we leveraged fake async to set up a tool tip directive and then verify the contents of the container. At run time, we found the tooltip text by going to the aria-describedby attribute. Using that value to look up the cdk text, that is part of the body.

**Comment by louie-succio** [comment]
As an alternative to using ng-reflect values to test correct data is passed to a child/custom/3rd party component, our team has been doing something like this.

We have a shared helper function that all tests can use, where we pass in the `selector` of the child component
```
export function selectDebugElement(selector: string): DebugElement {
  return fixture.debugElement.query(By.css(selector));
}
```

And if the html within the parent component looked something like this
```
<my-child-component [generatedText]="parentComponentGeneratedText"></my-child-component>
```

Then within the parent component spec, if you wanted to test whether the expected generated text is passed correctly to the child component it would look like this.

```
expect(selectDebugElement('my-child-component').componentInstance.generatedText).toBe(component.parentComponentGeneratedText);`
```

Since we would already have tests for the child component written within it's spec, we wouldn't want to duplicate those tests from the parent component spec so we just test that we are passing the expected data rather than testing if it's being used correctly in the child component.

I understand this isn't how some teams do their unit testing but I hope this helps someone who's having troubles with using ng-reflect.
