### ISSUE TITLE
Cannot find localize module en-US with posix

### ISSUE THREAD

**Issue by AstRonin** [angular/angular#28794]
# 🐞 bug report

### Description

I import 
"@angular/common/locales/en-US.js"
and get error:

> Error: Cannot find module './en-US.js'

![image](https://user-images.githubusercontent.com/2378239/52938462-2c601880-337b-11e9-89ee-7c67ed793443.png)

I looked to "@angula/common/locales" and did not found this package, but found like this with POSIX...
"https://github.com/angular/angular/tree/6.1.10/packages/common/locales"
![image](https://user-images.githubusercontent.com/2378239/52938617-8fea4600-337b-11e9-844c-f0059588c857.png)

So, is this really bug or I should import "en-US-POSIX" or do not use locale US and set only "en"?

## 🌍  Your Environment

**Angular Version:**
<pre><code>
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.2.7
Node: 8.11.1
OS: win32 x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.8.7
@angular-devkit/build-angular      0.8.7
@angular-devkit/build-optimizer    0.8.7
@angular-devkit/build-webpack      0.8.7
@angular-devkit/core               0.8.7
@angular-devkit/schematics         0.8.7
@angular/cdk                       6.4.7
@angular/cli                       6.2.7
@angular/material                  6.4.7
@angular/material-moment-adapter   6.4.7
@ngtools/webpack                   6.2.7
@schematics/angular                0.8.7
@schematics/update                 0.8.7
rxjs                               6.3.3
typescript                         2.9.2
webpack                            4.16.4

</code></pre>

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/20197, https://github.com/angular/angular/issues/20340

---

There's no `en-US` as it's the default locale for `en`, and `en.js` is dedicated for `US` locale.

**Comment by AstRonin** [comment]
ok, thanks
