### ISSUE TITLE
NPM Audit Failure - @angular/compiler-cli - V7.2.5

### ISSUE THREAD

**Issue by Adam-Kernig** [angular/angular#28796]
### Affected Package
@angular/compiler-cli - v7.2.5

### Description

│ Low           │ Regular Expression Denial of Service                         
│ Package       │ braces                                                       
│ Patched in    │ >=2.3.1                                                      
│ Dependency of │ @angular/compiler-cli [dev]                                  
│ Path          │ @angular/compiler-cli > chokidar > anymatch > micromatch >   braces                                                      
│ More info     │ https://npmjs.com/advisories/786                             

**Anything else relevant?**
Link to https://github.com/angular/angular/issues/28771 as they have reported it first

**Comment by Adam-Kernig** [comment]
Update:
The issue has been reported here to help
https://github.com/micromatch/anymatch/issues/26

**Comment by vladimiry** [comment]
Any reason to have two similar issues open (the original one https://github.com/angular/angular/issues/28771)?

**Comment by Adam-Kernig** [comment]
Yes, the post name was vague this is why I have included in the description for it to be linked.

**Comment by gkalpak** [comment]
Closing as a duplicate of #28771. I'll update the title there.

**Comment by Adam-Kernig** [comment]
thanks @gkalpak
