### ISSUE TITLE
mobileQuery.addEventListener is undefined in Safari

### ISSUE THREAD

**Issue by Kynson** [angular/angular#28798]
# 🐞 bug report

### Affected Package
@angular/core 
@angular/cdk/layout 

### Description
Safari returns TypeError: this.moblieQueryLarge.addEventListener is not a function (this.moblieQueryLarge is undefined) 

(Please note that in my code is 'mobileQueryLarge' not moblieQueryLarge' but the compiler compile 'moblieQueryLarge' in main.*.js even I change it.) 

But this.moblieQueryLarge is defined:

<pre><code>

constructor(private formBuilder: FormBuilder, private auth: AuthService, private router: Router, private media: MediaMatcher,
    private changeDetectorRef: ChangeDetectorRef, public dialog: MatDialog, private title: Title, private snackBar: MatSnackBar) {
    this.mobileQueryLarge = media.matchMedia('(max-width: 787px)');
    this.mobileQuerySmall = media.matchMedia('(max-width: 481px)');
    this.mobileQueryListener = () => changeDetectorRef.detectChanges();
    this.mobileQueryLarge.addEventListener('change', this.mobileQueryListener);
    this.mobileQuerySmall.addEventListener('change', this.mobileQueryListener);
  }

</code></pre>

There are no error while building <pre><code> ng build --prod </code></pre>

![screenshot 2019-02-18 at 21 16 39](https://user-images.githubusercontent.com/46522440/52953532-b67f9f80-33c2-11e9-8051-8c8450e01e82.png)

![screenshot 2019-02-18 at 20 42 38](https://user-images.githubusercontent.com/46522440/52952319-2855ea00-33bf-11e9-8d2a-ee0f73d88326.png)

I have tested it using Chrome and it works fine, also it also failed in mobile Safari and Chrome (iOS only)

## 🔬 Minimal Reproduction

run
<pre><code>
ng build --prod && http-server dist
</code></pre>

## 🔥 Exception
<pre><code>

No error is resulted.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.1
Node: 10.14.1
OS: darwin x64
Angular: 7.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/.DS_Store         <error>
@angular-devkit/architect         0.13.1
@angular-devkit/architect 2       <error>
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-angular 2   <error>
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.3.1
@angular-devkit/schematics        7.3.1
@angular-devkit/schematics 2      <error>
@angular/.DS_Store                <error>
@angular/cdk                      7.3.2
@angular/cdk 2                    <error>
@angular/cdk 3                    <error>
@angular/cli                      7.3.1
@angular/fire                     5.1.1
@angular/material                 7.3.2
@angular/material 2               <error>
@ngtools/webpack                  7.2.4
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.28.4

</code></pre>

**Anything else relevant?**
Safari version: 12.0.3 (14606.4.5) [Failed]

**Comment by ericmartinezr** [comment]
If I'm not wrong, issues related to the cdk should go in material's repo https://github.com/angular/material2

**Comment by pkozlowski-opensource** [comment]
Agreed with @ericmartinezr
