### ISSUE TITLE
Integration with single-spa

### ISSUE THREAD

**Issue by joeldenning** [angular/angular#28809]
# 🚀 feature request

Hi there 👋. I'm one of the authors and maintainers for a somewhat popular javascript library that allows angular, react, vue, and other frameworks to coexist within a single page application. The project is https://github.com/CanopyTax/single-spa

I've put some time into learning angular over the last three years in the name of allowing angular users to use single-spa. We now have an ecosystem of people who are using single-spa and angular together. However, I'm having trouble getting things working with angular 7 and with angular-cli, since angular is used to owning the whole html file and (afaik) does not have a way to lazy load an entire application.

I'd love to collaborate with your team on options available for this -- so far I've explored ngx-build-plus and a variety of other things and have created a list of my open questions at https://github.com/CanopyTax/single-spa-angular/issues/14.

Is there anybody on the Angular team who'd like to work with me on this? I'd love to either talk or chat synchronously if possible at some arranged time, or am also willing to talk on this github issue.

**Comment by robwormald** [comment]
Hi @joeldenning! Happy to chat, maybe drop me an email? robwormald at google dot com

**Comment by joeldenning** [comment]
Thanks! I'll draft up an email

**Comment by riccardomessineo** [comment]
Single-spa is a great framework, it helps people using new technology with legacy software.
Please, support this guys!

**Comment by joeldenning** [comment]
Update: I never was able to connect with Rob Wormald -- we almost set up a video call but then things fell through and it never happened. However, we have made significant progress on getting angular to work within a single-spa application and we've published a beta version of single-spa-angular that works with Angular 7.

See https://github.com/CanopyTax/single-spa-angular for more details.

**Comment by mgechev** [comment]
@joeldenning looks like the repo is in an excellent shape! I'm going to close this issue for now, but anything pops up please feel free to send us an email to devrel@angular.io.
