### ISSUE TITLE
angular.io/guide/router outlet url broken

### ISSUE THREAD

**Issue by yixd** [angular/angular#28805]
# 📚 Docs or angular.io bug report

### Description

Page not found in admin dashboard page with query parameters, fragments and secondary outlet.

### What's the affected URL?**
https://angular.io/guide/router#query-parameters-and-fragments

### Reproduction Steps**
1. Work till "Query paramters and fragments" section in "Milestone 5: Route guards" or just open the finished project in stackblitz
2. Go to login page (https://mxkjlkldpgj.angular.stackblitz.io/login)
3. Click contact (https://mxkjlkldpgj.angular.stackblitz.io/login(popup:compose))
4. Click login, shows admin dashboard (https://mxkjlkldpgj.angular.stackblitz.io/admin(popup:compose))
5. Go to login page (https://mxkjlkldpgj.angular.stackblitz.io/login(popup:compose))
6. Click logout (https://mxkjlkldpgj.angular.stackblitz.io/login(popup:compose))
7. Go to Admin page (https://mxkjlkldpgj.angular.stackblitz.io/login(popup:compose)?session_id=123456789#anchor)
8. Click login and Page not found shown (https://mxkjlkldpgj.angular.stackblitz.io/admin%28popup:compose%29(popup:compose)?session_id=123456789#anchor)

## 📷Screenshot

<img width="642" alt="capture" src="https://user-images.githubusercontent.com/14798053/52964642-cc647480-3370-11e9-9565-d4ddf772bfc9.PNG">

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by brandonroberts** [comment]
@yixd is this still an issue? Looks like the StackBlitz example has been deleted
