### ISSUE TITLE
QueryList isn't workung in angular elements

### ISSUE THREAD

**Issue by maxim1006** [angular/angular#28817]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/elements

### Is this a regression?

 It is not a regression issue

### Description

 When I use angular elements, such as tab-panel for example, 
```
<tab-panel>
<tab-panel-item></tab-panel-item>
<tab-panel-item></tab-panel-item>
</tab-panel>
```

I expect: 
1) Proper ngAfterContentInit callback, right now QueryList is empty
2) Proper updates of tabs on changes
```
this.tabItemsSubscribtion = this.tabItems.changes.subscribe((currentTabs:QueryList<UxTabPanelItem>) => {
            this.updateTabs(currentTabs);
        });
```

## 🔬 Minimal Reproduction

```
<tab-panel>
<tab-panel-item></tab-panel-item>
<tab-panel-item></tab-panel-item>
</tab-panel>
```

```
this.tabItemsSubscribtion = this.tabItems.changes.subscribe((currentTabs:QueryList<UxTabPanelItem>) => {
            this.updateTabs(currentTabs);
        });
```

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version: 7
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by lagatchell** [comment]
@maxim1006 what version of zone.js are you on?

**Comment by robwormald** [comment]
`@ContentChildren/ContentChild` cannot be supported in Elements, because Angular has no awareness of what is being projected into a template when used outside of Angular. 

See https://github.com/angular/angular/issues/24536 for more details - tldr - use slots and (slotchange)
