### ISSUE TITLE
uglifier issue

### ISSUE THREAD

**Issue by KingMario** [angular/angular#28812]
# 🐞 bug report

### Is this a regression?

I guess, no.

### Description

The [statements](https://github.com/visionmedia/debug/blob/3.2.6/src/browser.js#L72) in [debug](https://www.npmjs.com/package/debug) library are:
```
  args[0].replace(/%[a-zA-Z%]/g, function (match) {
    if (match === '%%') {
      return;
    }

    index++;

    if (match === '%c') {
      // We only are interested in the *last* %c
      // (the user may have provided their own)
      lastC = index;
    }
  });
```

but after `ng build --prod`, it turns:
```
e[0].replace(/%[a-zA-Z%]/g, function (t) {
        '%%' !== t && '%c' === t && (i = ++r);
    })
```
where ++r (index++) is misplaced after uglified.

Since I don't know which uglifier is used in `ng build --prod`, I file this issue here.

## 🔬 Minimal Reproduction

 

https://github.com/KingMario/angular-build-issue

https://github.com/KingMario/angular-build-issue/blob/master/src/app/app.component.ts#L13

## 🔥 Exception or Error
in development environment, got:
![image](https://user-images.githubusercontent.com/3956876/52990835-0010ce80-3445-11e9-898d-a430ba513972.png)

after `ng build --prod` and host the dist in a server, got:
![image](https://user-images.githubusercontent.com/3956876/52990860-20408d80-3445-11e9-8daa-21123565e80e.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.2.9
Node: 10.15.1
OS: darwin x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.9
@angular-devkit/build-angular     0.8.9
@angular-devkit/build-optimizer   0.8.9
@angular-devkit/build-webpack     0.8.9
@angular-devkit/core              0.8.9
@angular-devkit/schematics        0.8.9
@angular/cli                      6.2.9
@ngtools/webpack                  6.2.9
@schematics/angular               0.8.9
@schematics/update                0.8.9
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.16.4
</code></pre>

**Comment by trotyl** [comment]
Please report terser issue to https://github.com/angular/angular-cli or https://github.com/terser-js/terser itself.
