### ISSUE TITLE
How to configure when I want some npm modules to be transpiled to ES5 by typescript or webpack?

### ISSUE THREAD

**Issue by KingMario** [angular/angular#28813]
# 📚 Docs or angular.io bug report

### Description

Some npm modules are written in ES6. The module should be transpiled into ES5 for IE-compatibility.
But there's no documentation about how to configure when I want some npm modules to be transpiled by typescript or webpack (if the configuration exists).

Tried [stackoverflow](https://stackoverflow.com/search?q=angular+transpile+es6+npm+module) and got no answers for search term `angular transpile es6 npm module`.

**Comment by trotyl** [comment]
Wrong repo, please report to https://github.com/angular/angular-cli. Relates to https://github.com/angular/angular-cli/issues/5306, https://github.com/angular/angular-cli/issues/9508.
