### ISSUE TITLE
Why am I doing this?

### ISSUE THREAD

**Issue by weibon** [angular/angular#28819]
![312](https://user-images.githubusercontent.com/24470508/53011753-19813d00-347c-11e9-817d-ecfa0904852c.PNG)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Buddy, stop opening this kind of issues. Respect the template, it is there for a reason.
