### ISSUE TITLE
Cache Ivy's TView for subsequent requests with Angular SSR

### ISSUE THREAD

**Issue by bmeurer** [angular/angular#28820]
# 🚀 feature request

### Relevant Package

This feature request is for @angular/universal and @angular/core.

### Description

It seems that quite a significant amount of time is spent in setting up the `TView` (the template view) per render request. As per suggestion from @mhevery this is actually done unnecessarily and could be avoided by some proper caching. I did a naive prototype of this using the following patch

```diff
--- dist/server_ORIG.js 2019-02-05 20:45:02.000000000 +0100
+++ dist/server.js      2019-02-05 20:46:29.000000000 +0100
@@ -13002,7 +13002,11 @@
         16 /* CheckAlways */ | 256 /* IsRoot */;
     var rootContext = createRootContext(opts.scheduler, opts.playerHandler);
     var renderer = rendererFactory.createRenderer(hostRNode, componentDef);
-    var rootView = createLView(null, createTView(-1, null, 1, 0, null, null, null), rootContext, rootFlags, rendererFactory, renderer, undefined, opts.injector || null);
+    var tView = componentType.tView;
+    if (tView === undefined) {
+      componentType.tView = tView = createTView(-1, null, 1, 0, null, null, null);
+    }
+    var rootView = createLView(null, tView, rootContext, rootFlags, rendererFactory, renderer, undefined, opts.injector || null);
     var oldView = enterView(rootView, null);
     var component;
     try {

```
on top of the bmeurer/ivy-perf@11a26f2f commit. I see performance improvements of up to **17%** with this change, which suggests that investing in `TView` caching strategy might pay off. Looking into the profile, several things improve that are related to `TView` creation, in particular the time spent in the `GrowFastSmiOrObjectElements` builtin **drops from 4% to around 1%**, which matches @mhevery's intuition that `Array` resizing should almost never happen once the `TView` is created (and used for the first time). Another strong indicator is that `Array#fill()` completely disappears from the profile.

### Describe the solution you'd like

This would need some changes to the interface to allow Angular Universal to appropriately cache the `TView`s. The above hack to just slap it onto the `componentType` is probably not a very good idea.

**Comment by AndrewKushnir** [comment]
Closing this ticket, since `TView` caching is already present in the code (the code is invoked both on the server and on the client):

https://github.com/angular/angular/blob/main/packages/core/src/render3/instructions/shared.ts#L348-L370

Thank you.

**Comment by alan-agius4** [comment]
Just to clarify whilst we do have TView caching at the moment, this is not shared among requests which is what this issue suggests to do.

**Comment by alan-agius4** [comment]
We actually do cache this between requests. Here's the method is caching logic https://github.com/angular/angular/blame/ca517d7f2c38775969a65fde1d88f41ad5f27931/packages/core/src/render3/instructions/shared.ts#L343
