### ISSUE TITLE
angular6 - aot and build optimizer issue with slick.js

### ISSUE THREAD

**Issue by Anilpandiya** [angular/angular#28822]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

I need help regarding below issue - 
https://stackoverflow.com/questions/54762464/angular-6-aot-and-build-optimizer-issue

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by pkozlowski-opensource** [comment]
As @ericmartinezr pointed out this is a support request that doesn't belong here. If you believe that there is a problem with a build optimiser please open an issue, with a minimal reproduce scenario, in https://github.com/angular/angular-cli
