### ISSUE TITLE
Problems with inject inside factory

### ISSUE THREAD

**Issue by waterplea** [angular/angular#28824]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 No

### Description

I've updated from Angular 5 to Angular 7 and was trying new `options` and `factory` for `InjectionTokens`. I expected it to work like provide `useFactory` with `deps`, but there seem to be no `deps`, but instead an `inject` function, which is supposed to 

> inject a token from the currently active injector.

I've made 2 exactly same components, one injects parent component AppComponent through it's class name to get a value from it, other does the same thing but injects a token with a factory, that tries to inject parent component and get that value from it. When I try to do so, I get `No provider for AppComponent` error. Isn't this suppose to work? I thought they would be requesting providers from the same injector. Note that it also shows `Hello1Component` instead of Hello2 in error message which makes it all even stranger.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-factory-inject-bug

## 🔥 Exception or Error
<pre><code>ERROR
    Error: StaticInjectorError(AppModule)[Hello1Component -> AppComponent]: 
    StaticInjectorError(Platform: core)[Hello1Component -> AppComponent]: 
    NullInjectorError: No provider for AppComponent!
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>7.2.5
</code></pre>

**Anything else relevant?**

**Comment by alxhub** [comment]
This is working as expected. Tree-shakeable providers are only for module injectors, not for component injectors. So `inject(AppComponent)` will fail, because the current injector when the factory is running is the application injector, which knows nothing about components.
