### ISSUE TITLE
Declaring private constructors

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2883]
When generating `.d.ts` file it is sometimes nice to be able to export a class as non-instantiable. Some classes are visible to the developer, but they are never meant to be instantiated by the developer, so we would like to hide their constructor.

assume class in source which needs to be exported:
```
class SomeType {
  /**
   * @private()  // some way to mark a constructor as private.
   */
  constructor(somePrivateDep:SomePrivateDep) {}

  someMethod(): void {...}
}
```

When generating `.d.ts` we have two options:

1) We can generate a class and hide a constructor:

```
declare class SomeType {
  someMethod(): void {...}
}
```

2) or we create an interface with an injectable ref.

```
interface PrivateConstructor {} // declared only once in .d.ts file
declare var SomeType: PrivateConstructor; // needed to make DI work properly
interface SomeType {
  someMethod(): void {...}
}
```

I think we should do option no. 2, but either one is fine.

**Comment by petebacondarwin** [comment]
@mhevery can you give a bit more info how option 2 works? Is this `PrivateConstructor` reused for each situation where there is a private constructor?

**Comment by mhevery** [comment]
`PrivateConstructor` is there just so that we can hint to the developer that they should net be trying to instantiate it.

In TypeScript interfaces do not have a runtime representation and for that reason there will be no runtime reference, hence the DI will not work. To combat this we need to create a references using `declare var SomeType`. We could declare it as any but I think giving it a nice type as `PrivateConstructor` will give the user of the `.d.ts` file a nice hint.

It really is as simple as turning this:

```
class SomeType {
  /**
   * @private()  // some way to mark a constructor as private.
   */
  constructor(somePrivateDep:SomePrivateDep) {}

  someMethod(): void {...}
}
```

into:
```
declare var SomeType: PrivateConstructor;
interface SomeType {
  someMethod(): void {...}
}
```

**Comment by petebacondarwin** [comment]
OK. I think I can do that.

**Comment by mhevery** [comment]
thanks.

**Comment by alexeagle** [comment]
+1 for option 2 - this is the idiomatic way that TS themselves declare interface types which need runtime retention.

**Comment by alexeagle** [comment]
did you consider option 3: change angular sources to move the private constructor out of the exported symbol?
```
export interface SomeType {
  someMethod(): void {...}
}
var SomeType: void; // runtime retention
class SomeTypeImpl implements SomeType {
  constructor(somePrivateDep:SomePrivateDep) {}
}
```

**Comment by petebacondarwin** [comment]
I was wondering about that but I guess that it adds an extra unnecessary type to the system?

**Comment by mhevery** [comment]
Isn't @alexeagle option #3 just manual option #2?

**Comment by mhevery** [comment]
Actually no, no.3, will not work. That is because we need to export `SomeType` to have a real reference for the DI. So no.2 it is.

**Comment by alexeagle** [comment]
yes. means less magic in the codegen

**Comment by alexeagle** [comment]
in option 3 you still have a var which is retained in the .d.ts and at runtime

**Comment by mhevery** [comment]
but the var points to null. So DI would not work.

**Comment by mhevery** [comment]
You would have to do something like:

```
export interface SomeType {
  someMethod(): void {...}
}
class SomeTypeImpl implements SomeType {
  constructor(somePrivateDep:SomePrivateDep) {}
}

var SomeType: void = SomeTypeImpl; // runtime retention
```

and that would just bloat angular codebase.
