### ISSUE TITLE
docs: empty gap on the bottom of angular.io

### ISSUE THREAD

**Issue by jotatoledo** [angular/angular#28858]
### Description

An empty gap caused by a `<mat-icon>` element.

### What's the affected URL?**

Seems to affect most pages

### Reproduction Steps**

1. Go to https://angular.io/
2. Scroll to the bottom

### Browser info

Chrome Version 72.0.3626.109

Sidenote: a quick fix would be to wrap the `<mat-icon>` in a `<div.cdk-visually-hidden> `element. Im willing to do the PR if this is accepted.

**Comment by gkalpak** [comment]
It seems to be a Chrome issue. It doesn't happen on other browsers (Firefox, Edge, IE) and (by looking at the page's layout and styles) I couldn't find a reason for it to happen 😕

**Comment by gkalpak** [comment]
Nevermind, I got it ✌️ Creating a PR.

**Comment by gkalpak** [comment]
And now I read the issue description again and everything is there: What is causing the issue, how to fix and even offering to create a PR.

> An empty gap caused by a `<mat-icon>` element.
> [...]
> Sidenote: a quick fix would be to wrap the `<mat-icon>` in a `<div.cdk-visually-hidden> `element. Im willing to do the PR if this is accepted.

That's pretty embarrassing 🤦‍♂️ 
So sorry I missed all that great info on the first read, @jotatoledo. (That's unlike me, I promise 😇)
You still rock ❤️

**Comment by jotatoledo** [comment]
@gkalpak no worries, such a small comment can easily be overlooked.
