### ISSUE TITLE
UrlSerializer is not working as expected

### ISSUE THREAD

**Issue by JoniJnm** [angular/angular#28867]
# 🐞 bug report

### Affected Package

@angular/router

### Is this a regression?

No

### Description

The UrlSerializer provider is not working with internal [routerLink] navigations.

## 🔬 Minimal Reproduction
* https://stackblitz.com/edit/angular-issue-28867-gsqjqx (angular 10)
* https://stackblitz.com/edit/angular-issue-28867-uvnvag (angular 13.1)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.2
Node: 10.15.1
OS: linux x64
Angular: 7.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.2
@angular-devkit/build-angular     0.13.2
@angular-devkit/build-optimizer   0.13.2
@angular-devkit/build-webpack     0.13.2
@angular-devkit/core              7.3.2
@angular-devkit/schematics        7.3.2
@angular/cdk                      7.3.2
@angular/cli                      7.3.2
@angular/material                 7.3.2
@ngtools/webpack                  7.3.2
@schematics/angular               7.3.2
@schematics/update                0.13.2
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Comment by jinbeomhong** [comment]
It seems to me that `Router` doesn't call `UrlSerializer.parse()` before `NavigationStart` when a user navigate pages through the router.

**Comment by jasonaden** [comment]
Thanks. This seems like it's definitely a bug and could trip some people up. Thanks for reporting.

**Comment by JoniJnm** [comment]
Seems like stackblitz.com has changed and the direct URL is not working. They change the queryParams

**Comment by atscott** [comment]
Confirmed in v10 as well. FYI, the issue with the url is that line 38 should be `newTree.queryParams = params;` not `newTree.queryParams = Object;`

**Comment by JoniJnm** [comment]
Fixed and updated to v10, thanks
