### ISSUE TITLE
docs: add translations menu to main toolbar

### ISSUE THREAD

**Issue by jotatoledo** [angular/angular#28861]
### Description

Add some form of dropdown-menu with with hyperlinks to the available translations of the angular docs.

**Comment by jenniferfell** [comment]
Thanks for the input. Currently, translations are available from the site footer under "Languages."

**Comment by kapunahelewong** [comment]
Hi @jotatoledo since these are available in the footer, I'll close out this issue. Feel free to re-open if you have anymore thoughts or questions about it. Thanks! :)
