### ISSUE TITLE
Teach About "State should Go to Lowest Common Ancestor" similar to "Thinking in React"

### ISSUE THREAD

**Issue by YisraelV** [angular/angular#28863]
# 📚 Docs or angular.io bug report

### Description

React docs have a section "Thinking in React". This section explains that if a piece of state is needed in two different component, it should reside in their lowest common ancestor and be passed as an input. 

This conecept is very important for Angular developers to know. I've seen some very bad example in Angular codebases that don't take advantage of this technique. Alternative method were employed instead: 

1. Child component fetches data, then passes it to its parent in an output, which passes it to another child as input.

2. Holding the state in a service.

Most of the time storing the data in the parent is a much better solution.

I suggest putting a similar tutorial in a prominent place in the Angular docs.

**Comment by jenniferfell** [comment]
@brandonroberts Maybe this is something we can work into Part 2 of the new Getting Started?

**Comment by mgechev** [comment]
We're not focused on state management guidelines at the moment. As part of the micro-frontend research project, we'll explore developing such content. Until then, let's close the issue and reuse community resources.
