### ISSUE TITLE
Can't resolve 'router.ngfactory'

### ISSUE THREAD

**Issue by artuska** [angular/angular#28868]
```
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '../../node_modules/@angular/router/router.ngfactory' in '/private/var/www/balu/balumates-ru-frontend/src/app'
```

This error throws all the time i run `ng build --configuration=production` with `"aot": true`.

This error throws all the time i run `ng serve --aot`.

Angular — 7.2.5 // any version above 7
Angular CLI — 7.3.2 // any version above 7
TypeScript — 3.2.4

**Comment by gkalpak** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by artuska** [comment]
SOLVED!

If you have this type of error probably you have upgraded from Angular 5 to 6 or 7.

Replace `"rootDir": "./src",` in your `tsconfig.json` file to `"rootDir": "./",` or just remove this parameter completely.
