### ISSUE TITLE
cdk-virtual-scroll-viewport should set styles on nested wrapper

### ISSUE THREAD

**Issue by waterplea** [angular/angular#28865]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/cdk/scrolling

### Description
Documentation on virtual scrolling says that cdk-virtual-scroll-viewport can have orientation="horizontal" but we need to `ensure that the item are laid out horizontally via CSS`. We cannot do that if our components have encapsulated styles. It should set `display: flex` and `flex-direction: row` by itself. We shouldn't care about internal realization of cdk-virtual-scroll-viewport nor use ::ng-deep hacks.

### Describe the solution you'd like
I would expect it to set styles when I set orientation.

### Describe alternatives you've considered
It could also inherit styles from cdk-virtual-scroll-viewport somehow, so that we have an actual element in out templates that we can define our styles on.

**Comment by gkalpak** [comment]
Please, report issues related to `@angular/material` and `@angular/cdk` in [material repo][1].

[1]: https://github.com/angular/material2
