### ISSUE TITLE
Docs: http reportProgress requires observe events

### ISSUE THREAD

**Issue by oBusk** [angular/angular#28886]
# 📚 Docs or angular.io bug report

### Description

The section that explains using `reportProgress: true` does not mention the fact that enabling `reportProgress` does nothing when still `observe: 'body'` which is default. 

I don't know if the text has to mention this explicitly since it's probably understandable that you need to observe events to be able to do anything with them, but the example should atleast specify `observe: 'events'`

```typescript
const req = new HttpRequest('POST', '/upload/file', file, {
  reportProgress: true
});
```

### What's the affected URL?**
https://angular.io/guide/http#listening-to-progress-events

**Comment by brandonroberts** [comment]
Fixed via #28892
