### ISSUE TITLE
feat(router): add new `NavigationStop` base `RouterEvent`

### ISSUE THREAD

**Issue by jorroll** [angular/angular#28885]
# 🚀 feature request

### Relevant Package

This feature request is for @angular/router

### Description

As pointed out by others (e.g. https://github.com/angular/angular/issues/11375), the `RouterEvent` api could be improved. Specifically, I often want to receive an event when navigation has stopped. Currently, to do this you must filter on `NavigationEnd`, `NavigationError`, and `NavigationCancel` which is annoying and was a source of confusion for me when I was learning angular -> "Navigation is clearly over, why isn't `NavigationEnd` firing??".

### Describe the solution you'd like

Create a base class which the other navigation ending events extend. For example:

```typescript
export class NavigationStop extends RouterEvent {}

export class NavigationEnd extends NavigationStop {}
export class NavigationError extends NavigationStop {}
export class NavigationCancel extends NavigationStop {}
```

I believe this would be a non-breaking change and it would allow easier, more intuitive interactions with the router api. For example:

```typescript
this.router.events.pipe(
  filter(event => event instanceof NavigationStop)
).subscribe(() => {
  // do stuff...
})
```

I don't actually care what the name of this new, navigation-is-over, base class is. Some options:

- NavigationDone
- NavigationOver
- NavigationFinished
- NavigationStop

### Describe alternatives you've considered

Considering this is a quality of life improvement, the alternative is to do nothing.

**Comment by jasonaden** [comment]
This isn't a bad idea at all. If this is something you would want to work on getting added, that would be great. We could get a PR going and try to get it added in.

**Comment by jasonaden** [comment]
Something like `NavigationFinally` might be good.

**Comment by thefliik** [comment]
@jasonaden I've created a PR for this issue #29823. I added two notes regarding things I was unsure of.

**Comment by lacolaco** [comment]
I think it also can be solved by a pipe of RxJS. Nothing be changed. Just adding new independent API.

```ts
import { routerFinally } from '@angular/router'


this.router.events.pipe(
  routerFinally()
).subscribe(() => {
  // do stuff...
})
```
