### ISSUE TITLE
Router.navigate url with slashes error

### ISSUE THREAD

**Issue by andmaltes** [angular/angular#28887]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

import { NavigationStart, Router, ActivatedRoute } from '@angular/router';

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
No

### Description

 A clear and concise description of the problem...

When I try to navigate in the component to a URL that contains an slash (/), slashes are replaced by the URL encode and does not navigate to the correct URL.

In my current project:

Configured routes:
```

{
    path: 'hotel',
    component: HomeComponent
  },
  {
    path: 'hotel',
    component: HotelFormComponent,
    outlet: 'form'
  },
  {
    path: 'hotelResult/:staticType/:staticCode/:dateFrom/:dateTo',
    component: HotelResultComponent,
    runGuardsAndResolvers: 'always'
  },
  {
    path: '**',
    redirectTo: 'hotel'
  }

```
 
In the component: 

`
 this.router.events.subscribe(routerEvent => {
      if (routerEvent instanceof NavigationStart) {
        let params = this.route.snapshot.params;
        if (
          routerEvent.url.indexOf('hotel/') !== -1 &&
          routerEvent.url.indexOf('hotelResult/') === -1
        ) {
          let path = routerEvent.url
            .split('?')[0]
            .replace('/hotel/', 'hotelResult/');
          this.router.navigate(
            [
              {
                outlets: {
                  primary: [
                    path,
                    params
                  ],
                  form: 'hotel'
                }
              }
            ],
            {
              skipLocationChange: true
            }
          );
        }
...
`
In the console log:

> Router Event: NavigationStart
platform-browser.js:211 NavigationStart(id: 1, url: '/hotel/C/CO_02_05001/20190621/20190622?ha1=2&hn1=0')
platform-browser.js:211 NavigationStart {id: 1, url: "/hotel/C/CO_02_05001/20190621/20190622?ha1=2&hn1=0", navigationTrigger: "imperative", restoredState: null}
app.component.ts:46 routerEvent.url
app.component.ts:50 hotelResult/C/CO_02_05001/20190621/20190622
platform-browser.js:216 Router Event: NavigationStart
platform-browser.js:211 NavigationStart(id: 2, url: '/hotelResult%5CC%5CCO_02_05001%5C20190621%5C20190622(form:hotel)')
platform-browser.js:211 NavigationStart {id: 2, url: "/hotelResult%5CC%5CCO_02_05001%5C20190621%5C20190622(form:hotel)", navigationTrigger: "imperative", restoredState: null}
core.js:16819 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
platform-browser.js:216 Router Event: RoutesRecognized
platform-browser.js:211 RoutesRecognized(id: 2, url: '/hotelResult%5CC%5CCO_02_05001%5C20190621%5C20190622(form:hotel)', urlAfterRedirects: '/hotel(form:hotel)', state: Route(url:'', path:'') { Route(url:'hotel', path:'hotel'), Route(url:'hotel', path:'hotel') } )
platform-browser.js:211 RoutesRecognized {id: 2, url: "/hotelResult%5CC%5CCO_02_05001%5C20190621%5C20190622(form:hotel)", urlAfterRedirects: "/hotel(form:hotel)", state: RouterStateSnapshot}
platform-browser.js:216 Router Event: GuardsCheckStart
platform-browser.js:211 GuardsCheckStart(id: 2, url: '/hotelResult%5CC%5CCO_02_05001%5C20190621%5C20190622(form:hotel)', urlAfterRedirects: '/hotel(form:hotel)', state: Route(url:'', path:'') { Route(url:'hotel', path:'hotel'), Route(url:'hotel', path:'hotel') } )
platform-browser.js:211 GuardsCheckStart {id: 2, url: "/hotelResult%5CC%5CCO_02_05001%5C20190621%5C20190622(form:hotel)", urlAfterRedirects: "/hotel(form:hotel)", state: RouterStateSnapshot}
platform-browser.js:216 Router Event: ChildActivationStart
platform-browser.js:211 ChildActivationStart(path: '')
platform-browser.js:211 ChildActivationStart {snapshot: ActivatedRouteSnapshot}
platform-browser.js:216 Router Event: ActivationStart
platform-browser.js:211 ActivationStart(path: 'hotel')
platform-browser.js:211 ActivationStart {snapshot: ActivatedRouteSnapshot}
platform-browser.js:216 Router Event: ChildActivationStart
platform-browser.js:211 ChildActivationStart(path: '')
platform-browser.js:211 ChildActivationStart {snapshot: ActivatedRouteSnapshot}
platform-browser.js:216 Router Event: ActivationStart
platform-browser.js:211 ActivationStart(path: 'hotel')
platform-browser.js:211 ActivationStart {snapshot: ActivatedRouteSnapshot}
platform-browser.js:216 Router Event: GuardsCheckEnd
platform-browser.js:211 GuardsCheckEnd(id: 2, url: '/hotelResult%5CC%5CCO_02_05001%5C20190621%5C20190622(form:hotel)', urlAfterRedirects: '/hotel(form:hotel)', state: Route(url:'', path:'') { Route(url:'hotel', path:'hotel'), Route(url:'hotel', path:'hotel') } , shouldActivate: true)
platform-browser.js:211 GuardsCheckEnd {id: 2, url: "/hotelResult%5CC%5CCO_02_05001%5C20190621%5C20190622(form:hotel)", urlAfterRedirects: "/hotel(form:hotel)", state: RouterStateSnapshot, shouldActivate: true}
platform-browser.js:216 Router Event: ResolveStart
platform-browser.js:211 ResolveStart(id: 2, url: '/hotelResult%5CC%5CCO_02_05001%5C20190621%5C20190622(form:hotel)', urlAfterRedirects: '/hotel(form:hotel)', state: Route(url:'', path:'') { Route(url:'hotel', path:'hotel'), Route(url:'hotel', path:'hotel') } )
platform-browser.js:211 ResolveStart {id: 2, url: "/hotelResult%5CC%5CCO_02_05001%5C20190621%5C20190622(form:hotel)", urlAfterRedirects: "/hotel(form:hotel)", state: RouterStateSnapshot}
platform-browser.js:216 Router Event: ResolveEnd
platform-browser.js:211 ResolveEnd(id: 2, url: '/hotelResult%5CC%5CCO_02_05001%5C20190621%5C20190622(form:hotel)', urlAfterRedirects: '/hotel(form:hotel)', state: Route(url:'', path:'') { Route(url:'hotel', path:'hotel'), Route(url:'hotel', path:'hotel') } )
platform-browser.js:211 ResolveEnd {id: 2, url: "/hotelResult%5CC%5CCO_02_05001%5C20190621%5C20190622(form:hotel)", urlAfterRedirects: "/hotel(form:hotel)", state: RouterStateSnapshot}
platform-browser.js:216 Router Event: ActivationEnd
platform-browser.js:211 ActivationEnd(path: 'hotel')
platform-browser.js:211 ActivationEnd {snapshot: ActivatedRouteSnapshot}
platform-browser.js:216 Router Event: ActivationEnd
platform-browser.js:211 ActivationEnd(path: 'hotel')
platform-browser.js:211 ActivationEnd {snapshot: ActivatedRouteSnapshot}
platform-browser.js:216 Router Event: ChildActivationEnd
platform-browser.js:211 ChildActivationEnd(path: '')
platform-browser.js:211 ChildActivationEnd {snapshot: ActivatedRouteSnapshot}
platform-browser.js:216 Router Event: NavigationEnd
platform-browser.js:211 NavigationEnd(id: 2, url: '/hotelResult%5CC%5CCO_02_05001%5C20190621%5C20190622(form:hotel)', urlAfterRedirects: '/hotel(form:hotel)')
platform-browser.js:211 NavigationEnd {id: 2, url: "/hotelResult%5CC%5CCO_02_05001%5C20190621%5C20190622(form:hotel)", urlAfterRedirects: "/hotel(form:hotel)"}
platform-browser.js:216 Router Event: Scroll
platform-browser.js:211 Scroll(anchor: 'null', position: 'null')
platform-browser.js:211 Scroll {routerEvent: NavigationEnd, position: null, anchor: null}

So, for some reason is changing 
/hotel/C/CO_02_05001/20190621/20190622?ha1=2&hn1=0
to

/hotelResult%5CC%5CCO_02_05001%5C20190621%5C20190622(form:hotel)

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.2.3
Node: 11.6.0
OS: win32 x64
Angular: 7.2.2
... animations, common, compiler, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.11.4
@angular-devkit/build-angular      0.12.3
@angular-devkit/build-ng-packagr   0.11.4
@angular-devkit/build-optimizer    0.12.3
@angular-devkit/build-webpack      0.12.3
@angular-devkit/core               7.1.4
@angular-devkit/schematics         7.2.3
@angular/cdk                       7.3.0
@angular/cli                       7.2.3
@angular/compiler-cli              7.2.5
@angular/flex-layout               7.0.0-beta.23
@angular/material                  7.3.0
@angular/material-moment-adapter   7.2.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.2.3
@schematics/angular                7.2.3
@schematics/update                 0.12.3
ng-packagr                         4.7.1
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.29.0

</code></pre>

**Anything else relevant?**

**Comment by nil4you** [comment]
Can you provide minimal stackblitz.
To me looks like it's falling in malformedUriErrorHandler
https://github.com/angular/angular/blob/master/packages/router/src/router.ts

Not sure, once you provide stackblitz then I can confirm.

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-issue-repro2).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
