### ISSUE TITLE
docs: ngsw-config push notifications

### ISSUE THREAD

**Issue by SauceCode84** [angular/angular#28883]
# 📚 Docs or angular.io bug report

### Description

Is there any documentation present for configuring push notifications in **ngsw-config.json**?
There used to be an equivalent for configuring push notifications in **ngsw-manifest.json** in prior versions of the Angular Service Worker.

### What's the affected URL?
https://angular.io/guide/service-worker-config

**Comment by gkalpak** [comment]
I don't think there anythink you need to do in `ngsw-config.json`. You use your public key with [SwPush][1].
Leaving this open as a feature request to mention notifications (and what you can do with them) in the guides.

[1]: https://angular.io/api/service-worker/SwPush

**Comment by gkalpak** [comment]
In addition to the info in the [`SwPush` API docs][1], we now have a [Notifications guide][2] with more info on configuring notifications. I am going to close this. If you find things that are missing or can be improved in the docs, feel free to suggest changes.

[1]: https://angular.io/api/service-worker/SwPush#usage-notes
[2]: https://angular.io/guide/service-worker-notifications
