### ISSUE TITLE
File-level circular dependency checking

### ISSUE THREAD

**Issue by benlesh** [angular/angular#28895]
We already have circular dependency checking in our build/CI process (`gulp check-cycle`), however it's not as strict as the circular dependency checking we have in google3, and that causes us friction.

We need to have circular dependency checking that does the check such that inter-file dependencies are not circular. This is much more strict that what you would normally see in TS OSS.

In essence, we need dependency cycle checking that doesn't care if you're only importing types from a file, it just looks for any cycles in file imports.

**Comment by santoshyadav198613** [comment]
Hi @benlesh ,
Can i take this up, can you provide some help if i take this up please.

**Comment by benlesh** [comment]
@santoshyadav198613 the team is happy to support any PR and this with reviews and feedback. There may be others that have some suggestions on where to start. Unfortunately, I don't have any recommendations right now to help you get started, just a high-level need described in the issue.

**Comment by santoshyadav198613** [comment]
ok Thanks @benlesh ,

I have also noticed, that if we try to add a component in same components html file, we get circular dependency but it is not captured in build as well. So if i am not wrong, we are also trying to handle such scenarios here.

Will check for some utilities and will try to refer the same.,

Regards,
Santosh

**Comment by AndrewKushnir** [comment]
Hi Ben! The circular dependency tracking tool was re-written by @devversion recently. The tool is now on par (or even stricter in some cases) with g3 dependency tracking. Thank you.
