### ISSUE TITLE
Shrinkwrap broken after `npm i`

### ISSUE THREAD

**Issue by mprobst** [angular/angular#2889]
I ran `git pull upstream master`, `npm i`, `npm update clang-format`, `npm shrinkwrap --dev`, and now receive the errors below. It appears as if it includes dev dependencies for `ts2dart` on my machine, but I have no idea why. It is not a `npm link`ed package.

```
$ npm shrinkwrap --dev
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/Users/martinprobst/.homebrew/bin/npm" "shrinkwrap" "--dev"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: merge2@0.3.6 /Users/martinprobst/src/angular/node_modules/ts2dart/node_modules/merge2
npm ERR! extraneous: temp@0.8.3 /Users/martinprobst/src/angular/node_modules/ts2dart/node_modules/temp
npm ERR! extraneous: chai@2.3.0 /Users/martinprobst/src/angular/node_modules/ts2dart/node_modules/chai
npm ERR! extraneous: gulp-sourcemaps@1.5.2 /Users/martinprobst/src/angular/node_modules/ts2dart/node_modules/gulp-sourcemaps
npm ERR! extraneous: which@1.1.1 /Users/martinprobst/src/angular/node_modules/ts2dart/node_modules/which
npm ERR! extraneous: gulp-mocha@2.1.2 /Users/martinprobst/src/angular/node_modules/ts2dart/node_modules/gulp-mocha
npm ERR! extraneous: gulp-util@3.0.6 /Users/martinprobst/src/angular/node_modules/ts2dart/node_modules/gulp-util
npm ERR! extraneous: gulp@3.9.0 /Users/martinprobst/src/angular/node_modules/ts2dart/node_modules/gulp
npm ERR! extraneous: gulp-typescript@2.7.8 /Users/martinprobst/src/angular/node_modules/ts2dart/node_modules/gulp-typescript
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

It was possible to fix this by deleting the mentioned directories.

**Comment by IgorMinar** [comment]
I tried to repro this and wasn't successful. Upon further investigation I believe that you must have `cd`-ed into the `node_modules/ts2dart` and invoked `npm install` in there. That caused dev dependencies for ts2dart to be installed into `node_modules/ts2dart/node_modules/`.

If you look at the list of extraneous dependencies, you'll see that it's exactly the list of dev dependencies specified in [ts2dart's package.json](https://github.com/angular/ts2dart/blob/a8bd4694c0d8e44200db02732c6ed516a358ba68/package.json#L16-L29).

I'm testing npm v3 now which should resolve most of the issues we've been seeing according to the [changelog][https://github.com/npm/npm/releases/tag/v3.0.0). If that proves to be stable enough for our usecase, we'll switch over to it.
