### ISSUE TITLE
Function calls are not supported in decorators when building with bazel

### ISSUE THREAD

**Issue by eachirei** [angular/angular#28898]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/bazel (maybe?)

### Is this a regression?

 Not as far as I know.

### Description

 I'm working on an Angular 7 CLI project. Because of the size of the project, time of the build has increased to ~10 mins and that's why I tried to switch to Bazel to see if there are any improvements. After some bugfixes I encountered a final error which I do not know how to get around:
`Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'StoreModule' was called.`
Basically is the old `someModule.forRoot` problem. I tried to follow some fixes from #23609 but I don't know how to change the tsconfig file used by bazel when building. 

## 🌍  Your Environment
**Angular Version:**
<pre><code>

Angular CLI: 8.0.0-beta.2
Node: 11.10.0
OS: darwin x64
Angular: 7.2.6
... animations, common, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, upgrade

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.14.0-beta.2
@angular-devkit/architect-cli      0.14.0-beta.2
@angular-devkit/build-angular      0.14.0-beta.2
@angular-devkit/build-optimizer    0.14.0-beta.2
@angular-devkit/build-webpack      0.14.0-beta.2
@angular-devkit/core               8.0.0-beta.2
@angular-devkit/schematics         8.0.0-beta.2
@angular/bazel                     8.0.0-beta.5
@angular/cdk                       7.3.3
@angular/cli                       8.0.0-beta.2
@angular/compiler                  8.0.0-beta.5
@angular/flex-layout               7.0.0-beta.23
@angular/language-service          8.0.0-beta.5
@angular/material                  7.3.3
@angular/material-moment-adapter   7.3.3
@angular/platform-server           8.0.0-beta.5
@angular/router                    8.0.0-beta.5
@ngtools/webpack                   8.0.0-beta.2
@schematics/angular                8.0.0-beta.2
@schematics/update                 0.14.0-beta.2
rxjs                               6.4.0
typescript                         3.2.4
webpack                            4.29.5
</code></pre>

**Comment by alexeagle** [comment]
Under Bazel, we rely on the compilation of third-party libraries to happen outside of compiling your app. For this, we use a `postinstall` script which runs the `ngc` compiler over the `node_modules` directory.

Check if the `StoreModule` in question has an ngsummary file in the node_modules. For example, the `CommonModule` from `@angular/common` requires the file `node_modules/@angular/common/common.ngsummary.json` to be produced by the `postinstall` step, so that the compilation of user code under Bazel can resolve Angular's symbols.

Note that the postinstall uses the `angular-metadata.tsconfig.json` file to drive the `ngc` compiler so the change may be needed there.

**Comment by literalpie** [comment]
I am able to reproduce this with the following steps:
1. `ng new my-app`
2. `ng add @angular/bazel`
3. modify BUILD.bazel to include `"@npm//@ngx-translate/core"` (after using `--leaveBazelFilesOnDisk`)
4. `ng build`

In node_modules, I see `ngx-translate-core.metadata.json`, but no ngsummary. Was ngsummary renamed, or did the post install step fail?

**Comment by literalpie** [comment]
I figured it out! I needed to read Alex's last sentence more carefully :-)

adding the library (in my case, `node_modules/@ngx-translate/**/*`) fixed the issue.

**Comment by marcus-sa** [comment]
@literalpie doesn't seem to fix it for me :/

**Comment by alexeagle** [comment]
@marcus-sa do you have the ngsummary files in the node_modules like I described above?

**Comment by marcus-sa** [comment]
@alexeagle I had to clean and reinstall my dependencies, simply running the command manually didn't work.
It works now, yes :)

**Comment by RobertSenkel** [comment]
@alexeagle well, if the module in the node_modules does not have ngsummary, then the basel will not be able to build the application?

**Comment by alxhub** [comment]
Closing as obsolete - the Bazel builder and associated CLI functionality are deprecated and no longer supported.
