### ISSUE TITLE
docs(testing): 5 specs failures

### ISSUE THREAD

**Issue by KostyaTretyak** [angular/angular#28909]
# 📚 Docs or angular.io bug report

### Description

For now, from docs downloads example, 5 specs failures:
- Angular async helper > use jasmine.clock() > should auto enter fakeAsync
- Angular async helper > should get Date diff correctly in fakeAsync
- Angular async helper > test jsonp > should wait until promise.then is called
- Angular async helper > should run timeout callback with delay after call tick with millis
- Angular async helper > should get Date diff correctly in fakeAsync with rxjs scheduler

On [stackblitz](https://angular.io/generated/live-examples/testing/specs.stackblitz.html) this specs failures too.

## 🔬 Minimal Reproduction

After downloads [Tests](https://angular.io/generated/zips/testing/specs.testing.zip) from [docs](https://angular.io/guide/testing), `npm i` and `npm test`, angular CLI report about errors (see above).

### Expected vs Actual Behavior**

All specs should be passed.

## 🌍  Your Environment
Angular CLI: 7.3.3
Node: 10.14.1
OS: linux x64
Angular: 7.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.3
@angular-devkit/build-angular     0.13.3
@angular-devkit/build-optimizer   0.13.3
@angular-devkit/build-webpack     0.13.3
@angular-devkit/core              7.3.3
@angular-devkit/schematics        7.3.3
@angular/cli                      7.3.3
@ngtools/webpack                  7.3.3
@schematics/angular               7.3.3
@schematics/update                0.13.3
rxjs                              6.4.0
typescript                        3.3.3333
webpack                           4.29.0

### Browser info

Google Chrome

**Comment by futantan** [comment]
Same issue, any update? :)

**Comment by brandonroberts** [comment]
This is on the list of issues to resolve, but other than that no update yet.

**Comment by brandonroberts** [comment]
Fixed via #29256
