### ISSUE TITLE
AppViewManager.getHostElement(): Method name / semantics do not match

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2891]
The `AppViewManager.getHostElement(viewRef: ViewRef)` method implies that the return value is the host element, but the actual return value is the first element of the component's shadow view. 

Issues:
- Name missmatch: host element vs shadow view DOM
- Semantic missmatch: returning the first element, rather then all of the elements in the root of the shadow view.

Proposal:

Remove the API completely, as it is only used in the `DynamicComponentLoader` which needs it to get a hold of the Component.  Instead add the `AppViewManager`'s `getComponentFromView()` which would retrieve the component without the need to go through `ElementRef`

Additionally the code in `DynamicComponentLoader` is incorect

```
  loadAsRoot(typeOrBinding: Type | Binding, overrideSelector: string,
             injector: Injector): Promise<ComponentRef> {
    return this._compiler.compileInHost(typeOrBinding)
        .then(hostProtoViewRef => {
          var hostViewRef =
              this._viewManager.createRootHostView(hostProtoViewRef, overrideSelector, injector);
          var newLocation = this._viewManager.getHostElement(hostViewRef);
          var component = this._viewManager.getComponent(newLocation);

          var dispose = () => { this._viewManager.destroyRootHostView(hostViewRef); };

          // newLocation POINTS TO WRONG LOCATION. Pointing to first shadow child rather then 
          // the host element 
          return new ComponentRef(newLocation, component, dispose);
        });
  }
```

**Comment by tbosch** [comment]
This method is supposed to be used for host views only. I.e. the views that only contain a single element which is the host element of the component. This method is missing an assert statement for `view.type === ViewType.HOST_VIEW`.

Having the `ElementRef` be part of a `ComponentRef` is handy, e.g. for debugging, so a user can easily inspect the underlying dom element via `ElementRef.nativeElement`, or create another component as a sibling via `AppViewManager. getViewContainer(elementRef)`.

**Comment by tbosch** [comment]
I.e. I would vote for not changing this / keeping the ElementRef as the result (although I don't have a strong opinion about the name)

**Comment by mhevery** [comment]
But it does not actually return the `HostElement` It returns the first child of the `HostElement` i.e. the first element of the `ShadowView`. A `ShadowView` can have any number of root elements. So something is not right here.

**Comment by mhevery** [comment]
Also I think that `getNamedElementInComponentView` should take `HostView` rather then `ElementRef`

**Comment by mhevery** [comment]
Also seem like we don't need `DynamicComponentLoader` since we can do all with `AppViewManager`.
