### ISSUE TITLE
Support transpilation for testing browsers that do not support ES6

### ISSUE THREAD

**Issue by benlesh** [angular/angular#28910]
Transpilation is not supported in the karma_web_test_suite, unlike the JSunit test framework. As ES6 is now compulsory for new files, this makes it impossible to use Karma on new projects or actually respect this rule on existing projects using Karma.

https://b.corp.google.com/issues/38508360

**Comment by alexeagle** [comment]
I think this issue is just a placeholder to reference the buganizer one? The conversation there isn't even clear if it's still a problem. Can we close this?

**Comment by benlesh** [comment]
I agree. Let's close this and see how the Buganizer issue shakes out. (It seems to no longer be an issue there)
