### ISSUE TITLE
Providers injected by TestBed with async is undefined

### ISSUE THREAD

**Issue by totszwai** [angular/angular#28929]
# 🐞 bug report

### Affected Package
@angular/core/testing

### Description
Following the example provided here: https://v5.angular.io/guide/testing#cli-generated-tests

I am experiencing in my unit tests where the injected providers are undefined if we uses `async` in `beforeEach`.

## 🔬 Minimal Reproduction
I created a dummy component and a service and try to run the most basic unit test against them. However, when using async, it will fail because the provided service is undefined.

https://angular-fbbgc6.stackblitz.io

## 🔥 Exception or Error
<pre><code>
HeadlessChrome 0.0.0 (Ubuntu 0.0.0) Injected Provider should be defined FAILED
	Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'ng:///DynamicTestModule/DummyComponent_Host.ngfactory.js'. thrown
HeadlessChrome 0.0.0 (Ubuntu 0.0.0): Executed 1 of 3 (1 FAILED) (0 secs / 2.239 secs)
HeadlessChrome 0.0.0 (Ubuntu 0.0.0) Injected Provider should be defined FAILED
HeadlessChrome 0.0.0 (Ubuntu 0.0.0) Injected Provider should be the same FAILED
	Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'ng:///DynamicTestModule/DummyComponent_Host.ngfactory.js'. thrown
HeadlessChrome 0.0.0 (Ubuntu 0.0.0): Executed 2 of 3 (2 FAILED) (0 secs / 2.299 secs)
HeadlessChrome 0.0.0 (Ubuntu 0.0.0) Injected Provider should be the same FAILED
HeadlessChrome 0.0.0 (Ubuntu 0.0.0) Injected Provider should create FAILED
	Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'ng:///DynamicTestModule/DummyComponent_Host.ngfactory.js'. thrown
HeadlessChrome 0.0.0 (Ubuntu 0.0.0): Executed 3 of 3 (3 FAILED) (0 secs / 2.334 secs)
HeadlessChrome 0.0.0 (Ubuntu 0.0.0) Injected Provider should create FAILED
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 1.7.4
Node: 10.14.2
OS: linux x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

@angular/cdk: 5.2.5
@angular/cli: 1.7.4
@angular/material: 5.2.5
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack-bundle-analyzer: 2.13.1
webpack: 3.11.0

</code></pre>

**Comment by alexzuza** [comment]
Try replacing

```
providers: [
  { provide: DummyService }
],
```

with
```
providers: [DummyService],
```

**Comment by vikerman** [comment]
Can't open the stackblitz project. Reopen if still an issue.
