### ISSUE TITLE
ngOnDestroy on `providedIn: 'root'` service not called

### ISSUE THREAD

**Issue by sod** [angular/angular#28927]
angular 7.2.5 - reproduction: https://stackblitz.com/edit/angular-begg91

Issue
When you  call `destroy()` on an application, `ngOnDestroy` on services that are `@Injectable({providedIn: 'root'})`, is never called.

```typescript
@Injectable() // injected in an NgModule
export class ServiceInModule {
    ngOnDestroy() {} // <- working: is called when app is destroyed
}

@Injectable({providedIn: 'root'})
export class ServiceProvidedInRoot {
    ngOnDestroy() {} // <- not working: is never called
}
```

You see here, the constructor of `ServiceProvidedInRoot` is called in both bootstraps ... so it's not reused and should be parse of the livecycle. But `ngOnDestroy` is not called if module is destroyed:

![image](https://user-images.githubusercontent.com/905328/53258045-efbe5500-36cb-11e9-9c96-77f8c1da40bf.png)

This is currently an issue for as as we try to use angular/universal, but we can't tear down objects in services when provided in root.

**Comment by JoostK** [comment]
Thanks for the StackBlitz, that helped in tracking down this issue. I opened PR #28943 to fix it.
