### ISSUE TITLE
Support TypeScript 3.3

### ISSUE THREAD

**Issue by krojew** [angular/angular#28921]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/compiler-cli

### Description
TypeScript 3.3 is out for some time - it would be good to support it.

**Comment by JoostK** [comment]
Angular 8.0 is expected to update to TypeScript 3.3, there's a PR available at #28497.

**Comment by alxhub** [comment]
TypeScript 3.3 support has landed!

**Comment by kbirger** [comment]
In which version?

**Comment by MartinX3** [comment]
Upcoming 8.0
