### ISSUE TITLE
ERROR HttpErrorResponse {headers: HttpHeaders,

### ISSUE THREAD

**Issue by imguccho** [angular/angular#28924]
This typescript code ---

```ts

import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';


@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {

fullname : any;
email : any;
role : any;
typee : any;
password : any;

headers = new HttpHeaders();


  constructor(private httpClient: HttpClient) { 
    
  }

  insertData() {
      this.httpClient.post(
          "http://localhost/SilfraProject/src/app/register/register_insert.php",
          {
              'fullname':this.fullname, 
              'email':this.email,
              'role':this.role,
              'typee':this.typee,
              'password':this.password,

          },
          {
          headers : {
            'Content-Type' : 'application/x-www-form-urlencoded; charset=UTF-8'
          }
          }

      ).subscribe((data) => {
          alert("inserted");
          this.fullname = null;
          this.email = null;
          this.role = null;
          this.typee = null;
          this.password = null;
      });
  }
}

```
This is php code ---

```php
<?php  

header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Credentials: true");
header("Access-Control-Allow-Methods: POST, GET");
header('P3P: CP="CAO PSA OUR"'); // Makes IE to support cookies
header('content-type: text/plain');  
header("content-type: application/x-www-form-urlencoded");
header("Access-Control-Allow-Headers: Content-Type, Authorization, X- 
Requested-With");
header("Access-Control-Max-Age: 172800");
 header("Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept");

include 'dbcon.php';

$data = json_decode(file_get_contents("php://input"),true);
if(count($data) > 0 ) {

    $fullname = mysqli_real_escape_string($connect,$data['fullname']);
    $email = mysqli_real_escape_string($connect, $data['email']);
    $role = mysqli_real_escape_string($connect,$data['role']);
    $type = mysqli_real_escape_string($connect, $data['typee']);
    $password = mysqli_real_escape_string($connect,$data['password']);



    $insert = "INSERT INTO tbl_user values ('','$fullname','$email','$role','$type','$password')";


    if(mysqli_query($connect,$insert)){
      echo "Data inserted";
    } else {
      echo "Data not inserted" . mysqli_error($connect);
    }
}
 ?>  
```

**Comment by imguccho** [comment]
``<?php  

header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Credentials: true");
header("Access-Control-Allow-Methods: POST, GET");
header('P3P: CP="CAO PSA OUR"'); // Makes IE to support cookies
header('content-type: text/plain');  
header("content-type: application/x-www-form-urlencoded");
header("Access-Control-Allow-Headers: Content-Type, Authorization, X- 
Requested-With");
header("Access-Control-Max-Age: 172800");
 header("Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept");

include 'dbcon.php';

$data = json_decode(file_get_contents("php://input"),true);
if(count($data) > 0 ) {

    $fullname = mysqli_real_escape_string($connect,$data['fullname']);
    $email = mysqli_real_escape_string($connect, $data['email']);
    $role = mysqli_real_escape_string($connect,$data['role']);
    $type = mysqli_real_escape_string($connect, $data['typee']);
    $password = mysqli_real_escape_string($connect,$data['password']);



    $insert = "INSERT INTO tbl_user values ('','$fullname','$email','$role','$type','$password')";


    if(mysqli_query($connect,$insert)){
      echo "Data inserted";
    } else {
      echo "Data not inserted" . mysqli_error($connect);
    }
}
 ?>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter
