### ISSUE TITLE
Provide an error message and stacktrace for "Script Error".

### ISSUE THREAD

**Issue by benlesh** [angular/angular#28934]
When there is an error in executing the test script, the error message shows a simple "Script Error".

See https://sponge.corp.google.com/target?id=adfbbeb3-e772-404a-b263-c4edd7c4c621&target=//firebase/datastore/clients/web/testing/integration:minified_integration_tests_chrome-linux as an example.

This usually means someone on the team has to reproduce the issue and involves manual steps in figuring out what is wrong. This has cost our team lots of time in the past and I'm guessing other teams to.

If the error and stacktrace could be provided it would greatly reduce the work needed to figure out what went wrong and make fixing the bug much quicker.

**Comment by vikerman** [comment]
In Karma the logging system works with the browser side sending error messages/stacks using a web socket. If there is a script error which prevents Karma from even bootstrapping there is no way to send a meaningful stack back to the Karma server. 

The workaround is to open a browser locally and load the test and look at the error there.
