### ISSUE TITLE
Fetching data from cloud firestore and unable to render into html component after first time

### ISSUE THREAD

**Issue by ratnabh** [angular/angular#28938]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

I am fetching data from my cloud firestore and rendering in my html component.On my first attempt when i go the component i see my data rendered into html component

.component.ts file

```
import { Component, OnInit, ViewChild } from '@angular/core';
import { ItemsService } from 'src/app/services/items.service';
import { NgForm } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { ProductsService } from 'src/app/services/products.service';
import { Product } from 'src/app/modals/products.modal';

@Component({
selector: 'app-admin-new',
templateUrl: './admin-new.component.html',
styleUrls: ['./admin-new.component.scss']
})
export class AdminNewComponent implements OnInit {
@ViewChild('f') form:NgForm
categories
default="Bread"
constructor(public iservice:ItemsService,private 
prservice:ProductsService,private router:Router,private 
route:ActivatedRoute) { }

ngOnInit() {
this.iservice.getitems().subscribe(items=>{
  console.log(items)   //this is the data fetched from firestore
  this.categories=items

})
}
onsubmit(f){
this.prservice.fetchintocardcomponent(f)
this.router.navigate(['admin/products'])
}

}
```

service file
```
import { Injectable } from '@angular/core';
import 
{AngularFirestoreDocument,AngularFirestore,AngularFirestoreCollection} 
from 'angularfire2/firestore';

import { Observable } from 'rxjs';

@Injectable({
 providedIn: 'root'
})
export class ItemsService {
itemscollection:AngularFirestoreCollection<any>
items:Observable<any[]>

constructor(public afs:AngularFirestore,db:AngularFirestore) { 

this.items=this.afs.collection('categories',ref=>ref.orderBy('name'))
.valueChanges()  

}

getitems(){
  return this.items
}

}
```
Now i render it in html component by

```
<select [ngModel]="default" class="browser-default custom-select" 
 id="category"
 ngModel name="select" required #select="ngModel"
  >

 <option *ngFor="let c of categories" value="{{c.name}}">{{c.name}} . 
 </option>

 </select>
```

So here is the screenshot of what i am getting, it is working fine
 https://ibb.co/PFW6sR9

But after submitting the form when i go to another component by
`this.router.navigate(['admin/products'])`

And then when i return to the same component i do not see the values fetched from firestore being rendered in the html component

Here is the screenshot of my issue https://ibb.co/j5yNChs

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by benlesh** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
