### ISSUE TITLE
NgUpgradeLite throws confusing errors when one uses a downgradeInjectable

### ISSUE THREAD

**Issue by benlesh** [angular/angular#28932]
Technically, NgUpgradeLite does not support downgraded injectables - https://g3doc.corp.google.com/javascript/angular2/examples/ngupgrade/README.md#what-can-be-used-where

However, nothing is preventing one from calling downgradeInjectable and using it with the NgUpgradeLite setup. When that happens the error thrown is:

'Trying to get the Angular injector before bootstrapping an Angular module.'

Without some digging into the stack one doesn't know why and how this is happening.

**Comment by gkalpak** [comment]
Technically, ngUpgradeLite does support downgraded injectables, but [some limitations apply][1].
Maybe we could print that info in the error message, but other than that I don't think there is much we can do.

[1]: https://github.com/angular/angular/blob/81671cea9a2ca677dfcf433b6f3e5a27da944f6e/packages/upgrade/src/common/downgrade_injectable.ts#L48-L60

**Comment by jessicajaniuk** [comment]
We're at EOL for angularjs and ngUpgrade / Downgrade. While this is a bug, we're not going to address fixing it given the EOL status of angularjs.
