### ISSUE TITLE
document pattern for replacing chains of resolves

### ISSUE THREAD

**Issue by benlesh** [angular/angular#28933]
Talking with Jason about resolves that need other resolves as input. For example:

```
            resolve: {
              'a': {...},
              'b': (a) => {...},
            }
```

This pattern is supported by AngularJS routers, but not supported in Angular Router. We need to at least document that limitation and suggest workarounds.

**Comment by gkalpak** [comment]
I assume that by "AngularJS routers" you refer to `angular-route` and `ui.router`. I don't know about `ui.router`, but `angular-route` does not support that (afaik).

**Comment by jenniferfell** [comment]
Thanks. Can you provide information about why this is a hotlist item?

Audience and IA question: Should this be in the Upgrading from AngularJS docs, as that would appear to be the only/primary audience that would make an assumption that this syntax would work and that will need to change their apps as part of migrating/upgrading to Angular? Or is this something readers coming from other frameworks might try...and if so do you have a recommended location for the doc addition? Thanks!

**Comment by jenniferfell** [comment]
Is there an associated technical component, to help us determine the user impact or doc area?

**Comment by kapunahelewong** [comment]
Status: Docs team needs an SME to partner on this one. See above for some good questions.
