### ISSUE TITLE
Why I am getting HttpErrorResponse error in Angular6?

### ISSUE THREAD

**Issue by imguccho** [angular/angular#28948]
register.component.ts

`  constructor(private httpClient: HttpClient) {  }
  insertData() {
      this.httpClient.post(
          "http://localhost/register_insert.php",
          {
              'fullname':this.fullname, 
              'email':this.email,
              'role':this.role,
              'typee':this.typee,
              'password':this.password,

          },

      ).subscribe((data) => {
          alert("inserted");
          this.fullname = null;
          this.email = null;
          this.role = null;
          this.typee = null;
          this.password = null;
      });
  }`  

Here is some screenshots -

![screenshot 500](https://user-images.githubusercontent.com/46741059/53297488-73e81800-3845-11e9-9c77-7f0b2cc5ecc7.png)
![screenshot 501](https://user-images.githubusercontent.com/46741059/53297489-764a7200-3845-11e9-952d-d7febda06cce.png)
![screenshot 502](https://user-images.githubusercontent.com/46741059/53297490-764a7200-3845-11e9-8cd0-67919aebf8aa.png)
![screenshot 503](https://user-images.githubusercontent.com/46741059/53297491-764a7200-3845-11e9-8ba0-b54ddab5b7d5.png)

`

**Comment by cesargomezh** [comment]
You're not clear about what you're doing. According your screenshots, you are requesting via `http://localhost/` backend URL. Isn't it something related with a port, like localhost**:4200**?

**Comment by imguccho** [comment]
because I am two server. I was getting 404 error. After that I have given link of xampp server over there. Now 404 error is gone. But HttpErrorResponse error is getting appeared.

**Comment by mlc-mlapis** [comment]
@imguccho ... simplify your life and try to the same case in Stackblitz demo on https://stackblitz.com. You can use many free JSON mocking servers for reading and writing your data ... and anybody can help you immediately. What you are describing here is just uncompleted and hard to guess what you are really doing on your locale.

**Comment by benlesh** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
