### ISSUE TITLE
Angular documentation example: Angular template reference variable not working as expected

### ISSUE THREAD

**Issue by javatutorials2016** [angular/angular#28946]
# 📚 Docs or angular.io bug report

### Description

Doc Reference: https://angular.io/guide/template-syntax#expression-context

I tried to run the sample code about **template reference variable** and I am expecting the text entered in the input text box been displayed next to it. However, it doesn't work that way. I don't have this variable as viewChild inside the component as it is not mentioned in the Angular doc Page. Could you suggest here what is my mistake or my understanding is incorrect?

### What's the affected URL?**
 https://angular.io/guide/template-syntax#expression-context

### Reproduction Steps**

 app.component.ts

`import { Component } from '@angular/core';

import { Hero } from './hero';

@Component({
  selector: 'app-root',
  template: `

  <h1>{{title}}</h1>

  <label>Type something:
  <input #customerInput>{{customerInput.value}}
</label>
`,
styleUrls:["app.component.css"]
})

export class AppComponent {
  testInput = "Hello"
  title = 'Tour of Heroes';
  recommended = true;

}`

## 📷Screenshot

[Code screenshot:](https://i.stack.imgur.com/6uWvf.png)
[Output:](https://i.stack.imgur.com/F5Grj.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter
