### ISSUE TITLE
Fix CircleCI turnaround time regression via test parallelization

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#28940]
Our critical path in the default_workflow on CircleCI is back up to 25min per run (up from 11min).

We could get it down by turning on parallelization for several of the test jobs:

![screen shot 2019-02-22 at 6 07 42 pm](https://user-images.githubusercontent.com/216296/53280246-c81bbc80-36cc-11e9-8938-98f4d86d657b.png)
[source](https://circleci.com/workflow-run/468202b8-dd9d-4071-8f6e-780423f3cfe5)

`test_docs_examples_ivy` job should be the primary target, optionally followed by others in the 3rd column in the screenshot above that take over >5min to run.

@devversion has already implemented this kind of optimization in the past: 483f8250bf35c6cbc9a0abeac66ab4d7636dde02

**Comment by kara** [comment]
Closed by https://github.com/angular/angular/pull/29103
