### ISSUE TITLE
Render the child route in the parent route

### ISSUE THREAD

**Issue by mohammedzamakhan** [angular/angular#28950]
# 🚀 feature request

### Relevant Package
@angular/router

### Description
I want to keep the parent child relationship in the routes (because I am using it for the breadcrumbs) in the application, but I want the child to be loaded in the router-outlet where the parent is mounted.

Example issue:
https://stackblitz.com/edit/angular-bpga5a?file=src%2Fapp%2Fapp.component.html

### Describe the solution you'd like
If I used outlet name for the child, and assign it to the router outlet where the parent is mounted, then it should work

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by Bigless27** [comment]
Much needed!
