### ISSUE TITLE
Drag item from mat-sidenav over to mat-sidenav-content

### ISSUE THREAD

**Issue by torbgy** [angular/angular#28955]
Hi!

I'm trying to drag a picture from the mat-sidenav into the mat-sidenav-content area where it will be placed (drag with copy function). I thought that simply adding drag to a div element in sidenav would make it work, but I think there is some mix up with the z-index, that i can't figure out. The dragged element goes underneath the content area

stackblitz example:
https://stackblitz.com/edit/simulator

sidebar.component.html:
```
<mat-sidenav-container class="example-container">
  <mat-sidenav #sidebarLeft mode="side" opened="true" class="sidebar" fixedInViewport="false">
    <mat-list class="comp-groups">
      <mat-list-item *ngFor="let section of complist.sections">
        <h4 matLine (click)="showComp(section)">{{section.name}}</h4>
      </mat-list-item>
    </mat-list>
		<div class="component-list" *ngIf="selectedCompList">
      <mat-list-item *ngFor="let subsection of selectedCompList.subSections">
        <h4 mat-line>{{ subsection.name }}</h4>
        <div mwlDraggable 
        dropData="{{subsection.name}}"
        dragActiveClass="drag-active"
        [ghostDragEnabled]="true"
        [showOriginalElementWhileDragging] ="true"
        [dragSnapGrid]="snapping"
        (dragging)="dragging($event)">
        <img id="icon" src={{subsection.icon}}/>
        </div>
      </mat-list-item>
		</div>
  </mat-sidenav>
  <mat-sidenav #sidebarRight mode="side" opened="true" class="rightSidebar" fixedInViewport="false" position="end">
  <app-sidebar-right></app-sidebar-right>
  </mat-sidenav>
  <mat-sidenav-content class="workspace">
    <app-toolbar class="toolbarRow"></app-toolbar>
    <app-content class="contentContainer" mwlDroppable
  
  (drop)="onDrop($event)"
  dragOverClass="drop-over-active"
  (dragOver)="dragEnter($event)"
  (dragLeave) = "dragLeave($event)"
  
  ></app-content>
  </mat-sidenav-content>
</mat-sidenav-container>
```

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by torbgy** [comment]
Thanks for a quick response, sorry for the inconvenience
