### ISSUE TITLE
`scrollToAnchor` in BrowserViewportScroller fails with some fragments

### ISSUE THREAD

**Issue by axelboc** [angular/angular#28960]
# 🐞 bug report

### Affected Package

The issue is caused by packages @angular/common and/or @angular/router when the router is configured to scroll to anchors with `anchorScrolling: 'enabled'`.

### Description

When attempting to scroll to an anchor using the URL's fragment, the `BrowserViewportScroller` throws `SyntaxError: The string did not match the expected pattern.`

The error seems to come from this line : https://github.com/angular/angular/blob/7.2.6/packages/common/src/viewport_scroller.ts#L109

`querySelector('#<id>')` requires `<id>` to be a valid CSS identifier -- i.e. one that doesn't start with a number or a special character like `_`. The HTML5 spec, however, is not as strict in regard to element identifiers, so there's no harm in wanting to navigate to `#123` in order to scroll to an element with `id="123"`.

The fix should be as simple as replacing `querySelector()` with `getElementById()`.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-issue-repro2-rmyyfq

## 🔥 Exception or Error
In my project, I see the following:

<pre><code>
SyntaxError The string did not match the expected pattern. 
    [native code] querySelector
    node_modules/@angular/common/fesm5/common.js.pre-build-optimizer.js:5736:61 scrollToAnchor
    node_modules/@angular/router/fesm5/router.js.pre-build-optimizer.js:5304:58 
    ...
</code></pre>

On StackBlitz, I get `ERROR DOMException: "'#123' is not a valid selector"`. The stacktrace isn't as clear, so not sure it comes from the same place. It's definitely the same cause, though.

## 🌍  Your Environment

**Angular Version: 7.2.0**

**Comment by squelix** [comment]
I have the same issue in my project :/

**Comment by trotyl** [comment]
Closed by https://github.com/angular/angular/pull/29577?

**Comment by trotyl** [comment]
The original issue here has already been fixed, can be checked on [updated repro](https://stackblitz.com/edit/angular-issue-repro2-8j6qcd?file=src%2Fapp%2Fapp.component.ts). (fixed version is 7.2.12)

**Comment by axelboc** [comment]
@trotyl sorry for not getting back to you sooner. Unfortunately, the fix you mention is not satisfactory, as the fallback for `CSS.escape()` is not complete -- for instance, it doesn't deal with anchors that start with numbers.

I would recommend reverting the commit and using `getElementById` like in your PR. The `name` attribute selector works fine as long as the value is quoted and doesn't contain quotes, which can be specifically escaped with a simple `replace` - e.g. 

```js
document.body.querySelector("[name='0\=[]#']"); // => null
```

**Comment by trotyl** [comment]
I generally agree with you, but you'll still need to argue with Angular team on your own.

**Comment by petebacondarwin** [comment]
@axelboc - when I looked at the repro provided by @trotyl above (https://stackblitz.com/edit/angular-issue-repro2-8j6qcd) I can see that there is an anchor starting with number and it works fine (at least on Chrome OS/X).  Can you clarify what is still missing?

**Comment by axelboc** [comment]
Wow, this was a while ago, but looks like I was wrong: `CSS.escape` does handle IDs that start with numbers, you're right. The use case I mentioned works fine now, so feel free to close the issue.

---

For what it's worth, looking at the [implementation of `scrollToAnchor` on `master`](https://github.com/jasonaden/angular/blob/master/packages/common/src/viewport_scroller.ts#L112), which doesn't seem to have changed since #29577, I still find it silly to query the element with `this.document.querySelector(``#${anchor}``)`, when this could be done with `getElementById` without having to first escape the `anchor` (and risk forgetting to escape some characters...)

Why not attempt `getElementById` first, and only then, if it doesn't find anything, escape the `anchor` and try with `querySelector(``[name='${anchor}']``)`? This solution would even simplify the escaping regex (cf. my previous comment).

**Comment by petebacondarwin** [comment]
@axelboc - thanks for the response. I am going to close this issue.
Unfortunately I don't have the time right now to look into refactoring the code as you suggest.
But if you were interested in proposing a PR for it, I would gladly review and then help you get it merged.
