### ISSUE TITLE
HttpClient Forward Requests not intercepted

### ISSUE THREAD

**Issue by driverpt** [angular/angular#28966]
# 🐞 bug report

### Affected Package
@angular/common/http

### Is this a regression?
No

### Description
When HttpClient Requests are forwarded (via HTTP 301/302), the requests are not going through the Interceptor. Which is causing AWS S3 GET Request to throw HTTP 403 due to Authorization Header being set.
We are making an HTTP Request to a REST API (Authenticated) and we're getting a redirect to an AWS S3 Bucket Link Signed URL and the Forwarded Request should have been intercepted by the Interceptor and not put the Authorization Header.

## 🔬 Minimal Reproduction
Create an HTTP Client instance, perform a GET to a REST Service with Authentication (JWT) in custom headers. And make the service redirect HTTP 302 to an S3 Bucket.

## 🔥 Exception or Error
We get 403 Forbidden due to Authentication Header being set (in case of AWS).

## 🌍  Your Environment

**Angular Version:**

<pre><code>
7.2.4
</code></pre>

**Comment by driverpt** [comment]
Can someone give me an Update on this?

**Comment by pkaufi** [comment]
Browsers handle redirects transparently and automatically, so there's no way to intercept your 301/302 requests.
See: [W3C standard for the XMLHttpRequest object](https://dvcs.w3.org/hg/xhr/raw-file/tip/Overview.html#infrastructure-for-the-send%28%29-method)

> 2. If the source origin and the origin of request URL are same origin transparently follow the redirect while observing the same-origin request event rules.

**Comment by alxhub** [comment]
@pkaufi is correct; closing as this is not an issue with HttpClient interceptors.
