### ISSUE TITLE
Get rid of unnecessary spacing around MatFormField when no label or hint

### ISSUE THREAD

**Issue by AdriannaWenz** [angular/angular#28970]
# 🚀 feature request

### Relevant Package
@angular/material/form-field
@angular/material/input

### Description
There is extra space provided for the mat-label, even when there is no mat-label. This makes the text uncentered in the input. Additionally, there is extra padding below the input box for the mat-hint, even when there is no mat-hint. 
  
![extraspace](https://user-images.githubusercontent.com/20160721/53376914-e96ee980-3914-11e9-9710-adc1fde62f81.png)

### Describe the solution you'd like
If there is no label or hint, set their paddings to 0, or if they could be removed altogether that would be even better.

### Describe alternatives you've considered
Current workarounds would be to use ng-deep to change the padding for these elements.

**Comment by ericmartinezr** [comment]
Hey @AdriannaWenz would you mind openind this issue in material's repo https://github.com/angular/material2 ? 👍
