### ISSUE TITLE
feat(http): support use by AngularJS 1.x applications

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2897]
In order to ease the transition from AngularJS 1.x apps to Angular 2, the http module should be possible to be used in AngularJS 1.x applications, though not necessarily as a drop-in replacement for `$http`.

Some considerations:

 * DI and module systems are different, but the current architecture should allow for easily creating a module and service for http. #2680 will make this easier.
 * There is currently no notion of global interceptors or transformers, though these could be encapsulated in an AngularJS 1.x service/provider.
 * The new library is based on observables instead of promises. The observable should be easily converted to a promise as a convenience, but the encouraged path should be to use the observable.
 * Http doesn't hook into AngularJS 1.x's digest loop.
 * The test lib would also need to be bundled separately and made to work with 1.x.
 * Where should 1.x-friendly documentation live?

**Comment by robwormald** [comment]
This issue was moved to angular/http#70

**Comment by robwormald** [comment]
This issue was moved to angular/http#72
