### ISSUE TITLE
ng_package only marks main @angular packages as external

### ISSUE THREAD

**Issue by jbedard** [angular/angular#28971]
# 🐞 bug report

### Affected Package
`@angular/bazel`

### Description
Currently `ng_package` [hardcodes a list](https://github.com/angular/angular/blob/8.0.0-beta.5/packages/bazel/src/ng_package/ng_package.bzl#L61-L95) of external packages to not include in the package being built. This list is a little arbitrary making it hard to tell when this must be done manually or if `ng_package` does it for you etc. It should probably either do nothing or be replaced with something more generic such as anything in `node_modules` or `dependencies` from `package.json`.

The error message is also quite cryptic and appears to be very angular/component specific. For example when depending on `@angular/material/x` I got an error about an ngfactory file file missing from an indirect dependency:
```
[!] (Plugin at position 3 plugin) Error: Could not resolve import '@angular/cdk/scrolling/virtual-scroll-viewport.ngfactory' from '...long tmp dir path.../bazel-out/darwin-fastbuild/bin/<path>/npm.es6/external/angular_material/src/cdk/overlay/overlay-container.js'
```

## 🔬 Minimal Reproduction
A basic repro showing the issue when depending on material: https://github.com/jbedard/angular-bazel-examples/tree/ng_package-material, running `bazel build //ui:npm` produces the error.

In this case it can be fixed quite easily by just adding:
```
   globals = {
       '@angular/material/button': 'ng.material.button',
       '@angular/material/icon': 'ng.material.icon',
   }
```
But that doesn't seem obvious based on the error message, and isn't clear why this one is required but something such as `@angular/animations` is not required.

**Comment by jbedard** [comment]
FYI @kyliau

**Comment by alxhub** [comment]
Closing as obsolete - the Bazel builder and associated CLI functionality are deprecated and no longer supported.
