### ISSUE TITLE
Handling of Access token in Angular application

### ISSUE THREAD

**Issue by nikhil4326** [angular/angular#28975]
Hello, I am using angular 5 version with access token for unauthenticated/anonymous user.
I have some question to handle the token issue in angular.

I am calling token rest API from app.component.ts to get access token. setting it into observable object so that I can get access token in interceptor to add token in request headers of rest API call.
App.component.ts
```
export class AppComponent implements OnInit {
ngOnInit() {
		this.tokenService.generateAccessToken().subscribe(
            (data: any) => {
                this.tokenService.setAccesToken(data.access_token);
            } );
}
}
```

Token.service.ts
```
@Injectable()
export class UserService {
public bearerToken = new BehaviorSubject<string>(this.defautToken);
public currentBearerToken = this.bearerToken.asObservable();
public setAccesToken(accessToken: string){
    		this.bearerToken.next(accessToken);
  }
	
Public getAccessToken () {
Return ….
}

public generateAccessToken() {
......
return token;
}
}
```

When we launch/load application in browser, Children component of app.component  start rendering. children component includes Appabr, side bar, body, footer components. Children components also have the rest calls to get data which is used to render on screen.
```
export class ChildComponent implements OnInit {
	public ngOnInit() {
	getdata() //rest call
	}

}
```
We have Interceptor which add the access token in the request header.
```
export class ReachHttpInterceptor implements HttpInterceptor {
intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
	const token = getToken();
let authReq = req.clone();
const bearer = 'Bearer ' + token;
authReq = req.clone({ headers: req.headers.set('Authorization', bearer) });
return next.handle(authReq)….
}
}
```
When children components access rest API to get data, access token is not received from app.component.ts due to which rest API fails with 401 status code.
I understand the reason that children components of app component won’t wait to execute the init() function of app.component.ts
Please let me know what the best place is to have token API call code?
Is BehaviorSubject subject good to store token values?
can we stop child component from rendering till we receive token?

Thanks in Advance.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
