### ISSUE TITLE
Have a "global" component registry of all entry components.

### ISSUE THREAD

**Issue by andreElrico** [angular/angular#28977]
# 🚀 feature request

### Description

In order to render dynamic components we will somehow need to get hold of the `component-TYPE` at some point.

Let's imagine a situation where the "backend" tells us what component should be rendered in form of a returned `string` value.

Somehow this `string` need to be resolved into a `component-TYPE`.

Solutions on SO suggest creating a map, something like the following:

```
const classesMap = {
  "AComponentString": AComponentType,
  "BComponentString": BComponentType
}
```
here are a couple SO solutions: 
[SO1](https://stackoverflow.com/questions/49168240/angular-5-instantiate-a-component-from-its-name-as-a-string)
[SO2](https://stackoverflow.com/questions/40222579/angular-2-resolve-component-factory-with-a-string)
[SO3](https://stackoverflow.com/questions/40115072/how-to-load-component-dynamically-using-component-name-in-angular2)

When a more dynamic general approach is chosen and we loop through the factories which are declared private, things are about to become very adventurous.

In order to use dynamic components effectively throughout our apps, we need a reliable and complete stringComponent-MAP. This MAP should be updated/completed  when lazy modules with entryComponents are loaded.

### Describe the solution you'd like

So my suggestion is to use [entryComponents](https://angular.io/api/core/NgModule#entryComponents) directly to create such a `MAP`.

something like this could be possible:

```
@NgModule({
...
   entryComponents: [{"AComponentString": AComponentType}, {"BComponentString": BComponentType}, OtherComponentTypeThatWillNotBeAddedToTheMAP]
 ...
})
```

maybe through a decorator?

```
@NgModule({
...
   entryComponents: [@add2Map('AComponentString') AComponentType, @add2Map('BComponentString') BComponentType, OtherComponentTypeThatWillNotBeAddedToTheMAP]
 ...
})
```
Maybe the `MAP` could be accessible through a `StringComponentResolver` class that is somewhat analogous to `ComponentFactoryResolver`.

### Describe alternatives you've considered

+ Creating a MAP by hand feels very unsatisfying.
+ Creating a MAP by looping through private properties feels like not a longterm and save solution.

**Comment by mlc-mlapis** [comment]
@andreElrico ... we use a map defined in each lazily loaded module which can be taken later from a module instance or you can register it outside using the constructor body.
```
export default class ProductSet001Module {

	cmps: Map<{}, {}> = new Map();

	constructor() {
		this.cmps.set('product-set-001', ProductSet001Component);
	}
}
```

**Comment by andreElrico** [comment]
thank you @mlc-mlapis 
+ do you have any working reference/ repo where a dynamic global Map is in action?
+ what do you mean by `we use`. Is there already a default implementation or do you mean `we _could_ use` ... ?

**Comment by mlc-mlapis** [comment]
@andreElrico ... `we` as in our projects we use it. The dynamic global Map is just a simple property in a singleton service where you register all components ... in our cases, those are located only in lazily loaded modules, so we load them first and then we register their components in that registry.

**Comment by alexzuza** [comment]
See also https://github.com/angular/angular/issues/28826

**Comment by mhevery** [comment]
We will not be doing a global registry because that would prevent AoT from having any sort of locality. Sorry, but I am going to close this issue in the most polite way.
