### ISSUE TITLE
location.reload(true) not working in angular 6

### ISSUE THREAD

**Issue by puneetkjain25** [angular/angular#28974]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by mlc-mlapis** [comment]
@puneetkjain25 ... it's not supposed that you should reload a full page in Angular. Why do you do it? If you need it from another whatever reason just use pure JS `Window.location = '...'`

**Comment by puneetkjain25** [comment]
@mlc-mlapis My requirement is to reload the angular 6 application so everything should serve again from server. **location.reload()** done only nomal reload(ctrl+R). I want hard reload(Ctrl+Shift+R).

**Comment by mlc-mlapis** [comment]
@puneetkjain25 ... so you mean with cache clearing? What are you doing? How is it related to Angular?

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by puneetkjain25** [comment]
@mlc-mlapis 
I want to load my configuration outside the project. I have placed it in asset/data/config.json.
After making build it placed in dist/asset/data/config.json.

I am loading it through get request.
this.http.get("assets/data/config.json")

After logout i am redirecting it to login page and loading the application again by following code.

     this.zone.run(() => {
          setTimeout('location.reload(true)', 2000);     
    });
    this.router.navigate(["/authentication/login"],{queryParams: {refresh: new Date()}});

It only reload from cache not from server.
