### ISSUE TITLE
Remove interfaces from generated reflector data

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#2898]
This should be done _after_ generated change detectors are feature-complete.

## Background

Currently we use transformers with dynamic change detector, because generated change detectors are still buggy. Dynamic change detector needs to look up interfaces reflectively. As a temporary measure, https://github.com/angular/angular/pull/2328 adds these interfaces to the reflector. However, when generated change detectors are finished this information in the reflector becomes redundant and only increases code size. We should eventually remove it.

**Comment by naomiblack** [comment]
@jakemac53 can you own this one? It's blocked until change detection is complete so putting it in alpha-32.

**Comment by jakemac53** [comment]
I will be gone for the alpha-32 milestone but Tim will be back so assigned him

**Comment by kegluneq** [comment]
@yjbanov, is this still feasible given that we're using `interfaces` to implement `hasLifecycleHook` and its derivative features also (see a9a552c)? Is there a thought to implement lifecycle methods differently?

**Comment by sigmundch** [comment]
@kegluneq - unfortunately can't think of any other way.

**Comment by yjbanov** [comment]
@sigmundch is there a reason for the lack of support for this at the language level? It seems the amount of runtime information should be the same whether you support `obj is SomeInterface` (which is supported) or `SomeInterface.isAssignableFrom(otherType)`.

**Comment by sigmundch** [comment]
There has been some discussions on it, for example see: https://github.com/dart-lang/sdk/issues/23764

As for the amount of runtime information, it depends a lot on the representation we choose. In dart2js we don't represent the subtyping relations explicitly, we just store on each object whether it is of certain type (the `.$isFoo` properties). So the amount of information would be different to fully support this. That being said, @rakudrama had plans for moving to a different representation for checked mode, which could potentially be exactly what you need for this

**Comment by tbosch** [comment]
#6270 will remove the reflector and with this solve this issue as well.
