### ISSUE TITLE
Please up the experience of reading about docs 

### ISSUE THREAD

**Issue by marshalflow** [angular/angular#28980]
# 📚 Docs or angular.io bug report

### Description

  I really don't like the feeling when I read the docs of angular, font is small,  maybe 16px is better, and color #34495e looks like good and more fashion. even thought angular is so powerful, it deserve to have a more fashion design for the docs

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter

**Comment by benlesh** [comment]
Just to follow up with something that's not a canned response: That is to say, this issue is too subjective and vague to be actionable. Perhaps file an issue with specific problems and suggestions on how you'd fix those problems.

**Comment by marshalflow** [comment]
it's just my feeling, maybe it's subjective opinion, 
anyway, I really hope you will considerate  the things that document of angular should be re-design for better reading.
