### ISSUE TITLE
ng_package may generate imports to external packages bypassing the globals config

### ISSUE THREAD

**Issue by jbedard** [angular/angular#28991]
# 🐞 bug report

### Affected Package
`@angular/bazel`

### Description
`@Injectable`s compiled using `ng_package` may contain generated imports referencing external libraries. Normally external libraries would be put in the `ng_package` `globals` so they are not included in the package, but the generated imports might unexpectedly reference sub-paths of those libraries not listed in `globals`. This could a) cause external things to be included in the package b) cause a compilation error if any components are referenced by those generated imports because the `ngfactory` files are excluded (see below or repro)

## 🔬 Minimal Reproduction
https://github.com/jbedard/ng_package-material, specifically https://github.com/jbedard/ng_package-material/commit/6dbe9da746f463a8e519272c5d4e8c2a9e8dba99

## 🔥 Exception or Error
```
[!] (Plugin at position 3 plugin) Error: Could not resolve import '@angular/cdk/scrolling/virtual-scroll-viewport.ngfactory' from '...long tmp dir path.../bazel-out/darwin-fastbuild/bin/<path>/npm.es6/external/angular_material/src/cdk/overlay/overlay-container.js'
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>7.1</code></pre>

**Comment by alxhub** [comment]
Closing as obsolete - the Bazel builder and associated CLI functionality are deprecated and no longer supported.
