### ISSUE TITLE
Cookie not set in browser from HTTPS response

### ISSUE THREAD

**Issue by whiztestapp** [angular/angular#29001]
Cookie set in browser automatically at client side if client and server on same domain for example **https:example.com** and not set cookie if client and server is on different domain like client is on domain https://sub1.example1.com and server is on domain https://sub2.example2.com

Please refer following link for more details: 
[https://stackoverflow.com/questions/54898549/cookie-not-set-in-browser-from-https-response](url)

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
