### ISSUE TITLE
Tree Shaking for NgModule imports

### ISSUE THREAD

**Issue by bhaidar** [angular/angular#29005]
# 🚀 feature request

### Description
Can tree shaking work on the ngModule imports so that any imported module not being used in the app to get removed?

**Comment by pkozlowski-opensource** [comment]
Not sure what you mean... What matters are directives and providers contained in modules and those should be tree-shaken. If this is not the case please provide a minimal reproduce scenario.

**Comment by bhaidar** [comment]
Hi @pkozlowski-opensource For instance, when importing Angular Material modules inside "imports" of the AppModule. I am not using all those modules, what will happen, are they all going to be bundled in production? 

Thanks

**Comment by pkozlowski-opensource** [comment]
> I am not using all those modules, what will happen, are they all going to be bundled in production?

If you are using angular-cli only the actually used code should be part of the production bundle. We've got a build optimiser that takes care of this. If you see not-used code being retained than please open an issue with a minimal reproduce scenario in https://github.com/angular/angular-cli
