### ISSUE TITLE
In the Di in Action doc, what does Storage service mean ?

### ISSUE THREAD

**Issue by bandhavya** [angular/angular#29000]
In storage.service.ts file, we see that InjectionToken<Storage>
and also in the constructor a dependency is added with type as Storage 
constructor(@Inject(BROWSER_STORAGE) public storage: Storage) {}

where is this Storage coming from ? there is no import for this.

**Comment by pkozlowski-opensource** [comment]
I _guess_ you are reading through this: https://angular.io/guide/dependency-injection-in-action ?
If so I _think_  that `Storage` refers to https://developer.mozilla.org/en-US/docs/Web/API/Storage and as such it doesn't need to be imported.

I will leave this one open for the documentation team so see if it needs further clarification.

**Comment by jbogarthyde** [comment]
There is already a reference to the `localStorage` browser API in the intro to the example - "The following example uses an `InjectionToken` to provide the [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) browser API as a dependency in the `BrowserStorageService`."

After the example, it further explains: "The `factory` function returns the `localStorage` property that is attached to the browser window object."

I think the surrounding text adequately explains where the Storage service is coming from.

**Comment by jenniferfell** [comment]
Closing. It sounds like:
* Storage is a standard web API thing
* And the doc already has a link to the localStorage web API info
Thanks, everyone!
