### ISSUE TITLE
Provide an easy way to configure new pipes

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#2901]
Currently pipes are global and are not easily configurable. We need to make them scoped to a component and provide a way to easily configure them.

Proposal:

```
@Component({
  viewInjector: [
		 bind(Pipes).toFactory(Pipes.append({
		 		async: [newAsyncPipe]
		 })
  ]
})
```

**Comment by jeffbcross** [comment]
@btford and @matsko heads up that we're renaming `PipeRegistry` to `Pipes`. What do you think of changing `RouteRegistry` to `Routes`?

**Comment by matsko** [comment]
Works for me.

**Comment by btford** [comment]
I think `RouteRegistry` is a better name than `Routes` since there are so many class names that already have `Route` in them. But there may be a better name for `RouteRegistry`; we'd have to chat some to decide.
