### ISSUE TITLE
@hostListener does not work with IOS

### ISSUE THREAD

**Issue by Rutvik17** [angular/angular#29013]
I have a custom dropdown component and i'm calling that component in a reactive form. The dropdown does not close on ipad or iphone on click outside. It works fine with mouse click and on android devices.
In the dropdown html i have 
(document:click)="onOutsideClick($event)"
and i'm closing the dropdown with that function. I also tried 
@HostListener('document:click', ['$event'])
  onClickOutside(event: mouseEvent) {
    if (!this.el.nativeElement.contains(event.target)) {
      this.showMenu = false;
    }
  }
the dropdown still does not close on tap outside on ipad or iphone. Is there away to listen to touch events on IOS devices

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by kiran8827** [comment]
@Rutvik17 did you get any solution?

**Comment by Rutvik17** [comment]
@kiran8827 Yes, 
@HostListener('document:touchend', ['$event']) 
Use the document:touchend event.

**Comment by kiran8827** [comment]
@Rutvik17 thanks for your reply, i already tried this "document:touchend" works for android not for IOS, if you have any other solution plz let me know?

**Comment by kiran8827** [comment]
got it working, used @HostListener('document:mousedown', ['$event'])
thanks @Rutvik17
