### ISSUE TITLE
Korean culture specific AM/PM text isn't coming for formatted time

### ISSUE THREAD

**Issue by parthsw** [angular/angular#29025]
# 🐞 bug report

### Affected Package
The issue is caused by an incorrect behavior of formatDate function available inside @angular/common package. This is specific to Korean culture.

### Description
We've written a custom pipe to represent time based on the selected language & format. One of the scenario where function is not behaving properly is as follow;

- If a combination of Korean language( ko, ko-KR cultures) and 12 hour format('mediumTime' or 'hh:mm:ss a') is selected then it is not showing AM/PM in Korean culture. It simply prints output as **'PM 6:02:16'** , whereas, the expected output is **'오후 6:02:16'** 

If you set the locale as German then it properly converts the AM/PM.

I've verified that findLocaleData() for 'kr' culture has relevant data available, however, it is returning AM-PM instead of culture related values.

## 🔬 Minimal Reproduction
Here is a reproduction of above mentioned [issue](https://stackblitz.com/edit/angular-issue-repro2-nmw5gc).

## 🌍 Environment
**Angular Version:**
<pre><code>
Angular CLI: 7.1.1
Node: 10.14.1
OS: win32 x64
Angular: 7.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.6
@angular-devkit/build-angular      0.10.6
@angular-devkit/build-ng-packagr   0.10.7
@angular-devkit/build-optimizer    0.10.6
@angular-devkit/build-webpack      0.10.6
@angular-devkit/core               7.0.6
@angular-devkit/schematics         7.1.1 (cli-only)
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.6
@schematics/angular                7.1.1 (cli-only)
@schematics/update                 0.11.1 (cli-only)
ng-packagr                         4.4.5
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.19.1
</code></pre>

**Comment by trotyl** [comment]
It's expected, `a` stands for **Abbreviated Day Period**, instead `aaaa` is for **Widen Day Period**, which is what you need. The formats can be found in [`DatePipe`](https://angular.io/api/common/DatePipe#custom-format-options) API doc.

The content is specified as `AM`/`PM` in Abbreviated/Narrow and `오전`/`오후` in Widen [per CLDR data](https://github.com/unicode-cldr/cldr-dates-full/blob/6227cc013572391189a63350cec2544f0e0b3624/main/ko/ca-generic.json#L224-L258).

**Comment by parthsw** [comment]
Thank you for the information. 

However, as per my understanding, 12-hour format is expressed as **AM 02:10:11** instead of **02:10:11 AM** in Korean culture. 

I don't think that angular handles this culture specific scenario internally. Please let me know if I'm missing something.

**Comment by trotyl** [comment]
> However, as per my understanding, 12-hour format is expressed as AM 02:10:11 instead of 02:10:11 AM in Korean culture.

As what I can see, it indeed renders `AM 02:10:11` for `'mediumTime'` in [the StackBlitz provided above](https://stackblitz.com/edit/angular-issue-repro2-nmw5gc?file=src%2Fapp%2Fapp.component.ts), but if you specify the format manually then it's based on your own format.
