### ISSUE TITLE
In forms, removing from array breaks html [disabled]="!formid.form.valid" tag

### ISSUE THREAD

**Issue by lucascrandle** [angular/angular#29027]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/forms

### Is this a regression?

 No, this did not work with a previous version that I found. I tried upgrading to 7.2.6 but the issue is still present.

### Description

When using dynamic object arrays for forms, using splice to remove an object from the array at any point other than the last element, causes the form.valid property to break in the html tag, and it always returns false.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-dynamic-form-builder-ujdbsi

## 🔥 Exception or Error
No Error Present

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 6.2.6
Node: 10.13.0
OS: win32 x64
Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.8.6 (cli-only)
@angular-devkit/core         0.8.6 (cli-only)
@angular-devkit/schematics   0.8.6 (cli-only)
@schematics/angular          0.8.6 (cli-only)
@schematics/update           0.8.6 (cli-only)
rxjs                         6.2.2 (cli-only)

</code></pre>

**Anything else relevant?**
Tried in firefox and chrome, same issue.

**Comment by kara** [comment]
@lucascrandle We don't yet support dynamic names for `ngModel`. We have an existing feature request for that [here](https://github.com/angular/angular/issues/20546) if you'd like to track it.

In the meantime, a common workaround is to use `trackBy`:

https://stackblitz.com/edit/angular-dynamic-form-builder-n1pxng?file=app%2Fapp.component.ts

**Comment by lucascrandle** [comment]
That fixed the issue, thanks @kara !
