### ISSUE TITLE
Services provided implicitly vs explicitly behave differently

### ISSUE THREAD

**Issue by kapunahelewong** [angular/angular#29038]
# 🐞 bug report

### Affected Package

 The issue is caused by providing services explicitly vs implicitly in lazy loaded modules.

### Is this a regression?

 No

### Description

 A clear and concise description of the problem...

`@NgModule().providers` behaves differently than `@Injectable().providedIn` when providing services in lazy loaded modules.

## 🔬 Minimal Reproduction

[https://stackblitz.com/edit/circular-module-undefined](https://stackblitz.com/edit/circular-module-undefined)

## 🔥 Exception or Error
<pre><code>

Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[CupcakeComponent -> CupcakeService]: 
StaticInjectorError(Platform: core)[CupcakeComponent -> CupcakeService]: 
NullInjectorError: No provider for CupcakeService!
Error: StaticInjectorError(AppModule)[CupcakeComponent -> CupcakeService]: 
StaticInjectorError(Platform: core)[CupcakeComponent -> CupcakeService]: 
NullInjectorError: No provider for CupcakeService!
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

 7

</code></pre>

**Anything else relevant?**

**Comment by mhevery** [comment]
The issue is that it is not possible to have tree-shakable providers with components. Consider this setup:

`my-module.ts`
```typescript
imports {MyComponent} from './my-component';

@NgModule({
  declarations: [MyComponent]
})
class MyModule {}
```

`my-component.ts`
```typescript
import {MyService} from './my-service';
@Directive(...) 
class MyComponent {
  constructor(myService: MyService) {}
}
```

`my-service.ts`
```typescript
import {MyModule} from './my-module.ts';

@Injectable({
  providedIn: MyModule; // <<<< This should support forwardRef
})
class MyService {}
```

In the above set up there is a circular reference between the three files. As a result at the time of `MyService` evaluation the `MyModule` is `undefined`. To fix this the decorator should  thrown an error if `undefined` is passed in, and it should support `forwardRef`.

**Comment by alxhub** [comment]
Closing as obsolete - the repro stackblitz is no longer accessible, and Misko's comment implies the real problem here was a circular reference.
