### ISSUE TITLE
feat(http): automatically set request Content-Type header based on body type

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2903]
This is specific to the XhrBackend implementation, based on request body types for which it doesn't automatically set Content-Type headers.

When forming "write" requests inside of `http.request`, the "Content-Type" header should be set for certain request body types that the user agent doesn't implicitly set, using the body extraction steps described here: https://fetch.spec.whatwg.org/#concept-bodyinit-extract

 * JSON -> application/json
 * URLSearchParams -> application/x-www-form-urlencoded;charset=UTF-8
 * Blob -> If blob has set "type" property, set to its value

This should also be documented.

Will leave `FormData` up to the user-agent, so it can set the appropriate boundary.

**Comment by mgechev** [comment]
I can take this one.

Do we have to implement it only for `http.request`? I see that `http.post`, `http.patch`, `http.put` accept strings as `body` but don't you think they should be extended to work with other data types as well?

**Comment by robwormald** [comment]
This issue was moved to angular/http#69

**Comment by robwormald** [comment]
This issue was moved to angular/http#71
