### ISSUE TITLE
chore(http): convert RequestMethods to const list

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2904]
I made the `RequestMethodsMap` class during the big refactoring to support Dart, so that it could be declared at the top-level of the enums module. The class takes an enum (integer) and returns the corresponding enum's name. Like `requestMethodsMap.get(0)// -> 'GET'`But it should be able to be a constant and provide the same usefulness for converting `RequestMethods` enum values to strings and vice versa, with less overhead

**Comment by rixrix** [comment]
@jeffbcross I'd like to work on this easy task but would you be able to elaborate a little bit as to what you really want and maybe some hints (?). Would you like to get rid of using `requestMethodsMap` when requestmethods becomes a constant list ? and would you have to those constants be in separate file called `constants.ts` ? thanks

**Comment by jeffbcross** [comment]
Hey @rixrix, thanks for chiming in! Sorry I didn't see the notification for your comment sooner. 

This actually is a little easier now that Dart support has been dropped altogether for the `http` module.

So to fix this issue, you can just remove the `RequestMethodsMap` class from enums.ts, and then change all occurences of `requestMethodsMap.getMethod(someMethod)` to just use the typescript-provided reverse enum lookup like so `RequestMethods[someMethod]`. 

Example Before
```typescript
requestMethodsMap.getMethod(0);
```

Example After
```typescript
RequestMethods[0];
```

It looks like the files you'd need to change are 
angular2/src/http/
 * enums.ts
 * backends/jsonp_backend.ts
 * backends/xhr_backend.ts

Let me know if I can provide any more info.

**Comment by rixrix** [comment]
Hi Jeff, thanks I'll look at that today. cheers

**Comment by rixrix** [comment]
Hi,
I've pushed the PR for this ticket. I'd be good to get some feedback thanks.
