### ISSUE TITLE
docs(developer): update for the current state of Java SDK licensing

### ISSUE THREAD

**Issue by Splaktar** [angular/angular#29043]
# 📚 Docs or angular.io bug report

### Description

We currently list the Java SDK as a [prerequisite](https://github.com/angular/angular/blob/master/docs/DEVELOPER.md#prerequisite-software) in the [Developer Guide](https://github.com/angular/angular/blob/master/docs/DEVELOPER.md). 

We link to the Oracle JDK site in Spanish (http://www.oracle.com/technetwork/es/java/javase/downloads/index.html).

1. It seems like an English site should be the default (http://www.oracle.com/technetwork/java/javase/downloads/index.html)
2. The English site lists Oracle JDK 11.0.2 (LTS) as the top recommendation.

Does Selenium, Bazel, and everything else work with Java 11?
Does it work with the Open JDK 11?

Should we be pointing people at the [Open JDK](https://jdk.java.net/11/) now as the Oracle JDK’s [Oracle Commercial only license](https://www.oracle.com/technetwork/java/javase/terms/license/javase-license.html) will likely scare away contributors (and possibly even team’s considering Angular)?

The Open JDK uses a [GPL v2 license with the Classpath Exception](https://openjdk.java.net/legal/gplv2+ce.html).

Or do we need to specify Java SDK 8?

### What's the affected URL?**
https://github.com/angular/angular/blob/master/docs/DEVELOPER.md#prerequisite-software

### Reproduction Steps**
Click the link for the "Java Development Kit".

### Expected vs Actual Behavior**
It opens the [Oracle JDK site](http://www.oracle.com/technetwork/es/java/javase/downloads/index.html) in Spanish. It should open an English site by default and we should consider the Open JDK or specify Java SDK 8.

## 📷Screenshot
![screen shot 2019-02-28 at 18 20 03](https://user-images.githubusercontent.com/3506071/53605431-7f10b000-3b85-11e9-9239-4d823e089332.png)
![screen shot 2019-02-28 at 18 19 46](https://user-images.githubusercontent.com/3506071/53605435-81730a00-3b85-11e9-8940-8d9bb5385dd8.png)

### Browser info
Chrome 72.0.3626.109 (Official Build) (64-bit)

### Anything else relevant?

N/A

**Comment by jenniferfell** [comment]
Thanks. For tracking, this is a few issues, if I understand correctly: 

*1. Editorial Fix:* Change link from Spanish to English version of Oracle JDK site. (http://www.oracle.com/technetwork/es/java/javase/downloads/index.html).

*2. Compatibility update - 3rd party current version:* What version of Java SDK? Java SDK 8 or 11?
Details: The English site lists Oracle JDK 11.0.2 (LTS) as the top recommendation. Does Selenium, Bazel, and everything else work with Java 11? Does it work with the Open JDK 11?

*3. Compatibility update - different 3rd party:* Continue to link to Oracle JDK or change to Open JDK?
Details: Should we be pointing people at the Open JDK now as the Oracle JDK’s Oracle Commercial only license will likely scare away contributors (and possibly even team’s considering Angular)? The Open JDK uses a GPL v2 license with the Classpath Exception.

@IgorMinar: We'll need your input on this. Thanks!

**Comment by wKoza** [comment]
Bazel seems officially compatible openJDK 8, see [this link](https://docs.bazel.build/versions/master/install-ubuntu.html)

```
sudo apt-get install openjdk-8-jdk
```

**Comment by Splaktar** [comment]
@jenniferfell yes, that's accurate except that item `1` can't be solved independently. It needs an answer to either `2` or `3`, perhaps both.

@wKoza thank you for that information. That's helpful, but it would be good to have some kind of evidence and reasoning before we recommend/require that Angular framework contributors install an old version of the Java SDK. As far as I can tell from [Wikipedia](https://en.wikipedia.org/wiki/Java_version_history), Oracle put out the last free commercial update to Java 8 LTS in January 2019. It looks like they may update Java 8 for personal use for free until December 2020. Then it is EOL in 2025. 

Note that Java 9 and 10 are already EOL'd. Java 11 is the latest LTS version.

It may be viable to stay on Java SDK 8 (Oracle or OpenJDK), but it would need to be something that we specifically suggest to contributors if OpenJDK 11 causes issues.

**Comment by wKoza** [comment]
Of course. [In this doc](https://github.com/bazelbuild/bazel/blob/fc996af0d8be918832845eb8dc73e3d3e935b7fd/site/docs/install-compile-source.md#21-install-the-prerequisites), Bazel seems more directif concerning the compilation.

**Comment by Splaktar** [comment]
@wKoza oh great! That's certainly a solid piece of data, that the Bazel team's developer guide requires Java 8 (Oracle or OpenJDK, but OpenJDK recommended) and states "Versions other than 8 are *not* supported."

**Comment by gkalpak** [comment]
I think those requirements are for building bazel from sources (which is not what most people will be doing :grin:).
If one just wants to use bazel [via the binaries][1] (which is currently the recommended way, then I don't think JDK is a prerequisite, since bazel ships with its own version of it.

@alexeagle can confirm.

[1]: https://docs.bazel.build/versions/master/install-ubuntu.html#install-with-installer-ubuntu

**Comment by wKoza** [comment]
of course @gkalpak , but bazel **recommends** a Jre 8 for the runtime; After, it does not mean that it will not work with a Jre 11. However, there have been some deletions of some components in the version 11).

**Comment by gkalpak** [comment]
@wKoza, can you clarify _where_ bazel recommnds having JRE or JDK as a prerequisite for using bazel (via tha binaries)?
Because I don't think you need that at all with latest versions of bazel.

**Comment by wKoza** [comment]
I don't say that, you don't have to install a jre if you use the binary version

**Comment by rockument69** [comment]
We now link to the [Java SE - Downloads](https://www.oracle.com/java/technologies/javase-downloads.html) page at Oracle. This can be closed.

**Comment by Splaktar** [comment]
PR https://github.com/angular/angular/pull/33168 fixes the link to go to the English site instead of the Spanish site, but that doesn't resolve all of the issues mentioned in this issue.

We still link to the Oracle, proprietary licensed version of the JRE instead o the OpenJDK version. That doesn't seem like the right recommendation for our contributors.

We also link to the JRE `14.0.1` download, which may or may not be supported by Bazel. However, it appears that `@angular/bazel` comes with a JRE, so that's no longer a pre-requisite.

Our current docs state:

> Java Development Kit which is used to execute the selenium standalone server for e2e testing.

Is this really still needed for the "selenium standalone server"?

Do we still have Closure Compiler as part of the build process? That would require Java. But it seems like that might have been removed recently?

Can we verify that Java is still a prerequisite for contributors to Angular?

**Comment by Splaktar** [comment]
Oh and we're currently deprecating the `@angular/bazel` NPM package and recommending that everyone run Bazel directly now. So perhaps that re-introduces a Java JDK as a requirement of Bazel?

**Comment by Splaktar** [comment]
> Do we still have Closure Compiler as part of the build process? That would require Java. But it seems like that might have been removed recently?

It appears to still be part of some integration tests.

**Comment by Splaktar** [comment]
No one seems to know if Closure Compiler supports the [GPL v2 JDKs](https://jdk.java.net/), so I asked in https://groups.google.com/g/closure-compiler-discuss.

**Comment by Splaktar** [comment]
It looks like https://openjdk.java.net/ may be a good place to point developers as it points to the Open JDKs, Oracle's GPL v2 JDKs, and Oracle's commercial JDKs. Developers can then pick the one that is right for them.
