### ISSUE TITLE
angular.json 引入cdn文件报错

### ISSUE THREAD

**Issue by haihuo0910** [angular/angular#29051]
"scripts": [
              "http://192.168.101.126:9000/bigemap.js/v2.1.0/bigemap.js"
            ]

![image](https://user-images.githubusercontent.com/34278572/53623785-13881a80-3c39-11e9-92de-f9baab44d7c6.png)

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
