### ISSUE TITLE
Service worker requestSubscription() freezes and doesn't show native popup if serviceworker.controller is null

### ISSUE THREAD

**Issue by Serginho** [angular/angular#29067]
# 🐞 bug report

### Affected Package
@angular/service-worker

### Is this a regression?
No

### Description

The problem is here
https://github.com/angular/angular/blob/a06824aef6e2e1c5b1c037d2c2e1dda544842000/packages/service-worker/src/low_level.ts#L74-L82
When `controllerchange` is triggered, the code access to `serviceworker.controller` and filters it if is `null`. After that, the `registration` is created from the previous pipes.

What happens if the `serviceworker.controller` is `null` in all `controllerchange` events? (At the moment you are thinking that couldn't happen, but yes 🎉it happens!!!🎉. 
Then if the app is started with `serviceworker.controller = null `and `requestSubscription` is called a few minutes later, the promise won't never be resolved.
https://github.com/angular/angular/blob/c0757d1d440d6f934436418add9755e7d630bbcf/packages/service-worker/src/push.ts#L93-L99

**Possible solution**
Merging `registration`observable with `serviceworker.ready`but I'm not sure if breaks something.
https://github.com/angular/angular/blob/c0757d1d440d6f934436418add9755e7d630bbcf/packages/service-worker/src/low_level.ts#L81-L82

## 🔬 Minimal Reproduction
The problem reproduction is explained in the previous section. But if you want to get crazy to Chrome to test the bug, you can do the following:

You can test this on Chrome 72 Windows, the steps are not going to work on Chrome Mac. But I have logs that prove the bug happens in other Chrome version and platforms, maybe, doing different steps, but the state is the same, `serviceworker.controller` is `null`.

Steps Chrome Windows.
1. Create a app with a checkbox or switch button to activate/descativate notifications.
2. Check the switch in your app will call `requestSubscription()`
3. When the popup is shown, press Block.
4. Go to de addressbar, click in the lock :lock:. Change the notifications state to Allow. Chrome will say you that the page should be reloaded.
6. Reload the page.
7. If you call `requestSubscription()`again, you won't get the popup. Or if you write in the console `serviceworker.controller` you will get `null`.

Here is an example image. The app is started, `serviceworker.controller` is `null`, but I can get the service worker registration and the push subscription, so `serviceworker.controller` is not needed to get it. (Keys are hidden in the image).
<img width="735" alt="captura de pantalla 2019-03-01 a las 19 49 21" src="https://user-images.githubusercontent.com/315972/53675185-44e20400-3c94-11e9-91ac-9b9b46f04919.png">

## 🌍  Your Environment

**Angular Version:**
Tested in angular 7.1.7 but I think all version are affected.

**Anything else relevant?**

I use this code with a timeout before I  run into the issue to avoid freezing the function. I'm getting logs `Can't subscribe: Timeout ocurred` from Chrome Windows but specially lots of entries for Chrome android.
```typescript
      this.swPush.requestSubscription({serverPublicKey: this.VAPID_PUBLIC_KEY}))
      .pipe(
        timeout(8000),
        tap({
          next: () => this.measuringDao.sendBackendEvent('activated_notifications').subscribe(),
          error: err => this.logger.warn('Can\'t subscribe: ' + err.toString(), err)
        }),
        switchMap(sub => this.notificationsDao.registerPushSubscriber(sub))
      );
```

**Comment by gkalpak** [comment]
Interesting. Generally, according to [the spec][1], `navigator.serviceWorker.controller` does always reflect the worker controlling the page (which is what we want). One strange corner case seems to be that, if a client is force refreshed (_Shift + reflesh_), then the activated SW will not take it over once activated (even with `clients.claim()`) and thus [`navigator.serviceWorker.controller` will indeed remain `null`][2] (until the page is reloaded).

It seems strange that `client.claim()` would not be respected (I can't find anything relevant in [the spec][3]) 😕

##
In any case, this does not explain the behavior (since there was no force refreshing involved) and I could not reproduce it (with Chrome 72 on Windows). 

I wouldn't be opposed to taking `navigator.serviceWorker.ready` or `navigator.serviceWorker.getRegistration()` into account, but I would like to understand the error first. @Serginho, could you create a minimal reproduction (e.g. a repo I could checkout and reproduce the issue)?

[1]: https://w3c.github.io/ServiceWorker
[2]: https://w3c.github.io/ServiceWorker/#navigator-service-worker-controller
[3]: https://w3c.github.io/ServiceWorker/#clients-claim

**Comment by Serginho** [comment]
We can't discard that could be a Chrome bug. I'll try to give you an example an how to reproduce it, but... The important thing is:

> **Even if the user does a forced reload, the code should works anyway.**

I use a forked version of the service worker (don't worry if you are thinking that could be a problem of my forked code, I've only implemented the `pushsubscriptionchange` event)... Do you think this could be a hotfix?
```typescript
this.registration = <Observable<ServiceWorkerRegistration>>( 
     merge(this.worker, fromEvent(serviceWorker, 'ready')).pipe(switchMap(() => serviceWorker.getRegistration()))); 
```

We are losing lots of requestSubscriptions. Like I said, this code logs we the popup isn't shown.

```typescript
      this.swPush.requestSubscription({serverPublicKey: this.VAPID_PUBLIC_KEY}))
      .pipe(
        timeout(8000),
        tap({
          next: () => this.measuringDao.sendBackendEvent('activated_notifications').subscribe(),
          error: err => this.logger.warn('Can\'t subscribe: ' + err.toString(), err)
        }),
        switchMap(sub => this.notificationsDao.registerPushSubscriber(sub))
      );
```

Noticed that we are NOT showing the popup in the main page when the app boots. We have a page explaining why you should activate notifications, and if you click our button that says: "Activate notifications" then we will call `requestSubscription`.

These are the logs in the last 30 minutes. As you can see, This is not the tipical weird bug that happens by chance.

> March 3rd 2019, 20:02:02.514 | Can't subscribe: TimeoutError: Timeout has occurred | Chrome (72.0.3626.105) running over Android (5.1.1)
> March 3rd 2019, 19:54:03.964 | Can't subscribe: TimeoutError: Timeout has occurred | Chrome (71.0.3578.99) running over Android (8.1.0)
> March 3rd 2019, 19:53:18.459 | Can't subscribe: TimeoutError: Timeout has occurred | Chrome (72.0.3626.105) running over Android (7.1.1)
> March 3rd 2019, 19:53:08.646 | Can't subscribe: TimeoutError: Timeout has occurred | Chrome (71.0.3578.99) running over Android (4.4.2)
>  March 3rd 2019, 19:42:17.368 | Can't subscribe: TimeoutError: Timeout has occurred | Chrome (72.0.3626.105) running over Android (9)
> March 3rd 2019, 19:41:16.824 | Can't subscribe: TimeoutError: Timeout has occurred | Chrome (72.0.3626.105) running over Android (8.1.0)
> March 3rd 2019, 19:40:31.476 | Can't subscribe: TimeoutError: Timeout has occurred | Chrome (72.0.3626.105) running over Android (6.0.1)
> March 3rd 2019, 19:39:33.304 | Can't subscribe: TimeoutError: Timeout has occurred | Chrome (72.0.3626.105) running over Android (6.0)
> March 3rd 2019, 19:38:26.182 | Can't subscribe: TimeoutError: Timeout has occurred | Chrome (72.0.3626.105) running over Android (7.0)
>  March 3rd 2019, 19:36:15.625 | Can't subscribe: TimeoutError: Timeout has occurred | Chrome (70.0.3538.110) running over Android (6.0.1)
>  March 3rd 2019, 19:35:21.772 | Can't subscribe: TimeoutError: Timeout has occurred | Chrome (70.0.3538.110) running over Android (6.0.1)
>

**Comment by gkalpak** [comment]
> Even if the user does a forced reload, the code should works anyway.

Well, it is debatable what "works" should mean. If the page is not controlled by a SW (as seems to be the case after a force refresh), then should it be possible to request a subscription? Technically, it _is_ possible to use the matching SW registration to do that, but the page would not be notified of notification clicks, for example (since the SW in not yet controlling the page).
That could be equally confusing imo.

But, as you said, this could be a browser issue. It is hard to decide on the right "fix", without understanding the root of the problem (hence I want to reproduce it first).

##
> Do you think this could be a hotfix?
> ```
> this.registration = <Observable<ServiceWorkerRegistration>>(
>    merge(this.worker, fromEvent(serviceWorker, 'ready')).pipe(switchMap(() => serviceWorker.getRegistration())));

I don't think `navigator.serviceWorker` has a `ready` event, thus `fromEvent(serviceWorker, 'ready')` wouldn't do anything.
I think something like the following should do:

```
this.registration = <Observable<ServiceWorkerRegistration>>(
    merge(
        from(serviceWorker.ready),
        this.worker.pipe(switchMap(() => serviceWorker.getRegistration())),
    ));
```

But notice that other APIs depending on `this.worker` (e.g. checking/activating updates) might not work.

**Comment by gkalpak** [comment]
Interestingly, after a force refresh, the page is in a weird, intermediate state :grin:
It _can_ interact with the SW (e.g. via `(await navigator.serviceWorker.getRegistration()).postMessage(...)`) and the SW can respond to messages, but the page is not controlled by the SW.

We could probably detect this state and force the page to be controlled by the SW by trigerring `clients.claim()`, but there are certain drawbacks:
1. It has the side effect of claiming _all_ clients. (AFAICT, there is no way for the SW to claim a specific client only.)
2. It breaks the purpose of force refresh, which seems to be running the page without a SW.

One could argue that (1) would generally not be a problem, since all pages would be claimed. And, also, (2) may not make sense in the context of a SPA, where force refresh should be expected to run without the SW for the initial load, but after that it would be fine for the Sw to take over.

Of course, this is not something we should do lightly, but maybe worth considering.

**Comment by Serginho** [comment]
> I don't think navigator.serviceWorker has a ready event, thus fromEvent(serviceWorker, 'ready') wouldn't do anything.
Yes, navigator.serviceWorker.ready is available.

> 2. It breaks the purpose of force refresh, which seems to be running the page without a SW.
Hmm... Could it be when I change the notifications state from Block to Allow and Chrome shows an alert to reload the page, this reload will be a forced reload?. But just look at all android devices... 

Another thing we do and didn't mention in the previous comments is to call requestSubscription when the user enters on the site only if the notifications are enabled, this behaviour is cause Chrome don't implement `pushsubscriptionchange` event in order to minimize lost subscriptions. For this reason I know if the user has notifications enabled, and we request the subscription, the timeout could happen.  🤯

**Comment by Serginho** [comment]
@gkalpak This is crazy. I got it!
I could reproduce it by chance. It's a Chrome bug. When chrome gets in a weird state and `subscribe()` freezes and doesn't show the prompt and the promise won't never resolved.

See that image:
<img width="1270" alt="bug" src="https://user-images.githubusercontent.com/315972/54217647-51642900-44ec-11e9-9842-f60987241418.png">

`subscribe()` don't print any result.

`getSubscription()` prints `null`

`permissionStatus()` prints `prompt`

`Notification.permission` prints `default`

To confirm the bug I debugged `SwPush`. When this happens if you put a breakpoint in this line `pm` is defined.
https://github.com/angular/angular/blob/903d28fe86744159582b738cb41e453ec21095c9/packages/service-worker/src/push.ts#L93
But never reaches this line:
https://github.com/angular/angular/blob/903d28fe86744159582b738cb41e453ec21095c9/packages/service-worker/src/push.ts#L96

**Comment by gkalpak** [comment]
Nice, @Serginho! Have you checked whether `.subscribe()` rejects?

**Comment by Serginho** [comment]
<img width="1321" alt="Captura de pantalla 2019-03-12 a las 17 56 55" src="https://user-images.githubusercontent.com/315972/54219680-4612fc80-44f0-11e9-9b63-05ddde9a4a3e.png">

Update, no rejects

**Comment by gkalpak** [comment]
Nice sleuthing. Could you report it to Chrimium (if not already reported)?

**Comment by Serginho** [comment]
That's I'm trying to do. That is the last straw! I getting a 400 Bad request when I submit the issue, all fields are filled with no errors :sob:. I'll link the issue here.

**Comment by Moeriki** [comment]
Not sure if same issue. I make the same call

```ts
await this.swPush.requestSubscription({ serverPublicKey })
```

- I get no response, error or otherwise.
- `navigator.serviceWorker.controller` is `null`.
- Reproducible in Chrome and Firefox.

Can I help investigate? Should I create a separate issue?

**Comment by Serginho** [comment]
You are doing a force reload (Shift + F5). When you do this, the tab isn't controlled by service worker. 

No issue if you see `controller = null` with force reload.

**Comment by ElectroluxV2** [comment]
> Not sure if same issue. I make the same call
> 
> ```ts
> await this.swPush.requestSubscription({ serverPublicKey })
> ```
> 
> * I get no response, error or otherwise.
> * `navigator.serviceWorker.controller` is `null`.
> * Reproducible in Chrome and Firefox.
> 
> Can I help investigate? Should I create a separate issue?

I have same issue except that for me it works in Chrome unless user already gave permission to show notification... (works only if permission state is to ask for permission) and doesn't work at all in latest Brave.

**Comment by omatrot** [comment]
I have the same issue, whatever the browser when using Angular 8.X. 
This seems to be an angular issue because with another web site that is using Angular 7.2 it works !

**Comment by gkalpak** [comment]
From what I can tell, this is either a Chrome bug or if it is in Angular we don't have a reliable reproduction. Thus this is issue is not actionable in its current state.

If you are still running into this problem and you have confirmed that this is not browser bug, please open a new issue with a minimal reproduction.
