### ISSUE TITLE
Our Angular application is not working in IE-11 version - 11.0.9600.19266 - Help Needed

### ISSUE THREAD

**Issue by Vigneshml** [angular/angular#29077]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Team,

I'm not able to see our application working in internet explorer version - 11.0.9600.19266.
It's working fine in other browsers and higher versions of IE.
I'm seeing the below error in the IE console,
Error: Access is denied.
at DefaultDomRenderer2.prototype.setAttribute (vendor.js:line num)
at BaseAnimationRenderer.prototype.setAttribute (vendor.js)

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by brewzk1** [comment]
What version of Angular are you using?
If it's earlier than ng7 you may want to check your polyfills.ts file.
The commented instructions there are pretty clear on which lines to un-comment to for IE10 and IE11.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Vigneshml** [comment]
Team,
Thanks! for your inputs. The issue is resolved.

I'm putting the below points as it may be helpful to someone. 

Error causing code:
<img src="assets\logo.png"> in the app.component.html

Solution:
<img [src]="Logo"> here, the "Logo" is the .ts variable

you will get the reported issue(**Access is denied**) even if your HTML code is invalid like above.

Reference link: https://stackoverflow.com/questions/36287518/angular-2-img-src-in-a-relative-path

Best Regards,
Vignesh Manivasagan

**Comment by soeberg84** [comment]
Solution:
<img src="assets/logo.png">
