### ISSUE TITLE
DI: Trying to inject from a template element results in no provider found

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2907]
As discussed offline, the following is not working in the current release:

```html
<template popup>
  <material-popup></material-popup>
</template>
```

Where `popup` is a `PopupDirective`, and `material-popup` is:

```dart
class MaterialPopupComponent {
  MaterialPopupComponent(@Unbounded() PopupDirective directive) {}
}
```

For visibility: @naomiblack and @yjbanov

**Comment by matanlurey** [comment]
This is resolved as working as intended. A little background for those interested:

It used to be possible (pre - #2708) to inject a parent template directive. This was *not* working as design as the "true" representation of the DOM looks like this:

```html
<template popup></template>
<material-popup></material-popup>
```

We found a workaround (thx @rkirov @tbosch) that instead exports the popup directive and uses view locals to be able to do something like this:

```html
<template popup #handle="popup">
  <material-popup [handle]="handle"></material-popup>
</template>
```

If anybody is interested further how this pattern works I can expand. Thanks all!

**Comment by rkirov** [comment]
Thanks for the write-up!
