### ISSUE TITLE
ivy-ngcc is unable to recognise AngularFireModule.initializeApp as ModuleWithProviders

### ISSUE THREAD

**Issue by sarunint** [angular/angular#29078]
# 🐞 bug report

### Affected Package

The issue is caused by package `@angular/compiler-cli`

### Is this a regression?

No

### Description

Take a look at this code (taken from https://unpkg.com/@angular/fire@5.1.1/es2015/firebase.app.module.js):

```typescript
let AngularFireModule = AngularFireModule_1 = class AngularFireModule {
    static initializeApp(options, nameOrConfig) {
        return {
            ngModule: AngularFireModule_1,
            providers: [
                { provide: FirebaseOptionsToken, useValue: options },
                { provide: FirebaseNameOrConfigToken, useValue: nameOrConfig }
            ]
        };
    }
};
AngularFireModule = AngularFireModule_1 = __decorate([
    NgModule({
        providers: [FirebaseAppProvider],
    })
], AngularFireModule);
export { AngularFireModule };
```

`ivy-ngcc` cannot recognise the `AngularFireModule.initializeApp` and mark it as `ModuleWithProviders`.

This is because the current implementation of `ivy-ngcc` which looks for `ts.ClassDeclaration`. Instead, the code above is a variable assignment to `ts.BinaryExpression` which includes `ts.ClassExpression`.

There are 2 solutions to this issue:

1. Make `ivy-ngcc` to able to recognise class declaration like this.
2. Tell library authors to use `angularCompilerOptions.annotationsAs` as `static fields` during packaging.

My voice is with solution 2, though.

## 🔬 Minimal Reproduction
N/A

## 🔥 Exception or Error
N/A

## 🌍  Your Environment

**Angular Version:**
<pre><code>

8.0.0-beta.6

</code></pre>

**Anything else relevant?**

This causes #28603.

**Comment by StephenFluin** [comment]
For future search reference, the symptom I'm seeing that I believe is caused by this is the error:
`Error: Value at position 4 in imports array is not a reference: [object Object]` with position depending on where you have the `ModuleWithProviders` in the import array.

**Comment by sarunint** [comment]
@StephenFluin That's the exact error message that makes me go through debugging the `ivy-ngcc`.

By the way, what's the intended solution for this: fix `ivy-ngcc` or fix the library?

**Comment by petebacondarwin** [comment]
The fix needs to be in the ngcc tool.
