### ISSUE TITLE
Route children does not work with 

### ISSUE THREAD

**Issue by felipedrumond** [angular/angular#29072]
I have a set of routes configuration that should work after @angular 6.1.0, but it doesn't.

```
const routes: Routes = [
  { path: '', children: [
    { path: 'reconciliation', loadChildren: './reconciliation/reconciliation.module#ReconciliationModule' },
  ]}
];

```
The reconciliation.module imports reconciliation-routing.module that contains the following configuration:

```
const routes: Routes = [
  {
    path: '',
    component: ReconciliationComponent,
    children: [
      { path: '', redirectTo: 'reconcile', outlet: 'tab' },
      { path: 'reconcile', component: ReconcileComponent, outlet: 'tab' }, <--- should fall here
      { path: 'import', component: ImportTransactionsComponent, outlet: 'tab' },
    ]
  }
];
```

With this configuration navigating to /reconciliation should fall on ReconcileComponent but this does not work, throwing 
"ERROR Error: Uncaught (in promise): NoMatch: {}". It works if I add a new route option that redirects to the one I want: 

```
const routes: Routes = [
  { path: '', redirectTo: 'blabla', pathMatch: 'full' }, <----
  {
    path: 'blabla', <----
    component: ReconciliationComponent,
    children: [
      { path: '', redirectTo: 'reconcile', outlet: 'tab' },
      { path: 'reconcile', component: ReconcileComponent, outlet: 'tab' }, <-- falls here
      { path: 'import', component: ImportTransactionsComponent, outlet: 'tab' },
    ]
  }
];
```

I saw that 6.1.0 should fix this, I'm using 6.1.8 and even tried angular/router 7.2.7, with no success.

**Comment by ericmartinezr** [comment]
There's an issue that report the same error message https://github.com/angular/angular/issues/23282. If that's not your case, please provide a reproduction as requested in the issue template.

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-issue-repro2).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
