### ISSUE TITLE
router

### ISSUE THREAD

**Issue by sinanasiriamirbande** [angular/angular#29087]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please file any Angular CLI issues at: https://github.com/angular/angular-cli/issues/new

For the time being, we keep Angular CLI issues in a separate repository.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by sinanasiriamirbande** [comment]
in my shop component => root 
i get my menu and its children if i click on them redirect to my collection component that have list of products. but after calling get collection service in collection component . web page redirect to shop page.
i do not have any auth gurd yet. and the collection service get 200 success. but i redirect to shop page .
any where in my collection component i do not have navigate. what is reason

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
