### ISSUE TITLE
Angular Package Format (APF): include version field for secondary entry points

### ISSUE THREAD

**Issue by dherges** [angular/angular#29086]
# 🚀 feature request

### Relevant Package

Angular Package Format, affects generated build artefacts of the ecosystem

### Description

I was looking into Microsoft's API Extractor to flatten `d.ts` files for npm packages. The dtsRollup looks promising but I am running into a missing link with secondary entry points:

```
BUILD ERROR
Error reading "node_modules/@angular/common/http/package.json":
  The required field "version" was not found
Error: Error reading "node_modules/@angular/common/http/package.json":
  The required field "version" was not found
    at PackageJsonLookup.loadPackageJson (node_modules/@microsoft/node-core-library/lib/PackageJsonLookup.js:162:23)
    at PackageJsonLookup.tryLoadPackageJsonFor (node_modules/@microsoft/node-core-library/lib/PackageJsonLookup.js:132:21)
    at AstMethod._analyzeTypeReference (node_modules/@microsoft/api-extractor/lib/ast/AstItem.js:429:14)
```

### Describe the solution you'd like

Add the version field to `common/http/package.json` and every other secondary entry point?

### Describe alternatives you've considered

Fixing api-extractor to tolerate empty version field?

**Comment by alan-agius4** [comment]
This should have been solved in API extractor version 7.

If the problem persist I suggest to open an issue with API Extractor.

**Comment by alan-agius4** [comment]
Actually it seems there is an open issue related to this https://github.com/Microsoft/web-build-tools/issues/1044

**Comment by gkalpak** [comment]
Closing , since [it seems this will be fixed][1] in API extractor.

[1]: https://github.com/Microsoft/web-build-tools/issues/1044#issuecomment-461102658
