### ISSUE TITLE
feat(forms): hide get() method of FormControl from public API

### ISSUE THREAD

**Issue by KostyaTretyak** [angular/angular#29091]
# 🚀 feature request

### Relevant Package
This feature request is for `@angular/forms`

### Description
As far as I understand, the `get()` method of `FormControl` always returns null. (See also [stackoverflow](https://stackoverflow.com/q/54979138/1716560) with my relative question).

### hide get() method of FormControl from public API
Since this method is also used in other FormControl methods, maybe it makes sense for AbstractControl to make it protected, and in FormGroup and FormArray to make it API public? This solution seems to be suitable for Angular v8.

### Alternative
For Angular v7, it seems to make sense to rewrite it, for example:

```ts
  /**
   * In `FormControl`, this method always returns `null`.
   */
  get(path: Array<string | number> | string): null {
    return null;
  }
```

**Comment by dylhunn** [comment]
We cannot do this, because many libraries extend `AbstractControl` and rely on us not removing interface methods.

I don't think it's a big deal anyway: what does it even mean to `get` on a `FormControl`? I don't think returning `null` is so harmful!
