### ISSUE TITLE
 Anchor scrolling only works first time it is clicked and not on subsequent clicks.

### ISSUE THREAD

**Issue by ImranAhmed** [angular/angular#29099]
# 🐞 bug report

### Affected Package

"@angular/router": "^7.2.5",

### Description
In attached stackblitz.

1. Click 'scroll to A'. Page correctly scrolls to anchor A.
2. Scroll the browser window back to top of page.
3. Click 'scroll to A'. Page does not correctly scroll to anchor A.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-q641ci

## 🌍  Your Environment
  "dependencies": {
    "@angular/common": "^7.2.5",
    "@angular/compiler": "^7.2.5",
    "@angular/core": "^7.2.5",
    "@angular/forms": "^7.2.5",
    "@angular/platform-browser": "^7.2.5",
    "@angular/platform-browser-dynamic": "^7.2.5",
    "@angular/router": "^7.2.5",
    "core-js": "^2.6.5",
    "rxjs": "^6.4.0",
    "zone.js": "^0.8.29"
  }

**Comment by s-gbz** [comment]
Hey guys, I can take this on. Advice is appreciated though.

@gkalpak is https://github.com/angular/angular/blob/master/packages/router/src/router.ts a place to start?

**Comment by gkalpak** [comment]
I am not very familiar with the router. cc @jasonaden

**Comment by jasonaden** [comment]
@s-gbz It would be great if you want to take this on. We can collaborate on it a bit if you would like.

The scrolling is coming more from changes applied in #20030. I think it would be good to take a look there first.

You can DM me on Twitter if you want @jasonaden1.

**Comment by s-gbz** [comment]
Great, I'll get on to it next week!

**Comment by voidale** [comment]
+1 have this happen to me I thought there was a setting way to change this, good to know it's a bug and going to be fixed Thanks!

**Comment by s-gbz** [comment]
Hello there and sorry for the long wait. After fighting with Bazel for months, I can finally get to work on the real issue :)

**Comment by Tolga-FNT** [comment]
@s-gbz 
It's still not fixed yet. I am having the same issue.

**Comment by PedroJesusRomeroOrtega** [comment]
Hi!
Using the *the minimal reproduction* example, it works as you expected if you add ` onSameUrlNavigation: 'reload'` extra option to the router module:
``` diff
@NgModule({
  imports:      [ BrowserModule, FormsModule, 
  RouterModule.forRoot(appRoutes, {
      scrollPositionRestoration: 'enabled',
      anchorScrolling: 'enabled',
      useHash: false,
+      onSameUrlNavigation: 'reload',
    }) ],
  declarations: [ AppComponent, HelloComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }
```
