### ISSUE TITLE
SyntaxError: expected expression, got '<' whenever basehref is changed in production/dist

### ISSUE THREAD

**Issue by micheladennis** [angular/angular#29104]
### Description

Whenever I change basehref to "/v2/" (or any other value other than "/") I get the following error:
SyntaxError: expected expression, got '<'

Works in development - ng serve --base-href /v2/

## 🔬 Minimal Reproduction
Terminal
```
$ ng new testng
$ cd testng
$ ng build --prod --base-href /v2/

```
Deploy dist folder to nginx server

Easy - Docker Deployment for Reproducing

nginx default.conf

```
server {
  listen 80;
  charset utf-8;
  sendfile on;
  root /usr/share/nginx/html;
   
  location / {
    expires -1;
    add_header Pragma "no-cache";
    add_header Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0";
  
    try_files $uri $uri/ /index.html = 404;
  }
      
}
```

Dockerfile
```
FROM nginx:alpine

ENV DEPLOYMENT_FOLDER deployment/docker
ENV DIST dist/testng

#create the server and location configuration
COPY $DEPLOYMENT_FOLDER/default.conf /etc/nginx/conf.d/default.conf
#copies the build app to the default location
COPY $DIST /usr/share/nginx/html
```

`$ docker build -f Dockerfile -t testng:0.1 .`
`$ docker run --name testng -p 8083:80 -d testng:0.1`

## 🔬 Expected Results
https://server/v2/ show page data

## 🔬 Actually Results / 🔥 Exception or Error
https://server/v2/ -- Blank Page

SyntaxError: expected expression, got '<'[Learn More] runtime.06daa30a2963fa413676.js:1
SyntaxError: expected expression, got '<'[Learn More] polyfills.f4b78b65941f8063fd57.js:1
SyntaxError: expected expression, got '<'[Learn More] main.41370b040b122bba133b.js:1 

## Other Info
Angular CLI: 6.2.9
Node: 8.10.0
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.9
@angular-devkit/build-angular     0.8.9
@angular-devkit/build-optimizer   0.8.9
@angular-devkit/build-webpack     0.8.9
@angular-devkit/core              0.8.9
@angular-devkit/schematics        0.8.9
@angular/cli                      6.2.9
@ngtools/webpack                  6.2.9
@schematics/angular               0.8.9
@schematics/update                0.8.9
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.16.4

**Comment by robwormald** [comment]
This is likely your nginx server sending back the default / fallback route (likely your index.html) because its 404'ing on your scripts (because you've changed the base href) - see https://angular.io/guide/deployment#the-base-tag on how to configure it properly.
