### ISSUE TITLE
Tutorial: Step 4: Services - Heroes list doesn't show (no errors)

### ISSUE THREAD

**Issue by rokit** [angular/angular#29101]
# 📚 Docs or angular.io bug report

### Description
After completing the services tutorial, the list of heroes is not displayed.

## 🔬 Minimal Reproduction
Complete step 4 of the tutorial.

### What's the affected URL?**
https://angular.io/tutorial/toh-pt4

## 🌍  Your Environment
Windows 10
Firefox

### Browser info
Not browser specific as far as I can tell.

### Anything else relevant?
My git repo of project: https://github.com/rokit/tour-of-heroes

**Comment by manklu** [comment]
> My git repo of project: https://github.com/rokit/tour-of-heroes

This repo contains only an empty Angular project 😕

**Comment by rokit** [comment]
Sorry, forgot to commit. Should be fixed.

**Comment by kamilchlebek** [comment]
@rokit You haven't executed method `getHeroes` inside `ngOnInit`  https://github.com/rokit/tour-of-heroes/blob/master/src/app/heroes/heroes.component.ts#L17

Just add parentheses at the end of `this.getHeroes` and it will work

**Comment by rokit** [comment]
Well, that's embarrassing. Thanks.
