### ISSUE TITLE
SyntaxError: expected expression, got '<' whenever basehref is changed in production/dist

### ISSUE THREAD

**Issue by micheladennis** [angular/angular#29102]
Angular 7

### Description

Whenever I change basehref to "/v2/" (or any other value other than "/") via `ng build --prod --base-href /v2/` I get the following error:

SyntaxError: expected expression, got '<'

Works in development - `ng serve  --base-href /v2/`

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
