### ISSUE TITLE
Mirror dom property values as attribute values in debug mode

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#2910]
This is needed for web workers and other use cases, to make it easy to locate elements by binding. Assigning to @tbosch to spec out and figure out who should best implement.

**Comment by naomiblack** [comment]
Also cited in internal b//21869186

**Comment by jeffbcross** [comment]
We'll create a token in the root injector called `DOM_REFLECT_PROPERTIES_AS_ATTRIBUTES` with a default value of false. It's up to the user to set this value to true if they want properties to be reflected as attributes.

**Comment by jeffbcross** [comment]
Attributes will all be dash-cased, with a prefix of "ng-reflect-".
