### ISSUE TITLE
Wildcard animations do not work in Firefox

### ISSUE THREAD

**Issue by veliko** [angular/angular#29121]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/animations

### Is this a regression?

Seems like a regression. Can reproduce same behavior with v6.1.10 of the animations module.

### Description

Wildcard animation transitions do not work in Firefox (including latest v65). The animation fails silently. The same wildcard does work in Chrome and Safari.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-b4xmnb?file=src/app/app.component.ts

Open the above in Firefox. In this example, note that the animation padding value in app.component.ts is set to '*'. The animation does not run and fails silently. Change the padding value to something like '2rem' and observe the animation completing just fine.

If you open the example in Chrome or Safari, it runs fine.

## 🌍  Your Environment

**Angular Version:**
<pre><code>v7.2.7</code></pre>

**Anything else relevant?**

Firefox v65

Tested on macOS Mojave, version 10.14.3

**Comment by bahiaxip** [comment]
Continue the issue Firefox v68

**Comment by dario-piotrowicz** [comment]
This issue doesn't seem to happen in firefox anymore

I've tested the stackblitz with firefox 104:
![Screenshot at 2022-08-27 22-36-12](https://user-images.githubusercontent.com/61631103/187048860-0b47476c-d966-44d3-98ea-27c60830da00.png)

And as you can see everything seems to work as it should:
![Peek 2022-08-27 22-45](https://user-images.githubusercontent.com/61631103/187049074-e8c6351d-9449-4a53-a2d7-0591c7028b0d.gif)

**Comment by JeanMeche** [comment]
It works also on v112.  I'll close it !
