### ISSUE TITLE
How to generate Angular.json file

### ISSUE THREAD

**Issue by AkashSurana** [angular/angular#29131]
My current application was in Angular 4 without Angular CLI. So I never had Angualr.json file or Angular-cli.json file. Now we want to generate that Angular CLI or angular.json file. Because this file is not available it is not taking any of the ng commands like ng serve or ng g c testing

How can I generate the file without using ng new command because ng new will create a new project which I don't want. I want to support my existing project.

Few notes on my project : 
1. We are launching multiple application from one folder 
2. We are launching each application from the ASPX page without using index.html.

Please see the screen shot attached of the error and the folder structure of my project
<img width="519" alt="folder_structure_1" src="https://user-images.githubusercontent.com/27774371/53883228-6a795f80-403e-11e9-9682-0b04a68f26fc.PNG">
<img width="663" alt="error" src="https://user-images.githubusercontent.com/27774371/53883229-6a795f80-403e-11e9-9e9d-fbc9d8d06267.PNG">
<img width="584" alt="folder_structure_2" src="https://user-images.githubusercontent.com/27774371/53883230-6a795f80-403e-11e9-9531-159e827104b1.PNG">

**Comment by ericmartinezr** [comment]
Please open this issue in angular-cli's repo https://github.com/angular/angular-cli
