### ISSUE TITLE
Support for providing ngFor trackBy function through DI

### ISSUE THREAD

**Issue by glenngr** [angular/angular#29149]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/common

### Description
The application I'm working on contains a lot of lists and tables. We use ngFor trackBy to increase performance, but we often end up implementing the same trackBy function in multiple components because most of our data models inherit from a base class with an ID property.

### Describe the solution you'd like
I'd like to be able to provide a trackByFn through DI.
I could provide a default function in app.module and provide other functions where needed in view providers or in other modules.

### Describe alternatives you've considered
Custom ngFor directive with trackBy function
Directive that sets trackBy function on ngFor directive (could not get this to work) (for example trackById directive that resolves NgForOf and sets the ngForTrackBy input.

**Comment by pkozlowski-opensource** [comment]
> I'd like to be able to provide a trackByFn through DI.
I could provide a default function in app.module and provide other functions where needed in view providers or in other modules.

I think that you can do it today, no?

```
@Component({
    selector: '...'
    template: `<div *ngFor="let item of items; ;trackBy: sharedTrackBy">...</div>`
})
class MyComponent {
   constructor(@Inject(public <SomeToken>) sharedTrackBy)
}
```

What other mechanism/ facility would you expect from Angular?

**Comment by glenngr** [comment]
That's nice, but what if you could provide a trackBy function on a higher level and thus not have to inject it in every component you need it in.
What if Angular provided a `NGFOR_TRACKBY_FN` token that I could provide in a module, and all components within that module would resolve the token and use the provided function?


```
@NgModule({
    providers: [
        { provide: NGFOR_TRACKBY_FN, useExisting: TRACK_BY_ID }
    ],
})
export class SomeModule { }
```

**Comment by pkozlowski-opensource** [comment]
> What if Angular provided a NGFOR_TRACKBY_FN token that I could provide in a module, and all components within that module would resolve the token and use the provided function

That sounds like a reasonable feature request for `ngFor`.

**Comment by dawidgarus** [comment]
You can provide custom IterableDifferFactory which would use trackBy function of your choice if none is specified.

**Comment by Airblader** [comment]
The current default trackBy always works, but is almost never ideal. Switching this to "almost never works, but when it does it's ideal" sounds like a bad tradeoff to me. All it takes is one ngFor over a list without an ID property and you have a really hard to debug issue on your hands.

**Comment by glenngr** [comment]
@Airblader If Angular provided an easy way to provide your own trackBy function through DI, you would provide the "track by id property" function where you needed it based on your own application requirements. You could always fall back to tracking by index or something else as well. It is up to us as developers to create a robust and fault tolerant trackBy function.

However, I do agree that it can create hard to debug problems for example on a large project with many developers where  some developers maybe are not aware that a custom trackBy function was provided in the module they are working on.

That makes me think that maybe the way to provide custom trackBy functions is to register them by a name that could be used in the template. That also makes it more visible in the template that there is in fact a custom trackBy function being used, even though it was provided through DI.

For example:
```typescript
function trackByItemIdFn(index: number, item: any) {
    return item && item.id || index;
}

const trackById = { name: 'trackById', trackByFn: trackByItemIdFn };

// This could register the trackBy function by the name "trackById", which could be used in the template
{ provide: TRACK_BY_FN, useValue: trackById, multi: true }
```

```html
<!-- resolves the trackBy function registered under name trackById -->
<div *ngFor="let item of items; trackBy: 'trackById'">
....
</div>
```

Maybe some extra error logging could be added to ngFor as well so that it is easier to debug problems like the one you described.

**Comment by Airblader** [comment]
At that point what's the difference to putting the function in a separate file and using this? 

    class FooComponent {
        public readonly trackById = trackById;
    }

**Comment by johannesjo** [comment]
Personally I don't need or would ever want to provide a global trackBy function, but what I would really care for would be `trackByProperty` e.g.:
```
<div *ngFor="let x of xs; trackByProp: 'id'"></div>
```

**Comment by Airblader** [comment]
@johannesjo There's a separate issue for that feature request: #12969

**Comment by johannesjo** [comment]
@Airblader thanks for mentioning. I searched for something like that, but with the wrong keywords as it seems.

**Comment by nigrosimone** [comment]
Disclaimer! I'm the author of [NgForTrackByProperty](https://github.com/nigrosimone/ng-for-track-by-property)

Angular global trackBy directive by passing a property name for track the ngFor item with strict type checking.

```ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <ul *ngFor="let item of list; trackByProperty: 'id'">
      <li>{{ item.id }} {{ item.name }}</li>
    </ul>
  `,
})
export class AppComponent {
  list = [
    { id: 0, name: 'foo' },
    { id: 1, name: 'bar' },
    { id: 2, name: 'baz' },
  ];
}
```

[Online demo](https://stackblitz.com/edit/demo-ng-for-track-by-property?file=src%2Fapp%2Fapp.component.ts)

[Source code](https://github.com/nigrosimone/ng-for-track-by-property/blob/main/projects/ng-for-track-by-property/src/lib/ng-for-track-by-property.directive.ts)

**Comment by pkozlowski-opensource** [comment]
While it sounds like a reasonable request (especially for applications that would like to switch from tracking by identity to tracking by index as the default) there is a potential for surprises / breaking changes here:
* a library could have such provider in its `NgModule` and alter application's behavior;
* libraries might assume certain defaults and re-configuring it on the application level could result in subtle bugs / behaviour changes. 

We are on the fence here, keeping open for now but need more signal to decide.

**Comment by pkozlowski-opensource** [comment]
After thinking about it some more we've decided to _not_ implement this feature. The default behaviour (track by identity) is a correct one. Swapping the default strategy application-wise could be breaking / incorrect for the existing components.

We do have plans to make it easier to specify the `trackBy` function, though.
