### ISSUE TITLE
Location.normalize does not remove leading slashes

### ISSUE THREAD

**Issue by waterplea** [angular/angular#29152]
# 📚 Docs or angular.io bug report

### Description

 Location.normalize documentation says it removed leading slashed when it doesn't. It is also mentioned in the comments that leading slashes ARE required for the url to be considered normalized:
https://angular.io/api/common/Location#usage-notes

### What's the affected URL?**
https://angular.io/api/common/Location#normalize

### Expected

Text regarding leading slashes should be removed

**Comment by chembu** [comment]
fixed in #27010
