### ISSUE TITLE
Resolver in lazy loaded module  freezes when retrying request

### ISSUE THREAD

**Issue by DionisisKav** [angular/angular#29157]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

No

### Description

1)I navigate to a page where i have a lazy loaded module with  1 component and  1 resolver.
2)Resolver calls the api but the token has expired  so a 401 status  comes in response.
3)The interceptor below handles the 401 to refresh the token and retry the request.

The result in my network tab is : 
1)the request fails with 401 
2) the token refreshes
3) the request is retried
4) request returns successful

In console tab:
  `retry req` is printed  as last output

browser window
then browser window stops loading 
the resolver freezes and  the  
component is never initialized

The below code though works for any other request outside from resolver  .
For example if i call the api inside my component , token will be refreshed and request will be retried once

## 🔬 Minimal Reproduction
```
      intercept(request: HttpRequest<any>, next: HttpHandler): Observable< HttpEvent<any>>  {
         let apiReq;
         if (request.url.startsWith(`https://${environment.Bucket}`)) {
             apiReq = request;
          } else {
               apiReq = this.setIdToken(request);
          }

        return next.handle(apiReq)
            .pipe(catchError(err => {
                let report_error = true;

                if (err.status === 401) {
                    report_error = false;
                    console.log('401 from req');
                    // If login session exists and refresh token succeed retry the request
                    return this.authService.isLoggedInandRefreshTokenObservable().pipe(switchMap((result) => {
                        if (result === true) {
                            apiReq = request.clone({
                                setHeaders: {
                                    Authorization: `Bearer ${this.authService.getIdToken()}`,
                                }
                            });
                            console.log('retry req');
                            return next.handle(apiReq);
                        }
                    }));

                } else if ( err.status === 403 || err.status === 404) {
                    this.router.navigate(['404'], {skipLocationChange: true});
                    return throwError(err);
                } else {
                    return throwError(err);
                }
            }));
    }
```
 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

"@angular/animations": "^7.2.0",
    "@angular/cdk": "^7.2.1",
    "@angular/common": "^7.2.0",
    "@angular/compiler": "^7.2.0",
    "@angular/core": "^7.2.0",
    "@angular/flex-layout": "^7.0.0-beta.22",
    "@angular/forms": "^7.2.0",
    "@angular/http": "^7.2.0",
    "@angular/material": "^7.2.1",
    "@angular/platform-browser": "^7.2.0",
    "@angular/platform-browser-dynamic": "^7.2.0",
    "@angular/router": "^7.2.0",

</code></pre>

**Anything else relevant?**

**Comment by alxhub** [comment]
A code snippet is not a sufficient reproduction for this problem. Please include a Stackblitz link with clear instructions for reproducing the buggy behavior.

**Comment by alxhub** [comment]
Closing as no reproduction was provided.
