### ISSUE TITLE
i am facing loading issue after take build 

### ISSUE THREAD

**Issue by aboobacker5577** [angular/angular#29155]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: 
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by aboobacker5577** [comment]
Date: 2019-03-07T07:53:00.390Z
Hash: cd9da120a6b2bbf89b25
Time: 39692ms
chunk {0} runtime.b57bf819d5bdce77f1c7.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} es2015-polyfills.0d4f876df327d0111ca2.js (es2015-polyfills) 56.4 kB [initial] [rendered]
chunk {2} main.fc28e2d023fd5b8de026.js (main) 3.11 MB [initial] [rendered]
chunk {3} polyfills.f1a86b50434b1a515c5a.js (polyfills) 41 kB [initial] [rendered]
chunk {4} styles.cc62f00b7e7a53f33bf6.css (styles) 65.4 kB [initial] [rendered]
this is my production result

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Anyway, this a cli issue https://github.com/angular/angular-cli/. Open a new issue and provide all the information requested.
