### ISSUE TITLE
Merge PR script doesn't take into account Code Owners approval status

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#29171]
The `merge-pr` script that is actively used by Caretakers doesn't take Code Owners approval status into account. I.e. it's possible to merge a PR without all the necessary approvals. It looks like NG Bot should take care of this situation (similar to what we used to have with PullApprove integration).

cc @ocombe @kara

**Comment by ocombe** [comment]
@IgorMinar specifically asked me to not take code owner approvals into account for the ng bot

**Comment by gkalpak** [comment]
@ocombe, did he say why? :grin:
Is it to work round the global approval GitHub issue?

**Comment by ocombe** [comment]
I think so yes

**Comment by gkalpak** [comment]
If so, I think it would be better for ngbot to take the approvals into account. For global approvals, we could have a special label that would indicate someone is using their global approval. If the label is present, ngbot could either ignore approvals (i.e. behave the same as today) or better yet verify that one of the approvers have global approval rights :grin:

WDYT?

**Comment by ocombe** [comment]
I thought that we were supposed to move to pullapprove v3 to fix that?

**Comment by ajitsinghkaler** [comment]
@gkalpak @AndrewKushnir  I think this issue has been solved after pull Approve

**Comment by AndrewKushnir** [comment]
Hi @ajitsinghkaler, yes, it should be fixed by PullApprove. Closing this ticket. Thank you.
