### ISSUE TITLE
Setting the locale does not change the displayed date. 

### ISSUE THREAD

**Issue by cnomes** [angular/angular#29183]
# 🐞 bug report

### Affected Package

The issue is caused by package `@angular/core` || `@angular/material-moment-adapter`

### Description

 
Changing the locale does not affect the displayed value of the DatePicker component.

## 🔬 Minimal Reproduction

 https://stackblitz.com/angular/bayaoxeekbm?file=app%2Fdatepicker-locale-example.ts

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.1
Node: 11.8.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.1
@angular-devkit/core         7.3.1
@angular-devkit/schematics   7.3.1
@schematics/angular          7.3.1
@schematics/update           0.13.1
rxjs                         6.3.3
typescript                   3.2.4
<code>

</code></pre>

**Anything else relevant?**

**Comment by manojvignesh** [comment]
Wrong repo, this issue is related to https://github.com/angular/material2

**Comment by pkozlowski-opensource** [comment]
Yep, please open in https://github.com/angular/material2
