### ISSUE TITLE
Language service extension showing (undefined) in tooltip error message

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#29185]
# 🐞 bug report

### Affected Package
@angular/language-service

### Is this a regression?
Most likely

### Description
When using the `@angular/language-service` and `Angular Language Service` VsCode extension and having a template error, in the the error dialogue the message is terminated with an `(undefined)` text.

## 🔬 Minimal Reproduction
* Create a new application
* Enable the VSCode Extension
* Generate a template error, for example a blank interpolation expression `{{}}`
* Hover over the error

## 🔥 Exception or Error

![image](https://user-images.githubusercontent.com/17563226/54023985-b17a6880-4196-11e9-9eea-7bb3806a1d6e.png)

However, the `(undefined)` text doesn't show when you open the problems panel.
![image](https://user-images.githubusercontent.com/17563226/54024026-cc4cdd00-4196-11e9-9ba7-077dc42325d6.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0-beta.5
Node: 10.12.0
OS: win32 x64
Angular: 8.0.0-beta.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.14.0-beta.5
@angular-devkit/build-angular     0.14.0-beta.5
@angular-devkit/build-optimizer   0.14.0-beta.5
@angular-devkit/build-webpack     0.14.0-beta.5
@angular-devkit/core              8.0.0-beta.5
@angular-devkit/schematics        8.0.0-beta.5
@angular/cli                      8.0.0-beta.5
@ngtools/webpack                  8.0.0-beta.5
@schematics/angular               8.0.0-beta.5
@schematics/update                0.14.0-beta.5
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.6
</code></pre>

**Comment by kyliau** [comment]
This should not be an issue anymore, now that the v9 extension is released. Please open a new issue if this is not the case. The latest version could be downloaded from https://marketplace.visualstudio.com/items?itemName=Angular.ng-template
