### ISSUE TITLE
No config files found.

### ISSUE THREAD

**Issue by JeremyAube** [angular/angular#29189]
# 🐞 bug report

### Affected Package
`@angular/language-service`v7.1.4
vscode's [Angular Language Service](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template) v0.1.11

### Description
I installed Angular Language Service in vscode. The language service is loading but I get the following message in the ouput window:

```
Search path: c:/Users/jÃ©rÃ©my/**file path**
No config files found.
Angular Language Service: 7.1.4
TypeScript: 3.1.6
getTemplateReferences: 107ms
getDiagnostics: 0ms
```

As far as I can see the language server doesn't load my `tsconfig.json` file which is in the default location (Project was created using angular cli). My guess is that the accents in my windows user is causing this bug.

## 🔬 Minimal Reproduction
1. Create a user with utf-8 character (é in my case)
2. Create a new Angular project with Angular/cli
3. Install Angular Language Server in vscode

## 🌍  Environment
**Angular Version**
v7.1.4

**vscode**
 v1.32.1

**Operating System**
 Windows 7 Pro

**Comment by kyliau** [comment]
This should not be an issue now that the v9 extension is released. Please open a new issue if this is not the case. The latest version could be downloaded from https://marketplace.visualstudio.com/items?itemName=Angular.ng-template
