### ISSUE TITLE
Current route is not reloaded when page is refreshed

### ISSUE THREAD

**Issue by matsko** [angular/angular#2920]
This happens when the `HashLocationStrategy` is used.

**Comment by naomiblack** [comment]
this is internal b/22263630

**Comment by rightisleft** [comment]
I'm still seeing this on alpha 35. I a route reloads correctly, but params are ignored. 

http://stackoverflow.com/questions/32429089/how-do-i-support-routeparams-on-page-reload-using-angular-2-dart?noredirect=1#comment52795245_32429089
