### ISSUE TITLE
Navigating back in iframe in IE is not recognized by router

### ISSUE THREAD

**Issue by Znert** [angular/angular#29212]
# 🐞 bug report

### Affected Package

Given that this a routing issue I assume `@angular/router` is the cause.

### Is this a regression?

I am not sure if this issue occurred in earlier versions, but as the application migrated form 5 -> 6 (after we implemented the routing feature, see below) some time ago, I can only guess that with Angular 5 routing worked as expected. Otherwise the error would have been noticed earlier.

### Description

I am currently developing a micro-frontend website which uses iframes to load different applications into it.

The architecture of the project can be best described visually:

![iframe-setup](https://user-images.githubusercontent.com/18900196/53732941-b4681700-3e7f-11e9-868e-4bb22ed0b8d8.png)

The issue here is the inner iframe. If it navigates to some route, say from `module/route` to `module/feat` the history is filled correctly, so both URLs will be in the history. However, if I click the browser back button and the state is popped, Angular in the inner iframe will fail to detect the URL change. I have verified, that the URL of the iframe is correct by executing `iframe.contentWindow.location.href`.

Same holds true if I inject `Location` from `@angular/common`.

All other browsers (including Edge) detect the URL change and correctly open the previous route.

## 🔬 Minimal Reproduction

This is where it becomes tricky. I created a minimal setup on Gitlab:

https://gitlab.com/Znert/angular-iframe-navigation-bug

However, this project does **not** reproduce the error. If you start the project and navigate inside the iframe and go back, everything works fine.

Hence all I can provide you with is a link to our (German) production site: [onfarming.at](https://onfarming.at)

If you want to reproduce the error there, you have to sign in/up first (using Google, Facbeook or just use a throwaway email - just fill the fields `E-Mail Adresse`, `Passwort` and `Passwort wiederholen`, I guess you can figure out which requires what). Then you will come to the dashboard. The easiest way to navigate within iframes is if you click on "Pflanzenschutz". Once there, use the search in the top card "Produkte finden" and enter "amistar opti". Click on any match. This will cause a navigate to the product detail page. Now you can press the back button ("Zurück") on the top left of the iframe, or the browser back. Nothing will happen.

Validate, that the iframe's url changed by getting the (only) iframe on the page and call `iframe.contentWindow.location.href`. 

## 🌍  Your Environment

**Angular Version:**

All our micro-frontends have been upgraded to Angular 7 recently, but the error occurred while on 6 as well.

The following output is of one of the inner micro-frontends, but the versions are pretty much identical between each other:

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.2
Node: 8.14.1
OS: linux x64
Angular: 7.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.2
@angular-devkit/build-angular     0.13.2
@angular-devkit/build-optimizer   0.13.2
@angular-devkit/build-webpack     0.13.2
@angular-devkit/core              7.3.2
@angular-devkit/schematics        7.3.2
@angular/cli                      7.3.2
@ngtools/webpack                  7.3.2
@schematics/angular               7.3.2
@schematics/update                0.13.2
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**
This issue was found on IE 11 on Windows 10. Older versions of IE and Windows have not been tested.

Other browser do not have the issue (to the best of my knowledge).

I researched the topic and found the following two relevant posts:

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15513159/

https://github.com/angular/angular/issues/9497

However, neither of them provide a solution (and the second one even is for AngularJS...).

**Comment by abdulkareemnalband** [comment]
Same issue is occuraring at our end
The difference is that it is Electron app. ([Addin for Microsoft teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-overview))

on `location.back()` `location.href` is updated but there are no changes in application view

```
Angular CLI: 7.3.3
Node: 11.12.0
OS: win32 x64
Angular: 7.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.3
@angular-devkit/build-angular      0.13.3
@angular-devkit/build-ng-packagr   0.13.3
@angular-devkit/build-optimizer    0.13.3
@angular-devkit/build-webpack      0.13.3
@angular-devkit/core               7.3.3
@angular-devkit/schematics         7.3.3
@angular/cdk                       7.3.3
@angular/cli                       7.3.3
@angular/material                  7.3.3
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.3
@schematics/angular                7.3.3
@schematics/update                 0.13.3
ng-packagr                         4.7.1
rxjs                               6.4.0
typescript                         3.2.4
webpack                            4.29.0
```

**Comment by ektakanojiya26** [comment]
Is there any update. I am working on the Angular 7 & facing the same issue  of browser back because of iframe

**Comment by AndrewKushnir** [comment]
Closing this ticket, since the reported problem was only present in IE11 and Angular no longer supports IE.
