### ISSUE TITLE
animations guide: incorrect links to forms groups instead of animations group

### ISSUE THREAD

**Issue by gurius** [angular/angular#29213]
# 📚 Docs wrong link report

### Description

Wrong link: At https://angular.io/guide/complex-animation-sequences all group() links redirects to https://angular.io/api/forms/FormBuilder#group which, I believe, is wrong!

### Reproduction Steps**

1) Go to https://angular.io/guide/complex-animation-sequences
2) Click any group() link

### Expected vs Actual Behavior**

Apparently group() link on animation docs page should refer to https://angular.io/api/animations/group 

### Browser info

Chromium
Version 72.0.3626.121 (Official Build) Arch Linux (64-bit)

**Comment by jenniferfell** [comment]
Good catch! At the top of the doc, we probably want to link to the subsection below: 

https://angular.io/guide/complex-animation-sequences#parallel-animation-using-group-function

Within that section, I agree we should link to:
https://angular.io/api/animations/group

Note to authors: Also, we have too many links. We don't need to link every time we write "group()". No links for subsection titles. Link on 1st use in the section, from alert or callout box, and any "see also" references.

**Comment by santoshyadav198613** [comment]
Hi @jenniferfell ,

Taking this up.

**Comment by chembu** [comment]
Hi Santhosh,

I can take care of this one. Thank you.

**Comment by santoshyadav198613** [comment]
> Hi Santhosh,
> 
> I can take care of this one. Thank you.

Cool go ahead.

**Comment by chembu** [comment]
The wrong links are generated by disambiguators that try to guess the API links that the API names refer to. I can manually update those links to point to the right reference links. But cannot remove the many links we have in the doc as they are auto-links.

**Comment by kapunahelewong** [comment]
Please see #26696 for more context. Thank you @METACEO. :)

**Comment by gkalpak** [comment]
Fixed in #30618.
