### ISSUE TITLE
A Component with two interfaces will generate an error in transformers

### ISSUE THREAD

**Issue by TedSander** [angular/angular#2921]
A component that has two interfaces in their declaration will create an invalid ng_deps

Example:
  class MaterialInput implements ControlValueAccessor, NgValidator {

Ng_deps.dart:
        'interfaces': const [ControlValueAccessorNgValidator]

It looks like it is just missing a coma in the codegen.

**Comment by TedSander** [comment]
@rkirov @jakemac53

**Comment by munificent** [comment]
This is fixed now, by https://github.com/angular/angular/pull/2941.
