### ISSUE TITLE
Angular Library

### ISSUE THREAD

**Issue by wernerstr** [angular/angular#29217]
This is a feature request for Angular Libraries

I am currently having to loading an entire library, when I only need a service inside it. 

I would like to be able to have separate modules inside the Angular library, and load only the module I need. For example 'import from my-lib/my-module'

I have tried creating a library inside another one using the CLI, but they always get created in the root. I have also tried manually creating a package inside the library, but cannot get it to build as part of the compiled dist.

**Comment by dawidgarus** [comment]
Tree shaking will exclude any unused module, service or component from bundle.
If You import: `import { MyModule } from 'my-lib';` only `MyModule` (and it's dependencies) will be part of bundled app. What's more, when building for production (AOT enabled) even unused components that are part of imported module will be excluded.

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
