### ISSUE TITLE
Bug in create_url_tree.ts

### ISSUE THREAD

**Issue by sgeh** [angular/angular#29221]
Routing fails, if null is provided as routing parameter.

To resolve this, check your function createNewSegmentGroup(segmentGroup, startIndex, commands) {...} on line 272 (https://github.com/angular/angular/blob/master/packages/router/src/create_url_tree.ts#L272 / commit https://github.com/angular/angular/commit/091a504377782b9338a9d7916f84fb18c5bbdcc2) and check additionally `commands[i]` for not null.

**Comment by jasonaden** [comment]
Thank you for submitting this issue. However, it appears you didn't utilize the issue template when creating it. We require that all newly created issues follow the template for the issue type.

If your situation persists, please create a new issue utilizing the template.
