### ISSUE TITLE
Add file structure section to Creating Libraries

### ISSUE THREAD

**Issue by jbogarthyde** [angular/angular#29225]
# 📚 Docs or angular.io bug report

### Description

The new [Project Files Structure](https://angular.io/guide/file-structure) page for v8 references [Creating Libraries](https://angular.io/guide/creating-libraries) for more information on the file structure of libraries. 

To make the reference true, we need to add a file-structure section to [Creating Libraries](https://angular.io/guide/creating-libraries) guide. The structure will change in v8, so that should be the target. 

### What's the affected URL? 

 [Creating Libraries](https://angular.io/guide/creating-libraries) 

Possibly also add a more specific reference to [Project Files Structure](https://angular.io/guide/file-structure).

**Comment by alan-agius4** [comment]
@santoshyadav198613, sure go ahead. Let me know if you need any help.

**Comment by santoshyadav198613** [comment]
Thanks @alan-agius4 ,
Will get back to you in case have any issues.

**Comment by santoshyadav198613** [comment]
Hi @alan-agius4 ,

Should i add it in existing Link where we have folder structure what you think.

**Comment by alan-agius4** [comment]
We can probably add it there and link to it from the create libraries page.

**Comment by santoshyadav198613** [comment]
Hi @alan-agius4 ,

Please verify,let me know if more changes are needed.
