### ISSUE TITLE
RouterLink Dynamic LInks

### ISSUE THREAD

**Issue by hooloom** [angular/angular#29234]
# 🐞 bug report

### Affected Package
@angular/router

### Is this a regression?
Yes 
### Description
I am using Firestore to create dynamic router links with an ngFor statement, the Routerlink does not work as documented.  If I just put [routerLink]=['item.link] it does not produce the correct root url/baseref.  I have tried every variance of this possible.  routerLink['../'+item.link] routerlink={{item.link}}

if I enter ['../'+item.link] the href is correct but routing does not function properly.  If I just use href the routing works correctly. `<li  *ngFor="let item of links | orderby: ['+'+'order']; let i=index;"
     >
      <a       
      style="text-decoration: none" 
      [routerLink]="['/',item.link]"
      routerLinkActive="active" 
      #rla="routerLinkActive" 
      [attr.name]="item.link"
>
   <span      
    [ngStyle]="{'color':rla.isActive ? hovercolor : 'none'}"
   >
   {{item.link}}</span></a> `

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.4
Node: 10.0.0
OS: darwin x64
Angular: 7.2.8
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.4
@angular-devkit/build-angular     0.13.4
@angular-devkit/build-optimizer   0.13.4
@angular-devkit/build-webpack     0.13.4
@angular-devkit/core              7.3.4
@angular-devkit/schematics        7.3.4
@angular/cli                      7.3.4
@angular/fire                     5.1.1
@angular/language-service         7.2.7
@ngtools/webpack                  7.3.4
@schematics/angular               7.3.4
@schematics/update                0.13.4
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**
this used to work in angular 6, I've tried variances of trying to set the base href - but that also doesn't resolve the problem.  It's really wonky.

**Comment by Airblader** [comment]
Can you please add a reproducible example that actually shows what "item.link" contains etc?

**Comment by hooloom** [comment]
<img width="889" alt="Screen Shot 2019-03-11 at 12 44 04 PM" src="https://user-images.githubusercontent.com/47499396/54201760-d592be00-44a4-11e9-92e9-b03300cdd55f.png">
this is the generated output.  
the next image is with just [href] which allows routing to work.  That's the only difference.  
<img width="1275" alt="Screen Shot 2019-03-11 at 5 57 49 PM" src="https://user-images.githubusercontent.com/47499396/54201828-ff4be500-44a4-11e9-86e9-5569d609788b.png">

**Comment by Airblader** [comment]
With reproducible example I mean a playground on a site like StackBlitz.

**Comment by maktarsis** [comment]
agree with @Airblader
@hooloom could you create a small example in stackblitz? 

I guess the problem is not in the routerlink, but in the wrong configuration
we also need to see it

btw, I would recommend try a package [routeshub ](https://www.npmjs.com/package/routeshub ) that helps to navigate predictably

**Comment by hooloom** [comment]
Inexplicably - I started the application this morning, and it is now
functioning as expected.  I can do the stackblitz later on today - and I
shall.

There were no changes between yesterday and today at time of posting.

Gotta get back to it.  Very odd behavior.

**Comment by pkozlowski-opensource** [comment]
>  I can do the stackblitz later on today - and I shall.

Closing for now as we haven't heard back
