### ISSUE TITLE
Uncaught TypeError: e.target.className.indexOf is not a function

### ISSUE THREAD

**Issue by veronesecoms** [angular/angular#29248]
I have one bootstrap modal, when i click in my svg to close the modal i reveive:

> Uncaught TypeError: e.target.className.indexOf is not a function
> at HTMLDocument.mouseup (translator.js:433)

**My svg:**

    <svg data-dismiss="modal" class="cursorPointer" (click)="editaDescricao(sortedData[i])" fill="darkorange" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z"/><path d="M0 0h24v24H0z" fill="none"/></svg>

**My angular version:**

Angular CLI: 7.3.5
Node: 8.11.3
OS: win32 x64
Angular: 7.2.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.5
@angular-devkit/build-angular     0.13.5
@angular-devkit/build-optimizer   0.13.5
@angular-devkit/core              7.3.5
@angular-devkit/schematics        7.3.5
@angular/cdk                      7.3.3
@angular/cli                      7.3.5
@angular/material                 7.3.3
@schematics/angular               7.3.5
@schematics/update                0.13.5
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.6

My importations:

```
<body>

      <!-- Font Awesome -->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
      <!-- Bootstrap core CSS -->
      <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
      <!-- Material Design Bootstrap -->
      <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.4/css/mdb.min.css" rel="stylesheet">
    
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <!-- Bootstrap tooltips -->
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
      <!-- Bootstrap core JavaScript -->
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
      <!-- MDB core JavaScript -->
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.4/js/mdb.min.js"></script>

  <app-root>
  </app-root>

</body>
```

I don't think idea about how this is doing. I recently updated angular v6 to v7 and now i have this problem

**Comment by pkozlowski-opensource** [comment]
@veronesecoms you didn't provide a minimal reproduce scenario and you are using several 3rd party libraries so we can't see the error nor can _guess_ its source - there is just not enough info here.

Please provide a minimal reproduce scenario in a stackblitz (you can start with this one: https://stackblitz.com/edit/angular-7cw5r7) - without a reproduce scenario this issue is not actionable and will be closed.

**Comment by veronesecoms** [comment]
This problem is ocurred in <svg>. When i change to a <i> everything works

**Comment by pkozlowski-opensource** [comment]
> This problem is occurred in <svg>. When i change to a everything works

This is still not helping us to reproduce the issue. But I _think_ I know what is going on - you need to be aware that `className` _property_ has _different_ type definition on HTML elements and SVG elements. Long story short is that `className` property does _not_ have  `indexOf` method as it is of type `SVGAnimatedString`. This reading might help: https://medium.com/alistapart/javascript-modify-svg-element-class-4ca3055a2024

In any case this is one of differences in the HTML vs. SVG handling you need to be aware of. This is not related to Angular so closing it here.
