### ISSUE TITLE
Scrolling inside a section is disabled when an angular overlay is open

### ISSUE THREAD

**Issue by karlboulos** [angular/angular#29243]
**Bug, feature request, or proposal:** 
Bug, I think.

**What is the current behavior?**
When opening an angular cdk overlay configured to use a backdrop and any scrolling strategy, inside a page that is scrollable from a subsection which is different from the main body section, the scroll is blocked on the entire page (even if the directive `cdkScrollable` is set on this subsection).
If the page is scrollable from its main body section, the scroll is always active when the overlay is open regardless of its configuration.

**What is the expected behavior?**
When the overlay is open, I expect the scroll to be active on **any scrollable section**, regardless the config of the overlay (with or without a backdrop and the scrolling strategy)

**What are the steps to reproduce?**
Open a cdk overlay in a page that scrolls from its main body section: 
https://stackblitz.com/edit/angular-overlay-scrolling-page
The scroll should work when the overlay is open in this case.

Open a cdk overlay in a page that scrolls from a subsection different from the body section: https://stackblitz.com/edit/angular-overlay-scrolling-section
The scroll should be blocked when the overlay is open in this case.

**Environment**
Angular 7, Chrome

**Comment by pkozlowski-opensource** [comment]
Please open in https://github.com/angular/material2
