### ISSUE TITLE
docs(upgrade): list supported/unsupported features

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#29245]
# 📚 Docs or angular.io bug report

### Description

The now deprecated dynamic version of ngUpgrade used to have a [list of supported/unsupported features][1].
It would be a good idea to have a similar list for the new (static) ngUpgrade (e.g. in [UpgradeComponent][2] API docs).

### Related issues

- #22824.

[1]: https://angular.io/api/upgrade/UpgradeAdapter#supported-features-1
[2]: https://angular.io/api/upgrade/static/UpgradeComponent

**Comment by kapunahelewong** [comment]
Status: Team will need to partner with an engineer to make sure we get all of the correct info.

**Comment by atscott** [comment]
Closing - ngUpgrade is nearing end of life and we won't likely be investing in expanding the docs on it.
