### ISSUE TITLE
CI: Merge script should fail if there are fixups after merge

### ISSUE THREAD

**Issue by kara** [angular/angular#29268]
We have a merge script here:

https://github.com/angular/angular/blob/master/scripts/github/merge-pr

Caretakers use this script to merge PRs that are green. However, we've been noticing issues lately where fixup commits sometimes aren't squashed as expected and make it into master. 

Latest example:

https://github.com/angular/angular/pull/28296
https://github.com/angular/angular/commits/master

In that case, it seems like it happened because the message in the fixup commit didn't match any commit messages before it. 

It would be nice if the merge script could check to see if there are fixup commits remaining after merge and throw a friendly error. This would prevent caretakers from accidentally muddying the commit history with a bad squash.

**Comment by gkalpak** [comment]
Not the same thing, but for reference the `validate-commit-message` script checks that `fixup` commits have a matching earlier commit:

https://github.com/angular/angular/blob/d43187f7ef7e841d84ecf594e8e515a9d534daaa/tools/validate-commit-message/validate-commit-message.js#L39-L46

**Comment by AndrewKushnir** [comment]
@devversion could you please let us know if there are checks for orphaned fixup commits in the new merge script?

**Comment by devversion** [comment]
@AndrewKushnir Oh yeah. Thanks for the ping. That seems like a good addition to the merge script. I'll work on that!

**Comment by AndrewKushnir** [comment]
@jelbourn I haven't seen this issue for quite some time, but @josephperrott can confirm if this scenario is covered by the new merged script.

**Comment by josephperrott** [comment]
This is checked by the commit message testing on CI during the PRs presubmit process, so while this is not directly addressed in the merge script, it is already checked before the merge even occurs.

I am going to close this out as the spirit of this request is already addressed in our process while its execution ended up slightly different.
