### ISSUE TITLE
The FormGroup cannot obtain the latest valid status in real time.

### ISSUE THREAD

**Issue by DreamLi1314** [angular/angular#29273]
# 1. Environment:
* OS: Windows 10
* Angular: 6.1.3/7.2.5
* Browser: firefox 65.0.2 - 64 bit

# 2.  Description:
&nbsp;&nbsp;&nbsp;&nbsp;'formgroup.valid' always displays the previous state in valuechanges.subscribe of FormControl when using FormGroup/FormControl for data validation.

# 3. Issue
* open this demo: [Angular-Form-Demo](https://stackblitz.com/edit/angular-forms-test01)
* The string in the input is gradually deleted until the input value is empty.
* The valid value is true, which should be false, because the value of the input is required.

# 4. The core code
``` typescript
  name = 'Angular';
  form: FormGroup;
  valid: boolean = true;
  ngOnInit() {
      this.form = this.fb.group({
         name: [this.name, Validators.required]
      });

      this.form.controls["name"].valueChanges.subscribe((v) => {
          this.name = v;
          this.printValid();
      });
  }

  printValid() {
    this.valid = this.form.valid;
  }
```

``` html
<form [formGroup]="form">
  <input formControlName="name"  />

  <br>

  valid: {{valid}}

</form>
```

# 5. Result:
> **`form.valid` seems to always be the previous value.**
![Result 1](https://user-images.githubusercontent.com/23147720/54263752-85068800-45ac-11e9-9dbb-dfb92d4b8394.png)

![Result 2](https://user-images.githubusercontent.com/23147720/54263772-918ae080-45ac-11e9-9f64-e3fc51f28f84.png)

![Result 3](https://user-images.githubusercontent.com/23147720/54263796-a5cedd80-45ac-11e9-95d5-8a6d3e045706.png)

**Comment by tashoecraft** [comment]
So your assumption isn't quite true. You're saying that form.valid always shows the previous state, but that's because you bind to the state value as soon as the value change happens, not after the validation has run. You can see this by either binding your html template to
```
valid: {{form.valid}}
```

or by using setTimeout to really showcase what's going on
```
      this.form.controls["name"]
      .valueChanges
      .subscribe((v) => {
        setTimeout(() => {
          this.printValid();
        }, 0);
      });
```
this now works fine because the validation was able to run and update the status on the form control which updated the parent group status. You could either track the statusChanges obserable, or just reference the form.valid in the template. But otherwise there doesn't appear to be any bug with angular forms.

**Comment by DreamLi1314** [comment]
I know by setTimeout() can get the latest valid state, of course, you can do that in this demo, but I think in large projects excessive use setTimeout is not a good coding habits, and my project is just in valueChanges.subscribe will the form.valid values emit to the top level control some disable state, so the template value does not seem to have what use.

I just want to know is Angular right that like as you see this? I don't think so. So please fix it.

thank you!

**Comment by manklu** [comment]
@DreamLi1314 You should subscribe to status updates of the formgroup to get up to date information

https://stackblitz.com/edit/angular-forms-test01-ndfrme

**Comment by tashoecraft** [comment]
@DreamLi1314 What I was getting at is this isn't a bug with Angular, the setTimeout was merely a demonstration of what is going wrong. You shouldn't be subscribing to value changes and expecting the model to have updated when the value gets emitted. The setTimeout proved the model is about to update, but you're taking the status too early. Instead you should be doing what @manklu suggested, and subscribe to the status updates. 

There is no bug in Angular for this so there is nothing to fix.

**Comment by DreamLi1314** [comment]
> @DreamLi1314 You should subscribe to status updates of the formgroup to get up to date information
> 
> https://stackblitz.com/edit/angular-forms-test01-ndfrme

**Comment by DreamLi1314** [comment]
This is really a good way to deal with this problem. Thank you, @tashoecraft @manklu 
I'm going to rewrite a [Demo](https://stackblitz.com/edit/angular-forms-test02) to describe the application in a real project and to prompt users who have the same problem in the future.
However, there will still be a case where form. Valid is true while form.controls["name"].valid is false. It should be noted that this seems to be only a synchronization problem caused by time.

[See the project to fix this problem](https://stackblitz.com/edit/angular-forms-test02)

![image](https://user-images.githubusercontent.com/23147720/54406742-2bba6800-4716-11e9-879f-959f64795fa0.png)
