### ISSUE TITLE
Error: Can't resolve all parameters for ApplicationModule: (?). when running ng test after upgrading to angular 7

### ISSUE THREAD

**Issue by Slash7GNR** [angular/angular#29281]
# 🐞 bug report

### Affected Package

 It happened after upgrading my app to angular version 7.2

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular version 5.2

### Description

 A clear and concise description of the problem...
I'm upgrading my project to angular 7.2 from angular 5.2. I did the following:
1. Upgraded all angular packages package.json to ~7.2.0
2. ran ng upgrade @angular/cli
3. ran ng upgrade @angular/core
4. ran ng test and got the error:
`
Chrome 68.0.3440 (Windows 8.1.0.0) NdvAction ndv!!!! FAILED
        Error: Can't resolve all parameters for ApplicationModule: (?).
            at syntaxError node_modules/@angular/compiler/fesm5/compiler.js:2426:1)
            at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getDependenciesMetadata node_modules/@angular/compiler/fesm5/compiler.js:18979:1)
            at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getTypeMetadata node_modules/@angular/compiler/fesm5/compiler.js:18872:1)
            at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata node_modules/@angular/compiler/fesm5/compiler.js:18740:1)
            at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleSummary node_modules/@angular/compiler/fesm5/compiler.js:18550:1)
            at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/compiler/fesm5/compiler.js:18664:1
            at Array.forEach (<anonymous>)
            at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata node_modules/@angular/compiler/fesm5/compiler.js:18652:1)
            at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleSummary node_modules/@angular/compiler/fesm5/compiler.js:18550:1)
Chrome 68.0.3440 (Windows 8.1.0.0): Executed 1 of 395 (1 FAILED) (skipped 394) ERROR (0.527 secs / 0.038 secs)
`

## 🔬 Minimal Reproduction

Sorry but I couldn't create a small project to reproduce the issue, but I could isolate the issue on my own project.
On my project, I created an empty service:
```
import { Injectable } from '@angular/core';

@Injectable()
export class NdvAction {
}
```
With an empty unit test:
```
import { TestBed, inject } from '@angular/core/testing';
import { NdvAction } from './ndv.action';

fdescribe('NdvAction', () => {
  let target: NdvAction;

  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [NdvAction]
    });
  });

  beforeEach(inject([NdvAction],
    (service: NdvAction) => {
      target = service;
    }));

  it('ndv!!!!', () => {});
});

```
And the error reproduced, when I removed the beforeEach with the inject([NdvAction] part, the error disappeared.
Any idea what I'm doing wrong ? If you need any more details please let me know so that I'll add.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
package.json:
```
"dependencies": {
    "@angular-redux/store": "~9.0.0",
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/http": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@ngx-translate/core": "~11.0.0",
    "@ngx-translate/http-loader": "~4.0.0",
    "angular2-moment": "^1.0.0",
    "core-js": "2.4.1",
    "cyb-core": "1.0.17-ng7",
    "shell-utils": "~2.1.0",
    "intl": "1.2.5",
    "json-typescript-mapper": "1.1.3",
    "lodash": "4.17.4",
    "lodash-es": "4.16.0",
    "lodash.get": "4.4.2",
    "normalize.css": "4.2.0",
    "normalizr": "3.2.3",
    "primeng": "^5.2.4",
    "redux": "~4.0.0",
    "reflect-metadata": "0.1.10",
    "rxjs": "~6.4.0",
    "rxjs-compat": "~6.3.0",
    "sass-flex-mixin": "1.0.3",
    "string-template": "^1.0.0",
    "tslib": "^1.9.0",
    "web-animations-js": "2.3.1",
    "zone.js": "0.8.27"
  },
  "devDependencies": {
    "awesome-typescript-loader": "2.2.4",
    "@types/lodash": "4.14.120",
    "@angular-devkit/build-angular": "0.12.1",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/cli": "~7.2.0",
    "@types/jasmine": "2.5.46",
    "@types/node": "7.0.18",
    "codelyzer": "3.1.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "3.2.0",
    "karma": "1.5.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.0.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.1.0",
    "ts-node": "3.0.2",
    "tslint": "~5.12.0",
    "typescript": "~3.2.0",
    "test-reducer": "^2.0.2"
  }
```

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.2.4
Node: 8.9.1
OS: win32 x64
Angular: 7.2.6
... core

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.12.1
@angular-devkit/build-angular       0.12.1
@angular-devkit/build-optimizer     0.12.1
@angular-devkit/build-webpack       0.12.1
@angular-devkit/core                7.2.1
@angular-devkit/schematics          7.2.4
@angular/animations                 7.2.8
@angular/cli                        7.2.4
@angular/common                     7.2.0
@angular/compiler                   7.2.0
@angular/compiler-cli               7.2.0
@angular/forms                      7.2.0
@angular/http                       7.2.0
@angular/platform-browser           7.2.0
@angular/platform-browser-dynamic   7.2.0
@angular/router                     7.2.0
@ngtools/webpack                    7.2.1
@schematics/angular                 7.2.4
@schematics/update                  0.12.4
rxjs                                6.4.0
typescript                          3.2.4
webpack                             4.23.1

</code></pre>

**Anything else relevant?**

I tried to import reflect-metadata, import 'core-js/es7/reflect'; on the polyfills.ts file like previous issues suggested, but it didn't help.
If there's anything else that could help to understand the issue please let me know. Thanks!

**Comment by rynrn** [comment]
+1

**Comment by Slash7GNR** [comment]
Hey,
So after a full day investigating the issue, I could workaround the issue by adding import 'reflect-metadata' on the head of my test.ts file. But I don't feel like this is the correct solution, any other ideas ?

**Comment by alxhub** [comment]
Sorry, but without a working reproduction we'll be unable to help with this problem.

**Comment by irejwanul** [comment]
In angular 8 project, the issue occurs because of order of polyfills imports.
Also, polyfills of ‘reflect-metadata’ required to be followed by ‘zone.js’ or ‘zone.js/dost/zone’
After that remaining polyfills are imports.
This is why it is already warned that ‘import order is matter’

**Comment by Sparker73** [comment]
There are too many searches in the web today around this subject, even when only 10% of them is really relying on the way developers setup and use dependency injection (me included).
I have seen too many cases in which this error goes on and on and sometimes it is produced at compile time and some others at runtime.
In my case the app was working great and after adding SSR support for a specific route, the server.ts file looks like it needs some of these tweaks because the routes work well but the specific route that needs SEO with SSR throws this error at runtime.
I had several expert eyes on my code and all dependencies are well crafted. If I comment the code where routes are rendered or index.html served then it works well. So my path should be digging around SSR implementation (/server.ts in particular since this file is responsible for encapsulating everything, but that is my guess).

**Comment by pkozlowski-opensource** [comment]
As @alxhub [pointed out](https://github.com/angular/angular/issues/29281#issuecomment-484715054) we can't move forward on this issue without a reproduce scenario. If anyone is hitting problems described here please open a new ticket and share with us a reproduce scenario (stackblitz and / or minimal GitHub repo). Thnx!
