### ISSUE TITLE
Angular langauge service not typing nested array objects

### ISSUE THREAD

**Issue by DesHorsley** [angular/angular#29291]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/language-service: 7.2.3

### Description

When using nested arrays of strongly typed objects, in ngFor, the inner objects lose their strong typing and don't display errors on properties or suggest existing properties.

## 🔬 Minimal Reproduction
To reproduce the issue, clone this repo: https://github.com/TylerHaigh/angular-language-server-nested-arrays

run `npm install`

And check out `src/app/app.component.html`, line 12 is correct and works, line 13 is a bug, does not show as an error, and there is no intellisense or warnings that the developer has a typo (missing the `is` in `isCritical`)

It seems like on line 10 at this point `*ngFor="let test of accession.testSet"` the language service gives up trying to type the objects and just assumes it's an `any`

Our hope was that we'd have full intellisense and error detection on the test object used after line 10

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 1.7.4
Node: 8.12.0
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic

@angular/cli: 1.7.4
@angular/language-service: 7.2.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0

</code></pre>

This is evident in VS Code 1.31.1

**Comment by kyliau** [comment]
Broader issue related to this: Stricter type checking in Angular templates

**Comment by kyliau** [comment]
This has been fixed in https://github.com/angular/angular/pull/33676
