### ISSUE TITLE
ng new not working 

### ISSUE THREAD

**Issue by sathwiq** [angular/angular#29306]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please file any Angular CLI issues at: https://github.com/angular/angular-cli/issues/new

For the time being, we keep Angular CLI issues in a separate repository.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by sathwiq** [comment]
npm ERR! Unexpected end of JSON input while parsing near '...+EuGeFfIM3zMCaRLePh 7u'
--

**Comment by pkozlowski-opensource** [comment]
> Please file any Angular CLI issues at: https://github.com/angular/angular-cli/issues/new
For the time being, we keep Angular CLI issues in a separate repository.
