### ISSUE TITLE
Firefox Quantom 65.0.2(64-bit)

### ISSUE THREAD

**Issue by sysmat** [angular/angular#29304]
# 🐞 bug report

### Affected Package
I don't know

### Description

App not working

## 🔥 Exception or Error
<pre><code>

ERROR Error: "[object Object]"

    resolvePromise11Angular

core.js:15723

    defaultErrorLogger4Angular

defaultErrorLogger
handleError
next
schedulerFn
__tryOrUnsub5RxJS
emit14Angular

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.5
Node: 10.11.0
OS: win32 x64
Angular: 7.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.5
@angular-devkit/build-angular     0.13.5
@angular-devkit/build-optimizer   0.13.5
@angular-devkit/build-webpack     0.13.5
@angular-devkit/core              7.3.5
@angular-devkit/schematics        7.3.5
@angular/cli                      7.3.5
@ngtools/webpack                  7.3.5
@schematics/angular               7.3.5
@schematics/update                0.13.5
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**

browser specific issue with firefox

**Comment by skreborn** [comment]
Can you please provide a reproduction over on StackBlitz? You really haven't given anything to go on here except for an obscure error.

**Comment by jmac11** [comment]
Love

**Comment by jmac11** [comment]
More lovely stuff

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
