### ISSUE TITLE
504 gateway timeout

### ISSUE THREAD

**Issue by BLecha** [angular/angular#29310]
I created a project ng new testpwa
then add pwa ng add @angular/pwa all latest cli ng and pwa.

I have on my local IIS under default website a web api project visions under vision I added a new web api project testpwa which is pinting to the dist/testpwa folder of my ng project I described above.

so in my testpwa angular project i run ng build --prod.

The I go on the chrome browser in incognito mode and navigate to my https://localhost/visions/testpwa/ and my ng app open and runs no problem. Then I go to devtools application tab and I can see the ngsw-worker.js is registered then I select offline and update on reload in the application tab of devtools and reload the page everything works as expected the ng app is displayed and my external images from the web are also displayed in the network tab in size column I can see they are loaded from the service worker.

But when I take out my cabel and physically disconnect from internet and realod the ng app everything works fine except the external images from the web. Its says 504 timeout and is red the network tab.

I added everything to datagroups in the urls. I dont know why it does not load the images from the service worker when I physically disconnect internet but loads them when I simulate it through dev tools offline mode.

I did a lot of research on the internet but nothing usefull so far for this specific problem.

Kind Regards

Lecha

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by BLecha** [comment]
@pkozlowski-opensource  and  based on what did you determine this? If I may ask?
