### ISSUE TITLE
I found ngif will be block mousemove event

### ISSUE THREAD

**Issue by huan-qi** [angular/angular#29323]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

    <div #testDiv style="width: 1000px; height: 1000px; background-color: #808080">
      <canvas id="testCanvas"></canvas>
    </div>

    <div *ngFor="let data of testlist">
      <span *ngFor="let data of testlist">
        <span *ngIf="data.id != null"></span>

      </span>
    </div>

I tested mousemove this way. listening 'testDiv' mousemove event.  
 if i do not use ngif  ，the mousemove execution frequency is 16ms. 
when i use the ngif , the mousemove execution frequency is 25ms.
if i subscribe to the mousemove event twice, the execution frequency will be 77ms.

my data length is 100.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
