### ISSUE TITLE
[Ivy] Error: Unknown node type: function LiteralMap

### ISSUE THREAD

**Issue by pshurygin** [angular/angular#29327]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler-cli

### Is this a regression?

There is no such problem with ViewEngine

### Description

I'm trying to build a pretty large application with Ivy using latest beta version, but the build fails with the error messages posted below.

## 🔬 Minimal Reproduction

I have found that the Error1 (see below) is caused by this component annotation:

```
@Component({
    selector: 'sm-chart',
    template: `<div [ngStyle]="{'width': width, 'height': height}" style="position: relative">
                   <canvas #canvas class="chart chart-{{type}}"></canvas>
               </div>`,
    changeDetection: ChangeDetectionStrategy.OnPush
})
```

As soon as I remove [ngStyle] binding the Error1 is gone, but Error2(see below) arises, which is probably caused by the same root issue. Error2 seems to be related to ng-select library we are using in the project. Here is the element definition from the tcbProcessDirective method which causes the Error2:

<details>
  <summary>Click to expand</summary>
  
<pre><code>
Element {
  name: 'ng-select',
  attributes: [],
  inputs:
   [ BoundAttribute {
       name: 'smError',
       type: 0,
       securityContext: 0,
       value: [ASTWithSource],
       unit: null,
       sourceSpan: [ParseSourceSpan],
       i18n: undefined },
     BoundAttribute {
       name: 'smErrorMessage',
       type: 0,
       securityContext: 0,
       value: [ASTWithSource],
       unit: null,
       sourceSpan: [ParseSourceSpan],
       i18n: undefined },
     BoundAttribute {
       name: 'ng-select-error',
       type: 2,
       securityContext: 0,
       value: [ASTWithSource],
       unit: null,
       sourceSpan: [ParseSourceSpan],
       i18n: undefined },
     BoundAttribute {
       name: 'ngClass',
       type: 0,
       securityContext: 0,
       value: [ASTWithSource],
       unit: null,
       sourceSpan: [ParseSourceSpan],
       i18n: undefined },
     BoundAttribute {
       name: 'items',
       type: 0,
       securityContext: 0,
       value: [ASTWithSource],
       unit: null,
       sourceSpan: [ParseSourceSpan],
       i18n: undefined },
     BoundAttribute {
       name: 'loading',
       type: 0,
       securityContext: 0,
       value: [ASTWithSource],
       unit: null,
       sourceSpan: [ParseSourceSpan],
       i18n: undefined },
     BoundAttribute {
       name: 'placeholder',
       type: 0,
       securityContext: 0,
       value: [ASTWithSource],
       unit: null,
       sourceSpan: [ParseSourceSpan],
       i18n: undefined },
     BoundAttribute {
       name: 'typeahead',
       type: 0,
       securityContext: 0,
       value: [ASTWithSource],
       unit: null,
       sourceSpan: [ParseSourceSpan],
       i18n: undefined },
     BoundAttribute {
       name: 'ngModel',
       type: 0,
       securityContext: 0,
       value: [ASTWithSource],
       unit: null,
       sourceSpan: [ParseSourceSpan],
       i18n: undefined },
     BoundAttribute {
       name: 'notFoundText',
       type: 0,
       securityContext: 0,
       value: [ASTWithSource],
       unit: null,
       sourceSpan: [ParseSourceSpan],
       i18n: undefined },
     BoundAttribute {
       name: 'typeToSearchText',
       type: 0,
       securityContext: 0,
       value: [ASTWithSource],
       unit: null,
       sourceSpan: [ParseSourceSpan],
       i18n: undefined },
     BoundAttribute {
       name: 'loadingText',
       type: 0,
       securityContext: 0,
       value: [ASTWithSource],
       unit: null,
       sourceSpan: [ParseSourceSpan],
       i18n: undefined } ],
  outputs:
   [ BoundEvent {
       name: 'ngModelChange',
       type: 0,
       handler: [ASTWithSource],
       target: null,
       phase: null,
       sourceSpan: [ParseSourceSpan],
       handlerSpan: [ParseSourceSpan] },
     BoundEvent {
       name: 'clear',
       type: 0,
       handler: [ASTWithSource],
       target: null,
       phase: null,
       sourceSpan: [ParseSourceSpan],
       handlerSpan: [ParseSourceSpan] },
     BoundEvent {
       name: 'change',
       type: 0,
       handler: [ASTWithSource],
       target: null,
       phase: null,
       sourceSpan: [ParseSourceSpan],
       handlerSpan: [ParseSourceSpan] } ],
  children:
   [ Text { value: '\n\n    ', sourceSpan: [ParseSourceSpan] },
     Template {
       tagName: 'ng-template',
       attributes: [Array],
       inputs: [],
       outputs: [],
       templateAttrs: [],
       children: [Array],
       references: [],
       variables: [],
       sourceSpan: [ParseSourceSpan],
       startSourceSpan: [ParseSourceSpan],
       endSourceSpan: [ParseSourceSpan],
       i18n: undefined },
     Text { value: '\n\n    ', sourceSpan: [ParseSourceSpan] },
     Template {
       tagName: 'ng-template',
       attributes: [Array],
       inputs: [],
       outputs: [],
       templateAttrs: [],
       children: [Array],
       references: [],
       variables: [Array],
       sourceSpan: [ParseSourceSpan],
       startSourceSpan: [ParseSourceSpan],
       endSourceSpan: [ParseSourceSpan],
       i18n: undefined },
     Text { value: '\n\n    ', sourceSpan: [ParseSourceSpan] },
     Template {
       tagName: 'ng-template',
       attributes: [Array],
       inputs: [],
       outputs: [],
       templateAttrs: [],
       children: [Array],
       references: [],
       variables: [],
       sourceSpan: [ParseSourceSpan],
       startSourceSpan: [ParseSourceSpan],
       endSourceSpan: [ParseSourceSpan],
       i18n: undefined },
     Text { value: '\n', sourceSpan: [ParseSourceSpan] } ],
  references: [],
  sourceSpan:
   ParseSourceSpan {
     start:
      ParseLocation { file: [ParseSourceFile], offset: 0, line: 0, col: 0 },
     end:
      ParseLocation { file: [ParseSourceFile], offset: 691, line: 13, col: 62 },
     details: null },
  startSourceSpan:
   ParseSourceSpan {
     start:
      ParseLocation { file: [ParseSourceFile], offset: 0, line: 0, col: 0 },
     end:
      ParseLocation { file: [ParseSourceFile], offset: 691, line: 13, col: 62 },
     details: null },
  endSourceSpan:
   ParseSourceSpan {
     start:
      ParseLocation { file: [ParseSourceFile], offset: 1203, line: 28, col: 0 },
     end:
      ParseLocation { file: [ParseSourceFile], offset: 1215, line: 28, col: 12 },
     details: null },
  i18n: undefined } { ref:
   Reference {
     node:
      NodeObject {
        pos: 1160,
        end: 7547,
        flags: 4194304,
        transformFlags: undefined,
        parent: [SourceFileObject],
        kind: 240,
        decorators: undefined,
        modifiers: [Array],
        name: [IdentifierObject],
        typeParameters: undefined,
        heritageClauses: [Array],
        members: [Array],
        modifierFlagsCache: 536870915,
        symbol: [SymbolObject],
        localSymbol: [SymbolObject],
        nextContainer: [NodeObject] },
     identifiers: [ [IdentifierObject] ],
     _alias: null,
     bestGuessOwningModule:
      { specifier: '@ng-select/ng-select',
        resolutionContext:
         'D:/Solomoto/impl/solo/SolomotoWebRole/node_modules/@ng-select/ng-select/ng-select/ng-select.module.d.ts' } },
  name: 'NgSelectComponent',
  isComponent: true,
  selector: 'ng-select',
  exportAs: [],
  inputs:
   { clearable: 'clearable',
     markFirst: 'markFirst',
     dropdownPosition: 'dropdownPosition',
     loading: 'loading',
     closeOnSelect: 'closeOnSelect',
     hideSelected: 'hideSelected',
     selectOnTab: 'selectOnTab',
     bufferAmount: 'bufferAmount',
     selectableGroup: 'selectableGroup',
     selectableGroupAsModel: 'selectableGroupAsModel',
     searchFn: 'searchFn',
     excludeGroupsFromDefaultSelection: 'excludeGroupsFromDefaultSelection',
     clearOnBackspace: 'clearOnBackspace',
     labelForId: 'labelForId',
     autoCorrect: 'autoCorrect',
     autoCapitalize: 'autoCapitalize',
     multiple: 'multiple',
     addTag: 'addTag',
     searchable: 'searchable',
     isOpen: 'isOpen',
     items: 'items',
     compareWith: 'compareWith',
     clearSearchOnAdd: 'clearSearchOnAdd',
     bindLabel: 'bindLabel',
     placeholder: 'placeholder',
     notFoundText: 'notFoundText',
     typeToSearchText: 'typeToSearchText',
     addTagText: 'addTagText',
     loadingText: 'loadingText',
     clearAllText: 'clearAllText',
     virtualScroll: 'virtualScroll',
     openOnEnter: 'openOnEnter',
     bindValue: 'bindValue',
     appendTo: 'appendTo',
     maxSelectedItems: 'maxSelectedItems',
     groupBy: 'groupBy',
     groupValue: 'groupValue',
     typeahead: 'typeahead' },
  outputs:
   { blurEvent: 'blur',
     focusEvent: 'focus',
     changeEvent: 'change',
     openEvent: 'open',
     closeEvent: 'close',
     searchEvent: 'search',
     clearEvent: 'clear',
     addEvent: 'add',
     removeEvent: 'remove',
     scroll: 'scroll',
     scrollToEnd: 'scrollToEnd' },
  queries:
   [ 'optionTemplate',
     'optgroupTemplate',
     'labelTemplate',
     'multiLabelTemplate',
     'headerTemplate',
     'footerTemplate',
     'notFoundTemplate',
     'typeToSearchTemplate',
     'loadingTextTemplate',
     'tagTemplate',
     'ngOptions' ],
  hasNgTemplateContextGuard: false,
  ngTemplateGuards: [] }
</code></pre>
</details>

## 🔥 Exception or Error
Error1:
<pre><code>ERROR in : Error: Unknown node type: function LiteralMap(span, keys, values) {
            var _this = _super.call(this, span) || this;
            _this.keys = keys;
            _this.values = values;
            return _this;
        }
    at astToTypescript (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:96:19)
    at Object.astToTypescript (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:52:20)
    at tcbExpression (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:413:29)
    at processAttribute (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:454:28)
    at Array.forEach (<anonymous>)
    at tcbGetInputBindingExpressions (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:442:19)
    at tcbProcessDirective (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:313:24)
    at D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:300:52
    at Array.forEach (<anonymous>)
    at tcbProcessDirectives (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:300:20)
</code></pre>

Error2:
<pre><code>ERROR in : Error: Unknown node type: function BindingPipe(span, exp, name, args) {
            var _this = _super.call(this, span) || this;
            _this.exp = exp;
            _this.name = name;
            _this.args = args;
            return _this;
        }
    at astToTypescript (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:96:19)
    at Object.astToTypescript (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:52:20)
    at tcbExpression (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:413:29)
    at processAttribute (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:454:28)
    at Array.forEach (<anonymous>)
    at tcbGetInputBindingExpressions (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:442:19)
    at tcbProcessDirective (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:313:24)
    at D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:300:52
    at Array.forEach (<anonymous>)
    at tcbProcessDirectives (D:\Solomoto\impl\solo\SolomotoWebRole\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:300:20)
</code></pre>
## 🌍  Your Environment

**Angular Version:**
<pre><code>8.0.0-beta.8</code></pre>

**@ngtools/webpack Version:**
<pre><code>8.0.0-beta.7</code></pre>

**Comment by rcketscientist** [comment]
Seeing the `LiteralMap` error as well.  Any ideas?

**Comment by speige** [comment]
+1

**Comment by jponeill** [comment]
For anyone trying to get around this before it's fixed, changing "fullTemplateTypeCheck" from true to false in tsconfig.app.json gets rid of the error for me.
