### ISSUE TITLE
why the files of vendor.bundle.js  are different when compile the same project?

### ISSUE THREAD

**Issue by zenghuiLee** [angular/angular#29325]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

why the files of vendor.bundle.js  are different when compile the same project?

compile the same angular project twice,but the content of vendor.bundle.js is different 

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by luhan1997** [comment]
???

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Please open cli issues in its repo https://github.com/angular/angular-cli :+1:
