### ISSUE TITLE
Angular and Polyfills no longer working on IE 11

### ISSUE THREAD

**Issue by DotNetDemon** [angular/angular#29333]
# 🐞 bug report

### Is this a regression?

 Worked prior to February 2019

### Description
 
IE is reporting "Object doesn't support property or method 'includes'." Have turned on IE compatibility in polyfills TS and updated per instructions but still not rendering.

## 🔥 Exception or Error
ERROR TypeError: Object doesn't support property or method 'includes'

## 🌍  Your Environment

**Angular Version:**
<pre><code>@angular-devkit/architect    0.8.1
@angular-devkit/core         0.8.1
@angular-devkit/schematics   0.8.1
@schematics/angular          0.8.1
@schematics/update           0.8.1
rxjs                         6.2.2
typescript                   2.9.2
</code></pre>

**Anything else relevant?**

Internet Explorer 11

![ie_render](https://user-images.githubusercontent.com/48595432/54439369-07a75880-470f-11e9-9c04-4b0859247f11.png)
![edge_render](https://user-images.githubusercontent.com/48595432/54439370-07a75880-470f-11e9-8272-c08e94198c7e.png)

**Comment by pkozlowski-opensource** [comment]
I'm sorry but you will have to isolate this one more. It is not possible to act on just error message as we don't know where the `includes` come from. It is not part of Angular but might come from the application code, 3rd party components etc. 

I'm going to close it here as we don't have reproduce scenario and Angular itself is not using `.includes` anywhere. I would suggest searching for `.includes` in your application code and dependencies to isolate the problem and either remove this usage or polyfill it. In any case this is not something that Angular can fix.
