### ISSUE TITLE
`providedIn: null` has the same effect as `providedIn: 'root'`

### ISSUE THREAD

**Issue by dwiyatci** [angular/angular#29330]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core.

### Is this a regression?

 No, I don't think so.

### Description

 Creating a service/token with `providedIn: null` makes it still be able to be injected. Actually, not sure if this is by design, though.

#### Steps to reproduce
- Create a service/token with `providedIn: null`, e.g.
```typescript
import { InjectionToken } from '@angular/core';

export interface MyService {
  getValue(): any;
  setValue(val: any): any;
}

export const MY_SERVICE_TOKEN = new InjectionToken<MyService>('MyService', {
  //providedIn: 'root',
  providedIn: null, // passing null has the same effect as passing 'root'
  factory() {
    let value = 42;

    const service = {
      getValue() {
        return value;
      },

      setValue(val) {
        value = val;
      }
    };

    return service;
  }
});
```

- Inject the service to a component, e.g.
```typescript
export class HelloComponent  {
  @Input() name: string = 'Glenn';

  constructor(@Inject(MY_SERVICE_TOKEN) private myService: MyService) {
    console.log(`myService value: ${myService.getValue()}`);
  }
}
```

- Observe whether it throws.

#### Actual
- The "providedIn: null" service is still able to be injected.

#### Expected
- The "providedIn: null" service should not be able to be injected and Angular should throw.

## 🔬 Minimal Reproduction

 
https://stackblitz.com/edit/angular-f16k9z

## 🔥 Exception or Error
<pre><code>N/A.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 7.0.7
Node: 10.13.0
OS: darwin x64
Angular: 7.2.8
... animations, common, compiler, core, forms, http
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@angular/compiler-cli             7.0.4
@angular/language-service         7.0.4
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.4.0
typescript                        3.1.6
webpack                           4.19.1
</code></pre>

**Anything else relevant?**

N/A.

**Comment by atscott** [comment]
The behavior is actually identical to `undefined` but I think this is still a documentation issue because the behavior for `null` and `undefined` are not described in the [docs for Injectable](https://angular.io/api/core/Injectable).
