### ISSUE TITLE
Build guide could be more clear about where to create proxy.conf.json

### ISSUE THREAD

**Issue by avin-kavish** [angular/angular#29337]
![image](https://user-images.githubusercontent.com/48435155/54452285-ce0c3700-477a-11e9-8649-a01e593ebcaf.png)

What does this mean? What do you mean when you say next to `package.json`. What is next to `package.json`, The `src/` folder or the newly created `proxy.conf.json`? Either way, is it not incorrect? Can something ever be next to something else in a directory structure? It depends on the sorting algorithm used by your file explorer.

Reproduce here: https://angular.io/guide/build

**Comment by jenniferfell** [comment]
Thank you for requesting clarification. "next to" in this content means "in the same directory or folder as" or "as a sibling to".

**Comment by frankfcool** [comment]
Hi @jenniferfell, I can take this task and fix it. Thanks

**Comment by brandonroberts** [comment]
@frankfcool Go for it. Just reference this issue in your PR.

**Comment by inidaname** [comment]
@brandonroberts if this is still in need I can rephrase it as stated by @jenniferfell
