### ISSUE TITLE
@angular-builders/custom-webpack npm source link 404

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [angular/angular#29341]
# 📚 Docs or angular.io bug report

### Description

 Angular owns this repo, correct? If not I'm sorry, that's confusing. If you go to this description and click on the "Repository" link, you get directed to a 404.

### What's the affected URL?**
 https://www.npmjs.com/package/@angular-builders/custom-webpack

### Reproduction Steps**

1) Click on the link provided
2) Click on the text titled "Github" on the side under the bold text "repository".
3) ????
4) Profit

### Expected vs Actual Behavior**

Expected: I can get the the repo.
Actual: I can't.

## 🔥 Exception or Error
<pre><code>

HTTP 404
</code></pre>

### Browser info

Google Chrome

**Comment by pkozlowski-opensource** [comment]
> Angular owns this repo, correct?

Nope, it does not. Here is:
*  a list of packages published by Angular organisation: https://www.npmjs.com/~angular
* a package that you are mentioning: https://www.npmjs.com/package/@angular-builders/custom-webpack

Going to close it here as the mentioned package is not owned / managed by the Angular organisation.
