### ISSUE TITLE
Angular Language Support and Django Conflict

### ISSUE THREAD

**Issue by jurrinus** [angular/angular#29357]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by jurrinus** [comment]
I am working with Python, Angular in vscode. I had django extensions installed. When I attempted to do some html work I expected some intellisense however, django dominated. Once I disabled django I got the angular intellisense I expected.

**Comment by pkozlowski-opensource** [comment]
Sounds like it should be opened in the VS code / VS extensions repository.
