### ISSUE TITLE
Injector#get is typed incorrectly

### ISSUE THREAD

**Issue by Airblader** [angular/angular#29351]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core or @angular/forms (see comments below).

### Is this a regression?
No.

### Description
`Injector#get` is currently typed to return `T` for `InjectionToken<T>`. This is, however, incorrect for `multi: true` injection tokens where calling this method (correctly) returns `T[]`.

*Update*: If the intention is that the InjectionToken is already typed as an array, then `NG_VALUE_ACCESSOR` is currently typed incorrectly.

## 🌍  Your Environment

**Angular Version:**
<pre><code>7.3.5</code></pre>

**Comment by JoostK** [comment]
I always use an array type in `InjectionToken`'s generic type parameter for multi providers. Then the types align and users of the token can derive it needs to be `multi: true`  

That is not entirely accurate, as a single array value would also be an option, however this is the general problem with providing a value for a token: there's no type safety enforced there.

**Comment by Airblader** [comment]
OK, so specifically I am talking about `NG_VALUE_ACCESSOR`. As someone on [StackOverflow](https://stackoverflow.com/questions/55195456/inject-all-dependencies-registered-under-a-token-through-injector-in-angular/55195518#55195518) pointed out, if the token is typed as `InjectionToken<Foo[]>`, the `get` method behaves correctly.

So the question here is how the Angular team intends the API to work. Depending on that decision the bug is either

1. `Injection#get` is not typed correctly
2. `NG_VALUE_ACCESSOR` isn't typed correctly

**Comment by mhevery** [comment]
`NG_VALUE_ACCESSOR` is not type correctly. Would you mind creating a PR to fix it?

**Comment by Airblader** [comment]
[Done](https://github.com/angular/angular/pull/29723)
