### ISSUE TITLE
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

### ISSUE THREAD

**Issue by amitcdubey** [angular/angular#29352]
when am updating the dependencies version in package.json then am getting below error 
node_modules/ng-pick-datetime-moment/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

and this error is coming just because there are two folder which have @angular-jira-bot 
1 .node_modules/@angular/core/src/render3/ng_dev_mode.d.ts
2. node_modules/ng-pick-datetime-moment/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts

can you let me know what should i need to do for solve this issue

**Comment by wizzywilson** [comment]
Try removing the current node modules and installing them again,
Use "rm -rf node_modules" and then "npm i"
Also, make sure u have the right version of node modules if u have multiple versions nvm use <version> to solve it.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
