### ISSUE TITLE
Service worker - What about clients object?

### ISSUE THREAD

**Issue by dmitriytretyakov** [angular/angular#29359]
Hello, i want to open URL when user click on web push notification, my code
`this.swPush.notificationClicks.subscribe((data: {action: string, notification: Object}) => {
        window.open(data.action, "_blank");
      });
`
data.action is my url.

This method blocked by browser, i google it and found solution for pure service worker without angular:

`this.scope.addEventListener('notificationclick', (event) => {
    event.notification.close();
    if (clients.openWindow && event.notification.data.url) {
      event.waitUntil(clients.openWindow(event.notification.data.url));
    }
  });`

Question: how can i get clients object? In ngsw-worker.js only two arguments for this handler:

`
yield this.broadcast({
                    type: 'NOTIFICATION_CLICK',
                    data: { action, notification: options },
                });
` 
Sorry for my bad english :)

**Comment by gkalpak** [comment]
`clients` is globally available in ServiceWorkers, but not on the page (nor is it possible to pass it from the SW to the page).
If you want to open a new window as a result of a notification, then the code needs to be in the SW itself. This is currently not supported by `@angular/service-worker`, but there is a feature request for adding more options for handling notification clicks: #26907.
