### ISSUE TITLE
Disable Html5 Attributes Validation

### ISSUE THREAD

**Issue by tanjuyayak** [angular/angular#29369]
Hi, I am trying to disable angular's html5 attribute validation but may be I'm missing something.  For ex: I have my own textbox component (my-custom-textbox) and it has "my-max-length" input. When I use this component without a form (<form>), angular automatically runs its own maxlength validation for my reactive form control. I need to disable this situation bec. I use my own custom validation logic. I tried to use "novalidate" but it did not work.

<my-custom-textbox my-max-length="5" formControlName="testInput"></my-custom-textbox>

**Comment by dawidgarus** [comment]
Try binding to directly to attribute: `<input [attr.maxlength]="'10'">`

**Comment by tanjuyayak** [comment]
> Try binding to directly to attribute: `<input [attr.maxlength]="'10'">`

that works :) I was using [maxlength]="'10'" and agular built-in maxlength validator runs automatically. Now thanks to [attr.maxlength] it is not running automatically.

**Comment by ericmartinezr** [comment]
Try this https://github.com/angular/angular/blob/master/packages/forms/src/directives/ng_no_validate_directive.ts#L18

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Looks like your question was answered in any case.
