### ISSUE TITLE
Why service worker show notification if only user on website

### ISSUE THREAD

**Issue by dmitriytretyakov** [angular/angular#29368]
And doesn't show when user close my website.  It's because notification show method calls in application service?
`
this.swPush.messages.subscribe(payload => {
        this.registration.showNotification(payload['title'], payload);
        this.api.sendPushEvent('receipt', payload['data'].message_id).subscribe();
      });
`

I try to subscribe another websites with web push technology and i received messages when website not opened in browser.

How to fix it? Create handlers in ngsw-worker.js ?

**Comment by gkalpak** [comment]
Currently, the support for notification clicks in `@angular/service-worker` is minimal (and for example only works if the app is already open).
As mentioned in https://github.com/angular/angular/issues/29359#issuecomment-473862158, there is a feature request for adding more options for handling notification clicks. See #26907 for more info.

If you wanted to work around that, you would need to modify the `ngsw-worker.js` script directly (which is doable but not very straight forward).

**Comment by dmitriytretyakov** [comment]
Sorry, my mistake. I don't wrap my message with "notification" object and following code not runned:
`handlePush(data) {
            return __awaiter$5(this, void 0, void 0, function* () {
                yield this.broadcast({
                    type: 'PUSH',
                    data,
                });
                if (!data.notification || !data.notification.title) {
                    return;
                }
                const desc = data.notification;
                let options = {};
                NOTIFICATION_OPTION_NAMES.filter(name => desc.hasOwnProperty(name))
                    .forEach(name => options[name] = desc[name]);
                yield this.scope.registration.showNotification(desc['title'], options);
            });
        }`
