### ISSUE TITLE
error in production build when loading js file

### ISSUE THREAD

**Issue by jagdishjadeja** [angular/angular#29365]
# 🐞 bug report
When i do `ng build --prod` it builds production build successfully 
but when i run it browser throws error 
`TypeError: this.service.isLoggedIn is not a function`
it works and runs fine with `ng build`

i have used a theme login and which is used with js instead ts like this

./login
- login.component.d.ts
- login.component.html
- login.component.js
- login.component.metadata.json

and error is coming from this file.

i have used 

`this.service.isLoggedIn()` function in this file only.

i am using angular version 

`` 
     "@angular/animations": "^4.0.0",    

    "@angular/cli": "^1.5.0",    

    "@angular/common": "^4.0.0",    

    "@angular/compiler": "^4.0.0",    

    "@angular/compiler-cli": "^4.0.0",    

    "@angular/core": "^4.0.0",    

    "@angular/forms": "^4.0.0",    

    "@angular/http": "^4.0.0",

    "@angular/platform-browser": "^4.0.0",    

    "@angular/platform-browser-dynamic": "^4.0.0",  
  
    "@angular/router": "^4.0.0",` .

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Side note: Angular 4.x is _really_ old, you should _strongly_ consider bumping up dependency versions.
