### ISSUE TITLE
Partial view encapsulation

### ISSUE THREAD

**Issue by WhitWaldo** [angular/angular#29364]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/core

### Description
Today, we have four options with regards to view encapsulation in Angular: Emulated, Native, None and ShadowDom. There is usually only one reason I ever have to switch from Emulated to another option, typically None, and that's because there's styling in a third-party component that I need to override for some reason. 

However, it's annoying that I can only opt into view encapsulation as an all or nothing proposition, especially given its usefulness in simplifying my development by ensuring that I don't have colliding class names across my own various components.

### Describe the solution you'd like
It would be fantastic to have a fifth option,, one that would allow me to decorate the CSS selectors in such a way so as to indicate that I'm selectively opting out of the view-encapsulation, but only for those decorated selectors.

### Describe alternatives you've considered
I have two options I can currently take:
- Put the overriding CSS in a base file to compile into the rest of the solution
- Opt out of view encapsulation on a per-component basis

The downside to the former option is that my override file is no longer a 1:1 relationship to a given component, but now becomes a clutter of various overrides. The downside to the latter is that I usually have need for CSS customization in the component apart from the few changes I apply to the component I'm overriding, and now I have to ensure that I'm without collisions all over again. In other words, either of these alternatives are less than ideal and forgo the benefits of view encapsulation in the first place.

**Comment by Airblader** [comment]
`::ng-deep`

**Comment by moxival** [comment]
There is also [ViewEncapsulation](https://angular.io/api/core/ViewEncapsulation)

**Comment by Airblader** [comment]
@moxival Not sure what you're getting at, he clearly mentioned the available forms of encapsulation.

**Comment by moxival** [comment]
Sorry about that I misread the last part :) probably too early fo rme

**Comment by WhitWaldo** [comment]
@Airblader This definitely is in the realm of what I had in mind, but I'm showing from the commit for this that ::ng-deep is deprecated and will be removed in the future per changes to the CSS spec. To that end, I've just been looking through related issues to this and it doesn't seem like there's a straightforward replacement yet.

Per the note in #25160 the documentation behind ::ng-deep further confirms what I've found in that the use of that functionality is no longer recommended and is available only as a temporary fallback while Angular transitions to.. something else. The issues to watch here appear to be #23636 (except that it's closed) and #27614 (though not seeing any Angular team feedback there yet).

To that end, I'm going to close this request as this appears to be something that's already being addressed by others. Thanks for responding so quickly @Airblader and @moxival !

**Comment by Airblader** [comment]
It's deprecated, but currently the recommended solution. AFAIK it won't be removed until there's an alternative :-)
