### ISSUE TITLE
Ivy: Unable to write a reference

### ISSUE THREAD

**Issue by dirkluijk** [angular/angular#29361]
# 🐞 bug report

### Affected Package
`@angular/compiler-cli`

### Is this a regression?
No, does not seem so.

### Description

When building my Angular app with Ivy enabled, I get this error:
```
ERROR in Unable to write a reference to AccordionDirective in /Users/dirkluijk/path/to/project/libs/widgets/src/lib/accordion/accordion.directive.ts from /Users/dirkluijk/path/to/project/libs/widgets/src/lib/accordion/accordion.module.ts
```

## 🔬 Minimal Reproduction
I have a complex project setup, a monorepo with multiple Angular libs.

## 🔥 Exception or Error
With some debug statements in `node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js` my output looks like this:

```
$ ng serve p1
  0% compiling

EMITTED LocalIdentifierStrategy HttpClientModule /Users/dirkluijk/path/to/project/libs/api/src/lib/api.module.ts
EMITTED AbsoluteModuleStrategy HttpClientModule /Users/dirkluijk/path/to/project/libs/api/src/lib/api.module.ts
EMITTED AbsoluteModuleStrategy HttpClientXsrfModule /Users/dirkluijk/path/to/project/libs/api/src/lib/api.module.ts
EMITTED AbsoluteModuleStrategy HttpClientXsrfModule /Users/dirkluijk/path/to/project/libs/api/src/lib/api.module.ts
EMITTED LocalIdentifierStrategy AccordionDirective /Users/dirkluijk/path/to/project/libs/widgets/src/lib/accordion/accordion.module.ts                                                                               

Date: 2019-03-17T19:52:02.577Z                                                  
Hash: 655d0cccad5d9464bf74
Time: 7484ms
chunk {main} main.js, main.js.map (main) 1.89 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 704 bytes [initial] [rendered]
chunk {polyfills.es5} polyfills.es5.js, polyfills.es5.js.map (polyfills.es5) 322 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 643 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 330 kB [initial] [rendered]

ERROR in Unable to write a reference to AccordionDirective in /Users/dirkluijk/path/to/project/libs/widgets/src/lib/accordion/accordion.directive.ts from /Users/dirkluijk/path/to/project/libs/widgets/src/lib/accordion/accordion.module.ts
Failed to compile.
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0-beta.7
Node: 10.9.0
OS: darwin x64
Angular: 8.0.0-beta.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-beta.7
@angular-devkit/build-angular     0.800.0-beta.7
@angular-devkit/build-optimizer   0.800.0-beta.7
@angular-devkit/build-webpack     0.800.0-beta.7
@angular-devkit/core              8.0.0-beta.7
@angular-devkit/schematics        8.0.0-beta.7
@angular/cdk                      7.1.1
@angular/cli                      8.0.0-beta.7
@ngtools/webpack                  8.0.0-beta.7
@schematics/angular               8.0.0-beta.7
@schematics/update                0.800.0-beta.7
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.29.6
</code></pre>

**Anything else relevant?**
I make use of Typescript paths, combined with barrel files.

```json
{
  "compilerOptions": {
    "paths": {
      "@p1/api": [
        "libs/api/src"
      ],
      "@p1/common": [
        "libs/common/src"
      ],
      "@p1/testing": [
        "libs/testing/src"
      ],
      "@p1/interactions": [
        "libs/interactions/src"
      ],
      "@p1/widgets": [
        "libs/widgets/src"
      ],
      "@p1/features": [
        "libs/features/src"
      ]
    },
  }
}
```
When I remove the error throw in `node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js`, it seems that the files that fail are completely random:

![image](https://user-images.githubusercontent.com/2102973/54497197-01280500-48f8-11e9-982a-8b9aa454c2d9.png)

**Comment by dirkluijk** [comment]
The specific import that files, is just a relative import. I debugged `LogicalProjectStrategy`. It does however not emit, because the target file is not located in the `rootDirs`. The `rootDirs` only contains the directory of my app, not of the library where the import is located.

**Comment by alxhub** [comment]
I'm impressed by your debugging here! Out of curiosity, how hard was it to follow the logic?

You're correct that the library not being in `rootDirs` is the cause of your error. This is not a supported configuration at the moment.

Currently, we support generating imports to files in two places:
* Within the current project (relative imports used)
* Within an Angular Package Format (APF) entry-point (absolute imports used)

APF guarantees that if FooModule is imported from 'package/foo', then the components it declares (e.g. FooComponent) are also available by importing 'package/foo'.

Your path-mapped packages are of a third kind - outside the project, but also not in the APF. So assuming this layout:

```
libs/widgets/src:
  component.ts // declares WidgetComponent
  module.ts // declares WidgetModule with declarations [WidgetCmp]
```

your app might write

```
import {WidgetModule} from '@p1/widgets/module';
```

which is perfectly valid to do. However, It's not valid to assume that `WidgetComponent` is also importable via the same path `@p1/widgets/module`, as it would be in an APF package. So what import should the Ivy compiler generate?

The obvious answer is `@p1/widgets/component`, but how does the compiler arrive at this? It would have to reverse engineer the path mapping and figure out that a file `libs/widgets/src/X` should be referred to as `@p1/widgets/X`. And the same directory can have multiple paths mapped to it. Path mappings were never intended to work this way.

So today, we don't support this kind of layout. As we start looking more at this kind of multi-project use case, maybe we'll introduce some mechanisms to support this.

**Comment by SebastianPodgajny** [comment]
I have exactly same problem, IMO `freq` will not be low

**Comment by dirkluijk** [comment]
@alxhub  Wow, thank you for your detailed explanation! Yes, it was hard to debug, even more because I didn't even know what it is used for exactly.

So you say that a barrel file from an Angular Package Format module (e.g. built with ngPackagr) is not the same as a regular barrel file from a path-mapped directory? I didn't know that before.

The reason I use this project layout, is that it should not matter if the package was actually pre-built or just a "local library" (monorepo approach). As a matter of fact, I just use the Nx Workspace project layout which is basically a Angular App + Angular Libs monorepo structure.

I will create a tracking issue at the Nrwl repo as well. In the mean time, what is your suggestion for monorepos?

**Comment by alxhub** [comment]
> The reason I use this project layout, is that it should not matter if the package was actually pre-built or just a "local library" (monorepo approach). 

It does matter to Ivy, unfortunately :( The difference is that we don't know how your library will be linked to the application at runtime, and therefore how it should be imported.

If your library will be shipped on NPM (and thus packaged via ng-packagr) and linked in the bundler from there, then its components/directives should be imported from the library root (think how `@angular/common` works - everything is imported from the index barrel file). In fact, you _cannot_ deep import into an APF package, because there are multiple formats (flattened bundles, umd, etc) and deep imports implicitly point to a specific format. We'd also want to generate an error here if the user declares a directive which might need to be imported, but doesn't export that directive from the barrel file.

If, on the other hand, you're building a library that is directly consumed in a subsequent build (e.g. an application build that will be bundled and distributed as one) then deep imports are the norm, as the bundler will be able to deal with them.

The challenge here is that this is purely conventional - our compiler doesn't know how your path-mapped library will eventually be distributed, and therefore which strategy to choose for generating imports to it. The user or some part of the tooling would have to tell us.

This challenge didn't affect the View Engine compiler as ngfactories (and therefore imports) were only generated during the final application compile, at which point deep imports are completely fine.

**Comment by dirkluijk** [comment]
@alxhub Thank you. Yes, we have libs that are only consumed by the apps in the same repo.

I will remove our barrel files and go for the deep imports. Thank you for your suggestion in this matter!

**Comment by elepner** [comment]
Hello! Wanted to try out Ivy on our quite big monolith with angular 8.0.0-rc2 front-end app and came across the same issue. So, basically we large Angular app which we're running since the Angular 2 which is in state of transitioning to micro-frontends. Therefore we have a library project under ``/projects/powel/pf-ui/lib/.`` where we pull shared UI  components occasionally and the app itself under ``ClientApp/app`` and it serves both as our main app and large e2e test/development environment for the lib project. I didn't want to use ``--watch`` flag for library reloading because it works way slower than ordinary HMR. Therefore the main project imports the library via relative path: ``../../projects/powel/pf-ui/src/lib``. After enabling Ivy I got the error explained in that thread. I do reexport via ``index.ts`` file only for defining public_api for the library. But all imports are happening explicitly within the lib. Is there any workaround if I have a module outside the main project folder?

**Comment by julianobrasil** [comment]
Until beta.12 I couldn't even compile one @nrwl-style-based project. Now, in rc.3, I'm able to compile,, but I haven't tried Ivy yet because it still has issues related to a dependency (angular-text-mask). The barrel files don't seem to be the problem anymore.

**Comment by dirkluijk** [comment]
Thanks for investigating. Will give it a new try!

**Comment by SebastianPodgajny** [comment]
Problem still exist in rc.4

**Comment by james-criscuolo** [comment]
I did some digging into the angular source and discovered my `rootDir` was "wrong" so the build process wasn't finding anything. I happen to have a repo where the `build` directory and the `src` directory are in the same directory, and have set it up so that i can run my npm scripts from that parent and everything works. To get past this problem, I needed to add a `rootDir` argument to my `tsconfig.json` in my `build` directory pointing to my `src` directory. I had not set the `rootDir` in `tsconfig.json` previously, but now I can get past this error and complete a build (now on to runtime errors 😄 )

I realize this was mentioned earlier, but given I had no `rootDir` or `rootDirs` at all, I ignored it. If you also did that, it now appears one of the two must be set.

**Comment by JonWallsten** [comment]
I get this issue when using imports from another package in our monorepo via symlinks.

``` 
ERROR in Unable to write a reference to MaxCharactersPipe in 
    C:/Users/user/repo/mono/packages/some-package/node_modules/@mono/another-package/src/pipes/max-characters.pipe.ts 
from 
    C:/Users/user/repo/mono/packages/some-package/node_modules/@mono/another-package/src/pipes/pipes.module.ts
```

```
#pipes.module.ts
import { NgModule } from '@angular/core';
import { MaxCharactersPipe } from './max-characters.pipe';

@NgModule({
    declarations: [
        MaxCharactersPipe
    ],
    exports: [
        MaxCharactersPipe
    ]
})
export class PipesModule { }
```
```
#app.module.ts
import  { PipesModule } from '@mono/another-package'

@NgModule({
    imports: [
        ...
        PipesModule
    ]
})
```
```
#package.json
{
  "dependencies": {
    "@mono/another-package": "file:../another-package"
  }
}
```

**Comment by FDIM** [comment]
Seems like the main issue is that people want to avoid building library separately when it is consumed by the application and of course others also want a way to build the library separately and publish it. 

Here are my thoughts, lets consider such mapping of paths in tsconfig:
```
"paths": {
      "xyz-core": [
        "projects/xyz/src/public-api.ts"
      ],
      "xyz-core/*": [
        "projects/xyz/src/lib/*"
      ]
}
```
Desired behavior from my side:
* Inside application (or other libraries) only direct import from `xyz-core` should be allowed (just like any external lib)
* Inside `xyz-core` lib imports with relative paths (scoped to the library) and imports via `xyz-core/*` path should be allowed. The latter is a bit more explicit and lets you avoid imports starting with '../../../` (we also have tslint rule for this). 
* Bonus points if build would fail when importing from `xyz-core/*` in application / other library. Currently build still works.

At least this seem to work in non-ivy build, 

Now the problem as I see is that when you build application, and import `some.service.ts` from `xyz-core`, it will most likely import other files which some of them may not even be part of barrel file (private) or use import from `xyz-core/utils/index`.

Maybe tsconfig.lib.ts could be used when path mapping points to a library barrel file to enrich typescript configuration (and ivy) with extra mappings during build? This way mapping of `xyz-core/*` could be left inside tsconfig.lib.json

**Comment by jbjhjm** [comment]
> Seems like the main issue is that people want to avoid building library separately when it is consumed by the application and of course others also want a way to build the library separately and publish it.
> ...
> * Inside application (or other libraries) only direct import from `xyz-core` should be allowed (just like any external lib)
> * Inside `xyz-core` lib imports with relative paths (scoped to the library) and imports via `xyz-core/*` path should be allowed. The latter is a bit more explicit and lets you avoid imports starting with '../../../` (we also have tslint rule for this).
> * Bonus points if build would fail when importing from `xyz-core/*` in application / other library. Currently build still works.

In general I like your idea, but I got one issue with that concept.
I'm using a similar tsconfig path setup, let's say it's 
> ```
> "paths": {
>       "x-core": [
>         "projects/x/src/public-api.ts"
>       ],
>       "x-core/*": [
>         "projects/x/src/lib/*"
>       ],
>       "y-core": [
>         "projects/y/src/public-api.ts"
>       ]
> }
> ```

Let's say y-core uses some stuff located in x-core.
Normally something like `import {my,needed,stuff} from 'x-core' would be sufficient.
But there are cases where importing the whole barrel may lead to dependency problems or unnecessarily loaded code. For these situations I'm using the wildcard path and do specific imports like e.g. `import { SomeInterface } from 'x-core/interfaces/some.interface'.
Having only a single barrel import for all library contents doesn't look like a well working solution to me.

**Comment by FDIM** [comment]
@jbjhjm I get what you are saying, but such explicit imports only work when you are in control of entire lib and know what is public and what is private. It also kind of goes against usage of barrel files which basically enforces only public API usage. 

As for unneeded code that gets loaded, it should be tree-shaken at build time and should not be an issue in my mind.

> Having only a single barrel import for all library contents doesn't look like a well working solution to me.
I agree that this could get out of hand, but it also could be a sign that library is too broad and should be split into multiple ones. Its quite straightforward to create new libraries now (Except for path mapping)

**Comment by dirkluijk** [comment]
I checked on `8.1.0-next.1`, and the error seems to be gone. Can someone verify that?

**Comment by Hotalenw** [comment]
We are having this issue in our applications when setting 
"angularCompilerOptions": {
    "enableIvy": true
  },

in tsconfig. 

![Screen Shot 2019-06-12 at 8 22 02 AM](https://user-images.githubusercontent.com/21366648/59350957-4be4cd80-8ceb-11e9-9b13-4b829f493040.png)

**Comment by Hotalenw** [comment]
@dirkluijk I tried `"@angular/compiler-cli": "^8.1.0-next.1"` in package.json and still get the same error from your original post.

**Comment by samherrmann** [comment]
@dirkluijk I am still experiencing this error as well. I ran `ng update @angular/core --next`, which gave me the following stack:

```
Angular CLI: 8.0.1
Node: 10.16.0
OS: linux x64
Angular: 8.1.0-next.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.1
@angular-devkit/build-angular      0.800.1
@angular-devkit/build-ng-packagr   0.800.1
@angular-devkit/build-optimizer    0.800.1
@angular-devkit/build-webpack      0.800.1
@angular-devkit/core               8.0.1
@angular-devkit/schematics         8.0.1
@angular/cli                       8.0.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.1
@schematics/angular                8.0.1
@schematics/update                 0.800.1
ng-packagr                         5.2.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0
```

**Comment by ManishJainGitHubUser** [comment]
I haven't seen any workaround in this thread. So, assuming Ivy is not available until we have a fix.

**Comment by JonWallsten** [comment]
@p3x-robot They do that for all issues that doesn't affect the majority of users based on my experience. Also it's not OP adding the labels, it's the Angular-team. @dirkluijk is innocent.

**Comment by pburkindine** [comment]
For me at least the solution with a regular @nrwl/nx setup was just to add `"rootDir": "."` to the `compilerOptions` in `tsconfig.json`; thanks @james-criscuolo 	

On to the next error...

**Comment by rt-gavrilov** [comment]
@p3x-robot 
this works in my case:
1. angular 8.2.0-next.1
2. appending `"rootDir": "."` to the `compilerOptions` in the root `tsconfig.json`
3. using index.ts like this:
```
"paths": {
    "@libs/api": ["libs/api/src/index.ts"],
```
BTW, thank you guys @pburkindine @james-criscuolo, you're my favorite

**Comment by alxhub** [comment]
Hello all! For people monitoring this issue, I just wanted to give a quick update. I've put together a [design doc](https://hackmd.io/@alx/SycgothIV) describing the problem and my proposed solution. The basic idea is that in `tsconfig.json` you'll tell the Angular compiler which of your path-mapped libraries are "private". That will give the compiler enough information to correctly generate imports for the directives/components within those libraries.

**Comment by vthinkxie** [comment]
Hi we met the same problem, I think the freq is not `low`, and it block angular lib to migrate to ivy.
https://github.com/NG-ZORRO/ng-zorro-antd/pull/3740/files#diff-5

**Comment by vgb1993** [comment]
I managed to get it working folloing  @rt-gavrilov workaround and this article https://medium.com/@raviroshan.talk/fix-for-continuous-build-of-library-in-angular-workspace-c18422bab927

Steps to follow: 

1. Rename public-api.ts to index.ts in your libs. Update each ng-package.json of the libs to reference index.ts instead.

2.  Edit the root tsconfig.json. 
Append "rootDir": "." to the compilerOptions.  
Change the paths inside compilerOptions { 
"paths": {
      "appia-desktop": [
        "projects/appia-desktop"
      ],
      "appia-desktop/*": [
        "projects/appia-desktop/*"
      ]
}


My tsconfig.json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "appia-desktop": [
        "projects/appia-desktop"
      ],
      "appia-desktop/*": [
        "projects/appia-desktop/*"
      ],
    },
    "rootDir": "."
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
  }
}


AppModule
import { AppiaDesktopModule } from 'appia-desktop';
@NgModule({
  imports: [
    AppiaDesktopModule,


Library index.ts
export * from './src/features/maestros/conceptos/paginas/frm-e-conceptos/frm-e-conceptos.component';
export * from './src/features/maestros/conceptos/paginas/frm-e-conceptos/frm-e-conceptos.module';
export * from './src/appia-desktop.module';


Now  I can livereload angular libraries, wich is very convenient for development.  I'm currently using "@angular/core": "~9.0.0-next.3". Hope it helps someone.

**Comment by Svetomechc** [comment]
@vthinkxie are you planning to incorporate @vgb1993 workaround into ng-zorro-antd? Just asking.

**Comment by kukjevov** [comment]
@alxhub Hmmm, why it does not work with symlinks ? When i copy my directory it compiles without any problem. If i create symlink to same place it will not work. I hope i would go around by using symlink, becase it is outside of app directory.

**Comment by JonWallsten** [comment]
@alxhub: Thank you for you hard work on this. Really appreciated!

**Comment by JonWallsten** [comment]
@matsko: Will this be shipped in Angular@8.x.x?

**Comment by samherrmann** [comment]
I just upgraded a project from `8.2.8` to `9.0.0-next.13` with `ng update --next --force @angular/cli @angular/core` and I am still receiving the `Unable to write a reference error`. Unfortunately I am not able to share much about the project so my comment may not be of much help, but I just wanted to voice my outcome in case someone else experiences the same.

**Comment by JoostK** [comment]
> Will this be shipped in [Angular@8.x.x](mailto:Angular@8.x.x)?

@JonWallsten Nope, sorry. Please use the latest 9.0.next (tagged `next`) for using Ivy.

> I just upgraded a project from `8.2.8` to `9.0.0-next.13` with `ng update --next --force @angular/cli @angular/core` and I am still receiving the `Unable to write a reference error`. Unfortunately I am not able to share much about the project so my comment may not be of much help, but I just wanted to voice my outcome in case someone else experiences the same.

@samherrmann Could you set `"generateDeepReexports": true` under `"angularCompilerOptions"` in `tsconfig.json`:

```json
{
  ...
  "angularCompilerOptions": {
    "generateDeepReexports": true
  }
  ...
}
```

**Comment by samherrmann** [comment]
@JoostK thanks for responding. I added your suggested configuration but same result. I will try to create a reproducible repo that I can share.

**Comment by gnomeontherun** [comment]
@JoostK I can provide a repo here https://github.com/gnomeontherun/clarity/tree/angular9.

Run `ng build --prod` to see the following write reference error:

```
ERROR in Unable to write a reference to ClrIconCustomTag in src/clr-angular/icon/icon.ts from src/clr-angular/icon/icon.module.ts
```

**Comment by JonWallsten** [comment]
@JoostK: Unfortunately I get the same error using AngularCompilerPlugin for Webpack.
```
ERROR in Unable to write a reference to MaxCharactersPipe 
in C:/Users/<me>/monorepo/packages/web-app-edit/node_modules/@oas/web-lib-angular/src/pipes/max-characters.pipe.ts 
from C:/Users/<me>/monorepo/packages/web-app-edit/node_modules/@oas/web-lib-angular/src/pipes/pipes.module.ts
```

Added these to tsconfig.json:
```
"angularCompilerOptions": {
    "enableIvy": true,
    "generateDeepReexports": true
}
```

In addition I get a whole bunch of these:
```
ERROR in node_modules/@oas/web-lib-angular/src/components/dialog/dialog.component.ts(2,58): error TS2306: 
    File 'C:/Users/<me>/monorepo/packages/web-app-edit/node_modules/@angular/material/index.d.ts' is not a module.
node_modules/@oas/web-lib-angular/src/components/settings-dialog/settings-dialog.component.ts(2,64): error TS2306: 
    File 'C:/Users/<me>/monorepo/packages/web-app-edit/node_modules/@angular/material/index.d.ts' is not a module.
node_modules/@oas/web-lib-angular/src/material-design/material-design.module.ts(34,8): error TS2306: 
    File 'C:/Users/<me>/monorepo/packages/web-app-edit/node_modules/@angular/material/index.d.ts' is not a module.
```

**Comment by samherrmann** [comment]
I am no longer receiving the `Unable to write a reference` error. The problem was that my `paths` mapping in `tsconfig.json` was configured such that the libraries were referenced in the `projects` directory instead of the `dist` directory (for live library reload capability [as commented above by @vgb1993](https://github.com/angular/angular/issues/29361#issuecomment-524503373)). I understand however that this is [not a supported configuration](https://github.com/angular/angular/issues/29361#issuecomment-474616177).

**Comment by kuncevic** [comment]
got same error here with the latest 9 https://github.com/kuncevic/angular9-multi-app
Any ideas?

**Comment by samherrmann** [comment]
As of 9.0.0-rc.3, I can confirm that this issue is now also fixed when using path mappings that point to library source under `projects/` instead of built libraries under `dist/`.  The fix was delivered in PR https://github.com/angular/angular/pull/33828.
