### ISSUE TITLE
Ivy, ngcc: InlineSVGModule.forRoot() yields "is not a reference"

### ISSUE THREAD

**Issue by rcketscientist** [angular/angular#29362]
# 🐞 bug report

### Description

 A clear and concise description of the problem...
During `ivy-ngcc` I crash on a module with this error:
`Value at position 2 in the NgModule.importss of AlloyIconModule is not a reference: [object Ob`

the culprit has these imports:
```
  imports: [
      CommonModule,
      HttpClientModule,
      InlineSVGModule.forRoot()
  ]
```

It appears that `InlineSVGModule.forRoot()` cannot be processed.
Please let me know any further steps I can take to debug.

Possibly related:
https://github.com/angular/angular/pull/27326
https://github.com/angular/angular/issues/27582

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

8b8
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
Failed to process:
https://unpkg.com/ng-inline-svg@8.3.0/lib/inline-svg.module.js

The syntax of `ngModule: namespace.Identifier` is not currently supported, so that explains why this fails.

Moreover, looks like that package does not follow APF, which could be problematic for proper processing.

**Comment by rcketscientist** [comment]
Thanks for the fast reply. I'll look into the supplied details.

**Comment by rcketscientist** [comment]
I migrated `ng-inline-svg` to ng6, then converted it for Ivy and the demo ran fine.  I had some issues with the intermediary library, but I think the assessment of the package format being the issue is correct.

In case anyone else bumps into this specific library:
https://github.com/rcketscientist/ng-inline-svg/tree/ivyCompiler
