### ISSUE TITLE
can't able to clone a viewRef from one container to another container

### ISSUE THREAD

**Issue by sheikalthaf** [angular/angular#29366]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was present was

### Description

I want to clone a viewRef from one viewContainerRef to another viewContainerRef using the below commands but instead of cloning it is moving the viewRef. But there is already we have `move` option to move a viewRef.

```javascript
leftContainer.insert(mainContainer.get(i))
```

The viewRef moved from mainContainer to leftContainer. But i want to clone it. Any other thing I'm missing here?

I have added the stackblitz link below about my issue. please change `createViewInsteadOfClone = false` 
to check my issue

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-createview?file=src%2Fapp%2Flister%2Flister.component.ts

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.4
Node: 10.15.0
OS: win32 x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.8.1
@angular-devkit/build-angular      0.8.1
@angular-devkit/build-ng-packagr   0.8.1
@angular-devkit/build-optimizer    0.8.1
@angular-devkit/build-webpack      0.8.1
@angular-devkit/core               0.8.1
@angular-devkit/schematics         7.3.4
@angular/cli                       7.3.4
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.2.1
@schematics/angular                7.3.4
@schematics/update                 0.13.4
ng-packagr                         3.0.6
rxjs                               6.3.2
typescript                         2.9.2
webpack                            4.17.2
</code></pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment]
I think that there is some misunderstanding in how view management in `ViewContainerRef` was designed to work. I think that those two points might clarify things:
* the  `ViewContainerRef.move(viewRef: ViewRef, currentIndex: number)` method will _move_ a view within the same container (although, in practice it will insert a view if it is not part of the target `ViewContainerRef`)
* there is no concept (nor corresponding API) to "clone" a view (this would be prohibitively complex operation).

All in all you can _create_ a view instance and once it is created you can add / remove it to a  `ViewContainerRef` (or remove from one  `ViewContainerRef` and insert into another  `ViewContainerRef`). But you can't "clone" an instance of a view (as if "make a copy of it") once it is created.

I'm going to close this issue as there is no concept of view cloning in Angular and we don't intend supporting it.

**Comment by sheikalthaf** [comment]
@pkozlowski-opensource Thanks for your clarification.

But i have a requirement for cloning viewRef in one of my library [@ngu/carousel](https://www.npmjs.com/package/@ngu/carousel).

I'm following the owl carousel2 for my next update where i have to clone some of my viewRef item.

![image](https://user-images.githubusercontent.com/22526247/54531936-8e2c9600-49ac-11e9-93d7-8bcbc29df265.png)

Please check the above image how owlCarousel making cloning of some of its items.

any help from your side will be helpful
