### ISSUE TITLE
it seems that the alias "as" no longer works in the build

### ISSUE THREAD

**Issue by luisestebanvera** [angular/angular#29379]
> 

> 

> hi,

update my angular application 7.0.0 to 7.2.9. but when making the production build it says "ERROR ReferenceError: _environment_1 is not defined"

I'm using the environment as well:

`import { environment as ENV } from 'environments/environment.ts';`

the alias(as ENV) is no longer working.

in version 7.0.0 this did not happen

my package.json
{
  "name": "example",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build:prod": "ng build --configuration=prod",
    "build:dev": "ng build --configuration=dev",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.2.9",
    "@angular/common": "~7.2.9",
    "@angular/compiler": "~7.2.9",
    "@angular/core": "~7.2.9",
    "@angular/forms": "~7.2.9",
    "@angular/http": "~7.2.9",
    "@angular/platform-browser": "~7.2.9",
    "@angular/platform-browser-dynamic": "~7.2.9",
    "@angular/router": "~7.2.9",
    "@ngrx/effects": "^7.3.0",
    "@ngrx/store": "^7.3.0",
    "@ngrx/store-devtools": "^7.3.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "core-js": "^2.5.4",
    "js-sha512": "^0.8.0",
    "rxjs": "~6.4.0",
    "tiny-slider": "2.9.1",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular/cli": "~7.3.6",
    "@angular/compiler-cli": "~7.2.9",
    "@angular/language-service": "~7.2.9",
    "@types/faker": "^4.1.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "faker": "^4.1.0",
    "http-server": "^0.11.1",
    "husky": "^1.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "json-server": "0.14.0",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.4",
    "webpack-bundle-analyzer": "^3.0.3"
  }
}

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
