### ISSUE TITLE
Routing: canActivate is not created in --prod when using concat

### ISSUE THREAD

**Issue by mlechnioppg** [angular/angular#29374]
# 🐞 bug report

### Description

When using array_of_guards.concat(guard) as canActivate parameter in a route and building app   with --prod the resulting script doesn't have canActivate variable defined. 
When using [...array_of_guards, guard] it works fine.
The issue doesn't show when not in --prod meaning that a dev environment works fine.

## 🔬 Minimal Reproduction

https://github.com/mlechnioppg/guards-bug

Clone repo then run: ng build --prod
Use http-server to run, eg: http-server dist/guards
Click links while watching console and see that guards don't fire when clicking one link.
When testing using ng serve all logs show properly when clicked.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.3.6
Node: 8.12.0
OS: win32 x64
Angular: 7.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.3.6
@angular/cli                      7.3.6
@ngtools/webpack                  7.2.4
@schematics/angular               7.3.6
@schematics/update                0.13.6
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4

</code></pre>

**Anything else relevant?**

**Comment by csi-stasik** [comment]
I have the same issue when I want to attach the guard for all routes

```
const routes: Routes = [{
    path: "",
    loadChildren: "./home/home.module#HomeModule",
    data: { }
  },  {
    path: "test",
    loadChildren: "./test/test.module#TestModule",
    data: { }
  }]

 routes.forEach((route: Route) => {
   route.canActivate = [GuardService];
 });

```

**Comment by MattJeanes** [comment]
Seeing same problem with this code:

```
routes.forEach(x => {
    if (!x.canDeactivate) {
        x.canDeactivate = [];
    }
    x.canDeactivate.push(CanDeactivateGuard);

    if (x.path === "login" || x.path === "init") { return; }
    if (!x.canActivate) {
        x.canActivate = [];
    }
    x.canActivate.push(AuthGuard);
});
```

**Comment by gotwig** [comment]
This is maybe a solution, or relevant: https://stackoverflow.com/questions/43487827/how-to-apply-canactivate-guard-on-all-the-routes

I am still not a fan of this because it restricts your code.

Maybe someone of the devs can explain to us why the forEach works in dev but not in production?...
Are the routes in production generated and in dev not? that may be an explaination

**Comment by atscott** [comment]
Thanks for reporting this issue. I updated the example app to v10 and I can see that the console logs both `FirstGuard` and `SecondGuard` so this appears to be fixed, likely by Ivy (release as the default in v9).

If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
