### ISSUE TITLE
[Router] Allow scrollOffset of ExtraOptions to be an injectable token and allow the return value to be an Observable

### ISSUE THREAD

**Issue by jermowery** [angular/angular#29397]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/Router

### Description
The ExtraOptions for the RouterModule allows you to specify an scroll offset for scrolling to elements with "anchorScrolling" is enabled and when scroll restoration is enabled. This may be a static value or a function that returns a value.This must be specified in the options and cannot be injected. Also the value cannot be determined asynchronously via a Promise or Observable 

### Describe the solution you'd like
1. Provide a way of injecting the scrollOffset function instead or (or as well as) providing it inline. This would allow us to derive the offset from other Injectable services.
2. Allow the scrollOffset to be determined asynchronously. In our apps we depend on a nav bar that has a dynamic size, this size needs to be accounted for in the scrollOffset, unfortunately the API for this navbar uses promises so we can't easily return a value for the scrollOffset function.

**Comment by atscott** [comment]
Closing as unnecessary. This can be done by calling `setOffset` on the viewport scroller at any time:
https://github.com/angular/angular/blob/cc0f38130b48d66971cf518a611595f8069a0110/packages/common/src/viewport_scroller.ts#L36
This is exactly what the router module does with the config option:
https://github.com/angular/angular/blob/cc0f38130b48d66971cf518a611595f8069a0110/packages/router/src/router_module.ts#L179-L181

Arguably, this should be removed from the `ExtraOptions`. We shouldn't have two ways of controlling this and having it in the `ExtraOptions` as simply an alias to `viewportScroller.setOffset(...);` seems like an unnecessary expansion of the public API.
