### ISSUE TITLE
Route Snapshot fragment is sometimes null and sometimes undefined

### ISSUE THREAD

**Issue by gak10100** [angular/angular#29391]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 No

### Description

 Sometimes the route snapshot fragment is null and sometimes its undefined for the exact same route. This can cause issues down the line when the when the routing code is doing comparisons on the snapshot fragment.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-8vqamz
1) Click A  - You will see an output of "A - undefined" 
2) Click Reload - You will see an output of "A - null"

## 🌍  Your Environment

7.2.5

**Anything else relevant?**

**Comment by atscott** [comment]
Fixed by https://github.com/angular/angular/commit/b5551609fe02787641bdfdb0a6edfded413a3b52
