### ISSUE TITLE
Tutorial "Tour of Heros" css styles ".heroes .text" not used

### ISSUE THREAD

**Issue by neshanjo** [angular/angular#29393]
# 📚 Docs or angular.io bug report

### Description
Affects https://angular.io/tutorial/toh-pt2 (stable v7.2.9): In src/app/heroes/heroes.component.css, styles for `.heroes .text` are defined, but not used. The code in src/app/heroes/heroes.component.html should read
```
:
  <li *ngFor="let hero of heroes"
    [class.selected]="hero === selectedHero"
    (click)="onSelect(hero)">
    <span class="badge">{{hero.id}}</span><span class="text">{{hero.name}}</span>
  </li>
:
```
(extra span.text added), which then leads to correct vertical alignment of badge and text.

In later parts of the tutorial (e.g. https://angular.io/tutorial/toh-pt5), the `.heroes .text` styles are removed completely, which is consistent with the html, but leads to misalignment.

Here an image which shows the difference:
![image](https://user-images.githubusercontent.com/22233722/54598065-09875980-4a38-11e9-8fc1-ddd86308e015.png)
Rendered on Firefox 65.0.2 (64-bit), Windows 10

**Comment by brandonroberts** [comment]
Going to leave this as-is for now.
