### ISSUE TITLE
ngcc: produces wrong d.ts files for generic types (pipes)

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#29400]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/compiler-cli

### Is this a regression?

Dont know if this worked before.

### Description

When running `ngcc` for my own library ngcc runs without problem, but it does not produces correct d.ts files for generic types, respectively tested for pipes.

## 🔬 Minimal Reproduction

Here is repository with my sample package https://github.com/kukjevov/sample, there is compiled result that is used in sample https://github.com/kukjevov/ivy-code-size/tree/sample
Problem is on line https://github.com/kukjevov/ivy-code-size/blob/ee0b7436a18770991c03065204b3038ced24ef99/node_modules/%40ng/sample/src/pipes/ngSelectValue.pipe.d.ts#L11 

```typescript
static ngPipeDef: ɵngcc0.ɵPipeDefWithMeta<NgSelectValuePipe, "ngSelectValue">;
```

there should be 
```typescript
static ngPipeDef: ɵngcc0.ɵPipeDefWithMeta<NgSelectValuePipe<any>, "ngSelectValue">;
```

To reproduce problem:
`git clone https://github.com/kukjevov/ivy-code-size sample-ivy`
`cd .\sample-ivy\`
`git checkout sample`
`npm install`
`git reset --hard`
`npm run ngcc`
`npm run build`

## 🔥 Exception or Error
<pre><code>
node_modules/@ng/sample/src/pipes/ngSelectValue.pipe.d.ts:11:47 - error TS2314: Generic type 'NgSelectValuePipe<TValue>' requires 1 type argument(s).

11     static ngPipeDef: ɵngcc0.ɵPipeDefWithMeta<NgSelectValuePipe, "ngSelectValue">;

</code></pre>

## 🌍  Your Environment

**Angular Version:**
*8.0.0-beta.8*

**Anything else relevant?**
Windows 10
Version	10.0.17134 Build 17134
**node** v10.13.0
**npm** 5.3.0

**Comment by JoostK** [comment]
I looked into this and this is not currently supported for pipes in ngtsc. Directives and services should be emitted correctly (even with ngcc) however pipes do not take into account generic type arguments at all.
