### ISSUE TITLE
Render/Core: Conditionally add event handlers to DOM elements

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2940]
Have Angular register a single event handler at the top of the document and then forward the request to the appropriate statement. This means that multiple `(click)` registration would result in a single `document.addEventListener(...)` call. 

NOTE: Care needs to be taken when crossing shadow root boundaries.

## ORIGINAL TEXT

Right now, you can add something like a mouseenter handler in the DOM:

```html
<div (mouseenter)="onMouseEnter"></div>
```

However, this coupled with an `ng-for` could become really expensive. A common practice is to conditionally add event handlers only when they are needed, and remove them after. For example, pressing something like "reorder" could add a mousedown/drag event to list items.

Is there any plans to be able to something like

```html
<div (mouseenter-if)="dragEnabled | onMouseEnter()"></div>
```

(Not sure how to categorize this)

**Comment by gdi2290** [comment]
I prefer it if the value is `null` then it shouldn't register a handler so you can do something like this
`<div (mouseenter)="if dragEnabled then onMouseEnter()"></div>`
`<div (mouseenter)="onMouseEnter() | async"></div>`

**Comment by mhevery** [comment]
My understanding is that this is an optimization request. If that is the case it is better solved by registering single event handler at the application root, which can then forward events to the appropriate target.

You would still write 

```
<ul>
  <li *ng-for=."..." (click)="...">   </li>
</ul>
```

but only one actual registration would happen per app.

**Comment by matanlurey** [comment]
For click events that makes sense, but what about for mousemove or mouseenter?

**Comment by naomiblack** [comment]
Obsolete. But Matan, please come discuss with us if this is still a concern. We will get you unstuck.
