### ISSUE TITLE
New feature to identify an element from X and Y coordinates

### ISSUE THREAD

**Issue by Abhilash-Ram** [angular/angular#29415]
Hi, I would like to have a method in ElementRef.nativeElement to capture the dom elements present in the particular X and Y coordinates.

In Javascript we have
<pre>
document.elementFromPoint(X, Y); // X and Y denotes the positions
</pre>

In my application I planned to find the overlapping draggable elements on user action on any movable dom elements. Based on that i need to pass the information to an algorithm to find the next possible positions for that overlapping element

**Comment by pkozlowski-opensource** [comment]
> Hi, I would like to have a method in ElementRef.nativeElement to capture the dom elements present in the particular X and Y coordinates.

What you are asking for is tightly coupled to the DOM positioning and as such shouldn't be part of rendering-target-independent `ElementRef`. Just use DOM APIs.

Closing as won't implement.
