### ISSUE TITLE
Get list of all injected or injectable services of a module or component

### ISSUE THREAD

**Issue by no-more** [angular/angular#29413]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core/Injector

### Description

Ability to **get a list of all injectable services**.
I need to create a component or a service that could have access to all injectable services of an application without knowing all of them.
Currently the Injector provides only a **get** method and requires to know all services of all included modules (recursively) to achieve this.
The aim is to create an highly reusable code that could browse all injectable services, and filter the services that match a rule (for example that extends a common class). Then, for all those services, trigger a specific method.

### Describe the solution you'd like
 
Add a **getInjectableServiceList** method to Injector which would return a list of all injectable services. From this list we should be able to inject the service only if required.

### Describe alternatives you've considered
 
Creating and maintaining manually a list of all the services used by an application.
But as this is intended to be used in over 20 apps whom all have different configuration, it would be very painful and error prone, so this is not a viable solution.
Using **multi** is also not possible as it would require that all services are injected into same "name" and it won't be anymore possible get one specific service by it's class name. It would be great if multi was able to return all injectable services that extends a particular class without changing injection everywhere.

**Comment by no-more** [comment]
I don't know if this could help but I've opened a stock overflow discussion prior to this https://stackoverflow.com/questions/55097553/retrieve-list-of-all-injected-services-on-a-component-app

**Comment by Airblader** [comment]
Just to point it out: you'd still only get services that are used somewhere, as otherwise tree shaking throws them out in the AoT build anyway.

**Comment by no-more** [comment]
Yes that would be fine as long as I could at least have access to services that might not have been used yet but are used somewhere in the application.

**Comment by alxhub** [comment]
This is something you can implement yourself, as you mentioned, with `multi`. E.g:

```
function wrapProvider(provider: Provider) {
  const token = (provider instanceof Function) ? provider : provider.provide;
  return [provider, {provide: ALL_SERVICES, useExisting: token, multi: true}];
}
```

**Comment by alxhub** [comment]
As others have mentioned, not all services/providers are in the injector, so such a method would have limited usefulness.

**Comment by no-more** [comment]
If I'm not wrong, if I'm using multi I will not be able to access each services directly by their name. Your wrapProvider function is interesting, but I don't see how to use it but I will give it a try. Thanks.

But I don't understand why the injector of the main application component wouldn't know all injected services? Of course I'm not talking about services that are injected at a component level which of course are only accessible in that component. But otherwise all providers should be accessible by the top level injector, am I wrong?

Thanks for your help

**Comment by Airblader** [comment]
> But I don't understand why the injector of the main application component wouldn't know all injected services?

Lazy loaded modules should definitely be one interesting case here.

**Comment by no-more** [comment]
You're right, as I'm not using them right now I've forgot them.
