### ISSUE TITLE
Multiple Independent Instance of Same Component

### ISSUE THREAD

**Issue by newETA** [angular/angular#29410]
Hi There,
I am new to Angular and trying to create a multi-window chat application and using the same component for all chat window and I am loading chat window using ComponentFactoryResolver I am able to load the window as expected and it's good for if I just open one window. When I tried to open another window the opened window user information is showing correctly as expected but somehow the message is replacing with the last chatBox to all opened window. 

Only the message section isn't showing correct information based on the selection that one is replacing by whichever open. 

dynamic content loading code:

```
`loadSingleWindow(user_info)

 {
  const chatBoxFactory = this.componentFactoryResolver.resolveComponentFactory(WindowComponent);
  const viewContainerRef  = this.container;
 // viewContainerRef.clear();

    this.componentRef = viewContainerRef.createComponent(chatBoxFactory);
   // this.chatService.joinChat(user_info);

  const windowInstance = <WindowComponent>(this.componentRef.instance);
  windowInstance.chatUser = user_info;
  this.chatService.loadExistingMessage('').subscribe(data => {
    windowInstance.messages = data;
  });

}
destroyComponent() {
  this.componentRef.destroy();
}
`
```
and the Window component:
```
`export class ChatWindowComponent implements AfterViewInit {

  public messages: Array<ChatMessage> = [];
  activeRoom: any;

  public chatUser;

  ngAfterViewInit() {
      console.log('hello world');
  }
}
`
```
![Chatbox](https://user-images.githubusercontent.com/42071761/54660064-2446e600-4aab-11e9-8691-a64cc8157600.PNG)

> In the view, I am just looping the messages object to show all messages.  

Thank you so much in advance.

**Comment by Airblader** [comment]
The issue tracker is for bug reports, feature requests and the like. Please use platforms like StackOverflow for support seeking questions.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
