### ISSUE TITLE
[Router]: Catch-All Wildcard Route Not Lazy Loaded

### ISSUE THREAD

**Issue by daniel-nagy** [angular/angular#29428]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 Don't know.

### Description

 Catch-all route module is always downloaded.

## 🔬 Minimal Reproduction

 I don't know if lazy loaded modules can be tested in stackblitz but it is really easy to test by generating a new Angular application and adding two lazy loaded routes.

```typescript
const routes: Routes = [
  {
    path: 'home',
    loadChildren: './pages/home-page.module#HomePageModule'
  },
  {
    path: '**',
    loadChildren: './pages/not-found-page.module#NotFoundPageModule'
  }
];
```

if you load **/home** in the browser the `NotFoundPageModule` will be downloaded as well.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 6.0.8
Node: 10.14.1
OS: darwin x64
Angular: 7.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.8.3
</code></pre>

**Comment by jasonaden** [comment]
Thanks. I have heard of issues similar to this in the past. Please create a Stackblitz (yes, lazy loading works there) to replicate so we can take a look.

**Comment by jasonaden** [comment]
Here's the duplicate issue #25494. Therefore I'll go ahead and close this one.

We should be looking at this issue in the relatively near future.
