### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError, ngForm inside ng-template or structural directives and bindings to this form outside of ngTemplate : change detection works incorrectly

### ISSUE THREAD

**Issue by sharikovvladislav** [angular/angular#29421]
# 🐞 bug report

### Affected Package

 The issue is caused by package (probably) `@angular/compiler`/`@angular/forms`/`@angular/common`

### Is this a regression?

I am not sure. I have 7.2.7+ (also represented in 7.2.10).

### Description

 A clear and concise description of the problem...

What I have: 
I have some wrapper with ngForm directive on it. Inside of this block with ngForm I have another wrapper with *ngIf directive. I have 2 inputs: type text and type checkbox in some container with *ngIf. Input type=text is dynamically required. It is required when checkbox is checked and otherwise. Inside ngForm wrapper, but outside of *ngIf wrapper I have 2 buttons: one button is native HTML button and another button is native button wrapped into my custom component. This component contains only native HTML button and it has disabled binding on it. Disabled binding applies as disabled attribute binding to native HTML button in it. Both native button and custom component button have absolutely same `disabled` binding.

Common logic: buttons must be disabled when form is invalid and they must be enabled when form is invalid.

What I have: when I press checkbox form becomes invalid and native HTML button with disabled binding becomes disabled. But my custom button with disabled binding is not disabled. Also I have `ExpressionChangedAfterItHasBeenCheckedError` error in console in dev mode.

## 🔬 Minimal Reproduction

 [Stackblitz example](https://stackblitz.com/edit/angular-2cpkeo)

1. Open example
2. Press checbox (set it to checked).

Expect: 2 buttons disabled (accordingly to all bindings) + no errors in console.
Fact: native HTML button disabled, but my custom control with disabled binding is not disabled + `ExpressionChangedAfterItHasBeenCheckedError` error in console.

Notice: after next change detection cycle everything will become ok (you can trigger it by clicking anywhere outside of controls in my demo).

## 🔥 Exception or Error
<pre><code>
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'disabled: true'. Current value: 'disabled: false'.
</code></pre>

+ visually state rendered incorrecly.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
7.2.7 (also can be reproduced at 7.2.10).
</code></pre>

**Anything else relevant?**

Thoughts about structural directives: Structural directives are compiled to `ng-template` with directives. We figured out that it is not problem with structural directives. Structural directives are copiled to ng-templates. I also added raw `ng-template` example to my tag. So it is not problem with ngIf/ngSwitch/ngForOf or any my project-specific structural directive. Looks like it is problem with `ng-template`.

What I noticed: when I use `ng-template` when `@angular/compiler` creates `ngfactory` for my component for some reasons it create not 1 factory function but more functions. For some reasons `required` binding is in one factory, but buttons binding are in another factory (there are 2 "change detection" functions in each factory). So approximate flow is:

1. Call first "change detection" function from "first" ngfactory (with binding to native HTML button)
2. Call "change detection" function for required binding and change state of the form. 
3. Call second "change detection" function from ngfactory from point 1 ("first" ngfactory).

State of the form is changed in change detection cycle (at point 2) and when we reach point 3 we get another value from absolutely same binding. Because form state changed only at 2 point.

About error in console: In dev mode we have special check. After real change detection we have one more cycle to check if any bindings change their values. So in 1 point we got different values for `disabled` expressions (because form state changed in 1 change detection cycle). Thats why we get this error. 

I can write more verbose if you need. Hope you understood me.

**Comment by sharikovvladislav** [comment]
Any thoughts about workarounds for this issue?

Except setTimeout/debounce/any other async stuff...

Or maybe we are wrong in our thoughts and we use ng forms incorrectly and this is not a but? Can you help us please?

**Comment by pkozlowski-opensource** [comment]
What confuses me about your stackblitz is the fact that the error comes from the commented-out code (HTML comment). Keep in mind that Angular _will_ process things in a HTML comment.

I don't see error if I remove the commented out code: https://stackblitz.com/edit/angular-hyasm1?file=src/app/app.component.html - should it be there?

**Comment by sharikovvladislav** [comment]
> Angular will process things in a HTML comment.

Okay, but I can still see the error in the console.

I will drop video there: https://dropmefiles.com/c3nBb

Notice, that I reproduced this problem on your stackblitz example without commented code.

**Comment by sharikovvladislav** [comment]
I also created separate example with `ng-template` (code which was commented).

https://stackblitz.com/edit/angular-k5hyh2

**Comment by sharikovvladislav** [comment]
I also added video with debugging ngfactory: https://dropmefiles.com/tkyXg

We can see 2 or 3 functions created for AppComponent. One of them contains !checkbox binding (required binding). Another contains both buttons binding (in 2 different sub functions).

So the flow: 
1. detect changes for native html button (first sub function in first factory)
2. detect changes for required="!checbox" binding and change state of the form (in another factory).
3. detect changes for custom component button (second sub function in first factory)

So form state changed in between 1 and 2 button binding checks.

**Comment by sharikovvladislav** [comment]
Hope videos can help you.

Tell me please if you want me to put them on some another hosting.

**Comment by sharikovvladislav** [comment]
So any news on this? Is it just in backlog and would be fixed not rly soon? Looks like it is not even in backlog

**Comment by AndrewKushnir** [comment]
Hi @sharikovvladislav, thanks for providing a repro.

I've re-created it using the most up-to-date version of Angular packages and enabled Ivy, you can find [updated version here](https://stackblitz.com/edit/angular-ivy-d8gx5s?file=src%2Fapp%2Fapp.component.html). The original behavior remains the same (the `ExpressionChangedAfterItHasBeenCheckedError` is being thrown).

The problem that you encountered is related to the order in which Angular processes bindings in root and embedded views (in your example, the one created for the `<ng-template>` content). Angular first processes all bindings in the root template and after that goes through the list of embedded views.

In your example it means that the `[disabled]="form?.form?.invalid"` bindings are processed first and after that bindings for elements inside the `<ng-template>` are executed. As a result of processing bindings inside the `<ng-template>`, the form state changes, thus making the `disabled` binding value different from the one processed earlier. Angular detects that and throws the `ExpressionChangedAfterItHasBeenCheckedError` error. More information on execution order can be find in the [refereshView](https://github.com/angular/angular/blob/7acd33007d9bd30288a76fa2a3b6fe5948143d9f/packages/core/src/render3/instructions/shared.ts#L399) function. You may also find this comment useful as it's mostly applicable to your case as well: https://github.com/angular/angular/issues/35817#issuecomment-628889621.

The possible workaround is to update your template and move buttons to an embedded view as well. You can do that either by using `<ng-template>` + `<ng-container [ngTemplateOutlet]>` like you have for the checkbox and input elements or use `<ng-container>` with a structural directive (like *ngIf):

```
  <ng-container *ngIf="true">
     Form invalid? {{ form?.form?.invalid }}
    <button [disabled]="form?.form?.invalid">works</button>
    <app-my-button [disabled]="form?.form?.invalid"></app-my-button> 
  </ng-container>
```

I've updated the repro with the above mentioned solution, [see here](https://stackblitz.com/edit/angular-ivy-d8gx5s?file=src%2Fapp%2Fapp.component.html).

Thank you.
