### ISSUE TITLE
Easy way to animate change of bound values

### ISSUE THREAD

**Issue by ghost** [angular/angular#29439]
# 🚀 feature request
In my application I have some text. When the text changes, I want to fly out the old text and fade in the new text.

### Relevant Package
This should probably be implemented in @angular/animations?

### Description
In order to implement the solution at the moment, I see two alternatives: 
1. Work with two internal properties (oldValue, newValue) and overlay two divs in order to animate them.
2. Trigger first animation in code, implement a animation done callback. When the callback is executed, change value and trigger the second animation.

Both solutions seem to be quite complex for such a simple task. I wish I could define an animation for before changing the value and after change. 

### Describe the solution you'd like
This could look like:

```ts
@Component({
  selector: 'my-comp',
  template: '<div [@myTrigger]=myText>{{myText}}</div>',
  animations: [
    trigger('oldContent', [
      transition(':before', [
        animate('0.5s ease-in', style({
          opacity: 0.0,
        }))
      ]),
      transition(':after', [
        animate('0.5s ease-in', style({
          opacity: 1.0,
        }))
      ])
    ])
  ]
})
export class MyComponent{
}
```

**Comment by andrui** [comment]
@eosgortor You may use use 'void <=> *' transition along with custom strucural directive which recreates view when data is changed. Here is example https://stackblitz.com/edit/angular-5vng7d

**Comment by eosgortor** [comment]
This is a great third possibility, but still quite complex for the task. I will keep the feature request open. 

Thank you

**Comment by swoerpel** [comment]
I achieved something similar using just an :enter animation and an ngSwitch. just add logic to inc/dec the pageIndex.

![image](https://user-images.githubusercontent.com/39784324/118735628-752b0400-b806-11eb-8561-cfa7bcf1bd23.png)

![image](https://user-images.githubusercontent.com/39784324/118735615-6e03f600-b806-11eb-8005-295378a5aec1.png)

![image](https://user-images.githubusercontent.com/39784324/118735589-5e84ad00-b806-11eb-8d3f-5d7791064430.png)
