### ISSUE TITLE
ViewContainerRef.createComponent not inserting component into element

### ISSUE THREAD

**Issue by zys5945** [angular/angular#29448]
# 🐞 bug report

### Description

ViewContainerRef.createComponent is inserting the components into parent div, not the element itself

## 🔬 Minimal Reproduction

 

See https://stackblitz.com/edit/angular-vcbg86?file=src%2Fapp%2Fapp.component.ts

HelloComponents are not inserted into #placeholder, but rather the parent div

## 🔥 Exception or Error

No exception or error thrown

**Comment by pkozlowski-opensource** [comment]
> ViewContainerRef.createComponent is inserting the components into parent div, not the element itself

`ViewContainerRef` is _always_ inserting views as _siblings_ of a node on which a `ViewContainerRef` was requested (injected). This works as designed.
