### ISSUE TITLE
Protractor: Angular app uses hash routing. e2e tests do not navigate correctly.

### ISSUE THREAD

**Issue by clundberg1** [angular/angular#29445]
### Description

My app has hash enabled for routing. When writing e2e tests with protractor, I try to navigate to the sign up page by passing the relative path and expecting it to be appended to the baseUrl. Something like this in my Page Object: 

`return browser.get('/authentication/sign-up');`

Apparently it tries to navigate to `http://localhost:4200/authentication/sign-up` instead of  `http://localhost:4200/#/authentication/sign-up`. I've tried changing the baseUrl in the protractor.conf.js to `http://localhost:4200/#` but that didn't help. I've even logged `browser.baseUrl` and it's value is always `http://localhost:4200` no matter what value I define in protractor.conf.js
## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.2.3
Node: 8.10.0
OS: win32 x64
Angular: 7.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.12.3
@angular-devkit/build-angular      0.12.3
@angular-devkit/build-optimizer    0.12.3
@angular-devkit/build-webpack      0.12.3
@angular-devkit/core               7.2.3
@angular-devkit/schematics         7.2.3
@angular/cdk                       7.3.0
@angular/cli                       7.2.3
@angular/flex-layout               7.0.0-beta.23
@angular/material                  7.3.0
@angular/material-moment-adapter   7.3.1
@ngtools/webpack                   7.2.3
@schematics/angular                7.2.3
@schematics/update                 0.12.3
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.28.4
</code></pre>

**Comment by vikerman** [comment]
This bug doesn't belong to this repo. Please open a new one in Protractor when there is a repro or try stackoverflow. Thanks.

**Comment by antch** [comment]
I just stumbled on this trying to fix the same issue, and it turns out all you need to do is to prefix with a `#`, for example:

```
return browser.get('#/authentication/sign-up');
```

Of course you still do need to set `baseUrl` in the protractor configuration.
