### ISSUE TITLE
`templateUrl` behaves differently when using the Dart transformer

### ISSUE THREAD

**Issue by andresaraujo** [angular/angular#2945]
I don't know if it a bug or not, but the behaviour of the `templateUrl` is different when using the transformer. e.g:

This works okay *without* the transformer:
```dart
// app.dart
@Component( selector: "my-app" )
@View(
    templateUrl: "packages/my_app/app.html",
)
class AppComponent {}
```

But adding the transformer result in this error:

```
[Warning from DirectiveProcessor on my_app|lib/app.dart]:
Invalid URL to reach to another package: packages/my_app/app.html. Path reaching to other packages must first reach up all the way to the packages directory. For example, try changing the URL to: ../../packages/my_app/app.html
[Error from DirectiveProcessor]:
Uri packages/ng2_dart_quickstart/app.html not supported from my_app|lib/app.dart, could not build AssetId
```

To make it work with the transformer I had to change the `templateUrl` to either `"app.html"` or `"../../packages/my_app/app.html"`. But then then comes the issue that it will not work if you remove the transformer.

Project layout:
```
├── lib
│   ├── app.dart
│   └── app.html
├── pubspec.yaml
└── web
    ├── index.html
    └── main.dart

```

Tested on alpha 30

**Comment by matanlurey** [comment]
Andres, can you try using absolute `package:` URLs?

E.g.

`templateUrl: "package:my_app/app.html"`

You can plugin the following to enable support:

```dart
@Injectable()
class DartUrlResolver implements UrlResolver {
  static final _baseUrlResolver = new UrlResolver();

  final String urlPrefix;

  const DartUrlResolver() : urlPrefix = '';

  const DartUrlResolver.withUrlPrefix(this.urlPrefix);

  @override
  String resolve(String baseUrl, String url) {
    // Delegate to Angular to get a final URL.
    final angularResolvedUrl = _baseUrlResolver.resolve(baseUrl, url);

    // If this is a 'package:' style URL, replace with a pub-resolvable one.
    return angularResolvedUrl.replaceFirst('package:', '${urlPrefix}packages/');
  }
}
```

To add via DI, add this to your `bootstrap` function:

```dart
bind(UrlResolver).toClass(DartUrlResolver)
```

@jakemac53 and @yjbanov may have a better answer :)

**Comment by andresaraujo** [comment]
Thanks! that worked great.

**Comment by matanlurey** [comment]
@yjbanov, does it make sense to bundle this with the Dart version of Angular?

**Comment by yjbanov** [comment]
It does. I turned it into a proposal that covers TypeScript as well: https://github.com/angular/angular/issues/2991

**Comment by yjbanov** [comment]
Closing. Please reopen if #2991 is insufficient
