### ISSUE TITLE
QueryList<T>.get(index)

### ISSUE THREAD

**Issue by FallenMireq** [angular/angular#29467]
# 🚀 feature request

### Relevant Package

This feature request is for @angular/core

### Description
Now there is no way to get element from `QueryList<T>` by index.

### Describe the solution you'd like
Add method `get(index)` to [QueryList](https://github.com/angular/angular/blob/7.2.10/packages/core/src/linker/query_list.ts#L41)
```ts
export class QueryList<T> {
  // ...

  get(index: number): T|undefined {
    return this._results[index];
  }

  // ...
}
```

### Describe alternatives you've considered
Very expensive workaround:
```ts
function getQueryListItemByIndex<T>(list: QueryList<T>, index: number): T|undefined {
  let value;

  let found = list.some((x, i) => {
    if (i === index) {
      value = x;
      return true;
    }
    return false;
  });

  if (found) {
    return value;
  }
}
```

**Comment by pkozlowski-opensource** [comment]
Why not, but you can do `queryList.toArray()[index]` today

**Comment by FallenMireq** [comment]
@pkozlowski-opensource 

But slicing array every time isn't a good solution, I guess..

[QueryList.toArray()](https://github.com/angular/angular/blob/7.2.10/packages/core/src/linker/query_list.ts#L96):
```ts
export class QueryList<T> {
  // ...

  toArray(): T[] { return this._results.slice(); }

  // ...
}
```

**Comment by pkozlowski-opensource** [comment]
> But slicing array every time isn't a good solution

Sure, if you see it as a performance bottleneck in your application after perf-measuring it...

**Comment by dannymcgee** [comment]
@pkozlowski-opensource Even if not a performance bottleneck, it just seems like an oversight that the Angular team provided all of these array-mirroring methods like `forEach` and `map` for interacting with QueryLists, but didn't provide a method for accessing an item by index. I agree with OP, this would be a great feature to have.

**Comment by pburkindine** [comment]
Also like to see this, just awkward boilerplate to pull the array every time

**Comment by Merott** [comment]
Currently accessing by index like this:

```ts
queryList.find((_e, i) => i === index);
```
But sure, it would be nice to just do `.get(index)`
