### ISSUE TITLE
Service inside service

### ISSUE THREAD

**Issue by WarienX** [angular/angular#29461]
I have created an instance of Service 1 inside another Service 2 constructor. But right now it is giving me an error saying:
Can't resolve all parameters for Service 2: ([object Object], [object Object], [object Object], ?).
If I remove it from the constructor and place it outside for e.g
export class Service2 {
 public service1: Service1;
constructor() {}
}
It is showing another error saying
ERROR TypeError: Cannot read property 'ngMetadataName' of undefined at injectArgs

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
