### ISSUE TITLE
Routing not working as Expected

### ISSUE THREAD

**Issue by codekeyz** [angular/angular#29477]
# 🐞 bug report
Here is my route configuration for a submodule 
```typescript
const routes: Routes = [
  {
    path: '',
    component: VehiclesComponent,
    data: {
      title: 'Vehicles'
    },
    children: [
      {
        path: '',
        redirectTo: 'view',
        pathMatch: 'prefix'
      },
      {
        path: 'view',
        component: VehiclesViewComponent,
        data: {
          title: 'View'
        }
      },
      {
        path: 'view/:id',
        component: VehiclesSingleComponent,
        data: {
          title: 'Details'
        }
      },
      {
        path: 'add-new',
        component: VehiclesUploadComponent,
        data: {
          title: 'Add New'
        }
      }
    ]
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class VehicleRoutingModule {}

```

### Description
With this route configuration for my submodule, when i try to navigate to other routes withing this module, it comes prefixed in this form `http://localhost:4200/#/me/vehicles/view/add-new` instead of being `http://localhost:4200/#/me/vehicles/add-new` All works fine when i remove the redirect 
```typescript
    {
        path: '',
        redirectTo: 'view',
        pathMatch: 'prefix'
      }
```
But I need this redirect because the parent component within this module `VehiclesComponent` contains only a router-outlet through which `view`, `add-new` and `view/:id` components get displayed.

**Angular Version:**
<pre><code>

Angular CLI: 6.2.6
Node: 10.15.3
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.8.6
@angular/cli                      6.2.6
@angular/fire                     5.1.1
@angular/pwa                      0.13.5
@ngtools/webpack                  6.1.5
@schematics/angular               0.8.6
@schematics/update                0.8.6
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.9.2

</code></pre>

**Comment by Airblader** [comment]
Try `pathMatch: "full"` for the redirect.

Also this isn't a bug report but a support request. Please use platforms like StackOverflow for these.

**Comment by codekeyz** [comment]
@Airblader thanks, it works fine now.
