### ISSUE TITLE
Awesome dev experience: Can we detect infinite loops in change detection?

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2947]
Right now, it's possibly to hook up a listener on `onChange` or `onAllChangesDone`, and have it trigger a change, which in turn, will cause the function to be called again, ad-infinitum. In dev mode, could Angular detect a loop that will likely never complete (maybe > 10 times?) and throw/fail?

**Comment by mhevery** [comment]
Change detection only runs once in angular, by design. Can you post code which can repro the problem.

**Comment by matanlurey** [comment]
Sure, let me clarify, because we have the onAllChangesDone lifecycle event, you could update the model which triggers a child update which triggers the event, so on and so forth. Does that make sense? I can create a repro but I feel like this is a simple enough case to understand ;)

**Comment by mhevery** [comment]
onAllChangesDone, can not change model. If it did the dev mode check would fail. Ng2 does not allow infinite digest. There is a strict limit of one in ng2.

Do you have a use case which reproduces this?

**Comment by mhevery** [comment]
Per discussion with @matanlurey Closing, reopen when you have repro case.
