### ISSUE TITLE
Componente multiselect primeng

### ISSUE THREAD

**Issue by Jvra2018** [angular/angular#29493]
Portuguese:
Boa tarde, eu estou tentando ajustar o filtro do input do componente multiselect, eu queria que mostrasse na lista os resultados que começam pela primeira letra. 
Exemplo: 
Quando eu digitar no input a letra A, a lista deve retornar aquilo que começa com a letra A.

English:
Good afternoon, I'm trying to adjust the input filter of the multiselect component, I wanted it to show in the list the results that start with the first letter.
Example:
When I type in the input the letter A, the list should return what begins with the letter A.

How do I this??

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
