### ISSUE TITLE
Document difference between EventEmitter and Subject

### ISSUE THREAD

**Issue by pauldraper** [angular/angular#29499]
There is no documentation about the difference between `Subject` and `EventEmitter`. AFAIK, the only differences are EventEmitter's duplicative `emit()` and optional asynchronous mode.

Of the two, `Subject` is shorter, better documented, and is not unique to Angular, so I always prefer `Subject`.

I have no idea if I am getting something important wrong by doing this.

**Comment by Airblader** [comment]
EventEmitter is an Angular abstraction. It being a subject is an implementation detail and not public API.

You should treat them as conceptually different things.

**Comment by Airblader** [comment]
Related: #29016, #23435

**Comment by pauldraper** [comment]
Thanks. That still doesn't really answer why I would ever want to use `EventEmitter.

AFAIK, all of these are valid.

```typescript
@Output()
thing1 = new EventEmitter();

@Output()
thing2 = new Subject();

@Output()
thing3 = anObservable.pipe(map(a => a * 2));
```

When would I want to use the first?

**Comment by ericmartinezr** [comment]
Pretty much this https://www.bennadel.com/blog/3045-ward-bell-do-not-expect-eventemitter-to-be-observable-in-angular-2.htm. I'm not sure how valid it is nowadays though.

**Comment by Airblader** [comment]
> AFAIK, all of these are valid.

The only documented one for @Output is EventEmitter. Just because something else works doesn't mean it's guaranteed to work. :-)

**Comment by pauldraper** [comment]
Hm, true.

In light of how much Angular is using RxJS, the decision will be made to officially support Observable as @Output.

**Comment by jenniferfell** [comment]
As mentioned, subject is not part of Angular's public API. It is part of the RxJS API and therefore documented there: 
https://rxjs.dev/api/index/class/Subject

An Angular app certainly isn't limited to Angular's API, but we typically don't document the various alternatives available. We also don't typically document the implementation of Angular's API. 

In this case, however, it might make sense for the EventEmitter API doc to mention that it extends RxJS subject, include a xref link, and mention what Angular adds. 

@benlesh @jasonaden @brandonroberts @jbogarthyde  What do you think?

**Comment by jbogarthyde** [comment]
Resolved by https://github.com/angular/angular/pull/31780
