### ISSUE TITLE
navigationId inside RouteReuseStrategy

### ISSUE THREAD

**Issue by huntering** [angular/angular#29498]
# 🚀 feature request

### Relevant Package
@angular/router

### Description
I would like to have the navigationId available inside the RouteReuseStrategy to create a stack of pages.
The use case: Suppose I have a page that I can use to search a specific contact. I select contactttype "Accountmanager" and I know the CEO of the company he works for. So from this page I jump to a page to lookup a company. I don't know the company-name but I know the CEO. So from this page I jump to lookup a contact. I find the CEO, i hit "select". I come back in the page to lookup a company and the CEO is shown in the filter. I find my company, I hit select and I come back in the page to find contacts. My selection "Account Manager" is still present and the company name is added to the filter.
I want these pages to be stored in my RouteReuseStrategy but I can't use the URL because it's not unique.
My application is thus a stack of pages. While looking for information I open new pages in the same browserwindow that are added to the stack and as i find stuff I pop the pages from the stack, but the URL cannot be used to identify these pages.

### Describe the solution you'd like
I would like to use the navigationId to create a map of DetachedRouteHandle so I would like this parameter to be passed to the methods of the RouteReuseStrategy interface.

### Describe alternatives you've considered
I could add an id to every URL to simulate the navigationId but that seems awkward.
I've tried to access the navigationId from ActivatedRouteSnapshot but I cannot obtain it.

**Comment by Airblader** [comment]
You could also just use a service in which you store the intermediate results(?)

Another way would be to use query parameters for the actual search information, which would make the URL reentrant.
