### ISSUE TITLE
Angular 7 Routes is not backward compatible, does not execute ** when it didn't match any route

### ISSUE THREAD

**Issue by kaifuluca2016** [angular/angular#29500]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by kaifuluca2016** [comment]
Several Project routes not work well after upgrade Angular from 6.3 to 7.2.9. 
const appRoutes: Routes = [
  { path: '', component: OverviewpublishedListComponent },
...
{ path: '**', component: PageNavigateRouterComponent },

when it didn't match any other route, it should execute  the route as below:
{ path: '**', component: PageNavigateRouterComponent },

but after upgrade to angular 7.2.9. this is extremly compatible issues. it block the client correctly pay the billment and so on. It just jump into dashboard.
So important change, why not give very clear explain. You know any thing about routes, it is very important. Because it decided to which page it will go. I searched this issue very long time. I found all of upgraded angular 6.3 to 7.2.9 project had been affected, but others( without upgrade angular from 6 to 7) work very well.

**Comment by ericmartinezr** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

<hr>

Please provide a reproduction.

**Comment by kaifuluca2016** [comment]
> I'm sorry but we can't reproduce the problem following the instructions you provided.
> 
> If the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
> 
> Please provide a reproduction.
for example:
https://www.fulldaymall.com/browse/index.html?navigate=PricingtablesComponent
It can't jump to Pricing table directly.
But for another project
https://www.fulldaymall.com/register/index.html?navigate=ResetPasswordRequestFormComponent
it work very well.

**Comment by ericmartinezr** [comment]
A stackblitz would be ideal as stated in the issue template, it is not possible to debug it using your website. If it isn't possible through a stackblitz, a repository would work as well.

**Comment by kaifuluca2016** [comment]
> A stackblitz would be ideal as stated in the issue template, it is not possible to debug it using your website. If it isn't possible through a stackblitz, a repository would work as well.

Okay, I will upload a simple project or using stackblitz to explain it.

**Comment by pkozlowski-opensource** [comment]
> Okay, I will upload a simple project or using stackblitz to explain it.

Going to close for now as there are not enough details here and we haven't heard back with a reproduce scenario.
