### ISSUE TITLE
ng-for: support observable collections in Dart

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#2950]
An observable collection implements both `Iterable` and `Observable`, and delivers `ListChangeRecord`s. Example: `ObservableList` from `package:observe`.

ng2 should support custom implementations too and not rely on `ObservableList` specifically.

/cc @matanlurey

**Comment by vsavkin** [comment]
Closed via https://github.com/angular/angular/commit/d449ea5ca40d8d5904feee2fa92f27e3ffc5616b

**Comment by vsavkin** [comment]
This is how you use it:

```
@Component({
  hostInjector: [
    Pipes.extend({
      "iterableDiff": [const ObservableListDiffFactory()]
    })
  ]
})
class MyComponent {} 
```

Any place that requests an iterableDiff and uses an ObservableList from the observe package, will use ObservableListDiff.

ObservableListDiff does the following:
- Diffs the collection only if the collection changes.
- It notifies change detection (needed for ON_PUSH change detection).

**Comment by matanlurey** [comment]
Thanks! Will try this.
