### ISSUE TITLE
why not output params e?

### ISSUE THREAD

**Issue by anarckk** [angular/angular#29501]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....

https://github.com/angular/angular/blob/fd5cd100a3c8fb357f2a85769c74e5a847ddcd4a/packages/router/src/router.ts#L1046

### Description

I wonder why I get warnings when I use baseHref in the angular.json file

![image](https://user-images.githubusercontent.com/27038948/54904233-f2a1a500-4f18-11e9-9535-ed0dc894b58f.png)

### Describe the solution you'd like

e => { this.console.warn(`Unhandled Navigation Error: `, e);

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by anarckk** [comment]
我想让你把这个错误打印在控制台上。

**Comment by anarckk** [comment]
这样方便排查错误
