### ISSUE TITLE
docs(app-shell): needs some additional polish

### ISSUE THREAD

**Issue by Splaktar** [angular/angular#29511]
# 📚 Docs or angular.io bug report

### Description

I’m very glad that we have a Guide for `app-shell` now (https://next.angular.io/guide/app-shell via https://github.com/angular/angular/pull/28591)! However, it seems less polished than some of the other guides.

### What's the affected URL?**
https://next.angular.io/guide/app-shell

### Reproduction Steps**

- Typos like “For an existing application, you have to manually add the RouterModule and **defining** a <router-outlet>“.
- It seems like there should be a `Step 1a` and `Step 1b` with example snippets for an existing application
- For `Step 2`
  - `my-app` takes the name of your client application.
  - `server-app` takes the name of the Universal (or server) application.
  - These seem to be just repeating what’s on the command line example above. Should we be referencing the `--client-project` and `--universal-project` instead of `my-app` and `server-app` here?
  - It seems like there needs to be more explanation of where a developer would go to find these names.
- `Step 3` helps you verify that `ng run app-shell` works, but what about `Step 4` where you integrate this with your normal build, deploy, and verify this? If that gets too complicated, is there a section in the Universal docs that we should be pointing them to?
  - i.e. do they run that before or after `ng run my-app:app-shell`? should they do something like this? `"build:prod": "ng build --prod && ng run my-app:app-shell",`
  - or does `ng build --prod` already handle this and they don’t need to know about `ng run my-app:app-shell`?

### Expected vs Actual Behavior**
See above.

## 📷Screenshot
N/A

## 🔥 Exception or Error
N/A

### Browser info
Chrome 73

### Anything else relevant?
N/A

**Comment by Splaktar** [comment]
My opinion is that the hierarchy should be something like this

- Techniques
  - Security
  - Internationalization (i18n)
  - PWA (Overview with a link to a brief summary + stats from https://developers.google.com/web/progressive-web-apps/, HTTPS required, also cover auditing with Lighthouse)
    - Loading Performance (lazy loading tips with a focus on PWAs, tips for loading fonts, images, videos, etc)
      - App Shell
      - Service Workers
    - Offline (Docs on implementing offline support with Service Workers, tips for batching API requests and sending when back online, etc.)
    - Runtime Perf (TBD tips for smooth 60 FPS animations and smooth scrolling on all devices)
    - Native Look and Feel
      - Web App Manifest (make app installable, screen modes, theme colors)
      - Push Notifications (Docs on implementing these using Service Workers and cloud services)
  - ...

**Comment by jbogarthyde** [comment]
To implement the suggested changes to app-shell alone, I need:
* The examples for steps 1a and 1b
* The answers to your questions about a possible new step 4

I need to know a lot more about this to be able to implement the organization suggestions and create a PWA Overview. Even to improve the intro to app-shell, I need to know more about the relationship between Service Workers/app-shell and Universal.

**Comment by Splaktar** [comment]
To keep the ‘existing application’ part of step 1 short, I would actually set up routing without a module (most GDEs agree that this is the preferred approach today).

I’m not sure what the default routes configuration is for a new app that has run `ng generate app-shell --client-project my-app --universal-project server-app`, but the example here should probably be the similar.

https://developers.google.com/web/progressive-web-apps/checklist breaks down the goals of PWAs and suggestions how to test and fix each checklist item. 

- Service Worker is a solution to a number of these (push notifications, offline support, quick performance on reloads (not on the first page load)). 
- [The App Shell Model](https://developers.google.com/web/fundamentals/architecture/app-shell) explains how an app shell can be combined with Service Worker caching to provide a fast and responsive app loading experience.
- As mentioned in the [Universal Guide](https://angular.io/guide/universal), server-side rendering with Universal helps to address these key areas of a PWA
  - Faster First Contentful Paint (FCP), especially on mobile devices and networks. This helps with the first page load part that Service Workers don't solve.
  - Improved SEO

**Comment by rockument69** [comment]
@jbogarthyde : Do we need more engineering input on this? I'm sure we at least need the examples for steps 1a and 1b. This issue is already labeled for more input.

**Comment by Splaktar** [comment]
@rockument69 yes, I believe the current state is accurate.

**Comment by jbogarthyde** [comment]
I have a branch with the underlying framework ready to pop in information and set up the suggested navigation structure, when engineering is ready to work on it.

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
