### ISSUE TITLE
LI tag unable to focus on it only in angular

### ISSUE THREAD

**Issue by hemachandsai** [angular/angular#29512]
Hello everyone,

I had struggled a lot with this issue. I would be glad if anyone could help me

I had a simple code with an ul tag and nested li tags.When i tried to focus on the li element through console queryselector or javascript code in component or through viewchild it is not happening.I had also given tabindex.The same code is working fine with normal html and javascript ,the problem is happening only with angular.But when i try to simulate the same using devtools in chrome by selecting sudo focus property it is working fine.

NOTE: Iam using the latest angular version

Thanks in advance!!!

**Comment by pkozlowski-opensource** [comment]
Could you please provide a minimal reproduce scenario of the issue using stackblitz?
You can start with this one: https://stackblitz.com/edit/angular-srxnrt

**Comment by Airblader** [comment]
> NOTE: Iam using the latest angular version

Angular 8 Beta? I doubt it. Please include the actual version and follow the issue template for new issues.

**Comment by hemachandsai** [comment]
Thanks for your support guys. I had tried to reproduce it in stackblitz and is working fine there. May be it is some sort of issue from my system.
