### ISSUE TITLE
ngFor over complex data does not work for custom-elements in IE and Edge (freeze)

### ISSUE THREAD

**Issue by mzeiher** [angular/angular#29510]
# 🐞 bug report

### Affected Package
`@angular/core`

### Is this a regression?
Not testet in older Version

### Description
If you iterate over a complex array (array consisting of Objects) on an custom-element with *ngFor and the custom element deffers a render/update in a task or microtask angular freezes on IE11 and Edge. If you iterate over an array of basic-types everything works fine.

## 🔬 Minimal Reproduction
Repository to reproduce:
https://github.com/mzeiher/ngFor-custom-element-bug

Custom Elements defined here (one which renders directly, one defers render to a microtask, one defers render to a setTimeout):
https://github.com/mzeiher/ngFor-custom-element-bug/blob/master/src/app/app.component.ts

Angular Template:
https://github.com/mzeiher/ngFor-custom-element-bug/blob/master/src/app/app.component.html

just run `npm start`, un-comment line 5 and 6 in `app.component.html` and startup Edge or Internet Explorer 11. The page freezes, looks like the renderer is stuck in an endless loop (if the render is defered to a microtask the browser obviously freezes, if defered to a setTimeout the render just re-renders in an endless loop)

## 🔥 Exception or Error
<pre><code>
IE11 and Edge freeze, renderer stuck in endless loop
</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 7.3.6
Node: 11.12.0
OS: win32 x64
Angular: 7.2.10
</code></pre>

Source code is ES5, @webcomponents/webcomponentsjs polyfill is loaded for Edge and IE

If you need more code sample just let me know it.

**Comment by mzeiher** [comment]
if I wrapp the Promise or setTimeout in `globalZone.runOutsideAngular(() => { ... }` everything works and the browser does not freeze

At the moment I can't just import custom elements created that way in angular, I don't want to need to implement a heuristic to determine if the custom element runs in zone.js and hack a way out of it (thus using somehow native promises).

version wrapped with runOutsideAngular here:
https://github.com/mzeiher/ngFor-custom-element-bug/blob/zone-js-hack/src/app/app.component.ts

**Comment by mzeiher** [comment]
custom elements created with lit-element are also affected:
sample lit-element:
https://github.com/mzeiher/lit-element-test

sample with lit-element
https://github.com/mzeiher/ngFor-custom-element-bug/tree/lit-element-test

**Comment by JiaLiPassion** [comment]
I will check it, thanks!

**Comment by mzeiher** [comment]
thanks! If you have questions about how to reproduce this issue just let me know, I'll try the best I can to help you.

**Comment by mzeiher** [comment]
This can be closed -> I tracked the issue down to the bundling of @webcomponents/webcomponentsjs polyfill, if included via "scripts" in the angular.json the polyfills do not work as intended, the polyfill must be loaded in a script tag in the html (either CDN or assets) before everything else,
