### ISSUE TITLE
Wrong code sample for directive's outputs attribute

### ISSUE THREAD

**Issue by balteo** [angular/angular#29523]
# 📚 Docs or angular.io bug report

### Description

 The provided code sample for a directive's outputs attribute points to the directive's exportAs attribute instead.

### What's the affected URL?**
 https://angular.io/api/core/Directive#outputs

See: https://github.com/angular/angular/blob/master/packages/core/src/metadata/directives.ts#L165

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by kevinsunny1996** [comment]
Is this issue solved or still open?

**Comment by inidaname** [comment]
Hello @brandonroberts is this still open or resolve will like to take a shot at it.

Thank You

**Comment by brandonroberts** [comment]
@kevinsunny1996 @inidaname there is a PR here that is unfinished if you want to take it forward.

https://github.com/angular/angular/pull/30014

**Comment by inidaname** [comment]
@bradbrandhorst I have gone through #30014 but I am not clear to what to add, could I get a little direction.

PS: This will be my first contribution on angular

**Comment by brandonroberts** [comment]
@inidaname sure. Right now the PR example looks like this

   ```typescript
   @Directive({
     selector: 'child-dir',
     outputs: [ 'bankNameChange' ]
   })
   class ChildDir {
    bankNameChange: EventEmitter<string> = new EventEmitter<string>();
   }
   
   @Component({
     selector: 'main',
     template: ` {{ bankName }} <child-dir (bankNameChange)="onBankNameChange($event)"></child-dir>`
   })
   class MainComponent {
      onBankNameChange(bankName: string) {
        this.bankName = bankName;
      }
   }
```

We want to show a child component outputting an event that is handled in its parent template. So the `Directive` would need to change to a `Component` with a template. In the template, there is an `input` to that listens for an `(input)` event and emits the value of the `input` using the `bankNameChange` event emitter. I would suggest mocking something simple up in StackBlitz before opening a PR.

If you need more guidance, just let me know.

**Comment by laumair** [comment]
@brandonroberts https://github.com/angular/angular/pull/31199
