### ISSUE TITLE
Angular Reactive Forms - Clash with 1Password

### ISSUE THREAD

**Issue by george43g** [angular/angular#29520]
# 🐞 bug report

### Affected Package
The issue is found in package @angular/reactive-forms

### Is this a regression?
Not sure.

### Description

When coding up a login form, one of the features commonly used is detecting when the inputs have been "touched". This allows us to only show validation errors on inputs after the user has finished typing in that input box, or switched focus to another DOM element.

This usually works OK, except upon some research I realised that a bug that I was experiencing was being caused by the 1Password Chrome extension.

For some reason, when the extension is active, it triggers the "onBlur" event (or whatever event) on the input box almost immediately. I was able to compare two browser windows with the exact same environment, with the only difference that on one of those, 1Password was enabled and it was suggesting to autofill a password. In the 1Password window, as soon as the form control is in focus, it's already "dirty" and "touched", which triggers the error messages "email is invalid" to show immediately before the user has even had a chance to type anything. Im not sure how 1Password affects this, but it definitely causes the input element to behave as if it has already been used and lost focus, resulting in error messages showing instantly and affecting the user experience. I suspect it has something to do with the little icon/logo it shows inside the input box that allows users to auto-fill login details.

Just to be sure, on the chrome window that didn't have 1Password, the input forms worked as expected. the control stays "untouched" until the user loses focus of the input, only after the user has finished typing and moved on will the form display any errors.
I was definitely able to isolate 1Password as the cause.

I have already posted in the 1Password support forum here: https://discussions.agilebits.com/discussion/102640/developer-issue-angular-reactive-forms-clash-with-1password/

I'm unsure whose responsibility it is to fix such a bug.

## 🔬 Minimal Reproduction
I was about to code it all up again to reproduce (so just use any reactive form with an input element) but I wouldn't be able to include the browser plugin which causes the bug. I think that the description shows it's quite simple.

Steps:
1. Have a reactive form.
2. Include any validation code, and watch the value of "input.touched"
3. Install 1Password extension (a lot of people use this) and watch "input.touched" eval to true as soon as you type anything.

Expected Behaviour:
"input.touched" should only eval to true AFTER the input loses focus for the first time.

Bug:
"input.touched" evals to true as soon as you start typing.

## 🌍  Your Environment

**Angular Version:**
Latest
<pre><code>

Angular CLI: 7.3.5
Node: 11.11.0
OS: darwin x64
Angular: 7.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.5
@angular-devkit/build-angular     0.13.5
@angular-devkit/build-optimizer   0.13.5
@angular-devkit/build-webpack     0.13.5
@angular-devkit/core              7.3.5
@angular-devkit/schematics        7.3.5
@angular/cdk                      7.3.4
@angular/cli                      7.3.5
@angular/fire                     5.1.2
@angular/material                 7.3.4
@angular/pwa                      0.12.4
@ngtools/webpack                  7.3.5
@schematics/angular               7.3.5
@schematics/update                0.13.5
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

MacOS, MacBook Pro 2017, Chrome Browser (Latest), 1Password Extension V1.14.2

PS: I'm sorry if this isn't written properly. It's my first ever bug report for any open source software ever, so go easy on me.

**Comment by kara** [comment]
@george43g Thanks for taking the time to file an issue. I took a look, but I'm not sure there is much we can do on the Angular end, since the form is behaving as expected. Blur events are intended to flip controls to "touched". It seems like the 1Password plugin is causing the blur event to fire inappropriately, so this is probably something they would need to fix.

**Comment by Airblader** [comment]
I would like to add something:

> PS: I'm sorry if this isn't written properly. It's my first ever bug report for any open source software ever, so go easy on me.

You did a great job at reporting the issue properly. If only all new issues were as well written! :-)
