### ISSUE TITLE
Migration to core-js@3.x

### ISSUE THREAD

**Issue by WuglyakBolgoink** [angular/angular#29531]
See https://github.com/zloirock/core-js/blob/master/CHANGELOG.md#300---20190319

When we can upgrade this package?

**Comment by steveblue** [comment]
Please just do it in 8.0.0. I ran a forced update with the cli yesterday to test the latest 8.0.0-beta and core-js was the only package I had to downgrade after the cli automatically updated everything.

**Comment by steveblue** [comment]
If you do this `ng update --next --force` to test 8.0.0 packages right now, core-js is the only package you have to downgrade currently to get everything to work.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by WuglyakBolgoink** [comment]
@mhevery tnx for info.

**Comment by trotyl** [comment]
@WuglyakBolgoink Angular doesn't depend on `core-js`, I guess you mean Angular CLI instead, you can track https://github.com/angular/angular-cli/issues/13954 for the progress.

**Comment by WuglyakBolgoink** [comment]
@trotyl ah... right..
