### ISSUE TITLE
Tutorial toh-pt6 directs reader to delete mock-heroes.ts when it's still being used

### ISSUE THREAD

**Issue by solarjoe** [angular/angular#29535]
There is a small issues with the current toh-pt6 HTTP

The doc states 

> This file replaces mock-heroes.ts, which is now safe to delete.

This is not true at that point as in `hero.service.ts` there is the import

> import { HEROES } from './mock-heroes';

and `HEROES ` is still used in 

```
getHero(id: number): Observable<Hero> {
    ...
    return of(HEROES.find(hero => hero.id === id));
  }
```

[Later](https://angular.io/tutorial/toh-pt6#get-hero-by-id) in the tutorial this function is replaced but until then the code does not work. 

E.g. at the end of section [Get heroes with HttpClient](https://angular.io/tutorial/toh-pt6#get-heroes-with-httpclient) the doc states 

> Refresh the browser. The hero data should successfully load from the mock server.

but the code is broken at this point.

**Comment by rockument69** [comment]
I encountered this error also. I can volunteer to fix this by replacing "which is now safe to delete" with "which you should keep, not delete yet".

**Comment by rockument69** [comment]
This issue is fixed in next by the closing of this PR: [37516](https://github.com/angular/angular/pull/37516)
