### ISSUE TITLE
angular2.sfx.dev.js does not attach `angular` to the global object

### ISSUE THREAD

**Issue by theotherzach** [angular/angular#2953]
The subject says it all. Include`alpha.30` in the script tag and `angular` is no longer available as a global variable.
<img width="1392" alt="screen shot 2015-07-08 at 10 05 49 pm" src="https://cloud.githubusercontent.com/assets/1697198/8587132/8e5d8e16-25bd-11e5-860f-17390f13042a.png">

Tested on both `master` and `alpha-30`. I did not have this problem in `alpha.28`

**Comment by robwormald** [comment]
its available now as `ng` - https://github.com/angular/angular/blob/master/modules/angular2/angular2_sfx.ts#L18

**Comment by rkirov** [comment]
as @robwormald  it has been renamed to `ng` by https://github.com/angular/angular/commit/65a767d9b0b2816af86065083108bd517c35ce48
