### ISSUE TITLE
Windows: --watchfs is causing test to be flaky

### ISSUE THREAD

**Issue by meteorcloudy** [angular/angular#29541]
Following https://github.com/angular/angular/issues/27424#issuecomment-444116352, I tried to run `yarn bazel test //packages/core/test/render3` on Windows. And found the tests often fail with various kinds of IO error.
See the log here: https://gist.github.com/meteorcloudy/cb6b838266f1a1fd51ce59e5101bf40f

It turned out to be caused by `--watchfs`: 
https://github.com/angular/angular/blob/a28b3e33598cf6a9fae685d8c1a1e39b419d1c78/.bazelrc#L38-L39

If watchfs is enabled, it will [hold handles to all directories in the source trees](https://github.com/bazelbuild/bazel/blob/618a0760144a1b78fc41895447df0e03fea558b7/src/main/java/com/google/devtools/build/lib/skyframe/WatchServiceDiffAwareness.java#L255), which causes the test to be flaky.

@alexeagle @filipesilva Do you know how much do we need "--watchfs" to improve performance? We have an issue for supporting watchfs on Windows, but currently it is low priority. https://github.com/bazelbuild/bazel/issues/1931

FYI @meisterT @dslomov

**Comment by filipesilva** [comment]
@meteorcloudy my understanding is that `--watchfs` improves performance on linux/macos and thus should be turned on. But that it sometimes causes weird behaviour on windows, so it should be turned off there.

**Comment by meteorcloudy** [comment]
If it improves performance on Linux/macos by avoiding stat'ing input files, I think if we implement a proper watchfs on Windows, it could also benefit the Windows performance a lot.

**Comment by meteorcloudy** [comment]
Do you know how much it speeds up the Linux/macOS build?

**Comment by filipesilva** [comment]
No, I don't have a linux/macos machine to test that on.

**Comment by meteorcloudy** [comment]
No problem, I can look into it, thanks!
