### ISSUE TITLE
Inconsistent, non deterministic behaviour when using descendant, child selector 

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#29563]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/* 7.0.1

### Is this a regression?

Dont know if it was working.

### Description

When you have `Component` with selector defined as `"ng-select option"` or `"ng-select>option"` you will get inconsistent behaviour of creation of component. 

I think these types of selectors are not supported, but it should either work, or dont. But currently on same page i get two different results.

I have following HTML
```html
<select>
  <option [value]="itm.value" *ngFor="let itm of values">{{itm.name}}</option>
</select>
```

Sometimes it will replace `<option>` with my component and sometimes it does not. That means that few selects are working correctly and few does not. If these selectors were supported it should not create component, only when it is inside of `<ng-select>`, but what should happen if it is not supported?

## 🔬 Minimal Reproduction

I need to find out how to simulate this, because right now i cant, since i dont know what is causing it.

## 🔥 Exception or Error
No error occured

## 🌍  Your Environment

**Angular Version:**
7.0.1

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment]
> I think these types of selectors are not supported

Correct.

>  But currently on same page i get two different results.

This doesn't sound right. Could you please provide a minimal stackblitz reproducing this?

**Comment by kukjevov** [comment]
I will try to reproduce it, but that could be bit a problem, because it is happening in our production application which cant be shared, but i try to reproduce it.

**Comment by pkozlowski-opensource** [comment]
> I will try to reproduce it, but that could be bit a problem, because it is happening in our production application which cant be shared, but i try to reproduce it

Yeh, I understand that it might be tough to reproduce but please try to isolate it - I'm afraid that we can't do much without a reproduce scenario :-/

**Comment by alxhub** [comment]
Closing for lack of a reproduction. Please feel free to reopen if this is still an issue and it can be reproduced.
