### ISSUE TITLE
deploy angular 7 project with apache server in subfolder

### ISSUE THREAD

**Issue by jsasmitha** [angular/angular#29561]
Angular CLI: 7.3.1
Node: 11.1.0
OS: darwin x64
Angular: 7.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.1
@angular-devkit/build-angular     0.13.1
@angular-devkit/build-optimizer   0.13.1
@angular-devkit/build-webpack     0.13.1
@angular-devkit/core              7.3.1
@angular-devkit/schematics        7.3.1
@angular/cli                      7.3.1
@ngtools/webpack                  7.3.1
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

Index.html:

```
> <!doctype html>
> <html lang="en">
> <head>
>   <meta charset="utf-8">
>   <title>Flightslogic</title>
>   <base href="/">
> 
>   <meta name="viewport" content="width=device-width, initial-scale=1">
>   <link rel="icon" type="image/x-icon" href="favicon.ico">
> </head>
> <body>
>   <app-root></app-root>
> </body>
> </html>
> 
> 
```

App.routing:-
```
const routes: Routes = [
  { path: 'home', component: HomeComponent, pathMatch: 'full' },
  { path: '',  redirectTo: 'home', pathMatch: 'full' },
  { path: 'about-us', component: AboutUsComponent,  },
  { path: 'contact-us', component: ContactUsComponent,  },
  { path: 'products/fare-app', component: ProductFareAppComponent,  },
  { path: 'developer', component: ResourceDeveloperProgramComponent,  }
];

@NgModule({
  imports: [RouterModule.forRoot(routes), ],
  exports: [RouterModule]
})

```

Home page nav:
```
 <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link waves-light" href="#"  mdbWavesEffect>Home<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-light" mdbWavesEffect  href="about-us">About</a>
          </li>
<ul>
```

I want to deploy to apache server with subdirectory. How can I achieve that.
For ex: http://www.example.com and the subdirectory is subdir. So I want to deploy to http://www.example.com/subdir. How can I achieve it.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by istiti** [comment]
To change index.html's `<base>` tag `href=""` value you can make use of [--baseHref](https://angular.io/cli/build)

Simply command `ng new ap --minimal && cd ap && ng build --baseHref "okkk"` will ouput in `/dist/ap/index.html` : 
```
...
<base href="okkk">
...
```

If you already know that angular CLI argument then I think your question is not related to angular but apache server ask on SO with apache tag
