### ISSUE TITLE
Routes missing paths

### ISSUE THREAD

**Issue by JDillon522** [angular/angular#29574]
# 🐞 bug report

### Affected Package
Not sure. Presumably the router

### Is this a regression?
No

### Description
I have a series of lazy loaded routes. I recently added a new route and my app started to break. It builds fine but instead of redirecting to the correct route it redirects to the first processed route's first child route. Its hard to explain so heres my code:

````typescript
export const AccountPageRoutes: Routes = [
  {
    path: '',
    component: AccountPageComponent,
    children: [
      {
        path: '',
        component: AccountRootComponent
      },
      {
        path: 'settings',
        loadChildren: './child-pages/settings/settings.module#AccountSettingsModule'
      },
      {
        path: 'admin',
        loadChildren: './child-pages/admin/admin.module#AccountAdminModule'
      },
      {
        path: 'locations',
        loadChildren: './child-pages/locations/locations.module#AccountLocationsModule'
      },
      {
        path: 'users',
        loadChildren: './child-pages/users/users.module#AccountUsersModule'
      },
      {
        path: 'tasks',
        loadChildren: './child-pages/operational-tasks/operational-tasks.module#AccountOperationalTasksModule'
      },
      // A few routes are removed since this code relates to a business production app
      
    ]
  }
];

````

When I go to the `/account` route it does not load the `AccountRootComponent` but instead loads the component that should be at `/account/locations/list`. I added `{enable: tracing}` to the root module to trace the routes and saw this:

![image](https://user-images.githubusercontent.com/4861202/55188741-73a7a900-5172-11e9-8690-f4cd1835c851.png)

It seems as though the `path` property next to the `loadChildren` is getting removed. 

I have no idea if this is a bug in Angular or in my code. Its rather bizarre. 

I'll provide as much code as I can but I dont know if this is something I can fully reproduce in isolation. Any ideas on where to look would be helpful.

## 🔬 Minimal Reproduction
I dont know if I could

## 🔥 Exception or Error
No error is accompined in the CLI output or in the window console.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.6
Node: 8.9.4
OS: win32 x64
Angular: 7.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        7.3.6
@angular/cdk                      7.3.5
@angular/cli                      7.3.6
@angular/material                 7.3.5
@ngtools/webpack                  6.0.8
@schematics/angular               7.3.6
@schematics/update                0.13.6
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.8.3

</code></pre>

**Comment by Airblader** [comment]
Shouldn't there be a `pathMatch: "full"` in the empty route for AccountRootComponent?

Still seems like odd behavior, I think, though.

**Comment by JDillon522** [comment]
@Airblader normally yes. My `app-routing.module.ts` looks like this:

```typescript
export const routes: Routes = [
  {
    path: 'dev',
    loadChildren: './pages/dev-page/dev-page.module#DevPageModule'
  },
  {
    path: 'account',
    loadChildren: './pages/account/account.module#AccountPageModule'
  },
  {
    path: '',
    pathMatch: 'full',
    redirectTo: 'account' // TODO change to home page eventually
  }
];

@NgModule({
  imports:
  [
    CommonModule,
    // AccountPageModule,
    RouterModule.forRoot(
      routes,
      { enableTracing: true}
    )
  ],
  exports: [
    RouterModule
  ]
})
export class AppRoutingModule { }
```

So in my case `/account` is actually a routable page with many child routes. On each of those lazy loaded child routes there is a redirect.

But yeah, the behavior is really odd. I'm going to do the classic "back out everything and reintroduce one by one" to try and debug it.

**Comment by JDillon522** [comment]
I think I found the problem.

I was stupidly importing the lazy loaded modules into the `AccountModule`. So it was causing a bit of route-inception of sorts.

Perhaps this should be changed to a feature request for better error handling in such a weird case. I wish there was some sort of way to throw a breaking error if someone does something like that. I'll try to see if I can create a stackblitz recreating the issue.

**Comment by jasonaden** [comment]
Closing based on this having been resolved as above. But also sounds like if you can reproduce it, we would love to see as a feature request.
