### ISSUE TITLE
@angular/bazel's schematics property should be project not name

### ISSUE THREAD

**Issue by mgechev** [angular/angular#29572]
# 🚀 feature request

### Relevant Package

`@angular/bazel`

### Description

When `ng add @angular/bazel` we need to specify the project with `--name`. This is not intuitive, especially if we omit it:

```
~/Projects/real-world-bazel master* ng add @angular/bazel
Skipping installation: Package already installed
Schematic input does not validate against the Schema: {}
Errors:

  Data path "" should have required property 'name'.
```

### Describe the solution you'd like

Rename the option to `--project` or `--project-name`.

**Comment by kyliau** [comment]
Should have been closed by https://github.com/angular/angular/pull/30074

Manually closing this.
