### ISSUE TITLE
Where can I find the typings file “zone.d.ts”

### ISSUE THREAD

**Issue by camden-kid** [angular/angular#2958]
The file globals.d.ts references the file typings/zone/zone.d.ts but there isn't a typings directory.

**Comment by hdeshev** [comment]
It is [installed](https://github.com/angular/angular/blob/master/modules/angular2/tsd.json) by the `tsd` tool. You can run `tsd --reinstall` from the `modules/angular2` dir, and it will land in `typings/zone`.

**Comment by camden-kid** [comment]
I just tried that and this was the output (on a Max, OSX 10.10.3):

>> tsd 0.6.3

>> main:
   
   install <...pattern>        install definitions using one or more globbing patterns.

       $ tsd install mocha                   : install mocha
       $ tsd install angularjs/              : install full angularjs bundle

Followed by install options.

**Comment by hdeshev** [comment]
Oops - it should be `tsd reinstall` (no double hyphen).

**Comment by camden-kid** [comment]
Thank you. That worked.

**Comment by camden-kid** [comment]
Not related to this I'm getting a few more errors. They're not too important but I thought I would show them:

    angular2/src/directives/ng_for.ts(54,18): error TS2346: Supplied parameters do not match any signature of call target.
    angular2/src/facade/lang.ts(8,36): error TS2311: A class may only extend another class.
    angular2/src/facade/lang.ts(12,5): error TS2335: 'super' can only be referenced in a derived class.
    angular2/src/forms/directives/shared.ts(52,3): error TS2346: Supplied parameters do not match any     signature of call target.
    angular2/typings/hammerjs/hammerjs.d.ts(6,1): error TS6053: File 'angular2/typings/touch-events/touch-events.d.ts' not found.

**Comment by naomiblack** [comment]
closing this issue -- will be resolved by ongoing work to complete d.ts file.
