### ISSUE TITLE
Using LoadChildrenCallback prevents creating separated bundle for lazy module.

### ISSUE THREAD

**Issue by MaKCbIMKo** [angular/angular#29589]
# 🐞 bug report

### Description
Documentation says that I can use `LoadChildrenCallback` to specify loadChildren instead of providing `string`.
But in that case, `build/serve` doesn't create separated bundle for lazy module and includes code into `main` bundle -> which removes almost all benefits of using lazy modules.
When using string, separated bundle file is created, but I don't like string much, because there is no proper static safety for provided module path.

## 🔬 Minimal Reproduction
Using the following approach:
```
export function LoadMyModule() {
  return MyModule;
}

{
  path: '', 
  loadChildren: LoadMyModule
}
```

And calling any `build/serve` will not generate `LoadMyModule` bundle file.  

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.2.2
Node: 8.9.4
@angular-devkit/architect: 0.12.2
@angular-devkit/build-angular: 0.12.2
@angular-devkit/build-optimizer: 0.12.2
@angular-devkit/build-webpack: 0.12.2
@angular-devkit/core: 7.2.2
@angular-devkit/schematics: 7.2.2
@ngtools/webpack: 7.2.2
@schematics/angular: 7.2.2
@schematics/update: 0.12.2
typescript: 3.2.4
webpack: 4.28.4
</code></pre>

**Anything else relevant?**
I've seen a few articles that noted about using strings instead of callback function, but I still don't know why do we need callback then. Will be that supported later? or what...

**Comment by jasonaden** [comment]
You can't have the lazy load module in the same ES module (same file) as your configuration. Also, if you want tools such as Webpack to be able to do code splitting, you need to use the `import()` function. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports
