### ISSUE TITLE
Pass objects via RouteParams

### ISSUE THREAD

**Issue by dsebastien** [angular/angular#2959]
Hello,

Are there plans to support passing objects through RouteParams? RouteParams currently only handles a Map<string,string> and returns strings, but i'd be interested to be able to pass more complex data structures around. 

My use case is the following (not to say that it warrants including the feature -- I can certainly work around this limitation):

I have a PagesService whose responsibility is to fetch blog pages, including metadata & contents) and that service is used by a component that generates a navigation menu containing router links. Currently the generated router links look as follows: [router-link]="['/page-renderer',{pageToRender:page.title}]"

The component that the link points to uses the received router parameter the retrieve & display the page contents, but in order to do so it needs to interact with the PagesService which could be avoided if I was able to rather generate router links like this:

[router-link]="['/page-renderer',{pageToRender:page}]" (i.e., pass the whole Page object)

**Comment by danicomas** [comment]
+1 similar than UI router

**Comment by btford** [comment]
Seems reasonable.

Related to #2777

**Comment by user414** [comment]
Would be interested in this as well. To address this I use dependency injection, encapsulate whatever I need to pass as a service and deal with it that way. However, it means I need to put it in the top level bootstrap and I feel it would be more elegantly handled as a parameter as suggested by OP.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

Covered by new router.
