### ISSUE TITLE
Add the submitted flag to the Forms API

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#2960]
We need to implement something similar to $submitted in Angular 1, so we can do the following:

```
<form #f="form">
  <div *ng-if="f.submitted && !f.valid">Fix the form!</div>
</form>
```

**Comment by antonmoiseev** [comment]
Looks like a good one for a first contribution :wink:. Are you still planning to add this, can I take it?

**Comment by fxck** [comment]
is this in the new forms as well?

**Comment by binarious** [comment]
Yes, it's in there, too.
https://github.com/angular/angular/blob/2.0.0-rc.4/modules/%40angular/forms/src/directives/ng_form.ts#L109
>
>

**Comment by ashwinirajput** [comment]
same thing i Wanted to do but i am using formbuilder there is any way to display error when we click on submit button

**Comment by fxck** [comment]
Yeah, it's on the actual `<form>` directive, as it "doesn't" really make sense on `FormControl`, as they are never really "submitted". But it would still be useful, even if I could trigger the flag manually.
