### ISSUE TITLE
Implement basic html5 validations

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#2961]
We need to support the following validations: required, minlength, maxlength, min, max, pattern.n Currently we only support "required".

**Comment by yanivefraim** [comment]
@vsavkin @mhevery - can I take this one? Thanks!

**Comment by mhevery** [comment]
@yanivefraim it is all yours! We would love your contribution.

**Comment by yanivefraim** [comment]
Cool, I am on it. Thanks!

**Comment by rafacm** [comment]
@yanivefraim: I started to work on this yesterday an saw your comment today. :-) 
See my work so far here: https://github.com/rafacm/angular/commit/e5c4150525a4836d9b67bf4bb92e41bae166446a

Basically, implementation for Validators.minlength and Validators.maxlength and unit tests passing.

IMHO: the next step would be to add directive support, see modules/angular2/src/forms/directives/validators.ts and the unit tests that exercise them: forms/directives_spec.ts, forms/form_builder_spec.ts & forms/integration_spec.ts

**Comment by yanivefraim** [comment]
@rafacm: Thanks you very much... I did similar work - minlength + unit testing (:

**Comment by yanivefraim** [comment]
@mhevery: I will have to change public API by adding the following:
```Javascript```
Validators#minlength()
Validators#maxlength()
Validators#min()
Validators#max()
Validators#pattern()
```
I need you approval, as mentioned inside ```public_api_spec.ts```:
```DO NOT EDIT THIS LIST OF PUBLIC APIS UNLESS YOU GET IT CLEARED BY: mhevery, vsavkin, or tbosch!```

**Comment by mhevery** [comment]
@vsavkin I don't think such names should be attached to `Validators` API, as it is just one of many kinds of validations we could have. Do you have thoughts on how to handle this?

**Comment by yanivefraim** [comment]
@vsavkin @mhevery - any news on this? thanks!

**Comment by rolandjitsu** [comment]
How about `type="<type>"` validation. Or has that already been implemented? Because `type="email"` is definitely not validated.

**Comment by rafacm** [comment]
@rolandjitsu I believe data type validation is handled in #2962

**Comment by rolandjitsu** [comment]
@rafacm thanks. Looking forward to it :+1:

**Comment by gkalpak** [comment]
As of `v2.0.0-beta.8` the implemented validators are:

* [x] Required
* [x] MaxLength
* [x] MinLength
* [x] Pattern

Still missing (?):

* [ ] Max
* [ ] Min

**Comment by ericmartinezr** [comment]
@gkalpak I would like to give it a try with those two missings. But I'm curious about the fact that both min and max can be used in input type date fields, but that field is not supported in FF nor IE (see [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input)). So in case of sending a PR, I think it should be a basic support with fields type number. Am I right?

PS: Also assuming nobody else is already working on this.

**Comment by gkalpak** [comment]
I'm not sure what the plan is for unsupported input types (in fact I'm not sure how date inputs are handled - e.g. in ng1 the value is converted to a Date object).
I guess @vsavkin is more "qualified" to answer :)

**Comment by dragGH102** [comment]
any news on this (min/max)? it's quite crucial also for a project I'm working on

**Comment by user414** [comment]
@dragGH102 Not sure what's the status but since the pattern has been implemented I just use that primarily since with the pattern you can do pretty much anything else.

**Comment by dragGH102** [comment]
@user414 what do you mean by **has been implemented**?

**Comment by user414** [comment]
@dragGH102 as per @gkalpak comment and this commit

https://github.com/angular/angular/commit/38cb526

pattern is now supported in an input like the example below

```
<input [ngControl]="fullName" pattern="[a-zA-Z ]*">
```
so with that you can do pretty much anything you want.

**Comment by dragGH102** [comment]
thanks for the clarification.
yes, I did that actually (but passing via formbuilder validator to keep the
code cleaner)

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

**Comment by user414** [comment]
@mhevery I don't think this has been full implemented yet, and if @vicb assigned @kara 4 days ago perhaps this was closed to aggressively? Unless we are saying that we won't implement the remaining html5 validations?

**Comment by mcalmus** [comment]
Min/max handled by #15813
