### ISSUE TITLE
while creating nested dynamic modules  with compileModuleAndAllComponentsAsync  in aot build showing error

### ISSUE THREAD

**Issue by vinayaktroy** [angular/angular#29620]
ERROR Error: Unexpected value 'LocationAutocompleteModule' imported by the module 'class_1'. Please add a @NgModule annotation.
    at syntaxError (compiler.js:2427)
    at compiler.js:18351
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (compiler.js:18326)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules (compiler.js:25715)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndAllComponents (compiler.js:25703)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler.compileModuleAndAllComponentsAsync (compiler.js:25662)
    at CompilerImpl.push../node_modules/@angular/platform-browser-dynamic/fesm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAndAllComponentsAsync (platform-browser-dynamic.js:153)
    at DynamicCompilerService.push../src/app/services/dynamic-compiler.service.ts.DynamicCompilerService.createComponentFactory (dynamic-compiler.service.ts:31)
    at LandingPageComponent.push../src/app/modules/landing-page/landing-page.component.ts.LandingPageComponent.createDynamicTemplate (landing-page.component.ts:100)

**Comment by mlc-mlapis** [comment]
@vinayaktroy ... it has to = it's expected ... because of `compileModuleAndAllComponentsAsync` supposes Angular compiler to be loaded, which is not in AOT mode in run-time, so there is nothing by default what could compile it.

**Comment by vinayaktroy** [comment]
@mlc-mlapis  for overriding that. I have provided the run time compiler by explicitly passing compiler in module providers, by this its not showing error that I don't have a runtime compiler.

export function createCompiler(compilerFactory: CompilerFactory) {
  return compilerFactory.createCompiler();
} 
    [{provide: COMPILER_OPTIONS, useValue: {}, multi: true},
    {provide: CompilerFactory, useClass: JitCompilerFactory, deps: [COMPILER_OPTIONS]},
    {provide: Compiler, useFactory: createCompiler, deps: [CompilerFactory]},]

**Comment by mlc-mlapis** [comment]
@vinayaktroy ... OK, you didn't mention that. So, the next step ... do you use CLI to build your app? Because of CLI removes metadata by default.

**Comment by vinayaktroy** [comment]
@mac-mlapis ... Yes the project was created by angular CLI.

**Comment by mlc-mlapis** [comment]
@vinayaktroy ... probably that's the reason why you have a problem (because of CLI removes metadata by default). Maybe you can try first to declare your dynamic module as inline code and not as the separate module, so the factor of removed metadata is not in the game, as the following code. That example is concentrated on the fact, that you can pass any HTML template as a string param:

```
private addComponent(template: string) {
	@Component({
		template: template
	})
	class TemplateComponent {}

	@NgModule({
		imports: [
			ReactiveFormsModule,
			BrowserModule
		],
		declarations: [
			TemplateComponent
		]
	})
	class TemplateModule {}

	const mod = this.compiler.compileModuleAndAllComponentsSync(TemplateModule);
	const factory = mod.componentFactories.find(comp =>
		comp.componentType === TemplateComponent
	);
	const component = this.container.createComponent(factory);
}
```

**Comment by vinayaktroy** [comment]
@mlc-mlapis the above code working only in case of plain template ,i have template in which selectors of other components(from different module) is imported the its again showing the error ,in code below you can see the minimal code for error generating code.

import { Compiler, Component, NgModule, OnInit, ViewChild, ViewContainerRef } from '@angular/core';

import { New2Module } from '../../new2/new2.module';

@Component({
  selector: 'app-new',
  template: '<ng-template #vc></ng-template>',
  styleUrls: ['./new.component.css']
})
export class NewComponent implements OnInit {
  @ViewChild('vc', { read: ViewContainerRef })
  vc: ViewContainerRef;

  constructor(private compiler?: Compiler) { }

  ngOnInit() {
    class DynamicComponent extends NewComponent implements OnInit {
      constructor() {
        super();
      }
      ngOnInit() {
      }
    }

    const template = `
    <span> template for new component </span>
    <app-new2></app-new2>`;

    // <app-new2> is selector for component from module New2Module which is needed in this template
    

    const tmpCmp = Component({ template: template })(DynamicComponent);
    const tmpModule = NgModule({ declarations: [tmpCmp], imports:[New2Module] })(class { });

    this.compiler
      .compileModuleAndAllComponentsAsync(tmpModule)
      .then(factories => {
        const f = factories.componentFactories.find(
          _ => _.componentType === DynamicComponent
        );
        this.vc.remove();
        const cmpRef = this.vc.createComponent(f);
      });
  }




}

**Comment by mlc-mlapis** [comment]
@vinayaktroy ... yep, my example supposed that `TemplateModule` is a standalone module.

Your `New2Module` is a module compiled via CLI as a standard module AOT and and it's not necessary to compile it in run-time, right? Or it's necessary to compile it also in run-time by JitCompiler? Also the error message should be a bit different than in the previous case.

**Comment by mlc-mlapis** [comment]
@vinayaktroy ... what is your main idea/reasons to use JitCompiler in AOT app at all?

**Comment by vinayaktroy** [comment]
@mlc-mlapis  yes the idea is something like that if a page consists of 10 different modules then all these modules can be configurable(HTML) from dynamic strings from a database.

**Comment by mlc-mlapis** [comment]
@vinayaktroy ... it looks that you want to use it as the core functionality but normally it's an exception for some specific cases. How is it, that you have so many modules which you plan to configure via HTML dynamic strings?

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-issue-repro2).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
