### ISSUE TITLE
No documentation on running ngc (@angular/compiler-cli)

### ISSUE THREAD

**Issue by pauldraper** [angular/angular#29623]
# 📚 Docs or angular.io bug report

There is zero documentation on how to run the Angular CLI compiler.

* Nothing on https://angular.io, including https://angular.io/guide/aot-compiler
* No help from the executable itself; `ngc -h` and `ngc --help` hang forever.
* No README in @angular/compiler-cli package
* No README at package homepage https://github.com/angular/angular/tree/master/packages/compiler-cli

**Comment by pauldraper** [comment]
I should add: The related but separate project https://github.com/angular/angular-cli invokes the Angular compiler, but under the auspices of entire build system. This is insufficient, because as a side-project for a web MVC framework, it's naturally inflexible and [frequently requires ejecting config](https://github.com/angular/angular-cli/issues?utf8=%E2%9C%93&q=is%3Aissue+eject) as a workaround (and only that if you're lucky enough to want Webpack).

Lacking even cursory documentation, `ngc` cannot be be a good citizen in any reasonably involved build system. And of anyone, I should think Google understands the *immense* value of distinct compilers (gcc, clang, javac, go, tsc) and general-purpose build systems (Make, Jake, Bazel, Buck). 🙂

**Comment by pauldraper** [comment]
> needs eng input

Ping.

**Comment by bogacg** [comment]
`ngc` is basically `tsc` therefore [this documentation](https://www.typescriptlang.org/docs/handbook/compiler-options.html) should be valid mostly. However I agree it would be better to mention what really it is in docs as well.

**Comment by pauldraper** [comment]
> ngc is basically tsc therefore this documentation should be valid mostly. However I agree it would be better to mention what really it is in docs as well.

It clearly isn't though

```
node_modules/.bin/ngc --help
error TS5058: The specified path does not exist: 'tsconfig.json'.
```

```
node_modules/.bin/ngc --version
error TS5058: The specified path does not exist: 'tsconfig.json'.
```

```
node_modules/.bin/ngc --init
error TS5058: The specified path does not exist: 'tsconfig.json'.
```

```
node_modules/.bin/ngc hello.ts
error TS5058: The specified path does not exist: 'tsconfig.json'.
```

Are these bugs? Are these expected?

I have no idea as there isn't even a hello world example of how to use ngc.

**Comment by petermikitsh** [comment]
I've been using `ngc` directly as an alternative to using Angular Schematics / `ng build`. One thing I've found particularly useful is adding the following to my `tsconfig.prod.json`:

```json
{
  "angularCompilerOptions": { 
    "enableResourceInlining": true
  }
}
```

I don't know what other options can be fed into the `angularCompilerOptions` object, but when I build my app, it's as simple as having the following in my `package.json`:

```json
{
  "scripts": {
    "build": "ngc -p tsconfig.prod.json",
  }
}
```

With the proper typescript configuration, this will produce an AOT, ES Module build of an angular app.

**Comment by petermikitsh** [comment]
Does anyone know if it's possible to use https://github.com/cevek/ttypescript with ngc (instead of tsc)?

I'd like to use TypeScript transforms in my angular projects.

**Comment by piotrtomiak** [comment]
For anyone interested the "documentation" of `angularCompilerOptions` is here: https://github.com/angular/angular/blob/e8ae3c5f2efe01acee894f3ea094544689310066/packages/compiler-cli/src/transformers/api.ts#L40

**Comment by pauldraper** [comment]
@petermikitsh I assume you'll have to dig around in the guts of ngc to do that.

For a comparison point, ngc optionally uses a Closure Compiler transformer of sorts: https://github.com/angular/tsickle

**Comment by kapunahelewong** [comment]
Status: docs team, we will need engineering a SME to help inform contents of an ngc doc.

**Comment by aelbore** [comment]
it would be good if theres docs on how to use programatically, im planning to create for rollup plugin for ngc

**Comment by aelbore** [comment]
by the way i created a rollup plugin for angular with ivy, it uses ngc and buildOptimizer
https://github.com/aelbore/rollup-plugin-ngc

**Comment by pauldraper** [comment]
Ping.

(Also, preventing closure by `angular-automatic-lock-bot`.)

**Comment by gkalpak** [comment]
FWIW, the bot does not close open issues. As its name suggests it just _locks_ already closed issues.

**Comment by ajitsinghkaler** [comment]
You can use my article https://indepth.dev/angular-compatability-compiler/ if it helps you

**Comment by pauldraper** [comment]
@ajitsinghkaler thank you but that is ngcc, not ngc.

**Comment by pauldraper** [comment]
Thank you @aelbore .

Your project is more helpful on understanding the Angular compiler API than all documentation the Angular team has ever written.
