### ISSUE TITLE
RouterLinkBackHref directive

### ISSUE THREAD

**Issue by abdulkareemnalband** [angular/angular#29631]
# 🚀 feature request

### Relevant Package
This feature request is for `@angular/router`

### Description
A new directive for `anchor` tag which navigates back to previous route.
Directive should allow opening previous route in new tab on `ctrl+click`

Added bonus: developers just need to add this directive to enable back without any code changes in component

### Describe the solution you'd like

1. The directive must set correct `href` to previous route
2. Should **not** push previous route into *history* API, but should pop last route

### Describe alternatives you've considered
`Location` from `@angular/common` provides `back` method but it is not that versatile

**Comment by Airblader** [comment]
Note that if a user goes directly to a page then there is no "previous route". Such a directive would probably have to allow specifying a default to be useful.

Also I might be wrong but AFAIK the history API simply doesn't have a "previous URL" property. It only has `back`, which doesn't give an URL.
