### ISSUE TITLE
Angular Build

### ISSUE THREAD

**Issue by MANRIQUEZ23** [angular/angular#29637]
Hi  everyone, I' running my web angular app like:

localhost:47/TA_APPLICATION , but when I make the build  "ng build" and upload to Apache HTTP it goes to:
http://localhost/TA_APPLICATION/TA_APPLICATION/TA_APPLICATION

Does anyone knows how to avoid this redirection 2 levels up ?

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
