### ISSUE TITLE
New Getting Started: recommend defining product data in the product list component directly

### ISSUE THREAD

**Issue by DingWeizhe** [angular/angular#29649]
# 📚 Docs or angular.io bug report

### Description

I think the following code is easy to cause confusion.

https://github.com/angular/angular/blob/d4c4a8943168eae9f7c70f25c42d7b5a6b5ccf8f/aio/content/examples/getting-started-v0/src/app/product-list/product-list.component.ts#L11

In the same variable range, the same variable name, but the first one is the attribute of class, and the last one is the variable that is imported.

I think to write directly to the contents of variables here, although not clean but easier to understand.

like this: https://stackblitz.com/edit/angular-rbgsj9?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.ts

### What's the affected URL?**
https://next.angular.io/getting-started#output

**Comment by brandonroberts** [comment]
@DingWeizhe it was setup that way at one point, but we need to share the `products` data between the product list component and the product details component in the routing section. I would suggest renaming it to `PRODUCT_DATA` so its less ambiguous.

**Comment by brandonroberts** [comment]
Closing as we won't change this for now.
