### ISSUE TITLE
Custom validator for template driven form with additional/ "external" data to incorporate.

### ISSUE THREAD

**Issue by andreElrico** [angular/angular#29653]
I have searched the web and github for this. All examples I've found on the web for customValiditors they seem to overload EXISTING validators that are based on existing attributes of the Input element.

# 🚀 feature request

I have this [STACKOVERFLOW](https://stackoverflow.com/questions/55420411/advanced-custom-validator-for-template-driven-form-with-dynamic-input) Question. That explains what im aiming for.

You can see, that my validator should incorporate arbitrary data info (string1, string2) into the validation pipeline.

### Description

Please have a look into the Stackblitz in the SO-post.

### Describe the solution you'd like
I somehow need to get access to data from scoped in my component instance inside my general validator function.

### Describe alternatives you've considered
I tried hacking a solution under the "horizontal line" at the end of SO-post. It gets me close but the "notYetSolution" holds many problems.

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by andreElrico** [comment]
I was about to close it. I didnt know if its possible at all.
