### ISSUE TITLE
Angular child component passes undefined

### ISSUE THREAD

**Issue by bwor** [angular/angular#29650]
I asynchronously request data from the parent, and the child receives an undefined error from the array at @input。How to solve this problem?

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
