### ISSUE TITLE
RegExp constructor in NgModule annotation config not compiled to output for --prod

### ISSUE THREAD

**Issue by mtraynham** [angular/angular#29668]
# 🐞 bug report

### Is this a regression?

 
Yes, I think so.  The documentation of the [Angularlitics2](https://github.com/angulartics/angulartics2#remove-ids-from-url-paths) package shows that this works, and assuming the Angular documentation on [supported expressions in annotations](https://angular.io/guide/aot-compiler#expression-syntax) is still correct, it should work.

### Description
I'm using the [Angularlitics2](https://github.com/angulartics/angulartics2) package to track page views.  There is optional config to provide a RegExp that [removes ID's from tracked URL paths](https://github.com/angulartics/angulartics2#remove-ids-from-url-paths).  This seems to work fine for JIT (non-prod) builds.  But when adding the `--prod` flag, it seems that RegExp is stripped from the compiled build.

This is kind of a derivative of https://github.com/angular/angular-cli/issues/13702 which also doesn't work, but as pointed out in the bug, probably shouldn't work.

Originally reported here https://github.com/angular/angular-cli/issues/14055, but told to report it here.

## 🔬 Minimal Reproduction
https://github.com/mtraynham/angular-module-regex-constructor

1. `ng new angular-module-regex-constructor`  (routing Y; CSS)
2. Add Angularlitics, e.g. this [commit](https://github.com/mtraynham/angular-module-regex-constructor/commit/39d4501b5d811d24aee60ab7ec1cbda4ab92b651).
3. Compile with `ng build --prod`.
4. Search for `idsRegExp` in the compiled output and find no instances of the configured `idsRegExp: new RegExp('^[a-z]\\d+$')`.

I went ahead and ran `ng build --vendor-chunk`, `ng build --prod --vendor-chunk`, `ng build --prod --aot --vendor-chunk` and committed them to that same repository (after beautifying the main files).  It works in the standard build case, but not when using `--prod` as identified by the following lines:

JIT - https://github.com/mtraynham/angular-module-regex-constructor/blob/master/dist/angular-module-regex-constructor/main.js#L149-L153
```js
                angulartics2__WEBPACK_IMPORTED_MODULE_5__["Angulartics2Module"].forRoot({
                    pageTracking: {
                        clearIds: true,
                        idsRegExp: new RegExp('^[a-z]\\d+$') /* Workaround: No NgModule metadata found for 'AppModule' */
                    }
                })
```

Prod - https://github.com/mtraynham/angular-module-regex-constructor/blob/master/dist/angular-module-regex-constructor-prod/main.5ede6a1bdd2f105d28e3.js#L54
```js
b.qb(256, M.a, {settings: {pageTracking: {clearIds: !0}}}, [])
```

Prod AOT - https://github.com/mtraynham/angular-module-regex-constructor/blob/master/dist/angular-module-regex-constructor-prod-aot/main.5ede6a1bdd2f105d28e3.js#L54
```js
b.qb(256, M.a, {settings: {pageTracking: {clearIds: !0}}}, [])
```

## 🔥 Exception or Error
No error thrown.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.7
Node: 11.13.0
OS: darwin x64
Angular: 7.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.7
@angular-devkit/build-angular     0.13.7
@angular-devkit/build-optimizer   0.13.7
@angular-devkit/build-webpack     0.13.7
@angular-devkit/core              7.3.7
@angular-devkit/schematics        7.3.7
@angular/cli                      7.3.7
@ngtools/webpack                  7.3.7
@schematics/angular               7.3.7
@schematics/update                0.13.7
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

**Comment by alxhub** [comment]
I believe this was broken between Angular 5 and 6, as part of some changes with how metadata was validated (similarly to #26417). For the same reasons, this bug can't really be fixed in Angular today. The good news is that Angular Ivy should make this a non-issue.
