### ISSUE TITLE
Component CSS loads before angular material CSS

### ISSUE THREAD

**Issue by qmarquez** [angular/angular#29677]
# 🐞 bug report

### Description

Using material, icons for example, declared CSS rule don't override the material CSS

Result
![image](https://user-images.githubusercontent.com/18141238/55448233-5f621280-559d-11e9-86af-c9f7acdbfb81.png)

Component CSS
![image](https://user-images.githubusercontent.com/18141238/55448243-65f08a00-559d-11e9-8894-6fa804d8bb28.png)

To fix it i need to declare the CSS rules as `!important`
![image](https://user-images.githubusercontent.com/18141238/55448276-8fa9b100-559d-11e9-8818-8e5f671a4c64.png)
![image](https://user-images.githubusercontent.com/18141238/55448289-9d5f3680-559d-11e9-8ec9-7aab8bbe6d9a.png)

when a CSS rule it's declared on the component CSS it wont must be priority over anothers CSS rules?

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.7
Node: 10.13.0
OS: win32 x64
Angular: 7.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.7
@angular-devkit/build-angular     0.13.7
@angular-devkit/build-optimizer   0.13.7
@angular-devkit/build-webpack     0.13.7
@angular-devkit/core              7.3.7
@angular-devkit/schematics        7.3.7
@angular/cdk                      7.3.6
@angular/cli                      7.3.7
@angular/material                 7.3.6
@angular/pwa                      0.13.7
@ngtools/webpack                  7.3.7
@schematics/angular               7.3.7
@schematics/update                0.13.7
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Comment by pkozlowski-opensource** [comment]
This belongs to https://github.com/angular/material2
