### ISSUE TITLE
[Ivy] Component composition (inheritance) breaks rendering

### ISSUE THREAD

**Issue by MakesNine** [angular/angular#29687]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/....    Seems to be an issue considered to be crosscutting?

### Is this a regression?
Yes, the previous version in which this bug was not present was: Angular 7.3.7;  It also works with Angular 8.0.0-beta.10 when not using Ivy

According to this [source for Ivy status](https://github.com/angular/angular/blob/master/packages/core/src/render3/STATUS.md#crosscutting), extending components should now be supported with Ivy if I'm not mistaken.

### Description
When a component extends another component, the derived component and the components included in its template are not rendered on the screen.  I can see the the component tag by inspecting the DOM with devtools, but its actual content is not displayed.

I can also verify the constructor of the base class is called as expected.  However, it is not possible to get a reference to a child component inserted in the template of the derived component using @ViewChild (neither from the base component nor from the derived component).

## 🔬 Minimal Reproduction
I have created this repo with a minimal reproduction of the problem: [Component inheritance with Ivy](https://github.com/MakesNine/TestIvy8Beta10)

I have also created another repo, with the same code but created with Angular 8.0.0-beta.10 without Ivy enabled to show that it works in this case: [Component inheritance without Ivy](https://github.com/MakesNine/TestNoIvy)

## 🔥 Exception or Error
Content is not rendered and @ViewChild doesn't work.

## 🌍  Your Environment

Angular CLI: 8.0.0-beta.10
Node: 10.15.0
OS: win32 x64
Angular: 8.0.0-beta.10
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-beta.10
@angular-devkit/build-angular     0.800.0-beta.10
@angular-devkit/build-optimizer   0.800.0-beta.10
@angular-devkit/build-webpack     0.800.0-beta.10
@angular-devkit/core              8.0.0-beta.10
@angular-devkit/schematics        8.0.0-beta.10
@ngtools/webpack                  8.0.0-beta.10
@schematics/angular               8.0.0-beta.10
@schematics/update                0.800.0-beta.10
rxjs                              6.4.0
typescript                        3.3.4000
webpack                           4.29.6

**Anything else relevant?**
Tested with Chrome

**Comment by MakesNine** [comment]
I have further investigated this problem and I'm now able to define it more precisely.   I have a DemoComponent that extends a BaseDemoComponent.  The DemoComponent has a child component named DemoChildComponent (inserted in its template).  With Ivy only, the DemoChildComponent tag can be seen by inspecting the DOM, but it doesn't get rendered.  In fact, its constructor is never called so my understanding is that the component is not created.

The DemoComponent and the DemoChildComponent are declared in the DemoModule that is lazy loaded in the app.routing.module.ts file using the new syntax for Ivy as described in the documentation at next.angular.io.

I have discovered that if I import the DemoModule in the AppModule and insert it in the import array, the problem goes away.  Since the DemoModule is lazy loaded, we never had to import it in previous versions of Angular and it is still the case with Angular 8 if we don't use Ivy.  The documentation for lazy loading module at next.angular.io clearly mentions that lazy loaded modules must not be imported in the AppModule, but in this case this is what "fixes" my problem.  My guess is that this module is not really lazy loaded if I import it in the AppModule?

I have updated my repo by adding the import of the DemoModule in the AppModule to demonstrate that the fix works.  If you simply remove the DemoModule from the import array in the AppModule, the problem with derived classes will come back as described above.

**Comment by MakesNine** [comment]
I have update the test project to Angular 8.0.0-rc.2 and Angular-cli 8.0.0-rc.2.  The problem has gone away as the child component in the lazy loaded module is rendered without having to import the lazy loaded module in the root AppModule.
Thanks!

**Comment by zbarbuto** [comment]
FTR I just enabled ivy in a project using `@angular/cli@8.2.0` and am also experiencing this issue.

```ts
class BaseComponent {
  @Input title: string;
}

@Component({
  selector: 'better-base'
})
class BetterBaseComponent extends BaseComponent { }
```

```html
<better-base [title]="foo"></better-base>
```

Property 'type' does not exist on type 'HTMLElement'.
