### ISSUE TITLE
Implementation of migration "migration-v8-template-local-variables" is missing

### ISSUE THREAD

**Issue by log2-hwan** [angular/angular#29696]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?
No

### Description
@angular/core package's migrations.json file has "migration-v8-template-local-variables" migration but its implementation files are missing.

## 🔬 Minimal Reproduction
If you run `ng update @angular/core --next` in angular 7 project, it is failed with error message.

## 🔥 Exception or Error
<pre><code>
Cannot find module '.../node_modules/@angular/core/schematics/migrations/template-var-assignment/index'
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect          0.13.7
@angular-devkit/build-angular      0.13.7
@angular-devkit/build-ng-packagr   0.13.7
@angular-devkit/build-optimizer    0.13.7
@angular-devkit/build-webpack      0.13.7
@angular-devkit/core               7.3.7
@angular-devkit/schematics         7.3.7
@angular/cli                       7.3.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.7
@schematics/angular                7.3.7
@schematics/update                 0.13.7
ng-packagr                         5.0.1
rxjs                               6.4.0
typescript                         3.2.4
webpack                            4.29.0
</code></pre>

**Anything else relevant?**

**Comment by devversion** [comment]
Will be fixed by #29705

**Comment by devversion** [comment]
Fixed with https://github.com/angular/angular/commit/96b76dc3f13e250b7cc425c9c92ead2bdc8be236
