### ISSUE TITLE
Move pubspec_cleaner.js to build.dart

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#2969]
At present, we build dart artifacts in the `dist` dir during the build, with package overrides for tests. We then leave the dist folder in that state. Later, when we publish to pub, we run `pubspec_cleaner.js` to get the real files we upload.
Now that we publish dart snapshots for every green travis build, it would be better to do this cleaner during the build. We can run it after tests are finished, so we don't have to do anything fancy to keep them working.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
