### ISSUE TITLE
ngModel cannot bind in angular6

### ISSUE THREAD

**Issue by BhaveshPrince** [angular/angular#29701]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
Hii 
i had already  added formModule and reactiveformmodule but i have been getting error below.
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'input'. ("Name</label>
              <div class="col-sm-6">
                 <input type="text" id="status" [ERROR ->][(ngModel)]="roomType123.status"  name="status" class="form-control">
       
          
"): ng:///frontOfficeModule/roomTypeComponent.html@22:48

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by mlc-mlapis** [comment]
@BhaveshPrince ... your information is not complete. Where did you add it? Create a simple Stackblitz reproduction to show what you mean on https:/stackblitz.com.

**Comment by maximelafarie** [comment]
@BhaveshPrince can you please edit your issue, format the code and remove those icons from the message?

**Comment by Airblader** [comment]
Those icons are there because the template said to not ask support questions here, but on StackOverflow.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
