### ISSUE TITLE
Angular Elements should be able to emit/dispatch an event while initialization

### ISSUE THREAD

**Issue by Ahmtk** [angular/angular#29704]
# 🐞 bug report

### Affected Package
The issue is caused by package `@angular/elements`

### Description

We encountered a bug in Angular Elements that the element is not able to emit an event while initializing the component. We tried to emit the event using one of the Angular Component lifecycle hooks (`ngOnInit`, `ngAfterContentInit`, `ngAfterContentChecked`, `ngAfterViewInit`). Unfortunately, they were not emitted.

## 🔬 Minimal Reproduction
Here is a simple component example:

```
@Component({
  selector: 'test-component',
  templateUrl: './test-component.component.html',
  styleUrls: ['./test-component.component.scss']
})
export class TestComponent implements AfterViewInit {
  
	@Output() public connected: EventEmitter<any> = new EventEmitter<any>();

  ngAfterViewInit() {
    this.connected.emit();
  }
}

```

Component Usage
```
const comp = document.createElement('test-component');
comp.addEventListener('connected', function(eventParams) {
  console.log('initialized!!!!!'); // will not be called
});
document.body.append(comp);

```
Live example is available also on stackblitz.com :
https://stackblitz.com/edit/angular-issue-repro2-hssxfc

## 🌍  Your Environment

<pre><code>
Angular Version: 6.x & 7.x
</code></pre>

## Anything else relevant?

I checked the code of the `createCustomElement` function and found out that the listening to events and dispatching them is achieved after the component is connected! In other words, the statement here:
https://github.com/angular/angular/blob/699ecac2c28006df807e240e226e7dbaf9012d3d/packages/elements/src/create-custom-element.ts#L167 
is called after ` this.ngElementStrategy.connect(this); ` which means that the events will not dispatched as custom events till the ngComponent is initialized.

Moreover, I think it would be great to get a callback/hook when the Web Component is connected to the DOM. Such as `componentConnected()` hook.

**Comment by trotyl** [comment]
Relates to https://github.com/angular/angular/issues/25521

**Comment by dimarafonseca** [comment]
I'm having something similar, but it only happens if I use **Angular Elements** in **Angular Project**. I noticed in my ngAfterViewInit event the _@inputs()_ properties are always undefined. However, if I use these **angular custom elements** in a **regular HTML page** it works fine and the _@inputs()_ in my ngAfterViewInit event have value.
https://github.com/dimarafonseca/custom-angular-example - example with two projects: A custom elements and the other one using this element.
Thanks

**Comment by trotyl** [comment]
> I noticed in my `ngAfterViewInit` event the `@Inputs()` properties are always `undefined`.

@dimarafonseca That should be https://github.com/angular/angular/issues/27771, doesn't quite relates to this one.

**Comment by robwormald** [comment]
We can improve this slightly, but as described, this isn't really possible - consider a vanilla Custom Element:

```ts

class MyElement extends HTMLElement {
  constructor(){
    super();
    this.dispatchEvent(new CustomEvent('test-event'))
  }
}
customElements.define('my-element', MyElement);

const el = document.createElement('my-element');
//constructor fires synchronously, here
//event handler is attached too late.
el.addEventListener('test-event', e => {
  console.log('event fired'
});
```
You can of course extend the class returned from `createCustomElement` and implement that behavior (perhaps after a setTimeout):

```ts
class MyElement extends createCustomElement(Comp, {injector}){
  constructor(){
    super();
    setTimeout(() => this.dispatchEvent(new CustomEvent('test-event')));
  }
}
```
