### ISSUE TITLE
next.angular.io/guide/ivy doesn't mention ivy-ngcc

### ISSUE THREAD

**Issue by mrnateriver** [angular/angular#29719]
# 📚 Docs or angular.io bug report

### Description

https://next.angular.io/guide/ivy comes up if you Google how to enable/disable Ivy in existing project. It states that changing `angularCompilerOptions` is sufficient for that.

However, it doesn't mention the fact that when Angular CLI creates a project with `--experimental-ivy` it adds `postinstall` hook in `package.json` that runs `ivy-ngcc`. It then compiles all dependencies (as far as I understand) for the new compiler. And when you think you've disabled Ivy you are still in fact using it for external libraries, like Angular Material, which seems to be widely incompatible with Ivy.

### What's the affected URL?**
https://next.angular.io/guide/ivy

### Expected vs Actual Behavior**
Expected: tell about `ivy-ngcc`, what it does and how to fully enable/get rid of Ivy in a project.
Actual: states that changing configuration is enough.

**Comment by alan-agius4** [comment]
Hi @mrnateriver, that is because the post install hook is no longer required with the latest changes.

NGCC is now integreated as part of the build pipeline.

Kindly see: https://github.com/angular/angular-cli/pull/13968

**Comment by mrnateriver** [comment]
Well, that PR is in `master`, whereas Ivy can be enabled in current stable release. IMHO docs should've been updated with the release with that PR. But as of now, it causes confusion for newcomers (like me).

But anyway, thanks for the heads-up!

**Comment by alan-agius4** [comment]
The guide is for version 8. Hence the next in the sub domain of the documention.
