### ISSUE TITLE
fix(bazel): structure change in template files for correctly start with Bazel

### ISSUE THREAD

**Issue by DeveloperFromUkraine** [angular/angular#29726]
# 🐞 bug report

### Affected Package

`@angular/bazel@8.0.0-beta.11`

### Is this a regression?

No

### Description

I start the server via the `ng serve` command.
All dependencies that are in the rule `ts_devserver` in `scripts` attribute in development console failed with `Error: 404`. And does not start the development-server correctly.

## 🌍  Your Environment
```
"dependencies": {
    "@angular/animations": "8.0.0-beta.11",
    "@angular/bazel": "8.0.0-beta.11",
    "@angular/common": "8.0.0-beta.11",
    "@angular/compiler": "8.0.0-beta.11",
    "@angular/core": "8.0.0-beta.11",
    "@angular/forms": "8.0.0-beta.11",
    "@angular/platform-browser": "8.0.0-beta.11",
    "@angular/platform-browser-dynamic": "8.0.0-beta.11",
    "@angular/router": "8.0.0-beta.11",
    "core-js": "^2.5.4",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.800.0-beta.11",
    "@angular/cli": "8.0.0-beta.10",
    "@angular/compiler-cli": "8.0.0-beta.11",
    "@angular/language-service": "8.0.0-beta.11",
    "@bazel/bazel": "^0.24.0",
    "@bazel/ibazel": "^0.9.0",
    "@bazel/karma": "^0.27.9",
    "@bazel/typescript": "^0.27.9",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "3.3.3333"
  }
```

**Comment by alexeagle** [comment]
hey @DeveloperFromUkraine there's not enough info here for me to reproduce.

**Comment by kyliau** [comment]
@DeveloperFromUkraine 
Looking at the changes you made in the BUILD files, I think you're using an older version of rules_nodejs that does not support automatically pulling in scripts from node modules.
It also looks like you've experimented with `--leaveBazelFilesOnDisk` ? 
In that case, you'll have to manage the dependencies yourself in ejected mode.
Please make sure you upgrade `rules_nodejs` in WORKSPACE, along with `@bazel/*` packages in `package.json` to the latest version (`0.27.12` is the latest as of this writing).

Alternatively, you can delete the existing WORKSPACE and BUILD files from your project, upgrade to latest `@angular/bazel`, and re-build your project using the latest Bazel Builder.

**Comment by DeveloperFromUkraine** [comment]
I've use 0.27.8 - and made this fixes in that time. Then switch to 0.27.10 and continue.

**Comment by kyliau** [comment]
That makes sense, `0.27.8` does not support the Bazel files you see in `@angular/bazel`.
I'd suggest trying the latest version of rules_nodejs - `0.27.12`
