### ISSUE TITLE
CanActivate guard doesn't work with promises or observables

### ISSUE THREAD

**Issue by lcortess** [angular/angular#29734]
# 🐞 bug report

### Affected Package
CanActivate from "@angular/router"

### Description

Promises and Observables are not working when inside is an asynchronous proccess and the returned value is a UrlTree object, the page stays blank and there are no redirections

## 🔬 Minimal Reproduction
This piece of code works well, even the redirection to the login page

```
public canActivate(
    route: ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ): Promise<boolean | UrlTree> {
    return new Promise<boolean | UrlTree>((resolve, reject) => {
      const isLoggedIn = true;

      if (isLoggedIn) {
        resolve(true);
      } else {
        resolve(this.router.parseUrl("/login"));
      }
    });
  }

```

But if you add an asynchronous proccess inside the promise the redirection doesn't work, a quick test could be use a `setTimeout` function instead of call our asynchronous method:

```
public canActivate(
    route: ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ): Promise<boolean | UrlTree> {
    return new Promise<boolean | UrlTree>((resolve, reject) => {
      setTimeout(() => {
        console.log("next");
        resolve(this.router.parseUrl("/login"));
      }, 100);
    });
  }

```

The same behavior happen with observables

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.7
Node: 8.9.3
OS: linux x64
Angular: 7.2.11
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.7
@angular-devkit/build-angular     0.13.7
@angular-devkit/build-optimizer   0.13.7
@angular-devkit/build-webpack     0.13.7
@angular-devkit/core              7.3.7
@angular-devkit/schematics        7.3.7
@angular/animations               7.2.12
@angular/cdk                      7.3.6
@angular/cli                      7.3.7
@angular/material                 7.3.6
@ngtools/webpack                  7.3.7
@schematics/angular               7.3.7
@schematics/update                0.13.7
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Comment by Airblader** [comment]
Could you provide a Plunker / StackBlitz reproducing this?

**Comment by lcortess** [comment]
Sorry for this but seems like is other guard that somehow is blocking the redirection, I've removed the second guard and works fine
