### ISSUE TITLE
No way to set global options on HttpClient ( { observe: 'response' } )

### ISSUE THREAD

**Issue by mswilson4040** [angular/angular#29732]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

HttpClient / HttpInterceptor

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

There doesn't seem to be a way to set global options for an HttpClient. The only close option I see is configuring an HttpInterceptor and set the options within each request.

`const req = _request.clone(<Update Object>);`

It doesn't look like the update object is aware of the HttpClient options such as **{ observe: 'response }**

```
clone(update: {
        headers?: HttpHeaders;
        reportProgress?: boolean;
        params?: HttpParams;
        responseType?: 'arraybuffer' | 'blob' | 'json' | 'text';
        withCredentials?: boolean;
        body?: T | null;
        method?: string;
        url?: string;
        setHeaders?: {
            [name: string]: string | string[];
        };
        setParams?: {
            [param: string]: string;
        };
    }): HttpRequest<T>;
```

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

I'm not clear if there is some other way to handle this as my use case is to simply get the Http Response Code from the response. Of course, I can configure the **{ observe: 'response' }** on every call, but that is error prone (someone would eventually not add it).

**Comment by Airblader** [comment]
It sounds a bit strange to me that in your entire application there is not a single HTTP request where you're interested in anything other than the result code. If this is really the case, it's at the very least extremely exotic.

**Comment by mswilson4040** [comment]
@Airblader I'm working on converting an api to use proper http response types rather than a custom wrapper that is out of date. So yes, currently, there's a big chunk of the application that doesn't care about the return. I'm trying to fix that and am exploring ideas right now. Given the HttpInterceptor, I already built in error handling for specific error codes and was wanting to make it so that if a request didn't return anything, I could at least interrogate the response to see if it was 200 or not.

I know the next question is that if I'm already handling error codes in the interceptor, if the response completes, it's almost certain to be 2xx. I'm just exploring options and I didn't know about the { observe: 'response' } option. Looks like it's helpful, but I was unable to just flip it on for everything. Seems like it should be surfaced in the type so it can be added if desired.

**Comment by JoostK** [comment]
One reason I could think of for not being able to set the response format globally is that it would break libraries that also use `HttpClient` themselves. Furthermore, API consumers would not be able to be type-checked properly, this is also why an interceptor can't change the response format right now.

**Comment by mswilson4040** [comment]
@JoostK That's certainly understandable; and a very good point. My only argument is that in my use case, I am doing it consciously. As I was researching my options today, I think that enabling the option at the global level just makes for more work downstream. Having to interrogate every response to get what you're after seems like a bigger problem. 99% of the time you're just after the json response anyways. I don't have any other use case of right now that would involve some sort of way to set options to every single http request, so this can probably be closed.

**Comment by jiagouview** [comment]
newReq = req.clone({
        url: req.url,
        setHeaders: {'USERID': this.workNo, 'TOKEN': this.token}
      });
setHeaders，It doesn't work?
