### ISSUE TITLE
FormControlDirective and FormControlName contain incorrect or outdated deprecation statement

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#29743]
# 📚 Docs or angular.io bug report

### Description
 A clear and concise description of the problem...
Doc for `FormControlDirective` and `FormControlName` contains incorrect or outdated deprecation statements: 
* Deprecation statement says support for using reactive form directives will be removed in v7. Was it removed? If so, this doc should simply say that reactive form directives are no longer supported. 
* Deprecation policy says this: "We support each deprecated API for at least two subsequent major releases, which means at least 12 months after deprecation." That means when deprecation is announced in v6, the earliest the feature can be removed/unsupported is v8. If this feature is not already removed/unsupported, will it be in v8? 
https://angular.io/guide/releases#deprecation-practices

## 🔬 Minimal Reproduction

`FormControlName` API reference
https://angular.io/api/forms/FormControlName
"Support for using the ngModel input property and ngModelChange event with reactive form directives has been deprecated in Angular v6 and will be removed in Angular v7."
"To update your code before v7, you'll want to decide whether to stick with reactive form directives (and get/set values using reactive forms patterns) or switch over to template-driven directives."

FormControlDirective API ref page
https://angular.io/api/forms/FormControlDirective
"Support for using the ngModel input property and ngModelChange event with reactive form directives has been deprecated in Angular v6 and will be removed in Angular v7."
"To update your code before v7, you'll want to decide whether to stick with reactive form directives (and get/set values using reactive forms patterns) or switch over to template-driven directives."

### What's the affected URL?**
 https://angular.io/...
see above

### Reproduction Steps**

see above

### Expected vs Actual Behavior**

We need to confirm with @IgorMinar and then update docs to  accurately describe the current state, for v7 and  updated again if the current state will be different for v8. 

If we need to maintain the instructions for migrating code, I recommend positioning something like this: "Versions prior to v7/v8 [whatever version removes support] allowed the use of... That construct is no longer supported. To migrate your code..."

## 📷Screenshot

n/a

## 🔥 Exception or Error
<pre><code>

n/a
</code></pre>

### Browser info

n/a

**Comment by CreepyGnome** [comment]
FYI... it wasn't removed from Angular v7 as it is still working for me with latest v7. I currently only use reactive form validation with ngModel binding. I am not sold on reactive forms as there is no real binding for it and requires a lot more setup to use and you have to code the setting of the model and the setting of the form from the model.  While ngModel works "magically" for binding 1way and 2way to a backing model.  

It seems like it should just say it will be removed from a future version or state it's allowed if only used with reactive form validation, or provide a true binding mechanism in reactive forms to replace what ngModel does.  Regardless current docs are confusing on this matter.

**Comment by rockument69** [comment]
@kapunahelewong : I think this can be closed. In both docs, it now says " is scheduled for removal in a future version of Angular."

**Comment by AndrewKushnir** [comment]
Closing this issue based on the comment above.
