### ISSUE TITLE
Form successives submits trigger autocomplete cache just once, the first 

### ISSUE THREAD

**Issue by qmarquez** [angular/angular#29745]
# 🐞 bug report

### Description
On a template-driven form, before a submit, the navigator catch the values to keep it for autocomplete on nexts loads, the successives submits before the first, the values used for autocomplete don't be catche anymore except i refresh the page

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-gb5stt

Submit any name, check that name it's for autocomplete, then submit another name check that name it's not for autocomplete.
Reloads the page, submit the second name again and check that both names are for autocomplete.
Third, fourth and more, without refresh the page, are not loaded for autocomplete.
[Video_1554561252.zip](https://github.com/angular/angular/files/3050740/Video_1554561252.zip)

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.7
Node: 10.13.0
OS: win32 x64
Angular: 7.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.7
@angular-devkit/build-angular     0.13.7
@angular-devkit/build-optimizer   0.13.7
@angular-devkit/build-webpack     0.13.7
@angular-devkit/core              7.3.7
@angular-devkit/schematics        7.3.7
@angular/cdk                      7.3.6
@angular/cli                      7.3.7
@angular/material                 7.3.6
@angular/pwa                      0.13.7
@ngtools/webpack                  7.3.7
@schematics/angular               7.3.7
@schematics/update                0.13.7
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**
The expected behavior will coming that on any further submit the value of inputs can be catched by the navigator autocomplete engine.

**Comment by kara** [comment]
@qmarquez If I understand this correctly, the autocomplete functionality of the browser isn't showing up when you expect it to? If so, that's something controlled natively and not directly handled by Angular. As such, there's not much we can do on our end, so I'm closing the issue here.
