### ISSUE TITLE
ViewEncapsulation.ShadowDom is creating shadow dom but not encapsulating component from external css

### ISSUE THREAD

**Issue by goodmite** [angular/angular#29753]
# 🐞 bug report

I have a simplest possible angular component. The only difference is that I have `encapsulation: ViewEncapsulation.ShadowDom` enabled. Doing this is creating shadow dom as expected. But its not protecting component from external styling.

For example I have following styles in style.css

```
*{
  font-size: 30px;
  color:red;
}
```
This style is being applied to `div`s inside the component.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-1phjqd?file=src%2Fstyles.css

# other info:
Angular 7

**Comment by dawidgarus** [comment]
That's how Shadow DOM works:
http://jsfiddle.net/4o2jmfrq/2/
You can't directly style component's elements from outside, but properties will be inherited as usual.
It has nothing to do with Angular.

**Comment by goodmite** [comment]
Thanks for quick reply @dawidgarus . I will close this.
