### ISSUE TITLE
output from gulp build.material.dart is missing from dist/ folder on travis

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#2976]
The resulting CSS files need to be included in the snapshots we now publish to cloud storage.

**Comment by alexeagle** [comment]
note, it should probably be removed from https://github.com/angular/angular/blob/master/scripts/publish/pub_publish.sh#L20 at the same time

**Comment by rkirov** [comment]
Can't `build.dart.material` be rolled into as the last step of `build.dart`?

**Comment by jelbourn** [comment]
Yeah, I'll do that today. I had previously wanted to avoid that to prevent
coupling angular2 and angular_material, but it's not a big deal.

**Comment by naomiblack** [comment]
@jelbourn did this get fixed?

**Comment by jelbourn** [comment]
Not yet; I wrote the change and then forgot to send a PR. I'll send it out today.
