### ISSUE TITLE
Support Typescript 3.4

### ISSUE THREAD

**Issue by FDIM** [angular/angular#29766]
# 🚀 feature request

### Relevant Package

 
This feature request is for @angular/cli

### Description

[Incremental build](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html) looks promising! I guess this is too late for v8? 

#### Related
https://github.com/angular/angular-cli/issues/13941

**Comment by Airblader** [comment]
See #29372

**Comment by gkalpak** [comment]
Closing, since there is already a PR in progress.
