### ISSUE TITLE
How to declare pipe at component level?

### ISSUE THREAD

**Issue by kwiniarski97** [angular/angular#29763]
I got a pipe that is used only in one component. So I wanted to declare pipe at this component level. Something like this: 

```
@Component({
  selector: 'app-my-comp',
  templateUrl: './my-comp.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  declarations: [MyCustomPipe]
})
export class MyComponent {

}
```
However the `Component` annotation doesn't support `declarations`.

Is there anyway to achieve this? I know I can declare pipe in the module but then other components will be "notified" about it and it will break encapsulation.

**Comment by mlc-mlapis** [comment]
@kwiniarski97 ... not at the actual state of API.

**Comment by kwiniarski97** [comment]
@mlc-mlapis Is this on road map? It is pretty inconsistent as you can provide services at component level but why can't you pipes?

**Comment by mlc-mlapis** [comment]
@kwiniarski97 ... it's discussed ... to find a consistent and the best way. Not sure if the final decision was done already.

**Comment by Airblader** [comment]
> It is pretty inconsistent as you can provide services at component level but why can't you pipes?

Declaring a component, directive or pipe is something completely different from providing a service, so I'm not sure why this would be "inconsistent".

Is there any reason why you absolutely need to scope the pipe to this component? Just don't use it elsewhere. If you really want to bundle it closely together, wrap them both into a separate module and don't export the pipe.

**Comment by alxhub** [comment]
I'm a fairly big fan of the one-module-per-component pattern in Angular - having a dedicated module for each component. In this case, adding the pipe to the component is easy.

Otherwise, you need to put the pipe in the `NgModule` which declares the component, either directly via `declarations` or via another module with `imports`.
