### ISSUE TITLE
@angular/animations delay passed in options parameter for transition() call has no effect

### ISSUE THREAD

**Issue by konstantintieber** [angular/angular#29762]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/animations

### Is this a regression?
I don't know, I just tried to use the AnimationOptions parameter for the first time in @angular/animations version 7.2.1

### Description

I need to delay the starting of an animation, but the delay parameter of the animate() function doesn't fit, as the start event of the animation will be fired once the trigger was activated, regardless of the delay provided in this way: `animate ('duration delay easing')`

In the [transition()](https://angular.io/api/animations/transition) and [AnimationOptions](https://angular.io/api/animations/AnimationOptions) docs I came across the delay property, which is supposed to "set a time-delay for initiating an animation action".

I was not able to observe any delay when providing the `{ delay: '2s' }` as options parameter in my transition calls(). See stackblitz.

I depend on this behaviour, as I need to update component state, based on the animation start event, which needs to fire after the delay.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-qq6tyv

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.2.2
Node: 10.13.0
OS: darwin x64
Angular: 7.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.2
@angular-devkit/build-angular     0.12.2
@angular-devkit/build-optimizer   0.12.2
@angular-devkit/build-webpack     0.12.2
@angular-devkit/core              7.2.2
@angular-devkit/schematics        7.2.2
@angular/cli                      7.2.2
@ngtools/webpack                  7.2.2
@schematics/angular               7.2.2
@schematics/update                0.12.2
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4

</code></pre>

Angular Animations version: 7.2.1

**Comment by konstantintieber** [comment]
@matsko do you agree that this is broken? I was still thinking that there might be a chance that I'm using AnimationOptions in a wrong way.

If it _is_ broken, then I might take the time to find a fix for this.

**Comment by YonatanKra** [comment]
@konstantintieber I do not believe this is a bug. Looks like you are not using it correctly. Look at the docs: https://angular.io/guide/animations#transitions-and-timing
Specifically: 
```
To make the change less abrupt, we need to define an animation transition to specify the changes that occur between one state and another over a period of time. The transition() function accepts two arguments: the first argument accepts an expression that defines the direction between two transition states, and the second argument accepts an animate() function.
```
You sent it 3 parameters. The delay is sent inside the `animate` method. Here's your example with the correct syntax: https://stackblitz.com/edit/angular-qq6tyv-zkxv39

**Comment by konstantintieber** [comment]
@YonatanKra thanks for your feedback. However if you look at the API page of the [transition()](https://angular.io/api/animations/transition) function you see the third argument for AnimationOptions, which includes a delay property.

The difference between these two delays is, that the delay you define within the _animate()_ `timings` parameter will not delay the animation start event, unlike the `delay` from the `AnimationOptions` given in a _transition()_ call.

**Comment by YonatanKra** [comment]
`transition(stateChangeExpr: string | ((fromState: string, toState: string, element?: any, params?: { [key: string]: any; }) => boolean), steps: AnimationMetadata | AnimationMetadata[], options: AnimationOptions = null): AnimationTransitionMetadata`

**Comment by wooliesx-apirillo** [comment]
This still appears to be an issue, is it being worked on?

**Comment by VesterDe** [comment]
I would appreciate if someone took a look at this... It's been almost a year, and I just stumbled upon it.

Seems like a straightforward feature.

**Comment by aalvarez-stratio** [comment]
I have found a workaround for this using animation params. I don't know if this would be useful for you @konstantintieber. I hope yes:

```
const fadeIn = this._animationBuilder.build([
  style({ opacity: 0 }),
  animate('300ms {{delay}} ease-in-out', style({ opacity: 1 }))
]);
```

and then:

`
this._tooltipFadeInPlayer = fadeIn.create(this._tooltipElement, { params: { delay: '300ms' }});
`

Can also be used in this way: 

```
export const myAnimation = animation([
  animate('250ms {{delay}} cubic-bezier(0.25, 0.46, 0.45, 0.94)', style({ opacity: 1 }))
]);
```

and then: 

```
@Component({
  trigger('openClose', [
    transition('open => closed', [
      useAnimation(myAnimation, {
        params: { delay: 500 }
      })
    ])
  ])
})
```

**Comment by Mereo4** [comment]
Still present in v11.2.7. Since it is not fixed, it should be at least written in the documentation to avoid losing time searching for clues, please.
