### ISSUE TITLE
Running Bazel build on Windows with default Execution Policy doesn't work

### ISSUE THREAD

**Issue by frederikprijck** [angular/angular#29760]
# 🐞 bug report

### Affected Package
This issue is related to running Bazel on Windows.

### Is this a regression?
N/A

### Description

I checked out Angular and did a fresh yarn install. Once that was done, I tried running one of the `package/examples`, in this case it was my own example package (for my PR at https://github.com/angular/angular/pull/29755), which runs fine on the CI.

Once I run my example using `yarn bazel run //packages/examples/router/activated-route:devserver`, I get the error I mentioned below.

To resolve this, all I had to do was open PowerShell and execute the following command:

```
Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricted
```

When I now try and run `yarn bazel run //packages/examples/router/activated-route:devserver`, everything works fine! :)

As this unblocked me, I used this aproach and decided to see if anyone on twitter had a way to solve this.
The friendly @alexeagle replied to my tweet asking if I had an Github issue. I didn't, but now I do 😄 !

## 🔬 Minimal Reproduction
Just run the master on Windows 10 with the default Execution Policy (Resitricted) and run any example mini-app ( ensure to empty your bazel directory with cache etc). If you want to execute the command I've been pasting (`yarn bazel run //packages/examples/router/activated-route:devserver`), you'll need to run my branch for this PR: https://github.com/angular/angular/pull/29755

## 🔥 Exception or Error
<pre><code>Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: error loading package '': Encountered error while reading extension file 'package.bzl': no such package '@npm_bazel_karma//': copy_repository failed:
STDOUT:

STDERR:
File C:\users\frederik\_bazel_frederik\p5aerkcd\external\npm_bazel_karma\_copy.ps1 cannot be loaded because running
scripts is disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess
ERROR: error loading package '': Encountered error while reading extension file 'package.bzl': no such package '@npm_bazel_karma//': copy_repository failed:
STDOUT:

STDERR:
File C:\users\frederik\_bazel_frederik\p5aerkcd\external\npm_bazel_karma\_copy.ps1 cannot be loaded because running
scripts is disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess
INFO: Elapsed time: 54.276s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.</code></pre>

## 🌍  Your Environment

**Angular Version:**
N/A

**Anything else relevant?**
So I'm running on Windows 10, My Execution-Policy is set to its default value. 
If any other environmental information is needed, feel free to reach out.

**Comment by frederikprijck** [comment]
I got a feeling it's an issue on my end. I mean, the ExecutionPolicy is doing what it's expected rioght? Not allowing bazel to execute the script ...
However, I wanted to create this issue anyway, but feel free to close it if it's expected behavior.

**Comment by meteorcloudy** [comment]
@frederikprijck I guess this is WAI.
I am able to `yarn bazel run packages/examples/common:devserver` on Windows with
```
PS C:\Users\pcloudy> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy    RemoteSigned
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine          Bypass
```

**Comment by frederikprijck** [comment]
@meteorcloudy Yes, I guess the reason it's working for you is because you've set the ExecutionPolicy to `Bypass` for the `LocalMachine` scope. Setting it to `Unrestricted` it also works for me.

Do you recommend people to update their ExecutionPolicy to either Bypass or `Unrestricted` ? I'm not familiar with PowerShell, but it doesn't sound like a setting you wanna have.

**Comment by meteorcloudy** [comment]
I'm not very familiar with powershell, either. I think users should only be required to set `ExecutionPolicy` when their default setting doesn't work. @alexeagle What do you think it the best way to document this?

**Comment by frederikprijck** [comment]
Important to note that:

> PowerShell's execution policy is a safety feature that controls the conditions under which PowerShell loads configuration files and runs scripts. This feature helps prevent the the execution of malicious scripts.

I'm not familiar with Bazel, I guess it needs this setting. However it would be good if it could be avoided or configured to only set it for the bazel process (if that's even possible).

**Comment by meteorcloudy** [comment]
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-6#set-a-different-execution-policy-for-one-session

Looks like we can run `powershell.exe` with `-ExecutionPolicy Unrestricted` option.

**Comment by alexeagle** [comment]
Is there a way we can run code without the user having to modify a setting? Using .bat instead of powershell? We should always treat this kind of bad user ergonomics as a bug (I imagine many devs wouldn't have rights to change that kind of policy on their machine anyway)

@gregmagolan has a plan to remove the need for powershell in this case I believe.

**Comment by gregmagolan** [comment]
Finally got around to this. https://github.com/bazelbuild/rules_nodejs/pull/717 removes the powershell dep & used a `.bat` file instead

**Comment by meteorcloudy** [comment]
There is another powershell dependency coming from rules_webtesting:
https://github.com/bazelbuild/rules_webtesting/blob/master/web/internal/extract.bat
But I'm not sure there's any equivalent command in batch.
@gregmagolan
