### ISSUE TITLE
Docs: Getting started pages don't show hamburger menu on desktop

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#29773]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

When visiting any of the new getting started pages, the hamburger menu icon isn't displayed in the top left corner when in desktop mode.

## 🔬 Minimal Reproduction

 

Visit https://next.angular.io/getting-started with desktop resolution. Note the icon isn't displayed.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

Support for getting started page needs to be added to styles to https://github.com/angular/angular/blob/master/aio/src/styles/1-layouts/_top-menu.scss#L53 as `aio-shell.folder-getting-started mat-toolbar.mat-toolbar`

**Comment by invictusmaneo** [comment]
Hey @brandonroberts looks like a good first issue, can I take this up?

**Comment by gkalpak** [comment]
It's all yours, @invictusmaneo :smiley:

**Comment by brandonroberts** [comment]
Fixed via #29791 🎉
