### ISSUE TITLE
Dependency updates required for version 8

### ISSUE THREAD

**Issue by manughub** [angular/angular#29789]
<h1>Angular Dependency List</h1>
<table>

<tr>
  <td colspan=2 rowspan=2><strong>Dependency Info</strong></td>
  <td colspan=3><strong>Framework</strong></td>
  <td colspan=3> <strong>Components</strong></td>
  <td colspan=4> <strong>Tooling  </strong></td>
</tr>

<tr>
  <td><a href="https://github.com/angular/angular/blob/master/package.json">devDep</a></td>
  <td>dep
     <a href="https://github.com/angular/angular/blob/master/packages/core/package.json">1</a>,<a href="https://github.com/angular/angular/blob/master/packages/compiler-cli/package.json">2</a>,<a href="https://github.com/angular/angular/blob/master/packages/platform-server/package.json">3</a></td>
  <td><a href="https://github.com/angular/angular/blob/master/packages/core/package.json">peerDep</a></td>
  <td><a href="https://github.com/angular/material2/blob/master/package.json">devDep</a></td>
  <td><a href="https://github.com/angular/material2/blob/master/src/lib/package.json">dep</a></td>
  <td><a href="https://github.com/angular/material2/blob/master/src/lib/package.json">peerDep</a</td>
  <td><a href="https://github.com/angular/angular-cli/blob/master/package.json">devDep</a></td>
  <td>dep</td>
  <td>peerDep</td>
  <td><a href="https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/utility/latest-versions.ts">scaffold</a></td>
</tr>

<tr><td>zone.js<td>^0.9.0
  <td>[x]<td> <td>[x]
  <td>[x]<td> <td> 
  <td> <td>[x]<td> <td>[x]

<tr><td>typescript<td>^3.4.2
  <td>[x]<td> <td>[x]
  <td>[ ]<td> <td>
  <td>[x]<td>[x]<td> <td>[x]

<tr><td>tslib<td>^1.9.0
  <td>[x]<td>[x]<td>[?] 
  <td>[x]<td>[ ]<td>[?]
  <td> <td> <td> <td>[ ]

<tr><td>rxjs<td>^6.4.0
  <td>[ ]<td>[x] <td>[ ]
  <td><td><td>
  <td>[ ]<td>[ ]<td>[ ]<td>

<tr><td>Domino<td>^2.1.2<td>[ ]<td>[x]<td> <td><td><td><td><td><td><td>
<tr><td>xhr2<td>~0.1.4<td>[ ]<td>[ ]<td> <td><td><td><td><td><td><td>
<tr><td>reflect-metadata<td>^0.1.3<td>[ ]<td>[x]<td> <td><td><td><td><td><td><td>
<tr><td>@angular/core<td>^8.0.0-*<td>[ ]<td>[ ]<td>[ ]<td><td><td>[ ]<td>[]<td>[x]<td><td>
<tr><td>minimist<td>^1.2.0<td>[x]<td>[x]<td> <td><td><td><td><td><td><td>
<tr><td>canonical-path<td>^1.0.0<td>[?]<td>[x]<td> <td><td><td><td><td><td><td>
<tr><td>chokidar<td>^2.1.1<td>[? ]<td>[x]<td> <td><td><td><td><td><td><td>
<tr><td>webpack<td>4.30.0<td> <td>[x]<td> <td> <td> <td> <td> <td>[x]<td><td>
<tr><td>convert-source-map<td>^1.5.1<td>[?]<td>[x]<td> <td><td><td><td><td><td><td>
<tr><td>dependency-graph<td>0.7.2<td>[?]<td>[x]<td> <td><td><td><td><td><td><td>
<tr><td>magic-string<td>^0.25.0<td>[?]<td>[x]<td> <td><td><td><td><td><td><td>
<tr><td>shelljs<td>^0.8.1<td>[?]<td>[x]<td> <td><td><td><td><td><td><td>
<tr><td>source-map<td>^0.6.1<td>[?]<td>[x]<td> <td><td><td><td><td><td><td>
<tr><td>yargs<td>^9.0.1<td>[?]<td>[x]<td> <td><td><td><td><td><td><td>
<tr><td>jpm<td>^1.3.1<td>[?]<td>[x]<td> <td><td><td><td><td><td><td>
<tr><td>selenium-webdriver<td>3.5.0<td>[?]<td>[x]<td> <td><td><td><td><td><td><td>
<tr><td>firefox-profile<td>1.0.3<td>[?]<td>[x]<td> <td><td><td><td><td><td><td>
</table>

**Comment by IgorMinar** [comment]
all the important deps has been updated.
