### ISSUE TITLE
Why patchValue doesn't work with formArray ?

### ISSUE THREAD

**Issue by eudago** [angular/angular#29787]
WHen I use the patchValue and pass him an object where the formGroup has a formArray, the formArray is not setted.

Example:

test = new FormGroup({
   test: new FormArray([])
})

test.patchValue({test: [
  { ..... }
]})

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
