### ISSUE TITLE
ngStyle does not accept number as value

### ISSUE THREAD

**Issue by Spielboerg** [angular/angular#29782]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/common

### Description
I get a linting error when I use numbers in `ngStyle`.

Example:
```html
<div [ngStyle]="{ 'maxHeight.px': 100 }"></div>
```

## 🔥Error
```
Type {'maxHeight.px': number} is not assignable to type {[p: string]: string}
```

The file in the npm package that causes the error is `@angular/common/src/directives/ng_style.d.ts` line 53

I'm not sure, but maybe this line in the source file is causing the problem:
https://github.com/angular/angular/blob/master/packages/common/src/directives/ng_style_impl.ts#L30

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.8
Node: 10.8.0
OS: darwin x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cdk                      7.3.7
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.29.0
</code></pre>

**Comment by szywi** [comment]
Isn't it actually caused by this line [ng_style.ts at 7.2.x](https://github.com/angular/angular/blob/7.2.x/packages/common/src/directives/ng_style.ts#L66)

This should be fixed in [ng_style.ts at 8.0.x](https://github.com/angular/angular/blob/8.0.x/packages/common/src/directives/ng_style.ts#L112)

**Comment by Spielboerg** [comment]
It seems the problem has been fixed. At least I don't get the error anymore.
