### ISSUE TITLE
Extending Service Worker custom code support

### ISSUE THREAD

**Issue by kbirger** [angular/angular#29790]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/service-worker

### Description
This package provides a fantastically simple way to integrate a service worker into an angular application, but it would be great if there was a way to extend that service worker by providing custom code for event handling.

### Describe the solution you'd like
Ideally, you could just provide your own typescript files, which would be specified in the ngsw-config, and each file could be a single `self.addEventListener('xxx', () => {})` block. These would all get concatenated to form the final service worker.

I don't have a good idea at the moment for extending handling of functionality that already exists (such as the built-in fetch), but I think that might be less important.

### Describe alternatives you've considered
While it is possible to register any number of service workers to achieve functionality not currently present int his package, it seems that this would introduce maintenance overhead and potentially bugs with the interactions of multiple workers.

- multiple workers handling the same event

It also leaves application developers to their own devices in terms of how they will integrate their service workers into an application:

- Homegrown approach to building a service worker in TypeScript (if desired)
- Homegrown approach to integrating it

### Related Issue
https://github.com/angular/angular/issues/21918
https://github.com/angular/angular/issues/21183
https://stackoverflow.com/questions/36000127/can-i-have-multiple-service-workers-both-intercept-the-same-fetch-request/36004941#36004941

**Comment by alxhub** [comment]
This was an explicit non-goal for the Angular Service Worker - we wanted our SW to be a drop-in binary without any custom extension or configuration.

This may change with a later release, but for now it is not on our roadmap to support custom plugins in Service Workers.

**Comment by rohitnandan** [comment]
Such a drop-in binary is of no use for some cases, consider a request if made by GET will cross 2k characters limit & POST is not cached, indeed service-worker should have supported it from the start. There some solutions which let's you hook onto fetch request and even cache the idempotent POST requests.
