### ISSUE TITLE
Using TypeScript path mapping for peer dependencies

### ISSUE THREAD

**Issue by xpleria** [angular/angular#29807]
# 📚 Angular Docs Feedback

### Description

This is not a bug, but a feedback. Might seem really trivial, but will probably help the newbies.

The documentation says:

> List all the peer dependencies that your library uses in the TypeScript configuration file ./tsconfig.json

but does not mention which `tsconfig.json` file. Of the application or the library? 

Most of you are probably thinking "of the application! duh!?". But it wasn't clear for me and I kept trying different values in the library tsconfig file for quite some time before finally trying it in the application `tsconfig` file.

Moreover, shouldn't it be:

    {
      "compilerOptions": {
        // ...
        // paths are relative to `baseUrl` path.
        "paths": {
          "@angular/*": [
            "./node_modules/@angular/*"
          ],
          "tslib": [
            "./node_modules/tslib"
          ]
        }
      }
    }

The `node_modules` folder is in the same folder as the `tsconfig.json`. Unless you're talking about the `tsconfig.app.json` which is in the `src` folder.

Hope my feedback helps :)

**Comment by alan-agius4** [comment]
Hi, this refers to workspace tsconfig file. Ie the root `tsconfig.json`
