### ISSUE TITLE
queryParamsHandling: 'preserve' not work as describe in guide

### ISSUE THREAD

**Issue by DamianSheldon** [angular/angular#29805]
# 📚 Docs or angular.io bug report

### Description

 Query parameters and fragments don't  pass along  to the next route when queryParamsHandling set to preserve and preserveFragment set true.

### What's the affected URL?**
 https://angular.io/generated/live-examples/router/stackblitz.html

### Reproduction Steps**

1.Click Admin button;
2.Click Login button;

### Expected vs Actual Behavior**

Expected:
Query parameters and fragments should still intact in the address bar like follow:

https://lrgbklxpqal.angular.stackblitz.io/admin?session_id=123456789#anchor

Actual Behavior:
No query parameters and fragments in the address bar:

https://lrgbklxpqal.angular.stackblitz.io/admin

### Browser info

Chrome: Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by jasonaden** [comment]
I don't see where `queryParamsHandling` has been added such that it would behave as you expect. Changing the `Login` link in your example to the following produces the result you say you're looking for. I think this is working as designed, but if you continue to have a problem, please create a new issue as I'll close this one as "working as designed":

`<a routerLink="/login" routerLinkActive="active" queryParamsHandling="preserve">Login</a>`
