### ISSUE TITLE
Do not fire FormControl on change when setting the same value as store one

### ISSUE THREAD

**Issue by VGib** [angular/angular#29804]
# 🚀 feature request

(may be related to this: https://github.com/angular/angular/issues/26215, but I don't want to disable the emitEvent ....)

### Relevant Package
@angular/forms

### Description
Hello,

in my company I have some angular forms trouble. We have big forms with lot of datas, that we modify after form changing on webservice update.
Each web service update change the form, and some automatics propagation change other forms asking for web service propagation and so on ....
```typescript
myForm.get("myValue").valueChange..subscribe(value =>callAppServiceAndDoSomeStuf())
````
The problem is than when we change for same value, the valueChange event is fired and event is propagated.
As you see in set value code in FormControl class: which seems to be the only one updating FormControl value (am I right?), update every change event if change is the same.
````typescript
 setValue(value: any, options: {
    onlySelf?: boolean,
    emitEvent?: boolean,
    emitModelToViewChange?: boolean,
    emitViewToModelChange?: boolean
  } = {}): void {
    (this as{value: any}).value = this._pendingValue = value;
    if (this._onChange.length && options.emitModelToViewChange !== false) {
      this._onChange.forEach(
          (changeFn) => changeFn(this.value, options.emitViewToModelChange !== false));
    }
    this.updateValueAndValidity(options);
  }
````
To fix this I need to add the distinctUntilChanged rxjs operator everywhere, which is quite boring and errorprone, as this may be forgotten.

### Describe the solution you'd like
I'd like the Set Value of the ControlForm to fire change only if the setted value is distinct of the stored one.
I know this may be tricky and have lot of consequencies. So if this is not possible for reverse compatibility, I would like to have a form option, on formBuilder or as a static angular option, for enabling this behavior.

What do you think ?

### Describe alternatives you've considered
use distinctUntilChanged **everywhere** in your application

**Comment by Airblader** [comment]
Changing behavior should be out of the question as it's definitely behavior a user expects in many other cases. Regarding a new option my question would be why that's less errorprone than using distinctUntilChanged?

**Comment by pkozlowski-opensource** [comment]
This was reported several times previously (ex.: #25749) so I would argue that the current behaviour (or at least observable name) _is_ confusing and catches people. Also agree that it would be a braking change (although curious to learn _why_ and how people would use current behaviour to their advantage).

**Comment by Airblader** [comment]
Agreed that the name of the observable is misleading, but as long as we only have one, at least the current behavior is more permissive: the user can choose to ignore duplicate emissions. If we were to change it, the user is left unable to keep their behavior as they cannot recover duplicate emissions (unless a new observable is exposed for this).

If we look at it from the other side, `setValue` has an `emitEvent` option. I feel like it'd also be confusing if `setValue({emitEvent: true})` could suddenly *not* emit events anymore.

And, of course, catching duplicates is easy when your value is a primitive, but for anything complex you start running into the issue of determining equality.

**Comment by kara** [comment]
Thanks for the issue, @VGib. As others have noted, this is a common feature request (and the name is confusing), so it's on our radar. We just need to figure out how to navigate the breaking change, so it needs some design/thought.

Given that this use case is being tracked in the existing issue #25749, I'm closing this one as a duplicate.
