### ISSUE TITLE
Schematics for library project uses angular-in-memory-web-api from brandons repo

### ISSUE THREAD

**Issue by santoshyadav198613** [angular/angular#29802]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

After you download the Library schematic project from https://angular.io/guide/schematics-for-libraries, the package.json file contains below dependency

"angular-in-memory-web-api": "github:brandonroberts/in-memory-web-api-bazel#50a34d8",

aio/tools/examples/shared/package.json File path.
Now in most of the organization the only way we can download is via artifactory and we get error. And we are not even using this package in our example.

### What's the affected URL?**
 https://angular.io/...

https://angular.io/guide/schematics-for-libraries

### Expected vs Actual Behavior**

npm install should work behind proxy as well, which is breaking due to the package mentioned.

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by santoshyadav198613** [comment]
Hi @brandonroberts ,

Can you suggest any package which is available on npm rather than referring from your repo.

**Comment by brandonroberts** [comment]
As a workaround, replace the GitHub URL with `^0.8.0` in the `package.json`. I have a fix for the `package.json` generator for the zip files.

**Comment by santoshyadav198613** [comment]
Thanks @brandonroberts .

**Comment by santoshyadav198613** [comment]
Hi @kapunahelewong ,
I think this is still using githib link, should i update it.

**Comment by gkalpak** [comment]
What Brandon suggested above is that switching to `^0.8.0` locally is fine. Switching it in the angular repo, however, might make some tests fail on CI.

I don't know if that current version of `angular-in-memory-web-api` (0.9.0) is sufficient to make CI happy, but we can definitely try that. @santoshyadav198613, feel free to submit a PR updating to the latest version to check CI.

**Comment by santoshyadav198613** [comment]
Hi @gkalpak ,
Is there anything you want me to test because CI is green.

**Comment by gkalpak** [comment]
Thx for the PR, @santoshyadav198613! Let's discuss on #32892.
