### ISSUE TITLE
Objects converted to ParamMap can err when ParamMap functions are called on them.

### ISSUE THREAD

**Issue by Zarepheth** [angular/angular#29816]
# 🐞 bug report

### Affected Package
Error is in the Router module's shared.ts file, on line 68.
https://github.com/angular/angular/blob/79fb9d449c0fab9bdb5886f09d4fc9cd52f89318/packages/router/src/shared.ts#L68

### Description

If an object is passed to the `convertToParamMap` function is missing the `hasOwnProperty` method. Attempts to call the new ParamsAsMap object's `has`, `get`, or `getAll` methods will all throw this error: `TypeError: this.params.hasOwnProperty is not a function`.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-igb464?embed=1&file=src/app/app.component.ts

## 🔥 Exception or Error
<pre><code>
TypeError: this.params.hasOwnProperty is not a function
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 6.0.8
Node: 10.1.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.8
@angular-devkit/core         0.6.8
@angular-devkit/schematics   0.6.8
@schematics/angular          0.6.8
@schematics/update           0.6.8
rxjs                         6.2.2
typescript                   2.7.2

</code></pre>

**Anything else relevant?**
I'm pretty sure this occurred because I created the initial `Params` object using `Object.create(null)`. At the time, I wanted a very plain object with no extraneous stuff on its prototype chain.

**Comment by jasonaden** [comment]
Thanks! Looks like we could fix this issue by changing the call [here](https://github.com/angular/angular/blob/master/packages/router/src/shared.ts#L68) to something like: 

`Object.prototype.hasOwnProperty.call(this.params, name)`

If this is something you would want to submit as a PR, it would be appreciated.

**Comment by abarghoud** [comment]
I would like to take this one too

**Comment by abarghoud** [comment]
@jasonaden PR ready for a review

**Comment by rafaelss95** [comment]
I guess this can be closed as it was already fixed in [**`3190ccf`**](https://github.com/angular/angular/commit/3190ccf).

**Comment by JoostK** [comment]
Thanks @rafaelss95, closing as resolved in #31599.
