### ISSUE TITLE
ngAfterViewChecked called without change detection on child component

### ISSUE THREAD

**Issue by ChristophWieske** [angular/angular#29814]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core

### Is this a regression?

No, it wasn´t working in 2016 as well.

### Description

When using `OnPush` change strategy and a component gets clicked the change detection run for it and its ancestors. But it also executes `ngAfterViewChecked` for all its child components and the child components of each ancestor.

The docs say: 
[AfterViewChecked: A lifecycle hook that is called after the default change detector has completed checking a component's view for changes.](https://angular.io/api/core/AfterViewChecked)

But a change detection does not happen in that case.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/change-detection-sample-ng-after-view-checked?file=src%2Fapp%2Ftree-node%2Ftree-node.component.ts

## 🌍  My Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.1.4
Node: 8.9.0
OS: win32 x64
Angular: 7.1.4
... animations, cli, common, compiler, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.13.7
@angular-devkit/build-optimizer   0.13.7
@angular-devkit/build-webpack     0.13.7
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@angular/compiler-cli             7.2.11
@angular/material                 <error>
@ngtools/webpack                  7.3.7
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.29.0

</code></pre>

**Comment by pkozlowski-opensource** [comment]
Isn't this the same issue as #7055? Do we have new information / insight / proposal here? If not I would lean towards closing is as a duplicate of #7055

**Comment by ChristophWieske** [comment]
well yes, seems to be a duplicate. Was active on #7055 too, but thought it wasn´t recognized as a bug. As described there, I no longer think this is a bug. Maybe a little misleading docs.
