### ISSUE TITLE
Required Validator does not catch whitespace only

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular#29813]
# 🐞 bug report

### Affected Package
@angular/forms 7.2.1

### Is this a regression?
Not sure

### Description
Whitespaces are not invalid when using required validator in reactive forms. This causes our .net 4 Web API to throw a model validation error as the value gets trimmed somewhere on the way to .net.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-issue-repro2-ovo1un

## 🔥 Exception or Error
-

## 🌍  Your Environment

**Angular Version:**
7.2.1

**Comment by kara** [comment]
@mbeckenbach Thanks for taking the time to file an issue. I took at look at the example you provided;  this is actually expected behavior. Angular validators are intended to mimic native form validation, and the native required validator accepts whitespace as valid input.
