### ISSUE TITLE
Service worker offline caching not working in jboss server.

### ISSUE THREAD

**Issue by nandhini07** [angular/angular#29829]
Service worker offline caching is working in npm http server suggested by angular . But the same application deployed in jboss server its not caching the files while offline.

**steps which are followed:**

**step1:** ng add @angular/pwa

**step2:** ng build --prod

**step3:** deployed in https server(jboss server)

**step4:** accessing the application in  offline mode

**step5:**
![image](https://user-images.githubusercontent.com/37096316/55955178-57c9fa00-5c7e-11e9-8799-0936d07e76e6.png)

**notes:**
```
**manifest.json**

{
  "name": "Sample app",
  "short_name": "app",
  "theme_color": "#2196f3",
  "background_color": "#2196F3",
  "display": "standalone",
  "gcm_sender_id": "103953800507",
  "orientation": "portrait",
  "start_url": "/mxrw/",
"icons": [
```

**ngsw-config.json**

```
{
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "resources": {
        "files": [
          "/favicon.ico",
          "/index.html",
          "/*.css",
          "/*.js"
        ]
      }
    },
    {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "resources": {
        "files": []
      }
    }
  ]
}
```

Please suggest any of the configuration which has to be added additionally in above sample

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
