### ISSUE TITLE
make dart transformers work on material samples

### ISSUE THREAD

**Issue by sigmundch** [angular/angular#2982]
A currently known issue we are hitting is that we don't resolve correctly cross-package urls (we need to change the current convention of using a relative url from the baseUri, instead we should rely more on package: urls and possibly relative urls (if we can find a way to compute these using dart:mirrors for components declared in both plain libraries and part files)

**Comment by sigmundch** [comment]
FYI - @jakemac53 - this might be easier to get working now that Yegor fixed #2991

**Comment by jakemac53** [comment]
I will take a shot at it

**Comment by jakemac53** [comment]
nvm, package: urls are not enough for the examples, unless we want to define a dart and npm package for each example which is a different can of worms that I am not prepared to open :).

**Comment by jmac11** [comment]
Try it now

**Comment by tomaseilsoe** [comment]
Are there any workarounds to be able to use material in a dart angular2 app ?

**Comment by jelbourn** [comment]
@tomaseilsoe nobody should be using those components; they're only for internal testing at this stage.

**Comment by tbosch** [comment]
This might work now with the new compiler (not yet in master)...

**Comment by tbosch** [comment]
Fixed by #3605

**Comment by zoechi** [comment]
Can this be closed?
