### ISSUE TITLE
docs(cli): document that scripts and styles can accept objects

### ISSUE THREAD

**Issue by Splaktar** [angular/angular#29822]
# 📚 Docs or angular.io bug report

### Description

https://angular.io/cli/build mentions

> Some additional options can only be set through the configuration file, either by direct editing or with the ng config command. These include assets, styles, and scripts objects that provide runtime-global resources to include in the project. 

https://angular.io/guide/workspace-config#alternate-build-configurations and https://next.angular.io/guide/workspace-config#additional-build-and-test-options mention

OPTIONS PROPERTIES | DESCRIPTION
-- | --
styles | An object containing style files to add to the global context of the project. Angular CLI supports CSS imports and all major CSS preprocessors: sass/scss, less, and stylus.
scripts | An object containing JavaScript script files to add to the global context of the project. The scripts are loaded exactly as if you had added them in a <script> tag inside index.html.

But neither cover that they can accept an [extraEntryPoint](https://github.com/angular/angular-cli/blob/e6bba9eaf90e7d929b4e9da45ed5dabc5c8df49f/packages/angular/cli/lib/config/schema.json#L967-L996) object like: `{"input": "src/styles/foo.css", "lazy": true, "bundleName: "foo"}` nor how to use the features that these options enable like [lazy loading styles](https://github.com/angular/angular-cli/issues/11235).

### What's the affected URL?**
https://angular.io/guide/workspace-config#alternate-build-configurations
https://next.angular.io/guide/workspace-config#additional-build-and-test-options

### Reproduction Steps**
See Description.

### Expected vs Actual Behavior**
Stable features are expected to be documented.
Actual: stable features are not documented.

**Comment by kapunahelewong** [comment]
Hi @Splaktar I looked at the PR referenced above but it looks like this issue still needs to be addressed fully, right? (Just making sure I understand for labels). Thanks!

**Comment by Splaktar** [comment]
@kapunahelewong yes, the PR that references this issue is for AngularJS Material. I wanted to point to some good docs on this feature, but found that they didn't exist. Thus I opened this issue.

**Comment by Splaktar** [comment]
I'm not sure that I understand the `type: feature` label here as this is just a documentation issue. The feature exists and has been around for a year or more. The docs just don't provide enough detail beyond these fields accepting generic `object`s.

**Comment by kapunahelewong** [comment]
Ah, thanks for the clarification @Splaktar. The use of `type: feature` for anything `comp: docs` means just adding some new documentation, rather than something new in Angular. If you're interested in all the details, check out the guidelines the docs team PM, @jenniferfell, wrote: [Triage Guidelines](https://github.com/ExpertSupport/doc-workflow/wiki/Workflow-for-Open-Issues#secondary-triage-for-docs). Pardon me if some of my labels are off, I've only started triaging with the new guidelines this week! 😅

**Comment by alan-agius4** [comment]
Another missing part similar to the above is the `sourceMap` and `optimization` options when they don’t have a boolean value.

**Comment by Splaktar** [comment]
`sourceMap` comments and config are [here](https://github.com/angular/angular-cli/blob/0f9de92dcb8833cfdf6bfad832a9cf281ac27d3d/packages/angular_devkit/build_angular/src/browser/schema.json#L107-L141).

`optimization` comments and config are [here](https://github.com/angular/angular-cli/blob/0f9de92dcb8833cfdf6bfad832a9cf281ac27d3d/packages/angular_devkit/build_angular/src/browser/schema.json#L59-L83).

**Comment by jbogarthyde** [comment]
Landed in Next, depends on CLI change that isn't in Stable yet (renamed a parameter that was misleading)
