### ISSUE TITLE
Route guards fire before APP_INITIALIZER promise resolved

### ISSUE THREAD

**Issue by havran** [angular/angular#29828]
# 🐞 bug report

### Description

(In local development server) If user open page protected by guard, and this guard want use some data from service which is initialized by APP_INITIALIZER, then guard is fire before Promise from service is resolved.

## 🔬 Minimal Reproduction

https://github.com/havran/angular-APP_INITIALIZER-bug

## 🌍  Your Environment

```
Angular CLI: 7.3.8
Node: 8.15.1
OS: linux x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
```

**Comment by alexzuza** [comment]
Hey Juraj,

I took a look at your repository and discovered that your issue is directly related and effected by the problem introduced by #14588 where Victor Savkin [described](https://github.com/angular/angular/issues/14588#issuecomment-281744906) the background of the problem and the immediate solution.

So instead of using `'enabled'` initialNavigation you can run navigation by yourself after the application has loaded

**app-routing.module.ts**

```
RouterModule.forRoot(routes,  { initialNavigation: 'enabled'  })
```

**app.component.ts**
```
export class AppComponent {
  constructor(router: Router) {
    router.initialNavigation();
  }
}
```

**Comment by havran** [comment]
@alexzuza Thank you for answer, i hope for not only this solution. In our app we want `initialNavigation = 'enabled'` because of flickering on app rendered through SSR and then i can't use this.

**Comment by Antheso** [comment]
@havran did you found solution? I have the same problem (also with SSR).

**Comment by havran** [comment]
@antheso Hi - i use workaround when i get type of environment from Angular environment file and set initialNavigation enabled/disabled by environment.

**Comment by ayyash** [comment]
@havran care to elaborate a bit? what environment eventually affects the SSR implementation? do you set initialNavigation to false only if in ssr?
