### ISSUE TITLE
warning  > @angular/platform-server@7.2.12 has unmet peer dependency @angular/http@7.2.12

### ISSUE THREAD

**Issue by caviroski** [angular/angular#29831]
# 🐞 bug report

### Affected Package
@angular/platform-server@7.2.12

### Description

I have Angular v7.2.12 when I do `yarn` I get this warning:
`warning " > @angular/platform-server@7.2.12" has unmet peer dependency "@angular/http@7.2.12".`

I have removed `"@angular/http": "7.2.12",` from my `package.json`, because it is deprecated and I have only `"@angular/common": "7.2.12",`

## 🔬 Minimal Reproduction
Delete `node-modules` folders and run `yarn` with Angular 7.2.12

## 🌍  Your Environment

Angular CLI: 7.3.8
Node: 8.9.4
OS: darwin x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

yarn install v1.15.2

**Comment by ericmartinezr** [comment]
Related https://github.com/angular/angular/pull/29356

**Comment by CaerusKaru** [comment]
`@angular/http` has been removed starting in v8. You'll continue to get the warning for all v7 versions, but it will go away in v8.

**Comment by vikerman** [comment]
This is a known issue. As of 7.x version of platform-server you need to have @angular/http as a peer dependency even if you don't use it.

We are removing this dependency in 8 as referenced in the PR above.
