### ISSUE TITLE
ValueSansProvider / ClassSansProvider not available in docs

### ISSUE THREAD

**Issue by macjohnny** [angular/angular#29830]
# 📚 Docs or angular.io bug report

### Description

Some interfaces are not available in the API docs, e.g. `ClassSansProvider`, `ValueSansProvider`

### What's the affected URL?**
https://angular.io/api/core/ClassProvider

### Reproduction Steps**
clicking on the `ClassSansProvider` part of `interface ClassProvider extends ClassSansProvider ` leads to [https://angular.io/](https://angular.io/)

### Expected vs Actual Behavior**
Expected: should lead to `ClassSansProvider` interface description.
Due to the inheritance, e.g. the property `useClass` is not in the list of properties in https://angular.io/api/core/ClassProvider

**Comment by kapunahelewong** [comment]
Related to: #29963
