### ISSUE TITLE
The default route always is loaded.

### ISSUE THREAD

**Issue by danicomas** [angular/angular#2983]
The first time that we load the app with the route /#/home1 angular is loading the constructor of component Home (default) then loads Home1. I think that the component Home shouldn't be loaded. @btford @IgorMinar @jeffbcross

```js
this.router.config(
      [{ path: '/',  redirectTo: '/#/home' },
     { path: '/#/home', as: 'home', component: Home },
     { path: '/#/home1', as: 'home1', component: Home1 }]).then((_) => router.navigate(path);
```

**Comment by btford** [comment]
You should not include `#` in your URL. Instead, you should bind `LocationStrategy` to `HashLocationStrategy`.

**Comment by danicomas** [comment]
Thanks @btford today I will try it. But if I have a decorator instead router.config could I have a promise (function) to detect the route change? Something like $routeChangeSuccess in Angular 1. If I use router.config I can do it easily.

**Comment by btford** [comment]
You can use `router.subscribe`

**Comment by danicomas** [comment]
@btford I have changed for this:

```js
@Component({
 ...
  appInjector: [routerInjectables, bind(LocationStrategy).toClass(HashLocationStrategy)]
})
...
@RouteConfig([
  { path: '/',  redirectTo: '/home' },
  { path: '/home', as: 'home', component: Home },
  { path: '/home1', as: 'home1', component: Home1 }
])
// Component controller
class MyAppComponent {
  constructor( @Inject(Router) router, @Inject(Location) location) {
    this.router = router;
    this.location = location;
...
```

And I do this:
- Nav url http://locahost:8080/ and enter -> and this redirect to /#/home and the component Home is loaded (OK)
- if you click to an hyperlink with route-link this redirect to /#/home1 (OK)

But if I do this:
- Nav url http://locahost:8080/#/home and enter the home component is not loaded (KO)
- http://locahost:8080/#/home1 the home1 and enter home1 component is not loaded (KO)

It worked better when I had this:

```js
this.router.config(
      [{ path: '/',  redirectTo: '/#/home' },
     { path: '/#/home', as: 'home', component: Home },
     { path: '/#/home1', as: 'home1', component: Home1 }]).then((_) => router.navigate(path);
```

**Comment by danicomas** [comment]
Sorry @btford  I had this problems in the version 2.0.0-alpha.28. I have updated to 2.0.0-alpha.31 and it works well all the things that I said in the las comment.
