### ISSUE TITLE
[ivy] ERROR in Expected array when reading property exports using concat()

### ISSUE THREAD

**Issue by maltehol** [angular/angular#29835]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/cli ?

### Is this a regression?

 NO

### Description
When using .concat() to concat two arrays in the `exports` field of a Module, ivy throws an 
`ERROR in Expected array when reading property exports`

The compiled version of the package `@swimlane/ngx-charts` contains such an concat() that seems to prevent ivy to recognize the export variable as array. 
Removing `concat()` and merge the arrays by hand resolves the error. 
Since `concat()` returns an `Array` itself, I see the issue in angular / ivy, not in the ngx-charts package.

The line of the source: https://github.com/swimlane/ngx-charts/blob/4d9f58b1b8ec3127b408964c373613ee961dee71/src/common/chart-common.module.ts#L61

## 🔬 Minimal Reproduction

Checkout: https://github.com/maltehol/ivy-ngx-charts
and run ng build

## 🔥 Exception or Error
<pre><code>
ERROR in Expected array when reading property exports
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.0-beta.11
Node: 11.13.0
OS: win32 x64
Angular: 8.0.0-beta.11
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-beta.11
@angular-devkit/build-angular     0.800.0-beta.11
@angular-devkit/build-optimizer   0.800.0-beta.11
@angular-devkit/build-webpack     0.800.0-beta.11
@angular-devkit/core              8.0.0-beta.11
@angular-devkit/schematics        8.0.0-beta.11
@angular/@types                   <error>
@angular/events                   <error>
@angular/rxjs                     <error>
@angular/tslib                    <error>
@angular/typescript               <error>
@ngtools/webpack                  8.0.0-beta.11
@schematics/angular               8.0.0-beta.11
@schematics/update                0.800.0-beta.11
rxjs                              6.4.0
typescript                        3.3.4000
webpack                           4.29.6

</code></pre>

**Comment by yantrab** [comment]
I have the same with 8.0.0-rc.1

**Comment by JoostK** [comment]
@yantrab cold you share a repo with reproduction?

**Comment by yantrab** [comment]
Yes,
```
git clone -b  update-angular  https://github.com/yantrab/nest-angular.git

 cd .\nest-angular\ && npm i

 cd .\client\ && ng serve
```

after very long time i get `ERROR in Expected array when reading property exports`



and in [this ](https://github.com/yantrab/yangular) repo i get:
```
ERROR in Unable to write a reference to TableComponent in C:/Users/yantr/Desktop/mat-virtual-table/projects/mat-virtual-table/src/lib/table.component.ts from C:/Users/yantr/Desktop/mat-virtual-table/projects/mat-virtual-table/src/lib/table.module.ts
i ｢wdm｣: Failed to compile.
i ｢wdm｣: Compiling...
```

**Comment by JoostK** [comment]
@yantrab Thank you so much, that has been really helpful. The message `Expected array when reading property exports` is produced because at this moment, usage of tslib's `__spread` function usage as seen in `node_modules/mat-virtual-table/fesm5/mat-virtual-table.js#TableModule` is not recognized and prevents static analysis of the `NgModule.exports` value, which is required for the compiler to work. I created FW-1298 to track this.

I did not look into your second problem, could you perhaps open a new issue for that?

**Comment by yantrab** [comment]
Thanks.
In fact, the second repo is 'mat-virtual-table'. that i knew it has a 'concat' in imports, and I tried to reduce the problem. I'll open a new one for this.

By the way, how can you get a more detailed log about the error?
And what about the time that it is takes, is that reasonable?

**Comment by JoostK** [comment]
@yantrab I now spotted the `concat` in the imports, I am not sure however if that is causing the problem as 1.4.2 of `mat-virtual-table` has that `__spread` thing going on. I notice the `__spread` call has since been removed in 1.4.3. Are you still experiencing issues with that?

Regarding the performance: the initial time (with fresh `node_modules`) that you compile your Angular app with Ivy enabled is quite slow because ngcc (Angular Compatibility Compiler) will run AOT compilation for NPM libraries. This however is a one-time process per library installation, so subsequent runs should be quite a bit faster.

**Comment by blackholegalaxy** [comment]
@JoostK we can confirm using spread syntax in module declaration triggers the error `ERROR in Expected array when reading property declarations` each time. 
```
exports: [
    ...gmdModules,
    ScrollDispatchModule,
  ],
```

It's quite useful to be able to use spread syntax when importing/exporting/declaring large number of modules/components.

**Comment by JoostK** [comment]
@blackholegalaxy could you share the generated ES5 code of that module? If it uses `tslib.__spread(gmdModules)` it is not currently supported.

**Comment by blackholegalaxy** [comment]
It seems to be compiled into `concat()` but I will look deeper to find a `__spread`. 

The fact is the error doesn't point where it failed its hard to debug

**Comment by JoostK** [comment]
@blackholegalaxy Could you share the code, even for the `concat()`?
