### ISSUE TITLE
ng-for and ng-if break with transformer generated change detectors

### ISSUE THREAD

**Issue by jakemac53** [angular/angular#2984]
https://github.com/angular/angular/pull/2981 provides a test which fails. https://gist.github.com/jakemac53/675fdedad5ce469d292f is an simple example which will fail under the transformer.

**Comment by vsavkin** [comment]
The actual issue:

The DOM adapter used by the compiler used in the DirectiveProcessor transformer incorrectly reflects on the elements. The adapter cannot detect properly what properties a DOM element has. This problems manifest via change detection.

**Comment by matanlurey** [comment]
Is anyone tackling this? @tbosch mentioned something about registering a Schema last week.

**Comment by vsavkin** [comment]
@matanlurey we'll figure out a plan today. It looks like providing a schema would be a proper solution, but it may take some time. We may have to provide a temporary solution to unblock @jakemac53.

**Comment by yjbanov** [comment]
Assigned to @tbosch as he is already looking into the reflection issue.

**Comment by tbosch** [comment]
Have a PR up, should go in today.

**Comment by kevmoo** [comment]
Verified on 97ef1c2 with Dartium. Awesome! :metal:

**Comment by matanlurey** [comment]
:+1: looks good thanks guys.

**Comment by jakemac53** [comment]
todomvc works with the transformer now as well :)
