### ISSUE TITLE
Secondary outlet error : Cannot activate an already activated outlet

### ISSUE THREAD

**Issue by LeMalandrin** [angular/angular#29840]
Hello,
I'm encountering a problem with router-outlet. 
I have two outlets : the main app router outlet, and a secondary outlet named 'administration'.

When I want to navigate through any administration link at start, it works fine. But next time, when I try to navigate, angular throws this error message :
**Cannot activate an already activated outlet**

I have made a stackblitz to share with you : https://stackblitz.com/edit/angular-zxjslv
Maybe I made a mistake somewhere...

Thank you all :)

**Comment by LeMalandrin** [comment]
Someone has found a solution for me on stackoverflow : https://stackblitz.com/edit/angular-osnnd4?file=src%2Fapp%2FComponents%2FAdministration%2Fadministration%2Fadministration.component.ts
I have to manually desactivate the outlet...

This issue seems to be related to lazyloading routing and named outlets...does some fix planned in next release ?

Thanks :)

**Comment by jasonaden** [comment]
It would be great to link the StackOverflow solution you found. Then we can see if there's a fix planned for this.

**Comment by atscott** [comment]
Duplicate of #20694
