### ISSUE TITLE
ng_module can consume files without declaring the dependency

### ISSUE THREAD

**Issue by jbedard** [angular/angular#29857]
### Affected Package
`@angular/bazel`

### Description
`ng_module` should require declaring dependencies on all assets (`.css`, `.html`, ...) using `ng_module(assets)`. Referencing a file not declared as a dependency should fail the build.

It seems like `.html` files (and maybe more?) are accessible to `ng_module` even when the dependency was not properly declared. As a result the cache will not be invalided when this undeclared dependency changes, `ibazel` will not reload etc.

### Minimal Reproduction
https://github.com/jbedard/ng_package-material/tree/ng-module-html-not-in-assets

The [last commit](https://github.com/jbedard/ng_package-material/commit/c921508d3d7532d4c565d084f83acd345ce38329) (removing the `ng_module(name = "banner")` => `banner.html` dependency) should make `banner.html` inaccessible and cause the `ng_module` build to fail.

@gregmagolan

**Comment by alexeagle** [comment]
I think this should be fixed as part of moving to `ts_library` rule for Ivy. tsc_wrapped already has the logic to hide files via the CompilerHost which were not declared as inputs.

**Comment by alxhub** [comment]
Closing as obsolete - the Bazel builder and associated CLI functionality are deprecated and no longer supported.
