### ISSUE TITLE
remove 0 from src/app/user.service.0.ts from Singleton Service exampe

### ISSUE THREAD

**Issue by santoshyadav198613** [angular/angular#29862]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...
https://angular.io/guide/singleton-services contains the service example which has file name as src/app/user.service.0.ts , we need to rename it as src/app/user.service.ts as it is not the recommended file name format.

### What's the affected URL?**
 https://angular.io/...

### Expected vs Actual Behavior**

src/app/user.service.0.ts should be renamed as src/app/user.service.ts

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by AlekNiebla** [comment]
Hey can I take on this Issue?
