### ISSUE TITLE
Add a detailed example for ErrorHandler implementing any service

### ISSUE THREAD

**Issue by santoshyadav198613** [angular/angular#29863]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...
Currently there is no example on Angular.io describing the implementation of ErrorHandler, as it is littler bit different, how we use the services when we use ErrorHandler.

Add one example showcasing the same, to increase the usage of ErroHandler

### What's the affected URL?**
 https://angular.io/...

### Expected vs Actual Behavior**

Official doc should have an example for ErrorHandler implementation.

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by alimemonzx** [comment]
@santoshyadav198613 did you look at [this](https://angular.io/api/core/ErrorHandler#description) page?

**Comment by santoshyadav198613** [comment]
Yes i did, but it does not mention that we can not inject services directly into constructor as services are not available when this service is used. The only way to get the service is using Injector.

**Comment by trotyl** [comment]
> but it does not mention that we can not inject services directly into constructor as services are not available when this service is used. The only way to get the service is using Injector.

@santoshyadav198613 Could you please make an StackBlitz example? I don't find any issue in doing that:

https://stackblitz.com/edit/angular-efaezh?file=src%2Fapp%2Fapp.module.ts

Also the aio site is doing that as well: 

https://github.com/angular/angular/blob/ef853367194c77f505a0705e45f5670725873da1/aio/src/app/shared/reporting-error-handler.ts#L9-L14

It's most likely you encountered an unintended circular dependency issue similar to something like "making immediate HTTP request in `HttpInterceptor` constructor" which would always break as logically not feasible.

**Comment by santoshyadav198613** [comment]
> which would always break as logically no
sure let me create one.

**Comment by santoshyadav198613** [comment]
Closing it, as looks like it is sorted now.
