### ISSUE TITLE
Add an example to create multi provider in DI section

### ISSUE THREAD

**Issue by santoshyadavdev** [angular/angular#29860]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...
Doc contains the example to create a valueProvider, we need to add an example to add multiProvider.

### What's the affected URL?**
 https://angular.io/...

https://angular.io/guide/dependency-injection-providers#value-providers

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by kapunahelewong** [comment]
Thank you for the PR for this, @santoshyadav198613! Are you planning on continuing your efforts on it? I've also added this to our docs list so we can track it.

Status: docs team, the PR for this, https://github.com/angular/angular/pull/29909, is in progress, though may have fallen to the wayside. We can still revive it and help it keep moving, if @santoshyadav198613 would like to do so (@santoshyadav198613, if you have moved on to other things and would rather not go back to this PR, that's ok too. A docs team member could just take it over, if you'd like. Totally up to you. 😊)

**Comment by santoshyadav198613** [comment]
I will take it, no issues.

**Comment by kapunahelewong** [comment]
Oh thank you, @santoshyadav198613! Please feel free to ping me if I can help in any way.

**Comment by dylhunn** [comment]
Associated PR had no response.
