### ISSUE TITLE
After angular 7.2.12 upgrade - Getting webpack/lib/Template error

### ISSUE THREAD

**Issue by nitz88** [angular/angular#29865]
# 🐞 bug report

### Affected Package
@angular-devkit

### Is this a regression?

Did this behavior use to work in the previous version? : Yes. Before the update, there was no issue.

### Description

After we upgraded our application to Angular 7.2.12, now ng serve & ng build --prod will give below error.

## 🔥 Error
<pre><code>
Cannot find module 'webpack/lib/Template'
Error: Cannot find module 'webpack/lib/Template',
aft Function.Module._resolveFilename (module.js:547:15)
...
...
at Object,<anonymous> (C:\Code\MyProj\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models\webpack-config\browser,js:15:36)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.8
Node: 8.11.3
OS: win 32 ia32
Angular: 7.2.12
... animation, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package version
@angular-devkit/architect 0.13.8
@angular-devkit/build-angular 0.13.8
@angular-devkit/core 7.3.8
@angular-devkit/schematics 7.3.8(cli-only)
@angular/cdk 7.3.6
@angular/cli 7.3.8
@angular/material 7.3.6
@angular/material-moment-adaptor 7.3.6
@schemantics/angular 7.3.8(cli-only)
@schemantics/update 0.13.8(cli-only)
rxjs 6.3.3
typescript 3.1.6
</code></pre>

**Comment by nitz88** [comment]
@ericmartinezr sorry what I am missing here? you reacted so may be trying to understand the issue.

**Comment by ericmartinezr** [comment]
@nitz88 you're missing the reproduction step you deleted from the issue template.

**Comment by nitz88** [comment]
@ericmartinezr there is no reproduction steps, we just updated our normal app to new version of angular then we got this issue.

**Comment by ericmartinezr** [comment]
It's impossible without reproduction. Also I'd say this should go in cli's repo https://github.com/angular/angular-cli 👍

**Comment by benlesh** [comment]
I'm sorry but we can't reproduce the problem you are reporting. We require that reported issues have a minimal reproduction that showcases the problem.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template that include info on how to create a reproduction using our template.
