### ISSUE TITLE
 By Updating queryParams to null on same route using router.navigate, unwanted fragments get added into url or qureyParams does not get update.

### ISSUE THREAD

**Issue by phutaneVinayak** [angular/angular#29870]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 Don't know.

### Description
I want to clear qureyParams from route. so i just set queryParams: null, and update route using router.navigate, but sometimes broswer load same qureyParams with extra fragments added into route. which is not a normal routing beheviour. not correct route.

## 🔬 Minimal Reproduction
i will try, but lot of work to complete so i  post what is done in minimal reproduction so you all guys get idea that what i am doing.
1. trip-routing-module.ts
     this is child module routing.
     <pre>
      <code>
        Routes = [
            path: '',
            component: myComponentName,
            resolve: {data: myResolverName },
            runGuardsAndResolvers: 'paramsOrQueryParamsChange'
        ]
      </code>
    </pre>
'myComponentName ' component has resolver which is 'myResolverName', that read url params and fragments. base on that it make phone call to daddy get new data.

2. MyComponent.ts
----INTRO ---
Basically, this component uses to display all trips list and filters coming from daddy.
by updating filters, it's value get updated into qureyParams to remember sweet user choice.
the user can clear out all filters value (set to default ) by click clear selection button. the main problem happening here.
<pre>
    <code>
        clearSelection() {
            // asume all array | string etc set to empty. 
            this.router.navigate(
            [],
            {
                relativeTo: this.activeRoute,
                queryParams: null,
                preserveFragment: false
            });
        }
    </code>
</pre>

## 🔥 Exception or Error
Not getting any exception. I think it will behaviour issue or something else you guys decide it.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

6.1
</code></pre>

**Anything else relevant?**
not browser sepcific issue. 

I am submitting this issue after searching whole two days for help on online. but none of hacks, workaround etc worked for me. so i decide to post this issue. if i miss something please point it out, because i always learn new things.

**Comment by jasonaden** [comment]
Thanks for the issue. I can't see what would be causing this in the current codebase. But 6.1 is a couple versions behind. I think you should re-test with a current version and submit a new issue if it's still a problem.

Also, please provide a reproduction when you send the new issue. Then we can test to see what's causing it.
