### ISSUE TITLE
Problem in Angular "my-app" instructions in Windows, try #2

### ISSUE THREAD

**Issue by David263** [angular/angular#29878]
# 📚 Docs or angular.io bug report

### Description

On web page https://angular.io/guide/quickstart, there are instructions

```
Open ./src/app/app.component.ts. 
Change the title property from 'my-app' to 'My First Angular App'.
```

On Windows this fails because the example was created by default (following instructions) in folder C:\Windows\System32\my-app, which cannot be written because it is in the protected Windows directory tree.

### What's the affected URL?**
https://angular.io/guide/quickstart

### Reproduction Steps**
Follow the instructions given on Windows 10.

### Expected vs Actual Behavior**

Expected: no problem
Actual: cannot edit the file ./src/app/app.component.ts

## 📷Screenshot
Not needed: standard file system error on trying to save edited file

## 🔥 Exception or Error
<pre><code>
standard file system error on trying to save edited file
</code></pre>

**Comment by David263** [comment]
When a command line dialog box is created in Windows, the initial folder is set to C:\Windows\System32, a protected system folder. There were no instructions to change to a different folder. In fact, the instructions **actually created the Angular example in C:\Windows\System32**, which is a very bad practice.

**Comment by Airblader** [comment]
AFAIK this is only the default cwd if you start the terminal with administrator rights — which definitely is a bad idea (and not suggested by the docs).

Nonetheless, it probably wouldn't hurt to add a hint that the command will create a folder in the cwd and that the user should first cd to whichever location they prefer first.

**Comment by kapunahelewong** [comment]
Hi @Airblader or @David263 would either of you like to submit a PR for this? If not, I can. :)

**Comment by Airblader** [comment]
I'm not planning on doing it, I also don't use Windows, so go ahead!

**Comment by kapunahelewong** [comment]
@David263 I don't have Windows either, but am happy to collaborate. Are you interested in working on  a PR (together or on your own)?

**Comment by santoshyadav198613** [comment]
Hi @kapunahelewong ,

I would be happy to do it if he says no.

**Comment by kapunahelewong** [comment]
Thanks @santoshyadav198613 :)

**Comment by santoshyadav198613** [comment]
Hi @kapunahelewong ,
This is related to V7 documentation, as new getting started is updated to use StackBlitz, no one will face this issue ever. Do we still need to update the doc for V7?

**Comment by kapunahelewong** [comment]
Oh, good point @santoshyadav198613. Hey @brandonroberts, what are your thoughts?

**Comment by brandonroberts** [comment]
This may still be an issue with those going through the local environment setup on Windows or those who still want to do the getting started, but locally.

**Comment by santoshyadav198613** [comment]
Hi @brandonroberts  and @kapunahelewong ,

added a note for Windows users, please check and suggest changes.
