### ISSUE TITLE
Problem in Angular "my-app" instructions in Windows

### ISSUE THREAD

**Issue by David263** [angular/angular#29877]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by David263** [comment]
Huh? Why was an empty Issue created? Seems like a bug in the Issue submission process.

**Comment by Airblader** [comment]
You can just close this issue yourself since you created a separate one instead.
