### ISSUE TITLE
Which will be the best way to include messages in the form validators?

### ISSUE THREAD

**Issue by danicomas** [angular/angular#2988]
In Angular 1.X we can have a template (in other file) with all the error validators:

```html
<script id="templates/form-errors.html" type="text/ng-template">  
  <div class="form-error" ng-message="required">This field is required.</div>
  <div class="form-error" ng-message="minlength">This field is must be at least 5 characters.</div>
  <div class="form-error" ng-message="maxlength">This field is must be less than 50 characters</div>
</script>  
```

```html
<div class="form-errors" ng-messages="signinForm.username.$error" ng-messages-include="templates/form-errors.html"> 
</div> 
```

Which will be the way in Angular 2? I haven't found nothing in the source code @jeffbcross @mhevery @jeffbcross @pkozlowski-opensource

**Comment by plalx** [comment]
I've suggested an idea https://github.com/angular/angular/issues/2240. The important point is that broken rules carries enough meta-data. Once this is done it opens the door to much more powerful error reporting strategies.

**Comment by danicomas** [comment]
I didn't see this example: https://github.com/angular/angular/blob/c899b0a74c99ab29e50762aa68d8a0f3bde41c5c/modules/examples/src/template_driven_forms/index.ts#L101
