### ISSUE TITLE
Enable fullTemplateTypeCheck by default

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [angular/angular#29882]
# 🚀 feature request

### Relevant Package

This feature request is for @angular/cli (not sure)

### Description
I have tried including some library but they have some template bugs which they haven't caught.
I have this enabled and so I have to go through the whole issue/fix/new version process with them. Why?

### Describe the solution you'd like
Enable the option by default. Why would anyone responsible want to avoid doing this? At least make it somehow default in the testing process so that before people publish to npm this gets run.

### Describe alternatives you've considered
I have considered not complaining or forking the repo and fixing the issues for myself.

**Comment by Airblader** [comment]
This is the wrong repository as the flag for new projects must be set by the Angular CLI, so this should go to @angular/angular-cli. However, no need to post there as this is already the new default:

https://github.com/angular/angular-cli/blob/a13924364482cbf9a61ba4c3ac1171d3feaf8034/packages/schematics/angular/library/files/tsconfig.lib.json.template#L17

**Comment by benlesh** [comment]
As @Airblader pointed out, this is an issue with Angular-CLI and it already seems to be resolved. Thank you for the report, though! Hopefully the update to Angular-CLI resolves your issue.
