### ISSUE TITLE
Won't get build passed when generic type parameter exists in constructor

### ISSUE THREAD

**Issue by ah787264643** [angular/angular#29899]
First, the code:
```
export class BasicParent<T extends BaseService>{
  constructor(protected service: T, private injector?: Injector ) {
  }
}
```
this code won't build, say `ERROR in : Can't resolve all parameters for BasicParent in /app/class/basic-parent.ts: (?, [object Object]).
`
such generic parameter can not be used in constructor in Angular?

**Comment by trotyl** [comment]
In DI concept, the code:

```typescript
@Injectable()
class MyInjectable {
  constructor(whatever: Whatever) {
    console.log(whatever)
  }
}
```

is equivalent to:

```typescript
@Injectable()
class MyInjectable {
  constructor(injector: Injector) {
    const whatever = injector.get(Whatever)
    console.log(whatever)
  }
}
```

Namely `Whatever` here **must be a value, not a type**. And clearly the `T` in your example is not a value, and you can never pass it to `Injector`.

**Comment by ah787264643** [comment]
> In DI concept, the code:
> 
> ```ts
> @Injectable()
> class MyInjectable {
>   constructor(whatever: Whatever) {
>     console.log(whatever)
>   }
> }
> ```
> 
> is equivalent to:
> 
> ```ts
> @Injectable()
> class MyInjectable {
>   constructor(injector: Injector) {
>     const whatever = injector.get(Whatever)
>     console.log(whatever)
>   }
> }
> ```
> 
> Namely `Whatever` here **must be a value, not only a type**. And clearly the `T` in your example is not a value, and you can never pass it to `Injector`.

In my constructor, `service` is definitely a value and `T` is a type, same as your constructor. `T` is a generic type which is the only difference compared to type `Whatever`. Is it too strict of `ng build --prod` to constructors ?

**Comment by trotyl** [comment]
> In my constructor, `service` is definitely a value and `T` is a type, same as your constructor.

No, the `BaseService` is only a type here (even it can be used as value), you can checked the emitted JavaScript, there's no trace of `BaseService`.

**Comment by ah787264643** [comment]
> > In my constructor, `service` is definitely a value and `T` is a type, same as your constructor.
> 
> No, the `BaseService` is only a type here (even it can be used as value), you can checked the emitted JavaScript, there's no trace of `BaseService`.

BaseService following the class name is just used to indicate the scope type  T, I guess it may be gone after compiling (I call it compiling... ), is this 'bug' of javascript ? 
It is OK to do so in Java, and it is OK for idea with no warning at all...
Is there a way to make it work?

**Comment by trotyl** [comment]
> BaseService following the class name is just used to indicate the scope of type T, I guess it may be gone after compiling (I call it compiling... ), is this 'bug' of javascript ?

It's the expected behavior, the constructor parameter types (technically also decorated property types) are exception set by [`emitDecoratorMetadata`](http://www.typescriptlang.org/docs/handbook/decorators.html#metadata) option in TypeScript. The emission is very limited and only works with direct class reference:

https://github.com/Microsoft/TypeScript/search?q=emitDecoratorMetadata&type=Issues

**Comment by alxhub** [comment]
Yep, this is the expected behavior.

When Angular is compiling `BasicParent`, it needs to know what type to inject for the first constructor parameter. `T` doesn't suffice - it needs to either have a concrete class or an `@Inject` with a DI token.

**Comment by ah787264643** [comment]
> Yep, this is the expected behavior.
> 
> When Angular is compiling `BasicParent`, it needs to know what type to inject for the first constructor parameter. `T` doesn't suffice - it needs to either have a concrete class or an `@Inject` with a DI token.

It works , **`@Inject` with a DI token**, thanks a lot guys. @trotyl @alxhub
