### ISSUE TITLE
Dynamic Angular Router, change state params on same route

### ISSUE THREAD

**Issue by radvansky-tomas** [angular/angular#29891]
Hi everyone, I tried to follow docs and example, but I have no idea how to reload same route with different params, if you have idea what route you are in.

Described here:
https://stackoverflow.com/questions/55644532/how-to-change-route-state-params-for-current-route-using-router-service

But basically lets say that your convention is

/page/:appId/other-parts-of-url/:otherids/etc

And you want to change appId from some global scope. So you can this.router to access current Angular Router instance, and you want to call .navigate() method and load same route but with different appId param.

Any idea, how to do such simple thing ? I am not interested in string parsing url techniques or other "hacky" ideas, thx

**Comment by radvansky-tomas** [comment]
Hack solution looks like this:

```
  const url = this.router.routerState.snapshot.url.toLowerCase();
      const regex = /(?<=\/pages\/)([^/]*)/gm;

      if (url.includes('/pages/') && !url.includes('/app-management') && !url.includes('/profile')) {
        //replace appId
        console.log(url.replace(regex, "123"))
      }
```

If you look at the code you will realise that from URL i cannot really access state params by its name and I have to make hard-coded exceptions etc to change state param.

I am quite sure that has to be a method which can parse current URL with params. Then change param and pass url back to router.

**Comment by radvansky-tomas** [comment]
So lets ask contributors then: @jasonaden @vsavkin @vicb @dz

**Comment by jasonaden** [comment]
@radvansky-tomas Thanks, but I think the reason this issue hasn't been looked at is it doesn't follow the issue guidelines. It's more of a request for help on a particular issue, which should be directed to StackOverflow. I will close this issue, and ask that you submit the question there.

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
