### ISSUE TITLE
Lazy load BrowserModule has already been loaded

### ISSUE THREAD

**Issue by soyjuanmedina** [angular/angular#29906]
# 🐞 bug report

### Affected Package
import { BrowserModule } from '@angular/platform-browser';

### Description

I have two moduels: AppModule and UserModule, and a LoadingComponent use in both.

I try to export it from AppModule to UserModule

```
@NgModule({
  declarations: [
   ...,
    LoadingComponent
  ],
  imports: [
BrowserModule,,
...
  ],
  providers: [...
  ],
  bootstrap: [AppComponent],
  exports: [
    LoadingComponent
  ]
})
export class AppModule { }
```

And import in UserModule

```
@NgModule({
  imports: [
    AppModule,
    CommonModule,
...
  ],
  declarations: [
   ...
  ]
})
export class UserModule { }
```

But I recibe an error in console:

> Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

But as you can see I only import BrowserModule in AppModule, and if I don't import AppModule in UserModule I have an error

> Error: Template parse errors:
> 'loading-component' is not a known element:
> 1. If 'loading-component' is an Angular component, then verify that it is part of this module.

**Comment by mlc-mlapis** [comment]
@soyjuanmedina ... as described in docs on https://angular.io ... create the third module ... `SharedModule`  and move the `LoadingComponent` into. Then import the `SharedModule` to both `AppModule` and `UserModule`.

**Comment by soyjuanmedina** [comment]
Thanks a lob @mlc-mlapis, it's works.

And sorry if I post this like a bug.... I was looking for a solve but don't find anything.
