### ISSUE TITLE
Multi-language support for hyperlinks in i18n

### ISSUE THREAD

**Issue by AsrarMemon** [angular/angular#29903]
Hello,
We are developing a progressive app web using Angular 7.
The application must support multiple languages (around 18). For providing multi-language support, we are using Angular's Internationalization (i18n) tools.

There are few hyperlinks in our application which should open different links based on the language selected.
For example:
Link for FR language:
`<a class="nav-link" href="https://www.essilor.com/fr/">
	ACCOUNT
</a> 
`

Link for EN language:
`
<a class="nav-link" href="https://www.essilor.com/en/">
 ACCOUNT
</a> 
`

How can we avoid writing 18 different links for each and every language that we support. Does i18n provide any mechanism for the same?

Waiting for an urgent help here...

Thanks

**Comment by dawidgarus** [comment]
Inject LOCALE_ID to your component and you can use it as variable in template.

**Comment by ocombe** [comment]
I think that @dawidgarus's solution is the best and easiest to implement.

**Comment by ocombe** [comment]
Closing this because there hasn't been any new activity. Let me know if you want me to reopen it.
