### ISSUE TITLE
RFC: AsyncPipe doesn't necessarily need WrappedValue

### ISSUE THREAD

**Issue by trotyl** [angular/angular#29927]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common

### Is this a regression?

No, it's likely a design failure from the very beginning.

### Description

 A clear and concise description of the problem...

In [`WrappedValue`](https://angular.io/api/core/WrappedValue) documentation, it's saying:

> Indicates that the result of a [`Pipe`](https://angular.io/api/core/Pipe) transformation has changed even though the reference has not changed.

But inside [`AsyncPipe`](https://angular.io/api/common/AsyncPipe) whether or not returning an `WrappedValue` is fully based on reference changed or not:

https://github.com/angular/angular/blob/9147092a156203d46cd1c865e06fa72a1e2d4137/packages/common/src/pipes/async_pipe.ts#L106-L111

It will only wrap the first changed value into `WrappedValue`, all the subsequent unchanged values will retain unwrapped, even changing the observable reference won't make any effect:

https://stackblitz.com/edit/typescript-bzkarv

Otherwise, even the same value being re-emitted many times during change detection, it won't be wrapped and no error is reported:

https://stackblitz.com/edit/angular-kqkpym?file=src%2Fapp%2Fapp.component.ts

I don't know what's the difference if `AsyncPipe` just return the unwrapped value and let the change detector to check it. Please correct me if I am wrong.

And then, what's the meaning of `WrappedValue` as not need by Angular itself?

## 🔬 Minimal Reproduction

Linked above.

## 🔥 Exception or Error
<pre><code>N/A
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>N/A
</code></pre>

**Anything else relevant?**

The question was found when digging into https://github.com/angular/angular/pull/22305.

**Comment by mlc-mlapis** [comment]
@trotyl ... yep, I remember this problem was discussed a year ago: https://github.com/angular/angular/issues/23933

**Comment by kingecg** [comment]
sometimes, it would cause error "Expression has changed after it was checked". when I traced into code, I found it was comparing Wrapped value instance with my original value.
