### ISSUE TITLE
Docs: Reactive forms guide lists incorrect fields

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#29925]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

In the [reactive forms guide](https://angular.io/guide/reactive-forms#step-2-grouping-the-nested-form-in-the-template), the sentence tells you to add fields:

```
Add the `address` form group containing the `firstName` and `lastName` fields to the `ProfileEditor` template.
```

It should tell you to add the remaining fields instead.

```
Add the `address` form group containing the `street`, `city`, `state`, and `zip` fields to the `ProfileEditor` template.
````

Line 233 should be updated here https://github.com/angular/angular/blob/master/aio/content/guide/reactive-forms.md

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by iliesaithamouda** [comment]
Can i handle this Issue ?

**Comment by brandonroberts** [comment]
@iliesaithamouda Sure

**Comment by iliesaithamouda** [comment]
ok thank you. can you please jsut help me to know how to create a branch ? it seems that i can't do it as usual on my repos... sorry, i'm kind of new and i wanted to contribute.
i read the guideline but there is no mention of how to create branchs

**Comment by iliesaithamouda** [comment]
PR: https://github.com/angular/angular/pull/30007
