### ISSUE TITLE
Fix type in deployment#differential-loading

### ISSUE THREAD

**Issue by santoshyadav198613** [angular/angular#29935]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

As a result, this produces a two builds, with differential loading enabled

Should be 
As a result, this produces two builds, with differential loading enabled

### What's the affected URL?**
 https://pr29932-2368833.ngbuilds.io/guide/deployment#differential-loading

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by brandonroberts** [comment]
Thanks @santoshyadav198613, fixed. You can just comment directly in the PR if its under review.
