### ISSUE TITLE
Provide atlternate to cp command in schematics guide, as cp is not supported on windows

### ISSUE THREAD

**Issue by santoshyadavdev** [angular/angular#29952]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...
  "copy:collection": "cp schematics/collection.json ../../dist/my-lib/schematics/collection.json",

the above command exists in schematics guide, the problem here is "cp" is not supported on windows, need to provide alternate to this command for windows users.

### What's the affected URL?**

https://angular.io/guide/schematics-for-libraries#configure-the-new-schematic

### Expected vs Actual Behavior**

download the library schmatic project from https://angular.io/guide/schematics-for-libraries#configure-the-new-schematic and run "npm run build" on windows post npm install.

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by DustinMEastway** [comment]
I will take this one unless someone thinks that it is too tough for a first issue.

**Comment by DustinMEastway** [comment]
Should I add to the docs to use copy instead of cp or would it be better to go with a cross platform option like ncp?

**Comment by santoshyadav198613** [comment]
I think something which is cross platform will be better.

**Comment by DustinMEastway** [comment]
I like the cross platform option as well, I was just not sure if we wanted to have them install a npm dependency.

**Comment by Chan4077** [comment]
I've actually created a PR on this a month ago: #29505

**Comment by DustinMEastway** [comment]
@Chan4077 Thank you for letting us know. I will close my pull request since it is duplicated work. Could you edit the body of your pull request to close this issue upon completion?
https://github.blog/2013-05-14-closing-issues-via-pull-requests/

**Comment by Splaktar** [comment]
@DustinMEastway I think that your PR is still valid as PR https://github.com/angular/angular/pull/29505 still relies upon the `find` and `rsync` commands which may not be compatible on Windows.

It might be helpful in your PR to mention the Linux subsystem for Windows 10.

**Comment by DustinMEastway** [comment]
@Splaktar Would you like me to open my pull request again? As for adding information about the Linux subsystem for Windows 10, are you wanting that in place of or in addition to recommending ncp?

**Comment by Splaktar** [comment]
@DustinMEastway I would make it in addition to your mention of `copy` and `ncp`. I would probably put both sentences in a new paragraph.

**Comment by kapunahelewong** [comment]
Hey @DustinMEastway, would you tag me when you re-open your PR so I can stay in the loop? 🙏🏼

**Comment by jessicajaniuk** [comment]
Looks like this issue has been fixed with #30966.
