### ISSUE TITLE
BrowserAnimationsModule ivy compile error

### ISSUE THREAD

**Issue by jponeill** [angular/angular#29960]
# 🐞 bug report
A newly created angular-cli 8.0.0-beta.15 ivy project gives the following error after adding BrowserAnimationsModule to app.module imports

ERROR in src/app/app.module.ts(6,9): error TS2305: Module '"../../node_modules/@angular/platform-browser/animations"' has no exported member 'BrowserAnimationsModule'.
 
### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?
Yes

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
Using Angular CLI: 8.0.0-beta.15

1) ng new bugProj -enable-ivy
2) Add BrowserAnimationsModule to imports in app.module.ts
3) type ng build -configuration production
... get ERROR in src/app/app.module.ts(6,9): error TS2305: Module '"../../node_modules/@angular/platform-browser/animations"' has no exported member 'BrowserAnimationsModule'.
 

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

ERROR in src/app/app.module.ts(6,9): error TS2305: Module '"../../node_modules/@angular/platform-browser/animations"' has no exported member 'BrowserAnimationsModule'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.0-beta.15
Node: 10.12.0
OS: darwin x64
Angular: 8.0.0-beta.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-beta.15
@angular-devkit/build-angular     0.800.0-beta.15
@angular-devkit/build-optimizer   0.800.0-beta.15
@angular-devkit/build-webpack     0.800.0-beta.15
@angular-devkit/core              8.0.0-beta.15
@angular-devkit/schematics        8.0.0-beta.15
@angular/@types                   <error>
@angular/cli                      8.0.0-beta.15
@angular/events                   <error>
@angular/rxjs                     <error>
@angular/tslib                    <error>
@angular/typescript               <error>
@ngtools/webpack                  8.0.0-beta.15
@schematics/angular               8.0.0-beta.15
@schematics/update                0.800.0-beta.15
rxjs                              6.4.0
typescript                        3.4.3
webpack                           4.29.6
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
Thank you for trying out Ivy! This seems to be related to #29939, I'll try to have a look at it over the weekend.

**Comment by HitomiTenshi** [comment]
@JoostK I dug a little deeper and it seems that if you have `"target": "es2015"` in your `tsconfig.app.json`, the command `ng build --prod` will overwrite `.d.ts` files in `./node_modules` in a weird way, essentially removing `BrowserAnimationsModule` from `./node_modules/@angular/platform-browser/animations/animations.d.ts`.

Recovering from that is impossible. You will need to delete the `node_modules` folder and run `npm install` again to fix it.

If you set `"target": "es5"` in your `tsconfig.app.json`, then this bug does not happen.

My Setup:
- Windows 10
- Node 11.14.0
- Using the same angular versions as OP

**Comment by JoostK** [comment]
@HitomiTenshi thanks for your insights! It took me quite a while to find where the overwrite action originated from, eventually finding that it was actually ngcc at fault. PR available in #30020
