### ISSUE TITLE
Documentation for :ng-deep is misleading / incomplete

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#29967]
### Description

The documentation for ng-deep states

> Component styles normally apply only to the HTML in the component's own template.
> 
> Use the /deep/ shadow-piercing descendant combinator to force a style down through the child component tree into all the child component views. The /deep/ combinator works to any depth of nested components, and it applies to both the view children and content children of the component.

This is misleading because styles affected by `::ng-deep` don't only affect "child component views"- they affect _all views globally_. 

It would be more accurate to say that `::ng-deep` turns off view-encapsulation for that style declaration such that it becomes a global style.

### What's the affected URL?**
https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep

**Comment by JoostK** [comment]
We may want to document the pattern of using `:host ::ng-deep` to achieve the effect of applying the styles only to the descendants tree.

**Comment by SRINIVAS-B-SINDAGI** [comment]
> We may want to document the pattern of using `:host ::ng-deep` to achieve the effect of applying the styles only to the descendants tree.

> hey if we use `::ng-deep xxx {}`  the css styles bleeds out to all component and if i use  the syntax the `:host ::ng-deep xxx {}` the styles wont get applied at all and how to solve this issue?
