### ISSUE TITLE
Throw an error when templating braces are used to pass attribute values

### ISSUE THREAD

**Issue by glemiere** [angular/angular#29970]
Hi!

I've been using Angular for a few years now, and I regularly come across projects where previous developers used the templating braces to pass attribute values, doing awful sins such as:

`<img src="{{myPicture}}" />`

Instead of

`<img [src]="myPicture" />`

I'm starting to seriously pull my hair off by having to fix a ton of occurrences of the error described above, and for this reason I think it'd be really neat if Angular was just throwing an error at build time, runtime or both, preventing inexperienced developer to misuse templating braces.

Thanks!

**Comment by JoostK** [comment]
This would be something for a tslint rule, not the framework itself. From a framework perspective, the given syntax is perfectly valid, it's even documented like that. The thing is, `img#src` is supposed to be a string attribute so using interpolation to bind a string seems fine to me.

Feel free to elaborate on why you feel it is "awful" to use this syntax. FWIW, I do share your preference regarding brackets vs. interpolation, but to me it's entirely subjective.

**Comment by Airblader** [comment]
Interestingly, there is also a functional difference. If it's not an attribute but a directive, then using brackets can cause an error if the directive is not present while the interpolation will silently fail. Of course that's not exactly something I'd promote.

I'm with @JoostK here. While I share the preference of a proper input binding, both are valid from the framework perspective and without an objective reason for a breaking change this is better handles as a linting rule.

**Comment by glemiere** [comment]
@JoostK @Airblader Thank you both for your fast reply!
I see what you guys mean, I always educate my coworkers and receive knowledge as well. The problem here is that we inherit projects developed by other teams from other companies, and so they're not my coworkers, we just get the codebases as is and have to deal with it.
Codebases are sometimes badly written and having templates written this way doesn't help with code readability and maintainability which I think is a good enough reason to set higher standards within Angular itself.

Here is why I think it would be a smart design decision to throw and error (**or at least a warning**):
- A nice codebase (by my standard) is usually made of functions which aren't longer than 25 lines and 80 chars long. This is somehow true for HTML as well, it is much easier to read when lines don't exceed 80 characters of length. For example, if you build a path made of variable, you will end up doing something like `{{var1}}/{{var2}}/{{var3}}` vs `var1+'/'+var2+'/'+var3`. You save 4 chars with the second option by avoid using excessive braces. Of course you could set this inside your TS class, but some developers prefer setting this in there HTML template which I respect.

- I think it is important for a modern framework to draw clear line between templating and binding inputs attributes, directives, props or whatever you want to call them. Using/accepting braces to bind inputs feels hacky rather than proper. To be honest, I wonder if using the templating braces to bind inputs could result into security issues, I'd have to dig a little more into that to tell for sure.

- Making the difference between both concepts could open doors to further feature development like creating SSR and XSS proof alternatives to innerHTML by outputting nodes from an HTML string from a mustache template for example.

Let me know what your thoughts are, and again, thanks for the fast reply!

**Comment by Airblader** [comment]
> The problem here is that we inherit projects developed by other teams from other companies, and so they're not my coworkers, we just get the codebases as is and have to deal with it.

That's just a universal fact of software development, and I promise you – it won't change no matter what. There's more to quality than a framework can enforce. :-)

> having templates written this way doesn't help with code readability

This is entirely subjective. The very people who write the code like this probably think it's *easier* to read (based on my, also subjective, experience). Especially when there's some concatenation going on like in the following example:

```
<foo bar="hello-{{ worldName }}"></foo>
<foo [bar]="'hello-' + worldName"></foo>
```

Yes, I also still prefer the second version, but I find it hard to argue that one is truly more readable than the other.

> having templates written this way doesn't help with code […] maintainability

I fail to see how either one is more or less maintainable than the other(?)

> A nice codebase (by my standard) is usually made of functions which aren't longer than 25 lines and 80 chars long. 

This is again just opinion, and in fact a controversial topic. Other people see 80 characters as a relict of software development from two decades ago. If you have these standards, enforce them in your projects. Other people, teams and companies have other standards or focuses (such as easy for newcomers, fast iterations and prototyping, …).

You could also write a simple tslint autofixer that you run on the projects you inherit. :-)

> You save 4 chars with the second option by avoid using excessive braces.

Oh, the humanity… :-)

> Of course you could set this inside your TS class, but some developers prefer setting this in there HTML template which I respect.

Why? By my standard, this is a bad practice, so why should this be allowed? ;-)

> To be honest, I wonder if using the templating braces to bind inputs could result into security issues, I'd have to dig a little more into that to tell for sure.

I see no reason why it would, a lot of the underlying process is still the same. I won't count "security" as an argument unless there's an actual example – and even then, it could (and should) be fixed without dropping interpolation support.

---

Personally, I would do a cost versus benefit consideration. So far I haven't heard any *objective* benefit to dropping interpolation support. On the other hand, the cost is extremely high: it's a breaking change which, according to your own statements, would affect *a lot* of code. To be fair, this could likely be automigrated; but I doubt the wider development community would understand the necessity of the change.

**Comment by trotyl** [comment]
> A nice codebase (by my standard) is usually made of functions which aren't longer than 25 lines and 80 chars long.

This is clearly not some part of semantics and doesn't belong to the template engine. But totally valid for lint rules.

> For example, if you build a path made of variable, you will end up doing something like `{{var1}}/{{var2}}/{{var3}}` vs `var1+'/'+var2+'/'+var3`. You save 4 chars with the second option by avoid using excessive braces.

I'd say many people would not prefer string concatenation per parity of JavaScript/TypeScript rule:

+ https://eslint.org/docs/rules/prefer-template
+ https://palantir.github.io/tslint/rules/prefer-template/

By suggesting forbidding interpolation, you should aware what other people may suggest forbidding string concatenation as well.

Also you're treating the stat by not writing the full form and didn't count the whitespace, the real codes are:

```html
<el foo="{{ var1 }}/{{ var2 }}/{{ var3 }}">
<el [foo]="var1 + '/' + var2 + '/' + var3">
```

Template expression should always follow the same lint rules as JavaScript expression.

**Comment by pkozlowski-opensource** [comment]
`<img src="{{myPicture}}" />` is totally valid and is just a sugar for `<img [src]="''+myPicture+''" />`. It just means: bind to the `src` property (Angular is binding to properties by default) _and_ convert `myPicture` to string (which makes sense in the case of the `src` property as it us supposed to be a string representing a URI.

Given the above I don't think one should prefer one syntax over another and as such I don't think there is a room here for warnings / linters etc. One _could_ enforce particular rules for a given project but it would be a matter of a personal preference not some "best practice" from the framework point of view.
