### ISSUE TITLE
router.navigate() modifies previous request in browser when used in JSP.

### ISSUE THREAD

**Issue by nakshay** [angular/angular#29971]
### Description
I am trying to integrate angular app on JSP page, when the code hit the line router.navigate() browser just throws the previous request .

below is the summary :

### CASE 1: without angular

Page A ---POST(mandatory request body)----> Page B----> reload button ---> POST(mandatory request body)--->page B
                 (wihout agnular)

### CASE 2: with angular

Page A ---POST(mandatory request body) ----> Page B ------> reload button----->GET(all mandatory fields lost) --> failure becasue all mandatory fields are missing
		    (angular)

we have servlet filters on server side which checks for mandatory attributes in request body, when angular app is loaded the previous POST request is lost and in first case it is preserved.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.2.4
Node: 10.15.0
OS: win32 x64
Angular: 7.2.13
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.2.4
@angular/cli                      7.2.4
@ngtools/webpack                  7.2.4
@schematics/angular               7.2.4
@schematics/update                0.12.4
rxjs                              6.3.3
typescript                        3.2.4
webpack

</code></pre>

**Anything else relevant?**
I have noticed that when router.navigate() is not present on angular app previous post request is preserved but if present then previous POST request is vanished somehow.

**Comment by trotyl** [comment]
This is how browser works, as long as URL is changed, then there's going to be an new browser history item in the stack. You can try:

```javascript
console.log(history.length)
location.hash = 'foo'
console.log(history.length)
```

In any page with or without Angular, and you can found a new page navigation.

And after that, the current page is not the same page returned by your backend request.

The flow in your app is just too vulnerable that cannot work with frontend routing.

Technically you can achieve that by manually providing a full-memory-based [`PlatformLocation`](https://angular.io/api/common/PlatformLocation) that doesn't touch URL at all, but that's against the routing mechanism (doesn't work with refresh at all) and will not likely be provided by Angular.

**Comment by nakshay** [comment]
@trotyl on my page B there are multiple ajax requests fired still browser preserves the previous POST request which was used to render page B from page A moreover it has all form data in request body (when angular app is not present on page B).

When angular app is loaded and navigated to different component the same POST request is lost and on browser reload action only GET request is fired to the URL present in address bar.

I want to know is there any extra parameter which I can pass to router.navigate which will not modify the state of browser. like preserveQueryParams

Thanks 👍

**Comment by trotyl** [comment]
> on my page B there are multiple ajax requests fired still browser preserves the previous POST request which was used to render page B from page A

As explained above, your application doesn't work with front-end routing (changing the URL), XHR is not relevant.

> When angular app is loaded and navigated to different component the same POST request is lost

Given your application doesn't work with front-end routing, of course it would be break by any kind of URL change.

> I want to know is there any extra parameter which I can pass to router.navigate which will not modify the state of browser. like preserveQueryParams

No, `preserveQueryParams` will still trigger a new page navigation even if URL not changed, to [save the new history state](https://developer.mozilla.org/en-US/docs/Web/API/History_API#Example_of_pushState()_method).

---

Actually POST-returned-page has been considered a flaw for many years, and [POST-redirect-GET](https://en.wikipedia.org/wiki/Post/Redirect/Get) is expected, I don't suggest stick to a problematic web flow.

**Comment by nakshay** [comment]
thank you very much @trotyl , I found that when history.state is not modified everything works properly.
angular provide the option  

this.router.navigate(['/view'], { skipLocationChange: true });
but still it changes the state and adds the object  {navigationId: 2} in history.state

Is there anything I am missing or it is supposed to work like this.

**Comment by trotyl** [comment]
> this.router.navigate(['/view'], { skipLocationChange: true });

`skipLocationChange` is used to mark a different view being same page logically, which is page-specific.

But if you don't ever want location being changed, then it's no routing any more and you shouldn't use `Router`. You can not even use two different [`Route`](https://angular.io/api/router/Route)s when doing that.

If there's an option like `skipStateChange`, then [user state](https://angular.io/api/router/NavigationExtras#state) and [scrolling](https://angular.io/api/router/ExtraOptions#anchorScrolling) feature would not work any more, making the options exclusive rather than orthogonal, I don't think that can be a good design.

**Comment by nakshay** [comment]
@trotyl  I want my history.state to remain unchanged , is there any way to do that.
Thanks

**Comment by trotyl** [comment]
> I want my history.state to remain unchanged , is there any way to do that.

It was answered in [my first reply](https://github.com/angular/angular/issues/29971#issuecomment-484442629):

> Technically you can achieve that by manually providing a full-memory-based [`PlatformLocation`](https://angular.io/api/common/PlatformLocation) that doesn't touch URL at all

But by doing that you're responsible for handling the history yourself, be careful of memory leak between navigations.

**Comment by nakshay** [comment]
@trotyl skipLocationChange worked for me, the problem was the router configuration in my code. which does not accept skipLocationChange parameter and changes the state while visiting component and then after using SkipLocationChange does not work because state is already changed.

I have added stackoverflow question as well. [https://stackoverflow.com/questions/55747633/this-router-navigate-selectscenarios-skiplocationchange-true-not-wor](StackOverflow)



   ```
const appRoutes: Routes = [
 -     {
 -     path: '',
 -     redirectTo: "/customComponent",
 -     pathMatch: 'full'
 -   },
```

**Comment by nakshay** [comment]
So  bottom line is to use skipLocationChange we should make sure routing is not handled from anywhere else. i.e. without skipLocationChange .

Closing this issue.
