### ISSUE TITLE
Angular Service Worker Manifest Cache Not Clearing Instantly

### ISSUE THREAD

**Issue by rakeshgsharma** [angular/angular#29985]
# 🐞 bug report

### Affected Package

This issue is caused by @angular/service-worker

### Description

I am trying to clear the service worker caches after a new app is deployed. I am using http-server to deploy it on localhost. I have an angular app already running, and my service-worker is registered. When I change some code and redeploy the app, what I see in the cache memory is that the older cache is still present. In the cache manifest I see an array of the ngsw.json files. There is "latest" tab where the latest hash is stored. The app is rendered from the latest manifest hash, but sometimes, it gets rendered from the older manifests too. I am unable to reproduce that case, but it happens very rarely. After 10-15 mins, the manifest gets cleared and only one manifest hash is present in the cache storage. This is happening randomly without any consistency.

## 🔬 Minimal Reproduction
Create any angular app with angular service worker running, change some code, redeploy it, and you will see that the older service worker cache manifest are still present.

If I check the "Update On Reload" under the service worker tab, the older cache manifests are getting cleared instantly. I would like the older cache to be deleted by the angular service worker instantly without checking that option.

This is how my ngsw-config looks like:

<pre><code>

{
  "configVersion": 1,
  "index": "/index.html",
  "appData": ["/index.html", "/*.bundle.css", "/*.bundle.js", "/*.chunk.js"],
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "resources": {
        "files": ["/favicon.ico", "/index.html"],
        "versionedFiles": ["/*.bundle.css", "/*.bundle.js", "/*.chunk.js"]
      }
    },
    {
      "name": "assets",
      "installMode": "prefetch",
      "updateMode": "prefetch",
      "resources": {
        "files": ["/assets/**"]
      }
    }
  ]
}
</code></pre>

And this is how I have registered it in app.module.ts:
<pre><code>
@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    RouterModule,
    APP_ROUTING,
    ServiceWorkerModule.register('/ngsw-worker.js', {
      enabled: environment.production
    })
  ],
  providers: [],
  bootstrap: [AppComponent]
})
</code></pre>

This is what my app.component.ts looks like:

<pre><code>
import { Component } from '@angular/core';
import { SwUpdate } from '@angular/service-worker';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  constructor(private updates: SwUpdate) {
    this.updates.available.subscribe((event: any) => {
      this.updates.activateUpdate().then(() => {
        document.location.reload(true);
      });
    });
  }
</code></pre>

## 🔥 Exception or Error

This how the multiple manifests looks like in Cache Storage:

<pre><code>
113eb2d75d6b2b62654822b31924678b90ee76e9: {configVersion: 1, index: "/index.html",…}..
23er43ertgvcx6751cvb8u8u9o0mnb6765098h76: {configVersion: 1, index: "/index.html",…}..
987ujvsskjfd56snsnf34flo3298fcdgnzx768z7: {configVersion: 1, index: "/index.html",…}..
343eb2d56d6b2b638493hh331664690f55ssz8j8: {configVersion: 1, index: "/index.html",…}..
</code></pre>

And the latest key just above the manifest is:

<pre><code>
{ latest: "113eb2d75d6b2b62654822b31924678b90ee76e9" }
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>
Angular CLI: 1.6.7
Node: 10.15.0
OS: win32 x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cli: 1.6.7
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
<code>

</code></pre>

**The older manifest caches  should cleared as soon as a new app is deployed.**

**Anything else relevant?**
Using http-server to deploy it locally
Chrome version: Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by gkalpak** [comment]
Cache clean-up happens [every time the SW is initialized][1] (i.e. when a new SW is activated or a new SW instance is created by the browser).
It shouldn't be difficult to either run clean-up on every client update or allow triggering it from the app, but it might result in too much unnecessary work (e.g. if you have multiple tabs of the app open).

Any particular reason why the current behavior this doesn't work for you?

[1]: https://github.com/angular/angular/blob/ab6036272/packages/service-worker/worker/src/driver.ts#L496

**Comment by rakeshgsharma** [comment]
This current behavior seems unpredictable, I'm not sure when the new SW will be activated or new instance is created(it not activating as soon as a new manifest hash is created). Sometimes the caches clean up within a minute, sometimes it might take hours.
Is there any specific reason for this behavior? 
Can I manually clean up old cache rather than depending on the browser to initiate a SW?

**Comment by gkalpak** [comment]
> This current behavior seems unpredictable

Yes, it is unpredictable, but that shouldn't matter to the app developer (or the user). It is tied to SW lifecycle, which is also unpredictable (i.e. the browser decides when to suspend it or re-instantiate it).

##
> When I redeploy [...], the four-lettered service worker hash (#xxxx) is not changing

That is expected. The different application versions are independent of the SW script (unlike other SW implementations). This decoupling is by design and it allows the SW to serve the latest version to new clients (i.e. new tabs) even if old tabs are still open (and without having to disrupt old clients by forcing them to reload at arbitrary times).

##
> Can I manually clean up old cache?

No, it is currently not possible to manually clean-up (or trigger the clean-up of) the caches.
