### ISSUE TITLE
Error: Uncaught (in promise): Error: Cannot match any routes.

### ISSUE THREAD

**Issue by Domiserver** [angular/angular#30004]
Angular CLI: 7.3.3
Node: 11.14.0
OS: linux x64 
============================================
**My code from app.component.html is published but when I click on the button I get the following browser error:**
"core.js:15724 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'header/footer'
Error: Cannot match any routes. URL Segment: 'header/footer'
    at ApplyRedirects.push../node_modules/@angular/router/fesm5/router.js.ApplyRedirects.noMatchError (router.js:2469)
    at CatchSubscriber.selector (router.js:2450)
    ... "

**Here is the app-routing.module.ts**
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Routes, RouterModule } from '@angular/router';
import { HomeComponent } from './home/home.component';
import { HeaderComponent } from './shared/header/header.component';
import { FooterComponent } from './shared/footer/footer.component';

const routes: Routes = [
  {path: 'home', component: HomeComponent},
  {path: 'header', component: HeaderComponent},
  {path: 'footer', component: FooterComponent}
  {path: '', redirectTo: 'header', pathMatch: 'full'},
  {path: '**', redirectTo: 'home', pathMatch: 'full'}
];
@NgModule({
  declarations: [ ],
  imports: [
  CommonModule,
  RouterModule.forRoot(routes)
  ],
  exports: [RouterModule]
})
export class AppRoutingModule { }

 and here is the footer.component.html
<mat-card>
  <mat-card-title>
      Test Footer Page
  </mat-card-title>
  <mat-card-content>
    <button routerLink='home'>goto Home</button>
    <button routerLink='header'>goto Header</button>
    <br>
  </mat-card-content>
</mat-card> 

The code is with Angular Material but I am not able to paste it in here and be shown.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Domiserver** [comment]
I understand.

Thanks for replying.  I was able to solve this issue by reading the Angular Online Manual.
Is there anyway I can delete this question to avoid clutter on Github?
