### ISSUE TITLE
I want to say if your workspace is problematic.

### ISSUE THREAD

**Issue by weibon** [angular/angular#30003]
Why am I git clone https://github.com/angular/angular.git later
After yarn install
Yarn bazel build packages/core execution
Report this error why? ? ? ? ? ? ? I see this is a problem with the workspace file?
ERROR: Failed to load Starlark extension '@npm_bazel_karma//:package.bzl'.
It usually happens when the repository is not defined prior to being used.
This could either mean you have to add the 'npm_bazel_karma' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or the repository 'npm_bazel_karma' was defined too late in your WORKSPACE file.
ERROR: cycles detected during target parsing
INFO: Elapsed time: 0.303s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
Error Command failed with exit code 1.
Info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter
