### ISSUE TITLE
Feature Request: Descendant projection through router.

### ISSUE THREAD

**Issue by thesayyn** [angular/angular#30016]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/router, @angular/core

### Description
Basically, my feature request is about content projection through router tree.  I'll explain with an example. 
 
Let's say I have an Tab Component which contains a basic **"two tab"** **mat-tab-nav-bar**.
Also,  I have two other components which contain my real page contents.

In this case, my router configuration would be something like so
```typescript
      {
        path: 'identity',
        component: TabsComponent
        children: [
          {
            path: 'tab1',
            component: Tab1Component
          },
          {
            path: 'tab2',
            component: Tab2Component
          }
        ]
      }
```

My TabsComponent has an **@ContentChildren** query with descendants option true.

TabsComponents template looks like this.
```html
<mat-toolbar>
 <!--- actions varible has @ContentChildren('toolbar') decorator -->
  <ng-container *ngTemplateOutlet="actions"></ng-container>
  <mat-toolbar-row>
    <nav mat-tab-nav-bar color="accent">
      <a mat-tab-link routerLink="tab1">Tab1</a>
      <a mat-tab-link routerLink="tab2">Tab2</a>
    </nav>
  </mat-toolbar-row>
</mat-toolbar>
<router-outlet></router-outlet>
```
So each tab component has an ng-template something like so
```html
<ng-template #toolbar>
  <mat-toolbar-row>
   Content will be projected to anchestor component
  </mat-toolbar-row>
</ng-template>
```

### Describe the solution you'd like

Content projection should work as the current content projection works with descendant components.

### Describe alternatives you've considered

My workaround.

Each tab has an variable named as toolbar which has a @ViewChild('toolbar') decorator. So all tab pages takes their ng-template reference by theirselves.

So TabsComponents template looks like this.

```html
 <ng-container *ngTemplateOutlet="outlet?.component?.toolbar"></ng-container>
...
<router-outlet #outlet="outlet"></router-outlet>
```

Hint: Don't know whether this already solved by ivy. Thanks

**Comment by Airblader** [comment]
Why not just use multiple router outlets and separate components for tab content + corresponding actions?

**Comment by thesayyn** [comment]
It would require lots of efforts plus I won't be able to interact between components easily. For bigger applications your way will become so much complicated. 

My feature request 100 percent suits and works with current design of angular. There wouldn't be a new learning curve for this feature. 


Also this could be done with shadow dom + slots which is not supported by material2.
