### ISSUE TITLE
ng generate app-shell getting merge conflict  error

### ISSUE THREAD

**Issue by rajaramtt** [angular/angular#30013]
A merge conflicted on path "/src/app/app.server.module.ts".

![image](https://user-images.githubusercontent.com/17231665/56469203-0aa31080-6454-11e9-960b-58a256d5452d.png)

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter
