### ISSUE TITLE
Ability to turn off dash case for CSSClass directive

### ISSUE THREAD

**Issue by pflannery** [angular/angular#3001]
I'm finding problems with css that uses camel case when using CSSClass because [this line](https://github.com/angular/angular/blob/44891996b592cbbeafb3a6f45a27d8d943895bab/modules/angular2/src/render/dom/view/view.ts#L58) automatically converts each class to dashed case.

Can we have a choice between camel case and raw input when using the CSSClass directive?
Would be nice if we could provide a means to configure CSSClass directive per component.

**Comment by pkozlowski-opensource** [comment]
@pflannery why it is causing issues for you in practice? AFAIK css class names are not case-sensitive (https://developer.mozilla.org/en/docs/Case_Sensitivity_in_class_and_id_Names) and you can't have mixed cases in your HTML markup.

> I'm finding problems with css that uses camel case 

Could you be more precise? What is the exact use-case?

> Can we have a choice between camel case and raw input when using the CSSClass directive?
Would be nice if we could provide a means to configure CSSClass directive per component.

This wouldn't work as 3rd party components would be dependent on app's settings and thus could break without warning.

Once again, I would be keen on knowing more about your exact use-case. It sounds like you might have mixed-case in your CSS classes (which is not great) and then trying to replicate this markup in your HTML.

**Comment by pflannery** [comment]
@pkozlowski-opensource The problem comes with using and writing libraries that follow camel case guidelines like [OOCSS](https://github.com/stubbornella/oocss-code-standards#oocss-code-standards) or using libraries like animate.css

Camel case is my preference over dashed case. For me I would have to convert all my previous libraries over to dashed case or would be forced to write them all as lower case (for angular) to get around the dash case transformer. I personally want to keep readability using camel case classes both in code and html.

>This wouldn't work as 3rd party components would be dependent on app's settings and thus could break without warning.

Then perhaps a separate directive is a better approach?

**Comment by pkozlowski-opensource** [comment]
OK, I see, this is only for readability then, right? 

> Then perhaps a separate directive is a better approach?

As it is coded today, this conversion affects all the places where a CSS class is set on an element, so a separate directive wouldn't work / isn't enough. 

@tbosch maybe we are too aggressive about this conversion and should do it only when a CSS class name comes from HTML attribute value (that is, when using `[class.foo]=expr` syntax?

**Comment by mhevery** [comment]
I don't see how a choice of CSS class names causes an issue. Could you provide a working example demonstrating the problem.

**Comment by TiagoBraga39** [comment]
Hi all!

I also came into this issue. Here s how it goes:

<b>Html I provide:</b>
https://cloud.githubusercontent.com/assets/8090726/8826875/5c9baeb6-3081-11e5-8d4e-58d923b653d2.png

<b>Output Html:</b>
https://cloud.githubusercontent.com/assets/8090726/8826869/517f8db8-3081-11e5-8635-14df64e69cea.png

As you can see, I used an expression to bind the class of the element.
But the output has <b>hyphens</b> instead of <b>Capital Letters</b>.

<b>The expected output:</b>
![image](https://cloud.githubusercontent.com/assets/8090726/8827310/e0f3b76a-3083-11e5-97e4-e9b473a635bf.png)


<The actual output>
![image](https://cloud.githubusercontent.com/assets/8090726/8827280/b709d15a-3083-11e5-9c75-3eab2a5fb6ef.png)

---
Result
---
As you can see, in the actual output, I don't have that darker blue color...

Best regards,
Tiago Braga

**Comment by pkozlowski-opensource** [comment]
@TiagoBraga39 as quick work-around make sure that your CSS class names are lower-cased (which makes sense anyway, since browsers are not dealing with case-sensitive CSS)

**Comment by TiagoBraga39** [comment]
@pkozlowski-opensource The thing is I actually have a ton of css classes with capital letters, which worked on NG1, and now I can't use them in NG2?

**Comment by pkozlowski-opensource** [comment]
This is why I marked it as a work-around.

**Comment by pflannery** [comment]
I've found a case where the work-around doesn't work. 

It baffled me for a while because at first I was sure that classes are case sensitive but then I realised that it's because my angular project didn't have a doctype defined and when I added `<!DOCTYPE html>` at the top of the page this workaround stops working in firefox and chrome (didnt try any other browser).  Something else I noticed is that the [article posted above](https://developer.mozilla.org/en/docs/Case_Sensitivity_in_class_and_id_Names) was last updated 05 Mar 2001.

I think the ability to output as WYSIWYG would resolve this.

**Comment by pflannery** [comment]
@mhevery I've tried to post a working plunker example but cant get angular to work there. I always see "require is undefined"..if you have a template from plunker or fiddler etc.. I'd be happy to try  demonstrate

**Comment by TiagoBraga39** [comment]
@pflannery 
There you go: http://plnkr.co/edit/N5uD9ogaOghiKLRNP1JQ?p=preview

<b>Note 1:</b> It's just an Hello World Sample with 2 cdn: 
<li>Angular alpha 31</li>
<li>System 0.16</li>

<b>Note 2: </b>
<li>I can't exactly remember the options to put on config.js since I don't have the code with me.</li>

**Comment by pflannery** [comment]
@TiagoBraga39 thank you very much! 

Here is an example of the issue http://plnkr.co/edit/StVbjnVMWWnBZPtVQSsu?p=preview

**Comment by TiagoBraga39** [comment]
Yup, same behaviour.
After changing to dash case as @pkozlowski-opensource said it works, but only that way.

**Comment by amoizp** [comment]
+1 on maintaining original capitalization and dashes. 

We use css class names such as `Tabs-tabLabel` and dynamically bind `Tabs-tabLabel--selected`.  Worked fine with ng1 (using ng-class) and we'd very much like to continue that in ng2.

**Comment by tbosch** [comment]
Just verified myself: `querySelector` _does_ differentiate between the case in class names.

**Comment by rixrix** [comment]
Hi, tnx for not de-normalizing the CSS class name

**Comment by amoizp** [comment]
Thanks for the change.  It's better than before but still not working as expected.  Tried the following with alpha 33. 

While using `[class.Tabs-tabLabel--selected] = "tab.isActive()"` the css class is only selected if it is in lower-case i.e. `.tabs-tablabel--selected`.  It should work with `.Tabs-tabLabel--selected`

**Comment by pkozlowski-opensource** [comment]
@amoizp you are talking about a different issue here. You need to keep in mind that HTML is not case-sensitive nor case-preserving, so if you type `[class.Tabs-tabLabel-selected] = "tab.isActive()"` in HTML a _browser_ will "auto-correct" it to be `[class.tabs-tablabel-selected] = "tab.isActive()"` (lower-casing all attribute names). This happens before angular's compiler run, so we can't do much about his one.

**Comment by amoizp** [comment]
@pkozlowski-opensource  Got it, thanks.  

So far, our upgrade to angular 2 is working out very well.  Keep it up guys!
