### ISSUE TITLE
Cannot find module './lazy-load.module.ngfactory' with Custom Elements app

### ISSUE THREAD

**Issue by richardlnnr** [angular/angular#30027]
# 🐞 bug report

### Affected Package

 
The issue is caused by package @angular/elements and optimization config

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 6

### Description

When a custom element app is built using --optimization=true and the host app is running in prod mode (ng serve --prod) the lazy load doesn't work.
To see the error, please follow the next steps.

## 🔬 Minimal Reproduction

https://github.com/richardlnnr/angular-compiler-issue

Steps to reproduce the error:
For building this project it's necessary running the following steps:

Prepare the static server

* `cd static`
* `npm install`
* `npm start`

Prepare application

* `cd compiler-issue`
* `npm install`
* `npm run package:custom-element-a`
* `npm run start-prod`

When accessing the route `http://localhost:4200/lazy-load-strategy` the following error has thrown.

## 🔥 Exception or Error
<pre><code>

ERROR Error: Uncaught (in promise): Error: Cannot find module './lazy-load-strategy/lazy-load-strategy.module.ngfactory'
Error: Cannot find module './lazy-load-strategy/lazy-load-strategy.module.ngfactory'
    at bundle.js:1
    at e.invoke (zone.js.pre-build-optimizer.js:391)
    at Object.onInvoke (core.js.pre-build-optimizer.js:17299)
    at e.invoke (zone.js.pre-build-optimizer.js:390)
    at t.run (zone.js.pre-build-optimizer.js:150)
    at zone.js.pre-build-optimizer.js:910
    at e.invokeTask (zone.js.pre-build-optimizer.js:423)
    at Object.onInvokeTask (core.js.pre-build-optimizer.js:17290)
    at e.invokeTask (zone.js.pre-build-optimizer.js:422)
    at t.runTask (zone.js.pre-build-optimizer.js:195)
    at C (zone.js.pre-build-optimizer.js:852)
    at C (zone.js.pre-build-optimizer.js:809)
    at zone.js.pre-build-optimizer.js:913
    at e.invokeTask (zone.js.pre-build-optimizer.js:423)
    at Object.onInvokeTask (core.js.pre-build-optimizer.js:17290)
    at e.invokeTask (zone.js.pre-build-optimizer.js:422)
    at t.runTask (zone.js.pre-build-optimizer.js:195)
    at m (zone.js.pre-build-optimizer.js:601)
    at t.invokeTask [as invoke] (zone.js.pre-build-optimizer.js:502)
    at y (zone.js.pre-build-optimizer.js:1693)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.8
Node: 10.15.1
OS: win32 x64
Angular: 7.2.13
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**

When you build the `custom-element-a` with `--optimization=false` the `main-app` works in production mode, but doesn't work in dev-mode. (`npm run package-prod:custom-element-a`).

When you build the `custom-element-a` with `--optimization=true` the `main-app` doesn't work in production mode, but works in dev-mode. (`npm run package:custom-element-a`)

[Related issue](https://github.com/angular/angular/issues/30028) - I've opened separeted issues because the steps to reproduce the errors and the result are different errors.

**Comment by robwormald** [comment]
I believe this is the same root cause as #30028 - and the same fix applies :)
