### ISSUE TITLE
"Could not create Angular AOT compiler to determine query timing." when updating to Angular 8

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#30031]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core.

### Is this a regression?

No.

### Description

 A clear and concise description of the problem...

When updating a project created by Angular CLI version 7, the warnings are shown.

## 🔬 Minimal Reproduction
This error can be reproduced by following the update steps in 
```
npm i -g @angular/cli@~7.0
ng new seven-oh-project
cd seven-oh-project
ng update @angular/cli --next
ng update @angular/core --next
```
It also shows up in the CLI test suite for updates: https://github.com/angular/angular-cli/pull/14228/files#r277311238.

## 🔥 Exception or Error
<pre><code>
  Could not create Angular AOT compiler to determine query timing.
  The following diagnostics were detected:
  Cannot determine the module for class AppComponent in C:/Users/kamik/AppData/Local/Temp/angular-cli-e2e-2019322-20076-1fyaia4.k68k/assets/7.0-project-1555942786902/src/app/app.component.ts! Add AppComponent to the NgModule to fix it.
  Cannot determine the module for class LazyCompComponent in C:/Users/kamik/AppData/Local/Temp/angular-cli-e2e-2019322-20076-1fyaia4.k68k/assets/7.0-project-1555942786902/src/app/lazy/lazy-comp/lazy-comp.component.ts! Add LazyCompComponent to the NgModule to fix it.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
8.0.0-beta.13
</code></pre>

**Anything else relevant?**

Warnings seem to come from here:
https://github.com/angular/angular/blob/master/packages/core/schematics/migrations/static-queries/strategies/template_strategy/template_strategy.ts#L183-L187

**Comment by alexeagle** [comment]
fixed in #30034
