### ISSUE TITLE
Docs: yarn setup for docs is causing error in docs

### ISSUE THREAD

**Issue by m-henderson** [angular/angular#30033]
# 📚 Docs or angular.io bug report

### Description
When running `yarn` inside of the aio folder, all of the dependencies install perfectly fine. The next step is to run `yard setup`. That command is not finishing and is causing an error. 

### Reproduction Steps**
1. clone the angular repository. 
2. open a command prompt or bash in the directory of that repo you just cloned.
3. run `cd aio`
4. run `yarn`
5. run `yarn setup` <-- error occurs on step 5. 

### Expected vs Actual Behavior**
The setup should finish without error. 

## 📷Screenshot
![image](https://user-images.githubusercontent.com/16070192/56512744-e7c93880-64f5-11e9-8479-6b2b3037baa9.png)

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/16070192/56513097-f5cb8900-64f6-11e9-90e0-22d3ca42f94f.png)

**Comment by brandonroberts** [comment]
@m-henderson We haven't updated the yarn ranges under the `engines` yet. As a workaround, I recommend you downgrade `yarn` to version `1.13.0`

**Comment by m-henderson** [comment]
@brandonroberts that worked. How much effort is required to update the ranges?
