### ISSUE TITLE
How can I add a link to it into the `UI Components` section of https://angular.io/resources

### ISSUE THREAD

**Issue by rdkmaster** [angular/angular#30044]
# 📚 Docs or angular.io bug report

### Description

[Jigsaw](https://github.com/rdkmaster/jigsaw) is a powerful set of components based on angular, how can I add a link to it into the `UI Components` section of this page <https://angular.io/resources>

### What's the affected URL?**

https://angular.io/resources

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by thesayyn** [comment]
Checkout aio folder there must be a markdown file which contains these texts and then send a pull request against it

**Comment by rdkmaster** [comment]
Thanks @thesayyn , I will close this issue in that PR.

**Comment by gkalpak** [comment]
@rdkmaster, see [resources-contributing.md][1].

[1]: https://github.com/angular/angular/blob/9873356bd0597743cf67fcfafd585d1056cb2233/aio/content/marketing/resources-contributing.md
