### ISSUE TITLE
Router reloads view when hash added to url

### ISSUE THREAD

**Issue by andersonkoester** [angular/angular#30056]
I have an application that I need integrate with Android's Barcode Scanner app, in this app I can return a url to get the readed barcode. 

In my cenario I'm using this url: http://domain/home/ 
When a hash is added on url it causes a view refresh, closing the mdDialog used to read barcode purpose.

In this case is only refreshing the view, on log is added this event:
`NavigationStart => {id: 2, navigationTrigger: "popstate", restoredState: null, url: "/#3-571223"}`

I thought develop a custom component listening another route to open this mdDialog and listen hash modifications, but I think angular can be more smart than it.

PS: I tried CanActivar/CanDeactivate, as I'm using same route these events are not dispatched

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter
