### ISSUE TITLE
On submit the form overpass controls validators

### ISSUE THREAD

**Issue by qmarquez** [angular/angular#30053]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/forms

### Is this a regression?
No

### Description
it seems like not all validators run when the form submits

## 🔬 Minimal Reproduction
https://angular-mxzgvk.stackblitz.io

set a pwd, then set the same on pwd2 an backing to pwd change it, submit and the form it's like valid, overpassing the validator of match passwords.

## 🔥 Exception or Error
the expected behavior it's that on submit the form rerun all validator or at least have a method to manually run validators like, runValidators() o something.
the other, maybe more redundant situation, it's to put the validator on both controls, but i want to avoid that.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.8
Node: 11.14.0
OS: linux x64
Angular: 7.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cdk                      7.3.6
@angular/material                 7.3.6
@angular/pwa                      0.13.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8 (cli-only)
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Comment by qmarquez** [comment]
Okey, i "fixit myself", you can close this, the solution it's to put the validator at formgroup level, and assign manually the error to the respective control

**Comment by kara** [comment]
Okay, closing this issue as resolved. Thanks for the update.
