### ISSUE TITLE
Syntax error in @angular/upgrade package due to differential loading

### ISSUE THREAD

**Issue by jpzwarte** [angular/angular#30050]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
`@angular.upgrade@8.0.0-beta.13`

### Is this a regression?
Yes.

 Yes, the previous version in which this bug was not present was: ....

### Description
Due to differential loading. My app uses `setAngularJSGlobal` from `@angular/upgrade/static`. That code is now loaded in the browser as ES2015 code. That results in this line: https://github.com/angular/angular/blob/master/packages/upgrade/src/common/src/angular1.ts#L299 throwing a "Syntax Error":

`Uncaught SyntaxError: Identifier 'module' has already been declared`

When i look at the source, `module` is already defined by webpack:

```
/***/ "../../node_modules/@angular/upgrade/fesm5/static.js":
/*!************************************************************************************************************************!*\
  !*** /.../node_modules/@angular/upgrade/fesm5/static.js ***!
  \************************************************************************************************************************/
/*! exports provided: ɵangular_packages_upgrade_static_static_e, ɵangular_packages_upgrade_static_static_c, ɵangular_packages_upgrade_static_static_a, ɵangular_packages_upgrade_static_static_d, ɵangular_packages_upgrade_static_static_b, getAngularJSGlobal, getAngularLib, setAngularJSGlobal, setAngularLib, downgradeComponent, downgradeInjectable, VERSION, downgradeModule, UpgradeComponent, UpgradeModule */
/***/ (function(module, __webpack_exports__, __webpack_require__) {
```
 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

Uncaught SyntaxError: Identifier 'module' has already been declared
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.0-beta.16
Node: 10.15.2
OS: darwin x64
Angular: 8.0.0-beta.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-beta.16
@angular-devkit/build-angular     0.800.0-beta.16
@angular-devkit/build-optimizer   0.800.0-beta.16
@angular-devkit/build-webpack     0.800.0-beta.16
@angular-devkit/core              8.0.0-beta.16
@angular-devkit/schematics        8.0.0-beta.16
@angular/cli                      8.0.0-beta.16
@ngtools/webpack                  8.0.0-beta.16
@schematics/angular               8.0.0-beta.16
@schematics/update                0.800.0-beta.16
rxjs                              6.5.1
typescript                        3.4.4
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

**Comment by jpzwarte** [comment]
Workaround: `"target": "es5"` in `tsconfig.json`. cc @alexeagle

**Comment by filipesilva** [comment]
As far as I can tell, this is a webpack bug: https://github.com/webpack/webpack/issues/7369

**Comment by alexeagle** [comment]
I suppose the workaround is to change the name of that variable so it doesn't collide with `module`

**Comment by gkalpak** [comment]
True (since this is not public API).
