### ISSUE TITLE
ng-container with ngProjectAs breaks ContentChild queries

### ISSUE THREAD

**Issue by gnomeontherun** [angular/angular#30059]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core

### Is this a regression?

I do not know.

### Description

When using `ContentChild` to query for a content child element in a component, it works if the element is placed inside of the host component. However, if you place the child component that you want to query inside of another component and then use `ng-container ngProjectAs="app-original-child"` to project the child (through another child), the `ContentChild` query is unable to resolve.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-mdpbk6?file=src%2Fapp%2Fapp.component.html

## 🔥 Exception or Error

The error is simply that the component is not found when using ngProjectAs.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.0-beta.5
Node: 10.12.0
OS: darwin x64
Angular: 8.0.0-beta.5
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.14.0-beta.5
@angular-devkit/build-angular      0.14.0-beta.5
@angular-devkit/build-ng-packagr   0.14.0-beta.5
@angular-devkit/build-optimizer    0.14.0-beta.5
@angular-devkit/build-webpack      0.14.0-beta.5
@angular-devkit/core               8.0.0-beta.5
@angular-devkit/schematics         8.0.0-beta.5
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.0-beta.5
@schematics/angular                8.0.0-beta.5
@schematics/update                 0.14.0-beta.5
ng-packagr                         4.7.1
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.29.6
</code></pre>

**Anything else relevant?**

**Comment by kara** [comment]
@gnomeontherun The "ngProjectAs" attribute is used to sort projected nodes into `<ng-content>` buckets within the host component (e.g. you have a bucket like `<ng-content select="app-project-test">`). It's not really meant to be used as a selector for directive matching, so it's expected that the node in question wouldn't match the query.   

If you want some more flexibility, you might try using queries for string predicates and local refs. See example here:

https://stackblitz.com/edit/angular-pl7co4?file=src%2Fapp%2Fapp.component.html

**Comment by pauldraper** [comment]
> not really meant

What's the difference in intention between ng-content and ContentChildren.
