### ISSUE TITLE
Base class of a component must be exported in production build, works without export keyword in development

### ISSUE THREAD

**Issue by gunsh** [angular/angular#30062]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?

Yes. I first encountered it with 7.2.13 but I reproduced it even with 6.1.0.

### Description

There is a difference in behavior between debug and production builds. It turns out that if component B extends class A, then the class A must be prefixed by **_export_** keyword or the error below shows in production build. In debug build **_export_** is not needed and the app works fine. If both **_aot_** and **_buildOptimizer_** are set to **false** in _angular.json_ then even the production build works without adding the **_export_** keyword.

Begin forced to export private or abstract base classes is an unwanted behavior.

## 🔬 Minimal Reproduction

Clone the repository: https://github.com/gunsh/angular7-export-base-class-issue

Run in debug mode to witness that everything is working as expected.
<pre><code>ng serve</code></pre>

Then run in production mode to see the error.
<pre><code>ng serve --prod</code></pre>

To fix the error in production build, one can do either of the following:

1. Turn off **_aot_** and **_buildOptimizer_** in _angular.json_
2. Uncomment **_export_** keyword on line 4 of _app.component.ts_

Both are undesirable workarounds.

## 🔥 Exception or Error
<pre><code>
ERROR in : Can't bind to 'txt' since it isn't a known property of 'div'. ("<div derived [ERROR ->][txt]="'hello world!'"></div>")
</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 7.3.8
Node: 10.12.0
OS: win32 x64
Angular: 7.2.13
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cdk                      7.3.7
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.5.1
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Comment by alxhub** [comment]
Exporting the base class is a hard requirement. We should give a better error in the case where we can't type-check properly if we're missing base class type information, though.

**Comment by gunsh** [comment]
@alxhub If it's a hard requirement then the error should be descriptive enough so that the dev knows what to fix. I spent literally half a day hunting this one down. The error shown in production does not lead one into believing **_export_** keyword is the culprit.

**Comment by JoostK** [comment]
The reported issue is working in Ivy in Angular 9.0.
