### ISSUE TITLE
♿ Router: Focus element after URL hash scroll into view navigation

### ISSUE THREAD

**Issue by MrGrigri** [angular/angular#30067]
# ♿ feature request

Add a flag for the Router Module to accept a flag to enable focusing of the element to which it is scrolled. In a previous issue (#6595) it was [discussed](https://github.com/angular/angular/issues/6595#issuecomment-439632006) that a feature request is needed to handle this issue. 

**This feature is required for Accessibility to work properly.**

### Relevant Package
`@angular/router/ExtraOptions`

### Description

This feature is required for Accessibility to work properly. The `anchorScrolling` router option works...however, according to the HTML Standard Spec, [Navigate to a Fragment](https://html.spec.whatwg.org/#scroll-to-fragid), the last step is:

> Move the sequential focus navigation starting point to [the] target.

### Describe the solution you'd like

Add a parameter for ExtraOptions as `anchorFocus` with the boolean type attached and false as the default

``` Typescript
export interface ExtraOptions {
  ...
  anchorScrolling?: 'disabled' | 'enabled',
  anchorFocus?: boolean,
  ...
})
```
This could be achieved by dynamically setting a `tabindex` of `'0'` on the targeted element, focusing on that element, then setting the `tabindex` to `'-1'`. If a `tabindex` is already set to `'0'`, then just focus on the element.

**Comment by AlekNiebla** [comment]
Hey can I work this issue?

**Comment by AlekNiebla** [comment]
> Hey can I work this issue?

hey im not gonna take on this issue

**Comment by danielnixon** [comment]
This is one of the issues I'm tackling in https://github.com/oaf-project/oaf-angular-router

**Comment by jasonaden** [comment]
Thanks for the issue. This would be a good one to get fixed. Thanks for taking a look @danielnixon .

**Comment by zelliott** [comment]
Quickly chiming in, I don't think the proposed solution (reproduced below) is what we want:

>  This could be achieved by dynamically setting a tabindex of '0' on the targeted element, focusing on that element, then setting the tabindex to '-1'. If a tabindex is already set to '0', then just focus on the element.

We don't want to set focus on the target element, we want to correctly move the sequential focus navigation starting point to the target. There's likely some logic in Angular's router (I'm super unfamiliar with Angular's router) that's preventing the browser from correctly dong this.

**Comment by MrGrigri** [comment]
@zelliott, according to the [spec](https://html.spec.whatwg.org/#scroll-to-fragid), the element needs to be focused on for accessibility reasons.

**Comment by zelliott** [comment]
Sorry, I misread the spec, thanks.

However, after reading the spec, I still don't think the proposed solution is quite what we want. The target element should not be focused. Instead, it should have the [focusing steps](https://html.spec.whatwg.org/#focusing-steps) run on it. The difference is that if the target element is not focusable, it is not focused. Maybe a bit pedantic, but thought it'd be worth clarifying here.

**Comment by tomasdev** [comment]
I would like this issue not to be auto-closed due to inactivity.
