### ISSUE TITLE
How can be used an angular app at the top of the html tree

### ISSUE THREAD

**Issue by DavidGangel** [angular/angular#3006]
Hi,

In Angular1 it was possible to:

`<html ng-app="my-app">`

But how the same thing can be achieved with angular2 at the top level of the html?

**Comment by pkozlowski-opensource** [comment]
There is no direct equivalent of `ngApp` directive in Angular 2, but you can bootstrap an application on any element that you can target with an element CSS selector.

**Comment by DavidGangel** [comment]
I did the following:
`<html id="my-app">
  <head>
    <script src="https://github.jspm.io/jmcriffey/bower-traceur-runtime@0.0.87/traceur-runtime.js"></script>
    <script src="https://jspm.io/system@0.16.js"></script>
    <script src="https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js"></script>
    <script>System.import('app');</script>
  </head>
  <body>
     

	
  </body>
</html>`

app.ts:
`
/// <reference path="typings/angular2/angular2.d.ts" />
import {Component, View, bootstrap} from 'angular2/angular2';

@Component({
  selector: '#my-app'
})
@View({
  template: '<title>Angular second title</title>'
})
// Component controller
class MyAppComponent {
  name: string;
  
  constructor() {
    this.name = 'Alice';
  }
}
bootstrap(MyAppComponent);
`

Of course it's not working as the text can't be printed directly under the html tag.

What I would like to reach is to be able to manipulate the title tag inside the head tag through angular app as it's needs to be changed through navigation.

**Comment by pkozlowski-opensource** [comment]
@DavidGangel if it is about setting title you should be using the `Title` service: https://github.com/angular/angular/blob/master/modules/angular2/src/services/title.ts - you will have to inject it into places where you want to change title.

**Comment by DavidGangel** [comment]
Hi,

Thank you for your response. Okay I will take a look. Are there any modules for meta tag manipulation as well?

Thank you.

**Comment by pkozlowski-opensource** [comment]
Nope, there are no services for manipulating meta tags yet, but it could be a reasonable feature request, depending on your use-case. Could you please open a separate issue for this, specifically asking for a way to manipulate meta tags.

**Comment by DavidGangel** [comment]
Okay, thank you.
Raised ticket for meta manipulation under:
#3144
