### ISSUE TITLE
Incremental builds fail with ngtsc

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#30079]
There has been a regression in 8.0.0-beta.14 when using incremental builds in the CLI with ngtsc.

The second compilation fails and the root cause is that the old ts program is being re-used multiple times.

In the first compilation the current program is passed as the old/original program from
https://github.com/angular/angular/commit/98f86de8daf0fd4f29dd4fb98932aa7fc6ff66da#diff-c58dc797e5c0e361e5b797b30a767093R415

to
https://github.com/angular/angular/commit/98f86de8daf0fd4f29dd4fb98932aa7fc6ff66da#diff-b82ae8412104bda23cd21d0633add98fR184

The problem is that when creating a ts program the old ts program will be mutated which is causing the returned ts program from the original invocation of `createProgram` to be marked as reused, and on the subsequent compilation from the cli we are passing a re-used old program to the `createProgram` 

Talking to @alxhub offline about this.

**Comment by alxhub** [comment]
[Presubmit](http://test/OCL:245073473:BASE:245073510:1556127896200:ef1d2909)
