### ISSUE TITLE
Interpolation with {{property}} writes null and undefined rather than empty string

### ISSUE THREAD

**Issue by firecube** [angular/angular#3007]
A quick test with the quick start can reproduce this... https://angular.io/docs/js/latest/quickstart.html

Change the line below and you can see the work null written to screen.

Change...
this.name = 'Alice';
... to ...
this.name = null;

**Comment by vicb** [comment]
Work as epxected: in JS `'' + null == 'null'`

**Comment by firecube** [comment]
In Angular 1.x I could just bind to a variable like this {{name}} and if name was null nothing was shown on screen.  

In Angular 2, {{name}} seems to output the word 'null' which may be as expected but isn't very friendly.  

I don't want to have to do something like {{name || ''}} in my templates.

Am I missing something here or is there another way to approach this?

Thanks, Simon

**Comment by pkozlowski-opensource** [comment]
@vicb it is true that this is consistent with JS behaviour but I don't think this is what users would expect (at least I find it surprising) and it is not how things work in ng1.

I'm going to re-open this one so we can discuss. //cc: @mhevery

**Comment by caitp** [comment]
> @vicb it is true that this is consistent with JS behaviour but I don't think this is what users would expect (at least I find it surprising) and it is not how things work in ng1.

What would you expect, jus `''` in place of `'null'`?

**Comment by pkozlowski-opensource** [comment]
Yep, empty string. This is how it is handled in ng1, no?

**Comment by caitp** [comment]
i dunno, I think there's value in matching the language itself (eg ``` `${null}` ``` -> `"null"`), but whatever people want to do

**Comment by firecube** [comment]
In templates it should definitely handle nulls and undefined with empty string... otherwise this needs to be done by the user on every place holder in every template.

pkozlowski-opensource is right, this is the behaviour in Angular 1.

**Comment by gdi2290** [comment]
It might be a good idea to have default values 
```typescript
class App {
  name: string = '';
  constructor(service: Service) {
    service.subscribe(data => this.name = data.name);
  }
}

(`undefined` is also shown when using JitChangeDetection but not during DynamicChangeDetection)

**Comment by vicb** [comment]
What about `{{ value|default('') }}`

**Comment by gkalpak** [comment]
What about it ? :D
Just compare it with `{{ value }}`.

--
This is a really nice feature of ng1 (and one lots of developers are used to) and plays well with the elvis operator (which also everyone is used to from ng1 - well not the operator, just the behaviour (grrrr for introducing that btw)).

 TBH I haven't fiddled around much with ng2, so I don't know if the usefulness of defaulting to `''` has diminished.

**Comment by dsebastien** [comment]
@gdi2290 Is there a specific reason for the different behavior between DynamicChangeDetection and JitChangeDetection? If the detection mode is selected on startup, I'd assume it is because of some kind of feature/environment detection, but why would the end result be different for developers?

I agree with @gkalpak @pkozlowski-opensource that {{ bla }} should default to '' in the UI. I don't think having undefined or null visible in a UI is ever useful. Default values are an option but can be complicated assuming that the binding points to a class instance property.

Maybe having a hook to enable debug logging during development might be interesting (i.e., providing a way to let developers know that there might be something wrong).

**Comment by mhevery** [comment]
`null` should be `""` (empty string) User should never see `null`

**Comment by gdi2290** [comment]
while we're on the topic can we also make it to so for all `src` attributes otherwise it's `src="null"` which makes an http call to /null

**Comment by kernyden** [comment]
@pkozlowski-opensource but what ab this expression {{ value1 +  '(' + value2 + ')' }} ? It doesnt compile well --> null(undefined)

**Comment by pkozlowski-opensource** [comment]
@kernyden please open a new issue with a minimal reproduction scenario (stackblitz).
