### ISSUE TITLE
simple ngFor isn't working with Angular 7.X and Ivy preview 

### ISSUE THREAD

**Issue by eliraneliassy** [angular/angular#30081]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?

Yes

### Description

ngFor not working when generating new IVY project with angular V7.
I'm not getting any console exceptions but not getting anything out from my ngFor loop.  

## 🔬 Minimal Reproduction
Since this is an IVY issue, I can't run it on stackblitz.
Created this minimal repo on Github: 
https://github.com/eliraneliassy/ivy-ngfor-bug 

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.8
Node: 11.6.0
OS: darwin x64
Angular: 7.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**
No

**Comment by eliraneliassy** [comment]
After upgrading to v8-beta14 it seems like it works.

I've added another branch in the same repo:
https://github.com/eliraneliassy/ivy-ngfor-bug/tree/upgrade-v8-beta

Not sure if it worth the fix if it will be fixed in the next version...

**Comment by JoostK** [comment]
v7 has not received Ivy updates for quite some time now, so its Ivy renderer is quite outdated. Given that this seems to have been fixed in v8, I will close this issue.
