### ISSUE TITLE
Decorator or compiler-flag that treeshakes code in production and keeps code in dev mode.

### ISSUE THREAD

**Issue by andreElrico** [angular/angular#30083]
I've found these two related posts:

https://stackoverflow.com/questions/42307317/stripping-all-comments-and-console-logs-with-ng-build-prod-possible

and 

https://github.com/angular/angular-cli/issues/10999

# 🚀 feature request

Can there be a decorator that removes or keeps a code block based on the compile/build process (dev/ prod)?

### Describe the solution you'd like

So lets say our pseudo workspace code looks like:

```
prod code1
prod code2

@treeshakeInProd() {
    dev code1
    dev code2
}

prod code3
```

dev code looks like (normal ng build/ ng serve results)

```
prod code1
prod code2

dev code1
dev code2

prod code3
```

prod code looks like (--prod flag)

```
prod code1
prod code2


prod code3
```

### Describe alternatives you've considered
I have looked at the solution in the links above. I want to have NO reference/clue of the "dev code#" in prod-mode.

Any suggestions?

**Comment by Airblader** [comment]
Decorators cannot be wrapped around arbitrary code:

> A Decorator is a special kind of declaration that can be attached to a class declaration, method, accessor, property, or parameter.

– https://www.typescriptlang.org/docs/handbook/decorators.html

**Comment by andreElrico** [comment]
> Decorators cannot be wrapped around arbitrary code:
> 
> > A Decorator is a special kind of declaration that can be attached to a class declaration, method, accessor, property, or parameter.
> 
> – https://www.typescriptlang.org/docs/handbook/decorators.html

Thank you, the Decorator was just a random pseudo Code representation. I have generalized the topic title to "compiler-flag". So when the compiler hits this "flag" it should operate as desribed.

Maybe that could be a typescript feature :/ ?

**Comment by Airblader** [comment]
You can import the environment file and do

```
if (!environment.production) {
    // …
}
```
That's a flag which even exists already. Since the value is static I would think the optimizers can perform dead code elimination on it.

**Comment by andreElrico** [comment]
Sounds promising:

Do you have any references that could help me with: "optimizers can perform dead code elimination". Doesnt sound like too easy of a task :/.

**Comment by Airblader** [comment]
Thsts nothing you'd have to do. When you prod build, there are optimizers that run. I would hope they can eliminate this already. So I would just try it out.

**Comment by JoostK** [comment]
This is not something that Angular itself should have syntax for. Tools like Terser (the modern variant of Uglify) allow developers to insert hints to indicate that certain code can be elided as you request.

Please see [Terser's documentation](https://github.com/terser-js/terser/blame/fbebaaff9ff021bd46cc4dcb344348f3fbb3b57b/README.md#L818-L821).
