### ISSUE TITLE
ng build --watch with @angular/bazel

### ISSUE THREAD

**Issue by mgechev** [angular/angular#30089]
# 🚀 feature request

Introduce `ng build --watch`

### Relevant Package

 This feature request is for @angular/....

`@angular/bazel`

### Description
 A clear and concise description of the problem or missing capability...

In the webpack builder of Angular CLI we have `ng build --watch` which has similar semantics to `bazel run src:prodapp`.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

Invoke `bazel run src:prodapp` on `ng build --watch`

**Comment by kyliau** [comment]
@mgechev Is `ng serve` in the current CLI different from `ng build --watch`?
`ng serve` in Bazel already executes `ibazel run //src:devserver`.

**Comment by mgechev** [comment]
`ng build --watch` doesn't start a development server. `ng build --prod --watch` would be a better equivalent of our `bazel run src:prodapp`.

**Comment by mgechev** [comment]
Closing since we deprecated the Bazel schematics.
