### ISSUE TITLE
dgeni: When generating docs dgeni should preserve annotation

### ISSUE THREAD

**Issue by mhevery** [angular/angular#3008]
See: https://angular.io/docs/js/latest/api/directives/NgFor-class.html It should also include annotation such as: https://github.com/angular/angular/blob/f5f85bb528bcb697f433e3db95912562810bba28/modules/angular2/src/directives/ng_for.ts#L35

Annotations are important for the documentation purposes.

**Comment by naomiblack** [comment]
@petebacondarwin no idea if you can get to this before you leave... maybe?

**Comment by petebacondarwin** [comment]
@naomiblack and @mhevery - this was dealt with in #3167 and #3221, right?
