### ISSUE TITLE
Mistake in observables-in-angular#async-pipe documentation

### ISSUE THREAD

**Issue by cmrarjun** [angular/angular#30119]
Hi,

I think i found a mistake in https://angular.io/guide/observables-in-angular#async-pipe. i think you have missed to mention the unsubscribe method in the observable's subscriber function. i don't get how async pipe can unsubscribe without that. I may be wrong but please check that once and update if it is not correct.

**Comment by ericmartinezr** [comment]
https://angular.io/api/common/AsyncPipe#description

**Comment by cmrarjun** [comment]
Hi,
I have added console.log in the setInterval to see if it still publishes values after components gets destroyed. It is still publishing. Async pipe is not unsubscribing even if the component is destroyed.

`time = new Observable<string>((observer: Observer<string>) => {
      setInterval(() => {
          console.log('Publishing...');
          observer.next(new Date().toString());
        }, 1000);
    });`

**Comment by benlesh** [comment]
Please see the documentation linked by @ericmartinezr it covers your question. :)

**Comment by cmrarjun** [comment]
I saw that documentation. same is mentioned in that also. but it creates memory leak,
