### ISSUE TITLE
Build fails with FlexLayout when ivy is enabled

### ISSUE THREAD

**Issue by kccsf** [angular/angular#30114]
# 🐞 bug report
Enabling Ivy causes build to fail in a project that uses angular/flex-layout

### Affected Package
angular 8.0.0-beta.14
angular/flex-layout 7.0.0-beta.24

### Is this a regression?

Yes - works fine with ivy disabled.

### Description
Enabling Ivy causes build to fail in a project that uses angular/flex-layout

## 🔬 Minimal Reproduction
https://github.com/kccsf/AngularIvyFlexLayoutIssue

## 🔥 Exception or Error
<pre><code>
ERROR in ./node_modules/@angular/flex-layout/__ivy_ngcc__/esm5/extended.es5.js 156:578
Module parse failed: Unexpected token (156:578)
You may need an appropriate loader to handle this file type.
|         return _this;
|     }
> DefaultImgSrcDirective.ngDirectiveDef = ɵngcc0.ɵɵdefineDirective({ type: DefaultImgSrcDirective, selectors: [["img", "src.xs", ""], ["img", "src.sm", ""], ["img", "src.md", ""], ["img", "src.lg", ""], ["img", "src.xl", ""], ["img", "src.lt-sm", ""], ["img", "src.lt-md", ""], ["img", "src.lt-lg", ""], ["img", "src.lt-xl", ""], ["img", "src.gt-xs", ""], ["img", "src.gt-sm", ""], ["img", "src.gt-md", ""], ["img", "src.gt-lg", ""]], factory: function DefaultImgSrcDirective_Factory(t) { return ɵDefaultImgSrcDirective_BaseFactory((t || DefaultImgSrcDirective)); }, inputs: { src.xs: "src.xs", src.sm: "src.sm", src.md: "src.md", src.lg: "src.lg", src.xl: "src.xl", "src.lt-sm": "src.lt-sm", "src.lt-md": "src.lt-md", "src.lt-lg": "src.lt-lg", "src.lt-xl": "src.lt-xl", "src.gt-xs": "src.gt-xs", "src.gt-sm": "src.gt-sm", "src.gt-md": "src.gt-md", "src.gt-lg": "src.gt-lg" }, features: [ɵngcc0.ɵɵInheritDefinitionFeature] });
| const ɵDefaultImgSrcDirective_BaseFactory = ɵngcc0.ɵɵgetInheritedFactory(DefaultImgSrcDirective);
| /*@__PURE__*/ ɵngcc0.ɵsetClassMetadata(DefaultImgSrcDirective, [{
ERROR in ./node_modules/@angular/flex-layout/__ivy_ngcc__/esm5/flex.es5.js 195:653
Module parse failed: Unexpected token (195:653)
You may need an appropriate loader to handle this file type.
|         return _this;
|     }
> DefaultLayoutDirective.ngDirectiveDef = ɵngcc0.ɵɵdefineDirective({ type: DefaultLayoutDirective, selectors: [["", "fxLayout", ""], ["", "fxLayout.xs", ""], ["", "fxLayout.sm", ""], ["", "fxLayout.md", ""], ["", "fxLayout.lg", ""], ["", "fxLayout.xl", ""], ["", "fxLayout.lt-sm", ""], ["", "fxLayout.lt-md", ""], ["", "fxLayout.lt-lg", ""], ["", "fxLayout.lt-xl", ""], ["", "fxLayout.gt-xs", ""], ["", "fxLayout.gt-sm", ""], ["", "fxLayout.gt-md", ""], ["", "fxLayout.gt-lg", ""]], factory: function DefaultLayoutDirective_Factory(t) { return ɵDefaultLayoutDirective_BaseFactory((t || DefaultLayoutDirective)); }, inputs: { fxLayout: "fxLayout", fxLayout.xs: "fxLayout.xs", fxLayout.sm: "fxLayout.sm", fxLayout.md: "fxLayout.md", fxLayout.lg: "fxLayout.lg", fxLayout.xl: "fxLayout.xl", "fxLayout.lt-sm": "fxLayout.lt-sm", "fxLayout.lt-md": "fxLayout.lt-md", "fxLayout.lt-lg": "fxLayout.lt-lg", "fxLayout.lt-xl": "fxLayout.lt-xl", "fxLayout.gt-xs": "fxLayout.gt-xs", "fxLayout.gt-sm": "fxLayout.gt-sm", "fxLayout.gt-md": "fxLayout.gt-md", "fxLayout.gt-lg": "fxLayout.gt-lg" }, features: [ɵngcc0.ɵɵInheritDefinitionFeature] });
| const ɵDefaultLayoutDirective_BaseFactory = ɵngcc0.ɵɵgetInheritedFactory(DefaultLayoutDirective);
| /*@__PURE__*/ ɵngcc0.ɵsetClassMetadata(DefaultLayoutDirective, [{
ERROR in ./node_modules/@angular/flex-layout/__ivy_ngcc__/esm5/grid.es5.js 98:719
Module parse failed: Unexpected token (98:719)
You may need an appropriate loader to handle this file type.
|         return _this;
|     }
> DefaultGridAlignDirective.ngDirectiveDef = ɵngcc0.ɵɵdefineDirective({ type: DefaultGridAlignDirective, selectors: [["", "gdGridAlign", ""], ["", "gdGridAlign.xs", ""], ["", "gdGridAlign.sm", ""], ["", "gdGridAlign.md", ""], ["", "gdGridAlign.lg", ""], ["", "gdGridAlign.xl", ""], ["", "gdGridAlign.lt-sm", ""], ["", "gdGridAlign.lt-md", ""], ["", "gdGridAlign.lt-lg", ""], ["", "gdGridAlign.lt-xl", ""], ["", "gdGridAlign.gt-xs", ""], ["", "gdGridAlign.gt-sm", ""], ["", "gdGridAlign.gt-md", ""], ["", "gdGridAlign.gt-lg", ""]], factory: function DefaultGridAlignDirective_Factory(t) { return ɵDefaultGridAlignDirective_BaseFactory((t || DefaultGridAlignDirective)); }, inputs: { gdGridAlign: "gdGridAlign", gdGridAlign.xs: "gdGridAlign.xs", gdGridAlign.sm: "gdGridAlign.sm", gdGridAlign.md: "gdGridAlign.md", gdGridAlign.lg: "gdGridAlign.lg", gdGridAlign.xl: "gdGridAlign.xl", "gdGridAlign.lt-sm": "gdGridAlign.lt-sm", "gdGridAlign.lt-md": "gdGridAlign.lt-md", "gdGridAlign.lt-lg": "gdGridAlign.lt-lg", "gdGridAlign.lt-xl": "gdGridAlign.lt-xl", "gdGridAlign.gt-xs": "gdGridAlign.gt-xs", "gdGridAlign.gt-sm": "gdGridAlign.gt-sm", "gdGridAlign.gt-md": "gdGridAlign.gt-md", "gdGridAlign.gt-lg": "gdGridAlign.gt-lg" }, features: [ɵngcc0.ɵɵInheritDefinitionFeature] });
| const ɵDefaultGridAlignDirective_BaseFactory = ɵngcc0.ɵɵgetInheritedFactory(DefaultGridAlignDirective);
| /*@__PURE__*/ ɵngcc0.ɵsetClassMetadata(DefaultGridAlignDirective, [{
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0-beta.18
Node: 12.0.0
OS: win32 x64
Angular: 8.0.0-beta.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-beta.18
@angular-devkit/build-angular     0.800.0-beta.18
@angular-devkit/build-optimizer   0.800.0-beta.18
@angular-devkit/build-webpack     0.800.0-beta.18
@angular-devkit/core              8.0.0-beta.18
@angular-devkit/schematics        8.0.0-beta.18
@angular/cdk                      8.0.0-beta.2
@angular/cli                      8.0.0-beta.18
@angular/events                   <error>
@angular/flex-layout              7.0.0-beta.24
@ngtools/webpack                  8.0.0-beta.18
@schematics/angular               8.0.0-beta.18
@schematics/update                0.800.0-beta.18
rxjs                              6.5.1
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
Thanks for reporting. There is a known limitation for attribute names, where characters other than `-` are not escaped properly. This is causing the dot `.` in the property name to end up as raw property name, where it should be escaped.

**Comment by kccsf** [comment]
Thanks for the rapid feedback :-)

**Comment by tomskip123** [comment]
+1  on the v8

**Comment by fxck** [comment]
Any update on this?

**Comment by ronnyek** [comment]
I noticed that today with the recent "opt in blog article" I decided to try this again. I upgraded to 8.1.0-next.1, and have a totally blank new project which I've added @angular/flex-layout, and added an import in my app.module.ts.

Now I am seeing this error:
`ERROR in Node does not exist: C:/source/my-ivy-app/node_modules/@angular/flex-layout`

**Comment by briancvn** [comment]
![image](https://user-images.githubusercontent.com/11416798/59615712-34736d80-914d-11e9-9706-2697156e08e5.png)

**Comment by kschwidder** [comment]
Hi all, flex-layout is a key package for us. Therefore it should be processed properly by ivy. 
We will not get rid of flex-layout since it saves our days. Any news about this issue ?

**Comment by simeyla** [comment]
So if I'm not using the `.` syntax for responsive queries everything else will work fine with `flex-layout` ?

**Comment by ciel** [comment]
Yeah this is pretty game breaking here too.

**Comment by kccsf** [comment]
@Ismaestro Upgrade to 8.2.0-next.0

**Comment by Favna** [comment]
Upgrading to 8.2.0-next.0 does not resolve Ivy build issues for flex-layout, and the error remains the same. I have a repo with all latest versions that fails to build here: https://github.com/favware/website/tree/ivy. If you want to try it out then clone/download the repo, install packages with `yarn` and attempt a production build: `yarn build`

**Comment by JoostK** [comment]
@Favna I can't reproduce with your repo. Are you sure your `node_modules` is up-to-date with `8.2.0-next.0`.

**Comment by Favna** [comment]
Yes, I'm sure. Just now I made extra just by running `rm -rf node_modules yarn.lock && yarn`. It also failed on my CircleCI: https://circleci.com/gh/favware/website/278 (you can see the full error log in there too). Are you sure you were checking the `ivy` branch @JoostK?

Here is also the full log of `yarn` and `yarn build`, in PowerShell because my WSL was bugging out. https://hasteb.in/equwifes.coffeescript

**Comment by JoostK** [comment]
@Favna Yup, `ivy` branch. But as a matter of fact, those errors are not the same as the ones being reported here, yours are type-check errors. I'll have a look at why they are produced.

**Comment by Favna** [comment]
> But as a matter of fact, those errors are not the same as the ones being reported here, yours are type-check errors. I'll have a look at why they are produced.

Oh oops my bad! I got to this issue from a reference on the flex-layout repo so I blindly thought it would be the same error, should've checked. Anyway thanks for checking and looking forward to the answer.

**Comment by JoostK** [comment]
@Favna Ah, it's because `flex-layout` has dynamic inputs, i.e. declared inputs that do not have an associated property declaration for TypeScript, it's all handled during runtime:

https://github.com/angular/flex-layout/blob/d322ea75c00e2f2e9d9f467faccb4517a3868142/src/lib/flex/layout/layout.ts#L63-L66

We saw such a use-case before, see https://github.com/angular/angular/issues/30818#issuecomment-507210425, but there's no final design on how to deal with this properly at this moment. You can find details on how to disable type-checking for now in https://github.com/angular/angular/issues/30080#issuecomment-500499410.

**Comment by Favna** [comment]
Applying to workaround does in fact let the project build using Ivy. Am I understanding correctly that it's a known issue and it will be worked on in due time, meaning the issue doesn't have to be reported as a new issue here or in the flex-layout repo?

**Comment by JoostK** [comment]
@Favna I don't think it's tracked on its own, could you open an issue in this repo for the problem with dynamic inputs?

**Comment by petebacondarwin** [comment]
I have created an internal ticket to track this (FW-1433).

**Comment by duard** [comment]
```
Compiling @angular/core/testing : es2015 as esm2015

Compiling @angular/platform-browser-dynamic : es2015 as esm2015

Compiling @angular/platform-browser/testing : es2015 as esm2015

Compiling @angular/compiler/testing : es2015 as esm2015

Compiling @angular/platform-browser-dynamic/testing : es2015 as esm2015

Compiling @angular/common/testing : es2015 as esm2015

Compiling @angular/router : es2015 as esm2015

Compiling @angular/router/testing : es2015 as esm2015

Compiling @angular/router/upgrade : es2015 as esm2015

Compiling @angular/upgrade : es2015 as esm2015

Compiling @angular/upgrade/static/testing : es2015 as esm2015
                                                                                          
Date: 2019-07-19T17:57:58.970Z
Hash: 6b925fae8ae00c4a2c42
Time: 63764ms
chunk {main} main.js, main.js.map (main) 1.97 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 717 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 186 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 330 kB [initial] [rendered]

WARNING in Unknown member type: "[key: string]: (data: any) => void;

ERROR in node_modules/@angular/flex-layout/extended/typings/class/class.d.ts(30,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/extended/typings/img-src/img-src.d.ts(38,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/flex/typings/flex/flex.d.ts(50,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/align-columns/align-columns.d.ts(28,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/align-rows/align-rows.d.ts(28,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/areas/areas.d.ts(31,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/auto/auto.d.ts(31,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/columns/columns.d.ts(32,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/gap/gap.d.ts(31,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/rows/rows.d.ts(32,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

** Angular Live Development Server is listening on redecomprecerto.sigpharma.xyz:4200, open your browser on http://redecomprecerto.sigpharma.xyz:4200/ **
ℹ ｢wdm｣: Failed to compile.
ℹ ｢wdm｣: Compiling...
                                                                                          
Date: 2019-07-19T17:58:03.508Z - Hash: 85913cef8251329a3657 - Time: 4177ms
2 unchanged chunks
chunk {main} main.js, main.js.map (main) 16.5 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 130 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.15 MB [initial] [rendered]
ℹ ｢wdm｣: Compiled successfully.
    
    ERROR in node_modules/@angular/flex-layout/extended/typings/class/class.d.ts(30,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/extended/typings/img-src/img-src.d.ts(38,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/flex/typings/flex/flex.d.ts(50,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/align-columns/align-columns.d.ts(28,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/align-rows/align-rows.d.ts(28,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/areas/areas.d.ts(31,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/auto/auto.d.ts(31,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/columns/columns.d.ts(32,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/gap/gap.d.ts(31,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/rows/rows.d.ts(32,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

```
![ivy](https://user-images.githubusercontent.com/36894/61555587-1fcd1280-aa36-11e9-89f0-c0c8a4e5bb01.png)

**Comment by kKen94** [comment]
There is a lot of work to do if this issue is open yet, of course. 
But I can't believe that if I wanna use Ivy I have to remove flex-layout from the project or my application doesn't compile

**Comment by Splaktar** [comment]
@kKen94 Ivy is not yet ready for production. It's only available as an [opt-in compatibility preview](https://blog.angular.io/its-time-for-the-compatibility-opt-in-preview-of-ivy-38f3542a282f). The goal is to identify issues like this that can be resolved before Ivy is released for production.

**Comment by briancvn** [comment]
The issue solved with v8.2.2, although there are still some other issues. We know all you guys in Angular team worked hard for the new angular version.
Thank you very much and nervous waiting to see ivy stable.
![image](https://user-images.githubusercontent.com/11416798/62951330-fe343080-be13-11e9-8123-79a7e300d2d7.png)

**Comment by mrjpeterj** [comment]
For me, although it now builds, on the Ivy build `DefaultLayoutDirective` constructor gets called with no arguments and therefore fails shortly afterwards in `LayoutDirective.init`

**Comment by lneumeier** [comment]
> For me, although it now builds, on the Ivy build `DefaultLayoutDirective` constructor gets called with no arguments and therefore fails shortly afterwards in `LayoutDirective.init`

```
core.js:6014 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'init' of undefined
TypeError: Cannot read property 'init' of undefined
    at DefaultFlexDirective.init (core.js:463)
    at new FlexDirective (flex.js:851)
    at new DefaultFlexDirective (flex.js:967)
    at core.js:5954
    at NodeInjectorFactory.DefaultFlexDirective_Factory [as factory] (flex.js:971)
    at getNodeInjectable (core.js:5806)
    at instantiateAllDirectives (core.js:12859)
    at createDirectivesAndLocals (core.js:12229)
    at Module.ɵɵelementStart (core.js:21528)
    at SidenavComponent_Template (sidenav.component.html:12)
    at resolvePromise (zone-evergreen.js:797)
    at resolvePromise (zone-evergreen.js:754)
    at zone-evergreen.js:858
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:39687)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:559)
```

**Comment by Splaktar** [comment]
If you are still having issues, please open a new issue as this one is closed.
