### ISSUE TITLE
Sample app of the Testing chapter does not compile

### ISSUE THREAD

**Issue by siva636** [angular/angular#30137]
# 📚 Docs or angular.io bug report

### Description

 The sample app provided in the Testing chapter does not compile. The following error occurs when execute 'ng serve'
ERROR in src/app/model/testing/index.ts(1,15): error TS2307: Cannot find module './fake-hero.service'.
```
src/testing/jasmine-matchers.d.ts(3,67): error TS2694: Namespace 'jasmine' has no exported member 'CustomMatcher'.
src/testing/jasmine-matchers.ts(7,3): error TS2708: Cannot use namespace 'jasmine' as a value.
src/testing/jasmine-matchers.ts(12,32): error TS2694: Namespace 'jasmine' has no exported member 'CustomMatcher'.
src/testing/jasmine-matchers.ts(14,97): error TS2694: Namespace 'jasmine' has no exported member 'CustomMatcherResult'.

```

## 🔬 Minimal Reproduction
Download the sample app in the testing chapter, execute 'npm install' and then execute 'ng serve'

### What's the affected URL?**
 https://angular.io/guide/testing

### Expected vs Actual Behavior**

The sample should compile without errors when execute 'ng serve'

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by RRikor** [comment]
Besides the 4 jasmine errors, I am also getting this error when trying to run 'ng serve'
ERROR in src/app/model/testing/index.ts(1,15): error TS2307: Cannot find module './fake-hero.service'.

Using the 'Sample App' from https://angular.io/guide/testing

**Comment by kapunahelewong** [comment]
Since #30427 merged, it looks like this is resolved. I'll close this now, but if you have any further concerns @siva636 feel free to tag me here. Thanks for bringing this up! :)

**Comment by siva636** [comment]
@kapunahelewong I still get the following error:

```
ERROR in ./src/app/about/about.component.spec.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /Users/siva/Projects/Testing/specs.testing/src/app/about/about.component.spec.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/Users/siva/Projects/Testing/specs.testing/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:844:23)
    at pl
```

**Comment by kapunahelewong** [comment]
Thanks for letting me know, @siva636. I'll look into it and let you know what I find.

**Comment by kapunahelewong** [comment]
Possibly related to: #30939

**Comment by brandonroberts** [comment]
Fixed via https://github.com/angular/angular/pull/31120
