### ISSUE TITLE
inject is deprecated in v8, still referenced in examples

### ISSUE THREAD

**Issue by SarahGB** [angular/angular#30131]
# 📚 Docs or angular.io bug report

### Description
[inject](https://next.angular.io/api/core/inject) is deprecated in v8, but is still referenced in usage examples such as [InjectionToken](https://next.angular.io/api/core/InjectionToken#tree-shakable-injectiontoken)

### What's the affected URL?
https://next.angular.io/api/core/InjectionToken#tree-shakable-injectiontoken (for example)

**Comment by ericmartinezr** [comment]
Related https://github.com/angular/angular/pull/30132

**Comment by kara** [comment]
@SarahGB Thanks for pointing this out! The deprecation was a mistake, so #30132 should have removed the deprecation marker from that function.
