### ISSUE TITLE
Host properties are not set on root component

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#3013]
Repro: https://gist.github.com/jakemac53/795c4f1af486ccfb0014

This seems to be caused by the fact that we are creating a second temporary host element for the root component and calling `setAttribute` _before_ we attach content to the target host element.

/cc @jakemac53

**Comment by tbosch** [comment]
Note that this might be fixed by https://github.com/angular/angular/issues/2529 as this is changing the `DomRenderer`...

**Comment by matanlurey** [comment]
Let's make sure the following scenarios work:

1. You can set `'[class]': 'allOfMyClasses'` in the `host` property in a component
2. This also works on dynamically loaded components
3. This also works on the root-level (E.g. application shell component)

**Comment by tbosch** [comment]
Here is a PR that verifies that we can set properties, attributes and classes on the root element: https://github.com/angular/angular/pull/3085

However, what does not work is using `[class]`. Angular right now only supports using `[class.a]` or using `[className]`.

**Comment by tbosch** [comment]
Or you can use `[attr.class]`.

**Comment by tbosch** [comment]
Checked with @matanlurey that this is ok.
