### ISSUE TITLE
How to use same control {splitter } inside that control[same splitter]

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular#30142]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Sorry for the disturbance,

i have one question.i have posted it in stackoverflow but no reply can you guys please update this whethear my scenario is possible or not

https://stackoverflow.com/questions/55861030/how-to-use-same-control-inside-that-control-in-angular

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
