### ISSUE TITLE
Can't bind to 'for' since it isn't a know property of the 'label' element

### ISSUE THREAD

**Issue by woppa684** [angular/angular#3014]
Using:
```
<label for="{{id}}">
```
or
```
<label [for]="id">
```

in a template will throw the following error:

```
Can't bind to 'for' since it isn't a know property of the 'label' element and there are no matching directives with a corresponding property
```
Shouldn't this be possible?

**Comment by pkozlowski-opensource** [comment]
By default AngularJS binds to elements properties, not attributes and `for` is an attribute, not a property of the `<label>` element, see: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

You can use the `<label [attr.for]="id">` syntax to bind to attributes.
