### ISSUE TITLE
Angular7 Window Resize event does not work correctly

### ISSUE THREAD

**Issue by ALiuGuanyan** [angular/angular#30145]
![image](https://user-images.githubusercontent.com/42351146/56808327-c5bc1700-6863-11e9-9dd1-d4b83de90c55.png)
![image](https://user-images.githubusercontent.com/42351146/56808353-d7052380-6863-11e9-8843-f6935291b7f4.png)
Describe:
when I want to listen to the window size, it gives me this error. How to fix this problem?

![image](https://user-images.githubusercontent.com/42351146/56808399-fac86980-6863-11e9-85d2-270b83b3204d.png)

here are my dependencies:
![image](https://user-images.githubusercontent.com/42351146/56808490-36fbca00-6864-11e9-8c24-a886211d4244.png)

**Comment by ericmartinezr** [comment]
Works fine for me https://stackblitz.com/edit/angular-hnpttb?file=src%2Fapp%2Fapp.component.ts

**Comment by mlc-mlapis** [comment]
@ALiuGuanyan ... looks strange because of the message says `onWindowResize is not a function` ... where that method is called at all?

**Comment by ALiuGuanyan** [comment]
> @ALiuGuanyan ... looks strange because of the message says `onWindowResize is not a function` ... where that method is called at all?

I encapsulated a component, and when I use it in the app.component.html, it gives me this error.

**Comment by ALiuGuanyan** [comment]
> Works fine for me https://stackblitz.com/edit/angular-hnpttb?file=src%2Fapp%2Fapp.component.ts

what a pity, it does not work for my error

**Comment by mlc-mlapis** [comment]
@ALiuGuanyan ... hey, where do you call `onWindowResize` method?

**Comment by ALiuGuanyan** [comment]
> @ALiuGuanyan ... hey, where do you call `onWindowResize` method?

I never call onWindowResize method and I also did not declare onWindowResize, I do not even know why it appears.  I just want to listen to the window size, and I have tried @HostListener and other methods to achieve it, but all methods give me this error

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

<hr>

You need to provide a reproduction as required in the issue template

**Comment by mlc-mlapis** [comment]
@ALiuGuanyan ... do you understand that `onWindowResize` method can exist only as your own custom method (and later deleted it and forgot about it) and you have to call it somewhere? Did you try to search it in the code?
