### ISSUE TITLE
updateing my project from 7.3.x to 8-rc0 creates a syntax-error

### ISSUE THREAD

**Issue by web-dave** [angular/angular#30159]
I updated my project (webdave.de) from 7.3.x to 8-rc0
This created a strange syntaxerror at my pipe.

```bash
ng update @angular/cli @angular/core codelyzer --next
```
```typescript
import import { Pipe, PipeTransform, Injectable } from '@angular/core'; from '@angular/core';

@Injectable()
@Pipe({
  name: 'title'
})
export class TitlePipe implements PipeTransform {
  //  ...
}
```

my project is here
https://github.com/web-dave/ngx-blog
and the pipe is located here:
https://github.com/web-dave/ngx-blog/blob/master/src/app/framework/title.pipe.ts

After i fixed this manually, everything worked fine!

**Comment by web-dave** [comment]
My update result can be found at this branch
https://github.com/web-dave/ngx-blog/tree/cli-8-rc0

I had to update material and the CDK manually.
I guess the error occurs after the promt about migration strategy.
I choosed Template Stategy. (for no reason.)

**Comment by devversion** [comment]
cc. @crisbeto
