### ISSUE TITLE
@angular/bazel always generates WORKSPACE with yarn_install even if ng used npm

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#30164]
By default I do `ng new`, `ng add @angular/bazel`, I have a `package-lock.json` file but bazel fails because it looks for yarn.lock instead

**Comment by m-henderson** [comment]
so basically we should check to see if npm was used and if it was we need to look for a package-lock.json instead of yarn.lock?

**Comment by alexeagle** [comment]
Workaround is to create projects with yarn
`ng config -g cli.packageManager yarn`
or manually change the `WORKSPACE` file produced by the `@angular/bazel` schematic to use `npm_install` in place of `yarn_install`

The fix is for the schematic to be written with an `npm_install` rule if npm was used, yes
