### ISSUE TITLE
Live reload cannot be disabled in version 8

### ISSUE THREAD

**Issue by pe8ter** [angular/angular#30175]
# 🐞 bug report

### Affected Package

The issue is caused by package **@angular/cli**

### Is this a regression?

Yes, the previous version in which this bug was not present was: **7.3.8**

### Description

Disabling live reload when serving an app using `ng serve --liveReload=false` fails to disable live reloading.

## 🔬 Minimal Reproduction

1. Create a default application: `ng new my-app`.
2. Serve with live reload disabled: `ng serve --liveReload=false`.
3. Edit then save any HTML/CSS/TypeScript file.

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 8.0.0-rc.1
Node: 10.15.3
OS: darwin x64
Angular: 8.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.1
@angular-devkit/build-angular     0.800.0-rc.1
@angular-devkit/build-optimizer   0.800.0-rc.1
@angular-devkit/build-webpack     0.800.0-rc.1
@angular-devkit/core              8.0.0-rc.1
@angular-devkit/schematics        8.0.0-rc.1
@ngtools/webpack                  8.0.0-rc.1
@schematics/angular               8.0.0-rc.1
@schematics/update                0.800.0-rc.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0</code></pre>

**Comment by JoostK** [comment]
Hi @pe8ter,

thank you for trying out 8.0 RC. As this is an issue with the CLI, [could you reopen this issue in the CLI repo?](https://github.com/angular/angular-cli/issues/new?template=1-bug-report.md)
