### ISSUE TITLE
Template-driven form validation syntax

### ISSUE THREAD

**Issue by tebinumbiz** [angular/angular#30172]
# 📚 Docs or angular.io bug report

### Description

 In the Angular.io documentation for form validation, the example for displaying an error message to improve user experience indicates that the developer should place a question mark behind the "errors" property in the *ngIf clause. When copying the example, I have found that this does not work, the question mark should go behind the variable name instead. This may be a syntax changed due to versioning. The version in my package.json file is set to ""@angular/forms": "~7.2.0""

### Expected vs Actual Behavior**

Example 1 (Resolves to error):
```
<div class="form-group">
		<input id="firstName" name="firstName" class="form-control"
                required 
                ngModel #firstName="ngModel"  (change)="log('testing123')"
                type="text" >

        <div class="alert alert-danger" *ngIf="firstName.touched && !firstName.valid" >
     <--  ERROR HERE ->>>  --/>        <div  *ngIf="firstName.errors?.required"> First name is required.</div>
		</div>
</div>
```

Example 1 (Successful code):
```
<div class="form-group">
		<input id="firstName" name="firstName" class="form-control"
                required 
                ngModel #firstName="ngModel"  (change)="log('testing123')"
                type="text" >

        <div class="alert alert-danger" *ngIf="firstName.touched && !firstName.valid" >
     <--  FIXED ->>>  --/>        <div  *ngIf="firstName?.errors.required"> First name is required.</div>
		</div>
</div>
```

### What's the affected URL?**
 https://angular.io/guide/form-validation

## 🔥 Exception or Error
<pre><code>

Identifier 'required' is not defined. '__type' does not contain such a member
</code></pre>

### Reproduction Steps**
1. Create new angular app using version ~7.2.0
2. Create new template-driven form
3. Add input control and add validations per documentation (https://angular.io/guide/form-validation)
 -- specifically "<div *ngIf="<control name>.errors?.required"> First name is required.</div>

**Comment by tebinumbiz** [comment]
I'm relatively new to Angular, so it may be that I'm accessing older documentation? The site does not identify the targeted versions, so my assumption is that this url assumes the developer is using the latest version. (url: https://angular.io/guide/form-validation)

**Comment by Orodan** [comment]
Actually the documentation seems to have evolve as I can't find the example you're describing.

Also the question mark is called [the safe navigation operator](https://angular.io/guide/template-syntax#safe-navigation-operator) and it's purpose is to allow the developer to simplify the access of properties on a potentially null object, so it made sense to use it this way : 
```
firstName.errors?.required 
```
because in your example your firstName object is supposed to always be defined in your component, while the errors property can be null so you need to use the safe navigation operator to not crash your view.

I think this issue can be closed :)

**Comment by kapunahelewong** [comment]
Thank you @Orodan for answering this! @tebinumbiz I'll go ahead and close this but if you have any further questions, please feel free to tag me here and we can revisit. Thanks for filing this. :)
