### ISSUE TITLE
Wrong example for outputs option in Component decorator

### ISSUE THREAD

**Issue by saiKumarGanji** [angular/angular#30176]
# 🐞 bug report

### Is this a regression?
Not aware

### Description
Wrong example for outputs option in Component decorator.
Please refer the link https://angular.io/api/core/Directive#outputs

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/29523, fixed by https://github.com/angular/angular/pull/30014

**Comment by AndrewKushnir** [comment]
@saiKumarGanji thanks for noticing the problem and reporting it. As @ericmartinezr mentioned, it seems like a duplicate of #29523, so I'm closing this ticket. You can get the latest status by following [this link](https://github.com/angular/angular/issues/29523). Thank you.
