### ISSUE TITLE
Is the loading problem of the network not downloaded to the corresponding package or the problem introduced by the workspace file

### ISSUE THREAD

**Issue by weibon** [angular/angular#30182]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

![捕获](https://user-images.githubusercontent.com/24470508/56878974-37c17580-6a89-11e9-8b11-92a827604ad3.PNG)

what is the meaning

![捕获1](https://user-images.githubusercontent.com/24470508/56879156-fe3d3a00-6a89-11e9-854f-ca69318ea839.PNG)

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by JoostK** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
