### ISSUE TITLE
Open Desktop(winform) exe using angular6 application

### ISSUE THREAD

**Issue by kiranmahi999** [angular/angular#30186]
var shell = new ActiveXObject("WScript.shell");
    var bookmarktagexe = 'C:\\Users\\Public\\Documents\\BookMarkTag\\BookMarkTag.exe';
    shell.run('"' + bookmarktagexe + '"' + '"' + this.form.docxurl + '"', 1);

Thank you!

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
