### ISSUE TITLE
Multiple dynamic content projection

### ISSUE THREAD

**Issue by DenisRoss** [angular/angular#30184]
Need advice about best way how to make multiple dynamic content projection.
Situation, than we have parrent component template like this:
```
<tabs [count] = 'n'>
    <div tab_1>...</div>
    <div tab_2>...</div>
    ...
    <div tab_n-1>...</div>
    <div tab_n>...</div>
</tabs>
```
And expected that child (Tabs) component template will be like that:
```
...
<ng-content select='[tab_1]'></ng-content>
<hr/>
<ng-content select='[tab_2]'></ng-content>
...
<ng-content select='[tab_n-1]'></ng-content>
<hr/>
<ng-content select='[tab_n]'></ng-content>
...
```
In this case we have a problem, because we can't use ng-content like this one:
```
<div *ngFor="let item of [1, 2, ... , n - 1, n]]"> 
    <ng-content select='[tab_{{n-1}}]'></ng-content>
</div>
```
ng-content select is static, we can't use expression here.

How we can get array of content childs to use it in *ngFor?

**Comment by diicar** [comment]
```
<tabs ...>

  <div *ngFor="let item of items"> 
    ...
  </div>

</tabs>
```

Then, in yours tabs template

```
...
 <ng-content></ng-content>
...
```

IMO, multiple is only useful if you trying to project into different slots.

**Comment by DenisRoss** [comment]
@diicar sorry, but looks like i made bad explanation.

Imagine we have Tabs component:

```
<tabs>
    <div t1>
       <!-- Some conent in 1 tab -->
     </div>
    <div t2>
       <!-- Some conent in 2 tab -->
     </div>
    <div t3>
       <!-- Some conent in 3 tab -->
     </div>
</tabs>
```
And in `tabs` component template we want to wrap each of child `div` in some container.

so in `tabs` template we want to have something like:

  <div *ngFor="let item of ['t1', 't2', 't3]"> 
     <some_wrapper_container>
          <ng-content select='item'></ng-content>
     </some_wrapper_container>
  </div>

but we don't know how many of tabs we will have.

**Comment by diicar** [comment]
I do not understand what is preventing you to wrap the projected content in host component

**Comment by DenisRoss** [comment]
@diicar where will be different html content, like here:

```
<tabs>
    <div t1>
         <h1>hello world</h1>
         <p>some text</p>
     </div>
    <div t2>
         <button>activate</button>
     </div>
    <div t3>
         <a href='/faq'>Get help here</a>
     </div>
</tabs>
```

**Comment by diicar** [comment]
```
<tabs>
     <some_wrapper_container>
         <h1>hello world</h1>
         <p>some text</p>
     </some_wrapper_container>
    <some_wrapper_container *ngFor="let item of items">
         <button>activate</button>
    </some_wrapper_container>
    <some_wrapper_container>
         <a href='/faq'>Get help here</a>
     </some_wrapper_container>
</tabs>
```

and in your SomeWrapperComponent's template :

```
...
 <ng-content></ng-content>
...
```
Otherwise, I don't know

**Comment by DenisRoss** [comment]
@diicar XD 
Idea in that we need some_wrapper to use in tabs template, not in host) I don't know how we can reach this case. I try to ask on stackoverflow but have no response there.

**Comment by mlc-mlapis** [comment]
@DenisRoss ... it's possible using `select`, like:
```
<ng-content select=".my-class"></ng-content>
<ng-content select="div[role=intro]"></ng-content>
<ng-content select="ng-container[role=header]"></ng-content>
```

**Comment by DenisRoss** [comment]
@mlc-mlapis i know about select, but we can't use it on dynamic content, then you don't know how many childs will have host. Or i don't know how to do it(

**Comment by mlc-mlapis** [comment]
@DenisRoss ... ah, you mentioned that earlier, I missed that. No, you can do it for dynamic content (as generated via *ngFor) because of Angular compiler generates all relevant JS code in AOT mode and not in run-time in a browser, where the compiler is not loaded at all. There is no way how to do it using `<ng-content>` concept. You probably have to you several `<ng-template>` and references to them.

**Comment by DenisRoss** [comment]
@mlc-mlapis thx for answer, but can you explaine or make a simple example - how to do it using <ng-template> ? I will be very thankful because i can't serach good example of my case in google(

**Comment by alxhub** [comment]
@DenisRoss: As others have mentioned, a pretty standard way to do this is to use a template directive, and query for `TemplateRef`s directly. Here's an [example for you](https://stackblitz.com/edit/wrap-projected-templates?file=src/app.ts).

I'm going to close this issue as there is no bug or feature request here for Angular, but please let me know if that example clarifies things for you.

**Comment by mlc-mlapis** [comment]
@DenisRoss ... or with some type of registry ... https://stackblitz.com/edit/angular-hkwoby
