### ISSUE TITLE
support reportValidity for FormGroup

### ISSUE THREAD

**Issue by s97712** [angular/angular#30185]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/forms

### Description
 
support `reportValidity` for FormGroup, like the html5 form, if validate fail, it can scroll into the input and show error info.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by kara** [comment]
@s97712 `FormGroup` supports the `valid` and `invalid` properties, which should report whether the group is valid. It also emits a `statusChanges` event when the status changes, so you should be able to hook into it. If there is more functionality you're looking for than that, please open a new issue that fills out our template so we can look into it.
