### ISSUE TITLE
bazel: opt-out doesn't exclude two files that import generated modules

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#30188]
repro: 8.0-rc.1, create a project with Bazel

Try to opt-out following instructions on next.angular.io/guide/bazel

Error:
ERROR in src/main.dev.ts(2, 34): error TS2307: Cannot find module './app/app.module.ngfactory'.
src/main.prod.ts(3, 34): error TS2307: Cannot find module './app/app.module.ngfactory'.

We should either tell users to delete these two files, or add them to the ignore of the tsconfig.json used in compilations in this folder.

**Comment by alxhub** [comment]
Closing as obsolete - the Bazel builder and associated CLI functionality are deprecated and no longer supported.
