### ISSUE TITLE
bazel schematic adds comment in angular.json, not permitted by workspace API

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#30190]
After opting-out from Bazel, both the angular.json (which was copied from angular.json.bak) and the tsconfig.json (copied from tsconfig.json.bak) contain a comment on the first line like
`// this is a backup file of the original angular.json`

If I now run a command that invokes the workspace API, such as `ng add @angular/bazel`
the CLI errors:

`Invalid JSON character: "/" at 0:0.`

**Comment by alxhub** [comment]
Closing as obsolete - the Bazel builder and associated CLI functionality are deprecated and no longer supported.
