### ISSUE TITLE
CSS not applied to dynamically generated svg:circle 

### ISSUE THREAD

**Issue by gunsh** [angular/angular#30193]
# 🐞 bug report

The issue seems to be  caused by package @angular/core

### Is this a regression?

Yes. Stackblitz shows the issue with 6.1.9 while the actual project uses 7.2.14.

### Description

CSS applied as expected to SVG elements if a template has literal SVG code. If SVG dynamically generated (via a subcomponent), no CSS applied. Please see two simple SVG side-by-side in the provided sample. One features a red circle (explicitly provided) and a red-wannabe (but actually black) when dynamically generated by a child component.

I have found past issues that mention using _ViewEncapsulation.ShadowDom_ as a workaround. Even though this fixes the circle color, it also introduces the disappearance of _FontAwesome < i >_.

 On the other hand, using _ViewEncapsulation.None_ is not an option as it messes with the entire app's CSS.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/css-not-applied-to-svg-circle

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.8
Node: 10.12.0
OS: win32 x64
Angular: 7.2.14
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cdk                      7.3.7
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.5.1
typescript                        3.2.4
webpack                           4.29.0</code></pre>

**Anything else relevant?**
Not browser specific. Reproduced in latest Chrome, Firefox, IE11 (Edge barfs upon loading Stackblitz).

**Comment by alexzuza** [comment]
If we open Angular docs https://angular.io/guide/component-styles#style-scope we can read the following:

**The styles specified in @Component metadata apply only within the template of that component.**

That means that your child component can't take styles from parent component by default. I would try:

```
:host ::ng-deep .color-1 { fill: red; }
```

https://stackblitz.com/edit/css-not-applied-to-svg-circle-skuiw4?file=src/app/app.component.ts

**Comment by gunsh** [comment]
That does the trick. Thank you.

Closing.
