### ISSUE TITLE
how to set http flag in Angular i have used ngx-cookie service..and i have valid ssl certificate.

### ISSUE THREAD

**Issue by sagargitui** [angular/angular#30197]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by sagargitui** [comment]
this.cookieService.set( 'Test', 'HelloWorld',365,'/' ,null,true,"Strict"); how to set http flag in Angular

**Comment by kara** [comment]
Closing this issue as it does not fill in the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
