### ISSUE TITLE
Destructuring and AoT

### ISSUE THREAD

**Issue by Springrbua** [angular/angular#30206]
# 🐞 Bug report

### Affected Package
compiler

### Description

When using destructuring in a module-factory, the AoT-build seems to create a bundle with the wrong value.
The following code provides ` {prop1:{prop1:"prop1",prop2:"prop2"},prop2:undefined} ` instead of `{prop1:"prop1",prop2:"prop2"}`:
```
public static forRoot(
    { prop1 = "prop1", prop2 = "prop2" }: Partial<Bug>
): ModuleWithProviders
{
    return {
        ngModule: BugModule,
        providers: [
            { provide: BUG_TOKEN, useValue: { prop1, prop2 } },
        ]
    };
}
```
I inspected the generated `main.*.js` and it seems like the AoT-build inlines the value, but it is not calculated correctly.

## 🔬 Minimal Reproduction

A minimal reproduction can be found [here](https://github.com/Springrbua/aot-destructuring-bug).
Steps to reproduce:

1. Execute `ng build --prod`
2. Open `main.*.js` and search for `prop1`. You will find the following Object:  
    `{prop1:{prop1:"First Property",prop2:"Second Property"},prop2:void 0}`
3. Open `bug.module.ts` and enable the workaround by removing the comment form line 9 and line 16 and putting line 8 and line 15 in comment instead.
4. Run `ng build --prod` again.
5. Open the new `main.*.js` and search for `prop1` again. Now the Object has the correct value  
    `{prop1:"First Property",prop2:"Second Property"}`

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.8
Node: 10.14.0
OS: win32 x64
Angular: 7.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**
I was looking for this issue and found an article on angular.io, which says that [Destructured variables are not supported in AoT](https://angular.io/guide/aot-compiler#destructured-variable-not-supported).  
I am not sure if this also applies for my example, but if it does, it should probably show an error instead of resulting in a wrong bundle.
I already created this [issue in angular/angular-cli](https://github.com/angular/angular-cli/issues/14302) and was told that I should open it here, as it is a compiler issue.

**Comment by JoostK** [comment]
This particular example is no longer an issue, although destructuring is still not fully supported in Ivy. Tracking in #21227.
