### ISSUE TITLE
angular 使用懒加载，懒加载js文件的路径如何修改配置

### ISSUE THREAD

**Issue by yinuocode** [angular/angular#30205]
angular6（其实2~7一样）中使用懒加载
打包生成的js里面会包含懒加载的js文件
现在这些js文件全部放到另外的服务器上
index.html引入的只有不是懒加载的js文件
当页面运行时，运行到懒加载模块时，会请求加载改模块的懒加载js文件
这个时候控制台的懒加载文件地址是当前域名的地址
因为js文件不在当前域名下面，所以报404，文件找不到
那请问在哪可以配置请求懒加载文件的js地址？

看下报错信息显示懒加载js是在runtime.js中执行加载的
手动修改runtime.js里面引入懒加载js文件的路径当然是可以的
但是这明显不适合，压缩后的代码改动比较不妥。
所以想问下在哪里可以配置懒加载文件的路径，而不是默认当前域名请求懒加载js文件

各种搜索并未找到答案，期待哪位大神能帮我解决下

**Comment by JoostK** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
