### ISSUE TITLE
Cannot read property 'prototype' of undefined in angular 7

### ISSUE THREAD

**Issue by i-am-vivek** [angular/angular#30211]
### Description
I've added my code below
```
import { Component, OnInit } from '@angular/core';
import { Web3ProviderEngine, MetamaskSubprovider } from '0x.js';
import { SignerSubprovider } from '@0x/subproviders';

declare var web3: any;
const providerEngine = new Web3ProviderEngine();

const signer = (web3.currentProvider as any).isMetaMask
  ? new MetamaskSubprovider(web3.currentProvider)
  : new SignerSubprovider(web3.currentProvider);


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  title = 'angular-ui-zero-x';
  // public get providerEngine() { return }
  ngOnInit() {
  }
}

```

When I try to run, I'm getting following error in the browser console.

> Uncaught TypeError: Cannot read property 'prototype' of undefined
>     at inherits (inherits_browser.js:5)
>     at push../node_modules/keccak/lib/api/keccak.js.module.exports (keccak.js:21)
>     at push../node_modules/keccak/lib/api/index.js.module.exports (index.js:6)
>     at Object../node_modules/keccak/js.js (js.js:2)
>     at __webpack_require__ (bootstrap:78)
>     at Object../node_modules/ethereumjs-util/dist/index.js (index.js:5)
>     at __webpack_require__ (bootstrap:78)
>     at Object../node_modules/@0x/utils/lib/src/address_utils.js (address_utils.js:3)
>     at __webpack_require__ (bootstrap:78)
>     at Object../node_modules/@0x/utils/lib/src/index.js (index.js:5)

If I remove the following line, it is working properly.

```
const providerEngine = new Web3ProviderEngine();

const signer = (web3.currentProvider as any).isMetaMask
  ? new MetamaskSubprovider(web3.currentProvider)
  : new SignerSubprovider(web3.currentProvider);
```

**Angular Version:**

Angular CLI: 7.2.4
Node: 10.15.0
OS: darwin x64
Angular: 7.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.2.4
@angular/cli                      7.2.4
@ngtools/webpack                  7.2.4
@schematics/angular               7.2.4
@schematics/update                0.12.4
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.30.0

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
