### ISSUE TITLE
https://angular.io/api/router/ExtraOptions#properties ... this page renders properties off the right side and cant see them

### ISSUE THREAD

**Issue by gubo** [angular/angular#30218]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/27296

**Comment by kara** [comment]
Closing as duplicated of #27296
