### ISSUE TITLE
Observable don't seem to work with Chrome 41

### ISSUE THREAD

**Issue by glemiere** [angular/angular#30220]
Hi! I am currently trying to make my Angular 7 app to get crawled by Google properly, but unfortunately it seems like using HttpClient creates some trouble when I subscribe to it or attempt to convert it to a promise.

When using HttpClient, chrome 41 throws the following error:

```
TypeError: Cannot read property 'call' of undefined {stack: (...), message: "Cannot read property 'call' of undefined"}
errors.ts:35defaultErrorLogger
error_handler.ts:51push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError
application_ref.ts:230next
event_emitter.ts:110push../node_modules/@angular/core/fesm5/core.js.EventEmitter.subscribe.schedulerFn
Subscriber.ts:266push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub
Subscriber.ts:208push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next
Subscriber.ts:140push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next
Subscriber.ts:100push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next
Subject.ts:71push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next
event_emitter.ts:92push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit
ng_zone.ts:296(anonymous function)
zone.js:391push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke
zone.js:150push../node_modules/zone.js/dist/zone.js.Zone.run
ng_zone.ts:218push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular
ng_zone.ts:296onHandleError
zone.js:395push../node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError
zone.js:245push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask
zone.js:261push../node_modules/zone.js/dist/zone.js.Zone.scheduleMacroTask
zone.js:1194scheduleMacroTaskWithCurrentZone
zone.js:3371(anonymous function)
zone.js:1518push../node_modules/zone.js/dist/zone.js.proto.(anonymous function)
xhr.ts:319push../node_modules/@angular/common/fesm5/http.js.HttpXhrBackend.handle
Observable.ts:239push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe
Observable.ts:221push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe
subscribeToResult.ts:29subscribeToResult
mergeMap.ts:156push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._innerSub
mergeMap.ts:149push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext
mergeMap.ts:132push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next
Subscriber.ts:100push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next
subscribeToArray.ts:11push../node_modules/rxjs/_esm5/internal/util/subscribeToArray.js.subscribeToArray
Observable.ts:239push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe
Observable.ts:221push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe
mergeMap.ts:111push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapOperator.call
Observable.ts:215push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe
filter.ts:72push../node_modules/rxjs/_esm5/internal/operators/filter.js.FilterOperator.call
Observable.ts:215push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe
map.ts:60push../node_modules/rxjs/_esm5/internal/operators/map.js.MapOperator.call
Observable.ts:215push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe
...
...
...
```

I did a simple check by replacing this:

```
  return this.http.get(filename, {responseType: 'text'})
    .subscribe(
        data => this.log(filename, data),
        error => this.logError(filename, error)
    );
```

by this:

```
  return this.http.get(filename, {responseType: 'text'})
    .pipe(
      tap( // Log the result or error
        data => this.log(filename, data),
        error => this.logError(filename, error)
      )
    );
```

The error went away, but I can't resolve my promise inside the tap so it's not really useful for me. Any idea what's going wrong?

**Comment by trotyl** [comment]
The reported error is [`console.error`](https://github.com/angular/angular/blob/7d6f4885b25f36ab5262d868b0a4d762dea27a62/packages/core/src/errors.ts#L30) API not exist, you should have it polyfilled if running in browsers lacking this feature.

**Comment by glemiere** [comment]
@trotyl unfortunately not, the observable throws an error on older browser, not on a modern browser. The problem here is that the observable fails in itself

**Comment by glemiere** [comment]
Let me simplify, this works:
`this.http.get(endpoint, this.requestHeaders)`

This fails showing the error above:
`this.http.get(endpoint, this.requestHeaders).toPromise()`

**Comment by trotyl** [comment]
@glemiere  Please just read the error log, it has nothing to do with Observable. 

HTTP Observables are cold Observables, you have to subscribe it or nothing happens.

**Comment by glemiere** [comment]
I figured it out. Weirdly enough, in order for this to work with chrome 41 I had to rewrite my call the following way:

    import {
    	map,
    	catchError
    } from 'rxjs/operators'
    import {throwError} from 'rxjs'

Then

     public fetch(): Promise<object> {
        const endpoint = `http://myendpoint`
        const headers = {}

        let result = this.http.get(endpoint, headers)
            .pipe(
                    map((data: any) => {
                        return data;
                    }),
                    catchError((err: any) => {
                        return throwError(err);
                    })
                )

            return new Promise((resolve, reject) => {
                result.subscribe((data) => {
                    resolve(data)
                })
            });
    }

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/30203, has been fixed now.

It's a Zone.js issue which doesn't patch XHR properly.
