### ISSUE TITLE
IVY: ERROR in Invalid dot property access: undefined dot pathname

### ISSUE THREAD

**Issue by spock123** [angular/angular#30226]
### Description

After converting existing project to IVY, I get an error message which doesn't say anything about or where the "bug" is supposed to be.

```
ng serve --verbose
ERROR in Invalid dot property access: undefined dot pathname
ℹ ｢wdm｣: Failed to compile.
```

## 🔬 Minimal Reproduction
I took my existing project, enabled IVY in angularCompilerOptions

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.0-rc.2
Node: 10.15.3
OS: darwin x64
Angular: 8.0.0-rc.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.2
@angular-devkit/build-angular     0.800.0-rc.2
@angular-devkit/build-optimizer   0.800.0-rc.2
@angular-devkit/build-webpack     0.800.0-rc.2
@angular-devkit/core              8.0.0-rc.2
@angular-devkit/schematics        8.0.0-rc.2
@angular/cdk                      8.0.0-rc.0
@angular/material                 8.0.0-rc.0
@angular/pwa                      0.13.6
@angular/router                   8.0.0-rc.2
@ngtools/webpack                  8.0.0-rc.2
@schematics/angular               8.0.0-rc.2
@schematics/update                0.800.0-rc.2
rxjs                              6.5.1
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

** package.json **

<pre><code>
{
  "dependencies": {
    "@angular/animations": "^8.0.0-rc.2",
    "@angular/cdk": "^8.0.0-rc.0",
    "@angular/common": "^8.0.0-rc.2",
    "@angular/compiler": "^8.0.0-rc.2",
    "@angular/core": "^8.0.0-rc.2",
    "@angular/forms": "^8.0.0-rc.2",
    "@angular/material": "^8.0.0-rc.0",
    "@angular/platform-browser": "^8.0.0-rc.2",
    "@angular/platform-browser-dynamic": "^8.0.0-rc.2",
    "@angular/pwa": "^0.13.6",
    "@angular/router": "^8.0.0-rc.2",
    "@angular/service-worker": "^8.0.0-rc.2",
    "@ngrx/effects": "8.0.0-beta.1",
    "@ngrx/entity": "8.0.0-beta.1",
    "@ngrx/router-store": "8.0.0-beta.1",
    "@ngrx/store": "8.0.0-beta.1",
    "@ngrx/store-devtools": "8.0.0-beta.1",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "bootstrap-4-grid": "^2.4.1",
    "core-js": "^2.6.5",
    "file-saver": "^2.0.1",
    "hammerjs": "^2.0.8",
    "json-server": "^0.14.2",
    "ngrx-store-localstorage": "^7.0.0",
    "ngx-animations": "^2.2.4",
    "ngx-device-detector": "^1.3.5",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.800.0-rc.2",
    "@angular/cli": "^8.0.0-rc.2",
    "@angular/compiler-cli": "^8.0.0-rc.2",
    "@angular/language-service": "^8.0.0-rc.2",
    "@types/file-saver": "^2.0.0",
    "@types/jasmine": "~3.3.9",
    "@types/jasminewd2": "~2.0.6",
    "@types/node": "~11.11.0",
    "codelyzer": "~4.5.0",
    "fs-extra": "^7.0.1",
    "jasmine-core": "~3.3.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.5",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "lite-server": "^2.4.0",
    "protractor": "~5.4.2",
    "tslint": "~5.13.1",
    "typescript": "^3.4.5",
    "webpack-bundle-analyzer": "^3.1.0"
  }
}
</code></pre>

**Comment by JoostK** [comment]
Thanks for reporting! It looks like this happens because syntax of the form `object.property` is being statically analyzed with `object` being resolved to `undefined`. The interpreter doesn't currently handle that nicely and we should look into improving the situation.

Would you be able to share a reproduction? I could understand there's no way for you to find the culprit, but if it were possible to share some code that shows the problem would help in establishing the next steps.

**Comment by spock123** [comment]
@JoostK  I can't unfortunately.. it's an internal company app.

But I'll try to narrow it down, the app is highly modularized so I should be able to remove module by module until I fund the culprit module. I'll see what I can do.. cheers

**Comment by spock123** [comment]
@JoostK hi again - short status: after having removed all the app UX code bit by bit I've narrowed it down to something to do with a custom router serializer for @ngrx/store. More to come..  /s

**Comment by spock123** [comment]
@JoostK I've found the error.

My app is internationalized using ngx-translate. I create a top path language element by manipulating the APP_BASE token when app module is initialized:

```
 { provide: APP_BASE_HREF,
      useValue: '/' + (window.location.pathname.split('/')[1] || '')
    }

```

At runtime this is ok but at compile time IVY complains that window.location.pathname  is undefined.

**Comment by JoostK** [comment]
@spock123 thanks for investigating and sharing the code snippet!

By the looks of it, this problem is caused because of statically analyzing `NgModule` metadata to list all lazy routes in the program, a process that the CLI runs to support the `loadChildren` pattern for lazy modules.

When compiling Ivy code, the compiler itself does not attempt to statically analyze `NgModule.providers` as there is no need for it to interpret that code, it it just compiled verbatim into the correct location. The lazy listing of routes *is* however still implemented in the Ivy compiler so we should probably fix it to deal with this scenario.

@alan-agius4 is it possible to disable the listing of lazy routes? I found some code paths in the CLI that disable it based on a compiler option, but that option doesn't seem to be exposed to users.

**Comment by alan-agius4** [comment]
@JoostK, at the moment lazy route discovery can only be disabled when using the `@ngtool/webpack` directly. 

The main reason for that a user shouldn't need to disable/enable lazy routes discovery as this should be handled internally.

**Comment by JoostK** [comment]
@alan-agius4 Oh yes absolutely, it is not at all a problem that it can't be disabled, I was just wondering.

@spock123 I forgot to mention yesterday that using `useFactory` will probably workaround the issue:

```typescript
export function parseLocaleFromUrl(): string {
  return '/' + (window.location.pathname.split('/')[1] || '');
}

 { provide: APP_BASE_HREF, useFactory: parseLocaleFromUrl }
```

**Comment by spock123** [comment]
@JoostK thanks, yeah I have since refactored the code with useFactory. Thanks again.

**Comment by DavidRnR** [comment]
Hi everyone!

I've already upgraded to Angular 8 and set Ivy = true. I am getting the same error.

**

> ERROR in Invalid dot property access: undefined dot origin

**

Should be great how to find the error in the project with a reference in the console. No idea which could be the file/line that has got the error.

Thank you.

**Comment by nicolae536** [comment]
> Hi I found the same issue I think one of the problems can be `AgmCoreModule` I tryed to narrow it down but I couldn't I commented all imports in my app module leaving just the AppComponent and the basic angular modules and I still get the error :(

**Comment by netwiser** [comment]
I have a project using Firebase Auth, in my component:
import * as firebase from 'firebase/app';
....
googleSignIn() {
    const provider = new firebase.auth.GoogleAuthProvider();
    return this.oAuthLogin(provider);
 }

Then with IVY enabled it prompts ERROR in Invalid dot property access: undefined dot GoogleAuthProvider
