### ISSUE TITLE
support live editing in the browser

### ISSUE THREAD

**Issue by amitport** [angular/angular#30222]
# 🚀 feature request

### Relevant Package
@angular/core / docs?

### Description
Angular should support ability to quickly edit, compile and load components in the browser without complex server-side compilation.
This is possible with other languages / frameworks, including angular.js!, svelte, scala.js, and others. (see https://svelte.dev/examples, https://scalafiddle.io/)

### Describe the solution you'd like
If this is currently possible (with ivy?), please add documentation (or even an example).
Otherwise, please publish a roadmap for support or explain what is the critical issue.

### Describe alternatives you've considered
repl.it codesandbox stackblitz do manage to recreate such an experience by including code that almost replicates node's/npm's capabilities (+ some server side support).

Seems to me like an unreasonably complex, expensive (in term of dev time and maintenance),  and low-performance implementation. I want to create a website with dynamically created and edited components (i.e., IDE for specific domains). I did so in the past using iced-coffeescript+angular.js (browser-side compilation), I wish I could also write such code with Angular.

**Comment by alxhub** [comment]
Hi @amitport,

This is actually currently possible with Angular even today (pre-Ivy), using `@angular/platform-browser-dynamic` and JIT compilation. This is how, as you've mentioned, Stackblitz and others work. Stackblitz's emulation of NPM is necessary to support loading the libraries people want in a way they're familiar with, but is not a necessity if you don't want to support arbitrary published libraries.

For a custom solution without Stackblitz's goals of flexibility, transparency and sandboxing, you should be able to drop some of the complexity around emulation of NPM and around bundling, and more directly interface with the JIT compiler. Something like the Svelte example site would be very doable in this mode.

**Comment by amitport** [comment]
@alxhub, thank you for your response. I get that it is somewhat doable, but such implementation include undocumented (or sparsly-documented) moving APIs (I think, no real guides), hence the request for documentation/example. How do I take *pre-compiled* newly created angular+ts code and add it to a running app? (+Does this running app needs to be compiled/loaded in a special way?)
Any help is greatly appreciated.
