### ISSUE TITLE
docs: router - improve docs on the imports order of multi routing modules

### ISSUE THREAD

**Issue by yingding** [angular/angular#30223]
# 📚 Docs or angular.io bug report

### Description

For the section https://github.com/angular/angular/blob/master/aio/content/guide/router.md#import-crisis-center-module-into-the-appmodule-routes
in the router.md doc.

The current text is:
> Import crisis center module into the AppModule routes
> As with the HeroesModule, you must add the CrisisCenterModule to the imports array of the AppModule before the AppRoutingModule:

The **placement** order in the **imports array of the AppModule**  shall be highlighted with a Notice or Warning, since the natural way of doing the hero tutorial is adding the crisis-center module with the crisis-center routing using the angular-cli after the app module. The angular-cli creates the import of crisis-center module after the AppRoutingModule. This will be an issue for the code.

When a **Wildcard route** is defined in the **AppRoutingModule**, the wildcard route will be matched before the child route in the crisis-center routing can be matched. This happens very often wenn using the angular-cli to added submodule with routing feature.

The natrual way of adding Wildcard route is in the AppRoutingModule, and then always place the AppRoutingModule after all submodule in the import array of the AppModule. The debugging of such error relating to the routes match due to the import placement order is very difficult.  Thus, i suggest to improve the original doc text to hightlight this issue to prevent error in coding and improve the readers understanding of the impact of the placement order in the imports array of the angular modules.  

### What's the affected URL?**
https://angular.io/guide/router#import-crisis-center-module-into-the-appmodule-routes

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by rockument69** [comment]
@kapunahelewong : Can I get a status on this, or whether someone should take it on? 

The fix seems to be a note or warning. Something about this being wrong: "the natural way of doing the hero tutorial is adding the crisis-center module with the crisis-center routing using the angular-cli after the app module." The problem is that it adds the crisis-center module AFTER rather than BEFORE the `AppRoutingModule`. Is this a bug in the Hero Tutorial as well?
