### ISSUE TITLE
How to build Cordova Web view application using Kendo Angular 7 components?

### ISSUE THREAD

**Issue by fiportdev** [angular/angular#30228]
We are building an Angular 7 mobile app that will be integrated with a third party hybrid app (using standard HTML/JS technology) over which we have no control. They will call our function/app by launching a Webview (and URL) to pass control to us. Our app/functions then almost like a but in the Webview.

Generally, this is not a problem but we are trying to take advantage of the native controls that Cordova provides in a Hybrid app or access to via .

Do you have a sample app or an example or a build process on how to do this?

 It seems that it works with vanilla HTML app but not with Angular 7 app.

Thanks.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
