### ISSUE TITLE
template strategy & usage strategy need more definition

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#30224]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?
no

### Description
Upon using `ng update` to move to 8.0.0-rc.2 (or later), I get the following prompt:

```
------ Static Query migration ------
            In preparation for Ivy, developers can now explicitly specify the
            timing of their queries. Read more about this here:
            https://github.com/angular/angular/pull/28810
            
            There are two available migration strategies that can be selected:
              • Template strategy  -  migration tool (short-term gains, rare corrections)
              • Usage strategy  -  best practices (long-term gains, manual corrections)
            For an easy migration, the template strategy is recommended. The usage
            strategy can be used for best practices and a code base that will be more
            flexible to changes going forward.
? What migration strategy do you want to use?
```
This prompt doesn't include enough information for me to decide, and the linked PR doesn't talk about these strategies. It's unclear what the differences are or what changes will be made.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0-rc.2
Node: 12.1.0
OS: linux x64
Angular: 8.0.0-rc.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.2
@angular-devkit/build-angular     0.800.0-rc.2
@angular-devkit/build-optimizer   0.800.0-rc.2
@angular-devkit/build-webpack     0.800.0-rc.2
@angular-devkit/core              8.0.0-rc.2
@angular-devkit/schematics        8.0.0-rc.2
@angular/cdk                      8.0.0-rc.0
@angular/material                 8.0.0-rc.0
@ngtools/webpack                  8.0.0-rc.2
@schematics/angular               8.0.0-rc.2
@schematics/update                0.800.0-rc.2
rxjs                              6.5.1
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by StephenFluin** [comment]
Additionally, in an ideal world this would only prompt the user if we detect that they are using these queries.

**Comment by kara** [comment]
Agree, we need to expand the messaging.

Note that we should only be prompting if users have ViewChild/ContentChild queries.

**Comment by devversion** [comment]
I also agree that the prompt misses a lot of context that is necessary to make a correct decision. I don't think we can actually provide enough context within the terminal anyway, and it's probably best to have a dedicated document that provides context.

Also agreed on not prompting if there aren't any `ViewChild` or `ContentChild` queries that need to be migrated. I'll take care of this as soon as possible.

**Comment by Splaktar** [comment]
Is the plan to document this in the release notes or the Deprecation Guide? The documentation should have code examples for the two strategies.

**Comment by DeborahK** [comment]
For ngupdate, in addition to only prompting if no queries are used, the text should minimally be modified to:

- Add an adjective to 'query' such as 'ViewChild/ContentChild queries' because 'query' it too general.
- Change the link to the dedicated document outlining the two choices and their impact.

**Comment by devversion** [comment]
> The documentation should have code examples for the two strategies.

:+1: Examples are definitely a good idea.

> Should this be marked as a release blocker?

I'd say so. We want to make the upgrade as easy as possible.. and a confusing prompt with not much context doesn't help with that :smile:

**Comment by kara** [comment]
Closed by https://github.com/angular/angular/pull/30644
