### ISSUE TITLE
in api docs, an example implements ErrorHandler whitch is a class, not interface

### ISSUE THREAD

**Issue by xxyyzz2050** [angular/angular#30230]
in ErrorHandler API docs, it marked as a class, not interface, but in the example it implements it not extended it.

![feeaa5bd-c329-4e21-b6b8-a019b6fee430](https://user-images.githubusercontent.com/35532104/57061558-fcf85100-6cc5-11e9-9560-1bb18f394cd2.png)
![aef01908-5a0c-4722-aa7c-616289a420ae](https://user-images.githubusercontent.com/35532104/57061560-fcf85100-6cc5-11e9-8d13-a3c5dc83741d.png)

**Comment by jotatoledo** [comment]
See https://github.com/angular/angular/issues/21697

**Comment by xxyyzz2050** [comment]
@jotatoledo  the documentation is belongs to Angular, not typescript, so there is a big difference here between the class and the interface

if it is an interface, you must implement all its methods, but if it is a class, you have the choice to override some methods, and the other methods are already implemented.

it's not about how you use it in Typescript, it's bout how you work with it inside your code.
it is wrong in Angular even it is accepted in Typescript.

**Comment by trotyl** [comment]
Using class is the correct behavior as class can be DI token, so you can inject it anywhere. Also the class here could provide default implementation.

Class doesn’t meant a base, `implements SomeClass` is a common practice to express compatibility.

See https://github.com/angular/angular/issues/19632 for more information.

**Comment by xxyyzz2050** [comment]
so, there is a reaseon :) 
thaaaaaaaaaaaaanks @trotyl

**Comment by trotyl** [comment]
FYI, `extends ErrorHandler` is also valid usage if you want to reuse some functionality (by delegating to `super`), but make sure to explicitly define the constructor as `ErrorHandler` is not an injectable.

**Comment by kara** [comment]
Looks like this is resolved, so closing
