### ISSUE TITLE
Encoding of search criteria on angular.io causing no results to be shown

### ISSUE THREAD

**Issue by Brocco** [angular/angular#30242]
# 📚 Docs or angular.io bug report

### Description

When using the chrome URL bar search functionality to search angular.io with multiple words the search terms are encoded to replace the space with a `+` character. This is causing the search results to find no results.

## 🔬 Minimal Reproduction

To trace through the issue from the beginning... In the browser URL bar type "angular.io reactive forms" (note this needs to be typed and not pasted to trigger the search functionality.
This will navigate to this url: `https://angular.io/?search=reactive+forms` notice the encoding has replaced the space with a `+`.

With the search term 

### What's the affected URL?**
https://angular.io/?search=reactive+forms

### Expected vs Actual Behavior**
Expected: search results should show for search criteria containing a space.
Actual: due to the `+` there are no search results found

## 📷Screenshot
Entering the search criteria:
![image](https://user-images.githubusercontent.com/1565117/57088075-bce1a000-6cbe-11e9-8e18-b4886e279e31.png)

No results showing:
![image](https://user-images.githubusercontent.com/1565117/57089154-092ddf80-6cc1-11e9-98df-830ee5982b4b.png)

**Comment by gkalpak** [comment]
I assume you have set up angular.io as a custom search engine/provider in Chrome.
Good catch! PRs welcome :wink:

**Comment by Brocco** [comment]
Good call @gkalpak PR submitted 😉
