### ISSUE TITLE
Implement tests for CSP mode for JS and Dart

### ISSUE THREAD

**Issue by tbosch** [angular/angular#3025]
E.g. we do `eval` in `browser_adapter.dart` for performance reasons, and need to switch it to a slower version using `JsObject` instead.

**Comment by mhevery** [comment]
@IgorMinar may have an opinion as he has done this before.

**Comment by IgorMinar** [comment]
we'll need a special mode for the server that sends the right http headers to turn on the CSP mode.

this is what we did in v1: https://github.com/angular/angular.js/blob/master/lib/grunt/utils.js#L271-L283

**Comment by splincode** [comment]
@mhevery @IgorMinar  Is the issue relevant?

**Comment by mhevery** [comment]
no longer relevant
