### ISSUE TITLE
Contributing: Bazel build never finishing/ way too slow

### ISSUE THREAD

**Issue by s-gbz** [angular/angular#30251]
# 🐞 bug report

### Affected Package
Build tool related.

### Is this a regression?
I don't know.

### Description
I'm writing a test in order to fix #29099. Unfortunately building and testing Angular doesn't seem too work, because the system never stops "Compiling Typescript".

I tried `yarn bazel build //packages/compiler --profile filename_name.profile` and it too is going on for more than 32 minutes now. My machine is running Windows 10. Advice how to proceed is much appreciated.

## 🔬 Minimal Reproduction
`yarn bazel build / test/ ...`

## 🔥 Exception or Error

<pre><code>
C:\Users\grilborzer\Code\angular>yarn bazel build //packages/compiler --profile filename_name.profile
yarn run v1.14.0
$ bazel build //packages/compiler --profile filename_name.profile
INFO: Writing profile data to 'C:/users/grilborzer/code/angular/filename_name.profile'
INFO: Build option --legacy_external_runfiles has changed, discarding analysis cache.
INFO: Analysed target //packages/compiler:compiler (0 packages loaded, 4025 targets configured).
INFO: Found 1 target...
[8 / 9] Compiling TypeScript (devmode) //packages/compiler:compiler; 1957s local
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
OS: Windows 10
</code></pre>

**Anything else relevant?**

**Comment by meteorcloudy** [comment]
Does this happen consistently for you? I'm able to build `//packages/compiler` with 16s on my machine.
Can you check what process was running when the action hangs?

**Comment by s-gbz** [comment]
Hey, thanks a lot for looking into this!
It sure isn't related to performance, since the machine is pretty powerful.

I executed `yarn bazel build //packages/compiler` and it's still going on and on.

<pre>
yarn run v1.14.0
$ bazel build //packages/compiler
INFO: Analysed target //packages/compiler:compiler (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[1 / 2] Compiling TypeScript (devmode) //packages/compiler:compiler; 237s local
</pre>

What exactly do you mean by process? I looked into Windows Task Manage and found this `bazel-0.24.0-windows-x86_64.exe`

**Comment by meteorcloudy** [comment]
Can you share some information about the build?

- What's the commit for the angular repo?
- What's the bazel version? `yarn bazel version`

**Comment by s-gbz** [comment]
Thanks for the quick response!
I rebased my branch onto the master branch to see if there would be a difference. Unfortunately there isn't.

The hereby newest **commit** is:
`9abf114fbb826526a08ec62414799e5980ab56e4` - `"feat(bazel): use rbe_autoconfig() and new container. (#29336)"`

<pre>
The **bazel** version is `1.14.0`
Build label: 0.24.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Mar 26 16:13:02 2019 (1553616782)
Build timestamp: 1553616782
Build timestamp as int: 1553616782
Done in 3.10s.
</pre>

Not sure if it's relevant, but executing `build-packages-dist.sh` fails as well, because `command "." can't be found`

**Comment by kyliau** [comment]
@filipesilva has some experience with building angular repo on Windows. 
Filipe, what's the typical build time (I remember you mention it takes a long time) ?

**Comment by s-gbz** [comment]
Hello @brandonroberts, have you had any experience with this? @web-dave hinted me that you might be able to help out 🌝

**Comment by filipesilva** [comment]
Hmmm I haven't seen this windows problem myself. We have that particular target running right now in our Windows CI even. 

The only thing that comes to mind is some symlink related problem. Not having enough memory could do something similar. Maybe try outside of the `C:\Users\` folder as it might have something special going on there.

If you want to try using a Windows docker image that we know works, you can build the one in https://github.com/angular/angular/tree/master/.codefresh. We test the windows steps listed in `codefresh.yml`.

**Comment by s-gbz** [comment]
Using the container didn't work out, but continuously rebasing the branch onto master finally led to new errors:

![bazel-new-error](https://user-images.githubusercontent.com/23424538/61952747-fb80b100-afb4-11e9-9bf7-cbff168a6621.PNG)

Hoping this issue will be resolved by future Bazel updates I switched to **Windows Subsystem for Linux as a workaround** . After tidious dependecy installations I can finally run the Angular build and test suits. 

If anyone happens to depend on it as well make sure to install Nodejs 10.15.0 and Yarn 1.16.0 in the first place.
