### ISSUE TITLE
Use component templating without a module

### ISSUE THREAD

**Issue by alshdavid** [angular/angular#30258]
I have been looking for the capability to use Angular strictly as a component/template renderer. I don't need it to compile into customElements, I just need to mount a component instance on a DOM element and pass in dependencies using simple property injection.

**Basic syntax example**

```typescript
import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  declarations: [ pipes, directives, components ],
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
class HomeComponent {
    constructor(
        public dependencyA: any,
        private dependencyB: any
     ) {}
}

const target = document.querySelector('#component-root')

const component = new HomeComponent()
const instance = component.mount(target, [dependencyA, dependencyB]) 
  .subscribe(mountEvent => console.log(mountEvent))

instance.unmount()
  .subscribe(mountEvent  => mountEvent )
```

Perhaps if the injector is omitted and an array supplied, elect to use property injection, where passing an injector will enable usage of the dependency injection framework.
```typescript
component.mount(target, [dependencyA, dependencyB]) 
component.mount(target, { injector }) 
```

**Comment by JoostK** [comment]
I think @robwormald's [presentation during ng-conf last Wednesday](https://www.youtube.com/watch?v=JX5GGu_7JKc) may be interesting to you, as it touches some of the ideas you mention in the description.

**Comment by alshdavid** [comment]
I've updated my original post to be more concise. 

@robwormald great presentation! Is there any more information on how you're thinking of going about module-less components?

One question, are moduleless components going to be exclusive to customElements/ngElements or will we be able to mount component instances onto dom nodes?
