### ISSUE TITLE
Bazel genfiles not included in flat module metadata bundle

### ISSUE THREAD

**Issue by devversion** [angular/angular#30259]
# 🐞 bug report

### Affected Package

`@angular/bazel` and `@angular/compiler-cli`

### Is this a regression?

No

### Description

Currently when a `ng_module` bazel target references a Bazel generated file (`genfile`), the flat module metadata bundle that is generated by NGC does not contain the metadata of the genfile.

This can cause compilation issues when the genfile contains Angular modules
but now misses metadata. This makes the built component/module not usable in other projects.

## 🔬 Minimal Reproduction

https://github.com/devversion/ng-bazel-genfile-metadata-bundle

## 🔥 Root cause analysis

_Analysis is based on the reproduction above_

The issue appears because the metadata bundler tries to resolve
the genfile relatively to real `index.ts` source file. Under Bazel this ends
up resolving the genfile path within the `execroot/src/index.ts`, while the actual
genfile is part of the `execroot/bazel-out/../bin/src/` directory. The issue can be solved
by also respecting the genfile/bin directory when resolving the metadata of original source-files. 

https://github.com/angular/angular/blob/30d1f292c930d0ba8c198757b3333d4b594692d8/packages/compiler-cli/src/metadata/bundler.ts#L135-L145

(_see the `resolveModule` function call_)

## 🌍  Your Environment

Latest Angular version

**Comment by jelbourn** [comment]
@devversion is this issue still relevant?

**Comment by devversion** [comment]
@jelbourn This would still be an issue for View Engine compilations IIRC, but given that we use Ivy for our example package, this no longer surfaces. I'm closing this as I think we will not ever get to fix this and View Engine is removed in the future anyway.
