### ISSUE TITLE
Angular 8 + ivy + ng build library usage error

### ISSUE THREAD

**Issue by jmbarbier** [angular/angular#30265]
# 🐞 bug report

### Affected Package

Maybe a cli or ng-packagr or ivy issue.

### Is this a regression?

kinda : works with `enableIvy: false`, fails with `enableIvy: true`

### Description

Using angular/*@8.0.0-rc.2, and `ng new --enable-ivy` fresh projects :
in a `testlib` new project, building a `mylib` library with `ng g library` and `ng build`, only adding a ngIf & CommonModule to default lib files produces a bundle that cannot be consumed from a `testclient` : 

```
core.js:7182 ERROR Error: Template error: Can't bind to 'ngIf' since it isn't a known property of 'p'.
```

## 🔬 Minimal Reproduction

- use ng cli 8.0.0-rc.2
- create a lib using ng cli (ng8 rc2, enableIvy=true)
    - `ng new testlib --enable-ivy`  (no router, use css)
    - `ng g library mylib`
    - add CommonModule to mylib.module imports
    - add an *ngIf to mylib.component
    - build the lib using `ng build`

- use it in another project (ng8 rc2, enableIvy=true) 
  - `ng new testclient --enable-ivy` (no router, use css)
  - add this library (copy to node_modules / use yalc / publish to npm..)
  - use it : add MylibModule to app.module
  - add `lib-mylib` component to app.component.html
  - `ng serve` ... boom

this fails with enableIvy=true, works with enableIvy=false in testclient

I've setup a little repo with minimal reproduction

https://github.com/jmbarbier/ng8-ivy-library-issue

the compiled repro lib is available at 
https://github.com/jmbarbier/ng8-ivy-library-issue/raw/master/mylib.tar.gz

## 🔥 Exception or Error
<pre><code>
core.js:7182 ERROR Error: Template error: Can't bind to 'ngIf' since it isn't a known property of 'p'.
    at createUnknownPropertyError (core.js:12560)
    at elementPropertyInternal (core.js:12426)
    at Module.ɵɵproperty (core.js:16519)
    at MylibComponent_Template (mylib.js:24)
    at executeTemplate (core.js:11998)
    at checkView (core.js:13349)
    at componentRefresh (core.js:13113)
    at refreshChildComponents (core.js:11701)
    at refreshDescendantViews (core.js:11607)
    at checkView (core.js:13350)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0-rc.2
Node: 10.15.3
OS: linux x64
Angular: 8.0.0-rc.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.0-rc.2
@angular-devkit/build-angular      0.800.0-rc.2
@angular-devkit/build-ng-packagr   0.800.0-rc.2
@angular-devkit/build-optimizer    0.800.0-rc.2
@angular-devkit/build-webpack      0.800.0-rc.2
@angular-devkit/core               8.0.0-rc.2
@angular-devkit/schematics         8.0.0-rc.2
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.0-rc.2
@schematics/angular                8.0.0-rc.2
@schematics/update                 0.800.0-rc.2
ng-packagr                         5.1.0
rxjs                               6.4.0
typescript                         3.4.5
webpack                            4.30.0
</code></pre>

**Comment by jmbarbier** [comment]
Tested with rc3, same problem. Updated test repo https://github.com/jmbarbier/ng8-ivy-library-issue and compiled lib https://github.com/jmbarbier/ng8-ivy-library-issue/raw/master/mylib.tar.gz

Linked with https://github.com/ng-packagr/ng-packagr/issues/1278 

Some other info : using ̀ng serve --prod` or `ng build --prod` does not raise any error

this component 
```typescript
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'lib-mylib',
  template: `
    <p *ngIf="works">
      mylib works!
    </p>
    <p *ngIf="!works">
      i should not be displayed
    </p>
    <p>mylib present</p>
  `,
  styles: []
})
export class MylibComponent implements OnInit {
  works = true;
  constructor() { }

  ngOnInit() {
  }

}
```

is rendered as 
```html
<lib-mylib _ngcontent-akr-c1="">
    <!---->
    <!---->
    <p>mylib present</p>
</lib-mylib>
```

**Comment by jmbarbier** [comment]
Closing this issue as i was able to make it work (with rc.5). 

1. **don't use enableIvy=true on library side** - no error, the component is not displayed
2. always clean everything (node_modules, package-lock.json, .yalc ...) between changes

**Comment by fr0** [comment]
I am also having this problem, using an `ng-packagr` library. I did not set enableIvy=true on the library side. Angular 8.1.0-rc.0.

Cleaning `yarn.lock` and `node_moduels` did not help. Using `--prod` does work, as mentioned in this issue.

**Comment by fjoalland** [comment]
@fr0 Did you resolve this issue since you commented?
