### ISSUE TITLE
Ivy + Angular Elements = "NullInjectorError: No provider for CompilerFactory"

### ISSUE THREAD

**Issue by philly-vanilly** [angular/angular#30262]
# 🐞 bug report
### Description
Building Angular with ivy enabled (in angularCompilerOptions) results in the above runtime error, but only in --prod. Without --optimization=false the CompilerFactory is obfuscated/minified in the error message.

##  Relevant code
Basically it's the same setup as here: https://angularfirebase.com/lessons/angular-elements-advanced-techniques/

app.module:
<pre><code>
import {BrowserModule} from '@angular/platform-browser';
import {Injector, NgModule} from '@angular/core';

import {AppComponent} from './app.component';
import {createCustomElement} from '@angular/elements';

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule],
  entryComponents: [AppComponent]
})
export class AppModule {

  constructor(private injector: Injector) {
    const el = createCustomElement(AppComponent, {injector});
    customElements.define('my-selector', el);
  }

  ngDoBootstrap() {
  }

}
</code></pre>

main.ts (btw, using platformBrowser results in the same error)
<pre><code>
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic()
  .bootstrapModule(AppModule)
  .catch(err => console.error(err));
</code></pre>

build-script:

<code><pre>

const fs = require('fs-extra');
const concat = require('concat');

(async function build() {
  const files = [
    './dist/apps/myelement/runtime.js',
    './dist/apps/myelement/polyfills.js',
    './dist/apps/myelement/main.js',
    './dist/apps/myelement/scripts.js'
  ];

  await fs.ensureDir('dialog/myelement');
  await concat(files, 'dialog/myelement/myelement.js');
  await fs.copyFile(
    './dist/apps/myelement/styles.css'
  );
})();

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect         0.13.1
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.1
@angular-devkit/schematics        7.3.1
@angular/cli                      7.3.1
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.3.3
typescript                        3.2.2
webpack                           4.29.0
</code></pre>

**Comment by robwormald** [comment]
Ivy isn't supported with Elements yet, so this is expected behavior. Working on this!
