### ISSUE TITLE
Tab key after listen first focus not working

### ISSUE THREAD

**Issue by bhador1936** [angular/angular#30266]
when i set focus event then called my method and i access to event. but after called, Tab key not working and not go to next index !!! and other event like click, mouseover,... are true

<pre><code>
import { Component, EventEmitter, Input, Output, ElementRef } from '@angular/core';
import { Row } from '../../../lib/data-set/row';
import { Grid } from '../../../lib/grid';

@Component({
    selector: 'ng2-st-tbody-custom',
    template: `
    <button *ngFor="let action of grid.getSetting('actions.custom')"
         class="ng2-smart-action" 
         [innerHTML]="action.title"  
         (focus)="onActionfocus($event)"
         (click)="onCustom(action, $event)" 
    ></button>`,
    styles: [`
        .ng2-smart-action{ 
            display: inline-grid;
            margin: 0px 5px;
        }`
    ]
}) 
export class TbodyCustomComponent {

    @Input() grid: Grid;
    @Input() row: Row;
    @Input() source: any;
    @Output() custom = new EventEmitter<any>();

    constructor(private el: ElementRef) { }

    onCustom(action: any, event: any) {
        event.preventDefault();
        event.stopPropagation();

        this.custom.emit({
            action: action.name,
            data: this.row.getData(),
            source: this.source
        });
    }

    onActionfocus(e: Event){
        console.log(document.activeElement, e);
    }

}
</code></pre>

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
