### ISSUE TITLE
Angular CLI Version Should Be Specified For Previous Versions of Angular in CLI Quickstart

### ISSUE THREAD

**Issue by aakashgarg19** [angular/angular#30261]
# 📚 Docs or angular.io bug report

### Description

 If I want to create an project in previous version of Angular, the version archive document of that version should also mention cli version to install. Instead of asking to install the latest version of cli. As latest version will only output latest angular version project.

### What's the affected URL?**
For Angular 2 :- https://v2.angular.io/docs/ts/latest/cli-quickstart.html

## 📷Screenshot

![image](https://user-images.githubusercontent.com/13452345/57176375-de848800-6e74-11e9-9d32-9ec26df95ea4.png)

**Comment by FrederikSchlemmer** [comment]
@brandonroberts are you working on this issue? Otherwise I could take over this issue.

Where is the documentation of 'v2.angular.io' located?

**Comment by gkalpak** [comment]
I don't think we are updating the v2.angular.io docs any more. And since v7 (iirc), Angular core and cli major versions will be aligned (so you need cli version X to use Angular version X). Maybe we should add a note about that in the relevant guides.

**Comment by FrederikSchlemmer** [comment]
@gkalpak Maybe this section would be correct: [Angular Versioning and Releases](https://angular.io/guide/releases)?

What kind of note do you think is necessary? Just a quick note, that Angular core and cli major versions will be aligned since v7?

**Comment by gkalpak** [comment]
> What kind of note do you think is necessary? Just a quick note, that Angular core and cli major versions will be aligned since v7?

Yeah,something like that. Basically, that you can only use Angular vX with cli vX (and vice versa).
Then we could link to that note from the "Getting Started" guide, if necessary.

**Comment by FrederikSchlemmer** [comment]
@gkalpak thanks for the feedback! I have started a Pull Request and would be pleased about feedback!

**Comment by aakashgarg19** [comment]
Hi @FrederikSchlemmer , thanks for working on this. Hope to see it soon in documentation.

**Comment by aakashgarg19** [comment]
Hi @FrederikSchlemmer, Will you be including cli versions for angular v2 where the version number is mismatched between core and cli.

**Comment by FrederikSchlemmer** [comment]
> Hi @FrederikSchlemmer, Will you be including cli versions for angular v2 where the version number is mismatched between core and cli?

I think that the chosen phrase already covers this case, because there is explicit mention of the versions starting with V7.

**Comment by ajitsinghkaler** [comment]
@gkalpak @kapunahelewong I think we can close this issue.

**Comment by gkalpak** [comment]
Fixed with #30976.
