### ISSUE TITLE
Setting markAsTouched() on a FormControl with CVA doesn't call the registered onTouched callback.

### ISSUE THREAD

**Issue by jessejohnsohn** [angular/angular#30275]
### Relevant Package
This feature request is for @angular/forms

### Description
I setup a custom form control with multiple fields using the ControlValueAccessor. Once it was wired up and working, I called "markAsTouched()" on the form control from the parent component, expecting the callback function onTouched that I registered via RegisterOnTouched to be called. It wasn't.

### Describe the solution you'd like
Call the registered touch function when the control is touched programmatically.  Or expose a method such as setTouchedState (https://github.com/angular/angular/issues/27315) and then access it the same way the validate(ctrl: AbstractControl) method is accessed, via the multi-provider NG_VALIDATORS.

### Describe alternatives you've considered
1. Create a separate "@Input" binding on the component through which to pass its touched status.
2. Inject the NgControl and listen directly to it for touched (although there also exists no easy way to listen to touched/dirty/pristine statuses).

Here is a reproduction of the issue:
https://stackblitz.com/edit/angular-cva-example-ng-conf

**Comment by Airblader** [comment]
This is the intended behavior. The onTouched callback is for the view to inform the model, not for the model to inform the view.

**Comment by jessejohnsohn** [comment]
@Airblader Thanks. I'll close the issue and keep an eye on https://github.com/angular/angular/issues/27315.
