### ISSUE TITLE
Using a guard without declaring it in providers causes unhelpful error "Cannot read property 'loadChildren' of undefined"

### ISSUE THREAD

**Issue by imaspeer** [angular/angular#30283]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 Not as far as I know.

### Description

Adding a guard to a route configuration (e.g. in `canActivate`) without also adding it to the providers array causes builds to fail with the error `Cannot read property 'loadChildren' of undefined`.
This error message is not very helpful and makes it hard to figure out what the problem is. It looks like it is an error of the build process itself rather than a message intended to be seen by the end user.
A better message should at the very least indicate the problem is a bad route configuration, and preferably also include which route it is and what the exact problem is.

The following code, either used as the root module or included in it (with `.forChild` instead of `.forRoot` in that case), is enough to reproduce the problem:
```typescript
import {NgModule} from '@angular/core';
import {RouterModule} from '@angular/router';

class BugGuard {}

@NgModule({
	imports: [
		RouterModule.forRoot([{path: '', canActivate: [BugGuard]}])
	]
}) export class BugModule {}
```
The error disappears entirely if `providers: [BugGuard]` is added to the NgModule or if `, canActivate: [BugGuard]` is removed from the route (though there are several other things wrong with this code due to making it as short and simple as possible, so it wouldn't work anyway).

## 🔬 Minimal Reproduction

https://github.com/a-speer/angular-bug-repro-router-loadchildren-undefined
Relevant code is in `src/app/app-routing.module.ts`.
The problem is reproduced by simply running `ng build`.

## 🔥 Exception or Error
<pre><code>ERROR in Cannot read property 'loadChildren' of undefined</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.8
Node: 11.8.0
OS: linux x64
Angular: 7.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Comment by abarghoud** [comment]
Hi @imaspeer, I tried to reproduce the issue, and actually it's not because of the class BugGuard not injected in providers section.

The problem is that the class BugGuard is not exported, exporting the class worked for me.

**Comment by atscott** [comment]
I copied this into stackblitz and it appears that the error being reported is actually helpful.
https://stackblitz.com/edit/angular-ivy-vhadng?file=src%2Fapp%2Fapp-routing.module.ts
`Error: Invalid configuration of route ''. One of the following must be provided: component, redirectTo, children or loadChildren`
When I add a component for that route, the error becomes
`NullInjectorError: No provider for BugGuard!`

Both of these seem to be helpful errors and working as expected
