### ISSUE TITLE
Docs: Example for minutes and seconds using date pipe doesn't match

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#30281]
# 📚 Docs or angular.io bug report

### Description

 The format example using minutes and seconds in the date pipe is incorrect

https://github.com/angular/angular/blob/master/packages/common/src/pipes/date_pipe.ts#L128

It should be 'mm:ss' instead of 'mmss'

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by kapunahelewong** [comment]
Closing as PR was merged. Thanks @brandonroberts and @underfin 🌺
