### ISSUE TITLE
Animation Complex Sequences docs code example is incorrect

### ISSUE THREAD

**Issue by Richardinho** [angular/angular#30287]
# 📚 Docs or angular.io bug report

### Description

The documentation on the complex sequences page has an error in it. https://angular.io/guide/complex-animation-sequences

In the first section *Animate multiple elements using query() and stagger() functions*, the text reads: "Use query() to look for any element entering or leaving the page."

The code example directly below this text follows:

```
animations: [
    trigger('pageAnimations', [
      transition(':enter', [
        query('.hero, form', [
          style({opacity: 0, transform: 'translateY(-100px)'}),
          stagger(-30, [
            animate('500ms cubic-bezier(0.35, 0, 0.25, 1)', style({ opacity: 1, transform: 'none' }))
          ])
        ])
      ])
    ]),
  ]
})

```
This code does not show the query function looking for elements entering and leaving the page: The query function is targeting elements *within* the element being animated which match the query '.hero, form'. i.e. are form elements or have the 'hero' class on them.

In the live example, there is also a `filterAnimation` trigger. This does show the query function looking for elements entering and leaving the page. This is probably what the example should show.

**Comment by jbogarthyde** [comment]
I think the example doesn't need to change, as the point of it is to show `query()` and `stagger()` working together - it doesn't matter that is doesn't show querying for "entering and leaving the page".
 My PR changes the description of what the query IS doing - choosing among elements that are entering the page. The example then shows how to use `stagger()` to delay transformations of the matching elements.

**Comment by jbogarthyde** [comment]
Resolved by changing the text description - the example is fine.
