### ISSUE TITLE
docs: ng update add scenario for updating to next 

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#30286]
# 📚 Docs or angular.io bug report

### Description
Currently, the reference page for `ng update` includes a scenario for updating to latest, which is great. It would also be nice if it showed an example for how to update to next (which is the next/Beta or RC). 

`ng update --next @angular/cli @angular/core`

 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/...
https://angular.io/cli/update

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by jbogarthyde** [comment]
PR https://github.com/angular/angular-cli/pull/14352
