### ISSUE TITLE
TestComponentBuilder: Support mocking out view/hostInjector of component

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#3029]
Given an arbitrary component, like "AppShellComponent":

```dart
const uiSpecificBindings = const [
  routerInjectables
];

@Component(
  selector: 'app-shell-component',
  viewInjector: const [
    uiSpecificBindings
  ]
)
class AppShellComponent {}
```

Sometimes you may want to slightly alter or mock out a dependency because you are testing a part of the component or how it's interaction works with a child. 

Proposal
---

```dart
testComponentBuilder.addViewInjectable(
    AppShellComponent,
    const Binding(Router, toClass: FakeRouter))
```

**Comment by bestander** [comment]
+1 after searching the repository I could not find an example of unit testing a `@Component` with services mocked.
Should it be done without TestComponentBuilder?

**Comment by matanlurey** [comment]
I have a PR almost ready for this, hope to get an initial submit this week.

**Comment by mhevery** [comment]
@matanlurey any update on your PR?

**Comment by naomiblack** [comment]
Just chatted with Matan. He has this working in Dart (which has internal folks unblocked) but could use some help turning that into TypeScript as a contribution to Angular.

**Comment by vsavkin** [comment]
This has been implemented. See TestComponentBuilder.overrideProviders and TestComponentBuilder.overrideViewProviders.
