### ISSUE TITLE
Pipe for converting string to template reference

### ISSUE THREAD

**Issue by RakeshMaddala** [angular/angular#30294]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/common

### Description
 If we need to use 
```[ngTemplateOutlet]="templateName"```
The "**templateName**" should be defined in component and should be of type **TemplateRef**.

Problem described with an example here - [https://stackoverflow.com/questions/56001849/how-to-convert-string-to-an-template-reference-instance]( https://stackoverflow.com/questions/56001849/how-to-convert-string-to-an-template-reference-instance)

### Describe the solution you'd like
 I should be able to convert the string type from a property to templateRef type using a pipe like below
```[ngTemplateOutlet]="templateName | templateRef"```
In this case **templateName** can be string.

### Describe alternatives you've considered
 
Here is the current alternative to the problem described above.
[https://stackblitz.com/edit/ng-template-outlet-mhpnas?file=app/app.component.ts](url)

**Comment by trotyl** [comment]
Pipes are just normal user code, no pipe can bring extra capability to framework runtime. You'll need to request an imperative view children query API first.

**Comment by dawidgarus** [comment]
You can create a directive that registers a template in a service and pipe to retrieve it:
https://stackblitz.com/edit/angular-hkwoby
