### ISSUE TITLE
QueryList#changes is not typed strongly

### ISSUE THREAD

**Issue by Airblader** [angular/angular#30296]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core.

### Is this a regression?

No.

### Description

The type of `QueryList#changes` is `Observable<any>` ([link](https://github.com/angular/angular/blob/7.2.14/packages/core/src/linker/query_list.ts#L44)). Given that `QueryList` does have a type argument, the type should be `Observable<T[]>` as – at least AFAIK – this is the only thing that is ever emitted here.

Additionally, it is initialized as `EventEmitter` for no good reason and should probably be a `Subject` instead.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
7.3.6
</code></pre>

**Comment by Airblader** [comment]
I thought an issue for this must exist already, but couldn't find one. Apologies if this is a duplicate.

**Comment by Airblader** [comment]
Actually, `changes` appears to emit the entire QueryList. So instead I guess it would be `Observable<QueryList<T>>`?

**Comment by trotyl** [comment]
> So instead I guess it would be `Observable<QueryList<T>>`?

Can be simplified to `Observable<this>`.

**Comment by krzysztof-grzybek** [comment]
Hey! Is there any specific reason why this PR wasn't accepted?
https://github.com/angular/angular/pull/30375

It would be really nice to have strong types here.

**Comment by misha98857** [comment]
Type for `QueryList#changes` has been fixed in #40091.

**Comment by JeanMeche** [comment]
In v17.2 Angular added support for signal view queries which don't have this typing issue. This is now recommended alternative for type-satety.
