### ISSUE TITLE
Dart build is slow (>30m)

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#3030]
This slows us down a lot, especially for vetting PRs. Marking P1 as a substitute for 'high severity'.

Discussed with @vsavkin and @tbosch - theory is that every time we add an example, we have another expensive invocation of dart analyzer and dart2js because it is an additional entry point. We really only need to run one of the examples in dart, as a smoke test.

**Comment by alexeagle** [comment]
Have started working on this with @tbosch but won't be done for this milestone.

**Comment by alexeagle** [comment]
currently blocked on `pub serve`.
The issue is when we serve JSONP content. We serve a `.json` file (could be renamed to `.jsonp`) and it was previously served with no content-type. That's okay because strict mime checking was turned off in Chrome.
However, `pub serve` includes `X-Content-Type-Options: nosniff` header
https://github.com/dart-lang/sdk/blob/da0363172adaa266ef2d44cf87e09b61a185e79d/sdk/lib/io/http.dart#L173
and this turns on the strict MIME checking. That means the `.jsonp` file needs to have `Content-type: application/javascript

**Comment by munificent** [comment]
Huh. Maybe the cleanest solution is to have pub's MIME resolver support .jsonp as MIME type `application/javascript`. We could just turn off nosniff completely, but that feels like it may lead users down a path where their app works in pub serve, but not when they deploy it.

I'll talk to @nweiz who probably has a more informed opinion on this and see what she thinks. Either way, it should be relatively straightforward to fix this.

**Comment by alexeagle** [comment]
Thanks! I think I also have a workaround of rewriting the content type in
an extra middleware (we are proxying through node connect)

**Comment by alexeagle** [comment]
Note for future reference.
Our solution here is to serve the dart tests differently for PRs: we just `pub serve
