### ISSUE TITLE
Mistake in Angular document for Singleton Services

### ISSUE THREAD

**Issue by cmrarjun** [angular/angular#30303]
Hi,

While going through https://angular.io/guide/singleton-services, i have analyzed that even declaring the root value in providedIn property of @Injectable() cannot make a service singleton because Suppose same service is added as dependency in a feature module and angular Router creates a child injector for it when we navigate to a component in that feature module. child injector creates a local instance of that service. So there will be two instances of same service. So please help me out in how to make it singleton.

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
