### ISSUE TITLE
Mistake in Angular document for Singleton Services

### ISSUE THREAD

**Issue by cmrarjun** [angular/angular#30304]
# 📚 Docs or angular.io bug report

### Description

 While going through https://angular.io/guide/singleton-services, i have analyzed that even declaring the root value in providedIn property of @Injectable() cannot make a service singleton because Suppose same service is added as dependency in a feature module and angular Router creates a child injector for it when we navigate to a component in that feature module. child injector creates a local instance of that service. In this way there can be multiple instances of same service. So please help me out in how to make it singleton.

### What's the affected URL?**
 https://angular.io/guide/singleton-services#providing-a-singleton-service

### Reproduction Steps**

1. Go to https://angular.io/guide/singleton-services#providing-a-singleton-service
2. There it is mentioned like "Declare root for the value of the @Injectable() providedIn property" makes a service singleton.
3. But there can be multiple instances of same service. one is created by root injector and others are is created by child injectors

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by kapunahelewong** [comment]
Hi @cmrarjun! Check out this PR that is in the works. It's going to change significantly soon, but what's in there so far might help you with context. [Hierarchical Injectors PR 28700](https://pr28700-ee6cedc.ngbuilds.io/guide/hierarchical-dependency-injection#two-injector-hierarchies).

Here's my understanding. There are different injector trees and it depends on where you provide services that controls visibility. A child `ModuleInjector` is created when lazy loading modules. If you don't lazy load them, you won't get child `ModuleInjector`s and so a service provided in `root` would be a singleton. This is not the case if you lazy load and then provide the service in the lazy loaded module. When you provide services in components, your services are visible in the relevant part of the `ElementInjector` tree. This might be why you're running into this question. Anyone who reads this, feel free to correct me if I'm off anywhere (and in my PR!) Hope this helps.

**Comment by kapunahelewong** [comment]
@cmrarjun This question might also be helpful: [https://angular.io/guide/ngmodule-faq#q-why-bad](https://angular.io/guide/ngmodule-faq#q-why-bad)

**Comment by kapunahelewong** [comment]
Hey @cmrarjun, did either of those links or my explanation help you out?

**Comment by rockument69** [comment]
@kapunahelewong : This looks like it is done, except the PR is still open?

**Comment by atscott** [comment]
Closing as resolved by https://github.com/angular/angular/commit/1c6516199e22629a30fb26dd37e6a79634e6091c
