### ISSUE TITLE
Styles defined in animation transition is not applied in Safari and IE11

### ISSUE THREAD

**Issue by ysavoie-lavigueur** [angular/angular#30314]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/animations

### Is this a regression?

 No

### Description

 Temporary styles that should be applied during animation transitions are not applied to target element.

## 🔬 Minimal Reproduction

For example, this collapse animation should change color while animating. It works fine on Chrome, Firefox, Edge but doesn't work on Safari and IE11:

<pre><code>
export function CollapseAnimation(): AnimationTriggerMetadata
{
  return trigger(
    'collapse',
    [
      state('true', style(
      {
        border: '2px solid blue',
        height: '20px',
        overflowY: 'hidden'
      })),
      state('false', style(
      {
        border: '2px solid blue',
        height: '*',
        overflowY: 'hidden'
      })),
      transition('false => true', [
        style({border: '2px solid red', overflowY: 'hidden'}), // Bug --> not applied
        animate('1s')
      ]),
      transition('true => false', [
        style({border: '2px solid green', overflowY: 'hidden'}), // Bug --> not applied
        animate('1s')
      ])
    ]);
}

</code></pre>

https://stackblitz.com/edit/angular-tpwpgx

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.3.8
Node: 10.15.3
OS: win32 x64
Angular: 7.2.5
... common, compiler, compiler-cli, core, forms,
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.0
@angular-devkit/build-angular     0.10.0
@angular-devkit/build-optimizer   0.10.0
@angular-devkit/build-webpack     0.10.0
@angular/animations               7.2.5
@angular/cli                      7.0.2
typescript                        3.1.1

</code></pre>

**Anything else relevant?**

Browsers:
- Safari (iOS 12.1.1)
- Internet Explorer 11 (Windows 10)

**Comment by raymondkarstensen** [comment]
Have the same issue. A temporary downgrade to 7.2.4 for @angular/animations seems to work for me.

**Comment by kvbutler** [comment]
@raymondkarstensen Confirmed reverting from 7.2.15 to 7.2.4 worked for me as well in Safari and IE. Thanks!

**Comment by jessicajaniuk** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
