### ISSUE TITLE
Problem with HttpСlient (param: reportProgress)

### ISSUE THREAD

**Issue by Mreddi1** [angular/angular#30337]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/5.0.0

### Is this a regression?

 I don`t know

### Description
 
There was a problem calling the function:
<pre>
const req = new HttpRequest('POST', url, fileData, { headers, reportProgress: true, observe: 'events' });

this.http.request(req).subscribe((event)=>{...});
</pre>

Next, performing comparsion: 
<pre>
(event.type === HttpEventType.UploadProgress)
</pre>
And get the number of percent of the file download.

But when using the **Safari (desktop) v.12.0 (14606.1.36.1.9)**, the condition is triggered once and does not give complete data on the number of bytes transmitted on server.

This process is random. At one point in time, everything works correctly, at another it does not work correctly.
 
## 🔬 Minimal Reproduction

[https://stackblitz.com/edit/angular-file-upload-cszfpp](https://stackblitz.com/edit/angular-file-upload-cszfpp)

[https://i.imgur.com/x2qbOdB](https://i.imgur.com/x2qbOdB.png)

## 🔥 Exception or Error
<pre>
 None
</pre>

## 🌍  Your Environment
<pre><code>
Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version v.12.0 (14606.1.36.1.9) (MacBook Air Mid 2013/macOS Mojave v.10.14)
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by alxhub** [comment]
@Mreddi1 my initial guess is that this would be an upstream issue in Safari and not an issue in Angular. But maybe we can work around this somehow. Have you tried without `HttpClient` (e.g. just using a plain XHR?)

**Comment by Mreddi1** [comment]
I also agree that this is a Safari problem. No, I have not tried. I found a similar problem https://bugs.webkit.org/show_bug.cgi?id=165897 maybe it refers to an problem/

**Comment by alxhub** [comment]
Closing as this issue is very likely not with Angular - we're only reporting the numbers the browser gives us.
