### ISSUE TITLE
ng add @angular/bazel on windows 10 throw missing --name

### ISSUE THREAD

**Issue by istiti** [angular/angular#30347]
# 🐞 bug report

### Affected Package
Caused by [@angular/bazel (packages/bazel/src/schematics/ng-add/index.ts#L379)](https://github.com/angular/angular/blob/master/packages/bazel/src/schematics/ng-add/index.ts#L379)

### Description

Following [aio:bazel doc](https://next.angular.io/guide/bazel) to add bazel in an existing CLI application project on Windows

## 🔬 Minimal Reproduction
On Windows10 platform:
1. Run `ng add @angular/bazel@next`

## 🔥 Exception or Error
After command finish, console output:

> Installing packages for tooling via npm.
> + @angular/bazel@8.0.0-rc.3
> added 28 packages from 79 contributors and audited 19216 packages in 11.3s
> found 0 vulnerabilities
> 
> Installed packages for tooling via npm.
> Please specify a project using "--name project-name"

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0-rc.3
Node: 12.2.0
OS: win32 x64
Angular: 8.0.0-rc.3
... animations, bazel, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.3
@angular-devkit/build-angular     0.800.0-rc.3
@angular-devkit/build-optimizer   0.800.0-rc.3
@angular-devkit/build-webpack     0.800.0-rc.3
@angular-devkit/core              8.0.0-rc.3
@angular-devkit/schematics        8.0.0-rc.3
@angular/cdk                      8.0.0-rc.0
@angular/http                     8.0.0-beta.10
@angular/material                 8.0.0-rc.0
@angular/pwa                      0.800.0-rc.3
@ngtools/webpack                  8.0.0-rc.3
@schematics/angular               8.0.0-rc.3
@schematics/update                0.800.0-rc.3
rxjs                              6.5.1
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**
`--name` should be automatically determined 

PS: after rerun command `ng add @angular/bazel@next --name ap` it is ok, needed files are created!

cc @filipesilva

**Comment by filipesilva** [comment]
cc @kyliau

**Comment by kyliau** [comment]
This was fixed in https://github.com/angular/angular/pull/30074, but did not get included in the rc release. I'll cherry-pick it into patch branch.

**Comment by kyliau** [comment]
https://unpkg.com/@angular/bazel@8.0.0-rc.4/src/schematics/ng-add/schema.json
--> name is no longer required

https://unpkg.com/@angular/bazel@8.0.0-rc.4/src/schematics/ng-add/index.js
--> default name is set on this line if none is provided

Issue is confirmed to be fixed.
