### ISSUE TITLE
Implement Query filters 

### ISSUE THREAD

**Issue by rkirov** [angular/angular#3034]
To support more flexible queries implement an option to pass filter to Query. For example: ```@Query(MyFeature.filter) list: QueryList<dynamic>``` where ```static filter(obj) => obj is Foo || obj is Bar.```

see discussion on https://github.com/angular/angular/issues/1935 for more info.

**Comment by matanlurey** [comment]
:+1:

**Comment by rkirov** [comment]
Needs more design, as discussed passing every object through an opaque filter will prohibit further optimizations down the road.

**Comment by rkirov** [comment]
Discussed with Misko, we should tackle benchmarking query and performance improvements first before adding more general APIs.

**Comment by jhades** [comment]
I just wanted to mention that this feature could be more important than it might look at first sight. There are a lot of common use cases that seem to need this feature, take for example a menu with sub-menus:

    <top-menu>
        <option title="Menu Entry 1"></option>
        <option title="Menu Entry 2 "></option>
        <option-group title="Menu Entry 3 Sub menu">
            <option title="sub-menu entry 1"></option>
            <option title="sub-menu entry 2"></option>
            <option-group title="Submenu entry 3">
                <option title="Sub-Submenu entry 1"></option>
                <option title="Sub-Submenu entry 2"></option>
            </option-group>
        </option-group>
    </top-menu>

In this case I believe we need to have in the `top-menu` `@Component` a `QueryList` of both the `option`and `option-group` light-dom element directives. So we can loop over that list and render it as either an entry or a submenu. 

Or is there some other alternative way of implementing this with the current API? Thanks

**Comment by mhevery** [comment]
Let's not implement this just yet, as it may have negative perf improvement. Let's make sure that we have real use cases, which can not be implemented in other ways.

**Comment by bduffany** [comment]
fyi this issue was referenced on StackOverflow: http://stackoverflow.com/questions/32300168/how-to-get-a-reference-to-a-particular-component-in-an-angular2-template

**Comment by mhevery** [comment]
I think the latest thinking is now, as it would prevent compile time generation of the queries.  Will close.

/cc @tbosch

**Comment by bduffany** [comment]
@mhevery could you explain what you mean by that last comment?

**Comment by tbosch** [comment]
We will soon calculate the queries already during compilation.
With that, any filter function would need to be executed during compile
time as well. However, we don't have a good way to configure things that
need to run during compilation, as compilation will soon also run on the
server.

We could add a filter function that we just call on the query result, but
then there would be no benefit to a user filtering the result of a query
manually.
I would vote for not adding filters as it is one more concept that a user
has to learn, and does not provide a big benefit.
