### ISSUE TITLE
update shared dependency to Angular 8

### ISSUE THREAD

**Issue by santoshyadav198613** [angular/angular#30358]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...
Example code contains still uses Angular 7 lets upgrade to Angular 8.

https://github.com/angular/angular/tree/master/aio/tools/examples/shared

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by artem-galas** [comment]
I've started update packages, but we had one dependency `angular-in-memory-web-api`

Which are using `"github:brandonroberts/in-memory-web-api-bazel#50a34d8"` that incompatible with `angular-8`. 

https://github.com/angular/angular/blob/master/aio/tools/examples/shared/package.json#L36

What shall we use here?

**Comment by santoshyadav198613** [comment]
Keep it as it is, Brandon has fix for it, update rest of the dependencies.

Regards, 
Santosh

**Comment by santoshyadav198613** [comment]
Hi @artem-galas,

Looks like Brandon is already working on #30385. Which will take care of this.

Let me close this.

**Comment by artem-galas** [comment]
@santoshyadav198613 
Yes of course, no problem
