### ISSUE TITLE
Make RxJS optional!!!

### ISSUE THREAD

**Issue by LukeTOBrien** [angular/angular#30354]
Hi there,

I am writing this post under a cloud of extreme frustration the likes of which no one has ever seen before.  
As an aside must frustration is coming from my Angular CLI app which is throwing non-sencicle compile error and I seem to be stuck in a catch-22 situation.

... But anyway I digress..

It has been on my mind for a long time now that you should really make RxJS optional, I do like RxJS, but I only really use it for events, for http Promises will do fine for me.  
All my logic is performed on the server-side, so my return responses are just Models that need binding to the view, I don't need to .map or any other operator on my http responses... I think Observables just add extra overhead when they are not needed.  

What caused me to make this rant was the following error...?????  
It seems that with every version Angular breaks itself.

```
ERROR in ../node_modules/@angular/core/esm5/core.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:\...\node_modules\@angular\core\esm5'
ERROR in ../node_modules/@angular/http/esm5/http.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:\...\node_modules\@angular\http\esm5'
ERROR in ../node_modules/@angular/core/esm5/core.js
Module not found: Error: Can't resolve 'rxjs/Subject' in 'C:\...\node_modules\@angular\core\esm5'
ERROR in ../node_modules/@angular/core/esm5/core.js
Module not found: Error: Can't resolve 'rxjs/observable/merge' in 'C:\...\node_modules\@angular\core\esm5'
ERROR in ../node_modules/@angular/core/esm5/core.js
Module not found: Error: Can't resolve 'rxjs/operator/share' in 'C:\...\node_modules\@angular\core\esm5'
```

**Comment by sarunint** [comment]
It seems that you are using RxJS version 6 with Angular version less than 6.

Check https://github.com/angular/angular/blob/5.2x/packages/core/package.json

**Comment by mlc-mlapis** [comment]
@LukeTOBrien ... you didn't mention any details ... but `'rxjs/Observable'` sounds like you are on the old version ... ^^^

**Comment by maktarsis** [comment]
Hey @LukeTOBrien,
Could you provide a demo? 
It can help us to catch the problem in your code.

**Comment by LukeTOBrien** [comment]
I have just done a `ng new` with the latest CLI:
```
    "@angular/core": "~7.2.0",
...
    "rxjs": "~6.3.3",
```
But I think this error is a red herring (seem to get a lot of them), so don't sweat it.  

Point I was trying to make is I don't use Observables but I HAVE TO.  
In my services for example I have code like:

``` TypeScript
  Login(loginRequest: any): Observable<any> {
      console.log(this.env)
      return Observable.create(observer => {
          this.http.post(`${this.env.server}api/Account/Login`, loginRequest).subscribe(response => {
              let json = response.json();
              this.user = json.user;
        observer.next(json);
      });
    });
  }
```

So here Promises would do fine.

Anyway sorry for wasting your time...

**Comment by negue** [comment]
@LukeTOBrien something like this should work, you don't need to create a another Observable you already have one (`this.http.post()`):

```ts
  Login(loginRequest: any): Observable<any> {
      console.log(this.env)
      return this.http.post(`${this.env.server}api/Account/Login`, loginRequest)
		.pipe(
			tap(response => this.user = response.json().user)
		);
    });
  }
```
