### ISSUE TITLE
Mistake in docs on XSRF Protection

### ISSUE THREAD

**Issue by Cito** [angular/angular#30367]
# 📚 Docs or angular.io bug report

### Description

The documentation for "HttpClient - Security: XSRF Protection" says:

> "By default, an interceptor sends **this cookie** on all mutating requests (POST, etc.) to relative URLs but not on GET/HEAD requests or on requests with an absolute URL."

I think instead of "this cookie" it should say "this header", right?

### What's the affected URL?

https://angular.io/guide/http#security-xsrf-protection

**Comment by kapunahelewong** [comment]
Thank you for this @Cito!

**Comment by FrederikSchlemmer** [comment]
@kapunahelewong are you working on this issue? Otherwise I could take over this issue.

**Comment by kapunahelewong** [comment]
Hi @FrederikSchlemmer, if you'd like to, sure! Will you tag me on the PR so I can stay in the loop? This is great, thanks! :)

**Comment by FrederikSchlemmer** [comment]
Hi @kapunahelewong, I will tag you in the PR. Thanks!

**Comment by ajitsinghkaler** [comment]
@kapunahelewong I think we can close this issue

**Comment by kapunahelewong** [comment]
Thank you for looking out, @ajitsinghkaler! 🙂
