### ISSUE TITLE
Upgrade http-server in example to 0.11.1

### ISSUE THREAD

**Issue by santoshyadav198613** [angular/angular#30363]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

Currently, we are using http-server package for running doc portal locally and we are using http-server version 0.9 which is dependent on ecstatic 1.4, which is removed from artifactory.

Even http-server is not updated from last 1 year, so for best let's move away to 
https://www.npmjs.com/package/local-web-server or update to latest version which is 0.11.1

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by gkalpak** [comment]
There are [some things going on][1] with ecstatic (which is used by `http-server`), but I would wait for the dust to settle before making any changes (such as moving to a different server package). Updating to latest stable version shouldn't hurt, though.

[1]: https://github.com/angular/angular/pull/30417
