### ISSUE TITLE
Unable to use component in different lazy load modules

### ISSUE THREAD

**Issue by aika-ssha** [angular/angular#30378]
Hey, guys! I have one problem. I have 8 lazy loaded modules and everything works perfect except 1 thing. When I logout from 1 module and login again with different role to other module it throws error, cause both of them use the same components from SharedModule. I need this behaviour cause the same person can have 2 or more different roles and can login into 2 or more modules from the same device without reloading page.

# 🐞 bug report

Angular Version:  ~7.2

Adding possibility to use same components in different lazy load modules.

**Comment by mlc-mlapis** [comment]
@aika-ssha ... it's not related together. If declaring a component in a shared module and then you can import that shared module into any number of lazily-loaded modules. It has nothing to do with roles or anything else.

**Comment by Airblader** [comment]
The issue tracker is not for general support questions, please see [this](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
