### ISSUE TITLE
URL query string value encoding

### ISSUE THREAD

**Issue by AmarjitMindtree** [angular/angular#30379]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
@angular/common/http

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
I am not sure, I did not check.

### Description

 A clear and concise description of the problem...
If we pass data in query string in GET method with param value of HTTP PARAMS, by default it is not converting '@' symbol to %40 or any other reserved symbol with is corresponding UTF-8 code. It should convert '@' to %40, because of this I am not able to use http get with querystring.
eg, http://localhost:4200/api/usersData?userName=xxx.xxx@xxx.com&password=xxx@xxx
above request is failing.

Expected / new behavior:

function standardEncoding(v: string): string {
return encodeURIComponent(v)
.replace(/%40/gi, '@')
.replace(/%3A/gi, ':')
.replace(/%24/gi, '$')
.replace(/%2C/gi, ',')
.replace(/%3B/gi, ';')
.replace(/%2B/gi, '+')
.replace(/%3D/gi, '=')
.replace(/%3F/gi, '?')
.replace(/%2F/gi, '/');
}

this code is not able to convert @ to %40. It should do that.
If is write replace('@', '%40') then it is working.

Minimal reproduction of the problem with instructions:

Below mentioned code is the service code which is making a GET request with query string.

data passed is,
userName = xxx@xxx.com
password = pwd@#

const options = {
headers: new HttpHeaders({
'Content-Type': 'application/json',
}),
observe: 'response' as 'body',
params: null,
reportProgress: true,
responseType: 'json' as 'json',
withCredentials: true
};

@Injectable({
providedIn: 'root'
})
export class AuthenticationService {

constructor(private http: HttpClient) {
}

// login user
login(requestParam: { userName: string, password: string }): Observable<HttpResponse> {
options.headers = options.headers.set('Content-Type', 'application/x-www-form-urlencoded');
options.params = new HttpParams({ fromObject: requestParam, encoder: this.httpParameterCodec });
console.log(options.params);
return this.http.get<HttpResponse<Observable>>
(${environment.API_URL}usersData, options)
.pipe(
// retry(3),
catchError(this.handleError)
);
}

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

I am using In-Memory-Api for processing the report, then I am sent the queryString like
?userName=xxx@xxx.com&password=xxxx@xx
@, $ etc are not processing the request.

## 🔥 Exception or Error
<pre><code>

</code></pre>

http://localhost:4200/api/usersData?userName=bc@abc&password=abc 404 (Not Found)
Server error respose code:  404
Body was:  <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/usersData</pre>
</body>
</html>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

Angular CLI: 7.3.8
Node: 10.15.3
OS: win32 x64
Angular: 7.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

**Anything else relevant?**

**Comment by Airblader** [comment]
What is `httpParameterCodec`? I think that passing this overwrites how the URL is encoded, so probably that's the issue. Can you provide a Sackblitz demonstrating your problem?

**Comment by AmarjitMindtree** [comment]
Component
----------
import { Component, OnInit } from '@angular/core';
import { AuthenticationService } from './shared/service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.sass']
})
export class AppComponent implements OnInit {
  title = 'InMemoryWebApi';
  constructor(private authenticationService: AuthenticationService) {}
  ngOnInit() {

    this.authenticationService.login({ userName: 'bc@abc', password: 'abc'})
    .subscribe(
      (next) => {
        console.log(next);
      },
      (err) => {
        console.error(err);
      },
      () => {
        console.log('Completed succesfully');
      }
    );
  }
}
----------------------------------------------------------
Service;
import { Injectable } from '@angular/core';
import {
  HttpClient,
  HttpResponse,
  HttpErrorResponse,
  HttpHeaders,
  HttpParams,
  HttpParameterCodec
} from '@angular/common/http';
import { environment } from '../../../../environments/environment';
import { Observable, throwError } from 'rxjs';
import { catchError } from 'rxjs/operators';

const options = {
  headers: new HttpHeaders({
    'Content-Type': 'application/json',
  }),
  observe: 'response' as 'body',
  params: null,
  reportProgress: true,
  responseType: 'json' as 'json',
  withCredentials: true
};

@Injectable({
  providedIn: 'root'
})
export class AuthenticationService {

  constructor(private http: HttpClient) {
  }

  // login user
  login(requestParam: { userName: string, password: string }): Observable<HttpResponse<object>> {
    options.headers = options.headers.set('Content-Type', 'application/x-www-form-urlencoded');
    options.params =  new HttpParams({ fromObject: requestParam, encoder: this.httpParameterCodec });
    return this.http.get<HttpResponse<Observable<object>>>
    (`${environment.API_URL}usersData`, options)
    .pipe(
      // retry(3),
      catchError(this.handleError)
    );
  }

  private handleError(err: HttpErrorResponse) {
    if (err.error instanceof ErrorEvent) {
      console.error('An error occured: ', err.error.message);
    } else {
      console.error('Server error respose code: ', err.status);
      console.error('Body was: ', err.error);
    }
    return throwError('Something bad happened, please try again');
  }
}

------------------------------------------
In-memory data service:

import { Injectable } from '@angular/core';
import { InMemoryDbService, ResponseOptions, BackendService } from 'angular-in-memory-web-api';
import { Observable, of } from 'rxjs';
import { usersData, adminsData } from '../_defaultData';
import { HttpRequest } from '@angular/common/http';
import { query } from '@angular/core/src/render3';

@Injectable({
  providedIn: 'root'
})
export class DataService implements InMemoryDbService {

  createDb(): {} | Observable<{}> | Promise<{}> {
    return { usersData , adminsData };
  }
}


---------------
Shortly I will try to give stack blitz

**Comment by Airblader** [comment]
Your code again doesn't include the definition of your encoder. Please also use the code formatting, it's basically unreadable in its current form.

**Comment by AmarjitMindtree** [comment]
I am sorry...i removed that 

> encoder: this.httpParameterCodec

evenn though I am getting error.

I was overriding the default code
**httpParameterCodec: HttpParameterCodec = {
    encodeKey: (key: string) => this.standardEncoding(key),
    decodeKey: (key: string) => decodeURIComponent(key),
    encodeValue: (val: string) => this.standardEncoding(val),
    decodeValue: (val: string) => decodeURIComponent(val)
  };

  standardEncoding(v: string): string {
    return encodeURIComponent(v)
      .replace('@', '%40')  ---> by default it was .replace(/%40/gi, '@')
      .replace(/%3A/gi, ':')
      .replace(/%24/gi, '$')
      .replace(/%2C/gi, ',')
      .replace(/%3B/gi, ';')
      .replace(/%2B/gi, '+')
      .replace(/%3D/gi, '=')
      .replace(/%3F/gi, '?')
      .replace(/%2F/gi, '/');
  }**


I removed the above code and checked with normal , it is showing error, it is not converting '@' symbol to %40

**Comment by AmarjitMindtree** [comment]
https://github.com/AmarjitMindtree/AngularHttp

this is the location of code

**Comment by arobinson** [comment]
I'm also seeing encoding issues on Angular 7.2.5:
```
const fileName = 'Payment!@#$%^()_+&Terms.csv'
const correctEncoding = encodeURIComponent('Payment!@#$%^()_+&Terms.csv');
const angularEncoding = (new HttpParams()).encoder.encodeKey(fileName);
console.log('Correct: %o,\nAngular: %o\nEqual:%o', correctEncoding, angularEncoding, correctEncoding === angularEncoding);
```
Output:
```
Correct: "Payment!%40%23%24%25%5E()_%2B%26Terms.csv",
Angular: "Payment!@%23$%25%5E()_+%26Terms.csv"
Equal:false
```
This is preventing us from downloading some files from our backend due to bad URL escaping

**Comment by wjabbour** [comment]
Something that might be notable:
If it is correct behavior that when encoding a URL that HttpParams.encoder.encodeKey(stringToEncode)
should be called, then it seems the implementation in @angular/common/http/params.ts is backwards. 

It encodes the string with the Javascript encodeURIComponent(string) as expected, but then immediately calls the .replace() function to replace the encoded strings with their unencoded form. Specifically the characters '@', ':', '$', ',', ';', '+', '=', '?', and '/'.

To correct: 

function standardEncoding(v: string): string {
  return encodeURIComponent(v);
}

**Comment by spinnercat** [comment]
Why does the default HTTP encoder use standardEncoding (which does not encode special characters like `;`) to encode keys and values instead of just encodeURIComponent? If you have an object that is `{"key": "value;with+characters"}` shoudn't this be encoded to `key=value%3Bwith%2Bcharacters` as opposed to `key=value;with+characters`, as the latter seems very likely to be misinterpreted by the web server when it tries to parse the query string? I get that for encoding URIs in general, the semicolon is an acceptable character and should not be encoded, hence the existence of `standardEncoding` but when encoding keys and values of params, you clearly don't want to have special characters left alone that might affect how the query string gets parsed...

**Comment by alxhub** [comment]
The set of encoded characters was copied from AngularJS HTTP, and is meant to be backwards compatible with older Angular apps. `encodeURIComponent` is a bit overzealous and might generate undesirable URLs.

The solution here is to use a custom codec if you need to override how certain characters get encoded.

**Comment by spinnercat** [comment]
What's an example of legacy code or an expected use case that would result in older apps breaking or undesirable URLs? It seems like you would need to have an object with a string key or value that contains special characters that you'd want to leave intact so that your backend server interprets them as special URI tokens - I struggle to think of a scenario in which this would arise.
