### ISSUE TITLE
Docs: Remove mention of Chrome 41 for differential loading

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#30387]
# 📚 Docs or angular.io bug report

### Description

 

The differential loading guide at https://next.angular.io/guide/deployment#configuring-differential-loading mentions Chrome 41 in the browserslist config and in the text below as included for SEO. This is no longer required, as Googlebot has been updated to a more recent version of Chrome. 

1. Update the section in the differential loading doc to match the current browserslist config from the CLI https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/application/files/browserslist.template
2. Remove the text about Chrome 41 in the text below. https://github.com/angular/angular/blob/master/aio/content/guide/deployment.md

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by Showtim3** [comment]
This seems like an easy issue. All i have to do is to remove the **chrome 41** from the browserslist and the paragraph immediately below that in the **Configuring differential loading**
section. This is my first time contributing.Please let me know if i can work on the issue and submit a PR. 
Thanks.

**Comment by Showtim3** [comment]
This seems like an easy issue. All i have to do is to remove the **chrome 41** from the browserslist and the paragraph immediately below that in the **Configuring differential loading** section in deployment.md file. This is my first time contributing.Please let me know if i can work on the issue and submit a PR. 
Thanks.

**Comment by gkalpak** [comment]
AFAICT, this has been fixed by #30390.
<sub>Please, re-open if not.</sub>
