### ISSUE TITLE
bazel: new project Cannot find module '@angular/upgrade/static'.

### ISSUE THREAD

**Issue by william-lohan** [angular/angular#30399]
# 🐞 bug report

### Affected Package
@angular/bazel

### Description
`ng new bzl-app --collection=@angular/bazel`
produces error:
>Cannot find module '@angular/upgrade/static'.

Then you have to manually add `@angular/upgrade` then `npm i` again without error

## 🔬 Minimal Reproduction
`npm i -g @angular/cli@angular/bazel`
`ng new bzl-app --collection=@angular/bazel`

## 🔥 Exception or Error
>node_modules/@angular/router/upgrade/src/upgrade.d.ts(9,31): error TS2307: Cannot find module '@angular/upgrade/static'.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.9
Node: 10.15.3
OS: win32 x64
Angular: 7.2.15
... animations, bazel, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Comment by codingnuclei** [comment]
try ng update @angular/cli @angular/core 

You need version 8 of angular and the cli I believe.

**Comment by william-lohan** [comment]
`ng update @angular/cli @angular/core --next true` still produces 

>node_modules/@angular/common/upgrade/upgrade.d.ts(14,31): error TS2307: Cannot find module '@angular/upgrade/static'.
node_modules/@angular/router/upgrade/upgrade.d.ts(9,31): error TS2307: Cannot find module '@angular/upgrade/static'.

<pre><code>
Angular CLI: 8.0.0-rc.3
Node: 10.15.3
OS: win32 x64
Angular: 8.0.0-rc.3
... animations, bazel, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.3
@angular-devkit/build-angular     0.800.0-rc.3
@angular-devkit/build-optimizer   0.800.0-rc.3
@angular-devkit/build-webpack     0.800.0-rc.3
@angular-devkit/core              8.0.0-rc.3
@angular-devkit/schematics        8.0.0-rc.3
@ngtools/webpack                  8.0.0-rc.3
@schematics/angular               8.0.0-rc.3
@schematics/update                0.800.0-rc.3
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by william-lohan** [comment]
I copied https://github.com/angular/angular/blob/1f4c380f58d84bc50712f7a9625e62bb3f923ba1/packages/bazel/src/schematics/ng-add/files/angular-metadata.tsconfig.json.template and it worked this change https://github.com/angular/angular/commit/1f4c380f58d84bc50712f7a9625e62bb3f923ba1#diff-942614671385c916087baedff195b4d5 must have fixed but i would have needed to update to `next` (v8) globally then `ng new bzl-app --collection=@angular/bazel`.

Adding `skipLibCheck` also worked, could that be beneficial/more robust to add to `angular-metadata.tsconfig.json`, since its only to get ngsummary files?
