### ISSUE TITLE
it would be nice to have a way to automatically show methods and properties that are deprecated

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#30408]
# 📚 Docs or angular.io bug report

### Description

 
Currently, if a property or method is deprecated, a code owner or doc author must explicitly state that in the description text for that property or method. There is no automated way to have these presented in the AIO docs with strikethrough and a standard "Deprecated in version x" statement. 

## 🔬 Minimal Reproduction
See https://next.angular.io/api/forms/ReactiveFormsModule#withconfig

There is no indication in the AIO docs that this is deprecated. 

Now click `< >` to see the source code, where the deprecation is mentioned:
```
static withConfig(opts: {
    /** @deprecated as of v6 */ warnOnNgModelWithFormControl: 'never' | 'once' | 'always'
  }): ModuleWithProviders<ReactiveFormsModule> {
    return {
      ngModule: ReactiveFormsModule,
      providers: [{
        provide: NG_MODEL_WITH_FORM_CONTROL_WARNING,
        useValue: opts.warnOnNgModelWithFormControl
      }]
    };
```

### What's the affected URL?**
 
See above. Also see https://github.com/angular/angular/issues/30098 for more examples. 

### Reproduction Steps**

See above

### Expected vs Actual Behavior**

Readers expect AIO to clearly identify these properties and methods as deprecated, without having to open the source code to read the comments. 

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Anything else relevant?

Related Issues: 
Deprecate `ReactiveFormsModule.withConfig` method
https://github.com/angular/angular/issues/22640

docs: add deprecation info for properties, methods, etc. to deprecations summary doc
https://github.com/angular/angular/issues/30098

**Comment by petebacondarwin** [comment]
Properties, etc on classes, interfaces etc are actually automatically displayed as struck-out if they are deprecated.
What is being asked for here is to display properties on inline types as struck-out if they are deprecated. Currently there is very limited support for rendering such inline types, so this would be quite a lot of effort to implement, for now a huge amount of benefit, IMO. If the inline type is extracted out into a named interface then we can easily render such deprecated properties.
