### ISSUE TITLE
window.setTimeout called immediately

### ISSUE THREAD

**Issue by bitbay** [angular/angular#30404]
# 🐞 bug report

### Affected Package
?

### Is this a regression?
Not sure.

### Description
Setting high value for the delay on `window.setTimeout` causes the callback to be executed before it should (almost immediately). Did not figure out the threshold number yet...

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-timeout-bug

## 🔥 Exception or Error
<pre><code>
window.setTimeout(() => {
  console.log("long delay called");
}, 2667780325);

window.setTimeout(() => {
  console.log("25sec delay called");
}, 25000);
</code></pre>
Should print to console `25sec delay called` first, and (much) later `long delay called`.
It prints `long delay called` instead first, then 25 seconds later `25sec delay called`

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.1.4
Node: 10.1.0
OS: linux x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@angular/cdk                      7.2.0
@angular/material                 7.2.0
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
</code></pre>
But the stackblitz example uses
<pre><code>
"@angular/common": "^7.2.5",
    "@angular/compiler": "^7.2.5",
    "@angular/core": "^7.2.5",
    "@angular/forms": "^7.2.5",
    "@angular/platform-browser": "^7.2.5",
    "@angular/platform-browser-dynamic": "^7.2.5",
    "@angular/router": "^7.2.5",
    "core-js": "^2.6.5",
    "rxjs": "^6.4.0",
    "zone.js": "^0.8.29"
</code></pre>

**Anything else relevant?**
Tried in chrome, no other browser.

**Comment by bitbay** [comment]
updated the description after an accidental "press enter" on initial opening the bug.

**Comment by lazarljubenovic** [comment]
I don't think this has anything to do with Angular. Just wrote

```
window.setTimeout(() => console.log('wat'), 2667780325)
```

in the console on this page and got back a `wat` immediately. Wat indeed.

Then again, 2667780325 is over 30 days, so what are you exactly trying to do?

**Comment by ericmartinezr** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#Maximum_delay_value

**Comment by bitbay** [comment]
@lazarljubenovic thanks for pointing it out! This IS a shock to me! Do not trust javascript?! Will dig the specs to see if i find some clues about this.

**Comment by bitbay** [comment]
@ericmartinezr ...that was FAST! Thank You both very much!
