### ISSUE TITLE
min, max (Template Driven form) angular fails to mark the FormControl as invalid

### ISSUE THREAD

**Issue by jvutukur** [angular/angular#30409]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
Angular7, Forms

### Is this a regression?

 
 Not Sure

### Description

 
ngNativeValidate recognizes if the value goes out of min, max range
but angular fails to identify that the TemplateDriven FormControl value is invalid

## 🔬 Minimal Reproduction

 
https://stackblitz.com/edit/angular-6-template-driven-form-validation-lr8e5w

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Angular Version:**7
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by kara** [comment]
@jvutukur We actually don't have support for `min` and `max` validation in template-driven forms yet.  We only have the validator functions for reactive forms. Adding support is tracked in this issue: https://github.com/angular/angular/issues/16352
