### ISSUE TITLE
docs - cli: change ng analytics to have link to stable instead of next

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#30407]
# 📚 Docs or angular.io bug report

### Description

 

The command help and reference page for `ng update` contains a hard-coded reference to `next.angular.io`: 

https://next.angular.io/cli/analytics

"Configures the gathering of Angular CLI usage metrics. See https://next.angular.io/cli/usage-analytics-gathering."

That reference needs to be changed **before the final RC build of the CLI** so that the cli help and the AIO command reference page go to `https:/angular.io/cli/usage-analytics-gathering`. 

**It's also possible that the cli itself has a link to `https://next.angular.io/analytics`, which will need to be changed to `https://angular.io/analytics`.

### What's the affected URL?**
 
See above

### Reproduction Steps**

See above

### Expected vs Actual Behavior**

See above

## 📷Screenshot

n/a

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by IgorMinar** [comment]
we can change all the urls in the code to point to https://v8.angular.io/* which currently redirects to next.angular.io/* (preserving the url path), and as soon as the release goes out it will point to angular.io/*
