### ISSUE TITLE
docs: Ivy programmatic usage

### ISSUE THREAD

**Issue by yannickl88** [angular/angular#30405]
# 📚 Docs or angular.io bug report

### Description

One of the key selling points of the new Ivy render is locality and that it make it easier to use for build tooling. I know this might be early, but the documentation could really use a (simple) example showing how to use the compiler from a JS context.

Some examples of what I mean can be found in other tooling:
 * LESS: http://lesscss.org/usage/#programmatic-usage
 * SASS: https://sass-lang.com/documentation/js-api
 * TypeScript: https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API
 * UglifyJs: https://github.com/mishoo/UglifyJS2#api-reference

Angular could really benefit from something like this.

## 🔥 Exception or Error
<pre><code>
</code></pre>

**Comment by yannickl88** [comment]
Also, if somebody has a working code example I could use as a basis I would be more than happy to create PR for the docs. I just having trouble finding my way around the code to make a start with this.

**Comment by pkozlowski-opensource** [comment]
We are still debating the APIs to make Angular + ivy more dynamic. We will document those as soon as APIs are designed / implemented. For now we don't want to commit to specific public APIs so it is too early for documentation.

I'm going to close this issue for now as there is nothing immediately actionable here.
