### ISSUE TITLE
aio: script instead of scripts

### ISSUE THREAD

**Issue by kbradl16** [angular/angular#30418]
# 📚 Docs or angular.io bug report

### Description
In the section for running typescript scripts to compile your code:

> "Finally, you should add some npm scripts in package.json to compile the TypeScript files to JavaScript (based on the tsconfig.json configuration file):
`"script": { "tsc": "tsc", "tsc:w": "tsc -w", ... "`

Should be `"scripts":  { "tsc": "tsc", "tsc:w": "tsc -w", ...`

### What's the affected URL?**
https://angular.io/guide/upgrade#phonecat-upgrade-tutorial

**Comment by gkalpak** [comment]
Good catch, @kbradl16 👍 
BTW, if you want to submit a fix, [this][1] is where you need to go :wink:

[1]: https://github.com/angular/angular/edit/master/aio/content/guide/upgrade.md?message=docs(upgrade)%3A%20fix%20typo%20in%20code%20snippet%20(script%20--%3E%20scripts)#L1061
