### ISSUE TITLE
Compiler error for local js module with .d.ts

### ISSUE THREAD

**Issue by e-cloud** [angular/angular#30412]
# 🐞 bug report

### Affected Package

@angular/compiler

### Is this a regression?

I dont know

### Description

For some reason, I have to use a local js module in angular/cli project.

For example, `dynamic-conf.js`

And I need to turn on typescript **strict** mode. So, I have to add a `dynamic-conf.d.ts` with correct types to let typescript know what the js module contains.

However, when i try to run `ng build -c production`, errors prompt(see below.)

I think it's kind of related to the angular compiler, which interprets the module incorrectly? I see `dynamic-conf.ts` in the output and there is not such file.

## 🔬 Minimal Reproduction

reproduction is available in the following branch and repo
https://github.com/e-cloud/demo-repo-for-various-issues/tree/angular-aot-problem

high priority files:
* https://github.com/e-cloud/demo-repo-for-various-issues/blob/angular-aot-problem/src/app/app.module.ts
* https://github.com/e-cloud/demo-repo-for-various-issues/blob/angular-aot-problem/src/environments/environment.ts

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/5255354/57566652-3afe1f00-7402-11e9-849f-be4bcd25076c.png)

<pre><code>
> ng build -c production

Date: 2019-05-11T07:15:59.755Z
Hash: 01bae3fcd1c3adea3c5c
Time: 4945ms
chunk {0} runtime.26209474bfa8dc87a77c.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} es2015-polyfills.c5dd28b362270c767b34.js (es2015-polyfills) 56.4 kB [initial] [rendered]
chunk {2} main.fa4681da67b0e16d34dc.js (main) 128 bytes [initial] [rendered]
chunk {3} polyfills.41559ea504b9f00b6dea.js (polyfills) 130 bytes [initial] [rendered]
chunk {4} styles.3ff695c00d717f2d2a11.css (styles) 0 bytes [initial] [rendered]

ERROR in src\app\app.module.ts(12,25): Error during template compile of 'AppModule'
  Only initialized variables and constants can be referenced in decorators because the value of this va
riable is needed by the template compiler in 'environment'
    'environment' references 'URL' at src\environments\environment.ts(3,28)
      'URL' is not initialized at src\environments\dynamic-conf\dynamic-conf.ts(1,14).

npm ERR! code ELIFECYCLE
npm ERR! errno 1

</code></pre>

## 🌍  Your Environment

**Angular Version: 7.2
<pre><code>
Angular CLI: 7.3.9
Node: 10.14.2
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**

**Comment by alxhub** [comment]
Instead of `useValue`, use `useFactory` with a function that returns the URL based on the ternary.

This is working as intended for the compiler, which is trying to statically understand `useValue` in order to write it out in the metadata.
