### ISSUE TITLE
Add markAllAsTouched and clear method to example doc

### ISSUE THREAD

**Issue by santoshyadavdev** [angular/angular#30439]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

FormArray has 2 new methods markAllAsTouched and clear add both to example to showcase the functionality.

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by AndrewKushnir** [comment]
Closing this issue based on the https://github.com/angular/angular/pull/30655#issuecomment-736938526. I believe we should look at individual function descriptions to see if there is anything missing. Let's create separate ticket(s) in case there are improvements to that functions (from docs perspective). Thank you.
