### ISSUE TITLE
Application is generating a chunk of my lazy load module with prefix default ~ .. even before its getting invoked

### ISSUE THREAD

**Issue by SAkhil95** [angular/angular#30431]
Hello Team,

I have implemented lazy-loading in my Angular Application (using CLI 7.3.4)

Its compiling successfully but when I route to a lazy-loaded module (say module1 path), its loading one more chunk which is actually other lazy loaded module (Module2) path.

Chunk Name: "http://localhost:4200/default~lazy-load-modules-module1-module1-module~lazy-load-modules-module2-mo~be6d77c5.js"

I am unable to understand why this default ~ is getting generated.

I have tried searching in my entire workspace if the module is mistakenly invoked anywhere using router.navigate, but I found none.

I am expecting to load modules only when one of its component is invoked.

**Comment by SAkhil95** [comment]
Hello,

I have tried doing prod build with namedChunks: true.

js files generated after prod build :

default~lazy-load-modules-module1-module1-module-ngfactory~lazy-load-modules-module2~f905bd40.e57cb63c897b03f07599.js

default~lazy-load-modules-module2-module2-module-ngfactory~lazy-load-modules-m~e4585478.7b99f3d4bf5e27b58bfd.js

and 3 seperate js files for 3 seperate modules.

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-issue-repro2).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
