### ISSUE TITLE
 Routing parameters 'state' does not exist in type 'NavigationExtras'

### ISSUE THREAD

**Issue by MaryCooperGD** [angular/angular#30433]
I want to pass data to another page using Router and NavigationExtras. After reading the [documentation](https://angular.io/api/router/NavigationExtras#state) I've done this:

```
const navParams:NavigationExtras = {state: {functionalityId:'my id'}};
this.router.navigate(['processes'], navParams);
```

But I have the following error:

> Type '{ state: { functionalityId: string; }; }' is not assignable to type 'NavigationExtras'.
>   Object literal may only specify known properties, and 'state' does not exist in type 'NavigationExtras'.

As if "state" does not exist in NavigationExtras interface. What's wrong?

**Comment by trotyl** [comment]
Please fill the [issue template](https://github.com/angular/angular/blob/master/.github/ISSUE_TEMPLATE/1-bug-report.md) and you'll see there's a `version` field required:

```md
## 🌍  Your Environment

**Angular Version:**
<pre><code>
<!-- run `ng version` and paste output below -->
<!-- ✍️-->

</code></pre>
```

And you'll also need to provide a minimal reproduction. By doing so you can understand this is not an issue before even submit it.

**Comment by jasonaden** [comment]
Closing based on the above recommendation.
