### ISSUE TITLE
Ivy: expose component Injector for HOC

### ISSUE THREAD

**Issue by itayod** [angular/angular#30430]
# 🚀 feature request

### Relevant Package
@angular/core

### Description
I have tried to implement a **High Order Component** following @vsavkin [blog](https://blog.nrwl.io/metaprogramming-higher-order-components-and-mixins-with-angular-ivy-75748fcbc310)

While  doing so, I tried access to the component's injector in order to use some services,
but couldn't find any way to do it. 

### Describe the solution you'd like
I think a good solution might be exposing the component's injector by maybe passing it as a parameter to the component's factory function, or alternatively provide a `getInjector` function
that returns the component's injector.

### Describe alternatives you've considered
The only work around I have found is to inject the `Injector` in the component's constructor and get it after the component's instance is created.

Angular version: `8.0.0-rc.3`
link to my code: https://github.com/itayod/ngx-lazy-components/blob/master/src/app/lazy-components.ts

I will happily assist with a pr but I guess It will require some help 😄

**Comment by alxhub** [comment]
I offer no opinion on whether or not this is a good idea. But this is what `inject` is for in factory functions. If you look at a component compiled under Ivy:

```typescript
@Component({...})
export class FooCmp {
  constructor(private a: A, private b: B) {}
}
```

The factory function will look like:

```typescript
  factory: function FooCmp_Factory(t) { return new (t || FooCmp)(inject(A), inject(B)); }
```

So in your example, you can get ahold of the injector just by calling `inject(INJECTOR)`:

```typescript
import {inject, INJECTOR} from '@angular/core';

cmpType.ngComponentDef.factory = (...args) => {
  const cmp: any = originalFactory(...args);
      // TODO: check if there is an option to get the injector without forcing the user to inject it,
      //  or if there will be a future api.
      const injector = inject(INJECTOR);
```

**Comment by itayod** [comment]
Hi, @alxhub Thanks for your response!

I have tried to receive the injector the way suggested, but It didn't work for me 😞 
Unexpectedly this is the error I am getting:

![injector error](https://user-images.githubusercontent.com/6719615/57754346-e22ad100-76f6-11e9-9d66-bc9a8d44c1b8.PNG)

I have also tried to change the `arrow function` to `function` in order to keep the context, but without any luck.

**Comment by alxhub** [comment]
@itayod ahhh. Sorry, the Ivy runtime is a fast moving target currently. I believe because it's an `ngComponentDef` factory, you need to call `directiveInject` (probably the privately exported one) instead of `inject`.

I'm going to close this issue as there's nothing really actionable for us here at the moment, but we can continue discussing this.
