### ISSUE TITLE
add svg template example

### ISSUE THREAD

**Issue by santoshyadav198613** [angular/angular#30441]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

We support SVG as a valid template, update the template section with one example.

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by kapunahelewong** [comment]
Hi @santoshyadav198613, could you elaborate? If what you have in mind is something I can do, I'd be happy to add to one of my Template Syntax PRs.

**Comment by santoshyadav198613** [comment]
We have examples to create component and as we now support svg template can we add an example on how to use it in doc.

**Comment by ericmartinezr** [comment]
I think he means this https://levelup.gitconnected.com/using-svg-files-as-component-templates-with-angular-cli-ea58fe79b6c1

**Comment by santoshyadav198613** [comment]
Hi @ericmartinezr, thanks. @kapunahelewong if it comes into one of the PR it's ok, otherwise I was going to open a PR soon.

**Comment by kapunahelewong** [comment]
Thanks @ericmartinezr :) @santoshyadav198613 a PR from you would be great! Before you get started on it though, let me run it by the docs team and devrel to keep efforts efficient.

**Comment by santoshyadav198613** [comment]
Thanks, @kapunahelewong .

**Comment by kapunahelewong** [comment]
@santoshyadav198613, everyone's supportive of adding this to the docs! 🎉

@oocx added this to the CLI and wrote the article that @ericmartinezr referenced, and has agreed to be contact on the topic should we have any questions (thank you, @oocx!). 

Feel free to tag me here or in the PR when/if you have any questions. Thanks for this, @santoshyadav198613!!

**Comment by oocx** [comment]
That reminds me that I still need to finish that chart example that I promised to write in my article... :)

@santoshyadav198613 Let me know if you have any questions

**Comment by santoshyadav198613** [comment]
Sure @oocx  thanks.

**Comment by santoshyadav198613** [comment]
HI @kapunahelewong and @oocx , Should I add the example as well.

**Comment by santoshyadav198613** [comment]
Hi @kapunahelewong ,
I have added the code, had to add SVG as inline HTML as the <code-example> does not support svg.

**Comment by Splaktar** [comment]
@santoshyadav198613 where exactly did you run into that limitation of the docs? Was there [here](https://github.com/angular/angular/pull/30559/files#diff-fe1da8d4b293de490dd0cef57e6d036bR2038)?

**Comment by santoshyadav198613** [comment]
Hi @Splaktar ,the code-example component which we have can not render svg. So I had to wrap it as HTML in doc. Will take care of Comments.

**Comment by Splaktar** [comment]
Ah yes, triple backticks is the correct way to do that. 👍
