### ISSUE TITLE
Configure Timing of ViewChild/ContentChild queries

### ISSUE THREAD

**Issue by santoshyadav198613** [angular/angular#30440]
# 📚 Docs or angular.io bug report

### Description

Add timing parameter added in example.
 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by kapunahelewong** [comment]
Hi again @santoshyadav198613! Were you thinking of a PR for this one? (Because that would be amazing! hehe)

**Comment by santoshyadav198613** [comment]
Yes @kapunahelewong and 30439 too.

**Comment by kapunahelewong** [comment]
Thank you @santoshyadav198613

**Comment by santoshyadav198613** [comment]
Hi @kapunahelewong , is this state community new tag, never saw it earlier?

**Comment by kapunahelewong** [comment]
I think it's relatively new @santoshyadav198613 - maybe within the last 6 months or so, but I just learned of it. :)

**Comment by ahmadmu** [comment]
@kapunahelewong I'm getting multiple errors in rc.5 expecting ViewChild to have 2 parameters instead of one, and: 

`An argument for 'opts' was not provided.`

Is this already known/noted or/and expected, or should I open an issue for it?

**Comment by trotyl** [comment]
@ahmadmu Please take a look at CHANGELOG:

https://github.com/angular/angular/blob/master/CHANGELOG.md#800-rc5-2019-05-24

**Comment by ahmadmu** [comment]
@trotyl oh I missed that one, thanks!

**Comment by santoshyadav198613** [comment]
Closing this as docs are updated with the static flag.
