### ISSUE TITLE
Reversing views in the same ViewContainerRef yields wrong order

### ISSUE THREAD

**Issue by Shijir** [angular/angular#30454]
# 🐞 bug report

### Affected Package
 @angular/core

### Description

Initially, I insert embedded views into ViewContainerRef. The embedded views are created out of the following templates: 

```
<ng-template reorderableBox>
    <div class="box" style="background: blue"></div>
</ng-template>
<ng-template reorderableBox>
    <div class="box" style="background: orange"></div>
</ng-template>
<ng-template reorderableBox>
    <div class="box" style="background: green"></div>
</ng-template>
```

Then, I detach all of them from the view container and re-insert them back in reverse order. But, the issue is that they are being displayed in the wrong reverse order:

_Initial order: blue, orange, green_

_Reverse order (expected): green, orange, blue_

_Actual result: green, blue, orange_

Notes:

- I tried reversing a different number of embedded views, but the wrong reverse order sill persists. 

- I tried re-inserting views in different order indexes, and they work fine until the order becomes the reversed version of the initial order.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/reverse-view-insertion-fail

**Angular Version:**
v7.2.0

**Comment by trotyl** [comment]
It's expected behavior, the problem it's that you're inserting to a position that doesn't yet exist.

The operations in your example are:
+ Clear the ViewContainer; (length become 0)
+ Insert blue view to index 2; (**length is 0, blue view index becomes 0**)
+ Insert orange view to index 1; (length is 1, orange view index becomes 1)
+ Insert green view to index 0; (length is 2, green view index becomes 0)

The view container can not be sparse, so you need to make sure insert to a valid position.

**Comment by Shijir** [comment]
@trotyl but then what would be the proper way to change positions without detaching existing views first? Another solution I could think of was `ViewContainerRef.move`.  But that also has problems as well: https://stackblitz.com/edit/clarity-template-shuffle-by-moving
This example shows that views are moved to the wrong indexes.

**Comment by trotyl** [comment]
@Shijir To compute the exact minimal position changes between two sequence, you need to diff them, Angular itself provides the [`IterableDiffer`](https://angular.io/api/core/IterableDiffer) utility, but you can also apply your own algorithm based on any other framework/library.

If you don't mind performance, you can just insert from first one to last one, which is guaranteed to be safe:

https://stackblitz.com/edit/reverse-view-insertion-fail-mfco2r

**Comment by Shijir** [comment]
@trotyl haha yes I am currently using exactly the same solution you provided in your stackblitz. I just thought (or probably hoped) that `ViewContainerRef.move(view, index)` or `ViewContainerRef.insert(view, index)` in a more intuitive and robust way out of the box. I do appreciate your help and suggestions here. Thank you!

**Comment by trotyl** [comment]
@Shijir I agree there should be an explicit error when invalid index being used.

**Comment by alxhub** [comment]
Closing as @trotyl's analysis is correct (though I too agree we should have a much more explicit error - and [Ivy actually does](https://github.com/angular/angular/blob/bb8a18e72d7fc5b80a9a63a2366467017a0e9209/packages/core/src/render3/view_engine_compatibility.ts#L299)!).
