### ISSUE TITLE
Experimental Ivy - routerLink does not trigger navigation event

### ISSUE THREAD

**Issue by faustotnc** [angular/angular#30459]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?

I did not try experimental-ivy in previous versions

### Description
The routerLink directive does not work after creating a new Angular project with the experimental-ivy and routing flags on. I created the project using the angular cli and created three components and added them to app-routing.module.ts. Lastly, I added an anchor tag to the app.component.ts with routerLink="/about", but the link does not work when previewed on the browser.

**Behavior**
- When clicking on the link, the browser does not reload nor does it navigate.
- When hovering the link, the browser shows the tooltip on the bottom-left corner, but it shows the current URL rather than the URL I specified in routerLink.
- Inspecting the HTML, the href attribute shows the current url, while the routerLink attribute shows the URL I specified.
- The router-outlet works fine as it loads the components based on their URL correctly. However, it does not update when I click on a link with the routerLink directive.
- After setting 'enableTracing' to true inside app-routing.module.ts, when I click on the link the console does not log any navigation events.

## 🔬 Minimal Reproduction
The project was created with the following command:
`ng new FaustoWeb2019 --experimental-ivy true --prefix fausto --routing true --skipt-git true --skip-tests true --style scss`

Git repository with the generated (faulty) project:
[https://github.com/faustotnc/ngRouterLinkNotWorking](https://github.com/faustotnc/ngRouterLinkNotWorking)

Modified files:
- src/app/app.module.ts
- src/app/app.component.html
- src/app/app-routing.module.ts
- src/app/components/

## 🔥 Exception or Error
No console or CLI errors

## 🌍  Your Environment

**Angular Version:**
<pre><code>7.2.15</code></pre>
**Angular CLI Version:**
<pre><code>7.3.9</code></pre>

**Comment by faustotnc** [comment]
I decided to create a test app following the exact same steps, except that this time the --experimental-ivy flag was not set and routerLink now works just fine.

With this, we now know that the root cause of the problem is the experimental-ivy renderer.

**Comment by maktarsis** [comment]
Yeap. I checked that behavior on both projects.

I've debugged routerLink and discovered that routerLink's setter doesn't invoke function
That's why it doesn't set any commands. After that, it sets empty href (based on empty commands)

**Comment by alexzuza** [comment]
The reason here is that ngcc of version 7.2.15 doesn't properly recognize routerLink input property since it's a setter.
Looks like it has been already covered by https://github.com/angular/angular/pull/28357 @JoostK

Can you please update angular and @angular/cli version to the latest and see if it works?
Btw, I already tested it on the latest versions and routing works well.

**Comment by maktarsis** [comment]
Yeah, correct.
After update angular to the latest version (rc.4) all works fine

I think we can close it.

**Comment by faustotnc** [comment]
Awesome! Version 8.0.0-rc.4 does solve the problem.

Thanks for the help.

**Comment by gaurav-chandra** [comment]
It is still a problem in angular 8.2.5 with ivy enabled. Till the time I do not add href, routerLink does not work.
