### ISSUE TITLE
Custom validation function cannot get dynamic data(get data only firsth time)

### ISSUE THREAD

**Issue by emilalsgndr** [angular/angular#30476]
I want pass dynamic(email existing check on backend) data to custom form validation function. after get form submit response i want pass email ex(before submit) value . but it not get changed value/
![Screen Shot 2019-05-15 at 2 57 08 PM](https://user-images.githubusercontent.com/36768068/57770910-6d6d8c00-7722-11e9-91a1-2828723a1190.png)

![Screen Shot 2019-05-15 at 2 57 28 PM](https://user-images.githubusercontent.com/36768068/57771130-ebca2e00-7722-11e9-81ca-4b015c259f9f.png)

# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.3.8
Node: 10.15.3
OS: darwin x64
Angular: 7.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**

**Comment by mlc-mlapis** [comment]
@emilalsgndr ... as usual, https://stackblitz.com simple reproduction example is required.

**Comment by itayod** [comment]
@emilalsgndr if you'r trying to check if the email is already exists, I recommend you to take a look at [async validators](https://angular.io/guide/form-validation#async-validation).

I think it could fit you'r case better.

**Comment by mlc-mlapis** [comment]
@emilalsgndr ... sure, you are calling an async code you have to use also async validator.

Btw ... this is not a support forum ... and your case is not an issue. Use Gitter or SO channels instead.
