### ISSUE TITLE
ViewChild options are no described

### ISSUE THREAD

**Issue by djleonskennedy** [angular/angular#30473]
# 📚 Docs

### Description
We've seen code `@ViewChild(TemplateRef, {static: true})` where can we find options object interface in docs?

### What's the affected URL?**
https://angular.io/api/core/ViewChild

### Reproduction Steps**

Please see: https://angular.io/api/core/ViewChild

### Expected vs Actual Behavior**

There is no information about additional options of ViewChild except `read` prop

## 📷Screenshot

N/A

## 🔥 Exception or Error
N/A

### Browser info
N/A

### Anything else relevant?
N/A

**Comment by santoshyadav198613** [comment]
https://github.com/angular/angular/issues/30440

is already open to adding it to the doc.

**Comment by djleonskennedy** [comment]
@santoshyadav198613 thank you
