### ISSUE TITLE
ng g c with selection of app.module.ts

### ISSUE THREAD

**Issue by madks13** [angular/angular#30487]
# 🚀 feature request

angular 7+

### Description
Hello, my current app folder looks like the following :
 - app
 - - _app-base
 - - - app.module.ts
 - - - app-routing.module.ts
 - - - app-component
 - - - - app.component.html
 - - - - app.component.sass
 - - - - app.component.ts
 - - _components
 - - - administration (omitting the obvious files)
 - - - session (and many others)
 - - _data
 - - _guards
 - - _helpers (so forth and so on)

The problem i'm encountering is that since my app.module.ts isn't at the root of the app folder, i need to use the --skipImport when using ng g c....which can be annoying and time consuming when creating components, services and other parts.

### Describe the solution you'd like

Is it possible to add a setting to say where the main module of the app is?
Or, if not, at least add a command line option to give the path to it?

### Describe alternatives you've considered

As said, currently i have to use the --skipImport, but it slows down the creation of the parts quite a bit, since i use a GUI for those tasks, which are much faster than command line commands.

I tried using the command lines but since i have depp folder paths, it takes much longer trough the command line compared to the GUI.

**Comment by ericmartinezr** [comment]
Would you mind opening this feature request in angular-cli's repo https://github.com/angular/angular-cli ? :+1:

**Comment by madks13** [comment]
Hmm, so it is a cli issue...ok then.
