### ISSUE TITLE
The tooltip of 'Events' link in the footer of angular.io is wrong

### ISSUE THREAD

**Issue by alator21** [angular/angular#30480]
# 📚 Docs or angular.io bug report

### Description

 Events tooltip in the footer of angular.io is wrong.

### What's the affected URL?**
 All subpages of https://angular.io/

### Reproduction Steps**

 Just hover your mouse over the 'Events' link.

## Expected:
A message about Angular events.

## Actual:
"Post issues and suggestions on GitHub"

**Comment by Alayode** [comment]
Seems like there is a file at https://angular.io/generated/navigation.json  that is fetch from the navigationService in which is causing the error. I am not sure how I am able to get this file.

**Comment by gkalpak** [comment]
The original file is [aio/content/navigation.json][1].
This issue will be fixed by #30643, btw.

[1]: https://github.com/angular/angular/blob/8e8c1ad47/aio/content/navigation.json

**Comment by brandonroberts** [comment]
Fixed via #30643
