### ISSUE TITLE
Define common alias type for common locales type.

### ISSUE THREAD

**Issue by Domvel** [angular/angular#30506]
```ts
import localeEn from '@angular/common/locales/en';
import localeDe from '@angular/common/locales/de';
import localeIt from '@angular/common/locales/it';
import localeEs from '@angular/common/locales/es';
import localeFr from '@angular/common/locales/fr';
import localePt from '@angular/common/locales/pt';
import localeRu from '@angular/common/locales/ru';
```
Each of these objects have an own custom type. A very long and ugly complex type. Like:

*en.d.ts*
```ts
declare const _default: ({} | undefined)[];
```

*de.d.ts*
```ts
declare function plural(n: number): number;
declare const _default: (string | number | (string[] | undefined)[] | number[] | (string | undefined)[] | typeof plural | {
    'ATS': string[];
    'AUD': string[];
    'BGM': string[];
    'BGO': string[];
    'CUC': (string | undefined)[];
    'DEM': string[];
    'FKP': (string | undefined)[];
    'GNF': (string | undefined)[];
    'KMF': (string | undefined)[];
    'RON': (string | undefined)[];
    'RWF': (string | undefined)[];
    'SYP': never[];
    'THB': string[];
    'TWD': string[];
    'ZMW': (string | undefined)[];
})[];
export default _default;
```

In my opinion that should be improved by defining a common type for a Angular `Locate`.

Example:
```ts
export type AngularLocale = ({} | undefined)[];
```

you can additional create separated types for each language. But the developer who is using this library should not write miles of code for a type.

Especially on strict TypeScript settings like `noImplicitAny` and strict-mode for high Quality and CleanCode this is a bit ugly. (Prevent `any` type. Easy but, don't.)

Angular Version (tested):  `5.2.10`, `7.2.1` and may still exist in the latest `7.2.15` (sure that).
Code here is from `7.2.1`.

**Comment by ocombe** [comment]
Those types are auto generated by typescript, a developer who is using this library shouldn't need to write this kind of types. If you need access to the locale data, you can use the api functions for that: https://angular.io/api?query=getlocale
I'm not sure why you would need to write those types manually?

**Comment by Domvel** [comment]
@ocombe It's just a strict typing issue for clean code. We have to set the type on all arguments and return value. And avoid `any` type. We built a wrapper and returns the `Locale` object. I wanted a specific type for this. But in this case the types are very different from all. There is a common type (see my initial post). We could use it. It's better if Angular has such a type. A custom type (alias) from my side will cause some issues if Angular changes something. ... Anyway, it's not very important. I can live with that. Just suggested / opened a discussion. - Closed because no need at this moment in my case. Reopen if you think, this should be implemented.
