### ISSUE TITLE
Angular service worker state (/ngsw/state) doesn't work if context is not /

### ISSUE THREAD

**Issue by autozoom** [angular/angular#30505]
# 🐞 bug report

### Affected Package
@angular/pwa
@angular/service-worker

### Description
Service worker state is not viewable if the app context is not /

## 🔬 Minimal Reproduction
* build the angular PWA with `--base-href="/myfolder/"`
* deploy the app to the myfolder subfolder
* check that https://server/myfolder/ngsw/state does not work

For example:
* go to [https://www.bassanofamiglia.it/ng-garsiawe/portalecittadino](url) to see the app
* check that [https://www.bassanofamiglia.it/ng-garsiawe/portalecittadino/ngsw/state](url) doesn't work

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.8
Node: 10.15.0
OS: win32 x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.12.4
@angular-devkit/build-angular      0.12.4
@angular-devkit/build-ng-packagr   0.12.4
@angular-devkit/build-optimizer    0.12.4
@angular-devkit/build-webpack      0.12.4
@angular-devkit/core               7.2.4
@angular-devkit/schematics         7.3.8
@angular/cdk                       7.3.7
@angular/cli                       7.3.8
@angular/material                  7.3.7
@angular/pwa                       0.12.4
@angular/service-worker            7.2.15
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.2.4
@schematics/angular                7.3.8
@schematics/update                 0.13.8
ng-packagr                         4.7.1
rxjs                               6.4.0
typescript                         3.2.4
webpack                            4.28.4

</code></pre>

this comment to another issue is relevant: https://github.com/angular/angular/issues/30351#issuecomment-492754624

**Comment by gkalpak** [comment]
This is related to #25055. The code posted in https://github.com/angular/angular/issues/25055#issuecomment-408073162 should fix this as well (see [L1797][1] and [L1882][2] in the updated code).

@autozoom, if you (or anyone else) is interested in working on this, I'd be happy to help.
(You would basically take the fix from https://github.com/angular/angular/issues/25055#issuecomment-408073162, put it in a PR and add tests.)

[1]: https://gist.github.com/gkalpak/3d1b73f6c693df2d8cdcbabbed57d987#file-ngsw-worker-js-L1797
[2]: https://gist.github.com/gkalpak/3d1b73f6c693df2d8cdcbabbed57d987#file-ngsw-worker-js-L1882

**Comment by Jun711** [comment]
@autozoom 
Did you get the following error when you tried to access `ngsw/state` when building PWA using `--base-href="/myfolder/"`
 
```
core.js:15713 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'ngsw/state'
Error: Cannot match any routes. URL Segment: 'ngsw/state'
```
https://github.com/angular/angular/issues/29944

@gkalpak 
Do you have any update regarding this issue?

**Comment by gkalpak** [comment]
@Jun711, no much of an update, I'm afraid.

Someone started a PR (#31082) based on the code I posted in https://github.com/angular/angular/issues/25055#issuecomment-408073162 (which would solve the issue), but couldn't see it through, then a bunch of people offered to pick it up, but nobody did :grin:

If nobody beats me to it, I will pick it up at some point (after Ivy is released) 🤷‍♂
