### ISSUE TITLE
Ivy Template Compiler misinterprets someExternalServiceFunction(this) when surrounded by *ngIf

### ISSUE THREAD

**Issue by speige** [angular/angular#30507]
# 🐞 bug report

### Affected Package
Ivy Template Compiler

### Is this a regression?

Kindof. Not version specific, however it's dependent on which renderer is enabled (legacy/ivy).
tsconfig
```
  "angularCompilerOptions": {
    "enableIvy": true // bug
    "enableIvy": false // no bug
  }
```

### Description

Using "this" variable in template to access entire Component (as opposed to single property) can be interpreted wrong if surrounded by an *ngIf. (template compiler uses wrong context variable)

## 🔬 Minimal Reproduction
I can't use StackBlitz because it doesn't allow changing tsconfig.app.json

Minimal repro at: https://github.com/speige/ivy-this-context-bug

Swap enableIvy between true/false in tsconfig.app.json to see the regression/breakingChange.

This is a blank starting project, the only relevant code is here:
app.component.html
```
<div *ngIf="true">
	<span>With NgIf, Stringify(this) => </span>
	{{Stringify(this)}}
</div>

<div>
	<span>Without NgIf, Stringify(this) => </span>
	{{Stringify(this)}}
</div>

<br /><br />

<div *ngIf="true">
	<span>With NgIf, Stringify(this.Property) => </span>
	{{Stringify(this.Property)}}
</div>

<div>
	<span>Without NgIf, Stringify(this.Property) => </span>
	{{Stringify(this.Property)}}
</div>
```

app.component.ts
```
export class AppComponent {
  public Property = { Key: 'value' };

  public Stringify(object: any) : string {
	  return JSON.stringify(Object.getOwnPropertyNames(object));
  }
}
```

## 🔥 Exception or Error
Working Screenshot (enableIvy: false)
![image](https://user-images.githubusercontent.com/2002030/57843528-ab52ca80-778b-11e9-9741-a96eedd03368.png)

Broken Screenshot (enableIvy: true)
![image](https://user-images.githubusercontent.com/2002030/57843508-a130cc00-778b-11e9-81ad-80d9616ebad6.png)

When comparing the images, the addition of property "ngContext" is not a problem because it's just ivy internals. However, the ["$implicit", "ngIf"] is a problem because it's the completely wrong variable. If you debug the code you'll see it's the context object for the surrounding *ngIf.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0-rc.4
Node: 10.15.0
OS: win32 x64
Angular: 8.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.4
@angular-devkit/build-angular     0.800.0-rc.4
@angular-devkit/build-optimizer   0.800.0-rc.4
@angular-devkit/build-webpack     0.800.0-rc.4
@angular-devkit/core              8.0.0-rc.4
@angular-devkit/schematics        8.0.0-rc.4
@ngtools/webpack                  8.0.0-rc.4
@schematics/angular               8.0.0-rc.4
@schematics/update                0.800.0-rc.4
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**
This is probably an extremely rare use case & is possibly a code smell. However, my code was using it. It was easy to find a temporary workaround once the root cause was diagnosed.

My use case was I had a shared service with utility functions that needed an instance of a Component to work on. Similar to a BaseComponent or RootScope. The passed in reference was a weird context object instead of a Component. Was working before the ivy upgrade.

**Comment by alexzuza** [comment]
> However, the ["$implicit", "ngIf"] is a problem because it's the completely wrong variable

I would say that now it points to the exactly value it should be pointed before.

**Comment by trotyl** [comment]
> I would say that now it points to the exactly value it should be pointed before.

@alexzuza That doesn't seem reasonable, say that you need `$any(this)` to skip type-checking:

```html
{{ $any(this).foo }}
<ng-template>
  {{ $any(this).foo }}
</ng-template>
```

Or one need to bind this when passing a method:

```html
<p *ngFor="let item of items trackBy trackById.bind(this)">
<ng-template>
  <p *ngFor="let item of items trackBy trackById.bind(this)">
</ng-template>
```

All of them are valid use case and should not be broken by nesting in embedded views.

The general design of `<ng-template>` is that anything isn't explicit declared by `let-name` is resolved on component, `this` shouldn't make any difference. But I agree there should be a way to make access to `<ng-template>` context available per https://github.com/angular/angular/issues/22323.

**Comment by alexzuza** [comment]
@trotyl Thank you for your input.

I wouldn't use `bind` in template though but rather instance arrow function or bind in constructor for such cases.

I like your feature request.
I remember how I used $context and $root when worked with knockout https://knockoutjs.com/documentation/binding-context.html

**Comment by devversion** [comment]
PR that fixes this has been submitted. See #30897
