### ISSUE TITLE
Dynamically created component model is not being reflected in the template on change

### ISSUE THREAD

**Issue by azimsodikov** [angular/angular#30519]
# 🐞 bug report

### Affected Package

 The issue is caused by package 'not sure'

### Is this a regression?

 No

### Description

 Dynamically created component model is not being bind to the view on model change. Reproduced the issue in below stackblitz project.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-tyhfku

## 🌍  Your Environment

**Angular Version:**
<pre>

@angular/common7.2.5
@angular/compiler7.2.5
@angular/core7.2.5
@angular/forms7.2.5
@angular/platform-browser7.2.5
@angular/platform-browser-dynamic7.2.5
@angular/router7.2.5
core-js2.6.5
rxjs6.4.0
zone.js0.8.29
<code>

</code></pre>

**Anything else relevant?**

**Comment by mlc-mlapis** [comment]
@azimsodikov ... you have to process the CD by your own logic and code for dynamically created components ... it's not an issue, it's by design.

**Comment by azimsodikov** [comment]
@mlc-mlapis can you please elaborate on 'process CD by your own logic', what does it mean in this context?

**Comment by mlc-mlapis** [comment]
@azimsodikov ... ah, I missed that. I apologize.
... hmm, the problem is that the emits don't invoke subscriptions ... as you can see if `console.log('... CD runs');`  is added into.

There is something wrong with the observable logic and not with CD.
```
ngOnInit() {
    // on each new value emitted restore the state to default
    this.item$.subscribe(() => {
      this.config = SECTION_DEFAULT_STATE;
      this.cd.detectChanges();
      console.log('... CD runs');
    });
  }
```

**Comment by alexzuza** [comment]
@azimsodikov 
I suspect you're expecting that after you changed the `active` property by clicking on the line inside `app-section` component and then clicked on the `Restore State` button it should revert your primitive value to the default value, right?

The first we can try is to to remove dynamic loading
https://stackblitz.com/edit/angular-zsphvy?file=src%2Fapp%2Fsection.component.ts

As we can the dynamic component is not a problem here.

Now, let's think when ngOnChanges should be called.

It should be called when Angular (re)sets data-bound input properties.

parent component

```
const config= { foo: false };

<app-section [active]="config.foo"></app-section>
```

child component

```
@Component({
  selector: 'app-section',
  template: `<h1 (click)="active = !active" >click me to change state</h1>`,
})
export class SectionComponent implements OnChanges  {
  @Input() active: boolean;

  ngOnChanges() { 
    /* no changes */
    console.log(this.active);
  }
}


```
- When does Angular update an input property?
- When there is a change or in other words when view.oldValue is not identical to current value.



The first time the ngOnChanges is called is when we set default value so it changes from undefined to false.

**Comment by mlc-mlapis** [comment]
... ahh, so it's again the same story - the mutation of inputs. I missed it ... was too fast.

**Comment by azimsodikov** [comment]
@alexzuza correct! that's what I expect to happen when I click `restore state` button. Let's say 
when `ngOnChanges()` 
`AppSectionInstance.active = false;`
`view.oldValue = false;`
but as soon as config is bind, shouldn't `config.active = true` update `AppSectionInstance.active` to true?

**Comment by alexzuza** [comment]
@azimsodikov No, it should unless you use two-way binding

**Comment by alexzuza** [comment]
No, it shouldn't since config.active = true and view.oldValue[i] is also true so component will never receive updated value.
What you can do it to use two-way binding and don't mutate state.
https://stackblitz.com/edit/angular-5qansx?file=src/app/hero.component.ts
