### ISSUE TITLE
Angular is not suitable choice for enterprise grade systems!

### ISSUE THREAD

**Issue by orlovskyjavaprofi** [angular/angular#30527]
This is some sort of rant, but here we go:
after many months experiencing and long consideration and thinking i decided to make following statement: Angular in field in small and middle size company's , i say implementing enterprise heavy solutions in Angular **is not comfortable and very slow**, even writing test in tdd style is complicated  and unstable. 
**I dont want to discourage people using Angular**, but if managers read this github and thinking about Angular thats it , think twice or trice before you switch to Angular , because it may well cost your more then you think or can imagine.
For my clients i would highly recommend to switch to Vue.Js and others lightweight  java script frameworks.

**Comment by mlc-mlapis** [comment]
@orlovskyjavaprofi ... to say such a conclusion without any hard facts is even more frustrating. What do you think that those people should do? Blindly believe you?

**Comment by Zaljin** [comment]
@orlovskyjavaprofi the issues board is not a place to create a blog post on your opinions. If you truly feel this way, then I recommend trying to support your argument in a different forum.

**Comment by orlovskyjavaprofi** [comment]
mlc-mlapis, well it depends on budget of the company and the will to do the "Angular way" and how well the programmers experienced with working with Angular, what i have observed that first two or three iterations of Angular development is always fast ,but  in the forth and fifth it slow down , but there always a pattern and my  most concern as external contractor is responsibility to maintain the quality of project code base and if my unit tests always break after each time you do the npm update or yarn update, then there no way to maintain the stability of code and the ability to extend the project "features" goes away. Reasonably to ask ,  well what the most company's do in such cases?
 Well if they believe and trust in Angular , they just try new version or maintain "old" and highly customized version of Angular (which is not recommended in any way). 
Personally i would like to recommend to Angular community to become more mature and put a lot of effort in the developing better testing features like, so that after each change of Angular versions you just need minor changes in your mocks.

**Comment by mlc-mlapis** [comment]
@orlovskyjavaprofi ... I probably understand what you are trying to say, but I also see that it's tough to imagine real cases which you are talking about for an average developer or a project manager. If you are talking about a typical situation as **unit tests always break after each time you do the npm update**, you certainly have some hard conditions and I can only guess what it is, but I also know that it's not a typical case.

**Comment by Splaktar** [comment]
@orlovskyjavaprofi if you missed the ng-conf keynote this year, you may be interested in hearing @IgorMinar's [talk here](https://youtu.be/O0xx5SvjmnU?t=1568). It covers some of the strengths and weaknesses of Angular, including extra large Enterprise applications. 

If you have some ideas or prototypes that you would like to share with how Angular can work better in large Angular applications, please write a blog post or series about them, give talks, and start sharing your knowledge.

That said, the issue tracker is not the place for ranting or venting. If you need enterprise grade support, then there are some really capable consulting companies out there who can help you like @jeffbcross' [nrwl](https://nrwl.io), [Rangle](https://Rangle.io), [Manfred Steyer](https://www.softwarearchitekt.at/), and many others.

I'm not sure where it was mentioned in the keynotes this year at ng-conf, but a couple of Enterprise companies were highlighted for their contributions to Angular. They made these contributions after they encountered certain issues or limitations. So rather than just venting, they helped make things better. One of them came up with the design for the new Ivy Renderer and is an opt-in preview in version 8.

If you need some help figuring out how to channel your negative energy, writing up a blog post that demonstrates the different approaches that your team took and what their pros and cons were is a good starting point. Then you can ask for input from the community and maybe they can offer some ideas that you can try, or they can confirm that they are seeing the same issues and you can both reach out to devrel@angular.io with your case studies.

**Comment by Splaktar** [comment]
> that after each change of Angular versions you just need minor changes in your mocks.

@orlovskyjavaprofi it would be helpful if you could provide more concrete examples of what issues you ran into with your tests and 
- What versions of Angular were involved?
- Are they Angular CLI projects?
- Did the teams use `ng update`?
- Are you using Jasmine/Karma or Jest or Cypress?
- Were the test failures related to UI or framework? If UI, which UI library?

**Comment by Splaktar** [comment]
@orlovskyjavaprofi oh and you may find [this blog post](https://medium.com/airfrance-klm/how-we-upgraded-a-website-with-half-a-billion-annual-users-to-angular-7-in-less-then-a-day-71de33a1108e) by AirFrance KLM to be helpful.

**Comment by orlovskyjavaprofi** [comment]
Splaktar Thank for your response, it's clear that some work should be done to make Angular more testable , because well demand of enterprise always growing and without good testing suits developers would spent most of their day to day worktime with updating and configure stuff and not writing enterprise important code. Personally i dont wont to involve into Angular internal development, this is not my responsibility. If a given framework cant satisfy my high quality standards i switch to another one , that simple and i develop my business logic to be a framework independent one. My only hope that you aware of such issues and plan to do something about.

**Comment by trotyl** [comment]
> My only hope that you aware of such issues and plan to do something about.

Can you please share the issue links you encountered? No one demands you to make a PR to certain issue, but if you want to claim that you have problem during development, please provide some reference to let others understand what it is.

**Comment by orlovskyjavaprofi** [comment]
trotyl i would , but the code is very dependent on business logic of my client so i am not allowed to post it in public anywhere. I can only repeat what i have said early make Angular more testable and make that Mocks of Angular objects dont change they behavior and naming too much.

**Comment by trotyl** [comment]
@orlovskyjavaprofi 

> but the code is very dependent on business logic of my client so i am not allowed to post it in public anywhere.

Do you mean that you encountered an issue which isn't reported by anyone else, and you didn't report it either? That way I don't see how would you like to get help with.

Also, every issue required a minimal reproduction isolated from application, where only technical points stand.

**Comment by orlovskyjavaprofi** [comment]
trotyl , as said early my goal was to raise a concern, that Angular must be more testable and verifiable because in enterprise environment you have  a lot of legacy code which must be maintainable and in many cases you cant just switch to new version a framework because some sec or devops against it, so the procedure like you write you test suite to make sure that all of business logic working as expected and then the devops deploy  it into production, but what i have experienced as soon as new version of Angular is available the devops just update the server and in such cases too often the testsuite just breaks, because one of Angular mocks has been changed, this is not good for enterprise, so i basically propose , that if mocks must be changed they should have a version of Angular itselft, so that i can clearly pick the proper mock to the proper Angular version.

**Comment by mlc-mlapis** [comment]
@orlovskyjavaprofi ... what you write is generally understandable ... but still, one concrete example (even abstracted from corporate code) would help a lot to fully understand the cases you are working on and which creates such problems from your point of view.
