### ISSUE TITLE
Image inside <noscript> tag triggers request

### ISSUE THREAD

**Issue by chris13524** [angular/angular#30523]
# 🐞 bug report

### Description

When you have an `<img>` inside a `<noscript>`, the `<img>` still triggers a request.

My need for proper behavior of `<noscript>` is for lazy loading of images. In the event that JavaScript isn't available, you [put the image in a `<noscript>`](https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video/#javascript_availability) (which works in Angular using server-side rendering). However, if `<noscript>` still loads the image in Angular, that ruins the point of lazy loading.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-issue-repro2-r3jwsk

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 7.1.4
Node: 8.15.1
OS: linux x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
</code></pre>

**Comment by Airblader** [comment]
I don't quite get this: what's the point of rendering noscript through Angular? Angular requires JS, so with it disabled it would never render the template.

And I think the issue here is essentially not with Angular: the browser probably only applies the noscript logic on the initial DOM. If you put the noscript into the index.html, it probably works fine.

**Comment by chris13524** [comment]
@Airblader noscript is useful when you use server-side rendering or pre-rendering.

However, as you note this is not an issue with Angular since the below code triggers a network request even if it is never inserted into the DOM:

    var img = document.createElement("img");
    img.src = "https://via.placeholder.com/150";

As such, I do not believe there would be any reasonable way for Angular to workaround this. Unless there was some API that didn't trigger the network request until the element was inserted into the DOM?
