### ISSUE TITLE
next.angular.io quickstart npm install command installs wrong version in

### ISSUE THREAD

**Issue by caraya** [angular/angular#30549]
# 📚 Docs or angular.io bug report

### Description

In the quickstart page, the CLI installation command installs version 7 instead of the release candidate that matches the docs

## 🔬 Minimal Reproduction

```bash
npm install -g @angular/cli 
ng --version

Angular CLI: 7.3.9
Node: 10.15.3
OS: darwin x64
Angular:
```
### What's the affected URL?**

https://next.angular.io/guide/quickstart  

### Suggested change

To install the release candidate the command should be 

```bash
npm install -g @angular/cli@next
```

**Comment by chembu** [comment]
npm install should point to the latest stable release. `next` is reserved for upcoming major releases.
At the time this issue was raised, version 8 was not released. Hence the install didn't match the latest.

**Comment by caraya** [comment]
That is correct but this issue wasn't in the main documentation site but in the documentation for Version 8 before it was released.  

https://next.angular.io/ should always install the version that is the next one and should not point to a production build

**Comment by chembu** [comment]
Okay, I shall update the docs accordingly.

**Comment by rockument69** [comment]
@kapunahelewong and @jbogarthyde : I think this must now be obsolete, as I see the solution in both production and next versions.

**Comment by caraya** [comment]
I've closed the issue as it has indeed been resolved

**Comment by kapunahelewong** [comment]
Thank you, @caraya!
