### ISSUE TITLE
Bazel installs second copy of node_modules

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#30558]
Will be fixed in Bazel 0.26.0, due Tuesday or Wednesday. We should likely hold the Angular release on that if it's on-time.

Also needs https://github.com/bazelbuild/rules_nodejs/pull/704 to land.

Minimal changes needed in angular - this is mostly a tracking issue.

/cc @gregmagolan

**Comment by skreborn** [comment]
Bazel 0.26.0 was [released](https://github.com/bazelbuild/bazel/releases/tag/0.26.0) a week ago, and bazelbuild/rules_nodejs#704 has also landed. Can this be closed?

**Comment by IgorMinar** [comment]
closing as resolved: bazelbuild/rules_nodejs#704
