### ISSUE TITLE
incorrect command for webWorker

### ISSUE THREAD

**Issue by santoshyadav198613** [angular/angular#30554]
# 📚 Docs or angular.io bug report

### Description
You can add a web worker anywhere in your application. If the file that contains your expensive computation is src/app/app.component.ts, you can add a Web Worker using You can add a web worker anywhere in your application. If the file that contains your expensive computation is src/app/app.component.ts, you can add a Web Worker using ng generate web-worker app..

it should be ng generate webWorker app

 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by mgechev** [comment]
I believe: `ng generate webWorker app` is equivalent to `ng generate web-worker app`.

**Comment by santoshyadav198613** [comment]
Yes @mgechev , it as an alias but if we see other alias names we don't follow this pattern.

**Comment by santoshyadav198613** [comment]
closed by https://github.com/angular/angular-cli/pull/14526
