### ISSUE TITLE
Remove normalizeBlank from Dart output

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#3055]
It turns `null` to `null`, which is not very useful functionality and it also destroys types.

## Proposal

Similar to compile-time type substitution (e.g. `Promise` to `Future`) we should be able to substitute functions, in the `normalizeBlank` case we'd substitute it with empty string. It's ok to leave parens (unless it's easy to clean them up too). So, this:

```
var a = normalizeBlank(foo);
```

becomes this:

```
var a = (foo);
```

**Comment by mprobst** [comment]
Should this be a bug in ts2dart?

Also: it should be very easy for you to add this, see the `callHandlers` map in `facade_converter.ts`. Maybe take a stab at this?

**Comment by yjbanov** [comment]
I logged it here because:

- `normalizeBlank` is angular-specific, so I thought it would have to be fixed in this repo
- it will show up on the team issues dashboard

I'll take a stab at ti.
