### ISSUE TITLE
Several HTTPS REST requests via HttpClientModule with one TLS session

### ISSUE THREAD

**Issue by akonze** [angular/angular#30564]
Hello,

I'm new to angular, and I have the following issue: 
I make several HTTPS rest requests via HttpClient object, which is used by dependency injection in different modules. Unfortunately a new TLS handshake is made with each request, which affects the performance. Unfortunately I can't find a way to reuse the current TLS session (context). In the following you can see how I execute the calls and which version of @angular/common/http I use:

`"@angular/common": "^7.2.11",`

`import { HttpClientModule } from '@angular/common/http;`

`import { HttpClient } from @angular/common/http;`

`@Injectable()`
`export class XService {`
    `constructor(private http: HttpClient) { }`
	
	
    httpOptions = this.getHeaders(username, password);
    this.http.get("https://" + domain + '/license_information ', httpOptions);`

**Comment by mlc-mlapis** [comment]
@akonze ... how you would do it? We are talking about a browser requests via XHR (AJAX) calls. Angular can't do anything to affect it. It's just a browser/server thing. The only thing you can do is to enable a web server for Persistent Connections (also known as keep-alive) and then a browser maybe uses already open connections. It depends on timing and other internal factors but you can't do anything more.

**Comment by akonze** [comment]
Hmm, I thought that in Angular/JavaScript I could somehow remember and reuse a context with the TLS configuration.

Is this really a browser/server thing? If I enter the HTTPS XHR requests directly in the browser it works fine. A TLS handshake is done at the beginning and then automatically the same TLS session is used for the following calls. Unfortunately this does not work with the calls from the Angular Web Frontend. That's why I think I have to do something there.

**Comment by mlc-mlapis** [comment]
@akonze ...what do you mean by `If I enter the HTTPS XHR requests directly in the browser it works fine.`? Do you mean that you enter the URL directly in the address bar? **Then it is not XHR AJAX request.** These two cases are totally different. You can't mix them.

**Comment by akonze** [comment]
Yes I meant enter the URL directly in the address bar. But you are right, the two cases are totally different.
Is the issue that there is no `Connection': 'Keep-Alive'` in the response from the server to the XHR request?

> HTTP/1.1 200 OK
> Content-encoding: gzip
> Date: Tue, 21 May 2019 08:05:15 GMT
> Content-type: application/vnd.qumate.v2+json;charset=utf-8
> Access-control-allow-origin: http://localhost:4200
> Vary: Accept-Encoding
> Access-control-allow-credentials: true
> Content-length: 291

Many thanks so far for your help.

**Comment by mlc-mlapis** [comment]
@akonze ... so close the issue and don't increase the number of opened ones.
