### ISSUE TITLE
How to extend default ng generate component to generate extra file

### ISSUE THREAD

**Issue by kostia-lev** [angular/angular#30560]
I need to generate additional stub-* file for each generated component for usage in during testing. How can I do that? 
I understand that I can create my own schematics by copying default one, buy can I avoid that and gracefully extend default one with additional command for generation an empty stub-* file?

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by kostia-lev** [comment]
https://stackoverflow.com/questions/56316093/how-to-extend-default-angular-schematics-ng-generate-component
