### ISSUE TITLE
[ERROR] Browserslist: caniuse-lite is outdated. Please run next command npm update caniuse-lite browserslist

### ISSUE THREAD

**Issue by 690284557** [angular/angular#30579]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
angular6
**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

i use mvn install pack spring boot+webpack+angular6 project ,but has a error
[ERROR] Browserslist: caniuse-lite is outdated. Please run next command npm update caniuse-lite browserslist
[ERROR] (node:26895) DeprecationWarning: Tapable.plugin is deprecated. Use new API on .hooks instead
[ERROR] Browserslist: caniuse-lite is outdated. Please run next command npm update caniuse-lite browserslist
how to Solve

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
