### ISSUE TITLE
first run of ng serve under Bazel takes a long time with no output

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#30574]
reported by @istiti

I reproduced on my windows laptop, even for a vanilla `ng new --collection=@angular/bazel` project, it takes longer than I waited (60sec?) with no output.

I suspect it's bazel-watcher watching too many files.

**Comment by alxhub** [comment]
Closing as obsolete - the Bazel builder and associated CLI functionality are deprecated and no longer supported.
