### ISSUE TITLE
Cannot reattach ActivatedRouteSnapshot with a different number of children

### ISSUE THREAD

**Issue by vahidvdn** [angular/angular#30588]
Here is my routing:

```typescript
const routes: Routes = [

    {
        path: "",
        redirectTo: "/tabs/default",
        pathMatch: "full"
    },
    {
        path: "tabs",
        loadChildren: "~/app/modules/tabs/tabs.module#TabsModule"
    },
    {
        path: "login",
        loadChildren: "~/app/modules/login/login.module#LoginModule"
    },
    {
        path: "register",
        loadChildren: "~/app/modules/register/register.module#RegisterModule"
    }

];
```

The scenario which leads to the error: First the app starts with tabs route, then I go to the login page, after that I go to register and then again I go to tabs page (and clean the history). After that if I go to login page again and get back to previous one (tabs page), the error occurs.

The error:

```
JS: Error: Cannot reattach ActivatedRouteSnapshot with a different number of children
JS:     at setFutureSnapshotsOfActivatedRoutes (file:///data/data/org.nativescript.tns57/files/app/tns_modules/@angular/router/bundles/router.umd.js:1950:19) [angular]
JS:     at setFutureSnapshotsOfActivatedRoutes (file:///data/data/org.nativescript.tns57/files/app/tns_modules/@angular/router/bundles/router.umd.js:1954:13) [angular]
JS:     at createNode (file:///data/data/org.nativescript.tns57/files/app/tns_modules/@angular/router/bundles/router.umd.js:1935:17) [angular]
JS:     at file:///data/data/org.nativescript.tns57/files/app/tns_modules/@angular/router/bundles/router.umd.js:1975:20 [angular]
JS:     at Array.map (<anonymous>) [angular]
JS:     at createOrReuseChildren (file:///data/data/org.nativescript.tns57/files/app/tns_modules/@angular/router/bundles/router.umd.js:1958:30) [angular]
JS:     at createNode (file:///data/data/org...
```

I'm using Angular in NativeScript project, however, it relates to Angular itself. Also, there is a similar [issue](https://github.com/angular/angular/issues/13869) that is closed but not solved.

**Comment by vahidvdn** [comment]
**Update:** This occurs when I navigate to tabs page which has some children as following:

```TS
// tabs-routing.module.ts
const routes: Routes = [
    {
        path: "default",
        component: TabsComponent,
        children: [
            {
                path: "home",
                outlet: "homeTab",
                component: NSEmptyOutletComponent,
                loadChildren: "~/app/modules/home/home.module#HomeModule",
            },
            {
                path: "browse",
                component: NSEmptyOutletComponent,
                loadChildren: "~/app/modules/browse/browse.module#BrowseModule",
                outlet: "browseTab"
            },
            {
                path: "search",
                component: NSEmptyOutletComponent,
                loadChildren: "~/app/modules/search/search.module#SearchModule",
                outlet: "searchTab"
            }
        ]
    }
]
```

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-issue-repro2).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

<hr>

AFAIK, this is not a general problem with this functionality and it looks like you're hitting something we are specifically trying to avoid. A reproduction is needed to see what could be causing this.

**Comment by vahidvdn** [comment]
@jasonaden Actually as I mentioned in the issue, this issue relates to NativeScript project, so I can't reproduce it with StackBlitz. Alternatively, I can provide a GitHub [repo](https://github.com/NativeScript/login-tab-navigation-ng/issues/7). Btw, I'm not sure this relates to Angular or nativescript-angular module.

**Comment by tskweres** [comment]
same error, any solution?
