### ISSUE TITLE
Uncaught Error: Can't resolve all parameters for ApplicationModule: (?).

### ISSUE THREAD

**Issue by harishinfor** [angular/angular#30581]
I want to run a angular project which i was taken from github
https://github.com/DanWahlin/Angular-BareBones

But it is throwing errors
1. Uncaught Error: Can't resolve all parameters for ApplicationModule: (?).
    at syntaxError (compiler.js:1021) in console when iam running project
2.  node_modules/rxjs/internal/types.d.ts(82,52): error TS1005: ';' expected.
in Visual Studio Code.

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-issue-repro2).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
