### ISSUE TITLE
Ivy: fullTemplateTypeCheck ignores the mapping between attributes and properties

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#30607]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler-cli

### Is this a regression?

No

### Description

A template containing:

```html
<label [for]="name">
```

 throws with Ivy and `fullTemplateTypeCheck`. 

## 🔥 Exception or Error

<pre><code>
Property 'for' does not exist on type 'HTMLLabelElement'
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0-rc.4
Node: 11.11.0
OS: darwin x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.800.0-rc.4
@angular-devkit/core         8.0.0-rc.4
@angular-devkit/schematics   8.0.0-rc.4
@schematics/angular          8.0.0-rc.4
@schematics/update           0.800.0-rc.4
rxjs                         6.4.0
</code></pre>

**Anything else relevant?**

The type-checker doesn’t understand the mapping done between attributes and properties, and there is probably the same issue for all of https://github.com/angular/angular/blob/df1d3fb/packages/core/src/render3/instructions/shared.ts#L774-L780

cc @alxhub as we talked about it on Slack

**Comment by JoostK** [comment]
Tracked as FW-1327 ;)

**Comment by cexbrayat** [comment]
@JoostK Don't know how I managed to miss it with the exact same content 😓 Thank you for pointing it out.
