### ISSUE TITLE
on navigate router oulet get refresh but not sibling component in first time

### ISSUE THREAD

**Issue by vipinrana** [angular/angular#30603]
In my app component i have a header component directive and router oulet, so after login if i navigate to another component the page refresh only dashboard component because it render by router oultet but header directive is not loading in first time. But if i refresh the page it works fine.

app.component.html
`<app-header></app-header>`
`<router-oulet></router-outlet>`

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
