### ISSUE TITLE
DOM properties and capitalization 

### ISSUE THREAD

**Issue by SanderElias** [angular/angular#3061]
When accessing dom properties that have a capital in them, ng requires an -. Is this really necessary?
I mean, when I want to address innerText it becomes inner-text in my template.
Now take this code:
    
    <h2 #h2 >My app say's "Hello {{hello}}"</h2>
    <h3 [inner-H-T-M-L]='h2.innerHTML'></h3>

That doesn't look nice does it? It works, and does what it is supposed to do, but can't we just drop the need for the - at all? Is there really no other way around the auto-lower-casing of the DOM?

**Comment by pkozlowski-opensource** [comment]
> but can't we just drop the need for the - at all? Is there really no other way around the auto-lower-casing of the DOM?

I don't think so, at least not with the current strategy of compiling live DOM that was already parsed from text by a browser. Basically browsers will lower-case everything before Angular has a chance to kick in. 

So, to "solve" this problem we would have to do HTML text -> DOM parsing in the framework (which is sort of needed for the server-side rendering anyway...). But this would be substantial change in the way the framework operates and has its drawbacks (larger code-base, discrepancy of browsers and custom parsers etc.).

Now, coming back to your problem, we've got [special-casing](https://github.com/angular/angular/blob/81abc39929bac55f8e385f265beecee17d669fe7/modules/angular2/src/dom/browser_adapter.ts#L6) for commonly used properties, including innerHTML, so you can simply do: `<h3 [inner-html]='h2.innerHTML'>`. 

We are working on making this special-casing configurable / generic in https://github.com/angular/angular/issues/2014

Closing for now as there are reasonable work-arounds for now and we are working on the more generic solution. But I would love to continue the discussion if you've got any further questions / remarks.
