### ISSUE TITLE
ReactiveForms directives - mark component for Changes (make reactive forms trully reactive) 

### ISSUE THREAD

**Issue by montella1507** [angular/angular#30610]
# 🚀 feature request
@angular/forms

### Description
ReactiveForms is the main way how to handle forms, however i think they are not so reactive as they should be and it leads to big and easy to avoid boilerplate in code, main problems are:

- reactive forms directives do not mark component for checks. Why? It is very common scenario when you want to pass formControl / formGroup to "sub-edit" component. Developer has to do everytime the same - subscribe to status / value changes and markForCheck component manually. It doesnt respect the principle of least astonishment as well (https://en.wikipedia.org/wiki/Principle_of_least_astonishment) 

- i got ReactiveForms have methods like setValue / patchValue because of tests and for usage in non-reactive environment. However, if they are named reactive - they are missing still one thing -  reactive way to enable / disable form parts..  

- statusChanges push notifications only for validity - they should push notifications for ALL status changes.. why? You would like to  show / hide buttons when form is dirty / pristine, etc... 

Please, focus atleast on posiblities to "auto mark" components  by reactive forms directives like formControl, formControlName etc. It is very usable (it eliminates big part of component boiler plate) and it is very cheap (call on markForCheck()). When you have time, think about reactive solution to update value of form parts...

because setValue/patchValue is not a reactive way (calling methods != reactive) .

Thank you for your work, cannot wait for new NG 8.0! 

### Describe the solution you'd like
1) auto markforcheck in reactive forms directive
2) provide a way to reactively set form control value [formControl]="name" [formControlValue]="person.name"

to eliminate
@Input
set person(value: Person) {
 this.form.get('name').setValue(value.name);
}

3) statusChanges should notify about all status changes - like Router does.  We can still filter events by type.

4) Provide reactive way to disable /enable form.

### Describe alternatives you've considered
Template driven forms. Custom directives to disable / enable formControl, etc.

**Comment by maxime1992** [comment]
> It is very common scenario when you want to pass formControl / formGroup to "sub-edit" component

For that use case, you should rather use a [`ControlValueAccessor` ](https://angular.io/api/forms/ControlValueAccessor).

We've been working at [CloudNC](https://cloudnc.com/) on making sub forms easier to deal with and decided to open source the library we've built. Behind the scenes it's using `ControlValueAccessor` and adds a bunch of feature like type safety, recursive errors, etc. You can check it here: [https://github.com/cloudnc/ngx-sub-form](https://github.com/cloudnc/ngx-sub-form).

> i got ReactiveForms have methods like setValue / patchValue because of tests and for usage in non-reactive environment. However, if they are named reactive - they are missing still one thing - reactive way to enable / disable form parts..

What do you mean? You can do `myFormGroup.disable()` or `myFormGroup.enable()`. Same for `FormControl`s.

**Comment by montella1507** [comment]
So... your proclaimed solution is to implement controlValueAccessor in component and extend that "basecomponent"?

I am still not sure, because AFAIK  formControl / formControlName and ControlValueAccessor is defined as api to work with FormControl and NOT AbstractControl, so you are passing FormGroup where FormControl is expected. 

And FormGroup doesnt inherit from FormControl. From my point of view - the  behavior is then "Undefined" = it works now, may not work in next version of reactive forms.

Or.. maybe i just didntget your coment / library correctly.

**Comment by maxime1992** [comment]
> So... your proclaimed solution is to implement controlValueAccessor in component and extend that "basecomponent"?

I might be misreading and if that's the case ignore the following, but I'm trying to help here and if you're being rude just don't use the lib and do what you want? :man_shrugging: 

> so you are passing FormGroup where FormControl is expected.

What? Not sure to follow.  
Please take a look into our repo (`src` folder) where you'll find plenty of examples.

> Or.. maybe i just didntget your coment / library correctly.

I think so, but that's ok. We may not have been clear in our Readme or examples.  
If that's the case feel free to open an issue or a merge request and we'll do our best to improve it.

> this.form.disabled$ = anotherobs.map(x=> x.disabled)

That could be easily implemented with `ngx-sub-form`. Not sure we want to put that into the core of our lib for now but open an issue and we can discuss it. In the meantime you might just create a class which extends `NgxSubFormComponent` and implement it yourself.

**Comment by montella1507** [comment]
`if you're being rude just don't use the lib and do what you want? 🤷‍♂`

Just language barrier, sorry for inconvenience.  Should be "your offered solution".

Have to check your library deepr. Will come back to you later, with better understanding of your library, thank you.

**Comment by maxime1992** [comment]
> Just language barrier, sorry for inconvenience

Sure thing, no worries. I understand.

Let me know if I can help you with anything in regards of ngx-sub-form :+1:
