### ISSUE TITLE
value attribute of a checkbox ignored using FormControl.value

### ISSUE THREAD

**Issue by jed-meyer** [angular/angular#30619]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/forms.

### Is this a regression?

Can't tell, probably not.

### Description

The "value" attribute of a checkbox is not respected. FormControl.value seems to reflect the "checked" property in case of a checkbox while inline docs as well as MDN suggest it shouldn't.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-issue-repro2-j3iqgp

## 🔥 Exception or Error
n/a

## 🌍  Your Environment

**Angular Version:**
<pre><code>7.2.9</code></pre>

**Anything else relevant?**
n/a

**Comment by Airblader** [comment]
I assume that's just a practical decision as for most usecases you'd only be interested in a boolean value. Following the value rather than checked attribute would mean it's a string value set to "on" or undefined — which is awkward to handle.

If you really want this behavior you can just implement your own ControlValueAccessor, though.

**Comment by jed-meyer** [comment]
Or set to a user defined string. As in my use case: the result/value of a dynamic form is sent to a PDF generation service that doesn't know anything else.

Breaking standards for practical reasons is probably not best practice, hoping that's not the case here.

**Comment by jed-meyer** [comment]
At least as an intermediate step, angular might behave as is in case value attribute is missing from checkbox to prevent breaking existing usage.
If instead any value attribute is provided, angular should respect it and set the FormControl.value accordingly, i. e. set it to that of the attribute if checked, else set it to undefined and omitting it from FormGroup.value.

**Comment by Airblader** [comment]
That would still be a breaking change.

**Comment by jed-meyer** [comment]
Breaking for users already using a _value_ attribute on a checkbox *and* using FormControl *and* relying on the fact that FormControl does not do anything with the _value_ attribute. It's breaking as per definition, but real world impact should be near _null_ since this usage is mostly self-contradictory.
That said, I'd still prefer doing it right, though, just suggesting a lenient upgrade path.

**Comment by jasonaden** [comment]
Thanks for the issue. I agree there's something wrong or at least misleading about this API. I'm not entirely sure what the best solution is though as there are a number of things to consider. Minimally it seems there should be a way to get access to the "never" value you provided in the "value" attribute.

**Comment by anandmane90-ksb** [comment]
> Angular 9, I can't get it to work with `checked` or `value` attributes. It only work if you don't use the "object" syntax and pass a boolean instead, which means we can't use the `disabled` attributes.
> 
> ```
> this.formGroup = this.formBuilder.group({ 
>       check1: [ true ], // work
>       check2: [{ checked: true }],  // doesn't work
>       check3: [{ value: true }]  // doesn't work
> });
> ```

Hi,
how do we handle this check1 if we have array

**Comment by lebesnec** [comment]
that's not a feature request it's a bug

**Comment by smensito** [comment]
> > Angular 9, I can't get it to work with `checked` or `value` attributes. It only work if you don't use the "object" syntax and pass a boolean instead, which means we can't use the `disabled` attributes.
> > ```
> > this.formGroup = this.formBuilder.group({ 
> >       check1: [ true ], // work
> >       check2: [{ checked: true }],  // doesn't work
> >       check3: [{ value: true }]  // doesn't work
> > });
> > ```
> 
> Hi,
> how do we handle this check1 if we have array

Hello, thanks for your answer, it helped me.
I'm using FormArray to manage some elements and for each one loop, make FormBuilder and FormControl for each field. 

**Example below:**

```
this.controlArray = this.formLabors.get('formLaborsField') as FormArray;

    Object.keys(laborsAPlot?.fieldTasks).forEach((i: any) => {
      const fTask = laborsAPlot.fieldTasks[i];

      this.controlArray.push(
        this.formBuilder.group({
          name: new FormControl({
            value: fTask.name,
            disabled: fTask.checked,
          }),
          datetime: new FormControl({
            value: fTask.datetime,
            disabled: fTask.checked,
          }),
          checked: new FormControl(fTask.checked),
        })
      );
    });
```
In my example I'm running throught a list of field tasks name; datetime; checked attributes. In my case, for checking the checkboxes it just helped pass the boolean variable to the form control **(checked: new FormControl(fTask.checked))** .

**Comment by lebesnec** [comment]
why is this being closed? It's a bug that has not been fixed as far as I can tell.
