### ISSUE TITLE
tsconfig.json not correctly updated when installing bazel

### ISSUE THREAD

**Issue by admir86** [angular/angular#30613]
# 🐞 bug report

### Affected Package
"@angular/cli": "~8.0.0-rc.4",
"@angular/bazel": "~8.0.0-rc.4"

### Is this a regression?

I don't think so

### Description

I'm not sure if it's a bug or I'm missing something, but after adding bazel to an angular/cli project (as described [here](https://github.com/angular/angular/issues/19058#issuecomment-478506712)) which contains a library, the references to the library are broken.
In the tsconfig.json I have paths for the lib:
```json
"paths": {
      "my-lib": [
        "projects/my-lib/src"
      ],
      "my-lib/*": [
        "projects/my-lib/src/*"
      ]
    }
```
but now the `baseUrl` is removed in the tsconfig.json and I'm getting this error:
```
Error: error TS5060: Option 'paths' cannot be used without specifying '--baseUrl' option.
```

## 🔬 Minimal Reproduction
- update to angular/cli 8.0.0-rc.4
- create new angular project `ng new mrtest` 
- add a library `ng g library myLib`
- update the paths in tsconfig.json to use the source instead of the lib build output from dist (this way I can make changes to the lib while ng serve, and don't need to rebuild the library after each change)
- use/import the component/module from the lib in the app
- try to start the app `npm run start` -> error:
```
WARNING: your tsconfig.json file specifies options which are overridden by Bazel:
 - compilerOptions.paths is determined by the module_name attribute in transitive deps[]


src/app/app.module.ts(7,28): error TS2307: Cannot find module 'my-lib'.
```
- if try first to build the lib `ng build myLib` -> error: 
```
BUILD ERROR
error TS5060: Option 'paths' cannot be used without specifying '--baseUrl' option
``` 

## 🔥 Exception or Error
see above

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0-rc.4
Node: 10.15.0
OS: win32 x64
Angular: 8.0.0-rc.4
... animations, bazel, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.0-rc.4
@angular-devkit/build-angular      0.800.0-rc.4
@angular-devkit/build-ng-packagr   0.800.0-rc.4
@angular-devkit/build-optimizer    0.800.0-rc.4
@angular-devkit/build-webpack      0.800.0-rc.4
@angular-devkit/core               8.0.0-rc.4
@angular-devkit/schematics         8.0.0-rc.4
@bazel/bazel                       0.25.1
@bazel/ibazel                      0.10.3
@bazel/karma                       0.27.12
@bazel/typescript                  0.27.12
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.0-rc.4
@schematics/angular                8.0.0-rc.4
@schematics/update                 0.800.0-rc.4
ng-packagr                         5.2.0
rxjs                               6.4.0
typescript                         3.4.5
webpack                            4.30.0
</code></pre>

**Anything else relevant?**

**Comment by alxhub** [comment]
Closing as obsolete - the Bazel builder and associated CLI functionality are deprecated and no longer supported.
