### ISSUE TITLE
ng-add bazel enable fullTemplateTypeCheck by default and cannot be disabled

### ISSUE THREAD

**Issue by elvisbegovic** [angular/angular#30621]
# 🐞 bug report

### Affected Package
`@angular/bazel`

### Is this a regression?
no clue

### Description

If a typical developer in his existing CLI project never mentioned option `angularCompilerOptions.fullTemplateTypeCheck` before and try to (ng-add) bazel in his project. 
Then run `ng serve` or `ng serve --prod` he will get **hundreds** or errors in his console and serving will fail due tue templates mistakes! 

**This candisrupt users and discourage  them to try bazel!!!**

## 🔬 Minimal Reproduction
For repro you can clone [this existing CLI project](https://github.com/istiti/bazel-FullTemplateTypeCheck) that I ng-add bazel to it and make intentionally this error in [app.component.html](https://github.com/istiti/bazel-FullTemplateTypeCheck/blob/master/src/app/app.component.html#L5-L10) template

To get error : `npm install && ng s`

## 🔥 Error
All errors that `fullTemplateTypeCheck` can throw and fail to compile. Here I produce this error: 
<pre><code>
/home/.../src/BUILD.bazel:15:1: Compiling Angular templates (ngc) //src:src failed (Exit 1)
.../app.component.html(10,7): : Property 'propNotExist' does not exist on type 'AppComponent'
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0-rc.4
Node: 10.15.3
OS: linux x64
Angular: 8.0.0-rc.4
... animations, bazel, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.4
@angular-devkit/build-angular     0.800.0-rc.4
@angular-devkit/build-optimizer   0.800.0-rc.4
@angular-devkit/build-webpack     0.800.0-rc.4
@angular-devkit/core              8.0.0-rc.4
@angular-devkit/schematics        8.0.0-rc.4
@bazel/bazel                      0.25.1
@bazel/ibazel                     0.10.3
@bazel/karma                      0.27.12
@bazel/typescript                 0.27.12
@ngtools/webpack                  8.0.0-rc.4
@schematics/angular               8.0.0-rc.4
@schematics/update                0.800.0-rc.4
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**
Bazel always consider `fullTemplateTypeCheck` as enabled. It is important to note: even if we set to **FALSE** `angularCompilerOptions.fullTemplateTypeCheck` in `tsconfig.json` it is enabled.

I think by default `fullTemplateTypeCheck` should be disabled like in CLI without bazel and let users enable it intentionally inside `tsconfig.json`

cc @kyliau

**Comment by Airblader** [comment]
For the record, CLI does also automatically enable this flag in new projects, it just wasn't turned on for existing projects.

**Comment by mstawick** [comment]
Is there any workaround for this? In v9 `fullTemplateTypeCheck` ignores `*ngIf` checks, so it's pretty much unusable.

**Comment by alxhub** [comment]
Closing as obsolete - the Bazel builder and associated CLI functionality are deprecated and no longer supported.
