### ISSUE TITLE
Remove deprecated features from docs examples

### ISSUE THREAD

**Issue by kapunahelewong** [angular/angular#30620]
# 📚 Docs or angular.io bug report

### Description

We need to remove deprecated features from docs examples. 

EDIT: Specifically, see @trotyl's comment [below](https://github.com/angular/angular/issues/30620#issuecomment-495113058). (Thanks, @trotyl!)

### What's the affected URL?**
One example is here:
https://angular.io/guide/dynamic-component-loader#resolving-components

As noted by @trotyl in  https://github.com/angular/angular/pull/30598#pullrequestreview-240432132

### Expected vs Actual Behavior**
Examples in documentation should be up-to-date.

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Browser info

N/A

**Comment by trotyl** [comment]
> We need to remove deprecated features from docs examples.

Sorry for the confusion, I guess in this specific case the proper action is to add `{ static: true }` into `@ViewChild()`.

**Comment by kapunahelewong** [comment]
`@ViewChild()` in docs examples fixed by #30639 🙌🏼

Closing this issue. Will open new ones if I find other features to update.

Thanks for helping me, @trotyl!
