### ISSUE TITLE
APP_BASE_HREF conflicts with routing

### ISSUE THREAD

**Issue by salmau** [angular/angular#30635]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/common or @ngtools/webpack

### Description

I have 2 routes, one for the app module and one for the tabs module. 
#### App routes
```
const routes: Routes = [
  { path: '', redirectTo: 'home', pathMatch: 'full' },
  {
    path: 'home',
    loadChildren: './pages/home/home.module#HomePageModule'
  },
  { path: 'page/:pageName', loadChildren: './pages/page/page.module#PagePageModule' },

  {
    path: '',
    loadChildren: './tabs/tabs.module#TabsPageModule'
  }
]
```

#### App routes
```
const routes: Routes = [
  {
    path: 'tabs',
    component: TabsPage,
    children: [
      {
        path: '',
        redirectTo: '/tabs/tabproduct',
        pathMatch: 'full'
      },
      {
        path: 'tabproduct',
        children: [
          {
            path: '',
            loadChildren: '../pages/tabproduct/tabproduct.module#TabproductPageModule'
          }
        ]
      },
      {
        path: 'tabstory',
        children: [
          {
            path: '',
            loadChildren: '../pages/tabstory/tabstory.module#TabstoryPageModule'
          }
        ]
      },
      {
        path: 'tab/:id',
        children: [
          {
            path: '',
            loadChildren: '../pages/tab/tab.module#TabPageModule'
          }
        ]
      }
    ]
  },
  {
    path: '',
    redirectTo: '/tabs/tabproduct',
    pathMatch: 'full'
  }
]
```

On server side, I have a folder per version (v0.0, v0.1 ... v1.3 ...). I set up a default behavior in order to redirect on a version.
Ex: https://my.app.com/home -> returns the default version in the folder v1.3 for instance

So in my index.html, I have deleted the `<base href="/" />` tag and put a script instead :  
```
<script type='text/javascript'>
    let firstPathname = window.location.pathname.split('/')[1]
    console.log(firstPathname)

    let regexVersioningTag = new RegExp("^v");
    let result = regexVersioningTag.test(firstPathname);
    // if there is a version number
    if(result){ window['_app_base_href'] = '/' + firstPathname; }
</script>
```
So if there is an app version in the URL, the script stores it in a global variable.

In the app.module, I set the APP_BASE_HREF to the global variable or, by default, to '/' : 
```
@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    IonicModule.forRoot(),
    IonicStorageModule.forRoot(),
    AppRoutingModule,
  ],
  providers: [
    StatusBar,
    SplashScreen,
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    { provide: APP_BASE_HREF, useValue: window['_app_base_href'] || '/' }
  ],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
```

## 🔬 Issue

When I access to home page, it works like a charm ! (ie: https://my.app.com/home)

When I access to tabproduct page (ie: https://my.app.com/tabs.tabproduct), the browser produces errors because it's trying to get /tabs/{scripts.js} (but the page loads). 

![image](https://user-images.githubusercontent.com/38292202/58268988-d1c5c680-7d86-11e9-8219-6dc67e79e909.png)

However, the tags scripts in the index.html are good !
  
![image](https://user-images.githubusercontent.com/38292202/58268975-ca9eb880-7d86-11e9-8617-8d7b03fbabce.png)

## 🌍  Your Environment

**Angular Version:**
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.5
@angular-devkit/schematics        7.3.5
@angular/cli                      7.3.5
@angular/compiler                 7.2.2
@angular/compiler-cli             7.2.8
@ngtools/webpack                  7.3.8
webpack                           4.29.0

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-issue-repro2).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

<hr>

Looks like you went for some detail on the issue, and that's helpful. But without a reproduction we can't dig in on issues like this as it's really hard to tell what's happening in your environment to get an idea of the root cause.
