### ISSUE TITLE
Bazel hangs loading the JDK

### ISSUE THREAD

**Issue by alxhub** [angular/angular#30636]
Across both of my machines lately, I've been seeing an issue where Bazel hangs at `currently loading: @local_jdk//`, or in the analysis phase. It spends O(minutes) here if it even completes at all, and CPU usage maxes out to the point where the machine becomes unusable otherwise. `bazel clean --expunge` solves the problem temporarily, but it will return without warning on future builds. 

```
$ bazel test //tools/public_api_guard/...
INFO: Invocation ID: f4f2d880-00c4-4ec6-8ef7-791019fcc2fa
INFO: Build option --legacy_external_runfiles has changed, discarding analysis cache.
Analyzing: 93 targets (4 packages loaded, 11414 targets configured)
    currently loading: @local_jdk//
```

This is making it difficult for me to work.

**Comment by alexeagle** [comment]
Asked the Bazel team about it, it's apparently this: https://github.com/bazelbuild/bazel/issues/8355
I think to fix it on our side, we would need to use native node binary for the nodejs_test in ts-api-guardian/index.bzl rather than a sh_test wrapper that we use now for Windows support

**Comment by alexeagle** [comment]
As a workaround, try replacing
`load("@build_bazel_rules_nodejs//:defs.bzl", "nodejs_binary", "nodejs_test")`
with
`load("@build_bazel_rules_nodejs//internal/node:node.bzl", "nodejs_binary", "nodejs_test")`
and add `"@bazel_tools//tools/bash/runfiles"` to the data[] of the test

this will avoid the macro that expands to an sh_test and give you just pure node

**Comment by alxhub** [comment]
Haven't seen this in months; closing.
