### ISSUE TITLE
getting error trying to unit test my app-route.module.ts

### ISSUE THREAD

**Issue by Saeed-Najafi** [angular/angular#30631]
I have an application that hosts 2 other application (a website and dashboard)

for my mian application I either redirect to website or redirect to dashboard!
I am trying to make a unit test for this part:
my app-routing.module.ts lookslike this:
```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

export const routes: Routes = [
  {path: 'dashboard', loadChildren: './dashboard/dashboard.module#DashboardModule'},
  {path: '', loadChildren: './splash/splash.module#SplashModule'},
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }

```
my  app.component.spec.ts is:
```
import { TestBed, fakeAsync, tick, async } from "@angular/core/testing";
import { RouterTestingModule } from '@angular/router/testing';
import { AppComponent } from './app.component';
import { routes } from './app-routing.module';

describe('AppComponent', () => {
    beforeEach(async(() => {
        TestBed.configureTestingModule({
            imports: [
                RouterTestingModule.withRoutes(routes)
            ],
            declarations: [
                AppComponent
            ],
        }).compileComponents();
    }));

    it('should create the app', async(() => {
        const fixture = TestBed.createComponent(AppComponent);
        const app = fixture.debugElement.componentInstance;
        expect(app).toBeTruthy();
    }));

    it('should have as title "feedback-analytics"', async(() => {
        const fixture = TestBed.createComponent(AppComponent);
        const app = fixture.debugElement.componentInstance;
        expect(app.title).toEqual("feedback-analytics");
    }));

    // it("navigate to '' redirects you to /dashboard ", fakeAsync(() => {
    //     this.routes.navigate(['']);
    //     tick();
    //     expect(location.path()).toBe('/dashboard');
    // }));
});
```
with this I pass 2 codes, but when I try to test the dashboard part (commneted part) I get an error and I wont pass any tests!

what am I doing wrong?

**Comment by geromegrignon** [comment]
There are 2 problems : 
- you want to check the redirection but you firstly need to declare this redirection
- the '' path is already set to your SplashModule

Try out the following code sample to replace your routes 👍 

`
export const routes: Routes = [
  {path: '', redirectTo: '/dashboard', pathMatch:'full},
  {path: 'dashboard', loadChildren: './dashboard/dashboard.module#DashboardModule'},
  {path: splash'', loadChildren: './splash/splash.module#SplashModule'},
];
`

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
