### ISSUE TITLE
Can't access queryParams and fragments from canLoad

### ISSUE THREAD

**Issue by Chadys** [angular/angular#30633]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/router

### Description
 #12411 and #17359 are still not solved, even though now the `canLoad` function possesses a `UrlSegment[]` argument. This argument enable us to access matrix parameters, but the query parameters and fragments of the destination url are still out of reach from inside of the `canLoad`function

### Describe the solution you'd like
 Instead of a `UrlSegment[]` argument, what we need is a `UrlTree`

### Describe alternatives you've considered
 The only solutions available right now are still the same ones that have been given previously, and they are not satisfactory : either access the exact url from the `window` object (but there are lots of situation when the browser and router state are not in sync, like when using `skipLocationChange`) or give up on `canLoad` altogether and only use `canActivate` (but lose the benefit of lazyloading).

**Comment by joselcvarela** [comment]
Any ideas on when this will be implemented?
I have a route with lazy load children and need to access the parameters so I can check with canLoad if children modules/routes could be loaded and have no idea how to do that right now.
I am using `window.location.pathname` but only works if I access the child route directly by entering the URL in address bar. If I try to navigate to there via application I have no access to parameter ID neither by `window.location.pathname` neither by `UrlSegment`.
The UrlSegment only shows the parameter ID if I put that route one level up

**Comment by ciesielskico** [comment]
Also looking forward to having this implemented, have to comment out the canLoad section and just rely on canActivate for now.

**Comment by changhuixu** [comment]
Looking forward to having this feature. Thank you.

**Comment by kumaravnish** [comment]
+1
Having to load the bundle for users that should not be able to load, is undesirable, if we resort to canActivate. Can this be prioritized?

**Comment by stevethemacguy** [comment]
One year later, and there's still no way to access query parameters in CanLoad, so it's not possible to redirect the user to their intended destination url. 😢

**Comment by stevethemacguy** [comment]
Any update on this? This is a security issue. Without CanLoad, the app will load JS bundles even if the user isn't authorized to view that part of the app. Thank you.

**Comment by fabianrios** [comment]
2021 now :)

**Comment by atscott** [comment]
Closing, this information would be available by using `this.router.getCurrentNavigation().extractedUrl`.

**Comment by dabbid** [comment]
Can't we also get query params with `this.router.routerState.snapshot.root.queryParams`? What are the differences by the way from getting them with `this.router.getCurrentNavigation().extractedUrl.queryParams`?

**Comment by atscott** [comment]
> Can't we also get query params with `this.router.routerState.snapshot.root.queryParams`? What are the differences by the way from getting them with `this.router.getCurrentNavigation().extractedUrl.queryParams`?

@dabbid - The `routerState` represents the _current_ state of the router while `this.router.getCurrentNavigation()` would represent the in-flight navigation.
