### ISSUE TITLE
HI YOU SHOULD WRITE THE LINE NUMBER IN ANGULAR DOCUMENTATION

### ISSUE THREAD

**Issue by mrhili** [angular/angular#30648]
This method is Unsufisant for a beginner developer

![image](https://user-images.githubusercontent.com/40344789/58297645-bedbe200-7dd8-11e9-8753-ef1b05ec3d5f.png)

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
