### ISSUE TITLE
New router for Angular 1.X

### ISSUE THREAD

**Issue by beataa** [angular/angular#3065]
Hello,

In our project we are using Angular 1.4 and we've started to use new router as we want go in component based approach with flux architectural pattern. We are hoping with this approach we could migrate more easily to Angular 2.0.

So far all work great, still there are some issues with the router. Like we cannot have multiple named viewports at one view and so on. We have address them some time ago and were hoping they would be fixed in next router release.

Now we discovered that router source are moved to Angular 2.0 repository and seems like there will be no further releases of angular-new-router, or?

Can you support us now how shall we proceed here to be able to use new router with bug fixes with Angular 1.X ?

Is it still possible to have angular-new-router released for Angular 1?
Shall we use somehow modules from Angular 2?

Thanks in advance.

Regards,
Beata

**Comment by btford** [comment]
@beataa – track #1707. I'm working this week to get that in and be able to produce a build of the component router for angular 1.x that includes many of the bug fixes.

**Comment by beataa** [comment]
Great, thanks for the info Brain.

**Comment by btesser** [comment]
@btford @shahata Any news on this...?

**Comment by frodefi** [comment]
#1707 was closed a while ago. Eagerly waiting for news on this...

**Comment by PascalPrecht** [comment]
@btford is working hard on this. You can track the current state here: https://github.com/angular/angular/pull/3698

**Comment by xermiz** [comment]
i have problem in routes dinamycal whith angular 1 y sou hard
