### ISSUE TITLE
Runtime error, while bazel compile successfully.

### ISSUE THREAD

**Issue by elvisbegovic** [angular/angular#30662]
# 🐞 bug report

### Affected Package
`@angular/bazel`

### Description

Trying to add 3th party lib.
Immediatly when I add lib in `deps` of [/src/BUILD.bazel](https://github.com/istiti/bazel-runtime-error/blob/master/src/BUILD.bazel#L36) file, devserver trig file change and compile successfully, while at runtime we get error.

## 🔬 Minimal Reproduction

1. clone https://github.com/istiti/bazel-runtime-error
2. npm install 
3. ng serve

ONE LINE REPRO : _sudo git clone https://github.com/istiti/bazel-runtime-error && cd bazel-runtime-error && sudo npm install && ng s_

In console, devserver successfully compile: 

![image](https://user-images.githubusercontent.com/2789203/58334198-4fe5a400-7e3f-11e9-9166-5dd508f56372.png)

## 🔥 Error (runtime)
At runtime we get:

![image](https://user-images.githubusercontent.com/2789203/58334895-b9b27d80-7e40-11e9-8664-b091ceb378bf.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0-rc.4
Node: 10.15.3
OS: linux x64
Angular: 8.0.0-rc.4
... animations, bazel, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.4
@angular-devkit/build-angular     0.800.0-rc.4
@angular-devkit/build-optimizer   0.800.0-rc.4
@angular-devkit/build-webpack     0.800.0-rc.4
@angular-devkit/core              8.0.0-rc.4
@angular-devkit/schematics        8.0.0-rc.4
@bazel/bazel                      0.25.1
@bazel/ibazel                     0.10.3
@bazel/karma                      0.27.12
@bazel/typescript                 0.27.12
@ngtools/webpack                  8.0.0-rc.4
@schematics/angular               8.0.0-rc.4
@schematics/update                0.800.0-rc.4
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**
We could fail build at console too and indicate to users what is wrong/how 3th party lib should be added in ts_devserver() too ?

cc @alexeagle

**Comment by alxhub** [comment]
Closing as obsolete - the Bazel builder and associated CLI functionality are deprecated and no longer supported.
