### ISSUE TITLE
Calling FormControl#enable on an enabled control causes errors to be cleared

### ISSUE THREAD

**Issue by jermowery** [angular/angular#30665]
# 🐞 bug report

### Affected Package
@angular/forms

### Is this a regression?

Not that I am aware of

### Description

If you call enable on a FormControl that has errors the errors will be cleared, even if the FormControl is already enabled.

What I expect to happen

One of the following:

1. Calling enable on a FormControl should never clear errors, same with disable
2. Calling enable on a FormControl that is already enabled should be a no-op, same with disable

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-vr5sfn

Look at the console logs

## 🌍  Your Environment

g3 head

**Comment by santoshyadav198613** [comment]
Hi @jasonaden ,

Will work on this.

**Comment by jermowery** [comment]
Thanks for taking the time to work on this!
Do you know when we can expect this to be merged to master?

**Comment by santoshyadav198613** [comment]
> Thanks for taking the time to work on this!
> Do you know when we can expect this to be merged to master?

Will update will try to wrap up by next week, as I am busy this week.

**Comment by jermowery** [comment]
Any update on this?

**Comment by sonukapoor** [comment]
@AndrewKushnir Was this ever completed? If not, I can probably take this over.

**Comment by AndrewKushnir** [comment]
Hi @sonukapoor, I don't think that we have an open PR with the fix.

Looking at the problem, I'm leaning towards making `enable()` call on already enabled control a noop (same for `disable()`). However given the logic in `enable` and `disable` functions, it would probably be a breaking change, since developers may rely on some side-effects (like re-running validators). We can try to implement the noop version and see how break-y this change is by running tests in Google's codebase - based on that we can see what the next steps are. What do you think?

**Comment by sonukapoor** [comment]
Hi, I think that makes sense. Please assign the issue to myself and I will add it to my work slate. Thanks

**Comment by AndrewKushnir** [comment]
Thanks @sonukapoor, I've assigned this issue to you as requested. Thank you.

**Comment by sasunstepanyan777** [comment]
Hi, is this still actual?

**Comment by JeanMeche** [comment]
Isn't the problem that `enable()` calls `updateValueAndValidity()` which calls the validators. 

But since the errors were not generated by the validators they don't appear anymore. 

I would lean toward, "work as excepted". Just use validators.

**Comment by travisbashor** [comment]
Agreed. It seems like the whole goal of `enable()`ing a control is to include it in validity checks. So, even if there were an optional boolean flag, say `doValidityChecks = true` as another parameter to `enable()`, it would all wash out as soon as the first validity check runs anyway. And in the meantime, it would misrepresent the status of the form as (potentially) invalid when all of the validators would pass.

The [docs](https://angular.io/api/forms/AbstractControl#enable) say "Its status recalculates based on its value and its validators." So, doesn't seem like a bug. Maybe a little awkward though.

**Comment by JeanMeche** [comment]
Closing per above.
