### ISSUE TITLE
Angular Dynamic Menu using Material design lite

### ISSUE THREAD

**Issue by tt0686** [angular/angular#30673]
I want to create a dynamic menu, the data is get from database for instance. Here is the [https://stackblitz.com/edit/angular-dmenu](StackBlitz ) project

In the dynamic-menu.component.html in the StackBlitz project there are the dynamic solution and the static solution(that is commented).

The static solution should be how the dynamic solution will be rendered after executes.
If i just run with the static solution(uncomment and commented the dynamic) everything runs as expected, but if i try with the dynamic solution the menu does not work as expected (the main buttons stays on top of each other and the submenus do not display and work properly).
Is this related with how ng-template affect the CSS styles ?
Looking through Chrome developer tools i am able to see that the class="mat-menu-item ng-star-inserted" attribute in the dynamic version is added to the button for instance and this does not happen in the static version. I have try everything but i can not get it why is this happening. And how can i fix this. I am new to Angular but i want really understands how the frameworks works

Thanks in advance

Best regards

**Comment by matsko** [comment]
Sorry this issue doesn't follow our issue guidelines. Please resubmit something new with all the information provided.
