### ISSUE TITLE
Can't compile synchronously as TemplateComponent is still being loaded!     at componentStillLoadingError

### ISSUE THREAD

**Issue by dkdk000** [angular/angular#30672]
Update to angular 7. then this issue came at runtime - build successfully.
ERROR Error: Can't compile synchronously as TemplateComponent is still being loaded!
    at componentStillLoadingError (compiler.js:19229)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.loadDirectiveMetadata (compiler.js:18406)

Angular CLI: 7.3.9
Node: 11.9.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/material                 7.3.7
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.1.5
webpack                           4.29.0

![image](https://user-images.githubusercontent.com/7358889/58368068-49216480-7f05-11e9-981d-302c392309c7.png)

**Comment by alxhub** [comment]
Hello @dkdk000,

In order to investigate this issue we will need a reproduction, otherwise it's difficult for us to track down the problem.

Thanks!

**Comment by pkozlowski-opensource** [comment]
Going to close this one as we haven't hard back with the reproduce scenario.
