### ISSUE TITLE
load style.css failed when open pwa on the surface go

### ISSUE THREAD

**Issue by pinecut** [angular/angular#30682]
I often get the following two errors when I open my pwa on the surface go

`Uncaught (in promise) DOMException     ngsw-worker.js:1`
`Failed to load resource: net::ERR_FAILED   styles.[hash].css:1`

**Comment by gkalpak** [comment]
Unfortunately, there is not much we can do with the provided info and without a reproduction.
It is not even clear whether the issue is related to Angular or not.
