### ISSUE TITLE
The script resource is behind a redirect, which is disallowed

### ISSUE THREAD

**Issue by nimatullah** [angular/angular#30684]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
My website used to run on https://jobs.af, after four months we appended the www -> https://www.jobs.af.

The thing we did not think about was that service workers don’t play nice with redirects

What we didn't pay attention to is that service workers do not play nice with redirects

The user would go to https://www.jobs.af and NGINX would send them a 301 redirect for every resource they’d send a request for.

This worked perfectly fine for new users, but users who had already visited the website would encounter some issues.

Service workers update themselves automatically if there’s a new version available. In our case it tried to get the new version on https://www.jobs.af/ngsw-worker.js, which redirects to https://jobs.af/ngsw-worker.js. So the service worker would try to update itself from a new service worker behind a redirect which caused the following error:

enter image description here

My Code:

`app.browser.module.ts`
```
@NgModule({
  imports: [
    BrowserModule.withServerTransition({ appId: "app-root" }),
     .
     .
     .
    ServiceWorkerModule.register("./ngsw-worker.js", {
      enabled: environment.production
    })
  ],
  bootstrap: [AppComponent]
})
export class AppBrowserModule {}
```
`main.ts`
```
document.addEventListener("DOMContentLoaded", () => {
  platformBrowserDynamic()
    .bootstrapModule(AppBrowserModule)
    .then(() => {
      if ("serviceWorker" in navigator && environment.production) {
        navigator.serviceWorker.register("./ngsw-worker.js");
      }
    })
    .catch(err => console.log(err, "error"));
});
```
`manifest.json`
```
{
...
  "scope": "/",
  "start_url": "/"
}
```

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error

 

`The script resource is behind a redirect, which is disallowed`
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.2.9
Node: 10.6.0
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cdk                      6.4.7
@angular/cli                      6.2.9
@angular/material                 6.4.7
@angular/pwa                      0.10.7
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.8.9
rxjs                              6.5.2
typescript                        2.9.2
webpack                           4.8.3
    
```
</code></pre>

**Anything else relevant?**

**Comment by nimatullah** [comment]
@mhegazy can you please look at this.

**Comment by deliverymanager** [comment]
+1

**Comment by alxhub** [comment]
Thanks, this is good to know. I think this is more of a devops issue as there's nothing we can do on the Angular side to address it. However, we can improve our documentation, so I'll route the issue that way.

**Comment by TinyMan** [comment]
Can I do this ? 

I'll add a section in `Service worker in production` > `Service Worker Safety` if you are ok with that.
