### ISSUE TITLE
Additional information on how to migrate to new ViewChild/ContentChild

### ISSUE THREAD

**Issue by EmaGht** [angular/angular#30685]
# 📚 Docs or angular.io bug report

### Description
From https://next.angular.io/guide/static-query-migration:

> Without the static flag, the compiler decided when each query would be resolved on a case-by-case basis. All @ViewChild/@ContentChild queries were categorized into one of two buckets at compile time: "static" or "dynamic".

But now we have to define this, and this is cool with me, but what if my code relied on a Query which, in one case, needs to be dynamic, and in another case, needs to be static?

Example:
- I have a base_validation component, which gets specialized in input_validation, select_validation, etc...
- The base_validation component keeps a link on a generic NgModel declared in each of the specialized components
- In "input_validation", the NgModel must be resolved statically
- In "select_validation", the NgModel must be resolved dynamically (i have to do some *ngIf magic there)

After fiddling with this for some time i found a way to make the new ViewChild act exactly like the previous version so that component logic refactoring will not (as far as my tests go) be required.

(Apparently i'm unable to format this decently...)

@ViewChild(NgModel, { static: false }) validationControl: NgModel;

@ViewChild(NgModel, { static: true }) set validationControl_static(comp: NgModel) {
    if (comp) { this.validationControl = comp; }
};

This way, apparently, you get the dynamic part of the ViewChild and you "manually" merge it with the static part. (also, setters on a dynamic ViewChild doesn't get fired for some reason).

I think this might be useful to add to the static-query-migration. At least it would have been useful for me :)

Cheers!

### What's the affected URL?**
https://next.angular.io/guide/static-query-migration

**Comment by IgorMinar** [comment]
We are keeping an eye on how common this is and if we need to address it in a better way, but in the meantime this pattern should work for cases like yours.

https://github.com/angular/components/blob/d1366ba2b05d8893fb52e23b7cef5900b534abcd/src/material/form-field/form-field.ts#L255-L260

**Comment by EmaGht** [comment]
Thanks for the example,
I tried it out and works the same as my hackish solution so i'll stick with what you guys are using!

Cheers!
