### ISSUE TITLE
How to efficiently type the double theta `ɵɵ` as in `ɵɵinterpolate`?

### ISSUE THREAD

**Issue by qzmfranklin** [angular/angular#30694]
I am experimenting with the Ivy API.
I am interested in learning how to type the theta character `ɵ` efficiently without having to move off my keyboard.
Though it is mysterious to me, it should, I believe, be a solved problem within the Angular team. 

Any help is appreciated. Thanks in advance!

**Comment by trotyl** [comment]
> We explicitly don't consider the following to be our public API surface:
> any class members or symbols marked as `private`, or prefixed with underscore (`_`), barred latin o (`ɵ`), and double barred latin o (`ɵɵ`).

https://github.com/angular/angular/blob/master/docs/PUBLIC_API.md

The whole point of `ɵ` prefix is to avoid being typed by any user.

**Comment by qzmfranklin** [comment]
Thanks
