### ISSUE TITLE
docs(cli): edit/code buttons on cli command pages don't open a valid documentation file

### ISSUE THREAD

**Issue by Splaktar** [angular/angular#30700]
# 📚 Docs or angular.io bug report

### Description
Regarding the Edit (pencil) and code (`<>`) icons on the Angular CLI command pages, they do not appear to be useful.

### What's the affected URL?**
- https://next.angular.io/cli/serve
- https://next.angular.io/cli/generate
- etc.

### Reproduction Steps**
For next.aio:
- Edit opens a file like https://github.com/angular/angular-cli/blob/fe98024146de885ff70bde34b75139661613c9e7/packages/angular/cli/commands/serve.json that provides almost no possible way for someone to edit the page’s content other than the one sentence description.
- Code takes you to a 404 page ([url](https://github.com/angular/angular-cli/tree/v8.0.0-beta.18+129.5639079/packages/angular/cli/commands/serve.json))

For AIO:
- Edit takes you to generally the same file, as above, that isn’t useful for editing the page’s content
- Code takes you to the same file that is also not useful for reading or viewing the command’s options.

### Expected vs Actual Behavior**

Edit/Copy should take you to a Markdown file that can actually be edited to improve the Angular CLI documentation.

## 📷Screenshot

![Screen Shot 2019-05-28 at 12 57 59](https://user-images.githubusercontent.com/3506071/58497962-094bbe80-814b-11e9-9460-de30318b93d2.png)

## 🔥 Exception or Error
N/A

### Browser info
Chrome 74

### Anything else relevant?

N/A

**Comment by jenniferfell** [comment]
Is this specific to CLI command reference? Is the issue that the original source is in the CLI repo, so we need to either open the correct file in that repo, instead open an issue in this repo, or just disable this ability on the CLI command reference pages?

Adding @jbogarthyde for her info.

**Comment by jbogarthyde** [comment]
The doc page markdown is generated from JSON files in the CLI repo, so editing them wouldn’t work, and I don’t think AIO could find the original source. We should probably disable the button on these pages.

**Comment by Splaktar** [comment]
It's nice to have the auto generated docs, but it's not at all nice to discourage community contributions by making it excessively difficult to fix the documentation.

**Comment by gkalpak** [comment]
Why couldn't aio find the original source, @jbogarthyde? I am sure there is an "algorithm" for mapping the generated file to the source (in whatever format it might be 🤷‍♂).
