### ISSUE TITLE
Allow whitelisting and blacklisting for scroll reset

### ISSUE THREAD

**Issue by Amos47** [angular/angular#30709]
# 🚀 feature request
Allow enabling/disabling scroll restoration on a route level

### Relevant Package
This feature request is for @angular/router

### Description
We are forced to set scroll restoration behaviour on the app level.

There are specific cases, where we actually wish to disable the behaviour.
In our case the data can change, and the layout is the same. We would like to keep the user's scroll position even though the route has changed.

Right now we have to drop using the default scrolling system and use our own. It's probably less efficient and won't get updated as much.

### Possible Solutions Considered
It could be solved a few different ways.

**1. Global Blacklist**

```ts
{ 
  anchorScrolling: 'enabled',
  scrollPositionRestoration: 'enabled',
  scrollPositionBlacklist: [{from: /^todo\/.*$/, to: /^todo\/.*$/}]
}
```

By allowing the `from` and `to`, you can provide a lot more flexibility and a very easy to reason about system at the global level. This is also a relatively straightforward implementation, without needing to introduce any other concepts or dependencies.

The downside to this implementation is that it would be very easy to update the route without updating the corresponding blacklist. It's not easy to understand the whole route logic without seeing the route.

**2. Route Option**
The ideal long-term solution (IMO) would be two new parameters on the `Route` definition for `scrollPositionRestoration` and `anchorScrolling`

The option would look something like.

```ts
{ path: '/todo/:id', scrollPositionRestoration: { value: 'enabled',  from : /todo\/.+/  } }
```

The positive to this is that it keeps things consistent for the global/local options. It also allows for extension to make it a async function in a future feature.

The downside is that it extends the already bloated `Route` options. It lacks the ability to define global cases that are a little more broad, creating repetition.

## Contributing
This is something I am willing to try and tackle, if given permission and we can agree on a strategy.

**Comment by chris13524** [comment]
I have a similar issue. We have routable modals and we don't want to scroll position to be reset when they hide/show. [Similar issue.](https://github.com/angular/angular/issues/26848)

Similarly, consider a tabbed view where changing tabs shouldn't reset the scroll.

[This](https://github.com/angular/angular/issues/26744) proposal would also work, but it is not in the declarative fashion as this issue proposes.

**Comment by atscott** [comment]
The scroll implementation is designed to satisfy most use cases and be flexible enough to override behavior for anything application specific. This can be implemented be subscribing to the `Scroll` event and performing the scrolling in app-specific code ([example](https://stackblitz.com/edit/angular-ivy-smjyr7?file=src%2Fapp%2Fhello.component.ts,src%2Fmain.ts,src%2Fapp%2Fapp.component.ts,src%2Findex.html)). Adding this as a built-in option increases the API surface and would be non-tree-shakeable that increases the bundle size for all applications when most won't need it.
