### ISSUE TITLE
Angular 7 Service Worker takes old cache

### ISSUE THREAD

**Issue by f1nality** [angular/angular#30715]
# 🐞 bug report

### Affected Package
"@angular/common": "7.0.1"
"@angular/service-worker": "7.0.1"
"@angular/cli": "7.0.3"

### Description

I have a strange behavior. I've added service workers to my application a couple of months ago and it worked as expected all this time. But a week ago i began to see such behavior:

When I open my application after some time of browser inactivity the old version from cache is served (week ago cache). When I wait some time and refresh the page - i see the new version loaded, and of course after other reloads too. But if i close my application and open it after some time around 30 minutes (not right after it), it will see again the old cached version (a week ago). How it can be? I thought cache should be overwritten by new version. This situation repeats again and again during some days. Other users see the same behavior. I don't see any changes in the code that could be connected with this.

I had the same situation on another angular project and had to remove service worker to fix it.

## 🔬 Minimal Reproduction
Can't reproduce since its a bug on production only. The app is hosted here:
https://app.jetadmin.io/

## 🔥 Exception or Error
Old version is loaded

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.0.3
Node: 8.11.2
OS: darwin x64
Angular: 7.0.1
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.5
@angular-devkit/build-angular     0.6.5
@angular-devkit/build-optimizer   0.6.5
@angular-devkit/core              0.6.5
@angular-devkit/schematics        7.0.3
@angular/cli                      7.0.3
@angular/pwa                      0.13.6
@ngtools/webpack                  6.0.5
@schematics/angular               7.0.3
@schematics/update                0.10.3
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.8.3
    

</code></pre>

**Comment by YuZaiShui** [comment]
May i ask you a question ? How do you do about remove service worker? Maybe i had the same situation.

**Comment by f1nality** [comment]
I found the problem
There was an error at /ngsw/state URL saying it cannot read manifest since checksum of JS file is not correct. That was because of my post build scripts that modified JS files.
