### ISSUE TITLE
Angular 7 IE11 View Not Changing when Array Updates works in Chrome/FF

### ISSUE THREAD

**Issue by lenichols** [angular/angular#30710]
Searched the issue for this but unable to find a fix.

I have an array that is being passed to a <select> element. When the array is updated, in IE 11, the change is not reflected in the view. In other words, if i have an array say ["one", "two", "three"] and i reduce the array to ["one", "three"] when passing/binding the new reduced array back to the forLoop *ngFor the <options> elements are not updated. When i print the array it proves that it infact has been updated.

I have activated change detection but still can not get this to work in IE. and i've uncommented all the polyfills for IE in polyfills.ts but still, angular 7 will not detect the change to the array.

Any ideas why? Chrome and firefox detects the new array change and displays as expected.

**Comment by markgoho** [comment]
@lenichols this seems like a simple scenario to reproduce. Can you provide a [Stackblitz](https://stackblitz.com/) showing your code?

**Comment by alvaro450** [comment]
If you have OnPush changeDetection then you need to tell angular that a change has occurred by using markForCheck() from the ChangeDetectorRef service. As @markgoho stated, please provide a stackblitz that would provide more context around your issue.

**Comment by alxhub** [comment]
This could also be an issue with polyfills for IE11.

**Comment by lenichols** [comment]
I was able to get this solved by using splice. Simply replacing the array with a new one is not detected in IE11.

**Comment by pkozlowski-opensource** [comment]
Sounds like this one was solved on the user side and we don't have reproduce scenario so going to close it here.

**Comment by lenichols** [comment]
I need to re-open this ticket. Binding does not seem to be working in IE11. I thought i was able to solve with splice but after running in actual IE11 browser live, binding updates still aren't reflecting. Here is the stackblitz - you will need to open it in IE https://angular-7ypkdv.stackblitz.io to see that refreshing the array in the for loop does not work. @pkozlowski-opensource pls re-open this.
