### ISSUE TITLE
@angular/http not updated to v8

### ISSUE THREAD

**Issue by alvaro450** [angular/angular#30736]
# 🐞 bug report

### Affected Package
@angular/http 

### Is this a regression?
No

### Description

Not sure if this was intentional but @angular/http is the only package whose latest tag is still points to a 7.x version, and there is no final v8 version.

## 🔬 Minimal Reproduction
npm install @angular/http@latest  
-- installs v7.2.15

npm view @angular/http versions
-- shows 7.2.15 as the most recent stable release and 8.0.0-beta.10 as the last version published

**Comment by JoostK** [comment]
Hi @alvaro450, the `@angular/http` package has been deprecated for a while and was finally removed in v8. Instructions on how to migrate are available in the deprecations guide:

https://angular.io/guide/deprecations#angularhttp

**Comment by JoostK** [comment]
Actually, I see this is not mentioned in the release notes. We should include a note there.

**Comment by alvaro450** [comment]
Thank you @JoostK, I should have realized that! it may also be worth making the removing of the library part of schematics.
