### ISSUE TITLE
Constructor or variable initialization snippet does not compile

### ISSUE THREAD

**Issue by christophermurphy** [angular/angular#30730]
# 📚 Docs or angular.io bug report

### Description

This is a suggestion to make the code for https://angular.io/guide/displaying-data#constructor-or-variable-initialization either warn a reader that copy and paste will generate an error or make the code drop into the example smoothly.

I copy and pasted the code from the **Constructor or variable initialization?** and it did not compile.

Changing the name of the class from AppCtorComponent to AppComponent fixed the error.

Personally, I would prefer showing newbies the error and explaining how to fix it in the guide.  This would serve the purpose of showing what compile errors look like and how to use them in a controlled way. 

### What's the affected URL?**
https://angular.io/guide/displaying-data#constructor-or-variable-initialization

### Reproduction Steps**
>ng new displaying-data
>cd displaying-data/
>rm src/app/app.component.html
>ng serve

- edit app.component.ts to look like...

```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
  	<h1>{{title}}</h1>
  	<h2>My favorite hero is: {{myHero}}</h2>
  `
})
export class AppCtorComponent {
  title: string;
  myHero: string;

  constructor() {
    this.title = 'Tour of Heroes';
    this.myHero = 'Windstorm';
  }
}
```

### Expected vs Actual Behavior**
Expected the copy and paste to compile.
Actual behavior was an error message.

## 📷Screenshot
None

## 🔥 Exception or Error
<pre><code>
ERROR in app.module.ts(5,10): error TS2305: Module '"./app.component"' has no exported member 'AppComponent'.
</code></pre>

### Browser info
N/A

### Anything else relevant?
Angular CLI: 7.3.9
Node: 8.15.1
OS: linux ia32
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

**Comment by brandonroberts** [comment]
@christophermurphy would you like to submit a PR for this? The file to edit is here: https://github.com/angular/angular/blob/master/aio/content/examples/displaying-data/src/app/app-ctor.component.1.ts. You can edit that file directly from GitHub and create a fork for the pull request.

Commit message example: `docs: rename component for constructor example in displaying data guide`

**Comment by PandiyanCool** [comment]
Hi @brandonroberts 
I've raised a pull request for this change.
https://github.com/angular/angular/pull/30845

**Comment by PandiyanCool** [comment]
This issue can be marked as resolved as the following PR is merged
https://github.com/angular/angular/pull/30845
