### ISSUE TITLE
After upgrade to Angular 8.0.0 build fails

### ISSUE THREAD

**Issue by opterion** [angular/angular#30734]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 7.2

### Description

 @ngx-kit/core using StaticProvider type from `@angular/core/src/di/provider`. It's not exported anymore. https://angular.io/api/core/StaticProvider

## 🔬 Minimal Reproduction

 Update project with ngx-kit to Angular 8.0.0 and run build

## 🔥 Exception or Error
<pre><code>

During the build:
ERROR in node_modules/@ngx-kit/core/src/kit-overlay/kit-overlay.service.d.ts(2,32): error TS2307: Cannot find module '@angular/core/src/di/provider'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.0
Node: 12.3.1
OS: darwin x64
Angular: 8.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.800.0
@angular-devkit/build-angular              0.800.0
@angular-devkit/build-optimizer            0.800.0
@angular-devkit/build-webpack              0.800.0
@angular-devkit/core                       8.0.0
@angular-devkit/schematics                 8.0.0
@ngtools/webpack                           8.0.0
@nguniversal/common                        7.1.0
@nguniversal/express-engine                7.1.0
@nguniversal/module-map-ngfactory-loader   7.1.0
@schematics/angular                        8.0.0
@schematics/update                         0.800.0
rxjs                                       6.5.2
typescript                                 3.4.5
webpack                                    4.30.0

</code></pre>

**Anything else relevant?**

**Comment by opterion** [comment]
Is StaticProvider now deprecated type | should be imported elsewhere or it's a regression?

**Comment by JoostK** [comment]
Hi @opterion. Thanks for reporting this issue. Unfortunately, this issue is because of an import in `@ngx-kit/core` from an internal location within the `@angular/core` package. Those so-called *deep imports* are not considered public API; the file structure within a package can change at any point. That does not mean however that `StaticProvider` itself is no longer public, it's just that it can't be found in its previous location internally. Instead, it should be imported from the package's index as follows:

```typescript
import { StaticProvider } from '@angular/core';
```

I would suggest you to report the issue with `@ngx-core` so they can correct the import on their side.

**Comment by opterion** [comment]
Already reported to ngx-kit! Thanks a lot!
