### ISSUE TITLE
ng.probe is not a function

### ISSUE THREAD

**Issue by AndonMitev** [angular/angular#30737]
# 🐞 bug report
### Description

Hello i update my cli and core to v 8.0.0. After this I init my new application and set Ivy to true. When i type npm start/ng serve to run and open console i see following error: **"Uncaught TypeError: ng.probe is not a function"**

## 🌍  Your Environment
My envoirment is set to development

**Angular Version:**
![image](https://user-images.githubusercontent.com/32274987/58589626-ff20e180-826a-11e9-8c0c-3f88aaefad6b.png)

**Anything else relevant?**
Here i apply img to the issue 
![image](https://user-images.githubusercontent.com/32274987/58589676-14960b80-826b-11e9-8c6d-adb1f141cef7.png)

**Comment by vdumbrav** [comment]
I still have this issue

https://i.ibb.co/d26sssM/Screenshot-from-2019-05-31-17-33-46.png

**Comment by vdumbrav** [comment]
@AndonMitev Do you have Augury (Chrome Extension for Angular) ?

https://github.com/rangle/augury/issues/714

**Comment by sod** [comment]
Yes, augury assumes angular dev mode is active if `window.ng` exists, but ivy doesn't export probe right now

![image](https://user-images.githubusercontent.com/905328/58716426-49b87000-83c9-11e9-8e58-5255356a39fc.png)

**Comment by AndonMitev** [comment]
Yes i have augury but there were no problem until now with it

**Comment by trotyl** [comment]
@AndonMitev No, Ivy by design have a different set of debugging APIs, it's up to Augury to add support for Ivy.

**Comment by AndonMitev** [comment]
Aww gotchta can u give me some reference to articles / tools for these debugging API's

**Comment by trotyl** [comment]
> some reference to articles / tools for these debugging API's

No, I don't think there're any useful article nor do I think it can be considered stable.

For learning purpose you can check the [source code](https://github.com/angular/angular/blob/master/packages/core/src/render3/debug.ts) or some [dev doc](https://github.com/angular/angular/blob/master/packages/core/src/render3/VIEW_DATA.md), but don't be upset when finding it hard to understand. The raw data is directly added to the element and will be something looks like:

![image](https://user-images.githubusercontent.com/6059170/58745137-952d5580-847f-11e9-8840-cdfc10002188.png)

**Comment by AndonMitev** [comment]
Yoo thanks a lot bro!

**Comment by kara** [comment]
@AndonMitev As @trotyl mentioned, we do have separate debugging APIs for Ivy that Augury should use. Once we've finished polishing them / finalizing names, we should have documentation written so you don't have to read the source.
