### ISSUE TITLE
Is use ObservableWrapper the best way?

### ISSUE THREAD

**Issue by danicomas** [angular/angular#3074]
I had this in version 2.0.0-alpha.28:

myService.js
```js
getUser() {
		return this.http.get(this.AppConfig.apiUrl + '/users/danicomas').map(res => res.json());
  }
```
myComponents.js
```js
myService.getUser().subscribe(response => this.data = response);
```

And now I have this in 2.0.0-alpha.31:

myService.js
```js
getUser() {
		return this.http.get(this.AppConfig.apiUrl + '/users/danicomas');
  }
```

myComponents.js
```js
ObservableWrapper.subscribe(myService.getUser(), response => this.data = response.json());
```

Am I doing it well with the new version? And what type of advantage has this new way? I need to have ObservableWrapper in every component :S   @btford @jeffbcross @mhevery

**Comment by mhevery** [comment]
`ObservableWrapper` is an internal API which should not be used by application. It is needed to create a facade between the differences of JS and Dart.

Use direct APIs.

**Comment by danicomas** [comment]
@mhevery Is possible I have to use the ObservableWrapper due this commit?https://github.com/angular/angular/commit/34eaf65a79b2f43eccff8e88fb3b799d5e0906a0

    "This is temporary, until issue #2794 is resolved, when Observables will
    again be returned directly from Http class methods."

**Comment by jeffbcross** [comment]
Your best best in JS for now is to call toRx() on the Observable returned
from Http, which will give you an RxJS Subject to subscribe to. I'm
actively working on removing this step, as we work on getting rid of our
Observable facade.

The ObservableWrapper's only purpose is to have a JS-and-Dart-friendly
solution with the same source code.

On Wed, Jul 15, 2015 at 1:55 PM, Daniel Comas Fernández <
notifications@github.com> wrote:

> @mhevery <https://github.com/mhevery> Is possible I have to use the
> ObservableWrapper due this commit?34eaf65
> <https://github.com/angular/angular/commit/34eaf65a79b2f43eccff8e88fb3b799d5e0906a0>
>
> "This is temporary, until issue #2794 is resolved, when Observables will
> again be returned directly from Http class methods."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/angular/issues/3074#issuecomment-121744526>.
>



-- 

Jeff Cross | Software Engineer | crossj@google.com

**Comment by danicomas** [comment]
Thanks @jeffbcross
