### ISSUE TITLE
Document for "Angular - Opting into Angular Ivy" is not formatted properly

### ISSUE THREAD

**Issue by rohit2sharma95** [angular/angular#30746]
Document for **Angular Ivy** is not formatted properly. [This URL](https://angular.io/guide/ivy#using-ivy-in-an-existing-project) shows you the unformatted JSON code block at the end of the page. Or you can see [here](https://github.com/angular/angular/blob/master/aio/content/guide/ivy.md) on Github also in the last code block.

**Screenshot of the document**

![Screenshot from 2019-05-30 15-54-50](https://user-images.githubusercontent.com/26922866/58626828-52d70d80-82f3-11e9-90d2-73228dd2d574.png)

I think the above image is missing <code>```</code> at line 15 in its [original document](https://github.com/angular/angular/blob/master/aio/content/guide/ivy.md).

**Comment by trotyl** [comment]
PR already opened at https://github.com/angular/angular/pull/30711.
