### ISSUE TITLE
Angular Update Document

### ISSUE THREAD

**Issue by ravishankardubey** [angular/angular#30749]
# 📚 Docs or angular.io bug report

### Description

 The update.angular.io is not proper

### https://update.angular.io/#7.0:2.0
 When selecting to migrate angular version from 7 to 2, it shows to move dependency from HttpModules and map it to our new HttpClientModule

### Reproduction Steps**

1. https://update.angular.io
2. select angular version from 7 to 2.
3. generate doc will contain the issue

### Expected vs Actual Behavior**

Either it gives proper information or downgrading shouldn't be allowed.

## 📷Screenshot

![image](https://user-images.githubusercontent.com/29010724/58634691-92105900-8309-11e9-9ada-43c90d847917.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by ravishankardubey** [comment]
i found this bug while i was migrating my application to latest version of angular.
I intentionally thought to check the up gradation doc from **angular 7** to **angular 2**

**Comment by ericmartinezr** [comment]
Try also opening this issue over here https://github.com/StephenFluin/angular-update-guide

**Comment by Airblader** [comment]
The website does say that downgrades aren't supported.

**Comment by ravishankardubey** [comment]
Hi,

I saw that it says that it doesn't support,
better we show that message only rather than providing the document in this
case.

It will clear out the confusion.

*Thanks & Regards,*
*Ravi Shankar Dubey*

**Comment by StephenFluin** [comment]
Fixed in https://github.com/StephenFluin/angular-update-guide/commit/ae646bacc7ab82d4c5cd732b5a48d0d03aa69132

**Comment by ravishankardubey** [comment]
Thank you :)
