### ISSUE TITLE
Angular 8 breaks legacy scripts

### ISSUE THREAD

**Issue by mpgo13** [angular/angular#30759]
# 🐞 bug report

### Is this a regression?

Yes, the previous version in which this bug was not present was: Angular 7.x

### Description

Now with differential loading, angular runs all code within es6 modules in modern browsers. This breaks apps using legacy scripts (non es6 modules compatible).

## 🔬 Minimal Reproduction

1. `git clone https://github.com/mpgo13/angular8-breaks-legacyscripts.git`
2. `cd angular8-breaks-legacyscripts`
3. `ng build && (cd dist/repro-app && python -m SimpleHTTPServer)`
4. Browse to http://localhost:8000

Expected result:
* No script error

Actual result:
* Script error

UPDATE: Note: Works with `ng serve` as scripts are not loaded as es6 modules in that case.

**Comment by mpgo13** [comment]
I guess this was not meant to work or supported in Angular < 8.0.0 anyway. Legacy library has been replaced in our project. Feel free to close issue.

**Comment by gkalpak** [comment]
You could also set `target` to `es5` in your `tsconfig.json` file to avoid that.
