### ISSUE TITLE
HttpClient testing guide suggests using deprecated TestBed.get invocation on abstract class HttpTestingController

### ISSUE THREAD

**Issue by textbook** [angular/angular#30750]
# 📚 Docs or angular.io bug report

### Description

The example showing how to set up tests for a component consuming the HttpClient shows the following usage:

```ts
httpTestingController = TestBed.get(HttpTestingController);
```

This is deprecated from v8.0.0 (because the `HttpTestingController` is an abstract class), and therefore throws a warning in the linter; the docs should be updated to use (or at least show an example of) the recommended, compliant code.

### What's the affected URL?**

https://angular.io/guide/http#setup-1

### Reproduction Steps**

Add the minimal `HttpClient` testing example from the documentation:

```ts
describe('HttpClient testing', () => {
  let httpClient: HttpClient;
  let httpTestingController: HttpTestingController;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [ HttpClientTestingModule ]
    });

    // Inject the http service and test controller for each test
    httpClient = TestBed.get(HttpClient);
    httpTestingController = TestBed.get(HttpTestingController);
  });
  /// Tests begin ///
});
```

Run the linter:

```
$ ng lint
Linting "demo"...

...
WARNING: /path/to/app/service.test.ts:16:41 - get is deprecated: from v8.0.0 use Type<T> or InjectionToken<T>

Lint warnings found in the listed files.
```

### Expected vs Actual Behavior**

Expected: docs example uses up-to-date code
Actual: docs example uses deprecated code, leading to a warning

## 🔥 Exception or Error
<pre><code>
WARNING: /path/to/app/service.test.ts:16:41 - get is deprecated: from v8.0.0 use Type<T> or InjectionToken<T>
</code></pre>

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/29905

**Comment by textbook** [comment]
@trotyl I wasn't sure whether it would be a duplicate or not - it's not clear from the other issue whether `TestBed.get(HttpTestingController)` is still going to be the right way to get the controller, or whether the method will require additional type information. At the very least, I'd like to track here that the docs get some kind of update in the interim.

**Comment by trotyl** [comment]
> whether `TestBed.get(HttpTestingController)` is still going to be the right way to get the controller

It is the right way, any class is valid injection token, previously discussed a lot at https://github.com/angular/angular/pull/25222 and https://github.com/angular/angular/issues/26491.

**Comment by textbook** [comment]
@trotyl cool, thanks for the info
