### ISSUE TITLE
Relative links using href within an app cause a cold reload

### ISSUE THREAD

**Issue by richieforeman** [angular/angular#30752]
# 🚀 feature request

### Relevant Package
@angular/router

### Description
Relative a[href] links cause a cold reload in Angular2+ projects.  The Angular2+ solution seems to be to use routerLink -- but this might not be a solution in some legacy environments (namely hybrid AngularJS/Angular2+ apps).

This was brought up before, but I think this is worth addressing or having as an option:
https://github.com/angular/angular/issues/6212

### Describe the solution you'd like
Relative links should be handled by the router.

AngularJS had a bit of functionality called [`rewriteLinks`](https://github.com/angular/angular.js/blob/master/src/ng/location.js#L768).  While this functionality was a little scary, it basically globally re-wrote and captured every "a[href]" on the page and handled it via the router if it was a relative link.

ref: https://github.com/angular/angular.js/blob/master/src/ng/location.js#L768

### Describe alternatives you've considered
In my project I have a global directive that's sugaring all of my a[href] tags.  Here's a very simplified example of the problem/solution:

https://stackblitz.com/edit/angular-router-basic-example-lkw6hp

**Comment by alxhub** [comment]
I don't believe this is a feature we will add - `routerLink` is already well established, and I think your alternative is actually very reasonable for any applications that do care about this.
