### ISSUE TITLE
Unit testing: Can't test child's click handler and parent's @output handler in the same test

### ISSUE THREAD

**Issue by goodmite** [angular/angular#30757]
# 🐞 bug report
I am trying to test the `click` event and `@output` of a dead simple presentational component (```AppComponent```) which is having just a `button#test1`. For testing, I create a new  component `HostComponent` which is having `AppComponent` as a child and check if following two method's are called when `button#test1` is clicked:

1. AppComponent's `chatFeedbackClicked` (which is bound to button click event)
2. HostComponent's `outputHandler` (which is bound to `@output` event `chatMessageFeedback$`)

The problem if I test both of these methods in the same test, the test fails. **But if I test only one of these methods, by commenting either one of the following lines, the test works fine:**

1. LINE: child 1.1 and child 1.2 (test for AppComponent's `chatFeedbackClicked`)
2. LINE: parent 1.1 and parent 1.2 (test for HostComponent's `outputHandler`)

**My test**
```
import {async, ComponentFixture, fakeAsync, flushMicrotasks, TestBed, tick} from '@angular/core/testing';
import {Component, DebugElement} from "@angular/core";
import {AppComponent} from './app.component';
import {By} from '@angular/platform-browser';

function createHostComponent(): ComponentFixture<HostComponent> {
  const fixture = TestBed.createComponent(HostComponent);
  fixture.detectChanges();
  return fixture as ComponentFixture<HostComponent>;
}

fdescribe('AppComponent', () => {
  let component: AppComponent;
  let fixture: ComponentFixture<HostComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [HostComponent, AppComponent],
    })
    // .compileComponents();
  }));

  beforeEach(() => {
    // fixture = TestBed.createComponent(ChatFeedbackComponent);
    fixture = createHostComponent();

  });

  fit('should emit chatMessageFeedback$ true when clicked on like button', fakeAsync(() => {
    const appComponent = fixture.debugElement.query(By.directive(AppComponent)) as DebugElement;
    spyOn(appComponent.componentInstance,'chatFeedbackClicked');//LINE: parent 1.1
    spyOn(fixture.componentInstance,'outputHandler'); //LINE: child 1.1
    fixture.debugElement.nativeElement.querySelector('#test1').click();
    tick(500);
    flushMicrotasks();
    fixture.detectChanges();
    expect(appComponent.componentInstance.chatFeedbackClicked).toHaveBeenCalled();//LINE: parent 1.2
    expect(fixture.componentInstance.outputHandler).toHaveBeenCalledWith(true);//LINE: child 1.2
  }));

});


@Component({selector: 'host-for-test', template: `
    <app-root (chatMessageFeedback$)="outputHandler($event)"></app-root>
  `})
class HostComponent {

  outputHandler(data) {
    alert();
  }
}


```

**AppComponent:**
```
import {Component, EventEmitter, Input, OnInit, Output} from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <button id="test1" (click)="chatFeedbackClicked(true)">Test</button>
  `,
})
export class AppComponent {
  @Output() chatMessageFeedback$ = new EventEmitter();

  chatFeedbackClicked(isFeedbackPositive: boolean) {
    this.chatMessageFeedback$.emit(isFeedbackPositive);
  }
}

```

[stackblitz](https://stackblitz.com/edit/angular-st2x6b?file=src%2Fapp%2Fapp-initial.component.spec.ts)

### Is this a regression?
No

## 🔥 Exception or Error
<pre><code>
AppComponent should emit chatMessageFeedback$ true when clicked on like button
Expected spy outputHandler to have been called with [ true ] but it was never called.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.3.9
Node: 10.14.2
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**

**Comment by trotyl** [comment]
It's expected behavior, you need to understand how Jasmine works. When `spyOn()` a method, the original implementation of that method is not triggered.

And you did exact this:

```typescript
spyOn(appComponent.componentInstance,'chatFeedbackClicked');
```

After that it's only a no-op function and does nothing, which is the guaranteed behavior in Jasmine.

Please refer to [Jasmine docs](https://jasmine.github.io/api/edge/SpyStrategy.html) about how to configure the spying behavior.

**Comment by goodmite** [comment]
Thanks! That solves the issue.

**Comment by alxhub** [comment]
Glad to hear it!
