### ISSUE TITLE
Not found the docs of v7 of Angular in angular.io

### ISSUE THREAD

**Issue by mydaypower1** [angular/angular#30769]
# 📚 Not found the docs of v7 of Angular in angular.io

### Description

 
There are v2, v4, v5, v6, Stable (v8.0.0), But not found v7's docs in angular:
https://angular.io/docs

We plan to use Version 7 of Angular, So want to see the version 7's docs.
(Because of, It seems to that the Angular v7 need to use Node.js version 12 or later, But we have no plan to upgrade Nodejs specially, So just want to use Angular v7)

Could you please let me know why it is not there? Or that means that the Version 7 of Angular is not officially recommended to be used anymore?

### What's the affected URL?**
 https://angular.io/docs

### Reproduction Steps**
 Please see the **Screenshot** below

### Expected vs Actual Behavior**
 
Expected: Want to see the Version 7's docs of Angular in angular.io

Actual Behavior: Can not see the Version 7's docs of Angular in angular.io

## 📷Screenshot

![No-v7docs-2019-05-31_162151](https://user-images.githubusercontent.com/17958268/58692022-453b8980-83c0-11e9-9df9-a36b7bbbed2c.png)

**Comment by gkalpak** [comment]
Thx for pointing it out. We need to things to fix this:

1. Create a corresponding Firebase project and deploy to it.
2. Add v7 to the versions dropdown (this will be fixed by #30775).

##
BTW, I know that the [update instructions][1] mention upgrading to Node.js 12, but this is just a recommendation, not a hard requirement. We should fix the wording, but in the meantime don't let this stop you from using v8 :wink:

[1]: https://update.angular.io/#7.2:8.0

**Comment by mydaypower1** [comment]
@gkalpak, 
Wow, This is great, It is a really quick fixing, Thank you for your help, Awesome.

Btw, A small question, Just you said above, About the Node.js V12: "this is just a recommendation, not a hard requirement. We should fix the wording", But, Currently the "update instructions" still mention upgrading to Node.js 12 and using the words "Make sure", Please see the screenshot below.

![AngularV8-2019-06-01_164317](https://user-images.githubusercontent.com/17958268/58746274-1809dc80-848f-11e9-8dbe-4c0903a6856d.png)



I am not sure which features of Node 12( or later) are using during we are upgrading/using the Angular V8, If it is not, Could the great team please try to fix the wording if possible. Such as the lowest version recommended...
Because of some team from all over the word already noticed the new Angular 8 is a stable version, And try to upgrade...

Anyway, We will try to upgrade from V7 to V8...

Thanks again

**Comment by gkalpak** [comment]
The required Node.js version really boils down to what the Angular CLI needs. Currently, CLI 8.x declares `"node": ">= 10.9.0"` in its [package.json][1], so theoretically, that is the lowest compatible version.

I wouldn't be surprised if you could get by with a lower version, though.
In any case, I'm just guessing here - for an authoritative answer you should ask on the [CLI repo][2].

[1]: https://unpkg.com/@angular/cli@8.0.1/package.json
[2]: https://github.com/angular/angular-cli

**Comment by mydaypower1** [comment]
Thanks for your help, Very appreciated, Got it
