### ISSUE TITLE
Fresh angular 8 project doesn't open in IE 11

### ISSUE THREAD

**Issue by zlepper** [angular/angular#30765]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
Seems to be a problem with the generated project having bad configs

### Is this a regression?
Yes, it worked in Angular 7, i assume it was caused by the differential loading not being build correctly in serve mode

### Description
The application doesn't load in IE, because it is attempting to load ES6 code, incorrectly

## 🔬 Minimal Reproduction
1. Install the angular cli
2. Generate a new project using `ng new fresh`
3. Serve the project using `ng serve`
4. Open `localhost:4200` in IE11. 

-->

## 🔥 Exception or Error
![iexplore_I82S9FMgIg](https://user-images.githubusercontent.com/1499810/58686063-fb31b400-837d-11e9-84f2-bf953e90f8dc.png)

## 🌍  Your Environment

**Angular Version:**
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 8.0.1
Node: 10.15.3
OS: win32 x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

```
**Anything else relevant?**
This is specifically a problem for IE 11, on Windows. 

**Workaround**
Update the browserlist to allow IE 11
Change the tsconfig target to es5. 
This has the downside that all browsers then consume es5, however at least IE works.

**Comment by trotyl** [comment]
> Fresh angular 8 project doesn't open in IE 11

Of course it won't work, as explicitly configured as so:

```
> 0.5%
last 2 versions
Firefox ESR
not dead
not IE 9-11 # For IE 9-11 support, remove 'not'.
```

https://github.com/angular/angular-cli/blob/6ec09919b5c2695dee784ce0c3accee7f9754bb0/packages/schematics/angular/application/files/browserslist.template#L12

**Comment by zlepper** [comment]
Even with browserlist corrected, serve mode still tries to load ES6 modules in IE.

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/14455

**Comment by zlepper** [comment]
I really don't like the workaround there personally, but will take it for now, and move any discussion to that issue.
