### ISSUE TITLE
creating new app with @angular/bazel collection produces error due to import of non existing ngfactory file

### ISSUE THREAD

**Issue by blackholegalaxy** [angular/angular#30779]
# 🐞 bug report

### Affected Package

 The issue is caused by package angular/bazel` and CLI schematic.

### Description

 A clear and concise description of the problem...

Creating a new app using `@angular/cli` with `--collection @angular/bazel`, or adding `@angular/bazel` to existing project creates errored files:

 - `main.dev.ts`
 - `main.prod.ts`

Example of `main.dev.ts`:
```
import {platformBrowser} from '@angular/platform-browser';
import {AppModuleNgFactory} from './app/app.module.ngfactory';

platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
```

Both files import `import {AppModuleNgFactory} from './app/app.module.ngfactory';` but `app.module.ngfactory` file doesn't exist and was not created.

## 🔬 Minimal Reproduction

 generated app just commited there, with no modification: https://github.com/blackholegalaxy/bugreport-bazel-cli

## 🔥 Exception or Error
<pre><code>ng build
INFO: Analyzed target //src:prodapp (4 packages loaded, 63 targets configured).
INFO: Found 1 target...
ERROR: /Users/user/dev/dummyApp/src/BUILD.bazel:15:1: Compiling Angular templates (ngc) //src:src failed (Exit 1)

Asset not found:
  ./app.component.sass
Check that it's included in the `assets` attribute of the `ng_module` rule.

src/main.dev.ts(2,34): error TS2307: Cannot find module './app/app.module.ngfactory'.
src/main.prod.ts(3,34): error TS2307: Cannot find module './app/app.module.ngfactory'.

Target //src:prodapp failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5.557s, Critical Path: 0.81s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
/Users/user/dev/dummyApp/node_modules/@bazel/bazel-darwin_x64/bazel-0.25.1-darwin-x86_64 failed with code 1.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 8.0.1
Node: 10.15.3
OS: darwin x64
Angular: 8.0.0
... animations, bazel, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@bazel/bazel                      0.25.1
@bazel/bazel-darwin_x64           0.25.1
@bazel/ibazel                     v0.10.3
@bazel/karma                      0.27.12
@bazel/typescript                 0.27.12
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0</code></pre>

**Comment by marct83** [comment]
I am having the same issue.

**Comment by bleuscyther** [comment]
What i saw is that it does not work on projects with the Ivy setup. 
I disabled Ivy because of many bugs that are being fixed but the setup in the other files is here.

WWhen activating BAzel it generated two files: 

- **main.dev.ts**
- **main.prod.ts**

and it kpet the old file: **main.ts**

I took the code from **main.ts** and put it in both files while removing the unnecessary code ( if in prod ...)

example,

```typescript
/** main.ts  *//
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';
import 'hammerjs';

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
    .then(() => {
      if ('serviceWorker' in navigator && environment.production) {
        navigator.serviceWorker.register('./ngsw-worker.js');
      }
    })
  .catch(err => console.log(err));

```

becomes
``` typescript

/**main.prod.ts **/
import {enableProdMode} from '@angular/core';

import {AppModule} from './app/app.module';
import 'hammerjs';
import {platformBrowser} from "@angular/platform-browser";

enableProdMode();

platformBrowser().bootstrapModule(AppModule)
  .then(() => {
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('./ngsw-worker.js');
    }
  })
  .catch(err => console.log(err));

 

```

**Comment by bleuscyther** [comment]
Check this link : https://blog.ninja-squad.com/2019/05/14/build-your-angular-application-with-bazel/

**Comment by blackholegalaxy** [comment]
@bleuscyther  if you read the issue, you will see the command I use is exactly the one in this blog. I use bazel schematic on a brand new project built with something like `ng new bazel-project --defaults --collection=@angular/bazel` and just stopping here, doing nothing more, it fails.

**Comment by AndrewKushnir** [comment]
Hi,

Bazel builder and schematics were deprecated, so I'm closing this ticket. You can find more information about this on the [Deprecated APIs and features page](https://angular.io/guide/deprecations#bazel-builder-and-schematics) and in the [migration guide](https://github.com/angular/angular/blob/master/packages/bazel/src/schematics/README.md).

Thank you.
