### ISSUE TITLE
RouterLink missing queryParams

### ISSUE THREAD

**Issue by agustins** [angular/angular#30787]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?

 Yes, the previous version in which this bug was not present was: @angular/router 7.0.0

### Description

queryParams are missing when navigate or routerLink was executed.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-andycf

on navigate to a hero detail queryParam was supposed to be in console bug.

## 🔥 Exception or Error

queryParams are not propagated on navigation.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0
Node: 11.10.0
OS: win32 x64
Angular: 8.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@ngtools/webpack                  8.0.0
@schematics/angular               8.0.0
@schematics/update                0.800.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by sod** [comment]
queryParams is everything thats behind `?` like https://angular-andycf.stackblitz.io/superhero/13?foo=bar

Everything before `?` is `params` or `paramMap`

https://angular-eyk864.stackblitz.io/superhero/13;lorem=ipsum?foo=bar

**Comment by agustins** [comment]
> queryParams is everything thats behind `?` like https://angular-andycf.stackblitz.io/superhero/13?foo=bar
> 
> Everything before `?` is `params` or `paramMap`
> 
> https://angular-eyk864.stackblitz.io/superhero/13;lorem=ipsum?foo=bar

Yes I know. Sorry but I dont understand the poing of tour comment. 
Look at the example, I'm setting queryParams in routerLink directive and I dont receive params in the queryParamMap subscription...

**Comment by trotyl** [comment]
@agustins Please provide a dedicated example without any code from the tutorial, it's not clear where your change is.

**Comment by agustins** [comment]
Done, I just remove lot of code from tutorial.

The minimal step to reproduce are at hero-list.component.html

```
 <a [routerLink]="['/hero', hero.id]" [queryParams]="{debug: true}" queryParamsHandling>
   <span class="badge">{{ hero.id }}</span>{{ hero.name }}
 </a>
```
and hero-detail.component.ts:

```
ngOnInit() {
    this.route.queryParamMap.subscribe(
      p => console.log(p)
    );
  }
```

**Comment by trotyl** [comment]
@agustins

> The minimal steps to reproduce are at hero-list.component.html

That's why it has the problem, because the tutorial doesn't have a clean router config.
The configuration is:

```typescript
{ path: 'heroes', redirectTo: '/superheroes' },
{ path: 'hero/:id', redirectTo: '/superhero/:id' }, // <-- Your routerLink
{ path: 'superheroes',  component: ... },
{ path: 'superhero/:id', component: ... }  // <-- Your target component
```

The tutorial is performing a redirect deliberately for demonstrating this functionality, and query params are not preserved during this redirect as not configured to do so. Just change the `routerLink` to your real target will solve the issue.

**Comment by agustins** [comment]
@trotyl thank you very much. But there are not any form to preserve queryParams in this case of redirection?

**Comment by trotyl** [comment]
> But there are not any form to preserve queryParams in this case of redirection?

I think that's what being requested at https://github.com/angular/angular/issues/30686
