### ISSUE TITLE
TypeError: this._validator is not a function

### ISSUE THREAD

**Issue by nathanrobinson** [angular/angular#30784]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/forms in combination with AOT compilation

### Is this a regression?

Yes, the previous version in which this bug was not present was: Angular 8 without AOT.

### Description

When binding dynamic validator values to an input via `[maxlength]="maxLength"` if AOT compilation is enabled the validation is attempted before the validator is created.
An error is logged to the console: `ERROR TypeError: this._validator is not a function`.

## 🔬 Minimal Reproduction
https://github.com/nathanrobinson/angular_ivy_aot_validation_error

## 🔥 Exception or Error
<pre><code>
ERROR TypeError: this._validator is not a function
    at MinLengthValidator.validate (VM1588 vendor.js:67057)
    at VM1588 vendor.js:60658
    at VM1588 vendor.js:60606
    at Array.map (<anonymous>)
    at _executeValidators (VM1588 vendor.js:60602)
    at VM1588 vendor.js:60547
    at VM1588 vendor.js:60606
    at Array.map (<anonymous>)
    at _executeValidators (VM1588 vendor.js:60602)
    at FormControl.validator (VM1588 vendor.js:60547)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0                                             
Node: 10.14.2                                                  
OS: win32 x64                                                  
Angular: 8.0.0                                                 
... animations, cdk, cli, common, compiler, compiler-cli, core 
... forms, language-service, material, platform-browser        
... platform-browser-dynamic, router                           
                                                               
Package                           Version                      
-----------------------------------------------------------    
@angular-devkit/architect         0.800.0                      
@angular-devkit/build-angular     0.800.0                      
@angular-devkit/build-optimizer   0.800.0                      
@angular-devkit/build-webpack     0.800.0                      
@angular-devkit/core              8.0.0                        
@angular-devkit/schematics        8.0.0                        
@ngtools/webpack                  8.0.0                        
@schematics/angular               8.0.0                        
@schematics/update                0.800.0                      
rxjs                              6.4.0                        
typescript                        3.5.1                        
webpack                           4.30.0                       

</code></pre>

**Anything else relevant?**
The OnChange loop seems to call validate before setting the attributes, and then call it again after setting the attributes.
There are three instances in https://github.com/angular/angular/blob/master/packages/forms/src/directives/validators.ts where `this._validator` is called without checking if it is null. This could be resolved for example by rewriting 
```
validate(control: AbstractControl): ValidationErrors|null {
    return this.minlength == null ? null : this._validator(control);
  }
```
 as
```
validate(control: AbstractControl): ValidationErrors|null {
    return this.minlength == null || !this._validator ? null : this._validator(control);
  }
```

**Comment by kara** [comment]
@nathanrobinson Can you add a reproduction that doesn't use Material's mat-form-field? As it is, it's difficult to narrow down what's going on because mat-form-field has its own logic.

**Comment by nathanrobinson** [comment]
> @nathanrobinson Can you add a reproduction that doesn't use Material's mat-form-field? As it is, it's difficult to narrow down what's going on because mat-form-field has its own logic.

@kara I just updated the [repo](https://github.com/nathanrobinson/angular_ivy_aot_validation_error) with @angular/material removed. It seems to be throwing the same error with the same stack.

**Comment by santoshyadav198613** [comment]
Hi @nathanrobinson ,

I was able to run the code without the error, which you mentioned.

Only error which i got was ExpressionChangedAfterItHasBeenCheckedError.

**Comment by nathanrobinson** [comment]
@santoshyadav198613 were you using `ng serve` with AOT enabled? What OS/node/npm/yarn versions were you using?

**Comment by nathanrobinson** [comment]
Besides the version mentioned in the issue, I've pulled this repository and reproduced in:
```Angular CLI: 8.0.0                                               
Node: 10.9.0                                                     
OS: linux x64                                                    
Angular: 8.0.0                                                   
... animations, cdk, cli, common, compiler, compiler-cli, core   
... forms, language-service, platform-browser                    
... platform-browser-dynamic, router                             
                                                                 
Package                           Version                        
-----------------------------------------------------------      
@angular-devkit/architect         0.800.0                        
@angular-devkit/build-angular     0.800.0                        
@angular-devkit/build-optimizer   0.800.0                        
@angular-devkit/build-webpack     0.800.0                        
@angular-devkit/core              8.0.0                          
@angular-devkit/schematics        8.0.0                          
@ngtools/webpack                  8.0.0                          
@schematics/angular               8.0.0                          
@schematics/update                0.800.0                        
rxjs                              6.4.0                          
typescript                        3.5.1                          
webpack                           4.30.0                         
                                                                 ```

**Comment by santoshyadav198613** [comment]
Hi @nathanrobinson,

I went through your code, actually the first time I verified it on stackblitz which was working.
I downloaded your code locally and I do confirm the error you mentioned is there.

But This is what I noticed was incorrect, you have used the reactive form to create the form, but trying to use the template-driven syntax for validation. Generally, we don't do it. 

Here is the reason why :

**Reactive forms** are synchronous (as you create controls from your code) In reactive forms, you create the entire form control tree in code. You can immediately update a value or drill down through the descendants of the parent form because all controls are always available.

**template-driven** forms are asynchronous (as it delegates the task of creation of control) Template-driven forms delegate creation of their form controls to directives. To avoid "changed after checked" errors, these directives take more than one cycle to build the entire control tree. That means you must wait for a tick before manipulating any of the controls from within the component class.

You will get a similar error if you try to apply a custom validation on template driven forms scenario.
As the validator will be called before your form controls are initialized and we need to check if control is not undefined or null.

Also, remember the values are type safe, it means we can not pass null or undefined.

Let me know if you still have any doubts, so we can discuss.

**Comment by nathanrobinson** [comment]
Thanks for the explanation, @santoshyadav198613. Is it fair to say that reactive forms won't be able to use the browser to enforce maxLength via the `maxlength` attribute, then?

**Comment by santoshyadav198613** [comment]
Reactive forms already provide Validators class to handle this.

Use below syntax :
import { FormControl, Validators } from '@angular/forms';
const formControl = new FormControl('foo', Validators.minLength(10));

**Comment by nathanrobinson** [comment]
I updated the [repo](https://github.com/nathanrobinson/angular_ivy_aot_validation_error) to only use template driven forms (removed references to `FormGroup` and `FormControl`, and it's still erroring. 

The issue appears when binding to validation properties in a sub-component. 

So: 
```
<form>
            <input placeholder="Enter the first value"
                   name="text1"
                   [(ngModel)]="textValue"
                   type="text"
                   minlength="5"
                   maxlength="15"
                   pattern="[\w\d]*"
                   required />
</form>
```
and
```
<form>
       <input placeholder="Enter the second value"
                   name="text2"
                   [(ngModel)]="textValue2"
                   type="text"
                   [minlength]="minLength"
                   [maxlength]="maxLength"
                   [pattern]="pattern"
                   [required]="required" />
</form>
```
are fine. But 
```
<form>
    <app-form-input placeholder="Enter the third value"
                            name="text3"
                            [(value)]="textValue3"></app-form-input>
</form>
```
when `formInputComponent` contains 
```
<input [placeholder]="placeholder"
       [name]="name"
       [(ngModel)]="value"
       (ngModelChange)="valueChange.emit($event)"
       type="text"
       [required]="required"
       [minlength]="minLength"
       [maxlength]="maxLength"
       [pattern]="pattern" />
```
causes the error. 

I prefer to use the template-driven validation attributes because the browser enforces `maxlength` by truncating all input after the max is reached.

**Comment by santoshyadav198613** [comment]
Sure @nathanrobinson ,

Let me check once.

**Comment by jeroenvheel** [comment]
Hi I also get this error when using reactive forms and the maxlength Validator
Angular version is 8.0.1 with ivy
Without everything is fine

**Comment by vascofernandes** [comment]
I have this bug as well.

**Comment by mardikacom** [comment]
I get same error after upgrade to angular 9.
this is my formcontrol validator
it working fine on ng serve but after build it with aot the error appear

TypeError: this._validator is not a function

this is my code
`finalCloseFC          = new FormControl('', Validators.required);`

**Comment by igorkemack** [comment]
I have same error, angular 9.0.0-next.8

**Comment by fluidsonic** [comment]
Same here. But in my case it's the [PatternValidator](https://github.com/angular/angular/blob/8042140742708951f118501dc75a51b029513b1f/packages/forms/src/directives/validators.ts#L568). The `pattern` attribute is static though.
`PatternValidator`'s own `ngOnChanges()` isn't called before `validate()`.

The stacktrace goes back to `ngOnChanges()` for the input because `model` has changed:
```js
{
   model: SimpleChange,
   currentValue: '',
   firstChange: true,
   previousValue: undefined
}
```

```html
<input
	#input
	autocomplete="off"
	class="valueInput"
	inputmode="numeric"
	[max]="maximum"
	[maxLength]="_maximumLength"
	[min]="minimum"
	[ngModel]="value.input.toString()"
	*ngSwitchCase="'number'"
	pattern="[0-9]*"
	placeholder="Type your answer here…"
	tabindex="-1"
	type="text"
	(focus)="onValueInputFocus()"
	(keydown)="onValueInputKeydown($event)"
	(keypress)="onNumberValueInputKeypress($event)"
	(ngModelChange)="onValueInputChange($event)"
>
```

```
[PatternValidator.]validate (vendor.js:71056)
(anonymous) (vendor.js:64303)
(anonymous) (vendor.js:64251)
_executeValidators (vendor.js:64247)
(anonymous) (vendor.js:64189)
(anonymous) (vendor.js:64251)
_executeValidators (vendor.js:64247)
(anonymous) (vendor.js:64189)
_runValidator (vendor.js:66646)
updateValueAndValidity (vendor.js:66607)
_setUpStandalone (vendor.js:69128)
_setUpControl (vendor.js:69102)
[NgModel of <input>.]ngOnChanges (vendor.js:69038)
wrapOnChangesHook_inPreviousChangesStorage (vendor.js:44397)
callHook (vendor.js:28401)
callHooks (vendor.js:28361)
executeInitAndCheckHooks (vendor.js:28302)
refreshView (vendor.js:32221)
refreshDynamicEmbeddedViews (vendor.js:33469)
refreshView (vendor.js:32226)
refreshComponent (vendor.js:33492)
refreshChildComponents (vendor.js:31936)
refreshView (vendor.js:32255)
refreshComponent (vendor.js:33492)
refreshChildComponents (vendor.js:31936)
refreshView (vendor.js:32255)
refreshDynamicEmbeddedViews (vendor.js:33469)
refreshView (vendor.js:32226)
refreshComponent (vendor.js:33492)
refreshChildComponents (vendor.js:31936)
refreshView (vendor.js:32255)
renderComponentOrTemplate (vendor.js:32317)
tickRootContext (vendor.js:33656)
detectChangesInRootView (vendor.js:33696)
detectChanges (vendor.js:35203)
tick (vendor.js:57998)
…
```

```
Angular CLI: 9.0.0-next.7
Node: 12.8.1
OS: darwin x64
Angular: 9.0.0-next.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.7
@angular-devkit/build-angular     0.900.0-next.7
@angular-devkit/build-optimizer   0.900.0-next.7
@angular-devkit/build-webpack     0.900.0-next.7
@angular-devkit/core              9.0.0-next.7
@angular-devkit/schematics        9.0.0-next.7
@angular/cli                      9.0.0-next.7
@ngtools/webpack                  9.0.0-next.7
@nguniversal/common               9.0.0-next.2
@schematics/angular               9.0.0-next.7
@schematics/update                0.900.0-next.7
rxjs                              7.0.0-alpha.0
typescript                        3.5.3
webpack                           4.41.0
```

**Comment by fluidsonic** [comment]
My workaround, to be executed before bootstrapping the app module:

```ts
function fixValidator(validator: any) {
	validator.prototype.validate = (function(original: any) {
		return function(this: PatternValidator) {
			if (!this['_validator'])
				return null

			return original.apply(this, arguments)
		}
	})(validator.prototype.validate)
}

fixValidator(MaxLengthValidator)
fixValidator(MinLengthValidator)
fixValidator(PatternValidator)
```

It won't fix the other error though which is only raised in dev mode:
>ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: ''.

**Comment by tlaverdure** [comment]
I'm experiencing the same issue with Ivy. Only solution at this point seems to not use `minlength` or `maxlength` until this bug is fixed.

**Comment by DibyodyutiMondal** [comment]
Angular version: 9 with Ivy
Using 
```
<input matInput formControlName="someInput" maxlength="50" />
```

Is not working. I was expecting it to use the native browser behaviour, but it seems that angular resolves the 'maxlength' attribute to an instance of MaxLengthValidator.

So, Instead of using `maxlength`, I used `maxLength` in the html instead, and it worked. This is either because 
- Angular decided to ignore it as `maxLength` is unrecognised, and then the browser corrected the 'typo' or;
- The html->maxlength attribute is angular->maxLength property

Can someone please clear my doubts on this, and explain why this is working like this?

**Comment by davidpolo** [comment]
I have same error, angular 9.0.0-next.11

Workaround: Use max**L**ength (**L** in capital letter) instead max**l**ength.

**Comment by sod** [comment]
Easiest reproduction is, create a fresh project with angular cli, add `FormsModule` and replace the entire app template with just `<input ngModel [maxlength]="'3'">` ... that already throws.

![image](https://user-images.githubusercontent.com/905328/67151054-74e02500-f2c0-11e9-9711-cedccf67642a.png)

**Comment by magnattic** [comment]
This issue has been around for months and is now keeping us from switching to Ivy. Could someone take a look at the PR please? :)

**Comment by JoshuvaGeorge03** [comment]
any update on this issue? I was having this error, only happen with aot compilation.

`TypeError: this._validator is not a function. (In 'this._validator(t)', 'this._validator' is undefined)
validate — main.45ced4ef4300373ea46e.js:1:673556
map
(anonymous function) — main.45ced4ef4300373ea46e.js:1:631280
map
(anonymous function) — main.45ced4ef4300373ea46e.js:1:631280
updateValueAndValidity — main.45ced4ef4300373ea46e.js:1:650951
setValue — main.45ced4ef4300373ea46e.js:1:654775
X — main.45ced4ef4300373ea46e.js:1:646153
(anonymous function) — main.45ced4ef4300373ea46e.js:1:645377
handleChangeEvent — main.45ced4ef4300373ea46e.js:1:927465
_handleInputEvent — main.45ced4ef4300373ea46e.js:1:930073
Vc — main.45ced4ef4300373ea46e.js:1:766548
o — main.45ced4ef4300373ea46e.js:1:766687
(anonymous function) — main.45ced4ef4300373ea46e.js:1:466056
onInvokeTask — main.45ced4ef4300373ea46e.js:1:834671
runTask — polyfills.d23673a17e3e2c8fc99f.js:1:2982
invokeTask — polyfills.d23673a17e3e2c8fc99f.js:1:8880
_ — polyfills.d23673a17e3e2c8fc99f.js:1:22128
m — polyfills.d23673a17e3e2c8fc99f.js:1:22353
dispatchEvent
emit
runTask — polyfills.d23673a17e3e2c8fc99f.js:1:2982
invokeTask — polyfills.d23673a17e3e2c8fc99f.js:1:8880
(anonymous function) — polyfills.d23673a17e3e2c8fc99f.js:1:38552`

**Comment by julianobrasil** [comment]
While @trotyl PR is waiting, I've noticed that `FormBuilder` seems to bring this issue up:

```html
<form [formGroup]="_form">
    <input formControlName="x" maxlength="5">
</form>
```

```ts
this._form = this._formBuilder.group({x: null});
```

The same form doesn't throw any error if you use it like this:

```ts
this._form = new FormGroup({x: new FormControl(null)});
```

**Comment by buu700** [comment]
For the time being (with 9.0.0-rc.0), applying #33403 this way seems to be an effective workaround: `echo 'NzUwYTc1MQo+ICAgICAgICAgICAgIHRoaXMuX3NlbGVjdG9ySW5kZXhNYXAgPSBuZXcgTWFwKCk7Cjc3OGE3ODAsNzgxCj4gICAgICAgICAgICAgdGhpcy5fc2VsZWN0b3JJbmRleE1hcC5zZXQoY3NzU2VsZWN0b3IsIHRoaXMuX3NlbGVjdG9ySW5kZXhNYXAuc2l6ZSk7Cj4gCjg1Nyw4NThjODYwLDg2NQo8ICAgICAgICAgICAgIHJlc3VsdCA9IHRoaXMuX21hdGNoVGVybWluYWwodGhpcy5fZWxlbWVudE1hcCwgZWxlbWVudCwgY3NzU2VsZWN0b3IsIG1hdGNoZWRDYWxsYmFjaykgfHwgcmVzdWx0Owo8ICAgICAgICAgICAgIHJlc3VsdCA9IHRoaXMuX21hdGNoUGFydGlhbCh0aGlzLl9lbGVtZW50UGFydGlhbE1hcCwgZWxlbWVudCwgY3NzU2VsZWN0b3IsIG1hdGNoZWRDYWxsYmFjaykgfHwKLS0tCj4gCj4gICAgICAgICAgICAgdmFyIHNlbGVjdG9yTWF0Y2hDYWxsYmFjayA9IG1hdGNoZWRDYWxsYmFjayAhPSBudWxsID8gKGMsIGEpID0+IHsKPiAgICAgICAgICAgICAgICAgbWF0Y2hlZENhbGxiYWNrKGMsIGEsIHRoaXMuX3NlbGVjdG9ySW5kZXhNYXAuZ2V0KGMpKTsKPiAgICAgICAgICAgICB9IDogbnVsbDsKPiAKPiAgICAgICAgICAgICByZXN1bHQgPSB0aGlzLl9tYXRjaFRlcm1pbmFsKHRoaXMuX2VsZW1lbnRNYXAsIGVsZW1lbnQsIGNzc1NlbGVjdG9yLCBzZWxlY3Rvck1hdGNoQ2FsbGJhY2spIHx8Cjg1OWE4NjcsODcwCj4gICAgICAgICAgICAgcmVzdWx0ID0KPiAgICAgICAgICAgICB0aGlzLl9tYXRjaFBhcnRpYWwodGhpcy5fZWxlbWVudFBhcnRpYWxNYXAsIGVsZW1lbnQsIGNzc1NlbGVjdG9yLCBzZWxlY3Rvck1hdGNoQ2FsbGJhY2spIHx8Cj4gICAgICAgICAgICAgcmVzdWx0Owo+IAo4NjQsODY2Yzg3NSw4NzgKPCAgICAgICAgICAgICAgICAgICAgICAgICB0aGlzLl9tYXRjaFRlcm1pbmFsKHRoaXMuX2NsYXNzTWFwLCBjbGFzc05hbWUsIGNzc1NlbGVjdG9yLCBtYXRjaGVkQ2FsbGJhY2spIHx8IHJlc3VsdDsKPCAgICAgICAgICAgICAgICAgICAgIHJlc3VsdCA9CjwgICAgICAgICAgICAgICAgICAgICAgICAgdGhpcy5fbWF0Y2hQYXJ0aWFsKHRoaXMuX2NsYXNzUGFydGlhbE1hcCwgY2xhc3NOYW1lLCBjc3NTZWxlY3RvciwgbWF0Y2hlZENhbGxiYWNrKSB8fAotLS0KPiAgICAgICAgICAgICAgICAgICAgICAgICB0aGlzLl9tYXRjaFRlcm1pbmFsKHRoaXMuX2NsYXNzTWFwLCBjbGFzc05hbWUsIGNzc1NlbGVjdG9yLCBzZWxlY3Rvck1hdGNoQ2FsbGJhY2spIHx8Cj4gICAgICAgICAgICAgICAgICAgICAgICAgcmVzdWx0Owo+ICAgICAgICAgICAgICAgICAgICAgcmVzdWx0ID0gdGhpcy5fbWF0Y2hQYXJ0aWFsKAo+ICAgICAgICAgICAgICAgICAgICAgICAgIHRoaXMuX2NsYXNzUGFydGlhbE1hcCwgY2xhc3NOYW1lLCBjc3NTZWxlY3Rvciwgc2VsZWN0b3JNYXRjaENhbGxiYWNrKSB8fAo4NzdjODg5CjwgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHRoaXMuX21hdGNoVGVybWluYWwodGVybWluYWxWYWx1ZXNNYXAsICcnLCBjc3NTZWxlY3RvciwgbWF0Y2hlZENhbGxiYWNrKSB8fCByZXN1bHQ7Ci0tLQo+ICAgICAgICAgICAgICAgICAgICAgICAgICAgICB0aGlzLl9tYXRjaFRlcm1pbmFsKHRlcm1pbmFsVmFsdWVzTWFwLCAnJywgY3NzU2VsZWN0b3IsIHNlbGVjdG9yTWF0Y2hDYWxsYmFjaykgfHwgcmVzdWx0Owo4ODBjODkyCjwgICAgICAgICAgICAgICAgICAgICAgICAgdGhpcy5fbWF0Y2hUZXJtaW5hbCh0ZXJtaW5hbFZhbHVlc01hcCwgdmFsdWUsIGNzc1NlbGVjdG9yLCBtYXRjaGVkQ2FsbGJhY2spIHx8IHJlc3VsdDsKLS0tCj4gICAgICAgICAgICAgICAgICAgICAgICAgdGhpcy5fbWF0Y2hUZXJtaW5hbCh0ZXJtaW5hbFZhbHVlc01hcCwgdmFsdWUsIGNzc1NlbGVjdG9yLCBzZWxlY3Rvck1hdGNoQ2FsbGJhY2spIHx8IHJlc3VsdDsKODgzYzg5NQo8ICAgICAgICAgICAgICAgICAgICAgICAgIHJlc3VsdCA9IHRoaXMuX21hdGNoUGFydGlhbChwYXJ0aWFsVmFsdWVzTWFwLCAnJywgY3NzU2VsZWN0b3IsIG1hdGNoZWRDYWxsYmFjaykgfHwgcmVzdWx0OwotLS0KPiAgICAgICAgICAgICAgICAgICAgICAgICByZXN1bHQgPSB0aGlzLl9tYXRjaFBhcnRpYWwocGFydGlhbFZhbHVlc01hcCwgJycsIGNzc1NlbGVjdG9yLCBzZWxlY3Rvck1hdGNoQ2FsbGJhY2spIHx8IHJlc3VsdDsKODg2Yzg5OAo8ICAgICAgICAgICAgICAgICAgICAgICAgIHRoaXMuX21hdGNoUGFydGlhbChwYXJ0aWFsVmFsdWVzTWFwLCB2YWx1ZSwgY3NzU2VsZWN0b3IsIG1hdGNoZWRDYWxsYmFjaykgfHwgcmVzdWx0OwotLS0KPiAgICAgICAgICAgICAgICAgICAgICAgICB0aGlzLl9tYXRjaFBhcnRpYWwocGFydGlhbFZhbHVlc01hcCwgdmFsdWUsIGNzc1NlbGVjdG9yLCBzZWxlY3Rvck1hdGNoQ2FsbGJhY2spIHx8IHJlc3VsdDsKMTY2NzhhMTY2OTEsMTY2OTIKPiAgICAgICAgICAgICAvLyBNYXRjaGVkIGRpcmVjdGl2ZXMgaW4gdGVtcGxhdGUgdGhhdCBuZWVkIHRvIGJlIHNvcnRlZCBieSBpbmRleAo+ICAgICAgICAgICAgIHRoaXMuX2RpcmVjdGl2ZXNXaXRoSW5kZXggPSBbXTsKMTY3NjZhMTY3ODEsMTY3ODYKPiAKPiAgICAgICAgICAgICB0aGlzLl9kaXJlY3RpdmVzV2l0aEluZGV4LnNvcnQoKHQxLCB0MikgPT4gdDFbMV0gLSB0MlsxXSk7Cj4gICAgICAgICAgICAgZm9yICh2YXIgaSA9IDA7IGkgPCB0aGlzLl9kaXJlY3RpdmVzV2l0aEluZGV4Lmxlbmd0aDsgaSsrKSB7Cj4gICAgICAgICAgICAgICAgIHRoaXMuZGlyZWN0aXZlcy5hZGQodGhpcy5fZGlyZWN0aXZlc1dpdGhJbmRleFtpXVswXSk7Cj4gICAgICAgICAgICAgfQo+IAoxNzU1MGMxNzU3MAo8ICAgICAgICAgICAgICAgICB0aGlzLmRpcmVjdGl2ZU1hdGNoZXIubWF0Y2goc2VsZWN0b3IsIGZ1bmN0aW9uIChjc3NTZWxlY3Rvciwgc3RhdGljVHlwZSkgeyBfdGhpcy5kaXJlY3RpdmVzLmFkZChzdGF0aWNUeXBlKTsgfSk7Ci0tLQo+ICAgICAgICAgICAgICAgICB0aGlzLmRpcmVjdGl2ZU1hdGNoZXIubWF0Y2goc2VsZWN0b3IsIGZ1bmN0aW9uIChjc3NTZWxlY3Rvciwgc3RhdGljVHlwZSwgaW5kZXgpIHsgX3RoaXMuX2RpcmVjdGl2ZXNXaXRoSW5kZXgucHVzaChbc3RhdGljVHlwZSwgaW5kZXhdKTsgfSk7Cg==' | base64 --decode | patch node_modules/@angular/compiler/bundles/compiler.umd.js`

**Comment by Dj-jom2x** [comment]
9.0.0-rc.1 still exist

**Comment by instantgis** [comment]
I am using Angular 8.2.13
and 
@ng-dynamic-forms/core": "^8.1.1"

I turned on Ivy recently.
Ouch bad idea.
All my forms break - errors spewing in the console - validators related
Started with max length validator. Commented those out.
Expression validator errors show up which I am not using.

Turn off Ivy = back to working normal

**Comment by anton-white** [comment]
Same here on RC.3 with Ivy.

```
Angular CLI: 9.0.0-rc.3
Node: 12.13.1
OS: linux x64
Angular: 9.0.0-rc.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.14
@angular-devkit/build-angular     0.900.0-rc.3
@angular-devkit/build-optimizer   0.900.0-rc.3
@angular-devkit/build-webpack     0.900.0-rc.3
@angular-devkit/core              9.0.0-rc.3
@angular-devkit/schematics        8.3.14
@angular/cdk                      8.2.3
@angular/localize                 9.0.0-rc.0
@angular/material                 8.2.3
@ngtools/webpack                  9.0.0-rc.3
@schematics/angular               8.3.14
@schematics/update                0.900.0-rc.3
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
```

**Comment by tinybigideas** [comment]
Still exists with 9.0.0-rc.4. Was hoping https://github.com/angular/angular/pull/33403 would be merged if it is indeed the fix

**Comment by anton-white** [comment]
**RC.4** - no more error for `PatternValidator`!

**Comment by nathanrobinson** [comment]
This is fixed in the version 9 RC.4+
