### ISSUE TITLE
With enabled ivy project build failed

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [angular/angular#30780]
Hi, 
I am using angular 8.0.0

I have web page and 4 libarairies which exports modules.
Module looks like (tired with forRoot also)
```
@NgModule({
    providers: [
        { provide: DataStrategy, useClass: ImmerDataStrategy }
    ]
})
export class ImmerDataStrategyModule {
}
```
When trying to build website i got error 
```
error TS-991010: Value at position 4 in the NgModule.importss of ImmerAppModule is not a reference: [object Object]
```

And ImmerAppModule look like (21 line is word import: [)
```
...imports

@NgModule({
    imports: [
        CommonModule,
        FormsModule,
        ReactiveFormsModule,
        RouterModule.forChild(routes),
        StoreModule.provideStore(initialState),
        ImmerDataStrategyModule
    ],
    declarations: [
       ... components
    ]
})
export class ImmerAppModule {
}
```

I do no thtink that it is related to libraries but build with Ivy is failing. Any ideas why?

**Comment by alan-agius4** [comment]
Hi @vytautas-pranskunas, are these library published on npm or they are workspaces libraries?

**Comment by vytautas-pranskunas-** [comment]
Hi, I have tried both options... They are pushed, but i have tried 2 ways:
1) pushed
2) Removed from node_modules and compiled to relese folder with tsconfig.json containin path to it

in both cases error is the same.
I have also tired to add "enableIvy": true to libraries but nothing helps.

**Comment by vytautas-pranskunas-** [comment]
But tell me your thoughts maybe i can think of any improvements?

**Comment by vytautas-pranskunas-** [comment]
Actually they are workspace libs but with tsconfig.json path to release folder. So in my app i am using it that they would be i installed.

**Comment by alan-agius4** [comment]
That is currently not supported and is being tracked here https://github.com/angular/angular-cli/issues/14594

**Comment by vytautas-pranskunas-** [comment]
Thanks
