### ISSUE TITLE
Always get error: No provider for String! 

### ISSUE THREAD

**Issue by vincentsong** [angular/angular#3079]
Hi guys, 

  I am a newbie here, want to learn ng2, just followed the 5min quick start, but get the error below:

[Error] No provider for String! (MyAppComponent -> String)

BaseException@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:7173:34
AbstractBindingError@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:10580:70
NoBindingError@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:10598:64
_getByKey@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:23757:39
_getByKey@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:23752:44
get@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:23720:34
_getByKey@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:25555:54
_getByDependency@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:25370:34
_new@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:25288:54
getObjByKeyId@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:25722:43
hydrate@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:25659:33
hydrate@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:25209:35
_hydrateView@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:21836:38
hydrateRootHostView@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:21738:28
createRootHostView@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:24029:42
https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:14009:67
run@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:115:22
https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:12753:43
zoneBoundFn@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:88:22
lib$es6$promise$$internal$$tryCatch@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:479:24
lib$es6$promise$$internal$$invokeCallback@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:491:52
lib$es6$promise$$internal$$publish@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:462:52
https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:195:17
microtask@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:12773:25
run@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:115:22
https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:12753:43
zoneBoundFn@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:88:22
flush@https://code.angularjs.org/2.0.0-alpha.26/angular2.dev.js:1208:13
	logError (angular2.dev.js, line 18287)
	defaultErrorReporter (angular2.dev.js, line 26273)
	_onError (angular2.dev.js, line 12791)
	onError (angular2.dev.js, line 12739)
	run (angular2.dev.js, line 118)
	(anonymous function) (angular2.dev.js, line 12753)
	zoneBoundFn (angular2.dev.js, line 88)
	lib$es6$promise$$internal$$tryCatch (angular2.dev.js, line 479)
	lib$es6$promise$$internal$$invokeCallback (angular2.dev.js, line 491)
	lib$es6$promise$$internal$$publish (angular2.dev.js, line 462)
	(anonymous function) (angular2.dev.js, line 195)
	microtask (angular2.dev.js, line 12773)
	run (angular2.dev.js, line 115)
	(anonymous function) (angular2.dev.js, line 12753)
	zoneBoundFn (angular2.dev.js, line 88)
	flush (angular2.dev.js, line 1208)

**Comment by vincentsong** [comment]
Anyone could help me??

**Comment by gdi2290** [comment]
@vincentsong are you free for a screensharing? I can debug it with you

**Comment by mhevery** [comment]
please provide a replicated error on http://plnkr.co/edit/

Closing because it is not actionable.
