### ISSUE TITLE
Better code generation for Dart constructors

### ISSUE THREAD

**Issue by rakudrama** [angular/angular#308]
@vojtajina 

One difference between Dart and JavaScript is that in Dart, fields always exist and are initialized to 'null' if not explicitly initialized in a constructor.  All initalization is complete before the constructor body is executed.

The current pattern of assigning an initial value to fields in the constructor body causes dart2js to initialize the field and then assign to it later.  The code would be smaller and probably slightly faster if the transpiler generated Dart initializers instead of assignments.

Example:

    export class Key {
      token;
      id:int;
      metadata:any;
      constructor(token, id:int) {
        this.token = token;
        this.id = id;
        this.metadata = null;
      }

generates:

    class Key {
      var token;
      int id;
      dynamic metadata;
      Key(token, int id) {
        this.token = token;    // was initialized to null, now overwritten.
        this.id = id;
        this.metadata = null;  // was initialized to null, now overwritten with null.
      }

should generate

    class Key {
      var token;
      int id;
      dynamic metadata;
      Key(token, int id) 
          : this.token = token;
            this.id = id;
            this.metadata = null;

If the initializer does not depend on any constructor parameters, it can be initialized at the field.

    class Key {
      var token;
      int id;
      dynamic metadata = null;   // null is unnecessary, but could be e.g. 'new Map()'
      Key(token, int id)
          : this.token = token;
            this.id = id;

The general rule for the transpiler is to promote assignments to C++-style initializers until it sees 'this.' in a non-initializing position.

Example:

    export class Injector {
      _bindings:List;
      _instances:List;
      _parent:Injector;
      _defaultBindings:boolean;
      _asyncStrategy: _AsyncInjectorStrategy;
      _syncStrategy:_SyncInjectorStrategy;
      constructor(bindings:List, {parent=null, defaultBindings=false}={}) {
        var flatten = _flattenBindings(bindings, MapWrapper.create());
        this._bindings = this._createListOfBindings(flatten);
        this._instances = this._createInstances();
        this._parent = parent;                              // [A]
        this._defaultBindings = defaultBindings;            // [B]  

        this._asyncStrategy = new _AsyncInjectorStrategy(this);
        this._syncStrategy = new _SyncInjectorStrategy(this);
      }

This is much harder since 'this.' is used in the body.  In Dart, 'this' cannot be used in an initializer, other than for initializing a field, to prevent uninitialized fields being used.  It is hard (in the transpiler) to know whether this._createListOfBindings reads 'this._parent' before it is assigned.  If the ES6 code is rewritten to move the simple initializers first, then the transpiler can promote assignments to initializers until it sees 'this' in a context other than assigning a field.  More expressions can avoid 'this.' here if the helper methods used are static methods rather than instance methods.

Moving the fields forward gives us:

    export class Injector {
      _bindings:List;
      _instances:List;
      _parent:Injector;
      _defaultBindings:boolean;
      _asyncStrategy: _AsyncInjectorStrategy;
      _syncStrategy:_SyncInjectorStrategy;
      constructor(bindings:List, {parent=null, defaultBindings=false}={}) {
        this._parent = parent;                              // [A]
        this._defaultBindings = defaultBindings;            // [B]  
        var flatten = _flattenBindings(bindings, MapWrapper.create());
        this._bindings = this._createListOfBindings(flatten);
        this._instances = this._createInstances();
    
        this._asyncStrategy = new _AsyncInjectorStrategy(this);
        this._syncStrategy = new _SyncInjectorStrategy(this);
      }

which generates:

    class Injector {
      List _bindings;
      List _instances;
      Injector _parent;
      bool _defaultBindings;
      _AsyncInjectorStrategy _asyncStrategy;
      _SyncInjectorStrategy _syncStrategy;
      Injector(List bindings, {parent : null,
        defaultBindings : false}) {
        this._parent = parent;
        this._defaultBindings = defaultBindings;
        var flatten = _flattenBindings(bindings, MapWrapper.create());
        this._bindings = this._createListOfBindings(flatten);
        this._instances = this._createInstances();
        this._asyncStrategy = new _AsyncInjectorStrategy(this);
        this._syncStrategy = new _SyncInjectorStrategy(this);
      }

but should generate

    class Injector {
      List _bindings;
      List _instances;
      Injector _parent;
      bool _defaultBindings;
      _AsyncInjectorStrategy _asyncStrategy;
      _SyncInjectorStrategy _syncStrategy;
      Injector(List bindings, {parent : null,
        defaultBindings : false})
          : this._parent = parent,
            this._defaultBindings = defaultBindings {
        var flatten = _flattenBindings(bindings, MapWrapper.create());
        this._bindings = this._createListOfBindings(flatten);
        this._instances = this._createInstances();
        this._asyncStrategy = new _AsyncInjectorStrategy(this);
        this._syncStrategy = new _SyncInjectorStrategy(this);
      }

**Comment by mhevery** [comment]
Obsolete
