### ISSUE TITLE
pwa not working when service incude setInterval

### ISSUE THREAD

**Issue by pinecut** [angular/angular#30805]
I declare a function in app.service
``` 
// 每隔60分钟主动检查更新一次
  checkUpdateLoop() {
    if (this.updates.isEnabled) {
      this.updates.checkForUpdate();
      setInterval(() => {
        this.updates.checkForUpdate();
      }, 3600000);
    }
  }
```
and call it in app.service constructor
```
constructor(
    public ui: UiService,
    public updates: SwUpdate,
  ) {
    this.subscribeUpdate();
    this.checkRSSI();
    this.checkUpdateLoop();
  }
```

app.service is injected in app.component

```
export class AppComponent {
  constructor(private appService: AppService) {
  }
}
```

then my pwa won't work, service worker is not installed.
how can i do to fix it?

**Comment by gkalpak** [comment]
When you can a recurrent task (such as `setInterval()`), the app will never stabilize and the Angular ServiceWorker wll never get registered. See [SW Communications: Checking for updates][1] for more details.

[1]: https://angular.io/guide/service-worker-communications#checking-for-updates
