### ISSUE TITLE
Angular 8 upgradation - Error on Content Security Policy directive

### ISSUE THREAD

**Issue by Vinutha-BK** [angular/angular#30802]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
Hi Team,

After upgrading to v8 getting bellow error. Other manual migration work and AOT errors all resolved .Could anyone please help to resolve this.

Refused to load the image 'http://localhost:4200/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by RonAlmog** [comment]
I'm having the same issue. not a bit fan of the answer above. this is a new issue that came as a direct result of upgrading to ver 8. so any hint or direction for action would be appreciated. 
My code at least, is very standard and should not cause any issue:
<link rel="icon" type="image/x-icon" href="assets/images/favicon.ico">

**Comment by ctp-placebo** [comment]
Having the same problem with exact same error when trying to serve with  
`ng serve --configuration=no` or any othe i18n transation having followed the documentation closely to set up i18n.
How is this not suitable as a bug report? The error prevents pages loading and the error message does not provide useful information to resolve the issue.

**Comment by Sovai** [comment]
Come on! I also have this problem. any fix yet?

**Comment by tatsuya-takahashi** [comment]
any updates?

**Comment by Valdenirmezadri** [comment]
same issue

**Comment by mcshakes** [comment]
I have the same issue as this, though it only happened after I downloaded the following to the backend /api

`npm i --save axios chalk puppeteer`

Before that, the front end was loading just fine. When I restarted `npm run start` and `ng serve` on separate terminal window, I ran into the same problem above. One thing that stood out with downloading puppeteer was that a very large Chromium install needed to happen. Could be coincidental though

**Comment by whiteKhoukha** [comment]
I am also having the same issue, and it prevents loading the page itself!

**Comment by ti83** [comment]
I had this issue.  In my case, it was a bad import statement on one of my components.  That cleared it right up.  Here is an example of the import I had:

`import User = require("src/app/shared/interfaces/IUser");
import IUser = User.IUser;`

When I switched it to this:

`import { IUser } from 'src/app/shared/interfaces/IUser';`

The app seemed to load again.

**Comment by Celfin** [comment]
try npm install , it worked for me

**Comment by mcshakes** [comment]
Agreed, I removed all my node modules, cleaned everything and re did a fresh npm install. Fixed for me

**Comment by kidtango** [comment]
delete and reinstall node_modules didn't work for me. The app was working just fine yesterday!

**Comment by alechemy** [comment]
@mcshakes can you elaborate on what you did to "clean everything"? I'm in the same place as @kidtango -- deleted and reinstalled `node_modules`, but still getting this error which is preventing the app from loading.

**Comment by xinthose** [comment]
I had to re-create my whole app with `ng new` after upgrading the core to v8.  Now my app is working for me (a lot of work).

**Comment by kuromukira** [comment]
Hi, I'm getting this error. Created an app with angular 8 using `ng new`. Any updates on this?

**Comment by devrobx** [comment]
Also now getting this issue, everything was working fine earlier. Tried to backtrack to see if i changed anything by mistake but nothing helped

**Comment by pit-upgop-iti** [comment]
I tried removing node_modules and some other things but nothing seems to work, is there any consistent way to fix the issue?

**Comment by mjschranz** [comment]
I found the main issue for me was previously whenever I would navigate to just `http://localhost:4200` with my configuration using the `baseHref` and `baseUrl` options set to `en` it would auto redirect to `http://localhost:4200/en` and everything would be working just fine.

Under current versions if I do the same it doesn't auto redirect. If I set the url to `http://localhost:4200/en` then everything works just fine.

**Comment by jampasnando** [comment]
I solved the same issue doing:
npm rebuild node-sass

**Comment by romanakozak** [comment]
I am having this issue as well:
`localhost/:1 Refused to load the image 'http://localhost:3001/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.`

**Comment by glenngsanchez** [comment]
after running ionic cordova resources, got this same issue. anybody out there?

**Comment by Valdenirmezadri** [comment]
I create a pipe for this

@Pipe({name: 'safeHtml'})
export class SafeHtml {
  constructor(private sanitizer:DomSanitizer){}

  transform(html) {
    return this.sanitizer.bypassSecurityTrustResourceUrl(html);
  }
}

then use 
<audio   [src]="sound.src | safeHtml"  ></audio>

**Comment by jampasnando** [comment]
Just try:
npm rebuild node-sass

It worked for me

**Comment by kamaral75** [comment]
I am having the exact same issue. The workaround `npm rebuild node-sass` did not work. This seems to be a possible issue with the latest version of Angular router. I was not experiencing this issue until recently. I am running the latest version of Angular 8.

**Comment by DrBash** [comment]
I had the same issue, try to run "ionic cordova run android" to see what the actual error is (in the terminal instead of the browser error). I had an issue in my routing module!

**Comment by kinggolf** [comment]
I came across this same issue today while upgrading a fairly old Ionic/Angular app. I just upgraded a newer Ionic/Angular app last week with absolutely no issues. I compared the two and had to do the following 3 steps to the older app:
1) add core-js to package.json
2) add this to `tsconfig.json`:
```
,
    "paths": {
      "core-js/es7/reflect": ["node_modules/core-js/proposals/reflect-metadata"],
      "core-js/es6/*": ["node_modules/core-js/es/*"]
    }
```
I believe I've done this to all my angular app upgrades as well.
3) Changed `tsconifg.app.json` compileOptions from:
```
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015"
  },
```
to:
```
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "types": []

  },
```
I tried skipping any one of these, but had no success.

Both `ngUdate` and starting new projects to see changes from the older projects have served me well.

**Comment by abierbaum** [comment]
Does anyone have a diagnosis for what is causing this?  I can't seem to get it working with any of the solutions above.

**Comment by ram4420** [comment]
i had same issue i just tried "npm install" its working fine.

**Comment by hwaynefair** [comment]
i found a fix (of sorts) for me: I went back to a previous commit that "worked" - and replaced the "main.ts" with the "old" (working) version. *THIS FIXED THIS ISSUE FOR ME!*
Unfortunately I did not do a diff before applying this so I can't tell you what was different - but - after hours of trying to figure this out - I was relieved to find something that worked - I hope this helps someone!

**Comment by hwaynefair** [comment]
> Does anyone have a diagnosis for what is causing this? I can't seem to get it working with any of the solutions above.
Took me several hours but I found a solution that I think will work for many:
1. delete node_modules folder
2. run "npm i" in terminal to re-install
3. run "ng build" then correct any errors in your code you find revealed by the build
*****ONE CRITICAL ERROR YOU MIGHT SEE*****
Has to do with not being able to find something to do with web pack
If that is the case:
npm install --save-dev webpack
then
npm install --save-dev webpack-dev-server
Hope this helps!

**Comment by sannonaragao** [comment]
I had the same issue and fixed by updating my Node version.
  "engines": {
    "node": "10.16.3",
    "npm": "6.9.0"
  }

**Comment by ariley42** [comment]
I have the same issue when doing a very basic Angular tutorial, when I added Bootstrap css I got "Refused to load the image 'http://localhost:4200/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback."
I only added the import statements as given on the ng-bootstrap and bootstrap website. Has there been any resolution for this yet? None of the above solutions worked for me.

**Comment by Piyush9960** [comment]
> Refused to load the image 'http://localhost:4200/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.



> I have the same issue when doing a very basic Angular tutorial, when I added Bootstrap css I got "Refused to load the image 'http://localhost:4200/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback."
> I only added the import statements as given on the ng-bootstrap and bootstrap website. Has there been any resolution for this yet? None of the above solutions worked for me.

the <meta> element can be used to configure a policy, for example: <meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src https://*; child-src 'none';">

**Comment by hwaynefair** [comment]
Another thing that worked for me (when it reoccurred a second time)
One thing to try is to run **ng build**
This will possibly show errors in your code that are REALLY the problem - Fix those and you are good to go!
The build that occurs when you "serve" your code is just tripping over the favicon thing - but not the true issue/error

**Comment by Zer0ne83** [comment]
Same issue - soon as I upgraded to 8. None of the above solutions worked for me and it sounds like gutting the project and transplanting everything to a framework that actually works is the only 'solution' (and I use that term loosely). Good times.

**Comment by hwaynefair** [comment]
Zer0ne83  - really sorry to hear that - 
So - you did try my "solution"? (oh = BTW I too am using nG 8)
i.e.
**(I would suggest you reboot after the first two steps... you never know...)**
delete node_modules folder
run "npm i" in terminal to re-install
run "ng build" then correct any errors in your code you find revealed by the build
ONE CRITICAL ERROR YOU MIGHT SEE
Has to do with not being able to find something to do with web pack
If that is the case:
npm install --save-dev webpack
then
npm install --save-dev webpack-dev-server

**Comment by Zer0ne83** [comment]
Massive thank you @hwaynefair - I got too hung up on the content of the error message (CORS/permissions) which, if I had read your post properly, usually has nothing to do with the actual problem. ng build spat out the real issue/error, which was mine and too embarrassingly elementary to share *SMH*. Nevertheless, thank you, sir, saved me an unnecessary re-shelling *hats off*

**Comment by ravo10** [comment]
I got this error when I mistakenly put the "public" folder in the wrong place. I use `firebase serve`. If you have the same problem, make sure the settings in **firebase.json** is correct. The settings under "hosting" => "public" needs to point to the correct location you have your public folder (of course).

**Comment by TheRealOha** [comment]
Having the same problem after upgrading to Angular 8.
Reinstalled node modules, tried ng build (build was fine), modified tsconfig.json, nothing works.
