### ISSUE TITLE
Getting started guide without third parties?

### ISSUE THREAD

**Issue by i-schuetz** [angular/angular#30804]
# 📚 Docs or angular.io bug report

### Description

I'm following the start guide. It requires me to use StackBlitz development environment for which I also have to signup. Shouldn't the official starting guide to be rather a minimal, barebones introduction? I don't want to be forced to open an account on StackBlitz. Also, the predefined project makes it difficult to use this guide to build on a project from scratch. For example, it assumes at the beginning a custom module, while I'm looking how to create one.

### What's the affected URL?**
https://angular.io/start

**Comment by trotyl** [comment]
> for which I also have to signup

No, you don't.

> Shouldn't the official starting guide to be rather a minimal, barebones introduction?

That's why StackBlitz being used.

> I don't want to be forced to open an account on StackBlitz.

That's totally not making sense, StackBlitz has no account at all and just using GitHub to login.

> Also, the predefined project makes it difficult to use this guide to build on a project from scratch.

StackBlitz is using the same boilerplate as Angular CLI, you can go to https://angular.io/guide/setup-local for local setup but won't get any different file.

> For example, it assumes at the beginning a custom module, while I'm looking how to create one.

Again, that's not due to StackBlitz, just how Angular doc try to make it simple.

**Comment by Airblader** [comment]
StackBlitz can be used entirely without logging in as well. And if you prefer a local version with your own IDE, you can just use that instead.

**Comment by kapunahelewong** [comment]
@i-schuetz are you better able to work now with the info that @trotyl and @Airblader shared with you?

@brandonroberts and @jenniferfell fyi.

**Comment by i-schuetz** [comment]
Ah, I overflew the page and it mentioned logging in to StackBlitz, so I assumed that this was required. I see now that this is optional. Anyway I followed the heroes tutorial (https://angular.io/tutorial) which is more in line which what I was expecting. Thanks for the clarifications!
