### ISSUE TITLE
angular universal not work with angular 8

### ISSUE THREAD

**Issue by nadermedhet148** [angular/angular#30806]
i update my angular 6 app to angular 8 and after build universal app this error occur 
all things work in last version
     throw staticError('Unexpected provider', provider);
                ^

Error: StaticInjectorError[{provide:undefined, useFactory:_document, deps:[Injector]}]: Unexpected provider

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
