### ISSUE TITLE
Support DOM element to source mappings for VS Code's Browser preview 

### ISSUE THREAD

**Issue by auchenberg** [angular/angular#30800]
Hi 👋

I'm the author of https://github.com/auchenberg/vscode-browser-preview/, which is an extension for VS Code that allows users to preview web content inside the editor. 

Browser Preview also supports "inspect component" which enables people to select a DOM element and go directly to the component source inside the editor.

![ezgif com-optimize](https://user-images.githubusercontent.com/173559/58752303-8041c980-8461-11e9-90e2-845957170534.gif)

Details: https://mobile.twitter.com/auchenberg/status/1133178573773164545

I'd love to be able to support Angular for this feature, and I'm wondering if Angular already exposes element to source mappings when running in development mode?

Browser Preview is using https://github.com/auchenberg/element-to-source to do the mapping.

/k

**Comment by Airblader** [comment]
Have you looked into something like this? https://www.google.com/url?sa=t&source=web&rct=j&url=https://blog.angularindepth.com/everything-you-need-to-know-about-debugging-angular-applications-d308ed8a51b4&ved=2ahUKEwiyxLKi-cjiAhWvPOwKHR_sC3IQjjgwAHoECAgQAg&usg=AOvVaw2fKeAekz3g_Oy7yTe4TgQP
