### ISSUE TITLE
Property 'pipe' does not exist on type 'Observable<Response>'.

### ISSUE THREAD

**Issue by Gajendrasinh** [angular/angular#30813]
I am using   

"@angular/cli": "^8.0.1",  
"rxjs": "^6.5.2",
"rxjs-compat": "^6.5.2",

how to fix this error.

Property 'pipe' does not exist on type 'Observable<Response>'.

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
