### ISSUE TITLE
Router doesn't export the QueryParamsHandling interface anymore

### ISSUE THREAD

**Issue by FrankMerema** [angular/angular#30816]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?

Yes, the previous version in which this bug was not present was: angular 7.*

### Description
After migrating to angular 8.0 using the command
```ng update @angular/cli @angular/core```
The compiler started to complain about ```error TS2305: Module '"@angular/router/router"' has no exported member 'QueryParamsHandling'.```

I use this for importing the QueryParamsHandling interface 👍

```import { QueryParamsHandling} from '@angular/router/src/config';```

Should I import it from else where ?

## 🔥 Exception or Error
<pre><code>error TS2305: Module '"@angular/router/router"' has no exported member 'QueryParamsHandling'.
</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>Angular CLI: 8.0.1
Node: 10.16.0
OS: win32 x64
Angular: 8.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by trotyl** [comment]
> We explicitly don't consider the following to be our public API surface:
> + any file/import paths within our package except for the /, /testing and /bundles/* and other documented package entry-points.

https://github.com/angular/angular/blob/master/docs/PUBLIC_API.md

This is never a public API and should not work in any version.

**Comment by FrankMerema** [comment]
Thanks for the reply, I understand the reason why this is done 👍

**Comment by efcoyote** [comment]
Imho, this it a bug. The property is [flaged as part of the public API](https://github.com/angular/angular/blob/master/packages/router/src/config.ts#L147). But it's missing in the [index.ts](https://github.com/angular/angular/blob/master/packages/router/src/index.ts). The rest of the `NavigationExtras` interface seems to be part of the API so it make no sense to hide property types.

**Comment by willyboy** [comment]
@efcoyote I agree. We were using this to avoid having to duplicate the type. Anything types that are used for the public API should be exposed.
