### ISSUE TITLE
Export DefaultRouteReuseStrategy from router

### ISSUE THREAD

**Issue by ph55** [angular/angular#30827]
Please export `DefaultRouteReuseStrategy` from router for easy extension.
Most of the time you need to override only one method (maybe few) but not all.

**Comment by jasonaden** [comment]
Thanks for the issue. If you would like to create a PR, that would be helpful.

**Comment by abarghoud** [comment]
Hello @jasonaden, I am taking this one.

**Comment by abarghoud** [comment]
@jasonaden PR ready for a review

**Comment by gkalpak** [comment]
AFAICT, this has been fixed by #31575.
