### ISSUE TITLE
Squished docs text on animations/transitions page

### ISSUE THREAD

**Issue by chrismbarr** [angular/angular#30833]
# 📚 Docs or angular.io bug report

### Description

There is a very long parameter, which then squishes the following paragraph of text so that it is unreadable.

### What's the affected URL?**
https://angular.io/api/animations/transition

### Reproduction Steps**
Visit the page & look at the squished paragraph after "parameters" `stateChangeExpr`

### Expected vs Actual Behavior**
Not to be squished

## 📷Screenshot

![image](https://user-images.githubusercontent.com/463685/58828064-8dea8100-8612-11e9-8387-169a62344ced.png)

And here's a recording of what the whole page looks like when i scroll:

![squished-text](https://user-images.githubusercontent.com/463685/58828542-aeffa180-8613-11e9-9f3b-496d7b47ad0d.gif)

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/27296

**Comment by ajitsinghkaler** [comment]
@gkalpak @kapunahelewong I think this can be closed
