### ISSUE TITLE
Angular routing issue with base-href

### ISSUE THREAD

**Issue by pkundan24** [angular/angular#30836]
Hi,

When i build the angular project with having path in angular.json in outputPath: '../somewhere out from angular folder'   and added in package.json with  --base-href ../ngBuild/  which is also out side directory now my problem is all build stuff is located outside directory.
reason is simple for security concerns. 

on java side we were running .jsp file which includes index.html from build folder

so on run time running index.jsp url would be ../index.jsp
on time of routing as set --base-href as ../ngBuild/ the route navigate to ../ngBuild/something
which is working but not such directory available on reload time it throws error.

1. how can i maintain state with index.jsp??

i see skipLocationChange which allows to routing without changing URL but will not maintaining state.

on useHash in app.module will it be possible maintain state at index.jsp like URL will be like index.jsp/#/todo

note:  I don't have option to load project directly without index.jsp

**Comment by santoshyadav198613** [comment]
Not sure what you are trying to achieve, but as you you mentioned jsp. Which is server side rendering, you can look at https://github.com/swaechter/angularj-universal Universal Support for Java.

**Comment by pkundan24** [comment]
thank you santosh
 but nope this will not work in my case.
in spring boot there is option to load navigation url with page


in jsp need to import index.html from angular build folder where base-href created build.
and if i load that in url need to run index.jsp which having index.html included.

so in routing when we import routerModule angular itself started routes from localhost:4200/'routing path'

in my case running url is index.jsp/ 'here i need to maintain the routing state'

Thanks in advance

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
