### ISSUE TITLE
Responsive Component Feature - Matteo Rossi

### ISSUE THREAD

**Issue by bar0n91** [angular/angular#30837]
# 🚀 feature request

### Relevant Package
 This feature request is for @angular/core

### Description
One of the most annoiying task to do in a web application, is setting up a responsive layout for my templates. Sometimes, the html and the css files, are really dirty, because of too many media queries or styles for make the page responsive.
So i was thinking a solution to this problem using Angular.

### Describe the solution you'd like
 I was thinking about have more templates for differents screen sizes. For beginning, i think we should have an option to define if a certain component is "responsive".
![image](https://user-images.githubusercontent.com/51359557/58862610-57b00e80-86b1-11e9-823b-eb8604874b9a.png)

If the boolean flag is set to false, then the component will have the actual and standard setup.
If the boolean flag i set to true, then i imagine a scenario like this:
![image](https://user-images.githubusercontent.com/51359557/58864523-32bd9a80-86b5-11e9-8b8c-10fca6f3b240.png)

![image](https://user-images.githubusercontent.com/51359557/58864671-787a6300-86b5-11e9-948b-33ad87a092a5.png)
Paths are wrong but there are only for give an idea of the setup.
The component still has his css file, that i mean like the parent css of the component, and switching the screen size, the others css would be applied.
After this settings, Angular should know which template load dynamically, depending on the screen size. Obviously you can define the same template for differents screen sizes.
Of course, i imagine an option too, in the Angular CLI to generate a responsive component:
e.g. ng g c ComponentName --responsive

What do you think about my idea? I know this could be a bit of duplication codes sometimes, but can be really usefull in some scenario, where html and css are really dirty.
Sorry for my bad english, i'm trying to improve it too.

**Comment by jotatoledo** [comment]
This is a big nope IMO

**Comment by santoshyadav198613** [comment]
Agreed with @jotatoledo , This is not something which Angular should take care of.

**Comment by sebaherrera** [comment]
Some responsiveness is available via CDK:

https://github.com/angular/flex-layout/wiki/Responsive-API
https://github.com/angular/flex-layout/wiki/Breakpoints

I think that the API should be simplified in the ways of NG Bootstrap.

**Comment by mhevery** [comment]
Will not implement
