### ISSUE TITLE
Router links badly generated

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#3083]
I may be missing something, but with alpha 31, links that were like : 

    <a [router-link]="['/user', {'id', user.id}]">see user</a>

were generating '/users/1' urls and now generates '/users;id=1'.

With a router config : 

    {path: '/users/:id', component: UserCmp, as: 'user'},

Looks like it is related to matrix parameters introduced by @matsko in 5677bf73 , but maybe it is the intended behaviour and I need to change my router-link expressions, but I did not see anything in the changelog. Sorry if I missed it.

**Comment by bryantharpe** [comment]
I was able to generate URLs correctly in alpha 31 using the style below. The odd part is though, that it required me to reference the route by its name, but add a slash in front of it like I was referencing it by its path. I assume this is a bug, but, it got me going.


````html
<a [router-link]="['/UpdateProducts', {'productId':product.productId}]" class="link">{{product.name}}</a>
````

````javascript
@RouteConfig([
    {path: '/', component: ProductsList, as: 'Products'},
    {path: '/products/:productId', component: UpdateProducts, as: 'UpdateProducts'}
])
````

**Comment by cexbrayat** [comment]
That may be a mis configuration on my part : it indeed works if I tweak some things. Weird that it was working with the previous alpha, but well... I'll close for now.
