### ISSUE TITLE
How to check Android app is installed on device from browser in angular 2+

### ISSUE THREAD

**Issue by abhishek3999** [angular/angular#30843]
Hi,
 I would like to check if specified android app installed on device by browser.
Scenario:
X web application viewed by user with z url on browser.Then the condition is that to check some y android application is already installed or not.If yes open that or throw some popups.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
