### ISSUE TITLE
Router and Nested Router Problems

### ISSUE THREAD

**Issue by TiagoBraga39** [angular/angular#3084]
Hi all !
I may be not understanding something, but this is my main router:

```javascript
@RouteConfig([
    { path: '/',  redirectTo: '/#login' },
    { path: '#home', component: Home, as: 'home' },
    { path: '#login', component: Login, as: 'login' },
    { path: '#commercial/...', component: Commercial , as: 'commercial' }
])
```

```html
<ul class="nav">
    <li><a [router-link]="['./home']">Home</a></li>
    <li><a [router-link]="['./login']">Login</a></li>
    <li><a [router-link]="['./commercial']">Commercial</a></li>
</ul>
```

----
<h1>Problem 1:</h1>
I have this on my router component construtor:
```javascript
this.router.navigate('/'+location._location.hash);
```
And if I don´t, i can't get to the specified page on F5 (refreshing page).
Also: (location._location.hash) is the only way to get the hash that has value (for example): '#login'.

----
<h1>Problem 2:</h1>
If i have that redirect and if i click on home (currently on login page) the router works, but the url does not change. Not at first. I have to click twice for the click to change the url.

----
<h1>Problem 3:</h1>
As you can see, I have a nested router  on "commercial"., and it never triggers (i put a debugger on the Commercial constructor) with the url = "commercial" or "commercial/"

My Commercial Component:
```javascript
@View({
    template: '<h1>Commercial page</h1> <router-outlet></router-outlet>',
    directives: [ routerDirectives, Home ]
})
@RouteConfig([
    { path: '', redirectTo: '/favorites' },
    { path: '/', component: Home, as: 'home' },
    { path: '/favorites', component: Home, as: 'home' },
])
```

As you can see, I am just using my Home Component again (which should have no problem).
But still, i can't get the router to work.
I can if I use the url "commercial<b>//</b>" and  changes the url to "commercial/favorites", but it doesn't load the Home Component.

Used this to make the router:
```link
https://github.com/angular/angular/blob/master/modules/angular2/test/router/outlet_spec.ts#L112-L121
```

Any help will be usefull.

Best regards,
Tiago Braga

**Comment by btford** [comment]
You should not have `#` in your route config. This will become an error in alpha-32. Change `#home` to `home`, `#commercial/...` to `commercial/...`, etc.

You want to bind `LocationStrategy` to `HashLocationStrategy` if you want hashchange routing.

Try out these changes and let me know if you're still having trouble.

**Comment by TiagoBraga39** [comment]
I used those because the url path would become "<host>/index.html/<page>", which is a static url,  and refreshing the page would not work.
I also tried to bind, but I will again.

Will reply as soon as I am at work again :+1:

**Comment by TiagoBraga39** [comment]
@btford
Sorry to reopen this thread, but I just upgraded to alpha 32, and coulnd't get the routers to work...

<h1>First things first:</h1>
<h2>The Router</h2>
![image](https://cloud.githubusercontent.com/assets/8090726/8848959/ad9e3dda-3133-11e5-9111-cafcd63f6fc6.png)
<h2>The Nested Router</h2>
![image](https://cloud.githubusercontent.com/assets/8090726/8849121/02bc60a2-3135-11e5-904a-446247784af4.png)

---
<h1>Problem 1: Relative paths.</h1>
After upgrading, I had to add "new Route", and it throw the following error:
![image](https://cloud.githubusercontent.com/assets/8090726/8848927/65fc7578-3133-11e5-9902-658862657ce8.png)
<b>Solved this way:</b>
![image](https://cloud.githubusercontent.com/assets/8090726/8848938/79eaea88-3133-11e5-867a-8c1a5352ff51.png)

<h2>Result</h2>
I can only enter the page after F5 with this code in the constructor:
```javascript
this.router.navigate(location._location.hash.split('#')[1]);
```

I can enter the nested router, BUT only if I use something like:
```javascript
commercial/<something>
// doens't work If the url is "commercial" only.
```
new Redirect({ path: 'commercial', redirectTo: 'commercial/favorites'})

<b>Problem 1.1:</b> doens't work If the url is "commercial" only
<b>Problem 1.2.:</b> The following redirect doesn't work:
```javascript
new Redirect({ path: 'commercial', redirectTo: 'commercial/favorites'})
```

<h1>Problem 2: The nested router:</h1>
The nested router tiggers (debugger on construtor), but doesn't resolve in commercial page:
Again the nested router component:
![image](https://cloud.githubusercontent.com/assets/8090726/8849130/2a01f226-3135-11e5-85a5-78a1ed2b07be.png)

<h1>Problem 3: Router link:</h1>
How can I change router with router link to a nested Router?
Like this?
![image](https://cloud.githubusercontent.com/assets/8090726/8849150/4af063e6-3135-11e5-9b05-1e4a1657fb09.png)
Don't forget the nested router has :category parameter, so like this?
![image](https://cloud.githubusercontent.com/assets/8090726/8849158/633d74ac-3135-11e5-856a-148178d86dd4.png)

Sorry for all the trouble.

Best regards,
Tiago Braga

**Comment by thisisbadal** [comment]
I manage to make nested routing work. I have pasted the code at the end.

<b>In below example ./nested/start1 is not working correctly because start1 is mapped to "/"</b>

  <ul>
    <li><a [router-link]="['./start']">Start</a></li>
    <li><a [router-link]="['./contact']">Contact</a></li>
    <li><a [router-link]="['./aboutus']">About Us</a></li>
    <li><a [router-link]="['./nested/aboutus1']">Nested About Us</a></li>
    <li><a [router-link]="['./nested/start1']">Nested Start</a></li>
    <li><a [router-link]="['./nested/contact1']">Nested Contact</a></li>
  </ul

@Component({
    selector: 'main-app'
})
@RouteConfig([
  new Route({ path: '/', as : 'start', component: Start}),
  new Route({ path: '/contact', as : 'contact', component: Contact}),
  new Route({ path: '/aboutus', as : 'aboutus', component: AboutUs}),
  new Route({ path: '/nested/...', as : 'nested', component: NestedRouterExample})
])
export class MainApp {

}

@Component({
  selector: 'nestedrouterexample'
})
@View({
  directives: [RouterOutlet],
  template: `<h1>Inside Nasted Router</h1><router-outlet></router-outlet>`
})
@RouteConfig([
  new Route({ path: '/', as : 'start1', component: Start}),
  new Route({ path: '/contact1', as : 'contact1', component: Contact}),
  new Route({ path: '/aboutus1', as : 'aboutus1', component: AboutUs})
])
export class NestedRouterExample {
}

**Comment by tiziano88** [comment]
This seems still broken. Basically there seems to be no way of triggering the `/` route within a nested router.

**Comment by TiagoBraga39** [comment]
Sorry for the late feedback.

It now "works" but I can't access to the 
As you can see, I can't use router-link as you have, but something like (I guess):
```html
[router-link]="['./commercial/commercial-menu', { category: 'favorites' }]"
```
Which works, but now I can't access to the RouteParams property.
<b>The nested router:</b>
```javascript
@RouteConfig([
    //new Redirect({ path: '', redirectTo: 'favorites'}),
    //new Route({ path: 'favorites', component: CommercialMenu, as: 'favorites' }),
    new Route({ path: ':category', component: CommercialMenu, as: 'commercial-menu' }),
    new Route({ path: ':category/:list', component: EntityListing, as: 'entity-listing' }),
])
export class Commercial {
    constructor(router : Router, params: RouteParams) {
        this.router = router;
        this.params = params;
        this.selectedUrlCategory = this.params.get("category");
    }
```
Now RouteParams.get('category') returns null

Best regards,
Tiago Braga

**Comment by ericmartinezr** [comment]
@TiagoBraga39 did you find any solution for refreshing and 'back' button? I'm experiencing the same issues. [Other users](http://stackoverflow.com/questions/32429089/how-do-i-support-routeparams-on-page-reload-using-angular-2-dart) have found a related issue.

**Comment by radek-holy** [comment]
Why did you close this? The child's redirection still does not work, does it?
