### ISSUE TITLE
@NgModule argument must be an object literal

### ISSUE THREAD

**Issue by konsultaner** [angular/angular#30840]
# 🐞 bug report

### Affected Package
The issue is caused by package `@angular/compiler` on `@angular/core@next` and `@angular/compiler@8.0.0`.

### Is this a regression?
works with out ivy enabled

### Description

if `@NgModule()` arguments are passed as variable I get this error

## 🔬 Minimal Reproduction

this fails:

```ts
const moduleDefinition = {...}

@NgModule(moduleDefinition)
export class AppModule {
    constructor() {}
}
```

this works: 

```ts
@NgModule({...})
export class AppModule {
    constructor() {}
}
```

**Comment by alxhub** [comment]
This is an intentional change in Ivy - we're stricter about the arguments to decorators than View Engine was. It's a requirement for how Ivy compiles decorators (by moving the expressions inside them into other locations in the class output).
