### ISSUE TITLE
Angular 8 - ng build builds the application two times

### ISSUE THREAD

**Issue by proAppleEater** [angular/angular#30849]
# 🐞 bug report

### Affected Package
Angular 8

### Is this a regression?
Yes, it worked in Angular 7

### Description
Since the update to Angular 8, ng build builds the application two times.

## 🔬 Minimal Reproduction
Run ng build

## 🔥 Exception or Error
<pre><code>
ng build

Date: 2019-06-03T13:12:16.935Z
Hash: 01293a5de1d462ce2542
Time: 320308ms
chunk {0} common-es5.9d68d8ee241d78556065.js (common) 1.25 kB  [rendered]
chunk {1} 1-es5.ac1f7f02c87094b5dbfb.js () 16.3 kB  [rendered]
chunk {2} 2-es5.232fd8640d69a5e2d3f2.js () 31.3 kB  [rendered]
chunk {3} runtime-es5.478c1102f171ff89d1e9.js (runtime) 2.53 kB [entry] [rendered]
chunk {4} 4-es5.ffc71fdc9be673ce5000.js () 406 kB  [rendered]
chunk {5} main-es5.04f3eaaceae462dd3892.js (main) 4.01 MB [initial] [rendered]
chunk {6} polyfills-es5.3c846a2b08a355ef1aed.js (polyfills) 136 kB [initial] [rendered]
chunk {7} styles.f78c7b44959f56be1b90.css (styles) 211 kB [initial] [rendered]
chunk {8} 8-es5.b7fc1f2a63cf1e37d761.js () 409 kB  [rendered]
chunk {9} 9-es5.4386f279d5f7cf31e0ce.js () 495 kB  [rendered]
chunk {10} 10-es5.bb249809d0c028878617.js () 90.6 kB  [rendered]
chunk {11} 11-es5.dc6373baf45d76f13f3c.js () 2.65 kB  [rendered]
chunk {12} 12-es5.50c12a393d3776c68e22.js () 43.5 kB  [rendered]
chunk {13} 13-es5.8764c3080e8ff3bb65dd.js () 305 kB  [rendered]
chunk {14} 14-es5.fdd677dcb465e684eb64.js () 45.8 kB  [rendered]
chunk {15} 15-es5.7fa29539e9bc96f2fe02.js () 475 kB  [rendered]
chunk {16} 16-es5.fe18373fe63d6495e34f.js () 335 kB  [rendered]
chunk {17} 17-es5.4af39a1c9fae65a9a593.js () 163 kB  [rendered]
chunk {18} 18-es5.143cf9f2ba1252329a32.js () 48.1 kB  [rendered]
chunk {19} 19-es5.b914a23bfe9e3cf12531.js () 5.15 kB  [rendered]

Date: 2019-06-03T13:18:22.068Z
Hash: 195b53403057c8b24d2b
Time: 364149ms
chunk {0} common-es2015.7062c456e93d6ddf7087.js (common) 1.17 kB  [rendered]
chunk {1} 1-es2015.20566ffc9306ab929901.js () 15.9 kB  [rendered]
chunk {2} 2-es2015.262eb644017c1d5c3106.js () 31.3 kB  [rendered]
chunk {3} runtime-es2015.304479ed687030691c30.js (runtime) 2.54 kB [entry] [rendered]
chunk {4} 4-es2015.5e604f0d77b1862eb1df.js () 399 kB  [rendered]
chunk {5} main-es2015.2a037e88ce4044aa4559.js (main) 3.82 MB [initial] [rendered]
chunk {6} polyfills-es2015.833b7f84051b37ac8a11.js (polyfills) 61.8 kB [initial] [rendered]
chunk {7} styles.f78c7b44959f56be1b90.css (styles) 211 kB [initial] [rendered]
chunk {8} 8-es2015.a8023360c09a130c4661.js () 402 kB  [rendered]
chunk {9} 9-es2015.bbed9df0bb02625e73a9.js () 491 kB  [rendered]
chunk {10} 10-es2015.47860dd30db499a29baf.js () 89.5 kB  [rendered]
chunk {11} 11-es2015.b0679aec5b2fcefe3ec7.js () 2.65 kB  [rendered]
chunk {12} 12-es2015.2c7b1fc622c34a862dfb.js () 43.1 kB  [rendered]
chunk {13} 13-es2015.b0e5921586d2bc29c5be.js () 300 kB  [rendered]
chunk {14} 14-es2015.7d43cec7534b8da1a45b.js () 45 kB  [rendered]
chunk {15} 15-es2015.a8bd8e8c58aaae51f686.js () 469 kB  [rendered]
chunk {16} 16-es2015.efbd7cc9e9763cb92345.js () 333 kB  [rendered]
chunk {17} 17-es2015.ba7791812c4939996c21.js () 158 kB  [rendered]
chunk {18} 18-es2015.2541380fa0abcf48e446.js () 47.8 kB  [rendered]
chunk {19} 19-es2015.c3bb9993273ff08c877a.js () 5.15 kB  [rendered]

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0
Node: 10.15.0
OS: win32 x64
Angular: 8.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.0
@angular-devkit/build-angular      0.800.0
@angular-devkit/build-ng-packagr   0.800.0
@angular-devkit/build-optimizer    0.800.0
@angular-devkit/build-webpack      0.800.0
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.6.8
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.0
@schematics/angular                8.0.0
@schematics/update                 0.800.0
ng-packagr                         5.2.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0

</code></pre>

**Anything else relevant?**
Not that I can think of.

**Comment by jdaaboul** [comment]
I have been having the same issue after I upgraded to angular 8. Please help

**Comment by karu971** [comment]
Same for me...

**Comment by Brandinga** [comment]
there are now 2 different bundles:  one es5 and one es2015

[angular.io](https://angular.io/guide/deployment#differential-loading)

**Comment by proAppleEater** [comment]
This gives us a great lead. Thank you. We will comment and resolve the issue after our investigations.

**Comment by proAppleEater** [comment]
As Brandinga pointed out, this is an intended feature of Angular 8. You can build only one of the two if you want, depending of what your business want to support. We opted to build only es2015, since we don't want to support older versions.
Go in your browserslist, and adapt the list of browser you want to support. If you support the newer ones, like chrome, it will only build the es2015 one.
