### ISSUE TITLE
No additional chunks downloaded for lazy loaded modules

### ISSUE THREAD

**Issue by yannickglt** [angular/angular#30866]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?

Yes, the previous version in which this bug was not present was: 7.2.7

### Description

Lazy loaded modules do work but they do not look to be lazy loaded, as nothing appear in the network tab at loading time. It looks like all modules are eager.

## 🔬 Minimal Reproduction
The live example from the documentation is sufficient to see that no additional request is made to load the new module: https://angular.io/generated/live-examples/lazy-loading-ngmodules/stackblitz.html.
The steps to reproduce are described in the official documentation at https://angular.io/guide/lazy-loading-ngmodules#confirm-its-working.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.1
Node: 10.16.0
OS: darwin x64
Angular: 8.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.0
@angular/cli                      8.0.1
@angular/flex-layout              8.0.0-beta.26
@angular/http                     7.2.15
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.0
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**
The issue is visible in the Chrome Dev Tools and in the Firefox Toolbox.

**Comment by gkalpak** [comment]
I tried with the [downloadable zip][1] (both `ng serve` and `ng build --prod`) and it works as expected. I suspect StackBlitz is doing some smart prefetching/bundling for performance reasons and breaks the expected behavior.

@EricSimons should know more.

[1]: https://angular.io/generated/zips/lazy-loading-ngmodules/lazy-loading-ngmodules.zip

**Comment by trotyl** [comment]
It's a consistent behavior in StackBlitz, see https://github.com/angular/angular/issues/25843#issuecomment-419097607. Please don't mark it as regression if it never works.

**Comment by yannickglt** [comment]
OK, sorry for mentioning stackblitz as a demo, I didn't know about this issue. I gave it a try with the downloadable zip, thanks @gkalpak and it works as expected.

However, I created this issue because, of course, I got the same problem on my project and not only on stackblitz @trotyl. 

After comparing my project settings with the zip, I found the mistake which caused the lazy loaded modules to fail.
The problem came from the `module` option in the `tsconfig` which remained set to `commonjs` while Angular 8 looks to require `esnext` to get lazy-loaded modules work as expected.

Work as expected in Angular 7 but not in Angular 8:
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "moduleResolution": "node",
```

Work in Angular 8:
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "target": "es2015",
    "module": "esnext",
    "moduleResolution": "node",
```

Anyway, thanks for your help.

**Comment by EricSimons** [comment]
@gkalpak is correct- since all bundling is done in-mem, we currently preresolve all lazy modules. The next version of our in-browser toolchain will enable network fetch for dynamic imports just like the CLI though, ETA is a couple months from now 😅

**Comment by devel112** [comment]
Will `/* webpackPrefetch: true */` (`import(/* webpackPrefetch: true */ './Admin/admin.module')`) be supported?
