### ISSUE TITLE
Bazel - build_bazel_rules_nodejs\internal\web_package\injector: command not found

### ISSUE THREAD

**Issue by mcm-ham** [angular/angular#30863]
# 🐞 bug report

### Affected Package
@angular/bazel 8.0.0

### Description

Unable to follow guide to build an angular app using bazel:
https://angular.io/guide/bazel

## 🔬 Minimal Reproduction
1. npm i -g @angular/bazel
2. npm i -g @bazel/bazel `// fix https://github.com/bazelbuild/bazel-watcher/issues/252`
3. ng new --collection=@angular/bazel
4. ng serve

## 🔥 Exception or Error
<pre><code>Querying for files to watch...
)) was unexpected at this time.
Bazel query failed: exit status 255
Loading: 0 packages loaded
Loading: 33 packages loaded
Loading: 262 packages loaded

Loading: 262 packages loaded
Runing //src:devserver
Loading: 0 packages loaded
Loading: 0 packages loaded

Loading: 0 packages loaded
Launching with notifications
listening on :35729
Loading:
Loading: 0 packages loaded
Analyzing: target //src:devserver (1 packages loaded, 0 targets configured)
Analyzing: target //src:devserver (49 packages loaded, 6494 targets configured)
Analyzing: target //src:devserver (254 packages loaded, 18014 targets configured)
INFO: Analyzed target //src:devserver (254 packages loaded, 18018 targets configured).
INFO: Found 1 target...
[0 / 5] [-----] BazelWorkspaceStatusAction stable-status.txt
[6 / 8] checking cached actions
[22 / 24] [-----] SkylarkAction src/index.html
ERROR: C:/temp/bazel/src/BUILD.bazel:77:1: SkylarkAction src/index.html failed (Exit 127)
/bin/bash: C:\users\michael\_bazel_michael\j4y6ybtn\execroot\project\bazel-out\host\bin\external\build_bazel_rules_nodejs\internal\web_package\injector: command not found
Target //src:devserver failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9.189s, Critical Path: 1.17s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully
Error starting process: fork/exec C:\Users\Michael\AppData\Local\Temp\bazel_script_path167241051.bat: %1 is not a valid Win32 application.
Run start failed fork/exec C:\Users\Michael\AppData\Local\Temp\bazel_script_path167241051.bat: %1 is not a valid Win32 application.
Triggering live reload
requesting reload: reload
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 8.0.1
Node: 10.16.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.800.1
@angular-devkit/core         8.0.1
@angular-devkit/schematics   8.0.1
@schematics/angular          8.0.1
@schematics/update           0.800.1
rxjs                         6.4.0
</code></pre>

**Comment by blemaire** [comment]
I get a similar issue on a custom bazel configuration

```
load("@npm//@babel/cli:index.bzl", "babel")
load("@npm//http-server:index.bzl", "http_server")

babel(
    name = "compile",
    data = [
        "app.js",
       "@npm//@babel/preset-env",
    ],
    outs = ["app.es5.js"],
    args = [
        "app.js",
        "--out-file",
        "$(location app.es5.js)",
    ],
)

http_server(
    name = "server",
    data = [
        "index.html",
        "app.es5.js",
    ],
    args = ["."],
)
```

Here is the error I get:
```
?[0m?[31miBazel [11:38PM]?[0m: Error starting process: fork/exec C:\Users\lbast\AppData\Local\Temp\bazel_script_path521968771.bat: %1 is not a valid Win32 application.
?[31miBazel [11:38PM]?[0m: Run start failed fork/exec C:\Users\lbast\AppData\Local\Temp\bazel_script_path521968771.bat: %1 is not a valid Win32 application.
```

**Comment by CharlieLavers** [comment]
I was getting the same error message as above.  I found that the .bat file was empty and that I had the following error in my ibazel start up logs:

```
ERROR: Unrecognized option: --incompatible_bzl_disallow_load_after_statement=false
```

I found that I had to comment out / remove the following line in my generated `.bazelrc` file:

```
build --incompatible_bzl_disallow_load_after_statement=false
```

This fixed the issue

I am not sure if it is related to the original reporters bug, since I had that additional error log about the invalid flag.

**Comment by alxhub** [comment]
Closing as obsolete - the Bazel builder and associated CLI functionality are deprecated and no longer supported.
