### ISSUE TITLE
Service worker cache progress or finished event

### ISSUE THREAD

**Issue by MrCircuit** [angular/angular#30860]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/service-worker

### Description
 The angular service worker already provides an easy to use and robust caching solution for the assets of a web application. Nevertheless, there is currently no way to tell the user, at which percentage of the total amount of data the caching currently is working at and when it finished downloading the installation or update. Especially for use cases where the user just want to stay online for the time of installation or update, this issue is creating huge documentation and deployment problems for an offline web app.

### Describe the solution you'd like
 Although there is a similar, but much more general feature request (#22543), it would be great to just have a set of events, that report progress and / or start and finish of the caching process.

### Describe alternatives you've considered
 The current workaround is, that the users have to wait an indetermined amount of time until the web app is downloaded completely. The usage of the "network" tabs of the developer tools of browsers, where the progress can be monitored, is not wanted.

**Comment by gkalpak** [comment]
It is an interesting feature request. I can imagine it would be a little complicated to get right, because there several different situations and they change dynamically without a way to know beforehand.

For example:
- The client might just have installed the SW (so it is controlled by it, but there are no files yet cached by the SW).
- The client might be on the latest known cached version, but there might be a newer version available (which is detected asynchronously). So, again, you don't know how long to wait, before you have the latest files cached.

**Comment by MrCircuit** [comment]
I agree, that a perfect progress indicator with an accurate percentage of bytes transferred may be difficult to implement without this knowledge. But as far as I understood, at least the process itself is known in the interiors of the SW (e.g. the asset file list, the start of caching and the end of caching)? This would already help to a great extend - the user can be notified when everything is all set.

**Comment by gkalpak** [comment]
> This would already help to a great extend - the user can be notified when everything is all set.

That's the thing. It is not easy to know if/when _"everything is all set"_ (or what _"all set"_ means). I am not saying it is not doable, just that there are many edge cases that need to be taken into account.

And there is also the issue of when/how often to notify the client to avoid spamming them.

**Comment by gkalpak** [comment]
While this is an interesting feature, there doesn't seem to be a high demand for it. Closing for now.

**Comment by atamansv** [comment]
A "finished" event would be very useful due to the large assets of our project and the slow internet of the target customers!

**Comment by gkalpak** [comment]
@atamansv, you might want to follow #39840 (not sure if it's going to be implemented or not, but it is being tracked there).
