### ISSUE TITLE
Http Requests and Http Injectables

### ISSUE THREAD

**Issue by TiagoBraga39** [angular/angular#3086]
Hi all !

I think httpInjectables are not working completely...

----
<h1>Problem 1</h1>
This is my Service:
```javascript
@Component({
    viewInjector: [httpInjectables]
})
export class Service {
   constructor(http : Http) {
        ObservableWrapper.subscribe(http.get('http://api.github.com/users'), res => { 
            debugger
            this.people = res.json()
        });
   }
}
```

Which throws this:
![image](https://cloud.githubusercontent.com/assets/8090726/8727749/40ccbbdc-2bd9-11e5-9138-7e06c739f737.png)

This is my bootstrap:
```javascript
bootstrap(Application, []);
```
----
But <b>only</b> if I change my bootstrap, I can run the code..
```javascript
bootstrap(Application, [httpInjectables]);
```

Any ideas why is this happening?
I mean, if I want my service component to be distributed to other applications, I need to add httpInjectables to bootstrap? Seems wrong... The idea of NG2 was to build scalable and independent components.

----
<h1>Problem 2</h1>
If I request a non existing resource (it also happens locally): 
![image](https://cloud.githubusercontent.com/assets/8090726/8727914/3f9cb252-2bda-11e5-9363-7f0f71960eb2.png)

The status body id correct, but the status code is not and always returns 200.

Best regards,
Tiago Braga

**Comment by matanlurey** [comment]
You need to add HTTP injectables, because Angular can't possibly know *what* you intend to use across your application. For example, you may use a 3rd party HTTP or Router solution.

**Comment by gdi2290** [comment]
the first problem is due to appInjector(boostrap bindings) vs viewInjector vs hostInjector

the second problem might be solved with https://github.com/angular/angular/pull/2667 and https://github.com/angular/angular/pull/2882

**Comment by TiagoBraga39** [comment]
Thank you both for replying!
About the httpInjectables: imagine i have an application that does not need http requests, and you have a component that I found very useful, I would like to had the component, but that component of yours uses http.
Again, i should only importante your component, nothing more.. But that's my opinion..

Still, gonna close this.

Best regards, 
Tiago Braga
