### ISSUE TITLE
JitCompilerFactory error when enable ivy

### ISSUE THREAD

**Issue by vthinkxie** [angular/angular#30862]
# 🐞 bug report

### Affected Package

`@angular/platform-browser-dynamic`

### Is this a regression?

yes, it works fine without ivy enabled in Angular 8.

### Description

We use JitCompilerFactory to load dynamic component from the string that users input, everything works fine in `ng serve` and it also could work with `ng build --prod` when `buildOptimizer:false`.

but the app will go wrong when running `ng serve` when **ivy** enabled.

```json
  "angularCompilerOptions": {
    "enableIvy": true
  }
```

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-moqyep?file=src%2Fapp%2Fapp.component.ts

## 🔥 Exception or Error
<pre><code>
class__.html:1 ERROR Error: Unable to find context associated with [object HTMLInputElement]
    at loadLContext (core.js:17714)
    at loadLContextFromNode (core.js:17759)
    at getListeners (core.js:17793)
    at DebugElement__POST_R3__.get listeners [as listeners] (core.js:32724)
    at DebugRenderer2.listen (core.js:36732)
    at listenToElementOutputs (core.js:33712)
    at createViewNodes (core.js:34976)
    at callViewAction (core.js:35462)
    at execComponentViewsAction (core.js:35367)
    at createViewNodes (core.js:35041)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.1
Node: 10.15.3
OS: darwin x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Comment by pitAlex** [comment]
Hello, I am getting similar error after updating our angular project to be Ivy compatible. We got the pages to work with Ivy, but when turning it off while keeping AOT mode on, we get :
Unable to find context associated with [object HTMLInputElement]

**Comment by mhevery** [comment]
Please provide repro steps. Clicking on the stackblitz link does not throw that error and it is not clear what steps should be taken to reproduce the error.

**Comment by vthinkxie** [comment]
Hi @mgechev 
it works fine with the latest version of angular, close it now, thanks for your comment.
