### ISSUE TITLE
Schematic "ng-add" not found in collection "@angular/bazel".

### ISSUE THREAD

**Issue by Maximebpro** [angular/angular#30871]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/bazel

### Is this a regression?
I don't know

### Description

`ng add @angular/bazel` fails (even if i retry).

## 🔬 Minimal Reproduction

```
cd my-huge-angular-poject
node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng add @angular/bazel
```

## 🔥 Exception or Error
<pre><code>
$ yarn ngx add @angular/bazel
yarn run v1.15.2
$ node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng add @angular/bazel
Installing packages for tooling via yarn.
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["object-assign@latest"] is trying to unpack in the same destination "C:\\Users\\M4938423\\AppData\\Local\\Yarn\\Cache\\v4\\npm-object-assign-4.1.1-2109adc7965887cfc05cbbd442cac8bfbb360863\\node_modules\\object-assign" as pattern ["object-assign@^4.1.1","object-assign@^4.0.1","object-assign@^4.1.0","object-assign@^4","object-assign@^4.1.0","object-assign@^4.0.1","object-assign@^4.1.0","object-assign@^4.0.1","object-assign@^4.0.1"]. This could result in non-deterministic behavior, skipping.
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.0.7: The platform "win32" is incompatible with this module.
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @ng-bootstrap/ng-bootstrap@4.2.1" has incorrect peer dependency "@angular/common@^7.0.0".
warning " > @ng-bootstrap/ng-bootstrap@4.2.1" has incorrect peer dependency "@angular/core@^7.0.0".
warning " > @ng-bootstrap/ng-bootstrap@4.2.1" has incorrect peer dependency "@angular/forms@^7.0.0".
warning " > @ngrx/effects@7.3.0" has incorrect peer dependency "@angular/core@^7.0.0".
warning " > @ngrx/router-store@7.3.0" has incorrect peer dependency "@angular/common@^7.0.0".
warning " > @ngrx/router-store@7.3.0" has incorrect peer dependency "@angular/core@^7.0.0".
warning " > @ngrx/router-store@7.3.0" has incorrect peer dependency "@angular/router@^7.0.0".
warning " > @ngrx/store@7.3.0" has incorrect peer dependency "@angular/core@^7.0.0".
warning " > ng-dynamic-component@4.0.3" has incorrect peer dependency "@angular/common@^7.0.0".
warning " > ng-dynamic-component@4.0.3" has incorrect peer dependency "@angular/core@^7.0.0".
warning " > @angular/bazel@7.2.9" has incorrect peer dependency "@angular/compiler-cli@7.2.9".
warning " > @angular/bazel@7.2.9" has incorrect peer dependency "typescript@>=3.1.1 <3.3".
warning "@angular/bazel > tsickle@0.34.0" has incorrect peer dependency "typescript@~3.1.3 || ~3.2.0-rc".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 11 new dependencies.
info Direct dependencies
└─ @angular/bazel@7.2.9
info All dependencies
├─ @angular/bazel@7.2.9
├─ @bazel/typescript@0.26.0
├─ ascli@1.0.1
├─ bytebuffer@5.0.1
├─ colour@0.7.1
├─ long@3.2.0
├─ optjs@3.2.2
├─ protobufjs@5.0.3
├─ shelljs@0.8.2
├─ tsickle@0.34.0
└─ window-size@0.1.4
Installed packages for tooling via yarn.
Schematic "ng-add" not found in collection "@angular/bazel".
Error: Schematic "ng-add" not found in collection "@angular/bazel".
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.1
Node: 10.16.0
OS: win32 x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.1
@angular-devkit/build-angular      0.800.1
@angular-devkit/build-ng-packagr   0.800.1
@angular-devkit/build-optimizer    0.800.1
@angular-devkit/build-webpack      0.800.1
@angular-devkit/core               8.0.1
@angular-devkit/schematics         8.0.1
@angular/bazel                     7.2.9
@angular/cdk                       7.3.5
@angular/cli                       8.0.1
@bazel/typescript                  0.26.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.1
@schematics/angular                8.0.1
@schematics/update                 0.800.1
ng-packagr                         5.2.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0
</code></pre>

**Anything else relevant?**
Project was angular7. I used `ng update @angular/cli @angular/core` to upgrade to angular 8. No specific issue during the process.

**Comment by Maximebpro** [comment]
Could be linked to https://github.com/angular/angular/issues/30052 ?

**Comment by Maximebpro** [comment]
After further investigation... Using global cli
```
ng add @angular/bazel
```
goes a bit further
```
[...]
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 14 new dependencies.
info Direct dependencies
└─ @angular/bazel@8.0.0
info All dependencies
├─ @angular/bazel@8.0.0
├─ @microsoft/api-extractor-model@7.1.2
├─ @microsoft/api-extractor@7.1.7
├─ @microsoft/ts-command-line@4.2.5
├─ @types/argparse@1.0.33
├─ @types/fs-extra@5.0.4
├─ @types/jju@1.4.1
├─ @types/z-schema@3.16.31
├─ jju@1.4.0
├─ lodash.isequal@4.5.0
├─ shelljs@0.8.2
├─ tsickle@0.35.0
├─ validator@8.2.0
└─ z-schema@3.18.4
Done in 23.68s.
Installed packages for tooling via yarn.
CREATE angular-metadata.tsconfig.json (731 bytes)
CREATE e2e/protractor.on-prepare.js (1106 bytes)
CREATE src/initialize_testbed.ts (432 bytes)
CREATE src/main.dev.ts (185 bytes)
CREATE src/main.prod.ts (249 bytes)
CREATE src/rxjs_shims.js (1259 bytes)
CREATE angular.json.bak (13949 bytes)
CREATE tsconfig.json.bak (757 bytes)
UPDATE package.json (5298 bytes)
UPDATE angular.json (9958 bytes)
UPDATE .gitignore (731 bytes)
UPDATE tsconfig.json (550 bytes)
warning Pattern ["object-assign@latest"] is trying to unpack in the same destination "C:\\Users\\M4938423\\AppData\\Local\\Yarn\\Cache\\v4\\npm-object-assign-4.1.1-2109adc7965887cfc05cbbd442cac8bfbb360863\\node_modules\\object-assign" as pattern ["object-assign@^4.1.1","object-assign@^4.0.1","object-assign@^4.1.0","object-assign@^4","object-assign@^4.1.0","object-assign@^4.0.1","object-assign@^4.1.0","object-assign@^4.0.1","object-assign@^4.0.1"]. This could result in non-deterministic behavior, skipping.
warning " > @ng-bootstrap/ng-bootstrap@4.2.1" has incorrect peer dependency "@angular/common@^7.0.0".
warning " > @ng-bootstrap/ng-bootstrap@4.2.1" has incorrect peer dependency "@angular/core@^7.0.0".
warning " > @ng-bootstrap/ng-bootstrap@4.2.1" has incorrect peer dependency "@angular/forms@^7.0.0".
warning " > @ngrx/effects@7.3.0" has incorrect peer dependency "@angular/core@^7.0.0".
warning " > @ngrx/router-store@7.3.0" has incorrect peer dependency "@angular/common@^7.0.0".
warning " > @ngrx/router-store@7.3.0" has incorrect peer dependency "@angular/core@^7.0.0".
warning " > @ngrx/router-store@7.3.0" has incorrect peer dependency "@angular/router@^7.0.0".
warning " > @ngrx/store@7.3.0" has incorrect peer dependency "@angular/core@^7.0.0".
warning " > ng-dynamic-component@4.0.3" has incorrect peer dependency "@angular/common@^7.0.0".
warning " > ng-dynamic-component@4.0.3" has incorrect peer dependency "@angular/core@^7.0.0".
node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts(4,10): error TS1003: Identifier expected.
node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts(4,11): error TS1110: Type expected.
node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts(4,30): error TS1109: Expression expected.
node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts(4,41): error TS1128: Declaration or statement expected.
node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts(4,48): error TS1005: ';' expected.
node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts(7,19): error TS1139: Type parameter declaration expected.
node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts(7,30): error TS1005: '>' expected.
node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts(7,37): error TS1005: '=>' expected.
node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts(7,38): error TS1109: Expression expected.
node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts(8,34): error TS1139: Type parameter declaration expected.
node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts(8,45): error TS1005: ',' expected.
node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts(8,53): error TS1109: Expression expected.
node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts(8,64): error TS1109: Expression expected.
node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts(12,24): error TS1110: Type expected.
node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts(12,43): error TS1109: Expression expected.
node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts(21,40): error TS1110: Type expected.
node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts(21,59): error TS1109: Expression expected.
[...]
```

**Comment by alan-agius4** [comment]
Hi, from the first logs it looks like it's trying to install `@angular/bazel@7.2.9` which typically means that your local cli version is `7.x.x`.

The `@angular/bazel` schematics are only available in version `8.x.x`+

With regards to the later issue, it is a know issue and should be addressed in https://github.com/angular/angular/pull/30825

**Comment by Maximebpro** [comment]
After upgrading `@angular/cdk`, `ng add @angular/bazel` fetched the correct version (i.e. `8.0.0`).

And after analyzing #30825, I "hot" fixed the issue by modifying `node_modules\@angular\bazel\src\schematics\ng-add\files\angular-metadata.tsconfig.json.template` adding in the `exclude` array:
```
 "node_modules/@angular/cdk/schematics*",
 "node_modules/@angular/cdk/typings/schematics*",
```

Thanks for pointing me in the right direction @AlabasterAxe 👍

**Comment by alan-agius4** [comment]
I think you tagged the wrong person :P Glad it worked out for you :)
