### ISSUE TITLE
docs:Missed Style 03 in Version 8

### ISSUE THREAD

**Issue by michaelcharlesfs** [angular/angular#30878]
# 📚 Docs or angular.io bug report

### Description

 I am searching on style guide whats the difference between interface and classe for data models on newest version. But, i not found. This pattern has been deprecated or is really issue on documentation style guide session?

### What's the affected URL?**
 https://angular.io/guide/styleguide

**Comment by trotyl** [comment]
It's removed deliberately, see https://github.com/angular/angular/issues/24153, https://github.com/angular/angular/pull/29331, https://github.com/angular/angular/pull/30334 for more information.

**Comment by kapunahelewong** [comment]
Thanks, @michaelcharlesfs for bringing this up and thanks so much, @trotyl for sharing the details. @michaelcharlesfs does this help give you context for your question?

**Comment by michaelcharlesfs** [comment]
@kapunahelewong In the style guide are the Style 01, Style 02 and Style 04 sessions. In previous versions the Style 03 session explains rules and tips for constants, interfaces, classes, etc. But in the new version I did not find it. The Style 02-12 is "Angular NgModule names". The next session is Style 04-01 "LIFT".

**Comment by kapunahelewong** [comment]
You are correct, @michaelcharlesfs and the removal was indeed intentional. Did you take a look at the reasons listed in #24153? They might prove helpful.

**Comment by trotyl** [comment]
@kapunahelewong I think what @michaelcharlesfs means is that `04` should now be changed to `03` because original `03` was gone, also for every greater index number.

**Comment by kapunahelewong** [comment]
Ah, @trotyl thank you for the clarification. The numbering is indeed a valid point of discussion. I'll bring it up in the docs meeting. Maybe we need to rethink that aspect.

**Comment by michaelcharlesfs** [comment]
Yes. This is it. The numbering is confuse. But i understand which still in discuss. So, thank for all help and attention.
