### ISSUE TITLE
docs(aio): add https://dev.to/t/angular link to the resources section 

### ISSUE THREAD

**Issue by manekinekko** [angular/angular#30874]
# 📚 Docs or angular.io bug report

### Description

Lots of Angular content is being published on the Dev.to community 500+ up to now. I'd like us to support this community as well by adding the [https://dev.to/t/angular](https://dev.to/t/angular) link ~~to the Help section at the bottom section of angular.io~~ to the Resources section.

@IgorMinar @StephenFluin @mgechev @robwormald  wdyt?

**Comment by StephenFluin** [comment]
I think this isn't where someone would go for "help", this is more general content about Angular. I think it belongs in our resources page.

**Comment by mgechev** [comment]
I agree that resources page would be a better fit.

**Comment by manekinekko** [comment]
@mgechev @StephenFluin I've updated my PR accordingly. Thanks.

**Comment by manekinekko** [comment]
Merged in https://github.com/angular/angular/commit/7afd2603c9a0f5263ef8774731b3f432e97e843b
