### ISSUE TITLE
Document if static vs non-static ViewChild is preferred

### ISSUE THREAD

**Issue by epelc** [angular/angular#30887]
# 📚 Docs or angular.io bug report

### Description

Is there any recommendation or performance benefit on making a `ViewChild()` static or non-static in v8? ie in many cases you can switch from static to `static: false` if you aren't using the view within your `ngOnInit()` hook. Is 

A random guess would be that `static:true` would be better because the ViewChild would only have to be checked once but I do not have enough knowledge about how this is implemented to know for sure and it is not mentioned anywhere. I've also read that it is preferable to 

I assume others are also wondering this while upgrading to angular 8.

**Comment by santoshyadav198613** [comment]
Hi @epelc ,
I think we already have it https://angular.io/api/core/ViewChild
And of course, we cannot provide which is the preferred option, as it is already described which one to use in which scenario.

You can read the doc, and we can discuss if it is still required.

**Comment by epelc** [comment]
Thanks! I think that explains it better. I was reading some docs from the upgrade process which were slightly different.
