### ISSUE TITLE
improve vertical spacing and padding in docs

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#30880]
# 📚 Docs or angular.io bug report

### Description
In some places, vertical spacing and padding (aka vertical line spacing) is not optimal. Some specific areas: 

* Before and after section headings. We need more space above a new section. See guide/deprecations.md for examples.

* At bottom of alert boxes. See start/index.md alert about stackblitz tips. Not enough space below text. 

* Between text and figures. See start/index.md for one set of instructions with screen shots that follow. See guide/architecture.md and related architecture*.md for examples with diagrams. Also guide/forms-overview.md.

Also worth checking before and after tables.

Markdown is particularly poor in supporting authors in this regard. Where style sheets require specific spacing in the doc source file, we should be more clear in the Doc Style Guide about blank lines, etc. that are required to get the correct spacing and put in docs backlog to clean up certain elements (such as clean up all alerts). https://angular.io/guide/docs-style-guide 

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
See above 

### What's the affected URL?**
 https://angular.io/...
See above

### Reproduction Steps**

See above

### Expected vs Actual Behavior**

See above

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by jenniferfell** [comment]
Line spacing in lists isn't optimal. Ideally, there would be more space between list items. 

Is there any way to have AIO generation control vertical spacing in lists, or do authors need to handle it in markdown? 

When a list has items that are short, the default spacing works okay. 

As soon as a list item is 2-lines, you can start to see the decay in visual usability. See the first bullet list in attached screen shot.

When each list item is multi-line, I manually added blank lines to get better visual usability, rather than allowing the default spacing which too crowded. See the second bullet list in attached screen shot. 

Associated URL: https://angular.io/guide/docs-style-guide

![list-spacing](https://user-images.githubusercontent.com/31675481/58979936-6d463680-878c-11e9-89fb-556a1d7d7c58.png)

**Comment by gkalpak** [comment]
We can style the lists however we want (but the styles would apply to lists with both single-line and multi-line items).
But how do you want the styled?
- Do you want more space between items? (Would that look weird on lists with single-line items?)
- Or do you want to have less space between lines of the same items (see screenshot below)?

![li-dense](https://user-images.githubusercontent.com/8604205/58984154-0010c080-87e1-11e9-9b49-f4771523cc7d.png)

**Comment by sjtrimble** [comment]
@gkalpak  I was planning on adding an 8px padding to the `li` themselves. It looks ok still on single line items and multi-line. 

Example Multi-Line
<img width="695" alt="Screen Shot 2019-06-05 at 12 54 05 PM" src="https://user-images.githubusercontent.com/2958442/58985839-168f2b80-8791-11e9-84b3-fb81c6d60dd4.png">

Example Single-Line
<img width="654" alt="Screen Shot 2019-06-05 at 12 54 11 PM" src="https://user-images.githubusercontent.com/2958442/58985842-18f18580-8791-11e9-85a5-c7b0e07b8b0a.png">

I have a PR coming in for this as part of some of the Getting Started cleanup.

**Comment by aikidave** [comment]
Closing this issue as we've done some significant updates to the Angular.io CSS.
