### ISSUE TITLE
Angular JS and Angular running together in a single application

### ISSUE THREAD

**Issue by CHANDRAKANTHREDDY93** [angular/angular#30884]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: 
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by CHANDRAKANTHREDDY93** [comment]
Hi 
I'm trying to run Angular JS and Angular applications together in a single page application. In Angular JS I've set the path to navigate to Angular. When I tested it It is navigating, but only html file content is being display. When I console log something from a typescript file I could see nothing. Even the binding doesn't seem to be working. What's the possible solution for this? Also can I add Angular App Module to Angular JS? Or at least can I connect dist folder of Angular to Angular JS application

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
