### ISSUE TITLE
Post Undefined HttpClient

### ISSUE THREAD

**Issue by bkr32** [angular/angular#30881]
Hi there,
i recently upgraded from V7 to V8 using the guide provided.
Prior to this i was using HttpClient for my post requests and it went along fine.
After the update i get a `TypeError: Cannot read property 'post' of undefined` 
i've been over the code a dozen times and for the life of me i can't seem to find what' is wrong with it.

```
import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
@Injectable({
  providedIn: 'root'
})
  constructor(private httpClient: HttpClient) {}

  GetCountry(): Observable<any> {
    return this.httpClient.post(
      this.apiURL + '/country/list',
      JSON.stringify({
        api_key: this.apiKey
      }),
      this.httpOptions
    );
  }
```

Thanks

**Comment by RenuNishitha** [comment]
I am facing the same issue since morning

**Comment by ajayambre** [comment]
@bkr32
I think this is not specific to `POST` requests. 
Even the `GET` requests will give you the same error.
Please make sure you have imported `HttpClientModule` in your `app.module.ts`.

Do you see a `StaticInjector` error in your console?
Appreciate further details on this.

**Comment by bkr32** [comment]
Thank you for the fast response.
there is no StaticInjector error in my console
the full error is as follows
```
ERROR TypeError: Cannot read property 'post' of undefined
    at ApiService.GetCountry (api.service.ts:85)
    at RegisterComponent.GetCountry (register.component.ts:45)
    at RegisterComponent.ngOnInit (register.component.ts:41)
    at checkAndUpdateDirectiveInline (core.js:24489)
    at checkAndUpdateNodeInline (core.js:35151)
    at checkAndUpdateNode (core.js:35090)
    at debugCheckAndUpdateNode (core.js:36112)
    at debugCheckDirectivesFn (core.js:36055)
    at Object.updateDirectives (login-main.component.html:2)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:36043)```

and yes `HttpClientModule` is present in `app.module.ts`

```import { HttpClientModule } from '@angular/common/http';

@NgModule({
  imports: [
    HttpClientModule,
  ],
  declarations: [AppComponent],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

**Comment by santoshyadav198613** [comment]
Hi @bkr32 ,

Would advise you to post this question on StackOverflow or any facebook groups, you will get the answer there. we do not take such questions here. There is an Angular 8.0 facebook group join us and post this there.

**Comment by bkr32** [comment]
@santoshyadav198613 is there any on slack?
also posted this here since it might be a bug

**Comment by santoshyadav198613** [comment]
Join Gitter and try,
If you want us to can you create a GitHub repo or stackblitz link to check.

**Comment by bkr32** [comment]
Gitter? got a link for it?
as for stackblitz or a repo, the Api Url is in production so i'm afraid i can't do that.
however the above should be adequate since it's more of a HttpClient issue?
and not directly influenced by my config, as stated by @ajayambre it happens on `Get` requests as well

**Comment by santoshyadav198613** [comment]
I mean you don't have to write your code a simple http call,using any public API. You can just call Jon placeholder API .gitter link is available on code page of repository.

**Comment by srn99** [comment]
Hey,
I am struck with same error since yesterday. I downgraded from V8 to V7 and still i have that error

ComponentSpecValidatorComponent.html:47 ERROR TypeError: Cannot read property 'post' of undefined
    at OnboardingToolboxDataService.uploadFile (onboarding-toolbox-data.service.ts:19)
    at ComponentSpecValidatorComponent.onSubmitUpload (component-spec-validator.component.ts:37)
    at Object.eval [as handleEvent] (ComponentSpecValidatorComponent.html:47)
    at handleEvent (core.js:29587)
    at callWithDebugContext (core.js:31148)
    at Object.debugHandleEvent [as handleEvent] (core.js:30787)
    at dispatchEvent (core.js:25914)
    at core.js:26581
    at HTMLButtonElement.<anonymous> (platform-browser.js:1678)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask

I did import { HttpClientModule} from '@angular/common/http' in app.module.ts

**Comment by bkr32** [comment]
recreating on stackblitz https://stackblitz.com/edit/angular-vhsdwo
gives no error, following the `package.json` from the stackblitz yielded no results
i'm at a total loss

**Comment by santoshyadav198613** [comment]
Hi @bkr32 ,
I would suggest to have a look at your code again, I am sure you are either missing Httpclientmodule import in correct module. I know it can be frustrated sometime. Take a break and relook at the code.

**Comment by santoshyadav198613** [comment]
Also @bkr32 ,  search for @angular/http in you application and check if still there are any imports left.

**Comment by maxigimenez** [comment]
Try a fresh install of package.json also clearing npm cache and removing `node_modules`.

**Comment by srn99** [comment]
> Hi there,
> i recently upgraded from V7 to V8 using the guide provided.
> Prior to this i was using HttpClient for my post requests and it went along fine.
> After the update i get a `TypeError: Cannot read property 'post' of undefined`
> i've been over the code a dozen times and for the life of me i can't seem to find what' is wrong with it.
> 
> ```
> import { Injectable } from '@angular/core';
> import { HttpClient, HttpHeaders } from '@angular/common/http';
> @Injectable({
>   providedIn: 'root'
> })
>   constructor(private httpClient: HttpClient) {}
> 
>   GetCountry(): Observable<any> {
>     return this.httpClient.post(
>       this.apiURL + '/country/list',
>       JSON.stringify({
>         api_key: this.apiKey
>       }),
>       this.httpOptions
>     );
>   }
> ```
> 
> Thanks

Were you able to make it work??

**Comment by bkr32** [comment]
thanks for your suggestion @maxigimenez 
i reverted to a commit before the v8 update,
cleared npm cache cleared node modules
did a npm install
and then a ng update
it all worked out well after that
