### ISSUE TITLE
Update from Angular 7.2.0 to 8.0.0 ng-packagr

### ISSUE THREAD

**Issue by rbinsztock** [angular/angular#30892]
# Update Angular 7.2 to 8.0 Strangely named method

### Affected Package
ng-packagr\lib\ngc\compile-source-files
```
 at Object.<anonymous> (C:\Users\xxxx\sl_duo-front\node_modules\ng-packagr\lib\ngc\compile-source-files.js:66:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\xxxxx\seloger\node_modules\ng-packagr\lib\ngc\compile-source-files.js:4:58)
```

### Is this a regression?

Yes

### Description
I have project with one angular application and multiple libs, I tried the update to Angular 8.0.0 from 7.2.0 but the libraries build does not work anymore since : 

src/lib/card/directives/card-actions/card-actions.directive.ts(15,3): error TS0: cannot process decorators on strangely named method

## 🔬 Minimal Reproduction

card-actions.directive.ts(15,3): error TS0: cannot process decorators on strangely named method

L15 is `@HostListener('class.ui-card-actions-aligns-end') 'align === "end"': any;`

```
import { Directive, Input, HostBinding, HostListener } from '@angular/core';

/**
 * Action section of a card, needed as it's used as a selector in the API.
 */
@Directive({
  selector: 'ui-card-actions, [uiCardActions]',
  exportAs: 'uiCardActions',
})
export class CardActionsDirective {
  /** Position of the actions inside the card. */
  @Input() align: 'start' | 'end' = 'start';

  @HostBinding('class.ui-card-actions') true: Boolean;
  @HostListener('class.ui-card-actions-aligns-end') 'align === "end"': any;
}

```

## 🔥 Exception or Error
<pre><code>
projects/duo-ui-lib/src/lib/card/directives/card-actions/card-actions.directive.ts(15,3): error TS0: cannot process decorators on strangely named method

Error: projects/duo-ui-lib/src/lib/card/directives/card-actions/card-actions.directive.ts(15,3): error TS0: cannot process decorators on strangely named method

    at Object.<anonymous> (C:\Users\xxx\my_super_project\node_modules\ng-packagr\lib\ngc\compile-source-files.js:66:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\xxx\my_super_project\node_modules\ng-packagr\lib\ngc\compile-source-files.js:4:58)
</code></pre>

## 🌍  Your Environment

**Angular Version: 8.0.0
<pre><code>
Angular CLI: 8.0.1
Node: 12.4.0
OS: win32 x64
Angular: 8.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.1
@angular-devkit/build-angular      0.800.1
@angular-devkit/build-ng-packagr   0.800.1
@angular-devkit/build-optimizer    0.800.1
@angular-devkit/build-webpack      0.800.1
@angular-devkit/core               8.0.1
@angular-devkit/schematics         8.0.1
@angular/cli                       8.0.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.1
@schematics/angular                8.0.1
@schematics/update                 0.800.1
ng-packagr                         5.3.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0

</code></pre>

**Comment by santoshyadav198613** [comment]
Hi HostListener works with a method, I am seeing this for the first time,

  @HostListener('class.ui-card-actions-aligns-end') 'align === "end"': any;

Are you sure it should not be 
  @HostBinding('class.ui-card-actions-aligns-end') 'align === "end"': any;.

**Comment by rbinsztock** [comment]
> Hi HostListener works with a method, I am seeing this for the first time,
> 
> @HostListener('class.ui-card-actions-aligns-end') 'align === "end"': any;
> 
> Are you sure it should not be
> @HostBinding('class.ui-card-actions-aligns-end') 'align === "end"': any;.

Same with `@HostListerner` used

**Comment by JoostK** [comment]
This is actually tsickle: https://github.com/angular/tsickle/blob/0ceb7d6bc47f6945a6c4c09689f1388eb48f5c07/src/decorator_downlevel_transformer.ts#L408-L420

Could you check if your `tsconfig.json` or `tsconfig.app.json` files contain the Angular compiler option `annotateForClosureCompiler`, I guess it's set to `true`. Since tsickle doesn't support the syntax you're using, flipping it to `false` disables tsickle. I don't see though what has changed since 7.2 for this to have stopped working. I have _no idea_ what you're trying to achieve anyway, as that code sample makes no sense to me.

I am tempted to classify this bug as not being with the Angular framework itself, but in tooling instead.

**Comment by rbinsztock** [comment]
> This is actually tsickle: https://github.com/angular/tsickle/blob/0ceb7d6bc47f6945a6c4c09689f1388eb48f5c07/src/decorator_downlevel_transformer.ts#L408-L420
> 
> Could you check if your `tsconfig.json` or `tsconfig.app.json` files contain the Angular compiler option `annotateForClosureCompiler`, I guess it's set to `true`. Since tsickle doesn't support the syntax you're using, flipping it to `false` disables tsickle. I don't see though what has changed since 7.2 for this to have stopped working. I have _no idea_ what you're trying to achieve anyway, as that code sample makes no sense to me.
> 
> I am tempted to classify this bug as not being with the Angular framework itself, but in tooling instead.

Thank you for the help, switch `annotateForClosureCompiler` to false fixed the problem.

**Comment by trotyl** [comment]
@JoostK Allowing writing this is a BUG, see https://github.com/angular/angular/issues/18698 for more information.

**Comment by mhevery** [comment]
seems resoleved.
