### ISSUE TITLE
Versioning server side

### ISSUE THREAD

**Issue by salmau** [angular/angular#30895]
I have an Ionic webapp based on Angular routing.
Each time I published a new version of my app, I posted it in a versioned folder (i.e. v0.34)

How do you recommend to manage server-side versioning in the app routing?

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
