### ISSUE TITLE
Dart: DebugReflectionCapabilities's logging should not duplicate an application's

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#3089]
https://github.com/angular/angular/blob/master/modules/angular2/src/reflection/debug_reflection_capabilities.dart#L16 has the following:

```dart
Logger.root.onRecord.listen((LogRecord rec) {
  print('[${rec.loggerName}(${rec.level.name})]: ${rec.message}');
});
```

Unfortunately, most applications will usually install their own logger, so this means that all logging messages are duplicated. Ideally, DebugReflectionCapabilities would not install a root logger.

**Comment by jakemac53** [comment]
closed by https://github.com/angular/angular/pull/3224
