### ISSUE TITLE
Error in production build after update to Angular 8

### ISSUE THREAD

**Issue by MaciejWWojcik** [angular/angular#30890]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?
Yes, It occurred after update to Angular 8. I didn't change any environments files, or configuration. 
Previously I used Angular 7.

### Description
Production build fails using Angular 8.
Here is my configuration:
` "my-prod": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": true,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.my-prod.ts"
                }
              ]
            },`
I use command to build: `ng build --prod --configuration=my-prod`

## 🔥 Exception or Error
<pre><code>
ERROR in src/__ng_typecheck__.ts(334,62): error TS2344: Type '"enabled" | "minRows" | "maxRows" | "cdkAutosizeMinRows" | "cdkAutosizeMaxRows" | "matAutosizeMinRows" | "matAutosizeMaxRows" | "matAutosize" | "matTextareaAutosize"' does not satisfy the constraint '"ngOnDestroy" | "ngDoCheck" | "enabled" | "reset" | "ngAfterViewInit" | "minRows" | "maxRows" | "matAutosizeMinRows" | "matAutosizeMaxRows" | "matAutosize" | "matTextareaAutosize" | "_setMinHeight" | "_setMaxHeight" | "resizeToFitContent" | "_noopInputHandler"'.
  Type '"cdkAutosizeMinRows"' is not assignable to type '"ngOnDestroy" | "ngDoCheck" | "enabled" | "reset" | "ngAfterViewInit" | "minRows" | "maxRows" | "matAutosizeMinRows" | "matAutosizeMaxRows" | "matAutosize" | "matTextareaAutosize" | "_setMinHeight" | "_setMaxHeight" | "resizeToFitContent" | "_noopInputHandler"'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.1
Node: 12.4.0
OS: darwin x64
Angular: 8.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        0.6.8
@angular/cli                      8.0.1
@angular/http                     8.0.0-beta.10
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Comment by trotyl** [comment]
> Yes, It occurred after update to Angular 8. I didn't change any environments files, or configuration.

Not possible, template type-checking only exists in Ivy, which just got to preview stage in version 8.

**Comment by MaciejWWojcik** [comment]
okay, I only want to say, that my build was working in Angular 7

**Comment by santoshyadav198613** [comment]
Hi @MaciejWWojcik ,
1. In Angular 8 you can remove @angular/http, 
2. You are using cdk and material, can you check if it is also updated. 
3. In case you are using any third party library check if they are updated to Angular 8.
4. Make sure you don't have Ivy enabled.

**Comment by trotyl** [comment]
> I only want to say, that my build was working in Angular 7

The template type-checking is a **new feature** added in Ivy recently which being released at version 8, Ivy is only designed for preview purpose now, that mean any real project should not use Ivy (except for testing compatibility).

If you use Ivy in any real project (even in v7 or before?), you're puting your project on your own risk.

**Comment by MaciejWWojcik** [comment]
@santoshyadav198613 Hello :) 

Wow, the 4th point was actually very very helpful. I had enabled the Ivy :(
I switched this off and now my build is working 🎉 

Thanks very much!

**Comment by santoshyadav198613** [comment]
Welcome, @MaciejWWojcik. glad it worked.
