### ISSUE TITLE
how to fix Module not found: Error: Can't resolve 'rxjs/Observable' in 'node_modules\@angular\core\src\facade'

### ISSUE THREAD

**Issue by Gajendrasinh** [angular/angular#30903]
Angular Version :

Angular CLI: 8.0.2
Node: 8.11.4
OS: win32 x64
Angular: 8.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.2
@angular-devkit/build-angular     0.800.2
@angular-devkit/build-optimizer   0.800.2
@angular-devkit/build-webpack     0.800.2
@angular-devkit/core              8.0.2
@angular-devkit/schematics        8.0.2
@angular/cli                      8.0.2
@angular/flex-layout              8.0.0-beta.26
@ngtools/webpack                  8.0.2
@schematics/angular               8.0.2
@schematics/update                0.800.2
rxjs                              6.5.2
typescript                        3.4.1
webpack                           4.33.0

Error on ng serve

ERROR in C:/Users/gazala/Desktop/node_modules/@angular/core/src/facade/async.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:\Users\gazala\Desktop\node_modules\@angular\core\src\facade'
ERROR in C:/Users/gazala/Desktop/node_modules/@angular/forms/src/facade/async.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:\Users\gazala\Desktop\node_modules\@angular\forms\src\facade'
ERROR in C:/Users/gazala/Desktop/node_modules/@angular/http/src/backends/jsonp_backend.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:\Users\gazala\Desktop\node_modules\@angular\http\src\backends'
ERROR in C:/Users/gazala/Desktop/node_modules/@angular/http/src/backends/xhr_backend.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:\Users\gazala\Desktop\node_modules\@angular\http\src\backends'
ERROR in C:/Users/gazala/Desktop/node_modules/@angular/core/src/facade/async.js
Module not found: Error: Can't resolve 'rxjs/Subject' in 'C:\Users\gazala\Desktop\node_modules\@angular\core\src\facade'
ERROR in C:/Users/gazala/Desktop/node_modules/@angular/forms/src/facade/async.js
Module not found: Error: Can't resolve 'rxjs/Subject' in 'C:\Users\gazala\Desktop\node_modules\@angular\forms\src\facade'
ERROR in C:/Users/gazala/Desktop/node_modules/@angular/forms/src/model.js
Module not found: Error: Can't resolve 'rxjs/observable/fromPromise' in 'C:\Users\gazala\Desktop\node_modules\@angular\forms\src'
ERROR in C:/Users/gazala/Desktop/node_modules/@angular/forms/src/validators.js
Module not found: Error: Can't resolve 'rxjs/operator/toPromise' in 'C:\Users\gazala\Desktop\node_modules\@angular\forms\src'
ERROR in C:/Users/gazala/Desktop/node_modules/@angular/core/src/util/lang.js
Module not found: Error: Can't resolve 'rxjs/symbol/observable' in 'C:\Users\gazala\Desktop\node_modules\@angular\core\src\util'
i ｢wdm｣: Failed to compile.

**Comment by vinay95garg** [comment]
The issue seems to be rxjs version not compatible with Angular 8.Try running this command once :  
 npm install --save rxjs-compat    and see if works fine.

**Comment by Gajendrasinh** [comment]
Hello VInay,

Thank you for reply.

I have already try this step.

below is my package.json

 "dependencies": {
    "@angular/animations": "^8.0.0",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/flex-layout": "^8.0.0-beta.26",
    "@angular/forms": "^8.0.0",
    "@angular/material": "^8.0.0",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/router": "^8.0.0",
    "@ng-idle/core": "^7.0.0-beta.1",
    "@ng-idle/keepalive": "^7.0.0-beta.1",
    "@types/bootstrap": "^3.3.33",
    "@types/file-saver": "^2.0.1",
    "@types/underscore": "^1.8.18",
    "angular-2-dropdown-multiselect": "^1.9.0",
    "angular-dual-listbox": "^4.7.0",
    "angular-mat-datepicker": "^0.0.2",
    "angular2-moment": "1.9.0",
    "angular2-multiselect-dropdown": "^4.2.3",
    "bootstrap": "~3.3.7",
    "core-js": "^3.1.3",
    "enhanced-resolve": "^4.1.0",
    "file-saver": "^2.0.2",
    "flag-icon-css": "^3.3.0",
    "mydatepicker": "^2.6.6",
    "ng2-file-upload": "^1.3.0",
    "ng2-file-uploader": "^0.1.4",
    "ng2-translate": "^5.0.0",
    "ngx-filesaver": "^2.2.1",
    "ngx-modialog": "^5.0.1",
    "ngx-webstorage": "4.0.1",
    "primeng": "^8.0.0-rc.1",
    "rxjs": "^6.5.2",
    "rxjs-compat": "^6.5.2",
    "ts-helpers": "^1.1.2",
    "ts-metadata-helper": "^0.0.4",
    "tslib": "^1.9.0",
    "uglifyjs-webpack-plugin": "^2.1.3",
    "underscore": "^1.9.1",
    "xlsx": "^0.14.3",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.800.1",
    "@angular/cli": "^8.0.1",
    "@angular/compiler-cli": "^8.0.0",
    "@angular/language-service": "^8.0.0",
    "@types/jasmine": "^3.3.13",
    "@types/jquery": "3.3.29",
    "@types/node": "^12.0.4",
    "codelyzer": "^5.0.1",
    "jasmine-core": "^3.4.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^2.0.0",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "karma-remap-istanbul": "^0.6.0",
    "protractor": "^5.4.2",
    "rxjs-tslint": "^0.1.7",
    "ts-node": "^8.2.0",
    "tslint": "^5.17.0",
    "typescript": "3.4.1",
    "webpack": "^4.32.2",
    "webpack-cli": "^3.3.2"
  }

but its not working.

**Comment by santoshyadav198613** [comment]
Try fresh npm install, did you migrated your project to 8 recently?

**Comment by Gajendrasinh** [comment]
Hello Santosh,

Yes, recently i have migrated from angular 6 to 8.

I have try fresh npm install still issue is not fixed

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by christophstockinger** [comment]
I have the same problem! So I think it is a bug @mhevery!
