### ISSUE TITLE
option to disable redirection of /index.html#/routes to /#/routes [comp: router]

### ISSUE THREAD

**Issue by wis** [angular/angular#30902]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/router

### Description
the latter is nicer, but all browsers can't reload an extension page with a `<browser-extension-scheme>://<extension_GUID>/#/route` URL, they error out, I was certainly surprised that setting an extension's html pages location in manifest.json to "index.html#route" loads the page to the correct route with no issues.

I searched for docs to confirm if (already) it can be configured and how, but found nothing.

### Describe the solution you'd like
add a config option e.g "disablePageNameShortening" (i'm sure you're better than me at naming), similar to the "useHash" option.

**Comment by Airblader** [comment]
Can you be specific about which browsers error out and how?

**Comment by wis** [comment]
oh hello @Airblader thank you for i3gaps, I've been enjoying using it for 7 months now :smiley: 

Firefox and Chromium, I am in the process of open sourcing an Angular WebExtension(s) boilerplate, it's not ready yet for pushing, when I do you can clone it and try it yourself. or if you trust me to run a bundled extension, I linked it in the [issue report](https://bugs.chromium.org/p/chromium/issues/detail?id=849015#c_ts1529197162) I posted a year ago.

**Comment by wis** [comment]
can you please assist me in finding what part of the code base of the router module is responsible for this behavior so I can disable it (in a fork) for a temporary fix?
I would really appreciate it, a lot.
