### ISSUE TITLE
Migration from Angular 6 to Angular 8 - DOCUMENT import from @angular/platform-browser

### ISSUE THREAD

**Issue by camila-borges** [angular/angular#30904]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 6.1.0

### Description

I was migrating my project from Angular 6.1.0 to Angular 8.0.
I thought I was importing wrong in any part of project the DOCUMENT api, but I didn't find any code like "import { DOCUMENT } from '@angular/platform-browser';" in the project (so I couldn't import it right from '@angular/common' like I've seen as a solution in many places...).

## 🔬 Minimal Reproduction

Only updated my Angular version from 6.1.0 to 8.0.0 (using ng update @angular/cli @angular/core)

## 🔥 Exception or Error
<pre><code>

ERROR in ./src/app/features/secure/secure.module.ngfactory.js 104:4894-4906
"export 'DOCUMENT' (imported as 'i48') was not found in '@angular/platform-browser'
ERROR in ./src/app/features/secure/secure.module.ngfactory.js 104:5033-5045
"export 'DOCUMENT' (imported as 'i48') was not found in '@angular/platform-browser'
ERROR in ./src/app/features/updates/updates.module.ngfactory.js 108:4963-4975
"export 'DOCUMENT' (imported as 'i50') was not found in '@angular/platform-browser'
ERROR in ./src/app/features/updates/updates.module.ngfactory.js 108:5102-5114
"export 'DOCUMENT' (imported as 'i50') was not found in '@angular/platform-browser'
ERROR in ./src/app/features/jobs/job.module.ngfactory.js 109:5118-5130
"export 'DOCUMENT' (imported as 'i51') was not found in '@angular/platform-browser'
ERROR in ./src/app/features/jobs/job.module.ngfactory.js 109:4979-4991
"export 'DOCUMENT' (imported as 'i51') was not found in '@angular/platform-browser'
ERROR in ./src/app/features/accounts/account.module.ngfactory.js 112:5035-5047
"export 'DOCUMENT' (imported as 'i52') was not found in '@angular/platform-browser'
ERROR in ./src/app/features/accounts/account.module.ngfactory.js 112:5174-5186
"export 'DOCUMENT' (imported as 'i52') was not found in '@angular/platform-browser'
ERROR in ./src/app/features/control/control.module.ngfactory.js 115:5134-5146
"export 'DOCUMENT' (imported as 'i55') was not found in '@angular/platform-browser'
ERROR in ./src/app/features/control/control.module.ngfactory.js 115:5273-5285
"export 'DOCUMENT' (imported as 'i55') was not found in '@angular/platform-browser'
ERROR in ./src/app/features/devices/device.module.ngfactory.js 122:5242-5254
"export 'DOCUMENT' (imported as 'i58') was not found in '@angular/platform-browser'
ERROR in ./src/app/features/devices/device.module.ngfactory.js 122:5381-5393
"export 'DOCUMENT' (imported as 'i58') was not found in '@angular/platform-browser'
ERROR in ./node_modules/@swimlane/ngx-datatable/release/components/header/header.component.ngfactory.js 55:107-118
"export 'DOCUMENT' (imported as 'i8') was not found in '@angular/platform-browser'
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.1
Node: 10.16.0
OS: darwin x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cdk                      6.4.7
@angular/cli                      8.0.1
@angular/flex-layout              7.0.0-beta.24
@angular/material                 6.4.7
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by santoshyadav198613** [comment]
Hi @camila-borges ,

DOCUMENT was deprecated from '@angular/platform-browser' you should start importing from @angular/common.

let me know if it works.

**Comment by trotyl** [comment]
@santoshyadav198613 

The OP has stated it clearly he/she doesn't have any import of `DOCUMENT` from `platform-browser`:

> I thought I was importing wrong in any part of project the DOCUMENT api, but I didn't find any code like "import { DOCUMENT } from '@angular/platform-browser';" in the project (so I couldn't import it right from '@angular/common' like I've seen as a solution in many places...).

Please consider really reading the issues before making some conclusion. (I thought I should last person for clarifying this)

And in the log it's clear the errors are coming from `ngfactory`, not user files. This is because of the directive inline mechanism in view engine AOT implementation.

@camila-borges 

The [fix of `DOCUMENT` import in `@swimlane/ngx-datatable`](https://github.com/swimlane/ngx-datatable/pull/1697) was only landed in 15.0.0 version, but in your configuration `~14.0.0` it won't get that major version upgrade, you need to manually specify the version in upgrading like `npm install @swimlane/ngx-datatable@latest`.

**Comment by santoshyadav198613** [comment]
Hey @trotyl ,
Sorry missed reading that part, I will be careful in future. @camila-borges please follow suggestion from @trotyl

**Comment by camila-borges** [comment]
@trotyl thank you for the answer. It resolved some errors but it still happening :(

I've upgraded @swimlane/ngx-datatable (now at version 15.0.0) and @swimlane/ngx-charts (now at version 11.1.0) to test if it would resolve all errors, here are the errors that still happening:

```
ERROR in ./src/app/features/secure/secure.module.ngfactory.js 104:4913-4925
"export 'DOCUMENT' (imported as 'i48') was not found in '@angular/platform-browser'
ERROR in ./src/app/features/updates/updates.module.ngfactory.js 108:4982-4994
"export 'DOCUMENT' (imported as 'i50') was not found in '@angular/platform-browser'
ERROR in ./src/app/features/jobs/job.module.ngfactory.js 109:4998-5010
"export 'DOCUMENT' (imported as 'i51') was not found in '@angular/platform-browser'
ERROR in ./src/app/features/accounts/account.module.ngfactory.js 112:5054-5066
"export 'DOCUMENT' (imported as 'i52') was not found in '@angular/platform-browser'
ERROR in ./src/app/features/control/control.module.ngfactory.js 115:5153-5165
"export 'DOCUMENT' (imported as 'i55') was not found in '@angular/platform-browser'
ERROR in ./src/app/features/devices/device.module.ngfactory.js 122:5261-5273
"export 'DOCUMENT' (imported as 'i58') was not found in '@angular/platform-browser'
```

**Comment by vecernik** [comment]
experiencing similar error with covalent-core: 
ERROR in ./node_modules/@covalent/core/fesm2015/covalent-core.js 3821:79-87
"export 'DOCUMENT' was not found in '@angular/platform-browser'

**Comment by trotyl** [comment]
@camila-borges If you believe it’s an Angular issue, then you need to provide a minimal example, or you can just search your workspace (including `node_modules`) to see who did that.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mvlad7402** [comment]
> Hi @camila-borges ,
> 
> DOCUMENT was deprecated from '@angular/platform-browser' you should start importing from @angular/common.
> 
> let me know if it works.

Looks good in Angular 8.1.1
