### ISSUE TITLE
TestBed.get is considered deprecated by the docs

### ISSUE THREAD

**Issue by nicojs** [angular/angular#30906]
### Description

`TestBed.get` is considered deprecated according to the angular.io docs. Even though it isn't deprecated according to the changelog.

### What's the affected URL?**

https://angular.io/api/core/testing/TestBed#get

### Expected vs Actual Behavior**

Expected only one overload to be deprecated, as specified in the changelog:
https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes

## 📷Screenshot

![image](https://user-images.githubusercontent.com/1828233/59092117-19188f00-8911-11e9-96c1-0a8ef76c19aa.png)

**Comment by nicojs** [comment]
What can I do to add the overload that isn't deprecated to the docs? Happy to help.

**Comment by trotyl** [comment]
Possibly relates to https://github.com/angular/angular/pull/25670 (at least in same helper file), this is a docs-infra issue I don't think it's easy for community if not familiar with the process JSDoc extraction and rendering.

The best guess is that adding some JSDoc to the non-deprecated overload will automatically fix this, can be tested by local aio preview.

**Comment by kapunahelewong** [comment]
@chembu making sure this is on your radar regarding the changelog.

**Comment by trotyl** [comment]
@kapunahelewong The changelog is correct but the angular.io documentation is wrong.

**Comment by kapunahelewong** [comment]
Ohhh I see. I was mixed up. I'll look into it further. Thanks @trotyl :)

**Comment by ajitsinghkaler** [comment]
@gkalpak @kapunahelewong we can close this test bed.get  is deprecated in v9.0.0
