### ISSUE TITLE
@angular/elements behaviour nested component service injection different

### ISSUE THREAD

**Issue by pkracht** [angular/angular#30910]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/elements

### Is this a regression?

 No

### Description

 Injection of service in parent component using in child components not using host instance. Different behaviour using native angular component and webelements.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ybq1fc?file=src%2Fapp%2Fapp.component.html

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 8.0.1
Node: 12.4.0
OS: linux x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

**Comment by abstractFlo** [comment]
Push this up, we need this feature :(

**Comment by gkalpak** [comment]
It is really hard to tell what the problem is and whether it is still an issue (or what other issue it might be related to). The reproduction is quite complicated and the issue description lacks important information, such as what is the expected vs actual behavior and what actions to take to see the problem in action.

For example, this might be related #24181 or #37441.

##
This requires further investigation, but if someone wants to provide a minimal reproduction and a detailed description of what the problematic behavior is and how to see it in action, that would speed things up.

**Comment by pkracht** [comment]
Hmm, maybe it's related to the lazy loading problem, but using Angular 10 and ivy https://stackblitz.com/edit/angular-jqp3lw shows the same problem. Copying the custom tags outside app-root doesn't really fix it.

**Comment by jelbourn** [comment]
Took a look at this. I believe this is "working as expected" at least from the framework's perspective. When you use an Angular component, Angular knows that it's there and that any components in its content would have their injector augment by that component's providers. With custom elements, though, the components are a complete black-box to Angular- it can't know that injectors on a custom element would affect other custom elements inside of its content; they both end up with the same injector belonging to the template in which they're defined. 

This is a trade-off of using custom elements vs. Angular components; Angular components participate in a Angular framework idioms like DI directly, whereas custom elements are by their nature treated as a black box.
