### ISSUE TITLE
Zone: <root> ; Task: Promise.then ; Value: RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by sagarhspl** [angular/angular#30913]
Hi, 
I worked on a project(mobile app) with angular2 version 2.0.0-beta.11 and i've work on this project about a 2 years, application is compile and load fine, but when I am login in to my app and routing to dashboard screen it throws 'Maximum call stack size exceeded...' in iOS 12.2 and above version. below version are issue is not appear. If I removed some line from html template then it works like 70kb file size, but if I add some html line in that file and file size is getting 90kb it not working and below error is throw:

Unhandled Promise rejection: Maximum call stack size exceeded. ; Zone: <root> ; Task: Promise.then ; Value: RangeError: Maximum call stack size exceeded. ChangeDetector_DashboardComponent_0

viewFactory_DashboardComponent0
viewFactory_HostDashboardComponent0
createHostViewInContainer@file:///var/mobile/Containers/Data/Application/956DEEEF-17A4-43CF-B2C5-1ACB29B8EA76/Library/Application%20Support/Forge/assets-216AAE18-7A5E-40F0-BEB9-994B69237FD5/src/scripts/angular2.dev.js:6723:45
createHostView@file:///var/mobile/Containers/Data/Application/956DEEEF-17A4-43CF-B2C5-1ACB29B8EA76/Library/Application%20Support/Forge/assets-216AAE18-7A5E-40F0-BEB9-994B69237FD5/src/scripts/angular2.dev.js:6205:42
file:///var/mobile/Containers/Data/Application/956DEEEF-17A4-43CF-B2C5-1ACB29B8EA76/Library/Application%20Support/Forge/assets-216AAE18-7A5E-40F0-BEB9-994B69237FD5/src/scripts/angular2.dev.js:12419:55
run@file:///var/mobile/Containers/Data/Application/956DEEEF-17A4-43CF-B2C5-1ACB29B8EA76/Library/Application%20Support/Forge/assets-216AAE18-7A5E-40F0-BEB9-994B69237FD5/src/scripts/zone.min.js:1:18045
file:///var/mobile/Containers/Data/Application/956DEEEF-17A4-43CF-B2C5-1ACB29B8EA76/Library/Application%20Support/Forge/assets-216AAE18-7A5E-40F0-BEB9-994B69237FD5/src/scripts/zone.min.js:1:28176
runTask@file:///var/mobile/Containers/Data/Application/956DEEEF-17A4-43CF-B2C5-1ACB29B8EA76/Library/Application%20Support/Forge/assets-216AAE18-7A5E-40F0-BEB9-994B69237FD5/src/scripts/zone.min.js:1:18749
o@file:///var/mobile/Containers/Data/Application/956DEEEF-17A4-43CF-B2C5-1ACB29B8EA76/Library/Application%20Support/Forge/assets-216AAE18-7A5E-40F0-BEB9-994B69237FD5/src/scripts/zone.min.js:1:15791
invokeTask@file:///var/mobile/Containers/Data/Application/956DEEEF-17A4-43CF-B2C5-1ACB29B8EA76/Library/Application%20Support/Forge/assets-216AAE18-7A5E-40F0-BEB9-994B69237FD5/src/scripts/zone.min.js:1:24729
d@file:///var/mobile/Containers/Data/Application/956DEEEF-17A4-43CF-B2C5-1ACB29B8EA76/Library/Application%20Support/Forge/assets-216AAE18-7A5E-40F0-BEB9-994B69237FD5/src/scripts/zone.min.js:1:7037
v@file:///var/mobile/Containers/Data/Application/956DEEEF-17A4-43CF-B2C5-1ACB29B8EA76/Library/Application%20Support/Forge/assets-216AAE18-7A5E-40F0-BEB9-994B69237FD5/src/scripts/zone.min.js:1:7277

My package.json:
{
  "name": "Daysi",
  "version": "1.0.0",
  "scripts": {
    "start": "concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "lite": "lite-server",
    "typings": "typings",
    "postinstall": "typings install"
  },
  "license": "ISC",
  "dependencies": {
    "angular2": "2.0.0-beta.11",
    "crypto-js": "^3.1.6",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.35.0",
    "jquery": "^3.4.1",
    "ng2-translate": "^1.11.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "systemjs": "0.19.24",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "gulp": "^4.0.0",
    "lite-server": "^2.5.3",
    "typescript": "^1.8.9",
    "typings": "^0.7.9"
  }
}

Note: We are using trigger.io platform to Build native apps for iOS and Android and also used some builtin trigger modules and because of these in web our application is not working properly, so to run our app we need simulator or device to compile and run the app, That's why I didn't attach my project code.

Please help me to get this issue fix asap as our customers doesn’t use the app at all because of this issue.

Thanks in advance,
Sagar

**Comment by antch** [comment]
This should be posted on somewhere like StackOverflow, not here. If you think it's a legitimate bug with Angular, you should resubmit and use the template that's provided along with a minimal reproduction. Either way there is absolutely no way anybody would be able to help with your problem given the very limited information you provided.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
