### ISSUE TITLE
ViewChildren QueryList should run change detection when count changes

### ISSUE THREAD

**Issue by clabough** [angular/angular#30922]
# 🐞 bug report

### Description

 
When the visibility (e.g. *ngIf) of a component changes during the change detection cycle, the length of a `QueryList` may change. The new length is only correct in the `ngAfterViewChecked()` event, but then it is too late to make any view changes. If the length of any of the QueryLists changes during the change detection cycle, it seems to me that another cycle should be run automatically. I can manually check for this and use `setTimeout()` to run another cycle, but this smells hacky. I think another cycle should be automatic.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-uj7lnn

In the stackblitz, if you uncomment out the noted line in `ngAfterViewChecked()` or if you click the `run change detection` button, the count in the console is correct.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.2
Node: 12.3.1
OS: win32 x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.2
@angular-devkit/build-angular     0.800.2
@angular-devkit/build-optimizer   0.800.2
@angular-devkit/build-webpack     0.800.2
@angular-devkit/core              8.0.2
@angular-devkit/schematics        8.0.2
@angular/cli                      8.0.2
@ngtools/webpack                  8.0.2
@schematics/angular               8.0.2
@schematics/update                0.800.2
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Comment by Airblader** [comment]
You could also bind to `(textboxes.changes | async).count`.

**Comment by alxhub** [comment]
The problem is we _don't_ want to automatically run a CD cycle, because most of the time the user doesn't care or depend on the length changing. Yes, it's more manual work in the (somewhat rare) case that you do want to re-run CD after a query updates, but it avoids a performance issue that would be impossible to avoid otherwise.

**Comment by pkozlowski-opensource** [comment]
I will side with @alxhub here - the purpose of view queries, in general, is to give you access to the nodes of a _rendered_ view. And to render a view Angular needs to run change detection as what gets rendered is driven by model update mapped to DOM operations. Typically a sequence of events will be:
- a user interact with a page and DOM event fires;
- model is mutated in an event handler;
- Angular runs change detection, determines which part of the model have changed and updates view (DOM) - this is the point at which _view_ query results are ready.

It sounds like you want to drive view rendering by ... results of view rendering and this is not how we think about change detection. 

It is hard to purpose a good solution without fully understanding the functional use-case so if you could elaborate on what you are trying to do (functionally speaking), maybe we could suggest an alternative approach.

**Comment by clabough** [comment]
@alxhub @pkozlowski-opensource I want to display a message based upon the visible elements in a QueryList, but because the results of the QueryList are only correct in the ngAfterViewChecked() event, it's too late to display a message.

I do want the nodes in the _rendered_ view, but in the lifecycle events that occur while I can change the view, the QueryList is incorrect, that's why I'm asking for it to run change detection again if the QueryList count changes between ngDoCheck() and ngAfterViewChecked().

Right now I have to manually compare the count between the two events and if they're different, use SetTimeout() to run another change detection cycle.

**Comment by pkozlowski-opensource** [comment]
> I want to display a message based upon the visible elements in a QueryList

@clabough but I feel like this is "wrong" approach in the sense that UI is not model driven any more (and this is what Angular and other frameworks are all about). 

In your example stackblitz it _seems_ like you should display your message based on the `show` expression (one used by `ngIf`) - basically a displayed list changes in response to model changes and you should use the same source (model) to display your message.

**Comment by clabough** [comment]
@pkozlowski-opensource Yeah, I'd do that in a simple example like this, but in my real use case, I have a very large dynamic form that shows/hides many elements and nested elements based upon many conditions and I'm validating only those that are visible. I discovered this issue when in my first version it was saying the form was invalid because it was including elements that were hidden.

 I created the StackBlitz to show the basic issue. Sounds like I'm going to have to continue using SetTimeout. I figured there were other times when people want to use QueryList and wouldn't realize that it's including hidden elements until the ngAfterViewChecked() event.

**Comment by pkozlowski-opensource** [comment]
After thinking about this one we are _not_ going to implement this suggestion as it would _really_ mean that UI drives rendering of UI. This would be a slippery path towards maintenance and performance problems.

I do understand the use-case and the desire to simplify the development by querying a number of fields that get rendered based on the model. But in this case I strongly believe that this is "wrong" simplification that will bite you down the line. We don't want to enable / promote this patter for Angular users.
