### ISSUE TITLE
product-details.component.html doesn't work

### ISSUE THREAD

**Issue by GuodongH** [angular/angular#30923]
# 📚 Docs or angular.io bug report

### Description

 
Follow the start document. But the routing part doesn't  display the product details. It only show "Product Details" headline, but no details at all.

### What's the affected URL?**
 https://angular.io/start/routing#using-route-information

## 📷Screenshot

![Snipaste_2019-06-07_13-25-51](https://user-images.githubusercontent.com/28574559/59122159-0bbacf00-8928-11e9-8fc3-f2b0e9221528.jpg)

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Browser info

using https://stackblitz.com

**Comment by brandonroberts** [comment]
@GuodongH share you stackblitz URL so we can take a look.
