### ISSUE TITLE
HttpClient POST request body changes \n to ↵

### ISSUE THREAD

**Issue by yroc92** [angular/angular#30933]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/common/http

### Is this a regression?
No.

### Description
Sending a post body that either is a string or is an object that has a string as a value will replace any occurrence of "\n" with "↵".

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-uzxank

## 🔥 Exception or Error
No actual error is thrown.

## 🌍  Your Environment

**Angular Version:**
(Same issue persists in the stackblitz example (see `package.json`).
<pre><code>
Angular CLI: 7.3.8
Node: 10.15.3
OS: darwin x64
Angular: 7.2.13
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/animations               7.2.14
@angular/cdk                      7.3.7
@angular/cli                      7.3.8
@angular/material                 7.3.7
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**
Chrome 74.0.3729.169

**Comment by trotyl** [comment]
Would you mind simply click the "view source" button?

**Comment by yroc92** [comment]
I'm not sure what you are referring to exactly? View Page Source in the stackblitz example?

**Comment by yroc92** [comment]
Ah, I found a "View Source" button that you're referring to in the Inspector.

**Comment by yroc92** [comment]
Must be an issue with my server then. Thanks!
