### ISSUE TITLE
[Ivy] Binding to SafeStyle values does not work

### ISSUE THREAD

**Issue by jonrimmer** [angular/angular#30930]
# 🐞 bug report

### Affected Package

`@angular/compiler` I guess.

### Is this a regression?

Works without Ivy.

### Description

It should be possible to bind `SafeStyle` values returned by `DomSanitizer.bypassSecurityTrustStyle()` using `[style.foo]` bindings in a template, and `@HostBinding('style.foo')` in the component class. When Ivy is enabled, neither of these binding mechanisms work.

## 🔬 Minimal Reproduction

```ts
constructor(private sanitizer: DomSanitizer) {}

@HostBinding('style.color') color: SafeStyle;

ngOnInit() {
  this.color = this.sanitizer.bypassSecurityTrustStyle('red');
}
```

Full example: https://github.com/jonrimmer/ivy-hostbinding

## 🔥 Exception or Error

No error is emitted, but the bindings do not work.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.2
Node: 12.3.1
OS: darwin x64
Angular: 8.1.0-next.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.2
@angular-devkit/build-angular     0.800.2
@angular-devkit/build-optimizer   0.800.2
@angular-devkit/build-webpack     0.800.2
@angular-devkit/core              8.0.2
@angular-devkit/schematics        8.0.2
@angular/cli                      8.0.2
@ngtools/webpack                  8.0.2
@schematics/angular               8.0.2
@schematics/update                0.800.2
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by IgorMinar** [comment]
Hi @jonrimmer, thanks for the bug report.

I was able to verify that with 9.0.0-rc.1 this works properly. If you still see issues, please file a new issues and provide a reproduction. Thank you!

**Comment by kolkov** [comment]
@IgorMinar Still the same issue? https://github.com/angular/angular/issues/34023
