### ISSUE TITLE
ViewEncapsulation.ShadowDom causes a blocked frame with origin "https://www.google.com" from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by apesteguy** [angular/angular#30944]
# 🚀 feature request

### Relevant Package

@angular-devkit/architect    0.13.7 (cli-only)
@angular-devkit/core         7.3.7 (cli-only)
@angular-devkit/schematics   7.3.7 (cli-only)
@schematics/angular          7.3.7 (cli-only)
@schematics/update           0.13.7 (cli-only)
rxjs                         6.4.0
 "ng-recaptcha": "^4.3.0"

### Description
I am trying to display google ``reCAPTCHA`` inside specifics components from my application. 

- For some reasons, I must encapsulate some components from my application. To do that I am using ``ViewEncapsulation.ShadowDom``. 

- From the ``app.module.ts`` I have installed ``RecaptchaModule``, a [package ](https://www.npmjs.com/package/ng-recaptcha) that handles reCAPTCHA. 

My issue is about the ``reCAPTCHA`` <=> ``ViewEncapsulation.ShadowDom``. 

From what I can tell, the ``ViewEncapsulation.ShadowDom`` blocks the iframe reCAPTCHA from google to work as expected. 

If I remove the ``ViewEncapsulation.ShadowDom`` from my component everything works fine :-)
But if I add the ``ViewEncapsulation.ShadowDom`` and then run the application the console displays the following issue message: 
> recaptcha__en.js:527 Uncaught DOMException: Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame. 

Does the use  of ``ShadowDom``  means that we cannot use frames ? Is there another way to use frames ?

**Comment by trotyl** [comment]
reCAPTCHA doesn't supports Shadow DOM, there's nothing a framework can do to handle it.
The only option is to not use Shadow DOM.

See https://github.com/GoogleWebComponents/google-recaptcha/issues/4 for more information.

**Comment by apesteguy** [comment]
Thanks @trotyl for the quick answer and documention link. I expected (and feared!) that answer :-)
