### ISSUE TITLE
Ivy preview report. error TS2339: Property 'config' does not exist on type 'HTMLElement'

### ISSUE THREAD

**Issue by kolkov** [angular/angular#30945]
I try to compile complex project with libs and get an error:

```
ERROR in src/app/app.module.ts(34,12): error TS-991010: Value at position 2 in the NgModule.importss of AppModule is not a reference: [object Object]
src/__ng_typecheck__.ts(269,10): error TS2339: Property 'config' does not exist on type 'HTMLElement'.
```

![image](https://user-images.githubusercontent.com/3740898/59188787-28057880-8b81-11e9-802c-33e28eadd9ee.png)

```
@NgModule({
  declarations: [
    AppComponent,
    NotFoundComponent,
    HomeComponent,
    NewsComponent,
    HomeNewsComponent,
    BreadcrumbsComponent,
  ],
  imports: [
    BrowserModule,
    HttpClientModule,
    NgxMetrikaModule.forRoot({
      id: environment.yaCounterId,
      defer: true,
      webvisor: true,
      clickmap: true,
      trackLinks: true,
      accurateTrackBounce: true,
    }
      ),
    CompanyModule,
    CatalogModule,
    ServicesModule,
    ServiceCenterModule,
    BlogModule,
    CartModule,
    AppRoutingModule,
  ],
  providers: [
    {
      provide: LOCALE_ID,
      useValue: 'ru'
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

```
Angular CLI: 8.0.2
Node: 11.14.0
OS: win32 x64
Angular: 8.1.0-next.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.2
@angular-devkit/build-angular      0.800.2
@angular-devkit/build-ng-packagr   0.800.2
@angular-devkit/build-optimizer    0.800.2
@angular-devkit/build-webpack      0.800.2
@angular-devkit/core               8.0.2
@angular-devkit/schematics         8.0.2
@angular/cdk                       7.3.7
@angular/cli                       8.0.2
@angular/material                  7.3.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.2
@schematics/angular                8.0.2
@schematics/update                 0.800.2
ng-packagr                         5.3.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0


D:\Go\src\kassar\ui>
```
Libs:
https://github.com/kolkov/ngx-dadata
https://github.com/kolkov/ngx-metrika

**Comment by JoostK** [comment]
Are your libs published to `node_modules` or are they resolved to a `dist` folder using `paths`-mapping? The latter is not supported currently and is tracked here: https://github.com/angular/angular-cli/issues/14594. Could you please check if the workaround described in https://github.com/angular/angular-cli/issues/14594#issuecomment-497288501 works around the issue?

**Comment by kolkov** [comment]
Thanks! Yes its from `dist` folder:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "importHelpers": true,
    "module": "esnext",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,

    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "paths": {
      "@kolkov/ngx-metrika": [
        "dist/kolkov/ngx-metrika"
      ],
      "@kolkov/angular-editor": [
        "dist/kolkov/angular-editor"
      ],
      "@kolkov/ngx-dadata": [
        "dist/kolkov/ngx-dadata"
      ],
      "@kolkov/ngx-dadata/*": [
        "dist/kolkov/ngx-dadata/*"
      ],
      "@kolkov/translit": [
        "dist/kolkov/translit"
      ],
      "@kolkov/translit/*": [
        "dist/kolkov/translit/*"
      ]
    }
  }
}

```
But after:
```
D:\Go\src\kassar\ui>.\node_modules\.bin\ivy-ngcc -s .\dist
Warning: Entry point '@kolkov/ngx-metrika' contains deep imports into 'D:/Go/src/kassar/ui/node_modules/rxjs/internal/BehaviorSubject'. This is probably not a problem, but may cause the compil
ation of entry points to be out of order.
Compiling @kolkov/angular-editor : fesm2015 as esm2015
Compiling @kolkov/angular-editor : fesm5 as esm5
Compiling @kolkov/angular-editor : esm2015 as esm2015
Compiling @kolkov/angular-editor : esm5 as esm5
Compiling @kolkov/angular-editor : main as umd
Compiling @kolkov/ngx-dadata : fesm2015 as esm2015
Compiling @kolkov/ngx-dadata : fesm5 as esm5
Compiling @kolkov/ngx-dadata : esm2015 as esm2015
Compiling @kolkov/ngx-dadata : esm5 as esm5
Compiling @kolkov/ngx-dadata : main as umd
Compiling @kolkov/ngx-metrika : fesm2015 as esm2015
Compiling @kolkov/ngx-metrika : fesm5 as esm5
Compiling @kolkov/ngx-metrika : esm2015 as esm2015
Compiling @kolkov/ngx-metrika : esm5 as esm5
Compiling @kolkov/ngx-metrika : main as umd

D:\Go\src\kassar\ui>
```

![image](https://user-images.githubusercontent.com/3740898/59193314-f3e48480-8b8d-11e9-8972-bc5e9967dbd6.png)

Whats wrong?

**Comment by JoostK** [comment]
That's a good question. There's PR #30181 for making sense of that last remaining message. It looks like there's a `<ngx-da-data [config]="config">` in a template somewhere, that either failed to be matched to the `NgxDaDataComponent` component (could be that the component is not visible from the `NgModule` that the component is declared in) or there's something wrong with that component. I'm not sure if that's helpful, however I can't really tell what exactly is going on here.

**Comment by kolkov** [comment]
Yes! It's my problem. I commented this module when debug other errors )
![image](https://user-images.githubusercontent.com/3740898/59195484-c9e29080-8b94-11e9-82f9-28c39a51f0a9.png)
![image](https://user-images.githubusercontent.com/3740898/59195556-f696a800-8b94-11e9-96d3-fcae8be5b91b.png)
Thanks!
Bud I got enother problem in runtime:
`ERROR Error: NullInjectorError: No provider for InjectionToken ngx-metrika Config!`

**Comment by kolkov** [comment]
Thanks! It's from direct path to library...
change direct path to
`import {CommonOptions, NgxMetrikaService} from '@kolkov/ngx-metrika';`
fixed this last error
I am on Ivy now!
https://kassar.ru/main-es2015.b8c6ffdd5e36f2c23e1c.js
https://kassar.ru/ is this correct Ivy bundle?

**Comment by JoostK** [comment]
Great that you have it sorted. The fact that the `InjectionToken` failed to resolve due to a faulty import path could be because you'd end up with multiple instances of the token: one correctly from the library bundle and the other one from library source files that leaked into the application using the direct imports. Not sure though.

That bundle does in fact look like Ivy to me. I am not very good at looking into minified code though 😉 

I will go ahead and close this issue, as the actual issues you experienced are already being tracked. Thank you for trying Ivy!
