### ISSUE TITLE
serve(aot): with Ivy, does not detect changes to files

### ISSUE THREAD

**Issue by Splaktar** [angular/angular#30947]
# 🐞 Bug report

### Command
```
- [x] serve
```

### Is this a regression?
Yes? I didn't use AOT for dev mode serving previously because it wasn't as performant as it is now in Ivy.

### Description
The [Ivy Guide](https://angular.io/guide/ivy) suggests enabling `"aot": true` for dev mode builds.

What I’m finding during that experience is that while the rebuilds are super fast in Dev mode (`aot: true`), the Angular CLI often doesn’t pick up changes to SCSS and HTML. I need to constantly re-run `ng serve` over and over again to see my changes. It’s not the kind of DX that we’re looking for. 

Changing back to `aot: false` works around this issue.

## 🔬 Minimal Reproduction
- https://github.com/angular-hispano/angular-hispano/tree/enableIvy
- `npm start`
- Make changes to files like the following and see that the build reports
```sh
Date: 2019-06-09T02:07:26.153Z - Hash: fd4823b00365cd497714 - Time: 192ms
7 unchanged chunks
ℹ ｢wdm｣: Compiled successfully.
```
But the changes aren't reflected in the browser.

Change
https://github.com/angular-hispano/angular-hispano/blob/18c79aaf9c075feea4bdff7c3e3f39e08f88db2e/projects/web/src/app/landing/landing.component.html#L30-L31
to
```html
<section id="call-to-action">
```
Change
https://github.com/angular-hispano/angular-hispano/blob/d5be179b0b7a428c0a9225862df33caafb330ce8/projects/web/src/app/landing/landing.component.scss#L10-L12
to
```scss
    &#call-to-action {
      display: flex;
      flex-flow: row wrap;
      padding-top: 24px;
    }
```

## 🔥 Exception or Error
None

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.2
Node: 12.3.0
OS: darwin x64
Angular: 8.1.0-next.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.2
@angular-devkit/build-angular     0.800.2
@angular-devkit/build-optimizer   0.800.2
@angular-devkit/build-webpack     0.800.2
@angular-devkit/core              8.0.2
@angular-devkit/schematics        8.0.2
@angular/cdk                      8.0.0
@angular/cli                      8.0.2
@angular/fire                     5.2.1
@angular/material                 8.0.0
@ngtools/webpack                  8.0.2
@schematics/angular               8.0.2
@schematics/update                0.800.2
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**
Related to https://github.com/angular/angular-cli/issues/6347

Browser: Chrome Stable Version 75.0.3770.80 (Official Build) (64-bit)
OS: macOS Mojave
Package Manager: NPM

**Comment by filipesilva** [comment]
I think we missed testing for this on the CLI because we do e2e for ivy, but some of our tests (including the more elaborate rebuild ones) are not e2e.

**Comment by petebacondarwin** [comment]
Ahah! Yes, we do not include external template files as dependencies of a compiled file!
