### ISSUE TITLE
route animation doesn't work in IE after upgrade to version 8

### ISSUE THREAD

**Issue by Seemspyo** [angular/angular#30940]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/animations

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 7.2.12

### Description

 I have upgrade my front-end project to version 8. But route animation doesn't work in IE since upgrade. Other animation works fine. On the IE console it says [ cannot find "position" of null / cannot find "toString" of null ]

## 🔬 Minimal Reproduction

 https://github.com/Seemspyo/Slacking-studio/tree/master/front-end

## 🔥 Exception or Error
<pre><code>

cannot find "position" of null
cannot find "toString" of null
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

 8.0.1

</code></pre>

**Anything else relevant?**
 IE 11, IE 10, IE 9

**Comment by anuradhawick** [comment]
Are you using lazy loading of modules?

**Comment by Seemspyo** [comment]
> Are you using lazy loading of modules?

No. I didn't use lazy loading modules on this project.

**Comment by jelbourn** [comment]
Closing this because we're ending support for IE9 and IE10 in Angular v11 and old Edge-related issues have most likely been fixed in the newer Chromium-based versions of Edge.

**Comment by jelbourn** [comment]
Whoops, this one has IE11.

**Comment by dario-piotrowicz** [comment]
@jelbourn with Angular v13 out (and IE11 finally gone) can this issue be closed? :slightly_smiling_face:

**Comment by gkalpak** [comment]
Thx, @dario-piotrowicz! Closing since Angular v13 does [no longer support IE11][1].
If you run into a similar problem on a supported browser, please open a new issue.) 

[1]: https://angular.io/guide/browser-support
