### ISSUE TITLE
Angular Elements: DOMException when embedding other angular app

### ISSUE THREAD

**Issue by xyfer** [angular/angular#30951]
# 🐞 bug report

### Affected Package
@angular/elements

### Is this a regression?
No

### Description

Our use case is to create an angular agnostic shell that would be able to contain other web applications inside of it. I thought one possible candidate for this type of web app would be Angular Elements, since they are supposed to be agnostic and not interfere with the frameworks / scripts of other web applications.

Unfortunately, when trying to embed an angular-cli generated application within a website containing Angular Elements, we get the following error:

`Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry`

If ONE of the apps (The angular elements app or the angular-cli app) changes it's `"optimizations"` property in package.json to false, there will be no issue. Note: these optimizations are only triggered when running with the `--prod` flag when doing `ng build`

Building both in production mode with the flag set to true (The default setting) results in this error.

## 🔬 Minimal Reproduction

**Combined app index.html:**

```
<!DOCTYPE html>
<html lang="en">
<body>
<app-custom-element></app-custom-element>
<script src="./angular8app.js"></script>
<!-- EMBEDDED APP START -->
   <app-root></app-root>
   <script type="text/javascript" src="./runtime-es5.js"></script><script type="text/javascript" 
   src="./main-es5.js"></script>
<!-- EMBEDDED APP END -->
</body>
</html>
```

**Angular Element app.module:**

```
import { BrowserModule } from '@angular/platform-browser';
import { CUSTOM_ELEMENTS_SCHEMA, NgModule, Injector } from '@angular/core';
import { CustomComponent } from './custom/custom.component';
import { createCustomElement } from '@angular/elements';

@NgModule({
  declarations: [
    CustomComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [],
  entryComponents: [CustomComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class AppModule {
  constructor(injector: Injector) {
    const customElement = createCustomElement(CustomComponent, {injector});
      customElements.define('app-custom-element', customElement);
  }
  ngDoBootstrap() {}
}
```

**batch script to create concatenated angular8app.js:**
`ng build angular8-custom --prod --output-hashing=none && type "dist\angular8-custom\runtime-es2015.js" "dist\angular8-custom\polyfills-es2015.js" "dist\angular8-custom\scripts.js" "dist\angular8-custom\main-es2015.js" > "output\angular8app.js"`

**angular8app.js**: The script file for the angular element app, which is a concat of "runtime.js, main.js and polyfills.js"

**app-custom-element**: The custom element tag, defined in app.module

**app-root**: The app root of the embedded angular8 cli generated application.

**Other scripts**: Scripts for the angular8 cli generated application.

_Angular CLI app is all boilerplate / exactly what is generated from angular-cli_

## 🔥 Exception or Error
`Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry`

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 8.0.2
Node: 10.15.3
OS: win32 x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.2
@angular-devkit/build-angular     0.800.2
@angular-devkit/build-optimizer   0.800.2
@angular-devkit/build-webpack     0.800.2
@angular-devkit/core              8.0.2
@angular-devkit/schematics        8.0.2
@angular/cli                      8.0.2
@ngtools/webpack                  8.0.2
@schematics/angular               8.0.2
@schematics/update                0.800.2
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

**Anything else relevant?**

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/23732#issuecomment-388670907. Now I can't say how much things have changed since then, Rob can say more for sure.

**Comment by xyfer** [comment]
Leveraging the `output.JsonpFunction` described [here](https://github.com/webpack/docs/wiki/configuration) might be useful.

Looking to see if the angular CLI can access this configuration property.

**Comment by gkalpak** [comment]
This is essentially the same as #36028. Let's track this usecase in #36028, so we have a single point of reference.
