### ISSUE TITLE
[ng update] Allow specifying path to tsconfig file

### ISSUE THREAD

**Issue by Melmoth-the-Wanderer** [angular/angular#30952]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 Considering there is a project with tsconfig.ts file somewhere deep in folder structure. Node_modules folder and package.json file lays in the root of an application. When running "ng update" command from the root of an application it will update package.json and throw an error saying "Could not find any tsconfig file. Cannot migrate DOCUMENT to new import source". Which is obvious, since there is no single tsconfig on the root, but multiple tcsonfig files across the application.

### Describe the solution you'd like
 It would be great if we could run migration tool specifying a path to tsconfig.ts file.

### Describe alternatives you've considered
 Updating all files manually is painful. The folder structure is designed this way for a reason and is unlikely to be changed.

**Comment by Melmoth-the-Wanderer** [comment]
Same happens for @angular/material:
`Could not find any tsconfig file. Please submit an issue on the Angular Material repository that includes the path to your "tsconfig" file.`

**Comment by devversion** [comment]
The migrations are actually looking at the `angular.json` file for build targets which reference a `tsconfig` file. I'm also a fan of supporting an update flag for the tsconfig, but right now the goal is that `ng update` updates all projects which are part of the `angular.json` (workspace config).

Can you provide a bit more context? Isn't that `tsconfig` somewhere referenced in a build target?

**Comment by Melmoth-the-Wanderer** [comment]
@devversion It is pretty uncommon approach we took. Our application is a legacy .net app with some Angular features inside. Across the application there are **two angular apps**:
1) **one is build via angular cli**. It utilizes routing to load up components within already rendered gui. It serves small reusable actions (usually modals/sliders) available in many places.
2) **the other one is build via webpack**. It collects couple of bigger stand-alone angular features. (which are also injected in already rendered gui but they replace 90% of it).

The only **things** they have **in common** are: `package.json`, `node_modules` and `tsconfig.json` (which each of these angular apps are extending).

In conclusion, **there is no single angular.json file on package.json level** in the folder tree. The tree is something like this:
```
- /root/
    - package.json
    - node_modules/
    - webui/
        - scripts/
            - src/
                - angular1
                     - src/ (angular files)
                     - angular.json
                     - tsconfig.json (extending ./../tsconfig.json)
                - angular2/
                    - feature1/
                        - app/ (angular sources)
                        - angular.json (uses ./../tsconfig.json)
                    - feature2/ (...)
                    - feature3/ (...)
                    - tsconfig.json (extending ./../tsconfig.json)
                    - webpack.config.js
                - tsconfig.json
```

_We are also using some few other angular libraries which are published in our private npm repository, but they are structured in common manner and works fine with ng update_.

**Comment by alxhub** [comment]
I think the root issue here is attempting to apply an `ng update` migration to a non-CLI application? I don't believe we support this use case today. You might have some luck running the migration scripts manually, but I don't know off the top of my head how to do this.
