### ISSUE TITLE
HTML5LocationStrategy fails to update path on router.navigate

### ISSUE THREAD

**Issue by bryantharpe** [angular/angular#3096]
It appears that only the HashLocationStrategy updates the url on calls to router.navigate. When I change my LocationStrategy to the HTML5LocationStrategy the urls no longer update when navigating from *"/products/:productId" -> "/"*. The navigation does occur, though.

This is happening on Alpha.31.

The code I'm using is below.

# Component Controller code
````javascript
    updateProduct(product: {productId:string, name:string, description:string}) {
        this.productStore.updateProduct(product);

        this.router.navigate('/');
    }
````

# Routes
```javascript
@RouteConfig([
    {path: '/', component: ProductsList, as: 'Products'},
    {path: '/products/:productId', component: UpdateProducts, as: 'UpdateProducts'}
])
```

# Bootstrap
````javascript
import { httpInjectables } from 'angular2/http';
import { bootstrap, bind } from 'angular2/angular2';
import { routerInjectables, LocationStrategy, HashLocationStrategy, HTML5LocationStrategy } from 'angular2/router';
import { Onboarding } from './components/onboarding/onboarding';


bootstrap(Onboarding, [
    httpInjectables,routerInjectables, bind(LocationStrategy).toClass(HTML5LocationStrategy )
]);
````

**Comment by Zyzle** [comment]
Does your entry point page specify a `<base>` tag?  I found similar behaviour a few milestones back (~28 I think) when my app didn't have the base tag.

**Comment by bryantharpe** [comment]
Thanks for the tip. I just added a base tag and it works now.  Is that always going to be required for the HTML5 Strategy? Not exactly hard to add to the page, so, not that big of a deal.

**Comment by btford** [comment]
@bryantharpe you either have to add a `<base>` tag or set an app base href like this: https://github.com/angular/angular/blob/master/modules/angular2/test/router/router_integration_spec.ts#L78-L90

Currently the router uses `document.baseURI` to determine the base URI. I think it might be better to remove this option entirely and make the app base href binding required.

**Comment by bryantharpe** [comment]
Thanks for the input @btford That makes more sense, I went ahead and updated my code to work like that.
