### ISSUE TITLE
v7 Angular.io CLI commands section not accessible 

### ISSUE THREAD

**Issue by jreidgreer** [angular/angular#30964]
# 📚 Docs or angular.io bug report

### Description

When using v7 of the Angular.io docs, I'm unable to access the CLI Commands section of the documentation, and instead I'm redirected to the primary `/docs` page.

### What's the affected URL?**
https://v7.angular.io/cli/test

(or any `/cli/*` URL)

### Reproduction Steps**
Attempt navigation to [https://v7.angular.io/cli/test](https://v7.angular.io/cli/test). The application will redirect to https://v7.angular.io/docs.

### Expected vs Actual Behavior**

I would expect the application to load the proper content for `/cli/test` instead of redirecting.

## 🔥 Exception or Error
There is no exception thrown in the code, nor is there a failed network call.

### Browser info

Doesn't appear so. Same behavior in:

- Chrome 75
- Safari 12.1.1
- Firefox 67

**Comment by IgorMinar** [comment]
@gkalpak's PR #30894 addressed this

https://v7.angular.io/cli/test now works. thanks George!
