### ISSUE TITLE
Can't resolve modules from custom path

### ISSUE THREAD

**Issue by tbnovaes** [angular/angular#30978]
# 🐞 bug report

### Description

When trying to serve the app using custom paths on tsconfig.json for some libs I created everything works fine, however, when trying to build it using AOT, I get multiple errors:

```
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'some_module' in 'some_path '
```

Works fine when AOT is set to false.

### Additional Information

Here is my tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      //Env
      "@env/*": ["src/environments/*"],

      //Libs
      "@lib/pipes": ["dist/pipes"],
      "@lib/pipes/*": ["dist/pipes/*"],
      "@lib/utils": ["dist/utils"],
      "@lib/utils/*": ["dist/utils/*"],
      "@lib/directives": ["dist/directives"],
      "@lib/directives/*": ["dist/directives/*"],
      "@lib/models": ["dist/models"],
      "@lib/models/*": ["dist/models/*"],
      "@lib/websocket": ["dist/websocket"],
      "@lib/websocket/*": ["dist/websocket/*"],
      "@lib/intl-phone-input": ["dist/intl-phone-input"],
      "@lib/intl-phone-input/*": ["dist/intl-phone-input/*"]
    }
  }
}
```

## 🌍  Your Environment
```
**Angular Version:**
Angular CLI: 8.0.0
Node: 12.3.1
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.800.0
@angular-devkit/core         8.0.0
@angular-devkit/schematics   8.0.0
@schematics/angular          8.0.0
@schematics/update           0.800.0
rxjs                         6.4.0
```

**Comment by tbnovaes** [comment]
@trotyl @jotatoledo I haven't understand the thumbs down... if you know a solution/workaround would you please be able to post it here, so we can close the issue?

**Comment by jotatoledo** [comment]
Provide a repro...

**Comment by tbnovaes** [comment]
@jotatoledo here is a repo reproduction the issue:

https://github.com/tbnovaes/CustomPathIssue

`npm install`
`npm run build` => will build the lib and app

The steps I followed to reproduce it were:

1- Create a new project with the cli
2- Create a new library with the cli
3- Modify the tsconfig.json to use `@lib/my-lib` as path
3- Import the library on app.module.ts
4- Build the library
5- Build the app with `--prod` flag
6- Error happens around 90% of the build process

**Comment by alxhub** [comment]
Changing the path mapping is not enough to change the entrypoint name of the library. You also have to edit `package.json` for `projects/my-lib/package.json` and change the name there. Then your repro will work.

Hope this helps!
