### ISSUE TITLE
Function calls are not supported in decorators but 'makePropDecorator' was called.

### ISSUE THREAD

**Issue by Gajendrasinh** [angular/angular#30988]
Hello

Recently i have migrate from 7 to 8,

I am getting below error when running ng build --pord 

ERROR in Error during template compile of 'Input'
  Function calls are not supported in decorators but 'makePropDecorator' was called.

Can you help to how i can i fix this.

Thank you.

**Comment by Splaktar** [comment]
This issue doesn't follow the issue template. Please revise or close this and open an issue that follows the template and provides a reproduction via StackBlitz or GitHub.

Also I think you meant `ng build --prod`.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
