### ISSUE TITLE
Tsc should not let public methods require parameters/return values of a private type during build

### ISSUE THREAD

**Issue by uber5001** [angular/angular#3098]
When running tsc manually against the sources in `modules/angular2`, these errors are given:

	src/change_detection/parser/lexer.ts(35,50): error TS4063: Parameter 'type' of constructor from exported class has or is using private name 'TokenType'.
	src/directives/ng_for.ts(94,34): error TS4070: Parameter 'tuples' of public static method from exported class has or is using private name 'RecordViewTuple'.
	src/directives/ng_for.ts(95,60): error TS4052: Return type of public static method from exported class has or is using private name 'RecordViewTuple'.
	src/directives/ng_for.ts(111,34): error TS4070: Parameter 'tuples' of public static method from exported class has or is using private name 'RecordViewTuple'.
	src/directives/ng_for.ts(112,55): error TS4052: Return type of public static method from exported class has or is using private name 'RecordViewTuple'.
	src/render/dom/compiler/selector.ts(301,35): error TS4073: Parameter 'map' of public method from exported class has or is using private name 'SelectorContext'.
	src/router/path_recognizer.ts(29,20): error TS4073: Parameter 'params' of public method from exported class has or is using private name 'TouchMap'.

These errors should be caught in the build step for angular2.

**Comment by alexeagle** [comment]
I had trouble reproducing this. But @mhegazy  is working to change our broccoli build to stop ignoring some TS errors, after which I think we'll have proper enforcement that this doesn't regress.
