### ISSUE TITLE
angular v8 Web Worker use problem

### ISSUE THREAD

**Issue by 1456118242** [angular/angular#30990]
I think web worker not load when I using

my ng build
![image](https://user-images.githubusercontent.com/18241022/59328842-0098e200-8d20-11e9-80ec-0318d700fba1.png)
normal  ng service
![image](https://user-images.githubusercontent.com/18241022/59328883-20300a80-8d20-11e9-9bbb-6efeb89aa31b.png)

Can someone help me with the following documents?  May be a configuration error?
Or not support for  ng build
[angular.json.txt](https://github.com/angular/angular/files/3279916/angular.json.txt)
[tsconfig.json.txt](https://github.com/angular/angular/files/3279917/tsconfig.json.txt)
[tsconfig.worker.json.txt](https://github.com/angular/angular/files/3279918/tsconfig.worker.json.txt)

**Comment by 1456118242** [comment]
This  is my use , Is it running on the server?  But Browser executed the code that  if (typeof Worker !== 'undefined')
![image](https://user-images.githubusercontent.com/18241022/59329606-dba56e80-8d21-11e9-8651-5e130995a759.png)

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
