### ISSUE TITLE
Why!

### ISSUE THREAD

**Issue by christophstockinger** [angular/angular#30995]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Say, how did you get the idea to write such a framework that a lot of people love it? 
It lacks a detailed documentation as well as good examples and the logic behind the whole architecture is also a not thought through system!

I wouldn't recommend it to anyone to use Angular.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by manekinekko** [comment]
If you need to learn about Angular, we have all the necessary documentation to help you get started at https://angular.io/docs.

Please know that by acting like this and posting such comments, you are in violation of our code of conduct: https://github.com/angular/angular/blob/master/CODE_OF_CONDUCT.md

**Comment by maartentibau** [comment]
@christophstockinger it saddens me to read these words. Angular might not be perfect and it doesn't claim to be. The docs have come a long way, but the amount of effort that was put into in to make it better should not be underestimated. 

But we do need to show respect to one another. If you do not like Angular and would never like to use it, that is perfectly fine, there is so much more to choose from.

But keep in mind that showing this disrespect towards the Angular core team and more importantly all the people contributing and maintaining this open source project is not cool. Feedback like this will not help in any way.

**Comment by jotatoledo** [comment]
You reminded me of the _Angry German Kid_ :smile:

**Comment by Bandito11** [comment]
I been using Angular since it was in beta 4 (I mean the OG Angular 2 beta 4) and the docs were just fine for me to start doing an app. I am not a native English speaker. The docs now are way and beyond better that it was at the time. At least there are more explanation about the packagesand ts configuration options. Before there wasn't even that

**Comment by willi84** [comment]
🇩🇪@christophstockinger möchtest du eine Doku auf Bayrisch? Mal ernsthaft, was soll dieses kindische Ticket?🇩🇪

@all: I am sorry for my countryman

**Comment by christophstockinger** [comment]
@willi84: Des is koa kindisches Verhalten sondern a ganz normale Feststellung, de i gmocht hob. Des is mei Meinung und des bleibt a aso.

I bin a Web Developa der sei eigenes Setup hom mog und sei zeig um a framework rundum bauen kann. So wia Vue beispielsweise. Es gibt aba Situationen bei dene ma mal Angular ausprobian mog. Hab des gmocht und einfach mei oben festgestellte Meinung geschildert!

PS: Du brauchst die für mich ned entschuldiga. I hob nichts foisch mocht und a nix mit dir zum do! 🥨

**Comment by willi84** [comment]
The tickets here are to report bugs or request features. Not for useless framework bashing or discussions u can do in a chat. Useless tickets, without any action or valuable feedback costs money and time. And as a CEO u should know that this is not cool. 
Give valuable feedback with specified snippets scenarios where your approach would be different. If u like vue. Then use vue.js. angular is not vue.js.

Btw: Its also a question of feedback culture. Just saying someone its all sh... ur doing is no valuable feedback, nothing this person can work with.

**Comment by christophstockinger** [comment]
okay.

**Comment by christophstockinger** [comment]
okay
