### ISSUE TITLE
Angular App windows authentication issue.

### ISSUE THREAD

**Issue by abhishekhingu** [angular/angular#31001]
Hi,

I am hosting my App Angular App using IIS. Angular App has many modules files.

I have enabled the Windows Authentication on site. When I browse application first time it prompting me for Windows Authentication.

After successful authentication application get load in browser, but Once I start navigating between modules Lazy loader try to new modules js file and again IIS server challenging for username and password.

Please let me know how can I resolve this issue.

**Comment by JohnnyDevNull** [comment]
Take a look at the Microsofts IIS documentation...

A authentication setup like yours is nothing default and makes only sense when you have no other choice. When you need some real authentication and it should be microsoft go for the single sign on server: https://docs.microsoft.com/en-gb/azure/active-directory/hybrid/how-to-connect-sso or build your own maybe with json-web-token like in this blog post: https://medium.com/engineerbabu/angular-authentication-using-jwt-d846c5ce0ac6

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by abhishekhingu** [comment]
Thanks for update 
@JohnnyDevNull 
We are trying to implement the on-premise solution. just one query can I achieve the same implementation by using Microsoft ADFS Service instead on Azure directory  service.

**Comment by JohnnyDevNull** [comment]
You can also use the standalone single sign on server. I am working with one at my company and it works very well with the local active directory.
