### ISSUE TITLE
Angular Multiple Routing

### ISSUE THREAD

**Issue by krashiel** [angular/angular#31004]
My case scenario is this
I have a navigation bar which should load another navigation bar(both navigation bars should be on my screen) which loads my content. I've been google-ing for two days i tried tons of things and none of them seem to work in my use case.
I tried using 2x router outlets(one main one with name='content'), 3x router outlets(one main one name='sidebar' one name='content'), none of them would work to load my content, i only managed to make first navigation bar to load the other navigation bar, or when clicking the second navigation bar would render my content but replaced the second navigation bar
If anyone did something like this and could help me with some info i would be grateful.

Angular CLI: 7.3.9
Node: 10.15.3
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/material                 7.3.7
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.2.4
webpack                           4.29.0

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
