### ISSUE TITLE
Reserve the namespace "angular" on npm

### ISSUE THREAD

**Issue by tbosch** [angular/angular#3101]
Right now, Angular only has the npm packages `angular` and `angular2`. However, npm introduced namespaces, which will allow to do things like `npm install @angular/framework`. 

The problem is that the namespace `angular` is owned by somebody else, see https://www.npmjs.com/~angular

We should ping that person and ask whether we could have the namespace...

**Comment by gdi2290** [comment]
:+1: 
and `npm install @angular/cli`

**Comment by mhevery** [comment]
@naomiblack can you reach out to the https://www.npmjs.com/~angular and https://www.npmjs.com/~ng owner and see if we can get them transferred to our ownership?

**Comment by naomiblack** [comment]
yes, I have pinged both.
