### ISSUE TITLE
Router redirect: query parameters not being resolved properly

### ISSUE THREAD

**Issue by brunojcm** [angular/angular#31025]
# 🐞 bug report

### Affected Package
@angular/router

### Is this a regression?
Not that I'm aware of.

### Description
I have a redirect configured like that:

```
const routes = [
  {
    path: '',
    component: AppComponent,
  },
  {
    path: 'b',
    component: AppComponent,
  },
  {
    path: 'a/:var',
    redirectTo: '/b?v=:var',
  },
]
```

If I navigate to `/a/1`, I get myself redirected to `/b?v=undefined` instead of `/b?v=1`, which is what I would expect.

I would not expect any difference in regards to angular router supporting `redirectTo: '/b/:var'`, which works perfectly, and supporting `redirectTo: '/b?v=:var'`. This is also supported by the fact that the output is `/b?v=undefined`, not `/b?v=` or even `/b?v=:var`, which means angular is trying to resolve the variable, it just doesn't find any value.

Does that make sense?

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-i73jrp

## 🔥 Exception or Error
No exception, weird behaviour explained above.

## 🌍  Your Environment

**Angular Version:**
Angular 8 (vide stackblitz)

**Anything else relevant?**
No

**Comment by jasonaden** [comment]
So one issue here is that you're using an absolute redirect (prefixing with `/`), and thus the redirect will ignore any query parameters and simply redirect directly to the URL provided.

I would try making this a relative redirect first and see if it works that way. Not 100% sure it will, but there's a much better chance that it would since it will *definitely* not work with absolute redirects.

If that doesn't solve your problem, please create a new issue.

**Comment by brunojcm** [comment]
@jasonaden, have you considered that I'm trying to create a new parameter in the URL, not keep one that already exists before the redirect (which is the unsupported case by the documentation when using absolute URLs)? I don't think your comment applies to this case and, with all due respect, you closed the issue a little bit prematurely. 

Having a "undefined" in a url redirect for a variable that exists does not seem right anyway, so something should be done, even if it is to improve/create a validation and corresponding error message.

I'm willing to help and provide a PR, but I don't think rushing to close an issue containing a stack blitz stimulates such contributions.
