### ISSUE TITLE
docs: observables examples hard-coded and outdated

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#31024]
# 📚 Docs or angular.io bug report

### Description

The [Comparing Observables][1] guide shows examples with the old, obsolete syntax of having operators on the `Observable` prototype, instead of using `.pipe()`.

Also, the examples are hard-coded, instead of being extracted from actual mini-apps, which would prevent the code from getting out-of-date or break.

### What's the affected URL?**
https://angular.io/guide/comparing-observables

[1]: https://angular.io/guide/comparing-observables

**Comment by sonukapoor** [comment]
@kapunahelewong Looking at the link you provided, I don't see the old syntax. I see the new syntax using `.pipe(...)`. Can you let me know if any changes are still required? I would be willing to pick up this work if still required.

**Comment by gkalpak** [comment]
Thx, @sonukapoor!

This issues had basically two parts:
1. Updating the examples to use the new syntax (pipeable operators).
2. Moving the examples (which are currently hard-coded) to proper, testable mini-apps (in `aio/content/examples/`).

The first part has already been addressed by #31074. The second still needs to be addressed.

**Comment by sonukapoor** [comment]
Sounds good. Please assign to me if it’s still available.

**Comment by kapunahelewong** [comment]
@sonukapoor, if you need any help with the PR, please let me know. Thank you!!
