### ISSUE TITLE
MutationObserver should accept HTMLElement too

### ISSUE THREAD

**Issue by StefanKern** [angular/angular#31029]
> Question asked on Stackoverflow (https://stackoverflow.com/questions/56546116/typescript-convert-htmlelement-to-node/56546557?noredirect=1#comment99675409_56546557 ), full credit to `Cristian Traìna` answer.

Inside the `lib.dom.d.ts` (the type definition library used by Angular), the MutationObserver object is not much correctly defined:
```
interface MutationObserver {
    disconnect(): void;
    observe(target: Node, options: MutationObserverInit): void;
    takeRecords(): MutationRecord[];
}
```

According to the MDN documentation, a HTML element is also accepted (seen in the demo: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver´, `document.getElementById('some-id')` returns a `HTMLElement` ).

So a better definition would be 
```
    observe<T extends Node>(target: T, options: MutationObserverInit): void;
```

The current workaround is to cast the HTMLElement to node via 
```
observer.observe((<Node> <any> errorElement), { 
....
});
```

**Comment by pkozlowski-opensource** [comment]
This should be reported to TypeScript directly where the definition lives: https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts
