### ISSUE TITLE
Emulated view encapsulation attribute selectors are extremely slow in IE11

### ISSUE THREAD

**Issue by laurentgoudet** [angular/angular#31033]
# 🐞 bug report

### Affected Package
The issue is caused by the emulated view encapsulation code in the styles compiler (`@angular/compiler`) and `DomRenderer` (`@angular/platform-browser`)

### Is this a regression?
No

### Description

We have a fairly large Angular app which runs smoothly in Chrome/Firefox/Safari/Edge, but is very laggy in IE11. Looking at the IE11 performance timeline shows that this is caused by extremely expensive styling operations:

<img width="1024" alt="_Screen Shot 2019-06-12 at 19 50 41" src="https://user-images.githubusercontent.com/2169585/59414262-76a15580-8dc1-11e9-8c50-58db7f966f0c.png">

Digging into the problem, it appears that attributes selectors are a huge performance bottleneck in IE11, as pointed out in https://medium.com/@aantipov/ie11-performance-bottleneck-de304569361d. This is apparently a well-known issue, as Angular Material had the exact same issue back in 2015, which was fixed by refactoring the layout directives as class names instead of attributes (https://github.com/angular/material/issues/1771#issuecomment-133521445). The Ionic team came up with the same conclusion as well, and [stopped using attribute selectors for their shadow dom polyfill](https://github.com/ionic-team/ionic/issues/14876#issuecomment-408877240), and CSSLint [even has a lint rule for it](https://github.com/CSSLint/csslint/wiki/Disallow-unqualified-attribute-selectors).

However, Angular's emulated view encapsulation, which is the default view encapsulation mode (i.e. what most people are using), is based on the `_nghost-${COMPONENT_VARIABLE}` and `_ngcontent-${COMPONENT_VARIABLE}` attributes to emulate the styles encapsulation. This effectively adds unqualified attribute selectors as the key part (far-right) of all host & component styles selectors.

To test that theory, I've patched the emulated view encapsulation implementation locally to use CSS classes instead of attributes for `_nghost` & `_ngcontent`, and I can confirm this indeed solves the issue (a.k.a. the app becomes usable in IE11 again), i.e. it pretty much removes all the time spent in layout operations:

<img width="1024" alt="Screen Shot 2019-06-12 at 19 53 46" src="https://user-images.githubusercontent.com/2169585/59418143-cdf6f400-8dc8-11e9-999c-3fd10df52dc0.png">

The exact (completely hacky) code change I've made to the compiler/renderer to obtain that result is in https://github.com/laurentgoudet/angular-ie11-bug/commit/13896b53fc61c424ff5c6f98c58cc9ccc0f7d502.

## 🔬 Minimal Reproduction

I'm working on a minimal reproduction but it's a bit tricky as one apparently needs both a high number of DOM nodes and a high number a attribute-based styles rules (although the rules don't need to be match any element?), a.k.a. some real-world UI complexity.

A [codepen was reproducing the issue](https://codepen.io/david-gang/pen/RRJjxG) for Angular Material (i.e. AngularJS), which I roughly ported to Angular v8 (https://embed.plnkr.co/e9vp65), but I'm not very happy with it as I can't see the same dramatic performance difference as I can see how with our app (when using my fork) - I suspect there might not be enough depth or different selectors (since the same component - `_ngcontent` - is duplicated over & over).

## 🌍  Your Environment

**Angular Version:**
v7, but the shadow DOM emulation code doesn't seem to have changed in `master` (and I don't think enabling Ivy changes anything as the style compiler seems independant).

**Comment by vbraun** [comment]
Some benchmarks can be found at https://medium.com/@aigoncharov/edge-hates-you-attributes-d15faf162939

On Edge attribute selectors are also slow, just not as slow as on IE11

**Comment by petebacondarwin** [comment]
I wonder if we should allow these markers to be configurable? For instance using CSS classes rather than attributes; or to solve #25355 using `data-...` attributes?

**Comment by petebacondarwin** [comment]
Given that Edge has recently moved to be based upon Chrome, I believe that it will no longer have this performance issue.
Further, IE11 is a legacy browser that will become unsupported in the medium term.
So I am going to close this as an issue that we are not going to fix.
