### ISSUE TITLE
Replace the real value from api for parameter in the URL when changing manually by the user in the address bar

### ISSUE THREAD

**Issue by Chandru22714** [angular/angular#31030]
Lets say, I have the url,

`http://localhost:4200/param1/param2/product`

Here param1, param2 are the parameter  real values from api. If the user changes the value of parameter in the address bar manually and reloading the page. The value of the parameter should be replaced by the real values from the api. Please suggest me a way to achieve this. I found this for queryparam, which we can use navigation extras to achieve that. But for parameter not to able to find the solution.

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-issue-repro2).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
