### ISSUE TITLE
[docs] ViewChild and ContentChild - static option

### ISSUE THREAD

**Issue by DiedrikDM** [angular/angular#31034]
# 📚 Docs or angular.io bug report

### Description

Starting from Angular 8 the ViewChild and ContentChild decorators need a second parameter where the "static" option needs to be set. If it is not set, the TypeScript compiler throws an error.
In the documentation the ViewChild and ContentChild decorators describe this extra option. When you read through the documentation it says the "static" value is an option and can be omitted. If you try to remove the option on the other hand, the TypeScript compiler - as previously stated - throws an error.

### What's the affected URL?**
[https://angular.io/api/core/ContentChild](https://angular.io/api/core/ContentChild)
[https://angular.io/api/core/ViewChild](https://angular.io/api/core/ViewChild)

### Reproduction Steps**
Create a new Angular 8 project and add a ViewChild or ContentChild decorator to a field in a component, without the static option and try to compile.

### Expected vs Actual Behavior**
a. Either Angular allows the decorators to be used without the static option, like it will be done in Angular 9 (as stated in [https://angular.io/guide/static-query-migration#why-do-i-have-to-specify-static-false-isnt-that-the-default](https://angular.io/guide/static-query-migration#why-do-i-have-to-specify-static-false-isnt-that-the-default))
b. Or the documentation needs a little update mentioning the static parameter is necessary.

### Related issues
#30751

**Comment by DiedrikDM** [comment]
If necessary I'm willing to do a PR, but I want to be sure that there's no option C that the Angular Team is thinking about in the meanwhile - before A9 release.

**Comment by kara** [comment]
@DiedrikDM Thanks for catching this! We forgot to update the API docs when we changed the type signature. We should probably fix this in a patch release.

**Comment by DiedrikDM** [comment]
@kara no problem. I'm just wondering, should there be a mention of the changes coming later in A9 in the docs or should those be kept separately for the "static-query-migration" guide like it is now?
