### ISSUE TITLE
Styling issue when creating a new project

### ISSUE THREAD

**Issue by psingl** [angular/angular#31036]
Suppose we create a  new project using the command `ng new <project_name> --style=sass`
The new project when created successfully contains a file named `styles.scss` but in and the angular cli build configuration file `angular.json` the file points to `styles.sass` as we are selecting sass preprocessor while creating a new project.

So while serving the project on localhost or building it shows an error of Module not found.

**Comment by pkozlowski-opensource** [comment]
Could you please open in https://github.com/angular/angular-cli? Thnx!
