### ISSUE TITLE
[Ivy] (8.1.0-next.1) ng build ERRORs for @covalent, ngx-bootstrap, ngx-pipes

### ISSUE THREAD

**Issue by anisabboud** [angular/angular#31032]
# 🐞 bug report

### Affected Packages

`@covalent`: https://github.com/Teradata/covalent
`ngx-bootstrap`: https://github.com/valor-software/ngx-bootstrap
`ngx-pipes`: https://github.com/danrevah/ngx-pipes

### Description

I'm trying to upgrade to Ivy following the [blog post](https://blog.angular.io/its-time-for-the-compatibility-opt-in-preview-of-ivy-38f3542a282f).
But `ng build` produces 3 **different** errors for 3 different packages (dependencies).

## 🔬 Minimal Reproduction

- Install the packages above.
- `ng update @angular/core --next` + https://angular.io/guide/ivy#using-ivy-in-an-existing-project
- `ng build`

## 🔥 Exception or Errors
<pre><code>1. Compiling @covalent/core : module as esm5
ERROR in Tried to overwrite .../node_modules/@covalent/core/paging/paging-bar.component.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.

2. Compiling ngx-bootstrap/datepicker : module as esm5
ERROR in Expected array when reading property declarations

3. Compiling ngx-pipes : module as esm5
ERROR in Value at position 12 in the NgModule.declarationss of NgStringPipesModule is not a reference: [object Object]
</code></pre>

## 🌍  Your Environment

**Angular Version: `8.1.0-next.1`**
<pre><code>Angular CLI: 8.0.2
Node: 12.3.1
OS: linux x64
Angular: 8.1.0-next.1
(everything latest)
</code></pre>

**Anything else relevant?**

Faced another error `ERROR in Failed to list lazy routes: Unknown module '.../src/app/app.module#AppModule'.` even though I don't have any lazy-loaded modules. Resolved it by adding `"aot": true` to build options in `angular.json` according to https://angular.io/guide/ivy.

Also, I don't understand why Ivy needs to recompile the entire node_modules folder.
The rationalization isn't explained in the guide/blog post. (Is this a scalable approach?)

**Comment by JoostK** [comment]
1. The issue with `@covalent/core` is that it re-exports secondary entry-points from the primary entry-point. This causes the sources from the secondary entry-points to be compiled twice, which is disallowed in ngcc. @petebacondarwin Your #30591 should fix that right, given that Material follows the same approach?

2. `ngx-bootstrap/datepicker` uses `__spread` from `tslib`, for which support landed in #30492 which will be in `next.2` once it is released.

3. This one I can't spot what the reason would be. Needs investigation

**Comment by danrevah** [comment]
@JoostK I'm maintaining 'ngx-pipes', haven't touched Angular in a while.. any idea how I could approach researching this?

**Comment by danrevah** [comment]
Nevermind. found it after 10min..  Thanks anyway :)

**Comment by JoostK** [comment]
@danrevah Let's first see if it's been resolved in the latest release, `8.2.0-next.0` at this moment. I suspect it's an issue with ngcc somehow, which has received quite some fixes in recent weeks, so maybe the situation has improved.



> Nevermind. found it after 10min.. Thanks anyway :)

Then I want to know what it is :p Does it require a fix on the Angular side?

**Comment by danrevah** [comment]
@JoostK I think that it might be nice to have this supported, but it's not the cleanest implementation.. so it's probably not a must.

https://github.com/danrevah/ngx-pipes/commit/d4e619294a65da6f74349d935a4dfe223f0b9361

It was related to the latinise pipe, I've just wrapped the latin characters in the JSON and it seemed to stop failing.
Anyway, if not a fix, then maybe a more explanatory error? since I had no idea what to search for.

**Comment by danrevah** [comment]
Also, this was only failing while setting the target to 'es5', when it was 'es2015' and above I didn't get any error.

**Comment by JoostK** [comment]
@danrevah Thanks for looking into it. Looks like ngcc might have some issues with encodings. We should definitely try to improve the messaging here, or even try to support it in the first place.

**Comment by smasala** [comment]
Also getting one of the errors with a different module

`ERROR in Value at position 0 in the NgModule.imports of AngularFontAwesomeModule is not a reference: [object Object]`

Version:
`Angular: 8.1.2`

**Comment by gkalpak** [comment]
All the PRs have landed and the latest version of `ngx-pipes` works fine with `ngcc`. [ngcc-validation/infra/passing.json] also confirms that all packages compile fine with `ngcc`.

Should we close this?
Do we need to create a ticket for investigating the encoding issue?

[1]: https://github.com/mgechev/ngcc-validation/blob/ce115f17c/infra/passing.json

**Comment by gkalpak** [comment]
I am going to assume everything is fixed here (see https://github.com/angular/angular/issues/31032#issuecomment-521422600).
Please open a new issue if you are still running into problems.
