### ISSUE TITLE
input type=radio not handled correctly by ng-model

### ISSUE THREAD

**Issue by rkj** [angular/angular#3104]
For this snippet:

      {{selected}}
      <div *ng-for="#value of allValues">
        <input type="radio"
               name="group"
               [(ng-model)]="selected">
          {{value}}
        </input>
      </div>

It will select the first value correctly, but then all the follow up changes are ignored.

**Comment by dsebastien** [comment]
Any update on this one?

**Comment by zoechi** [comment]
See #5506 seems to be planned for the next beta

**Comment by park9140** [comment]
#5506 seems to only fix it as part of an ngForm control does this need to be fixed in ngModel as well so that ngModel can be used on a single checkbox or set of radio buttons?

**Comment by GregWoods** [comment]
Does this really work?
I had a working set of radio buttons by injecting this: [radio_value_accessor.ts](https://github.com/angular2-school/angular2-radio-button/blob/master/modules/ng-school/controls/radio/radio_value_accessor.ts)  code into my controller.
Now I have updated to Beta6, removed the above code, and my radio buttons are no longer bound to my model. All other controls are fine. Am I missing something else?

**Comment by Emdot** [comment]
I don't doubt that it works, but I'd really appreciate a plnkr showing how to use it correctly. A straightforward update of what worked prior to this change doesn't appear to work (see http://stackoverflow.com/questions/35653175/how-to-bind-to-radio-buttons-in-angular2-beta-6) so presumably there's some secret sauce somewhere that we're missing.

**Comment by kylecordes** [comment]
This is a surprisingly tricky thing to get right. Maybe someone will read the A1 source code to talking checkbox DOM, and implement the same thing for A2.

**Comment by GregWoods** [comment]
Seems to work easily enough in Beta3 using [radio_value_accessor.ts](https://github.com/angular2-school/angular2-radio-button/blob/master/modules/ng-school/controls/radio/radio_value_accessor.ts)
But then it may break other test cases, I have no idea. But I'm sticking to this for the foreseeable future

**Comment by vsavkin** [comment]
Fixed here e725542703d82d1d3e47d9898022452456115747

**Comment by GregWoods** [comment]
This needs reopening

I've no doubt something was fixed, but I don't think the original issue was understood.

I believe this is how the OP was trying to use radio buttons. It does not work in Beta 9
http://plnkr.co/edit/46duKk

This is template based forms using [(ngModel)] for 2 way binding.

If it does indeed work, please update with guidance on how to make it work.

**Comment by GregWoods** [comment]
Workaround 1: https://github.com/pleerock/ng2-radio-group Depends on bootstrap 3

Workaround 2: using a template variable with separate (click) and [checked] instead of [(ngModel)]

```
        <input #male [checked]="model.Gender==male.value" (click)="model.Gender=male.value" name="Gender" value="male" id="radioMale" type="radio">
          <label for="radioMale">Male</label><br />
        
        <input #female [checked]="model.Gender==female.value" (click)="model.Gender=female.value" name="Gender"value="female" id="radioFemale" type="radio">
          <label for="radioFemale">Female</label>
          <br>
```

**Comment by GregWoods** [comment]
new issue #7642
