### ISSUE TITLE
platform-server errors with ivy-ngcc

### ISSUE THREAD

**Issue by ramarivera** [angular/angular#31069]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/platform-server

### Is this a regression?

 Yes, the previous version in which this bug was not present was: @angular/platform-server@8.0.1

### Description

 A clear and concise description of the problem...
When trying to compile my application with Ivy, I get errors on ivy ngcc for platform-server, as well as several warnings for other packages

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-issue-repro2-7h4alk

Download the stackblitz project, run `npm install`

## 🔥 Exception or Error
<pre><code>

> angular@0.0.0 postinstall C:\Users\rrivera\Desktop\angular-issue-repro2-7h4alk
> ivy-ngcc

Compiling @angular/animations : fesm2015 as esm2015
Compiling @angular/animations : fesm5 as esm5
Compiling @angular/animations : esm2015 as esm2015
Compiling @angular/animations : esm5 as esm5
Compiling @angular/animations : main as umd
Compiling @angular/core : fesm2015 as esm2015
Compiling @angular/core : fesm5 as esm5
Compiling @angular/core : esm2015 as esm2015
Compiling @angular/core : esm5 as esm5
Compiling @angular/core : main as umd
Compiling @angular/animations/browser : fesm2015 as esm2015
Compiling @angular/animations/browser : fesm5 as esm5
Compiling @angular/animations/browser : esm2015 as esm2015
Compiling @angular/animations/browser : esm5 as esm5
Compiling @angular/animations/browser : main as umd
Compiling @angular/animations/browser/testing : fesm2015 as esm2015
Compiling @angular/animations/browser/testing : fesm5 as esm5
Compiling @angular/animations/browser/testing : esm2015 as esm2015
Compiling @angular/animations/browser/testing : esm5 as esm5
Compiling @angular/animations/browser/testing : main as umd
Compiling @angular/cdk : es2015 as esm2015
Compiling @angular/cdk : main as umd
Compiling @angular/cdk : module as esm5
Compiling @angular/common : fesm2015 as esm2015
Compiling @angular/common : fesm5 as esm5
Compiling @angular/common : esm2015 as esm2015
Compiling @angular/common : esm5 as esm5
Compiling @angular/common : main as umd
Compiling @angular/cdk/platform : es2015 as esm2015
Compiling @angular/cdk/platform : main as umd
Compiling @angular/cdk/platform : module as esm5
Compiling @angular/cdk/coercion : es2015 as esm2015
Compiling @angular/cdk/coercion : main as umd
Compiling @angular/cdk/coercion : module as esm5
Compiling @angular/cdk/bidi : es2015 as esm2015
Compiling @angular/cdk/bidi : main as umd
Compiling @angular/cdk/bidi : module as esm5
Compiling @angular/cdk/collections : es2015 as esm2015
Compiling @angular/cdk/collections : main as umd
Compiling @angular/cdk/collections : module as esm5
Compiling @angular/cdk/scrolling : es2015 as esm2015
Compiling @angular/cdk/scrolling : main as umd
Compiling @angular/cdk/scrolling : module as esm5
Compiling @angular/cdk/drag-drop : es2015 as esm2015
Compiling @angular/cdk/drag-drop : main as umd
Compiling @angular/cdk/drag-drop : module as esm5
Compiling @angular/common/http : fesm2015 as esm2015
Compiling @angular/common/http : fesm5 as esm5
Compiling @angular/common/http : esm2015 as esm2015
Compiling @angular/common/http : esm5 as esm5
Compiling @angular/common/http : main as umd
Compiling @angular/common/http/testing : fesm2015 as esm2015
Warning: Unknown member type: "[key: string]: (data: any) => void;
Compiling @angular/common/http/testing : fesm5 as esm5
Warning: Unknown member type: "[key: string]: (data: any) => void;
Compiling @angular/common/http/testing : esm2015 as esm2015
Warning: Unknown member type: "[key: string]: (data: any) => void;
Compiling @angular/common/http/testing : esm5 as esm5
Warning: Unknown member type: "[key: string]: (data: any) => void;
Compiling @angular/common/http/testing : main as umd
Compiling @angular/flex-layout/core : es2015 as esm2015
Compiling @angular/flex-layout/core : main as umd
Compiling @angular/flex-layout/core : module as esm5
Compiling @angular/platform-browser : fesm2015 as esm2015
Compiling @angular/platform-browser : fesm5 as esm5
Compiling @angular/platform-browser : esm2015 as esm2015
Compiling @angular/platform-browser : esm5 as esm5
Compiling @angular/platform-browser : main as umd
Compiling @angular/flex-layout/extended : es2015 as esm2015
Compiling @angular/flex-layout/extended : main as umd
Compiling @angular/flex-layout/extended : module as esm5
Compiling @angular/flex-layout/flex : es2015 as esm2015
Compiling @angular/flex-layout/flex : main as umd
Compiling @angular/flex-layout/flex : module as esm5
Compiling @angular/flex-layout/grid : es2015 as esm2015
Compiling @angular/flex-layout/grid : main as umd
Compiling @angular/flex-layout/grid : module as esm5
Compiling @angular/flex-layout : es2015 as esm2015
Compiling @angular/flex-layout : main as umd
Compiling @angular/flex-layout : module as esm5
Compiling @angular/platform-browser-dynamic : fesm2015 as esm2015
Compiling @angular/platform-browser-dynamic : fesm5 as esm5
Compiling @angular/platform-browser-dynamic : esm2015 as esm2015
Compiling @angular/platform-browser-dynamic : esm5 as esm5
Compiling @angular/platform-browser-dynamic : main as umd
Compiling @angular/platform-browser/animations : fesm2015 as esm2015
Compiling @angular/platform-browser/animations : fesm5 as esm5
Compiling @angular/platform-browser/animations : esm2015 as esm2015
Compiling @angular/platform-browser/animations : esm5 as esm5
Compiling @angular/platform-browser/animations : main as umd
Compiling @angular/platform-server : fesm2015 as esm2015
Warning: Unknown member type: "[key: string]: (data: any) => void;
Compiling @angular/platform-server : fesm5 as esm5
Warning: Unknown member type: "[key: string]: (data: any) => void;
Compiling @angular/platform-server : esm2015 as esm2015
Warning: Unknown member type: "[key: string]: (data: any) => void;
Compiling @angular/platform-server : esm5 as esm5
Warning: Unknown member type: "[key: string]: (data: any) => void;
Compiling @angular/platform-server : main as umd
Error: Expected UMD module file (C:/Users/rrivera/Desktop/angular-issue-repro2-7h4alk/node_modules/url/node_modules/punycode/punycode.js) to contain exactly one statement, but found [object Object],[object Object].
    at UmdReflectionHost.getUmdModule (C:\Users\rrivera\Desktop\angular-issue-repro2-7h4alk\node_modules\@angular\compiler-cli\ngcc\src\host\umd_host.js:50:27)
    at UmdReflectionHost.getModuleStatements (C:\Users\rrivera\Desktop\angular-issue-repro2-7h4alk\node_modules\@angular\compiler-cli\ngcc\src\host\umd_host.js:102:34)
    at UmdReflectionHost.Esm2015ReflectionHost.findClassSymbols (C:\Users\rrivera\Desktop\angular-issue-repro2-7h4alk\node_modules\@angular\compiler-cli\ngcc\src\host\esm2015_host.js:310:18)
    at DecorationAnalyzer.analyzeFile (C:\Users\rrivera\Desktop\angular-issue-repro2-7h4alk\node_modules\@angular\compiler-cli\ngcc\src\analysis\decoration_analyzer.js:109:55)
    at C:\Users\rrivera\Desktop\angular-issue-repro2-7h4alk\node_modules\@angular\compiler-cli\ngcc\src\analysis\decoration_analyzer.js:100:59
    at Array.map (<anonymous>)
    at DecorationAnalyzer.analyzeProgram (C:\Users\rrivera\Desktop\angular-issue-repro2-7h4alk\node_modules\@angular\compiler-cli\ngcc\src\analysis\decoration_analyzer.js:100:18)
    at Transformer.analyzeProgram (C:\Users\rrivera\Desktop\angular-issue-repro2-7h4alk\node_modules\@angular\compiler-cli\ngcc\src\packages\transformer.js:113:57)
    at Transformer.transform (C:\Users\rrivera\Desktop\angular-issue-repro2-7h4alk\node_modules\@angular\compiler-cli\ngcc\src\packages\transformer.js:62:27)
    at C:\Users\rrivera\Desktop\angular-issue-repro2-7h4alk\node_modules\@angular\compiler-cli\ngcc\src\main.js:102:60
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular@0.0.0 postinstall: `ivy-ngcc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rrivera\AppData\Roaming\npm-cache\_logs\2019-06-15T12_57_08_875Z-debug.log
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.1.0-beta.2
Node: 10.15.0
OS: win32 x64
Angular: 8.1.0-next.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0-beta.2
@angular-devkit/build-angular     0.801.0-beta.2
@angular-devkit/build-optimizer   0.801.0-beta.2
@angular-devkit/build-webpack     0.801.0-beta.2
@angular-devkit/core              8.1.0-beta.2
@angular-devkit/schematics        8.1.0-beta.2
@angular/cdk                      8.0.1
@angular/cli                      8.1.0-beta.2
@angular/flex-layout              8.0.0-beta.26
@angular/http                     8.0.0-beta.10
@angular/material                 8.0.1
@ngtools/webpack                  8.1.0-beta.2
@schematics/angular               8.1.0-beta.2
@schematics/update                0.801.0-beta.2
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.34.0
</code></pre>

**Anything else relevant?**

**Comment by ramarivera** [comment]
Removing platform-server from package.json gets rid of the error

**Comment by petebacondarwin** [comment]
This will be fixed by https://github.com/angular/angular/pull/30591
