### ISSUE TITLE
Non closing HTML tags

### ISSUE THREAD

**Issue by psingl** [angular/angular#31067]
Angular version 7.2.15
Error while using non closing html tag like `<hr>` tag.

I am having a component named HomeComponent which is working very fine when newly created but after using a non closing tag `<hr>` the compiler throws a Template Parse error.
> home.component.html
````
<p>
    home works!
</p>
````
The above code works very fine.
<br>
> home.component.html
````
<p>
    home works!
    <br>Hello
</p>
````
This code also works fine.
<br>
> home.component.html
````
<p>
    home works!
    <hr>Hello
</p>
````
This throws a Template parse error as shown below.
![image](https://user-images.githubusercontent.com/13885706/59545853-59e05b80-8f42-11e9-8849-5e4ed647b8dc.png)

**Comment by trotyl** [comment]
`<hr>`  is not allowed inside `<p>`, that’s HTML syntax.
