### ISSUE TITLE
Docs should not use StackBlitz "generator" or other proprietary features

### ISSUE THREAD

**Issue by methodbox** [angular/angular#31073]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...
The documentation uses a number of proprietary features of "StackBlitz" online code editor to explain fundamental concepts of Angular. This obscures the process that is occurring when these features, such as "Angular Generator" are used.

This is bad practice both due to the fact that there are many reported issues (just do a quick Google search) using StackBlitz, particularly exporting the default project (see here: https://github.com/stackblitz/core/issues/377) and due to the fact that learning from a process that "magically" generates files isn't actually learning anything at all.

## 🔬 Minimal Reproduction
Here's an example of part of the docs where this is used: https://angular.io/start#input

### What's the affected URL?**
 https://angular.io/...
https://angular.io/start#input

### Reproduction Steps**

Read the docs. See the issue.

### Expected vs Actual Behavior**

This isn't a bug. It's a documentation approach issue.

## 📷Screenshot

Unnecessary.

## 🔥 Exception or Error
<pre><code>

Not a bug.
</code></pre>

## 🌍  Your Environment
Not applicable.

### Browser info

Not applicable.
### Anything else relevant?

Not applicable.

**Comment by Airblader** [comment]
For the record, is the graphical access to the CLI only one or the only one example? In other words, which other things are affected by this?

As far as the CLI schematics go I agree that it would make sense to describe the CLI usage and optionally explain how it can be done on StackBlitz. I don't think there's anything inherently wrong with giving users a playground where they can work without having it set up an IDE locally first. In many ways StackBlitz is just VS Code anyway.

**Comment by methodbox** [comment]
@Airblader I’m not sure, but yeah that may be the only example.

There’s nothing wrong with StackBlitz as a tool, I agree there’s nothing inherently wrong with using it here.

It’s a process that can (apparently) be done with the CLI that isn’t explained - that makes it a bit confusing when trying to reproduce this locally.

I’m new to Angular having gone the React route the last few years and only last used AngularJS.

I’ve heard lots of great things about Angular tooling and it seems this is probably a good opportunity to show it off, yet it’s not done ... and as a perfect example of why this is a problem, I didn’t even know the CLI could do this ( I would assume but it didn’t come to mind as I’m not familiar with it).

I feel the documentation could benefit from focusing on Angular's strength in tooling. Obscuring this away from the user is just as likely to cause future confusion.

**Comment by brandonroberts** [comment]
@methodbox I understand your point of view. The choice to use StackBlitz for getting started is motivated by letting you focus on getting up and running with Angular, with less friction of having to get a full build environment setup first. Yes, you can do the equivalent steps with the CLI that you can do with StackBlitz, but that's a next step and not something you need to do to get started and see what the framework can do you for you.

**Comment by methodbox** [comment]
> @methodbox I understand your point of view. The choice to use StackBlitz for getting started is motivated by letting you focus on getting up and running with Angular, with less friction of having to get a full build environment setup first. Yes, you can do the equivalent steps with the CLI that you can do with StackBlitz, but that's a next step and not something you need to do to get started and see what the framework can do you for you.

I'm suggesting _adding_ something like, "You can also generate new components and many other things using Angular CLI. To skip ahead and learn how to do this click here."

My first step when starting the intro app was to rip the code out of the online IDE and pull it up in my own environment, then figure out how to make it work locally. Judging by the number of posts here and other places regarding StackBlitz I would say I'm not alone.

I'm not advocating to get rid of it, or even really change the general flow of the docs. I'm advocating to let users know that once they start using Angular, since they probably won't doing all their dev work on StackBlitz, there's a standardized method of doing this using the CLI.

**Comment by FrederikSchlemmer** [comment]
@methodbox I also think it would be a good idea to add a little note to the proposal that this procedure can also be done with the Angular CLI. A link to [this page](https://angular.io/cli) would be enough in my opinion.

@brandonroberts If you are also of the opinion I would like to make the changes. If @methodbox  doesn't mind?

**Comment by StephenFluin** [comment]
If you feel like a link or reference off to the CLI would help clarify the situation, go for it! 

Our intent is definitely for people to know about generators, whether in StackBlitz or in the CLI.

**Comment by methodbox** [comment]
@FrederikSchlemmer Were you intending to submit a PR for this, or I can? I didn't see anything for it yet.

**Comment by FrederikSchlemmer** [comment]
> @FrederikSchlemmer Were you intending to submit a PR for this, or I can? I didn't see anything for it yet.

I'm working on it. There should be a PR today!
@methodbox would be great if you give feedback about the changes.

**Comment by brandonroberts** [comment]
Closed via https://github.com/angular/angular/pull/31216
