### ISSUE TITLE
Providing Compiler doesn't have any effect in Angular 7

### ISSUE THREAD

**Issue by mtuzinskiy** [angular/angular#31079]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular 6

### Description

 Providing the Compiler in the app module doesn't have any effect, the Compiler remains the same

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/github-f7azvt?file=src/app/app.module.ts
Even providing the `null` value does nothing:
```
{ provide: COMPILER_OPTIONS, useValue: {}, multi: true },
{ provide: CompilerFactory, useClass: JitCompilerFactory, deps: [COMPILER_OPTIONS] },
{ provide: Compiler, useValue: null, deps: [CompilerFactory] }
```

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

7.2.0
</code></pre>

**Anything else relevant?**

**Comment by alxhub** [comment]
`Compiler` is an Angular internal token. Overriding it is not supported, sorry.

**Comment by mtuzinskiy** [comment]
@alxhub Is it possible to at least mention about the "internal tokens" in the documentation? Thank you
