### ISSUE TITLE
How to force index.html to be loaded from server in any browsers using Angular 2 code if it was cached

### ISSUE THREAD

**Issue by rakshitshah94** [angular/angular#31077]
Currently I am hosting an Angular 2 application on Apache 2.4 web server and in client's browser latest website changes are not rendered after new production deployment! I found that index.html is cached by the browser. All css and angular bundle file linking can be done on index.html,so it is entry point of the application. We have thousands of active users so we cannot insist them to press CTRL+F5 or do hard reload.

I have checked with different ways of production build (for example, <a href="https://stackoverflow.com/questions/39647810/how-to-prevent-browser-cache-on-angular-2-site/39671383#_=_">Thread1</a>, <a href="https://github.com/angular/angular-cli/issues/4320" >Thread2</a>), index.html also contains following meta tags already.

```
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">
```
Using angular code, I have checked with cache busting by query param and also followed up a good practice to use module.id in each component as well.

```
@Component({
    ...
    moduleId: module.id,
    ...
})
```
So my question is,

1. In this situation, how do I force browser to load new index.html using Angular 2 code in all user's machine? - If it is possible then please let me know about how do i cope up with this issue.

Your help will be appreciated!

**Comment by alastair-todd** [comment]
Think this will get wiped as its not an angular issue.
You need to look at your apache set up and play with the caching config there, maybe turn it off for starters

https://stackoverflow.com/questions/22891965/how-to-disable-cache-of-apache

**Comment by rscherer** [comment]
We did this by caching everything except .html files. But it is, indeed, a server configuration, not Angular's.

**Comment by alastair-todd** [comment]
Even js files? Are they cache-busted? That's your app being cached right there

**Comment by rscherer** [comment]
Even js files. Since bundles are referenced on main bundle, and main bundle is referenced on index.html, by generating different hash codes on every new build, users will always use the lastest main and modules bundles. But once they are loaded, they'll be cached until next build.

**Comment by AndrewKushnir** [comment]
@rakshitshah94 I'm closing this issue, since it seems unrelated to Angular (as @alastair-todd mentioned in this thread) and most likely related to Apache config. Thank you.
