### ISSUE TITLE
Ivy: ERROR in Unsupported binary operator: EqualsEqualsEqualsToken

### ISSUE THREAD

**Issue by matheo** [angular/angular#31076]
🐞 bug report

### Affected Package

I guess the issue is caused by package `@angular/compiler-cli` because googling for that operator, the only reference I get is about a metadata file inside that package.

### Description

After reading https://blog.angular.io/its-time-for-the-compatibility-opt-in-preview-of-ivy-38f3542a282f I wanted to see the bundle size of a project of mine to compare the final prod size, and I got the error.

## 🔬 Minimal Reproduction

It's a large project using different libs, so I'm not sure of the exact origin to reproduce it.

## 🔥 Exception or Error
<pre><code>
Date: 2019-06-16T03:18:32.502Z
Hash: 23322230c697a07e45b1
Time: 429325ms
chunk {0} runtime.741402d1d47331ce975c.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main.4af9b61479361f268d39.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills.961ffc045f11208a7197.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} styles.3ef5a23be68fc1aa7d7a.css (styles) 79.1 kB [initial] [rendered]

ERROR in Unsupported binary operator: EqualsEqualsEqualsToken
error Command failed with exit code 1.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect          0.800.1
@angular-devkit/build-angular      0.800.3
@angular-devkit/build-ng-packagr   0.800.3
@angular-devkit/build-optimizer    0.800.3
@angular-devkit/build-webpack      0.800.3
@angular-devkit/core               8.0.1
@angular-devkit/schematics         8.0.1
@angular/cli                       8.0.3
@angular/fire                      5.2.1
@angular/flex-layout               8.0.0-beta.26
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.3
@schematics/angular                8.0.1
@schematics/update                 0.800.3
ng-packagr                         5.3.0
rxjs                               6.5.2
typescript                         3.4.4
webpack                            4.30.0
</code></pre>

**Anything else relevant?**

I develop on Linux using `yarn` as the package manager.

**Comment by kara** [comment]
@matheo I don't think this is enough info for us to really investigate. Any way you can create a repro somewhere or post some more code?

**Comment by matheo** [comment]
@kara is there a way to get some debugging info from Ivy?
I mean, there's no stacktrace to check where's the problem, I don't have enough info about the cause of this project to not be built :(

**Comment by JoostK** [comment]
I think I do know where the issue comes from, we should be able to create a local test to reproduce the issue and provide a fix accordingly.

So for me, I don't necessarily need a repo ;)

**Comment by kara** [comment]
Even better, thanks @JoostK

**Comment by matheo** [comment]
Thanks a lot @JoostK
