### ISSUE TITLE
Docs: titles in search results are not readable

### ISSUE THREAD

**Issue by Ivnosing** [angular/angular#31086]
# 📚 Docs or angular.io bug report

### Description
Within the search results, the titles of each section (e.g. API, CLI, GUIDE...) are colored in black, being the background dark gray.

## 🔬 Minimal Reproduction

1. Go to https://angular.io/
1. Search something in the upper right search field
1. Observe the titles of each section in the search results. They are colored in black and hard to read

### What's the affected URL?
https://angular.io/ and sub-folders.

### Expected vs Actual Behavior
The titles should have a readable color (e.g. `white`, `#dbdbdb`).

## 📷Screenshot
![image](https://user-images.githubusercontent.com/26304638/59596933-f2204100-90f8-11e9-8653-f4ed3b9b48d7.png)

**Comment by petebacondarwin** [comment]
Fixed by https://github.com/angular/angular/pull/30924
