### ISSUE TITLE
Is Angular supports conditional routing based on type?

### ISSUE THREAD

**Issue by vbpradeep** [angular/angular#31084]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Hi NG Developers,

i have some concerns about angular?

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2

![image](https://user-images.githubusercontent.com/12544691/59581416-76bb9100-90f2-11e9-9979-79bc043936eb.png)

Is this possible in Angular routing?

if i config below route config means how i call 2nd router programatically.

```
 { path: ':locale/:id', component: HomePageCategory    },
 { path: ':locale/:platform', component: PlatformPageCategory    },
 { path: ':locale/contact', component: ContactPageCategory    },
```

can you please check the above scenarios.

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by dawidgarus** [comment]
Angular care for the order of routes, so you should define them from more specific to general ones, like:
```
{ path: ':locale/contact', component: ContactPageCategory },
{ path: ':locale/:platform', component: PlatformPageCategory },
```
You may be interested in custom UrlMatcher: https://angular.io/api/router/UrlMatcher

**Comment by vbpradeep** [comment]
Hi @AndrewKushnir ,

can you consider this as feature? 

Regards,
Pradeep Kumar B

**Comment by robwormald** [comment]
As @dawidgarus said, you can implement this behavior yourself via a custom UrlMatcher. It's not something we're planning on implementing.
