### ISSUE TITLE
[IVY] Cannot find namespace 'ctx'

### ISSUE THREAD

**Issue by magnattic** [angular/angular#31087]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler-cli

### Is this a regression?
No

### Description
When I try to compile my large project with Ivy, I get obscure compilation errors and I cannot find out what the problem is. Compilation with the old compiler works fine.

## 🔥 Exception or Error
<pre><code>
➜  frontend git:(master) ✗ node_modules/.bin/ngc
src/app/power/shop/shop.module.ts:117:12 - error NG1010: Value at position 8 in the NgModule.importss of ShopModule is not a reference: [object Object]

117   imports: [
               ~
118     CommonModule,
    ~~~~~~~~~~~~~~~~~
... 
132     EnergyMixModule
    ~~~~~~~~~~~~~~~~~~~
133   ],
    ~~~
__ng_typecheck__.ts:238:65 - error TS2344: Type '"dataSource" | "trackBy" | "inputs" | "carouselLoad" | "onMove"' does not satisfy the constraint '"ngOnInit" | "ngOnDestroy" | "ngDoCheck" | "ngAfterViewInit" | "dataSource" | "trackBy" | "_dataSubscription" | "_dataSource" | "_dataDiffer" | "styleid" | "activePoint" | ... 42 more ... | "velocity"'.
  Type '"inputs"' is not assignable to type '"ngOnInit" | "ngOnDestroy" | "ngDoCheck" | "ngAfterViewInit" | "dataSource" | "trackBy" | "_dataSubscription" | "_dataSource" | "_dataDiffer" | "styleid" | "activePoint" | ... 42 more ... | "velocity"'.

238 const _ctor45: <T = any>(init: Partial<Pick<i73.NguCarousel<T>, "dataSource" | "trackBy" | "inputs" | "carouselLoad" | "onMove">>) => i73.NguCarousel<T> = (null!);
                                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
__ng_typecheck__.ts:1457:81 - error TS2345: Argument of type '{ cloudyOptions: any; imageUrl: any; imageAltText: undefined; any: undefined; }' is not assignable to parameter of type 'Partial<Pick<ResponsiveImageComponent, "isAutoCropped" | "isRound" | "imageAltText" | "sizes" | "imageUrl" | "baseImageWidth" | "fallbackImageWidth" | "cloudyOptions" | "useLazyLoading">>'.
  Object literal may only specify known properties, and 'any' does not exist in type 'Partial<Pick<ResponsiveImageComponent, "isAutoCropped" | "isRound" | "imageAltText" | "sizes" | "imageUrl" | "baseImageWidth" | "fallbackImageWidth" | "cloudyOptions" | "useLazyLoading">>'.

1457         } as any), imageUrl: (ctx.imageUrl + ".png" as any), imageAltText: ( as any), baseImageWidth: (ctx.imageSize as any), fallbackImageWidth: (ctx.imageSize as any), useLazyLoading: (ctx.useLazyLoading as any) });
                                                                                     ~~~
__ng_typecheck__.ts:1457:104 - error TS2503: Cannot find namespace 'ctx'.

1457         } as any), imageUrl: (ctx.imageUrl + ".png" as any), imageAltText: ( as any), baseImageWidth: (ctx.imageSize as any), fallbackImageWidth: (ctx.imageSize as any), useLazyLoading: (ctx.useLazyLoading as any) });
                                                                                                            ~~~
__ng_typecheck__.ts:1457:148 - error TS2503: Cannot find namespace 'ctx'.

1457         } as any), imageUrl: (ctx.imageUrl + ".png" as any), imageAltText: ( as any), baseImageWidth: (ctx.imageSize as any), fallbackImageWidth: (ctx.imageSize as any), useLazyLoading: (ctx.useLazyLoading as any) });
                                                                                                                                                        ~~~
__ng_typecheck__.ts:1457:188 - error TS2503: Cannot find namespace 'ctx'.

1457         } as any), imageUrl: (ctx.imageUrl + ".png" as any), imageAltText: ( as any), baseImageWidth: (ctx.imageSize as any), fallbackImageWidth: (ctx.imageSize as any), useLazyLoading: (ctx.useLazyLoading as any) });
                                                                                                                                                                                                ~~~
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.2
Node: 11.14.0
OS: linux x64
Angular: 8.1.0-next.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.800.2
@angular-devkit/build-angular              0.800.2
@angular-devkit/build-ng-packagr           0.800.2
@angular-devkit/build-optimizer            0.800.2
@angular-devkit/build-webpack              0.800.2
@angular-devkit/core                       8.0.2
@angular-devkit/schematics                 8.0.2
@angular/cdk                               8.0.1
@angular/cli                               8.0.2
@angular/material                          8.0.1
@ngtools/json-schema                       1.1.0
@ngtools/webpack                           8.0.2
@nguniversal/express-engine                7.1.1
@nguniversal/module-map-ngfactory-loader   7.1.1
@schematics/angular                        8.0.2
@schematics/update                         0.800.2
ng-packagr                                 5.3.0
rxjs                                       6.5.2
typescript                                 3.4.5
webpack                                    4.30.0
</code></pre>

**Anything else relevant?**
Any idea what might be the issue for this type of message? I checked the relevant code and couldn't find anything out of the ordinary.

**Comment by kara** [comment]
@magnattic Any more code you can show us? It would be easier to help with a repro.

**Comment by magnattic** [comment]
Actually, I don't even know where to start looking for the problem, because the error is so obscure. Any ideas would be appreciated.

The last errors sound like they come from one of two possible components, `DeviceResponsiveImageComponent` or `ResponsiveImageComponent`. Both components are in a library project within the same AngularCLI workspace. I link the library in tsconfig.json like this:

``` 
  "compilerOptions": {
    ...
    "paths": {
      "@mycompany/ui": ["../projects/ui/src"]
    }
  }
``` 

Here are the components:

**device-responsive-image.component.html**:
```
<eny-responsive-image
  [baseImageWidth]="baseImageWidth"
  [fallbackImageWidth]="fallbackImageWidth"
  [imageUrl]="useMobileImage ? imageUrlMobile : imageUrlDesktop"
  [cloudyOptions]="useMobileImage ? cloudyOptionsMobile : cloudyOptionsDesktop"
  [sizes]="useMobileImage ? sizesMobile : sizesDesktop"
  [imageAltText]="imageAltText"
  [useLazyLoading]="useLazyLoading"
  [isAutoCropped]="isAutoCropped"
></eny-responsive-image>
```

**device-responsive-image.component.ts**:
``` 
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';

@Component({
  selector: 'eny-device-responsive-image',
  templateUrl: './device-responsive-image.component.html',
  styleUrls: ['./device-responsive-image.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class DeviceResponsiveImageComponent {
  @Input() useMobileImage: boolean;
  @Input() useLazyLoading = false;
  @Input() isAutoCropped = true;
  @Input() imageAltText: string;
  @Input() sizesMobile = '100vw';
  @Input() sizesDesktop =
    `(max-width: 575px) 100vw, ` +
    `(min-width: 576px) and (max-width: 767px) 100vw, ` +
    `(min-width: 768px) and (max-width: 991px) 100vw, ` +
    `(min-width: 992px) and (max-width: 1199px) 100vw, ` +
    `(min-width: 1200px) 100vw`;
  @Input() public imageUrlMobile: string;
  @Input() public imageUrlDesktop: string;
  @Input() public baseImageWidth = 900;
  @Input() public fallbackImageWidth = 1920;
  @Input() public cloudyOptionsMobile = {};
  @Input() public cloudyOptionsDesktop = {};
}
``` 

**responsive-image.component.html**:
``` 
<img
  [attr.alt]="imageAltText"
  [sizes]="sizes"
  [src]="src$ | async"
  [srcset]="srcSet$ | async"
  class="responsive-image"
  [class.responsive-image--contain]="!isAutoCropped"
  [class.is-round]="isRound"
/>
```

**responsive-image.component.ts**:
``` 
import { AfterViewInit, ChangeDetectionStrategy, Component, ElementRef, Inject, Input, OnDestroy, PLATFORM_ID } from '@angular/core';
import { BehaviorSubject, combineLatest, Observable, of, ReplaySubject, Subject } from 'rxjs';
import { distinctUntilChanged, map, mapTo, startWith, switchMap, takeUntil } from 'rxjs/operators';
import { ImageSourceGeneratorService } from '../image-source-generator.service';
import { isPlatformServer } from '@angular/common';

@Component({
  selector: 'eny-responsive-image',
  templateUrl: './responsive-image.component.html',
  styleUrls: ['./responsive-image.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class ResponsiveImageComponent implements AfterViewInit, OnDestroy {
  @Input() isAutoCropped = true;
  @Input() isRound = false;
  @Input() imageAltText: string;
  @Input() sizes =
    `(max-width: 575px) 100vw, ` +
    `(min-width: 576px) and (max-width: 767px) 100vw, ` +
    `(min-width: 768px) and (max-width: 991px) 100vw, ` +
    `(min-width: 992px) and (max-width: 1199px) 100vw, ` +
    `(min-width: 1200px) 100vw`;

  @Input() set imageUrl(value: string) {
    this.imageUrl$.next(value);
  }

  @Input() set baseImageWidth(value: number) {
    this.baseImageWidth$.next(value);
  }

  @Input() set fallbackImageWidth(value: number) {
    this.fallbackImageWidth$.next(value);
  }

  @Input() set cloudyOptions(value: object) {
    this.cloudyOptions$.next(value);
  }

  @Input() set useLazyLoading(value: boolean) {
    if (isPlatformServer(this.platform)) {
      return;
    }
    this.useLazyLoading$.next(value);
  }

  public src$: Observable<string>;
  public srcSet$: Observable<string>;
  private readonly imageUrl$ = new ReplaySubject<string>(1);
  private readonly baseImageWidth$ = new BehaviorSubject(900);
  private readonly fallbackImageWidth$ = new BehaviorSubject(1920);
  private readonly cloudyOptions$ = new BehaviorSubject({});
  private readonly useLazyLoading$ = new BehaviorSubject(false);
  private intersectionObserver: IntersectionObserver;
  private readonly triggerLazyLoading$ = new ReplaySubject<void>(1);
  private readonly EMPTY_IMAGE = 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7';
  private readonly ngDestroy$ = new Subject<void>();

  constructor(
    private readonly imageService: ImageSourceGeneratorService,
    private readonly element: ElementRef,
    // tslint:disable-next-line:ban-types
    @Inject(PLATFORM_ID) private readonly platform: Object
  ) {
    const imageIsInView$ = this.triggerLazyLoading$.pipe(
      mapTo(true),
      startWith(false)
    );
    const renderRealImage$ = this.useLazyLoading$.pipe(switchMap(lazy => (!lazy ? of(true) : imageIsInView$)));

    this.src$ = renderRealImage$.pipe(
      switchMap(renderRealImage =>
        renderRealImage
          ? combineLatest([this.imageUrl$, this.cloudyOptions$, this.fallbackImageWidth$]).pipe(map(values => this.buildSrc(...values)))
          : of(this.EMPTY_IMAGE)
      )
    );

    this.srcSet$ = renderRealImage$.pipe(
      switchMap(renderRealImage =>
        renderRealImage
          ? combineLatest([this.imageUrl$, this.cloudyOptions$, this.baseImageWidth$]).pipe(map(values => this.buildSrcSet(...values)))
          : of('')
      )
    );
  }

  ngAfterViewInit() {
    this.useLazyLoading$
      .pipe(
        distinctUntilChanged(),
        takeUntil(this.ngDestroy$)
      )
      // tslint:disable-next-line: rxjs-prefer-async-pipe
      .subscribe(useLazyLoading => {
        if (useLazyLoading) {
          this.setupIntersectionObserver();
        }
      });
  }

  setupIntersectionObserver() {
    if (this.intersectionObserver != null) {
      this.intersectionObserver.unobserve(this.element.nativeElement as Element);
      this.intersectionObserver.disconnect();
    }
    this.intersectionObserver = new IntersectionObserver(this.checkForIntersection, {});
    this.intersectionObserver.observe(this.element.nativeElement);
  }

  ngOnDestroy() {
    if (this.intersectionObserver) {
      this.intersectionObserver.disconnect();
    }
    this.ngDestroy$.next();
    this.ngDestroy$.complete();
  }

  private readonly checkForIntersection = (entries: IntersectionObserverEntry[]) => {
    entries.forEach((entry: IntersectionObserverEntry) => {
      if (this.checkIfIntersecting(entry)) {
        this.triggerLazyLoading$.next();
        this.intersectionObserver.unobserve(this.element.nativeElement as Element);
        this.intersectionObserver.disconnect();
      }
    });
  };

  private checkIfIntersecting(entry: IntersectionObserverEntry) {
    return entry.isIntersecting && entry.target === this.element.nativeElement;
  }

  private buildSrc(imageUrl: string, cloudyOptions: object, fallbackImageWidth: number) {
    return this.imageService.generateFallbackImagetSrc(imageUrl, cloudyOptions, fallbackImageWidth);
  }

  private buildSrcSet(imageUrl: string, cloudyOptions: object, baseImageWidth: number) {
    return this.imageService.generateImageSrcSet(imageUrl, cloudyOptions, baseImageWidth);
  }
}
```

**Comment by JoostK** [comment]
Hi @magnattic, unfortunately I can't reproduce. There's all sorts of weird stuff going on in the `__ng_typecheck__.ts` file it would seem from the errors.

Could you help out and modify `node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_file.js` to log out the full typecheck file, like so:

```patch
--- node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_file.js	Wed Jun 19 23:55:23 2019
+++ node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_file.js	Wed Jun 19 23:55:25 2019
@@ -95,6 +95,7 @@
                 }
                 finally { if (e_3) throw e_3.error; }
             }
+            console.log(source);
             return ts.createSourceFile(this.fileName, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
         };
         TypeCheckFile.prototype.getPreludeStatements = function () { return []; };
```

I'm not sure if that will yield enough data to understand the issue. If you can't share the results publicly please let me know, maybe there's a private way to share the data.

**Comment by magnattic** [comment]
Thanks for your advice, @JoostK, seeing the generated source helps a lot.

It seems there are going on multiple things, some related to ngu-carousel, but another problem is this:

```
function _tcb84(ctx: i91.ProfileImageComponent) { if (true) {
    var _t1 = document.createElement("eny-responsive-image");
    var _t2 = _ctor9({ cloudyOptions: ({
            "aspect_ratio": "1:1",
            "crop": "thumb",
            "gravity": "face",
            "radius": "max",
            "zoom": "0.7"
        } as any), imageUrl: (ctx.imageUrl + ".png" as any), imageAltText: ( as any), baseImageWidth: (ctx.imageSize as any), fallbackImageWidth: (ctx.imageSize as any), useLazyLoading: (ctx.useLazyLoading as any) });
} }
``` 

Looking at the template of ProfileImageComponent:
```
<eny-responsive-image
  ...
  [imageAltText]=""
``` 
Apparently the empty input is being compiled to `mageAltText: ( as any)`.

Is this working as intended?

**Comment by JoostK** [comment]
It's definitely not working as intended ;) The generated typecheck code should always be valid TypeScript code, but apparently it's not.

In the errors in the initial post, there's also this:
```
238 const _ctor45: (init: Partial, "dataSource" | "trackBy" | "inputs" | "carouselLoad" | "onMove">>) => i73.NguCarousel = (null!);
                                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
__ng_typecheck__.ts:1457:81 - error TS2345: Argument of type '{ cloudyOptions: any; imageUrl: any; imageAltText: undefined; any: undefined; }' is not assignable to parameter of type 'Partial>'.
```

That is extremely wrong, the `Partial` type is missing its opening `<` and whatnot.

The problem with `[imageAltText]=""` generating `imageAltText: ( as any)` is also weird to me. There is currently a bug with such empty bindings (see #30076, #30929 and PR #30938), however the known result is that the compiler crashes, not generate invalid code.

Without a reproduction, I can't really tell how to proceed from here. If you are able to reproduce in a repo on GH (doesn't necessarily have to be minimal) that would allow me to have a chat with the debugger sometime ;)

**Comment by chakrachi** [comment]
getting error too when using latest angular beta with ivy
<img width="1113" alt="Screen Shot 2019-07-18 at 4 11 49 PM" src="https://user-images.githubusercontent.com/9326703/61495646-c9e56580-a976-11e9-913f-93406c4e8b2b.png">

**Comment by JoostK** [comment]
Hey @magnattic,

Over the last few months the reporting of type check errors has been significantly improved, so I'd be interested to learn if the issues you were having have maybe been resolved. Could you please test again with `9.0.0-next.10` and report back on your findings? Thanks!

**Comment by magnattic** [comment]
@JoostK Thanks for getting back to me. I refactored a lot of the code in the meantime (for example we don't use a ng library in the workspace anymore), so it's hard to say if the old issues would be fixed with the new compiler.

However, in the current form my project builds fine with ivy. Only issues remaining are at runtime with outdated 3rd party libraries (ngu-carousel). So I will close. Thanks for the work!
