### ISSUE TITLE
Generic [class] binding.

### ISSUE THREAD

**Issue by Y-Less** [angular/angular#3109]
I wrote some code so that `getAlertType()` would return a string, and set the template to (following on from issue #3108):

```html
<div class="alert" role="alert" [id]="getUID('bs_alert_')"
  [class]="getAlertType()"
  [class.alert-dismissable]="isDismissable()"
  [class.fade]="isFadable()"
  [class.in]="isFadable()"
>
    <button *ng-if="isDismissable()" type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <content></content>
</div>
```

The important part being:

```html
[class]="getAlertType()"
```

However, running this gives:

```
Can't bind to 'class' since it isn't a know property of the 'div' element and there are no matching directives with a corresponding property
```

I have found references to this being valid syntax in #2765 so that implies that the fact that it doesn't work is a bug (or an as-yet unimplemented feature, but I also couldn't find reference to that).

**Comment by Y-Less** [comment]
I also tried returning an object looking like `{'name': true}` (as implied in #2765) but no dice.

**Comment by pkozlowski-opensource** [comment]
It already works with the class directive: https://github.com/angular/angular/blob/master/modules/angular2/src/directives/class.ts

You just need to make sure that it is referenced in your @View annotation

**Comment by Y-Less** [comment]
Missing it on the View annotation was the problem, I just wasn't expecting to have to specify that since you don't for any other attribute, or even any explicit `[class.x]`.  Thanks.
