### ISSUE TITLE
Typo in Corporate Proxy under Proxying to a Backend Server

### ISSUE THREAD

**Issue by sedulous-mortal** [angular/angular#31090]
# 📚 Docs or angular.io bug report

### Description

On the Angular Proxy Documentation page, under Proxying to a Backend Server, in the [Corporate Proxy](https://angular.io/guide/build#using-corporate-proxy) section, there is the following typo.

### What's the affected URL?**
https://angular.io/guide/build#using-corporate-proxy

### Reproduction Steps**

Read site

### Expected vs Actual Behavior**

Actual Sentence: "If you work behind a corporate proxy, **the** cannot directly proxy calls to any URL outside your local network."

Expected Sentence:
I think it should read, "If you work behind a corporate proxy, **you** cannot directly proxy calls to any URL outside your local network." or "If you work behind a corporate proxy, the **backend** cannot directly proxy calls to any URL outside your local network."

**Comment by theswanand** [comment]
Looks like this typo has been solved. We can close this issue.
