### ISSUE TITLE
Base Href appending to url

### ISSUE THREAD

**Issue by Nick-lab** [angular/angular#31094]
Hello i am working in an ionic project but i opened a ticket with them and they said its an angular issue as the routing comes from angular

looked for issues pertaining to this i'm using ionic in a dynamically served way. for users to access their administration panel they just browse to http://domain.com/admin i was able to get the app loading correctly from changing the `<base href="/">` to `<base href="admin/">` and on the server the urls requested are correct eg

```
domain.com\admin\runtime.js
domain.com\admin\polyfills.js
domain.com\admin\styles.js
domain.com\admin\vendor.js
domain.com\admin\main.js
domain.com\admin\2.js
domain.com\admin\common.js
domain.com\admin\162.js
domain.com\admin\96.js
domain.com\admin\home-home-module.js
domain.com\admin\6.js
domain.com\admin\4.js
domain.com\admin\3.js
domain.com\admin\assets\icon\favicon.png
```
which is turned into

```
ionic_directory\www\runtime.js
ionic_directory\www\polyfills.js
ionic_directory\www\styles.js
ionic_directory\www\vendor.js
ionic_directory\www\main.js
ionic_directory\www\2.js
ionic_directory\www\common.js
ionic_directory\www\162.js
ionic_directory\www\96.js
ionic_directory\www\home-home-module.js
ionic_directory\www\6.js
ionic_directory\www\4.js
ionic_directory\www\3.js
```
all of the file serving is fine however the issue is that now the url get the admin/ base append onto when its already there turning `http://domain.com/admin` into `http://domain.com/admin/admin/`

### IONIC INFO
ionic (Ionic CLI)             : 4.7.1 (C:\Users\Brian\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

**Comment by dawidgarus** [comment]
Maybe this will be helpful: https://angular.io/api/common/APP_BASE_HREF
You can provide APP_BASE_HREF which is used as base href angular routing only. By default it uses location from `<base href>`, but it can be something else, so it could be independent.

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-issue-repro2).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
