### ISSUE TITLE
feat(Observable): swap underlying RxJS implementation used by EventEmitter with RxJS-Next

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#3110]
I've already started on this, but breaking it into its own task instead of lumping in with #2794.

This will be a breaking change since the API of the observable returned from `toRx()` will be different. Semantically, `EventEmitter` should not change.

https://github.com/reactivex/rxjs

**Comment by jeffbcross** [comment]
Moved to alpha 33 since I'm still trying to figure out the proper way to load the new lib for tests and apps that consume angular.

**Comment by jeffbcross** [comment]
Unassigning this until new RxJS is at alpha release, since there's so much churn in the codebase right now. I'll be helping where I can in the RxJS project to accelerate the alpha.

**Comment by rolandjitsu** [comment]
@jeffbcross [3.0.0](https://github.com/Reactive-Extensions/RxJS/releases/tag/v3.0.0) has also been released, maybe switch to that for now?
