### ISSUE TITLE
Ivy doesn't report about missed component declaration

### ISSUE THREAD

**Issue by fetis** [angular/angular#31108]
# 🐞 bug report

### Affected Package
compiler

### Is this a regression?
yes. 

**Without Ivy**
If you miss component declaration you get an error. Either during AOT build or serve
`ERROR in : Cannot determine the module for class ButtonComponent in ...`

or with JIT in browser  (`ng serve`)
```
compiler.js:2175 Uncaught Error: Template parse errors:
'app-button' is not a known element:
```

**With Ivy**
Nothing reported in both modes! Nieither during the build, nor in the browser console.

### Description
I belive it should be reporting about missed component declaration in all modes. Error message must include missed tag name.

## 🔬 Minimal Reproduction
here's the repo to illistrate the problem
https://github.com/fetis/ng8ivy

I created `ButtonComponent` and comment it in module declaration.

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 8.0.3
Node: 12.4.0
OS: darwin x64
Angular: 8.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              8.0.3
@angular-devkit/schematics        8.0.3
@angular/cli                      8.0.3
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

**Comment by robwormald** [comment]
[Some would say](https://github.com/angular/angular/issues/13590) this is a *feature* :) 

This is expected behavior in Ivy, though we do need to consider how to transition this.

**Comment by fetis** [comment]
> this is a feature :)

:fearful: it's a scary feature imo. let's say you comment some of your code for testing or move it to different folder and you'll miss broken component in templates

**Comment by alxhub** [comment]
Ivy's not done yet :)

This is a component of template type-checking which is not yet implemented. We're still working out exactly how we want this to behave.

**Comment by fetis** [comment]
> Ivy's not done yet :)

hm, I hear different info from different ng-devs. Last time @matsko on local meetup said that the current status is kind of RC and all internal testing is complete.

**Comment by stweedie** [comment]
> [Some would say](https://github.com/angular/angular/issues/13590) this is a _feature_ :)
> 
> This is expected behavior in Ivy, though we do need to consider how to transition this.

Could we get some clarity on this? Ivy won't tell us at build time if we are referencing a component that is not declared by current module or exported by one of current module's imports? 

also, the linked issue is a different story entirely; If I am not referencing a component anywhere, why would I need to declare it?

**Comment by trotyl** [comment]
> Could we get some clarity on this? Ivy won't tell us at build time if we are referencing a component that is not declared by current module or exported by one of current module's imports?

As `NgFactory` wrapper is gone, a component can indeed be used imperatively without being declared in any NgModule, why do you think it's an issue?

**Comment by stweedie** [comment]
Now, I don't think it's an issue. I was unaware that Ivy removed the need for any declaration, which is awesome! I see now what robwormald meant about it being a feature.

**Comment by alxhub** [comment]
What's actually missing here is the template type-checking experience that would tell you if certain elements/bindings in the template were not matched. In this case, our compiler should also know that the component is not part of a module, and let you know that this might be one reason why.

**Comment by kara** [comment]
> hm, I hear different info from different ng-devs. Last time @matsko on local meetup said that the current status is kind of RC and all internal testing is complete.

Ivy isn't RC yet (will be RC when v9 RC comes out). Internal testing is definitely still in-progress. We don't have all the pieces done yet.

**Comment by alxhub** [comment]
Closing as we now have proper template type-checking including the error message that tells you your component should be part of an NgModule.
