### ISSUE TITLE
Router drops question mark in query value

### ISSUE THREAD

**Issue by sidnei** [angular/angular#31116]
# 🐞 bug report

### Affected Package
router

### Is this a regression?
No

### Description

According to https://tools.ietf.org/html/rfc3986#section-3.4, the query part of a URL is allowed to contain '?', however 
https://github.com/angular/angular/blob/master/packages/router/src/url_tree.ts#L428

## 🔬 Minimal Reproduction
- Parse URL with query parameter containing another URL containing a query string, eg:
new DefaultUrlSerializer().parse('/bar?redirect_to=http://bar/baz?yolo=true');
- Parameter 'redirect_to' contains the value of the query string parameter up to the question mark, but anything after that is dropped.
  
https://angular-issue-repro2-b8ljku.stackblitz.io

## 🌍  Your Environment

**Angular Version:**
<pre><code> All?

</code></pre>

**Comment by jasonaden** [comment]
Thanks for the issue. This should definitely be fixed. It would be great to get a PR for this one if a community member can pick this up.

**Comment by MariosRadis** [comment]
I will try to check this one.
