### ISSUE TITLE
service inside a service and directly wants access of methods

### ISSUE THREAD

**Issue by chetanupreti** [angular/angular#31114]
how can access of method of child service directly into a component using instance of parent service.Is there a way to handle this senerio???????

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
