### ISSUE TITLE
Questions about HttpHeader.set(“xx”,"xxx") 

### ISSUE THREAD

**Issue by VolcanoOves** [angular/angular#31128]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

header = new HttpHeaders();
header.set("xxxx","xxxx");
After this method is called, the contents of the header remain empty，But its return value is available.
expect: After the set method is called, this object should contain the content that is set.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by tieppt** [comment]
> HttpHeaders class represents the header configuration options for an HTTP request. Instances should be assumed immutable with lazy parsing.

https://angular.io/api/common/http/HttpHeaders

```
header = new HttpHeaders();
header = header.set("xxxx","xxxx");
```

**Comment by pkozlowski-opensource** [comment]
Sounds like as support request that was [answered](https://github.com/angular/angular/issues/31128#issuecomment-503458972). Thnx @tieppt
