### ISSUE TITLE
import { DOCUMENT } from '@angular/platform-browser';

### ISSUE THREAD

**Issue by madhuri09b** [angular/angular#31127]
Following steps, I have followed for migrating angular 7 to 8
1) ng update --all --force
2) ng serve
3) Resolved errors as per new updates
4) ng build --prod

When I tried to build a project, I am getting an error for 'DOCUMENT' which is inside node_modules
export 'DOCUMENT'  was not found in '@angular/platform-browser'

**Comment by tieppt** [comment]
`import { DOCUMENT } from '@angular/common';`

Docs: https://angular.io/api/common/DOCUMENT

**Comment by madhuri09b** [comment]
Thanks for the quick response.

Error got resolved when we import from
import { DOCUMENT } from '@angular/common';
but that error is inside node_modules which we can not change.
I am using Lightbox package from "angular2-lightbox", inside they have used Document.
Due to this I am getting Uncaught Error: Can't resolve all parameters for Lightbox: ([object Object], [object Object], error.
Kindly provide some solutions.




Thanks & Regards,

Madhuri


________________________________

**Comment by santoshyadav198613** [comment]
This is happening due to third party package, check if they have updated there code as well

**Comment by madhuri09b** [comment]
> This is happening due to third party package, check if they have updated there code as well

Yes, I have updated that third part package with the latest update but no luck. Maybe I need to replace that package

**Comment by mlc-mlapis** [comment]
@madhuri09b … If not dead, the maintainer certainly updates that package. Try to ping him.

**Comment by pkozlowski-opensource** [comment]
Sounds like this needs to be fixed in `angular2-lightbox`

**Comment by madhuri09b** [comment]
For Angular 5, 6, 7, please use ngx-lightbox 1.x.x. npm install ngx-lightbox@1.2.0
For Angular >= 8, please use ngx-lightbox 2.x.x. npm install ngx-lightbox@2.0.0
For Angular 2, 4, please use angular2-lightbox
