### ISSUE TITLE
DOMException: Failed to execute 'attachShadow' on 'Element'

### ISSUE THREAD

**Issue by turbolego** [angular/angular#31135]
# 🐞 bug report

### Description

We have several Angular Elements projects that are working perfectly, but they all have this error in console:

> DOMException: Failed to execute 'attachShadow' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree.

This seems to be a similar/related to this issue posted by @JenPeleva a year ago: https://github.com/angular/angular/issues/24397

I have tried the possible solutions online, but there is not much to go on, and there are only 5 results on google for this specific error message (soon to be 6).

We have been using:
`encapsulation: ViewEncapsulation.ShadowDom,`
in all our projects.

Changing to:
`encapsulation: ViewEncapsulation.Native,`
works too, but gives the same error in console.

Changing to:
`encapsulation: ViewEncapsulation.Emulated,`
removes the error, but then the whole app is gone, blank screen.

## 🔥 Exception or Error
<pre><code>
ERROR DOMException: Failed to execute 'attachShadow' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree.
    at new ShadowDomRenderer (http://localhost:4005/vendor.js:109027:61)
    at DomRendererFactory2.createRenderer (http://localhost:4005/vendor.js:108735:24)
    at AnimationRendererFactory.createRenderer (http://localhost:4005/vendor.js:106454:40)
    at DebugRendererFactory2.createRenderer (http://localhost:4005/vendor.js:64671:49)
    at createComponentView (http://localhost:4005/vendor.js:63186:56)
    at callWithDebugContext (http://localhost:4005/vendor.js:64639:27)
    at Object.debugCreateComponentView [as createComponentView] (http://localhost:4005/vendor.js:63954:12)
    at createViewNodes (http://localhost:4005/vendor.js:63257:46)
    at createRootView (http://localhost:4005/vendor.js:63167:5)
    at callWithDebugContext (http://localhost:4005/vendor.js:64639:27)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.9
Node: 10.15.2
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, elements
... forms, http, language-service, platform-browser
... platform-browser-dynamic, platform-server

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/material                 7.3.7
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.1.1
webpack                           4.29.0
</code></pre>

**Anything else relevant?**
Not sure if this worked before without the error, we have been working on these projects for months and only noticed this error recently without changing encapsulation...

**Comment by robwormald** [comment]
This is pretty hard to debug without seeing how you're using it. The error is coming from the underlying browser API, so the question here is why two are getting created.

**Comment by turbolego** [comment]
We found that some of our Angular Elements projects did not have this error while others did.
The difference was in the app.module.ts file.

The solution to get rid of this error was the following:

1. Add this import:
`import { DoBootstrap } from '@angular/core';`
2. Add the following:
```
entryComponents: [
    AppComponent
  ],
```
3. Set the following:
`bootstrap: [AppComponent]`
to:
`bootstrap: []`
4. Change from:

```
export class AppModule {
  constructor(private injector: Injector) {
    const el = createCustomElement(AppComponent, {
      injector: this.injector
    });
    customElements.define('selector-name-here', el);
  }
}
```

to:

```
export class AppModule implements DoBootstrap {
  constructor(private injector: Injector) {
    const el = createCustomElement(AppComponent, {
      injector: this.injector
    });
    customElements.define('selector-name-here', el);
  }

  ngDoBootstrap() {
  }
}
```

We did not change anything else, and the projects that had this error before no longer have this error.
The projects with this error worked and we only noticed this error when we looked in the console for something else.
Why did the error occur?

Thanks! 😄

**Comment by abadakhshan** [comment]
I Have this problem.
It happens when I create a **"Custom Element "** with  `encapsulation: ViewEncapsulation.ShadowDom`.  
and detach and reattach the element container from **"dom"**.

I think this error happens due to that `"connectedCallback"` calls again on reattach   and  "Angular" try to "attachShadow" again.

**Comment by shashankvivek** [comment]
I came across this question which seems to be related to this bug. 

https://stackoverflow.com/questions/60456917/why-encapsulation-viewencapsulation-shadowdom-is-not-working-for-some-component

**Comment by Romanchuk** [comment]
Angular 9
Demo (see encaps.component):
https://codesandbox.io/s/epic-sky-kf9f4

**Comment by vrapalis** [comment]
I had the same error, move the creation of the elements/components in ngDoBootstrap method.
![image](https://user-images.githubusercontent.com/38319324/80946995-87025a80-8def-11ea-9527-608de85ccffa.png)

**Comment by muratcorlu** [comment]
I have same problem and using `ngDoBootstrap` approach didn't help. This occures when I'm try to use a custom element inside another custom element. I'm using Angular 9.

**Comment by muratcorlu** [comment]
I fixed my issue by using a different tag for my custom element then angular component selector. 

```ts
@Component({
  selector: 'component-one',
  template: `<div>Hello</div>`,
  encapsulation: ViewEncapsulation.ShadowDom
})
...

@Component({
  selector: 'component-two',
  template: `<component-one></component-one>`,
  encapsulation: ViewEncapsulation.ShadowDom
})
```

If I define those components as custom elements with same tag name as `selector`, I get error mentioned above. Then I changed `selector` of `component-one`, and it's working now.

 ```ts
@Component({
  selector: 'app-component-one',
  template: `<div>Hello</div>`,
  encapsulation: ViewEncapsulation.ShadowDom
})
...

@Component({
  selector: 'component-two',
  template: `<app-component-one></app-component-one>`,
  encapsulation: ViewEncapsulation.ShadowDom
})
```

**Comment by gkalpak** [comment]
I am going to clode this, because there is no reproduction from the OP.
If anyone is still running into this problem, please open a new issue providing the necessary details (including a (minimal :pray:) reproduction).

##
BTW, the reproduction provided in https://github.com/angular/angular/issues/31135#issuecomment-592942824 doesn't seem to be related to Angular elements (the app doesn't even use `@angular/elements` afaict).
@muratcorlu, your issue is the same as #24397 (https://github.com/angular/angular/issues/24397#issuecomment-396009894 explains the root cause).
