### ISSUE TITLE
Docs: add doc on breaking change in autoprefixer WRT CSS grid support

### ISSUE THREAD

**Issue by jbogarthyde** [angular/angular#31141]
Document  breaking change in Angular version 8:  autoprefixer turned off css grid support by default.  

See https://github.com/angular/angular/pull/31115#issuecomment-503305862

**Comment by alastair-todd** [comment]
Some extra notes - the only way I could enable the css-grid IE10/11 autofixes was to add this to the top of the global styles file (but can be added at specific css selector scope):

/* autoprefixer grid: autoplace */
or
/* autoprefixer grid: no-autoplace */

[as documented here](https://porter.io/github.com/ai/autoprefixer)

**Comment by jbogarthyde** [comment]
resolved by https://github.com/angular/angular/pull/32109
