### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by Nikos-yps** [angular/angular#31156]
Hello,

I have recently created an app with angular 7 frontend and c# backend and I get this error in console although the app works.
![js-error](https://user-images.githubusercontent.com/15939416/59837440-e4b3c280-9355-11e9-81f6-eee8f9e5b4c0.jpg)
![console-error](https://user-images.githubusercontent.com/15939416/59837442-e4b3c280-9355-11e9-98e6-83bc16f87f96.jpg)

My tsconfig.json configuration is:
`{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "typeRoots": [
      "node_modules/@types"
    ],
    "types": [
      "core-js"
    ]
  }
}
`
Any ideas what might be wrong here and I am getting this error?
Thank you in advance.

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Nikos-yps** [comment]
Hello,

Thank you for the feedback. I have posted the question at stackoverflow.
