### ISSUE TITLE
ivy: ERROR in Cannot have multiple query decorators on the same class member

### ISSUE THREAD

**Issue by slubowsky** [angular/angular#31163]
# 🐞 bug report

### Is this a regression?
No

### Description

Try to use ivy on project that works without ivy. Compilation fails, Get error, but not enough info to try to find cause (project has dozens of components). Looks like error output wants to say where the problem was - "ERROR in" but doesn't actually say where...

## 🔥 Exception or Error
<pre><code>
ERROR in Cannot have multiple query decorators on the same class member
</code>
Once got more info
<code>ERROR in Cannot have multiple query decorators on the same class member
i ｢wdm｣: Failed to compile.
D:\my-app\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:228
                    finally { if (e_2) throw e_2.error; }
                                       ^

Error: Cannot have multiple query decorators on the same class member
    at D:\my-app\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\directive.js:353:23
    at Array.map (<anonymous>)
    at queriesFromFields (D:\my-app\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\directive.js:346:23)
    at Object.extractDirectiveMetadata (D:\my-app\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\directive.js:125:35)
    at ComponentDecoratorHandler.analyze (D:\my-app\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:133:47)
    at analyze (D:\my-app\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:172:60)
    at _loop_1 (D:\my-app\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:212:25)
    at visit (D:\my-app\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:234:21)
    at visitNodes (D:\my-app\node_modules\typescript\lib\typescript.js:16514:30)
i ｢wdm｣: Compiling...
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.3
Node: 12.4.0
OS: win32 x64
Angular: 8.1.0-next.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.3
@angular-devkit/build-angular      0.800.3
@angular-devkit/build-ng-packagr   0.800.3
@angular-devkit/build-optimizer    0.800.3
@angular-devkit/build-webpack      0.800.3
@angular-devkit/core               8.0.3
@angular-devkit/schematics         8.0.3
@angular/cli                       8.0.3
@angular/pwa                       0.800.3
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.3
@schematics/angular                8.0.3
@schematics/update                 0.800.3
ng-packagr                         5.3.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0
</code></pre>

**Anything else relevant?**

**Comment by ericmartinezr** [comment]
If I'm not wrong this will be fixed by https://github.com/angular/angular/pull/31123

**Comment by AndrewKushnir** [comment]
Hi @slubowsky,

As @ericmartinezr mentioned, we have a PR #31123 in progress that would make that particular error message more descriptive - it will contain a reference to a file and class field, so it'd be easier to find and fix the problem. Meanwhile you can try to perform local modification similar to the one from the mentioned PR to get more verbose output.

Thank you.

**Comment by slubowsky** [comment]
Thanks. I did find it by searching for all query decorators in entire project. Found one that accidentally got left behind some time ago when a property was removed, resulting in 2 ViewChild decorators on the next property. I guess ill close this as hopefully error message will improve and I wont be retesting as I have moved past this issue (and on to the next...)
