### ISSUE TITLE
Dart: support observe '>=0.13.1'

### ISSUE THREAD

**Issue by kevmoo** [angular/angular#3117]
Hard-wired to 0.13.1 at the moment. We'd like to support future releases as well.

Per https://github.com/angular/angular/commit/d449ea5ca40d8d5904feee2fa92f27e3ffc5616b#commitcomment-12230154

**Comment by vsavkin** [comment]
@kevmoo can you submit a PR with the fix?

**Comment by kevmoo** [comment]
Way ahead a ya https://github.com/angular/angular/pull/3118

**Comment by vsavkin** [comment]
Thank you so much!
