### ISSUE TITLE
How to dynamically create ngModal  in Angular 7

### ISSUE THREAD

**Issue by ayoubkhan558** [angular/angular#31177]
How to dynamically create ngModal  in Angular 7 on input element and set and get thier values.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by kara** [comment]
@ayoubkhan558 Since this is a support request, our issue tracker isn't the right place to post. Try our Gitter (http://gitter.im/angular/angular) - people tend to be very helpful!
