### ISSUE TITLE
Clicking on the links opening in the same page 

### ISSUE THREAD

**Issue by iMahesh** [angular/angular#31176]
# 📚 Docs or angular.io bug report

### Description

 When I click on the links, the new page opens in the current page by overriding angular.io/xxx page 

### What's the affected URL?**
 https://angular.io/start#getting-started-with-angular-your-first-app

### Reproduction Steps**

Click on any link. The link does not open in the new page.

### Expected vs Actual Behavior**

Expected: When I click on any link the link supposed to open in new page.
Actual: The link opens in the current page.

### Browser info
Google Chrome
Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by kapunahelewong** [comment]
Hi @iMahesh, thanks for bringing this up. I've tested about 10 links on that page but couldn't replicate. Everything works for me as expected. Is it still happening today? Quirky problems like this can happen to me when I don't reboot for a long time.

**Comment by Airblader** [comment]
I can reproduce this, but I think this is how it should be. Every browser allows you to open a link in a new tab if you want, but the opposite would be impossible. IMHO links should only be forced into a new tab if there's volatile state that could be lost, and in a docs page that's not the case.

**Comment by iMahesh** [comment]
When you click on the links, are they opening in a new tab? @kapunahelewong

**Comment by kapunahelewong** [comment]
@iMahesh when I click them, they open in the same tab. No new tabs. I've just confirmed that this is working as expected and is intentional as a good practice. If you prefer to have them open in a new tab, you could `Cmd`+click/right click and select "Open link in a new Tab", though you may already be aware of this. Hope this helps. 🙂
