### ISSUE TITLE
Docs: where you can use template variables

### ISSUE THREAD

**Issue by SoAsEr** [angular/angular#31186]
# 📚 Docs or angular.io bug report

### Description

According to the docs: https://angular.io/guide/template-syntax#ref-vars

>You can refer to a template reference variable anywhere in the component's template.

However, as mentioned here: https://github.com/angular/angular/issues/6179
you cannot link a template reference variable which was declared in an ngIf outside of it. The docs should make that clear

### Expected vs Actual Behavior**
Documentation should reflects the real behaviour

**Comment by Airblader** [comment]
Note that this isn't specific to ngIf in any way, it's just a consequence of structural directives being inline templates. All structural directives or ng-template have the same limitation.

The docs should simply be changed to not say "component template" and maybe some hint that structural directives like ngIf and ng-template create new templates that are a "boundary" (for obvious reasons).

**Comment by kapunahelewong** [comment]
Hey @SoAsEr and @Airblader, how's this wording? #31195

I'd appreciate any help you can offer to make sure it's accurate and clear. ✨

**Comment by kapunahelewong** [comment]
The following is some of what will be in #28700 (but isn't yet):

>There is one additional component, a ChildComponent. The most basic rendered view would look like nested HTML elements such as this:

```
<my-app> <!-- MyAppComponent selector -->
    <app-child> <!-- ChildComponent selector -->
    </app-child>
</my-app>
```
> However, behind the scenes, Angular uses a logical view representation as follows when resolving injection requests:

```
<my-app> <!-- MyAppComponent selector -->
    <#VIEW>
        <app-child> <!-- ChildComponent selector -->
            <#VIEW>
            </#VIEW>
        </app-child>
    </#VIEW>
</my-app>
```

> The <#VIEW> here represents an instance of a template. Notice that each component has its own <#VIEW>; <my-app> and <app-child>.

Maybe this will help in the meantime.
