### ISSUE TITLE
[Ivy] (8.1.0-next.3) Angular hybrid app with custom webpack config

### ISSUE THREAD

**Issue by kmaraz** [angular/angular#31189]
# 🐞 bug report

### Affected Package
Latest Angular packages version 8.1.0-next.3
Latest CLI packages 8.1.0-beta.2

### Description
When I am trying to compile the app with AOT enabled and Ivy enabled, I get the following error: `ERROR in Failed to resolve styles[0] to a string`. There is nothing else to it and that's confusing me.

## 🔬 Minimal Reproduction
<pre><code>
export const styles = [require('./test.component.scss').toString()];

@Component({
  selector: 'test',
  styles,
  template: '<div></div>'
})
export class TestComponent { }
</code></pre>

## 🔥 Exception or Error
<pre><code>
ERROR in Failed to resolve styles[0] to a string
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect          0.801.0-beta.2
@angular-devkit/core               8.0.3
@angular-devkit/schematics         8.0.3
@angular/cdk                       8.0.1
@angular/cli                       8.1.0-beta.2
@angular/material                  8.0.1
@angular/material-moment-adapter   8.0.1
@ngtools/webpack                   8.1.0-beta.2
@schematics/angular                8.1.0-beta.2
@schematics/update                 0.801.0-beta.2
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.35.0
</code></pre>

**Comment by JoostK** [comment]
In the meantime, the error has been improved to point at the class.  @kmaraz Are you expecting this to work? Did this work in ViewEngine?

**Comment by alxhub** [comment]
The error message has been improved since the original request. The error is correct - this is not supported syntax.
