### ISSUE TITLE
Angular TokenKey function 

### ISSUE THREAD

**Issue by hkgupta** [angular/angular#31180]
I have a question regarding the implementation of tokenKey function of angular core library. 
For key why is it using **name + tokensize**? Why not directly the name of the token?
function tokenKey(token) {
    var key = _tokenKeyCache.get(token);
    if (!key) {
        **key = stringify(token) + '_' + _tokenKeyCache.size;**
        _tokenKeyCache.set(token, key);
    }
    return key;
}

I am trying to load a component/module which is AOT compiled with Angular 5x libraries inside an angular application shell which is using Angular 7x libraries. The problem is for some of the dependencies like RendererFactory2, sanitizer etc it is unable to resolve the dependency. After debugging I found that the dependency is there in token cache but with different key than what it is trying to resolve. 
What if I modify this function to use the name of the dependency without appending the number?

function tokenKey(token) {
    var key = _tokenKeyCache.get(token);
    if (!key) {
        **key = stringify(token) **
        _tokenKeyCache.set(token, key);
    }
    return key;
}

Another interesting observation is if I update the libraries of the component to 7x (means both shell and application are in 7x) it works like charm.  
Is this token cache maintained per module or application level?

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
