### ISSUE TITLE
HTTP Interceptor can't resolve all parameters

### ISSUE THREAD

**Issue by SampatPenugonda** [angular/angular#31196]
Hi I am facing Cyclic dependency over here during the implementation of HTTP interceptor. 

Here is my custom interceptor code : 

import { HttpHandler,
    HttpProgressEvent,
    HttpInterceptor,
    HttpSentEvent,
    HttpHeaderResponse,
    HttpUserEvent,
    HttpRequest,
    HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs/Observable';
import {OidcSecurityService} from 'angular-auth-oidc-client';
import { Injector } from '@angular/core';

export class CustomHttpInterceptorService implements HttpInterceptor {
  //private oidcSecurityService: OidcSecurityService;

  constructor(private injector : Injector) {}
    intercept(req: HttpRequest<any>, next: HttpHandler):
      Observable<HttpSentEvent | HttpHeaderResponse | HttpProgressEvent | HttpResponse<any> | HttpUserEvent<any>> {
      var tokenValue = '';
      let _oidcSecurityService = this.injector.get(OidcSecurityService);       
      if (_oidcSecurityService !== undefined) {
        let token = _oidcSecurityService.getToken();
        if (token !== '') {
             tokenValue = 'Bearer ' + token;
           // requestToForward = req.clone({ setHeaders: { Authorization: tokenValue } });
        }
    } else {
        console.debug('OidcSecurityService undefined: NO auth header!');
    }

        const nextReq = req.clone({
        headers: req.headers.set('Cache-Control', 'no-cache')
          .set('Pragma', 'no-cache')
          .set('Expires', 'Sat, 01 Jan 2000 00:00:00 GMT')
           .set('If-Modified-Since', '0')    
           .set('Authorization', tokenValue)       
      });

      return next.handle(nextReq);
  }
}

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by SampatPenugonda** [comment]
Hi, 

Apologies for raising over here. Thanks, I will ask in the stack.
