### ISSUE TITLE
Bazel ng-new schematic doesn't handle less stylesheet format correctly

### ISSUE THREAD

**Issue by henning96** [angular/angular#31209]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/bazel.

### Is this a regression?

No, this never worked.

### Description and Minimal Reproduction

The Bazel ng-new schematic doesn't seem to respect the less stylesheet format option.
I've followed the instructions on https://blog.angular.io/try-bazels-opt-in-preview-in-angular-cli-b9430bd00e82 to create a new Bazel project and selected less as my stylesheet format.
When trying to build the generated project, the build fails with the message:
`index out of range (index is 0, but sequence has 0 elements)` in sass_binary.

## 🔬 Minimal Reproduction
Create a new Bazel project by using the command:
`ng new my-app --collection=@angular/bazel` and choose the less stylesheet format option.
Then try to build the project by running `ng build`.

## 🔥 Exception or Error
<pre><code>
ERROR: workspace_root/src/BUILD.bazel:12:9: Traceback (most recent call last):
        File "workspace_root/src/BUILD.bazel", line 10
                sass_binary(name = "global_stylesheet", src = ...], ...")
        File "workspace_root/src/BUILD.bazel", line 12, in sass_binary
                glob(["styles.css", "styles.scss"])[0]
index out of range (index is 0, but sequence has 0 elements)
ERROR: error loading package 'src': Package 'src' contains errors
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.3
Node: 12.4.0
OS: darwin x64
Angular: 8.0.2
... animations, bazel, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              8.0.3
@angular-devkit/schematics        8.0.3
@angular/cli                      8.0.3
@bazel/bazel                      0.26.1
@bazel/ibazel                     0.10.3
@bazel/karma                      0.31.1
@bazel/typescript                 0.31.1
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by perjerz3434** [comment]
same issue
```
Angular CLI: 8.0.3
Node: 10.15.3
OS: darwin x64
Angular: 8.0.2
... animations, bazel, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              8.0.3
@angular-devkit/schematics        8.0.3
@angular/cli                      8.0.3
@bazel/bazel                      0.26.1
@bazel/bazel-darwin_x64           0.26.1
@bazel/ibazel                     v0.10.3
@bazel/karma                      0.31.1
@bazel/typescript                 0.31.1
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
```

**Comment by perjerz3434** [comment]
I has changed the project to css. The first build is fine.
```
INFO: Analyzed target //src:prodapp (528 packages loaded, 19286 targets configured).
INFO: Found 1 target...
Target //src:prodapp up-to-date:
  dist/bin/src/prodapp
INFO: Elapsed time: 97.560s, Critical Path: 28.03s
INFO: 7 processes: 6 local, 1 worker.
INFO: Build completed successfully, 8102 total actions
```
However, I ran `ng serve`
I got the error message.
```
ng serve 
Error getting Bazel info exec: "bazel": executable file not found in $PATH
error setting higher file descriptor limit for this process: invalid argumentQuerying for files to watch...
Bazel query failed: exec: "bazel": executable file not found in $PATH
Bazel query failed: exec: "bazel": executable file not found in $PATH
Runing //src:devserver
Error running Bazel exec: "bazel": executable file not found in $PATH
/Users/perjerz/bazel/node_modules/@bazel/ibazel/bin/darwin_amd64/ibazel failed with code 4.
```
This error leads to https://github.com/bazelbuild/bazel-watcher/issues/252

After that I ran
```
npm install -g @bazel/bazel
```

Then, I got this error.
```
ng serve                   
error setting higher file descriptor limit for this process: invalid argumentQuerying for files to watch...
Loading: 0 packages loaded
ERROR: /private/var/tmp/_bazel_perjerz/e94172a9a26676c96635c93e5554594c/external/build_bazel_rules_sass_deps/sass/BUILD.bazel:249:1: no such package '@build_bazel_rules_sass_deps//node_modules/sass': BUILD file not found in directory 'node_modules/sass' of external repository @build_bazel_rules_sass_deps and referenced by '@build_bazel_rules_sass_deps//sass:sass'
Loading: 17 packages loaded
Loading: 17 packages loaded
Loading: 22 packages loaded
Loading: 154 packages loaded
    currently loading: @npm//node_modules/arr-union
ERROR: /private/var/tmp/_bazel_perjerz/e94172a9a26676c96635c93e5554594c/external/io_bazel_rules_sass/sass/BUILD:11:1: no such package '@build_bazel_rules_sass_deps//node_modules/sass': BUILD file not found in directory 'node_modules/sass' of external repository @build_bazel_rules_sass_deps and referenced by '@io_bazel_rules_sass//sass:sass_bin'
ERROR: /private/var/tmp/_bazel_perjerz/e94172a9a26676c96635c93e5554594c/external/build_bazel_rules_sass_deps/sass/BUILD.bazel:249:1: no such package '@build_bazel_rules_sass_deps//node_modules/sass': BUILD file not found in directory 'node_modules/sass' of external repository @build_bazel_rules_sass_deps and referenced by '@build_bazel_rules_sass_deps//sass:sass'
ERROR: Evaluation of subquery "deps(set(//src:devserver))" failed (did you want to use --keep_going?): errors were encountered while computing transitive closure
Loading: 266 packages loaded
Loading: 266 packages loaded
Bazel query failed: exit status 7
Loading: 0 packages loaded
ERROR: /private/var/tmp/_bazel_perjerz/e94172a9a26676c96635c93e5554594c/external/io_bazel_rules_sass/sass/BUILD:11:1: no such package '@build_bazel_rules_sass_deps//node_modules/sass': BUILD file not found in directory 'node_modules/sass' of external repository @build_bazel_rules_sass_deps and referenced by '@io_bazel_rules_sass//sass:sass_bin'
ERROR: /private/var/tmp/_bazel_perjerz/e94172a9a26676c96635c93e5554594c/external/build_bazel_rules_sass_deps/sass/BUILD.bazel:249:1: no such package '@build_bazel_rules_sass_deps//node_modules/sass': BUILD file not found in directory 'node_modules/sass' of external repository @build_bazel_rules_sass_deps and referenced by '@build_bazel_rules_sass_deps//sass:sass'
ERROR: Evaluation of subquery "deps(set(//src:devserver))" failed (did you want to use --keep_going?): errors were encountered while computing transitive closure
Loading: 0 packages loaded
Loading: 0 packages loaded
Bazel query failed: exit status 7
Runing //src:devserver
Loading: 0 packages loaded
Loading: 0 packages loaded

Loading: 0 packages loaded
Launching with notifications
listening on :35729
Loading: 
Loading: 0 packages loaded
Analyzing: target //src:devserver (1 packages loaded, 0 targets configured)
ERROR: /private/var/tmp/_bazel_perjerz/e94172a9a26676c96635c93e5554594c/external/io_bazel_rules_sass/sass/BUILD:11:1: no such package '@build_bazel_rules_sass_deps//node_modules/sass': BUILD file not found in directory 'node_modules/sass' of external repository @build_bazel_rules_sass_deps and referenced by '@io_bazel_rules_sass//sass:sass_bin'
ERROR: Analysis of target '//src:devserver' failed; build aborted: no such package '@build_bazel_rules_sass_deps//node_modules/sass': BUILD file not found in directory 'node_modules/sass' of external repository @build_bazel_rules_sass_deps
INFO: Elapsed time: 0.763s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (19 packages loaded, 41 targets configured)
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (19 packages loaded, 41 targets configured)
Error starting process: fork/exec /var/folders/vl/wp3bydl53fvcy8gh1dvnfqxh0000gn/T/bazel_script_path469790526: permission denied
Run start failed fork/exec /var/folders/vl/wp3bydl53fvcy8gh1dvnfqxh0000gn/T/bazel_script_path469790526: permission denied
Triggering live reload
requesting reload: reload
```

**Comment by forssri** [comment]
I am facing similar issues, creating a new project using 8.0.3 angular and latest @angular/bazel and latest @bazel/bazel fails for both ng serve and ng build.

`Analyzing: target //src:devserver (1 packages loaded, 0 targets configured)
ERROR: /private/var/tmp/_bazel_sriram/67919b6f64079d0c1fa653a6ec12dcff/external/bazel_tools/tools/bash/runfiles/BUILD:1:1: in @build_bazel_rules_nodejs//internal/common:sources_aspect.bzl%sources_aspect aspect on sh_library rule @bazel_tools//tools/bash/runfiles:runfiles: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_sriram/67919b6f64079d0c1fa653a6ec12dcff/external/bazel_tools/tools/bash/runfiles/BUILD", line 1
		@build_bazel_rules_nodejs//internal/common:sources_aspect.bzl%sources_aspect(...)
	File "/private/var/tmp/_bazel_sriram/67919b6f64079d0c1fa653a6ec12dcff/external/build_bazel_rules_nodejs/internal/common/sources_aspect.bzl", line 40, in _sources_aspect_impl
		depset([f for f in target.files if f.pa...")], ...])
	File "/private/var/tmp/_bazel_sriram/67919b6f64079d0c1fa653a6ec12dcff/external/build_bazel_rules_nodejs/internal/common/sources_aspect.bzl", line 41, in depset
		[f for f in target.files if f.path.endswith(".js")]
type 'depset' is not iterable. Use the `to_list()` method to get a list. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.
`

**Comment by alan-agius4** [comment]
Hi, at the moment bazel only supports CSS and SASS. 

With regards to the users experiencing other errors, I suggest that a new issue is opening. Since the errors that you are experiencing are not related to the original issue.

Thanks.

**Comment by gurezo** [comment]
Hi @alan-agius4 !
In my PC environment, both CSS and SASS fail to create a project.
Is this a problem with versions such as angular/cli?

```
➜  work ng new ng-bazel-sample --collection="@angular/bazel"
? Would you like to add Angular routing? No
? Which stylesheet format would you like to use? CSS
Schematic input does not validate against the Schema: {"name":"ng-bazel-sample --collection=@angular/bazel","version":"8.0.3","routing":false,"style":"css"}
Errors:

  Data path ".name" should match format "html-selector".
➜  work ng new ng-bazel-sample --collection="@angular/bazel"
? Would you like to add Angular routing? No
? Which stylesheet format would you like to use? Sass   [ http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html       ]
Schematic input does not validate against the Schema: {"name":"ng-bazel-sample --collection=@angular/bazel","version":"8.0.3","routing":false,"style":"sass"}
Errors:

  Data path ".name" should match format "html-selector".
➜  work

➜  work ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 8.0.3
Node: 10.14.1
OS: darwin x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.800.3
@angular-devkit/core         8.0.3
@angular-devkit/schematics   8.0.3
@schematics/angular          8.0.3
@schematics/update           0.800.3
rxjs                         6.4.0
```

**Comment by henning96** [comment]
Hi @alan-agius4,
I see. Is support for Less planned for the Angular 9 release? Or do we have to create our own Bazel rule for this?

**Comment by alan-agius4** [comment]
@henning96, probably we will have a first party rule for Less, but there is no timeframe yet.

**Comment by alan-agius4** [comment]
@gurezo, please file a new issue your error is unrelated to Less.

**Comment by gurezo** [comment]
@alan-agius4 Okay!
i'll making to new issue

**Comment by ManishJainGitHubUser** [comment]
I got the same error using SASS. Can you remove css options from ng new with bazel so we don't go through this pain.
