### ISSUE TITLE
benchpress docs should be provided as g3docs in G3

### ISSUE THREAD

**Issue by tbosch** [angular/angular#3120]
We need to rename the `docs` folder into `g3docs` when deploying benchpress to G3. We probably also need a `METADATA` file that describes the layout, ...

**Comment by mhevery** [comment]
Why don't we just call the `g3docs` to begin with?

**Comment by splincode** [comment]
@tbosch Is the issue relevant?

**Comment by mhevery** [comment]
no longer relevant
