### ISSUE TITLE
Cannot read property 'loadChildren' of null 

### ISSUE THREAD

**Issue by ashu8912** [angular/angular#31206]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

Yes, the previous version in which this bug was not present was: version 6

### Description

So whenever i start my angular server...each time it explodes with this error:-
Cannot read property 'loadChildren' of null 
The temperoray hack that i found for this was each time whenever this error pops up
i do some changes (((like adding some space or anything,,,,that will make angular recompile)))
to the routing.module.ts file the error goes away in the next re compilation step

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

@angular-devkit/architect    0.12.0
@angular-devkit/core         7.2.0
@angular-devkit/schematics   7.2.0
@schematics/angular          7.2.0
@schematics/update           0.12.0
rxjs                         6.3.3
typescript                   3.2.2
</code></pre>

**Anything else relevant?**

**Comment by ashu8912** [comment]
My app.routing.module.ts file looks something like this
```javascript
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { MainComponent } from './main/MainComponent/main.component';
import { NotFoundComponent } from './not-found/not-found.component';
import { SuperAdminComponent } from './super-admin/SuperAdminComponent/super-admin.component';
import SuperAdminRoutes from './utils/routesConfig/superAdminRoutes';
import { LoginComponent } from './auth/login/login.component';
import { AdminAuthGuard } from './guards/can-activate-admin-route.guard';
import { SuperAdminAuthGuard } from './guards/can-activate-super-admin-route.guard';
import { LoginGuard } from './guards/login-route.guard';
import { LogoutComponent } from './auth/logout/logout.component';

const routes: Routes = [{
  path: '',
  component: MainComponent,
  canActivate: [AdminAuthGuard],
  children: [{
    path: '',
    loadChildren:() => import('./main/container/container.module').then(module => module.ContainerModule)
  },
  ]
},
{
  path: 'superAdmin',
  component: SuperAdminComponent,
  children: [
    ...SuperAdminRoutes
  ],
  canActivate: [SuperAdminAuthGuard]

},
{
  path: 'logout',
  component: LogoutComponent
},
{
  path: 'login',
  component: LoginComponent,
  canActivate: [LoginGuard]
},
{
  path: "**",
  component: NotFoundComponent
}];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```

**Comment by codewithdhiman** [comment]
Hey, you can use the children route as follows. 

children: [{
    path: '',
    loadChildren: './main/container/container.module#ContainerModule' // put your path for module#ModuleName here
  }]

**Comment by santoshyadav198613** [comment]
Hi @ashu8912 ,
From logs looks like you are using Angular 7, The native import is available with Angular 8.
Please change your code to use  loadChildren: 'modue_path'

**Comment by ashu8912** [comment]
tried what @codewithdhiman  said but the error still persists

**Comment by ashu8912** [comment]
@santoshyadav198613 yes i am using Angular 7  if the native import is available with version 8
than why does it work when i recompile the app

**Comment by jasonaden** [comment]
Please try this with current Angular and see if that fixes your problem.

The import syntax was not a compilation problem as it's legal JavaScript. But it needed to be wired into the Angular Compiler which was done for v8.
