### ISSUE TITLE
ngOnInit is invoked without the class implementing the OnInit interface.

### ISSUE THREAD

**Issue by kdawg1406** [angular/angular#31217]
# 🐞 bug report

### Description
ngOnInit is invoked without the class implementing the OnInit interface.

## 🔬 Minimal Reproduction
Create a component that does not implement OnInit interface.
Add a ngOnInit method.
Run the app, the ngOnInit method will be invoked.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.3.9
Node: 11.6.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/material                 7.3.7
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Comment by Airblader** [comment]
Implementing interfaces is technically not required because TypeScript works structurally and not declsrstively. It's just good practice to explicitly implement it.

This behavior is completely expected and correct.

**Comment by Airblader** [comment]
Also see https://angular.io/guide/lifecycle-hooks#interfaces-are-optional-technically which already explains this.

**Comment by kdawg1406** [comment]
@Airblader thank you, I didnt' know this.

I do not agree with Angular implementing their code like this.  These interfaces are mere suggestions and not real code contracts, this breaks the notion of code contracts and the use of interfaces. 

I'll close this.

**Comment by Airblader** [comment]
This has nothing to do with Angular, it's how TypeScript works.

**Comment by mlc-mlapis** [comment]
@kdawg1406 ... use classes instead of interfaces then.

**Comment by kdawg1406** [comment]
@Airblader the Angular team could write their code to check for interfaces before checking for a method on the class.

**Comment by mlc-mlapis** [comment]
@kdawg1406 … it would be a real performance hit. If you want to implement the real checking restriction user your own classes and instantiate them with constructors.

**Comment by Airblader** [comment]
In AoT this would be possible, in JIT it's impossible. Also what's the point of defying TypeScript. You talk about losing the idea of contracts, which isn't true if you understood how the structural comparison works.
