### ISSUE TITLE
decorators.ts needs parameter names in function signatures

### ISSUE THREAD

**Issue by uber5001** [angular/angular#3121]
currently, some interfaces provided by `modules/angular2/src/di/decorators.ts` don't have parameter names:

    export interface AncestorFactory {
      /* should be (ParamNameHere?: {self: boolean}): any; */
      ({self: boolean}?): any;
      new ({self: boolean}?): AncestorMetadata;
    }

This is not being caught in the compilation step due to Microsoft/TypeScript#3912

**Comment by jeffbcross** [comment]
Dupe of #3062
