### ISSUE TITLE
run-time error when using static member in `Route#redirectTo`

### ISSUE THREAD

**Issue by s-gusev** [angular/angular#31227]
# 🐞 bug report

### Description

When you define Route#redirectTo via static field it works in debug but fails in prod (AoT enabled)

## 🔬 Minimal Reproduction

minimal changeset to reproduce: https://github.com/s-gusev/demo-test-static-routing/commit/4f8000ffee8d73b6b012d6a0419685877babc5e4

full project: https://github.com/s-gusev/demo-test-static-routing

## 🔥 Exception or Error
<pre><code>

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'split' of null
TypeError: Cannot read property 'split' of null
    at Jl (main.ed34cdf4288be3900171.js:1)
    at Df (main.ed34cdf4288be3900171.js:1)
    at e.matchSegmentAgainstRoute (main.ed34cdf4288be3900171.js:1)
    at e.expandSegmentAgainstRoute (main.ed34cdf4288be3900171.js:1)
    at t.project (main.ed34cdf4288be3900171.js:1)
    at t._next (main.ed34cdf4288be3900171.js:1)
    at t.next (main.ed34cdf4288be3900171.js:1)
    at e._subscribe (main.ed34cdf4288be3900171.js:1)
    at e._trySubscribe (main.ed34cdf4288be3900171.js:1)
    at e.subscribe (main.ed34cdf4288be3900171.js:1)
    at j (polyfills.d64817aaf614d4221ef9.js:1)
    at j (polyfills.d64817aaf614d4221ef9.js:1)
    at polyfills.d64817aaf614d4221ef9.js:1
    at e.invokeTask (polyfills.d64817aaf614d4221ef9.js:1)
    at Object.onInvokeTask (main.ed34cdf4288be3900171.js:1)
    at e.invokeTask (polyfills.d64817aaf614d4221ef9.js:1)
    at t.runTask (polyfills.d64817aaf614d4221ef9.js:1)
    at y (polyfills.d64817aaf614d4221ef9.js:1)
pt @ main.ed34cdf4288be3900171.js:1
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 6.2.9
Node: 8.12.0
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.9
@angular-devkit/build-angular     0.8.9
@angular-devkit/build-optimizer   0.8.9
@angular-devkit/build-webpack     0.8.9
@angular-devkit/core              0.8.9
@angular-devkit/schematics        0.8.9
@angular/cli                      6.2.9
@ngtools/webpack                  6.2.9
@schematics/angular               0.8.9
@schematics/update                0.8.9
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.16.4

</code></pre>

**Comment by s-gusev** [comment]
this issue has the same reproduction steps with https://github.com/angular/angular/issues/16321 but it was about compiled time error while this one about run-time

**Comment by BruneXX** [comment]
Hi guys, I experiencing similar issue as #16321 I'm using angular **v8.2.5** with universal **v8.1.1** when tried to set routes from a json file like:

```
export const routes = [
  { path: `${ROUTES.login}`, component: LoginComponent, pathMatch: 'full' },
  { path: `${ROUTES.register}`, component: RegisterComponent, pathMatch: 'full' }
];
```

Works OK on debug mode but after compilation I'm receiving the following error:

```
 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'split' of null
TypeError: Cannot read property 'split' of null
```

Please any help will be appreciated. Thanks!

**Comment by BruneXX** [comment]
I've tried the demo to test the bug and it's super similar to mine: this is de **DEMO repo** error: `ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'startsWith' of null`

**Comment by BruneXX** [comment]
Hi @IgorMinar sorry to bother you but do you know when could be reviewed by an angular developer in order to apply a fix for this issue? If someone of the team has a workaround for this will be great to know about it, Thanks!

**Comment by BruneXX** [comment]
Hi @jasonaden is there any update on this? thanks!

**Comment by BruneXX** [comment]
Hi @s-gusev Do you had any chance to figured out what's the issue related to this? so, have you inspected the core code that is involved on that? if you so and can be so kind to share to me will be great to help on this, this problem is directly taking a big impact in my current project and I need to find or help to provide a solution in some way. Thanks!

**Comment by BruneXX** [comment]
Hello guys, Is this going to be assigned and reviewed before new angular version comes out?

**Comment by BruneXX** [comment]
Hi Guys, is there any update on this?

**Comment by BruneXX** [comment]
Hi Guys, I haven't heard nothing about this issue, will be reviewed soon? please let me know.

**Comment by sibest19** [comment]
Hi, did you try to use named imports instead of default import?

```ts
import { ROUTES } from 'routes.ts';

export const routes = [
  { path: `${ROUTES.login}`, component: LoginComponent, pathMatch: 'full' },
  { path: `${ROUTES.register}`, component: RegisterComponent, pathMatch: 'full' }
];
```

```ts
// routes.ts
export const ROUTES = {
  login: 'login',
  register: 'register',
}
```

**Comment by BruneXX** [comment]
Yes, in fact (don't remember just right now, I'll double check) but I think I'm doing exactly that, I've tried both ways without success.

**Comment by sibest19** [comment]
Hi again, default exports are not allowed with AoT. Replacing them with named exports will make it work.

https://github.com/sibest19/demo-test-static-routing/commit/494fdf0221d804882512a408293f043555f79f56

**Comment by BruneXX** [comment]
@sibest19 excellent I'll give a try soon and I'll let you know, thanks for your answer!

**Comment by BruneXX** [comment]
Thanks @sibest19 works like a charm! :)

**Comment by JoostK** [comment]
I upgraded your repro to Angular 9.0 and this issue has been resolved in Ivy!
