### ISSUE TITLE
Uninformative Documentation

### ISSUE THREAD

**Issue by artistry-intelligence-solutions** [angular/angular#31225]
**Webpage**: [HostListener](https://angular.io/api/core/HostListener)

**Issue**
I'd consider myself barely an adept at Angular, but it wasn't too long ago since I was a complete novice. I found that certain areas of the Angular documentation are very uninformative (_perhaps I am not reading them correctly?_). 

For example the HostListener section of the documentation does not cover what type of events are covered or how to call them. I personally found the explanation of the method a bit brief. I have found in other sections as well that it is often assumes that the reader has a certain level of understanding of Angular instead of endeavouring to be as informative and in depth as possible. This has led to lengthy discussions online and searches outside of the [Angular](https://angular.io/) website as well beginners lacking an understanding of the possibilities and scope for the method's application.

I would appreciate that (and I am sure so would many other developers) cited complex as well as simple examples of the method's application would be given. Thank you.

**Comment by kapunahelewong** [comment]
Hi @artistry-intelligence-solutions, thanks for bringing this up. Do you have a specific URL(s) and sections in mind?

**Comment by artistry-intelligence-solutions** [comment]
@kapunahelewong thank you for responding to my request. It may also be the case that I am not using the documentation as it was intended, if so I would appreciate any guidance. But here are some urls as you requested:
- https://angular.io/api/core/HostListener
- https://angular.io/api/core/HostBinding
- https://angular.io/guide/observables-in-angular
- https://angular.io/api/common/KeyValuePipe

**Comment by jbogarthyde** [comment]
The API reference pages are meant to provide clear and complete syntax descriptions (although they don’t all do so—we’re working on it). 
The intention is for more comprehensive usage information and extended examples to go into the guides. We are always continuing to improve and add to those as well, but in some cases there is no suitable place to put such content, so we do add more usage details to an API page

**Comment by jbogarthyde** [comment]
@artistry-intelligence-solutions
I'm closing this as too general to address. If you have specific suggestions for improvements to doc, please re-open, or open a new issue.
