### ISSUE TITLE
aot compiler silently misbehaves with expressions derived from es6 default exports

### ISSUE THREAD

**Issue by captaincaius** [angular/angular#31224]
# 🐞 bug report

### Affected Package

Not sure - angular's compiler is black magic to me as of now ;). 

### Is this a regression?

Not sure.

### Description

First off, I thought it's related to https://github.com/angular/angular/issues/11402 but it doesn't look like it - in that case it at least gives you an error and dies, but in this case it compiles with wrong results.  So I think this is a separate issue.  On to the description...

Assuming you have environment.ANIMATIONS set to false, one would expect the following two to both useValue false...

```typescript
@NgModule({
  providers: [
    { provide: 'shouldBeFalse', useValue: environment.ANIMATIONS === true ? true : false },
    environment.ANIMATIONS === true
      ? { provide: 'shouldAlsoBeFalse', useValue: true }
      : { provide: 'shouldAlsoBeFalse', useValue: false },
  ],
})
```

...but they don't.  For some reason, the first case behaves as expected, but the second does NOT, at least in my test case I'll link below.

I think it'll be easier to just look at the diff, but the specific details to make it misbehave (and silently!) are as follows:

- AoT
- environment is a const that comes from a named export in another file
- environment.ANIMATIONS is an expression that depends on an object that comes from a default export of yet another file.

After a couple days of experimentation to figure out why false is true, I was able to get the second pattern to work by changing the second export from a default export to a named export.

I've had the compiler yell at me before when something isn't statically analyzable, but sadly in this case it just merrily gives the wrong result.

## 🔬 Minimal Reproduction

StackBlitz for some reason can't reproduce the problem, and I think it's because it's running JIT.

But here's a PR diff showing how to reproduce it:

https://github.com/captaincaius/rocketdefaultexporttestcase/pull/1/files#diff-5c26d2c8f8838f32ace87fdecd6344eaL26

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

> ng "version"

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.9
Node: 10.14.2
OS: linux x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/flex-layout              7.0.0-beta.24
@angular/material                 7.3.7
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.2.4
webpack                           4.29.0
    

</code></pre>

**Anything else relevant?**

shouldn't be, but I'm running latest chrome.

shouldn't, but just in case:
Ubuntu Linux bionic beaver
vscode
shows up with both yarn and npm
no http server

**Comment by alxhub** [comment]
This is WAI for Angular View Engine. The semantics of static evaluation in providers are really tricky to understand. I think in particular default exports are not well supported.

Fortunately, this example is completely fixed by Ivy which 1) has much better static evaluation and 2) does not evaluate providers at all.
