### ISSUE TITLE
angular.io > Step By Step Guide > User Input has small typos

### ISSUE THREAD

**Issue by ehjay** [angular/angular#3123]
In the User Input page of the angular.io docs:

https://angular.io/docs/js/latest/guide/user-input.html

under the Final Code section there are two typos. Need to change "ngfor" to "ng-for" and "NIf" to "NgIf". That is:

```
 <li *ngfor="#todo of todos">
```

should be

```
 <li *ng-for="#todo of todos">
```

and

```
directives: [NgFor, NIf]
```
should be
```
directives: [NgFor, NgIf]
```

**Comment by SekibOmazic** [comment]
@ehjay You can close the issue here. It belongs to another repo and I've made a PR based on your comments.
