### ISSUE TITLE
Security vulnerability in shelljs

### ISSUE THREAD

**Issue by markgoho** [angular/angular#31236]
https://github.com/shelljs/shelljs/issues/945

shelljs is a dependency of `@angular/compiler-cli`

It does not look like there's a patch for this yet.

**Comment by limonte** [comment]
same here, more info https://github.com/sweetalert2/ngx-sweetalert2/network/alert/yarn.lock/shelljs/open

**Comment by Beyarz** [comment]
> same here, more info https://github.com/sweetalert2/ngx-sweetalert2/network/alert/yarn.lock/shelljs/open

404

**Comment by Beyarz** [comment]
> I’m not quite understanding why that would be a vulnerability. Isn’t the purpose of “exec” to execute an arbitrary command? Wouldn’t that make node itself vulnerable since you can spawn arbitrary commands with it?

You don't want the commands you're executing to include input from "external sources" as previously mentioned. [1](https://github.com/shelljs/shelljs/issues/945)

**Comment by limonte** [comment]
> 404

This is strange. Looks like security issues aren't public, which doesn't make much sense to me. Anyway, here's the screenshot:

![image](https://user-images.githubusercontent.com/6059356/60038210-62f8c780-96bc-11e9-9c52-c9e0d79c7398.png)

**Comment by Beyarz** [comment]
> > 404
> 
> This is strange. Looks like security issues aren't public, which doesn't make much sense to me. Anyway, here's the screenshot:
> 
> ![image](https://user-images.githubusercontent.com/6059356/60038210-62f8c780-96bc-11e9-9c52-c9e0d79c7398.png)

Got the same alert too

**Comment by gkalpak** [comment]
Duplicate of #29460.

**tl;dr**
We are not using `.exec()`, so we are not affected 🤷‍♂
