### ISSUE TITLE
New default module is generated when module is lazy loaded

### ISSUE THREAD

**Issue by shaileshyadav24** [angular/angular#31230]
I've lazy loaded a module, but it returns 2 files:
1. Lazy loaded modules
2. Default module which I'm not sure what it contains
![Screenshot 2019-06-24 at 5 40 54 PM](https://user-images.githubusercontent.com/39512705/60017899-806f6680-96a7-11e9-9a9e-fc40b88fcf2c.jpg)

Any idea about this module?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
