### ISSUE TITLE
While loading one page navigate to another page

### ISSUE THREAD

**Issue by PrabakarKaruppasamy** [angular/angular#31250]
Hi Team,

While loading one page the user navigate to another page before successfully the previous page loads it causing some errors. It appending the previous page to current one.

How can  we kill the previous page if the user navigate to another page immediately or before successfully load that page.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
