### ISSUE TITLE
[compiler-cli 8.1.0-next.3 w/ Ivy] NgModule error regarding HttpClientModule

### ISSUE THREAD

**Issue by juergenzimmermann** [angular/angular#31253]
During compilation I get the following error after upgrading from 8.0 to 8.1:

```
ERROR in node_modules/@angular/common/http/http.d.ts:2799:22 - error TS-996002: Appears in the NgModule.imports of BalkendiagrammModule, but could not be resolved to an NgModule class

2799 export declare class HttpClientModule {
```

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Comment by alexzuza** [comment]
@juergenzimmermann Duplicate of https://github.com/angular/angular/issues/30972
