### ISSUE TITLE
Documenting how to update to specific angular version with `ng update`.

### ISSUE THREAD

**Issue by RyotaMurohoshi** [angular/angular#31259]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

There are some situation that we want to update to specific version, to not latest angular version.

But, there are no description for how to update to specific angular version with `ng update` in [update.angular.io](https://update.angular.io/) and [ng update reference](https://angular.io/cli/update). Caution: not "migrate only update". I refer about update the installed version.

By the way, Acording to [angular-cli/docs/specifications/update.md](https://github.com/angular/angular-cli/blob/v8.0.4/docs/specifications/update.md) ,

> Each package follows the convention of [@scope/]packageName[@version-range-or-dist-tag]. 

So we can use next command to update specific Angular version.

```
ng update @angular/cli@7.0.0 @angular/core@7.0.0
```

Is this above method that update to specific version is defined correctly?
And this is a little hard to find how to update to specific version.
I am so happy if there is documented at [update.angular.io](https://update.angular.io/) or [ng update reference](https://angular.io/cli/update).

related : https://stackoverflow.com/questions/52970467/ng-update-to-specific-angular-version

### Describe the solution you'd like

How about documenting how to update to specific angular version with `ng update` in [update.angular.io](https://update.angular.io/) and [ng update reference](https://angular.io/cli/update)?

```
ng update @angular/cli@7.0.0 @angular/core@7.0.0
```

**Comment by IgorMinar** [comment]
please use `ng update @angular/cli@^<major_version> @angular/core@^<major_version>` instead. e.g. `ng update @angular/cli@^7 @angular/core@^7`. This means take the latest 7.x.x version and use that to update. In general we recommend that you use the latest patch version during update as it contains fixes we released since the initial major release.

**Comment by jordan-amman** [comment]
@RyotaMurohoshi @kapunahelewong @IgorMinar 
I believe I can help fix this issue, but I can only find the CLI Overview page in the source code in aio/content/cli/index.md and not this specific page for ng update: https://angular.io/cli/update

**Comment by jbogarthyde** [comment]
The CLI API doc is in the CLI repo, https://github.com/angular/angular-cli/
I should probably do this, these use a different generation process that is a bit tricky.

**Comment by jbogarthyde** [comment]
Resolved by https://github.com/angular/angular-cli/pull/15897
