### ISSUE TITLE
https://angular.io/guide/attribute-directives  when you copy the title it appends Attribute Directiveslink 

### ISSUE THREAD

**Issue by mjawath** [angular/angular#31254]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by kara** [comment]
There doesn't seem to be enough actionable info in this issue, so closing. Please feel free to open a new one that fills out the template.
