### ISSUE TITLE
docs-infra: a11y issues with API docs

### ISSUE THREAD

**Issue by Splaktar** [angular/angular#31265]
# 📚 Docs or angular.io bug report

### Description
https://github.com/angular/angular/pull/31118 and https://github.com/angular/angular/pull/31252 made changes to some of the placeholder styling on AIO.

I tested the changes in Firefox and these versions (plus previous versions) have the same issue of being overly transparent and not meeting a11y contrast guidelines that we saw in AngularJS Material (https://github.com/angular/material/pull/11497).

### What's the affected URL?**
- https://pr31252-bb25150.ngbuilds.io/api
- https://next.angular.io/api
- https://angular.io/api

### Reproduction Steps**
Inspect the placeholder styling of the filter input.
Run a Lighthouse A11y audit against the page.

### Expected vs Actual Behavior**
The placeholder text and background should have a recommended contrast of 4.5 (AA).

## 📷Screenshot
Firefox:
![Screen Shot 2019-06-25 at 14 47 46](https://user-images.githubusercontent.com/3506071/60124777-617cdd00-9758-11e9-8305-2c0af9e2a0fa.png)
This is unreadable for many people, even those without significant vision issues.

Chrome:
![Screen Shot 2019-06-25 at 14 47 58](https://user-images.githubusercontent.com/3506071/60124779-63df3700-9758-11e9-90a5-51a8f26270b8.png)
This color is still well under the recommended contrast guidelines for a11y
![Screen Shot 2019-06-25 at 15 29 19](https://user-images.githubusercontent.com/3506071/60127387-12d24180-975e-11e9-995b-e1f751efc7bc.png)

## 🔥 Exception or Error
Contrast ratio of `1.45` is well under AA recommendation of `4.5`.

### Browser info
Chrome 75 and Firefox `67.0.3`

**Comment by sjtrimble** [comment]
The original placeholder styles weren't actually applying - I will get on this so it matches the Search box placeholder styling as intended. Thanks!
