### ISSUE TITLE
Bot reports bazel changes do not affect Google3

### ISSUE THREAD

**Issue by kara** [angular/angular#31269]
We just merged a PR (https://github.com/angular/angular/pull/31019) that was reported as "does not affect G3". However, this PR broke a number of i18n tests inside Google. We should no longer exempt those files from G3 checks as they can actually break Google.

**Comment by josephperrott** [comment]
As seen [here](packages/bazel/src/ng_module.bzl) the file (`packages/bazel/src/ng_module.bzl`) which is being synced do g3 should have been detected as included.  However it was considered to be excluded by the bot and resulted in the bot errantly saying the change did not affect g3.  Need to find out why the bot instance made a different determination than this isolated reproduction.

**Comment by kara** [comment]
Moving this to dev-infra Jira
