### ISSUE TITLE
docs(start): StackBlitz devDependencies are listing previous Angular version

### ISSUE THREAD

**Issue by LayZeeDK** [angular/angular#31263]
# 📚 Docs or angular.io bug report

### Description

The `devDependencies` in `package.json` in the Getting started guide are listing Angular version 7.

### What's the affected URL?**
- https://angular.io/generated/live-examples/getting-started-v0/stackblitz.html
- https://angular.io/generated/live-examples/getting-started/stackblitz.html

### Reproduction Steps**
Click the _Click here to create a new project in StackBlitz._ link.
![image](https://user-images.githubusercontent.com/6364586/60124814-c0f3e080-978a-11e9-8072-33e83f36c27b.png)

### Expected vs Actual Behavior**
Expected Angular version 8 in `devDependencies` in `package.json`. Instead, I got version 7:

```
{
  "name": "gaarjjedxev.angular",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "rxjs": "6.5.2",
    "tslib": "1.10.0",
    "core-js": "2.6.9",
    "zone.js": "0.9.1",
    "jasmine-core": "2.99.1",
    "@angular/core": "8.0.2",
    "@angular/forms": "8.0.2",
    "@angular/common": "8.0.2",
    "@angular/router": "8.0.2",
    "jasmine-marbles": "0.6.0",
    "@angular/compiler": "8.0.2",
    "web-animations-js": "2.3.2",
    "@angular/animations": "8.0.2",
    "@angular/platform-browser": "8.0.2",
    "angular-in-memory-web-api": "0.8.0",
    "@angular/platform-browser-dynamic": "8.0.2"
  },
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular/cli": "~7.0.2",
    "@angular/compiler-cli": "~7.0.0",
    "@angular/language-service": "~7.0.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.1"
  }
}
```

## 📷Screenshot
![image](https://user-images.githubusercontent.com/6364586/60124937-01ebf500-978b-11e9-9bb1-da0585641608.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Anything else relevant?
https://github.com/stackblitz/core/issues/1004

**Comment by brandonroberts** [comment]
This is an issue with StackBlitz, as the `package.json` used to generate the example is update to date. https://github.com/angular/angular/blob/master/aio/tools/examples/shared/boilerplate/cli/package.json.


cc: @ericsimons

**Comment by rockument69** [comment]
Issue is with StackBlitz. Can we pass this along and then close it?

**Comment by EricSimons** [comment]
This bug is already fixed I think? Clicked on both links and devDeps are showing v9 versions. Lmk if y’all see otherwise on your end though

**Comment by LayZeeDK** [comment]
For Angular v9 (the current stable version of angular.io), this has been fixed.

If I go back to the Getting started tutorial in the v8 docs:
https://v8.angular.io/start

And click the link https://v8.angular.io/generated/live-examples/getting-started-v0/stackblitz.html or https://v8.angular.io/generated/live-examples/getting-started/stackblitz.html, I now get v8 `dependencies`, but v9 `devDependencies`. Is there any way around this, @EricSimons?
```
{
  "name": "akqbkmrlmgn.angular",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "rxjs": "6.5.5",
    "tslib": "1.13.0",
    "core-js": "2.6.11",
    "zone.js": "0.9.1",
    "jasmine-core": "2.99.1",
    "@angular/core": "8.2.14",
    "@angular/forms": "8.2.14",
    "@angular/common": "8.2.14",
    "@angular/router": "8.2.14",
    "jasmine-marbles": "0.6.0",
    "@angular/compiler": "8.2.14",
    "web-animations-js": "2.3.2",
    "@angular/animations": "8.2.14",
    "@angular/platform-browser": "8.2.14",
    "angular-in-memory-web-api": "0.8.0",
    "@angular/platform-browser-dynamic": "8.2.14"
  },
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.1",
    "@angular/cli": "~9.1.1",
    "@angular/compiler-cli": "~9.1.1",
    "@angular/language-service": "~9.1.1",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}
```

**Comment by EricSimons** [comment]
Unfortunately not because the Angular docs only send the `dependencies` and not `devDependencies`. You can see this by viewing source on the links you posted. In the absence of devDeps we automatically will default to the latest devDeps from Ang CLI on our end.

**Comment by LayZeeDK** [comment]
I see. This sounds like an issue that can be solved by Angular docs. Put a hidden input named `devDependencies`, right?

**Comment by StephenFluin** [comment]
@EricSimons Do you support us sending the devDependencies?

CC: @aikidave

**Comment by LayZeeDK** [comment]
@EricSimons can you confirm?

**Comment by LayZeeDK** [comment]
This is still an issue.

**Comment by dylhunn** [comment]
This is a StackBlitz issue, and seems to have been fixed.

**Comment by LayZeeDK** [comment]
Aaah, finally! ❤
