### ISSUE TITLE
Lazyload Angular Module from URL with singleton services

### ISSUE THREAD

**Issue by infnada** [angular/angular#31261]
# 🚀 feature request

I'm trying to load an angular module from external sources. Meaning i dont know nor have the source code at Application compilling time.

I fetch/load the angular module from URL with SystemJS and compile it.

Code to load Module A, same as Module B:

```typescript

const modules = [
      {
        url: 'https://raw.githubusercontent.com/infnada/angularLazyTest/master/dist/mod-lazy-a/bundles/mod-lazy-a.umd.js',
        name: 'ModLazyAModule',
        componentName: 'ModLazyAComponent'
      },
      {
        url: 'https://raw.githubusercontent.com/infnada/angularLazyTest/master/dist/mod-lazy-b/bundles/mod-lazy-b.umd.js',
        name: 'ModLazyBModule',
        componentName: 'ModLazyBComponent'
      }
    ];

loadLazyModule(lazyMod) {

    return SystemJS.import(lazyMod.url).then((moduleToCompile) => {

      this.compiler.compileModuleAndAllComponentsAsync(moduleToCompile[lazyMod.name]);
    }).then((comp) => {
      comp.ngModuleFactory.create(this.injector);

      lazyMod.factory = comp;

      const componentFactory = lazyMod.factory.componentFactories.filter((component) => {
        return component.componentType.name === lazyMod.componentName;
      })[0];

      // Some ViewContainerRef
      this.lazyComponentAView.createComponent(componentFactory);
    });

  }
```

## 🔬 Minimal Reproduction
https://github.com/infnada/angularLazyTest

## 🔥 Exception or Error

ModLazyA Service constructor is called 2 times (2 different instances of service) even when they are `providedIn: 'root'`

```
mod-loader.service.ts:16 Loading Module ModLazyAModule
18:58:36.065 app.component.ts:40 Waiting before importing LazyModuleB
18:58:36.068 core.js:16829 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
18:58:36.146 mod-lazy-a.service.ts:11 ModLazyA Service constructor
18:58:36.147 mod-lazy-a.module.ts:13 ModLazyA Module constructor
18:58:36.147 mod-lazy-a.module.ts:15 Pushing data from ModLazyA Module constructor
18:58:36.147 mod-lazy-a.module.ts:17 data ["some Data from ModLazyA Module constructor"]
18:58:36.148 mod-lazy-a.component.ts:16 ModLazyA Component constructor
18:58:36.150 mod-lazy-a.component.ts:20 Pushing data from ModLazyA Component ngOnInit
18:58:36.150 mod-lazy-a.component.ts:22 data (2) ["some Data from ModLazyA Module constructor", "some Data from ModLazyA Component ngOnInit"]
18:58:37.640 mod-loader.service.ts:16 Loading Module ModLazyBModule
18:58:37.664 mod-lazy-a.service.ts:11 ModLazyA Service constructor
18:58:37.665 mod-lazy-b.module.ts:15 ModLazyB Module constructor
18:58:37.665 mod-lazy-b.module.ts:17 Getting data from ModLazyB Module constructor
18:58:37.665 mod-lazy-b.module.ts:18 data []
18:58:37.666 mod-lazy-b.component.ts:16 ModLazyB Component constructor
18:58:37.667 mod-lazy-b.component.ts:20 Getting data from ModLazyB Component constructor
18:58:37.667 mod-lazy-b.component.ts:21 data []
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.9
Node: 10.15.3
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.9
@angular-devkit/build-angular      0.13.9
@angular-devkit/build-ng-packagr   0.13.9
@angular-devkit/build-optimizer    0.13.9
@angular-devkit/build-webpack      0.13.9
@angular-devkit/core               7.3.9
@angular-devkit/schematics         7.3.9
@angular/cli                       7.3.9
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.9
@schematics/angular                7.3.9
@schematics/update                 0.13.9
ng-packagr                         4.7.1
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.29.0
</code></pre>

### Describe the solution you'd like

Just be able to lazyLoad **external**  (full url) Services in the root injector.

Anything that allows external module loading and be shared among any other lazyLoaded modules.

Usefull docs about why is creating multiple injectors: https://github.com/angular/angular/issues/30304

**Comment by FRJMGOMEZ** [comment]
Same issue over here.

**Comment by infnada** [comment]
@FRJMGOMEZ just if you need, i end up creating a library inside the main angular app to set and get singleton services. https://github.com/infnada/SysOS/blob/ng7modular/projects/sysos-lib-service-injector/src/lib/services/sysos-lib-service-injector.service.ts

So when i load a module with SystemJS i do a Set https://github.com/infnada/SysOS/blob/ng7modular/projects/sysos-app-infrastructure-manager/src/lib/sysos-app-infrastructure-manager.module.ts#L91

Then on another module loaded with SystemJS i do a Get https://github.com/infnada/SysOS/blob/ng7modular/projects/sysos-app-datastore-explorer/src/lib/body/body-new-connection/body-new-connection.component.ts#L35

And the service is singleton. Hope it helps.

**Comment by trotyl** [comment]
This isn't relates to lazy loading from URL nor single service, the problem is that your bundle file has been executed twice thus creates two different `ModLazyAService` class, and each of them are indeed singleton.

Try add a `console.log` at top level of `mod-lazy-a.service.ts` and file you'll get two logs.

**Comment by jelbourn** [comment]
Tracking the main underlying concern here in #18093
