### ISSUE TITLE
export 'ParamMap' was not found in '@angular/router'

### ISSUE THREAD

**Issue by rallets** [angular/angular#31279]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.0.0

### Description

 A clear and concise description of the problem...
if you use ParamMap interface (ex. helper function) with
import { ParamMap } from '@angular/router';
it raise a compilation error running ng serve or ng test

## 🔬 Minimal Reproduction

 https://github.com/rallets/angular8-router-parammap-bug

## 🔥 Exception or Error
<pre>
<code>

ERROR in ./src/app/parammap.helper.ts 11:12-20
"export 'ParamMap' was not found in '@angular/router'

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.4
Node: 12.4.0
OS: win32 x64
Angular: 8.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.4
@angular-devkit/build-angular     0.800.4
@angular-devkit/build-optimizer   0.800.4
@angular-devkit/build-webpack     0.800.4
@angular-devkit/core              8.0.4
@angular-devkit/schematics        8.0.4
@angular/cli                      8.0.4
@ngtools/webpack                  8.0.4
@schematics/angular               8.0.4
@schematics/update                0.800.4
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

**Comment by baltie** [comment]
I experienced the same when importing an interface from a file that contained a simple class and an interface. Importing the class worked fine. It was not possible to import the interface. If I changed the declaration from `export interface AnInterface {}` to `export class AnInterface {}`, it worked again.

Reverting to @angular-devkit/build-angular version 0.800.3 fixed the problem.

**Comment by atscott** [comment]
This seems to be resolved now. I updated to v10 and did not see the issue. Comments in #31257 mention this may have been fixed in July 2019.
