### ISSUE TITLE
Ngcc doesn't process library secondary entrypoint with path mapping

### ISSUE THREAD

**Issue by log2-hwan** [angular/angular#31274]
# 🐞 bug report

### Affected Package
@angular/compiler-cli

### Is this a regression?
No

### Description
If you execute `npm run build ngcc-test-library && npm run build ngcc-test-app --prod` command on reproduction demo repository, you can see the error I wrote below. And you can also find that `NgccTestSecondaryModule` which is imported by `NgccTestLibraryModule` was not processed by Ngcc. This bug doesn't happen on node_modules libraries, so I guess it only happens when the project has path mappings.

## 🔬 Minimal Reproduction
https://github.com/log2-hwan/ngcc-bug-demo

## 🔥 Exception or Error
<pre><code>
npm run build ngcc-test-library && npm run build ngcc-test-app --prod

> ngcc-bug-demo@0.0.0 build /**/ngcc-bug-demo
> ng build "ngcc-test-library"

Building Angular Package
Building entry point 'ngcc-test-library/ngcc-test-secondary'
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Copying declaration files
Writing package metadata
Built ngcc-test-library/ngcc-test-secondary
Building entry point 'ngcc-test-library'
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Copying declaration files
Writing package metadata
Built ngcc-test-library
Built Angular Package!
 - from: /**/ngcc-bug-demo/projects/ngcc-test-library
 - to:   /**/ngcc-bug-demo/dist/ngcc-test-library

> ngcc-bug-demo@0.0.0 build /**/ngcc-bug-demo
> ng build "ngcc-test-app"

                                                                              h Date: 2019-06-26T07:41:22.822Z
Hash: 7d40b0303089ca29d01d
Time: 3739ms
chunk {main} main-es5.js, main-es5.js.map (main) 658 bytes [initial] [rendered]
chunk {polyfills} polyfills-es5.js, polyfills-es5.js.map (polyfills) 467 kB [initial] [rendered]
chunk {runtime} runtime-es5.js, runtime-es5.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles-es5.js, styles-es5.js.map (styles) 16.9 kB [initial] [rendered]

ERROR in dist/ngcc-test-library/lib/ngcc-test-library.module.d.ts(1,22): error TS-996002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngcc-bug-demo@0.0.0 build: `ng build "ngcc-test-app"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngcc-bug-demo@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.3
Node: 12.4.0
OS: darwin x64
Angular: 8.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.3
@angular-devkit/build-angular      0.800.3
@angular-devkit/build-ng-packagr   0.800.3
@angular-devkit/build-optimizer    0.800.3
@angular-devkit/build-webpack      0.800.3
@angular-devkit/core               8.0.3
@angular-devkit/schematics         8.0.3
@angular/cli                       8.0.3
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.3
@schematics/angular                8.0.3
@schematics/update                 0.800.3
ng-packagr                         5.3.0
rxjs                               6.4.0
typescript                         3.4.5
webpack                            4.30.0
</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
To try out IVY you need to use 8.1.x versions of Angular. @log2-hwan can you try this?

**Comment by log2-hwan** [comment]
I tried angular and angular-cli version 8.1.0-rc.0 and got this error. Seems this time ngcc failed to process library project entirely.
```
npm run build ngcc-test-library && npm run build ngcc-test-app --prod

> ngcc-bug-demo@0.0.0 build /**/ngcc-bug-demo
> ng build "ngcc-test-library"

Building Angular Package
Building entry point 'ngcc-test-library/ngcc-test-secondary'
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Copying declaration files
Writing package metadata
Built ngcc-test-library/ngcc-test-secondary
Building entry point 'ngcc-test-library'
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Copying declaration files
Writing package metadata
Built ngcc-test-library
Built Angular Package!
 - from: /**/ngcc-bug-demo/projects/ngcc-test-library
 - to:   /**/ngcc-bug-demo/dist/ngcc-test-library

> ngcc-bug-demo@0.0.0 build /**/ngcc-bug-demo
> ng build "ngcc-test-app"

  0% compiling
Compiling @angular/core : module as esm5

Compiling @angular/common : module as esm5

Compiling @angular/platform-browser : module as esm5

Compiling @angular/platform-browser-dynamic : module as esm5
                                                                                       
chunk {main} main-es5.js, main-es5.js.map (main) 658 bytes [initial] [rendered]
chunk {polyfills} polyfills-es5.js, polyfills-es5.js.map (polyfills) 479 kB [initial] [rendered]
chunk {runtime} runtime-es5.js, runtime-es5.js.map (runtime) 6.09 kB [entry] [rendered]
chunk {styles} styles-es5.js, styles-es5.js.map (styles) 16.9 kB [initial] [rendered]
Date: 2019-06-28T15:39:05.052Z - Hash: c7bdb2a693f178c31648 - Time: 11408ms

ERROR in Node does not exist: /**/ngcc-bug-demo/dist/ngcc-test-library
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngcc-bug-demo@0.0.0 build: `ng build "ngcc-test-app"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngcc-bug-demo@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!
```

**Comment by petebacondarwin** [comment]
Thanks for the update - I'll look into it at the start of next week.

**Comment by petebacondarwin** [comment]
Sorry I didn't update this issue earlier. I have looked into this and I believe it is a bug in the ngcc `ModuleResolver`. A fix is on the way...

**Comment by petebacondarwin** [comment]
Here it is https://github.com/angular/angular/pull/31450
I tried this fix against your reproduction repo (https://github.com/log2-hwan/ngcc-bug-demo) and it compiled fine locally.
