### ISSUE TITLE
Service Worker how to exclude some API Urls?

### ISSUE THREAD

**Issue by pramod-salian-k** [angular/angular#31275]
I need to bypass some of the url from Service Worker?

**Comment by manekinekko** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by pramod-salian-k** [comment]
What is the use of dataGroups? Here i can exclude url?

https://stackoverflow.com/questions/47693093/angular-5-and-service-worker-how-to-exclude-a-particular-path-from-ngsw-config

**Comment by petebacondarwin** [comment]
@pramod-salian-k - I am sorry but this issue tracker is only for bug reports and feature requests in the Angular framework.

Your messages look more like a support request, which, as @manekinekko pointed out, should be posted on StackOverflow or the mailing list.

**Comment by pramod-salian-k** [comment]
Okay
