### ISSUE TITLE
Add info about updating libraries to static query migration guide

### ISSUE THREAD

**Issue by kara** [angular/angular#31287]
Recent conversations with GDEs have brought up that it's not clear how libraries should handle adding the new static flag for v8 compatibility. [This thread](https://github.com/angular/angular/issues/30654#issuecomment-495642339) has the relevant info about how v7 apps will continue to work with v8 libs that have the static flags (so our recommendation for libs is to update to add the flags). 

Since this thread is difficult to find, we should add the info to the FAQ in the migration guide here:

http://angular.io/guide/static-query-migration

**Comment by kapunahelewong** [comment]
If anyone who knows the ins and outs of this would like to collaborate, please tag me. I can help with getting the PR going, navigating the repo, standards, language, git, etc.

**Comment by gkalpak** [comment]
AFAICT, this has been addressed by #31447, so closing.
@kapunahelewong, feel free to reopen, if I'm wrong.
