### ISSUE TITLE
Typo in docs: "neeed"

### ISSUE THREAD

**Issue by AdrianSchneble** [angular/angular#31282]
# 📚 Docs or angular.io bug report

### Description

Quote from the docs (_emphasis_ mine): "The reverse is also true in that if the child only needs to receive data from the parent, you'd only _neeed_ @Input()."

## 🔬 Minimal Reproduction
N/A

### What's the affected URL?
https://angular.io/guide/template-syntax#input-and-output-are-independent

### Reproduction Steps
N/A

### Expected vs Actual Behavior
One "e" too much in "neeed"

## 📷Screenshot
(I'd add a screenshot, but I can't upload it for some reason)

## 🔥 Exception or Error
N/A

## 🌍  Your Environment
N/A

### Browser info
N/A

### Anything else relevant?
N/A

**Comment by kapunahelewong** [comment]
Thanks, @AdrianSchneble! That one actually has my name all over it. 😁PR submitted! 🌸

**Comment by AdrianSchneble** [comment]
@kapunahelewong no neeed to be ashamed, it happens to the best of us ;)
