### ISSUE TITLE
8.0.4 prod build output fails at runtime

### ISSUE THREAD

**Issue by chadbr** [angular/angular#31286]
### Affected Package
?? not sure?

### Is this a regression?

yes, worked fine in 8.0.0

### Description

Upgraded application from 8.0.0 to 8.0.4 -- and now the production build output fails to load.

To be clear - the build completes successfully - the output fails to load.

## 🔬 Minimal Reproduction

Sorry - I can't do a repo on this one?

## 🔥 Exception or Error
<pre><code>
index.js.pre-build-optimizer.js:1 Uncaught TypeError: Cannot assign to read only property 'MAX_SAFE_INTEGER' of function 'function Number() { [native code] }'
    at index.js.pre-build-optimizer.js:1
    at index.js.pre-build-optimizer.js:1
    at Object.<anonymous> (index.js.pre-build-optimizer.js:1)
    at Object.<anonymous> (index.js.pre-build-optimizer.js:1)
    at i (index.js.pre-build-optimizer.js:1)
    at Module.<anonymous> (index.js.pre-build-optimizer.js:1)
    at i (index.js.pre-build-optimizer.js:1)
    at index.js.pre-build-optimizer.js:1
    at Object.oHoW (index.js.pre-build-optimizer.js:1)
    at f (bootstrap:78)
(anonymous) @ index.js.pre-build-optimizer.js:1
(anonymous) @ index.js.pre-build-optimizer.js:1
(anonymous) @ index.js.pre-build-optimizer.js:1
(anonymous) @ index.js.pre-build-optimizer.js:1
i @ index.js.pre-build-optimizer.js:1
(anonymous) @ index.js.pre-build-optimizer.js:1
i @ index.js.pre-build-optimizer.js:1
(anonymous) @ index.js.pre-build-optimizer.js:1
oHoW @ index.js.pre-build-optimizer.js:1
f @ bootstrap:78
zUnb @ environment.ts:7
f @ bootstrap:78
0 @ survey-template.validator.js.pre-build-optimizer.js:27
f @ bootstrap:78
t @ bootstrap:45
r @ bootstrap:32
(anonymous) @ main-es2015.05bd84a00932f2e2f0a5.js:1
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.4
Node: 10.16.0
OS: win32 x64
Angular: 8.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.4
@angular-devkit/build-angular     0.800.4
@angular-devkit/build-optimizer   0.800.4
@angular-devkit/build-webpack     0.800.4
@angular-devkit/core              8.0.4
@angular-devkit/schematics        8.0.4
@angular/cdk                      8.0.1
@angular/cli                      8.0.4
@angular/flex-layout              7.0.0-beta.19
@angular/material                 8.0.1
@ngtools/webpack                  8.0.4
@schematics/angular               8.0.4
@schematics/update                0.800.4
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Comment by chadbr** [comment]
also... for some reason it switched from a single output:

```
$ node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --configuration production

Date: 2019-06-25T23:17:16.254Z
Hash: 5355a3791e1de2a1487a
Time: 599816ms
chunk {0} runtime.858f8dd898b75fe86926.js, runtime.858f8dd898b75fe86926.js.map (runtime) 1.46 kB [entry] [rendered]
chunk {1} main.146127183af69f8c2413.js, main.146127183af69f8c2413.js.map (main) 8.67 MB [initial] [rendered]
chunk {2} polyfills.a3f585d393ecee6ff04d.js, polyfills.a3f585d393ecee6ff04d.js.map (polyfills) 36.5 kB [initial] [rendered]
chunk {3} styles.cdfd522e0ae14066e741.css, styles.cdfd522e0ae14066e741.css.map (styles) 1.43 MB [initial] [rendered]
chunk {scripts} scripts.200fca3f34e4f3d6a8ec.js, scripts.200fca3f34e4f3d6a8ec.js.map (scripts) 399 bytes [entry] [rendered]
```

to multiple outputs...

```
yarn run v1.16.0
$ node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --configuration production

Date: 2019-06-26T13:22:22.260Z
Hash: 17f9e8b36385d62fc83f
Time: 577929ms
chunk {0} runtime-es5.741402d1d47331ce975c.js, runtime-es5.741402d1d47331ce975c.js.map (runtime) 1.47 kB [entry] [rendered]
chunk {1} main-es5.872a37498392419fab97.js, main-es5.872a37498392419fab97.js.map (main) 9.12 MB [initial] [rendered]
chunk {2} polyfills-es5.0bc13f67d0c1b58f40aa.js, polyfills-es5.0bc13f67d0c1b58f40aa.js.map (polyfills) 111 kB [initial] [rendered]
chunk {scripts} scripts.200fca3f34e4f3d6a8ec.js, scripts.200fca3f34e4f3d6a8ec.js.map (scripts) 399 bytes [entry] [rendered]

Date: 2019-06-26T13:31:52.916Z
Hash: 734afe8a628a9170b33d
Time: 570116ms
chunk {0} runtime-es2015.858f8dd898b75fe86926.js, runtime-es2015.858f8dd898b75fe86926.js.map (runtime) 1.47 kB [entry] [rendered]
chunk {1} main-es2015.05bd84a00932f2e2f0a5.js, main-es2015.05bd84a00932f2e2f0a5.js.map (main) 8.67 MB [initial] [rendered]
chunk {2} polyfills-es2015.a3f585d393ecee6ff04d.js, polyfills-es2015.a3f585d393ecee6ff04d.js.map (polyfills) 36.5 kB [initial] [rendered]
chunk {3} styles.3b0146a33aaa8321c6f4.css, styles.3b0146a33aaa8321c6f4.css.map (styles) 1.44 MB [initial] [rendered]
chunk {scripts} scripts.200fca3f34e4f3d6a8ec.js, scripts.200fca3f34e4f3d6a8ec.js.map (scripts) 399 bytes [entry] [rendered]
```

**Comment by kara** [comment]
@chadbr This issue looks like it belongs in the CLI repo: 

https://github.com/angular/angular-cli
