### ISSUE TITLE
How to continue with tutorial from a specific section in Stackblitz?

### ISSUE THREAD

**Issue by wzup** [angular/angular#31280]
# 📚 Docs or angular.io bug report

### Description

1. I follow Angular tutorial "Your First App".
2. It uses Stackblitz.
3. Stackblitz doesn't store where you left off.
4. I closed my browser window and lost my development state.
5. HOW can I continue from "Managing Data" section in tutorial? I hate to type all previous sections of tutorial again!

**Comment by santoshyadav198613** [comment]
Hi @wzup ,
You can push your code to GitHub repository and than commit changes whenever you make some changes.
You just need to login to stackblitz using git account. 
Also as this is not a error with Angular so it will be closed.

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
