### ISSUE TITLE
Language service "component not in module" error when using `require.context`

### ISSUE THREAD

**Issue by mrahhal** [angular/angular#31303]
# 🐞 bug report

### Affected Package
@angular/language-service

### Is this a regression?
No

### Description

I use dynamic importing of components (require.context) to import them into angular modules. Angular language service can't detect that so it issues me the `Component 'x' is not included in a module and will not be available inside a template. Consider adding it to a NgModule declaration` error on all of my components.

I know that angular can't do much here to detect those usages, so can I at least disable this error in the language service?

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 7.3.2
Node: 12.4.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.2
@angular-devkit/core         7.3.2
@angular-devkit/schematics   7.3.2
@schematics/angular          7.3.2
@schematics/update           0.13.2
rxjs                         6.3.3
typescript                   3.2.4
</code></pre>

**Comment by mrahhal** [comment]
I had to disable this extension completely because all of my html files contain errors because of that.

**Comment by ayazhafiz** [comment]
Unfortunately the language service doesn't currently support disabling errors, but I don't see why it shouldn't be able to. Perhaps we could allow specifying a `.config.ngls` or a section in `package.json` to allow customization of certain rules.

@mrahhal, what would you want this to look like?

**Comment by mrahhal** [comment]
Yes that would help a lot as we still have it disabled in the whole team, we're really missing having analysis in our html files. A standalone file like `.config.ngls` sounds perfect 👌

**Comment by atscott** [comment]
Hi @mrahhal, thanks for reporting this issue. I'm closing it since the underlying problem is covered by the feature RFC #32663
