### ISSUE TITLE
ng build --aot not reporting where the errors are

### ISSUE THREAD

**Issue by pakopa** [angular/angular#31302]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
No

### Description
`ng build --aot` reports an error in a html template, but does not state in which template file

## 🔬 Minimal Reproduction
I have created the sample project [here](https://github.com/pakopa/ng-build-issue-20190626/tree/127ec9aeedbdcdab5762d4f641aa5ee173491a91)

clone and run `ng bulid --aot`

## 🔥 Exception or Error
Expected output when running `ng bulid --aot`
<pre><code>
...
chunk {styles} styles.js, styles.js.map (styles) 16.3 kB [initial] [rendered]

ERROR in : 'test-component' is not a known element:
1. If 'test-component' is an Angular component, then verify that it is part of this module.
2. If 'test-component' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<div style="text-align:center">
  [ERROR ->]<test-component></test-component>
</div>")

</code></pre>

test-component is part of the test-module which is not imported in the app module, the error is correct but nowhere in the error states that the problem is in app.component.html:3

In a project with dozen of template files is quite hard to pinpoint where the error is.

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.9
Node: 10.14.2
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**
running ng build in git bash for windows

**Comment by JoostK** [comment]
Closing as resolved in Ivy, where such messages now indicate exactly where they originated:

![image](https://user-images.githubusercontent.com/123679/74590288-60f9c500-500d-11ea-9dbf-1b80f99afa82.png)
(screenshot taken from the [V9 blog post](https://blog.angular.io/version-9-of-angular-now-available-project-ivy-has-arrived-23c97b63cfa3))
