### ISSUE TITLE
Bug: (^keyup) on a parent element/component does not seem to function

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#3130]
For example, if `MaterialInputComponent`'s template was `<input type="text">', doing the following:

```html
<material-input (^keyup)="onKeyUp()"></material-input>
```

Should be legal. It's working for me with `keydown` and `keyup.enter`, but not standalone.

**Comment by mlaval** [comment]
I had a look at this issue, but I can't reproduce it.
See this plnkr: http://plnkr.co/edit/Z7Ponfks0j0R99lM4EvB

@matanlurey can you please provide more details on the issue?

**Comment by mhevery** [comment]
@matanlurey This has not been update for 2 weeks. Is this still a P1? Sounds like no. If I don't hear in next few days, will close as can't reproduce.

**Comment by mhevery** [comment]
Will close as can not reproduce, Please re-open if you can show a repro case.
