### ISSUE TITLE
Does not have 'ngModuleDef' property.

### ISSUE THREAD

**Issue by markokusljugic** [angular/angular#31311]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

 After enabling Ivy and start project, browser console show error:  does not have 'ngModuleDef' property.

## 🌍 Your Environment
<pre><code>
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              8.0.3
@angular-devkit/schematics        8.0.3
@angular/cdk                      7.3.7
@angular/cli                      8.0.3
@angular/material                 7.3.7
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Comment by jasschul** [comment]
Hi,

if it helps:
 I created a new angular project with --ivy-enable and even after updating to angular next version, I still get an error after adding devextreme.
I copied the files to this repo:
https://github.com/jasschul/angular8-ivytest

**Comment by gkalpak** [comment]
I tried with a recent 9.0.0-next version of Angular and the latest version of `devextreme`/`devextreme-angular` and eveything seems to work fine: angular/ngcc-validation#492

Please open a new issue if you run into something that still doesn't work correctly.
