### ISSUE TITLE
Ivy re-compilation fails

### ISSUE THREAD

**Issue by bampakoa** [angular/angular#31328]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core 8.1.0-rc.0

### Is this a regression?

 Yes, the previous version in which this bug was not present was: @angular/core 8.0.3

### Description

I have enabled Ivy renderer in my project and use the command `ng serve --aot --sourceMap=true` to run it. Compilation of `node_modules` and first build of the project works as expected. Any subsequent changes that I make to the code and cause recompilation of the project, throw error 

>ERROR in Cannot read property `has` of null.

## 🔬 Minimal Reproduction

 I followed the guides for Ivy opt-in for an existing project in https://angular.io/guide/ivy

## 🔥 Exception or Error

![image](https://user-images.githubusercontent.com/7170892/60328615-4d72ee80-9997-11e9-931e-637b8dde3ba4.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.6
Node: 10.15.3
OS: win32 x64
Angular: 8.1.0-rc.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cdk                      8.0.1
@angular/cli                      8.0.6
@angular/material                 8.0.1
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Anything else relevant?**

**Comment by alexzuza** [comment]
`getModifiedResourceFiles` method for Ivy AOT was only released in @ngtools/webpack (8.1.0-beta.2).

Can you please update your CLI version in try it again?

**Comment by bampakoa** [comment]
@alexzuza I installed Angular CLI 8.1.0-rc.0 and the recompilation issue resolved. BTW the speed of recompilation and reload of the application is amazing. You guys rock 🤘 . On the other hand, I am now experiencing a different error. Should I open a new issue or continue to this one?
