### ISSUE TITLE
Add SVG support to DomSanitizer

### ISSUE THREAD

**Issue by waterplea** [angular/angular#31329]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
 There should be a way to sanitize SVG code, right now even `&lt;svg&gt;&lt;/svg&gt;` is getting stripped to nothing by DomSanitizer.sanitize in HTML context. Perhaps there could be separate SVG SecurityContext added, but there should be a way to use SVG via source string in Angular.

### Describe the solution you'd like
 DomSanitizer should be able to sanitize SVG.

### Describe alternatives you've considered
 Creating your own sanitizer, probably using DOMPurify

**Comment by Vandivier** [comment]
Please take a look at the following, and consider upvoting, as a generic solution for this and other similar problems:
https://github.com/angular/angular/issues/36650

**Comment by waterplea** [comment]
Well, I ended up creating my own sanitizer that delegates work to DOMPurify, works pretty good:
https://github.com/TinkoffCreditSystems/ng-dompurify
Might be what you need, but your suggestion is also interesting.

**Comment by waterplea** [comment]
I'm closing this in favor of more upvoted issue mentioned above and due to the fact that Angular already has a way to add own `Sanitizer` implementations.
