### ISSUE TITLE
Search for pipe character (|) finds no results

### ISSUE THREAD

**Issue by randycasburn** [angular/angular#31320]
# 📚 Docs or angular.io bug report

### Description
The linked StackOverflow question "What does the vertical bar in an interpolation mean in Angular?" was asked by a novice Angular user. The OP stated they attempted Google searches and documentation searches to no avail. 

Requesting necessary steps taken to link the Pipe operator documentation to the site search for | (vertical bar).

https://stackoverflow.com/questions/56797648/what-does-the-vertical-bar-in-an-interpolation-mean-in-angular

### What's the affected URL?**
 https://angular.io/docs 

### Reproduction Steps**
1) go to:  https://angular.io/docs 
2) type |  (vertical bar) in search input top right of page
3) hit enter

### Expected vs Actual Behavior**
Actual: blank search header - no results
Expected: at least a single link to the definition of the Pipe operator

**Comment by ajitsinghkaler** [comment]
@gkalpak @petebacondarwin can you please explain how search works in aio I am not able to find the exact function which searches on the website

**Comment by randycasburn** [comment]
This:

https://angular.io/?search=pipes

Will open/expand the search bar at the top of the aio page.

**Comment by gkalpak** [comment]
@randycasburn, I assume @ajitsinghkaler is asking about how it is implemented in code.

There are two kinds of searches in angular.io:
- The one on the [API docs page][1] does a basic (case-insensitive) `indexOf` search in API docs. The code is in [src/app/custom-elements/api/api-list.component.ts][2].
- The one on the top-bar (which searches across the whole site) is powered by [Lunr][3] and uses various rules and heuristics to perform fuzzy-matching, full-text search across the whole docs content (iirc). The code leaves in [src/app/search/][4].
  (To reduce the payload size, the search index is being built on the browser and to keep the performance good the heavy processing is done inside a WebWorker.)

##
Now sure what options we have here for tweaking Lunr to match `|`.
@petebacondarwin knows a lot more than me on this area and he has tweaked the search engine before.

[1]: https://angular.io/api
[2]: https://github.com/angular/angular/tree/1cee9b32c/aio/src/app/custom-elements/api/api-list.component.ts
[3]: https://lunrjs.com/
[4]: https://github.com/angular/angular/tree/1cee9b32c/aio/src/app/search

**Comment by petebacondarwin** [comment]
The keywords for each document are extracted by a dgeni processor:
https://github.com/angular/angular/blob/master/aio/tools/transforms/angular-base-package/processors/generateKeywords.js

Special status is given to member names (of API elements such as classes and interfaces) and also to headings (e.g. in guides). Also each docType can define a property called searchTitle which defaults to the normal title but can be customised if needed.

The processor gets some configuration here: https://github.com/angular/angular/blob/master/aio/tools/transforms/angular-base-package/index.js#L62-L64

Note that we ignore example-region docTypes (as they are not directly rendered but are part of other docs) and also we ignore the renderedContent property, which is basically the HTML form of the doc once it is ready to be rendered.

Finally the Lunr search index is created, configured and queried in a WebWorker, which is all in this file: https://github.com/angular/angular/blob/master/aio/src/app/search/search.worker.ts

We can tweak how much status is given to the different fields in the index: https://github.com/angular/angular/blob/master/aio/src/app/search/search.worker.ts#L30-L33

You’ll also see that we try to search on the query string directly initially: https://github.com/angular/angular/blob/master/aio/src/app/search/search.worker.ts#L87

But if that returns no results then we modify the query to be more relaxed which brings back more terms (but can lead to false-positives): https://github.com/angular/angular/blob/master/aio/src/app/search/search.worker.ts#L89-L92

The last thing to say is that the keyword extraction in the dgeni processor (above) is fairly simplistic.

It does not really capture phrases. We just tokenize the text into a set of unique words, adding in words with ng… removed from the front of the word.

Hope that helps

**Comment by ajitsinghkaler** [comment]
thanks @petebacondarwin for this great explanation I will try to solve the above issue, using your info. I will ping you if any help needed.

**Comment by dario-piotrowicz** [comment]
Sorry if what I am about to suggest is very silly and naive, but I was thinking, could we not just transform the query on the fly to convert specific symbols/words in the general understanding for them?

Like converting a standalone `|` into `pipe` and the like.

Something like this: https://github.com/dario-piotrowicz/angular/commit/f556ef18b933a3921242d9dde2004efc54bff744

It also seems to work reasonably well:
![Peek 2021-06-13 15-51](https://user-images.githubusercontent.com/61631103/121812513-f6d44d00-cc5f-11eb-81f3-94cd770860e2.gif)

I am suggesting this as I believe that special characters are not being used for tokens thus cannot be queried (https://github.com/angular/angular/blob/99f2ffc740279509b89bb96093e2515ce0b46ae1/aio/tools/transforms/angular-base-package/processors/generateKeywords.js#L133) thus I guess they would need an ad-hoc handling

**Comment by petebacondarwin** [comment]
That's a very interesting idea... @dario-piotrowicz

**Comment by petebacondarwin** [comment]
I think it would be good if we could avoid adding too much custom logic to the front-end search. Perhaps instead we could find a way to generate appropriate keywords for pipes that included `|` etc? And ensure that these are considered as valid tokens in the search index?

**Comment by dario-piotrowicz** [comment]
yeah I agree that putting custom login in the front-end just seem hacky and not too good for maintainability.

But I am not sure I'm understanding what you're suggesting since I cannot imagine of any keyword (given that whitespaces are separators) containing `|` except from just the `|` keyword itself.

Are you suggesting to generate keywords containing `|` and also whitespaces? ( like `"| date"` from example)

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
