### ISSUE TITLE
Spanish i18n Date pre-defined formats are wrong.

### ISSUE THREAD

**Issue by blogcraft** [angular/angular#31324]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/common/locales/es

### Is this a regression?

Don't know.

### Description

In Spanish date formats have 4 number years dd/MM/yyyy or d/M/yyyy depending on the country.

But in Angular's Spanish locales, the format is simply d/M/yy 

## 🔬 Minimal Reproduction

Create a new Angular project
in AppModule:
import { LOCALE_ID } from '@angular/core';
import localeEs from '@angular/common/locales/es'; (or any other es locale)

set Privider:     { provide: LOCALE_ID, useValue: 'es' },

in html set a date {{'2010-12-30' | date:'shortDate'}}

## 🔥 Exception or Error

The date will wrongly show as 30/12/10 (d/M/yy)

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.0.0
Node: 11.10.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.800.0
@angular-devkit/core         8.0.0
@angular-devkit/schematics   8.0.0
@schematics/angular          8.0.0
@schematics/update           0.800.0
rxjs                         6.4.0
</code></pre>

**Comment by blogcraft** [comment]
Here is some additional info about country date formats. [Listing of countries with their preferred date formats, ISO3166 code, ISO629-2
](https://gist.github.com/mlconnor/1887156)

**Comment by ocombe** [comment]
Hello, Angular uses [CLDR](http://cldr.unicode.org/) data for all i18n values, if you believe that there is a mistake in those data, please open an issue on the CLDR repository: http://cldr.unicode.org/index/bug-reports
Thanks!
