### ISSUE TITLE
formcontrol not identified within recursive template using ng-container 

### ISSUE THREAD

**Issue by Vikki123** [angular/angular#31339]
# 🐞 bug report

### Affected Package

@angular/forms

### Is this a regression?

Not sure

### Description

I am basically trying to write a common module that will generate nested forms dynamically out of json object. But the formDataName doesn't seem to work inside ng-container. An error is displayed even though the form group is defined.

**Error**

![image](https://user-images.githubusercontent.com/8450434/60351885-58a03b80-99e4-11e9-8f2d-8467e15da941.png)

FormGroup

![image](https://user-images.githubusercontent.com/8450434/60351975-82596280-99e4-11e9-983e-40291200e875.png)

## 🔬 Minimal Reproduction

[Here](https://stackblitz.com/edit/angular-ztx4cp) is the reproduction of the error and the code to display what i am trying to achieve.

## 🔥 Exception or Error
<pre><code>
DynamicForm.html:5 ERROR Error: Cannot find control with name: 'data'
    at _throwError (forms.js:1775)
    at setUpControl (forms.js:1683)
    at FormGroupDirective.push../node_modules/@angular/forms/fesm5/forms.js.FormGroupDirective.addControl (forms.js:4532)
    at FormControlName.push../node_modules/@angular/forms/fesm5/forms.js.FormControlName._setUpControl (forms.js:5030)
    at FormControlName.push../node_modules/@angular/forms/fesm5/forms.js.FormControlName.ngOnChanges (forms.js:4980)
    at checkAndUpdateDirectiveInline (core.js:9239)
    at checkAndUpdateNodeInline (core.js:10507)
    at checkAndUpdateNode (core.js:10469)
    at debugCheckAndUpdateNode (core.js:11102)
    at debugCheckDirectivesFn (core.js:11062)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
"@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.4",
    "ng5-slider": "^1.1.13",
    "node-sass": "^4.11.0",
    "rxjs": "6.3.3",
    "socket.io": "^2.2.0",
    "zone.js": "~0.8.26"

</code></pre>

**Anything else relevant?**

**Comment by jasonaden** [comment]
Thanks for sending the issue. Can you be more explicit though with the reproduction. Yes, I see the error, but to figure out what's happening here I need to go through and debug the code. It would be easier to explicitly have JUST the form control that's erring and remove all the additional loops and conditionals to get to the minimal reproduction.

**Comment by atscott** [comment]
It doesn't appear that your template is set up correctly. In the rendered component, all the controls have the label 'Cart Name'. If you still think this is a problem with Angular, please file a new bug and try to make a more minimal reproduction of the problem that clearly shows the issue.
