### ISSUE TITLE
Allow custom attributes with dot (some-name.some-suffix) interpolation

### ISSUE THREAD

**Issue by n-srg** [angular/angular#31334]
# 🐞 bug report

### Affected Package
Any version i guess

### Is this a regression?
No

### Description
Allow to handle complicated custom attributes by html parser

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-playground-zhx28b

Take a look on `hello-framework.component.html`
```
<button data-ts.label="abc">action 1</button>
<button data-ts.label="{{name}}">action 2</button>
<button [attr.data-ts.label]="name">action 3</button>
```

EXPECTED all three button should have `data-ts.label="some-title"`

## 🔥 Exception or Error
For case with `<button data-ts.label="{{name}}">action 2</button>` it throws
<pre><code>
Error in /turbo_modules/@angular/compiler@7.2.4/bundles/compiler.umd.js (2496:21)
Template parse errors:
Can't bind to 'ts.label' since it isn't a known property of 'button'. ("

<button data-ts.label="some-title">action 1</button>
<button [ERROR ->]data-ts.label="{{title}}">action 2</button>
<button [attr.data-ts.label]="title">action 3</button>"): ng:///HelloFrameworkModule/HelloFrameworkComponent.html@5:8
</code></pre>

Third example with `<button [attr.data-ts.label]="name">action 3</button>`
cuts `.label` suffix

![image](https://user-images.githubusercontent.com/22394106/60339193-4ae1ba80-99d2-11e9-992e-d52287adc74d.png)

**Comment by jessicajaniuk** [comment]
Thanks for reporting this issue. Luckily it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by n-srg** [comment]
Everything is fine now, thank you for closing this, @jessicajaniuk !
