### ISSUE TITLE
ERROR in Symbol when compiling with Ivy

### ISSUE THREAD

**Issue by davidjeliba** [angular/angular#31342]
# 🐞 bug report

### Affected Package

 ngcc?

### Is this a regression?

 Version 8.0.3 which is current latest produces a different error as discussed with @petebacondarwin in angular/angular/pull/27326#issuecomment-506625841. Upgrading to 8.1.0-rc.0 fixes the ModuleWithProviders issue but now is returning error below.

### Description

 When running normal production build with aot=true and Ivy disabled the build process completes successfully. Running with Ivy enabled results in the below error.

## 🔬 Minimal Reproduction
https://github.com/davidjeliba/angular-uirouterhybrid-ivy-issue

master branch uses 8.1.0-rc.0
"latest" branch uses angular@latest which is currently 8.0.3 - I provided this just in case there is any value in seeing the previous ModuleWithProviders error.

To setup/run:

Clone project
run "yarn"
run "yarn build:production" - aot=true, ivy=false - to show successful compilation
run "yarn build:production:ivy" - aot=true, ivy=true - produces the error

## 🔥 Exception or Error
<pre><code>ERROR in Symbol UIRouterModule declared in angular-uirouterhybrid-ivy-issue/node_modules/@uirouter/angular/lib/uiRouterNgModule.d.ts is not exported from @uirouter/angular-hybrid (import into angular-uirouterhybrid-ivy-issue/src/app/child.module.ts)</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 8.1.0-rc.0
Node: 10.15.3
OS: darwin x64
Angular: 8.1.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0-rc.0
@angular-devkit/build-angular     0.801.0-rc.0
@angular-devkit/build-optimizer   0.801.0-rc.0
@angular-devkit/build-webpack     0.801.0-rc.0
@angular-devkit/core              8.1.0-rc.0
@angular-devkit/schematics        8.1.0-rc.0
@ngtools/webpack                  8.1.0-rc.0
@schematics/angular               8.1.0-rc.0
@schematics/update                0.801.0-rc.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.0
</code></pre>

**Anything else relevant?**
After running yarn build:production:ivy and inspecting angular-uirouterhybrid-ivy-issue/node_modules/@uirouter/angular-hybrid/lib/angular-hybrid.d.ts the code is as follows from line 96:
```typescript
export declare class UIRouterUpgradeModule {
    static forRoot(module?: NgHybridStatesModule): ModuleWithProviders<UIRouterUpgradeModule>;
    static forChild(module?: NgHybridStatesModule): ModuleWithProviders<ɵngcc1.UIRouterModule>;
    static ngModuleDef: ɵngcc0.ɵɵNgModuleDefWithMeta<UIRouterUpgradeModule, [typeof UIViewNgUpgrade], [typeof ɵngcc1.UIRouterModule, typeof ɵngcc2.UpgradeModule], [typeof UIViewNgUpgrade, typeof ɵngcc1.UIRouterModule]>;
    static ngInjectorDef: ɵngcc0.ɵɵInjectorDef<UIRouterUpgradeModule>;
}
```

I'm not sure if it is relevant that forRoot has ModuleWithProviders<UIRouterUpgradeModule> while forChild has ModuleWithProviders<engcc1.UIRouterModule>

**Comment by petebacondarwin** [comment]
This is a bug in ngtsc.

When we statically interpret the `ɵngcc1.UIRouterModule` type expression we lose the fact that it is jumping to another file (probably because of the namespaced import). So then ngtsc thinks that `UIRouterModule` was declared inside `@uirouter/angular-hybrid` rather than `@uirouter/angular`. Therefore it thinks that `UIRouterModule` is an internal non-exported class inside `@uirouter/angular-hybrid`, which is basically what the error message is telling us.

Working on a fix :-)

**Comment by petebacondarwin** [comment]
Here we go: https://github.com/angular/angular/pull/31367

**Comment by davidjeliba** [comment]
Very cool, thanks a lot for looking into this so quickly @petebacondarwin

**Comment by james-schwartzkopf** [comment]
Just a note for anyone who gets here through google like I did, this same error messages occurred when I accidentally imported a module from my library using a deep path instead from @scope/mylib.
