### ISSUE TITLE
I discover a bug in transfer data between two components that are not in the same level with rxjs/Subject  

### ISSUE THREAD

**Issue by hassanLoveCar** [angular/angular#31343]
Hi Angular's Team Developer
I what to notice a important issue that I discorded it from angular 5. When we try to transfer(send and receive) data between to components that are not there in the same level. The Subject method is not responsible. 
For example when component A is in a module and component B is in the main root of App folder the Subject method doe not useful and can not transfer data between component A and B. 
At first you should use of subject in a service same at App folder level for sending data from component A to service and after it you should subscribe data in app.component.ts from service and use of @Input() method to send data from app.component.ts to component B.

I found it and test it.
I think angular's team did not have attention to same level of components for transferring data between two components in Subject rxjs method.

+---— app
|   +--— Module
|   |   |--component A
|   |   |-->level component A
|   |
|   |  component B 
|   |
|   |--app.component.ts
|   |--app.module.ts 
|   |-->level component B

Sincerely yours
Hassan Khaleghi Rad.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
