### ISSUE TITLE
Error when try to call super setter/getter (reproduce only with prod task)

### ISSUE THREAD

**Issue by andreisazonov** [angular/angular#31340]
When I try call super getter or super setter when overriding properties? I get an error:
**TS2340: Only public and protected methods of the base class are accessible via the 'super' keyword**.

This error I get only when execute 'ng build --configuration=production --stats-json'

This error appeared after the I update Angular from v7.2.11 to v8.0.3 (TypeScrypt from v3.1.6 to v3.4.5)

**Code example:**
```
export abstract class ChildComponent extends ParentComponent {
	get selected(): boolean {
		return super.selected;
	}
	set selected(selected: boolean) {
		super.selected = selected;
	}
}
```
```
export abstract class ParentComponent {
	public get selected(): boolean {
		return this._selected;
	}
	public set selected(value: boolean) {
		this._selected = value;
	}
}
```

With Angular v7.2.11 and TypeScrypt v3.1.6 there is no such error.

**Comment by Airblader** [comment]
This issue is not related to Angular at all, it's purely about TypeScript. The reason for why this doesn't work can be read up on here: https://github.com/microsoft/TypeScript/issues/338

You'll need to change your compilation target from es5 if you want to be able to use this, which of course impacts which browsers you can support.

**Comment by andreisazonov** [comment]
I don't use targeting to es5. 
My **tsconfig**:
```
{
        "compileOnSave": false,
	"compilerOptions": {
                "downlevelIteration": true,
		"outDir": "./dist",
		"baseUrl": ".",
		"sourceMap": true,
                "declaration": false,
                "moduleResolution": "node",
		"module": "esnext",
		"emitDecoratorMetadata": true,
                "experimentalDecorators": true,
		"noEmitHelpers": true,
		"importHelpers": true,
		"esModuleInterop": true,
		"target": "es2015",
		"typeRoots": [
			"node_modules/@types"
		],
                "lib": [
                       "es2017",
                       "dom"
               ],
               "paths": {
	               ...
               }
        },
        "exclude": [
		...
       ]
}
```

I tried to target es2015, es2016, es2017, but I get the same error in each case.
Maybe there is any errors in my config?

**Comment by andreisazonov** [comment]
[In Angular CLI version 8 and higher, differential loading is enabled by default for the ng build command. ](https://angular.io/guide/deployment#differential-loading)As a result, this produces two builds, and differential loading is enabled. If you ignore browsers without ES2015 support, a single build is produced.

You can do this by setting .browserlistrc to ignore or include browsers that you needed. Otherwise you can add the "browserslist" field to your package.json.
