### ISSUE TITLE
Injection by the equivalent (but not same instance) of the InjectionToken does not work

### ISSUE THREAD

**Issue by denis-itskovich** [angular/angular#31357]
# 🐞 bug report

### Affected Package
`@angular/core`

### Is this a regression?
Not sure
### Description

When provider defines binding for `InjectionToken` (rather than for Type), the injection can be made only with the same instance of `InjectionToken`. It's expected to work with the equivalent InjectionToken as well.

```typescript
    const token1 = new InjectionToken<string>('MyInjectionToken');
    const token2 = new InjectionToken<string>('MyInjectionToken');

    const injector = Injector.create({providers: [
      { provide: token1, useValue: 'My value' }
    ]})

    // Expected: injection should succeed, 
    // Actual: exception is thrown
    const injectedValue = injector.get<string>(token2);
```

## 🔬 Minimal Reproduction
[reproduction at stackblitz](https://stackblitz.com/edit/angular-issue-repro2-snbyse)

## 🔥 Exception or Error
<pre><code>
preview-4adb70f742b91f09679fb.js:1 ERROR Error: StaticInjectorError[InjectionToken MyInjectionToken]: 
  NullInjectorError: No provider for InjectionToken MyInjectionToken!
    at NullInjector.get (injector.ts:39)
    at resolveToken (injector.ts:334)
    at tryResolveToken (injector.ts:276)
    at StaticInjector.get (injector.ts:156)
    at AppComponent.ngOnInit (VM2377 app.component.ts:21)
    at checkAndUpdateDirectiveInline (provider.ts:205)
    at checkAndUpdateNodeInline (view.ts:429)
    at checkAndUpdateNode (view.ts:389)
    at debugCheckAndUpdateNode (services.ts:429)
    at debugCheckDirectivesFn (services.ts:390)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>6.1.1</code></pre>
Reproduced also with Angular 8

**Anything else relevant?**

**Comment by trotyl** [comment]
`InjectionToken` is the typed version of `Symbol`, which is nominal, there are never two equivalent `Symbol`s even their descriptions are same.

**Comment by JoostK** [comment]
As @trotyl mentions, this works as designed. The idea behind `InjectionToken` is that you need the actual instance of the token to be able to retrieve the service from the DI system, as that allows for making DI services truly private by not exposing the `InjectionToken`. The descriptor you pass to `InjectionToken` is not relevant for the actual resolution of the token, it's purely descriptive.
