### ISSUE TITLE
Angular httpclient sends a request with a special character problem

### ISSUE THREAD

**Issue by sz274071580** [angular/angular#31359]
I use angular6. When I use HttpClient to send a request, the parameter has a "+" character. Usually, the "+" is automatically converted to "%2B" in the browser, and the HttpClient of the angular is not "+". Escaped, causing the server to receive is a "space", how should it be solved?

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
