### ISSUE TITLE
Angular 8 Ivy - Components created via eRenderComponent do not invoke lifecycle events??

### ISSUE THREAD

**Issue by Igneous01** [angular/angular#31352]
### Affected Package
Not sure what packages are affected

### Is this a regression?
No

### Description
I'm not sure if this is a bug or intended behavior. 

Creating components dynamically via **ɵrenderComponent** does not fire the lifecycle event **ngOnInit** for that component. Is this intended behavior?

## 🔬 Minimal Reproduction
My reproduction is here: https://github.com/Igneous01/ivy-dynamic-module
In this code there is a feature-module that contains a feature-component with an ngOnInit that logs output to console. This component is rendered dynamically inside of app.component.ts using dynamic import and erenderComponent. When running this solution we can observe that ngOnInit is not called and no output is logged.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.4
Node: 10.16.0
OS: win32 x64
Angular: 8.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.4
@angular-devkit/build-angular     0.800.4
@angular-devkit/build-optimizer   0.800.4
@angular-devkit/build-webpack     0.800.4
@angular-devkit/core              8.0.4
@angular-devkit/schematics        8.0.4
@angular/cli                      8.0.4
@angular/http                     7.2.15
@ngtools/webpack                  8.0.4
@schematics/angular               8.0.4
@schematics/update                0.800.4
rxjs                              6.5.2
typescript                        3.5.2
webpack                           4.30.0
</code></pre>

**Comment by alexzuza** [comment]
I think it's intended behavior.
Root component is special component where you have to provide `LifecycleHooksFeature`:

```
import { 
  ɵrenderComponent as renderComponent,
  ɵLifecycleHooksFeature as LifecycleHooksFeature 
} from '@angular/core';
import { AppComponent } from './app/app.component';

renderComponent(AppComponent, { hostFeatures: [LifecycleHooksFeature] });
```

**Comment by pkozlowski-opensource** [comment]
`renderComponent` API is _highly_ experimental and as such we don't officially support it yet nor accept bug reports for it. Feel free to experiment with those APIs but keep in mind that the exact API and its semantics are subject to change before it gets public.
