### ISSUE TITLE
App doesn't work in Firefox/Waterfox after updating it to Version 8

### ISSUE THREAD

**Issue by Codehan25** [angular/angular#31364]
We have updated an Angular app from version 7.2 to version 8. The update process has worked so far and the app can be used locally and in prod mode (on the server) on Chrome, Firefox Developer Edition, Safari, Opera as usual.

***But in the normal Firefox browser and Waterfox, the app does not work:***

- The app tries to render while the browser shows the status ***"Performing a tls handshake to localhost"***, until at some point a ***"The connection has timed out"*** comes.
- In prod mode, after I have deployed the app, at least the login mask shows up but the performance of the app is so bad that hardly nothing works.

***We have created a browserlist file with the following content:***

    # This file is used by the build system to adjust CSS and JS output to support the specified browsers below.
    # For additional information regarding the format and rule options, please see:
    # https://github.com/browserslist/browserslist#queries
    
    # You can see what browsers were selected by your queries by running:
    # npx browserslist
    
    > 0.5%
    last 2 versions
    Firefox ESR
    not dead
    not IE 9-11 # For IE 9-11 support, remove 'not'.

***Our tsconfig looks like this:***

    {
      "compileOnSave": false,
      "compilerOptions": {
        "downlevelIteration": true,
        "importHelpers": true,
        "outDir": "./dist/out-tsc",
        "baseUrl": "src",
        "sourceMap": true,
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es2015",
        "typeRoots": [
          "Node_modules / @ types"
        ]
        "lib": [
          "ES2016"
          "Dom"
        ]
        "module": "esnext"
      }
    }

***And the area with the ssl configuration inside the angular.json so:***

      "serve": {
        "builder": "@angular-devkit/build-angular:dev-server",
        "options": {
          "browserTarget": "farm-management-ui:build",
          "port": 8080,
          "ssl": true,
          "proxyConfig": "src/proxy.conf.js"
        },

***We have already successfully executed the following commands:***

**ng update @ angular / cli --from 7 --to 8 --migrate - only**

**ng update @ angular / core - from 7 - to 8 --migrate-only**

And I have the feeling that if the app is running in Firefox an endless loop is created, because I can't also open other webpages like Stackoverflow and so on..

Why does Firefox suddenly have this behavior and how can we fix this?

**Comment by alxhub** [comment]
Hello @Codehan25,

Unfortunately it would be very difficult to debug this issue without a reproduction. Is there any way you can share a (maybe reduced) version of the code which causes this problem?

Thanks,
Alex

**Comment by Codehan25** [comment]
Hi @alxhub 

The problem is, there is no place in the code that causes problems. The app will not load in Firefox. No console outputs, no compile or other errors in the CLI. In Chrome, Opera, etc., the app works as usual.

**Comment by jostyposty** [comment]
I have the same problem with Firefox 57.0.4 (I'm locked at this version at the office). 
No problem with Firefox 67.0.4.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
