### ISSUE TITLE
How to deploy Angular Universal App and how to host on windows server?

### ISSUE THREAD

**Issue by bharatbhushanv** [angular/angular#31363]
I'm hosting our project in IIS web server. anyone tell me how to host the universal project in windows server. A normal angular project I move all bundles in dist to my website/All files folder. but in universal, I have two folder server and browser. When I moving all files from server and browser folder then the website is working but angular universal not working.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by bharatbhushanv** [comment]
thank you Joost Koehoon
