### ISSUE TITLE
Compiling sass with bazel

### ISSUE THREAD

**Issue by rerion** [angular/angular#31362]
# 🐞 bug report

### Is this a regression?
There is feature missing for bazel pipeline.

### Description
Build angular pipeline allows for adding global style preprocessor options, in particular
includePaths option for Sass and Stylus.
https://github.com/angular/angular-cli/wiki/stories-global-styles

When using bazel, [multi_sass_binary](https://github.com/bazelbuild/rules_sass#multi_sass_binary) is used to, but it doesn't allow for passing includePaths.

There is a relevant request in rules_sass repository. https://github.com/bazelbuild/rules_sass/issues/90

Additionaly include_paths option takes paths, not labels, therefore its problematic to pass directories from other packages.
It's common to include some directory containing partial scss files from node_modules, currently it's impossible to reference them directly.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.6
Node: 10.15.3
OS: win32 x64
Angular: 8.0.3
... animations, bazel, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic
... platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.6
@angular-devkit/build-angular      0.800.6
@angular-devkit/build-ng-packagr   0.800.6
@angular-devkit/build-optimizer    0.800.6
@angular-devkit/build-webpack      0.800.6
@angular-devkit/core               8.0.6
@angular-devkit/schematics         8.0.6
@angular/cdk                       8.0.1
@angular/cli                       8.0.6
@angular/flex-layout               8.0.0-beta.26
@angular/material                  8.0.1
@bazel/bazel                       0.27.0
@bazel/ibazel                      0.10.3
@bazel/karma                       0.31.1
@bazel/typescript                  0.32.2
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.6
@schematics/angular                8.0.6
@schematics/update                 0.800.6
ng-packagr                         5.2.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0

</code></pre>

**Anything else relevant?**

**Comment by Toxicable** [comment]
>It's common to include some directory containing partial scss files from node_modules, currently it's impossible to reference them directly.

This is incorrect
An example, importing theming.scss from @angular/material would look like 

```
sass_library(
    name = "styles",
    srcs = glob(["*.scss"]) + [
      "@npm//:node_modules/@angular/material/_theming.scss",
    ],
)
```
Then the import is `@import 'external/npm/node_modules/@angular/material/theming';`

**Comment by rerion** [comment]
Thanks for quick response.

The keyword here was 'directly'.
This issue is about reproducing exisiting angular behavior, here's exactly what should be achieved.

In the past one could slam 
```
"stylePreprocessorOptions": {
  "includePaths": [
    "node_modules/@angular/material/"
  ]
},
```
inside angular.json, and then import like `@import 'theming';` from ALL component style files,
regardless of where that file is relative to _theming.scss file.

Now I am of course aware that it's possible to reference files from other modules.

But best to my knowledge it's not possible to reproduce existing angular behavior bazel,
and in consequence switch to bazel without refactoring import paths in components
(and thats BREAKING change).

please correct me if I'm wrong :)

**Comment by herman-rogers** [comment]
> > It's common to include some directory containing partial scss files from node_modules, currently it's impossible to reference them directly.
> 
> You can reference files from node_modules
> 
> An example for importing theming.scss from @angular/material would look like
> 
> ```
> sass_library(
>     name = "styles",
>     srcs = glob(["*.scss"]) + [
>       "@npm//:node_modules/@angular/material/_theming.scss",
>     ],
> )
> ```
> 
> Then the import is `@import 'external/npm/node_modules/@angular/material/theming';`

So I attempted this but I can't for the life of me find any documentation about this and importing node_module files. When I attempt the above I get:

```
 no such target '@npm//:node_modules/path-to-package/styles.scss': target 'node_modules/path-to-package/styles.scss' not declared in package ''; however, a source file of this name exists.  (Perhaps add 'exports_files(["path-to-package"])' to /BUILD?)
```

Am I missing something obvious here?

**Comment by Toxicable** [comment]
@herman-rogers Are you on the latest versions? the syntax for how you'd find the file with bazel changed recently

**Comment by herman-rogers** [comment]
@Toxicable yea I'm on the latest version - I was able to get the target working by doing:

`@npm://node_modules/path-to-package:/dist/styles.scss` I assume that's the syntax you meant? Still wasn't able to import it (the @import 'external' just didn't work). Ended up just hardcoding the paths since its a mono repo for a temp fix.

**Comment by kyliau** [comment]
Bazel builder for Angular CLI has been deprecated since version 10.
Community support is available via the [Angular Bazel](https://github.com/bazelbuild/rules_nodejs/tree/master/examples/angular) repo and the [#angular](http://slack.bazel.build/) channel on Slack.
For more info, please see this [migration doc](https://github.com/angular/angular/blob/master/packages/bazel/src/schematics/README.md).
