### ISSUE TITLE
[innerHtml] causing error from angular 8

### ISSUE THREAD

**Issue by Domainv** [angular/angular#31366]
# 🐞 bug report

### Affected Package
angular/*@8.0.0

### Is this a regression?

This used to work in:
angular/*@7.2.6

### Description

After migrating to Angular 8, [innerHtml] binding starts causing error

## 🔬 Minimal Reproduction
<div [innerHtml]="text">

## 🔥 Exception or Error
<pre><code>
ERROR in demo/src/__ng_typecheck__.ts(857,9): error TS2551: Property 'innerHtml' does not exist on type 'HTMLParagraphElement'.
</code></pre>

## 🌍  Your Environment

Angular CLI: 8.0.2
Node: 10.16.0
OS: linux x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.800.2
@angular-devkit/build-angular              0.800.2
@angular-devkit/build-optimizer            0.800.2
@angular-devkit/build-webpack              0.800.2
@angular-devkit/core                       8.0.1
@angular-devkit/schematics                 8.0.1
@angular/cli                               8.0.2
@ngtools/json-schema                       1.1.0
@ngtools/webpack                           8.0.2
@nguniversal/common                        7.1.1
@nguniversal/express-engine                7.1.1
@nguniversal/module-map-ngfactory-loader   7.1.1
@schematics/angular                        8.0.1
@schematics/update                         0.800.2
ng-packagr                                 5.1.0
rxjs                                       6.4.0
typescript                                 3.4.5
webpack                                    4.30.0

**Comment by alexzuza** [comment]
Looks like your Angular version doesn't contain these changes https://github.com/angular/angular/pull/30675/commits/2e9f3f6ff0767e12b142e03b5524deb60f734b9f

Can you please try to update Angular to the latest version and check it again?

**Comment by santoshyadav198613** [comment]
Hi @Domainv ,

actually, the property is [innerHTML ]https://www.w3schools.com/jsref/prop_html_innerhtml.asp.

Maybe it was working because Angular 7 had no strict check for templates. change to [innerHTML]

**Comment by Domainv** [comment]
Thank you for answers

**Comment by JoostK** [comment]
It appears as if you are using Ivy (in production? 🙀), as the error you're seeing is from the new typecheck infrastructure introduced for Ivy in 8.0. You should have more success with `8.1.0-rc.0`.

**Comment by Domainv** [comment]
@JoostK Yes, we use Ivy on ngx-bootstrap :)
