### ISSUE TITLE
Angular is too complex and grammatical anti-human. It's really hard to use.

### ISSUE THREAD

**Issue by 690284557** [angular/angular#31360]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: 
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by pkozlowski-opensource** [comment]
Thnx for the feedback but those are very general / vague statement and as such not really actionable. If you would like to point out attention to specific areas please open a new issue with a detailed description of a problem as requested in the issue template.
