### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by DanielFrugoni** [angular/angular#31375]
ERROR in The Angular Compiler requires TypeScript >=3.4.0 and <3.5.0 but 3.6.0-dev.20190701 was found instead.

Cant solve, no matter what I DO

**Comment by santoshyadav198613** [comment]
Can you check your package.json which version of typescript is added? If it's 3.4 and still you are getting this issue, check if any of the 3rd party library uses the mentioned version.

**Comment by DanielFrugoni** [comment]
3.6.0-dev20190701

**Comment by santoshyadav198613** [comment]
Ohh looks like you update typescript to latest version , please change it to 3.4.0 and do npm install .it will work

**Comment by DanielFrugoni** [comment]
get this, trying to install 3.4.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for typescript@3.4.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

or Im installing it the wrong way ?

**Comment by santoshyadav198613** [comment]
"typescript": "~3.4.3"

**Comment by DanielFrugoni** [comment]
Let see if Im doing it ok.
 "devDependencies": {
    "@angular-devkit/build-angular": "~0.801.0-rc.0",
    "@angular/cli": "^8.1.0-rc.0",
    "@angular/compiler-cli": "^8.1.0-rc.0",
    "@angular/language-service": "~8.1.0-rc.0",
    "@types/cors": "^2.8.5",
    "@types/jasmine": "~3.3.13",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.0.10",
    "codelyzer": "^5.1.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.5",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.2",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "~3.4.3"
  }
then ng serve  and I get

ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/reflect' in 'D:\demoshub\demoshub\src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es7/reflect' in 'D:\demoshub\demoshub\src'
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
