### ISSUE TITLE
set-cookie header will be ignored even by enabling withCredentials option, when using with electronjs

### ISSUE THREAD

**Issue by MetaiR** [angular/angular#31373]
Hi,

I know I shouldn't post these kinds of stuff here but I am desperate and hopeless, I already asked my question on stackoverflow, here https://stackoverflow.com/questions/56829754/set-cookie-header-will-be-ignored-even-by-enabling-withcredentials-option-angul

so please just give me a simple clue before u close this issue, it is very important to me

# the question

I have a desktop application which has to send http request to other sites and get some data and response cookies:

here is my code to send and http request with HttpClient:

```
getSite(url: string): Observable<HttpResponse<string>> {
    const types = 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8';

    const headers = new HttpHeaders()
        .set('Accept', types);

    return this._http.get(
        url,
        {
            observe: 'response',
            headers: headers,
            responseType: 'text',
            withCredentials: true
        }
    );
}
```
the problem is that there is no set-cookie header in the response.

btw: I also disabled webSecurity when the application window is creating due to CORS problem

so what is the problem?

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

Sorry for the canned response. You could try the [Angular Gitter chat](https://gitter.im/angular/angular).

**Comment by MetaiR** [comment]
@JoostK 
after I did some tests with a brand new angular 8 project (without electron or anything else), I see the problem still exist and the interesting part is when I tried my test by `XMLHttpRequest` everything was fine.

so isn't it a problem or bug in angular `HttpClient` library?

**Comment by JoostK** [comment]
I can't tell without a minimal reproduction. Perhaps sharing a HAR archive with the request/response data using both `XMLHttpRequest` and `HttpClient` would shed some light on this.

[More info on how to create a HAR](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting#h_2598b2df-ca9f-49bc-8166-054c9e5e665a)

**Comment by MetaiR** [comment]
it is very simple actually; after I sent by XMLHttpRequest, the cookies would be set in my browser but with angular httpClient they wouldn't

**Comment by JoostK** [comment]
Yes, we need something to reproduce. That means actual code that can actually run. Since a backend is involved that might get tricky, hence the suggestion to share the HAR as that should contain valuable info without needing to run anything.

**Comment by mlc-mlapis** [comment]
@MetaiR We all know that there could be hundreds of things why you have a problem (from some simple typo to more complicated situations) so the number one rule is: **Trust only the reproduction demo.** That's why the simple online demo is always expected and required for serious discussion.

**Comment by MetaiR** [comment]
there is just one problem, and it is the `CORS`.
I could reproduce these things by disabling the cors on my chrome browser, so do u now any web service or site that add headers for cors and also set some cookies?

**Comment by mlc-mlapis** [comment]
@MetaiR  But CORS is just a server-side thing. It's not related to Angular at all or any other client side. Don't mix 2 different things here together?

**Comment by mlc-mlapis** [comment]
@MetaiR Did you read for example the whole story in https://github.com/angular/angular/issues/15805?

**Comment by MetaiR** [comment]
I know about that, i know it is server side but when I send http request somewhere (withCredentials: true) and there is a `set-cookie` header I expect that I can find the cookies inside my inspect element in the application tab and I can't because httpClient will ignore them even when withCredentials is true, but the other tools like fetch Api or XMLHttpRequest don't do it and the cookies are set in browser and inside the client side,

so the problem is:

> some how httpClient ignore `set-cookie` header (and ignore its withCredentials option)

so now we clear the problem lets create a test project that u can see what happend exactly, for doing that I need to send httpRequest to somewhere and most places doesn't allow `CORS` so if u want me to reproduce this problem for u I need a web service or even a site that :

1. enabled CORS
2. return `set-cookie` in the response header

is there any question?

**Comment by mlc-mlapis** [comment]
@MetaiR ... you can do it with the Node express as server-side on http://localhost:4205 for example, when the app is loading from http://localhost:4200 because of different ports mean that CORS has to be set.

**Comment by mlc-mlapis** [comment]
@MetaiR Couldn't be the same problem as described here: https://stackoverflow.com/questions/50076352/angular-is-not-sending-the-cookie-received-in-set-cookie-even-if-withcredentials?

**Comment by MetaiR** [comment]
as the writer mentioned, he got the `set-cookie` header but in my case, there is no `set-cookie` header so I guess they're not the same but it gave me the idea of using an interceptor to go deeper
