### ISSUE TITLE
A circular dependency created by an injection token construct does not raise an error but a second service instance 

### ISSUE THREAD

**Issue by thomashilzendegen** [angular/angular#31387]
# 🐞 bug report

### Affected Package

The issue is caused by package `@angular/core`.

### Is this a regression?

 Not sure, but the behavior is also reproducible in version 7.

### Description

When ServiceA is additionally registered with a different token (with `useExisting` to use the already existing instance) and the token is injected into ServiceB which is also injected into ServiceA, a second instance of ServiceA is created for the token registration. Even using `useFactory` with `deps: [ServiceA]` doesn't help. It behaves like using `useClass` instead.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-avmhhr (see console log)

## 🔥 Exception or Error
A second instance is created for the token.

Besides the reported problem, by using `@Injectable({ providedIn: 'root' })` instead of listing the service in `providers` the value `undefined` will be put into the token registration. Maybe this could come from the same part of the code.

## 🌍  Your Environment

**Angular Version:**
Angular 8.0.3 (see stackblitz)

**Anything else relevant?**
Nope.

**Comment by kara** [comment]
@thomashilzendegen We've fixed this issue in Ivy (it throws a circular dependency error as expected):

https://stackblitz.com/edit/angular-ivy-trixke?file=src%2Fapp%2Fapp.module.ts

However, as this problem is still present in View Engine in version 9, keeping this issue open.

**Comment by rahultokase** [comment]
Does this apply to resolve and canActivate as well if we use the token there as well.

**Comment by JoostK** [comment]
Closing as resolved in Ivy.
