### ISSUE TITLE
platform-browser.d.ts error

### ISSUE THREAD

**Issue by playkang** [angular/angular#31382]
When I build, I get the following error.

ERROR in node_modules/@angular/platform-browser/platform-browser.d.ts(739,22): error TS2515: Non-abstract class 'ɵBrowserPlatformLocation' does not implement inherited abstract member 'getState' from class 'PlatformLocation'.
node_modules/@angular/platform-browser/platform-browser.d.ts(739,22): error TS2515: Non-abstract class 'ɵBrowserPlatformLocation' does not implement inherited abstract member 'hostname' from class 'PlatformLocation'.
node_modules/@angular/platform-browser/platform-browser.d.ts(739,22): error TS2515: Non-abstract class 'ɵBrowserPlatformLocation' does not implement inherited abstract member 'href' from class 'PlatformLocation'.
node_modules/@angular/platform-browser/platform-browser.d.ts(739,22): error TS2515: Non-abstract class 'ɵBrowserPlatformLocation' does not implement inherited abstract member 'port' from class 'PlatformLocation'.
node_modules/@angular/platform-browser/platform-browser.d.ts(739,22): error TS2515: Non-abstract class 'ɵBrowserPlatformLocation' does not implement inherited abstract member 'protocol' from class 'PlatformLocation'.

**Comment by santoshyadav198613** [comment]
Can you also share the Angular Version?

**Comment by playkang** [comment]
The versions are:

Angular CLI: 8.0.6
Node: 11.12.0
OS: darwin x64
Angular: 8.0.0-beta.11
... animations, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cdk                      7.3.7
@angular/cli                      8.0.6
@angular/common                   8.0.3
@angular/http                     6.1.7
@angular/material                 6.4.7
@angular/router                   8.0.3
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.5.2
typescript                        3.3.3333
webpack                           4.30.0

**Comment by santoshyadav198613** [comment]
Thanks for sharing, looks like you have not properly updated your packages, You are still using lower version of Angular Material , Typescript should be >3.4 and < 3.5 can you update your all package and do a clean install and check first.

The error which you are getting is due to experimental API, if you are using Ivy please disable it. if you are testing it with Ivy , share a small reproduction to check.

**Comment by playkang** [comment]
Thanks for the quick answer.
However, the following error appears.
What should I do in this case?

ERROR in The Angular Compiler requires TypeScript >=3.3.3333 and <3.4.0 but 3.4.5 was found instead.

**Comment by santoshyadav198613** [comment]
Also I can see the implmentation https://github.com/angular/angular/blob/8.0.3/packages/platform-browser/src/browser/location/browser_platform_location.ts so most probably it is related to the packages which are not updated properly.

**Comment by santoshyadav198613** [comment]
> Thanks for the quick answer.
> However, the following error appears.
> What should I do in this case?
> 
> ERROR in The Angular Compiler requires TypeScript >=3.3.3333 and <3.4.0 but 3.4.5 was found instead.

As mentioned please update your typescript version to 3.4.x .

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by playkang** [comment]
This error Fixed after ng update. Thank you.
