### ISSUE TITLE
Bundle Size is showing less size on build,,,but on browser it is very large

### ISSUE THREAD

**Issue by ashu8912** [angular/angular#31389]
I typed In the Command 

ng build --prod --aot --vendor-chunk --common-chunk --delete-output-path --buildOptimizer 

![Screenshot 2019-07-02 at 9 01 20 PM](https://user-images.githubusercontent.com/30126128/60526627-586aad80-9d0e-11e9-9dde-8bbb1c1dd76a.png)

to prepare my build and the bundle size is showing a very less size but on looking in browser
the bundle is still very high

![Screenshot 2019-07-02 at 9 01 56 PM](https://user-images.githubusercontent.com/30126128/60526757-8f40c380-9d0e-11e9-8e91-a9bd3a8d342a.png)
## 🌍  Your Environment

**Angular Version:**
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.2.4
@angular/cdk                      7.3.7
@angular/cli                      7.2.4
@angular/material                 7.3.7
@ngtools/webpack                  7.2.4
@schematics/angular               7.2.4
@schematics/update                0.12.4
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4

**Comment by ashu8912** [comment]
Please...(this has been a headache) help me solve this issue.....
if any info is still needed please tell,,,don't just straightaway cancel issue
plzz..

**Comment by gkalpak** [comment]
The `resources` is very different than "the size of my JS files. See [this SO question/answer][1] for more info.

In any case, this issue doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

[1]: https://stackoverflow.com/questions/56043151/what-is-the-difference-between-transferred-and-resources-in-chrome-devtools
