### ISSUE TITLE
ERROR in Cannot combine @Input decorators with query decorators

### ISSUE THREAD

**Issue by hukaixuan2017** [angular/angular#31398]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

I installed angular 8 and ran a project developed on angular 7 with the following error. I didn't indicate which line was wrong. Is this a bug?

Thank you!

![image](https://user-images.githubusercontent.com/29294119/60565900-d921bc00-9d97-11e9-885e-4d5634e6ac58.png)

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by aipirvu** [comment]
I encountered the same error message when running `build --prod` after enabling Ivy (`"enableIvy": true`) in `tsconfig.app.json` > `angularCompilerOptions`. This was the only change I made on a recently updated angular-cli project from version 7 to 8.

**Comment by hukaixuan2017** [comment]
> I encountered the same error message when running `build --prod` after enabling Ivy (`"enableIvy": true`) in `tsconfig.app.json` > `angularCompilerOptions`. This was the only change I made on a recently updated angular-cli project from version 7.1.3 to 8.1.0.

Have you solve this porblem ？

**Comment by aipirvu** [comment]
> > I encountered the same error message when running `build --prod` after enabling Ivy (`"enableIvy": true`) in `tsconfig.app.json` > `angularCompilerOptions`. This was the only change I made on a recently updated angular-cli project from version 7.1.3 to 8.1.0.
> 
> Have you solve this porblem ？

No man. I was interested only in checking out Ivy. As it is in *preview* still we are not planning to use it in production so I don't have the interest of digging into this at this moment. Sorry.

I did however ended up on [this](https://stackoverflow.com/questions/56457566/cannot-combine-input-decorators-with-query-decorators-using-ivy) stackoverflow thread but it was not applicable in our case. Most likely it is a third party library that causes the issue as suggested there.

**Comment by AndrewKushnir** [comment]
Hi,

Based on the error message, it looks like @Input() and @ContentChild decorators are used on the same field in a Component class. This is not supported in Ivy and as a possible solution, you can assign decorators to different class fields and use the value from the second field if the first one is not defined.

We've also improved the error message for these cases (that should also include the location in the code where the problem happens) in PR #31123 and the changes are available within the `8.2.0-next.0` version (and will be included into `8.2.0`). You can upgrade to that version to see more descriptive error message.

Note: `8.2.0-next.0` is the next version, so you should use it for testing purposes only and use current stable version for production builds.

Thank you.

**Comment by hukaixuan2017** [comment]
I try to install angular 7 and the project can be run。

If I use the upgrade script（ng update @angular/cli @angular/core），upgrade to angular 8, can I avoid this problem?

**Comment by aipirvu** [comment]
> I try to install angular 7 and the project can be run。
> 
> If I use the upgrade script（ng update @angular/cli @angular/core），upgrade to angular 8, can I avoid this problem?

You shouldn't have this problem if you don't enable Ivy. This is how you [enable it](https://angular.io/guide/ivy). So if you did, then remove `"enableIvy": true` or set it to `false`.

**Comment by kara** [comment]
Closing this since the PR to add the line numbers (https://github.com/angular/angular/pull/31123) has been merged into master.
