### ISSUE TITLE
10kb larger main bundle with Angular version 8.1.0

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#31404]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core I think

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.0.3

### Description

Building [this app](https://github.com/angular/angular-cli/tree/bed09493b075d56ef20224bbbb086f5f06f1bdd4/tests/legacy-cli/e2e/assets/webpack) using Angular version 8.1.0 yields a 10kb larger main bundle than with 8.0.3.

Below are the versions I tried and sizes obtained:
- 8.0.3

```
drwxr-xr-x 1 kamik 197609      0 Jul  3 13:12 .
drwxr-xr-x 1 kamik 197609      0 Jul  3 13:30 ..
-rw-r--r-- 1 kamik 197609   1011 Jul  3 13:30 0.app.main.js
-rw-r--r-- 1 kamik 197609   1118 Jul  3 13:09 1.app.main.js
-rw-r--r-- 1 kamik 197609   1117 Jul  3 13:30 2.app.main.js
-rw-r--r-- 1 kamik 197609   1168 Jul  3 13:30 3.app.main.js
-rw-r--r-- 1 kamik 197609 479591 Jul  3 13:30 app.main.js
```

- 8.1.0-beta.0
```
drwxr-xr-x 1 kamik 197609      0 Jul  3 13:12 .
drwxr-xr-x 1 kamik 197609      0 Jul  3 13:35 ..
-rw-r--r-- 1 kamik 197609   1011 Jul  3 13:36 0.app.main.js
-rw-r--r-- 1 kamik 197609   1118 Jul  3 13:09 1.app.main.js
-rw-r--r-- 1 kamik 197609   1117 Jul  3 13:36 2.app.main.js
-rw-r--r-- 1 kamik 197609   1168 Jul  3 13:36 3.app.main.js
-rw-r--r-- 1 kamik 197609 489664 Jul  3 13:36 app.main.js
```

- 8.1.0-next.1
```
drwxr-xr-x 1 kamik 197609      0 Jul  3 13:12 .
drwxr-xr-x 1 kamik 197609      0 Jul  3 13:37 ..
-rw-r--r-- 1 kamik 197609   1011 Jul  3 13:37 0.app.main.js
-rw-r--r-- 1 kamik 197609   1118 Jul  3 13:09 1.app.main.js
-rw-r--r-- 1 kamik 197609   1117 Jul  3 13:37 2.app.main.js
-rw-r--r-- 1 kamik 197609   1168 Jul  3 13:37 3.app.main.js
-rw-r--r-- 1 kamik 197609 492474 Jul  3 13:37 app.main.js
```

- 8.1.0
```
drwxr-xr-x 1 kamik 197609      0 Jul  3 13:12 .
drwxr-xr-x 1 kamik 197609      0 Jul  3 13:39 ..
-rw-r--r-- 1 kamik 197609   1011 Jul  3 13:39 0.app.main.js
-rw-r--r-- 1 kamik 197609   1118 Jul  3 13:09 1.app.main.js
-rw-r--r-- 1 kamik 197609   1117 Jul  3 13:39 2.app.main.js
-rw-r--r-- 1 kamik 197609   1168 Jul  3 13:39 3.app.main.js
-rw-r--r-- 1 kamik 197609 492876 Jul  3 13:39 app.main.js
```

- 8.2.0-next.0

```
drwxr-xr-x 1 kamik 197609      0 Jul  3 14:05 .
drwxr-xr-x 1 kamik 197609      0 Jul  3 14:05 ..
-rw-r--r-- 1 kamik 197609   1011 Jul  3 14:05 0.app.main.js
-rw-r--r-- 1 kamik 197609   1117 Jul  3 14:05 2.app.main.js
-rw-r--r-- 1 kamik 197609   1168 Jul  3 14:05 3.app.main.js
-rw-r--r-- 1 kamik 197609 493072 Jul  3 14:05 app.main.js
```

## 🔬 Minimal Reproduction
Check out this folder at the specific sha in the link https://github.com/angular/angular-cli/tree/bed09493b075d56ef20224bbbb086f5f06f1bdd4/tests/legacy-cli/e2e/assets/webpack

Run `npm i && rm -rf dist/ && ./node_modules/.bin/webpack-cli && ls -la dist/` to install, build and see size. Vary the Angular version 

## 🔥 Exception or Error
No error, but larger size.

## 🌍  Your Environment

**Angular Version:**
Angular version 8.1.0
</code></pre>

**Anything else relevant?**
I wondered if the size increase might have gone unnoticed because lazy chunks in webpack [prevent some optimizations](https://docs.google.com/document/d/1aOgWymYSFzcOjS2uHx-CsUW1jmFnTROgxymndXCXPsI/edit#heading=h.2zllxqviadrm). I tested if it also happens without lazy chunks, and I can still see a similar size increase.

- 8.0.3

```
drwxr-xr-x 1 kamik 197609      0 Jul  3 14:03 .
drwxr-xr-x 1 kamik 197609      0 Jul  3 14:03 ..
-rw-r--r-- 1 kamik 197609 475760 Jul  3 14:03 app.main.js
```

- 8.1.0
```
drwxr-xr-x 1 kamik 197609      0 Jul  3 14:02 .
drwxr-xr-x 1 kamik 197609      0 Jul  3 14:02 ..
-rw-r--r-- 1 kamik 197609 489046 Jul  3 14:02 app.main.js
```

**Comment by filipesilva** [comment]
Worth mentioning that the repro doesn't use Angular CLI. It's a simple webpack config with very little in it. Notably there is no Build Optimizer.

**Comment by gkalpak** [comment]
This could be related the the known issue of webpack/terser not being able to tree-shake code imported between modules (which can, for example, result in Ivy-specific code being retained in ViewEngine bundles, etc.). E.g. there was a ~7KB size increase between 8.0.0-rc.2 and 8.1.0-next.1 on aio because of that: https://github.com/angular/angular/pull/30935#discussion_r291841072

**Comment by lppedd** [comment]
Just to let you know, after switching from 7.2.15 to 8.1, I noticed an increase of about 150kb for the total initial bundle size.
