### ISSUE TITLE
Http failure response for http://192.168.252.10:10204/login: 0 Unknown Error on IOS browser

### ISSUE THREAD

**Issue by DeltaFox0018** [angular/angular#31409]
I'm creating a WebApp with anngular that needs to run on windows, android and ios, I created a login form that contacts the server and receives a JSON with code 200 if the login is successful or 400 if the login isn't successful,trying on windows and android works perfectly it doesn't work on ios 12, it gives me an error

> Http failure response for http://192.168.252.10:10204/login: 0 Unknows Error

The tests done on ios have been done both with chrome, safare and firefox and give the same error, can anyone help me?

On the header that comes from the server there are these fields, are they missing?

    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, PATCH, POST, DELETE, OPTIONS');
    res.header('Access-Control-Allow-Headers', 'Origin, Content-Type, Accept, Authorization, X-Request-With');
    res.header('Access-Control-Max-Age', '86400');
    res.header('Access-Control-Expose-Headers','Content-Length, X-JSON');
    res.header('Content-Type','application/json');

**Comment by alxhub** [comment]
This is likely not an issue with the Angular HTTP libraries (which know nothing about CORS) but with your server's configuration / the iOS browser.

**Comment by molysama** [comment]
The CORS work of my console XHR, it means that the server Settings take effect.
But it failed at HttpClient.
The amazing thing is that CORS work after I changed param to HttpParams!
```
// blocked
this.http.post(url, { 
  username: username
}).pipe(
```
```
// pass
let body = new HttpParams()
body.set('username', username)
this.http.post(url, body)
```
