### ISSUE TITLE
requiredTrue doesn't set a control to be `INVALID` when its value is not `true`

### ISSUE THREAD

**Issue by gultyaev** [angular/angular#31400]
**See comment thread**

# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
"@angular/forms": "^8.0.2"

### Is this a regression?
Not sure

### Description

I change validation rules on fly by setting `Validators.requriedTrue` however the control which has whatever value but `true` is still valid and my form is ready to submit (meanwhile it shouldn't).

I use `this.formGroup.get(...).setValidators(Validators.requiredTrue)`. The validator is set, but form is still valid although the value of the control is `null` or `false`

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-wrokpb
Click the button to toggle the `requiredTrue` and see in console logged FormGroup object.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.4
Node: 12.5.0
OS: linux x64
Angular: 8.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.4
@angular-devkit/build-angular      0.800.4
@angular-devkit/build-ng-packagr   0.800.4
@angular-devkit/build-optimizer    0.800.4
@angular-devkit/build-webpack      0.800.4
@angular-devkit/core               8.0.4
@angular-devkit/schematics         8.0.4
@angular/cdk                       8.0.1
@angular/cli                       8.0.4
@angular/material                  8.0.1
@angular/material-moment-adapter   8.0.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.4
@schematics/angular                8.0.4
@schematics/update                 0.800.4
ng-packagr                         5.3.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0
</code></pre>

**Anything else relevant?**

**Comment by ElisePatrikainen** [comment]
You need to call the updateValueAndValidity() method after adding or removing the validator. 
Here is a fonctionnal demo : 
https://stackblitz.com/edit/angular-rgfmjd?embed=1&file=src/app/app.component.ts

For information, here is a very useful article on this subject :
https://netbasal.com/three-ways-to-dynamically-alter-your-form-validation-in-angular-e5fd15f1e946

**Comment by gultyaev** [comment]
Well then why isn't it described in docs. And why isn't this applied automatically with an optional flag to not to invoke "updateValueAndValidity" like in setValue?

**Comment by jasonaden** [comment]
You're correct, this should be noted in the docs for `setValidators`. I'm moving this to a docs issue.

**Comment by jbogarthyde** [comment]
Resolved by doc addition to `setValidity()` method
