### ISSUE TITLE
Reactive forms: if control has two parents, only emits value to last

### ISSUE THREAD

**Issue by Serginho** [angular/angular#31406]
# 🐞 bug report

### Affected Package
@angular/forms

### Is this a regression?
No

### Description

Angular forms do not have support for adding a control to two parents.

## 🔬 Minimal Reproduction

```typescript
const parent1 = new FormGroup({});
const parent2 = new FormGroup({});
const control = new FormControl();
parent1.addControl('key1', control);
parent2.addControl('key2', control);
parent1.valueChanges.subscribe((data)=>console.log('parent1 change'));
parent2.valueChanges.subscribe((data)=>console.log('parent2 change'));
control.setValue('value');
// Log: parent1 change
```

## 🌍  Your Environment

**Angular Version:**
Angular 7.2.0

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
