### ISSUE TITLE
getCurrencySymbol('USD', 'narrow') getCurrencySymbol('USD', 'wide') is same?

### ISSUE THREAD

**Issue by billpeace** [angular/angular#31402]
https://angular.io/api/common/getCurrencySymbol#description
Description
For example, for the default en-US locale, the code USD can be represented by the narrow symbol $ or the wide symbol US$.

### Description

 A clear and concise description of the problem...
getCurrencySymbol('USD', 'narrow')  out: $
getCurrencySymbol('USD', 'wide')  out: $

**Comment by trotyl** [comment]
They're same according to [CLDR data](https://github.com/unicode-cldr/cldr-numbers-full/blob/23c17f05023c33c1a25a4527f1f76fe756d231f8/main/en/currencies.json#L1621-L1622).

Please reports to http://cldr.unicode.org/index/bug-reports if you think there is some issue.

**Comment by AndrewKushnir** [comment]
@billpeace as @trotyl mentioned, this issue is not directly related to Angular's code/implementation, so I'm closing this ticket. Thank you.
