### ISSUE TITLE
Cannot find external module 'angular2/http'

### ISSUE THREAD

**Issue by VirtualOverride** [angular/angular#3141]
I dont know where to submit this, i used the latest angular.d.ts v2.0.0-alpha.31 and angular.dev.js v31. when i execute the tsc or compile my typescript code it says "Cannot find external module 'angular2/http'"

**Comment by gdi2290** [comment]
this is due to missing type definitions (TypeScript thing)

**Comment by VirtualOverride** [comment]
@gdi2290 
so any suggestion what version of .d.ts should i use? in order the http module will work? by the way i use TS 1.5 beta.

**Comment by gdi2290** [comment]
yeah, just include this somewhere (tsconfig file) then TypeScript will figure it out.
```
declare module "angular2/http" {
  class Http {
    _backend: any;
    _defaultOptions: any;
    constructor(_backend?: any, _defaultOptions?: any);
    request(url: string, options?: any): any;
    get(url: string, options?: any): any;
    post(url: string, body: any, options?: any): any;
    put(url: string, body: any, options?: any): any;
    delete(url: string, options?: any): any;
    patch(url: string, body: any, options?: any): any;
    head(url: string, options?: any): any;
  }
  class MockBackend {
    constructor(req: any)
  }
  class Headers {
    constructor(config: any)
  }
  class XHRBackend {}
  class BaseRequestOptions {}
  var httpInjectables: Array<any>;
}

```
If you need a starter repo you can check out this one [angular2-webpack-starter](https://github.com/angular-class/angular2-webpack-starter) (feedback welcome). If this works for you then you can close the issue

**Comment by VirtualOverride** [comment]
@gdi2290 many thanks for this. this what i did. i create angular2.http.d.ts on the typings folder then i add this as reference to tsd.d.ts it works on me. and i will try to look at your webpack starter. again thanks.
