### ISSUE TITLE
Extension: language-service not working anymore

### ISSUE THREAD

**Issue by Ploppy3** [angular/angular#31417]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/language-service

### Is this a regression?

 Yes, working fine on 8.0.3, broken since 8.1.0

### Description

 vs code language-service extension does not seem to work:
working fine on **8.0.3** (state: **working** properly)
starting with version **8.1.0** (state: **broken**)
also tested on **8.2.0-next** (state: **broken**)

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

No error thrown
</code></pre>

**Anything else relevant?**

**Comment by alexzuza** [comment]
Duplicate of https://github.com/angular/vscode-ng-language-service/issues/343
There is a fix here https://github.com/angular/vscode-ng-language-service/pull/344

**Comment by Ploppy3** [comment]
Seems to be patched in 8.2.0-next.2
