### ISSUE TITLE
Angular 6 Website Not Opening on Iphone X , Iphone X Max , Iphone XS Max 

### ISSUE THREAD

**Issue by muzzammilhussain** [angular/angular#31427]
# 🐞 bug report

### Affected Package
I cannot point out which Package has an issue as I am quite blank yet. The basic issue is my angular 6 website is not opening on  Iphone X , Iphone X Max , Iphone XS Max . 

Safari and Chrome both not working
website address is backadmin.thetowertech.com if anyone can find log errors it will be great help as I cannot find them as well
### Is this a regression?

No, my angular 5 app works fine

### Description

Website Login Page shows and then chrome show aww snap

## 🔬 Minimal Reproduction
Safari and Chrome both not working
website address is backadmin.thetowertech.com if anyone can find log errors it will be great help as I cannot find them as well

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>6<code>

</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
