### ISSUE TITLE
Angular 6 and webpack implemented giving Warning on npm start 

### ISSUE THREAD

**Issue by kunjarani** [angular/angular#31428]
CURRENT BEHAVIOUR

_**WARNING in ./node_modules/@angular/core/fesm5/core.js 4982:15-36
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/@angular/core/fesm5/core.js 4994:15-102
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/@angular/core/fesm5/core.js 4982:15-36
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/

WARNING in ./node_modules/@angular/core/fesm5/core.js 4994:15-102
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
i ?wdm?: Compiled with warnings.**_

POSSIBLE SOLUTION

No peer dependency warnings/errors from npm. Compiled successfully

STEPS TO REPRODUCE

cloned the code.
npm install
npm start

Hi Folks,

I am working on a hybrid application consists of Angularjs and Angular6 with webpack code. After cloning, i tried getting node modules using npm install. I got peer dependency of angular/core and manually installed these. When I am trying to do npm start , the cmd is giving following warnings and the angular6 code is not executing. giving errors in the console.

Please give a solution to remove these warnings

**Comment by jasonaden** [comment]
In general, NPM warnings aren't something that needs to be considered. However, we are looking at reducing these in some upcoming versions. I think the best thing would be to update to a more recent version of Angular and see how that changes what you're seeing.

**Comment by andrius-pra** [comment]
You need to add additional [rule](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts#L397-L402) to webpack config.

**Comment by doricohen4** [comment]
any updates ? i am getting same thing with hybrid with angularjs and angular 

i use angular 8 and wepack 4.39.1
