### ISSUE TITLE
Router: Current status of sibling outlet support

### ISSUE THREAD

**Issue by DavidGangel** [angular/angular#3143]
Hi,

I would like to get an update about support of sibling outlet in the new router for Angular2.
I've read this article (~1 month old):
http://blog.thoughtram.io/angular/2015/06/16/routing-in-angular-2.html
And mentioned:
Attention: 
The components property has been removed as of #2329 but the feature will be reintroduced with a different mechanism.

The linked issue is closed by splitting up the issues under seperate tickets.

However I don't realy see where this part of feature went or what is the status of supporting it.

Thank you.

**Comment by mhevery** [comment]
I am sorry but this is not a place to file update requests. We are currently in alpha and so there are too many things in flux.

**Comment by DavidGangel** [comment]
Hi,

Ok I understand this, but if there is no ticket available for this feature then this issue is valid as it points out an important missing feature that was also planed to be get implemented.
