### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by SuhasParameshwara** [angular/angular#31430]
Hi team,

In our project, we use Angular 7 with of course Http Client. And some times, if there are any HttpHeaders sent as null, we are facing with the above error. I know that we shouldn't send headers as null but I think this condition can be handled in this respective file,

https://github.com/angular/angular/blob/master/packages/common/http/src/headers.ts 

https://github.com/angular/angular/blob/1d3e22766a978bc8bd6e3ef29cec5cdb44e04278/packages/common/http/src/headers.ts#L220

let value = update.value !;
        if (typeof value === 'string') {
          value = [value];
        }
        if (!value || value.length === 0) {
          return;
        }

**Comment by JoostK** [comment]
Both https://github.com/angular/angular/blob/1d3e22766a978bc8bd6e3ef29cec5cdb44e04278/packages/common/http/src/headers.ts#L147 and https://github.com/angular/angular/blob/1d3e22766a978bc8bd6e3ef29cec5cdb44e04278/packages/common/http/src/headers.ts#L159 are typed to require a value of type `string|string[]`, so passing `null` is not supported. Therefore, your application code has to ensure not to pass `null` header values.
