### ISSUE TITLE
If-else statement problem

### ISSUE THREAD

**Issue by altreze** [angular/angular#31433]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/8.1.0

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 7.x

### Description

 A clear and concise description of the problem...
In the if-else statement, it seems #loading is not being processed while running `ng build --prod`, any tips is welcome

<pre><code>
app-loading-spinner *ngIf="!(loaded$ | async); else loading"> /app-loading-spinner

ng-container *ngFor="let attribute of (attributes$ | async)" #loading
  app-attribute [attribute]="attribute"> /app-attribute
/ng-container>
</code></pre>

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>
ERROR in ../components/attributes/attributes.component.html(1,22): : Property 'loading' does not exist on type 'AttributesComponent'.
../components/products/products.component.html(1,22): : Property 'loading' does not exist on type 'ProductsComponent'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.1.0
Node: 12.6.0
OS: darwin x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0
@ngtools/webpack                  8.1.0
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Anything else relevant?**

**Comment by dblVs** [comment]
It's because your container is not wrapped in an ng-template. 

If you need further help you could visit gitter where there are loads of people who would help you. 

Once you fix your usage would you be able to close this?

**Comment by altreze** [comment]
Nice catch.

Did work as-is with `v7.x`, I am closing this issue.
