### ISSUE TITLE
Router reconstruct parent component when children change in angular 7

### ISSUE THREAD

**Issue by mfarhani** [angular/angular#31439]
When children components changing in layout component, layout component reconstruct and expansion panel collapse, app logo blinking, ... . I use a router-outlet in app.component.html for root components such as main-layout-component and use another router-outlet in root components for children component. But when switch between children component, main-layout-component constructor called. Is there any way to handle this issue?

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mfarhani** [comment]
> Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.
> 
> If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Nobody answer me in stackoverflow. So where can i ask my problem? I do everything right then angular router has bug
