### ISSUE TITLE
Is it possible to Reuse a piece of angular code / Component  as a Angular Library as well as Angular Element 

### ISSUE THREAD

**Issue by mohan-mu** [angular/angular#31449]
Or Any way around to reuse code both as Angular Library & angular Element

**Comment by mohan-mu** [comment]
Idea here is Single piece  of Code should serve both as Angular Library and Angular Element

**Comment by santoshyadav198613** [comment]
Check if this article helps you https://blog.angularindepth.com/using-angular-elements-with-ngrx-bc655e1eb212

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular` or reach out via [our gitter channel](https://gitter.im/angular/angular).

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
