### ISSUE TITLE
Add support for manipulating meta tags inside the head element

### ISSUE THREAD

**Issue by DavidGangel** [angular/angular#3144]
Hi,

I think it would be quite useful if meta tags could be manipulable through Angular app.
I mean there are some meta tags like:
Meta Description Attribute or Meta Robots Attribute
that are related to the current sub-page and are not global tags for the whole "domain" and so to the global app. It means it's not enough to set them only once during the page load.

Would be nice if these tag informations could be loaded from REST API as one example of source of the data.

**Comment by gdi2290** [comment]
Can you elaborate a bit more about your use case so we can understand your requirements? For example, "My analytics sdk doesn't have a web client and it reads the meta tags" or "I care about SEO and I want my app to be visible to search engine crawlers or Facebook previews". From my understanding of Meta tags, they're only useful for web crawlers (google search and facebook/twitter preview) which means Meta tags only matter on the server when serving the initial web page. You're able to run your Angular app on the server which means there can be a helper service, let's call it `Server`, that allows you to configure any concern related to server settings. Settings such as `robot.txt`, document title, and of course the meta tags. There are a few ways I can imagine this working out.

1. Include a decorator for each component that will allow the user to configure server settings
(for now let's make it extremely simple)
```typescript
@Component()
@View()
@RouteConfig()
@ServerConfig({
  'title': 'My home page'
  'robot.txt': `
User-agent: Twitterbot
Disallow:
 
User-agent: *
Disallow: /
  `,
  metatags: `
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@nytimesbits" />
<meta name="twitter:creator" content="@nickbilton" />
<meta property="og:url" content="http://bits.blogs.nytimes.com/2011/12/08/a-twitter-for-my-sister/" />
<meta property="og:title" content="A Twitter for My Sister" />
<meta property="og:description" content="In the early days, Twitter grew so quickly that it was almost impossible to add new features because engineers spent their time trying to keep the rocket ship from stalling." />
<meta property="og:image" content="http://graphics8.nytimes.com/images/2011/12/08/technology/bits-newtwitter/bits-newtwitter-tmagArticle.jpg" />
  `
})
class App {
  
}
```


2. Include it in the `@RouteConfig` as a data property simular to how you would handle auth


```typescript

var robotTxt = `
  User-agent: Twitterbot
  Disallow:
   
  User-agent: *
  Disallow: /
`;

var metatags = `
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@nytimesbits" />
  <meta name="twitter:creator" content="@nickbilton" />
  <meta property="og:url" content="http://bits.blogs.nytimes.com/2011/12/08/a-twitter-for-my-sister/" />
  <meta property="og:title" content="A Twitter for My Sister" />
  <meta property="og:description" content="In the early days, Twitter grew so quickly that it was almost impossible to add new features because engineers spent their time trying to keep the rocket ship from stalling." />
  <meta property="og:image" content="http://graphics8.nytimes.com/images/2011/12/08/technology/bits-newtwitter/bits-newtwitter-tmagArticle.jpg" />
`;

@Component()
@View()
@RouteConfig([
  { path: '/', component: Home, data: { metatags, robotTxt} }
])
class App {
  
}
```

3. Configure via helper service


```typescript

var robotTxt = `
  User-agent: Twitterbot
  Disallow:
   
  User-agent: *
  Disallow: /
`;

var metatags = `
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@nytimesbits" />
  <meta name="twitter:creator" content="@nickbilton" />
  <meta property="og:url" content="http://bits.blogs.nytimes.com/2011/12/08/a-twitter-for-my-sister/" />
  <meta property="og:title" content="A Twitter for My Sister" />
  <meta property="og:description" content="In the early days, Twitter grew so quickly that it was almost impossible to add new features because engineers spent their time trying to keep the rocket ship from stalling." />
  <meta property="og:image" content="http://graphics8.nytimes.com/images/2011/12/08/technology/bits-newtwitter/bits-newtwitter-tmagArticle.jpg" />
`;

@Component()
@View()
@RouteConfig()
class App {
  constructor(server: Server) {
    server.set('title', 'My home page');
    server.set('robot.txt', robotTxt);
    server.set('metatags', metatags);
  }
}
```

Going back to the original description if metatags are only meaningful to web crawlers then you can increase the initial load just of your index.html, a little bit, by not including them for your users. We can use also directives to manage these meta tags for each service. Doing so could be either `noop` via bindings, server config, or remove it during the build step

**Comment by intellix** [comment]
Titles aren't just useful for crawlers. It changes the name of the tab, which is useful to have change as you traverse an app: `Homepage - mywebsite.com`

**Comment by pkozlowski-opensource** [comment]
@intellix changing title is already supported with the Title service.

**Comment by mhevery** [comment]
crawlers read meta-tags before angular executes, and for this reason why you are asking for is not feasible.
