### ISSUE TITLE
Dynamic form example with type error

### ISSUE THREAD

**Issue by webcat12345** [angular/angular#31446]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...
https://angular.io/guide/dynamic-form

Dynamic form example - `dynamic-form-question` component, has input value - `questions` and it's `type` field is not there - `QuestionBase<any>`. 
From HTML it's rendering 

```
    <input *ngSwitchCase="'textbox'" [formControlName]="question.key"
            [id]="question.key" [type]="question.type">
```
But `type` property is - QuestionTextBox class specific and it throws type check error on IDE.

![image](https://user-images.githubusercontent.com/19761422/60783886-82064900-a101-11e9-9191-46f5467ea3af.png)

## 🔬 Minimal Reproduction

Just follow example code from angular.io

### What's the affected URL?**
https://angular.io/guide/dynamic-form#question-form-components

### Reproduction Steps**

- ` @Input() questions: QuestionBase<any>[] = [];`
- `<input *ngSwitchCase="'textbox'" [formControlName]="question.key"
            [id]="question.key" [type]="question.type">`

### Expected vs Actual Behavior**

`type` rendering on HTML should pass without any error

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/19761422/60784001-fb9e3700-a101-11e9-82e5-4426c92af49f.png)

IDE: Webstorm 2019.1 - Angular supported

## 🌍  Your Environment

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.0
Node: 12.2.0
OS: linux x64
Angular: 8.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@angular/flex-layout              8.0.0-beta.26
@ngtools/webpack                  8.0.0
@schematics/angular               8.0.0
@schematics/update                0.800.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

```

### Browser info

No browser specific

**Comment by santoshyadav198613** [comment]
Hi @webcat12345 ,
Good catch, there are several issues with the example we are using any and this is where the issue is. for the textbox, we do have a type but as the model type is any we are getting the error 

https://angular.io/guide/dynamic-form#question-model

Let me revisit the example, and try to write in a better way.
