### ISSUE TITLE
Done callback for set animation state action.

### ISSUE THREAD

**Issue by MarenkovIgor** [angular/angular#31440]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/animations

### Description
There is @animationTrigger.done callback. This callback fires on transition done.
However animation trigger actions can include set style action ( like state('true', style(...)) ) in addition to transition(s) action(s). There is not done callback for animation trigger set state.
It can be pain in some cases.
For example, check https://stackblitz.com/edit/angular-state-apply-callback.
Click "show" button fire "menuShrink" animation trigger in ContentComponent. After menuShrink.done callback TestChild injects in DOM and show self width in pixels.
Success result looks like:
![image](https://user-images.githubusercontent.com/13851068/60754579-4ee28d80-a00d-11e9-8998-0f93cdc2483b.png)

Click on "enable parent animation", then click "show" once again.
You will see wrong result:
![image](https://user-images.githubusercontent.com/13851068/60754599-8f420b80-a00d-11e9-91d6-6d7a39097b1d.png)
Reason of wrong result is fact that parent animation blocks child animation and  @menuShrink.done callback fires before set animation style action.

### The solution I'd like
Please implement callback that fires atfter set animation state action.
It can look like: <component (@trigger.state.done)="onSetState()"

### Alternatives I've considered
 Have you considered any alternative solutions or workarounds?
I have to use workaround now:
```
<component (@trigger.done)="triggerDone($event)">

...

triggerDone($event) {
  setImmediate(() => { //wait set animation state action
    this.showContentChild = $event.toState;
  })
}
```

Another alternative is direct use of AnimationFactory instead of animation triggers mechanism.

**Comment by dario-piotrowicz** [comment]
Hi @MarenkovIgor, I really like your idea and I had also thought of something like this, but what we need to keep in mind is that the callbacks are relative to the trigger themselves not the transitions in them, they are of a rather simple semantic

it would indeed be nice to have finer grade callbacks but for the state and what not, but what I believe we need to keep in mind is that if you were to introduce other callbacks, you could not introduce them only for what you need at the moment but everything should generically have a callback, so I mean that `state`s should have a callback, but also `transition`s, `group`s, `animate`s, etc... and you would also need to keep in mind that you can have like multiple instances of each in the same trigger (for example you can have a trigger with 2 states, 3 transitions and inside of each transitions there are various other instructions)

So I think this would become very complex and very easy to get out of hand and especially be overwhelming for the users (independently on the complexity of the implementation)

I think that the animation callbacks were not just designed for such usages and I am not sure I can see a clear/simple way that could work

what are your thoughts? do you agree? or do you have some suggestions on how something like this could potentially work? :slightly_smiling_face:

**Comment by dario-piotrowicz** [comment]
@MarenkovIgor there is also a different way to support this and it's as mentioned here: https://github.com/angular/angular/issues/14008#issuecomment-347698646 using a different approach to callbacks, I think that would also work in your case right? :slightly_smiling_face:

**Comment by dylhunn** [comment]
We are unlikely to implement this, absent a stronger signal of more community interest.
