### ISSUE TITLE
Mark deprecated API properties with strike-out font

### ISSUE THREAD

**Issue by jbogarthyde** [angular/angular#31455]
# 📚 Docs or angular.io bug report

### Description

The API docs show many deprecated elements with strike-out font. Within classes and interfaces, deprecated methods are correctly struck out, but deprecated *properties* are not.
## 🔬 Minimal Reproduction

See `https://angular.io/api/router/NavigationExtras#preserveQueryParams` (deprecated in favor of `queryParamsHandling` since v4.

### What's the affected URL?**
`https://angular.io/api/router/NavigationExtras#preserveQueryParams` 
(might be more)

### Expected vs Actual Behavior**
The deprecated property should appear in strike-out font.

**Comment by ajitsinghkaler** [comment]
@petebacondarwin if you can guide me through the way docs are designed I can do this

**Comment by petebacondarwin** [comment]
This is a good place to start looking https://github.com/angular/angular/blob/382d3ed1d24b0e0c2da37044f4be4da70940d94f/aio/tools/transforms/templates/api/lib/memberHelpers.html#L13-L23

You would want to do something like:

```shell
git clone https://github.com/angular/angular
cd angular
yarn
cd aio
yarn
yarn setup
```

which will get AIO in a state to start working on it.

You can now make changes to the dgeni configuration in `aio/tools/transforms` and then run


```shell
yarn docs-only
yarn start
```

to check out what changed

**Comment by ajitsinghkaler** [comment]
@petebacondarwin where are these members defined in the above file

**Comment by ajitsinghkaler** [comment]
@petebacondarwin can you please give me an example about what I've to do

**Comment by petebacondarwin** [comment]
Hi @ajitsinghkaler - sorry for the delay in responding. I'll give you some more guidance today.

**Comment by petebacondarwin** [comment]
These `member` objects are generated by other parts of the dgeni system (primarily by parsing the TS code and JSDOC comments - but also modified by other dgeni processors).

The good news is that any `member` that is marked as deprecated with have a property on them: `member.deprecated`. You can then use this in the templates to render them appropriately.

For example:

```
{%- macro renderMembers(doc) -%}
  {%- for member in doc.staticProperties %}{% if not member.internal %}
  <a class="code-anchor{% if member.deprecated %} deprecated-api-item{% endif %}" href="{$ doc.path $}#{$ member.anchor | urlencode $}">{$ renderMemberSyntax(member, 1) $}</a>{% endif %}{% endfor -%}
  {% for member in doc.staticMethods %}{% if not member.internal %}
  <a class="code-anchor{% if member.deprecated %} deprecated-api-item{% endif %}" href="{$ doc.path $}#{$ member.anchor | urlencode $}">{$ renderMemberSyntax(member, 1) $}</a>{% endif %}{% endfor -%}
  {% if doc.constructorDoc and not doc.constructorDoc.internal %}
  <a class="code-anchor{% if member.deprecated %} deprecated-api-item{% endif %}" href="{$ doc.path $}#{$ doc.constructorDoc.anchor | urlencode $}">{$ renderMemberSyntax(doc.constructorDoc, 1) $}</a>{% endif -%}
  {% for member in doc.properties %}{% if not member.internal %}
  <a class="code-anchor{% if member.deprecated %} deprecated-api-item{% endif %}" href="{$ doc.path $}#{$ member.anchor | urlencode $}">{$ renderMemberSyntax(member, 1) $}</a>{% endif %}{% endfor -%}
  {% for member in doc.methods %}{% if not member.internal %}
  <a class="code-anchor{% if member.deprecated %} deprecated-api-item{% endif %}" href="{$ doc.path $}#{$ member.anchor | urlencode $}">{$ renderMemberSyntax(member, 1) $}</a>{% endif %}{% endfor -%}

  {%- for ancestor in doc.extendsClauses %}{% if ancestor.doc %}

  // inherited from <a class="code-anchor" href="{$ ancestor.doc.path $}">{$ ancestor.doc.id $}</a>{$ renderMembers(ancestor.doc) $}{% endif %}{% endfor -%}
{%- endmacro -%}
```

Note here that I have added `{% if member.deprecated %} deprecated-api-item{% endif %}` to cause the `deprecated-api-item` CSS class to be added to any of the members that have this `member.deprecated` property.  This will fix the "overview" section:

![Screenshot 2019-11-27 at 08 41 57](https://user-images.githubusercontent.com/15655/69707513-d1b9d100-10f1-11ea-97aa-af1bf7ac0ce4.png)

But you would need to look further through the templates to fix other areas where member get rendered, such as 

https://github.com/angular/angular/blob/382d3ed1d24b0e0c2da37044f4be4da70940d94f/aio/tools/transforms/templates/api/lib/memberHelpers.html#L178-L188

and

https://github.com/angular/angular/blob/382d3ed1d24b0e0c2da37044f4be4da70940d94f/aio/tools/transforms/templates/api/lib/memberHelpers.html#L191-L230

**Comment by jbogarthyde** [comment]
@petebacondarwin The Deprecated filter doesn't work with the Package type.
https://next.angular.io/api?status=deprecated&type=package

**Comment by petebacondarwin** [comment]
@jbogarthyde - yes this was intentionally done in https://github.com/angular/angular/commit/234661b3d619f428007bbed4631474a5a50191d3

See https://github.com/angular/angular/issues/25708

We may want to revisit this and work out some way of identifying whole packages that are deprecated, which I don't think we can currently do.
