### ISSUE TITLE
*ngIf ; else breaks when switching between templates with ngTemplateOutlet and ngComponentOutlet directives

### ISSUE THREAD

**Issue by npafitis** [angular/angular#31452]
# 🐞 bug report

### Affected Package
This issue seems to be caused by @angular/common, and more concretely ngTemplateOutlet and ngComponentOutlet directives.

### Description

Having an *ngIf that switches through two templates depending on the type of an object, one that uses *ngTemplateOutlet and one that uses *ngComponentOutlet where they get as input the same object, causes an error.

Thing is, when the object is a component, everything works fine, if the type is TemplateRef, it still looks for it in the entryComponents.

### Expected Behaviour
Since the ng-template element with the ngComponentOutlet directive is not used in the case that the object is a TemplateRef, then it shouldn't look for an entry in entryComponents.

## 🔬 Minimal Reproduction
Reproduction in [stackblitz](https://stackblitz.com/edit/angular-6s8yuf)

## 🔥 Exception or Error
<pre><code>
ERROR Error: No component factory found for [object Object]. Did you add it to @NgModule.entryComponents?
    at noComponentFactoryError (core.js:19467)
    at CodegenComponentFactoryResolver.resolveComponentFactory (core.js:19518)
    at CodegenComponentFactoryResolver.resolveComponentFactory (core.js:19515)
    at CodegenComponentFactoryResolver.resolveComponentFactory (core.js:19515)
    at NgComponentOutlet.ngOnChanges (common.js:4230)
    at checkAndUpdateDirectiveInline (core.js:24499)
    at checkAndUpdateNodeInline (core.js:35163)
    at checkAndUpdateNode (core.js:35102)
    at debugCheckAndUpdateNode (core.js:36124)
    at debugCheckDirectivesFn (core.js:36067)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.6
Node: 10.15.3
OS: win32 x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.6
@angular-devkit/build-angular      0.800.6
@angular-devkit/build-ng-packagr   0.800.6
@angular-devkit/build-optimizer    0.800.6
@angular-devkit/build-webpack      0.800.6
@angular-devkit/core               8.0.6
@angular-devkit/schematics         8.0.6
@angular/cdk                       8.0.1
@angular/cli                       8.0.6
@angular/flex-layout               8.0.0-beta.26
@angular/material                  8.0.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.6
@schematics/angular                8.0.6
@schematics/update                 0.800.6
ng-packagr                         5.3.0
rxjs                               6.4.0
typescript                         3.4.5
webpack                            4.30.0
</code></pre>

**Comment by alexzuza** [comment]
Hey,
In your example ng-template element with the ngComponentOutlet directive is actually used.

Here's an example when it's not used:

```
<ng-template #componentContainer>
  <ng-template [ngComponentOutlet]="cellTemplate"></ng-template>
</ng-template>
```

**Comment by npafitis** [comment]
> Hey,
> In your example ng-template element with the ngComponentOutlet directive is actually used.
> 
> Here's an example when it's not used:
> 
> ```
> <ng-template #componentContainer>
>   <ng-template [ngComponentOutlet]="cellTemplate"></ng-template>
> </ng-template>
> ```
> 
> https://stackblitz.com/edit/angular-dtvnst?file=src%2Fapp%2Fapp.component.html

Thanks alot! It worked perfectly fine with your fix in my project.
It just feels weird because one would think that since it is not rendered, the ngComponentOutlet directive shouldn't be triggered.

**Comment by alexzuza** [comment]
It shouldn't feel weird once you expand *ngComponentOutlet structural directive to the full form

```
<ng-template [ngComponentOutlet]="cellTemplate">
```
This means that `ngComponentOutlet` input binding is being passed to the directive and you're getting the error because of that.

**Comment by npafitis** [comment]
Thanks alot @alexzuza.
Closing this ticket since it is not really an issue.
