### ISSUE TITLE
Display inaccuracy on angular.io homepage

### ISSUE THREAD

**Issue by tzvipm** [angular/angular#31454]
# 📚 Docs or angular.io bug report

### Description

The "Get started" button on the angular.io homepage seems to be displaying incorrectly.

### What's the affected URL?**
https://angular.io/

### Reproduction Steps**
N/A

### Expected vs Actual Behavior**
Should be apparent from the screenshot

## 📷Screenshot
![angularIoDisplayBug](https://user-images.githubusercontent.com/1950680/60835494-41eea700-a191-11e9-98e3-2fe1549ea111.png)

## 🔥 Exception or Error
N/A

### Browser info
Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by ericmartinezr** [comment]
On what version of the website are you? I'm on Version 8.1.1-local+sha.4bda80003. and I see it fine. Same version of Chrome.

**Comment by gkalpak** [comment]
I suspect this is an issue with a specific fallback font (specified [here][1] and used [there][2]).
This has been brought up again in the past: #20382

@tzvipm (or anyone else): Would you be interested in implementing the changes suggested in https://github.com/angular/angular/pull/20382#discussion_r150487492?
(And/Or verify that they fix the problem for you?)

[1]: https://github.com/angular/angular/blob/6aaca21c27f0e220e2ec59b7ea46d20e1a70a597/aio/src/styles/_constants.scss#L2
[2]: https://github.com/angular/angular/blob/6aaca21c27f0e220e2ec59b7ea46d20e1a70a597/aio/src/styles/0-base/_typography.scss#L6

**Comment by tzvipm** [comment]
I was able to reproduce the bug locally on the latest master branch. I can take a look at #20382 and see if that fixes the issue :+1:

**Comment by tzvipm** [comment]
@gkalpak, The suggestion in https://github.com/angular/angular/pull/20382#discussion_r150487492 seems to work, but the button text looks vertically misaligned:

![angularIoDisplayBugSuggestedFix](https://user-images.githubusercontent.com/1950680/60904661-65712a80-a241-11e9-906b-8a06c1ab1adb.png)

Getting rid of the explicit `height` as well fixes that issue:

![angularIoDisplayBugSuggestedFixNoHeight](https://user-images.githubusercontent.com/1950680/60904674-6a35de80-a241-11e9-99e7-2377066dcd2a.png)

I'll put up a PR shortly
