### ISSUE TITLE
When is better to use NgForm and when NgFormModel?

### ISSUE THREAD

**Issue by danicomas** [angular/angular#3145]
Should I use NgFormModel or NgForm? @davideast @btford?

* Ng-Form-model
```js
constructor( @Inject(FormBuilder) fb) {
		this.personForm = fb.group({
			   name: ["", Validators.required], // required
			   age: [""] // optional
		});
	}
```

By this way you can define the validators and the bindings of your models in the class (centralized).

We don't need ng-model

* Ng-Form
```js
constructor() {
		this.model = new Model();
	}
```

It is the same way that exists in Angular 1.X.

Sometimes ng-control than ng-model is redundant (it could be the the answer :D)

**Comment by danicomas** [comment]
Is possible bind FormBuilder control with javascript variable (model)? @mhevery @davideast @btford? @jeffbcross

```js
this.personForm = fb.group({
			name: [this.model.name (binding?¿), Validators.required], // required
			age: [""] // optional
		});

onSubmit() {
		console.log(this.model); // model name is not changed
		//if we receive the model of an api endpoint we want to update the same resource (the model name should be changed) What do you think?
	}
```

**Comment by hitmanmcc** [comment]
I have the same issue as @danicomas and also tried to update the form control value with:
```javascript
this.accommodationMaintenanceForm.controls['name'].value = "new value"
```
This threw the following error:
![image](https://cloud.githubusercontent.com/assets/3464842/8822665/033c04dc-305f-11e5-9cf1-e3f4e977d286.png)

Anyway, this 2nd approach was supposed to be a hack to solve the issue but what I really wanted was for it to work like @danicomas exemplified. Or if anyone has a better suggestion, I'm all ears.

Thanks in advance.
:+1:

**Comment by mhevery** [comment]
We are still in alpha and many things are in flux. I am sorry but in order not to get overflowed with non-actionable issues we are going to close this.

**Comment by danicomas** [comment]
Ok @mhevery but we need to keep in consideration. By now the Ng-Form is not valid for the 99% of cases :D

All the devs we do:
1)Call WS
2)The WS return JSON data
3)JSON data is added in a JS variable (model)
4)Update the fields in the form
5)Send the updated model to a PUT WS (Now we need to update the model with the form fields, this is ugly)

**Comment by danicomas** [comment]
@mhevery a lot of time and commits since I opened this issue. Could you provide me the current status? I think that ng-form-model if it is not related to a model is not useful.

```js
this.personForm = fb.group({
            name: [this.model.name (binding?¿), Validators.required], // required
            age: [""] // optional
        });
```
