### ISSUE TITLE
upgrade(8.0.3 to 8.1.0)  issues with cordova android

### ISSUE THREAD

**Issue by soorireddy** [angular/angular#31466]
after upgrade  to 8.1.0 from 8.03  , the build is not working in **cordova-android**  platform.
but is working well in cordova-browser (chrome) ?

**any changes required  in tsconfig  ?**

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "emitBOM": false,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}

 

 @angular/animations                  8.0.3  →    8.1.0
 @angular/common                      8.0.3  →    8.1.0
 @angular/compiler                    8.0.3  →    8.1.0
 @angular/core                        8.0.3  →    8.1.0
 @angular/forms                       8.0.3  →    8.1.0
 @angular/platform-browser            8.0.3  →    8.1.0
 @angular/platform-browser-dynamic    8.0.3  →    8.1.0
 @angular/router                      8.0.3  →    8.1.0
 @angular-devkit/build-angular      0.800.6  →  0.801.0
 @angular/cli                         8.0.6  →    8.1.0
 @angular/compiler-cli                8.0.3  →    8.1.0
 @angular/language-service            8.0.3  →    8.1.0
 typescript                           3.4.3  →    3.5.3

Run ncu -u to upgrade package.json

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-issue-repro2).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

---

In your case, maybe using Stackblitz won't work, but creating a repo where this can be replicated would. If this is a regression with Angular, we would definitely like to look at it ASAP, but without some way to reproduce what you're looking at, we can't do much.
