### ISSUE TITLE
Http Headers

### ISSUE THREAD

**Issue by TiagoBraga39** [angular/angular#3146]
Hi all!

Just wondering why we have Http "Headers" class.

I don't think its' functionality is clear.

<b>The code:</b>
```javascript
var req = new Request({
    url: <api>,
    body: { },
    method: RequestMethods.GET,
    mode: RequestModesOpts.Cors,
    credentials: RequestCredentialsOpts.Omit,
    headers: new Headers()
});
```

<b>And the req object:</b>
![image](https://cloud.githubusercontent.com/assets/8090726/8773020/eb5ff0b8-2ec8-11e5-961f-222aa3827e4c.png)

----
As you can see, headers is not a json (of course it's an object), but how can I use this class to add headers to my http request?

<h2>Option 1:</h2>
request.headers: { json here }

<h2>Option 2:</h2>
Iterate over an Header object, and add to headers property.

----
But that's it? I don't see the advantage of using the Header class if I can't simply do:
```javascript
var header = new Header({ json here })
----------- or -----------
var header = new Header();
header.append('key', 'value');

----------- and then -----------
request.headers = headers.toJson() // or something like that
```

Best regards,
Tiago Braga

**Comment by mhevery** [comment]
We are still in alpha and many things are in flux. I am sorry but in order not to get overflowed with non-actionable issues we are going to close this.

**Comment by TiagoBraga39** [comment]
Seems fair :)
I will continue to use a JSON object for now.
