### ISSUE TITLE
Angular Doc -File Names are wrong in examples  @Input() and @Output() declarations section

### ISSUE THREAD

**Issue by amolchaudhari69** [angular/angular#31467]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by amolchaudhari69** [comment]
I am exploring Angular 7 latest Doc where I found the component code is mentioned for template file.

URL
https://angular.io/guide/template-syntax#template-reference-variables-var  
Section :
@Input() and @Output() declarations

Files names are not correct
Check out the file names in the attached screenshot
File names should be **src/app/app.component.ts** 

![AngularDocIssue](https://user-images.githubusercontent.com/4987106/60897394-a428d400-a285-11e9-8cde-3f1b3eaf00bf.PNG)

**Comment by kapunahelewong** [comment]
Thanks for this @amolchaudhari69! I've submitted a PR to fix it.

**Comment by amolchaudhari69** [comment]
Thank You  For Quick Action
