### ISSUE TITLE
TypeError: shared_1.myFunction is not a function in tests for "static" functions

### ISSUE THREAD

**Issue by yelhouti** [angular/angular#31460]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core/testing

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
When my test code calls a method on component that uses a static function I get the error:
`TypeError: shared_1.myFunction is not a function`

## 🔬 Minimal Reproduction
Sorry can't use stackblitz since it's the tests that aren't working

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

TypeError: shared_1.myFunction is not a function
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.2
Node: 10.15.3
OS: linux x64
Angular: 8.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.800.2
@angular-devkit/core         8.0.2
@angular-devkit/schematics   8.0.2
@angular/cli                 8.0.2
@ngtools/webpack             8.0.2
@schematics/angular          8.0.2
@schematics/update           0.800.2
rxjs                         6.5.2
typescript                   3.4.5
webpack                      4.34.0

</code></pre>

**Anything else relevant?**

Maybe this is caused by:
```
.overrideTemplate(CustomerComponent, '')
.compileComponents();
```
overriding a needed reference.

**Comment by AndrewKushnir** [comment]
Hi @yelhouti, unfortunately this ticket doesn't contain enough information to perform an investigation. Could you please try to create a small repro that we can look at? Thank you.

**Comment by yelhouti** [comment]
@AndrewKushnir my bad, i kept investigating and found out that it's ts-jest fault, it doesn't handle `import`s from `export` in my index.ts. https://github.com/kulshekhar/ts-jest/issues/1149
My bad, closing.
