### ISSUE TITLE
Allow `sms`-URLs

### ISSUE THREAD

**Issue by Springrbua** [angular/angular#31462]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/platform-browser, but the related code is located in @angular/core

### Description
The method `DomSanitizer#sanitize` should allow resource-urls starting with `sms`

### Describe the solution you'd like
The [SAFE_URL_PATTERN](https://github.com/angular/angular/blob/master/packages/core/src/sanitization/url_sanitizer.ts#L37) should be updated to allow `sms` in addition to `mailto`, `ftp`, `tel` and `file`.
Current: `/^(?:(?:https?|mailto|ftp|tel|file):|[^&:/?#]*(?:[/?#]|$))/gi`
Updated: `/^(?:(?:https?|mailto|ftp|tel|sms|file):|[^&:/?#]*(?:[/?#]|$))/gi`

### Describe alternatives you've considered
The current workaround is using `bypassSecurityTrustResourceUrl`. This is not a problem in my case, since the URL is not user-defined and definitely starts with `sms`.

**Comment by Coooi** [comment]
Any updates on this one?

**Comment by Vandivier** [comment]
Please take a look at the following, and consider upvoting, as a generic solution for this and other similar problems:
https://github.com/angular/angular/issues/36650
