### ISSUE TITLE
Router navigateByUrl with Route  pass role 

### ISSUE THREAD

**Issue by anuraggupta816** [angular/angular#31461]
Hi 
I am using role base auth guard. but i am facing issues with navigateByUrl. how can I pass role with navigateByUrl?

**Comment by djleonskennedy** [comment]
@anuraggupta816 this isn't place for "How To" !

**Comment by santoshyadav198613** [comment]
Hi @anuraggupta816 ,
This is not an angular issue, post this question on StackOverflow with Tag as Angular. I am sure you will get some help there. This will be closed soon.

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
