### ISSUE TITLE
Cannot read files from ubuntu on send to rest

### ISSUE THREAD

**Issue by Montellanos** [angular/angular#31475]
I have created a reactive form to send files to a rest.

For this I used the httpclient module, but I'm facing an error when I want to send the files.
I detail the problem:
I select a file that is only read in ubuntu 18, and when I send it, I get denied access in the http client.

My question is if there is any way of capturing which file is not allowed to be sent, to be able to report in the interface, because the http client error only says unknown error.

I await your comments.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
