### ISSUE TITLE
Http Request Subscribe Try Catch Finally Clause

### ISSUE THREAD

**Issue by TiagoBraga39** [angular/angular#3147]
Hi all!

As far as I am concerned, I can't use the common try catch finally clauses on a http request.
I tried 2 ways to do so.

<h1>Request object</h1>
```javascript
var req = new Request({
    url: 'http://api.github.com/users',
    body: { },
    method: RequestMethods.GET,
    mode: RequestModesOpts.Cors,
    credentials: RequestCredentialsOpts.Omit
});
```
---
<h1>Option 1:</h1>
```javascript
var observable = this.http.request(req).toRx();
observable.subscribe(
    res => {
        console.log("Try clause");
    },
    error => {
        console.log("Catch clause");
    },
    () => {
        console.log("Finally clause");
    }
);
```
---
<h1>Option 2:</h1>
```javascript
ObservableWrapper.subscribe(this.http.request(req), 
    res => {
        console.log("Try clause");
    },
    error => {
        console.log("Catch clause");
    },
    () => {
        console.log("Finally clause");
    }
);
```
---
<h1>Result:</h1>
None of them trigger the finally clause.

<h3>Source for option 1:</h3>
![image](https://cloud.githubusercontent.com/assets/8090726/8773455/54306a20-2ecc-11e5-8080-9777c716dc3c.png)

<h3>Source for option 2:</h3>
![image](https://cloud.githubusercontent.com/assets/8090726/8773436/3645dfea-2ecc-11e5-9424-243aa9165dd3.png)

Best regards,
Tiago Braga

**Comment by danicomas** [comment]
option 2 is not correct you shouldn't use ObservableWrapper because it is an internal API. @TiagoBraga39

**Comment by TiagoBraga39** [comment]
Better that way, since I wanted the first one.
But what about option 1?

Best regards,
Tiago Braga

**Comment by gdi2290** [comment]
there's a PR open for this https://github.com/angular/angular/pull/2666

**Comment by TiagoBraga39** [comment]
Closed by https://github.com/angular/angular/commit/6fac9011
