### ISSUE TITLE
add ' to (mouseover) 

### ISSUE THREAD

**Issue by mourahi** [angular/angular#3148]
the documentation for Directive here https://github.com/angular/angular/blob/master/modules/angular2/docs/core/02_directives.md 

must add '  to (mouseover) like that : 

 host: {                   
    '(mouseover)' : 'show()'   
 }

thanks

**Comment by pkozlowski-opensource** [comment]
@mourahi I'm probably to sloppy to notice where it needs to be added but after the quick scan of the doc I can see that it is there: https://github.com/angular/angular/blame/master/modules/angular2/docs/core/02_directives.md#L70

Could you please point to the exact line, or - better yet, send a pull request with a correction?

**Comment by mourahi** [comment]
My english is very bad , sorry /

Here the problem : 

```
@Directive({
  selector: '[tooltip]',     | CSS Selector which triggers the decorator
  properties: [              | List which properties need to be bound
    'text: tooltip'          |  - DOM element tooltip property should be
  ],                         |    mapped to the directive text property.
  host: {                    | List which events need to be mapped.
    (mouseover): 'show()'    |  - Invoke the show() method every time
  }                          |    the mouseover event is fired.
})                           |
class Form {                 | Directive controller class, instantiated
                             | when CSS matches.
  text:string;               | text property on the Directive Controller.
                             |
  show(event) {              | Show method which implements the show action.
    console.log(this.text);  |
  }
}
```

in this example, you must add ' to (mouseover) like that : 

host :{
   '(mouseover)' :'show()'
}

thanks and sorry

**Comment by pkozlowski-opensource** [comment]
@mourahi but I've linked to the exact line where the code is there: https://github.com/angular/angular/blame/master/modules/angular2/docs/core/02_directives.md#L70

Is there any other place where it should be added?

**Comment by mourahi** [comment]
No, that's the exact line .
