### ISSUE TITLE
Angular Browser cache

### ISSUE THREAD

**Issue by ansitrajesh** [angular/angular#31488]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

I am developing web app in angular and i face one issue many times that when i update the build on server and open the app on server url then all the time i need to clear my browser cache. If i not do this then the older pages are load and this effect my angular app performance.

Please give me some idea to clear the client browser cache when my page load at first time.

I also tried these following methods:
1)
meta http-equiv="cache-control" content="max-age=0" 
meta http-equiv="cache-control" content="no-cache" 
meta http-equiv="expires" content="0" 
meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" 
meta http-equiv="pragma" content="no-cache"
2) At the build time ng build --prod --outputHashing=all

Both methods are not working. Please share your views to this issue.

You can get your questions answered using other communication channels. Please see: 
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

If you need to file a new ticket with a bug, please make sure to follow the template and include a reproduction. Without a reproduction, we can't do much about issues such as this.
