### ISSUE TITLE
Unable to run Angular8 application on IE9

### ISSUE THREAD

**Issue by neelshah1994** [angular/angular#31484]
Hi,

I have been trying a lot to run my angular8 application on IE9. Tried using polyfills and also tried many suggested solutions from angular docs and stack-overflow responses but still i dont find any success on it. 
---------------------------------------------------------------------
---------------------------------------------------------------------
Here is my **ng --version**
---------------------------------------------------------------------
Angular CLI: 8.1.0
Node: 10.15.0
OS: darwin x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.1.0
@angular/cdk                      8.0.2
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.0.2
@ngtools/webpack                  8.0.6
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
---------------------------------------------------------------------
---------------------------------------------------------------------
Here is my **package.json** : 
---------------------------------------------------------------------
"dependencies": {
    "@angular/animations": "^8.0.2",
    "@angular/cdk": "^8.0.1",
    "@angular/common": "^8.0.2",
    "@angular/compiler": "^8.0.2",
    "@angular/core": "^8.0.2",
    "@angular/flex-layout": "^2.0.0-beta.9",
    "@angular/forms": "^8.0.2",
    "@angular/material": "^2.0.0-beta.10",
    "@angular/platform-browser": "^8.0.2",
    "@angular/platform-browser-dynamic": "^8.0.2",
    "@angular/router": "^8.0.2",
    "amcharts3": "^3.21.14",
    "ammap3": "^3.21.13",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "http-status-codes": "^1.3.0",
    "install": "^0.12.2",
    "ng2-dragula": "^1.5.0",
    "npm": "^6.5.0",
    "plotly.js": "^1.43.1",
    "rxjs": "^6.5.2",
    "tslib": "^1.9.0",
    "web-animations-js": "github:angular/web-animations-js#release_pr208",
    "webpack": "^4.35.0",
    "zone.js": "~0.9.1",
    "rxjs-compat": "^6.0.0-rc.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular/cli": "^8.0.4",
    "@angular/compiler-cli": "^8.0.2",
    "@angular/language-service": "^8.0.2",
    "@types/hammerjs": "^2.0.35",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^5.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^5.1.0",
    "node-sass": "^4.11.0",
    "protractor": "^5.4.1",
    "raw-loader": "^0.5.1",
    "sass-loader": "^6.0.6",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "^3.4.5"
  }
---------------------------------------------------------------------

Could some one please help me with this??

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-issue-repro2).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

<hr>

Unfortunately, we can't do any debugging without knowing what's in your application. We test Angular against all supported browsers and it does work. So there is likely something in your environment that is broken. It of course could be related to something with Angular Version 8, but it's hard to tell without a reproduction. If you would like to re-file this ticket, please do so including a way to actually reproduce the problem.
