### ISSUE TITLE
angular.io landing page text not positioned inside button

### ISSUE THREAD

**Issue by Cogentx** [angular/angular#31498]
## 📷Screenshot
![image](https://user-images.githubusercontent.com/2342026/61012653-f20f0c00-a359-11e9-9710-789293ae322c.png)
![angulario](https://user-images.githubusercontent.com/2342026/61012786-65b11900-a35a-11e9-99b1-1223438cb866.png)

## 🌍  Your Environment
MacBook Pro

### Browser info
chrome

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/31454

**Comment by gkalpak** [comment]
Closing as duplicate of #31454.
