### ISSUE TITLE
UpdateRenderer Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by ManshSel** [angular/angular#31492]
Angular version 7.2

I build my project in prod, with a nginx webserver, An error pops off when loading the page,

main.4e8303955f3728ba991b.js:1 ERROR TypeError: Cannot read property 'id' of undefined
    at Object.updateRenderer (12.bcddf8877443ff7862af.js:1)
    at Object.updateRenderer (main.4e8303955f3728ba991b.js:1)
    at Iv (main.4e8303955f3728ba991b.js:1)
    at Bv (main.4e8303955f3728ba991b.js:1)
    at Lv (main.4e8303955f3728ba991b.js:1)
    at Iv (main.4e8303955f3728ba991b.js:1)
    at Bv (main.4e8303955f3728ba991b.js:1)
    at Lv (main.4e8303955f3728ba991b.js:1)
    at Iv (main.4e8303955f3728ba991b.js:1)
    at Bv (main.4e8303955f3728ba991b.js:1)

The update Renderer error which actually doesnt let me work with all the functionality in the app.

Please let me know if there is anything i need to know, It builds without error and works fine in local servers.

angular options

 "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]

**Comment by ericmartinezr** [comment]
Possibly related/dup https://github.com/angular/angular/issues/31314

Also a repro is always welcomed as stated in the issue template.

**Comment by ManshSel** [comment]
@ericmartinezr Thanks for the redirect, but seems not related to mine as i am not using ivy at all. I would not be able to share the repo as it is a private development code. Very sorry, but ya i did deploy in https://tactuc.com/ which can be of reference.

Thanks a lot

**Comment by Mansh05** [comment]
Hi Everyone, Anyone? any feedback or help here. Been stuck for a while with my project.

**Comment by mhevery** [comment]
We need stackblitz repro otherwise we can't help you.
