### ISSUE TITLE
Dynamically FormControl not binding

### ISSUE THREAD

**Issue by ankurgupta12** [angular/angular#31505]
My code is following .

in dynamic Form Builder Component is following.
<button (click)="addItem()">Add</button> 
<form (ngSubmit)="onSubmit(this.form.value)" [formGroup]="form" class="form-horizontal">
<div formArrayName="items">
<div *ngFor="let item of form.get('items').controls; let i=index" [formGroupName]="i" >
<div *ngFor="let field of fields">
<label class="col-md-3 form-control-label" [attr.for]="field.label">
{{field.label}}

</label>
<div class="col-md-9" [ngSwitch]="field.type">
<textbox *ngSwitchCase="'text'" [field]="field" [form]="form"></textbox>
</div>
</div>
</div>
</div>
</div>
</form>
`,
})
export class DynamicFormBuilderComponent implements OnInit {
  // @Output() onSubmit = new EventEmitter();
  @Input() fields;
  form: FormGroup;
  items: FormArray;
  fieldsCtrls = {};
  constructor(public fb: FormBuilder) { }
  ngOnInit() {
    for (let f of this.fields) {
      this.fieldsCtrls[f.name] = new FormControl()
    }
console.log(this.fieldsCtrls);

    this.form = new FormGroup({
      "items": new FormArray([new FormGroup(this.fieldsCtrls)])
    });
    console.log('fieldsCtrls', this.form)
    // this.form = new FormGroup(fieldsCtrls);
  }

  addItem = () => {
    let fieldsCtrls = {};
    for (let f of this.fields) {
      fieldsCtrls[f.name] = new FormControl(f.value || '')
    }
    this.items = this.form.get('items') as FormArray;
    this.items.push(new FormGroup(fieldsCtrls));
    console.log(this.items);
  }

  onSubmit = (data) => {
    console.log("===vlaue", data);
  }
}

TextBox component is following code .
@Component({
    selector: 'textbox',
    template: `
      <div [formGroup]="form" >
        <input [attr.type]="field.type" class="form-control" id="{{field.name}}" name="{{field.name}}" formControlName="{{field.name}}">
      </div> 
    `
})
export class TextBoxComponent {
    @Input() field;
    @Input() form:FormGroup;
    ngOnInit() {
      console.log(this.field);
    }
    get isValid() { return this.form.controls[this.field.name].valid; }
    get isDirty() { return this.form.controls[this.field.name].dirty; }
  
    constructor() {

    }
}

In appComponent.html
<div class="col-sm-12">
  <div class="card">
    <div class="card-header">Dynamic Forms</div>
    <div class="card-body">
      <dynamic-form-builder [fields]="getFields()"></dynamic-form-builder>
    </div>
  </div>
</div>

Now error is coming that Cannot find control with name: 'firstName' after adding more fields  also it is showing the same error. So please tell me what is the issue with dynamic form control.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by santoshyadav198613** [comment]
Hi @ankurgupta12 ,
This doesn't look like an Angular issue, you can post it on StackOverflow , if you still think its an Angular issue, please create a stackblitz link to check.
This issue will be closed soon.

**Comment by ankurgupta12** [comment]
https://stackblitz.com/edit/angular-dynamic-form-builder

**Comment by ankurgupta12** [comment]
Please have a look for this issue ..

**Comment by santoshyadav198613** [comment]
Hi @ankurgupta12 ,
The link provided works fine, where is the error?

**Comment by ankurgupta12** [comment]
Actually  you have to paste the following code into the dynamicFormBuilderComponent.ts..

import { Component, Input, OnInit, Output, EventEmitter } from '@angular/core';
import { FormGroup, FormControl, Validators,FormArray,FormBuilder } from '@angular/forms';

@Component({
selector: 'dynamic-form-builder',
template:`
<button (click)="addItem()">Add</button>
<form (ngSubmit)="onSubmit(this.form.value)" [formGroup]="form" class="form-horizontal">
<div formArrayName="items">
<div *ngFor="let item of form.get('items').controls; let i=index" formGroupName="{{i}}" >
<div *ngFor="let field of fields">
<label class="col-md-3 form-control-label" [attr.for]="field.label">
{{field.label}}
<strong class="text-danger" *ngIf="field.required">*</strong>
</label>
<div class="col-md-9" [ngSwitch]="field.type">
<textbox *ngSwitchCase="'text'" [field]="field" [form]="form"></textbox>
<dropdown *ngSwitchCase="'dropdown'" [field]="field" [form]="form"></dropdown>
<checkbox *ngSwitchCase="'checkbox'" [field]="field" [form]="form"></checkbox>
<radio *ngSwitchCase="'radio'" [field]="field" [form]="form"></radio>
<file *ngSwitchCase="'file'" [field]="field" [form]="form"></file>
<div class="alert alert-danger my-1 p-2 fadeInDown animated" *ngIf="!isValid && isDirty">{{field.label}} is required</div>
</div>
</div>
</div>
</div>
<div class="form-row"></div>
<div class="form-group row">
<div class="col-md-3"></div>
<div class="col-md-9">
<button type="submit" [disabled]="!form.valid" class="btn btn-primary">Save</button>
</div>
</div>
</form>
`,
})
export class DynamicFormBuilderComponent implements OnInit {
// @Output() onSubmit = new EventEmitter();
@Input() fields: any[] = [];
form: FormGroup;
items: FormArray;

constructor(public fb : FormBuilder) { }

ngOnInit() {
let fieldsCtrls = {};
for (let f of this.fields) {
fieldsCtrls[f.name] = new FormControl(f.value || '')
}

this.form = new FormGroup({
"items": new FormArray([new FormGroup(fieldsCtrls)])
});
console.log('fieldsCtrls', fieldsCtrls)
// this.form = new FormGroup(fieldsCtrls);
}
print(){
console.log('form is', this.form)
}
addItem = () => {
let fieldsCtrls = {};
for (let f of this.fields) {
fieldsCtrls[f.name] = new FormControl(f.value || '')
}
this.items = this.form.get('items') as FormArray;
this.items.push(new FormGroup(fieldsCtrls));
console.log(this.items);
}


onSubmit = (data) => {
console.log("===vlaue", data);
}
}

**Comment by santoshyadav198613** [comment]
Hi @ankurgupta12 ,
can you update your stackblitz with above changes,

**Comment by santoshyadav198613** [comment]
Hi @ankurgupta12 ,
Also, i would suggest open this on stackoverflow.

**Comment by ankurgupta12** [comment]
https://stackblitz.com/edit/dynamicform2?file=src%2Fapp%2Fapp.component.css

**Comment by ankurgupta12** [comment]
Now Please Open this URL and look into console .

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
