### ISSUE TITLE
Cannot create property 'ngIf' on number in Angular 8

### ISSUE THREAD

**Issue by BlindDespair** [angular/angular#31508]
# 🐞 bug report

### Affected Package

@angular/core

### Is this a regression?

I can't tell exactly, this app is freshly written in angular 8, but I've never encountered such issues in previous versions.

### Description
ngIf behaves unexpectedly, I have a complex component which consists of multiple smaller components, but still template reaches up to 70 lines. There I have bindings on every component and at the top of the template I have this code:
```
<h2>
    <span *ngIf="hasBasicInfo(); else missing">
      {{ form.value[basicInfoFormControlName][nameControlName] }}
    </span>
    <ng-template #missing>MISSING</ng-template>
  </h2>
```
This works perfectly fine until I changed one of subcomponents, which in template looked like this:
```
<st-classification-in-frameworks
              [solution]="solution"
              [selectedSegments]="solution.segments"
              (segmentSelectionChange)="updateSolutionOnSegmentSelection($event)"
></st-classification-in-frameworks>
```
Basically I just deleted `[selectedSegments]="solution.segments"` like and removed an `@Input()` in that component.
As soon as I do that I get error: `Cannot create property 'ngIf' on number 871548`
It complains exactly about that `ngIf` I mentioned above. I believe this is a bug in the core rendering(I am using Ivy), because for some reason `instance` in `setInputsForProperty` is evaluated as a number, and not only that, sometimes I am also getting boolean value. This appears to be pretty random, because when I remove else part from that `ngIf` it works again, or if I move it another place. I don't see how my code can be wrong to break it. But I also don't have knowledge of how Ivy works from inside to understand why this happens.

## 🔬 Minimal Reproduction
Unfortunately I was not able to reproduce this in any other setup, this issue seems to be pretty specific and quite random.

## 🔥 Exception or Error
<pre><code>

core.js:7187 ERROR TypeError: Cannot create property 'ngIf' on number '871548'
    at setInputsForProperty (core.js:13500)
    at elementPropertyInternal (core.js:12390)
    at Module.ɵɵproperty (core.js:16528)
    at SolutionComponent_Template (solution.component.html:3)
    at executeTemplate (core.js:12007)
    at checkView (core.js:13358)
    at componentRefresh (core.js:13122)
    at refreshChildComponents (core.js:11710)
    at refreshDescendantViews (core.js:11616)
    at renderComponentOrTemplate (core.js:11985)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.0
Node: 10.16.0
OS: darwin x64
Angular: 8.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@ngtools/webpack                  8.0.0
@schematics/angular               8.0.0
@schematics/update                0.800.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

One more detail is that the error doesn't happen on initial load of the component. First time it renders correctly, however if `hasBasicInfo` returns false, it does not render the `missing` template. Then I click on something that triggers change detection and that error appears. What is interesting is that it only appears twice(for ngIf and ngIfElse, which I could while trying to debug) with different property and third time it actually runs.

**Comment by kara** [comment]
@BlindDespair This definitely looks like an Ivy bug, but we need a bit more information to help. I tried to reproduce this was an ngIf / else, but wasn't able to. Can you make a minimal repro on Github so we can take a look?

**Comment by BlindDespair** [comment]
I'll try to create an app where this would be reproducible when I have time. Hopefully this week.

**Comment by BlindDespair** [comment]
@kara I spent a couple of hours today to create a small project where I could reproduce this bug, but no luck, it just doesn't happen in a minimal setup. Although I can still reproduce it my real application. But to get rid of error it's enough for me to move element to another part of template. Specifically put it inside a form element. Basically there is a big page editing component, which has subforms. And I display name of the page on top of form, which is using value from a subform. And I usually get this error when I place header outside of form, but even then it's fishy, because I can change something else and the error is gone. It's a pretty large module, so it's really hard to replicate what I have there in a minimal repro...
2 days ago I again stumbled upon error related to this. For that header I created a separate component because more things had to be added to it. and Ivy wouldn't create that component with a similar error until I moved it inside a form tag. I don't know how else to reproduce this.

**Comment by BlindDespair** [comment]
I think now I know what issue is related to. It seems that I produced this issue by my own mistake. My method `addForm` was doing this at the end: `this.cdr.detectChanges();`. When I remove it I stop getting random errors. I think issue is that `addForm` is called by event emitted from `ngOnInit` from a child component. Which means I was starting change detection while already in change detection. So I think that's what was messing things up. I think this is not bug in Ivy, but rather would be nice to have a better error message if possible.
