### ISSUE TITLE
Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

### ISSUE THREAD

**Issue by mswilson4040** [angular/angular#31518]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
@angular/material/menu/typings/menu.d.ts

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
No. First noticed the issue in 8.1.0

### Description
After going through the upgrade and (finally) getting through it all, I delete the node_modules folders as directed. I then run npm install and run ng serve. Then you're presented with this:

> ERROR in node_modules/@angular/material/menu/typings/menu.d.ts(161,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

> Angular CLI: 8.1.1
> Node: 10.15.3
> OS: darwin x64
> Angular: 8.1.1
> ... animations, cli, common, compiler, compiler-cli, core, forms
> ... language-service, platform-browser, platform-browser-dynamic
> ... platform-server, router
> 
> Package                           Version
> -----------------------------------------------------------
> @angular-devkit/architect         0.800.6
> @angular-devkit/build-angular     0.800.6
> @angular-devkit/build-optimizer   0.800.6
> @angular-devkit/build-webpack     0.800.6
> @angular-devkit/core              8.0.6
> @angular-devkit/schematics        8.1.1
> @angular/cdk                      8.0.2
> @angular/material                 8.0.2
> @ngtools/webpack                  8.0.6
> @schematics/angular               8.1.1
> @schematics/update                0.801.1
> rxjs                              6.5.2
> typescript                        3.4.5
> webpack                           4.30.0

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
Hi @mswilson4040,

this should have been resolved in `8.2.0-next.1`, could you please upgrade to that version? In general, the latest Ivy fixes are only available in the `next` releases, so using those is recommended for Ivy testing.

More info in #31160

**Comment by mswilson4040** [comment]
Thanks, @JoostK. Is this to say that we shouldn't be pulling from the current available package on `npm` (which is 8.1.1)? When will 8.2 be generally available (up on npm as the default version)?

**Comment by JoostK** [comment]
@mswilson4040 You should definitely use 8.1.1 for production usages, with Ivy disabled. Ivy is currently in preview with fixes landing regularly, so to be using the latest Ivy preview you need to be on the latest preview release, which are tagged `next`.

**Comment by mswilson4040** [comment]
Awesome. Thanks for the quick feedback, @JoostK!
