### ISSUE TITLE
i18n example file contains data ('heroes') from another tutorial

### ISSUE THREAD

**Issue by pimonenkov** [angular/angular#31514]
# 📚 Docs or angular.io bug report

### Description
When reading the "Internationalization (i18n)" article, a visitor can download the "i18n Example" file. In one of the files (i18n\src\app\app.component.ts), there is a line with 'heroes' irrelevant to the i18n example. 

* Looks like this line is a remnant of a template file in the "Tour of Heroes App" (https://angular.io/tutorial),
* When working with the i18n example file, this line can be misleading.
* I suggest removing it from the source code if it's really irrelevant. 
 

### Affected URL
https://angular.io/guide/i18n

### Reproduction Steps
1. Navigate to Techniques -> Internationalization (i18n).
2. Download the example file by clicking on a link in the "See the i18n Example..." line.
3. In the example folder, open up the ".\src\app\app.component.ts" file.
4. Look at the line 12: "heroes: string[] = ['Magneta', 'Celeritas', 'Dynama'];"

**Suggestion:** just remove the line, it belongs to another tutorial, not this one.

**Comment by kapunahelewong** [comment]
Thanks for this, @pimonenkov! I'll fix it.
