### ISSUE TITLE
Form: Implement updateValue for ControlGroup and ControlArray

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#3151]
Currently only Control has updateValue.

**Comment by cwmrowe** [comment]
+1

**Comment by choeller** [comment]
Are there plans to add this until final release (candidate)? Currently I see no nice way to populate a form with data when not wanting to use two-way databinding. Or am I missing a possibility?

**Comment by vicb** [comment]
@kara is this still applicable to the new forms ?

**Comment by zoechi** [comment]
Similar to #9553

**Comment by kara** [comment]
Thanks @zoechi. @vicb  I'm going to close this in favor of #9553.
