### ISSUE TITLE
HMR not work when enableIvy is true

### ISSUE THREAD

**Issue by ofirrifo** [angular/angular#31528]
# 🐞 bug report

### Description
The HMR (hot module replacement) stop working when I set enableIvy to true.

## 🔬 Minimal Reproduction
1. Create any Angular CLI project 
2. Configure project with Hot Module Replacement
3. add to `tsconfig.app `
     ```
      "angularCompilerOptions": {
          "enableIvy": true
        }
      ```
4. start project
5. change any scss file

Now when enableIvy is true the page refresh and then I see a blank page.
then I manually refresh the page and everything is ok.

Note when enableIvy is set to false it works as expected.
-->

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 8.1.1
Node: 12.3.1
OS: darwin x64
Angular: 8.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.1
@angular-devkit/build-angular      0.801.1
@angular-devkit/build-ng-packagr   0.801.1
@angular-devkit/build-optimizer    0.801.1
@angular-devkit/build-webpack      0.801.1
@angular-devkit/core               8.1.1
@angular-devkit/schematics         8.1.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.1.1
@schematics/angular                8.1.1
@schematics/update                 0.801.1
ng-packagr                         5.3.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.35.2

**Comment by kukjevov** [comment]
This might be related https://github.com/angular/angular-cli/issues/15225

**Comment by filipesilva** [comment]
Heya, I'm closing because https://github.com/angular/angular/issues/31916#issuecomment-517482988 indicates this is a tracked bug and there is a fix on the way.
