### ISSUE TITLE
interpolation not working properly while dynamically change value

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular#31526]
# 🐞 bug report

**interpolation throws error while dynamically change value**

### Description

**I have tried to update value dynamically using interpolation but it throws below error:**

**I have created components like below :**

```
import { Component, ViewEncapsulation} from '@angular/core';
 
@Component({
 selector: 'app-root',
 templateUrl: 'app.component.html',
 styleUrls: ['app.component.css'],
 encapsulation: ViewEncapsulation.None
})
 
export class AppComponent {
 constructor() { }
 public rtedataSource: string = "<p>One</p>";
 checkRTE(){
 this.rtedataSource ="asffsdffsf"
 }
}
```

### Error: 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/36756050/61124994-20a9f580-a4c6-11e9-94f4-c490fc4615d8.png)

## 🔬 Minimal Reproduction

1. Download below sample: 
[Angular_issue.zip](https://github.com/angular/angular/files/3386234/Angular_issue.zip)

2. give below commands

> npm i

> ng serve

## 🔥 Exception or Error

But if i use **_changeDetection: ChangeDetectionStrategy.OnPush_**, it doesn't throws any error and interpolation working fine.

**Reference code:**

```
import { Component, ViewEncapsulation, ChangeDetectionStrategy, ChangeDetectorRef} from'@angular/core';
 
@Component({
selector:'app-root',
templateUrl:'app.component.html',
styleUrls: ['app.component.css'],
encapsulation:ViewEncapsulation.None,
changeDetection:ChangeDetectionStrategy.OnPush
})
 
exportclassAppComponent {
constructor(privateref:ChangeDetectorRef) {
ref.detach();
setInterval(() => { this.ref.detectChanges(); }, 100);
 }
publicrtedataSource:string="<p>One</p>";
checkRTE(){
this.rtedataSource="asffsdffsf"
 }
}
```

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.0.3
Node: 8.9.3
OS: win32 x64
Angular:
...

 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.3
@angular-devkit/core         7.0.3
@angular-devkit/schematics   7.0.3
@schematics/angular          7.0.3
@schematics/update           0.10.3
rxjs                         6.3.3
typescript                   3.1.3
</code></pre>

**Anything else relevant?**

I just want to know why this happening?

**Comment by mlc-mlapis** [comment]
@kumaresan-subramani The behavior is expected. You change `rtedataSource`  twice in one CD cycle. For the first time here (to `undefined`), when `ejs-richtexteditor` child component is instantiated:
```
<ng-template #valueTemplate>
   <p>{{rtedataSource}}</p>
</ng-template>
```
and for the second time here `public rtedataSource: string = "<p>One</p>";`.

**Comment by kumaresan-subramani** [comment]
HI @mlc-mlapis ,

You mean, while using **changedetection** it goes for **marforcheck**() then **ngonchange**() cycle starts so that issue wont occurs while using **change detection.**

Is it?

**Comment by mlc-mlapis** [comment]
@kumaresan-subramani I mean the order, in which the parent and its children components are instantiated and why the error `ExpressionChangedAfterItHasBeenCheckedError` appears when you run the app.

**Comment by kumaresan-subramani** [comment]
@mlc-mlapis , Thanks 👍

**Comment by dblVs** [comment]
@kumaresan-subramani could you close the issue

**Comment by pkozlowski-opensource** [comment]
Sounds like a support request that got resolved. Thnx so much for helping out with the issues @mlc-mlapis !

**Comment by kumaresan-subramani** [comment]
HI @pkozlowski-opensource ,

But i have one more issue,

If i use interpolation to bind value in ng-template, my tooltip positioning got misplaced

Any idea about this?

Issue sample - [click here](https://stackblitz.com/edit/angular-vavoqp?file=src/app/app.component.ts)

But with out interpolation sample working fine. please refer below sample:

Sample - [click here](https://stackblitz.com/edit/angular-rxxhee?file=src/app/app.component.html)

**Comment by mlc-mlapis** [comment]
@kumaresan-subramani Hmm, just styling polishing. The binding adds some parts to HTML and they interfere probably differently with your styles. Compare details what is in DOM in both cases (including comments).

**Comment by kumaresan-subramani** [comment]
HI @mlc-mlapis ,

Please analyze issue before updating your answer 👎 

Styling is not an issue here

based on interpolated value, i will set position of my dialog

But here, interpolation value comes with some time delay so that my positioning goes wrong...!

Thats why i have posted this here.........!

**Comment by kumaresan-subramani** [comment]
Hi @alan-agius4 ,

Do you have suggestion regarding this?

**Comment by mlc-mlapis** [comment]
@kumaresan-subramani OK, from that simple demo it was not clear. If you know the reason why didn't you explain it? And what do expect now? Do you think that somebody would analyze how `<ejs-tooltip>` component is working, which timeline is exactly using and so on?

**If it is a real Angular problem then demonstrate it using the pure code without using any libs.**

**Comment by kumaresan-subramani** [comment]
HI @mlc-mlapis ,

I am not expecting, somebody would analyze how <ejs-tooltip> component is working.

I am looking for any suggestion to regarding this like is there any other possibility to avoid time delay while interpolation performs.

Anyway thanks for your reply 👍

**Comment by mlc-mlapis** [comment]
@kumaresan-subramani Then I think it is the issue for https://github.com/syncfusion/ej2-angular-ui-components/issues.

**Comment by kumaresan-subramani** [comment]
Okay @mlc-mlapis ,

Thanks 👍
