### ISSUE TITLE
Ability to annotate a constructor for services/components with multiple constructors

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#3152]
Right now the behavior is to use the default constructor, and it gives a warning, but it would be nice to remove the warning from the build step by annotating a constructor we want.

**Comment by mhevery** [comment]
I don't think we will support this. JS does not have named constructors. Going to close. Can you reopen with specific use case.

**Comment by matanlurey** [comment]
This would just be for the Dart version since only Dart has the transformer :)

**Comment by mhevery** [comment]
Why can't we just have the default constructor to be the injectable one. You are free to create named constructors for yourself. Would't that solve the issue?

**Comment by matanlurey** [comment]
This occurs in the transformer build step, as it warns when it sees multiple constructors. If this is the behavior we want (always use default constructor) then let's not warn.
