### ISSUE TITLE
Live example broken

### ISSUE THREAD

**Issue by virtualgithub** [angular/angular#31537]
# 📚 Docs or angular.io bug report

### Description

https://angular.io/guide/template-syntax
There is a live example from the official doc thats not working: https://angular.io/generated/live-examples/template-syntax/stackblitz.html

The live example error says:
Import error, can't find file: ./svg.component.svg

If I download the example and npm install it, I got the error:
ERROR in ./src/app/svg.component.ts
Module not found: Error: Can't resolve './svg.component.svg' in 'C:\Users\Elias\Desktop\New folder\src\app'

### What's the affected URL?**
https://angular.io/generated/live-examples/template-syntax/stackblitz.html

## 🔥 Exception or Error
<pre><code>

Import error, can't find file:
./svg.component.svg

</code></pre>

**Comment by santoshyadav198613** [comment]
Hi @virtualgithub ,
The problem is stackblitz does not support it. You can download it locally and run. Also there is already an issue logged with stackblitz.

**Comment by virtualgithub** [comment]
> Hi @virtualgithub ,
> The problem is stackblitz does not support it. You can download it locally and run. Also there is already an issue logged with stackblitz.

If I download the example and npm install it, I got the error:
ERROR in ./src/app/svg.component.ts
Module not found: Error: Can't resolve './svg.component.svg' in 'C:\Users\Elias\Desktop\New folder\src\app'

**Comment by santoshyadav198613** [comment]
Hi @kapunahelewong ,

I will look into it.

**Comment by santoshyadav198613** [comment]
Hi @kapunahelewong ,

In example zipper, we are not including .svg added it.
