### ISSUE TITLE
Unsubscribe additions...

### ISSUE THREAD

**Issue by deadmann** [angular/angular#31538]
# 🚀 feature request

### Relevant Package

https://angular.io/guide/http or maybe RxJs

### Description
I'm not sure, but as i just recently searched a lot and hear... right or wrong
unsubscribe abort the http process?

- [ ] if wrong: then we need a functionality to abort the actual process reducing client load and downloads
- [ ] if right: then what if i want to decrease the load on my server? a user keep on changing stuff, or an unsure user keep switching between multiple options, with lots of data calculation and huge queries behind the scene?
i would like to do something like this:
```TypeScript
let y = x.subscribe(data=>{result = data;});
...user input change...
x.subscribe(data => cacheList[data.name] = data);
y.unsubscribe(); // --> and the flow of loading data continue but it don't affect our UI
```

### Describe the solution you'd like
we need a method for fully abort, another for just unsubscribe the event handler

### Describe alternatives you've considered
no alternative by me

**Comment by montella1507** [comment]
you may use shareReplay of your Http subscription if i got you right.

**Comment by deadmann** [comment]
what I'm talking is in a term of my knowledge of subscription, which in all language we mean subscribe to some event object. the un-subscription process usually remove the event handler or the function from the calling back queues. so i could subscribe 2 time, and then i needed to unsubscribe two time too, to have no access point to the data, and data really becomes useless.

event.subscribe(x=>{ /*Here do data binding*/ }
event.subscribe(x=>{ /*Here do something else*/ }

BTW i feel to wrote lots of codes, and i did what i needed through this code:

```Typescript
  // tslint:disable:member-ordering
  private stateOrProvinceCache: Array<KeyValuePair<string, Array<StateOrProvince>>> = [];
  private stateOrProvinceRunningHttpProcess: Array<string> = [];
  public stateOrProvinceIsLoading = false;
  // tslint:restore:member-ordering
  onCountryChanged() {
    if (_.find(this.stateOrProvinceRunningHttpProcess, w => w === this.country.value.id)) {
      // If process exists return
      return;
    } else {
      // Otherwise add process
      this.stateOrProvinceRunningHttpProcess.push(this.country.value.id);
    }

    // Make it part of function body, so it will persists per call
    const countryId = this.country.value.id;

    // Clearing List and Form Selections
    this.stateOrProvinceList = [];
    this.cityList = [];
    this.regionList = [];
    this.stateOrProvince.setValue(null);
    this.city.setValue(null);
    this.region.setValue(null);
    this.stateOrProvince.disable();
    this.city.disable();
    this.region.disable();

    // Read from Cache
    const cached = _.find(this.stateOrProvinceCache, w => w.Key === countryId);
    if (cached) {
      this.stateOrProvinceList = cached.Value;
      this.stateOrProvince.enable();
    }

    // Make HTTP Request
    this.stateOrProvinceIsLoading = true;
    this.stateOrProvinceService.getsByCountry(countryId).subscribe((data: Array<StateOrProvince>) => {
      this.stateOrProvinceCache.push(new KeyValuePair<string, Array<StateOrProvince>>(countryId, data));
      if (this.country.value.id === countryId) {
        this.stateOrProvinceList = data;
        this.stateOrProvince.enable();
        this.stateOrProvinceIsLoading = false;
      }
    }, (error) => {
      this.alertify.error(error);
    }, () => {
      // On Complete
      this.stateOrProvinceRunningHttpProcess.remove(countryId, (item, cId) => {
        return item === cId;
      });
    });
  }
```

**Comment by alxhub** [comment]
`unsubscribe` on an `HttpClient` `Observable` will abort the request, yes.

A typical way of doing this is to use the `switchMap` operator:

```typescript
@Component({
  template: `
    Data is: {{data}}
    <input (input)="userInput.next($event.target.value)">
  `, ...
})
export class MyUiComponent {
  userInput = new Subject<string>();
  data: string = '';
  
  ngOnInit(): void {
    userInput.pipe(
      switchMap(value => this.http.get(`/api/data?id=${value}`)),
    ).subscribe(data => this.data = data);
  }
}
```

The `switchMap` ensures that when the next value comes through the `userInput` `Observable`, the previous `HttpClient` request will be unsubscribed and cancelled. This operation is often combined with a `debounceTime` operator to reduce load on the server even further.

I'm going to close this issue as there's nothing actionable for us, but please feel free to continue discussing :)
