### ISSUE TITLE
Improve bad URL experience

### ISSUE THREAD

**Issue by sjtrimble** [angular/angular#31532]
# 📚 Docs or angular.io bug report

### Description

Per discussion in https://github.com/angular/angular/pull/31390:

Improve bad URL experience for users by giving them relevant data instead of 'no results found' for something they didn't _actually_ search for.

### What's the affected URL?**
Example: https://angular.io/lemonade

### Reproduction Steps**
Go to https://angular.io/lemonade to see page and message

### Expected vs Actual Behavior**
Don't actually show the "I have nothing to show you" message if we don't have any suggestions OR even better, show them a few items where they might want to spend some time on like the blog, the guide, etc.

## 📷Screenshot
<img width="1409" alt="Screen Shot 2019-07-04 at 12 32 16 PM" src="https://user-images.githubusercontent.com/2958442/60685427-edc58900-9e57-11e9-9fd2-24b1469ee2f3.png">

**Comment by ajitsinghkaler** [comment]
@sjtrimble Can I help you on this.
