### ISSUE TITLE
markAllAsTouched method is not available in NgForm (Template Driven Form)

### ISSUE THREAD

**Issue by TanvirArjel** [angular/angular#31536]
In angular 8.1.1, `markAllAsTouched` method is only available in `FormGroup` and `FormArray` in case of Reactive Form. Its not available for `NgForm` in case of Template Driven Form.

Please take a look onto it!

**Comment by atscott** [comment]
Hey Tanvir, you can call `.control.markAllAsTouched()` on the `NgForm`. I think this should be what you're looking for.
