### ISSUE TITLE
Cannot find module './app.module.ngfactory'.ts(2307)

### ISSUE THREAD

**Issue by rezaee** [angular/angular#31530]
I have uploaded my project here: https://github.com/rezaee/conFusion, actually it was an NativeScript-Angular project written in 2017 with version 5 or 6 that I tried to update it to Angular 8, and I did all the job but one file named `main.aot.ts` remained. In that file that has this content:
```
// this import should be first in order to load some required settings (like globals and reflect-metadata)
import { platformNativeScript } from "nativescript-angular/platform-static";

import { AppModuleNgFactory } from "./app.module.ngfactory";

platformNativeScript().bootstrapModuleFactory(AppModuleNgFactory);
```
I get  `Cannot find module './app.module.ngfactory'.ts(2307)` error message. I tried `npm install ```
```
ng-factory` but it gives me the following error too:
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN @angular/http@8.0.0-beta.10 requires a peer of @angular/core@8.0.0-beta.10+1.sha-a28b3e3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@8.0.0-beta.10 requires a peer of @angular/platform-browser@8.0.0-beta.10+1.sha-a28b3e3 but none is installed. You must install peer dependencies yourself.
npm WARN nativescript-angular@8.0.0 requires a peer of zone.js@^0.8.4 but none is installed. You must install peer dependencies yourself.
npm WARN nativescript-couchbase@1.0.18 requires a peer of tns-core-modules@^3.0.0 but none is installed. You must install peer dependencies yourself.

+ ng-factory@1.1.0
updated 1 package and audited 11952 packages in 25.655s
found 169 vulnerabilities (13 low, 2 moderate, 154 high)
  run `npm audit fix` to fix them, or `npm audit` for details

```
``
As I am a new learner and just following a video tutorial I don't know how to solve the problem? Please help me to solve the last error message. Thank you in advanced!

**Comment by matsko** [comment]
Sorry @rezaee. Unfortunately the issue doesn't follow our blueprint and doesn't have enough detail for us to be able to reproduce what's going on here. Please reopen a new issue and fill in everything so that we can have a look.

**Comment by rezaee** [comment]
@matsko : But I put the link of the full project! I don't know what more information is needed, or what material is needed to reproduce the project when I put the full source code?
