### ISSUE TITLE
Ivy Material menu error

### ISSUE THREAD

**Issue by enniob** [angular/angular#31545]
# 🐞 bug report

### Affected Package
I'm having an issue with the @angular/material/menu module. 

### Description
I added the @angular/material/menu module to my application and now I get the following error when I run my application.

ERROR in node_modules/@angular/material/menu/typings/menu.d.ts:161:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

161     static ngBaseDef: ɵngcc0.ɵɵBaseDef;

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.1.1
Node: 10.16.0
OS: win32 x64
Angular: 8.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.1
@angular-devkit/build-angular     0.801.1
@angular-devkit/build-optimizer   0.801.1
@angular-devkit/build-webpack     0.801.1
@angular-devkit/core              8.1.1
@angular-devkit/schematics        8.1.1
@angular/cdk                      8.0.2
@angular/fire                     5.2.1
@angular/material                 8.0.2
@ngtools/webpack                  8.1.1
@schematics/angular               8.1.1
@schematics/update                0.801.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Comment by JoostK** [comment]
Hi @enniob,

this should have been resolved in 8.2.0-next.1, could you please upgrade to that version and try again? In general, the latest Ivy fixes are only available in the next releases, so using those is recommended for Ivy testing.

More info in #31160

**Comment by enniob** [comment]
thanks for the help. That worked.
