### ISSUE TITLE
michaelbromley/ngx-pagination with ivy

### ISSUE THREAD

**Issue by hadley8899** [angular/angular#31540]
# 🐞 bug report

### Affected Package
@angular 8.0.0 and 8.1.0 with ivy

### Is this a regression?
Works fine without ivy

### Description
When Ivy is enabled the package michaelbromley/ngx-pagination no longer works. It produces a console error as seen in the Exception or Error section

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-1nyivw

The project is setup here but IVY doesn't seem to work on stackblitz (It just doesn't detect the tsconfig)

## The repo for this is here
https://github.com/hadley8899/angular-ngx-pagination-ivy-issue

## 🔥 Exception or Error
`core.js:9110 ERROR Error: Export of name 'paginationApi' not found!
    at cacheMatchingLocalNames (core.js:15418)
    at resolveDirectives (core.js:15191)
    at createDirectivesAndLocals (core.js:14609)
    at ɵɵelementStart (core.js:19505)
    at PaginationControlsComponent_Template (template.html:2)
    at executeTemplate (core.js:14533)
    at checkView (core.js:15957)
    at componentRefresh (core.js:15715)
    at refreshChildComponents (core.js:14214)
    at refreshDescendantViews (core.js:14120)`

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.1
Node: 10.15.3
OS: win32 x64
Angular: 8.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.1
@angular-devkit/build-angular     0.801.1
@angular-devkit/build-optimizer   0.801.1
@angular-devkit/build-webpack     0.801.1
@angular-devkit/core              8.1.1
@angular-devkit/schematics        8.1.1
@ngtools/webpack                  8.1.1
@schematics/angular               8.1.1
@schematics/update                0.801.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Comment by JoostK** [comment]
Hi @hadley8899,

thanks you for reporting! I had a quick go with your reproduction repo and even after upgrading to `8.2.0-next.1` I am able to reproduce. At first glance, only the `NgxPaginationModule` module from `ngx-pagination` is processed by ngcc, none of its components are processed and therefore not prepared for Ivy. So this does look like an issue in ngcc that we need to look into. Thanks again for reporting!

**Comment by JoostK** [comment]
ngcc is not dealing with the suffixed names like `__decorate$1` and `__metadata$1` correctly, which causes the package to be processed only partially. With a small fix to ngcc we can get it to work :)

<img width="294" alt="Screenshot 2019-07-13 at 12 28 34" src="https://user-images.githubusercontent.com/123679/61170475-d4b08c80-a569-11e9-99f7-35d20df80cc8.png">

I will work on a PR later this week.

**Comment by hadley8899** [comment]
Awesome, that is great news :)

**Comment by haucongle** [comment]
I use Angular 8.2.1 and this problem is still happening. Did you fix this?

**Comment by JoostK** [comment]
@haucongle Please use 9.0.0-next.2 for the Ivy preview.
