### ISSUE TITLE
Wrong route guard (CanActivate) executed

### ISSUE THREAD

**Issue by olaf89** [angular/angular#31549]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Description

Not activated route guard is executed.
I have following router structure:

/a/configuration
/dashboard

Where configuration is a lazy loaded module defined as below. When i navigate to dashboard configuration canActivate guard is being executed, which causes app user to be navigated to error page.

```
{
    path: 'configuration',
    loadChildren: () =>
      import('./configuration/configuration.module').then(
        m => m.ConfigurationModule
      )  
}

ConfigurationModule.ts

RouterModule.forChild([
 {
    path: '',
    component: ConfigurationComponent,
    canActivate: [RoleGuard],
    data: {
      roles: MyRole
    }
  }
])
```

When {path: ''} is being changed to something not empty the guard is not longer executed.

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.1.0
Node: 11.4.0
OS: darwin x64
Angular: 8.2.0-next.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0
@angular/cdk                      8.0.2
@angular/cli                      8.1.0
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.0.2
@ngtools/webpack                  8.1.0
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.5.2
typescript                        3.5.2
webpack                           4.35.2
</code></pre>

**Anything else relevant?**

**Comment by santoshyadav198613** [comment]
Can you provide reproduction to check.

**Comment by olaf89** [comment]
My bad I got ConfigurationModule imported in AppModule.
