### ISSUE TITLE
Virus "Atc4.detection" with Angular CLI and node.js

### ISSUE THREAD

**Issue by leviathan009** [angular/angular#31548]
Hi!

My Bitdefender installation issued a "Atc4.detection" virus found for "nodejs.exe" on the following occasions:

- When I installed node.js (downloaded from nodejs.org, checked sha256 sums, checked on virustotal.com, both fine)
- When I installed angular cli (npm i -g @angular/cli)
- When I created a new project (ng new foobar).

On an equivalent machine of mine this issue does not occur. 

Has anyone the same problem or might this be specific to my machine?

OS: Windows 10 Home Version 1903
Bitdefender Build: 23.0.24.120, Engine 7.81578

**Comment by ericmartinezr** [comment]
As suggested in the issue you opened in node's repo (https://github.com/nodejs/help/issues/2012) this should be fixed in Bitdefender's side

**Comment by leviathan009** [comment]
Bitdefender did reply and they recommended to release the file from virus quarantine and use it regularily.
So...here I go I guess.
