### ISSUE TITLE
Import error, can't find file: ./svg.component.svg

### ISSUE THREAD

**Issue by liheb** [angular/angular#31558]
![Capture](https://user-images.githubusercontent.com/52902620/61194770-e1f68400-a6ed-11e9-9fda-9c5a85156e08.PNG)
![Capture](https://user-images.githubusercontent.com/52902620/61194776-e7ec6500-a6ed-11e9-9bce-f42873e0274b.PNG)

# 📚 Docs or angular.io bug report

### Description

 Import error, can't find file:
./svg.component.svg

### What's the affected URL?**
 https://stackblitz.com/angular/rxrlyneyjmn

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by santoshyadav198613** [comment]
Duplicate of #31537
