### ISSUE TITLE
Microsoft Edge compat

### ISSUE THREAD

**Issue by csuwildcat** [angular/angular#3155]
Hey there Angularians,

I am working on assessing, cataloging, and triaging library compat with Microsoft Edge. Do you know the version compat range for Angular in Edge? Are all versions fully operable in Edge? Also, do you have any bugs that block features or compat I can help with or escalate?

**Comment by mhevery** [comment]
it should work with edge. File specific issues if you see any.

**Comment by csuwildcat** [comment]
Do you have any tests or verification mechanisms I can check for this? We're trying to engage as a service to lib authors, so I'd like to get as much info as you have, if that's ok.
