### ISSUE TITLE
Running ng update on codebase with projects fails

### ISSUE THREAD

**Issue by Akxe** [angular/angular#31564]
# 🐞 bug report

### Affected Package
@angular-cli

### Is this a regression?

No, yet it is part of `ng update`.

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
Updating code with project(s) results in updating only its `.specs.ts` files...

## 🔥 Exception or Error
All `.spec.ts` files and files in `src` get updated, but none of the files within `projects` folder.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
7.x => 8.1.1
</code></pre>

**Anything else relevant?**

I am not sure, ask us...

**Comment by matsko** [comment]
It looks like this issue belongs into the CLI project. Please add it there so that the CLI team can investigate: https://github.com/angular/angular-cli
