### ISSUE TITLE
currency pipe not converting IDR to Rp

### ISSUE THREAD

**Issue by Tipster74743** [angular/angular#31567]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/common

### Is this a regression?
No

### Description
`currencyCode` for 'IDR' is not converting to 'Rp'. Other currencyCodes are working but when passing in Indonesian rupiah, instead of getting 'Rp' it is showing as "IDR".

## 🔬 Minimal Reproduction
![image](https://user-images.githubusercontent.com/16975474/61225945-34807200-a6e7-11e9-9310-7fb54ad33cf6.png)

As you can see, I just passed in IDR on a list that is properly getting and converting EUR. Even just passing in `value | currency:'IDR':symbol` is failing to convert the currency to the proper symbol.

Current syntax being used is:

 <span>{{currency}} {{value | currency:'IDR':'symbol' }}</span>
-->

## 🔥 Exception or Error
None.

## 🌍  Your Environment
```
**Angular Version:**
Angular CLI: 1.6.8
Node: 8.16.0
OS: darwin x64
Angular: 5.2.9
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/animations: 5.2.11
@angular/cdk: 5.2.5
@angular/cli: 1.6.8
@angular/material: 5.2.5
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.6.2
webpack: 3.10.0
```

**Comment by trotyl** [comment]
It's the expected behavior, [in `symbol` it's defined to be `IDR` and in `symbol-narrow` it's `Rp`](https://github.com/unicode-cldr/cldr-numbers-full/blob/23c17f05023c33c1a25a4527f1f76fe756d231f8/main/en/currencies.json#L766-L771):

```json
{
  "displayName": "Indonesian Rupiah",
  "displayName-count-one": "Indonesian rupiah",
  "displayName-count-other": "Indonesian rupiahs",
  "symbol": "IDR",
  "symbol-alt-narrow": "Rp"
}
```

If you strongly believe that CLDR is wrong, please report to http://cldr.unicode.org/index/bug-reports

**Comment by QuantariusRay** [comment]
I think you're right @trotyl. Looks like I missed that. Thanks for the clarification.
