### ISSUE TITLE
Angular Hybrid App - Upgraded Component with Template Function not receiving $element or $attrs

### ISSUE THREAD

**Issue by bamblack** [angular/angular#31565]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/upgrade/static

### Is this a regression?

Not sure

### Description
An upgraded component that uses a template function doesn't receive the `$element` or `$attrs` arguments

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-hybrid-upgrade-aq2wkx?file=ng1%2Fng1-demo.component.ts

## 🌍  Your Environment

**Angular Version:** 
<pre><code>
Angular CLI: 7.3.0
Node: 8.14.0
OS: darwin x64
Angular: 7.2.0
... common, compiler, core, platform-browser
... platform-browser-dynamic, upgrade

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.0
@angular-devkit/core         7.3.0
@angular-devkit/schematics   7.3.0
@angular/animations          7.2.5
@angular/cdk                 7.3.2
@angular/cli                 7.3.0
@angular/forms               7.2.4
@angular/material            7.3.2
@angular/router              7.2.3
@schematics/angular          7.3.0
@schematics/update           0.13.0
rxjs                         6.4.0
typescript                   3.2.2
</code></pre>

**AngularJS Version:** 1.7.2

**Comment by gkalpak** [comment]
This is similar to #6715 and #22824. See there (esp. https://github.com/angular/angular/issues/6715#issuecomment-331996391 and https://github.com/angular/angular/issues/22824#issuecomment-374262127) for more details.

The bottom line is that `$attrs` is probably not going to be supported and will remain a known limitation. Supporting `$element` should be fairly straight forward, I believe. We would basically need to pass `this.$element` [here][1] and eventually pass it to the template function.

##
I am leaving this open as a feature request to support `$element` in template functions, but it is not a high priority.
I would be more than happy to help and guide anyone interested in implementing this :wink:

[1]: https://github.com/angular/angular/blob/12fd06916bd78f8e282af960db40f07fea221e6b/packages/upgrade/src/common/src/upgrade_helper.ts#L117

**Comment by bamblack** [comment]
That's what I figured, I'd be more than happy to take a stab at this once I get some free time!

**Comment by bamblack** [comment]
Opened #31637 for this
