### ISSUE TITLE
start and stop a gif

### ISSUE THREAD

**Issue by Thami747** [angular/angular#31562]
I would like to know if there is a way to start(play) and stop a gif when required.
I would like to play a gif for x-number of seconds and be able to stop it.

**Comment by ericmartinezr** [comment]
Srsly?...

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
