### ISSUE TITLE
Binding a model to div [innertext] throws error

### ISSUE THREAD

**Issue by bryantharpe** [angular/angular#3157]
I'm getting an error binding a div to [innertext]="model.description in one of my templates.

If I change it to {{model.description}} it works fine, so I assume I'm binding to the wrong property but, thats the property name I would think to choose. I've also tried innerText, textcontent, and textContent.

Is there some other field I should be using fine. I saw it should just use the dom attribute associated with it.

#### Error
"Can't bind to 'innertext' since it isn't a know property of the 'div' element and there are no matching directives with a corresponding property"

#### Template
````html
<div>
    <a [router-link]="['/UpdateProducts', {'productId':model.productId}]" class="link" [text]="model.name"></a>
    <div [innertext]="model.description"></div>
</div>
````

#### Model
````javascript
interface Product {
    productId: string;
    name: string;
    description: string;
}
````

#### Controller Class
````javascript
@Component ({
    selector: 'product-item',
    properties: [
        'model'
    ]
})
@View({
    templateUrl: 'components/product-item/product-item.html',
    directives: [RouterLink]
})
export class ProductItem {
    model: Product;

    constructor() {

    }
}
````

**Comment by bryantharpe** [comment]
Actually, closing this. Assume would likely cause browser issues anyways doing that.

**Comment by pkozlowski-opensource** [comment]
@bryantharpe you need to remember that HTML is not case-sensitive so if you want to bind to properties with mixed case you need to use the snake-case to dashCase conversion. In short: `<div [inner-text]="model.description"></div>` should work (but in this case doing `<div>{{model.description}}</div>` is probably easier / better).

**Comment by bryantharpe** [comment]
Thanks @pkozlowski-opensource totally forgot about trying to flip it over to inner-text. Thanks for the tip. That said, agree that binding to inner-text is odd anyways. I changed it over to the {{prop}} syntax.
