### ISSUE TITLE
Forms does not set option selected attribute on select elements.

### ISSUE THREAD

**Issue by michaeljota** [angular/angular#31589]
# 🐞 bug report

### Affected Package

The issue is caused by package `@angular/forms`

### Is this a regression?

 No, I don't think it ever worked.

### Description

When using Forms, either template or reactive, none of the `option` elements inside a `select` element is marked as `selected`. Because how Angular does the binding, this works most of the time, but doing a simple `reset` on the forms, passing a value for the form, would make the UI to display the first `option` regardless the value of the control. 

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-option-not-selected

## 🔥 Exception or Error
<pre><code>
No error
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |  /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.0
Node: 10.16.0     
OS: win32 x64     
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0
@angular/cdk                      8.0.2
@ngtools/webpack                  8.1.0
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Anything else relevant?**

Workaround: 

Bind the `selected` attribute with an expression that resolves either true, if the value control if the same of the form model, or null otherwise. 

`[attr.selected]="form.value.name === optionValue || null"`

That should be handled by Angular forms by default.

**Comment by michaeljota** [comment]
@AndrewKushnir Looking at the source code, seems like there a directive option for each, single select elements, and multiple select elements. In `SelectMultipleControlValueAccessor`, option seems to have a function that set the property to true or false. However, this function does not actually alter any of the properties of the option. [Source](https://github.com/angular/angular/blob/master/packages/forms/src/directives/select_multiple_control_value_accessor.ts#L279)

May I ask, why use `Render2` instead of `HostBinding` for this? As I see it, it would only help in case this option have no a `select` element with a Select directive associated.

**Comment by michaeljota** [comment]
Looking around, seems like a Component/Directive can not destroy itself. (#18673). If that were to be supported, this directive could destroy itself if there is not `select` element with a Select directive associated. (Isolated form elements).

**Comment by atscott** [comment]
It appears this behaves as expected. The `selected` attribute ["Specifies that an option should be pre-selected when the page loads"](https://www.w3schools.com/tags/tag_option.asp) and isn't meant to track the currently selected item. If you still feel there is an issue, please provide further details in a new issue.

**Comment by michaeljota** [comment]
I see. But, if it should be used to pre-selected items only, Angular is not even doing that. Because then, the first selected item should have that property, shouldn't it?

**Comment by michaeljota** [comment]
Also, in the case a Form gets reset, what should the behavior in that case? I think the value should fallback to the pre-selected item, the one that should have the `selected` attribute.
