### ISSUE TITLE
Does not use HTTP/2 for all of its resources

### ISSUE THREAD

**Issue by ayoubkhan558** [angular/angular#31583]
**I want to serve all my assets in http2**
Em suing Angular7 with ionic 4.

![image](https://user-images.githubusercontent.com/20210961/61278023-d0d07480-a7cc-11e9-9a40-f93e5f6c3571.png)

**What I can do?**

**Comment by gkalpak** [comment]
This is related to the server you use and its configuration. It has nothing to do with Angular.
I would suggest looking at the documentation or asking in support forums specific to the server you are using.
