### ISSUE TITLE
Downgraded component example

### ISSUE THREAD

**Issue by ecureuilpop** [angular/angular#31584]
# 📚 Docs or angular.io bug report

### Description

Where is a clear example of downgraded component with outputs/inputs in angular io ?

## 🔬 Minimal Reproduction

https://angular.io/api/upgrade/static/downgradeComponent#downgradecomponent

### Reproduction Steps**
Read the doc

### Expected vs Actual Behavior**
Expected: Having a code repository with a working code
Actual:
 // This directive will act as the interface to the "downgraded" Angular component
ng1AppModule.directive('ng2Heroes', downgradeComponent({component: Ng2HeroesComponent}));

**Comment by gkalpak** [comment]
BTW, there is such an example in the [Upgrade guide][1]. Maybe we should link to it?

[1]: https://angular.io/guide/upgrade#using-angular-components-from-angularjs-code

**Comment by ajitsinghkaler** [comment]
@kapunahelewong need any help on this.

**Comment by kapunahelewong** [comment]
Sure, @ajitsinghkaler! It looks like you could just link to it from the api doc. If you submit a PR, will you tag me? Thank you!!
