### ISSUE TITLE
Auto-Emitting @Output-Variables

### ISSUE THREAD

**Issue by wottpal** [angular/angular#31582]
# 🚀 feature request

### Relevant Package
This feature request is for `@angular/core`

### Description
If I have a variable which is an `@Output` as well I often have code code cluttered like:

```js
this.isLoading = true
this.isLoadingChange.emit(true)
this.isLoadingError = false
this.isLoadingErrorChange.emit(false)

observable$.subscribe(
  () => {
    // ...
    this.isLoading = false
    this.isLoadingChange.emit(false)
  }, (error) => {
    // ...
    this.isLoading = false
    this.isLoadingChange.emit(false)
    this.isLoadingError = true
    this.isLoadingErrorChange.emit(true)
  }
)
```

My first approach to make this more DRY was creating setter/getter-methods for `isLoading` and `isLoadingChange` which automatically emit on `set`. This quickly became unsatisfying as a lot of boilerplate-code is needed for this solution as well:

```js
@Output() isLoadingChange = new EventEmitter<boolean>()
private _isLoading
public get isLoading(): boolean { return this._isLoading }
public set isLoading(isLoading: boolean) { 
  this._isLoading = isLoading
  this.isLoadingChange.emit(isLoading)
}
```

(For the sake of simplicity this is only the example for one variable.)

### Describe the solution you'd like

Disclaimer: I really have no experience of crafting new language-features in such a highly complex environment.

I would like a way of defining `@Output`s to emit automatically when their counterpart variable (without `Change` suffix) is being changed. The idea for the syntax I came up with is inspired by the options-object I can pass to the `@ViewChild`-decorator.

```js
public isLoading = true
// Or: @Input() isLoading = true
@Output('isLoading', { emitOnUpdate: true }) isLoadingChange = new EventEmitter<boolean>()
```

#### Notes

* Optionally another option `emitOnlyOnChange` could ensure that any value value is only emitted if it's not equal to its predecessor (`===`).
* Optionally another option `updateAsync` could ensure that the private assignment `this._isLoading = isLoading` is executed asynchronously. (Just like if you pass `true` to the `EventEmitter`-constructor.

Best regards, 
Dennis

**Comment by Airblader** [comment]
My main concern with this request lies in the fact that there is (AFAICT) no way to have type safety with regards to the referenced class member existing or being of the correct type.

There's also another way:

```
export class FooComponent implements OnInit {
    @Output public loadingChange = new EventEmitter<boolean>();
    private loading: boolean;

    public ngOnInit(): void {
        // Don't forget to unsubscribe
        this.loadingChange.subscribe(loading => this.loading = loading);
    }

    // Or if needed in the template even just `loadingChange | async`, you might not even
    // need the local variable at all
}
```

Small note: historically, it was recommended not to treat `@Output` as an observable as this was considered to be an implementation detail. However, the Angular team has stated that this is no longer true.

I have written many components and have not really ever needed to have the state both locally and in an output unless it was also an input, in which case this issue is related to #25036.
