### ISSUE TITLE
Angular PWA not load all files from cache

### ISSUE THREAD

**Issue by michaelholzknecht** [angular/angular#31581]
Hello,

I'am working on a Angular 8.1.0 PWA and when I test it offline on a device the .svg and font files got not loaded from the cache – png files work fine! If i check it with Chrome inspect the files are listed in "Application -> Cache Storage" but the service worker can not load it.

Here the error from the console.log

`ngsw-worker.js:596 Uncaught (in promise) Error: Response not Ok (fetchAndCacheOnce): request for https://xxx.com/assets/pfeil-full-rechts.svg returned response 504 Gateway Timeout`

Here a screenshot from the Chrome Inspect Tool

![screen_shot_1](https://user-images.githubusercontent.com/1126086/61271694-9a333380-a7a5-11e9-86e8-5ff2d4c36cbb.jpg)

And here the ngsw-config.json

```
{
  "$schema": "./node_modules/@angular/service-worker/config/schema.json",
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "resources": {
        "files": [
          "/favicon.ico",
          "/index.html",
          "/*.css",
          "/*.js"
        ]
      }
    }, {
      "name": "assets",
      "installMode": "prefetch",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/assets/**",
          "/*.(eot|svg|cur|jpg|png|webp|gif|otf|ttf|woff|woff2|ani)"
        ]
      }
    }
  ]
}
```
The interesting thing is that also the preview from the cache works, f.e. if i select in the Dev Tool the '/assets/pfeil-links.svg' from the Cache Storage the preview works (look at the 
screenshot)

The version of Chrome on my device is 75.0.3770

Thanks for your help!

**Comment by gkalpak** [comment]
It should work as expected. We cache both SVG files and fonts in angular.io (which also uses `@angular/service-worker`) and they work fine offline.

So, it must be something in your setup. What does [/ngsw/state][1] show after a failed SVG request?
(Is there any chance the served files would be different than the ones found in the `dist/` directory after `ng build` (e.g. optimized, normalized whitespace, etc.)?

##
Closing the issue, since I don't think this is an issue in `@angular/service-worker`, but feel free to continue the discussion below.

[1]: https://angular.io/guide/service-worker-devops#locating-and-analyzing-debugging-information

**Comment by michaelholzknecht** [comment]
Thanks for your fast replay ... here the log form ngsw/state

```
NGSW Debug Info:

Driver state: NORMAL ((nominal))
Latest manifest hash: 6ee39f03940d7c805553bc705bbdba7d4eacdca5
Last update check: never

=== Version 6ee39f03940d7c805553bc705bbdba7d4eacdca5 ===

Clients: 8de3c650-1240-458c-aaf3-dd6708f314db, 5ed26b1c-ad7e-4bde-aa9d-b6d8f9d9d675

=== Idle Task Queue ===
Last update tick: 14s113u
Last update run: 9s113u
Task queue:


Debug log:

[20s888u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://example.com/ngsw.json?ngsw-cache-bust=0.773384249347199)
[20s887u] Check for update aborted. (Client or server offline.) 
[20s777u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://example.com/ngsw.json?ngsw-cache-bust=0.051138463446643856)
[20s800u] Check for update aborted. (Client or server offline.) 
[9s126u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://example.com/ngsw.json?ngsw-cache-bust=0.7871519333735213)
[9s126u] Check for update aborted. (Client or server offline.) 
```

**Comment by michaelholzknecht** [comment]
I checked the files names in the dist/assets folder, they seem to be ok. Here another log ... 

```
NGSW Debug Info:

Driver state: NORMAL ((nominal))
Latest manifest hash: 6ee39f03940d7c805553bc705bbdba7d4eacdca5
Last update check: never

=== Version 6ee39f03940d7c805553bc705bbdba7d4eacdca5 ===

Clients: a3438bb3-1a63-4e1f-bbd4-8041eceac873, 1ac062c6-5ab3-4a74-8331-278d789e3b1c

=== Idle Task Queue ===
Last update tick: 10s587u
Last update run: 5s587u
Task queue:


Debug log:

[32s671u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://example.com/manifest.webmanifest)
[23s540u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://example.com/ngsw.json?ngsw-cache-bust=0.2585365396423742)
[23s540u] Check for update aborted. (Client or server offline.) 
[23s420u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://example.com/ngsw.json?ngsw-cache-bust=0.4746510275857012)
[23s419u] Check for update aborted. (Client or server offline.) 
[13s226u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://example.com/manifest.webmanifest)
[5s575u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://example.com/ngsw.json?ngsw-cache-bust=0.30748491971917713)
[5s574u] Check for update aborted. (Client or server offline.) 
```

**Comment by gkalpak** [comment]
Is this right after a failed SVG fetch? I would expect the SVG url to be in the logs.

**Comment by michaelholzknecht** [comment]
yes, i started the pwa in the browser offline and when navigated to the page where the svg's are not loadet, I entered the /ngsw/state to the route ...

**Comment by michaelholzknecht** [comment]
I also tried, that I uploaded the assets folder from the src/assets not from the dist/assets to be sure the the filenames are ok.

**Comment by michaelholzknecht** [comment]
Now I tried it it with a complete fresh installation and still the same problem, here the steps I did:

-> ng new testproject
-> ng add @angular/pw
-> I replaced the Angular Demo logo with the a downloaded svg file
-> <img width="300" alt="Angular Logo" src="./assets/logo.svg">
-> ng build --prod
-> uploaded the dist folder to the server
-> visit the page and install the pwa
-> the svg image is showing up

-> close the app
-> go offline
-> start the app and the svg is not loading (same error)

has anyone the same problem? Could it maybe on problem with the provider or the ssl?

**Comment by gkalpak** [comment]
It would be more useful to see `/ngsw/state` after loading the page in online mode.
I would also compare the _**served**_ SVG file with the one in `dist/` after `ng build`. I've seen file contents being changed (for normalization or optimization) by FTP clients, servers, HTTP proxies.

I would be happy to take a look at the app if it is somewhere publicly accessible (but other than that, I don't know how else to help).

**Comment by michaelholzknecht** [comment]
Hello George,

thanks for you help – here the domain where I put the test project https://www.lola-safety.info/

**Comment by gkalpak** [comment]
I took a look and I couldn't figure out what is going on 😞

When I build and serve the project locally, everything works fine. On `lola-safety.info`, however, nothing seems to work offline (not just the SVG, but even the scripts). For some reason, the requests don't go through the ServiceWorker (but I couldn't figure out why - everything seems to be set up correctly).

@michaelholzknecht, can you verify that building and serving locally works for you too?

**Comment by michaelholzknecht** [comment]
I tested with different situations, always simulate "offline" with the chrome inspect

-> using MAMP Appache Server with self signed ssl  -> works
-> using http-server plugin http://127.0.0.1:8080 -> works but get this error

```
manifest.webmanifest:1 GET http://127.0.0.1:1233/manifest.webmanifest 504 (Gateway Timeout)
manifest.webmanifest:1 Manifest: Line: 1, column: 1, Unexpected token.
```

-> using http-server plugin http://myLocalIp:8080 -> no service worker get installed

I could not test it on my device – it's only tested in chrome on my desktop computer!

**Comment by gkalpak** [comment]
Note that in order for ServiceWorkers to work, the browsers requires a secure host, which means either served over HTTPS or `localhost`. So, `127.0.0.1` or `youLocalIp` should not work over HTTP.

**Comment by michaelholzknecht** [comment]
I think the problem depending on the server, I have put the the test pwa on a different server and there it works. @gkalpak maybe if you have a minute can check if it works here https://www.berlinblockmasters.com/ 

Thanks a lot!

**Comment by gkalpak** [comment]
Yeah, that seems to work fine. From a quick look I don't see any differences (some request headers are slightly different, but nothing that explains the difference in behavior). I wouldn't be surprized if there is also a browser issue involved 🤷‍♂

**Comment by michaelholzknecht** [comment]
Just to finish this issue. I did't figured out where the problem is – also on a different server / device the same problem pops up - it works randomly. So finally I replaced all the svg's to png's or use the svg in a html template.

Thanks for your help and time!
