### ISSUE TITLE
[i18n] Unexpected character "EOF" 

### ISSUE THREAD

**Issue by aguadotzn** [angular/angular#31586]
# 🐞 bug report

### Affected Package
I can not pin-point any package because I'm not sure about it.

### Is this a regression?
I think was not working in previous versions but i'm not sure 100% about it.

### Description
I'm trying to internationalise an application. I create a `<span>` and put several information there. When we have info that starts with '(' the compilation fails.

## 🔬 Minimal Reproduction
You can find small reproduction of the issue here with the same output:
https://stackblitz.com/edit/angular-issue-repro2-u3gnzz

## 🔥 Exception or Error
```
Template parse errors:
@xxx/core: Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.) (" transport {International transport} (Inter)national transport {(Inter)national transport} } </span> [ERROR ->]"): 67
}
</span>
```

## 🌍  Your Environment

**Angular Version:**
<pre>Angular CLI: 7.0.6
Node: 8.11.1
OS: darwin x64
Angular: 7.0.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.6
@angular-devkit/build-angular     0.10.6
@angular-devkit/build-optimizer   0.10.6
@angular-devkit/build-webpack     0.10.6
@angular-devkit/core              7.0.6
@angular-devkit/schematics        7.0.6
@angular/cli                      7.0.6
@ngtools/webpack                  7.0.6
@schematics/angular               7.0.6
@schematics/update                0.10.6
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
<code>

</code></pre>

**Anything else relevant?**
IDE: IntelliJ IDEA
OS: macOS

**Comment by aguadotzn** [comment]
UPDATE: Same problems if the sentence stars with **%**. 

So maybe happen with more characters...

**Comment by petebacondarwin** [comment]
I can see the reproduction on stackblitz but equally I can't find a version of Angular for which this ever worked.

**Comment by sonukapoor** [comment]
@petebacondarwin As discussed offline, I will work on this.
