### ISSUE TITLE
Deno support or Deno rewrite pilot

### ISSUE THREAD

**Issue by inunotaisho26** [angular/angular#31580]
# 🚀 feature request
Would like [Deno](https://deno.land/) runtime support.

### Description
This is a new runtime that has was created by [Ryan Dahl](https://en.wikipedia.org/wiki/Ryan_Dahl), the original creator of [NodeJS](https://nodejs.org/en/). It has several new advantages:

- Use of Promises
- Uses TypeScript out of the box
- no need for node_modules
- uses urls to load dependencies (might be a plus or minus).

**Comment by santoshyadav198613** [comment]
Hi @inunotaisho26 ,
Thanks for this feature request, but remember Angular uses Typescript. This feature request will be a good fit for Typescript but not Angular.

**Comment by trotyl** [comment]
It's spamming.

+ https://github.com/facebook/react/issues/16140
+ https://github.com/vuejs/vue/issues/10274
+ https://github.com/emberjs/ember.js/issues/18204
