### ISSUE TITLE
Expand button regression

### ISSUE THREAD

**Issue by puku0x** [angular/angular#31590]
# 📚 Docs or angular.io bug report

### Description
The expand button is not rendered correctly on mobile since v8.

## 🔬 Minimal Reproduction
See, for example, https://angular.io/guide/displaying-data on mobile device.

### What's the affected URL?**
Every pages using `<aio-toc />`
 https://angular.io/...

### Reproduction Steps**
Go to any page with toc on mobile. 

## 📷Screenshot

| v7 | v8  |
|---|---|
| ![v7 angular io_guide_displaying-data(iPhone 6_7_8 Plus)](https://user-images.githubusercontent.com/2607019/61309804-e75ae800-a82d-11e9-885b-4c9ead008bf3.png) | ![angular io_guide_displaying-data(iPhone 6_7_8 Plus)](https://user-images.githubusercontent.com/2607019/61309793-e3c76100-a82d-11e9-85f1-9698fa09482d.png) |

| v7 | v8  |
|---|---|
| ![IMG_0955](https://user-images.githubusercontent.com/2607019/61310498-6270ce00-a82f-11e9-8e79-a5cdcf98f2b3.PNG)|![IMG_0953](https://user-images.githubusercontent.com/2607019/61310514-6997dc00-a82f-11e9-8ac6-8608f6b17a72.PNG) |

## 🔥 Exception or Error
None

### Browser info
- macOS 10.14.5 Chrome 75.0.3770.100
- iPhone 12.31 Safari

**Comment by puku0x** [comment]
@gkalpak @sjtrimble
The changes in https://github.com/angular/angular/pull/31173 seems to cause this style regression.

**Comment by gkalpak** [comment]
Thx for looking into it, @puku0x. I think it will be fixed by #31533. Can you confirm?

**Comment by puku0x** [comment]
@gkalpak 
I confirmed #31533 solves the problem, thank you!
