### ISSUE TITLE
Migrating to ChangeStrategy.OnPush makes performance even worse.

### ISSUE THREAD

**Issue by 87182485** [angular/angular#31593]
We have a real content Single page application that is not fully adopting `ChangeDectionStragtegy.OnPush`, but after I update the component `ChangeDectionStrategy` to `OnPush`, it makes the performance even worse.

I am comparing by `ChangeDetectionPerfRecord` (ng.profiler.timeChangeDetection)

*** before ***
```
ng.profiler.timeChangeDetection()
platform-browser.js:2216 ran 573 change detection cycles
platform-browser.js:2217 0.87 ms per check
```

*** after ***
```
ng.profiler.timeChangeDetection()
platform-browser.js:2216 ran 862 change detection cycles
platform-browser.js:2217 0.58 ms per check
```

Another extreme case 

*** before ***
```
ng.profiler.timeChangeDetection()
platform-browser.js:2216 ran 150 change detection cycles
platform-browser.js:2217 3.34 ms per check
```

*** after ***
```
ng.profiler.timeChangeDetection()
platform-browser.js:2216 ran 1869 change detection cycles
platform-browser.js:2217 0.27 ms per check
```

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

---

How do you interpret those results to be _slower_? Being able to run more change detection cycles in the same timeframe such that each cycle is shorter in duration, means it is faster, doesn't it?
