### ISSUE TITLE
Routing not working after route from HTML form action.

### ISSUE THREAD

**Issue by deepakpizonesgnr** [angular/angular#31602]
I'm tring to route to angular component from form action but failed to redirect to component with error
`  page can’t be found`
```
var oForm = document.createElement('form');
			oForm.action = (Page URL with hash);
			oForm.method = 'POST';
```

**Comment by santoshyadav198613** [comment]
What are you trying, not clear.

**Comment by deepakpizonesgnr** [comment]
hi @santoshyadav198613 thnks for replying  
 Actually i am using robokassa payment gateway in my project . In the return of successful payment it returns some success url in form action .. but angular do not accept from action .. so  user have to reload the browser  .. for redirect .. 
any solution pls ?

**Comment by deepakpizonesgnr** [comment]
hi @santoshyadav198613 thnks for replying
Actually i am using robokassa payment gateway in my project . In the return of successful payment it returns some success url in form action .. but angular do not accept form action .. so user have to reload the browser .. for redirect ..
any solution pls ?

**Comment by deepakpizonesgnr** [comment]
@santoshyadav198613 angular routing not working when i'm try to load url from form element action

**Comment by deepakpizonesgnr** [comment]
```
<form action="UR/">
</form
```

**Comment by matsko** [comment]
Please follow the Angular issue blueprint when creating new issues. Otherwise we don't know what to fix. Closing.
