### ISSUE TITLE
UpgradeModule AoT not working after update from v6 to v7 (or  v8)

### ISSUE THREAD

**Issue by runeabrahams1** [angular/angular#31603]
# 🐞 bug report

### Affected Package
@angular/upgrade/static
@angular/core (or cli?)
angularjs 1.7.8

### Is this a regression?
Yes. This works in v6 (latest).
Does not work in any version of v7 or v8.

### Description
We got a quite large hybrid app (700+ Components, ~100 angularJs components/directives).
Build it **with AoT** works perfectly in Angular v6, but stops working in v7 or v8.
Building it **without** AoT works in all versions without issues.

The problem is that we get no errors when building with AoT in v7 or v8. The build get stuck at 11% and will stay there even after 50+ hours.

This is the line it get stuck on:
_11% building 13/14 modules 1 active ...epos\Stream\node_modules\less-loader\dist\cjs.js??ref--14-3!C:\Repos\Stream\src\styles.less_

Is there any way to get a more detailed log of what the compiler is trying to do?

I'm out of ideas of how to fix this. I've tried looking at other issues with AoT or UpgradeModule, but none of them quite matches this or helps with my issue.

I've done everything in https://update.angular.io/#6.1:7.0.
We run RxJS 6 without compat, and have removed HttpModule from everything

## 🔬 Minimal Reproduction
This is the problem. I can't reproduce it in a new app with all our third party libs.  Something in out code breaks AoT compilation in version 7 or 8.

## 🌍  Your Environment

I tried v7@latest, v8, v8.1, v8@next

**Angular Version:**
<pre><code>
Angular CLI: 8.2.0-next.0
Node: 10.15.3
OS: win32 x64
Angular: 8.2.0-next.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0-next.0
@angular-devkit/build-angular     0.802.0-next.0
@angular-devkit/build-optimizer   0.802.0-next.0
@angular-devkit/build-webpack     0.802.0-next.0
@angular-devkit/core              8.2.0-next.0
@angular-devkit/schematics        8.2.0-next.0
@angular/cli                      8.2.0-next.0
@ngtools/webpack                  8.2.0-next.0
@schematics/angular               8.2.0-next.0
@schematics/update                0.802.0-next.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.3
</code></pre>

**Comment by gkalpak** [comment]
Thx for the detailed report. This doesn't sounds at all related to `UpgradeModule` though.

Do you have other info indicating this is somehow caused by/related to `UpgradeModule`?
If not, I suggest you ask on the [cli repo][1], since people there are more likely to have useful advice on how to debug the build process.

[1]: https://github.com/angular/angular-cli

**Comment by runeabrahams1** [comment]
@gkalpak You might be right. I just have a feeling it might be something in out angularJS code, so was unsure which repo to use.
I'll close this issue for now and try the CLI repo.
