### ISSUE TITLE
Project config in angular.js file

### ISSUE THREAD

**Issue by sviat9440** [angular/angular#31606]
@angular/cli

It would be nice to be able to dynamically generate a config.

Like
```
module.exports = {
    projects: {
        'my-angular-project': {...}
    }
}
```

Now we have to make a custom script to generate the configuration.

**Comment by matsko** [comment]
Please follow the Angular issue blueprint when creating a new issue. Otherwise we don't know how to reproduce and fix it.

**Comment by gkalpak** [comment]
@matsko, this is a feature request. There is nothing to investigate :wink:
@sviat9440, this feature request should be submitted on the [cli repo][1].

[1]: https://github.com/angular/angular-cli
