### ISSUE TITLE
Angular router hashing

### ISSUE THREAD

**Issue by iamsrk** [angular/angular#31601]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

The {useHash: true} in an angular route, doesn't work properly when on right-clicking and opening in a new tab. The problem is described [here](https://stackoverflow.com/questions/57069202/angular-router-hashing?noredirect=1#comment100663978_57069202).

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by matsko** [comment]
Please follow and fillout the issue blueprint when reporting something. Closing.

**Comment by iamsrk** [comment]
No problem, will follow and report again. Sorry for inconvenience.
