### ISSUE TITLE
ng add @angular/bazel: styles fail to compile

### ISSUE THREAD

**Issue by brunojcm** [angular/angular#31619]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

No.

### Description

1. Make sure you import some styles from an extenal library in your `styles.scss`, like:
```
@import "~bootstrap/scss/bootstrap";
@import '~bootstrap/scss/bootstrap-reboot';
@import '~bootstrap/scss/bootstrap-grid';
```
2. Enable bazel with `ng add @angular/bazel`
3. Run `ng build`

## 🔥 Exception or Error
<pre><code>
$ ng build
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: target //src:prodapp (1 packages loaded, 0 targets configured)
INFO: Analyzed target //src:prodapp (538 packages loaded, 35287 targets configured).
INFO: Found 1 target...
[0 / 22] [Prepa] Expanding template external/build_bazel_rules_nodejs/internal/rollup/terser-wrapped_bin.sh [for host] ... (4 actions, 0 running)
[0 / 22] [Prepa] Creating source manifest for @build_bazel_rules_nodejs//internal/rollup:tsc [for host] ... (6 actions, 0 running)
Slow read: a 26068120-byte read from C:/users/medeb8/_bazel_medeb8/ccghtaa2/external/nodejs/bin/nodejs/node.exe took 18140 ms.
ERROR: C:/users/medeb8/git/Project/solutions/Company/Company.Project.client/src/BUILD.bazel:10:1: SassCompiler src/global_stylesheet.css failed (Exit 65)
Error: Can't find stylesheet to import.
   ╷
40 │ @import '~bootstrap/scss/functions', "~bootstrap/scss/variables";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src\_variables.scss 40:9  @import
  src\styles.scss 2:9       root stylesheet
Target //src:prodapp failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 753.239s, Critical Path: 22.82s
INFO: 1 process: 1 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
C:\Users\medeb8\git\Project\Solutions\Company\Company.Project.Client\node_modules\@bazel\bazel\node_modules\@bazel\bazel-win32_x64\bazel-0.27.0-windows-x86_64.exe failed with code 1.
</code></pre>

## 🌍 Your Environment
<pre><code>
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.1.0
Node: 10.16.0
OS: win32 x64
Angular: 8.1.0
... animations, bazel, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.1.0
@angular/cdk                      8.0.2
@bazel/bazel                      0.27.0
@bazel/hide-bazel-files           0.32.2
@bazel/ibazel                     0.10.3
@bazel/karma                      0.32.2
@bazel/typescript                 0.32.2
@ngtools/webpack                  8.0.6
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

Not that I can think of, but please let me know if you need something.

**Comment by lousley** [comment]
> Hi @brunojcm, thanks for trying Bazel.
> 
> This is somewhat expected, because `~` is not a standard to resolve node modules and quite specific to Webpack, Bazel doesn't make use of webpack and hence it will break code which was rewitten to work for a specific build tool/bundler.
> 
> While for SASS and Less compilers there are plugins/custom importers to mitigate this and make this available to these mentioned compilers, Bazel rules at the moment doesn't offer any functionality to add these to style preprocessor.
> 
> The plugins imports I am referring too are;
> https://www.npmjs.com/package/node-sass-tilde-importer
> https://www.npmjs.com/package/less-plugin-npm-import
> 
> To get this working without the above plugins, you need to reference the bootstrap imports relative to the current scss file.
> 
> Ex:
> 
> ```css-scss
> @import '../../node_modules/bootstrap/scss/functions'
> ```
> 
> Once could also add the `node_modules` directory to the `include_paths` to replace the above import with
> 
> ```css-scss
> @import 'bootstrap/scss/functions'
> ```
> 
> However, `include_paths` is only available when using `sass_binary` and not available in `multi_sass_binary` which is also being using in `@angular/bazel`
> 
> More info about this rules can be found here: https://github.com/bazelbuild/rules_sass
> 
> //cc @alexeagle

How can i add the https://www.npmjs.com/package/node-sass-tilde-importer plugin to bazel?

**Comment by AndrewKushnir** [comment]
Hi,

Bazel builder and schematics were deprecated some time ago, so I'm closing this ticket. You can find more information about this on the [Deprecated APIs and features page](https://angular.io/guide/deprecations#bazel-builder-and-schematics) and in the [migration guide](https://github.com/angular/angular/blob/master/packages/bazel/src/schematics/README.md).

Thank you.
