### ISSUE TITLE
 Compilation error in Ivy mode with 8.1.2

### ISSUE THREAD

**Issue by sergey-morenets** [angular/angular#31616]
# 🐞 bug report

### Is this a regression?

No

### Description

I have a working Angular v8 application that uses ng2-device-detector dependency. I tried to upgrade to 8.1.2 to verify that Ivy mode works properly:

"angularCompilerOptions": {
    "enableIvy": true
  }

But in Ivy mode I get the error message. In non-Ivy mode everything works fine.

## 🔬 Minimal Reproduction

ng build --prod

## 🔥 Exception or Error
<pre><code>
ERROR in ENOENT: no such file or directory, open 'node_modules/ng2-device-detector/ng2-device-detector.js'
</code></pre>

## 🌍  Your Environment

<pre><code>
Angular CLI: 8.1.2
Node: 12.3.1
OS: win32 x64
Angular: 8.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.2
@angular-devkit/build-angular     0.801.2
@angular-devkit/build-optimizer   0.801.2
@angular-devkit/build-webpack     0.801.2
@angular-devkit/core              8.1.2
@angular-devkit/schematics        8.1.2
@angular/cdk                      7.3.7
@angular/material                 7.3.7
@ngtools/webpack                  8.1.2
@schematics/angular               8.1.2
@schematics/update                0.801.2
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Comment by sergey-morenets** [comment]
I tried to migrate from ng2-device-detector to ngx-device-detector and this error gone.
However new strange error happened: ERROR in Node does not exist: /node_modules/ngx-highlightjs
Although I have this folder (node_modules/ngx-highlightjs)

**Comment by JoostK** [comment]
Hi @sergey-morenets,

Could you try `ngx-device-detector` again with `9.0.0-next.14` and let us know if that has resolved the "Node does not exist" error? There have been quite some fixes in that area so I am fairly confident this problem has been resolved. Thanks!

**Comment by sergey-morenets** [comment]
Hi @JoostK 

I have some other issues with Ivy but this issues can't be reproduced now.
