### ISSUE TITLE
ng add @angular/bazel: build fail on peer dependencies

### ISSUE THREAD

**Issue by brunojcm** [angular/angular#31617]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

No.

### Description

1. Make sure you have a dependency that has a transitive peer dependency, like `bootstrap`, whose `popper.js` is a peer dependency of.
2. Enable bazel with `ng add @angular/bazel`
3. Run `ng build`

## 🔥 Exception or Error
<pre><code>
$ ng build
...
INFO: Call stack for the definition of repository 'npm' which is a npm_install (rule definition at C:/users/medeb8/_bazel_medeb8/ccghtaa2/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:294:15):
 - C:/users/medeb8/_bazel_medeb8/ccghtaa2/external/build_bazel_rules_nodejs/defs.bzl:77:5
 - C:/users/medeb8/git/Project/solutions/Company/Company.Project.client/WORKSPACE:64:1
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
        File "C:/users/medeb8/_bazel_medeb8/ccghtaa2/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 292
                _create_build_files(repository_ctx, "npm_install", node, r...)
        File "C:/users/medeb8/_bazel_medeb8/ccghtaa2/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 146, in _create_build_files
                fail(("generate_build_file.js failed:...)))
generate_build_file.js failed:
STDOUT:

STDERR:
Could not find peer dependency 'popper.js' of 'bootstrap'
ERROR: error loading package '': Encountered error while reading extension file 'install_bazel_dependencies.bzl': no such package '@npm//': Traceback (most recent call last):
        File "C:/users/medeb8/_bazel_medeb8/ccghtaa2/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 292
                _create_build_files(repository_ctx, "npm_install", node, r...)
        File "C:/users/medeb8/_bazel_medeb8/ccghtaa2/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 146, in _create_build_files
                fail(("generate_build_file.js failed:...)))
generate_build_file.js failed:
STDOUT:

STDERR:
Could not find peer dependency 'popper.js' of 'bootstrap'
ERROR: error loading package '': Encountered error while reading extension file 'install_bazel_dependencies.bzl': no such package '@npm//': Traceback (most recent call last):
        File "C:/users/medeb8/_bazel_medeb8/ccghtaa2/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 292
                _create_build_files(repository_ctx, "npm_install", node, r...)
        File "C:/users/medeb8/_bazel_medeb8/ccghtaa2/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 146, in _create_build_files
                fail(("generate_build_file.js failed:...)))
generate_build_file.js failed:
STDOUT:

STDERR:
Could not find peer dependency 'popper.js' of 'bootstrap'
INFO: Elapsed time: 465.835s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
</code></pre>

## 🌍 Your Environment
<pre><code>
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.1.0
Node: 10.16.0
OS: win32 x64
Angular: 8.1.0
... animations, bazel, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.1.0
@angular/cdk                      8.0.2
@bazel/bazel                      0.27.0
@bazel/hide-bazel-files           0.32.2
@bazel/ibazel                     0.10.3
@bazel/karma                      0.32.2
@bazel/typescript                 0.32.2
@ngtools/webpack                  8.0.6
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

Installing the peer dependency seems to "solve" the problem and the build passes this point, build standard `ng build` doesn't require that, so I thought it would be worth reporting.

**Comment by brunojcm** [comment]
> on standard npm install or yarn install these are warnings instead of errors.

Not only on those, but also standard `ng build` works whereas its bazel counterpart is currently failing.

Unless it's at least documented somewher, we will have a lot of people seeing their builds failing after migration.

**Comment by Toxicable** [comment]
this is the tracking issue for this one https://github.com/bazelbuild/rules_nodejs/issues/1162

**Comment by AndrewKushnir** [comment]
Hi,

Bazel builder and schematics were deprecated, so I'm closing this ticket. You can find more information about this on the [Deprecated APIs and features page](https://angular.io/guide/deprecations#bazel-builder-and-schematics) and in the [migration guide](https://github.com/angular/angular/blob/master/packages/bazel/src/schematics/README.md).

Thank you.
