### ISSUE TITLE
Docs: Reactive Forms "Step 2: Generating and importing a new form control"  NameEditorComponent  has no constructor or ngOnInit()

### ISSUE THREAD

**Issue by JoeCodeswell** [angular/angular#31612]
# 📚 Docs or angular.io bug report

### Description

In the Docs for Reactive Forms [Step 2: Generating and importing a new form control](https://angular.io/guide/reactive-forms#step-2-generating-and-importing-a-new-form-control)  the NameEditorComponent  has no constructor or ngOnInit() method.

As a person just starting with Angular 8, using this guide is very confusing.

Can this guide please be updated to Angular 8 syntax?

### What's the affected URL?**
https://angular.io/guide/reactive-forms#step-2-generating-and-importing-a-new-form-control

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Browser info
i am using vscode on windows.

**Comment by Airblader** [comment]
Why do you think it needs either? Classes don't require explicit constructors, but that is just Javascript and has nothing to do with Angular.

Merging declaration and initialization of class members is a completely normal language feature and also found in most syntactically similar languages.

**Comment by JoeCodeswell** [comment]
Hi @Airblader . Thanks for the reply. 
I don't understand TypeScript/Angular 8 enough to know what it should look like. 
Re "Angular 8 syntax": I know that when i used the Ang8 CLI to `ng generate component` the resulting .ts file came back with a constructor() & ngOnInit() member. 
Where and how do i declare & initialize "name" as referred to in the example? 

Thanks for the help.
Love and peace,
Joe

**Comment by Airblader** [comment]
> I know that when i used the Ang8 CLI to ng generate component the resulting .ts file came back with a constructor() & ngOnInit() member.

Yes, they're just there as boilerplate. Neither one is technically required, `class Foo {}` is a valid class definition.

> Where and how do i declare & initialize "name" as referred to in the example?

I don't understand the question – the example code on the page shows how to do it:

```
export class NameEditorComponent {
  name = new FormControl('');
}
```

This is standard ES6 class syntax and has nothing to do with Angular, which is also why I'd be hesitant to change it – personally, I believe that no one should try to learn Angular if they don't yet understand JavaScript syntax. Just my opinion, of course.

**Comment by jbogarthyde** [comment]
This seems to be a TypeScript issue, not an Angular doc issue. 
Joe, I'm closing it, please feel free to re-open it if you have more to say.

**Comment by JoeCodeswell** [comment]
Hi Judy and Ingo,

After MUCH AVOIDABLE experimentation, I found an answer to my question that WORKS.

Accordingly, to reflect the Angular 8 CLI initialized component TypeScript code, I suggest you folks update the referenced docs to show the following:
```
import { Component } from '@angular/core';
import { FormControl } from '@angular/forms';

@Component({
  selector: 'app-name-editor',
  templateUrl: './name-editor.component.html',
  styleUrls: ['./name-editor.component.css']
})
export class NameEditorComponent {

  name = new FormControl('');

  constructor() { }
  ngOnInit() {
  }
}
```
Thank you for your kind attention. 

Love and peace,

Joe

**Comment by Airblader** [comment]
I still don't understand. That's exactly the same code as the first code block on the docs page you reference, except that you have an empty constructor and ngOnInit, neither one of which you need.

**Comment by JoeCodeswell** [comment]
I have another component that i have that is similar to the component under discussion.

The following ,ts code causes an error. `Date: 2019-07-25T18:56:20.688Z  ... ERROR ... Property 'ngOnInit' is missing in type 'LoginComponent' but required in type 'OnInit'.`
```
import { Component, OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})

export class LoginComponent implements OnInit {
  name = new FormControl('');
  email = new FormControl('');
  updateName() {
    this.name.setValue('Nancy');
    this.email.setValue('n@n.com');
  }

  // constructor() {

  // }

  // ngOnInit() {
  // }

}
```
When I uncomment the constructor & ngOnInit(), the code works fine. 

Thanks for the help.

Love and peace,
Joe

**Comment by Airblader** [comment]
That's because of `implements OnInit`, which is there to enforce that you actually have that method. If you don't want to implement the method, remove the interface as well.

That truly is just how TypeScript works, though, and unrelated to Angular.
