### ISSUE TITLE
Ivy issue with ng2-pdfjs-viewer

### ISSUE THREAD

**Issue by kccsf** [angular/angular#31629]
# 🐞 bug report

### Is this a regression?

 Yes, works with Ivy switched off

### Description

 A project with ng2-pdfjs-viewer added to it will fail at runtime with Angular Ivy enabled.

## 🔬 Minimal Reproduction

 https://github.com/kccsf/ng2-pdfjs-viewer-ivy-test

## 🔥 Exception or Error
<pre><code>

 core.js:24459 Uncaught TypeError: Cannot read property 'id' of undefined
    at registerNgModuleType (core.js:24459)
    at core.js:24470
    at Array.forEach (<anonymous>)
    at registerNgModuleType (core.js:24470)
    at new NgModuleFactory (core.js:24574)
    at compileNgModuleFactory__POST_R3__ (core.js:27900)
    at PlatformRef.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.PlatformRef.bootstrapModule (core.js:28108)
    at Module../src/main.ts (main.ts:11)
    at __webpack_require__ (bootstrap:79)
    at Object.0 (main.ts:12)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.2.0-next.1
Node: 10.15.3
OS: win32 x64
Angular: 8.2.0-next.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0-next.1
@angular-devkit/build-angular     0.802.0-next.1
@angular-devkit/build-optimizer   0.802.0-next.1
@angular-devkit/build-webpack     0.802.0-next.1
@angular-devkit/core              8.2.0-next.1
@angular-devkit/schematics        8.2.0-next.1
@angular/cli                      8.2.0-next.1
@ngtools/webpack                  8.2.0-next.1
@schematics/angular               8.2.0-next.1
@schematics/update                0.802.0-next.1
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.35.3
</code></pre>

**Anything else relevant?**

**Comment by abarghoud** [comment]
Hi there, I am taking this issue

**Comment by abarghoud** [comment]
So, after searching, it seems related to [#14594](https://github.com/angular/angular-cli/issues/14594), 
Modules in libraries are not compiled the same way ivy does or normal modules in application

**Comment by petebacondarwin** [comment]
The ng2-pdfjs-viewer has two problems that need fixing for it to be compatible with v9 (let alone ivy).
This PR should fix it https://github.com/intbot/ng2-pdfjs-viewer/pull/55/files
