### ISSUE TITLE
Dependency injection with @Self() is broken in tests

### ISSUE THREAD

**Issue by jonrimmer** [angular/angular#31632]
# 🐞 bug report

### Affected Package

@angular/core

### Is this a regression?

Unknown

### Description

The `@Self()` decorator does not work in tests to inject dependencies from directives placed on a component by a test-specific wrapper component.

E.g. if a I have a custom form control that injects `NgControl` using the `@Self()` decorator, as recommended by the Angular team:

```ts
constructor(@Self() ngControl: NgControl) {
  ngControl.valueAccessor = this;
}
```

And I try to use this in a test wrapper component:

```ts
@Component({
  template: `
    <form>
      <app-hello [formControl]="ctrl" name="test"></app-hello>
   </form>
 `
})
class TestWrapper {
  ctrl = new FormControl(''); 
}

describe('HelloComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [FormsModule, ReactiveFormsModule],
      declarations: [
        HelloComponent,
        TestWrapperComponent
      ],
    }).compileComponents();
  }));
});
```

Then test will fail due to an inability to inject NgControl.

## 🔬 Minimal Reproduction

https://github.com/jonrimmer/di-is-broken

If you run the app, you will see that it works fine.

If you run the test, you will see that it fails due to an inability to inject `NgControl` into the custom form control.

## 🔥 Exception or Error
<pre><code>
Chrome 75.0.3770 (Mac OS X 10.14.5) HelloComponent should create FAILED
	No provider for NgControl ("[ERROR ->]<app-hello></app-hello>"): @0:0
	error properties: Object({ ngSyntaxError: true, ngParseErrors: [ No provider for NgControl ("[ERROR ->]<app-hello></app-hello>"): @0:0 ] })

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.6
Node: 12.4.0
OS: darwin x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cli                      8.0.6
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

**Comment by mhevery** [comment]
Can you simplify the example and turn it into stackblitz. We have limited amount of time, and we can't spend time reverse engineering your example. The fewer files the better. Also text describing where exactly you are expecting to inject things and where you are not getting what you expect.

**Comment by kavinda1995** [comment]
Happened to me also when creating an input in angular elements

**Comment by jonrimmer** [comment]
@mhevery I cannot, because the injection problem is happening in tests, as indicated by the issue title and description, and Stackblitz has no capability to run Angular unit tests.. The linked repo is a `ng new` project with a single, simple commit applied. The bug text also already includes the description of what I am injecting and what is going wrong.

I spent considerable effort and time creating this simplified example. I find your suggestion that I didn't, and that I'm asking you to perform unreasonable reverse engineering rude and unfounded. If your team doesn't have the capacity to handle bug reports from the community, then you shouldn't accept them, instead of insulting community members who make good-faith attempts to contribute.

**Comment by ryneo** [comment]
@jonrimmer I came across this problem when implementing a custom control like yours.  Turns out the way to fix the unit tests is to add the `@Optional()` decorator to the `NgControl` dependency like

```
constructor(@Self() @Optional() ngControl: NgControl) {
  ngControl.valueAccessor = this;
}
```

It is a requirement that this component has a host test component to provide it with a `FormControl`. 

Also it appears that your example code has a typo.  The test component class is `TestWrapper` but it is declared as `TestWrapperComponent` in the testing module.

**Comment by free-easy** [comment]
@jonrimmer By any chance, does this happen when you run `ng build --prod`? Because I'm implementing custom form controls too. I haven't setup any tests yet, as we're in very early prototyping phase, but while with `ng serve` everything is just fine, when trying AOT I get the same error as yours.

**Comment by Adityau1** [comment]
Try 
```typescript
(fixture.componentInstance as any).ngControl = new FormControl();
```

**Comment by ShadowManu** [comment]
In case anybody finds this useful, I'm able to fix this using `TestbedStatic.overrideComponent`:

```typescript
  beforeEach(async () => {
    const NG_CONTROL_PROVIDER = {
      provide: NgControl,
      useClass: class extends NgControl {
        control = new FormControl();
        // tslint:disable-next-line: no-empty
        viewToModelUpdate() {}
      },
    };

    await TestBed.configureTestingModule({
      declarations: [SelectAmountComponent],
      imports: [FormsModule],
    })
      .overrideComponent(SelectAmountComponent, {
        add: { providers: [NG_CONTROL_PROVIDER] },
      })
      .compileComponents();
  });
```

**Comment by isahohieku** [comment]
Thanks @ShadowManu. This worked.

**Comment by kara** [comment]
@jonrimmer Thanks for linking the repo (and to your point, testing in Stackblitz isn't easy, so a repo in this case is fine). I ported the example to Ivy and it appears that the problem no longer manifests with the new compiler. However, it still looks like there is an unexpected error in View Engine for version 9. 

I noticed the following when investigating this:
- This is a compilation problem. If you add `@Optional()` to bypass the compile-time error, the runtime is able to successfully find the `NgControl` dependency without issues. 
- It's only the `@Self()` flag that seems to cause an issue. Using `@Host()` doesn't seem to cause a problem. This hints to me that maybe we're looking at the wrong node when resolving this provider.

**Comment by rajnadan** [comment]
You are missing providers in the setup.

`describe('HelloComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [FormsModule, ReactiveFormsModule],
      declarations: [
        HelloComponent,
        TestWrapperComponent
      ],
     **providers: [{ provide: NgControl}]**
    }).compileComponents();
  }));
});`

**Comment by JoostK** [comment]
This is no longer an issue in Ivy, so closing as resolved.
