### ISSUE TITLE
Error on loading pages with hashLocationStrategy on file://... or Cordova project

### ISSUE THREAD

**Issue by simon-sharp** [angular/angular#31652]
# 🐞 bug report

### Affected Package
Core / Variable change detection

### Is this a regression?
Yes. We used it often. Angular 5 definitely worked Angular 7 might still have done the Job.

### Description
When building an ordinary App with the command
`ng build --prod --base-href="./" --outputPath="dist/web-prod"`
and then open the index.html directly by file:// in the browser or putting this into a cordova App you get a white page.

To get rid of the CORS errors I set the
`"target": "es5",`
in the tsconfig.json file.

After that I set the routeLocationStrategy to Hash by adding useHash in the app-routing.module.ts

```
@NgModule({
    imports: [
        RouterModule.forRoot(
            routes,
            {
                useHash: true
            }
        )
    ],
    exports: [RouterModule]
})
export class AppRoutingModule {
}
```
I then create several page components that have routes and are linked from one to another.

They have a navigation that has a `*ngIf="showNavigation"` with showNavigation being a boolean value that is changes by a simple toggleShowNaviagtion Function that runs

`this.showNavigation = !this.showNavigation`

After going to the second page all commands freeze and the page is not rerendered. Adding this.ngZone.run(() => {}); solved the issue shortyl. But after changing the route again the page got stuck and the page was not even loaded.

Under some circumstances when loading from file://.../index.html the page is white completely white from the beginning. This is specialy true when the build path is outside the root path of the angular app

`ng build --prod --base-href="./" --outputPath="../../dist/web-prod"`

## 🔬 Minimal Reproduction
https://github.com/simon-sharp/angular-error
Check an run build_android.sh

## 🔥 Exception or Error
No exceptions, no errors. Just a white page

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.6
Node: 9.11.2
OS: linux x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cli                      8.0.6
@angular/pwa                      0.12.4
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**
Chrome and Firefox are tested and have the issue

**Comment by simon-sharp** [comment]
Got the cordova error fixed by replacing the links from 

`public target = '#/client/settings';`

to

`public target = 'index.html#/client/settings';`

It still seems to me that this behaviour is wrong.

I also tried

`public target = '/#/client/settings';`

but that does not work at all

**Comment by atscott** [comment]
Hi @simon-sharp, can you change your build step to be `ng build --prod --base-href="index.html" --outputPath="dist/web-prod"` when you are building to run from a file? The issue is that you're setting the base to `./` but you really want all navigations to be from the `index.html` file.

When the initial url is resolved and the router attempts a navigation, you're getting the following error:
`Uncaught DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///Users/atscott/github/angular-error/dev/angular-error/dist/web-dev/#/' cannot be created in a document with origin 'null' and URL 'file:///Users/atscott/github/angular-error/dev/angular-error/dist/web-dev/index.html#/'.`

**Comment by atscott** [comment]
As far as I can tell, this behaves as expected. Please reference my previous comment on how to resolve the issue for your project. If you still feel there is a different issue, please provide further details in a new issue.
