### ISSUE TITLE
URL of next route snapshot is not populated in guard

### ISSUE THREAD

**Issue by jonr-elsewhen** [angular/angular#31662]
# 🐞 bug report

### Affected Package

@angular/router

### Is this a regression?

Unknown

### Description

The `URL` property of the `next: ActivatedRouteSnapshot` parameter supplied to `canActivate()` is not populated.

## 🔬 Minimal Reproduction

```ts
@Injectable()
export class BasicGuardService implements CanActivate {
  constructor(private readonly router: Router) {}

  public canActivate(next: ActivatedRouteSnapshot): boolean | UrlTree {
    const { filterId } = next.queryParams;

    if (!filterId) {
      return this.router.createUrlTree(
        next.url,
        { queryParams: { filterId: '1' } }
      );
    }

    return true;
  }
}
```

## 🔥 Exception or Error

`next.url` in the above is an empty array.

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 8.1.0
Node: 12.4.0
OS: darwin x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0
@angular/cdk                      8.0.2
@ngtools/webpack                  8.1.0
@nguniversal/express-engine       8.1.0
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Anything else relevant?**

**Comment by christianlundberg** [comment]
Correct me if I'm wrong but the route you're going to is the second parameter. The first is where you currently are, so it's probably empty because it's your first navigation.

**Comment by jonr-elsewhen** [comment]
@christianlundberg I don't believe so. The second parameter is a snapshot of the router state. I am going by https://angular.io/guide/router#guard-the-admin-feature which labels the first param as "next". Also, when debugging, I can see that the snapshot object does have the URL parts assigned into a private property, just not the public `url` property.

**Comment by jonr-elsewhen** [comment]
Never mind, this was based on a misunderstanding of what the snapshot's `url` property contains: It is only those parts of the URL matched by the route declaration, not the whole URL. I am able to get the full URL from the second parameter.
