### ISSUE TITLE
Determine why ordering matters in render compiler / change detector generation code

### ISSUE THREAD

**Issue by kegluneq** [angular/angular#3166]
Currently, a mismatch of iteration order between the transformer & the runtime code can cause change detection to fail. https://github.com/angular/angular/pull/3165 works around this problem by stable sorting map keys before iterating, but we need to figure out why order matters and, fix the code to avoid that problem, and add a regression test to make sure it doesn't happen again.

**Comment by tbosch** [comment]
I bet this is because we are recreating the change records when the application bootstraps. We already had a lot of issues that were caused because of this. How about we serialize the change records with the change detector during transformation? These two are clearly very tightly linked...

**Comment by tbosch** [comment]
I think we should bump the priority on this one, i.e. serializing the change records, to make our system more stable. @vsavkin @mhevery What do you think?

**Comment by kegluneq** [comment]
Serializing records is a great idea, though I remember looking at it a bit back and thinking it would be a bit tricky -- there's a lot in those records.

[Link to related issue](https://github.com/angular/angular/issues/2067)

**Comment by mhevery** [comment]
Obsolete by #3605
