### ISSUE TITLE
Zone issue #537 using Electron menus resurfacing using Electron 4+

### ISSUE THREAD

**Issue by pamtbaau** [angular/angular#31668]
It seems like issue [#537](https://github.com/angular/zone.js/issues/537) is resurfacing after upgrading to angular v7.2.8.

Angular does not detect changes anymore when change occurs after selecting Electron menu.

**Comment by pamtbaau** [comment]
@JiaLiPassion Thank you for you reply. I understand your reasoning, but... I used to work fine in Electron 3.x...

I've found another statement that makes change detection fail:
```
// declaration
import { remote } from 'electron';
const { Menu } = remote;

// usage in method creating menu:
const menu = Menu.buildFromTemplate(template);
```

This too used to work in Electron 3.x. I've solved this last issue by using the following:
```
import { remote } from 'electron';

// usage in method creating menu:
const menu = remote.Menu.buildFromTemplate(template);
```

When will the patched version of zone.js be available?

**Comment by JiaLiPassion** [comment]
@pamtbaau, oh, so `  private static breaksZone = remote.app.getPath('userData');` this will work in `electron 3.x`? I will check why it worked, maybe the the timing of `initialization of CallRegistery` changed.

the new version should be released soon.

**Comment by pamtbaau** [comment]
@JiaLiPassion Upgraded to zone.js 0.10.0 and change detection of Electron (popup)menu events are working fine.

Thanks for fixing this!
