### ISSUE TITLE
Issue in layout of page while resizing of page.

### ISSUE THREAD

**Issue by kailashchandra** [angular/angular#31666]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Anything else relevant?

When i go to URL (https://angular.io/tutorial/toh-pt2). If i resize my web page so on top left there is one button which seems like resizing bug on button. For better explanation i am attaching screenshot (highlighted in red).

![image](https://user-images.githubusercontent.com/13407278/61574002-92d99600-aad5-11e9-9cdb-dac2265ffc45.png)

And Here is width and Height to reproduce the bug:

![image](https://user-images.githubusercontent.com/13407278/61574029-214e1780-aad6-11e9-99e9-8dff276adafa.png)

**Comment by gkalpak** [comment]
Thx for reporting, @kailashchandra! This will be fixed by #31533.
