### ISSUE TITLE
Warning in zone-evergreen.js from Chrome

### ISSUE THREAD

**Issue by fr0** [angular/angular#31676]
```
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
(anonymous) @ zone-evergreen.js:2967
```

Looks like the code it is referring to is this:

```
        const openNative = patchMethod(XMLHttpRequestPrototype, 'open', () => function (self, args) {
            self[XHR_SYNC] = args[2] == false;
            self[XHR_URL] = args[1];
            return openNative.apply(self, args);
        });
```

**Comment by fr0** [comment]
Sorry for the late response - it happens every time when using karma-jasmine.

https://github.com/fr0/angular-test/tree/zone

Run `npm install` then `npm test`

**Comment by tobiasschweizer** [comment]
any progress on this?

**Comment by symphony2014** [comment]
I just give a try, and never found the warnning.  Also, since the angular version is outdate, with latest RENDER3  **label.opacity** should be work.

**Comment by tobiasschweizer** [comment]
Can you confirm that the warning does not indicate any actual problem in the specs?

**Comment by JiaLiPassion** [comment]
This is not a zone.js issue, the warning is from here.
https://github.com/evanw/node-source-map-support/blob/50642d69b1ba461beb651bbf4f6e52fbddaa5318/source-map-support.js#L96

The source map support library will open a `sync` xhr, so the warning will be displayed. will close this issue.
