### ISSUE TITLE
ng-content does not work properly with @angular/elements

### ISSUE THREAD

**Issue by michael-vasyliv** [angular/angular#31675]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/elements

### Is this a regression?
--

### Description
a custom element does not insert ``<ng-content>`` in the right place properly
the element has next html:
```
!<div>
  ~<ng-content></ng-content>~
</div>!
```
but it creates next one:
```
<ngx-a _ngcontent-jmh-c0="" _nghost-jmh-c2="" ng-version="8.1.2">
  !<div _ngcontent-jmh-c2=""> 
    ~~
  </div>!
  123123123
</ngx-a>
```
but I expect next one:
```
<ngx-a _ngcontent-jmh-c0="" _nghost-jmh-c2="" ng-version="8.1.2">
  !<div _ngcontent-jmh-c2=""> 
    ~123123123~
  </div>!  
</ngx-a>
```

the problem is - ``<ng-content>`` is inserting at the end of the content custom element

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-wj4nra

## 🔥 Exception or Error
--

## 🌍  Your Environment
Chrome
@Angular/* 8.x.x
windows 10

**Comment by divyanshumehta** [comment]
@AndrewKushnir , I am facing this too, anyone got any update on this.

**Comment by michael-vasyliv** [comment]
https://github.com/angular/angular/issues/24536#issuecomment-411240071
