### ISSUE TITLE
Annotations not showing up in Documentation

### ISSUE THREAD

**Issue by mhevery** [angular/angular#3167]
See docs for `ng-for` https://angular.io/docs/js/latest/api/directives/NgFor-class.html. Notice that the annotation from https://angular.io/docs/js/latest/api/directives/NgFor-class.html are not showing up.

There should be a separate section (above `Members`) called `Annotations` which should show:
```
@Directive({
  selector: '[ng-for][ng-for-of]', 
  properties: ['ngForOf'], 
  lifecycle: [LifecycleEvent.onCheck]
})
```

**Comment by petebacondarwin** [comment]
You mean these annotations: 

https://github.com/angular/angular/blob/master/modules/angular2/src/directives/ng_for.ts#L43-L44

I can look into this on Thursday.
