### ISSUE TITLE
"host: style" metadata in child component has breaking change ( enableIvy: true)

### ISSUE THREAD

**Issue by Domainv** [angular/angular#31671]
# 🐞 bug report

### Affected Package
angular/*8.2.0-next.0 (Ivy engine enabled)

### Is this a regression?

This used to work with
Ivy engine: disabled

### Description

"host: style" metadata in child component has a breaking change

"Ivy: false" rewriting all host styles with styles in the option
"Ivy: true" rewriting only changed styles

## 🔬 Minimal Reproduction
https://github.com/Domainv/ivy-host-style-metadata-reproduction

![123](https://user-images.githubusercontent.com/14885427/61579468-1911ce80-ab0e-11e9-8dcc-f1f53e5c43f8.gif)

## 🌍  Your Environment

Angular CLI: 8.1.0-rc.0
Node: 10.16.0
OS: linux x64
Angular: 8.2.0-next.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.2
@angular-devkit/build-angular     0.800.2
@angular-devkit/build-optimizer   0.800.2
@angular-devkit/build-webpack     0.800.2
@angular-devkit/core              8.0.2
@angular-devkit/schematics        8.1.0-rc.0
@angular/cli                      8.1.0-rc.0
@angular/router                   8.0.0
@ngtools/webpack                  8.0.2
@schematics/angular               8.1.0-rc.0
@schematics/update                0.801.0-rc.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

**Comment by kara** [comment]
@Domainv Thanks for the detailed report! This issue actually looks like an expected breaking change from [our list here](https://docs.google.com/document/d/1Dije0AsJ0PxL3NaeNPxpYDeapj30b_QC0xfeIvIIzgg/preview?source=post_page---------------------------). 

> Properties like host inside @Component and @Directive decorators can be inherited (previously, only properties with explicit field decorators like @HostBinding would be inherited). 

In this case, because `host` is inherited, the style from `ParentComponent` will be applied to its subclass, `ChildComponent`.

**Comment by Domainv** [comment]
Thank you)
