### ISSUE TITLE
Feature request: patch performance.now within a FakeAsync zone

### ISSUE THREAD

**Issue by eric-simonton-sama** [angular/angular#31677]
Similar to the way `fakeAsync` advances `Date.now` since https://github.com/angular/zone.js/pull/1009, this is a feature request to also have it freeze and advance [`performance.now`](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now)

**Comment by ersimont** [comment]
A workaround:

```ts
    beforeEach(() => {
      spyOn(performance, "now").and.callFake(() => Date.now());
    });
```
