### ISSUE TITLE
Google API Breaks Change Detector in Lazy Loaded Module

### ISSUE THREAD

**Issue by faran52000** [angular/angular#31673]
I have implemented Google API in my project and Whenever I authenticate from the popup view the change detector breaks for the Angular and the view stops refreshing the values as can be seen in the stack-blitz below.

Stack-blitz: https://stackblitz.com/edit/angular-bgzrt2

What should happen here is when I get back from Google API the value should update to true in the `example.component.html` which stops refreshing the value.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by faran52000** [comment]
@mhevery I've posted this on stackoverflow. I think it is a bug if not CDR should respond to changes made after injection of a script it's the same case for Facebook/Google and any other script injected at runtime which I have reproduced in the stackblitz above

**Comment by mlc-mlapis** [comment]
@faran52000 ??? How Angular should know what, when and where you inject any script?

**Comment by faran52000** [comment]
@mlc-mlapis I'm injecting the script in head. I've tried in body too. After injecting the script as soon as I get a response from onInit for the script the CDR in the component breaks and the view for that particular component do not detect changes even if I manually create an instance of cdr and run detect changes manually.

**Comment by mlc-mlapis** [comment]
@faran52000 Hmm, not clear what are you doing. Does it correspond to the Stackblitz above? But generally, you probably need to use `NgZone` -> as `this._ngZone.run(() => {...})` to cover your scripts under Zone and allow to CD to register the events from those third parties scrips.

**Comment by faran52000** [comment]
@mlc-mlapis yes the above stackblitz cover one of the scenarios. By what you are saying I should inject script from the NgZone to cover the functionality?
Shouldn't angular do that by default since they are being injected from the angular's default?

**Comment by mlc-mlapis** [comment]
@faran52000 I didn't mention to inject it from NgZone, I meant invoking the relevant parts.

First of all, it's necessary to have the exact simple reproduction to discuss it. Otherwise, it's just blind guessing. But still, Angular (NgZone specifically) has to know that there is a script which should be taken into the account.

**Comment by mlc-mlapis** [comment]
@faran52000 I recommend you to read this article: https://blog.angularindepth.com/a-gentle-introduction-into-change-detection-in-angular-33f9ffff6f10, specifically the part about **Automatic change detection with zones**.

**Comment by faran52000** [comment]
@mlc-mlapis ok thanks, I'll check the article out
