### ISSUE TITLE
Change detection stops working when calling detectChanges outside of angular

### ISSUE THREAD

**Issue by adamdport** [angular/angular#31682]
I discovered this while trying to create a reproduction for #1034. However, I've managed to reproduce it outside Cordova too:

https://stackblitz.com/edit/angular-material2-issue-pfytvj

If you call `detectChanges` from `runOutsideAngular`, **at a specific time**, change detection stops working properly:

    this.ngZone.runOutsideAngular(() => {
      this.changeDetectorRef.detectChanges();
    });

Doing this from `ngOnInit` seems to reproduce the issue, while calling it from a button click does not. I've also seen it happen when called from a `NavigationEnd` router event. 

It appears that button clicks (even clicks that aren't bound to a function) and `setTimeout`s allow a single pass of change detection to occur, but focus, keypress, etc do not trigger change detection appropriately.

This didn't used to cause issues until I recently updated packages, so I suspect the change was released in the past couple months.

**Comment by jelbourn** [comment]
Closing this into #28493, which covers documentation for zone.js since this seems to be working as expected, but without anything to explain how it is meant to work.
