### ISSUE TITLE
One of the Tableau js promise in Angular 7 resolves only on user event - mousemove

### ISSUE THREAD

**Issue by smitach** [angular/angular#31683]
This is the following code I have in my service.
```
declare var tableau: any;
export class TableauService {
 createViz(url: string, onFirstInteractive: () => void): void {
    this.viz = new tableau.Viz(this.element.nativeElement, url, {
      hideTabs: true,
      usePublishedSize: true,
      hideToolbar: true,
      width: '100%',
      height: '700px',
      onFirstInteractive,
    });
 }

 applyFilterToSheet(name, value) {
    const sheets = this.viz.getWorkbook().getActiveSheet().getSheets();
    return sheets[0].applyFilterAsync(name, value, tableau.FilterUpdateType.REPLACE); //returns a promise       
 }
}
```
Following code in one of the components,
```
applyFilterToSheet('Location', 'Berlin').then( result => console.log('Applied Location filter'), err => console.log('Error in applying filter'))
```
I get success callback call when I move my cursor.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
