### ISSUE TITLE
zone-evergreen: Object.prototype.toString.apply(null) returns [object Window]

### ISSUE THREAD

**Issue by mindstorm** [angular/angular#31681]
When using zone-evergreen.js from version 0.9.x (as its done by NG CLI 8), Object.prototype.toString.apply(null) returns [object Window] instead of [object Null].

I found this issue while debugging the integration of the CKEditor in a NG8 Application.

**Comment by hakimio** [comment]
@JiaLiPassion what's zone.js version where this was fixed?

**Comment by JiaLiPassion** [comment]
@hakimio, the newest version is the fixed one, 0.10.2

**Comment by hakimio** [comment]
Cool, maybe this one should be closed then?
