### ISSUE TITLE
zone-patch-rxjs - Unsubscription error - Cannot read property 'apply' of null

### ISSUE THREAD

**Issue by AleG94** [angular/angular#31684]
I'm trying to implement a retry http interceptor for Angular 7. 

Without `import 'zone.js/dist/zone-patch-rxjs';` it works fine but when I add it, I get:

```
ERROR {"message":"1 errors occurred during unsubscription:\n1) TypeError: Cannot read property 'apply' of null","name":"UnsubscriptionError","errors":[{}]}
```

This is an example repo to reproduce the issue: 

[https://stackblitz.com/edit/angular-s3iv5u?file=polyfills.ts](https://stackblitz.com/edit/angular-s3iv5u?file=polyfills.ts)

Comment and uncomment the line `import 'zone.js/dist/zone-patch-rxjs';` in `polyfills.ts` to see the error appear and disappear.

**Comment by arturovt** [comment]
@AleG94 just checked the example you've provided with Angular 8 and it works fine. Probably it was fixed but PR didn't mention this issue.

**Comment by xinbaihui** [comment]
I update zone.js from v0.9.1 to v0.10.3  to avoid this error. But I encounter another problem that it won't stop when retry times up to [count] times.
```
return source.pipe(
    retryWhen(errs =>
        errs.pipe(
          take(count),
          mergeMap((err, i) => {
            if (i < count - 1) {  // i === 0 all the time
              return of(err);
            }
            return throwError(err);
          }),
          delay(delayTime)
        )
      )
    );
```

**Comment by JiaLiPassion** [comment]
@xinbaihui, please provide a reproduce repo and a simple step to explain what is the expect result. thanks.

**Comment by xinbaihui** [comment]
This is an example from AleG94, I update zone.js to v0.10.3
[https://stackblitz.com/edit/angular-wmyhre](url)

I hope  the request will be stopped and catch the error after retry 3 times. But actually the retry won't stop even retry time up to maxAttempts. 

Thanks very much.

**Comment by JiaLiPassion** [comment]
@xinbaihui , thank you for the sample, I have created a PR https://github.com/angular/angular/pull/37091 to fix this one.

**Comment by xinbaihui** [comment]
@JiaLiPassion Thank you for resolving this problem so fast. It helps a lot. Thanks again.
