### ISSUE TITLE
Proper message when angular test.ts has invalid order instead of "TypeError: Cannot read property 'assertPresent' of undefined"

### ISSUE THREAD

**Issue by vovikdrg** [angular/angular#31694]
After I enabled ts-lint autofix with import sorting I got error in my tests "TypeError: Cannot read property 'assertPresent' of undefined"

// This file is required by karma.conf.js and loads recursively all the .spec and framework files

```
import { getTestBed } from '@angular/core/testing';
import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing';
import 'zone.js/dist/zone-testing';


declare const require: any;

getTestBed().initTestEnvironment(
    BrowserDynamicTestingModule,
    platformBrowserDynamicTesting()
);
const context = require.context('./', true, /\.spec\.ts$/);

context.keys().map(context);
```
After that i found https://github.com/angular/angular/issues/11317#issuecomment-419122951 which solved my issue but I am not one who have this problem

I would expect to see proper message that my "import 'zone.js/dist/zone-testing';" is wrong.

I also submitted[ feature-request to angular-cli](https://github.com/angular/angular-cli/issues/12550) but it was rejected. Such issues just make people to dislike angular while I want them to love it :)

**Comment by JoostK** [comment]
I just looked at this again and there are error messages reported now, instead of calling `assertPresent` on an undefined value.
