### ISSUE TITLE
Change detection stops working on Cordova

### ISSUE THREAD

**Issue by artuska** [angular/angular#31709]
Change detection stops working if the Cordova application:

- goes to the background;
- goes to offline/online state
- opens via the Push Notification click on mobile phone.

For example, I have a social authorization via the native mobile Facebook application on iPhone. When I click on authorization button Facebook application opens and my application goes to the background, when authorization is finished my application goes back to the foreground, but change detection stops working — if there are some `(click)` events on some buttons they will run fine, but HTML code will not update — for example, `[ngClass]` will not change classes, etc. 

## Environment
<pre><code>Angular version: 5.2.1

Browser:
- [x] iOS webView browser

For Tooling issues:
- Platform: iOS, Cordova
</code></pre>

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
