### ISSUE TITLE
Unhandled Promise Rejection when requests are cancelled due to reloading page in firefox

### ISSUE THREAD

**Issue by thefoxcoder** [angular/angular#31700]
If i have an ongoing ajax request that gets cancelled due to refreshing the page or navigating to another page i get a Unhandled Promise rejection exception. 

`Unhandled Promise rejection: NetworkError when attempting to fetch resource. ; Zone: <root> ; Task: Promise.then ; Value: TypeError: "NetworkError when attempting to fetch resource."`

This does not happen when not using zone.js. It should be easy to reproduce by simply running the following on a site running zone.js in FireFox, and simply refreshing the page before the promise has resolved:

``new Promise(function(resolve, reject){ 
    fetch('http://www.fakeresponse.com/api/?sleep=2')
    .then(function(data){
        resolve("done");
    });
})
.then(console.log);``

**Comment by JiaLiPassion** [comment]
@thefoxcoder , sorry for the very long delay, is the issue still exists? could you provide a reproduce repo? Thanks.

**Comment by jelbourn** [comment]
Closing due to lack of more information.
