### ISSUE TITLE
XMLHttpRequest & globalZoneAwareCallBack

### ISSUE THREAD

**Issue by ardeshirj** [angular/angular#31705]
We recently noticed a performance issue with IE11 in our angular 5 app that is not happening in other browsers. I start troubleshooting it using F12 developer tools in windows 10. Used both networks and performance tab in the debug tools and noticed XMLHttpRequest (networks) & globalZoneAwareCallBack (performance) are the main tasks that takes about 25 seconds to finish.

![ie-11-win-10-cors-2](https://user-images.githubusercontent.com/6003742/40015600-bf02e284-5768-11e8-9c76-a18ff34def70.png)

![ie-11-win-10-performance](https://user-images.githubusercontent.com/6003742/40010409-7ffd1488-5759-11e8-9298-f3c6cb6ca35b.jpeg)

As you can tell from the screenshot, the OPTIONS request are taking so long to finish. My understanding is IE and other browsers send these CORS preflight before the actual request. Most browsers will process the response in 300-500 ms but for some reason IE 11 in windows 10 takes about 24 seconds. Hovering over the timing tab, it indicate the majority of the time is being used for "downloading" (the step after TTFB), which is weird since successful response for OPTIONS request usually is 204 with `No Content`. 

I tried this again, but this time I used IE 11 in windows 8.1 instead. This time, IE 11 took around 6s for each and the result was `aborted` instead of 204. Also noticed there were some errors (SEC7118 & SEC7119) in console logs, which according to MS website [here](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/samples/dn423949(v=vs.85)) are removed from IE 11 from windows 10:

>This requires the server to return an "Access-Control-Allow-Origin" header in its response headers, but one was not returned.

>The specific operation of the request required both CORS support and preflighting on the server side, but preflighting failed.

These raise the question if the api is supporting CORS or not and the answer is yes. Also other browsers finish the OPTIONS request successfully. Not sure why IE  11 is acting different in two version of windows. I assume this is IE 11 related and out of the scope for this issue, so I moved on and troubleshoot using the performance tab.

In performance tab, there is DOM event that is taking about 22 seconds and once I expand it i noticed globalZoneAwareCallBack event listener. Unfortunately I don't see any call stack under `Javascript call stack`, so I am not sure where the globalZoneAwareCallBack is struggling.

I wonder if there is any correlation between XMLHttpRequest and globalZoneAwareCallBack here. The XMLHttpRequest OPTIONS request takes about 25 seconds while the globalZoneAwareCallBack takes about 22 + few second tasks before that. I wonder if any of these OPTIONS request is blocking the globalZoneAwareCallBack tasks or vice versa.

I am not sure this could be a bug related to zonejs but noticed some other issues that was related #691, #971 and both of them are closed now. Opening this issue to get some feedback regarding where globalZoneAwareCallBack or XMLHttpRequest is possibly having issue while I am working reproducing this issue in a separate repo.

Packages:
"@angular/animations": "^5.2.0",
"@angular/common": "^5.2.0",
"@angular/compiler": "^5.2.0",
"@angular/core": "^5.2.0",
"@angular/forms": "^5.2.0",
"@angular/http": "^5.2.0",
"@angular/platform-browser": "^5.2.0",
"@angular/platform-browser-dynamic": "^5.2.0",
"@angular/platform-server": "^5.2.0",
"@angular/router": "^5.2.0",
"zone.js": "^0.8.20"

IE-11 Windows 10 version: `11.15.16299.0`
IE-11 Windows 8.1 version: `11.0.9600.18953`

**Comment by AndrewKushnir** [comment]
Closing this ticket, since the reported problem was only present in IE11 and Angular no longer supports IE.
