### ISSUE TITLE
Taps on a touch screen are not triggering click events when packaged with Electron

### ISSUE THREAD

**Issue by BenBergman** [angular/angular#31703]
I have an Electron app that I inherited that I need to get working with a touch screen on macOS. If I repackage the app with Cordova touches trigger click events just fine but I am missing a bunch of functionality that Electron provides.

I have created [a fairly minimal project](https://github.com/BenBergman/angular-electron-tap-bug-test) that demonstrates this issue.

I had originally opened [a ticket](https://github.com/angular/angular/issues/24694) with the main Angular project but was directed to open a ticket here as it was determined to likely be a zone.js issue.

**Comment by jelbourn** [comment]
Closing due to lack of more information, possibly obsolete.
