### ISSUE TITLE
Error:  can not transition to 'running', expecting state 'scheduled', was 'notScheduled'.

### ISSUE THREAD

**Issue by mariohmol** [angular/angular#31706]
Hi,

i have an app using nodejs, express , multer (to upload images).

For some specific files (some wav formats) it gives me a different flow in busboy where reaches the zone.js and breaks the node app (stops the execution without catching the error )

Without zone.js everything works fine. But as i have an SSR project, i have to have zone.js.

Here is more details about the error: https://github.com/mscdex/busboy/issues/166

Any ideas how i can solve that?

Thanks!

**Comment by jelbourn** [comment]
Closing due to lack of more information, possibly obsolete.
