### ISSUE TITLE
fakeAsync cannot work with FileReader event

### ISSUE THREAD

**Issue by Teamop** [angular/angular#31702]
## verison
zone.js: 0.8.26

## issue
For testing the `FileReader` event, like `onload`, if with `setTimeout`, test case can pass, while with `fakeAsync`, failed. 
The below is the code that can reproduce this issue and can just be pasted in the current test spec and run

```javascript
// function need to be tested
function fileReaderTest(blob: Blob): number {
  const reader = new FileReader();

  let num = 0;

  reader.onload = () => {
    num++;
  };

  reader.readAsText(blob);

  return num;
}

// test the above function
fdescribe('', () => {
  let blob: Blob;

  beforeEach(() => {
    const data = 'Hello, World!';
    blob = new Blob([data]);
  });

  // can pass
  it('with setTimeout', () => {
    const number = fileReaderTest(blob);

    setTimeout(() => {
      expect(number).toEqual(1);
    });
  });

  // fail
  it('with fakeAsync', () => {
    let FakeAsyncTestZoneSpec = (Zone as any)['FakeAsyncTestZoneSpec'];
    let testZoneSpec: any;
    let fakeAsyncTestZone: Zone;

    testZoneSpec = new FakeAsyncTestZoneSpec('name');
    fakeAsyncTestZone = Zone.current.fork(testZoneSpec);

    const num = fileReaderTest(blob);

    fakeAsyncTestZone.run(() => {

      testZoneSpec.tick(100);
      testZoneSpec.tick(100);
      testZoneSpec.flush(); 
      testZoneSpec.flushMicrotasks();
      expect(num).toEqual(1);
    });
  });
});

```

## Background
Today when I tried to write some unit tests for a function with `FileReader`, I got this issue. But I'm not sure if it's really a bug or just my misuse.

thanks

**Comment by aburht** [comment]
Any updates on this issue or any workaround to test this solution

**Comment by JiaLiPassion** [comment]
I will begin to work on this soon.

**Comment by akhilbothsa** [comment]
Meanwhile, Is there any work around to achieve this?

**Comment by jonyeezs** [comment]
The workaround is to not use `fakeAsync` or `async`. Will have to resort to good ol Jasmine `done()`.

Here's a working example https://stackblitz.com/edit/writing-test-for-filereader.

P.S: it's code to my usecase but I reckon it highlights how to test with `FileReader` in mind

**Comment by dj7266** [comment]
@JiaLiPassion I think `Image` is not supported by `fakeAsync` either if you have a chance to look at it.

**Comment by roddc** [comment]
Any updates?
