### ISSUE TITLE
zone-patch-rxjs causes Testability.whenStable to fire too early

### ISSUE THREAD

**Issue by gawicks** [angular/angular#31711]
Hi,

I have created two stackblitz to demonstrate the issue here. Both applications are running a simple Timer observable. With the only difference being the zone rxjs patch.

https://stackblitz.com/edit/angular-pk8m9n [without patch]
https://stackblitz.com/edit/angular-stywbt [with patch]

In the version without the patch whenStable gets called when the timer completes. this is as expected ([angular/#8089](https://github.com/angular/angular/issues/8089)). In the version with the patch whenStable gets called right at the beginning, and does not wait for the timer to complete.

For me this breaks protractor's waitForAngular. It begins clicking stuff before angular has stabilized.

**Comment by atscott** [comment]
I updated the stackblitz example with the patch to the latest versions of all the packages and it has the same behavior as the first (stable is produced at the very end). Closing as the appears to be resolved.
