### ISSUE TITLE
Infinite loop with MutationObserver + browser zoom

### ISSUE THREAD

**Issue by eric-simonton-sama** [angular/angular#31712]
Using a combination of [`ngx-bootstrap`](https://github.com/valor-software/ngx-bootstrap) tooltips, `MutationObserver`, and browser zooming it is possible to trigger an infinite loop that locks up the browser tab. [Here](https://plnkr.co/edit/oJvObtL3CeFwFiiYpQQT?p=preview) is a plunker demonstrating the issue. Try different browser zoom levels, then mousing over the tooltips. For me it will lock the browser at 90% and 125% zoom, but not at 100% or 110%.

I filed this issue with a couple other libraries while trying to nail down the culprit:
- https://github.com/valor-software/ngx-bootstrap/issues/3047
- https://github.com/que-etc/resize-observer-polyfill/issues/27

@que-etc mentioned `zone.js` as his prime suspect in that second link, thus I am filing this issue.

Thanks for making Angular easier to use with this library!

**Comment by notbear** [comment]
@JiaLiPassion , sure. I borrowed the example from https://github.com/angular/angular/issues/31483 which seems to be very similar issue. During investigation, I noticed that webcomponents are not necessary to reproduce this bug. See examples:

The `getName` method returns a new object instance. Luckily, unwrapping the MutationObserver fixes the issue:
https://stackblitz.com/edit/angular-mutationobserver-object?file=src/app/app.component.ts

But if you work with collection which reinstatiates object items like in the method `getOptions`, nothing helps. 
https://stackblitz.com/edit/angular-mutationobserver-collection?file=src/app/app.component.ts

**Comment by notbear** [comment]
Hi @JiaLiPassion 

Related tickets #26948 and #31483 were recently closed because of inactivity. 

I've just checked the example provided last time using latest versions of Angular and Zone (see versions below) and the issue still exists. 

But luckily... the known workaround with unwrapping Zone previously worked only for plain objects. Now it seems to help also for collections. Could you comment or confirm that it's been fixed somehow?


```
    "@angular/animations": "~8.2.7",
    "@angular/common": "~8.2.7",
    "@angular/compiler": "~8.2.7",
    "@angular/core": "~8.2.7",
    "@angular/forms": "~8.2.7",
    "@angular/platform-browser": "~8.2.7",
    "@angular/platform-browser-dynamic": "~8.2.7",
    "@angular/router": "~8.2.7",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
```

**Comment by jelbourn** [comment]
@IgorMinar and I looked at this and we think this is at least working as expected. Angular uses zones to drive change detection, so using APIs like `MutationObserver` and `ResizeObserver` to then trigger further change detections is inherently prone to infinite loops. The advice here would be to generally listen to these outside of the zone and exercise more specific control over calling into change detection.
