### ISSUE TITLE
TypeError: setting a property that has only a getter

### ISSUE THREAD

**Issue by chris13524** [angular/angular#31729]
Version 0.8.12 brings a change that causes this error. This does not happen in v0.8.11.
![image](https://user-images.githubusercontent.com/1979423/27006556-be27fb38-4e04-11e7-9c0d-a5dfe37617e6.png)

This is happening for me on Firefox (v53.03), but not on Chrome (v54.0.2840.59).

The third stack trace element is this:
![image](https://user-images.githubusercontent.com/1979423/27006582-80832bee-4e05-11e7-985c-69a9fe9a0070.png)

It seems to me this issue is related to #788.

**Comment by mhevery** [comment]
Closing because there is no repro and the last activity has been over 3 years ego.
