### ISSUE TITLE
Unhandled Promise rejection: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten. Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.) ; Zone: <root> ; Task: Promise.then ;

### ISSUE THREAD

**Issue by divyamrastogi** [angular/angular#31724]
This is my `package.json`:
`"dependencies": {
    "@angular/common": "~4.2.0",
    "@angular/compiler": "~4.2.0",
    "@angular/core": "~4.2.0",
    "@angular/forms": "~4.2.0",
    "@angular/http": "~4.2.0",
    "@angular/platform-browser": "~4.2.0",
    "@angular/platform-browser-dynamic": "~4.2.0",
    "@angular/router": "~4.2.0",
    "bootstrap": "^3.3.7",
    "bootstrap-notify": "^3.1.3",
    "concurrently": "^3.5.0",
    "cookie-parser": "^1.4.3",
    "core-js": "^2.4.1",
    "jquery": "^3.2.1",
    "newrelic": "^2.0.2",
    "node-uuid": "^1.4.8",
    "request": "^2.81.0",
    "rxjs": "5.0.1",
    "sha256": "^0.2.0",
    "x-frame-options": "^1.0.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@types/jasmine": "2.5.36",
    "@types/jquery": "^3.2.12",
    "@types/node": "^6.0.45",
    "angular2-template-loader": "^0.6.0",
    "awesome-typescript-loader": "^3.0.4",
    "chalk": "^2.1.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.26.1",
    "extract-text-webpack-plugin": "2.0.0-beta.5",
    "figures": "^2.0.0",
    "file-loader": "^0.9.0",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.16.1",
    "jasmine-core": "^2.4.1",
    "karma": "^1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-jasmine": "^1.0.2",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^2.0.1",
    "null-loader": "^0.1.1",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.2",
    "style-loader": "^0.13.1",
    "to-string-loader": "^1.1.5",
    "typescript": "~2.3.1",
    "webpack": "2.2.1",
    "webpack-dev-middleware": "^1.12.0",
    "webpack-dev-server": "2.4.1",
    "webpack-hot-middleware": "^2.18.2",
    "webpack-merge": "^3.0.0"
  }`

This is my webpack.common.js:
`const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const helpers = require('./helpers');
const project = require('../project.config');

console.log(project.config.ui);
module.exports = {
  entry: {
    'polyfills': './src/polyfills.ts',
    'vendor': './src/vendor.ts',
    'app': './src/main.ts'
  },

  resolve: {
    extensions: ['.ts', '.js'],
    modules: [
      'node_modules',
      helpers.root('src')
    ]
  },

  module: {
    rules: [{
        test: /\.ts$/,
        loaders: ['awesome-typescript-loader', 'angular2-template-loader']
      },
      {
        test: /\.html$/,
        loader: 'html-loader'
      },
      {
        test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
        loader: 'file-loader?name=assets/[name].[hash].[ext]'
      },
      {
        test: /\.css$/,
        exclude: helpers.root('src', 'app'),
        loader: ['to-string-loader'].concat(ExtractTextPlugin.extract({
          fallbackLoader: 'style-loader',
          loader: 'css-loader?sourceMap'
        }))
      },
      {
        test: /\.css$/,
        include: helpers.root('src', 'app'),
        loader: 'raw-loader'
      }
    ]
  },

  plugins: [
    /*
     * Plugin: CopyWebpackPlugin
     * Description: Copy files and directories in webpack.
     *
     * Copies project static assets.
     *
     * See: https://www.npmjs.com/package/copy-webpack-plugin
     */
    new CopyWebpackPlugin([{
        from: 'src/assets',
        to: 'assets'
      },
      {
        from: 'src/login.html'
      }
    ]),
    // Workaround for angular/angular#11580
    new webpack.ContextReplacementPlugin(
      // The (\\|\/) piece accounts for path separators in *nix and Windows
      /angular(\\|\/)core(\\|\/)@angular/,
      helpers.root('./src'), // location of your src
      {} // a map of your routes
    ),

    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery'
    }),

    new webpack.DefinePlugin({
      'ENV': JSON.stringify(process.env.NODE_ENV),
      'CONFIG': JSON.stringify(project.config.ui)
    }),

    new webpack.optimize.CommonsChunkPlugin({
      name: ['app', 'vendor', 'polyfills']
    }),

    new HtmlWebpackPlugin({
      template: 'src/index.ejs',
      title: 'Leasing Leads Management System',
      chunksSortMode: 'dependency',
      inject: 'body',
      env: process.env.NODE_ENV
    })
  ]
};`

This is the `webpack.config.js`:
`var webpack = require('webpack');
var webpackMerge = require('webpack-merge');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var commonConfig = require('./webpack.common.js');
var helpers = require('./helpers');

const ENV = process.env.NODE_ENV = process.env.ENV = 'production';

module.exports = webpackMerge(commonConfig, {
  devtool: 'source-map',

  output: {
    path: helpers.root('dist'),
    publicPath: '/',
    filename: '[name].[hash].js',
    chunkFilename: '[id].[hash].chunk.js'
  },

  plugins: [
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.optimize.UglifyJsPlugin({ // https://github.com/angular/angular/issues/10618
      mangle: {
        keep_fnames: true
      }
    }),
    new ExtractTextPlugin('[name].[hash].css'),
    new webpack.DefinePlugin({
      'process.env': {
        'ENV': JSON.stringify(ENV)
      }
    }),
    new webpack.LoaderOptionsPlugin({
      htmlLoader: {
        minimize: false // workaround for ng2
      }
    })
  ]
});`

`polyfills.ts`
`import 'core-js/es7/reflect';
require('zone.js/dist/zone');

if (process.env.ENV === 'production') {
  // Production
} else {
  // Development and test
  Error['stackTraceLimit'] = Infinity;
  require('zone.js/dist/long-stack-trace-zone');
}`

`vendor.ts`
`// Angular
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/http';
import '@angular/router';

// RxJS
import 'rxjs';

// Other vendors for example jQuery, Lodash or Bootstrap
// You can import js, ts, css, sass, ...
import 'bootstrap-notify';
import 'bootstrap/dist/js/bootstrap.min.js';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'assets/css/dataTable.css';
import 'assets/css/app.css';
import 'assets/css/main.css';`

We seem to be getting an error on production intermittently:

`Unhandled Promise rejection: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.) ; Zone: <root> ; Task: Promise.then ; Value: Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
    at Function.Zone.assertZonePatched (polyfills.e62b826c4d59b0712100.js:43)
    at new NgZone (vendor.e62b826c4d59b0712100.js:188)
    at PlatformRef_._bootstrapModuleFactoryWithZone (vendor.e62b826c4d59b0712100.js:188)
    at vendor.e62b826c4d59b0712100.js:188
    at nrWrapper (newrelic-production.js:4)
    at ZoneDelegate.invoke (polyfills.e62b826c4d59b0712100.js:43)
    at Zone.run (polyfills.e62b826c4d59b0712100.js:43)
    at polyfills.e62b826c4d59b0712100.js:50
    at ZoneDelegate.invokeTask (polyfills.e62b826c4d59b0712100.js:43)
    at Zone.runTask (polyfills.e62b826c4d59b0712100.js:43) Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
    at Function.Zone.assertZonePatched (https://leasing-lms.olacabs.com/polyfills.e62b826c4d59b0712100.js:43:985)
    at new NgZone (https://leasing-lms.olacabs.com/vendor.e62b826c4d59b0712100.js:188:5688)
    at PlatformRef_._bootstrapModuleFactoryWithZone (https://leasing-lms.olacabs.com/vendor.e62b826c4d59b0712100.js:188:10499)
    at https://leasing-lms.olacabs.com/vendor.e62b826c4d59b0712100.js:188:11358
    at nrWrapper (https://leasing-lms.olacabs.com/assets/js/newrelic-production.js:4:14951)
    at ZoneDelegate.invoke (https://leasing-lms.olacabs.com/polyfills.e62b826c4d59b0712100.js:43:7642)
    at Zone.run (https://leasing-lms.olacabs.com/polyfills.e62b826c4d59b0712100.js:43:2729)
    at https://leasing-lms.olacabs.com/polyfills.e62b826c4d59b0712100.js:50:1672
    at ZoneDelegate.invokeTask (https://leasing-lms.olacabs.com/polyfills.e62b826c4d59b0712100.js:43:8375)
    at Zone.runTask (https://leasing-lms.olacabs.com/polyfills.e62b826c4d59b0712100.js:43:3426)
n.onUnhandledError @ polyfills.e62b826c4d59b0712100.js:50
handleUnhandledRejection @ polyfills.e62b826c4d59b0712100.js:50
e @ polyfills.e62b826c4d59b0712100.js:50
n.microtaskDrainDone @ polyfills.e62b826c4d59b0712100.js:50
drainMicroTaskQueue @ polyfills.e62b826c4d59b0712100.js:43
Promise resolved (async)
scheduleMicroTask @ polyfills.e62b826c4d59b0712100.js:43
ZoneDelegate.scheduleTask @ polyfills.e62b826c4d59b0712100.js:43
Zone.scheduleTask @ polyfills.e62b826c4d59b0712100.js:43
Zone.scheduleMicroTask @ polyfills.e62b826c4d59b0712100.js:43
scheduleResolveOrReject @ polyfills.e62b826c4d59b0712100.js:50
ZoneAwarePromise.then @ polyfills.e62b826c4d59b0712100.js:50
nrWrapper @ newrelic-production.js:4
PlatformRef_._bootstrapModuleWithZone @ vendor.e62b826c4d59b0712100.js:188
PlatformRef_.bootstrapModule @ vendor.e62b826c4d59b0712100.js:188
535 @ app.e62b826c4d59b0712100.js:160
__webpack_require__ @ polyfills.e62b826c4d59b0712100.js:1
window.webpackJsonp @ polyfills.e62b826c4d59b0712100.js:1
(anonymous) @ app.e62b826c4d59b0712100.js:1`

I am unable to find which library/code is overwriting the Promise.

**Comment by JiaLiPassion** [comment]
@LeParadoxHD , @kumaresan-subramani , please provide version and reproduce repo. thanks!

**Comment by 143premsai** [comment]
@JiaLiPassion  I was also getting the same error. It was occurring when i was doing browser navigation buttons forward and backward.
![image](https://user-images.githubusercontent.com/12939389/61623442-41c3d080-ac94-11e9-848c-c9211a648046.png)

I have one hybrid application, in which main Header and body are in angular 1.4 version and using the state router when i got Lifecyclemgmt as state i was redirecting to angular 8 index.html in dist folder as mentioned below.

![image](https://user-images.githubusercontent.com/12939389/61623562-7fc0f480-ac94-11e9-811f-218acd603a02.png)


The entire application was working fine, if i have implemented internal routing using anchor tag it was working. Even Reload functionality is also working, but only for forward and backward using browser keys i am getting the issue.

My application 
Header,Body - Angular 1.4
Inside the Body i was  embedding Angular 8 using state  router.

**Comment by JiaLiPassion** [comment]
@143premsai , could you provide a reproduce repo? thanks!

**Comment by Prabin1111** [comment]
main.ts:12 Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
    at Function.push../node_modules/zone.js/dist/zone.js.Zone.assertZonePatched (zone.js:58)
    at new NgZone (core.js:17174)
    at getNgZone (core.js:17861)
    at PlatformRef.push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModuleFactory (core.js:17759)
    at core.js:17803
    at fusioncharts.js:13

**Comment by gandavarapurajasekhar** [comment]
@Prabin1111 have you got any solution for this error in fusioncharts

**Comment by cagcak** [comment]
```
/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
import 'zone.js/dist/zone';

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es/symbol';
import 'core-js/es/object';
import 'core-js/es/function';
// import 'core-js/es/promise'; // throws error
import 'core-js/es/number';
import 'core-js/es/math';
import 'core-js/es/string';
import 'core-js/es/date';
import 'core-js/es/array';
import 'core-js/es/regexp';
import 'core-js/es/map';
import 'core-js/es/weak-map';
import 'core-js/es/set';
```

**Comment by sourvil** [comment]
We entirely removed core-js but still getting same error, after migration to Angular 8.2.14.
Same error.
We tried to put "import 'zone.js/dist/zone';" to main.ts but it broke our environment based settings. Did not work.

Could not find a solution for hours. Any help? Maybe we should change zonejs version? 

Thanks

![Screen Shot 2019-11-21 at 17 02 17](https://user-images.githubusercontent.com/11807680/69344652-c8a7aa80-0c80-11ea-9944-3cc31acb6f4d.png)
![Screen Shot 2019-11-21 at 17 02 05](https://user-images.githubusercontent.com/11807680/69344653-c8a7aa80-0c80-11ea-81e4-12abe97a2934.png)

**Comment by JiaLiPassion** [comment]
@sourvil , please provide a reproduce repo, thanks!

**Comment by sourvil** [comment]
Sorry, i do not have enough time for now. What we fixed this by like that:

1. Create a totally new v8.3.19 app by "ng new".
2. Copied all our v7 application content to this new v8 app and tested
3. Some file locations are changed but we managed to get success
4. We deleted v7 app content
5. After that we copied v8 app content to v7 app folder
And it worked!

PS: Pls check "ng-dragula" package if you use. If you have an option, try to remove it. 

Thanks

**Comment by izmaylovdev** [comment]
@JiaLiPassion angular.io does not run on iPhone with iOS@10.3.4

**Comment by AlejandrDiaz** [comment]
any fix for that? same issue using iPhone with iOS@12.4.3

**Comment by JiaLiPassion** [comment]
@izmaylovdev , @AlejandrDiaz , this should have been fixed by https://github.com/angular/angular/pull/34162, please wait for the next release, if the issue still exists, please tell me, thanks.

**Comment by AlejandrDiaz** [comment]
Hello!, how long gonna take till release? Thanks in advance @JiaLiPassion

**Comment by JiaLiPassion** [comment]
@AlejandrDiaz, sorry I am not sure the exact date, but it will not take very long.

**Comment by eafiontzi** [comment]
Hello everyone. I created a web component with angular 8 and am trying to use it inside another angular application. Even if I remove the `"import 'zone.js/dist/zone';"` from my polyfills.ts file (in the web component), after including it to my angular.json file in scripts I get the above error about the zone.js. 

The only way to make it work is leaving the import of the zone in the web component file and removing it from the main application, which is not a good solution as the application must run both with and without the component.

Web component uses "zone.js": "~0.9.1" while the core application uses "zone.js": "^0.8.26", maybe that is an issue?

Thank everyone and happy holidays

**Comment by JiaLiPassion** [comment]
@eafiontzi, could you provide a reproduce repo? thanks!

**Comment by eafiontzi** [comment]
@JiaLiPassion thanks for answering. Unfortunately the main app is proprietary software of my company so I cannot share it but the web component is a test one so you can find it here zipped 
[test-component.zip](https://github.com/angular/angular/files/3997963/test-component.zip) (I really tried creating a stackblitz project instead but when I use the share link it shows the original code without my changes. I have signed in saved and shared but nothing) 

The component works great as a standalone app, inside the preview folder but when imported in a main Angular app it throws error. I tried removing the zone related imports from the web component but the error persists.

Thanks again for your time

**Comment by hansen-simon** [comment]
> Same here, but only in Safari <= 10.1
> 
> ![Zone](https://user-images.githubusercontent.com/11415752/61446161-07ce9380-a94f-11e9-9cd7-356783281730.PNG)

I had the same problem with old Safari versions. 
Solved it by adding the versions to the browserslist file: 
```
ios_saf >= 10
Safari >= 10
```

[founde here](https://github.com/angular/angular-cli/issues/15152#issuecomment-514572736)

**Comment by osmanraifgunes** [comment]
To help anybody facing problem, if you import core-js in sub modules you face this error .

`import { Object } from 'core-js';`

**Comment by sdudal** [comment]
Hello @JiaLiPassion! Do you have any updates when this changes will be released? Thanks in advance

**Comment by JiaLiPassion** [comment]
@sdudal, this one will be released very soon, thanks for the waiting.

**Comment by dsozzi** [comment]
hi @sdudal is there any news regarding this issue? thanks

**Comment by JiaLiPassion** [comment]
@dsozzi, this one has been fixed, could you check it in zone.js 0.10.3, thanks.

**Comment by dtslvr** [comment]
@JiaLiPassion Yes, `0.10.3` works for us!

**Comment by JiaLiPassion** [comment]
@dtslvr , thanks for the confirm.

**Comment by dsozzi** [comment]
Unfortunately it's not working on my side. The environment that I found the problem is as follow:
- angular element (angular 9)
- angular app (angular 8)

both running ng-zone 0.10.3

_The issue is present on ie11_. 
I try to include the angular element inside the angular app in the index.html file. if the element loads first I got the error in the object. I tried to include the element with a setTimeout and I don't get the error but the component (angular element) doesn't get clicks for example and I have to force using the zone.run()

**Comment by JiaLiPassion** [comment]
@dozzi, could you post a reproduce repo? And it seems your cases really import zone.js twice, I need see your setup to figure out the issue.

**Comment by Kr0san89** [comment]
@dsozzi i have exactly the same issue with the same constilation as you.
I found an "dirty" workaround.
On the component instantiating the Angular Element i do:
`
constructor(private zone: NgZone){}
ngOnInit() {
(window as any).ngZ = this.zone;
}
` 

and at the Angular Element main.ts
`
let zone;
if ((window as any).ngZ) {
  zone = (window as any).ngZ;
} else {
  zone = new NgZone({});
}
platformBrowserDynamic().bootstrapModule(AppModule, { ngZone: zone})
  .catch(err => console.error(err));
`

Also working is:
`
platformBrowserDynamic().bootstrapModule(AppModule, { ngZone: 'noop'})
  .catch(err => console.error(err));
`
Depending if you need Zone in Elements.

It looks like in Internet Explorer the Zone is newly instantiated with `new NgZone({});` and runs into the `Zone.assertZonePatched();` 

@JiaLiPassion hope this information helps you.
And as a small question is that a bad thing when the use the same "Zone"?

**Comment by alopezbr** [comment]
Hello everyone, 
@JiaLiPassion  I got a similar issue than @dsozzi .
Angular 8 custom element.
Angular 5 app (zone.js@0.10.3).

Works fine in Chrome and Firefox.
Throws **_Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten_.** error in IE11 and Edge.

Any idea why the new zone.js release will not fix the issue on IE11 and Edge??

Thanks!!

**Comment by bilgular** [comment]
Hello everyone, 
@JiaLiPassion  I got a similar issue than @dsozzi .
Angular 8 custom element.
Angular 5 app (zone.js@0.10.3).

Works fine in Chrome and Firefox.
Throws **_Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten_.** error in IE11 and Edge.

Any idea why the new zone.js release will not fix the issue on IE11 and Edge??

Thanks!!
