### ISSUE TITLE
Wrong validation in checkbox type

### ISSUE THREAD

**Issue by vahidvdn** [angular/angular#31721]
# 🐞 bug report

### Description

I have a form with some types of inputs. There is a mistake in the form validation in the `checkbox` type. First, I check the first item. Then I check the second one and then I uncheck the first one. It shows **error message**!

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-2oj6o6

## 🌍  Your Environment

**Angular Version:**
Angular 8.0.2

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
