### ISSUE TITLE
Publish `zone-patch-rxjs` also in `commonjs` module format

### ISSUE THREAD

**Issue by mlc-mlapis** [angular/angular#31725]
Because of using SystemJS loader with `commonjs` module format it would be nice to have also `zone-patch-rxjs` in that format to avoid manual and additional transpiling steps to get it.

Actually `zone-patch-rxjs` is published only using the following setting of `tsconfig-esm.json` -> `es2015` module format:
```
{
  "compilerOptions": {
    "module": "es2015",
    "target": "es5",
    ...
  }
```
```
gulp.task('build/rxjs.js', ['compile-esm'], function(cb) {
  return generateScript('./lib/rxjs/rxjs.ts', 'zone-patch-rxjs.js', false, cb);
});
```

**Comment by IgorMinar** [comment]
This has been addressed already in the recent versions of zone.js. See: https://unpkg.com/browse/zone.js@0.11.2/bundles/zone-patch-rxjs.umd.js
