### ISSUE TITLE
conventional-changelog 0.1.x is release

### ISSUE THREAD

**Issue by stevemao** [angular/angular#3172]
Just wondering if you guys are cool to switch to the latest version. All issues with the CHANGELOG here or in any related repos are fixed. Because of the rewrite, the syntax is completely changed. A few people are using it and I've been using it but I haven't found any problems so far. 
Related modules such as [conventional-github-releaser](https://github.com/stevemao/conventional-github-releaser) should also be good to use ~~but need more tests~~ tests are comprehensive now.

**Comment by mhevery** [comment]
@IgorMinar can you comment?

**Comment by stevemao** [comment]
I have fixed a few other bugs so it should be good to use.

**Comment by stevemao** [comment]
This is not closed properly. The message should say 
```
Closes #3204
Closes #3172
```

BTW, did you test it? The `changelog.js` script is not completely correct.

**Comment by rkirov** [comment]
ah, magic string parsing strikes again.

The new CHANGELOG.mk that was checked in with the change was gened by the script, so at least the basic functionality is working. Can you send me a PR fixing any other issues in `changelog.js`?

**Comment by stevemao** [comment]
Will do.

**Comment by rkirov** [comment]
Thanks!
