### ISSUE TITLE
Change detection doesn't fire after async method from the Web Audio API

### ISSUE THREAD

**Issue by robianmcd** [angular/angular#31736]
**I'm submitting a:** 
```
[x] bug report
```

**Current behavior**
After the callback runs from calling [AudioContext.decodeAudioData(buffer, callback)](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/decodeAudioData) change detection does not run

**Expected behavior**
change detection should occur after the callback runs

**Minimal reproduction of the problem with instructions**
With the following component:

```TypeScript
import { Component, ViewChild } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
  <div>Status: {{status}}</div>
  <div><button (click)="decodeAudio()" [disabled]="status === 'loading audio'">Decode Audio</button></div>
  <div><button (click)="onTrigger()">Trigger Change Detection</button></div>
`
})
export class AppComponent { 
  status = 'loading audio'; 
  buffer: ArrayBuffer;
  
  constructor() {
    var request = new XMLHttpRequest();
    var url = 'https://dl.dropboxusercontent.com/u/20066539/Forum%20Links/audiocheck.wav';
    request.open('GET', url, true);
    request.responseType = 'arraybuffer';
    
    request.onload = () => {
      this.buffer = request.response;
      this.status = 'audio loaded';
    }
    request.send();
  }
  
  decodeAudio() {
    var context = new AudioContext();
    
    this.status="decoding audio";
    
    context.decodeAudioData(this.buffer, () => {
      this.status="finished decoding audio";
    });
    
  }
  
  onTrigger() {
    console.log(this.status);
  }
}
```

1. Click the 'Decode Audio' button once it is enabled.
2. Observe that the status text never changes to 'finished decoding audio' (should take less than a second)
3. Click the "Trigger Change Detection" button which just calls console.log
4. Observe that the status text is updated to 'finished decoding audio'

Plunker that demonstrates the issue: https://plnkr.co/edit/XmcZf9etKLoBK92gT9cz?p=preview

**What is the motivation / use case for changing the behaviour?**
using the web audio API in an Angular 2 app

**Please tell us about your environment:**

* **Angular version:** 2.4.1
* **zone.js version:** 0.7.2
* **Browser:** [all]

Moving this issue over from angular/angular https://github.com/angular/angular/issues/13930

**Comment by alxhub** [comment]
Closing due to insufficient votes.
