### ISSUE TITLE
Safari does not patch Image.prototype.onload

### ISSUE THREAD

**Issue by mhevery** [angular/angular#31739]
https://plnkr.co/edit/QRY99XlPaH3DyakQbRKN?p=preview

```
var zone = Zone.current;
let img = new Image();
img.src = "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png";
img.onload = _=> {
  expect(Zone.current).toBe(zone);
};
```

**Comment by atscott** [comment]
Tested in latest version of Angular and Safari and this appears to work now:
https://stackblitz.com/edit/angular-ivy-mqckax?file=src%2Fapp%2Fapp.module.ts
