### ISSUE TITLE
Zone.js breaks Web Animations polyfill on iOS 7

### ISSUE THREAD

**Issue by code-tree** [angular/angular#31737]
The Web Animations polyfill needs to catch an error to work properly on iOS 7, but zone.js is silencing that error.

The error is silenced here: https://github.com/angular/zone.js/blob/402971a5296d3f082364dac290e03fe7e1cbd038/lib/browser/define-property.ts#L91-L102

The error needs to be caught by Web Animations here: https://github.com/web-animations/web-animations-js/blob/e5e2e872b7cd9de90eba45cd4893a7e7e0006a0b/src/apply-preserving-inline-style.js#L160-L171

This causes my Angular2 app that uses both zone.js and Web Animations polyfill to fail on iOS 7 (crashes Safari). I fixed it by rethrowing the error in zone.js.

**Comment by JeanMeche** [comment]
The supported browsers don't need that polyfill anymore. I'll close this issue as not relevant anymore.
