### ISSUE TITLE
Error: Permission denied to access property "apply"

### ISSUE THREAD

**Issue by hmdhk** [angular/angular#31738]
This Issue happens when using walkme.com firefox extension.

to reproduce:
- install walkme.com firefox extension
- load a page with zone.js
- record some steps with walkme
- click "Preview" in walkme

![image](https://cloud.githubusercontent.com/assets/6134122/19430611/1d43cd5a-9455-11e6-9cf5-61a066ecdba8.png)

Update:
As you can see the error is in patchProperty/desc.set. In this case it is trying to set 'load' event on a script with a different origin and when the event fires this error happens. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Property_access_denied) "Permission denied" could be the result of cross-origin issue.

**Comment by JeanMeche** [comment]
I'm closing this issue as we didn't get any other reports in the last 8 years.
