### ISSUE TITLE
Error when trying to clean up spies after running jasmine tests since jasmine 2.5.0

### ISSUE THREAD

**Issue by GZidar** [angular/angular#31732]
A change in the way that jasmine is cleaning up its spies means that as of version 2.5.0 of that testing framework the test results will not display in the browser window when using the tool in conjunction with zone.js patching.

This issue can be reproduced using any of the angular 2 testing samples if the package definitions for jasmine are updated to 2.5.0 or higher. The developer of Jasmine has suggested that this issue is related to the way jasmine is patched to work with zone js so a fix needs to be implemented here rather than in jasmine itself.

**Comment by alxhub** [comment]
Closing as obsolete.
