### ISSUE TITLE
question: debugging zone.js performance issues 🐌  🌩️

### ISSUE THREAD

**Issue by samccone** [angular/angular#31731]
I have recently been debugging angular 2 apps who have been running into performance problems rooted in what seems to be zone.ts (I would share screenshots but they are currently not public things, and yes I acknowledge this makes my question harder to answer directly).

my observations have been that I have a lot of call stacks that terminating or originate in the following root functions:

scheduleMicroTask
scheduleMacroTask
scheduleQueueDrain

or in some other cases timer

--

My normal approach for debugging perf issues follows the ideas of M.P.D.I.A
measure, profile, diagnose, identify, attempt 

In the real world this looks like:

1. record a timeline
2. look at a segment of the timeline using the bottom up profiler
3. identify the heaviest stacks
4. identify what is starting the stacks to happen (a callback? a user action? a loop?)
5. change what is causing the work and see if there is an impact

But with zone.ts code, i see very very long stacks 99% of which is inside of zone code (counting self time) and very little of the self time in userland code, making my process hard to follow.

So here is my question, how does one go about profiling code that is using zone? Is there a way to disable zone to see if it is the root issue? Is there a special perf technique for debugging zone code that requires knowledge of how zone is implemented?

Thanks in advance!

**Comment by Hamcker** [comment]
In my case it was from `ngx-spinner` library.

**Comment by jelbourn** [comment]
Closing this to track in #34735, which covers adding documentation for performance tuning for Angular applications.
