### ISSUE TITLE
Change detection doesn't fire after Web MIDI API callback

### ISSUE THREAD

**Issue by robianmcd** [angular/angular#31733]
Change detection doesn't fire in an Angular 2 app after receiving a MIDI message through the Web MIDI API.  e.g. The following component listens to all MIDI messages and displays the most recent message but the message only shows up after doing something like clicking a button.

```TypeScript
@Component({
  selector: 'my-app',
  template: `
  <div>
    Listening to:
    <div *ngFor="let device of devices">{{device.name}}</div>
  </div>
  <div>
    Last Message: [{{lastMsg[0]}}, {{lastMsg[1]}}, {{lastMsg[2]}}]
  </div>
  <button (click)="onClick()">Trigger Detection</button>
`
})
export class AppComponent {
  lastMsg = [];
  devices = [];
  
  
  constructor() {
     navigator.requestMIDIAccess()
      .then((midiAccess) => {
          midiAccess.inputs.forEach((device) => {
            this.devices.push(device);
            device.onmidimessage = (message) => {
              this.lastMsg = message.data;
            }
        });
      })
  }
  
  onClick() {
    
  }
  
}
```

Plunker: https://plnkr.co/edit/wf7CLlnsTBc0GO8jbyzD?p=preview

I tried wrapping `this.lastMsg = message.data;` with `Zone.current.run();` but it still didn't update the view. If I inject `ChangeDetectorRef` and call `detectChanges()` then the view will update but in the actual application I'm building it's not so easy to track down all the components I need to trigger change detection on (although I guess I could trigger it on the root component). Any ideas on other ways I could work around this?

**Comment by alxhub** [comment]
Closing due to insufficient votes.
