### ISSUE TITLE
No tick call when using phonegap + hammerjs + angularjs or zonejs + android

### ISSUE THREAD

**Issue by daedeloth** [angular/angular#31735]
I have an app built in angular2 that works fine in browser and when phonegap-bundled for iOS. It uses hammerjs to handle touch events like pan and pinch.

However, when I bundle it for Android, things go haywire.

After some debugging I managed to isolate the problem to "tick" not being called as often as it should. On iOS and in browser (any browser really, even IE), during any drag action the tick method is called on even the slightest move. When bundled for android, it is only called at the end of the drag, and even then not always.

I've added a console.log in core.umd.js to monitor the tick method calls, so I'm pretty sure the problem originates here.

Anyone else noticed similar behaviour?

Isolated case available at:
https://github.com/daedeloth/phonegap-hammer-zone-angular-issue

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
