### ISSUE TITLE
Losing zone in RxJS and fetch

### ISSUE THREAD

**Issue by alvipeo** [angular/angular#31749]
For my angular 2 project I created a service that uploads files and I use fetch API there and RxJS. But it doesn't keep angular zone, here:

```
return uploadFileUri$
            .map(uri => {
                uploadFileUri = uri;
                return file.loadBlocksWithFileData();
            })
            .switch()
            .mergeMap((blk: IlgBlock) => {
[ ... some unrelated stuff ... ]
                console.log("Zone1: " + Zone.current.name);

                return fetch(putUri, reqOptions);
            }, (blk: IlgBlock, resp: Response, idx) => {
                console.log("Zone2: " + Zone.current.name);

                return [blk, resp];
            }, 1  // fetch ONE at a time
            )
[ ... other operators ...]
```

the output is:

> Zone1: angular
> Zone2: root

This shouldn't be like it I think. As a result, component's view doesn't ever get updated.

Also, once zone is lost it never gets back to 'angular'. So I see angular only the first time it runs.

zone: 0.6.8.

**Comment by JiaLiPassion** [comment]
Now we have a patch for `fetch` API, so this issue can be closed
