### ISSUE TITLE
Error when running zone.js in a web worker in Safari browser

### ISSUE THREAD

**Issue by urimor** [angular/angular#31740]
The problem is in patchViaCapturingAllTheEvents() which is the workaround for patching on-properties in browsers other than Chrome & Firefox.

The patch is made by calling document.addEventListener() but in a web worker, the call to document causes error.

In our fork we fixed this (c359ce719ddaa73317cb40e78ba516fdab149837) by changing document.addEventListener() to self.addEventListener().

Thanks

**Comment by jelbourn** [comment]
Closing since this is four years old and there's not really enough information to go off for investigating anything.
