### ISSUE TITLE
Relate different XMLHttpRequest tasks to the original request

### ISSUE THREAD

**Issue by jahtalab** [angular/angular#31743]
Currently on mobile browsers, the target for eventTasks related to XMLHttpRequests (like onreadystatechange) and the target for XMLHttpRequest.send macroTask are two different instances. so it's not possible to relate the two.

this is useful when we want to make sure all the event listeners for a http request has been fired before we do anything else.

**Comment by jelbourn** [comment]
Closing since this seems like a feature request and I don't believe it's something we plan on supporting.
