### ISSUE TITLE
Zone.js causing event property to be undefined on HTML element

### ISSUE THREAD

**Issue by TJ-Dev** [angular/angular#31742]
The event property of an element loaded using div.innerHTML is undefined when zone.js is included on the page. The event property is correctly defined when zone.js is not included. 
Including zone.js is causing issues with third-party libraries using the innerHTML.

Example (please see attached file for full example):

``` javascript
function clickHandler() {
    var innerDiv = document.getElementById('inner');
    // onclick event handler is undefined when zone.js is loaded.
    console.log('innerDiv onclick', innerDiv.onclick); 
}

function bodyLoaded() {
     var hostDiv = document.getElementById('host');
    hostDiv.innerHTML = '<div id="inner" onclick="clickHandler()"></div>';
}
```

[zone.html.txt](https://github.com/angular/zone.js/files/368500/zone.html.txt)

**Comment by mhevery** [comment]
https://stackblitz.com/edit/web-platform-mrmqai shows that the repro is working.
