### ISSUE TITLE
Implementation specific limitations with Zone.js

### ISSUE THREAD

**Issue by gionkunz** [angular/angular#31758]
While investigating the problems with Indexed DB described in #202 , I've noticed that Zone.js proxies seem to modify scope in a way that can cause problems depending on the implementation of event handling within specific code.

After monkey patching https://github.com/angular/zone.js/blob/master/lib/patch/event-target.js and https://github.com/angular/zone.js/blob/master/lib/patch/property-descriptor.js I was able to use Indexed DB with correctly established Zones. However, when using PouchDB which is a wrapper around Indexed DB (and other storage) the patch does not seem to work in a way that breaks PouchDB.

PouchDB is using "inline handlers" (`request.onsuccess = function...`) that were covered using my monkey patch in https://github.com/angular/zone.js/blob/master/lib/patch/property-descriptor.js by using `utils.patchProperties(IDBRequest.prototype)` (and others). However, somehow the proxies seem to break PouchDB and I don't get the results. When using Indexed DB directly, the patch seems to work.

I know this is hard to reproduce, but are there any known limitations of the proxies within Zone.js ?

**Comment by jelbourn** [comment]
Closing this issue because I think it is obsolete; zone.js was rewritten from scratch in 2016 which should have resolved this.
