### ISSUE TITLE
ZoneJS does not work with Handsontable

### ISSUE THREAD

**Issue by nicam** [angular/angular#31754]
Hi There

There's an issue in Handsontable when it's used inside an Angular2 application. This seems to be caused by ZoneJS (see reason below). When you copy a row and paste it into a different row on Chrome, 2 rows are inserted instead of one.

Do you have any hint how I could work around this issue or how it might be solved?

![Gif Showing the Error](http://g.recordit.co/ibpy9VgiT2.gif)

It only happens when Handsontable is running inside Angular2. I think this is somehow related to ZoneJS since this issue seems also be happening in MeteorJS when the ZoneJS Bundle is used there (https://github.com/awsp/handsontable-meteor/issues/17).

You can reproduce it here: https://valor-software.github.io/ng2-handsontable/

**Steps to reproduce:**
- Open example page in Chrome (47.0.2526.111)
- Click on a single row
- CMD+C (on Mac)
- Click on a different row (has to be writable)
- CMD+V

Two rows are inserted.

Any idea why ZoneJS might cause this issue on Chrome?

Best regards and thank you for your help!

Pascal Helfenstein

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
