### ISSUE TITLE
Object.defineproperties does not work well with symbols

### ISSUE THREAD

**Issue by david-gang** [angular/angular#31750]
Hi all,

This is a continuation of the SO http://stackoverflow.com/questions/36111582/is-it-valid-to-use-object-defineproperties-with-symbols

It should be valid to define Object.defineproperties with symbols. 

However the implementation at https://github.com/angular/zone.js/blob/master/lib/browser/define-property.ts#L22-L27 uses Object.keys which does not take symbols into account.

So the following code would not work well

``` javascript
var obj = {};
var x = Symbol();
Object.defineProperties(obj, {
  [x]: {
    value: true,
    writable: true
  },
  "property2": {
    value: "Hello",
    writable: false
  }
  // etc. etc.
});
console.log(obj[x])
```

It would print undefined.

This causes also problems in https://github.com/ngUpgraders/ng-forward/issues/158

There is also a comment in SO which advises not to polyfill it at all if it is already defined. Is this possible?

Anyway the solution proposed there is that we should use instead of Object.keys(props) 
Object.getOwnPropertyNames(props).concat(Object.getOwnPropertySymbols(props))

If the core contributors agree to this solution I could craft a PR.
Thanks,
David

**Comment by compulim** [comment]
To verify if `Object.defineProperties` is good or not, run the following code in browser.

```js
Object.defineProperties({}, { [Symbol.iterator]: {}, abc: {} });
```

Good: `{ abc: undefined, [Symbol.iterator]: undefined }`

Bugged: `{ abc: undefined }`

FYI, `Object.defineProperties` is [native on IE9+](https://caniuse.com/#search=defineproperties) but zone.js polyfill it regardless.

**Comment by jelbourn** [comment]
Took a look at this- as far as I can tell, I now get the same behavior with and without zones loaded on the page (both in Chrome and in IE11). Closing for now, feel free to open a new issue with more details.
