### ISSUE TITLE
static methods are missing from angular2.d.ts

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#3175]
Reported in https://github.com/borisyankov/DefinitelyTyped/issues/4769

our current published .d.ts contains
```
class Validators {
}
```
but the original source in `forms/validators.ts` contains
```
export class Validators {
  static required(c: modelModule.Control): StringMap<string, boolean> {
...
```

**Comment by alexeagle** [comment]
Have to push this off since I'm occupied with the syncmaster on-duty.

**Comment by NathanWalker** [comment]
Hope this makes it in 34 ... If I had time to offer a PR I would, if this is still open in couple days, I could certainly help.

**Comment by alexeagle** [comment]
Probably not in 34 as that is getting cut today.
I have not started on this so if you'd like to send a PR it would be really
appreciated!

**Comment by alexeagle** [comment]
Punting to next milestone, maybe @NathanWalker will get to this before I can.

**Comment by NathanWalker** [comment]
@alexeagle sorry I haven't been able to get to this yet.
I did look at the typings template last week and the setup had changed a bit since some of the earlier alpha versions and was unable to understand fully what needed to be done to make the static methods available in the .d.ts file.

**Comment by alexeagle** [comment]
Thank you for letting me know the status! I'll try to look today or tomorrow.
