### ISSUE TITLE
zone.js + sweetalert = no callback called

### ISSUE THREAD

**Issue by MichaelJCole** [angular/angular#31753]
Hi, I'm using zone.js packaged for Meteor.  When mixed with sweetAlert, zone.js prevents sweetAlert's callback from happening.

Is there a way to turn zone.js off for a block of code?  Sorry if I don't really understand zone.js.

For example this code:

```
swal({
  title: 'Are you sure?',
  text: 'You will not be able to recover this imaginary file!',
  type: 'warning',
  showCancelButton: true,
  confirmButtonText: 'Yes, delete it!',
  cancelButtonText: 'No, keet it',
}, function() {
  console.log('Your imaginary file has been deleted.');
});
```

Without zone.js, no problem.

With zone.js, this error is reported, which appears to prevent the callback:

```
Error: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
    at TypeError (native)
    at s (https://dashboard-dev.hello.io/packages/patrickml_swal.js?06d775f51a9debdd71fd5de7eb0594d0e94eed1b:32:7559)
    at HTMLButtonElement.p (https://dashboard-dev.hello.io/packages/patrickml_swal.js?06d775f51a9debdd71fd5de7eb0594d0e94eed1b:32:3375)
```

FYI: https://github.com/meteorhacks/zones/issues/85

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
