### ISSUE TITLE
Global imports with browserify ES6 syntax

### ISSUE THREAD

**Issue by Emnalyeriar** [angular/angular#31755]
I'm using Gulp with Browserify as my build tools.
Angular2 needs zone as a global variable, normally I would do this like that:

``` javascript
window.zone = require('zone.js');
```

but I have a problem when it comes to ES6 syntax and TypeScript.
Tried doing it like this:

``` javascript
import 'zone.js';
(<any>window).Zone = zone;
```

but this of course shows an error "Cannot find name zone' because variable zone is not defined anywhere.
Then I tried defining it like this:

``` javascript
import * as zone from 'zone.js';
(<any>window).Zone = zone;
```

and now I get "Cannot find module zone.js" but the weird thing is that it works and browserify compiles it correctly.
Also tried:

``` javascript
import {zone} from 'zone.js';
```

but this causes the same error "Cannot find module zone.js.

Could anyone help me how should I import it correctly?

**Comment by jelbourn** [comment]
Closing this since I believe it is obsolete; including polyfills and zones is handled by the Angular CLI at this point
