### ISSUE TITLE
Patch all browsers API returning Promise

### ISSUE THREAD

**Issue by vicb** [angular/angular#31762]
All browsers API returning Promise should be patched.

This is required because the returned Promises would not extend the monkey-patched Promise by default.

It seems like patching might not be needed when microtasks are not used (the monkey patch on the Promise.prototype **is** taken into account on latest Chrome version (44) but it fails on earlier version. It should probably be tested when other browsers implement the API before we remove the patch on zone.js - we **must** keep it for zone-microtask.js)

ref:
- `fetch()` has been patched in #119 
- idl can be download via the script in #118

**Comment by AndrewKushnir** [comment]
Closing this ticket since ZoneJS already covers a large subset of APIs and we can create new tickets in case additional APIs should be patched.
