### ISSUE TITLE
Explore a compile-time step to add hooks

### ISSUE THREAD

**Issue by btford** [angular/angular#31768]
I'm mostly just brainstorming/documenting this idea. I'm not sure if it's worth taking a shot at implementing it.

Suggested by @mikeal [over here](https://twitter.com/mikeal/status/450730662920589312).

Pros:
- might be a smaller code size
- might be faster since you can unwrap/inline hooks

Cons:
- can't call any code that you didn't compile – you can't include `jquery.js`; you'd have to preprocess it first.
- perhaps harder to implement than patching (probably can't use static analysis) – `['setTimeout'].forEach(function (fn) { ... }};`

**Comment by AndrewKushnir** [comment]
This was implemented for the `ngOnChanges` lifecycle hook to provide better tree-shaking, see [ng_onchanges_feature.ts](https://github.com/angular/angular/blob/master/packages/core/src/render3/features/ng_onchanges_feature.ts).
