### ISSUE TITLE
Debug Zone

### ISSUE THREAD

**Issue by mhevery** [angular/angular#31764]
Have a `DebugZone` which would print out when each bound method got called (such as `addEventListener`) and it would print out when each bound method callback got called (such as `addEventListener(foo, callback)`)

The print out should include the `Zone.id` and the arguments which were used when registering the callback.

**Comment by atscott** [comment]
@mhevery @JiaLiPassion  Is this still relevant?

**Comment by JiaLiPassion** [comment]
@atscott , I do have some plan to make some similar feature, I will create another issue to describe it. we can close this for now.
