### ISSUE TITLE
Zone.js does not work with WTF

### ISSUE THREAD

**Issue by mhevery** [angular/angular#31761]
https://github.com/google/tracing-framework/issues/531

1) Go to: http://mhevery.github.io/github_issues/ and see Angular2 app running.
2) turn on the WTF extension "Enable Recording for this URL"
3) Observe that Angular2 app is no longer running. 

I don't see any exception in the console. It seems as if the WTF extension is somehow breaking the System.js module loader and preventing it from loading Angular 2 app.

1) WTF monkey patches the XMLHttpRequest object. 
2) Angular, through zone.js then monkey patches the XMLHttpRequest again.
3) system.js sends of a request to load the code code.
  3.a) WTF sees the response, but when it tries to forward the request on, it fails
  3.b) the syntem.js does not see the response.

So it seems like the WTF and zone.js do not like each other when monkeypatching.

Zone.js way of monkey patching:
- https://github.com/angular/zone.js/blob/08c7084046f9c9ab8b25d739bbb398be8476cdfe/lib/patch/event-target.js
- https://github.com/angular/zone.js/blob/d8a7457cb5aefdde8ebaab9e72383d90321defd0/lib/utils.js#L87

WTF monkey patching code:
- https://github.com/google/tracing-framework/blob/661b2031b13e0535403c169d769123d659649720/src/wtf/trace/providers/xhrprovider.js#L75

If you click the gear on the WTF HUD that's on the page and go to Providers at the bottom you can uncheck the XMLHttpRequest provider. Then the page works great. So it's definitely this causing a problem.

XHR lives here:
https://github.com/google/tracing-framework/blob/master/src/wtf/trace/providers/xhrprovider.js#L103

I actually swap out the entire XMLHttpRequest object with that version.

It subclasses BaseEventTarget, which adds the addEventListener/removeEventListener methods:
https://github.com/google/tracing-framework/blob/master/src/wtf/trace/eventtarget.js#L431

I'm not seeing anything that stands out as a possible problem.
It's possible patchProperty in zone.js is also messing with things (if you're using the on\* properties instead of addEventListener).

1) WTF creates a new XHR implementation and replaces the global one.
2) Zone.js patches only EventTarget (not the XHR) since it assumes that XHR inherits from EventTarget
  2a) as a result zone does not patch the WTF-XHR.

So the above is definitely a problem, but it should manifest as a broken VMTurn detection not as broken XHR. So I don't understand why it is a problem.

**Comment by IgorMinar** [comment]
I'm going to close this one as obsolete.
