### ISSUE TITLE
Angular application has been freezing for some time when create duplicate tab - Chrom

### ISSUE THREAD

**Issue by chintan12** [angular/angular#31777]
# 🐞 bug report

### Description
Hi, I am facing one issue in angular like I have a page which is having the basic angular form as well three independent components which are basically loading the list from API like and Highchart of the list, wavesuffer js for listing mp3.

Angular application has been freezing for some time when creating a duplicate tab - Chrom 

## 🌍  Your Environment

That issue is producing on both local as well as production.

**Angular Version:** 6

**Comment by trotyl** [comment]
Please provide a minimal reproduction for others to investigate. You can use https://stackblitz.com/ or share a newly create Angular CLI application in GitHub.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
