### ISSUE TITLE
Philosophy of Angular in the docs.

### ISSUE THREAD

**Issue by quangv** [angular/angular#31774]
# 📚 Docs or angular.io bug report

### Description
 
The introduction should include more of the philosophy of Angular, much like AngularJS' introduction page.

## 🔬 Minimal Reproduction

https://angular.io/docs (intro page)
vs
https://docs.angularjs.org/guide/introduction (AngularJS' intro page)

### What's the affected URL?**

https://angular.io/docs

```
(N/A)
### Reproduction Steps**
<!-- If applicable please list the steps to take to reproduce the issue -->
<!-- ✍️edit:-->

### Expected vs Actual Behavior**
<!-- If applicable please describe the difference between the expected and actual behavior after following the repro steps. -->
<!-- ✍️edit:-->


## 📷Screenshot
<!-- Often a screenshot can help to capture the issue better than a long description. -->
<!-- ✍️upload a screenshot:-->


## 🔥 Exception or Error
<pre><code>
<!-- If the issue is accompanied by an exception or an error, please share it below: -->
<!-- ✍️-->

</code></pre>


## 🌍  Your Environment

### Browser info
<!-- ✍️Is this a browser specific issue? If so, please specify the device, browser, and version. -->
```

### Anything else relevant?

I am new to Angular and been reading the docs for a bit. I had to asked a couple Angular veterans if they can point me to a philosophy of Angular. And they proceeded to tell me.

I asked them if the philosophy changed between AngularJS and Angular (2+), and they said the philosophy was much the same. About super-charging the HTML in a declarative way to give it super powers...

I think a little more of this romanticize philosophy, could go into the new Angular docs!

 _"Why Angular?"_

Regards.

**Comment by kapunahelewong** [comment]
Hi @quangv, thanks for your feedback. You might find that the following pages share the Angular perspective:

- If you scroll down here, there are four points highlighted: https://angular.io/ (This one seems the most obviously in line with "Why Angular".)
- Similar to the above with a little more detail: https://angular.io/features 
- The blog, where the latest and greatest reasons to use Angular are featured: https://blog.angular.io/

Let me know your thoughts. If you have a particular idea for a PR beyond the above links, please feel free to share. We're always open to discussing and trying out different ways to grow and evolve.

**Comment by quangv** [comment]
I still believe the introduction should provide a little bit more personality and over-arching philosophy. More a "love letter" like AngularJS introduction, versus a list of features. The _"Zen of Angular"_ for example, if there still is one.

It'll be good for brand new developers who haven't had experience with AngularJS to know the heart/philosophy of Angular, an overview of it's approach.

**Comment by kapunahelewong** [comment]
Thanks for your thoughts, @quangv. I'll share this thread with the docs team!

**Comment by kapunahelewong** [comment]
Status:  docs team is working on a refactor of the docs. This may prove especially helpful in that effort. 

Thank you, @quangv! 

cc @rockument69

**Comment by rockument69** [comment]
In the new doc structure, the first page (after the home page) that describes Angular is **Getting Started > Angular Concepts> [Intro to Basic Concepts](https://angular.io/guide/architecture)** page, which will have the new title "Introduction to Angular concepts". There will also be a link to this page from the home page.

**Comment by aikidave** [comment]
Marking this as closed as we not only updated the introduction to Angular topic, but added a What is Angular topic (https://angular.io/guide/what-is-angular), which I think helps cover the points raised in this issue.
