### ISSUE TITLE
Lazy Loading with params

### ISSUE THREAD

**Issue by Kappyh** [angular/angular#31778]
# 🚀 Lazy Loading with params

### Relevant Package
This feature request is for @angular/router and @angular/core
Angular version 8.

### Description
I can't do lazy loading with params between the children and his parent.
Like this:
https://rotas817351.stackblitz.io/dealership/1/about
My child route 'about' don't get the param with ActivatedRoute, the params properties comes empty. 
Example in stackblitz: https://stackblitz.com/edit/rotas817351

### Describe the solution you'd like
Some propertie in the navigate from Router that allows us to pass this params and persist for the others lazy routings.

### Describe alternatives you've considered
I tried many workarounds described in https://github.com/angular/angular/issues/19420

**Comment by djleonskennedy** [comment]
Hallo @Kappyh 
angular has it already

```
RouterModule.forRoot(
      [ ],
      {paramsInheritanceStrategy: 'always'}
    )
```

make sure that you have uniq "id" names

**Comment by Kappyh** [comment]
Nice!! I'm outdated in angular issues lol I'll try this solutions. Thank yout!
