### ISSUE TITLE
window.onerror

### ISSUE THREAD

**Issue by blittle** [angular/angular#31771]
Chrome recently landed an awesome new feature where an actual error object is passed to `window.onerror`. Without an actual error object, it is really difficult make use of the `window.onerror` because the original context is lost and no stack trace is available. Even libraries like stacktrace.js are unable to work around this.

Any idea if zone.js is able to work around this for IE and FF? 

References:
https://code.google.com/p/chromium/issues/detail?id=147127
https://bugzilla.mozilla.org/show_bug.cgi?id=355430
https://github.com/stacktracejs/stacktrace.js/issues/26

**Comment by JiaLiPassion** [comment]
This has been implemented, will close now.
