### ISSUE TITLE
Support all native boundaries where callbacks happen

### ISSUE THREAD

**Issue by btford** [angular/angular#31770]
via @Raynos here: https://github.com/btford/zone.js/issues/10

Main IO interfaces to support:
- [x] ES6 promises
- [x] IndexedDB
- [x] webrtc
- [x] requestAnimationFrame
- [x] setImmediate
- [x] EventSource
- [x] WebSocket
- [ ] HTML5 File system
- [ ] History API
- [ ] postMessage
- [ ] iframes
- [ ] web workers
- [x] WebGL

There are probably others

**Comment by vladkasianenko** [comment]
> Are there any news on implementing this for IndexedDB?

You can use libs like Dexie.js to deal with IndexedDB.

**Comment by AndrewKushnir** [comment]
It looks like most of these APIs are already covered by ZoneJS. If there are some missing ones, we can create new ticket(s).
