### ISSUE TITLE
Angular 6 application and search-engine optimization, empty Google cached page version

### ISSUE THREAD

**Issue by askbs** [angular/angular#31794]
When we open the website its working fine but when we check it SCO purpose it can't be open. Here is the URl -

http://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fwww.uzyth.com&oq=cache%3Ahttps%3A%2F%2Fwww.uzyth.com&aqs=chrome..69i57j69i60j69i58j69i60l2.2214j0j4&sourceid=chrome&ie=UTF-8

We have make a dynamic HTML page for change the languages. We can use to bind the data from JSON using innerHTML and also we use the safeHTML pipe also.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
