### ISSUE TITLE
AsyncPipe doesn't register identical numbers as a change

### ISSUE THREAD

**Issue by StevenSerrien** [angular/angular#31799]
# 🐞 bug or intended?

### Description

Hello everyone, I'm trying to figure out as to why my AsyncPipe is not exactly behaving like a basic subscription. I have an external subject to which I next numbers upon. This subject is given to a child-component through the Async pipe, which then displays whatever given in its template.

For this easy test case, I also want to reset that internal `@Input()` of the child component whenever I want to, to 0. However, when I did reset that internal value to 0, and try to next another number ( the same number as I previously did ), the `@Input()` setter does not pick up any change coming from the Async subscribed subject. I'm guessing the Async-pipe has some logic built in that covers duplicates? Although, I would think that it would act the same as a subscription on that Subject, because a normal subscription does log every entry, even identical ones.

Unsure if this is a bug, or just something that is intended.
I've read the documentation and it only says that `When a new value is emitted, the async pipe marks the component to be checked for changes.`, but I was thinking it is mentioning that for the change detection itself?
Or is the AsyncPipe simply built to only act whenever the value has changed from the previous one,
as sending through objects always triggers it?

Any help is highly appreciated.

## 🔬 Minimal Reproduction
I've created a StackBlitz, just click on the first button to next 200 for the first time, then click the second button to reset it internally in the child component and then try to do another next of 200.

https://stackblitz.com/edit/angular-xvahxd

**Comment by santoshyadav198613** [comment]
Hi @StevenSerrien ,
The issue is not with asyncPipe , this is because the way the code is written, on reset you should call next again to update the counter value, which you are missing.

change your reset to 

```ts
enterData() {
    this.data = Array.from(new Array(10), (x, i) => ({
      id: i,
      name: `Character ${i}`,
    }));
    
     this.count$.next(0);
}
```

**Comment by trotyl** [comment]
Relates to https://github.com/angular/angular/issues/29927

**Comment by StevenSerrien** [comment]
> Hi @StevenSerrien ,
> The issue is not with asyncPipe , this is because the way the code is written, on reset you should call next again to update the counter value, which you are missing.
> 
> change your reset to
> 
> ```ts
> enterData() {
>     this.data = Array.from(new Array(10), (x, i) => ({
>       id: i,
>       name: `Character ${i}`,
>     }));
>     
>      this.count$.next(0);
> }
> ```

Hi @santoshyadav198613, thanks for your reply.
I guess that that's the issue tho, what if I'm building a library and for the sake of convenience do not want the user that is using the hellocomponent from library to have to manually send a next on its subject to reset it, but rather handle it inside the library component. Seems like a valid usecase, no ?

**Comment by petebacondarwin** [comment]
As far as I can tell this is working as expected. Since the observable only ever emits `200`, the `@Input() count` property is only ever set to 200 (by Angular). So even if you change it internally it will not be marked dirty.

Consider if you did not use an Observable. See https://stackblitz.com/edit/angular-ewemot?file=src%2Fapp%2Fapp.component.ts

Despite the change to `data` setting the internal `count` property to 0, setting the external value for `count` to 200 is a noop.
