### ISSUE TITLE
how to use ::ng-deep inside @media query syntax?

### ISSUE THREAD

**Issue by manikandanm143** [angular/angular#31795]
i want to use ng-deep inside css media query.
@media (min-width: 1025px) and (max-width: 1280px) {
     ::ng-deep.bs-datepicker {
         left: var(--my-var) !important;
     }  
}

**Comment by GuilhermeBCC** [comment]
Try stackoverflow. Here are issue about angular development.

**Comment by ChellappanRajan** [comment]
Try this:

::ng-deep.bs-datepicker {
  @media (min-width: 1025px) and (max-width: 1280px) {
    left: var(--my-var) !important;
  }
}

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
