### ISSUE TITLE
PortalInjector does not delegate parentInjector to dynamically created component

### ISSUE THREAD

**Issue by BlindDespair** [angular/angular#31819]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/cdk or @angular/core

### Is this a regression?

 No

### Description

 I have a lazy loaded module, which has entry components defined in it. I've built a shared service using @angular/cdk for opening modal windows. In my lazy module I have a provided service for backend communication. My modal is opened through its own service that is provided on component that can open that modal(but inside uses the shared service). But in my modal component I am not able to inject the service that is provided in my lazy loaded module! I am getting `NullInjectorError`. I thought maybe it's because shared service was creating the portal injector, so I passed injector of my scoped service to the shared one as a parameter and used that, however it's still NullInjectorError. I don't get it, I should be able to inject my service somehow, I don't want to make that modal component globally available, because it's coupled to the lazy loaded module. It makes no sense to make it accessible outside. A workaround I can I think about is that I could recreate injection token for that http service in my scoped service and pass it to modal dialog service, which will set it on PortalInjector. And for now I will probably do it, but I am convinced it should be possible to reuse parent injector in angular out of the box.

## 🔬 Minimal Reproduction

 You can reproduce issue in https://github.com/BlindDespair/injector-bug.

## 🔥 Exception or Error
<pre><code>

core.js:7187 ERROR NullInjectorError: R3InjectorError(AppModule)[SolutionService]: 
  StaticInjectorError(AppModule)[SolutionService]: 
    StaticInjectorError(Platform: core)[SolutionService]: 
      NullInjectorError: No provider for SolutionService!
    at NullInjector.get (http://localhost:4200/vendor.js:26173:27)
    at resolveToken (http://localhost:4200/vendor.js:26500:24)
    at tryResolveToken (http://localhost:4200/vendor.js:26426:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:26289:20)
    at resolveToken (http://localhost:4200/vendor.js:26500:24)
    at tryResolveToken (http://localhost:4200/vendor.js:26426:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:26289:20)
    at R3Injector.get (http://localhost:4200/vendor.js:43485:33)
    at NgModuleRef$1.get (http://localhost:4200/vendor.js:51942:33)
    at Object.get (http://localhost:4200/vendor.js:49822:35)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

OS: darwin x64
Angular: 8.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.2
@angular-devkit/build-angular     0.801.2
@angular-devkit/build-optimizer   0.801.2
@angular-devkit/build-webpack     0.801.2
@angular-devkit/core              8.1.2
@angular-devkit/schematics        8.1.2
@angular/cdk                      8.1.1
@ngtools/webpack                  8.1.2
@schematics/angular               8.1.2
@schematics/update                0.801.2
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Comment by mhevery** [comment]
Can you simplify the example and turn it into stackblitz. We have limited amount of time, and we can't spend time reverse engineering your example. The fewer files the better. Also text describing where exactly you are expecting to inject things and where you are not getting what you expect.
