### ISSUE TITLE
Add doc for `ng test --spec`

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#31821]
Angular CLI recently added a new option for `ng test` called `--spec`: https://github.com/angular/angular-cli/pull/13423. This option allows testing only specific files.

This option is not yet documented in angular.io. It should feature in https://angular.io/cli/test.

/cc @jbogarthyde

**Comment by gkalpak** [comment]
angular.io retrieves the docs from `angular/cli-builds`. I don't see the `--spec` option on [cli-builds/help/test.json][1].

[1]: https://github.com/angular/cli-builds/blob/d09f24d091417b3567e708aa369bfb93567587d4/help/test.json

**Comment by filipesilva** [comment]
Turns out no action is needed. I had the name wrong, it's not `spec`, it's `include` now. And it's already listed in https://angular.io/cli/test. My bad!
