### ISSUE TITLE
DomSanitizer recognizes Chinese characters as potentially dangerous characters

### ISSUE THREAD

**Issue by kiddliu** [angular/angular#31835]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/platform-browser

### Is this a regression?

Not sure 'cause I'm a new Angular user

### Description

Chinese characters, and potentially other East Asian language characters are encoded into a string that 'can be safely inserted into attribute or element text', which breaks the UI in those languages.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-issue-repro2-vfe7th

## 🔥 Exception or Error
<pre><code>
No Exception or Error
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.1.0
Node: 10.16.0
OS: win32 x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/pwa                      0.13.9
@ngtools/webpack                  8.1.0
@schematics/angular               7.3.9
@schematics/update                0.801.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Anything else relevant?**
[html_sanitizer.ts](https://github.com/angular/angular/blob/master/packages/core/src/sanitization/html_sanitizer.ts#L214-L233) may relevant to this issue.

**Comment by mhevery** [comment]
The above example is not correct. See working example here: https://stackblitz.com/edit/angular-issue-repro2-kh52nw?file=src/app/app.component.ts

The issue is that you can't use `SecurityContext.HTML` with binding such as `{{sampleString}}` it needs to be used as HTML like so: `<span [innerHtml]="sampleString"></span>`

Works as intended.
