### ISSUE TITLE
Should support type annotations on functions

### ISSUE THREAD

**Issue by mhevery** [angular/angular#3183]
```
var inj = Injector.resolveAndCreate([
	bind(Car).toFactory((e) => new Car(e), [Engine]),
	bind(Engine).toFactory(() => new Engine())
]);
```

should be written as:

```
var inj = Injector.resolveAndCreate([
	bind(Car).toFactory((e: Engine) => new Car(e)),
	bind(Engine).toFactory(() => new Engine())
]);
```

**Comment by PascalPrecht** [comment]
What about other metadata types? Should those be usable as decorator then?

E.g. currently you would do:

```js
bind(Car).toFactory((e) => {
  return new Car(e);
}, [[Engine, new SelfMetadata()]]);
```

**Comment by PascalPrecht** [comment]
Okay, I guess it will simply be

```
bind(Car).toFactory((@Self e: Engine) => {
  return new Car(e);
});
```
Is this feature still planned?

**Comment by mhevery** [comment]
Yes, but we need better support from TypeScript and the standards for that.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

**Comment by KrzysztofBogdan** [comment]
@mhevery 
Then what about this comment: [https://github.com/angular/angular/blob/2581c0851a257e834683f460443831877dba4d21/modules/%40angular/http/src/http_module.ts#L48](http_module.ts#L48) ?
