### ISSUE TITLE
CircleCI reports flake as test failure in Test Summary UI

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#31833]
https://circleci.com/gh/angular/angular/402431
had
//modules/benchmarks/src/expanding_rows:perf_chromium-local               FLAKY, failed in 1 out of 2 in 111.8s
  Stats over 2 runs: max = 111.8s, min = 84.1s, avg = 97.9s, dev = 13.9s
  
but then circleci now reads the test.xml from Bazel and reports
an ugly red error at the top

**Comment by alexeagle** [comment]
![image](https://user-images.githubusercontent.com/47395/61832756-04dc1300-ae27-11e9-84b1-53616bd0ab6e.png)

**Comment by alexeagle** [comment]
Not sure what needs to change so I just tossed it in the dev-infra backlog

**Comment by AndrewKushnir** [comment]
It looks like we no longer run this job on CI (only in g3), so I'm closing this ticket. Thank you.
