### ISSUE TITLE
Not able to find Angular Generator option in vs code 1.36.1 as docs shows it in https://angular.io/start link

### ISSUE THREAD

**Issue by saleemnasa** [angular/angular#31836]
Not able to find Angular Generator option in vs code 1.36.1 as docs shows it in https://angular.io/start link

path:

Getting Started  -> Your first App -> Input -> screen shot

**Comment by santoshyadav198613** [comment]
It is for stackblitz not for vs code.

**Comment by saleemnasa** [comment]
![image](https://user-images.githubusercontent.com/30295282/61886082-a8f3b600-af1c-11e9-9593-61a1b0b56932.png)
Hey found a bug.
