### ISSUE TITLE
bazel:  lazy loading of angular libraries is failing.

### ISSUE THREAD

**Issue by beynya** [angular/angular#31850]
# 🐞 bug report

### Description

Lazy loading of angular libraries with bazel is failing.

## 🔬 Minimal Reproduction

https://github.com/beynya/angular-bazel-libs
<pre><code>
npm i
npm run start
</code></pre>

## 🔥 Exception or Error
<pre><code>

ERROR: angular-bazel-libs/apps/project-a/BUILD.bazel:24:1: Compiling Angular templates (ngc) //apps/project-a:project-a failed (Exit 1)

apps/project-a/app/app.module.dev.ts(6,10): error TS2305: Module '"project/apps/project-a/app/lib-a/lib-a.module.ngfactory"' has no exported member 'LibAModuleNgFactory'.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
"dependencies": {
    "@angular/animations": "~8.1.1",
    "@angular/common": "~8.1.1",
    "@angular/compiler": "~8.1.1",
    "@angular/core": "~8.1.1",
    "@angular/forms": "~8.1.1",
    "@angular/platform-browser": "~8.1.1",
    "@angular/platform-browser-dynamic": "~8.1.1",
    "@angular/router": "~8.1.1",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.801.1",
    "@angular/bazel": "~8.1.1",
    "@angular/cli": "~8.1.1",
    "@angular/compiler-cli": "~8.1.1",
    "@angular/language-service": "~8.1.1",
    "@bazel/bazel": "^0.27.0",
    "@bazel/hide-bazel-files": "0.32.2",
    "@bazel/ibazel": "^0.10.2",
    "@bazel/karma": "0.32.2",
    "@bazel/typescript": "0.32.2",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }

</code></pre>

**Comment by marcus-sa** [comment]
So what's the updates on this ?
Or is it possible to achieve it using code splitting in rollup?

**Comment by kyliau** [comment]
Bazel builder for Angular CLI has been deprecated since version 10.
Community support is available via the [Angular Bazel](https://github.com/bazelbuild/rules_nodejs/tree/master/examples/angular) repo and the [#angular](http://slack.bazel.build/) channel on Slack.
For more info, please see this [migration doc](https://github.com/angular/angular/blob/master/packages/bazel/src/schematics/README.md).
