### ISSUE TITLE
Lazy loaded module not showing in page source but working fine in browser with Angular Universal

### ISSUE THREAD

**Issue by AliShd** [angular/angular#31857]
I have followed and implemented the Angular Universal guide and everything seems to work fine. I can see the pre-rendered markup via page source. But when it comes to lazy loaded route/module, it's not being shown in the page source. But its working fine in browser. Below is an example of a lazy loaded module.

In the browser window:
![Capture](https://user-images.githubusercontent.com/10972060/61950938-deee7400-afc8-11e9-9010-27e38ab13650.PNG)

In page source (formatted for brevity):

![Capture1](https://user-images.githubusercontent.com/10972060/61951336-26293480-afca-11e9-81ac-7cfd13b37713.PNG)

There's no list of notes in the page source as it's a lazy loaded route/module, but other contents are there. Please help! Any suggestions would highly be appreciated.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
