### ISSUE TITLE
Service Worker performance strategy ignores images

### ISSUE THREAD

**Issue by Exocomp** [angular/angular#31867]
# 🐞 bug report

### Description

Angular service worker ignores images that are specified in dataGroups when using the performance strategy.

## 🔬 Minimal Reproduction

1. First make the browser/service worker cache is cleared
2. Here is an example section from ngsw-config.json
```
{
	"name": "photos",
	"urls": [
		"/api/photo/**"
	],
	"cacheConfig": {
		"strategy": "performance",
		"maxSize": 1000,
		"maxAge": "7d"
	}
}
```
3. Browse to a page which has an html img tag to an image with the path that is covered by the url specified (see above step)

4. Look at the network requests and you will see that a network request is made everytime, the service worker is not caching the image

**NOTE** When using the freshness strategy images are cached and works correctly.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

R:\phoenix\src\phoenix-angular-web>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.1.0
Node: 10.13.0
OS: win32 x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.801.0
@angular-devkit/build-angular              0.801.0
@angular-devkit/build-optimizer            0.801.0
@angular-devkit/build-webpack              0.801.0
@angular-devkit/core                       8.1.0
@angular-devkit/schematics                 8.1.0
@angular/cdk                               8.0.2
@angular/http                              7.2.15
@angular/material                          8.0.2
@angular/pwa                               0.801.0
@ngtools/webpack                           8.1.0
@nguniversal/module-map-ngfactory-loader   7.1.1
@schematics/angular                        8.1.0
@schematics/update                         0.801.0
rxjs                                       6.5.2
typescript                                 3.4.5
webpack                                    4.35.2

</code></pre>

**Comment by gkalpak** [comment]
Thx for reporting this, @Exocomp. However, I could not reproduce the issue following your instructions. If you still think there is an issue, please provide a minimal reproduction (e.g. a project we can check out or download and the commands to run to reprodue the issue).

**Comment by Exocomp** [comment]
@gkalpak 

I provided you with the "minimal reproduction" steps.  It is your product right, why don't you care and actually put effort to make it better but you just go ahead and close it.

Stop being so lazy all the time. You frustrate me to no end.

Why don't you show me your efforts to try to reproduce it and I will point out where the problem is.
