### ISSUE TITLE
[Question] How to communicate through events?

### ISSUE THREAD

**Issue by ericmdantas** [angular/angular#3186]
I have been asking this in the gitter channel for a while now, but no luck.

The idea is pretty much the same of ```$rootScope.$on``` and ```$rootScope.$broadcast```.

Here's the question:

How do I make different components communicate through events? 
They're not parent/child type of components, they're like:

```html
<some-cmp></some-cmp>
<some-other-cmp></some-other-cmp>
```

Let's say ```some-cmp``` emmited an event called ```somethingHappened```, how does ```some-other-cmp``` listens to it?

**Comment by matanlurey** [comment]
Hi Eric, you have a lot of different options:

1. You can inject a common parent component as a service, and use it as a message bus
2. You can use the `#` syntax to pass one directive to another:

```html
<some-cmp #component></some-cmp>
<some-other-cmp [events]="component"></some-other-cmp>
```

3. You can have a parent component use the `@Query` syntax and coordinate between the two

**Comment by ericmdantas** [comment]
@matanlurey, thank you for the quick answer!

I'll give those a try.

Also, shouldn't this work too?

```html
<some-cmp #component></some-cmp>
<some-other-cmp (something-happened)="component.doSomethingAboutIt()"></some-other-cmp>
```

Where the event happens in the ```some-other-cmp``` but ```sme-cmp``` is the one in charge of dealing with it.

**Comment by matanlurey** [comment]
That sounds reasonable.

**Comment by ericmdantas** [comment]
Just in case someone looks for it too, I ended up implementing a simple message bus, [here's the code](https://github.com/ericmdantas/ng2-tsc/blob/8cd80a11ba75d3cb8c094adfc74447108d559cd3/app/message_bus/message_bus.ts#L1-L20).

The only thing different is that whenever the component is listening to something, you'll have to make NgZone run manually [(code)](https://github.com/ericmdantas/ng2-tsc/blob/8cd80a11ba75d3cb8c094adfc74447108d559cd3/app/cart/cart_cmp.ts#L32), since there were no events happening - only callbacks being executed inside an array - which won't update the view by default.
