### ISSUE TITLE
write an implementation that uses Deno

### ISSUE THREAD

**Issue by catastrop** [angular/angular#31869]

**Comment by trotyl** [comment]
This user account is for spamming purpose only. Please consider block the account.

Same issue opened in:

+ https://github.com/cube-js/cube.js/issues/172
+ https://github.com/markedjs/marked/issues/1529
+ https://github.com/webpack/webpack/issues/9482
+ https://github.com/babel/babel/issues/10276
+ https://github.com/prettier/prettier/issues/6334
+ https://github.com/parcel-bundler/parcel/issues/3280
+ https://github.com/nestjs/nest/issues/2661
+ https://github.com/fastify/fastify/issues/1772
+ https://github.com/graphql/graphql-js/issues/2056
+ https://github.com/eslint/eslint/issues/12029
+ https://github.com/dawnlabs/carbon/issues/831
+ https://github.com/rollup/rollup/issues/3008
+ https://github.com/lbryio/lbry-sdk/issues/2353

**Comment by catastrop** [comment]
@trotyl No, I am not spamming
