### ISSUE TITLE
documentation and error conflict: "path and matcher cannot be used together"

### ISSUE THREAD

**Issue by mcalmus** [angular/angular#31862]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
@angular/route

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
The documentation for matcher in Route says: "A URL-matching function to use as a custom strategy for path matching. If present, supersedes path and pathMatch." However, if both a matcher and a path are specified in a route configuration a runtime error is thrown saying "path and matcher cannot be used together".

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

"Invalid configuration of route 'my/route': path and matcher cannot be used together"
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

8.1.1
</code></pre>

**Anything else relevant?**

**Comment by IgorMinar** [comment]
thanks for the report @mcalmus. "supersedes" is definitely incorrect - only one of `path` or `matcher` can be used per route. @kapunahelewong or @jbogarthyde can you please update the doc?

**Comment by jbogarthyde** [comment]
Resolved by https://github.com/angular/angular/pull/32970
