### ISSUE TITLE
Ascending DOM heirarchy creates exception when passing objects

### ISSUE THREAD

**Issue by PeterDavidCarter** [angular/angular#31871]
# 🐞 bug report

### Affected Package

@angular/core

### Is this a regression?

Always been this way.

### Description

When ascending the DOM heirarchy and passing objects to a retrieved DOM variable, an exception is created. This is always a stack trace involving seemingly random files beginning with zone.js and ending in just about any other file.

**Comment by AndrewKushnir** [comment]
@PeterDavidCarter we looked at this ticket, but it doesn't seem to contain enough info to repro the problem and fully understand the issue. Could you please provide additional information on how we can reproduce it? A repro case using https://stackblitz.com/ would be very helpful. Thank you.
