### ISSUE TITLE
what???

### ISSUE THREAD

**Issue by weibon** [angular/angular#31876]
yarn install return this problem？？？
error https://saucelabs.com/downloads/sc-4.5.1-linux.tar.gz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by santoshyadav198613** [comment]
@weibon please do not spam. can see a similar issue which was closed #31874 .
Please feel free to open an issue on StackOverflow.

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
