### ISSUE TITLE
Use a service from a manual loaded module using Angular 8

### ISSUE THREAD

**Issue by cantacell** [angular/angular#31886]
# 🐞 bug report
Load programmatically module and use its service whithout using SystemJsNgModuleLoader.

### Description
Using Angular 7 I can load programmatically a module (defined in angular.json "lazyModules" section) and use its service.
How I can achieve the same functionality without using deprecated SystemJsNgModuleLoader?

LoaderComponent
```
@Component({
  ....
  providers: [SystemJsNgModuleLoader]
})
export class LoaderComponent {
  constructor(loader: SystemJsNgModuleLoader, injector: Injector) {}

load() {
this.loader.load('src/app/evaluate-process/evaluate-process.module#EvaluateProcessModule')
      .then((factory: NgModuleFactory<any>) => {
          const moduleRef = factory.create(this.injector);
        const eps: any = moduleRef.injector.get((<any>factory.moduleType).eps);

        eps.startMyFunction();
      });
}
```

EvaluateProcessModule
```
@NgModule({
 providers: [EvaluationProcessService]
})
export class EvaluateProcessModule {
  static eps = EvaluationProcessService;
}
```

## 🌍  Your Environment

**Angular Version:**
8.1.3

**Comment by mlc-mlapis** [comment]
@cantacell Using the dynamic import, like `import('./modules/login/login.module').then(m => m.LoginModule)`. But you have to differentiate between JIT (login.module) and AOT (login.module.ngfactory) mode.

**Comment by cantacell** [comment]
I tried:
```
import('src/app/shared/evaluate-process/evaluate-process.module').then(
  module => {
    return module.EvaluateProcessModule;
  }
).then(mod => {
  const c = mod as unknown as NgModuleFactory<any>;
  const moduleRef = c.create(this.injector);
  const eps: any = moduleRef.injector.get(mod.eps);
  eps.evaluateService.evaluateSourcePage = 'map';
  eps.startMyFunction();
});
```

but without success:
Error: Uncaught (in promise): TypeError: c.create is not a function

**Comment by mlc-mlapis** [comment]
@cantacell The context is JIT so you have to compile that module first. If you print on a console, what is `mod` now?

**Comment by cantacell** [comment]
```
import('src/app/shared/evaluate-process/evaluate-process.module').then(
  module => {
console.log(module);
    return module.EvaluateProcessModule;
  }
).then(mod => {
console.log(mod);
});
```
First console.log:
```
Module {__esModule: true, Symbol(Symbol.toStringTag): "Module"}
EvaluateProcessModule: class EvaluateProcessModule
eps: class EvaluationProcessService
ngInjectorDef: {factory: ƒ, providers: Array(3), imports: Array(7)}
arguments: (...)
caller: (...)
length: 0
name: "EvaluateProcessModule"
prototype: {constructor: ƒ}
__annotations__: [DecoratorFactory]
__proto__: ƒ ()
[[FunctionLocation]]: evaluate-process.module.ts:65
[[Scopes]]: Scopes[2]
Symbol(Symbol.toStringTag): "Module"
__esModule: true
get EvaluateProcessModule: ƒ ()
__proto__: Object
```

Second console.log:
```
class EvaluateProcessModule {
}
```

**Comment by pawelkondraciuk** [comment]
Try this

```typescript
return import(`path`)
  .then(m => m.MyModule)
  .then((moduleOrFactory) => {
    if (moduleOrFactory instanceof NgModuleFactory) {
      return moduleOrFactory;
    } else {
      return this.compiler.compileModuleAsync(moduleOrFactory);
    }
  })
  .then(module => {
    // module.get
  })
```

**Comment by cantacell** [comment]
Thank You pawelkondraciuk,
I'm implementing and testing this code in the same time that you replied :-)
I followed this guide: https://blog.angularindepth.com/automatically-upgrade-lazy-loaded-angular-modules-for-ivy-e760872e6084

**Comment by pawelkondraciuk** [comment]
Put list of lazy module paths in `lazyModules` config in angular.json

https://github.com/angular/angular-cli/blob/96fe7686aa15956c8f7254cfe16c0954240c1d26/packages/angular_devkit/build_angular/src/server/schema.json#L214

**Comment by mlc-mlapis** [comment]
@cantacell There is no Angular compiler in AOT mode. It means that your code tries to compile something even in the run-time of AOT mode app probably.

**Comment by cantacell** [comment]
Already done in my angular.json:
"projects": {
    "XXXXX": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "tsConfig": "src/tsconfig.app.json",
            "polyfills": "src/polyfills.ts",
            "stylePreprocessorOptions": {
              "includePaths": [
                "src/assets/sass"
              ]
            },
            "customWebpackConfig": {
              "path": "./extra-webpack.config.js",
              "mergeStrategies": { "loaders": "replace" },
              "replaceDuplicatePlugins": true
            },
            "assets": [
              "src/assets",
              "src/favicon.ico",
              "src/fonts"
            ],
            "lazyModules": [
              "src/app/shared/evaluate-process/evaluate-process.module"
            ]

**Comment by cantacell** [comment]
> @cantacell There is no Angular compiler in AOT mode. It means that your code tries to compile something even in the run-time of AOT mode app probably.

Yes, you are right as written into page https://blog.angularindepth.com/automatically-upgrade-lazy-loaded-angular-modules-for-ivy-e760872e6084.

**Comment by pawelkondraciuk** [comment]
I think you need to put full path with .ts extension

pon., 29 lip 2019, 17:46 użytkownik cantacell <notifications@github.com>
napisał:

**Comment by pawelkondraciuk** [comment]
I think you need to put full path with .ts extension

**Comment by cantacell** [comment]
> I think you need to put full path with .ts extension

Tried without success.

**Comment by mlc-mlapis** [comment]
@pawelkondraciuk TS extension? What does it compile it to JS?

**Comment by mikezks** [comment]
it's likely that it will not work until ivy because NGC does not create the factory if the lambda expression with the dynamic import is placed anywhere else but in the router config.

siehe: https://github.com/angular/angular-cli/issues/14763

**Comment by mlc-mlapis** [comment]
@mikezks But you can define that lazy-loaded module in the router config and still load the module programmatically using dynamic `import('...')`.

**Comment by cantacell** [comment]
After 7 years (from AngularJS) there is no native / official-doc to load a module when an user click on a button! Bah....

**Comment by mikezks** [comment]
@mlc-mlapis , i found the a working solution now:

```
export const lazyModules = {
    myDemo: {
        loadChildren: () => import('../my-demo/my-demo.module').then(m => m.MyDemoModule)
    }
};

class Loader {
    load() {
        return lazyModules['myDemo'].loadChildren()
            .then(moduleOrFactory => {
                if (moduleOrFactory instanceof NgModuleFactory) {
                    return moduleOrFactory;
                } else {
                    return this.compiler.compileModuleAsync(moduleOrFactory);
                }
            })
            .then(factory => {
                this.moduleRef = factory.create(this.injector).instance as unknown as NgModuleRef<any>;
            });
    }
}
```

more on this later.

**Comment by mlc-mlapis** [comment]
@mikezks Yep, this is the right syntax with one exception ... the path in `import('../my-demo/my-demo.module')`, wherein AOT mode it should be  `import('../my-demo/my-demo.module.ngfactory')`. 

What is completely undocumented is the exact way how to address a bundle of such a lazy-loaded module, created by CLI. You can enforce the exact name of that bundle to be able to use it in `import(...)`, but still you have to get finally `NgModuleFactory` from it.

The code created by CLI for loading a bundled lazy-loaded module is something like:
`const Mc=()=>n.e(4).then(n.bind(null,"C2cN")).then(e=>e.LoginModuleNgFactory)`

**Comment by cantacell** [comment]
> @mlc-mlapis , i found the a working solution now:
> 
> ```
> export const lazyModules = {
>     myDemo: {
>         loadChildren: () => import('../my-demo/my-demo.module').then(m => m.MyDemoModule)
>     }
> };
> 
> class Loader {
>     load() {
>         return lazyModules['myDemo'].loadChildren()
>             .then(moduleOrFactory => {
>                 if (moduleOrFactory instanceof NgModuleFactory) {
>                     return moduleOrFactory;
>                 } else {
>                     return this.compiler.compileModuleAsync(moduleOrFactory);
>                 }
>             })
>             .then(factory => {
>                 this.moduleRef = factory.create(this.injector).instance as unknown as NgModuleRef<any>;
>             });
>     }
> }
> ```
> 
> more on this later.

It works!
But with
```
const moduleRef = factory.create(this.injector);
const eps: any = moduleRef.injector.get((<any>factory.moduleType).eps);
```
instead of 
`this.moduleRef = factory.create(this.injector).instance as unknown as `

**Comment by mikezks** [comment]
> @mikezks Yep, this is the right syntax with one exception ... the path in `import('../my-demo/my-demo.module')`, wherein AOT mode it should be `import('../my-demo/my-demo.module.ngfactory')`.
> 
> What is completely undocumented is the exact way how to address a bundle of such a lazy-loaded module, created by CLI. You can enforce the exact name of that bundle to be able to use it in `import(...)`, but still you have to get finally `NgModuleFactory` from it.
> 
> The code created by CLI for loading a bundled lazy-loaded module is something like:
> `const Mc=()=>n.e(4).then(n.bind(null,"C2cN")).then(e=>e.LoginModuleNgFactory)`

@mlc-mlapis, luckly it is not that complex in this case, because Angular already deals with almost everything you mention.

There is no need to change the import from module to module factory depending on AOT or JIT environment. The Angular build process is able to do this for you. You just need to use the path that matches in your dev environment, the rest is changed by the compiler.

Actually there are two necessary things:

The separate bundle needs to be generated by webpack. Therefore the "lazyModules" option need to be set in the `angular.json` as we are not using the router.

Then it is also necessary to have the module factory available in the AOT build (means the separated lazy JS bundle) as we have no compiler available in the AOT build. This was the error we all ran into the last days and this can be solved by using the exact `loadChildren` syntax mentioned above. It was really tricky to find out which syntax actually works and as I tried several ways, the above mentioned is the leanest possible that worked for me.

You definitly do not need to change the import statement for the production bundle. This is done by Angular for you, if you implement it the way mentioned. Looking in the main production bundle, you will find the path to the lazy bundle which is den accessible during runtime.

**Comment by mikezks** [comment]
> > @mlc-mlapis , i found the a working solution now:
> > ```
> > export const lazyModules = {
> >     myDemo: {
> >         loadChildren: () => import('../my-demo/my-demo.module').then(m => m.MyDemoModule)
> >     }
> > };
> > 
> > class Loader {
> >     load() {
> >         return lazyModules['myDemo'].loadChildren()
> >             .then(moduleOrFactory => {
> >                 if (moduleOrFactory instanceof NgModuleFactory) {
> >                     return moduleOrFactory;
> >                 } else {
> >                     return this.compiler.compileModuleAsync(moduleOrFactory);
> >                 }
> >             })
> >             .then(factory => {
> >                 this.moduleRef = factory.create(this.injector).instance as unknown as NgModuleRef<any>;
> >             });
> >     }
> > }
> > ```
> > 
> > 
> > more on this later.
> 
> It works!
> But with
> 
> ```
> const moduleRef = factory.create(this.injector);
> const eps: any = moduleRef.injector.get((<any>factory.moduleType).eps);
> ```
> 
> instead of
> `this.moduleRef = factory.create(this.injector).instance as unknown as as NgModuleRef<any>;`

Yes, you are right. I had less time yesterday and just wanted to give you this update asap. To respect the inital issue it is necessary to ask for the service as mentioned by you.

**Comment by mikezks** [comment]
The following aspects need to be respected so that NGC can find your dynamic import request correctly:

- You need to use the loadChildren syntax: `{ loadChildren: () => import('../my-demo/my-demo.module').then(m => m.MyDemoModule) }`
- Using this statement inline did not work for me, but you can use a reference to this definition
- Using it as class property did not work
- Using an exported const worked for me
- It is possible to nest this syntax as shown above, so that you can use several definitions which are accessible by property name
- This way you can use a string value to dynamically load a certain module: `lazyModules['myDemo'].loadChildren()`

**Comment by mlc-mlapis** [comment]
@mikezks Yep, you are right. 👍 🍰 I use the same concept of programmatical loading of lazily-loaded modules via NGC compiler and our own build path (before dynamic import syntax), so I didn't expect that CLI is able to do it itself. I can confirm that the following code works on my side, so it's great news. Thanks.

```
export const lazyModules = {
	platform: {
		loadChildren: () => import('../../modules/platform/platform.module').then(m => m.PlatformModule)
	}
};

@Injectable({
	providedIn: 'root'
})
export class LoaderModule {
	private lazyModuleRef: NgModuleRef<any>;

	constructor(
		private _compiler: Compiler,
		private _injector: Injector
	) {}

	load() {

		const CUSTOM_TOKEN = new InjectionToken<string>('Any string custom value.');

		const providers = [
			{provide: CUSTOM_TOKEN, useValue: 'CUSTOM_VALUE'}
		];

		const lazyModuleInjector = Injector.create({
			providers,
			parent: this._injector,
			name: 'lazyModuleProviders'
		});

		lazyModules.platform.loadChildren().then(moduleOrFactory => {
			if (moduleOrFactory instanceof NgModuleFactory) {
				return moduleOrFactory;
			} else {
				return this._compiler.compileModuleAsync(moduleOrFactory);
			}
		}). then((factory: NgModuleFactory<any>) => {
			this.lazyModuleRef = factory.create(lazyModuleInjector);
			const componentType: Type<any> = this.lazyModuleRef.instance.entryComponentsType;
			// ... code to create component factory and its instance.
		});
	}
}
```
where:

```
export class PlatformModule {

	entryComponentsType: Type<PlatformComponent>;

	constructor() {
		this.entryComponentsType = PlatformComponent;
	}
}
```
