### ISSUE TITLE
upgrade 7.1.2 to 8.1.2：The ngcc compiler has changed since the last ngcc build

### ISSUE THREAD

**Issue by hukaixuan2017** [angular/angular#31881]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

I upgraded from the version of angular 7 to 8 and executed the command: ng update @angular/cli @angular/core. 

After I started my project, I got the following error:

ERROR in The ngcc compiler has changed since the last ngcc build.
Please completely remove `node_modules` and try again.

Have you met? What is the solution to this problem?

![image](https://user-images.githubusercontent.com/29294119/62015216-18e39400-b1dc-11e9-8f3a-4724e74992c2.png)

Thinks
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Hi @hukaixuan2017, as per info in the error. You need to remove your `node_modules` directory and do a fresh `npm install` or `yarn install`

```cmd
rm -rf node_modules
npm install
```

**Comment by hukaixuan2017** [comment]
> Hi @hukaixuan2017, as per info in the error. You need to remove your `node_modules` directory and do a fresh `npm install` or `yarn install`
> 
> ```batchfile
> rm -rf node_modules
> npm install
> ```

I tried the method you said, but I still reported an error at startup. 

It should be that the third-party plug-in package we used in the project was not updated in time, resulting in the project not being used.

![image](https://user-images.githubusercontent.com/29294119/62175410-321d4980-b370-11e9-988e-2473b486fae0.png)

**Comment by ZQ-jhon** [comment]
same error with @hukaixuan2017  at 

> 🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
> 
> I upgraded from the version of angular 7 to 8 and executed the command: ng update @angular/cli @angular/core.
> 
> After I started my project, I got the following error:
> 
> ERROR in The ngcc compiler has changed since the last ngcc build.
> Please completely remove `node_modules` and try again.
> 
> Have you met? What is the solution to this problem?
> 
> ![image](https://user-images.githubusercontent.com/29294119/62015216-18e39400-b1dc-11e9-8f3a-4724e74992c2.png)
> 
> Thinks
> 🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

same error with u

**Comment by petebacondarwin** [comment]
@hukaixuan2017 - the problem with date-fns should be fixed in the latest `next` release of Angular.
@ZQ-jhon - the solution is to reinstall your node_modules (see https://github.com/angular/angular/issues/31881#issuecomment-516415619).
