### ISSUE TITLE
 Can't resolve all parameters for

### ISSUE THREAD

**Issue by GHqiang** [angular/angular#31884]
compiler.js:2175 Uncaught Error: Can't resolve all parameters for ProductDetailsComponent: (?).
    at syntaxError (compiler.js:2175)

**Comment by gkalpak** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
