### ISSUE TITLE
zone.js sourcemap wrong url

### ISSUE THREAD

**Issue by Delagen** [angular/angular#31883]
# 🐞 bug report

### Affected Package
zone.js

### Is this a regression?
zone.js reference sourcemap as
```
//# sourceMappingURL=zone_rollup.umd.js.map
```
but this file missing from npm package

### Description
Sourcemap issue

## 🔬 Minimal Reproduction
```
import 'zone.js';
```
using Webpack or any build tools with sourcemap support

## 🔥 Exception or Error
<pre><code>
Sourcemap load error due missing zone_rollup.umd.js.map
</code></pre>

## 🌍  Your Environment

**Angular Version:**
Unaffected

**Anything else relevant?**
zone.js: 0.10.0

**Comment by JiaLiPassion** [comment]
Thanks for posting the issue, I will check it.
