### ISSUE TITLE
ERROR in In Ivy, decorator metadata must be inline - Clarity not working with Ivy

### ISSUE THREAD

**Issue by webmasters964** [angular/angular#31891]
`ng add @clr/angular` and Angular CLI: 8.1.2

ERROR in In Ivy, decorator metadata must be inline

![image](https://user-images.githubusercontent.com/4738163/62043424-f3777a00-b21d-11e9-9d60-a5042fa6b0c5.png)

**Comment by alxhub** [comment]
We should definitely give a better error for this.

**Comment by JoostK** [comment]
This now produces a diagnostic for the code that is failing instead of crashing without giving context, so I'll close this as resolved.
