### ISSUE TITLE
I got a 406 error When I using yarn

### ISSUE THREAD

**Issue by xyfy** [angular/angular#31902]
Arguments: 
  C:\Program Files\nodejs\node.exe C:\Program Files (x86)\Yarn\bin\yarn.js

PATH: 
  C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\nodejs\;C:\Program Files\Redis\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Yarn\bin\;C:\Users\dell\AppData\Local\Microsoft\WindowsApps;C:\Users\dell\AppData\Roaming\npm;C:\Users\dell\AppData\Local\Programs\Fiddler;C:\Users\dell\AppData\Local\Yarn\bin

Yarn version: 
  1.16.0

Node version: 
  10.15.3

Platform: 
  win32 x64

Trace: 
  Error: https://saucelabs.com/downloads/sc-4.5.1-linux.tar.gz: Request failed "406 Not Acceptable"
      at ResponseError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:696:66)
      at new ResponseError (C:\Program Files (x86)\Yarn\lib\cli.js:802:124)
      at Request.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:65270:16)
      at Request.emit (events.js:189:13)
      at Request.module.exports.Request.onRequestResponse (C:\Program Files (x86)\Yarn\lib\cli.js:130467:10)
      at ClientRequest.emit (events.js:194:15)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
      at TLSSocket.socketOnData (_http_client.js:442:20)
      at TLSSocket.emit (events.js:189:13)

npm manifest: 
  {
    "name": "angular-srcs",
    "version": "8.2.0-next.2",
    "private": true,
    "description": "Angular - a web framework for modern web apps",
    "homepage": "https://github.com/angular/angular",
    "bugs": "https://github.com/angular/angular/issues",
    "license": "MIT",
    "engines": {
      "node": ">=10.9.0 <11.0.0",
      "yarn": ">=1.12.1 <=1.16.0"
    },
    "repository": {
      "type": "git",
      "url": "https://github.com/angular/angular.git"
    },
    "scripts": {
      "bazel:format": "find . -type f \\( -name \"*.bzl\" -or -name WORKSPACE -or -name BUILD -or -name BUILD.bazel \\) ! -path \"*/node_modules/*\" | xargs buildifier -v --warnings=attr-cfg,attr-license,attr-non-empty,attr-output-default,attr-single-file,constant-glob,ctx-args,depset-iteration,depset-union,dict-concatenation,duplicated-name,filetype,git-repository,http-archive,integer-division,load,load-on-top,native-build,native-package,output-group,package-name,package-on-top,positional-args,redefined-variable,repository-name,same-origin-load,string-iteration,unused-variable",
      "bazel:lint": "yarn bazel:format --lint=warn",
      "bazel:lint-fix": "yarn bazel:format --lint=fix",
      "preinstall": "node tools/yarn/check-yarn.js",
      "postinstall": "yarn update-webdriver && node --preserve-symlinks --preserve-symlinks-main ./tools/postinstall-patches.js",
      "update-webdriver": "webdriver-manager update --gecko false $CI_CHROMEDRIVER_VERSION_ARG",
      "check-env": "gulp check-env",
      "commitmsg": "node ./scripts/git/commit-msg.js",
      "test-ivy-aot": "bazel test --define=compile=aot --build_tag_filters=-no-ivy-aot,-fixme-ivy-aot --test_tag_filters=-no-ivy-aot,-fixme-ivy-aot",
      "test-fixme-ivy-aot": "bazel test --define=compile=aot --build_tag_filters=-no-ivy-aot --test_tag_filters=-no-ivy-aot",
      "list-fixme-ivy-targets": "bazel query --output=label 'attr(\"tags\", \"\\[.*fixme-ivy.*\\]\", //...) except kind(\"sh_binary\", //...) except kind(\"devmode_js_sources\", //...)' | sort",
      "bazel": "bazel"
    },
    "// 1": "dependencies are used locally and by bazel",
    "dependencies": {
      "@angular-devkit/architect": "^0.800.0-beta.15",
      "@angular-devkit/build-optimizer": "^0.800.0-beta.15",
      "@angular-devkit/core": "^8.0.0-beta.15",
      "@angular-devkit/schematics": "^8.0.0-beta.15",
      "@angular/bazel": "file:./tools/npm/@angular_bazel",
      "@bazel/jasmine": "0.34.0",
      "@bazel/karma": "0.34.0",
      "@bazel/protractor": "0.34.0",
      "@bazel/typescript": "0.34.0",
      "@microsoft/api-extractor": "^7.0.21",
      "@schematics/angular": "^8.0.0-beta.15",
      "@types/angular": "^1.6.47",
      "@types/base64-js": "1.2.5",
      "@types/bluebird": "^3.5.27",
      "@types/chai": "^4.1.2",
      "@types/chokidar": "^1.7.5",
      "@types/convert-source-map": "^1.5.1",
      "@types/diff": "^3.5.1",
      "@types/fs-extra": "4.0.2",
      "@types/hammerjs": "2.0.35",
      "@types/inquirer": "^0.0.44",
      "@types/jasmine": "^2.8.8",
      "@types/jasminewd2": "^2.0.6",
      "@types/minimist": "^1.2.0",
      "@types/node": "^10.9.4",
      "@types/selenium-webdriver": "3.0.7",
      "@types/shelljs": "^0.7.8",
      "@types/systemjs": "0.19.32",
      "@types/yargs": "^11.1.1",
      "@webcomponents/custom-elements": "^1.0.4",
      "angular": "npm:angular@1.7",
      "angular-1.5": "npm:angular@1.5",
      "angular-1.6": "npm:angular@1.6",
      "angular-mocks": "npm:angular-mocks@1.7",
      "angular-mocks-1.5": "npm:angular-mocks@1.5",
      "angular-mocks-1.6": "npm:angular-mocks@1.6",
      "base64-js": "1.2.1",
      "bluebird": "^3.5.5",
      "brotli": "^1.3.2",
      "canonical-path": "1.0.0",
      "chai": "^4.1.2",
      "chalk": "^2.3.1",
      "chokidar": "^2.1.1",
      "convert-source-map": "^1.5.1",
      "core-js": "^2.4.1",
      "dependency-graph": "^0.7.2",
      "diff": "^3.5.0",
      "domino": "2.1.2",
      "fs-extra": "4.0.2",
      "hammerjs": "2.0.8",
      "incremental-dom": "0.4.1",
      "jasmine": "^3.1.0",
      "jasmine-core": "^3.1.0",
      "jquery": "3.0.0",
      "karma": "^3.1.4",
      "karma-browserstack-launcher": "^1.3.0",
      "magic-string": "^0.25.0",
      "materialize-css": "1.0.0",
      "minimist": "1.2.0",
      "node-uuid": "1.4.8",
      "nodejs-websocket": "^1.7.2",
      "protractor": "^5.4.2",
      "reflect-metadata": "^0.1.3",
      "rollup": "^1.1.0",
      "rollup-plugin-amd": "^3.0.0",
      "rollup-plugin-commonjs": "^9.2.1",
      "rollup-plugin-json": "^4.0.0",
      "rollup-plugin-node-resolve": "^4.0.0",
      "rollup-plugin-sourcemaps": "^0.4.2",
      "rxjs": "^6.4.0",
      "selenium-webdriver": "3.5.0",
      "shelljs": "^0.8.1",
      "source-map": "^0.6.1",
      "source-map-support": "0.5.9",
      "systemjs": "0.18.10",
      "tsickle": "0.36.0",
      "tslib": "^1.9.0",
      "tslint": "5.7.0",
      "typescript": "~3.5.3",
      "xhr2": "0.1.4",
      "yargs": "13.1.0",
      "zone.js": "^0.9.1"
    },
    "optionalDependencies": {
      "fsevents": "2.0.1"
    },
    "// 2": "devDependencies are not used under Bazel. Many can be removed after test.sh is deleted.",
    "// 3": "when updating @bazel/bazel version you also need to update the RBE settings in .bazelrc (see https://github.com/angular/angular/pull/27935)",
    "devDependencies": {
      "@angular/cli": "^8.0.0-beta.15",
      "@bazel/bazel": "0.28.1",
      "@bazel/buildifier": "^0.26.0",
      "@bazel/ibazel": "~0.9.0",
      "@types/minimist": "^1.2.0",
      "browserstacktunnel-wrapper": "2.0.1",
      "check-side-effects": "0.0.21",
      "clang-format": "1.0.41",
      "cldr": "4.10.0",
      "cldr-data-downloader": "0.3.2",
      "cldrjs": "0.5.0",
      "conventional-changelog": "^2.0.3",
      "cors": "2.8.4",
      "entities": "1.1.1",
      "firebase-tools": "5.1.1",
      "firefox-profile": "1.0.3",
      "glob": "7.1.2",
      "gulp": "3.9.1",
      "gulp-clang-format": "1.0.23",
      "gulp-connect": "5.0.0",
      "gulp-conventional-changelog": "^2.0.3",
      "gulp-filter": "^5.1.0",
      "gulp-git": "^2.7.0",
      "gulp-tslint": "8.1.2",
      "husky": "^0.14.3",
      "jpm": "1.3.1",
      "karma-chrome-launcher": "^2.2.0",
      "karma-jasmine": "^1.1.2",
      "karma-sauce-launcher": "^2.0.2",
      "karma-sourcemap-loader": "^0.3.7",
      "madge": "0.5.0",
      "mutation-observer": "^1.0.3",
      "rewire": "2.5.2",
      "sauce-connect": "https://saucelabs.com/downloads/sc-4.5.1-linux.tar.gz",
      "semver": "5.4.1",
      "tslint-eslint-rules": "4.1.1",
      "tslint-no-toplevel-property-access": "0.0.2",
      "tsutils": "2.27.2",
      "universal-analytics": "0.4.15",
      "vlq": "0.2.2",
      "vrsource-tslint-rules": "5.1.1",
      "webpack": "1.12.9"
    },
    "// 4": "natives is needed for gulp to work with node >= 10.13, see #28213",
    "resolutions": {
      "natives": "1.1.6"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by s-gbz** [comment]
Please add more detailed description on what you've been wanting to do, what happened etc. 
Feel free to stick to the guideline/ template that appeared when you first oppened this issue. 

The better you display your problem the better we can help you :)

Kind regards
Sergej

**Comment by xyfy** [comment]
I just clone the code , then use yarn command

and got the error

**Comment by xyfy** [comment]
I used yarn-1.16.0

**Comment by xyfy** [comment]
I changed the yarn version require in package.json to 1.18.0
then I fixed the error.
