### ISSUE TITLE
Ivy Compilation Failed: ERROR in ENOENT: no such file or directory. ngx-segment-analytics

### ISSUE THREAD

**Issue by rudineymc** [angular/angular#31912]
# Bug Report

#### What is the expected behavior?
Should compile correctly with Ivy

#### What is the current behavior?
Only if Ivy is disabled compiles correctly

#### What are the steps to reproduce?
* Install ngx-segment-analytics dependency
* Import the module and compile with Ivy.
* It should fetch the index.js not ngx-segment-analytics.js
* ERROR in ENOENT: no such file or directory, open '/node_modules/ngx-segment-analytics/ngx-segment-analytics.js'.

#### What is the use-case or motivation for changing an existing behavior?
This issue happens because the definition file (named ngx-segment-analytics.d.ts which makes `export * from './index.js') does not have the same name of the index.js file. If I rename index.js to be ngx-segment-analytics.js it works.
Behavior should be consistent with Ivy disabled

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular version: 8.1.2
Material: 8.1.2
TypeScript: 3.4.3

**Comment by JoostK** [comment]
This is a bug in the packaged library, the `"module"` field within [the package.json file](https://unpkg.com/browse/ngx-segment-analytics@1.4.0/package.json) points to `ngx-segment-analytics.js`, which does not exist. Either index.js needs to be renamed, or the module field needs to be adjusted.

Anyway, you can resolve the issue by configuring ngcc to use an override for the module property. In the root of your project, create a file named `ngcc.config.js` with the following:

```javascript
module.exports = {
  packages: {
    'ngx-segment-analytics': {
      entryPoints: {
        '.': {
          override: { module: 'index.js' }
        }
      }
    }
  }
};
```

**Comment by petebacondarwin** [comment]
Closing as this is not an issue with Angular and there is an open bug in the library repository: https://github.com/opendecide/ngx-segment-analytics/issues/95.
If the library does not resolve the issue, then you can use the workaround provided by @JoostK above.
