### ISSUE TITLE
Add the descendants  option to ContentChild

### ISSUE THREAD

**Issue by the-avid-engineer** [angular/angular#31921]
# 🚀 feature request

### Relevant Package
@angular/core

### Description
Similar but opposite to how the `ContentChildren` decorator has descendants option to query all descendants, I would like `ContentChild` to have an option to query only direct descendants.

### Describe the solution you'd like
1. Add `descendants` as a metadata property for `ContentChild`
2. If `descendants` is true or undefined, query all descendants (preserves current behavior)
3. If `descendants` is false, query only direct descendants

**Comment by the-avid-engineer** [comment]
The expected behavior, for example, would be that a component (`my-component`) which may or may not expect a content child directive (`my-directive`) will not catch said content child directive from the nested component.

I can make a working example if this pseudo-example doesn't explain very well

```
<my-component>
    <my-component>
        <ng-template my-directive></ng-template>
    </my-component>

    <ng-template my-directive></ng-template>
</my-component>
```

VS

```
<my-component>
    <my-component>
        <ng-template my-directive></ng-template>
    </my-component>
</my-component>
```

**Comment by pkozlowski-opensource** [comment]
Yep, we should definitively add the `descendants` option for `ContentChild`, was bitten by the lack of it several times already!

**Comment by the-avid-engineer** [comment]
It would be nice if the bot posted a link to the poll itself. I had no idea where to vote.

**Comment by Airblader** [comment]
If you read the documentation of the process it links to, you'll find out.

**Comment by the-avid-engineer** [comment]
I don't see any links in the documentation.

**Comment by the-avid-engineer** [comment]
Is the voting just done on this issue?

**Comment by Airblader** [comment]
Yes, it's done using reactions on the issue.

**Comment by Xriuk** [comment]
Is this not considered? If someone has optional templates with nested components the parent can pick children templates and consider them like its own, which is wrong
