### ISSUE TITLE
Setting `fullTemplateTypeCheck` changes the output folder structure

### ISSUE THREAD

**Issue by boyanio** [angular/angular#31927]
# 🐞 bug report

### Affected Package

The issue is probably caused by package @angular/compiler-cli

### Description

When I enable `fullTemplateTypeCheck` in `tsconfig.json`, I get different output folder structure.

## 🔬 Minimal Reproduction

I created a small [repo](https://github.com/boyanio/angular-fulltemplatetypecheck-issue) to reproduce this issue.

If I run `npm run build` (without `fullTemplateTypeCheck`), I get a `dist` folder, containing all compiled files.

If I run `npm run build-fulltemplatetypecheck` (with `fullTemplateTypeCheck`), I get a `dist` folder, containing a `src` folder, containing all compiled files.

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 7.3.9
Node: 10.16.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.8
@angular-devkit/build-angular      0.13.8
@angular-devkit/build-optimizer    0.13.8
@angular-devkit/build-webpack      0.13.8
@angular-devkit/core               7.3.8
@angular-devkit/schematics         7.3.9
@angular/cdk                       7.3.7
@angular/cli                       7.3.9
@angular/material                  7.3.7
@angular/material-moment-adapter   7.3.7
@ngtools/webpack                   7.3.8
@schematics/angular                7.3.9
@schematics/update                 0.13.9
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.38.0</code></pre>

**Comment by alxhub** [comment]
We need a `severity: wtf` label.

What a strange bug!

**Comment by alxhub** [comment]
Confirmed as reported! Definitely broken. On the plus side, the Ivy compiler doesn't do this.

**Comment by JoostK** [comment]
Closing as resolved in the Ivy compiler, as released in Angular 9.
