### ISSUE TITLE
the CompileMetadataResolver can`t hit catche under the dynamic loading module with systemJs

### ISSUE THREAD

**Issue by jol5** [angular/angular#31923]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

the bug find in angular8.X ssource packages\compiler\src\metadata_resolver.ts#_xxxCache.get() ;

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
yes!

### Description

 A clear and concise description of the problem...

1.under the dynamic loading module，metadata_resolver can`t hit my module  ,component and 
directive，_ngModuleOfTypes and so on cache.
2. only don`t work in my module.but thirty lib is work !
![image](https://user-images.githubusercontent.com/28615922/62179172-2b95ce80-b37e-11e9-952e-58662a807844.png)
3.i thing it also question in javaScript Map.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.1.1
Node: 10.15.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.801.1
@angular-devkit/core         8.1.1
@angular-devkit/schematics   8.1.1
@schematics/angular          8.1.1
@schematics/update           0.801.1
rxjs                         6.4.0

</code></pre>

**Comment by jol5** [comment]
foreach catche map ,i will  got the same key tips .
![image](https://user-images.githubusercontent.com/28615922/62179419-238a5e80-b37f-11e9-9bc3-ac449d97e96d.png)

**Comment by jol5** [comment]
![image](https://user-images.githubusercontent.com/28615922/62179731-1a4dc180-b380-11e9-9815-39874f28b07b.png)
the function why not equal ！！！！help！！！

**Comment by jol5** [comment]
hei ! function is a object ,they are compare memory reference。 ok，therefore，they will return false because SystemJs will create a new module or component instance after loaded。so，they hold different memory reference.  
of course ，i hope angular will give a solution to solve it.

**Comment by jol5** [comment]
maybe it will  solve during this.compiler.compileModuleAndAllComponentsAsync(cacheModule_or_new_module);   cacheModule_or_new_module: defind a selfCache hitter

**Comment by alxhub** [comment]
Hello @jol5, thanks for the issue report. Can you please submit a reproduction (either a StackBlitz or a link to a repository which illustrates the problem, along with instructions on how to produce the buggy behavior). We cannot investigate this issue without a reproduction.

**Comment by alxhub** [comment]
Closing as no reproduction was provided in the timeframe of a week. Feel free to open a new issue with a reproduction if this is still a problem for you.
