### ISSUE TITLE
Connector_db2 for IBM DB2 iseries

### ISSUE THREAD

**Issue by DeltaFox0018** [angular/angular#31931]
I was trying to look at the npm ibm-db or connector_db2 modules on the internet to connect to the databases on IBM System Power I8, but I can't get away, can anyone help me out?

**Comment by ericmartinezr** [comment]
wat?

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by DeltaFox0018** [comment]
In fact I didn't put it in these two categories bug report or feature request but in support request
