### ISSUE TITLE
Upgrade to npm v3

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#3193]
npm v3 should solve many of the issues around node_modules being in inconsistent state and shrinkwrap issues: [changelog](https://github.com/npm/npm/releases/tag/v3.0.0)

v3 is still beta so we need test it well before jumping on, this bug is to track any issues that are found during the testing.

- [ ] the way we verify state of node_modules by copying over shrinkwrap.json as a fingerprint is not compatible with v3 and in fact it should be unnecessary - we should remove it from npm postinstall
- [ ] new dedupe algorithm changes paths to d.ts files for our tslint - the paths will neeed to be updated
- [ ] update travis.yaml
- [ ] update `requiredNpmVersion` in gulpfile.js
- [ ] update all dependencies and reshrinkwrap the dependency tree
- [ ] resolve issues with peerDependencies that now work differently in v3 (must be explicitly required by the parent component)
- [ ] benchmark difference in install time (using Travis)

**Comment by NathanWalker** [comment]
@IgorMinar I"m sure this is not a huge priority at moment with `beta` completion looming, but curious if this is still on radar to complete and do you think ~month or couple months?

A lot projects are using npm v3 with Node v5 now and whenever I want to contribute here, I have to uninstall and go back to npm v2 and node v4.2.x  ;)

**Comment by IgorMinar** [comment]
we'll do this by the end of the year.

**Comment by laco0416** [comment]
Please unuse `peerDependencies` for reflect-metadata, zone.js, and rxjs.

reflect-metadata and zone.js are included in polyfills.
rxjs should be depended as normal dependencies.

**Comment by gdi2290** [comment]
+1 for removing `peerDependencies`
I'm using `es7-reflect-metadata` which is a fork of `reflect-metadata` with better universal and bundling support

**Comment by IgorMinar** [comment]
Interesting. That's a new use case.

We need more flexibility in npm to define different kinds of peer
dependencies.

Some are optional like zone and reflect metadata when angular2-pollyfills
file is used, or es6-shims when deploying to a modern browser.

Others could be fulfilled by other npm packages (es6-shims -> core-js,
reflect-metadata -> es7-reflect-metadata).

I guess it's time to talk to the npm folks about this.
