### ISSUE TITLE
Dynamic plugins

### ISSUE THREAD

**Issue by enigmaticsc** [angular/angular#31948]
I need a solution for working with dynamically generated plugins. That is to say that we have a framework with AOT compilation and then pre-compiled plugin modules which are loaded (and possibly unloaded) at runtime. I have found several approaches to this and each seem to get broken with a new version of Angular. This is becoming a significant headache when building large complex web applications. The plugins should be more than just lazy loaded routes (and routes should be strictly optional - using them is not appropriate for our application).

thanks

**Comment by alxhub** [comment]
Hello @enigmaticsc,

Angular 8 supports ES dynamic import, which can be used to load `NgModule`s at runtime. This enables all kinds of "plugin" use cases that were not previously possible (given the usual lazy-loading caveat that the application is still built in one cohesive compilation, using the CLI for example).

Does this feature cover your use cases? If not, can you elaborate?

**Comment by enigmaticsc** [comment]
Thanks @alxhub … Whilst useful, I'm not sure ES dynamic import entirely answers the requirement, particularly around the 'one cohesive compilation' part. As an example, say I wrote an online shop framework using Angular. It's running for a year or so with the type of plugin framework that I need. A new product comes along that I wish to add which has a complex configurator. My framework would have a popup window framework within which a product plugin could (within reason) do as it wishes to set up the product for the basket. As an admin, when new product configurators are required I simply want to create them and upload the plugin module without recompiling and restarting the whole application and they can operate within said framework. If I have understood it correctly, ES Dynamic Import might work in itself but it sounds like Angular becomes the sticking point in that everything must be compiled together.

BTW - The above use-case is an example to illustrate the point, the real use-case is a lot more complex and not an online shop!

**Comment by pkozlowski-opensource** [comment]
I'm afraid that we are bit light on the details here. I fully support the idea of Angular being more "dynamic" and "lazy loadable" and we've got number of issues / feature requests open for it already. We want to work in this direction.

I'm going to close this issue here since, as I've mentioned, we are lack specific actions / ideas / problem description here.
