### ISSUE TITLE
add dynamic HostListener just like HostBinding [style.XXX]="" and [class.XXX]=""

### ISSUE THREAD

**Issue by nanixne** [angular/angular#31968]
# 🚀 feature request

### Relevant Package
 This feature request is for @angular/core or @angular/platform-browser?

### Description
I have a output parameter in my Directive like
```
@Output() animationEnd = new EventEmitter<string>();
```

for using this I just use `(animationEnd)="($event==='fadeOut' && show=false)"`

**show** is binding to *ngIf
and **fadeOut** is a css animation
with means when animation done set **show** to false

for only one animation this way is OK but for multiple like `'flipLeft'`, I have to write like 
`(animationEnd)="(($event==='fadeOut' ||$event==='flipLeft' )&& show=false)"`

I know we can write a function do this, but if we use following dynamically host listener that would be excellent
```
<div *ngIf="show" (animationEnd.fadeOut)="show=false" (animationEnd.flipLeft)="show=false"></div>
```

### Describe the solution you'd like
more flexible, if we have
```
@Output() someOutput = new EventEmitter<Array<string>>();
```
```
(someOutput.AAA)="abc()"  // if $event includes 'AAA'
```

```
(someOutput.BBB)="xyz()" // if $event includes 'BBB'
```

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

BTW: how to create you own HostBinding or HostListener format just like  **class.XXX** or **style.XXX.XXX**

**Comment by Airblader** [comment]
I do like the idea of allowing this syntax in custom directives, but making the second part just be the emitted value is restrictive and inconsistent: it would only work with `EventEmitter<string>` and even the builtin keydown/keyup etc versions of this don't behave that way: the emitted value is an entire event, not a strong representation of the key.

**Comment by nanixne** [comment]
> 
> 
> I do like the idea of allowing this syntax in custom directives, but making the second part just be the emitted value is restrictive and inconsistent: it would only work with `EventEmitter<string>` (and maybe `EventEmitter<string[]>` according to the proposal) and even the builtin keydown/keyup etc versions of this don't behave that way: the emitted value is an entire event, not just a string representation of the key.

I agree, I think we should have ability to define the .XXX, for example `[keyup.e]="abc()"` means when keyup event .key is "e" it will call `abc()`

**Comment by pkozlowski-opensource** [comment]
IMO @Airblader [has a valid point](https://github.com/angular/angular/issues/31968#issuecomment-517920918) here - any JS object can act as event's payload so having any syntax that  assumes event payload to be a string is no-go. 

In this particular example I would suggest creating several outputs, so there are different ways of modelling API.

Going to close this issue - thnx for the suggestion but this is not something we will try to implement.
