### ISSUE TITLE
Upgrade to angular 8.2.0 from 8.1.3 error: Uncaught NullInjectorError: StaticInjectorError

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angular#31979]
### Is this a regression?
Yes, the previous version in which this bug was not present was: 8.1.3

### Description
So after upgrading from 8.1.3 where everything worked peachy to 8.2.0 I get the following error: 
![image](https://user-images.githubusercontent.com/1098243/62410525-035cd880-b5e7-11e9-8384-09b3a58c4680.png)
This NOT on my local build, only when I deploy, so when optimizer is on.
We use target: es2015 but con't use IVY yet.
On first glance, it seems to be happening somewhere when loading the site and when the authentication state is retrieved. (which is done with angularFire).

even if I make the Authentication service more 'correct' (so comment out injections of other services by using the injector service) it keeps happening:

```
constructor(public angularFireAuth: AngularFireAuth, private inj: Injector) {
    angularFireAuth.authState.subscribe((state: User) => {
      this.authState = state;
      //if you have two tabs open and logout in tab one, the other tab is unauthenticated also and should navigate automatically to /home
      //this should not happen the first time the state is retrieved as this is the moment when the application is loading in
      // if (!this.authState && !this.isFirstStateRetrieval) inj.get(Router).navigate(['home']);
      this.isFirstStateRetrieval = false;
      // this.helpers = this.inj.get(Helpers);

      if (this.id) this.lastLoggedInUserEmail = this.email;
    });
  }
```

## 🔬 Minimal Reproduction
With the complexity of the components it would take quite some time. I'll see first if this is a early-8.2.0-adopter-issue-that-is-very-common.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
