### ISSUE TITLE
the link to ng-deep in angular update to 8 guide go to typescript instead

### ISSUE THREAD

**Issue by robertIsaac** [angular/angular#31978]
# 📚 Docs or angular.io bug report

### Description

in https://update.angular.io/#7.0:8.0 
> Replace /deep/ with ::ng-deep in your styles, `read more about angular component styles and ::ng-deep.` /deep/ and ::ng-deep both are deprecated but using ::ng-deep is preferred until the shadow-piercing descendant combinator is removed from browsers and tools completely.

the highlighted text link to https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html, which has nothing to do with ::ng-deep
i think it should link to https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep

## 🔬 Minimal Reproduction

1. open https://update.angular.io/#7.0:8.0
2. click on  read more about angular component styles and ::ng-deep.

### What's the affected URL?**

https://update.angular.io/#7.0:8.0

### Reproduction Steps**

1. open https://update.angular.io/#7.0:8.0
2. click on  read more about angular component styles and ::ng-deep.

### Expected vs Actual Behavior**

it the link that provide data about ng-deep, not typescript 3.4

## 📷Screenshot

![image](https://user-images.githubusercontent.com/14242054/62410372-f2ab6300-b5e4-11e9-8bfc-13eba266e363.png)

## 🔥 Exception or Error

NA

## 🌍  Your Environment

NA

### Browser info

google chrome

### Anything else relevant?
no

**Comment by jbogarthyde** [comment]
@StephenFluin The link is correct in angular-update-guide/blob/master/src/app/recommendations.ts#L61, and the text from that line is properly displayed. 
The incorrect link appears (associated with different text) on line 62. Some kind of off-by-one error?

**Comment by robertIsaac** [comment]
> @StephenFluin The link is correct in angular-update-guide/blob/master/src/app/recommendations.ts#L61, and the text from that line is properly displayed.
> The incorrect link appears (associated with different text) on line 62. Some kind of off-by-one error?

is there  a private repo called angular-update-guide?
cause i can't follow the link to `angular-update-guide/blob/master/src/app/recommendations.ts`

**Comment by jbogarthyde** [comment]
Sorry, yes -- the Update tool is an app that Stephen wrote and maintains in his own repo -- https://github.com/StephenFluin/angular-update-guide

**Comment by StephenFluin** [comment]
This was fixed by https://github.com/StephenFluin/angular-update-guide/commit/6a008619aff46617159da40020b59feec4e8c61a

**Comment by robertIsaac** [comment]
> This was fixed by [StephenFluin/angular-update-guide@6a00861](https://github.com/StephenFluin/angular-update-guide/commit/6a008619aff46617159da40020b59feec4e8c61a)

@StephenFluin 
should the link be https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep
now it's only https://angular.io/guide/component-styles
