### ISSUE TITLE
Angular testing - Button is undefined inside ng-template

### ISSUE THREAD

**Issue by ankitsalu** [angular/angular#31970]
Getting undefined error on dispatch....If i make this button available outside the template then it works fine. It doesn't recognize the button when its inside ng-template. 

Please suggest...

<ng-template #confirmApprove let-c="close" let-d="dismiss">
    <div class="modal-header">
        <h4 class="modal-title">Test</h4>
        <button type="button" class="close" aria-label="Close" (click)="d('Cross click')"><span aria-hidden="true">&times;</span></button>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-outline-danger" (click)="c('Close click')"><fa class="pr-1" [name]="'close'"></fa>Close</button>
    </div>
</ng-template>

it('check close event', () => {       
        let button = nativeElement.querySelector('button.btn-outline-danger');
        button.dispatchEvent(new Event('click'));
    });

**Comment by AndrewKushnir** [comment]
Hi @ankitsalu,

Could you please provide a bit more information, so we can reproduce the problem? It'd be helpful to see which operations are performed, whether the <ng-template> content is embedded into the view.

Thank you.

**Comment by ankitsalu** [comment]
thanks for getting back, we are using ng-bootstrap/ng-bootstrap
So the popup opens on a click of a button
<button type="button" class="btn btn-link" (click)="openPopUp(confirmApprove)">More...</button>
<ng-template #confirmApprove let-c="close" let-d="dismiss">   
        <button type="button" class="btn btn-outline-danger" (click)="c('Close click')">Close</button>
</ng-template>

now when i directly wants to access the button, i get undefined error. For some reason the button is not visible to selector.

The same issue is referenced here:
https://stackoverflow.com/questions/50129410/jasmine-tests-get-elements-inside-ng-template-angular

Please advise

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
