### ISSUE TITLE
Position of dynamically rendered component has changed in DOM from "next sibling" to "last sibling"

### ISSUE THREAD

**Issue by stefanocke** [angular/angular#31971]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?
Yes, the previous version in which this bug was not present was: 8.1.2

### Description

In the template of my AppComponent, I have a placeholder for a dynamic component an some other components:
```
  <ng-container #placeholder></ng-container>
  <app-comp1></app-comp1>
 ...
  <app-comp20></app-comp20>
``` 

The dynamic component is rendered like this (Ivy is on):
```
 @ViewChild('placeholder', { read: ViewContainerRef, static: true })
  container: ViewContainerRef;
...
this.container.createComponent(componentFactory, 0, moduleRef.injector); 
```

Up to Angular 8.1.2, the dynamic component has been rendered right next to the placeholder (or: it "replaced" it, since ng-container is not rendered):

```
  <ng-container #placeholder></ng-container>
!!!HERE!!!
  <app-comp1></app-comp1>
 ...
  <app-comp20></app-comp20>
```  

Starting with Angular 8.2.0, the dynamci component is rendered as the last one after all the other components:

```
  <ng-container #placeholder></ng-container>
  <app-comp1></app-comp1>
 ...
  <app-comp20></app-comp20>
!!!HERE!!!
```  

## 🔬 Minimal Reproduction

- The example project is at https://github.com/stefanocke/angular-cli-app-with-rollup
- To run call:

npm i
npm run rollup-dev

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.2.0
Node: 10.16.0
OS: win32 x64
Angular: 8.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0
@angular-devkit/build-angular     0.802.0
@angular-devkit/build-optimizer   0.802.0
@angular-devkit/build-webpack     0.802.0
@angular-devkit/core              8.2.0
@angular-devkit/schematics        8.2.0
@ngtools/webpack                  8.2.0
@schematics/angular               8.2.0
@schematics/update                0.802.0
rxjs                              6.5.2
typescript                        3.5.3
</code></pre>

**Anything else relevant?**

- It is a custom build with rollup.
- Ivy is used.

**Comment by pkozlowski-opensource** [comment]
Thnx for reporting. Yes, we've changed slightly the DOM insertion order in respect to view marker comment node but didn't expect this to cause issues in practice. Will have a closer look at your case.

**Comment by pkozlowski-opensource** [comment]
@stefanocke it turned out that this is _not_ a breaking change in ivy but rather a bug that we've fixed recently in #33816. The fix is already in master, will be part of the next release (v9 RC.3).

I've opened a PR with an additional test (#33939) "just to be safe"

**Comment by stefanocke** [comment]
Works as expected in https://github.com/stefanocke/angular-cli-app-with-rollup/commit/e2b69bc668032cb61de1b15700185061345a8b53

**Comment by pkozlowski-opensource** [comment]
Thnx for confirming @stefanocke ! 👍
