### ISSUE TITLE
@Query is not able to find transcluded children in <content></content>

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#3197]
Not sure what component this belongs under, but this pretty nasty. Reported internally.

```dart
@Component(selector: 'root-component')
@View(
directives: const [QueryComponent, ContentComponent],
template:
'''
<div>
  <query-component></query-component>
  <content-component>
    <query-component></query-component>
    <query-component></query-component>
  </content-component>

  <div (click)="onClick()" > click me </div>
</div>
'''
)
class RootComponent {
  QueryList<QueryComponent> _components;

  RootComponent(@Query(QueryComponent) this._components);

  void onClick() {
    print(_components.length); // will output "1"
  }
}


@Component(selector: 'content-component')
@View(
    directives: const [],
    template: '<div><content></content></div>'
)
class ContentComponent {}

@Component(selector: 'query-component')
@View(
    directives: const [],
    template: '<div>toQuery</div>'
)
class QueryComponent {}
```

Tried using `"descendants : true`" in Query, getting really weird behavior: It will not be there at first, then after first attempt of interaction it will get there and then it will randomly disappear and appear. With descendants = true: it was calling reset for this queryList on removal of element (multiple times) and wasn't adding it back until same array for ng-for have got element added.

Tried both using `queryList` directly and listening to `onChange()`.

If I listen to  onChange() it have behaved even more randomly

**Comment by rkirov** [comment]
https://github.com/angular/angular/pull/3278 adds a similar setup as a test case. It is passing at head, so this might be fixed.

Ping me, and I will reopen the issue if you still see the problem.
