### ISSUE TITLE
ERROR in Cannot combine @Input decorators with query decorators

### ISSUE THREAD

**Issue by ganySA** [angular/angular#31977]
**With Ivy : ERROR in Cannot combine @Input decorators with query decorators when building.**

Previously stated there would be line numbers and additional info i have tried to upgrade to Angular 9 Next, but it does not seem to show any line numbers.

First i found #31327, then to this fix #31123 but this does not seem to work as the latest Angular version does not print line numbers.

I have a large number of 3rd party libraries, and those libraries could in fact have more libraries so impossible to post a piece of code to reproduce other than tearing down half the application.

Angular CLI: 8.3.0-next.0
Node: 10.15.3
OS: win32 x64
Angular: 9.0.0-next.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.0-next.0
@angular-devkit/build-angular     0.803.0-next.0
@angular-devkit/build-optimizer   0.803.0-next.0
@angular-devkit/build-webpack     0.803.0-next.0
@angular-devkit/core              8.3.0-next.0
@angular-devkit/schematics        8.3.0-next.0
@angular/cdk                      8.1.1
@angular/cli                      8.3.0-next.0
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.1.2
@angular/pwa                      0.803.0-next.0
@ngtools/webpack                  8.3.0-next.0
@schematics/angular               8.3.0-next.0
@schematics/update                0.803.0-next.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0

**Comment by trotyl** [comment]
This is a [documented deprecated pattern](https://angular.io/guide/deprecations#contentchild--input-used-together), and the removal is designed to happen in Ivy.

**Comment by JoostK** [comment]
Hello @ganySA,

This might be occurring when ngcc is processing the node_modules directory, in which case any `FatalDiagnosticError` is not currently handled properly. So that might explain why #31123 does not resolve the problem you have, as that fix was targeting ngtsc (the compiler used to compile from TypeScript source) and not ngcc (the compiler used to upgrade node_modules to ngtsc compatible code).

We have FW-1374 (internal only) to track work on this issue.

**Comment by ganySA** [comment]
Great thanks - this looks correct.
