### ISSUE TITLE
Error with IVY renderer when using attribute that is not supported in browser

### ISSUE THREAD

**Issue by gary-holland** [angular/angular#31976]
# 🐞 bug report

I'm getting the following error when trying to use the autocapitalize="true" on an input element.

Error: Template error: Can't bind to 'autocapitalize' since it isn't a known property of 'input'.

The error does not occur in Chrome, however occurs in Safari (OSX) where the attribute is not supported.

### Is this a regression?

Yes.  This does not error when ivy build is set too false. 

### Description

See bug report.

## 🔬 Minimal Reproduction

# new app with ivy build enabled.
ng new test-app --enable-ivy

# upgrade packages to latest (8.2.0 builds)
ncu -u

add following elements to app.component.html

<input [autocapitalize]="true">

run, and open in Safari browser.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0
@angular-devkit/build-angular     0.802.0
@angular-devkit/build-optimizer   0.802.0
@angular-devkit/build-webpack     0.802.0
@angular-devkit/core              8.2.0
@angular-devkit/schematics        8.2.0
@ngtools/webpack                  8.2.0
@schematics/angular               8.2.0
@schematics/update                0.802.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0
</code></pre>

**Anything else relevant?**

On on Safari on OSX (12.1.1)

OSX (Majave)

**Comment by mhevery** [comment]
resolved in https://github.com/angular/angular/pull/32463
