### ISSUE TITLE
multiple values on class attribute fail

### ISSUE THREAD

**Issue by dsl400** [angular/angular#31984]
Input:
`[class]="[valid_expression  ? 'class_name':'']">`
Outcome:
`... <i _ngcontent-yae-c4="" class="class_name, ng-star-inserted"> ....`
class_name is followed by a comma and the expression 'class_name,' will be ignored by the browser
similar outcome if comma is in front of class_name

workaround:
place a space characters  in front and after 
`' class_name '`

Angular CLI: 8.1.3
Node: 10.16.0
OS: win32 x64
Angular: 8.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.801.3
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.801.3
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.1.3
@angular/cdk                      8.1.2
@angular/material                 8.1.2
@ngtools/webpack                  8.1.3
@schematics/angular               8.1.3
@schematics/update                0.801.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by dsl400** [comment]
having commas that make css classes fail is not a bug ? did you at least read what I posted ?
