### ISSUE TITLE
Can't build an angular library that depends on another angular linked library (symlink) 

### ISSUE THREAD

**Issue by fjoalland** [angular/angular#31989]
I can't build an angular library (let's call this library **libA**), if I linked another angular library (**libB** ) to it with the command 'npm link'.

If you want to reproduce my error, just clone this [repository-git]( https://github.com/fjoalland/multiple-angular-lib/tree/master), and follow the steps in the readme. You will have the same error as me.

**Context**

I created several independent angular libraries in different folders:
- /home/user/lib1
- /home/user/lib2
- /home/user/lib3

The lib2 and lib3 libraries need the lib1 as a dependency.

So here are the steps of what I am doing to link and add the lib1 to the lib2/lib3:

1. I install the dependencies of the lib1 (npm install) and build the lib1 (ng build)
2. I navigate to the dist folder and link the lib1 with the command 'npm link'
3. I navigate to the lib2 or lib3
4. I install my dependencies with npm (npm install)
5. I add the lib1 with the command 'npm link lib1'
6. I add the lib1 as a module in the lib2/lib3 as bellow:
```
// Example of the lib3.module.ts 

import { Lib1Module } from '@libs/lib1';

@NgModule({
  declarations: [Lib3Component],
  imports: [
    Lib1Module
  ],
  exports: [Lib3Component]
})
export class Lib3Module { }
```
7 . I try to build the lib2/lib3 with the command 'ng build'
However, I get a build issue (bellow, you can see the error message).

`ERROR: : Unexpected value 'Lib1Module in /home/user/Documents/multiple-angular-lib/lib1/dist/libs/lib1/libs-lib1.d.ts' imported by the module 'Lib2Module in /home/user/Documents/multiple-angular-lib/lib2/projects/libs/lib2/src/lib/lib2.module.ts'. Please add a @NgModule annotation.`

The most weird part is, if I deploy my lib1 on the official repository of npm and install it in lib2 and lib3, it will work. So there is a problem with the symlink.

**What I tried**

I tried to follow the solutions proposed here:

https://github.com/angular/angular-cli/issues/10665

**How to reproduce my problem**

I've reproduced an example here:
-  https://github.com/fjoalland/multiple-angular-lib/tree/master

Just follow the steps and you should have the same error as me.

**Error message**

Bellow, the full error I got when I try to build the lib2 with a symlink of the lib1
`
[root@user lib2]# ng build Building Angular Package ------------------------------------------------------------------------------ Building entry point '@libs/lib2' ------------------------------------------------------------------------------ Compiling TypeScript sources through ngc ERROR: : Unexpected value 'Lib1Module in /home/user/Documents/multiple-angular-lib/lib1/dist/libs/lib1/libs-lib1.d.ts' imported by the module 'Lib2Module in /home/user/Documents/multiple-angular-lib/lib2/projects/libs/lib2/src/lib/lib2.module.ts'. Please add a @NgModule annotation. An unhandled exception occurred: : Unexpected value 'Lib1Module in /home/user/Documents/multiple-angular-lib/lib1/dist/libs/lib1/libs-lib1.d.ts' imported by the module 'Lib2Module in /home/user/Documents/multiple-angular-lib/lib2/projects/libs/lib2/src/lib/lib2.module.ts'. Please add a @NgModule annotation. See "/tmp/ng-V1D4qF/angular-errors.log" for further details.
`
The contents of the angular-error.log file:

`[error] Error: : Unexpected value 'Lib1Module in D:/Documents/multiple-angular-lib/lib1/dist/libs/lib1/libs-lib1.d.ts' imported by the module 'Lib2Module in D:/Documents/multiple-angular-lib/lib2/projects/libs/lib2/src/lib/lib2.module.ts'. Please add a @NgModule annotation. at Object.<anonymous> (D:\Documents\multiple-angular-lib\lib2\node_modules\ng-packagr\lib\ngc\compile-source-files.js:73:19) at Generator.next (<anonymous>) at fulfilled (D:\Documents\multiple-angular-lib`

**Comment by vugar005** [comment]
I think you are importing module from incorrect path. Could you please try this ?
`import {Lib1Module} from '@libs/lib1/lib1.module.ts'`

**Comment by fjoalland** [comment]
Did you try my GitHub? It is a simple project who reproduce my error.

No, I already tried that and it's not that.
First, my angular library is compiled so you don't need to call all the path as you mentioned, it must work like that. But the weird part is, if I publish my library in NPM and install it in another library, it will work. So there is a problem with symlink and angular library.

**Comment by vugar005** [comment]
@fjoalland Seems there are 3 different workspaces. Sorry, that is different case from what I thought.

**Comment by fjoalland** [comment]
Yes, each folder is an angular application which contains an angular library:
- folder lib1 contains the lib @libs/lib1
- folder lib2 contains the lib @libs/lib2
- folder lib3 contains the lib @libs/lib3

**Comment by fjoalland** [comment]
I think it's an angular issue, I don't understand why it's not possible to do that today. Or maybe my implementation is wrong.

**Comment by alxhub** [comment]
👍 thank you for the bug report and useful reproduction. You're absolutely right, Angular does not work with `npm link`, or with symlinked `node_modules` in general. This is related to how the compiler is architected - it uses the full pathname of source files (including `.d.ts` files from `node_modules`) as a key to look up classes internally. Since a file behind a symlink has two possible paths, this scheme breaks down.

The good news is that the Ivy compiler should not have this problem!

**Comment by fjoalland** [comment]
@alxhub thanks a lot for this useful answer :+1:
But when you say Angular doesn't work with npm  link , it's not one hundred percent correct. I can link a library to an angular project, but I can not link a library to another library. 

I will try Ivy compiler and let you inform!

**Comment by gilsdav** [comment]
`"preserveSymlinks": true` option in angular.json doesn't help ?

**Comment by fjoalland** [comment]
@gilsdav you cannot use preserveSymlinks in a angular library. I got this error:

`[root@fjoalland library-angular]# ng build
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(preserveSymlinks).
`

**Comment by fabianpittroff** [comment]
Hey @fjoalland 
the preserveSymlinks option needs to be on different places. For your application it is the angular.json and for ng-packagr builds you can set the option inside the tsconfig.lib.json.
```
"angularCompilerOptions": {
    "preserveSymlinks": true,
    ...
}
```
There should already be some angularCompilerOptions, just add the preserveSymlinks to it.

**Comment by fjoalland** [comment]
Thanks for your help I finally resolved this issue.

First, @fabianpittroff  you were right. I had to add the `preserveSymlinks` option in the `tsconfig` of my library:

```
"angularCompilerOptions": {
    "preserveSymlinks": true,
    ...
}
```
However, even with this option, It didn't work and I had the same mistake. But I realized why, and I think it's because of `npm`. To explain why, let's take the following example. I want to import a libA library into a libB library.

So first, I will create a symlink of my libA with the commant `npm link `

```
cd /home/libA/dist/libA
npm link
/usr/lib/node_modules/libA  -> /home/libA/dist/libA
```

And secondly, I will link my libA to my libB with the command `npm link libA i`n the directory of libB
```
cd /home/libB
npm link libA
/home/fjoalland/libB/node_modules/libA -> /usr/lib/node_modules/libA -> /home/libA/dist/libA
```

As you can see here **/home/fjoalland/libB/node_modules/libA -> /usr/lib/node_modules/libA -> /home/libA/dist/libA** Npm created two symlinks, and I think the compiler of angular doesn't manage that. Maybe Angular can only manage one symlink, I will wait an answer of @alxhub.

But anyway, to resolve this issue I use now **yarn**! I do the same process and use the command yarn link instead of npm link.
