### ISSUE TITLE
Http post tutorial vague description

### ISSUE THREAD

**Issue by zzj0402** [angular/angular#31999]
# 📚 Docs or angular.io bug report

### Description
Error handling is different from get method.   
"Of course it catches errors in much the same manner described above.  " very vague
> https://angular.io/guide/http#making-a-post-request
First it's not the same kind of error handler. Second, following the tutorial throws error
```
Type 'Observable<never>' provides no match for the signature '(err: any, caught: Observable<File>): ObservableInput<any>'.
```
### What's the affected URL?**
https://angular.io/guide/http#making-a-post-request

### Reproduction Steps**
Follow the tutorial.

### Expected vs Actual Behavior**
Expected: post tutorial has a working code snippet.
Actual: tutorial skips error handling on post request.

## 📷Screenshot
![image](https://user-images.githubusercontent.com/15345547/62440265-757a1c80-b7a3-11e9-89ce-6f83d04c3f09.png)

## 🌍  Your Environment
Windows 10 64 bit Pro
### Browser info
Google Chrome
Version 76.0.3809.87 (Official Build) (64-bit)

**Comment by Airblader** [comment]
The compilation error is because your handleError function has to return an error handler, not an error observable. It should return a function.

**Comment by zzj0402** [comment]
How exactly to do that? I am just following the tutorial. So far none of what you informed was mentioned in there.
> https://angular.io/guide/http#error-details
```typescript
private handleError(error: HttpErrorResponse) {
  if (error.error instanceof ErrorEvent) {
    // A client-side or network error occurred. Handle it accordingly.
    console.error('An error occurred:', error.error.message);
  } else {
    // The backend returned an unsuccessful response code.
    // The response body may contain clues as to what went wrong,
    console.error(
      `Backend returned code ${error.status}, ` +
      `body was: ${error.error}`);
  }
  // return an observable with a user-facing error message
  return throwError(
    'Something bad happened; please try again later.');
};
```

**Comment by Airblader** [comment]
Look more carefully at how the tutorial uses the function:

```
catchError(this.handleError)
```

The function is passed, *not* called.

**Comment by zzj0402** [comment]
![image](https://user-images.githubusercontent.com/15345547/62443467-15897300-b7af-11e9-8784-9706fc706312.png)
Yes I "looked" carefully and that's why.

**Comment by zzj0402** [comment]
```
Argument of type '(error: string, dataset: File) => Observable<never>' is not assignable to parameter of type '(err: any, caught: Observable<File>) => Observable<never>'.
  Types of parameters 'dataset' and 'caught' are incompatible.
    Type 'Observable<File>' is missing the following properties from type 'File': lastModified, name, size, type, slicets(2345)
```

**Comment by zzj0402** [comment]
Also look carefully:
```typescript
/** POST: add a new hero to the database */
addHero (hero: Hero): Observable<Hero> {
  return this.http.post<Hero>(this.heroesUrl, hero, httpOptions)
    .pipe(
      catchError(this.handleError('addHero', hero))
    );
}
```
> https://angular.io/guide/http#making-a-post-request

**Comment by Airblader** [comment]
You're giving your error handler different arguments, so that "short" syntax of passing the function will no longer work. You need to explicitly call the function, since you want to call it with different arguments than catchError wants to pass to it.

**Comment by zzj0402** [comment]
My point is the tutorial is quite confusing.

**Comment by Airblader** [comment]
Yes, the other example you posted shows the same as what you're doing and that is indeed confusing and should be changed.

**Comment by zzj0402** [comment]
I tired both and neither seem to work so I end up Googling like mad dog and found this:
> https://angular.io/generated/live-examples/http/stackblitz
This one seems more sensible but I am still trying.

**Comment by zzj0402** [comment]
Also it seems to me that the tutorial is insufficient. There is http post on file uploading.  Like this one:
> https://stackoverflow.com/questions/47936183/angular-file-upload

**Comment by zzj0402** [comment]
Also regarding https://angular.io/guide/http#making-a-post-request page:
inline header is a better option:
> https://stackoverflow.com/questions/47761262/angular-4-5-httpclient-argument-of-type-string-is-not-assignable-to-body/47761516#47761516

I followed the tutorial tried to make a post request( not file upload):
```typescript
postCommands(command: Command) {
    if (!command) {
      return;
    }
    // console.log(command);
    const httpOptions = {
      headers: new HttpHeaders({
        "Content-Type": "application/x-www-form-urlencoded"
      }),
      reportProgress: true
    };
    return this.http.post(this.moaServerURI, command, httpOptions).pipe(
      map(event => this.getEventMessage(event, command)),
      tap(message => this.showProgress(message)),
      last(), // return last (completed) message to caller
      catchError(this.handleError(command))
    );
  }
```
gives error :  
```bash
ERROR in src/app/task/post.service.ts(36,41): error TS2345: Argument of type 'Object' is not assignable to parameter of
type 'HttpEvent<any>'.
      The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
        The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
          Property 'type' is missing in type 'Object' but required in type 'HttpUserEvent<any>'.
```

**Comment by kapunahelewong** [comment]
@zzj0402 Thank you for the details. They'll really help in improving this doc. I might not be able to rewrite that doc right away, but this issue is in our list of important issues to work on. Please feel free to add as much as you think is relevant to this issue as I will come back here as soon as I can to reference your feedback for improving the doc.

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
