### ISSUE TITLE
GDE list at angular.io is outdated

### ISSUE THREAD

**Issue by willi84** [angular/angular#31992]
# 📚 Docs or angular.io bug report

### Description
The GDE list at angular.io is not compatible with the directory result at developer.google.com

## 🔬 Minimal Reproduction
* open https://angular.io/about?group=GDE 
  * search for e.g. "Shmuela" or "David"
* open https://developers.google.com/community/experts/directory/ 
  * choose technology "Angular" 
  * search for "Shmuela" or "David"

### What's the affected URL?**
https://angular.io/about?group=GDE

### Reproduction Steps**
see minimal reproduction

### Expected vs Actual Behavior**
Both lists should be synchronized

**Comment by gkalpak** [comment]
cc @StephenFluin

**Comment by Stephenradams** [comment]
@kapunahelewong I could have a look at this if no one else is. Seems like a great first issue to work on and learn about the commit process for the docs.

**Comment by kapunahelewong** [comment]
That would be very nice, @Stephenradams. @ajitsinghkaler and @sonukapoor, neither of you are working on this, right? (I didn't find any PRs on it.)

If they aren't, @Stephenradams, I'd be happy to help guide you through the process. 😊

**Comment by ajitsinghkaler** [comment]
No I'm not it's a good easy first issue someone else can work on it

**Comment by sonukapoor** [comment]
I can take this.

**Comment by kapunahelewong** [comment]
Thank you both, @sonukapoor and @ajitsinghkaler. @Stephenradams, it's all yours if you'd like it. I'm here if you need help. Thank you!  😊

**Comment by Stephenradams** [comment]
Thanks @kapunahelewong is there someone in the Angular site that goes through the steps for contributing to the Angular docs? I know there is a video of a talk you made about contributing, I just wondered if there is a readme about it as well?

**Comment by kapunahelewong** [comment]
I have some notes I maintain on the process, @Stephenradams. They really just started as notes to myself that I put on GitHub so I wouldn't lose them. 😆But they have the steps for cloning, running locally, which files to work in for docs, how to rebase, etc. Please have a look and if you have any questions or suggestions for improvement, just let me know. My [notes for docs contributing](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca).

**Comment by Stephenradams** [comment]
Thanks @kapunahelewong these notes are brilliant.

**Comment by PandiyanCool** [comment]
Let me try sync' the list 🔢

**Comment by PandiyanCool** [comment]
@kapunahelewong please let me know where can I find the latest updated list of GDEs.

**Comment by StephenFluin** [comment]
We would like the GDEs to add themselves as part of their onboarding. I'd
totally accept a PR that is correct, but I don't want to lose the
opportunity for GDEs to becoming contributors.

**Comment by PandiyanCool** [comment]
@StephenFluin I will send PR shortly with sync current details available in this link
https://developers.google.com/community/experts/directory/

**Comment by PandiyanCool** [comment]
Hi @StephenFluin @kapunahelewong 

I have raised a PR 
https://github.com/angular/angular/pull/35925

Please check, Thanks

**Comment by rockument69** [comment]
@kapunahelewong : Can you check the status of PR [35925](https://github.com/angular/angular/pull/35925)? It says:

```
This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.
Conflicting files
aio/content/marketing/contributors.json
```

**Comment by kapunahelewong** [comment]
Yes, @rockument69. That message means that the branch needs to be [rebased on master](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase). But as @StephenFluin noted [above](https://github.com/angular/angular/issues/31992#issuecomment-593756191), we'd like for GDEs to add themselves. I'll have to defer to him on this one.

**Comment by StephenFluin** [comment]
We'll always accept a contribution that helps our docs, even if the intent
is for GDEs to add themselves. :) Once the conflicts are resolved, I'd be
happy to take another look.

**Comment by kapunahelewong** [comment]
Thank you for clarifying, @StephenFluin! 

@PandiyanCool if you need any help with your PR, just let me know. I keep notes on my workflow  you might find helpful which include [rebasing](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase).

**Comment by josephperrott** [comment]
Closing this out as this is not something we can directly fix with a PR as it will just become outdate again.

As mentioned above, we would love to have GDEs create PRs to add themselves to the documentation.
