### ISSUE TITLE
angular.merge() turns regexps into empty objects

### ISSUE THREAD

**Issue by mondalaci** [angular/angular#3199]
```
var jQueryMerged = $.extend(true, {}, {regexp:/blah/});
var angularMerged = angular.merge({}, {regexp:/blah/});
```

`jQueryMerged.regexp` yields `/blah/`
`angularMerged.regexp` yields `Object {}`

**Comment by gdi2290** [comment]
can you close this and submit the issue at https://github.com/angular/angular.js

**Comment by pkozlowski-opensource** [comment]
Right, this is not the appropriate repo, this one is for ng2.

**Comment by mondalaci** [comment]
Sorry guys, you're totally right. Just created https://github.com/angular/angular.js/issues/12409
