### ISSUE TITLE
static_tree/tree_benchmark.ts Dart results deviate too much from baseline

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#3200]
Note below that JS baseline is very close to ng2, while Dart ng2 is 50% slower.

JavaScript:

Baseline: 27.10+-9%
Ng2: 26.84+-8%
Ng1: 55.30+-14%

Dart:

Baseline: 30.13+-4%
Ng2: 45.94+-3%
Ng1: 128.88+-10%

**Comment by tbosch** [comment]
Just measured again on current master with the following results in Dart:

Static tree: 19.02+-5%ms
Static tree baseline: 18.55+-7%ms
