### ISSUE TITLE
Angular 8 with Universal not rendering on server despite no errors

### ISSUE THREAD

**Issue by m-te** [angular/angular#32000]
# 🐞 bug report
I'm not sure if this is an issue or support request, since universal works as expected with the default ng new'd project, however it doesn't work on my project although there are no errors so it might as well be a bug report specific to certain environments

### Affected Package

Not sure, I'm using Angular 8

### Is this a regression?

Only ever tried Universal with Angular 8, so unsure about that

### Description

I've already asked on stackoverflow, you can find relevant files and details there:-https://stackoverflow.com/questions/57284346/angular-2-universal-page-not-rendering-on-server?noredirect=1#comment101076546_57284346

But the gist is, there are no errors on either server terminal or console in browser, still I don't get ssr: no code in shown within app-root tag and it just returns html page like a non-universal project(view source)

## 🔬 Minimal Reproduction

I can't really put the whole code up somewhere and I'm not sure what part are causing the issue since there are not visible errors
## 🔥 Exception or Error
None that I can find in either server terminal or browser console

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.1.0
Node: 10.15.3
OS: darwin x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.801.0
@angular-devkit/build-angular              0.801.0
@angular-devkit/build-optimizer            0.801.0
@angular-devkit/build-webpack              0.801.0
@angular-devkit/core                       8.1.0
@angular-devkit/schematics                 8.1.0
@angular/cdk                               8.1.1
@angular/material                          8.0.2
@angular/platform-server                   8.1.3
@angular/pwa                               0.801.0
@ngtools/webpack                           8.1.0
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.1.0
@schematics/update                         0.801.0
rxjs                                       6.4.0
typescript                                 3.4.5
webpack                                    4.35.2
</code></pre>

**Anything else relevant?**

I fixed several errors with local-storage etc not being available by using domino and so on

**Comment by deepakrudrapaul** [comment]
Hi I am also facing the same issue. Did you find any solution ?

**Comment by vikerman** [comment]
Hi - This issue doesn't have enough info to take action on. Is there anything you can provide that can help reproduce your issue?

**Comment by m-te** [comment]
I now see this in the server console

```
Node Express server listening on http://localhost:4000
(node:9119) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
ERROR [Error]
ERROR [Error]
ERROR [Error]
ERROR [Error]
```

**Comment by smlee** [comment]
Anyone figure out this issue yet?

**Comment by vikerman** [comment]
Please re-open with repro
