### ISSUE TITLE
Error loading legacy es5 bundle on internet explorer

### ISSUE THREAD

**Issue by kKen94** [angular/angular#32002]
I have an 8.2 project, and  it compiles and works like a charm with and without Ivy, in local and aot mode.
But if I open it on Internet Explorer I have this error: 

![image](https://user-images.githubusercontent.com/46461611/62458551-8a43b980-b77d-11e9-8db0-32b870eb7450.png)

**Comment by matsko** [comment]
Hello @kKen94. Please re-create an issue following our issue template so that we can reproduce the issue and get back to you.
