### ISSUE TITLE
onClick [routerLink] do not trigger canActivate method

### ISSUE THREAD

**Issue by nikhilganji** [angular/angular#32022]
<pre>
<code>
case_1: [routerLink] = "['/home']"
case_2: this.router.navigate(['home']);
canActivate method in AuthGuard is triggered with `router.navigate` but not with `routerLink`

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
