### ISSUE TITLE
Standalone mechanism for dynamic import of widget feature modules

### ISSUE THREAD

**Issue by snortblt** [angular/angular#32024]
# 🚀 feature request

### Relevant Package
?

### Description
There are cases where we need to be able to lazy-load components from a module that may not fit into a router paradigm; for instance, a component that gets loaded into a popover as a menu button is clicked (this is the exact scenario I'm facing). 

### Describe the solution you'd like
There are third-party solutions such as `hero-loader` that solve this problem, but a built-in solution would be preferred, especially since there shouldn't much additional code beyond the router's implementation to make this happen with dynamic imports in a reusable way. Please provide some kind of directive that could be placed on an `ng-container` that would allow me to target a module, and preferably a component within it. Alternatively, the boostrapped component approach done by `hero-loader` could be acceptable when there's one and only one expected component available.

### Describe alternatives you've considered
 `hero-loader`

**Comment by mlc-mlapis** [comment]
@snortblt Look at https://github.com/angular/angular/issues/31886.

**Comment by snortblt** [comment]
Thanks @mlc-mlapis. I am aware of using dynamic imports to load a module. Specifically, I'm looking for how to load and host a component. Unless I've missed something in #31886 an approach for doing that was not discussed.

**Comment by mlc-mlapis** [comment]
@snortblt Then I don't understand what you mean by `How to load and host a component.` probably. 

The smallest part you can lazy load actually is the Angular module (and my last comment shows exactly how to load a lazily loaded module programmatically and instantiate its component), **not a component**. There some plans with Ivy to allow loading a component separately (probably in the scope of so-called `default module`), but it's not available today, yet.

**Comment by snortblt** [comment]
I understand about the module granularity. The part I’m interested in is what is apparently not shown at your comment ` // factory and its instance.`. Could you possibly give me a hint as to what that factory and component instantiation would look like?

**Comment by mlc-mlapis** [comment]
@snortblt Ah, OK. The next step is already documented in https://angular.io/guide/dynamic-component-loader and the code below uses the same API:
```
lazyModules.platform.loadChildren().then(moduleOrFactory => {
			if (moduleOrFactory instanceof NgModuleFactory) {
				return moduleOrFactory;
			} else {
				return this._compiler.compileModuleAsync(moduleOrFactory);
			}
		}).then((factory: NgModuleFactory<any>) => {
			this.lazyModuleRef = factory.create(lazyModuleInjector);
			const componentType: Type<any> = this.lazyModuleRef.instance.entryComponentsType;
			const componentFactory = this.lazyModuleRef.componentFactoryResolver.resolveComponentFactory(componentType);
			// ... either using ViewComponentRef interface: https://angular.io/api/core/ViewContainerRef
			const componentRefA = this.viewContainerRef.createComponent(componentFactory);
			// ... or using direct ComponentFactory interface: https://angular.io/api/core/ComponentFactory
			const componentRefB = componentFactory.create(anyInjector, ...);
		});
```
Now you have a component instance reference `componentRefA` or `componentRefB`.

**Comment by mhevery** [comment]
If I understand your issue you would like to load a component lazy but to do so now requires you to load the module and that get the factory from there. The steps are non-trivial. With ivy a simple `import(...)` will work just fine.

**Comment by snortblt** [comment]
Thanks @mlc-mlapis. That's what I was looking for! 

@mhevery Yes, I would love to use Ivy. Unfortunately it's not currently compatible with dynamic compilation which I'm also using, AFACT. I'm hoping to switch to that ASAP when full Ivy API is available.

**Comment by chris13524** [comment]
@mhevery could you give an example of how to lazy load a component with `import(...)` in Ivy? This is something that would be very valuable and could be put in the docs. I tried creating a module and `import()`ing it before I display the component (with `*ngIf`) but there are more issues such as the compiler doing the "error `lazy-component` is not a known element" error.

In my case, I want to load the component for a notification only after the first notification comes in.

**Comment by mlc-mlapis** [comment]
@chris13524 Read, for example, this article:
https://medium.com/angular-in-depth/lazy-load-components-in-angular-596357ab05d8

**Comment by pkozlowski-opensource** [comment]
Lazy loading components is now possible with Angular v9 running on ivy. There are still many APIs that we want to simplify in the future (ex. drop the need for the `ComponentFactoryResolver`) but the basic mechanism are in place now.

Stay tuned for all the exciting things that we can do on top of ivy :-)
