### ISSUE TITLE
Angular 8 proxy doesn't forward requests with "Sec-Fetch-Site:same-origin" request header

### ISSUE THREAD

**Issue by ironbirdie** [angular/angular#32032]
I had a angular-app working with angular 7.1.2, i have now upgraded that app to angular 8.1.3.

I'm making a rest-call to a spring-boot-rest-service passing in a JWT-token. When I bundle the application and deploy it the call works perfectly, but when i run using the cli and the proxy, the call fails. When I try the call using curl it seems to work until I add the "Sec-Fetch-Site:same-origin" request header. It doesn't even show in the debug log of the cli. Calls without JWT-token get proxied correctly. I'm using the HttpClientModule to make the rest-call together with the JwtModule.

Can this be corrected?

package.json:
`
"@angular/animations": "^8.1.3",
    "@angular/cdk": "^8.1.2",
    "@angular/common": "^8.1.3",
    "@angular/compiler": "^8.1.3",
    "@angular/core": "^8.1.3",
    "@angular/forms": "^8.1.3",
    "@angular/material": "^8.1.2",
    "@angular/platform-browser": "^8.1.3",
    "@angular/platform-browser-dynamic": "^8.1.3",
    "@angular/platform-server": "^8.1.3",
    "@angular/router": "^8.1.3",
    "@auth0/angular-jwt": "^3.0.0",`

app.module.ts:
`HttpClientModule,
    JwtModule.forRoot({
      config: {
        tokenGetter: tokenGetter,
        // whitelistedDomains: [''],
        // blacklistedRoutes: ['/oauth/token'],
        // throwNoTokenError: false,
        // skipWhenExpired: false
      }
    }),`

Proxy-conf:
`{
  "/oauth/*": {
    "target": "http://localhost:8090",
    "secure": false,
    "logLevel": "debug"
  },
  "/api/**": {
    "target": "http://localhost:8090",
    "secure": true,
    "logLevel": "debug",
    "changeOrigin": true
  }
}`

Working headers => status 200
Url: 'http://localhost:4200/api/translation'
`Authorization:Bearer e...
Host:localhost:4200
Referer:http://localhost:4200/
Sec-Fetch-Mode:cors`

Failing headers => status 400 Bad request
`Authorization:Bearer e...
Host:localhost:4200
Referer:http://localhost:4200/
Sec-Fetch-Mode:cors
Sec-Fetch-Site:same-origin`

**Comment by alxhub** [comment]
Hello @ironbirdie,

Unfortunately we won't be able to do much with this issue unless you're able to provide us a reproduction which demonstrates the problem (likely in the form of a Github repository we can clone/investigate).

**Comment by ironbirdie** [comment]
I have found the solution, it seemed my oauth2-token was getting too big and it hit a http-header-limit on the angular proxy.

I have solved it with following command:

`"scripts": {
    "start": "node --max-http-header-size=100000 ./node_modules/@angular/cli/bin/ng serve  --host=0.0.0.0 --proxyConfig=proxy.conf.json -o",
  
  },`
