### ISSUE TITLE
Promise rejection: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by jwangyangls** [angular/angular#32034]
update angular from 7.1.3 to 8.2, When starting a project, the following error is emitted：
🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅
![image](https://user-images.githubusercontent.com/29826789/62604664-1fd07c00-b92b-11e9-9836-806141698d10.png)
**Environment**
![image](https://user-images.githubusercontent.com/29826789/62604842-776ee780-b92b-11e9-8566-e4552e6dd49c.png)

**Comment by jwangyangls** [comment]
I found that the source of the error was the inability to obtain localeId, which resulted in an error.
![image](https://user-images.githubusercontent.com/29826789/62605076-f19f6c00-b92b-11e9-9c3f-589a0e3ad414.png)

**Comment by jwangyangls** [comment]
The parameters used to obtain localeId are as follows
![image](https://user-images.githubusercontent.com/29826789/62605388-95891780-b92c-11e9-8cb0-3166d93cab1e.png)
![image](https://user-images.githubusercontent.com/29826789/62605412-a043ac80-b92c-11e9-888d-2a295e7a2862.png)

**Comment by AndrewKushnir** [comment]
Hi @jwangyangls, this problem was resolved and the fix is available in `9.0.0-next.0` version. There is also a PR to make this fix available in one of the upcoming 8.2.x releases: PR #31983. Could you please try to reproduce the problem with `9.0.0-next.0` version and let us know if everything works as expected? Thank you.

**Comment by AndrewKushnir** [comment]
@jwangyangls FYI the fix was included into `8.2.1` version that was released a couple hours ago. Feel free to reopen the ticket if you still see the issue after updating the version. Thank you.
