### ISSUE TITLE
Little question about the shopping cart case

### ISSUE THREAD

**Issue by conlinslver** [angular/angular#32030]
When I use the shopping cart example, I find that emptying the shopping cart USES a code like "this.items=[]", which in turn causes the shopping cart to use a new array, and if the original array is referenced where the shopping cart service is used, it will cause the emptying function to fail to empty the shopping cart.So we recommend using "this.items.length=0" to use the same original array

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
