### ISSUE TITLE
docs: wrong description for currencyCode param for formatCurrency function

### ISSUE THREAD

**Issue by nathanko** [angular/angular#32043]
# 📚 Docs or angular.io bug report

### Description

Both 
- [https://angular.io/api/common/formatCurrency](https://angular.io/api/common/formatCurrency) and
- [https://github.com/angular/angular/blob/961d663fbef4d6ea2ebb5a60f38799a273fa71ed/packages/common/src/i18n/format_number.ts#L136-L137](https://github.com/angular/angular/blob/961d663fbef4d6ea2ebb5a60f38799a273fa71ed/packages/common/src/i18n/format_number.ts#L136-L137) 
say the `currencyCode` param is the "...currency code to use in the result string...". However, `currencyCode` is in fact not used in the returned string.

## 🔬 Minimal Reproduction

```
// actually returns '$12.34', not something like '$12.34 CAD' as expected by the docs
formatCurrency(12.34, 'en-US', '$', 'CAD');
```

### What's the affected URL?**
 
- [https://angular.io/api/common/formatCurrency
](https://angular.io/api/common/formatCurrency)
- [https://github.com/angular/angular/blob/961d663fbef4d6ea2ebb5a60f38799a273fa71ed/packages/common/src/i18n/format_number.ts#L136-L137](https://github.com/angular/angular/blob/961d663fbef4d6ea2ebb5a60f38799a273fa71ed/packages/common/src/i18n/format_number.ts#L136-L137)

### Reproduction Steps**

 
```
// '$12.34'
console.log(formatCurrency(12.34, 'en-US', '$', 'CAD'));
```

### Expected vs Actual Behavior**

Either
- the docs for the `currencyCode` param should say "The ISO 4217 currency code such as USD for the US dollar and EUR for the euro. Used to determine the number of digits in the decimal part.";
or
- `formatCurrency` should include the `currencyCode` in its return value.

**Comment by jbogarthyde** [comment]
Resolved by change in API page
https://angular.io/api/common/formatCurrency
