### ISSUE TITLE
Changelog doesn't show all breaking change

### ISSUE THREAD

**Issue by rkirov** [angular/angular#3204]
For example between 2.0.0-alpha.31 and alpha.32 https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes looks like we had only one breaking change, but there were more commits with BREAKING CHANGE in the description, for example - https://github.com/angular/angular/commit/6f4a39c337f85a63d379da349855814a623ce28e

**Comment by stevemao** [comment]
Please see #3172
