### ISSUE TITLE
Data access from constructor in Getting Started guide

### ISSUE THREAD

**Issue by bampakoa** [angular/angular#32048]
# 📚 Docs or angular.io bug report

### Description

I have noticed that `ShippingComponent` and `CartComponent` components access data from within the constructor and not using the recommended `ngOnInit` lifecycle event. Is this something that you are aware of (like keep it simple for the sake of a Getting started guide) or should it be fixed? In the latter case, I would be happy to submit a PR for that 😃 

### What's the affected URL?**

https://angular.io/start/data#define-the-shipping-page
https://angular.io/start/data#display-the-cart-items

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by kapunahelewong** [comment]
You're absolutely right, @bampakoa! If you'd like to submit a PR that'd be great. I could help you through the review process and collaborate if you like. 

Doing it the way we should is simple enough that a newcomer should be able to follow.

**Comment by bampakoa** [comment]
@kapunahelewong thanks for your feedback. I would ❤️ to submit a PR 😃 . Should I follow the Angular Documentation Style Guide for this?

**Comment by kapunahelewong** [comment]
Yes, @bampakoa, the [Angular Documentation Style Guide](https://angular.io/guide/docs-style-guide) is what we use for angular.io specific style. When it comes to language use, the [Google Developer Documentation Style Guide](https://developers.google.com/style/) is our main resource. In case you haven't memorized either of those (yet! 🌟) I can help you on any of those kinds of style choices. Feel free to tag me here, in your PR, or reach out on twitter or gitter. Thanks a lot, this is great! 🌺
