### ISSUE TITLE
ControlValueAccessor methods are being call before OnInit using DowngradeComponent

### ISSUE THREAD

**Issue by maxigimenez** [angular/angular#32056]
# 🐞 bug report

### Affected Package
```
"@angular/animations": "^8.1.1",
"@angular/cdk": "^8.1.1",
"@angular/common": "^8.1.1",
"@angular/compiler": "^8.1.1",
"@angular/core": "^8.1.1",
"@angular/forms": "^8.1.1",
"@angular/http": "^7.2.15",
"@angular/material": "^8.1.1",
"@angular/platform-browser": "^8.1.1",
"@angular/platform-browser-dynamic": "^8.1.1",
"@angular/router": "^8.1.1",
"@angular/upgrade": "^8.1.1",
```

### Is this a regression?

 No

### Description

We notice that using `downgradeComponent` from `@angular/upgrade/static` with a component that implements `ControlValueAccessor` the `writeValue|registerOnChange` are being called before `ngOnInit` (or `ngChanges`), this causes a different behavior of the component compared if we use the component in the Angular application.

This is the execution order in the angular application:
```
constructor
ngOnInit
writeValue
registerOnChange
```

And this is on the AngularJS using `downgradeComponent`:

```
constructor
registerOnChange
writeValue
ngOnInit
```

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
```
8.1.1
```

**Anything else relevant?**

**Comment by gkalpak** [comment]
Thx for reporting this @maxigimenez. Could you, please, create a minimal reproduction that we can use to investigate the problem. E.g. you could use StackBlitz and fork [this project][1] as a starting point.

**Comment by gkalpak** [comment]
Thx for reporting this @maxigimenez. Could you, please, create a minimal reproduction that we can use to investigate the problem. E.g. you could use StackBlitz and fork [this project][1] as a starting point.

[1]: https://stackblitz.com/edit/ngupgradestatic-playground

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
