### ISSUE TITLE
JavaScript heap out of memory problem when building production build with command: npm run build:ssr && npm run serve:ssr

### ISSUE THREAD

**Issue by charanmfe** [angular/angular#32053]
I have an angular application integrated with angular universal for server side rendering so when I try to make production build using command: npm run build:ssr && npm run serve:ssr then I got JavaScript heap out of memory problem. So please provide me solution how can I resolve this issue. I am already using flag --max_old_space_size=8192 but still I am getting JavaScript heap out of memory problem.

chunk {53} main.e6e6440ad5cb5d4d9fea.js (main) 1.96 MB [initial] [rendered]

WARNING in Invalid animation value at 10711:25. Ignoring. 10% building modules 1/1 modules 0 active
<--- Last few GCs --->

[6291:0x3ce9770] 987446 ms: Mark-sweep 1377.2 (1490.2) -> 1377.0 (1493.2) MB, 2009.1 / 0.0 ms allocation failure GC in old space requested [6291:0x3ce9770] 989323 ms: Mark-sweep 1377.0 (1493.2) -> 1376.8 (1461.2) MB, 1876.0 / 0.0 ms last resort GC in old space requested [6291:0x3ce9770] 991255 ms: Mark-sweep 1376.8 (1461.2) -> 1376.8 (1460.7) MB, 1931.8 / 0.0 ms last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x144a77e25891 1: set(this=0x2e6509671521 ,0x2f7b24fe3559 ,0x21e764587629 ) 2: record [/opt/lampp/htdocs/forexeye/angular-ssr-universal/myforexeye-front/node_modules/@angular/compiler-cli/src/transformers/node_emitter.js:~260] [pc=0x37a26a42de74](this=0x2e65096714e1 ,ngNode=0x...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory 1: node::Abort() [ng run myforexeye-front:server] 2: 0x8cd14c [ng run myforexeye-front:server]

**Comment by alxhub** [comment]
Hello @charanmfe,

Unfortunately we won't be able to do much with this issue unless you're able to provide us a reproduction which demonstrates the problem (likely in the form of a Github repository we can clone/investigate).

**Comment by alxhub** [comment]
Closing as no reproduction was provided in the timeframe of a week. Feel free to open a new issue with a reproduction if this is still a problem for you.
