### ISSUE TITLE
Interpolated HTML fragments get encapsulated CSS when using ViewEncapsulation.ShadowDom

### ISSUE THREAD

**Issue by pe8ter** [angular/angular#32050]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?

 unknown

### Description

When using `[innerHTML]` binding and `ViewEncapsulation.ShadowDom`, Angular applies encapsulated CSS to interpolated HTML fragments.

## 🔬 Minimal Reproduction

1. Clone repo https://github.com/pe8ter/encap-repro and change into its directory.
2. Run `npm i`.
3. Run `npm run start`.
4. In a web browser, navigate to http://localhost:4200.

## Expected Result

Text should not have a background color.

## Observed Result

Text has a background color.

## Additional Info

For reference, see the [component with an interpolated HTML fragment](https://github.com/pe8ter/encap-repro/blob/master/src/app/app.component.ts).

You can quickly disable/enable `ShadowDom` view encapsulation in [main.ts](https://github.com/pe8ter/encap-repro/blob/master/src/main.ts#L12). Notice that when using the default `Emulated` encapsulation, the text has no background color, which is what I'd expect for interpolated HTML fragments.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.1.3
Node: 10.15.3
OS: darwin x64
Angular: 8.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.801.3
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.801.3
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.1.3
@ngtools/webpack                  8.1.3
@schematics/angular               8.1.3
@schematics/update                0.801.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Comment by mhevery** [comment]
This repro is quite complicated and  we have limited time to investigate. If you would like us to look into it please make the simplest possible repro on stack-blitz and paste the link here.

**Comment by pe8ter** [comment]
@mhevery https://stackblitz.com/edit/angular-issue-repro2-mpx3ie

**Comment by trotyl** [comment]
This is the expected behavior, while the current `Emulated` behavior is a (won’t-fix-in-near-future) bug due to design limitation: https://github.com/angular/angular/issues/7108, https://github.com/angular/angular/issues/7845

---

`Emulated` stands for Angular’s own style encapsulation implementation that emulates native (shadow DOM) behavior, it cannot be made the opposite.

**Comment by pe8ter** [comment]
@trotyl Thank you. This corrects my poor understanding of the issue.
