### ISSUE TITLE
Angular javascript not working after dashboard route. refresh page then working 

### ISSUE THREAD

**Issue by prasad305** [angular/angular#32054]
Angular javascript not working after dashboard route. refresh page then working .
im used google transliteration its not working on dashboard component change. its working only refresh page only. give me a solution for this

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
