### ISSUE TITLE
Issue with directive selector inside SVG when using IVY

### ISSUE THREAD

**Issue by mitch8** [angular/angular#32061]
# 🐞 bug report

### Affected Package
IVY Compiler

### Is this a regression?

Yes, works fine without IVY

### Description

A directive or component with a selector of type 'element[attribute]' and Inputs will not compile under IVY if used inside an SVG template.

An attribute selector works as expected.

## 🔬 Minimal Reproduction

https://github.com/mitch8/ivy-issue

The issue is only present when building with IVY.
<pre><code>
"angularCompilerOptions": {
    "enableIvy": true,
  }
</code></pre>
**ng build** works fine
**ng build --prod** fail with IVY enabled

## 🔥 Exception or Error

If the directive is part of my app I get an error like this.
<pre><code>
ERROR in src/app/app.component.html(4,9): Property 'test' does not exist on type 'HTMLElement'.

</code></pre>

Interestingly, if the directive is part of a library from node_modules, it will compile without errors under IVY, however you will then get a runtime error. 
<pre><code>
Can't bind to 'test' since it isn't a known property of 'text'
</code></pre>

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 8.2.1
Node: 10.13.0
OS: win32 x64
Angular: 8.2.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.1
@angular-devkit/build-angular     0.802.1
@angular-devkit/build-optimizer   0.802.1
@angular-devkit/build-webpack     0.802.1
@angular-devkit/core              8.2.1
@angular-devkit/schematics        8.2.1
@ngtools/webpack                  8.2.1
@schematics/angular               8.2.1
@schematics/update                0.802.1
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.38.0

</code></pre>

**Comment by llimos** [comment]
This seems to be affecting the popular @swimlane/ngx-charts library, which is using such directives on SVG's and is not working for me at all under Ivy

**Comment by cal-smith** [comment]
I seem to be hitting this with our Angular icon package (we also use directives on SVGs, it's pretty core to the functionality of our library). This is the error the compiler gives me: 
![image](https://user-images.githubusercontent.com/1744185/65790376-8143e880-e12d-11e9-9d26-fcae9c7afefa.png)

Which is produced by this code: 
```html
<svg ibmIconAddAlt [size]="'16'"></svg>
```

I can provide a minimal environment if needed 👍
