### ISSUE TITLE
Slow completions with angular language server active

### ISSUE THREAD

**Issue by gayanper** [angular/angular#32062]
# 🐞 bug report

### Affected Package
@angular/language-service

### Is this a regression?
No

## 🔬 Minimal Reproduction

Steps to Reproduce:

1. Open a medium size angular project with with around 18K lines of typescript code
The initialization of the language server takes around 2 mins.

2. Now open a typescript file and try to invoke code completions. That's takes around 10-20 secs to get the completion list. 
3. The second invocation is fast.
4. Now open another typescript file and invoke code completions. That's takes around 10-20 secs again
This is same for html files as well when completing template code.

This problem is not there if i disable the angular language server plugin.

 🔥 Exception or Error
None

## 🌍  Your Environment
VSCode Version: 1.36.1
OS Version: Windows 10 (1903)

**Angular Version:**
Angular CLI: 7.2.3                                           
Node: 10.15.0                                                
OS: win32 x64                                                
Angular: 7.2.0                                               
... animations, cdk, common, compiler, core, forms           
... platform-browser, platform-browser-dynamic, router       
                                                             
@angular-devkit/architect  0.12.3 (cli-only)               
@angular-devkit/core         7.2.3 (cli-only)                
@angular-devkit/schematics   7.2.3 (cli-only)                
@schematics/angular          7.2.3 (cli-only)                
@schematics/update           0.12.3 (cli-only)               
rxjs                         6.5.2                           
typescript                   3.1.3                           

**Anything else relevant?**

**Comment by kyliau** [comment]
This should no longer be an issue now that the v9 extension is released. Please open a new issue if this is not the case.
The latest version can be downloaded from https://marketplace.visualstudio.com/items?itemName=Angular.ng-template
