### ISSUE TITLE
SSR: Unable to get view source code for routing pages in angular 6 

### ISSUE THREAD

**Issue by DivyaSaiBalakavi** [angular/angular#32065]
### Description

I have done server side rendering in angular 6 application . Got the entire application view in server side with complete functionality but unable to get the VIEW PAGE SOURCE CODE to navigated pages.
I am able to get same(index.html) VIEW PAGE SOURCE CODE to all pages  in the application.
All the files required for SSR is updated in my application.

Need clarification:
Is there any specific code to update for getting View page source code to all routing pages in application?

Could anyone help me getting out of this issue.

## 🌍  Your Environment

**Angular CLI:7.9.3
npm version: 6.4.2
<pre><code>

</code></pre>

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
