### ISSUE TITLE
ivy: flex-layout directives cause runtime errors with 9.0.0

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#32064]
# Bug Report

#### What is the expected behavior?

flex-layout should support Angular IVY

#### What is the current behavior?

When compiling angular app that uses flex-layout and has IVY enabled, the app compiles successfully, but when running in browser, it doesn't display anything on screen and throws below error in developer console:

```
(2,25): Cannot invoke an expression whose type lacks a call signature. Type '{ ngStyle: any; (Missing): number; }' has no compatible call signatures.
src/app/test/mycomponent.component.html(2,25): Cannot find name 'ngStyle'.
src/app/test/mycomponent.component.html(2,25): Cannot find name 'xs'.

```
#### What are the steps to reproduce?
Adding below code to an app using flex-layout, should throw the above error:

```
<div id="myDiv" [ngStyle.gt-xs]="{'margin-left.px':-16,'margin-right.px':-16,'margin-top.px':-16}">
</div>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

```
Angular CLI: 8.3.0-next.0
Node: 10.16.0
OS: win32 x64
Angular: 9.0.0-next.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.0-next.0
@angular-devkit/build-angular              0.803.0-next.0
@angular-devkit/build-optimizer            0.803.0-next.0
@angular-devkit/build-webpack              0.803.0-next.0
@angular-devkit/core                       8.3.0-next.0
@angular-devkit/schematics                 8.3.0-next.0
@angular/cdk                               8.1.2
@angular/cli                               8.3.0-next.0
@angular/fire                              5.2.1
@angular/flex-layout                       8.0.0-beta.26
@angular/http                              8.0.0-beta.10
@angular/material                          8.1.2
@angular/material-moment-adapter           8.1.2
@angular/pwa                               0.803.0-next.0
@ngtools/webpack                           8.3.0-next.0
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.3.0-next.0
@schematics/update                         0.803.0-next.0
rxjs                                       6.5.2
typescript                                 3.4.5
webpack                                    4.38.0
```

**Comment by naveedahmed1** [comment]
Just to add little more, its not just flex-layout `[ngStyle.gt-xs]` directives; I'm receiving errors for simple `ngStyle` angular directives like `[ngStyle]="{'padding-top': media.isActive('xs') ? '65px':'75px'}"` as well, though the error is different in this case:

```
ERROR TypeError: Cannot read property 'init' of undefined
    at DefaultStyleDirective.init (core.js:463)
    at new StyleDirective (extended.js:624)
    at new DefaultStyleDirective (extended.js:729)
    at core.js:5962
    at NodeInjectorFactory.DefaultStyleDirective_Factory [as factory] (extended.js:733)
    at getNodeInjectable (core.js:5804)
    at instantiateAllDirectives (core.js:12856)
    at createDirectivesAndLocals (core.js:12222)
    at Module.ɵɵelementStart (core.js:21493)
    at AppComponent_Template (app.component.html:79)
```

**extended.js:733**
`DefaultStyleDirective.ngDirectiveDef = ɵngcc0.ɵɵdefineDirective({ type: DefaultStyleDirective, selectors: [["", "ngStyle", ""], ["", "ngStyle.xs", ""], ["", "ngStyle.sm", ""], ["", "ngStyle.md", ""], ["", "ngStyle.lg", ""], ["", "ngStyle.xl", ""], ["", "ngStyle.lt-sm", ""], ["", "ngStyle.lt-md", ""], ["", "ngStyle.lt-lg", ""], ["", "ngStyle.lt-xl", ""], ["", "ngStyle.gt-xs", ""], ["", "ngStyle.gt-sm", ""], ["", "ngStyle.gt-md", ""], ["", "ngStyle.gt-lg", ""]], factory: function DefaultStyleDirective_Factory(t) { return ɵDefaultStyleDirective_BaseFactory(t || DefaultStyleDirective); }, inputs: { ngStyle: "ngStyle", "ngStyle.xs": "ngStyle.xs", "ngStyle.sm": "ngStyle.sm", "ngStyle.md": "ngStyle.md", "ngStyle.lg": "ngStyle.lg", "ngStyle.xl": "ngStyle.xl", "ngStyle.lt-sm": "ngStyle.lt-sm", "ngStyle.lt-md": "ngStyle.lt-md", "ngStyle.lt-lg": "ngStyle.lt-lg", "ngStyle.lt-xl": "ngStyle.lt-xl", "ngStyle.gt-xs": "ngStyle.gt-xs", "ngStyle.gt-sm": "ngStyle.gt-sm", "ngStyle.gt-md": "ngStyle.gt-md", "ngStyle.gt-lg": "ngStyle.gt-lg" }, features: [ɵngcc0.ɵɵProvidersFeature([LayoutNgStyleImplProvider]), ɵngcc0.ɵɵInheritDefinitionFeature] });`

**Comment by kara** [comment]
@naveedahmed1 `DefaultStyleDirective` in the stack trace is something from `flex-layout`, not Angular core, so that's Ivy-specific.

Regarding this:
> Any issue with compiling with Ivy is strictly an Ivy issue, as it’s meant to be backwards.compatible with ViewEngine.

That's actually not true. There are some [minor changes](https://docs.google.com/document/d/1Dije0AsJ0PxL3NaeNPxpYDeapj30b_QC0xfeIvIIzgg/preview) that will require application updates, not Ivy updates. These will mostly be accomplished through automated schematics, but until those are ready, you will see some errors that are expected.

**Comment by naveedahmed1** [comment]
So can you please transfer the issue back to flexlayout repository?

**Comment by kara** [comment]
@mhevery Can you help? (I don't have permissions in the other repo)

**Comment by Nodarii** [comment]
I experience the same issue during migration from 8.2.0 to 9.0.0.next.4. So now this issue blocks migration

**Comment by Splaktar** [comment]
@Nodarii with what version of Flex Layout?

**Comment by naveedahmed1** [comment]
I ended up removing Flex-Layout, from my project and now using to `CSS Flexbox` + `BreakpointObserver` Service from Angular Material, since I'm already using Angular Material. One less dependency and life is peaceful :D

**Comment by Nodarii** [comment]
@Splaktar It was 8.0.0-beta.26

**Comment by Splaktar** [comment]
@Nodarii I hope that you are unblocked now with `8.0.0-beta.27`?

**Comment by khalilou88** [comment]
I have this error when i run : ng build --prod but ng serve work without any error. i use  the latest version of angular : 9.0.0-next.10 .

**Comment by literalpie** [comment]
Also seeing this. To work around, I will use a breakpoint observer instead of the directives.

**Comment by petebacondarwin** [comment]
Please try with the `next` versions of Angular (9.0.0-rc.5) and flex-layout (8.0.0-beta.27)

**Comment by Nodarii** [comment]
It works for me

**Comment by petebacondarwin** [comment]
Great. Thanks for letting us know @Nodarii
