### ISSUE TITLE
NoopZone badly implements NgZone

### ISSUE THREAD

**Issue by pauldraper** [angular/angular#32063]
https://github.com/angular/angular/blob/5296c04f61bd370e7031ee7072ced586faadcfba/packages/core/src/zone/ng_zone.ts#L319

NoopZone doesn't use this or arguments that are passed.

**Comment by AndrewKushnir** [comment]
@pauldraper, could you please provide some additional information/context on this issue? Thank you.

**Comment by JiaLiPassion** [comment]
@pauldraper , you mean 

```
  run(fn: () => any): any { return fn(); }
```

should be something like

```
  run(fn: () => any, applyThis, applyArgs): any { return fn.apply(applyThis, applyArgs); }
```
?

Could you post some cases the current implementation not working? 
And I will update the implementation. Thanks!

**Comment by pauldraper** [comment]
Yep, exactly thanks @JiaLiPassion
