### ISSUE TITLE
To protect assets folder for the staging url

### ISSUE THREAD

**Issue by krishnasaikumarraju** [angular/angular#32075]
Hi Team,

Could you please suggest me how to over this issue.

### Relevant Package
Angular-Version: 6
Node:8.9

### Description
I'm able to access the assets folder for the staging url which is url: https://stage-example.com/assets

### Describe the solution you'd like
I would like to restrict and to be redirected to the login page.

### Describe alternatives you've considered
I have tried with the Authgaurd If the token expires page to be redirected to the login page.

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
