### ISSUE TITLE
Underscores in property name environment configuration yield invalid JS

### ISSUE THREAD

**Issue by MatthewDavidCampbell** [angular/angular#32071]
# 🐞 bug report

### Affected Package
Angular CLI (configure environment during build phase)

### Is this a regression?
Uncertain since started using Angular after version 8.

### Description
Any underscore in a property name generates invalid JavaScript.  For example, the following build in not correct:

    export const environment = {
      "http://some/url/_underscore": "value",
      "_": "value"
    }

is then invalid:

    var r = {  http://some/url/_underscore: "value", _: "value" }

since the resulting property names that are not valid identifiers should be in quotes (i.e. adhering to bracket notation).

## 🔬 Minimal Reproduction
Just add an underscore to any property name.

## 🔥 Exception or Error
Assumes this is by design since leading underscores are frowned on by style guides.  However, an underscore would be valid in a property name made of a url (which is my case).

## 🌍  Your Environment
Angular 8+ on Windows.

**Comment by NoamBuzaglo** [comment]
Hey,
I want to take part in this issue.
It's my first time that i will fix issue in open source project.
Thanks.

**Comment by kara** [comment]
@MatthewDavidCampbell Thanks for the issue report! Angular CLI issues should actually be posted in the CLI repo here:

https://github.com/angular/angular-cli

Would you mind re-opening the issue there?
