### ISSUE TITLE
debugElement.query can't find an element that wasn't added by angular

### ISSUE THREAD

**Issue by fr0** [angular/angular#32082]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core/testing

### Is this a regression?

Unknown

### Description

1. Have your component add a DOM element via JavaScript
2. Notice that unit tests can't find that element via `debugElement.query`

```
@Component({
  selector: 'app-route1',
  template: ``
})
export class Route1Component implements OnInit {
  constructor(private element: ElementRef<HTMLElement>) { }

  ngOnInit() {
    const div = document.createElement('div');
    div.classList.add('thing');
    div.innerText = 'this is the dynamic div';
    this.element.nativeElement.appendChild(div);
  }
}

...

  it('should be able to add an element dynamically', fakeAsync(() => {
    component.ngOnInit();
    tick(100);
    expect(fixture.debugElement.query(By.css('.thing'))).toBeTruthy();
 }));

```

In practice, this happens with 3rd party libraries that aren't angular specific.

E.g. `ace editor` https://github.com/ajaxorg/ace
or `json-formatter-js` https://github.com/mohsen1/json-formatter-js

or any library that wants to add DOM elements.

## 🔬 Minimal Reproduction

https://github.com/fr0/angular-test/tree/debugelement

Run `yarn test`

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.2.1
Node: 12.6.0
OS: darwin x64
Angular: 8.2.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.1
@angular-devkit/build-angular     0.802.1
@angular-devkit/build-optimizer   0.802.1
@angular-devkit/build-webpack     0.802.1
@angular-devkit/core              8.2.1
@angular-devkit/schematics        8.2.1
@ngtools/webpack                  8.2.1
@schematics/angular               8.2.1
@schematics/update                0.802.1
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0

</code></pre>

**Comment by pkozlowski-opensource** [comment]
Yep, this is how it is designed currently. We will be able to support this correctly with ivy.

**Comment by alxhub** [comment]
Closing as this is not actionable for Angular, as @pkozlowski-opensource says. Debug queries can only find elements that were created with the `Renderer2`.
