### ISSUE TITLE
router-link can't eval function?

### ISSUE THREAD

**Issue by gastrodia** [angular/angular#3208]
is it can be use like this?

```
<a href="javascript:;" (click)="onItemClick(i)" [router-link]="getItemLink(i)">
```

**Comment by naomiblack** [comment]
Hi! The router is not yet officially released. We'll have full documentation when it is. In the meantime, try asking this question on the forum (https://groups.google.com/forum/#!forum/angular) or on gitter https://gitter.im/angular/angular

Closing this issue as it's not really a bug.
