### ISSUE TITLE
ivy with pnpm: ERROR in EACCES: permission denied, copyfile  ...

### ISSUE THREAD

**Issue by aquark** [angular/angular#32087]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/compiler

### Is this a regression?

N/A

### Description

When building with ivy and pnpm, I get EACCES errors because ivy attempts to modify cached package directory which is immutable.

## 🔬 Minimal Reproduction

Create an Angular app with `angular.json` including `"cli": {"packageManager": "pnpm"}` and `src/tsconfig.app.json` including  `"angularCompilerOptions": { "enableIvy": true }`.

Run `ng build --prod`

## 🔥 Exception or Error
<pre><code>
  0% compiling
Compiling @angular/core : module as esm5

chunk {0} runtime.9ad22a88fcc70a015907.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main.0bb076cab38745b1b034.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills.434a4f36b18c87969736.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} polyfills-es5.226f1ee14488352ed431.js (polyfills-es5) 69.9 kB [initial] [rendered]
chunk {4} styles.d90b18e52a9fc4f63eef.css (styles) 62.9 kB [initial] [rendered]
Date: 2019-08-09T21:14:47.099Z - Hash: f662a5001ac751200886 - Time: 5709ms

ERROR in EACCES: permission denied, copyfile '.../@angular/core/8.2.0/node_modules/@angular/core/fesm5/core.js' -> '.../@angular/core/8.2.0/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js'
Exit status: 1
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.2.0
Node: 10.16.0
OS: darwin x64
Angular: 8.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0
@angular-devkit/build-angular     0.802.0
@angular-devkit/build-optimizer   0.802.0
@angular-devkit/build-webpack     0.802.0
@angular-devkit/core              8.2.0
@angular-devkit/schematics        8.2.0
@angular/cdk                      7.3.7
@angular/material                 7.3.7
@ngtools/webpack                  8.2.0
@schematics/angular               8.2.0
@schematics/update                0.802.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0
</code></pre>

**Anything else relevant?**
No

**Comment by alxhub** [comment]
Hi @aquark, thanks for the report.

Unfortunately the design of our compatibility compiler `ngcc` assumes it can upgrade packages in-place. This design choice was discussed in-depth on the team as it has pros and cons which deeply affect developer workflows.

In the end, we settled on the current design as it's compatible with the most tooling - everything else requires custom module resolvers or loaders to "intercept" resolution into `node_modules` and redirect to files stored outside. When `ngcc` modifies `node_modules` itself, all the build tooling does not have to be aware of this at all.

Unfortunately this does mean that tooling like `pnpm` is fundamentally incompatible with `ngcc`. Eventually Angular libraries will ship with Ivy code compiled in and `ngcc` will be superfluous. Until then, it will be necessary to use `npm` or `yarn` instead of `pnpm` when working in an Angular project. Alternatively, you can opt out of Ivy and continue using View Engine for now.

Sorry for the inconvenience :( the tradeoffs here are frustrating, and in an ideal world we could have `ngcc` support both modes of operation. But unfortunately we have to prioritize our efforts and I don't think we'll be able to get to this.

I'm going to close this issue as it's not actionable for us, but please feel free to continue discussing.

**Comment by aquark** [comment]
I was able to work around this by enabling the side-effects-cache feature.

**Comment by varolo** [comment]
After last ng update I found a problem that is very similar to yours:

`ng build --prod --base-href /web2/  --output-hashing=all

chunk {0} runtime-es2015.7b6d4b0455539741dc9b.js (runtime) 4.31 kB [entry] [rendered]
chunk {1} main-es2015.ff285b500035f9e9f9ef.js (main) 6.64 MB [initial] [rendered]
chunk {2} polyfills-es2015.fd917e7c3ed57f282ee5.js (polyfills) 64.3 kB [initial] [rendered]
chunk {3} polyfills-es5-es2015.4c0d377788fb16dcec21.js (polyfills-es5) 211 kB [initial] [rendered]
chunk {4} styles.29d5340fb16f2896bf8b.css (styles) 279 kB [initial] [rendered]
chunk {5} 5-es2015.f88ae0088ee68fa3f369.js () 374 kB  [rendered]
chunk {6} 6-es2015.6d6af2e6ae0d69ffc579.js () 50.3 kB  [rendered]
chunk {7} 7-es2015.18abacb057e4c8b31429.js () 30.7 kB  [rendered]
chunk {8} 8-es2015.6983604cce89e1b2ef72.js () 171 kB  [rendered]
chunk {9} 9-es2015.e1030c7a517902164f32.js () 9.4 kB  [rendered]
chunk {scripts} scripts.ea9a7b51b5073e2a08c5.js (scripts) 161 kB [entry] [rendered]
Date: 2019-08-26T12:44:38.401Z - Hash: c65a75f8e447eec3a4f2 - Time: 190071ms
Generating ES5 bundles for differential loading...
An unhandled exception occurred: EACCES: permission denied, copyfile '/home/massi/AEMTECH_MAIN/arch/kraitbionic/src/boards/aurora/apps/webclient/node_modules/.cache/angular-build-dl/content-v2/sha512/01/7c/70fbbc0547725e68e1663ff968e9fca283fa6e43d4a9297e01915636b3ef35fb954b64ae665221a440c7997f9d0064615d8f2a49646a89bffe89d5f7ad16' -> '/home/massi/AEMTECH_MAIN/arch/kraitbionic/src/boards/aurora/apps/webclient/dist/webclient/assets/js/moment.min.js'
See "/tmp/ng-gvDMP4/angular-errors.log" for further details.`

I solved running ng build with sudo.

`**sudo** ng build --prod --base-href /web2/  --output-hashing=all`


This is my situation:

```
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.0
Node: 11.15.0
OS: linux x64
Angular: 8.2.3
... animations, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.0
@angular-devkit/build-angular     0.803.0
@angular-devkit/build-optimizer   0.803.0
@angular-devkit/build-webpack     0.803.0
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.2.2
@angular-devkit/schematics-cli    0.802.2
@angular/cdk                      8.1.3
@angular/cli                      8.3.0
@angular/common                   9.0.0-next.3
@ngtools/webpack                  8.3.0
@schematics/angular               8.3.0
@schematics/schematics            0.802.2
@schematics/update                0.803.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.39.2
```
