### ISSUE TITLE
Improving docs for NavigationCancel

### ISSUE THREAD

**Issue by dzhavat** [angular/angular#32096]
# 📚 Docs or angular.io bug report

### Description

Some time ago I was researching what triggers `NavigationCancel` because the docs don't mention this information right now (at least not on the [`NavigationCancel`](https://angular.io/api/router/NavigationCancel) page).

Later, I made a [post](https://dzhavat.github.io/2019/06/08/when-is-navigation-cancel-triggered.html) with my findings. In there I mention two cases:

* when a route guard returns `false`
* on redirect initiated by a route guard

These aren't extraordinary findings by any means but I think it might be helpful mentioning them in the docs.

I also volunteer for doing a PR in case this is accepted :)

### What's the affected URL?**

https://angular.io/api/router/NavigationCancel

**Comment by jbogarthyde** [comment]
Thanks for the input! Adding your cases to the API page.

**Comment by dzhavat** [comment]
Closed by #32140
