### ISSUE TITLE
[Feature Request] Angular Lite (single file components)

### ISSUE THREAD

**Issue by alshdavid** [angular/angular#32092]
**The problem:**

It seems everywhere I look, front end frameworks have an obsession with vendor lock in by ensuring business logic is located inside of the front end framework.

Angular has a custom DI solution to help get your business logic talking to other islands of business logic. Angular's DI also helps put that logic into your components. 

While it's pretty good, it is a unique style of DI and has limitations. Limitations like a lack of dependency inversion. We depend on concrete implementations, and as a result there is a testing suite built by the Angular team to facilitate this.

_What I **love**, and I mean absolutely **love**_ about Angular is how phenomenal its templating syntax is. I'm not joking, it's honestly the most ergonomic expression of presentational concerns I have ever worked with.

What I dislike is that when I write an application, it's an Angular application. Not a TypeScript application which uses Angular as a renderer.

**The solution:**

This was briefly touched on in a conference given a while back, but I just wanted to add my 5 cents to the discussion.

Using decorators (for context-style DI), constructor injection and a simple mount/unmount system where everything is focused around components.

Here is an example of what I would love to see:
https://gist.github.com/alshdavid/32fdc1c39477910b4e5d6bc28630a269

Here is a running examle of this pattern being implemented in React
https://stackblitz.com/edit/react-ts-biohay?file=gui%2Fapp.tsx

**Comment by Airblader** [comment]
For the record, Angular's DI does not force you to rely on implementations. You can inject interfaces or even arbitrary tokens.

**Comment by mhevery** [comment]
Yes when you design framework you have to make some choices about syntax. I don't think it is possible to design something which is truly independent. So while I agree with your concern, it is very unlikely that we will or can do anything along this lines. 

Closing as not-actionable.
