### ISSUE TITLE
Error when setting [style.color] on mat-button with Ivy enabled.

### ISSUE THREAD

**Issue by james-schwartzkopf** [angular/angular#32099]
#### Reproduction

https://github.com/james-schwartzkopf/ng8-issues/tree/style-color-issue

Steps to reproduce:
1. yarn 
2. yarn run build
 
```
<button mat-button [style.color]="'red'">A Button</button>
```
```
ERROR in src/app/app.component.html(4,20): Type '"red"' is not assignable to type 'ThemePalette'.
```

 #### Expected Behavior

button should display with the CSS color set.

#### Actual Behavior

Works when enableIvy is false, template compiles with error when enableIvy is true.

#### Environment

- Angular: 8.2.0
- CDK/Material: 8.1.2

**Comment by naveedahmed1** [comment]
Is it similar to https://github.com/angular/angular/issues/32064 (though this is related to flex-layout) ?
