### ISSUE TITLE
Error: Cannot find 'AppModule' in 'app/app.module'

### ISSUE THREAD

**Issue by Gnorro** [angular/angular#32091]
# 🐞 bug report

### Description

After production build (ng build...) we get error navigating among some components
We don't have any problem during development (ng serve...)

## 🔥 Exception or Error

Error: Uncaught (in promise): Error: Cannot find 'AppModule' in 'app/app.module'
Error: Cannot find 'AppModule' in 'app/app.module'

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.9
Node: 10.16.0
OS: win32 x64
Angular: 7.1.4
... animations, common, compiler, core, forms, http
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/compiler-cli             7.2.15
@angular/language-service         7.2.15
@angular/material                 7.3.7
@angular/service-worker           7.2.15
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.29.0
</code></pre>

This is our routing module
We have some modules in lazy load. Navigating among product module or home module is ok. When we navigate on other components we ge that error
<pre><code>
export const layoutRootRoutes: Routes = [

    { path: '', component: LayoutRootComponent, children: [
        // ACCOUNT MODULE -----------------------------------------------------------------------------------------------------------
        { path: 'account', data: { breadcrumb: 'Account' }, loadChildren: 'app/features/account/account.module#AccountModule' },
        { path: 'account/.', redirectTo: 'account' },

        // PRODUCT MODULE
        { matcher: productMatcher, pathMatch: 'full', loadChildren: 'app/features/product/product.module#ProductModule' },

        // HOMEPAGE MODULE -----------------------------------------------------------------------------------------------------------
        { path: '', pathMatch: 'full', component: HomeComponent },

        { path: '', loadChildren: 'app/app.module#AppModule' },
    ]},

];
</code></pre>

For production buil we do:
<pre><code>
ng build --configuration=production
</code></pre>
and production configuration is:
<pre><code>
"production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            }
</code></pre>

Thanks

**Comment by Gnorro** [comment]
I solved it using yarn instead npm for install

I Don't know what was the cause of the problem, but it's solved

**Comment by Gnorro** [comment]
I think it's solved now.
I added this at the end of index.html:

<script>
  if (global === undefined) {
    var global = window;
  }
  if (System === undefined) {
    var System = window;
  }
</script>

**Comment by Gnorro** [comment]
Even if it's solved now, it would be interesting understand what was the cause of the problem.
This script was added not by me and was added when trying implementing universal.
So I think it's something related to that.

I would like to avoid using that script if it's not necessary. Any ideas about that?

thanks

**Comment by petebacondarwin** [comment]
AFAICT this is not compiling with ivyEnabled and so is not related to ngcc.

**Comment by pkozlowski-opensource** [comment]
Going to close this one as the oryginal issue was solved by the author and there is no reproduce scenario.
