### ISSUE TITLE
how to change router by typescript in angular2

### ISSUE THREAD

**Issue by gastrodia** [angular/angular#3210]
for exmaple I use router-link like this:

```
  <li><a [router-link]="['/start']">Start</a></li>
```
but how can I change the router to /start by typescript (by code)?

**Comment by naomiblack** [comment]
Hi! The router is not yet officially released. We'll have full documentation when it is. In the meantime, try asking this question on the forum (https://groups.google.com/forum/#!forum/angular) or on gitter https://gitter.im/angular/angular

Closing this issue as it's not really a bug.
