### ISSUE TITLE
Reopening ngOnInit not firing when clicking browser's back button.

### ISSUE THREAD

**Issue by glemiere** [angular/angular#32113]
The critical issue mentioned here: https://github.com/angular/angular/issues/26829 and in early 2016 here: https://github.com/angular/angular/issues/7722 isn't properly addressed.

Please re-open.

**Comment by glemiere** [comment]
@jasonaden

**Comment by thefliik** [comment]
This sounds like intended behavior. Angular router reuses components as approriate, and `ngOnInit` only runs when a component is created (so if a component is re-used, `ngOnInit` won't be run again). [As pointed out in the issue you linked to](https://github.com/angular/angular/issues/26829#issuecomment-516984660), it sounds like you can change the router's route re-use strategy to provide the behavior you seem to be expecting, but this will obviously degrade performance and isn't something most apps will want.

**Comment by Danieliverant** [comment]
please notice is not just the ngOnInit cycle, we talking also about Guards and Resolvers that not being fired. 
In my case, I have an empty route that validates the user and get an Access Token from Azure threw a Guard (can-activate) and then redirecting to an internal page, and on "back button" or "backslide" (on iPhone) the Guard is not activated.

Dashboard = empty page with a can activate guard.
Dashboard/Home or Dashboard/news = inner pages. 
When you navigate back from Dashboard/Home to Dashboard the guard not activated.

**Comment by atscott** [comment]
Hi @glemiere, please see @thefliik's response. If that does not solve your issue, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template, including a minimal reproduction that demonstrates the error.
