### ISSUE TITLE
Serialization of JSON bodies containing a Typescript Map object. 

### ISSUE THREAD

**Issue by celian-garcia** [angular/angular#32117]
# 🚀 feature request

### Relevant Package

 
This feature request is for **@angular/common/http**

### Description

Let's say we defined an object containing a map like this:
```typescript
export interface MyObject {
  name: string;
  description: string;
  labels?: Map<string, string>;
}
```

We instantiate it with some labels and want to send it in an http post request
```typescript
this.http.post<AlertRule>(url.build(), myObjectInstance).pipe(
    catchError(this.errorHandler.handlerHTTPError)
);
```
The problem is that the object actually sent **does not contain our Map fields**.
```json
{
  "name" : "my-name",
  "description" : "my-description",
  "labels" : {}
}
```

### Describe the solution you'd like

The solution would be to give a custom  ``replacer`` and ``reviver`` respectively to the ``JSON.stringify()`` ``JSON.parse()`` call like described in this post https://stackoverflow.com/questions/29085197/how-do-you-json-stringify-an-es6-map/56150320#56150320

### Describe alternatives you've considered
 
My workaround right now is to defined my object like this, and it works, but I hope that angular http will support Map in bodies.
```typescript
interface StringMap {
  [key: string]: string;
}

export interface MyObject {
  name: string;
  description: string;
  labels?: StringMap ;
}
```

**Comment by alxhub** [comment]
Unfortunately `HttpClient` uses a simple `JSON.stringify` call to serialize bodies to JSON. This call doesn't support what you'd like to do with `Map` objects.

I suggest using an `HttpInterceptor` to modify outgoing request bodies before they're serialized, and convert `Map`s to POJ(s)Os.

**Comment by celian-garcia** [comment]
Hello Alex.
Ok I see so the ``JSON.stringify`` you use is different from the one of the StackOverflow link. Interesting. It was a perfomances choice ?

And I suppose that the ``Map<string, object>`` to ``{ [s: string]: object; }`` transformation **automatically** done by angular, either by modifying the HttpClient or by creating a default HttpInterceptor is not a good idea because it decrease the performances too ...

Since Map is an official typescript object I still want to do something because it took me a while to understand that it was not supported.
I will create an interceptor and put it in a simple npm package. https://www.npmjs.com/search?q=map%20interceptor%20angular If I make well the referencing I hope that other noobs like me will fall on it on their desperate web search. :)

Thank you very much for your time. We can close this issue.
