### ISSUE TITLE
formatNumber does not format correctly

### ISSUE THREAD

**Issue by alexej-strelzow** [angular/angular#32119]
# 🐞 bug report

### Affected Package
@angular/commons

formatNumber

### Is this a regression?
probably

### Description

```
import { formatNumber, registerLocaleData } from '@angular/common';
import localeDe from '@angular/common/locales/de';

describe('formatNumber', () => {

  beforeEach(() => {
    registerLocaleData(localeDe);
  });

  it('should format 815 -> 0815', () => {
    expect(formatNumber(815, 'de', '4.0')).toEqual('0815');
  });

});
```

## 🔬 Minimal Reproduction
See description

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.2.0
Node: 10.15.3
OS: darwin x64
Angular: 8.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0
@angular-devkit/build-angular     0.802.0
@angular-devkit/build-optimizer   0.802.0
@angular-devkit/build-webpack     0.802.0
@angular-devkit/core              8.2.0
@angular-devkit/schematics        8.2.0
@ngtools/webpack                  8.2.0
@schematics/angular               8.2.0
@schematics/update                0.802.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.38.0

</code></pre>

**Anything else relevant?**

**Comment by alexej-strelzow** [comment]
`Error: expect(received).toEqual(expected) // deep equality

Expected: "0815"
Received: "0.815"
`

**Comment by petebacondarwin** [comment]
In the German locale (`de`) the "grouping separator" is actually a `.` and not `,` like in the `en` locale. So `0.815` actually is correct, assuming that the CLDR data is correct.
