### ISSUE TITLE
Router is an NgModule?

### ISSUE THREAD

**Issue by Univream** [angular/angular#32135]
The angular docs states that the [Router is a NgModule](https://angular.io/api/router/Router), though it's marked as a class and to my knowledge an Injectable. The NgModule it's encapsulated in, is the RouterModule.
Correct me if I am wrong.

Thanks;

**Comment by kapunahelewong** [comment]
Good catch, @Univream! Looks like a class to me, too. 😊

**Comment by AndrewKushnir** [comment]
@Univream thanks for noticing this, the corresponding PR (with the necessary updates) was merged into master. Thank you.
