### ISSUE TITLE
ViewChildren behavior (it's a bug?)

### ISSUE THREAD

**Issue by Lkledu** [angular/angular#32149]
I'm trying to use `createComponent( )` inside a forEach of an `queryList<ViewContainerRef>`, but the console returns `createComponent is not a function`

when i use console.log to see the elements of forEach, they are consoled as SlideComponent instead ViewContainerRef.

I'm creating the queryList elements with a `<slide #slides *ngFor="let req of httpRequest"></slides>` in my template and getting the elements with 
`ViewChildren('slides') slides: QueryList<ViewContainerRef>;`

Why angular change the type of the queryList element? it's expected to be occurring?

**Comment by AndrewKushnir** [comment]
@vLkledu could you please create a repro case using https://stackblitz.com/, so we can better understand the problem? Thank you.

**Comment by Lkledu** [comment]
I get it, I was missing the {read: ViewContainerRef} parameter.
Now I'm using `ViewChildren('slides', {read: ViewContainerRef}) slides: QueryList<ViewContainerRef>`

 [what I was trying to do](https://stackblitz.com/edit/angular-isdain)

maybe this can be add to documentation
