### ISSUE TITLE
CLI File Naming Options

### ISSUE THREAD

**Issue by Vandivier** [angular/angular#32158]
# 🚀 feature request

### Relevant Package
angular CLI

### Description
 A clear and concise description of the problem or missing capability...
currently when a component is generated it might be called x.component.ts and a service like y.service.ts

This has a few negative effects in my book:
1 - sorting by name does not group components and services together.
2 - Hungarian-like naming becomes awkward, eg `ServiceAnalyticsService`. Service is prepended in the hungarian-like system I like, but it also has to be appended to comply with angular convention.
3 - it doesn't seem possible to programmatically or humanly know whether a folder under app refers to a component, service, module...by looking at the folder name when generating a non-flat entity.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
1 - An option to have the files generated with flipped naming like component.x.ts and service.y.ts
2 - A different option to allow type to be added to the folder name without redundancy. So normal mode is `x-component/x.component.ts` and flipped is `component-x/component.x.ts`

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
I'm personally OK with the redundant naming but my team isn't. So a key workaround would be having a component called ComponentThingComponent or ServiceSomeService.

**Comment by ericmartinezr** [comment]
@Vandivier would you mind opening this in cli's repo https://github.com/angular/angular-cli/issues? 👍

**Comment by Vandivier** [comment]
roger that ty
