### ISSUE TITLE
Angular Elements doesn't work with Angular v5

### ISSUE THREAD

**Issue by arodr967** [angular/angular#32169]
# 🐞 bug report

### Affected Package
I believe this issue is caused by package `webpack: 3.11.0` which is being used in `@angular/cli: 1.7.4`.

### Description

Not the best description but... Putting an angular-elements app into an angular v5 app simply does not work.

## 🔥 Exception or Error
The following is the error shown on the console which points to the bundled javascript from the angular-element app inside of the angular v5 app.

![error](https://user-images.githubusercontent.com/11788477/63181822-0b713b00-c01f-11e9-8bbb-dbb6e83deeeb.png)

<pre><code>Uncaught TypeError: Cannot read property 'bind' of undefined</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 1.7.4
Node: 10.15.0
OS: darwin x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.7.2
webpack: 3.11.0
</code></pre>

**Anything else relevant?**

- Is there a way to run the latest version (or at least v4) of `webpack` in an Angular v5 app? Is there a way to build the angular-elements app so that it doesn't depend on `window["webpackJsonp"]` returning an array?
 
- This issue is the one which makes me believe that the issue might be with the webpack version -- https://github.com/webpack/webpack/issues/6985
- Angular elements works perfectly with an Angular v6 app -- which is using webpack version 4.
- Angular elements app version I am using:
<pre><code>
Angular CLI: 8.0.6
Node: 10.15.0
OS: darwin x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cli                      8.0.6
@angular/elements                 8.2.2
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by jolares** [comment]
using the [`ngx-build-plus`](https://github.com/manfredsteyer/ngx-build-plus/tree/master) extension fixed the problem for us (@arodr967 and I):

1) run `ng add ngx-build-plus@^8.0.0` in your Angular 8 elements project.
2) run `ng update ngx-build-plus --force`.

The problem seems to be a bundle conflict between the Angular 5 consumer app and the custom element one built with Angular 8 (because they both use the global webpackJsonP). @manfredsteyer's extension provides a fix because it does not use webpackJsonP; the web component is a self-contained bundle.

Thank you @zackarychapple and @manfredsteyer for helping us find a solution for this issue.
