### ISSUE TITLE
ERROR in Symbol when compiling with Ivy in 9.0.0-next.2

### ISSUE THREAD

**Issue by davidjeliba** [angular/angular#32166]
# 🐞 bug report

### Affected Package
ngtsc

### Is this a regression?
No

### Description
When running normal production build with aot=true and Ivy disabled the build process completes successfully. Running with Ivy enabled results in the below error.

## 🔬 Minimal Reproduction
https://github.com/davidjeliba/angular-uirouterhybrid-ivy-issue
master branch uses 9.0.0-next.2

To setup/run:

Clone project
run "yarn"
run "yarn build:production" - aot=true, ivy=false - to show successful compilation
run "yarn build:production:ivy" - aot=true, ivy=true - produces the error

## 🔥 Exception or Error
<pre><code>WARNING in Unknown member type: "[key: string]: any;

ERROR in Symbol UIRouterModule declared in angular-uirouterhybrid-ivy-issue/node_modules/@uirouter/angular/lib/uiRouterNgModule.d.ts is not exported from @uirouter/angular-hybrid (import into angular-uirouterhybrid-ivy-issue/src/app/child.module.ts)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 8.3.0-rc.0
Node: 10.15.3
OS: darwin x64
Angular: 9.0.0-next.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.0-rc.0
@angular-devkit/build-angular     0.803.0-rc.0
@angular-devkit/build-optimizer   0.803.0-rc.0
@angular-devkit/build-webpack     0.803.0-rc.0
@angular-devkit/core              8.3.0-rc.0
@angular-devkit/schematics        8.3.0-rc.0
@angular/cli                      8.3.0-rc.0
@ngtools/webpack                  8.3.0-rc.0
@schematics/angular               8.3.0-rc.0
@schematics/update                0.803.0-rc.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

The change @petebacondarwin made in https://github.com/angular/angular/issues/31342 seems to have removed the first unknown member type warning that was also present in the 8.1.0-rc.0 example.

<pre><code>WARNING in Unknown member type: "[key: string]: (data: any) => void;

WARNING in Unknown member type: "[key: string]: any;

ERROR in Symbol UIRouterModule declared in angular-uirouterhybrid-ivy-issue/node_modules/@uirouter/angular/lib/uiRouterNgModule.d.ts is not exported from @uirouter/angular-hybrid (import into angular-uirouterhybrid-ivy-issue/src/app/child.module.ts)
</code></pre>

**Comment by davidjeliba** [comment]
Still present in 9.0.0-next.3 - I have updated the example.

Also yarn build:production is now essentially the same command as yarn build:production:ivy in the example project now that Ivy is enabled by default as of next.3

**Comment by davidjeliba** [comment]
Tested on 9.0.0-next.18 and updated reproduction repo.

No warnings now, just the error as per first post.

**Comment by davidjeliba** [comment]
Probably not relevant at the moment to be an Angular issue.

@uirouter/angular issue tracking Ivy support is probably more relevant https://github.com/ui-router/angular/issues/516

**Comment by petebacondarwin** [comment]
The `ivy` branch in the uirouter/angular repository does work with v9 now.
See https://github.com/ui-router/angular/issues/516#issuecomment-539767843

**Comment by petebacondarwin** [comment]
But I see that the original issue is with `@ui-router/angular-hybrid` not `@ui-router/angular`. so I am reopening this while I investigate.

**Comment by petebacondarwin** [comment]
This package has a separate issue from the `uirouter/angular` package. Working on a solution...
