### ISSUE TITLE
Styles not applied in component rendered with Ivy

### ISSUE THREAD

**Issue by keilla** [angular/angular#32179]
# 🐞 bug report

### Affected Package

 The issue was founded with release 9.0.0-next.2

### Is this a regression?

 No, it wasn't working with v8.1.2 too.

### Description

 
I used ɵrenderComponent as follow:
ɵrenderComponent(MyApp);

MyComponent class:

@Component({
  selector: 'my-app',
  templateUrl: './my-app.component.html',
  styleUrls: ['./my-app.component.scss']
})

I also try to use inside styles array:

@Component({
  selector: 'my-app',
  templateUrl: './my-app.component.html',
  styles: [`
  .comment-card {
    border: 1px solid $grey-80;
  },
  `],
})

After build, I inspected file generated: my-app.component.js and it the styles are in ngComponentDef: 

styles: [".comment-card[_ngcontent-%COMP%] {\n    border: 1px solid $grey-80;\n  },"] });

And it was declared the element with css class in the JavaScript file:

const _c0 = [1, "comment-card"]

Although, the style is only applied to the component when CSS styles are global.

## 🔬 Minimal Reproduction

I couldn't reproduce with StackBlitz. The code is at GitHub: https://github.com/keilla/angular-ivy-elements/tree/master/likable-comment-ivy-angular-app

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.2.2
Node: 10.10.0
OS: darwin x64
Angular: 9.0.0-next.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.2
@angular-devkit/build-angular     0.802.2
@angular-devkit/build-optimizer   0.802.2
@angular-devkit/build-webpack     0.802.2
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.2.2
@angular/cli                      8.2.2
@ngtools/webpack                  8.2.2
@schematics/angular               8.2.2
@schematics/update                0.802.2
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0

</code></pre>

**Anything else relevant?**

**Comment by kara** [comment]
@keilla `renderComponent` uses the DOM by default (not `Renderer2`), so you won't get inline styles from the renderer. If you want to use it with `Renderer2`, you can provide `Renderer2Factory` as the rendererFactory in the options arg:

https://github.com/angular/angular/blob/master/packages/core/src/render3/component.ts#L35
