### ISSUE TITLE
Override where XMLHttpRequest comes from?

### ISSUE THREAD

**Issue by phillip-haydon** [angular/angular#3217]
With jQuery and $.ajax you can specify a function for xhr

```
$.ajax({
    ....
    xhr: function() {....}
});
```

What is the equivalent of this in Angular?

**Comment by gdi2290** [comment]
this is angular2 and you could do that easily in the bindings
`[ bind(BrowserXhr).toClass(YouCustomXhr) ]`

**Comment by phillip-haydon** [comment]
Blah ok sorry! I'll close and re-open in Angular 1.#

Repo names are not good here :/
