### ISSUE TITLE
'data' attribute missing for <object/> when it's value is build of static part and variable

### ISSUE THREAD

**Issue by Eljah** [angular/angular#32183]
# 🐞 bug report

### Affected Package

 The issue is caused by no idea what is the package processing the template

### Is this a regression?
I don't know, but I have seen some related issue: https://github.com/angular/angular/issues/18184

 

### Description

 
https://stackoverflow.com/questions/57550423/how-to-workaround-data-attribute-missing-in-angular-when-it-is-build-of-static 

I have a couple of template tags in Angular like that:

```
<object type="application/x-shockwave-flash" data="api/swfgames/{{ game.id }}.swf" width="{{ game.width }}" height="{{ game.height }}">
   <param name="movie" value="api/swfgames/{{ game.id }}.swf"/>
   <a href="http://www.adobe.com/go/getflash">
   <!--<img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" crossorigin="anonymous" alt="Get Adobe Flash player"/>-->Get Flash!</a>
</object>
```
and to investigate I have tried variable-less approach to object tag with the variable value hard-coded.

`<object type="application/x-shockwave-flash" data="api/swfgames/1052.swf" width="260" height="23">
`And I get it rendered as

```
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="myFlashMovie" width="730" height="605" align="middle"> <param name="movie" value="api/swfgames/1052.swf">
    <object type="application/x-shockwave-flash" width="730" height="605">
        <param name="movie" value="api/swfgames/1052.swf">  
        <br>
        <a href="http://www.adobe.com/go/getflash"> Get Flash!</a>
    </object>
</object>

```
(note there is no data attribute for the inner object tag there; also note width and height that are successfully renedered of the variable) and

`<object data="api/swfgames/1052.swf" type="application/x-shockwave-flash" width="260" height="23">`
(note there the data attribute exists and make the tag workig)

How I can force data attribute to be rendered as concatenation of the static string and the variable?

UPD

`<object type="application/x-shockwave-flash" data="{{ 'api/swfgames/' +  game.id }}.swf" width="{{ game.width }}" height="{{ game.height }}">`
also doesn't help

UPD2. And the same doesn't work even with <embed type="application/x-shockwave-flash" src='{{ "api/swfgames/" +  game.id + ".swf" }}' width="{{ game.width }}" height="{{ game.height }}"/>

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular version is 8.0.0 (comes with jHipster 6.2.0)

</code></pre>

**Anything else relevant?**

**Comment by Eljah** [comment]
<embed type="application/x-shockwave-flash" src='{{ "api/swfgames/" +  game.id + ".swf" }}' width="{{ game.width }}" height="{{ game.height }}"/> also doesn't work

**Comment by mhevery** [comment]
We need a stackblitz showing the issue, otherwise we can't investigate it.

**Comment by Eljah** [comment]
@mhevery I have reproduced it there: https://stackblitz.com/edit/angular-xyjwxl

it doesn't render the data attribute for the object tag

![image](https://user-images.githubusercontent.com/2749858/64359326-c5e9d180-d010-11e9-8a42-fd2bd8232104.png)

**Comment by Eljah** [comment]
Unfortunately stackblitz doesn't allow me to upload a small swf file to the project so I had to check this with Chrome console inspector.

**Comment by mhevery** [comment]
Open the console and you will see this:

```
ERROR Error: unsafe value used in a resource URL context (see http://g.co/ng/security#xss)
    at DomSanitizerImpl.sanitize (dom_sanitization_service.ts:180)
    at setElementProperty (element.ts:306)
    at checkAndUpdateElementValue (element.ts:253)
    at checkAndUpdateElementInline (element.ts:209)
    at checkAndUpdateNodeInline (view.ts:425)
    at checkAndUpdateNode (view.ts:389)
    at debugCheckAndUpdateNode (services.ts:431)
    at debugCheckRenderNodeFn (services.ts:416)
    at Object.eval [as updateRenderer] (AppComponent.html:13)
    at Object.debugUpdateRenderer [as updateRenderer] (services.ts:410)
```

There error is because you are trying to write a potential un-sanitize value to the DOM which could be dengerous. See https://angular.io/guide/security

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Eljah** [comment]
@mhevery it is already on Stackoverflow under the angular tag and I'm asking for the work around there, as i need create object tag fro loading the swf files dynamically: https://stackoverflow.com/questions/57550423/how-to-workaround-data-attribute-missing-in-angular-when-it-is-build-of-static

Could you please review it and give me advice how to work it around.

**Comment by Eljah** [comment]
@mhevery So any solution for the forming of working dynamically created object tag from the variable that I'm passing from my rest backend are welcomed and please post them to the stackoverflow question. For now I have no idea how to dynamically load the swf files to the frontend from the database through the rest backend.

**Comment by Eljah** [comment]
@mhevery nobody answered my to my stackoverflow quiestion. should I use sanitized url or what?
