### ISSUE TITLE
Better with  statement detection

### ISSUE THREAD

**Issue by oleersoy** [angular/angular#32182]
Right now all we get is:

:4200/vendor.js:107024 Uncaught SyntaxError: Strict mode code may not include a with statement

And no further information on what package / file is causing the problem.

https://stackoverflow.com/questions/57548407/4200-vendor-js107024-uncaught-syntaxerror-strict-mode-code-may-not-include-a

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
