### ISSUE TITLE
Angular 8 upgrade docs for 'Local development in older browsers' should mention a couple of changes that will need to be made to the sample config information. 

### ISSUE THREAD

**Issue by devin5885** [angular/angular#32199]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

On the page:
https://angular.io/guide/deployment#local-development-in-older-browsers

there is the following for the upgrade of Angular.json:

"es5": {
      "browserTarget": "app:build:es5"
    }

It should mention that the string 'app' should be replaced with the name of the app.

The e2e section needs the same note.

Also, it might be nice to mention that the path to your tsconfig.app.json file might be under 'src' for older projects.

### What's the affected URL?**
 https://angular.io/guide/deployment#local-development-in-older-browsers

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by AndrewKushnir** [comment]
@devin5885 could you please provide more information on this issue (like links to specific pages, the content that is missing, etc)?

**Comment by devin5885** [comment]
Sorry, when I submitted the text I entered was deleted from some reason.
