### ISSUE TITLE
Angular component render in browser after console opens

### ISSUE THREAD

**Issue by gomteshhatgine** [angular/angular#32195]
Recently in project HTML rendering in angular projet is done when we open browser console or else it will not even initiaze componet due to which that component is not rendered in browser.
Even if i hit the URL directly then also it will open but when we navigate to that page it will just giving blanck page.

in console ther is warning message : 
Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?
  | navigateByUrl | @ | router.js:4666
  | onClick | @ | router.js:5562
  | (anonymous) | @ | DataSetsListComponent.html:5
  | handleEvent | @ | core.js:12888
  | callWithDebugContext | @ | core.js:14463
  | debugHandleEvent | @ | core.js:14074
  | dispatchEvent | @ | core.js:9304
  | (anonymous) | @ | core.js:9964
  | (anonymous) | @ | platform-browser.js:1654
  | globalListener | @ | platform-browser.js:2110

**Comment by AndrewKushnir** [comment]
@gomteshhatgine it seems like your request doesn't contain enough information. Could you please provide a repro (for example using https://stackblitz.com/)? Thank you.

**Comment by hakimio** [comment]
Doesn't the warning message explain your issue: `Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'`?
Looks like an issue in your app, not Angular bug.

**Comment by gomteshhatgine** [comment]
I think change detection issue, when I use
** this.ngZone.run(() => this.router.navigate(commands)).then();**
then the page is loading properly
But why it is breaking change detection

**Comment by atscott** [comment]
I'm sorry but we can't reproduce the problem you are reporting. We require that reported issues have a minimal reproduction that showcases the problem.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template that include info on how to create a reproduction using our template.
