### ISSUE TITLE
Ivy: using svg with a class has a runtime error on IE11

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#32192]
# 🐞 bug report

### Affected Package

 The issue is caused by package `@angular/core`

### Is this a regression?

 I don't know.

### Description

Ivy: using svg with a class, like `<svg class="something"></svg>` has a runtime error on IE11. Using a svg tag without a class will not show an error.

## 🔬 Minimal Reproduction
- `npm i -g git+https://github.com/angular/cli-builds.git` (when CLI 9.0.0-next.0 is available you can instead do `npm i -g @angular/cli@9.0.0-next.0`)
- `ng new ivy-svg-app && cd ivy-svg-app`
- replace the contents of `src/app/app.component.html` with `<svg class="something"></svg>`
- `ng serve --prod`
- open http://localhost:4200 on IE11

## 🔥 Exception or Error

![image](https://user-images.githubusercontent.com/4172079/63285640-1d1c4200-c2ae-11e9-8c71-26b3d319bdbc.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.0-rc.0
Node: 10.16.0
OS: win32 x64
Angular: 9.0.0-next.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.0-rc.0
@angular-devkit/build-angular     0.803.0-rc.0
@angular-devkit/build-optimizer   0.803.0-rc.0
@angular-devkit/build-webpack     0.803.0-rc.0
@angular-devkit/core              8.3.0-rc.0
@angular-devkit/schematics        8.3.0-rc.0
@angular/cli                      8.3.0-rc.0
@ngtools/webpack                  8.3.0-rc.0
@schematics/angular               8.3.0-rc.0
@schematics/update                0.803.0-rc.0
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>
**Anything else relevant?**

**Comment by filipesilva** [comment]
Should be fixed by https://github.com/angular/angular/pull/32111

**Comment by pkozlowski-opensource** [comment]
@filipesilva I believe that this one should be fixed with RC.11 - would you mind verifying?

**Comment by filipesilva** [comment]
Tried to reproduce with a project using `@angular/core@9.0.0-rc.9` and could not see the problem anymore.
