### ISSUE TITLE
Support async keyword by correctly intercepting it in zones

### ISSUE THREAD

**Issue by Alxandr** [angular/angular#322]
Traceur has support for async functions, which makes writing functions that use promises a lot easier in javascript. As far as I know (and last time I checked) it was hidden away behind a flag. Is this enabled in AtScript? If not, could it be enabled by default? This might also end up driving the implementation of the async support due to usage.

Async functions can make some aspects of promises incredibly easier. Example:

Without async:
```js
function foo() {
    return getValues().then(function(values) {
        return values.reduce(function(previousOperation, value) {
            return previousOperation.then(function(newValues) {
                return asyncOperation(value).then(function(newValue) {
                    console.log(newValue);
                    newValues.push(newValue);
                    return newValues;
                });
            });
        }, Promise.resolve([]));
    }).catch(function(err) {
        console.log('We had an ', err);
    });
}
```

With async:
```js
async function foo() {
  try {
    let result = [];
    for (let value of await getValues()) {
      let newVal = await asyncOperation(value);
      console.log(newVal);
      result.push(newVal);
    }
    return result;
  } catch (e) {
    console.log('We had an ', e);
  }
}
```

**Comment by btford** [comment]
:+1:

**Comment by vicb** [comment]
`async` / `await` is planned for TS 1.6 (https://github.com/Microsoft/TypeScript/issues/1664).

I guess there will be nothing to do when the target is ES6.

**Comment by gdi2290** [comment]
if you're talking about template syntax there is a AsyncPipe for example
```html
<li *ng-for="qux of foo() | async">
  {{ qux }}
<li>
```

**Comment by andrashatvani** [comment]
This is still an issue.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

**Comment by wizarrc** [comment]
@Alxandr @andrashatvani I figured out a workaround way to get async/await working using TypeScript 1.8, webpack, and babel.

https://github.com/angular/angular/issues/7381#issuecomment-240222667

I'm thinking out loud that one could try the same thing loading zone.js before your Traceur and then at the top of your Traceur. I have not used Traceur, but if it's anything like babel, there is a method you can replace to override the promise used by the async generator.
