### ISSUE TITLE
Bug in getBaseElementHref from browser_adapter

### ISSUE THREAD

**Issue by hitmanmcc** [angular/angular#3220]
Hi all!

I just changed to the newest alpha build (32) and I came across this error:
![image](https://cloud.githubusercontent.com/assets/3464842/8849528/62463c3e-3138-11e5-96ac-d41b473547cd.png)

Which I solved by adding a base tag to index.html file, like so:
```html
<base href="http://localhost:47040/index.html" target="_blank" />
```

Having done this I then got a new error as you can see below:
![image](https://cloud.githubusercontent.com/assets/3464842/8849602/e18922a4-3138-11e5-9050-508e67d09a81.png)

It would appear that someone tried to call a function (attr) that does not exist for that particular object, the syntax almost makes it seem like the attr function from jQuery.
I downloaded the source for angular2.dev.js instead of loading it directly from your CDN and changed the line:
```javascript
return baseElement.attr('href');
```
to vanilla javascript:
```javascript
return baseElement.getAttribute('href');
```
Once I did this, everything was working fine. It seems like something I should bring to your attention.

Best regards,
André

**Comment by markharding** [comment]
see https://github.com/angular/angular/commit/8296dcec09d9b8be0d4cfcc492000d5cc401cfa0#commitcomment-12317209

**Comment by hitmanmcc** [comment]
Thanks for the heads-up.
