### ISSUE TITLE
Submit button for each FormGroup in an FormArray

### ISSUE THREAD

**Issue by bejgumshirisha** [angular/angular#32208]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/forms

### Description
 In current FormsModule we can have only one submit button for form.We cannot create separate submit buttons for each  formgroup in formarray.

### Describe the solution you'd like
 If we can have  individual submit action for each formgroup in formarray then we can ignore validations of other formgroups can submit the data.
On Parent form submit if we can remove validations for formarray based on selection then we can submit the data to server

### Describe alternatives you've considered
 I have tried to use regular button with submitted variable for each formgroup in formarray but it is not working because of index and also not working as default submit action

**Comment by santoshyadav198613** [comment]
This is not Angular restriction, this is how forms work in HTML, you can add multiple buttons and add using click action.

**Comment by bejgumshirisha** [comment]
> This is not Angular restriction, this is how forms work in HTML, you can add multiple buttons and add using click action.

using click action can we validate each formgroup within a formarray. If yes can you please provide any links

**Comment by santoshyadav198613** [comment]
Hi @bejgumshirisha ,

Yes, it can be achieved, I would suggest raising this on StackOverFlow using Angular tag, the community will help.

**Comment by bejgumshirisha** [comment]
> Hi @bejgumshirisha ,
> 
> Yes, it can be achieved, I would suggest raising this on StackOverFlow using Angular tag, the community will help.

@santoshyadav198613  : Already created a question.
[https://stackoverflow.com/questions/57558168/can-we-have-different-submit-button-for-each-formgroup-in-formarray-using-angula](url)

**Comment by santoshyadav198613** [comment]
Ok, I have commented on the issue, you can close this one.
