### ISSUE TITLE
Ivy: compiler errors are not fully displayed on rebuild

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#32213]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler-cli

### Is this a regression?

 I don't know

### Description

AOT errors are only fully displayed on initial build. On rebuilds, the line numbers and erroneous code are not displayed.

## 🔬 Minimal Reproduction
- `npm install -g @angular/cli@next`
- `ng new ivy-rebuild-project && cd ivy-rebuild-project`
- introduce an AOT error by replacing `selector: 'app-root',` with `selector: (() => 'app-root')(),` in `src/app/app.component.ts`
- update Angular Framework versions to `9.0.0-next.2`
- set `angularCompilerOptions.enableIvy` to `true` in `tsconfig.json` if it's not there
- run `yarn ngc -p tsconfig.app.json -w`
- wait for the build error message, see that it contains all information
- remove the AOT error and save the file
- wait for the successful build
- re-introduce the error
- wait for the build error message, see that it contains partial information

## 🔥 Exception or Error
<pre><code>
kamik@RED-X1C6 MINGW64 /d/sandbox/snapshot-project (master)
$ yarn ngc -p tsconfig.app.json -w
yarn run v1.12.3
$ D:\sandbox\snapshot-project\node_modules\.bin\ngc -p tsconfig.app.json -w
src/app/app.component.ts(4,13): error TS-991010: selector must be a string

Compilation failed. Watching for file changes.

src/app/app.component.ts:4:13 - error NG1010: selector must be a string

4   selector: (() => 'app-root')(),
              ~~~~~~~~~~~~~~~~~~~~


File change detected. Starting incremental compilation.

Compilation complete. Watching for file changes.

File change detected. Starting incremental compilation.

src/app/app.component.ts(4,13): error TS-991010: selector must be a string

Compilation failed. Watching for file changes.
</code></pre>

Note that the first build had errors with line numbers and example, but the second one did not.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.0-rc.0
Node: 10.16.0
OS: win32 x64
Angular: 9.0.0-next.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.0-rc.0
@angular-devkit/build-angular     0.803.0-rc.0
@angular-devkit/build-optimizer   0.803.0-rc.0
@angular-devkit/build-webpack     0.803.0-rc.0
@angular-devkit/core              8.3.0-rc.0
@angular-devkit/schematics        8.3.0-rc.0
@angular/cli                      8.3.0-rc.0
@ngtools/webpack                  8.3.0-rc.0
@schematics/angular               8.3.0-rc.0
@schematics/update                0.803.0-rc.0
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**
<!-- ✍️Is this a browser specific issue? If so, please specify the browser and version. -->

<!-- ✍️Do any of these matter: operating system, IDE, package manager, HTTP server, ...? If so, please mention it below. -->

**Comment by alxhub** [comment]
It would appear that the watch mode uses a different method to print out `ts.Diagnostic`s. This should be a trivial fix.

**Comment by IgorMinar** [comment]
@alxhub says that https://github.com/angular/angular/pull/33862 should fix this one as well
