### ISSUE TITLE
Missing Command to Properly Follow Through the Setup Tutorial

### ISSUE THREAD

**Issue by Marwan01** [angular/angular#32216]
# 📚 Docs or angular.io bug report

### Description

 I was on the Angular website today, getting ready to learn the language. As I was following the instructions in the page in the mentioned URL, I could not proceed to Step 3. I realized it was because I did not execute npm install to get the node_modules after Step 2.

### What's the affected URL?**
 https://angular.io/guide/setup-local

## 🔥 Exception or Error
 Different node_modules related errors with different machines.

## 🌍  Your Environment
Macbook Pro + VS Code + Google Chrome

### Anything else relevant?
I believe the solution is just to add a note between step 2 and step 3 to tell the users to execute:
npm install
and explain why this is important.

**Comment by santoshyadav198613** [comment]
Hi @Marwan01 ,

ng new appname installs the dependency, that's why it is not mentioned.

**Comment by Marwan01** [comment]
![Screen Shot 2019-08-20 at 10 40 01 AM](https://user-images.githubusercontent.com/25825598/63362117-edfde300-c336-11e9-8412-b0a57348ff43.png)

I got this error after trying that. Could it be not from the missing node_modules? If so I can close this issue!

**Comment by santoshyadav198613** [comment]
Sometime installation gets failed due to multiple reasons, where you need to install it manually. Otherwise you don't need to do it manually.

**Comment by Marwan01** [comment]
Oh okay! I would suggest to still put in a little note just in case because this happened to me with two computers. Otherwise thank you for getting back to me and this shouldn't be an issue anymore!
