### ISSUE TITLE
Angular 8 upgrade docs could mention that some core.js related polyfills are no longer needed.

### ISSUE THREAD

**Issue by devin5885** [angular/angular#32228]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

The Angular 8 upgrade removes references to the core.js polyfills in pollyfills.js (e.g.)

import 'core-js/es6/symbol';
import 'core-js/es6/object';
etc.

According to the following pages this is because Angular 8 includes core.js explicitly:

https://stackoverflow.com/questions/56892243/is-not-core-js-needed-anymore, and https://blog.ninja-squad.com/2019/05/29/angular-cli-8.0/

It would be good to mention which pollyfills are no longer needed in the migration docs.

### What's the affected URL?**
 https://update.angular.io/#7.0:8.0

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by trotyl** [comment]
> core.js related polyfills are no longer needed.

That's simply not true, only polyfills used by Angular itself became no longer needed, which is [based on Angular source code analysis](https://github.com/angular/angular-cli/pull/15246/commits/f0b6cd81a68e7693497e2975c8dc55eb71f57745). Your application may need far more JavaScript features than Angular itself, especially for 3rd-party libraries used.

Also, the generated `es5-polyfills.js` only contains ES2015 feature, so any of ES2016, ES2017, ES2018, ES2019, ES2020 or WIP proposals features still require manual imports. See https://github.com/angular/angular-cli/issues/14168 for more information.

**Comment by devin5885** [comment]
So I guess this means that any pollyfills that are listed in 

https://github.com/clydin/angular-cli/blob/f0b6cd81a68e7693497e2975c8dc55eb71f57745/packages/angular_devkit/build_angular/src/angular-cli-files/models/es5-polyfills.js

are no longer needed, but anything else is. Correct?

**Comment by trotyl** [comment]
> So I guess this means that any pollyfills that are listed in `es5-polyfills.js` are no longer needed, but anything else is. Correct?

Yep, anything listed there are forced to be add in ES5 bundle, cannot be controlled by user.

> Also, I am thinking these are the ones that the upgrade removed, anything else is not removed?

If you don't have any extra polyfill than default ones, that's true.

**Comment by falsyvalues** [comment]
> > So I guess this means that any pollyfills that are listed in es5-polyfills.js are no longer needed, but anything else is. Correct?

> Yep, anything listed there are forced to be add in ES5 bundle, cannot be controlled by user.

Why? They should be predefined but still editable for developers. Simple case, Angular hybrid app which may already have polyfills we should not be forced to keep them in build. 
Only build related polyfill should be mandatory.

**Comment by trotyl** [comment]
> Why? They should be predefined but still editable for developers. Simple case, Angular hybrid app which may already have polyfills we should not be forced to keep them in build.

I don't know the real answer though, I guess it's for simplicity, also ES5 support is no-longer the default (first-class) case in Angular CLI. Feel free to continue discussion at https://github.com/angular/angular-cli/issues/14168.

**Comment by jbogarthyde** [comment]
Is there still a docs issue? Do you have a suggestion for improving the Update tool, or specific doc pages?

**Comment by alan-agius4** [comment]
Closing since this issue isn't completing enough to warrant a docs update considering that version 7 and 8 are no longer supported, and the activity in this issue is low.

Thanks.
