### ISSUE TITLE
child component as root of parent component does not get rendered

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#3222]
For some reason if I have a [parent](https://github.com/rolandjitsu/ng2-play/tree/33d035476b9954a67792ffee2f9d0ba141016c66/src/app/components/todo_list) component which [view](https://github.com/rolandjitsu/ng2-play/tree/33d035476b9954a67792ffee2f9d0ba141016c66/src/app/components/todo_list/todo_list.html)'s consists of a [child](https://github.com/rolandjitsu/ng2-play/tree/33d035476b9954a67792ffee2f9d0ba141016c66/src/app/components/todo_item) component, the child component does not get rendered anymore.

That happens if I use `NativeShadowDomStrategy`, used like shown [here](https://github.com/rolandjitsu/ng2-play/tree/33d035476b9954a67792ffee2f9d0ba141016c66/src/common/shadow_dom.ts). But if I don't inject the [shadowDomInjectables](https://github.com/rolandjitsu/ng2-play/tree/33d035476b9954a67792ffee2f9d0ba141016c66/src/app/bootstrap.ts#L15) that I created (visible on the previous url) then everything seems to work fine.

It also works if I wrap the `<todo-item [model]="todo" *ng-for="#todo of todos"></todo-item>` with another dom element.

**Comment by rolandjitsu** [comment]
I've also noticed that if I do wrap `<todo-item [model]="todo" *ng-for="#todo of todos"></todo-item>` with a `<div>` (which fixes the issue of the component not being rendered), the component no longer uses native shadow dom as I cannot find the `#shadow-root` in the element inspector.

**Comment by mhevery** [comment]
could you add plnkr.co

**Comment by rolandjitsu** [comment]
@mhevery I actually have the [app](https://ng2-play.firebaseapp.com/) running and I am not sure I can reproduce the same circumstances. Wouldn't it be easier to just clone the [repo](https://github.com/rolandjitsu/ng2-play) and run it locally?

**Comment by mhevery** [comment]
Is this still an issue? Or can this be closed?

**Comment by rolandjitsu** [comment]
I think it can be closed, I'll check if the issue still occurs and I'll open it if so.
