### ISSUE TITLE
Using zone.js 0.10.1 in an angular app is not working on IE 11

### ISSUE THREAD

**Issue by jmesa-sistel** [angular/angular#32237]
# 🐞 bug report

### Affected Package

 The issue is caused by package zone.js

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 0.10.0

### Description

 
If you update `zone.js` to "0.10.1" in an angular webapp then IE11 will show the next error in console:
`In this configuration Angular requires Zone.js`

## 🔬 Minimal Reproduction

Create a angular 8.2.2 app, update zone.js to "0.10.1", then build the app and then open it in IE11
If you try with 0.10.0 everything works fine on IE11

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.2.2
Node: 12.7.0
OS: win32 x64
Angular: 8.2.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.2
@angular-devkit/build-angular     0.802.2
@angular-devkit/build-optimizer   0.802.2
@angular-devkit/build-webpack     0.802.2
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.2.2
@angular/cdk                      8.1.3
@angular/pwa                      0.802.2
@ngtools/webpack                  8.2.2
@schematics/angular               8.2.2
@schematics/update                0.802.2
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0
</code></pre>

**Anything else relevant?**

**Comment by JiaLiPassion** [comment]
@jmesa-sistel , could you try to update to zone.js `0.10.2` to confirm it is ok or not? thanks.

**Comment by jmesa-sistel** [comment]
@JiaLiPassion `0.10.2` is not working, the error happens when you move from `0.10.0` to `0.10.1`

**Comment by JiaLiPassion** [comment]
Could you provide a reproduce repo? And could you show me the error from Dev tools? Thanks.

**Comment by jmesa-sistel** [comment]
@JiaLiPassion I cannot reproduce with a simple angular app.
My app is a bit complicated
I will try to create a minimal repo to show you the problem

**Comment by jmesa-sistel** [comment]
@JiaLiPassion 
The problem is on my side. I'm integrating the angular app inside jira, seems that a global var is been 
exposed and I have conflict with others js files from jira.
