### ISSUE TITLE
TestRequest can't convert correct body by Content-Type

### ISSUE THREAD

**Issue by wszgrcy** [angular/angular#32232]
# 🐞 bug report

### Affected Package
@angular/common/http/testing

### Is this a regression?
unknown

### Description
Because of unit test,I test http request with HttpClientTestingModule.
But the when the body is json and header-`Content-Type` not `application/json`,
I get the `TestRequest` instance by`httpTestingController.expectOne('xxx')`
the testQuest.request's body is also origin not convert

## 🔬 Minimal Reproduction
`Content-Type` is `application/x-www-form-urlencoded` so body must as string like` { p1: 1, p2: 2 }`,but `req.request.body` also a object
```ts
  it('origin', async (done) => {
    http.post('http://127.0.0.1:3000/aaa', { p1: 1, p2: 2 }, {
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
      }
    }).subscribe((val) => {
      done()
    })
    let req = httpTestingController.expectOne('http://127.0.0.1:3000/aaa');
    req.event(new HttpResponse({ body: { c: 'retrun' }, status: 200 }))
  })
```
## 🔥 Exception or Error
the body we assign shoud auto convert with `Content-Type`

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.2.0
Node: 10.15.3
OS: win32 x64
Angular: 8.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.802.0
@angular-devkit/build-angular      0.802.0
@angular-devkit/build-ng-packagr   0.802.0
@angular-devkit/build-optimizer    0.802.0
@angular-devkit/build-webpack      0.802.0
@angular-devkit/core               8.2.0
@angular-devkit/schematics         8.2.0
@angular/cdk                       8.1.2
@angular/http                      7.2.15
@angular/material                  8.1.2
@ngtools/webpack                   8.2.0
@schematics/angular                8.2.0
@schematics/update                 0.802.0
ng-packagr                         5.4.3
rxjs                               6.5.2
typescript                         3.5.3
webpack                            4.38.0
</code></pre>

**Anything else relevant?**

**Comment by alxhub** [comment]
This is working as designed.

`HttpClientTestingModule` is not designed to be a universal mock HTTP server. It does not emulate things such as HTTP serialization or MIME types, for example. Instead, think of it as a mock of `XMLHttpRequest` - whatever you put in the `body` is whatever will be handed to the browser to be serialized.
