### ISSUE TITLE
IVY: library ngx-socket-io errors during serve (9.0.0-next.3)

### ISSUE THREAD

**Issue by spock123** [angular/angular#32242]
# 🐞 bug report

### Affected Package
I am using the library ngx-socket-io to provide socket.io connection to my server.
Everything works fine without IVY.

Library:
[https://github.com/rodgc/ngx-socket-io](https://github.com/rodgc/ngx-socket-io)

### Is this a regression?
Never worked with IVY
Always worked without IVY

.

## 🔬 Minimal Reproduction
I have made a very simple project: 

[https://github.com/spock123/angular-ivy-ngx-socket-io](https://github.com/spock123/angular-ivy-ngx-socket-io)

Steps to reproduce:

```
npm install
npm run serve
```

## 🔥 Exception or Error
<pre><code>
ERROR in Attempted to get members of a non-class: "class PerMessageDeflate {
  /**
   * Creates a PerMessageDeflate instance.
   *
   * @param {Object} options Configuration options
   * @param {Boolean} options.serverNoContextTakeover Request/accept disabling
   *     of server context takeover
   * @param {Boolean} options.clientNoContextTakeover Advertise/acknowledge
   *     disabling of client context takeover
   * @param {(Boolean|Number)} options.serverMaxWindowBits Request/confirm the
   *     use of a custom server window size
   * @param {(Boolean|Number)} options.clientMaxWindowBits Advertise support
   *     for, or request, a custom client window size
   * @param {Object} options.zlibDeflateOptions Options to pass to zlib on deflate
   * @param {Object} options.zlibInflateOptions Options to pass to zlib on inflate
   * @param {Number} options.threshold Size (in bytes) below which messages
   *     should not be compressed
   * @param {Number} options.concurrencyLimit The number of concurrent calls to
   *     zlib
   * @param {Boolean} isServer Create the instance in either server or client
   *     mode
   * @param {Number} maxPayload The maximum allowed message length
   */
  constructor(options, isServer, maxPayload) {
    this._maxPayload = maxPayload | 0;
    this._options = options || {};

... and a ton more (truncated)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.0-rc.0
Node: 12.2.0
OS: darwin x64
Angular: 9.0.0-next.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.0-rc.0
@angular-devkit/build-angular     0.803.0-rc.0
@angular-devkit/build-optimizer   0.803.0-rc.0
@angular-devkit/build-webpack     0.803.0-rc.0
@angular-devkit/core              8.3.0-rc.0
@angular-devkit/schematics        8.3.0-rc.0
@angular/cdk                      8.1.2
@angular/cli                      8.3.0-rc.0
@angular/material                 8.1.2
@angular/pwa                      0.803.0-rc.0
@ngtools/webpack                  8.3.0-rc.0
@schematics/angular               8.3.0-rc.0
@schematics/update                0.803.0-rc.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

OS: Mac OS, Node 12

**Comment by spock123** [comment]
Forgot to mention: 
- if you remove the socket-io module in the app.module, and remove references to it in app.component.ts the error disappears.

**Comment by spock123** [comment]
Upgraded the linked project to next.3 - same issue.

**Comment by spock123** [comment]
FWIW I have dropped using the library and am now using rxjs/socket (which compiles under Ivy).

You guys can close this issue if you want, but if other people are using the library, the issue will still be there...

**Comment by gkalpak** [comment]
It seems to work with the latest versions (Angular v9.0.0-rc.0).
If anyone is still running into problems, please open a new issue.
