### ISSUE TITLE
ngIf with two async Pipes using local template variables: Parser Error: Missing expected )

### ISSUE THREAD

**Issue by cpeisert** [angular/angular#32240]
# 🐞 bug report

### : ngIf with two async Pipes using local template variables: Parser Error: Missing expected )

Templates work as expected:

```
<div *ngIf="data1$ | async as data1">
    <p><b>data1 (one conditional)</b>: {{ data1 }}</p>
</div>

<div *ngIf="data1$ && data2$">
    <p><b>data1$ && data2$</b>: {{ data1$ | async }} && {{ data2$ | async }}</p>
</div>

<div *ngIf="(data1$ | async) && (data2$ | async)">
    <p><b>(data1$ | async) && (data2$ async)</b>: {{ data1$ | async }} && {{ data2$ | async }}</p>
</div>
```

Template error

```
<div *ngIf="(data1$ | async as data1) && (data2$ | async as data2)">
    <p><b>(data1$ | async as data1) && (data2$ async as data2)</b>: {{ data1 }} && {{ data2 }}</p>
</div>
```

## 🔬 Minimal Reproduction

Stackblitz example: https://stackblitz.com/edit/angular-templatebug-baxxkq?file=index.html

## 🔥 Exception or Error
<pre><code>
Error: Template parse errors:
Parser Error: Missing expected ) at column 17 in [(data1$ | async as data1) && (data2$ | async as data2)] in ng:///AppModule/AppComponent.html@13:5 ("

<div [ERROR ->]*ngIf="(data1$ | async as data1) && (data2$ | async as data2)">
    <p><b>(data1$ | async as data1) "): ng:///AppModule/AppComponent.html@13:5
Parser Error: Missing expected ) at column 17 in [(data1$ | async as data1) && (data2$ | async as data2)] in ng:///AppModule/AppComponent.html@13:5 (") && (data2$ | async as data2)">
    <p><b>(data1$ | async as data1) && (data2$ async as data2)</b>[ERROR ->]: {{ data1 }} && {{ data2 }}</p>
</div>
"): ng:///AppModule/AppComponent.html@14:66
    at syntaxError (util.ts:100)
    at TemplateParser.parse (template_parser.ts:106)
    at JitCompiler._parseTemplate (compiler.ts:297)
    at JitCompiler._compileTemplate (compiler.ts:275)
    at eval (compiler.ts:206)
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.ts:206)
    at eval (compiler.ts:108)
    at Object.then (util.ts:89)
    at JitCompiler._compileModuleAndComponents (compiler.ts:107)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Current build: 8.1.2
</code></pre>

**Comment by trotyl** [comment]
This is expected behavior, `as` is not related to the previous expression in any case.

```html
<el *ngIf="data1$ | async as data1">
```

is expanded to:

```html
<el *ngIf="data1$ | async; ngIf as data1">
```

and equivalent to:

```html
<el *ngIf="data1$ | async; let data1 = ngIf">
```

All of `as` bindings must occur in top level, and there can only be one nameless `as`, will automatically use the directive prefix as its source name.

So please don't use parentheses for `as` in any case, which could misguide you about what the syntax is.

Reference: 

+ https://github.com/angular/angular/issues/24961#issuecomment-406000798
+ https://angular.io/guide/structural-directives#grammar

**Comment by alxhub** [comment]
@trotyl is correct about the syntax, this is expected behavior.
