### ISSUE TITLE
broken references to @angular/upgrade from @angular/*/upgrade

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#32249]
https://unpkg.com/@angular/common@8.2.3/upgrade/upgrade.d.ts
has
`import { UpgradeModule } from '@angular/upgrade/static';`
but 
https://unpkg.com/@angular/common@8.2.3/package.json
doesn't include a dependency on `@angular/upgrade`

same with https://unpkg.com/@angular/router@8.2.3/upgrade/upgrade.d.ts

**Comment by gkalpak** [comment]
The problem with these sub-entry-points (`@angular/common/upgrade` and `@angular/router/upgrade`) is that they require `@angular/upgrade`, but they don't have their own `package.json` to declare that. The parent entry-points (`@angular/common` and `@angular/router`) do not depend on `@angular/upgrade` and in most cases people don't use them with `@angular/upgrade`, so it would make little sense to add `@angular/upgrade` as a required dependency of `@angular/common` and `@angular/router`.

Moving those APIs under `@angular/upgrade` (e.g. `@angular/upgrade/common` and `@angular/upgrade/router` or something) would probably make more sense, but then again we would have to define `@angular/common` and `@angular/router` as dependencies of `@angular/upgrade`, which is not necessarily the case (although I would imagine most people using `@angular/upgrade` would use `common` and `router` as well).

Ideally, `@angular/common/upgrade` and `@angular/router/upgrade` should be independent packages (with their own `package.json` and correct dependencies), but there is an overhead to having more packages and I don't know what our other concerns there might be (e.g. DX-related).

@alexeagle, would it help with bazel, if we specified `@angular/upgrade` as an optional dependency?

**Comment by alexeagle** [comment]
there's no way to express an optional dependency. The `optionalDependencies` field in package.json means "always install this dependency, but it's okay if it fails".

the problem isn't Bazel actually - you can reproduce simply by running `ngc` over the `node_modules` if you've installed `@angular/common` but not `@angular/upgrade`. `ngc` will try to generate `ngsummary.js/json` files for all the files in the packages but will fail when it encounters the `.d.ts` file with the dangling reference.

For my purposes here, an easy solution would be for `ngc` to skip over packages that are "broken" in this way.

**Comment by gkalpak** [comment]
These would be `peerDependencies`, so `optionalPeerDependencies` wouldn't cause installing and it would be the user's responsibility to install them as necessary.

I don't know enough about ngc, bazel or whatever is involved with installing dependencies and consuming `.d.ts` files, so no idea what the best solution would be 😕

**Comment by alexeagle** [comment]
optional peer dependencies sound cool, Igor has a fun post here
https://github.com/npm/npm/issues/3066#issuecomment-162287137
but it seems to not exist.

I think you can repro just by installing `@angular/common` and running `ngc -p tsconfig.json` with a tsconfig that looks like
```
{
    "compilerOptions": {
        "lib": [
            "dom",
            "es2015"
        ],
        "experimentalDecorators": true,
        "types": [],
        "module": "amd",
        "moduleResolution": "node"
    },
    "angularCompilerOptions": {
        "enableSummariesForJit": true
    },
    "include": [
        "node_modules/@angular/**/*",
```

**Comment by jelbourn** [comment]
Closing since I don't see us coming back to fix this for ngupgrade
