### ISSUE TITLE
ng new / Unexpected end of JSON input while parsing near '...e":"latest","@types/t'

### ISSUE THREAD

**Issue by WilliamKrieg** [angular/angular#32262]
Hey,

This morning after update @angular/cli I want create a new projet .
But I have this error :/

CREATE testLOL/e2e/src/app.po.ts (251 bytes)
(node:18016) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
npm ERR! Unexpected end of JSON input while parsing near '...e":"latest","@types/t'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\conta\AppData\Roaming\npm-cache\_logs\2019-08-22T09_45_21_110Z-debug.log
Package install failed, see above.

An idea ?

**Angular CLI: 8.2.2
Node: 12.9.0
OS: win32 x64
@angular-devkit/architect    0.802.2
@angular-devkit/core         8.2.2
@angular-devkit/schematics   8.2.2
@schematics/angular          8.2.2
@schematics/update           0.802.2
rxjs                         6.4.0**

**Comment by atscott** [comment]
Hi William, most likely the package got corrupted during the download. There have been similar issues submitted like [this one](https://github.com/angular/angular/issues/26997). If you're still experiencing issues, file an issue in the [angular-cli repo](https://github.com/angular/angular-cli).
