### ISSUE TITLE
NgClass provider broken in Angular 8

### ISSUE THREAD

**Issue by kyro38** [angular/angular#32264]
# 🐞 bug report

### Affected Package
 The issue is caused by package @angular/common

### Is this a regression?
Yes. Worked on Angular 7

### Description
Injecting NgClass in a component triggers an the following error : No provider for NgClassImpl

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-xlvnb3?file=src/app/app.component.ts

## 🔥 Exception or Error
```
NullInjectorError: StaticInjectorError(AppModule)[NgClass -> NgClassImpl]: 
  StaticInjectorError(Platform: core)[NgClass -> NgClassImpl]: 
    NullInjectorError: No provider for NgClassImpl!
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.2.2
Node: 10.16.3
OS: win32 x64
Angular: 8.2.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.2
@angular-devkit/build-angular     0.802.2
@angular-devkit/build-optimizer   0.802.2
@angular-devkit/build-webpack     0.802.2
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.2.2
@ngtools/webpack                  8.2.2
@schematics/angular               8.2.2
@schematics/update                0.802.2
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0
</code></pre>

**Comment by Totati** [comment]
I had a similar issue, I'm extending the ngClass dricetive. They changed the ngClass directive and now it's logic is implemented in 2 services because of Ivy, and it caused me a breaking change, cause the new constructor is accepting only one value, the service itself. 
[Here is](https://stackblitz.com/edit/angular-no-provider-for-ngclassimpl?file=src/app/app.component.ts) my fix.

**Comment by kmjbyrne** [comment]
Stuck on this for far too long. Thank you very much @Totati

**Comment by pkozlowski-opensource** [comment]
I believe that this is fixed in Angular v9
