### ISSUE TITLE
HttpClient is overly complicated and doesn't provide timeout, abort, or the underlying XMLHttpRequest 

### ISSUE THREAD

**Issue by claygifford** [angular/angular#32271]
HttpClient is overly complicated and doesn't provide timeout, or abort.
But thankfully it does return the get as an observable. (Because that's what react uses)

var longRunningCommandSubscription = 
        this.httpClient.get(url, {
            headers: this.headers(options),
            withCredentials: true,
            params: params
        });
longRunningCommandSubscription.subscribe();
longRunningCommandSubscription.unsubscribe();

I am expecting at least the option to abort the underlying request.

**Comment by santoshyadav198613** [comment]
This is where RxJs comes to help, you can combine it with any operators from RxJs.

**Comment by claygifford** [comment]
In order for you to set a timeout, you need to implement a TimeoutInterceptor

Something like this:

intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    const timeoutValue = Number(req.headers.get('timeout')) || this.defaultTimeout;
    return next.handle(req).pipe(timeoutWith(timeoutValue, throwError(new Error('Timeout has occurred'))));
  }

But again this does not stop the underlying request. So how does that help?

**Comment by Airblader** [comment]
> HttpClient is overly complicated

How so? Can you be more specific? In the simplest case all you need is `http.get("..")` — how can this be simpler?

> doesn't provide timeout

It doesn't need to, you can use rxjs to time out and this will also cancel the underlying request if supported.

> or abort

That's the same as timeout=0, simply unsubscribing achieves this.

>  Because that's what react uses

How is that at all relevant to Angular?

**Comment by claygifford** [comment]
unsubscribe does not cancel the underlying request.
