### ISSUE TITLE
Unable to get property 'get' of undefined or null reference

### ISSUE THREAD

**Issue by macwac** [angular/angular#32270]
# 🐞 bug report

### Is this a regression?
don't know at all
tested on 8.0.0 and 8.2.2
and not working

### Description
I've got Unable to get property 'get' of undefined or null reference error on IE11

## 🔥 Exception or Error
vendor.js
<pre><code>
  var TypedArrayProto_toStringTag =
      uncurryThis(
        Object.getOwnPropertyDescriptor(TypedArrayPrototype,
                                        Symbol.toStringTag).get);
}
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.2.2
Node: 12.8.0
OS: linux x64
Angular: 8.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.800.3
@angular-devkit/build-angular              0.800.3
@angular-devkit/build-optimizer            0.800.3
@angular-devkit/core                       8.2.2
@angular-devkit/schematics                 8.2.2
@angular/cli                               8.2.2
@nguniversal/express-engine                7.1.1
@nguniversal/module-map-ngfactory-loader   7.1.1
@schematics/angular                        8.2.2
@schematics/update                         0.802.2
rxjs                                       6.5.2
typescript                                 3.4.5
webpack                                    4.35.0
</code></pre>

**Anything else relevant?**
IE 11.0.9600 WIN 7

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
