### ISSUE TITLE
Error "JavaScript heap out of memory"

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular#32287]
# 🐞 bug report

### Description

I created an angular app based on ivy compiler. Also, I am using devextreme-angular which was compiled for ivy.
ng serve works fine. But when I try to build app I get the error.

## 🔬 Minimal Reproduction

 For reproduction, you can use this [project](https://github.com/ovchinnikov/dx-ivy)
and the following steps:

npm i
ng build
After it, you get the error
If I use `ng build --prod` then everything works fine

## 🔥 Exception or Error
<pre><code>
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF60F2ADD8A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF60F288886 node::MakeCallback+4534
 3: 00007FF60F289200 node_module_register+2032
 4: 00007FF60F5A30DE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF60F5A300F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF60F789804 v8::internal::Heap::MaxHeapGrowingFactor+9620
 7: 00007FF60F7807E6 v8::internal::ScavengeJob::operator=+24550
 8: 00007FF60F77EE3C v8::internal::ScavengeJob::operator=+17980
 9: 00007FF60F787B87 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF60F787C06 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF60F8B1EA7 v8::internal::Factory::NewFillerObject+55
12: 00007FF60F92F096 v8::internal::operator<<+73494
13: 000002A4F97DC5C1

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.802.2
@angular-devkit/build-angular      0.802.2
@angular-devkit/build-ng-packagr   0.802.2
@angular-devkit/build-optimizer    0.802.2
@angular-devkit/build-webpack      0.802.2
@angular-devkit/core               8.2.2
@angular-devkit/schematics         8.2.2
@angular/cli                       8.2.2
@ngtools/webpack                   8.2.2
@schematics/angular                8.2.2
@schematics/update                 0.802.2
ng-packagr                         5.5.0
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.38.0

</code></pre>

**Anything else relevant?**

**Comment by JohnnyDevNull** [comment]
use something like this as npm-script entry:

```
"build:prod": "node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng build --prod"
```

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by dxbykov** [comment]
Looks like a duplicate of [https://github.com/angular/angular-cli/issues/13734](https://github.com/angular/angular-cli/issues/13734)
