### ISSUE TITLE
Running New project shows empty screen

### ISSUE THREAD

**Issue by bobsort** [angular/angular#32284]
As your support request ticket is broken and there is no "#question" tag exist in 
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
I'll ask my question here.

# 🐞 bug report

### Affected Package
Not sure, it is not even running!

### Is this a regression?

Not sure either! because I can't download previous versions! I just downloaded a fresh copy of the angular a few moments ago

### Description
I downloaded angular a few minutes ago with 

` npm install -g @angular/cli`

Download completed successfully and version is reported as following

```
Angular CLI: 8.3.0
Node: 10.16.0
OS: win32 x64
Angular: 8.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.0
@angular-devkit/build-angular     0.803.0
@angular-devkit/build-optimizer   0.803.0
@angular-devkit/build-webpack     0.803.0
@angular-devkit/core              8.3.0
@angular-devkit/schematics        8.3.0
@angular/cli                      8.3.0
@ngtools/webpack                  8.3.0
@schematics/angular               8.3.0
@schematics/update                0.803.0
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
***
ran following commands in same order
***
ng new first --skip-git
cd first
ng build
ng serve -o
```
![run](https://user-images.githubusercontent.com/2040435/63584879-6fbc6d80-c5d0-11e9-9ac0-c7209fa8b7da.png)

And the browser screen is empty

![Web](https://user-images.githubusercontent.com/2040435/63584894-79de6c00-c5d0-11e9-8911-adfc6fa6828f.png)

view source in browser shows 

```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>First</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
<body>
  <app-root></app-root>
<script src="runtime.js" type="module"></script><script src="polyfills.js" type="module"></script><script src="styles.js" type="module"></script><script src="vendor.js" type="module"></script><script src="main.js" type="module"></script></body>
</html>
```

As  you can see 
`<app-root></app-root>`
wasn't processed.

**How to fix the issue? (screenshot attached)**

## 🔬 Minimal Reproduction
I'm planning to work on my local computer not inside a website, so I would like to make it work on my local computer too.

## 🔥 Exception or Error
No Exception, only empty page.

## 🌍  Your Environment

**Angular Version:**
`Angular CLI: 8.3.0`

**Anything else relevant?**

No, not related to browser, as page is not served correctly

It is served with angular I believe, so no, I don't think any of these matters.
Also Project folder have access permission set to everyone full access to make sure.

**Comment by Newbie012** [comment]
console log?

**Comment by vikram06** [comment]
The latest version of angular is only setup for evergreen browsers by default...

The current setup is for so-called "evergreen" browsers; the last versions of browsers that automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera), Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile. 
This also includes firefox, although not mentioned.

See here for more information on browser support along with a list of suggested polyfills for specific browsers. https://angular.io/guide/browser-support#polyfill-libs

This means that you manually have to enable the correct polyfills to get Angular working in IE11 and below.
To achieve this, go into polyfills.ts (in the src folder by default) and just uncomment the following imports:
```

/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
 import 'core-js/es6/symbol';
 import 'core-js/es6/object';
 import 'core-js/es6/function';
 import 'core-js/es6/parse-int';
 import 'core-js/es6/parse-float';
 import 'core-js/es6/number';
 import 'core-js/es6/math';
 import 'core-js/es6/string';
 import 'core-js/es6/date';
 import 'core-js/es6/array';
 import 'core-js/es6/regexp';
 import 'core-js/es6/map';
 import 'core-js/es6/set';
```
Note that the comment is literally in the file, so this is easy to find.

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by bobsort** [comment]
@vikram06: I'm not sure how this is related to polyfills, 

isn't <app-root></app-root> tag supposed to be replaced by actual content of the app folder?
and even if this not the case during debug session (serve) shouldn't it be replaced during build?
because it is not getting replaced in any of those cases.

@atscott, My apologies, but as far as I know, SO is not a support request website.

https://meta.stackoverflow.com/questions/282993/merit-of-a-flag-category-for-it-is-a-customer-support-request
