### ISSUE TITLE
Inconsitent handling of the value property in FromControl

### ISSUE THREAD

**Issue by snailcatcher** [angular/angular#32282]
# 🐞 bug report

### Affected Package
@angular/forms

### Is this a regression?
I don't know.

### Description
Inconsitent handling of the value property in FromControl. 
FormControl handels value property different, depending on the options passed in the constructor.

Regarding the Stackblitz example, I would expect the output of the red lines or the blue lines are the same.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-a9efni

## 🔥 Exception or Error
No

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.2.0
Node: 10.16.2
OS: win32 x64
Angular: 8.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0
@angular-devkit/build-angular     0.802.0
@angular-devkit/build-optimizer   0.802.0
@angular-devkit/build-webpack     0.802.0
@angular-devkit/core              8.2.0
@angular-devkit/schematics        8.2.0
@angular/cdk                      8.1.2
@angular/material                 8.1.2
@ngtools/webpack                  8.2.0
@schematics/angular               8.2.0
@schematics/update                0.802.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0
</code></pre>

**Anything else relevant?**
I don't think so.
I'm using Google Chrome 76.0.3809.100.

**Comment by Newbie012** [comment]
>Regarding the Stackblitz example, I would expect the output of the red lines or the blue lines are the same.

Well, you're asking two different values. See -https://stackblitz.com/edit/angular-gsoh4j?file=src/app/app.component.html

red text - `formControlJustValue.value` ("{ "value": "myvalue" }'")
blue text - `formControlJustValue.value.value` ("myvalue")

Not sure what's the problem here.

**Comment by snailcatcher** [comment]
> Not sure what's the problem here.

The problem is this:
```
red text -  formControlJustValue.value: '{ "value": "myvalue" }'
red text -  formControlWithOptions.value: 'myvalue'
```
Look in the 'app.component.ts'.
In my opinion, these two lines above should output the same value. 

The only difference between these two is, that 'formControlWithOptions' was initialized with the additional 'disabled' property. This should not affect how the 'value' property get processed.

**Comment by atscott** [comment]
It appears this behaves as expected. When using an object as the first argument in the constructor, the `{value: 'initialValue', disabled: true/false}` is a special case to set the disabled state as well as the value. All other objects as the first argument in the FormControl constructor are treated as the initial value (reference [here](https://github.com/angular/angular/blob/9bb5f05cb9491fea4f4b8a494d516d0f74786d53/packages/forms/src/model.ts#L1169) and [here](https://github.com/angular/angular/blob/9bb5f05cb9491fea4f4b8a494d516d0f74786d53/packages/forms/src/model.ts#L871)).
