### ISSUE TITLE
Allow *ngFor and *ngIf to coexist

### ISSUE THREAD

**Issue by PeterDavidCarter** [angular/angular#32294]
#31668 🚀 feature request

Provide a brief summary of the feature you would like to see.

I'd like *ngFor and *ngIf to co-exist on the same element without conflicting.

Use Case
Describe the use case(s) that the proposed feature would enable.

Sometimes I want to chose whether to instantiate based on one value and then iterate based on another if it is instantiated

### Relevant Package

 This feature request is for @angular/....

common

Usually imported via platform-browser

### Description
 A clear and concise description of the problem or missing capability...

It is not possible to use an *ngFor and an *ngIf on the same element. 

## Describe the solution you'd like
 If you have a solution in mind, please describe it.

I'd like *ngFor to check for the existence of an *ngIf on its element and only execute the *ngFor loop if it doesn't find one or it does and the conditional resolves to true. 

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

1: Use a display css binding to hide the fact the element is instantiated. Not useful when I want the component not to exist, not just not to be seen, for example in cases where it contains a data calculation service.
2. Introduce additional HTML or custom wrapper elements, complicating the DOM in potentially counter-intuitive ways likely to introduce style bugs, create problematic encapsulations and cause confusion for other developers. 
3. Hack through the DOM/shadow DOM in the controller, breaking separation of concerns and potentially playing havoc with life-cycle timings.

**Comment by pkozlowski-opensource** [comment]
> I'd like *ngFor and *ngIf to co-exist on the same element without conflicting.

You can use de-sugared version of *ngFor and *ngIf on `<ng-template>` to achieve this:

```html
<ng-template [ngIf]="condition">
   <div *ngFor="..."></div>
</ng-template> 
```

See https://angular.io/guide/structural-directives#the-asterisk--prefix

We are _not_ going to allow *ngFor and *ngIf as it wouldn't be clear which one should execute first.

**Comment by PeterDavidCarter** [comment]
Nice to know, thanks...

**Comment by PeterDavidCarter** [comment]
I mean: are you going to tell an attribute to fire a loop on an attribute when you've told its host element not to exist? What would the existence of the element even mean in that case?
