### ISSUE TITLE
@angular/http@next doesn't exist

### ISSUE THREAD

**Issue by felixelgato92** [angular/angular#32290]
# 🐞 bug report

### Affected Package
@angular/http

### Description
The beta version is not working. It shows as non-existing in npm 

## 🔬 Minimal Reproduction
run:
npm i @angular/http@8.0.0-beta.10
or:
npm i @angular/http@next

## Error
<pre><code>npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular/http@8.0.0-beta.10.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!    /.npm/_logs/2019-08-23T16_47_19_964Z-debug.log</code></pre>
## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 7.3.9
Node: 12.9.0
OS: darwin x64
Angular: 8.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.6
@angular-devkit/build-angular      0.800.6
@angular-devkit/build-ng-packagr   0.11.4
@angular-devkit/build-optimizer    0.800.6
@angular-devkit/build-webpack      0.800.6
@angular-devkit/core               8.0.6
@angular-devkit/schematics         7.3.9
@angular/cdk                       7.3.7
@angular/cli                       7.3.9
@angular/http                      7.2.15
@angular/language-service          7.0.4
@angular/material                  7.3.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.2.2
@schematics/angular                7.3.9
@schematics/update                 0.13.9
ng-packagr                         4.7.1
rxjs                               6.5.2
typescript                         3.5.3
webpack                            4.30.0
</code></pre>

**npm version:**
<pre><code>6.11.2</code></pre>

**node version:**
<pre><code>v12.9.0</code></pre>

**Comment by santoshyadav198613** [comment]
It was deprecated long back and removed with Angular 8, use common/http
