### ISSUE TITLE
Ability to configure silent failure for a required dependency that cannot be injected

### ISSUE THREAD

**Issue by mbilotta** [angular/angular#32300]
# 🚀 feature request

### Relevant Package

This feature request is for @angular/core

### Description
When a constructor parameter cannot be injected, the framework raises an appropriate exception unless the `Optional` decorator is used. I'd like to have a way to tell Angular to just don't instantiate any component/directive when a particular required dependency is not available. This can help implementing components/directives that are instantiated based on the presence of another ancestor component/directive. As an example, think about a directive activated by `[role="grid"]` that transforms a static table into a navigable [grid](https://www.w3.org/TR/wai-aria-practices/#grid). Inside the grid, directives bound to `tr`, `td`, `th`, would be activated by the required dependency without the need of additional attributes/classes on those elements. Other `tr`, `td`, `th` tags inside tables not marked by `[role="grid"]` would stay unaffected.

### Describe the solution you'd like
The solution I propose is to have a `Required` decorator that represents the default injector behavior plus an option to fail silently:
```typescript
@Directive({ selector: '[my-dir]' })
export class MyDirective {
  constructor(@Required({ fatal: false }) private myNonFatalDep: MyDep) { }
}
```
Of course the `fatal` option will have a default value of `true` when not specified. Also, combining this decorator with `Optional` should raise an error.

### Describe alternatives you've considered
I couldn't find any.

**Comment by Airblader** [comment]
I think it'd feel more natural if such dependencies are declared on the same level as the directive / component decorator rather than in the constructor. Something like

```
@Directive({
    requires: [
        FooService, 
        BarInjectionToken
    ],
})  
```

**Comment by mbilotta** [comment]
@Airblader Ok so this way you could require dependencies without forcibly having to inject them, right? This could also cover scenarios where the relationship is established by the ancestor component/directive via `ViewChild` or `ContentChild`. Do you agree?

**Comment by alxhub** [comment]
Can you help me understand a little bit more what you're going for?

As I understand it, you want the ability to create a directive, e.g. with a selector `[role="grid"]`, which doesn't get applied unless a particular DI token is available in the application. Is that correct?

**Comment by mbilotta** [comment]
@alxhub yes and no. Think of an ARIA grid as a regular HTML table with navigation capabilities. You can focus each cell with the mouse and move the focus in every direction using arrow keys. Currently, to implement this behavior I need to create directives for every table-related element. The `table` element will be of course distinguished by a `role` attribute set to `grid` but to have directives attached to `tbody`, `thead`, `tfoot`, `tr`, `td`, `th` I have to further specify these selectors because I don't want to affect static (non grid-like) HTML tables which won't have such role set. Also I don't want to create my own grid markup and set roles accordingly inside directives because this will limit styling possibilities.

**Comment by alxhub** [comment]
Unfortunately, we won't be able to implement this feature request. By design, Angular selectors are local and don't consider surrounding elements in a template. This leads to a simple (and performant) model for selector matching, and allows both users and tooling to easily understand which directives/components are present on a given template node.

Adding additional functionality to conditionally create directives depending on either the entire template context or the runtime environment would greatly complicate this model, and we don't think the benefits of such functionality really warrant the additional complexity.
