### ISSUE TITLE
DomElementBinder#hasNativeShadowRoot is null, not false, resulting in an NPE in...

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#3230]
Reported internally. I've hotfixed accordingly there but this needs to be fixed before the next release.

DomRenderer where the check `if (binder.hasNativeShadowRoot)` is used.

I actually see this problem across the Angular code base, where bools are not set to false, but people instead use the `isPresent()` check first. That seems very error prone.

**Comment by tbosch** [comment]
The cause if probably when text nodes are projected to a place where there is no binding...
