### ISSUE TITLE
build failed NgControlStatusGroup

### ISSUE THREAD

**Issue by aayman997** [angular/angular#32313]
Angular forms 
 The issue is caused by package @angular/.... Forms

I am trying to build my app using angular universal but I keep getting error in Angular forms without knowing the cause of the issue

`ERROR in Illegal State: referring to a type without a variable {"filePath":"D:/Easy Schools/Yep/primary/yepfront/node_modules/@angular/forms/forms.d.ts","name":"NgControlStatusGroup","members":[]}`

### Is this a regression?

 No
 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre>ERROR in Illegal State: referring to a type without a variable {"filePath":"D:/Easy Schools/Yep/primary/yepfront/node_modules/@angular/forms/forms.d.ts","name":"NgControlStatusGroup","members":[]}<code>

</code></pre>

## 🌍  Your Environment

**Angular Version:** 
<pre>8<code>

</code>
Angular CLI: 8.1.3
Node: 12.5.0
OS: win32 x64
Angular: 8.1.3
... cdk, cli, common, compiler, compiler-cli, core
... language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.801.3
@angular-devkit/build-angular              0.801.3
@angular-devkit/build-optimizer            0.801.3
@angular-devkit/build-webpack              0.801.3
@angular-devkit/core                       7.3.9
@angular-devkit/schematics                 7.3.9
@angular/animations                        8.2.3
@angular/forms                             7.2.15
@angular/http                              7.2.15
@ngtools/webpack                           8.1.3
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        7.3.9
@schematics/update                         0.801.3
rxjs                                       6.4.0
typescript                                 3.4.5
webpack                                    4.35.2
</pre>

**Anything else relevant?**

**Comment by saikumar-madana** [comment]
I am having the same issue too. Please help us solve this issue.

**Comment by mahmodkamal** [comment]
look bro this is rare to happen , but the cause of this could be one of two reasons 
first : you have form controls in html without having an initialized form group for them so you better review your forms in html .
second : but its pretty rare look if you're using any llib that uses jquery or you're using jquery in somewhere

**Comment by aguskianto** [comment]
Sorry for asking, I face the same issue. When I do ng serve, everything works fine, but when I do ng build --prod. The same issue occurs.

How to initialize a form group? Is there any sample code?

**Comment by ravishtiwari** [comment]
I am also facing the same issue. ```ng serve``` works without any issue, but, `ng build --prod fails`.

**Comment by EDHA9704** [comment]
Hola, estoy en el mismo problema, alguna solución???

**Comment by EDHA9704** [comment]
Hello, I am in the same problem, any solution please ???

**Comment by aguskianto** [comment]
Solve it, but forgot how to achieve it.

**Comment by yashar-rad** [comment]
Any updates on this?

**Comment by aayman997** [comment]
I have found that I'm using a package that isn't compatible with angular universal. so I advise you to check packages you're using in your project and be sure it's compatible with angular universal.
