### ISSUE TITLE
Components listen to event streams/emitters even when there is no listener in the template

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#3231]
Quick repo:

```dart
import 'dart:async';

@Component(
  selector: 'are-you-listening',
  events: const [
    'event'
  ]
)
@View(
  template: '{{hasListener}}'
)
class AreYouListening {
  final _eventController = new StreamController();

  Stream get event => _eventController.stream;

  bool get hasListener => _eventController.hasListener;
}
```

Expected: false, unless `(event)` is used. 

Actual: true.

**Comment by matanlurey** [comment]
Not sure who this goes to.

**Comment by mhevery** [comment]
Why is this P1? I am downgrading since this is perf optimization only.

**Comment by matanlurey** [comment]
This is important (at least P2) because you may actually want to conditionally change the UI when someone is listening to event (versus not). Does that sound reasonable?

**Comment by mhevery** [comment]
/cc @vsavkin 
@matanlurey i don't think we will support this. We think it is incorrect for a component to use presence of a listener as an input to its behavior. A component should behave same regardless if there is a  listener or not. If you want to change the way the component behaves explicit flags should be passed in regardless of presence of listeners. 

WONT_FIX / WORKING_AS_INTENDED
