### ISSUE TITLE
changedetection triggered in child component of (parent) component with OnPush ChangeDetectionStrategy

### ISSUE THREAD

**Issue by david-bulte** [angular/angular#32323]
# 🐞 bug report

### Description

I am not sure whether this is a bug, if not maybe the documentation could be expanded. 

As I wasn't entirely sure how change detection works in Angular, I did some experiments (https://github.com/david-bulte/changedetection). I understand now that when a parent component is configured with OnPush ChangeDetectionStrategy, its child components inherit that strategy (see f.e. https://github.com/angular/angular/issues/22461).

However, I noticed that when I trigger change detection in the parent component (f.e. by clicking a button), change detection also runs for the child component. Should the child component fully inherit the OnPush ChangeDetectionStrategy, this would not be the case.
  
## 🔬 Minimal Reproduction

Take a look at: https://stackblitz.com/github/david-bulte/changedetection/tree/3_parent-onpush_child-def

Click the top "Add by mutate" button (in the "parent w/ChangeDetection.OnPush" section) and you notice that change detection also runs for the child component (and even displays the updated value!). Also, clicking the "just trigger change detection" button shows that change detection also runs for the child component. 

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.1.3
Node: 10.14.1
OS: win32 x64
Angular: 8.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
</code></pre>

**Comment by trotyl** [comment]
The `ChangeDetectionStrategy` will never be inherited, each component always has its own configuration. But as `ChangeDetectionStrategy.OnPush` means `stopPropagation` if not dirty, so if a parent view doesn't perform change detection, the `ChangeDetectionStrategy` configuration of its children won't be used, that's the behavior of tree traversal.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
