### ISSUE TITLE
Dart-Transformer: Support for prefixed identifiers within directive aliases (dart)

### ISSUE THREAD

**Issue by sigmundch** [angular/angular#3232]
#3203 adds support for directive aliases, but only simple identifiers are supported:

```dart
const formDirectives = const [ Foo ]
```

It might be worth in the future adding support for referring to types with prefixes as well.

Parsing this is easy, the main complexity is that when we deal with merging of NgMeta & flattening, we need a way to normalize prefixes.

**Comment by matanlurey** [comment]
Just to be clear, does this mean if you have 

```dart
import 'form.dart' as coolio;

coolio.formDirectives // Would fail if added in a @View
```

?

**Comment by sigmundch** [comment]
good question - that would be supported, it's only if you do this:

```dart
const formDirectives = const [prefix.Foo]
```

that we don't support.

**Comment by sigmundch** [comment]
I just updated the title of the bug to a bit more precise :)
