### ISSUE TITLE
ControlValueAccessor doesn't work as expected

### ISSUE THREAD

**Issue by JoshuaKeyz** [angular/angular#32336]
# 🐞 bug report

### Affected Package
This issue is caused from the package @angular/forms

### Is this a regression?
I am not sure.

### Description
As it can be seen in the stackbliz reproduction attached to the issue, i implemented the ControlValueAccessor interface in order to create a custom form control (in this case, a counter). 
The problem arises when i want to use the callback which i saved in a variable (this.onChange) in context of the component class. It turns out that even after saving the function provided by the registerOnChange method into the onChange property, if i want to call it in the increment() or decrement() methods, it isn't defined. If i am not missing something here, it spells a bug in my dictionary. Thanks. 

## 🔬 Minimal Reproduction
Clicking on either the minus or the plus button reproduces the error
https://stackblitz.com/edit/angular-5jkoym

## 🔥 Exception or Error
<pre><code>
ERROR TypeError: this.onChange is not a function
    at TestFieldComponent.increment (VM1112 test-field.component.ts:26)
    at Object.eval [as handleEvent] (VM1118 TestFieldComponent.ngfactory.js:23)
    at handleEvent (view.ts:138)
    at callWithDebugContext (services.ts:630)
    at Object.debugHandleEvent [as handleEvent] (services.ts:377)
    at dispatchEvent (util.ts:135)
    at eval (element.ts:200)
    at HTMLButtonElement.eval (dom_renderer.ts:52)
    at ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (ng_zone.ts:262)
console.<computed> @ preview-d2335ca5bdb955611c1cb.js:1

</code></pre>

## 🌍  Your Environment
StackBliz
**Angular Version:**
<pre><code>
~7.0.2

</code></pre>

**Comment by dawidgarus** [comment]
You have error in you code:
```typescript
 providers: [{
    provide: NG_VALUE_ACCESSOR,
    useClass: forwardRef(()=> TestFieldComponent),
    multi: true
  }],
```
You should've used `useExisting` instead of `useClass`. The latter will cause to create new instance as `NG_VALUE_ACCESSOR`

**Comment by JoshuaKeyz** [comment]
@dawidgarus , thanks alot i missed that. But regardless, if you look at the {"testField": 5} monitor which i placed under the form element, you'll see that it doesn't update. Isn't it supposed to?

**Comment by dawidgarus** [comment]
```typescript
registerOnTouched(fn: any) {
    this.onChange = fn;
  }
```
on change callback is overwritten by on touched

**Comment by JoshuaKeyz** [comment]
Damn, disgraceful on my path. Thanks alot @dawidgarus I literally spent over 8 hours looking for the solution. You are a genius man, thanks.
