### ISSUE TITLE
ngOnChanges works incorrectly with async pipe

### ISSUE THREAD

**Issue by rewweRrr** [angular/angular#32335]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?

_

### Description

I have object:
```typescript
  public model = {
    field: "blabal",
    field2: [1,2]
  };
```
and use it like this:
```html
<app-component-2 
        [model] = "(model$ | async)?.field2"
>
</app-component-2>
```
where `model$`:

```typescript
 public model$ = new Subject();

  onClick() {
    this.model$.next({...this.model})
  }
```

in `app-component-2` I have `ngOnChanges`:
```typescript
 ngOnChanges(changes){
    this.i++;
    console.log(changes.model.currentValue === changes.model.previousValue);
  }
``` 

`ngOnChanges` have been called each time when i call `onClick` function. But I don't change  array `field2`.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-m7zzct

1) Click on "Just create new object only for model"
ER:  ngOnChanges shouldn't be called
AR: ngOnChanges have been called

## 🔥 Exception or Error
<pre><code>
no exceptions

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

@angular/common8.0.0
@angular/compiler8.0.0
@angular/core8.0.0
@angular/forms8.0.0
@angular/platform-browser8.0.0
@angular/platform-browser-dynamic8.0.0
@angular/router8.0.0
core-js2.6.9
rxjs6.5.2
zone.js0.9.1
</code></pre>

**Comment by trotyl** [comment]
Relates to https://github.com/angular/angular/issues/23933

**Comment by mhevery** [comment]
closing as dup
