### ISSUE TITLE
Tokens with multi: true should add to default value, not override it

### ISSUE THREAD

**Issue by waterplea** [angular/angular#32338]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
 When we define an InjectionToken we can use factory to create default value and even use `inject` function there to reach for dependencies. When we have a multi token and provide it in our app — it overrides the default array value, instead of adding to it. A small reproduction:
https://stackblitz.com/edit/angular-multi-token

### Describe the solution you'd like
 I would like it to keep original values. I have a case where DI extends base functionality by providing more items.

### Describe alternatives you've considered
 Right now I have to manually add my required items to all constructors needing it or create additional private token, even though both tokens would serve the same cause.

**Comment by Airblader** [comment]
Can you post an example that reproduces this?

**Comment by waterplea** [comment]
Sure, here's a simple example:
https://stackblitz.com/edit/angular-multi-token

**Comment by trotyl** [comment]
Technically duplicate of https://github.com/angular/angular/issues/18894, there's no cross-injector concatenation of multi token providers.

**Comment by waterplea** [comment]
Isn't it a global provider in both cases of my example?

**Comment by trotyl** [comment]
> Isn't it a global provider in both cases of my example?

Default injectors act as a different injector tree bridged to existing injector tree, similar to the relationship between module injector tree and node injector tree. If a token cannot be found in current module injector but available at the bridged default providers injector, then default provider will be used as fallback.

**Comment by waterplea** [comment]
I see, thank you for the explanation, closing as a duplicate.
