### ISSUE TITLE
Drop upper limit for Typescript peerDependecy

### ISSUE THREAD

**Issue by Akxe** [angular/angular#32343]
# 🐞 bug report

### Affected Package

@angular/cli

### Is this a regression?

Somewhat

### Description

Typescript version is locked within range.

## 🔬 Minimal Reproduction

Not needed

## 🔥 Exception or Error
Angular asks for Typescript to be peerDependency within a certain range. I would expect it to not be that case as when upgrading from 7.x I was forced to downgrade Typescript from 3.5.x.

I suppose there need to be some minimal version required, but I don't see any reason why prevent developers from using newer version if they op into it. I would understand a note about "incorrect" version at most.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.1
Node: 12.4.0
OS: win32 x64
Angular: 8.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.1
@angular-devkit/build-angular     0.801.1
@angular-devkit/build-optimizer   0.801.1
@angular-devkit/build-webpack     0.801.1
@angular-devkit/core              8.1.1
@angular-devkit/schematics        8.1.1
@ngtools/webpack                  8.1.1
@schematics/angular               8.1.1
@schematics/update                0.801.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2</code></pre>

**Anything else relevant?**
https://github.com/angular/angular/issues/31059

**Comment by Airblader** [comment]
I don't understand — if you have a too high version, it might not be compatible. TypeSxript does have breaking changes.

**Comment by Akxe** [comment]
The problem is that the `ng build` will halt with error saying that the version of typescript must be 3.4.x

**Comment by trotyl** [comment]
> The problem is that the `ng build` will halt with error saying that the version of typescript must be 3.4.x

Then it should be a request to change that to warning, in any case this should be requested to [Angular CLI](https://github.com/angular/angular-cli). Official support for newer version of TypeScript will always take time, which won't be changed.

**Comment by alan-agius4** [comment]
@Akxe, you can opt to use unsupported TypeScript versions by using the `disableTypescriptVersionCheck` compiler option.

See: https://angular.io/guide/angular-compiler-options#disabletypescriptversioncheck

**Comment by Akxe** [comment]
Awesome, I suppose we can then close this
