### ISSUE TITLE
docs(dgeni): Provide a way to document and x-link to vars, functions, types

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#3235]
Currently, we are only able to use `{@link Foo}` to cross-link to documentation for classes. It would be useful to be able to also link back to vars (including const), functions, and types.

For example, we'd like to define `{@link Type}`, for the type exported in [line 6 of lang.ts](https://github.com/angular/angular/blob/83e99fc72d5f6aa80f044bcf54f8679b2370dab7/modules/angular2/src/facade/lang.ts#L6) and provide documentation that can be linked to.

This should be possible, but I think it's not currently implemented.

**Comment by petebacondarwin** [comment]
First thing I note is that `Type` is not a publicly exported "thing" so it would not appear in the angular.io docs in any case. I will look into whether it is possible to link to other non-class things.

**Comment by petebacondarwin** [comment]
OK, so this does work for `var` docs such as `httpInjectables`, which is not a class. So the following would work in the docs:

```
{@link httpInjectables}
```

**Comment by petebacondarwin** [comment]
Here is a list of all the docs that are currently available to link to when you run `gulp docs/angular.io`.

https://gist.github.com/petebacondarwin/de0095a8ec779f742a54

In this gist, there is an item for each doc, specifying its `id` and `docType`. You can see that there are plenty of docs that have docType different to `class`. The `angular2/http/httpInjectables` doc has `var` docType. Remember that the `id` is the most specific and unique identifier for the doc. Each doc will also have a list of `aliases` that can be used in links. For example the `angular2/http/httpInjectables` also has an alias of `httpInjectables`.

**Comment by petebacondarwin** [comment]
I think that this deals with this issue @naomiblack.

**Comment by naomiblack** [comment]
I am still confused about linking to {@link Type} which does not work, but @mhevery keeps adding back into the compiler API docs as something that he wants to link to. How should Type be documented?

**Comment by petebacondarwin** [comment]
The thing about `Type` is that it is not exported from any of the public modules, so it does not appear in the docs
In order to be able to link to it, it needs to exist in the docs. For it to exist in the docs, it must be exported from, say `angular2/angular2` modules
