### ISSUE TITLE
AoTCompiler collects ng module even not being imported in my project

### ISSUE THREAD

**Issue by e-cloud** [angular/angular#32366]
# 🐞 bug report

### Affected Package

@angular/compiler

### Is this a regression?

I'm afraid not

### Description

1. I need to use a 3rd party angular library -- `moduleA`
    * it has components `compA`, `compB`, `compC`
    * `compB` is used inside `compA`
    * it exports all its components
2. for my probject, i need to use `compA`.
3. however, some behavior of compB is not what I desired.
4. Only thing I need is to inject a directive to `compB` to slightly modify its behavior.
5. I make a custom ng module `customModuleA` to declare those components again
    * put that directive in declaration also to allow recognition by compiler
    * drop the use of origin module `moduleA`
    * same way I did in the demo repo below.
6. JIT mode works well. AoT mode build with error.

It turns out angular aot compiler blindly collects every things in typescript declaration.
see https://github.com/angular/angular/blob/7.2.x/packages/compiler/src/aot/compiler.ts#L886. 

**Even for a ng module not being imported in the whole application.**

## 🔬 Minimal Reproduction

https://github.com/e-cloud/demo-repo-for-various-issues/tree/angular-aot-problem2

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/5255354/63838339-bda9ea80-c9af-11e9-8741-a3545f60741a.png)

<pre><code>
$ ng build -c production

Date: 2019-08-28T08:19:39.695Z
Hash: 3fbda6158fa9cff2234e
Time: 5034ms
chunk {0} runtime.26209474bfa8dc87a77c.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} es2015-polyfills.bda95d5896422d031328.js (es2015-polyfills) 56.6 kB [initial] [rendered]
chunk {2} main.fa4681da67b0e16d34dc.js (main) 128 bytes [initial] [rendered]
chunk {3} polyfills.41559ea504b9f00b6dea.js (polyfills) 130 bytes [initial] [rendered]
chunk {4} styles.3ff695c00d717f2d2a11.css (styles) 0 bytes [initial] [rendered]

ERROR in : Type CompAComponent in C:/Users/SHe/github/demo-repo-for-various-issues/src/app/lib-a/comp-a/comp-a.component.ts is part of the declarations of 2 modules: CustomLibAModule in C:/Users/SHe/github/demo-repo-for-various-issues/src/app/custom-lib-a.module.ts and LibAModule in C:/Users/SHe/github/demo-repo-for-various-issues/src/app/lib-a/lib-a.module.ts! Please consider moving CompAComponent in C:/Users/SHe/github/demo-repo-for-various-issues/src/app/lib-a/comp-a/comp-a.component.ts to a higher module that imports CustomLibAModule in C:/Users/SHe/github/demo-repo-for-various-issues/src/app/custom-lib-a.module.ts and LibAModule in C:/Users/SHe/github/demo-repo-for-various-issues/src/app/lib-a/lib-a.module.ts. You can also create a new NgModule that exports and includes CompAComponent in C:/Users/SHe/github/demo-repo-for-various-issues/src/app/lib-a/comp-a/comp-a.component.ts then import that NgModule in CustomLibAModule in C:/Users/SHe/github/demo-repo-for-various-issues/src/app/custom-lib-a.module.ts and LibAModule in C:/Users/SHe/github/demo-repo-for-various-issues/src/app/lib-a/lib-a.module.ts

</code></pre>

## 🌍  Your Environment

**Angular Version:** (demo project is newly generated by angular-cli)
<pre><code>

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.9
Node: 10.14.2
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**

**Comment by trotyl** [comment]
Relates to https://github.com/angular/angular/issues/10646, https://github.com/angular/angular/issues/13590

**Comment by alxhub** [comment]
Yes. This is working as intended for the compiler - it processes every class in its inputs, even those which aren't actually referenced from your `AppModule`.
