### ISSUE TITLE
transition  :leave does not work in EDGE/IE/Firefox

### ISSUE THREAD

**Issue by mtsaryk** [angular/angular#32373]
# 🐞 bug report

### Description

Transition  :leave with *ngIf does not work in EDGE/IE/Firefox as expected. 
It happens if we change the width of the borders. And after :leave transition DOM still present. Then after *ngIf="true" again - we have a duplicated DOM.

## 🔬 Minimal Reproduction
https://angular-issue-repro2-yffvfh.stackblitz.io

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.3
Node: 10.16.0
OS: win32 x64
Angular: 8.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              8.0.3
@angular-devkit/schematics        8.0.3
@angular/cdk                      8.0.1
@angular/cli                      8.0.3
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

## Browsers

Works in:
✔Chrome
✔Opera
✔Safari (mobile)

Does not work in:
❌IE
❌EDGE
❌Firefox

**Comment by mhevery** [comment]
1) please provide link to the source (not running app) of stackblitz.
2) This seems like an issue with browser not with angular since angular does not have any browser special logic.
