### ISSUE TITLE
Feature Request: a ngBreak to break through FOR loops.

### ISSUE THREAD

**Issue by nickykapur** [angular/angular#32399]
# 🚀 ngBreak

### Description
 ngFor loops with the feature of let item of items, goes through all the array. 
(If array has 1000 elements it would go through all the elements of the array).

### Describe the solution you'd like
 Someone to engineer a way to add the break elements into loops like for, switch.
With this solution the array would break if a condition is met for example:
for let item of items
if(item.value == 5){ break;}
endfor

### Describe alternatives you've considered
 using a let i = index, and when reaches to a certain point as i < 10, stop the loop. but not the most efficient way.
This makes it not dynamic

**Comment by Airblader** [comment]
You should just slice your array on the controller side first.

**Comment by santoshyadav198613** [comment]
I don't think this should be handled by ngFor as @Airblader already suggested do it as controller side. and what is the use case?

**Comment by nickykapur** [comment]
I did it in the controller side, it took some effort, but best way to deal with it.
