### ISSUE TITLE
Routing b/w components as last component shouldn't show current component show be on screen.

### ISSUE THREAD

**Issue by AXWELL911** [angular/angular#32409]
pls reply on same..........

**Comment by santoshyadav198613** [comment]
Can you please describe in detail what you want, also a reproduction would be good to check this issue.

**Comment by AXWELL911** [comment]
Actually i have two components, In one component i have one button and i want to navigate to other component, and when i click on that button previous component shouldn't be shown and page would go to on second component. That's it.

**Comment by AXWELL911** [comment]
> Actually i have two components, In one component i have one button and i want to navigate to other component, and when i click on that button previous component shouldn't be shown and page would go to on second component. That's it.

**Comment by AXWELL911** [comment]
Actually i have two components, In one component i have one button and i want to navigate to other component, and when i click on that button previous component shouldn't be shown and page would go to on second component. That's it.

**Comment by santoshyadav198613** [comment]
Looks like not a bug please raise it on StackOverFlow with Angular tag,

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular` as @santoshyadav198613 proposed.

More information on why we don't resolve support issues via the issue tracker can be found [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
