### ISSUE TITLE
HttpClient doesn't "use" api-calls already preloaded with link[rel=preload]

### ISSUE THREAD

**Issue by filipbech** [angular/angular#32411]
# 🐞 bug report

### Affected Package
HttpClient

### Is this a regression?
Not sure if it ever worked

### Description
HttpClient makes a new request instead of reusing the request that has been preloaded by link[rel=preload]. 

## 🔬 Minimal Reproduction
In index.html insert a link[rel=preload] tag to preload an api-call (using [as=fetch]) that angular will make later. 
From angular, make the same api-call with HttpClient (maybe with a timeout so you can see it preload first). Watch in the network tab as the request goes out again when httpclient does its thing. 
It works as expected if you use fetch() or xhr directly, but somehow not with HttpClient (looks like it makes another type of request)

https://stackblitz.com/edit/angular-preload-api?file=src%2Fapp%2Fapp.component.ts

Comment in/out the httpClient and the fetch implementation to see how it "should" work...

## 🔥 Exception or Error
No error, it just does the request again, instead of using the one that was preloaded.

## 🌍  Your Environment

Beware only webkit/chromium supports link[rel=preload] as of this bug.

**Angular Version:**
<pre><code>
@angular-devkit/architect          0.801.3
@angular-devkit/build-angular      0.801.3
@angular-devkit/build-optimizer    0.801.3
@angular-devkit/build-webpack      0.801.3
@angular-devkit/core               8.1.3
@angular-devkit/schematics         8.1.3
@angular/cdk                       8.1.2
@angular/http                      7.2.14
@angular/material                  8.1.2
@angular/material-moment-adapter   8.1.2
@ngtools/webpack                   8.1.3
@schematics/angular                8.1.3
@schematics/update                 0.801.3
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.35.2
</code></pre>

**Comment by alxhub** [comment]
This is the default behavior of browsers. `XMLHttpRequest` will always create a new request (which might read from the browser cache) and does not specifically take `<link rel="preload">` into consideration.

**Comment by filipbech** [comment]
No, making my own XMLHttpRequest also works as expected. 
I updated my demo to also include that as an example. 

See difference in attached screenshots:
![screenshots](https://user-images.githubusercontent.com/1720790/64403884-78a24a00-d07a-11e9-8d36-b0d406547da7.jpeg)

**Comment by filipbech** [comment]
Ok, so it comes down to the headers that HttpClient sends. The link[rel=preload] has a very limited set of options for headers, that aren't really compatible with what HttpClient adds by default. (How can I remove the Accept header?)
