### ISSUE TITLE
Angular 4.2 not overriding Authorization header for basic authentication

### ISSUE THREAD

**Issue by akinfo06** [angular/angular#32412]
My Web API 2.-0 code is -
OnValidateClientAuthentication = async context =>
{
.......string clientId;
........string clientSecret;
........if (context.TryGetBasicCredentials(out clientId, out clientSecret))
........{
..................if (clientId == "client1" && clientSecret == "secretKey1")
................{
....................context.Validated();
 ................}
...........}
}

I am using Bearer Authentication here.
Now I am calling this from angular-

tried two approaches -
approach 1. in module configure -

app.config(['$httpProvider', function ($httpProvider) {
.........$httpProvider.defaults.headers.common['Authorization'] = 'Basic ' + window.btoa("Client1:secretKey1");      
}

approach  2. 
app.service('memberService', function ($http) {
    var headers = { 'Access-Control-Allow-Origin': true, 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'Authorization':'Basic ' + window.btoa("Client1:secretKey1") }
    this.GetTocken = function (data) {
       
        var response = $http({
            method: "Post",
            url: window.g_baseUrl + "accesstoken",
            headers: headers
        });
        return response;
    };
}

I tried with Angular 1.1.x, to 1.5.x with no luck. 
Google is telling that HttpClient class is totally. dumb 
after setting Authorization header, two keys : access-control-request-method & access-control-request-headers are increasing but no key with the name of 'Authorization'.
while sending request from postman its adding Authorization key in request header. 
can someone help with angular sample code with version ...

**Comment by spock123** [comment]
Hi @akinfo06 , this is not the repo for AngularJS (https://github.com/angular/angular.js/)

I think you should post your issue there.

**Comment by akinfo06** [comment]
> Hi @akinfo06 , this is not the repo for AngularJS (https://github.com/angular/angular.js/)
> 
> I think you should post your issue there.

thanks bro...
