### ISSUE TITLE
Is there an option to Interrupt (stop) the component life cycle

### ISSUE THREAD

**Issue by HemendPatel63** [angular/angular#32419]
I’m working on RBAC implementation in my angular app. I want to interrupt (stop) the component lifecycle and the rendering of the component template (and child components / templates). If user doesn’t entitle.
I have created directive to manage the UI behavior but want to stop the .ts code execution too.
Do angular have any option or can I restrict or override child  component lifecycle from parent component?

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
