### ISSUE TITLE
Upgrade Angular 9, getting error ERROR in Value at position 1 in the NgModule.imports of AccordionModule is not a reference: [object Object]

### ISSUE THREAD

**Issue by sumitdeyonline** [angular/angular#32422]
After upgrade to Angular 9, getting following error while building the application, In Angular 8, it is working perfectly. 

ERROR in Value at position 1 in the NgModule.imports of AccordionModule is not a reference: [object Object]

**Comment by spock123** [comment]
Sorry to meddle.. I had this error because one of my files had .js extension... Check if that's the case with you. Ivy is more picky/correct

**Comment by sumitdeyonline** [comment]
Thank you Lars. What files could .js extension, my source files or package
file?

**Comment by spock123** [comment]
@sumitdeyonline sorry for the delay.. it was in my source code, one of my barrel index files was accidentally given .js extension, but somehow angular/webpack accepted it. Ivy didn't.

So check your source files for extensions, could be the issue (although it could be tons of other things I imagine).. best of luck

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by vaztimur** [comment]
the error is caused by the package.json entry "ngx-bootstrap": old version
change it to the current version of 5.1.2 and it should disappear. Hope i could help you
