### ISSUE TITLE
Shrink generated change detector code size

### ISSUE THREAD

**Issue by kegluneq** [angular/angular#3242]
The `dart2js` build step for apps with large numbers of components (>500) is running out of memory.

Abstracting duplicated and boilerplate code out of generated change detectors and into utilities and/or `AbstractChangeDetector` will give `dart2js` less code to process and should help with memory pressure.

**Comment by matanlurey** [comment]
Tim is this for *creating* the change detectors, or using them? Just to be clear.

**Comment by kegluneq** [comment]
We are trying to generate less code for each change detector while not significantly affecting execution speed.

**Comment by kegluneq** [comment]
Closing since this is better covered by the other issues in the `CD size` hotlist
