### ISSUE TITLE
mat-table + ivy + elements + serve + scss = error

### ISSUE THREAD

**Issue by flash-me** [angular/angular#32426]
I'll sum it up:
- I have an angular element (AppComponent).
- I have 'enableIvy' = true & aot = true
- I use SCSS in seperate files
- I do have a valid setup. So far this only happens with **mat-table**
- I don't use third party builders. Standard ng serve
- **Only reload with dev-server breaks**, build etc. are fine
- Any change in SCSS files that are included in compilation will cause error
- _**(!)(!)No caching problem. This also happens with build --watch, the created bundles are corrupt(!)(!)**_ You have to restart the build / serve task completely.

So far the workarounds are (one Of):
- Inline SCSS changes do not cause break
- Disable aot for ng serve
- Disable ivy for ng serve 

#### Reproduction
Github Repo: https://github.com/kqadem/ivy-test

Steps to reproduce:
1. npm start
2. change sth in src/app/app.component.scss, linebreak is enough
3. refresh browser 
 
#### Expected Behavior
I was expection the usual behaviour --> Run without any issues

#### Actual Behavior
Error at bootstrap / startup / Initializing with following error:
![image](https://user-images.githubusercontent.com/5240450/63797906-4883da00-c909-11e9-9c10-4d90ea23a589.png)

#### Environment

- Angular: 8.2.0 (error still happens with 9-next)
- CDK/Material: 8.1.4
- Browser(s): Chrome 76
- Operating System (e.g. Windows, macOS, Ubuntu): So far tested on Windows 7 and Ubuntu 19.04

**Comment by JoostK** [comment]
I'm hoping that #33522 will resolve this issue, I'll test your repro with my PR to confirm over the weekend.

**Comment by JoostK** [comment]
While it was indeed failing as you describe with 8.2.13. I have tested this with 9.0.0-rc.0 and are no longer able to reproduce.

Please upgrade using

```
ng update @angular/cli @angular/core --next --force
```
