### ISSUE TITLE
StaticInjectorError(Platform: core)[RouterScroller -> ViewportScroller]

### ISSUE THREAD

**Issue by dcolakchile** [angular/angular#32423]
It's a starter app, practically empty, just upgraded angular and now have this error:

null: NullInjectorError: StaticInjectorError(AppModule)[RouterScroller -> ViewportScroller]:

stack:"NullInjectorError: StaticInjectorError(AppModule)[RouterScroller -> ViewportScroller]: \n  StaticInjectorError(Platform: core)[RouterScroller -> ViewportScroller]: \n    NullInjectorError: No provider for ViewportScroller!\n    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (http://localhost:4200/vendor.js:67531:25)\n    at resolveToken (http://localhost:4200/vendor.js:78723:24)\n    at tryResolveToken (http://localhost:4200/vendor.js:78667:16)\n    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (http://localhost:4200/vendor.js:78569:20)\n    at resolveToken (http://localhost:4200/vendor.js:78723:24)\n    at tryResolveToken (http://localhost:4200/vendor.js:78667:16)\n    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (http://localhost:4200/vendor.js:78569:20)\n    at resolveNgModuleDep (http://localhost:4200/vendor.js:87039:29)\n    at _callFactory (http://localhost:4200/vendor.js:87107:67)\n    at _createProvid...

**You guys know we live in constant fear of updating angular???** 

**Stop breaking projects with each new version of angular!!!**

Routing is of course, not working!

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
