### ISSUE TITLE
No documentation for Bazel Starlark rules

### ISSUE THREAD

**Issue by pauldraper** [angular/angular#32439]
# 📚 Docs or angular.io bug report

## Description

Angular continues (#29623)  its bid for web framework with the worst documented build process, by having no documentation for the rather important `ng_module`.

## Workaround

Read the source code: https://github.com/angular/angular/blob/master/packages/bazel/src/ng_module.bzl

**Comment by Toxicable** [comment]
There should probably be some links to get here but here's the rules_nodejs docs: https://bazelbuild.github.io/rules_nodejs/ - rules_nodejs is the base for ng_module
Then there's Angualar specific ones here: https://angular.github.io/bazel-builds/

I understand that the docs there are really just api coverage and not full guides. So there's some good examples here aswell: https://github.com/bazelbuild/rules_nodejs/tree/master/examples

**Comment by pauldraper** [comment]
Ah, https://angular.github.io/bazel-builds/ is exactly what I was looking for.

But I had been looking for it on angular.io/docs.
