### ISSUE TITLE
same component multi times in page

### ISSUE THREAD

**Issue by MujahedSaleem** [angular/angular#32435]
when create a component and use it twice 
once in component 
second in  enteryComponent 
 when do action in enteryComponent the action in copomonent is fired 
![image](https://user-images.githubusercontent.com/16061878/64076084-d1fc2900-ccc8-11e9-9095-6f25e9130e0e.png)
when click on entery component action i component is fired
![image](https://user-images.githubusercontent.com/16061878/64076112-1687c480-ccc9-11e9-9fb6-ca058aff2f43.png)

**Comment by santoshyadav198613** [comment]
Can you explain what you are trying to achieve and what is the error.

**Comment by MujahedSaleem** [comment]
@santoshyadav198613 
i was create file uploder 
what i want to achieve is to use my uploder in my project 
the error is when i put my uploder inside component (in red) and put it in enteryComponent(popup) in blue 
when click on  fileUploder in entery component(popup) the action associated with component(in red) is fired.

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
