### ISSUE TITLE
APP_INITIALIZER functions differently in unit tests vs normal build, not waiting for promise

### ISSUE THREAD

**Issue by ChristopherKiss** [angular/angular#32441]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
@angular/core

### Is this a regression?
Not that I'm aware of

### Description
When you bootstrap your app using an async app initializer, the app will wait until the promise resolves before finishing the bootstrap process. However, when in unit tests, async app initializers are not awaited.

## 🔬 Minimal Reproduction

https://github.com/ChristopherKiss/angular-app-initializer

You can see the output from my repo here:
![image](https://user-images.githubusercontent.com/24984762/64088797-81e39c00-cd86-11e9-93d2-f20b54d1fd54.png)

## 🔥 Exception or Error
N/A

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.3
Node: 12.9.1
OS: win32 x64
Angular: 8.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.801.3
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.801.3
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.1.3
@ngtools/webpack                  8.1.3
@schematics/angular               8.1.3
@schematics/update                0.801.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Anything else relevant?**
Comparing the bootstrap process, we can see the promise is waited to resolve.

https://github.com/angular/angular/blob/1537791f06df5d85dd27e763836fd99bb1530991/packages/core/src/application_ref.ts#L282-L286

However, in unit tests, it is not waited for.

https://github.com/angular/angular/blob/1537791f06df5d85dd27e763836fd99bb1530991/packages/core/testing/src/test_bed.ts#L380

In the testbed, the initIfNeeded function is called from inject, execute or createComponent function.

We see that initializers are run inside this function:
https://github.com/angular/angular/blob/1537791f06df5d85dd27e763836fd99bb1530991/packages/core/testing/src/test_bed.ts#L415-L416

But never waited to resolve first before continuing.

Finally, the documentation is quite slim in this area:
https://angular.io/api/core/APP_INITIALIZER
https://angular.io/guide/dependency-injection-providers#predefined-tokens-and-multiple-providers

What order do multi initializers run in?
Do they run in parallel or do they wait for each other?

**Comment by mhevery** [comment]
This works as intended, since we want the unit tests to be easy to write we assume that code is already compiled hence we don't wait on the promise.

**Comment by ChristopherKiss** [comment]
@mhevery,

Sorry, I don't understand, what does compiling have to do with async app initializers? The async app initializers lets us run async code before the app is bootstrapped.

This difference between functionality for unit tests and actual runtime is not documented anywhere, nor is there a way to possible wait for this in unit tests either, so we are left with async app initializers not being possible to be used in unit tests, when they are indeed valid at runtime in a normal app.

Can you provide additional details on why you think this is intended and how we can make this work in unit tests?
