### ISSUE TITLE
Angularjs timepicker for angular 6

### ISSUE THREAD

**Issue by pratikpatel62** [angular/angular#32443]
i need to use angularjs timepicker or like that in angular 6 application, so is there any feature for exact features like angularjs timepicker, not material. bootstrap and other

**Comment by santoshyadav198613** [comment]
Please raise this on stackoverflow, if you are facing any issues with framework you can raise here.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
