### ISSUE TITLE
Lazy loading not working with module commonjs in angular 8

### ISSUE THREAD

**Issue by Avcajaraville** [angular/angular#32444]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

My setup was working correctly in angular7. This issue is happening after upgrading to angular8 and the new syntax for lazy loading.

### Description

I'm doing SSR with angular and just upgraded to angular8.

My tsconfig looks like:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "downlevelIteration": true,
    "paths": {
      "@app/*": [ "src/app/*" ],
      "@server/*": [ "server/*" ],
      "@shared/*": [ "shared/*" ]
    },
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "commonjs",
    "esModuleInterop": true,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es6",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}
```

I understand I need to change module and target, but right now, I need to have module as commonjs, or else, my server-side code won't run.

Everything is compiling good, but all my modules are compiled inside the main.js and not lazy-loaded.

## 🌍  Your Environment

**Angular Version:**
<pre>8.2.4<code>

**Comment by ponkys** [comment]
> Everything is compiling good, but all my modules are compiled inside the main.js and not lazy-loaded.

In serverside you don't need to separate lazy-loaded modules in another file. You do it on client-side to save users data and avoid serving useless files if they aren't needed. However, in the server, it's faster if you have all compiled into one file. As long as it is compiling, that's how it is supposed to work.

**Comment by Avcajaraville** [comment]
I was pointing out the ssr architecture as reference, but I mean the bundles are not splitted when serving for the client.

I dont get lazy load on my client bundles. Sorry for the confusion.

**Comment by ponkys** [comment]
got it. Try this: add `"module": "commonjs",` only to your tsconfig.server.json. In your   tsconfig.json leave "module": "esnext"

**Comment by Avcajaraville** [comment]
This solved my problem! Thanks a lot, didn't consider this approach ;)
