### ISSUE TITLE
Move callOnAllChangesDone to super and override only when necessary

### ISSUE THREAD

**Issue by mhevery** [angular/angular#3244]
For most of the CDs we generate:

```Dart
  void callOnAllChangesDone() {
    _dispatcher.notifyOnAllChangesDone();
  }
```

But this is not usually needed. Only when a directive implement `OnAllChangesDone` which is relatively rare. 

- [ ] Move the code to superclass.
- [ ] Override the method only if we need to create a behavior different than shown.

Example:

```Dart
  void callOnAllChangesDone() {
    super.callOnAllChangesDone();
    somedirective.onAllChangesDone();
  }
```

**Comment by vsavkin** [comment]
Merged via https://github.com/angular/angular/commit/adc27398fddd29fe6eab1c417a61c1cb5c7c588b
