### ISSUE TITLE
@angular/http: typescript truncates last digits of int64 / number

### ISSUE THREAD

**Issue by cgebe** [angular/angular#32456]
# 🐞 bug report

### Affected Package

"@angular/http": "^7.2.15"

### Is this a regression?

No

### Description

Using angular/http, Typescript truncates the last digits of a int64 type retrieved via HTTP, due to number being a floating point number type. Using the new `bigint` data type https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html#bigint yields the same result in my testings. Is there a possibility to handle int64 without truncation by the `number` type through angular http?

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-at161u

## 🔥 Exception or Error

-

## 🌍  Your Environment

```
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.6
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              0.8.6
@angular-devkit/schematics        0.8.6
@angular/cdk                      8.1.4
@angular/cli                      6.2.6
@angular/flex-layout              8.0.0-beta.27
@angular/http                     7.2.15
@angular/material                 8.1.4
@ngtools/webpack                  7.0.7
@schematics/angular               0.8.6
@schematics/update                0.8.6
rxjs                              6.5.2
typescript                        3.5.1
webpack                           4.19.1
```

**Anything else relevant?**

-

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
