### ISSUE TITLE
Incorrect warning on angular language service

### ISSUE THREAD

**Issue by jpike88** [angular/angular#32451]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/language-service

### Description

```Component 'exampleComponent' is not included in a module and will not be available inside a template. Consider adding it to a NgModule declaration.```

This issue fires up when a component class is exported using ```export default```. A warning should be present, as I went down a rabbit hole trying to figure out why that error was firing.

The error goes away when all components are exported normally, and not using the ```default``` syntax.

Angular Language Service Version: 9.0.0-next.4

**Comment by kyliau** [comment]
This is no longer an error, fixed in https://github.com/angular/angular/pull/34115
