### ISSUE TITLE
PWA language /en subfolder problem with english version of page reload ( i18n --aot language version build in /en subfolder)

### ISSUE THREAD

**Issue by dalibor-sanzeru** [angular/angular#32452]
Hi,
I cannot reload english /en version of in PWA application.

Based on i18n angular documentation, reload is needed to --aot build i18n application ->need new build for each language - done.
I need to combine 'refresh translated application from subfolder' with PWA application (If this even feasibile solution).

I have 2 applications builded in 2 folders:
ROOT
ROOT/EN

I see in console log following error when i click to language switcher for EN version:  Cannot match any routes. -> I was expecting to reload application from subfolder.
 
Use case:
1. User loads root page: https://www.sanzeru.sk
2. User clicks to english version https://www.sanzeru.sk/en
3. Expected: Provided link triggers english-builded application reload of application from /en folder.
4. Current: Application is not loaded from en subfolder. 

If i check Update on reload + Bypass network in chrome dev tools its working as expected - before PWA integration was done.

Thanks for advice...

**Comment by dalibor-sanzeru** [comment]
Ok I have found solution working for me:
https://angular.io/guide/service-worker-config#matching-navigation-request-urls

You can disable cache for specific url, for me add this into application hosted in root was working:

...
 "index": "/index.html",
  **"navigationUrls": [
    "!/en"
  ],**
  "assetGroups": [
...

**Comment by gkalpak** [comment]
It is not clear from your description exactly what the problem was, but, since you found a way to make it work for you, I am going to close this issue.

**Comment by dalibor-sanzeru** [comment]
Thanks, comment updated to clarify it more.
