### ISSUE TITLE
Fix Back Button - Load the last state of the component when back button is clicked, just like a normal web page.

### ISSUE THREAD

**Issue by ArunEdathadan** [angular/angular#32455]
### Description
When we go forward, the state and position of the last component is reset every time. this is making too much trouble making the back button work.

### I would like having
Create a new parameter to cache or not cache the previous page. we only need this for a very few pages like search page etc. Too much time is lost figuring this out. if the back button worked just normally like any other normal webpage. that is very useful.

### Alternatives
popup and the new window is currently used. but does not serve the purpose efficiently.

**Comment by Alex-Torres** [comment]
Respectfully, I don't think this is an issue.  There are tons of things that you can do get the back button navigation you need, kindly look over the Angular Router ([Angular Docs](https://angular.io/api/router/Router)).  If not, I would recommend that you post a "how to question" on [StackOverFlow](https://stackoverflow.com/questions/tagged/angular).

**Comment by Alex-Torres** [comment]
Hope this simple example on StackBlitz helps: https://stackblitz.com/edit/alex-routing-example

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
