### ISSUE TITLE
Using @SkipSelf and @Host should throw an error in the Hierarchical Injectors example.

### ISSUE THREAD

**Issue by ukyo** [angular/angular#32461]
# 📚 Docs or angular.io bug report

### Description

In https://angular.jp/guide/hierarchical-dependency-injection#host-and-viewproviders section.

> @SkipSelf(), causes the injector to start its search for the AnimalService at the <app-root>, not the <app-child>, where the request originates, and @Host() stops the search at the <app-root> <#VIEW>. Since AnimalService is provided via the viewProviders array, the injector finds 🐶 (puppy) in the <#VIEW>.

I tried this in the [live example](https://stackblitz.com/angular/nngdvaobbve?file=src%2Fapp%2Fchild%2Fchild.component.ts), but it thrown an error.

```
Error: Template parse errors:
No provider for AnimalService ("

<h2>From ChildComponent:</h2>
[ERROR ->]<app-child><app-inspector></app-inspector></app-child>


"): ng:///AppModule/AppComponent.html@8:0
```

### What's the affected URL?**
 https://angular.jp/guide/hierarchical-dependency-injection#host-and-viewproviders

## 📷Screenshot

<img width="1225" alt="スクリーンショット 2019-09-04 4 22 50" src="https://user-images.githubusercontent.com/373554/64202843-135d2600-cecd-11e9-9eb1-1109ce256eb3.png">

**Comment by kapunahelewong** [comment]
Hi @ukyo! Thank you so very much for taking the time to file this issue. This was a recent rewrite and as it gets very detailed, I had unintentionally left out the code for adding the `viewProviders` to the `AppComponent` and you found it! I've added notes in the `app.component.ts` as well as instructions in the guide. If you would like to review my PR, I'd be very grateful as you clearly have a very good eye! 

Here's the latest preview with the corrections in case you need this info right away: https://pr32501-4f0c199.ngbuilds.io/guide/hierarchical-dependency-injection#host-and-viewproviders

And the PR:
https://github.com/angular/angular/pull/32501
