### ISSUE TITLE
Use angular language service standalone in CI

### ISSUE THREAD

**Issue by jpike88** [angular/angular#32467]
Currently, the only way I can seem to use the angular language service is by installing an extension for VSCode.

However, it raises errors in my templates that are useful, and would be useful in running when doing CI testing.

However, the closest thing I can find is codelyzer, which doesn't support the below error.

![Screen Shot 2019-09-04 at 3 14 07 pm](https://user-images.githubusercontent.com/9585787/64237496-a8403d80-cf26-11e9-86a0-1f0333bfaa96.png)

I don't use angular CLI when running my tests, it's done directly using tslint, fuse-box for bundling etc.

It would be great to run the exact same thing that does checks in the VSCode extension. Currently there isn't a clear way, if any to do this.

**Comment by trotyl** [comment]
Language service is a live compiler, all of the errors are normal compilation error. To get the error it would need an AOT compilation.

Even you don't use Angular CLI, there would be some script for AOT build process to get a production-ready bundle.

**Comment by jpike88** [comment]
> there would be some script for AOT build process to get a production-ready bundle

Where can I get this script? 

I would just want it purely for the errors it might throw. I don't want it to be heavy as if it was creating a production bundle, I only want it to run for a few seconds.

**Comment by trotyl** [comment]
> Where can I get this script?

For Angular CLI it's `ng build --aot`, if not in Angular CLI you'll need to check your configuration.

> I would just want it purely for the errors it might throw. I don't want it to be heavy as if it was creating a production bundle, I only want it to run for a few seconds.

Those are compilation error, not lint error, which can never be changed. To get compilation error the entire project need to be parsed, even you skip the file output.

Technically what you need is to combine `--noEmit` option with `ngc`, but won't change the fact it's a build step.

**Comment by jpike88** [comment]
ah yep I see. ```$(npm bin)/ngc -p client/src/tsconfig.json --noEmit``` did the trick.

just have to pipe that out I guess

thanks
