### ISSUE TITLE
Can't serve a fresh angular app with bazel installed

### ISSUE THREAD

**Issue by Newbie012** [angular/angular#32468]
# 🐞 bug report

### Affected Package

 The issue is caused by package @bazel\ibazel

### Is this a regression?
Unknown

### Description
I've created a new project by running the following commands:
```
npm i -g @angular/bazel
ng new portfolio --defaults --collection=@angular/bazel
```

After that, I ran `ng s` and I get errors (see below)

## 🔬 Minimal Reproduction
I'm not sure it's possible to reproduce this error in Stackblitz.
GitHub - https://github.com/Newbie012/angular-bazel

## 🔥 Exception or Error
<pre><code>
C:\Users\Eliya\Desktop\Apps\portfolio>ng s
Error getting Bazel info exit status 2
Querying for files to watch...
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
INFO: Call stack for the definition of repository 'npm' which is a npm_install (rule definition at C:/users/eliya/_bazel_eliya/2nsldyxa/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:294:15):
 - C:/users/eliya/_bazel_eliya/2nsldyxa/external/build_bazel_rules_nodejs/defs.bzl:77:5
 - C:/users/eliya/desktop/apps/portfolio/WORKSPACE:64:1
Loading: 0 packages loaded
ERROR: An error occurred during the fetch of repository 'npm':
   npm_install failed:
> portfolio@0.0.0 postinstall C:\Users\Eliya\Desktop\Apps\portfolio
> ngc -p ./angular-metadata.tsconfig.json

 (The system cannot find the path specified.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! portfolio@0.0.0 postinstall: `ngc -p ./angular-metadata.tsconfig.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the portfolio@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Eliya\AppData\Roaming\npm-cache\_logs\2019-09-04T09_47_56_791Z-debug.log
)
ERROR: no such package '@npm//': npm_install failed:
> portfolio@0.0.0 postinstall C:\Users\Eliya\Desktop\Apps\portfolio
> ngc -p ./angular-metadata.tsconfig.json

 (The system cannot find the path specified.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! portfolio@0.0.0 postinstall: `ngc -p ./angular-metadata.tsconfig.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the portfolio@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Eliya\AppData\Roaming\npm-cache\_logs\2019-09-04T09_47_56_791Z-debug.log
)
Loading: 0 packages loaded
Loading: 0 packages loaded
Bazel query failed: exit status 7
Loading: 0 packages loaded
Loading: 0 packages loaded
INFO: Call stack for the definition of repository 'npm' which is a npm_install (rule definition at C:/users/eliya/_bazel_eliya/2nsldyxa/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:294:15):
 - C:/users/eliya/_bazel_eliya/2nsldyxa/external/build_bazel_rules_nodejs/defs.bzl:77:5
 - C:/users/eliya/desktop/apps/portfolio/WORKSPACE:64:1
Loading: 0 packages loaded
ERROR: An error occurred during the fetch of repository 'npm':
   npm_install failed:
> portfolio@0.0.0 postinstall C:\Users\Eliya\Desktop\Apps\portfolio
> ngc -p ./angular-metadata.tsconfig.json

 (The system cannot find the path specified.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! portfolio@0.0.0 postinstall: `ngc -p ./angular-metadata.tsconfig.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the portfolio@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Eliya\AppData\Roaming\npm-cache\_logs\2019-09-04T09_48_10_054Z-debug.log
)
ERROR: no such package '@npm//': npm_install failed:
> portfolio@0.0.0 postinstall C:\Users\Eliya\Desktop\Apps\portfolio
> ngc -p ./angular-metadata.tsconfig.json

 (The system cannot find the path specified.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! portfolio@0.0.0 postinstall: `ngc -p ./angular-metadata.tsconfig.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the portfolio@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Eliya\AppData\Roaming\npm-cache\_logs\2019-09-04T09_48_10_054Z-debug.log
)
Loading: 0 packages loaded
Loading: 0 packages loaded
Bazel query failed: exit status 7
Runing //src:devserver
Loading: 0 packages loaded
Loading: 0 packages loaded
INFO: Call stack for the definition of repository 'npm' which is a npm_install (rule definition at C:/users/eliya/_bazel_eliya/2nsldyxa/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:294:15):
 - C:/users/eliya/_bazel_eliya/2nsldyxa/external/build_bazel_rules_nodejs/defs.bzl:77:5
 - C:/users/eliya/desktop/apps/portfolio/WORKSPACE:64:1
Loading: 0 packages loaded
ERROR: An error occurred during the fetch of repository 'npm':
   npm_install failed:
> portfolio@0.0.0 postinstall C:\Users\Eliya\Desktop\Apps\portfolio
> ngc -p ./angular-metadata.tsconfig.json

 (The system cannot find the path specified.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! portfolio@0.0.0 postinstall: `ngc -p ./angular-metadata.tsconfig.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the portfolio@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Eliya\AppData\Roaming\npm-cache\_logs\2019-09-04T09_48_22_141Z-debug.log
)
ERROR: no such package '@npm//': npm_install failed:
> portfolio@0.0.0 postinstall C:\Users\Eliya\Desktop\Apps\portfolio
> ngc -p ./angular-metadata.tsconfig.json

 (The system cannot find the path specified.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! portfolio@0.0.0 postinstall: `ngc -p ./angular-metadata.tsconfig.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the portfolio@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Eliya\AppData\Roaming\npm-cache\_logs\2019-09-04T09_48_22_141Z-debug.log
)
Loading: 0 packages loaded
Loading: 0 packages loaded
Error running Bazel exit status 7
C:\Users\Eliya\Desktop\Apps\portfolio\node_modules\@bazel\ibazel\bin\windows_amd64\ibazel.exe failed with code 4.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.2
Node: 10.11.0
OS: win32 x64
Angular: 8.2.4
... animations, bazel, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.2
@angular-devkit/build-angular     0.803.2
@angular-devkit/build-optimizer   0.803.2
@angular-devkit/build-webpack     0.803.2
@angular-devkit/core              8.3.2
@angular-devkit/schematics        8.3.2
@angular/cli                      8.3.2
@bazel/bazel                      0.28.1
@bazel/hide-bazel-files           0.36.2
@bazel/ibazel                     0.10.3
@bazel/karma                      0.34.0
@bazel/protractor                 0.34.0
@bazel/typescript                 0.34.0
@ngtools/webpack                  8.3.2
@schematics/angular               8.3.2
@schematics/update                0.803.2
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment]
Hi,

Bazel builder and schematics were deprecated several major versions ago, so I'm closing this ticket. You can find more information about this on the [Deprecated APIs and features page](https://angular.io/guide/deprecations#bazel-builder-and-schematics) and in the [migration guide](https://github.com/angular/angular/blob/master/packages/bazel/src/schematics/README.md).

Thank you.
