### ISSUE TITLE
TSLint is being deprecated

### ISSUE THREAD

**Issue by Tchanu** [angular/angular#32462]
What are your plans about [Roadmap: TSLint -> ESLint #4534](https://github.com/palantir/tslint/issues/4534)?

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
