### ISSUE TITLE
Weird mismatch with @angular/language-service and @angular/compiler-cli errors

### ISSUE THREAD

**Issue by jpike88** [angular/angular#32470]
@angular/language-service with latest vscode extension brings up an errors that $(npm bin)/ngc -p client/src/tsconfig.json --noEmit doesn't bring up, and vice versa. I thought @angular/language-service uses the same rulesets as @angular/compiler-cli?

**Here is an example of an error that gets shown in the VSCode extension, but not in ngc.**

```
components/app/admin-panel/admin-users.component.ts.AdminUsersComponent.html(3,3): Property 'loading' does not exist on type 'AdminUsersComponent'.
```

```
@Component({
	template: `
			<custom-table *ngIf="!loading">
	                </custom-table>
	`
})
export class AdminUsersComponent {

}
```

^ this is the code that threw the error. This is good. But the VSCode extension does not pick this up.

**Here is an example of an error that gets shown in the VSCode extension, but not in ngc.**

<img width="998" alt="Screen Shot 2019-09-04 at 5 48 41 PM" src="https://user-images.githubusercontent.com/9585787/64248938-aaad9200-cf3c-11e9-878a-56206aa2cd5c.png">

I'm using "@angular/language-service": "^9.0.0-next.4". I'm using VSCode extension version v0.900.0-next.0

**Comment by atscott** [comment]
Hi @jpike88, thanks for reporting this issue. This will be resolved when we release the Language Service for Ivy. All diagnostics for the Ivy LS come directly from the Angular compiler whereas the current VE implementation does its own interpretation of the template to produce diagnostics.

**Comment by JoostK** [comment]
With the Ivy language service now available, the errors that are reported are now consistent with regular builds as the compiler is now used to do type-checking, including a user's compiler options.
