### ISSUE TITLE
https://angular.io/guide/lazy-loading-ngmodules#lazy-loading-feature-modules guide doesn't work

### ISSUE THREAD

**Issue by nickbullock** [angular/angular#32476]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router and @angular/compiler

### Is this a regression?

 Maybe

### Description

 
Hi, i created simple application described in https://angular.io/guide/lazy-loading-ngmodules#lazy-loading-feature-modules step by step.
Lazy loading using Router doesn't work with arrow syntax in AOT or prod build.
String syntax does.

```
const routes: Routes = [
  {
    path: 'customers',
    loadChildren: './customers/customers.module#CustomersModule'
  },
  {
    path: 'orders',
    loadChildren: () => import('./orders/orders.module').then(mod => mod.OrdersModule)
  },
  {
    path: '',
    redirectTo: '',
    pathMatch: 'full'
  }
];
```

## 🔬 Minimal Reproduction

 
[link](https://github.com/easy-two/ng-child-module-injector/tree/master/examples/router-module-lazy-loading-error)

## 🔥 Exception or Error
<pre><code>ERROR Error: Uncaught (in promise): Error: Runtime compiler is not loaded
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 7.3.9
Node: 10.15.3
OS: darwin x64
Angular: 8.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.29.0</code></pre>

**Comment by mlc-mlapis** [comment]
@nickbullock Wouldn't be better also to use Angular CLI 8.x?

**Comment by trotyl** [comment]
You can found the legacy version doc at https://v7.angular.io/guide/lazy-loading-ngmodules#routes-at-the-app-level

**Comment by nickbullock** [comment]
@trotyl sorry, my bad. Version 8 works as expected.

**Comment by kapunahelewong** [comment]
@nickbullock did the link that @trotyl shared and the note by @mlc-mlapis help you out? (thank you both! 🌟)

**Comment by nickbullock** [comment]
@kapunahelewong yes, everything is OK now, thank you

**Comment by kapunahelewong** [comment]
Great, thanks for letting us know, @nickbullock 😊

Would it be all right if I closed the issue since it's ok now?

**Comment by nickbullock** [comment]
@kapunahelewong ok =)

**Comment by sharikovvladislav** [comment]
@trotyl @mlc-mlapis can you explain how does it work, please? At least could you please point out what file/files handle dynamic imports in AOT case? 

Is it some transformer? Or is it in angular/compiler package?

**Comment by mlc-mlapis** [comment]
@sharikovvladisla The compiler has to recognize the pattern. Read https://github.com/angular/angular/issues/31886#issuecomment-517704935. I also didn't recognize immediately, that the pattern is important and the compiler can do all for you.
