### ISSUE TITLE
ngcc: Ideas for potential future improvements/refactorings

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#32486]
This is a random list of potential future improvements/ideas/suggestions to consider/explore for `ngcc`, mostly related to our goal of speeing it up (as a follow-up to #32427).

Jira issue: [FW-1543](https://angular-team.atlassian.net/browse/FW-1543)

---

**Architecture / Refactorings**

- [x] &nbsp;
> I believe that this could move inside the `Executor`. That way we can actually create a different updater for master and slave, rather than having an intelligent one that needs to care about the `cluster` API.

By: @petebacondarwin
Source: https://github.com/angular/angular/pull/32427#discussion_r319765730
PR: https://github.com/angular/angular/pull/36637

##
- [x] &nbsp;
> In fact I think that having a `ClusterMasterExecutor` and `ClusterWorkerExecuter` would be a cleaner way to architect this. I think it would require moving a lot of the helper functions in the file into an abstract `BaseExecutor` class, but I think this would also be helpful in terms of making this big main file more manageable.

By: @petebacondarwin
Source: https://github.com/angular/angular/pull/32427#discussion_r319765969
PR: https://github.com/angular/angular/pull/36637

##
- [x] &nbsp;
> Investigate whether we need to take available memory/memory consumption into account, when calculating how many worker processes to spawn?
> - How is memory affected by worker processes?
> - What happens, when available memory is exceeded?

By: @gkalpak
PR: https://github.com/angular/angular/pull/36626

---

**Speed improvement**

- [ ] &nbsp;
> **Pete:** From what I read, the main difference (only?) between `cluster.fork()` and `child_process.fork()` is that they share TCP connections? But since we are not interested in acting as a server, isn’t that redundant?
>
> **George:** Yes, we could use `child_process.fork()`, but `cluster` is a little more convenient (e.g. we don't need to provide the executable and argunents to `.fork()`, we can listen for messages on all workers with `cluster.on()`, it exposes `cluster.isMaster`/`cluster.isWorker`, etc.).
If there is extra overhead to `cluster`, I would expect it to be fixed (so not worth doing the bookkeeping manually), but we can definitely try (so that we don't have to assume :smiley:).

By: @petebacondarwin 
Source: https://angular-team.slack.com/archives/CB4UC1932/p1567284254046600

##
- [x] &nbsp;
> One thing [...] to try is to make the JS file that is executed by the worker process much slimmer. Currently the whole of the ngcc program must be reloaded into the node.js process (including requiring and parsing all the dependent JS files). I found in dgeni that this can be quite a significant initial hit if the program is large.

By: @petebacondarwin 
Source: https://angular-team.slack.com/archives/CB4UC1932/p1567354022059300

##
- [ ] &nbsp;
> BTW2, we could also investigate whether `worker_threads` work better for `ngcc`. They are supposed to be more lightweight than separate processes and can communicate more efficiently with the main thread via shared memory. (But they are experimental and available behind a flag before 11.7 iirc.)

By: @gkalpak
Source: https://angular-team.slack.com/archives/CB4UC1932/p1567245751039000
PR: -

More context:
If the speed improvement is significant, we could detect support for `worker_threads` and use that implementation if it is available and fall back to other implementation (e.g. `cluster`-based) if not.

##
- [x] &nbsp;
> BTW, I believe we can get another ~2x improvement by only processing the entry-points we care about, instead of processing everything by default with ivy-ngcc.

By: @gkalpak
Source: https://angular-team.slack.com/archives/CB4UC1932/p1567237731035500
PR: https://github.com/angular/angular/pull/37075

More context:
Currently, in order to take advantage of the speed improvement achieved through parallel task execution, one needs to run `ngcc` "stand-alone" (not implicitly via `@angular/cli`). The easiest way to do that using the `ivy-ngcc` node script.

The default (e.g. with `npm run ivy-ngcc`) is to process all supported formats (even if they won't be used). This takes much more time than necessary. As a rouch estimate, the difference between `yarn ivy-ngcc` vs `yarn ivy-ngcc -p es2015 module` (which are the properties that `@angular/cli` essentially [cares about](https://github.com/angular/angular-cli/blob/e0073c0210547cd8e502fcd47a6cb6976f02b572/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts#L69-L70)) is 2.5x faster on my laptop for `aio`.

I believe it would make sense to get people to only compile the properties they care about by default. This would require to:
1. Recommend this in documentation and/or have `@angular/cli` auto-generate a suitable `postinstall` npm script when scaffolding IVy apps.
2. Determine the format properties we need to consider, based on the cli targets (and the `mainFields` used from the current version of `@angular/cli`). There are potentially going to be two sets of properties; one for es2015 and one for es5.
3. Add support for compiling the first of two sets of `propertiesToConsider` (or run `ngcc` twice, once for es2015 and once for es5, but that would be significantly slower, I assume).

##
- [ ] &nbsp;
> Investigate potential performance bottlenecks (e.g. why only a 2x/2.5x improvement via parallelization).
> Incorporate tracking of various metrics (possibly with a special flag only, to avoid affecting performance) to help gain better insight on current performance/issues. Examples:
> - Track time spent on master.
> - Track time spent on IPC (e.g. by including timestamps in messages).
> - Track worker idle time.
> - Track tasks processed per worker.
>     - Track mean processing time.
> - Cached file-system cache hits/misses.

By: @gkalpak
PR: -

**Comment by petebacondarwin** [comment]
Slightly off-topic: We also need to consider the process-safety of ngcc when reading and writing to disk. It turns out that some people run multiple `ng build`s at the same time! This means that each CLI process is triggering ngcc independently, which can result in corrupt files. Encouraging people to use the stand-alone `ivy-ngcc` in CI scenarios would alleviate this.

**Comment by Toxicable** [comment]
One thought I had about this is that `ivy-ngcc` should probably be incrimental.

We often have to run our postinstall step in our repository and `ivy-ngcc` can take 5-10 minutes, weather it's to update deps, update, test/debug updates or just bazel invalidating it's cache and needing to rerun postinstall, it happens often and the time `ivy-ngcc` takes is a significant drain.

If we were to add a incrimental module we could likely get that processing time down significantly.
One implementation could be by hashing the package after processing it and storing that state into a cache file, then simply read that state out before deciding if we need to re-run `ivy-ngcc` on a specific module

**Comment by petebacondarwin** [comment]
@Toxicable - yes we have discussed this in the past. I think it is a good idea but would need careful thinking through.

**Comment by petebacondarwin** [comment]
I don't think there is much value is moving away from `cluster` for creating multiple executors now. So those aspects of this issue can be ignored. Most of the other items have been addressed.

The only outstanding ones as far as I can tell are:

* Investigate potential performance bottlenecks (e.g. why only a 2x/2.5x improvement via parallelization).
* Investigate incremental builds

**Comment by petebacondarwin** [comment]
At this stage we are not going to implement incremental builds for ngcc.
I believe that the refactoring to simplify the bootup time of worker processes and also making them load up lazily as needed should have improved the parallelization times, so I think there is limited (if any) benefit in spending time investigating this further.
