### ISSUE TITLE
Update Bazel dependencies for angular packages to rely on zone-js from source

### ISSUE THREAD

**Issue by josephperrott** [angular/angular#32482]
Usage of `zone.js` within the Angular repo should depend on zonejs directly rather than via npm package.

Imports of `zone.js` import from `//packages/zone.js` rather than `@npm//zone.js` and ultimately `zone.js` should be able to be removed from `/package.json'.

**Comment by JiaLiPassion** [comment]
Working on this one now, update to prevent the issue to be auto closed.
