### ISSUE TITLE
General code generation cleanups

### ISSUE THREAD

**Issue by mhevery** [angular/angular#3248]
# Normalize string / No interpolation
- [x]  Replace `interpolate1 = "" "${componentName0 == null ? "" : componentName0}" ""` with `interpolate1 = " " + stringify(componentName0) + " ";` NOTE: will require import of `stringify` method. I think `${}` creates extra unneeded checks, so simple string concat `+` should be better in this case.

# Inline assignments
- [x] take advantage of multiple assignments per line. 

```Dart``
    _componentName0 = _gen.ChangeDetectionUtil.uninitialized();
    _interpolate1 = _gen.ChangeDetectionUtil.uninitialized();
    _directive_1_0 = _gen.ChangeDetectionUtil.uninitialized();
    _directive_2_0 = _gen.ChangeDetectionUtil.uninitialized();
``` 

becomes:

```Dart
 _componentName0 = _interpolate1 = _directive_1_0 = _directive_2_0 
       = _gen.ChangeDetectionUtil.uninitialized;
```

- [x] Also call `dehydrateDirectives()` from constructor so that we don't have to duplicate the code in the constructor.

# Inline assignments and usages
- [ ] inline where ever possible.

```Dart
        _dispatcher.notifyOnBinding(currentProto.bindingRecord, interpolate1);
        _interpolate1 = interpolate1;
```

becomes
```Dart
        _dispatcher.notifyOnBinding(currentProto.bindingRecord, _interpolate1 = interpolate1);
```

# have `notifyOnBinding` helper

- [ ] create `viewSet` in super. Notice that `_dispatcher` is always a View. This code is no longer abstract so we should use concrete names. 

```Dart
currentProto = _protos[1]
...     
change_interpolate1 = true;
_dispatcher.notifyOnBinding(currentProto.bindingRecord, interpolate1);
_interpolate1 = interpolate1;
```

becomes
```Dart
        change_interpolate1 = viewSet(1, _interpolate1 = interpolate1);
```

which requires this method on superclass

```Dart
  boolean viewSet(int index, dynamic value) {
    _view.notifyOnBinding(protos[index].bindingRecord, value);
    return true;
  }
```

# `looseNotIdentical`

- [x] have `loseNotIdentical` which will allow us to change `if (!_gen.looseIdentical(...))` to `if (_gen.looseNotIdentical(...))`. (its only one char, but it is everywhere)

# inline context assignment

```Dart
    var context = null;
    context = _context;
```

should be 

```Dart
    var context = _context;
```

# Unused `change_context`

- [x] the code is never used in output

```Dart
var change_context = false;
```

but is never read.

# change `uninitialized()` method call to `uninitialized` static field

-  [x] should save some chars

**Comment by kegluneq** [comment]
fyi, per our discussion i'm currently working on `Inline assignments` above

**Comment by kegluneq** [comment]
Step 1: Determine if "Normalize string / No interpolation" provides any benefit
Step 2 already underway

**Comment by yjbanov** [comment]
This issue proposes to optimize the size of code that we should not be generating at all. Therefore, fixing any of these will have 0 net effect on code size once we stop generating it. I'd rather we spent our time on the ultimate solution.

The ultimate solution is to move all value fields, and comparison and notification logic into common classes. Generated code should only be responsible for evaluating expressions in a typed and monomorphic manner. Here are two ways (which we can combine) for how we can do this: https://docs.google.com/document/d/1x8MmbK3bKJb5JFrz3SmLfUsWYURZhYqPux12zKm1i8k/edit#

**Comment by kegluneq** [comment]
@yjbanov , I commented on that doc but in summary I'm not confident we'll be able to implement that scheme without performance impact. Most of the `ProtoRecord`s result in code like what you propose but not all of them and we'd need runtime checks to figure out what course of action to take.

In the mean time, this process is cutting down on code duplication, which should make any ultimate solution easier to implement.

**Comment by kegluneq** [comment]
* Double-checked, but at least for Dart, interpolation is better than `+` concat, so it's my intention to not complete that piece of this issue unless someone wants to discuss.
* I'm pushing the remaining parts to the next milestone because https://github.com/angular/angular/issues/3245 will be a bigger win and is closer to completion
  * **Inline assignments and usages**
  * **have notifyOnBinding helper**

I won't be finishing either this milestone as I'm out the next couple of days.

**Comment by kegluneq** [comment]
The remaining points here are not as urgent as supporting `part`s in the transformer.

**Comment by kegluneq** [comment]
Change detectors & code generation in general have changed a lot - this is now obsolete.
