### ISSUE TITLE
Reactive Forms 'Required' Validator 

### ISSUE THREAD

**Issue by shivamkhanna189** [angular/angular#32487]
Reactive Forms  "Required Validator "  

Required Validator when applied on input field and passed with  **null or ""**  gives an error . Means that this is invalid input. This is completely fine. 

But my conern is that when Required Validator is passed with an string of spaces **"                "** 
,it doesn't give any error. Means it take this as the valid input . But according to me this should be an invalid input . 

 Its internal implementation should check something like this  :

**control.value.toString().trim() == ""**
Then I think It will work fine .

**Comment by tieppt** [comment]
This is expected behavior as the `required` attribute.
Demo here: https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation#The_required_attribute

To custom behavior, you can create new validator function https://angular.io/guide/form-validation#custom-validators

**Comment by atscott** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
