### ISSUE TITLE
Peer dependency node-gyp doesn't works with PYTHON 3

### ISSUE THREAD

**Issue by omarlara** [angular/angular#32498]
# 🐞 bug report

### Affected Package
node-sass
node-gyp

 The issue is caused by package @angular/....

### Is this a regression?

 no regression ....

### Description
We have a server in windows with phyton 3 installed and we have an error with node-gyp, this package is used by some other dependencies from angular cli.
 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

You need to have a windows server with phyton3 installed.
then run "npm install"

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

`EXEC : gyp ERR! stack error : Can't find Python executable "C:\Python\Python37\python.exe", you can set the PYTHON env variable. [F:\_work\3\s\project.csproj] 

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.3
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              0.8.3
@angular-devkit/schematics        0.8.3
@angular/cli                      6.2.3
@ngtools/webpack                  7.3.9
@schematics/angular               0.8.3
@schematics/update                0.8.3
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.29.0

</code></pre>

**Anything else relevant?**

WINDOWS SERVER

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
