### ISSUE TITLE
Click on child routerLink does not trigger (click) on parent component(s)

### ISSUE THREAD

**Issue by gromo** [angular/angular#32490]
# 🐞 bug report

### Description
Click on `<a [routerLink]="['/any-valid-route']">link</a>` does not trigger (click) on parent component, or it's triggered only once, but when navigating to another url and back, all further clicks on this link cannot be handled in parent element click handler

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-zeqa7x?file=src%2Fapp%2Ftest.component.html

```
<div (click)="onWrapperClick()">
  <div>Click here will trigger `onWrapperClick()`</div>
  <div>
    <a [routerLink]="['/take-while/1']">click here will trigger `onWrapperClick()` only for first time component is created or won't be triggered even the first time</a>
  </div>
</div>
```

## 🌍  Your Environment

**Angular Version:**
reproduced on Angular 7 and 8

**Comment by haacki47** [comment]
I see this issue. By default Angular click event is bubbling, thus when you redirect on another page component destroyed and event can't be triggered.

This code will works, because it is capturing event.

```javascript
 //file: test.component.ts

  ngOnInit() {
    this.el.nativeElement.addEventListener('click', function () {
      console.log('hello world');
    }, true)
  }
``

**Comment by gromo** [comment]
@haacki47 thanks for explanation why this bug/unexpected behavior happens, knowing this I have updated code to handle `(click)` directly on `routerLink` and emit event manually through custom Output - in my case click handler and link are in different components.

**Comment by atscott** [comment]
Closing as working as expected. Adding specific documentation for this rare use-case would create more confusion than it solves and make the documentation longer and harder to read.
