### ISSUE TITLE
Write a component response to IFRAME with CSS not rendered inside IFRAME

### ISSUE THREAD

**Issue by santooudnur** [angular/angular#32494]
We have component  which will get data from CMS and rendered through html template and style URLs.

Now we have requirement where the same component response need to be rendered through IFRAME for sandboxing resaons.  

I was able to write the response of component to IFRAME but SCSS of this components are not available inside IFRAME html . Just iframe document body has been updated with html no css.

Please provide solution for the same.

Refered : https://stackoverflow.com/questions/38457662/iframe-inside-angular2-component-property-contentwindow-does-not-exist-on-typ

Reference 2 : https://stackblitz.com/edit/angular-component-iframe?file=src%2Fapp%2Fapp.component.css-and-js-code-into-an-iframe-2blc
sample code 

[angular-component-iframe-code.zip](https://github.com/angular/angular/files/3579450/angular-component-iframe-code.zip)

Waiting for your quick response

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
