### ISSUE TITLE
An object literal cannot have multiple properties with the same name in strict mode.

### ISSUE THREAD

**Issue by jkyoutsey** [angular/angular#32496]
# 🐞 bug report

### Affected Package
*IVY*
`ng build --prod` - Only affects Ivy prod build.

### Is this a regression?
Yes, the previous version in which this bug was not present was: "without Ivy" same version

### Description
In templates where I have a `class.something` binding and a `something` binding:
```
[class.something]="someVar"
[something]="someVar"
```
I get these errors when doing an `ng build --prod` only.
```
ERROR in src/app/common/searchable-select.component.html(5,2): An object literal cannot have multiple properties with the same name in strict mode.
src/app/common/searchable-select.component.html(5,2): Duplicate identifier 'something'.
```
Happens regardless of inline or external template.
I can ng serve without these errors.

## 🔬 Minimal Reproduction
I cannot reproduce the issue with `ng new name --enable-ivy` in a simple app.  I did ng update to the latest version of Angular in the new app as well.  This is happening in my VERY large application on several templates.

## 🔥 Exception or Error
<pre><code>
ERROR in src/app/common/searchable-select.component.html(5,2): An object literal cannot have multiple properties with the same name in strict mode.
src/app/common/searchable-select.component.html(5,2): Duplicate identifier 'something'.
</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 8.3.2
Node: 10.16.0
OS: darwin x64
Angular: 8.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.2
@angular-devkit/build-angular     0.803.2
@angular-devkit/build-optimizer   0.803.2
@angular-devkit/build-webpack     0.803.2
@angular-devkit/core              8.3.2
@angular-devkit/schematics        8.3.2
@angular/cdk                      8.1.4
@angular/cli                      8.3.2
@angular/material                 8.1.4
@angular/pwa                      0.803.2
@ngtools/webpack                  8.3.2
@schematics/angular               8.3.2
@schematics/update                0.803.2
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.39.2
</code></pre>

## Workaround
Change the css class name in the binding so that it doesn't conflict and the error goes away.
Or use `*ngClass="{something: something}"`

**Comment by alxhub** [comment]
This looks related to template type-checking.

**Comment by Splaktar** [comment]
This looks like it may be the same issue as https://github.com/angular/angular/issues/32099.

**Comment by jkyoutsey** [comment]
@Splaktar these are probably related, but this does not appear to be a material issue. I hit this error on non-material components. I imagine the underlying source of the problem is the same though.

**Comment by Splaktar** [comment]
Right, it's not specific to Angular Material. It's an issue with template type checking in general.

**Comment by harshjulka** [comment]
Please reopen this issue. Getting below errors while enabling ivy

After migrating to latest version.
 "dependencies": {
    "@angular/animations": "^9.0.0-next.11",
    "@angular/cdk": "^9.0.0-next.0",
    "@angular/common": "^9.0.0-next.11",
    "@angular/compiler": "^9.0.0-next.11",
    "@angular/core": "^9.0.0-next.11",
    "@angular/forms": "^9.0.0-next.11",
    "@angular/http": "^7.2.15",
    "@angular/material": "^9.0.0-next.0",
    "@angular/platform-browser": "^9.0.0-next.11",
    "@angular/platform-browser-dynamic": "^9.0.0-next.11",
    "@angular/platform-server": "^9.0.0-next.11",
    "@angular/pwa": "^0.803.9",
    "@angular/router": "^9.0.0-next.11",
    "@angular/service-worker": "^9.0.0-next.11",
    "@auth0/angular-jwt": "^2.1.2",
    "@ng-idle/core": "^8.0.0-beta.4",
    "@ng-idle/keepalive": "^8.0.0-beta.4",
    "@ngu/carousel": "^1.5.5",
    "@nguniversal/common": "^8.1.1",
    "@nguniversal/express-engine": "^8.1.1",
    "@nguniversal/module-map-ngfactory-loader": "^8.1.1",
    "@ngx-meta/core": "^7.0.0",
    "bootstrap": "^4.3.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.6.10",
    "font-awesome-scss": "^1.0.0",
    "hammerjs": "^2.0.8",
    "lodash": "^4.17.15",
    "mock-browser": "^0.92.14",
    "moment": "^2.24.0",
    "ng5-slider": "^1.2.4",
    "ngx-bootstrap": "^3.3.0",
    "ngx-perfect-scrollbar": "^6.3.0",
    "pm2": "^2.10.4",
    "rxjs": "^6.5.3",
    "rxjs-tslint": "^0.1.7",
    "stacktrace-js": "^2.0.1",
    "ts-loader": "^4.4.1",
    "web-animations-js": "^2.3.2",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.900.0-next.12",
    "@angular/cli": "~9.0.0-next.12",
    "@angular/compiler-cli": "^9.0.0-next.11",
    "@angular/language-service": "^9.0.0-next.11",
    "@types/express": "^4.17.1",
    "@types/jasmine": "^3.4.4",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "~12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "^2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.2",
    "ts-node": "~8.4.1",
    "tslint": "^5.10.0",
    "typescript": "3.6.4",
    "webpack-cli": "^3.3.9"
  }

rror TS1117: An object literal cannot have multiple properties with the same name in strict mode.

21                                         <mat-list *ngFor="let proof of inpData['data']; let i of index;">
                                                     ~~~~~~~~~~~~~~~~~~~~~~~
 error TS2300: Duplicate identifier 'ngForOf'.

21                                         <mat-list *ngFor="let proof of inpData['data']; let i of index;">

**Comment by biltongza** [comment]
Getting this issue with @angular/flex-layout `[fxFlex]="flexPercent" [fxFlex.xs]="flexXsPercent"`.

**Comment by Splaktar** [comment]
@harshjulka and @biltongza this issue is closed. I think that we can track this in https://github.com/angular/angular/issues/33590 going forward.
