### ISSUE TITLE
404 GET /rxjs-compat/add/operator/filter

### ISSUE THREAD

**Issue by Shubhamschavan90** [angular/angular#32492]
We are trying to migrate from angular 2.4 to angular 8 and we're getting the issue of 404 rxjs-compat module not found though this module is not present in our node modules folder.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
