### ISSUE TITLE
ng build error when ivy used

### ISSUE THREAD

**Issue by schuman66** [angular/angular#32504]
Angular 8
Under ivy mode I get a error when 'ng build'.
The error information: ERROR in There is no appropriate source code format in ### **'C:/Users/Administrator/Desktop/my-project/node_modules/date-fns/distance_in_words_to_now' entry-point.**
Need your help.

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
