### ISSUE TITLE
problem running tests with bazel

### ISSUE THREAD

**Issue by kevinlllR** [angular/angular#32507]
# 🐞 bug report

### Is this a regression?
No
### Description

 I try to run the tests with bazel but I get an error.

## 🔬 Minimal Reproduction

 clone angular , install packages 
`yarn bazel test packages/service-worker`

## 🔥 Exception or Error
<pre><code>

`DEBUG: /home/garabato/.cache/bazel/_bazel_garabato/261f63f10319411c44159014f4f4080b/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:256:5: rbe_ubuntu1604_angular is using checked-in configs 'struct(config_repos = [], create_cc_configs = True, create_java_configs = True, env = {"ABI_LIBC_VERSION": "glibc_2.19", "ABI_VERSION": "clang", "BAZEL_COMPILER": "clang", "BAZEL_HOST_SYSTEM": "i686-unknown-linux-gnu", "BAZEL_TARGET_CPU": "k8", "BAZEL_TARGET_LIBC": "glibc_2.19", "BAZEL_TARGET_SYSTEM": "x86_64-unknown-linux-gnu", "CC": "clang", "CC_TOOLCHAIN_NAME": "linux_gnu_x86"}, java_home = "/usr/lib/jvm/java-8-openjdk-amd64", name = "9.0.0")'
INFO: Analyzed target //packages/service-worker:service-worker (113 packages loaded, 7514 targets configured).
INFO: Found 1 target and 0 test targets...
INFO: Deleting stale sandbox base /home/garabato/.cache/bazel/_bazel_garabato/261f63f10319411c44159014f4f4080b/sandbox
Target //packages/service-worker:service-worker up-to-date:
  dist/bin/packages/service-worker/index.ngfactory.d.ts
  dist/bin/packages/service-worker/index.ngsummary.d.ts
  dist/bin/packages/service-worker/index.d.ts
  dist/bin/packages/service-worker/public_api.ngfactory.d.ts
  dist/bin/packages/service-worker/public_api.ngsummary.d.ts
  dist/bin/packages/service-worker/public_api.d.ts
  dist/bin/packages/service-worker/src/index.ngfactory.d.ts
  dist/bin/packages/service-worker/src/index.ngsummary.d.ts
  dist/bin/packages/service-worker/src/index.d.ts
  dist/bin/packages/service-worker/src/low_level.ngfactory.d.ts
  dist/bin/packages/service-worker/src/low_level.ngsummary.d.ts
  dist/bin/packages/service-worker/src/low_level.d.ts
  dist/bin/packages/service-worker/src/module.ngfactory.d.ts
  dist/bin/packages/service-worker/src/module.ngsummary.d.ts
  dist/bin/packages/service-worker/src/module.d.ts
  dist/bin/packages/service-worker/src/push.ngfactory.d.ts
  dist/bin/packages/service-worker/src/push.ngsummary.d.ts
  dist/bin/packages/service-worker/src/push.d.ts
  dist/bin/packages/service-worker/src/update.ngfactory.d.ts
  dist/bin/packages/service-worker/src/update.ngsummary.d.ts
  dist/bin/packages/service-worker/src/update.d.ts
  dist/bin/packages/service-worker/service-worker.d.ts
INFO: Elapsed time: 150.894s, Critical Path: 128.00s
INFO: 34 processes: 34 worker.
INFO: Build completed successfully, 79 total actions
INFO: Build completed successfully, 79 total actions
error Command failed with exit code 4.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

</code></pre>

## 🌍  Your Environment

**Yarn Version:**
1.17.3
**Nodejs Version:**
Node v10.9 and v10.16

**Anything else relevant?**
Ubuntu 16.04.4 lts

**Comment by lazarljubenovic** [comment]
Same on Ubuntu 18.04.3 LTS.

**Comment by lukasmatta** [comment]
Same on macOS 10.14.6.

**Comment by alexeagle** [comment]
Where did you get the command `yarn bazel test packages/service-worker` ? That's wrong.

That isn't a test target, so bazel just does a build, then exits 4 because there were no tests to run
```
alexeagle@alexeagle-glaptop:~/Projects/angular$ bazel test packages/service-worker
INFO: Build completed successfully, 77 total actions
alexeagle@alexeagle-glaptop:~/Projects/angular$ echo $?
4
```

You could find this out:
```
$ bazel query packages/service-worker
ng_module rule //packages/service-worker:service-worker
``` 
testing an `ng_module` doesn't do anything.

If you want to run all the service-worker tests you probably want 
`yarn bazel test packages/service-worker/...`

**Comment by lukasmatta** [comment]
@alexeagle Thank you for your explanation, it works now. Reading documentation I thought that string *...* in the path is just a placeholder for the package name.

**Comment by albyrock87** [comment]
@alexeagle actually I just found that "documentation string" here: https://github.com/angular/angular/blob/master/docs/DEVELOPER.md#running-tests-locally

**Comment by JoostK** [comment]
Thanks @alexeagle for the insight, this is indeed working as expected.

**Comment by lazarljubenovic** [comment]
It's working as expected when you know what to expect. The docs are heavily misleading.

**Comment by alexeagle** [comment]
I think the only reasonable place to change is Bazel itself? It exits 4 and nothing specific to Angular, Node, or yarn really has a chance at intercepting and better explaining the meaning of the exit codes.

**Comment by JoostK** [comment]
> I think the only reasonable place to change is Bazel itself? It exits 4 and nothing specific to Angular, Node, or yarn really has a chance at intercepting and better explaining the meaning of the exit codes.

Agreed, that would offer the best improvement. I relabeled this as docs issue to briefly go into the `...` syntax, as apparently that's what's causing confusion here.

**Comment by petebacondarwin** [comment]
This is an issue with the error messages coming from the upstream `Bazel` tool.
There is nothing actionable for us here.
I would suggest opening an issue here https://github.com/bazelbuild/bazel
