### ISSUE TITLE
Module not found: Error: Can't resolve '@angular/core' in fesm2015 

### ISSUE THREAD

**Issue by nialish** [angular/angular#32513]
I have built an angular class library and imported it in separate project module but after doing ng serve it gives error:
**ERROR in ../dist/MyBuiltLibrary/fesm2015/MyBuiltLibrary.js
Module not found: Error: Can't resolve '@angular/core' in '..\dist\MyBuiltLibrary\fesm2015'**

Why is it so?

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
