### ISSUE TITLE
docs: Add filename headers to code snippets

### ISSUE THREAD

**Issue by kapunahelewong** [angular/angular#32517]
# 📚 Docs or angular.io bug report

### Description

Generally, we try to have file name headers on docs code snippets, however, there are still outstanding snippets that don't have them. This will help clarify where the reader is supposed to find, edit, or add something. 

### What's the affected URL?**

@alan-agius4 mentioned i18n in [this comment](https://github.com/angular/angular/pull/32329#issuecomment-528995907) which is a good start. In addition, there are a number of other instances throughout the docs.

### Reproduction Steps**

Just scroll through docs with code snippets (they'll have to be found). For example, [line 209 of the i18n doc](https://github.com/angular/angular/blame/master/aio/content/guide/i18n.md#L209).

### Expected vs Actual Behavior**

We can improve the reader experience by always being explicit.

## 📷Screenshot

This should have a blue header with the file name:
![image](https://user-images.githubusercontent.com/4116963/64461609-ac599000-d0cb-11e9-9388-c47ea2806a6d.png)

### Browser info

N/A

**Comment by gkalpak** [comment]
I just wanted to note that there _are_ (few) code snippets for which a filename header does not make sense or improve the reader's experience. (They are definitely a minority though.)

**Comment by alan-agius4** [comment]
Yeah absolutely @gkalpak!!

**Comment by kapunahelewong** [comment]
Yep, @gkalpak. This is true. @jbogarthyde if you have any questions as to which ones don't need headers, let me know. :)

**Comment by jbogarthyde** [comment]
The reference PR is just for the ones in i18n -- looking for more examples.

**Comment by alan-agius4** [comment]
@jbogarthyde, why has this been closed? The suggestion was to go through the entries AIO guides and add the headers to the code snippets that don’t have.

**Comment by jbogarthyde** [comment]
I did go through all the pages and added headers, in the referenced PR. Have you seen some I missed?

**Comment by alan-agius4** [comment]
This one
https://github.com/angular/angular/blob/master/aio/content/guide/cli-builder.md

**Comment by jbogarthyde** [comment]
Adding the code-example headers in https://angular.io/guide/cli-builder -- I don't see this code for the final  test example anywhere in the Minko's demo.
https://angular.io/guide/cli-builder#testing-a-builder
What should the header be? @alan-agius4 @michael.prentice

**Comment by jbogarthyde** [comment]
Resolved by referenced PRs -- will add to guidelines.
