### ISSUE TITLE
NgControl.control is undefined when injected

### ISSUE THREAD

**Issue by jessejohnsohn** [angular/angular#32522]
# 🐞 bug report

### Affected Package

 The issue looks to come from @angular/forms when the `enableIvy` flag is set to true.

### Is this a regression?

 Yes, this works as expected with the `enableIvy` flag set to false.

### Description

Injecting NgControl into a component that implements the ControlValueAccessor shows up with an undefined `control` property only when the `enableIvy` flag is set to true in tsconfig.json.

With `enableIvy` set to false, the "control" property exists on the injected NgControl object and is populated with the appropriate FormControl instance.

## 🔬 Minimal Reproduction
https://github.com/jessejohnsohn/possible-ivy-bug

Run the application and view the browser console. A `FormControl` instance will be logged, coming from `full-name.component.ts:25.`

Go into the application's tsconfig.json file and change "enableIvy" to true. Stop the local dev server and restart it.

Now load the application and view the browser's console. Where the FormControl instance was logging before will now say `undefined`.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.2.2
Node: 10.16.0
OS: win32 x64
Angular: 8.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.2
@angular-devkit/build-angular     0.802.2
@angular-devkit/build-optimizer   0.802.2
@angular-devkit/build-webpack     0.802.2
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.2.2
@angular/cli                      8.2.2
@ngtools/webpack                  8.2.2
@schematics/angular               8.2.2
@schematics/update                0.802.2
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.38.0
</code></pre>

**Anything else relevant?**

This is on the latest version of Chrome.

Windows computer.

**Comment by benelliott** [comment]
This also results in `NgControl.statusChanges` etc being null. This is a major blocker for us updating to Ivy.

**Comment by IgorMinar** [comment]
I was able to repro this with rc.1

The odd thing is that the `NgControl` has a different shape with Ivy than without:

`enableIvy: false`:
![Screen Shot 2019-11-08 at 5 56 02 PM](https://user-images.githubusercontent.com/216296/68521002-75316780-0251-11ea-86dd-0355977cc897.png)

`enableIvy: true`:
![Screen Shot 2019-11-08 at 5 55 48 PM](https://user-images.githubusercontent.com/216296/68521005-79f61b80-0251-11ea-8ad3-e53315a1f47f.png)


Notice that the `control` prop is missing with Ivy and that the object has `__ngContext__` and `__ngSimpleChanges__` props. Is this expected?
