### ISSUE TITLE
polyfill.ts in start application on StackBlitz too old for local build

### ISSUE THREAD

**Issue by mMerlin** [angular/angular#32527]
# 📚 Docs or angular.io bug report

### Description

Following the instructions to build the start application locally fails.  The deployment page needs additional information about handling different StackBlitz and local environment versions.

## 🔬 Minimal Reproduction

- Download start application project from StackBlitz
- unzip downloaded file
- ng new test-project
- rm -rf test-project/src
- mv ~/Downloads/tmp/src test-project
- ng build --prod

### What's the affected URL?**

https://angular.io/start/deployment

### Expected vs Actual Behavior**

Expected:

`ng` builds the project, creating files in the dist folder.

Actual:

build error messages and abort

## 🔥 Exception or Error

<pre><code>ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/reflect' in '…/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es7/reflect' in '…/src'
</code></pre>

## 🌍  Your Environment

5.2.11-200.fc30.x86_64
ng --version
…
Angular CLI: 8.3.1
Node: 10.16.3
OS: linux x64
Angular:
…
@angular-devkit/architect    0.803.1
@angular-devkit/core         8.3.1
@angular-devkit/schematics   8.3.1
@schematics/angular          8.3.1
@schematics/update           0.803.1
rxjs                         6.4.0

### Anything else relevant

Researching the cause of the reported missing files found

<https://stackoverflow.com/questions/55308769/module-not-found-error-cant-resolve-core-js-es6>

With that hint, I did some version checks.  The downloaded package.json shows `"core-js": "2.6.9"` while a new empty local project package-lock.json shows `"core-js": "3.2.1"`.  A significant difference.  Further checking shows that the StackBlitz project was created with `Angular CLI version (7.0.7)`, while my local environment is `(8.3.1)`.  Obviously not directly compatible.

After experimenting with ways to get the StackBlitz code updated to the newer environment for awhile, I hit on a simple solution.  Before deleting the `/src` folder from the new local project, save a copy of `/src/polyfills.ts`.  After moving the downloaded `/src` folder into the project, replace the downloaded `polyfills.ts` file with the saved version.  That gets the latest polyfill version, apparently upgrading everything to match the local environment.

The `polyfills.ts` file was never touched while creating the start application on StackBlitz.  It seems to have the default for the environment used there.  So it should be safe to simply replace it.  At least it worked for me, with no warnings about version differences.

**Comment by gkalpak** [comment]
FWIW, I don't think it is possible to ensure that creating a new CLI project and replacing the `src/` directory with the one downloaded from StackBlitz will always work.

I suggest that we don't try to do that, because we will end up with broken or complex instructions for beginners. There are two more much more reliable alternatives that we could use instead:

1. Have a link for people to download the zip that is generated for the example. E.g. for the get started guide, it will be https://angular.io/generated/zips/getting-started-v0/getting-started-v0.zip.
    _Pros:_
    - The app is guaranteed to at least build successfully (since we are testing it on CI).
    - We have full control over the downloaded archive (which isn't the case with StackBlitz).
    - Most likely, it is safe to replace the `src/` directory with the one downloaded from StackBlitz. (This is still not 100% guaranteed to work, but the probability of breakages is much lower.)
    _Cons:_
    - This will still not be using the latest version of Angular (but we do periodically update the version of Angular used in examples).
    - It might include some (few) irrelevant dependencies, since the `package.json` file is shared among many examples.

2. Suggest that people create a new app using `@angular/cli` (`ng new ...`) and if necessary re-apply the changes from their StackBlitz demo.
    _Pros:_
    - Guaranteed to use the latest version of Angular and project layout (if they are using the latest CLI version).
    - Guaranteed to build successfully.
    _Cons:_
    - More friction if the user is trying to run an example from StackBlitz locally.

In any case, I feel that both of the above options (with their pros and cons) are better than what we are trying to do now (which is kind of trying to merge the two approaches).

**Comment by rockument69** [comment]
To resolve this, I think we should choose option #2 in @gkalpak comment above. This would require only a few steps to copy code from Stackblitz to the new project.

**Comment by aikidave** [comment]
If we address https://github.com/angular/angular/issues/32524, I think we can address this one as well.

**Comment by JeanMeche** [comment]
I'll close this in favor of #49709 which is a about same issue but with the current state of the default stackblitz project.
