### ISSUE TITLE
Feature Request: Web worker client

### ISSUE THREAD

**Issue by gleosmith** [angular/angular#32528]
Hi angular community,

# 🚀 feature request

### Relevant Package
It would likely fit into a separate package such as @angular/web-worker

### Description
Improve the development experience when making use of web workers by providing easier, strongly typed communication between a web worker and an Angular application. Also improving the test-ability of a web worker.

### Describe the solution you'd like
A service that can create clients to communicate with web workers which have decorated observables, properties and/or methods.

### Describe alternatives you've considered
I have built a library to do something similar, although I think it could be made a bit more comprehensive to cover a few more use cases (https://github.com/gleosmith/angular-web-worker).

**Comment by jelbourn** [comment]
Closing all issues related to web-workers since Angular's experimental web-worker renderer has been deprecated and it now being removed completely in Angular v11.
