### ISSUE TITLE
Custom Element will display error if change ngZone:'noop' on main.ts

### ISSUE THREAD

**Issue by DarkHorseReborn** [angular/angular#32546]
I'm trying to build an angular custom web element that could support in non-angular-application or angular-application.

Basically I have done installed relevant package like  "@angular/elements": "6.1.10" and so on.
Cut long story short, I will provide the sample code that encounters the issue.
https://stackblitz.com/edit/angular-xqfkvj?file=package.json

Please refer image below for my error :
![image](https://user-images.githubusercontent.com/24264392/64487422-18bfc500-d26d-11e9-80a1-6eefbc04afc9.png

I hope there someone could tell me what is happening? Your help is much appreciated.

Thanks.

**Comment by gkalpak** [comment]
Sorry for the late response. This seems to work fine on the latest version (10.0.3): [Updated StackBlitz][1]
If you are still running into problems with the latest version, please open a new issue.

[1]: https://stackblitz.com/edit/ngelements-issue-32546?file=src%2Fapp%2Fapp.component.ts
