### ISSUE TITLE
Expecting content transclusion where it won't happen should fail/throw fast

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#3254]
For example, if you do:

```html
<panel>
  <my-component></my-component>
</panel>
```

If `<panel>` does not define an `<ng-content>` outlet, it effectively does nothing in the best case (wasting ops) and in the worst case will cause errors as the underlying elements may expect to be in the DOM.

**Comment by mhevery** [comment]
WONT_FIX / WORKS_AS_INTENDED

This is the way ShadowDOM works. But more importantly maybe real Panel has re-projection, but in your tests you have MockPanel which does not have re-projection. In such a case you don't want to fail. So I think this is the correct behavior.

**Comment by tbosch** [comment]
Note that after https://github.com/angular/angular/issues/3605 is done,
ElementRef.nativeElement will return an element for all ElementRefs, even
if they are not projected.
