### ISSUE TITLE
Lazy Loading without Routing in Angular 8

### ISSUE THREAD

**Issue by Hema95** [angular/angular#32559]
#### Feature Description

Lazy Loading without Routing is now not possible with loadchilden It would be nice to have such feature

#### Use Case

There is an alternative to use NgModuleFactoryLoader but it gives lint warning during AOT compilation

**Comment by mlc-mlapis** [comment]
@Hema95 It is possible. Look at https://github.com/angular/angular/issues/31886 for example.

**Comment by freemanlam** [comment]
> @Hema95 It is possible. Look at #31886 for example.

I tried but not work. This is my repro: https://github.com/freemanlam/ng8-aot-dynamic-import-issue

**Comment by freemanlam** [comment]
> @freemanlam You ignored the main facts that were mentioned in #31886, so you can't be surprised that it doesn't work.
> 
> You can't use just `const loadedModule = await import('./test-module.module').then(m => m.TestModuleModule);`. Angular compiler doesn't understand such a syntax.

Thanks so much.
Finally I read whole thread and success to load lazy modules in AOT.

For my case my `import()` functions are already put in a variable and I just need to handle [instance type check](https://github.com/angular/angular/issues/31886#issuecomment-515996665), then it works :D

**Comment by atscott** [comment]
Based on the discussion here, it looks like a solution was found so I'm closing this issue.
