### ISSUE TITLE
customizing component

### ISSUE THREAD

**Issue by arcturuscom** [angular/angular#32550]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please file any Angular Components issues at: https://github.com/angular/components/issues/new

For the time being, we keep Angular Components issues in a separate repository.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
Hello, i would like to know if could be possible to customize angular component on my business need. sometimes we repeat a lot of common behaviours in some components.

e.g : form component that will manage the form behind the scence.
we know already that this component will start with form validation and display errors if necessary.
and most of time we have 2 buttons one for submit and the other for reset.
and finally it's will end up with success or fail message.

could it be possible to create or customize a component that could do all this stuff behind the scence and the developer could only focus on submit method that should be create to route with service call.

**Comment by matsko** [comment]
Closing this since the issue doesn't follow our new issue template.
