### ISSUE TITLE
Language Service: Provide information about the NgModule a directive belongs to

### ISSUE THREAD

**Issue by ayazhafiz** [angular/angular#32565]
# 🚀 feature request

### Relevant Package

This feature request is for @angular/tools-language-service

### Description

We should provide information about the NgModule a directive in a TS file and selectors in a template file belong to, when the directives and selectors are hovered over.

### Describe the solution you'd like

Update [language-service/definitions.ts](https://github.com/angular/angular/blob/master/packages/language-service/src/definitions.ts).

**Comment by kyliau** [comment]
Perhaps we should leave this open after #32763 is merged since that only handles directive in a TS file? Showing the same info for selectors in a template might be a little more involved.
