### ISSUE TITLE
canDeactive firing AFTER lazy loading of route even if navigation is not allowed to occur

### ISSUE THREAD

**Issue by ShaneMcGowan** [angular/angular#32561]
# 🐞 bug report

### Affected Package
Have tested 8.1.3 and 6.1.10

### Is this a regression?
No, is acting the same in V6 and V8

### Description
When going to a lazy loaded route from a route with a `canDeactivate` route guard, before the `canDeactivate` would prevent navigation, the lazy loading happens and the chunk is downloaded causing the `RouteConfigLoadStart` and `RouteConfigLoadEnd` events to fire. 
These events should only occur if the `canDeactivate` returns true.

## 🔬 Minimal Reproduction
Check console output.
Navigate to module A and then to module B. You will see lazy loading start and then complete before the can deactivate is called
[https://angular-can-deactivate-lazy-loading-issue.stackblitz.io/](https://angular-can-deactivate-lazy-loading-issue.stackblitz.io/)

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.1.3
Node: 10.16.3
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.801.3
@angular-devkit/core         8.1.3
@angular-devkit/schematics   8.1.3
@schematics/angular          8.1.3
@schematics/update           0.801.3
rxjs                         6.4.0

</code></pre>

**Comment by sergei-dzekevich** [comment]
Same problem I have encountered.

**Comment by ShaneMcGowan** [comment]
any word on this being fixed?

**Comment by martinsik** [comment]
Just tested this issue in Angular 13 and it's still happening: https://stackblitz.com/edit/angular-can-deactivate-lazy-loading-issue-p8j9v9?file=src%2Fapp%2Fapp-routing.module.ts

**Comment by atscott** [comment]
This is working as designed and won't be changed. The `Router` needs to first compute _where_ the requested navigation goes. This can affect the result of the `canDeactivate` guards. In order to know where the navigation is going, the router must load, expand, and match against the route configs, and apply any redirects.

**Comment by ShaneMcGowan** [comment]
> This is working as designed and won't be changed. The `Router` needs to first compute _where_ the requested navigation goes. This can affect the result of the `canDeactivate` guards. In order to know where the navigation is going, the router must load, expand, and match against the route configs, and apply any redirects.

You've broken my heart Andrew, you've broken my heart

**Comment by atscott** [comment]
❤️  @ShaneMcGowan Sorry! It's really just not feasible given the Router's architecture so I thought it best to close the issue rather than leave it open for eternity ☹️
