### ISSUE TITLE
Support more popular package managers out-of-the-box

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#3257]
With https://github.com/angular/angular/pull/3215 we have the capability to set package relative URLs as `package:PACKAGE_NAME/path/to/file/within/package`. We currently support only pub. We should provider resolvers for:

- npm
- bower
- webpack
- jspm

**Comment by Alxandr** [comment]
May I suggest adding jspm to that list?

**Comment by yjbanov** [comment]
@Alxandr of course!

**Comment by pflannery** [comment]
It would also be worth having a custom path config option as bower lets us define the directory name (in the .bowerrc file) it uses for storing its packages.
