### ISSUE TITLE
Angular Router ExtraOptions initialNavigation does not default to enabled

### ISSUE THREAD

**Issue by laurentgoudet** [angular/angular#32571]
# 📚 Docs or angular.io bug report

At https://angular.io/api/router/ExtraOptions, the docs state that `initialNavigation` defaults to `enabled`:

> One of enabled (the default) or disabled.

This is not the case. Looking at the code (https://github.com/angular/angular/blob/master/packages/router/src/router_module.ts#L556),  it defaults to `legacy_enabled`, which is not the same as `enabled` (e.g. `enabled` is required for SSR to work as per https://github.com/angular/angular/issues/15716#issuecomment-291025332).

The docs do not mention the legacy values as these are deprecated, so I'm not sure what would be the best way to phrase it. Maybe:

> One of enabled or disabled (defaults to a legacy behavior for compatibility).

**Comment by Splaktar** [comment]
Types like `InitialNavigation` should actually show up in the docs. It looks like there is a bug here.

https://github.com/angular/angular/blob/8a47b489124204e7d2139927e3258f2be4e3aeb1/packages/router/src/router_module.ts#L228-L252
Seems valid and is marked `@publicApi`. Other `Types` are listed here: https://angular.io/api?type=type-alias. But I don't see any others that use a `Boolean` value like `true`.

**Comment by Splaktar** [comment]
Oh and here's an official comment from @vikerman confirming that `enabled` is required for Universal with lazy loading to avoid style flickering: https://github.com/angular/angular/issues/15716#issuecomment-302195906

**Comment by Splaktar** [comment]
PR https://github.com/angular/angular/pull/32707 adds the `InitialNavigation` API to the docs.

Thank you for reporting this!

**Comment by Splaktar** [comment]
This is fixed in PR https://github.com/angular/angular/pull/32702 which has been merged.

@jbogarthyde I think that this can be closed now?
