### ISSUE TITLE
Vendor.js is very large

### ISSUE THREAD

**Issue by letanloc1998** [angular/angular#32579]
Vendor.js is not optimize, it is very large, how to optimizer it? (delete comment, remove enter/space,....)

**Comment by mlc-mlapis** [comment]
@letanloc1998 What mode do you mean? JIT or AOT? If AOT, what is included in it. Did you check the structure?

**Comment by letanloc1998** [comment]
> @letanloc1998 What mode do you mean? JIT or AOT? If AOT, what is included in it? Did you check the structure?

what is it? i use ng build prod
when I delete comment it reduce about 20%. how to delete all comment in vendor.js and space not use?

**Comment by Edouardbozon** [comment]
@letanloc1998 running `ng build --prod` will optimize the build, for what is AOT [go here](https://angular.io/guide/aot-compiler)

**Comment by letanloc1998** [comment]
> @letanloc1998 running `ng build --prod` will optimize the build, for what is AOT [go here](https://angular.io/guide/aot-compiler)

Thank you
