### ISSUE TITLE
Add autocorrect attribute support on <input> field for iOS devices

### ISSUE THREAD

**Issue by rms-bc** [angular/angular#32575]
# 🚀 feature request

### Description
The `autocorrect` attribute on `<input>` fields causes Angular to throw an error.
Indeed, this attribute is not part of the HTML5 specification and is therefore nonstandard.
However, this attribute allows for disabling predictive typing on iOS devices, which happens to be really useful.

### Describe the solution you'd like
Add support for the `autocorrect` attribute for iOS devices.
Allowed values are `on` and `off`

### Describe alternatives you've considered
At the moment, the only working solution (to do it properly) is to go through `Renderer2`, and dynamically set the attribute whenever it is needed.

**Comment by alxhub** [comment]
You can also use an `[attr.autocorrect]` binding. Our DOM schema is generated automatically from Chrome, so we try to avoid making manual tweaks like this.
