### ISSUE TITLE
data not updated in angular

### ISSUE THREAD

**Issue by ManishKSeth** [angular/angular#32583]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
Hi All,

I am new in angular and currently working with angular 8.
I am facing an issue related to call function and life cycle hooks in angular.
i have a anchor link in table, on click of this anchor link **i opened a new browser as a popup window with the respective data** and on that screen user can also delete and update the record.

All above functionality works fine but **when i close the newly opened popup browser and come on my main browser screen then tables data not updates and deleted records showing there.**
how can i update that, is there any way to call function or life cycle hooks from one component to another.
**be careful these two components are in two different browsers as i mentioned above.**

i also used event emitter services but they are not  working.

please help. thanks in advance.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by ShaneMcGowan** [comment]
You can't do that, the two different windows are completely seperate

**Comment by SineOfLight** [comment]
Assuming the source data lives in a database, and not in JS memory, you might want to listen to the document.visibilitychange event and simply refresh your data when becoming visible, e.g call your backend for th latest state

https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event

**Comment by matsko** [comment]
Closing this since the issue wasn't filled out properly.
