### ISSUE TITLE
Template error: Can't bind to 'ngIf' since it isn't a known property of 'h1/ng-container/div'.

### ISSUE THREAD

**Issue by cromefire** [angular/angular#32597]
# 🐞 bug report

### Affected Package

 I guess it's the @angular-devkit/build-angular

### Is this a regression?

 Yes, the previous version in which this bug was not present was: I guess somewhat around `8.1` or `8.2`

### Description

If I use structural directives (at least `*ngIf` and I also got this with the forms module) combined with `ivy` and `ng server` (`yarn start`) the app works (so it's not an issue with `CommonModule` not being imported or similar). Then you need to change a thing in the template (just add text somewhere) and when `ng serve` reloads then it can't find the directive. This get resolved again if you restart `ng serve`

## 🔬 Minimal Reproduction

https://github.com/cromefire/ngIf-issue

## 🔥 Exception or Error

```
Template error: Can't bind to 'ngIf' since it isn't a known property of 'h1'.
```
or
```
Template error: Can't bind to 'ngIf' since it isn't a known property of 'ng-container'.
```
or
```
Template error: Can't bind to 'ngIf' since it isn't a known property of 'div'.
```

## 🌍  Your Environment

**Angular Version:**

```
Angular CLI: 8.3.3
Node: 12.10.0
OS: linux x64
Angular: 8.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.3
@angular-devkit/build-angular     0.803.3
@angular-devkit/build-optimizer   0.803.3
@angular-devkit/build-webpack     0.803.3
@angular-devkit/core              8.3.3
@angular-devkit/schematics        8.3.3
@angular/cli                      8.3.3
@ngtools/webpack                  8.3.3
@schematics/angular               8.3.3
@schematics/update                0.803.3
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
```

**Anything else relevant?**

Important:
 - `ivy`
 - `ng serve`

**Comment by cromefire** [comment]
Do components already have support for `9.0`?

**Comment by JoostK** [comment]
@cromefire Not officially according to its `peerDependencies`, but it does work. In fact, the Angular framework repo runs the  testcases from the `components` repo for each commit/PR, and vice versa does the `components` repo run against a nightly of Angular (therefore the 9.0 previews).
