### ISSUE TITLE
variable init of undefined after build with ivy

### ISSUE THREAD

**Issue by GlauberF** [angular/angular#32609]
# 🐞 Bug report

```
- [ ] new
- [ x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
After deploying with ivy and returning success in the terminal, when opening the error app in various init, as the image below

## 🌍 Your Environment
```
Angular CLI: 8.3.3
Node: 10.15.3
OS: linux x64
Angular: 9.0.0-next.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.3
@angular-devkit/build-angular      0.803.3
@angular-devkit/build-optimizer    0.803.3
@angular-devkit/build-webpack      0.803.3
@angular-devkit/core               8.3.3
@angular-devkit/schematics         8.3.3
@angular/cdk                       8.2.0
@angular/cli                       8.3.3
@angular/flex-layout               8.0.0-beta.26
@angular/material                  8.2.0
@angular/material-moment-adapter   8.2.0
@ngtools/webpack                   8.3.3
@schematics/angular                8.3.3
@schematics/update                 0.803.3
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2
```

## 🔥 Exception or Error
![Captura de Tela_selecionar área_20190910161612](https://user-images.githubusercontent.com/11314585/64643750-7aa43a00-d3e7-11e9-9256-b703290558c7.png)

![Captura de Tela_selecionar área_20190910161711](https://user-images.githubusercontent.com/11314585/64643760-80018480-d3e7-11e9-8f96-a3c3f17f970f.png)

**Comment by kara** [comment]
@GlauberF Since we still don't have a repro, this issue isn't actionable, so I'm closing it.

That said, are you using flex-layout? My guess is that you ran into this one: https://github.com/angular/angular/issues/31956.  It should be fixed if you upgrade the version of the lib.
