### ISSUE TITLE
Intercept and cancel the client side call of “enableProdMode()” function

### ISSUE THREAD

**Issue by ahmadabulaban** [angular/angular#32601]
Dears,

To enable the production mode the application should call the "enableProdMode()" function in main.ts . The issue is that the generated js will contain the method without renaming, so the attacker can intercept and cancel the function call then the debug mode will be enabled.

One of the solutions used (even used in [angular.io](https://angular.io) site) is to use webpack as webpack tries to reduce the size of bundled JavaScript files by renaming functions with random short names. Now the function renamed successfully but also the generated js will contain a hint to know where's the function place and also intercept and cancel it, the webpack always replace enableProdMode() with something like this:

`function Oa(){if(ib)throw Error("Cannot enable prod mode after platform setup.");ge=!1}
` 

So the attacked can search for the string "Cannot enable prod mode after platform setup" or part of it and change the function before the browser receives it.

Kindly find the related link that show how to simulate this case: https://nvisium.com/blog/2019/01/17/angular-for-pentesters-part-2.html

Any suggestions for this issue, because it was reported by the security team as a vulnerability ?

Version used is **8.2.4**

**Comment by mprobst** [comment]
> The issue is that the generated js will contain the method without renaming, so the attacker can intercept and cancel the function call then the debug mode will be enabled.

Can you share some detail on how an attacker will intercept this function call?

An attacker will need to run JavaScript code in the context of the Angular application to intercept the `enableProdMode` function. But generally speaking, if an attacker can already execute arbitrary JavaScript in the context of your page, all is lost. The attacker can already steal cookies, perform arbitrary operations on the page, etc.

With that in mind, `enableProdMode` isn't a security boundary, and obfuscating the method will not help. Having it around might make it a bit easier to poke at what's going on in a page, but a motivated attacker will figure that out in any case.

I'd report that back to your security team. Please reopen if there's more detail or something we're missing here.
