### ISSUE TITLE
TypeScript peer dependency warnings

### ISSUE THREAD

**Issue by jpike88** [angular/angular#32600]
```
npm WARN @angular/compiler-cli@8.2.5 requires a peer of typescript@>=3.4 <3.6 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/core@8.2.5 requires a peer of zone.js@~0.9.1 but none is installed. You must install peer dependencies yourself.
```

And typescript 3.6.3 just came out now. Why the lag in having angular handle 3.6.x? Is there some kind of blocker?

**Comment by sarunint** [comment]
Because the compiler uses the TypeScript API which _has breaking changes even in minor revision_.

**Comment by jpike88** [comment]
Is there an active PR that is referencing a TS upgrade? I can't seem to find any

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/32380
