### ISSUE TITLE
bazel ngc maximum call stack size exceeded

### ISSUE THREAD

**Issue by marcus-sa** [angular/angular#32612]
# 🐞 bug report

### Affected Package
The issue is caused by package `@angular/bazel@9.0.0-next.5`

### Is this a regression?
No, still fails with `@angular/bazel@8.2.5`

### Description
Maxes out call stack when building, because of an infinite loop caused by NGC when trying to find metadata.

## 🔬 Minimal Reproduction
1. Clone repository commit branch https://github.com/ng-qt/ng-qt/tree/1a488ad7587140437691b5a52aefa4e63f171dab
2. Install dependencies (if installation of `@nodegui/nodegui` throws an error, just ignore it)
3. Build using `bazel build //packages/platform --sandbox_debug`

## 🔥 Exception or Error
Can be found at https://github.com/ng-qt/ng-qt/issues/52

## 🌍  Your Environment
```
@bazel/typescript: 0.36.2
@bazel/bazel: 0.29.0

**Comment by AndrewKushnir** [comment]
Hi,

Bazel builder and schematics were deprecated several major versions ago, so I'm closing this ticket. You can find more information about this on the [Deprecated APIs and features page](https://angular.io/guide/deprecations#bazel-builder-and-schematics) and in the [migration guide](https://github.com/angular/angular/blob/master/packages/bazel/src/schematics/README.md).

Thank you.
