### ISSUE TITLE
Remove jasmine custom equality tester in matchers.ts

### ISSUE THREAD

**Issue by vikerman** [angular/angular#32620]
# 🐞 bug report

### Affected Package
@angular/platform-browser/testing

### Is this a regression?
No

### Description
Compare two maps for equality in tests. 
expect(map1).toEqual(map2);

- What was the result?
The two maps do not pass the test if key type is not a basic type.

Reasoning: 
Map looks up values by key-reference rather than key equality, this makes the custom equality tester added to jasmine here (https://github.com/angular/angular/blob/master/packages/platform-browser/testing/src/matchers.ts#L134) to fail. Notice the expected.get() call in line 138).
The extra tester was added since Jasmine did not support Maps. We are now using Jasmine 3.x which has the requisite support.

**Comment by JoostK** [comment]
Resolved in #45521.
