### ISSUE TITLE
Getting Started example app doesn't build locally

### ISSUE THREAD

**Issue by carlin-q-scott** [angular/angular#32629]
# 📚 Docs or angular.io bug report

### Description
I followed the Angular Getting Started tutorial on StackBlitz, and it went well until I got to the Deployment section and had to download my code locally to build it for deployment.

After downloading my code, I ran `npm install` and then `npm audit fix` because there was a critical security bug. I then spent the next two hours resolving peer dependency conflicts by upgrading all the packages to their latest versions, and then downgrading a couple that were too new for peer dependencies.

### What's the affected URL?**
https://angular.io/start

### Reproduction Steps**
1. Open the [StackBlitz Angular Example app](https://angular.io/generated/live-examples/getting-started-v0/stackblitz.html) that's referenced [here](https://angular.io/start#create-a-new-project).
1. Click the download button below the Share button.
1. Extract the downloaded zip archive
1. Open the extracted folder in your terminal app
1. Run `npm install`
1. Run `npm audit fix`
1. Run `npm run build`

### Expected vs Actual Behavior**
I expect the build to pass, but it fails due to a missing Build class.

## 🌍  Your Environment
Windows 10 Home v1903
Windows Susbsystem for Linux running Ubuntu v18.04.3 LTS
Node v10.16.3
npm v6.9.0

### Anything else relevant?
I have my code on github here: https://github.com/carlin-q-scott/angular-kvsbvb

**Comment by Orodan** [comment]
I think the issue can be solved by upgrading the example in stackblitz with the latest version of angular (it's still in angular 7). I already tested it, this way there is no more vulnaribilities with the dependencies, we can keep the deployment section instructions as they are and we have an example up to date :)

I am ready to submit a PR but I'm not sure what is the procedure to update an stackblitz example of the project, any hint on that @kapunahelewong and @jbogarthyde ?

**Comment by kapunahelewong** [comment]
Thank you, @Orodan and @carlin-q-scott. 

Of related interest, I have a PR regarding the steps in the Deployment section of the Getting Started, that I think will clarify, [32888](https://github.com/angular/angular/pull/32888) (btw, I have some updates still to do to it, but you can see the overall direction).

There's also this that was recently merged [32969](https://github.com/angular/angular/pull/32969) that gets rid of the polyfills error. @Orodan you might find that one interesting as it effects the output from StackBlitz. However, as for changing the version of Angular, can you give us some insight, @StephenFluin?

**Comment by StephenFluin** [comment]
The StackBlitz team is planning to use the real CLI to generate the project files (package.json, etc) in the future, so while I know this doesn't fix this in the short term, this is the right fix.

When it comes to security errors, almost all of these are irrelevant for Angular users as they are in the CLI dependency chain, which is not shared/shipped to users.

If there was a short term fix, it would be changing the boilerplate version of the StackBlitz project to the right versions (and possibly adding a package-lock.json or yarn.lock file), but that might have unintended side effects.

**Comment by rockument69** [comment]
@kapunahelewong : Please confirm, this has been fixed. The PR [35510](https://github.com/angular/angular/pull/35510) is closed.

**Comment by AndrewKushnir** [comment]
Closing based on https://github.com/angular/angular/issues/32629#issuecomment-634319954.
