### ISSUE TITLE
import FormBuilder Component throw error

### ISSUE THREAD

**Issue by kittencup** [angular/angular#3263]
`import {FormBuilder,Validators,ControlGroup,formDirectives} from 'angular2/forms';`
error message
 Cannot resolve all parameters for xxxx(?). Make sure they all have valid type or annotations.

```
import {FormBuilder} from 'angular2/angular2';
import {Validators,ControlGroup,formDirectives} from 'angular2/forms';
```
That's right.

**Comment by ericmdantas** [comment]
Do you have:

```js

viewInjector: [Form Builder]

```

and:

```js

 constructor(@Inject(FormBuilder) fb: FormBuilder) {
}

```?

**Comment by kittencup** [comment]
yes, i have...

**Comment by ericmdantas** [comment]
Could you please set up a plnker or something?

**Comment by mhevery** [comment]
Closing until we have a plnker repro
