### ISSUE TITLE
Misprint in the documentation

### ISSUE THREAD

**Issue by AndreySy4** [angular/angular#32641]
#### Bug, feature request, or proposal:
Misprint in the documentation https://angular.io/guide/typescript-configuration
On example code "tsconfig.json" block "compilerOptions" declarate 2 times

**Comment by Potapy4** [comment]
Already fixed in #32449

**Comment by kapunahelewong** [comment]
Yes, @Potapy4 is correct (thank you, @Potapy4!). @AndreySy4, it takes a little while before PRs are merged for them to show up live, but good catch and thank you for reporting it. I'll close this issue if that's all right. If you see anything else, please let us know and you're always welcome to tag me, especially for docs issues. Thanks!
