### ISSUE TITLE
Angular HttpHeader not getting set

### ISSUE THREAD

**Issue by WarienX** [angular/angular#32657]
Hello everyone,
I am trying to set httpheader parameters but somehow it is not getting set. I have tried all the possible ways but cant seem to point out the issue. This is happening only in one component bcoz when I tested the same code in a different component the values set properly inside the header.

Currently I am using Angular 7.0.4 
This is a small part of the code where I am assigning the header:
const httpOptions = {
      headers: new HttpHeaders({
        'Access-Control-Allow-Origin': httpHeaderData.get('Access-Control-Allow-Origin'),
        'Content-Type': httpHeaderData.get('Content-Type'),
        'token': httpHeaderData.get('token'),
      }),
      headerData: new HttpParams().set('token', httpHeaderData.get('token')),
      withCredentials: true
    };
    const headers = new HttpHeaders({
      'Access-Control-Allow-Origin': httpHeaderData.get('Access-Control-Allow-Origin'),
      'Content-Type': httpHeaderData.get('Content-Type'),
      'token': httpHeaderData.get('token'),
    });
    headers.set('Access-Control-Allow-Origin', httpHeaderData.get('Access-Control-Allow-Origin'));

this is the browser console:-
headers: {"normalizedNames":{},"lazyUpdate":null}

httpOptions: {"headers":{"normalizedNames":{},"lazyUpdate":null},"headerData":{"updates":[{"param":"token","value":"gSOeLnlezHGiB-NIouli6Y2oQwJOl8aT","op":"s"}],"cloneFrom":{"updates":null,"cloneFrom":null,"encoder":{},"map":null},"encoder":{},"map":null},"withCredentials":true}

Any help would be greatly appreciated.

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
