### ISSUE TITLE
RouteConfig: Non Existing Components Issue

### ISSUE THREAD

**Issue by TiagoBraga39** [angular/angular#3265]
Hi all!

Just a quick pain I came across:
In Route Config, if we Route a non existing component, no error is thrown.
<b>In fact, the application doesn't even load:</b>
```javascript
@RouteConfig([
     new Route({ path: 'home', component: NonExistingComponent, as: 'home' })
])
```

Stay awesome,
Tiago Braga

**Comment by btford** [comment]
:+1: Will work on this for next iteration.

**Comment by TiagoBraga39** [comment]
Nice and thank yoou :+1

**Comment by btford** [comment]
@TiagoBraga39 I'm going to keep this open until the issue properly lands
