### ISSUE TITLE
Typo in diagnostic template info 

### ISSUE THREAD

**Issue by cRAN-cg** [angular/angular#32662]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/compiler-cli

### Is this a regression?
No

### Description

 When a variable is not defined in a template context the diagnostic offset span pushes the error as 
`The template context does not defined a member called`
instead it should be
`The template context does not define a member called`

## 🔥 Exception or Error
<pre><code>
The template context does not defined a member called
</code></pre>
## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.0-beta.15
Node: 10.16.0
OS: darwin x64
Angular: undefined
... 

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-beta.15
@angular-devkit/build-optimizer   0.800.0-beta.15
@angular-devkit/core              8.0.0-beta.15
@angular-devkit/schematics        8.0.0-beta.15
@angular/bazel                    0.0.0
@angular/cli                      8.0.0-beta.15
@schematics/angular               8.0.0-beta.15
@schematics/update                0.800.0-beta.15
rxjs                              6.4.0
typescript                        3.5.3
webpack                           1.12.9

</code></pre>

**Anything else relevant?**

**Comment by cRAN-cg** [comment]
I would like to work on it.

**Comment by cRAN-cg** [comment]
Sorry for the closing it.

**Comment by gkalpak** [comment]
Good catch, @cRAN-cg 👍 
Feel free to go ahead and submit a pull request :wink:

**Comment by cRAN-cg** [comment]
@gkalpak While going through the tests of `language-service` I found that the error message for implicit context reference
<pre><code>
    describe('in ngIf', () => {
      function expectError(locationMarker: string, message: string) {
        expectSemanticError('app/ng-if-cases.ts', locationMarker, message);
      }
      it('should report an implicit context reference', () => {
        expectError(
            'implicit', 'The template context does not defined a member called \'unknown\'');
      });
    });
</code></pre>
 
is different than that defined in the `compiler-cli`
<pre><code>
if (ast.value === '$implicit') {
          this.reportError(
              'The template context does not have an implicit value', spanOf(ast.sourceSpan));
        }
</code></pre>
I was wondering if you could advise me on the same too.
