### ISSUE TITLE
How to consume REST service with Basic Authentication

### ISSUE THREAD

**Issue by ultrasonicsoft** [angular/angular#3266]
Hi All,

I have java REST services and consumer in Angularjs 1.3. Services are JSON based and expect BASIC authentication (username-password). 
In AgJs 1.3, I used Base64 factory code (found on google) for creating basic authentication token from username and password and able to consume services SUCCESSFULLY.

I read HTTP class in AgJs 2.0 documentation but I didn't find any information about basic authentication.

Could anybody please provide sample code to consume REST services in Angularjs 2.0 using BASIC authentication?

Thanks in advance!
Best Regards!

My AgJs 1.3 code:

var url = "http://x.x.x.x:xxxx/data/" + number;

        $http.defaults.headers.common['Authorization'] = 'Basic ' + Base64.encode('username' + ':' + 'password');
        $http.defaults.headers.common['Content-Type'] = 'application/json';

        $http({ method: 'GET', url: url }).
                success(function (data, status, headers, config) {
                   alert(data);
                }).
                error(function (data, status, headers, config) {
                    alert("error: " + data);
                });

**Comment by kittencup** [comment]
https://github.com/kittencup/angular2-github-manage/blob/master/app/services/github.service.ts#L29

**Comment by ultrasonicsoft** [comment]
Hi kittencup,

Thank you very much for your reply.

I have gone through your source code to understand the use but i couldn't get exactly how to use it.I have downloaded your code and started with http-server but web page is not loading. Console showing resources missing errors. :(

I see you have used HTTPService and GithubService for calling services and in config setting Base Url.
I am surely missing some important steps. 

Could you please try to get some easy example of showing how to consume rest service with BASIC authentication?

Thanks in advance!

Best Regards,
Balram

**Comment by mhevery** [comment]
This is for issues, Could we take help to [gitter](https://gitter.im/angular/angular?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or [stackoverflow](http://stackoverflow.com/questions/tagged/angular2)?

**Comment by PTAB-TEch** [comment]
Hi,
i am calling switch API's for that i need to login to it first from postman i am using Authorization type basic and setting username ans password , i want to implement this in code i am using Angular 6.

please help me to get solution 


Thanks in advance 
Tanaji

**Comment by okako** [comment]
Hi,

Try that
headers.set('Authorization', `Basic ${btoa("username:password")}`)

Regards
