### ISSUE TITLE
Edge requires `crossorigin="anonymous"` to get `script` files from CDN

### ISSUE THREAD

**Issue by niklaas** [angular/angular#32660]
# 📚 Docs or angular.io bug report

### Description

We host our Angular application on Amazon S3. We use Java Wildfly to bootstrap our application i.e., import the required files via `<script>`s in the HTML template. (This is probably not very elegant but generally works and is due to some infrastructure restriction.) After updating to Angular 8 and its [Differential Builds feature](https://angular.io/guide/deployment#differential-builds) we had to adapt  the `<script>` tags and took the sample output provided at the linked resource as reference.

Since then Edge was unable to bootstrap the application and complained with error messages such as

```
SEC7120: [CORS] The origin 'https://example.com' did not find 'https://example.com' in the Access-Control-Allow-Origin' response header for cross-origin script resource at 'https://s3. ... .amazonaws.com/.../runtime-es2015.js'.
```

This happened because Edge did not send the `Origin` header, thus S3 did not answer with the required response header. Only after reloading the page, the application was bootstrapped. So it seems the required JS files were indeed received, taken from cache then, but the error message aborted the execution of the JS files.

The fix was to add `crossorigin="anonymous"` to module `<script>`s because

> Unlike classic scripts, module scripts require the use of the CORS protocol for cross-origin fetching. [3] (see also [1], [2], [4], [5])

Edge, in comparison to Firefox (and probably Chrome), seems to be very picky about this and only sends `Origin` if the attribute is provided. So I suggest altering the provided example output on [Differential Builds feature](https://angular.io/guide/deployment#differential-builds) to

```
<body>
  <app-root></app-root>
  <script src="runtime-es2015.js" type="module" crossorigin="anonymous"></script>
  <script src="runtime-es5.js" nomodule></script>
  <script src="polyfills-es2015.js" type="module" crossorigin="anonymous"></script>
  <script src="polyfills-es5.js" nomodule></script>
  <script src="styles-es2015.js" type="module" crossorigin="anonymous"></script>
  <script src="styles-es5.js" nomodule></script>
  <script src="vendor-es2015.js" type="module" crossorigin="anonymous"></script>
  <script src="vendor-es5.js" nomodule></script>
  <script src="main-es2015.js" type="module" crossorigin="anonymous"></script>
  <script src="main-es5.js" nomodule></script>
</body>
```

or mention this issue at least.

[1]: https://fetch.spec.whatwg.org/#concept-request-credentials-mode
[2]: https://fetch.spec.whatwg.org/#http-cors-protocol
[3]: https://html.spec.whatwg.org/multipage/scripting.html#attr-script-crossorigin
[4]: https://html.spec.whatwg.org/multipage/urls-and-fetching.html#cors-settings-attributes
[5]: https://html.spec.whatwg.org/multipage/webappapis.html#module-script

### Browser info
Microsoft Edge 44.*

**Comment by trotyl** [comment]
> The fix was to add `crossorigin="anonymous"` to module `<script>`s because

You were misreading the spec (it's indeed hard to read though), the module script will treat missing `crossorigin` attribute as `crossorigin="anonymous"`:

> To perform this translation, we define the module script credentials mode for a given CORS settings attribute to be determined by switching on the attribute's state:
> 
> - No CORS
> - Anonymous
>   ->"same-origin"

There is currently no way to disable CORS for module script, the spec change was made in https://github.com/whatwg/html/pull/3656, and the corresponding Edge issue is https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19076021/ and still open.

**Comment by kapunahelewong** [comment]
Adding label for engineering input to check on docs direction for v9. fyi @aikidave

**Comment by rockument69** [comment]
The central question is whether to change the provided example in [Differential Builds](https://angular.io/guide/deployment#differential-builds) to include `crossorigin="anonymous"` in the script. According to @trotyl there is no need to (the module script will treat missing `crossorigin` attribute as `crossorigin="anonymous"`). @kapunahelewong Should we close this?

**Comment by jelbourn** [comment]
Closing old Edge-related issues since any such issues have likely been resolved in the newer Chromium-based Edge.
