### ISSUE TITLE
Ngcc doesn't produce valid es5 code

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#32665]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
@angular/forms, @angular/common

### Is this a regression?

 Yes, it works without ivy

### Description

 A clear and concise description of the problem...
Code produced by ngcc is not valid es5.
Examples:
Fragment of node_modules\@angular\forms\__ivy_ngcc__\fesm5\forms.js 
```
const _c0 = ["ng-untouched", "ng-touched", "ng-pristine", "ng-dirty", "ng-valid", "ng-invalid", "ng-pending"];
const _c1 = ["novalidate", ""];
```
const!
Fragment of node_modules\@angular\common\__ivy_ngcc__\fesm5\common.js 
```
NgForOf.ngDirectiveDef = ɵngcc0.ɵɵdefineDirective({ type: NgForOf, selectors: [["", "ngFor", "", "ngForOf", ""]], factory: function NgForOf_Factory(t) { return new (t || NgForOf)(ɵngcc0.ɵɵdirectiveInject(ViewContainerRef), ɵngcc0.ɵɵdirectiveInject(TemplateRef), ɵngcc0.ɵɵdirectiveInject(IterableDiffers)); }, inputs: { ngForOf: "ngForOf", ngForTrackBy: "ngForTrackBy", ngForTemplate: "ngForTemplate" } });
/*@__PURE__*/ ɵngcc0.ɵsetClassMetadata(NgForOf, [{
        type: Directive,
        args: [{ selector: '[ngFor][ngForOf]' }]
    }], function () { return [{ type: ViewContainerRef }, { type: TemplateRef }, { type: IterableDiffers }]; }, { _viewContainer: [], _template: [], _differs: [], _ngForOfDirty: [], _differ: [], ngForOf: [{
            type: Input
        }], ngForTrackBy: [{
            type: Input
        }], ngForTrackBy: [], ngForTemplate: [{
            type: Input
        }], ngDoCheck: [], _applyChanges: [], _perViewChange: [] });
    return NgForOf;
}());
```
Notice double ngForTrackBy. PhantomJS thinks it's Syntax Error.

## 🔬 Minimal Reproduction
Compile any project which used ngFor or NG_VALUE_ACCESSOR 

## 🌍  Your Environment

**Angular Version:**
```json
{
  "dependencies": {
    "@angular/animations": "8.1.1",
    "@angular/common": "8.1.1",
    "@angular/compiler": "8.1.1",
    "@angular/core": "8.1.1",
    "@angular/forms": "8.1.1",
    "@angular/platform-browser": "8.1.1",
    "@angular/platform-browser-dynamic": "8.1.1",
    "@angular/router": "8.1.1",
    "core-js": "2.4.1",
    "rxjs": "6.4.0",
    "rxjs-compat": "6.4.0",
    "tslib": "1.9.1",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular/cli": "8.1.1",
    "@angular/compiler-cli": "8.1.1",
    "@angular/language-service": "8.1.1",
    "@ngtools/webpack": "^8.1.1",
    "codelyzer": "^5.0.0",
    "gulp": "^4.0.2",
    "typescript": "3.4.5",
    "webpack": "^4.35.2"
  }
}
```

**Anything else relevant?**

**Comment by alxhub** [comment]
Super weird. We'll investigate.

**Comment by trotyl** [comment]
> It's legal ES5 to repeat a property name inside an object literal

It's only valid in [ES5 sloppy mode, but not in strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Converting_mistakes_into_errors), and valid in both sloppy and strict mode after ES6. Given all module files are forced to be strict, that's not a valid ES5 code.

**Comment by dawidgarus** [comment]
What's also weird is that property is repeated but with different value. I don't know what should be the correct value, but it's worth to investigate whether the correct value is actually used. Note that minifiers like terser will remove duplicates.

**Comment by gkalpak** [comment]
The duplicate value is due to `ngcc` not handling getters/setters correctly. This is tracked in #30569.
We should still look into the `const` thing.

**Comment by gkalpak** [comment]
Interestingly, according to [MDN][1] (and empirical data :grin:), `const` _is_ supported in IE11.
(It's still not valid ES5 and we should look into, of course.)

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const

**Comment by dawidgarus** [comment]
@gkalpak yes, ES5 code generated by ngcc works in IE 11, that's probably why nobody notice anything weird before. However, I had notice that PhantomJS, and perhaps other tools that except ES5 code, is not as forgiving and it breaks my CI/CD pipeline.
