### ISSUE TITLE
Content Security Policy 

### ISSUE THREAD

**Issue by fbadshah** [angular/angular#32669]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

With the Angular framework - we receive low security grades on the Content Security Policy Header, due to the use of unsafe inline scripts. Is there a fix around this? Will this updated in the newer version? 
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by goenning** [comment]
In which situation do you get an inline script with Angular? I though it'd always bundle all the code.

**Comment by IgorMinar** [comment]
Angular never uses inline scripts. I wonder if this issue is caused by some other library or your custom setup. In any case, your security grades are not affected by the use of Angular.
