### ISSUE TITLE
A workaround to solve cycle dependencies

### ISSUE THREAD

**Issue by qaiffluke** [angular/angular#32672]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/bazel

### Description
 We come across many problems while integrating bazel with an existing angular project. One troubling issue is the cycle dependencies where components are dependent on various components from different modules. There is no way to build them as dependencies in bazel.

### Describe the solution you'd like
 If bazel could detect the cycle dependencies and find a way to build them altogether, it could solve the problem. Even using the cached build for the same targets could help.

### Describe alternatives you've considered
 Can build them all as sources but it is not as feasible. Also might have to replicate the components in the current module directory to avoid the cycle dependencies.

**Comment by Toxicable** [comment]
Could you produce an example of the dep graph you have?

If you know bazel query it can produce a dep graph for you like - https://blog.bazel.build/2015/06/17/visualize-your-build.html

**Comment by AndrewKushnir** [comment]
Hi,

Bazel builder and schematics were deprecated several major versions ago, so I'm closing this ticket. You can find more information about this on the [Deprecated APIs and features page](https://angular.io/guide/deprecations#bazel-builder-and-schematics) and in the [migration guide](https://github.com/angular/angular/blob/master/packages/bazel/src/schematics/README.md).

Thank you.
