### ISSUE TITLE
angular-ng-autocomplete due to compilation errors

### ISSUE THREAD

**Issue by DanielFrugoni** [angular/angular#32683]
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.4
@angular-devkit/build-angular     0.803.4
@angular-devkit/build-optimizer   0.803.4
@angular-devkit/build-webpack     0.803.4
@angular-devkit/core              8.3.4
@angular-devkit/schematics        8.3.4
@angular/cdk                      8.2.0
@angular/cli                      8.3.4
@angular/fire                     5.2.1
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.1.4
@ngtools/webpack                  8.3.4
@schematics/angular               8.3.4
@schematics/update                0.803.4
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2

after updating, get the error:
ERROR in Failed to compile entry-point angular-ng-autocomplete due to compilation errors:
node_modules/angular-ng-autocomplete/fesm2015/angular-ng-autocomplete.js(947,20): error TS-991006: Cannot combine @Input decorators with query decorators

How can I solve this ?

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

-------

It looks like angular-ng-autocomplete has this pattern, which is no longer allowed:

```
@Input() @ContentChild() something: any;
```
