### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError when *ngIf is used

### ISSUE THREAD

**Issue by MaBiloKako** [angular/angular#32693]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Description

I have 2 components inside a wrapper, and wrapper has fixed height. 
ToggleComponent has _height_ css property bound to `height` field and a button which changes `height` field.
TestComponent takes rest of the height. It has _test_ attribute bound to its _clientHeight_ .
Focus is on the DOM binding to something that would change from other component by its binding, that is why i use _clientHeight_. If there is `*ngIf` directive on TestComponent, when `ToggleComponent.height` is changed, ExpressionChangedAfterItHasBeenCheckedError occurs.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/ngif-detectionchange-v2

## 🔥 Exception or Error
<pre><code>
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'test: 200'. Current value: 'test: 100'.
    at viewDebugError (core.js:20440)
    at expressionChangedAfterItHasBeenCheckedError (core.js:20428)
    at checkBindingNoChanges (core.js:20530)
    at checkNoChangesNodeInline (core.js:23403)
    at checkNoChangesNode (core.js:23390)
    at debugCheckNoChangesNode (core.js:23994)
    at debugCheckDirectivesFn (core.js:23922)
    at Object.eval [as updateDirectives] (testChild.html:2)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:23911)
    at checkNoChangesView (core.js:23289)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.7
Node: 10.13.0
OS: win32 x64
Angular: 7.2.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.7
@angular-devkit/build-angular     0.13.7
@angular-devkit/build-optimizer   0.13.7
@angular-devkit/build-webpack     0.13.7
@angular-devkit/core              7.3.7
@angular-devkit/schematics        7.3.7
@angular/cdk                      7.3.6
@angular/cli                      7.3.7
@ngtools/webpack                  7.3.7
@schematics/angular               7.3.7
@schematics/update                0.13.7
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.6
</code></pre>

**Comment by kovaletsyurii** [comment]
It looks like code-issue, not angular. Can you try to display your components only after ViewInit?

**Comment by indraraj26** [comment]
may be your button which changes the height of toggle component is in ngFor. Can you replicate this in  stackblitz

**Comment by Crazybutch** [comment]
I've forked your example and changed it a little bit.
https://stackblitz.com/edit/ngif-detectionchange-v2-sa32ex

https://angular.io/guide/lifecycle-hooks#lifecycle-sequence

**Comment by MaBiloKako** [comment]
> may be your button which changes the height of toggle component is in ngFor. Can you replicate this in stackblitz

I have already attached a stackblitz example in OP. Here it is:
https://stackblitz.com/edit/ngif-detectionchange-v2

> I've forked your example and changed it a little bit.
https://stackblitz.com/edit/ngif-detectionchange-v2-sa32ex

Thank you for trying to help. Problem with that approach is that you set `height` property before view is updated, therefore we would have old value and not changed one.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
