### ISSUE TITLE
Ivy compiler incorrectly allows undefined to be passed to any component input even without explicit undefined in input type when strictNullChecks is on

### ISSUE THREAD

**Issue by compeek** [angular/angular#32690]
# 🐞 bug report

### Affected Package

Not exactly sure, but probably:
@angular/compiler
@angular/compiler-cli

### Is this a regression?

 

No, from my experience, the old compiler didn't enforce strictNullChecks in templates at all, so this is new to Ivy.

### Description

With `strictNullChecks` turned _on_, if you have a component input with a certain type that does _not_ explicitly include `undefined`, the Ivy compiler _does not complain_ if you pass `undefined` to that input from another component. This defeats a lot of the purpose of using `strictNullChecks`. (Note that it does complain about passing `null` if `null` isn't explicitly in the type, so I know `strictNullChecks` is enabled properly.)

I believe this is due to the use of `Partial<Pick<...>>` in the type check block for the template as described here: https://blog.angularindepth.com/type-checking-templates-in-angular-viewengine-and-ivy-77f8536359f5

`Partial<...>` causes each property to be made optional, which in effect adds `undefined` to the type of each property as well, as described in the TypeScript docs: `Optional parameters and properties automatically have undefined added to their types, even when their type annotations don’t specifically include undefined.`. (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#optional-parameters-and-properties)

So, what seems to be happening is the Ivy compiler is adding `undefined` to the type of every input when considering the bindings, which means it will never complain about passing `undefined` to the input of any component. That really makes `strictNullChecks` a lot less useful.

Please understand that although nobody in practice would probably pass a hardcoded `undefined` to a component input, this is an actual problem any time you use `undefined` to represent the absence of a value being passed to a component. In my case, I have a store I subscribe to using the `async` pipe, and then some of the state gets passed into child components from there. Various properties on my state have types like `SomeModel | undefined`. `undefined` could mean the model is not yet loaded, for example. Although some people may use `null` instead, there seems to be a significant group that prefers to use `undefined` in all cases. Wherever you fall on that debate, my point is that this definitely comes into play in real projects, and in fact I'm having the issue after switching to Ivy in my own project. I can't have a lot of confidence in what I'm passing to my components' inputs if `undefined` is always allowed by the compiler regardless of the actual type of the inputs.

## 🔬 Minimal Reproduction

https://github.com/compeek/angular-ivy-input-undefined-issue

If you compile this project, you should only see a compiler error about `null` and not about `undefined` as well. See `index.html` for some more explanation of the example.

You can reproduce this easily in any project with `strictNullChecks` turned on and the Ivy compiler enabled with these two components (from my minimal reproduction project):

```
@Component({
  selector: 'app-root',
  template: `<app-child [stringOnlyInput1]="thisPropertyIsUndefined" [stringOnlyInput2]="thisPropertyIsNull"></app-child>`
})
export class AppComponent {
  thisPropertyIsUndefined: undefined = undefined;
  thisPropertyIsNull: null = null;
}

@Component({
  selector: 'app-child',
  template: `
    {{ 'stringOnlyInput1: ' + stringOnlyInput1 }}
    <br>
    {{ 'stringOnlyInput2: ' + stringOnlyInput2 }}
  `
})
export class ChildComponent {
  @Input() stringOnlyInput1: string = '';
  @Input() stringOnlyInput2: string = '';
}
```

The compiler should complain about the values passed to both inputs, but in fact it only complains about the `null` value and not `undefined`.

## 🔥 Exception or Error

I would expect an error like:
`Type 'undefined' is not assignable to type 'string'.`

But none is thrown.

And in fact if you do it with `null`, the error looks like this:
`Type 'null' is not assignable to type 'string | undefined'.`

Notice how it says it's not assignable to `string | undefined` even though the input type is just `string`.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.0-next.4
Node: 10.16.3
OS: win32 x64
Angular: 9.0.0-next.6
... animations, common, compiler, compiler-cli, core
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.4
@angular-devkit/build-angular     0.900.0-next.4
@angular-devkit/build-optimizer   0.900.0-next.4
@angular-devkit/build-webpack     0.900.0-next.4
@angular-devkit/core              9.0.0-next.4
@angular-devkit/schematics        9.0.0-next.4
@angular/cli                      9.0.0-next.4
@ngtools/webpack                  9.0.0-next.4
@schematics/angular               9.0.0-next.4
@schematics/update                0.900.0-next.4
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.3
</code></pre>

**Anything else relevant?**

**Comment by alxhub** [comment]
This is https://angular-team.atlassian.net/browse/FW-1606. @JoostK has a fix :)

**Comment by compeek** [comment]
> This is https://angular-team.atlassian.net/browse/FW-1606. Joost Koehoorn has a fix :)

Unfortunately I do not have access to that so I'm not sure what you're referencing. :( However if there's a fix, that's great! Any idea when it will be shipped?

**Comment by JoostK** [comment]
@compeek the idea is that we will remove the `Partial` mapped type and instead ensure to generate all possible inputs in the object literal, where any input that is not used is set to `null as any`. This achieves the same goal of allowing not all inputs to be present, without undesirably introducing `undefined` for all inputs.

Expect a PR to be out later this week.

**Comment by compeek** [comment]
When you say `any input that is not used is set to null as any`, do you mean that any input not specified in the template will automatically get a value of `null` passed to it? If so, wouldn't they override any default values set on those input properties?

**Comment by JoostK** [comment]
Oh these changes will all be in the generated code that's used for type checking, which will never actually execute. The generated code that the compiler generates for runtime execution will not be affected.

**Comment by compeek** [comment]
Oh, I see now. Excellent. Thank you for the information! I look forward to this fix coming out in a "next" release.
