### ISSUE TITLE
Identifier 'value' is not defined. 'T' does not contain such a member Angular

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#32692]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
Language Service
 "@angular/language-service": "~8.1.2",

### Is this a regression?
No idea

### Description
Getting this intelliSense error, When i am using nested or for loop with keyvalue pipe
Identifier 'value' is not defined. 'T' does not contain such a member Angular

## 🔬 Minimal Reproduction

loop nested object with keyvalue pipe example:
```
 <div *ngFor="let item of dashboardSectionDetails.DashBoardData | keyvalue | slice : 0:6" class="col-md-2 padding-0 border-style content--row-1__col-1--firstsection__col-1">
                                <div class="custom-firstsection-item">
                                    <div class="row content--row-1__col-1--firstsection__col-1__header">{{item.key}}
                                    </div>
                                    <div class="row content--row-1__col-1--firstsection__col-1__body">{{item.value}}</div>
                                </div>
                            </div> 
```

## 🔥 Exception or Error
<pre><code>
Identifier 'value' is not defined. 'T' does not contain such a memberAngular
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.2
Node: 10.16.0
OS: win32 x64
Angular: 8.1.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.2
@angular-devkit/build-angular     0.801.2
@angular-devkit/build-optimizer   0.801.2
@angular-devkit/build-webpack     0.801.2
@angular-devkit/core              8.1.2
@angular-devkit/schematics        8.1.2
@angular/cdk                      8.1.1
@angular/cli                      8.1.2
@angular/material                 8.1.1
@ngtools/webpack                  8.1.2
@schematics/angular               8.1.2
@schematics/update                0.801.2
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2

</code></pre>

**Anything else relevant?**

Screenshot:
![image](https://user-images.githubusercontent.com/23274631/64936956-0ef21f00-d876-11e9-8cb4-9059262fee3f.png)

**Comment by geromegrignon** [comment]
Please provide more informations about the dashboardSectionDetails.DashBoardData model.

**Comment by indraraj26** [comment]
Hi @geromegrignon , I have not made any model or interface for object, but it should not throw any intellisense error in vscode.

This is what i am getting from backend in dashboardSectionDetails.
DashBoardData: {
power-v: "13.60400021312"
}

**Comment by geromegrignon** [comment]
You can't read 'item.value' as DashboardData has no 'value' property. You need to replace it by 'item.power-v'.

Please close this issue.

**Comment by indraraj26** [comment]
I am using keyvalue pipe there i don't  need to read key with item.power-v. btw already Andrew tag this issue with Lang service.

**Comment by geromegrignon** [comment]
You are right, i missread.

**Comment by atscott** [comment]
Thanks for reporting this issue. I wasn't able to reproduce this locally so it must fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

Note: The type of `item` in the `ngFor` template context here is `any` at the moment. We are currently developing the Language Service for Ivy and I verified locally that the more narrow type type `KeyValue<string, string>` will be produced  when `strictTemplates` is enabled in the `tsconfig.json`
