### ISSUE TITLE
search  more then 2000 data in dropdown angualr is very slow ..  search content

### ISSUE THREAD

**Issue by rsurendraidexcel** [angular/angular#32700]
this my screen:
[
![Interface_my](https://user-images.githubusercontent.com/7713535/64974164-eb58c400-d8c9-11e9-9c7b-aa5c0de0ceaa.png)

While search   its stocking unwanted event fire on console 
![search_data](https://user-images.githubusercontent.com/7713535/64974249-0fb4a080-d8ca-11e9-9b49-5a07951a2ca3.png)

# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mlc-mlapis** [comment]
@rsurendraidexcel It's undoubtedly wrong logic if you want to show more then 2000 items in such a place. You probably need to implement some auto-complete component which offers a reduced list of items on the base the first three characters or so.
