### ISSUE TITLE
Unable to resolve @angular/core module when there is a symlinked package

### ISSUE THREAD

**Issue by Fatme** [angular/angular#32705]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [x] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

No

### Description

In case we have an application with symlinked typescript package (a typescript project that is required locally from another folder), `ERROR in Could not resolve module @angular/core` error is thrown. This happens when the symlinked package is added as first element in files property in `tsconfig.app.json` file [as shown here in demo app](https://github.com/Fatme/testApp/blob/2132f14ee2222a2d8d79fbf3b0513d18f04cf06c/tsconfig.app.json#L8).

It seems that `@angular/core` module is required in source code [here](https://github.com/angular/angular/blob/ec4381dd401f03bded652665b047b6b90f2b425f/packages/compiler-cli/src/transformers/program.ts#L562) in order to resolve all decorated elements from source file. It seems that `@angular/core` is searched for as a dependency relatively to the [first included source file](https://github.com/angular/angular/blob/3166cffd28e12d882bef3e55472e0a50f4cfc6f5/packages/compiler-cli/src/transformers/compiler_host.ts#L192). Source files are gettered based on `tsconfig.json` file and mainly on `files`, `include` and `exclude` properties. However, in our particular case when there is a symlinked package, it matters if `@angular/core` will be searched for relatively to the symlinked package or relatively to the application as `@angular/core` is dependency in the application but it is not dependency of the symlinked package.

The comment [here](https://github.com/angular/angular/blob/3166cffd28e12d882bef3e55472e0a50f4cfc6f5/packages/compiler-cli/src/transformers/compiler_host.ts#L191) says that any containing file gives the same result for absolute imports. As we can see, there are situations when the order of the imported files affects the final result:
* when file outside of the application is first element in files property in `tsconfig.app.json` file -> it is not possible to resolve `@angular/core`
* when file from application is first element in files property in `tsconfig.app.json` file -> `@angular/core` is resolved correctly

It seems that getting the first source file as containing folder is not the correct decision, maybe all files should be checked until `@angular/core` is found.

## 🔬 Minimal Reproduction

1. git clone https://github.com/Fatme/symlinkedPlugin
2. git clone https://github.com/Fatme/testApp
3. cd symlinkedPlugin
4. `npm i`
5. cd ../testApp
6. `npm i`
7. `ng serve`

> NOTE: If you change the order of files [here](https://github.com/Fatme/testApp/blob/master/tsconfig.app.json#L8) and `main.ts` is the first file, the issue will not reproduce.

## 🔥 Exception or Error
<pre><code>
ERROR in Could not resolve module @angular/core

</code></pre>

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.4
Node: 10.13.0
OS: darwin x64
Angular: 8.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.4
@angular-devkit/build-angular     0.803.4
@angular-devkit/build-optimizer   0.803.4
@angular-devkit/build-webpack     0.803.4
@angular-devkit/core              8.3.4
@angular-devkit/schematics        8.3.4
@angular/cli                      8.3.4
@ngtools/webpack                  8.3.4
@schematics/angular               8.3.4
@schematics/update                0.803.4
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Comment by alxhub** [comment]
I have good news and bad news!

The good news is that this issue _should_ be fixed by Ivy, which doesn't depend on identifying specific Angular decorator declarations.

The bad news is that it's still an unsupported use case - we don't specifically test symlinked or `npm link`ed `node_modules` at all, so you might still run into some turbulence.

**Comment by alxhub** [comment]
Closing as Ivy is released in Angular 9!
