### ISSUE TITLE
PLATFORM_ID injection into custom decorators

### ISSUE THREAD

**Issue by kovaletsyurii** [angular/angular#32713]
Hi All! I just want to ask how to Inject PLATFORM_ID into my custom decorator? 
For example, I use angular universal and I need to execute some methods in class only if platform is browser, then I write decorator RunOnlyInBrowser:
``` 
function RunOnlyInBrowser(target: any, name: string, descriptor: PropertyDescriptor){
    const method = descriptor.value;
    descriptor.value = function(...args) {
      if(isServer) { //here I need to use isPlatformBrowser(platform_id)
        return;
      }
      method.apply(this, args);
    };
  }
}
```

and apply this decorator to method in class:
```
...

@RunOnlyInBrowser
itsClientMethod(){
    console.log('hello world');
}
...
```

but I don't find ways to use PLATFORM_ID inside my decorator.

**Comment by codewithdhiman** [comment]
You can write a static injector property to that specific component.

@Component({
 ...
})
export MyComponent implements OnInit {
    injector: Injector;
   constructor (injector: Injector) {}
}

So, when you need platform id to any method to this component, you can grab it like 

isPlatformBrowser(MyComponent.injector.get(PLATFORM_ID))

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
