### ISSUE TITLE
extending/ reusing components html template

### ISSUE THREAD

**Issue by andreElrico** [angular/angular#32714]
Hey there are some SO questions on that issue but nothing answers my question.

# 🚀 feature request

Let's say two components **C1** and **C2** are 90% identital in their class and **template**.

For components classes we can refactor the **Common code** into a base-class and then extend  **C1** and **C2**.

We don't have such a thing for HTML-templates.

It should work something like this:

**baseTemplate.html** (file)
```
<!-- common html goes in this file -->
```
and then

**C1.html** (file)
```
<span>I'm C1<\span>
ngCompilerIncludeHTML('path/baseTemplate.html')
<span>I'm still C1<\span>
```
and

**C2.html** (file)
```
<span>I'm now C2<\span>
ngCompilerIncludeHTML('path/baseTemplate.html')
<span>I'm still C2<\span>
```
### Description
I of course see a few problems.

+ How do we get lintable type/ error/ checking/ suggestions in **baseTemplate.html** while developing in our IDE.
+ How do we get lintable type/ error/ checking/ suggestions in **C1** and **C2** while developing in our IDE.
We would need some sort of parsed HTML preview.

Something like for **C1**:
```
<span>I'm C1<\span>
ngCompilerIncludeHTML('path/baseTemplate.html') {
   <!-- common html goes in this file -->
}
<span>I'm still C1<\span>
```
Not sure how we can live manipulate our **C1.html** file when **baseTemplate.html** changes.
Not sure if that's even possible.

Any suggestions?

### How do the best of best deal with this situation ?
**ng-template** can only be reused inside one single component as far as I know.

**Comment by andreElrico** [comment]
references:
+ https://github.com/angular/angular/issues/13981

**Comment by pkozlowski-opensource** [comment]
The recommended way to go here would be to create a dedicated component that has your `<!-- common html goes in this file -->`. It has several advantages:
* you can actually _name_ the common part and manage inputs / outputs;
* there is no need to modify the framework, introduce new concepts etc.

Component's composition should be the way to go, I don't think we want to support "template inheritance". 

What would be a set of practical problems that would prevent you from going down the "component's composition" path?

**Comment by andreElrico** [comment]
Well in my special case its: (a little simplified of course)

**C1** is a mat-table with lets say 3 cols.
**C2** is the the same table and ONE additonal column with mat-checkboxes.

My final goal is to build a library with C1 and C2 where the mat-checkboxes will be treeshaked when  only **C1** is used in the app. Since **C1** does NOT CALL the checkboxes.

My current workaround is to project the checkboxes from C2 to C1 into a placeholder column that is not present when C1 is rendered normally.

This might work in my case but there are cases where the above would come in handy.

**Comment by alxhub** [comment]
I'm going to close this request as something we're not going to be able to support any better, at least for the foreseeable future. However! This pattern does work:

```typescript
export const COMMON_HTML = `<h2>This is the common HTML.</h2>`;

@Component({
  template: `
    <h1>This is component one!</h1>
    ${COMMON_HTML}
  `,
  selector: 'cmp-one',
})
export class CmpOne {}

@Component({
  template: `
    <h1>This is component two!</h1>
    ${COMMON_HTML}
  `,
  selector: 'cmp-two',
})
export class CmpTwo {}
```

It'll even work if `COMMON_HTML` is imported from another file!
