### ISSUE TITLE
Angular Material Datepicker issue when using Dutch language

### ISSUE THREAD

**Issue by harangusdan** [angular/angular#32711]
I want to use multiple languages for the Material Datepicker. I use the setLocale method from DateAdapter but it generates an inconsistency regarding the display of the days of week. In the Dutch version, Monday is considered as week-end day and it is disabled by my week-end days filter. Also, the days of week in Dutch are displayed with starting lowercase. 

<img width="295" alt="Screenshot 2019-09-17 at 10 12 21" src="https://user-images.githubusercontent.com/55430168/65019338-aff2df80-d933-11e9-81f6-b83daa81740e.png">
<img width="256" alt="Screenshot 2019-09-17 at 09 57 17" src="https://user-images.githubusercontent.com/55430168/65019165-5c809180-d933-11e9-924a-9622c4b9d60c.png">
<img width="254" alt="Screenshot 2019-09-17 at 09 58 12" src="https://user-images.githubusercontent.com/55430168/65019182-61dddc00-d933-11e9-9979-6e320deffd31.png">

**Comment by pkozlowski-opensource** [comment]
Please report in https://github.com/angular/components
