### ISSUE TITLE
ivy AoT build with fullTemplateTypeCheck enabled never completes

### ISSUE THREAD

**Issue by mattlewis92** [angular/angular#32717]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler

### Is this a regression?
It works without ivy

### Description
When `fullTemplateTypeCheck` is enabled on our project with ivy the build never completes, I left it for over an hour and it still never finished. If I disable `fullTemplateTypeCheck` then the build completes in ~14 minutes. Disabling that flag or disabling ivy and everything works as normal. Maybe it's to do with the size of our application?

## 🔬 Minimal Reproduction
I'm not able to provide one as I think it's related to the size of our application. I can either give an angular team member access or if someone can point me to the best place to look to try and find the issue, then I can do that.

## 🔥 Exception or Error
There is none, the AoT build just never completes.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-next.4
Node: 12.6.0
OS: darwin x64
Angular: 9.0.0-next.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.4
@angular-devkit/build-angular     0.900.0-next.4
@angular-devkit/build-optimizer   0.900.0-next.4
@angular-devkit/build-webpack     0.900.0-next.4
@angular-devkit/core              8.2.0
@angular-devkit/schematics        8.2.0
@angular/cdk                      8.0.2
@angular/cli                      9.0.0-next.4
@angular/pwa                      0.802.0
@ngtools/webpack                  9.0.0-next.4
@schematics/angular               8.2.0
@schematics/update                0.900.0-next.4
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.3
</code></pre>

**Anything else relevant?**
I'm running it on node 12 with the flag `--max_old_space_size=8192`

**Comment by alxhub** [comment]
That's weird. Can you reach out to devrel@angular.io and we can look into your specific application?

Thanks,
Alex

**Comment by Splaktar** [comment]
Can you give the full command that you are running?

You don't get a heap or out of memory error?

**Comment by mattlewis92** [comment]
Just the standard build command with the node memory limit increased:
```
node --max_old_space_size=8192 node_modules/.bin/ng build --configuration=staging --prod
```

**Comment by Splaktar** [comment]
Is it still happening with CLI `9.0.0-next.8` and Angular `9.0.0-next.10`? There were some memory optimizations put in place (but the issue may not be fully resolved).

**Comment by mattlewis92** [comment]
Yeah I've been trying every beta release as it comes out and it's still an issue

**Comment by mattlewis92** [comment]
Closing in favour of https://github.com/angular/angular/issues/33532 (I finally found a minimal repro)
