### ISSUE TITLE
Building docs behind proxy fails- saucelabs.com unreachable

### ISSUE THREAD

**Issue by umdstu** [angular/angular#32722]
# 🐞 bug report

### Affected Package
angular/angular/aio

### Is this a regression?
Unknown, but unlikely.

### Description
When behind a proxy (using proxy's set for npmjs.org and yarnpkg.com). attempting to build the docs for offline viewing fails.

If you comment out the saucelabs entry in `package.json`, it makes some further progress, until it fails again due to beling offline, as it also cannot connect to googleapis.com for the webdriver-manager/selenium.

## 🔬 Minimal Reproduction
Block access to npmjs.org and yarnpkg.com. Configure proxies for both, then attempt to install. It will fail because it cannot reach saucelabs.com.

## 🔥 Exception or Error
<pre><code>
error An unexpected error occurred: "https://saucelabs.com/downloads/sc-4.5.1-linux.tar.gz: getaddrinfo ENOTFOUND saucelabs.com".
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
N/A
</code></pre>

**Anything else relevant?**
N/A

**Comment by gkalpak** [comment]
@umdstu, not sure what we can do about it. We have some dependencies that we need to get from different places. There is no getting around that 🤔

If you know what you are doing, you can work around this (if you do not intend to use those dependencies). E.g. you can comment out `sauce-connect` in `package.json` (as you did) and remove the `webdriver-manager update` call in `postinstall`.

But I don't think there is something to fix here. I am going to close the issue, but feel free to continue the discussion below.

**Comment by umdstu** [comment]
Would you mind if we leaved this open while I work through building this 'offline' and see if there are places that could updated to be more 'offline' friendly? If not, I suppose I could create separate tickets for each.

eg. the tools/examples/shared directory makes use of `in-memory-web-api-bazel` package, directly in Github, rather than a yarn or npm module. Any way this could be published and configured to use a non-github source?
