### ISSUE TITLE
Structural assertions for component nesting

### ISSUE THREAD

**Issue by tbosch** [angular/angular#3272]
## Gloal

HTML parsers know that inside of a `<select>` only `<option>` elements are allowed. We should have something similar for angular components. This would prevent user errors like "Why can't I see element xzy?" and would also allow nice tooling support (e.g. auto completion for child elements in the template editor).

## Proposal

Add assertions around `<ng-content>`:

1. If there are elements / non whitespace text in the light dom of an Angular component that is not projected, throw (see #3254). 
2. Support attributes `select-min` and `select-max` on `<ng-content>` to allow to define how many elements should be projected by the given `<ng-content>`.

Note: This is only possible as we do the content projection already during compilation, i.e. we know which elements are projected into which `<ng-content>`.

## Examples

Tab component that requires exactly one child `<label>` element and one child `<body>` element:

```
@Component({selector: 'tab'})
@View({
  template: `
  Label: <ng-content select="tab-label" select-min="1" select-max="1"></ng-content>
  Body: <ng-content select="tab-body" select-min="1" select-max="1"></ng-content>
`
})
class Tab {}

Usage:
<tab>
  <tab-label>some label</tab-label>
  <tab-body>hello</tab-body>
</tab>

These usages would be detected as errors:
<tab></tab>

<tab>hello</tab>

<tab>
  <tab-label>some label</tab-label>
</tab>
```

**Comment by tbosch** [comment]
@mhevery Let's talk about this...

**Comment by TiagoBraga39** [comment]
Just wondering...
Why do inside HTML and Components are deleted after the rendering of the outside component?
Example:
```html
<outside-cmp>
     <p>Some text</p>
     <inside-cmp></inside-cmp>
</outside-cmp>
```
After the compiling of the "outside-cmp", all the inside is gone.
To avoid it, we should use the "ng-content" (as far as I am concerned).
<b>Why not the opposite?</b>
If I need the inside to disappear, I should explicitly say that.

Best regards,
Tiago Braga

**Comment by tbosch** [comment]
@TiagoBraga39: An angular component defines a template via `@View()`. The semantics of this is that this view defines the children of the component. 

How should elements directly below the `<outside-cmp>` be ordered relative to the elements from the template in `@View`?

Our behavior here is also similar to how ShadowDom works: Whenever you have a shadow root, all elements that are direct children of an element are not visible any more.

**Comment by tbosch** [comment]
We should do this early as this can affect many components...

**Comment by tbosch** [comment]
Note: if a `<ng-content>` is inside of an `ng-if`/... it becomes optional

**Comment by tbosch** [comment]
Special case: directives that don't need a DOM node could be allowed in the light dom without being projected...

**Comment by tbosch** [comment]
Closing this for now. Let's resurrect this when we really want it.
