### ISSUE TITLE
Importing .js file breaks dependancy injection

### ISSUE THREAD

**Issue by Vallerious** [angular/angular#32723]
# 🐞 bug report

### Affected Package

 I cannot say for sure, but it might be @angular/compiler v. "~8.2.5".

### Is this a regression?

 No, I can see the same behaviour in Angular 7. But in Angular 5 I noticed something different - the DI container was not recognising the .js import as valid provider.

### Description

 Unexpected behaviour when a typescript file is imported with extension '.js'. The compiler does not complain, VS Code is happy with the import, DI does not error as in Angular 5 but instead treats the service as a new DI entry.
The compiler should not allow importing not existing files or at least the '.js' extension should be ignored and therefore the DI container should work fine.
I spent one hour debugging this, but if the compiler warned me that time could be used working on the actual app.

To test this I created one service that is shared between components and provided it as a singleton by setting 'providedIn': 'root'. In one component I imported the service without extension (.ts is assumed) and in the other component I imported it with '.js' extension. Everything seems to work, no errors, but two instances of the service are created.

## 🔬 Minimal Reproduction

 https://github.com/Vallerious/test-ang-module

## 🔥 Exception or Error
<pre><code>

Nothing, but there should be
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

 
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.4
@angular-devkit/build-angular     0.803.4
@angular-devkit/build-optimizer   0.803.4
@angular-devkit/build-webpack     0.803.4
@angular-devkit/core              8.3.4
@angular-devkit/schematics        8.3.4
@angular/cli                      8.3.4
@ngtools/webpack                  8.3.4
@schematics/angular               8.3.4
@schematics/update                0.803.4
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

My node version is: 10.16.3

**Comment by alxhub** [comment]
This is not an Angular problem, but is related to the bundler seeing two different import paths that _happen to_ resolve to the same file. Thus, you get two distinct copies of the service in your app. This is working as intended. My advice would be to refrain from using any extensions in your import statements.

**Comment by Vallerious** [comment]
I do not think someone intended it to work like that, because it does not make sense.
There is no file called xxx.js so the bundler should respond saying that the import is impossible.
