### ISSUE TITLE
Hi , i want to help adding Spanish language to angular.io

### ISSUE THREAD

**Issue by AntonioCardenas** [angular/angular#32724]
# 📚 Docs or angular.io bug report

### Description
I have a few questions 
First: in what directory is the archives of website
Second : the website use i18n ngx traslate or how use multiple lenguajes 
Third: the language in Spanish would be angular.es 
### What's the affected URL?**
!https://angular.io/...
Thanks I hope to contribute

**Comment by kapunahelewong** [comment]
Hi @AntonioCardenas, thanks for this! 

Regarding your questions, I can only answer the first one. 

Here is where you'll spend most of your time doing docs: 
In general: https://github.com/angular/angular/tree/master/aio/content
The guides (mostly): https://github.com/angular/angular/tree/master/aio/content/guide
The example apps: https://github.com/angular/angular/tree/master/aio/content/examples

For the others, I'm finding the right people for you to talk to. I'll be back with more info. :)

**Comment by AntonioCardenas** [comment]
Thanks @kapunahelewong , i will get in touch with @alvarocamillont , and update and pull request the existing repository

**Comment by alvarocamillont** [comment]
@AntonioCardenas you can count on me to help you! I am also starting the translation project and I believe we can learn a lot together! You can find me on all social networks with @alvarocamillont!
Here we go! ¡Aquí vamos! Vamos nessa! 行こう！

**Comment by luisejrobles** [comment]
@alvarocamillont  @AntonioCardenas  I would love to help translating the docs!
 can I join you? :smile:

**Comment by alvarocamillont** [comment]
Great to know!

**Comment by AntonioCardenas** [comment]
yes @luisejrobles you're welcome

**Comment by luisejrobles** [comment]
I tried to get assigned to an issue at [angular-es](https://github.com/angular/angular-es/issues/31) but I was said the project is discontinued

**Comment by kapunahelewong** [comment]
@luisejrobles, generally, anyone can fork the docs and run their own site with their own version of them if they want. It may be that whoever had worked on it previously didn't continue, but anyone can start it up again. :)
