### ISSUE TITLE
Angular elements throws error when an element is consumed by root app and another element

### ISSUE THREAD

**Issue by SantiagoIlli** [angular/angular#32726]
# 🐞 bug report

### Affected Package

The issue may be caused by package @angular/core

### Description
If i make an app1 with angular elements, and export this app1 to use those elements in another app it works just fine.

The problem is when I want to make a second app2 with elements (to export more complex elements), which also uses elements from my app1 as external elements, and use both app1 and app2 as external elements in a third app3.

If in my app3, i just use elements from app1, or just from app2 it works just fine.
But when i use both it throws the following error:

Error: Failed to execute 'define' on 'CustomElementRegistry': the name "blue-element" has already been used with this registry

## 🔬 Minimal Reproduction

I made this two based on [the article made by Tomas Trajan](https://medium.com/@tomastrajan/the-best-way-to-lazy-load-angular-elements-97a51a5c2007)

first app exported:
https://github.com/SantiagoIlli/simple-angular-element

this one exports blue-element (a very simple angular element)

second app exported:
https://github.com/SantiagoIlli/complex-angular-element

this one exports orange-with-blue-inside  (is a simple angular element that use blue-element in it)

You can see the error in this stackblitz:

https://stackblitz.com/edit/angular-qwrhdz

These are two repos to show how did I create the apps to export as external elements.

Notice that if blue-element is used and orange-with blue is not used, works fine. If orange-with-blue is used and blue-element is not used, it also works fine.
The problem is when i try to use both of them.

## 🔥 Exception or Error
<pre><code>

Error: Failed to execute 'define' on 'CustomElementRegistry': the name "blue-element" has already been used with this registry
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.4
Node: 10.15.3
OS: win32 x64
Angular: 8.2.6
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.4
@angular-devkit/build-angular     0.803.4
@angular-devkit/build-optimizer   0.803.4
@angular-devkit/build-webpack     0.803.4
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@angular/cdk                      8.2.0
@angular/cli                      8.3.4
@angular/flex-layout              8.0.0-beta.27
@ngtools/webpack                  8.3.4
@schematics/angular               8.0.0
@schematics/update                0.803.4
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/23732#issuecomment-388670907

**Comment by SantiagoIlli** [comment]
Thanks for answer so fast!

I already saw that issue, and that comment, but it's from more than a year ago, and it says: 
"Again, we're working to enable this use case for v7, so I'm going to close this (as its not actually an issue with Angular core)"

That issue was closed, and we are almoust in v9, i tried to find more info about the problem, but with no succes.

**Comment by eafiontzi** [comment]
Hello all, have the same issue with @SantiagoIlli and #33619, created a web component with Angular 8 using custom elements and want to use it inside my main angular application. I get the "DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "my-element" has already been used with this registry".

I tried many different approaches proposed without much luck. Did someone manage to get past this error? Thank you very much in advance.

**Comment by eafiontzi** [comment]
Hello again, @SantiagoIlli I finally managed to remove the error by following [this ](https://medium.com/@sri1980/multiple-angular-elements-apps-loading-in-one-window-7bcc95887ff4) article. Though I do not have multiple elements, it suppressed the error. Hope it helps you too.

**Comment by SantiagoIlli** [comment]
Hi @eafiontzi 

Thanks for sharing the article. 

Unfortunately as you mention the use case it's different cause i have multiple elements. I gave it a try, but i couldn't manage to make it work with multiple elements.

**Comment by gkalpak** [comment]
This is essentially the same as #36028. Let's track this usecase in #36028, so we have a single point of reference.
