### ISSUE TITLE
Show Custom popup message on windowbeforeunload event in angular 8 

### ISSUE THREAD

**Issue by rajgsdei** [angular/angular#32737]
Oh hi there! 😄 

I want to show a custom message or popup if there is any changes in form. For this purpose I am using addEventListener('beforeunload') event in ### Angular 8. But I am getting the default message of windowUnload as "Changes that you made may not be saved". Please help me out with this.
Is there any relevant package for the same or is there any way to achieve this in **Angular 8**

**Comment by santoshyadav198613** [comment]
Hey @rajgsdei,
This can be achieved using candeactivate hook, would suggest to raise this on stackoverflow. As this is not Angular framework issue.

**Comment by rajgsdei** [comment]
> Hey @rajgsdei,
> This can be achieved using candeactivate hook, would suggest to raise this on stackoverflow. As this is not Angular framework issue.

Candeactivate calls only when there is route change I want to show custom popup or custom message on refresh

**Comment by santoshyadav198613** [comment]
> > Hey @rajgsdei,
> > This can be achieved using candeactivate hook, would suggest to raise this on stackoverflow. As this is not Angular framework issue.
> 
> Candeactivate calls only when there is route change I want to show custom popup or custom message on refresh

Ok, check on stackoverflow community there will help you, we don't take any support issues here.

**Comment by mlc-mlapis** [comment]
@rajgsdei It's a part of general browsers API. It's very, very limited and because of security factors practically unusable for some advanced custom messages. Each browser implements it even a bit differently. You have to live without it.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by rajgsdei** [comment]
There should be someway around for this, there are many questions over the internet regarding the same issue but no one has appropriate explanation to that. If we can show custom popup for CanDeactivate guard functionality then this functionality should also be there in the case of refresh page. Because sometimes when user enters data and if by mistake if user hits f5 then all of user's data will be gone so there should be proper way for the same. Browser's default popup will not make it in sync, because it shows different messages on different browsers. Atleast there should be the same returned message for every browser.

**Comment by mlc-mlapis** [comment]
@rajgsdei No, it's technically not possible at all. There no hook you can use in some more advanced level from any JS. Simply pressing F5 or closing the windows means that the browser does it and you can't do anything more from your JS. The reason is security, and that's why browsers don't offer any advanced API for JS. Just the primitive and limited one which already exists around `beforeunload` hook.
