### ISSUE TITLE
ngOnInit() {   this.route.paramMap.subscribe(params => {     this.product = products[+params.get('productId')];   }); }

### ISSUE THREAD

**Issue by x001xx** [angular/angular#32730]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Anything else relevant?

![9fd7001d-573d-4bf6-a70a-9946f3684427](https://user-images.githubusercontent.com/53470529/65081165-adcc6780-d9ab-11e9-8aec-8f1047d881a2.jpg)
![21210f87-d716-4caa-b2cd-46fc257eff7f](https://user-images.githubusercontent.com/53470529/65081166-adcc6780-d9ab-11e9-84dd-ba9bb8971fdc.jpg)

**Comment by x001xx** [comment]
не хватает одного знака

**Comment by AndrewKushnir** [comment]
Hi @x001xx,

It looks like this issue doesn't contain enough information to understand the problem, so I'm closing it.

Could you please create a new ticket by following a template and provide the necessary info, so we can have a look?

Thank you.
