### ISSUE TITLE
Unit test for pipe on next.handle()

### ISSUE THREAD

**Issue by bhawin-boom** [angular/angular#32738]
Hi  , 

I have a code which i like very difficult to unit test for me .

Can anypone help me with this one how to code cover the .pipe and map and return the http response .

`
intercept(
    req: HttpRequest<any>,
    next: HttpHandler
  ): Observable<HttpEvent<any>> {

    try {
      this.loggedOnUser = this.tokenManagementService.getAuthToken();
      req = req.clone({
        headers: new HttpHeaders({
          'authorization': 'Bearer ' + this.token,
          'Cache-Control': 'no-cache',
          'Pragma': 'no-cache',
          'Expires': new Date().toISOString(),
          'accept': 'application/json',
          'Content-Type': 'application/json',
          'x-ibm-client-id': 'b405e650-e823-46ad-8453-7459b423d4b2'
        })
      });
      return next.handle(req).pipe(
        map((event: HttpEvent<any>) => {
          if (event instanceof HttpResponse) {
            if (event.url.indexOf('financeandprocurementmanagement') > -1) {
              const resultCode = event.body.codesDefined.resultsSet.resultCode;
              if (['R02', 'R04', 'R05', 'U0'].indexOf(resultCode) > -1) {
                this.router.navigate(['/system-error']);
                this.dashboardService.setRouteParams('header');
              }
            }
            if (event.url.indexOf('cashoperations') > -1) {
              const resultCode = event.body.codesDefined ? event.body.codesDefined.resultsSet.resultCode : event.body.resultsSet.resultCode;
              if (['E01'].indexOf(resultCode) > -1) {
                this.router.navigate(['/system-error']);
                this.dashboardService.setRouteParams('header');
              }
            }
          }
          return event;
        }),
        catchError((error: HttpErrorResponse) => {
          if (error.status > 299) {
            if (error.status === 403) {
              localStorage.removeItem('Authorization');
              this.dashboardService.setIsLogout(true);
              this.router.navigate(['/logout']);
            } else {
              this.router.navigate(['/system-error']);
              this.dashboardService.setRouteParams('header');
            }
          }
          // let data = {};
          // data = {
          //   reason: error && error.error.reason ? error.error.reason : '',
          //   status: error.status
          // };
          return throwError(error);
        }));

    } catch (e) {
      this.handleAuthError(e);
    }
  }
`

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
