### ISSUE TITLE
Define style encapsulation for components in `@View` annotation

### ISSUE THREAD

**Issue by tbosch** [angular/angular#3273]
## Goal

Right now, components contain all of the configuration that the compiler needs to analyze them in the `@Component` or `@View` annotation. However, the way we do style encapsulation is defined globally for all components via the `ShadowDomStrategy`. This can easily break the reuse of a component in other projects if the component expects style encapsulation but the using application disables style encapsulation.

## Proposal

Add a `renderEncapsulation` field to the `@View` annotation with the values `null`, `native` or `emulated`. This seems to be verbose, but the solution is the same as for the `directives` array in `@View` (see #2844).

## Examples

```
@Component()
@View({
  encapsulation: ViewEncapsulation.EMULATED,
  styles: 'div {background: green}',
  template: '<div></div>'
})
class MyComponent {}
```

This component will work in any application and won't have the side effect of making _all_ `<div>`s green (which this component would have if the application used the `EmulatedUnscopedShadowDomStrategy` right now).

**Comment by tbosch** [comment]
@mhevery Let's talk about this...

**Comment by tbosch** [comment]
Blocked on #2844

**Comment by tbosch** [comment]
Note that this is important as it is a breaking change that can affect a lot of components.

**Comment by tbosch** [comment]
Closed via #3314 and 16e3d7e96efaf37f7523508ea7dc02f1f6336404

**Comment by rolandjitsu** [comment]
@tbosch node that this has not been documented anywhere in the  [CHANGELOG.md](https://github.com/angular/angular/blob/master/CHANGELOG.md). And it is a breaking change to those who were using `NativeShadowDomStrategy`.

**Comment by rolandjitsu** [comment]
@tbosch Also, if I set the `encapsulation` on the view to `ViewEncapsulation.NATIVE` and it is not supported in the browser is running, will it fallback to `ViewEncapsulation.EMULATED`?
