### ISSUE TITLE
In Internet Explorer My angular 6 project not opening

### ISSUE THREAD

**Issue by madhugrfeb** [angular/angular#32734]
My project is working fine in chrome browser, Firefox, even in edge, but not in  IE, I am not able to see my UI some image for reference,
![image](https://user-images.githubusercontent.com/43066620/65115066-1267e080-da05-11e9-91c6-e73096b6555f.png)

![image](https://user-images.githubusercontent.com/43066620/65115436-72f71d80-da05-11e9-9880-81bdabca39df.png)

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by AndrewKushnir** [comment]
Hi @madhugrfeb,

It looks like you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

Thank you.
