### ISSUE TITLE
Angular 8 -> Angular 9 breaks with ng2-charts

### ISSUE THREAD

**Issue by whyboris** [angular/angular#32748]
# 🐞 bug report

### Affected Package
`ng2-charts` https://github.com/valor-software/ng2-charts

### Is this a regression?
Angular 8.2.6 works
Angular 9.0.0-next.5 fails

### Description
Everything works as expected with 8.2.6
Upgrading to 9.0.0-next.5 fails to build (Ivy disabled, aot enabled)

## 🔬 Minimal Reproduction
I created a repository: https://github.com/whyboris/angular-ivy-problem-2

It was created with `npm install -g @angular/cli@next` and `ng new angular-ivy-problem-2` which runs. 

But simply adding `ng2-charts` fails compilation; see PR:
https://github.com/whyboris/angular-ivy-problem-2/pull/1/files

It is easy to fix, by simply downgrading from angular 9 to angular 8; see PR: 
https://github.com/whyboris/angular-ivy-problem-2/pull/2/files

Another fix is to upgrade from `ng2-charts` version `1.6.0` to latest (`2.3.0`), see PR:
https://github.com/whyboris/angular-ivy-problem-2/pull/3/files

## 🔥 Exception or Error
<pre><code>

ERROR in node_modules/ng2-charts/charts/charts.d.ts:53:22 - error TS-996002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

53 export declare class ChartsModule {
                        ~~~~~~~~~~~~
src/app/app.component.html:413:25 - error TS8002: 'ngSwitch' is not a valid property of <div>.

413   <div class="terminal" [ngSwitch]="selection.value">
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/app/app.component.ts:5:16
    5   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.
src/app/app.component.html:531:1 - error TS8001: 'router-outlet' is not a valid HTML element.

531 <router-outlet></router-outlet>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/app/app.component.ts:5:16
    5   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Failed to compile.
ℹ ｢wdm｣: Compiling...
95% emitting CopyPlugin    
    ERROR in node_modules/ng2-charts/charts/charts.d.ts(53,22): error TS-996002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class
    src/app/app.component.html(413,25): error TS8002: 'ngSwitch' is not a valid property of <div>.
    src/app/app.component.html(531,1): error TS8001: 'router-outlet' is not a valid HTML element.
</code></pre>


## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-next.4
Node: 12.10.0
OS: darwin x64
Angular: 9.0.0-next.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.4
@angular-devkit/build-angular     0.900.0-next.4
@angular-devkit/build-optimizer   0.900.0-next.4
@angular-devkit/build-webpack     0.900.0-next.4
@angular-devkit/core              9.0.0-next.4
@angular-devkit/schematics        9.0.0-next.4
@angular/cli                      9.0.0-next.4
@ngtools/webpack                  9.0.0-next.4
@schematics/angular               9.0.0-next.4
@schematics/update                0.900.0-next.4
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.3

</code></pre>

**Anything else relevant?**
Very similar to another issue I opened: https://github.com/angular/angular/issues/32729

I think it's acceptable to expect users of Angular to upgrade external libraries they use (e.g. `ng2-charts`), but I wanted to note this since the original intention behind _Angular 9_ was that it would work out of the box for all users with minimal changes 🤷‍♂ 

Please keep up the wonderful work ❤️ 🙇 I love working with Angular and with the Angular team (the few times I have interacted) 🙌

**Comment by fr0** [comment]
Maybe the same problem as https://github.com/angular/angular/issues/32078, which was fixed in `9.0.0-next.7`. You might try that version to see if the problem still occurs.

**Comment by whyboris** [comment]
thank you @fr0 -- I tried with the `9.0.0-next.7` (along with the latest `cli` versions and `rm -rf node_modules` and `npm install`) but the error is identical to before (same as `Exception or Error` above, pasting just the last 3 lines):

```
    ERROR in node_modules/ng2-charts/charts/charts.d.ts(53,22): error TS-996002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class
    src/app/app.component.html(413,25): error TS8002: 'ngSwitch' is not a valid property of <div>.
    src/app/app.component.html(531,1): error TS8001: 'router-outlet' is not a valid HTML element.
```

PR with the `next7` branch: https://github.com/whyboris/angular-ivy-problem-2/pull/4/files

**Comment by whyboris** [comment]
I think it's sensible for Angular to allow some outdated versions of libraries to become incompatible with new Angular releases 👌 

The solution here is simple: upgrade `ng2-charts` version `1.6.0 `to latest `2.3.0` 👌 

Please feel free to close the issue if you think there's nothing to learn about why Angular can not compile with the old version of a library 👌

**Comment by mhevery** [comment]
works with latest closing
