### ISSUE TITLE
Bazel and 9.0.0-next.7 breaks builds

### ISSUE THREAD

**Issue by fredrikredflag** [angular/angular#32766]
# 🐞 bug report

Using bazel and 9.0.0-next.7 seems to have a issues with compiling templates. 

### Description

Don't really know what the issue is other then the below exception.

But let's do some guessing.

1. Missing `ngsummary.json` files

There are two similar issues #28898 and #32055 both deals with missing `ngsummary.json` files. And yes these files are indeed missing. The reason for this seems to be the fact that ivy is now the default and no `ngsummary.json` files are created by `ngc` with the postinstall script (`ngc -p ./angular-metadata.tsconfig.json`). We can solve this by modifying `angular-metadata.tsconfig.json` to disable ivy: 
<pre><code>
"angularCompilerOptions": {
    "enableIvy": false
  }
</code></pre>

Now `ngsummary.json` files are created. 

Unfortunately this gives us another exception.
<pre><code>
Error: Could not resolve ./router.ngfactory from /home/broken/.cache/bazel/_bazel_broken/a989ca7319030786eb94b60dd781e6a5/execroot/project/external/npm/node_modules/@angular/router/router.d.ts
</code></pre>

Can't figure out why, `router.ngfactory.js` is indeed there. But maybe it want's a .ts?
Full stop. 

2. Ivy don't want/care about `ngsummary.json` files. 

Then i really don't know. Full stop.

## 🔬 Minimal Reproduction
<pre><code>
ng new --collection=@angular/bazel
ng update --next=true @angular/cli @angular/core
npm run start
</code></pre>

## 🔥 Exception or Error
<pre><code>

Error during template compile of 'AppRoutingModule'
  Function calls are not supported in decorators but 'RouterModule' was called.
Unexpected value 'undefined' imported by the module 'AppRoutingModule in /home/broken/.cache/bazel/_bazel_broken/a989ca7319030786eb94b60dd781e6a5/execroot/project/src/app/app-routing.module.ts'
Can't export value RouterModule in /home/broken/.cache/bazel/_bazel_broken/a989ca7319030786eb94b60dd781e6a5/execroot/project/external/npm/node_modules/@angular/router/router.d.ts from AppRoutingModule in /home/broken/.cache/bazel/_bazel_broken/a989ca7319030786eb94b60dd781e6a5/execroot/project/src/app/app-routing.module.ts as it was neither declared nor imported!
Unexpected value 'BrowserModule in /home/broken/.cache/bazel/_bazel_broken/a989ca7319030786eb94b60dd781e6a5/execroot/project/external/npm/node_modules/@angular/platform-browser/platform-browser.d.ts' imported by the module 'AppModule in /home/broken/.cache/bazel/_bazel_broken/a989ca7319030786eb94b60dd781e6a5/execroot/project/src/app/app.module.ts'. Please add a @NgModule annotation.
Error during template compile of 'AppRoutingModule'
  Function calls are not supported in decorators but 'RouterModule' was called.
'router-outlet' is not a known element:
1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<router-outlet>
{{title}} sda
</router-outlet>
")
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-next.5
Node: 10.16.0
OS: linux x64
Angular: 9.0.0-next.7
... animations, bazel, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.5
@angular-devkit/build-angular     0.900.0-next.5
@angular-devkit/build-optimizer   0.900.0-next.5
@angular-devkit/build-webpack     0.900.0-next.5
@angular-devkit/core              9.0.0-next.5
@angular-devkit/schematics        8.3.5
@angular/cli                      9.0.0-next.5
@bazel/bazel                      0.28.1
@bazel/hide-bazel-files           0.37.1
@bazel/ibazel                     0.10.3
@bazel/karma                      0.34.0
@bazel/protractor                 0.34.0
@bazel/typescript                 0.34.0
@ngtools/webpack                  9.0.0-next.5
@schematics/angular               8.3.5
@schematics/update                0.900.0-next.5
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.40.2
</code></pre>

**Comment by SanderElias** [comment]
This happens when not all things in node_modules are precompiled for ivy.
try:
```bash
yarn ivy-ngcc
```

That did solve it for me.

**Comment by fredrikredflag** [comment]
I managed to reproduction and solve it, it was in fact the missing `enableIvy: false` in `./angular-metadata.tsconfig.json`. 

But the missing part was that you need to clean up bazel befor building again.

```
ng new --collection=@angular/bazel
ng update --next=true @angular/cli @angular/core
./node_modules/.bin/bazel bazel clean --expunge
npm run start
```

Doing the above seems to fix the issue. 

@SanderElias `yarn ivy-ngcc` didn't solve it for me, but the above solution did. Sounds like some sort of caching issue.

However, since (at least for me) a needed to add `enableIvy: false` in order to make it work I don't know if this is a bug or work as intended.

**Comment by yoonjesung** [comment]
In my case, clearing the cache did not solve the issue, and neither did disabling ivy-ngcc.

**Comment by kyliau** [comment]
Bazel builder for Angular CLI has been deprecated since version 10.
Community support is available via the [Angular Bazel](https://github.com/bazelbuild/rules_nodejs/tree/master/examples/angular) repo and the [#angular](http://slack.bazel.build/) channel on Slack.
For more info, please see this [migration doc](https://github.com/angular/angular/blob/master/packages/bazel/src/schematics/README.md).
