### ISSUE TITLE
ng update @angular/core@next removes options for @ViewChild

### ISSUE THREAD

**Issue by Goobles** [angular/angular#32786]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
I think this is a regression on the "Dynamic queries migration" that did work correctly in the v7 to v8 migration, but gives an incorrect change in the v8 to v9 migration

### Description
`ng update @angular/cli@next` (in this case v9,0.0-next.7) causes options on `@ViewChild` to be removed, this causes TS errors.

I noticed that this only occurs in usages of `@ViewChild` where `ng upgrade --from=7 --to=8` failed to automatically infer the correct option for the `static` property 

## 🔬 Minimal Reproduction
Create an application with a component that has a property annotated with `@ViewChild('something',{static: false})` that is not used anywhere. This way `ng update` cannot infer the value for `static`
Run the `ng update @angular/core --from 8.0.0 --to 9.0.0 --migrate-only` 

## 🔥 Exception or Error
When compiling:
<pre><code>
error TS2554: Expected 2 arguments, but got 1.                                                     
8   @ViewChild(FormService) private formService: FormService<any>;                                                                                              ~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                
  ../../../../node_modules/@angular/core/core.d.ts:7919:47                                                                                                     7919     (selector: Type<any> | Function | string, opts: {                                                                                                                                                    ~~~~~~~                                                                                                 7920         read?: any;                                                                                                                                        ~~~~~~~~~~~~~~~~~~~                                                                                                                                   7921         static: boolean;                                                                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                              7922     }): any;                                                                                                                                               ~~~~~                                                                                                                                                 An argument for 'opts' was not provided.   
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.0-next.5
Node: 12.9.1
OS: win32 x64
Angular: 9.0.0-next.7
... animations, common, compiler, compiler-cli, core, forms     
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------     
@angular-devkit/architect         0.900.0-next.5
@angular-devkit/build-angular     0.900.0-next.5
@angular-devkit/build-optimizer   0.900.0-next.5
@angular-devkit/build-webpack     0.900.0-next.5
@angular-devkit/core              8.3.2
@angular-devkit/schematics        8.3.2
@angular/cdk                      8.1.4
@angular/cli                      9.0.0-next.5
@angular/material                 8.1.4
@ngtools/webpack                  9.0.0-next.5
@schematics/angular               8.3.2
@schematics/update                0.900.0-next.5
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.40.2
</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. I followed the reproduction steps and now changes were made in the migrations so I think this has been resolved as described by @devversion 

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
