### ISSUE TITLE
Use Node.js async hooks to support Zone.js

### ISSUE THREAD

**Issue by pauldraper** [angular/angular#32796]
# 🚀 feature request

### Relevant Package

Zone.js

### Description

Zone.js is incompatible with ES2017. Seeing as it is already 2019....it seems time to address this.

### Describe the solution you'd like

Node.js offers the async-hooks API which could support this on that platform.

@JiaLiPassion worked on this a couple years ago in the old repo. https://github.com/angular/zone.js/pull/795

As far as I know, there's no fundamental blocker.

### Describe alternatives you've considered

Don't use ES2017.

**Comment by JiaLiPassion** [comment]
Yeah, we can do this, I will try to figure out the schedule

**Comment by snebjorn** [comment]
@JiaLiPassion any progress on this?

**Comment by sviat9440** [comment]
Any news?

**Comment by snebjorn** [comment]
I noticed this on the roadmap 
https://angular.io/guide/roadmap#leverage-full-framework-capabilities-with-zonejs-opt-out

> ### Leverage full framework capabilities with Zone.js opt-out
> We are going to design and implement a plan to make Zone.js optional from Angular applications. This way, we will simplify the framework, improve debugging, and reduce application bundle size. Additionally, this will allow us to take advantage of native async/await syntax, which currently Zone.js does not support.

**Comment by dylhunn** [comment]
While this would be nice, we're not convinced it's implementable because the async hooks API lets you observe but not capture the continuation (i.e. reschedule the async operation). More generally, this is not the main direction we're planning to invest in.
