### ISSUE TITLE
Directive order in the compiler pipeline

### ISSUE THREAD

**Issue by vicb** [angular/angular#328]
- `_collectDirectiveBindings()` in the `ProtoElementInjectorBuilder` step order directive (types) by component, template and decorators,
- `_collectDirectives()` in `ElementBinderBuilder` step order directives by decorators, template and component. 

Could that cause an issue if an element is ie a template with decorators as we use the index to get a directive from the element injector ?

/cc @tbosch @vsavkin

**Comment by tbosch** [comment]
Yes, I think you are right that this is problematic. Could you try to create a unit test that produces an error because of this order mismatch?

**Comment by vicb** [comment]
I'll try to come with a test (and a fix).
I'll also investigate if collecting once could be better in term of perf.
