### ISSUE TITLE
PWA App showing white screen due to very slow load on cold start

### ISSUE THREAD

**Issue by try2flyb4ucry** [angular/angular#32800]
Hi, this is a very complex issue to describe, so I try my best to explain it in full details: We have an PWA app written in Angular, using Angular Service Worker package for PWA functionality. Recently we have noticed via Google Analytics that our page loads has gone too high and users complaining about our PWA app not loading (or very slow loading) in their desktop systems.

So, we investigated this issue and could reproduce it under certain conditions; We found out that it's not something related to our code, because many similar projects with the same library (Angular+ServiceWorker) also have this problem and it does not really matter which version of Angular packages you use, I tried 6, 7, 8 and also 9, but with the same result. Here are some url with Angular PWA demos on it which have the same issue:

https://firestarter-96e46.firebaseapp.com
https://angular-pwa-38ba5.firebaseapp.com
https://pwa.ng

So, these are steps to reproduce this issue on Chrome 76 & 77 (These two versions are the ones I could reproduce on them, Chrome 70 seems to work just fine and I guess this issue started in Chrome 75 or 76):

1. Go to the given URL (Desktop only, not mobile).
2. Click Install button on address bar for installing the PWA app.
3. Close all chrome windows and processes (**Important**)
4. Run PWA app by clicking it's icon on the desktop
5. Window pops up, but with no content, just a white screen.

This is very confusing, Because if you have any chrome window opened before opening the app, it works just fine. That's what makes step 3 so important in reproducing the issue and for having a so-called cold start effect on app start-up.

I tried other PWA apps that were written using Google WorkBox library, and they didn't had this issue. I guess this is somehow related to Angular ServiceWorker implementation causing some conflict with Chrome recent versions. I'm sure this is not something related to our code or even Angular, because it used to work just fine with older chrome versions. I Also submitted this issue on chromium issue tracker, but decided to also submit it in here to see if anyone else has this problem?

Possible Workaround:
After a lot of trial & errors, I noticed that if I put an async script tag in the end of head tag in my index.html, page renders fine, although page loading is still in progress for about 4-5 minutes without any specific reason and then window.load fires.

This is a very frustrating issue and we're losing our customers because of it. I hope and really appreciate if someone could shed some lights on it?

**Comment by try2flyb4ucry** [comment]
I created an issue for this on chromium issue tracker, and they could reproduce the issue and confirmed that it's a regression bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=1006546&can=2&start=0&num=100&q=component%3AUI>Browser>WebAppInstalls%20

But, While I hope they can get it fixed very soon, I really like to see if there's anything that Angular team could do to overcome this very specific situation? Because upgrading Angular is much more easier than requesting all the end users to update their Chrome versions😎😊

**Comment by gkalpak** [comment]
I am afraid there is not much we can do to work around this Chrome bug 😞
If you have ideas or find out more details, I would be happy to discuss, but I don't know of an easy fix/work-around based on the current info.

##
I am going to close this issue, since it is not actionable from our side atm. Feel free to continue the discussion below and (if more info comes up) I will reopen it and investigate further.

**Comment by try2flyb4ucry** [comment]
This issue is solved in Chrome version 78.0.3904.44 beta.

**Comment by try2flyb4ucry** [comment]
Due to severity of the problem, Chrome team decided to also include fix for the issue in version 77. The stable channel has been updated to version 77.0.3865.120 with fix included; update and enjoy! 😉😊
