### ISSUE TITLE
Missing the letter "e" in "MDN HTMLTableCellElment" in docs.

### ISSUE THREAD

**Issue by julianomacielferreira** [angular/angular#32803]
# 📚 Docs or angular.io bug report

### Description

 It's just missing the letter "e" in the word "HTMLTableCellElment".

- FUNDAMENTALS 
   - Components & Templates 
      - Templates Syntax 
         -  Property Binding [property]
            - Examples

### What's the affected URL?**
 https://angular.io/guide/template-syntax#examples

### Reproduction Steps**

Accessing the affected URL and search for "MDN HTMLTableCellElment".

### Expected vs Actual Behavior**

Actual: _HTMLTableCellElment_ 
Expected: __HTMLTableCellElement__ 

## 📷Screenshot

![2019-09-21-155131_1920x1080_scrot](https://user-images.githubusercontent.com/49996266/65377924-ced0d900-dc87-11e9-8376-9a46bd32f43f.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Browser info

Google Chrome - Version 77.0.3865.90 (Official Build) (64-bit)

### Anything else relevant?

None.

**Comment by jbogarthyde** [comment]
Resolved by https://github.com/angular/angular/pull/32805
