### ISSUE TITLE
Router: Cannot read property 'routes' of undefined at getChildConfig (crash, router.js::3297)

### ISSUE THREAD

**Issue by maks187** [angular/angular#32814]
# 🐞 bug report

### Affected Package
Router

### Is this a regression?

Unknown.

### Description

Hi,

one of my rounter-configurations is/could-be-or-not uncomplete. This can happen.
Your router is crashing on that (Why is it crashing? An array could be empty or could not exist at all, a framework must handle that and react accordingly on that).
Your code throws an exception with a absolutely useless crash-stack.
Developers like me who use your framework have no chance to debug that and
must submit an issue for that on Github for that..
It seems not to be a error which is thrown by the compiler or webpack itself, because you actually display what happens, but not WHY and WHERE!
Thank you.

## 🔬 Minimal Reproduction
I can't. I don't know where it came from, because you have all the information where it does
occur, but don't show where it happens..

## 🔥 Exception or Error
<pre><code>
Uncaught Error: Uncaught (in promise): TypeError: Cannot read property 'routes' of undefined
TypeError: Cannot read property 'routes' of undefined
    at getChildConfig (router.js:3297)
    at Recognizer.push../node_modules/@angular/router/fesm5/router.js.Recognizer.processSegmentAgainstRoute (router.js:3269)
    at Recognizer.push../node_modules/@angular/router/fesm5/router.js.Recognizer.processSegment (router.js:3228)
    at Recognizer.push../node_modules/@angular/router/fesm5/router.js.Recognizer.processSegmentGroup (router.js:3213)
    at router.js:3217
    at router.js:971
    at forEach (router.js:705)
    at mapChildrenIntoArray (router.js:969)
    at Recognizer.push../node_modules/@angular/router/fesm5/router.js.Recognizer.processChildren (router.js:3217)
    at Recognizer.push../node_modules/@angular/router/fesm5/router.js.Recognizer.processSegmentAgainstRoute (router.js:3272)
    at resolvePromise (zone.js:852)
    at resolvePromise (zone.js:809)
    at zone.js:913
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:24340)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
  | resolvePromise | @ | zone.js:852
-- | -- | -- | --
  | resolvePromise | @ | zone.js:809
  | (anonymous) | @ | zone.js:913
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask | @ | zone.js:423
  | onInvokeTask | @ | core.js:24340
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask | @ | zone.js:422
  | push../node_modules/zone.js/dist/zone.js.Zone.runTask | @ | zone.js:195
  | drainMicroTaskQueue | @ | zone.js:601
  | setTimeout (async) |   |  
  | scheduleTask | @ | zone.js:3091
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask | @ | zone.js:410
  | push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask | @ | zone.js:238
  | push../node_modules/zone.js/dist/zone.js.Zone.scheduleMacroTask | @ | zone.js:261
  | scheduleMacroTaskWithCurrentZone | @ | zone.js:1194
  | (anonymous) | @ | zone.js:3106
  | proto.<computed> | @ | zone.js:1518
  | hostReportError | @ | hostReportError.js:3
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub | @ | Subscriber.js:200
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next | @ | Subscriber.js:130
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next | @ | Subscriber.js:76
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next | @ | Subject.js:47
  | push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit | @ | core.js:22085
  | (anonymous) | @ | core.js:24371
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke | @ | zone.js:391
  | push../node_modules/zone.js/dist/zone.js.Zone.run | @ | zone.js:150
  | push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular | @ | core.js:24308
  | onHandleError | @ | core.js:24371
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError | @ | zone.js:395
  | push../node_modules/zone.js/dist/zone.js.Zone.runGuarded | @ | zone.js:164
  | _loop_1 | @ | zone.js:715
  | api.microtaskDrainDone | @ | zone.js:724
  | drainMicroTaskQueue | @ | zone.js:608
  | Promise.then (async) |   |  
  | scheduleMicroTask | @ | zone.js:584
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask | @ | zone.js:413
  | onScheduleTask | @ | zone.js:301
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask | @ | zone.js:404
  | push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask | @ | zone.js:238
  | push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask | @ | zone.js:258
  | scheduleResolveOrReject | @ | zone.js:900
  | ZoneAwarePromise.then | @ | zone.js:1040
  | push../node_modules/@angular/router/fesm5/router.js.RouterInitializer.appInitializer | @ | router.js:5650
  | push../node_modules/@angular/core/fesm5/core.js.ApplicationInitStatus.runInitializers | @ | core.js:23759
  | (anonymous) | @ | core.js:24850
  | _callAndReportToErrorHandler | @ | core.js:24943
  | (anonymous) | @ | core.js:24848
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke | @ | zone.js:391
  | onInvoke | @ | core.js:24349
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke | @ | zone.js:390
  | push../node_modules/zone.js/dist/zone.js.Zone.run | @ | zone.js:150
  | push../node_modules/@angular/core/fesm5/core.js.NgZone.run | @ | core.js:24263
  | push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModuleFactory | @ | core.js:24839
  | ./src/main/typescript/app/basis/main.ts | @ | main.ts:18
  | __webpack_require__ | @ | bootstrap:83
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.0.3
Node: 10.16.0
OS: win32 x64
Angular: 8.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.3
@angular-devkit/build-angular      0.800.3
@angular-devkit/build-optimizer    0.800.3
@angular-devkit/build-webpack      0.800.3
@angular-devkit/core               8.0.3
@angular-devkit/schematics         8.0.3
@angular/cdk                       8.0.1
@angular/cli                       8.0.3
@angular/flex-layout               8.0.0-beta.26
@angular/http                      7.2.15
@angular/material                  8.0.1
@angular/material-moment-adapter   8.0.1
@ngtools/webpack                   8.0.3
@schematics/angular                8.0.3
@schematics/update                 0.800.3
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0
</code></pre>

**Comment by bre10000** [comment]
Facing the same Issues 

My angular version

Angular CLI: 8.3.14
Node: 12.13.0
OS: win32 x64
Angular: 8.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.14
@angular-devkit/build-angular     0.803.14
@angular-devkit/build-optimizer   0.803.14
@angular-devkit/build-webpack     0.803.14
@angular-devkit/core              8.3.14
@angular-devkit/schematics        8.3.14
@angular/cli                      8.3.14
@angular/http                     7.2.15
@ngtools/webpack                  8.3.14
@schematics/angular               8.3.14
@schematics/update                0.803.14
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

**Comment by ShacharHarshuv** [comment]
I get this exception too, not sure why. It happens when I add a root route to share a resolver:

Old code: 
```
[
  {path: 'blabla', ... }, 
  {path: 'blublue', ... } 
]
```
New code: 
```
[
 path: '', resolver: ..., children: [
   {path: 'blabla', ... }, 
   {path: 'blublue', ... } 
 ]
]
```

**Comment by atscott** [comment]
Hi, can someone who's experiencing this issue try to provide a reproduction? It's impossible to debug without one. Stackblitz is ideal but a small github repo would work as well.

**Comment by bre10000** [comment]
@atscott 

https://stackblitz.com/edit/angular-v5d65t

The Code run fine on stackblitz

**Comment by atscott** [comment]
@bre10000 I'm not sure I follow. Is the stackblitz link supposed to be a reproduction of the error described in this ticket? I'm not seeing the `Cannot read property 'routes' of undefined`.

**Comment by bre10000** [comment]
**Error-** Cannot read property 'routes' of undefined.

I got this error when I use lazy loading to load Dashboard component. The app worked fine when I changed it back to regular routes. 

What is the proper way of using lazy loading on Angular 8?

Also I posted the environment details above.

**Comment by duprez** [comment]
Any updates?

**Comment by atscott** [comment]
Hi, if you can't get a stackblitz example that shows the bug, please create a minimal reproduction in a GitHub project. Environment details are helpful but not enough. There needs to be some code to reference or we cannot debug the issue.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by simeyla** [comment]
@atscott - I got this today - Ivy / Angular 9 - while I don't have a sample project (yet) I think the following should explain what's happening.  It's basically a race condition in router during navigation.
The condition is easily repeated and to the best of my knowledge this is what's happening:

I came across this error when testing a lazy named route by navigating in a `setTimeout` 

- Open site to `/` (yes my homepage at `/` is actually a lazy route. It has half a dozen chunks - so takes a couple seconds to load.
- In `app.component` in a `setTimeout(2000)` I open another lazy module in a named outlet 

        this.router.navigate([ { outlets: { 'dialog-outlet': commands }} ], { skipLocationChange: false })

- If the main navigation hasn't yet completed I'll see a `NavigationCancel` event since the primary navigation is not yet completed. 

Here's the log of navigation events - note the timestamps - the NavigationCancel is a direct result of the NavigationStart event to the named outlet:

```
21:20:25.560 main.js:30478 NAVIGATION EVENT NavigationStart {id: 1, url: "/", navigationTrigger: "imperative", restoredState: null}
21:20:25.575 main.js:30478 NAVIGATION EVENT RouteConfigLoadStart {route: {…}}
21:20:27.519 main.js:30478 NAVIGATION EVENT NavigationCancel {id: 1, url: "/", reason: "Navigation ID 1 is not equal to the current navigation id 2"}
21:20:27.521 main.js:30478 NAVIGATION EVENT NavigationStart {id: 2, url: "/(dialog-outlet:dialog/faq/56)", navigationTrigger: "imperative", restoredState: null}
21:20:27.525 main.js:30478 NAVIGATION EVENT RouteConfigLoadStart {route: {…}}
21:20:27.582 main.js:30478 NAVIGATION EVENT RouteConfigLoadEnd {route: {…}}
```

When the race condition doesn't occur I'll see `NavigationEnd` for my `/` route followed by `NavigationStart` - so no `NavigationCancel` and no problem.

```
21:55:24.109 main.js:30478 NAVIGATION EVENT NavigationEnd {id: 1, url: "/", urlAfterRedirects: "/"}
21:55:24.120 main.js:30478 NAVIGATION EVENT Scroll {routerEvent: NavigationEnd, position: null, anchor: null}
21:55:25.263 main.js:30478 NAVIGATION EVENT NavigationStart {id: 2, url: "/(dialog-outlet:dialog/faq/56)", navigationTrigger: "imperative", restoredState: null}
```

Should be pretty easy to duplicate this - but the lazy module would need to be large enough to be slow to download to trigger the race condition. 

![image](https://user-images.githubusercontent.com/3656278/74505552-4eb44580-4eac-11ea-9424-7da4eee8d78e.png)

Possible workaround: Watch for main navigation events and don't navigate to a child outlet if a navigation event is already occuring (or queue it in a promise).

**Comment by atscott** [comment]
Hi @simeyla, thanks for the additional info. It will certainly be helpful for investigating this issue. Once you can get a reproduction (stackblitz or github), please include this information along with the repro in a new issue.
