### ISSUE TITLE
dart: serve "package:" urls relative to AppRootUrl

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#3281]
This should work better with non-pub servers.

Context: https://github.com/angular/angular/pull/3215/files#r35440289

**Comment by yjbanov** [comment]
Fixed by #3287

**Comment by yjbanov** [comment]
The fix was reverted due to build breakage. Reopening.

**Comment by yjbanov** [comment]
@kegluneq, @jakemac53 I'm going to punt on this for now. The issue turned out to be that the contents of the `packages` directories depend on whether they are created by `pub build` or `pub get`.

`pub build` does _not_ put resources in non-root `packages` and so you have to look for resources using absolute URL. I could change our build to account for that, but that defeats the purpose of the feature in that it is supposed to be a standard way to resolve URLs.

**Comment by naomiblack** [comment]
Won't fix. this is obsoleted by the new compiler.
