### ISSUE TITLE
(bug) AoT ERROR in (1,1): Directive AnyComponent, Expected 0 arguments, but got 1. (HostListener)

### ISSUE THREAD

**Issue by Domvel** [angular/angular#32828]
# 🐞 bug report

### Affected Package

`@angular/core`

### Is this a regression?

In Angular `8.1.2` it works. But in Angular `8.2.5` not. I also tried the latest versoin `8.2.7`. 

Update: It's a old known issue. See the second post here.

### Description

I get the error: `ERROR in (1,1): Directive AnyComponent, Expected 0 arguments, but got 1.`

The first problem is: There is no file path and no line number / member name in the error message. You have to find out successively. This should be improved. But back to this issue...

It's about the `HostListener`. If I comment it out, it works.

```ts
@HostListener('window:resize', ['$event'])
public onResize(): void {
  // Some stuff.
}
```

This is a correct implementation and has worked so far.
It looks like a pseudo bug. I only get this error when I compile in production mode (AoT).

```text
ng build --project=app1 --prod --sourceMap=false
```

## 🔬 Minimal Reproduction
I don't know how to create a demo at Stackblitz for this special issue about building.
Please see the description above. Here is a demo project as zip:
[ng-build-issue.zip](https://github.com/angular/angular/files/3646657/ng-build-issue.zip)
(Created by the latest ng cli `ng new ng-build-issue`, see readme.md for more info.)

## 🔥 Exception or Error
<pre><code>
ERROR in (1,1): Directive AnyComponent, Expected 0 arguments, but got 1.
</code></pre>

## 🌍  Your Environment

<pre><code>
Angular CLI: 8.3.5
Node: 10.15.3
OS: win32 x64
Angular: 8.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.3
@angular-devkit/build-angular      0.803.5
@angular-devkit/build-ng-packagr   0.803.5
@angular-devkit/build-optimizer    0.803.5
@angular-devkit/build-webpack      0.803.5
@angular-devkit/core               8.1.3
@angular-devkit/schematics         8.1.3
@angular/cli                       8.3.5
@ngtools/webpack                   8.3.5
@schematics/angular                8.3.5
@schematics/update                 0.803.5
ng-packagr                         5.5.1
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Anything else relevant?**

I upgraded the demo to Angular `8.2.7` (and the latest CLI) in the demo project and the error is gone. But I in another project I did the same, and the error is still present. Also 8.2.7. It's weird. I also removed the node_modules and package-lock. It seems to be it's not yet fixed.

**Comment by Domvel** [comment]
Workaround: Remove the `$event` from the array of the second argument. It's really weird.

```ts
@HostListener('window:resize', [])
public onResize(): void {
  this.setScale();
}
```

**Comment by Domvel** [comment]
@ericmartinezr Thanks, that's correct. It's because unused argument. Or more not declared argument. But in my experience this error is randomly. Maybe it has to do with the arrangement of the planets or the compilers emotional state. 😄 It's just weird that sometimes it works. Anyway... This should be 1. just a warning and 2. a more specific error message.

The error message is confusing.
```text
ERROR in (1,1): Directive AnyComponent, Expected 0 arguments, but got 1.
```

- No path of the affected file.
- No name of the affected member / decorator or line number.
- I think the "expected" arguments `0` comes from the method I defined. Anyway, this should be a warning or nothing. Like unused arguments / variables.

...

Just a suggestion. Be free to close this. But it could help other developers.

**Comment by alxhub** [comment]
I think it's definitely related to the compiler's emotional state :)

Luckily in this case the Ivy compiler is much more rational. This shouldn't be a problem.

**Comment by 404Assassin** [comment]
I have two components in the same application both have identical HostListeners (for window resize events), the first component does not throw an error in prod builds but the second component, with the identical HostListener code, does. Removing the $event(unused anyways) in the second input gets rid of the build error.

```
Angular CLI: 8.3.4
Node: 10.16.0
OS: darwin x64
Angular: 8.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.4
@angular-devkit/build-angular     0.803.4
@angular-devkit/build-optimizer   0.803.4
@angular-devkit/build-webpack     0.803.4
@angular-devkit/core              8.3.4
@angular-devkit/schematics        8.3.4
@angular/cdk                      8.2.0
@angular/cli                      8.3.4
@angular/material                 8.2.0
@ngtools/webpack                  8.3.4
@schematics/angular               8.3.4
@schematics/update                0.803.4
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
```

**Comment by alxhub** [comment]
Closing as "resolved" - I don't believe the Ivy compiler yet checks host bindings.
