### ISSUE TITLE
[Proposal] Ability to set a default ChangeDetectionStrategy at a module/application level

### ISSUE THREAD

**Issue by cleavera** [angular/angular#32834]
# 🚀 Feature request

### Relevant Package
This feature request is for @angular/core

### Description
When declaring a component you can specify the change detection strategy for the component, there is the CheckAlways (default) and CheckOnce (onPush) strategies. Enabling CheckOnce can give a pretty big performance boost over the default strategy, as such on the project I work on our guidance is to use OnPush and only fallback to the default strategy if it proves unreasonable. The issue is that (at least from what I can glean from the docs and typings) ChangeDetectionStrategy has to be set on each component, this results in `changeDetection: ChangeDetectionStrategy.OnPush;` being added to the declaration for almost every component in our system and also means developers have to explicitly remember to opt into it.

### Describe the solution you'd like
There is a similar property in the component declaration called `encapsulation?: ViewEncapsulation`. This can be set on a component by component level but crucially can also be given a default value when calling `bootstrapModule` by passing the `CompilerOptions` property `defaultEncapsulation?: ViewEncapsulation;`. I would propose a similar solution for this. Something like `defaultChangeDetectionStrategy?: ChangeDetectionStrategy` which behaves in a similar way. 

### Describe alternatives you've considered
You could specify it at a module level but I think it would be a weird thing to declare for a module and would still need to be repeated for different parts of the system, furthermore which strategy should a component declared under multiple modules use (just seems to add complexity).

### Tangential thoughts
In general I think there should be more of a push towards onPush (😉). I would personally consider renaming `ChangeDetectionStrategy.Default` to something more descriptive, its not particularly clear to the user what thats doing and in my opinion steers them towards it being the defacto value. I would also like to see the documentation around it guiding first time users more towards using onPush in almost all cases (mentioning it in the Getting started guide for instance).

**Comment by dannyskoog** [comment]
I like the idea! Especially for new angular apps or existing ones with `OnPush` already used for all components.

Interesting question though - how common is it using `OnPush` throughout the whole tree of an Angular app?

Personally I have a mix in the app that I’m maintaining. Mostly because it’s not worth the hassle being ”in charge” of change detection for certain smarter components

**Comment by dawidgarus** [comment]
You only need to set `OnPush` on root component. All inner components will inherit this behavior.
https://angular.io/api/core/ChangeDetectionStrategy:
> Use the CheckOnce strategy, meaning that automatic change detection is deactivated until reactivated by setting the strategy to Default (CheckAlways). Change detection can still be explicitly invoked. This strategy applies to all child directives and cannot be overridden.

**Comment by dannyskoog** [comment]
Good point @dawidgarus

**Comment by cleavera** [comment]
Good spot, @dawidgarus 

I still think the tangential thoughts are worth discussing, but the inheritability of OnPush solves my original issue. With this in mind I'll close this unless there are any objections.
