### ISSUE TITLE
Used Lazy loading Method its return Console error 

### ISSUE THREAD

**Issue by kathirm** [angular/angular#32833]
core.js:1673 ERROR Error: Uncaught (in promise): Error: Template parse errors:
'app-header' is not a known element:
1. If 'app-header' is an Angular component, then verify that it is part of this module.
2. If 'app-header' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<app-header></app-header>

<div class="anaytics-container">
"): ng:///ShopModule/LeaveListingComponent.html@0:0
Can't bind to 'value' since it isn't a known property of 'p-messages'.
1. If 'p-messages' is an Angular component and it has 'value' input, then verify that it is part of this module.
2. If 'p-messages' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

<div class="anaytics-container">
  <p-messages [ERROR ->][(value)]="msgs"></p-messages>
  <div class="left-container {{leftContentClass}}">
    <div class="fi"): ng:///ShopModule/LeaveListingComponent.html@3:14
'p-messages' is not a known element:
1. If 'p-messages' is an Angular component, then verify that it is part of this module.
2. If 'p-messages' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("

<div class="anaytics-container">
  [ERROR ->]<p-messages [(value)]="msgs"></p-messages>
  <div class="left-container {{leftContentClass}}">
    <d"): ng:///ShopModule/LeaveListingComponent.html@3:2
Can't bind to 'data' since it isn't a known property of 'app-filters'.
1. If 'app-filters' is an Angular component and it has 'data' input, then verify that it is part of this module.
2. If 'app-filters' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("   <div class="leftcontainer filtersection dynamic-filter" *ngIf="showFilter">
        <app-filters [ERROR ->][data]="filterMetaData" [facetData]="facetData" (onFilterChanged)="filterChange($event)"></app-filter"): ng:///ShopModule/LeaveListingComponent.html@7:21
Can't bind to 'facetData' since it isn't a known property of 'app-filters'.
1. If 'app-filters' is an Angular component and it has 'facetData' input, then verify that it is part of this module.
2. If 'app-filters' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("iner filtersection dynamic-filter" *ngIf="showFilter">
        <app-filters [data]="filterMetaData" [ERROR ->][facetData]="facetData" (onFilterChanged)="filterChange($event)"></app-filters>
      </div>
    </di"): ng:///ShopModule/LeaveListingComponent.html@7:45
'app-filters' is not a known element:
1. If 'app-filters' is an Angular component, then verify that it is part of this module.
2. If 'app-filters' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. (""filter">
      <div class="leftcontainer filtersection dynamic-filter" *ngIf="showFilter">
        [ERROR ->]<app-filters [data]="filterMetaData" [facetData]="facetData" (onFilterChanged)="filterChange($event)""): ng:///ShopModule/LeaveListingComponent.html@7:8
Can't bind to 'model' since it isn't a known property of 'p-splitButton'.
1. If 'p-splitButton' is an Angular component and it has 'model' input, then verify that it is part of this module.
2. If 'p-splitButton' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("ages/refresh.png" title="Refresh" /></a>
          <p-splitButton label="Action" icon="pi pi-file"  [ERROR ->][model]="actionItems" [disabled]="selectedRows.length == 0" styleClass="ui-button-info" class="margin"): ng:///ShopModule/LeaveListingComponent.html@20:59
Can't bind to 'disabled' since it isn't a known property of 'p-splitButton'.
1. If 'p-splitButton' is an Angular component and it has 'disabled' input, then verify that it is part of this module.
2. If 'p-splitButton' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("e="Refresh" /></a>
          <p-splitButton label="Action" icon="pi pi-file"  [model]="actionItems" [ERROR ->][disabled]="selectedRows.length == 0" styleClass="ui-button-info" class="margin-bottom-10px pull-righ"): ng:///ShopModule/LeaveListingComponent.html@20:81
'p-splitButton' is not a known element:
1. If 'p-splitButton' is an Angular component, then verify that it is part of thcompiler.js:1021)
    at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:14830)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:24018)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:24005)
    at compiler.js:23948
    at Set.forEach (<anonymous>)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (compiler.js:23948)
    at compiler.js:23858
    at Object.then (compiler.js:1012)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:23857)
    at resolvePromise (zone.js:831)
    at resolvePromise (zone.js:788)
    at zone.js:892
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:3811)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:502)
    at invokeTask (zone.js:1744)
defaultErrorLogger @ core.js:1673
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:1719
next @ core.js:4311
schedulerFn @ core.js:3551
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:195
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:133
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:3535
(anonymous) @ core.js:3842
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:3779
onHandleError @ core.js:3842
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:395
push../node_modules/zone.js/dist/zone.js.Zone.runGuarded @ zone.js:164
_loop_1 @ zone.js:694
api.microtaskDrainDone @ zone.js:703
drainMicroTaskQueue @ zone.js:608
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:502
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770

**Comment by kathirm** [comment]
Thanks n adance Any idea's

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
