### ISSUE TITLE
Unable to build an abstract Component in a library

### ISSUE THREAD

**Issue by alastair-todd** [angular/angular#32848]
# 🐞 bug report

### Affected Package
`build-ng-packagr` I think

### Is this a regression?

Unsure

### Description

Unable to build when an abstract component exists inside a library. The compiler complains that it has no module. If you add it to a module there is a type mismatch because the abstract component cannot be instantiated.

Removing the @Component directive means it can get through the "must be exported by a module" issue. However the template and css can no longer be reused properly by components extending this one.

## 🔬 Minimal Reproduction
<pre><code>
@Component({
  selector: 'lib-abstract',
  templateUrl: './abstract.component.html',
  styleUrls: ['./abstract.component.css']
})
export abstract class AbstractComponent {}

@NgModule({
  declarations: [ComponentsComponent, AbstractComponent],
  imports: [
  ],
  exports: [ComponentsComponent]
})
export class ComponentsModule { }
</code></pre>

## 🔥 Exception or Error
<pre><code>

------------------------------------------------------------------------------
Building entry point 'components'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
ERROR: projects/components/src/lib/components.module.ts(8,39): error TS2322: Type 'typeof AbstractComponent' is not assignable to type 'any[] | Type<any>'.
  Type 'typeof AbstractComponent' is not assignable to type 'Type<any>'.
    Cannot assign an abstract constructor type to a non-abstract constructor type.

An unhandled exception occurred: projects/components/src/lib/components.module.ts(8,39): error TS2322: Type 'typeof AbstractComponent' is not assignable to type 'any[] | Type<any>'.
  Type 'typeof AbstractComponent' is not assignable to type 'Type<any>'.
    Cannot assign an abstract constructor type to a non-abstract constructor type.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.5
Node: 10.15.3
OS: win32 x64
Angular: 8.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.5
@angular-devkit/build-angular      0.803.5
@angular-devkit/build-ng-packagr   0.803.5
@angular-devkit/build-optimizer    0.803.5
@angular-devkit/build-webpack      0.803.5
@angular-devkit/core               8.3.5
@angular-devkit/schematics         8.3.5
@angular/cdk                       8.2.0
@angular/cli                       8.3.5
@angular/material                  8.2.0
@ngtools/webpack                   8.3.5
@schematics/angular                8.3.5
@schematics/update                 0.803.5
ng-packagr                         5.5.1
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2

</code></pre>

**Comment by SantiagoIlli** [comment]
Hi!

Even if the component could be abstract, and you create another component that extends the first component, the html and css would be different, cause component metadata is not inheritable as far as I know.

If you want several components to share behaviour you can create an abstract class and extend it in the components.

If you also want to share html template, you can export it as a const and then use it as a template in the component.

For example:

html-share-template.ts

`
export const templateToShare = '<div>\n' +
  '  My sharable template!\n' +
  '</div>';
`

And use it in a component like:

`  import {templateToShare} from '...';
@Component({
  selector: 'a-component-selector',
  template: templateToShare,
  styleUrls: ['./a-component.component.css']
})`

**Comment by alastair-todd** [comment]
The meta data is inheritable.

What about binding in your example? The only thing abstract here is the source of data.

**Comment by SantiagoIlli** [comment]
Binding works as expected.

[Here i made a stackblitz very small example.](https://stackblitz.com/edit/angular-tte6sf?file=src%2Fapp%2Fhello.component.ts)

Hello component imports the htmlTemplate from app.component.ts, could be a library but i didn't create one for simplicity, and the bindings works.

I know that is not the best, you must respect 'manually' the methods and variable names, but if you create an abstract class that the components will inherit, shouldn't be a big problem.

If you have a lot of code and need code predicting for write it, you can also create a first component that inherits from the abstract class, put the html code there, and then just copy it into a const.

Hope this can work at least as a workaround for your use case!

**Comment by SantiagoIlli** [comment]
I'm curious, how do you inherit metadata between components?

**Comment by alastair-todd** [comment]
Perhaps it is not possible after all

#24463

**Comment by SantiagoIlli** [comment]
So, as meta data  is not inheritable, an abstract component does not make much sense for me, cause you can use an abstract class in case you need it.
If you agree, this issue could be closed.

**Comment by alxhub** [comment]
I agree :) in Ivy this is even stricter I believe - a component must have its own `@Component` decorator, it can't inherit one from its parent.
