### ISSUE TITLE
8.3.x ES5 build broken for spread operator on set

### ISSUE THREAD

**Issue by readme42** [angular/angular#32851]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/cli

### Is this a regression?
No, its broken since the optimized creation of es5 builds were introduced. In 8.2.x of angular-cli everything was fine.

### Description

We have quite a large application. Since updating `angular/cli` to 8.3.x it turns our that our ES5 builds are broken - exceptions are thrown during runtime. 

What I found out so far: 

ES2015 builds are fine. 
ES5 builds, created with `NG_BUILD_DIFFERENTIAL_FULL=true` are fine.
ES5 builds, created without `NG_BUILD_DIFFERENTIAL_FULL=true` are broken.

It turns out, that the following line creates `undefined` in es5 builds whereas it creates an array of strings in es2015 builds:

<pre><code>
// Make demand ids in day unique
cardDataByDay[ key ] = [ ...new Set(cardDataByDay[ key ]) ];
</code></pre>

Happens in any browser in which you load the es5 build. No need to use old browsers for testing, just load the es5 builds in the latest chrome. 

## 🔥 Exception or Error
<pre><code>As its quite some effort and you maybe already know what and where to fix it, 
I will do when you really need it. Just drop a comment in this case.

Runtime exception is the basic 'cant access <x> of undefined'.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.5
Node: 12.6.0
OS: darwin x64
Angular: 8.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.2
@angular-devkit/build-angular     0.803.2
@angular-devkit/build-optimizer   0.803.2
@angular-devkit/build-webpack     0.803.2
@angular-devkit/core              8.3.2
@angular-devkit/schematics        8.3.5
@angular/cdk                      8.2.1
@angular/cli                      8.3.5
@angular/material                 8.2.1
@ngtools/webpack                  8.3.2
@schematics/angular               8.3.5
@schematics/update                0.803.5
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.39.2
</code></pre>

**Comment by sarunint** [comment]
Please open this issue in angular/angular-cli repository

**Comment by readme42** [comment]
Damn, sorry. Here we go: https://github.com/angular/angular-cli/issues/15673
