### ISSUE TITLE
Angular : PWA - Custom Add to Home Screen or App install option. 

### ISSUE THREAD

**Issue by SWGeekPD** [angular/angular#32854]
I am using Angular 8 I have added @Angular/PWA package and I can see my code is having 
**manifest.webmanifest** and **ngsw-config.json** file.

I did prod build and I am able to install the application from Windows chrome browsers + button in the address bar. I am using Chrome 77.

I want to modify this behavior and want to use my own popup or link in which user can click and can install application any time.

https://developers.google.com/web/fundamentals/app-install-banners/promoting-install-mobile
I followed the steps in the above site.

Someone please help me to find where to write below code.
window.addEventListener('beforeinstallprompt', (e) => {}

This guideline is really not good , I am not able to understand where to write this code for SW.

I create custom-sw.js file and when trying to add there it is saying 
**Uncaught ReferenceError: window is not defined**

please help.

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

##
(The super-quick answer would be that the code you mentioned should be added to your app code, not the ServiceWorker script.)
