### ISSUE TITLE
Router module is crashing on the Webkit when link href is updated

### ISSUE THREAD

**Issue by AndrisBB** [angular/angular#32863]
We have Angular 7 application running on the embedded platform using Webkit (WPE - https://wpewebkit.org/).
When we navigate the menu the application will crash randomly and terminate the WPEWebProcess.
I have narrowed down the problem to a single variable assignment in the Router module.
updateTargetUrlAndHref() {
    this.href = this.locationStrategy.prepareExternalUrl(this.router.serializeUrl(this.urlTree));
}
If I remove the line or add console.log before the assignment, then crash is gone. Same crash happens if I try to update another property like download instead of href.

Crash do not happen on the PC using Chrome, Firefox or other WebKit based browsers - Gnome Browser, Epiphany etc.

Dependencies:
    "@angular-devkit/build-angular": "^0.13.0",
    "@angular/animations": "7.2.4",
    "@angular/common": "7.2.4",
    "@angular/compiler": "7.2.4",
    "@angular/core": "7.2.4",
    "@angular/forms": "7.2.4",
    "@angular/http": "7.2.4",
    "@angular/platform-browser": "7.2.4",
    "@angular/platform-browser-dynamic": "7.2.4",
    "@angular/router": "7.2.4",
    "core-js": "^2.5.4",
    "rxjs": "6.4.0",
    "rxjs-compat": "6.5.2",
    "zone.js": "0.8.29"

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template, including a minimal reproduction.
