### ISSUE TITLE
mat-sort-header does not apply component local style correctly

### ISSUE THREAD

**Issue by ttsuen** [angular/angular#32861]
# 🐞 bug report

### Affected Package
    "@angular/material": "^8.1.2",

### Is this a regression?
do not know. I just started using this in 8.1.2 but it is at least from that version onward.

### Description
When a material table has a column sort header and you want to apply a style/css class to that header, component specific style (created in component level scss file) cannot be applied.

## 🔬 Minimal Reproduction
https://angular-issue-repro2-sykr4e.stackblitz.io

## 🔥 Exception or Error
No Error. Just incorrect behavior.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.1.2
Node: 10.15.3
OS: darwin x64
Angular: 8.1.2
... cdk, cli, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.801.3
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.801.3
@angular-devkit/core              8.1.2
@angular-devkit/schematics        8.1.2
@angular/animations               8.2.0
@angular/http                     7.2.15
@ngtools/webpack                  8.1.3
@schematics/angular               8.1.2
@schematics/update                0.801.2
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2

</code></pre>

**Anything else relevant?**
My application development was done with 8.1 but the reproduction was done in 8.2.  That doesn't seems to affect the behavior.

**Comment by atscott** [comment]
I believe this issue belongs in the [angular/components](https://github.com/angular/components) repo. Please refile the issue there.
