### ISSUE TITLE
HttpInterceptor triggers RxJS operator `tap` twice but `finalize` once

### ISSUE THREAD

**Issue by sasensi** [angular/angular#32868]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common/http

### Is this a regression?

 Not that I know.

### Description

 In HTTP interceptor, when piping to `next.handle(req)`, some RxJS operators behave in an unexpected manner. `tap` is called twice while `finalize` is called once.  
When reproducing the same pipe out of the `HttpInterceptor` context, directly on the `HttpClient` call, both operators are called only once, as expected.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/tap-tap-finalize  
Outputs: "tap tap success finalize" instead of "tap success finalize".

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.4
Node: 10.16.0
OS: win32 x64
Angular: 8.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.4
@angular-devkit/build-angular     0.803.4
@angular-devkit/build-optimizer   0.803.4
@angular-devkit/build-webpack     0.803.4
@angular-devkit/core              8.3.4
@angular-devkit/schematics        8.3.4
@angular/cdk                      8.2.0
@angular/cli                      8.3.4
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.0
@ngtools/webpack                  8.3.4
@schematics/angular               8.3.4
@schematics/update                0.803.4
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

**Comment by Airblader** [comment]
finalize can only ever run once because it acts upon completion of the observable, and a completed observable is closed.

So it seems two values are emitted here before the observable is completed.

**Comment by sasensi** [comment]
Indeed, in this [modified version](https://stackblitz.com/edit/tap-tap-finalize-7lx4on) of the example, I log the value in the console.
It appears that this object: `{type: 0}` is emitted first, then, the response.
Is it on purpose and if so, what does this value mean ?

**Comment by dannyskoog** [comment]
Most likely the first event you’re intercepting is of type https://angular.io/api/common/http/HttpEventType#Sent

**Comment by yzhe554** [comment]
The first emit is telling you the request's sent successfully({type: 0}). The second emit is the HttpResponse.

**Comment by sasensi** [comment]
Ok, thank you for your insights.
I still have a last misunderstanding: if 2 consecutive values are effectively emitted from the observable (HttpEventType then HttpResponse), why does the subscriber only receive the second one ?
In other words, why don't we see the output "tap tap success success finalize" ?

**Comment by trotyl** [comment]
> In other words, why don't we see the output "tap tap success success finalize" ?

You do, if you choose to receive all events by using `observe: 'events'` instead of `observe: 'body'` or `observe: 'response'`. See https://angular.io/guide/http#listening-to-progress-events for details.

**Comment by gkalpak** [comment]
I am going to close this, since everything works as expected afaict. Feel free to continue the discussion below (and let me know if you don't think this should be closed).

**Comment by sasensi** [comment]
Ok, thank you, I guess this was not a bug then but my misunderstanding of the behavior of the interceptor.
  
Can I use your knowledge of the internal logic one last time ?
My use case is actually to show a loading animation while at least one HTTP request is pending.
So every time a request starts, I increment a loading counter and every time a request ends, I decrement it. The loading animation is displayed when the counter is not null.
I hooked into the interceptor to do that and the double tap behavior was problematic for me because I was incrementing the counter twice the time that I was decrementing it (so I needed to add nasty custom logic to correct that).
After your answers, I am able to set that up in a cleaner manner, using RxJS `last` operator at the start of my pipe:
```javascript
return next.handle(req).pipe(
  last(),
  tap(() => document.write("tap ")),
  finalize(() => document.write("finalize "))
);
```
Here is the [modified example](https://stackblitz.com/edit/tap-tap-finalize-nw64pf).
This works as I want, but I wanted to make sure that this will have no side effect on the internal logic ?

**Comment by dannyskoog** [comment]
I wouldn’t recommend it since you’re effectively limiting potential subsequent interceptors from receiving anything but the last event per request. It’s better explained in the last paragraph of this section https://angular.io/guide/http#httpevents.

I would rather write some logic in the `tap` in order to sniff whatever event I’m interested in. And probably give the interceptor file a nisched and declarative name

**Comment by sasensi** [comment]
Ok, I understand way better now and will certainly stay with my custom `tap` logic then.
Thank you all for your support.

**Comment by dannyskoog** [comment]
Great @sasensi! Happy to serve :)
