### ISSUE TITLE
Hero property change to array of objects. So to print in right way the code should change!

### ISSUE THREAD

**Issue by diogoperdomo** [angular/angular#32866]
# 📚 Docs or angular.io bug report

### Description

 Inside docs, the code 

> myHero = this.heroes[0];

won't work cause the property heroes now is a array of objects

> heroes = [
>   new Hero(1, 'Windstorm'),
>   new Hero(13, 'Bombasto'),
>   new Hero(15, 'Magneta'),
>   new Hero(20, 'Tornado')
> ];

### What's the affected URL?**
https://angular.io/guide/displaying-data

### Reproduction Steps**

Using the Hero class
After importing the Hero class, the AppComponent.heroes property can return a typed array of Hero objects:

src/app/app.component.ts (heroes)
content_copy
heroes = [
  new Hero(1, 'Windstorm'),
  new Hero(13, 'Bombasto'),
  new Hero(15, 'Magneta'),
  new Hero(20, 'Tornado')
];
myHero = **this.heroes[0];**

### Expected vs Actual Behavior**

To work should be: myHero = **this.heroes[0].name;**

## 🔥 Exception or Error
<pre>My favorite hero is: [object Object]<code>

</code></pre>

**Comment by atscott** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

Immediately below the `src/app/app.component.ts`
```
heroes = [
  new Hero(1, 'Windstorm'),
  new Hero(13, 'Bombasto'),
  new Hero(15, 'Magneta'),
  new Hero(20, 'Tornado')
];
myHero = this.heroes[0];
```
there is an update to the template:
```
template: 
  <h1>{{title}}</h1>
  <h2>My favorite hero is: {{myHero.name}}</h2>
  <p>Heroes:</p>
  <ul>
    <li *ngFor="let hero of heroes">
      {{ hero.name }}
    </li>
  </ul>
```
