### ISSUE TITLE
aio: Can't find multiple content projection in docs

### ISSUE THREAD

**Issue by sod** [angular/angular#32865]
I know that you can multi project via `<ng-content select="..."`, but wanted to link to the docs for a colleague. But couldn't find it.

Searched for `ng-content` (no results), `template` (found https://angular.io/guide/template-syntax & https://angular.io/guide/architecture-components, but no mention of ng-content) `content projection` (no meaningful results).

Grepping over the aio folder in angular repo via `grep -HErn 'select\]?=' .` found nothing. Is the `select` for content projection not documented?

**Comment by Airblader** [comment]
AFAIK a few months ago there was talk about efforts to document this. Not sure anything ever came of it.

**Comment by trotyl** [comment]
Related to https://github.com/angular/angular/issues/17983

**Comment by sod** [comment]
oh thx, should have searched harder.
