### ISSUE TITLE
Style Guide - Interface names and function return type

### ISSUE THREAD

**Issue by jeevasusej** [angular/angular#32875]
I have two questions on the style guide
- For component we need to use single responsibility, do we need to follow the same for interface?
- Do we need to use return type for functions?

**Comment by dannyskoog** [comment]
First of all - we don’t **need** to follow anything in the style guide. It’s a guide, which means it’s a set of recommendations. Although I personally encourage people to follow it.

And I assume the 2 points you’re bringing up aren’t covered in the style guide. So to my next question:

Is this issue meant to request them to be added to the style guide **or** are you simply interested in peoples opinions?

If it’s the latter I can give you my POV if you’re interested :)

**Comment by StephenFluin** [comment]
The style guide doesn't specify these, as we currently believe they should be up to individual teams. We'll be revisiting the style guide holistically in the future.
