### ISSUE TITLE
In angular-cli 6, "ng serve --prod" throws error

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular#32877]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
   

>  "@angular/compiler-cli": "^6.1.9",
>     "@angular-devkit/build-angular": "~0.6.0",

### Is this a regression?

Working fine latest angular-CLI version- 8

### Description

WHile try to run my application in production mode using below command, throws below error

![angularIssue](https://user-images.githubusercontent.com/36756050/65764881-4b5e2e80-e144-11e9-88de-eda6780564d9.PNG)

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

Step 1: Download  sample
[angular6-Issue.zip](https://github.com/angular/angular/files/3662419/angular6-Issue.zip)

Step 2: Give below commands

> npm i

> ng serve --prod

**You will see the reported issue.**

## 🌍  Your Environment

**Angular Version:**
<pre><code>

    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.1.9",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "@angular/compiler-cli": "^6.1.9",
    "@angular-devkit/build-angular": "~0.6.0",
    "typescript": "~2.7.2",
    "@angular/cli": "~6.2.3",
</code></pre>

**Anything else relevant?**
Working fine in the latest angular-CLI version-8

**Comment by sarunint** [comment]
Please open the issue in [Angular CLI repository](https://github.com/angular/angular-cli).

**Comment by kumaresan-subramani** [comment]
For your information

I can't able to use this workaround in my case

https://github.com/angular/angular/issues/20815#issuecomment-361427086
