### ISSUE TITLE
$locationShim constructor calling AngularJSUrlCodec.parse with only one parameter that then calls the URL constructor with two parameters which fails on Safari

### ISSUE THREAD

**Issue by jacobbuck72** [angular/angular#32874]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/common/upgrade

### Is this a regression?

No, we've only recently started using $locationShim.

### Description
The $locationShim constructor injects AngularJSUrlCodec as its urlCodec and then makes this call:

    let parsedUrl = this.urlCodec.parse(initialUrl);

The 'parse' method takes two parameters (url, base) and inside this method the following call is made:

     const parsed = new URL(url, base);

On Safari the URL constructor throws an exception which is not intended in this case.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-issue-repro-locationshim-safari-url

## 🔥 Exception or Error
<pre><code>
Error: Invalid URL (http://localhost:4200/dashboard) with base (undefined) — vendor.js:21978 (polyfills.js, line 3969)
</code></pre>

## 🌍  Your Environment

**Angular Version: 8.2.7**

**Anything else relevant?**
This was reproduced on Safari 11 and 12, though not tested on older versions.

**Comment by gkalpak** [comment]
Fixed by #32959.
