### ISSUE TITLE
Missing space between "Component" and "will" in docs.

### ISSUE THREAD

**Issue by julianomacielferreira** [angular/angular#32873]
# 📚 Docs or angular.io bug report

### Description

 
It's just missing the space to separate the words "Component" and "will" in docs.
 - FUNDAMENTALS
      - Components & Templates
          - Templates Syntax
              - Template reference variables (#var)
                  - How a reference variable gets its value

### What's the affected URL?**
 https://angular.io/guide/template-syntax#how-a-reference-variable-gets-its-value

### Reproduction Steps**

 Accessing the affected URL and search for "Componentwill".

### Expected vs Actual Behavior**

Actual: Componentwill
Expected: **Component will**

## 📷Screenshot

![2019-09-27-031003_1920x1080_scrot](https://user-images.githubusercontent.com/49996266/65746140-62653800-e0d4-11e9-8bc8-babb66b27a34.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Browser info

Version 77.0.3865.90 (Official Build) (64-bit)

### Anything else relevant?

None.

**Comment by MrJithil** [comment]
Issue confirmed.
![image](https://user-images.githubusercontent.com/26359740/65749431-adf30280-e123-11e9-8884-fc26a0a2abf2.png)

**Comment by YuliaTsareva** [comment]
It seems to be a low-hanging fruit. Can I send a PR for this issue?

**Comment by kapunahelewong** [comment]
Just saw this, @YuliaTsareva, thank you for the PR. :) I've approved and marked for merge. Everything was in perfect order.
