### ISSUE TITLE
Discuss: Router `initialNavigation` values and defaults

### ISSUE THREAD

**Issue by vikerman** [angular/angular#32887]
Currently the allowed values for `initialNavigation` parameter for the router `ExtraOptions` are `enabled` and `disabled` (and deprecated `enabled_legacy` and `disabled_legacy`).

### Problem
`initialNavigation` parameter not only controls whether to perform initial navigation on router initialization(parse the URL and set the router state) but also whether to block the application bootstrap until the route is fully resolved (fetch lazy loaded chunks and finish rendering).

`enabled` actually means both perform initial navigation and also block application bootstrap.

The doc mentions `enabled` is the default. It is not the case. The default is `enabled_legacy` which does initial navigation but does *not* block the application bootstrap. 

`enabled` is not a good default for client side rendered applications because we want them to perform initial navigation without actually waiting for the route to be fully resolved. (Or otherwise the whole page will be blank and affect FCP and other performance metrics).

### Proposal
Have 3 states for `initialNavigation` :
- `enabledNonBlocking`: This should be the default when unspecified
- `enabledBlocking` : This is the new clearer name for `enabled`
- `disabled`: Same as before - No initial navigation or blocking

Optional:
- Deprecate `enabled` (or alternatively mention in the doc that `enabled` and `enabledBlocking` are equivalent)

Client side rendered apps should get the saner default of `enabledNonBlocking`. SSR apps will set `initialNavigation` to `enabledBlocking` to avoid flicker when directly navigating to a lazy loaded route.

**Comment by vikerman** [comment]
@Splaktar @IgorMinar @CaerusKaru

**Comment by Splaktar** [comment]
We actually just got a couple related PRs merged
- PR #32702 updates the [router/ExtraOptions#initialNavigation docs](https://next.angular.io/api/router/ExtraOptions#initialNavigation) to accurately describe the behavior and defaults
- PR #32707 adds the `InitialNavigation` type to the [API docs](https://next.angular.io/api/router/InitialNavigation)

We've also opened https://github.com/angular/angular/issues/32855 to track the need to better document how SSR apps should be configured to avoid flickering. This is one part of that, it appears that Preboot is another key part of that.

In your proposal here, does `enabled_legacy` (marked as deprecated) map to the same behavior as `enabledNonBlocking` or is there a slight difference that I am missing?

**Comment by vikerman** [comment]
Yes. `enabled_legacy` is same as `enabledNonblocking`. But we should not make `enabled`(which is same as `enabledBlocking`) as the default. Instead `enabledNonblocking` should be the default. That is different from current implementation and docs.

**Comment by vikerman** [comment]
Regarding flickering in ssr - we can only do so much to avoid it. Preboot will not stop flicker. 

Last week I debugged a site where a Google analytics experiments script was causing client to hide it's body till it was ready and was causing a flicker.

We are going to have a schematics to set `enabledBlocking` as the settings for ssr apps. This eliminates one easy source of flicker.

But there may be more - we will keep trying to locate them and add ways to avoid them.

**Comment by Splaktar** [comment]
OK, that's good to know. Hopefully we can gather enough experience to be able to create some kind of troubleshooting docs for flicker in SSR since it seems to be very commonly encountered and the solution does seem to vary across a number of scenarios.

**Comment by Splaktar** [comment]
Should this proposal include an Angular CLI migration script to migrate projects to these new values?
Should it also include removing the 2 deprecated `legacy_x` values?
I also assume that the proposal include updating the two related API docs and the SSR guide.

As for `enabled`, I think that we should deprecate it and just map it to `enabledBlocking` for now. Then it could be considered for removal following the normal deprecation policy.

Would this go into version 9?

**Comment by vikerman** [comment]
> * Should this proposal include an Angular CLI migration script to migrate projects to these new values?

Yes - It's part of the plan. Adam Plumer would be helping here

> * Should it also include removing the 2 deprecated `legacy_x` values?

Yes. And migrate them out since they have deprecated for quite some time.

> * I also assume that the proposal include updating the two related API docs and the SSR guide.

Yes

> As for `enabled`, I think that we should deprecate it and just map it to `enabledBlocking` for now. Then it could be considered for removal following the normal deprecation policy.
> 

Yes - That was my plan

> Would this go into version 9?
Yes - Seems straightforward and doable.

**Comment by IgorMinar** [comment]
This sounds good to me. Since we are not changing the default behavior for the existing apps, and just cleaning up the meaning of various flags and deprecating the confusingly named `enabled` flag, we are making the current situation strictly better without downsides.

The only breaking change is the default to the behavior of new SSR projects, without affecting the default of existing applications.

**Comment by Splaktar** [comment]
👍 from me as well!

**Comment by BruneXX** [comment]
Hi Guys, any idea about this?

`in src/app/app-routing.module.ts:10:3 - error TS2322: Type '"enabledBlocking"' is not assignable to type 'InitialNavigation'`

**Comment by CaerusKaru** [comment]
Closing as implemented as part of v11.
