### ISSUE TITLE
button action gets executed after multiple clicks

### ISSUE THREAD

**Issue by armanhadifatah** [angular/angular#32886]
Hi 

this is not that kind of bug which gives an error or something like that.

I noticed that when I click on a button in an angular app or even ionic-angular app the button will not do anything till the second click, this is relay annoying  because people think that my app has a problem or it is slow but in reality, it is a kind of bug in angular the experience is wors when you try in mobile phones.

I think maybe the problem is that angular think that I moved my finger from the button that's why it doesn't execute click action but in reality, my intention was to click on the button 

This is my simple website just click on the hamburger icon to see that 
kteblab.com

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

For what it's worth, I went to your site and could not reproduce the issue on my phone nor on my laptop.

**Comment by armanhadifatah** [comment]
Thank you for your response

I realized the problem by testing it so many times.

The problem is the area of a button in angular is small ( area of click
action or touch ) and the splash effect take some time , when you touch a
button fast and you move your finger away quickly (that is what people do)
the button think that you don't want to make the action so it will not do
that but the splash effect will show up and you think that the button
doesn't work.

One solution i came up with is to make the button as big as possible that
make a difference.

The material design of a button must be changed to that the area would be
bigger even if the text or icon is small , i know we can do that by our
selves but it will be nice if that is  out of the box.
