### ISSUE TITLE
node:21980) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead

### ISSUE THREAD

**Issue by Aeonrush** [angular/angular#32897]
# 🐞 bug report

### Affected Package
The issue is caused by package ```xhr2@0.1.4``` in version ```0.2.0``` this issue was fixed https://github.com/pwnall/node-xhr2/commit/e6529e87b266b0ff5274b1ebcab36284ea58b61b

### Is this a regression?

 No, the previous version has a same warning

### Description

 
After ```build:ssr``` and running by ```npm run serve:ssr``` and navigating to page with HttpClient request in server console I have a deprecation warning.

## 🔬 Minimal Reproduction

 
https://github.com/Aeonrush/angular-universal-buffer-api-deprecation
1. ```npm run build:ssr```
2. ```npm run serve:ssr```
3. Navigate to http://localhost:4200/u/aeonrush
4. See in "serve" terminal for warning

## 🔥 Exception or Error
<pre><code>(node:20868) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 8.3.6
Node: 10.16.3
OS: linux x64
Angular: 8.2.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.6
@angular-devkit/build-angular              0.803.6
@angular-devkit/build-optimizer            0.803.6
@angular-devkit/build-webpack              0.803.6
@angular-devkit/core                       8.3.6
@angular-devkit/schematics                 8.3.6
@angular/cli                               8.3.6
@ngtools/webpack                           8.3.6
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.3.6
@schematics/update                         0.803.6
rxjs                                       6.4.0
typescript                                 3.5.3
webpack                                    4.39.2
</code></pre>

**Anything else relevant?**

**Comment by djabif** [comment]
hey @Aeonrush did you solve it? I'm facing the same issue :(

**Comment by ayyash** [comment]
Personally, I found the problem in `@angular/platform-server` package, that depends on the older version of xhr2... https://github.com/angular/angular/blob/master/packages/platform-server/package.json

` "xhr2": "^0.1.4"`

Unfortunately this has not changed in 8.3, so what I did is got my hands dirty, went into the node_modules and installed `xh2 0.2.0` instead, hoping that the next version of angular would fix this.

**Comment by JulienM-77** [comment]
I confirm, I force xhr2 update in platform-serve and no other error message
thanks @ayyash for your tips
Next step update the package for next release

**Comment by CarlosTorrecillas** [comment]
@JulienM-77 , @ayyash , which version of Angular are you using? I faced the same issue however when I updated the xhr2 package to v0.2.0 I don't get the warning anymore but my app still hangs. I'm on This is my package.json dependency section:
```
"dependencies": {
    "@angular/animations": "8.2.12",
    "@angular/common": "8.2.12",
    "@angular/compiler": "8.2.12",
    "@angular/core": "8.2.12",
    "@angular/forms": "8.2.12",
    "@angular/platform-browser": "8.2.12",
    "@angular/platform-browser-dynamic": "8.2.12",
    "@angular/platform-server": "8.2.12",
    "@angular/router": "8.2.12",
    "@nguniversal/express-engine": "8.1.1",
    "@nguniversal/module-map-ngfactory-loader": "8.1.1",
    "express": "4.17.1",
    "rxjs": "6.5.3",
    "tslib": "1.10.0",
    "zone.js": "0.10.2",
    "@fortawesome/angular-fontawesome": "0.5.0",
    "@fortawesome/fontawesome-svg-core": "1.2.25",
    "@fortawesome/free-brands-svg-icons": "5.11.2",
    "@fortawesome/free-solid-svg-icons": "5.11.2",
    "ngx-cookie": "4.1.2",
    "bootstrap": "4.3.1",
    "web-animations-js": "2.3.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.803.14",
    "@angular/cli": "8.3.14",
    "@angular/compiler-cli": "8.2.12",
    "@angular/language-service": "8.2.12",
    "@types/node": "12.6.8",
    "@types/jasmine": "3.3.15",
    "@types/jasminewd2": "2.0.6",
    "codelyzer": "5.1.0",
    "jasmine-core": "3.4.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "4.1.0",
    "karma-chrome-launcher": "3.0.0",
    "karma-coverage-istanbul-reporter": "2.1.0",
    "karma-jasmine": "2.0.1",
    "karma-jasmine-html-reporter": "1.4.2",
    "protractor": "5.4.2",
    "ts-loader": "6.2.1",
    "ts-node": "8.4.1",
    "tslint": "5.20.0",
    "typescript": "3.4.3",
    "webpack-cli": "3.3.9"
  }
```

**Comment by JulienM-77** [comment]
Hey @CarlosTorrecillas, I didn't add xhr2 v2 to my package. json. 
I got the source code of @angular/platform-server (my current version is v8.2.14) in my project. Change the json package of it to update the xhr2 version to v2 and use this version in my app.server.module. 
To be watched when upgrading angular version to follow the evolution while waiting for a patch.

**Comment by nimatullah** [comment]
Hello guys, I have the same issue. If I update **@angular/platform-server**, will it works?

**Comment by ayyash** [comment]
@nimatullah no, not yet, u have to do this manually, install xhr2 latest, then in package-lock change

from this 
```
 "@angular/platform-server": {
      "version": "8.2.14",
      "resolved": "...",
      "integrity": "...",
      "requires": {
        "domino": "^2.1.2",
        "tslib": "^1.9.0",
        "xhr2": "^0.1.4"
      },
      "dependencies": {
        "xhr2": {
          "version": "0.1.4",
          "resolved": "https://registry.npmjs.org/xhr2/-/xhr2-0.1.4.tgz",
          "integrity": "..."
        }
      }
    },
```

to this

```
 "@angular/platform-server": {
      "version": "8.2.14",
      "resolved": "...",
      "integrity": "...",
      "requires": {
        "domino": "^2.1.2",
        "tslib": "^1.9.0",
        "xhr2": "^0.2.0"
      }
    },
```

**Comment by borriej** [comment]
im having the same issue today. We upgraded our Azure Node.exe from 10 to 12.13

and got
```
(node:21624) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
when using api calls

dependencies
```

  "dependencies": {
    "@angular-redux/store": "^9.0.0",
    "@angular/animations": "^8.2.5",
    "@angular/cdk": "^7.1.0",
    "@angular/common": "^8.2.5",
    "@angular/compiler": "^8.2.5",
    "@angular/core": "^8.2.5",
    "@angular/forms": "^8.2.5",
    "@angular/material": "^7.1.0",
    "@angular/material-moment-adapter": "^7.2.2",
    "@angular/platform-browser": "^8.2.5",
    "@angular/platform-browser-dynamic": "^8.2.5",
    "@angular/platform-server": "^8.2.5",
    "@angular/router": "^8.2.5",
    "@ng-select/ng-select": "^2.10.1",
    "@ngu/carousel": "^1.5.5",
    "@nguniversal/express-engine": "^8.0.0-rc.1",
    "@nguniversal/module-map-ngfactory-loader": "^8.1.1",
    "@ngx-loading-bar/core": "^4.2.0",
    "@ngx-loading-bar/http-client": "^4.2.0",
    "@ngx-loading-bar/router": "^4.2.0",
    "@swimlane/ngx-datatable": "^16.0.2",
    "axios": "^0.18.0",
    "better-npm-run": "^0.1.1",
    "bootstrap": "^4.3.1",
    "core-js": "^2.5.4",
    "currency.js": "^1.2.1",
    "glob": "^7.1.6",
    "hammerjs": "^2.0.8",
    "highcharts": "^7.2.0",
    "highcharts-angular": "^2.4.0",
    "jspdf": "^1.5.3",
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "ng2-dragula": "^2.1.1",
    "ngx-avatar": "^3.7.0",
    "ngx-bootstrap": "^5.1.2",
    "ngx-currency": "^1.5.0",
    "ngx-moment": "^3.2.0",
    "redux": "^4.0.1",
    "rxjs": "~6.5.3",
    "smoothscroll-polyfill": "^0.4.3",
    "ts-loader": "^6.0.4",
    "ts-money": "^0.4.6",
    "tslib": "^1.10.0",
    "typescript-string-operations": "^1.3.1",
    "uuid": "^3.3.3",
    "zone.js": "~0.9.1"
  },
```

**Comment by vipinjn24** [comment]
When is this issue going to get resolved?

**Comment by vipinjn24** [comment]
Well i did updated xhr2 and i can see that the dev server started to roll-out responses faster than before.
Thanks for the permanentish solution :)

**Comment by vipinjn24** [comment]
ROFL I was searching for a solution for my own code where i used Buffer.from.
Here i got to know the real issue.

When is this issue going to get resolved?

Well i did updated xhr2 and i can see that the dev server started to roll-out responses faster than before.
Thanks for the permanentish solution :)

**Comment by tayambamwanza** [comment]
Is everyone still experiencing this issue? Because I am.

**Comment by vipinjn24** [comment]
@tayambamwanza This is a non critical issue and can be resolved by just installing latest xhr2.

issue the below command to resolve this issue.
`npm i xhr2`

**Comment by tayambamwanza** [comment]
@vipinjn24 Thank you, I realised that's it's a warning and not an outright error, so application will still run regardless, hopefully it will be resolved in a release.

Appreciate you following up.

**Comment by CarlosTorrecillas** [comment]
To me this is a critical issue since I got my Angular 9 SSR hanging and the CPU goes to the roof. In my case, this is happening when navigating straight to a lazy loaded module and invoking the HTTPClient. If you load the "home page" and then navigate to a lazy loaded route the problem does not exist.

For reference I have:
node v10.16.2 
Angular 9.0.6 
Universal 9.0.2

I'm importing the HttpClientModule only once in the AppModule. I think this should be addressed.

**Comment by vipinjn24** [comment]
@CarlosTorrecillas I am saying that this issue can be resolved by installing xhr2 manually. This is the reason this is not critical.

Please issue the below command.
`npm i xhr2 --save`

**Comment by CarlosTorrecillas** [comment]
@vipinjn24 indeed, in fact if you upgrade to angular 9.1.1 it does contain the update. My issue comes to the usage of the HTTPClient on a lazy loaded module which is causing the application to hang and sets the cpu usage to 100%

**Comment by vipinjn24** [comment]
@CarlosTorrecillas Then you should take this to a forum may be stackoverflow.

Also the just to give you a hint, if you are using ngrx effects then check if any effect is called without dispatch: false and no returned dispatch in the effect itself. This makes even i9 CPU touch the heights.

**Comment by CarlosTorrecillas** [comment]
Thanks for the tip. Indeed I took it to StackOverflow: https://stackoverflow.com/q/61188087/5293466 and still haven’t got a clue as to why this is happening. I’ve just got a standard get promise

**Comment by umairjameel1** [comment]
I am using angular 7 and I have tried all the option given above but still getting same errors. I have updated the version of xhr2 to 0.2.0 and also in package-lock file. 

I have analyzed that when I build my app with `npm run build:ssr` and try to run `npm run serve:ssr`, there get a file generated dist/server.js. There is still `new Buffer` written at almost 6 places in file server.js.

**Comment by sispor** [comment]
> @CarlosTorrecillas I am saying that this issue can be resolved by installing xhr2 manually. This is the reason this is not critical.
> 
> Please issue the below command.
> `npm i xhr2 --save`

It´s work for my project: Angular 9, Angular Universal

**Comment by CarlosTorrecillas** [comment]
@sispor thanks for this. I was puzzled about the error and it turned out to be something different. In fact it was related to an issue I have already raised with the Angular Universal team @platform/server section. It had to do with an issue that happens when an angular animation executes the “done” event and it’s all mixed with a HTTP call...

**Comment by CaerusKaru** [comment]
Closing this since latest versions of Angular used the updated version of `xhr2`.
