### ISSUE TITLE
display some text when div is empty  in angular 8....my div has some bootstrap 4 alerts ....

### ISSUE THREAD

**Issue by versatilePrakash** [angular/angular#32894]
<div class="card shopping">

                <div class="alert alert-dismissible d-flex flex-wrap">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <div class="image "><img src="../../IMG_6518.jpg" height="50px" width="50px"></div>
                    <div class="title px-2">
                        <span class="dark" style="font-size:17px; font-weight: 500;">MacBook Air</span>
                    </div>
                    <div class="price">
                        <h5 class="dark "><span style="font-size:20px;">1200</span><span style="font-size:16px;">$</span></h5>
                    </div>
                    <div class="quantity">
                        <div class="d-flex row-wrap">
                            <div class=" mt-2 ">
                                <p class="font-size:15px; font-weight:500;">Qty.</p>
                            </div>
                            <div>
                                <input class="form-control ml-2 " type="number ">
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="empty ">
                    <h5>Your cart is empty!!!</h5>
                </div>
                <div class="alert alert-dismissible d-flex flex-wrap">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <div class="image "><img src="../../IMG_6518.jpg" height="50px" width="50px"></div>
                    <div class="title px-2">
                        <span class="dark" style="font-size:17px; font-weight: 500;">MacBook Air</span>
                    </div>
                    <div class="price">
                        <h5 class="dark "><span style="font-size:20px;">1200</span><span style="font-size:16px;">$</span></h5>
                    </div>
                    <div class="quantity">
                        <div class="d-flex row-wrap">
                            <div class=" mt-2 ">
                                <p class="font-size:15px; font-weight:500;">Qty.</p>
                            </div>
                            <div>
                                <input class="form-control ml-2 " type="number ">
                            </div>
                        </div>
                    </div>
                </div>

**Comment by dannyskoog** [comment]
Could you please ellaborate on what you actually want to achieve? It’s not clear from your original post, that’s why

**Comment by Prakashkhadka7** [comment]
When bootstrap alerts are closed the div becomes empty .....and at the instant i want display text ..."the div is empty"

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
