### ISSUE TITLE
UI and form values are not in sync

### ISSUE THREAD

**Issue by yugRakesh** [angular/angular#32907]
### Affected Package
ReactiveFormsModule / FormGroup Packages as the source of the bug:
 @angular/forms
The issue is caused by package @angular/forms

### Description
When one drop down is dependent on another, If we are changing values based on first drop down, the object of FormGroup "fg" will keep the previously selected value of second drop down though we have updated the values and HTML content is showing some another values, and the values preserved is no longer part of any drop down then after. 
We need to forcefully reset the value of that object which is not realistic. Form object should preserve the values if exist. but your UI is changed now, ts file is also contains new values. 

When i am imposing validation on the second drop down, and it is not selected, yet i am able to submit the form with previously selected (historic) value, second drop down is required to select, and html shows it empty but yet form is getting submitted with empty value.

## Minimal Reproduction
Editor URL: https://stackblitz.com/edit/angular-yuxk9b
App URL: https://angular-yuxk9b.stackblitz.io
Embed URL: https://stackblitz.com/edit/angular-yuxk9b?xmbed=1&file=src/app/app.component.html

## Environment
Angular Version:
8.3.5
![1](https://user-images.githubusercontent.com/932476/65853800-58636380-e378-11e9-8084-110fa4cc3078.JPG)
![2](https://user-images.githubusercontent.com/932476/65853801-58636380-e378-11e9-86ab-f16bfcc33d84.JPG)
![expected_1](https://user-images.githubusercontent.com/932476/65857034-a54b3800-e380-11e9-8da8-73127fe39f53.JPG)
![unexpected_2](https://user-images.githubusercontent.com/932476/65857035-a54b3800-e380-11e9-8e02-ab07fc743e92.JPG)
![unexpected_3](https://user-images.githubusercontent.com/932476/65857509-a466d600-e381-11e9-86bf-9bed2f320b8f.JPG)

**Comment by dannyskoog** [comment]
Hi @yugRakesh. I had a look at your blitz and it seems to be working as per design.

If you want to avoid your 2nd dropdown from slipping through validation you need to reset it each time you re-populate it. Basically by invoking `this.fg.get(’Two_ID’).reset()`.

As to my knowledge Reactive Forms are meant to react either to UI interaction or programmatic use of `FormGroup` and/or `FormControl`.

**Comment by yugRakesh** [comment]
Hi @dannyskoog, 

I have already used reset() in my project, but its looks like a patch. If you observe the form, UI and Backend Program, You could not find the preserved value by object, if one of my another case UI is shown some other value and form object is sending previously selected value which is misleading, User doesn't know the background process and state of different object.

It will lead to mis-interpretation, and debugging of such issues are very tough for new developers. If i am talking about my case, 4 developers were facing this issue since few days and they come up with problem statement.

Framework is there to simplify the programming. If angular team is able to update the flow then that will minimize the time of many developer.

**Comment by dannyskoog** [comment]
I see. Sure, those are fair points! Then this issue is more like a feature request, correct?

So how would you like the framework to behave in the scenario that you posted initially?

**Comment by yugRakesh** [comment]
Solution is simple, Object of formgroup "fg" is keeping selected values of dropdown, but when html is getting updated with new values form group object should automatically reset values when drop down values or any DOM object value is getting changed. It is already happening for text box and other objects, so the same behavior is expected from drop down control.

**Comment by dannyskoog** [comment]
Sure. I understand your point. Let’s see if someone is interested in owning such feature request, if not yourself?

**Comment by Airblader** [comment]
IMHO this would be a problematic change causing a lot of issues. A very common case is that options are loaded asynchronously and this would cause a set value to disappear.

It's also not at all invalid that a drop-down has a value that isn't carried by any of the possible options. This is also something that happens a lot in real life applications.
