### ISSUE TITLE
Capture cancelled request event with Interceptor

### ISSUE THREAD

**Issue by NumericFactory** [angular/angular#32909]
# **The problem**
No event or information from **HttpClient** or **Interceptor** when an Http Request is cancelled. 

# **Solution from vanilla JS**
With Vanilla JS we have a solution with readystate and status code.
"...When a request is aborted, its readyState is changed to XMLHttpRequest.UNSENT (0) and the request's status code is set to 0."
(source : https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort)

# **proposition in Angular**
I suggest a new HttpEventType.cancel we could write easily in intercept method, like this:

``` 
   // In intercept() Method...

   return next.handle(req).pipe(tap(
   (ev: HttpEvent<any>) => {
      if (ev.type === HttpEventType.cancel) {
        // do something
      }
    })
  )
``` 
i hope this issue will be resolved quickly ☺

**Comment by NumericFactory** [comment]
Have you got a best solution to resolve this problem @ericmartinezr  ?

**Comment by ericmartinezr** [comment]
I have not to be honest, but I'm pretty sure @lazarljubenovic has a good one.

**Comment by mlc-mlapis** [comment]
@NumericFactory Isn't `complete` way for it?

**Comment by maddykws** [comment]
How are you cancelling a HTTP request from the interceptor? Can you add full code here?

**Comment by NumericFactory** [comment]
@maddykws  : No, i cancel http requests on input search in a component.ts like this 

```
getResults() {
    return this.searchCompanyDataOnSirene$
                .pipe(
                  debounceTime(700),
                  distinctUntilChanged(),
                  switchMap(term => {
                    console.log(term.length);
                    if(term.length<=3) {
                      // do nothing
                      return of([]);
                    }
                    else {
                      return term?this.searchOnSireneApiService.searchEntries(term):of([]);
                    }       
                  })
                )               
  }
```

and i would like capture "cancelled http request event" in Intercept method of my Interceptor, to set a "loadingSubject" to false when an httpRequest is cancelled

**Comment by trotyl** [comment]
There is an RxJS operator called [`finalize`](https://rxjs.dev/api/operators/finalize).

**Comment by alxhub** [comment]
I've done this in the past using a construct like this:

```typescript
function tapUnsubscribe<T>(callback: () => void) {
  return function(obs: Observable<T>) => {
    return new Observable(subscriber => {
      let sub = obs.subscribe(value => subscriber.next(value), err => subscriber.error(err), () => subscriber.complete());
      return () => {
        // This handler is called when the client unsubscribes (cancels).
        callback();
        sub.unsubscribe();
      };
    });
  };
}
