### ISSUE TITLE
The "L" letter should be lowercase in "HTMLELement" in docs.

### ISSUE THREAD

**Issue by julianomacielferreira** [angular/angular#32917]
# 📚 Docs or angular.io bug report

### Description

 
The letter "L" should be lowercase in the interface name "HTMLELement".
- FUNDAMENTALS 
   - Components & Templates 
      - Angular Elements
         -  Typings for custom elements

### What's the affected URL?**
 
[https://angular.io/guide/elements#typings-for-custom-elements](https://angular.io/guide/elements#typings-for-custom-elements)

### Reproduction Steps**

Accessing the affected URL and search for "HTMLELement". It's the first of the four returned results.

### Expected vs Actual Behavior**

Actual: HTMLELement
Expected: **HTMLElement**

## 📷Screenshot

![2019-09-30-142022_1920x1080_scrot](https://user-images.githubusercontent.com/49996266/65900990-97e87a80-e38d-11e9-8823-dcac210a534c.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Browser info

Google Chrome - Version 77.0.3865.90 (Official Build) (64-bit)
### Anything else relevant?

None.

**Comment by julianomacielferreira** [comment]
Just to add, in the same section, I think that "HTMLELementTagNameMap" should have lowercase "L", too.

![2019-09-30-150713_1920x1080_scrot](https://user-images.githubusercontent.com/49996266/65904089-16481b00-e394-11e9-812e-13895adfb2df.png)

Thank you very much!
Juliano.

**Comment by joshuacolvin** [comment]
I'd be happy to fix this
