### ISSUE TITLE
ngFor not update view unless click on view Angular

### ISSUE THREAD

**Issue by kidqn** [angular/angular#32929]
# 🐞 bug report

### Affected Package
 The issue is caused by package @angular/....
    "@angular/common": "7.2.15",
    "@angular/compiler": "7.2.15",
    "@angular/core": "7.2.15",
    "@angular/fire": "^5.2.1",
    "@angular/forms": "7.2.15",
    "@angular/http": "7.2.15",
    "@angular/platform-browser": "7.2.15",
    "@angular/platform-browser-dynamic": "7.2.15",

### Description
Angular breaks detection changes if a new window open like firebase auth popup.

## 🔬 Minimal Reproduction
```
 this.allInfo$.subscribe(data => {
      this.allInfos = data;
    });
```
```
<div (click)="addInfo(social)" *ngFor="let info of allInfos"
         [ngClass]="{'active': info.connected}">
        <span>{{info.name}} {{info.connected}}</span>
      </div>
```
When I click addInfo, app will open thirdparty dialog like firebase login (AngularFireAuth), if success will return new data and update to store allInfo$ I tracked. But the view does not change? Is that angular bug?
NOTE:  View change if I click somewhere on screen.  My angular version 7.
Not success solution I tried: detectChanges, markForCheck, cloneDeep, re-assign, trackBy, ONLY click trigger re-rendering. This case ONLY happens when a new window open and return a promise.

**Comment by mlc-mlapis** [comment]
@kidqn Because of the event comes from outside of Zone, so you have to use `this._ngZone.run(...)`.

**Comment by kidqn** [comment]
> @kidqn Because of the event comes from outside of Zone, so you have to use `this._ngZone.run(...)`.
Can I use without _ngZone, because my app not use it until now?

**Comment by mlc-mlapis** [comment]
@kidqn Your app is using the Zone by default.

**Comment by kidqn** [comment]
> @kidqn Your app is using the Zone by default.

Okay thank you! My issue was resolved.
