### ISSUE TITLE
AppComponent.html:1 ERROR RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by versatilePrakash** [angular/angular#32926]
it  compiles successively but cant display the  form  content.....
red underlined on :      f.username:
[authentication.zip](https://github.com/angular/angular/files/3674390/authentication.zip)
  
                <div *ngIf="submitted && f.username.errors" class="invalid-feedback">
                        <div *ngIf="f.username.errors.required">Username is required</div>
                    </div>

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
