### ISSUE TITLE
TypeError: actual.subscribe is not a function

### ISSUE THREAD

**Issue by 3gwebtrain** [angular/angular#32928]
Here is my test spec file:

import { async, ComponentFixture, TestBed } from '@angular/core/testing';
import { Store, select } from '@ngrx/store';
import { cold, getTestScheduler, hot } from 'jasmine-marbles';
import { RouterTestingModule } from '@angular/router/testing';
import { HttpClientModule } from '@angular/common/http';
import { ShellViewProgMgmtComponent } from './shell-view-prog-mgmt.component';
import { ViewProgMgmtComponent } from './../../components/view-prog-mgmt/view-prog-mgmt.component';
import { StateSetupConfigModel } from './../../models/model.programmeMngt';
import { provideMockStore, MockStore } from '@ngrx/store/testing';

describe('ShellViewProgMgmtComponent', () => {

    let component: ShellViewProgMgmtComponent;
    let fixture: ComponentFixture<ShellViewProgMgmtComponent>;
    let mockStore: MockStore<StateSetupConfigModel>;

    const loadingState = {
        mockName: ''
    } as StateSetupConfigModel;

    beforeEach(async(() => {
        TestBed.configureTestingModule({
            declarations: [ShellViewProgMgmtComponent, ViewProgMgmtComponent],
            imports: [HttpClientModule, RouterTestingModule],
            providers: [provideMockStore({ initialState: loadingState })]
        })
        .compileComponents();

        mockStore = TestBed.get(Store);

    }));

    beforeEach(() => {

        fixture = TestBed.createComponent(ShellViewProgMgmtComponent);
        component = fixture.componentInstance;
        fixture.detectChanges();

    });

    it('should display name as empty', async(() => {

        const expected = cold('a', { mockName: '' });
        expect(component.mockName).toBeObservable(expected); //issue happens

    }));

});

when i run this test file I am getting an error as TypeError: actual.subscribe is not a function
![mock-issue](https://user-images.githubusercontent.com/6211826/65935024-31b73280-e435-11e9-8c33-37e1d2eb1e6b.JPG)
any one help me to fix this issue?

**Comment by dannyskoog** [comment]
Hi @3gwebtrain. This sounds more like a support issue to me. So please re-post it on StackOverflow please. Thank you!

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
