### ISSUE TITLE
Missing space between the words "eventhandlers" in docs.

### ISSUE THREAD

**Issue by julianomacielferreira** [angular/angular#32924]
# 📚 Docs or angular.io bug report

### Description

 
It's just missing a space between the words "eventhandlers".
- FUNDAMENTALS 
   - Components & Templates 
      - Attribute Directives
         -  Respond to user-initiated events

### What's the affected URL?**
 
[https://angular.io/guide/attribute-directives#respond-to-user-initiated-events](https://angular.io/guide/attribute-directives#respond-to-user-initiated-events)

### Reproduction Steps**

Accessing the affected URL and search for "eventhandlers".

### Expected vs Actual Behavior**

Actual: eventhandlers
Expected: **event handlers**

## 📷Screenshot

![2019-09-30-191307_1920x1080_scrot](https://user-images.githubusercontent.com/49996266/65920772-6932ca00-e3b6-11e9-8a0b-6c8bbad4f3b9.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Browser info

Google Chrome - Version 77.0.3865.90 (Official Build) (64-bit)
### Anything else relevant?

None.

**Comment by Showtim3** [comment]
@julianomacielferreira @atscott Can i help with this? This will be my first contribution here

**Comment by Showtim3** [comment]
@kapunahelewong @atscott Can i help with this? This will be my first contribution here

**Comment by kapunahelewong** [comment]
Thatʻd be great, @atscott! If you like, you can refer to [my notes for my own workflow](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca) for the process and where stuff is. Let me know if you have any questions and please feel free to tag me in the PR. Thanks!

**Comment by Showtim3** [comment]
@kapunahelewong maybe you meant @Showtim3 ?

**Comment by kapunahelewong** [comment]
Oh yes, youʻre right, @Showtim3. Thank you. Edited above.
