### ISSUE TITLE
Angular update guide website has wrong link 

### ISSUE THREAD

**Issue by dkosasih** [angular/angular#32927]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

The link on one of the section that talk about replacing `/deep/` with `::ng-deep` in the update guide on Angular.io (https://update.angular.io/#7.0:8.0) is incorrect. 
![image](https://user-images.githubusercontent.com/8027235/65926605-6af1a180-e439-11e9-9980-4ae4091f6e92.png)
at the moment ` read more about angular component styles and ::ng-deep` link is going to `https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html` this should be going `https://www.chromestatus.com/features/6750456638341120` I supposed?

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by tieppt** [comment]
I think, the link for this segment will be `https://angular.io/guide/component-styles`

**Comment by Splaktar** [comment]
This is being tracked in https://github.com/StephenFluin/angular-update-guide/issues/37.

**Comment by dkosasih** [comment]
This seems to be fix on master. It should be out with the next build.
