### ISSUE TITLE
usage of "as" in html templates is not flexible enough.

### ISSUE THREAD

**Issue by andreElrico** [angular/angular#32934]
# 🚀 feature request

[STACKBLITZ](https://stackblitz.com/edit/angular-76jusr)

We can use `"as"` in our templates like `<ng-container *ngIf="timer$ | async as t$">`

+ As you can see in my Stackblitz I can't use `"as"` like this to avoid multiple subscriptions.
+ Also *ngIf's `"as"` does not allow multiple declarations:
 `<ng-container *ngIf="obs1$ | async as o1$; obs2$ | async as o2$">`
+ we would have to nest two ng-containers

### Describe the solution you'd like

lets create a directive:

`[NgVoid]`

+ where we can have multiple declarations and solve my above issue with only one subscription.

```
<ng-container *ngVoid="timer$ | async as t$">
....

```
### Describe alternatives you've considered
As alternatives I have two subs, or two more specialised streams?

Whats your take on this?

# COPY OF STACKBLITZ CODE
(HTML)
```
Works and is the desired result!!!
<br>

    <button
      [disabled]="(timer$ | async) != 0" mat-button (click)="onCancel()">
          <div *ngIf="!(timer$ | async); else countDown;">close</div>
          <ng-template #countDown>{{timer$ | async}}</ng-template>
    </button>

<hr>
Does not work

<br>
<span innerText="
    <ng-container *ngIf='timer$ | async as t$ || true'>
    <button [disabled]='t$ != 0' mat-button  (click)='onCancel()' >
        <div *ngIf='!t$; else countDown;'>close</div>
        <ng-template #countDown>{{t$}}</ng-template>
    </button>
    </ng-container>
"></span>

<!--    
<ng-container *ngIf="timer$ | async as t$ || true">
  <button [disabled]="t$ != 0" mat-button (click)="onCancel()" style = "float: right;">
      <div *ngIf="!t$; else countDown;">close</div>
      <ng-template #countDown>{{t$}}</ng-template>
  </button>
</ng-container>
-->
<hr>
<br>

This here has a different outcome
<br>
<ng-container *ngIf="(timer$ | async as t$); (timer$ | async as t2$)">
  <button [disabled]="t$ != 0" mat-button (click)="onCancel()">
      <div *ngIf="!t$; else countDown;">close</div>
      <ng-template #countDown>{{t$}}</ng-template>
  </button>
</ng-container>
```

(ts)
```
import { Component, OnInit } from '@angular/core';
import { Observable, timer } from 'rxjs';
import { take, map, tap } from 'rxjs/operators';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent implements OnInit {
  name = 'Angular';

  timer$: Observable<number>;

  ngOnInit() {

    const start = 5;
    this.timer$ = timer(0, 1000)
    .pipe(
      map(i => start - i),
      take(start + 1),
    );
  }



}
```

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/15280

---

https://github.com/angular/angular/issues/15280#issuecomment-430550596 is for your case.

**Comment by andreElrico** [comment]
thank you sir! this was helpful. Somehow I have a hard time using the seach function of github. Never shows me what im searching for. As there is a solid implementation availible I will close this. However it would be nice to have this feature "ON BORD".
