### ISSUE TITLE
onChange() not triggered anymore via @Directive property binding

### ISSUE THREAD

**Issue by jhades** [angular/angular#3293]
This is a [repo](https://github.com/jhades/directive-binding-issue) with running code to reproduce the issue, check it's README for running instructions.

The issue is that I have a custom directive, to which i'm trying to pass in some input value via a property binding in a component template:

    <div>
        <button (click)="onClick()">Trigger @Directive binding</button>
       <div custom-directive [input]="inputData">
   </div> 

When the button get's clicked, a click handler get's executed and the property input data is changed:

    console.log("the click handler gets triggered ..");
    this.inputData = Math.random();

But the custom directive never sees the new value via its `onChange()`lifecycle callback, like it used to. This is the custom directive:

    @Directive({
        selector:'[custom-directive]',
        properties: ['input'],
        lifecycle: [onChange]
    })
    export class Custom {
        constructor() {
            console.log('directive constructor is called..');
        }

        onChange(changes) {
            // this never gets logged
            console.log(changes);
        }
    }

**Comment by jomeier** [comment]
I found an enum LifecycleEvent where onChange sitzs in.
...
import {LifecycleEvent} from 'angular2/angular2';

@Directive({
  ...
  lifecycle: [LifecycleEvent.onChange]
})
...
might do it?

**Comment by jhades** [comment]
That was it, thanks!
