### ISSUE TITLE
Zone: No change detection after Electron (popup)menu events in Angular/cli project

### ISSUE THREAD

**Issue by pamtbaau** [angular/angular#32932]
# 🐞 bug report

### Affected Package

The issue resurfaces when using package @angular/cli

### Is this a regression?

I don't know, I have never used angular-cli before.
However, it **does** work in Angular projects created without @angular/cli, but not in projects generated using 'ng new'

### Description
Change detection does not work in native Electron (popup)menus events when project is created using 'ng new'.

The issue is the same as [#13363](https://github.com/angular/angular/issues/13363) and [#31668](https://github.com/angular/angular/issues/31668). These projects do not use angular-cli and issues have been solved using the patch: 'zone.js/dist/zone-patch-electron'.

However, when project is created using 'ng new', the problem arises again.

## 🔬 Minimal Reproduction

Reproduction of issue can be found in repository [angular-cli-electron-menus](https://github.com/pamtbaau/angular-cli-electron-menus)

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.6
Node: 12.5.0
OS: win32 x64
Angular: 8.2.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.6
@angular-devkit/build-angular     0.803.6
@angular-devkit/build-optimizer   0.803.6
@angular-devkit/build-webpack     0.803.6
@angular-devkit/core              8.3.6
@angular-devkit/schematics        8.3.6
@angular/cli                      8.3.6
@ngtools/webpack                  8.3.6
@schematics/angular               8.3.6
@schematics/update                0.803.6
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

**Comment by JiaLiPassion** [comment]
@pamtbaau, please inport `zone.js/dist/zone-patch-electron` package. If CD still not work, please tell me.

**Comment by pamtbaau** [comment]
@JiaLiPassion Patch is already imported. See './src/polyfills.ts':
```
import 'zone.js/dist/zone';  // Included with Angular CLI.
import 'zone.js/dist/zone-patch-electron';
```

**Comment by JiaLiPassion** [comment]
Sorry, I didn't read the issue clearly, I will check it.

**Comment by pamtbaau** [comment]
Could you please clarify what you mean by "'zone-patch-electron' will not be included"? When I debug the project, breakpoints in your patch are being hit at lines: 31, 35, 39

Not sure if this makes a difference, but I use the custom builder [@angular-builders/custom-webpack](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack) to build the project. This builder runs the default Angular builder, but allows injections into Angular's @angular-devkit/build-angular builder.

I use it to inject 'target:'electron-renderer' into webpack, else the project cannot run in Electron.

**Comment by JiaLiPassion** [comment]
@pamtbaau, I am not sure I understand your question.
So you mean.
1. you are using `ng new` to create a new project.
2. you `import zone-patch-electron` by yourself.
3. and electron menu will not trigger CD.

is that correct?

**Comment by pamtbaau** [comment]
@JiaLiPassion, Yes, 

1. I used `ng new` to create a new project
2. I modified the file './src/polyfills.js' to import 'zone.js/dist/zone-patch-electron', as follows:
  ```
  import 'zone.js/dist/zone';  // Included with Angular CLI.
  import 'zone.js/dist/zone-patch-electron';
  ```
3. And did some more to make app ready for electron (see [README](https://github.com/pamtbaau/angular-cli-electron-menus) in repo), like:
   - Modified `angular.json` to replace the default builder by custom webpack builder
   - Modified `angular.json` to modify outputPath
   - Added `index.js` to setup main process.
   - ...
4. And electron menu will not trigger CD

**Comment by JiaLiPassion** [comment]
@pamtbaau, ok, could you provide a reproduce repo? Thanks.

**Comment by pamtbaau** [comment]
@JiaLiPassion  As asked by the template when opening this issue....

Reproduction of issue can be found in repository [angular-cli-electron-menus](https://github.com/pamtbaau/angular-cli-electron-menus)

**Comment by JiaLiPassion** [comment]
Got it, thanks! Sorry I didn't notice you already provided 😅

**Comment by pamtbaau** [comment]
@JiaLiPassion Any luck?

**Comment by arturovt** [comment]
@pamtbaau If you upgrade the `zone.js` version to `0.10.0` then the issue goes away on its own :) P.S. I checked it in your example. The new `zone.js` version patches the `ipcRenderer.on` and those methods are invoked in the Angular zone.

**Comment by pamtbaau** [comment]
@arturovt Thanks a lot! That upgrade of `zone.js` did indeed fix the issue... It's official, you may drop the "Junior"

I'm surprised that that `zone.js` 0.10.x wasn't in my repo which is build Oct. 1st, while `zone.js` was already out in September... Oh well...

**Comment by JiaLiPassion** [comment]
Thanks @arturovt for confirmation.
And @pamtbaau , I will close this one, and please create issue if you find any other problems.
