### ISSUE TITLE
A mistake in the docs - in the description of the Component Class section

### ISSUE THREAD

**Issue by fouaddev** [angular/angular#32948]
# 📚 Docs or angular.io bug report

### Description
In the _Component Class_ section, the reference of angular in relation to typescript should be angular instead of angularJS.

### What's the affected URL?**

https://angular.io/guide/ajs-quick-reference

### Reproduction Steps**
Go to the link above and scroll down to the _Component class_ section. Read its description.

### Expected vs Actual Behavior**

Expected:

NOTE: If you are using TypeScript with Angular, you must use the export keyword to export the component class.

Actual Behavior:

NOTE: If you are using TypeScript with AngularJS, you must use the export keyword to export the component class.

## 📷Screenshot

![angular_mistake](https://user-images.githubusercontent.com/26067937/66011784-758c5500-e492-11e9-82e6-0baeb78d96e8.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Browser info
Version 77.0.3865.90 (Official Build) (64-bit)

### Anything else relevant?
This is just a text mistake in the docs, not a code error.

**Comment by ODAVING** [comment]
Hello, 
I'm fairly new to the open source community! however, I've made a PR for this issue, please let me know if there are any changes that need to be done. 

Additionally, the form the PR has me fill out is a bit confusing, so I'd appreciate some insight in that as well.
Thanks!

**Comment by fouaddev** [comment]
Hey ODAVING, me too, this is my first issue that I opened for Angular :) Loving it so far. As for the PR, yeah It can be a bit confusing but just follow the steps one by one. There are many blog posts on how to do it. Just google it.

**Comment by olierxleben** [comment]
should have "has PR" tag! Just wanted to jump in. lol

**Comment by ODAVING** [comment]
@fouaddev That's amazing! I think I managed to do everything they suggested, so I guess we just have to wait until PR is reviewed. I'm loving open source as well as the community!

**Comment by YuliaTsareva** [comment]
@ODAVING I would advise to add footer with "Closes #issue_number" text to commit message next time :) In that case, the issue and your PR will be linked automatically. So it will be easier to track PRs even before the label "has PR" is added.

**Comment by ODAVING** [comment]
@YuliaTsareva Really appreciate the advice Yulia, will keep that in-mind for next time!

**Comment by fouaddev** [comment]
I was wondering how long does it usually take to resolve a doc issue like this one?
