### ISSUE TITLE
Angular Universal throwing JSON.parse errors 100 of times while loading application page

### ISSUE THREAD

**Issue by Krrish92** [angular/angular#32949]
I am getting very frustrating error while loading the application page. It seems angular universal requesting the page with responseType as Json.

"SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.onLoad (/var/www/html/booking/dist/server.js:82827:51)
    at XMLHttpRequest.module.exports.XMLHttpRequestEventTarget.dispatchEvent (/var/www/html/booking/dist/server.js:186743:20)
    at XMLHttpRequest.module.exports.XMLHttpRequest._dispatchProgress (/var/www/html/booking/dist/server.js:187238:12)
    at XMLHttpRequest.module.exports.XMLHttpRequest._onHttpResponseEnd (/var/www/html/booking/dist/server.js:187193:12)
    at IncomingMessage.<anonymous> (/var/www/html/booking/dist/server.js:187152:24)
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/var/www/html/booking/dist/server.js:173524:31)
    at Object.onInvokeTask (/var/www/html/booking/dist/server.js:14274:33)
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/var/www/html/booking/dist/server.js:173523:36)
    at Zone.module.exports.Zone.runTask (/var/www/html/booking/dist/server.js:173291:47)"

Here is my server.ts file 

    import 'zone.js/dist/zone-node';
    import 'reflect-metadata';
    require('source-map-support').install();
    import { enableProdMode } from '@angular/core';
    import { ngExpressEngine } from '@nguniversal/express-engine';
    import { provideModuleMap } from '@nguniversal/module-map-ngfactory-loader';
    import * as proxy from 'http-proxy-middleware';

    import * as express from 'express';
    import * as cors from 'cors';
    import * as compression from 'compression';
    import * as cookieparser from 'cookie-parser';

    const domino = require('domino');
    const redirection = require('./redirection');
    const url = require('url');

    const win = domino.createWindow('<body></body>');
    const baseUrl = "/";

    /* varibale for caching */
    let key;

    global['window'] = win;
    global['document'] = win.document;
    global['css'] = null;
    global['Event'] = null;
    global['Prism'] = null;

    enableProdMode();

    export const app = express();

    const NodeCache = require('node-cache');
    const myCache = new NodeCache();

    app.use(compression());
    app.use(cookieparser());
    const corsOptions = {
      origin: true,
      methods: 'GET,HEAD,PUT,PATCH,POST,DELETE',
      credentials: true,
      exposedHeaders: ['x-auth-token'],
      maxAge: 86400,
      preflightContinue: true,
    };
    app.use(cors(corsOptions));

    app.use(function (req, res, next) {
      const path = url.parse(req.url).pathname;
      if (path.indexOf('blog/') != -1) {
        let url = `https://booking.londonserenity.com/web/blog`;
        res.status(301).redirect(url);
        return;
      }

      //  console.log('path ======>', path);
      const isRedirect = redirection(path);
      if (isRedirect.status) {
        if (isRedirect.base_url == false) {
          res.status(301).redirect(isRedirect.dest);
          return;
        }

        res.redirect(baseUrl + isRedirect.dest);
        return;
      } else
        next();
    });

    app.use('/ws/', proxy({ target: 'https://booking.londonserenity.com', changeOrigin: true }));

    app.use((req, res, next) => {
      key = '__express__' + req.originalUrl || req.url;
      const cachedBody = myCache.get(key);
      if (cachedBody) {
        console.log('<==== Returning From Server Cache ====>')
        res.send(cachedBody);
        return;
      } else
        next();
    });

    const { AppServerModuleNgFactory, LAZY_MODULE_MAP } = require('./dist/server/main');

    app.engine('html', ngExpressEngine({
      bootstrap: AppServerModuleNgFactory,
      providers: [
        provideModuleMap(LAZY_MODULE_MAP)
      ]
    }));

    app.set('view engine', 'html');
    app.set('views', './dist/browser');
    app.set('trust proxy', true);

    app.use(function (req, res, next) {
      res.setHeader('Cache-Control', 'public, max-age=86400000'); // cache header
      next();
    });

    app.get('/redirect/**', (req, res) => {
      const location = req.url.substring(10);
      res.redirect(301, location);
      return;
    });

    app.get('*.*', express.static('./dist/browser', {
      maxAge: '1y'
    }));

    app.get('/assets/i18n/en.json', (req, res) => {
      res.download(`/assets/i18n/en.json`)
    });

    app.get('*', (req, res) => {
      global['navigator'] = req['headers']['user-agent'];
      res.render('index', {
        req,
        res,
        providers: [{
          provide: 'serverUrl',
          useValue: `${req.protocol}://${req.get('host')}`
        }]
      }, (err, html) => {
        if (html) {
          myCache.set(key, html, 2592000); // time duration in secs
          res.send(html);
        } else {
          console.log('server error :', err);
          res.send(err);
        }
      });
    });

`

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
