### ISSUE TITLE
select set value with ngModel isn't working with IE

### ISSUE THREAD

**Issue by robertIsaac** [angular/angular#32951]
# 🐞 bug report

### Affected Package
@angular/forms

### Is this a regression?
no

### Description
having simple `<select>` element and set it's value with `[(ngModel)]` doesn't affect the visible option in IE 11 only
in my example the page render with no default value (1)
and after 3 seconds it sets the value to 4 and that will remove the selected option (if you did before the 3 seconds)

in IE
![image](https://user-images.githubusercontent.com/14242054/66032683-1c5e0900-e506-11e9-914e-dbb0c58803f7.png)
in chrome
![image](https://user-images.githubusercontent.com/14242054/66032725-31d33300-e506-11e9-9445-9fd6cb20d84c.png)

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-v8jbds

## 🔥 Exception or Error
none

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.3.6
Node: 12.4.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.6
@angular-devkit/core         8.3.6
@angular-devkit/schematics   8.3.6
@schematics/angular          8.3.6
@schematics/update           0.803.6
rxjs                         6.4.0
</code></pre>

**Anything else relevant?**
only happen with IE 11, my IE version is

![image](https://user-images.githubusercontent.com/14242054/66032602-f6d0ff80-e505-11e9-80ad-a255e74cb6b6.png)

i have made a work around using `nativeElement.options[0].selected = true;` to make it work with IE

**Comment by trotyl** [comment]
The issue is because all the `<option>` elements are missing `value` input, it will work correctly once changed to:

```html
<option [value]="1">1</option>
```

BTW, the root issue is that Angular doesn't support content as value in `<option>` element, which is tracked by https://github.com/angular/angular/issues/8549.

**Comment by robertIsaac** [comment]
Issue fixed by adding value to the option
