### ISSUE TITLE
Resolver isn't called when navigating from tab A to tab B and rapidly back to tab A

### ISSUE THREAD

**Issue by DzmVasileusky** [angular/angular#32964]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Description

 
There is a page A with a resolver.
There is a page B with another resolver.
Navigate from page A to page B and then back to A while B's resolver is still loading data and url wasn't changed.

Rapid navigation back in that case not calling A's resolver.
Sequence of router events:
NavigationStart (B)
RoutesRecognized (B)
GuardsCheckStart (B)
ChildActivationStart (B)
ActivationStart (B)
GuardsCheckEnd (B)
ResolveStart (B)
NavigationCancel (B)
NavigationStart (A)
RoutesRecognized (A)
GuardsCheckStart (A)
GuardsCheckEnd (A)
??? Resolve is missing ???
ActivationEnd (A)
ChildActivationEnd (A)
ActivationEnd (A)
ChildActivationEnd (A)

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-djwtf8

## 🌍  Your Environment

**Angular Version:**
<pre>Angular CLI: 7.3.6
Node: 8.11.4
OS: darwin x64
Angular: 8.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.4
@angular-devkit/build-angular     0.803.4
@angular-devkit/build-optimizer   0.803.4
@angular-devkit/build-webpack     0.803.4
@angular-devkit/core              8.3.4
@angular-devkit/schematics        8.3.4
@angular/cdk                      8.2.0
@angular/cli                      8.3.4
@angular/material                 8.2.0
@ngtools/webpack                  8.3.4
@schematics/angular               8.3.4
@schematics/update                0.803.4
rxjs                              6.5.3
typescript                        3.4.5
webpack                           4.39.2<code>

</code></pre>

**Comment by Totati** [comment]
I think this is how it should work. You're on route A, navigating to route B starts the resolving. During the resolve navigating back to route A cancels the resolve and nothing happens. Angular won't reload the component that's already loaded. 
Your issue seems to be related to [THIS ](https://github.com/angular/angular/issues/21115) one. 
[Here](https://angular.io/api/router/ExtraOptions#onSameUrlNavigation)'s a config that might fix your problem too.

**Comment by DzmVasileusky** [comment]
@Totati I see. So that's an expected behavior. We recently had to move some code from resolvers to page containers because of that
