### ISSUE TITLE
Typo opting out differential loading

### ISSUE THREAD

**Issue by borriej** [angular/angular#32978]
# 📚 Docs or angular.io bug report

### Description

The docs say:
_To explicitly disable differential loading:

Enable the dead or IE browsers in the browserslist config file by removing the not keyword in front of them.
Set the target in the compilerOptions to es5._

https://angular.io/guide/deployment#opting-out-of-differential-loading

This confuses me a lot, and I think its a typo. Because it says: "If you only want a ES6 build, you should set the tsconfig compilerOptions target to ES5. This is weird.

## Reproduction Steps**
angular core ```8.2.5```
angular cli ```8.3.3```

My browserlist looks like
```
last 2 Chrome versions
last 2 Safari versions
last 2 Firefox versions
```
my tsconfig looks like
```
{
    "compileOnSave": false,
    "compilerOptions": {
        "baseUrl": "./",
    "downlevelIteration": true,
    "importHelpers": true,
        "outDir": "./dist/out-tsc",
        "sourceMap": true,
        "declaration": false,
        "module": "esnext",
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "allowJs": true,
        "target": "es2015",
        "typeRoots": [
            "node_modules/@types",
            "node_modules/@types/stripe-v3",
            "node_modules/@types/jspdf"
        ],
        "lib": [
            "es2017",
            "dom"
        ],
        "paths": {
            "@app/*": ["./src/app/*"],
            "@env/*": ["./src/environments/*"],
            "@routes/*": ["./routes/*"]
        }
    },
    "include": [
        "src/**/*",
        "node_modules/ts-money/**/*"
    ]
}
```

But the build is creating ES6 + ES5 bundles :/ I expect only ES6 bundle.
```
Generating ES5 bundles for differential loading...
ES5 bundle generation complete.
```

(I am using SSR Angular Universal, maybe this changes things, but dont think so)

So maybe:
* the docs are wrong (its seems weird to set ES5 if you want ES6) 
* I am doing it correctly, but there is a bug in opting-out of differential loading
* I am doing it wrong ?

**Comment by trotyl** [comment]
The doc is correct, "disable differential loading" means **only produce ES5 bundle**.

**Comment by ajitsinghkaler** [comment]
@gkalpak I think we can close this issue

**Comment by kapunahelewong** [comment]
Thanks, @ajitsinghkaler!
