### ISSUE TITLE
lifecycle events are only available through 'LivecycleEvent' enum since Alpha 32: mention it in CHANGELOG.md ?

### ISSUE THREAD

**Issue by jomeier** [angular/angular#3298]
Hi,

since all lifecycle events are only available with the ```LifecycleEvent``` enum since Alpha 32 it should be mentioned in the CHANGELOG.md document?

Regards,

Josef

**Comment by mhevery** [comment]
We are still improving our process. Not sure we want to go back and rewrite the change log, but we will get better at it over time. We are still in Alpha.

**Comment by jomeier** [comment]
@mhevery Thanks!
