### ISSUE TITLE
Produce warnings/errors for code that change detection can't handle

### ISSUE THREAD

**Issue by sod** [angular/angular#32995]
Examples:

### Creates new observable on every change detection cycle
```html
<div *ngIf="getX() | async as x">{{ x }}</div>
```
> Maybe: Warning - Observables should not change on every change detection cycle. Create a single observable upfront instead

### Doesn't use trackBy
```html
<div *ngIf="let x of y">
    [[ ... dozens of lines of dom & components ... ]]
</div>
```
> Maybe: Warning - Angular doesn't reuse the DOM tree inside ngFor right now. Consider adding trackBy for performance

~~### Create new reference on every single change detection:~~
```html
<div *ngFor="let x of y.slice(0, 3)">
    {{ x }}
</div>
```
~~> Maybe: Warning - The array reference should not change on every change detection cycle / or use pipe slice instead~~
Update: This case is handled by angular, my assumption was wrong

---

These are footguns that rise from how angular works. For me these errors are super clear.  But anybody that is not familiar with angular or doesn't work every day with it writes code like this all the time. And it's super hard to keep up with it in code reviews to not let those things slip into master.

A little help from the framework to prevent these issues would be appreciated.

**Comment by Toxicable** [comment]
There are situations where some of those examples you gave are totally fine.
It's hard to generalise things like this, I'd say it should be more of a linting warning/error rather than a core framework one.

**Comment by Airblader** [comment]
In fact the trackBy one is AFAIK intentional to make it easier on beginners. In React providing a "key" is required, in Angular it's optional. And for small lists that's totally fine. 

It's probably also difficult to know whether an expression returns a new reference on every call or not. How do you determine that apart from hardcoding knowledge on built-in functions such as slice?

**Comment by Airblader** [comment]
One more point, but drowning existing apps in dozens or hundreds of warnings probably wouldn't help anyone either, so I agree that this should be a linting effort. All of these work by design, it'd be odd for the core to issue warnings for intended usage. If we wanted to prevent this with certainty, Angular shouldn't allow calling functions from the template etc.

**Comment by sod** [comment]
Doesn't has to be a default. More like a `strict` flag like typescript has.

I personally have no issues with any of those examples. But I breathe angular since beta & angularjs for forever. And understood the why and how the change detection works.

But people coming from other frameworks (e.g. react, where state changes are explicit, or vue.js where state is easiliy memoized via computed getters) or someone picking angular as their first framework, it just seems to be sooooo hard to not fall in those traps.

**Comment by trotyl** [comment]
All of `NgIf`, `NgForOf` and `AsyncPipe` are  just built-in libraries, totally user code, not recognized by either compiler or runtime.

**Comment by sod** [comment]
One of my arguments why angular is so incredibly good is, that templates are strongly typed (and it becomes even better with ivy). Saying that directives and pipe are just gonna be ignored in that equation - even the shipped-with-angular ones - is sad to hear.

**Comment by Airblader** [comment]
I don't see what type checking has to do with the fact that these directives are not hard-coded into the core but rather just use framework features to be implemented outside the core.

**Comment by sod** [comment]
AngularJS just called change detection as long as nothing changed anymore. And it gave up after 10 tries and threw an error. This prevented the first of my 2 examples. And AngularJS had a default trackBy strategy, that prevented the third example.

So angularjs already had tools to prevent those issues. Why shouldn't it be possible in angular? Is doesn't *has* to be at compile time.

**Comment by trotyl** [comment]
> AngularJS just called change detection as long until nothing changes anymore. And it gave up after 10 tries and threw an error. This prevented the first of my 2 examples. And AngularJS had a default trackBy strategy, that prevented the third example.

@sod Could you please try it yourself? None of these would happen in AngularJS:

https://stackblitz.com/edit/angularjs-gtx4nx?file=home%2Fhome.controller.js

**Comment by sod** [comment]
Ya, it doesn't work on primitives. And it supposed to play into angular/animate, so if a value changes, the node changes.

But if the objects are the same, but the outer array changes, it reuses the dom, even though the array is new: https://stackblitz.com/edit/angularjs-mbzwk4?file=home/home.controller.js

But to be clear, I like that angular got rid of that default trackBy. But a nod to the developer, that if the loop is pretty heavy on the DOM, adding a trackBy would be a huge bonus.

E.g. in the talk of the team at angular connect (https://www.youtube.com/watch?v=G5rBTvLugVs) for the question "is micro optimization useful for app developers", the answer "add trackBy to your ngFors" would have been the easiest tip for performance in angular :D

**Comment by trotyl** [comment]
> Ya, it doesn't work on primitives. And it supposed to play into angular/animate, so if a value changes, the node changes.
> 
> But if the objects are the same and the outer array changes, it reuses the dom, even though the array is new: https://stackblitz.com/edit/angularjs-mbzwk4?file=home/home.controller.js

That's exactly same in Angular and AngularJS.

https://stackblitz.com/edit/angular-pbvudd

> But to be clear, I like that angular got rid of that default trackBy.

"Tracking by identity" is known as "no trackBy", which is the default trackBy in both Angular and AngularJS, if you want to call it a trackBy mechanism.

**Comment by sod** [comment]
Yes you are right. Seems like I never saw that because we try not to mutate state, so a property change mostly recreates the object. Or data comes via AJAX and that data are new references as well every time.

**Comment by sod** [comment]
Strange that there is a slice pipe when `let value of values?.slice(0, 3)` does exactly the same as `let value of values | slice:0:3` :D
