### ISSUE TITLE
Named outlets are not displaying the route content

### ISSUE THREAD

**Issue by robbiemu** [angular/angular#33002]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

import { RouterModule } from '@angular/router';

### Is this a regression?

not sure

### Description

 A clear and concise description of the problem...

named outlets are not displaying the routed content, with no error, and a router.config that appears appropriate (this has been reviewed by almost 4 dozen people now, and we're not saying _ti is wrong_ but it seems wrong)

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-bxcmgg (under routed component you should see "default works!")

## 🔥 Exception or Error
no error occurs. Route navigation does occur:

```
Router Event: NavigationEnd
platform-browser.js:211 NavigationEnd(id: 2, url: '/main(routed:default)', urlAfterRedirects: '/main(routed:default)')
platform-browser.js:211 NavigationEnd {id: 2, url: "/main(routed:default)", urlAfterRedirects: "/main(routed:default)"}
```

and the router config appears right:
```
router.config
(8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
0: {path: "", pathMatch: "full", redirectTo: "/main"}
1: {path: "main", pathMatch: "prefix", component: ƒ}
2: {path: "404", component: ƒ}
3: {path: "**", redirectTo: "/404"}
4: {path: "", pathMatch: "prefix", component: ƒ}
5: {path: "", pathMatch: "full", redirectTo: "/default"}
6: {path: "default", outlet: "routed", component: ƒ}
7: {path: "second", outlet: "routed", component: ƒ}
```

## 🌍  Your Environment

**Angular Version:**
this is appearing in angular 5 and angular 7 (see stackblitz package.json says 
<pre><code>
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular/cli": "~7.0.2",
    "@angular/compiler-cli": "~7.0.0",
    "@angular/language-service": "~7.0.0",
</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
Hi @robbiemu, the problem doesn't appear to be an issue with named router (try removing the code that has to do with handling named routes and you'll get the same behavior). It looks like part of this is trying to handle some matched route with children but there aren't any. The first matched route '/main' ends the navigation and the other router outlets do nothing. Also, you have multiple `RouterModule.forRoot` which can lead to unexpected behavior. Lastly, for reference, `redirectTo` named outlets appears to have been fixed a while ago: #12740

All in all, this doesn't seem to fall into a bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
