### ISSUE TITLE
<content></content> no longer working with Alpha 32

### ISSUE THREAD

**Issue by woppa684** [angular/angular#3301]
consider this example:

```typescript
import {Component, View, bootstrap} from "angular2/angular2";

@Component({
    selector: "app"
})
@View({
    template: `<div><content></content</div>`,
})
class App {
}

bootstrap(App);
```
with the html:

```html
<app>My content</app>
```

Then I would expect "My content" to appear on the page but in fact only the actual content tags are there... This used to work up until Alpha 31 but I can't find anything related in the changelog...

**Comment by msterba** [comment]
Looking at the zippy component example, it's ng-content.
https://github.com/angular/angular/blob/master/modules/examples/src/zippy_component/zippy.html#L6

**Comment by jessegood** [comment]
See https://github.com/angular/angular/issues/2529.
Shadow DOM emulation no longer supports `<content>` and uses `<ng-content>` instead I believe because it differs from native shadow DOM.

**Comment by woppa684** [comment]
Aha, but I would have expected at least something in the changelog then...

**Comment by tbosch** [comment]
Changelog has been updated...
