### ISSUE TITLE
Getting Started Tutorial: Unable to create product alert component using Angular Generator

### ISSUE THREAD

**Issue by chjoslyn** [angular/angular#33014]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

When I right click on the "app folder" and then select "component" in the "Angular Generator", a field appears to name the new component but when I press enter to create the component nothing happens. The field just stays there and a new "product-alert" folder does not appear in the sidebar nor do the component.ts .html or .css files. 

### What's the affected URL?**
 https://angular.io/...

## 📷Screenshot

![image](https://user-images.githubusercontent.com/56140974/66249055-5b00e880-e6eb-11e9-8f97-f5f18cd67384.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Browser info

I've tried creating the component using Firefox and Chrome but it doesn't work for either of them.

**Comment by lazarljubenovic** [comment]
This is a StackBlitz issue, not Angular. https://github.com/stackblitz/core

**Comment by chjoslyn** [comment]
Thank you!

Sent from Mail for Windows 10

**Comment by kapunahelewong** [comment]
Closing this since it's StackBlitz specific. @chjoslyn if you still have questions, please feel free to re-open and ping me. Thanks!
