### ISSUE TITLE
Add `Location.urlChanges` as Observable<{url, state}>

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#33021]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/common

### Description

Currently, `Location` class exposes `onUrlChange` event listener. To get URL changes as `Observable`, we have to create own wrapper service. And this is a common use case; to reflect URL to title, meta data, or etc...

`Router.events` is like this but URL change event doesn't depend on Router. It should just wrap platform's location change.

### Describe the solution you'd like

Add `Location.urlChanges` field.

```ts
class Location {
  readonly urlChanges: Observable<{url: string; state: unknown}>;
}
```

### Describe alternatives you've considered

Current workaround

```ts
const urlChanges$ = new Subject();
location.onUrlChange((url) => {
  urlChanges$.next(url);
});
```

**Comment by Airblader** [comment]
The workaround can be written in a more compact way as*

```
const urlChanges$ = bindCallback(location.onUrlChange)();
```

Overall I think Angular shouldn't expose the same thing in many different ways as that muddies the API surface, so either it should stay with the current form (that workaround isn't really problematic in any way) or it should be a breaking change (IMHO).

<sub>*) Untested, perhaps it has to be wrapped in an anonymous function to ignore the first argument, but I believe rxjs recognizes this correctly.</sub>
