### ISSUE TITLE
Feature (DI): Better developer story for large applications

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#3303]
The current DI system, when compared to something like [Guice](https://github.com/google/guice), has some limitations that large internal clients are finding lacking. Below, when I use the term `module`, I mean, for Dart at least, a `const` `List` of `<Binding | Type | List<...>>`

Requests from internal clients:
- [ ] If two or more modules would resolve bindings differently, have an option to warn or throw.

This would be used to help detect when you may not intend for a binding to be overriden.
```dart
const serviceBindings = const [ const Binding(MapsService, toClass: DefaultMapsService) ];
const debugBindings = const [ const Binding(MapsService, toClass: DebugMapsService) ];

// We will (accidentally?) override DefaultMapsService with DebugMapsService.
// In some mode (debug?) we may want to print to console or throw something.
void main() {
  bootstrap(..., [serviceBindings, debugBindings])
}
```
- [ ] Have a required binding "marker" to remind developers to fill-in implementations or flags.
```dart
const mapsServicePrefixToken = const OpaqueToken('mapsServicePrefix');

const serviceBindings = const [
  const Binding(MapsService, toClass: DefaultMapsService),
  const RequireBinding(mapsServicePrefixToken, reason: 'Define an API prefix to use MapsService')
];
```

- [ ] Allow optional typing of `token`-type bindings to throw earlier
```dart
const mapsServicePrefixToken = const OpaqueToken<String>('mapsServicePrefix');

const serviceBindings = const [
  const Binding(mapsServicePrefixToken, 5); // Should throw fast in dev-mode
];
```

- [x] ~~Reduce the cost of duplicate/re-binding by resolving bindings, when possible, at build time~~

*This is already done.*
```dart
const serviceBindings = const [
  const Binding(MapsService, toClass: DefaultMapsService)
];

const mapsRenderingBindings = const [
  serviceBindings,
  otherBindings
];

// We are binding two identical `const Binding(MapsService)` at runtime, even though they will resolve
// exactly the same. We could detect this at build time.
void main() {
  bootstrap(..., [serviceBindings, mapsRenderingBindings])
}
```

Other related issues (will add to if I create sub-issues):
- #3251 (Makes the current system easier to digest)

Requires some input by @TedSander, @yjbanov if possible before pushing to Misko and Victor :)

**Comment by naomiblack** [comment]
Out of scope for Angular 2 release.
