### ISSUE TITLE
Angular Responsive Navbar

### ISSUE THREAD

**Issue by TunMyintThein1995** [angular/angular#33032]
/*** HTML ***/
<mat-sidenav-container class="sidenav-container">
    <mat-sidenav #drawer class="sidenav"
    [ngClass]="{hidden: !(isHandset | async)!.matches}"
    fixedInViewport="true"
    [attr.role]="isHandset ? 'dialog' : 'navigation'"
    [mode]="(isHandset | async)!.matches ? 'over' : 'side'"
    [opened]="!(isHandset | async)!.matches">
      <mat-toolbar color="primary">
        <button type="button" aria-label="Toggle sidenav" mat-icon-button (click)="drawer.toggle()" *ngIf="(isHandset | async)!.matches">
          <mat-icon class="mat-18" aria-label="Side nav toggle icon">close</mat-icon>
        </button>
      </mat-toolbar>
      <mat-nav-list>
        <a mat-list-item href="#"></a>
        <a mat-list-item href="#"></a>
        <a mat-list-item href="#"></a>
      </mat-nav-list>
    </mat-sidenav>
    <mat-sidenav-content>
      <mat-toolbar color="primary">
        <button type="button" aria-label="Toggle sidenav" mat-icon-button (click)="drawer.toggle()" *ngIf="(isHandset | async)!.matches">
          <mat-icon class="mat-18" aria-label="Side nav toggle icon">menu</mat-icon>
          
        </button>
      </mat-toolbar>
      <app-home></app-home>
    </mat-sidenav-content>
    

</mat-sidenav-container>

/**** Ts File ****/
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { BreakpointObserver, BreakpointState, Breakpoints } from '@angular/cdk/layout';

export class PagesComponent implements OnInit {
  isHandset: Observable<BreakpointState> = this.breakpointObserver.observe([
    // Breakpoints.Handset,
    // Breakpoints.Tablet,
    '(max-width: 980px)'
    ]);
  constructor(private breakpointObserver: BreakpointObserver) { }

}

**Comment by santoshyadav198613** [comment]
Hi looks like you are getting some problem with the code, raise it on Stackoverflow. We don't take support issues here.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem)
