### ISSUE TITLE
BUG: IVY ViewContainerRef does not remove item with animation (Route)

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#33030]
# 🐞 bug report

### Affected Package
`@angular/core`
`@angular/common`
`@angular/animations`
`@angular/router`

Probably one of these

### Is this a regression?
I am not sure, but i think it was working without IVY, so it is possible that it is regression.

### Description

When you have route with animation (little complex animation) on component which is routet, after changing route, new component appear next to old component which is not removed and this will stack.

## 🔬 Minimal Reproduction

> `clone https://github.com/kukjevov/ng-universal-demo.git`
> `cd ng-universal-demo`
> `git checkout ivy-error`
> `npm install`
> `npm start`
> open browser at `http://localhost:8888`
> click on garden link
> click on *Garden* link
> click on *Home* link
> click on *Garden* link
> click on *Home* link
> click on *Garden* link
> click on *Home* link

then you will see that `home-view` will be there multiple times (it is not removed after changing route)

## 🔥 Exception or Error

No exception just not removed component from view.

## 🌍  Your Environment

**Angular Version:**

**Versions:**
angular: 9.0.0-next.9
nodejs: 10.16.0
npm: 6.9.0
windows: 10.0.17763 Build 17763

**Comment by AndrewKushnir** [comment]
Potentially related issue - #34139.

**Comment by jornare** [comment]
We're experiencing the same issue without IVY (have not tested IVY) but with firefox (win & macos). Safari & Chrome works fine.

**Comment by jornare** [comment]
Seems similar to #20489 and #16330

**Comment by kukjevov** [comment]
Well I am not sure, because this is browser independent problem.

**Comment by jornare** [comment]
> Well I am not sure, because this is browser independent problem.

That was not clear from your report, and its helpful that you clarify. Which browser did you test?

**Comment by AndrewKushnir** [comment]
Hi @kukjevov, thanks for reporting the issue and providing a repro.

I've tested an app with the `9.0.0-next.12` version and was able to reproduce the issue, but after upgrading to the most recent RC.7 version (i.e. `9.0.0-rc.7`) the app works as expected and there are no unnecessary views accumulated on a page - old views are properly removed.

Could you please try to update Angular packages in `package.json` to `9.0.0-rc.7`, test an app once again and let us know if the problem still exists?

Thank you.

**Comment by kukjevov** [comment]
Hi @AndrewKushnir thanks for info, i will look into it :).

**Comment by kukjevov** [comment]
I have tested it with rc.8 and it looks fine with this version :).

Thx
