### ISSUE TITLE
Factory providers return undefined in AOT mode

### ISSUE THREAD

**Issue by makkgregory** [angular/angular#33036]
# 🐞 bug report

### Affected Package

Probably `@angular/compiler`

### Description

`useFactory` function is not called and `undefined` value injected instead when compiled in AOT mode.

## 🔬 Minimal Reproduction
<pre><code>
git clone https://github.com/makkgregory/factory-provider-issue.git
cd factory-provider-issue
npm install
npm run ng -- serve --aot
</code></pre>

Open `localhost:4200`,  then go to console: both injected values are undefined.
See `app.module.ts` for details.

## 🔥 Exception or Error
No errors during compilation and runtime

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.8
Node: 11.12.0
OS: win32 x64
Angular: 8.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.8
@angular-devkit/build-angular     0.803.8
@angular-devkit/build-optimizer   0.803.8
@angular-devkit/build-webpack     0.803.8
@angular-devkit/core              8.3.8
@angular-devkit/schematics        8.3.8
@angular/cli                      8.3.8
@ngtools/webpack                  8.3.8
@schematics/angular               8.3.8
@schematics/update                0.803.8
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Comment by JoostK** [comment]
This works fine in Ivy and an easy workaround is available for ViewEngine:

Change
```ts
    { provide: PROVIDED_OBJECT, useFactory() { return new ProvidedObject(); } },
    { provide: ProvidedObject, useFactory() { return new ProvidedObject(); }}
```
into
```ts
    { provide: PROVIDED_OBJECT, useFactory: () => new ProvidedObject() },
    { provide: ProvidedObject, useFactory: () => new ProvidedObject() }
```
this will cause ViewEngine's _lowering_ magic to make it work.
