### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError with Interceptor and component interaction(Angular 8)

### ISSUE THREAD

**Issue by Kappyh** [angular/angular#33037]
### Affected Package
"@angular/core": "8.2.5"
"@angular/common": "8.2.5"

### Description

I'm facing some common issue on Angular template, I have this general template for all my pages and inside of it I have a *ngIf with a spinner inside and another one with my router-outlet.
The interceptor controlls the behavior and visibility of the spinner, so with that comes the error, in a specific component I subscribe on a http method on a ngOnInit and the result of that is the error.
This error just happen if I call some method on lifecycle methods. I already tried some workarounds like envolve the setSpinnerState with setTimeout and tried to use other lifecycle hooks(AfterViewInit, AfterContentInit...).
Also a tried to use changeDetection: ChangeDetectionStrategy.OnPush on my LayoutComponent Notation and this on the component lifecycle: 
`ngOnChanges(){
    this.cdr.detectChanges();
  }`
With the code above the error disappears, but the spinner behavior stop to work.

## 🔬 Minimal Reproduction
[https://stackblitz.com/edit/angular-xyulo9](https://stackblitz.com/edit/angular-xyulo9)

## 🔥 Exception or Error
`ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngIf: true'. Current value: 'ngIf: false'.
    at viewDebugError (core.js:28792)
    at expressionChangedAfterItHasBeenCheckedError (core.js:28769)
    at checkBindingNoChanges (core.js:29757)
    at checkNoChangesNodeInline (core.js:44442)
    at checkNoChangesNode (core.js:44415)
    at debugCheckNoChangesNode (core.js:45376)
    at debugCheckDirectivesFn (core.js:45273)
    at Object.eval [as updateDirectives] (LayoutsComponent.html:10)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:45258)
    at checkNoChangesView (core.js:44248)`

## Your Environment
MacOS 10.14.6
Angular Cli 8.3.5
Typescript 3.4.3

**Anything else relevant?**
Browser: Chrome 77.0.3865.90
Visual Studio Code
My question on Stackoverflow :
[https://stackoverflow.com/questions/58276430/expressionchangedafterithasbeencheckederror-on-angular-8-and-method-called-on-ng](https://stackoverflow.com/questions/58276430/expressionchangedafterithasbeencheckederror-on-angular-8-and-method-called-on-ng)

**Comment by dannyskoog** [comment]
This is not a bug. It’s just Angular’s way of informing you that you one of the values changed between the start and end of a particular change detection run.

I have to look into your blitz in more detail to tell you exactly why

**Comment by Kappyh** [comment]
> This is not a bug. It’s just Angular’s way of informing you that you one of the values changed between the start and end of a particular change detection run.
> 
> I have to look into your blitz in more detail to tell you exactly why

Oh I see, sorry.

**Comment by dannyskoog** [comment]
No problem @Kappyh! One can’t know everything, right? :)

I would recommend posting this on StackOverflow instead since we concluded that this is more of a support issue

**Comment by Kappyh** [comment]
Solved on Stackoverflow.
[https://stackoverflow.com/questions/58276430/expressionchangedafterithasbeencheckederror-on-angular-8-and-method-called-on-ng](https://stackoverflow.com/questions/58276430/expressionchangedafterithasbeencheckederror-on-angular-8-and-method-called-on-ng)
