### ISSUE TITLE
HttpHeaders set/append not working.

### ISSUE THREAD

**Issue by ming-hermawan** [angular/angular#33033]
Refer to 'https://angular.io/api/common/http/HttpHeaders', I try to set/append header for my post html.

My code is like:
const header = new HttpHeaders();
header.set(...); // still no headers in header.
header.append(...); // still no headers in header.

I check the header variable and still no headers inside.
Please fix it Angular team, because I'm really sure it's bugs.

I create a new issue because this issue 'https://github.com/angular/angular/issues/19044' is already closed without resolution.

**Comment by Airblader** [comment]
You might be sure, but you would be wrong. HttpHeaders is immutable, those methods always return a new copy with the added headers, they don't mutate the instance on which they are called.

**Comment by djleonskennedy** [comment]
@ming-hermawan from angular docs

![image](https://user-images.githubusercontent.com/8366455/66379975-2b89fe80-e9bf-11e9-8706-5776ef7fe1c9.png)

**Comment by JoostK** [comment]
I would vote to actually improve the documentation for this class. Methods like `append` only briefly say it returns a clone in the return type description, whereas the main docblock does not mention anything about this behavior.

**Comment by JoostK** [comment]
@kapunahelewong Do you know of anyone who could be interested in taking on the documentation improvement?

**Comment by kapunahelewong** [comment]
Hey, @jbogarthyde, would you like to take this?

**Comment by ming-hermawan** [comment]
Thanks for the supports everyone.
