### ISSUE TITLE
Add documentation for PR authors on how to use fixup commits

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#33042]
PRs in this repository are merged using a script that supports `fixup` commits. Good usage of `fixup` commits in a PR makes reviewers lives easier by compartimentalizing sets of requested changes in individual commits that will be squashed into a single commit only when the PR is merged.

There should be documentation for contributors on how to avail of this functionality, and how to avoid common pitfalls while using it.

**Comment by dannyskoog** [comment]
Out of curiosity @filipesilva - is it this line that squashes the fixup commits upon PR merge?

https://github.com/angular/angular/blob/master/scripts/github/merge-pr#L198

**Comment by gkalpak** [comment]
Yes :smiley:

**Comment by dannyskoog** [comment]
Good stuff! :) And I agree on that this particular documentation should be added to the contribution guidelines

**Comment by sonukapoor** [comment]
@gkalpak I was trying to find this info in the guidelines, however, it's not there yet. A google search brought me here. Can we get this merged or can I help with any changes to it?

**Comment by gkalpak** [comment]
Thx for stepping up, @sonukapoor! My branch is still a WIP (so not merge-ready), but at this point I think it would be faster for me to finish it (than hand it over to someone else). I'll try to get it finished later this week.
