### ISSUE TITLE
3rdpartylicenses.txt - optional generation, documentation and fitness for purpose

### ISSUE THREAD

**Issue by DanKing123** [angular/angular#33056]
I think this is a combination of a **bug report**, plus a possible **feature request** and **change to the documentation**.

The issue is around `3rdpartylicenses.txt`, how (and whether) it's generated during a build, and whether it's actually fit for purpose.

By default (at least when you do a production build via `ng build --prod`), all license information from third party JS dependencies is stripped out, de-duplicated, and moved to `3rdpartylicenses.txt`. This is all well and good! This file is located in the same directory as `index.html` etc., thus making it available (assuming you deploy the whole directory or its contents) at the root level of your application.

What's not so clear to me though - and this doesn't seem to be covered in the Angular documentation - is whether or not this actually satisfies the license requirements, e.g. "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software" - from the MIT License.

Do I have to publicise the existence of `3rdpartylicenses.txt`, or make it in some way directly accessible to users from my web application, in order to satisify the requirement that it "shall be included in ... the Software"? This seems overly burdensome on me though, so **what other - alternative - options do I have? And can this please be covered in the documentation?**

At the moment, it is possible to prevent the generation of `3rdpartylicenses.txt` by supplying `--extractLicenses=false` to the build command. *However* - and this is where the bug report comes in - this ***doesn't** actually prevent the license details from being stripped out of the minified JS! Instead, it just prevents `3rdpartylicenses.txt` from being created!* (at least, this is the case when I just tested it in Angular 7 anyway...)

**Comment by IgorMinar** [comment]
hi @DanKing123, the `extractLicense` setting does the correct thing - it controls whether the licensing info should be extracted into `3rdpartylicenses.txt` file. This is a convenience feature, more than a legal requirement.

It is customary to preserve licensing information in application bundles in the form of js comments marked with `@license` js doc and that's what Angular CLI does. We currently don't offer a way to omit the inclusion of these headers in the application bundles. You can do so by customizing the build system, but whether or not that is against the licensing requirements should be determined by your legal advisor. We cannot offer legal advice to you in this matter.

The default behavior of the CLI is pragmatic and conservative. Considering the large variety of libraries and licenses with different requirements, as well as developers residing in many different countries with different legal systems, we don't feel comfortable offering legal advice via our documentation. I hope you understand.

**Comment by DanKing123** [comment]
> It is customary to preserve licensing information in application bundles in the form of js comments marked with @license js doc and that's what Angular CLI does. We currently don't offer a way to omit the inclusion of these headers in the application bundles.

@IgorMinar I assume that by "application bundles", you are referring to the combined and minified js files created by the build process, which make up the application ready for deployment.

I've just checked (as I said before, I am using Angular 7), and these don't contain any @license js doc - or in fact any comments or documentation of any kind, just minified JavaScript with all the comments including all license information removed.

Can you please tell me what I'm missing??
