### ISSUE TITLE
IE 11, Multiple definitions, common.js -> vendor.js

### ISSUE THREAD

**Issue by 029shailesh** [angular/angular#33050]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

IE 11
SCRIPT1046: Multiple definitions of a property not allowed in strict mode
vendor.js (1150,192)

located in:
\node_modules\@angular\common\__ivy_ngcc__\fesm2015\common.js
at line 1799
and
\node_modules\@angular\common\__ivy_ngcc__\fesm5\common.js
at line 1020
pathname: []
is reapeated two times

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by santoshyadav198613** [comment]
Hi @029shailesh ,

Can UI describe issue in detail, also include GitHub or stackblitz repo to generate the issue. Also issue one of the issue template.

**Comment by 029shailesh** [comment]
sorry I am new to this angular, by mistake I missed some pre configuration for IE.
Thank you.
