### ISSUE TITLE
Language service does not handle expressions involving generics correctly

### ISSUE THREAD

**Issue by jonrimmer** [angular/angular#33055]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/language-service

### Is this a regression?

No. It was previously raised in #19408 and incorrectly closed.

### Description

Given the following component definition...

```ts
interface IBox<T> {
  value: T;
}

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent<T>  {
  value: T;
  boxedValue: IBox<T>;
}
```

...the values of `value` and `boxedValue.value` are of the same type, but the following template expression produces an error in the editor:

```html
<p *ngIf="value == boxedValue?.value">
  Start editing to see some magic happen :)
</p>
```

## 🔬 Minimal Reproduction

https://ng-run.com/edit/3DoFPnIQDsI5zy4EXwRC

## 🔥 Exception or Error

```
Expected the operants to be of similar type or any
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.2.0
Node: 12.4.0
OS: darwin x64
Angular: 8.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0
@angular-devkit/build-angular     0.802.0
@angular-devkit/build-optimizer   0.802.0
@angular-devkit/build-webpack     0.802.0
@angular-devkit/core              8.2.0
@angular-devkit/schematics        8.2.0
@angular/cdk                      8.1.2
@ngtools/webpack                  8.2.0
@nguniversal/express-engine       8.1.1
@schematics/angular               8.2.0
@schematics/update                0.802.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0

</code></pre>

**Anything else relevant?**

**Comment by snebjorn** [comment]
I've run into this issue as well. Here's a "real world" example showing the issue.

Example:
```html
<nz-table #nzTable [nzData]="listOfData">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let data of nzTable.data">
      <td>
        <!-- data is type any. It should infer the type from listOfData -->
        {{ data.name }}
      </td>
    </tr>
  </tbody>
</nz-table>
```

[The NzTable is implemention](https://github.com/NG-ZORRO/ng-zorro-antd/blob/5be4c59a88d2d3dbd98ece2a11a06d0b91f5fb75/components/table/nz-table.component.ts). This implementation should allow the language service to infer the type T to be the type given via `nzData`

Lets say the type of `listOfData` is `User[]` then ngFor should know that the types are `*ngFor="let data: User of nzTable.data: User[]"` (added the types TS style)

**Comment by atscott** [comment]
I wasn't able to reproduce with the latest version of the Language Service. Please update to the most recent version to resolve the problem.

If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
