### ISSUE TITLE
Incorrect naming in examples of EventEmitter

### ISSUE THREAD

**Issue by gilles-phan** [angular/angular#33057]
Hello,

In the examples (_at the end of the page_), the name of EventEmitter are "_onOpen_" and "_onClose_", but it "**should not be prefixed with on (no-output-on-prefix)**".

=> https://angular.io/api/core/EventEmitter

![image](https://user-images.githubusercontent.com/1096770/66489680-4d16e300-eab0-11e9-8bce-77c9a187cfc3.png)

**Comment by gkalpak** [comment]
This rule refers to output names (which show up as events in the template), not to method names.

In the above example, it is the `open` and `close` outputs/events that should not be prefixed with `on`. So, `(on-open)="..."` or `(on-close)="..."` is to be avoided, but naming a method on the component `onOpen()`/`onClose()` is fine (even if we happen to use such a method as an event handler in the template).

I hope that makes sense. I you have ideas on how to make this more clear in the [style guide][1], please open a new issue (or better yet a pull request :grin:).

[1]: https://angular.io/guide/styleguide#dont-prefix-output-properties

**Comment by gilles-phan** [comment]
Oh damn ! Indeed, sorry ! Thanks for your correction !
I confused the outputs and the name of the method, as you says.. >_<

Le mer. 9 oct. 2019 à 20:06, George Kalpakas <notifications@github.com> a
écrit :
