### ISSUE TITLE
perf(docs-infra): various issues affecting performance of angular.io

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#33063]
This is a list of issues that have been found to affect performance of angular.io and need further investigation. (Capturing what we have found out so far for future reference.)

> NOTE 1: Most of the issues are not angular.io specific and would affect all similar apps.
> NOTE 2: The issues don't seems to be VE or Ivy specific.

Jira issue: [FW-1616][1]

**Context**
While debugging an unrelated bug in #32923 (turning on Ivy for angular.io), I noticed too many change detection runs (~250! in some cases) while navigating to `/guide/router` (a looong guide with lots of custom elements (193, 10 of which are `MatTabGroup`s)).

**Problems**
@pkozlowski-opensource profiled the app ([sample recording][2]) and found out it takes several seconds (~4-8s :scream:) to fully load the `/guide/router` page. The time is mostly spent in JS and forced layouts (:scream: :scream:).

The main problems seem to be the following:

- [ ] _Several forced layouts during JS execution._
    **Source:** `MatTabGroup`/`MatTab` components (`material`), `TocComponent` (`aio/`)
    **Related issues:** angular/components#17317

- [ ] _Several timers (as a result of scheduling macrotasks in some RxJS observable)._
    **Source:** `MatTab` component (`material`)

- [ ] _Several change detection runs triggered in `requestAnimationFrame()` calls._
    **Source:** `@angular/elements` change detection (at least 1 per element _instance_ (often more due to a bug - see related issues)) (`elements`)
    **Related issues:** #33059, #33060

fyi @pkozlowski-opensource 

[1]: https://angular-team.atlassian.net/browse/FW-1616
[2]: https://github.com/angular/components/files/3698146/aio_mat_tab_forced_layout.json.zip

[FW-1616]: https://angular-team.atlassian.net/browse/FW-1616

**Comment by JeanMeche** [comment]
Closing this as we new focus work on the new angular.dev doc site.
