### ISSUE TITLE
How does angular global configure routing not to be added to history？

### ISSUE THREAD

**Issue by yinuocode** [angular/angular#33095]
I know that you can add "replaceurl: true" when you jump, but there are many places where you need to jump. There is no global configuration that prevents the browser from logging history.
thanks!

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
