### ISSUE TITLE
OnPush strategy and Observable Input

### ISSUE THREAD

**Issue by martibenj** [angular/angular#33094]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?
Don't think that is a regression

### Description
I'm trying to pass an observable from a parent component, using OnPush strategy, to a child.
First value of this observable is undefined, then later, on ngOnInit, I create the observable with a dummy value
=> I though that the ngOnChanges of the child component would be triggered because moving from undefined to an observable instance is a reference change, but not.
When removing the change strategy on the parent, the child's ngOnChanges is triggered

Thanks for your help to understand that behavior !

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-xbgnz8
Try to remove the change strategy on parentComponent to see the message change from 'initial value' to 'Got a new Observable for observable$ input !'

## 🔥 Exception or Error
No error seen in console

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular v8.0.0</code></pre>

**Anything else relevant?**
None

**Comment by dannyskoog** [comment]
You need to inject `ChangeDetectorRef` into `parent.component.ts` and perform `this.changeDetectorRef.markForCheck()` on the line after the re-assignment of `observable$`

**Comment by spock123** [comment]
This might be a dumb question but why are you passing an observable as input to the child component?

Why not do` <child-component [prop]="myObservable$ | async"></child-component> `

**Comment by dannyskoog** [comment]
@spock123 he might want to achieve any of the following:
- Control when the observable is subscribed to
- Hook into `error` or `complete` callbacks
- etc.

**Comment by martibenj** [comment]
@spock123 
I agree with you, usually I use the async pipe to pass data to the child component, but in that case I wanted : 
- to call data from XHR on the parent to make only one query,
- pass the cold observable to a child, which add some process to the observable,
- pass it to another sub-child which do something else

@dannyskoog 
Thx but I didn't wanted to do this myself. I though that the onPush stategy would detect the change on the input automatically because the input changed from undefined to an observable instance.

In my comprehension of the OnPush stategy, that was enough to trigger an onChanges. What am I missing..?

**Comment by mlc-mlapis** [comment]
@martibenj Simply `OnPush` checks the passed reference and not what is inside. If the reference is the same, then it means no changes.

**Comment by dannyskoog** [comment]
@martibenj I see. Thanks for elaborating :)

What you're missing is that the assignment of `observable$` is performed **asynchronously** (wrapped by `setTimeout`). And async operations (with a few exceptions) won't **automatically** opt in to the next change detection for `OnPush` components. Hence the need of **manually** opting in by invoking `markForCheck()`

**Comment by martibenj** [comment]
@mlc-mlapis ok, so using ``OnPush`` strategy, it's impossible to use @Input on objects which are initialized to ``undefined`` ? Even for a string ?

**Comment by mlc-mlapis** [comment]
@martibenj All primitive data types, like string, number, ... are not passed as references, so any value change means that `OnPush` detects that.

**Comment by mlc-mlapis** [comment]
@martibenj If you pass the initial value of `@Input` as `undefined` and then something else, like a real object or array, ... then CD should detect it.

**Comment by martibenj** [comment]
Yeah I agree, but that doesn't seems to work on the stackblitz I wrote : https://stackblitz.com/edit/angular-xbgnz8
At construction of the component, ``observable$`` is ``undefined`` then 2 seconds after the call to ngOnInit, ``observable$`` is instantiated with ``of('')``.
So it' ``undefined`` => ``reference`` ?

**Comment by mlc-mlapis** [comment]
@martibenj Hmm, you are right. It looks like the initial can't be falsy value, but what's more interesting, even not the empty string, like `observable$: Observable<string> | string = '';`.

But with any value like `observable$: Observable<string> | {} = {};` it works.

**Comment by mlc-mlapis** [comment]
@martibenj But for me, it works ... as you can see, if you add `console.log` into `ngOnChanges`. The CD runs when `observable$` as `undefined` is switch to a real observable.

**Comment by martibenj** [comment]
@mlc-mlapis yeah I agree with your conclusions.
On your example, it works because the ``changeDetection: ChangeDetectionStrategy.OnPush`` is on the child and not on the parent like on mine. That's the main difference

**Comment by dannyskoog** [comment]
@martibenj did you check my previus reply?

**Comment by martibenj** [comment]
@dannyskoog Sorry, skipped your comment. Thanks for the reminder !

I've updated to test case to replace the setTimeout with an Observable processing with a delay, that is much more what I had in mind.
So what you're telling me is that if I changed any ``@Input`` of the child inside an observable (=async operation) of the parent, the ``@Input`` won't be updated ?

**Comment by mlc-mlapis** [comment]
@martibenj Yep, you have to run the CD by your own code, somewhere in a subscription ... whenever you detect an emit and correctly apply the emitted value, of course.

**Comment by martibenj** [comment]
Ok, that seems to be the problem :
=> Changing the value of a child component ``@Input`` inside of an async operation on the parent using ``OnPush``

**Comment by dannyskoog** [comment]
That’s correct @martibenj

**Comment by dblVs** [comment]
can this be closed since it's not a problem in angular?
also my 2 cents into this -> passing in observables has always been an anti-pattern from my experience building component libraries. my recommendation would be passing the input from outside like others have suggested. so that way you don't have to figure out the change detection manually.
