### ISSUE TITLE
Angular 9.0.0-next.10 fails to build (worked fine in 9.0.0-next.9). Error: Unable to copy assets: EPERM: operation not permitted

### ISSUE THREAD

**Issue by vgb1993** [angular/angular#33105]
# 🐞 bug report

### Affected Package
I don`t know wich package is failing exactly.

### Is this a regression?
It worked in 8.2.2 and 9.0.0-next.9.

### Description
I can not build a brand new app. All I did was ng update. I can still serve it with ng s.
I've been all day trying to fix it with things like: 

- Close VS Code
- Uninstall Node
- Restart Windows
- Remove node_modules and package.lock.json
- Clear node cache
- Run build as Administrator
- Updated Node to 12.

Nothing works...

I can build my app in v8.2.2 and my assets get copied to the correct location.
I update and all schematics run successfully. I can serve my app but I can not build it.
Also, I've tried another project with version 9.0.0-next.9 and it was working until I updated to 9.0.0-next.10 

Can I get some help please? I'm really stucked here.

## 🔬 Minimal Reproduction
- ng new test-10
- add file "assests/imgs/background.jpg"
- ng b ( this works FINE )
- ng update @angular/core --next
- ng update @angular/cli --next
- ng s ( this works FINE )
- ng b  ( this FAILS )

Unable to copy assets: EPERM: operation not permitted, copyfile 'C:\Users\vgall\Documents\Appia\test10\src\assets\imgs' -> 'C:\Users\vgall\Documents\Appia\test10\dist\test10\assets\imgs'

## 🔥 Exception or Error
<pre><code>

C:\Users\vgall\Documents\Appia\test10>ng  b

chunk {main} main-es2015.js, main-es2015.js.map (main) 10.1 kB [initial] [rendered]
chunk {polyfills} polyfills-es2015.js, polyfills-es2015.js.map (polyfills) 251 kB [initial] [rendered]
chunk {runtime} runtime-es2015.js, runtime-es2015.js.map (runtime) 6.09 kB [entry] [rendered]
chunk {styles} styles-es2015.js, styles-es2015.js.map (styles) 16.7 kB [initial] [rendered]
chunk {vendor} vendor-es2015.js, vendor-es2015.js.map (vendor) 3.76 MB [initial] [rendered]
Date: 2019-10-11T16:10:23.473Z - Hash: 6810b492859753732b11 - Time: 7923ms

chunk {main} main-es5.js, main-es5.js.map (main) 10.4 kB [initial] [rendered]
chunk {polyfills} polyfills-es5.js, polyfills-es5.js.map (polyfills) 558 kB [initial] [rendered]
chunk {runtime} runtime-es5.js, runtime-es5.js.map (runtime) 6.09 kB [entry] [rendered]
chunk {styles} styles-es5.js, styles-es5.js.map (styles) 16.7 kB [initial] [rendered]
chunk {vendor} vendor-es5.js, vendor-es5.js.map (vendor) 3.79 MB [initial] [rendered]
Date: 2019-10-11T16:10:29.999Z - Hash: 8c17680eb762d5c3b799 - Time: 6490ms

C:\Users\vgall\Documents\Appia\test10>
C:\Users\vgall\Documents\Appia\test10>
C:\Users\vgall\Documents\Appia\test10>
C:\Users\vgall\Documents\Appia\test10>
C:\Users\vgall\Documents\Appia\test10>ng update --next=true
Using package manager: 'npm'
Collecting installed dependencies...
Found 30 dependencies.
    We analyzed your package.json, there are some packages to update:

      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cli                       8.2.2 -> 9.0.0-next.9    ng update @angular/cli --next
      @angular/core                      8.2.10 -> 9.0.0-next.10  ng update @angular/core --next

C:\Users\vgall\Documents\Appia\test10>ng update @angular/core --next
Using package manager: 'npm'
Collecting installed dependencies...
Found 30 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular/core @ "9.0.0-next.10" (was "8.2.10")...
    Updating package.json with dependency @angular/language-service @ "9.0.0-next.10" (was "8.2.10")...
    Updating package.json with dependency @angular/animations @ "9.0.0-next.10" (was "8.2.10")...
    Updating package.json with dependency @angular/compiler @ "9.0.0-next.10" (was "8.2.10")...
    Updating package.json with dependency rxjs @ "6.5.3" (was "6.4.0")...
    Updating package.json with dependency @angular/common @ "9.0.0-next.10" (was "8.2.10")...
    Updating package.json with dependency @angular/forms @ "9.0.0-next.10" (was "8.2.10")...
    Updating package.json with dependency @angular/platform-browser @ "9.0.0-next.10" (was "8.2.10")...
    Updating package.json with dependency zone.js @ "0.10.2" (was "0.9.1")...
    Updating package.json with dependency @angular/router @ "9.0.0-next.10" (was "8.2.10")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "9.0.0-next.10" (was "8.2.10")...
    Updating package.json with dependency @angular/compiler-cli @ "9.0.0-next.10" (was "8.2.10")...
UPDATE package.json (1360 bytes)
npm WARN rollback Rolling back readable-stream@2.3.6 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\vgall\Documents\Appia\test10\node_modules\webpack-dev-server\node_modules\fsevents\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\karma\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\@angular\compiler-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.0 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 7 packages from 6 contributors, updated 12 packages and audited 17206 packages in 15.758s
found 0 vulnerabilities

    ** Executing migrations for package '@angular/core' **
            ------ Dynamic queries migration ------
            ------ Missing @Injectable migration ------
            Successfully migrated all undecorated providers.
            -------------------------------------------
            ------ Renderer to Renderer2 Migration ------
            As of Angular 9, the Renderer class is no longer available.
            Renderer2 should be used instead.
            ------ Undecorated classes with decorated fields migration ------
            As of Angular 9, it is no longer supported to have Angular field decorators on a class that does not have an Angular decorator.
            ------ Undecorated classes with DI migration ------
            Successfully migrated all found undecorated classes
            that use dependency injection.
            ----------------------------------------------

C:\Users\vgall\Documents\Appia\test10>ng update @angular/cli --next
Using package manager: 'npm'
Collecting installed dependencies...
Found 30 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular/cli @ "9.0.0-next.9" (was "8.2.2")...
    Updating package.json with dependency @angular-devkit/build-angular @ "0.900.0-next.9" (was "0.802.2")...
UPDATE package.json (1374 bytes)

> core-js@3.2.1 postinstall C:\Users\vgall\Documents\Appia\test10\node_modules\core-js
> node scripts/postinstall || echo "ignore"

> @angular/cli@9.0.0-next.9 postinstall C:\Users\vgall\Documents\Appia\test10\node_modules\@angular\cli
> node ./bin/postinstall/script.js

npm WARN sass-loader@8.0.0 requires a peer of node-sass@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.0 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-subresource-integrity@1.3.4 requires a peer of html-webpack-plugin@^2.21.0 || ~3 || >=4.0.0-alpha.2 <5 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\karma\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\@angular\compiler-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.0 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 149 packages from 107 contributors, removed 21 packages, updated 60 packages, moved 1 package and audited 18688 packages in 31.099s
found 0 vulnerabilities

    ** Executing migrations for package '@angular/cli' **
UPDATE angular.json (3653 bytes)
UPDATE package.json (1375 bytes)
npm WARN rollback Rolling back node-pre-gyp@0.12.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\vgall\Documents\Appia\test10\node_modules\webpack-dev-server\node_modules\fsevents\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\karma\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\@angular\compiler-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.0 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 18688 packages in 7.578s
found 0 vulnerabilities

C:\Users\vgall\Documents\Appia\test10>ng s --prod
****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
10% building 3/3 modules 0 activei ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.html

chunk {0} runtime.9a460a9c27201ee28355.js (runtime) 2.83 kB [entry] [rendered]
chunk {1} main.b7efc77d4a570d562200.js (main) 500 kB [initial] [rendered]
chunk {2} polyfills.60c329e22b5a497a5012.js (polyfills) 63.7 kB [initial] [rendered]
chunk {3} styles.0e4338761429b4eb16ac.css (styles) 0 bytes [initial] [rendered]
Date: 2019-10-11T16:48:35.772Z - Hash: 88f72de96f90343b533c - Time: 17235ms

WARNING in C:/Users/vgall/Documents/Appia/test10/src/environments/environment.prod.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Compiled with warnings.
^C¿Desea terminar el trabajo por lotes (S/N)?
^C

C:\Users\vgall\Documents\Appia\test10>ng b
0% compiling
Compiling @angular/core : es2015 as esm2015

Compiling @angular/common : es2015 as esm2015

Compiling @angular/platform-browser : es2015 as esm2015

Compiling @angular/platform-browser-dynamic : es2015 as esm2015

Compiling @angular/router : es2015 as esm2015
Generating ES5 bundles for differential loading...
ES5 bundle generation complete.
Unable to copy assets: EPERM: operation not permitted, copyfile 'C:\Users\vgall\Documents\Appia\test10\src\assets\imgs' -> 'C:\Users\vgall\Documents\Appia\test10\dist\test10\assets\imgs'

C:\Users\vgall\Documents\Appia\test10>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-next.9
Node: 12.11.1
OS: win32 x64
Angular: 9.0.0-next.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.9
@angular-devkit/build-angular     0.900.0-next.9
@angular-devkit/build-optimizer   0.900.0-next.9
@angular-devkit/build-webpack     0.900.0-next.9
@angular-devkit/core              9.0.0-next.9
@angular-devkit/schematics        9.0.0-next.9
@angular/cli                      9.0.0-next.9
@ngtools/webpack                  9.0.0-next.9
@schematics/angular               9.0.0-next.9
@schematics/update                0.900.0-next.9
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.41.0

  "dependencies": {
    "@angular/animations": "~9.0.0-next.10",
    "@angular/common": "~9.0.0-next.10",
    "@angular/compiler": "~9.0.0-next.10",
    "@angular/core": "~9.0.0-next.10",
    "@angular/forms": "~9.0.0-next.10",
    "@angular/platform-browser": "~9.0.0-next.10",
    "@angular/platform-browser-dynamic": "~9.0.0-next.10",
    "@angular/router": "~9.0.0-next.10",
    "rxjs": "~6.5.3",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.0-next.9",
    "@angular/cli": "~9.0.0-next.9",
    "@angular/compiler-cli": "~9.0.0-next.10",
    "@angular/language-service": "~9.0.0-next.10",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
</code></pre>

Folder Permisions ( full premisions )
##C:\Users\vgall\Documents\Appia>icacls test10
test10 NT AUTHORITY\SYSTEM:(I)(OI)(CI)(F)
       BUILTIN\Administradores:(I)(OI)(CI)(F)
       VGB\vgall:(I)(OI)(CI)(F)

node -v
v12.11.1

**Comment by dannyskoog** [comment]
And you’re not running `ng serve` in another command prompt while performing `ng build`?

**Comment by dannyskoog** [comment]
Looks like it was reported here (#15816) as well and will be fixed with #15818

**Comment by vgb1993** [comment]
You are right they appear to be the same, thanks
