### ISSUE TITLE
Angular 9.0.0-next.10 fails to build/serve app with Ivy

### ISSUE THREAD

**Issue by mikolaj-leszczynski** [angular/angular#33100]
### Description
I am trying to follow `angular-bazel-example` from `rules_nodejs` repo. In that repo Angular was updated to the same version I provided below. However, when trying to build and serve my app I'm failing in both cases.

## 🔥 Exception or Error
<pre><code>
▶ yarn build
yarn run v1.17.3
$ ng build

chunk {main} main.js, main.js.map (main) 648 bytes [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 149 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 531 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 175 kB [initial] [rendered]
Date: 2019-10-11T11:52:48.407Z - Hash: adb9878f9a181991f06f - Time: 5758ms

ERROR in Failed to list lazy routes: Unknown module '/home/workspace/my repo/src/app/app.module#AppModule'.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

</code></pre>

<pre><code>
▶ yarn start
yarn run v1.17.3
$ ng serve --port 9089
****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
10% building 4/4 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:9089/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to //index.html

chunk {0} runtime.70a81a280ddba6047a3b.js (runtime) 1.45 kB [entry] [rendered]
chunk {1} main.9b350b7c230fdb52699e.js (main) 146 kB [initial] [rendered]
chunk {2} polyfills.6c0dc9a451f5c5e40cbd.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} polyfills-es5.750ca46f5828ffad1817.js (polyfills-es5) 79.6 kB [initial] [rendered]
chunk {4} styles.9a50d2d49d16335b9b70.css (styles) 61.3 kB [initial] [rendered]
Date: 2019-10-11T11:55:13.780Z - Hash: 12d07be98581bf9d599a - Time: 15195ms

ERROR in app/app.module.ts:79:12 - error TS-991010: Value at position 6 in the NgModule.imports of AppModule is not a reference: [object Object]

</code></pre>

This 6th position is 
<pre><code>
    JwtModule.forRoot({
      jwtOptionsProvider: {
        provide: JWT_OPTIONS,
        useFactory: jwtOptionsFactory,
      },
    }),
</code></pre>
## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.0-next.6
Node: 10.16.0
OS: linux x64
Angular: 9.0.0-next.10
... animations, bazel, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.9
@angular-devkit/build-angular     0.900.0-next.9
@angular-devkit/build-optimizer   0.900.0-next.9
@angular-devkit/build-webpack     0.900.0-next.9
@angular-devkit/core              9.0.0-next.6
@angular-devkit/schematics        9.0.0-next.6
@angular/cdk                      8.2.2
@angular/cli                      9.0.0-next.6
@angular/material                 8.2.2
@angular/upgrade                  8.2.4
@bazel/bazel                      0.29.0
@bazel/bazel-linux_x64            0.29.0
@bazel/benchmark-runner           0.1.0
@bazel/buildifier                 0.28.0
@bazel/buildifier-linux_x64       0.28.0
@bazel/hide-bazel-files           0.36.2
@bazel/ibazel                     v0.10.3
@bazel/karma                      0.38.2
@bazel/rollup                     0.38.2
@bazel/terser                     0.38.2
@bazel/typescript                 0.38.2
@ngtools/webpack                  9.0.0-next.9
@schematics/angular               9.0.0-next.6
@schematics/update                0.900.0-next.6
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.41.0

</code></pre>

**Comment by mikolaj-leszczynski** [comment]
@mhevery I found out this is somehow connected to `"postinstall": "ivy-ngcc"` script I'm having in my `package.json`. When I build/serve my app without running this script the app builds successfully and can be served without errors. Should I have this script in my `package.json` ?

**Comment by gkalpak** [comment]
This sounds like an issue with `ngcc`. @mikolaj-leszczynski, any chance you could share a minimal reproduction?

**Comment by mikolaj-leszczynski** [comment]
Sure, give me a moment : )

**Comment by alan-agius4** [comment]
Hi @mikolaj-leszczynski, under Ivy the deprecated string based lazy loading syntax is not supported. 

This syntax will be updated automatically when the version 9 becomes stable and running `ng update @angular/cli`.

To try it out you can update your `loadChildren` syntax to;

```ts
loadChildren: './app.module#AppModule'
```
to
```ts
loadChildren: import('./app.moduleAppModule'').then(m => m.AppModule) 
```

**Comment by mikolaj-leszczynski** [comment]
@alan-agius4 the thing is I do not have any lazy loaded modules in my app.

@gkalpak, ok. After some digging it turned out that this bug:
<pre><code>
▶ yarn build
yarn run v1.17.3
$ ng build

chunk {main} main.js, main.js.map (main) 648 bytes [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 149 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 531 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 175 kB [initial] [rendered]
Date: 2019-10-11T11:52:48.407Z - Hash: adb9878f9a181991f06f - Time: 5758ms

ERROR in Failed to list lazy routes: Unknown module '/home/workspace/my repo/src/app/app.module#AppModule'.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


</code></pre>
came from missing `aot: true` in `angular.json` in `proejcts.<my-app-name>.architect.build.options`... 
So this one can be crossed out.

However, even when adding `aot: true` I am experiencing the second bug I mentioned:
<pre><code>
▶ yarn start
yarn run v1.17.3
$ ng serve --port 9089
****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
10% building 4/4 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:9089/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to //index.html

chunk {0} runtime.70a81a280ddba6047a3b.js (runtime) 1.45 kB [entry] [rendered]
chunk {1} main.9b350b7c230fdb52699e.js (main) 146 kB [initial] [rendered]
chunk {2} polyfills.6c0dc9a451f5c5e40cbd.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} polyfills-es5.750ca46f5828ffad1817.js (polyfills-es5) 79.6 kB [initial] [rendered]
chunk {4} styles.9a50d2d49d16335b9b70.css (styles) 61.3 kB [initial] [rendered]
Date: 2019-10-11T11:55:13.780Z - Hash: 12d07be98581bf9d599a - Time: 15195ms

ERROR in app/app.module.ts:79:12 - error TS-991010: Value at position 6 in the NgModule.imports of AppModule is not a reference: [object Object]

</code></pre>

This 6th position is 
<pre><code>
    JwtModule.forRoot({
      jwtOptionsProvider: {
        provide: JWT_OPTIONS,
        useFactory: jwtOptionsFactory,
      },
    }),
</code></pre>

The repro is super simple:
1. ng new shiny-ivy-app --enable-ivy
2. Add `@auth0/angular-jwt`
3. Modify your `app.module` so it looks like:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { JWT_OPTIONS, JwtModule } from '@auth0/angular-jwt';

import { AppComponent } from './app.component';

export function jwtOptionsFactory() {
  return {
    tokenGetter: () => 'something0',
    whitelistedDomains: ['something1'],
    blacklistedRoutes: ['something2 ],
  };
}

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    JwtModule.forRoot({
      jwtOptionsProvider: {
        provide: JWT_OPTIONS,
        useFactory: jwtOptionsFactory,
      },
    }),
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```
2. Add `postinstall` script to `package.json` and update Angular version to the newest one:
```
{
  "name": "shiny-ivy-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "ivy-ngcc"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "9.0.0-next.10",
    "@angular/common": "9.0.0-next.10",
    "@angular/compiler": "9.0.0-next.10",
    "@angular/core": "9.0.0-next.10",
    "@angular/forms": "9.0.0-next.10",
    "@angular/platform-browser": "9.0.0-next.10",
    "@angular/platform-browser-dynamic": "9.0.0-next.10",
    "@angular/router": "9.0.0-next.10",
    "rxjs": "6.5.3",
    "tslib": "^1.9.0",
    "zone.js": "0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.900.0-next.9",
    "@angular/cli": "9.0.0-next.9",
    "@angular/compiler-cli": "9.0.0-next.10",
    "@angular/language-service": "9.0.0-next.10",
    "@auth0/angular-jwt": "^3.0.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }
}
```

The error I'm getting:
```
examples/angular-with-ivy/shiny-ivy-app  master ✗                                                                                                  1h28m ⚑ ◒  
▶ yarn build
yarn run v1.17.3
$ ng build

ERROR in src/app/app.module.ts:19:12 - error TS-991010: Value at position 1 in the NgModule.imports of AppModule is not a reference: [object Object]

 19   imports: [
               ~
 20     BrowserModule,
    ~~~~~~~~~~~~~~~~~~
... 
 26     }),
    ~~~~~~~
 27   ],
    ~~~

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This can be fixed by:
* deleting  reference to `JwtModule` <-- so it is probably the broken package
* deleting `postinstall` script with `ivy-ngcc` command

What is strange, this is the output after running `ng build`:
```
Compiling @angular/core : es2015 as esm2015

Compiling @angular/common : es2015 as esm2015

Compiling @angular/platform-browser : es2015 as esm2015

Compiling @angular/platform-browser-dynamic : es2015 as esm2015

Compiling @auth0/angular-jwt : module as esm5

Compiling @angular/common/http : es2015 as esm2015
```
so I assume under the hood `ngcc` is run on only those packages.

However when `ivy-ngcc` is run the output is:
```
Compiling @angular/animations : esm2015 as esm2015
Compiling @angular/animations : main as umd
Compiling @angular/animations : fesm2015 as esm2015
Compiling @angular/animations : fesm5 as esm5
Compiling @angular/animations : esm5 as esm5
Compiling @angular/compiler/testing : fesm5 as esm5
Compiling @angular/compiler/testing : fesm2015 as esm2015
Compiling @angular/compiler/testing : esm2015 as esm2015
Compiling @angular/core : fesm5 as esm5
Compiling @angular/compiler/testing : esm5 as esm5
Compiling @angular/compiler/testing : main as umd
Compiling @angular/core : main as umd
Compiling @angular/core : esm5 as esm5
Compiling @angular/core : fesm2015 as esm2015
Compiling @auth0/angular-jwt : module as esm5
Compiling @angular/core : esm2015 as esm2015
Compiling @auth0/angular-jwt : main as commonjs
Compiling @angular/animations/browser : esm5 as esm5
Compiling @angular/animations/browser : fesm5 as esm5
Compiling @angular/animations/browser : main as umd
Compiling @angular/animations/browser : fesm2015 as esm2015
Compiling @angular/animations/browser : esm2015 as esm2015
Compiling @angular/core/testing : fesm2015 as esm2015
Compiling @angular/common : fesm5 as esm5
Compiling @angular/common : fesm2015 as esm2015
Compiling @angular/animations/browser/testing : fesm2015 as esm2015
Compiling @angular/animations/browser/testing : fesm5 as esm5
Compiling @angular/animations/browser/testing : esm5 as esm5
Compiling @angular/animations/browser/testing : esm2015 as esm2015
Compiling @angular/animations/browser/testing : main as umd
Compiling @angular/common : esm5 as esm5
Compiling @angular/common : esm2015 as esm2015
Compiling @angular/common : main as umd
Compiling @angular/core/testing : fesm5 as esm5
Compiling @angular/platform-browser : fesm2015 as esm2015
Compiling @angular/core/testing : esm2015 as esm2015
Compiling @angular/common/http : fesm5 as esm5
Compiling @angular/common/http : fesm2015 as esm2015
Compiling @angular/common/http : esm2015 as esm2015
Compiling @angular/common/testing : fesm2015 as esm2015
Compiling @angular/router : fesm2015 as esm2015
Compiling @angular/platform-browser/testing : fesm2015 as esm2015
Compiling @angular/common/http/testing : fesm5 as esm5
Warning: Unknown member type: "[key: string]: (data: any) => void;
Compiling @angular/common/http : main as umd
Compiling @angular/common/http : esm5 as esm5
Compiling @angular/platform-browser-dynamic : fesm2015 as esm2015
Compiling @angular/common/http/testing : esm5 as esm5
Warning: Unknown member type: "[key: string]: (data: any) => void;
Compiling @angular/common/http/testing : esm2015 as esm2015
Warning: Unknown member type: "[key: string]: (data: any) => void;
Compiling @angular/common/http/testing : main as umd
Compiling @angular/common/http/testing : fesm2015 as esm2015
Warning: Unknown member type: "[key: string]: (data: any) => void;
Compiling @angular/platform-browser : fesm5 as esm5
Compiling @angular/forms : esm2015 as esm2015
Compiling @angular/forms : fesm5 as esm5
Compiling @angular/platform-browser : esm2015 as esm2015
Compiling @angular/forms : fesm2015 as esm2015
Compiling @angular/forms : esm5 as esm5
Compiling @angular/forms : main as umd
Compiling @angular/platform-browser : esm5 as esm5
Compiling @angular/platform-browser : main as umd
Compiling @angular/platform-browser/animations : fesm5 as esm5
Compiling @angular/platform-browser/animations : esm5 as esm5
Compiling @angular/platform-browser/animations : esm2015 as esm2015
Compiling @angular/platform-browser/animations : fesm2015 as esm2015
Compiling @angular/platform-browser/animations : main as umd
Compiling @angular/core/testing : esm5 as esm5
Compiling @angular/core/testing : main as umd
Compiling @angular/platform-browser-dynamic : fesm5 as esm5
Compiling @angular/platform-browser/testing : fesm5 as esm5
Compiling @angular/platform-browser-dynamic : esm5 as esm5
Compiling @angular/platform-browser-dynamic : esm2015 as esm2015
Compiling @angular/platform-browser-dynamic : main as umd
Compiling @angular/platform-browser/testing : esm2015 as esm2015
Compiling @angular/platform-browser/testing : esm5 as esm5
Compiling @angular/platform-browser/testing : main as umd
Compiling @angular/common/testing : fesm5 as esm5
Compiling @angular/common/testing : esm2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : fesm2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : fesm5 as esm5
Compiling @angular/platform-browser-dynamic/testing : esm2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : main as umd
Compiling @angular/common/testing : esm5 as esm5
Compiling @angular/platform-browser-dynamic/testing : esm5 as esm5
Compiling @angular/common/testing : main as umd
Compiling @angular/router : fesm5 as esm5
Compiling @angular/router/testing : fesm5 as esm5
Compiling @angular/router : main as umd
Compiling @angular/router : esm5 as esm5
Compiling @angular/router/testing : esm2015 as esm2015
Compiling @angular/router : esm2015 as esm2015
Compiling @angular/router/testing : fesm2015 as esm2015
Compiling @angular/router/testing : esm5 as esm5
Compiling @angular/router/testing : main as umd
```

**Comment by mikolaj-leszczynski** [comment]
\+ 
in `ivy-ngcc` we have
`Compiling @auth0/angular-jwt : main as commonjs`
and in `ng build`:
`Compiling @auth0/angular-jwt : module as esm5`
Maybe this is the reason?

**Comment by gkalpak** [comment]
Thx for the details, @mikolaj-leszczynski :+1:

`Ngcc` can be either run explicitly from the commnd line (as `ivy-ngcc` (actually renamed to `ngcc` in the comng version)) or implicitly via `ng build`. In both cases, the same code is used, but with slightly different options. One of the dofferences is that `ivy-ngcc` (without any option arguments) will compile all supported formats (es2015, es5, commonjs, umd) of all Angular dependencies it finds in `node_modules/`, while when run via `ng build` it will only compile the formats it needs. (It is possible to configure `ivy-ngcc` to behave (almost) identical to `ng build` - see #32999.)

So, this explain why you see both `Compiling @auth0/angular-jwt : main as commonjs` and `Compiling @auth0/angular-jwt : module as esm5` with `ivy-ngcc`, but only `Compiling @auth0/angular-jwt : module as esm5` with `ng build`.

This still doesn't explain the error you are getting :grin:
Does the error go away if you change your post-install script to the one mentioned in #32999?

**Comment by mikolaj-leszczynski** [comment]
@gkalpak what do you mean by:
> ivy-ngcc (without any option arguments) will compile all supported formats (es2015, es5, commonjs, umd) of all Angular dependencies it finds in node_modules/
?
Do you say that running `ivy-ngcc` on an angular lib produces 4 versions of the same app, one for each format?

>while when run via ng build it will only compile the formats it needs. 
Which formats do we need? Am I not aware of something? How does the compiler know what formats do I need?

> Does the error go away if you change your post-install script to the one mentioned in #32999?
You mean this: `ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points` 
?

**Comment by mikolaj-leszczynski** [comment]
With the above `positinstall` script:
1. `ng build` produces an error:
```
ERROR in ./src/app/app.module.ts 124:56-76
"export 'EffectsRootModule' (imported as 'i2') was not found in '@ngrx/effects'
2. `ng start` works fine!
3. Is it normal that I get the same packages compiled two times? First time during `yarn` as a part of postinstall script and second time during `ng build` ? Shouldn't `ng build` be aware of the fact that I have just compiled the required libraries ? 
```

**Comment by gkalpak** [comment]
>> `ivy-ngcc` (without any option arguments) will compile all supported formats (es2015, es5, commonjs, umd) of all Angular dependencies it finds in `node_modules/`
>
> Do you say that running `ivy-ngcc` on an angular lib produces 4 versions of the same app, one for each format?

Almost :smiley: `ivy-ngcc` does not create app versions; it transforms Angular dependencies to be in Ivy format (i.e. as if they had been compiled by `ngtsc` (the Ivy compiler)). Each Angular dependency you have in your `node_modules/` can have up to 4 different formats (different sets of files) - es2015, es5, commonjs, umd - that `ngcc` knows how to transform. So, when running `ivy-ngcc` (now renamed to `ngcc` btw) without any arguments, it will transform all formats of each dependency that exist (some dependencies may not provide all formats).

>> while when run via `ng build` it will only compile the formats it needs.
>
> Which formats do we need? Am I not aware of something? How does the compiler know what formats do I need?

This depends on your bundler (by default `webpack` under the cli hood), so `@angular/cli` knows which formats you need. Without getting into details, currently it tells `ngcc` (via the `--properties` option) to consider the following properties (in that order): `es2015`, `browser`, `module`, `main`
(`es2015` is omitted if you have `target: es5` in your `tsconfig.json`).

>> Does the error go away if you change your post-install script to the one mentioned in #32999?
>
> You mean this: `ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points`?

Yes :smiley:

##
> Is it normal that I get the same packages compiled two times? First time during `yarn` as a part of postinstall script and second time during `ng build`?

No, it is not normal 😕 

> ERROR in ./src/app/app.module.ts 124:56-76
> "export 'EffectsRootModule' (imported as 'i2') was not found in '@ngrx/effects'

Regarding the new error: Could you provide a minimal reproduction?

**Comment by yusuke-oba1** [comment]
I had same issue. The minimal reproduction is below.

Set the 'target' property in tsconfig.json to 'es5'
```
  "compilerOptions": {
      "target": "es5",
     ...
  }
```
 and run 'npm start', it causes error
```
ERROR in ./src/app/app.module.ts 23:26-46
"export 'EffectsRootModule' (imported as 'i1') was not found in '@ngrx/effects'
```

On the other hand, set the target property to 'es2015', it works fine. I hosted to here
https://github.com/yusuke-oba1/ivy-test

**Comment by mikolaj-leszczynski** [comment]
when having Ivy and postinstall script: `ngcc` do I also have to have bazel builder instead of custom one in my `angular.json` ?

**Comment by alxhub** [comment]
Hello @mikolaj-leszczynski!

Are you still seeing this problem when using the latest (RC) version of Angular 9? If so, can you please provide a link to a reproduction repository with instructions? Thanks!

-Alex

**Comment by mikolaj-leszczynski** [comment]
Hi @alxhub , I will check it soon and let you know! Thanks for asking :)

**Comment by petebacondarwin** [comment]
Closing this as the reproduction steps at https://github.com/angular/angular/issues/33100#issuecomment-542113903 no longer cause an error; and the errors related to `@ngrx/effects` were fixed some time ago in https://github.com/angular/angular/commit/002a97d8529b183bde37ac02eb93dd2866fa5740.

@mikolaj-leszczynski (or others on this thread) - if you are still experiencing errors building please open a new issue with a new reproduction.
