### ISSUE TITLE
Method ngOnInit changed in 'Getting started' guide in 'Forms' page

### ISSUE THREAD

**Issue by antgar9** [angular/angular#33106]
# 📚 Docs or angular.io bug report

### Description

There is an error in the 'Getting started' guide:

In 'Managing data', CartComponent has this method:
  ngOnInit() {
    this.items = this.cartService.getItems();
  }
  
But next, in 'Forms', that line appears inside the constructor.

### What's the affected URL?**
https://angular.io/start/data
https://angular.io/start/forms

**Comment by dannyskoog** [comment]
It’s not really an error. It’s more of an inconsistency between the two guides, which could be seen as enough argument for changing the latter one

**Comment by santoshyadav198613** [comment]
I think @antgar9 is right, we should avoid making service calls from the constructor, @antgar9 feel free to open a PR @kapunahelewong any thought?
constructor(
    private cartService: CartService,
    private formBuilder: FormBuilder,
  ) {
    **this.items = this.cartService.getItems();** // Should be moved to ngOnInit

    this.checkoutForm = this.formBuilder.group({
      name: '',
      address: ''
    });
  }

**Comment by kapunahelewong** [comment]
Thanks for this @antgar9 and you're right, it is inconsistent. I have a PR to fix it https://github.com/angular/angular/pull/32839, so it should be better soon. Thanks for bringing it up!

**Comment by ajitsinghkaler** [comment]
@kapunahelewong this has been resolved so I think we can close this issue
