### ISSUE TITLE
ngc does not handle barrel files properly in many situations

### ISSUE THREAD

**Issue by rraziel** [angular/angular#33121]
# 🐞 bug report

### Affected Package
The issued is caused by package @angular/compiler-cli

### Is this a regression?
No

### Description
Note: PR #22856 by @jeffora lay the groundwork for proper barrel file support

Right now, any path depth with barrel files fails because `MetadataBundler.resolveModuleName` and a few other methods do not keep track of the parent paths, mostly leading to intermediate paths disappearing.

With the following example, no decorator metadata gets added to metadata.json file, and the `MetadataBundler` processes `repro.module` as if it was at `src/repro.module.ts` rather than `src/lib/repro.module.ts` (because `path.dirname(from)` returns `.` for `./lib`, thus losing the path in the process when then joining with `repro.module`).

<pre><code>
// src/public-api.ts
import * from './lib';

// src/lib/index.ts
export {ReproModule} from './repro.module';

// src/lib/repro.module.ts
import {NgModule} from '@angular/core';
@NgModule({})
class ReproModule;
export {ReproModule};
</code></pre>

This is only the case for metadata retrieval, the classes/etc. are properly exported. The metadata.json does not hold any metadata information though.

Without barrel files, the metadata.json file is (html tags removed):

<pre><code>
{
    "__symbolic": "module",
    "version": 4,
    "metadata": {
        "ReproService": {
            "__symbolic": "class",
            "decorators": [{
                "__symbolic": "call",
                "expression": {
                    "__symbolic": "reference",
                    "module": "@angular/core",
                    "name": "Injectable",
                    "line": 2,
                    "character": 1
                },
                "arguments": [{
                    "providedIn":"root"
                }]
            }],
           "members": {
               "__ctor__": [{
                   "__symbolic": "constructor"
               }]
            },
            "statics": {
                "ngInjectableDef": {}
            }
        },
       ....
}
</code></pre>

With barrel files, the metadata.json file is:

<pre><code>
{
    "__symbolic": "module",
    "version": 4,
    "exports": [{
        "from": "./repro.service"
    }, {
        "from": "./repro.component"
    }, {
        "from": "./repro.module"
    }],
    "metadata": {},
    "origins": {},
    "importAs": "repro"
}
</code></pre>

## 🔬 Minimal Reproduction
<pre><code>
git clone https://github.com/rraziel/ngc-barrel-repo
cd ngc-barrel-repo; npm i
ng build repro
cat dist/repro/repro.metadata.json
</code></pre>

The project was created with:
<pre><code>
ng new ngc-barrel-repro
ng generate library repro
add an index.ts next to repro.module.ts that exports what is exported from public-api.ts
modify public-api.ts to use index.ts implicitly
</code></pre>

Relevant files:
- https://github.com/rraziel/ngc-barrel-repo/blob/master/projects/repro/src/public-api.ts
- https://github.com/rraziel/ngc-barrel-repo/blob/master/projects/repro/src/lib/index.ts

## 🔥 Exception or Error
The generated *metadata.json file does not contain metadata information (e.g. the NgModule decorator).
Many other issues can also arise depending on how files are imported and generally end up with undefined error messages (undefined module, duplicate undefined keys, etc.).

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.8
Node: 11.8.0
OS: win32 x64
Angular: 8.2.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.8
@angular-devkit/build-angular      0.803.8
@angular-devkit/build-ng-packagr   0.803.8
@angular-devkit/build-optimizer    0.803.8
@angular-devkit/build-webpack      0.803.8
@angular-devkit/core               8.3.8
@angular-devkit/schematics         8.3.8
@angular/cdk                       8.2.3
@angular/cli                       8.3.8
@ngtools/webpack                   8.3.8
@schematics/angular                8.3.8
@schematics/update                 0.803.8
ng-packagr                         5.6.1
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Anything else relevant?**
This issue makes it very difficult to work with a monorepo (unless going through all the files and manually appending index for all the barrel imports), especially with the current `module undefined` messages as I mostly end up commenting out imports until the build works. Or just adding a console.log with the module name to the bundler code.

**Comment by rraziel** [comment]
@alexeagle , @alxhub : just pinging as you were reviewers on that PR and probably most relevant when it comes to this issue.

**Comment by rraziel** [comment]
Note: #23713 was closed because of inactivity, but more and more people are encounting these issues

**Comment by alxhub** [comment]
Hi @rraziel,

Thanks for the issue report. This is indeed a design flaw in View Engine's metadata system. The PR you linked (#22856) does appear to help, but calling TS module resolution is expensive - it's likely not as simple as that. It's not likely that a fix for this will land as View Engine is being replaced by our Ivy compiler/runtime.

The good news is that this bug is completely fixed by Ivy, which doesn't use metadata files at all and should completely solve this problem. So any project using Ivy with 9.x or later should be fine with barrel files.

**Comment by rraziel** [comment]
Hello @alxhub ,

I kind of forgot about this issue as I moved to Ivy a while back, and it does indeed work much better there.

Pretty sure this issue can be closed, since I assume existing projects without Ivy avoided barrel files and new projects that may want to use barrel files will use the latest version of Angular anyway.

Thanks for the update on the issue though.
