### ISSUE TITLE
Enforce trailing comma style guide rule

### ISSUE THREAD

**Issue by dannyskoog** [angular/angular#33133]
# 🚀 feature request

### Relevant Package
All

### Description
The [contribution guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-coding-rules) state that [Google's JavaScript Style Guide](https://google.github.io/styleguide/jsguide.html) is being followed. Although that's incorrect since the **trailing comma** rule for [object](https://google.github.io/styleguide/jsguide.html#features-objects-use-trailing-comma) and [array](https://google.github.io/styleguide/jsguide.html#features-arrays-trailing-comma) literals is violated. Most likely since this rule isn't enforced, which makes it not being a rule at all at the moment.

### Describe the solution you'd like
**Best option:** Add the rule to the formatter (`clang-format`) if possible.

**2nd best option:** Add the rule to TS lint. I.e:
```json
"trailing-comma": [
  true,
  {
    "multiline": {
      "objects": "always",
      "arrays": "always"
    },
    "esSpecCompliant": true
  }
]
```

### Describe alternatives you've considered
There are none

**Comment by santoshyadav198613** [comment]
For adding rules , you can add this feature request in https://github.com/mgechev/codelyzer

**Comment by trotyl** [comment]
@santoshyadav198613 The OP is about this repo (Angular source code), not user project.

**Comment by dannyskoog** [comment]
Thanks for confirming my suspicions @trotyl :) Great - then I'm where I should be

**Comment by santoshyadav198613** [comment]
Thanks, @trotyl I thought it's for user project.
