### ISSUE TITLE
Question: Web-Components vs. Angular-2-Directives

### ISSUE THREAD

**Issue by manfredsteyer** [angular/angular#3313]
Hi,

as I unterstand it, Angular-2-Directives won't be "real" Web Components but some "light-version" of  Web Components and Angular-2 will be able to work with Web Components seamlessly. 

Now I'm wondering, what it will take to write "real" Web Components with Angular 2. Are there any plans on that?

Wishes,
Manfred

**Comment by mhevery** [comment]
You will be able to write an Angular component and then wrap it int a real component. The exact details are still TBD.

**Comment by manfredsteyer** [comment]
Great. Thx for this quick reply.
