### ISSUE TITLE
Use array shorthand syntax

### ISSUE THREAD

**Issue by dannyskoog** [angular/angular#33135]
# 🚀 feature request

### Relevant Package
All

### Description
Typescript offers 2 array syntax:

**Shorthand:** `T[]` _(read only variant `readonly T[]`)_
**Generic:** `Array<T>` _(read only variant `ReadonlyArray<T>`_)

Currently we're using both, although the `shorthand` has a HUGE majority in the code-base. And since I'm a big fan of unification it would be preferable to settle for just one of them - specifically for the `shorthand` one IMHO.

`Shorthand` pros:
- It's by far the most used syntax (of the two) throughout the code-base
- It's shorter to write
- It's similar to many other programming languages' syntax
- It doesn't change type when made read only (by utilizing Typescript's readonly keyword)

### Describe the solution you'd like
Add TS lint rules that enforce usage of the `shorthand`:

```json
"array-type": [
  true,
  "array"
],
"ban-types": [
  true,
  [
    "ReadonlyArray<.+>",
    "Use 'readonly T[]' instead."
  ]
],
```

### Describe alternatives you've considered
Keep using both

**Comment by santoshyadav198613** [comment]
For adding rules , you can add this feature request in https://github.com/mgechev/codelyzer

**Comment by dannyskoog** [comment]
@santoshyadav198613 this issue is for Angular's internal source code, not external consumers' ones

**Comment by MrJithil** [comment]
Hi @dannyskoog ,
This is not the feature provided by Angular. The `TypeScript` providing both the ways to declare the array.

To unifying these, please consider to raise a feature request in [TypeScript](https://github.com/Microsoft/TypeScript).

@mhevery, Please consider closing the issue, if the above answer sounds relevant.

<sup>Disclaimer : in my perspectives, it is good to have multiple ways to declare an array</sup>

**Comment by dannyskoog** [comment]
@MrJithil thanks. And I’m very well aware of everything you’re saying.

The purpose of this issue is to discuss whether we are interested in unifying the array syntax throughout the Angular codebase or not.

And the `feature` issue template was just the most suitable one out of all available templates :)

Given that, I still think it’s valuable to keep this one open a little longer in order for people to get the chance to chip in.

**Comment by dannyskoog** [comment]
@mhevery Given the low activity of this issue I believe it's reasonable to close it. What do you think?

**Comment by petebacondarwin** [comment]
Closing as this request is just to change the typings of the internal code base for Angular - it has no impact on external application developers - and there is not much value in constraining this way of defining arrays.
