### ISSUE TITLE
httpinterceptor not working lazy modules

### ISSUE THREAD

**Issue by rajashekarreddy2222** [angular/angular#33138]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular: 8.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.3.5
@angular-devkit/schematics        8.3.5
@angular/cdk                      8.2.0
@angular/cli                      8.3.5
@angular/fire                     5.2.1
@angular/language-service         8.0.0
@angular/material                 8.2.0
@angular/pwa                      0.803.5
@ngtools/webpack                  8.0.6
@schematics/angular               8.3.5
@schematics/update                0.803.5
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Anything else relevant?**

**Comment by alxhub** [comment]
Hello @rajashekarreddy2222,

I'm closing this for two reasons:

1. There is no information in the bug report itself. When you file issues in the Angular repo, please take the time to fill out the issue template. We often cannot investigate or even understand the problem if you don't provide a detailed description and a reproduction.

2. This is working as designed. See the documentation section on providing the interceptor here: https://angular.io/guide/http#http-interceptors. Interceptors must be registered in the same injector as `HttpClient` itself.
