### ISSUE TITLE
Support node-gyp version 6.0.0

### ISSUE THREAD

**Issue by omarlara** [angular/angular#33145]
# 🚀 feature request
for Angular Version 6
### Relevant Package
node-sass peer dependency node-gyp (upgrade to version  6.0.0)
 This feature request is for @angular/....

### Description
support node-gyp 6.0.0
https://github.com/nodejs/node-gyp/releases/tag/v6.0.0

### Describe the solution you'd like
upgrade node-sass peer dependency node-gyp to version  6.0.0

**Comment by alan-agius4** [comment]
Hi @omarlara, I'm sorry, but this issue is not caused by Angular.` node-sass` has a direct dependency on `node-gyp` version `3.x.x`.  `node-sass` don't seem to be willing to upgrade `node-gyp`.

See: https://github.com/sass/node-sass/issues/2716
