### ISSUE TITLE
docs: Creating Libraries Guide should include guidance on CSS/assets

### ISSUE THREAD

**Issue by Splaktar** [angular/angular#33141]
# 📚 Docs or angular.io bug report

### Description
I spent some time in January working on a new library. One thing that is missing from the new Library guide, and not supported out of the box (but generally required by most library authors) in the Angular CLI or ng-packagr, is shipping assets or theme SCSS files with your library. This issue (https://github.com/angular/angular-cli/issues/11071) and many other linked/closed issues with hundreds of 👍  indicate that this is a major need and at minimum that the docs to work around this are not available.

It appears that the general guidance for SCSS is to use the `scss-bundle` package similar to [what Angular Material does](https://github.com/angular/components/blob/aaa656dbab41fee298244cc25351da8f44e9f614/tools/BUILD.bazel#L16-L24). For assets, it appears that manually copying them via npm scripts is the most common approach.

I can understand some hesitation to include details about library-specific implementation that could cause some kind of support burden.

However, the other perspective is that library authors see the docs and get started and then get completely stuck on assets and scss files (like many hundreds have already run into), etc with no references for how to proceed. They will then continue to open duplicate issues in the Angular CLI GitHub.

Perhaps there is some kind of happy medium between providing them with some starting points on how to handle this without providing them a fully supported solution that doesn’t exist yet. Even telling/reminding people that you can just use regular command line copy commands to move assets via NPM scripts would help people rather than them having to dig through a lot of closed GitHub issues to find examples that work.

### What's the affected URL?**
- https://next.angular.io/guide/creating-libraries
- https://angular.io/guide/creating-libraries

@jbogarthyde I haven't had time to write up some proposed copy for this, but I wanted to at least create the issue.

**Comment by santoshyadav198613** [comment]
This is much needed, I also struggled with the same. I will love to help in documentation, so can we add how to use scss-bunlde @Splaktar .

**Comment by santoshyadav198613** [comment]
Hi @kapunahelewong,
I will start working on this.

**Comment by santoshyadav198613** [comment]
Just raised a WIP PR to move further discussion.

**Comment by Splaktar** [comment]
Closed in https://github.com/angular/angular/commit/26b17aee1441534b554862129df308c780169c5f via PR https://github.com/angular/angular/pull/34217.
