### ISSUE TITLE
No error if trackBy function undefined

### ISSUE THREAD

**Issue by fider** [angular/angular#33164]
# 🐞 bug report

### Affected Package
@angular/compiler-cli v8.2.8

### Is this a regression?
No idea if it is regression or intended behavior

### Description
If `undefinedFunction` is provided to `*ngFor trackBy` then I expect error (compilation or runtime console.error).
Actually no error observed.

## 🔬 Minimal Reproduction
Check `undefinedFunction` reference in `app.component.html`:
https://stackblitz.com/edit/angular-2qfgef

## 🔥 Exception or Error
No error, **but I suppose it is desired behavior to see error** (compilation or runtime console error)

## 🌍  Your Environment
- "@angular/cli": "~8.3.6"
- "@angular/compiler-cli": "~8.2.8"
- Chrome Version 77.0.3865.120
- `> ng serve`

**Comment by trotyl** [comment]
The error is reported as expected:

![image](https://user-images.githubusercontent.com/6059170/66815858-9d3bec80-ef6b-11e9-82a8-c9e85cde806f.png)

StackBlitz only supports JIT build, but template type-checking requires AOT build.

Note: `ng serve` is also JIT by default, if you want template type-checking you need to enable it yourself.
