### ISSUE TITLE
Regarding a Routing 

### ISSUE THREAD

**Issue by krishnaradical** [angular/angular#33172]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

There should be add one configuration to initialization of global variable and OnInit function.
* Because some time My requirement is on redirect of url I don't want to initialize  a OnInit function as well as global  variable. 
* Please if you have this feature in your latest version please replied in comment otherwise think about this feature

**Comment by santoshyadav198613** [comment]
Sorry @krishnaradical ,
But I don't think so anyone is able to understand the problem statement. Can you describe in detail, also some examples will be really helpful.

**Comment by krishnaradical** [comment]
> Sorry @krishnaradical ,
> But I don't think so anyone is able to understand the problem statement. Can you describe in detail, also some examples will be really helpful.

My requirement is if we route one page to another page it will  refresh a page and call function ngOnInit. so, I am suggesting the they should give configure for call function on initialization of page.

For example:- 
I have two component
1. school.component and another is student.component.
I initialize two variable in school.component and  one variable in student component.
I am redirecting school to student  then it will again reinitialize.

**Comment by santoshyadav198613** [comment]
There are many alternatives to this and is not a feature request, I would suggest using service in this case. and if you need more approach, raise this on StackOverflow

**Comment by atscott** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
