### ISSUE TITLE
Root ICU doesn't keep message ID

### ISSUE THREAD

**Issue by HitkoDev** [angular/angular#33171]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler@next

### Is this a regression?

Yes

### Description

When i18n message only contains a single ICU expression, compiler doesn't keep specified message ID.

## 🔬 Minimal Reproduction
https://github.com/HitkoDev/repro-app

**Comment by AndrewKushnir** [comment]
Thanks for reporting the problem @HitkoDev. This issue should be resolved in PR #33191.
