### ISSUE TITLE
docs: clarify docs for when derived class has no decorator

### ISSUE THREAD

**Issue by kapunahelewong** [angular/angular#33182]
# 📚 Docs or angular.io bug report

### Description

Clarify docs in cases of a derived class doesn't have a decorator (`@Directive` or `@Injectable`)

### What's the affected URL?**
to be determined

### Reproduction Steps**

n/a

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Anything else relevant?

Specifically, see https://github.com/angular/angular/issues/30080#issuecomment-539631082 for details.

**Comment by AndrewKushnir** [comment]
Closing this ticket for now since there are no specific action items (we can improve the necessary docs and cover this topic iteratively).
