### ISSUE TITLE
Change detection needs to fire a allViewChangesDone callback

### ISSUE THREAD

**Issue by rkirov** [angular/angular#3319]
This would be similar to 'allChangesDone' but it will include any change detectors in the view tree.

It is needed for ViewQuery to fire its onChange callback guaranteeing it has all the directives that might have materialized in this CD turn. See failing test - https://github.com/rkirov/angular/commit/e543bab8a7f1efa9970d68b82c70f68cc81447af

**Comment by mhevery** [comment]
I am confused, Are you suggesting that for `Query` to work it needs to wait for global CD to finish? That does not seem right. Can we chat about this?

**Comment by rkirov** [comment]
The name is unfortunate, I am not proposing anything global.

Imagine the following tree of injectors/nodes.
```
injQ ---- (component view) -- 
 - inj1                       | -- inj3
 - inj2                       | -- inj4
```

`onChange` is called when after we dirty-check the bindings on injQ.
`onAllChangesDone` is called after we dirty-check inj1 and inj2 (but before we dirty check inj3 and inj4).
We need a callback local to injQ to be called after we dirty-check all bindings in inj1, inj2 and the whole component view tree (inj3 and inj4).

The callback is still local to injQ, and not global.

**Comment by mhevery** [comment]
I see, makes sense.

**Comment by mhevery** [comment]
clearing assignee since no milestone.

**Comment by rkirov** [comment]
fixed in https://github.com/angular/angular/commit/5ebeaf7c9bdab8de6d11c7b4c4d0954553196903
