### ISSUE TITLE
Tour of heroes, services chapter 4: adding service as described causes error

### ISSUE THREAD

**Issue by emmasaunders** [angular/angular#33196]
# 📚 Docs or angular.io bug report

### Description

When following the Tour of Heroes tutorial, adding the heroService as described results in console error: this.heroService.getHeroes is not a function. Problem might be that I have declared getHeroes() in the wrong place (see snippet below). I've tried several positions for it. If this is the problem could the correct position be specified in the documentation please?

## 🔬 Minimal Reproduction
Follow the tutorial

### What's the affected URL?**
https://angular.io/tutorial/toh-pt4

### Reproduction Steps**
Follow the tutorial up to the part "See it run" before the "Observable data" section.

### Expected Behavior**
No JS error.

## 🔥 Exception or Error
Error
<pre><code>this.heroService.getHeroes is not a function</pre></code>
Code snippet
<pre><code>
  heroes: Hero[];

  constructor(private heroService: HeroService) { }

  getHeroes():void { this.heroes = this.heroService.getHeroes(); }

  ngOnInit() {
    this.getHeroes();
  }
</code></pre>

### Browser info
Don't think browser specific. Tested in Chrome and Firefox.

**Comment by santoshyadav198613** [comment]
can you share a stackblitz link, because looks correct to me

**Comment by emmasaunders** [comment]
It worked on stackblitz: https://stackblitz.com/edit/angular-8dutqe
I leave the link here as hopefully useful for others to file check this intermediate step.
I started and stopped the server in terminal and now it works. Sorry for any waste of time. I did go through the tutorial multiple times and kept getting the same error

**Comment by santoshyadav198613** [comment]
No problem, you can go ahead and close this issue.
