### ISSUE TITLE
docs: fullTemplateTypeCheck's initial value is true

### ISSUE THREAD

**Issue by HalitTalha** [angular/angular#33193]
# 📚 Docs or angular.io bug report

### Description

Documentation about `fullTemplateTypeCheck`option's default value may be confusing. In the docs the default value is said to be false however [tsconfig schematic](https://github.com/angular/angular-cli/blob/a13924364482cbf9a61ba4c3ac1171d3feaf8034/packages/schematics/angular/library/files/tsconfig.lib.json.template#L17) comes with the fullTemplateTypeCheck option set as true. This could be an initial value however it actually makes the default behavior true for the users of the framework.
I encountered this after migrating to an angular 8 version. The term default value deserves to be false however initial value is worth mentioning in the docs I think.

Please check the corresponding angular.io page:
https://angular.io/guide/angular-compiler-options#fulltemplatetypecheck

**Comment by jbogarthyde** [comment]
Changing default for v9 docs: https://github.com/angular/angular/pull/33577

**Comment by JoostK** [comment]
This was clarified in #33577.
