### ISSUE TITLE
bazel error when running scripts/build-packages-dist.sh

### ISSUE THREAD

**Issue by vikerman** [angular/angular#33208]
Ran scripts/build-packages.dist.sh from two Linux machines. Got the following bazel error

ERROR: /usr/local/google/home/viks/.cache/bazel/_bazel_viks/5175b640a65049738e46185f3441ce29/external/com_google_protobuf/BUILD:85:1: undeclared inclusion(s) in rule '@com_google_protobuf//:protobuf_lite':
this rule is missing dependency declarations for the following files included by 'external/com_google_protobuf/src/google/protobuf/stubs/common.cc':
  '/usr/lib/gcc/x86_64-linux-gnu/6/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/6/include/stdarg.h'
  '/usr/lib/gcc/x86_64-linux-gnu/6/include/stdint.h'
  '/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/limits.h'
  '/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/syslimits.h'

WORKAROUND: 
In .bazelrc in the root of the project comment out the following lines (in Remote HTTP Caching section)

```
build --remote_http_cache=https://storage.googleapis.com/angular-team-cache
build --remote_accept_cached=true
build --remote_upload_local_results=false
```

**Comment by vikerman** [comment]
@alexeagle @josephperrott

**Comment by IgorMinar** [comment]
I believe that this is now obsolete. Closing
