### ISSUE TITLE
Stackblitz tutorial - stackblitz does not have anything to do with building a simple e-commerce site with a catalog, shopping cart, and check-out form

### ISSUE THREAD

**Issue by AMDphreak** [angular/angular#33213]
# 📚 Docs or angular.io bug report

### Description

 
The Stackblitz basic app has nothing in common with the Angular tutorial. Angular tutorial is inapplicable to what new users see in Stackblitz.

![image](https://user-images.githubusercontent.com/1058978/66970588-a6a08400-f053-11e9-9f6e-27d6bd880538.png)

Meanwhile, on Angular.io:
> This tutorial introduces you to the essentials of Angular by walking you through building a simple e-commerce site with a catalog, shopping cart, and check-out form.

### What's the affected URL?**
 https://angular.io/start

**Comment by AMDphreak** [comment]
> I don't see why you would expect the basic StackBlitz app to have anything to do with the Angular tutorial. StackBlitz is independent online IDE and the basic projects for the various languages/frameworks it supports are supposed to be basic.
> 
> But I _do_ see that the starting section of the https://angular.io/start guide is indeed a little confusing as to what is going on. A couple of examples:
> 
> * It mentions the _"StackBlitz Generator"_, which I assume refers to our internal [stackblitz-builder](https://github.com/angular/angular/tree/d192a7b47/aio/tools/stackblitz-builder) tool (that the reader should know nothing about).
> * The button that you can click to generate/clone a pre-made minimal e-commerce app says _"Click here to create a new project in StackBlitz"_, which sounds more like it will create a vanilla StackBlitz project (that is not the case).
> * Then further below it says _"StackBlitz creates a starter Angular app"_. Here _"starter Angular app"_ sounds like a generic thing (the basic app that StackBlitz creates for you when you choose the Angular template).
> 
> So, I think the docs could make a better job explaining what is going on, which in a nutshell is that we have created a minimal e-commerce app that is going to be used for the tutorial and provide the reader with a button to clone this app (or rather generate a new instance of the pre-made minimal e-commerce app).

Yeah I noticed this after writing my issue. But I left the issue as is, because this is the issue that new users see---not the "we wanted you to do it this way, but you did it that way because we were ambiguous" problem. The fact that people downvoted this is more a condemnation of their assumptions than mine.

**Comment by jbogarthyde** [comment]
resolved by referenced PRs
