### ISSUE TITLE
If route.queryParamMap contains an array as a param it leads to trigger queryParamMap observable even if any params are not changed

### ISSUE THREAD

**Issue by pakhuta** [angular/angular#33227]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?

No

### Description
If route.queryParamMap contains an array as a param it leads to trigger `queryParamMap ` observable even if any `params` are not changed.
Steps to reproduce:

1. Open https://stackblitz.com/edit/angular-1qdje4
1. Open console (dev console) in stackblitz.
1. Click on link "Go to parent component". In console will be displayed message from `route.queryParamMap` observable handler.
1. Click on link "Go to child component".

**Actual result:**
In console again will be displayed message from `route.queryParamMap` observable handler.
The second link "Go to child component" has attribute `[queryParamsHandling]="'preserve'"`. It means that queryParams will be the same as on current route and `route.queryParamMap` observable shouldn't be triggered.
**Expected result:**
`route.queryParamMap` observable shouldn't be triggered.

P.S. If we change attribute of link "Go to parent component" from `[queryParams]="{item: [1, 2, 3]}"` to `[queryParams]="{item: 1}"`, i.e. make value of `item` as primitive type it works as expected: `route.queryParamMap` observable is not triggered.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-1qdje4

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.1.0
Node: 12.10.0
OS: win32 x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.801.3
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.801.3
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.1.0
@angular/language-service         8.2.0
@ngtools/webpack                  8.1.3
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Comment by JonasTaulienSolutions** [comment]
I experience the same problem (Angular 8.2.7): When i have a query parameter that is an array and I change the fragment by executing:
```ts
this.router.navigate(
    [],
    {
        relativeTo: this.route, // this.route: ActivatedRoute
        queryParamsHandling: 'preserve',
        fragment: 'my-fragment',
        replaceUrl: true
    }
);
```
`this.route.queryParamMap` emits an event.

**Comment by pakhuta** [comment]
Guys, good news!
Bug is not reproduced in Angular 9 👏. Please consider to close the issue and related PR.

The same code as in minimal reproduction in initial comment but with using Angular 9: https://stackblitz.com/edit/angular-ro4prz

@matsko, @atscott

**Comment by atscott** [comment]
@pakhuta That's great to hear. Thanks for letting us know 😄
