### ISSUE TITLE
Dynamically defined template reference variables

### ISSUE THREAD

**Issue by jzabinski** [angular/angular#33233]
# 🚀 feature request

### Relevant Package
Wherever the structural directives live

### Description
Template reference variables cannot be uniquely defined for elements within an *ngFor. For example, to my knowledge, the best we have now is:
```
<ng-container *ngFor="let user of users">
  <p #ref>{{user}}</p>
</ng-container>
```

Where 'ref' is applied to all ```<p>``` elements within the *ngFor.

### Describe the solution you'd like
I would like syntax to define a template reference variable dynamically. Something like:
```
<ng-container *ngFor="let user of users">
  <p #[{{user}}]>{{user}}</p>
</ng-container>
```

### Describe alternatives you've considered
The existing syntax can be used if ViewChildren and QueryList are also used to keep track of everything with that template reference variable. This allows for filtering, .forEach(), etc. See [this Stackblitz example](https://stackblitz.com/edit/angular-1bnq3q). But with a dynamically defined variable, workarounds like that would not be necessary.

**Comment by dannyskoog** [comment]
Interesting! How would you bind to such dynamic template variable from within a component? Spontaneously it seems hard due to the fact that the template variable’s resolved at runtime

**Comment by Airblader** [comment]
Who says users is an array without duplicates?

**Comment by jzabinski** [comment]
Good point: I think that it would also be helpful to have a method of binding to these via ViewChildren (for example), or maybe a new decorator. So maybe we could say something like:
```
[template]
<ng-container *ngFor="let user of users">
  <p #[{{user}}]>{{user}}</p>
</ng-container>
[class]
@ViewChildren({fromArray: users}) userElements: QueryList<HTMLParagraphElement>;
```

But the use case that I have in mind (and haven't mentioned yet) is the scenario where you need to send focus to a specific element that is being built by the *ngFor directive. In that case, the only technique which works that I know of is ```document.getElementById('somehardcodedstring').focus()```. And make sure that you set the 'id' attribute on one of the iterated elements to ```'somehardcodedstring'```. Rather brittle technique.

**Comment by Airblader** [comment]
There's plenty of ways to solve that, for example a directive with a boolean input that when it changes to true focuses the host. Or splitting into smaller components and using existing ViewChild mechanisms etc.

**Comment by jzabinski** [comment]
> Who says users is an array without duplicates?

Based on your question, I'm assuming that duplicates are bad. As it stands now, using a template reference variable on an element within an *ngFor creates many duplicate template references. The proposal would reduce the risk of that happening, although not eliminating it.
  A dynamically determined template reference variable doesn't necessarily need to depend on the array being used by the *ngFor at all. Maybe it could be something as simple as #[{{x++}}]. The point of the proposal is that template reference variables within loops need to be improved.

> What happens when the collection changes?

In terms of working with the elements via ViewChild/ViewChildren, programmers would need to be aware of that possibility and work with it. But it sounds like there may be problems if the variable changes on the template side.

**Comment by jzabinski** [comment]
> There's plenty of ways to solve that, for example a directive with a boolean input that when it changes to true focuses the host. Or splitting into smaller components and using existing ViewChild mechanisms etc.

Fair enough. But I'm having trouble imagining code that would be as clean as *ngFor, which could also use a unique directive in some cases. That's not to say that it doesn't exist, just that I'm not experienced enough with directives to fully understand you. Of course, abandoning *ngFor entirely would be an option, but it's a very convenient construct.

**Comment by Airblader** [comment]
No one is telling you not to use `*ngFor`. Here's an example of the directive that I mentioned: https://angular-4p6uws.stackblitz.io

**Comment by nickshoe** [comment]
This is a workaround for getting hold of a child component nativeElement based on some properties of the component itself:

```typescript
export class ParentComponent {
    @ViewChildren(ChildComponent)
    childrenComponents!: QueryList<ChildComponent>;

    ngAfterViewInit(): void {
        let childComponent = this.childrenComponents.find(childComponent => /* predicate on childComponent.model */);

        let childComponentNativeElement = childComponent.elRef.nativeElement;

        /* do stuff on nativeElement */
    }
}
```

```typescript
export class ChildComponent {
    @Input()
    public model: Model;

    constructor(
        public elRef: ElementRef
    )
}
```

**Comment by mcalmus** [comment]
I'm trying to do a popup within a loop and bind it to an HTML element immediately adjacent to the thing being popped so that tab order works in a reasonable way.

```<div *ngFor="let item of items; index as i">
  <a [popper]="popover" [popperTarget]="popoverTarget.nativeElement">click</a>
  <span #popoverTarget></span>
</div>```

This works, but without a unique name (I was planning to use the index) the popup is structurally at the bottom of the list of items. So, if you tab through, hit enter on the first item you have to tab through the others before links in the popup get focus.

**Comment by mcalmus** [comment]
I'm trying to do a popup within a loop and bind it to an HTML element immediately adjacent to the thing being popped so that tab order works in a reasonable way.

```
<div *ngFor="let item of items; index as i>
  <a [popper]="popover" [popperTarget]="popoverTarget.nativeElement">click</a>
  <span #popoverTarget></span>
</div>
```

This works, but without a unique name (I was planning to use the index) the popup is structurally at the bottom of the list of items. So, if you tab through, hit enter on the first item you have to tab through the others before links in the popup get focus.
