### ISSUE TITLE
Top Menu highlight wrong item after click on browser back button

### ISSUE THREAD

**Issue by animnook** [angular/angular#33239]
# 📚 angular.io bug
### Reproduction Steps**
1. Open angular.io page
2. Click on resources link on top
3. Click on docs link on top
4. Click on browser back button.
The docs link is highlighted while it should highlight resource link

### Expected vs Actual Behavior**
Browser back button does change the page back to the last page user on, and it should also the highlight item of current page. But it is not highlighting the correct menu item

**Comment by gkalpak** [comment]
That highlight is for the currently focused item. So the behavior is correct in the regard, but I see how it may seem like the highlighted item is the active page and confuse people.

@sjtrimble, any ideas on how we could make it more obvious that the highlighted element is the focused one (and not the active page) and/or also highlight the active page?

**Comment by sjtrimble** [comment]
Yeah, I have some ideas for how we can clean up the focus/hover/active styles.

**Comment by sjtrimble** [comment]
@gkalpak I'll need your help getting an active state working on the topnav. The styles are there but it's not using the standard `routerlinkactive` that I'm used to. Otherwise, take a look at the PR.
