### ISSUE TITLE
When multiple apps are in a page at a time the CSS conflict

### ISSUE THREAD

**Issue by TedSander** [angular/angular#3324]
In our environment we run multiple separate angular applications on the same page. The CSS emulation uses a static application counter to determine CSS class names. When multiple apps are on a page they conflict.

Most of this code is contained in: angular2/src/render/dom/shadow_dom/util.ts

Propose making _nextComponentUID feed by a variable in the page space instead of a value in the application.

**Comment by TedSander** [comment]
@naomiblack Can you triage this?

**Comment by TedSander** [comment]
b/22774631

**Comment by naomiblack** [comment]
this looks like a task for @tbosch -- Tobias, is there anyone besides you who might be able to get to this in alpha-34? I know you're already heavily loaded for the week.

**Comment by tbosch** [comment]
Ted, this counter is global, it is shared by all angular applications on
the same page.

Could you provide a demo link where I can debug this? Maybe just on the
buganizer issue if it is an internal app...

**Comment by TedSander** [comment]
Matt has some code where he can easily reproduce this. I'll have him sync with you. I'll also sync with you tomorrow on what we are seeing.

**Comment by tbosch** [comment]
Talked with Matt offline and found that the example app is using 2 Dart isolates.

**Comment by tbosch** [comment]
Talked to @mhevery and will add an `appId` that can be defined with a binding to the `bootstrap` call. Will do this while doing https://github.com/angular/angular/pull/3314. Will probably land tomorrow morning...

**Comment by tbosch** [comment]
Closed via #3314
