### ISSUE TITLE
ng add @angular/bazel fails with Property 'serve' does not exist in JSON object

### ISSUE THREAD

**Issue by lukasholzer** [angular/angular#33246]
# 🐞 bug report

### Affected Package 
The issue is caused by package @angular/bazel

### Is this a regression?

no

### Description

When I run in my monorepo library `ng add @angular/bazel` it will start installing packages and then it fails with the message `Property 'serve' does not exist in JSON object`

## 🔬 Minimal Reproduction

create an angular.json with a library that has no `architect.serve` target:

```json
...
"other-apps": {},
"lib": {
  "root": "",
  "sourceRoot": "src",
  "projectType": "library",
  "prefix": "dt",
  "architect": {
    "build": {
      "builder": "@angular-devkit/build-ng-packagr:build",
      "options": {
        "tsConfig": "src/lib/tsconfig.build.json",
        "project": "src/lib/ng-package.json"
      },
      "configurations": {
        "production": {
          "project": "src/lib/package.json"
        }
      }
    },
    "test": {
      "builder": "@nrwl/jest:jest",
      "options": {
        "jestConfig": "jest.config.js",
        "tsConfig": "src/lib/tsconfig.spec.json",
        "setupFile": "src/lib/test-setup.ts"
      }
    }
  }
},
...
```

Then Run: `ng add @angular/bazel`

## 🔥 Exception or Error
<pre><code>
Property 'serve' does not exist in JSON object
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.2
Node: 11.10.1
OS: darwin x64
Angular: 8.0.0
... animations, bazel, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic
... platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.2
@angular-devkit/build-angular      0.800.2
@angular-devkit/build-ng-packagr   0.800.2
@angular-devkit/build-optimizer    0.800.2
@angular-devkit/build-webpack      0.800.2
@angular-devkit/core               8.0.2
@angular-devkit/schematics         8.0.2
@angular/cdk                       8.1.1
@angular/cli                       8.0.2
@bazel/typescript                  0.38.3
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.2
@schematics/angular                8.0.2
@schematics/update                 0.800.2
ng-packagr                         5.3.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0

</code></pre>

## Expected Behaviour

ng-add schematics should check if the serve target is present and only then update it – in case of the library i want that this updates only the builder.

**Comment by RashmiChandran** [comment]
Any update on this issue?

**Comment by tibinthomas** [comment]
Same issue here for me too!

**Comment by tibinthomas** [comment]
Looks like we are missing "serve" config for defaultProject in angular.json

**Comment by AndrewKushnir** [comment]
Hi,

Bazel builder and schematics were deprecated several major versions ago, so I'm closing this ticket. You can find more information about this on the [Deprecated APIs and features page](https://angular.io/guide/deprecations#bazel-builder-and-schematics) and in the [migration guide](https://github.com/angular/angular/blob/master/packages/bazel/src/schematics/README.md).

Thank you.
