### ISSUE TITLE
Help or example, correct way to implement reactive forms nested with N levels, respecting routing with VCA

### ISSUE THREAD

**Issue by kasius** [angular/angular#33251]
hello
I hope to find someone who can help me with the following problems, thanks.
Hello, I am trying to implement a complex multi-level form with nested reagent forms using components and VCA and routing (each route is a nested component with VCA), when I have 2 levels there is no problem but when I have a component that in turn uses 2 other levels of nested components within the same parent form and I return to another route the form enters an infinite loop and throws me the typical maximun problem in a loop, the question is if anyone has ever done this, can you guide me or show some example where it is used
reactive forms, routing, nested forms by N levels, VCA and that can handle the state, validations and the entire form from the parent component, in the past I have worked with complex reactive forms using @Input and @oputput and the truth is that no I want to use this methodology, please appreciate help to implement complex N-level forms with VCA correctly, respecting the router

<img width="764" alt="Captura de Pantalla 2019-10-18 a la(s) 10 43 16" src="https://user-images.githubusercontent.com/4899368/67100428-0606ad00-f196-11e9-9e8c-5dc97b3c5a2b.png">

**Comment by dannyskoog** [comment]
Hi @kasius. I appreciate you reaching out. But StackOverflow is better suited for support questions like this.

**Comment by ajitsinghkaler** [comment]
@gkalpak @kapunahelewong I think we can close this.
