### ISSUE TITLE
update dgeni docs templates for harp 0.17

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#3325]
In harp 0.17, vars must be declared as `- var foo=bar`. Need to update https://github.com/angular/angular/blob/master/docs/angular.io-package/templates/module.template.html

and other templates possibly?

**Comment by naomiblack** [comment]
This change needs to go in when the one on angular.io (https://github.com/angular/angular.io/pull/176) goes in, otherwise we break our ability to publish API docs.

**Comment by petebacondarwin** [comment]
I have provided a PR for this.
