### ISSUE TITLE
Ivy - ASSERTION ERROR: Expecting LContainer

### ISSUE THREAD

**Issue by sod** [angular/angular#33272]
Angular Version: 9.0.0-next.12

I tried ivy with our app and hit an error. Sadly I can't share it and I couldn't boil it down to a reproduction :(. Posting it anyway as you can maybe make sense of it. Have the state stil locally if you need more details.

The debugger stops here:
![image](https://user-images.githubusercontent.com/905328/67149642-f37f9700-f2ad-11e9-8a77-3af5a7d3ed6a.png)

And this is a few layers up in the stack:
![image](https://user-images.githubusercontent.com/905328/67149663-30e42480-f2ae-11e9-85c2-9643faa3a370.png)

Ivy access index 53 in LView and expects there to be an LContainer (?) from, but gets a string.

The component was way more complex, but this is what I reduced it to:
```typescript
@Component({
    selector: 'media-pdp-above-the-fold',
    styleUrls: ['./media-pdp-above-the-fold-component.scss'],
    template: `
        <div>
            <div>
                <div>
                    <product-wishlist
                        [product]="{}"
                        [cssModifier]="['ry-pdp-wishlist--pdp-media']"
                    >
                    </product-wishlist>
                </div>
                <some-component></some-component>
                <div>
                </div>
            </div>
        </div>

        <modal #modalDelivery>
            {{ 'foo1' | trans }}
            <ng-container *ngTemplateOutlet="deliveryPrice"></ng-container>
            {{ 'foo2' | trans: {}:'countries' }}
            <ul>
                <li>
                    <span></span>
                </li>
                <li>
                    <span> </span>
                </li>
            </ul>
            <div>
                {{ 'foo3' | trans }}
            </div>

            <ul>
                <li>
                    {{ 'foo4' | trans }}
                    <span>{{ 199 | ryCurrency }}</span>
                </li>
            </ul>

            <p>{{ 'foo5' | trans }}</p>
            <p>{{ 'foo6' | trans }}</p>
        </modal>
        <ng-template #deliveryPrice></ng-template>
    `,
})
export class MediaPdpAboveTheFoldComponent {
    @Input() public productView: ProductViewResponse;

    constructor(public freeShipping: FreeShipping) {}
}
```

If I fiddle around with that template more, the error disappears or other errors appear. 

This is the contents of LView:
![image](https://user-images.githubusercontent.com/905328/67149709-d8f9ed80-f2ae-11e9-9418-beff41fc2b9d.png)
![image](https://user-images.githubusercontent.com/905328/67149719-ed3dea80-f2ae-11e9-9170-4fb4c4176663.png)

Any ideas?

**Comment by sod** [comment]
Ok found the issue. The `product-wishlist` component called `changeDetectorRef.detectChanges()` in `ngOnInit()` :D. ViewEngine seemed to silently accept it, ivy doesn't like that at all.

**Comment by JoostK** [comment]
@sod In that case, this PR may be related: https://github.com/angular/angular/pull/33235

**Comment by sod** [comment]
Ah nice, I'll try my reproduction again if the lands in master.
