### ISSUE TITLE
window events that are being listened to by a HostListener are not being handled by the EventManager

### ISSUE THREAD

**Issue by maximedupre** [angular/angular#33277]
# 🐞 bug report

### Description

`window` events that are being listened to by a `HostListener` are not being handled by the `EventManager`. This prevents us from running those events outside the angular zone.

## 🔬 Minimal Reproduction

As you can see in the repo, the `addEventListener` of the `CustomEventManager` is never called when listening to a window event with `@HostListener('window:dragover.outside-zone', ['$event'])`. If I remove the `window` prefix in the event name, everything works fine.

https://stackblitz.com/edit/angular-issue-repro2-gpd87k

## 🌍  Your Environment

**Angular Version:**
<pre><code>
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.12
Node: 12.11.0
OS: darwin x64
Angular: 8.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.12
@angular-devkit/build-angular     0.803.12
@angular-devkit/build-optimizer   0.803.12
@angular-devkit/build-webpack     0.803.12
@angular-devkit/core              8.3.12
@angular-devkit/schematics        8.3.12
@angular/cli                      8.3.12
@ngtools/webpack                  8.3.12
@schematics/angular               8.3.12
@schematics/update                0.803.12
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
    
</code></pre>

**Comment by trotyl** [comment]
It's expected, in your example only [`addEventListener()`](https://angular.io/api/platform-browser/EventManager#addeventlistener) method being override, but not [`addGlobalEventListener()`](https://angular.io/api/platform-browser/EventManager#addglobaleventlistener). The latter is used for global events.
