### ISSUE TITLE
Custom font not working properly

### ISSUE THREAD

**Issue by kanhaiyaarthonsys** [angular/angular#33270]
I create a font folder in assets and when i use this fonts in scss file and create build with base-href then in build the url is not showing properly 
base-url not adding in fonts URL

Angular Version  : 8

**Comment by dannyskoog** [comment]
Hi @kanhaiyaarthonsys. The info you’re providing is not enough to understand your issue.

Preferably post a link to a minimal reproduction using [Stackblitz](https://stackblitz.com)

**Comment by matsko** [comment]
Please create issues following our template. This way it's better for the team to help figure out exactly what's going on. Closing.
