### ISSUE TITLE
docs: document public_api_guard and Golden files

### ISSUE THREAD

**Issue by Splaktar** [angular/angular#33278]
# 📚 Docs or angular.io bug report

### Description
When any contributor submits a PR to the project, they may see build failures like the following

<details>
  <summary>CircleCI Test Failure</summary>

```ts
FAIL: //tools/public_api_guard:forms_api (see /home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/execroot/angular/bazel-out/k8-fastbuild/testlogs/tools/public_api_guard/forms_api/test_attempts/attempt_1.log)
FAIL: //tools/public_api_guard:forms_api (see /home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/execroot/angular/bazel-out/k8-fastbuild/testlogs/tools/public_api_guard/forms_api/test.log)

FAILED: //tools/public_api_guard:forms_api (Summary)
      /home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/execroot/angular/bazel-out/k8-fastbuild/testlogs/tools/public_api_guard/forms_api/test.log
      /home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/execroot/angular/bazel-out/k8-fastbuild/testlogs/tools/public_api_guard/forms_api/test_attempts/attempt_1.log
INFO: From Testing //tools/public_api_guard:forms_api:
==================== Test output for //tools/public_api_guard:forms_api:
--- tools/public_api_guard/forms/forms.d.ts	Golden file
+++ tools/public_api_guard/forms/forms.d.ts	Generated API
@@ -4,9 +4,9 @@
     readonly disabled: boolean;
     readonly enabled: boolean;
     readonly errors: ValidationErrors | null;
     readonly invalid: boolean;
-    readonly parent: FormGroup | FormArray;
+    readonly parent: FormGroup | FormArray | undefined;
     readonly pending: boolean;
     readonly pristine: boolean;
     readonly root: AbstractControl;
     readonly status: string;


Accept the new golden file:
  bazel run //tools/public_api_guard:forms_api.accept
================================================================================
==================== Test output for //tools/public_api_guard:forms_api:
--- tools/public_api_guard/forms/forms.d.ts	Golden file
+++ tools/public_api_guard/forms/forms.d.ts	Generated API
@@ -4,9 +4,9 @@
     readonly disabled: boolean;
     readonly enabled: boolean;
     readonly errors: ValidationErrors | null;
     readonly invalid: boolean;
-    readonly parent: FormGroup | FormArray;
+    readonly parent: FormGroup | FormArray | undefined;
     readonly pending: boolean;
     readonly pristine: boolean;
     readonly root: AbstractControl;
     readonly status: string;


Accept the new golden file:
  bazel run //tools/public_api_guard:forms_api.accept
================================================================================
```
</details>

The important output here is the following

```sh
Accept the new golden file:
  bazel run //tools/public_api_guard:forms_api.accept
```

#### Issues

- "Accept the new golden file"
  - These words have little to no meaning to new contributors
  - It is not clear that this is an instruction to the PR author
- `bazel run //tools/public_api_guard:forms_api.accept`
  - For contributors who have never used [Bazel](https://bazel.build/) before
    - It's not clear that this is a shell command
    - It's also not clear that `public_api_guard:forms_api.accept` is a script or a runnable target
- There is no explanation here (or link to) about what is wrong or why the PR author needs to take an action.
- There is no explanation here (or link to) on how to read the API diff and how to think about or make API changes. 

#### Mitigation
- `CONTRIBUTING.md` should mention and have some kind of link to the full description of this message, `public_api_guard`, and Golden files.
- `DEVELOPER.md` should mention and have some kind of link to the full description of this message, `public_api_guard`, and Golden files.
- `COMMITTER.md` or a new `.md` file may be the correct place to put the full description of this message, `public_api_guard`, and Golden files.
  - It would be nice to link to the [API deprecation policy](https://angular.io/guide/releases#deprecation-practices) in that explanation.
- Update the CircleCI output from `public_api_guard` to link to the full description.

### Expected vs Actual Behavior**
Expected to find some documentation describing this in one of these
- https://github.com/angular/angular/blob/master/CONTRIBUTING.md
- https://github.com/angular/angular/blob/master/docs/DEVELOPER.md
- https://github.com/angular/angular/blob/master/docs/COMMITTER.md
- https://github.com/angular/angular/blob/master/docs/CARETAKER.md
- https://github.com/angular/angular/blob/master/docs/PR_REVIEW.md
- https://github.com/angular/angular/blob/master/docs/TOOLS.md

but found nothing.

[PUBLIC_API.md](https://github.com/angular/angular/blob/master/docs/PUBLIC_API.md) starts to touch on some of the relevant concepts, but it doesn't cover anything from the contributor or PR author's perspective. 

### Browser info
N/A

### Anything else relevant?
Related issues
- https://github.com/angular/angular/issues/26589
- https://github.com/angular/angular/issues/28406

Full build job and failure that the above CircleCI output was sourced from: https://circleci.com/gh/angular/angular/457388

**Comment by dannyskoog** [comment]
Good initiative! Btw - do we also want to add (or link) such information to https://github.com/angular/angular/blob/master/docs/BAZEL.md?

Just popping the question since we have build and test instructions in that doc already.

**Comment by jbogarthyde** [comment]
@Splaktar Can you provide the specific information that needs to be added to some or any or all of these pages?
 I have always wondered how it worked -- and also who can do it. As a contractor, I don't seem to have the required access. I have always had to get someone else to update the golden file when needed.

**Comment by Splaktar** [comment]
@jbogarthyde you should just be able to run the `bazel` command that it gives you in the Circle CI error output in your local branch. Then you review the changes that it made to the APIs, and if it looks correct you commit the local changes and force push up your branch.

The tool that is used for this is called [ts-api-guardian](https://github.com/angular/angular/tree/master/tools/ts-api-guardian). But there aren't many docs at that link and the project wraps that behind a `bazel` command so that you don't need to directly interact with the ts-api-guardian library.

I've added most of the information that I have in the OP. I've managed to properly do this a couple times now, but I'm still learning as well.

That said, I think that just some guidance on defining what this thing is, how it helps verify that all API changes are explicitly recorded and reviewed, and what the commands and some of the vocabulary means would be greatly helpful for new contributors.

**Comment by jbogarthyde** [comment]
@Splaktar Please check out new PR

**Comment by Splaktar** [comment]
@jbogarthyde feedback left in PR. The script is not interactive, but we do need to tell people how to read the API diff output in Circle CI.

**Comment by Splaktar** [comment]
This is fixed in https://github.com/angular/angular/commit/a00f82797b28a19786ac692e61f35bc420a477bb. 

It's available here: https://github.com/angular/angular/blob/master/docs/PUBLIC_API.md#golden-files
