### ISSUE TITLE
Deprecated Example of Angular with Axios

### ISSUE THREAD

**Issue by maschinedreams** [angular/angular#33271]
# 📚 Docs or angular.io bug report

### Description

Angular with axios example, is deprecated and the hierarchy of the classes is wrong.

## 🔬 Minimal Reproduction
Just try to "imitate" the code
TS will start complaining
You will see its better to use observables and services than this example

### What's the affected URL?**
https://stackblitz.com/edit/angular-with-axios?
### Reproduction Steps**
I tried to make equal to the code as the example, but it doesnt run.

### Expected vs Actual Behavior**
Typescript keeped complaining about the types, I added the class and all the stuff about onInit, but this example doesnt work.
I tried to fetch data from an Cryptocurrency API, which is the current project I was working on.

``
import {Component, OnInit} from '@angular/core';
export class AppComponent implements OnInit {

constructor(peopleService: PeopleService) {}

ngOnInit() {
this.getList();
}

getList() {
this.people = peopleService.getPeople();
}
}
``

working example on top

## 📷Screenshot
![erro](https://user-images.githubusercontent.com/39539531/67148074-7df5d580-f271-11e9-8026-ae0db20a7bc4.PNG)
![erros](https://user-images.githubusercontent.com/39539531/67148078-83532000-f271-11e9-9c0a-ecafac5739f9.PNG)
![imports](https://user-images.githubusercontent.com/39539531/67148081-8d751e80-f271-11e9-9962-b520fd6f469e.PNG)

## 🔥 Exception or Error
<pre>
[ts] cannot find OnInit
<code>
</code>
</pre>

## 🌍  Your Environment
Windows 10, VS Code, NodeJS, Angular 7+

**Comment by dannyskoog** [comment]
At least a few of your compilation errors are due to incorrect formatting. So start with this:

1. Move the curly brace (`}`) on line `22` to line `29`
2. Move the code you have on line `25` to line `27`

**Comment by gkalpak** [comment]
This example is not maintained by ther Angular team, so we can't update it. If you need help setting up axios with Angular, I suggest you ask on one of our general support channels (e.g. [StackOverflow](http://stackoverflow.com/) using tag `angular` or [Gitter](https://gitter.im/angular/angular)).
