### ISSUE TITLE
Prevent router-outlet default property

### ISSUE THREAD

**Issue by allahyar** [angular/angular#33287]
I Want to enable/disable router-outlet dynamically. When router-outlet was disabled then, tab-outlet handle routing. This is interesting for me that when isActivate false then tab-outlet work fine! But when isActivate true by default and disable manually (click by button) It Dosn't work.

```
@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AppComponent {

  isActivate = true;

  constructor(private cd: ChangeDetectorRef) {
  }

  onDeactive() {
    this.isActivate = false;
    setTimeout(() => {
      this.cd.detectChanges();
    });
  }
}
```

```
<app-tab-outlet></app-tab-outlet>
 <router-outlet *ngIf="isActivate"></router-outlet>
<button type="button" (click)="onToggle()">Show RouterOutlet</button>
```

See in [Stackbilitz](https://stackblitz.com/edit/angular-fp15ov?file=src%2Fapp%2Fapp.component.ts)

**Comment by allahyar** [comment]
I didn't find any solution, I think this is a bug :(

**Comment by allahyar** [comment]
@tinyMan can you help me ?

**Comment by MrJithil** [comment]
@allahyar, you can not disable it just adding the if condition. If you add that, the complete router-outlet will be hide or show based on the condition.

If you need a dynamic routing, you can either add the logic in  the `<a>` tag of your provided sample. Or you need to hook the `(activate)` event of the `router-outlet`.

**Comment by manklu** [comment]
Both outlets have the same name and override the registration of each other (last registration wins). You should ensure that only one outlet is active at a time.

**Comment by ajitsinghkaler** [comment]
@gkalpak @kapunahelewong I think we can close this.
