### ISSUE TITLE
Adding a friendly Url in Dynamic Views of Angular8 to use SEO

### ISSUE THREAD

**Issue by LeonelTasso** [angular/angular#33280]
i'm using Angular routing to switch between views.

My version of Angular is `"@angular/core": "~8.0.0"`

This is how it's done today:

`www.mywebsite.com.br`

When i chose some view, i load a data from the server to show the info, and the URL look's like this:

`www.mywebsite.com.br/course/1`

But, to use SEO in my website i need to show the tittle of the course in the URL, like this:

`www.mywebsite.com.br/how-to-use-a-computer`

And when i navigate inside this course i need to create the path, like this:

`www.mywebsite.com.br/how-to-use-a-computer/my-first-class`
This, my routes:

```
const routes = [

  {path: 'manufacturer/:id_ manufacturer', component: ManufacturerComponent},

  {path: 'course/:id_course', component: CourseComponent},

  {path: 'category/:id_ category', component: CategoryComponent},

  {path: 'course/:id_course/class/:id_ class', component: ClassComponent},
];
```
There is anyway to change the URL?

**Comment by dannyskoog** [comment]
Hi @LeonelTasso. This is more of a support question and is better suited to post on Stackoverflow. Thanks

**Comment by LeonelTasso** [comment]
Hi @dannyskoog, i already asked there, but i didnt have any answer

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
