### ISSUE TITLE
No way to prevent angular-cli from removing license info from minified JS

### ISSUE THREAD

**Issue by DanKing123** [angular/angular#33288]
I _believe_ this is a bug, although it's also possible that I've misunderstood the intended current behaviour and that this is in fact a feature request.

According to @IgorMinar in [this comment](https://github.com/angular/angular/issues/33056#issuecomment-540821307):
> It is customary to preserve licensing information in application bundles in the form of js comments marked with @license js doc and that's what Angular CLI does. We currently don't offer a way to omit the inclusion of these headers in the application bundles.

This is _not_ the behaviour I am observing however. When I run `ng build --prod` using Angular CLI version 8.3.6, _all_ third party license info is _removed_ from the resulting minified JavaScript bundles and placed in `3rdpartylicenses.txt`.

If I run the same command with `--extractLicenses=false`, the license info is _still_ removed, but `3rdpartylicenses.txt` is not created.

There doesn't seem to be any way to _prevent_ Angular CLI from removing this license information from the JS that I am going to be serving in my application.

**Comment by trotyl** [comment]
This isn’t an Angular issue, please report to [Angular CLI](https://github.com/angular/angular-cli/issues) if you believe there is something wrong with the bundling process.

**Comment by DanKing123** [comment]
Apologies - my mistake - I have done that now: https://github.com/angular/angular-cli/issues/15890
