### ISSUE TITLE
ngcc: runtime error with `ng6-breadcrumbs`

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#33297]
In [ng6-breadcrumbs][1], the entry-point for `package.json > main` (which is detected by `ngcc` as CommonJS format) has indeed most files in CommonJS format (e.g. [lib/breadcrumbs.module.js][2]), but the entry-point file is in ESM5 format ([ng6-breadcrumbs.js][3]).

`ngcc` compiles the entry-point correctly (possibly as a result of `CommonJsReflectionHost` extending `Ems5ReflectionHost`?), but fails to detect that `BreadcrumbsComponent` is exported as part of the `export * from './lib/breadcumbs.component'` export and adds a re-export for the `BreadcrumbsComponent`. Since `ngcc` considers this file to be in CommonJS format (as the whole entry-point), the export it adds looks like `exports.BreadcrumbsComponent = ...`.

The resulting file uses both ES module exports (`export * ...`) and CommonJS exports (`exports.Foo = ...`). As a result, webpack cannot bundle it correctly, treating it as an ES module and resulting in a runtime error: `exports is not defined`.

Open questions:
- [ ] Do we want to support that in `ngcc`?
    _As discussed, we probably don't want to support this._
- [ ] A quick-ish work-around (that would work in some cases, but not all) would be to change `ngcc` so that the `CommonJsReflectionHost` can recognize exports in ESM5 format. (So, in this case, it wouldn't re-add the `BredcrumbComponent` export?) <-- Needs to be verified.
- [ ] Is this a common pattern or is it just this one package?

[1]: https://www.npmjs.com/package/ng6-breadcrumbs
[2]: https://cdn.jsdelivr.net/npm/ng6-breadcrumbs@1.0.7/lib/breadcrumbs.module.js
[3]: https://cdn.jsdelivr.net/npm/ng6-breadcrumbs@1.0.7/ng6-breadcrumbs.js

**Comment by alxhub** [comment]
Let's not track individual packages here in our issue tracker (unless they're filed by the community).
