### ISSUE TITLE
BUG: IVY ViewChild does not work when defined in base class

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#33292]
# 🐞 bug report

### Affected Package
`@angular/core`

### Is this a regression?

Definitely yes, it is working without IVY.

### Description

When you define `ViewChild` (probably same with `ViewChildren`, maybe even with `ContentChild`) in parent *base* class, this property will never be set by Angular.

## 🔬 Minimal Reproduction

> `git clone https://github.com/kukjevov/ng-universal-demo.git`
> `cd ng-universal-demo`
> `git checkout ivy-error`
> `npm install`
> `npm start`
> open browser on `http://localhost:8888/garden`
> you should see undefined in console instead of requested instance of component

## 🔥 Exception or Error

No error just missing value of property with `ViewChild`

## 🌍  Your Environment

**Angular Version:**
Angular 9-next.12

**Anything else relevant?**
Windows: 10.0.17763
Node: 11.6.0
NPM: 6.9.0

**Comment by dannyskoog** [comment]
Do you have decorator (e.g. `@Directive()`) on the base class?

**Comment by kukjevov** [comment]
No i dont have `Directive` decorator since it is not directive, but i have `Injectable` decorator. You might take a look at the repo :).

**Comment by alexzuza** [comment]
Related https://github.com/angular/angular/issues/30080#issuecomment-540758324

**Comment by dannyskoog** [comment]
@kukjevov the reason why I brought up `@Directive` is due to this https://next.angular.io/guide/migration-undecorated-classes

**Comment by kukjevov** [comment]
Oh thx @dannyskoog i tried it and it is working :). But still if it is final state, this is *breaking change* that should be mentioned, but as workaround it is working :).

**Comment by alxhub** [comment]
@kukjevov glad to hear it's working for you. There are a set of code migrations for Ivy which are required - you can see that in the `next.angular.io` link posted above. The CLI applies these migrations automatically when updating to v9.
