### ISSUE TITLE
ReferenceError: Response is not defined in IE 11

### ISSUE THREAD

**Issue by rockeshub** [angular/angular#33295]
# 🐞 bug report

### Affected Package
I am suspecting it is a polyfill or Zone.js issue.

### Is this a regression?
No

### Description

Recently we migrated to Angular 8 from Angular 5.

## 🔬 Minimal Reproduction
This happens whenever there is an API call to the backend. It says Response is not defined.
I am creating a minimal project where I can reproduce this issue. once it is done, I will update here.
meanwhile, if anyone knows the fix. please help. Stuck with this and it is blocking the release

## 🔥 Exception or Error
<pre><code>
@ngrx/store: runtime checks are currently opt-in but will be the default in the next major version with the possibility to opt-out, see https://ngrx.io/guide/migration/v8 for more information.
Initial App State [object Object]
   "Initial App State"
   {
      [functions]: ,
      __proto__: { },
      Symbol(INITIAL_VALUE)_f.xmt0dn316re: undefined,
      Symbol(rxSubscriber)_e.xmt0dn316re: undefined
   }
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
'Response' is undefined ReferenceError: 'Response' is undefined
   "'Response' is undefined"
   {
      [functions]: ,
      __proto__: { },
      description: "'Response' is undefined",
      message: "'Response' is undefined",
      name: "ReferenceError",
      number: -2146823279,
      stack: "ReferenceError: 'Response' is undefined
   at Anonymous function (https://cedar-qa01.internal.synopsys.com/main-es5.js:1664:22)
   at TapSubscriber.prototype._next (https://cedar-qa01.internal.synopsys.com/vendor-es5.js:177026:5)
   at Subscriber.prototype.next (https://cedar-qa01.internal.synopsys.com/vendor-es5.js:168340:5)
   at onLoad (https://cedar-qa01.internal.synopsys.com/vendor-es5.js:18210:21)
   at ZoneDelegate.prototype.invokeTask (https://cedar-qa01.internal.synopsys.com/polyfills-es5.js:8611:13)
   at onInvokeTask (https://cedar-qa01.internal.synopsys.com/vendor-es5.js:43369:17)
   at ZoneDelegate.prototype.invokeTask (https://cedar-qa01.internal.synopsys.com/polyfills-es5.js:8611:13)
   at Zone.prototype.runTask (https://cedar-qa01.internal.synopsys.com/polyfills-es5.js:8384:21)
   at ZoneTask.invokeTask (https://cedar-qa01.internal.synopsys.com/polyfills-es5.js:8687:17)
   at invokeTask (https://cedar-qa01.internal.synopsys.com/polyfills-es5.js:9882:9)
   at globalZoneAwareCallback (https://ce",
      Symbol(INITIAL_VALUE)_f.xmt0dn316re: undefined,
      Symbol(rxSubscriber)_e.xmt0dn316re: undefined
   }

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.6
Node: 10.16.3
OS: darwin x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.6
@angular-devkit/core         8.3.6
@angular-devkit/schematics   8.3.6
@schematics/angular          8.3.6
@schematics/update           0.803.6
rxjs                         6.4.0

</code></pre>

**Anything else relevant?**
Not Working IE 11

**Comment by rockeshub** [comment]
@PatrickJS  can you help me here. thanks in advance.

**Comment by pkaufi** [comment]
It's hard to tell from the information you provided, but I see you're running it in development mode. I'm not sure if you're running it like written in this post: https://github.com/angular/angular-cli/issues/14455#issuecomment-493739768

**Comment by rockeshub** [comment]
@pkaufi I have used the solution given. Even after running it in prod mode we are facing this issue.

**Comment by rockeshub** [comment]
I found the issue 
we were using a HttpInterceptor and we were checking the type of response
something like this  
if (response instanceof Response && response.url.includes('link_error.jsp')

I fixed it by changing it to 
if (response instanceof HttpResponse && response.url.includes('link_error.jsp')
