### ISSUE TITLE
does deep copy is needed to reference an array from service in component?

### ISSUE THREAD

**Issue by pratheshb** [angular/angular#33293]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: 
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by pratheshb** [comment]
had an array in service.

> let srvcArr= ['elm1'];

in component

> this.comArr = this.service.srvcArr;
> this.comArr.push('elm2');

this will change srvcArr in the service. 
we can prevent this by deep copying.
Is there any other way to prevent this?

**Comment by logicalravii** [comment]
@pratheshb i think its the only way, and i don't think anything wrong with that.

**Comment by dannyskoog** [comment]
Shallow copying is enough:
`this.comArr = [...this.service.srvcArr, ’elm2’];`

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Thank you.
