### ISSUE TITLE
[Ivy] `HostListener` decorated methods are handled multiple times on inheriting (child) components

### ISSUE THREAD

**Issue by ViktorSlavov** [angular/angular#33300]
# 🐞 bug report

### Affected Package
Seems it's caused by `@angular/core`.

### Is this a regression?
Version 8.x **without** Ivy works fine.
With Ivy enabled, fails on both 8.x and 9.x.

### Description
In a project using Angular 9, `HostListener` and `HostBinding` decorators are handled multiple times on child and grandchild components.

## 🔬 Minimal Reproduction
Here's a link to a repo with the reproduction:
[https://github.com/ViktorSlavov/angular-inheritance-repo](https://github.com/ViktorSlavov/angular-inheritance-repo)

Steps to reproduce:
 1. Run the app and open the console.
 2. Click on one of the components labeled `Child` - one entry is logged
 7. Click on one of the components labeled `Grand Child` - two entries are logged

## 🔥 Exception or Error
None
The `grand-child` component's handler is executed twice.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.12
Node: 10.15.2
OS: win32 x64
Angular: 9.0.0-next.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.12
@angular-devkit/build-angular     0.803.12
@angular-devkit/build-optimizer   0.803.12
@angular-devkit/build-webpack     0.803.12
@angular-devkit/core              8.3.12
@angular-devkit/schematics        8.3.12
@angular/cli                      8.3.12
@ngtools/webpack                  8.3.12
@schematics/angular               8.3.12
@schematics/update                0.803.12
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.39.2

</code></pre>

**Additional Info**
In the repro repo, if you remove the `HostBinding`s in `(Grand)ChildComponent`, the handler is executed only once.

**Comment by AndrewKushnir** [comment]
Hi @ViktorSlavov, thanks for reporting the issue and providing detailed instructions on how to reproduce it.

I've created a [PR with proposed fix](https://github.com/angular/angular/pull/34244). PR still requires review and the final implementation might change, but I'd like to ask if you could test your app with the changes from that PR to make sure the fix covers the case that you have in the app and everything works as expected. You can follow an instruction in [this document on how to use PR artifacts](https://github.com/angular/angular/blob/master/docs/DEVELOPER.md#archives-for-each-package). An archive with updated `@angular/core` package is available [here](https://555273-24195339-gh.circle-artifacts.com/0/angular/core-pr34244-abae3b4da3.tgz) (please make sure you updated other `@angular` packages to `9.0.0-rc.5` to avoid version conflicts).

Thank you.

**Comment by ViktorSlavov** [comment]
Hi @AndrewKushnir , thank you for the reply and the detailed instructions!

I updated my repo with the artifact from your PR (along w/ the other packages to rc-5) and can confirm that your PR resolves the issue - the event handler on the `Grandchild` component fires only once.

I'll keep an eye on this issue and future releases so I can see once the fix has made its way into the package.

Thanks again for addressing this so quickly!

**Comment by AndrewKushnir** [comment]
Hi @ViktorSlavov, thanks for testing the app with the changes from the PR. I will keep this thread updated once PR is reviewed and merged. Thank you.

**Comment by AndrewKushnir** [comment]
Hi @ViktorSlavov, the fix was included into the `9.0.0-rc.8` version of the framework that is now available on NPM. Could you please try to test your application with the mentioned version and let us know if the app works as expected now? Thank you.

**Comment by ViktorSlavov** [comment]
Hi @AndrewKushnir, thanks for the update!

I ran `ng update @angular/core@next` on the test repo and now everything seems to be working fine! ([repo branch w/ rc.8](https://github.com/ViktorSlavov/angular-inheritance-repo/tree/update-to-rc8))
You can close this issue.

Thanks again for staying on top of this!

**Comment by AndrewKushnir** [comment]
Thanks for the update @ViktorSlavov.
