### ISSUE TITLE
angular *ngFor not re-render html table with input

### ISSUE THREAD

**Issue by ikishanoza** [angular/angular#33316]
I have weird issues with `*ngFor` that describe here 
https://stackoverflow.com/questions/58498055/angular-ngfor-not-re-render-html-table-with-input

any help suggestion ?

**Comment by pkozlowski-opensource** [comment]
It is a support question that got answered on SO already

**Comment by ikishanoza** [comment]
If you check the comments its not resolved 

Please I don’t understand why its not working

**Comment by mlc-mlapis** [comment]
@ikishanoza First of all, create always Stackblitz reproduction simple working demo. The key for understanding is the fact, how and when the elements are kept/created/removed in DOM. The purpose of `trackby`  is to get `unique identifications of elements`. Angular is using them to check if the element should be kept, created or removed. In your case, the elements are always removed and then recreated, and that why the content is always lost.
