### ISSUE TITLE
Spell check broken in textarea using Edge

### ISSUE THREAD

**Issue by Steven-Harris** [angular/angular#33325]
# 🐞 bug report

### Affected Package
@angular/forms (*guessing*)

### Description
This one is a little tricky but I have done a lot of troubleshooting and I think I have some clues. Feel free to skip to the stackblitz. Spell check breaks inside of a textarea when the following conditions are met 
1. Using Edge
2. Using reactive forms (*template-driven form seems to work*)
3. page contains a contains a <option> tag, 
4. the value of the textarea is either on the page somewhere or in the DOM. 

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-dpetcz
*note: In our prod application, we don't have a pre tag showing the value of the form but it was the only easy way I could reproduce*
## 🔥 Exception or Error
Red underline never shows under misspelled words

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.1.2
Node: 12.2.0
OS: win32 x64
Angular: 8.2.0
... animations, common, compiler, core, elements, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.9
@angular-devkit/build-angular      0.801.3
@angular-devkit/build-ng-packagr   0.801.3
@angular-devkit/build-optimizer    0.801.3
@angular-devkit/build-webpack      0.13.9
@angular-devkit/core               8.1.3
@angular-devkit/schematics         8.1.3
@angular/cdk                       8.1.2
@angular/cli                       8.1.2
@angular/compiler-cli              8.1.3
@angular/material                  8.1.2
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.1.3
@schematics/angular                8.1.2
@schematics/update                 0.801.2
ng-packagr                         5.3.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.35.2
</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment]
Hi @Steven-Harris, thanks for reporting the problem and providing a repro. It looks like this problem might be outside of Angular, but you also mentioned that when you use Template-driven forms you don't see the issue. Could you please provide a small repro (using [Stackblitz](https://stackblitz.com/)) with Template-driven forms, so we can compare the implementations? I'm also curious if you tried to repro this issue without Angular (with plain HTML/JS)? Thank you.
