### ISSUE TITLE
Dynamically loaded select input options "broken" in Safari

### ISSUE THREAD

**Issue by tuuling** [angular/angular#33343]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

 Not sure

### Description

 Dynamically loaded select options behave different in Chrome and Safari. Not sure if bug in Chrome, Safari or Angular. 

## 🔬 Minimal Reproduction

  
[https://stackblitz.com/edit/angular-bpdhia?embed=1&file=src/app/app.module.ts](https://stackblitz.com/edit/angular-bpdhia?embed=1&file=src/app/app.module.ts)

## 🔥 Exception or Error
In Chrome the select box remains empty after values are loaded from an Observable.
In Safari the first value seems to be selected by default, but the model is still empty. Selecting the same value from the dropdown has no effect. Selecting another value from the dropdown finally has an effect and the model changes.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.6
Node: 12.12.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.6
@angular-devkit/core         8.3.6
@angular-devkit/schematics   8.3.6
@schematics/angular          8.3.6
@schematics/update           0.803.6
rxjs                         6.4.0

</code></pre>

OS: macOS Catalina

**Anything else relevant
Browsers are:
Chrome: Version 77
Safari: Version 13.0.2

**Comment by tuuling** [comment]
The easiest fix was to set the value of the model when getting the list of options in the component.

**Comment by AndrewKushnir** [comment]
Hi @tuuling, this issue seems to be related to the one described in #23784. You can subscribe to that thread to get further updates. Thank you.
