### ISSUE TITLE
Adding emojis to formcontrol breaks pattern validation in IE11

### ISSUE THREAD

**Issue by drandell** [angular/angular#33359]
# 🐞 bug report

### Affected Package
The issue is caused by package '@angular/forms'

### Is this a regression?
No

### Description
Currently trying to stop users adding bad values to my form control input, to allow only;
a-z A-z 0-9 and spaces.

Adding emojis to my form control via the windows 10 emoji keyboard and then moving away from that keyboard window seems to completely break the form control in IE11. 

No new valueChange events fire off on that form control field. The value of my input never changes. Example picture below; 

![image](https://user-images.githubusercontent.com/393945/67416923-a2c6b180-f5bf-11e9-9db4-567d8ad43069.png)

![image](https://user-images.githubusercontent.com/393945/67416956-b245fa80-f5bf-11e9-9d8b-8da3407d7541.png)

(And then completely deleting the field, you can see my inital value of 'dan' hasnt change since after adding the emojis):

![image](https://user-images.githubusercontent.com/393945/67417032-d43f7d00-f5bf-11e9-9af7-52b1f9b34b59.png)

In Chrome & Edge, the emojis are not even adding to the form control field. 

## 🔬 Minimal Reproduction

 
Clone repository; https://github.com/drandell/angular_bug 

In IE11, on the form control "name". 
Press Windows Key & ";" to open the emoji window.
Add some emojis, and click off the emoji window (not the form control field), to make it disappear. 
Once it is gone, go back to the form control field and add in any forbidden characters (symbols, more emojis etc.)

## 🔥 Exception or Error
No exception or error 
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.13
Node: 11.1.0
OS: win32 x64
Angular: 8.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.13
@angular-devkit/build-angular     0.803.13
@angular-devkit/build-optimizer   0.803.13
@angular-devkit/build-webpack     0.803.13
@angular-devkit/core              8.3.13
@angular-devkit/schematics        8.3.13
@angular/cli                      8.3.13
@ngtools/webpack                  8.3.13
@schematics/angular               8.3.13
@schematics/update                0.803.13
rxjs                              6.5.3
typescript                        3.4.5
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

Only occurs in IE 11

**Comment by drandell** [comment]
Updated repo to use latest angular 9 deps. 
Bug still exists in IE11. 
Although now, you have to move completely away from the formcontrol (via tab for example) and then go back to it to reproduce.

**Comment by drandell** [comment]
Updated repo to use latest angular 9.1 deps.
Bug still exists in IE11.

**Comment by AndrewKushnir** [comment]
Hi @drandell, thanks for reporting the issue.

It looks like the problem is outside of Angular and is related to the IE11 and how RegExps handle emojis. Could you please try to re-create the same logic (i.e. create an input, add event listener, run RegExp inside it and log the result) in plain JS/HTML (without Angular) using [Stackblitz](https://stackblitz.com/) and see if the behavior is the same?

Thank you.

**Comment by ahuss96** [comment]
Hi @AndrewKushnir, I work with @drandell. We were unable to replicate the issue using plain JS/HTML. Stackblitz along with alternatives do not support IE11 anymore, but we were able to use [W3Schools editor](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_default). You will have to copy and paste the following code to test for yourself.

`<!DOCTYPE html>
<html>
  <head>
    <title>Regex</title>
    <meta charset="UTF-8" />
  </head>

  <body>
    <form>
      <label>Name</label>
      <input type="text" id="name-input"/>
    </form>

    <script>
      var invalid = new RegExp(/([^A-Za-z0-9 ]|^ )/g);

      // on keyup
      document.getElementById("name-input").addEventListener("keyup", function(e) {
        var response = invalid.test(e.target.value) ? "invalid" : "valid";
        console.log("keyup:", response);
        e.target.value = e.target.value.replace(invalid, "");
      });

      // on blur
      document.getElementById("name-input").addEventListener("blur", function(e) {
        var response = invalid.test(e.target.value) ? "invalid" : "valid";
        console.log("blur:", response);
        e.target.value = e.target.value.replace(invalid, "");
      });
	</script>
  </body>
</html>`

**Comment by dylhunn** [comment]
IE11 support is removed from the next major version of Angular.
