### ISSUE TITLE
SyntaxHighlighter语法高亮 在 angular8.2版本中需要刷新页面才会起作用如何解决，

### ISSUE THREAD

**Issue by jiawenguang** [angular/angular#33368]
SyntaxHighlighter语法高亮 在 angular8.2版本中需要刷新页面才会起作用如何解决，

**Comment by AndrewKushnir** [comment]
Thanks for creating a ticket. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
