### ISSUE TITLE
getModuleFactory fails to find loaded module in production

### ISSUE THREAD

**Issue by rskendzic** [angular/angular#33369]
# 🐞 bug report 

### Affected Package

"@angular/core": "^8.2.4",

### Is this a regression?

I am not aware if this worked earlier. 

### Description

 A clear and concise description of the problem...
[getModuleFactory](https://angular.io/api/core/getModuleFactory#getmodulefactory) is working properly when serving application locally. When I build an application and try to serve it. Same piece of code is not working the same way. 

## 🔬 Minimal Reproduction
Reproduction can happen only with built project for production. 

```
@NgModule({
  imports: [CommonModule, RouterModule.forChild(routes), SharedModule],
  providers: [ContextAdminGuard],
  declarations: [LayoutComponent],
  id: 'ContextAdminModule'
})
export class ContextAdminModule {
}
```
This piece of code will return `true` when using ng serve. 
The same piece of code will return `false` when serving application built with `ng build --prod`
```
try {
      getModuleFactory('ContextAdminModule');
      return true;
    } catch (e) {
      return false;
    }
```
## 🔥 Exception or Error
No Errors

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.3
Node: 10.12.0
OS: darwin x64
Angular: 8.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.3
@angular-devkit/build-angular      0.803.4
@angular-devkit/build-ng-packagr   0.803.4
@angular-devkit/build-optimizer    0.803.4
@angular-devkit/build-webpack      0.803.4
@angular-devkit/core               7.1.4
@angular-devkit/schematics         7.1.4
@angular/cdk                       8.1.4
@angular/cli                       8.3.3
@angular/flex-layout               8.0.0-beta.27
@angular/material                  8.1.4
@angular/material-moment-adapter   8.1.4
@angular/pwa                       0.11.4
@ngtools/webpack                   8.3.4
@schematics/angular                7.1.4
@schematics/update                 0.803.3
ng-packagr                         5.5.1
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2

</code></pre>

**Anything else relevant?**
Using nwrl monorepo, but I don't believe it's the root of the problem.

**Comment by montella1507** [comment]
Similar issue here...  Module is built using "lazyModules" in angular.json but it is not found in production.

**Comment by mlc-mlapis** [comment]
`Returns the NgModuleFactory with the given id, if it exists and **has been loaded**. Factories for modules that do not specify an id cannot be retrieved. Throws if the module cannot be found.`

**Comment by rskendzic** [comment]
> `Returns the NgModuleFactory with the given id, if it exists and` **has been loaded**`. Factories for modules that do not specify an id cannot be retrieved. Throws if the module cannot be found.`

Yes. The same code is loaded during `ng serve` and after building. Same modules are loaded during `ng serve` and when you serve built version.  The module is loaded, but it returns false. Like it lost `id` or smth.

**Comment by mlc-mlapis** [comment]
@rskendzic Are you able to reproduce that behavior without Nx monorepo and publish a simple repo?

**Comment by mhevery** [comment]
Needs repro

**Comment by rskendzic** [comment]
@mlc-mlapis @mhevery Managed to reproduce.
Here is the [repo](https://github.com/rskendzic/get-module-factory)
If you start with `ng serve`
```
layout works!

Context Admin module is loaded
```

If you build project with the command `ng build --aot --prod`, go into dist, and serve the application (with lite-server for example)

```
layout works!

Context Admin module is not loaded
```

**Comment by JoostK** [comment]
I tried the reproduction using Angular 12 and this is now working correctly.
