### ISSUE TITLE
chore(ci): add check for git message formatting

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#3337]
We should have a script that runs on Travis to enforce git commit message guidelines, to prevent accidental merging of commits with messages that don't conform to requirements established [here](https://docs.google.com/document/u/1/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/mobilebasic)

Yes, this would be a slight inconvenience for "WIP" PRs, but worth the assurance of preventing pushes to master while forgetting to check a commit message, and needing to force-push to fix.

**Comment by mhevery** [comment]
I think we already have one here: https://github.com/angular/angular.js/blob/master/validate-commit-msg.js

**Comment by vvo** [comment]
I think you can have multiple checks so that you see that tests passes for ongoing PRs

> I think we already have one here: https://github.com/angular/angular.js/blob/master/validate-commit-msg.js

Yep just need to run it in another CI check
