### ISSUE TITLE
Platform Only Method Decorators. 

### ISSUE THREAD

**Issue by karocksjoelee** [angular/angular#33371]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/common

### Description
 A clear and concise description of the problem or missing capability...
Current Angular have provide isPlatfromBrowser checking platform id . But it becomes a lot of 
if (isPlatformBrowser(PLATFORM_ID) { ... } statement in code if developer is adapting Angular Universal ( Server Side Rendering ) . 

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
How about some decorators we could use to decorate methods in Services and Components ?  
`@BrowserOnly
checkLocalStorage() { ... }

@ServerOnly
doSomething() { ... } 
`

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by CaerusKaru** [comment]
This is not the recommended approach, at least from the perspective of the Universal team. Instead, it's suggested that you create separate server and browser implementations of your classes, and override them in your modules as necessary. This insures a common base interface that can remain solely about business logic, where platform modifications are made as needed.

As it is, I don't think this is something the team will likely support in the future (speaking for myself, not the team here).

**Comment by CaerusKaru** [comment]
Closing as not something the team will take on. If you find a complete necessity on this, you're welcome to implement and open source your own implementations.
