### ISSUE TITLE
TemplateRef passed into other component not checked under Ivy

### ISSUE THREAD

**Issue by vthinkxie** [angular/angular#33393]
🐞 bug report

### Affected Package

angular 9 with ivy

### Is this a regression?
yes

### Description
I check the Ivy Minor Change docs here

https://docs.google.com/document/d/1Dije0AsJ0PxL3NaeNPxpYDeapj30b_QC0xfeIvIIzgg/preview

and found that

>If a template is declared in one view but inserted into a different view, change detection will occur for that template only when its insertion point is checked (previously, change detection would also run when its declaration point was checked). 

It will bring lots of break changes to our UI library when upgrading it to angular 9 with ivy, because of many components' input support both `string` and `TemplateRef<any>` type, and all components are working under **OnPush** mode.

When the user passes a TemplateRef with a variable to the component, the template inside the component won't update any longer even if the variable has changed outside the component, which is a very common situation.

For example

the select API here: https://ng.ant.design/components/select/en#api

Property | Description | Type | Default
-- | -- | -- | --
[nzNotFoundContent] | Specify content to show when no result matches.. | string \| `TemplateRef<void>` | 'Not Found'

The feature comes from a directive here: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/core/addon/string_template_outlet.ts#L24 which brought a lot of convenience to the user.

I wonder if it is possible to keep the same as the previous version of the template check behavior

Thanks a lot

## 🔬 Minimal Reproduction
it works with angular 8 in the stackblitz, but not work under 9.0.0-next

https://stackblitz.com/edit/angular-99qln5?file=src/app/hello.component.ts

I could not enable ivy in stackblitz, so there is no online repro here.
Download and upgrade all `@angular/*`, you can find the name inside the component is `Angular`, but the outside name is `Angular Next` after 3 sec.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect         0.900.0-next.15
@angular-devkit/build-angular     0.900.0-next.15
@angular-devkit/build-optimizer   0.900.0-next.15
@angular-devkit/build-webpack     0.900.0-next.15
@angular-devkit/core              9.0.0-next.15
@angular-devkit/schematics        9.0.0-next.15
@angular/cli                      9.0.0-next.15
@ngtools/webpack                  9.0.0-next.15
@schematics/angular               9.0.0-next.15
@schematics/update                0.900.0-next.15
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Comment by h-cenggel** [comment]
+1

**Comment by trotyl** [comment]
Relates to https://github.com/angular/angular/issues/33285

**Comment by manklu** [comment]
@vthinkxie Instead of manually trigger change detection, you could use rxjs.
See https://github.com/angular/angular/issues/33285#issuecomment-546528919 for a sample

**Comment by vthinkxie** [comment]
@manklu there are a lot of ways to make it work, but the point is the breaking change, we can not count on all lib users to modify all the variables to async observable, it brings too many troubles for them.

**Comment by IgorMinar** [comment]
We are looking into this issue, and reconsidering if this incompatibility is justified. It does appear that this is something we need to fix.

**Comment by jbedard** [comment]
I've run into this in multiple places now. This does seem odd imo. I would almost expect the opposite behavior of what ivy is doing. Data frequently comes from the template definition/declaration location...
