### ISSUE TITLE
tree-shakeable useExisting for inheritance and injection tokens

### ISSUE THREAD

**Issue by nud** [angular/angular#33400]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description

We have several classes like this:

```typescript
class A {
  // some methods
}

@Injectable()
class B extends A {
 // some more methods
}

@NgModule({
  providers: {
    B,
    { provide: A, useExisting: B }
  }
})
class MyModule {}
```

This works fine and allows us to provide several "level of services" to several users, making it easier to test stuff.

But when switching to `providedIn`, it is not possible to do so anymore. One seemingly obvious solution (adding `@Injectable({ providedIn: 'root', useExisting: B })` to class A) does not work because typescript complains about a value being used before being defined.

### Describe the solution you'd like

A possible solution would be to add an extra `provideAs` property to `@Injectable`, that would take an array of `ValueProvider` or type/tokens, so we can do something like this:

```typescript
@Injectable({
  provideIn: "root"
  provideAs: [A]
})
class B {
}
```

As a bonus, it would also make it possible to use the same facility for injection tokens, which would also be nice.

```typescript
@Injectable({
  providedIn: "root",
  provideAs: [{ provide: HTTP_INTERCEPTORS, multi: true }]
})
class MyInterceptor {
}
```

Maybe an extra key would be needed if someone wants to tweak the behaviour between `useExisting`-style and `useClass`-style.

### Describe alternatives you've considered

The current alternative is sticking to `NgModule`-based provider definition.

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/27477

**Comment by nud** [comment]
@trotyl only the token part, but IMO the "inheritance" part is still valid because in that use case, it is expected that you'd inject the class (or one of the `provideAs`es) directly.

**Comment by trotyl** [comment]
> only the token part, but IMO the "inheritance" part is still valid because in that use case, it is expected that you'd inject the class (or one of the `provideAs`es) directly.

It has nothing to do with the use case, what you're suggesting isn't logically possible. It has been explained in the linked issue above and I don't think pasting is needed.

**Comment by nud** [comment]
Ok I misunderstood the explanation in the other issue when I first read it. I skipped over the purity argument. So this proposal is definitely not an option to solve the problem.

Is there any way to work around the reference-before-use issue? Because it unfortunately makes using `useExisting` in decorators with abstract classes or inheritance a no-go ATM.

**Comment by trotyl** [comment]
> Is there any way to work around the reference-before-use issue? Because it unfortunately makes using useExisting in decorators with abstract classes or inheritance a no-go ATM.

It can be wrapped in `forwardRef` like:

```typescript
@Injectable({
  providedIn: 'root',
  useExisting: forwardRef(() => Bar)),
})
abstract class Foo {}

@Injectable()
class Bar extends Foo {}
```

**Comment by nud** [comment]
Thanks!
