### ISSUE TITLE
IVY comp - ERROR in app/app.module.ts:136:12 - error TS-991010: Value at position 15 in the NgModule.imports of AppModule is not a reference: [object Object]

### ISSUE THREAD

**Issue by ALEXOTANO** [angular/angular#33405]
# 🐞 bug report

### Affected Package
IVY

### Is this a regression?

No, works fine if I disable IVY.

### Description

Been trying to get IVY to compile our project, I've made many PR to current libraries so they will be compatible with IVY, and now we're able to pass all the compiling *library* : module, succesfully but after all that I'm receiving: 
![image](https://user-images.githubusercontent.com/38110541/67585125-92741b00-f714-11e9-9788-51a6c5fa3ca4.png)

I can't understand what to look for: 

my app.module imports are: 
```
imports: [
    ContactosModule,
    PopUpsModule,
    LayoutModule,
    AuthModule,
    CoreModule,
    MaterialModule,
    DirectivasModule,
    PipesModule,
    FormsModule,
    SweetAlert2Module,
    BrowserModule,
    BrowserAnimationsModule,
    HttpClientModule,
    AppRoutesModule,
    StoreModule.forRoot(appReducers),
    SocketIoModule.forRoot(mySocketConfig),
    StoreDevtoolsModule.instrument({ maxAge: 25, logOnly: environment.production }),
    FlexLayoutModule,
    ServiceWorkerModule.register('./ngsw-worker.js', { enabled: environment.production }),
    SocialLoginModule
  ],
```

## 🔥 Exception or Error

as above
<pre><code>
ng build --prod

chunk {0} runtime.1720a40670866f12654e.js (runtime) 1.45 kB [entry] [rendered]
chunk {1} main.580833eeafe7b31e9e58.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills.c3e242d22f08a71b9be2.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} polyfills-es5.775a3e2687fce568f2ea.js (polyfills-es5) 79.6 kB [initial] [rendered]
chunk {4} styles.bf34b7d793f8cf1ec584.css (styles) 317 kB [initial] [rendered]
chunk {scripts} scripts.3fb9b0ac9d7e8816a58a.js (scripts) 28.2 kB [entry] [rendered]
Date: 2019-10-25T15:38:39.948Z - Hash: 4be1cfdc6f785e26fd4e - Time: 17099ms

ERROR in app/app.module.ts:136:12 - error TS-991010: Value at position 15 in the NgModule.imports of AppModule is not a reference: [object Object]

136   imports: [
               ~
137     ContactosModule,
    ~~~~~~~~~~~~~~~~~~~~
...
156     SocialLoginModule
    ~~~~~~~~~~~~~~~~~~~~~
157   ],
    ~~~

</code></pre>


## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.12
Node: 10.16.3
OS: win32 x64
Angular: 8.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.12
@angular-devkit/build-angular      0.803.12
@angular-devkit/build-optimizer    0.803.12
@angular-devkit/build-webpack      0.803.12
@angular-devkit/core               7.3.9
@angular-devkit/schematics         7.3.9
@angular/cdk                       8.2.3
@angular/cli                       8.3.12
@angular/fire                      5.2.1
@angular/flex-layout               8.0.0-beta.27
@angular/material                  8.2.3
@angular/material-moment-adapter   8.2.3
@angular/pwa                       0.13.9
@ngtools/webpack                   8.3.12
@schematics/angular                7.3.9
@schematics/update                 0.803.12
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2

</code></pre>

**Comment by AndrewKushnir** [comment]
Hi @ALEXOTANO, could you please try to reproduce this error with the @next version (`9.0.0-next.13`)? The error message was improved, so you may find additional information regarding this problem. Thank you.

**Comment by ALEXOTANO** [comment]
I'm working on it, its been 4 hard hours. 
Getting this :  
` ERROR in Error: Assertion error: failed to find directive with exportAs: ngModel `
I'm doing some research about it,

**Comment by ALEXOTANO** [comment]
I couldn't migrate our app, I'll close this for now, I'll give it a try in a few days and open a new issue in case I run into trouble again.
