### ISSUE TITLE
Param Map for Activated Route Contains Incorrect Param Keys

### ISSUE THREAD

**Issue by johnluisi** [angular/angular#33408]
# 🐞 bug report

### Affected Package

@angular/router

### Is this a regression?

I do not know if this issue existed in previous versions.

### Description

Retrieving values from the param map for the activated route does not work as expected. I was following the routing section of the tour of heroes tutorial https://angular.io/tutorial/toh-pt5. After defining the parameterized route for the hero details component, i noticed the details would not appear when clicking on a hero (from both the list and the dashboard). The URL displayed in the address bar was correct (i.e. /heroes/details/11), and the href attribute in the rendered html was also correct. After stepping through the debugger (in VS Code), i discovered that the parameter key in the route map was stored as "id}" instead of id. When i updated my code to retrieve the value passing "id}" as the key name, it worked as expected and the details were displayed for the selected hero. It appears as though one of the ending "}" chars from the binding syntax in the template is not being dropped when the key/value pair is added to the activated route's param map. This issue was found using Firefox 69.0.3 and was not tested in other browsers.

## 🔬 Minimal Reproduction

https://github.com/johnluisi/angular-demo-bug

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.14
Node: 12.13.0
OS: win32 x64
Angular: 8.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.14
@angular-devkit/build-angular     0.803.14
@angular-devkit/build-optimizer   0.803.14
@angular-devkit/build-webpack     0.803.14
@angular-devkit/core              8.3.14
@angular-devkit/schematics        8.3.14
@angular/cli                      8.3.14
@ngtools/webpack                  8.3.14
@schematics/angular               8.3.14
@schematics/update                0.803.14
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Comment by manklu** [comment]
@johnluisi The parameter in the route definition is named "id}".

```{  path: 'detail/:id}', component: HeroDetailComponent }```

**Comment by johnluisi** [comment]
well i just facepalmed really hard, i completely missed that when i reviewed everything. thanks !
