### ISSUE TITLE
Converting Array/Plain Object to FormArray/FormGroup

### ISSUE THREAD

**Issue by sardormajano** [angular/angular#33412]
# 🚀 feature request

 

**This feature request is for @angular/forms**

 

Currently creating a nested `FormGroup` requires knowing its structure in advance. There is unfortunately no capability to dynamically generate a nested `FormGroup` out of a plain `Object`.

 

```

const personFormGroup = new FormGroup({

  name: new FormControl(),

  address: new FormGroup({

    street: new FormControl()

  })

});

 

const personData: object = await someService.fetchPerson();

personFormGroup.patchValue(personData); //or could be `setValue`

 

```

 

It could have been a great feature to generate `FormGroup` or `FormArray` out of a plain `Object` or `Array`, and it seems to me (correct me if I am wrong please) that this should be part of `AbstractControl API`.

 

```

const personData: object = await someService.fetchPerson();

const personAbstractControl: AbstractControl = AbstractControl.from(personData);

```

 

 

For my specific case currently I have created a workaround, method called `mapToAbstractControl`

```

mapToAbstractControl(data: any): AbstractControl {

    if (_isPlainObject(data)) {

      const formGroupDescription = {};

      Object.keys(data).forEach(key => {

        formGroupDescription[key] = this.mapToAbstractControl(data[key]);

      });

      return new FormGroup(formGroupDescription);

    } else if (_isArray(data)) {

      const formArrayDescription = [];

      data.forEach(elem => {

        formArrayDescription.push(this.mapToAbstractControl(elem));

      });

      return new FormArray(formArrayDescription);

    } else {

      return new FormControl(data);

    }

  }

```

 

Do you agree that this method should be part of AbstractControl (e.g. a static method), or am I missing something here?

 

Thanks in advance.

**Comment by Airblader** [comment]
This is essentially https://angular.io/guide/dynamic-form

Baking this method in out of the box wouldn't allow defining default values, (async) validators or any other options, so its usefulness would be very limited.

**Comment by sardormajano** [comment]
Yeah, it wouldn't offer much in terms of validators and default values; but at least it would be somewhat of an inverse operation to `getRawValue` in `FormGroup`.
