### ISSUE TITLE
[9.0.0-rc] language-service doesn't display `strictTemplates` errors

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#33416]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/{compiler, language-service}

### Is this a regression?

 `strictTemplates` is a new feature. It's not regression.

### Description

Language service doesn't display errors from new `strictTemplates` however `ng build --aot` emits them. This is inconsistent.

![image](https://user-images.githubusercontent.com/1529180/67613022-81dea600-f7e3-11e9-8d29-acd3189d2c59.png)

## 🔬 Minimal Reproduction

- `ng new`
- set `strictTemplates: true` 
- write invalid template
- `ng build --aot`

```
<div *ngFor="let item of [{ key: 1 }]">
  {{ item.foo }}
</div>
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-next.16
Node: 10.16.0
OS: darwin x64
Angular: 9.0.0-next.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.16
@angular-devkit/build-angular     0.900.0-next.16
@angular-devkit/build-optimizer   0.900.0-next.16
@angular-devkit/build-webpack     0.900.0-next.16
@angular-devkit/core              9.0.0-next.16
@angular-devkit/schematics        9.0.0-next.16
@angular/cli                      9.0.0-next.16
@ngtools/webpack                  9.0.0-next.16
@schematics/angular               9.0.0-next.16
@schematics/update                0.900.0-next.16
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by lacolaco** [comment]
Same at RC.0

![image](https://user-images.githubusercontent.com/1529180/68063772-063aa700-fd57-11e9-828b-ded2e46690c8.png)

**Comment by IgorMinar** [comment]
This is a known issue, and it won't be addressed in v9.

Due to ensuring library compatibility and keeping the scope of v9 release manageable we decided to keep language service features on the same level as they were in v8.

Instead of feature development for language service, we did some heavy refactoring of the code to resolve instabilities and bugs that were affecting v8 language service users.

**Comment by lacolaco** [comment]
@IgorMinar The scope of v9.0 makes sense. But I don't know why it will be scoped in v10. Because `strictTemplates` is opt-in compiler options, I guess its diagnosis may not break compatibilities.
Why not v9.x scope?

**Comment by pshurygin** [comment]
Looks like this is not even in v10.1. Is there a release target for this issue?

**Comment by JoostK** [comment]
@pshurygin integrating the Ivy template type checker into the language service is currently in development, there's a project board here: https://github.com/orgs/angular/projects/1. It won't be ready when v11 arrives, but there may be experimental opt-in.

**Comment by JoostK** [comment]
With the Ivy language service now released in Angular v12, this issue has been resolved.
