### ISSUE TITLE
Decorator of AsyncValidator example should be a Directive not an Injectable

### ISSUE THREAD

**Issue by Irykson** [angular/angular#33429]
# 📚 Docs or angular.io bug report

### Description

The Decorator shouldn't be an Injectable as in the example.

It should be a Directive:
`@Directive({
  selector: '[uniqueAlterEgoValidator]',
  providers: [{
      provide: NG_ASYNC_VALIDATORS,
      useExisting: UniqueAlterEgoValidatorDirective,
      multi: true
    }
  ]
})`

I want to point out, that you need to provide NG_ASYNC_VALIDATORS instead of NG_VALIDATORS, which wasn't documented in the guide.

### What's the affected URL?**
https://angular.io/guide/form-validation#implementing-custom-async-validator

**Comment by AndrewKushnir** [comment]
Closing this ticket based on https://github.com/angular/angular/pull/34011#issuecomment-736929738.
