### ISSUE TITLE
DomSanitizer.sanitize return value if input was not safe

### ISSUE THREAD

**Issue by raichshlv** [angular/angular#33423]
I am trying to display e-mails fetched from an IMAP server on my webapp.

Currently I am importing DomSanitizer
`import { DomSanitizer } from "@angular/platform-browser";`
And I declare it as sanitizer in my constructor
`private sanitizer: DomSanitizer`

When I fetch for the e-mail, I call the DomSanitizer.sanitize function on the e-mails HTML.
`letter.safeHtml = this.sanitizer.sanitize(1, res.html);`

However, I want the user to be notified in case that some of the HTML has been stripped and have the user hit a button and run DomSanitizer.bypassSecurityTrustHtml if they accept the warning.

Therefore I request that the DomSanitizer.sanitize function returns null if the content provided was not safe or perhaps create another function like isSafe(SecurityContext, value) which would return true/false;

**Comment by dannyskoog** [comment]
The `sanitize` function is already capable of returning `null` in certain cases (https://angular.io/api/platform-browser/DomSanitizer#sanitize). Although most likely for a completely different purpose than the case you’re describing. 

Why can’t you just compare the string passed in to the function with the value returned?

**Comment by IgorMinar** [comment]
yup. compare the before and after strings to know if anything was stripped.

the sanitizer doesn't know if the content that was stripped was dangerous or not, it simply strips anything potentially dangerous.
