### ISSUE TITLE
BUILD ERROR 'Note' is not exported by node_modules/**

### ISSUE THREAD

**Issue by xeinebiu** [angular/angular#33442]
Hi.

From an angular project, when referencing to a model which is defiend on a Typescript module and as well it is exported as follows:
> export * from './base/models';

angular compiler complains when building, that the module is not exporting the model called "Note".

The following export works ok.
> export { Note } from './base/models/note.model';

But, I am more interested on the first export mode using the wild card.

Thank you.

**Comment by santoshyadav198613** [comment]
Looks like what you need is barells, you can post this in stackoverflow you will get the answer, but this is not a framework issue.

**Comment by alxhub** [comment]
If you look at the two paths in your exports (the `export *` vs the explicit export), you can see that the files are different. The `export *` is not exporting anything from `note.model`.

**Comment by xeinebiu** [comment]
> If you look at the two paths in your exports (the `export *` vs the explicit export), you can see that the files are different. The `export *` is not exporting anything from `note.model`.

in 'base/models' there is an index.ts file which explicity exports the Note model
