### ISSUE TITLE
Optional route matrix parameters not populated into paramMap of ActivatedRoute when route consists into two paths and each path have its own parameters

### ISSUE THREAD

**Issue by borjapazr** [angular/angular#33443]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/angular

### Description
When using matrix route optional parameters if the route absolute path consists in multiple paths with matrix parameters, the ActivatedRoute only contains the parameters of the last path. On the other side, if the path is composed by children routes and the main route doesn't have a component associated, then both all the matrix params will merge and doesn't respect its namespace.

## 🔬 Minimal Reproduction
For example.

I define the following routes:

```
const routes: Routes = [
  {
    path: '',
    redirectTo: 'one',
    pathMatch: 'full'
  },
  {
    path: 'One',
    component: OneComponent
  },
  {
    path: 'two/test',
    component: TwoComponent
  }
];
```
Then, in OneComponent I have this function that I call in a button click event:

```
goToTwo() {
    this.router.navigate(['/two/', {twoMatrix: 'twoMatrixValue'}, 'test', {testMatrix: 'testMatrixValue'}]);
}
```
In TwoComponent:

```
ngOnInit() {
    this.activatedRoute.params.subscribe(values => {
      console.log(values);
    });
}
```
When I click the button and I go to TwoComponent the URL becames into:

`http://localhost:4200/two;twoMatrix=twoMatrixValue/test;testMatrix=testMatrixValue`

But when I print the activatedRoute params, only the matrix params related with the last path (test) are retrieved. It shows like this:

`{testMatrix: "testMatrixValue"}`

I expect that the params related with "two" will be also retrieved and printed.

I was testing with another routes configuration, for example:

```
const routes: Routes = [
  {
    path: '',
    redirectTo: 'one',
    pathMatch: 'full'
  },
  {
    path: 'one',
    component: OneComponent
  },
  {
    path: 'two',
    children: [
      {
        path: 'test',
        component: TwoComponent
      }
    ]
  }
];
```
With this children route, it works as expected. I am be able to retrieve all the parameters from this.activatedRoute.params.

But when I change this routes to this:
```
const routes: Routes = [
  {
    path: '',
    redirectTo: 'one',
    pathMatch: 'full'
  },
  {
    path: 'one',
    component: OneComponent
  },
  {
    path: 'two',
    component: TwoComponent,
    children: [
      {
        path: 'test',
        component: TwoComponent
      }
    ]
  }
];
```
This way, TwoComponent prints its parameters in its corresponding path. This requires two `router-outlet`. Without component attribute in two path ActivatedRoute populates its paramsMap with both of `testMatrix` and `twoMatrix`. This behaviour has a downside, because if both of params have the same name, one will override the other. With this attribute the first TwoComponent will print `twoMatrix` and the second one `testMatrix`.

The other solution I've found to get all the params is by using the URL of the activatedRoute this.activatedRoute.snapshot.url[0].parameterMap

The final question is, why can't I retrieve the parameters with the first route configuration? I suspect that is because the route two/test acts as whole, but I am not sure. Is this a bug?

Thanks in advance.

## 🌍  Your Environment

**Angular Version:** 8.0.1
<pre>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.6
Node: 10.16.0
OS: win32 x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cli                      8.0.6
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0<code>

**Comment by atscott** [comment]
I think this is working in an understandable way. 

In your first example, no route matches `/two` so the data you send to that route is lost because there is no valid route for it.

In the second example, you do have a matching route for `/two` but not component for what would be the `ActivatedRoute` there so the data coalesce until you get to an active route. 

The last example works on the same principle: because you have a component that matches for `/two` it gets the params you passed to it. The params for the `ActivatedRoute` are only scoped to the current route so you only get that final `{testMatrix: 'testMatrixValue'}` for your child `TwoComponent` since there is an `ActivatedRoute` instance for the parent that takes `{twoMatrix: 'twoMatrixValue'}`
