### ISSUE TITLE
Attribute Selector changes Input behaviour

### ISSUE THREAD

**Issue by marcuskrahl** [angular/angular#33445]
# 🐞 bug report

### Affected Package
`@angular/core`

### Is this a regression?

No

### Description

As of #18156  a combination of an element selector and an attribute selector can be used to define required inputs, e.g. `selector: 'my-component[myRequiredInput]'`. This works correctly under normal circumstances.

However unit tests reset the input value when triggering a change detection (`fixture.detectChanges`). This does not occur if the attribute selector is removed, e.g. for `selector: 'my-component'`.
These errors are also reported by users in #18156. 

This behaviour can be seen in the unit tests of the sample repo.

There is a second issue which is very likely related to this. Again if a component has a selector combined of element and attribute and it is used as a component in the router, any previously set value will be overriden. Note that using a component with inputs as a routable component might not be something angular is expected to do correctly.

This issue is also demonstrated in the sample repo and in [https://angular-issue-repro2-vtyahq.stackblitz.io/](this stackblitz).

## 🔬 Minimal Reproduction

https://github.com/marcuskrahl/attribute-selector-angular
https://angular-issue-repro2-vtyahq.stackblitz.io/

## 🔥 Exception or Error

It should not matter whether if a selector is defined including an attribute selector or not. The behaviour for routing and unit tests should stay the same

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.3.14
Node: 10.16.2
OS: win32 x64
Angular: 8.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.14
@angular-devkit/build-angular     0.803.14
@angular-devkit/build-optimizer   0.803.14
@angular-devkit/build-webpack     0.803.14
@angular-devkit/core              8.3.14
@angular-devkit/schematics        8.3.14
@angular/cli                      8.3.14
@ngtools/webpack                  8.3.14
@schematics/angular               8.3.14
@schematics/update                0.803.14
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

No

**Comment by pedrozan** [comment]
Hello All, this seems like an interesting bug to fix, can I work on it?

**Comment by mhevery** [comment]
Verified that the test works in v9.0.1 as expected.
