### ISSUE TITLE
wrong brackets in guide code

### ISSUE THREAD

**Issue by MojioMS** [angular/angular#33459]
# 📚 Docs or angular.io bug report

### Description

The angular.io guide for reuseable-animations shows a code snippet containing 2x an opening square bracket `[`, but 3x the closing one  `]`. The showen code does not compile that way:
```
// src/app/open-close.component.ts
@Component({
     trigger('openClose', [
      transition('open => closed', [
        useAnimation(transAnimation, {
          params: {
            height: 0,
            opacity: 1,
            backgroundColor: 'red',
            time: '1s'
          }
        })
      ])
    ])
  ],
})
```

## 🔬 Minimal Reproduction
Just have a look at src/app/open-close.component.ts at the end of the URL.

### What's the affected URL?**
https://angular.io/guide/reusable-animations#creating-reusable-animations

**Comment by rkatka** [comment]
I'll push a PR for this
