### ISSUE TITLE
Very Very Long Documentations!!

### ISSUE THREAD

**Issue by ghost** [angular/angular#33461]
# 📚 Docs or angular.io bug report

### Description

 Some page documentations are painfully long! Already the learning curve for Angular is quite steep, when in that case the documentation atleast should not add further to the burden..

### What's the affected URL?**
 https://angular.io/guide/i18n (just one sample.. but there's lots more)

### Reproduction Steps**

 just open the url and see how long that topic on internationalisation is.. it is not a 5min or 15min read... it feels like a 5hour read!! Even if users are interested to learn something from official documentation, there is a huge possibility they will feel dejected after seeing the length of this page.. 

### Expected vs Actual Behavior**

 Categorise these documentations further, you can breakdown one long topic into several categories and have them each on its own page and finally show them grouped on the left panel in an accordion or something like https://angular.io/cli page and its subtopics.. Style guide advises us to not keep our component code more than 400 lines.. why the documentation should be 400 times bigger?? These are just the basics of User and Usability Engineering, considering the developers visiting angular.io as users of Angular...

**Comment by ElianCordoba** [comment]
I disagree, I prefer longer documentations rather than shorter ones, especially knowing that we are talking about Angular, a big framework with a lot of utilities and capabilities. If you think you can do better you can always open a PR.

**Comment by djleonskennedy** [comment]
I agree with @ElianCordoba almost all docs are well made

**Comment by kapunahelewong** [comment]
Hi @JamesAshok, thanks for your thoughts. They can indeed get long. Part of the reason for that is because of how they (the docs) developed over time. Like an app, they grew as we went, and as you know, Angular is robust with lots of features. 

We have made an effort to break some of the docs into smaller, more manageable chunks, such as the [NgModules](https://angular.io/guide/ngmodules) section, and there are other docs we'd like to do this with, but as you can imagine it's a very big job so we have to work in small steps as bandwidth allows while coordinating release-related tasks that require lots of sustained effort and attention. And the docs team is quite small with only two of us. It doesn't solve your issue, but hopefully the context helps, and of course you're always welcome to submit PRs or issues that might help re-think some of the places where we could improve. Sometimes issues that discuss better ways of thinking about a concept can really help guide a re-writing project for docs. Let me know if you have any more questions or thoughts.

**Comment by tayambamwanza** [comment]
> Hi @JamesAshok, thanks for your thoughts. They can indeed get long. Part of the reason for that is because of how they (the docs) developed over time. Like an app, they grew as we went, and as you know, Angular is robust with lots of features.
> 
> We have made an effort to break some of the docs into smaller, more manageable chunks, such as the [NgModules](https://angular.io/guide/ngmodules) section, and there are other docs we'd like to do this with, but as you can imagine it's a very big job so we have to work in small steps as bandwidth allows while coordinating release-related tasks that require lots of sustained effort and attention. And the docs team is quite small with only two of us. It doesn't solve your issue, but hopefully the context helps, and of course you're always welcome to submit PRs or issues that might help re-think some of the places where we could improve. Sometimes issues that discuss better ways of thinking about a concept can really help guide a re-writing project for docs. Let me know if you have any more questions or thoughts.

Something that would be awesome with regard to this is a set of official angular tutorial videos, there's a lot on youtube and stuff yes and don't want to eat into market but if you could do just the basics, like walkthrough the beginner tutorial app, I think inital learning curve would drop drammatically, not many people learn and absorb well through reading but today many are absorbed in video.

**Comment by kapunahelewong** [comment]
Thanks, @tayambamwanza. This is a great idea! I love videos and having them would definitely differentiate the potential learning paths in a constructive way for different styles of learning. And doing just the intro topics keeps it manageable. I'll definitely share your thoughts with our new team lead, @aikidave. Love this idea!

**Comment by tayambamwanza** [comment]
@kapunahelewong, It's been on my mind for a while now and I thought this is a good issue to propose it, glad you like it. You will obviously decide as a team on the details, but I'd like to recommend Jeff Delaney from [fireship.io](https://twitter.com/fireship_dev) to do them if he's willing as I enjoy his angular videos the most. Anyway hope it works out.

**Comment by kapunahelewong** [comment]
Oh thanks, @tayambamwanza, for the recommendation. I'll be sure to pass it along. 🌸😊

**Comment by tayambamwanza** [comment]
@JamesAshok Wouldn't you like to keep this open for the information about tutorial videos?

**Comment by kapunahelewong** [comment]
Update: Docs team is currently working in the direction of breaking up especially long docs, for example https://github.com/angular/angular/pull/36954. This will be an ongoing process related to the long-term project of improving the overall doc set.

Thanks everybody, for contributing to this conversation. It really helps!

**Comment by rockument69** [comment]
This issue is related to issue [37563](https://github.com/angular/angular/issues/37563).

**Comment by alxhub** [comment]
Closing as not really actionable for us - we've made a lot of progress refactoring the documentation (for example, the i18n page included in the initial report). At this point, it's unclear what the "completion criteria" would be for this issue as reported.

If you feel like a particular page of the documentation is excessively long or complicated, please open a specific ticket for it and we can consider that on a case-by-case basis.
