### ISSUE TITLE
Bug when local library linked by npm link (lib is not in the npm registry.)

### ISSUE THREAD

**Issue by kolkov** [angular/angular#33469]
Hi! I try to use local lib on my windows host, I put it to dependencies:
![image](https://user-images.githubusercontent.com/3740898/67773862-76061480-fa6d-11e9-8f74-c12497deecce.png)
but got an error when reinstall after ngcc changes message:
![image](https://user-images.githubusercontent.com/3740898/67773801-5838af80-fa6d-11e9-92d5-9e58530a835f.png)

```
Angular CLI: 9.0.0-next.18
Node: 12.6.0
OS: win32 x64
Angular: 9.0.0-next.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.18
@angular-devkit/build-angular     0.900.0-next.18
@angular-devkit/build-optimizer   0.900.0-next.18
@angular-devkit/build-webpack     0.900.0-next.18
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      9.0.0-next.18
@angular/pwa                      0.13.9
@ngtools/webpack                  9.0.0-next.18
@schematics/angular               7.3.9
@schematics/update                0.900.0-next.18
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
```

**Comment by kolkov** [comment]
If I remove this lib from dependencies, install works fine, but after install I got error:
![image](https://user-images.githubusercontent.com/3740898/67775259-bf576380-fa6f-11e9-9afc-1f096f8463a4.png) 
if I return it to dependencies I see the same error, but if I click to `go to declaration` in IDE I see:
![image](https://user-images.githubusercontent.com/3740898/67775445-08a7b300-fa70-11e9-891e-b97ab39e5a90.png)
whats wrong?

**Comment by kolkov** [comment]
The app is builds successfully:
![image](https://user-images.githubusercontent.com/3740898/67776592-920bb500-fa71-11e9-9895-0126fe98b9fb.png)
but, I can't see message in the footer:
![image](https://user-images.githubusercontent.com/3740898/67776702-bc5d7280-fa71-11e9-8516-e1b636586a0b.png)
instead of 
![image](https://user-images.githubusercontent.com/3740898/67776796-e57e0300-fa71-11e9-9f0f-3b654fe3b07e.png)
But apps rebuilds, if I change lib code.

**Comment by kolkov** [comment]
from console.
![image](https://user-images.githubusercontent.com/3740898/67801768-f0995900-fa9a-11e9-81bc-043ed0d9c1de.png)

**Comment by alxhub** [comment]
`npm link` isn't supported by the Angular compiler currently. Closing this as WAI.
