### ISSUE TITLE
CHANGE LOG is broken

### ISSUE THREAD

**Issue by sysmat** [angular/angular#33460]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by AndrewKushnir** [comment]
Hi @sysmat, I've checked CHANGELOG.md formatting and it looks correct. If you still see the problem, please create a new ticket with additional information (like screen shots and links to broken pages), so we can look into this. Thank you.
