### ISSUE TITLE
(dblclick) not updating IVY @next(9)

### ISSUE THREAD

**Issue by neofuture** [angular/angular#33479]
I have the following 

```
<span *ngFor="let windowItem of objectKeys(windowList)"
      [ngClass]="['tabItem',  windowList[windowItem].class]"
      [ngStyle]="{width: 'calc(' + (100 / objectKeys(windowList).length) + '% - 16px)'}"
      (click)="makeWindowActive(windowList[windowItem])"
      (dblclick)="maximiseWindow($event, windowList[windowItem])">
  <div class="text">{{ windowList[windowItem].titleBar}}</div>

  <button *ngIf="!windowList[windowItem].state.isMaximised && windowList[windowItem].resizable" (click)="maximiseWindow($event, windowList[windowItem])">
      &#9634;
    </button>
    <button *ngIf="windowList[windowItem].state.isMaximised && windowList[windowItem].resizable" (click)="maximiseWindow($event, windowList[windowItem])">
      <span>&#9723;</span><span>&#9723;</span></button>
</span>
```

The 

`(click)="maximiseWindow($event, windowList[windowItem])`

updates the view and change is all done properly 

The 

`(dblclick)="maximiseWindow($event, windowList[windowItem])`

DOES NOT update the view, and will only update after a click on another element or a further interaction

Environment Below

Issue is same in dev and production build 

Angular CLI: 9.0.0-next.16
Node: 12.7.0
OS: darwin x64
Angular: 9.0.0-next.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.16
@angular-devkit/build-angular     0.900.0-next.16
@angular-devkit/build-optimizer   0.900.0-next.16
@angular-devkit/build-webpack     0.900.0-next.16
@angular-devkit/core              9.0.0-next.16
@angular-devkit/schematics        9.0.0-next.16
@angular/cli                      9.0.0-next.16
@ngtools/webpack                  9.0.0-next.16
@schematics/angular               9.0.0-next.16
@schematics/update                0.900.0-next.16
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

**Comment by neofuture** [comment]
issue can be demonstrated here 

http://ng.owuk.co.uk

Double Click on a 'tab' window should maximise, but does not unless you single click on another tab, or the same tab then the previous maximise action happens

**Comment by IgorMinar** [comment]
I can't reproduce this issue. Can you please create a reproduction on stackblitz or as a cli projecT?

**Comment by neofuture** [comment]
Im not sure how I can, my test project is on bitbucket, not GitHub so I seem not to be able to clone to stackblitz ?

http://ng.owuk.co.uk/framework.zip

is a copy of the clone, If you build this, then double click on a tab on the tab bar this component has (dblclick) to maximise, but it does not trigger the change, the change is triggered when you click on another tab or something else

**Comment by IgorMinar** [comment]
that url doesn't work. This is my reduction that does work: https://stackblitz.com/edit/angular-cwyeoj?file=src/app/app.component.html

could you try to modify it by mimicking what your application does to reproduce your issue?

**Comment by neofuture** [comment]
I have the code here in vscode server

https://code.owuk.co.uk:8443

and running on 

https://code.owuk.co.uk:4200

**Comment by neofuture** [comment]
https://stackblitz.com/edit/angular-yjjs7q

this is pretty much the same simplified, and I cant get the same issue, so I feel the issue is in my own code, or something I have done thats not standard so ill close this for now and they and resolve, if I can reproduce ill submit a new issue, sorry for any wasted time

**Comment by neofuture** [comment]
For Information: The issue I had was I was setting the window object to maximised, and expecting the update to happen, what I had forgotten was that the window classes are only applied when the window was made active...

The flow was inverse as the active was done on click then the maximise set on dblclick, hence the class would only be applied when the window was next changed state and put through the on active event, or the loop that loops all windows to set the correct classes.

My bad, sorry to Igor and his team for me wasting time...
