### ISSUE TITLE
Proposal: add migrator for string token to @injectontoken<unknown>

### ISSUE THREAD

**Issue by Goodwine** [angular/angular#33475]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
 A clear and concise description of the problem or missing capability...
https://github.com/angular/angular/blob/09a2bb839fffb8f45bf63433ffd3529a48155b8e/packages/core/src/di/injector.ts#L65

`Injector.get('foo')` is deprecated and can make things difficult to maintain because it's typed as `any`
It would be awesome if `new InjectionToken<unknown>('foo')` was a drop-in replacement.

### Describe the solution you'd like
Implement a migrator (for `ng update`) so these values are auto inserted, and then the function signature can finally go away

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

An alternative is to update the signature to return `unknown`, still deprecated

**Comment by trotyl** [comment]
FYI, string tokens has legal use cases for bridging providers in `@angular/upgrade` as Angular did itself:

https://github.com/angular/angular/blob/cbd5d28f711e579a63144b60e6178ee327f53451/packages/upgrade/static/src/angular1_providers.ts#L42-L51

These kind of providers should not be changed as long as ngUpgrade is still supported.

Also, string providers are used in Router documentation:

+ https://angular.io/api/router/CanActivate
+ https://angular.io/api/router/CanActivateChild
+ https://angular.io/api/router/Resolve
+ https://angular.io/api/router/CanDeactivate
+ https://angular.io/api/router/CanLoad

If this is not preferred, then the official documentation should be changed first.

**Comment by Goodwine** [comment]
I agree, string tokens would need to be updated out of the documentation.

The way I see this is a multi step process so it's the less disruptive:
1. Update docs like you mentioned so string tokens don't come up anymore
2. Make sure `new InjectionToken<unknown>('foo')` works with `{provides: 'foo'...`
3. Write tslint fixer that replaces:
    * `injector.get('foo')` -> `injector.get(new InjectionToken<unknown>('foo'))`
4. `Injector.get(any, any): any` should now be safely removed

`{provides: 'foo'` would still be supported (but not documented) at this time since it would only be used internally

My goal is just that APIs shouldn't have `any` as a return value to avoid error prone things, at least `unknown` should be used instead.

But... I guess that if this is too much work, `Injector.get(any,any):any` could just be changed to `Injector.get(any,any):unknown` and everything else would remain the same
