### ISSUE TITLE
bootstrapping apps with `selector: '#app'` in `app.component.ts` is not working any more after upgrading to 9.0.0

### ISSUE THREAD

**Issue by JounQin** [angular/angular#33485]
# 🐞 bug report

### Affected Package

 The issue is caused by package `@angular/core` or `@angular/compiler` ? I don't know exactly.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

Yes, in `8.0.0`, it does work.

### Description

 A clear and concise description of the problem...

As title, when I'm using `#app`, it complains about `selctor 'app' not found`.

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by IgorMinar** [comment]
repro:

**application.component.ts**:
```
import { Component } from '@angular/core';

@Component({
  selector: '#app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'v9-test';
}
```

**index.html**:
```
...
<body>
  <div id=app-root></div>
</body>
...
```

**Comment by IgorMinar** [comment]
The issue doesn't repro in Jit mode (https://stackblitz.com/edit/angular-xth7wc) but does repro locally with CLI.

**Comment by trotyl** [comment]
> The issue doesn't repro in Jit mode (https://stackblitz.com/edit/angular-xth7wc) but does repro locally with CLI.

@IgorMinar This is an Ivy issue, StackBlitz doesn't support Ivy yet even when using v9. The issue happens in both AOT and JIT (of Ivy).

**Comment by IgorMinar** [comment]
@trotyl dang, you are right. I thought I hacked stackblitz enough to get to to run ivy in JIT mode, but that was not the case.
