### ISSUE TITLE
Ivy can't compile a project that has a library with internal imports sharing same parent directory

### ISSUE THREAD

**Issue by gnomeontherun** [angular/angular#33482]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler-cli

### Is this a regression?

 No it has not worked as far as I know. Related work in #29361 did not resolve the issue I'm facing, though the error reports the same thing. 

### Description

Ivy is not able to determine the file paths for imports inside of a library in the same CLI project when it is configured in a certain way. It seems to only occur when the library and the application are both inside of the same subdirectory in a project (`src/app` and `src/library`), but seems to work when they are not in the same subdirectory (`src/app` and `projects/library`). This is the only difference that I can determine from various configuration and setups. 

## 🔬 Minimal Reproduction

https://github.com/gnomeontherun/angular-9-ivy-library-error

Working configuration in separate directories: https://github.com/gnomeontherun/angular-9-ivy-library-error/commit/1443b1139d0a2d814d0acd1c2dbd8d1c1cc05547

Failing configuration in same directory: https://github.com/gnomeontherun/angular-9-ivy-library-error/commit/1f9c7817c2adc75229b4509d061f6d2d4f1c0fbf

1. Clone & `npm install`
2. `ng build` or `ng build --prod`

This is also reproducible from Clarity https://github.com/gnomeontherun/clarity/tree/angular9

With Clarity, you can still build the library with Ivy (enable Ivy in tsconfig.prod.json config file inside of clr-angular and run `ng build --prod clr-angular), it is isolated to the sample application that imports the library.

## 🔥 Exception or Error
<pre><code>
ERROR in Unable to write a reference to ClrAngularComponent in /repo/projects/clr-angular/src/lib/clr-angular.component.ts from /repo/projects/clr-angular/src/lib/clr-angular.module.ts

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-next.18
Node: 10.16.0
OS: darwin x64
Angular: 9.0.0-next.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-next.18
@angular-devkit/build-angular      0.900.0-next.18
@angular-devkit/build-ng-packagr   0.900.0-next.18
@angular-devkit/build-optimizer    0.900.0-next.18
@angular-devkit/build-webpack      0.900.0-next.18
@angular-devkit/core               9.0.0-next.18
@angular-devkit/schematics         9.0.0-next.18
@angular/cli                       9.0.0-next.18
@ngtools/webpack                   9.0.0-next.18
@schematics/angular                9.0.0-next.18
@schematics/update                 0.900.0-next.18
ng-packagr                         9.0.0-rc.1
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2

</code></pre>

**Anything else relevant?**

I tested a lot of things, such as the use of TypeScript paths or not, and everything was working until they were colocated in the same directory.

**Comment by alxhub** [comment]
Hello @gnomeontherun,

I dug into this reproduction, and was able to get the build working. It boils down to some project configuration in the tsconfigs.

The top-level tsconfig (which the app inherits from) has `@clr/angular` mapped to the library's TS sources. This is correct for an editor configuration. However, the Ivy compiler requires that any dependencies (e.g. the library, when building the app) already be compiled. So when building the app, `@clr/angular` should be mapped to the _compiled library_, not to its sources.

So I made a couple changes to the tsconfigs, for the app and the library both. I:

* Unified the `outDir`s into a single `out-tsc` structure, with `lib` and `app` subdirs.
* Used the TS option `rootDir` to eliminate a lot of the nested directory structure, so the library index ends up at `out-tsc/lib/index.d.ts`
* In the app tsconfig, used `paths` to map `@clr/angular` to `out-tsc/lib`, _overriding the mapping from the editor config_.

With these changes, the app is able to build correctly! 

Cheers :) 
-Alex

**Comment by rorry121** [comment]
is ivy supported for library by default? angular version 8.2.11

**Comment by JonWallsten** [comment]
@rorry121: In version 8 you have to enable IVY manually. In version 9 it's forced if I'm not mistaken.

**Comment by JonWallsten** [comment]
@alxhub: Sorr for highjacking this, but do you mind checking our monorepo as well? I also still get the same error message.
Reproduction: https://github.com/JonWallsten/monorepo-repro

**Comment by gnomeontherun** [comment]
Hi @alxhub I am unable to get your repo to build https://github.com/alxhub/angular-9-ivy-library-error - I get an error with unable to find the package.

```
git clone https://github.com/alxhub/angular-9-ivy-library-error.git
cd angular-9-ivy-library-error
npm i
ng build --prod clr-angular
ng build --prod dev
```

This is the error I'm getting.

```
ERROR in src/app/app.module.ts:7:34 - error TS2307: Cannot find module '@clr/angular'.

7 import { ClrAngularModule } from '@clr/angular';
                                   ~~~~~~~~~~~~~~
```

I've been able to reproduce this again with these exact commands as you see in this repository https://github.com/gnomeontherun/monorepo-library-errors which has a CI job that tries to build a clean monorepo and import the library into the app, but fails with the `Unable to write a reference to...` error.
