### ISSUE TITLE
[Feature|Bug][@angular/elements] NgModuleRef remains after CustomElement is removed from DOM

### ISSUE THREAD

**Issue by flash-me** [angular/angular#33489]
# 🚀 feature & bug  request

### Relevant Package
@angular/elements

### Description
Hi there. We are successfully ([& performant! :yum:](https://twitter.com/simsek_dev/status/1168163228574277639)) implementing the micro frontends approach with the help of **@angular/elements**.
On my weekly performance check of the many applications on the customer side, I realized that the bootstrapped module of an @angular/element remains alive, even after the CustomElement has been removed from the DOM. 
*To think further, this means that every service instance and the hole injection tree is still alive.*

### Describe the solution you'd like
We do have triggers / timestamps to know when to destroy such *NgModuleRefs*, by attaching this to the `disconnectedCallback()`, which is a [specified reaction for CustomElements](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-reactions).

### Describe alternatives you've considered
We / I can work this around by saving a reference to the bootstraped NgModuleRef and decide manually when to destroy the NgModuleRef, but
**In my opinion this is not an expected behaviour or should be documented at least somewhere.**

Yes, the current approach might share the current NgModuleRef of a given bootstrapped angular application, but the way I understand the concept of CustomElements, everything should be cleaned up after the element is removed from the DOM.
To put it rather dumbly: "Why are the @angular/elements not just create their own NgModuleRef?"

**Comment by flash-me** [comment]
Another solution would be to provide all services on Component, which is passed to createCustomElement, since the Component will be destroyed after removing from DOM.

But still, the injection tree remains and it's not clear at first look.

**Comment by flash-me** [comment]
Maybe instead of passing a component to the `createCustomElement` Method, 
- we could pass an NgModule to it
- save the `NgModuleRef` in a closure
- and destroy it on `disconnectedCallback`

This way the complete "platform" would be cleaned up, as I would expect it, when removing a CustomElement from the DOM.

**Comment by vinayakpatil** [comment]
Any updates on this? I am also stuck in similar situation while building micro-frontends with the help of angular elements.

**Comment by gkalpak** [comment]
This is a tricky one, I'm afraid. It is not easy (or even possible?) to know when an `NgModule` should be destroyed. One might choose to use one `NgModule` per Angular component, but that is no necessarily always the case.

In the future, we might tweak the `createCustomElement()` API to account for this usecase and others (such as #37441). That would be a breaking change, though.

Fortunately, there are work-arounds available for the time being (as @flash-me mentioned).

**Comment by vinayakpatil** [comment]
@gkalpak I know this following trick which I had used for reloads. But I am not sure how to use that in my use-case.

We render web-component on a specific route, if I manually invoke the destroy on route change then I get some weird error if I navigate back to the previous route with web-components. Basically, it wont bootstrap again. Any thoughts there?

```javascript
platformBrowserDynamic()
    .bootstrapModule(AppModule)
    .then(ref => {
      // INFO: Ensure Angular destroys itself on reloads.
      if (TrqWindowRef.getProp('ngRef')) {
        TrqWindowRef.getProp('ngRef').destroy();
      }
      TrqWindowRef.setProp('ngRef', ref);

      // Otherwise, log the boot error
    })
    .catch(err => console.error(err));
```

**Comment by gkalpak** [comment]
@vinayakpatil, I can't really say, since I don't know what your usecase is 😅
Maybe you could ask in one of our support channels (e.g. on StackOverflow or the Angular Discord server - see [CONTRIBUTING.md][1]).

[1]: https://github.com/angular/angular/blob/d39d64c15dcba74aa673cacfc1365bd35a1d4f95/CONTRIBUTING.md#question

**Comment by flash-me** [comment]
@gkalpak Currently, a Component is passed to the `createCustomElement` function.

Another use case would be to provide another function that accepts an NgModule instead of a Component. By doing this, the `bootstrap` Array could be used in order to find out for which Components a custom element should be created. This would support cohesion, since everything that belongs to those custom elements can be put into one single module.
Another benefit of this approach is that you would get an event on when to destroy the platform: 
When all of the bootstrapped Components have been removed from the DOM. 

This additional function would not introduce a breaking change, but instead adds a feature.

cheers
flash ⚡
