### ISSUE TITLE
Useful errors

### ISSUE THREAD

**Issue by lwensveen** [angular/angular#33492]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/*

### Description
After some years of Angular programming I've been noticing the same issues repeating itself over and over again. And that issue is a lack of information given by Angular when stuff goes wrong.

For instance, I've been refactoring some code, afterwards I wanted to run a build to see if everything was still in order.

Sadly, I was faced with the following errors:

```
ERROR in Cannot determine the module for class DbValueComponent in /lib/db-value/db-value.component.ts! Add DbValueComponent to the NgModule to fix it.

Cannot determine the module for class DbInputComponent in /lib/db-input/db-input.component.ts! Add DbInputComponent to the NgModule to fix it.
```

So then you think, alright lets take a look in my ngModule see if everything's in order. But everything's there. So now the error message became useless, it doesn't point you in the right way at all.

Now this is just a simple example, but this happens too often in my opinion. Greatly reduces efficiency for no apparent gain.

### Describe the solution you'd like
Fix error descriptions so it's actually useful.

### Describe alternatives you've considered
React

**Comment by alxhub** [comment]
@lwensveen I'm going to close this issue for a couple of reasons.

1) Without a reproduction/actual example code, there's no way of knowing whether or not the error is correct or not. That error message does seem informative, assuming it's accurate. We'd have to see the contents of the module to know for sure.

2) As a feature request for better error messages, this is a bit too vague to be actionable for us. Don't worry, though - we have lots of specific goals for improving error messages in the Angular compiler for Ivy. Some of them are already in place.
