### ISSUE TITLE
Support Custom Events in WebWorker apps

### ISSUE THREAD

**Issue by jteplitz** [angular/angular#3350]
Currently we only support a limited subset of events (specified in web-workers/ui/impl.ts). We'd like to somehow support user-defined events with custom serializers.

**Comment by jeffbcross** [comment]
Maybe this will be solved as part of render services implementation #2409.

**Comment by stakach** [comment]
It would be good to HammerJS events supported in webworkers at the very least - or should this be a seperate issue?

**Comment by splincode** [comment]
@jteplitz Is the issue relevant?

**Comment by jelbourn** [comment]
Closing all issues related to web-workers since Angular's experimental web-worker renderer has been deprecated and it now being removed completely in Angular v11.
