### ISSUE TITLE
new lazyLoad syntax not working after upgrading to 8.2.12 from 7

### ISSUE THREAD

**Issue by shaulnaim** [angular/angular#33501]
this works:
 { path: 'error', loadChildren:  () => ErrorsModule },
but this
 { path: 'error', loadChildren:  () => import('./modules/errors/errors.module').then(m => m.ErrorsModule) },

creates error
****ERROR in ./src/app/app.routes.ts 154:41
Module parse failed: Unexpected token (154:41)

> **You may need an appropriate loader to handle this file type.**

|         canActivate: [RouteGuardService]
|     },
>     { path: 'error', loadChildren: () => import('./modules/errors/errors.module').then(m => m.ErrorsModule) },
|     { path: '**', redirectTo: 'error/404', pathMatch: 'full' }
| ];
 @ ./src/app/app.module.ts 89:0-48 161:12-28
 @ ./src/singleSpaEntry.ts
 @ multi (webpack)-dev-server/client?http://0.0.0.0:9001 src/singleSpaEntry.ts
i ｢wdm｣: Failed to compile.****

tried this https://github.com/angular/angular/issues/31421
and also removing node_modules and package.lock etc... with no help.....

**Comment by spock123** [comment]
Hi, just passing by. 

Double check the url to your "ErrorsModule"
Double check file extension to your ErrorsModule file 
What does your ErrorsModule file look like? Does is export a class named "ErrorsModule"?

Sorry for the questions, I find that this feature works without issues so I suspekt something is going on with your code somewhere.. I once had an error somewhat like that, turned out I had accidentally named my file ".js" instead of ".ts", hence my questions.

**Comment by shaulnaim** [comment]
`import { UnknownComponent } from './unknown/unknown.component';
import { ErrorComponent } from './error.component';
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Error404Component } from './error404/error404.component';
import { Error500Component } from './error500/error500.component';
import { NotSupportedComponent } from './not-supported/not-supported.component';
import { ErrorsRoutingModule } from './errors-routing.module';

@NgModule({
  declarations: [
    ErrorComponent,
    Error404Component,
    Error500Component,
    UnknownComponent,
    NotSupportedComponent
  ],
  exports: [
    ErrorComponent
  ],
  imports: [CommonModule, ErrorsRoutingModule]
})
export class ErrorsModule {}
`

@spock123  this is my ErrorsModule  no problem with URL neither extensions

**Comment by shaulnaim** [comment]
`import { NotSupportedComponent } from './not-supported/not-supported.component';
import { UnknownComponent } from './unknown/unknown.component';

const routes: Routes = [
   {
    path: '',
    component: ErrorComponent,
    children: [
      { path: '', redirectTo: 'unknown', pathMatch: 'full' },
      { path: '404', component: Error404Component },
      { path: '500', component: Error500Component },
      { path: 'not-supported', component: NotSupportedComponent },
      { path: 'unknown', component: UnknownComponent }
    ]
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class ErrorsRoutingModule { }
`
and this is ErrorsRoutingModule

**Comment by shaulnaim** [comment]
and webpack.config
`const path = require('path');
const ContextReplacementPlugin = require('webpack/lib/ContextReplacementPlugin');

let webpackLoader;
let AngularCompilerPluginAttempt;
try {
  AngularCompilerPluginAttempt = require('@ngtools/webpack');
  AngularCompilerPluginAttempt = AngularCompilerPluginAttempt.AngularCompilerPlugin;
  webpackLoader = '@ngtools/webpack';
} catch (e) {
}

if (!webpackLoader) {
  webpackLoader = '@angular-devkit/build-angular/node_modules/@ngtools/webpack';
}
const AngularCompilerPlugin = AngularCompilerPluginAttempt ? AngularCompilerPluginAttempt : require('@angular-devkit/build-angular/node_modules/@ngtools/webpack').AngularCompilerPlugin;
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const CopyWebpackPlugin = require('copy-webpack-plugin');


module.exports = function (env) {
  const analyzeBundle = !!(env && env.analyzeBundle);
  const prodMode = !!(env && env.production);


  const plugins = [
    new ContextReplacementPlugin(
      /(.+)?angular(\\|\/)core(.+)?/,
      path.resolve(__dirname, '../src')
    ),
    new AngularCompilerPlugin({
      mainPath: path.resolve(__dirname, 'src/singleSpaEntry.ts'),
      tsConfigPath: path.resolve(__dirname, 't.sconfig.json'),
      sourceMap: !prodMode,
      skipCodeGeneration: !prodMode,
      platform: 0,
      hostReplacementPaths: {
        "environments/environment.ts": prodMode ? "environments/environment.prod.ts" : "environments/environment.ts"
      }
    }),
    new CopyWebpackPlugin([
      {from: 'src/assets', to: 'assets'},
      {from: 'src/mustUseAppFramework.html', to: 'index.html'}])
  ];

  if (analyzeBundle) {
    plugins.push(new BundleAnalyzerPlugin());
  }

  const devTypescriptLoader = [
    {
      test: /\.ts$/,
      loader: webpackLoader
    }
  ];

  const prodTypescriptLoader = [
    {
      "test": /\.js$/,
      "use": [
        {
          "loader": "@angular-devkit/build-optimizer/webpack-loader",
          "options": {
            "sourceMap": false
          }
        }
      ]
    },
    {
      test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/,
      use: [
        {
          "loader": "@angular-devkit/build-optimizer/webpack-loader",
          "options": {
            "sourceMap": false
          }
        },
        webpackLoader
      ]
    }
  ];

  const typescriptLoader = prodMode ? prodTypescriptLoader : devTypescriptLoader;

  return {
    entry: {
      singleSpaEntry: 'src/singleSpaEntry.ts',
    },
    output: {
      filename: '[name].js',
      path: path.resolve(__dirname, 'release'),
      libraryTarget: 'umd',
      library: 'segmentation-root'
    },
    module: {
      rules: [
        {
          test: /\.polyfill\/\.js$/,
          use: [ 'script-loader' ]
        },
        {
          test: /\.html$/,
          loader: ["raw-loader", {
            loader: 'replace-string-loader',
            options: {
              search: /assets/g,
              replace: '\/seg\/assets',
              file: false
            }
          },{
            loader: 'replace-string-loader',
            options: {
              search: /\/assets/g,
              replace: 'assets',
              file: false
            }
          }]
        },
        {
          test: /\.(jpe?g|png|webp|gif|otf|ttf|woff2?|ani)$/,
          loader: "url-loader",
          options: {
            name: "[name].[hash:20].[ext]",
            limit: 10000,
            publicPath: '/seg/'
          }
        },
        {
          test: /\.(eot|svg|cur)$/,
          loader: "file-loader",
          options: {
            name: "[name].[hash:20].[ext]",
            publicPath: '/seg/'
          }
        },
        {
          test: /bootstrap\.scss$/,
          exclude: [
            path.resolve(__dirname, "src/styles.scss")
          ],
          use: [{
            loader: 'replace-string-loader',
            options: {
              search: /assets/g,
              replace: '\/seg\/assets',
              file: false
            }
          },{
            loader: 'replace-string-loader',
            options: {
              search: /\/assets/g,
              replace: 'assets',
              file: false
            }
          }, 'to-string-loader', 'style-loader', 'css-loader', 'sass-loader'],
        },
        {
          test: /styles\.scss$/,
          exclude: [
            path.resolve(__dirname, "node_modules/bootstrap")
          ],
          use: [{
            loader: 'replace-string-loader',
            options: {
              search: /assets/g,
              replace: '\/seg\/assets',
              file: false
            }
          },{
            loader: 'replace-string-loader',
            options: {
              search: /\/assets/g,
              replace: 'assets',
              file: false
            }
          }, 'to-string-loader', 'style-loader', 'css-loader', 'sass-loader']
        },
        {
          test: /\.scss$/,
          exclude: [
            path.resolve(__dirname, "node_modules/bootstrap"),
            path.resolve(__dirname, "src/styles.scss")
          ],
          use: ['to-string-loader', {
            loader: 'replace-string-loader',
            options: {
              search: /assets/g,
              replace: '\/seg\/assets',
              file: false
            }
          },{
            loader: 'replace-string-loader',
            options: {
              search: /\/assets/g,
              replace: 'assets',
              file: false
            }
          }, 'raw-loader', 'sass-loader']
        },
        {
          test: /\.css$/,
          exclude: [
            path.resolve(__dirname, "node_modules/bootstrap"),
            path.resolve(__dirname, "src/styles.scss")
          ],
          use: ['to-string-loader', 'style-loader', 'css-loader']
        }
      ].concat(typescriptLoader)
    },
    resolve: {
      extensions: [".ts", ".js"],
      modules: [
        __dirname,
        'node_modules'
      ]
    },
    devtool: prodMode ? 'none' : 'inline-sourcemap',
    externals: [],
    plugins: plugins,
    devServer: {
      historyApiFallback: true,
      watchOptions: {aggregateTimeout: 300, poll: 1000},
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, PATCH, OPTIONS",
        "Access-Control-Allow-Headers": "X-Requested-With, content-type, Authorization"
      }
    }
  }
};
`

**Comment by shaulnaim** [comment]
after removing node_modules and package-lock and installing again. I have no errors on compile stage but when routing to a lazyload module I get this on network tab - any ideas why?

![image](https://user-images.githubusercontent.com/2099185/67947365-2b5ed680-fbec-11e9-91c6-efd2faa223d2.png)

**Comment by spock123** [comment]
@shaulnaim ahh I thought you were using the CLI..  maybe it's something with your custom webpack setup then

**Comment by IgorMinar** [comment]
if you are using custom webpack setup then the dynamic imports are not going to work, that feature is available only for Angular CLI users for now.

I suggest that you move your application to use Angular CLI and if the issue persists please share your `ng version` output so that we can better analyze where the issue can be coming from.

**Comment by shaulnaim** [comment]
@IgorMinar thanks, thats disappointing... can you tell me how should i handle lazy loading in custom webpack project? since the string path version also not working out of the box...

also will i face issues on this kind of project if i want to use angular elements?
thanks a lot
appreciate your time
