### ISSUE TITLE
Two-way binding not working

### ISSUE THREAD

**Issue by DibyodyutiMondal** [angular/angular#33503]
# 🐞 bug report

### Affected Package

Don't know what's causing the problem. Dependencies are as follows:
```
"dependencies": {
    "@angular/animations": "~9.0.0-next.14",
    "@angular/common": "~9.0.0-next.14",
    "@angular/compiler": "~9.0.0-next.14",
    "@angular/core": "~9.0.0-next.14",
    "@angular/forms": "^9.0.0-next.15",
    "@angular/localize": "^9.0.0-next.11",
    "@angular/platform-browser": "~9.0.0-next.14",
    "@angular/platform-browser-dynamic": "~9.0.0-next.14",
    "@angular/router": "~9.0.0-next.14",
    "rxjs": "~6.5.3",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.0-next.18",
    "@angular/cli": "~9.0.0-next.18",
    "@angular/compiler-cli": "~9.0.0-next.14",
    "@angular/language-service": "~9.0.0-next.14",
    "@types/node": "^12.11.1",
    "ts-node": "~8.4.1",
    "tslint": "~5.20.0",
    "typescript": "~3.6.4"
  }
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 
```
 "dependencies": {
    "@angular/animations": "~9.0.0-next.2",
    "@angular/cdk": "~8.1.2",
    "@angular/common": "~9.0.0-next.2",
    "@angular/compiler": "~9.0.0-next.2",
    "@angular/core": "~9.0.0-next.2",
    "@angular/forms": "~9.0.0-next.2",
    "@angular/material": "^8.1.2",
    "@angular/platform-browser": "~9.0.0-next.2",
    "@angular/platform-browser-dynamic": "~9.0.0-next.2",
    "@angular/router": "~9.0.0-next.2",
    "hammerjs": "^2.0.8",
    "rxjs": "~6.5.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.802.1",
    "@angular/cli": "~8.2.1",
    "@angular/compiler-cli": "~9.0.0-next.2",
    "@angular/language-service": "~9.0.0-next.2",
    "@types/node": "~8.9.4",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
```

### Description

Two-way binding does not work as intended, at least with *ngFor directives. I have been unable to find the time for testing and further specifiy what the problem is, beyond the fact that the cli says that it can't find the looping variable as a property of the component class, which is obvious, because the looping variable has been declared in the template.

## 🔬 Minimal Reproduction
https://github.com/DibyodyutiMondal/Issue-Repros/tree/1/repro1

## 🔥 Exception or Error
<pre><code>
ERROR in src/app/app.component.html:1:56 - error TS2339: Property 'n' does not exist on type 'AppComponent'.

1 <primary *ngFor="let n of numbers" [(input_number)]="n"></primary>
                                                         ~~~~~~

  src/app/app.component.ts:5:16
    5   templateUrl: './app.component.html'
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.
</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-next.19
Node: 12.2.0
OS: win32 x64
Angular: 9.0.0-next.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.19
@angular-devkit/build-angular     0.900.0-next.19
@angular-devkit/build-optimizer   0.900.0-next.19
@angular-devkit/build-webpack     0.900.0-next.19
@angular-devkit/core              9.0.0-next.19
@angular-devkit/schematics        9.0.0-next.19
@angular/cli                      9.0.0-next.19
@angular/localize                 9.0.0-next.11
@ngtools/webpack                  9.0.0-next.19
@schematics/angular               9.0.0-next.19
@schematics/update                0.900.0-next.19
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Comment by trotyl** [comment]
Expected behavior, see https://angular.io/guide/deprecations#cannot-assign-to-template-variables.

**Comment by DibyodyutiMondal** [comment]
Ohkay... Thank you for pointer...
