### ISSUE TITLE
(feat/DecimalPipe) Option to set the thousand separator.

### ISSUE THREAD

**Issue by Domvel** [angular/angular#33505]
# 🚀 feature request

### Relevant Package
`DecimalPipe` from `@angular/common`
https://angular.io/api/common/DecimalPipe

### Description
Currently there is no option to configure the `number` pipe to set the thousand separator character. But it would be awesome to do this. In best case once on global settings. And optional as parameter. This parameter is a simple string variable and by default the current behavior. But this parameter must allow an empty string to remove the separator or a space character. So to handle the default behavior we should use the initial value `undefined`. ...

### Describe the solution you'd like
An option to set the string of the thousand separator character. Example values for the character: `''` (empty string), `' '` (space), `'_'` Underscore, `undefined` (default / current behavior).

### Describe alternatives you've considered
In my opinion this pipe really need this option.
I wondering why is this not already implemented. I hope this is not the first request. Sorry if this is a duplicate. I really searched for it here. Nothing found.

A alternative could be an option to just disable the separator. Like in `toLocalString` option `useGrouping`. [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString) But it would be nice to replace the separator to `' '` (space) to be neutral for all locations.

**Comment by trotyl** [comment]
The numeric separator is currently defined by locale file extracted from CLDR, do you mean you want numbers being displayed in different format even in same locale?

**Comment by Domvel** [comment]
No, very simple. Just replace the thousand separator globally for the current language. Ok, I don't know how this currently works. I can't find the part in the source code. 
But I guess that this comes from a JavaScript number API like `toLocaleString`? So, we have to replace this separator by string match replace? Without removing the decimal separator. 🤔 Currently I have no idea how to do that best.

If the number is generated by `toLocaleString` [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString). There is an option `useGrouping`. If this is set to `false` it will remove the separator. I update my initial post above for "alternatives". Because the alternative is to just disable the separator. ...

**Comment by trotyl** [comment]
The separator is defined by CLDR:

https://github.com/unicode-cldr/cldr-numbers-full/blob/2da222c3406e15890d208990b170d7bb52ef8293/main/en/numbers.json#L18

And extracted to Angular locale files:

https://github.com/angular/angular/blob/2eed7e33ef47f9cf8294e6111f2c3f5d6472b6de/packages/common/locales/en.ts#L39

Replacing the definition is only about copying the file and changing its value, there is no difficulty in doing that. But given the format itself is private API I agree this can be a valid feature request (or documentation request).

**Comment by Domvel** [comment]
Thanks. But no, I don't want to copy the locale files or manipulate the node_modules. I think about a global setting to overwrite the separator of all locales or just an option to disable it.

**Comment by Domvel** [comment]
Here is one workaround. Writing an own pipe with `toLocaleString`.

```js
const input = 123412341234.1234;

// Find out the thousand separator.
const thousandSeparator = (1234).toLocaleString().replace(/\d/g, '');
const thousandSeparatorRegex = new RegExp(escapeRegExp(thousandSeparator), 'g');

let output = input.toLocaleString().replace(thousandSeparatorRegex, ' ');

console.log(thousandSeparator);
console.log(output);
```

Console result (en):

```text
,
123 412 341 234.123 
```

We could also pass the LOCALE_ID of Angular in the contructor and the locale string to the `toLocaleString` method. Otherwise it takes the browser and the OS language settings.

```ts
@Inject(LOCALE_ID) private _locale: string
```

It's also possible to simply disable the thousand separator by the option `useGrouping` to `false` of the `toLocalString` method.

I prefer to use the Angular pipe. This is just a demo of a workaround.

**Comment by trotyl** [comment]
Locale files has nothing to do with `node_modules`. It's only a static data registered by yourself.

The symbol is shared by several utils: [`DecimalPipe`](https://angular.io/api/common/DecimalPipe),  [`PercentPipe`](https://angular.io/api/common/PercentPipe), [`CurrencyPipe`](https://angular.io/api/common/CurrencyPipe), [`formatNumber`](https://angular.io/api/common/formatNumber), [`formatPercent`](https://angular.io/api/common/formatPercent), [`formatCurrency`](https://angular.io/api/common/formatCurrency). It's never a pipe-level configuration.

No matter which one you want the overriding, it need to happen only once before any application code, otherwise existing executions won't get the correct result.

Also, even you only need to override `separator` today, but others may have different overriding case, the scenario is always about customizing locale configuration, not any specific symbol. Or there would be eventually 117 APIs to set each symbol in locale configuration.

**Comment by ahnpnl** [comment]
hi @trotyl , I have a question related to this topic. I see at the moment `DecimalPipe` doesn't accept grouping separator and it throws error. Is it by designed ?

For example in locale `en`, I have a string value `1,5.5` (which can be interpreted as `15.5`), this string will cause the pipe to throw error.
