### ISSUE TITLE
Difficulty to explore the resource page @ https://angular.io/resources

### ISSUE THREAD

**Issue by bhargava-raju** [angular/angular#33526]
# 📚 Docs or angular.io bug report

### Description

 **EXPLORE ANGULAR RESOURCES** @ https://angular.io/resources needs to be sturctured to be able to navigate to all resources with improved user experience. A lone scroll bar in this page will not help the reader a great deal in exploring the resources.

## 🔬 Minimal Reproduction
Go to https://angular.io/resources
### What's the affected URL?**
 https://angular.io/...

### Expected vs Actual Behavior**
User should be able to nagivate the various aspects of the angular resources with ease. The current page is unable to provide a glimpse of all the resources at one place as well.

## 📷Screenshot

![image](https://user-images.githubusercontent.com/46414819/68012666-aee1fb80-fcb0-11e9-8c9f-10977841894e.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by gkalpak** [comment]
Quite true. The resources page is getting unwieldy.
We should at least have a Table of Contents in there. Possibly also break the page up into multiple tabs (e.g. `Development`, `Education`, `Community`), similar to the [contributors page][1].

[1]: https://angular.io/about

**Comment by bhargava-raju** [comment]
I will work on this.

**Comment by ajitsinghkaler** [comment]
@bhargava-raju can I help you on this

**Comment by ajitsinghkaler** [comment]
@bhargava-raju @gkalpak I think for the first change we can just convert the headings into expansion panels.

**Comment by gkalpak** [comment]
Not sure what you mean, @ajitsinghkaler? Can you elaborate?

**Comment by ajitsinghkaler** [comment]
![Expansion Panel   Angular Material](https://user-images.githubusercontent.com/39260684/68781063-363e5000-065d-11ea-85b3-c0bf16783613.png)

Something like this I wanted to suggest an expansion panel for all the headings in the angular resources page.

**Comment by gkalpak** [comment]
Oh, I see. Personally, I would rather use the tabbed approach we use in the `About` page (as mentioned in https://github.com/angular/angular/issues/33526#issuecomment-548768734), mainly for consistency/having less different "UI concepts" on the website.

But this is up for debate.

@sjtrimble: Any ideas?

**Comment by ajitsinghkaler** [comment]
@gkalpak Yeah we can add tabs but we have two levels of headings even then we may have to use something like this. 

Like for development, the education, the community we may use tabs but for the rest, we can use expansion panels.  What are your thoughts on this.

**Comment by gkalpak** [comment]
Let's take is one step at a time :smiley: 
I suspect splitting them up by the first level and then we can decide what to do on the second level if/when needed.

**Comment by sjtrimble** [comment]
I agree with @gkalpak - tabs would be great as we have on the https://angular.io/about page. 

I also suggest adding an "ALL" tab so that someone can easily search through something they are looking for in particular.

This would be a great next step and improvement from what we have.
