### ISSUE TITLE
Ivy: fullTemplateTypeCheck errors with noImplicitAny and null in function expressions

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#33528]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler

### Is this a regression?

This is introduced by Ivy

### Description

If a function expression in a template does a `null` affectation, than the template type-checking fails if `noImplicitAny` is used:

```html
<button (click)="title = null">Cancel</button>
```

## 🔬 Minimal Reproduction

https://github.com/cexbrayat/null-event

## 🔥 Exception or Error
<pre><code>
ERROR in src/app/app.component.html:1:18 - error TS7011: Function expression, which lacks return-type annotation, implicitly has an 'any' return type.

1 <button (click)="title = null">Cancel</button>
                   ~~~~~~~~~~~~

  src/app/app.component.ts:5:16
    5   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.0
Node: 12.12.0
OS: darwin x64
Angular: 9.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.0
@angular-devkit/build-angular     0.900.0-rc.0
@angular-devkit/build-optimizer   0.900.0-rc.0
@angular-devkit/build-webpack     0.900.0-rc.0
@angular-devkit/core              9.0.0-rc.0
@angular-devkit/schematics        9.0.0-rc.0
@ngtools/webpack                  9.0.0-rc.0
@schematics/angular               9.0.0-rc.0
@schematics/update                0.900.0-rc.0
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Comment by JoostK** [comment]
Nice find! This was introduced when checking of event bindings was added in #33125 and should be easy to fix.

**Comment by JoostK** [comment]
Ah, this wasn't caught during testing as it specifically requires `strictDomEventTypes`/`strictOutputEventTypes` to be `false` __and__ `strictNullChecks` to be `false`. I opened #33550 with a fix.
