### ISSUE TITLE
Consider changing the function expression into an exported function, Function expressions are not supported in decorators

### ISSUE THREAD

**Issue by GlauberF** [angular/angular#33539]
I have the following expression that is giving error.
```javascript
const monacoConfig: NgxMonacoEditorConfig = {
    onMonacoLoad: () => {
        (window as any).monaco = (window as any).monaco || null;
    }
};
```
he is returning this error

```
ERROR in Error during template compile of 'VimboEditorCodeModule'
  Function expressions are not supported in decorators in 'ɵ0'
    'ɵ0' contains the error at src/@vimbo/components/editor-code/editor-code.module.ts(16,19)
      Consider changing the function expression into an exported function.
```

how could i change the expression using the hint informed in the terminal.
remembering that, I care about it as follows.

```
@NgModule({
    declarations: [VimboEditorCodeComponent],
    imports: [
        MonacoEditorModule.forRoot(monacoConfig)
   ]
});
```

**Comment by AndrewKushnir** [comment]
@GlauberF it looks like `MonacoEditorModule.forRoot` function may have incomplete type, i.e. just `ModuleWithProviders` vs `ModuleWithProviders<MonacoEditorModule>`. Could you please check the `forRoot` function type? Thank you.

**Comment by GlauberF** [comment]
in forRoot, there's it:
```javascript
import { ModuleWithProviders } from '@angular/core';
import { NgxMonacoEditorConfig } from './config';
export declare class MonacoEditorModule {
    static forRoot(config?: NgxMonacoEditorConfig): ModuleWithProviders;
}

```

**Comment by JoostK** [comment]
@GlauberF what Andrew was hinting at is that `ModuleWithProviders` will start to need the type of the NgModule as a generic type argument:

```typescript
export declare class MonacoEditorModule {
    static forRoot(config?: NgxMonacoEditorConfig): ModuleWithProviders<MonacoEditorModule>;
}
```

But that is not the issue here. Also, since this may not be in your code but in a library, the library would need an update (but also this is not a requirement at this moment, so don't worry about it).

You should be able to make this work by exporting the logic:

```typescript
export function onMonacoLoad() {
    (window as any).monaco = (window as any).monaco || null;
}

const monacoConfig: NgxMonacoEditorConfig = {
    onMonacoLoad
};
```

**Comment by GlauberF** [comment]
Thanks

**Comment by JoostK** [comment]
Since the solution is already mentioned in the error:
```
      Consider changing the function expression into an exported function.
```
I'll go ahead and close this issue.
