### ISSUE TITLE
ng-if="myarray[index]" or binding like {{myarray[index]}} 

### ISSUE THREAD

**Issue by JugnuPathak** [angular/angular#3354]
how to use access array element  to ng-if?
in my scope i have :
scope.myarray = //my array
scope.index = //any index

should i use $interpolate ? I'm not finding any good example to do that??

**Comment by pkozlowski-opensource** [comment]
@JugnuPathak this is wrong repo, this one is for angular 2. Having said this, you should:
* use `myarray[index]` - did you try it?
* ask support questions using a dedicated channel in the future: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by JugnuPathak** [comment]
its throwing synstax error

**Comment by pkozlowski-opensource** [comment]
@JugnuPathak please ask the question using one of the indicated support channels (remember to add a live reproduce scenario using plunker or similar - this will greatly increase your chance of getting a meaningful answer).
