### ISSUE TITLE
Adding custom headers in HttpInterceptor do not work correctly.

### ISSUE THREAD

**Issue by PooyaDel** [angular/angular#33546]
Hi all, 
![image](https://user-images.githubusercontent.com/10491467/68067762-b5976e00-fd97-11e9-97ff-53a93e19ae3b.png)

Chrome : Version 78.0.3904.70 (Official Build) (64-bit) (also on edge)

Reporting a bug :

Simple scenario:

import { Injectable } from '@angular/core';
import { HttpInterceptor, HttpRequest, HttpHandler, HttpEvent } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable()
export class CustomHeaderInterceptor implements HttpInterceptor {
    constructor() { }
    intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        req = req.clone({
            setHeaders: {
                'api-key': 'API-XXXXXXXX'
            }
        });
        return next.handle(req);
    }
}
-----------------------------------------------
app.module.ts 

providers: [{ provide: HTTP_INTERCEPTORS, useClass: CustomHeaderInterceptor, multi: true },......],

and then request header looks like this :

![image](https://user-images.githubusercontent.com/10491467/68067735-66513d80-fd97-11e9-952b-ad36a39f05cc.png)

**Comment by trotyl** [comment]
HTTP headers can only be added to actually request (GET), not the preflight request (OPTIONS). If you have some question about what is a preflight request (OPTIONS) and how it works, please consider refer to MDN or StackOverflow.

**Comment by alxhub** [comment]
You're looking at the CORS preflight (`OPTIONS`) request, which is asking the server for permission to send the `api-keys` header as part of your real request. I believe the 403 means the server said no.
