### ISSUE TITLE
Support for providedIn: 'component'

### ISSUE THREAD

**Issue by dirkluijk** [angular/angular#33568]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/core

### Description

The existing behaviour of `@Injectable({ providedIn: 'root' )` is that whenever an injectable is needed, the provider is created and provided in the current root injector automatically.

We could do the same for component injectors.

### Describe the solution you'd like
```ts
@Injectable({ providedIn: 'component' })
class MyService {}

@Component()
class MyComponent {
  constructor(myService: MyService) {}
}
```

would be the same as:

```ts
@Injectable()
class MyService {}

@Component({ providers: [MyService] })
class MyComponent {
  constructor(myService: MyService) {}
}
```

Why would we need this? Well, some injectable services may be intended to use on component injectors. For example, if it has a dependency on the `ActivatedRoute` of the component. This way, you cannot forget to provide it on the component anymore.

So, the **intended use** of a service is more explicit.

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/18015, https://github.com/angular/angular/issues/31355

**Comment by dirkluijk** [comment]
Sorry, it seems I did not search good enough.
