### ISSUE TITLE
Configure the Router with json file

### ISSUE THREAD

**Issue by DavidGangel** [angular/angular#3357]
Hi,

I would like to know that is it possible to configure the Router data from a json file?
If yes a small example code would be very helpful how to achieve it.

Thank you.

**Comment by gdi2290** [comment]
yes and no

you can kinda do something like this

```es6
var jsonFile require('./jsonFile.json');


@Component({})
@View({})
@RouteConfig([
  convertValueToTypes(jsonFile)
])
```
but you don't have a reference to the types as well as importing them. If we were using ES5 then maybe we can do something more dynamic 

```es6
var jsonFileAsArray require('./jsonFileAsArray.json');


var App = ng.
  Component({}).
  View({}).
  RouteConfig(jsonFileAsArray.map(function(config) {
    config.component = ng[config.component];
    return config;
  }).
  Class({
    constructor: [func]
  });
```
I wouldn't use any of the hacks above though since you're probably looking for something like



```typescript
@Component({})
@View({})
class App {
  constructor(router: Router, http: Http) {

  }

  onInit() {
    this.routesObs = this.http.get('/someRoutesFile.json').subscribe({
      next(configs) {
        router.config(configs)
      }
    });
  }
  onDestroy() {
    this.routesObs.dispose();
  }
}
```

**Comment by DavidGangel** [comment]
Yes the last part is the nicest way to do it.
Is it possible to code that way with the latest alpha?

**Comment by gdi2290** [comment]
you're probably better off rendering the json file inside of the index page itself to save an ajax call
`index.html`
```html
<app></app>
<script>
System.import('app').then(function(main) {
  return main.bootstrap(<%- jsonServerRoutes %> );
});
</script>
```
I'm not sure if the router throws an error with `[router-link]` directive when something isn't defined and it's unable to generate the href

**Comment by mhevery** [comment]
This is for Issues. Please use Gitter for help/discussions
