### ISSUE TITLE
Typo in zone.js

### ISSUE THREAD

**Issue by hansottowirtz** [angular/angular#33579]
# 🐞 bug report

### Affected Package
zone.js

### Is this a regression?
No.

### Description
I was inspecting some angular source code and noticed that `vrdisplayconnected` was misspelled in https://github.com/angular/angular/blob/5eb7426216b1597cca3a7923cc714e59464fec89/packages/zone.js/lib/browser/property-descriptor.ts#L147
This should become `vrdisplayconnected`.

**Comment by JiaLiPassion** [comment]
Thanks, will fix it.
