### ISSUE TITLE
TypeError: Cannot set property 'nodeValue' of undefined

### ISSUE THREAD

**Issue by rgb4268** [angular/angular#33573]
I am using Angular with webcomponents and polyfills, and I get this error in Canary in dev tools

TypeError: Cannot set property 'nodeValue' of undefined
    at interpolateFnWatchAction 
    at interpolateFnWatcher
    at Object.watchGroupAction [as fn]
    at Scope.$apply 
    at done 
    at completeRequest
    at XMLHttpRequest.requestLoaded

This may be a bug?

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
