### ISSUE TITLE
HostBinding not resolving 'style.width.%'

### ISSUE THREAD

**Issue by conorlauer** [angular/angular#33576]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.2.0

### Description

 A clear and concise description of the problem...
HostBinding no longer seems to apply values when the selector is "style.width.%"

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.0-rc.0
Node: 12.7.0
OS: win32 x64
Angular: 9.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.0
@angular-devkit/build-angular     0.900.0-rc.0
@angular-devkit/build-optimizer   0.900.0-rc.0
@angular-devkit/build-webpack     0.900.0-rc.0
@angular-devkit/core              9.0.0-rc.0
@angular-devkit/schematics        9.0.0-rc.0
@ngtools/webpack                  9.0.0-rc.0
@schematics/angular               9.0.0-rc.0
@schematics/update                0.900.0-rc.0
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

Not sure if this is as designed, due to the "style.width.%" being a non-standard thing.

**Comment by atscott** [comment]
Hi @conorlauer, can you provide some more context? What other style bindings do you have on your element? Those may conflict with the `style.width.%`.

**Comment by conorlauer** [comment]
Thank you for your response, I do have a ```style.width.px``` which may be the conflict you are mentioning. I was just testing out an update and ran into this issue. 

**More context**
So I have two HostBinding variables (that I would assume may be in conflict):
```
@HostBinding('style.width.%') public componentWidthPercent: any = 100;
@HostBinding('style.width.px') public componentWidthPixel = '';
@HostBinding('style.flex-grow') public autoFill = 0;
```
The component should have a default width of 100% in this case, however there is a bit of code that resets the PIXEL, componentWidthPixel, variable if the option is passed:
```
        // Override width and heights pixels if autoFill === true
        if (styles.autoFill) {
          // this.componentWidthPercent = '';
          // this.componentHeightPercent = '';
          this.componentWidthPixel = '';
          this.componentHeightPixel = '';
          this.autoFill = 1;
        }
```
Notice how the componentWidthPercent is commented out and should not remove the default value for componentWidthPercent.

Prior to the 9.0.0-rc.0 version, this worked as mentioned above.

Can I set up stackblitz to use the latest 9.0.0 version?

**Comment by atscott** [comment]
Hey @conorlauer - it looks like stackblitz isn't currently able to run Angular with Ivy so that isn't an option. There are a lot of changes in Ivy with regards to how styling is applied but I'm wondering if your code only happened to coincidentally work in previous versions. How would you expect this to work when you're binding to width with both a percent and a px value? Maybe it should look something more like this:

```
@HostBinding('style.width')
bindHostWidth() {
  return this.componentWidthPixel ? `${this.componentWidthPixel}px` : `${this.componentWidthPercent}%`;
}

**Comment by conorlauer** [comment]
I think what you are saying makes sense. I was relying on the black magic of the current rendering process. I did expect that setting the componentWidthPixel would override what ever was defined in the componentWidthPercent. 

That being said, I think the solution you provide is more intuitive and does not rely on whatever either of the Rendering engines decides to do with it.

Thanks for your input, and I will close this issue.
