### ISSUE TITLE
v8 -> v9 Without Ivy bundle size increase

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular#33578]
# 🐞 bug report
When going from `8.0.0-rc.3` to `9.0.0.rc.1` I experienced a bundle size increase of roughly 10% with ivy disabled. 

![image](https://user-images.githubusercontent.com/2133184/68150335-7db23700-ff0d-11e9-8399-8f962e8333c6.png)

cc @StephenFluin

**Comment by StephenFluin** [comment]
Can you supply source map stats before and after to help us investigate?

**Comment by pkozlowski-opensource** [comment]
I believe that this one is obsolete - there were some rc releases where VE was accidentally pulling ivy code but AFAIK those were fixed. In anyone can reproduce this increase with the final version of v9 please open a new issue with a reproduce scenario. Thnx!
