### ISSUE TITLE
Cannot call GET api from second times 

### ISSUE THREAD

**Issue by dinhlambcs** [angular/angular#33589]
# 🐞 bug report

I want to call GET api every 10 seconds, but only the first time it was  called, from second times api not show in Network tab/ chrome. So I don't know whether angular interceptor block it?

If I create a button with  getNoti(), and click it when page loaded done, I can see my api called every 10s in Network tab, I don't know reason why.

## 🌍  Your Environment

Angular universal: 7.2.15
Rxjs: 6.5.2
@ngrx/store: "^7.4.0"

## 🔥 My code
In my notifications component,

``` 
ngOnInit() {
    this.loadStatus = this.store.pipe(select(selectLoadStatus));
    this.notifications = this.store.pipe(select(selectAllNotifications));
   // not call secondly if dispatch here
    let i = 0;
    timer(0, 10000).subscribe(() => {
      i++;
      console.log('call api n', i); // its called every 10s
      this.notificationsService.getNotifications().subscribe(data => {
        console.log('call api'); // its called every 10s, BUT Network tabs in Chrome just show one api 
      });
    });
  }
getNoti() {
   // when comment code in OnInit(), and click a button to run getNoti(), Network tabs show new api every 10s
     timer(0, 10000).subscribe(() => {
      this.notificationsService.getNotifications().subscribe(data => {
        console.log('call api'); // its called every 10s, Network tabs show new api every 10s
      });
    });
}
```
my notification html
```
<ng-container *ngIf="(loadStatus | async) === LoadStatus.loaded; else loading">
    <a *ngFor="let noti of notifications | async" class="notification">
       {{noti.title}}
    </a>
  </ng-container>
```

My service
```
getNotifications() {
    return this.httpClient.get(this.config.notification);
}
```
My error image link: https://i.stack.imgur.com/tKgbE.png
See my above image please, 20/125 request, 125 continue increasing, 20/130, 20/135, but number 20 didn't increase

**Comment by santoshyadav198613** [comment]
The code is related to ngrx please raise this in ngrx repo, or stackoverflow.
This is the repo: https://github.com/ngrx/platform/pull/2209

**Comment by dinhlambcs** [comment]
> The code is related to ngrx please raise this in ngrx repo, or stackoverflow.
> This is the repo: [ngrx/platform#2209](https://github.com/ngrx/platform/pull/2209)

hi @santoshyadav198613 I think it is angular's issue. I've updated my post

**Comment by dinhlambcs** [comment]
Sorry but I fixed this problem by adding a random params for method GET. I guess that Google Chrome are detecting auto call a api (GET) by scripts or event from users.
