### ISSUE TITLE
Support TypeScript 3.7

### ISSUE THREAD

**Issue by fr0** [angular/angular#33596]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description

TypeScript 3.7 was released today. It includes plenty of useful new features, like the optional chaining and nullish coalescing operators. Angular should support it.

**Comment by gkalpak** [comment]
Related PR: #32962

**Comment by filipesilva** [comment]
If you're using the framework/CLI RC and Ivy, you might be able to just use TypeScript 3.7 directly. You'll get a peer dependency warning but in all likelihood it'll just work. Ivy is far less sensitive to TypeScript version changed than View Engine. Let me know if you try this and run into problems.

**Comment by gligoran** [comment]
Any possibility this will be ready for the release of Angular 9?

**Comment by filipesilva** [comment]
Current thinking at the moment is within version 9, but after 9.0 proper.

**Comment by xiaoxiangmoe** [comment]
@filipesilva Will Angular 8 support ts 3.7 in the future?

**Comment by filipesilva** [comment]
@xiaoxiangmoe I'm not aware of plans to backport the changes needed to version 8. Generally only security fixes and very important bugs are fixed in older versions.

**Comment by xiaoxiangmoe** [comment]
Can we open `useDefineForClassFields` in Angular 9? @filipesilva

**Comment by filipesilva** [comment]
You can try, but that looks like it might cause some trouble... if you run into problems please let us know.

**Comment by alan-agius4** [comment]
Closing as Angular ` v9.0.0-rc.9` supports TypeScript version 3.7.

**Comment by filipesilva** [comment]
Support was added in https://github.com/angular/angular/pull/33717

**Comment by filipesilva** [comment]
Hey all,

Starting with `@angular/cli@9.0.0-rc.10` and `@angular/core@9.0.0-rc.9` you should be able to use TypeScript 3.7 with no problems, while 3.6 is also supported. Please let us know if something if you encounter any problems with the TS version..

**Comment by michaeljota** [comment]
@xiaoxiangmoe Did `useDefineForClassFields` work for you? I'm seeing a weird issue, and I think it's because of that.

**Comment by michaeljota** [comment]
I'll try to open another ticket with a reproducible repo but it seems like if you use `useDefineForClassFields` option will throw somehow if you have a service with a property defined but not initialized.

**Comment by xiaoxiangmoe** [comment]
@michaeljota Sorry, I haven't tried to turn on this option because we are busy with other things.
