### ISSUE TITLE
Transformer: Template are not inlined (?) when the class format is different?

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#3360]
Using the `identifier = base with mixin` is legal Dart, but the transformer doesn't seem to like it.

```dart
abstract class FooMixin {}
abstract class BarBase {}

@Component(
  selector: 'baz'
)
@View(
  template: 'package:baz/baz.html'
)
class BazComponent = BarBase with FooMixin;
```

This *does* work when you change slightly:

```dart
class BazComponent extends BarBase with FooMixin {}
```

**Comment by yjbanov** [comment]
This is a rare syntax and has an easy workaround, so dropping to P3.

**Comment by matanlurey** [comment]
Just ran into this again. Only 8 months later.
