### ISSUE TITLE
Placeholder texts in code examples of angular.io markdown content do not display in the browser

### ISSUE THREAD

**Issue by akaustav** [angular/angular#33612]
# 📚 Docs or angular.io bug report

### Description
Placeholder texts (enclosed inside angle brackets - like `<app-name>`) inside `<code-example></code-example>` tags on the markdown content for [angular.io](https://angular.io/guide/deployment#local-development-in-older-browsers) do not display on browsers. Instead they are treated as opening html tags without matching closing tags.

### What's the affected URL?

- [Configuring serve for ES5](https://angular.io/guide/deployment#configuring-serve-for-es5)
- [Configuring the e2e command](https://angular.io/guide/deployment#configuring-the-e2e-command)

### Reproduction Steps

1. Open the above affected URL(s) in any browser of your choice.
1. Scroll down till the paragraph which contains information about replacing `<app-name>` in the provided configuration. There are two instances:
   - **Instance 1** under [Configuring serve for ES5](https://angular.io/guide/deployment#configuring-serve-for-es5):
   > You can then run the `ng serve` command with this configuration. Make sure to replace `<app-name>` (in `"<app-name>:build:es5"`) with the actual name of the app, as it appears under `projects` in `angular.json`. For example, if your app name is `myAngularApp` the config will become `"browserTarget": "myAngularApp:build:es5"`.
   - **Instance 2** Under [Configuring the e2e command](https://angular.io/guide/deployment#configuring-the-e2e-command):
   > You can then run the `ng e2e` command with this configuration. Make sure to replace `<app-name>` (in `"<app-name>:serve:es5"`) with the actual name of the app, as it appears under `projects` in `angular.json`. For example, if your app name is `myAngularApp` the config will become `"devServerTarget": "myAngularApp:serve:es5"`.
1. Check the provided configuration above this paragraph for instances of `<app-name>`.

### Expected Behavior
I was hoping to find `<app-name>` somewhere in the provided configuration.

### Actual Behavior
I can NOT find any instances of `<app-name>` in the provided configuration.

## 📷Screenshot
Here is the screenshot for [Configuring serve for ES5](https://angular.io/guide/deployment#configuring-serve-for-es5) section:

![image](https://user-images.githubusercontent.com/11030959/68270434-7462c080-001a-11ea-9052-1db66e3a3025.png)

And here is the screenshot for [Configuring the e2e command](https://angular.io/guide/deployment#configuring-the-e2e-command) section:

![image](https://user-images.githubusercontent.com/11030959/68270649-3d40df00-001b-11ea-9520-f41780f8cf08.png)

### Browser info

This issue does NOT seem to be browser specific - it is reproducible in all of the following browsers which I have access to:

- **Device:** Laptop
- **Operating System:** Microsoft Windows 10 (version 1909)
- **Browsers:**
  - **Google Chrome** 78.0.3904.87 (Official Build) (64-bit)
  - **Microsoft Edge** 44.18362.449.0 (with EdgeHTML 18.18363)
  - **Mozilla Firefox** 71.0b7 (64-bit)

### Anything else relevant?
Tracing back the commit logs and older issues, I believe this problem was introduced in commit 9bbe67f which is part of PR #32210 meant for fixing documentation issue #32199.

**Comment by akaustav** [comment]
Tagging folks who (in my opinion) might know more about this issue:

- @devin5885 - created issue #32199
- @santoshyadav198613 - authored commit 9bbe67f and created PR #32210
- @matsko - merged PR #32210 into `master`
- @kapunahelewong - reviewed and approved PR #32210
- @gkalpak - reviewed and approved PR #32210

**Comment by santoshyadav198613** [comment]
Hi @akaustav ,
Let me take a look.

**Comment by santoshyadav198613** [comment]
I have made one small change looks like it is ignoring <> brackets, will update once a preview is available,
