### ISSUE TITLE
Error building Angular 9.0.0-rc.0 on windows 10

### ISSUE THREAD

**Issue by rgunczer** [angular/angular#33615]
# 🐞 bug report

C:\dev\angular-9.0.0-rc.0>yarn install -> success

Build log:

```
flanker@nitro MINGW64 /c/dev/angular-9.0.0-rc.0
$ ./scripts/build-packages-dist.sh
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to 'C:/users/flanker/_bazel_flanker/tvgsfriw/command.profile.gz'
INFO: Invocation ID: 839563b8-2d92-413b-adf9-4eaa5ab55f9e
INFO: Call stack for the definition of repository 'npm' which is a yarn_install (rule definition at C:/users/flanker/_bazel_flanker/tvgsfriw/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:385:16):
 - C:/users/flanker/_bazel_flanker/tvgsfriw/external/build_bazel_rules_nodejs/index.bzl:82:5
 - C:/dev/angular-9.0.0-rc.0/WORKSPACE:85:1
ERROR: An error occurred during the fetch of repository 'npm':
   yarn_install failed: $ node tools/yarn/check-yarn.js
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info @bazel/bazel-darwin_x64@1.0.0: The platform "win32" is incompatible with this module.
info "@bazel/bazel-darwin_x64@1.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @bazel/bazel-linux_x64@1.0.0: The platform "win32" is incompatible with this module.
info "@bazel/bazel-linux_x64@1.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @bazel/buildifier-darwin_x64@0.26.0: The platform "win32" is incompatible with this module.
info "@bazel/buildifier-darwin_x64@0.26.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @bazel/buildifier-linux_x64@0.26.0: The platform "win32" is incompatible with this module.
info "@bazel/buildifier-linux_x64@0.26.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @google-cloud/functions-emulator@1.0.0-beta.5: The engine "node" is incompatible with this module. Expected version "~6". Got "10.16.0"
info "@google-cloud/functions-emulator@1.0.0-beta.5" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.0.1: The platform "win32" is incompatible with this module.
info "fsevents@2.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
info If you think this is a bug, please open a bug report with the information provided in "C:\\dev\\angular-9.0.0-rc.0\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 (warning Resolution field "graceful-fs@4.2.2" is incompatible with requested version "graceful-fs@~3.0.2"
warning Resolution field "graceful-fs@4.2.2" is incompatible with requested version "graceful-fs@^3.0.0"
warning Resolution field "graceful-fs@4.2.2" is incompatible with requested version "graceful-fs@~1.2.0"
warning @angular-devkit/architect@0.900.0-next.15: The engine "pnpm" appears to be invalid.
warning @angular-devkit/core@9.0.0-next.15: The engine "pnpm" appears to be invalid.
warning @angular-devkit/build-optimizer@0.900.0-next.15: The engine "pnpm" appears to be invalid.
warning @angular-devkit/schematics@9.0.0-next.15: The engine "pnpm" appears to be invalid.
warning @angular/cli@9.0.0-next.15: The engine "pnpm" appears to be invalid.
warning @schematics/angular@9.0.0-next.15: The engine "pnpm" appears to be invalid.
warning @schematics/update@0.900.0-next.15: The engine "pnpm" appears to be invalid.
warning " > tsickle@0.37.0" has incorrect peer dependency "typescript@~3.5.3".
error An unexpected error occurred: "EPERM: operation not permitted, unlink 'C:\\dev\\angular-9.0.0-rc.0\\node_modules\\@bazel\\bazel-win32_x64\\bazel-1.0.0-windows-x86_64.exe'".
Process stalled
Active handles:
  - Socket
  - Socket
  - Socket
)
ERROR: no such package '@npm//': yarn_install failed: $ node tools/yarn/check-yarn.js
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info @bazel/bazel-darwin_x64@1.0.0: The platform "win32" is incompatible with this module.
info "@bazel/bazel-darwin_x64@1.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @bazel/bazel-linux_x64@1.0.0: The platform "win32" is incompatible with this module.
info "@bazel/bazel-linux_x64@1.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @bazel/buildifier-darwin_x64@0.26.0: The platform "win32" is incompatible with this module.
info "@bazel/buildifier-darwin_x64@0.26.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @bazel/buildifier-linux_x64@0.26.0: The platform "win32" is incompatible with this module.
info "@bazel/buildifier-linux_x64@0.26.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @google-cloud/functions-emulator@1.0.0-beta.5: The engine "node" is incompatible with this module. Expected version "~6". Got "10.16.0"
info "@google-cloud/functions-emulator@1.0.0-beta.5" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.0.1: The platform "win32" is incompatible with this module.
info "fsevents@2.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
info If you think this is a bug, please open a bug report with the information provided in "C:\\dev\\angular-9.0.0-rc.0\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 (warning Resolution field "graceful-fs@4.2.2" is incompatible with requested version "graceful-fs@~3.0.2"
warning Resolution field "graceful-fs@4.2.2" is incompatible with requested version "graceful-fs@^3.0.0"
warning Resolution field "graceful-fs@4.2.2" is incompatible with requested version "graceful-fs@~1.2.0"
warning @angular-devkit/architect@0.900.0-next.15: The engine "pnpm" appears to be invalid.
warning @angular-devkit/core@9.0.0-next.15: The engine "pnpm" appears to be invalid.
warning @angular-devkit/build-optimizer@0.900.0-next.15: The engine "pnpm" appears to be invalid.
warning @angular-devkit/schematics@9.0.0-next.15: The engine "pnpm" appears to be invalid.
warning @angular/cli@9.0.0-next.15: The engine "pnpm" appears to be invalid.
warning @schematics/angular@9.0.0-next.15: The engine "pnpm" appears to be invalid.
warning @schematics/update@0.900.0-next.15: The engine "pnpm" appears to be invalid.
warning " > tsickle@0.37.0" has incorrect peer dependency "typescript@~3.5.3".
error An unexpected error occurred: "EPERM: operation not permitted, unlink 'C:\\dev\\angular-9.0.0-rc.0\\node_modules\\@bazel\\bazel-win32_x64\\bazel-1.0.0-windows-x86_64.exe'".
Process stalled
Active handles:
  - Socket
  - Socket
  - Socket
)
INFO: Writing tracer profile to 'C:/users/flanker/_bazel_flanker/tvgsfriw/command.profile.gz'
INFO: Call stack for the definition of repository 'npm' which is a yarn_install (rule definition at C:/users/flanker/_bazel_flanker/tvgsfriw/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:385:16):
 - C:/users/flanker/_bazel_flanker/tvgsfriw/external/build_bazel_rules_nodejs/index.bzl:82:5
 - C:/dev/angular-9.0.0-rc.0/WORKSPACE:85:1
ERROR: An error occurred during the fetch of repository 'npm':
   yarn_install failed: $ node tools/yarn/check-yarn.js
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info @bazel/bazel-darwin_x64@1.0.0: The platform "win32" is incompatible with this module.
info "@bazel/bazel-darwin_x64@1.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @bazel/bazel-linux_x64@1.0.0: The platform "win32" is incompatible with this module.
info "@bazel/bazel-linux_x64@1.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @bazel/buildifier-darwin_x64@0.26.0: The platform "win32" is incompatible with this module.
info "@bazel/buildifier-darwin_x64@0.26.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @bazel/buildifier-linux_x64@0.26.0: The platform "win32" is incompatible with this module.
info "@bazel/buildifier-linux_x64@0.26.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @google-cloud/functions-emulator@1.0.0-beta.5: The engine "node" is incompatible with this module. Expected version "~6". Got "10.16.0"
info "@google-cloud/functions-emulator@1.0.0-beta.5" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.0.1: The platform "win32" is incompatible with this module.
info "fsevents@2.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
info If you think this is a bug, please open a bug report with the information provided in "C:\\dev\\angular-9.0.0-rc.0\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 (warning Resolution field "graceful-fs@4.2.2" is incompatible with requested version "graceful-fs@~3.0.2"
warning Resolution field "graceful-fs@4.2.2" is incompatible with requested version "graceful-fs@^3.0.0"
warning Resolution field "graceful-fs@4.2.2" is incompatible with requested version "graceful-fs@~1.2.0"
warning @angular-devkit/architect@0.900.0-next.15: The engine "pnpm" appears to be invalid.
warning @angular-devkit/core@9.0.0-next.15: The engine "pnpm" appears to be invalid.
warning @angular-devkit/build-optimizer@0.900.0-next.15: The engine "pnpm" appears to be invalid.
warning @angular-devkit/schematics@9.0.0-next.15: The engine "pnpm" appears to be invalid.
warning @angular/cli@9.0.0-next.15: The engine "pnpm" appears to be invalid.
warning @schematics/angular@9.0.0-next.15: The engine "pnpm" appears to be invalid.
warning @schematics/update@0.900.0-next.15: The engine "pnpm" appears to be invalid.
warning " > tsickle@0.37.0" has incorrect peer dependency "typescript@~3.5.3".
error An unexpected error occurred: "EPERM: operation not permitted, unlink 'C:\\dev\\angular-9.0.0-rc.0\\node_modules\\@bazel\\bazel-win32_x64\\bazel-1.0.0-windows-x86_64.exe'".
Process stalled
Active handles:
  - Socket
  - Socket
  - Socket
)
ERROR: no such package '@npm//': yarn_install failed: $ node tools/yarn/check-yarn.js
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info @bazel/bazel-darwin_x64@1.0.0: The platform "win32" is incompatible with this module.
info "@bazel/bazel-darwin_x64@1.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @bazel/bazel-linux_x64@1.0.0: The platform "win32" is incompatible with this module.
info "@bazel/bazel-linux_x64@1.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @bazel/buildifier-darwin_x64@0.26.0: The platform "win32" is incompatible with this module.
info "@bazel/buildifier-darwin_x64@0.26.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @bazel/buildifier-linux_x64@0.26.0: The platform "win32" is incompatible with this module.
info "@bazel/buildifier-linux_x64@0.26.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @google-cloud/functions-emulator@1.0.0-beta.5: The engine "node" is incompatible with this module. Expected version "~6". Got "10.16.0"
info "@google-cloud/functions-emulator@1.0.0-beta.5" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.0.1: The platform "win32" is incompatible with this module.
info "fsevents@2.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
info If you think this is a bug, please open a bug report with the information provided in "C:\\dev\\angular-9.0.0-rc.0\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 (warning Resolution field "graceful-fs@4.2.2" is incompatible with requested version "graceful-fs@~3.0.2"
warning Resolution field "graceful-fs@4.2.2" is incompatible with requested version "graceful-fs@^3.0.0"
warning Resolution field "graceful-fs@4.2.2" is incompatible with requested version "graceful-fs@~1.2.0"
warning @angular-devkit/architect@0.900.0-next.15: The engine "pnpm" appears to be invalid.
warning @angular-devkit/core@9.0.0-next.15: The engine "pnpm" appears to be invalid.
warning @angular-devkit/build-optimizer@0.900.0-next.15: The engine "pnpm" appears to be invalid.
warning @angular-devkit/schematics@9.0.0-next.15: The engine "pnpm" appears to be invalid.
warning @angular/cli@9.0.0-next.15: The engine "pnpm" appears to be invalid.
warning @schematics/angular@9.0.0-next.15: The engine "pnpm" appears to be invalid.
warning @schematics/update@0.900.0-next.15: The engine "pnpm" appears to be invalid.
warning " > tsickle@0.37.0" has incorrect peer dependency "typescript@~3.5.3".
error An unexpected error occurred: "EPERM: operation not permitted, unlink 'C:\\dev\\angular-9.0.0-rc.0\\node_modules\\@bazel\\bazel-win32_x64\\bazel-1.0.0-windows-x86_64.exe'".
Process stalled
Active handles:
  - Socket
  - Socket
  - Socket
)
Loading: 0 packages loaded

flanker@nitro MINGW64 /c/dev/angular-9.0.0-rc.0
$
```

**Comment by manklu** [comment]
Duplicate of https://github.com/bazelbuild/rules_nodejs/issues/894

**Comment by gkalpak** [comment]
Thx, @manklu. bazelbuild/rules_nodejs#894 is about fixing `rules_nodejs`, so let's keep this issue (#33615) to track getting this fixed in the angular project (i.e. updating `rules_nodejs` once it is fixed there).

**Comment by rgunczer** [comment]
Trying to compile the latest master on windows gives the following:

flanker@nitro MINGW64 /c/angular/angular (master)
$ node ./scripts/build-packages-dist.js
WARNING: Running Bazel server needs to be killed, because the startup options are different.
Starting local Bazel server and connecting to it...
C:/users/flanker/_bazel_flanker/ecq3zsps/execroot/angular/bazel-out/x64_windows-fastbuild/bin
##################################
scripts\build-packages-dist.js:
  Building @angular/* npm packages
  Mode: Production
##################################
Loading: 235 packages loaded
//packages/upgrade:npm_package
//packages/service-worker:npm_package
//packages/router:npm_package
//packages/platform-webworker-dynamic:npm_package
//packages/platform-webworker:npm_package
//packages/platform-server:npm_package
//packages/platform-browser-dynamic:npm_package
//packages/platform-browser:npm_package
//packages/localize:npm_package
//packages/language-service:npm_package
//packages/forms:npm_package
//packages/elements:npm_package
//packages/core:npm_package
//packages/compiler-cli:npm_package
//packages/compiler:npm_package
//packages/common:npm_package
//packages/bazel:npm_package
//packages/animations:npm_package
INFO: Call stack for the definition of repository 'local_config_cc' which is a cc_autoconf (rule definition at C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/
tools/cpp/cc_configure.bzl:143:15):
 - C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/cc_configure.bzl:179:5
 - C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/cc_configure.bzl:179:5
 - /DEFAULT.WORKSPACE.SUFFIX:392:1
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/cc_configure.bzl", line 120
                configure_windows_toolchain(<1 more arguments>)
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 690, in configure_windows_toolchain
                _get_msvc_vars(repository_ctx, <1 more arguments>)
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 503, in _get_msvc_vars
                _find_missing_vc_tools(<2 more arguments>)
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 387, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, <2 more arguments>)
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 367, in find_msvc_tool
                _get_vc_full_version(<2 more arguments>)
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 357, in _get_vc_full_version
                _get_latest_subversion(<2 more arguments>)
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 336, in _get_latest_subversion
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC (No such file or directory)
ERROR: C:/users/flanker/_bazel_flanker/ecq3zsps/external/io_bazel_skydoc/skydoc/BUILD:84:1: @io_bazel_skydoc//skydoc:skydoc depends on @local_config_cc//:cc-compiler-x64_win
dows in repository @local_config_cc which failed to fetch. no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/cc_configure.bzl", line 120
                configure_windows_toolchain(<1 more arguments>)
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 690, in configure_windows_toolchain
                _get_msvc_vars(repository_ctx, <1 more arguments>)
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 503, in _get_msvc_vars
                _find_missing_vc_tools(<2 more arguments>)
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 387, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, <2 more arguments>)
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 367, in find_msvc_tool
                _get_vc_full_version(<2 more arguments>)
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 357, in _get_vc_full_version
                _get_latest_subversion(<2 more arguments>)
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 336, in _get_latest_subversion
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC (No such file or directory)
ERROR: Analysis of target '//packages/bazel:npm_package' failed; build aborted: no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/cc_configure.bzl", line 120
                configure_windows_toolchain(<1 more arguments>)
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 690, in configure_windows_toolchain
                _get_msvc_vars(repository_ctx, <1 more arguments>)
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 503, in _get_msvc_vars
                _find_missing_vc_tools(<2 more arguments>)
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 387, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, <2 more arguments>)
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 367, in find_msvc_tool
                _get_vc_full_version(<2 more arguments>)
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 357, in _get_vc_full_version
                _get_latest_subversion(<2 more arguments>)
        File "C:/users/flanker/_bazel_flanker/ecq3zsps/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 336, in _get_latest_subversion
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC (No such file or directory)
INFO: Elapsed time: 3.824s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (231 packages loaded, 12170 targets configured)
child_process.js:655
    throw err;
    ^

Error: Command failed: yarn --cwd "C:\angular\angular" --silent bazel build --config=release --config=view-engine //packages/upgrade:npm_package //packages/service-worker:np
m_package //packages/router:npm_package //packages/platform-webworker-dynamic:npm_package //packages/platform-webworker:npm_package //packages/platform-server:npm_package //
packages/platform-browser-dynamic:npm_package //packages/platform-browser:npm_package //packages/localize:npm_package //packages/language-service:npm_package //packages/form
s:npm_package //packages/elements:npm_package //packages/core:npm_package //packages/compiler-cli:npm_package //packages/compiler:npm_package //packages/common:npm_package /
/packages/bazel:npm_package //packages/animations:npm_package
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at exec (C:\angular\angular\scripts\package-builder.js:106:18)
    at buildTargetPackages (C:\angular\angular\scripts\package-builder.js:68:3)
    at Object.<anonymous> (C:\angular\angular\scripts\build-packages-dist.js:16:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 12132,
  stdout: null,
  stderr: null
}

**Comment by basherr** [comment]
@jelbourn Any update on this since I am getting similar error. @rgunczer have you fixed the issue?

**Comment by rgunczer** [comment]
Here is the latest attempt.

$ node ./scripts/build/build-packages-dist.js
2020/11/28 21:37:44 Downloading https://releases.bazel.build/3.6.0/release/bazel-3.6.0-windows-x86_64.exe...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: Download from https://mirror.bazel.build/nodejs.org/dist/v12.14.1/node-v12.14.1-win-x64.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned
404 Not Found
C:/users/flan/_bazel_flan/f72tnigz/execroot/angular/bazel-out/x64_windows-fastbuild/bin
##################################
scripts\build\build-packages-dist.js:
  Building @angular/* npm packages
  Mode: Production
##################################
WARNING: Download from https://mirror.bazel.build/nodejs.org/dist/v12.14.1/node-v12.14.1-win-x64.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned
404 Not Found
Loading: 270 packages loaded
//packages/upgrade:npm_package
//packages/service-worker:npm_package
//packages/router:npm_package
//packages/platform-server:npm_package
//packages/platform-browser-dynamic:npm_package
//packages/platform-browser:npm_package
//packages/localize:npm_package
//packages/language-service:npm_package
//packages/forms:npm_package
//packages/elements:npm_package
//packages/core:npm_package
//packages/compiler-cli:npm_package
//packages/compiler:npm_package
//packages/common:npm_package
//packages/bazel:npm_package
//packages/animations:npm_package
WARNING: Download from https://mirror.bazel.build/nodejs.org/dist/v12.14.1/node-v12.14.1-win-x64.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned
404 Not Found
DEBUG: Rule 'com_google_protobuf' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1542334746 -0800"
DEBUG: Repository com_google_protobuf instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule git_repository defined at:
  C:/users/flan/_bazel_flan/f72tnigz/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Analyzed 16 targets (244 packages loaded, 20409 targets configured).
INFO: Found 16 targets...
ERROR: C:/users/flan/_bazel_flan/f72tnigz/external/com_google_protobuf/BUILD:85:11: C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed (Exit 1)

The target you are compiling requires Visual C++ build tools.
Bazel couldn't find a valid Visual C++ build tools installation on your machine.
Please check your installation following https://docs.bazel.build/versions/master/windows.html#using

INFO: Elapsed time: 143.021s, Critical Path: 80.30s
INFO: 340 processes: 244 internal, 11 local, 85 worker.
FAILED: Build did NOT complete successfully
child_process.js:674
    throw err;
    ^

Error: Command failed: yarn --cwd "C:\flanker\angular" --silent bazel build --config=release --config=view-engine //packages/upgrade:npm_package //packages/service-worker:npm_package //packages/router:npm_package
//packages/platform-server:npm_package //packages/platform-browser-dynamic:npm_package //packages/platform-browser:npm_package //packages/localize:npm_package //packages/language-service:npm_package //packages/for
ms:npm_package //packages/elements:npm_package //packages/core:npm_package //packages/compiler-cli:npm_package //packages/compiler:npm_package //packages/common:npm_package //packages/bazel:npm_package //packages/
animations:npm_package
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at exec (C:\flanker\angular\scripts\build\package-builder.js:128:18)
    at buildTargetPackages (C:\flanker\angular\scripts\build\package-builder.js:84:3)
    at Object.<anonymous> (C:\flanker\angular\scripts\build\build-packages-dist.js:18:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 4892,
  stdout: null,
  stderr: null
}

**Comment by martinsik** [comment]
I'm having the exact same issue on Windows 10 PRO with the latest master branch.

**Comment by vash72** [comment]
I'm having the same problem:

**Comment by rgunczer** [comment]
Closing the issue after +1.5 year...
