### ISSUE TITLE
Production build fails due to lazy loaded module from library

### ISSUE THREAD

**Issue by nandhaaas** [angular/angular#33622]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler

### Is this a regression?

 No

### Description

 Lazy loading a library module in app route is causing production build to fail

## 🔬 Minimal Reproduction

 
Lazy load a library modue in app route

<pre><code>
{
    path: 'pdl',
    loadChildren: () => import('@core/pdl').then(m => m.PdlModule)
}
</code></pre>

## 🔥 Exception or Error
<pre><code>

ERROR in ./src/app/app-routing.module.ts
Module not found: Error: Can't resolve './../../node_modules/@core/pdl/lib/pdl.module.d.ngfactory' in 'D:\DFC\Source\web\core\src\app'
resolve './../../node_modules/@core/pdl/lib/pdl.module.d.ngfactory' in 'D:\DFC\Source\web\core\src\app'
  using description file: D:\DFC\Source\web\core\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: D:\DFC\Source\web\core\node_modules\@core\pdl\package.json (relative path: ./lib/pdl.module.d.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\DFC\Source\web\core\node_modules\@core\pdl\lib\pdl.module.d.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\DFC\Source\web\core\node_modules\@core\pdl\lib\pdl.module.d.ngfactory.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        D:\DFC\Source\web\core\node_modules\@core\pdl\lib\pdl.module.d.ngfactory.tsx doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        D:\DFC\Source\web\core\node_modules\@core\pdl\lib\pdl.module.d.ngfactory.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\DFC\Source\web\core\node_modules\@core\pdl\lib\pdl.module.d.ngfactory.js doesn't exist
      as directory
        D:\DFC\Source\web\core\node_modules\@core\pdl\lib\pdl.module.d.ngfactory doesn't exist
[D:\DFC\Source\web\core\node_modules\@core\pdl\lib\pdl.module.d.ngfactory]
[D:\DFC\Source\web\core\node_modules\@core\pdl\lib\pdl.module.d.ngfactory.ts]
[D:\DFC\Source\web\core\node_modules\@core\pdl\lib\pdl.module.d.ngfactory.tsx]
[D:\DFC\Source\web\core\node_modules\@core\pdl\lib\pdl.module.d.ngfactory.mjs]
[D:\DFC\Source\web\core\node_modules\@core\pdl\lib\pdl.module.d.ngfactory.js]
 @ ./src/app/app-routing.module.ts 2:122-189
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

   
Angular CLI: 8.3.17
Node: 12.3.1
OS: win32 x64
Angular: 8.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.17
@angular-devkit/build-angular     0.803.17
@angular-devkit/build-optimizer   0.803.17
@angular-devkit/build-webpack     0.803.17
@angular-devkit/core              8.3.17
@angular-devkit/schematics        8.3.17
@angular/cdk                      8.2.3
@angular/cli                      8.3.17
@angular/material                 8.2.3
@ngtools/webpack                  8.3.17
@schematics/angular               8.3.17
@schematics/update                0.803.17
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Kindly see https://github.com/angular/angular-cli/issues/6373#issuecomment-533204545
