### ISSUE TITLE
COMPONENT_INITIALIZER

### ISSUE THREAD

**Issue by andreaslarssen** [angular/angular#33620]
# 🚀 feature request

### Relevant Package

This feature request is for @angular/core

### Description
In my case, I want to load a translation file each time a component is initialized, but this feature would enable you to do whatever you need to do before a component initializes. Much like APP_INITIALIZER.

### Describe the solution you'd like
I'd like access to a COMPONENT_INITIALIZER function that returns a promise.

### Describe alternatives you've considered
Not sure there are alternatives for my use case, but this issue is not just to cover my use case.

**Comment by spock123** [comment]
@andreaslarssen how about the component constructor? That's not early enough?

**Comment by andreaslarssen** [comment]
@spock123, no that's too late. The loading of the file takes longer than the component rendering.

**Comment by spock123** [comment]
@andreaslarssen how about resolve in the router?

https://angular.io/api/router/Resolve

**Comment by andreaslarssen** [comment]
@spock123: Won't fix my use case. I want to load translations when the component is initialized. Not all components have routes.

**Comment by Airblader** [comment]
The question is what do you want the rendering to do while the data is loading? Whatever the answer is, load the data in OnInit and display the answer in the meantime(?) That's true even if you want to display nothing at all.

**Comment by andreaslarssen** [comment]
@Airblader: You don't need to render anything. Handling this in OnInit would mean that you have to handle (in my case) the same thing in each and every component in the whole application. Uncle Bob would die. Also, OnInit won't wait for you. Which means you have to handle the GUI somehow.

**Comment by Airblader** [comment]
On the other hand making a request for each and every instance of every component sounds like a nightmare as well, doesn't it?

**Comment by andreaslarssen** [comment]
@Airblader: This issue isn't for my use case in particular. I'm sure there's other use cases than loading files. 

Having said that, loading a (local) translation file for each component (and caching them) when they first initialize is not a nightmare, no.

**Comment by spock123** [comment]
@andreaslarssen 
Why not call your file-fetching-stuff inside OnInit, let it return an observable, and just display your template when the observable is resolved? So in your template code:

```
<ng-container *ngIf="myInitObservableIsResolved | async">

<h1>Hi, I am the component template, and the file stuff has been fetched</h1>
</ng-container>
```

I do stuff like that all the time, I just dispatch an ngrx store action in my OnInit, which triggers the entire logic of doing whatever you need to do. The component just subscribes to the resolved observable exposed by the store.

This way you can reuse the same logic in any component you'd like.. just subscribe to the store observable, trigger the action in OnInit and update your template when the observable is resolved.

**Comment by andreaslarssen** [comment]
@spock123: That would mean I have to handle it in ALL OnInits, and it also means I would have to wrap ALL my templates with a ng-container. Ain't nobody got time for that.

Again, this issue is not really to solve my use case (which I've solved another way).

**Comment by spock123** [comment]
@andreaslarssen 

Even if you have a special COMPONENT_INITIALIZER you would still have to handle it inside the component. Are you suggesting that the COMPONENT_INITIALIZER should be called for EVERY component ??

**Comment by andreaslarssen** [comment]
Why would you have to handle this inside the component?

Yes and yes. 

I don't have hundreds of components.

**Comment by mlc-mlapis** [comment]
@andreaslarssen Long ping & pong. Could you describe your idea of COMPONENT_INITIALIZER more clearly? How should it work exactly and what API would it have?

**Comment by andreaslarssen** [comment]
@mlc-mlapis: It should work like APP_INITIALIZER, only for the components

**Comment by mlc-mlapis** [comment]
@andreaslarssen It's so vague formulation that I guess, nobody would seriously think about it. If you don't have enough time to do it, then it's hard to discuss.

As was mentioned before, APP_INITIALIZER works on a single app instance, but there are more different components and even more of their instancies.

**Comment by andreaslarssen** [comment]
@mlc-mlapis: I don't mean to be vague. What is it that's not clear?

**Comment by mlc-mlapis** [comment]
@andreaslarssen I know, how APP_INITIALIZER works in detail, but the still foggy idea, how it should work as COMPONENT_INITIALIZER. That's why the request for your more detailly described suggestion.

**Comment by andreaslarssen** [comment]
@mlc-mlapis: What is it that makes it not possible that it should work in the same way?

**Comment by mlc-mlapis** [comment]
@andreaslarssen I think, I already mentioned it.

>..., APP_INITIALIZER works on a single app instance, but there are more different components and even more of their instancies.

So the first thing would be to specify, what exactly COMPONENT_INITIALIZER is and how it's used to create that hook from the point of many different components and many of their instancies.

**Comment by andreaslarssen** [comment]
@mlc-mlapis: What different components are you thinking of, and how is that (and the potential of having several instances of them) an issue?

**Comment by mlc-mlapis** [comment]
@andreaslarssen Again, a lot of pings. Just start to show the syntax example, how COMPONENT_INITIALIZER looks like in a component context.

**Comment by mlc-mlapis** [comment]
@andreaslarssen Do you mean something like:

```
export function appInitServiceFactory(cmpInit: ComponentInitService): () => void {
	return () => cmpInit.load().then(...);
}

@Component({
	selector: '...',
	templateUrl: '...',
	providers: [
		ComponentInitService,
		{
			provide: COMPONENT_INITIALIZER,
			useFactory: componentInitServiceFactory,
			deps: [ComponentInitService],
			multi: true
		}
	]
})
```

**Comment by andreaslarssen** [comment]
@mlc-mlapis: Pings? Are you talking about the file fetching? That's an application specific implementation of translations, and even though that's what triggered my thoughts of having this feature, it has nothing to do with the actual feature request.

Yeah, something like that. If you want to define it on the component you want it to run for, or in app.module to trigger before any component initialisation is just a flavour. 

Much like a global component OnInit.

**Comment by mlc-mlapis** [comment]
@andreaslarssen Ah, then on module level it should be MODULE_INITIALIZER. For a component level you probably still need to define some new syntax extension, which allows you to control the exact conditions by which the hook should be active. You probably don't need to run all of them on each instance creation.

**Comment by andreaslarssen** [comment]
@mlc-mlapis: There's already an issue for a MODULE_INITIALIZER (#17606).

The though here was that if you need something to run on each instance creation (like a global OnInit w/ promise "support"), than this is what you'll use. But another version of it could be one that lets you decide which ones to run them for, that would probably also be helpfull.

**Comment by alxhub** [comment]
I don't believe this is something we will implement, as it would require making component instantiation asynchronous which would be a major change to Angular's rendering model.

An alternative might be to create a structural directive which could be applied to a component, that will first perform the necessary loading operation and then render the component.
