### ISSUE TITLE
How can a component use or inject an already rendered View

### ISSUE THREAD

**Issue by DavidGangel** [angular/angular#3362]
Hi,

Let's say the browser already has rendered the HTML and that contains a View which I would like to use in a component. Is this scenario supported at all?

Thank you.

**Comment by gdi2290** [comment]
I think you're trying to suggest server rendering in which case you can check out this video talking about that. The Client version of Angular replaces the view that was server rendered for security and performance reasons. If you're suggesting different scenarios then do you mind elaborating more

[![Server Rending Angular 2](http://img.youtube.com/vi/0wvZ7gakqV4/0.jpg)](http://www.youtube.com/watch?v=0wvZ7gakqV4)

if that works for you can you close the issue

**Comment by DavidGangel** [comment]
I watched the video and basically I would use it as I can then solve 2 issue at the same time.
But is this usable to decide I would like to try it out.
I have searched over the net but didn't find any example how to achieve it.
In the changelog I also don't see any mention.

Is this released at all in some alpha version?

Thank you.

**Comment by gdi2290** [comment]
it's hiding in plain sight at https://github.com/angular/universal and it's also not on npm. I can show you how it works and figure out your use cases if you want to close this and open an issue there we can chat more or on gitter

**Comment by DavidGangel** [comment]
I'm ready to give it a try now.

**Comment by gdi2290** [comment]
can you jump on chat via [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/angular/universal?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by DavidGangel** [comment]
Speaking on chat.

**Comment by gdi2290** [comment]
for context the use case is a CMS with a live preview
