### ISSUE TITLE
Data binding not working in Canary

### ISSUE THREAD

**Issue by rgb4268** [angular/angular#33635]
I have an Angular 1.3 app running. It works fine on Chrome. However, it does not render correctly in Canary v80. The following are snippets from my code - 

`<html>
            <paper-dropdown-menu >
                <paper-listbox class="dropdown-content" selected = "1">
                    <paper-menu class="menu" data-ng-model="abc" attr-for selected="name">
                        <paper-item name="{{gb}}" data-ng-repeat="a in abc">{{a}}</paper-item>
                    </paper-menu>
                </paper-listbox>
            </paper-dropdown-menu>
</html>
`

(This works fine if the data is something static)

In the controller file, I invoke a REST call to get the data 'abc'. I have verified by the debugger that the data is loaded correctly. 

In the drop-down, nothing shows. So data-ng-model is not loading data in time for the render. I get the stack trace below
TypeError: el.getPropertyInfo is not a function
    at http://127.0.0.1:9000/bower_components/ng-polymer-elements/ng-polymer-elements.js:196:39
    at Array.forEach (<anonymous>)
    at link (http://127.0.0.1:9000/bower_components/ng-polymer-elements/ng-polymer-elements.js:163:18)
...
   at compositeLinkFn (http://127.0.0.1:9000/bower_components/angular/angular.js:7143:13) <paper-menu class="menu ng-pristine ng-untouched ng-valid ng-isolate-scope" data-ng-model="abc" attr-for-selected="name" role="menu" tabindex="0">

This might be a polymer error I guess. Or polyfills. Just don't know how to fix this.

**Comment by rgb4268** [comment]
I don't know how to make the code show in the above. I just see a {{a}}

**Comment by ericmartinezr** [comment]
This repo is for angular, you're looking this one https://github.com/angular/angular.js.
