### ISSUE TITLE
Make @HostListener decorators in an inherited class not override @HostListener directives in a base class

### ISSUE THREAD

**Issue by elezar42** [angular/angular#33632]
This feature request is for @angular/core

Currently, if you have a @HostListener decorator for an event on a method in a base class, and a @HostListener decorator for the same event on a class that inherits from that base class, the one in the base class is overridden, and thus the base class's method is never added as an event listener. This does follow the inheritance semantics outlined at https://github.com/angular/angular/issues/11606#issuecomment-262315256. And while those semantics make sense for most decorators, I don't think they do for @HostListener. It's completely valid and not uncommon to want to have a base class and derived class both handle the same event. And if you _do_ want to override the base class's handling of the event, you can just create a method of the same name in the inherited class, without the decorator.

The best workaround I can come up with is to have the method in the inherited class call the method in the base class. But this is a maintenance nightmare. Any time a @HostListener is added to the base class, every derived class has to be checked to see if it's handling the same event, and if so, updated to call the new base class method. It really breaks the purpose of using events. It also requires the inherited class to know implementation details of the base class, which breaks one of the purposes of inheritance.

Here's a stackblitz showing how it currently works: https://stackblitz.com/edit/angular-hostlistener-inheritance

On a side note, is the inheritance semantics documented somewhere, or is that comment the only place to go to see how it's supposed to work? Knowing that information in advance would have saved me several hours of troubleshooting...

**Comment by jbjhjm** [comment]
A question closely related to the topic:
In Angular 9, if you redeclare a host listener method and add it's decorator, it will be called twice for each event:

```ts
export class BaseComponent {
  @HostListener('click')
  onClick() {
    console.log('Base click');
  }
}

export class ChildComponent extends BaseComponent {
  @HostListener('click')
  onClick() {
    console.log('Derived click');
  }
}
```
A click would result in logging "Derived click" twice. Is this the way it should work?

**Comment by gvamsilatha** [comment]
> A question closely related to the topic:
> In Angular 9, if you redeclare a host listener method and add it's decorator, it will be called twice for each event:
> 
> ```ts
> export class BaseComponent {
>   @HostListener('click')
>   onClick() {
>     console.log('Base click');
>   }
> }
> 
> export class ChildComponent extends BaseComponent {
>   @HostListener('click')
>   onClick() {
>     console.log('Derived click');
>   }
> }
> ```
> 
> A click would result in logging "Derived click" twice. Is this the way it should work?

Apparently Yes. I had the same issue. so in my case i removed the childcomponent hostlistener and it solved my problem.

**Comment by JoostK** [comment]
This is working in latest Angular, presumably since Ivy.
