### ISSUE TITLE
issue : in angular 2+ version "this" key world get conflict or overlap many times. If you use nested function or way out of from parent function.! In angular why they not create special key instance of 'this' key world which hold separate angular application scope for 'this'? Suggestion: In angular they can create special key world example: "ngThis"

### ISSUE THREAD

**Issue by JituG22** [angular/angular#33641]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

Thank you.
