### ISSUE TITLE
Support svg and browsers without `<template>` elements

### ISSUE THREAD

**Issue by tbosch** [angular/angular#3364]
In some cases we are serializing templates into strings (see #3356). Right now, this breaks SVG support as parsing them via `template.innerHTML` will not create the right nodes.

Also, Angular assumes in many places that browsers support the `<Template>` element. This breaks in e.g. IE10.

**Comment by tbosch** [comment]
For now we won't implement special cases for 2) and 3). However we should encapsulate the serialization and cloning into a central place so they are easy to add.

**Comment by tbosch** [comment]
Maybe: only do this for "bigger" ProtoViews with many nodes

**Comment by mhevery** [comment]
@tbosch  Will this still be a problem with the new compiler prototype?

**Comment by tbosch** [comment]
No, I don't think so. https://github.com/angular/angular/issues/3605

**Comment by mhevery** [comment]
Ok, let's close it with #3605

**Comment by mhevery** [comment]
obsolete
