### ISSUE TITLE
Sites angular.io and angularjs.org do not work!

### ISSUE THREAD

**Issue by KorolevvRoman** [angular/angular#33649]
Sites angular.io and angularjs.org do not work for about a week. Only with mobile. This situation is repeated regularly, once in half a year
Browser: Google Chrome 78.0.3904.87
Location: Russia

**Comment by gkalpak** [comment]
They definitely work for other people, so it sounds like a local/network issue.
I'm afraid there is not much we can do with more info (if at all).

I am going to close this issue, since it is not actionable for us, but feel free to continue the discussion below.
