### ISSUE TITLE
Lazy loading components does not load FormModule/ngModel unable to bind

### ISSUE THREAD

**Issue by neofuture** [angular/angular#33654]
# 🐞 bug report

### Affected Package
IVY/9/RC0

### Is this a regression?

no

### Description

I have set up a lazy load for a component as follows in V9 RC0

```
constructor(private cfr: ComponentFactoryResolver) {}

...

@ViewChild('viewContainer', {read: ViewContainerRef}) viewContainer: ViewContainerRef;

...

const {DemoComponent} = await import('../demo/demo.component');
const componentRef = this.viewContainer.createComponent(this.cfr.resolveComponentFactory(DemoComponent));
``` 

Which works and gets into the child view 

```
<ng-container #viewContainer></ng-container>
```

But if i try and use any `[(ngModel)]` in the lazy loaded component, i get the following issue 

```Can't bind to 'ngModel' since it isn't a known property of 'select'```

If i import the component in the app module it works as expected, but then its already pre loaded and does not lazy load

### 🔥 Exception or Error
<pre><code>
    ERROR in src/app/modules/contact-manager/contact-manager.component.html(12,9): error TS8002: Can't bind to 'ngModel' since it isn't a known property of 'select'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.0
Node: 12.2.0
OS: darwin x64
Angular: 9.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.0
@angular-devkit/build-angular     0.900.0-rc.0
@angular-devkit/build-optimizer   0.900.0-rc.0
@angular-devkit/build-webpack     0.900.0-rc.0
@angular-devkit/core              9.0.0-rc.0
@angular-devkit/schematics        9.0.0-rc.0
@angular/cdk                      8.2.3
@ngtools/webpack                  9.0.0-rc.0
@schematics/angular               9.0.0-rc.0
@schematics/update                0.900.0-rc.0
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Comment by neofuture** [comment]
Does anyone know a work around for this issue ?

**Comment by neofuture** [comment]
Since updating to rc6 this is now now returned as an error but now as a warning 

Can't bind to 'ngModel' since it isn't a known property of 'select'.

**Comment by neofuture** [comment]
I have created a repo to illustrate the issue 

https://github.com/neofuture/lazyload

**Comment by fkolar** [comment]
Please conside #34780 case as well, Where in this case we try to instantiate a component which using ngModel the #34780 is trying to bind it programatically.

**Comment by diogen737** [comment]
still having have the same issue  on rc11. here's my code:

```
    private async loadModule(input: any): Promise<void> {
        const module = await import('./charts/column-chart/column-chart.component');
        const cmpFactory = this._cmpResolver.resolveComponentFactory(module.ColumnChartComponent);
        const cmp = this.chartsContainer.createComponent(cmpFactory, 0, this._injector);
        cmp.instance.data = input;
        cmp.instance.ngOnChanges(null)
    }

```

**Comment by neofuture** [comment]
Still having the same issue with 

```
      const {DemoComponent} = await import('../components/utilities/demo/demo.component');
      const componentRef = viewContainer.createComponent(
        this.componentFactoryResolver.resolveComponentFactory(DemoComponent)
      );
      componentRef.instance.windowItem = windowItem;
```

**Comment by fkolar** [comment]
I think when you load component without this programatic API as you say it works. Does this mean that you first import Module that imports FormAPI? Here I would just make sure when working with DEMOComponent to create FormFactory that you also load all the other modules needed. I will be using this dynamic imports soon our our side as well. 

For components that has no dependencies its probably ok, for components that needs some other modules or even services depend..., I think better way is change it to :


1. You update your ComponentsModule, to have e.g. this renderComponent method
2. You dont `wait import... ` actual component but module from that component.
3. You pass in to the module current viewContainer and module using its renderComponent method will add it to the page. 


I will be dealing with the same soon. So I wonder if this will work? Also version nine has longer way to go I think, Untill it becames 9.1.x I dont thing will be stable enough to be used in prod env.

**Comment by neofuture** [comment]
Ive tried the component in a module and included the formAPI still get the same error

**Comment by levani132** [comment]
What if you inject injector in constructor of opener component and pass this.injector as third parameter of this.viewContainer.createComponent? So it follows like:

`constructor(private cfr: ComponentFactoryResolver, private injector: Injector) {}

...

@ViewChild('viewContainer', {read: ViewContainerRef}) viewContainer: ViewContainerRef;

...

const {DemoComponent} = await import('../demo/demo.component');
const componentRef = this.viewContainer.createComponent(this.cfr.resolveComponentFactory(DemoComponent), undefined, this.injector);`

So if the created component will have same injector as the creator I think it will have same modules imported too (as well as common module or forms module if you have it in your base module).

**Comment by diogen737** [comment]
@levani132 tried it, didn't work (see my comment [above](https://github.com/angular/angular/issues/33654#issuecomment-580580279))

**Comment by levani132** [comment]
I tried it and it doesn't work, but if you write this in the end of your demo.component.ts file

```
@NgModule({
  declarations: [DemoComponent],
  imports: [CommonModule]
})
class TestModule {
}
```

Then everything will work as you want it to. Though, isn't it possible to make loaded component use same imports as the opener?

**Comment by levani132** [comment]
> @levani132 tried it, didn't work (see my comment [above](https://github.com/angular/angular/issues/33654#issuecomment-580580279))

Oh, I see sorry, didn't see that line.

**Comment by maxstee** [comment]
Have this issue  on CLI 9.0.2
`Angular CLI: 9.0.2
Node: 10.15.3
OS: win32 x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2`

Error

`ERROR in src/app/configurations/openings/edit-opening/edit-opening.component.html:3:64 - error NG8004: No pipe found with name 'async'.

      3     <h4 class="modal-title" id="modal-title">{{ SelectedDate | async }}</h4>
                                                                       ~~~~~~

        src/app/configurations/openings/edit-opening/edit-opening.component.ts:7:18
          7     templateUrl: './edit-opening.component.html',
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          Error occurs in the template of component EditOpeningComponent.`

**Comment by maxstee** [comment]
Have the same issue on CLI 9.0.2

` ERROR in src/app/configurations/openings/edit-opening/edit-opening.component.html:3:64 - error NG8004: No pipe found with name 'async'.

      3     <h4 class="modal-title" id="modal-title">{{ SelectedDate | async }}</h4>
                                                                       ~~~~~~

        src/app/configurations/openings/edit-opening/edit-opening.component.ts:7:18
          7     templateUrl: './edit-opening.component.html',
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          Error occurs in the template of component EditOpeningComponent.`

**Comment by levani132** [comment]
> Have the same issue on CLI 9.0.2
> 
> ` ERROR in src/app/configurations/openings/edit-opening/edit-opening.component.html:3:64 - error NG8004: No pipe found with name 'async'.
> 
> ```
>   3     <h4 class="modal-title" id="modal-title">{{ SelectedDate | async }}</h4>
>                                                                    ~~~~~~
> 
>     src/app/configurations/openings/edit-opening/edit-opening.component.ts:7:18
>       7     templateUrl: './edit-opening.component.html',
>                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       Error occurs in the template of component EditOpeningComponent.`
> ```
```
@NgModule({
  declarations: [EditOpeningComponent],
  imports: [CommonModule]
})
class EditOpeningModule {
}
```

Try adding this lines in the end of the edit-opening.component.html

**Comment by mlc-mlapis** [comment]
@levani132 Yep. It should lead to the situation when the compiler recognizes `CommonModule` and if it is not imported in other code, then it would become a part of the lazy-loaded component itself.

**Comment by neofuture** [comment]
would be really nice if this worked

**Comment by ilyasKerbal** [comment]
@neofuture I am running into this problem. I can't get all my tests to pass.
```
    Can't bind to 'ngModel' since it isn't a known property of 'input'. ("card-content>
          <mat-form-field class="full-width">
            <input matInput placeholder="Title" [ERROR ->][(ngModel)]="currentProject.title" type="text" name="title">
          </mat-form-field>
          <mat-form-"): ng:///DynamicTestModule/ProjectsDetailsComponent.html@13:44
    Can't bind to 'ngModel' since it isn't a known property of 'textarea'. ("m-field>
          <mat-form-field class="full-width">
            <textarea matInput placeholder="Details" [ERROR ->][(ngModel)]="currentProject.details" name="details"></textarea>
          </mat-form-field>
          <sectio"): ng:///DynamicTestModule/ProjectsDetailsComponent.html@16:49
    Can't bind to 'ngModel' since it isn't a known property of 'mat-slider'.
    1. If 'mat-slider' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
    2. If 'mat-slider' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("ete</h4>
            <mat-slider class="full-width" min="0" max="100" thumbLabel name="percentComplete" [ERROR ->][(ngModel)]="currentProject.percentComplete"></mat-slider>
          </section>
          <section class="ful"): ng:///DynamicTestModule/ProjectsDetailsComponent.html@20:91
    Can't bind to 'ngModel' since it isn't a known property of 'mat-checkbox'.
    1. If 'mat-checkbox' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
    2. If 'mat-checkbox' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
.......
......
```

**Comment by neofuture** [comment]
Yes I still have the same issue in 10. would ne nice if we could properly lazy load components :(

**Comment by JoostK** [comment]
@neofuture Hi there, sorry for the long silence. I am looking at your reproduction and it appears that `BrokenComponent` is not declared in any NgModule, hence it won't be able to see any declarations (directives/components/pipes). So from that perspective, it appears to be behaving as expecting.

**Comment by neofuture** [comment]
Well I certainly have questions about how to make it work, I followed what Igor presented at angular connect on the lazy loading, I have some huge components and declaring them in the NgModule means they are not lazy, is there a way to lazy load the component and allocate it the ability to see the declarations ?

**Comment by JoostK** [comment]
@neofuture Let me try to go over it:

> declaring them in the NgModule means they are not lazy

Luckily, this isn't entirely accurate although I can most certainly see where the confusion comes from. Declaring a component in an NgModule does not necessarily mean they are not lazy. It all depends on how that NgModule is integrated in the full NgModule graph. Each NgModule can have imports and can be imported by other NgModules. The NgModules that are (transitively) imported from the root NgModule (typically `AppModule`) are _not_ lazy loaded, but the NgModules that are not referenced in this way will not be loaded until you load them. This is typically done today using `@angular/router` using the `loadChildren` idiom, where you load the NgModule form within a dynamic import, allowing it to be lazily loaded as the Router is asked to load those children.

So to have a component that is supposed to be lazily loaded _and_ use any declarations, you'd need an NgModule that declares the component and imports the necessary NgModules, _but is not imported into any other NgModule_. This allows the component to use the declarations that have become visible through the NgModule.

The tricky bit is what to do with that extra NgModule. In some situations, you could only lazily load the component without loading the NgModule that declares it, provided that you're using AOT compilations. During AOT compilation, the compiled component will have explicit references to the declarations that it actually uses, so the NgModule is not strictly necessary for the component to render. _However_, it could be that the NgModule is also used to provide additional providers for DI that were not already loaded into an `Injector` from `AppModule`. In that case, the NgModule must also be lazily loaded and instantiated to obtain its `Injector` which contains the registered providers. This is exactly how the Router operates, by the way.

The confusing part is how NgModules serve two purposes: declaration scopes and DI provider registration. In AOT compilations the scope information is not really needed, but the DI information may certainly be. Unfortunately it's almost impossible to know if a certain NgModule and the NgModules that it imports do register providers for DI purposes, so it's always guessing whether a component can be lazily imported without needing to load its NgModule as well.

More information can be found here: https://github.com/angular/angular/issues/35759#issuecomment-601444856

**Comment by neofuture** [comment]
Thank you for the excellent explanation, I think I understand that, however it doesn't help me understand how to do what I need to do, or if what I'm trying to do will be possible.

**Comment by neofuture** [comment]
Yes, so I can not do what I want too, I think lazy loading components is pretty much a a requirement for app optimisation, I was excited at angular connect when this was demo'ed. could you explain a way to lazy load a component and even if its maybe a future feature, or be able to assign the declarations in the component and outside of the module ?

**Comment by mlc-mlapis** [comment]
**@neofuture** Is it still the problem that if you lazy-load only a component, it's not able to load also all types of dependencies except providers because only them you are able to declare on that component level? If there are other parts, like pipes, other modules and so, you have to lazy-load a module and not that component itself?

**Comment by levani132** [comment]
> > Have the same issue on CLI 9.0.2
> > ` ERROR in src/app/configurations/openings/edit-opening/edit-opening.component.html:3:64 - error NG8004: No pipe found with name 'async'.
> > ```
> >   3     <h4 class="modal-title" id="modal-title">{{ SelectedDate | async }}</h4>
> >                                                                    ~~~~~~
> > 
> >     src/app/configurations/openings/edit-opening/edit-opening.component.ts:7:18
> >       7     templateUrl: './edit-opening.component.html',
> >                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> >       Error occurs in the template of component EditOpeningComponent.`
> > ```
> 
> ```
> @NgModule({
>   declarations: [EditOpeningComponent],
>   imports: [CommonModule]
> })
> class EditOpeningModule {
> }
> ```
> 
> Try adding this lines in the end of the edit-opening.component.ts @maxstee

@neofuture Why don't you use this approach? There's a clear explanation of why you can't use plain component (without declaring in module) as lazy loaded component by @JoostK, but as I see and as you really want to use it without of declaring it in any other modules just give the component its own module.

Also you can support my issue [here](https://github.com/angular/angular/issues/35545#issue-567404126) if you think this will be a good approach of doing what you want to do.

**Comment by neofuture** [comment]
WOW 

It is possible 

Component 

`
import {Component, Input, NgModule, OnInit} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {CommonModule} from '@angular/common';

@Component({
  selector: 'app-example',
  templateUrl: './example.component.html',
  styleUrls: ['./example.component.css']
})
export class ExampleComponent implements OnInit {
  @Input() windowItem;
  demo = 'Testing';

  constructor() { }

  ngOnInit(): void {
  }
}

@NgModule({
  imports: [
    FormsModule,
    CommonModule
  ],
  declarations: [ExampleComponent]
})

export class ExampleModule {}
`

Lazy loading
`
    import('../components/system/example/example.component').then(c => {
      const ngModuleFactory = this.compiler.compileModuleSync(c.ExampleModule);
      const ngModule = ngModuleFactory.create(viewContainer.injector);
      const factory = ngModule.componentFactoryResolver.resolveComponentFactory(c.ExampleComponent);
      componentRef = viewContainer.createComponent(factory);
      componentRef.instance.windowItem = windowItem;
    });
`
@JoostK you are a star thank you for giving me the solution, the forms work fine now, understanding is a great thing

It seems having a module declaration in the component that handles the declarations allow you to have the module definitions too, as you factory those in too, I probably didn't explain that right but I get the pattern now

**Comment by neofuture** [comment]
@levani132 awesome thank you I didn't read that until I went away and did what I did, but that's pretty much my solution, thank you for your comments and advice, what an awesome community 👍

**Comment by neofuture** [comment]
also thanks to @mlc-mlapis you are absolutely correct... thank you

**Comment by neofuture** [comment]
This is possible and is not a bug, with the kind explanations, there is a way to do this so this should be closed now
