### ISSUE TITLE
CLI Monorepo fails to build

### ISSUE THREAD

**Issue by gnomeontherun** [angular/angular#33659]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler-cli or @angular/cli

### Is this a regression?

 Yes, it used to build before Ivy.

### Description

Creating a new CLI project in a monorepo style, adding an application and a library, cannot build the application. It throws the same error as in https://github.com/angular/angular/issues/29361. It seems something about the configuration is wrong as generated by the CLI, though our project follows the same patterns and has the same errors (https://github.com/gnomeontherun/clarity/tree/angular9).

I opened a previous issue https://github.com/angular/angular/issues/33482 which is the same problem, but it was closed. @alxhub provided a fix, but testing his repository throws a different error so it really isn't fixed or working as far as I can tell.

Alex also has a draft of notes about some build notes here https://hackmd.io/zhu28RUcRiaG0DZq5bLy1A?view. 

## 🔬 Minimal Reproduction

I made a CircleCI job that runs a few CLI commands to generate a project, manually add the library to the application, then try to build.

https://github.com/gnomeontherun/monorepo-library-errors

It has an artifact you can download with the result of the build: https://19-219057101-gh.circle-artifacts.com/0/home/circleci/project/artifact.tar

## 🔥 Exception or Error
<pre><code>
ERROR in Unable to write a reference to SharedComponent in /home/circleci/project/monorepo/projects/shared/src/lib/shared.component.ts from /home/circleci/project/monorepo/projects/shared/src/lib/shared.module.ts
</code></pre>

## 🌍  Your Environment

The job loads the current @next tags.

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.0
Node: 10.16.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.0-rc.0
@angular-devkit/core         9.0.0-rc.0
@angular-devkit/schematics   9.0.0-rc.0
@schematics/angular          9.0.0-rc.0
@schematics/update           0.900.0-rc.0
rxjs                         6.5.3
</code></pre>

**Anything else relevant?**

**Comment by kuncevic** [comment]
I guess that would reproduce the error https://github.com/kuncevic/angular9-multi-app

Was being recently playing with 9 ☝️ but that 👇🏻:
`ERROR in Unable to write a reference to SharedLibComponent in /Users/A/Work/Projects/tmp/angular9-multi-app/projects/shared-lib/src/lib/shared-lib.component.ts from /Users/A/Work/Projects/tmp/angular9-multi-app/projects/shared-lib/src/lib/shared-lib.module.ts`
