### ISSUE TITLE
Error during serve in RC.1

### ISSUE THREAD

**Issue by Aw3same** [angular/angular#33655]
# 🐞 bug report

### Is this a regression?

Yes, without ivy engine everything works as expected (v8.2.13).

### Description

With the intention of preventing the possible problems of migrating our application to the aversion 9, we tried to migrate the application to version rc.1 by running the script :

<code>ng update @angular/cli @angular/core --next --force</code>

Migration and install works fine. When I execute <code>ng s</code> I receive a ton of errors (many of them related to @angular/components).

I've been searching among the issues something related, and I've applied this: 

<code>   
"angularCompilerOptions": {
    "fullTemplateTypeCheck": false,
    "ivyTemplateTypeCheck": false,
    "strictInjectionParameters": false
  }
</code>

If I set _fullTemplateTypeCheck_ to true, I receive errors like : 

<pre><code>
  src/app/pages/titularidades/components/suministros/components/tabla-sum/tabla-sum.component.ts:10:15
    10  templateUrl: './tabla-sum.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component TablaSumComponent.
src/app/pages/titularidades/components/suministros/components/tabla-sum/tabla-sum.component.html:104:16 - error TS8002: Can't bind to 'pageSizeOptions' since it isn't a known property of 'mat-paginator'.
1. If 'mat-paginator' is an Angular component and it has 'pageSizeOptions' input, then verify that it is part of this module.
2. If 'mat-paginator' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

104 <mat-paginator [pageSizeOptions]="[10, 20, 30]" showFirstLastButtons></mat-paginator>

</code></pre>

If I set _ivyTemplateTypeCheck_ to true, I receive errors like : 

<pre>
<code>
  src/app/core/layout/components/menu-usuario/menu-usuario.component.ts:15:15
    15  templateUrl: './menu-usuario.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component MenuUsuarioComponent.
src/app/core/layout/components/page-top/page-top.html:31:11 - error TS8001: 'info-version' is not a known element:
1. If 'info-version' is an Angular component, then verify that it is part of this module.
2. If 'info-version' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
</code>
</pre>

With all flags set to true, the amount of errors decreases, but I still have many like:

<pre><code>src/app/core/layout/layout.module.ts:61:14 - error TS-996002: Appears in the NgModule.imports of PageNotFoundModule, but itself has errors>/code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.0-rc.0
Node: 13.0.1
OS: win32 x64
Angular: 9.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.0
@angular-devkit/build-angular     0.900.0-rc.0
@angular-devkit/build-optimizer   0.900.0-rc.0
@angular-devkit/build-webpack     0.900.0-rc.0
@angular-devkit/core              9.0.0-rc.0
@angular-devkit/schematics        9.0.0-rc.0
@angular/cdk                      8.2.3
@angular/cli                      9.0.0-rc.0
@angular/material                 8.2.3
@ngtools/webpack                  9.0.0-rc.0
@schematics/angular               9.0.0-rc.0
@schematics/update                0.900.0-rc.0
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

I check all the possibles errors in files and I can't see anything.

**Comment by IgorMinar** [comment]
can you please specify what errors you got with your initial `angularCompilerOptions` settings and what these settings were?

`ivyTemplateTypeCheck` is not a public flag, so please don't rely on it. For the list of supported flags please see: https://next.angular.io/guide/template-typecheck

But again, we'd love to know what your original settings were and what the original errors were.

**Comment by Aw3same** [comment]
Hi Igor,
We have an application  developed since version 4, and we've been migrating it over the releases. At first, we didn't have _angularCompilerOptions_ , so we decide to create a new project in v8, see what are the default configuration for a new project and update the information we've lost.

We've include this _angularCompilerOptions_:
<pre><code>
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
</code></pre>


Furthermore, the previous team (which was the owner of this application) decided to include _PrimeNG_, but no in a typical way (they downloaded the node module and included it as a resource in `src/app/core/layout/components/primeng`). Something related to this is the first error:

- We have many errors like this:
`ERROR in src/app/core/layout/components/primeng/dialog/dialog.d.ts:110:22 - error TS-996002: Appears in the NgModule.imports of LayoutModule, but could not be resolved to an NgModule class`

- After that, we have errors with third party librarires. We don't worry about that (yet):

<code>src/app/app.component.html:3:3 - error TS8001: 'ngx-spinner' is not a known element:
1. If 'ngx-spinner' is an Angular component, then verify that it is part of this module.
2. If 'ngx-spinner' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
<ngx-spinner name="SpinnerNgxGeneral" [fullScreen]="false" bdColor="rgba(51,51,51,0.0)" size="large" color="#E75F00" type="ball-scale-pulse">LOADING</ngx-spinner>
</code>

- But reading across the errors, we've found some 'weird' things:
<code>
 src/app/app.component.ts:8:15  templateUrl: './app.component.html',
   Error occurs in the template of component AppComponent.
src/app/app.component.html:7:1 - error TS8001: 'router-outlet' is not a known element:

1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

<router-outlet></router-outlet>
</code>

- I don't want to give an example of every error, but we have it with custom components. with `angular/components`( `mat-paginator`,`mat-tab-group`..). Generally, errors are : 
- **TS8001** -> `src/app/pages/maintenance/maintenance.component.html:100:9 - error TS8001: 'mat-card' is not a known element` 
- **TS8002** -> `src/app/pages/maintenance/list-inmuebles/components/lista-derechos/lista-derechos.component.html:42:58 - error TS8002: Can't bind to 'hidePageSize' since it isn't a known property of 'mat-paginator'.`

We do not know if it is a project or ivy issue. In v8 it works fine.

**Comment by Aw3same** [comment]
We have advanced in the development of this error. Since in the first instance the library added as a resource (`src/app/core/layout/components/primeng`) gave problems, we have decided to remove it.

The result is that we no longer have any compilation errors. With the default options included in the previous comment, the result of executing ng s is:

<pre><code>
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
</code></pre>
![image](https://user-images.githubusercontent.com/10500082/68588859-cc6e4c80-048a-11ea-9729-ecf0e897413e.png)

However, the application still does not work. Although the compilation is correct, in `localhost: 4200 `does not appear well. We receive this error in console:

<pre><code>
main.ts:10 Error: Cannot instantiate cyclic dependency! ApplicationRef
    at throwCyclicDependencyError (core.js:7887)
    at R3Injector.hydrate (core.js:18268)
    at R3Injector.get (core.js:18034)
    at injectInjectorOnly (core.js:774)
    at Module.ɵɵinject (core.js:784)
    at Function.Overlay_Factory [as ɵfac] (ngx-toastr.js:478)
    at Object.factory (ngx-toastr.js:479)
    at R3Injector.hydrate (core.js:18272)
    at R3Injector.get (core.js:18034)
    at injectInjectorOnly (core.js:774)
</code></pre>

We hope it is an error related to a third-party library (`ngx-toastr`).

**Comment by Aw3same** [comment]
Finally we got it. The cyclic dependencie was caused by a provider declaration in `core.module.ts`. changing this:
<code>
  providers: [
    {
      provide: ErrorHandler,
      useClass: GlobalErrorHandler,
    },
    /**...*/
  ]
</code>

To this:
<code>
  providers: [
    GlobalErrorHandler,
    /**...*/
  ]
</code>

The cyclic dependencie dissapears.
