### ISSUE TITLE
i18n ICU expressions in Universal/App-Shell - ERROR ReferenceError: document is not defined

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#33651]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?

Yes, works with VE.

### Description
In the CLI @clydin enabled some further tests in the CLI and i18n. Server tests are now failing when using anything which is dependent on ICU expressions such as plural. The culprit seems to be that Ivy i18n relies on the document global rather than the standard way to get the document via the DI token. This will break in universal and app-shell because document as a global doesn't exist, and it will fail with `ERROR ReferenceError: document is not defined`

## 🔬 Minimal Reproduction
Use i18n ICU expressions in universal or app-shell scenario.

## 🔥 Exception or Error
ERROR ReferenceError: document is not defined
</code></pre>

## 🌍  Your Environment

**Angular Version:**
9.0.0-rc.0

**Anything else relevant?**
Exception is thrown from:

https://github.com/angular/angular/blob/10583f951d57bbc74cb70c49e58c6659a1b4662c/packages/core/src/render3/i18n.ts#L1183

Posted also in #fw-i18n

**Comment by petebacondarwin** [comment]
@mhevery 's suggestion:

>>>
1) Make InertBodyHelper constructor optional for document
2) In InertBodyHelper if document is not passed it it should try to look for it by probing the global space.
3) First look for createHTMLDocument and if found call it
4) Second look for document and use it to build innert document like now.
5) Lastly it should throw an error saying that it looked for those two places did not find anything and is giving up. It should than point to  some instructions on what it expects to be there.

**Comment by petebacondarwin** [comment]
An alternative idea ...

Move `getDOM()` and `setDOM()` to `@angular/core` (they are currently in `@angular/common` ).
Then we can do getDOM().createHtmlDocument(); in the sanitiser. 
And it is up to the current `platform` to call `setDOM()` with the appropriate `DomAdapter`.

**Comment by petebacondarwin** [comment]
New idea discussed offline with @mhevery :

```ts
import {setDocumentFactory} from '@angular/core';
setDocumentFactory(() => ...);
```

etc

**Comment by petebacondarwin** [comment]
Final idea: define `setDocument()` and `getDocument()` method for ivy.

* Use `getDocument()` wherever ivy needs a global `document` object.
* Use `setDocument()` in each of the platform packages to set the appropriate `document` value.

E.g.

```ts
  const inertBodyHelper = new InertBodyHelper(getDocument());
```

and

```ts
function _document(injector: Injector) {
  let config: PlatformConfig|null = injector.get(INITIAL_CONFIG, null);
  const document = config && config.document ? parseDocument(config.document, config.url) :
                                               getDOM().createHtmlDocument();
  // Tell ivy about the global document
  ɵsetDocument(document);
  return document;
}
```
