### ISSUE TITLE
Missing 'BrowserAnimationsModule' import in Routing documentation step 3

### ISSUE THREAD

**Issue by jsadowski** [angular/angular#33665]
# 📚 Docs or angular.io bug report

### Description

Hello there. On the page https://angular.io/guide/router#milestone-3-wrap-up there is one missing import in app.module.ts file available among all changed files for step 3. 

For making included files to be working as a whole example, app.module.ts should have:
```
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
```
as well as below one:
```
imports: [
   /* ... */
    BrowserAnimationsModule,
   /* ... */
],
```

### What's the affected URL?
https://angular.io/guide/router#milestone-3-wrap-up

### Reproduction Steps
1. Click on the link above.
1. Navigate to the section of all changed files for 3rd milestone.
1. See that app.module.ts file has no BrowserAnimationsModule imported (which btw is highlighted in https://angular.io/guide/router#adding-animations-to-the-routed-component)

### Expected vs Actual Behavior
app.module.ts should have BrowserAnimationsModule imported in the summary of milestone 3

**Comment by kapunahelewong** [comment]
Thanks for the specifics, @jsadowski. They helped me pinpoint where to edit. Would you like to take a look at the PR to make sure I've addressed the issue appropriately? https://pr33740-d984c67.ngbuilds.io/guide/router#milestone-3-wrap-up

**Comment by jsadowski** [comment]
Hi @kapunahelewong . It looks good to me. I would add an empty line after 'import' statement to stick with formatting convention of other module files and all will be set. Thanks.
