### ISSUE TITLE
Locale Regression: 150 locales purged

### ISSUE THREAD

**Issue by doom777** [angular/angular#33681]
# 🐞 bug report

### Affected Package
common

### Is this a regression?
Yes, caused by #33634

 Yes, the previous version in which this bug was not present was: ....

### Description
Switiching to cldr-data pulled in a slim availableLocales file, which ends up bringing only 370 locales instead of 526.
 A clear and concise description of the problem...
extract.js used to download locale data, and then load it into cldr-js. PR #33634 outsourced this work to an existing library `cldr-data`. Unfortunately, the availableLocales file in cldr-data does not have all the locales we had previously, about 1/4 of the locales are now not being generated. 

## 🔬 Minimal Reproduction
Delete packages/common/locales directory, and run  `yarn gulp cldr:extract`
You will see only 374 locales. Testing will also fail, since some unit tests depend on the purged locales.

**Comment by doom777** [comment]
@petebacondarwin @atscott

**Comment by petebacondarwin** [comment]
Ouch! Do we know if it is because the npm library does not contain those locales?

cc @josephperrott

**Comment by doom777** [comment]
Ok, I figured it out. It's the difference between modern and main. We can fix it, by adding a flag to our package.json

**Comment by petebacondarwin** [comment]
Fixed by #33682 - thanks @doom777
