### ISSUE TITLE
zone.js attaches some enumerable properties elements

### ISSUE THREAD

**Issue by sod** [angular/angular#33692]
zone.js 0.10.2

zone.js attaches some `enumerable: true` properties to elements with event listeners attached like `__zone_symbol__clickfalse` in case of a `click` listener.

## 🔬 Minimal Reproduction

Go to https://angular.io, select the search field with the element inspector, then `JSON.stringify($0, null, 2)`

you see:

![image](https://user-images.githubusercontent.com/905328/68489492-7e1d3b80-0247-11ea-98d1-b88f188a0935.png)

There are a lot more keys, but the other ones are properly attached as `enumerable: false`
![image](https://user-images.githubusercontent.com/905328/68489586-b15fca80-0247-11ea-97fc-bab52903f0e4.png)

**Comment by sod** [comment]
Seems to be added in 

https://github.com/angular/angular/blob/c7542a1d09b27b027a0367a1f3732a908cdd617a/packages/zone.js/lib/common/events.ts#L421

Shouldn't that read:

```typescript
Object.defineProperty(target, symbolEventName, {value: existingTasks = []});
```

?

**Comment by JiaLiPassion** [comment]
Thanks for posting the issue, yeah, it maybe more reasonable that those property become `not enumerable`, but I just a little worried about such kind of change may break some applications, because some application may hack the `zone.js` to get the `event delegates` by looping the `properties`.
