### ISSUE TITLE
debugElement.properties with ivy differ from debugElement.properties without ivy

### ISSUE THREAD

**Issue by nmatushevskiy** [angular/angular#33695]
# 🐞 bug report

### Affected Package
The issue is caused by package angular/core

### Is this a regression?
Yes, the previous version in which this bug was not present was: 9.0.0-rc.1 without ivy.

### Description
In unit test i have ```<input type="radio" />``` and want to get some property (in my case, it's "checked") by debugElement.properties. Without ivy this code works fine:

The component:
```
@Component({
  selector: 'app-root',
  template: `<input type="radio" value="one" [(ngModel)]="active"/>`
})
export class AppComponent {
  active = 'one';
}
```

The unit test:
```
it('issue example', () => {
    console.log('debugElement properties', debugElement.query(By.css('input[type="radio"]')).properties);
    console.log('debugElement properties checked', debugElement.query(By.css('input[type="radio"]')).properties.checked);
    console.log('nativeElement checked', debugElement.query(By.css('input[type="radio"]')).nativeElement.checked);

    expect(debugElement.query(By.css('input[type="radio"]')).properties.checked).toBeDefined();
    expect(debugElement.query(By.css('input[type="radio"]')).properties.checked).toBe(true);

    expect(debugElement.query(By.css('input[type="radio"]')).nativeElement.checked).toBe(true);
  });
```
logs:
<img width="600" alt="Снимок экрана 2019-11-08 в 18 20 09" src="https://user-images.githubusercontent.com/56971144/68491345-bb8bc400-025b-11ea-9e68-8f1dad195a77.png">

If ivy enable, same code will be work differently.
logs:
<img width="662" alt="Снимок экрана 2019-11-08 в 18 19 32" src="https://user-images.githubusercontent.com/56971144/68492626-6ac89b00-025c-11ea-97f4-6f96b3c0a5ac.png">

the first two tests fail.

## 🔬 Minimal Reproduction

github: https://github.com/nmatushevskiy/ivy-debug-element-properties-issue

* clone repository
* npm i
* ng test

unit test with issue you can find in: https://github.com/nmatushevskiy/ivy-debug-element-properties-issue/blob/master/src/app/app.component.spec.ts

## 🌍  Your Environment
```
Angular CLI: 9.0.0-rc.1
Node: 10.16.0
OS: darwin x64
Angular: 9.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.1
@angular-devkit/build-angular     0.900.0-rc.1
@angular-devkit/build-optimizer   0.900.0-rc.1
@angular-devkit/build-webpack     0.900.0-rc.1
@angular-devkit/core              9.0.0-rc.1
@angular-devkit/schematics        9.0.0-rc.1
@ngtools/webpack                  9.0.0-rc.1
@schematics/angular               9.0.0-rc.1
@schematics/update                0.900.0-rc.1
rxjs                              6.3.3
typescript                        3.6.4
webpack                           4.41.2

**Comment by pkozlowski-opensource** [comment]
Hmmmmm, I don't see the `FormsModule` being imported in your test (I guess the `checked` property is set by `ngModel`). I find it surprising that it used to with VE...

**Comment by nmatushevskiy** [comment]
FormsModule imported into AppModule, which imported in my test.
