### ISSUE TITLE
quickstart missing essential information

### ISSUE THREAD

**Issue by ppbrown** [angular/angular#33696]
As someone new to angular, I have a fresh perspective to share with you folks.
Your "quickstart documentation" is missing one crucial step:

HOW TO INSTALL ANGULAR/ng  
:-/

Usually that sort of info is the first item on such guides.

I'm not a js developer. I dont WANT to be a developer. I'm just trying to deploy a project that says it needs angular to run.

**Comment by StephenFluin** [comment]
Hey there! Can you clarify where you were looking for this content (such as the URL), so we can use this to improve the docs? I'm guessing you are referring to https://angular.io/start, is that right?

If you aren't looking to become an Angular developer, but just need to be able to build an existing project, you can check out our local setup instructions: https://angular.io/guide/setup-local

**Comment by ppbrown** [comment]
yes that is correct.
there are actually multiple places that talk about a quickstart but they
all seem to redirect to that url

maybe you would want to have a separate user vs developer quickstart doc.

**Comment by StephenFluin** [comment]
I'm going to close this issue, but can you elaborate on what you mean by user vs developer? Most users only access applications via the browser, and most developers need to know about things like Templates and Components. Can you share more about your needs?

**Comment by ppbrown** [comment]
developers are people who are probably already familiar with node.js and
probably want to tweak stuff in the code, even

users are people like me who don’t know anything about node.js, npm and
don’t want to know. They Just Want to Use an Application.

for what it’s worth: i’ve been programming and been a sysadmin for 30
years.
C. php. perl. java.
 so i’m relatively tech savvy. but i don’t write node code.
i’ve had 3  node.js apps come across my radar lately, and they’ve all been
a PAIN IN THE BUTT to get working.

from the description i was hoping that Angular would  be the solution to
those kinds of problems.
sadly, so far, it’s been exactly opposite. :-(

**Comment by ppbrown** [comment]
okay let me clarify.
when i said “use an application” i should probably have said “deploy and
run an application”
