### ISSUE TITLE
scrollTo start bottom

### ISSUE THREAD

**Issue by yurineves92** [angular/angular#33691]
when I use the lazy loading pattern of angular and I go to another component basically the scroll starts at the bottom of the screen, I started analyzing and checking if I had any issues open about it, then made a javascript tweak on the specific component, but I wanted to know if you have any resolution on this case or is it first time.
[IMAGE](https://imgur.com/a/Yoolag4)

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
