### ISSUE TITLE
[Ivy - 9.0.0-rc.1] Running `ngc` on a custom library throws error "Appears in the NgModule.imports of ..., but could not be resolved to an NgModule class"

### ISSUE THREAD

**Issue by VladimirAmiorkov** [angular/angular#33690]
# 🐞 bug report

### Affected Package
`@angular/common` but I expect that others can also have this issue.

### Is this a regression?

Yes, running `ngc` on a code of a library that uses Angular's packages has always works and the correct .metadata.json files have been created.

### Description

Running `ngc` to generate the `metadata.json` of my custom library's source code fails when using the latest 9.0.0.x release, currently available in the @next tag at npm.

I am testing how to building my package will work when 9.0.0 comes out.

## 🔬 Minimal Reproduction

As this requires compiling with `ngc` I have prepared a very simply package and you can download it here [ngc issue.zip](https://github.com/angular/angular/files/3825183/ngc.issue.zip)

Simply do the following:
- Extract the archive and open it in a terminal
- Install the npm packages with `npm install`
- Trigger `ngc` by executing `./node_modules/.bin/ngc`

The following error is thrown:

## 🔥 Exception or Error
<pre><code>

node_modules/@angular/common/common.d.ts:115:22 - error NG6002: Appears in the NgModule.imports of MyCommonModule, but could not be resolved to an NgModule class

115 export declare class CommonModule {
                         ~~~~~~~~~~~~
node_modules/@angular/common/common.d.ts:115:22 - error NG6003: Appears in the NgModule.exports of MyCommonModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class

115 export declare class CommonModule {
                         ~~~~~~~~~~~~

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.0-rc.1
Node: 10.15.2
OS: darwin x64
Angular: 9.0.0-rc.1
... common, compiler, compiler-cli, core

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.0-rc.1 (cli-only)
@angular-devkit/core         9.0.0-rc.1 (cli-only)
@angular-devkit/schematics   9.0.0-rc.1 (cli-only)
@schematics/angular          9.0.0-rc.1 (cli-only)
@schematics/update           0.900.0-rc.1 (cli-only)
rxjs                         6.5.3
typescript                   3.6.4

</code></pre>

**Anything else relevant?**
I am hitting this error in preparation for Ivy and 9.0.0 of my custom Angular library. I would love some assistance before 9.0.0 is live because at the moment I cannot build my custom library when using Angular packages 9.0.0

**Comment by alexzuza** [comment]
Hey, it looks like you forgot to run Angular compatibility compiler(ngcc) first. This compiler prepares Angular code to work with new Ivy compiler(ngtsc).

So your actions are:

```
./node_modules/.bin/ngcc -p es2015
```

You can also compile other formats like fesm2015, fesm5, esm2015, esm5, main, module (See also https://aio-staging.firebaseapp.com/guide/migration-ngcc#can-i-customize-the-ngcc-options-in-the-postinstall-script)

then
```
./node_modules/.bin/ngc
```

**Comment by VladimirAmiorkov** [comment]
Thanks for replying. I did find out that but was wondering if that is correct. I was not sure if ngcc should be ran before ngc, because if I do this then there are no metadata json files created

**Comment by alexzuza** [comment]
@VladimirAmiorkov Ivy compiler is now default compiler. If you want to compile your library in ViewEngine mode then I would suggest you using `enableIvy` option in your tsconfig.json
```
"angularCompilerOptions": {
      "genDir": ".",
      "skipMetadataEmit": false,
      "skipTemplateCodegen": true,
      "strictMetadataEmit": true,
      "enableIvy": false
    },
```

**Comment by VladimirAmiorkov** [comment]
@alexzuza Awesome, thank you. My issue is resolved so I will close this issue.
