### ISSUE TITLE
RC.1/IVY - export 'EffectsFeatureModule' (imported as 'i2') was not found in @ngrx/effects

### ISSUE THREAD

**Issue by spock123** [angular/angular#33701]
# 🐞 bug report

### Affected Package

  

After upgrading to RC1 and turning on IVY I get tons of errors from  the @ngrx/effects module.

```
"export 'EffectsFeatureModule' (imported as 'i2') was not found in '@ngrx/effects'
"export 'EffectsFeatureModule' (imported as 'i2') was not found in '@ngrx/effects'
```
... and so on.. 

Turning off IVY everything works without an issue.

This is from a production app running NG8 currently in production.
It uses @ngrx/store and effects module.

I've never had these issues with the .next-x and rc.0 versions.

### Is this a regression?

I think so

 Yes, the previous version in which this bug was not present was: ....

I believe so.
 I've never seen this issue before and I've tested all .next versions and rc.0

### Description

ng serve yields lots off errors like:

```
ERROR in ./src/app/store/bizz-store/bizz-store.module.ts 19:79-102
"export 'EffectsFeatureModule' (imported as 'i1') was not found in '@ngrx/effects'
ERROR in ./src/app/modules/lazy-shared/lazy-shared.module.ts 136:26-50
"export 'EffectsFeatureModule' (imported as 'i16') was not found in '@ngrx/effects'
ERROR in ./src/app/feature-modules/dashboard/dashboard.module.ts 58:520-544
"export 'EffectsFeatureModule' (imported as 'i16') was not found in '@ngrx/effects'
ERROR in ./src/app/store/iticket-store/iticket-store.module.ts 22:105-128
"export 'EffectsFeatureModule' (imported as 'i2') was not found in '@ngrx/effects'
ERROR in ./src/app/feature-modules/login/store/login-store.module.ts 24:103-126
"export 'EffectsFeatureModule' (imported as 'i2') was not found in '@ngrx/effects'
ERROR in ./src/app/feature-modules/gdpr/gdpr.module.ts 40:149-172
"export 'EffectsFeatureModule' (imported as 'i3') was not found in '@ngrx/effects'
ERROR in ./src/app/modules/licenseplate-checker/licenseplate-checker-module.ts 25:162-185
"export 'EffectsFeatureModule' (imported as 'i3') was not found in '@ngrx/effects'
ERROR in ./src/app/feature-modules/feedback/feedback.module.ts 38:185-208
"export 'EffectsFeatureModule' (imported as 'i3') was not found in '@ngrx/effects'
ERROR in ./src/app/feature-modules/weather/weather.module.ts 38:182-205
"export 'EffectsFeatureModule' (imported as 'i3') was not found in '@ngrx/effects'
ERROR in ./src/app/feature-modules/receipt/receipt.module.ts 39:170-193
"export 'EffectsFeatureModule' (imported as 'i4') was not found in '@ngrx/effects'
```

## 🔬 Minimal Reproduction

Unfortunately I cannot share my repo but if nobody has seen this issue before I'll try and do a minimal version. 

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.0-rc.1
Node: 12.2.0
OS: darwin x64
Angular: 9.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.1
@angular-devkit/build-angular      0.900.0-rc.1
@angular-devkit/build-optimizer    0.900.0-rc.1
@angular-devkit/build-webpack      0.900.0-rc.1
@angular-devkit/core               9.0.0-rc.1
@angular-devkit/schematics         9.0.0-rc.1
@angular/cdk                       9.0.0-rc.0
@angular/material                  9.0.0-rc.0
@angular/material-moment-adapter   9.0.0-rc.0
@ngtools/webpack                   9.0.0-rc.1
@schematics/angular                9.0.0-rc.1
@schematics/update                 0.900.0-rc.1
rxjs                               7.0.0-alpha.0
typescript                         3.6.4
webpack                            4.41.2

</code></pre>

**Anything else relevant?**

**Comment by Dj-jom2x** [comment]
not related I think..  have u tried to download  @ngrx/effects
 source and put it inside your src folder? like, create a folder inside src like " ngx" then put the library there. and change the public_api.ts to index.ts then import thru there. that's what I do.. when other applications are still on ag 8 and having a problem when importing at ag 9..  it works fine tho haha xD

**Comment by spock123** [comment]
@Dj-jom2x hi, no haven't tried that. It's kind of a hack though /s

**Comment by spock123** [comment]
I've also tried downgrading rxjs to latest stabile version but as expected that didn't change anything.

**Comment by petebacondarwin** [comment]
I added a PR to include ngrx in ngcc-validation: https://github.com/angular/ngcc-validation/pull/559
It doesn't appear to fail but I am probably missing some detail

**Comment by dannyskoog** [comment]
I'm also experiencing this using `rc.1` in combination with `"@ngrx/effects": "~8.0.1"`

**Comment by spock123** [comment]
@dannyskoog 
I updated to 8.5.1 (latest stabile) but that didn't resolve the issue, unfortunately..

**Comment by petebacondarwin** [comment]
We need to prioritise getting this working. I will look into it today.

**Comment by petebacondarwin** [comment]
@spock123 and @dannyskoog - it is hard to help solve this without a reproduction. Currently I cannot make a failing ivy + ngrx app...

**Comment by petebacondarwin** [comment]
Actually @brandonroberts  suggests that we open a ticket on https://github.com/ngrx/platform so it can get some visibility there too.

See https://github.com/ngrx/platform/issues/2260

**Comment by dannyskoog** [comment]
Sure @petebacondarwin. I’ll see if I can put up a reproduction on StackBlitz tonight 👍

**Comment by dannyskoog** [comment]
The only lead I've found so far is that once I change the `target` in `tsconfig.json` from `es5` to `es2015` everything works properly. Take note @petebacondarwin

I will continue trying to create a reproduction

**Comment by brandonroberts** [comment]
@petebacondarwin @dannyskoog I was able to reproduce the issue when using NgRx within a library, and the target is `es5`. 

Here is the repo: https://github.com/brandonroberts/ngrx-ivy-lib-build-error.

1. clone repo
2. run `yarn` to install dependencies
3. run `ng build my-lib` to build the library
4. run `ng build` to build the app
5. note the build error as the same error mentioned above

**Comment by JoostK** [comment]
@brandonroberts @dannyskoog Thanks for providing this information. Together with  https://github.com/angular/angular/issues/33100#issuecomment-546610580 this helped me track down the issue.

This is an appearance of a bug that #32902 was supposed to have fixed. I don't know exactly how this can still be broken as I recall that fix to have made a difference back then, but apparently some other circumstances were at play there.

There was a migration to install a postinstall hook to run ngcc, with a set of properties that are suitable for ES2015 targets. When targeting ES5 however, as @dannyskoog rightfully found out, the compilation under the CLI is loading ES5 bundles as the previously processed ES2015 bundles cannot be used. During this additional processing of the ES5 bundle it was not necessary to process the .d.ts files, as these had already been processed during the postinstall hook when processing ES2015. This prevents the migration for `ModuleWithProviders` to run, as it's primarily there to update .d.ts files. However, it is also responsible for detecting the case where the imported NgModule needs to become a public export for the Ivy compiler to refer to.

Please see the description in #32902 for more info. I expect to open a PR with a fix soon.

**Comment by dannyskoog** [comment]
Our pleasure @JoostK. And thanks for that thorough ellaboration on the root cause 👍

**Comment by spock123** [comment]
Thank you so much guys!
