### ISSUE TITLE
Provide a service to find component by name

### ISSUE THREAD

**Issue by abadakhshan** [angular/angular#33715]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
I have a scenario in my framework that I should find **ComponentType** by it's name and then create it. In Angular 8 I used `ComponentFactoryResolver["_factories"]`  to find component.
(Component added to `EntryComponent`)

But in **Ivy** there is no `_factories `in `ComponentFactoryResolver`.

I tried to use `_r3Injector.injectorDefTypes` and then `["ɵmod"].declarations` for each module. It was OK in development but in production mode **declarations** is always empty.

After that I tried to use **directiveRegistry** of **TView** . But I understood that only components stay on  **directiveRegistry** that used.

### Describe the solution you'd like
 I think it would be nice if there is a service that metadata of modules and components can be accessible via it.

### Describe alternatives you've considered
 An alternative can be  provide a service to register these types  and then use them.

**Comment by IgorMinar** [comment]
Can you please clarify this request? The `ComponentFactoryResolver` already allows you to create component by type (constructor of the component) via the `resolveComponentFactory` method.

Are you saying that you want to create it using the string name of the class or something else?

**Comment by abadakhshan** [comment]
Yes, @IgorMinar.
I have some metadata (in JSON format) and based on this metadata I should create appropriate Component dynamically.
Actually  I don't have the ComponetType I only have the Component name.
In Previous Angular versions (8 and before) I used this code:


```
      factories = Array.from(
        this.componentFactoryResolver["_factories"].keys()
      );
      factoryClass = <Type<any>>(
        factories.find(
          (x: any) =>
            x.name === viewInfo.component ||
            x["COMPONENT_NAME"] === viewInfo.component
        )
      );

   const componentFactory = this.componentFactoryResolver.resolveComponentFactory(
      factoryClass
    );
    const viewContainerRef = this.loaderHost.viewContainerRef;
    viewContainerRef.clear();

    const cmp = viewContainerRef.createComponent(componentFactory);
     ........
     ..........
```

_**COMPONENT_NAME** is a static field on class for build situation that real class name changed due to optimization_

**Comment by ssougnez** [comment]
I'm kind of having the same issue. Indeed, in my current application, I receive some information from my back end such as a name and a version and based on that, I generate a string that looks like `{name}-{version}` , then uses the following code to load the corresponding component in the page using the `_factories` field of `ComponentFactoryResolver`.

However, when I enable ivy, `_factories` is `null` so I have no way of dynamically loading a component based on its selector.

**Comment by TzyHuan** [comment]
I encounter the same problem!
The property of `_factories` was originally in the `ComponentFactoryResolver`.
When upgrade to Angular 9, I don't know how to get the information about components.

**Comment by mlc-mlapis** [comment]
@TzyHuan The `_factories` was never a public API. The names are always obfuscated/manged during building process. If you need to lookup by kyes, use your own dictionary/tokens.

**Comment by TzyHuan** [comment]
@mlc-mlapis Webpack will uglify names indeed, but the `selector` is unchanged. In fact, use own dictionary/tokens is a better way as you said. I will design own property in case of uglifying `selector`. 🤣🤣🤣

What If I wanna do reflection in Angular, and the targets are components unfortunately. Is there another way to get the component list? This is what I wanna mention.
In previous version of Angular, I can get the list of components from `_factories`.

**Comment by mlc-mlapis** [comment]
@TzyHuan Because of the Angular Ivy structure wasn't stable enough, I didn't explore it enough yet. It's possible to expect that when Angular 9 will be published as a stable major version, so new features will be also available in this area. We still need to wait a bit. Be patient.

**Comment by ssougnez** [comment]
A dictionary is indeed an option but it means that it needs to be maintained and that's sometimes that you'll forget most of the time... 

To be honest, I'm a bit surprised that there is no official solution at all, even with ng8 to load a component based on its selector. Being able to load dynamically a component this way can be very helpful.

I guess that if ng9 does not come with a better solution, I'll create a custom dictionary with all loadable component but it's not really a good solution.

**Comment by leonelvsc** [comment]
my current solution to this problem is from #35795 :

some-service.ts

```
export const TYPE_MAP = {};

export class SomeService {
    typeMap = TYPE_MAP;

    constructor() {
    }
}
```
type-manager.interface.ts

```
export interface TypeManager {
    someMethod();
}
```

type-manager.decorator.ts

```
export function TypeManagerDecorator(aType: string) {
    return function _TypeManagerDecorator<T extends { new(...args: any[]): TypeManager}>(constr: T) {
        TYPE_MAP[aType] = constr;
    };
}
```
manager-for-type-a.component.ts

```
@TypeManagerDecorator('a')
@Component({
    selector: 'app-manager-for-type-a',
    templateUrl: './manager-for-type-a.component.html',
    styleUrls: ['./manager-for-type-a.component.css'],
    viewProviders: [
        {
            provide: ControlContainer,
            useExisting: NgForm
        }
    ]
})
export class ManagerForTypeAComponent implements OnInit, TypeManager {

    constructor() {
    }

    ngOnInit() {
    };

    someMethod() {
    };
}
```
manager-for-type-b.component.ts

```
@TypeManagerDecorator('b')
@Component({
    selector: 'app-manager-for-type-b',
    templateUrl: './manager-for-type-b.component.html',
    styleUrls: ['./manager-for-type-b.component.css'],
    viewProviders: [
        {
            provide: ControlContainer,
            useExisting: NgForm
        }
    ]
})
export class ManagerForTypeBComponent implements OnInit, TypeManager {

    constructor() {
    }

    ngOnInit() {
    };

    someMethod() {
    };
}
```
main.component.html

```

<form #form="ngForm" (ngSubmit)="form.valid" autocomplete="off">

    <select [(ngModel)]="type" name="type" (ngModelChange)="changeTypeManager($event)">
        <option value="a">Type A</option>
        <option value="b">Type B</option>
    </select>


    <ng-container #container></ng-container>

</form>
```
main.component.ts
```

@Component({
    selector: 'app-main',
    templateUrl: './main.component.html',
    styleUrls: ['./main.component.css']
})
export class MainComponent implements OnInit, OnDestroy {

    @ViewChild('container', {read: ViewContainerRef, static: true})
    private mainContainer: ViewContainerRef;
    private componentReference: ComponentRef<any>;

    constructor(
        private aService: SomeService,
        private resolver: ComponentFactoryResolver
    ) {

    }

    ngOnInit() {
    }

    ngOnDestroy() {
        if(this.componentReference) {
            this.componentReference.destroy();
        }
    }

    private changeTypeManager(aType: string) {
        if(this.componentReference) {
            this.componentReference.destroy();
        }

        if(!this.aService.typeMap[aType]) {
            throw new Error(`No class exists with the decorator @TypeManagerDecorator('${aType}')`);
        }

        const componentFactory = this.resolver.resolveComponentFactory(this.aService.typeMap[aType]);
        this.componentReference = this.mainContainer.createComponent(componentFactory);
    }

}
```

**Comment by abadakhshan** [comment]
thank you @leonelvsc 
I used this approach, but I have a problem with the production build.
It seems that the custom decorator(TypeManagerDecorator) does not work.

Maybe due to this issue: https://github.com/angular/angular/issues/31495

Have you used this solution in production build?

**Comment by leonelvsc** [comment]
Same happened to me in production, i endedup doing a static hashmap "object" with the types and commented out the decorators.

On the previous issue of mine there was another solution that involves the multi injection token. That should work, but i haven't tested it out in production.

Link to alternative solution: https://github.com/angular/angular/issues/35795#issuecomment-593630404

**Comment by nitzanb-medopad** [comment]
I also need angular to keep exposing _factoring or suggest an easy alternative in Angular 9..

**Comment by TzyHuan** [comment]
I found the official [live example](https://angular.io/guide/dynamic-component-loader) on Angular 9.0.7 can get `_factories` from `ComponentFactoryResolver` with key/value data. The `private componentFactoryResolver` print out as below, It's seems from this [source codes](https://github.com/angular/angular/blob/40aaa42f445c0d2600a219d1a83834db510a2eab/packages/core/src/linker/component_factory_resolver.ts#L54#L64).

![image](https://user-images.githubusercontent.com/35286773/78502721-0e2ec500-7795-11ea-91d4-c6ffd9f38306.png)


but I run the same version 9.0.7 on local project with `ng serve` , the result is weird as below

![image](https://user-images.githubusercontent.com/35286773/78503273-3d930100-7798-11ea-9939-0c42aa34a874.png)

Does anyone know what's problems causing different result?

**Comment by mlc-mlapis** [comment]
@TzyHuan The difference is Ivy:
![image](https://user-images.githubusercontent.com/5693835/78503898-d4949480-7769-11ea-88db-8de03fd1b001.png)

**Comment by abadakhshan** [comment]
I think there is a problem in Angular Ivy related to this issue.

In Angular V 8 there is an `EntryComponent `on `NgModules `that we define dynamic components there.  Some of these components were used by direct reference, some were used without any reference. for example like [this](https://github.com/angular/angular/issues/33715#issuecomment-552551389)

In Angular 9 (Ivy) `EntryComponent ` has been deprecated and there is no need to put dynamic components to it because Factory is created in a static field on the component itself.

This method works well for dynamic components with direct reference but causes dynamic components that does not have any reference in the application( they are going to be created in some dynamic manner for example by its selector dynamically), is removed from the bundle in production build!

**Comment by klogeaage** [comment]
@abadakhshan Spot on, we also have a major problem because the `entryComponents `array is now ignored in Angular9 when using Ivy, thus removing the components that are ONLY referenced via a name lookup with a scheme like what is described in #35314. I'm going to attempt a workaround as described [here](https://github.com/angular/angular/issues/35314#issuecomment-584821399). 

But it would be nice if there was either an official supported mechanism for this type of scenario, or if the `entryComponents `array was still taking into account. And by the way, [the official documentation](https://angular.io/guide/entry-components#the-entrycomponents-array) still claims that to be the case, even though it is deprecated. I think it might have been a mistake to completely remove `entryComponents`...

**Comment by mlc-mlapis** [comment]
@klogeaage @JoostK Yep. You are right. The problem exists. It's a bit surprising for me that the Angular team didn't cover this case in some official solution. Especially from the point of view, that the whole site https://angular.io used this technique some time ago (parsing HTML template code and dynamically creating a pre-defined set of components on the base of their selectors).

It's true that there is a lot of possible solutions on how to directly reference those components and to include them into bundles in the end, but I still think that there should exist some official way/convention on how to do it. The biggest advantage of it would be more precise readability/understanding of code - very fast orientation where is what on the first look.

**Comment by montella1507** [comment]
@mlc-mlapis  i am going to go deeper... i think it should / may be possible in the future to use lazy-loaded component directly in template with some kind of shield, aka:

`
[LAZY(./something.module)]
 <lazy-component [inputA]="5" (output)="onOutput()"></lazy-component>
`

Because:
1) It should be possible (check ngx-template-streams) 
2) It is really needed, NOONE has ever written article about cross referencing components:
 A Module -> A Detail component  has to show B Detail component from B Module and vice versa (cross references between modules)

And there are only 2 Solutions:
1) Merge into 1 module - it is nonsense, in big CRM all components will end in 1 module..
2) Dynamic component loading

**Comment by mlc-mlapis** [comment]
@montella1507 Yep, it would be nice. 👍 But there is still necessary to come in with some clever and flexible way how to register such components somewhere + elegant syntax how to do it. The same role the Web Components (Angular Elements) have, but in our discussed topic those components are integral parts of the whole application, so it is not necessary to cover the complete interface.

**Comment by ecerichter** [comment]
Any update on this (load component by name)?

**Comment by alessiostalla** [comment]
We have this problem as well, and even though we can easily work around it, a built-in solution akin to old entryComponents would be nice.

**Comment by ashishgehlot** [comment]
I am facing same issue. "_factories" node doesn't exist in componentFactoryResolver since angular 9. 
Angular team should consider this feature request. 

Is their any workaround to make it happen ?

**Comment by leonelvsc** [comment]
https://github.com/angular/angular/issues/33715#issuecomment-594088782

That solution with custom decorators started to work again, i would refactor the code like this deleting the service

type-manager.decorator.ts
`
const TYPE_MAP = new Map<string, any>();

export function TypeManagerDecorator(aType: string) {
    return function _TypeManagerDecorator<T extends { new(...args: any[]): TypeManager}>(constr: T) {
        TYPE_MAP[aType] = constr;
    };
}

export function getComponent(aType: string) {
  return TYPE_MAP.get(aType);
}
`

main.component.ts
`
...

getComponent(aType)

...
`

**Comment by srivastava07** [comment]
I have the same problem, does anyone found the solution of this problem? For Complex ERP with dynamic  component loading based on configuration you can't maintain a map of class, it doesn't make sense, Ivy needs to expose its factory map to outside use.

**Comment by tarangkhandelwal** [comment]
We are using a way to have dynamic components by extending modules to provide components that should be available via selectors. Hope this helps.

https://indepth.dev/posts/1400/components-by-selector-name-angular

**Comment by priyanka01deb** [comment]
Can we get a solution for this in Angular Ivy?

**Comment by softengi** [comment]
Do we have an update on this? any workaround or solution?
I can see in this thread that there are so many people facing this issue.

**Comment by JoostK** [comment]
Hi all,

Providing access to components by some identifier is not something that we'd be adding to Angular. Such a feature would actively prevent tree-shaking of unused components, and different projects may have different requirements for _how_ a component has to be identified.

There are a couple ways you can achieve something like this already:

1. Declare a list of components you want to find dynamically at runtime in a static field of a some class, or even just a global variable.
2. Use Angular's DI system to register components using a multi-provider.

I would advise against using decorators to achieve the registration, as that requires that the decorator has a global side-effect.
