### ISSUE TITLE
HttpUrlEncodingCodec reverses part of the encoding

### ISSUE THREAD

**Issue by Johanneke** [angular/angular#33728]
# 🐞 bug report

### Affected Package
@angular/common/http

### Is this a regression?
Seems this issue has existed for a couple of years, but issues get closed due to inactivity.
See also
- https://github.com/angular/angular/issues/18261
- https://github.com/angular/angular/issues/30379
- https://github.com/angular/angular/issues/26979
- https://github.com/angular/angular/issues/27009

### Description
When passing parameters with special characters (for example the equals-sign '=') to the angular HttpClient, parameters are by default encoded using the HttpUrlEncodingCodec. 
This codec uses the vanilla encodeURIComponent, but then proceeds to replace a couple of the encoded characters with their decoded counterpart. See code (https://github.com/angular/angular/blob/8.2.13/packages/common/http/src/params.ts#L81-L92):
```
function standardEncoding(v: string): string {
  return encodeURIComponent(v)
      .replace(/%40/gi, '@')
      .replace(/%3A/gi, ':')
      .replace(/%24/gi, '$')
      .replace(/%2C/gi, ',')
      .replace(/%3B/gi, ';')
      .replace(/%2B/gi, '+')
      .replace(/%3D/gi, '=')
      .replace(/%3F/gi, '?')
      .replace(/%2F/gi, '/');
}
```

I've seen a comment somewhere that this is "by design", but it was lacking any explanation and was autoclosed due to inactivity. 

## 🔬 Minimal Reproduction
```
let params = new HttpParams({fromObject: {
        param1: 'app=excess'
    }});
```
This will encode params to be `app=excess`, instead of the expected `app%3Dexcess`.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
node: 10.15.0
os: darwin x64
@angular/animations: 7.1.4
@angular/common: 7.1.4
@angular/compiler: 7.1.4
@angular/core: 7.1.4
@angular/forms: 7.1.4
@angular/http: 7.1.4
@angular/platform-browser: 7.1.4
@angular/platform-browser-dynamic: 7.1.4
@angular/router: 7.1.4
@angular/compiler-cli: 7.1.4
@ngtools/webpack: 7.1.4
</code></pre>

**Comment by Johanneke** [comment]
By the way, this same "standardEncoding" is also applied to the key. So if your key contains the `=` character, it will not get encoded, but then it will function as a delimiter in your query! That is *NOT* according to spec.

**Comment by hokkaido** [comment]
This basically means that you cannot make certain requests with the existing HttpClient implementation, i.e. if you need to query a backend service that accepts international phone numbers as a query param there is no way to properly encode the plus sign.

**Comment by alxhub** [comment]
I'm going to fold this into #11058 as it's essentially the same root cause (the query parameter encoding is pretty broken).
