### ISSUE TITLE
Tell users they can bypass the compiler error

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#33745]
# 🚀 feature request

### Relevant Package
@angular/compiler

### Description
Users with the wrong TypeScript version get the error: ERROR in The Angular Compiler requires TypeScript >=3.6.4 and <3.7.0 but 3.7.2 was found instead.

When this error is hit, you should tell users they can bypass the error with: 
    `  "disableTypeScriptVersionCheck": true`

### Describe the solution you'd like
Tell people how to bypass it.

**Comment by gkalpak** [comment]
Do we really want to do that (given that there are breaking changes in TS v3.7. that are not compatible with our code - e.g. the removal of `.typeArguments`)? 🤔

**Comment by Airblader** [comment]
In the view engine world I would prefer not showing people the foot gun they can use.

However I did read on the PR for latest TS support that Ivy is supposedly much more stable with regards to changes in TS, so there this could perhaps make more sense.

**Comment by gkalpak** [comment]
That is generally true, but we do use the removed `typeArguments` property in several places, so I am afraid we might be setting people up for failure.

(I could be wrong.)

**Comment by Airblader** [comment]
I would put it like this: if the only reasonable action to add this information is to also add a big fat warning along the lines of "this can break everything", then I think it shouldn't be added at all.

**Comment by MrJithil** [comment]
It's already documented in [disabletypescriptversioncheck](https://angular.io/guide/angular-compiler-options#disabletypescriptversioncheck) in aio.

I think, we don't need anything more about this.

@kapunahelewong , could you please verify the above answer and kindly close this issue?

**Comment by MrJithil** [comment]
> In the view engine world I would prefer not showing people the foot gun they can use.
> 
> However I did read on the PR for latest TS support that Ivy is supposedly much more stable with regards to changes in TS, so there this could perhaps make more sense.

As a developer, we need to all the foot guns. I don't agree to hide a feasibility from a dev.

And FYI, we already exposing it in the [disabletypescriptversioncheck](https://next.angular.io/guide/angular-compiler-options#disabletypescriptversioncheck)

**Comment by kapunahelewong** [comment]
Thanks for pointing this out and sharing the link, @MrJithil. @jbogarthyde do you have any context on this that you might be able to share? As @MrJithil points out, it does look like it's written in the guide, but maybe the intention is for it to be more explicit?

**Comment by AndrewKushnir** [comment]
Closing this ticket since the mentioned config option is already documented.
