### ISSUE TITLE
Allow users to specify parts of event string that should run on UI thread

### ISSUE THREAD

**Issue by jteplitz** [angular/angular#3374]
Currently we are nulling out anything in the event object that can't be serialized and passed to the worker. There should be a way to specify specific values to be passed to the worker with the event.

**Comment by jeffbcross** [comment]
Should be fixed when render services API is implemented #2409. Leaving open for verification.

**Comment by splincode** [comment]
@jteplitz Is the issue relevant?

**Comment by fobo66** [comment]
Is this issue still relevant?
