### ISSUE TITLE
Integration of url and inline types into a single type for templates and styles.

### ISSUE THREAD

**Issue by RohanAntony** [angular/angular#33752]
# 🚀 feature request

### Relevant Package
@angular/core

### Description
Integration of 'templateUrls' and 'template' as well as 'styles' and 'styleUrls' option into a single field while defining a 'Component'. 

### Describe the solution you'd like
Define a class which contains type, value as the fields to a new Class. 
Create an instance of this class which can have type set to 'URL' or 'INLINE' and value set for template or path for the template.
A single object instance can be set for template whereas an array of these can be set for styles. 

### Describe alternatives you've considered
Current implementation is the alternative.

**Comment by Airblader** [comment]
What is the benefit of changing this that you are expecting or looking for? 

Without a benefit it's of course not a good idea to make such a breaking change.

**Comment by ajitsinghkaler** [comment]
@RohanAntony it only reduces 1 % of developer's effort and they may have to change a lot of codebases to implement this I think its best left as it is.

**Comment by mhevery** [comment]
I don't see value in this either.
