### ISSUE TITLE
LiveReload Not Working for Symlinked Files

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [angular/angular#33750]
### Is this a regression?

No

### Description

I have an Ionic 4 project using Angular. I have one angular.json file for several projects with one shared folder. The regular projects include symlinks to the shared folder. Everything works including the AoT build except for LiveReload. Whenever I save a file that's located inside the regular project, the LiveReload gets triggered. However, for any files that are symlinks, it does not get retriggered. I have experimented using TypeScript paths but I ran into a dead end with them. Is there anyway to get Angular to detect when a symlinked file is saved?

**Comment by ajitsinghkaler** [comment]
Hi, This is a project related issue its better if you post this on StackOverflow. It is better suited there and moreover, you cannot post project related issues here.

Please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by ajitsinghkaler** [comment]
@gkalpak I think we can close this issue.

**Comment by gkalpak** [comment]
This doesn't sound like an Angular-specific problem (or at least I can't infer that from the description).
Closing the issue, but feel free to add more details below or open a new one, if you think this is Angular-specific (and can provide a minimal reproduction).
