### ISSUE TITLE
nested ngFor with independend click fuction

### ISSUE THREAD

**Issue by sincy123** [angular/angular#33753]
<ul class="dropdown-content">
                                            
                   <li *ngFor="let i of departments" class="dropdown-submenu (click)="getCategory(i.dept_url)"><a>{{i.department}}</a>
                         <ul class="dropdown-menu" style="padding: 0%;background-color: transparent;">
                                  <ng-container *ngFor="let m of cats">
                                                <ng-container *ngIf="i.department==m.department" >
                                                <li *ngFor="let e of m?.category"><a (click)="getProductlist(e.seo_url,i.dept_url)">{{e.category}}</a></li>
                                                        </ng-container>
                                                    </ng-container> 
                                                   
                                                </ul>
                                            </li>
                                            
                                        </ul>

**Comment by sincy123** [comment]
if i click on the getProductlist(),getCategory() also invoked..how to fix this problem

**Comment by JonWallsten** [comment]
@sincy123: What is the actual problem here? That both of them is called?

**Comment by sincy123** [comment]
stopPropagation() method is applicable for angular6?

getProductlist(a,b,$event)
  { 
    localStorage.setItem("dept_url",b)
    this.router.navigate(['products/list/productlist',a]) 
    $event.stopPropagation();
  }

**Comment by sincy123** [comment]
``

> @sincy123: What is the actual problem here? That both of them is called?
> 
> Edit: If that's the case you should use stopPropagation.
> 
> ```
> <li (click)="getProductlist($event, e.seo_url,i.dept_url)"></li>
> ```
> 
> ```js
> getProductlist ($event, ...) {
>   // Stop the event from reaching the outer click listener
>   $event.stopPropagation();
> }
> ```

thank you sir...Now it works

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by JonWallsten** [comment]
> stopPropagation() method is applicable for angular6?
> 
> getProductlist(a,b,$event)
> {
> localStorage.setItem("dept_url",b)
> this.router.navigate(['products/list/productlist',a])
> $event.stopPropagation();
> }

It's applicable to JavaScript in general. You should read up about event.preventDefault and event.StopPropagation. It's really good to know.
