### ISSUE TITLE
compareWith should be able to access global variables

### ISSUE THREAD

**Issue by SC-JC** [angular/angular#33758]
# 🚀 feature request

### Relevant Package
@angular/forms

### Description
I wrote components that get a string as input which is used to compare objects, as i might want to compare the whole object or just the ID of the objects, depending on it's use.
Sadly the function passed to [compareWith] has no access to the global variables of the component.

### Describe the solution you'd like
The function passed to [compareWith] gets access to the global variables of the component.

### Describe alternatives you've considered
Extend the parameters for compareWith to include an optional third parameter used for comparing.
e.g.:

[compareWith]="compare" compareWithIndex="id"

compare(c1: any, c2: any, index: string)

### Example:
https://stackblitz.com/edit/angular-bh1kuo

**Comment by marcjcs** [comment]
As a workaround you can do:
```
compare = (c1: any, c2: any): boolean => {
  return c1 && c2 ? c1[this.compareBy] == c2[this.compareBy] : false
}
```

**Comment by SC-JC** [comment]
Seems to work, will check it tomorrow.

thanks :)

**Comment by AndrewKushnir** [comment]
Hi @SC-JC, thanks for creating this ticket. The thing is that the compare function is invoked with the `SelectControlValueAccessor` context, not the context of the class where the function was defined, so you should capture the right context in the compare function (for example as @marcjcs mentioned). I will keep the ticket open to see if we can improve documentation to cover capturing context for `compareWith` function. Thank you.
