### ISSUE TITLE
http post is returning empty data in backend api

### ISSUE THREAD

**Issue by versatilePrakash** [angular/angular#33756]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Angular http post from the form data is being posted but is just posted empty .
I am getting the data completely but posting made the problem here

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by santoshyadav198613** [comment]
Please raise it on Stackoverflow with some error code, you can raise any framework related hugs here.

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
