### ISSUE TITLE
angular.io website is missing titles (SSR, SEO)

### ISSUE THREAD

**Issue by slavafomin** [angular/angular#33760]
Hello!

Thank you for your hard work.

However, `https://angular.io/` website is missing the correct titles.

Consider this page:
https://angular.io/guide/lazy-loading-ngmodules

It has a heading: "Lazy Loading Feature Modules", but it's not reflected in the `<title>` when HTML is returned from the server. The title looks like this for all pages: `<title>Angular</title>`, so it makes search results less readable in engines, which doesn't support JavaScript (e.g. DuckDuckGo):

![screenshot-duckduckgo com-2019 11 12-18_47_00](https://user-images.githubusercontent.com/1702725/68686562-de301c80-057c-11ea-844d-6c429a444a78.png)

I believe this should be fixed on SSR side.

**Comment by gkalpak** [comment]
Well...currently there is no SSR, but it's a potential future enhancement.

**Comment by Yogu** [comment]
Should be fixed with the release of angular.dev, right? (You did an awesome job with that!)

**Comment by JeanMeche** [comment]
We're looking at deprecating angular.io in favor of anguiar.dev. The new doc site uses prerendering to fix this issue.
