### ISSUE TITLE
Add readme to every angular package

### ISSUE THREAD

**Issue by ajitsinghkaler** [angular/angular#33766]
# 📚 Docs or angular.io bug report

### Description

 Ca we add a readme to each and every angular npm package to get a basic understanding of for what each and every package is used. Currently, we have readme for a few of the packages like Zone.js and bench press. Via adding readme we can make people aware of the basic functioning of these packages and if people even want to use them in their main app. Like many people, if they are if they want to decouple their components from the angular app does not use zone.js for change detection.

### What's the affected URL?**
 https://angular.io/

### Expected vs Actual Behavior**

Expected - A bit of documentation for all packages using readme.
No documentation for related packages

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by jbogarthyde** [comment]
@ajitsinghkaler Zones (and a few other packages) are external dependencies, that's why they have their own full ReadMe doc. The Angular-specific packages all share a general ReadMe that points at the git repo. I'm adding a pointer to Angular AIO, where the full documentation is available, including individual package docs -- see https://angular.io/api?type=package

**Comment by ajitsinghkaler** [comment]
In the readme, I just want to know what effect they have on angular or how they interact with angular. So that If some packages hinder my use case. Like the zone js example, I've given.

**Comment by jbogarthyde** [comment]
Of course -- and the place to find that out is in the Angular doc 😃 
The packages are included when you install Angular, you don't need to decide which ones to include.

**Comment by ajitsinghkaler** [comment]
There is nothing about the language packages localize and language-service

**Comment by jbogarthyde** [comment]
Localize is not an Angular package, but good point about `@angular/tools-language-service`. 
I'll look into it.

**Comment by ajitsinghkaler** [comment]
okay once the update is done we can close this issue

**Comment by josephperrott** [comment]
Closing this out as we now have the i18n documentation on angular.io
