### ISSUE TITLE
Proposal: An Observable wrapper for socket.io

### ISSUE THREAD

**Issue by alxhub** [angular/angular#3376]
Modern web applications often make use of a more powerful communication abstraction than HTTP provides. Technologies like long-polling and websockets make possible a bidirectional communication stream between user agents and backends.

The popular **socket.io** library expands on this abstraction, offering namespaced communication, message acknowledgement, reconnection, and selection of an appropriate transport depending on the backend's capabilities.

I propose building an abstraction of bidirectional communication capabilities in Angular, based on the Observable standard utilized in the rest of the framework. Such an abstraction would promote usability and testability of bidirectional backend communications in Angular applications.

Given that many of Angular's customers utilize socket.io's capabilities already, I propose basing the new abstraction on socket.io and providing an implementation wrapper for it. Thus, Angular users could enjoy an Observables-based interface to socket.io with all of the capabilities it provides under the hood:

* Namespaced communication - client can subscribe to specific topics/namespaces only
* Optional acknowledgement of message receipt
* Transport fallback to long polling / JSONP if web sockets are not available
* Automatic reconnection in the event of network instability

In addition to the socket.io implementation, I will provide a mock implementation to enable easy testing of apps which rely on a bidirectional connection to their backends.

**Comment by gdi2290** [comment]
why not make a `WebSocket` service (much like `Http`) that has a ConnectionStrategy bindings of `BrowserSocket` and optional `SocketIO`. Then it's trivial for others to make their own ConnectionStrategy for web services such as Faye/PubNub or even other versions of socket.io such as `SockJS`

**Comment by gdi2290** [comment]
There's also `WebRTC` and Server-Sent Events with `EventSource` for the Rails users

**Comment by jgainfort** [comment]
I agree that this implementation would be great to have. Currently I have been testing a simple web application that requests data from my nodejs/express server using socket.io. However I cant get angular to recognize that my properties have been updated after I receive the data from the socket listener.

I currently have an open question on stackoverflow: http://stackoverflow.com/questions/31706948/angular2-view-not-changing-after-data-is-updated/31728149#31728149

This has my current workaround for now that performs a simple requestCheck() on my component for when I think I should be expecting some data. Also in the ticket is a sample git repo that can be cloned that executes a socket event on app init and receives a simple array of strings.

**Comment by btford** [comment]
You might want to wrap Engine.IO instead – https://github.com/socketio/engine.io

Socket.IO adds extra features (rooms, channels, etc.). If you just want to support multiple transport fallbacks, Engine.IO might be preferable.

**Comment by jeffbcross** [comment]
@jgainfort it sounds like there might be a bug with zones not correctly intercepting events from socket.io.

**Comment by jgainfort** [comment]
@jeffbcross That was my guess. Im looking into Engine.IO to see if this will work better.

**Comment by robwormald** [comment]
I'm doing one of these for angularSails (which uses socket.io-client), see https://github.com/robwormald/rx-sails/blob/master/src/RxSails.ts and afair it works fine with ng2 - on hold until the next version of Rx merges in. Wrapped in an Rx.Subject it works very nicely. See also https://github.com/blesh/RxSocketSubject which is what I based my implementation on (both will need rewriting to match the RxNext spec) 

I've chatted a bit with @Urigo of angular-meteor about this and keep meaning to dig into it more with him. I'm a big fan of socket.io but frankly I don't think it's the right abstraction to bet the farm on. 

@jeffbcross / @btford  one thing I'm unclear on - if I have an Observable (or a Subject) and opt-in to ON_PUSH change detection, is Zone involved at all? Obviously it's going to patch the global APIs but it seems a bit counterintuitive it would be required when using push CD.

**Comment by rolandjitsu** [comment]
:+1: for [Engine.IO](https://github.com/socketio/engine.io)

**Comment by jeffbcross** [comment]
@robwormald there are two different concerns with your question: triggering change detection, and dirty checking. Zones are concerned with triggering change detection at the right time, and ON_PUSH tells change detector that it shouldn't dirty check your values during a change detection cycle unless you've explicitly requested a check. So yeah, Zones should still do their thing to trigger change detection.

**Comment by mhevery** [comment]
1. WebSocket should work with Zone today, if not it is a bug with Zone and it should be filed there.
2. I am not sure if Angular should be in the business of writing things which are not-angular specific. I think such use cases are better served by separate third party projects. I would much rather focus on things which Angular needs to enable to work smoothly with existing code out there. 
3. I would like to see the community pick these kinds of projects up.

I would be tempted to close this issue, or at least push it down the road until we have the first main release of Angular2.

**Comment by jeffbcross** [comment]
Agreed on closing for now, and seeking more input from apps about how realtime communication is being facilitated, and what problems angular should help alleviate.
