### ISSUE TITLE
FormArray push issue when formArrayValues are disabled

### ISSUE THREAD

**Issue by monstrege** [angular/angular#33768]
Hi Angular community,

I'm having an issue when I try to push a new formControl into a formArray of formControls.
The issue happens when the other values are disabled.

When other values are disabled, the push will update correctly the ```controls```, **but the values will all be erased and only the new value will be there.**

I found the issue source:
formArray.push calls updateValueAndValidity
updateValueAndValidity calls _updateValue
_updateValue calls ._reduceValue

here's the code source
```https://github.com/angular/angular/blob/8bce694c2f658afc283e26f8adad7f8776e36728/packages/forms/src/model.ts#L1566```

Can somebody explain to me why do the disabled values should be removed from the formArray, or could this be fixed?

Workaround:

I enable everything before, then disable everything after the push:
``` 
///formValue is my FormArray
this.formValues.enable();
this.formValues.push(emptyItem)
this.formValues.disable();
```

Thanks for your attention!

**Comment by AndrewKushnir** [comment]
Hi @monstrege, thanks for reporting the issue. Could you please provide a minimal repro to illustrate the problem (using [Stackblitz](https://stackblitz.com/))? That will help us better understand the problem and perform additional investigation. Thank you.

**Comment by AndrewKushnir** [comment]
Hi, I'm closing this ticket since there is no repro that we can look into. Feel free to create a new ticket once the repro is available. Thank you.
