### ISSUE TITLE
angular 6 internationalisation

### ISSUE THREAD

**Issue by sincy123** [angular/angular#33789]
Is there is any simple methods to implement multiple language support..???
except ngx-translate

**Comment by billyjov** [comment]
@sincy123 I Think this is not an Angular related issue..You have to post your Question on SO, Gitter, Slack Channel or somewhere else..

BTW

If you want to implement i18n in your WebApp..Just choose one of the following solutions: 

- Angular i18n package (doc here with example: https://angular.io/guide/i18n)
- ngx-translate like already mentioned (doc here with example: https://github.com/ngx-translate/core )
- transloco (doc here with examples: https://github.com/ngneat/transloco).... 

For any other support please consider using SO and tag with  `angular`, `i18n`, `rxjs`.. So the community will able to help you :)

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
