### ISSUE TITLE
angular6 app internationalisation 

### ISSUE THREAD

**Issue by sincy123** [angular/angular#33785]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please file any Angular Components issues at: https://github.com/angular/components/issues/new

For the time being, we keep Angular Components issues in a separate repository.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
i want a angular 6 code for selecting a particular language that change the whole project language..
please

**Comment by sincy123** [comment]
i want a angular 6 code for selecting a particular language that change the whole project language..
please

**Comment by AndrewKushnir** [comment]
Hi @sincy123, it looks like this ticket doesn't contain sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

Feel free to file a new issue and ensure you provide all of the required information when filling out the issue template.
