### ISSUE TITLE
service-worker can block POST requests if cache fails

### ISSUE THREAD

**Issue by apocalyp0sys** [angular/angular#33793]
# 🐞 bug report

### Affected Package
 The issue is caused by package @angular/**service-worker**

### Description

I've ran into another caching problem. When handling POST (or any mutating) fetches, service-worker tries to invalidate cache for the corresponding url and re-write LRU table. LRU table is stored in CacheStorage. If writing to cache fails, no fetch is called and no request is made.

## 🔬 Minimal Reproduction
Not easily doable, may provide a repo/virtual machine later, if needed
1. Create an a application with ngsw
2. Define a dataGroup in ngsw-config.json
3. Fill up system disk (found no other reliable way to reduce available cache size)
4. Make a POST request to a url defined in dataGroup 

## 🔥 Exception or Error
<pre><code>Uncaught (in promise) DOMException: Quota exceeded.
POST {{url here}} net::ERR_FAILED</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
8.2.13
</code></pre>

**Comment by apocalyp0sys** [comment]
The uncatched error is thrown here.

https://github.com/angular/angular/blob/2be0a1d35b8f46e65ee843eaec288aacc317c2be/packages/service-worker/worker/src/data.ts#L321

There were cache-failure related issues previously, maybe we should wrap all cache-wrinting calls in `try`?

**Comment by gkalpak** [comment]
Ouch, good catch! Yeah, it might make sense to make the LRU syncing methods more resilient to errors (instead of error-proofing all call-sites).
