### ISSUE TITLE
ngc/ngtsc codegen should emit tree-shake friendly imports

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#33796]
For a module such as:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Ivy will emit the following code:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import * as i0 from "@angular/core";
export class AppModule {
}
AppModule.ɵmod = i0.ɵɵdefineNgModule({ type: AppModule, bootstrap: [AppComponent] });
AppModule.ɵinj = i0.ɵɵdefineInjector({ factory: function AppModule_Factory(t) { return new (t || AppModule)(); }, providers: [], imports: [[
            BrowserModule
        ]] });
/*@__PURE__*/ i0.ɵɵsetNgModuleScope(AppModule, { declarations: [AppComponent], imports: [BrowserModule] });
/*@__PURE__*/ i0.ɵsetClassMetadata(AppModule, [{
        type: NgModule,
        args: [{
                declarations: [
                    AppComponent
                ],
                imports: [
                    BrowserModule
                ],
                providers: [],
                bootstrap: [AppComponent]
            }]
    }], null, null);
//# sourceMappingURL=app.module.js.map
```

The `import * as i0 from "@angular/core";` in particular is hard to optimize, as it imports the whole of `@angular/core`.

Instead it should only emit imports for the used imports:
```
import {ɵɵdefineNgModule, ɵɵdefineInjector, ɵɵsetNgModuleScope, ɵsetClassMetadata} from "@angular/core";
```

Alternatively, they could be added to the existing `@angular/core` import.

@clydin found that TypeScript has done the same for their helpers, for the same reason: https://github.com/microsoft/TypeScript/pull/32742

**Comment by filipesilva** [comment]
https://github.com/microsoft/TypeScript/issues/33035 casts some doubts on whether we should do this.

**Comment by alan-agius4** [comment]
Note: this is also a blocker  for using dts_bundling with Ivy.

https://github.com/angular/angular/blob/e25b256aa4d00e8d8a43952bdbaaa567bdaa1277/packages/bazel/src/ng_module.bzl#L136-L154

**Comment by filipesilva** [comment]
@clydin mentioned that having the star imports causes `ɵɵdefineNgModule` etc to always be property accesses, thus preventing those names from being mangled. This was actually the first reason why we talked about removing the star imports but eventually I forgot about it.

Since the names repeat significantly they should compress to gzip well though.

**Comment by IgorMinar** [comment]
I believe that star imports if not abused or interacted with in unusual ways (e.g. metaprograming) should tree-shake at the same level as explicit imports.

So before we go about implementing this, we should prototype if explicit imports yield any improvements.

**Comment by alxhub** [comment]
(writing here for context as this has been discussed in meetings previously)

There is a technical limitation in the TS compiler where synthetic destructuring imports do not correctly downlevel to all module formats. This is why the compiler always uses import-* style imports.

Theoretically, depending on the target module format we could use one or the other, but this would be non-trivial to implement, and so we should only do it if there's a provable tree-shaking benefit.

**Comment by filipesilva** [comment]
Discussed further with @clydin, doesn't seem like there's anything we should do there. Webpack does treeshake these away, and also allows mangling the name.
