### ISSUE TITLE
Latest stable versions of every angular component

### ISSUE THREAD

**Issue by basickarl** [angular/angular#33791]
How does one get the latest stable release for every component. You guys are releasing RC's into the eco system which I have no interest in until it's considered stable. Where do I find the stable version for the following packages:

```
        @angular/animations
        @angular/cdk
        @angular/common
        @angular/compiler
        @angular/core
        @angular/forms
        @angular/material
        @angular/platform-browser
        @angular/platform-browser-dynamic
        @angular/router
```

**Comment by mlc-mlapis** [comment]
@basickarl Here: https://github.com/angular/angular/releases. The actual stable major version is 8 so the latest is always the last one, now 8.2.13.

**Comment by basickarl** [comment]
@mlc-mlapis Ah so if I'm correct all of those libraries have the same release cycle? (one version for them all?)

**Comment by mlc-mlapis** [comment]
@basickarl Yep, that's right.

**Comment by mlc-mlapis** [comment]
@basickarl The only exception on the list is `@angular/cdk` which could have a bit different releasing on the minor version.

**Comment by mlc-mlapis** [comment]
@basickarl And it's also maintained on https://github.com/angular/components/releases.

**Comment by basickarl** [comment]
@mlc-mlapis Ok dude perfect answer thanks man!
