### ISSUE TITLE
angular.io homepage doesn't load without cookies enabled

### ISSUE THREAD

**Issue by mverver-google** [angular/angular#33795]
# 📚 Docs or angular.io bug report

### Description

When the browser is configured not to accept cookies, the angular.io homepage shows a blank page without any content.

### What's the affected URL?**
https://angular.io/

### Reproduction Steps**
Disable cookies in your browser. Visit https://angular.io/

### Expected vs Actual Behavior**
Expected behavior: static content is visible as normal.
Actual behavior: page shows no content at all.

## 📷Screenshot
The page is completely blank; I don't think a screenshot would clarify the issue.

### Browser info
Issue is reproducible in both Chrome and Firefox.

**Comment by gkalpak** [comment]
Good catch! Apparently, when cookies are disabled accessing `window.sessionStorage` is an error, so [ScrollService][1] throws.

[1]: https://github.com/angular/angular/blob/master/aio/src/app/shared/scroll.service.ts

**Comment by gkalpak** [comment]
@ajitsinghkaler, would you like to take this on? This is a fairly straight forward issue and I would be happy to guide/help you through the process.

**Comment by ajitsinghkaler** [comment]
I would love to thank you for helping me get started.

**Comment by gkalpak** [comment]
Awesome! Thx, @ajitsinghkaler!

If this is your first time contributing to Angular, you can find some general instructions in [CONTRIBUTING.md][1] and also instructions related to angular.io (or aio for short) specifically in [aio/README.md][2].

Basically, the problem we have here is that we assumed `window.sessionStorage` will always be available. But when cookies are disabled, trying to even access `window.sessionStorage` throws an error.

A possible fix could be this:
Change aio's [ScrollService][3] to check whether `window.sessionStorage` is accessible and if not use a no-op stub. In code, this could look something like this (off the top of my head):

```ts
class ScrollService {
  private storage: Storage;

  constructor(...) {
    try {
      this.storage = window.sessionStorage;
    } catch {
      // When cookies are disabled in the browser, even trying to access
      // `window.sessionStorage` throws an error. Use a no-op storage.
      this.storage = {
        length: 0,
        clear: () => undefined,
        getItem: () => null,
        key: () => null,
        removeItem: () => undefined,
        setItem: () => undefined,
      };
    }

    ...
  }

  ...
}
``` 

Then, inside `ScrollService`, replace all occurrences of `window.sessionStorage` with `this.storage`.
Finally, we need some tests to ensure this works as expected and there will be no regressions. (I can help with that, when the time comes.)

##
I hope that makes sense (feel free to ask for help if anything isn't clear or if you get stuck down the road).

To avoid cluttering this thread with implementation details, I suggest you open a pull request with your initial changes (it doesn't matter if it is not complete) and continue the discussion there.

Thx again for taking this on 💯 

[1]: https://github.com/angular/angular/blob/b30bb8dd9/CONTRIBUTING.md
[2]: https://github.com/angular/angular/blob/b30bb8dd9/aio/README.md
[3]: https://github.com/angular/angular/blob/b30bb8dd9/aio/src/app/shared/scroll.service.ts
