### ISSUE TITLE
Dynamic Classes 

### ISSUE THREAD

**Issue by zamamohammed** [angular/angular#3380]
In Angular 1.X we used to create dynamic classes by using 
`ng-class="'panel-{{displayStatus}}'"`

but when I see in Angular 2.0, we use

`[class.panel-primary] = "isPrimary"`

Is their a way I can do `[class.panel-"displayStatus"]`

**Comment by kittencup** [comment]
[class] api https://angular.io/docs/js/latest/api/directives/CSSClass-class.html

**Comment by zamamohammed** [comment]
@kittencup I think thats a old documentation for `class` because I am getting this error:

`Can't bind to 'class' since it isn't a known property of the '<div>' element and there are no matching directives with a corresponding property`

I first thought that would work, but it didn't and saw some examples in this repo and saw how its being used now.

**Comment by kittencup** [comment]
import CSSClass from angular2/angular2

@View({
   directives:[CSSClass]
})


component class annation add this code

**Comment by zamamohammed** [comment]
I think I was missing this, but still `[class]="'panel-{{displaystatus}}'"` is not working as expected

**Comment by kittencup** [comment]
[class]='object or function'

function is return object 

object or function defined component class
