### ISSUE TITLE
Setting custom property in angular elements throws ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by Dannybrown2710** [angular/angular#33812]
Referring to this
https://github.com/angular/angular/issues/24415.

I have developed a component which accepts a configuration in object form.
`@Input() config` and I have exported it as a custom element.

While using in another module, I have passed the config as a html prop
`document.querySelector('ui-btn').config = {displayText:'click'}`

I am incurring the error ExpressionChangedAfterItHasBeenCheckedError 
`
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'null: undefined'. Current value: 'null: {
  "displayText": "click"
}'. 
`

**Comment by SantiagoIlli** [comment]
Can you provide a minimal reproduction?

**Comment by ajitsinghkaler** [comment]
@Dannybrown2710 we can try to reproduce this in a plunker with the angular versions and we can help everyone if this is an issue.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
