### ISSUE TITLE
What is the alternative for ::ng-deep?

### ISSUE THREAD

**Issue by chetanapadmane1** [angular/angular#33814]
Hi Team,
I am working on angular from last year.
I wanted to override the style of child component through parent component.
After reading document I got the information as ::ng-deep and >>> is deprecated now. What is the alternative for ::ng-deep excluding encapsulation none?

**Comment by rodolfojnn** [comment]
Duplicate of #17867 and #25160

**Comment by pkozlowski-opensource** [comment]
Yes, this is a duplicate of #25160
