### ISSUE TITLE
@angular/core/testing inject() bug.

### ISSUE THREAD

**Issue by kdshop** [angular/angular#33819]
# 🐞 bug report

### Affected Package

 The issue is caused by function `inject` from package @angular/core/testing

### Is this a regression?

 Possibly.

### Description

 When using "subscribe and assert" pattern inside `inject()` function `DoneFN` can't be called so test times out.

## 🔬 Minimal Reproduction
[https://github.com/kdshop/injectbug](https://github.com/kdshop/injectbug)

Just `npm i` and then `ng t` bug lives in `app.service.spec.ts`

## 🔥 Exception or Error
Jasmine returns message:
<pre><code>Error: Timeout - Async callback was not invoked within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
Error: Timeout - Async callback was not invoked within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
    at Jasmine
</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>Angular: 8.2.13
RxJS: 6.4.0
Jasmine: 3.4.0
</code></pre>

**Comment by JiaLiPassion** [comment]
@kdshop, this is not an issue, you are missing `()` after `inject`.

```
  it('should just work', (done: DoneFn) => {
    inject([SomeService], (appService: SomeService) =>
      appService.getObservable().subscribe(value => {
        expect(value).toBe(1);
        done();
      })
    )(); // here you need to call the function.
  });
```

**Comment by JiaLiPassion** [comment]
I accidentally clicked the `close and comment` button, please confirm and close this issue.

**Comment by IgorMinar** [comment]
thanks @JiaLiPassion  for looking into this. @kdshop I'll go ahead and close this issue. If you are still having problems please file a new bug and provide additional information that will help us understand the nature of issue you see. thanks
