### ISSUE TITLE
Router link stop the event propagation

### ISSUE THREAD

**Issue by tamascsaba** [angular/angular#3381]
When I click router link stop the event propagation with ``` return false; ```
https://github.com/angular/angular/blob/master/modules/angular2/src/router/router_link.ts#L59

why not only prevent the default action?

Typical use case: 
Bootstrap dropdown item not close after click the link (which is router-link too), because router-link stop event propagation

**Comment by gdi2290** [comment]
so the problem is that returning false does both `$event.stopPropagation()` and `$event.preventDefault()` when it should only do `$event.preventDefault()`

**Comment by tamascsaba** [comment]
Yes :)

**Comment by cexbrayat** [comment]
I was under the impression that an event handler returning false was only preventing default, not stopping the propagation. See https://github.com/angular/angular/issues/2042

**Comment by tamascsaba** [comment]
return false stop the event propagation. See: http://stackoverflow.com/a/1357151

**Comment by cexbrayat** [comment]
Oh in jQuery sure. But in Angular for now (as far as I know), it just prevents default.
As you can see here https://github.com/angular/angular/blob/master/modules/angular2/src/render/dom/view/view.ts#L82

and also in the docs  https://github.com/angular/angular/blob/master/modules/angular2/docs/core/01_templates.md#binding-events and in the issue I mentioned before.

Using alpha-32, I have to manually stop the propagation in my app.

**Comment by tamascsaba** [comment]
Thanks for the information, i close the issue.

**Comment by muniom** [comment]
I've just had some success with a similar issue: having an array of nav links in an ngFor, some required [routerLink], while others required (click) - my issue was that all links relied on [routerLink] for [routerLinkActive], so I had to stop routerLink, without touching it's value.

`<a [routerLink]="item.link" routerLinkActive="isActive">
    <span (click)="item.click ? item.click($event) : void>
</a>`
with:

`click: ($event) => {
    $event.stopPropagation(); // Only seems to
    $event.preventDefault(); // work with both
    // Custom onClick logic
}`
As the span is inside, you can be sure the cancelling of the event happens before it bubbles up to [routerLink], while routerLinkActive will still apply.

**Comment by tomrainedotcom** [comment]
I had the same problem but I found a work around
HTML
```
...
@Component({
    template: `<a [(routeLink)]="goto($event, ['status'])" routeLinkActive="active">Status</a>`
})
export class SomeComponent() {
    ...
    public goto(event: any, path: Array<string>) {
        // do some logic here
        if (path.indexOf('status')) {
            event.preventDefault();
            event.stopPropagation();
        }
        return path; // this is so the routeActiveLink still knows what the active path should be
    }
    ...
}
```
