### ISSUE TITLE
Custom directive - @Self() has null valueChanged observable property during ngOnInit

### ISSUE THREAD

**Issue by JamesHough** [angular/angular#33817]
# 🐞 bug report

### Affected Package
_Angular 9 RC2_
The issue is caused by package @angular/core@next

### Is this a regression?
Yes, the previous version in which this bug was not present was: v8.2.14

### Description
I have upgraded a project from `v8.2.14` to `v9.0.0-rc.2` . After the upgrade, a custom directive throws an error trying to access a null property on the control.

## 🔬 Minimal Reproduction
https://github.com/JamesHough/angular9-directive-error.git

The repo attached has a single custom directive `CleanUnusualCharactersDirective` which has a reference to the control in the constructor: `@Self() private control: NgControl`

When this directive executes `ngOnInit()` then the property "valueChanges" is null
```
ngOnInit(): void {
  this.subscriptions = this.control.valueChanges
    .pipe(distinctUntilChanged())
    .subscribe((v: string) => this.cleanInput(v));
}
```

This repo has the previous working version on Angular 8.2.14 in the commit history.

## 🔥 Exception or Error
Error in the JavaScript console:
<pre><code>
core.js:6161 ERROR TypeError: Cannot read property 'pipe' of null
    at CleanUnusualCharactersDirective.ngOnInit (clean-unusual-characters.directive.ts:34)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.2
Node: 12.5.0
OS: win32 x64
Angular: 9.0.0-rc.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.2
@angular-devkit/build-angular     0.900.0-rc.2
@angular-devkit/build-optimizer   0.900.0-rc.2
@angular-devkit/build-webpack     0.900.0-rc.2
@angular-devkit/core              9.0.0-rc.2
@angular-devkit/schematics        9.0.0-rc.2
@ngtools/webpack                  9.0.0-rc.2
@schematics/angular               9.0.0-rc.2
@schematics/update                0.900.0-rc.2
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Comment by benelliott** [comment]
Related to #32522

**Comment by JamesHough** [comment]
I see related issue is closed and a test case covering my scenario was added in PR #34026

Closing this issue for now. I will retest with the next release.

**Comment by JamesHough** [comment]
Confirmed. Working in RC4
