### ISSUE TITLE
Potential bug: HTML imports being used, which will soon be deprecated

### ISSUE THREAD

**Issue by jburtondev** [angular/angular#33825]
Hi there, our team is using Angular 6 and are getting the following error when running our automation suite: 

```
WARNING deprecation - HTML Imports is deprecated and will be removed in M80, around February 2020. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.
```

Is Angular Elements using HTML Imports? I don't believe so, it should be using ES6 modules right?  As per: https://github.com/angular/angular/blob/master/packages/elements/src/create-custom-element.ts

**Comment by IgorMinar** [comment]
Hi @jburtondev,

We don't use Html Imports so that warning must be coming from some other code outside of the Angular framework.

**Comment by jburtondev** [comment]
@IgorMinar thanks for confirming 👍
