### ISSUE TITLE
Avoid calling abort on XMLHttpRequest in the http module

### ISSUE THREAD

**Issue by jahtalab** [angular/angular#33822]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/http

### Is this a regression?

 It seems to have been like this for a while

### Description
The http package (more specifically xhr_backend) calls `abort` on the XMLHttpRequest object once the load event is fired. While this is acceptable in most applications, it makes it hard for 
 other libraries that instruments XMLHttpRequest, to keep track of the XHR correctly, e.g. for  observability purposes. Furthermore calling `abort` on the XHR object changes the state of the object (e.g. readyState is set to 0) which would also result in inconsistent tracking of the XHR.

Relevant code lines:
* https://github.com/angular/angular/blob/master/packages/http/src/backends/xhr_backend.ts#L149
* https://github.com/angular/angular/blob/master/packages/http/src/backends/xhr_backend.ts#L92

**Comment by djleonskennedy** [comment]
@angular/http deprecated use  @angular/common/http

**Comment by IgorMinar** [comment]
yup. thanks @djleonskennedy. in fact  @angular/http was removed from our distribution in v8.0.

we will soon delete the  @angular/http from our repo.
