### ISSUE TITLE
no global export

### ISSUE THREAD

**Issue by blacksonic** [angular/angular#3382]
I started playing with Angular2, the public built code from http://code.angularjs.org , but after version alpha30 it doesnt export a global ```window.angular``` object. Is it intentional?

**Comment by gdi2290** [comment]
the global is now `window.ng` since there is a requirement of having angular2 work alongside angular1 (that ises `window.angular`)
https://code.angularjs.org/2.0.0-alpha.32/angular2.sfx.dev.js

**Comment by pkozlowski-opensource** [comment]
@gdi2290 is right, closing.
