### ISSUE TITLE
No provider for ApplicationRef in Angular 9 RC2 & RC3

### ISSUE THREAD

**Issue by jinder** [angular/angular#33821]
# 🐞 bug report

### Affected Package
@angular/router I think

### Is this a regression?
Yes, Angular 8 compiled fine.

### Description
Since upgrading to Angular 9 RC2,  I'm now seeing a No provider for ApplicationRef error.  This might be disguising another error, but it's very difficult to debug.  The project uses NGRX.

## 🔥 Exception or Error
<pre><code>
main.ts:13 NullInjectorError: R3InjectorError[RouterModule -> Router -> ApplicationRef -> ApplicationRef -> ApplicationRef]: 
  NullInjectorError: No provider for ApplicationRef!
    at NullInjector.get (http://localhost:4200/vendor.js:36972:27)
    at R3Injector.get (http://localhost:4200/vendor.js:52450:33)
    at R3Injector.get (http://localhost:4200/vendor.js:52450:33)
    at R3Injector.get (http://localhost:4200/vendor.js:52450:33)
    at injectInjectorOnly (http://localhost:4200/vendor.js:36851:33)
    at ɵɵinject (http://localhost:4200/vendor.js:36861:57)
    at injectArgs (http://localhost:4200/vendor.js:36954:23)
    at Object.factory (http://localhost:4200/vendor.js:52813:42)
    at R3Injector.hydrate (http://localhost:4200/vendor.js:52676:63)
    at R3Injector.get (http://localhost:4200/vendor.js:52438:33)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.0-rc.2
Node: 12.13.0
OS: win32 x64
Angular: 9.0.0-rc.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.2
@angular-devkit/build-angular     0.900.0-rc.2
@angular-devkit/build-optimizer   0.900.0-rc.2
@angular-devkit/build-webpack     0.900.0-rc.2
@angular-devkit/core              9.0.0-rc.2
@angular-devkit/schematics        9.0.0-rc.2
@angular/cdk                      9.0.0-rc.1
@ngtools/webpack                  9.0.0-rc.2
@schematics/angular               9.0.0-rc.2
@schematics/update                0.900.0-rc.2
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Comment by naveedahmed1** [comment]
Delete `node_modules` and run `npm install` again.

**Comment by kukjevov** [comment]
Interesting thing is that this happened to me also several times, mostly removing `node_modules` and reinstalling helped, but last time i had to clean also `npm cache`. I am just curious why this happens? It looks like random thing.

**Comment by naveedahmed1** [comment]
@jinder please reopen this issue, since this issue still exists. Removing node_modules sometimes works and sometimes doesn't work.

**Comment by jinder** [comment]
I agree - it didn't help me

**Comment by jaipresto** [comment]
Same here. Had the problem and others very similar with several Angular 9 releases. Tried so many things - starting afresh, removing and reinstalling and removing and reinstalling packages, playing around with various injector `providedIn` settings - but nothing changes. Only disabling Ivy works.

**Comment by gnanakeethan** [comment]
Same here too. I reverted the Router to RC1, and it seemed to be working fine. 

I feel something is wrong with the Router than the Compiler itself.

**Comment by didaktio** [comment]
@gnanakeethan I did this, nuked the node_modules and reinstalled. The postinstall script ran and now it's compiling just fine. Good find!

**Comment by didaktio** [comment]
> @gnanakeethan

Update: It worked once. The error came back after I installed another package an recompiled :(

**Comment by didaktio** [comment]
So the fix for now is to include `ApplicationModule` in the main app module imports. It seems the problem is related to the `BrowserModule`, which is supposed to bring this along when imported. I'm now using the latest everything, with aot and Ivy enabled, and it's working.

**Comment by mlc-mlapis** [comment]
@didakti What is `ApplicationModule`?

**Comment by gnanakeethan** [comment]
I am not sure what else is wrong. I just shared what worked for me. Just in case. 😄

**Comment by neil-119** [comment]
I'm seeing this too, and unfortunately deleting node_modules and reinstalling did not fix it for me.

**Comment by mlc-mlapis** [comment]
@neil-119 Where are you importing the `BrowserModule`?

**Comment by jaipresto** [comment]
Importing `ApplicationModule` worked in `app.module.ts` worked for me. It
resolved the above error and another one related to
`ApplicationInitStatus`. `BrowserModule` was included by default in my
ionic app, but I still had the problem. The hover comment(?) states that
the `BrowserModule` imports this by default, but something must be off.

**Comment by jaipresto** [comment]
(repost) 
Importing `ApplicationModule` worked in `app.module.ts` worked for me. It resolved the above error and another one related to `ApplicationInitStatus`. `BrowserModule` was included by default in my ionic app, but I still had the problem. The hover comment(?) states that the `BrowserModule` imports this by default, but something must be off.

**Comment by jaipresto** [comment]
> (repost)
> Importing `ApplicationModule` worked in `app.module.ts` worked for me. It resolved the above error and another one related to `ApplicationInitStatus`. `BrowserModule` was included by default in my ionic app, but I still had the problem. The hover comment(?) states that the `BrowserModule` imports this by default, but something must be off.

@mlc-mlapis Just read your comment - perhaps my issue is related to ionic (where yes, I'm building only a web app)?

**Comment by jinder** [comment]
@didaktio Including ApplicationModule directly worked for me!

**Comment by neil-119** [comment]
@mlc-mlapis `BrowserModule` is imported in `AppModule` in our app.

**Comment by mlc-mlapis** [comment]
@neil-119 So, if I understand correctly, it is at the top-level module of your app, right?

**Comment by jinder** [comment]
Doing a fresh ng upgrade on the repo seems to have fixed the issue for me.  I think this may be caused by some issue problem with the upgrade process - but the error isn't conveyed to the user.

**Comment by IgorMinar** [comment]
can someone please create a reproduction of this as a minimal CLI project posted as a repo on github? or please provide exact sequence of steps to create such project and reproduce this error.

based on the number of reports and our inability to reproduce this, I do believe that the problem is real, but without a repro we can't do anything to fix it.

**Comment by jinder** [comment]
@IgorMinar I think it’ll be very difficult to create a repo for this issue.  I tried ng upgrade on the same code base for a second time and it started to work.  There was no difference in my code or the dependencies.  I also noticed there was an issue with a @ViewChild decorator on Angular CDK tree component not working, which also resolved itself magically after doing a fresh upgrade.  It leads me to think that it’s something to do with how Ivy handles decorators...

**Comment by jaipresto** [comment]
I started with an Ionic project and ran ng update to upgrade to Ivy and Angular 9. I noticed only today that the @angular/compiler wasn't included in the dependencies but the _devDependencies_. Perhaps this is related to the above problems - the `ng update` schematic doesn't pick up that this or other packages aren't correctly arranged/installed. Upgrading to rc4 and moving the package to the production has allowed me to remove `ApplicationModule` from the` app.module.ts` imports. Things seem to be operating fine. For now.

**Comment by jinder** [comment]
Is anyone still experiencing this with the latest RC?  It is not longer occurring for me, so I will close the ticket unless there are objections.

**Comment by jaipresto** [comment]
All good here :)

**Comment by neil-119** [comment]
Seems to be working here as well. Will report if anything changes. Thanks!

**Comment by manughub** [comment]
Pls advice if you're still seeing the issue, else we'll go ahead and close the ticket.
