### ISSUE TITLE
ERROR in src/app/app.module.ts:6:37 - error TS2307: Cannot find module '@xxx/xxx'.

### ISSUE THREAD

**Issue by walidabouzaid** [angular/angular#33833]
Although, I've created, built, and published an angular 8 library as your Angular.IO docs. I face this showstopper bug. See below attachment.
![thiqahNPMCriticalIssue](https://user-images.githubusercontent.com/19210082/68894929-5a6f5f00-0739-11ea-8e92-10ccc70c53f6.png)

The module of my library can't be imported unless I import it like below.
`import { ThiqahTreeLibModule } from '@thiqah/tree/src/lib/thiqah-tree-lib.module';`

**Comment by Dj-jom2x** [comment]
it means there's no index on it xD

**Comment by walidabouzaid** [comment]
@Dj-jom2x 
Angular CLI should create index on it xD :( form its self. I see it not my job to create a file not mentioned on your angular.io docs.
https://angular.io/guide/creating-libraries

**Comment by Dj-jom2x** [comment]
nope xD you need to export it inside public-api.ts manually

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
