### ISSUE TITLE
Using zone.js >0.10.0 in an angular changes the PropertyDescripton of the imported references

### ISSUE THREAD

**Issue by AlexMa1er** [angular/angular#33846]
# 🐞 bug report

### Affected Package
The issue is caused by package zone.js since version 0.10.0.

### Is this a regression?
Yes, the previous version in which this problem was not present was: <=0.9.1

### Description
The following problem occurs during the test process. (Therefore, no statement can be made as to whether this causes problems at real runtime)

Create a angular 8 app, update zone.js to "0.10.0" (or higher). Afterwards the PropertyDescripton of the references are changed and (in our concrete case) special spies in our tests can no longer be executed.

## 🔬 Minimal Reproduction
Cannot reproduce it under a stackblitz.com sample project. However, for all projects created with the Angular CLI.

https://github.com/AlexMa1er/angular-issue-repro-zonejs

Run the 'SpyReferences' (spy.references.spec) Test. From the version onwards, the spy can no longer be executed.

## 🔥 Exception or Error
<pre><code>
Spec List | Failures

SpyReferences > should a spyable reference
Error: Expected false to be truthy.
    at <Jasmine>
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/app/spy.references.spec.ts:9:29)
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:365:1)
    at ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:305:1)

SpyReferences > should spy the rxjs-interval method reference
Error: interval is not declared configurable
	    at <Jasmine>
	    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/app/spy.references.spec.ts:13:5)
	    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:365:1)
	    at ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:305:1)
	    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:364:1)
	    at Zone.run (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:124:1)
	    at runInTestZone (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:554:1)
	    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:569:1)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.19
Node: 10.15.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.19
@angular-devkit/build-angular     0.803.19
@angular-devkit/build-optimizer   0.803.19
@angular-devkit/build-webpack     0.803.19
@angular-devkit/core              8.3.19
@angular-devkit/schematics        8.3.19
@angular/cli                      8.3.19
@ngtools/webpack                  8.3.19
@schematics/angular               8.3.19
@schematics/update                0.803.19
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

**Comment by JiaLiPassion** [comment]
@AlexMa1er, this is not a bug, but a behavior change, before `zone.js 0.10.0`, zone.js will automatically patch `Object.defineProperty` and try to make every property `configurable = true` to make some old browser's API patchable, but it will cause some other problems, so from `zone.js 0.10.0`, with `evergreen browser`, zone.js will not patch `Object.defineProperty` automatically, so when you call `Object.defineProperty` and `Object.getOwnPropertyDescriptor`, you are using the `native` one. And in your case `configurable = false` is the correct result.

So to make this work as before, you need to 
1. create a new `polyfill.zone-patch-object.ts`, and copy the content from `polyfill.ts`.
2. add following line before `import zone`.
```
import './zone-test-flag';
import 'zone.js/dist/zone-legacy';
(window as any)['__zone_symbol__legacyPatch']();
```
3. create a file called `zone-test-flag.ts`
```
(window as any).__Zone_disable_registerElement = true;
(window as any).__Zone_disable_EventTargetLegacy = true;
```
4. update `angular.json` create a new `target` to point to this new polyfill.

**Comment by AlexMa1er** [comment]
Thank you for the detailed description. The test **implementation** now **works again.** 

One more question,
I only did the explicit `zone-legacy` import, without the `zone-test-flag.ts` implementation. 
Is the `zone-test-flag.ts` adjustment necessary, or is this due to the executor definition (in karma conf)?

thx, best regards

**Comment by JiaLiPassion** [comment]
It is not necessary, just to disable some features of legacy browsers, it will have no impact to the behavior.
