### ISSUE TITLE
ngAfterViewInit not called correctly when transcluded by <ng-content>

### ISSUE THREAD

**Issue by Yona-Appletree** [angular/angular#33842]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?

Not sure. The bug appears in both Angular 7 and 8.

### Description

The `ngAfterViewInit` lifecycle hook isn't called for a component that is transcluded using `<ng-content>` which itself is within an `*ngIf`.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-playground-vqhjuh

## 🔥 Exception or Error

No error, but the hooks aren't called at the correct time.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.6
@angular-devkit/build-angular     0.803.6
@angular-devkit/build-optimizer   0.803.6
@angular-devkit/build-webpack     0.803.6
@angular-devkit/core              8.3.6
@angular-devkit/schematics        8.3.6
@angular/cli                      8.3.6
@ngtools/webpack                  8.3.6
@schematics/angular               8.3.6
@schematics/update                0.803.6
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.39.2
</code></pre>

**Comment by Yona-Appletree** [comment]
This is a duplicate of #13921 and probably a good use case for #13925. I may potentially create another issue requesting DOM hooks.

**Comment by mhevery** [comment]
So this works as intended. `ngAfterViewInit` init gets called on creation, regardless if the content is transcluded or not. This is by design and it is how Web-components work which this is modeld on. 

You can see this in your test case because `1. In Container: ngAfterViewInit` gets created automatically on creation.
