### ISSUE TITLE
Binding doesn't work on value attribute of <progress> element in IE11

### ISSUE THREAD

**Issue by tkrugg** [angular/angular#3384]
Here is a [sample](http://plnkr.co/edit/NVrbDEy53lHfFGlHMu7P?p=preview) that illustrates it. As you can see the progress element stays at value=0.

seen on IE11 with angular 1.4

**Comment by pkozlowski-opensource** [comment]
@tkrugg this is a repo for angular 2. Please report ng1-related issues in https://github.com/angular/angular.js

Thnx!

**Comment by tkrugg** [comment]
sorry
