### ISSUE TITLE
Angular run npm start not show image

### ISSUE THREAD

**Issue by donhuvy** [angular/angular#33847]
Please see https://stackoverflow.com/questions/58873194/angular-run-npm-start-not-show-image

I am reading https://angular.io/guide/template-syntax#template-syntax .

I download https://angular.io/generated/zips/template-syntax/template-syntax.zip

![abc](https://user-images.githubusercontent.com/1328316/68931500-4112f500-07c3-11ea-9b11-1fbcdc493756.png)

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
