### ISSUE TITLE
Implement 'ng-value-checked' / 'ng-value-unchecked'

### ISSUE THREAD

**Issue by adamdbradley** [angular/angular#3385]
When using checkbox inputs, it'd be great to also get the input's `value` too, rather than just a boolean if the input is checked or not. This would be similar to ng1's `ng-true-value` and `ng-false-value`. I'd also relate this to when a form is posted, and when the checkbox is `checked=true`, then its `value` is what is submitted, and when the input doesn't have a value, then the value of `on` would be submitted.

In this plnkr, the form control is telling me if the checkboxes are checked or not, but I'd really like to know their values rather than having to cross-reference somewhere else in my code that `checkbox1.checked=true` means the value of `apples`.
http://plnkr.co/edit/Yd966WZDrkLfOft0SMLw?p=preview

**Comment by lucecene** [comment]
+1

**Comment by ObaidUrRehman** [comment]
Will this be implemented?

**Comment by jainanuj0812** [comment]
@naomiblack , Have we implemented this yet, or we have to settle down with the other approaches.

Can you please make sure you describe in comments, why we have closed this one it's not clear why we have.
