### ISSUE TITLE
"Updating to Angular Version 9" - Code contains incorrect hyperlink to @angular/forms

### ISSUE THREAD

**Issue by andrewseguin** [angular/angular#33859]
Docs page: https://next.angular.io/guide/updating-to-version-9

For some reason, the code snippet under "Updating CLI Apps" contains a hyperlink to `api/forms/NgModel#update`

![WLK2HjsgmC5](https://user-images.githubusercontent.com/22898577/68970068-5116de80-079b-11ea-9375-0b3dc89b7224.png)

**Comment by IgorMinar** [comment]
@petebacondarwin should we work around this by not using syntax highlighting / code snippet or is this an easy fix?

**Comment by petebacondarwin** [comment]
I suggest that we change the auto-code-linking so that it either:

* does not try to link blocks that are marked as `bash` language
* only links blocks that are marked as `ts` language

**Comment by petebacondarwin** [comment]
https://github.com/angular/angular/pull/33877 should fix this.
