### ISSUE TITLE
"ERROR in Unable to write a reference to" building with Ivy

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#33850]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core, or compiler-cli

### Is this a regression?

 No

### Description

Building using ivy shows the following error:
```
ERROR in Unable to write a reference to MemoryFormatter in D:/sandbox/dashboard/src/app/frontend/common/pipes/memoryformatter.ts from D:/sandbox/dashboard/src/app/frontend/common/pipes/module.ts    
```

## 🔬 Minimal Reproduction
```
git clone https://github.com/filipesilva/dashboard
cd dashboard
git checkout fs-test-setup
yarn
ng build --aot --prod
```

## 🔥 Exception or Error
<pre><code>
ERROR in Unable to write a reference to MemoryFormatter in D:/sandbox/dashboard/src/app/frontend/common/pipes/memoryformatter.ts from D:/sandbox/dashboard/src/app/frontend/common/pipes/module.ts  
</code></pre>

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 9.0.0-rc.2
Node: 10.16.0
OS: win32 x64
Angular: 9.0.0-rc.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.2
@angular-devkit/build-angular     0.900.0-rc.2
@angular-devkit/build-optimizer   0.900.0-rc.2
@angular-devkit/build-webpack     0.900.0-rc.2
@angular-devkit/core              9.0.0-rc.2
@angular-devkit/schematics        9.0.0-rc.2
@angular/cdk                      8.2.3
@angular/flex-layout              8.0.0-beta.27
@angular/http                     7.2.15
@angular/material                 8.2.3
@ngtools/webpack                  9.0.0-rc.2
@schematics/angular               9.0.0-rc.2
@schematics/update                0.900.0-rc.2
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Anything else relevant?**
This seems similar to https://github.com/angular/angular/issues/33659 and https://github.com/angular/angular/issues/33562, but this project is not a monorepo. The project has one path alias to the same application, but I tried removing it and it didn't seem to make a difference.

cc @alxhub @petebacondarwin @gkalpak

**Comment by filipesilva** [comment]
Seems to be fixed by https://github.com/angular/angular/pull/33828

**Comment by AndrewKushnir** [comment]
@filipesilva thanks for reporting the issue, feel free to reopen this ticket if the problem still exists after #33828. Thank you.
