### ISSUE TITLE
ngSwitchCase doesn't handle undefined properly

### ISSUE THREAD

**Issue by eseliger** [angular/angular#33873]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/common

### Is this a regression?

No

### Description

It's currently impossible to use the type system to forbid invalid states. An example for that would be:

```
{
isLoadingProject: boolean
project?: Project | null
}
```
would result in 6 possible configurations, of which only 3 would be a valid state. To handle that case better, the following is possible

```
{
	project?: Project | null
}
```

Using ngSwitch however, there is currently no distinction to make between undefined (still loading) and null (not found) and hence, the following template always shows both the loader and the not found method if the value of project is `null`

```
<ng-container [ngSwitch]="project">
            <div *ngSwitchCase="undefined">
                Loading project
            </div>
            <div *ngSwitchCase="null">
                Project not found!
            </div>
            <div *ngSwitchDefault>
                {{ project | json }}
            </div>
        </ng-container>
```

This is because ngSwitch uses `==` and not `===`, while in javascript
```
null == undefined // true
null === undefined // false
```

The line in question is https://github.com/angular/angular/blob/8.2.14/packages/common/src/directives/ng_switch.ts#L135 and changing it makes it work properly and helps me handle all those invalid states with this simple approach.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-wqgssr

This stackblitz goes through all three valid states, 

- undefined (loading)
- an object (loaded project)
- null (not found)

What to look for: The loading and not found messages are both shown at the same time for undefined and null cases.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.2
Node: 12.13.0
OS: darwin x64
Angular: 9.0.0-rc.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.2
@angular-devkit/build-angular     0.900.0-rc.2
@angular-devkit/build-optimizer   0.900.0-rc.2
@angular-devkit/build-webpack     0.900.0-rc.2
@angular-devkit/core              9.0.0-rc.2
@angular-devkit/schematics        9.0.0-rc.2
@ngtools/webpack                  9.0.0-rc.2
@schematics/angular               9.0.0-rc.2
@schematics/update                0.900.0-rc.2
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Comment by petebacondarwin** [comment]
For what it is worth, it is possible to constrain the states discussed at the start of the issue:

```ts
interface Project {
  name: string;
}

type LoadingProject = IsLoadingProject | LoadedProject | UnknownProject;

interface IsLoadingProject {
  isLoading: true;
}

interface LoadedProject {
  isLoading: false;
  project: Project;
}

interface UnknownProject {
  isLoading: false;
  project: null;
}
```

**Comment by petebacondarwin** [comment]
Changing `ngSwitch` to treat falsy values differently would be a breaking change.
I think we would want to have some kind of update migration that parsed the possible switches for values that could be falsy and therefore no longer match the more constrained check.
It is possible we could have a configuration in `ngSwitch` to turn this additional constraint on the equality on...

**Comment by robert-king** [comment]
potential workaround: use ternary operator

```

<div class="action-container">
  <ng-container [ngSwitch]="fileItem?.progress ? fileItem?.progress : -1">
    <mat-icon *ngSwitchCase="100">check</mat-icon>
    <ng-container *ngSwitchCase="-1">
      <ng-content>
      </ng-content>
    </ng-container>
    <mat-progress-spinner
      *ngSwitchDefault
      [diameter]="20"
      mode="determinate"
      [value]="fileItem?.progress">
    </mat-progress-spinner>
  </ng-container>
</div>

```

**Comment by pkozlowski-opensource** [comment]
Re-labelling it as a bug. We should fix it but this would be a breaking change. Need to weight on the cost / benefit here.
