### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by gidon-handler** [angular/angular#33876]
While Angular is a technological marvel, I can't understand why we need to go to such length to animate an element when it can be done with two lines of CSS. 
The code here is from the docs. Why all the fuss when I can do it so simply with CSS.
What am I missing (not talking about Route transition animations).

  ```
 selector: 'app-open-close',
  animations: [
    trigger('openClose', [
      // ...
      state('open', style({
        height: '200px',
        opacity: 1,
        backgroundColor: 'yellow'
      })),
      state('closed', style({
        height: '100px',
        opacity: 0.5,
        backgroundColor: 'green'
      })),
      transition('open => closed', [
        animate('1s')
      ]),
      transition('closed => open', [
        animate('0.5s')
      ]),
    ]),
  ],
  templateUrl: 'open-close.component.html',
  styleUrls: ['open-close.component.css']
})
```

**Comment by Airblader** [comment]
If you're happy using CSS, use CSS. Take another look at the animation framework when you want to do a complex animation and can't figure out how to do it in CSS.

**Comment by IgorMinar** [comment]
@gidon-handler the animation package indeed enables you to construct animations that are much more complex than what you can express via CSS. Additionally for some animations, you need to coordinate the DOM insertions and removals with the duration of CSS transitions or animations and for this you will need to help the renderer understand what you want the animation to look like.

If you however need just some simple effects, then please by all means use css transitions or animations.

I'll go ahead and close this issue as it's not really actionable and I hope I provided enough info that helps you understand what to you when.
