### ISSUE TITLE
ng8 vs ng5 different CORS behaviour

### ISSUE THREAD

**Issue by cakeinpanic** [angular/angular#33880]
# 🐞 ng8 ang ng5 HttpClient behave differently

### Affected Package
` "@angular/core": "8.2.13"`
vs
` "@angular/core": "5.2.11"`

### Description

I am refactoring the app, at the same moment migrating angular from 5 to 8
In both apps I have the same request that is sent to a backend that is working on localhost
I am running both frontend applications on the same port(not simultaneously, in rotation)
If the request is sent from ng5-app, everything operates normally, if from ng8-app – I'm getting an error 

`The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
`

This error _can be fixed on the backed_ by specifying `Access-Control-Allow-Origin` header,  but my question is why there is a difference in behaviour between two versions of angular

## 🔬 Minimal Reproduction
The cURL of both requests are the same:
`
curl 'http://localhost:4007/bo/accounts' -X OPTIONS -H 'Sec-Fetch-Mode: cors' -H 'Access-Control-Request-Method: GET' -H 'Origin: http://localhost:4400' -H 'Referer: http://localhost:4400/' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36' -H 'Access-Control-Request-Headers: env' --compressed
`

**Comment by pkozlowski-opensource** [comment]
@cakeinpanic hmmm, this sounds really interesting but _unlikely_ that Angular version change would impact anything in terms of CORS behaviour. Since we can't investigate it on our end I'm afraid that you will have to dig deeper and try to narrow down the issue more.

There is nothing we can do given the set of information provided...

**Comment by cakeinpanic** [comment]
I have created isolated repo, but everything operates normally in in. Seems that problem is no only in ng5 and ng8, would investigate deeper

**Comment by alxhub** [comment]
Thanks, I'll go ahead and close this issue.
