### ISSUE TITLE
angular renderer insertBefore method element, only one

### ISSUE THREAD

**Issue by WuZhenXing** [angular/angular#33889]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
I created a directive，add a divider to each child element, but only one divider.
example：
| is divider.
12345 is elements.
In the for loop
step1:  1 | 2345
step2:  12 | 345
step3:  123 | 45
step4:  1234 | 5
divider moving....
divider is not the same instance

I think it's the life cycle of angular

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-raxuw7

## 🔥 Exception or Error
<pre><code>

Incorrect operation result
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

 "@angular/core": "^8.2.11",
</code></pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
