### ISSUE TITLE
strictMetadataEmit causing unclear error message to occur during build

### ISSUE THREAD

**Issue by mhintzke** [angular/angular#33888]
# 🐞 bug report

### Affected Package
This appears to be a compiler issue so my guess would be @angular/compiler-cli

### Is this a regression?
Not sure, I have never used this feature before

### Description

I believe a specific compiler options called `strictMetadataEmit` is the problem. Either the error is displaying as a false positive, or this code is supposed to fail the build, but maybe a better error message is required.

When using the CLI to create a new Angular Library like `ng new library`, the tsconfig.lib.json contains an `angularcompilerOptions` property called `strictMetadataEmit` that is set to `true` by default. When I try to build the following code, I get the error message: 
```
ERROR in C:/Test/Test/application/src/app/app.module.ts:16:1: Error encountered in metadata generated for exported symbol 'AppModule': 
 C:/Test/Test/application/src/app/app.module.ts:10:22: Metadata collected contains an error that will be reported at runtime: Lambda not supported.
  {"__symbolic":"error","message":"Lambda not supported","line":9,"character":21}
```

```
import { JwtModule, JWT_OPTIONS } from '@auth0/angular-jwt';

export function jwtOptionsFactory() {
    return {
        // It believes there is a lambda here when this is clearly an anonymous function and is
        // completely valid JS, so I don't understand how it could be invalid.
        tokenGetter: function () {  
            return null;
        }
    };
}

@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [
        BrowserModule,
        JwtModule.forRoot({
            jwtOptionsProvider: {
                provide: JWT_OPTIONS,
                useFactory: jwtOptionsFactory,
                deps: []
            }
        })
    ],
    providers: [],
    bootstrap: [AppComponent]
})
export class AppModule { }

```

As soon as I do this, however, it builds just fine.
```
export function jwtOptionsFactory() {
    function tokenGetter () {  
        return null;
    }

    return {
        tokenGetter: tokenGetter
    };
}
```

So it doesn't seem to be mad about a lambda, but rather a simple anonymous function, right? Am I missing some other lambda here or is the error mesage just a little unclear?

## 🔬 Minimal Reproduction
Just pull this down and run `ng build`. The above code is my actual application code and doesn't reflect what is in this repository.
https://github.com/mhintzke/angular-cli-aot-example

## 🔥 Exception or Error
<pre><code>
ERROR in C:/Test/Test/application/src/app/app.module.ts:16:1: Error encountered in metadata generated for exported symbol 'AppModule': 
 C:/Test/Test/application/src/app/app.module.ts:10:22: Metadata collected contains an error that will be reported at runtime: Lambda not supported.
  {"__symbolic":"error","message":"Lambda not supported","line":9,"character":21}
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.19
Node: 10.15.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.19
@angular-devkit/build-angular      0.803.19
@angular-devkit/build-ng-packagr   0.803.19
@angular-devkit/build-optimizer    0.803.19
@angular-devkit/build-webpack      0.803.19
@angular-devkit/core               8.3.19
@angular-devkit/schematics         8.3.19
@angular/cli                       8.3.19
@ngtools/webpack                   8.3.19
@schematics/angular                8.3.19
@schematics/update                 0.803.19
ng-packagr                         5.7.1
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Comment by alxhub** [comment]
The good news is that in Ivy there is no `metadata.json`, so `strictMetadataEmit` and all of it's weirdness will no longer be an issue!

**Comment by mhintzke** [comment]
@alxhub Ok that sounds like good news. Is it possible to confirm that the scenario I laid out above will not throw any time of error at all then? If so, I'm ok with closing this and just waiting for Ivy

**Comment by alxhub** [comment]
@mhintzke indeed, the scenario you described won't cause any errors in Ivy in 9. I'm going to close this issue :)
