### ISSUE TITLE
Angular IVY - Chrome UX Reports URL as SLOW  - Main Bundle Size for Mid size applications is still large

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#33881]
# 🐞 bug report

### Affected Package
Angular 9.0.0-rc.2

### Is this a regression?
 No

### Description

I have a mid size app (Mustakbil.com), when I build it for productions the size of my main bundle (es2015) is 1.17Mb. If I use bundle analyzer to explore the main bundle, the size of the Angular related modules is 891kb, rxjs is 105kb, @firebase is 20kb.

![mustakbil-main-bundle](https://user-images.githubusercontent.com/7761180/69007584-72c1c280-0961-11ea-8ddb-1581ebe89ee1.jpg)

For users with fast internet connections and desktop machines it shouldn't be a problem that's why I have a lighthouse score of 100.

![mustakbil-lighthouse](https://user-images.githubusercontent.com/7761180/69007616-ec59b080-0961-11ea-94ee-3465e1b1f37b.jpg)

But for slow mobile devices with slow internet connection the lighthouse score isn't very impressive:

![mustakbil-lighthouse-slow-devices](https://user-images.githubusercontent.com/7761180/69007710-0a73e080-0963-11ea-9cb5-fe0aacb24604.jpg)

The lighthouse scores of angular.io and next.angular.io are not much different.

It appears that in general Angular websites are slow for mobile devices.

May be that's the reason that even Google's own conference (ChromeDev Summit) have more mentions about React, Next.js and Vuejs than Angular.

Angular team has done excellent work on Angular IVY, which indeed has greatly improved overall bundle size and lighthouse scores.

It would be great if more efforts could be put on optimizing performance for slow mobile devices, and we have a mobile first strategy for Angular Framework and Angular Components.

One thing to point out is that the framework currently supports lazyloading components through routes but loazyloading other components/modules is not very simple may be a better api and features could be added. So that we can conditionally load modules/components.

**Comment by kschwidder** [comment]
I agree to the findings. We compiled our app with IVY rc2 (--prod) and the size is 3.3 MB instead of 1.6MB with angular 8.x The size of the bundle is definitely to big. I hope that the final release is far better. 
As stated with IVY it was the goal to reduce the bundle size heavily :-)

State of IVY is promising so far except some inconvenience with external libs (ngx-charts e.g.)

**Comment by dogmatico** [comment]
I've to check with the a RC, but with previous v9 and v8 Ivy build we found that the optimization isn't working as with VE and much more packages are put into the main bundle.

For example, we use an app shell with route and custom elements, using the aio technique, lazy loading. Libraries, like parts of Angular Material or Luxon, which were used in lazy-loaded parts of the application were moved to the main bundle after building with Ivy enabled. This was the sole cause of the increase of size with Ivy, being the other components more or less of the same size.

**Comment by naveedahmed1** [comment]
In my case IVY reduced app size as well as main bundle size. But my concern is that the size of main bundle is still large.

Though for desktop and fast internet connection it's not an issue but for mobile with slow internet connection it certainly is an issue. As a result it will also have negative affect on website's SEO.

Especially because Google is now showing pages as slow in Search Console where:

FCP is longer than 3s (mobile)
FID is longer than 300ms (mobile)

The Pagespeed diagnostic shows that much of the time is spend on script evaluation, and I believe that's because of the size of main bundle.

**Minimize Main Thread Work**
![minimize-main-thread-work](https://user-images.githubusercontent.com/7761180/69054711-0365d480-0a2e-11ea-8a1b-56f906dde087.jpg)

**Reduce Javascript Execution Time**
![reduce-javascript-execution-time](https://user-images.githubusercontent.com/7761180/69054721-08c31f00-0a2e-11ea-9860-f5dddad00ea5.jpg)


> State of IVY is promising so far except some inconvenience with external libs (ngx-charts e.g.)

I agree, I am also having issue with ngx-charts, and I have already reported it here https://github.com/angular/angular/issues/33864

**Comment by naveedahmed1** [comment]
Let me also share Chrome UX report from Search Console, in August we upgraded to Angular IVY, the Speed report takes around 28 days to reflect changes. And you can see that on around Sep 24, it did improve the speed for some of the urls to moderate level but its still not fast.

![chrome-ux-report](https://user-images.githubusercontent.com/7761180/69063336-25ffe980-0a3e-11ea-9bfd-3d85d99b8cdf.jpg)

**Comment by naveedahmed1** [comment]
@IgorMinar if you want I can add you to a private repository as well.

**Comment by vthinkxie** [comment]
Hi @IgorMinar 
we meet the same problem, the bundle size of Ivy(9.0.0-rc.3) is about 60% larger than ViewEngine

Ivy
![image](https://user-images.githubusercontent.com/1506722/69319164-a199aa80-0c79-11ea-817d-4f92ab6c63aa.png)

ViewEngine
![image](https://user-images.githubusercontent.com/1506722/69319188-aeb69980-0c79-11ea-962f-052c07b0adcc.png)



here is the html file generated by source-map-explorer

[diff.zip](https://github.com/angular/angular/files/3873504/diff.zip)

**Comment by filipesilva** [comment]
The related issue on the CLI repo is https://github.com/angular/angular-cli/issues/16146.

**Comment by waterplea** [comment]
In my case I have a workspace with several libraries I develop. In Angular 8 if I only use one module from one library in an application, I see that it only grabbed like 1KB from my library in prod build. With Angular 9 a lot of my library gets added to the final bundle. I've created an issue about it but couldn't provide a reproduction due to proprietary nature of the library. I use custom decorators heavily, could this be a reason?

**Comment by IgorMinar** [comment]
We are investigating this issue. So far the root cause has not been determined, but since we can't reproduce it on many common apps, we suspect it's going to be some kind of edge-case with large impact on affected apps.  We'll figure out what's going on.

**Comment by IgorMinar** [comment]
There are several reports of this size regression. If we find no evidence of this being caused by multiple root causes, we'll dedupe these issues and consolidate updates to just one.

**Comment by vthinkxie** [comment]
> In my case I have a workspace with several libraries I develop. In Angular 8 if I only use one module from one library in an application, I see that it only grabbed like 1KB from my library in prod build. With Angular 9 a lot of my library gets added to the final bundle. I've created an issue about it but couldn't provide a reproduction due to proprietary nature of the library. I use custom decorators heavily, could this be a reason?

We also use lots of custom decorators, it might be the reason.

**Comment by dogmatico** [comment]
> > In my case I have a workspace with several libraries I develop. In Angular 8 if I only use one module from one library in an application, I see that it only grabbed like 1KB from my library in prod build. With Angular 9 a lot of my library gets added to the final bundle. I've created an issue about it but couldn't provide a reproduction due to proprietary nature of the library. I use custom decorators heavily, could this be a reason?
> 
> We also use lots of custom decorators, it might be the reason.

We don't use custom decorators and we have detected the same issue of modules used in lazy modules and components moved to the main bundle after enabling Ivy.

**Comment by kschwidder** [comment]
We are using lazy loading via Router heavily. We will run the analyzer to Check the difference. Ivy seems to have General issue with Bigger projects than with Hello world.

**Comment by mlc-mlapis** [comment]
Ahh, it could be just a simple and trivial hidden bit, which affects a lot of logic. When you discover it, you can solve all those problems in a second. 😃

**Comment by filipesilva** [comment]
Hey all,

This issue contains two different things: 
- a discussion of the Chrome UX Reports for mid size applications
- reports of main bundle size increasing after updating to ivy/version 9

If you want to discuss the Chrome UX reports please continue doing so on this issue.

If you are seeing **larger main bundles** but **smaller lazy bundle or lesser number of lazy bundles** after updating from Angular version 8 to version 9, please instead follow https://github.com/angular/angular-cli/issues/16146. You will find a description of what's happening and what you can do right now in https://github.com/angular/angular-cli/issues/16146#issuecomment-557559287.

**Comment by Splaktar** [comment]
> One thing to point out is that the framework currently supports lazy loading components through routes but lazy loading other components/modules is not very simple.  Maybe a better api and features could be added. So that we can conditionally load modules/components.

It's not fully streamlined yet, but the process for lazy loading components described by [this post](https://medium.com/angular-in-depth/lazy-load-components-in-angular-596357ab05d8) seems like a viable path for improving your bundle size and performance reports.

**Comment by naveedahmed1** [comment]
Thank you so much @Splaktar for sharing this wonderful post, I recently started exploring this topic and already gone through similar post at https://dev.to/binarysort/manually-lazy-load-components-in-angular-8-ffi , the one you shared seems more comprehensive. If you have also gone through this article, can you please guide which approach is better and recommended?

**Comment by IgorMinar** [comment]
hi there, we believe these issues have been resolved already in the recent RCs, if you can still reproduce the problem, please check out this comment and file a new issue with repro: https://github.com/angular/angular-cli/issues/16146#issuecomment-579935603

thank you!

**Comment by naveedahmed1** [comment]
Thank you @IgorMinar I believe https://github.com/angular/angular-cli/issues/16146 is a separate issue (its about bundle sizes) as @filipesilva mentioned in comment https://github.com/angular/angular/issues/33881#issuecomment-557561876

This issue is about Chrome UX Reports. 

With 9.0.0-rc.7, for most of the urls of my website, Search Console reports the page speed as **Moderate** instead of **Slow** (in my case the default crawler is Google Smartphone Crawler), We have yet to deploy and test the a version with latest RC. We're also going for Lazy Loading Non-Routable Components. I can share the impact after the deployment. It takes about 28 days for Search Console to show the impact of the change on website speed after the deployment.

I would request you to please close this issue only if someone has actually verified that the issue has been fixed.

Thank you!

**Comment by Splaktar** [comment]
> Thank you so much @Splaktar for sharing this wonderful post, I recently started exploring this topic and already gone through similar post at https://dev.to/binarysort/manually-lazy-load-components-in-angular-8-ffi , the one you shared seems more comprehensive. If you have also gone through this article, can you please guide which approach is better and recommended?

Sorry, I have not yet had an opportunity to implement this approach in an app. However, I will note that the one you linked is designed for Angular version 8, where the one that I liked was designed for Angular version `9.0.0-rc.6` w/ Ivy. The more recent article seems like it would be the best approach to try with your Ivy app.

**Comment by IgorMinar** [comment]
@naveedahmed1 chrome UX reports is an overly aggregate status signal that is very difficult for us to action, that being said, the critical path bundle size is well known to be the one of the primary factors afecting the chrome UX metrics. We do believe that all of the size regressions caused by Ivy related changes in the build pipeline have been resolved. If there are any remaining issues affecting Chrome UX reports, we'll need a new issue opened, focused on the particular scenario with a good reproduction.

I also suggest that you test with lighthouse and webpagetest.org which will give you instant feedback rather than monitoring the significantly delayed chrome ux reports. The chrome ux reports are a great final check, but are not the right tool to debug performance issues.

Lastly, I agree with what was said on this thread - we do need more fine-grained lazy-loading story. In v9 you can lazy load individual components with a few caveats, and post-v9 now that Ivy which was a prerequisite for enabling fine-grained lazy loading, we'll finally be able to make it a first-class construct in Angular.
