### ISSUE TITLE
EventEmitter () with the name "change"

### ISSUE THREAD

**Issue by postnikovpasha** [angular/angular#33890]
Why when changing <select> EventEmitter () called "change" is called?
At the same time, EventEmitter () with the name "change" is used in a completely different function and is in no way associated with <select>.
```
HTML:
    <select [(ngModel)]="profileArr[6]" class="inputProfile" id="language">
      <option value="ru-RU">Русский</option>
      <option value="en-US">English</option>
    </select>
```
```
ts:  
@Output() change = new EventEmitter();

  changePassword() {
    this.change.emit('changePassword');
  }
```

**Comment by Airblader** [comment]
`change` is a native event. You should name the emitter something else.

**Comment by pkozlowski-opensource** [comment]
Note: the main problem here is that we've got no way of distinguishing DOM events vs. directive outputs. This is already traced in #4593 / #4059

**Comment by postnikovpasha** [comment]
Is it written somewhere in the documentation? I can not find.

**Comment by IgorMinar** [comment]
it doesn't help that your styleguide uses `change` @Outputs in several examples: https://angular.io/guide/styleguide#decorate-input-and-output-properties
