### ISSUE TITLE
Is there any way to prevent  "ngOndestroy" hook triggering?

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular#33892]
# 🚀 feature request

IS there any way to prevent "angular" hook getting triggered.

I need this because of below :
https://stackoverflow.com/questions/58875510/how-to-delay-ngondestroy-hook-calling-while-components-destroy

**Comment by kumaresan-subramani** [comment]
@alan-agius4 , i am expecting your suggestion. Please check this.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
