### ISSUE TITLE
packaging of @angular/bazel changes esm5.bzl to a format that breaks buildifier_check

### ISSUE THREAD

**Issue by SeanCondon** [angular/angular#33906]
# 🐞 bug report

### Affected Package
@angular/bazel

### Is this a regression?
Yes this seems to be present in at least all of 8.2.x releases

### Description
When I download @angular/bazel from npmjs.org at
https://registry.npmjs.org/@angular/bazel/-/bazel-8.2.13.tgz

I can see that the file src/esm5.bzl has a whitespace tab where some text is removed by the packager. This tab causes problems for the buildifier_check tool in bazel when I try to build

So the original file has this 
https://github.com/angular/angular/blob/341d5847d6a7d3f922040f5baf11f7bc64e6f9bc/packages/bazel/src/esm5.bzl#L98
specifically:
```
    elif replay_compiler_name.startswith("ngc-wrapped"):
        compiler = ctx.executable._ngc_wrapped

        # BEGIN-INTERNAL
        # If the "replay_compiler" path does not refer to "ngc_wrapped" from the "@npm" workspace,
        # we use "ngc_wrapped" from within the Angular workspace. This is necessary because we
        # don't have a "npm" workspace with the "@angular/bazel" NPM package installed.
        if replay_compiler_path != ctx.executable._ngc_wrapped.short_path:
            compiler = ctx.executable._internal_ngc_wrapped

        # END-INTERNAL
    else:
        fail("Unknown replay compiler", target.typescript.replay_params.compiler.path)
```
where as the npmjs.org file from https://registry.npmjs.org/@angular/bazel/-/bazel-8.2.13.tgz has a `tab` in place of the `#BEGIN-INTERNAL` to `#END-INTERNAL`
```
    elif replay_compiler_name.startswith("ngc-wrapped"):
        compiler = ctx.executable._ngc_wrapped

        
    else:
        fail("Unknown replay compiler", target.typescript.replay_params.compiler.path)

```
It is this tab that the linter `buildifier_check` does not like.

## 🔬 Minimal Reproduction
Download the file from 
https://registry.npmjs.org/@angular/bazel/-/bazel-8.2.13.tgz
to see the difference

## 🔥 Exception or Error
I'm using this in a branch of the [ONOS](https://gerrit.onosproject.org/c/22800) project and I have `@angular/bazel` 8.2.13 in my `package.json`
```
scondon@Z420:~/onos$ bazel run //:buildifier_check
INFO: Writing tracer profile to '/RaidData/scondon/.cache/bazel/_bazel_scondon/9eee44166e74bfc121cf827da25d905e/command.profile.gz'
INFO: Analyzed target //:buildifier_check (43 packages loaded, 6897 targets configured).
INFO: Found 1 target...
Target //:buildifier_check up-to-date:
  bazel-bin/buildifier_check.bash
INFO: Elapsed time: 9.911s, Critical Path: 1.11s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
./web/gui2-fw-lib/node_modules/@angular/bazel/src/esm5.bzl # reformat
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.19
Node: 10.16.0
OS: linux x64
Angular: 8.2.14
... animations, bazel, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.19
@angular-devkit/build-angular      0.803.19
@angular-devkit/build-ng-packagr   0.803.19
@angular-devkit/build-optimizer    0.803.19
@angular-devkit/build-webpack      0.803.19
@angular-devkit/core               8.3.19
@angular-devkit/schematics         8.3.19
@angular/cli                       8.3.19
@angular/http                      7.2.15
@bazel/bazel                       0.28.1
@bazel/bazel-linux_x64             0.28.1
@bazel/hide-bazel-files            0.40.0
@bazel/karma                       0.34.0
@bazel/protractor                  0.34.0
@bazel/typescript                  0.34.0
@ngtools/webpack                   8.3.19
@schematics/angular                8.3.19
@schematics/update                 0.803.19
ng-packagr                         5.7.1
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Anything else relevant?**
No

**Comment by devversion** [comment]
Thanks for the issue. I tried having a quick look, and it's indeed true that buildifier will fail when it checks the `esm5.bzl` file provided by `@angular/bazel`.

Though I'm not sure if it's something we should fix, or care about (in terms of future `.bzl` files we ship). It seems that the buildifier check that is set up in the `onos` repo should not check for files inside of the `node_modules`? or is there a good reason to do so?

**Comment by SeanCondon** [comment]
Thanks for looking at it - my experience with Buildifier is that it does not ignore `.bzl` files in `node_modules` - not sure why. It's not a big deal, but at the same time it would not seem to be too big an item to fix and what's the point in formatting rules if they are made to be broken

**Comment by jelbourn** [comment]
Closing this since we don't expect anyone to be formatting files inside of `node_modules`
