### ISSUE TITLE
Shall we allow @Component on a web component?

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#3391]
While working on the schema support I've stumbled upon this situation: let's say that we've got a real web components that produces content. The question would be: shall we allow @Component directives on real web components? Doing so would get us into the situation where there are 2 parties competing / creating shadow DOM entries.

Currently we've got [a test](https://github.com/angular/angular/blob/cb6fc9c7cb7216b6c160260c29b56fe91bd10913/modules/angular2/test/render/dom/view/proto_view_builder_spec.ts#L53) that assumes that if a @Component matched a given DOM element, this element can't be a web component. But this is kind of backwards for me - that is - I would rather say that we shouldn't allow @Component directives on web components (?)

@tbosch IMO this test is wrong and we should replace the logic in a compiler to either:
* properly detect web components
* disallow @Components on web components

//cc: @mhevery

**Comment by tbosch** [comment]
Yes, we should not allow web components / custom elements and angular `@Component` elements on the same DOM element. The only trouble is that we can't check for web components during compilation, as compilation might (and soon will) happen in a build step where web components are not alive.

**Comment by pkozlowski-opensource** [comment]
Yeh, while we could detect web components during in-browser compilation, I guess it is tough in the server-side environment.... But I guess this is where different element schemas  come into play, no? The DOM-based schema (used for in-browser compilation) could auto-detect web components and throw errors accordingly. For the server-side compilation we would have another schema (either hand-written or "dumb" ).

WDYT?

**Comment by mhevery** [comment]
Sounds good to me.

**Comment by mhevery** [comment]
Can we close this issue, and replace it with concrete issue as to what needs to be done?

**Comment by pkozlowski-opensource** [comment]
Right, now that the initial question is answered we can close it and handle actionable items in https://github.com/angular/angular/issues/3424
