### ISSUE TITLE
Missing locale data for the locale "ne" for Country nepal 

### ISSUE THREAD

**Issue by santosTT** [angular/angular#33929]
# 🐞 bug report
when i import locale id if 'ne' in app module I.e.   providers: [

    { provide: LOCALE_ID, useValue: "ne" }
  ],
And i try to use the angular pipe of currency in template 
i.e {{ value | currency }}
![image](https://user-images.githubusercontent.com/53549906/69304658-82832480-0c49-11ea-9f58-5d3ad292999e.png)

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
 "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/material": "^7.3.7",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
       "angular-linq": "^1.0.6",
    "angular2-text-mask": "^9.0.0",
    "bootstrap": "^4.3.1",
    "core-js": "^2.5.4",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jquery": "^3.4.1",
       "linqts": "1.10.0",
    "ngx-toastr": "^10.0.2",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by ajitsinghkaler** [comment]
I cannot see your issue properly can you please elaborate it.

**Comment by santosTT** [comment]
> ![Desktop screenshot (7)](https://user-images.githubusercontent.com/39260684/69257612-5b910800-0be1-11ea-96d5-16fe7016122e.png)
> I cannot see your issue properly can you please elaborate it.

I have provide locale id in app.module of 'ne' and with using currency pipe it gives error as 
![image](https://user-images.githubusercontent.com/53549906/69304727-cece6480-0c49-11ea-8197-4f7bfec86df6.png)

**Comment by ajitsinghkaler** [comment]
You have to edit your issue to keep in a format given in the guidelines please edit it.

**Comment by IgorMinar** [comment]
did you include the locale data? we do support `ne` locale: https://github.com/angular/angular/blob/master/packages/common/locales/ne.ts

Please see: https://angular.io/guide/i18n#i18n-pipes

Without a reproduction it's hard to help here, so if the issue persists please provide a minimal repro of the issue. thanks!
