### ISSUE TITLE
Proxy Configuration Issues with WebSockets 

### ISSUE THREAD

**Issue by rodrigocasillas** [angular/angular#33925]
Hello. I've been trying to send firebase traffic through a Configured Proxy but have not been able to accomplish it. Except for normal requests.
Is it posible to proxy Firebase Internet activity?. If so, is there a way to do it? Am I missing something?
I understand that firebase works with WebSockets. 
According to WebSockets docs this should be possible, but I'm not sure if angular/ionic can achieve this, which is why I'm sending you this message.  
I would appreciate any help on this topic. Thank you in advance.

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular` or in this case `firebase`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
