### ISSUE TITLE
ngx-formly fails at runtime with: ASSERTION ERROR: index

### ISSUE THREAD

**Issue by juristr** [angular/angular#33924]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

Yes this worked seemlessly with ViewEngine under Angular 8.

### Description

 A clear and concise description of the problem...

When using [ngx-formly](https://github.com/ngx-formly/ngx-formly) with Ivy the app breaks. The **compilation succeeds without issues** but at **runtime** immediately when opening the app, I get the exception

```
ERROR Error: ASSERTION ERROR: index
    at throwError (core.js:1222)
    at assertLessThan (core.js:1196)
    at ViewContainerRef_._adjustIndex (core.js:17181)
    at ViewContainerRef_.insert (core.js:17104)
    at ViewContainerRef_.move (core.js:17131)
    at ViewContainerRef_.insert (core.js:17108)
    at FormlyField.renderField (ngx-formly-core.js:1165)
    at ngx-formly-core.js:1155
    at FormlyWrapperFormField.set [as fieldComponent] (ngx-formly-core.js:261)
    at FieldWrapper_Query (ngx-formly-core.js:1794)
```
which starts [here](https://github.com/ngx-formly/ngx-formly/blob/v5/src/core/src/lib/components/formly.field.ts#L111) in the Formly library.

## 🔬 Minimal Reproduction

Pointing to a GitHub repo as it strangely "works" (?) on Stackblitz.

1. `git clone git@github.com:juristr/superforms-talk.git`
1. `git checkout upgrade-ng9`
1. `yarn install` (or `npm install`)
1. Go to http://localhost:4200/formly-basics/person-simple

The example is broken as the Material components don't animate properly and the devtools console gives the `ASSERTION ERROR: index` as mentioned above

## 🔥 Exception or Error
<pre><code>

ERROR Error: ASSERTION ERROR: index
    at throwError (core.js:1222)
    at assertLessThan (core.js:1196)
    at ViewContainerRef_._adjustIndex (core.js:17181)
    at ViewContainerRef_.insert (core.js:17104)
    at ViewContainerRef_.move (core.js:17131)
    at ViewContainerRef_.insert (core.js:17108)
    at FormlyField.renderField (ngx-formly-core.js:1165)
    at ngx-formly-core.js:1155
    at FormlyWrapperFormField.set [as fieldComponent] (ngx-formly-core.js:261)
    at FieldWrapper_Query (ngx-formly-core.js:1794)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.0-rc.2
Node: 11.6.0
OS: darwin x64
Angular: 9.0.0-rc.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.2
@angular-devkit/build-angular     0.900.0-rc.2
@angular-devkit/build-optimizer   0.900.0-rc.2
@angular-devkit/build-webpack     0.900.0-rc.2
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@ngtools/webpack                  9.0.0-rc.2
@schematics/angular               0.6.8
@schematics/update                0.900.0-rc.2
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

Reporting it here, but could also be related to some ngx-formly implementation issue

**Comment by gnomeontherun** [comment]
I've also run into this in Clarity in our tabs component.

**Comment by petebacondarwin** [comment]
This should fix the problem : https://github.com/angular/angular/pull/34052

**Comment by juristr** [comment]
@petebacondarwin Awesome 👏. Once the next RC is out I'll give it another try. Thanks a lot
