### ISSUE TITLE
Override Events

### ISSUE THREAD

**Issue by TiagoBraga39** [angular/angular#3392]
Hi all!

Is it possible to override an event or function?
I need a component with a standard behaviour, but in certain times I want to override the event.

Here is what I came up with:
```javascript
@Component({
    selector: 'topbar',
    events: [
        'closeViewCallback: onClose' // Events with dash-case transform into camelCase
    ]
})
export class Topbar {
    constructor() {
        this.closeViewCallback = new EventEmitter();
    }
    closeView($event) {
       this.closeViewCallback.next($event);
       console.log("Close View inside component.");
    }
}
```
From outside of the component I now can either do:
```html
Option a) <topbar></topbar>
Option b) <topbar (on-close)="closeView()"></topbar>
```

But this was a small hack since inside the topbar component I have 2 callback function (the standard and the passed by parameter).

<b>Is it possible to override events OR at least check if there is anyone from the outside of the component listening to an event?</b>

<b>Outside the topbar component:</b>
```javascript
closeView($event) {
   console.log("Close View outside component.");
}
```

<b>Inside the topbar component:</b>
```javascript
closeView($event) {
   this.closeViewCallback.next($event);
   console.log("Close View inside component.");
}
```

---
<h3>Result</h3>
<h4>Using option a)</h4>
// prints "Close View inside component."
<h4>Using option b)</h4>
// prints "Close View outside component."
// prints "Close View inside component."

**Comment by TiagoBraga39** [comment]
So I just tested the this.closeViewCallback property in both options, and they are equal... (used ===)
Any ideas how can I solve the thread?

**Comment by mhevery** [comment]
It is really not clear to me what are you asking. Perhaps start with a problem first?

**Comment by TiagoBraga39** [comment]
@mhevery Thank you for your feedback.
As you may see, I have a topbar component, which has a close button with an internal behaviour on it. All I want is to be able to override that behaviour.
<b>Let's say:</b> I want the default event on clicking on the close button to actually be closing the view.
<b>But</b> in a specific view I want it to open a dialog to confirm closing of the view.

I could use event emmiters, and that works fine, but beside that, I wanted a default behaviour.

Best regards,
Tiago Braga

**Comment by mhevery** [comment]
I think you are asking: "Can the button know if someone is listening to it?" The short answer is that it would create weird behavior, and so we don't want to add that API.

Closing as I don't think there is anything for us to do.
