### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MartinM25** [angular/angular#33932]
Hi...Im planning to connect a JSON api to my angular project...was hoping if i could get some guidelines

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by konradekk** [comment]
I guess that Angular [HTTPClient guide](https://angular.io/guide/http) should be a definite answer here—tell here if anything is missing in the documentation regarding this matter.

**Comment by ajitsinghkaler** [comment]
@gkalpak I think you ca close this issue
