### ISSUE TITLE
Angular 8 with custom hammer config not working anymore after upgrade

### ISSUE THREAD

**Issue by REPTILEHAUS** [angular/angular#33934]
Some strange issues popped up after upgrading angular in the context of an ionic app (however this is angular related so posting here).

Mentioning this as I believe it is related to the main issue (Custom hammer gestures), after upgrade I got this error 

```
TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
```

Which I solved by including the following polyfil to make it play nicely with ```"target":"es2015",```

```
import '@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js';
```

With that issue solved it took a while to notice that for some reason, an no errors being thrown, my custom gesture config is broken:

```
core.js:38790 The "pressup" event cannot be bound because Hammer.JS is not loaded and no custom loader has been specified.
```

Previously this had been working absolutely fine... some code from my application below stripped for brevity:

app.module.ts

```
....
import { BrowserModule, HAMMER_GESTURE_CONFIG } from '@angular/platform-browser';
....
{ provide: HAMMER_GESTURE_CONFIG, useClass: GestureServiceService },   
...
```

GestureServiceService
```
import { Injectable } from '@angular/core';
import { HammerGestureConfig } from "@angular/platform-browser";

/**
 * @hidden
 * This class overrides the default Angular gesture config.
 */
@Injectable({
  providedIn: 'root'
})
export class GestureServiceService extends HammerGestureConfig {

  buildHammer(element: HTMLElement) {
    const mc = new (<any>window).Hammer(element);

    for (const eventName in this.overrides) {
      if (eventName) {
        mc.get(eventName).set(this.overrides[eventName]);
      }
    }

    return mc;
  }
  
}
```

Any help much appreciated, I cant find too much online about it however i think this issue might be related 

```
angular-cli: 1.0.0-beta.28.3
node: 10.16.0
os: darwin x64
@angular/common: 8.2.14
@angular/core: 8.2.14
@angular/fire: 5.2.3
@angular/forms: 8.2.14
@angular/http: 7.2.15
@angular/material: 8.2.3
@angular/platform-browser: 8.2.14
@angular/platform-browser-dynamic: 8.2.14
@angular/router: 8.2.14
@angular/cli: 8.3.19
@angular/compiler: 8.2.14
@angular/compiler-cli: 8.2.14
@angular/language-service: 8.2.14
```

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

If you can have a reproduction for us, please re-open new issue with exact steps to reproduce it. (Stackplitz or github repo to clone)
