### ISSUE TITLE
Renderer2 is undefined when wrapped in setTimeout block. Cannot read property 'removeClass' of undefined

### ISSUE THREAD

**Issue by imnickvaughn** [angular/angular#33938]
# 🐞 bug report

### Affected Package
The issue is caused by import Renderer2 in package @angular/core 

### Is this a regression?
Unsure

### Description
I expect that when I use Renderer2 to addClass within a setTimeout() that it will do so after the delay,
Instead after the delay, an error is thrown. Renderer2 is undefined by the time it gets called.

## 🔬 Minimal Reproduction
Here I have tried using Renderer2 Factory and Renderer2 itself.  If you click on the first button it will throw the error because it is wrapped in a setTimeout(). The second one is not wrapped in a setTimeout so it will not throw an error.
https://stackblitz.com/edit/angular-renderer2factorytest

## 🔥 Exception or Error
'''
ERROR
Error: Cannot read property 'removeClass' of undefined
'''

## 🌍  Your Environment

**Angular Version:**
@angular/common8.0.0
@angular/compiler8.0.0
@angular/core8.0.0
@angular/forms8.0.0
@angular/platform-browser8.0.0
@angular/platform-browser-dynamic8.0.0
@angular/router8.0.0
core-js2.6.9
rxjs6.5.2
zone.js

**Comment by pkozlowski-opensource** [comment]
This has nothing to do with Angular, you are falling into the `this` "trap"of JavaScript...
Here is the fixed stackblitz: https://stackblitz.com/edit/angular-renderer2factorytest-ek8k1d?file=src/app/app.component.ts
