### ISSUE TITLE
Angular Elements in Vanilla & Angular Consuming/Parent Applications

### ISSUE THREAD

**Issue by warrendugan** [angular/angular#33942]
Angular Elements show a lot of promise to enterprises running multiple projects so we can keep things DRY. However, getting Angular Elements consumed in another app is still quite a chore. I'd love to see this process simplified. 

Currently I'm able to overcome the zone duplication issue in Angular consumers by piggy backing off the zone in the consuming Angular application (Reference: https://angular-extensions.github.io/elements/#/docs/change-detection) by removing zone.js from polyfills in the angular elements application and bootstrapping like such:
`  
platformBrowserDynamic()
    .bootstrapModule(AppModule, { ngZone: (window as any).ngZone })
    .catch((err) => console.log(err));
`
Then I set up the consuming app module like such:
`
export class AppModule {
  constructor(private ngZone: NgZone) {
    (window as any).ngZone = this.ngZone;
  }
}
`

That is working and I'm not getting any rxjs issue either, however, I'm not able to get Angular Elements to work in BOTH an Angular consumer and Vanilla JS consumer. I've tried loading zone through a cdn but am having no luck. 

Is there anything in the works for getting Angular Elements consumed without so much configuration for any/all framework(s)?

Your input is very much appreciated!

**Comment by danielgeri** [comment]
@warrendugan it sounds like you've had some luck with rendering an Angular Element component for either the Angular consumer or vanilla js application, but I can't tell. Any chance you can share your implementation? It is difficult to find solid examples of this

**Comment by gkalpak** [comment]
I believe the main underlying problem is being able to easily consume Angular Elements in non-Angular apps, for which we don't have a great solution yet. Let's track this in #25421.
