### ISSUE TITLE
specs.http.zip Project Fails

### ISSUE THREAD

**Issue by mousedownmike** [angular/angular#33945]
# 📚 Docs or angular.io bug report

### Description

The project in specs.http.zip does will not run `ng test`

### What's the affected URL?**

https://angular.io/guide/http#testing-http-requests
https://angular.io/generated/zips/http/specs.http.zip

### Reproduction Steps**

1. Download https://angular.io/generated/zips/http/specs.http.zip
1. Extract and change into the folder...
2. Run `npm install`
3. Run `ng test`
Observe:
```
ERROR in src/app/heroes/heroes.service.spec.ts(7,22): error TS2307: Cannot find module './hero'.
src/app/heroes/heroes.service.ts(9,22): error TS2307: Cannot find module './hero'.
```

### Expected vs Actual Behavior**
Expected tests to run and succeed but tests do not run.

## 🔥 Exception or Error
<pre><code>
mike@zem:~/Downloads/specs.http$ ng test
 40% building 12/12 modules 0 active20 11 2019 13:10:53.634:WARN [karma]: No captured browser, open http://localhost:9876/
20 11 2019 13:10:53.653:INFO [karma-server]: Karma v4.1.0 server started at http://0.0.0.0:9876/
20 11 2019 13:10:53.653:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
20 11 2019 13:10:53.676:INFO [launcher]: Starting browser Chrome
                                                                                              
ERROR in src/app/heroes/heroes.service.spec.ts(7,22): error TS2307: Cannot find module './hero'.
src/app/heroes/heroes.service.ts(9,22): error TS2307: Cannot find module './hero'.

</code></pre>

### Browser info
```
ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.19
Node: 10.17.0
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.3.19
@angular/cli                      8.3.19
@ngtools/webpack                  8.0.0
@schematics/angular               8.3.19
@schematics/update                0.803.19
rxjs                              6.5.3
typescript                        3.4.5
webpack                           4.30.0
```

**Comment by gkalpak** [comment]
This will be fixed by #33941.

**Comment by mousedownmike** [comment]
Happy to close this one as duplicate... sorry I didn't find that one in my search.

**Comment by mousedownmike** [comment]
I confirmed that my test case now succeeds using assets from the staging url: https://pr33941-f5c7991.ngbuilds.io/guide/http#testing-http-requests

Nice!
