### ISSUE TITLE
ngIfUseIfTypeGuard: confusing documentation and deprecation?

### ISSUE THREAD

**Issue by Airblader** [angular/angular#33943]
### Description

The referenced page describes the following:

> Directives that behave like *ngIf can declare that they want the same treatment by including a static member marker that is a signal to the template compiler to treat them like *ngIf. This static member for *ngIf is:
> ```
> public static ngIfUseIfTypeGuard: void;
> ```

It's not very clear that the pattern has to be `xyzUseIfTypeGuard` for input `xyz` (that's how it is – right?). At the very least this deserves to be polished, however I also wonder whether this feature deserves to be deprecated given that we now have `ngTemplateGuard_xyz` which can do the same and is much more generic.

In fact I was unable to finde a code path that actually implements this (old) logic. Does it even still exist?

### What's the affected URL?**
https://angular.io/guide/aot-compiler#custom-ngif-like-directives

**Comment by kapunahelewong** [comment]
Removing this reference per https://github.com/angular/angular/pull/34435#discussion_r358441328.

**Comment by JoostK** [comment]
The `ngIfUseIfTypeGuard` field is indeed no longer used in Ivy and the documentation has since been removed.
