### ISSUE TITLE
ngSwitchCase no longer accepts multiple values

### ISSUE THREAD

**Issue by pauldraper** [angular/angular#33953]
# 🚀 feature request

### Relevant Package

@angular/common

### Description

Upgrading to Angular 2 has a feature regression, when multiple match values for ngSwitchCase are supported.

https://docs.angularjs.org/api/ng/directive/ngSwitch 

This was raised in https://github.com/angular/angular/issues/12174 but it was closed and locked due to old issue bad new issue good.

### Describe the solution you'd like

Angular 1 uses string tokenization and ngSwitchWhenSeparator,

I however prefer ngSwitchCases direction that accepts a list of values to match.

### Describe alternatives you've considered

Copy-paste.

Manually create common template definition and instantiate it.

**Comment by niteshbisht** [comment]
It seems to work as expected can be closed
