### ISSUE TITLE
How to get the current library name?

### ISSUE THREAD

**Issue by tailamphat** [angular/angular#33951]
Hi everyone,

I created a library in Angular workspace, inside a component, I want to get the library name but I searched on Google and found nothing.
How can I get the library's name in the library?

**Comment by santoshyadav198613** [comment]
Any reason, you want to do that, the one solution is to read from package.json. you can ask this question on stackoverflow you will get the answer.

**Comment by tailamphat** [comment]
Thanks. I move to stackoverflow https://stackoverflow.com/questions/58967540/how-to-get-the-current-library-name
