### ISSUE TITLE
Remove `hostActions`

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#3396]
We should remove hostActions since we agreed that using ElementRef and Renderer directly is a better approach.

This is a breaking change.

**Comment by typotter** [comment]
Without HostActions, what is the recommended way to focus an element?
`ElementRef.nativeElement.focus()` ?

**Comment by mhevery** [comment]
@typotter yes

**Comment by PascalPrecht** [comment]
@vsavkin could you quickly summarize why this is the better to deal with that? Performance?

**Comment by mhevery** [comment]
@PascalPrecht It is simpler for the developer. No need to create new concepts. The reason we had actions was to deal with WebWorkes, but CustomRenderer are better solutions there.
