### ISSUE TITLE
The Date pipe returns incorrect week numbers

### ISSUE THREAD

**Issue by anxious-witch** [angular/angular#33961]
Hi, I believe I've come across a bug in the date parsing. I haven't seen any indications that this is expected behavior, so I'm opening an issue here.

# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common: ^6.1.9

### Is this a regression?

 Not that I've seen.

### Description

 
The Date pipe has some unexpected behavior when it comes to weeks. A week is defined as a period of exactly 7 days (according to Wikipedia), and according to ISO 8601, the first week of a year is the week containing the first Thursday of the year.

By these rules, 2019 has 52 weeks, and 2020 has 53 weeks.

E.g. the first week of 2020 is the week from 30th of December to the 5th of January. 
The Date pipe returns the period from December 29th to December 31st as week 53, and January 1st of 2020 as week 1. 

The date parsing has an extra week in 2019, which has 3 days, which seems like unexpected behavior.

## 🔬 Minimal Reproduction

 https://angular-issue-repro2-ycvycu.stackblitz.io

```js
{{ '2019-12-29T00:00:00' | date:'w' }}
```

**Comment by ajitsinghkaler** [comment]
Can I try to solve this

**Comment by dannyskoog** [comment]
I can confirm that this behaviour is even the same in the latest "next" version (`9.0.0-rc.3`). And yes, it seems like a bug

**Comment by petebacondarwin** [comment]
@ajitsinghkaler feel free to have a crack at this.

**Comment by ajitsinghkaler** [comment]
Thanks I'll try this
