### ISSUE TITLE
Windows build error: Generating Skylark documentation dir for docs (2 files) failed (Exit 9009)

### ISSUE THREAD

**Issue by theodorejb** [angular/angular#33965]
# 🐞 bug report

### Affected Package
bazel?

### Description

When I try to build Angular on Windows (running the command `node ./scripts/build-packages-dist.js`) it always goes part way and then fails with "ERROR: C:/users/theod/documents/github/angular/packages/bazel/docs/BUILD.bazel:3:1: Generating Skylark documentation dir for docs (2 files) failed (Exit 9009)"

The error happens even if I run bash as an administrator.

## 🔬 Minimal Reproduction

Clone Angular repository with Git 2.24 on Windows 10 1903. Check out master branch, run `yarn install` and then `node ./scripts/build-packages-dist.js`.

## 🔥 Exception or Error
<pre><code>
##################################
scripts\build-packages-dist.js:
  Building @angular/* npm packages
  Mode: Production
##################################
INFO: Writing tracer profile to 'C:/users/theod/_bazel_theod/bkm46ell/command.profile.gz'
Loading: 0 packages loaded
//packages/upgrade:npm_package
//packages/service-worker:npm_package
//packages/router:npm_package
//packages/platform-webworker-dynamic:npm_package
//packages/platform-webworker:npm_package
//packages/platform-server:npm_package
//packages/platform-browser-dynamic:npm_package
//packages/platform-browser:npm_package
//packages/localize:npm_package
//packages/language-service:npm_package
//packages/forms:npm_package
//packages/elements:npm_package
//packages/core:npm_package
//packages/compiler-cli:npm_package
//packages/compiler:npm_package
//packages/common:npm_package
//packages/bazel:npm_package
//packages/animations:npm_package
INFO: Writing tracer profile to 'C:/users/theod/_bazel_theod/bkm46ell/command.profile.gz'
INFO: Invocation ID: 37bf1298-0857-4f81-a74a-882858fe63ed
INFO: Analyzed 18 targets (1 packages loaded, 166 targets configured).
INFO: Found 18 targets...
ERROR: C:/users/theod/documents/github/angular/packages/bazel/docs/BUILD.bazel:3:1: Generating Skylark documentation dir for docs (2 files) failed (Exit 9009)
INFO: Elapsed time: 34.888s, Critical Path: 22.99s
INFO: 44 processes: 15 local, 29 worker.
FAILED: Build did NOT complete successfully
error Command failed with exit code 1.
child_process.js:660
    throw err;
    ^

Error: Command failed: yarn --cwd "C:\Users\theod\documents\GitHub\angular" --silent bazel build --config=release --define=compile=legacy //packages/upgrade:npm_package //packages/service-worker:npm_package //packages/router:npm_package //packages/platform-webworker-dynamic:npm_package //packages/platform-webworker:npm_package //packages/platform-server:npm_package //packages/platform-browser-dynamic:npm_package //packages/platform-browser:npm_package //packages/localize:npm_package //packages/language-service:npm_package //packages/forms:npm_package //packages/elements:npm_package //packages/core:npm_package //packages/compiler-cli:npm_package //packages/compiler:npm_package //packages/common:npm_package //packages/bazel:npm_package //packages/animations:npm_package
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at exec (C:\Users\theod\documents\GitHub\angular\scripts\package-builder.js:106:18)
    at buildTargetPackages (C:\Users\theod\documents\GitHub\angular\scripts\package-builder.js:68:3)
    at Object.<anonymous> (C:\Users\theod\documents\GitHub\angular\scripts\build-packages-dist.js:16:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 18808,
  stdout: null,
  stderr: null
}
</code></pre>

## 🌍  Your Environment

**Angular Version:** Master branch commit fc2f6b84562bb909532ebb29b728f83718e846dc
Windows 10 1903
Git v2.24.0

**Comment by RahulPrabhune** [comment]
@theodorejb, please install the latest version of Python(brew install python3) to fix this issue on your local. 

This is not a bug!

**Comment by theodorejb** [comment]
@RahulPrabhune I'm following the instructions in https://github.com/angular/angular/blob/master/docs/DEVELOPER.md, but Python isn't listed in the Prerequisite Software section. If Python is needed, shouldn't it be listed here? Also, the error message doesn't say anything about needing Python.

When I try to run `brew install python3` I get a different error saying "brew: command not found". Is brew another undocumented prerequisite I need to install?

**Comment by RahulPrabhune** [comment]
@theodorejb, you can install Python3 from [here](https://www.python.org/downloads/windows/) for Windows 

Also attached is the screenshot of the reproduced error with instructions to install Python3. 

<img width="981" alt="error_reproduced" src="https://user-images.githubusercontent.com/9441934/71328904-a1950080-24ec-11ea-8006-b1c01e03e41d.png">

**Comment by theodorejb** [comment]
@RahulPrabhune I installed Python 3.8.1 from that link, but I still get the same error:
![my error](https://user-images.githubusercontent.com/3053271/71369017-1a3ca100-256f-11ea-9eaf-96e8eff04838.png)

**Comment by RahulPrabhune** [comment]
@theodorejb, this looks like your local machine issue. Your windows machine is killing this process because it has low priority. 

Try (jobs value should be any value below 200)
 node ./scripts/build-packages-dist.js --jobs=2

**Comment by theodorejb** [comment]
@RahulPrabhune I tried with `--jobs=2` and `--jobs=6`, but either way I still get the same error (though with more jobs it seems to fail faster). Is there anything else I can try?

**Comment by RahulPrabhune** [comment]
@theodorejb, are you using VSCode Terminal to run this job? If not, give it a try. To sum up, you need better memory management on your machine. Unfortunately, i am not able to replicate this issue on my Macbook.

**Comment by theodorejb** [comment]
@RahulPrabhune I tried using the bash shell from the VSCode Terminal, but I get the same error as when running in the Git Bash terminal. If I use PowerShell or the Command Prompt shell I get a different error:

> ERROR: C:/users/theod/documents/github/angular/packages/language-service/bundles/BUILD.bazel:21:1: Executing genrule //packages/language-service/bundles:banner failed (Exit -1). Note: Remote connection/protocol failed with: execution failed
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("c:\tools\msys64\usr\bin\bash.exe" -c "source external/bazel_tools/tools/genrule/genrule-setup.sh; cp packages/language-service/bundles/banner.js bazel-out/x64_windows-fastbuild/bin/packages/language-service/bundles/banner.txt"): The system cannot find the file specified.        
 (error: 2)

I'm not sure what memory management would have to do with generating a Skylark documentation directory. I'm using an up-to-date Windows 10 PC with 16 GB or memory. It seems more likely there's a bug in the Angular build process that doesn't properly handle directory creation on Windows. Can anyone else try building Angular on Windows to see if they can replicate the issue?

**Comment by DmitryEfimenko** [comment]
Getting the same error on Windows

**Comment by icreatedanaccount** [comment]
Also getting the same error on Windows 10 PC with RAM : 16 GB.

**Comment by amitmca43** [comment]
I am also getting the same error on Windows PC running code in WSL Ubuntu 20.04

**Comment by amitmca43** [comment]
Found solution to it, install python3  if not installed: sudo apt install python3
Than create symlink : sudo ln -s /usr/bin/python3 /usr/bin/python

It fixed that issue for me.

**Comment by theodorejb** [comment]
Closing since this seems to have resolved itself now.
