### ISSUE TITLE
ng-content select does not work when content is in a *ng-for loop

### ISSUE THREAD

**Issue by typotter** [angular/angular#3397]
When providing an element selector to the ng-content tag, the contents are not transcluded.
Example:

__my-component template__

    <div>My Items</div>
    <ng-content select="my-item"></ng-content>

__caller template__

    <my-component>
      <my-item *ng-for="#item of items">{{item}}</my-item>
    <my-component>

In this example, the `my-item` components are not transcluded. If they are not in a for loop, then they are picked up. example:

    <my-component>
      <my-item>Item 1</my-item>
      <my-item>Item 2</my-item>
    <my-component>

**Comment by matanlurey** [comment]
I think this is WAI, @tbosch would know best.

**Comment by tbosch** [comment]
yes, this does not work right now. However, what does work is this:

```
<my-component>
  <template ng-for #item [of]="items" class="item"><my-item>{{item}}</my-item></template>
</my-component>

...
<ng-content select=".item">
```

I.e. we are checking the `template` element to be projected, as `<my-item *ng-for>` actually is just a shorthand for the above code. However, we probably want to support this case as well...

**Comment by kara** [comment]
@tbosch The syntax in your example is now `[ng-for-of]` rather than `[of]`, right? 

```javascript
<my-component>
  <template ng-for #item [ng-for-of]="items" class="item">
       <my-item>{{item}}</my-item>
   </template>
</my-component>
```

Here's a plunker of the working code for anyone else playing around with this:
http://plnkr.co/edit/Hn393B9fJN6zgfaz54tn

**Comment by tbosch** [comment]
@kara yes, this is correct.

**Comment by woppa684** [comment]
Any update on when this will be fixed?

**Comment by tbosch** [comment]
This should work as of https://github.com/angular/angular/commit/aa966f5de2efbaa9b1dc55836b0006315f010576

**Comment by uMaxmaxmaximus** [comment]
in my framework is works ^^ https://www.youtube.com/watch?v=tmKMAfzR8Ow
