### ISSUE TITLE
After installing memo-decorator lazy route

### ISSUE THREAD

**Issue by PriyankaShankar** [angular/angular#33980]
hi,
After installing memo-decorator i am seeing lazy route issue.

ERROR in Failed to list lazy routes: Unknown module 'C:/SourceCode/Projects/src/app/app.module#AppModule'.

what i observed is after installing memo-decorator,ngx -pagination issue came in app,module.Then again i installed ngx-pagination after this i am seeing issues above .
Does anyone faced this issue.

Thanks,
Priya
!--🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
