### ISSUE TITLE
ivy: ERROR in Unsupported mode: Visiting a localized string while targeting ES5

### ISSUE THREAD

**Issue by sergei-startsev** [angular/angular#33990]
# 🐞 bug report

### Affected Package
`@angular/compiler-cli@9.0.0-rc.3`

### Is this a regression?
Yes, the previous version in which this bug was not present was `9.0.0-rc.2`.

### Description

The Ivy compiler issues an error message after migration to `9.0.0-rc.3`. I guess it can be caused by b53a1ac. The issue isn't reproduced if `enableIvy` is `false`.

```js
//tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    ...
  }
}
```

## 🔥 Exception or Error
<pre><code>
ERROR in Unsupported mode: Visiting a localized string (which produces a tagged template literal) ' while targeting ES5.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.3
Node: 10.15.0
OS: win32 x64
Angular: 9.0.0-rc.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.3
@angular-devkit/build-angular      0.900.0-rc.3
@angular-devkit/build-ng-packagr   0.900.0-rc.3
@angular-devkit/build-optimizer    0.900.0-rc.3
@angular-devkit/build-webpack      0.900.0-rc.3
@angular-devkit/core               9.0.0-rc.3
@angular-devkit/schematics         9.0.0-rc.3
@angular/pwa                       0.803.4
@ngtools/webpack                   9.0.0-rc.3
@schematics/angular                8.3.19
@schematics/update                 0.900.0-rc.3
ng-packagr                         9.0.0-rc.1
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2
</code></pre>

**Comment by JoostK** [comment]
@sergei-startsev Hey, thank you for testing RC 3 and taking the time to report an issue. This particular error has been recently fixed (#33857) but it just missed the RC 3 release, unfortunately.

As such, I'll go ahead and close this. If you experience any other issues, please open a new issue.
