### ISSUE TITLE
Null response from API while using angular-cli v8 

### ISSUE THREAD

**Issue by ishaqueahmed-mev** [angular/angular#34006]
Hello,

I am using angular-cli v8.3 and trying to call one API from my client server, but all I receive is null response with 204 status. The problem is that the API is working fine when used with angular-cli v7, and also returns expected response with postman, or running directly in browser, only had issue while calling in angular 8.

my configurations are (where it doesn't works) ::
 
```
@angular/common": "~8.2.4",
@angular/compiler": "~8.2.4",
@angular/core": "~8.2.4",
@angular/cli: "~8.3.2" 
```

and configs where receiving proper response are
```
@angular/common: "^5.2.9",
@angular/compiler: "^5.2.9",
@angular/compiler-cli: "^5.2.9",
@angular/core: "^5.2.9",
@angular/cli: "7.2.3"
```
any help would be appreciated.

Thank you

**Comment by ajitsinghkaler** [comment]
It will be very helpful if you can reproduce this issue on some level on a plunker etc. otherwise this seems like an issue more fitting on StackOverflow

**Comment by dannyskoog** [comment]
Please post support questions like this on StackOverflow. Also take note that you are actually updating from version 5 to 8 (`HttpClient` resides within `@angular/common`). And moving 3 major versions in one go usually requires some adjustments to your codebase

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
