### ISSUE TITLE
:host styling doesn't work on root component

### ISSUE THREAD

**Issue by siggisim** [angular/angular#3402]
Angular applies an _nghost attribute to components and uses this for css shimming of the :host selector. See example:
```
<foo-component class="ng-binding" _ngcontent-khi-0="" _nghost-khi-1="">
</foo-component>
```

This does not seem to happen on the top level component in the angular application. See our root component with the selector 'root' does not contain the _nghost attribute:
```
<root></root>
```

I would expect components to behave the same regardless of whether they are the root component or a nested component.

**Comment by PascalPrecht** [comment]
Came across the same thing as stated here: http://blog.thoughtram.io/angular/2015/06/29/shadow-dom-strategies-in-angular2.html#shadow-dom-in-angular-2

However, I thought this would be okay, because Angular only cares about the stylings inside the root component (which is actually not true)..

**Comment by tbosch** [comment]
The reason for this is as follows:
Angular applies these classes during compilation, which might happen during a build step. However, Angular does not know the element on which it will bootstrap, so it can't apply the styles.

We are storing these styles in `DomProtoView.hostAttributes`, so `DomRenderer.createRootHostView` should read these out and apply them to the root element.

**Comment by mhevery** [comment]
@tbosch Sounds like this is working as intended. Can this be closed?

**Comment by tbosch** [comment]
This will be solved via https://github.com/angular/angular/issues/3605 as well.

**Comment by chrisgreeff** [comment]
+1

**Comment by kentongray** [comment]
running into this on angular 2 final.. definitely not intuitive

**Comment by stefan-niedermann** [comment]
Me too, i'm using Angular 2.0.0 via npm and styling with `:host` does not take any effect.

**Comment by zoechi** [comment]
@stefan-niedermann Please create a new issue with a Plunker to reproduce. Commenting on closed issues is usually pointless.
