### ISSUE TITLE
ngcc generates invalid syntax in umd module

### ISSUE THREAD

**Issue by jbedard** [angular/angular#34025]
# 🐞 bug report

### Description
For some reason this is happening with `@ngrx/store-devtools` (the `store-testing.umd.js` file), I haven't seen it anywhere else and the non-UMD files are fine.

The normal imports (not added by `ngcc`) for `@ngrx/store` get converted to `global.ngrx.store`, or `@angular/core` converted to `global.ng.core` etc., In this case `ngcc`  adds an additional import of `@angular/core` and `@ngrx/store`. The variable for the extra `@angular/core` is correctly `global.ng.core` like usual, but the variable for the extra `@ngrx/store` is `global.@ngrx/store` which is invalid syntax.

For example in the `store-testing.umd.js` file `ngcc` converts:
```
(function (global, factory) {
     typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('tslib'), require('@angular/core'), require('rxjs'), require('@ngrx/store'), require('@angular/core/testing')) :
     typeof define === 'function' && define.amd ? define('@ngrx/store/testing', ['exports', 'tslib', '@angular/core', 'rxjs', '@ngrx/store', '@angular/core/testing'], factory) :
     (global = global || self, factory((global.ngrx = global.ngrx || {}, global.ngrx.store = global.ngrx.store || {}, global.ngrx.store.testing = {}), global.tslib, global.ng.core, global.rxjs, global['@ngrx/store'], global.ng.core.testing));
 }(this, function (exports, tslib_1, core, rxjs, store, testing) { 'use strict'; 
```

into:

```
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('tslib'), require('@angular/core'), require('rxjs'), require('@ngrx/store'), require('@angular/core/testing'),require('@angular/core'),require('@ngrx/store')) :
    typeof define === 'function' && define.amd ? define('@ngrx/store/testing', ['exports', 'tslib', '@angular/core', 'rxjs', '@ngrx/store', '@angular/core/testing','@angular/core','@ngrx/store'], factory) :
    (global = global || self, factory((global.ngrx = global.ngrx || {}, global.ngrx.store = global.ngrx.store || {}, global.ngrx.store.testing = {}), global.tslib, global.ng.core, global.rxjs, global['@ngrx/store'], global.ng.core.testing,global.ng.core,global.@ngrx/store));
}(this, function (exports, tslib_1, core, rxjs, store, testing,ɵngcc0,ɵngcc1) { 'use strict';
```

Note the invalid `global.@ngrx/store` syntax at the end of the `factory(...)` args which `ngcc` added.

## 🔬 Minimal Reproduction
https://github.com/jbedard/angular-bazel-examples/tree/af68213db7fe2470f254aac6861bd8b6bd264a8c

Just running `yarn` and looking at `node_modules/@ngrx/store/bundles/store-testing.umd.js` shows the error.

If you want to see it at runtime run `bazel run //:devserver` for the devserver with UMD bundles to see the error. The `bazel run //:prodserver` runs rollup+terser on the es6 modules which works fine.

## 🔥 Exception or Error
<pre><code>Uncaught SyntaxError: Invalid or unexpected token</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>angular: 9.0.0-rc.3
ngrx: 8.5.2</code></pre>

**Comment by JoostK** [comment]
#34012 is here to fix it :-)

Btw, the published packages of NgRx [are themselves broken](https://unpkg.com/browse/@ngrx/store@8.5.2/bundles/store-testing.umd.js) (notice the `global['@ngrx/store']` in the UMD factory, although valid syntax it is not correct), for which there is a fix in https://github.com/ngrx/platform/pull/2275.

**Comment by jbedard** [comment]
Good to see! I guess I was only searching for existing issues and not PRs, but now there's a bug to close :)

> notice the global['@ngrx/store'] in the UMD factory

I did notice that as well, but need that syntax error fixed before looking into that one :)

**Comment by jbedard** [comment]
@JoostK is this one considered fixed then? I guess I can verify when the next RC is released...

**Comment by gkalpak** [comment]
Since the corresponding PR has been merged, I am going to close this.
@jbedard, you can grab the Angular packages for the latest 9.0.x build from CI (see [here][1] for details), if you can't wait to try it out: https://circleci.com/gh/angular/angular/546073#artifacts/containers/0

[1]: https://github.com/angular/angular/blob/8c33f9152/docs/DEVELOPER.md#getting-packages-from-build-artifacts

**Comment by jbedard** [comment]
I'll try it once the next RC is out.
