### ISSUE TITLE
http interceptor should complete after canceled request

### ISSUE THREAD

**Issue by Anderman** [angular/angular#34020]
### Affected Package

 The issue is caused by package @angular/....
httpmodule

### Description

Problem exist when the client use client use cors. When the first request (cors check) is done and the request is canceled (switchmap) then the http interceptor does not complete.

I needed this to hide the loading indicator
```
export class LoadingIndicatorInterceptor implements HttpInterceptor {
  constructor(private loaderService: LoadingIndicatorService) { }
  public intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    this.showLoader();
    console.log('start', req.url);
    return next.handle(req).pipe(
      tap(
        (event: HttpEvent<any>) => {
          console.log(event);
          if (event instanceof HttpResponse) {
            this.onEnd('request complete');
          }
        },
        () => this.onEnd('request error'),
        () => console.log('Observable complete')
      )
    );
  }
  private onEnd(type: string): void {
    console.log(type);
    this.hideLoader();
  }
  private showLoader(): void {
    this.loaderService.show();
  }
  private hideLoader(): void {
    this.loaderService.hide();
  }
}

```
Some component
```
    this.surveyId$.pipe(tap(_ => console.log('switchmap')), switchMap(x => !x ? of({ description: null, postMessage: null } as SurveyModel) : this.client.getSurveyModel(x))).subscribe(x => this.data = x);

```
chrome console log. The first is a normal request. The second request is canceled
![image](https://user-images.githubusercontent.com/1858745/69497255-2cc5ab00-0edb-11ea-82f8-9dcf2fd9abe1.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.19
Node: 10.16.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.19
@angular-devkit/build-angular      0.803.19
@angular-devkit/build-optimizer    0.803.19
@angular-devkit/build-webpack      0.803.19
@angular-devkit/core               8.3.19
@angular-devkit/schematics         8.3.19
@angular/cdk                       8.2.3
@angular/cli                       8.3.19
@angular/material                  8.2.3
@angular/material-moment-adapter   8.2.3
@angular/pwa                       0.803.19
@ngtools/webpack                   8.3.19
@schematics/angular                8.3.19
@schematics/update                 0.803.19
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Anything else relevant?**

**Comment by alxhub** [comment]
I'm afraid we won't be able to investigate this without a working reproduction (e.g. something on Stackblitz) which demonstrates the behavior.

I actually think if this is a bug, it has nothing to do with interceptors. If the second request is cancelled by the browser, it should have a response/status of some sort, or an error, but it shouldn't hang silently.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
