### ISSUE TITLE
Ivy preview strange behavior when binding SafeStyles

### ISSUE THREAD

**Issue by kolkov** [angular/angular#34023]
If I disable Ivy I have no errors in thumbnails, but if i back enable Ivy I see only one thumbnails element.
No styles for other elements...
![image](https://user-images.githubusercontent.com/3740898/69500536-251efa00-0f0d-11ea-9dfd-4196d8083f0e.png)

![image](https://user-images.githubusercontent.com/3740898/69500552-4253c880-0f0d-11ea-8b63-6df0f20534c1.png)

https://github.com/kolkov/ngx-gallery/blob/53785a725e709b10c0f716050e41d32cc3e73d68/projects/gallery/src/lib/ngx-gallery-thumbnails/ngx-gallery-thumbnails.component.html#L7

https://github.com/kolkov/ngx-gallery/blob/53785a725e709b10c0f716050e41d32cc3e73d68/projects/gallery/src/lib/ngx-gallery-thumbnails/ngx-gallery-thumbnails.component.ts#L159

![image](https://user-images.githubusercontent.com/3740898/69500562-5b5c7980-0f0d-11ea-8880-74acb355b60b.png)

**Comment by kolkov** [comment]
Still present in rc.4, but two items in thomgs, thst progress:
![image](https://user-images.githubusercontent.com/3740898/69799030-8d0e6280-11e3-11ea-99f4-83d98ebeb7e9.png)

https://github.com/kolkov/ngx-gallery/blob/b424fabd8d256f9c6aef0033cdfdf3f4f2c08295/projects/gallery/src/lib/ngx-gallery-thumbnails/ngx-gallery-thumbnails.component.html#L6

**Comment by kolkov** [comment]
@pkozlowski-opensource As I see only first elemets get SafeStyles. I hope that it willbe fixed in next rc.5. Thanks!

**Comment by Splaktar** [comment]
So it looks like there is an issue here when binding `SafeStyle` values to elements within an `*ngFor`.

**Comment by AndrewKushnir** [comment]
Hi @kolkov, thanks for reporting the issue and providing information on how to reproduce it.

I've created a [PR with proposed fix](https://github.com/angular/angular/pull/34286). PR still requires review and the final implementation might change, but I'd like to ask if you could test your app with the changes from that PR to make sure the fix covers the case that you have in the app and everything works as expected. You can follow an instruction in [this document on how to use PR artifacts](https://github.com/angular/angular/blob/master/docs/DEVELOPER.md#archives-for-each-package). An archive with updated `@angular/core` package is available [here](https://557900-24195339-gh.circle-artifacts.com/0/angular/core-pr34286-e65797b434.tgz) (please make sure you update other `@angular` packages to `9.0.0-rc.5` to avoid version conflicts).

Thank you.

**Comment by kolkov** [comment]
@AndrewKushnir Thanks! Fixed in rc.6

**Comment by AndrewKushnir** [comment]
@kolkov, thanks for checking. We are glad to know that everything works as expected now. Thank you.

**Comment by kolkov** [comment]
https://github.com/kolkov/ngx-gallery/tree/9.0.0 for cheking.
