### ISSUE TITLE
(input) binding not working in Microsoft Edge

### ISSUE THREAD

**Issue by BevRivling** [angular/angular#34035]
# 🐞 bug report

### Affected Package
My assumption is that this is caused by `"@angular/core": "~8.2.0".  This also does not work in previous versions.

### Is this a regression?
I'm not sure, but this works in neither Angular 6 or 8.

### Description
I cannot trigger a function through input bindings with a checkbox on Edge.  The bound expression does not execute.  This works on all other browsers tested.

## 🔬 Minimal Reproduction
code: https://stackblitz.com/edit/angular-issue-repro2-8nay57
app: https://angular-issue-repro2-8nay57.stackblitz.io

## 🔥 Exception or Error
No error message available.

## 🌍  Your Environment

**Angular Version:**
```
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.2
@angular-devkit/build-angular     0.802.2
@angular-devkit/build-optimizer   0.802.2
@angular-devkit/build-webpack     0.802.2
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.2.2
@angular/cli                      8.2.2
@ngtools/webpack                  8.2.2
@schematics/angular               8.2.2
@schematics/update                0.802.2
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.38.0
```

**Anything else relevant?**
Only a browser issue.  Edge version: 18.18362

**Comment by pkozlowski-opensource** [comment]
It looks like the `input` event might not be fully working on Edge with check-boxes: https://caniuse.com/#feat=input-event 

Using `(change)` might be an option here...

**Comment by BevRivling** [comment]
Ah, that seems to be the issue.  I've updated to a `change` and it all seems to work now.   Appreciate your help!

**Comment by gkalpak** [comment]
Keep in mind that `change` may be fired at different times on different browsers (because the spec is a bit vague on when it should happen). At least that used to be the case in the past. (IIRC, that was particularly obvious with `<select>`.)

You could also use the `click` event for checkboxes.
