### ISSUE TITLE
Router: Provide method to compare urls

### ISSUE THREAD

**Issue by mochicode** [angular/angular#34030]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/router

### Description

I would like to find a component inside the router config based on a given URL (not the active one).

### Describe the solution you'd like
 expose a function such as `match(routePath: string, url: UrlTree | string): boolean`

### Describe alternatives you've considered
 importing containsTree directly from `@angular/router/esm5/src/url_tree`

**Comment by Airblader** [comment]
What about lazy loaded modules?
