### ISSUE TITLE
Golang Server Code Snippet Does Not Work in Angular 8 for Chrome, Firefox

### ISSUE THREAD

**Issue by Gregory-Ledray** [angular/angular#34036]
# 📚 Docs or angular.io bug report

### Description
Previously, you could host an Angular application on a Golang server using Angular's suggested server code.

As of Angular 8, the code snippet no longer works because Go is not setting the MIME type with the suggested code snippet. This was not a problem before Angular 8 because the MIME type was set by Angular. See issue #30835 

There is some discussion about MIME types in golang here: https://github.com/golang/go/issues/32351

### What's the affected URL?**
https://angular.io/guide/deployment#server-configuration
Scroll down to this: "Golang: create a Golang server using (gorilla/mux) with a basic Golang file that configures the server main.go"

### Reproduction Steps**
Install Golang and Angular with a hello world app for Angular. Copy and paste the suggested code snipped for golang. Build (go build). Start the application (it should have generated an executable). Navigate to localhost:80 and notice that in Chrome, nothing loads. Open Developer Tools and observe the folly of man.

### Expected vs Actual Behavior**
I expect a documented method for serving Angular to work. You have several options to fix this. You could remove this documented method, include code to adjust the generated ./dist files such that Go can serve them (did not work for me - see "Attempts to Find a Solution"), find a way to adjust the go server such that it sends the proper MIME type for you (I do not see how this is possible - again see below), or you could fix #30835

## 🔥 Exception or Error
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

runtime-es2015.0d2af1576c48cfaa282f.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

main-es2015.96a0727a2084e300eb8a.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

### Browser info
Chrome: 78.0.3904.108 (Official Build) (64-bit) (cohort: Stable)

### Anything else relevant?
While you're there, please update the code snippet so it reads, 
"dist/[Your-Project-Name]" instead of "./dist" because the latter absolutely does not work.

### Updating MIME types after build with a script
Does not work because I'm using a service worker in my actual application. Resulting error: 
main.3ae3d6ffc19608a068bd.js:1 Service worker registration failed with: DOMException: Failed to register a ServiceWorker for scope ('http://localhost:4200/') with script ('http://localhost:4200/ngsw-worker.js'): The script has an unsupported MIME type ('text/plain').

### Adjusting MIME in Golang server
This does not seem to be possible based on this pull, where we can see Golang's HTTP package is specifying which MIME type to use for us.
https://go-review.googlesource.com/c/go/+/186927/

### Testing with a Different Server
I have tested my code using "http-server" and it works fine. This seems to point the blame away from my code and towards Angular 8, the Go server code I'm asking to be fixed in the Angular docs, or towards Go itself.

**Comment by kapunahelewong** [comment]
Thanks for bringing this up, @Gregory-Ledray. After discussing and testing this in docs management, we decided that since this has issues we should remove it from the documentation (it was a recent addition that we wanted to be vigilant about anyway, though it worked on our end at the time). We're sorry for any inconvenience this code sample caused you.

**Comment by Gregory-Ledray** [comment]
That's fine. I rely heavily on the docs and just want to make sure they are accurate.

**Comment by josephperrott** [comment]
Closing as this was already removed, but the issue was closed for it.
