### ISSUE TITLE
Double navigation and no url change when Guard navigates back to the same URL (using hash url)

### ISSUE THREAD

**Issue by StefanKern** [angular/angular#34049]
# 🐞 bug report
Setup:
Using routes with `RouterModule.forRoot(APP_ROUTES, {useHash: true, enableTracing: false}),` (so hashes).

having a guard, whcih protects access to certain roots. If not permitted, it displays a error message and navigates to the startpage:
Code:
```
....
@Injectable({
  providedIn: 'root'
})
export class AdminRightGuard implements CanActivate {
  constructor(protected rightService: RightService) {
  }

  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot, snackBarService: SnackBarService): boolean | UrlTree {
    if (this.rightSerivce.hasRight('admin'))) {
      return true;
    } else {
      this.snackBarService.pop('Not permitted');
      return this.router.parseUrl('/start');
    }
  }
}

```
it works fine, expect if we are already on the `/start` route. In this case, it tirggers the route twice (--> two popups) and doesn't change the browser url.

### Workaround
If I check, if we already on the correct url in the guard and if yes, retun false, the behaviour is as expected.

Code:
```
  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): boolean | UrlTree {
    if (this.rightSerivce.hasRight('admin'))) {
      return true;
    } else {
      this.snackBarService.pop('Not permitted');
      if (this.router.url !== '/start') {
        return this.router.parseUrl('/start');
      } else {
        return false;
      }
    }
  }
```

### Enviroment
Tested with angular 8, but could reproduce it in lower versions as well.

**Comment by atscott** [comment]
Hi @StefanKern, can you please provide a reproduction. I tried doing it here: https://stackblitz.com/edit/angular-ivy-router-base-nfkajk?file=src%2Fapp%2Fapp.component.html but was not seeing the issue you described.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
