### ISSUE TITLE
Angular Testability API should not require root node

### ISSUE THREAD

**Issue by goderbauer** [angular/angular#3404]
Right now, in order to get access to the angular testability api you need to know the root node of your app, example:

var el = document.querySelector('rootSelector');
window.getAngularTestability(el).whenStable(...);

However, there is no way to identify root nodes on the page as they are not marked. This makes it complicated to write non-flaky webdriver tests with the whenStable API because the test author essentially has to provide the root node selectors of all angular apps he/she wants to wait for. To fix this, there should either be a way to query a page for all root nodes or the testability API should just not require a root node at all.

**Comment by DrMarcII** [comment]
Cited in internal issue: http://b/21869186

**Comment by hankduan** [comment]
see https://github.com/angular/angular/pull/3413
