### ISSUE TITLE
 Format of Nepalese Currency must be रू 12,41,54,54,545.23 rather then नेरू 12,415,454,545.23

### ISSUE THREAD

**Issue by santosTT** [angular/angular#34050]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
The currency Format is wrong  and prefer short symbol at first 
View the currency format
https://en.wikipedia.org/wiki/Numbers_in_Nepali_language

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-g1y94e

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by KevinCathcart** [comment]
This is an upstream data issue. There is an existing upstream bug report: https://unicode-org.atlassian.net/browse/CLDR-11998

Unfortunately it seems to have gotten stuck in NEW status. Upstream lacks the lakh style number formatting. It also has an apparently completely invented currency symbol set as the default symbol. It has the correct symbol रू set as the narrow form symbol. The correct symbol is the first syllable of the word rupee in Devanagari script. It is actually completely unique as a currency symbol. The invented wide form symbol appears to be some form of attempt to disambiguate this symbol, by attaching the first syllable of the word Nepal.

If somebody with contacts with the CLDR team could reach out and get the upstream issue unstuck, that would certainly help fix this issue.

**Comment by petebacondarwin** [comment]
Closing as this is out of scope for this repo. Please chase the CLDR issue above instead.
