### ISSUE TITLE
HttpHeaders lazyInit throws error with non-string value

### ISSUE THREAD

**Issue by cooneyasendia** [angular/angular#34059]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common/http

### Is this a regression?

No

### Description

Initializing HttpHeaders with an object of key/value pairs where a value is set to null causes an error.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-issue-repro2-vmkwd7

This code in particular

<pre>
<code>
return this.httpClient.get('URL GOES HERE', {
  headers: new HttpHeaders({
    'X-Key-1': '1',
    'X-Key-2': null,
  }),
});
</code>
</pre>

## 🔥 Exception or Error
<pre>
<code>
ERROR TypeError: "values is null"
    common common-http.umd.js:175
    common common-http.umd.js:169
    common common-http.umd.js:233
    common common-http.umd.js:302
    common common-http.umd.js:1496
    rxjs Observable.js:44
    rxjs Observable.js:30
    rxjs subscribeTo.js:22
    rxjs subscribeToResult.js:10
    rxjs mergeMap.js:82
    rxjs mergeMap.js:76
    rxjs mergeMap.js:59
    rxjs Subscriber.js:67
    rxjs scalar.js:6
    rxjs Observable.js:44
    rxjs Observable.js:30
    rxjs mergeMap.js:39
    rxjs Observable.js:25
    rxjs filter.js:29
    rxjs Observable.js:25
    rxjs map.js:32
    rxjs Observable.js:25
    ngOnInit app.component.ts:20
    core core.umd.js:9274
    core core.umd.js:10538
    core core.umd.js:10500
    core core.umd.js:11133
    core core.umd.js:11093
    View_AppComponent_Host_0 (index):1
    core core.umd.js:11085
    core core.umd.js:10482
    core core.umd.js:11375
    core core.umd.js:11053
    core core.umd.js:8869
    core core.umd.js:4641
    core core.umd.js:4641
    core core.umd.js:4675
    core core.umd.js:4617
    core core.umd.js:4420
    core core.umd.js:4420
    core core.umd.js:4386
    js zone.js:388
    core core.umd.js:3890
    js zone.js:387
    js zone.js:138
    js zone.js:872
    js zone.js:421
    core core.umd.js:3881
    js zone.js:420
    js zone.js:188
    js zone.js:595
preview-0578bbed66dd68addeaab.js:1:90093
</code>
</pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Your global Angular CLI version (8.3.14) is greater than your local
version (7.3.8). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.3.8
Node: 10.16.3
OS: win32 x64
Angular: 7.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cdk                      7.3.3
@angular/cli                      7.3.8
@angular/flex-layout              7.0.0-beta.23
@angular/material                 7.3.3
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.4.0
typescript                        3.2.2
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

Although I am using an older version of Angular (current work version), this problem is still relevent in the current version of Angular.

**Comment by alxhub** [comment]
This usage is already prohibited by the `HttpHeaders` constructor signature, assuming you have `strictNullChecks` enabled in TypeScript.

This is the error that I get:
```
Argument of type '{ 'X-Key-1': string; 'X-Key-2': null; }' is not assignable to parameter of type 'string | { [name: string]: string | string[]; } | undefined'.
  Type '{ 'X-Key-1': string; 'X-Key-2': null; }' is not assignable to type '{ [name: string]: string | string[]; }'.
    Property ''X-Key-2'' is incompatible with index signature.
      Type 'null' is not assignable to type 'string | string[]'.
```

Based on this, I think `HttpHeaders` is working as intended. You cannot pass a type other than the one that they declare and expect not to get an error at runtime.
