### ISSUE TITLE
click event triggers before ng-model changes the value.

### ISSUE THREAD

**Issue by imsingh** [angular/angular#3406]
I am doing something like this.

`<input [(ng-model)]="item.completed" (click)="completed(i)" type="checkbox">`

What i want is the when checkbox is clicked it changes the value of *item.completed*  and then it fires the click event.

But what happening is. click events get fired and then ng-model changes the value of item.completed.

**Comment by zzm2q** [comment]
yes, i also met this case: 

(with select tag)
```
<select [(ng-model)]="scale" (change)="tryPrintScaleValue()">...</select>
```
`tryPrintScale` will be called **before** scale changed.

<br/>
(with input tag)
`tryPrintScale` will be called **after** scale changed.
```
<input [(ng-model)]="scale" (change)="tryPrintScaleValue()">
```

**Comment by gdi2290** [comment]
have you guys tried to swap the position of the `[(ng-model)]` and `(change)`?
`<input (change)="tryPrintScaleValue()" [(ng-model)]="scale">`

**Comment by zzm2q** [comment]
yes, i have tried it just now. nothing change.

**Comment by gdi2290** [comment]
alright, I was just wondering. The bindings are meant to be more predictable this time around so I was wondering if position mattered.

what about breaking apart the two-way binding (this probably won't change anything either)
`<input (change)="tryPrintScaleValue()"  [ng-model]="scale = $event" (ng-model)="scale">`

**Comment by S-YOU** [comment]
some browsers change attributes order when you access attributes (not sure about latest browsers), so position shouldn't matter.
this does not happen in angular 1.x because ng-model has higher priority than normal events. 
priority concept is gone in angular 2 btw?

**Comment by mhevery** [comment]
This should be handled by processing events on `@Component.host` before processing events on elements `(event)`.

**Comment by imsingh** [comment]
@mhevery Can you explain or give a link to explanation? Need more info, new comer to angular2.  Thanks.

**Comment by BlackHawkDesign** [comment]
What is the status of this issue? I'm facing the same problem. Is it gonna be fixed before v20?

**Comment by tonywong625** [comment]
also having the same issue, can someone point me to the right direction ?

**Comment by Drol** [comment]
I have problems with this too. One workaround is to use [(ngModel)] on select instead of (change) and declade get/set methods in the component for your value and do your work the set method.

Html:
`<select id="county" class="sc-select" [(ngModel)]="selectedMunicipalityMod">
  <option *ngFor="let municipality of municipalities" [ngValue]="municipality">
    {{municipality.name}}
  </option>
</select>`

TS:
`get selectedMunicipalityMod() {
        return this.selectedMunicipality;
 }
 set selectedMunicipalityMod(value: Municipality) {
        this.selectedMunicipality = value
        this.search();
}`

**Comment by Drol** [comment]
Another workaround that seems to work fine is to wrap everything in your OnChange method in a setTimeout(() => { *dostuff* });

**Comment by awerlang** [comment]
`click` is a DOM event, not related to the higher level `ngModel`. The proper event for this is `ngModelChange`. If you want to use DOM events, then forget about ngModel and use `$event` inside the handler or a `#ref`.

So, instead of 

```
<input [(ngModel)]="item.completed" (click)="completed(i)" type="checkbox">
```

it should be 

```
<input [(ngModel)]="item.completed" (ngModelChange)="completed(i)" type="checkbox">
```

**Comment by Drol** [comment]
@awerlang Yeah well I guess it deserves down vote. But I was very specific it was a work around.

Thanks for mentioning (ngModelChange). Sometimes it can be hard to know when to use (change) or (ngModelChange).

**Comment by LanceEa** [comment]
I was experiencing this as well and here is a stack-overflow explaining it. I found that the order of `ngModel` and `ngModelChange` matter as of RC.4.

http://stackoverflow.com/questions/38512006/angular-2-rc4-select-ngmodel-delayed-update/38521630#38521630

Based on this thread it sounds like it shouldn't matter and that it is a bug. But, if it is the way it should work then I think there is an opportunity to provide some documentation around how this works. I definitely can provide some help in documenting if need be.
@wardbell @Foxandxss  @naomiblack

**Comment by jessedhillon** [comment]
There's some cases where `ngModelChange` is still insufficient. Consider this directive:

```typescript
@Component({
  selector: 'textarea[autosize]',
  template: '',
})
class TextAreaAutosize {
  @HostListener('input', ['$event.target']) onInput(textArea: HTMLTextAreaElement): void {
    this.adjust();
  }

  constructor(public element: ElementRef){}

  ngOnInit(): void {
    this.adjust();
  }

  adjust(): void {
    this.element.nativeElement.style.overflow = 'hidden';
    this.element.nativeElement.style.height = 'auto';
    this.element.nativeElement.style.height = this.element.nativeElement.scrollHeight + "px";
  }
}
```

and this template:

```html
  <textarea autosize [(ngModel)]="myText"></textarea>
```

How can you resize the element when the directive is initialized? The `ngModelChange` event is fired *after* the value is changed but *before* the element's value is updated. AFAICT there's no way short of `setTimeout` to coincidentally happen after the `textarea` value is updated.

**Comment by ashblue** [comment]
Any word on getting this fixed. Our QA team has been freaking out over this issue the past few days on RC4.

**Comment by zoechi** [comment]
@ashblue Can't you just use instead
```ts
<input [(ngModel)]="item.completed" (ngModelChange)="completed(i)" type="checkbox">
```

**Comment by kara** [comment]
As a few people have mentioned, using the `ngModelChange` event is the best practice if you want to ensure the value has been updated. 

@jessedhillon I'm curious about your specific case, but we'll need some further info to look into it. If you're still having issues, please open a new issue with a minimal plunker so we can take a look.

**Comment by Mani2693** [comment]
Facing same issue with
 <ui-switch (ngModelChange)="toggleEnable($event)" [(ngModel)]="enableState" size="small">
</ui-switch> 

on click() will toggle the state of the switch, with "toggleEnable($event)" I am checking some condition and setting "enableState" but this changes are not replicated in the UI , Only the click() event is applied over the switch 

Need some work around asap 

Thanks in advance!

**Comment by githubakash007** [comment]
I faced the same issue today while using radio button list and used the "awerlang" solusion of using (ngModelChange)  instead of (click) event , and it worked like magic.

**Comment by marshallalsup** [comment]
Same issue here with a textarea. But I can't really use ngModelChange() because it steals some of the characters the user is typing when it handles the change (after every character typed). I was trying to use (focusout) before and that is how I ran into this problem.

**Comment by zoechi** [comment]
@marshallalsup sounds like you're doing something wrong

**Comment by marshallalsup** [comment]
@zoechi I think you're probably right since I'm still learning. However, I'll leave the comment there in case the idea of using change instead of ngModelChange helps someone else in the same situation.

**Comment by parth23** [comment]
@Drol I used getter and setter property but getter function called infinite time and my page was crashed
I don't understand why getter functions behave like this.

**Comment by zoechi** [comment]
@parth23 uf you bind to a getter or function, it gets called every time change detection runs, Try to avoid that

**Comment by parth23** [comment]
Here is my html and ts code:
 ` <p-calendar [value]="asd" [(ngModel)]="selectedMunicipalityMod" readonlyInput="true" placeholder="--" [utc]="true" [showIcon]="true" dateFormat="{{INPUT_DATE_FORMAT}}" [monthNavigator]="true"
                                                                    [yearNavigator]="true" yearRange="2000:2030" class="cal-slam"></p-calendar>`

`get selectedMunicipalityMod() 
{ 
        console.log("selectedMunicipalityModGet");
        var cdate =  Global.transformDate(this.foFormSections[this.currentSectionIndex].FOFormFieldList[this.currentFieldIndex].FOFormFieldResponseText.toString());
        return cdate; 
    } 
    

set selectedMunicipalityMod(value: any) 
    { 
        var cdate =  Global.transformDate(value.toString());
        this.foFormSections[this.currentSectionIndex].FOFormFieldList[this.currentFieldIndex].FOFormFieldResponseText = cdate; 
    }`

I just assigned the value once but get function called too many times...

**Comment by cray2015** [comment]
After spending hours on this issue(as I didn't know what to search for), I reached here and to my surprise I didn't knew the preference chain with angular, ngModelChange fixed my issue thanks!!!

**Comment by cray2015** [comment]
@parth23 you are using a method to set the model value so it keeps running the methods so as to check if the value has changed. I would not recommend to do it in that manner.

**Comment by apurva04** [comment]
what I did to make it work 
 <input type="text" [(ngModel)]="rowData[col.field]"(paste)="onPaste($event,i,rowData)" (ngModelChange)="onModelChange($event)">

(ngModelChange) function is called when model is changed inside that 
setTimeout(() => {
    --do your stuff here update the model value 
    });

**Comment by Achutharaman** [comment]
Any solution for this Issue other than the TimeOut function?

**Comment by cray2015** [comment]
> Any solution for this Issue other than the TimeOut function?

@Achutharaman what do you want to achieve?

**Comment by ipsjolly** [comment]
> `click` is a DOM event, not related to the higher level `ngModel`. The proper event for this is `ngModelChange`. If you want to use DOM events, then forget about ngModel and use `$event` inside the handler or a `#ref`.
> 
> So, instead of
> 
> ```
> <input [(ngModel)]="item.completed" (click)="completed(i)" type="checkbox">
> ```
> it should be
> 
> ```
> <input [(ngModel)]="item.completed" (ngModelChange)="completed(i)" type="checkbox">
> ```

What to do if we have a div with (click) calling a method, in that method ngModel is not correct.

**Comment by alinmateut** [comment]
`ngModelChange` is now deprecated...

**Comment by gongAll** [comment]
For whoever may concern, I solved this by using 

```
    @HostListener('click', ['$event'])
    public onMouseEvent(event: MouseEvent): void {
        if (event.ctrlKey) {
            // do something here after ngModelChange was triggered
        }
    }
```

**Comment by ronny98** [comment]
> html file
> <input  [(ngmodel)]="item" (ngModelChange)="completed($event)" type="checkbox">`
>  Try it may it works for you....
> set
export class{.......
	public item: boolean = false;

       completed(event: any){
		
		this.item = this.item;
// if want to try on select ,un selected api call for backend data
                if(item) {
                 this.getUnselectedUsers();  //method for Api avoid //false so UNselected
                      }

                 else { this.getSelectedUser(): } //true so selected user

> set default true and false value for an item in .ts file, when completed() call set that change value of an item in the default value.
