### ISSUE TITLE
Constants in templates

### ISSUE THREAD

**Issue by daniel-dimitrovv** [angular/angular#34078]
Please consider the following code:
HTML:    
```
<app-table-editable
      [data]="data"
      [customFormArrayName]="CUSTOM_CONTROLS.VARIANTS"
      [displayedColumns]="displayedColumns">
</app-table-editable>
```

TS:
```
....
import { CUSTOM_CONTROLS } from '../../../shared/constants/custom-controls/custom-controls.constants';
@Component({
  selector: 'app-combination',
  templateUrl: './combination.component.html',
  styleUrls: ['./combination.component.sass']
})
export class CombinationComponent implements OnInit, OnDestroy {
  CUSTOM_CONTROLS = CUSTOM_CONTROLS;
 ...
}
```

First topic: How can I use the constant(`CUSTOM_CONTROLS`) on the template without setting it to a property in the .ts file?

Second topic: If set like that `[customFormArrayName]="CUSTOM_CONTROLS.VARIANTS"` change detection(CD) will always check if the value of `[customFormArrayName]` has been changed. Of course in this situation, it won't be changed, so we are putting some unnecessary load onto the client. It will be cool if we have a way of setting a value in the template only one time, so CD won't be analyzing properties that will never be changed after the first time it has been set.

**Comment by cedvdb** [comment]
You can make a pipe for that

**Comment by mlc-mlapis** [comment]
@daniel-dimitrovv You have to create a public property for such constants first.

**Comment by daniel-dimitrovv** [comment]
> You can make a pipe for that

Hi, @cedvdb:). Can you give me an example of how can I do that? From my knowledge you should still add the pipe in the property biding- example: `[property]="value | pipe"`

**Comment by pauldraper** [comment]
`[property]="('VARIANTS' | customControls)"`

or

`[property]="(null | customControls).VARIANTS"`

Though you may just reconsider your opposition to just "setting it to a property in the .ts file".

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
