### ISSUE TITLE
angular.d.ts does not show suggestion 

### ISSUE THREAD

**Issue by itsmeprasanjit** [angular/angular#3407]
The angular.d.ts is not showing suggestions for components while importing in 'angular2/angular' using visual studio code

**Comment by jeffbcross** [comment]
Do you mean angular2/angular2? And can you specify which version of angular2.d.ts you're referring to?

**Comment by jeffbcross** [comment]
Closing this for now. If you can provide more detail, please add a comment and mention me so I can reopen the issue.

**Comment by itsmeprasanjit** [comment]
Steps:1)tsd init (with tsd -v 0.6.3)
2)tsd install angular2 --save 
3)code-->
------------------------------------------***************----------------------------
/// <reference path="typings/angular2/angular2.d.ts" />

import {Component, View, bootstrap} from 'angular2/angular2';

@Component({
  selector: 'my-app'
})
@View({
  template: '<h1>Hello {{ name }}</h1>'
})
// Component controller
class MyAppComponent {
  name: string;
  constructor() {
    this.name = 'Alice';
  
}

bootstrap(MyAppComponent);
--------------------*************************---------------------

on writing import { } from 'angular2/angular2'
on pressing ctrl + enter inside the bracket it shows no suggestion earlier it was working but the selector and template etc were not working inside the decorators
