### ISSUE TITLE
fix(docs-infra): entry-points are incorrectly labelled as packages

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#34081]
On API docs pages for Angular packages (e.g. https://angular.io/api/common), we show all primary and secondary entry-points. Following a link to one of the secondary entry-points (e.g. https://angular.io/api/common/http), navigates the docs page for the secondary entry-point, where it is incorrectly (and misleadingly) labelled as `PACKAGE` and not as an entry-point.

(NOTE: This currently only affects secondary entry-points, because the primary entry-point has the same name as the npm package, so they are on the same API docs page.)

##
We should implement a new `ENTRY-POINT` label and add support for correctly differentiating between entry-points and packages.

To avoid regressions, we should also check against invalid package names, like `@angular/common/http`.

##
Original discussion: https://github.com/angular/angular/pull/33801#issuecomment-558903958

**Comment by sonukapoor** [comment]
@gkalpak I can probably take a look at this, once I am done with #28017

**Comment by ajitsinghkaler** [comment]
@gkalpak can you explain is this also generated by dgeni because when I looked into it there was no doctype package in api-list.json can you please explain this.

**Comment by petebacondarwin** [comment]
There are two possible approaches

## New docType
One is to create a new docType say, `secondary-entry-point` and then change all the `package` docs that are actually secondary entry-points to have this. Then we would need to check through the dgeni config for places where `packages` are mentioned and then accommodate this new type. A quick search of the code base brings back this list of places to consider:

```
aio/tools/transforms/angular-api-package/index.js
  52,89:           return EXPORT_DOC_TYPES.concat(['decorator', 'directive', 'ngmodule', 'pipe', 'package']);
  197,24:             docTypes: ['package'],

aio/tools/transforms/angular-api-package/processors/computeApiBreadCrumbs.js
  29,26:   return doc.docType === 'package' && !doc.isPrimaryPackage;

aio/tools/transforms/angular-api-package/processors/computeSearchTitle.js
  11,14:         case 'package':

aio/tools/transforms/angular-api-package/processors/generateApiListDoc.js
  15,42:           .filter(doc => doc.docType === 'package')

aio/tools/transforms/angular-api-package/processors/processPackages.js
  14,25:           doc.docType = 'package';

aio/tools/transforms/angular.io-package/processors/createOverviewDump.js
  17,29:         if (doc.docType === 'package') {
```

Plus a new template would be needed for this new docType that will display the entry-point correctly.

## Discriminate within the package docType

The package/entry-point docs have a property: `doc.isPrimaryPackage`, which could be used to discriminate between packages and secondary entry-points.

The fix would involve changing this line: https://github.com/angular/angular/blob/c0869ecfb31dc589b86aa6f10184508bac951f17/aio/tools/transforms/templates/api/package.template.html#L26

to something like

```
  {% if doc.isPrimaryPackage %}<label class="api-type-label package">package</label>{% else %}<label class="api-type-label {$ entry-point $}">{$ entry-point $}</label>{% endif %}
```

And then tweaking the AIO styles to display the label correctly.
