### ISSUE TITLE
DI: Stack trace is lost when a binding is failed to be created

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#3408]
Instead of seeing a stack trace/error of why the factory/constructor of a binding failed, I only see `Caught Error during instantiation of...` with a stack trace of `di/injector.dart` being called.

**Comment by pkozlowski-opensource** [comment]
Yeh, was bumping into it why working on Dart unit tests as well. Here is a simple test to reproduce (you can add it to injector_spec.ts):

```js
it('confusing err', () => {
        var injector = createInjector([bind(Engine).toClass(BrokenEngine)]);
        injector.get(Engine);
});
```

This test will fail with:

> Chrome 39.0.2171 (Linux) injector dynamic confusing err FAILED
	Test failed: Caught Error during instantiation of Engine!.
	#0      Injector._new (package:angular2/src/di/injector.dart:704:7)
	#1      InjectorDynamicStrategy.getObjByKeyId (package:angular2/src/di/injector.dart:313:40)
	#2      Injector._getByKeyDefault (package:angular2/src/di/injector.dart:783:31)
	#3      Injector._getByKey (package:angular2/src/di/injector.dart:731:19)
	#4      Injector.get (package:angular2/src/di/injector.dart:467:17)
        ....

Notice that there is not enough context (no trace of the original exception).

@vsavkin would love to fix this one if you've got any pointers.

**Comment by pkozlowski-opensource** [comment]
So, we've got the same pb under JS and the crux here is that it seems like by default Jasmine is not calling `.toString()` on the exception obj when reporting exceptions with a message. Instead the [following logic](https://github.com/jasmine/jasmine/blob/master/src/core/ExceptionFormatter.js) is used. 

Maybe we should make sure that the `AbstractBindingError` has the original error message as a part of the message itself? Thinking about this some more - it really is a pb of any exception, not only in DI....

**Comment by naomiblack** [comment]
@vsavkin is this closed by https://github.com/angular/angular/commit/f6cc57368768e0c2f47c6646620c4cff73e5d5a7?
