### ISSUE TITLE
ChangeDetectionStrat OnPush with save-navigator in view

### ISSUE THREAD

**Issue by workingerror** [angular/angular#34083]
# 🐞 bug report

### Affected Package
Testet with

- "@angular/common": "^8.0.0",
- "@angular/compiler": "^8.0.0",
- "@angular/core": "^8.0.0",

and with 

- "@angular/common": "^8.2.12",
- "@angular/compiler": "^8.2.12",
- "@angular/core": "^8.2.12",

### Is this a regression?

_unknown_

### Description

Change Detection will not fire with save-navigator (`a?.b`) or even with a safe check (`a && a.b`) in view. See stackblitz-Link below.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-sdtfeg

## 🔥 Exception or Error

_no visible errors messages_

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.14
Node: 10.16.0
OS: win32 x64
Angular: 8.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.14
@angular-devkit/build-angular      0.803.14
@angular-devkit/build-optimizer    0.803.14
@angular-devkit/build-webpack      0.803.14
@angular-devkit/core               8.3.14
@angular-devkit/schematics         8.3.14
@angular/cdk                       8.2.3
@angular/cli                       8.3.14
@angular/material                  8.2.3
@angular/material-moment-adapter   8.2.3
@ngtools/webpack                   8.3.14
@schematics/angular                8.3.14
@schematics/update                 0.803.14
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Anything else relevant?**

Because I could not find any information about this behaviour it seems to be a bug. If it's not feel free to send me some link to the docs where this is explained.

Have a nice day :)

**Comment by pkozlowski-opensource** [comment]
I _think_ I understand what is the confusion here! So, the thing is that `OnPush` matters _only_ after the first change detection. In other words, component's template is change-detected at least once in your particular case - and this is where the `obj` is undefined: https://stackblitz.com/edit/angular-yurit6?file=src/app/test-regular.component.ts.

Another possible confusion point might be with `obj: {};` - maybe you wanted to write `obj: {a: string} = {a: undefined};` ?

In any case all looks good here - works as designed.
