### ISSUE TITLE
Google Tag Manager conflict with zone.js

### ISSUE THREAD

**Issue by pshurygin** [angular/angular#34105]
# 🐞 bug report

### Affected Package
The issue is caused by package zone.js

### Is this a regression?
This issue was reported and allegedly fixed back in 2017, but i'm seeing this problem again.
https://github.com/angular/zone.js/issues/898
Probably something has changed with the GTM script, causing this issue to appear again.

### Description

When loading Google tag manager script during runtime(after zone.js has been executed), it overrides ZoneAwarePromise with native Promise, breaking change detection.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-3kvxy9

Make sure to disable any adblock extension, as it may block GTM script. Also, it would possibly be required to manually disable stackblitz serviceworkers, as they are also preventing GTM script from loading.

Click page2 link => click page1 link and notice how CD is broken. Click button to trigger CD => everything is working again.

## 🌍  Your Environment

**Angular Version:**
Stackblitz repro is using angular 8.2.14, but i have actually faced this issue with latest 9.0.0-rc3 with Ivy enabled.
zone.js of version 0.9.1 and 0.10.2 are both failing.

**Comment by JiaLiPassion** [comment]
@pshurygin, I think this issue is because the `script` is loaded dynamically, did you try to load `gtm script` statically? 
And it seems the `Promise` is overwrite by `asksuite infochat.js`, could you provide a github repo to reproduce this issue? 
Thank you!

**Comment by pshurygin** [comment]
@JiaLiPassion unfortunately i cannot load this script statically, because in my case it is provided from a backend (the app i'm working on allows to inject user-provided html into the app).

I have converted stackblitz to github repo if that is what you are asking for:
https://github.com/pshurygin/zone-js-gtm-conflict

**Comment by JiaLiPassion** [comment]
@pshurygin, the `github repo` is not be able to run, could you create a `repo` with `angular cli`? Thank you

**Comment by pshurygin** [comment]
@JiaLiPassion I have updated the repo so that you can now simply run it using ng serve.

**Comment by pshurygin** [comment]
It looks like it was not released alongside rc5. Is there a known release date for this fix?

**Comment by JiaLiPassion** [comment]
@pshurygin , I am not sure the release data, but it should be soon in the next release.
