### ISSUE TITLE
 Runtime error in Ivy mode with 9.0.0-rc.4

### ISSUE THREAD

**Issue by sergey-morenets** [angular/angular#34119]
# 🐞 bug report

### Is this a regression?

No

### Description

I have a working Angular v8 application that I tried to upgrade to 9.0.0-rc.4 to verify that Ivy mode works properly:

But in Ivy mode I get the error message when I build it, run and open in browser. In non-Ivy mode everything works fine.
Interesting that if I run it using ng serve then application works fine.

## 🔬 Minimal Reproduction

1. ng build --prod
2. Start application and open main page in the browser. You see the following error in the console.

## 🔥 Exception or Error
<pre><code>
Error: "Can't resolve all parameters for r: (?)."
</code></pre>

## 🌍  Your Environment

<pre><code>
Angular CLI: 9.0.0-rc.4
Node: 12.13.0
OS: win32 x64

Angular: 9.0.0-rc.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.4
@angular-devkit/build-angular     0.900.0-rc.4
@angular-devkit/build-optimizer   0.900.0-rc.4
@angular-devkit/build-webpack     0.900.0-rc.4
@angular-devkit/core              9.0.0-rc.4
@angular-devkit/schematics        9.0.0-rc.4
@ngtools/webpack                  9.0.0-rc.4
@schematics/angular               9.0.0-rc.4
@schematics/update                0.900.0-rc.4
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Comment by AndrewKushnir** [comment]
@sergey-morenets, could you please provide additional information and a repro, so we can try to run it and perform an investigation? Based on the error message, it looks like one of the services (with dependencies injected in constructor) doesn't have `@Injectable` decorator, which is now required in Ivy for all classes that participate in dependency injection (unless these classes have other Angular decorators like @Component, @Directive and @Pipe). Thank you.

**Comment by sergey-morenets** [comment]
@AndrewKushnir Yes, you're right. After I added missing @Injectable() decorator to a couple of services application ran properly.
Just curious, would it possible to add this check during build (not at runtime phase) ?

**Comment by AndrewKushnir** [comment]
@sergey-morenets, thanks for the update.

There is [the migration](https://next.angular.io/guide/migration-injectable) that adds `@Injectable` to classes that participate in Dependency injection. It's executed when you upgrade from v8 to v9 using CLI.

We are also working on detecting these cases better, for example there is PR #34061 in progress to cover some of the cases and turn it into compile-time error.

Thank you.
