### ISSUE TITLE
Throw on {{}}

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#3412]
The compiler should throw on `{{}}`.

**Comment by pkozlowski-opensource** [comment]
@vsavkin were you planning to check it on the parser level (`parseInterpolation`) or somewhere else in the compiler (property and text parser)?

**Comment by vsavkin** [comment]
I was thinking to check it in Parser. I think that an empty input to the parser is invalid regardless of where it comes from (hostProperties, properties, text).

**Comment by pkozlowski-opensource** [comment]
Right. I was actually bumping into this corner case when passing `null` (by accident). Agree that having an informative err message would help here.
