### ISSUE TITLE
Explanation with downloadable example

### ISSUE THREAD

**Issue by RajeevKashyap** [angular/angular#34124]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by santoshyadav198613** [comment]
Hi @RajeevKashyap ,
Not sure what you need here, can you provide the proper description so we can help.

**Comment by RajeevKashyap** [comment]
Actually, I was going through angular documentation https://angular.io/tutorial/toh-pt0 and while reading docs. I was curious to implement the same. But somewhere i stuck due to ambiguity in documents explanation and request you to please provide an example that can be downloadable. So that anyone can download and import locally for best practice. I hope you got my requirement. If you still have any query or concern, feel fee to reach out to me. Thanks!

**Comment by santoshyadav198613** [comment]
A complete example is already there which you can download.
![image](https://user-images.githubusercontent.com/11923975/69794916-2d1eb880-11f1-11ea-9fdd-f706376ef84b.png)

**Comment by RajeevKashyap** [comment]
> A complete example is already there which you can download.
> ![image](https://user-images.githubusercontent.com/11923975/69794916-2d1eb880-11f1-11ea-9fdd-f706376ef84b.png)

Thank you for reverting. It's really helpful to me. Thanks!

**Comment by santoshyadav198613** [comment]
Happy that it helped @RajeevKashyap, you can close the issue now.

**Comment by RajeevKashyap** [comment]
Hi Santosh,
I am not sure how to close this issue as I am not able to edit it anymore. Could you please close this issue or you can tell me how to close.
Thanks & Regards,


|  |  | Rajeev Kashyap
Senior Software Specialist, PTC9599106488 | rajekumar@ptc.com | Skype: rajeevkashyap3 | Parametric Technology India Pvt. Ltd., 5th Floor Tower-B, Weikfield, Vimannagar, Pune-411047
|  |  |  |

 |


 

    On Thursday, 28 November, 2019, 08:09:20 pm IST, Santosh Yadav <notifications@github.com> wrote:  
 
 
Happy that it helped @RajeevKashyap, you can close the issue now.
