### ISSUE TITLE
Basic deployment to a cpanel

### ISSUE THREAD

**Issue by sincy123** [angular/angular#34123]
![Untitled](https://user-images.githubusercontent.com/57656920/69793187-f2ffe780-11ed-11ea-9fc7-3c056e650ad6.png)

cpanel folder path : public_html/samples/asiatride_design/dist/Asia

base url : "/asiatride_design/"

**Comment by santoshyadav198613** [comment]
Hi @sincy123 ,
You can raise this issue on StackOverflow as this is not a framework issue.
