### ISSUE TITLE
ngProjectAs not working in Ivy v9 rc4

### ISSUE THREAD

**Issue by keatkeat87** [angular/angular#34120]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?
I do not know.

Did this behavior use to work in the previous version?
Yes, v8.2.14 ok

### Description
version 8 all slot is correct
![v8-good](https://user-images.githubusercontent.com/8691013/69777731-8d572f80-11dc-11ea-80d9-3b468a59f88f.gif)

version 9 all slot is not correct 
![v9-bad](https://user-images.githubusercontent.com/8691013/69777756-a5c74a00-11dc-11ea-9fd8-8ae6903a17f5.gif)

above are using same code. 

## 🔬 Minimal Reproduction
v8: https://github.com/keatkeat87/ng-project-as-issue-v8
v9: https://github.com/keatkeat87/ng-project-as-issue-v9
git clone 
ng serve --open
click button

## 🌍  Your Environment
**Angular Version:**
Angular CLI: 9.0.0-rc.4
Node: 12.3.1
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.0-rc.4
@angular-devkit/core         9.0.0-rc.4
@angular-devkit/schematics   9.0.0-rc.4
@schematics/angular          9.0.0-rc.4
@schematics/update           0.900.0-rc.4
rxjs                         6.5.3

**Comment by AndrewKushnir** [comment]
Hi @keatkeat87, thanks for reporting the issue. We were able to reproduce it and I've created a PR #34200 to fix the issue. Thank you.

**Comment by AndrewKushnir** [comment]
@keatkeat87, PR #34200 (with the changes that should fix this issue) was merged into master and the changes will be available in the upcoming 9.0.0-rc.5 release. Feel free to reopen the ticket if the problem still exists with 9.0.0-rc.5 (once it's released within the next couple days). Thank you.
