### ISSUE TITLE
basic deployment of an angular application on cpanel

### ISSUE THREAD

**Issue by sincy123** [angular/angular#34126]
cpanel folder path : public_html/samples/asiatride_design/dist/

base url : "/asiatride_design/"
![Untitled](https://user-images.githubusercontent.com/57656920/69795832-e0d47800-11f2-11ea-958f-09c10c598534.png)

how can i fix it ?

**Comment by gkalpak** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
