### ISSUE TITLE
I can no longer develop the library after update to rc.4 from rc.3 (Can't bind to 'options' since it isn't a known property of 'ngx-gallery'.)

### ISSUE THREAD

**Issue by kolkov** [angular/angular#34128]
Hi! After update to rc.4 from rc.3, my project stop working with:
![image](https://user-images.githubusercontent.com/3740898/69796090-6f8aca00-11de-11ea-922a-07988c831921.png)

please try to build this lib with rc.4:
https://github.com/kolkov/ngx-gallery/tree/9.0.0

```
Angular CLI: 9.0.0-rc.4
Node: 12.13.1
OS: win32 x64

Angular: 9.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.4
@angular-devkit/build-angular      0.900.0-rc.4
@angular-devkit/build-ng-packagr   0.900.0-rc.4
@angular-devkit/build-optimizer    0.900.0-rc.4
@angular-devkit/build-webpack      0.900.0-rc.4
@angular-devkit/core               9.0.0-rc.4
@angular-devkit/schematics         9.0.0-rc.4
@ngtools/webpack                   9.0.0-rc.4
@schematics/angular                9.0.0-rc.4
@schematics/update                 0.900.0-rc.4
ng-packagr                         9.0.0-rc.2
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2

```

**Comment by kolkov** [comment]
I tried to research, all works good now, I disabled Ivy when try to find solution to this issue. When I switched it on back, solve building problem.
https://github.com/angular/angular/issues/34023

**Comment by kolkov** [comment]
I think we need more clear error messages and check for Ivy enabled.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
