### ISSUE TITLE
Can't get an instance of component which has placed inside ng-template?

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular#34121]
I have used mycomponent inside `ng-temmplate` then i tried to take an instance of my component but it returns `undefined`

I have tried like below:

> Sample -
> https://stackblitz.com/edit/grid-details-templates-ngtemplate-outlet-hrguvv?file=app.component.ts

**Html:**

    <div class="control-section">
    	<ejs-grid #grid [dataSource]='empData' (detailDataBound)="detailsDataBound($event)" id='Grid'>
    		<ng-template #detailTemplate let-data>
    			<ng-container *ngTemplateOutlet="check"></ng-container>
    		</ng-template>
    		<e-columns>
    			<e-column field="id" headerText="നമ്പർ" width="6%"></e-column>
    			<e-column field="slNo" headerText="നമ്പർ" width="6%"></e-column>
    		</e-columns>
    	</ejs-grid>
    </div>

    <ng-template #check>
    	<ejs-grid #childComponent allowPaging='true' (load)='load($event)' [pageSettings]='pageSettings'>
    		<e-columns>
    			<e-column field='OrderID' headerText='Order ID' width='120' textAlign='Right'></e-column>
    			<e-column field='OrderDate' headerText='Order Date' width='130' format="yMd" textAlign='Right'>
    			</e-column>
    			<e-column field='Freight' headerText='Freight' width='120' format='C2' textAlign='Right'></e-column>
    			<e-column field='ShippedDate' headerText='Shipped Date' width='130' format="yMd" textAlign='Right'>
    			</e-column>
    			<e-column field='ShipCountry' headerText='Ship Country' width='150'></e-column>
    		</e-columns>
    	</ejs-grid>
    </ng-template>

**App.component.ts:**

    export class AppComponent {

      // Tried like below but no luck
        @ViewChild('childComponent', {static: false})
        private compInsideTemplate: GridComponent;

        @ViewChild('grid', {static: true})
        public grid: GridComponent;
        public data: object[];
        public datas: object[];
        public args: any;

        public getdata(args: any): object[] {
          return this.data.filter((e: any)=> e.EmployeeID === args.EmployeeID);
        }
        ngOnInit(): void {
            this.data = hierarchyOrderdata;
            this.datas = data;
          
        }
        ngAfterViewInit() {
        debugger;
        console.log(this.compInsideTemplate);
      }
      
     }

But ihave tried like below it works but i am not able take mycomponent instance exactly

> Sample - https://stackblitz.com/edit/grid-details-templates-ngtemplate-outlet-w9aqmh?file=app.component.ts

**app.component.ts:**

    export class AppComponent {

        @ViewChild('check', {static: false})
        private detailgrid: TemplateRef<any>;

        @ViewChildren('check') detailgrid1: QueryList<any>;

        @ViewChild('grid', {static: true})
        public grid: GridComponent;
        public data: object[];
        public datas: object[];
        public args: any;

        public getdata(args: any): object[] {
          return this.data.filter((e: any)=> e.EmployeeID === args.EmployeeID);
        }
        ngOnInit(): void {
            this.data = hierarchyOrderdata;
            this.datas = data;
          
        }
        ngAfterViewInit() {
        debugger;
        console.log(this.detailgrid);
        console.log(this.detailgrid1);
      }
     }

### is this not possible to take component instance when it is placed inside ng-template?

**Comment by pkozlowski-opensource** [comment]
@kumaresan-subramani there is a _lot_ going on in your stackblitz, could you try to simplify it a bit (remove all code non-essential to reproduce the issue)? This would speed up investigations, otherwise it is super-hard to see what is going on :-/

**Comment by kumaresan-subramani** [comment]
@pkozlowski-opensource , sorry for that. please refer below sample

https://stackblitz.com/edit/grid-details-templates-ngtemplate-outlet-1gboau?file=app.component.ts

I want to take instance of component which has paced inside `ng-template`

```
<div class="control-section">
	<ejs-grid #grid [dataSource]='empData' (detailDataBound)="detailsDataBound($event)" id='Grid'>
		<ng-template #detailTemplate let-data>
			<ng-container *ngTemplateOutlet="check"></ng-container>
		</ng-template>
		<e-columns>
			<e-column field="id" headerText="നമ്പർ" width="6%"></e-column>
			<e-column field="slNo" headerText="നമ്പർ" width="6%"></e-column>
		</e-columns>
	</ejs-grid>
</div>

<ng-template #check>
    // Need to instance of below component
	<ejs-grid #childComponent [dataSource]='datas' allowPaging='true' (load)='load($event)' [pageSettings]='pageSettings'>
		<e-columns>
			<e-column field='OrderID' headerText='Order ID' width='120' textAlign='Right'></e-column>
			<e-column field='OrderDate' headerText='Order Date' width='130' format="yMd" textAlign='Right'>
			</e-column>
			<e-column field='Freight' headerText='Freight' width='120' format='C2' textAlign='Right'></e-column>
			<e-column field='ShippedDate' headerText='Shipped Date' width='130' format="yMd" textAlign='Right'>
			</e-column>
			<e-column field='ShipCountry' headerText='Ship Country' width='150'></e-column>
		</e-columns>
	</ejs-grid>
</ng-template>
```

**Comment by Airblader** [comment]
You cannot query it in the AfterViewInit hook of the parent component because at that time the check template hasn't been instantiated yet. You need to wait for that to happen, and that timing depends entirely on ejs-grid. Angular cannot know when they component decides to instantiate the template passed to it.

**Comment by kumaresan-subramani** [comment]
In `ejs-grid`, we have append initialized element to DOM in `nfAfterviewInit` hook so tat i have tried to get component instance in same hook here.

https://github.com/syncfusion/ej2-angular-ui-components/blob/master/components/base/src/component-base.ts#L146

**Comment by SantiagoIlli** [comment]
Hi!

I went to [the docs](https://angular.io/guide/structural-directives#the-ng-template):

> The ng-template
The ng-template is an Angular element for rendering HTML. It is never displayed directly. In fact, before rendering the view, Angular replaces the <ng-template> and its contents with a comment.

>If there is no structural directive and you merely wrap some elements in a <ng-template>, those elements disappear. That's the fate of the middle "Hip!" in the phrase "Hip! Hip! Hooray!".

Then, I tried your stackblitz code, and your ng-template it's in fact replaced with a comment:

![image](https://user-images.githubusercontent.com/17262053/69817909-5c75fb00-11da-11ea-9e2a-bb8d4f626822.png)


Hope this helps.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

The issue is that the template is not instantiated in your example. Here is a working example: https://stackblitz.com/edit/grid-details-templates-ngtemplate-outlet-dat9ea?file=app.component.html

**Comment by kumaresan-subramani** [comment]
@mhevery , 

> The issue is that the template is not instantiated in your example. Here is a working example: https://stackblitz.com/edit/grid-details-templates-ngtemplate-outlet-dat9ea?file=app.component.html

But still i am not able to get component instance here

**Comment by mlc-mlapis** [comment]
@kumaresan-subramani The situation is more complicated than it seems to you. I recommend you to read more about the differences between `@ViewChild/@ViewChildren` and `@ContentChild/@ContentChildren` and about the level of nesting/scoping -> what can you see/get from which level.
