### ISSUE TITLE
Input property doesn't change value

### ISSUE THREAD

**Issue by teabagp** [angular/angular#34134]
# 🐞 bug report
### Description

 I created a component with some input properties. I use two-way binding for one property and change value inside the component and then change it in a parent component. After some actions, value stops changing.

## 🔬 Minimal Reproduction

[An example ](https://codesandbox.io/s/angular-ypfwd)
1. Change the value of the input.
2. You can see "Validation message"
3. Then type again -> "Validation message" is gone
4. After the next typings message doesn't appear

But I want to see the message after changes.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by michaeljota** [comment]
You should consider your inputs as read-only, and updated them only in the parent component, using outputs as you are using.

**Comment by EmaGht** [comment]
when the "change" event of this input 

`<input (change)="handler($event)" />`

gets triggered, you first do this:

`this.isValid = true;`

and then you emit your output with

`this.valueChanged.emit(e.target.value);`

on which app.component is listening on, which does this:

`this.isValid = false;`

Notice that the "isValid" variable of app.component is in turn bound to the ngModel of my.component

Basically, before Angular's change detection can run you are changing the input value twice, bringing it always back to it's invalid value, therefore Angular cannot pickup any change.

As a test, change this in app.component:
`valChanged(val: string) {
    if (val !== "test") {
      this.isValid = false;
    }
  }`

to this:
` valChanged(val: string) {
    if (val !== "test") {
      setTimeout(()=> {this.isValid = false});
    }
  }`

Welcome to Change Detection, also be sure to check stackoverflow, documentation and whatever next time ;)

**Comment by ajitsinghkaler** [comment]
@teabagp if this resolve you issue can you please close it. Please from now on can you ask these type of questions on Stackoverflow there people can better resolve these kind issues for you.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
