### ISSUE TITLE
ngcc cannot handle UMD factory without parameters ( renderFactoryParameters )

### ISSUE THREAD

**Issue by Wintermoose** [angular/angular#34138]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler-cli

### Is this a regression?

Don't know

### Description

As part of our internal library, we have simple module that has no dependencies (two of them actually, but here I'll pick the primitive one). When compiled, the UMD bundle looks something like this:
<pre><code>
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
	typeof define === 'function' && define.amd ? define('us.test', factory) :
	(global = global || self, (global.us = global.us || {}, global.us.test = factory()));
}(this, (function () { 'use strict';

	/**
	 * @fileoverview added by tsickle
	 * @suppress {checkTypes,extraRequire,missingOverride,missingReturn,unusedPrivateMembers,uselessCode} checked by tsc
	 */
	var index = "";

	return index;

}))); 
</code></pre>

You'll  notice that the factory function has no parameters. When calling ngcc on our library (included in another project), the compiler crashes with the error:

<pre>
Cannot read property 'getEnd' of undefined
at renderFactoryParameters (C:\Test\node_modules\@angular\compiler-cli\ngcc\src\rendering\umd_rendering_formatter.js:175:64)
    at UmdRenderingFormatter.addImports (C:\Test\node_modules\@angular\compiler-cli\ngcc\src\rendering\umd_rendering_formatter.js:50:13)
    at Renderer.renderFile (C:\Test\node_modules\@angular\compiler-cli\ngcc\src\rendering\renderer.js:91:35)
    at C:\Test\node_modules\@angular\compiler-cli\ngcc\src\rendering\renderer.js:50:84
...
</pre>
It would seem, that renderFactoryParameters has no test for parameters.length being zero.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.4
Node: 10.15.3
OS: win32 x64

Angular: 9.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.4
@angular-devkit/build-angular      0.900.0-rc.4
@angular-devkit/build-ng-packagr   0.900.0-rc.4
@angular-devkit/build-optimizer    0.900.0-rc.4
@angular-devkit/build-webpack      0.900.0-rc.4
@angular-devkit/core               9.0.0-rc.4
@angular-devkit/schematics         9.0.0-rc.4
@angular/cdk                       8.1.2
@angular/http                      <error>
@ngtools/webpack                   9.0.0-rc.4
@schematics/angular                9.0.0-rc.4
@schematics/update                 0.900.0-rc.4
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2
</code></pre>

**Comment by petebacondarwin** [comment]
I have a fix for this...

**Comment by petebacondarwin** [comment]
Here we go: https://github.com/angular/angular/pull/34353
