### ISSUE TITLE
Ivy: html elements from previous route are still in the DOM when ngOnInit and ngAfterViewInit are executed

### ISSUE THREAD

**Issue by MakesNine** [angular/angular#34139]
# 🐞 bug report

### Affected Package
The problem occurs only when the project is configured to use Ivy.

### Is this a regression?
I have not encountered the problem with Angular 8, but I wasn't able to test Ivy at that time because of dependencies in our project that were not compatible with Ivy.

### Description
The application displays an Amchart map that is created in the component's (map1) ngOnInit() when the user navigates to that component and it works.  However, if the user navigates to another component (map2) that also creates an Amchart map in its ngOnInit(), the map in the second component is not created and I get only an empty div (confirmed also by inspecting the dom). 

Amcharts requires that we provide the id of the div that it will use to create the chart when we call its makeChart function.  The chart/map is created as a child element of that div.
example: `<div id="chartdiv" class="map"></div>`

I have noticed that the problem only occurs when the divs used in both compoments (map1 and map2) have the same id.  If I use different ids, the map is always created as expected.
example: 
Map1 template:
`<div id="chartdiv1" class="map"></div>`
Map2 template:
`<div id="chartdiv2" class="map"></div>`

I have also noticed that when I use the same Id for both divs, and I therefore have the problem, I can briefly see that the map gets created a fraction of a second before leaving the component when I navigate from a component with a failed map (empty div) to another component that creates a map in a div with the same Id.

The behavior described above leads me to believe that, with Ivy, when I navigate to another component, the code in ngOnInit() starts its execution in the context of the template of the previous component that has not yet been deleted.  That would explain why the map is not created when I navigate from one component having a map to another one that tries to create one.

The workaround involving having different div's id works in this context but If I were to refactor the application to encapsulate the map in a dedicated component and insert that component in both map1 and map2 components it would likely not work because again a div with the same id would exist in two different routes.

## 🔬 Minimal Reproduction
I have created a minimal reproduction in the following repo: [TestIvyRc4](https://github.com/MakesNine/TestIvyRc4)

- The master branch contains the code that generates the error.
ng serve, open the app on localhost:4200, click the link "Navigate to first component with a map" than click the other link, "Navigate to second component with a map".

- The ivy-false branch contains the same code but Ivy set to false in the angularCompilerOptions.  You can verify that the problem doesn't occur with this branch.

- In the third branch named fix-chartdiv, you have the same code as in master except for the different ids provided in the templates of both map components.  The changed ids are also used accordingly in the createChart function of these components.  You can use this branch to confirm that the error goes away using a different id for each div.

## 🔥 Exception or Error
The application doesn't throw an exception/ error.  You can see however that the map isn't created.

## 🌍  Your Environment

**Angular Version:**
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.0-rc.4
Node: 10.15.0
OS: win32 x64

Angular: 9.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.4
@angular-devkit/build-angular      0.900.0-rc.4
@angular-devkit/build-ng-packagr   0.900.0-rc.4
@angular-devkit/build-optimizer    0.900.0-rc.4
@angular-devkit/build-webpack      0.900.0-rc.4
@angular-devkit/core               9.0.0-rc.4
@angular-devkit/schematics         9.0.0-rc.4
@ngtools/webpack                   9.0.0-rc.4
@schematics/angular                9.0.0-rc.4
@schematics/update                 0.900.0-rc.4
ng-packagr                         9.0.0-rc.2
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2

Other information:
We do have a workaround for the map creation problem, but I'm afraid that we will encounter other synchronization problems if it is confirmed that ngOnInit code can execute in the context of the template of a previous route.

**Comment by MakesNine** [comment]
I added console logs for some lifecycle hooks in the master branch version.  Using document.querySelectorAll(), I can see that when ngOnInit executes both the div from the current component and the div from the component in the previous route are returned.  The old div still sticks around in ngAfterViewInit and the first ngAfterViewChecked.  I can see the old div is gone when I click a button I added to trigger a log.

**Comment by AndrewKushnir** [comment]
Hi @MakesNine, thanks for reporting the issue and providing a repository with the repro. I performed additional investigation and I'd like to share the results.

I tested the app with the latest version of Angular framework (rc.7) and compared behavior in View Engine (VE) and Ivy.

VE and Ivy behavior is similar in terms of which elements are present in DOM at a certain point of time (in lifecycle hooks), i.e. both `<app-map1>` and `<app-map2>` elements (which both contain a `<div>` with the 'chartdiv' id) are present when `ngOnInit` and `ngAfterViewChecked` lifecycle hooks are executed. The difference is in the order in which `<app-map1>` and `<app-map2>` are present in DOM. While switching from `map1` -> `map2`, the order in VE is: `<app-map2>`, `<app-map1>`, when in Ivy the order is reversed. As a result, after passing `chartdiv` as a selector to this call: `this.AmCharts.makeChart('chartdiv', this.options)`, different element are found and in case of Ivy, an element from the previous route is referenced.

We will look into elements ordering further, but I'd like to propose an update to the app that should make the logic agnostic to underlying implementation (i.e. in which order elements are present). The idea is to use [ViewChild property decorator](https://angular.io/api/core/ViewChild) to reference an element inside the current view:

1. Update a template to add `#chartdiv` to the necessary div:
```
<div #chartdiv id="chartdiv" target="map1" class="map"></div>
```

2. Use `@ViewChild` decorator in Component class:
```
export class Map1Component implements OnInit, OnDestroy, AfterViewInit, AfterViewChecked {
  @ViewChild('chartdiv', {static: true, read: ElementRef}) chartdiv: ElementRef;

  // rest of the logic in the Map1Component class...
}
```

3. Update the code that creates a chart (first argument can be a DOM node):
```
this.chart = this.AmCharts.makeChart(this.chartdiv.nativeElement, this.options);
```

As a result, the `this.chartdiv.nativeElement` will always contain a reference to the right `<div>` element.

Please let me know if the proposed solution works for you.

Thank you.

**Comment by MakesNine** [comment]
Hi @AndrewKushnir, thanks for investigating this issue and reporting your findings. As you mentionned, the problem can be narrowed down to the order in which the elements are present in the DOM when navigating between components.

Thank you very much also for the solution you proposed.  I did not realized that I could pass a reference to the html element, instead of a string containing an Id, as a first argument to the makeChart method, thus allowing me to control what element is used by the third party component.  Using `@ViewChild` to retrieve the proper element will insure that I get the element defined in the template of my component, therefore isolating the code of this component from whatever else is going on in the DOM.

So yes, I very much like your proposed solution.

I would have closed the issue, but I'm not sure if you want to let it open to track the elements ordering issue with it.  

Thanks again.

**Comment by AndrewKushnir** [comment]
Hi @MakesNine, thanks for confirming that the fix worked. I'm closing this ticket for now, since elements ordering (while changing routes) is an internal implementation detail that may change between versions, so using public API methods (like `ViewChild`) is preferable. Thank you.
