### ISSUE TITLE
Angular incremental build example

### ISSUE THREAD

**Issue by invingagan1** [angular/angular#34145]
I am working on a large angular 8 based application. It is taking around 8 mins to make AOT build every time.
I am thinking to use incremental build to improve the build time as most of the code comes as shared code.

I did not find any working example of angular incremental build.
I made following changes in tsconfig.json but they did not work for me.

If some one fix or create a example that would be great help.

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "incremental": true,
    "tsBuildInfoFile": "./cache-file",
    "composite": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}

**Comment by thekip** [comment]
this is not a right place to this kind of questions. Please ask your question on StackOverflow. 

btw typescript's `incremental` flag has no effect in AngularClI, webpack or any other tool which uses typescript's api and not `tsc` command directly.

**Comment by invingagan1** [comment]
@thekip : Thanks for the reply. But Sometimes you need to ask the question who built the framework as there is no information available anywhere. however, I have asked the same question on StackOverflow.

As per https://github.com/angular/angular/commit/86a3f90
we can use an incremental flag. But there is no information how?

**Comment by SantiagoIlli** [comment]
If there is no information available and it should be you must ask for more info in the docs using the docs template. If that's not the case, you are asking for a feature request, so you should use the feature request template.
It's important to use the templates that angular team provides when we create issues.

**Comment by kapunahelewong** [comment]
Thanks for your feedback, @invingagan1. I don't know the answer to your issue, but I work on the docs and can definitely add this to our list of docs projects. We might not be able to do this right away, but I can bring it up with the docs team to make sure we discuss it. 

I know very little about this, so if anyone else can share knowledge about it here in this issue, it would be helpful. Thanks, everyone!

**Comment by Draccoz** [comment]
Any update?

**Comment by aikidave** [comment]
Hi! @invingagan1 and @Draccoz!

I've added this item to my Priority Backlog list. At the moment that's a spreadsheet, but I'm working on a better system. When I next meet with the Angular engineers, I'll see when we can address this.

As @kapunahelewong mentioned, we might not get to it right away. There's a lot on our to do list. But we do prioritize everything and you're always welcome to ping me if you need an update! Thanks for bringing this issue to our attention!

**Comment by alxhub** [comment]
`ngc` supports `--watch`, and the CLI supports incremental builds by default (on top of `ngc`'s watch mode). We generally don't give strong guidance on how to use `ngc`'s features outside of the CLI.
