### ISSUE TITLE
whitespace is included in trans-unit id

### ISSUE THREAD

**Issue by jakob-bebop** [angular/angular#34147]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

This has never been a problem before; I think it has surfaced because Prettier has started intruducing whitespace into i18n attribute values

see
https://github.com/prettier/prettier/commit/4e46f92b8648c7f25de62bfaf4368aa3f2e588d9

### Description

 A clear and concise description of the problem...
In a template, the 

    i18n="description  | name@@id" 

syntax can be used to fix the id of the translation unit. If for some reason (e.g. using Prettier) the template code is changed to

    i18n="
        description  | name@@id
    " 

the id in the resulting `messages.xlf` file now _includes the trailing whitespace_. This
messes up the subsequent xliffmerge run. Also sometimes we get duplicate trans-units
(whose id's differ by whitespace only)

## 🔬 Minimal Reproduction

- generate a project with

        ng new i18n-app

- add a whitespace-id'ed tag to the app template, and look at the resulting messages file (two instances of `sillyId`!)

        cd i18n-app
        echo '<p i18n="name| @@sillyId ">silly test</p>' >> src/app/app.component.html
        echo '<p i18n="name| @@sillyId">silly test</p>' >> src/app/app.component.html
        ng xi18n
        grep sillyId messages.xlf

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.20
Node: 10.13.0
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.20
@angular-devkit/build-angular     0.803.20
@angular-devkit/build-optimizer   0.803.20
@angular-devkit/build-webpack     0.803.20
@angular-devkit/core              8.3.20
@angular-devkit/schematics        8.3.20
@angular/cli                      8.3.20
@ngtools/webpack                  8.3.20
@schematics/angular               8.3.20
@schematics/update                0.803.20
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
I transferred this issue here because the i18n extraction code is here.

**Comment by petebacondarwin** [comment]
Should be a fairly simple fix.
