### ISSUE TITLE
ivy i18n Wrong placeholders generated for components with dash

### ISSUE THREAD

**Issue by thekip** [angular/angular#34151]
# 🐞 bug report

### Affected Package
The issue is caused by packages
**@angular/localize
@angular/compiler**

### Description

Localized build is failed if you have a components in 18n section with more than one word in name (my-test-component) (see error below)

```html
<div i18n><app-my-component></app-my-component> Welcome</div>
```
Caused because `@angular/compiler` generates xliff file with kebab-case in placeholders `START_TAG_APP-MY-COMPONENT` for components with kebab-cased name, but `ɵtranslate` from 
`@angular/localize` package expecting placeholders in underscore case format:

```ts
/// packages/localize/src/utils/src/translations.ts
export function translate(...): [TemplateStringsArray, readonly any[]] {
  ....
  return [
    translation.messageParts, translation.placeholderNames.map(placeholder => {
      if (message.substitutions.hasOwnProperty(placeholder)) {
        return message.substitutions[placeholder];
      } else {
        throw new Error(
            `No placeholder found with name ${placeholder} in message ${describeMessage(message)}.`);
      }
    })
  ];
}
```
![image](https://user-images.githubusercontent.com/1586852/69865215-e5f00080-12a0-11ea-9f54-d71e6bb47722.png)

Manual edit placeholder in translation file from Kebab-case to underscore_case helps:
```diff
+START_TAG_APP_MY_COMPONENT
-START_TAG_APP-MY-COMPONENT
```

## 🔬 Minimal Reproduction
Minimal reproduction repo is here:

https://github.com/thekip/i18n-ivy-placeholder-issue

Steps to reproduce: 

Just run `ng build` and see error or follow next steps to see more details:

1. Generate messages using `ng xi18n` command
2. Ensure that `START_TAG_APP-MY-COMPONENT` has kebab case in component name
3. Create a translation file (there is one `ru` already created in repo) and add a translation
4. Build project with any of AngularCli commands
5. See error
6. Change kebab case to unserscore case  in translation file
7.  See succesful build

## 🔥 Exception or Error
<pre><code>No placeholder found with name START_TAG_APP-MY-COMPONENT in message "293cc2dd1c2eef5113079f323ba045dd817e422d" ("{$START_TAG_APP_MY_COMPONENT}{$CLOSE_TAG_APP_MY_COMPONENT} Welcome").
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.4
Node: 10.16.0
OS: darwin x64

Angular: 9.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.4
@angular-devkit/build-angular     0.900.0-rc.4
@angular-devkit/build-optimizer   0.900.0-rc.4
@angular-devkit/build-webpack     0.900.0-rc.4
@angular-devkit/core              9.0.0-rc.4
@angular-devkit/schematics        9.0.0-rc.4
@angular/localize                 9.0.0-rc.0
@ngtools/webpack                  9.0.0-rc.4
@schematics/angular               9.0.0-rc.4
@schematics/update                0.900.0-rc.4
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

FYI @ocombe

**Comment by petebacondarwin** [comment]
From a quick read I think the problem is in how we read the placeholder names from the translation files. They need to be normalized to only contain `_` and not `-`. I'll fix it.
