### ISSUE TITLE
Ivy: cannot use async pipe in ICU 

### ISSUE THREAD

**Issue by a88zach** [angular/angular#34159]
# 🐞 bug report

### Affected Package
@angular/core
@angular/localize

### Is this a regression?
Yes, using an async pipe in an ICU and compiling without ivy works as expected

### Description

When using an async pipe with and ICU expression and running `ng serve` causes the application to crash

## 🔬 Minimal Reproduction
https://github.com/a88zach/ivy-bug

## 🔥 Exception or Error
<pre><code>
core.js:6354 ERROR Error: No provider for ChangeDetectorRef!
    at Module.ɵɵinjectPipeChangeDetectorRef (core.js:38723)
    at AsyncPipe_Factory (common.js:6777)
    at Module.ɵɵpipe (core.js:36808)
    at AppComponent_Template (app.component.html:1)
    at executeTemplate (core.js:13942)
    at renderView (core.js:13744)
    at renderComponent (core.js:15179)
    at renderChildComponents (core.js:13546)
    at renderView (core.js:13770)
    at ComponentFactory$1.create (core.js:34242)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.4
Node: 10.15.3
OS: darwin x64

Angular: 9.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.4
@angular-devkit/build-angular     0.900.0-rc.4
@angular-devkit/build-optimizer   0.900.0-rc.4
@angular-devkit/build-webpack     0.900.0-rc.4
@angular-devkit/core              9.0.0-rc.4
@angular-devkit/schematics        9.0.0-rc.4
@angular/localize                 9.0.0-rc.0
@ngtools/webpack                  9.0.0-rc.4
@schematics/angular               9.0.0-rc.4
@schematics/update                0.900.0-rc.4
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment]
Hi @a88zach, thanks for reporting the problem. We were able to reproduce it and I've created a PR #34198 to resolve the issue. Thank you.

**Comment by pkozlowski-opensource** [comment]
This is fixed in master via #34198, will be part of the next release.
