### ISSUE TITLE
Angular routing without zone.js

### ISSUE THREAD

**Issue by ms-dosx86** [angular/angular#34150]
I know that in new angular 9 we can work without zone.js because of the new engine Ivy. So I've created a new app and added one simple route /dashboard. And when I navigate to that route it seems that ngOnInit doesn't trigger. As a workaround I can do this.router.navigate(['dashboard']).then(() => markDirty(this));, but what to do when you manually open the /dashboard route from the address bar? Do I have to subscribe to all router events and trigger change detection manually? In angular 8 it doesn't work either. I assume that all of this async stuff is handled by zonejs, so how to deal with it without zonejs? I'm dealing with hybrid app and zonejs does really affect to performance.

**Comment by marcj** [comment]
>  Do I have to subscribe to all router events and trigger change detection manually

Yes.

```
class AppComponent {
    constructor(
        router: Router,
        a: ApplicationRef,
    ) {
        router.events.subscribe((event: Event) => {
            if (event instanceof NavigationEnd || event instanceof ActivationEnd) {
                a.tick();
            }
        });
    }
}
```

> I assume that all of this async stuff is handled by zonejs, so how to deal with it without zonejs?

Correct, you have two options. Call manually `ChangeDetectorRef.detectChanges`. Or call `ChangeDetectorRef.markForCheck` and schedule a `ApplicationRef.tick` in the next `requestAnimationFrame`. A handy custom abstraction/service for that should be necessary. We use Typescript decorators for Observable and async methods, which automatically call `ApplicationRef.tick` when either resolved or Observable `next`ed, completed, or errored.

In my rather big desktop application we got rid of Zonejs as well. Add these lines in your constructor as well to support almost anything as usual.

```
        document.addEventListener('click', () => a.tick());
        document.addEventListener('mousedown', () => a.tick());
        document.addEventListener('focus', () => a.tick());
        document.addEventListener('blur', () => a.tick());
        document.addEventListener('keydown', () => a.tick());
        document.addEventListener('keyup', () => a.tick());
        document.addEventListener('keypress', () => a.tick());
```

but you need to call `ChangeDetectorRef.detectChanges()` manually when you change data in your components via anything other than those DOM events you just subscribed. For example XHR, websockets, setTimeout, resolved Promises, etc.

**Comment by ms-dosx86** [comment]
@marcj I wasn’t sure that it’s a good practice, now it make sense. Thank you for quick response =) have a good day
