### ISSUE TITLE
refactor(facade): move facade into separate top-level module

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#3415]
In the process of moving Http into its own module (#2680), there is still a requirement to depend on angular2 because of facades and dependency injection. The facades should be moved into their own top-level package so that other top-level modules will not need to depend on all of Angular2.

Right now, I'm planning to take this on after I finish #2680, since the process will be fresh in my head. But I'm waiting to self-assign until I clear some things off my plate.

**Comment by rolandjitsu** [comment]
:+1: It would be really nice to have it, I tend to use many of the methods exposed by the facade, especially all the wrappers.

**Comment by gdi2290** [comment]
great idea for 3rd party modules that also want to support ts and dart

**Comment by jeffbcross** [comment]
Bad news, fellas, it's going to stay in core for now. It's not really a thing we want to maintain and support for outside folks, and I doubt there will be _significant_ interest in building libs that target both JS and Dart. It will still be in the core and could pretty easily be consumed by installing the angular2 package and moving it into its own module though. If later on it becomes apparent that there's value to separating it, there's no reason we couldn't do it at that time.

**Comment by jeffbcross** [comment]
The good news is, ts2dart keeps improving and the facade is getting smaller and less necessary.
