### ISSUE TITLE
Instructions for how to compile without Ivy?

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular#34160]
When compiling a library we get this message:

```

ole@mkt:~/Github/angular-stripe-service-workspace$ ng build angular-stripe-service-lib
Building Angular Package

** It is not recommended to publish Ivy libraries to NPM repositories **

------------------------------------------------------------------------------
Building entry point '@fireflysemantics/angular-stripe-service'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Copying declaration files
Writing package metadata
Built @fireflysemantics/angular-stripe-service

```

Then when we try to publish it we get this message:

> ERROR: Trying to publish a package that has been compiled by Ivy. This is not allowed. Please delete and rebuild the package, without compiling with Ivy, before attempting to publish.

But no instructions on how to compile without Ivy.  This is the answer to that:

https://stackoverflow.com/questions/59113052/how-to-compile-a-library-without-ivy?noredirect=1#comment104457188_59113052

But it would have been nice if it did this by default or the instructions were included in the message.

**Comment by kolkov** [comment]
Try to disable Ivy with `enableIvy=false`

**Comment by alan-agius4** [comment]
Kindly see: https://next.angular.io/guide/creating-libraries#publishing-your-library

**Comment by alan-agius4** [comment]
In the next version of ng-packagr a link will be added ad per this bug request https://github.com/ng-packagr/ng-packagr/issues/1453

Going to close this issue as the warning is shown by a ng-packagr and not the Angular compiler and it has also been already addressed.

**Comment by kolkov** [comment]
> Kindly see: https://next.angular.io/guide/creating-libraries#publishing-your-library

But how we works now with local libs as `npm link` like before?

**Comment by alan-agius4** [comment]
@kolkov, the `npm link` issue is currently being tracked here: https://github.com/angular/angular/issues/33395
