### ISSUE TITLE
Building existing library as Custom Elements fails

### ISSUE THREAD

**Issue by kolkov** [angular/angular#34161]
Hi! I try to build my library as Angular Elements, but I can't do this.
I can't botstrap my main library component, but if I add new component this works inside new component, but this behavior wery strange for me.
Whats wrong?

![image](https://user-images.githubusercontent.com/3740898/69897897-0ed8ca00-1363-11ea-83ac-b5eeb5e625f9.png)

![image](https://user-images.githubusercontent.com/3740898/69897940-9f170f00-1363-11ea-85d0-17e011f662b3.png)

![image](https://user-images.githubusercontent.com/3740898/69897955-ba821a00-1363-11ea-8ef8-a78c53504b49.png)

![image](https://user-images.githubusercontent.com/3740898/69897959-d685bb80-1363-11ea-8bd8-f040a302707c.png)

![image](https://user-images.githubusercontent.com/3740898/69897963-ea312200-1363-11ea-98b8-d2aa8176451d.png)

![image](https://user-images.githubusercontent.com/3740898/69897889-fc5e9080-1362-11ea-87ff-921740cef645.png)

But if I comment tag:
![image](https://user-images.githubusercontent.com/3740898/69897996-4b58f580-1364-11ea-9310-2ecd19919df3.png)

I see:
![image](https://user-images.githubusercontent.com/3740898/69898004-61ff4c80-1364-11ea-8395-21e07efacc9e.png)

Source code at:
https://github.com/kolkov/angular-editor/tree/elements

``` Angular CLI: 8.3.20
Node: 12.13.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.20
@angular-devkit/build-angular      0.803.20
@angular-devkit/build-ng-packagr   0.803.20
@angular-devkit/build-optimizer    0.803.20
@angular-devkit/build-webpack      0.803.20
@angular-devkit/core               8.3.20
@angular-devkit/schematics         8.3.20
@angular/cli                       8.3.20
@ngtools/webpack                   8.3.20
@schematics/angular                8.3.20
@schematics/update                 0.803.20
ng-packagr                         5.7.1
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2
```

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by kolkov** [comment]
@mhevery If I understand correctly, you builded this library as custom Angular elements, and they were built and bootstrapped correctly?
