### ISSUE TITLE
Support A/B & MVT Testing. 

### ISSUE THREAD

**Issue by SADHASIVAM-BE** [angular/angular#34166]
🚀 A/B & MVT Testing

### Description
One of my clients enterprise application, looking AB & MVT testing solution in Angular. Its biggest drawback with angular to turn around into front end migration.

Functional requirement : Async load angular component (compiled) JavaScript file and register with appropriate module. Once its loaded, wanted to append or replace existing component. 

**Example**: Giving different menu bar experience to 50% traffic.

#hello world - main.js file (production mode) - Here i going to change HTML template alone, rest of event binding are same.
(window.webpackJsonp = window.webpackJsonp || []).push([
    [1], {
        0: function(n, o, t) {
            n.exports = t("zUnb")
        },
        zUnb: function(n, o, t) {
            "use strict";
            t.r(o);
            var e = t("fXoL"),
                r = t("jhN1");
            let s = (() => {
                    class n {}
                    return n.\u0275fac = function(o) {
                        return new(o || n)
                    }, n.\u0275cmp = e.pb({
                        type: n,
                        selectors: [
                            ["app-root"]
                        ],
                        decls: 2,
                        vars: 0,
                        **template: function(n, o) {
                            1 & n && (e.xb(0, "h1"), e.Db(1, "Hello world"), e.wb())
                        },**
                        styles: [""]
                    }), n
                })(),
                c = (() => {
                    class n {}
                    return n.\u0275mod = e.tb({
                        type: n,
                        bootstrap: [s]
                    }), n.\u0275inj = e.sb({
                        factory: function(o) {
                            return new(o || n)
                        },
                        providers: [],
                        imports: [
                            [r.a]
                        ]
                    }), n
                })();
            Object(e.H)(), r.b().bootstrapModule(c).catch(n => console.error(n))
        },
        zn8P: function(n, o) {
            function t(n) {
                return Promise.resolve().then((function() {
                    var o = new Error("Cannot find module '" + n + "'");
                    throw o.code = "MODULE_NOT_FOUND", o
                }))
            }
            t.keys = function() {
                return []
            }, t.resolve = t, n.exports = t, t.id = "zn8P"
        }
    },
    [
        [0, 0, 5]
    ]
]);

**Comment by dblVs** [comment]
@SADHASIVAM-BE This is not an issue with angular. 

You can already achieve that by building an A/B testing outlet directive which has multiple components passed in and chooses 1 in random OR creating few different modules which you lazyload. 

P.S. Posting your own code is generally frowned upon, because it shows lack of effort on your side to actually understand your problem and expecting other people to spend their time to look into something you don't think is worth your time.

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
