### ISSUE TITLE
refactor(di): move di into its own top-level module

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#3416]
Since other modules that live outside of core, #2680 for example, use DI, di should be moved into its own module. This way, its dependents can use DI without a dependency on the whole angular2 module.

**Comment by jeffbcross** [comment]
Closing since we decided to move this to "core" and not publish it.

**Comment by PascalPrecht** [comment]
Is that the decision for now or will it be available "standalone" someday?

**Comment by DavidSouther** [comment]
What would be needed to reopen this? Reading through the DI code, nothing is environment specific, and it would be *incredibly* useful to use this in a Node.js project.

**Comment by PascalPrecht** [comment]
@DavidSouther for now you can totally just use the `angular2/di` module, even without using Angular at all. However, it requires you to install the whole framework, which you might not want.

Would also like to hear @jeffbcross' thoughts on this.

**Comment by robwormald** [comment]
Agreed on making this a standalone published module, especially since DI.js is dying a slow death.

**Comment by DavidSouther** [comment]
I've been having trouble getting `import { Inject, Binding } from 'angular2/di'` working in TypeScript node projects; it's likely blocked on Microsoft/Typescript#247

**Comment by nateabele** [comment]
Seems like we've been slowly moving away from the "Angular 2 is going to be a framework of decoupled libraries" position for a while now. Safe to say that's officially no longer a goal?

**Comment by jeffbcross** [comment]
@nateabele good question. That's not our primary goal at the moment, as we focus on creating a good integrated experience for the framework. It's definitely on our minds start thinking about where there's value to decouple parts of the framework, di being the most obvious bit. Though DI moved into its own module, @vsavkin and I are planning to add it to our npm release process soon (not sure if it's going to be published to our existing di package on npm or a new one though).

**Comment by nateabele** [comment]
@jeffbcross That sounds great, thanks for the update.

**Comment by calebboyd** [comment]
@jeffbcross @vsavkin I know you guys off on other endeavors but is anyone picking this up in core?

**Comment by jeffbcross** [comment]
I think it was decided that this would not be something supported by the
core team.

**Comment by calebboyd** [comment]
Ah shucks! 😞 Sounds like its probably depended upon by compiler/AoT... Guess you can't optimize for everything..
