### ISSUE TITLE
I've tried much times, does anyone know that how to test element, class and attribute in angular using jasmine?

### ISSUE THREAD

**Issue by SunnyVakil** [angular/angular#34167]
Here I'm trying to test attribute of a button which is, variant="icon"
it('', () => {

  const de = fixture.debugElement.query(By.css('button'));

  const el: HTMLElement = de.nativeElement;

  expect(el.attributes['variant'].value).toEqual('icon');

  });

Here, I'm trying to test span element inside the list-data class.

it('', () => {

  const de = fixture.debugElement.nativeElement;

 expect(de.querySelector('.list-data')).toContain('span');

  });

Here, I'm trying to test class btn with the class btn-primary

it('', () => {

  const de = fixture.debugElement.query(By.css('.btn'));

  const el: HTMLElement = de.nativeElement;

  expect(el.classList['btn-primary']).toBe(true);

  });

But all are the fail, can anyone help.

any help would be helpful.

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests. I provided some basic information below and please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular` in case additional information/help is required.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

> to test attribute of a button which is, variant="icon"

You can probably access element properties directly on the element, for example:
```
expect(el.variant).toEqual('icon');
```

> test span element inside the list-data class.

Try expanding selector to include `span`:
```
expect(de.querySelector('.list-data span')).toBeTruthy();
```

> test class btn with the class btn-primary

Try to use `contains` method of the [classList](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) to check if a certain class exists:
```
expect(el.classList.contains('btn-primary')).toBe(true);
```

Hope this helps. Please post your question on [StackOverflow](http://stackoverflow.com/) using tag `angular` if more information is required.

Thank you.
