### ISSUE TITLE
@HostListener docs do not mention option to listen to global events

### ISSUE THREAD

**Issue by JPGygax68** [angular/angular#34165]
I'm stil relatively new to Angular, so it's probable that someone with more knowledge could guess this. But it seems to me that this options should be mentioned; it's anything but self-evident that a decorator that connects to DOM events targeted at the host element can also subscribe to window events, let alone how that is done.

For example, I had found `@HostListener` somewhere on the internet, and used it as I had found it, which was with "window:" prepended to the event name. This appeared to work for me, until I noticed that my keyboard handler would react even when my component wasn't focused. It took me a while to figure out that the prepended "window:" was actual non-standard usage.

```typescript
@HostListener('window:keydown', ['$event'])
  handleKeyDown(event: KeyboardEvent) {

    console.log('handleKeyDown:', event);
   //...
```

**Comment by pauldraper** [comment]
`document:` too.

**Comment by MrJithil** [comment]
@kapunahelewong PR created with an example which mentioning how we could handle a global event.

**Comment by MrJithil** [comment]
![image](https://user-images.githubusercontent.com/26359740/70138131-98ff9600-16b5-11ea-8c3a-d0d66c990489.png)

**Comment by kapunahelewong** [comment]
Thank you so much for this, @MrJithil! You are rad!

**Comment by JPGygax68** [comment]
@MrJitHil Thank you! The example is good (typo: "Youn" where it should be "You"), but it should be clearly stated somewhere what the difference is compared to listening to the host element.
Also, referring to @pauldraper 's comment, it would great if both options were mentioned, `window` and `document`.

**Comment by MrJithil** [comment]
> @MrJithil Thank you! The example is good (typo: "Youn" where it should be "You"), but it should be clearly stated somewhere what the difference is compared to listening to the host element.
> Also, referring to @pauldraper 's comment, it would great if both options were mentioned, `window` and `document`.

We have rewritten the sentence to "The following example registers another DOM event handler that listens for key-press events".

**Comment by kapunahelewong** [comment]
Thanks agian, @MrJithil! @JPGygax68 I'll close this now that https://github.com/angular/angular/pull/34228 has merged. If you have any outstanding questions, please feel free to re-open or submit another issue. Thanks!
