### ISSUE TITLE
ng service-worker does not cache data

### ISSUE THREAD

**Issue by postnikovpasha** [angular/angular#34203]
ng service-worker caches data only for the time specified in the Cache-Control response header: public, max-age = 60, s-maxage = 60. After 60 seconds in offline mode, the response 504 Gateway Timeout (from ServiceWorker) comes to the request.

```
 {
      "$schema": "./node_modules/@angular/service-worker/config/schema.json",
      "index": "/index.html",
      "assetGroups": [
        {
          "name": "app",
          "installMode": "prefetch",
          "resources": {
            "files": [
              "/favicon.ico",
              "/index.html",
              "/manifest.webmanifest",
              "/*.css",
              "/*.js"
            ]
          }
        },
         {
          "name": "assets",
          "installMode": "lazy",
          "updateMode": "prefetch",
          "resources": {
            "files": [
              "/assets/**",
              "/app/app.component.ts",
              "/*.(pdf|odt|eot|svg|cur|jpg|png|webp|gif|otf|ttf|woff|woff2|ani)"
            ]
          }
        }
      ],
      "dataGroups": [
      {
          "name": "github-api",
          "urls": ["**//api.github.com/**"],
          "cacheConfig": {
          "strategy": "performance",
          "maxSize": "100",
          "maxAge": "7d"

        }
      }
    ]
    }
```
What could be the problem?

P.S. I installed the worker for my application using this command:
 ng add @angular/pwa --project project-name –

**Comment by gkalpak** [comment]
That should work as expected. Can you point us to a reproduction (either publicly accessible deployed app that suffers from the problem or a minimal project along with instructions on how to build and run it in order to see the problem).

**Comment by postnikovpasha** [comment]
Here is a project in which the cache is only stored for 60 seconds. Then in offline mode Status Code: 504 Gateway Timeout (from ServiceWorker).
[https://github.com/postnikovpasha/testCacheNgSw](url)

**Comment by gkalpak** [comment]
It works correctly for me. I am going to close this issue, but feel free to continue the discussion below.

How so you serve the app?
What does `http://127.0.0.1:8080/ngsw/state` show?

**Comment by postnikovpasha** [comment]
Many thanks! At http://127.0.0.1:8080 everything really worked. The error was in the configuration of the real server.

Another question arose. Is it possible to cache outgoing requests?
For example, a user creates a message offline and clicks the "Send" button, and the application as soon as connected to the Internet sends this message to the server.

**Comment by gkalpak** [comment]
Glad you sorted it out :tada:

There are features such as [Background Sync][1] and [Background Fetch][2], but they are not standardized yet (so only some browsers support them) and the Angular SW does not support them atm.

[1]: https://developers.google.com/web/updates/2015/12/background-sync
[2]: https://developers.google.com/web/updates/2018/12/background-fetch

**Comment by postnikovpasha** [comment]
That is, for these functions you need to write a separate SW? Is it possible to distinguish POST and Get requests in the description of the SW configuration if the URLs of these requests are the same?

**Comment by postnikovpasha** [comment]
I had an idea how to bypass caching of outgoing requests. I can save the contents of outgoing requests in local storage, and when an Internet connection appears, send requests to the server with the contents of the local storage. Is such a solution possible or is it a bad practice?

**Comment by gkalpak** [comment]
Every page can only be controlled by one SW. So, you need your own SW implementation (e.g. based on [WorkBox][1] if you need to support features that are not built-in in the Angular SW. (It is theoretically possible to combine Angular's SW with your own, where your own handles some requests and passes the rest through to the Angular SW, but it is not official supported (so kind of a hack) and might be a little brittle. I don't recommend this approach, unless it is for something trivial and you really know what yo are doing.)

Regarding saving pending requests in `LocalStorage`:
If it works for your usecase, then fine. But in general, this kind of functionality has several requirements that are not covered by this approach.

[1]: https://developers.google.com/web/tools/workbox

**Comment by postnikovpasha** [comment]
Is it possible to distinguish POST and Get requests in the description of the SW configuration if the URLs of these requests are the same?

**Comment by gkalpak** [comment]
I am not sure what you mean by "distinguish". The SW only caches handles non-mutating requests (i.e. GET, HEAD, OPTIONS), but (unless [bypassed][1]) the SW will handle all requests (even if just to forward them to the network).

[1]: https://angular.io/guide/service-worker-devops#bypassing-the-service-worker

**Comment by postnikovpasha** [comment]
How to describe the configuration so that SW does not handle outgoing requests?

**Comment by gkalpak** [comment]
I am confused. All requests are outgoing 😕
If you mean PUT/POST requests, then it is not possible to configure the SW to ignore them. You can do it on a per-request basis (as described [here][1]), but at this point you might be better off implementing your own SW.

[1]: https://angular.io/guide/service-worker-devops#bypassing-the-service-worker

**Comment by postnikovpasha** [comment]
Thanks so much for the consultation!
('ngsw-bypass', 'true') is exactly what I need!
