### ISSUE TITLE
ERROR on build: unexpected value null exported by the module

### ISSUE THREAD

**Issue by vitaliypva** [angular/angular#34223]
I'm getting this error during the Angular Build (ng build --prod):
`ERROR in: Unexpected value 'null' exported by the module 'SharedModule'`
It builds fine for dev (ng build)

I  have this error when I have:
`export default class SomeComponent {...}` 
    
Changing it to: 
    `export class SomeComponent {...}` 
fixes the problem

**Comment by MrJithil** [comment]
@vitaliypva  Please leave more detailed explanation. If it's a project specific issue you are facing, then please use some forums. If you still think it's an issue with the framework, please add more detailed description to reproduce the issue.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
