### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular#34226]
# 🐞 bug report

I have created an angular application with our multiselect control, refer below:

https://stackblitz.com/edit/angular-5hwaty?file=src/app/app.component.ts

I am facing below error when i choose dropdown value and click button which has been placed inside dropdown value usig `ng-template`,  facing below error

```
ERROR
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ng-untouched: true'. Current value: 'ng-untouched: false'.
```

### Description

I have tried so many solutions which are listed below:

1. https://stackoverflow.com/questions/39787038/how-to-manage-angular2-expression-has-changed-after-it-was-checked-exception-w

2.https://github.com/angular/angular/issues/14748#issuecomment-313190829

3.https://github.com/angular/angular/issues/14748#issuecomment-312148877

## 🔬 Minimal Reproduction

1. open sample - https://stackblitz.com/edit/angular-5hwaty?file=src/app/app.component.ts
2. choose drop-down value in sample
3.click button in choosed value 
4. you will see an error

> Note : Error occurs only in first time clicking button

## 🔥 Exception or Error
Issue occurs only in chrome browser:

https://github.com/angular/angular/issues/22426#issuecomment-368306896

## 🌍  Your Environment

Latest angular packages:

`Angular-cli : 8.3.20`

**Anything else relevant?**

When i use `changeDetection: ChangeDetectionStrategy.OnPush` it works fine

**Comment by kumaresan-subramani** [comment]
I think issue similar to below:

https://github.com/angular/angular/issues/34121

i have used function in button click but i am using it inside `ng-template` so when i click button it throws error.

Can anyone please confirm this?

**Comment by EmaGht** [comment]
If you comment out the line that actually opens the modal:

`const modalRef = this.modalService.open('clicked: ' + data['sports']);`

you'll see it works.
This means the opening of the modal is causing that issue.

It looks like there is a problem with your integration of ng-bootstrap or ng-bootstrap has a bug/side effect causing the issue.

Still, it's not a problem with Angular and this questions should be asked in StackOverflow

**Comment by kumaresan-subramani** [comment]
@EmaGht , thanks...
