### ISSUE TITLE
CanActivateOr interface

### ISSUE THREAD

**Issue by GiorgosPap** [angular/angular#34230]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/router

### Description
The current implementation of **CanActivate** interface is:  

> If all guards return true, navigation will continue. 

### Describe the solution you'd like
It would be useful to exist a **CanActivateOr** interface that will evaluate the following:

>  If some guards return true, navigation will continue. 

Example
```
const routes: Routes = [
  {
    path: 'pathA',
    component: ComponentA,
    resolve: {
      data: ResolverA
    },
    CanActivateOr: [Guard1, Guard2] // If Guard1 OR Guard2 returns true then continue
  }
];
```

**Comment by Airblader** [comment]
What would this be useful for?

**Comment by GiorgosPap** [comment]
Example:
Let's say that we have 2 different guards in the app: **ClientGuard** and **CompanyGuard** and we use them in different routes in order to allow a **client/company** to enter the route respectively.

```
const routes: Routes = [
  {
    path: 'pathA',
    component: ComponentA,
    resolve: {
      data: ResolverA
    },
    CanActivate: [ClientGuard] // only client has access to ComponentA
  },
 {
    path: 'pathB',
    component: ComponentB,
    resolve: {
      data: ResolverB
    },
    CanActivate: [CompanyGuard] // only company has access to ComponentB
  },
];
```

Now if we want to create a new route that should allow access to a user that is **client** OR **company**, it would be useful to create a new route with the suggested interface **CanActivateOr** in order to evaluate one of them:

```
const routes: Routes = [
  {
    path: 'pathC',
    component: ComponentC,
    resolve: {
      data: ResolverC
    },
    CanActivateOr: [ClientGuard, CompanyGuard] // suggested interface
  }
];
```

With the current implementation (i.e. CanActivate), we should **create a new Guard** that evaluates the other two guards and returns true/false. So we need to write more code.

Maybe there is another way, but I think it would be useful this way. 

Thank you in advance

**Comment by matthewjh** [comment]
It seems to me a better solution to write a new guard that composes your guards A and B, ORing their results, rather than lifting "or" to the framework. Should the framework later do the same for "and"?

**Comment by Airblader** [comment]
"and" is what the framework already does, but I agree that I'd KISS this and compose the guards instead.

**Comment by atscott** [comment]
I agree with what has been said above, composing the two guards seems like a good approach.
