### ISSUE TITLE
export type definitions for test_lib

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#3423]
Has it been considered exposing the typings for the `angular2/test_lib` module? Maybe even have it as top level module? Because I use some of the exposed methods in unit tests for the components I write, and I think that might be the case for many others, unless there is a plan for some other lib for unit tests.

**Comment by jeffbcross** [comment]
Taking care of this today

**Comment by jeffbcross** [comment]
Moved it to next milestone because of some complications with cross-module dependencies that I need to figure out.

**Comment by mhevery** [comment]
Duplicate of #3714
