### ISSUE TITLE
elements schema: support web components

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#3424]
As of today element schema DOM-based implementation doesn't detect web components correctly and as such we are not doing 2 checks that we otherwise could:
* not allowing both a web component and @Component on the same DOM element (see: #3391)
* correctly detecting bindings to web component properties

Explore how we could better support web components in all the environments (js / dart and browser / server-side compilation) and change the schema accordingly.

**Comment by vicb** [comment]
provisioned in NgModule
