### ISSUE TITLE
ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by pawanjoshi** [angular/angular#34253]
Hello, I'm getting a ReferenceError: Element is not defined while working on Angular seo task.

I run the below command:

**npm i @ng-toolkit/universal** 

then 

**npm run build:prod**

both worked but  while I am using below command:

**npm run server** 

getting below error:

ReferenceError: Element is not defined
    at Object.316.326 (E:\streetpin-phase3-web\dist\server.js:221531:104525)
    at o (E:\streetpin-phase3-web\dist\server.js:221531:446)
    at E:\streetpin-phase3-web\dist\server.js:221531:497
    at Object.314.299 (E:\streetpin-phase3-web\dist\server.js:221531:103950)
    at o (E:\streetpin-phase3-web\dist\server.js:221531:446)
    at E:\streetpin-phase3-web\dist\server.js:221531:497
    at Object.311.314 (E:\streetpin-phase3-web\dist\server.js:221531:103252)
    at o (E:\streetpin-phase3-web\dist\server.js:221531:446)
    at E:\streetpin-phase3-web\dist\server.js:221531:497
    at Object.312.311 (E:\streetpin-phase3-web\dist\server.js:221531:103437)

**Environment:**

Angular CLI: 6.2.9
Node: 10.16.3
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.9
@angular-devkit/build-angular     0.12.1
@angular-devkit/build-optimizer   0.12.1
@angular-devkit/build-webpack     0.12.1
@angular-devkit/core              0.8.9
@angular-devkit/schematics        0.8.9
@angular/cli                      6.2.9
@angular/compiler-cli             7.2.5
@angular/fire                     5.2.3
@ngtools/webpack                  7.2.1
@schematics/angular               0.8.9
@schematics/update                0.8.9
rxjs                              6.2.2
typescript                        3.2.4
webpack                           4.41.2

**Comment by pkozlowski-opensource** [comment]
Sounds like something that should be opened in https://github.com/maciejtreder/ng-toolkit first...
