### ISSUE TITLE
Angular 9 rc. 3 error in Render Ivy + Nebular Theme

### ISSUE THREAD

**Issue by BrayanVG** [angular/angular#34259]
# 🐞 bug report

### Affected Package
The issue is caused by package @nebular/theme@4.6.0

### Is this a regression?
Yes, the previous version in which this bug was not present was: 
This started using the new Render of Angular Ivy and I was also introduced in Angular 8, I am currently using Angular 9.rc 3

### Description

I started an application using Angular 9 rc.3 I added Angular Material, then Nebular Theme and compiled the project all right until it started with the Nebular

## 🔥 Exception or Error
<pre><code>
ERROR in Failed to compile entry-point @nebular/theme due to compilation errors:
node_modules/@nebular/theme/fesm2015/index.js(17791,5): error TS-996003: Appears in the NgModule.exports of NbTableModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class
node_modules/@nebular/theme/fesm2015/index.js(17827,5): error TS-996002: Appears in the NgModule.imports of NbTreeGridModule, but itself has errors
node_modules/@nebular/theme/fesm2015/index.js(17827,5): error TS-996003: Appears in the NgModule.exports of NbTreeGridModule, but itself has errors

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.0-rc.5
Node: 12.6.0
OS: win32 x64

Angular: 9.0.0-rc.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.5
@angular-devkit/build-angular     0.900.0-rc.5
@angular-devkit/build-optimizer   0.900.0-rc.5
@angular-devkit/build-webpack     0.900.0-rc.5
@angular-devkit/core              9.0.0-rc.5
@angular-devkit/schematics        9.0.0-rc.5
@angular/cdk                      8.2.3
@angular/fire                     5.2.3
@angular/material                 8.2.3
@ngtools/webpack                  9.0.0-rc.5
@schematics/angular               9.0.0-rc.5
@schematics/update                0.900.0-rc.5
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Comment by ericmartinezr** [comment]
Dup of https://github.com/akveo/nebular/issues/2113. Still not up to me to decide if this is because of angular itself, or the 3rd lib.

**Comment by JoostK** [comment]
This is a known issue and fixed by #34014.

**Comment by BrayanVG** [comment]
> This is a known issue and fixed by #34014.

I don't understand what needs to be done, the files are different in this is called, are they using Angular / cli?

**Comment by BrayanVG** [comment]
This is a known issue and fixed by #34014. @JoostK 

I don't understand what needs to be done, the files are different in this is called, are they using Angular / cli?

**Comment by petebacondarwin** [comment]
@BrayanVG - once that PR (#34014) is merged and released, please check again if this is failing for you.

**Comment by BrayanVG** [comment]
Hi @petebacondarwin , how to know if Ivy is really active in the project, sometimes it appears compiling the libraries and this means that it is active, but sometimes it does not, how to know that an improvement has been released and how to implement its update, These errors with the Angular / Material and Angular / Nebular libraries occur very varied, why is that?

**Comment by BrayanVG** [comment]
Many times errors occur, I stop the project, compile again and it goes well, or I have to deactivate Ivy to continue compiling without problems

**Comment by petebacondarwin** [comment]
@BrayanVG - it appears you are running Angular RC.5 so ivy is enabled by default. Unless you have set `enableIvy: false` in your tsconfig you are building with ivy.
The fix mentioned above will be released in 9.0.0-rc.6 later this week. Once that is published, please try again.

**Comment by JoostK** [comment]
Closing as #34014 has landed. The fix will be available in the next release.

**Comment by BrayanVG** [comment]
Okay @petebacondarwin , I will be attentive, my version in the package.json is rc.3 so I must update the globlal and also my project
