### ISSUE TITLE
Not able to get Observable value into other modules component using shared services

### ISSUE THREAD

**Issue by nileshzala005** [angular/angular#34250]
Please check this GitHub repo https://github.com/nileshzala005/Service-demo

userService registered at root level.

I would like to get getUserLogin observable value into SharedModule's UserComponent.when user click on button " Send value to user component" from HomeComponent that is declared into HomeModule

UserService at the root level
` userLogin = new Subject<string>();

  constructor() { }
  sendUserLogin(user: string) {
    console.log("value received at user service ", user);
    this.userLogin.next(user);
  }
  getUserLogin(): Observable<string> {
    return this.userLogin.asObservable();
  }
`
HomeComponent in homeModules

`export class HomeComponent implements OnInit {

  constructor(private userService: UserService) {

  }

  ngOnInit() {
  }
  onClick() {
    console.log("value is send from home component", "Nilesh")
    this.userService.sendUserLogin("Nilesh");
  }

}
`
User Component in Shared modules
`export class UserComponent implements OnInit {

  constructor(private userService: UserService) { }

  ngOnInit() {
    this.userService.getUserLogin().subscribe(res => {
          /// here it should receive but not able to get it
      console.log("user component should get value here ", res);
    });
  }

}
`

**Comment by mlc-mlapis** [comment]
@nileshzala005 Each time your `return this.userLogin.asObservable();` would be a new observable. Maybe read more here https://stackoverflow.com/questions/36986548/when-to-use-asobservable-in-rxjs

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
