### ISSUE TITLE
elements schema: detect invalid events

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#3426]
We should detect and report invalid event handlers. Built-in DOM events and custom-element events need to be hand-coded into schema support. We also need to:
- take directive events into account
- be able to re-map event names (for example to correctly handle events with mixed and dash-case).

**Comment by splincode** [comment]
@pkozlowski-opensource Is the issue relevant?

**Comment by pauldraper** [comment]
Given that #2014, #4862, #17483, and #27707 are all dups, I would think this is still relevant 4 years later.

**Comment by crisbeto** [comment]
We discussed this in the feature triage meeting. We decided to close it, because we can't really validate event names due to custom events.

**Comment by pauldraper** [comment]
@crisbeto what is a "custom event"? Is that like a "custom input"?

**Comment by crisbeto** [comment]
I was referring to this browser API: https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent. It allows for an event with any name to be dispatched from a DOM node.
