### ISSUE TITLE
@ViewChild(MyInjectorToken as any, { static: false }) no longer works with Ivy

### ISSUE THREAD

**Issue by elca-lan** [angular/angular#34267]
# 🐞 bug report

### Affected Package
Ivy Compiler

### Is this a regression?
Yes. This used to work with Angular 8

### Description
To get view children or content children that implement a certain abstract class or interface requires a bit of a workaround - casting the injector token to "any" - but was definitely supported in so far that somebody had to have written the code that deals with the injector token. For details, see the related issues:
* https://github.com/angular/angular/issues/12758
* https://github.com/angular/angular/issues/21152

With a new Angular 9 (9.0.0-rc.5) project, the same mechanism fails in the AOT compillation step with the message: "error TS-991010: @ViewChild predicate cannot be interpreted"

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-viewchildtoken-angular8-4dpwkt?file=src%2Fapp%2Fhello.component.ts

1. Download the Stackblitz sample
2. Upgrade the project to Angular 9 rc5 with `ng update --next=true @angular/cli @angular/core`
3. Build the project in AOT mode

## 🔥 Exception or Error
<pre><code>
error TS-991010: @ViewChild predicate cannot be interpreted
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.5
Node: 10.16.0
OS: win32 x64

Angular: 9.0.0-rc.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.5
@angular-devkit/build-angular      0.900.0-rc.5
@angular-devkit/build-ng-packagr   0.900.0-rc.5
@angular-devkit/build-optimizer    0.900.0-rc.5
@angular-devkit/build-webpack      0.900.0-rc.5
@angular-devkit/core               9.0.0-rc.5
@angular-devkit/schematics         9.0.0-rc.5
@ngtools/webpack                   9.0.0-rc.5
@schematics/angular                9.0.0-rc.5
@schematics/update                 0.900.0-rc.5
ng-packagr                         9.0.0-rc.3
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2
</code></pre>

*Edit*: A fellow developer had some trouble to reproduce the issue, so think it's worth mention that the error only appears when building in AOT mode.

**Comment by alxhub** [comment]
Interesting bug, and thank you for the clear reproduction! This is indeed an issue.

What's going on here is that Angular sees `const ComponentInterfaceToken = new InjectionToken<...>(...)` and realizes that it cannot statically determine the value as it involves the `new` operation. The compiler is trying to verify that the value in question is either a string or a `class` instance as specified by the type of `@ViewChild()`.

This is why you need a cast here - you're going beyond Angular's public API when you pass an `InjectionToken` as the query predicate. The fact that this worked in the runtime is an implementation detail.

**Comment by waterplea** [comment]
Will that be fixed by Ivy stable? I use that a lot, it is very helpful :( My latest usecase — I have directives for Web Audio API. They all extend native AudioNodes and provide themselves as AUDIO_NODE token. I need to be able to query all nodes in the view/content.
