### ISSUE TITLE
CHANGELOG.md missing 9.0.0-rc.5 changes

### ISSUE THREAD

**Issue by vadjs** [angular/angular#34269]
# 📚 Docs or angular.io bug report

### Description
`CHANGELOG.md` files missing 9.0.0-rc.5 changes but 9.0.0-rc.5 version released 2 days ago.

## 🔬 Minimal Reproduction
Open `CHANGELOG.md`, see no 9.0.0-rc.5 changes.

### What's the affected URL?**
https://github.com/angular/angular/blob/master/CHANGELOG.md

### Anything else relevant?
Angular version 9.0.0-rc.5

**Comment by AndrewKushnir** [comment]
Hi @vadjs, thanks for noticing and reporting that. We've updated [CHANGELOG.md](https://github.com/angular/angular/blob/master/CHANGELOG.md#900-rc5-2019-12-04) with v9.0.0-rc.5 release notes (which were only added to the 9.0.x branch during the release).
