### ISSUE TITLE
I hope FormGroup can support it, consume first and then create control

### ISSUE THREAD

**Issue by WuZhenXing** [angular/angular#34263]
Formgroup uses control first. It finds that there is no control that automatically creates null value. Can it support it? It's not convenient to create first and then use. If there is dynamic control

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
