### ISSUE TITLE
elements schema: hand-written schema for Dart / server-side compilation

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#3427]
There are environments (Dart, serer-side compilation) where we can't properly detect properties available on elements and thus we can't report "dangling" properties. We need to hand-write schema for those environments based on HTML specs / Dart APIs etc.

This is important because right now we can't give good error messages to Dart folks. With the new parser #4417 this should be straightforward to implement.

This is also important for security as we need to whitelist which properties are OK to write to.

**Comment by naomiblack** [comment]
removing this from the GT hotlist because they are more concerned with fully typed code, which the new compiler already addresses.

**Comment by pkozlowski-opensource** [comment]
This was solved by d327ac4b434cff8eb5e510c99f8c503940339e4d
