### ISSUE TITLE
Run-time performance regression between Angular 8 and Angular 9

### ISSUE THREAD

**Issue by rkaraivanov** [angular/angular#34271]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?
Yes, the previous version in which this bug was not present was: 
8.2.14

### Description
Run-time performance is regressed between v8.2.14 and the latest release candidate.
Change detection cycles take 1.5x-3x times as much for the same workload.

## 🔬 Minimal Reproduction
https://github.com/rkaraivanov/ng-v8-to-v9-performance

1. Clone the repository
2. Install the dependencies for the two applications
3. Run them side by side in production mode
4. Try scrolling horizontally/vertically in both applications and observe the difference in FPS between v8 and v9.

## 🔥 Exception or Error
None

## 🌍  Your Environment

**Angular Version for v8 appliaction:**
<pre><code>
Angular CLI: 8.3.20
Node: 12.10.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.20
@angular-devkit/build-angular     0.803.20
@angular-devkit/build-optimizer   0.803.20
@angular-devkit/build-webpack     0.803.20
@angular-devkit/core              8.3.20
@angular-devkit/schematics        8.3.20
@angular/cli                      8.3.20
@ngtools/webpack                  8.3.20
@schematics/angular               8.3.20
@schematics/update                0.803.20
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Angular Version for v9 appliaction:**
<pre><code>
Angular CLI: 9.0.0-rc.5
Node: 12.10.0
OS: win32 x64

Angular: 9.0.0-rc.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.5
@angular-devkit/build-angular     0.900.0-rc.5
@angular-devkit/build-optimizer   0.900.0-rc.5
@angular-devkit/build-webpack     0.900.0-rc.5
@angular-devkit/core              9.0.0-rc.5
@angular-devkit/schematics        9.0.0-rc.5
@ngtools/webpack                  9.0.0-rc.5
@schematics/angular               9.0.0-rc.5
@schematics/update                0.900.0-rc.5
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
I'm also attaching a zip with two performance profiles from the applications. You can see the difference in the scroll event timings there.
[scroll_measure.zip](https://github.com/angular/angular/files/3932419/scroll_measure.zip)

**Comment by pkozlowski-opensource** [comment]
Thnx for the report @rkaraivanov - I was able to reproduce and can confirm the issue. Looking into it.

**Comment by IgorMinar** [comment]
This should be now fixed (by #34307) and should be in rc.10
