### ISSUE TITLE
In Ivy, ng-container is preventing content children from being queried

### ISSUE THREAD

**Issue by Shijir** [angular/angular#34289]
# 🐞 bug report

"@angular/core": "9.0.0-rc.5" with Ivy 

### Is this a regression?

Very Likely. 

### Description

Previously, I was able to query content children that were nested inside `ng-container`. For example:

```html
<hello-container>
    <ng-container>
        <hello [name]="'Tom'"></hello>
        <hello [name]="'Jerry'"></hello>
    </ng-container>
</hello-container>
```

```ts
@Component({
  selector: 'hello-container',
  template: `<ng-content></ng-content>`,
})
export class HelloContainerComponent  {
  @ContentChildren(HelloComponent) hellos: QueryList<HelloComponent>;

  ngAfterContentInit() {
    console.log(this.hellos.length);
  }
}
```

This code snippet above would log 2 like here reproduced in Angular 8: https://stackblitz.com/edit/ngfor-ngcontainer-ngif. 

__But in Ivy, it would log 0__ as it's not querying/registering content children if they are nested with `ng-container`.

## How to reproduce

We just need to enable ivy.

Reproduction in Ivy: https://ivy.ng-run.com/edit/83UoqeeHqo08KIenCTIM

## Expected behavior

Should be able to register content children like it does in Angular 8.

## Versions

* Angular: 9.0.0-rc.5

## Additional notes

I tried it with `ngProjectAs` as shown below:

```html
<hello-container>
    <ng-container ngProjectAs="hello">
        <hello [name]="'Tom'"></hello>
        <hello [name]="'Jerry'"></hello>
    </ng-container>
</hello-container>
```
Unfortunately, this didn't help solve the issue either.

**Comment by AndrewKushnir** [comment]
Hi @Shijir, it looks like an Ivy change related to `@ContentChildren` queries, you can [find more information here](https://next.angular.io/guide/ivy-compatibility-examples#content-children-descendants). As a possible fix (that would be compatible with View Engine as well) is to add `{descendants: true}` as a second argument to `@ContentChildren` query, for example:
```
@ContentChildren(HelloComponent, {descendants: true}) hellos: QueryList<HelloComponent>;
```
I will close this ticket, feel free to reopen if adding `descendants` doesn't work as expected.
Thank you.
