### ISSUE TITLE
2.0.0-alpha.32 is listed twice in CHANGELOG.md

### ISSUE THREAD

**Issue by theodorejb** [angular/angular#3428]
The second one looks like a duplicate of 2.0.0-alpha.33 (2015-07-30).

**Comment by gdi2290** [comment]
@rkirov @stevemao do you think the recent update to conventional-changelog caused this?

**Comment by stevemao** [comment]
I don't think so. I regenerated it on my computer and it's not like this. Looks like changelog is run somehow before the release of `2.0.0-alpha.33`

**Comment by mhevery** [comment]
Not sure this is actionable, since we will not remove the duplicate. Closing

**Comment by theodorejb** [comment]
Why not remove the duplicate? It looks like this was fixed for a different release in #3954. Would you accept a pull request?
