### ISSUE TITLE
"products.ts" reference at https://angular.io/start

### ISSUE THREAD

**Issue by abergquist** [angular/angular#34291]
# 📚 Docs or angular.io bug report

### "products.ts" reference at https://angular.io/start

In the following sentence at https://angular.io/start:

The product list component also defines a products property that contains imported data for each product from the products array in products.ts.

I believe "products.ts" needs to be replaced with "product-list.component.ts".

TIA,

Art Bergquist

P.S. Also, in the following text, "browser specific" needs to be replaced with "browser-specific":

  Is this a browser specific issue? If so, please specify the device, browser, and version.

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by ajitsinghkaler** [comment]
@abergquist  the file it is referencing is correct.

@gkalpak, as it is a first-time tutorial, should we show the products.ts file on the page too. As it will be better for understanding.

**Comment by abergquist** [comment]
Correct; if a file belongs in the tutorial, it should be shown on the page.
