### ISSUE TITLE
Pipes: Allow to specify locale

### ISSUE THREAD

**Issue by cghislai** [angular/angular#3429]
I see the code uses the ECMA Intl module to get Number / Date Formatters. At the moment, it seems the hardcoded 'en_US' locale value is passed. We should be able to specify the locale of our application somehow.

Thanks!

**Comment by rdelabarrera90** [comment]
+1

**Comment by meriturva** [comment]
+1

**Comment by meriturva** [comment]
We really need to use DatePipe with locale defined on html lang attribute for example.
How to do that?

**Comment by deeleman** [comment]
+1

**Comment by meriturva** [comment]
any news here? thanks.

**Comment by CarlosAdrianM** [comment]
+1

**Comment by CEikermann** [comment]
+1

**Comment by zoechi** [comment]
There is a nice new GitHub feature to "add reaction"s instead of `+1` posts. Please use this instead :+1:

**Comment by DzmitryShylovich** [comment]
@vicb it's already implemented, isn't it?

**Comment by CarlosAdrianM** [comment]
I think LOCALE_ID is the way to do it, but in the docs it is marked like "experimental": https://angular.io/docs/js/latest/api/core/index/LOCALE_ID-let.html

**Comment by DzmitryShylovich** [comment]
half of the angular is marked as experimental :)

**Comment by pkozlowski-opensource** [comment]
Yep, defining and injecting `LOCALE_ID` is the way to go right now. It is true that this API _is_ marked as experimental right now but this is the best / only solution in place right now. Experimental means that it _might_ change if we've got much better idea but it _doesn't have to_ change.

Closing as implemented.

**Comment by ocombe** [comment]
Hello, a new "locale" parameter will be added to i18n pipes (date, number, ...) with the PR to replace the intl API for angular v5 (see [#10809](https://github.com/angular/angular/issues/10809))
