### ISSUE TITLE
https://angular.io/tutorial/toh-pt1#create-a-hero-class showing class instead of interface

### ISSUE THREAD

**Issue by ajitsinghkaler** [angular/angular#34292]
# 📚 Docs or angular.io bug report

### Description
I resolved issue #21186 in #34022 but currently, in the aio docs, it's still showing class rather than the interface. Is there a problem because I saw in the base dos the path is correct in the code-example tag. I'm attaching screenshots for reference.

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
https://angular.io/tutorial/toh-pt1#create-a-hero-class

### What's the affected URL?**
 https://angular.io/...

### Reproduction Steps**
Go to https://angular.io/tutorial/toh-pt1#create-a-hero-class

### Expected vs Actual Behavior**

Expected the code-example should show interface

Actual it is still show class.

## 📷Screenshot

![Angular - The Hero Editor](https://user-images.githubusercontent.com/39260684/70372532-37823600-1906-11ea-8bb5-b982e95c1d02.png)
![Editing angular toh-pt1 md at master · angular angular](https://user-images.githubusercontent.com/39260684/70372534-381acc80-1906-11ea-8917-49ce0910036d.png)
![Desktop screenshot (18)](https://user-images.githubusercontent.com/39260684/70372536-394bf980-1906-11ea-9ddf-250271298d49.png)
## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by ajitsinghkaler** [comment]
@petebacondarwin I cannot understand what exactly is the problem.

**Comment by ericmartinezr** [comment]
https://next.angular.io/tutorial/toh-pt1#create-a-hero-class

**Comment by ajitsinghkaler** [comment]
Thanks @ericmartinezr
