### ISSUE TITLE
https://angular.io/ is breakdown

### ISSUE THREAD

**Issue by fadymissiha** [angular/angular#34313]
Hi,
https://angular.io/ is breakdown!

**Comment by gkalpak** [comment]
I'm sorry but we don't understand the problem you are reporting.
I assume you might have meant that angular.io is down, but it works fine for me, so it must be something on your end (network/proxy issue?).

If the problem persists, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and provide a clear explanation of what problem you are experiencing (including expected vs actual behavior).

**Comment by fadymissiha** [comment]
Yes, you are right. thank you.
