### ISSUE TITLE
Angular dynamic form cannot find control with unspecified name attribute

### ISSUE THREAD

**Issue by ganeshmandlik** [angular/angular#34315]
Hello Team,

I am creating Angular Dynamic Forms using FormGroup, however while creating form facing issue like
Hide   Copy Code
Cannot find control with unspecified name attribute
. Please someone help me what is causing an issue regarding this. I am providing github public url for code. Thanks and highly appreciate.

GitHub - ganeshmandlik/DynamicFormsAngular: DynamicFormsAngular[^]

What I have tried:

I tried to generate Form object on ngOnInit(), however id did not work.

**Comment by ajitsinghkaler** [comment]
Can you please provide the actual link not the name of the repo I tried this in search but could not find any thing.

**Comment by ganeshmandlik** [comment]
Thanks for your reply Ajitsingh Ji, currently I just put on hold I will update you once I post the url. Thanks!

**Comment by AndrewKushnir** [comment]
Hi @ganeshmandlik, thanks for reporting the issue. However it's not actionable without a repro. I will close this ticket for now. Feel free to create a new one once there is a repro available. Thank you.
