### ISSUE TITLE
Return Observable from catchError in async validator example

### ISSUE THREAD

**Issue by gflohr** [angular/angular#34323]
# 📚 Docs or angular.io bug report

### Description

The `UniqueAlterEgoValidator` must return this:

```typescript
    return this.heroesService.isAlterEgoTaken(ctrl.value).pipe(
      map(isTaken => (isTaken ? { uniqueAlterEgo: true } : null)),
      catchError(() => of(null))
    );
```

Currently, the `catchError` function just returns `null`, not `of(null)`, which may throw an error:

```
TypeError: You provided 'null' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
```

### What's the affected URL?**
https://angular.io/guide/form-validation#implementing-custom-async-validator

**Comment by kapunahelewong** [comment]
Thank you for spotting this, @gflohr and thanks to @sonukapoor for opening the PR!
