### ISSUE TITLE
src/app/product-list/product-alerts.component.ts

### ISSUE THREAD

**Issue by doberman7** [angular/angular#34320]
# 📚 Docs or angular.io bug report

### Description

On the tutorial _Getting Started with Angular: Your First App_
This path 
src/app/product-list/product-alerts.component.ts
Doesnt exist

The functional one is
src/app/product-alerts/product-alerts.component.ts

### What's the affected URL?**
https://angular.io/start#getting-started-with-angular-your-first-app

<img width="1179" alt="Screen Shot 2019-12-09 at 7 10 49 PM" src="https://user-images.githubusercontent.com/23062808/70486712-6cce8580-1ab8-11ea-8f2c-4c81cff514b9.png">

**Comment by MrJithil** [comment]
@doberman7 Could you please elaborate the issue? I could see `src\app\product-list\product-list.component.ts` file exist in the `aio\content\examples\getting-started\src\app\product-list\product-list.component.ts`.

**Comment by gkalpak** [comment]
@MrJithil, as mentioned by OP, the incorrect path is _"src/app/**product-list**/product-alerts.component.ts"_, which should be _"src/app/**product-alerts**/product-alerts.component.ts"_.

(So, both `product-list/product-list.component.ts` and `product-alerts/product-alerts.component.ts` exist, but not ``product-list/product-alerts.component.ts`.)

**Comment by doberman7** [comment]
Why is this issue closed?

The problem still there, and as a new developer, this was real issue ad the start so I think it would really cool to solved in order that the Angular framework would be more used by the community

**Comment by doberman7** [comment]
<img width="868" alt="Screen Shot 2019-12-11 at 3 36 27 PM" src="https://user-images.githubusercontent.com/23062808/70662564-1aae7100-1c2c-11ea-9595-bb4ead9fb0ab.png">

**Comment by gkalpak** [comment]
@doberman7, this has been fixed in master and on the 9.0.x branch.
Since 9.x is still in RC, it doesn't get deployed to https://angular.io, which contains the currently stable version (currently 8.x).

You can see the changes live in our "staging" environment: https://next.angular.io/start#input

If someone wants to backport this to the 8.2.x branch, we could get it into angular.io befoe 9.0.0 is released.
