### ISSUE TITLE
angular control.registerOnChange is not a function example link given

### ISSUE THREAD

**Issue by gkamle** [angular/angular#34330]
I am facing issue while loading form dynamically. Example link given: https://stackblitz.com/edit/angular-ubmufe

click on clickone button and then click on clicktwo button, you will find error in console.

if you click on clickone button refresh app and click on clicktwo button then it is working.

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
