### ISSUE TITLE
when scroll is too fast, white screen appear

### ISSUE THREAD

**Issue by scm-kaungeainsan** [angular/angular#34338]
I've been testing this on chrome. During long scrolls data start disappearing from the screen and come back in a few seconds. Is there any solution for this issue.

thanks,

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
