### ISSUE TITLE
Pass configuration data to services in a lazy loaded module

### ISSUE THREAD

**Issue by kristofdegrave** [angular/angular#34351]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/core or @angular/router

### Description
I have an angular Application and a separate library which contains a feature. This feature is Lazy Loaded.

In that feature I have a service which needs some configuration that is environment dependent. So this information is present in the `environment.ts` files of the application.

Now I'm looking for a way to pass this environment information to my lazy loaded feature library. These services should only be accessible inside this module or its decedents.

### Describe the solution you'd like
I was thinking about a similar solution as the forRoot or the forChild methods that currently exists.
```
@NgModule({
   imports: [
      RouterModule.forRoot([{
         path: 'feature',
         loadChildren: () => import('path/to/feature').then(module => module.FeatureModule.forChild(environment.whateverConfigSetting))
       }])
   ]
})
export class AppModule {}
```

### Describe alternatives you've considered

An alternative solution I currently use is that I have created an addition library with a module that implements a forRoot method. And the module.forRoot() of this library is added to the imports. of the AppModule. Disadvantage of this is that the services is now exposes to the whole application.

An other alternative solution could be to inject a AppSettings service into the service living in the feature library and fetch the environment settings of this service. Disadvantage of this solution is that for every feature library I additionally add I have a tight coupling to that service.

**Comment by mlc-mlapis** [comment]
@kristofdegrave You can use dynamic `import(...)` of a lazily-loaded module and during instantiating that module, you can pass an injector, which you can modify before (add new tokens, ...), so you have those injections available in constructors of any part of such a lazily-loaded module.

**Comment by kristofdegrave** [comment]
Can you please provide a little example of that, I don't really get what you mean.

**Comment by mlc-mlapis** [comment]
@kristofdegrave Principally like this: https://github.com/angular/angular/issues/31886#issuecomment-517704935

**Comment by kristofdegrave** [comment]
@mlc-mlapis I found that issue before I filed this one. But that thread focuses on loading modules outside the router, it mimics the behavior of what the router does with the advantage you can also inject providers.

What I am looking for is a solution with the router. I just want a decoupling between my feature libs and my Applications, but those feature libs need to run inside a context of an application, and that context needs to deliver some configuration to my feature libraries.

**Comment by mlc-mlapis** [comment]
@kristofdegrave OK, using only the router way is a problem. Theoretically, you can nest the one into the other, but it's a question if it's not too complicated.

**Comment by kristofdegrave** [comment]
I think I found a possible solution on how to handle this.
I have seen that the `loadModuleFactory` (which handles the `loadChildren`) in the router accepts an instance of thar `NgModuleFactory`. **https://github.com/angular/angular/blob/1e9eeafa9e3fbfad5e94d697b8079cf649db626e/packages/router/src/router_config_loader.ts#L47-L59**

With that in my mind I implemented an own implementation of the `NgModuleFactory` which accepts a ModuleWithProviders. https://gist.github.com/kristofdegrave/518622c22c6bd6a65382d9365e965d84

Using this implementation I can do the following in my routes:
```
RouterModule.forRoot([{
   path: 'feature',
   loadChildren: () =>
      import('path/to/feature').then(module => 
         new LazyNgModuleWithProvidersFactory(
            module.Feature.forRoot('Feature base url')))
}])
```

Some feedback on the solution would be nice, since my knowledge about the injector and compiler is limited, I don't know if I'm doing things I shouldn't.

**Comment by Wilt** [comment]
> "Some feedback on the solution would be nice"

Would also be nice for others ending up here looking for a similar solution. I have parent modules lazy loading some feature modules and depending on the parent some things need to be configured differently, would be great to see some feedback on what @kristofdegrave proposed here.

**Comment by kristofdegrave** [comment]
@Wilt No feedback received, but the proposed solution with the `LazyNgModuleWithProvidersFactory` is something that works.

**Comment by the-ult** [comment]
This seems like something a lot of projects could use. Using Configs/InjectionTokens for lazy loaded routes. So you can keep your feature-modules/libs clean.

But somehow it is hard to find any clean solutions. And it is still possible with the lazy routes itsself => So it makes me wonder.. what are we doing wrong 🤔  🙃   And what would be a proper/better way to solve this?

Instead of:
```ts
TasksModule.forRoot({
      config: {
        domains: MyDomains,
      },
    }),
```
doing something like this would be great.
```ts
[
  {
     path: 'tasks',
     loadChildren: async () => (await import('@my-lib/tasks')).TasksModule.config(
        config: {
        domains: MyDomains,
      },
     ),
  }
]
```

Using a 'global' `ConfigService` is a solution. But in that case, the `ConfigService` has to know to much about feature modules. And feature modules would need to inject the same ConfigService (High Coupling)
So it doesn't feel like a proper solution.

**Comment by mlc-mlapis** [comment]
@the-ult Did you mean using `forRoot`?
```
[
  {
     path: 'tasks',
     loadChildren: async () => (await import('@my-lib/tasks')).TasksModule.forRoot(
        config: {
          domains: MyDomains,
        },
     ),
  }
]
```

**Comment by the-ult** [comment]
Yes. using `forRoot` or in this example I renamed it to `config` 
Since `forRoot()` is/was more the convention for inside `imports[]`. So I figured, this might be more appropriate 😇 

But the above example does not work like that.. does it? e.g.
using the same `forRoot()` syntax, but within the `loadChilderen`? Or can you?

**Comment by mlc-mlapis** [comment]
@the-ult Never tried. It's normally a static method declared inside that module. If you tried it and it doesn't work, it would mean that it's not invoked in the case of `loadChildren`, but it's invoked and processed correctly during imports (because the compiler understands what it means).

**Comment by the-ult** [comment]
Followed this article. Which seems to be working 👍 
https://volosoft.com/blog/how-to-configure-angular-modules-loaded-by-the-router

But since it is so difficult to get it done and there is hardly anything found about providing config to a lazy loaded feature module... I'm still wondering what would be a better way to provide `config` to a feature module 🤔 

@mgechev, or @IgorMinar do you have any solutions/ideas/insights?

**Comment by mlc-mlapis** [comment]
@the-ult That example should be improved a bit to work also in AOT mode and not only in JIT because this code `const factory = compiler.compileModuleSync(this.moduleType);`.

**Comment by mgechev** [comment]
I'll close this issue since it didn't collect a sufficient number of votes and doesn't align with an existing project on the roadmap.
