### ISSUE TITLE
How do I figure it out this Angular error?

### ISSUE THREAD

**Issue by irimescu-maria** [angular/angular#34365]
When I run ng serve I receive this error.
[Here is my error](https://firebasestorage.googleapis.com/v0/b/beep-7adbf.appspot.com/o/Screenshot%202019-12-12%20at%2009.56.57.png?alt=media&token=5fd6116d-4744-48af-b104-af0fa7a3d312)

[Those are my dependencies](https://firebasestorage.googleapis.com/v0/b/beep-7adbf.appspot.com/o/Screenshot%202019-12-12%20at%2009.56.40.png?alt=media&token=118d4c57-2092-44c5-aab2-1c551ed287b7)

**Comment by Dj-jom2x** [comment]
you had ad blocker maybe

**Comment by irimescu-maria** [comment]
> you had ad blocker maybe

I disabled the Grammarly extension. I have only one error after that. You know it's weard because this is the first time when I receive this error.

<img width="578" alt="Screenshot 2019-12-12 at 10 38 34" src="https://user-images.githubusercontent.com/37383339/70696090-ab885980-1ccb-11ea-895d-92fa9f2c1e20.png">

**Comment by spock123** [comment]
@irimescu-maria did you set a Content-Security-Policy meta tag in your index.html?

**Comment by munro-art** [comment]
Not sure of the root cause but a quick fix is .... delete your node_modules and package-lock.json and then re install (npm i or yarn install).  Should clear the error.

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
