### ISSUE TITLE
Weird priority ordering on route data/resolve

### ISSUE THREAD

**Issue by hoffmale** [angular/angular#34361]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router.

### Is this a regression?

 I don't know.

### Description

 There seems to be a weird edge case in the handling of static and dynamic data of routes in the case of nested routes.

Routes offer the properties `data` and `resolve` in order to attach some data, statically and dynamically respectively.

For most nested route scenarios, these work as expected: `resolve` supersedes `data`, and the parents `ActivatedRoute` contains the data set on the parents route, and the childs `ActivatedRoute` contains the data set on its respective route.

But there is one case where this breaks down:

- The parent route loads some dynamic data via `resolve`
- The child route loads some static data with the same key via `data`
- The child routes relative path is `''` (i.e. empty).

```
const routes: Route[] = [
    // ...
    { path: 'outer', component: OuterComponent, resolve: { breadcrumb: OuterResolverService }, children: [
        { path: '', pathMatch: 'full', component: InnerComponent, data: { breadcrumb: 'inner' } }
    ] },
];
```

Expected behavior:

- The childs corresponding `ActivatedRoute` contains the static data specified in the route (for the example above: `'inner'`), like any other child route with a different `path`.

Observed behavior:

- The childs corresponding `ActivatedRoute` contains the dynamically resolved data specified in the route of the parent (for the example above: whatever `OuterResolverService.resolve` returned).

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-issue-repro2-tdz3sn

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.20
Node: 12.13.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.20
@angular-devkit/core         8.3.20
@angular-devkit/schematics   8.3.20
@schematics/angular          8.3.20
@schematics/update           0.803.20
rxjs                         6.4.0

</code></pre>

**Anything else relevant?**

Seems browser-independent. Tested on Firefox 71.0 (64bit) and Edge.

**Comment by martinsik** [comment]
I can confirm this is still happening in Angular 13.

Updated stackblitz for Angular 13: https://stackblitz.com/edit/angular-ivy-uvc7mm?file=src%2Fapp%2Fapp.module.ts
