### ISSUE TITLE
Service-Worker: Allow setting userVisibleOnly = false on SwPush

### ISSUE THREAD

**Issue by eladcandroid** [angular/angular#34368]
I want to set the PushSubscription userVisibleOnly option to false, but it can't be passed from outside (on requestSubscription function call)

Here's the specific code line:
https://github.com/angular/angular/blob/ad987021ce5a2a2bc498dcb38a8e64300c461cc9/packages/service-worker/src/push.ts#L158

**Comment by gkalpak** [comment]
I am a little torn on this. First of all, this might not be supported on some browsers (e.g. [according to this article][1] Chrome does not support it, but that might be outdated). And I am not sure we should encourage people to use it (given it can't be used maliciously).

I am not saying I am definitely against it, but I am on the fence.
I am going to leave this open as a feature request and see what others think.

In the meantime, (even if not ideal) it is fairly straight-forward to implement your own `requestSubscription()` method that allows passing `useVisibleOnly: false`.

(OOC, what is your usecase? Why do you need silent push?)

[1]: https://developers.google.com/web/fundamentals/push-notifications/subscribing-a-user

**Comment by eladcandroid** [comment]
@gkalpak Maybe you right.. I thought it should enable to get push notifications on windows when chrome is down...

**Comment by gkalpak** [comment]
Given that the demand for this feature is low and that there are concerns about this being a good idea for `@angular/service-worker` in the first place (see my previous comment), I am going to close this. 
<sub>It is always possible to work around this by implementing your own `requestSubscription()` function.</sub>
