### ISSUE TITLE
https://angular.cn/guide/reactive-forms 中文版这一章节，建议把“alias” 翻译为别名，而不是绰号，因为绰号是贬义词，而别名是现在通用的；

### ISSUE THREAD

**Issue by luoyalin** [angular/angular#34386]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please help us process issues more efficiently by filing an
issue using one of the following templates:

https://github.com/angular/angular/issues/new/choose

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by hsuanxyz** [comment]
Please submit this issue to the [angular/angular-cn](https://github.com/angular/angular-cn) repository
