### ISSUE TITLE
9.0.0-rc.6: ERROR in Failed to resolve styles[0] to a string.

### ISSUE THREAD

**Issue by edward24689** [angular/angular#34389]
# 🐞 bug report

### Affected Package
9.0.0-rc.6

### Description

 When AOT enabled and Ivy enabled, I get the following error: ERROR in Failed to resolve styles[0] to a string.

## 🔬 Minimal Reproduction
<pre><code>
let contentStr = '';
        contentStr = content;
        @Component({
            template: contentStr,
            styles: [css]
        })
        class InsertedComponent {

            customData: any = customData;

            tplRef: any;

            currentTab: any;

            constructor() {

            }
        }
        return InsertedComponent;
</code></pre>

## 🔥 Exception or Error
<pre>
<code>
ERROR in Failed to resolve styles[0] to a string
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect         0.900.0-rc.6
@angular-devkit/build-angular     0.900.0-rc.6
@angular-devkit/build-optimizer   0.900.0-rc.6
@angular-devkit/build-webpack     0.900.0-rc.6
@angular-devkit/core              9.0.0-rc.6
@angular-devkit/schematics        9.0.0-rc.6
@angular/cdk                      8.2.3
@angular/material                 8.2.3
@ngtools/webpack                  9.0.0-rc.6
@schematics/angular               9.0.0-rc.6
@schematics/update                0.900.0-rc.6
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment]
Hi @edward24689, I've just tried to compile a test component, similar to the one you described:
```
  const css = 'h2 { font-size: 10px; }';
  @Component({
    selector: 'test',
    template: '...',
    styles: [css]
  })
  export class TestCmp {}
```
and Ivy Compiler resolved `css` correctly.

Could you please provide a bit more information on how `css` is defined in your case (it's missing in your example code), so we can try to reproduce the problem?

Thank you.

**Comment by edward24689** [comment]
I try to create function return component
<pre><code>
createDynamicComponent(content: string, css: string = '') {
        @Component({
            template: content,
            styles: [css]
        })
        class InsertedComponent {
            constructor() {
            }
        }

        return InsertedComponent;
}
</code></pre>

**Comment by Chen-wendy** [comment]
Are you trying to compile the template and component in the browser?

**Comment by AndrewKushnir** [comment]
Thanks for additional information @edward24689. It looks like this is a part of the expected changes in Ivy (see [Ivy Compatibility guide](https://next.angular.io/guide/ivy-compatibility)):
```
Foreign functions or foreign constants in decorator metadata aren't statically resolvable
(previously, you could import a constant or function from another compilation unit, like a library,
and use that constant/function in your @NgModule definition).
```
The solution is to refactor the code to make sure decorator metadata is statically resolvable and use Angular APIs to pass dynamic content to a component (like Content Projection and/or Dependency Injection).
