### ISSUE TITLE
Update Tour of Heroes completed project ZIP file for v9

### ISSUE THREAD

**Issue by vikerman** [angular/angular#34382]
The link in completed example to download  - https://next.angular.io/generated/zips/toh-pt6/toh-pt6.zip  in next.angular.io still points to the 8.0 version.

This needs to be updated to the 9.x versions.

**Comment by gkalpak** [comment]
I am working on that as part of [FW-1609][1].
It will be fixed by #34374 (still WIP).

[1]: https://angular-team.atlassian.net/browse/FW-1609
