### ISSUE TITLE
rxjs Observable or Subject instead EventEmitter

### ISSUE THREAD

**Issue by klemenoslaj** [angular/angular#34394]
# 📚 Docs or angular.io bug report

### Description

In the times of Angular v2, there was a semi-official [statement](https://www.bennadel.com/blog/3038-eventemitter-is-an-rxjs-observable-stream-in-angular-2-beta-6.htm#comments_47949) not to use rxjs `Observable` or `Subject` directly instead of `EventEmitter` because the implementation of `EventEmitter` might change in the future.

I am wondering if this is still valid today, given that rxjs is a first-class citizen of Angular and any serious project based on Angular?

I found myself always wishing to use observable or piped observable directly in my reactive component instead of going out of my way to call `EventEmitter.emit`.

If the statement is still valid, could it perhaps be valuable to be documented?

**Comment by ajitsinghkaler** [comment]
@kapunahelewong can I take this.

**Comment by kapunahelewong** [comment]
Thank you, @ajitsinghkaler! Yes, that would be great. I've just confirmed that it is indeed still applicable. :)

**Comment by didii** [comment]
Is this issue completed? On https://angular.io/api/core/EventEmitter I can see

> Extends RxJS Subject for Angular by adding the emit() method.

Which to me is an indication that it is documented properly.

**Comment by klemenoslaj** [comment]
> Is this issue completed? On https://angular.io/api/core/EventEmitter I can see
> 
> > Extends RxJS Subject for Angular by adding the emit() method.
> 
> Which to me is an indication that it is documented properly.

That was not the point of this issue. The `EventEmitter` was always extending the `Subject`. That is clear. However there was a [statement](https://www.bennadel.com/blog/3038-eventemitter-is-an-rxjs-observable-stream-in-angular-2-beta-6.htm#comments_47949) not to count on it to remain a `Subject` forever since it's internal implementation could change.

I asked if that is still valid or can we count on `EventEmitter` being a subject and therefore we can use observables as `@Output`.

> Do NOT count on EventEmitter continuing to be an Observable!
>
> Do NOT count on those Observable operators being there in the future!
>
>These will be deprecated soon and probably removed before release.
>
>Use EventEmitter only for event binding between a child and parent component. Do not subscribe >to it. Do not call any of those methods. Only call `eve.emit()`

**Comment by DaemonExMachina** [comment]
Is there an official stance on this yet? I'd definitely like some documentation to point people to when they get all confused about me doing this. In particular, we're talking about for example replacing this:
```ts
class Component implements OnInit {
  @Output() entityIdChange = new EventEmitter<number>();
  // ...
  ngOnInit() {
    this.entityFacade.entityId$
      .pipe(takeUntil(this.stop$))
      .subscribe(entityId => {
        this.entityIdChange.emit(entityId);
      });
  }
}
```
with this:
```ts
class Component {
  @Output() entityIdChange = this.entityFacade.entityId$;
}
```
I feel safe in doing this anyway in the meantime, despite the lack of official word, because extracting Angular's dependency on RxJS at this point seems _literally_ impossible. I don't even foresee you bringing in a replacement implementation for the EventEmitter (one that _doesn't_ extend Subject or Observable). It also helps that this is a pattern I only use in a couple of places (because it's so rarely genuinely _needed_), and so if you ever _do_ change the implementation of EventEmitter or OutputDecorator in a way that breaks this it will be easy enough to strip out of our codebase. But it would be nice to have something in the docs to back me up on that (and reassure me that it won't break!).

**Comment by mlc-mlapis** [comment]
@DaemonExMachina Hmm, I don't have any concrete link. Still, as I remember, the official stance is that `@Output()` and its functionality are parts of the stable public API that will be compatible with future changes. Any custom replacement can work fine at that moment. It won't be guaranteed the same with future changes, and it would be the developer side's responsibility to migrate such custom code.

**Comment by klemenoslaj** [comment]
@DaemonExMachina Well that is the point of this issue, to document it finally and strictly.

Right now, even your statement can be easily turned around: 

> Still, as I remember, the official stance is that `@Output()` and its functionality are parts of the stable public API that will be compatible with future changes

`EventEmitter` is part of public API and because it extends `Subject`, it inherits all it's public methods (like `next`, `subscribe`, etc.). Those that aren't underscored or private in TypeScript I could understand of being part of public api of `EventEmitter` and am free to use. So changing `EventEmitter` from `Subject` to whatever else indeed is a breaking change of public api.

And honestly, that is exactly how I perceive it personally if I look at the code only and don't mind what someone said somewhere.

If Angular would really like to protect itself it should be explicit and completely abstract the inner implementation. Use subject internally in custom `EventEmitter` class and expose only the `emit` and `subscribe` functions.

**Comment by Airblader** [comment]
AFAIK public API is not defined by public or non-underscored methods, but rather by what ends up in the API docs. You can see there, https://angular.io/api/core/EventEmitter, that only emit and subscribe are considered public API at the moment.

**Comment by klemenoslaj** [comment]
> AFAIK public API is not defined by public or non-underscored methods, but rather by what ends up in the API docs. You can see there, https://angular.io/api/core/EventEmitter, that only emit and subscribe are considered public API at the moment.

Yes, I agree :+1: I just wanted to point out how easily it can be misunderstood if not explicitly said otherwise.

The issue is as well IDE will offer you autocompletion no matter what is written in the docs. I am pretty sure people don't double check each method call with docs.

**Comment by mlc-mlapis** [comment]
@klemenoslaj I understand, no problem. 😄 

> these places are easily traceable so I am fine with the risk

But still, would you be able to suggest the formulation that could be added to the docs? I mean the one, that wouldn't sound duplicitous in comparison with the definition of what the public API is already saying?

**Comment by DaemonExMachina** [comment]
It's not so much the EventEmitter's public API that's in question here. The question is whether we're strictly allowed to assign plain Observables to class members that are attached to `@Output` attributes, _instead_ of EventEmitters. To add an explicit type annotation to my earlier snippet:
```ts
class Component {
  @Output() entityIdChange: Observable<number> = this.entityFacade.entityId$;
}
```

The place to put such a statement might be somewhere like the [docs on communication between components](https://angular.io/guide/inputs-outputs#output), and might be an "alert" box of some sort that says something like, "We use EventEmitters in these examples because they provide the `emit` method, making it easy to emit a value from anywhere in the component's code or template. But if the only values to be emitted are all coming from a single Observable, it may make more sense to simply assign that Observable directly to the `@Output` field. This is possible, and works as you would expect." Maybe with a StackBlitz example showing that it does indeed work, including that it is unsubscribed on teardown.

**Comment by klemenoslaj** [comment]
@DaemonExMachina to me it is a question of the public API of EventEmitter because it feels like that the Subject was exposed by accident and people use it, even tho Angular is not committed to supporting it. If EventEmitter would not have a public API of Subject (as in, not extending it) no one would be using it (for better or worse).

Don't get me wrong, I use Observables as Output all over the place and would love to continue to do so. I don't like writing useless wrappers because the framework is in my way. I am just trying to see if Angular intends to support that and if not, there should be a statement in docs to **not** use anything but EventEmitter.

 ---

@mlc-mlapis if Angular doesn't want anyone to use Observable as an output, possibly a warning note next to the following line should be added:

> Extends RxJS Subject for Angular by adding the emit() method.

Something like:

> NOTE: Only use the `EventEmitter` as Output, not the observable. We do not guarantee `EventEmitter` will extend `Subject` in the future.

**Comment by mlc-mlapis** [comment]
@DaemonExMachina @klemenoslaj I think that you are right both of you.

I also think that there are no concrete plans to change anything on the `@Output()` interface, so that's why that general position and recommendation to use only the current public API because it is on the safer side.

**Comment by atscott** [comment]
Discussed with @jelbourn and we think this isn't something that needs official documentation or guidance. There are myriad of ways to _not_ do something and we shouldn't attempt to document them. Our docs give guidance on the provided APIs, not a list of unsupported use-cases.

As far as the question of using something other than `EventEmitter` goes, as long as you follow the interface you're more or less safe. It's just outside the official guidance and will not have official support. That said, it's highly unlikely to change and even if it did, you'd know at compile-time so it's more or less safe, relatively speaking.
