### ISSUE TITLE
Email validation regex doesn't support a dot in the local-part

### ISSUE THREAD

**Issue by atul-falle** [angular/angular#34390]
local-part email address can contain dot( . )  character inside qouetes( ' )
but currently only one dot( . )  character is alowed,
whereas email address can contain multiple dot( . ) operators inside qoutes ( ' )
Ref: https://en.wikipedia.org/wiki/Email_address

**Comment by ajitsinghkaler** [comment]
@AndrewKushnir  can I take this

**Comment by jelbourn** [comment]
@ajitsinghkaler you could probably take this, but it's a breaking change so it wouldn't be able to land until we're on the train for v12.

**Comment by dylhunn** [comment]
We're unlikely to ever change the email validator -- it's copied from the WHATWG regex, which is stricter than the RFC standard. If it doesn't work for you use case, you should use `Validatrs.Pattern` with a custom regex.
