### ISSUE TITLE
npm run build:ssr doesn't work

### ISSUE THREAD

**Issue by irimescu-maria** [angular/angular#34392]
Hi! I try to run npm run build:ssr but I won't work
![This is what I receive when I run npm run build:ssr](https://user-images.githubusercontent.com/37383339/70801052-77d62e00-1db6-11ea-8f88-b37ba832820b.png)

**Comment by BrsJsk** [comment]
What does npm run build:ssr even do?
Have you tried npm install?

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
