### ISSUE TITLE
docs: Add missing tests for comparing observables

### ISSUE THREAD

**Issue by sonukapoor** [angular/angular#34398]
# 📚 Docs or angular.io bug report

### Description

The examples used in the [comparing-observables](https://github.com/angular/angular/blob/master/aio/content/guide/comparing-observables.md) guide have no tests ensuring they are valid. Work can start after https://github.com/angular/angular/pull/34327 has been merged. 

### What's the affected URL?**
https://angular.io/guide/comparing-observables

**Comment by sonukapoor** [comment]
I will be working on this as soon as the other PR is in place.

**Comment by sonukapoor** [comment]
I will be working on this as soon as the other PR is in place.

**Comment by kapunahelewong** [comment]
This is wonderful! 🎉Thank you so much, @sonukapoor! If you need anything while working on the PR, feel free to tag me.

**Comment by gkalpak** [comment]
I moved this to `comp: docs-infra`, because this is about adding tests for the examples (and the necessary infrastructure changes to accomodate that).

**Comment by gkalpak** [comment]
This has been addressed in #34537.
