### ISSUE TITLE
Ivy: Remove entryComponents property from @NgModule decorator in @angular/core migrations

### ISSUE THREAD

**Issue by blove** [angular/angular#34399]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/core

The relevant migrations are currently located at:
https://github.com/angular/angular/tree/master/packages/core/schematics/migrations

### Description
Updating to Angular version 9 performs several post-install migrations using schematics. These are incredible, and very much appreciated. ❤️

This feature request is to add an additional migration when updating to Angular v9 using the `ng update` command to remove the `entryComponents` property in all `@NgModule()` decorators since the code is unnecessary after updating to Angular version 9 with Ivy.

### Describe the solution you'd like
Remove `entryComponents` property in `@NgModule()` decorators using schematics.

### Describe alternatives you've considered
Alternative include:

1. Manually remove `entryComponents` after updating.
2. Leave the `entryComponents` after updating since it does not cause an errors or side effects.
3. Create a schematic separate from the @angular/core module to perform the migration for those that desire this functionality.

**Comment by reaction1989** [comment]
I removed all entryComponents from the NgModules. But i ran into issues after this. It seems that it is still needed for Material Dialogs. This probably needs some clarification in the update docs on update.angular.io

**Comment by elvisbegovic** [comment]
@reaction1989 Maybe in your project IVY is intentionally disabled in `angularCompilerOptions` ? [entryComponents](https://angular.io/guide/deprecations#entryComponents) is no longer required with IVY only. Otherwise, maybe you can repro ?

**Comment by elvisbegovic** [comment]
@reaction1989 Maybe in your project IVY is intentionally disabled in angularCompilerOptions ? AFAIK entryComponents is no longer required with IVY only. Otherwise, maybe you can repro ?

**Comment by elvisbegovic** [comment]
@reaction1989 Maybe in your project IVY is intentionally disabled in angularCompilerOptions ? AFAIK [entryComponents ](https://angular.io/guide/deprecations#entryComponents)is no longer required with IVY only. Otherwise, maybe you can repro ?

**Comment by reaction1989** [comment]
@elvisbegovic Now it is working.. I removed node_modules and installed everything from scratch... Strange...

**Comment by salvajavier** [comment]
Why Angular Material's documentation still says you must define entrycomponents on your modules?

**Comment by JoostK** [comment]
Implemented in #44322.
