### ISSUE TITLE
Service Worker - Feedback if SwUpdate.checkForUpdate does not find an update

### ISSUE THREAD

**Issue by KyleAlanDavis** [angular/angular#34397]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/service-worker

### Description
It would be nice if calling SwUpdate.checkForUpdate() had some kind of feedback from the function if there isn't an update available.

### Describe the solution you'd like
Ideally checkForUpdate would return a Promise boolean rather than Promise void, where the boolean is true if there is an update and false if there is no update.

### Describe alternatives you've considered
I have not thought of any alternatives.

**Comment by gkalpak** [comment]
What is your usecase, @KyleAlanDavis? Why do you need to get that info from `checkForUpdate()`?
(Available versions are emitted on [SwUpdate#available][1].)

##
BTW, you could implement this yourself by keeping track of whether `SwUpdate#available` has emitted a value before the `checkForUpdate()` promise resolves.

[1]: https://angular.io/api/service-worker/SwUpdate#available

**Comment by BobDankert** [comment]
It seems this would be useful if implementing a "Check for Updates" button/action in a software. Typically I am used to clicking "Check for updates" in a software and getting a message back that either there are updates available, or there are no updates available. It would seem there is no feedback currently if there are no updates available.

**Comment by gcerquant** [comment]
I would like to **show to the user that a more recent version is published**, even if the update is not available to use (might still be downloading).

## Why?
In case of a large number of big assets, it takes a while to update.
The user might leave before finishing updating.

It's frustrating when you have fixed a bug, and your user test again, not knowing that even though they reloaded in their browser, they still have the previous version.

## Solution
➡️ like suggested by @KyleAlanDavis and @BobDankert , I would like that `checkForUpdate` returns a Promise boolean.

## Alternative
An alternative would be to get an observable event when we start downloading the update.
(My understanding is that `available: Observable<UpdateAvailableEvent>` only triggers when the update is ready for install by `window.location.reload();`)

**Comment by romanovma** [comment]
I have the same use case - when a user opens a home page I want to show a loading spinner meanwhile checking if there are any updates. 

```
if checkForUpdate resolves to true:
    wait several seconds for `available` to be emitted
    if `available` is emitted within these seconds:
        update
    else:
        show cached version
else:
    show cached version
```

**Comment by gkalpak** [comment]
@romanovma: Just in case you've missed https://github.com/angular/angular/issues/34397#issuecomment-565709684, `SwUpdate#available` will have emitted before the promise returned by `SwUpdate#checkForUpdate()` resolves.

**Comment by Odonno** [comment]
@gkalpak WTF ?! I don't want to wait a huge amount of time to get notified that an update is available...  The `setupUpdate` is taking several seconds before completion so your idea is non-sense for a critical update scenario.

The simplest solution would be to send the `available$` just when we know a new version is available. I don't know why it isn't the case...

**Comment by gkalpak** [comment]
I am sorry that you don't like my "idea", @Odonno :grin:

Technically, there is no update available by the SW until it has successfully downloaded the necessary files. (For example, the server may go offline before the SW is able to download all the JS bundles.) The SW should not advertise an update before it is able to serve it.

In the future, we could consider having more granular reporting, so the SW could emit events for both when an update is available on the server and when the update is ready to be served by the SW. (Although, I am not sure how one would use the info that an update is available on the server.)

For the time being, though, `SwUpdate#available` refers to an update being available to be served by the SW 🤷‍♂️

**Comment by Odonno** [comment]
I see. Well, there must a confusion between "new version available" and "ready for update". In the first case, we could just use the hash difference between the current and the new version. In the last case, we just know that the SW is ready for update.

**Comment by souravs-2pirad** [comment]
I have a similar requirement as @BobDankert  , I need to know if an update is available or not. Any updates/workaround on this issue ?
