### ISSUE TITLE
docs: Add missing tests for cli-builder

### ISSUE THREAD

**Issue by sonukapoor** [angular/angular#34393]
# 📚 Docs or angular.io bug report

### Description

The examples used in the [cli-builder](https://github.com/angular/angular/blob/master/aio/content/guide/cli-builder.md) guide have no tests ensuring they are valid. Work can start after the PR https://github.com/angular/angular/pull/34362 has been merged.

### What's the affected URL?**
https://angular.io/guide/cli-builder

**Comment by sonukapoor** [comment]
I will be working on this as soon as the other PR is in place.

**Comment by kapunahelewong** [comment]
Thank you so much, @sonukapoor. This is great! As I noted in the other issue, please feel free to tag me if you need me at any point in the process.

**Comment by gkalpak** [comment]
FYI: I moved this to `comp: docs-infra`, because this is about adding tests for the examples (and the necessary infrastructure changes to accomodate that).

**Comment by gkalpak** [comment]
This has been addressed in #34362.
