### ISSUE TITLE
Error in Vendor.js 

### ISSUE THREAD

**Issue by Manmohabe** [angular/angular#34408]
After updating to angular 9 from angular 8 i get the following error when i try to build the project. Please see the attached images, I need help. I am a beginner in angular.(Am using Asp.net core 3.1 angular templete)
![error](https://user-images.githubusercontent.com/42378971/70849421-1b930d00-1e8f-11ea-8e68-36454ff7c8a4.PNG)

![Bug](https://user-images.githubusercontent.com/42378971/70849424-2e0d4680-1e8f-11ea-8969-c12479da831a.PNG)

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
