### ISSUE TITLE
valueChanges emits even when the value hasn't changed

### ISSUE THREAD

**Issue by mtaran-google** [angular/angular#34407]
#### Documentation Feedback

https://github.com/angular/angular/blob/403bb6bee341ac12c9bfbd9f910432c2d385886f/packages/forms/src/model.ts#L295-L300 is a lie. In particular, it says valueChanges "emits an event every time the value of the control changes", but in fact when you call `enable()` or `disable()` without passing along `{emitEvent: false}` it will also emit :(

This behavior should either be removed or documented (even if it's documented as being recommended against).

**Affected documentation page:** https://angular.io/api/forms/AbstractControl

**Comment by ajitsinghkaler** [comment]
@kapunahelewong should we document this behaviour

**Comment by indraraj26** [comment]
Hi @mtaran-google , it is working fine for me. 
stackblitz : https://stackblitz.com/edit/angular-lawi8z?file=src%2Fapp%2Fapp.component.html

**Comment by ajitsinghkaler** [comment]
@indraraj26 he's saying that it's working fine but we should put proper documentation on when when valuechanges is triggered

**Comment by indraraj26** [comment]
Okay my bad. btw it is already mentioned in AbstractControl api anyway lets wait for community suggestion.

**Comment by ajitsinghkaler** [comment]
I think then we can close this issue

**Comment by kapunahelewong** [comment]
@mtaran-google, thanks for pointing this out, and thank you @ajitsinghkaler for speaking up. Yes, it would be great to have a PR updating this. Thank you! 🌸
