### ISSUE TITLE
docs: Add missing tests for animations

### ISSUE THREAD

**Issue by sonukapoor** [angular/angular#34416]
# 📚 Docs or angular.io bug report

### Description

The [examples](https://github.com/angular/angular/tree/master/aio/content/examples/animations) used in the [animations](https://angular.io/guide/animations) guide have no tests ensuring they are valid. 

### What's the affected URL?**
https://angular.io/guide/animations

**Comment by gkalpak** [comment]
@sonukapoor, afaict there are [plenty of tests][1] 😕
(Note that we primarily focus on e2e tests for the examples, because that is what is run on CI.)

[1]: https://github.com/angular/angular/tree/f79110c63/aio/content/examples/animations/e2e/src

**Comment by sonukapoor** [comment]
Makes sense. Let’s close this.
