### ISSUE TITLE
ViewportScroller service console logs "Window Scrolling"

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular#34410]
This is the demo.  The demo is not logging anything, but whenever scrolling occurs, the ViewportScroller service logs "Window Scrolling". 

https://stackblitz.com/edit/angular-window-scrolling-console?file=src/app/app.component.ts

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
