### ISSUE TITLE
ERROR in Unsupported binary operator: FirstAssignment

### ISSUE THREAD

**Issue by Anil-Toxy** [angular/angular#34419]
# 🐞 bug report

### Affected Package

 Can't able to figure it out which package 

### Description

 I just want to use the ivy feature but it showing thius. all i cant reproduce repo as its very big and complicated project with many third party libs. 

## 🔬 Minimal Reproduction
It's a large project using different third party libs, so I'm not sure  to reproduce it.

## 🔥 Exception or Error
<pre><code>
ng build --prod
0% compiling
Compiling @syncfusion/ej2-angular-calendars : module as esm5

chunk {0} runtime.b5562b9338a39ab29ca5.js (runtime) 1.46 kB [entry] [rendered]
chunk {1} main.9778927d7336266dd8ff.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills.89463effb1c4035ba369.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} polyfills-es5.bd223b5117033808388a.js (polyfills-es5) 72.6 kB [initial] [rendered]
chunk {4} styles.654016b1e2f66c697ef4.css (styles) 4.84 kB [initial] [rendered]
chunk {scripts} scripts.cfe1f5d5f31479269f83.js (scripts) 463 kB [entry] [rendered]
Date: 2019-12-16T05:41:20.012Z - Hash: 0a36a95d0c47c9174d1c - Time: 26133ms

WARNING in Unknown member type: "[x: string]: string | number | Date | boolean | Predicate | Predicate[] | Function | null;

ERROR in Unsupported binary operator: FirstAssignment

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.0
Node: 10.15.1
OS: win32 x64
Angular: 8.2.3
... cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.0
@angular-devkit/build-angular     0.803.0
@angular-devkit/build-optimizer   0.803.0
@angular-devkit/build-webpack     0.803.0
@angular-devkit/core              8.3.0
@angular-devkit/schematics        8.3.0
@angular/animations               8.2.11
@angular/cli                      8.3.0
@ngtools/webpack                  8.3.0
@schematics/angular               8.3.0
@schematics/update                0.803.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Comment by JoostK** [comment]
Please test with the latest 9.0 preview release (`9.0.0-rc.6` at the moment). This particular error no longer exists.

Since this issue is not otherwise actionable, I will go ahead and close this.
