### ISSUE TITLE
Add missing square brackets

### ISSUE THREAD

**Issue by RabbitHols** [angular/angular#34413]
**Description**
The demo missing the closed square brackets at line 43

**What's the affected URL?****

https://github.com/angular/angular/blob/master/aio/content/examples/animations/src/app/open-close.component.3.ts

**Comment by AndrewKushnir** [comment]
Closing this issue based on https://github.com/angular/angular/pull/34414#issuecomment-741868852 - the mentioned section is removed from docs. Thank you.
