### ISSUE TITLE
Get Started user flow enhancements

### ISSUE THREAD

**Issue by SujitSingh** [angular/angular#34428]
**Suggestion to improve the Get Started user flow -**
1. "Get Started" links should point the user to a page with information regarding the creation of a new project,  such as the [Setup page](https://angular.io/guide/setup-local).
2. After that, we should provide Angular's architecture overview, something like [Architecture Overview](https://angular.io/guide/architecture) in simple terms.
4. Then, introduce the user to [Your First App](https://angular.io/start) as it is. Later ask the user to continue with the [Tour of Heroes App](https://angular.io/tutorial) tutorial to give them a real taste of developing an Angular app.

**Why these suggestions?**
* There is front-end framework war out in the world and every non-Angular developers say that documentations are hard to understand. This gives them one extra reason to move away from Angular.
* Few Front-end devs in my team informed me that they couldn't clearly get things which are required to start with Angular. They mentioned that they had to navigate a few pages to get started. When I tried a fresh start by myself, I too couldn't find things clearly, even though I have been visiting  [Angular.io](https://angular.io/) since 2017.

Above suggestions are from a few devs from my team(freshers and experienced). We will be more than happy to get further suggestions in order to improve the above starter flow even better.

**Comment by ajitsinghkaler** [comment]
@kapunahelewong do you think we should implement these changes

**Comment by kapunahelewong** [comment]
Thank you for taking the time to share your thoughts here, @SujitSingh. I will share this with the Docs Team as we are continually working with these same kinds of thoughts in mind.

@ajitsinghkaler, these are indeed some nice suggestions, but as it encompasses some significant changes, I'd like to make sure @aikidave and @jbogarthyde are in on the conversation.

**Comment by aikidave** [comment]
This is great feedback. Thanks! We (the docs folks) are currently looking into how to make it easier to understand and adopt Angular--your insights are really helpful!

**Comment by aikidave** [comment]
We have made a lot of updates to Angular's Getting Started examples. While there will always be more work to do on this, I am closing this issue.
