### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by forforeach** [angular/angular#3444]
Hi,

There is a small mistake in the documentation of ViewAnnotation Class. The definitions of "templateUrl" and "template" are messed up. They should be switched.

![ng2-doc-mistake](https://cloud.githubusercontent.com/assets/2650168/9021760/e898963a-385c-11e5-82cc-4da3bdab1303.PNG)

Br,
Dima

**Comment by gdi2290** [comment]
can you make a pull request?


how-to
https://github.com/angular/angular/blob/master/CONTRIBUTING.md

where to fix
https://github.com/angular/angular/blob/master/modules/angular2/src/core/annotations_impl/view.ts#L39...L51

**Comment by forforeach** [comment]
@gdi2290 I submitted a pull request. Should I close this issue or you'll handle it?

**Comment by gdi2290** [comment]
in your github PR edit the description and add `closes #3444` that way github will automatically close the issue. Doing so also helps with figuring out more information about the PR

**Comment by forforeach** [comment]
@gdi2290 thanks! My first PR to angular, I'm so excited :smiley:
