### ISSUE TITLE
i18n: No translation found for "<id>" when doing ng build

### ISSUE THREAD

**Issue by xyfer** [angular/angular#34449]
# 🐞 bug report

### Affected Package
@angular/localize, possibly

### Is this a regression?
 Yes, the previous version in which this bug was not present was:
8

### Description

 A clear and concise description of the problem...

Setting up a very simple vanilla Angular 9 application with a single element marked as i18n, adding the new @angular/localize dependency, generating the source messages.xlf translation file, copying the file into a new file for a different language, providing the translation in the target selector, setting up the angular.json build configuration as per the documentation, running ng build --configuration=fr.

## 🔬 Minimal Reproduction
https://github.com/xyfer/i18n-error

Steps:
<code>
- clone repo
- npm install
- ng build --configuration=fr
</code>

## 🔥 Exception or Error
<pre><code>
Generating localized bundles...
No translation found for "8144297081924293509" (" Hello! ").
No translation found for "8144297081924293509" (" Hello! ").

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.6
Node: 10.17.0
OS: win32 x64

Angular: 9.0.0-rc.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.6
@angular-devkit/build-angular     0.900.0-rc.6
@angular-devkit/build-optimizer   0.900.0-rc.6
@angular-devkit/build-webpack     0.900.0-rc.6
@angular-devkit/core              9.0.0-rc.6
@angular-devkit/schematics        9.0.0-rc.6
@angular/localize                 9.0.0-rc.0
@ngtools/webpack                  9.0.0-rc.6
@schematics/angular               9.0.0-rc.6
@schematics/update                0.900.0-rc.6
rxjs                              6.5.3
typescript                        3.6.4
webpack

</code></pre>

**Comment by petebacondarwin** [comment]
Note that the `@angular/localize` version is out of sync with the other packages (i.e. rc.0 rather than rc.6).
Updating the packages to the same version solves this problem.

The question is how did you end up with the versions out of sync? Did you use `ng add @angular/localize`?
Or perhaps `ng update` failed to bump the `@angular/localize` version?

**Comment by xyfer** [comment]
> Note that the `@angular/localize` version is out of sync with the other packages (i.e. rc.0 rather than rc.6).
> Updating the packages to the same version solves this problem.
> 
> The question is how did you end up with the versions out of sync? Did you use `ng add @angular/localize`?
> Or perhaps `ng update` failed to bump the `@angular/localize` version?

Good catch, bumping `@angular/localize` to rc.6 corrected the issue! 

You were correct in your guess, using `ng add @angular/localize` only installed rc.0, and using `ng update` failed to detect any newer versions of the dependency.

**Comment by petebacondarwin** [comment]
It seems that `@angular/localize@latest` points to `9.0.0-rc.0`. So the trick is (until 9.0.0 is out) is to use `yarn ng add @angular/localize@next`
