### ISSUE TITLE
Consecutive request with same URL is not made

### ISSUE THREAD

**Issue by venkatpselvam1** [angular/angular#34448]
# 🐞 bug report

### Is this a regression?

 I am not sure

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
```
export class AppComponent {
  title = 'test';
  constructor(private http: HttpClient) {
    this.http.get('/repos/javascript-tutorial/en.javascript.info/commits').subscribe((x) => console.log(x));
    this.http.get('/repos/javascript-tutorial/en.javascript.info/commits').subscribe((x) => console.log(x));
    this.http.get('/repos/javascript-tutorial/en.javascript.info/commits').subscribe((x) => console.log(x));
   }
}
```
Note: the issue is only reproduceable in Safari browser
My expectation is the angular will make 3 API calls but it only made one API call and remaining calls are neglected

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.20
Node: 10.16.3
Angular: 8.2.14

</code></pre>

**Anything else relevant?**

**Comment by dannyskoog** [comment]
Sounds like standard (although browser-specific) handling of concurrent requests towards the same resource

**Comment by venkatpselvam1** [comment]
When I have the plain JS it works fine but only with respect to angular http module I am facing the issue.
Works fine. (4 requests are made in safari browser)
```
document.addEventListener('DOMContentLoaded', (event) => {
  console.log('dom loaded');
  fetch('\api');
  fetch('\api');
  fetch('\api');
  fetch('\api');
});
```

**Comment by alxhub** [comment]
Yep, my guess is this is Safari somehow caching, de-duping, or otherwise rate limiting GET requests. Not an Angular issue (comparing another API - `fetch` instead of `XMLHttpRequest` - to a different endpoint on a different origin isn't really relevant).
