### ISSUE TITLE
RouterLink with queryParamsHandling preserve or merge does not work with OnPush change detection

### ISSUE THREAD

**Issue by chrstnbrn** [angular/angular#34442]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?

Not sure.

### Description

Using the routerLink directive with queryParamsHandling preserve or merge in combination with OnPush change detection leads to incorrect links.

I'm trying to use the routerLink directive with queryParamsHandling="preserve" in a component that uses OnPush change detection. However, if I set a query param, the param is not included in the link. The href of the link is not updated when the query param is set, so if I open the link in a new tab the query param is gone.

A workaround for this is to call markForCheck whenever a NavigationEnd event occurs, but I think this use case should be handled by the routerLink directive itself.

## 🔬 Minimal Reproduction

https://stackblitz.com/github/chrstnbrn/angular-routerlink-onpush-repro

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.20
Node: 10.16.2
OS: win32 x64
Angular: 8.2.14
... common, compiler, compiler-cli, core, language-service
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.20
@angular-devkit/build-angular     0.803.20
@angular-devkit/build-optimizer   0.803.20
@angular-devkit/build-webpack     0.803.20
@angular-devkit/core              8.3.20
@angular-devkit/schematics        8.3.20
@angular/cli                      8.3.20
@ngtools/webpack                  8.3.20
@schematics/angular               8.3.20
@schematics/update                0.803.20
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Comment by atscott** [comment]
It appears this behaves as expected. The `OnPush` component is not marked for check when you change your route so the template bindings are not updated when change detection runs. If you wanted to ensure that the query params are reflected in the template's anchor, add something like the following to your `OnPush` component:
```
  constructor(cdr: ChangeDetectorRef, route: ActivatedRoute) {
    route.queryParams.subscribe(() => {
      cdr.markForCheck();
    });
```
 If you still feel there is an issue, please provide further details in a new issue.
