### ISSUE TITLE
Should be run on vDOM's

### ISSUE THREAD

**Issue by isener** [angular/angular#3445]
New version could be as fast as that it on super big projects. 

Also scope works perfect behind it, keep it super simple as if possible.

Thanks

**Comment by S-YOU** [comment]
angular + non-native htmlparser + vdom can't be anything faster in my opinion.

**Comment by mhevery** [comment]
What should be run on vDOMs?

I am going to close this because the issue is vague. Please open up an issue with specific actionable tasks.
