### ISSUE TITLE
Angular ng object is missing in production bundles in developer tools console

### ISSUE THREAD

**Issue by julianobrasil** [angular/angular#34458]
# 🐞 bug report

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8

### Description

In angular version 8  I had access to `window.ng` object in chrome developer tools console either in development build and in production build.

Today I realized that with the 9.0.0-rc.x version (9.0.0-rc.5) I'm not able to access the `ng` object if the app is compiled for production.

**PRODUCTION:**
![image](https://i.stack.imgur.com/li4Dk.gif)

**DEVELOPMENT:**
![image](https://i.stack.imgur.com/pXJZZ.gif)

## 🔬 Minimal Reproduction

 
Just use cli to generate a brand new project, upgrade it to the latest rc version and compile it to production. In the browser console, try to access `ng` object.

## 🔥 Exception or Error

No exceptions are thrown.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.5
@angular-devkit/build-angular      0.900.0-rc.5
@angular-devkit/build-optimizer    0.900.0-rc.5
@angular-devkit/build-webpack      0.900.0-rc.5
@angular-devkit/core               9.0.0-rc.5
@angular-devkit/schematics         9.0.0-rc.5
@angular/cdk                       9.0.0-rc.5
@angular/cli                       9.0.0-rc.5
@angular/flex-layout               8.0.0-beta.27
@angular/material                  9.0.0-rc.5
@angular/material-moment-adapter   9.0.0-rc.5
@ngtools/webpack                   9.0.0-rc.5
@schematics/angular                9.0.0-rc.5
@schematics/update                 0.900.0-rc.5
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2

</code></pre>

**Anything else relevant?**

At first I thought it was a matter of generating `.map` files in production compilation, but it didn't solve the problem.

**Comment by mhevery** [comment]
This is by intention. `window.ng` is hidden behind `ngDevMode` and is only included in developer builds.
