### ISSUE TITLE
[Error] - Ivy + Angular Material

### ISSUE THREAD

**Issue by BrayanVG** [angular/angular#34452]
#33784 🐞 bug report

### Affected Package

 The issue is caused by package:
@angular/material@9.0.0-rc.5
                             

### Is this a regression?

 Yes, the previous version in which this bug was not present was: the version of Angular 9 rc.3 and Angular Material rc.4 there were no such problems

### Description

I was in the Angular version rc.3 and updated to Angular 9 rc.6 (this error does not occur in the version I was), once I finished updating delete the node_modules and put the postinstall script that is recommended in the Angular Next documentation, I reinstalled the packages (npm install), I compile them well with the ngcc but when I went to run the ng serve I get three errors in the Angular Material library.

https://next.angular.io/guide/ivy#speeding-up-ngcc-compilation

## 🔥 Exception or Error
<pre><code>

> Executing task: ng serve codiDito --port=4041 <

chunk {main} main.js, main.js.map (main) 2 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 676 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 12.3 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 3.47 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 340 kB [initial] [rendered]
Date: 2019-12-17T17:48:13.394Z - Hash: 48a43c79df4c88acf112 - Time: 19794ms

ERROR in node_modules/@angular/material/core/common-behaviors/common-module.d.ts:8:10 - error TS2305: Module '"D:/Proyectos/Angular8/codiDito/node_modules/@angular/cdk/a11y"' has no exported member 'HighContrastModeDetector'.

8 import { HighContrastModeDetector } from '@angular/cdk/a11y';
           ~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@angular/material/snack-bar/snack-bar-container.d.ts:9:78 - error TS2305: Module '"D:/Proyectos/Angular8/codiDito/node_modules/@angular/cdk/portal"' has no exported member 'DomPortal'.

9 import { BasePortalOutlet, CdkPortalOutlet, ComponentPortal, TemplatePortal, DomPortal } from '@angular/cdk/portal';
                                                                               ~~~~~~~~~

** Angular Live Development Server is listening on localhost:4041, open your browser on http://localhost:4041/ **

</code></pre>


## 🌍  Your Environment

**Angular Version:**
<pre><code>
<!-- run `ng version` and paste output below -->
<!-- ✍️-->

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.0-rc.6
Node: 12.6.0
OS: win32 x64

Angular: 9.0.0-rc.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.19
@angular-devkit/build-angular     0.900.0-rc.6
@angular-devkit/build-optimizer   0.900.0-rc.6
@angular-devkit/build-webpack     0.900.0-rc.6
@angular-devkit/core              8.3.19
@angular-devkit/schematics        8.3.19
@angular/cdk                      8.2.3
@angular/fire                     5.2.3
@angular/material                 9.0.0-rc.5
@angular/pwa                      0.803.19
@ngtools/webpack                  9.0.0-rc.6
@schematics/angular               8.3.19
@schematics/update                0.900.0-rc.6
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
<!-- ✍️Is this a browser specific issue? If so, please specify the browser and version. -->

<!-- ✍️Do any of these matter: operating system, IDE, package manager, HTTP server, ...? If so, please mention it below. -->

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/components/issues/17690?

**Comment by JoostK** [comment]
This is indeed due to `@angular/cdk` having a different version than `@angular/material`. More info in angular/components#17690.

**Comment by BrayanVG** [comment]
It has worked, thank you very much, it is rare for pwa to continue at 8 and other things remain at rc.5 even though rc.6 is out
