### ISSUE TITLE
Changedetection method detectChanges re-runs change detection on whole component tree

### ISSUE THREAD

**Issue by rawfox** [angular/angular#34463]
# 🐞 bug report

### Affected Package

 in @angular/core  class ChangeDetectorRef

### Is this a regression?

I don't know.

### Description

 Problem: when detectChanges runs from component A with onPush strategy, Angular runs change detection on whole component tree. It does with and without calling detach 
 method from specified component. Other components has default change detection strategy.
Shouldn't Angular run change detection only on that specific component? detectChanges method runs on that component and it's childrean so why does angular runs on whole component tree?

## 🔬 Minimal Reproduction
Minimal reproduction: https://stackblitz.com/edit/angular-emyzs7

## 🔥 Exception or Error
<pre><code>

after calling detectChanges, Angular re-runs change detection on whole component tree.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.3
Node: 10.16.0
OS: win32 x64
Angular: 8.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
-----------------------------------------------------------
@angular-devkit/architect         0.803.3
@angular-devkit/build-angular     0.803.3
@angular-devkit/build-optimizer   0.803.3
@angular-devkit/build-webpack     0.803.3
@angular-devkit/core              8.3.3
@angular-devkit/schematics        8.3.3
@angular/cdk                      8.0.0
@angular/cli                      8.3.3
@angular/material                 8.0.0
@ngtools/webpack                  8.3.3
@schematics/angular               8.3.3
@schematics/update                0.803.3
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment]
> Shouldn't Angular run change detection only on that specific component? detectChanges method runs on that component and it's childrean so why does angular runs on whole component tree?

Oh, I _think_ I know from where the confusion comes from! Look at this stackblitz where I've removed call to `this.cdr.detectChanges()` from the `HeaderComponent`: https://stackblitz.com/edit/angular-my3cks?file=src/app/header/header.component.ts

Notice that even with the `this.cdr.detectChanges()` removed both `AppComponent` and `MainComponent` as still change detected. In other words it is _not_ `this.cdr.detectChanges()` call that change-detects entire tree! Rather, it is the `setInterval` timer (patched by zone.js) that refreshes the whole application. If you don't want to have `setInterval` triggering CD, run this timer handler outside of Angular zone.

I know it is not immediately obvious / intuitive but it works as designed so I'm going to close this issue for now.

**Comment by rawfox** [comment]
@pkozlowski-opensource  thanks, you helped me a lot :D It was my mistake after all and sorry for caused nuisance.
