### ISSUE TITLE
feat(service-worker): improve default `SwRegistrationStrategy`

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#34464]
**The problem**

In order to avoid negatively affecting the initial page-load time, `@angular/service-worker` will (by default) wait for the [app to stabilize][1], before registering the SW  script. This can lead to a situation where the SW will never be registered when there is a long-running task (such as an interval or recurring timeout), which can often be started by a 3rd-party dependency (without the developer realizing). Related issues: #20970, #34461

This can easily be missed by the developer and there is no other indication other than the SW is not in effect. This is particularly hard to detect, because the SW is typically not used during development and on production builds a previous SW instance might be in effect.

##
**Possible solutions**

Since 4cfba5807, it is possible to overwrite this default behavior by [providing a different `SwRegistrationStrategy`][2]. Things we could do to remedy the situation (non-exhaustive list; up for discussion):

- Change the default strategy to a custom one that wait for the app to stabilize, but registers anyway after X seconds (no matter whether stabilized or not).

- Keep the current behavior, but print a warning after X seconds that the app has not stabilized yet and the SW has not been registered. (This won't change the current behavior, but will make it easier for developers to identify the problem.)

[1]: https://angular.io/api/core/ApplicationRef#is-stable-examples
[2]: https://angular.io/api/service-worker/SwRegistrationOptions#registrationStrategy

**Comment by Splaktar** [comment]
I agree that this needs to be addressed and I like your first idea. 👍

**Comment by sonukapoor** [comment]
@gkalpak  / @Splaktar I will take this one. Please assign this to me, so that I can track it.
